### ISSUE TITLE
[Bug]: [chaos][cluster] Insert data fails when etcd pod recovered running status after been killed 

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#10171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 Insert data still fail when etcd pod recovered running status after been killed.
error message
```
Error: <BaseException: (code=1, message=GetSegmentID failed: SegmentIDAllocator failRemainRequest err:syncSegmentID Failed:server is not serving)>
Traceback (most recent call last):
  File "hello_milvus.py", line 89, in <module>
    hello_milvus()
  File "hello_milvus.py", line 47, in hello_milvus
    collection.insert(
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 525, in insert
    res = conn.insert(collection_name=self._name, entities=entities, ids=None,
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/stub.py", line 61, in handler
    raise e
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/stub.py", line 45, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/stub.py", line 931, in insert
    return handler.bulk_insert(collection_name, entities, partition_name, timeout, **kwargs)
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler
    raise e
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 505, in bulk_insert
    raise err
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 501, in bulk_insert
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=GetSegmentID failed: SegmentIDAllocator failRemainRequest err:syncSegmentID Failed:server is not serving)>
```

### Expected Behavior

All operations can work well

### Steps To Reproduce

```markdown
1. Deploy milvus by helm: cd `tests/python_client/chaos` && `helm install --wait --timeout 360s milvus-chaos milvus/milvus -f cluster-values.yaml  -n=chaos-testing`
2. Run scripts before chaos: `python helllo_milvus.py` 
3. Delete ectd pod: `kubectl delete pod ${pod_name}`
4. Run scripts after chaos: `python hello_milvus.py`
```

### Environment

```markdown
- Milvus version: d54f342
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.0.0rc8.dev9
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Anything else?

[k8s_log.zip](https://github.com/milvus-io/milvus/files/7371099/k8s_log.zip)

**Comment by congqixia** [comment]
in datacoord log file
```
[2021/10/19 06:35:53.525 +00:00] [INFO] [grpclog.go:37] ["[core]Subchannel Connectivity change to CONNECTING"]
[2021/10/19 06:35:53.525 +00:00] [INFO] [grpclog.go:37] ["[core]Subchannel picks a new address \"my-releases-etcd:2379\" to connect"]
[2021/10/19 06:35:53.525 +00:00] [INFO] [grpclog.go:37] ["[balancer]base.baseBalancer: handle SubConn state change: 0xc000390f50, CONNECTING"]
[2021/10/19 06:35:53.647 +00:00] [INFO] [grpclog.go:37] ["[core]Subchannel Connectivity change to CONNECTING"]
[2021/10/19 06:35:53.647 +00:00] [INFO] [grpclog.go:37] ["[core]Subchannel picks a new address \"my-releases-etcd:2379\" to connect"]
[2021/10/19 06:35:53.647 +00:00] [INFO] [grpclog.go:37] ["[balancer]base.baseBalancer: handle SubConn state change: 0xc0005bf0d0, CONNECTING"]
[2021/10/19 06:35:54.234 +00:00] [WARN] [grpclog.go:46] ["[core]grpc: addrConn.createTransport failed to connect to {my-releases-etcd:2379 my-releases-etcd <nil> 0 <nil>}. Err: connection error: desc = \"transport: Error while dialing dial tcp 10.96.207.194:2379: connect: connection refused\". Reconnecting..."]
[2021/10/19 06:35:54.234 +00:00] [INFO] [grpclog.go:37] ["[core]Subchannel Connectivity change to TRANSIENT_FAILURE"]
[2021/10/19 06:35:54.234 +00:00] [INFO] [grpclog.go:37] ["[balancer]base.baseBalancer: handle SubConn state change: 0xc000414050, TRANSIENT_FAILURE"]
[2021/10/19 06:35:54.428 +00:00] [INFO] [grpclog.go:37] ["[core]Subchannel Connectivity change to READY"]
[2021/10/19 06:35:54.428 +00:00] [INFO] [grpclog.go:37] ["[balancer]base.baseBalancer: handle SubConn state change: 0xc0005bed10, READY"]
[2021/10/19 06:35:54.428 +00:00] [INFO] [grpclog.go:37] ["[roundrobin]roundrobinPicker: newPicker called with info: {map[0xc0005bed10:{{my-releases-etcd:2379 my-releases-etcd <nil> 0 <nil>}}]}"]
[2021/10/19 06:35:54.428 +00:00] [INFO] [grpclog.go:37] ["[core]Channel Connectivity change to READY"]
[2021/10/19 06:35:54.505 +00:00] [INFO] [grpclog.go:37] ["[core]Subchannel Connectivity change to CONNECTING"]
[2021/10/19 06:35:54.505 +00:00] [INFO] [grpclog.go:37] ["[core]Subchannel picks a new address \"my-releases-etcd:2379\" to connect"]
[2021/10/19 06:35:54.505 +00:00] [INFO] [grpclog.go:37] ["[balancer]base.baseBalancer: handle SubConn state change: 0xc000391e40, CONNECTING"]
[2021/10/19 06:35:54.507 +00:00] [INFO] [grpclog.go:37] ["[core]Subchannel Connectivity change to READY"]
[2021/10/19 06:35:54.507 +00:00] [INFO] [grpclog.go:37] ["[balancer]base.baseBalancer: handle SubConn state change: 0xc000391e40, READY"]
[2021/10/19 06:35:54.507 +00:00] [INFO] [grpclog.go:37] ["[roundrobin]roundrobinPicker: newPicker called with info: {map[0xc000391e40:{{my-releases-etcd:2379 my-releases-etcd <nil> 0 <nil>}}]}"]
[2021/10/19 06:35:54.507 +00:00] [INFO] [grpclog.go:37] ["[core]Channel Connectivity change to READY"]
[2021/10/19 06:35:54.555 +00:00] [INFO] [grpclog.go:37] ["[core]Subchannel Connectivity change to READY"]
[2021/10/19 06:35:54.555 +00:00] [INFO] [grpclog.go:37] ["[balancer]base.baseBalancer: handle SubConn state change: 0xc000390f50, READY"]
[2021/10/19 06:35:54.555 +00:00] [INFO] [grpclog.go:37] ["[roundrobin]roundrobinPicker: newPicker called with info: {map[0xc000390f50:{{my-releases-etcd:2379 my-releases-etcd <nil> 0 <nil>}}]}"]
[2021/10/19 06:35:54.555 +00:00] [INFO] [grpclog.go:37] ["[core]Channel Connectivity change to READY"]
[2021/10/19 06:35:54.683 +00:00] [INFO] [grpclog.go:37] ["[core]Subchannel Connectivity change to READY"]
[2021/10/19 06:35:54.683 +00:00] [INFO] [grpclog.go:37] ["[balancer]base.baseBalancer: handle SubConn state change: 0xc0005bf0d0, READY"]
[2021/10/19 06:35:54.683 +00:00] [INFO] [grpclog.go:37] ["[roundrobin]roundrobinPicker: newPicker called with info: {map[0xc0005bf0d0:{{my-releases-etcd:2379 my-releases-etcd <nil> 0 <nil>}}]}"]
[2021/10/19 06:35:54.683 +00:00] [INFO] [grpclog.go:37] ["[core]Channel Connectivity change to READY"]
[2021/10/19 06:35:54.807 +00:00] [INFO] [grpclog.go:37] ["[core]Subchannel Connectivity change to CONNECTING"]

```
Datacoord is reconnectng etcd so it's not fully functional at the moment. Will check why does this happen.

**Comment by yanliang567** [comment]
@xiaofan-luan As @sunby commented above, if this is the design, users have to reinstall Milvus if every time etcd is down for 1 minute.  I don;t think this is a high reliable design.  Any ideas?
/assign @xiaofan-luan

**Comment by merqurio** [comment]
We are facing this problem in cluster and standalone modes using rc-7. I can reproduce it tinkering with etcd. 

We have etcd running in 3 nodes with a pod anti-affinity rule says that the pod should not be scheduled onto a node if that node has another etcd pod. I can definitely add more etcd pods but sometimes problems can happen and will happen in production (network partitions, a node/zone rebooting...). Yesterday it happened to us and we haven't recovered yet.  

A one minute policy seems too strict, if reevaluating that is not feasible, there should be a well documented procedure to recover the milvus cluster in these cases. 

Happy to document and create guides about this, but i'm still trying to figure out how to recover. 
Thanks in advance !

**Comment by zhuwenxing** [comment]
If we reinstall milvus (keep pvc), milvus will not report error message. However, milvus will hang at search or get collections entities just like the issue of reinstalling milvus

**Comment by xiaofan-luan** [comment]
> If we reinstall milvus (keep pvc), milvus will not report error message. However, milvus will hang at search or get collections entities just like the issue #7313 #10069 of reinstalling milvus.
> 
> #7313 and #10069 need milvus to keep running a long time or a large size data, but in this test, the issue can be triggered easily in a short time or small size data.

When etcd crashed, the system should be down but is will be recovered in minutes, that's the expectation, are we meet the expectation? @zhuwenxing

**Comment by zhuwenxing** [comment]
> > If we reinstall milvus (keep pvc), milvus will not report error message. However, milvus will hang at search or get collections entities just like the issue #7313 #10069 of reinstalling milvus.
> > #7313 and #10069 need milvus to keep running a long time or a large size data, but in this test, the issue can be triggered easily in a short time or small size data.
> 
> When etcd crashed, the system should be down but is will be recovered in minutes, that's the expectation, are we meet the expectation? @zhuwenxing

No! The milvus system still can't work even though  etcd has recovered for a long time

**Comment by zhuwenxing** [comment]
@xiaofan-luan 

In version `master-20211117-9bd3664`,  in this test, querynode can't be ready (0/1).
![image](https://user-images.githubusercontent.com/12268675/142150376-23430d0f-bbce-4c65-9169-3a7d24b0388e.png)

the log is
[etcd.zip](https://github.com/milvus-io/milvus/files/7552477/etcd.zip)


```
[2021/11/17 07:00:24.649 +00:00] [DEBUG] [client.go:136] ["IndexCoordClient getIndexCoordAddress failed"]
[2021/11/17 07:00:27.650 +00:00] [DEBUG] [client.go:171] ["IndexCoordClient try connect failed"] [error="All attempts results:\nattempt #1:number of indexcoord is incorrect, 0\nattempt #2:number of indexcoord is incorrect, 0\nattempt #3:number of indexcoord is incorrect, 0\nattempt #4:number of indexcoord is incorrect, 0\nattempt #5:number of indexcoord is incorrect, 0\nattempt #6:number of indexcoord is incorrect, 0\nattempt #7:number of indexcoord is incorrect, 0\nattempt #8:number of indexcoord is incorrect, 0\nattempt #9:number of indexcoord is incorrect, 0\nattempt #10:number of indexcoord is incorrect, 0\nattempt #11:number of indexcoord is incorrect, 0\nattempt #12:number of indexcoord is incorrect, 0\nattempt #13:number of indexcoord is incorrect, 0\nattempt #14:number of indexcoord is incorrect, 0\nattempt #15:number of indexcoord is incorrect, 0\nattempt #16:number of indexcoord is incorrect, 0\nattempt #17:number of indexcoord is incorrect, 0\nattempt #18:number of indexcoord is incorrect, 0\nattempt #19:number of indexcoord is incorrect, 0\nattempt #20:number of indexcoord is incorrect, 0\n"]
[2021/11/17 07:00:27.650 +00:00] [DEBUG] [client.go:75] ["IndexcoordClient try reconnect failed"] [error="All attempts results:\nattempt #1:number of indexcoord is incorrect, 0\nattempt #2:number of indexcoord is incorrect, 0\nattempt #3:number of indexcoord is incorrect, 0\nattempt #4:number of indexcoord is incorrect, 0\nattempt #5:number of indexcoord is incorrect, 0\nattempt #6:number of indexcoord is incorrect, 0\nattempt #7:number of indexcoord is incorrect, 0\nattempt #8:number of indexcoord is incorrect, 0\nattempt #9:number of indexcoord is incorrect, 0\nattempt #10:number of indexcoord is incorrect, 0\nattempt #11:number of indexcoord is incorrect, 0\nattempt #12:number of indexcoord is incorrect, 0\nattempt #13:number of indexcoord is incorrect, 0\nattempt #14:number of indexcoord is incorrect, 0\nattempt #15:number of indexcoord is incorrect, 0\nattempt #16:number of indexcoord is incorrect, 0\nattempt #17:number of indexcoord is incorrect, 0\nattempt #18:number of indexcoord is incorrect, 0\nattempt #19:number of indexcoord is incorrect, 0\nattempt #20:number of indexcoord is incorrect, 0\n"]
[2021/11/17 07:00:27.850 +00:00] [DEBUG] [client.go:100] ["IndexCoordClient GetSessions success"] [key=IndexCoord] [msess={}]
[2021/11/17 07:00:27.851 +00:00] [DEBUG] [client.go:103] ["IndexCoordClient msess key not existed"] [key=IndexCoord] ["len of msess"=0]
[2021/11/17 07:00:27.851 +00:00] [DEBUG] [client.go:136] ["IndexCoordClient getIndexCoordAddress failed"]
[2021/11/17 07:00:28.051 +00:00] [DEBUG] [client.go:100] ["IndexCoordClient GetSessions success"] [key=IndexCoord] [msess={}]
[2021/11/17 07:00:28.051 +00:00] [DEBUG] [client.go:103] ["IndexCoordClient msess key not existed"] [key=IndexCoord] ["len of msess"=0]
[2021/11/17 07:00:28.051 +00:00] [DEBUG] [client.go:136] ["IndexCoordClient getIndexCoordAddress failed"]
[2021/11/17 07:00:28.452 +00:00] [DEBUG] [client.go:100] ["IndexCoordClient GetSessions success"] [key=IndexCoord] [msess={}]
[2021/11/17 07:00:28.452 +00:00] [DEBUG] [client.go:103] ["IndexCoordClient msess key not existed"] [key=IndexCoord] ["len of msess"=0]
[2021/11/17 07:00:28.452 +00:00] [DEBUG] [client.go:136] ["IndexCoordClient getIndexCoordAddress failed"]
[2021/11/17 07:00:29.253 +00:00] [DEBUG] [client.go:100] ["IndexCoordClient GetSessions success"] [key=IndexCoord] [msess={}]
[2021/11/17 07:00:29.253 +00:00] [DEBUG] [client.go:103] ["IndexCoordClient msess key not existed"] [key=IndexCoord] ["len of msess"=0]
[2021/11/17 07:00:29.253 +00:00] [DEBUG] [client.go:136] ["IndexCoordClient getIndexCoordAddress failed"]
[2021/11/17 07:00:30.854 +00:00] [DEBUG] [client.go:100] ["IndexCoordClient GetSessions success"] [key=IndexCoord] [msess={}]
[2021/11/17 07:00:30.854 +00:00] [DEBUG] [client.go:103] ["IndexCoordClient msess key not existed"] [key=IndexCoord] ["len of msess"=0]
[2021/11/17 07:00:30.854 +00:00] [DEBUG] [client.go:136] ["IndexCoordClient getIndexCoordAddress failed"]
```

**Comment by zhuwenxing** [comment]
Test this case in version `master-20211119-51b353b` again!
Same error, querynode is always not ready!
```
milvus-chaos-querynode-5c69985fdd-5ngvx               0/1     Running     3          17m
```
The log of describe
```
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  19m                   default-scheduler  Successfully assigned chaos-testing/milvus-chaos-querynode-5c69985fdd-5ngvx to qa-node011.zilliz.local
  Normal   Pulled     13m (x2 over 19m)     kubelet            Container image "milvusdb/milvus-dev:master-20211119-51b353b" already present on machine
  Warning  Unhealthy  13m (x5 over 15m)     kubelet            Liveness probe failed: HTTP probe failed with statuscode: 500
  Normal   Killing    13m                   kubelet            Container querynode failed liveness probe, will be restarted
  Normal   Created    13m (x2 over 19m)     kubelet            Created container querynode
  Normal   Started    13m (x2 over 19m)     kubelet            Started container querynode
  Warning  Unhealthy  3m42s (x45 over 17m)  kubelet            Readiness probe failed: HTTP probe failed with statuscode: 500
```

The log of running `hello_milvus.py`
```
List collections...
Error: <BaseException: (code=1, message=syncTimestamp Failed:context canceled)>
Traceback (most recent call last):
  File "scripts/hello_milvus.py", line 112, in <module>
    hello_milvus(args.host)
  File "scripts/hello_milvus.py", line 28, in hello_milvus
    print(list_collections())
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/orm/utility.py", line 294, in list_collections
    return _get_connection(using).list_collections()
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/stub.py", line 58, in handler
    raise e
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/stub.py", line 42, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/stub.py", line 390, in list_collections
    return handler.list_collections(timeout)
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler
    raise e
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 407, in list_collections
    raise BaseException(status.error_code, status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=syncTimestamp Failed:context canceled)>
```

**Comment by congqixia** [comment]
@zhuwenxing Fix PR has been merged. Please verify.
The expected behavior is:
- When etcd is down for 1 minute or more, all the milvus instances(excluding proxy) should go down(or restart) until etcd goes back.
- When etcd is down less than a minute, the instances should be waiting for etcd.

**Comment by binbinlv** [comment]
@zhuwenxing hello, wenxing, please help to verify and update the status here.  Thanks.

**Comment by zhuwenxing** [comment]
@congqixia 
In version `master-20211124-62bbc9c`,  issue is still not fixed.
Other pods restart as expected when etcd pod was killed. 
![image](https://user-images.githubusercontent.com/12268675/143187782-f09215dd-4d86-4464-8653-93e2f71e94e2.png)
But after deleting etcd pod kill chaos, running `hello_milvus.py` will raise error:
```
Start time: 2021-11-24 14:23:57

List collections...
Error: <BaseException: (code=1, message=syncTimestamp Failed:context canceled)>
Traceback (most recent call last):
  File "scripts/hello_milvus.py", line 112, in <module>
    hello_milvus(args.host)
  File "scripts/hello_milvus.py", line 28, in hello_milvus
    print(list_collections())
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/orm/utility.py", line 294, in list_collections
    return _get_connection(using).list_collections()
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/stub.py", line 58, in handler
    raise e
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/stub.py", line 42, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/stub.py", line 390, in list_collections
    return handler.list_collections(timeout)
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 74, in handler
    raise e
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 66, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 406, in list_collections
    raise BaseException(status.error_code, status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=syncTimestamp Failed:context canceled)>
```
[etcd-pod_kill-11-24.zip](https://github.com/milvus-io/milvus/files/7593257/etcd-pod_kill-11-24.zip)

**Comment by XuanYang-cn** [comment]
After waiting enough time for the pods to get running, it behaves as expected.
/unassign
/assign @zhuwenxing

**Comment by zhuwenxing** [comment]
Verified and passed in version `master-20211126-48bdeb5`
