### ISSUE TITLE
[Bug]: Find search result duplicated

### ISSUE THREAD

**Issue by cydrain** [milvus-io/milvus#10259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In core/unittest/test_c_api.cpp::CApiTest::Reduce,
after search, 2 search results are with same primary key but different distance:
[52] 100354 -9.85499954
[97] 100354 -14.9619999

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

**Comment by binbinlv** [comment]
This is unittest, transfer to @cydrain, thanks.

**Comment by cydrain** [comment]
```
#0  milvus::query::FloatSearchBruteForce (dataset=..., chunk_data_raw=0x7f4b0ed91010, size_per_chunk=10000, bitset=...) at /home/caiyd/vec/milvus/internal/core/src/query/SearchBruteForce.cpp:104
#1  0x00007f4b30628314 in milvus::query::FloatSearch (segment=..., info=..., query_data=0x556a1c126540, num_queries=10, ins_barrier=10000, bitset=..., results=...) at /home/caiyd/vec/milvus/internal/core/src/query/SearchOnGrowing.cpp:93
#2  0x00007f4b30628c4c in milvus::query::SearchOnGrowing (segment=..., ins_barrier=10000, info=..., query_data=0x556a1c126540, num_queries=10, bitset=..., results=...) at /home/caiyd/vec/milvus/internal/core/src/query/SearchOnGrowing.cpp:189
#3  0x00007f4b3033baa1 in milvus::segcore::SegmentGrowingImpl::vector_search (this=0x556a1c124600, vec_count=10000, search_info=..., query_data=0x556a1c126540, query_count=10, timestamp=18446744073709551615, bitset=..., output=...) at /home/caiyd/vec/milvus/internal/core/src/segcore/SegmentGrowingImpl.cpp:295
#4  0x00007f4b3057d90a in milvus::query::ExecPlanNodeVisitor::VectorVisitorImpl<milvus::FloatVector> (this=0x7ffcdf65c9c0, node=...) at /home/caiyd/vec/milvus/internal/core/src/query/visitors/ExecPlanNodeVisitor.cpp:115
#5  0x00007f4b3057c0a5 in milvus::query::ExecPlanNodeVisitor::visit (this=0x7ffcdf65c9c0, node=...) at /home/caiyd/vec/milvus/internal/core/src/query/visitors/ExecPlanNodeVisitor.cpp:158
#6  0x00007f4b3063943a in milvus::query::FloatVectorANNS::accept (this=0x556a1c09ea70, visitor=...) at /home/caiyd/vec/milvus/internal/core/src/query/generated/PlanNode.cpp:20
#7  0x00007f4b303c967e in milvus::query::ExecPlanNodeVisitor::get_moved_result (this=0x7ffcdf65c9c0, node=...) at /home/caiyd/vec/milvus/internal/core/src/query/generated/ExecPlanNodeVisitor.h:49
#8  0x00007f4b303c7457 in milvus::segcore::SegmentInternalInterface::Search (this=0x556a1c124600, plan=0x556a1c0e4d60, placeholder_group=..., timestamp=1) at /home/caiyd/vec/milvus/internal/core/src/segcore/SegmentInterface.cpp:110
#9  0x00007f4b3031888a in Search (c_segment=0x556a1c124600, c_plan=0x556a1c0e4d60, c_placeholder_group=0x556a1c118ac0, timestamp=1, result=0x7ffcdf65cc88) at /home/caiyd/vec/milvus/internal/core/src/segcore/segment_c.cpp:78
#10 0x0000556a1a738fd3 in CApiTest_ReduceRemoveDuplicates_Test::TestBody (this=0x556a1c0e0b40) at /home/caiyd/vec/milvus/internal/core/unittest/test_c_api.cpp:525
#11 0x0000556a1a83a36a in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void> (location=0x556a1a88c58d "the test body", method=<optimized out>, object=0x556a1c0e0b40) at /home/caiyd/vec/milvus/internal/core/cmake-build-debug/thirdparty/gtest/googletest-src/googletest/src/gtest.cc:2443
#12 testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void> (object=0x556a1c0e0b40, method=<optimized out>, location=0x556a1a88c58d "the test body") at /home/caiyd/vec/milvus/internal/core/cmake-build-debug/thirdparty/gtest/googletest-src/googletest/src/gtest.cc:2479
#13 0x0000556a1a825b4a in testing::Test::Run (this=0x556a1c0e0b40) at /home/caiyd/vec/milvus/internal/core/cmake-build-debug/thirdparty/gtest/googletest-src/googletest/src/gtest.cc:2517
#14 0x0000556a1a825c88 in testing::TestInfo::Run (this=0x556a1c0ac840) at /home/caiyd/vec/milvus/internal/core/cmake-build-debug/thirdparty/gtest/googletest-src/googletest/src/gtest.cc:2693
#15 0x0000556a1a825d95 in testing::TestCase::Run (this=0x556a1c0bb150) at /home/caiyd/vec/milvus/internal/core/cmake-build-debug/thirdparty/gtest/googletest-src/googletest/src/gtest.cc:2811
#16 0x0000556a1a8360a8 in testing::internal::UnitTestImpl::RunAllTests (this=this@entry=0x556a1c0aad50) at /home/caiyd/vec/milvus/internal/core/cmake-build-debug/thirdparty/gtest/googletest-src/googletest/src/gtest.cc:5177
#17 0x0000556a1a836271 in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (location=0x556a1a88ddb8 "auxiliary test code (environments or event listeners)", method=<optimized out>, object=<optimized out>) at /home/caiyd/vec/milvus/internal/core/cmake-build-debug/thirdparty/gtest/googletest-src/googletest/src/gtest.cc:2443
#18 testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (location=0x556a1a88ddb8 "auxiliary test code (environments or event listeners)", method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x556a1a835c50 <testing::internal::UnitTestImpl::RunAllTests()>, object=0x556a1c0aad50) at /home/caiyd/vec/milvus/internal/core/cmake-build-debug/thirdparty/gtest/googletest-src/googletest/src/gtest.cc:2479
#19 testing::UnitTest::Run (this=0x556a1ab25480 <testing::UnitTest::GetInstance()::instance>) at /home/caiyd/vec/milvus/internal/core/cmake-build-debug/thirdparty/gtest/googletest-src/googletest/src/gtest.cc:4786
#20 0x0000556a1a6f8cb2 in RUN_ALL_TESTS () at /home/caiyd/vec/milvus/internal/core/cmake-build-debug/thirdparty/gtest/googletest-src/googletest/include/gtest/gtest.h:2341
#21 0x0000556a1a6f8c41 in main (argc=1, argv=0x7ffcdf65d148) at /home/caiyd/vec/milvus/internal/core/unittest/init_gtest.cpp:24
#22 0x00007f4b2dde4bf7 in __libc_start_main (main=0x556a1a6f8c1a <main(int, char**)>, argc=3, argv=0x7ffcdf65d148, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffcdf65d138) at ../csu/libc-start.c:310
#23 0x0000556a1a6f8b3a in _start ()
```

**Comment by cydrain** [comment]
Not a real issue, the duplicated primary keys are for different queries.
[52] belongs to query 5, [97] belongs to query 9.
