### ISSUE TITLE
[Bug]: No param check for "travel_timestamp"

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#10265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Searching with non-valid value for parameter "travel_timestamp": No pymilvus error 

ValueError: Value out of range: -1000

1. value < 0
2. value >  maximum range
3.  Not valid type

### Expected Behavior

Report error replacing python error

### Steps To Reproduce

```markdown
res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0", travel_timestamp=-1)
```

### Environment

```markdown
- Milvus version: latest
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc8.dev11
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

**Comment by DragonDriver** [comment]
already fixed.
/assign @binbinlv

**Comment by binbinlv** [comment]
Verified, and fixed.

milvus:  a6160bc
pymilvus: 2.0.0rc8.dev26

```
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0", travel_timestamp=-1000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 676, in search
    partition_names, output_fields, timeout, round_decimal, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 61, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 45, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 1045, in search
    travel_timestamp=kwargs.get("travel_timestamp", 0),
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/check.py", line 335, in check_pass_param
    _raise_param_error(key, value)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/check.py", line 269, in _raise_param_error
    raise ParamError(f"`{param_name}` value {param_value} is illegal")
pymilvus.client.exceptions.ParamError: `travel_timestamp` value -1000 is illegal
```
