### ISSUE TITLE
[Bug]: Insert failed with exception "GetSegmentID failed: SegmentIDAllocator failRemainRequest err:syncSegmentID Failed:DataCoord is not serving"

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#10633]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 73343ca
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc8.dev14
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Running nightly CI, large numbers of cases failed for insert failure: [standalone]

https://jenkins.zilliz.cc/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/204/artifacts

Test logs:
```
[2021-10-25T15:48:26.131Z] [2021-10-25 15:20:17 - ERROR - pymilvus.client.grpc_handler]: Error: <BaseException: (code=1, message=GetSegmentID failed: SegmentIDAllocator failRemainRequest err:syncSegmentID Failed:DataCoord is not serving)> (grpc_handler.py:59)
[2021-10-25T15:48:26.131Z] [2021-10-25 15:20:17 - ERROR - ci_test]: Traceback (most recent call last):
[2021-10-25T15:48:26.131Z]   File "/milvus/tests/python_client/utils/api_request.py", line 18, in inner_wrapper
[2021-10-25T15:48:26.131Z]     res = func(*args, **kwargs)
[2021-10-25T15:48:26.131Z]   File "/milvus/tests/python_client/utils/api_request.py", line 45, in api_request
[2021-10-25T15:48:26.131Z]     return func(*arg, **kwargs)
[2021-10-25T15:48:26.131Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 526, in insert
[2021-10-25T15:48:26.131Z]     partition_name=partition_name, timeout=timeout, **kwargs)
[2021-10-25T15:48:26.131Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 61, in handler
[2021-10-25T15:48:26.131Z]     raise e
[2021-10-25T15:48:26.131Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 45, in handler
[2021-10-25T15:48:26.131Z]     return func(self, *args, **kwargs)
[2021-10-25T15:48:26.131Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 931, in insert
[2021-10-25T15:48:26.131Z]     return handler.bulk_insert(collection_name, entities, partition_name, timeout, **kwargs)
[2021-10-25T15:48:26.131Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler
[2021-10-25T15:48:26.131Z]     raise e
[2021-10-25T15:48:26.131Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
[2021-10-25T15:48:26.132Z]     return func(self, *args, **kwargs)
[2021-10-25T15:48:26.132Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 505, in bulk_insert
[2021-10-25T15:48:26.132Z]     raise err
[2021-10-25T15:48:26.132Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 501, in bulk_insert
[2021-10-25T15:48:26.132Z]     raise BaseException(response.status.error_code, response.status.reason)
[2021-10-25T15:48:26.132Z] pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=GetSegmentID failed: SegmentIDAllocator failRemainRequest err:syncSegmentID Failed:DataCoord is not serving)>
```
Milvus logs: 0.log

```
2021-10-25T15:19:27.476472778Z stdout F [2021/10/25 15:19:27.476 +00:00] [ERROR] [query_collection.go:297] ["mismatch collectionID when addGlobalSegmentInfo,  manager collectionID =  428651357583179777 ,  segmentInfo collectionID =  428651356180709377\n"] [stack="github.com/milvus-io/milvus/internal/querynode.(*queryCollection).consumeQuery\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/query_collection.go:297"]
2021-10-25T15:19:27.477031685Z stderr F fatal error: unexpected signal during runtime execution
2021-10-25T15:19:27.481472007Z stderr F [signal SIGSEGV: segmentation violation code=0x2 addr=0x7fab0c000b98 pc=0x7fab0c000b98]
2021-10-25T15:19:27.481487415Z stderr F
2021-10-25T15:19:27.481493942Z stderr F runtime stack:
2021-10-25T15:19:27.481497511Z stderr F runtime.throw(0x26569ae, 0x2a)
2021-10-25T15:19:27.481501831Z stderr F         /usr/local/go/src/runtime/panic.go:1116 +0x72
2021-10-25T15:19:27.4815046Z stderr F runtime.sigpanic()
2021-10-25T15:19:27.481506614Z stderr F         /usr/local/go/src/runtime/signal_unix.go:704 +0x4ac
2021-10-25T15:19:27.48150875Z stderr F
2021-10-25T15:19:27.481510642Z stderr F goroutine 1927745 [syscall]:
2021-10-25T15:19:27.481512425Z stderr F runtime.cgocall(0x17bd6ba, 0xc030042b80, 0xc02f85b210)
2021-10-25T15:19:27.481514602Z stderr F         /usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc030042b50 sp=0xc030042b18 pc=0x729d1b
2021-10-25T15:19:27.481517312Z stderr F github.com/milvus-io/milvus/internal/querynode._Cfunc_ReduceSearchResultsAndFillData(0x7fab88031120, 0xc00ea7a0c0, 0x4, 0x0, 0x0)
2021-10-25T15:19:27.481519898Z stderr F         _cgo_gotypes.go:742 +0x56 fp=0xc030042b80 sp=0xc030042b50 pc=0x178d476
2021-10-25T15:19:27.481522845Z stderr F github.com/milvus-io/milvus/internal/querynode.reduceSearchResultsAndFillData.func1(0xc018a756c0, 0xc00ea7a0c0, 0x4, 0x2, 0x3)
2021-10-25T15:19:27.481524821Z stderr F         /go/src/github.com/milvus-io/milvus/internal/querynode/reduce.go:49 +0x8f fp=0xc030042bc0 sp=0xc030042b80 pc=0x17a5a2f
2021-10-25T15:19:27.481527475Z stderr F github.com/milvus-io/milvus/internal/querynode.reduceSearchResultsAndFillData(0xc018a756c0, 0xc007423d40, 0x4, 0x4, 0x4, 0x0, 0x0)
2021-10-25T15:19:27.481529419Z stderr F         /go/src/github.com/milvus-io/milvus/internal/querynode/reduce.go:49 +0x178 fp=0xc030042c78 sp=0xc030042bc0 pc=0x179a278
2021-10-25T15:19:27.481531356Z stderr F github.com/milvus-io/milvus/internal/querynode.(*queryCollection).search(0xc01dfcae10, 0x285ba00, 0xc02fd46120, 0x0, 0x0)
2021-10-25T15:19:27.481535276Z stderr F         /go/src/github.com/milvus-io/milvus/internal/querynode/query_collection.go:1005 +0x159a fp=0xc0300434c8 sp=0xc030042c78 pc=0x17766ba
2021-10-25T15:19:27.481537124Z stderr F github.com/milvus-io/milvus/internal/querynode.(*queryCollection).receiveQueryMsg(0xc01dfcae10, 0x285ba00, 0xc02fd46120, 0x0, 0x0)
2021-10-25T15:19:27.481539412Z stderr F         /go/src/github.com/milvus-io/milvus/internal/querynode/query_collection.go:462 +0x1ac5 fp=0xc030043ec0 sp=0xc0300434c8 pc=0x176f425
2021-10-25T15:19:27.481547995Z stderr F github.com/milvus-io/milvus/internal/querynode.(*queryCollection).consumeQuery(0xc01dfcae10)
2021-10-25T15:19:27.481550312Z stderr F         /go/src/github.com/milvus-io/milvus/internal/querynode/query_collection.go:284 +0x11e fp=0xc030043fd8 sp=0xc030043ec0 pc=0x176cf5e
2021-10-25T15:19:27.481552074Z stderr F runtime.goexit()
2021-10-25T15:19:27.481553926Z stderr F         /usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc030043fe0 sp=0xc030043fd8 pc=0x796641
2021-10-25T15:19:27.481556002Z stderr F created by github.com/milvus-io/milvus/internal/querynode.(*queryCollection).start
2021-10-25T15:19:27.481594078Z stderr F         /go/src/github.com/milvus-io/milvus/internal/querynode/query_collection.go:132 +0xa7
2021-10-25T15:19:27.48159619Z stderr F
2021-10-25T15:19:27.4815985Z stderr F goroutine 1 [chan receive, 22 minutes]:
2021-10-25T15:19:27.481600211Z stderr F github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run(0xc000b8feff, 0x1, 0x0, 0x0)
2021-10-25T15:19:27.481601982Z stderr F         /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:469 +0x2f8
2021-10-25T15:19:27.481603829Z stderr F main.main()
2021-10-25T15:19:27.481605749Z stderr F         /go/src/github.com/milvus-io/milvus/cmd/main.go:286 +0x649
2021-10-25T15:19:27.481607772Z stderr F
2021-10-25T15:19:27.481609704Z stderr F goroutine 55 [select]:
2021-10-25T15:19:27.481611525Z stderr F github.com/uber/jaeger-client-go.(*RemotelyControlledSampler).pollControllerWithTicker(0xc000407040, 0xc000140730)
2021-10-25T15:19:27.481613344Z stderr F         /go/pkg/mod/github.com/uber/jaeger-client-go@v2.25.0+incompatible/sampler_remote.go:144 +0xdf
2021-10-25T15:19:27.481615239Z stderr F github.com/uber/jaeger-client-go.(*RemotelyControlledSampler).pollController(0xc000407040)
2021-10-25T15:19:27.481616958Z stderr F         /go/pkg/mod/github.com/uber/jaeger-client-go@v2.25.0+incompatible/sampler_remote.go:139 +0x73
2021-10-25T15:19:27.481618654Z stderr F created by github.com/uber/jaeger-client-go.NewRemotelyControlledSampler
2021-10-25T15:19:27.481620641Z stderr F         /go/pkg/mod/github.com/uber/jaeger-client-go@v2.25.0+incompatible/sampler_remote.go:86 +0x125
```

### Expected Behavior

No exception

**Comment by binbinlv** [comment]
Verified through latest several nightly tests, it is fixed.
