### ISSUE TITLE
[Bug]: [chaos][proxy]create collection failed when one of proxy pods injected pod failure chaos

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#11035]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc8.dev23
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When one of proxy pods injected pod failure chaos, chaos test failed.
Create collection failed.

### Expected Behavior

Since proxy has multi pods, when one of them fails, all operations should still work well.

### Steps To Reproduce

```markdown
Run Github action https://github.com/milvus-io/milvus/actions/workflows/pod-failure-chaos-test.yaml
```

### Anything else?

Error message
```
[2021-11-01 17:42:52 - ERROR - pymilvus.client.grpc_handler]: Error: <BaseException: (code=1, message=syncTimestamp Failed:All attempts results:
attempt #1:context canceled
attempt #2:context canceled
)> (grpc_handler.py:59)
[2021-11-01 17:42:52 - ERROR - pymilvus.client.grpc_handler]: Error: <BaseException: (code=1, message=syncTimestamp Failed:All attempts results:
attempt #1:context canceled
attempt #2:context canceled
)> (grpc_handler.py:59)
[2021-11-01 17:42:52 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/zilliz/workspace/backup/milvus/tests/python_client/utils/api_request.py", line 19, in inner_wrapper
    res_str = str(res)
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 148, in __repr__
    'partitions': [json.loads(p.__repr__()) for p in self.partitions],
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 766, in partitions
    partition_strs = conn.list_partitions(self._name)
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/stub.py", line 61, in handler
    raise e
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/stub.py", line 45, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/stub.py", line 567, in list_partitions
    return handler.list_partitions(collection_name, timeout)
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler
    raise e
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 456, in list_partitions
    raise BaseException(status.error_code, status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=syncTimestamp Failed:All attempts results:
attempt #1:context canceled
attempt #2:context canceled
```

**Comment by zhuwenxing** [comment]
@cydrain 
[Uploading proxy.zip…]()

**Comment by zhuwenxing** [comment]
This test is to test that the Milvus can work well if one of proxy pods failure.
But when running `test_chaos.py`, there are some error message in logs 
```
[2021-11-16 15:23:55 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0], [[0.09358621934583634, 0.12633857263820206, 0.07860463063354693, 0.017727953169202098, 0.14963292158907043, 0.0005600727772687151, 0.0988626029125439, 0.06300515845982878, 0.01111276388297122, 0.08052045659278449, ......, kwargs: {'timeout': 20} (api_request.py:44)
[2021-11-16 15:24:14 - ERROR - pymilvus.client.grpc_handler]:
Addr [10.96.3.89:19530] query
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1637047454.533700000","description":"Error received from peer ipv4:127.0.0.1:7890","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
	{'API start': '2021-11-16 15:23:29.012827', 'RPC start': '2021-11-16 15:23:54.528252', 'RPC error': '2021-11-16 15:24:14.534531'} (grpc_handler.py:73)
[2021-11-16 15:24:14 - ERROR - pymilvus.client.grpc_handler]:
Addr [10.96.3.89:19530] _execute_search_requests
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1637047454.570947000","description":"Error received from peer ipv4:127.0.0.1:7890","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Deadline Exceeded","grpc_status":4}"
```
In my view, there should not be such error messages in the whole process.
However, if I inject a pod failure chaos by manual，then run `hello_milvus.py`, the whole process is OK.

So this issue's priority maybe should not be set as urgent
@cydrain  @xiaofan-luan

**Comment by cydrain** [comment]
See lots of warnings in proxy's log.
It seems that when one proxy node down and up again, rootcoord did not recognize this new proxy node.
```
[2021/11/16 07:26:45.640 +00:00] [WARN] [proxy.go:289] [sendChannelsTimeTickLoop.UpdateChannelTimeTick] [ErrorCode=UnexpectedError] [Reason="Skip ChannelTimeTickMsg from un-recognized proxy node 11"]
[2021/11/16 07:26:45.840 +00:00] [WARN] [proxy.go:289] [sendChannelsTimeTickLoop.UpdateChannelTimeTick] [ErrorCode=UnexpectedError] [Reason="Skip ChannelTimeTickMsg from un-recognized proxy node 11"]
[2021/11/16 07:26:46.040 +00:00] [WARN] [proxy.go:289] [sendChannelsTimeTickLoop.UpdateChannelTimeTick] [ErrorCode=UnexpectedError] [Reason="Skip ChannelTimeTickMsg from un-recognized proxy node 11"]
[2021/11/16 07:26:46.241 +00:00] [WARN] [proxy.go:289] [sendChannelsTimeTickLoop.UpdateChannelTimeTick] [ErrorCode=UnexpectedError] [Reason="Skip ChannelTimeTickMsg from un-recognized proxy node 11"]
```

**Comment by zhuwenxing** [comment]
There appear some error messages in one of three tests, but it seems that the error doesn't affect the result, because all operations work well！

**Comment by zhuwenxing** [comment]
verified and passed in version `1dcd06c` and Github action job https://github.com/milvus-io/milvus/runs/4575901797?check_suite_focus=true
