### ISSUE TITLE
[Bug]: Querycoordinator crashed after decresing number of replicas of its worker nodes

### ISSUE THREAD

**Issue by parsa-ra** [milvus-io/milvus#11156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.0rc8
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): v2.0.0rc8 
- OS(Ubuntu or CentOS): Ubuntu 20.04.3 LTS
- CPU/Memory: cluster
- GPU: None
- Others: None
```

### Current Behavior

When decreasing the number of querynode replicas (i.e. from 10 to 6 ) after applying the new values the queryCoordinator will crash and its state will change to CrashLoopBackOff

Check out the logs of the QueryCoordinator: 
```bash 
parano@parano-ThinkPad-E14:~$ kubectl logs -f mil-milvus-querycoord-7bcd5c78fd-759r8 -n mil-test --tail=50
[2021/11/03 05:25:48.935 +00:00] [DEBUG] [session_util.go:82] ["Sessiont connect to etcd success"]
[2021/11/03 05:25:48.936 +00:00] [WARN] [paramtable.go:54] ["Failed to parse dataCoord.grpc.clientMaxSendSize, set to default"] [dataCoord.grpc.clientMaxSendSize=] [error="strconv.Atoi: parsing \"\": invalid syntax"]
[2021/11/03 05:25:48.936 +00:00] [DEBUG] [paramtable.go:63] [initClientMaxSendSize] [dataCoord.grpc.clientMaxSendSize=104857600]
[2021/11/03 05:25:48.936 +00:00] [WARN] [paramtable.go:77] ["Failed to parse dataCoord.grpc.clientMaxRecvSize, set to default"] [dataCoord.grpc.clientMaxRecvSize=] [error="strconv.Atoi: parsing \"\": invalid syntax"]
[2021/11/03 05:25:48.937 +00:00] [DEBUG] [paramtable.go:86] [initClientMaxRecvSize] [dataCoord.grpc.clientMaxRecvSize=104857600]
[2021/11/03 05:25:48.937 +00:00] [DEBUG] [session_util.go:261] ["SessionUtil GetSessions"] [prefix=DataCoord] [resp="{\"header\":{\"cluster_id\":6512979360485748541,\"member_id\":14709806716859994569,\"revision\":60825,\"raft_term\":4},\"kvs\":[{\"key\":\"YnktZGV2L21ldGEvc2Vzc2lvbi9EYXRhQ29vcmQ=\",\"create_revision\":60658,\"mod_revision\":60658,\"version\":1,\"value\":\"eyJTZXJ2ZXJJRCI6MjgsIlNlcnZlck5hbWUiOiJEYXRhQ29vcmQiLCJBZGRyZXNzIjoibWlsLW1pbHZ1cy1kYXRhY29vcmQ6MTMzMzMiLCJFeGNsdXNpdmUiOnRydWV9\",\"lease\":999091996569128408}],\"count\":1}"]
[2021/11/03 05:25:48.937 +00:00] [DEBUG] [client.go:93] ["DataCoordClient try reconnect "] [address=mil-milvus-datacoord:13333]
[2021/11/03 05:25:48.937 +00:00] [INFO] [grpclog.go:37] ["[core]parsed scheme: \"\""]
[2021/11/03 05:25:48.937 +00:00] [INFO] [grpclog.go:37] ["[core]scheme \"\" not registered, fallback to default scheme"]
[2021/11/03 05:25:48.937 +00:00] [INFO] [grpclog.go:37] ["[core]ccResolverWrapper: sending update to cc: {[{mil-milvus-datacoord:13333  <nil> 0 <nil>}] <nil> <nil>}"]
[2021/11/03 05:25:48.937 +00:00] [INFO] [grpclog.go:37] ["[core]ClientConn switching balancer to \"pick_first\""]
[2021/11/03 05:25:48.937 +00:00] [INFO] [grpclog.go:37] ["[core]Channel switches to new LB policy \"pick_first\""]
[2021/11/03 05:25:48.937 +00:00] [INFO] [grpclog.go:37] ["[core]Subchannel Connectivity change to CONNECTING"]
[2021/11/03 05:25:48.937 +00:00] [INFO] [grpclog.go:37] ["[core]Subchannel picks a new address \"mil-milvus-datacoord:13333\" to connect"]
[2021/11/03 05:25:48.937 +00:00] [INFO] [grpclog.go:37] ["[core]pickfirstBalancer: UpdateSubConnState: 0xc0001cce80, {CONNECTING <nil>}"]
[2021/11/03 05:25:48.938 +00:00] [INFO] [grpclog.go:37] ["[core]Channel Connectivity change to CONNECTING"]
[2021/11/03 05:25:48.938 +00:00] [INFO] [grpclog.go:37] ["[core]Subchannel Connectivity change to READY"]
[2021/11/03 05:25:48.938 +00:00] [INFO] [grpclog.go:37] ["[core]pickfirstBalancer: UpdateSubConnState: 0xc0001cce80, {READY <nil>}"]
[2021/11/03 05:25:48.938 +00:00] [INFO] [grpclog.go:37] ["[core]Channel Connectivity change to READY"]
[2021/11/03 05:25:48.938 +00:00] [DEBUG] [service.go:153] ["QueryCoord try to wait for DataCoord ready"]
[2021/11/03 05:25:48.941 +00:00] [DEBUG] [service.go:162] ["QueryCoord report DataCoord ready"]
[2021/11/03 05:25:48.941 +00:00] [DEBUG] [service.go:165] [QueryCoord] [State=Initializing]
[2021/11/03 05:25:48.941 +00:00] [DEBUG] [query_coord.go:93] ["query coordinator try to connect etcd"]
[2021/11/03 05:25:48.941 +00:00] [INFO] [grpclog.go:37] ["[core]parsed scheme: \"etcd-endpoints\""]
[2021/11/03 05:25:48.941 +00:00] [INFO] [grpclog.go:37] ["[core]ccResolverWrapper: sending update to cc: {[{mil-etcd:2379 mil-etcd <nil> 0 <nil>}] 0xc0001b0ce0 <nil>}"]
[2021/11/03 05:25:48.941 +00:00] [INFO] [grpclog.go:37] ["[core]ClientConn switching balancer to \"round_robin\""]
[2021/11/03 05:25:48.941 +00:00] [INFO] [grpclog.go:37] ["[core]Channel switches to new LB policy \"round_robin\""]
[2021/11/03 05:25:48.941 +00:00] [INFO] [grpclog.go:37] ["[balancer]base.baseBalancer: got new ClientConn state: {{[{mil-etcd:2379 mil-etcd <nil> 0 <nil>}] 0xc0001b0ce0 <nil>} <nil>}"]
[2021/11/03 05:25:48.941 +00:00] [INFO] [grpclog.go:37] ["[core]Subchannel Connectivity change to CONNECTING"]
[2021/11/03 05:25:48.941 +00:00] [DEBUG] [query_coord.go:99] ["query coordinator try to connect etcd success"]
[2021/11/03 05:25:48.941 +00:00] [DEBUG] [etcd_kv.go:63] ["LoadWithPrefix "] [prefix=by-dev/meta/queryCoord-collectionMeta]
[2021/11/03 05:25:48.941 +00:00] [INFO] [grpclog.go:37] ["[core]Subchannel picks a new address \"mil-etcd:2379\" to connect"]
[2021/11/03 05:25:48.941 +00:00] [INFO] [grpclog.go:37] ["[balancer]base.baseBalancer: handle SubConn state change: 0xc0001cd380, CONNECTING"]
[2021/11/03 05:25:48.941 +00:00] [INFO] [grpclog.go:37] ["[core]Channel Connectivity change to CONNECTING"]
[2021/11/03 05:25:48.942 +00:00] [INFO] [grpclog.go:37] ["[core]Subchannel Connectivity change to READY"]
[2021/11/03 05:25:48.942 +00:00] [INFO] [grpclog.go:37] ["[balancer]base.baseBalancer: handle SubConn state change: 0xc0001cd380, READY"]
[2021/11/03 05:25:48.942 +00:00] [INFO] [grpclog.go:37] ["[roundrobin]roundrobinPicker: newPicker called with info: {map[0xc0001cd380:{{mil-etcd:2379 mil-etcd <nil> 0 <nil>}}]}"]
[2021/11/03 05:25:48.942 +00:00] [INFO] [grpclog.go:37] ["[core]Channel Connectivity change to READY"]
[2021/11/03 05:25:48.943 +00:00] [DEBUG] [etcd_kv.go:63] ["LoadWithPrefix "] [prefix=by-dev/meta/queryCoord-segmentMeta]
[2021/11/03 05:25:48.945 +00:00] [DEBUG] [etcd_kv.go:63] ["LoadWithPrefix "] [prefix=by-dev/meta/queryCoord-queryChannel]
[2021/11/03 05:25:48.946 +00:00] [ERROR] [query_coord.go:102] ["query coordinator init meta failed"] [error="line 1.0: unexpected byte 0x12"] [stack="github.com/milvus-io/milvus/internal/querycoord.(*QueryCoord).Init\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/query_coord.go:102\ngithub.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/service.go:166\ngithub.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/service.go:77\ngithub.com/milvus-io/milvus/cmd/components.(*QueryCoord).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/query_coord.go:41\ngithub.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runQueryCoord.func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:156"]
panic: line 1.0: unexpected byte 0x12

goroutine 142 [running]:
github.com/milvus-io/milvus/cmd/components.(*QueryCoord).Run(...)
	/go/src/github.com/milvus-io/milvus/cmd/components/query_coord.go:42
github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runQueryCoord.func1(0x0, 0x27238c0, 0xc0004220c0, 0xc0003c6e18, 0xc0003260a0)
	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:156 +0x16d
created by github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runQueryCoord
	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:141 +0xb0
```

### Expected Behavior

Well, this should not happen ... 

### Steps To Reproduce

```markdown
1. Deploy cluster
2. decrease the number of replica node for QueryNodes
3. Apply the new values
```

### Anything else?
The cluster uses a PVC storage.

**Comment by xiaofan-luan** [comment]
Hi parsa, is this rc7 or master? Seems we didn't release rc8 yet? are you also doing any upgrade or it is the same version?

**Comment by parsa-ra** [comment]
I believe there is something wrong with the [helm-charts](https://github.com/milvus-io/milvus-helm/blob/master/charts/milvus/values.yaml)

**Comment by yanliang567** [comment]
@LoveEachDay could you please help to look at this issue?

/assign @LoveEachDay 
/unassign

**Comment by yanliang567** [comment]
@ThreadDao  could you please help to check this issue on latest master?
/assign @ThreadDao 
/unassign @LoveEachDay

**Comment by ThreadDao** [comment]
Follow the steps below to deploy with helm `master-20211203-ffd05eb ` or operator `master-20211202-ed546d0` and failed to reproduce this problem:
1. deploy milvus cluster with 10 queryNode replicas
2. do some operations (pytest test_query.py -n 6)
3. update queryNode.replicas to 6 and apply
4. rerun query cases, no pods crash

**Comment by yanliang567** [comment]
@parsa-ra could you please retry on latest master? it seems that it did not reproduce any more.
/assign @parsa-ra

**Comment by parsa-ra** [comment]
> @parsa-ra could you please retry on latest master? it seems that it did not reproduce any more. /assign @parsa-ra

Yeah for sure, I'll keep you posted ...
