### ISSUE TITLE
[Bug]: [chaos][standalone]Milvus hangs at creating index after standalone pod kill chaos deleted

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#11275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: `91be4b1`
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):2.0.0rc8.dev23
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Milvus hangs at search after standalone pod kill chaos deleted

### Expected Behavior

All operations work well

### Steps To Reproduce

```markdown
1. cd `tests/python_client/chaos`

2. modify param value and run script `chaos_test.sh`
pod="standalone"
chaos_type="pod_kill"

A common way to reproduce
deploy a standalone milvus by helm 
use `kubectl delete` to kill standalone pod multi times (about 5~10times in 1 min)
run hello_milvus.py to check the results


```

### Anything else?

[standalone.log](https://github.com/milvus-io/milvus/files/7474385/standalone.log)

**Comment by zhuwenxing** [comment]
update logs
[standalone.zip](https://github.com/milvus-io/milvus/files/7480389/standalone.zip)

**Comment by xiaofan-luan** [comment]
@cydrain could you please a look ?

**Comment by zhuwenxing** [comment]
new logs @cydrain 
[standalone.zip](https://github.com/milvus-io/milvus/files/7544616/standalone.zip)

**Comment by cydrain** [comment]
```
[2021/11/16 08:23:59.946 +00:00] [ERROR] [services.go:468] ["get collection info from master failed"] [collectionID=429143060243283969] [error="state code = Initializing"] [stack="github.com/milvus-io/milvus/internal/datacoord.(*Server).GetRecoveryInfo\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/services.go:468\ngithub.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).GetRecoveryInfo\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:253\ngithub.com/milvus-io/milvus/internal/proto/datapb._DataCoord_GetRecoveryInfo_Handler.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proto/datapb/data_coord.pb.go:3356\ngithub.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38\ngithub.com/milvus-io/milvus/internal/proto/datapb._DataCoord_GetRecoveryInfo_Handler\n\t/go/src/github.com/milvus-io/milvus/internal/proto/datapb/data_coord.pb.go:3358\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1286\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1609\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:934"]
[2021/11/16 08:23:59.948 +00:00] [ERROR] [services.go:468] ["get collection info from master failed"] [collectionID=429143069575610369] [error="state code = Initializing"] [stack="github.com/milvus-io/milvus/internal/datacoord.(*Server).GetRecoveryInfo\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/services.go:468\ngithub.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).GetRecoveryInfo\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:253\ngithub.com/milvus-io/milvus/internal/proto/datapb._DataCoord_GetRecoveryInfo_Handler.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proto/datapb/data_coord.pb.go:3356\ngithub.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38\ngithub.com/milvus-io/milvus/internal/proto/datapb._DataCoord_GetRecoveryInfo_Handler\n\t/go/src/github.com/milvus-io/milvus/internal/proto/datapb/data_coord.pb.go:3358\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1286\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1609\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:934"]
[2021/11/16 08:23:59.949 +00:00] [ERROR] [services.go:468] ["get collection info from master failed"] [collectionID=429143070597971969] [error="state code = Initializing"] [stack="github.com/milvus-io/milvus/internal/datacoord.(*Server).GetRecoveryInfo\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/services.go:468\ngithub.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).GetRecoveryInfo\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:253\ngithub.com/milvus-io/milvus/internal/proto/datapb._DataCoord_GetRecoveryInfo_Handler.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proto/datapb/data_coord.pb.go:3356\ngithub.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38\ngithub.com/milvus-io/milvus/internal/proto/datapb._DataCoord_GetRecoveryInfo_Handler\n\t/go/src/github.com/milvus-io/milvus/internal/proto/datapb/data_coord.pb.go:3358\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1286\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1609\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:934"]
[2021/11/16 08:25:22.879 +00:00] [ERROR] [query_collection.go:297] ["mismatch collectionID when addGlobalSegmentInfo,  manager collectionID =  429143060243283969 ,  segmentInfo collectionID =  429143069575610369\n"] [stack="github.com/milvus-io/milvus/internal/querynode.(*queryCollection).consumeQuery\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/query_collection.go:297"]
[2021/11/16 08:25:22.879 +00:00] [ERROR] [query_collection.go:297] ["mismatch collectionID when addGlobalSegmentInfo,  manager collectionID =  429143060243283969 ,  segmentInfo collectionID =  429143070597971969\n"] [stack="github.com/milvus-io/milvus/internal/querynode.(*queryCollection).consumeQuery\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/query_collection.go:297"]
[2021/11/16 08:25:24.562 +00:00] [DEBUG] [task.go:1580] [Proxy::searchTask::PreExecute] [plan.OutputFieldIds="[100,101]"] [plan="vector_anns:<field_id:102 predicates:<unary_range_expr:<column_info:<field_id:100 data_type:Int64 is_primary_key:true > op:GreaterThan value:<int64_val:100 > > > query_info:<topk:5 metric_type:\"L2\" search_params:\"{\\\"nprobe\\\":10}\" round_decimal:-1 > placeholder_tag:\"$0\" > output_field_ids:100 output_field_ids:101 "]
[2021/11/16 08:26:44.669 +00:00] [DEBUG] [task.go:1901] [Proxy] ["searchTask PostExecute Loop exit caused by ctx.Done"=429143128528128970]
[2021/11/16 08:26:44.669 +00:00] [DEBUG] [time_recorder.go:76] ["searchTask PostExecute: done (80106ms)"]
[2021/11/16 08:26:44.669 +00:00] [ERROR] [task_scheduler.go:463] ["Failed to post-execute task: searchTask:wait to finish failed, timeout: 429143128528128970"] [traceID=7233e2477a0a5377] [stack="github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:463"]
```

**Comment by zhuwenxing** [comment]
In version `fd45a7e` built in Nov 16,  the test will hang at getting collection entities about 10 min, after this ,search can return results very quickly.

new logs
[standalone.zip](https://github.com/milvus-io/milvus/files/7545236/standalone.zip)

**Comment by zhuwenxing** [comment]
This issue can be reproduced almost every time, so set it as urgent.

**Comment by zhuwenxing** [comment]
version: `9bd3664`
after deleting chaos and Milvus recovered, if we insert data (this step can work well ) and then do other operations (such as 
 flush search), the standalone pod will crash and restart.
```
goroutine 633 [running]:
github.com/milvus-io/milvus/internal/querycoord.assignInternalTask(0x28ed520, 0xc00382c2d0, 0x5f4b4b3f5cb0d41, 0x290edc0, 0xc0038248c0, 0x2910300, 0xc00172f0e0, 0x0, 0x0, 0xc000b8e808, ...)
	/go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:2073 +0xfa
github.com/milvus-io/milvus/internal/querycoord.(*handoffTask).execute(0xc0038248c0, 0x28ed520, 0xc00382c2d0, 0x1, 0x1)
	/go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:1597 +0x10ae
github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processTask(0xc001f4a960, 0x290edc0, 0xc0038248c0, 0x0, 0x0)
	/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:546 +0x6d4
github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).scheduleLoop(0xc001f4a960)
	/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:659 +0x1305
created by github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).Start
	/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:892 +0x65
```

**Comment by xige-16** [comment]
> 9bd3664

this bug has been fixed on master branch

**Comment by xige-16** [comment]
pr #11796 may has fixed the issue， @zhuwenxing trouble you check it

**Comment by zhuwenxing** [comment]
> pr #11796 may has fixed the issue， @zhuwenxing trouble you check it

in version `master-20211118-27715c1`, standalone pod will not restart anymore. However, after recovering from pod kill, getting collection entities, creating index, and searching all cost much longer time than normal situations (I would better say it hangs). 

[standalone-pok-kill-11-19.zip](https://github.com/milvus-io/milvus/files/7568631/standalone-pok-kill-11-19.zip)

/assign @cydrain

**Comment by zhuwenxing** [comment]
> > pr #11796 may has fixed the issue， @zhuwenxing trouble you check it
> 
> in version `master-20211118-27715c1`, standalone pod will not restart anymore. However, after recovering from pod kill, getting collection entities, creating index, and searching all cost much longer time than normal situations (I would better say it hangs).
> 
> [standalone-pok-kill-11-19.zip](https://github.com/milvus-io/milvus/files/7568631/standalone-pok-kill-11-19.zip)
> 
> /assign @cydrain

But if we create a new collection and do the same operations, the operations will work well.
```
--------------------------------------------------------------------------------------- live log setup ----------------------------------------------------------------------------------------
[2021-11-19 15:59:36 - INFO - ci_test]: ################################################################################ (conftest.py:165)
[2021-11-19 15:59:36 - INFO - ci_test]: [initialize_milvus] Log cleaned up, start testing... (conftest.py:166)
[2021-11-19 15:59:36 - INFO - ci_test]: [setup_class] Start setup class... (client_base.py:44)
[2021-11-19 15:59:36 - INFO - ci_test]: *********************************** setup *********************************** (client_base.py:50)
[2021-11-19 15:59:36 - INFO - ci_test]: [setup_method] Start setup test case test_milvus_default. (client_base.py:51)
---------------------------------------------------------------------------------------- live log call ----------------------------------------------------------------------------------------
[2021-11-19 15:59:38 - INFO - ci_test]: assert create collection: 1.1047630310058594, init_entities: 0 (test_e2e.py:24)
[2021-11-19 15:59:53 - INFO - ci_test]: assert insert: 15.39885687828064 (test_e2e.py:31)
[2021-11-19 15:59:56 - INFO - ci_test]: assert flush: 2.6599600315093994, entities: 3000 (test_e2e.py:39)
[2021-11-19 15:59:58 - INFO - ci_test]: assert search: 0.5111057758331299 (test_e2e.py:50)
[2021-11-19 16:00:18 - INFO - ci_test]: assert index entities: 6000 (test_e2e.py:57)
[2021-11-19 16:00:21 - INFO - ci_test]: assert index: 2.710942029953003 (test_e2e.py:64)
[2021-11-19 16:00:22 - INFO - ci_test]: assert load: 1.2246770858764648 (test_e2e.py:71)
[2021-11-19 16:00:23 - INFO - ci_test]: assert search: 0.398651123046875 (test_e2e.py:78)
[2021-11-19 16:00:23 - INFO - ci_test]: assert query result 3: 0.3181788921356201 (test_e2e.py:85)


-------------------------------------------------------------------------------------- live log teardown --------------------------------------------------------------------------------------
[2021-11-19 16:00:23 - INFO - ci_test]: *********************************** teardown *********************************** (client_base.py:61)
[2021-11-19 16:00:23 - INFO - ci_test]: [teardown_method] Start teardown test case test_milvus_default... (client_base.py:62)
[2021-11-19 16:00:25 - INFO - ci_test]: [teardown_class] Start teardown class... (client_base.py:47)
```

**Comment by zhuwenxing** [comment]
@congqixia This behavior is much same as  the behavior of #7313

**Comment by zhuwenxing** [comment]
[standalone-pod_kill-chaos-test-2021-11-22-19-23-19.zip](https://github.com/milvus-io/milvus/files/7580553/standalone-pod_kill-chaos-test-2021-11-22-19-23-19.zip)

[2021-11-22 19:15:33 - INFO - ci_test]: chaos injected (test_chaos.py:165)
[2021-11-22 19:16:34 - INFO - ci_test]: chaos deleted (test_chaos.py:191)
hello_milvus.py start time: 2021-11-22 19:18:20

**Comment by zhuwenxing** [comment]
> milvus version `master-20211122-0f2b7d1`
> 
> [standalone-pod_kill-chaos-test-2021-11-22-19-23-19.zip](https://github.com/milvus-io/milvus/files/7580553/standalone-pod_kill-chaos-test-2021-11-22-19-23-19.zip)
> 
> [2021-11-22 19:15:33 - INFO - ci_test]: chaos injected (test_chaos.py:165) [2021-11-22 19:16:34 - INFO - ci_test]: chaos deleted (test_chaos.py:191) hello_milvus.py start time: 2021-11-22 19:18:20

in this test, the process mainly hangs at search.
```
+ timeout 5m python scripts/hello_milvus.py --host 10.96.50.204

Start time: 2021-11-22 19:18:20

List collections...
['Checker__M0yPYKkG', 'Checker__JnFggJrR', 'Checker__ZmVrlBZy', 'Checker__xc4hTl9C', 'hello_milvus', 'Checker__ia6VKF1v', 'Checker__THRC9xa4']

Create collection...

List collections...
['Checker__ZmVrlBZy', 'Checker__xc4hTl9C', 'hello_milvus', 'Checker__ia6VKF1v', 'Checker__THRC9xa4', 'Checker__M0yPYKkG', 'Checker__JnFggJrR']

Insert 3000 vectors cost 1.288625955581665 seconds

Get collection entities...
6000

Get collection entities cost 2.6748223304748535 seconds

Create index...

load collection...

load collection cost 0.031244993209838867 seconds

Search...
+ echo 'e2e test fail'
e2e test fail
```

**Comment by cydrain** [comment]
milvus version master-20211122-0f2b7d1

standalone-pod_kill-chaos-test-2021-11-22-19-23-19.zip

```
[2021/11/22 11:16:32.306 +00:00] [ERROR] [root_coord.go:1357] ["DescribeCollection failed"] ["collection name"=] [msgID=0] [error="can't find collection id : 429281702084345857"] [stack="github.com/milvus-io/milvus/internal/rootcoord.(*Core).DescribeCollection\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:1357\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).DescribeCollection\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:320\ngithub.com/milvus-io/milvus/internal/proto/rootcoordpb._RootCoord_DescribeCollection_Handler.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proto/rootcoordpb/root_coord.pb.go:915\ngithub.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38\ngithub.com/milvus-io/milvus/internal/proto/rootcoordpb._RootCoord_DescribeCollection_Handler\n\t/go/src/github.com/milvus-io/milvus/internal/proto/rootcoordpb/root_coord.pb.go:917\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1286\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1609\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:934"]
[2021/11/22 11:16:32.306 +00:00] [ERROR] [root_coord.go:1357] ["DescribeCollection failed"] ["collection name"=] [msgID=0] [error="can't find collection id : 429281702084345857"] [stack="github.com/milvus-io/milvus/internal/rootcoord.(*Core).DescribeCollection\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:1357\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).DescribeCollection\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:320\ngithub.com/milvus-io/milvus/internal/proto/rootcoordpb._RootCoord_DescribeCollection_Handler.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proto/rootcoordpb/root_coord.pb.go:915\ngithub.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38\ngithub.com/milvus-io/milvus/internal/proto/rootcoordpb._RootCoord_DescribeCollection_Handler\n\t/go/src/github.com/milvus-io/milvus/internal/proto/rootcoordpb/root_coord.pb.go:917\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1286\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1609\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:934"]
[2021/11/22 11:18:26.882 +00:00] [DEBUG] [task.go:1562] [Proxy::searchTask::PreExecute] [plan.OutputFieldIds="[100,101]"] [plan="vector_anns:<field_id:102 predicates:<unary_range_expr:<column_info:<field_id:100 data_type:Int64 is_primary_key:true > op:GreaterThan value:<int64_val:100 > > > query_info:<topk:5 metric_type:\"L2\" search_params:\"{\\\"nprobe\\\":10}\" round_decimal:-1 > placeholder_tag:\"$0\" > output_field_ids:100 output_field_ids:101 "]
[2021/11/22 11:23:19.715 +00:00] [DEBUG] [task.go:1868] [Proxy] ["searchTask PostExecute Loop exit caused by ctx.Done"=429281745717169097]
[2021/11/22 11:23:19.715 +00:00] [DEBUG] [time_recorder.go:76] ["searchTask PostExecute: done (292832ms)"]
[2021/11/22 11:23:19.715 +00:00] [ERROR] [task_scheduler.go:468] ["Failed to post-execute task: searchTask:wait to finish failed, timeout: 429281745717169097"] [traceID=cb9773b600e7e07] [stack="github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:468"]
```

**Comment by xige-16** [comment]
A retry called by grpc will take at least 12 minutes

**Comment by xige-16** [comment]
There are still locks on retry called by different grpc
```
func (c *Client) getGrpcClientFunc() (querypb.QueryNodeClient, error) {
	c.grpcClientMtx.RLock()
	if c.grpcClient != nil {
		defer c.grpcClientMtx.RUnlock()
		return c.grpcClient, nil
	}
	c.grpcClientMtx.RUnlock()

	c.grpcClientMtx.Lock()
	defer c.grpcClientMtx.Unlock()

	if c.grpcClient != nil {
		return c.grpcClient, nil
	}

	// FIXME(dragondriver): how to handle error here?
	// if we return nil here, then we should check if client is nil outside,
	err := c.connect(retry.Attempts(20))
	if err != nil {
		return nil, err
	}

	return c.grpcClient, nil
}
```

**Comment by zhuwenxing** [comment]
In version `master-20211124-6c4c0ef`, this issue still exists.


[standalone-pod_kill-11-24-16-19-00.zip](https://github.com/milvus-io/milvus/files/7593897/standalone-pod_kill-11-24-16-19-00.zip)

[2021-11-22 14:06:36 - INFO - ci_test]: chaos injected (test_chaos.py:165)
[2021-11-24 16:12:42 - INFO - ci_test]: chaos deleted (test_chaos.py:191)
start time: 2021-11-24 16:15:00   : run hello_milvus.py after chaos

**Comment by zhuwenxing** [comment]
@xige-16 
However, #10357 this issue was verified and passed. So there are some other causes for this issue.

**Comment by zhuwenxing** [comment]
In version master-20211124-6c4c0ef, the main problem is that getting collection entities costs a lot of time
```
Start time: 2021-11-24 17:50:58

List collections...
['Checker__bY0uCXYZ', 'Checker__xjsAhTPo', 'Checker__TOg52F7L', 'Checker__w2ZJfgoC', 'CreateChecker__bnt2nkhl', 'hello_milvus', 'Checker__km4ctkJ0', 'Checker__ni2oLXpP']

Create collection...

List collections...
['Checker__km4ctkJ0', 'Checker__ni2oLXpP', 'Checker__bY0uCXYZ', 'Checker__xjsAhTPo', 'Checker__TOg52F7L', 'Checker__w2ZJfgoC', 'CreateChecker__bnt2nkhl', 'hello_milvus']

Insert 3000 vectors cost 1.3865940570831299 seconds

Get collection entities...
9000

Get collection entities cost 190.7297968864441 seconds

Create index...

load collection...

load collection cost 2.2428858280181885 seconds

Search...
(distance: 0.0, id: 2998) -14.0
(distance: 13.607627868652344, id: 265) -15.0
(distance: 13.74374008178711, id: 2277) -13.0
(distance: 13.8092622756958, id: 310) -17.0
(distance: 14.17446517944336, id: 2048) -18.0
(distance: 0.0, id: 2999) -11.0
(distance: 14.373578071594238, id: 2390) -12.0
(distance: 15.628049850463867, id: 2830) -18.0
(distance: 15.628683090209961, id: 2060) -15.0
(distance: 15.760536193847656, id: 525) -17.0
search latency = 0.4833s
{'count': 2, 'random_value': -13.0}
{'count': 4, 'random_value': -20.0}
{'count': 6, 'random_value': -16.0}
{'count': 8, 'random_value': -11.0}
```

**Comment by xige-16** [comment]
[2021/11/24 08:15:02.537 +00:00] [DEBUG] [impl.go:1603] ["Flush Done"] [] [role=proxy] [msgID=429324160682429375] [timestamp=429324160865927169] [db=] [collections="[hello_milvus]"]
[2021/11/24 08:19:27.931 +00:00] [DEBUG] [server.go:683] ["flush segment complete"] [id=429324109080166402]

**Comment by zhuwenxing** [comment]
@sunby 
version: `master-20211124-1a8e2e5`

```
Start time: 2021-11-24 20:15:13

List collections...
['Checker__IzdobFok', 'Checker__pxZFb9JM', 'Checker__rzPg4hDd', 'hello_milvus', 'Checker__Vtjvb8g6', 'Checker__40UYY6Kg', 'Checker__ykiqe9W1']

Create collection...

List collections...
['Checker__Vtjvb8g6', 'Checker__40UYY6Kg', 'Checker__ykiqe9W1', 'Checker__IzdobFok', 'Checker__pxZFb9JM', 'Checker__rzPg4hDd', 'hello_milvus']

Insert 3000 vectors cost 0.6829068660736084 seconds

Get collection entities...
9000

Get collection entities cost 256.76664185523987 seconds

Create index...

load collection...

load collection cost 2.3088438510894775 seconds

Search...
(distance: 0.0, id: 2998) -14.0
(distance: 13.456015586853027, id: 876) -19.0
(distance: 15.002704620361328, id: 2882) -16.0
(distance: 15.437359809875488, id: 2513) -12.0
(distance: 15.684139251708984, id: 359) -12.0
(distance: 0.0, id: 2999) -15.0
(distance: 14.095157623291016, id: 2671) -20.0
(distance: 14.418627738952637, id: 1154) -20.0
(distance: 14.470747947692871, id: 1606) -13.0
(distance: 14.622243881225586, id: 1433) -15.0
search latency = 0.4315s
{'count': 2, 'random_value': -13.0}
{'count': 4, 'random_value': -14.0}
{'count': 6, 'random_value': -12.0}
{'count': 8, 'random_value': -20.0}
```
[standalone-pod_kill-11-24-29-21-00.zip](https://github.com/milvus-io/milvus/files/7595545/standalone-pod_kill-11-24-29-21-00.zip)

**Comment by bigsheeper** [comment]
the same reason with #12190

**Comment by zhuwenxing** [comment]
@sunby 
In version `master-20211125-858e95f`
```
Start time: 2021-11-25 12:04:55

List collections...
['Checker__ErbIXOCa', 'Checker__3PfImmXJ', 'Checker__jkbmm43g', 'Checker__pVkaxrIU', 'hello_milvus', 'Checker__E62qogWt', 'Checker__GBthfkXY']

Create collection...

List collections...
['Checker__E62qogWt', 'Checker__GBthfkXY', 'Checker__ErbIXOCa', 'Checker__3PfImmXJ', 'Checker__jkbmm43g', 'Checker__pVkaxrIU', 'hello_milvus']

Insert 3000 vectors cost 1.6623618602752686 seconds

Get collection entities...
6000

Get collection entities cost 236.89950299263 seconds

Create index...

load collection...

load collection cost 2.227540969848633 seconds

Search...
(distance: 0.0, id: 2998) -19.0
(distance: 15.774225234985352, id: 1971) -16.0
(distance: 15.897157669067383, id: 953) -16.0
(distance: 15.925368309020996, id: 2901) -13.0
(distance: 15.96180534362793, id: 455) -14.0
(distance: 0.0, id: 2999) -14.0
(distance: 13.896049499511719, id: 939) -18.0
(distance: 14.348217010498047, id: 2493) -18.0
(distance: 14.599384307861328, id: 2131) -19.0
(distance: 14.810193061828613, id: 2038) -15.0
search latency = 0.2830s
{'count': 2, 'random_value': -11.0}
{'count': 4, 'random_value': -13.0}
{'count': 6, 'random_value': -13.0}
{'count': 8, 'random_value': -12.0}
```
[standalone-pod_kill-11-24-16-19-00.zip](https://github.com/milvus-io/milvus/files/7600597/standalone-pod_kill-11-24-16-19-00.zip)

**Comment by zhuwenxing** [comment]
@czs007


Now getting collections entities time cost is normal, however, creating index time(more than 5mins) is not normal.
[standalone-pod_kill-chaos-test-2021-11-26-18-28-31.zip](https://github.com/milvus-io/milvus/files/7608342/standalone-pod_kill-chaos-test-2021-11-26-18-28-31.zip)

**Comment by zhuwenxing** [comment]
In version `master-20211130-2a0d646`, this issue is still open.
@czs007 Please help to check
[ standalone-pod_kill-11-30-15-21-00.zip](https://github.com/milvus-io/milvus/files/7623985/standalone-pod_kill-11-30-15-21-00.zip)

**Comment by zhuwenxing** [comment]
> 
But it was not 100% happened, for now, it happened once in 4 tries.

**Comment by zhuwenxing** [comment]
The failed case:
[standalone-pod_kill-11-30-17-00-00.zip](https://github.com/milvus-io/milvus/files/7625229/standalone-pod_kill-11-30-17-00-00.zip)

**Comment by sunby** [comment]
IndexCoord may assign task to a dead proxyNode and it will retry many times. @czs007 is fixing it.

**Comment by czs007** [comment]
@zhuwenxing please recheck this. The Pr Had already merged 5 days ago.

**Comment by zhuwenxing** [comment]
This issue has not happened so far, so remove priority/critical-urgent.
If the issue does not happen after several tests, then it will be closed

**Comment by zhuwenxing** [comment]
The same issue reproduced in `master-20211219-1dcd06c`
Milvus hangs at creating index after standalone pod kill chaos deleted.
But it will work well after waiting for about 20min
log:
[test-standalone-pod-kill-12-20-13-20-00.zip](https://github.com/milvus-io/milvus/files/7742793/test-standalone-pod-kill-12-20-13-20-00.zip)

**Comment by yanliang567** [comment]
@czs007 could you please take a look at this issue again?
/assign @czs007 
/unassign @zhuwenxing

**Comment by zhuwenxing** [comment]
as you can see: *Create index cost 1463.3308727741241 seconds*
```
+ echo 'e2e test fail'
e2e test fail
+ python scripts/hello_milvus.py --host 10.96.250.92

Start time: 2021-12-20 16:54:55

List collections...
['Checker__lvz9xU33', 'Checker__NKX3khB3', 'CreateChecker__HamOiiks', 'Checker__Pvx67MNp', 'Checker__klL0gH0r', 'Checker__MM2lv574', 'Checker__DTG8IrCw', 'hello_milvus']

Create collection...

List collections...
['Checker__MM2lv574', 'Checker__DTG8IrCw', 'Checker__Pvx67MNp', 'Checker__lvz9xU33', 'Checker__NKX3khB3', 'CreateChecker__HamOiiks', 'hello_milvus', 'Checker__klL0gH0r']

Insert 3000 vectors cost 0.9331257343292236 seconds

Get collection entities...
6000

Get collection entities cost 3.1523478031158447 seconds

Create index...

Create index cost 1463.3308727741241 seconds

load collection...

load collection cost 0.026205062866210938 seconds

Search...
(distance: 0.0, id: 2998) -14.0
(distance: 12.930343627929688, id: 2561) -11.0
(distance: 13.657979011535645, id: 2121) -11.0
(distance: 13.903371810913086, id: 156) -19.0
(distance: 14.198887825012207, id: 2874) -11.0
(distance: 0.0, id: 2999) -12.0
(distance: 14.501724243164062, id: 1164) -16.0
(distance: 14.6956205368042, id: 1698) -18.0
(distance: 14.913738250732422, id: 348) -13.0
(distance: 15.122392654418945, id: 1035) -19.0
search latency = 0.4653s
{'count': 2, 'random_value': -13.0}
{'count': 4, 'random_value': -13.0}
{'count': 6, 'random_value': -15.0}
{'count': 8, 'random_value': -15.0}
```

**Comment by czs007** [comment]
@zhuwenxing  please retry.

**Comment by zhuwenxing** [comment]
In GitHub action and local k8s env， this issue is not reproduced. So remove the urgent label, but keep it open until it has not been reproduced several times

**Comment by zhuwenxing** [comment]
Not reproduced for a long time, so close it
