### ISSUE TITLE
[Bug]: [benchmark][cluster] search error: No Available Query node result

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#11406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20211106-436d530
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-2.0.0rc8.dev5
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

client log:
```
[2021-11-06 16:08:51,308] [   DEBUG] - Milvus create_index run in 109.44s (milvus_benchmark.client:52)
[2021-11-06 16:08:51,312] [    INFO] - None (milvus_benchmark.client:290)
[2021-11-06 16:08:51,312] [    INFO] - {'index_type': 'flat', 'metric_type': None, 'index_param': None} (milvus_benchmark.runners.accuracy:251)
[2021-11-06 16:08:51,313] [    INFO] - Start load collection: glove_200_angular (milvus_benchmark.runners.accuracy:252)
[2021-11-06 16:09:10,049] [   DEBUG] - Milvus load_collection run in 18.74s (milvus_benchmark.client:52)
[2021-11-06 16:09:10,050] [    INFO] - End load collection: glove_200_angular (milvus_benchmark.runners.accuracy:255)
[2021-11-06 16:09:10,288] [    INFO] - Start run case (milvus_benchmark.main:87)
[2021-11-06 16:09:12,531] [   ERROR] - Error: <BaseException: (code=1, message=No Available Query node result, filter reason Search failed, C runtime error detected, error code = 1, error msg = Error in milvus::knowhere::ConfAd
: id 428923895712975508)> (pymilvus.client.grpc_handler:59)
[2021-11-06 16:09:12,532] [   ERROR] - Error: <BaseException: (code=1, message=No Available Query node result, filter reason Search failed, C runtime error detected, error code = 1, error msg = Error in milvus::knowhere::ConfAd
: id 428923895712975508)> (pymilvus.client.grpc_handler:59)
[2021-11-06 16:09:12,536] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 94, in run_suite
    result = runner.run_case(case_metric, **case)
  File "/src/milvus_benchmark/runners/accuracy.py", line 265, in run_case
    self.milvus.query(case_param["vector_query"], filter_query=case_param["filter_query"])
  File "/src/milvus_benchmark/client.py", line 48, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 317, in query
    result = self._milvus.search(tmp_collection_name, **params)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 61, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 45, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 1071, in search
    partition_names, output_fields, timeout, round_decimal, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 94, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 620, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 587, in _execute_search_requests
    raise pre_err
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 578, in _execute_search_requests
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=No Available Query node result, filter reason Search failed, C runtime error detected, error code = 1, error msg = Error in milvus::knowhere::ConfAd
: id 428923895712975508)>
 (milvus_benchmark.main:97)
[2021-11-06 16:09:12,537] [    INFO] - None (milvus_benchmark.main:98)
[2021-11-06 16:09:12,537] [   DEBUG] - {'type': 'ann_accuracy', 'value': {}} (milvus_benchmark.main:106)
[2021-11-06 16:09:12,538] [   DEBUG] - {'_version': '0.1', '_type': 'case', 'run_id': 1636214697, 'mode': 'local', 'server': <milvus_benchmark.metrics.models.server.Server object at 0x7f87a86115c0>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware object at 0x7f876519cf98>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7f876519ceb8>, 'status': 'RUN_FAILED', 'err_message': '<BaseException: (code=1, message=No Available Query node result, filter reason Search failed, C runtime error detected, error code = 1, error msg = Error in milvus::knowhere::ConfAd\n: id 428923895712975508)>\nTraceback (most recent call last):\n  File "main.py", line 94, in run_suite\n    result = runner.run_case(case_metric, **case)\n  File "/src/milvus_benchmark/runners/accuracy.py", line 265, in run_case\n    self.milvus.query(case_param["vector_query"], filter_query=case_param["filter_query"])\n  File "/src/milvus_benchmark/client.py", line 48, in wrapper\n    result = func(*args, **kwargs)\n  File "/src/milvus_benchmark/client.py", line 317, in query\n    result = self._milvus.search(tmp_collection_name, **params)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 61, in handler\n    raise e\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 45, in handler\n    return func(self, *args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 1071, in search\n    partition_names, output_fields, timeout, round_decimal, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler\n    raise e\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler\n    return func(self, *args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 94, in handler\n    return func(self, *args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 620, in search\n    return self._execute_search_requests(requests, timeout, **_kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler\n    raise e\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler\n    return func(self, *args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 587, in _execute_search_requests\n    raise pre_err\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 578, in _execute_search_requests\n    raise BaseException(response.status.error_code, response.status.reason)\npymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=No Available Query node result, filter reason Search failed, C runtime error detected, error code = 1, error msg = Error in milvus::knowhere::ConfAd\n: id 428923895712975508)>\n', 'collection': {'dimension': 200, 'metric_type': 'ip', 'dataset_name': 'glove_200_angular', 'shards_num': None}, 'index': {'index_type': 'ivf_flat', 'index_param': {'nlist': 1024}}, 'search': {'nq': 10000, 'topk': 10, 'search_param': {'nprobe': 1}, 'filter': []}, 'run_params': None, 'metrics': {'type': 'ann_accuracy', 'value': {}}, 'datetime': '2021-11-06 16:04:57.516798', 'type': 'metric'} (milvus_benchmark.metric.api:29)
```

server: 
```
NAME                                                              READY   STATUS      RESTARTS   AGE     IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-cron-1636214400-5-etcd-0                                1/1     Running     0          3m      10.97.17.154   qa-node014.zilliz.local   <none>           <none>
benchmark-cron-1636214400-5-etcd-1                                1/1     Running     0          3m      10.97.17.152   qa-node014.zilliz.local   <none>           <none>
benchmark-cron-1636214400-5-etcd-2                                1/1     Running     0          3m      10.97.17.157   qa-node014.zilliz.local   <none>           <none>
benchmark-cron-1636214400-5-milvus-datacoord-5f69b9b594-5h6rs     1/1     Running     0          3m      10.97.8.4      qa-node006.zilliz.local   <none>           <none>
benchmark-cron-1636214400-5-milvus-datanode-78b47db7bf-r49ml      1/1     Running     0          2m59s   10.97.11.11    qa-node009.zilliz.local   <none>           <none>
benchmark-cron-1636214400-5-milvus-indexcoord-675795cf47-j7txs    1/1     Running     0          3m      10.97.10.181   qa-node008.zilliz.local   <none>           <none>
benchmark-cron-1636214400-5-milvus-indexnode-68fd6b4b64-k4dws     1/1     Running     0          2m59s   10.97.17.139   qa-node014.zilliz.local   <none>           <none>
benchmark-cron-1636214400-5-milvus-proxy-57876fc664-s94fg         1/1     Running     0          3m      10.97.10.176   qa-node008.zilliz.local   <none>           <none>
benchmark-cron-1636214400-5-milvus-querycoord-8449d747b-b4jjk     1/1     Running     0          3m      10.97.10.175   qa-node008.zilliz.local   <none>           <none>
benchmark-cron-1636214400-5-milvus-querynode-748c5946b-r9qk6      1/1     Running     0          3m      10.97.10.183   qa-node008.zilliz.local   <none>           <none>
benchmark-cron-1636214400-5-milvus-rootcoord-78bfbd8f4b-dmh8v     1/1     Running     0          3m      10.97.8.2      qa-node006.zilliz.local   <none>           <none>
benchmark-cron-1636214400-5-minio-0                               1/1     Running     0          3m      10.97.10.174   qa-node008.zilliz.local   <none>           <none>
benchmark-cron-1636214400-5-minio-1                               1/1     Running     0          3m      10.97.10.177   qa-node008.zilliz.local   <none>           <none>
benchmark-cron-1636214400-5-minio-2                               1/1     Running     0          3m      10.97.10.178   qa-node008.zilliz.local   <none>           <none>
benchmark-cron-1636214400-5-minio-3                               1/1     Running     0          3m      10.97.10.179   qa-node008.zilliz.local   <none>           <none>
benchmark-cron-1636214400-5-pulsar-autorecovery-7fbbd955c4vkc9z   1/1     Running     0          3m      10.97.8.5      qa-node006.zilliz.local   <none>           <none>
benchmark-cron-1636214400-5-pulsar-bastion-5567946888-xr94b       1/1     Running     0          3m      10.97.8.3      qa-node006.zilliz.local   <none>           <none>
benchmark-cron-1636214400-5-pulsar-bookkeeper-0                   1/1     Running     0          3m      10.97.8.8      qa-node006.zilliz.local   <none>           <none>
benchmark-cron-1636214400-5-pulsar-bookkeeper-1                   1/1     Running     0          57s     10.97.6.179    qa-node004.zilliz.local   <none>           <none>
benchmark-cron-1636214400-5-pulsar-broker-6d5ccd5df4-q5ch7        1/1     Running     0          2m59s   10.97.15.52    qa-node012.zilliz.local   <none>           <none>
benchmark-cron-1636214400-5-pulsar-proxy-84dbfcc96-2n7w5          2/2     Running     0          2m59s   10.97.13.62    qa-node010.zilliz.local   <none>           <none>
benchmark-cron-1636214400-5-pulsar-zookeeper-0                    1/1     Running     0          3m      10.97.9.254    qa-node007.zilliz.local   <none>           <none>
benchmark-cron-1636214400-5-pulsar-zookeeper-1                    1/1     Running     0          2m42s   10.97.6.177    qa-node004.zilliz.local   <none>           <none>
benchmark-cron-1636214400-5-pulsar-zookeeper-2                    1/1     Running     0          2m28s   10.97.6.178    qa-node004.zilliz.local   <none>           <none>
benchmark-cron-1636214400-5-pulsar-zookeeper-metadata-zzjf5       0/1     Completed   0          3m      10.97.10.180   qa-node008.zilliz.local   <none>           <none>
```

### Steps To Reproduce

```markdown
argo task:benchmark-cron-1636214400

test yaml:
client-configmap:client-acc-glove-ivf-flat
server-configmap:server-cluster-8c16m
```

### Anything else?

client-acc-glove-ivf-flat：
```
ann_accuracy:
    collections:
      -
        source_file: /test/milvus/ann_hdf5/glove-200-angular.hdf5
        collection_name: glove_200_angular
        index_types: ['ivf_flat']
        index_params:
          nlist: [1024]
        top_ks: [10]
        nqs: [10000]
        search_params:
          nprobe: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512]
```

**Comment by cydrain** [comment]
[query_node.log](https://github.com/milvus-io/milvus/files/7494748/query_node.log)
```
[2021/11/06 16:09:11.833 +00:00] [WARN] [query_collection.go:944] ["Search failed, C runtime error detected, error code = 1, error msg = Error in milvus::knowhere::ConfAd"]
[2021/11/06 16:09:11.833 +00:00] [WARN] [query_collection.go:564] ["Search failed, C runtime error detected, error code = 1, error msg = Error in milvus::knowhere::ConfAd"]
```

**Comment by cydrain** [comment]
cannot find where this error msg is printed out in segcore

**Comment by cydrain** [comment]
https://argo-test.zilliz.cc/workflows/qa/yanliang-test-cleanup-s4svb?tab=workflow&nodeId=yanliang-test-cleanup-s4svb-2477813711

**Comment by yanliang567** [comment]
jigao reproduce this issue, and @DragonDriver is working on it.
/assign @DragonDriver 
/unassign @cydrain @wangting0128

**Comment by DragonDriver** [comment]
Already fixed, pls retry this. @wangting0128

**Comment by yanliang567** [comment]
not repro in latest nightly, close for now
