### ISSUE TITLE
[Bug]: Error I/O operation on closed file occured on CI

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#11679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-11633/1/pipeline
```
[2021-11-11T03:39:14.738Z] [gw1] [ 99%] FAILED testcases/entity/test_insert.py::TestInsertMultiCollections::test_insert_entity_create_index_another[get_simple_index0] [create_path] folder(/milvus/_artifacts/tests/pytest_logs) is not exist.
[2021-11-11T03:39:14.738Z] [create_path] create path now...
[2021-11-11T03:39:14.739Z] Can not use /milvus/_artifacts/tests/pytest_logs/ci_test_log.debug or /milvus/_artifacts/tests/pytest_logs/ci_test_log.log or /milvus/_artifacts/tests/pytest_logs/ci_test_log.err to log. error : [Errno 21] Is a directory: '/milvus/tests/python_client'
[2021-11-11T03:39:20.011Z] --- Logging error ---
[2021-11-11T03:39:20.012Z] Traceback (most recent call last):
[2021-11-11T03:39:20.012Z]   File "/usr/local/lib/python3.6/logging/__init__.py", line 996, in emit
[2021-11-11T03:39:20.012Z]     stream.write(msg)
[2021-11-11T03:39:20.012Z] ValueError: I/O operation on closed file.
[2021-11-11T03:39:20.012Z] Call stack:
[2021-11-11T03:39:20.012Z]   File "<string>", line 1, in <module>
[2021-11-11T03:39:20.012Z]   File "<string>", line 8, in <module>
[2021-11-11T03:39:20.012Z]   File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 1554, in serve
[2021-11-11T03:39:20.012Z]     WorkerGateway(io=io, id=id, _startcount=2).serve()
[2021-11-11T03:39:20.012Z]   File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 1060, in serve
[2021-11-11T03:39:20.012Z]     self._execpool.integrate_as_primary_thread()
[2021-11-11T03:39:20.012Z]   File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 267, in integrate_as_primary_thread
[2021-11-11T03:39:20.012Z]     self._perform_spawn(reply)
[2021-11-11T03:39:20.012Z]   File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 285, in _perform_spawn
[2021-11-11T03:39:20.012Z]     reply.run()
[2021-11-11T03:39:20.012Z]   File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 220, in run
[2021-11-11T03:39:20.012Z]     self._result = func(*args, **kwargs)
[2021-11-11T03:39:20.012Z]   File "/usr/local/lib/python3.6/site-packages/execnet/gateway_base.py", line 1084, in executetask
[2021-11-11T03:39:20.012Z]     do_exec(co, loc)  # noqa
[2021-11-11T03:39:20.012Z]   File "/usr/local/lib/python3.6/site-packages/xdist/remote.py", line 244, in <module>
[2021-11-11T03:39:20.012Z]     config.hook.pytest_cmdline_main(config=config)
[2021-11-11T03:39:20.012Z]   File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
[2021-11-11T03:39:20.012Z]     return self._hookexec(self, self.get_hookimpls(), kwargs)
[2021-11-11T03:39:20.012Z]   File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
[2021-11-11T03:39:20.012Z]     return self._inner_hookexec(hook, methods, kwargs)
[2021-11-11T03:39:20.012Z]   File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
[2021-11-11T03:39:20.012Z]     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
[2021-11-11T03:39:20.012Z]   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
[2021-11-11T03:39:20.012Z]     res = hook_impl.function(*args)
[2021-11-11T03:39:20.012Z]   File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 316, in pytest_cmdline_main
[2021-11-11T03:39:20.012Z]     return wrap_session(config, _main)
[2021-11-11T03:39:20.012Z]   File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 305, in wrap_session
[2021-11-11T03:39:20.012Z]     session=session, exitstatus=session.exitstatus
[2021-11-11T03:39:20.012Z]   File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
[2021-11-11T03:39:20.012Z]     return self._hookexec(self, self.get_hookimpls(), kwargs)
[2021-11-11T03:39:20.012Z]   File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
[2021-11-11T03:39:20.012Z]     return self._inner_hookexec(hook, methods, kwargs)
[2021-11-11T03:39:20.012Z]   File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
[2021-11-11T03:39:20.012Z]     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
[2021-11-11T03:39:20.012Z]   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
[2021-11-11T03:39:20.012Z]     res = hook_impl.function(*args)
[2021-11-11T03:39:20.012Z]   File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 103, in pytest_sessionfinish
[2021-11-11T03:39:20.012Z]     session._setupstate.teardown_all()
[2021-11-11T03:39:20.012Z]   File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 412, in teardown_all
[2021-11-11T03:39:20.012Z]     self._pop_and_teardown()
[2021-11-11T03:39:20.012Z]   File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 387, in _pop_and_teardown
[2021-11-11T03:39:20.012Z]     self._teardown_with_finalization(colitem)
[2021-11-11T03:39:20.012Z]   File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 405, in _teardown_with_finalization
[2021-11-11T03:39:20.012Z]     self._callfinalizers(colitem)
[2021-11-11T03:39:20.012Z]   File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 395, in _callfinalizers
[2021-11-11T03:39:20.012Z]     fin()
[2021-11-11T03:39:20.012Z]   File "/usr/local/lib/python3.6/site-packages/_pytest/fixtures.py", line 1027, in finish
[2021-11-11T03:39:20.012Z]     func()
[2021-11-11T03:39:20.012Z]   File "/usr/local/lib/python3.6/site-packages/_pytest/fixtures.py", line 941, in _teardown_yield_fixture
[2021-11-11T03:39:20.012Z]     next(it)
[2021-11-11T03:39:20.012Z]   File "/usr/local/lib/python3.6/site-packages/_pytest/python.py", line 845, in xunit_setup_method_fixture
[2021-11-11T03:39:20.012Z]     _call_with_optional_argument(func, method)
[2021-11-11T03:39:20.012Z]   File "/usr/local/lib/python3.6/site-packages/_pytest/python.py", line 739, in _call_with_optional_argument
[2021-11-11T03:39:20.012Z]     func(arg)
[2021-11-11T03:39:20.012Z]   File "/milvus/tests/python_client/base/client_base.py", line 61, in teardown_method
[2021-11-11T03:39:20.012Z]     log.info(("*" * 35) + " teardown " + ("*" * 35))
```

**Comment by ThreadDao** [comment]
No longer appear.
