### ISSUE TITLE
[Bug]: Server is not healthy after re-start milvus

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#11764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:4cd7680
- Deployment mode(standalone or cluster):both
- SDK version(e.g. pymilvus v2.0.0rc2):2.0.0rc9.dev3
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
Traceback (most recent call last):
  File "scripts/action_reinstall.py", line 5, in <module>
    connections.connect(host="127.0.0.1", port=19530, timeout=60)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 158, in connect
    conn = connect_milvus(**kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 148, in connect_milvus
    return Milvus(tmp_host, tmp_port, handler, pool, **tmp_kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/stub.py", line 122, in __init__
    self._update_connection_pool(channel=channel)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/stub.py", line 172, in _update_connection_pool
    self._wait_for_healthy()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/stub.py", line 141, in _wait_for_healthy
    raise Exception("server is not healthy, please try again later")
Exception: server is not healthy, please try again later
```

### Expected Behavior

Works well

### Steps To Reproduce

```markdown
cd `tests/python_client/deploy`
run script `bash test.sh -m standalone -t reinstall -p ${root_password}`
```

### Anything else?

GitHub action detail info: https://github.com/milvus-io/milvus/actions/runs/1457309022

log: https://github.com/milvus-io/milvus/suites/4346441304/artifacts/114024991

**Comment by sunby** [comment]
standalone parse wrong collectionID in datacoord. @godchen0212 will fix it. 
/unassign @sunby 
/assign @godchen0212

**Comment by godchen0212** [comment]
The issue has been fixed. Test it again.
/unassign

**Comment by zhuwenxing** [comment]
https://github.com/milvus-io/milvus/actions/runs/1461107626

Verified and passed
