### ISSUE TITLE
[Bug]: [benchmark][cluster] call query coordinator LoadCollection: rpc error: code = Unknown desc = , no queryNode to allocate

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#11777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20211112-71e814f
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus-2.0.0rc9.dev7
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

client pod: benchmark-tag-ljjdx-1237361420

client log:
```
[2021-11-13 07:38:38,402] [    INFO] - {'total_time': 39235.35, 'rps': 25487.22, 'ni_time': 1.96} (milvus_benchmark.runners.base:151)
[2021-11-13 07:38:38,483] [   DEBUG] - Start flush. (milvus_benchmark.runners.locust:428)
[2021-11-13 07:38:43,994] [   DEBUG] - Milvus flush run in 5.51s (milvus_benchmark.client:52)
[2021-11-13 07:38:43,995] [   DEBUG] - Fulsh done, during time: 5.51 (milvus_benchmark.runners.locust:431)
[2021-11-13 07:38:43,998] [   DEBUG] - Row count: 1000000000 in collection: <sift_1b_128_l2> (milvus_benchmark.client:416)
[2021-11-13 07:38:43,999] [   DEBUG] - 1000000000 (milvus_benchmark.runners.locust:432)
[2021-11-13 07:38:44,048] [   DEBUG] - Start build index for last file (milvus_benchmark.runners.locust:434)
[2021-11-13 07:38:44,049] [    INFO] - Building index start, collection_name: sift_1b_128_l2, index_type: IVF_SQ8, metric_type: L2 (milvus_benchmark.client:273)
[2021-11-13 07:38:44,050] [    INFO] - {'nlist': 1024} (milvus_benchmark.client:275)
[2021-11-13 07:38:44,050] [   DEBUG] - collection: sift_1b_128_l2 Index params: {'index_type': 'IVF_SQ8', 'metric_type': 'L2', 'params': {'nlist': 1024}} (milvus_benchmark.client:281)
[2021-11-13 07:39:05,591] [   DEBUG] - Building index done, collection_name: sift_1b_128_l2, response: Status(code=0, message='') (milvus_benchmark.client:283)
[2021-11-13 07:39:05,591] [   DEBUG] - Milvus create_index run in 21.54s (milvus_benchmark.client:52)
[2021-11-13 07:39:05,592] [   DEBUG] - {'flush_time': 5.51, 'build_time': 21.54} (milvus_benchmark.runners.locust:438)
[2021-11-13 07:39:05,595] [   DEBUG] - Row count: 1000000000 in collection: <sift_1b_128_l2> (milvus_benchmark.client:416)
[2021-11-13 07:39:05,596] [    INFO] - 1000000000 (milvus_benchmark.runners.locust:439)
[2021-11-13 07:39:05,596] [    INFO] - Start load collection (milvus_benchmark.runners.locust:440)
[2021-11-13 07:39:06,585] [   ERROR] - Error: <BaseException: (code=1, message=call query coordinator LoadCollection: rpc error: code = Unknown desc = , no queryNode to allocate)> (pymilvus.client.grpc_handler:69)
[2021-11-13 07:39:06,586] [   ERROR] - <BaseException: (code=1, message=call query coordinator LoadCollection: rpc error: code = Unknown desc = , no queryNode to allocate)> (milvus_benchmark.main:117)
[2021-11-13 07:39:06,591] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 86, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/locust.py", line 442, in prepare
    self.milvus.load_collection()
  File "/src/milvus_benchmark/client.py", line 48, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 478, in load_collection
    return self._milvus.load_collection(collection_name, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 58, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 42, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 322, in load_collection
    return handler.load_collection("", collection_name=collection_name, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 820, in load_collection
    raise BaseException(response.error_code, response.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=call query coordinator LoadCollection: rpc error: code = Unknown desc = , no queryNode to allocate)>
 (milvus_benchmark.main:118)
[2021-11-13 07:39:06,592] [   DEBUG] - {'_version': '0.1', '_type': 'metric', 'run_id': 1636727671, 'mode': 'local', 'server': <milvus_benchmark.metrics.models.server.Server object at 0x7f36012cf860>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware object at 0x7f36012cf8d0>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7f36012cf9e8>, 'status': 'RUN_FAILED', 'err_message': '', 'collection': {'dimension': 128, 'metric_type': 'l2', 'dataset_name': 'sift_1b_128_l2', 'collection_size': 1000000000, 'other_fields': None, 'ni_per': 50000, 'shards_num': None}, 'index': {'index_type': 'ivf_sq8', 'index_param': {'nlist': 1024}}, 'search': None, 'run_params': {'task': {'types': [{'type': 'query', 'weight': 20, 'params': {'top_k': 10, 'nq': 10, 'search_param': {'nprobe': 16}}}, {'type': 'load', 'weight': 1}, {'type': 'get', 'weight': 2, 'params': {'ids_length': 10}}], 'connection_num': 1, 'clients_num': 20, 'spawn_rate': 2, 'during_time': 302400}, 'connection_type': 'single'}, 'metrics': {'type': 'locust_random_performance', 'value': {}}, 'datetime': '2021-11-12 14:34:31.628576', 'type': 'metric'} (milvus_benchmark.metric.api:29)
```

querynode monitor：
<img width="1917" alt="截屏2021-11-15 10 33 00" src="https://user-images.githubusercontent.com/26307815/141713188-209908f6-e708-425e-b7bd-76b88cd9e385.png">

### Expected Behavior

loading collection successfully

### Steps To Reproduce

```markdown
1、create a collation
2、build index of IVF_SQ8
3、insert 1 billion vectors
4、flush collection
5、create index with the same params
6、load collection <- raise error of no queryNode to allocate
```

### Anything else?

argo task: benchmark-tag-ljjdx

test yaml：
client-configmap:client-random-locust-search-84h-1b,
server-configmap:server-cluster-8c64m-datanode2-indexnode4-querynode6

server:
```
NAME                                                        READY   STATUS      RESTARTS   AGE   IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-tag-ljjdx-1-etcd-0                                1/1     Running     0          17h   10.97.17.22    qa-node014.zilliz.local   <none>           <none>
benchmark-tag-ljjdx-1-etcd-1                                1/1     Running     0          17h   10.97.17.20    qa-node014.zilliz.local   <none>           <none>
benchmark-tag-ljjdx-1-etcd-2                                1/1     Running     0          17h   10.97.17.21    qa-node014.zilliz.local   <none>           <none>
benchmark-tag-ljjdx-1-milvus-datacoord-8f676c8c4-t5kpm      1/1     Running     0          17h   10.97.14.161   qa-node011.zilliz.local   <none>           <none>
benchmark-tag-ljjdx-1-milvus-datanode-55f78dcc9c-x4hzg      1/1     Running     0          17h   10.97.10.59    qa-node008.zilliz.local   <none>           <none>
benchmark-tag-ljjdx-1-milvus-datanode-55f78dcc9c-zmdv6      1/1     Running     0          17h   10.97.12.36    qa-node015.zilliz.local   <none>           <none>
benchmark-tag-ljjdx-1-milvus-indexcoord-6999dd8577-slz25    1/1     Running     0          17h   10.97.19.208   qa-node016.zilliz.local   <none>           <none>
benchmark-tag-ljjdx-1-milvus-indexnode-769965df58-28jfs     1/1     Running     0          17h   10.97.19.207   qa-node016.zilliz.local   <none>           <none>
benchmark-tag-ljjdx-1-milvus-indexnode-769965df58-bqhdn     1/1     Running     0          17h   10.97.17.14    qa-node014.zilliz.local   <none>           <none>
benchmark-tag-ljjdx-1-milvus-indexnode-769965df58-jx276     1/1     Running     0          17h   10.97.17.15    qa-node014.zilliz.local   <none>           <none>
benchmark-tag-ljjdx-1-milvus-indexnode-769965df58-p44bf     1/1     Running     0          17h   10.97.13.220   qa-node010.zilliz.local   <none>           <none>
benchmark-tag-ljjdx-1-milvus-proxy-666c96d644-57lw9         1/1     Running     0          17h   10.97.14.160   qa-node011.zilliz.local   <none>           <none>
benchmark-tag-ljjdx-1-milvus-querycoord-7bf4b4bccd-nqdhq    1/1     Running     0          17h   10.97.14.159   qa-node011.zilliz.local   <none>           <none>
benchmark-tag-ljjdx-1-milvus-querynode-7465dffb7b-4p2fm     1/1     Running     0          17h   10.97.11.106   qa-node009.zilliz.local   <none>           <none>
benchmark-tag-ljjdx-1-milvus-querynode-7465dffb7b-ctdlm     1/1     Running     0          17h   10.97.14.165   qa-node011.zilliz.local   <none>           <none>
benchmark-tag-ljjdx-1-milvus-querynode-7465dffb7b-nnzx4     1/1     Running     0          17h   10.97.13.221   qa-node010.zilliz.local   <none>           <none>
benchmark-tag-ljjdx-1-milvus-querynode-7465dffb7b-szdpz     1/1     Running     0          17h   10.97.15.254   qa-node012.zilliz.local   <none>           <none>
benchmark-tag-ljjdx-1-milvus-querynode-7465dffb7b-xznmp     1/1     Running     0          17h   10.97.12.37    qa-node015.zilliz.local   <none>           <none>
benchmark-tag-ljjdx-1-milvus-querynode-7465dffb7b-z6m9f     1/1     Running     0          17h   10.97.17.16    qa-node014.zilliz.local   <none>           <none>
benchmark-tag-ljjdx-1-milvus-rootcoord-84fbf8846b-kbpsc     1/1     Running     0          17h   10.97.14.163   qa-node011.zilliz.local   <none>           <none>
benchmark-tag-ljjdx-1-minio-0                               1/1     Running     0          17h   10.97.10.60    qa-node008.zilliz.local   <none>           <none>
benchmark-tag-ljjdx-1-minio-1                               1/1     Running     0          17h   10.97.15.3     qa-node012.zilliz.local   <none>           <none>
benchmark-tag-ljjdx-1-minio-2                               1/1     Running     0          17h   10.97.7.138    qa-node005.zilliz.local   <none>           <none>
benchmark-tag-ljjdx-1-minio-3                               1/1     Running     0          17h   10.97.9.46     qa-node007.zilliz.local   <none>           <none>
benchmark-tag-ljjdx-1-pulsar-autorecovery-c77f8db9b-bthtc   1/1     Running     0          17h   10.97.14.162   qa-node011.zilliz.local   <none>           <none>
benchmark-tag-ljjdx-1-pulsar-bastion-7f7458b4cb-2ghnv       1/1     Running     0          17h   10.97.15.253   qa-node012.zilliz.local   <none>           <none>
benchmark-tag-ljjdx-1-pulsar-bookkeeper-0                   1/1     Running     0          17h   10.97.10.61    qa-node008.zilliz.local   <none>           <none>
benchmark-tag-ljjdx-1-pulsar-bookkeeper-1                   1/1     Running     0          17h   10.97.9.48     qa-node007.zilliz.local   <none>           <none>
benchmark-tag-ljjdx-1-pulsar-broker-7c6f67b55c-8sd2v        1/1     Running     0          17h   10.97.14.164   qa-node011.zilliz.local   <none>           <none>
benchmark-tag-ljjdx-1-pulsar-proxy-7c4d94cb65-l6fgr         2/2     Running     0          17h   10.97.15.252   qa-node012.zilliz.local   <none>           <none>
benchmark-tag-ljjdx-1-pulsar-zookeeper-0                    1/1     Running     0          17h   10.97.7.137    qa-node005.zilliz.local   <none>           <none>
benchmark-tag-ljjdx-1-pulsar-zookeeper-1                    1/1     Running     0          17h   10.97.7.139    qa-node005.zilliz.local   <none>           <none>
benchmark-tag-ljjdx-1-pulsar-zookeeper-2                    1/1     Running     0          17h   10.97.7.140    qa-node005.zilliz.local   <none>           <none>
benchmark-tag-ljjdx-1-pulsar-zookeeper-metadata-b5f9s       0/1     Completed   0          17h   10.97.15.251   qa-node012.zilliz.local   <none>           <none>
```

**Comment by yanliang567** [comment]
@xige-16 please help to check this issue?
/assign @xige-16

**Comment by xige-16** [comment]
querycoord adds logic to determine whether the segment can be loaded on the querynode, judging by the size of the original vector, regardless of the index

**Comment by xige-16** [comment]
I will fix it

**Comment by binbinlv** [comment]
Verifying.

**Comment by binbinlv** [comment]
Blocked by #12073
