### ISSUE TITLE
[Bug]: querynode crashed after load 5000w&64dim vectors, when call search().

### ISSUE THREAD

**Issue by JamCrash** [milvus-io/milvus#11781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: rc8
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-rc8
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: guarantee enough
- GPU: 
- Others:
```

### Current Behavior

[2021/11/14 22:40:10.095 +00:00] [DEBUG] [historical.go:103] ["globalSealedSegments add segment"] [segmentID=429063743066603521] 
[2021/11/14 22:40:10.098 +00:00] [DEBUG] [historical.go:103] ["globalSealedSegments add segment"] [segmentID=429063909790187522] 
[2021/11/14 22:40:10.102 +00:00] [DEBUG] [query_node.go:290] ["get SealedSegmentsChangeInfo from etcd"] [infoID=429061055399593414] 
[2021/11/14 22:40:10.103 +00:00] [DEBUG] [query_node.go:290] ["get SealedSegmentsChangeInfo from etcd"] [infoID=429061055399593413] 
[2021/11/14 22:40:10.103 +00:00] [DEBUG] [collection_replica.go:493] ["remove segment"] [segmentID=429061297066475522] 
[2021/11/14 22:40:10.103 +00:00] [DEBUG] [segment.go:229] ["delete segment"] [segmentID=429061297066475522] 
[2021/11/14 22:40:10.105 +00:00] [DEBUG] [collection_replica.go:493] ["remove segment"] [segmentID=429064094968709122] 
[2021/11/14 22:40:10.130 +00:00] [DEBUG] [segment.go:229] ["delete segment"] [segmentID=429064094968709122] 
[2021/11/14 22:40:10.133 +00:00] [DEBUG] [collection_replica.go:493] ["remove segment"] [segmentID=429064154383646721] 
[2021/11/14 22:40:10.150 +00:00] [DEBUG] [segment.go:229] ["delete segment"] [segmentID=429064154383646721] 
[2021/11/14 22:40:10.152 +00:00] [DEBUG] [collection_replica.go:493] ["remove segment"] [segmentID=429063853612728321] 
[2021/11/14 22:40:10.174 +00:00] [DEBUG] [segment.go:229] ["delete segment"] [segmentID=429063853612728321] 
[2021/11/14 22:40:10.176 +00:00] [DEBUG] [collection_replica.go:493] ["remove segment"] [segmentID=429064202775429121] 
[2021/11/14 22:40:10.176 +00:00] [DEBUG] [segment.go:229] ["delete segment"] [segmentID=429064202775429121] 
[2021/11/14 22:40:10.179 +00:00] [DEBUG] [collection_replica.go:493] ["remove segment"] [segmentID=429064686955397121] 
[2021/11/14 22:40:10.179 +00:00] [WARN] [query_node.go:302] ["adjustByChangeInfo failed"] [error="cannot find segment in query node, id = 429064686955397121"] 
[2021/11/15 02:40:43.107 +00:00] [DEBUG] [time_recorder.go:76] ["receiveQueryMsg 429095962320602963: get searchable time done (0ms)"] 
[2021/11/15 02:40:43.107 +00:00] [DEBUG] [query_collection.go:436] ["doing query in receiveQueryMsg..."] [collectionID=429063694478213121] [sm.GuaranteeTimestamp=2021/11/15 02:40:43.055 +00:00] [serviceTime=1970/01/01 00:00:00.000 +00:00] ["delta seconds"=429115059] [msgID=429095962320602963] [msgType=search] 
[2021/11/15 02:40:43.107 +00:00] [DEBUG] [historical.go:246] ["no partition specified, search all partitions"] [collectionID=429063694478213121] ["all partitions"="[429063694491320321]"] 
[2021/11/15 02:40:43.107 +00:00] [DEBUG] [historical.go:282] ["doing search in historical"] [collectionID=429063694478213121] [reqPartitionIDs="[]"] [searchPartitionIDs="[429063694491320321]"] 
[2021/11/15 02:40:43.107 +00:00] [DEBUG] [segment.go:303] ["do search on segment"] [segmentID=429063952847339521] [segmentType=3] 
[2021/11/15 02:40:43.111 +00:00] [DEBUG] [segment.go:303] ["do search on segment"] [segmentID=429064541950443522] [segmentType=3] 
[2021/11/15 02:40:43.165 +00:00] [DEBUG] [segment.go:303] ["do search on segment"] [segmentID=429063743066603521] [segmentType=3] 
[2021/11/15 02:40:43.170 +00:00] [DEBUG] [segment.go:303] ["do search on segment"] [segmentID=429063955809566722] [segmentType=3] 
[2021/11/15 02:40:43.171 +00:00] [DEBUG] [segment.go:303] ["do search on segment"] [segmentID=429064307672350721] [segmentType=3] 
[2021/11/15 02:40:43.173 +00:00] [DEBUG] [segment.go:303] ["do search on segment"] [segmentID=429063703876075521] [segmentType=3] 
[2021/11/15 02:40:43.174 +00:00] [DEBUG] [segment.go:303] ["do search on segment"] [segmentID=429064202762321921] [segmentType=3] 
[2021/11/15 02:40:43.175 +00:00] [DEBUG] [segment.go:303] ["do search on segment"] [segmentID=429063798903275521] [segmentType=3] 
[2021/11/15 02:40:43.176 +00:00] [DEBUG] [time_recorder.go:76] ["search 429063694478213121(nq=5, k=10): historical search done (69ms)"] 
[2021/11/15 02:40:43.176 +00:00] [DEBUG] [time_recorder.go:76] ["search 429063694478213121(nq=5, k=10): streaming search done (0ms)"] 
2021-11-15 02:40:43,177 DEBUG [default] [user@istio-milvus-querynode-6f47c7544d-ks2xk] [void GetResultData(std::vector<std::vector<long int> >&, std::vector<milvus::SearchResult*>&, int64_t, int64_t)] [/go/src/github.com/milvus-io/milvus/internal/core/src/segcore/reduce_c.cpp:113] [SEGCORE][GetResultData][milvus] skip duplicated search result, count = 70 
fatal error: unexpected signal during runtime execution 
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x7fb8bc623cba] 
 
runtime stack: 
runtime.throw(0x265ae26, 0x2a) 
	/usr/local/go/src/runtime/panic.go:1116 +0x72 
runtime.sigpanic() 
	/usr/local/go/src/runtime/signal_unix.go:704 +0x4ac 
 
goroutine 2804 [syscall]: 
runtime.cgocall(0x17c043a, 0xc000ba2ae0, 0xc00056b600) 
	/usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc000ba2ab0 sp=0xc000ba2a78 pc=0x729d1b 
github.com/milvus-io/milvus/internal/querynode._Cfunc_ReduceSearchResultsAndFillData(0x7fb8331504c0, 0xc000f02e40, 0x8, 0x0, 0x0) 
	_cgo_gotypes.go:742 +0x56 fp=0xc000ba2ae0 sp=0xc000ba2ab0 pc=0x178f7d6 
github.com/milvus-io/milvus/internal/querynode.reduceSearchResultsAndFillData.func1(0xc000011030, 0xc000f02e40, 0x8, 0x4, 0x5) 
	/go/src/github.com/milvus-io/milvus/internal/querynode/reduce.go:49 +0x8f fp=0xc000ba2b20 sp=0xc000ba2ae0 pc=0x17a83ef 
github.com/milvus-io/milvus/internal/querynode.reduceSearchResultsAndFillData(0xc000011030, 0xc000f02dc0, 0x8, 0x8, 0x8, 0x0, 0x0) 
	/go/src/github.com/milvus-io/milvus/internal/querynode/reduce.go:49 +0x178 fp=0xc000ba2bd8 sp=0xc000ba2b20 pc=0x179c8d8 
github.com/milvus-io/milvus/internal/querynode.(*queryCollection).search(0xc0009b7d10, 0x285fb60, 0xc000792240, 0x0, 0x0) 
	/go/src/github.com/milvus-io/milvus/internal/querynode/query_collection.go:996 +0x169a fp=0xc000ba34c8 sp=0xc000ba2bd8 pc=0x177841a 
github.com/milvus-io/milvus/internal/querynode.(*queryCollection).receiveQueryMsg(0xc0009b7d10, 0x285fb60, 0xc000792240, 0x0, 0x0) 
	/go/src/github.com/milvus-io/milvus/internal/querynode/query_collection.go:448 +0x1e45 fp=0xc000ba3ec0 sp=0xc000ba34c8 pc=0x17710a5 
github.com/milvus-io/milvus/internal/querynode.(*queryCollection).consumeQuery(0xc0009b7d10) 
	/go/src/github.com/milvus-io/milvus/internal/querynode/query_collection.go:284 +0x11e fp=0xc000ba3fd8 sp=0xc000ba3ec0 pc=0x176eb5e 
runtime.goexit() 
	/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000ba3fe0 sp=0xc000ba3fd8 pc=0x796641 
created by github.com/milvus-io/milvus/internal/querynode.(*queryCollection).start 
	/go/src/github.com/milvus-io/milvus/internal/querynode/query_collection.go:130 +0xa7 
 
goroutine 1 [chan receive, 290 minutes]: 
github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run(0xc0007a7eff, 0x0, 0x0, 0x0) 
	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:472 +0x2f8 
main.main() 
	/go/src/github.com/milvus-io/milvus/cmd/main.go:286 +0x649 
 
goroutine 185 [select]: 
github.com/uber/jaeger-client-go.(*RemotelyControlledSampler).pollControllerWithTicker(0xc000350340, 0xc000134690) 
	/go/pkg/mod/github.com/uber/jaeger-client-go@v2.25.0+incompatible/sampler_remote.go:144 +0xdf 
github.com/uber/jaeger-client-go.(*RemotelyControlledSampler).pollController(0xc000350340) 
	/go/pkg/mod/github.com/uber/jaeger-client-go@v2.25.0+incompatible/sampler_remote.go:139 +0x73 
created by github.com/uber/jaeger-client-go.NewRemotelyControlledSampler 
	/go/pkg/mod/github.com/uber/jaeger-client-go@v2.25.0+incompatible/sampler_remote.go:86 +0x125 
 
goroutine 296 [select, 290 minutes]: 
context.propagateCancel.func1(0x284a420, 0xc000af0590, 0x282f3e0, 0xc0001d90c0) 
	/usr/local/go/src/context/context.go:279 +0xda 
created by context.propagateCancel 
	/usr/local/go/src/context/context.go:278 +0x1fb 
 
goroutine 111 [IO wait, 290 minutes]: 
internal/poll.runtime_pollWait(0x7fb8905ff808, 0x72, 0x0) 
	/usr/local/go/src/runtime/netpoll.go:220 +0x55 
internal/poll.(*pollDesc).wait(0xc000524218, 0x72, 0x0, 0x0, 0x2618fcd) 
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45 
internal/poll.(*pollDesc).waitRead(...) 
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92 
internal/poll.(*FD).Accept(0xc000524200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0) 
	/usr/local/go/src/internal/poll/fd_unix.go:394 +0x1fc 
net.(*netFD).accept(0xc000524200, 0xc000179d00, 0xc000600800, 0x7fb8bde6d7d0) 
	/usr/local/go/src/net/fd_unix.go:172 +0x45 
net.(*TCPListener).accept(0xc00053a2e0, 0xc000179d40, 0x734778, 0x30) 
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x32 
net.(*TCPListener).Accept(0xc00053a2e0, 0x24fe580, 0xc0003fc240, 0x23c73e0, 0x3648d00) 
	/usr/local/go/src/net/tcpsock.go:261 +0x65 
net/http.(*Server).Serve(0xc0003b2540, 0x2844260, 0xc00053a2e0, 0x0, 0x0) 
	/usr/local/go/src/net/http/server.go:2937 +0x266 
net/http.(*Server).ListenAndServe(0xc0003b2540, 0xc0003b2540, 0x3) 
	/usr/local/go/src/net/http/server.go:2866 +0xb7 
net/http.ListenAndServe(...) 
	/usr/local/go/src/net/http/server.go:3120 
github.com/milvus-io/milvus/internal/metrics.ServeHTTP.func1() 
	/go/src/github.com/milvus-io/milvus/internal/metrics/metrics.go:646 +0x66 
created by github.com/milvus-io/milvus/internal/metrics.ServeHTTP 
	/go/src/github.com/milvus-io/milvus/internal/metrics/metrics.go:645 +0x75 

### Expected Behavior

expect: search well 

ps: the querynode crashed and restart, then do a cycle between reload/delete segment, after about 30minutes, the cycle done, and do not search the task, and the pymilvus client block; if pymilvus client restart, the problem reproduce.

### Anything else?
collection id mismatch: 

[2021/11/15 02:44:41.203 +00:00] [DEBUG] [query_node.go:290] ["get SealedSegmentsChangeInfo from etcd"] [infoID=429061055399593436]
[2021/11/15 02:44:41.203 +00:00] [DEBUG] [query_node.go:290] ["get SealedSegmentsChangeInfo from etcd"] [infoID=429061055399593437]
[2021/11/15 02:44:41.203 +00:00] [DEBUG] [collection_replica.go:493] ["remove segment"] [segmentID=429061363218513921]
[2021/11/15 02:44:41.203 +00:00] [DEBUG] [segment.go:229] ["delete segment"] [segmentID=429061363218513921]
[2021/11/15 02:44:41.206 +00:00] [DEBUG] [collection_replica.go:493] ["remove segment"] [segmentID=429063955809566721]
[2021/11/15 02:44:41.260 +00:00] [DEBUG] [segment.go:229] ["delete segment"] [segmentID=429063955809566721]
[2021/11/15 02:44:41.262 +00:00] [DEBUG] [collection_replica.go:493] ["remove segment"] [segmentID=429064209630494722]
[2021/11/15 02:44:41.283 +00:00] [DEBUG] [segment.go:229] ["delete segment"] [segmentID=429064209630494722]
[2021/11/15 02:44:41.285 +00:00] [DEBUG] [collection_replica.go:493] ["remove segment"] [segmentID=429063952834232321]
[2021/11/15 02:44:41.286 +00:00] [DEBUG] [segment.go:229] ["delete segment"] [segmentID=429063952834232321]
[2021/11/15 02:44:41.287 +00:00] [DEBUG] [collection_replica.go:493] ["remove segment"] [segmentID=429064206039121922]
[2021/11/15 02:44:41.289 +00:00] [DEBUG] [segment.go:229] ["delete segment"] [segmentID=429064206039121922]
[2021/11/15 02:44:41.291 +00:00] [DEBUG] [collection_replica.go:493] ["remove segment"] [segmentID=429064541950443521]
[2021/11/15 02:44:41.316 +00:00] [DEBUG] [segment.go:229] ["delete segment"] [segmentID=429064541950443521]
[2021/11/15 02:44:41.318 +00:00] [DEBUG] [collection_replica.go:493] ["remove segment"] [segmentID=429064583644446721]
[2021/11/15 02:44:41.366 +00:00] [DEBUG] [segment.go:229] ["delete segment"] [segmentID=429064583644446721]
[2021/11/15 02:48:25.023 +00:00] [ERROR] [query_collection.go:297] ["mismatch collectionID when addGlobalSegmentInfo, manager collectionID = 429061296961617921 , segmentInfo collectionID = 429063694478213121\n"] [stack="github.com/milvus-io/milvus/internal/querynode.(*queryCollection).consumeQuery\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/query_collection.go:297"]
[2021/11/15 02:48:25.027 +00:00] [DEBUG] [historical.go:103] ["globalSealedSegments add segment"] [segmentID=429061297066475522]
[2021/11/15 02:48:25.030 +00:00] [DEBUG] [historical.go:103] ["globalSealedSegments add segment"] [segmentID=429064641919057921]
[2021/11/15 02:48:25.033 +00:00] [ERROR] [query_collection.go:297] ["mismatch collectionID when addGlobalSegmentInfo, manager collectionID = 429063694478213121 , segmentInfo collectionID = 429061296961617921\n"] [stack="github.com/milvus-io/milvus/internal/querynode.(*queryCollection).consumeQuery\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/query_collection.go:297"]
[2021/11/15 02:48:25.034 +00:00] [DEBUG] [historical.go:103] ["globalSealedSegments add segment"] [segmentID=429063706838302721]
[2021/11/15 02:48:25.037 +00:00] [DEBUG] [historical.go:103] ["globalSealedSegments add segment"] [segmentID=429064583644446721]
[2021/11/15 02:48:25.040 +00:00] [DEBUG] [historical.go:103] ["globalSealedSegments add segment"] [segmentID=429064427262443521]
[2021/11/15 02:48:25.043 +00:00] [DEBUG] [historical.go:103] ["globalSealedSegments add segment"] [segmentID=429064248912773121]
[2021/11/15 02:48:25.046 +00:00] [DEBUG] [historical.go:103] ["globalSealedSegments add segment"] [segmentID=429061301024849922]

**Comment by xiaofan-luan** [comment]
Hi Jam, sorry for bring you so much trouble. We've tested with around reasonable workload but for sure there are many stability issues. 

Please help us improve the stability together and be nice~ people in the community didn't charge for a penny

**Comment by yanliang567** [comment]
@xige-16 Could you please help to take a look at this issue
/assign @xige-16

**Comment by xiaofan-luan** [comment]
I'm looking into it

**Comment by JamCrash** [comment]
> Hi Jam, sorry for bring you so much trouble. We've tested with around reasonable workload but for sure there are many stability issues.
> 
> Please help us improve the stability together and be nice~ people in the community didn't charge for a penny

**Comment by JamCrash** [comment]
I turned this issue off by accident, is there any one can reopen it ?

**Comment by xiaofan-luan** [comment]
the search issue is similar to https://github.com/milvus-io/milvus/issues/10729, which should already be fixed by #10832

**Comment by xiaofan-luan** [comment]
do you know what task the py client is blocking at @JamCrash

**Comment by JamCrash** [comment]
when first create index done, and search for the first time, the querynode crash, and the pymilvus block. After the client restart, it block too

**Comment by JamCrash** [comment]
after querynode restart, if I restart client(reload partition and do search), the problem reproduce

**Comment by JamCrash** [comment]
the milvus image I used is milvus:v2.0.0-rc8-20211104-d1f4106

**Comment by JamCrash** [comment]
I am confused why the collection id will mismatch when query the same partition

**Comment by xiaofan-luan** [comment]
> the milvus image I use is milvus:v2.0.0-rc8-20211104-d1f4106， maybe this image does not fix the problem? @xiaofan-luan

yep, it should be fixed by the GA version, RC8 doesn't include the fix.

**Comment by JamCrash** [comment]
so when this version can be compliled into image?

**Comment by xiaofan-luan** [comment]
> so when this version can be compliled into image?

trying to deliver in GA. but the day build should already include this change

**Comment by xige-16** [comment]
If you don't insert data multiple times with the same primary key, rc8 should no longer encounter this problem

**Comment by xige-16** [comment]
> If you don't insert data multiple times with the same primary key, rc8 should no longer encounter this problem

If you still have this problem, please let us know. @JamCrash

**Comment by JamCrash** [comment]
this problem can reproduce more than once

**Comment by JamCrash** [comment]
after querynode crash and restart for the first time, if call load or search, the pymilvus client will hang forever

**Comment by JamCrash** [comment]
the milvus behavior is very instable under my dataset(600 million, 64dim) with index param {"index_type": "IVF_PQ", "params": {"nlist": 20480, "m": 8}, "metric_type": "L2"}

milvus rc8, pulsar standalone, minio standalone, etcd(3 nodes with local storage) 
with k8s environment
