### ISSUE TITLE
[Bug]: Load failed reporting "<BaseException: (code=1, message=rpc error: code = Unknown desc = collection has not been loaded to memory or load failed)"

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#11969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: latest
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): latest
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Load failed:

Logs: [standalone:  artifacts-milvus-standalone-master-220-pymilvus-e2e-logs.tar.gz]
[please download from through the upper log name]
https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/220/

Other clues:

Failed case 1:

1. Failed case:  FAILED testcases/test_search_20.py::TestCollectionSearch::test_search_after_different_index_with_params[8-False-True-HNSW-params4] 

2. Collection name: search_collection_w4WHSbge

3. Timeline:
```
[2021-11-16 15:29:18,685 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None], kwargs: {'timeout': 20} (api_request.py:44)
[2021-11-16 15:30:36,929 - ERROR - ci_test]: Traceback (most recent call last):
  File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 45, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 449, in load
    conn.load_collection(self._name, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 58, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 42, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 322, in load_collection
    return handler.load_collection("", collection_name=collection_name, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 823, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 841, in wait_for_loading_collection
    return self._wait_for_loading_collection_v2(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 868, in _wait_for_loading_collection_v2
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=rpc error: code = Unknown desc = collection has not been loaded to memory or load failed)>
```

Failed case 2:

1. Failed case
```
[2021-11-16T15:33:08.981Z] [gw0] [ 41%] FAILED testcases/test_search_20.py::TestCollectionSearch::test_search_after_index_different_metric_type[128-True-True-IVF_FLAT-params1] 
```
2. collection name: search_collection_sp6bGVTh

3. Timeline:
```
[2021-11-16 15:32:59,995 - ERROR - ci_test]: Traceback (most recent call last):
  File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 45, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 449, in load
    conn.load_collection(self._name, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 58, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 42, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 322, in load_collection
    return handler.load_collection("", collection_name=collection_name, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 823, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 841, in wait_for_loading_collection
    return self._wait_for_loading_collection_v2(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 868, in _wait_for_loading_collection_v2
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=rpc error: code = Unknown desc = collection has not been loaded to memory or load failed)>
```
### Expected Behavior

Load success

**Comment by yanliang567** [comment]
ci nightly blocked, set to urgent

**Comment by xige-16** [comment]
[2021/11/16 15:21:25.002 +00:00] [DEBUG] [client.go:164] ["QueryNode Client grpc error"] [error="rpc error: code = Unknown desc = All attempts results:\nattempt #1:Access Denied.\nattempt #2:Access Denied.\nattempt #3:Access Denied.\nattempt #4:Access Denied.\nattempt #5:Access Denied.\nattempt #6:Access Denied.\nattempt #7:Access Denied.\nattempt #8:Access Denied.\nattempt #9:Access Denied.\nattempt #10:Access Denied.\n"]

**Comment by xige-16** [comment]
@DragonDriver  any update?

**Comment by binbinlv** [comment]
Did not occur for several days, so cancel the urgent first.

**Comment by binbinlv** [comment]
It occurs at CI, set it as urgent.

https://github.com/milvus-io/milvus/issues/11969

**Comment by binbinlv** [comment]
@xige-16 @DragonDriver any update?

**Comment by xige-16** [comment]
[2021/11/24 02:10:40.481 +00:00] [DEBUG] [cluster.go:263] ["loadSegments: queryNode load segments error"] [nodeID=8] ["error info"="rpc error: code = Unknown desc = Access Denied."]

**Comment by binbinlv** [comment]
It does not occur every time (nightly and CI occur 2 times), so cancel the urgent label.

**Comment by binbinlv** [comment]
After resolving nightly hangs issue, then this issue exposed in Nightly again, and it occurs at quite a many cases, so set it as urgent again.

```
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=err: rpc error: code = Unknown desc = collection 429453915516829697 has not been loaded to memory or load failed
```
And
```
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=call query coordinator LoadCollection: err: rpc error: code = Unknown desc = , Access Denied.
```

**Comment by bigsheeper** [comment]
```
[2021/11/30 01:46:05.313 +00:00] [DEBUG] [segment_loader.go:586] ["estimate segment fields size"] [collectionID=429453915516829697] [segmentID=429453915831140354] [fieldID=1] [paths="[insert_log/429453915516829697/429453915516829698/429453915831140354/1/429453916473655301]"]

[2021/11/30 01:46:05.322 +00:00] [DEBUG] [segment_loader.go:586] ["estimate segment fields size"] [collectionID=429453915516829697] [segmentID=429453915831140354] [fieldID=100] [paths="[insert_log/429453915516829697/429453915516829698/429453915831140354/100/429453916473655297]"]

[2021/11/30 01:46:05.334 +00:00] [DEBUG] [segment.go:232] ["delete segment"] [segmentID=429453915831140354]

[2021/11/30 01:46:05.334 +00:00] [WARN] [task.go:622] ["Access Denied."]

[2021/11/30 01:46:05.334 +00:00] [WARN] [task_scheduler.go:58] ["Access Denied."]

[2021/11/30 01:46:05.334 +00:00] [WARN] [impl.go:380] ["Access Denied."]
```

Query node cannot get binlog size by monio interface in `segment_loader.go` and return `Access Denied.` error.
When I check minio log, it shows:
```
API: HeadObject(bucket=milvus-bucket, object=index_files/429453916521365508/1/429453915516829698/429453915831140354/QUANTIZATION_DATA)

Time: 01:44:52 UTC 11/30/2021

DeploymentID: 84bc3ff3-fed9-4203-891a-9dcda7e43f29

RequestID: 16BC2F97ACCD55AB

RemoteHost: 10.202.12.170

Host: ms-dd13-236-minio:9000

UserAgent: MinIO (linux; amd64) minio-go/v7.0.10

Error: file access denied (cmd.StorageErr)

       6: cmd/fs-v1-helpers.go:210:cmd.fsStatFile()

       5: cmd/fs-v1.go:1006:cmd.(*FSObjects).getObjectInfo()

       4: cmd/fs-v1.go:1035:cmd.(*FSObjects).getObjectInfoWithLock()

       3: cmd/fs-v1.go:1053:cmd.(*FSObjects).GetObjectInfo()

       2: cmd/object-handlers.go:572:cmd.objectAPIHandlers.HeadObjectHandler()

       1: net/http/server.go:2042:http.HandlerFunc.ServeHTTP()
```

**Comment by LoveEachDay** [comment]
According to https://github.com/minio/minio/issues/7811， we've modified the nfs mount options to `noac`. 
/unassign
/assign @binbinlv

**Comment by binbinlv** [comment]
OK, will check the results tonight.

**Comment by binbinlv** [comment]
Through using local storage replacing NFS, it is not reproduced in latest nightly.

Cancel urgent, and will close it after checking several days.

**Comment by binbinlv** [comment]
Need to investigate the NFS related issue.

**Comment by AbhayNathaniWOT** [comment]
/reopen 
RPC error: [search], <MilvusException: (code=1, message=checkIfLoaded failed when search, collection:demo, partitions:[], err = GetCollectionInfo failed, collection = demo, err = collection <ID> has not been loaded to memory or load failed)>

**Comment by AbhayNathaniWOT** [comment]
RPC error: [search], <MilvusException: (code=1, message=checkIfLoaded failed when search, collection:demo, partitions:[], err = GetCollectionInfo failed, collection = demo, err = collection <ID> has not been loaded to memory or load failed)>

**Comment by xiaofan-luan** [comment]
> RPC error: [search], <MilvusException: (code=1, message=checkIfLoaded failed when search, collection:demo, partitions:[], err = GetCollectionInfo failed, collection = demo, err = collection has not been loaded to memory or load failed)>

Did you try to load the collection before search?
Usually the way you can use milvus is to:
create collection
build index
insert data
load the collection
search
