### ISSUE TITLE
[Bug]: Load timeout during tests

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#11978]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: latest
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc9.dev6
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Logs: [standalone mode:  artifacts-milvus-standalone-master-220-pymilvus-e2e-logs.tar.gz]

https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/220/

Clues:

1. Failed case: test_search_collection_after_release_load.
2. collection name: search_collection_f7iE0esp
3. Timeline:
```
[2021-11-16 15:33:40,028 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None], kwargs: {'timeout': 20} (api_request.py:44)
[2021-11-16 15:37:18,074 - ERROR - ci_test]: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 42, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 322, in load_collection
    return handler.load_collection("", collection_name=collection_name, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 818, in load_collection
    response = rf.result()
  File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "{"created":"@1637077038.073524564","description":"Error received from peer ipv4:10.201.212.98:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 45, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 449, in load
    conn.load_collection(self._name, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 53, in handler
    raise BaseException(1, "rpc timeout")
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=rpc timeout)>
 (api_request.py:26)
[2021-11-16 15:37:18,074 - ERROR - ci_test]: (api_response) : <BaseException: (code=1, message=rpc timeout)> (api_request.py:27)
```

### Expected Behavior

Load successfully

### Steps To Reproduce

```markdown
During nightly tests
```

**Comment by xige-16** [comment]
[2021/11/16 15:32:24.893 +00:00] [DEBUG] [impl.go:321] [LoadCollection] [role=proxy] [msgID=429149831408417191] [timestamp=429149846206414854] [db=] [collection=search_collection_f7iE0esp]

[2021/11/16 15:32:25.381 +00:00] [DEBUG] [impl.go:2349] [RegisterLink] [role=proxy] ["state code of proxy"=Healthy]

[2021/11/16 15:32:25.384 +00:00] [DEBUG] [impl.go:529] ["ShowCollections enqueue"] [role=proxy] [request="type:InMemory collection_names:\"search_collection_sp6bGVTh\" "]

[2021/11/16 15:32:25.384 +00:00] [DEBUG] [id.go:141] ["IDAllocator pickCanDoFunc"] [need=1] [total=168857] [remainReqCnt=0]

[2021/11/16 15:32:25.384 +00:00] [DEBUG] [impl.go:542] [ShowCollections] [role=proxy] [DbName=] [ShowType=InMemory] [CollectionNames="[search_collection_sp6bGVTh]"]

[2021/11/16 15:32:25.619 +00:00] [DEBUG] [session_util.go:284] ["SessionUtil GetSessions "] [prefix=IndexNode] [key=IndexNode-6] [address=10.202.30.133:21121]

[2021/11/16 15:32:26.384 +00:00] [DEBUG] [impl.go:309] ["LoadCollection enqueue"] [role=proxy] [db=] [collection=query_yiQczyoQ]

[2021/11/16 15:32:26.384 +00:00] [DEBUG] [id.go:141] ["IDAllocator pickCanDoFunc"] [need=1] [total=168856] [remainReqCnt=0]

[2021/11/16 15:32:26.384 +00:00] [DEBUG] [impl.go:321] [LoadCollection] [role=proxy] [msgID=429149831408417193] [timestamp=429149846599630849] [db=] [collection=query_yiQczyoQ]

[2021/11/16 15:32:28.614 +00:00] [DEBUG] [index_coord.go:629] ["IndexCoord recycleUnusedIndexFiles"] ["Need recycle tasks num"=0]

[2021/11/16 15:32:28.616 +00:00] [DEBUG] [session_util.go:284] ["SessionUtil GetSessions "] [prefix=IndexNode] [key=IndexNode-6] [address=10.202.30.133:21121]

[2021/11/16 15:32:31.621 +00:00] [DEBUG] [session_util.go:284] ["SessionUtil GetSessions "] [prefix=IndexNode] [key=IndexNode-6] [address=10.202.30.133:21121]

[2021/11/16 15:32:34.052 +00:00] [DEBUG] [index_loader.go:113] ["load path"="[index_files/429149833506062340/1/429149831211778050/429149831421493249/IVF index_files/429149833506062340/1/429149831211778050/429149831421493249/RAW_DATA index_files/429149833506062340/1/429149831211778050/429149831421493249/indexParams]\n"]

[2021/11/16 15:32:34.621 +00:00] [DEBUG] [session_util.go:284] ["SessionUtil GetSessions "] [prefix=IndexNode] [key=IndexNode-6] [address=10.202.30.133:21121]

[2021/11/16 15:32:37.615 +00:00] [DEBUG] [session_util.go:284] ["SessionUtil GetSessions "] [prefix=IndexNode] [key=IndexNode-6] [address=10.202.30.133:21121]

[2021/11/16 15:32:38.624 +00:00] [DEBUG] [index_coord.go:629] ["IndexCoord recycleUnusedIndexFiles"] ["Need recycle tasks num"=0]

[2021/11/16 15:32:40.622 +00:00] [DEBUG] [session_util.go:284] ["SessionUtil GetSessions "] [prefix=IndexNode] [key=IndexNode-6] [address=10.202.30.133:21121]

[2021/11/16 15:32:43.626 +00:00] [DEBUG] [session_util.go:284] ["SessionUtil GetSessions "] [prefix=IndexNode] [key=IndexNode-6] [address=10.202.30.133:21121]

[2021/11/16 15:32:44.056 +00:00] [DEBUG] [index_loader.go:113] ["load path"="[index_files/429149833506062340/1/429149831211778050/429149831421493249/IVF index_files/429149833506062340/1/429149831211778050/429149831421493249/RAW_DATA index_files/429149833506062340/1/429149831211778050/429149831421493249/indexParams]\n"]

[2021/11/16 15:32:44.887 +00:00] [DEBUG] [impl.go:328] ["LoadCollection Done"] [error="Proxy TaskCondition context Done"] [role=proxy] [msgID=429149831408417189] [timestamp=429149846206414852] [db=] [collection=search_collection_3oovXxD1]

[2021/11/16 15:32:44.887 +00:00] [DEBUG] [client.go:198] ["QueryCoord Client grpc error"] [error="rpc error: code = Canceled desc = context canceled"]

[2021/11/16 15:32:44.887 +00:00] [INFO] [grpclog.go:37] ["[core]Channel Connectivity change to SHUTDOWN"]

[2021/11/16 15:32:44.887 +00:00] [INFO] [grpclog.go:37] ["[core]Subchannel Connectivity change to SHUTDOWN"]

[2021/11/16 15:32:44.887 +00:00] [INFO] [grpclog.go:37] ["[transport]transport: loopyWriter.run returning. connection error: desc = \"transport is closing\""]

[2021/11/16 15:32:44.887 +00:00] [INFO] [grpclog.go:37] ["[transport]transport: loopyWriter.run returning. connection error: desc = \"transport is closing\""]

[2021/11/16 15:32:44.887 +00:00] [DEBUG] [session_util.go:284] ["SessionUtil GetSessions "] [prefix=QueryCoord] [key=QueryCoord] [address=10.202.30.133:19531]

[2021/11/16 15:32:44.887 +00:00] [DEBUG] [client.go:148] ["QueryCoordClient try reconnect "] [address=10.202.30.133:19531]

[2021/11/16 15:32:44.887 +00:00] [INFO] [grpclog.go:37] ["[core]parsed scheme: \"\""]

[2021/11/16 15:32:44.887 +00:00] [INFO] [grpclog.go:37] ["[core]scheme \"\" not registered, fallback to default scheme"]

[2021/11/16 15:32:44.887 +00:00] [INFO] [grpclog.go:37] ["[core]ccResolverWrapper: sending update to cc: {[{10.202.30.133:19531  <nil> 0 <nil>}] <nil> <nil>}"]

[2021/11/16 15:32:44.887 +00:00] [INFO] [grpclog.go:37] ["[core]ClientConn switching balancer to \"pick_first\""]

[2021/11/16 15:32:44.887 +00:00] [INFO] [grpclog.go:37] ["[core]Channel switches to new LB policy \"pick_first\""]

[2021/11/16 15:32:44.887 +00:00] [INFO] [grpclog.go:37] ["[core]Subchannel Connectivity change to CONNECTING"]

[2021/11/16 15:32:44.887 +00:00] [INFO] [grpclog.go:37] ["[core]Subchannel picks a new address \"10.202.30.133:19531\" to connect"]

[2021/11/16 15:32:44.887 +00:00] [INFO] [grpclog.go:37] ["[core]pickfirstBalancer: UpdateSubConnState: 0xc014a306e0, {CONNECTING <nil>}"]

[2021/11/16 15:32:44.887 +00:00] [INFO] [grpclog.go:37] ["[core]Channel Connectivity change to CONNECTING"]

[2021/11/16 15:32:44.887 +00:00] [INFO] [grpclog.go:37] ["[core]Subchannel Connectivity change to READY"]

[2021/11/16 15:32:44.887 +00:00] [INFO] [grpclog.go:37] ["[core]pickfirstBalancer: UpdateSubConnState: 0xc014a306e0, {READY <nil>}"]

[2021/11/16 15:32:44.887 +00:00] [INFO] [grpclog.go:37] ["[core]Channel Connectivity change to READY"]

[2021/11/16 15:32:44.887 +00:00] [DEBUG] [client.go:188] ["QueryCoordClient try reconnect success"]

[2021/11/16 15:32:44.887 +00:00] [ERROR] [task_scheduler.go:457] ["Failed to execute task: call query coordinator LoadCollection: rpc error: code = Canceled desc = context canceled"] [traceID=31e1c85d53ca48cc] [stack="github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:457\ngithub.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:482"]

[2021/11/16 15:32:44.887 +00:00] [DEBUG] [root_coord.go:1353] [DescribeCollection] [name=search_collection_uCJTkKhS] [msgID=429149831408417190]

[2021/11/16 15:32:44.888 +00:00] [DEBUG] [root_coord.go:1373] ["DescribeCollection Succeeded"] [name=search_collection_uCJTkKhS] [msgID=429149831408417190]

[2021/11/16 15:32:44.888 +00:00] [DEBUG] [task.go:4133] ["loadCollectionTask PreExecute"] [role=proxy] [msgID=429149831408417191]

[2021/11/16 15:32:44.888 +00:00] [DEBUG] [task.go:4147] ["loadCollectionTask Execute"] [role=proxy] [msgID=429149831408417191]

[2021/11/16 15:32:44.888 +00:00] [DEBUG] [task.go:4168] ["send LoadCollectionRequest to query coordinator"] [role=proxy] [msgID=429149831408417191] [collectionID=429149833361358849] [schema="name:\"search_collection_f7iE0esp\" fields:<fieldID:100 name:\"int64\" is_primary_key:true data_type:Int64 > fields:<fieldID:101 name:\"float\" data_type:Float > fields:<fieldID:102 name:\"float_vector\" data_type:FloatVector type_params:<key:\"dim\" value:\"128\" > > "]

[2021/11/16 15:32:44.888 +00:00] [DEBUG] [impl.go:435] ["DescribeCollection Done"] [] [role=proxy] [msgID=429149831408417190] [timestamp=429149846206414853] [db=] [collection=search_collection_uCJTkKhS]

[2021/11/16 15:32:44.888 +00:00] [DEBUG] [impl.go:135] ["LoadCollectionRequest received"] [role=querycoord] [msgID=429149831408417191] [collectionID=429149833361358849] [schema="name:\"search_collection_f7iE0esp\" fields:<fieldID:100 name:\"int64\" is_primary_key:true data_type:Int64 > fields:<fieldID:101 name:\"float\" data_type:Float > fields:<fieldID:102 name:\"float_vector\" data_type:FloatVector type_params:<key:\"dim\" value:\"128\" > > "]

[2021/11/16 15:32:44.888 +00:00] [DEBUG] [task_scheduler.go:455] ["EnQueue a triggerTask and save to etcd"] [taskID=429149438296460286]

[2021/11/16 15:32:44.894 +00:00] [DEBUG] [impl.go:328] ["LoadCollection Done"] [error="Proxy TaskCondition context Done"] [role=proxy] [msgID=429149831408417191] [timestamp=429149846206414854] [db=] [collection=search_collection_f7iE0esp]

[2021/11/16 15:32:44.894 +00:00] [DEBUG] [client.go:198] ["QueryCoord Client grpc error"] [error="rpc error: code = Canceled desc = context canceled"]

**Comment by xige-16** [comment]
The proxy waited 20 seconds after receiving the load request before processing

**Comment by xige-16** [comment]
> The proxy waited 20 seconds after receiving the load request before processing

During this period, the proxy reconnected to querycoord, which took less than a second

**Comment by DragonDriver** [comment]
![image](https://user-images.githubusercontent.com/31589260/142796075-b26edbf5-3948-47d7-88ff-7cef3e62024a.png)

**Comment by DragonDriver** [comment]
`Flush` here is too slow, so other tasks in `ddl` queue time out.
Figuring out why `Flush` here is too slow.

**Comment by DragonDriver** [comment]
![image](https://user-images.githubusercontent.com/31589260/142813127-0dc22fd3-60ab-4faa-9a44-d04662e29d86.png)

Sorry, I made a mistake. In fact, `ShowCollections` is the last complete operation in `ddl` queue. Then `LoadCollection` entered the queue later.
Figuring out why `LoadCollection` took so many time in Proxy.

**Comment by DragonDriver** [comment]
[2021/11/16 15:32:02.889 +00:00] [DEBUG] [impl.go:309] ["LoadCollection enqueue"] [role=proxy] [db=] [collection=search_collection_f7iE0esp]

[2021/11/16 15:32:02.890 +00:00] [DEBUG] [id.go:141] ["IDAllocator pickCanDoFunc"] [need=1] [total=171373] [remainReqCnt=0]

[2021/11/16 15:32:02.890 +00:00] [DEBUG] [impl.go:321] [LoadCollection] [role=proxy] [msgID=429149831408414676] [timestamp=429149840439246851] [db=] [collection=search_collection_f7iE0esp]

[2021/11/16 15:32:02.890 +00:00] [DEBUG] [task.go:4133] ["loadCollectionTask PreExecute"] [role=proxy] [msgID=429149831408414676]

[2021/11/16 15:32:02.890 +00:00] [DEBUG] [task.go:4147] ["loadCollectionTask Execute"] [role=proxy] [msgID=429149831408414676]

[2021/11/16 15:32:02.890 +00:00] [DEBUG] [task.go:4168] ["send LoadCollectionRequest to query coordinator"] [role=proxy] [msgID=429149831408414676] [collectionID=429149833361358849] [schema="name:\"search_collection_f7iE0esp\" fields:<fieldID:100 name:\"int64\" is_primary_key:true data_type:Int64 > fields:<fieldID:101 name:\"float\" data_type:Float > fields:<fieldID:102 name:\"float_vector\" data_type:FloatVector type_params:<key:\"dim\" value:\"128\" > > "]

[2021/11/16 15:32:02.890 +00:00] [DEBUG] [impl.go:135] ["LoadCollectionRequest received"] [role=querycoord] [msgID=429149831408414676] [collectionID=429149833361358849] [schema="name:\"search_collection_f7iE0esp\" fields:<fieldID:100 name:\"int64\" is_primary_key:true data_type:Int64 > fields:<fieldID:101 name:\"float\" data_type:Float > fields:<fieldID:102 name:\"float_vector\" data_type:FloatVector type_params:<key:\"dim\" value:\"128\" > > "]

[2021/11/16 15:32:02.890 +00:00] [DEBUG] [task_scheduler.go:455] ["EnQueue a triggerTask and save to etcd"] [taskID=429149438296460283]

**Comment by DragonDriver** [comment]
After send `LoadCollection` to qc, qc didn't answer until time out. And we didn't see any logs about "load collection search_collection_f7iE0esp" in qc.

**Comment by xige-16** [comment]
[2021/11/16 15:32:54.091 +00:00] [DEBUG] [cluster.go:232] ["loadSegments: queryNode load segments error"] [nodeID=7] ["error info"="rpc error: code = Unknown desc = Access Denied."]

**Comment by xige-16** [comment]
duplicate with issue #11969

**Comment by bigsheeper** [comment]
/assign @LoveEachDay 
/unassign
same reason with #11969

**Comment by LoveEachDay** [comment]
We've disable nfs cache on ci, assign back to qa to verify.
/unassign
/assign @binbinlv

**Comment by yanliang567** [comment]
/assign @ThreadDao 
please help to verify the fix @ThreadDao 
/unassign @binbinlv

**Comment by binbinlv** [comment]
Has not been reproduced for days, so close it and will reopen if it occurs again.
