### ISSUE TITLE
[Bug]: Load collection failed after compact and merge segments

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#11970]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20211117-9bd3664
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-2.0.0rc9.dev11
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others: enableCompaction: true
```

### Current Behavior

1. create a collection with `shard_num=1`
2. insert 1500 entities, flush
3. insert another 1500 entities, flush
4. compact and wait for it completed
5. get compact plans
6. load collection
7. raise exception
```
[2021-11-17 11:42:25,154 - DEBUG - ci_test]: (api_response) : {"name": "compact_hQWoL0NT", "schema": {"auto_id": false, "description": "", "fields": [{"name": "int64", "description": "", "type": 5, "is_primary": true, "auto_id": false}, {"name": "float", "description": "", "type": 10}, {"name": "float_vector", "description": "", "type": 101, "params": {"dim": ......  (api_request.py:21)
[2021-11-17 11:42:25,240 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [      int64   float                                       float_vector
0         0     0.0  [0.08361501853081017, 0.052939734239931084, 0....
1         1     1.0  [0.07908742562979258, 0.12271840016879328, 0.1...
2         2     2.0  [0.03933273929124697, 0.08666822661288238, 0.0...
3         3    ......, kwargs: {'timeout': 20} (api_request.py:44)
[2021-11-17 11:42:32,146 - DEBUG - ci_test]: (api_response) : (insert count: 1500, delete count: 0, upsert count: 0, timestamp: 429161330002100225)  (api_request.py:21)
[2021-11-17 11:42:36,134 - DEBUG - ci_test]: 1500 (test_compaction.py:268)
[2021-11-17 11:42:36,181 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [      int64   float                                       float_vector
1500   1500  1500.0  [0.08353557924420224, 0.07817128419182166, 0.0...
1501   1501  1501.0  [0.07593527140223755, 0.10503382344142562, 0.0...
1502   1502  1502.0  [0.10648220554060715, 0.07489292437999703, 0.0...
1503   1503  15......, kwargs: {'timeout': 20} (api_request.py:44)
[2021-11-17 11:42:42,943 - DEBUG - ci_test]: (api_response) : (insert count: 1500, delete count: 0, upsert count: 0, timestamp: 429161332833255426)  (api_request.py:21)
[2021-11-17 11:42:46,029 - DEBUG - ci_test]: 3000 (test_compaction.py:271)
[2021-11-17 11:42:46,029 - DEBUG - ci_test]: (api_request)  : [Collection.compact] args: [20], kwargs: {} (api_request.py:44)
[2021-11-17 11:42:46,045 - DEBUG - ci_test]: (api_response) : None  (api_request.py:21)
[2021-11-17 11:42:47,064 - DEBUG - ci_test]: (api_request)  : [Collection.get_compaction_plans] args: [20], kwargs: {} (api_request.py:44)
[2021-11-17 11:42:47,073 - DEBUG - ci_test]: (api_response) : 
Compaction Plans:
 - compaction id: 429161333659009025
 - state: 2
 - plans: [
Plan:
 - sources: [429161330002100225, 429161332833255425]
 - target: 429161333659009027
]
   (api_request.py:21)
[2021-11-17 11:42:47,073 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None], kwargs: {'timeout': 20} (api_request.py:44)
[2021-11-17 11:42:51,366 - ERROR - ci_test]: Traceback (most recent call last):
  File "/home/zong/zong/projects/milvus/tests/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/home/zong/zong/projects/milvus/tests/python_client/utils/api_request.py", line 45, in api_request
    return func(*arg, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 449, in load
    conn.load_collection(self._name, timeout=timeout, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 58, in handler
    raise e
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 42, in handler
    return func(self, *args, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 322, in load_collection
    return handler.load_collection("", collection_name=collection_name, timeout=timeout, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler
    raise e
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    return func(self, *args, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 823, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler
    raise e
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    return func(self, *args, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 841, in wait_for_loading_collection
    return self._wait_for_loading_collection_v2(collection_name, timeout)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 868, in _wait_for_loading_collection_v2
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=rpc error: code = Unknown desc = collection has not been loaded to memory or load failed)>
 (api_request.py:26)
[2021-11-17 11:42:51,367 - ERROR - ci_test]: (api_response) : <BaseException: (code=1, message=rpc error: code = Unknown desc = collection has not been loaded to memory or load failed)> (api_request.py:27)
FAILED
```

### Expected Behavior

Load merged segment successfully

### Steps To Reproduce

```markdown
def test_compact_merge_two_segments(self):
        """
        target: test compact merge two segments
        method: 1.create with shard_num=1
                2.insert half nb and flush
                3.insert half nb and flush
                4.compact
                5.search
        expected: Verify segments are merged
        """
        half = ct.default_nb // 2
        # create collection
        collection_w = self.init_collection_wrap(name=cf.gen_unique_str(prefix), shards_num=1)
        df = cf.gen_default_dataframe_data()
        res, _ = collection_w.insert(df[:half])
        log.debug(collection_w.num_entities)

        collection_w.insert(df[half:])
        log.debug(collection_w.num_entities)

        collection_w.compact()
        collection_w.wait_for_compaction_completed(timeout=40)
        collection_w.get_compaction_plans()[0]

        collection_w.load()
```
```


### Anything else?

**Comment by ThreadDao** [comment]
[milvus_logs.tar.gz](https://github.com/milvus-io/milvus/files/7551617/milvus_logs.tar.gz)

**Comment by sunby** [comment]
@XuanYang-cn DataNode add a deltaInfo item if there's no delta log. And QueryNode read empty blobs form it.
