### ISSUE TITLE
[Bug]: datanode crash 

### ISSUE THREAD

**Issue by JamCrash** [milvus-io/milvus#11974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: rc8
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus rc8 
- OS(Ubuntu or CentOS):  Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

[2021/11/17 04:25:44.172 +00:00] [DEBUG] [flow_graph_dd_node.go:107] ["DDNode receive insert messages"]
[2021/11/17 04:25:44.172 +00:00] [INFO] [flow_graph_dd_node.go:116] ["Filtering Insert Messages"] ["Message endts"=429161888733724673] [FilterThreshold=429161995020009473]
[2021/11/17 04:25:44.172 +00:00] [DEBUG] [flow_graph_dd_node.go:107] ["DDNode receive insert messages"]
[2021/11/17 04:25:44.172 +00:00] [INFO] [flow_graph_dd_node.go:116] ["Filtering Insert Messages"] ["Message endts"=429161888733724673] [FilterThreshold=429161995020009473]
[2021/11/17 04:25:44.172 +00:00] [DEBUG] [flow_graph_dd_node.go:107] ["DDNode receive insert messages"]
[2021/11/17 04:25:44.172 +00:00] [INFO] [flow_graph_dd_node.go:116] ["Filtering Insert Messages"] ["Message endts"=429161888733724673] [FilterThreshold=429161995020009473]
[2021/11/17 04:25:44.658 +00:00] [DEBUG] [segment_replica.go:233] ["Add new segment"] ["segment ID"=429161890752233473] ["collection ID"=429161841469161473] ["partition ID"=429161841469161474] ["channel name"=test-rootcoord-dml_8_429161841469161473v0]
[2021/11/17 04:25:44.658 +00:00] [DEBUG] [segment_replica.go:550] ["updating segment"] ["Segment ID"=429161890752233473] [numRows=1499672]
[2021/11/17 04:25:44.658 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:668] ["Updating segments statistics..."]
[2021/11/17 04:25:44.658 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:677] ["Segment Statistics to Update"] ["Segment ID"=429161890752233473] [NumOfRows=1499672]
[2021/11/17 04:26:02.516 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:214] ["insert seg buffer status"] [No.=0] [segmentID=429161890752233473] ["buffer size"=1499672] ["buffer limit"=65536]
[2021/11/17 04:26:02.516 +00:00] [WARN] [flow_graph_insert_buffer_node.go:233] ["Auto flush"] ["segment id"=429161890752233473]
panic: runtime error: slice bounds out of range [::384126461] with length 268435456
goroutine 270 [running]:
github.com/milvus-io/milvus/internal/storage.(*PayloadWriter).GetPayloadBufferFromWriter(0xc00a9f0060, 0x0, 0x0, 0x695348, 0x4, 0xc025a37660)
/go/src/github.com/milvus-io/milvus/internal/storage/payload.go:388 +0xd2
github.com/milvus-io/milvus/internal/storage.(*baseEventWriter).GetMemoryUsageInBytes(0xc00b7a6000, 0x0, 0x0, 0x11)
/go/src/github.com/milvus-io/milvus/internal/storage/event_writer.go:133 +0x3b
github.com/milvus-io/milvus/internal/storage.(*baseEventWriter).Finish(0xc00b7a6000, 0x0, 0x0)
/go/src/github.com/milvus-io/milvus/internal/storage/event_writer.go:164 +0x73
github.com/milvus-io/milvus/internal/storage.(*baseBinlogWriter).Close(0xc0006800c0, 0xc025aba030, 0x2621509)
/go/src/github.com/milvus-io/milvus/internal/storage/binlog_writer.go:110 +0x21b
github.com/milvus-io/milvus/internal/storage.(*InsertCodec).Serialize(0xc01f7ed700, 0x5f4b06bc7ec0002, 0x5f4b077416c0001, 0xc00a969e40, 0x5f4b06bc7ec0002, 0xc000b8ba00, 0x0, 0x0, 0xc0101c2000, 0xc00a9671c8, ...)
/go/src/github.com/milvus-io/milvus/internal/storage/data_codec.go:319 +0x4b5
github.com/milvus-io/milvus/internal/datanode.(*rendezvousFlushManager).flushBufferData(0xc000c04240, 0xc00a969e20, 0x5f4b077416c0001, 0x0, 0xc00a93c2a0, 0x1, 0xc00a93a760)
/go/src/github.com/milvus-io/milvus/internal/datanode/flush_manager.go:239 +0x1e7
github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Operate(0xc0004a7790, 0xc00a92bea0, 0x1, 0x1, 0x2817160, 0xc00a937200, 0x0)
/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:278 +0x126c
github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work(0xc000739260)
/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:79 +0xda
created by github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start
/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:56 +0x55

**Comment by yanliang567** [comment]
@JamCrash could you please share more info, e.g repro steps, scripts you used to insert data?
