### ISSUE TITLE
[Bug]: Milvus is crashed during CI

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#11987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: latest 
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2): latest
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Milvus is crashed.

Milvus Logs: [standalone]
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-11982/1/artifacts/

Some clues in milvus log: [0.log]
```
2021-11-17T07:23:04.50990417Z stdout F [2021/11/17 07:23:04.509 +00:00] [WARN] [flush_manager.go:498] ["failed to SaveBinlogPaths"] [error="All attempts results:\nattempt #1:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_163_429164790432923649v1 is not watched on node 7\nattempt #2:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_163_429164790432923649v1 is not watched on node 7\nattempt #3:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_163_429164790432923649v1 is not watched on node 7\nattempt #4:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_163_429164790432923649v1 is not watched on node 7\nattempt #5:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_163_429164790432923649v1 is not watched on node 7\nattempt #6:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_163_429164790432923649v1 is not watched on node 7\nattempt #7:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_163_429164790432923649v1 is not watched on node 7\nattempt #8:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_163_429164790432923649v1 is not watched on node 7\nattempt #9:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_163_429164790432923649v1 is not watched on node 7\nattempt #10:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_163_429164790432923649v1 is not watched on node 7\n"]
2021-11-17T07:23:04.513305966Z stderr F panic: All attempts results:
2021-11-17T07:23:04.513313955Z stderr F attempt #1:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_163_429164790432923649v1 is not watched on node 7
2021-11-17T07:23:04.51331977Z stderr F attempt #2:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_163_429164790432923649v1 is not watched on node 7
2021-11-17T07:23:04.513326613Z stderr F attempt #3:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_163_429164790432923649v1 is not watched on node 7
2021-11-17T07:23:04.513328544Z stderr F attempt #4:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_163_429164790432923649v1 is not watched on node 7
2021-11-17T07:23:04.513330279Z stderr F attempt #5:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_163_429164790432923649v1 is not watched on node 7
2021-11-17T07:23:04.513332037Z stderr F attempt #6:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_163_429164790432923649v1 is not watched on node 7
2021-11-17T07:23:04.51333384Z stderr F attempt #7:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_163_429164790432923649v1 is not watched on node 7
2021-11-17T07:23:04.513335654Z stderr F attempt #8:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_163_429164790432923649v1 is not watched on node 7
2021-11-17T07:23:04.513337368Z stderr F attempt #9:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_163_429164790432923649v1 is not watched on node 7
2021-11-17T07:23:04.5133391Z stderr F attempt #10:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_163_429164790432923649v1 is not watched on node 7
2021-11-17T07:23:04.513340752Z stderr F
2021-11-17T07:23:04.513342573Z stderr F
2021-11-17T07:23:04.513344375Z stderr F goroutine 1659294 [running]:
2021-11-17T07:23:04.513346399Z stderr F github.com/milvus-io/milvus/internal/datanode.flushNotifyFunc.func1(0xc0055296d0)
2021-11-17T07:23:04.513348755Z stderr F         /go/src/github.com/milvus-io/milvus/internal/datanode/flush_manager.go:500 +0x132d
2021-11-17T07:23:04.51335049Z stderr F github.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).waitFinish(0xc000943380, 0xc001bb0360, 0xc002b56fd0)
2021-11-17T07:23:04.513352637Z stderr F         /go/src/github.com/milvus-io/milvus/internal/datanode/flush_task.go:150 +0xc5
```

Test logs:
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-11982/1/pipeline/71

Some clues:

1. Failed case: 
```
[2021-11-17T07:23:41.846Z] [gw0] [ 73%] FAILED testcases/test_search_20.py::TestCollectionSearch::test_search_with_expression[8-False-int64 not in [1, 2, 3]] 
```

2. Collectin name: search_collection_NHVNzR05

3. Timeline:
```
[2021-11-17T07:23:48.396Z] [2021-11-17 07:23:03 - DEBUG - ci_test]: (api_request)  : [Collection] args: ['search_collection_NHVNzR05', {"auto_id": false, "description": "", "fields": [{"name": "int64", "description": "", "type": 5, "is_primary": true, "auto_id": false}, {"name": "float", "description": "", "type": 10}, {"name": "float_vector", "description": "", "type": 101, "params": {"dim": 8}}]}, '......, kwargs: {} (api_request.py:44)

[2021-11-17T07:23:48.396Z] [2021-11-17 07:23:04 - ERROR - pymilvus.client.grpc_handler]: 

[2021-11-17T07:23:48.396Z] Addr [172.18.255.155:19530] has_collection

[2021-11-17T07:23:48.396Z] RPC error: <_MultiThreadedRendezvous of RPC that terminated with:

[2021-11-17T07:23:48.396Z] 	status = StatusCode.UNAVAILABLE

[2021-11-17T07:23:48.396Z] 	details = "Socket closed"

[2021-11-17T07:23:48.396Z] 	debug_error_string = "{"created":"@1637133784.554645598","description":"Error received from peer ipv4:172.18.255.155:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Socket closed","grpc_status":14}"
```

### Expected Behavior

No crash

### Steps To Reproduce

```markdown
Running CI
```

**Comment by XuanYang-cn** [comment]
I've encountered the same error.

Caused by start-positions not set properly

**Comment by binbinlv** [comment]
@sunby, OK, verifying it. And this issue is not reproduced each time, so will close it after verification.

**Comment by xiaofan-luan** [comment]
assign @binbinlv

**Comment by binbinlv** [comment]
Verified, and fixed,  so closed.
