### ISSUE TITLE
[Bug]: Insert failed after Milvus restart

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#12060]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: `d35bd76`
- Deployment mode(standalone or cluster): standalone and cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.0.0rc9.dev3
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

raise error when inserting data
```
Error: <BaseException: (code=1, message=GetSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error)>
Traceback (most recent call last):
  File "scripts/action_reinstall.py", line 13, in <module>
    create_collections_and_insert_data()
  File "/home/yanliang/workspace/milvus/tests/python_client/deploy/scripts/utils.py", line 83, in create_collections_and_insert_data
    collection.insert(
  File "/home/yanliang/anaconda3/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 530, in insert
    res = conn.insert(collection_name=self._name, entities=entities, ids=None,
  File "/home/yanliang/anaconda3/lib/python3.8/site-packages/pymilvus/client/stub.py", line 61, in handler
    raise e
  File "/home/yanliang/anaconda3/lib/python3.8/site-packages/pymilvus/client/stub.py", line 45, in handler
    return func(self, *args, **kwargs)
  File "/home/yanliang/anaconda3/lib/python3.8/site-packages/pymilvus/client/stub.py", line 909, in insert
    return handler.bulk_insert(collection_name, entities, partition_name, timeout, **kwargs)
  File "/home/yanliang/anaconda3/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler
    raise e
  File "/home/yanliang/anaconda3/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
    return func(self, *args, **kwargs)
  File "/home/yanliang/anaconda3/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 505, in bulk_insert
    raise err
  File "/home/yanliang/anaconda3/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 501, in bulk_insert
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=GetSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error)>
```

### Expected Behavior

works well

### Steps To Reproduce

```markdown
cd `tests/python_client/deploy`
run script
`bash test.sh -t reinstall -m standalone -p ${root_password}`
```

### Anything else?

[standalone-reinstall-2021-11-18-11-47-05.log](https://github.com/milvus-io/milvus/files/7559789/standalone-reinstall-2021-11-18-11-47-05.log)

**Comment by yanliang567** [comment]
@congqixia please help to take a look at this issue, it blocks data compatibility test in reinstall part.
/assign @congqixia 
/unassign

**Comment by zhuwenxing** [comment]
Verified and passed
