### ISSUE TITLE
[Bug]: Index files in minio are deleted without drop operations when GC is enabled

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#12229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 18463eb
- Deployment mode(standalone or cluster): both
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc9.dev15
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Index files are deleted in minio before drop colleciton

And load:
```
Error: <BaseException: (code=1, message=call query coordinator LoadCollection: rpc error: code = Unknown desc = , The specified key does not exist.)>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 454, in load
    conn.load_collection(self._name, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 58, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 42, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 322, in load_collection
    return handler.load_collection("", collection_name=collection_name, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 820, in load_collection
    raise BaseException(response.error_code, response.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=call query coordinator LoadCollection: rpc error: code = Unknown desc = , The specified key does not exist.)>
```

### Expected Behavior

Index files are not deleted in minio without collection drop

### Steps To Reproduce
1 Set the env:
Enable GC and set clean time
in milvus.yaml:
enableGarbageCollection: true
gc:
interval: 60 # gc interval in seconds
missingTolerance: 60 # file meta missing tolerance duration in seconds, 1 day
dropTolerance: 60 # file belongs to dropped entity tolerance duration in seconds, 1 day

2 create collection, insert, create index, load

```python
from pymilvus import CollectionSchema, FieldSchema
from pymilvus import Collection
from pymilvus import connections
from pymilvus import DataType
from pymilvus import Partition
from pymilvus import utility

dim = 128
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
schema = CollectionSchema(fields=[int64_field, float_field, float_vector])
connections.connect()
import numpy as np
collection = Collection("test_search_collection_binbin_1", schema=schema)
nb = 3000
nq = 2
limit = 10
import random
default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors])
collection.num_entities
default_index = {"index_type": "IVF_PQ", "params":{"nlist": 128, "m": 16, "nbits": 8}, "metric_type": "L2"}
collection.create_index("float_vector", default_index)
collection.load()
```

**Comment by binbinlv** [comment]
Logs:
[12229.tar.zip](https://github.com/milvus-io/milvus/files/7586946/12229.tar.zip)

Collection name: test_search_collection_binbin_1

**Comment by binbinlv** [comment]
New function issue, set as urgent.

**Comment by xiaocai2333** [comment]
DataCoord traverses the root path in minio during GC, but there is no meta for index files in DataCoord, so the path of index files is listed in the queue that needs to be recycled. As soon as the GC time is up, the index files are deleted.

**Comment by congqixia** [comment]
/reopen
/unassign
/unassign @xiaocai2333 
/assign @binbinlv 
The fixing pr has been merged. Could you please verify? @binbinlv

**Comment by binbinlv** [comment]
@congqixia OK, working on it.

**Comment by binbinlv** [comment]
Verified and fixed.

milvus: 62bbc9c
pymilvus: 2.0.0rc9.dev17
