### ISSUE TITLE
[Bug]: Milvus crashed with panic when enabling compaction and GC

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#12265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: latest
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): latest
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Milvus is crashed with panic
```
d-dml_234_429327338027614209v0 is not watched on node 7\nattempt #2:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_234_429327338027614209v0 is not watched on node 7\nattempt #3:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_234_429327338027614209v0 is not watched on node 7\nattempt #4:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_234_429327338027614209v0 is not watched on node 7\nattempt #5:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_234_429327338027614209v0 is not watched on node 7\nattempt #6:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_234_429327338027614209v0 is not watched on node 7\nattempt #7:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_234_429327338027614209v0 is not watched on node 7\nattempt #8:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_234_429327338027614209v0 is not watched on node 7\nattempt #9:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_234_429327338027614209v0 is not watched on node 7\nattempt #10:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_234_429327338027614209v0 is not watched on node 7\n"]
2021-11-24T11:37:32.426529677Z stderr F panic: All attempts results:
2021-11-24T11:37:32.426567598Z stderr F attempt #1:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_234_429327338027614209v0 is not watched on node 7
2021-11-24T11:37:32.426572509Z stderr F attempt #2:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_234_429327338027614209v0 is not watched on node 7
2021-11-24T11:37:32.426574623Z stderr F attempt #3:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_234_429327338027614209v0 is not watched on node 7
2021-11-24T11:37:32.426594442Z stderr F attempt #4:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_234_429327338027614209v0 is not watched on node 7
2021-11-24T11:37:32.42659899Z stderr F attempt #5:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_234_429327338027614209v0 is not watched on node 7
2021-11-24T11:37:32.426602122Z stderr F attempt #6:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_234_429327338027614209v0 is not watched on node 7
2021-11-24T11:37:32.426604116Z stderr F attempt #7:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_234_429327338027614209v0 is not watched on node 7
2021-11-24T11:37:32.426606019Z stderr F attempt #8:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_234_429327338027614209v0 is not watched on node 7
2021-11-24T11:37:32.426624374Z stderr F attempt #9:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_234_429327338027614209v0 is not watched on node 7
2021-11-24T11:37:32.426628487Z stderr F attempt #10:data service save bin log path failed, reason = channel by-dev-rootcoord-dml_234_429327338027614209v0 is not watched on node 7
2021-11-24T11:37:32.426630482Z stderr F
2021-11-24T11:37:32.426633033Z stderr F
2021-11-24T11:37:32.426634914Z stderr F goroutine 247170 [running]:
2021-11-24T11:37:32.426688175Z stderr F github.com/milvus-io/milvus/internal/datanode.flushNotifyFunc.func1(0xc001cf6690)
2021-11-24T11:37:32.426695234Z stderr F         /go/src/github.com/milvus-io/milvus/internal/datanode/flush_manager.go:509 +0x1439
2021-11-24T11:37:32.426697399Z stderr F github.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).waitFinish(0xc006768600, 0xc00a7c9020, 0xc00c779c90)
2021-11-24T11:37:32.426719453Z stderr F         /go/src/github.com/milvus-io/milvus/internal/datanode/flush_task.go:186 +0xbd
2021-11-24T11:37:32.426759007Z stderr F created by github.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).init.func1
2021-11-24T11:37:32.426763191Z stderr F         /go/src/github.com/milvus-io/milvus/internal/datanode/flush_task.go:118 +0xb0
```

### Expected Behavior

No panic

### Steps To Reproduce

1 Start milvus with compaction and GC enabled:

```
--set dataCoordinator.enableCompaction="true" \
--set dataCoordinator.enableGarbageCollection="true" \
--set dataCoordinator.gc.interval=60 \
--set dataCoordinator.gc.missingTolerance=60 \
--set dataCoordinator.gc.dropTolerance=60 \
```

2 Runnig CI test cases

**Comment by binbinlv** [comment]
Logs:
[12265.tar.zip](https://github.com/milvus-io/milvus/files/7595412/12265.tar.zip)

panic is in "kind-worker/pods/default_ms-milvus-standalone-f5b68fc4d-ps9jk_72682743-4880-48ab-83a4-7ebcf4587c68/standalone/0.log".

**Comment by binbinlv** [comment]
Here I enabled compaction and clean up together>

But only enable clean up, CI test cases passed.

So the root cause may be related to compaction or the combination of compaction and clean data (GC) function.

**Comment by binbinlv** [comment]
Updated:
Retested the scenario only enabling compaction, CI test cases pass, so summary:

(1) enable compaction + GC, CI test cases fail with panic
(2) enable compaction, CI tests Good
(3) enable GC, CI tests Good

**Comment by congqixia** [comment]
Find the cause for panicking:
- When Drop Collection, datacoord skips `compacted to` segments in case of meta mismatch from datanode. So after all `normal`(uncompacted) segment dropped, the vchannel is unwatched from related datanode
- Data node try to SaveBinlogPaths of `compacted to` segment with dropped flag but found vchannel unwatched
- After 10 retry with same failure, datanode panicked

@sunby and I will try to find a workable solution for this case.

**Comment by congqixia** [comment]
@binbinlv Fixing PR has been merge. Could you please verify? 
/unassign @congqixia @sunby 
/assign @binbinlv

**Comment by binbinlv** [comment]
OK， working on it. Thanks.

**Comment by binbinlv** [comment]
Verified, but panic still exist.

milvus: 2ee0c7c
pymilvus: 2.0.0rc9.dev19

[reproduced.log.zip](https://github.com/milvus-io/milvus/files/7601129/reproduced.log.zip)

**Comment by binbinlv** [comment]
[reproduced.tar.zip](https://github.com/milvus-io/milvus/files/7601156/reproduced.tar.zip)

Maybe the format uploaded before is not right, re-upload.

**Comment by congqixia** [comment]
@binbinlv Fixed another bug. Could you please this problem still exists?
/unassign
/assign @binbinlv

**Comment by binbinlv** [comment]
OK， working on it.

**Comment by binbinlv** [comment]
Verified, but panic again.

Milvus: ad83090
pymilvus: 2.0.0rc9.dev19

Logs:
[reproduced1.tar.zip](https://github.com/milvus-io/milvus/files/7602608/reproduced1.tar.zip)

**Comment by binbinlv** [comment]
Same panic occurs in nightly, [only enabling compaction]:


Logs:

https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/230/

```
panic: All attempts results:

attempt #1:data service save bin log path failed, reason = failed to get segment 429353166901870597

attempt #2:data service save bin log path failed, reason = failed to get segment 429353166901870597

attempt #3:data service save bin log path failed, reason = failed to get segment 429353166901870597

attempt #4:data service save bin log path failed, reason = failed to get segment 429353166901870597

attempt #5:data service save bin log path failed, reason = failed to get segment 429353166901870597

attempt #6:data service save bin log path failed, reason = failed to get segment 429353166901870597

attempt #7:data service save bin log path failed, reason = failed to get segment 429353166901870597

attempt #8:data service save bin log path failed, reason = failed to get segment 429353166901870597

attempt #9:data service save bin log path failed, reason = failed to get segment 429353166901870597

attempt #10:data service save bin log path failed, reason = failed to get segment 429353166901870597
```

**Comment by xige-16** [comment]
```
[2021/11/25 14:59:33.086 +00:00] [INFO] [impl.go:2591] ["received get flush state request"] [request="segmentIDs:429353171804225537 segmentIDs:429353171804225538 "]

[2021/11/25 14:59:33.087 +00:00] [DEBUG] [services.go:853] ["received get flush state request"] ["segment ids"="[429353171804225537,429353171804225538]"] [len=2]

[2021/11/25 14:59:33.087 +00:00] [DEBUG] [services.go:876] ["unflushed segment ids"] ["segment ids"="[429353171804225537,429353171804225538]"] [len=2]

[2021/11/25 14:59:33.087 +00:00] [INFO] [impl.go:2601] ["received get flush state response"] [response="status:<> "]

[2021/11/25 14:59:33.093 +00:00] [WARN] [flush_manager.go:508] ["failed to SaveBinlogPaths"] [error="All attempts results:\nattempt #1:data service save bin log path failed, reason = failed to get segment 429353166901870597\nattempt #2:data service save bin log path failed, reason = failed to get segment 429353166901870597\nattempt #3:data service save bin log path failed, reason = failed to get segment 429353166901870597\nattempt #4:data service save bin log path failed, reason = failed to get segment 429353166901870597\nattempt #5:data service save bin log path failed, reason = failed to get segment 429353166901870597\nattempt #6:data service save bin log path failed, reason = failed to get segment 429353166901870597\nattempt #7:data service save bin log path failed, reason = failed to get segment 429353166901870597\nattempt #8:data service save bin log path failed, reason = failed to get segment 429353166901870597\nattempt #9:data service save bin log path failed, reason = failed to get segment 429353166901870597\nattempt #10:data service save bin log path failed, reason = failed to get segment 429353166901870597\n"]

panic: All attempts results:

attempt #1:data service save bin log path failed, reason = failed to get segment 429353166901870597

attempt #2:data service save bin log path failed, reason = failed to get segment 429353166901870597

attempt #3:data service save bin log path failed, reason = failed to get segment 429353166901870597

attempt #4:data service save bin log path failed, reason = failed to get segment 429353166901870597

attempt #5:data service save bin log path failed, reason = failed to get segment 429353166901870597

attempt #6:data service save bin log path failed, reason = failed to get segment 429353166901870597

attempt #7:data service save bin log path failed, reason = failed to get segment 429353166901870597

attempt #8:data service save bin log path failed, reason = failed to get segment 429353166901870597

attempt #9:data service save bin log path failed, reason = failed to get segment 429353166901870597

attempt #10:data service save bin log path failed, reason = failed to get segment 429353166901870597





goroutine 105517 [running]:

github.com/milvus-io/milvus/internal/datanode.flushNotifyFunc.func1(0xc009906280)

	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_manager.go:510 +0x1599

github.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).waitFinish(0xc00983e0c0, 0xc0094c2b10, 0xc006d11c40)

	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_task.go:186 +0xbd

created by github.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).init.func1

	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_task.go:118 +0xb0
```

**Comment by xige-16** [comment]
> ```
> [2021/11/25 14:59:33.086 +00:00] [INFO] [impl.go:2591] ["received get flush state request"] [request="segmentIDs:429353171804225537 segmentIDs:429353171804225538 "]
> 
> [2021/11/25 14:59:33.087 +00:00] [DEBUG] [services.go:853] ["received get flush state request"] ["segment ids"="[429353171804225537,429353171804225538]"] [len=2]
> 
> [2021/11/25 14:59:33.087 +00:00] [DEBUG] [services.go:876] ["unflushed segment ids"] ["segment ids"="[429353171804225537,429353171804225538]"] [len=2]
> 
> [2021/11/25 14:59:33.087 +00:00] [INFO] [impl.go:2601] ["received get flush state response"] [response="status:<> "]
> 
> [2021/11/25 14:59:33.093 +00:00] [WARN] [flush_manager.go:508] ["failed to SaveBinlogPaths"] [error="All attempts results:\nattempt #1:data service save bin log path failed, reason = failed to get segment 429353166901870597\nattempt #2:data service save bin log path failed, reason = failed to get segment 429353166901870597\nattempt #3:data service save bin log path failed, reason = failed to get segment 429353166901870597\nattempt #4:data service save bin log path failed, reason = failed to get segment 429353166901870597\nattempt #5:data service save bin log path failed, reason = failed to get segment 429353166901870597\nattempt #6:data service save bin log path failed, reason = failed to get segment 429353166901870597\nattempt #7:data service save bin log path failed, reason = failed to get segment 429353166901870597\nattempt #8:data service save bin log path failed, reason = failed to get segment 429353166901870597\nattempt #9:data service save bin log path failed, reason = failed to get segment 429353166901870597\nattempt #10:data service save bin log path failed, reason = failed to get segment 429353166901870597\n"]
> 
> panic: All attempts results:
> 
> attempt #1:data service save bin log path failed, reason = failed to get segment 429353166901870597
> 
> attempt #2:data service save bin log path failed, reason = failed to get segment 429353166901870597
> 
> attempt #3:data service save bin log path failed, reason = failed to get segment 429353166901870597
> 
> attempt #4:data service save bin log path failed, reason = failed to get segment 429353166901870597
> 
> attempt #5:data service save bin log path failed, reason = failed to get segment 429353166901870597
> 
> attempt #6:data service save bin log path failed, reason = failed to get segment 429353166901870597
> 
> attempt #7:data service save bin log path failed, reason = failed to get segment 429353166901870597
> 
> attempt #8:data service save bin log path failed, reason = failed to get segment 429353166901870597
> 
> attempt #9:data service save bin log path failed, reason = failed to get segment 429353166901870597
> 
> attempt #10:data service save bin log path failed, reason = failed to get segment 429353166901870597
> 
> 
> 
> 
> 
> goroutine 105517 [running]:
> 
> github.com/milvus-io/milvus/internal/datanode.flushNotifyFunc.func1(0xc009906280)
> 
> 	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_manager.go:510 +0x1599
> 
> github.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).waitFinish(0xc00983e0c0, 0xc0094c2b10, 0xc006d11c40)
> 
> 	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_task.go:186 +0xbd
> 
> created by github.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).init.func1
> 
> 	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_task.go:118 +0xb0
> ```

Latest nightly hangs issue:

https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/231/pipeline/91

Logs:
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/231/artifacts

**Comment by zhuwenxing** [comment]
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/activity?branch=PR-12503 
This PR has 4 attempts, but all of them are failed at  `testcases/test_collection.py::TestLoadCollection::test_load_collection_after_index` this case

**Comment by binbinlv** [comment]
@congqixia hi, congqi, how is the fix going?

Thanks.

**Comment by congqixia** [comment]
> @congqixia hi, congqi, how is the fix going?
> 
> Thanks.

@binbinlv  Waiting for the final PR

**Comment by congqixia** [comment]
@binbinlv fixing PRs have been merged. Could you please verify?
/unassign
/assign @binbinlv

**Comment by binbinlv** [comment]
working on it.

**Comment by binbinlv** [comment]
Verified, and fixed.

Milvus: d40f4a6
pymilvus: rc9.dev22
