### ISSUE TITLE
[Bug]: [benchmark][cluster] Load collection error: syncTimestamp Failed:context canceled

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#12279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:DEBUG-12254-1
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus-2.0.0rc9.dev7
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

client pod:benchmark-tag-x65xq-689412990

client log:
```
[2021-11-25 05:26:39,648] [   DEBUG] - Row count: 1000000000 in collection: <sift_1b_128_l2> (milvus_benchmark.client:416)
[2021-11-25 05:26:39,649] [   DEBUG] - 1000000000 (milvus_benchmark.runners.locust:432)
[2021-11-25 05:26:39,650] [   DEBUG] - Start build index for last file (milvus_benchmark.runners.locust:434)
[2021-11-25 05:26:39,650] [    INFO] - Building index start, collection_name: sift_1b_128_l2, index_type: IVF_SQ8, metric_type: L2 (milvus_benchmark.client:273)
[2021-11-25 05:26:39,651] [    INFO] - {'nlist': 1024} (milvus_benchmark.client:275)
[2021-11-25 05:26:39,652] [   DEBUG] - collection: sift_1b_128_l2 Index params: {'index_type': 'IVF_SQ8', 'metric_type': 'L2', 'params': {'nlist': 1024}} (milvus_benchmark.client:281)
[2021-11-25 05:27:23,536] [   DEBUG] - Building index done, collection_name: sift_1b_128_l2, response: Status(code=0, message='') (milvus_benchmark.client:283)
[2021-11-25 05:27:23,537] [   DEBUG] - Milvus create_index run in 43.89s (milvus_benchmark.client:52)
[2021-11-25 05:27:23,538] [   DEBUG] - {'flush_time': 2.52, 'build_time': 43.89} (milvus_benchmark.runners.locust:438)
[2021-11-25 05:27:23,542] [   DEBUG] - Row count: 1000000000 in collection: <sift_1b_128_l2> (milvus_benchmark.client:416)
[2021-11-25 05:27:23,543] [    INFO] - 1000000000 (milvus_benchmark.runners.locust:439)
[2021-11-25 05:27:23,544] [    INFO] - Start load collection (milvus_benchmark.runners.locust:440)
[2021-11-25 06:36:41,470] [   ERROR] - Error: <BaseException: (code=1, message=syncTimestamp Failed:context canceled)> (pymilvus.client.grpc_handler:69)
[2021-11-25 06:36:41,472] [   ERROR] - Error: <BaseException: (code=1, message=syncTimestamp Failed:context canceled)> (pymilvus.client.grpc_handler:69)
[2021-11-25 06:36:41,473] [   ERROR] - <BaseException: (code=1, message=syncTimestamp Failed:context canceled)> (milvus_benchmark.main:117)
[2021-11-25 06:36:41,480] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 86, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/locust.py", line 442, in prepare
    self.milvus.load_collection()
  File "/src/milvus_benchmark/client.py", line 48, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 478, in load_collection
    return self._milvus.load_collection(collection_name, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 58, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 42, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 322, in load_collection
    return handler.load_collection("", collection_name=collection_name, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 823, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 841, in wait_for_loading_collection
    return self._wait_for_loading_collection_v2(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 868, in _wait_for_loading_collection_v2
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=syncTimestamp Failed:context canceled)>
 (milvus_benchmark.main:118)
[2021-11-25 06:36:41,481] [   DEBUG] - {'_version': '0.1', '_type': 'metric', 'run_id': 1637747049, 'mode': 'local', 'server': <milvus_benchmark.metrics.models.server.Server object at 0x7f32102db208>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware object at 0x7f32102dbc18>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7f32102db048>, 'status': 'RUN_FAILED', 'err_message': '', 'collection': {'dimension': 128, 'metric_type': 'l2', 'dataset_name': 'sift_1b_128_l2', 'collection_size': 1000000000, 'other_fields': None, 'ni_per': 50000, 'shards_num': None}, 'index': {'index_type': 'ivf_sq8', 'index_param': {'nlist': 1024}}, 'search': None, 'run_params': {'task': {'types': [{'type': 'query', 'weight': 20, 'params': {'top_k': 10, 'nq': 10, 'search_param': {'nprobe': 16}}}, {'type': 'load', 'weight': 1}, {'type': 'get', 'weight': 2, 'params': {'ids_length': 10}}], 'connection_num': 1, 'clients_num': 20, 'spawn_rate': 2, 'during_time': 864000}, 'connection_type': 'single'}, 'metrics': {'type': 'locust_random_performance', 'value': {}}, 'datetime': '2021-11-24 09:44:09.435566', 'type': 'metric'} (milvus_benchmark.metric.api:29)
```

### Expected Behavior

argo task：**benchmark-tag-x65xq**

test yaml：
```
client-configmap: client-random-locust-search-84h-1b
server-configmap: server-cluster-8c64m-datanode2-indexnode4-querynode6
```

server：
```
NAME                                                         READY   STATUS        RESTARTS   AGE    IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-tag-x65xq-1-etcd-0                                 1/1     Running       0          20h    10.97.17.93    qa-node014.zilliz.local   <none>           <none>
benchmark-tag-x65xq-1-etcd-1                                 1/1     Running       0          20h    10.97.17.97    qa-node014.zilliz.local   <none>           <none>
benchmark-tag-x65xq-1-etcd-2                                 1/1     Running       0          20h    10.97.17.96    qa-node014.zilliz.local   <none>           <none>
benchmark-tag-x65xq-1-milvus-datacoord-f46756849-cgmhj       1/1     Running       0          20h    10.97.19.116   qa-node016.zilliz.local   <none>           <none>
benchmark-tag-x65xq-1-milvus-datanode-7fbcc5dd7b-6d6fk       1/1     Running       0          20h    10.97.19.118   qa-node016.zilliz.local   <none>           <none>
benchmark-tag-x65xq-1-milvus-datanode-7fbcc5dd7b-9gdpc       1/1     Running       0          20h    10.97.19.114   qa-node016.zilliz.local   <none>           <none>
benchmark-tag-x65xq-1-milvus-indexcoord-74d4dd6c64-bq2vd     1/1     Running       0          20h    10.97.6.34     qa-node004.zilliz.local   <none>           <none>
benchmark-tag-x65xq-1-milvus-indexnode-7567fd6489-bp5rh      1/1     Running       0          20h    10.97.15.17    qa-node012.zilliz.local   <none>           <none>
benchmark-tag-x65xq-1-milvus-indexnode-7567fd6489-bwxfb      1/1     Running       0          20h    10.97.17.86    qa-node014.zilliz.local   <none>           <none>
benchmark-tag-x65xq-1-milvus-indexnode-7567fd6489-mtkt5      1/1     Running       0          20h    10.97.17.87    qa-node014.zilliz.local   <none>           <none>
benchmark-tag-x65xq-1-milvus-indexnode-7567fd6489-pbwfr      1/1     Running       0          20h    10.97.14.36    qa-node011.zilliz.local   <none>           <none>
benchmark-tag-x65xq-1-milvus-proxy-54b6d786df-s9x6h          0/1     Running       0          113s   10.97.14.28    qa-node011.zilliz.local   <none>           <none>
benchmark-tag-x65xq-1-milvus-proxy-54b6d786df-sng49          1/1     Terminating   0          20h    10.97.9.247    qa-node007.zilliz.local   <none>           <none>
benchmark-tag-x65xq-1-milvus-querycoord-98574f6cf-87t6g      1/1     Running       0          20h    10.97.19.117   qa-node016.zilliz.local   <none>           <none>
benchmark-tag-x65xq-1-milvus-querynode-96589666c-4mdcb       0/1     Running       0          112s   10.97.14.29    qa-node011.zilliz.local   <none>           <none>
benchmark-tag-x65xq-1-milvus-querynode-96589666c-4x57z       1/1     Terminating   0          20h    10.97.9.246    qa-node007.zilliz.local   <none>           <none>
benchmark-tag-x65xq-1-milvus-querynode-96589666c-gdwzm       1/1     Running       0          20h    10.97.15.18    qa-node012.zilliz.local   <none>           <none>
benchmark-tag-x65xq-1-milvus-querynode-96589666c-gv2tg       1/1     Running       0          20h    10.97.11.150   qa-node009.zilliz.local   <none>           <none>
benchmark-tag-x65xq-1-milvus-querynode-96589666c-jrdhv       1/1     Running       0          20h    10.97.17.88    qa-node014.zilliz.local   <none>           <none>
benchmark-tag-x65xq-1-milvus-querynode-96589666c-r6vlc       1/1     Running       0          20h    10.97.12.9     qa-node015.zilliz.local   <none>           <none>
benchmark-tag-x65xq-1-milvus-querynode-96589666c-tvxzv       1/1     Running       0          20h    10.97.19.119   qa-node016.zilliz.local   <none>           <none>
benchmark-tag-x65xq-1-milvus-rootcoord-6cd79977b9-mmxw5      1/1     Running       0          20h    10.97.19.115   qa-node016.zilliz.local   <none>           <none>
benchmark-tag-x65xq-1-minio-0                                1/1     Running       0          20h    10.97.10.63    qa-node008.zilliz.local   <none>           <none>
benchmark-tag-x65xq-1-minio-1                                1/1     Running       0          20h    10.97.10.67    qa-node008.zilliz.local   <none>           <none>
benchmark-tag-x65xq-1-minio-2                                1/1     Running       0          20h    10.97.10.62    qa-node008.zilliz.local   <none>           <none>
benchmark-tag-x65xq-1-minio-3                                1/1     Running       0          20h    10.97.10.65    qa-node008.zilliz.local   <none>           <none>
benchmark-tag-x65xq-1-pulsar-autorecovery-7f9984775b-v42hw   1/1     Running       0          20h    10.97.15.16    qa-node012.zilliz.local   <none>           <none>
benchmark-tag-x65xq-1-pulsar-bastion-5ff5cb6b9b-9snrx        1/1     Running       0          20h    10.97.7.73     qa-node005.zilliz.local   <none>           <none>
benchmark-tag-x65xq-1-pulsar-bookkeeper-0                    1/1     Running       3          20h    10.97.10.66    qa-node008.zilliz.local   <none>           <none>
benchmark-tag-x65xq-1-pulsar-bookkeeper-1                    1/1     Running       3          20h    10.97.14.37    qa-node011.zilliz.local   <none>           <none>
benchmark-tag-x65xq-1-pulsar-broker-578c496b7-pgv6t          1/1     Running       1          20h    10.97.7.75     qa-node005.zilliz.local   <none>           <none>
benchmark-tag-x65xq-1-pulsar-proxy-d45cbfb59-rxm74           2/2     Running       0          20h    10.97.8.177    qa-node006.zilliz.local   <none>           <none>
benchmark-tag-x65xq-1-pulsar-zookeeper-0                     1/1     Running       0          20h    10.97.10.64    qa-node008.zilliz.local   <none>           <none>
benchmark-tag-x65xq-1-pulsar-zookeeper-1                     1/1     Running       0          20h    10.97.10.68    qa-node008.zilliz.local   <none>           <none>
benchmark-tag-x65xq-1-pulsar-zookeeper-2                     1/1     Running       0          20h    10.97.10.69    qa-node008.zilliz.local   <none>           <none>
benchmark-tag-x65xq-1-pulsar-zookeeper-metadata-r7pcl        0/1     Completed     0          20h    10.97.7.74     qa-node005.zilliz.local   <none>           <none>
```

### Steps To Reproduce

```markdown
1、create collection
2、create index of IVF_SQ8
3、insert one billion vectors
4、flush collection
5、create index with the same params
6、load collection <- raise error of syncTimestamp Failed:context canceled
```

**Comment by xige-16** [comment]
A querynode is down, and the panic log is not recorded before it down, but it does not affect the load, because a querynode is restarted, and querycoord is also loading normally

**Comment by ThreadDao** [comment]
I also encountered this error.

1. Deploy milvus cluster image `master-20211124-1a8e2e5` with config
```
config:
    queryNode:
      gracefulTime: 0
    dataCoord:
      enableCompaction: true
      compaction:
        retentionDuration: 20
```
2. Run CI case (included compaction cases), all passed
`pytest --tags L0 L1 --host 10.98.0.7 -n 6`

3. After 18 hours, I try to create collection and get this error
```
[2021-11-25 14:49:12,760 - ERROR - ci_test]: Traceback (most recent call last):
  File "/home/zong/zong/projects/milvus/tests/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/home/zong/zong/projects/milvus/tests/python_client/utils/api_request.py", line 45, in api_request
    return func(*arg, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/orm/utility.py", line 294, in list_collections
    return _get_connection(using).list_collections()
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 58, in handler
    raise e
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 42, in handler
    return func(self, *args, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 390, in list_collections
    return handler.list_collections(timeout)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 74, in handler
    raise e
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 66, in handler
    return func(self, *args, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 406, in list_collections
    raise BaseException(status.error_code, status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=syncTimestamp Failed:context canceled)>
 (api_request.py:26)
```
**Pod name**
```
mic-compact-etcd-0                                    1/1     Running     0          23h
mic-compact-etcd-1                                    1/1     Running     0          23h
mic-compact-etcd-2                                    1/1     Running     0          23h
mic-compact-milvus-datacoord-d6bf4d7d7-q4x26          0/1     Running     1          18h
mic-compact-milvus-datanode-78455ff58-bkjdk           1/1     Running     2          18h
mic-compact-milvus-indexcoord-84db89fcb4-grkql        1/1     Running     0          18h
mic-compact-milvus-indexnode-c4ff7948f-4fm7f          0/1     Running     1          18h
mic-compact-milvus-proxy-7467b56bd8-w5fh9             1/1     Running     0          18h
mic-compact-milvus-querycoord-7d764978c9-bfdwc        0/1     Running     1          18h
mic-compact-milvus-querynode-64fd7b65c5-kvfj8         0/1     Running     1          18h
mic-compact-milvus-rootcoord-fcb75ff75-p78x4          1/1     Running     0          18h
mic-compact-minio-0                                   1/1     Running     0          23h
mic-compact-minio-1                                   1/1     Running     0          23h
mic-compact-minio-2                                   1/1     Running     0          23h
mic-compact-minio-3                                   1/1     Running     0          23h
mic-compact-pulsar-bookie-0                           1/1     Running     0          23h
mic-compact-pulsar-bookie-1                           1/1     Running     0          23h
mic-compact-pulsar-bookie-init-sswx4                  0/1     Completed   0          23h
mic-compact-pulsar-broker-0                           1/1     Running     1          23h
mic-compact-pulsar-broker-1                           1/1     Running     0          23h
mic-compact-pulsar-proxy-0                            1/1     Running     0          23h
mic-compact-pulsar-proxy-1                            1/1     Running     0          23h
mic-compact-pulsar-pulsar-init-2l82x                  0/1     Completed   0          23h
mic-compact-pulsar-recovery-0                         1/1     Running     0          23h
mic-compact-pulsar-toolset-0                          1/1     Running     0          23h
mic-compact-pulsar-zookeeper-0                        1/1     Running     0          23h
mic-compact-pulsar-zookeeper-1                        1/1     Running     0          23h
mic-compact-pulsar-zookeeper-2                        1/1     Running     0          23h
```

**Comment by cydrain** [comment]
seems related with #11918

**Comment by DragonDriver** [comment]
I guess it's the network problem caused this issue. Maybe we should record the schedule of all pods next time this issue occur.

Rootcoord depends on etcd to allocate tso. The timeout of AllocTimestmap request is `5s`.

Then analyze the log of `rootcoord`.

```
[2021/11/25 06:37:20.420 +00:00] [INFO] [grpclog.go:37] ["[core]Subchannel picks a new address \"benchmark-tag-x65xq-1-etcd:2379\" to connect"]
```

Rootcoord tried to reconnect etcd. `06:37:20.420`.

```
[2021/11/25 06:37:49.378 +00:00] [WARN] [grpclog.go:46] ["[core]grpc: addrConn.createTransport failed to connect to {benchmark-tag-x65xq-1-etcd:2379 benchmark-tag-x65xq-1-etcd <nil> 0 <nil>}. Err: connection error: desc = \"transport: Error while dialing dial tcp: lookup benchmark-tag-x65xq-1-etcd on 10.96.0.10:53: server misbehaving\". Reconnecting..."]
```

Until `06:37:49.378`, `rootcoord` didn't connect to `etcd` yet, which the gap is much more than the timeout--`5s`.

The ip of etcd `10.96.0.10` doesn't appear in [above](https://github.com/milvus-io/milvus/issues/12279#issue-1063271506) too. I wonder if there are any restart situations in etcd.

**Comment by DragonDriver** [comment]
Please help to check the network situations of the benchmark cluster. @LoveEachDay 
/assign @LoveEachDay

**Comment by LoveEachDay** [comment]
`10.96.0.10` is the dns service ip, according the error message `Error while dialing dial tcp: lookup benchmark-tag-x65xq-1-etcd on 10.96.0.10:53: server misbehaving`, rootcoord failed to connect to etcd, because it cannot get the ip address from the dns.

So it's reasonable to raise error.

**Comment by xiaofan-luan** [comment]
> `10.96.0.10` is the dns service ip, according the error message `Error while dialing dial tcp: lookup benchmark-tag-x65xq-1-etcd on 10.96.0.10:53: server misbehaving`, rootcoord failed to connect to etcd, because it cannot get the ip address from the dns.
> 
> So it's reasonable to raise error.

Any guess why does it can not connect to the dns?

**Comment by LoveEachDay** [comment]
> Any guess why does it can not connect to the dns?
I guess that coredns server returns a `SERVFAIL` response code for this query. 
We need a dashboard for monitoring coredns.

**Comment by yanliang567** [comment]
remove urgent, as it reproduces occasionally.

**Comment by wangting0128** [comment]
lets keep it for tracking

**Comment by czs007** [comment]
can we close this issue ? @wangting0128

**Comment by wangting0128** [comment]
This problem has not reproduced, close it first.
