### ISSUE TITLE
[Bug]: Milvus is crashed with panic "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#12514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 7f9a414
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc9.dev22
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others: compaction enabled
```

### Current Behavior

Milvus is crashed with panic:
```
[2021/11/30 13:09:36.428 +00:00] [DEBUG] [task.go:634] ["releaseCollectionTask postExecute done"] [msgID=429462618407447130] [collectionID=429464644230053889] [nodeID=0]

panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x17631a2]



goroutine 2242 [running]:

github.com/milvus-io/milvus/internal/querycoord.(*releaseCollectionTask).execute(0xc0142d7140, 0x2928a60, 0xc009134270, 0x0, 0x0)

        /go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:587 +0x182

github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processTask(0xc00074d0e0, 0x294aa00, 0xc0142d7140, 0x0, 0x0)

        /go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:551 +0x6d4

github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).scheduleLoop(0xc00074d0e0)

        /go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:628 +0xf55

created by github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).Start

        /go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:856 +0x65
```

### Expected Behavior

No panic

### Steps To Reproduce

Nightly:

Logs: [artifacts-milvus-standalone-master-238-pymilvus-e2e-logs.tar.gz]
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/238/artifacts/

Log file including panic:
jenkins.var.log.containers.ms-7f9a-238-milvus-standalone-59fb4ff464-7c4nw_milvus-ci_standalone-2848c5064ada1a9dac5c714833e958a05a4e266cf15001ef58fc0f74e98005c9.log

**Comment by bigsheeper** [comment]
I'll fix it

**Comment by xige-16** [comment]
[query_node.go:234] ["query node init successfully"] [queryNodeID=0] [IP=10.202.32.85] [Port=21123]
If the nodeID registered by querynode is equal to 0, it will cause coord panic. I will reorganize the logic of this part.

**Comment by xige-16** [comment]
> 



> [query_node.go:234] ["query node init successfully"] [queryNodeID=0] [IP=10.202.32.85] [Port=21123] If the nodeID registered by querynode is equal to 0, it will cause coord panic. I will reorganize the logic of this part.

I made a mistake, the nodeID is not actually not 0.

**Comment by DragonDriver** [comment]
```shell
cat jenkins.var.log.containers.ms-7f9a-238-milvus-standalone-59fb4ff464-7c4nw_milvus-ci_standalone-2848c5064ada1a9dac5c714833e958a05a4e266cf15001ef58fc0f74e98005c9.log | grep "start do releaseCollectionTask" | grep "msgID=0" | wc -l
885
```

**Comment by DragonDriver** [comment]
Not sure why. I think it's `querypb.ReleaseCollectionRequest = nil` caused this issue. But after searched the all usage of `releaseCollectionTask`, I can't find any possibilities that `querypb.ReleaseCollectionRequest = nil`.

**Comment by DragonDriver** [comment]
There are some unreasonable places:
- 1, disconnected to etcd, qc exit, but the scheduler of qc don't exit normally;
- 2, the task id of rollback task is not assigned, which is not convinient to debug;

**Comment by xige-16** [comment]
query coord panic at "if res.ErrorCode != commonpb.ErrorCode_Success || err != nil {"
```
		res, err := rct.rootCoord.ReleaseDQLMessageStream(rct.ctx, releaseDQLMessageStreamReq)
		if res.ErrorCode != commonpb.ErrorCode_Success || err != nil {
			log.Warn("releaseCollectionTask: release collection end, releaseDQLMessageStream occur error", zap.Int64("collectionID", rct.CollectionID))
			err = errors.New("rootCoord releaseDQLMessageStream failed")
			rct.setResultInfo(err)
			return err
		}
```

**Comment by xige-16** [comment]
> query coord panic at "if res.ErrorCode != commonpb.ErrorCode_Success || err != nil {"
> 
> ```
> 		res, err := rct.rootCoord.ReleaseDQLMessageStream(rct.ctx, releaseDQLMessageStreamReq)
> 		if res.ErrorCode != commonpb.ErrorCode_Success || err != nil {
> 			log.Warn("releaseCollectionTask: release collection end, releaseDQLMessageStream occur error", zap.Int64("collectionID", rct.CollectionID))
> 			err = errors.New("rootCoord releaseDQLMessageStream failed")
> 			rct.setResultInfo(err)
> 			return err
> 		}
> ```

root coord client return (res=nil, error=err) if ReleaseDQLMessageStream failed, and when querycoord call res.ErrorCode, querycoord panic.
```
// ReleaseDQLMessageStream release DQL msgstream
func (c *Client) ReleaseDQLMessageStream(ctx context.Context, in *proxypb.ReleaseDQLMessageStreamRequest) (*commonpb.Status, error) {
	ret, err := c.grpcClient.ReCall(ctx, func(client interface{}) (interface{}, error) {
		if !funcutil.CheckCtxValid(ctx) {
			return nil, ctx.Err()
		}
		return client.(rootcoordpb.RootCoordClient).ReleaseDQLMessageStream(ctx, in)
	})
	if err != nil || ret == nil {
		return nil, err
	}
	return ret.(*commonpb.Status), err
}
```

**Comment by binbinlv** [comment]
Panic happens again in nightly:

Milvus Logs: [standalone]
https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/260/

Log with panic: [ the following name]
jenkins.var.log.containers.ms-260-milvus-standalone-65764dcdc8-pkx9b_milvus-ci_standalone-0121ad31db67cbce06dbefe981c3fcb7af47b4b3ff3faeae2af7c7322c27a377.log
```
[2021/12/09 17:23:12.089 +00:00] [WARN] [session_util.go:100] ["failed to initialize session"] [error="All attempts results:\nattempt #1:context deadline exceeded\nattempt #2:context deadline exceeded\nattempt #3:context deadline exceeded\nattempt #4:context deadline exceeded\nattempt #5:context deadline exceeded\nattempt #6:context deadline exceeded\nattempt #7:context deadline exceeded\nattempt #8:context deadline exceeded\nattempt #9:context deadline exceeded\nattempt #10:context deadline exceeded\nattempt #11:context deadline exceeded\nattempt #12:context deadline exceeded\nattempt #13:context deadline exceeded\nattempt #14:context deadline exceeded\nattempt #15:context deadline exceeded\nattempt #16:context deadline exceeded\nattempt #17:context deadline exceeded\nattempt #18:context deadline exceeded\nattempt #19:context deadline exceeded\nattempt #20:context deadline exceeded\nattempt #21:context deadline exceeded\nattempt #22:context deadline exceeded\nattempt #23:context deadline exceeded\nattempt #24:context deadline exceeded\nattempt #25:context deadline exceeded\nattempt #26:context deadline exceeded\nattempt #27:context deadline exceeded\nattempt #28:context canceled\nattempt #29:context canceled\n"]

[2021/12/09 17:23:12.089 +00:00] [DEBUG] [service.go:93] ["DataCoord Register etcd failed"] [error="failed to initialize session"]

panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x12acd6b]



goroutine 223 [running]:

github.com/milvus-io/milvus/internal/util/sessionutil.(*Session).Init(0x0, 0x2fa1e58, 0xa, 0xc0002f4e60, 0x12, 0x1)

        /go/src/github.com/milvus-io/milvus/internal/util/sessionutil/session_util.go:112 +0x2b

github.com/milvus-io/milvus/internal/querycoord.(*QueryCoord).Register(0xc00054f400, 0xa, 0x31bc8a0)

        /go/src/github.com/milvus-io/milvus/internal/querycoord/query_coord.go:100 +0x445

github.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).init(0xc0005d83c0, 0x8319de, 0xc000846008)

        /go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/service.go:111 +0xe4

github.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).Run(0xc0005d83c0, 0xc0005d8300, 0x0)

        /go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/service.go:88 +0x2f

github.com/milvus-io/milvus/cmd/components.(*QueryCoord).Run(0xc00014d440, 0xffffffffffffffff, 0x31efa80)

        /go/src/github.com/milvus-io/milvus/cmd/components/query_coord.go:50 +0x33

github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runQueryCoord.func1(0x127e001, 0x31ef100, 0xc000822d80, 0xc000010028, 0xc000846000)

        /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:178 +0xf0
```

**Comment by binbinlv** [comment]
Occurs again, so set as urgent.

**Comment by czs007** [comment]
#12983 has beed merged. @binbinlv please recheck this.

**Comment by ThreadDao** [comment]
This problem did not occur in the last five runs, so the priority is lowered to priority/backlog.

**Comment by binbinlv** [comment]
Check the nightly, the panic did not occur for several days, so close it.
