### ISSUE TITLE
[Bug]: [benchmark][cluster] Insert timeout : message send timeout: TimeoutError

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#12615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20211201-7370533
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus-2.0.0rc9.dev22
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

client pod:benchmark-cron-n5dz2-3917376036

client log:
```
[2021-12-01 16:16:07,335] [    INFO] - Prepare to run cases (milvus_benchmark.main:85)
[2021-12-01 16:16:07,353] [   DEBUG] - Milvus exists_collection run in 0.02s (milvus_benchmark.client:52)
[2021-12-01 16:16:07,970] [    INFO] - Create collection: <glove_200_angular> successfully (milvus_benchmark.client:148)
[2021-12-01 16:16:07,971] [   DEBUG] - Milvus create_collection run in 0.61s (milvus_benchmark.client:52)
[2021-12-01 16:16:27,455] [    INFO] - Set normalize for metric_type: ip (milvus_benchmark.runners.utils:254)
[2021-12-01 16:16:37,693] [   DEBUG] - The row count of entities to be inserted: 1183514 (milvus_benchmark.runners.accuracy:226)
[2021-12-01 16:16:37,709] [   DEBUG] - Milvus get_info run in 0.01s (milvus_benchmark.client:52)
[2021-12-01 16:16:49,585] [   DEBUG] - Milvus insert run in 10.98s (milvus_benchmark.client:52)
[2021-12-01 16:16:56,542] [   DEBUG] - Milvus insert run in 6.03s (milvus_benchmark.client:52)
[2021-12-01 16:17:04,212] [   DEBUG] - Milvus insert run in 6.06s (milvus_benchmark.client:52)
[2021-12-01 16:17:12,227] [   DEBUG] - Milvus insert run in 7.13s (milvus_benchmark.client:52)
[2021-12-01 16:17:18,412] [   DEBUG] - Milvus insert run in 4.53s (milvus_benchmark.client:52)
[2021-12-01 16:17:24,120] [   DEBUG] - Milvus insert run in 4.72s (milvus_benchmark.client:52)
[2021-12-01 16:17:29,327] [   DEBUG] - Milvus insert run in 3.79s (milvus_benchmark.client:52)
[2021-12-01 16:17:34,841] [   DEBUG] - Milvus insert run in 4.59s (milvus_benchmark.client:52)
[2021-12-01 16:17:42,990] [   DEBUG] - Milvus insert run in 6.94s (milvus_benchmark.client:52)
[2021-12-01 16:17:48,534] [   DEBUG] - Milvus insert run in 4.66s (milvus_benchmark.client:52)
[2021-12-01 16:17:54,245] [   DEBUG] - Milvus insert run in 4.54s (milvus_benchmark.client:52)
[2021-12-01 16:18:00,260] [   DEBUG] - Milvus insert run in 5.22s (milvus_benchmark.client:52)
[2021-12-01 16:18:06,855] [   DEBUG] - Milvus insert run in 5.4s (milvus_benchmark.client:52)
[2021-12-01 16:18:13,871] [   DEBUG] - Milvus insert run in 5.77s (milvus_benchmark.client:52)
[2021-12-01 16:18:29,003] [   DEBUG] - Milvus insert run in 14.3s (milvus_benchmark.client:52)
[2021-12-01 16:18:35,948] [   DEBUG] - Milvus insert run in 5.75s (milvus_benchmark.client:52)
[2021-12-01 16:18:43,737] [   DEBUG] - Milvus insert run in 7.0s (milvus_benchmark.client:52)
[2021-12-01 16:18:53,948] [   DEBUG] - Milvus insert run in 9.09s (milvus_benchmark.client:52)
[2021-12-01 16:19:32,157] [   ERROR] - Error: <BaseException: (code=1, message=message send timeout: TimeoutError)> (pymilvus.client.grpc_handler:69)
[2021-12-01 16:19:32,159] [   ERROR] - <BaseException: (code=1, message=message send timeout: TimeoutError)> (milvus_benchmark.client:165)
[2021-12-01 16:19:32,171] [   DEBUG] - Milvus insert run in 37.42s (milvus_benchmark.client:52)
[2021-12-01 16:19:32,172] [   ERROR] -  (milvus_benchmark.main:117)
[2021-12-01 16:19:32,174] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 86, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/accuracy.py", line 243, in prepare
    assert res_ids == ids
AssertionError
 (milvus_benchmark.main:118)
[2021-12-01 16:19:32,586] [   DEBUG] - {'_version': '0.1', '_type': 'metric', 'run_id': 1638375349, 'mode': 'local', 'server': <milvus_benchmark.metrics.models.server.Server object at 0x7f87a3fa3eb8>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware object at 0x7f87a3fa3ef0>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7f87a3fa3cf8>, 'status': 'RUN_FAILED', 'err_message': '', 'collection': {'dimension': 200, 'metric_type': 'ip', 'dataset_name': 'glove_200_angular', 'shards_num': None}, 'index': {}, 'search': None, 'run_params': None, 'metrics': {'type': 'ann_accuracy', 'value': {}}, 'datetime': '2021-12-01 16:15:49.990097', 'type': 'metric'} (milvus_benchmark.metric.api:29)
```

### Expected Behavior

argo task: benchmark-cron-n5dz2

test yaml:
client-configmap: client-acc-glove-ivf-flat,instanceId:5,server-configmap:server-cluster-8c16m

server:
```
NAME                                                              READY   STATUS             RESTARTS   AGE     IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-cron-n5dz2-5-etcd-0                                     1/1     Running            0          6h2m    10.97.17.43    qa-node014.zilliz.local   <none>           <none>
benchmark-cron-n5dz2-5-etcd-1                                     1/1     Running            0          6h2m    10.97.17.42    qa-node014.zilliz.local   <none>           <none>
benchmark-cron-n5dz2-5-etcd-2                                     1/1     Running            0          6h2m    10.97.17.45    qa-node014.zilliz.local   <none>           <none>
benchmark-cron-n5dz2-5-milvus-datacoord-d7467c74b-qnx9t           1/1     Running            3          6h2m    10.97.4.135    qa-node002.zilliz.local   <none>           <none>
benchmark-cron-n5dz2-5-milvus-datanode-76776bf95c-rr9xp           1/1     Running            0          6h2m    10.97.14.119   qa-node011.zilliz.local   <none>           <none>
benchmark-cron-n5dz2-5-milvus-indexcoord-b4d57976f-t74vq          1/1     Running            1          6h2m    10.97.4.137    qa-node002.zilliz.local   <none>           <none>
benchmark-cron-n5dz2-5-milvus-indexnode-f9cdf85db-ntb84           1/1     Running            0          6h2m    10.97.14.118   qa-node011.zilliz.local   <none>           <none>
benchmark-cron-n5dz2-5-milvus-proxy-df8884df4-mg4hx               1/1     Running            2          6h2m    10.97.4.136    qa-node002.zilliz.local   <none>           <none>
benchmark-cron-n5dz2-5-milvus-querycoord-7f5b5f86db-tdcxr         1/1     Running            2          6h2m    10.97.4.133    qa-node002.zilliz.local   <none>           <none>
benchmark-cron-n5dz2-5-milvus-querynode-67769486cb-whk8x          1/1     Running            0          6h2m    10.97.17.31    qa-node014.zilliz.local   <none>           <none>
benchmark-cron-n5dz2-5-milvus-rootcoord-648d865bb6-gfhw4          1/1     Running            0          6h2m    10.97.4.134    qa-node002.zilliz.local   <none>           <none>
benchmark-cron-n5dz2-5-minio-0                                    1/1     Running            0          6h2m    10.97.11.55    qa-node009.zilliz.local   <none>           <none>
benchmark-cron-n5dz2-5-minio-1                                    1/1     Running            0          6h2m    10.97.11.54    qa-node009.zilliz.local   <none>           <none>
benchmark-cron-n5dz2-5-minio-2                                    1/1     Running            0          6h2m    10.97.11.56    qa-node009.zilliz.local   <none>           <none>
benchmark-cron-n5dz2-5-minio-3                                    1/1     Running            0          6h2m    10.97.8.70     qa-node006.zilliz.local   <none>           <none>
benchmark-cron-n5dz2-5-pulsar-autorecovery-85866d55f6-wrw8c       1/1     Running            0          6h2m    10.97.11.51    qa-node009.zilliz.local   <none>           <none>
benchmark-cron-n5dz2-5-pulsar-bastion-7f4cc8ff86-bqpc6            1/1     Running            0          6h2m    10.97.11.53    qa-node009.zilliz.local   <none>           <none>
benchmark-cron-n5dz2-5-pulsar-bookkeeper-0                        1/1     Running            0          6h2m    10.97.3.247    qa-node001.zilliz.local   <none>           <none>
benchmark-cron-n5dz2-5-pulsar-bookkeeper-1                        1/1     Running            0          6h1m    10.97.13.82    qa-node010.zilliz.local   <none>           <none>
benchmark-cron-n5dz2-5-pulsar-bookkeeper-2                        1/1     Running            0          6h      10.97.15.230   qa-node012.zilliz.local   <none>           <none>
benchmark-cron-n5dz2-5-pulsar-broker-65f4b59759-sv4nh             1/1     Running            9          6h2m    10.97.15.228   qa-node012.zilliz.local   <none>           <none>
benchmark-cron-n5dz2-5-pulsar-proxy-755dcd5455-lkxsv              2/2     Running            0          6h2m    10.97.10.223   qa-node008.zilliz.local   <none>           <none>
benchmark-cron-n5dz2-5-pulsar-zookeeper-0                         1/1     Running            0          6h2m    10.97.3.246    qa-node001.zilliz.local   <none>           <none>
benchmark-cron-n5dz2-5-pulsar-zookeeper-1                         1/1     Running            0          6h2m    10.97.13.80    qa-node010.zilliz.local   <none>           <none>
benchmark-cron-n5dz2-5-pulsar-zookeeper-2                         1/1     Running            0          6h1m    10.97.14.120   qa-node011.zilliz.local   <none>           <none>
benchmark-cron-n5dz2-5-pulsar-zookeeper-metadata-dss9c            0/1     Completed          0          6h2m    10.97.4.132    qa-node002.zilliz.local   <none>           <none>

```

### Steps To Reproduce

```markdown
1、create collection
2、insert data <- raise error of timeout
```

### Anything else?

client-acc-glove-ivf-flat:
```
ann_accuracy:
      collections:
        -
          source_file: /test/milvus/ann_hdf5/glove-200-angular.hdf5
          collection_name: glove_200_angular
          index_types: ['ivf_flat']
          index_params:
            nlist: [1024]
          top_ks: [10]
          nqs: [10000]
          search_params:
            nprobe: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512]
```

**Comment by yanliang567** [comment]
one more thing I think we need to look into:
```
[2021-12-01 16:16:49,585] [   DEBUG] - Milvus insert run in 10.98s (milvus_benchmark.client:52)
[2021-12-01 16:18:29,003] [   DEBUG] - Milvus insert run in 14.3s (milvus_benchmark.client:52)
```
insert cost more seconds, comparing with before(around 2 seconds)

**Comment by congqixia** [comment]
Found datacoord exited for disconnecting fomr etcd
```
[2021/12/01 16:33:40.465 +00:00] [ERROR] [server.go:409] ["Data Coord disconnected from etcd, process will exit"] ["Server Id"=4] [stack="github.com/milvus-io/milvus/internal/datacoord.(*Server).startServerLoop.func1\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/server.go:409"]
```
Will check other coords

**Comment by congqixia** [comment]
@wangting0128 check all log of restarted pods
```
datacoord.log
623:[2021/12/01 16:33:40.465 +00:00] [ERROR] [server.go:409] ["Data Coord disconnected from etcd, process will exit"] ["Server Id"=4] [stack="github.com/milvus-io/milvus/internal/datacoord.(*Server).startServerLoop.func1\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/server.go:409"]

proxy.log
1227:[2021/12/01 16:33:40.496 +00:00] [ERROR] [proxy.go:117] ["Proxy disconnected from etcd, process will exit"] ["Server Id"=5] [stack="github.com/milvus-io/milvus/internal/proxy.(*Proxy).Register.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/proxy.go:117"]

querycoord.log
343:[2021/12/01 16:33:40.110 +00:00] [ERROR] [query_coord.go:209] ["Query Coord disconnected from etcd, process will exit"] ["Server Id"=2] [stack="github.com/milvus-io/milvus/internal/querycoord.(*QueryCoord).Start.func1\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/query_coord.go:209"]

indexcoord
1070:[2021/12/01 16:33:40.140 +00:00] [ERROR] [index_coord.go:250] ["Index Coord disconnected from etcd, process will exit"] ["Server Id"=6] [stack="github.com/milvus-io/milvus/internal/indexcoord.(*IndexCoord).Start.func1.1\n\t/go/src/github.com/milvus-io/milvus/internal/indexcoord/index_coord.go:250"]
```
The disconnected from etcd at same moment. Afterward restarts are caused by failure to connect etcd at start procedure.

**Comment by yanliang567** [comment]
seems like a test env noisy issue, remove from urgent first
