### ISSUE TITLE
[Bug]: [benchmark][cluster] 1 billion dataset, loading error: 503 Service Unavailable

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#12629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20211201-7370533
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-2.0.0rc9.dev22
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

client pod:benchmark-no-clean-wzt6t-758071449

client logs:
```
[2021-12-02 07:34:05,192] [    INFO] - {'total_time': 34338.3, 'rps': 29122.0, 'ni_time': 1.72} (milvus_benchmark.runners.base:151)
[2021-12-02 07:34:05,271] [   DEBUG] - Start flush. (milvus_benchmark.runners.locust:428)
[2021-12-02 07:34:15,839] [   DEBUG] - Milvus flush run in 10.57s (milvus_benchmark.client:52)
[2021-12-02 07:34:15,842] [   DEBUG] - Fulsh done, during time: 10.57 (milvus_benchmark.runners.locust:431)
[2021-12-02 07:34:15,851] [   DEBUG] - Row count: 1000000000 in collection: <sift_1b_128_l2> (milvus_benchmark.client:420)
[2021-12-02 07:34:15,851] [   DEBUG] - 1000000000 (milvus_benchmark.runners.locust:432)
[2021-12-02 07:34:15,852] [   DEBUG] - Start build index for last file (milvus_benchmark.runners.locust:434)
[2021-12-02 07:34:15,852] [    INFO] - Building index start, collection_name: sift_1b_128_l2, index_type: IVF_SQ8, metric_type: L2 (milvus_benchmark.client:273)
[2021-12-02 07:34:15,852] [    INFO] - {'nlist': 1024} (milvus_benchmark.client:275)
[2021-12-02 07:34:15,852] [   DEBUG] - collection: sift_1b_128_l2 Index params: {'index_type': 'IVF_SQ8', 'metric_type': 'L2', 'params': {'nlist': 1024}} (milvus_benchmark.client:281)
[2021-12-02 07:34:41,732] [   DEBUG] - Building index done, collection_name: sift_1b_128_l2, response: Status(code=0, message='') (milvus_benchmark.client:283)
[2021-12-02 07:34:41,760] [   DEBUG] - Milvus create_index run in 25.91s (milvus_benchmark.client:52)
[2021-12-02 07:34:41,760] [   DEBUG] - {'flush_time': 10.57, 'build_time': 25.91} (milvus_benchmark.runners.locust:438)
[2021-12-02 07:34:41,763] [   DEBUG] - Row count: 1000000000 in collection: <sift_1b_128_l2> (milvus_benchmark.client:420)
[2021-12-02 07:34:41,763] [    INFO] - 1000000000 (milvus_benchmark.runners.locust:439)
[2021-12-02 07:34:41,763] [    INFO] - Start load collection (milvus_benchmark.runners.locust:440)
[2021-12-02 07:55:49,577] [   ERROR] - Error: <BaseException: (code=1, message=, 503 Service Unavailable)> (pymilvus.client.grpc_handler:69)
[2021-12-02 07:55:49,578] [   ERROR] - <BaseException: (code=1, message=, 503 Service Unavailable)> (milvus_benchmark.main:117)
[2021-12-02 07:55:49,584] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 86, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/locust.py", line 442, in prepare
    self.milvus.load_collection()
  File "/src/milvus_benchmark/client.py", line 48, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 482, in load_collection
    return self._milvus.load_collection(collection_name, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 58, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 42, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 322, in load_collection
    return handler.load_collection("", collection_name=collection_name, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 835, in load_collection
    raise BaseException(response.error_code, response.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=, 503 Service Unavailable)>
 (milvus_benchmark.main:118)
[2021-12-02 07:55:49,610] [   DEBUG] - {'_version': '0.1', '_type': 'metric', 'run_id': 1638375011, 'mode': 'local', 'server': <milvus_benchmark.metrics.models.server.Server object at 0x7fb847719198>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware object at 0x7fb847719048>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7fb847719390>, 'status': 'RUN_FAILED', 'err_message': '', 'collection': {'dimension': 128, 'metric_type': 'l2', 'dataset_name': 'sift_1b_128_l2', 'collection_size': 1000000000, 'other_fields': None, 'ni_per': 50000, 'shards_num': None}, 'index': {'index_type': 'ivf_sq8', 'index_param': {'nlist': 1024}}, 'search': None, 'run_params': {'task': {'types': [{'type': 'query', 'weight': 20, 'params': {'top_k': 10, 'nq': 10, 'search_param': {'nprobe': 16}}}, {'type': 'load', 'weight': 1}, {'type': 'get', 'weight': 2, 'params': {'ids_length': 10}}], 'connection_num': 1, 'clients_num': 20, 'spawn_rate': 2, 'during_time': 864000}, 'connection_type': 'single'}, 'metrics': {'type': 'locust_random_performance', 'value': {}}, 'datetime': '2021-12-01 16:10:11.427005', 'type': 'metric'} (milvus_benchmark.metric.api:29)
```

### Expected Behavior

argo task: benchmark-no-clean-wzt6t

test yaml:
client-configmap: client-random-locust-search-84h-1b
server-configmap: server-cluster-8c64m-datanode2-indexnode4-querynode6-nocompaction

**service sets compaction to true**

server:
```
NAME                                                              READY   STATUS      RESTARTS   AGE    IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-no-clean-8bdck-1-etcd-0                                 1/1     Running     0          36m    10.97.17.194   qa-node014.zilliz.local   <none>           <none>
benchmark-no-clean-8bdck-1-milvus-standalone-75b488d645-66zkq     1/1     Running     0          36m    10.97.17.191   qa-node014.zilliz.local   <none>           <none>
benchmark-no-clean-8bdck-1-minio-6c6b88776d-s9z78                 1/1     Running     0          36m    10.97.17.195   qa-node014.zilliz.local   <none>           <none>
benchmark-no-clean-wzt6t-1-etcd-0                                 1/1     Running     0          17h    10.97.17.248   qa-node014.zilliz.local   <none>           <none>
benchmark-no-clean-wzt6t-1-etcd-1                                 1/1     Running     0          17h    10.97.17.249   qa-node014.zilliz.local   <none>           <none>
benchmark-no-clean-wzt6t-1-etcd-2                                 1/1     Running     0          17h    10.97.17.250   qa-node014.zilliz.local   <none>           <none>
benchmark-no-clean-wzt6t-1-milvus-datacoord-55dbb697-nh4jc        1/1     Running     0          17h    10.97.12.248   qa-node015.zilliz.local   <none>           <none>
benchmark-no-clean-wzt6t-1-milvus-datanode-fd4865f4d-8dm5v        1/1     Running     0          17h    10.97.19.245   qa-node016.zilliz.local   <none>           <none>
benchmark-no-clean-wzt6t-1-milvus-datanode-fd4865f4d-lbhnk        1/1     Running     0          17h    10.97.10.217   qa-node008.zilliz.local   <none>           <none>
benchmark-no-clean-wzt6t-1-milvus-indexcoord-79f4569bc4-rv959     1/1     Running     0          17h    10.97.19.242   qa-node016.zilliz.local   <none>           <none>
benchmark-no-clean-wzt6t-1-milvus-indexnode-5985d9cf5-bflkz       1/1     Running     0          17h    10.97.15.223   qa-node012.zilliz.local   <none>           <none>
benchmark-no-clean-wzt6t-1-milvus-indexnode-5985d9cf5-gxfxk       1/1     Running     0          17h    10.97.12.250   qa-node015.zilliz.local   <none>           <none>
benchmark-no-clean-wzt6t-1-milvus-indexnode-5985d9cf5-lnf7l       1/1     Running     0          17h    10.97.11.41    qa-node009.zilliz.local   <none>           <none>
benchmark-no-clean-wzt6t-1-milvus-indexnode-5985d9cf5-wvp7x       1/1     Running     0          17h    10.97.16.78    qa-node013.zilliz.local   <none>           <none>
benchmark-no-clean-wzt6t-1-milvus-proxy-7b6f98fbc9-rm25f          1/1     Running     0          17h    10.97.19.241   qa-node016.zilliz.local   <none>           <none>
benchmark-no-clean-wzt6t-1-milvus-querycoord-7b768466f-v5nnt      1/1     Running     0          17h    10.97.12.251   qa-node015.zilliz.local   <none>           <none>
benchmark-no-clean-wzt6t-1-milvus-querynode-55c8dfbf-4ps5b        1/1     Running     0          17h    10.97.12.249   qa-node015.zilliz.local   <none>           <none>
benchmark-no-clean-wzt6t-1-milvus-querynode-55c8dfbf-79n28        1/1     Running     1          17h    10.97.16.79    qa-node013.zilliz.local   <none>           <none>
benchmark-no-clean-wzt6t-1-milvus-querynode-55c8dfbf-95rvh        1/1     Running     1          17h    10.97.16.80    qa-node013.zilliz.local   <none>           <none>
benchmark-no-clean-wzt6t-1-milvus-querynode-55c8dfbf-9gxvw        1/1     Running     0          17h    10.97.19.244   qa-node016.zilliz.local   <none>           <none>
benchmark-no-clean-wzt6t-1-milvus-querynode-55c8dfbf-h6hmg        1/1     Running     1          17h    10.97.16.77    qa-node013.zilliz.local   <none>           <none>
benchmark-no-clean-wzt6t-1-milvus-querynode-55c8dfbf-qb58k        1/1     Running     0          17h    10.97.19.238   qa-node016.zilliz.local   <none>           <none>
benchmark-no-clean-wzt6t-1-milvus-rootcoord-76d54c5cbf-qgmhp      1/1     Running     0          17h    10.97.6.158    qa-node004.zilliz.local   <none>           <none>
benchmark-no-clean-wzt6t-1-minio-0                                1/1     Running     0          17h    10.97.9.161    qa-node007.zilliz.local   <none>           <none>
benchmark-no-clean-wzt6t-1-minio-1                                1/1     Running     0          17h    10.97.9.160    qa-node007.zilliz.local   <none>           <none>
benchmark-no-clean-wzt6t-1-minio-2                                1/1     Running     0          17h    10.97.9.158    qa-node007.zilliz.local   <none>           <none>
benchmark-no-clean-wzt6t-1-minio-3                                1/1     Running     0          17h    10.97.9.159    qa-node007.zilliz.local   <none>           <none>
benchmark-no-clean-wzt6t-1-pulsar-autorecovery-6984b6ddd4-frfrr   1/1     Running     0          17h    10.97.15.221   qa-node012.zilliz.local   <none>           <none>
benchmark-no-clean-wzt6t-1-pulsar-bastion-d8cbc5556-4pkgh         1/1     Running     0          17h    10.97.15.222   qa-node012.zilliz.local   <none>           <none>
benchmark-no-clean-wzt6t-1-pulsar-bookkeeper-0                    1/1     Running     0          17h    10.97.9.157    qa-node007.zilliz.local   <none>           <none>
benchmark-no-clean-wzt6t-1-pulsar-bookkeeper-1                    1/1     Running     0          17h    10.97.17.251   qa-node014.zilliz.local   <none>           <none>
benchmark-no-clean-wzt6t-1-pulsar-bookkeeper-2                    1/1     Running     0          17h    10.97.6.160    qa-node004.zilliz.local   <none>           <none>
benchmark-no-clean-wzt6t-1-pulsar-broker-766cbb94bb-wh9s4         1/1     Running     0          17h    10.97.10.216   qa-node008.zilliz.local   <none>           <none>
benchmark-no-clean-wzt6t-1-pulsar-proxy-7968d8f4c4-l8c9j          2/2     Running     0          17h    10.97.7.234    qa-node005.zilliz.local   <none>           <none>
benchmark-no-clean-wzt6t-1-pulsar-zookeeper-0                     1/1     Running     0          17h    10.97.6.159    qa-node004.zilliz.local   <none>           <none>
benchmark-no-clean-wzt6t-1-pulsar-zookeeper-1                     1/1     Running     0          17h    10.97.9.162    qa-node007.zilliz.local   <none>           <none>
benchmark-no-clean-wzt6t-1-pulsar-zookeeper-2                     1/1     Running     0          17h    10.97.9.163    qa-node007.zilliz.local   <none>           <none>
benchmark-no-clean-wzt6t-1-pulsar-zookeeper-metadata-zqrws        0/1     Completed   0          17h    10.97.10.215   qa-node008.zilliz.local   <none>           <none>

```

**Comment by xige-16** [comment]
Querycoord encountered this error when getting  the binlog header from minio
```
[2021/12/02 07:55:49.286 +00:00] [DEBUG] [segment_allocator.go:117] ["shuffleSegmentsToQueryNodeV2: estimate segment size error"] [error="503 Service Unavailable"]
```

**Comment by LoveEachDay** [comment]
Minio server misbehaved.  We can test with `local-path` storageclass for now.
