### ISSUE TITLE
[Bug]: [benchmark][standalone] search raise error: query coordinator is not healthy

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#12719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20211203-d1aeed2
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-2.0.0rc9.dev22
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

client pod: benchmark-tag-blqqf-1248263126

[client.log](https://github.com/milvus-io/milvus/files/7648767/client.log)

client log:
```
[2021-12-03 09:42:30,244] [   DEBUG] - Start run query, run 10 of 30 (milvus_benchmark.runners.search:283)
[2021-12-03 09:42:30,244] [    INFO] - {'nq': 1200, 'topk': 1, 'search_param': {'nprobe': 32}, 'filter': [], 'guarantee_timestamp': None} (milvus_benchmark.runners.search:284)
[2021-12-03 09:42:48,892] [   DEBUG] - Milvus query run in 18.65s (milvus_benchmark.client:52)
[2021-12-03 09:42:48,894] [   DEBUG] - Start run query, run 11 of 30 (milvus_benchmark.runners.search:283)
[2021-12-03 09:42:48,895] [    INFO] - {'nq': 1200, 'topk': 1, 'search_param': {'nprobe': 32}, 'filter': [], 'guarantee_timestamp': None} (milvus_benchmark.runners.search:284)
[2021-12-03 09:42:48,993] [   ERROR] - Error: <BaseException: (code=1, message=query coordinator is not healthy)> (pymilvus.client.grpc_handler:69)
[2021-12-03 09:42:48,994] [   ERROR] - Error: <BaseException: (code=1, message=query coordinator is not healthy)> (pymilvus.client.grpc_handler:69)
[2021-12-03 09:42:48,997] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 94, in run_suite
    result = runner.run_case(case_metric, **case)
  File "/src/milvus_benchmark/runners/search.py", line 287, in run_case
    guarantee_timestamp=case_param["guarantee_timestamp"])
  File "/src/milvus_benchmark/client.py", line 48, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 321, in query
    result = self._milvus.search(tmp_collection_name, **params)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 58, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 42, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 1048, in search
    partition_names, output_fields, timeout, round_decimal, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 104, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 643, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 605, in _execute_search_requests
    raise pre_err
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 596, in _execute_search_requests
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=query coordinator is not healthy)>
 (milvus_benchmark.main:97)
[2021-12-03 09:42:48,998] [    INFO] - None (milvus_benchmark.main:98)
[2021-12-03 09:42:48,999] [   DEBUG] - {'type': 'insert_search_performance', 'value': {}} (milvus_benchmark.main:106)
[2021-12-03 09:42:49,000] [   DEBUG] - {'_version': '0.1', '_type': 'case', 'run_id': 1638514633, 'mode': 'local', 'server': <milvus_benchmark.metrics.models.server.Server object at 0x7fc43c35ae10>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware object at 0x7fc43c35ad30>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7fc43c35abe0>, 'status': 'RUN_FAILED', 'err_message': '<BaseException: (code=1, message=query coordinator is not healthy)>\nTraceback (most recent call last):\n  File "main.py", line 94, in run_suite\n    result = runner.run_case(case_metric, **case)\n  File "/src/milvus_benchmark/runners/search.py", line 287, in run_case\n    guarantee_timestamp=case_param["guarantee_timestamp"])\n  File "/src/milvus_benchmark/client.py", line 48, in wrapper\n    result = func(*args, **kwargs)\n  File "/src/milvus_benchmark/client.py", line 321, in query\n    result = self._milvus.search(tmp_collection_name, **params)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 58, in handler\n    raise e\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 42, in handler\n    return func(self, *args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 1048, in search\n    partition_names, output_fields, timeout, round_decimal, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler\n    raise e\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler\n    return func(self, *args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 104, in handler\n    return func(self, *args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 643, in search\n    return self._execute_search_requests(requests, timeout, **_kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler\n    raise e\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler\n    return func(self, *args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 605, in _execute_search_requests\n    raise pre_err\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 596, in _execute_search_requests\n    raise BaseException(response.status.error_code, response.status.reason)\npymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=query coordinator is not healthy)>\n', 'collection': {'dimension': 128, 'metric_type': 'l2', 'dataset_name': 'sift_50m_128_l2', 'fields': None, 'shards_num': None}, 'index': {'index_type': 'ivf_flat', 'index_param': {'nlist': 1024}}, 'search': {'nq': 1200, 'topk': 1, 'search_param': {'nprobe': 32}, 'filter': [], 'guarantee_timestamp': None}, 'run_params': None, 'metrics': {'type': 'insert_search_performance', 'value': {}}, 'datetime': '2021-12-03 06:57:13.094509', 'type': 'metric'} (milvus_benchmark.metric.api:29)
[2021-12-03 09:42:49,009] [   DEBUG] - Start run query, run 1 of 30 (milvus_benchmark.runners.search:283)
[2021-12-03 09:42:49,010] [    INFO] - {'nq': 1200, 'topk': 10, 'search_param': {'nprobe': 32}, 'filter': [], 'guarantee_timestamp': None} (milvus_benchmark.runners.search:284)
[2021-12-03 09:42:49,108] [   ERROR] - Error: <BaseException: (code=1, message=query coordinator is not healthy)> (pymilvus.client.grpc_handler:69)
[2021-12-03 09:42:49,109] [   ERROR] - Error: <BaseException: (code=1, message=query coordinator is not healthy)> (pymilvus.client.grpc_handler:69)
[2021-12-03 09:42:49,110] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 94, in run_suite
    result = runner.run_case(case_metric, **case)
  File "/src/milvus_benchmark/runners/search.py", line 287, in run_case
    guarantee_timestamp=case_param["guarantee_timestamp"])
  File "/src/milvus_benchmark/client.py", line 48, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 321, in query
    result = self._milvus.search(tmp_collection_name, **params)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 58, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 42, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 1048, in search
    partition_names, output_fields, timeout, round_decimal, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 104, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 643, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 605, in _execute_search_requests
    raise pre_err
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 596, in _execute_search_requests
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=query coordinator is not healthy)>
 (milvus_benchmark.main:97)
[2021-12-03 09:42:49,110] [    INFO] - None (milvus_benchmark.main:98)
[2021-12-03 09:42:49,111] [   DEBUG] - {'type': 'insert_search_performance', 'value': {}} (milvus_benchmark.main:106)
[2021-12-03 09:42:49,112] [   DEBUG] - {'_version': '0.1', '_type': 'case', 'run_id': 1638514633, 'mode': 'local', 'server': <milvus_benchmark.metrics.models.server.Server object at 0x7fc43c35a828>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware object at 0x7fc43c35a780>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7fc43c35a6a0>, 'status': 'RUN_FAILED', 'err_message': '<BaseException: (code=1, message=query coordinator is not healthy)>\nTraceback (most recent call last):\n  File "main.py", line 94, in run_suite\n    result = runner.run_case(case_metric, **case)\n  File "/src/milvus_benchmark/runners/search.py", line 287, in run_case\n    guarantee_timestamp=case_param["guarantee_timestamp"])\n  File "/src/milvus_benchmark/client.py", line 48, in wrapper\n    result = func(*args, **kwargs)\n  File "/src/milvus_benchmark/client.py", line 321, in query\n    result = self._milvus.search(tmp_collection_name, **params)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 58, in handler\n    raise e\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 42, in handler\n    return func(self, *args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 1048, in search\n    partition_names, output_fields, timeout, round_decimal, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler\n    raise e\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler\n    return func(self, *args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 104, in handler\n    return func(self, *args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 643, in search\n    return self._execute_search_requests(requests, timeout, **_kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler\n    raise e\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler\n    return func(self, *args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 605, in _execute_search_requests\n    raise pre_err\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 596, in _execute_search_requests\n    raise BaseException(response.status.error_code, response.status.reason)\npymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=query coordinator is not healthy)>\n', 'collection': {'dimension': 128, 'metric_type': 'l2', 'dataset_name': 'sift_50m_128_l2', 'fields': None, 'shards_num': None}, 'index': {'index_type': 'ivf_flat', 'index_param': {'nlist': 1024}}, 'search': {'nq': 1200, 'topk': 10, 'search_param': {'nprobe': 32}, 'filter': [], 'guarantee_timestamp': None}, 'run_params': None, 'metrics': {'type': 'insert_search_performance', 'value': {}}, 'datetime': '2021-12-03 06:57:13.094509', 'type': 'metric'} (milvus_benchmark.metric.api:29)
[2021-12-03 09:42:49,121] [   DEBUG] - Start run query, run 1 of 30 (milvus_benchmark.runners.search:283)
[2021-12-03 09:42:49,122] [    INFO] - {'nq': 1200, 'topk': 100, 'search_param': {'nprobe': 32}, 'filter': [], 'guarantee_timestamp': None} (milvus_benchmark.runners.search:284)
[2021-12-03 09:42:49,235] [   ERROR] - Error: <BaseException: (code=1, message=query coordinator is not healthy)> (pymilvus.client.grpc_handler:69)
[2021-12-03 09:42:49,236] [   ERROR] - Error: <BaseException: (code=1, message=query coordinator is not healthy)> (pymilvus.client.grpc_handler:69)
[2021-12-03 09:42:49,237] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 94, in run_suite
    result = runner.run_case(case_metric, **case)
  File "/src/milvus_benchmark/runners/search.py", line 287, in run_case
    guarantee_timestamp=case_param["guarantee_timestamp"])
  File "/src/milvus_benchmark/client.py", line 48, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 321, in query
    result = self._milvus.search(tmp_collection_name, **params)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 58, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 42, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 1048, in search
    partition_names, output_fields, timeout, round_decimal, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 104, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 643, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 605, in _execute_search_requests
    raise pre_err
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 596, in _execute_search_requests
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=query coordinator is not healthy)>
 (milvus_benchmark.main:97)
[2021-12-03 09:42:49,239] [    INFO] - None (milvus_benchmark.main:98)
[2021-12-03 09:42:49,239] [   DEBUG] - {'type': 'insert_search_performance', 'value': {}} (milvus_benchmark.main:106)
[2021-12-03 09:42:49,240] [   DEBUG] - {'_version': '0.1', '_type': 'case', 'run_id': 1638514633, 'mode': 'local', 'server': <milvus_benchmark.metrics.models.server.Server object at 0x7fc43c35a4e0>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware object at 0x7fc43c35a400>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7fc43c35a320>, 'status': 'RUN_FAILED', 'err_message': '<BaseException: (code=1, message=query coordinator is not healthy)>\nTraceback (most recent call last):\n  File "main.py", line 94, in run_suite\n    result = runner.run_case(case_metric, **case)\n  File "/src/milvus_benchmark/runners/search.py", line 287, in run_case\n    guarantee_timestamp=case_param["guarantee_timestamp"])\n  File "/src/milvus_benchmark/client.py", line 48, in wrapper\n    result = func(*args, **kwargs)\n  File "/src/milvus_benchmark/client.py", line 321, in query\n    result = self._milvus.search(tmp_collection_name, **params)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 58, in handler\n    raise e\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 42, in handler\n    return func(self, *args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 1048, in search\n    partition_names, output_fields, timeout, round_decimal, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler\n    raise e\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler\n    return func(self, *args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 104, in handler\n    return func(self, *args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 643, in search\n    return self._execute_search_requests(requests, timeout, **_kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler\n    raise e\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler\n    return func(self, *args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 605, in _execute_search_requests\n    raise pre_err\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 596, in _execute_search_requests\n    raise BaseException(response.status.error_code, response.status.reason)\npymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=query coordinator is not healthy)>\n', 'collection': {'dimension': 128, 'metric_type': 'l2', 'dataset_name': 'sift_50m_128_l2', 'fields': None, 'shards_num': None}, 'index': {'index_type': 'ivf_flat', 'index_param': {'nlist': 1024}}, 'search': {'nq': 1200, 'topk': 100, 'search_param': {'nprobe': 32}, 'filter': [], 'guarantee_timestamp': None}, 'run_params': None, 'metrics': {'type': 'insert_search_performance', 'value': {}}, 'datetime': '2021-12-03 06:57:13.094509', 'type': 'metric'} (milvus_benchmark.metric.api:29)
[2021-12-03 09:42:49,252] [   DEBUG] - Start run query, run 1 of 30 (milvus_benchmark.runners.search:283)
[2021-12-03 09:42:49,252] [    INFO] - {'nq': 1200, 'topk': 1000, 'search_param': {'nprobe': 32}, 'filter': [], 'guarantee_timestamp': None} (milvus_benchmark.runners.search:284)
[2021-12-03 09:42:49,377] [   ERROR] - Error: <BaseException: (code=1, message=query coordinator is not healthy)> (pymilvus.client.grpc_handler:69)
[2021-12-03 09:42:49,378] [   ERROR] - Error: <BaseException: (code=1, message=query coordinator is not healthy)> (pymilvus.client.grpc_handler:69)
[2021-12-03 09:42:49,379] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 94, in run_suite
    result = runner.run_case(case_metric, **case)
  File "/src/milvus_benchmark/runners/search.py", line 287, in run_case
    guarantee_timestamp=case_param["guarantee_timestamp"])
  File "/src/milvus_benchmark/client.py", line 48, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 321, in query
    result = self._milvus.search(tmp_collection_name, **params)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 58, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 42, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 1048, in search
    partition_names, output_fields, timeout, round_decimal, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 104, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 643, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 605, in _execute_search_requests
    raise pre_err
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 596, in _execute_search_requests
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=query coordinator is not healthy)>
 (milvus_benchmark.main:97)
[2021-12-03 09:42:49,388] [    INFO] - None (milvus_benchmark.main:98)
[2021-12-03 09:42:49,389] [   DEBUG] - {'type': 'insert_search_performance', 'value': {}} (milvus_benchmark.main:106)
[2021-12-03 09:42:49,389] [   DEBUG] - {'_version': '0.1', '_type': 'case', 'run_id': 1638514633, 'mode': 'local', 'server': <milvus_benchmark.metrics.models.server.Server object at 0x7fc43c35a160>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware object at 0x7fc43c35a080>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7fc43c3d04a8>, 'status': 'RUN_FAILED', 'err_message': '<BaseException: (code=1, message=query coordinator is not healthy)>\nTraceback (most recent call last):\n  File "main.py", line 94, in run_suite\n    result = runner.run_case(case_metric, **case)\n  File "/src/milvus_benchmark/runners/search.py", line 287, in run_case\n    guarantee_timestamp=case_param["guarantee_timestamp"])\n  File "/src/milvus_benchmark/client.py", line 48, in wrapper\n    result = func(*args, **kwargs)\n  File "/src/milvus_benchmark/client.py", line 321, in query\n    result = self._milvus.search(tmp_collection_name, **params)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 58, in handler\n    raise e\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 42, in handler\n    return func(self, *args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 1048, in search\n    partition_names, output_fields, timeout, round_decimal, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler\n    raise e\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler\n    return func(self, *args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 104, in handler\n    return func(self, *args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 643, in search\n    return self._execute_search_requests(requests, timeout, **_kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler\n    raise e\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler\n    return func(self, *args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 605, in _execute_search_requests\n    raise pre_err\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 596, in _execute_search_requests\n    raise BaseException(response.status.error_code, response.status.reason)\npymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=query coordinator is not healthy)>\n', 'collection': {'dimension': 128, 'metric_type': 'l2', 'dataset_name': 'sift_50m_128_l2', 'fields': None, 'shards_num': None}, 'index': {'index_type': 'ivf_flat', 'index_param': {'nlist': 1024}}, 'search': {'nq': 1200, 'topk': 1000, 'search_param': {'nprobe': 32}, 'filter': [], 'guarantee_timestamp': None}, 'run_params': None, 'metrics': {'type': 'insert_search_performance', 'value': {}}, 'datetime': '2021-12-03 06:57:13.094509', 'type': 'metric'} (milvus_benchmark.metric.api:29)
[2021-12-03 09:42:49,404] [   DEBUG] - {'_version': '0.1', '_type': 'metric', 'run_id': 1638514633, 'mode': 'local', 'server': <milvus_benchmark.metrics.models.server.Server object at 0x7fc43c44cb70>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware object at 0x7fc43c44cc88>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7fc43c44cd68>, 'status': 'RUN_FAILED', 'err_message': '', 'collection': {'dimension': 128, 'metric_type': 'l2', 'dataset_name': 'sift_50m_128_l2', 'fields': None, 'shards_num': None}, 'index': {'index_type': 'ivf_flat', 'index_param': {'nlist': 1024}}, 'search': None, 'run_params': None, 'metrics': {'type': 'insert_search_performance', 'value': {}}, 'datetime': '2021-12-03 06:57:13.094509', 'type': 'metric'} (milvus_benchmark.metric.api:29)
```

### Expected Behavior

argo task： benchmark-tag-blqqf

test yaml:
client-configmap: client-search-sift50m-ivf-flat-1024
server-configmap: server-single-32c128m

server:
```
NAME                                                         READY   STATUS             RESTARTS   AGE    IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-tag-blqqf-1-etcd-0                                 0/1     Running            1          169m   10.97.17.42    qa-node014.zilliz.local   <none>           <none>
benchmark-tag-blqqf-1-milvus-standalone-6f5b48465f-5c67x     0/1     Running            1          169m   10.97.17.40    qa-node014.zilliz.local   <none>           <none>
benchmark-tag-blqqf-1-minio-6f7684fc75-6vqrs                 1/1     Running            0          169m   10.97.17.41    qa-node014.zilliz.local   <none>           <none>
```

### Steps To Reproduce

```markdown
1、create collection
2、create index of ivf_falt
3、insert 50m vectors
4、flush
5、create index with the same params
6、load collection
7、search <- raise error
```

### Anything else?

client-search-sift50m-ivf-flat-1024：
```
insert_search_performance:
      collections:
        -
          collection_name: sift_50m_128_l2
          ni_per: 50000
          build_index: true
          index_type: ivf_flat 
          index_param:
            nlist: 1024
          run_count: 30
          top_ks: [1, 10, 100, 1000]
          nqs: [1, 10, 100, 500, 1000, 1200]
          search_params:
            -
              nprobe: 8
            -
              nprobe: 32
```

**Comment by xige-16** [comment]
[standalone.log](https://github.com/milvus-io/milvus/files/7649257/standalone.log)
The standalone pod only has the log of the first few minutes of startup

**Comment by xige-16** [comment]
standalone restart at [2021/12/03 09:43:08.656 +00:00], when client call load, the querycoord is initializing，error message “query coordinator is not healthy” is the expected result.

**Comment by xige-16** [comment]
when standalone restart, report the error "panic: new session error, maybe can not connect to etcd", and restart failed

**Comment by xige-16** [comment]
the issue was caused by the high load of etcd nodes

**Comment by xige-16** [comment]
@LoveEachDay has assigned two nodes to etcd, the issue  should have been fixed
