### ISSUE TITLE
[Bug]: [benchmark][cluster] One billion data sets, when inserting more than 600 million, the insert is stuck

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#12753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20211204-0f5776e
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-2.0.0rc9.dev22
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

client pod: benchmark-no-clean-zg56b-1791458232

client log:
```
[2021-12-04 13:43:03,364] [   DEBUG] - Row count: 615999799 in collection: <sift_1b_128_l2> (milvus_benchmark.client:420)
[2021-12-04 13:43:03,365] [   DEBUG] - 615999799 (milvus_benchmark.runners.base:89)
[2021-12-04 13:43:03,747] [   DEBUG] - Start id: 642750000, end id: 642800000 (milvus_benchmark.runners.base:76)
[2021-12-04 13:43:05,179] [   DEBUG] - Milvus insert run in 1.43s (milvus_benchmark.client:52)
[2021-12-04 13:43:05,181] [   DEBUG] - Row count: 615999799 in collection: <sift_1b_128_l2> (milvus_benchmark.client:420)
[2021-12-04 13:43:05,182] [   DEBUG] - 615999799 (milvus_benchmark.runners.base:89)
[2021-12-04 13:43:06,657] [   DEBUG] - Start id: 642800000, end id: 642850000 (milvus_benchmark.runners.base:76)
[2021-12-04 13:43:08,177] [   DEBUG] - Milvus insert run in 1.52s (milvus_benchmark.client:52)
[2021-12-04 13:43:08,180] [   DEBUG] - Row count: 615999799 in collection: <sift_1b_128_l2> (milvus_benchmark.client:420)
[2021-12-04 13:43:08,180] [   DEBUG] - 615999799 (milvus_benchmark.runners.base:89)
[2021-12-04 13:43:08,557] [   DEBUG] - Start id: 642850000, end id: 642900000 (milvus_benchmark.runners.base:76)
[2021-12-04 13:43:09,956] [   DEBUG] - Milvus insert run in 1.4s (milvus_benchmark.client:52)
[2021-12-04 13:43:09,959] [   DEBUG] - Row count: 615999799 in collection: <sift_1b_128_l2> (milvus_benchmark.client:420)
[2021-12-04 13:43:09,960] [   DEBUG] - 615999799 (milvus_benchmark.runners.base:89)
[2021-12-04 13:43:10,969] [   DEBUG] - Start id: 642900000, end id: 642950000 (milvus_benchmark.runners.base:76)
```

server:
```
NAME                                                              READY   STATUS             RESTARTS   AGE     IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-no-clean-zg56b-1-etcd-0                                 1/1     Running            0          46h     10.97.17.19    qa-node014.zilliz.local   <none>           <none>
benchmark-no-clean-zg56b-1-etcd-1                                 1/1     Running            0          46h     10.97.16.165   qa-node013.zilliz.local   <none>           <none>
benchmark-no-clean-zg56b-1-etcd-2                                 1/1     Running            0          46h     10.97.17.20    qa-node014.zilliz.local   <none>           <none>
benchmark-no-clean-zg56b-1-milvus-datacoord-6ff59858d-5sj4n       1/1     Running            0          46h     10.97.12.54    qa-node015.zilliz.local   <none>           <none>
benchmark-no-clean-zg56b-1-milvus-datanode-c895c95-26jtv          0/1     CrashLoopBackOff   445        46h     10.97.17.15    qa-node014.zilliz.local   <none>           <none>
benchmark-no-clean-zg56b-1-milvus-datanode-c895c95-5svxr          0/1     Evicted            0          46h     <none>         qa-node011.zilliz.local   <none>           <none>
benchmark-no-clean-zg56b-1-milvus-datanode-c895c95-hb8mn          0/1     CrashLoopBackOff   444        37h     10.97.17.24    qa-node014.zilliz.local   <none>           <none>
benchmark-no-clean-zg56b-1-milvus-indexcoord-c7ffbbfcc-56t5l      1/1     Running            0          37h     10.97.19.36    qa-node016.zilliz.local   <none>           <none>
benchmark-no-clean-zg56b-1-milvus-indexcoord-c7ffbbfcc-pfwnx      0/1     Evicted            0          46h     <none>         qa-node006.zilliz.local   <none>           <none>
benchmark-no-clean-zg56b-1-milvus-indexnode-688c66f478-7tb6s      1/1     Running            0          46h     10.97.10.65    qa-node008.zilliz.local   <none>           <none>
benchmark-no-clean-zg56b-1-milvus-indexnode-688c66f478-7xcvf      1/1     Running            0          46h     10.97.19.32    qa-node016.zilliz.local   <none>           <none>
benchmark-no-clean-zg56b-1-milvus-indexnode-688c66f478-frc9d      1/1     Running            0          46h     10.97.20.138   qa-node018.zilliz.local   <none>           <none>
benchmark-no-clean-zg56b-1-milvus-indexnode-688c66f478-mcdl4      1/1     Running            0          46h     10.97.20.137   qa-node018.zilliz.local   <none>           <none>
benchmark-no-clean-zg56b-1-milvus-proxy-6b64d4bfc6-pwlnd          1/1     Running            0          46h     10.97.12.53    qa-node015.zilliz.local   <none>           <none>
benchmark-no-clean-zg56b-1-milvus-querycoord-67477d9674-22w5z     1/1     Running            0          37h     10.97.19.39    qa-node016.zilliz.local   <none>           <none>
benchmark-no-clean-zg56b-1-milvus-querycoord-67477d9674-5mrwl     0/1     Evicted            0          46h     <none>         qa-node011.zilliz.local   <none>           <none>
benchmark-no-clean-zg56b-1-milvus-querynode-559585fd76-8kv8x      1/1     Running            0          46h     10.97.12.56    qa-node015.zilliz.local   <none>           <none>
benchmark-no-clean-zg56b-1-milvus-querynode-559585fd76-8q8zq      1/1     Running            0          46h     10.97.17.14    qa-node014.zilliz.local   <none>           <none>
benchmark-no-clean-zg56b-1-milvus-querynode-559585fd76-9hxhr      1/1     Running            0          46h     10.97.13.247   qa-node010.zilliz.local   <none>           <none>
benchmark-no-clean-zg56b-1-milvus-querynode-559585fd76-gfjgg      1/1     Running            0          46h     10.97.20.134   qa-node018.zilliz.local   <none>           <none>
benchmark-no-clean-zg56b-1-milvus-querynode-559585fd76-qxlgz      1/1     Running            0          46h     10.97.20.136   qa-node018.zilliz.local   <none>           <none>
benchmark-no-clean-zg56b-1-milvus-querynode-559585fd76-vlphw      1/1     Running            0          46h     10.97.20.135   qa-node018.zilliz.local   <none>           <none>
benchmark-no-clean-zg56b-1-milvus-rootcoord-9c69f95f6-xt65w       1/1     Running            0          46h     10.97.12.55    qa-node015.zilliz.local   <none>           <none>
benchmark-no-clean-zg56b-1-minio-0                                1/1     Running            0          36m     10.97.14.36    qa-node011.zilliz.local   <none>           <none>
benchmark-no-clean-zg56b-1-minio-1                                1/1     Running            0          46h     10.97.19.34    qa-node016.zilliz.local   <none>           <none>
benchmark-no-clean-zg56b-1-minio-2                                0/1     Pending            0          2m20s   <none>         <none>                    <none>           <none>
benchmark-no-clean-zg56b-1-minio-3                                1/1     Running            0          30m     10.97.6.116    qa-node004.zilliz.local   <none>           <none>
benchmark-no-clean-zg56b-1-pulsar-autorecovery-574bb76d6d-q2gb8   0/1     Evicted            0          46h     <none>         qa-node006.zilliz.local   <none>           <none>
benchmark-no-clean-zg56b-1-pulsar-autorecovery-574bb76d6d-wcrp8   1/1     Running            0          37h     10.97.17.25    qa-node014.zilliz.local   <none>           <none>
benchmark-no-clean-zg56b-1-pulsar-bastion-78f4cdb8cd-zqlkv        1/1     Running            0          46h     10.97.13.246   qa-node010.zilliz.local   <none>           <none>
benchmark-no-clean-zg56b-1-pulsar-bookkeeper-0                    1/1     Running            0          46h     10.97.15.145   qa-node012.zilliz.local   <none>           <none>
benchmark-no-clean-zg56b-1-pulsar-bookkeeper-1                    1/1     Running            0          46h     10.97.17.22    qa-node014.zilliz.local   <none>           <none>
benchmark-no-clean-zg56b-1-pulsar-bookkeeper-2                    1/1     Running            0          37h     10.97.13.252   qa-node010.zilliz.local   <none>           <none>
benchmark-no-clean-zg56b-1-pulsar-broker-5f74f784f-fpx8t          1/1     Running            0          46h     10.97.17.16    qa-node014.zilliz.local   <none>           <none>
benchmark-no-clean-zg56b-1-pulsar-proxy-58c47d99b5-bq677          2/2     Running            0          46h     10.97.15.144   qa-node012.zilliz.local   <none>           <none>
benchmark-no-clean-zg56b-1-pulsar-zookeeper-0                     1/1     Running            0          37h     10.97.3.77     qa-node001.zilliz.local   <none>           <none>
benchmark-no-clean-zg56b-1-pulsar-zookeeper-1                     1/1     Running            0          37h     10.97.10.69    qa-node008.zilliz.local   <none>           <none>
benchmark-no-clean-zg56b-1-pulsar-zookeeper-2                     1/1     Running            0          46h     10.97.13.248   qa-node010.zilliz.local   <none>           <none>
benchmark-no-clean-zg56b-1-pulsar-zookeeper-metadata-jtx5m        0/1     Completed          0          46h     10.97.14.188   qa-node011.zilliz.local   <none>           <none>
```

### Expected Behavior

argo task: benchmark-no-clean-zg56b

test yaml:
client-configmap:client-random-locust-search-84h-1b
server-configmap:server-cluster-8c64m-datanode2-indexnode4-querynode6-nocompaction

**Comment by congqixia** [comment]
The reason datanodes continue to crash is that the recovery point has segment(s) with non-empty start position but empty dml position. Some code will crash is this situation in creating new DataSyncService.
The first crash may caused by mal-function of minio. Will update after find any log evidence.

**Comment by congqixia** [comment]
> The reason datanodes continue to crash is that the recovery point has segment(s) with non-empty start position but empty dml position. Some code will crash is this situation in creating new DataSyncService. The first crash may caused by mal-function of minio. Will update after find any log evidence.

Datanode first crashed with log:
```
[2021/12/04 13:26:12.292 +00:00] [WARN] [flush_task.go:203] ["flush task error detected"] [error="All attempts results:\nattempt #1:Please reduce your request\nattempt #2:Please reduce your request\nattempt #3:Please reduce your request\nattempt #4:Please reduce your request\nattempt #5:Please reduce your request\nattempt #6:Please reduce your request\nattempt #7:Please reduce your request\nattempt #8:Please reduce your request\nattempt #9:Please reduce your request\nattempt #10:Please reduce your request\n"] []
[2021/12/04 13:26:12.292 +00:00] [WARN] [flush_manager.go:680] ["flush pack with error, data node quit now"]
goroutine 650776 [running]:
github.com/milvus-io/milvus/internal/datanode.flushNotifyFunc.func1(0xc11f8c1630)
	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_manager.go:682 +0x15a7
	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_task.go:186 +0xbd
created by github.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).init.func1

github.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).waitFinish(0xc0004c0540, 0xc0070a6870, 0xc0192221a0)
panic: execution failed
	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_task.go:118 +0xb0
```
It failed to save binlog to etcd

**Comment by congqixia** [comment]
@wangting0128 keep restart issue fixed. Root cause was env (resource exhausted). Could you please verify?
/unassign @sunby 
/assign @wangting0128
