### ISSUE TITLE
[Bug]:[data compatibility] Search raise rpc timeout error after re-start standalone milvus installed by docker-compose 

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#12769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:  `43ef945`
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc9.dev22
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
Search...
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/stub.py", line 42, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/stub.py", line 1047, in search
    return handler.search(collection_name, data, anns_field, param, limit, expression,
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 85, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 104, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 643, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 85, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 605, in _execute_search_requests
    raise pre_err
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 593, in _execute_search_requests
    response = ft.result()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1638771769.721194240","description":"Error received from peer ipv4:127.0.0.1:19530","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/action_reinstall.py", line 11, in <module>
    load_and_search()
  File "/home/runner/work/milvus/milvus/tests/python_client/deploy/scripts/utils.py", line 136, in load_and_search
    res = c.search(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 687, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/stub.py", line 53, in handler
    raise BaseException(1, "rpc timeout")
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=rpc timeout)>

```

### Expected Behavior

works well

### Steps To Reproduce

```markdown
see script `tests/python_client/deploy/test.sh`
```

### Anything else?

logs:
[logs-standalone-reinstall](https://github.com/zhuwenxing/milvus/suites/4562362525/artifacts/122607792)

This issue only happened when deploying standalone milvus by docker-compose

**Comment by yanliang567** [comment]
@xige-16 you can reproduce it by rerun the tests in github actions. https://github.com/milvus-io/milvus/actions/runs/1546503405

**Comment by zhuwenxing** [comment]
This reproduces on local env, so set it as urgent.

Note that, before re-start, the collection was not released.

**Comment by zhuwenxing** [comment]
Test steps:
1. deploy standalone milvus by docker-compose
2. cd `tests/python_client/deploy/scripts` and run `python action_reinstall.py`
3. docker-compose down but keep volumes
4. docker-compose up -d
5. cd `tests/python_client/deploy/scripts` and run `python action_reinstall.py`

The issue happens in step 5

**Comment by xige-16** [comment]
when recover dmchannels of collection 429594090552950785, a dmchannel was missed.
```
[DEBUG] [task.go:2116] ["assignInternalTask: assign segment to node success"] ["load segments requests"="[{\"base\":{\"msg_type\":252,\"sourceID\":11},\"dst_nodeID\":15,\"infos\":[{\"segmentID\":429594090592272385,\"partitionID\":429594090552950786,\"collectionID\":429594090552950785,\"binlog_paths\":[{\"fieldID\":1,\"binlogs\":[\"files/insert_log/429594090552950785/429594090552950786/429594090592272385/1/429594091208310794\"]},{\"fieldID\":100,\"binlogs\":[\"files/insert_log/429594090552950785/429594090552950786/429594090592272385/100/429594091208310790\"]},{\"fieldID\":101,\"binlogs\":[\"files/insert_log/429594090552950785/429594090552950786/429594090592272385/101/429594091208310791\"]},{\"fieldID\":102,\"binlogs\":[\"files/insert_log/429594090552950785/429594090552950786/429594090592272385/102/429594091208310792\"]},{\"binlogs\":[\"files/insert_log/429594090552950785/429594090552950786/429594090592272385/0/429594091208310793\"]}],\"num_of_rows\":1503,\"statslogs\":[{\"binlogs\":[\"files/stats_log/429594090552950785/429594090552950786/429594090592272385/0/429594091208310793\"]},{\"fieldID\":1,\"binlogs\":[\"files/stats_log/429594090552950785/429594090552950786/429594090592272385/1/429594091208310794\"]},{\"fieldID\":100,\"binlogs\":[\"files/stats_log/429594090552950785/429594090552950786/429594090592272385/100/429594091208310790\"]}],\"enable_index\":true,\"index_path_infos\":[{\"indexBuildID\":429594100957446148,\"index_file_paths\":[\"files/index_files/429594100957446148/1/429594090552950786/429594090592272385/META\",\"files/index_files/429594100957446148/1/429594090552950786/429594090592272385/RAW_DATA\",\"files/index_files/429594100957446148/1/429594090552950786/429594090592272385/RHNSW_FLAT_Index\",\"files/index_files/429594100957446148/1/429594090552950786/429594090592272385/indexParams\"]}]}],\"schema\":{\"name\":\"RHNSW_FLAT\",\"description\":\"test collection\",\"fields\":[{\"fieldID\":100,\"name\":\"count\",\"is_primary_key\":true,\"data_type\":5},{\"fieldID\":101,\"name\":\"random_value\",\"data_type\":11},{\"fieldID\":102,\"name\":\"float_vector\",\"data_type\":101,\"type_params\":[{\"key\":\"dim\",\"value\":\"128\"}]}]},\"load_condition\":3,\"source_nodeID\":7},{\"base\":{\"msg_type\":252,\"sourceID\":11},\"dst_nodeID\":15,\"infos\":[{\"segmentID\":429594090592272386,\"partitionID\":429594090552950786,\"collectionID\":429594090552950785,\"binlog_paths\":[{\"fieldID\":100,\"binlogs\":[\"files/insert_log/429594090552950785/429594090552950786/429594090592272386/100/429594091208310785\"]},{\"fieldID\":101,\"binlogs\":[\"files/insert_log/429594090552950785/429594090552950786/429594090592272386/101/429594091208310786\"]},{\"fieldID\":102,\"binlogs\":[\"files/insert_log/429594090552950785/429594090552950786/429594090592272386/102/429594091208310787\"]},{\"binlogs\":[\"files/insert_log/429594090552950785/429594090552950786/429594090592272386/0/429594091208310788\"]},{\"fieldID\":1,\"binlogs\":[\"files/insert_log/429594090552950785/429594090552950786/429594090592272386/1/429594091208310789\"]}],\"num_of_rows\":1497,\"statslogs\":[{\"fieldID\":100,\"binlogs\":[\"files/stats_log/429594090552950785/429594090552950786/429594090592272386/100/429594091208310785\"]},{\"binlogs\":[\"files/stats_log/429594090552950785/429594090552950786/429594090592272386/0/429594091208310788\"]},{\"fieldID\":1,\"binlogs\":[\"files/stats_log/429594090552950785/429594090552950786/429594090592272386/1/429594091208310789\"]}],\"enable_index\":true,\"index_path_infos\":[{\"indexBuildID\":429594100957446146,\"index_file_paths\":[\"files/index_files/429594100957446146/1/429594090552950786/429594090592272386/META\",\"files/index_files/429594100957446146/1/429594090552950786/429594090592272386/RAW_DATA\",\"files/index_files/429594100957446146/1/429594090552950786/429594090592272386/RHNSW_FLAT_Index\",\"files/index_files/429594100957446146/1/429594090552950786/429594090592272386/indexParams\"]}]}],\"schema\":{\"name\":\"RHNSW_FLAT\",\"description\":\"test collection\",\"fields\":[{\"fieldID\":100,\"name\":\"count\",\"is_primary_key\":true,\"data_type\":5},{\"fieldID\":101,\"name\":\"random_value\",\"data_type\":11},{\"fieldID\":102,\"name\":\"float_vector\",\"data_type\":101,\"type_params\":[{\"key\":\"dim\",\"value\":\"128\"}]}]},\"load_condition\":3,\"source_nodeID\":7}]"]
[DEBUG] [task.go:2123] ["assignInternalTask: assign dmChannel to node success"] ["watch dmChannel requests"="[{\"base\":{\"msg_type\":508,\"sourceID\":11},\"nodeID\":15,\"collectionID\":429594090552950785,\"infos\":[{\"collectionID\":429594090552950785,\"channelName\":\"by-dev-rootcoord-dml_13_429594090552950785v1\",\"seek_position\":{\"channel_name\":\"by-dev-rootcoord-dml_13_429594090552950785v1\",\"msgID\":\"NQpAfIk59gU=\",\"msgGroup\":\"by-dev-dataNode-8-429594090552950785\",\"timestamp\":429594091168989185},\"flushedSegments\":[{\"ID\":429594090592272386,\"collectionID\":429594090552950785,\"partitionID\":429594090552950786,\"insert_channel\":\"by-dev-rootcoord-dml_13_429594090552950785v1\",\"num_of_rows\":1497,\"state\":4,\"max_row_num\":986895,\"last_expire_time\":429594091116560388,\"start_position\":{\"channel_name\":\"by-dev-rootcoord-dml_13_429594090552950785v1\",\"msgID\":\"IghAfIk59gU=\"},\"dml_position\":{\"channel_name\":\"by-dev-rootcoord-dml_13_429594090552950785v1\",\"msgID\":\"NQpAfIk59gU=\",\"msgGroup\":\"by-dev-dataNode-8-429594090552950785\",\"timestamp\":429594091168989185}}]}],\"schema\":{\"name\":\"RHNSW_FLAT\",\"description\":\"test collection\",\"fields\":[{\"fieldID\":100,\"name\":\"count\",\"is_primary_key\":true,\"data_type\":5},{\"fieldID\":101,\"name\":\"random_value\",\"data_type\":11},{\"fieldID\":102,\"name\":\"float_vector\",\"data_type\":101,\"type_params\":[{\"key\":\"dim\",\"value\":\"128\"}]}]}}]"]
[DEBUG] [task.go:1867] ["loadBalanceTask: add a childTask"] ["task type"=252] [task="base:<msg_type:LoadSegments sourceID:11 > dst_nodeID:15 infos:<segmentID:429594090592272385 partitionID:429594090552950786 collectionID:429594090552950785 binlog_paths:<fieldID:1 binlogs:\"files/insert_log/429594090552950785/429594090552950786/429594090592272385/1/429594091208310794\" > binlog_paths:<fieldID:100 binlogs:\"files/insert_log/429594090552950785/429594090552950786/429594090592272385/100/429594091208310790\" > binlog_paths:<fieldID:101 binlogs:\"files/insert_log/429594090552950785/429594090552950786/429594090592272385/101/429594091208310791\" > binlog_paths:<fieldID:102 binlogs:\"files/insert_log/429594090552950785/429594090552950786/429594090592272385/102/429594091208310792\" > binlog_paths:<binlogs:\"files/insert_log/429594090552950785/429594090552950786/429594090592272385/0/429594091208310793\" > num_of_rows:1503 statslogs:<binlogs:\"files/stats_log/429594090552950785/429594090552950786/429594090592272385/0/429594091208310793\" > statslogs:<fieldID:1 binlogs:\"files/stats_log/429594090552950785/429594090552950786/429594090592272385/1/429594091208310794\" > statslogs:<fieldID:100 binlogs:\"files/stats_log/429594090552950785/429594090552950786/429594090592272385/100/429594091208310790\" > enable_index:true index_path_infos:<indexBuildID:429594100957446148 index_file_paths:\"files/index_files/429594100957446148/1/429594090552950786/429594090592272385/META\" index_file_paths:\"files/index_files/429594100957446148/1/429594090552950786/429594090592272385/RAW_DATA\" index_file_paths:\"files/index_files/429594100957446148/1/429594090552950786/429594090592272385/RHNSW_FLAT_Index\" index_file_paths:\"files/index_files/429594100957446148/1/429594090552950786/429594090592272385/indexParams\" > > infos:<segmentID:429594090592272386 partitionID:429594090552950786 collectionID:429594090552950785 binlog_paths:<fieldID:100 binlogs:\"files/insert_log/429594090552950785/429594090552950786/429594090592272386/100/429594091208310785\" > binlog_paths:<fieldID:101 binlogs:\"files/insert_log/429594090552950785/429594090552950786/429594090592272386/101/429594091208310786\" > binlog_paths:<fieldID:102 binlogs:\"files/insert_log/429594090552950785/429594090552950786/429594090592272386/102/429594091208310787\" > binlog_paths:<binlogs:\"files/insert_log/429594090552950785/429594090552950786/429594090592272386/0/429594091208310788\" > binlog_paths:<fieldID:1 binlogs:\"files/insert_log/429594090552950785/429594090552950786/429594090592272386/1/429594091208310789\" > num_of_rows:1497 statslogs:<fieldID:100 binlogs:\"files/stats_log/429594090552950785/429594090552950786/429594090592272386/100/429594091208310785\" > statslogs:<binlogs:\"files/stats_log/429594090552950785/429594090552950786/429594090592272386/0/429594091208310788\" > statslogs:<fieldID:1 binlogs:\"files/stats_log/429594090552950785/429594090552950786/429594090592272386/1/429594091208310789\" > enable_index:true index_path_infos:<indexBuildID:429594100957446146 index_file_paths:\"files/index_files/429594100957446146/1/429594090552950786/429594090592272386/META\" index_file_paths:\"files/index_files/429594100957446146/1/429594090552950786/429594090592272386/RAW_DATA\" index_file_paths:\"files/index_files/429594100957446146/1/429594090552950786/429594090592272386/RHNSW_FLAT_Index\" index_file_paths:\"files/index_files/429594100957446146/1/429594090552950786/429594090592272386/indexParams\" > > schema:<name:\"RHNSW_FLAT\" description:\"test collection\" fields:<fieldID:100 name:\"count\" is_primary_key:true data_type:Int64 > fields:<fieldID:101 name:\"random_value\" data_type:Double > fields:<fieldID:102 name:\"float_vector\" data_type:FloatVector type_params:<key:\"dim\" value:\"128\" > > > load_condition:nodeDown source_nodeID:7 "]
[DEBUG] [task.go:1867] ["loadBalanceTask: add a childTask"] ["task type"=513] [task="base:<msg_type:WatchDeltaChannels sourceID:11 > nodeID:15 collectionID:429594090552950785 infos:<collectionID:429594090552950785 channelName:\"by-dev-rootcoord-delta_12_429594090552950785v0\" seek_position:<channel_name:\"by-dev-rootcoord-dml_12_429594090552950785v0\" msgID:\"1\\n@|\\2119\\366\\005\" msgGroup:\"by-dev-dataNode-8-429594090552950785\" timestamp:429594091168989185 > > infos:<collectionID:429594090552950785 channelName:\"by-dev-rootcoord-delta_13_429594090552950785v1\" seek_position:<channel_name:\"by-dev-rootcoord-dml_13_429594090552950785v1\" msgID:\"5\\n@|\\2119\\366\\005\" msgGroup:\"by-dev-dataNode-8-429594090552950785\" timestamp:429594091168989185 > > "]
[DEBUG] [task.go:1867] ["loadBalanceTask: add a childTask"] ["task type"=508] [task="base:<msg_type:WatchDmChannels sourceID:11 > nodeID:15 collectionID:429594090552950785 infos:<collectionID:429594090552950785 channelName:\"by-dev-rootcoord-dml_13_429594090552950785v1\" seek_position:<channel_name:\"by-dev-rootcoord-dml_13_429594090552950785v1\" msgID:\"5\\n@|\\2119\\366\\005\" msgGroup:\"by-dev-dataNode-8-429594090552950785\" timestamp:429594091168989185 > flushedSegments:<ID:429594090592272386 collectionID:429594090552950785 partitionID:429594090552950786 insert_channel:\"by-dev-rootcoord-dml_13_429594090552950785v1\" num_of_rows:1497 state:Flushed max_row_num:986895 last_expire_time:429594091116560388 start_position:<channel_name:\"by-dev-rootcoord-dml_13_429594090552950785v1\" msgID:\"\\\"\\010@|\\2119\\366\\005\" > dml_position:<channel_name:\"by-dev-rootcoord-dml_13_429594090552950785v1\" msgID:\"5\\n@|\\2119\\366\\005\" msgGroup:\"by-dev-dataNode-8-429594090552950785\" timestamp:429594091168989185 > > > schema:<name:\"RHNSW_FLAT\" description:\"test collection\" fields:<fieldID:100 name:\"count\" is_primary_key:true data_type:Int64 > fields:<fieldID:101 name:\"random_value\" data_type:Double > fields:<fieldID:102 name:\"float_vector\" data_type:FloatVector type_params:<key:\"dim\" value:\"128\" > > > "]
[DEBUG] [task.go:1867] ["loadBalanceTask: add a childTask"] ["task type"=510] [task="base:<msg_type:WatchQueryChannels sourceID:11 > nodeID:15 collectionID:429594090552950785 request_channelID:\"by-dev-search-0\" result_channelID:\"by-dev-searchResult-0\" seek_position:<channel_name:\"by-dev-search-0\" msgID:\"\\002\\000H\\250\\2179\\366\\005\" > global_sealed_segments:<segmentID:429594090592272385 collectionID:429594090552950785 partitionID:429594090552950786 nodeID:7 segment_state:sealed > global_sealed_segments:<segmentID:429594090592272386 collectionID:429594090552950785 partitionID:429594090552950786 nodeID:7 segment_state:sealed > "]
[DEBUG] [task.go:1869] ["loadBalanceTask: assign child task done"] [collectionID=429594090552950785] [partitionIDs="[429594090552950786]"]
[DEBUG] [task.go:1739] ["loadBalanceTask: partitions to recover"] [partitionIDs="[429594092702531586]"]
```

**Comment by xige-16** [comment]
same with issue #12190
