### ISSUE TITLE
[Bug]:   Milvus is crashed with panic when flushing

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#13064]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 6f68ce46f
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): rc9.22
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Milvus is crashed with panic
```
[2021/12/09 05:44:41.586 +00:00] [DEBUG] [service.go:174] ["QueryCoord wait for DataCoord ready failed"] [error="All attempts results:\nattempt #1:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #2:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #3:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #4:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #5:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #6:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #7:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #8:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #9:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #10:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #11:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #12:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #13:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #14:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #15:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #16:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #17:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #18:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #19:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #20:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #21:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #22:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #23:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #24:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #25:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #26:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #27:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #28:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #29:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #30:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #31:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #32:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #33:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #34:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #35:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #36:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #37:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #38:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #39:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #40:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #41:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #42:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #43:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #44:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #45:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #46:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #47:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #48:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #49:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #50:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #51:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #52:WaitForComponentStates, not meet, DataCoord current state:0\nattempt #53:context canceled\n"]

panic: All attempts results:

attempt #1:WaitForComponentStates, not meet, DataCoord current state:0

attempt #2:WaitForComponentStates, not meet, DataCoord current state:0

attempt #3:WaitForComponentStates, not meet, DataCoord current state:0

attempt #4:WaitForComponentStates, not meet, DataCoord current state:0

attempt #5:WaitForComponentStates, not meet, DataCoord current state:0

attempt #6:WaitForComponentStates, not meet, DataCoord current state:0

attempt #7:WaitForComponentStates, not meet, DataCoord current state:0

attempt #8:WaitForComponentStates, not meet, DataCoord current state:0

attempt #9:WaitForComponentStates, not meet, DataCoord current state:0

attempt #10:WaitForComponentStates, not meet, DataCoord current state:0

attempt #11:WaitForComponentStates, not meet, DataCoord current state:0

attempt #12:WaitForComponentStates, not meet, DataCoord current state:0

attempt #13:WaitForComponentStates, not meet, DataCoord current state:0

attempt #14:WaitForComponentStates, not meet, DataCoord current state:0
```

### Expected Behavior

No crash

### Steps To Reproduce

Run CI:

1. test logs:
https://ci.milvus.io:18080/jenkins/blue/rest/organizations/jenkins/pipelines/milvus-ha-ci/branches/PR-13050/runs/2/nodes/61/steps/114/log/?start=0

2. Milvus logs: [artifacts-milvus-standalone-PR-13050-2-pymilvus-e2e-logs.tar.gz]

https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-13050/2/artifacts/

Clues：

panic log file: 
"jenkins.var.log.containers.ms-13050-2-milvus-standalone-86486787f4-bnf9l_milvus-ci_standalone-965f97fb97974bfc4d9e38f921b5e96c368c4382de3f29f7ee137ba63eb34398.log"

collection name: utility_VdM8mxUd

Timeline： [when flushing]
```
[2021-12-09T06:15:21.513Z] Addr [ms-13050-2-milvus.milvus-ci:19530] get_flush_state
[2021-12-09T06:15:21.513Z] RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
[2021-12-09T06:15:21.513Z] 	status = StatusCode.UNAVAILABLE
[2021-12-09T06:15:21.513Z] 	details = "Socket closed"
[2021-12-09T06:15:21.513Z] 	debug_error_string = "{"created":"@1639030477.277075308","description":"Error received from peer ipv4:10.201.127.17:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Socket closed","grpc_status":14}"
[2021-12-09T06:15:21.513Z] >
[2021-12-09T06:15:21.513Z] 	{'API start': '2021-12-09 06:14:30.782295', 'RPC start': '2021-12-09 06:14:30.783122', 'RPC error': '2021-12-09 06:14:37.277597'} (grpc_handler.py:84)
[2021-12-09T06:15:21.513Z] [2021-12-09 06:14:37 - ERROR - pymilvus.client.grpc_handler]: 
[2021-12-09T06:15:21.513Z] Addr [ms-13050-2-milvus.milvus-ci:19530] _wait_for_flushed
[2021-12-09T06:15:21.513Z] RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
[2021-12-09T06:15:21.513Z] 	status = StatusCode.UNAVAILABLE
[2021-12-09T06:15:21.513Z] 	details = "Socket closed"
[2021-12-09T06:15:21.513Z] 	debug_error_string = "{"created":"@1639030477.277075308","description":"Error received from peer ipv4:10.201.127.17:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Socket closed","grpc_status":14}"
```

**Comment by congqixia** [comment]
Standalone has three run in this PR:
1. Datacoord cannot be healthy so the standalone restarted (05:40:47-05:44:41)
2. The working run, it became healthy and provided ci test services until panic for etcd error (05:44:42 - 06:14:37)
3. Restarted run run 2, killed since test case failed.

So the main target is Run2, which panicked with this error:
```
[2021/12/09 06:14:37.148 +00:00] [WARN] [etcd_kv.go:424] ["Slow etcd operation remove"] ["time spent"=7.000776298s]

panic: etcdserver: request timed out



goroutine 750 [running]:

github.com/milvus-io/milvus/internal/querycoord.(*MetaReplica).removeGlobalSealedSegInfos(0xc0004682d0, 0x5f6775051000001, 0x0, 0x0, 0x0, 0x203002, 0x50000c00672dc00, 0xffffffffffffffff)

	/go/src/github.com/milvus-io/milvus/internal/querycoord/meta.go:656 +0x12a5

github.com/milvus-io/milvus/internal/querycoord.updateSegmentInfoFromTask(0x3175ec0, 0xc000173640, 0x3198000, 0xc0059eb280, 0x3199040, 0xc0004682d0, 0x0, 0xc003a0d480)

	/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:878 +0xcb4

github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).scheduleLoop(0xc000159ea0)

	/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:647 +0xe6b

created by github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).Start

	/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:856 +0x65
```

One etcd operation took 7 seconds and then querycoord panic with etcd operation timeout.

In etcd log, we found slow log:
```
{"level":"warn","ts":"2021-12-09T06:14:37.258Z","caller":"wal/wal.go:802","msg":"slow fdatasync","took":"7.111999273s","expected-duration":"1s"}
```
And there was almost a slow log every minute.
So the root cause shall be the env noisy.
@LoveEachDay is working on checking the ci cluster disk.
@binbinlv could please check and verify?
/unassgin
/assign @binbinlv

**Comment by binbinlv** [comment]
Did not reproduce, so close it first, will reopen it if it occurs again.
