### ISSUE TITLE
[Bug]: [benchmark][standalone] load raise error: The specified key does not exist

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#13250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20211210-175f314
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus-2.0.0rc9.dev22
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

client pod: benchmark-cluster-cron-1639170000-186218196

client log:
```
[2021-12-11 00:00:51,040] [   DEBUG] - Row count: 49800000 in collection: <local_50m_512_l2> (milvus_benchmark.client:420)
[2021-12-11 00:00:51,042] [   DEBUG] - 49800000 (milvus_benchmark.runners.base:89)
[2021-12-11 00:00:57,163] [   DEBUG] - Start id: 49950000, end id: 50000000 (milvus_benchmark.runners.base:76)
[2021-12-11 00:01:02,315] [   DEBUG] - Milvus insert run in 5.15s (milvus_benchmark.client:52)
[2021-12-11 00:01:02,332] [   DEBUG] - Row count: 49800000 in collection: <local_50m_512_l2> (milvus_benchmark.client:420)
[2021-12-11 00:01:02,333] [   DEBUG] - 49800000 (milvus_benchmark.runners.base:89)
[2021-12-11 00:01:02,335] [    INFO] - {'total_time': 4897.34, 'rps': 10209.63, 'ni_time': 4.9} (milvus_benchmark.runners.base:151)
[2021-12-11 00:12:55,003] [   DEBUG] - Milvus flush run in 712.24s (milvus_benchmark.client:52)
[2021-12-11 00:12:55,009] [   DEBUG] - Row count: 50000000 in collection: <local_50m_512_l2> (milvus_benchmark.client:420)
[2021-12-11 00:12:55,009] [   DEBUG] - {'collection count': 50000000} (milvus_benchmark.runners.get:123)
[2021-12-11 00:12:55,010] [   DEBUG] - {'flush_time': 712.24} (milvus_benchmark.runners.get:124)
[2021-12-11 00:12:55,011] [   DEBUG] - Start load collection (milvus_benchmark.runners.get:125)
[2021-12-11 00:13:10,671] [   ERROR] - Error: <BaseException: (code=1, message=, The specified key does not exist.)> (pymilvus.client.grpc_handler:69)
[2021-12-11 00:13:10,672] [   ERROR] - <BaseException: (code=1, message=, The specified key does not exist.)> (milvus_benchmark.main:117)
[2021-12-11 00:13:10,677] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 86, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/get.py", line 126, in prepare
    self.milvus.load_collection(timeout=1200)
  File "/src/milvus_benchmark/client.py", line 48, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 482, in load_collection
    return self._milvus.load_collection(collection_name, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 58, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 42, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 322, in load_collection
    return handler.load_collection("", collection_name=collection_name, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 835, in load_collection
    raise BaseException(response.error_code, response.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=, The specified key does not exist.)>
 (milvus_benchmark.main:118)
[2021-12-11 00:13:10,678] [   DEBUG] - {'_version': '0.1', '_type': 'metric', 'run_id': 1639170460, 'mode': 'local', 'server': <milvus_benchmark.metrics.models.server.Server object at 0x7fc887d4cbe0>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware object at 0x7fc887d4ccf8>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7fc887d4ce80>, 'status': 'RUN_FAILED', 'err_message': '', 'collection': {'dimension': 512, 'metric_type': 'l2', 'dataset_name': 'local_50m_512_l2', 'collection_size': 50000000, 'other_fields': None, 'ni_per': 50000, 'shards_num': None}, 'index': {'index_type': 'ivf_sq8', 'index_param': {'nlist': 1024}}, 'search': None, 'run_params': None, 'metrics': {'type': 'insert_get_performance', 'value': {}}, 'datetime': '2021-12-10 21:07:40.686968', 'type': 'metric'} (milvus_benchmark.metric.api:29)
```

### Expected Behavior

argo task: benchmark-cluster-cron-1639170000

test yaml:
client-configmap: client-get-local50m-512
server-configmap: server-single-32c128m

server:
```
NAME                                                              READY   STATUS             RESTARTS   AGE     IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-cluster-cron-1639170000-1-etcd-0                        1/1     Running            0          3h13m   10.97.17.80    qa-node014.zilliz.local   <none>           <none>
benchmark-cluster-cron-1639170000-1-milvus-standalone-6f59rsglg   1/1     Running            1          3h13m   10.97.16.108   qa-node013.zilliz.local   <none>           <none>
benchmark-cluster-cron-1639170000-1-minio-db496696f-56g9k         1/1     Running            0          3h13m   10.97.12.84    qa-node015.zilliz.local   <none>           <none>
```

### Steps To Reproduce

```markdown
1、create collection
2、insert 50 million vectors
3、flush collection
4、load collection <- raise error
```

### Anything else?

client-get-local50m-512:
```
insert_get_performance:
      collections:
        -
          collection_name: local_50m_512_l2
          ni_per: 50000
          build_index: false
          index_type: ivf_sq8
          index_param:
            nlist: 1024
          ids_length_list:
            [1, 100, 10000]
```

**Comment by XuanYang-cn** [comment]
Not reproducing lately

**Comment by xiaofan-luan** [comment]
close for now
