### ISSUE TITLE
[Bug]: [chaos][datacoord][rootcoord]e2e test failed after deleting datacoord or rootcoord pod kill chaos

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#13256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: `master-20211213-4992c87`
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc9.dev22
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

e2e test failed after deleting datacoord pod kill chaos

```
testcases/test_e2e.py::TestE2e::test_milvus_default 
-------------------------------- live log setup --------------------------------
[2021-12-13 06:18:53 - INFO - ci_test]: ################################################################################ (conftest.py:165)
[2021-12-13 06:18:53 - INFO - ci_test]: [initialize_milvus] Log cleaned up, start testing... (conftest.py:166)
[2021-12-13 06:18:53 - INFO - ci_test]: [setup_class] Start setup class... (client_base.py:44)
[2021-12-13 06:18:53 - INFO - ci_test]: *********************************** setup *********************************** (client_base.py:50)
[2021-12-13 06:18:53 - INFO - ci_test]: [setup_method] Start setup test case test_milvus_default. (client_base.py:51)
-------------------------------- live log call ---------------------------------
[2021-12-13 06:18:54 - INFO - ci_test]: assert create collection: 1.1875872611999512, init_entities: 0 (test_e2e.py:24)
[2021-12-13 06:18:55 - INFO - ci_test]: assert insert: 0.6571390628814697 (test_e2e.py:31)
[2021-12-13 06:18:58 - INFO - ci_test]: assert flush: 3.119951009750366, entities: 3000 (test_e2e.py:39)
[2021-12-13 06:19:08 - ERROR - pymilvus.client.grpc_handler]: Error: <BaseException: (code=1, message=, context deadline exceeded)> (grpc_handler.py:69)
[2021-12-13 06:19:08 - ERROR - ci_test]: Traceback (most recent call last):
  File "/home/runner/work/milvus/milvus/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
    res = func(*args, **kwargs)
  File "/home/runner/work/milvus/milvus/tests/python_client/utils/api_request.py", line 56, in api_request
    return func(*arg, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 454, in load
    conn.load_collection(self._name, timeout=timeout, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/stub.py", line 58, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/stub.py", line 42, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/stub.py", line 322, in load_collection
    return handler.load_collection("", collection_name=collection_name, timeout=timeout, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 835, in load_collection
    raise BaseException(response.error_code, response.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=, context deadline exceeded)>
 (api_request.py:35)
[2021-12-13 06:19:08 - ERROR - ci_test]: (api_response) : <BaseException: (code=1, message=, context deadline exceeded)> (api_request.py:36)
FAILED
```

```
[2021/12/13 06:19:08.647 +00:00] [DEBUG] [id.go:141] ["IDAllocator pickCanDoFunc"] [need=1] [total=157502] [remainReqCnt=0]
[2021/12/13 06:19:08.647 +00:00] [DEBUG] [impl.go:1558] ["DescribeIndex enqueued"] [traceID=57ed223f669e9508] [role=Proxy] [MsgID=429752556886205955] [BeginTs=429752673527136259] [EndTs=429752673527136259] [db=] [collection=e2e__3ULZrAVj] [field=] ["index name"=]
[2021/12/13 06:19:08.648 +00:00] [ERROR] [task_scheduler.go:461] ["Failed to execute task: index not exist"] [traceID=57ed223f669e9508] [stack="github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:461\ngithub.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:486"]
[2021/12/13 06:19:08.648 +00:00] [WARN] [impl.go:1571] ["DescribeIndex failed to WaitToFinish"] [error="index not exist"] [traceID=57ed223f669e9508] [role=Proxy] [MsgID=429752556886205955] [BeginTs=429752673527136259] [EndTs=429752673527136259] [db=] [collection=e2e__3ULZrAVj] [field=] ["index name"=]
[2021/12/13 06:19:08.650 +00:00] [DEBUG] [impl.go:251] ["DropCollection received"] [traceID=588186040d55ab4b] [role=Proxy] [db=] [collection=e2e__3ULZrAVj]
```

### Expected Behavior

This is a successful example 
```
testcases/test_e2e.py::TestE2e::test_milvus_default 
-------------------------------- live log setup --------------------------------
[2021-12-13 06:21:26 - INFO - ci_test]: ################################################################################ (conftest.py:165)
[2021-12-13 06:21:26 - INFO - ci_test]: [initialize_milvus] Log cleaned up, start testing... (conftest.py:166)
[2021-12-13 06:21:26 - INFO - ci_test]: [setup_class] Start setup class... (client_base.py:44)
[2021-12-13 06:21:26 - INFO - ci_test]: *********************************** setup *********************************** (client_base.py:50)
[2021-12-13 06:21:26 - INFO - ci_test]: [setup_method] Start setup test case test_milvus_default. (client_base.py:51)
-------------------------------- live log call ---------------------------------
[2021-12-13 06:21:27 - INFO - ci_test]: assert create collection: 1.095484972000122, init_entities: 0 (test_e2e.py:24)
[2021-12-13 06:21:28 - INFO - ci_test]: assert insert: 0.647528886795044 (test_e2e.py:31)
[2021-12-13 06:21:31 - INFO - ci_test]: assert flush: 3.11745548248291, entities: 3000 (test_e2e.py:39)
[2021-12-13 06:21:33 - INFO - ci_test]: assert search: 0.291187047958374 (test_e2e.py:50)
[2021-12-13 06:21:38 - INFO - ci_test]: assert index entities: 6000 (test_e2e.py:57)
[2021-12-13 06:21:42 - INFO - ci_test]: assert index: 3.1813199520111084 (test_e2e.py:64)
[2021-12-13 06:21:44 - INFO - ci_test]: assert load: 2.23065185546875 (test_e2e.py:71)
[2021-12-13 06:21:44 - INFO - ci_test]: assert search: 0.3027935028076172 (test_e2e.py:78)
[2021-12-13 06:21:44 - INFO - ci_test]: assert query result 3: 0.19698381423950195 (test_e2e.py:85)
PASSED
```

### Steps To Reproduce

```markdown
# reproduce on local k8s env
cd `tests/python_client/chaos`
modify milvus tag in `cluster-values.yaml` to `master-20211213-4992c87`
run command `bash chaos_test.sh datacoord`

# run GitHub action
https://github.com/milvus-io/milvus/actions/workflows/pod-kill-chaos-test.yaml
```

### Anything else?

This issue happened in GitHub action but was not reproduced in local k8s env

You can check https://github.com/zhuwenxing/milvus/runs/4502446415?check_suite_focus=true for more details
logs:
chaos-test.zip](https://github.com/milvus-io/milvus/files/7701866/chaos-test.zip)

**Comment by yanliang567** [comment]
@sunby could you please take a look at this issue?

**Comment by zhuwenxing** [comment]
This issue happened in Github action stably, so set it as urgent
However, it never reproduced in k8s local env.
case: https://github.com/milvus-io/milvus/runs/4610414473?check_suite_focus=true
log: https://github.com/milvus-io/milvus/suites/4739477430/artifacts/130892574

**Comment by zhuwenxing** [comment]
rootcoord pod kill chaos test failed with same issue!
```
2021-12-23 18:52:55 - ERROR - pymilvus.client.grpc_handler]: Error: <BaseException: (code=1, message=, context deadline exceeded)> (grpc_handler.py:69)
[2021-12-23 18:52:55 - ERROR - ci_test]: Traceback (most recent call last):
  File "/home/runner/work/milvus/milvus/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
    res = func(*args, **kwargs)
  File "/home/runner/work/milvus/milvus/tests/python_client/utils/api_request.py", line 56, in api_request
    return func(*arg, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 453, in load
    conn.load_collection(self._name, timeout=timeout, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/stub.py", line 58, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/stub.py", line 42, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/stub.py", line 322, in load_collection
    return handler.load_collection("", collection_name=collection_name, timeout=timeout, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 835, in load_collection
    raise BaseException(response.error_code, response.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=, context deadline exceeded)>
```
https://github.com/milvus-io/milvus/runs/4620968352?check_suite_focus=true

**Comment by sunby** [comment]
@czs007 After datacoord restarted, querycoord tried to connect to the dead datacoord with old client instance and timeout. So the load collection task will never success.

**Comment by sunby** [comment]
/assign @zhuwenxing 
Fixed. Please verify it.

**Comment by zhuwenxing** [comment]
Verified and passed in version `master-20211225-8c5260c`
