### ISSUE TITLE
[Bug]: The maximum field's number should be limited to 256 rather than 64

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#13321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20211213-835e098
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-2.0.0rc9.dev23
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Create a collection with 254 int fields, 1 primary int field, 1 float vector field.
```
    @pytest.mark.tags(CaseLabel.L2)
    def test_create_collection_maximum_fields(self):
        """
        target: test create collection with maximum fields
        method: create collection with maximum field number
        expected: no exception
        """
        self._connect()
        c_name = cf.gen_unique_str(prefix)
        int_fields = []
        limit_num = ct.max_field_num - 2
        for i in range(limit_num):
            field_name = cf.gen_unique_str("field_name")
            field = cf.gen_int64_field(name=field_name)
            int_fields.append(field)
        int_fields.append(cf.gen_float_vec_field())
        int_fields.append(cf.gen_int64_field(is_primary=True))
        schema = cf.gen_collection_schema(fields=int_fields)
        self.collection_wrap.init_collection(c_name, schema=schema, check_task=CheckTasks.check_collection_property,
                                             check_items={exp_name: c_name, exp_schema: schema})
```
Exception:
```
[2021-12-14 10:36:03 - ERROR - ci_test]: Traceback (most recent call last):
  File "/home/zong/zong/projects/milvus/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
    res = func(*args, **kwargs)
  File "/home/zong/zong/projects/milvus/tests/python_client/utils/api_request.py", line 56, in api_request
    return func(*arg, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 140, in __init__
    conn.create_collection(self._name, fields=schema.to_dict(), shards_num=self._shards_num)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 58, in handler
    raise e
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 42, in handler
    return func(self, *args, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 226, in create_collection
    return handler.create_collection(collection_name, fields, shards_num=shards_num, timeout=timeout, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler
    raise e
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    return func(self, *args, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 354, in create_collection
    raise BaseException(status.error_code, status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=maximum field's number should be limited to 64)>
 (api_request.py:35)
[2021-12-14 10:36:03 - ERROR - ci_test]: (api_response) : <BaseException: (code=1, message=maximum field's number should be limited to 64)> (api_request.py:36)
```

**Comment by DragonDriver** [comment]
> /assign @yhmo could you please take a lookd

I'll fix this soon.
/unassign @yhmo 
/assign

**Comment by DragonDriver** [comment]
It seems that we didn't configure it in helm. So proxy read a default value `64`. Could you help to check this? @LoveEachDay

**Comment by LoveEachDay** [comment]
Yes, the default value of `maxFieldNum` is 64 in helm chart.
We can change the default value of `maxFieldNum` from 64 to 256 if needed.

**Comment by DragonDriver** [comment]
> Yes, the default value of `maxFieldNum` is 64 in helm chart. We can change the default value of `maxFieldNum` from 64 to 256 if needed.

/assign @ThreadDao 
How do you think about it?

**Comment by DragonDriver** [comment]
@LoveEachDay has already changed the default value of `maxFieldNum` in helm chart. @ThreadDao

**Comment by yanliang567** [comment]
@haorenfsa I think it requires an update for Operator as well?
