### ISSUE TITLE
[Bug]:Test case" test_search_after_different_index_with_params"fail

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#13673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):2.0.0rc9.dev22
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

TestCollectionSearch.test_search_after_different_index_with_params
```
self = <test_search_20.TestCollectionSearch object at 0x7fe55161f0b8>, dim = 128
[2021-12-17T13:04:15.226Z] index = 'RHNSW_PQ', params = {'M': 48, 'PQM': 64, 'efConstruction': 500}
[2021-12-17T13:04:15.226Z] auto_id = True, _async = True
[2021-12-17T13:04:15.226Z] 
[2021-12-17T13:04:15.226Z]     @pytest.mark.tags(CaseLabel.L1)
[2021-12-17T13:04:15.226Z]     @pytest.mark.parametrize("index, params",
[2021-12-17T13:04:15.226Z]                              zip(ct.all_index_types[:9],
[2021-12-17T13:04:15.226Z]                                  ct.default_index_params[:9]))
[2021-12-17T13:04:15.226Z]     def test_search_after_different_index_with_params(self, dim, index, params, auto_id, _async):
[2021-12-17T13:04:15.226Z]         """
[2021-12-17T13:04:15.226Z]         target: test search after different index
[2021-12-17T13:04:15.226Z]         method: test search after different index and corresponding search params
[2021-12-17T13:04:15.226Z]         expected: search successfully with limit(topK)
[2021-12-17T13:04:15.226Z]         """
[2021-12-17T13:04:15.226Z]         # 1. initialize with data
[2021-12-17T13:04:15.226Z]         collection_w, _, _, insert_ids, time_stamp = self.init_collection_general(prefix, True, 5000,
[2021-12-17T13:04:15.226Z]                                                                                   partition_num=1,
[2021-12-17T13:04:15.226Z]                                                                                   auto_id=auto_id,
[2021-12-17T13:04:15.226Z]                                                                                   dim=dim, is_index=True)[0:5]
[2021-12-17T13:04:15.226Z]         # 2. create index and load
[2021-12-17T13:04:15.226Z]         if params.get("m"):
[2021-12-17T13:04:15.226Z]             if (dim % params["m"]) != 0:
[2021-12-17T13:04:15.226Z]                 params["m"] = dim // 4
[2021-12-17T13:04:15.226Z]         if params.get("PQM"):
[2021-12-17T13:04:15.226Z]             if (dim % params["PQM"]) != 0:
[2021-12-17T13:04:15.226Z]                 params["PQM"] = dim // 4
[2021-12-17T13:04:15.226Z]         default_index = {"index_type": index, "params": params, "metric_type": "L2"}
[2021-12-17T13:04:15.226Z] >       collection_w.create_index("float_vector", default_index)
[2021-12-17T13:04:15.226Z] 
[2021-12-17T13:04:15.226Z] testcases/test_search_20.py:1320: 
[2021-12-17T13:04:15.226Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[2021-12-17T13:04:15.226Z] base/collection_wrapper.py:187: in create_index
[2021-12-17T13:04:15.226Z]     field_name=field_name, index_params=index_params, **kwargs).run()
[2021-12-17T13:04:15.226Z] check/func_check.py:31: in run
[2021-12-17T13:04:15.226Z]     result = self.assert_succ(self.succ, True)
[2021-12-17T13:04:15.226Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[2021-12-17T13:04:15.226Z] 
[2021-12-17T13:04:15.226Z] actual = False, expect = True
[2021-12-17T13:04:15.226Z] 
[2021-12-17T13:04:15.226Z]     @staticmethod
[2021-12-17T13:04:15.226Z]     def assert_succ(actual, expect):
[2021-12-17T13:04:15.226Z] >       assert actual is expect
[2021-12-17T13:04:15.226Z] E       AssertionError
[2021-12-17T13:04:15.226Z] 
```

### Steps To Reproduce

```markdown
pipeline:
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-13665/2/pipeline
Logs:
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-13665/2/artifacts
```

**Comment by yanliang567** [comment]
@jingkl is it an occasional issue? which index type or index params would fail this test?
/assign @jingkl 
/unassign

**Comment by binbinlv** [comment]
This cases failed for  Exception: "<BaseException: (code=1, message=CreateIndex Timeout)" which occurs in one of a CI tests:

Milvus Logs: [standalone, artifacts-milvus-standalone-PR-13665-1-pymilvus-e2e-logs.tar.gz && artifacts-milvus-standalone-PR-13665-2-pymilvus-e2e-logs.tar.gz]
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-13665/2/artifacts/

Test logs:
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-13665/2/pipeline

And some clues from the prospective of tests:
(1) collection name (failed case):  search_collection_e33XByeV
(2) failed test case: test_search_after_different_index_with_params
(3) failed index and its params:
index_type': 'RHNSW_PQ', 'params': {'M': 48, 'efConstruction': 500, 'PQM': 64}, 'metric_type': 'L2'}]
(4) failed timeline:
```

[2021-12-17T13:04:15.227Z] [2021-12-17 13:03:22 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['float_vector', {'index_type': 'RHNSW_PQ', 'params': {'M': 48, 'efConstruction': 500, 'PQM': 64}, 'metric_type': 'L2'}], kwargs: {'timeout': 40} (api_request.py:55)
[2021-12-17T13:04:15.227Z] [2021-12-17 13:04:02 - ERROR - pymilvus.client.grpc_handler]: Error: <BaseException: (code=1, message=CreateIndex Timeout)> (grpc_handler.py:69)
[2021-12-17T13:04:15.227Z] [2021-12-17 13:04:02 - ERROR - pymilvus.client.grpc_handler]: Error: <BaseException: (code=1, message=CreateIndex Timeout)> (grpc_handler.py:69)
[2021-12-17T13:04:15.227Z] [2021-12-17 13:04:02 - ERROR - ci_test]: Traceback (most recent call last):
[2021-12-17T13:04:15.227Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
[2021-12-17T13:04:15.227Z]     res = func(*args, **kwargs)
[2021-12-17T13:04:15.227Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 56, in api_request
[2021-12-17T13:04:15.227Z]     return func(*arg, **kwargs)
[2021-12-17T13:04:15.227Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 1044, in create_index
[2021-12-17T13:04:15.227Z]     timeout=timeout, **kwargs)
[2021-12-17T13:04:15.227Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 58, in handler
[2021-12-17T13:04:15.227Z]     raise e
[2021-12-17T13:04:15.227Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 42, in handler
[2021-12-17T13:04:15.227Z]     return func(self, *args, **kwargs)
[2021-12-17T13:04:15.227Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 810, in create_index
[2021-12-17T13:04:15.227Z]     return handler.create_index(collection_name, field_name, params, timeout, **kwargs)
[2021-12-17T13:04:15.227Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler
[2021-12-17T13:04:15.227Z]     raise e
[2021-12-17T13:04:15.227Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
[2021-12-17T13:04:15.227Z]     return func(self, *args, **kwargs)
[2021-12-17T13:04:15.227Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 771, in create_index
[2021-12-17T13:04:15.227Z]     field_name=field_name, timeout=timeout)
[2021-12-17T13:04:15.227Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler
[2021-12-17T13:04:15.227Z]     raise e
[2021-12-17T13:04:15.227Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
[2021-12-17T13:04:15.227Z]     return func(self, *args, **kwargs)
[2021-12-17T13:04:15.227Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 827, in wait_for_creating_index
[2021-12-17T13:04:15.227Z]     raise BaseException(1, "CreateIndex Timeout")
[2021-12-17T13:04:15.227Z] pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=CreateIndex Timeout)>
[2021-12-17T13:04:15.227Z]  (api_request.py:35)
[2021-12-17T13:04:15.227Z] [2021-12-17 13:04:02 - ERROR - ci_test]: (api_response) : <BaseException: (code=1, message=CreateIndex Timeout)> (api_request.py:36)
```

**Comment by binbinlv** [comment]
And I think it is similar with issue #9623 
 
 @xiaocai2333 
 
 Could you help to check whether it is similar with #9623? Thanks very much.

**Comment by bigsheeper** [comment]
I'm working on it

**Comment by xiaocai2333** [comment]
This is exactly the same problem as #9623 .
