### ISSUE TITLE
[Bug]: [chaos][querynode]Search hangs after deleting querynode pod kill chaos

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#13758]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20211219-1dcd06c
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.0.0rc9.dev22
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

after deleting chaos, running `hello_milvus.py`, search hangs

```

Start time: 2021-12-20 14:13:49

List collections...
['Checker__zbxmJA4S', 'Checker__1zW37HQP', 'Checker__i2FAEVKB', 'Checker__RPN3bvKB', 'Checker__2g1hoVfW', 'Checker__knsKbjpf', 'CreateChecker__JO8P6kbJ', 'hello_milvus']

Create collection...

List collections...
['Checker__2g1hoVfW', 'Checker__zbxmJA4S', 'Checker__1zW37HQP', 'Checker__i2FAEVKB', 'hello_milvus', 'Checker__knsKbjpf', 'CreateChecker__JO8P6kbJ', 'Checker__RPN3bvKB']

Insert 3000 vectors cost 0.5835340023040771 seconds

Get collection entities...
6000

Get collection entities cost 3.1618361473083496 seconds

Create index...

Create index cost 2.710383892059326 seconds

load collection...

load collection cost 0.03207588195800781 seconds

Search...
^CTraceback (most recent call last):
  File "scripts/hello_milvus.py", line 117, in <module>
    hello_milvus(args.host)
  File "scripts/hello_milvus.py", line 84, in hello_milvus
    res = collection.search(
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 687, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/stub.py", line 42, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/stub.py", line 1047, in search
    return handler.search(collection_name, data, anns_field, param, limit, expression,
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 104, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 643, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 593, in _execute_search_requests
    response = ft.result()
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/grpc/_channel.py", line 733, in result
    timed_out = _common.wait(self._state.condition.wait,
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/grpc/_common.py", line 141, in wait
    _wait_once(wait_fn, MAXIMUM_WAIT_TIMEOUT, spin_cb)
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/grpc/_common.py", line 106, in _wait_once
    wait_fn(timeout=timeout)
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
```

### Expected Behavior

all work well

### Steps To Reproduce

```markdown
cd `tests/python_client/chaos`
change Milvus tag in cluster-values.yaml

run script `bash chaos_test.sh querynode`
```

### Anything else?

log:
[test-querynode-pod-kill-12-20-14-20-00.zip](https://github.com/milvus-io/milvus/files/7743014/test-querynode-pod-kill-12-20-14-20-00.zip)

**Comment by zhuwenxing** [comment]
@xige-16  Please take a look!

**Comment by xige-16** [comment]
after querynode down, only a dmChannel was watched by querynode. 
dup to #12190
```
[2021/12/20 06:12:28.206 +00:00] [DEBUG] [task.go:1255] ["start do watchDmChannelTask"] [dmChannels="[by-dev-rootcoord-dml_3_429910985150562305v1]"] ["loaded nodeID"=36] [taskID=429910974021501025]
```
