### ISSUE TITLE
[Bug]: Test case" test_insert_multi_times"fail

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#13764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):2.0.0rc9 dev22
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

test error:
```
[2021-12-20 06:44:33 - ERROR - pymilvus.client.grpc_handler]: Error: <BaseException: (code=1, message=getSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error)> (grpc_handler.py:69)
[2021-12-20T06:44:45.491Z] [2021-12-20 06:44:33 - ERROR - ci_test]: Traceback (most recent call last):
[2021-12-20T06:44:45.491Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
[2021-12-20T06:44:45.491Z]     res = func(*args, **kwargs)
[2021-12-20T06:44:45.491Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 56, in api_request
[2021-12-20T06:44:45.491Z]     return func(*arg, **kwargs)
[2021-12-20T06:44:45.491Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 537, in insert
[2021-12-20T06:44:45.491Z]     partition_name=partition_name, timeout=timeout, **kwargs)
[2021-12-20T06:44:45.491Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 58, in handler
[2021-12-20T06:44:45.491Z]     raise e
[2021-12-20T06:44:45.491Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 42, in handler
[2021-12-20T06:44:45.491Z]     return func(self, *args, **kwargs)
[2021-12-20T06:44:45.491Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 906, in insert
[2021-12-20T06:44:45.491Z]     return handler.bulk_insert(collection_name, entities, partition_name, timeout, **kwargs)
[2021-12-20T06:44:45.491Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler
[2021-12-20T06:44:45.491Z]     raise e
[2021-12-20T06:44:45.491Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
[2021-12-20T06:44:45.491Z]     return func(self, *args, **kwargs)
[2021-12-20T06:44:45.491Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 521, in bulk_insert
[2021-12-20T06:44:45.491Z]     raise err
[2021-12-20T06:44:45.491Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 517, in bulk_insert
[2021-12-20T06:44:45.491Z]     raise BaseException(response.status.error_code, response.status.reason)
[2021-12-20T06:44:45.491Z] pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=getSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error)>
[2021-12-20T06:44:45.491Z]  (api_request.py:35)
[2021-12-20T06:44:45.491Z] [2021-12-20 06:44:33 - ERROR - ci_test]: (api_response) : <BaseException: (code=1, message=getSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error)> (api_request.py:36)
```
test case:
```
[2021-12-20T06:44:45.487Z] [gw0] linux -- Python 3.6.8 /usr/local/bin/python3[gw0] linux -- Python 3.6.8 /usr/local/bin/python3
[2021-12-20T06:44:45.487Z] 
[2021-12-20T06:44:45.487Z] self = <test_insert_20.TestInsertOperation object at 0x7f2cef528fd0>, dim = 4096
[2021-12-20T06:44:45.487Z] 
[2021-12-20T06:44:45.487Z]     @pytest.mark.tags(CaseLabel.L1)
[2021-12-20T06:44:45.487Z]     def test_insert_multi_times(self, dim):
[2021-12-20T06:44:45.487Z]         """
[2021-12-20T06:44:45.487Z]         target: test insert multi times
[2021-12-20T06:44:45.487Z]         method: insert data multi times
[2021-12-20T06:44:45.487Z]         expected: verify num entities
[2021-12-20T06:44:45.487Z]         """
[2021-12-20T06:44:45.487Z]         step = 120
[2021-12-20T06:44:45.487Z]         nb = 12000
[2021-12-20T06:44:45.487Z]         collection_w = self.init_collection_general(prefix, dim=dim)[0]
[2021-12-20T06:44:45.487Z]         for _ in range(nb // step):
[2021-12-20T06:44:45.487Z]             df = cf.gen_default_dataframe_data(step, dim)
[2021-12-20T06:44:45.487Z] >           mutation_res, _ = collection_w.insert(data=df)
[2021-12-20T06:44:45.487Z] 
[2021-12-20T06:44:45.487Z] testcases/test_insert_20.py:694: 
[2021-12-20T06:44:45.487Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[2021-12-20T06:44:45.487Z] base/collection_wrapper.py:105: in insert
[2021-12-20T06:44:45.487Z]     **kwargs).run()
[2021-12-20T06:44:45.487Z] check/func_check.py:31: in run
[2021-12-20T06:44:45.487Z]     result = self.assert_succ(self.succ, True)
[2021-12-20T06:44:45.487Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[2021-12-20T06:44:45.487Z] 
[2021-12-20T06:44:45.487Z] actual = False, expect = True
[2021-12-20T06:44:45.487Z] 
[2021-12-20T06:44:45.487Z]     @staticmethod
[2021-12-20T06:44:45.487Z]     def assert_succ(actual, expect):
[2021-12-20T06:44:45.487Z] >       assert actual is expect
[2021-12-20T06:44:45.487Z] E       AssertionError
[2021-12-20T06:44:45.487Z] 
[2021-12-20T06:44:45.487Z] check/func_check.py:73: AssertionError
```

### Steps To Reproduce
test pipeline:
https://ci.milvus.io:18080/jenkins/blue/rest/organizations/jenkins/pipelines/milvus-ha-ci/branches/PR-13665/runs/3/log/?start=0
Milvus Logs: [standalone, artifacts-milvus-standalone-PR-13665-3-pymilvus-e2e-logs.tar.gz ]
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-13665/3/artifacts
colletion name:collection_Ue3BHStj

**Comment by yanliang567** [comment]
@congqixia could you please help on this issue?
/assign @congqixia 
/unassign
