### ISSUE TITLE
[Bug]: [standalone] Milvus is crashed with panic during nightly 

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#13925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: a275417
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.0.0rc9.dev24 
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Milvus is crashed with panic:
```
panic: Failed to create consumer , error = All attempts results:

attempt #1:Topic is empty: InvalidConfiguration

attempt #2:Topic is empty: InvalidConfiguration

attempt #3:Topic is empty: InvalidConfiguration

attempt #4:Topic is empty: InvalidConfiguration

attempt #5:Topic is empty: InvalidConfiguration

attempt #6:Topic is empty: InvalidConfiguration

attempt #7:Topic is empty: InvalidConfiguration

attempt #8:Topic is empty: InvalidConfiguration

attempt #9:Topic is empty: InvalidConfiguration

attempt #10:Topic is empty: InvalidConfiguration

attempt #11:Topic is empty: InvalidConfiguration

attempt #12:Topic is empty: InvalidConfiguration

attempt #13:Topic is empty: InvalidConfiguration

attempt #14:Topic is empty: InvalidConfiguration

attempt #15:Topic is empty: InvalidConfiguration

attempt #16:Topic is empty: InvalidConfiguration

attempt #17:Topic is empty: InvalidConfiguration

attempt #18:Topic is empty: InvalidConfiguration

attempt #19:Topic is empty: InvalidConfiguration

attempt #20:Topic is empty: InvalidConfiguration


goroutine 818 [running]:

github.com/milvus-io/milvus/internal/msgstream.(*MqTtMsgStream).AsConsumerWithPosition(0xc0019246c0, 0xc0058e1810, 0x1, 0x1, 0xc003028740, 0x3a, 0x1)

        /go/src/github.com/milvus-io/milvus/internal/msgstream/mq_msgstream.go:733 +0x2a7

github.com/milvus-io/milvus/internal/msgstream.(*MqTtMsgStream).AsConsumer(0xc0019246c0, 0xc0058e1810, 0x1, 0x1, 0xc003028740, 0x3a)

        /go/src/github.com/milvus-io/milvus/internal/msgstream/mq_msgstream.go:702 +0x66

github.com/milvus-io/milvus/internal/querynode.(*queryNodeFlowGraph).seekQueryNodeFlowGraph(0xc000599bd0, 0xc004c9a120, 0xc00100c2a0, 0x2c)

        /go/src/github.com/milvus-io/milvus/internal/querynode/flow_graph_query_node.go:219 +0xac

github.com/milvus-io/milvus/internal/querynode.(*watchDmChannelsTask).Execute(0xc004f41500, 0x320f820, 0xc0001d33c0, 0x0, 0x0)

        /go/src/github.com/milvus-io/milvus/internal/querynode/task.go:431 +0x24eb

github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).processTask(0xc0001d3400, 0x3222020, 0xc004f41500, 0x3220580, 0xc00011e410)

        /go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:61 +0x173

github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).taskLoop(0xc0001d3400)

        /go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:78 +0x191

created by github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).Start

        /go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:86 +0x5c
```

### Expected Behavior

No crash for milvus

### Steps To Reproduce

Run nightly:

1. Milvus Logs: [artifacts-milvus-standalone-master-273-pymilvus-e2e-logs.tar.gz]
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/273/artifacts/

2. The following log is corresponding to the timeline started to be failed:
"jenkins.var.log.containers.ms-273-milvus-standalone-6dc846854b-kml5m_milvus-ci_standalone-3e2c55088c832226a53de98704bd5eb953def65da4a7e20051ff43fe30dd8802.log"

3. Test Logs:
https://ci.milvus.io:18080/jenkins/blue/rest/organizations/jenkins/pipelines/milvus-nightly-ci/branches/master/runs/273/nodes/106/steps/114/log/?start=0

4. Timeline started to be failed:
```
[2021-12-21T15:22:28.044Z] testcases/test_search_20.py::TestSearchBase::test_search_ip_flat[get_simple_index5-10-1100] FAILED
```

5 Other clues:
```
[2021/12/21 15:22:43.694 +00:00] [WARN] [rocksmq_impl.go:572] ["rocksmq produce too slowly"] [topic=by-dev-datacoord-timetick-channel] ["get lock elapse"=196] ["produce elapse"=202]

[2021/12/21 15:22:45.743 +00:00] [WARN] [flow_graph_dd_node.go:131] ["filter invalid InsertMsg, collection mis-match"] ["Get collID"=429942202740244481] ["Expected collID"=429942061064781825]
```

**Comment by binbinlv** [comment]
@congqixia  Could you help to check it first? Thanks.

**Comment by congqixia** [comment]
Panicking was cause by calling `AsConsumer` with empty channel name. Still looking for the root cause

**Comment by binbinlv** [comment]
Same panic occurs again, set this as urgent.

Milvus log: standalone [artifacts-milvus-standalone-master-275-pymilvus-e2e-logs.tar.gz]

https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/275/artifacts

Timeline started to be failed:
```
[2021-12-23T15:43:02.895Z] testcases/test_search_20.py::TestCollectionSearch::test_search_binary_tanimoto_flat_index[2-128-True-False-BIN_IVF_FLAT]
```

**Comment by yanliang567** [comment]
@congqixia please take a look, thx

**Comment by congqixia** [comment]
@binbinlv @yanliang567 #14169 add some check before panicking situation. And added some log to find the root cause. need to verify in the next run.

**Comment by binbinlv** [comment]
> 

OK，will try to reproduce it.

**Comment by yanliang567** [comment]
not reproduce last night.

**Comment by binbinlv** [comment]
Have not been reproduced for continuously third days.

**Comment by binbinlv** [comment]
Have not been reproduced for long time, so close it first, will reopen it if it occurs later.
