### ISSUE TITLE
[Bug]: [benchmark][cluster] Milvus is not healthy, connection timeout

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#14005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20211222-1e658f2
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc9.dev22
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

client pod: benchmark-tag-dg67m-1802803593

proxy log:
```
[2021/12/22 11:38:07.359 +00:00] [DEBUG] [impl.go:3371] [RegisterLink] [role=proxy] ["state code of proxy"=Initializing]
[2021/12/22 11:38:08.362 +00:00] [DEBUG] [impl.go:3371] [RegisterLink] [role=proxy] ["state code of proxy"=Initializing]
[2021/12/22 11:38:09.364 +00:00] [DEBUG] [impl.go:3371] [RegisterLink] [role=proxy] ["state code of proxy"=Initializing]
[2021/12/22 11:38:10.009 +00:00] [DEBUG] [client.go:81] ["DataCoordClient, not existed in msess "] [key=datacoord] ["len of msess"=0]
[2021/12/22 11:38:10.009 +00:00] [DEBUG] [client.go:121] ["datacoord client getAddr failed"] [error="number of datacoord is incorrect, 0"]
[2021/12/22 11:38:10.211 +00:00] [DEBUG] [client.go:81] ["DataCoordClient, not existed in msess "] [key=datacoord] ["len of msess"=0]
[2021/12/22 11:38:10.211 +00:00] [DEBUG] [client.go:121] ["datacoord client getAddr failed"] [error="number of datacoord is incorrect, 0"]
[2021/12/22 11:38:10.366 +00:00] [DEBUG] [impl.go:3371] [RegisterLink] [role=proxy] ["state code of proxy"=Initializing]
[2021/12/22 11:38:10.612 +00:00] [DEBUG] [client.go:81] ["DataCoordClient, not existed in msess "] [key=datacoord] ["len of msess"=0]
[2021/12/22 11:38:10.612 +00:00] [DEBUG] [client.go:121] ["datacoord client getAddr failed"] [error="number of datacoord is incorrect, 0"]
[2021/12/22 11:38:11.369 +00:00] [DEBUG] [impl.go:3371] [RegisterLink] [role=proxy] ["state code of proxy"=Initializing]
[2021/12/22 11:38:11.414 +00:00] [DEBUG] [client.go:81] ["DataCoordClient, not existed in msess "] [key=datacoord] ["len of msess"=0]
[2021/12/22 11:38:11.414 +00:00] [DEBUG] [client.go:121] ["datacoord client getAddr failed"] [error="number of datacoord is incorrect, 0"]
[2021/12/22 11:38:12.371 +00:00] [DEBUG] [impl.go:3371] [RegisterLink] [role=proxy] ["state code of proxy"=Initializing]
[2021/12/22 11:38:13.015 +00:00] [DEBUG] [client.go:81] ["DataCoordClient, not existed in msess "] [key=datacoord] ["len of msess"=0]
[2021/12/22 11:38:13.015 +00:00] [DEBUG] [client.go:121] ["datacoord client getAddr failed"] [error="number of datacoord is incorrect, 0"]
[2021/12/22 11:38:13.373 +00:00] [DEBUG] [impl.go:3371] [RegisterLink] [role=proxy] ["state code of proxy"=Initializing]
[2021/12/22 11:38:14.376 +00:00] [DEBUG] [impl.go:3371] [RegisterLink] [role=proxy] ["state code of proxy"=Initializing]
[2021/12/22 11:38:15.378 +00:00] [DEBUG] [impl.go:3371] [RegisterLink] [role=proxy] ["state code of proxy"=Initializing]
[2021/12/22 11:38:16.015 +00:00] [DEBUG] [client.go:161] ["datacoord client try reconnect failed"] [error="All attempts results:\nattempt #1:number of datacoord is incorrect, 0\nattempt #2:number of datacoord is incorrect, 0\nattempt #3:number of datacoord is incorrect, 0\nattempt #4:number of datacoord is incorrect, 0\nattempt #5:number of datacoord is incorrect, 0\n"]
[2021/12/22 11:38:16.015 +00:00] [WARN] [client.go:214] ["datacoord ClientBase ReCall grpc first call get error "] [error="err: All attempts results:\nattempt #1:number of datacoord is incorrect, 0\nattempt #2:number of datacoord is incorrect, 0\nattempt #3:number of datacoord is incorrect, 0\nattempt #4:number of datacoord is incorrect, 0\nattempt #5:number of datacoord is incorrect, 0\n\n, /usr/local/go/src/runtime/extern.go:216 runtime.Callers\n/go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:25 github.com/milvus-io/milvus/internal/util/trace.StackTraceMsg\n/go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:43 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:213 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall\n/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:108 github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).GetComponentStates\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:50 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates.func1\n/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:34 github.com/milvus-io/milvus/internal/util/retry.Do\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:74 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:89 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentHealthy\n/go/src/github.com/milvus-io/milvus/internal/proxy/proxy.go:149 github.com/milvus-io/milvus/internal/proxy.(*Proxy).Init\n"]
[2021/12/22 11:38:16.017 +00:00] [DEBUG] [client.go:81] ["DataCoordClient, not existed in msess "] [key=datacoord] ["len of msess"=0]
[2021/12/22 11:38:16.017 +00:00] [DEBUG] [client.go:121] ["datacoord client getAddr failed"] [error="number of datacoord is incorrect, 0"]
[2021/12/22 11:38:16.218 +00:00] [DEBUG] [client.go:81] ["DataCoordClient, not existed in msess "] [key=datacoord] ["len of msess"=0]
[2021/12/22 11:38:16.218 +00:00] [DEBUG] [client.go:121] ["datacoord client getAddr failed"] [error="number of datacoord is incorrect, 0"]
[2021/12/22 11:38:16.619 +00:00] [DEBUG] [client.go:81] ["DataCoordClient, not existed in msess "] [key=datacoord] ["len of msess"=0]
[2021/12/22 11:38:16.619 +00:00] [DEBUG] [client.go:121] ["datacoord client getAddr failed"] [error="number of datacoord is incorrect, 0"]
[2021/12/22 11:38:17.421 +00:00] [DEBUG] [client.go:81] ["DataCoordClient, not existed in msess "] [key=datacoord] ["len of msess"=0]
[2021/12/22 11:38:17.421 +00:00] [DEBUG] [client.go:121] ["datacoord client getAddr failed"] [error="number of datacoord is incorrect, 0"]
[2021/12/22 11:38:19.022 +00:00] [DEBUG] [client.go:81] ["DataCoordClient, not existed in msess "] [key=datacoord] ["len of msess"=0]
[2021/12/22 11:38:19.022 +00:00] [DEBUG] [client.go:121] ["datacoord client getAddr failed"] [error="number of datacoord is incorrect, 0"]
```

client logs:
```
[2021-12-22 11:34:15,908] [   DEBUG] - Get runner (milvus_benchmark.main:81)
[2021-12-22 11:35:16,059] [   ERROR] - server is not healthy, please try again later (milvus_benchmark.client:81)
[2021-12-22 11:35:16,060] [   ERROR] - Milvus connect failed: 0 times (milvus_benchmark.client:82)
[2021-12-22 11:36:46,219] [   ERROR] - server is not healthy, please try again later (milvus_benchmark.client:81)
[2021-12-22 11:36:46,220] [   ERROR] - Milvus connect failed: 1 times (milvus_benchmark.client:82)
[2021-12-22 11:38:16,380] [   ERROR] - server is not healthy, please try again later (milvus_benchmark.client:81)
[2021-12-22 11:38:16,382] [   ERROR] - Milvus connect failed: 2 times (milvus_benchmark.client:82)
[2021-12-22 11:39:46,539] [   ERROR] - server is not healthy, please try again later (milvus_benchmark.client:81)
[2021-12-22 11:39:46,540] [   ERROR] - Milvus connect failed: 3 times (milvus_benchmark.client:82)
[2021-12-22 11:40:16,542] [   ERROR] - Server connect timeout (milvus_benchmark.main:117)
[2021-12-22 11:40:16,544] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 82, in run_suite
    runner = get_runner(run_type, env, metric)
  File "/src/milvus_benchmark/runners/__init__.py", line 13, in get_runner
    "insert_performance": InsertRunner(env, metric),
  File "/src/milvus_benchmark/runners/insert.py", line 17, in __init__
    super(InsertRunner, self).__init__(env, metric)
  File "/src/milvus_benchmark/runners/base.py", line 25, in __init__
    self._milvus = MilvusClient(host=self._env.hostname)
  File "/src/milvus_benchmark/client.py", line 87, in __init__
    raise Exception("Server connect timeout")
Exception: Server connect timeout
 (milvus_benchmark.main:118)
[2021-12-22 11:40:16,545] [   DEBUG] - {'_version': '0.1', '_type': 'metric', 'run_id': 1640172855, 'mode': 'local', 'server': <milvus_benchmark.metrics.models.server.Server object at 0x7efc10b7b128>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware object at 0x7efc10b7b208>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7efc10b7b198>, 'status': 'RUN_FAILED', 'err_message': '', 'collection': {}, 'index': {}, 'search': {}, 'run_params': {}, 'metrics': {'type': '', 'value': None}, 'datetime': '2021-12-22 11:34:15.907358'} (milvus_benchmark.metric.api:29)
```

### Expected Behavior

argo task: benchmark-tag-dg67m

test yaml:
client-configmap:client-random-locust-search-84h-1b
server-configmap:server-cluster-8c64m-datanode2-indexnode4-querynode6

server:
```
NAME                                                              READY   STATUS      RESTARTS   AGE     IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-tag-dg67m-1-etcd-0                                      1/1     Running     0          12m     10.97.16.57    qa-node013.zilliz.local   <none>           <none>
benchmark-tag-dg67m-1-etcd-1                                      1/1     Running     0          12m     10.97.17.85    qa-node014.zilliz.local   <none>           <none>
benchmark-tag-dg67m-1-etcd-2                                      1/1     Running     0          12m     10.97.16.56    qa-node013.zilliz.local   <none>           <none>
benchmark-tag-dg67m-1-milvus-datacoord-576c569f74-pfs7z           1/1     Running     0          12m     10.97.14.199   qa-node011.zilliz.local   <none>           <none>
benchmark-tag-dg67m-1-milvus-datanode-5bbbc7f485-74tkt            1/1     Running     0          12m     10.97.16.44    qa-node013.zilliz.local   <none>           <none>
benchmark-tag-dg67m-1-milvus-datanode-5bbbc7f485-m9zpw            1/1     Running     0          12m     10.97.16.46    qa-node013.zilliz.local   <none>           <none>
benchmark-tag-dg67m-1-milvus-indexcoord-854fd7ff6f-wpcvd          1/1     Running     0          12m     10.97.16.41    qa-node013.zilliz.local   <none>           <none>
benchmark-tag-dg67m-1-milvus-indexnode-7747656c78-4ks6b           1/1     Running     0          12m     10.97.19.96    qa-node016.zilliz.local   <none>           <none>
benchmark-tag-dg67m-1-milvus-indexnode-7747656c78-k89gt           1/1     Running     0          12m     10.97.12.49    qa-node015.zilliz.local   <none>           <none>
benchmark-tag-dg67m-1-milvus-indexnode-7747656c78-t5hx4           1/1     Running     0          12m     10.97.16.45    qa-node013.zilliz.local   <none>           <none>
benchmark-tag-dg67m-1-milvus-indexnode-7747656c78-wvw8v           1/1     Running     0          12m     10.97.16.43    qa-node013.zilliz.local   <none>           <none>
benchmark-tag-dg67m-1-milvus-proxy-5c5d886976-bt66x               1/1     Running     0          12m     10.97.19.97    qa-node016.zilliz.local   <none>           <none>
benchmark-tag-dg67m-1-milvus-querycoord-84b99d6778-5lzn8          1/1     Running     0          12m     10.97.6.23     qa-node004.zilliz.local   <none>           <none>
benchmark-tag-dg67m-1-milvus-querynode-58fdd94b56-8r4pp           1/1     Running     0          12m     10.97.11.240   qa-node009.zilliz.local   <none>           <none>
benchmark-tag-dg67m-1-milvus-querynode-58fdd94b56-qwtnp           1/1     Running     0          12m     10.97.10.116   qa-node008.zilliz.local   <none>           <none>
benchmark-tag-dg67m-1-milvus-querynode-58fdd94b56-r5fpk           1/1     Running     0          12m     10.97.14.200   qa-node011.zilliz.local   <none>           <none>
benchmark-tag-dg67m-1-milvus-querynode-58fdd94b56-tfhnr           1/1     Running     0          12m     10.97.17.84    qa-node014.zilliz.local   <none>           <none>
benchmark-tag-dg67m-1-milvus-querynode-58fdd94b56-ts87n           1/1     Running     0          12m     10.97.16.47    qa-node013.zilliz.local   <none>           <none>
benchmark-tag-dg67m-1-milvus-querynode-58fdd94b56-x79lh           1/1     Running     0          12m     10.97.13.88    qa-node010.zilliz.local   <none>           <none>
benchmark-tag-dg67m-1-milvus-rootcoord-d8f7ccc4b-hfk96            1/1     Running     0          12m     10.97.16.42    qa-node013.zilliz.local   <none>           <none>
benchmark-tag-dg67m-1-minio-0                                     1/1     Running     0          12m     10.97.16.58    qa-node013.zilliz.local   <none>           <none>
benchmark-tag-dg67m-1-minio-1                                     1/1     Running     0          12m     10.97.19.99    qa-node016.zilliz.local   <none>           <none>
benchmark-tag-dg67m-1-minio-2                                     1/1     Running     0          12m     10.97.12.54    qa-node015.zilliz.local   <none>           <none>
benchmark-tag-dg67m-1-minio-3                                     1/1     Running     0          12m     10.97.12.53    qa-node015.zilliz.local   <none>           <none>
benchmark-tag-dg67m-1-pulsar-autorecovery-b97f5c486-w5xcd         1/1     Running     0          12m     10.97.11.239   qa-node009.zilliz.local   <none>           <none>
benchmark-tag-dg67m-1-pulsar-bastion-5dc95b6c44-9bbkz             1/1     Running     0          12m     10.97.4.88     qa-node002.zilliz.local   <none>           <none>
benchmark-tag-dg67m-1-pulsar-bookkeeper-0                         1/1     Running     0          12m     10.97.8.49     qa-node006.zilliz.local   <none>           <none>
benchmark-tag-dg67m-1-pulsar-bookkeeper-1                         1/1     Running     0          10m     10.97.9.166    qa-node007.zilliz.local   <none>           <none>
benchmark-tag-dg67m-1-pulsar-bookkeeper-2                         1/1     Running     0          10m     10.97.7.84     qa-node005.zilliz.local   <none>           <none>
benchmark-tag-dg67m-1-pulsar-broker-7948dc9fc7-n9hbv              1/1     Running     0          12m     10.97.4.89     qa-node002.zilliz.local   <none>           <none>
benchmark-tag-dg67m-1-pulsar-proxy-fc69fb447-96kqb                2/2     Running     0          12m     10.97.11.238   qa-node009.zilliz.local   <none>           <none>
benchmark-tag-dg67m-1-pulsar-zookeeper-0                          1/1     Running     0          12m     10.97.9.164    qa-node007.zilliz.local   <none>           <none>
benchmark-tag-dg67m-1-pulsar-zookeeper-1                          1/1     Running     0          12m     10.97.9.165    qa-node007.zilliz.local   <none>           <none>
benchmark-tag-dg67m-1-pulsar-zookeeper-2                          1/1     Running     0          11m     10.97.7.83     qa-node005.zilliz.local   <none>           <none>
benchmark-tag-dg67m-1-pulsar-zookeeper-metadata-w8gr2             0/1     Completed   0          12m     10.97.8.47     qa-node006.zilliz.local   <none>           <none>
```

**Comment by yanliang567** [comment]
the datacoord is not registered into etcd, as etcd service is not ready(high latency) at that time. 
remove from urgent as it does not repro if retry

**Comment by wangting0128** [comment]
argo task: benchmark-tag-txfbr

test yaml:
client-configmap:client-search-sift50m-ivf-flat-2048
server-configmap:server-single-16c64m

server:
```
NAME                                                             READY   STATUS      RESTARTS   AGE     IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-tag-txfbr-1-etcd-0                                     1/1     Running     0          9m27s   10.97.17.174   qa-node014.zilliz.local   <none>           <none>
benchmark-tag-txfbr-1-milvus-standalone-6bd9b559c8-djssw         1/1     Running     0          9m27s   10.97.16.139   qa-node013.zilliz.local   <none>           <none>
benchmark-tag-txfbr-1-minio-57fc9bbd8d-bntkw                     1/1     Running     0          9m27s   10.97.19.124   qa-node016.zilliz.local   <none>           <none>
```

client pod: benchmark-tag-txfbr-3378080778

client log:
```
[2021-12-23 07:22:05,648] [    INFO] - {'host': 'benchmark-tag-txfbr-1-milvus.qa-milvus.svc.cluster.local', 'port': 19530, 'deploy_mode': 'single', 'server_tag': '16c64m', 'deploy_opology': {'server': {'server_tag': '16c64m'}, 'milvus': {'deploy_mode': 'single'}}} (milvus_benchmark.main:63)
[2021-12-23 07:22:05,648] [   DEBUG] - Get runner (milvus_benchmark.main:81)
[2021-12-23 07:23:05,798] [   ERROR] - server is not healthy, please try again later (milvus_benchmark.client:81)
[2021-12-23 07:23:05,799] [   ERROR] - Milvus connect failed: 0 times (milvus_benchmark.client:82)
[2021-12-23 07:24:35,975] [   ERROR] - server is not healthy, please try again later (milvus_benchmark.client:81)
[2021-12-23 07:24:35,976] [   ERROR] - Milvus connect failed: 1 times (milvus_benchmark.client:82)
[2021-12-23 07:26:06,135] [   ERROR] - server is not healthy, please try again later (milvus_benchmark.client:81)
[2021-12-23 07:26:06,136] [   ERROR] - Milvus connect failed: 2 times (milvus_benchmark.client:82)
[2021-12-23 07:27:36,304] [   ERROR] - server is not healthy, please try again later (milvus_benchmark.client:81)
[2021-12-23 07:27:36,305] [   ERROR] - Milvus connect failed: 3 times (milvus_benchmark.client:82)
[2021-12-23 07:28:06,307] [   ERROR] - Server connect timeout (milvus_benchmark.main:117)
[2021-12-23 07:28:06,310] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 82, in run_suite
    runner = get_runner(run_type, env, metric)
  File "/src/milvus_benchmark/runners/__init__.py", line 13, in get_runner
    "insert_performance": InsertRunner(env, metric),
  File "/src/milvus_benchmark/runners/insert.py", line 17, in __init__
    super(InsertRunner, self).__init__(env, metric)
  File "/src/milvus_benchmark/runners/base.py", line 25, in __init__
    self._milvus = MilvusClient(host=self._env.hostname)
  File "/src/milvus_benchmark/client.py", line 87, in __init__
    raise Exception("Server connect timeout")
Exception: Server connect timeout
 (milvus_benchmark.main:118)
[2021-12-23 07:28:06,312] [   DEBUG] - {'_version': '0.1', '_type': 'metric', 'run_id': 1640244125, 'mode': 'local', 'server': <milvus_benchmark.metrics.models.server.Server object at 0x7f7b4c259c50>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware object at 0x7f7b4c259b70>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7f7b4c259a90>, 'status': 'RUN_FAILED', 'err_message': '', 'collection': {}, 'index': {}, 'search': {}, 'run_params': {}, 'metrics': {'type': '', 'value': None}, 'datetime': '2021-12-23 07:22:05.647913'} (milvus_benchmark.metric.api:29)
```

**Comment by yanliang567** [comment]
@LoveEachDay  could you please check the latest error above? Was it caused by the same issue?

**Comment by LoveEachDay** [comment]
From the pod log, etcd behaves normally. And DataCoord failed to start:
![image](https://user-images.githubusercontent.com/1573213/147227370-7d6b2cff-c4eb-47cb-a293-4b60249eada7.png)
So it won't register itself to etcd.
/unassign

**Comment by yanliang567** [comment]
@sunby could you please take a look at logs above

**Comment by wangting0128** [comment]
argo task: benchmark-tag-skbvc

test yaml:
client-configmap:client-random-locust-100m-ddl-r8-w2
server-configmap:server-single-32c128m

server:
```
NAME                                                             READY   STATUS      RESTARTS   AGE    IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-tag-skbvc-1-etcd-0                                     1/1     Running     0          9m5s   10.97.16.151   qa-node013.zilliz.local   <none>           <none>
benchmark-tag-skbvc-1-milvus-standalone-67bbbdc6b6-jjkjw         1/1     Running     0          9m5s   10.97.16.150   qa-node013.zilliz.local   <none>           <none>
benchmark-tag-skbvc-1-minio-c49684544-pn7tw                      1/1     Running     0          9m5s   10.97.19.130   qa-node016.zilliz.local   <none>           <none>
```

client log:
```
[2021-12-23 10:18:30,946] [   DEBUG] - Get runner (milvus_benchmark.main:81)
[2021-12-23 10:19:31,106] [   ERROR] - server is not healthy, please try again later (milvus_benchmark.client:81)
[2021-12-23 10:19:31,107] [   ERROR] - Milvus connect failed: 0 times (milvus_benchmark.client:82)
[2021-12-23 10:21:01,267] [   ERROR] - server is not healthy, please try again later (milvus_benchmark.client:81)
[2021-12-23 10:21:01,307] [   ERROR] - Milvus connect failed: 1 times (milvus_benchmark.client:82)
[2021-12-23 10:22:31,453] [   ERROR] - server is not healthy, please try again later (milvus_benchmark.client:81)
[2021-12-23 10:22:31,537] [   ERROR] - Milvus connect failed: 2 times (milvus_benchmark.client:82)
[2021-12-23 10:24:01,677] [   ERROR] - server is not healthy, please try again later (milvus_benchmark.client:81)
[2021-12-23 10:24:01,682] [   ERROR] - Milvus connect failed: 3 times (milvus_benchmark.client:82)
[2021-12-23 10:24:31,685] [   ERROR] - Server connect timeout (milvus_benchmark.main:117)
  Looking in indexes: https://test.pypi.org/simple/
  ERROR: Could not find a version that satisfies the requirement setuptools>=42 (from versions: none)
  ERROR: No matching distribution found for setuptools>=42
  ----------------------------------------
WARNING: Discarding https://test-files.pythonhosted.org/packages/df/69/e8f615e1a779e2d2d23d29d56dc55bbb1db2a828f0ef36d10bc697d63968/ujson-4.2.0.tar.gz#sha256=fffe509f556861c7343c6cba57ed05fe7bcf4b48a934a5b946ccb45428cf8883 (from https://test.pypi.org/simple/ujson/) (requires-python:>=3.6). Command errored out with exit status 1: /usr/local/bin/python /usr/local/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-w032630g/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://test.pypi.org/simple/ -- 'setuptools>=42' wheel 'setuptools_scm[toml]>=3.4' Check the logs for full command output.
[2021-12-23 10:24:31,690] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 82, in run_suite
    runner = get_runner(run_type, env, metric)
  File "/src/milvus_benchmark/runners/__init__.py", line 13, in get_runner
    "insert_performance": InsertRunner(env, metric),
  File "/src/milvus_benchmark/runners/insert.py", line 17, in __init__
    super(InsertRunner, self).__init__(env, metric)
  File "/src/milvus_benchmark/runners/base.py", line 25, in __init__
    self._milvus = MilvusClient(host=self._env.hostname)
  File "/src/milvus_benchmark/client.py", line 87, in __init__
    raise Exception("Server connect timeout")
Exception: Server connect timeout
 (milvus_benchmark.main:118)
[2021-12-23 10:24:31,692] [   DEBUG] - {'_version': '0.1', '_type': 'metric', 'run_id': 1640254710, 'mode': 'local', 'server': <milvus_benchmark.metrics.models.server.Server object at 0x7f3ff2898b70>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware object at 0x7f3ff2898be0>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7f3ff2898d30>, 'status': 'RUN_FAILED', 'err_message': '', 'collection': {}, 'index': {}, 'search': {}, 'run_params': {}, 'metrics': {'type': '', 'value': None}, 'datetime': '2021-12-23 10:18:30.946567'} (milvus_benchmark.metric.api:29)
```

**Comment by xiaofan-luan** [comment]
> From the pod log, etcd behaves normally. And DataCoord failed to start: ![image](https://user-images.githubusercontent.com/1573213/147227370-7d6b2cff-c4eb-47cb-a293-4b60249eada7.png) So it won't register itself to etcd. /unassign

From the log, it seems that the minio bucket is not cleaned thus datacoord could not start

**Comment by xiaofan-luan** [comment]
should be solved, close it for now
