### ISSUE TITLE
[Bug]: [chaos][querynode]search hangs when running `hello_milvus.py`  after deleting querynode pod kill chaos

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#14048]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20211222-5a29db6
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc9.dev24
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Running `hello_milvus.py`  timeout after deleting querynode pod kill chaos, but can't find out which step is hanged from the output log in console.

### Expected Behavior

all steps success

### Steps To Reproduce

```markdown
# reproduce on local k8s env
cd `tests/python_client/chaos`
modify milvus tag in `cluster-values.yaml` to `master-20211222-5a29db6`
run command `bash chaos_test.sh querynode`

# run GitHub action
https://github.com/milvus-io/milvus/actions/workflows/pod-kill-chaos-test.yaml
```

### Anything else?

It reproduced in Github action, but not reproduced in local k8s env.
GitHub action: https://github.com/milvus-io/milvus/runs/4610414772?check_suite_focus=true
some error message in proxy pod:
```
time="2021-12-22T18:54:15Z" level=warning msg="[Failed to lookup topic]" error=ServiceNotReady message="org.apache.pulsar.client.api.PulsarClientException: java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: test-querynode-pod-kill-pulsar-broker.chaos-testing.svc.cluster.local/10.96.12.24:6650" serviceURL="pulsar://test-querynode-pod-kill-pulsar-proxy:6650" topic="persistent://public/default/by-dev-search-0"
time="2021-12-22T18:54:15Z" level=warning msg="[Failed to lookup topic]" error=ServiceNotReady producerID=25 producer_name=test-querynode-pod-kill-pulsar-0-114 topic="persistent://public/default/by-dev-search-0"
time="2021-12-22T18:54:15Z" level=info msg="[Reconnecting to broker in  14.703118971s]" producerID=25 producer_name=test-querynode-pod-kill-pulsar-0-114 topic="persistent://public/default/by-dev-search-0"
time="2021-12-22T18:54:15Z" level=warning msg="[Failed to lookup topic]" error=ServiceNotReady message="org.apache.pulsar.client.api.PulsarClientException: java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: test-querynode-pod-kill-pulsar-broker.chaos-testing.svc.cluster.local/10.96.12.24:6650" serviceURL="pulsar://test-querynode-pod-kill-pulsar-proxy:6650" topic="persistent://public/default/by-dev-rootcoord-dml_9"
time="2021-12-22T18:54:15Z" level=warning msg="[Failed to lookup topic]" error=ServiceNotReady producerID=14 producer_name=test-querynode-pod-kill-pulsar-0-69 topic="persistent://public/default/by-dev-rootcoord-dml_9"
time="2021-12-22T18:54:15Z" level=info msg="[Reconnecting to broker in  14.358470244s]" producerID=14 producer_name=test-querynode-pod-kill-pulsar-0-69 topic="persistent://public/default/by-dev-rootcoord-dml_9"
time="2021-12-22T18:54:27Z" level=warning msg="[Failed to lookup topic]" error=ServiceNotReady message="org.apache.pulsar.client.api.PulsarClientException: java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: test-querynode-pod-kill-pulsar-broker.chaos-testing.svc.cluster.local/10.96.12.24:6650" serviceURL="pulsar://test-querynode-pod-kill-pulsar-proxy:6650" topic="persistent://public/default/by-dev-rootcoord-dml_3"
time="2021-12-22T18:54:27Z" level=warning msg="[Failed to lookup topic]" error=ServiceNotReady producerID=9 producer_name=test-querynode-pod-kill-pulsar-0-38 topic="persistent://public/default/by-dev-rootcoord-dml_3"
time="2021-12-22T18:54:27Z" level=info msg="[Reconnecting to broker in  30.282166655s]" producerID=9 producer_name=test-querynode-pod-kill-pulsar-0-38 topic="persistent://public/default/by-dev-rootcoord-dml_3"
time="2021-12-22T18:54:28Z" level=info msg="[Connecting to broker]" remote_addr="pulsar://test-querynode-pod-kill-pulsar-proxy:6650"
```

logs:
https://github.com/milvus-io/milvus/suites/4739477430/artifacts/130892583

**Comment by xige-16** [comment]
pulsar proxy log
```
18:53:39.077 [pulsar-proxy-io-2-1] WARN  org.apache.pulsar.client.impl.ConnectionPool - Failed to open connection to test-querynode-pod-kill-pulsar-broker:6650 : io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: test-querynode-pod-kill-pulsar-broker.chaos-testing.svc.cluster.local/10.96.12.24:6650
18:53:39.079 [pulsar-proxy-io-2-1] WARN  org.apache.pulsar.client.impl.ConnectionPool - Failed to open connection to test-querynode-pod-kill-pulsar-broker:6650 : io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: test-querynode-pod-kill-pulsar-broker.chaos-testing.svc.cluster.local/10.96.12.24:6650
18:53:39.087 [pulsar-proxy-io-2-1] WARN  org.apache.pulsar.client.impl.ConnectionPool - Failed to open connection to test-querynode-pod-kill-pulsar-broker:6650 : io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: test-querynode-pod-kill-pulsar-broker.chaos-testing.svc.cluster.local/10.96.12.24:6650
18:53:39.097 [pulsar-proxy-io-2-1] WARN  org.apache.pulsar.client.impl.ConnectionPool - Failed to open connection to test-querynode-pod-kill-pulsar-broker:6650 : io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: test-querynode-pod-kill-pulsar-broker.chaos-testing.svc.cluster.local/10.96.12.24:6650
```

**Comment by xige-16** [comment]
There is a problem with the pulsar broker's network
```
18:53:39.257 [pulsar-proxy-io-2-1] WARN  org.apache.pulsar.client.impl.ConnectionPool - Failed to open connection to test-querynode-pod-kill-pulsar-broker:6650
```

**Comment by xige-16** [comment]
pulsar broker exception log
```
java.util.concurrent.CompletionException: org.apache.pulsar.broker.service.BrokerServiceException$PersistenceException: org.apache.bookkeeper.mledger.ManagedLedgerException$CursorNotFoundException: ManagedCursor not found: reader-83cd9bc866
	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326) ~[?:1.8.0_302]
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:998) ~[?:1.8.0_302]
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137) ~[?:1.8.0_302]
	at org.apache.pulsar.broker.service.persistent.PersistentSubscription.delete(PersistentSubscription.java:829) ~[org.apache.pulsar-pulsar-broker-2.7.3.jar:2.7.3]
	at org.apache.pulsar.broker.service.persistent.PersistentSubscription.deleteForcefully(PersistentSubscription.java:792) ~[org.apache.pulsar-pulsar-broker-2.7.3.jar:2.7.3]
	at org.apache.pulsar.broker.admin.impl.BrokersBase.lambda$healthcheck$2(BrokersBase.java:313) ~[org.apache.pulsar-pulsar-broker-2.7.3.jar:2.7.3]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_302]
	at org.apache.pulsar.broker.admin.impl.BrokersBase.healthcheck(BrokersBase.java:310) ~[org.apache.pulsar-pulsar-broker-2.7.3.jar:2.7.3]
	at sun.reflect.GeneratedMethodAccessor117.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_302]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_302]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[org.glassfish.jersey.core-jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) ~[org.glassfish.jersey.core-jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) ~[org.glassfish.jersey.core-jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:159) ~[org.glassfish.jersey.core-jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) ~[org.glassfish.jersey.core-jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469) ~[org.glassfish.jersey.core-jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391) ~[org.glassfish.jersey.core-jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80) ~[org.glassfish.jersey.core-jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253) ~[org.glassfish.jersey.core-jersey-server-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[org.glassfish.jersey.core-jersey-common-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[org.glassfish.jersey.core-jersey-common-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[org.glassfish.jersey.core-jersey-common-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[org.glassfish.jersey.core-jersey-common-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[org.glassfish.jersey.core-jersey-common-2.31.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) ~[org.glassfish.jersey.core-jersey-common-2.31.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232) ~[org.glassfish.jersey.core-jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680) ~[org.glassfish.jersey.core-jersey-server-2.31.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394) ~[org.glassfish.jersey.containers-jersey-container-servlet-core-2.31.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346) ~[org.glassfish.jersey.containers-jersey-container-servlet-core-2.31.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366) ~[org.glassfish.jersey.containers-jersey-container-servlet-core-2.31.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319) ~[org.glassfish.jersey.containers-jersey-container-servlet-core-2.31.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205) ~[org.glassfish.jersey.containers-jersey-container-servlet-core-2.31.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) ~[org.eclipse.jetty-jetty-servlet-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626) ~[org.eclipse.jetty-jetty-servlet-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.apache.pulsar.broker.web.ResponseHandlerFilter.doFilter(ResponseHandlerFilter.java:66) ~[org.apache.pulsar-pulsar-broker-2.7.3.jar:2.7.3]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[org.eclipse.jetty-jetty-servlet-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[org.eclipse.jetty-jetty-servlet-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548) ~[org.eclipse.jetty-jetty-servlet-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[org.eclipse.jetty-jetty-server-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[org.eclipse.jetty-jetty-server-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[org.eclipse.jetty-jetty-server-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435) ~[org.eclipse.jetty-jetty-server-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[org.eclipse.jetty-jetty-server-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501) ~[org.eclipse.jetty-jetty-servlet-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[org.eclipse.jetty-jetty-server-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[org.eclipse.jetty-jetty-server-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350) ~[org.eclipse.jetty-jetty-server-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[org.eclipse.jetty-jetty-server-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234) ~[org.eclipse.jetty-jetty-server-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146) ~[org.eclipse.jetty-jetty-server-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:179) ~[org.eclipse.jetty-jetty-server-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[org.eclipse.jetty-jetty-server-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[org.eclipse.jetty-jetty-server-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388) ~[org.eclipse.jetty-jetty-server-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633) [org.eclipse.jetty-jetty-server-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380) [org.eclipse.jetty-jetty-server-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) [org.eclipse.jetty-jetty-server-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [org.eclipse.jetty-jetty-io-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [org.eclipse.jetty-jetty-io-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [org.eclipse.jetty-jetty-io-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) [org.eclipse.jetty-jetty-util-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) [org.eclipse.jetty-jetty-util-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) [org.eclipse.jetty-jetty-util-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) [org.eclipse.jetty-jetty-util-9.4.42.v20210604.jar:9.4.42.v20210604]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383) [org.eclipse.jetty-jetty-util-9.4.42.v20210604.jar:9.4.42.v20210604]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_302]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_302]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.60.Final.jar:4.1.60.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_302]
Caused by: org.apache.pulsar.broker.service.BrokerServiceException$PersistenceException: org.apache.bookkeeper.mledger.ManagedLedgerException$CursorNotFoundException: ManagedCursor not found: reader-83cd9bc866
	at org.apache.pulsar.broker.service.persistent.PersistentTopic$3.deleteCursorFailed(PersistentTopic.java:869) ~[org.apache.pulsar-pulsar-broker-2.7.3.jar:2.7.3]
	at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl.asyncDeleteCursor(ManagedLedgerImpl.java:827) ~[org.apache.pulsar-managed-ledger-2.7.3.jar:2.7.3]
	at org.apache.pulsar.broker.service.persistent.PersistentTopic.unsubscribe(PersistentTopic.java:853) ~[org.apache.pulsar-pulsar-broker-2.7.3.jar:2.7.3]
	at org.apache.pulsar.broker.service.persistent.PersistentSubscription.lambda$delete$17(PersistentSubscription.java:829) ~[org.apache.pulsar-pulsar-broker-2.7.3.jar:2.7.3]
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995) ~[?:1.8.0_302]
	... 68 more
Caused by: org.apache.bookkeeper.mledger.ManagedLedgerException$CursorNotFoundException: ManagedCursor not found: reader-83cd9bc866
```

**Comment by zhuwenxing** [comment]
It reproduced in local env.
log:
[test-querynode-pod-kill-12-23-17-52-00.zip](https://github.com/milvus-io/milvus/files/7768379/test-querynode-pod-kill-12-23-17-52-00.zip)

**Comment by xige-16** [comment]
> 

After querynode down, the balance task successfully assigned the querynode to the child task, but the assigned querynode was also down when the child task was executed, and there was no online querynode at this time, and the child task exited directly, resulting in data loss

**Comment by zhuwenxing** [comment]
It reproduced in local env and GitHub action in version `master-20211224-9a2c91d`.
So set it as an urgent issue.

`test_e2e.py` failed at search step:
```
[2021-12-25 10:59:34 - ERROR - pymilvus.client.grpc_handler]:
Addr [10.96.87.205:19530] load_collection
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1640401174.360042000","description":"Error received from peer ipv4:10.96.87.205:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
	{'API start': '2021-12-25 10:59:14.357580', 'RPC start': '2021-12-25 10:59:14.357986', 'RPC error': '2021-12-25 10:59:34.360714'} (grpc_handler.py:83)
[2021-12-25 10:59:56 - ERROR - pymilvus.client.grpc_handler]:
Addr [10.96.87.205:19530] load_collection
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1640401196.390996000","description":"Error received from peer ipv4:10.96.87.205:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
	{'API start': '2021-12-25 10:59:36.386999', 'RPC start': '2021-12-25 10:59:36.388627', 'RPC error': '2021-12-25 10:59:56.391277'} (grpc_handler.py:83)
```

`hello_milvus.py` search hangs
```
+ python scripts/hello_milvus.py --host 10.96.87.205

Start time: 2021-12-25 11:02:53

List collections...
['Checker__DHX7EBtN', 'hello_milvus', 'Checker__acLnnfCB', 'Checker__tunmoMbl', 'CreateChecker__K7qZZgyE', 'Checker__GDfyQx96', 'Checker__2qo3CG9A', 'Checker__iyfp8eA0']

Create collection...

List collections...
['Checker__iyfp8eA0', 'Checker__DHX7EBtN', 'Checker__tunmoMbl', 'CreateChecker__K7qZZgyE', 'Checker__GDfyQx96', 'Checker__2qo3CG9A', 'hello_milvus', 'Checker__acLnnfCB']

Insert 3000 vectors cost 1.7160007953643799 seconds

Get collection entities...
6000

Get collection entities cost 2.7078330516815186 seconds

Create index...

Create index cost 3.3081438541412354 seconds

load collection...

load collection cost 0.08123421669006348 seconds

Search...
^CTraceback (most recent call last):
```

log:
[test-querynode-pod-kill-12-25-11-19-00.zip](https://github.com/milvus-io/milvus/files/7775421/test-querynode-pod-kill-12-25-11-19-00.zip)

**Comment by czs007** [comment]
/unassign @xige-16 
/assign @zhuwenxing 
@zhuwenxing please recheck this.

**Comment by zhuwenxing** [comment]
/assign @xige-16 
https://github.com/milvus-io/milvus/runs/4637343350?check_suite_focus=true
This job hangs at `hello_milvus.py`.
Please take a look!

**Comment by zhuwenxing** [comment]
in https://github.com/zhuwenxing/milvus/actions/runs/1633291184 and https://github.com/xige-16/milvus/actions/runs/1633279843, querynode pod kill  job passed. The Milvus version is `master-20211229-42b7753`.
