### ISSUE TITLE
Server crashed while inserting sift-1b datasets

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#1411]
**Describe the bug**
global.log
```
2020-02-28 01:53:27,136 | INFO | default | [WAL] sift_1b_2048_128_l2 is flushed by lsn 4080320591280
2020-02-28 01:53:27,136 | INFO | default | [WAL] Delete wal file 948
2020-02-28 01:53:27,154 | INFO | default | [WAL] Delete wal file 949
2020-02-28 01:53:27,366 | INFO | default | [WAL] record type 1 table sift_1b_2048_128_l2 lsn 4080353148520
2020-02-28 01:53:27,465 | INFO | default | [WAL] record type 1 table sift_1b_2048_128_l2 lsn 4084533341336
2020-02-28 01:53:27,527 | INFO | default | [WAL] record type 1 table sift_1b_2048_128_l2 lsn 4084585341376
2020-02-28 01:53:27,703 | INFO | default | [WAL] record type 1 table sift_1b_2048_128_l2 lsn 4084637341416
2020-02-28 01:53:27,896 | INFO | default | [WAL] record type 1 table sift_1b_2048_128_l2 lsn 4084648115856
2020-02-28 01:53:27,962 | INFO | default | [WAL] record type 1 table sift_1b_2048_128_l2 lsn 4088850091432
2020-02-28 01:53:28,090 | INFO | default | [WAL] record type 1 table sift_1b_2048_128_l2 lsn 4088902091472
2020-02-28 01:53:28,283 | INFO | default | [WAL] record type 1 table sift_1b_2048_128_l2 lsn 4088943083112
2020-02-28 01:53:29,633 | INFO | default | [SERVER] Server received critical signal: 11
2020-02-28 01:53:29,633 | INFO | default | [SERVER] Call stack:
2020-02-28 01:53:29,633 | INFO | default | [SERVER] ../bin/milvus_server() [0x5ec6c4]
2020-02-28 01:53:29,633 | INFO | default | [SERVER] ../bin/milvus_server() [0x5ecde8]
2020-02-28 01:53:29,633 | INFO | default | [SERVER] /usr/lib64/libc.so.6(+0x363b0) [0x7f668c71b3b0]
2020-02-28 01:53:29,633 | INFO | default | [SERVER] /usr/lib64/libc.so.6(+0x156426) [0x7f668c83b426]
2020-02-28 01:53:29,633 | INFO | default | [SERVER] ../bin/milvus_server() [0x893fb3]
2020-02-28 01:53:29,633 | INFO | default | [SERVER] ../bin/milvus_server() [0x89b3d1]
2020-02-28 01:53:29,633 | INFO | default | [SERVER] ../bin/milvus_server() [0x7ba048]
2020-02-28 01:53:29,633 | INFO | default | [SERVER] ../bin/milvus_server() [0x6f9bdc]
2020-02-28 01:53:29,633 | INFO | default | [SERVER] ../bin/milvus_server() [0x63bcf0]
2020-02-28 01:53:29,633 | INFO | default | [SERVER] ../bin/milvus_server() [0x4a9bba]
2020-02-28 01:53:29,633 | INFO | default | [SERVER] ../bin/milvus_server() [0x4a4c06]
2020-02-28 01:53:29,633 | INFO | default | [SERVER] ../bin/milvus_server() [0xeae59f]
2020-02-28 01:53:29,633 | INFO | default | [SERVER] /usr/lib64/libpthread.so.0(+0x7e65) [0x7f668d4efe65]
2020-02-28 01:53:29,633 | INFO | default | [SERVER] /usr/lib64/libc.so.6(clone+0x6d) [0x7f668c7e388d]
```

test log:
```
01:53:13  2020-02-27:17:53:12,545 INFO     [runner.py:150] Start id: 258200000, end id: 258300000
01:53:20  2020-02-27:17:53:20,299 INFO     [client.py:33] Milvus insert run in 7.75s
01:53:20  2020-02-27:17:53:20,309 DEBUG    [runner.py:154] 244946390
01:53:31  2020-02-27:17:53:29,869 INFO     [runner.py:150] Start id: 258300000, end id: 258400000
01:53:31  <_InactiveRpcError of RPC that terminated with:
01:53:31  	status = StatusCode.UNAVAILABLE
01:53:31  	details = "failed to connect to all addresses"
01:53:31  	debug_error_string = "{"created":"@1582826011.356696158","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3941,"referenced_errors":[{"created":"@1582826011.356682904","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":393,"grpc_status":14}]}"
01:53:31  >
01:53:31  2020-02-27:17:53:31,367 ERROR    [grpc_handler.py:594] <_InactiveRpcError of RPC that terminated with:
01:53:31  	status = StatusCode.UNAVAILABLE
01:53:31  	details = "failed to connect to all addresses"
01:53:31  	debug_error_string = "{"created":"@1582826011.356696158","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3941,"referenced_errors":[{"created":"@1582826011.356682904","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":393,"grpc_status":14}]}"
01:53:31  >
01:53:31  2020-02-27:17:53:31,382 ERROR    [client.py:71] Error occurred. failed to connect to all addresses
01:53:31  2020-02-27:17:53:31,382 INFO     [client.py:33] Milvus insert run in 1.51s
01:53:33  2020-02-27:17:53:33,384 ERROR    [main.py:68] Please connect to the server first
01:53:33  2020-02-27:17:53:33,394 ERROR    [main.py:69] Traceback (most recent call last):
01:53:33    File "main.py", line 66, in queue_worker
01:53:33      runner.run(run_type, table)
01:53:33    File "/home/jenkins/agent/workspace/milvus-debug/milvus_benchmark/k8s_runner.py", line 104, in run
01:53:33      res = self.do_insert(milvus_instance, table_name, data_type, dimension, table_size, ni_per)
01:53:33    File "/home/jenkins/agent/workspace/milvus-debug/milvus_benchmark/runner.py", line 154, in do_insert
01:53:33      logger.debug(milvus.count())
01:53:33    File "/home/jenkins/agent/workspace/milvus-debug/milvus_benchmark/client.py", line 150, in count
01:53:33      return self._milvus.get_table_row_count(self._table_name)[1]
01:53:33    File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 16, in wrapper
01:53:33      raise NotConnectError('Please connect to the server first')
01:53:33  milvus.client.exceptions.NotConnectError: Please connect to the server first
01:53:33  
01:53:33  2020-02-27:17:53:33,539 DEBUG    [k8s_runner.py:62] benchmark-test-1hsodmbl
01:53:33  2020-02-27:17:53:33,539 DEBUG    [utils.py:253] helm uninstall -n milvus benchmark-test-1hsodmbl
01:53:34  release "benchmark-test-1hsodmbl" uninstalled
01:53:34  2020-02-27:17:53:33,955 DEBUG    [main.py:74] All task finished in queue: eros
```

last lines in debug.log
```
2020-02-28 01:53:02,860 | DEBUG | default | [SERVER] InsertRequest(table=sift_1b_2048_128_l2, n=100000, partition_tag=): add vectors to engine (0.068634 second [68.633712 ms])
2020-02-28 01:53:02,860 | DEBUG | default | [SERVER] InsertRequest(table=sift_1b_2048_128_l2, n=100000, partition_tag=): total cost (0.069023 second [69.023137 ms])
2020-02-28 01:53:02,990 | DEBUG | default | [SERVER] CountTableRequest(table=sift_1b_2048_128_l2): check validation (0.000325 second [0.324569 ms])
2020-02-28 01:53:02,990 | DEBUG | default | [SERVER] CountTableRequest(table=sift_1b_2048_128_l2): totally cost (0.000928 second [0.927745 ms])
2020-02-28 01:53:14,753 | DEBUG | default | [ENGINE] Update 4 table files
2020-02-28 01:53:14,753 | DEBUG | default | [ENGINE] New merged segment 1582825964093577000 of size 497997410 bytes
2020-02-28 01:53:14,784 | DEBUG | default | [ENGINE] Unmark ongoing file:1582825936289217000 refcount:0
2020-02-28 01:53:14,784 | DEBUG | default | [ENGINE] Unmark ongoing file:1582825936387129000 refcount:0
2020-02-28 01:53:14,784 | DEBUG | default | [ENGINE] Unmark ongoing file:1582825937033571000 refcount:0
2020-02-28 01:53:14,784 | DEBUG | default | [ENGINE] Flushing table: sift_1b_2048_128_l2
2020-02-28 01:53:20,072 | DEBUG | default | [SERVER] InsertRequest(table=sift_1b_2048_128_l2, n=100000, partition_tag=): check validation (0.000281 second [0.280931 ms])
2020-02-28 01:53:20,072 | DEBUG | default | [SERVER] InsertRequest(table=sift_1b_2048_128_l2, n=100000, partition_tag=): prepare vectors data (0.000105 second [0.105182 ms])
2020-02-28 01:53:20,142 | DEBUG | default | [ENGINE] Successfully update table flag, table id = sift_1b_2048_128_l2
2020-02-28 01:53:20,142 | DEBUG | default | [SERVER] InsertRequest(table=sift_1b_2048_128_l2, n=100000, partition_tag=): add vectors to engine (0.069780 second [69.779872 ms])
2020-02-28 01:53:20,142 | DEBUG | default | [SERVER] InsertRequest(table=sift_1b_2048_128_l2, n=100000, partition_tag=): total cost (0.070195 second [70.195229 ms])
2020-02-28 01:53:20,279 | DEBUG | default | [SERVER] CountTableRequest(table=sift_1b_2048_128_l2): check validation (0.000274 second [0.273970 ms])
2020-02-28 01:53:20,280 | DEBUG | default | [SERVER] CountTableRequest(table=sift_1b_2048_128_l2): totally cost (0.000831 second [0.830923 ms])
2020-02-28 01:53:21,841 | DEBUG | default | [ENGINE] Remove segment directory: /test/milvus/db_data_gpu_crud/sift_1b_2048_128_l2_sq8/db/tables/sift_1b_2048_128_l2/1582825807174946000
2020-02-28 01:53:21,956 | DEBUG | default | [ENGINE] Remove segment directory: /test/milvus/db_data_gpu_crud/sift_1b_2048_128_l2_sq8/db/tables/sift_1b_2048_128_l2/1582825807693729000
2020-02-28 01:53:21,957 | DEBUG | default | [ENGINE] Clean 2 files expired in 10 seconds
2020-02-28 01:53:21,958 | DEBUG | default | [ENGINE] Update single table file, file id = 1582825964208012000
2020-02-28 01:53:21,958 | DEBUG | default | [ENGINE] New raw file 1582825964208012000 of size 134217728 bytes, lsn = 4080320591280
2020-02-28 01:53:21,958 | DEBUG | default | [ENGINE] Flushed segment 1582825964208012000
2020-02-28 01:53:27,126 | DEBUG | default | [ENGINE] Update single table file, file id = 1582825964866398000
2020-02-28 01:53:27,126 | DEBUG | default | [ENGINE] New raw file 1582825964866398000 of size 98030592 bytes, lsn = 4080320591280
2020-02-28 01:53:27,126 | DEBUG | default | [ENGINE] Flushed segment 1582825964866398000
2020-02-28 01:53:27,134 | DEBUG | default | [ENGINE] Successfully update table flush_lsn, table id = sift_1b_2048_128_l2
2020-02-28 01:53:27,134 | DEBUG | default | [ENGINE] Finished flushing for table sift_1b_2048_128_l2 in 12.3506 s
2020-02-28 01:53:27,134 | DEBUG | default | [ENGINE] Flushed table sift_1b_2048_128_l2
2020-02-28 01:53:27,136 | DEBUG | default | [ENGINE] Update global lsn = 4080320591280
2020-02-28 01:53:27,357 | DEBUG | default | [ENGINE] Mark ongoing file:1582825964093577000 refcount:1
2020-02-28 01:53:27,357 | DEBUG | default | [ENGINE] Mark ongoing file:1582825964208012000 refcount:1
2020-02-28 01:53:27,357 | DEBUG | default | [ENGINE] Mark ongoing file:1582825964866398000 refcount:1
2020-02-28 01:53:27,357 | DEBUG | default | [ENGINE] Merge files for table: sift_1b_2048_128_l2
2020-02-28 01:53:27,358 | DEBUG | default | [ENGINE] Successfully create table file, file id = 1582826007357931000
2020-02-28 01:53:27,391 | DEBUG | default | [ENGINE] Successfully create table file, file id = 1582826007390143000
2020-02-28 01:53:27,868 | DEBUG | default | [ENGINE] Successfully create table file, file id = 1582826007865305000
2020-02-28 01:53:28,430 | DEBUG | default | [ENGINE] Successfully create table file, file id = 1582826008429339000
```
**Steps/Code to reproduce behavior**
1. create table
2. create index: ivf_sq8
3. inserting vectors, 100,000 vectors each request, and no manual flush

**Expected behavior**

**Environment details**
IndexType: ivf_sq8
Build index gpu: gpu0 gpu1 gpu2 gpu3
```
2020-02-27 11:47:10,759 | INFO | default | [SERVER] Milvus Release version: v0.7.0, built at 2020-02-26 11:44.05
2020-02-27 11:47:10,759 | INFO | default | [SERVER] GPU edition
2020-02-27 11:47:10,784 | INFO | default | [ENGINE] Using SQLite
```
**Screenshots**

**Additional context**

**Comment by JinHai-CN** [comment]
Same issue with #1399?

**Comment by shengjun1985** [comment]
It is the same as #1399.

**Comment by del-zhenwu** [comment]
will run regression test again
