### ISSUE TITLE
[Bug]:[chaos][proxy]Proxy pods keep crashbackoff after running `testcases/test_e2e.py` or deleting pod failure chaos

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#14172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20211223-5a4dc83
- Deployment mode(standalone or cluster): cluster and proxy replicas is 2
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc9.dev22
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

before chaos: one of the proxy pods will restart many times when running test_e2e.py
after chaos: affected pod by chaos can't recovery to ready status

### Expected Behavior

before chaos: all pod running well
after chaos: affected pod by chaos can recovery after deleting chaos

### Steps To Reproduce

```markdown
1. cd `tests/python_client/chaos`
2. change the tag in cluster-values.yaml
3. run `bash chaos_test.sh proxy pod_failure chaos-test 2`
```

### Anything else?

GitHub action: https://github.com/milvus-io/milvus/runs/4621347983?check_suite_focus=true
log: https://github.com/milvus-io/milvus/suites/4749870797/artifacts/131505942

local reproduce:
![image](https://user-images.githubusercontent.com/12268675/147330207-9998e308-f6e5-44c7-a8c9-24be8cdba7ed.png)
log:
[test-proxy-pod-failure-12-24-15-38-00.zip](https://github.com/milvus-io/milvus/files/7773252/test-proxy-pod-failure-12-24-15-38-00.zip)

**Comment by zhuwenxing** [comment]
/assign @czs007
Please help to have a look

**Comment by zhuwenxing** [comment]
error message 
```
time="2021-12-24T08:14:53Z" level=error msg="[Failed to create consumer]" consumerID=20 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=wzekd subscription=by-dev-proxy-0 topic="persistent://public/default/by-dev-searchResult-0"
panic: Failed to create consumer by-dev-searchResult-0, error = All attempts results:
attempt #1:server error: ConsumerBusy: Exclusive consumer is already connected
attempt #2:server error: ConsumerBusy: Exclusive consumer is already connected
attempt #3:server error: ConsumerBusy: Exclusive consumer is already connected
attempt #4:server error: ConsumerBusy: Exclusive consumer is already connected
attempt #5:server error: ConsumerBusy: Exclusive consumer is already connected
attempt #6:server error: ConsumerBusy: Exclusive consumer is already connected
attempt #7:server error: ConsumerBusy: Exclusive consumer is already connected
attempt #8:server error: ConsumerBusy: Exclusive consumer is already connected
attempt #9:server error: ConsumerBusy: Exclusive consumer is already connected
attempt #10:server error: ConsumerBusy: Exclusive consumer is already connected
attempt #11:server error: ConsumerBusy: Exclusive consumer is already connected
attempt #12:server error: ConsumerBusy: Exclusive consumer is already connected
attempt #13:server error: ConsumerBusy: Exclusive consumer is already connected
attempt #14:server error: ConsumerBusy: Exclusive consumer is already connected
attempt #15:server error: ConsumerBusy: Exclusive consumer is already connected
attempt #16:server error: ConsumerBusy: Exclusive consumer is already connected
attempt #17:server error: ConsumerBusy: Exclusive consumer is already connected
attempt #18:server error: ConsumerBusy: Exclusive consumer is already connected
attempt #19:server error: ConsumerBusy: Exclusive consumer is already connected
attempt #20:server error: ConsumerBusy: Exclusive consumer is already connected


goroutine 264 [running]:
github.com/milvus-io/milvus/internal/msgstream.(*mqMsgStream).AsConsumerWithPosition(0xc0004d56c0, 0xc000c8e730, 0x1, 0x1, 0xc000603db0, 0xe, 0x0)
	/go/src/github.com/milvus-io/milvus/internal/msgstream/mq_msgstream.go:164 +0x2a7
github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).collectResultLoop(0xc000517680)
	/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:634 +0x102
created by github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).Start
	/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:845 +0x117
```

**Comment by czs007** [comment]
@zhuwenxing  please recheck this.

**Comment by zhuwenxing** [comment]
Verified and pass in version `master-20211224-9a2c91d`
Keep it open but remove the urgent label.
