### ISSUE TITLE
[Bug]: datanode crashs when specific data inserting.

### ISSUE THREAD

**Issue by andy263** [milvus-io/milvus#14220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):v2.0.0-rc8-20211104-d1f4106
both
- SDK version(e.g. pymilvus v2.0.0rc2):2.0.0rc7
- OS(Ubuntu or CentOS): ubuntu
- CPU/Memory: 16c64G
- GPU: NA
- Others:
```

### Current Behavior

Trying the reverse_image_search demo in porject milvus-io/bootcamp to test image search. Milvus datanode crashed as soon as loading about 200K images to collection. I think it could be some suspicious image data, but failed to determine which one it it since the large amount.

`goroutine 886 [running]:
github.com/milvus-io/milvus/internal/storage.(*PayloadWriter).GetPayloadBufferFromWriter(0xc0023532d0, 0x0, 0x0, 0x695348, 0x4, 0xc047589be0)
        /go/src/github.com/milvus-io/milvus/internal/storage/payload.go:388 +0xd2
github.com/milvus-io/milvus/internal/storage.(*baseEventWriter).GetMemoryUsageInBytes(0xc0019fd770, 0x0, 0x0, 0x11)
        /go/src/github.com/milvus-io/milvus/internal/storage/event_writer.go:133 +0x3b
github.com/milvus-io/milvus/internal/storage.(*baseEventWriter).Finish(0xc0019fd770, 0x0, 0x0)
        /go/src/github.com/milvus-io/milvus/internal/storage/event_writer.go:164 +0x73
github.com/milvus-io/milvus/internal/storage.(*baseBinlogWriter).Close(0xc000798780, 0xc0441ac540, 0x2621509)
        /go/src/github.com/milvus-io/milvus/internal/storage/binlog_writer.go:110 +0x21b
github.com/milvus-io/milvus/internal/storage.(*InsertCodec).Serialize(0xc043fe7dc0, 0x5f793ff0fa80002, 0x5f79f3159300001, 0xc052586560, 0x5f793ff0fa80002, 0xc001aa3d80, 0x0, 0x0, 0xc01d935500, 0xc044b52000, ...)
        /go/src/github.com/milvus-io/milvus/internal/storage/data_codec.go:319 +0x4b5
github.com/milvus-io/milvus/internal/datanode.(*rendezvousFlushManager).flushBufferData(0xc00116f9e0, 0xc052586540, 0x5f79f3159300001, 0x0, 0xc051a17ce0, 0x1, 0xc051a03378)
        /go/src/github.com/milvus-io/milvus/internal/datanode/flush_manager.go:239 +0x1e7
github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Operate(0xc00237cdd0, 0xc051a18b20, 0x1, 0x1, 0x2817160, 0xc051a2e000, 0x0)
        /go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:278 +0x126c
github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work(0xc00139cb60)
        /go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:79 +0xda
created by github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start
        /go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:56 +0x55`

**Comment by yanliang567** [comment]
@czs007 is it known issue that just fixed in master?
/assign @czs007 
/unassign

**Comment by congqixia** [comment]
Hi @andy263. Thanks for the report. Could you please provide the script used to insert data into collection?
