### ISSUE TITLE
Server crashed when searching vectors using GPU

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#1429]
**Describe the bug**
```
2020-02-28 22:42:00,105 | INFO | default | [WAL] record type 5 table  lsn 0
2020-02-28 22:42:01,268 | INFO | default | [WAL] record type 5 table  lsn 0
2020-02-28 22:42:02,420 | INFO | default | [WAL] record type 5 table  lsn 0
2020-02-28 22:42:03,577 | INFO | default | [WAL] record type 5 table  lsn 0
2020-02-28 22:42:04,739 | INFO | default | [WAL] record type 5 table  lsn 0
2020-02-28 22:42:05,846 | INFO | default | [WAL] record type 5 table  lsn 0
2020-02-28 22:42:06,884 | INFO | default | [SERVER] Server received critical signal: 11
2020-02-28 22:42:06,884 | INFO | default | [SERVER] Call stack:
2020-02-28 22:42:06,885 | INFO | default | [SERVER] ../bin/milvus_server() [0x5ec924]
2020-02-28 22:42:06,885 | INFO | default | [SERVER] ../bin/milvus_server() [0x5ed048]
2020-02-28 22:42:06,885 | INFO | default | [SERVER] /usr/lib64/libc.so.6(+0x363b0) [0x7fe5e4c063b0]
2020-02-28 22:42:06,885 | INFO | default | [SERVER] ../bin/milvus_server() [0x63e4e1]
2020-02-28 22:42:06,885 | INFO | default | [SERVER] ../bin/milvus_server() [0x4b49b8]
2020-02-28 22:42:06,885 | INFO | default | [SERVER] ../bin/milvus_server() [0x4a612a]
2020-02-28 22:42:06,885 | INFO | default | [SERVER] ../bin/milvus_server() [0xeb403f]
2020-02-28 22:42:06,885 | INFO | default | [SERVER] /usr/lib64/libpthread.so.0(+0x7e65) [0x7fe5e59dae65]
2020-02-28 22:42:06,885 | INFO | default | [SERVER] /usr/lib64/libc.so.6(clone+0x6d) [0x7fe5e4cce88d]
2020-02-28 22:42:06,987 | INFO | default | [WAL] record type 5 table  lsn 0
2020-02-28 22:42:07,189 | INFO | default | [SERVER] Server received critical signal: 11
2020-02-28 22:42:07,189 | INFO | default | [SERVER] Call stack:
2020-02-28 22:42:07,189 | INFO | default | [SERVER] ../bin/milvus_server() [0x5ec924]
2020-02-28 22:42:07,189 | INFO | default | [SERVER] ../bin/milvus_server() [0x5ed048]
2020-02-28 22:42:07,189 | INFO | default | [SERVER] /usr/lib64/libc.so.6(+0x363b0) [0x7fe5e4c063b0]
2020-02-28 22:42:07,189 | INFO | default | [SERVER] ../bin/milvus_server() [0x63e4e1]
2020-02-28 22:42:07,189 | INFO | default | [SERVER] ../bin/milvus_server() [0x4b49b8]
2020-02-28 22:42:07,189 | INFO | default | [SERVER] ../bin/milvus_server() [0x4a612a]
2020-02-28 22:42:07,189 | INFO | default | [SERVER] ../bin/milvus_server() [0xeb403f]
2020-02-28 22:42:07,189 | INFO | default | [SERVER] /usr/lib64/libpthread.so.0(+0x7e65) [0x7fe5e59dae65]
2020-02-28 22:42:07,189 | INFO | default | [SERVER] /usr/lib64/libc.so.6(clone+0x6d) [0x7fe5e4cce88d]
2020-02-28 22:42:08,098 | INFO | default | [WAL] record type 5 table  lsn 0
2020-02-28 22:42:09,225 | INFO | default | [WAL] record type 5 table  lsn 0
2020-02-28 22:42:10,361 | INFO | default | [WAL] record type 5 table  lsn 0
2020-02-28 22:42:11,480 | INFO | default | [WAL] record type 5 table  lsn 0
```

last lines in debug.log
```
2020-02-28 22:42:07,255 | DEBUG | default | [SERVER] Search task load file id:985 CPU2GPU:1 file type:3 size:287731151 bytes from location: /test/milvus/db_data_gpu_crud/sift_50m_1024_128_l2_ivf_4096/db/tables/sift_50m_1024_128_l2/1582275743619247000/1582360822031095000 totally cost (0.114731 second [114.730695 ms])
2020-02-28 22:42:07,255 | DEBUG | default | [SERVER] PickToLoad  (0.000005 second [0.004755 ms])
2020-02-28 22:42:07,302 | DEBUG | default | [ENGINE] CPU to GPU1
2020-02-28 22:42:07,302 | DEBUG | default | [SERVER] Insert /test/milvus/db_data_gpu_crud/sift_50m_1024_128_l2_ivf_4096/db/tables/sift_50m_1024_128_l2/1582275063124987000/1582360793671686000 size: 1075200000 bytes into cache, usage: 3225600000 bytes, capacity: 6442450944 bytes
2020-02-28 22:42:07,303 | DEBUG | default | [SERVER] Search task load file id:983 CPU2GPU:1 file type:3 size:287731151 bytes from location: /test/milvus/db_data_gpu_crud/sift_50m_1024_128_l2_ivf_4096/db/tables/sift_50m_1024_128_l2/1582275063124987000/1582360793671686000 totally cost (0.047736 second [47.736120 ms])
2020-02-28 22:42:07,303 | DEBUG | default | [SERVER] PickToLoad  (0.000004 second [0.003765 ms])
2020-02-28 22:42:07,350 | DEBUG | default | [ENGINE] CPU to GPU1
2020-02-28 22:42:07,350 | DEBUG | default | [SERVER] Insert /test/milvus/db_data_gpu_crud/sift_50m_1024_128_l2_ivf_4096/db/tables/sift_50m_1024_128_l2/1582274387199573000/1582360770750350000 size: 1075200000 bytes into cache, usage: 4300800000 bytes, capacity: 6442450944 bytes
2020-02-28 22:42:07,350 | DEBUG | default | [SERVER] Search task load file id:981 CPU2GPU:1 file type:3 size:287731151 bytes from location: /test/milvus/db_data_gpu_crud/sift_50m_1024_128_l2_ivf_4096/db/tables/sift_50m_1024_128_l2/1582274387199573000/1582360770750350000 totally cost (0.047256 second [47.255567 ms])
```
**Steps/Code to reproduce behavior**
searching based on sift-50m-sq8 dataset
nq: 200, top_k: 1
```
22:42:05  2020-02-28:14:42:05,144 INFO     [runner.py:175] Start query, query params: top-k: 1000, nq: 100, actually length of vectors: 100
22:42:05  2020-02-28:14:42:05,144 INFO     [runner.py:177] Start run query, run 1 of 2
22:42:05  2020-02-28:14:42:05,514 INFO     [client.py:33] Milvus query run in 0.37s
22:42:05  2020-02-28:14:42:05,515 INFO     [runner.py:177] Start run query, run 2 of 2
22:42:06  2020-02-28:14:42:05,945 INFO     [client.py:33] Milvus query run in 0.43s
22:42:06  2020-02-28:14:42:05,948 INFO     [runner.py:183] Min query time: 0.37
22:42:06  2020-02-28:14:42:05,948 INFO     [runner.py:175] Start query, query params: top-k: 1, nq: 200, actually length of vectors: 200
22:42:06  2020-02-28:14:42:05,948 INFO     [runner.py:177] Start run query, run 1 of 2
22:43:42  <_InactiveRpcError of RPC that terminated with:
22:43:42  	status = StatusCode.UNAVAILABLE
22:43:42  	details = "Socket closed"
22:43:42  	debug_error_string = "{"created":"@1582901021.984698092","description":"Error received from peer ipv4:10.44.0.2:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}"
22:43:42  >
22:43:42  2020-02-28:14:43:41,985 ERROR    [grpc_handler.py:882] <_InactiveRpcError of RPC that terminated with:
22:43:42  	status = StatusCode.UNAVAILABLE
22:43:42  	details = "Socket closed"
22:43:42  	debug_error_string = "{"created":"@1582901021.984698092","description":"Error received from peer ipv4:10.44.0.2:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}"
22:43:42  >
22:43:42  2020-02-28:14:43:41,986 ERROR    [client.py:71] Error occurred: Socket closed
22:43:42  2020-02-28:14:43:41,986 INFO     [client.py:33] Milvus query run in 96.04s
22:43:42  2020-02-28:14:43:41,990 INFO     [runner.py:177] Start run query, run 2 of 2
22:43:43  <_InactiveRpcError of RPC that terminated with:
22:43:43  	status = StatusCode.UNAVAILABLE
22:43:43  	details = "failed to connect to all addresses"
22:43:43  	debug_error_string = "{"created":"@1582901022.994012111","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3941,"referenced_errors":[{"created":"@1582901022.994009672","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":393,"grpc_status":14}]}"
22:43:43  >
22:43:43  2020-02-28:14:43:42,994 ERROR    [grpc_handler.py:882] <_InactiveRpcError of RPC that terminated with:
22:43:43  	status = StatusCode.UNAVAILABLE
22:43:43  	details = "failed to connect to all addresses"
22:43:43  	debug_error_string = "{"created":"@1582901022.994012111","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3941,"referenced_errors":[{"created":"@1582901022.994009672","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":393,"grpc_status":14}]}"
22:43:43  >
22:43:43  2020-02-28:14:43:42,994 ERROR    [client.py:71] Error occurred: failed to connect to all addresses
22:43:43  2020-02-28:14:43:42,994 INFO     [client.py:33] Milvus query run in 1.0s
22:43:43  2020-02-28:14:43:42,994 INFO     [runner.py:183] Min query time: 1.00
22:43:43  2020-02-28:14:43:42,994 INFO     [runner.py:175] Start query, query params: top-k: 10, nq: 200, actually length of vectors: 200
22:43:43  2020-02-28:14:43:42,994 INFO     [runner.py:177] Start run query, run 1 of 2
22:46:04  <_InactiveRpcError of RPC that terminated with:
22:46:04  	status = StatusCode.UNAVAILABLE
22:46:04  	details = "Socket closed"
22:46:04  	debug_error_string = "{"created":"@1582901156.986139869","description":"Error received from peer ipv4:10.44.0.2:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}"
22:46:04  >
22:46:04  2020-02-28:14:45:56,987 ERROR    [grpc_handler.py:882] <_InactiveRpcError of RPC that terminated with:
22:46:04  	status = StatusCode.UNAVAILABLE
22:46:04  	details = "Socket closed"
22:46:04  	debug_error_string = "{"created":"@1582901156.986139869","description":"Error received from peer ipv4:10.44.0.2:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}"
22:46:04  >
22:46:04  2020-02-28:14:45:56,987 ERROR    [client.py:71] Error occurred: Socket closed
22:46:04  2020-02-28:14:45:56,987 INFO     [client.py:33] Milvus query run in 133.99s
22:46:04  2020-02-28:14:45:56,988 INFO     [runner.py:177] Start run query, run 2 of 2
22:46:04  2020-02-28:14:45:58,989 ERROR    [main.py:68] Please connect to the server first
22:46:04  2020-02-28:14:45:58,992 ERROR    [main.py:69] Traceback (most recent call last):
22:46:04    File "main.py", line 66, in queue_worker
22:46:04      runner.run(run_type, table)
22:46:04    File "/home/jenkins/agent/workspace/milvus-debug/milvus_benchmark/k8s_runner.py", line 195, in run
22:46:04      res = self.do_query(milvus_instance, table_name, top_ks, nqs, nprobe, run_count)
22:46:04    File "/home/jenkins/agent/workspace/milvus-debug/milvus_benchmark/runner.py", line 179, in do_query
22:46:04      query_res = milvus.query(vectors, top_k, nprobe)
22:46:04    File "/home/jenkins/agent/workspace/milvus-debug/milvus_benchmark/client.py", line 31, in wrapper
22:46:04      result = func(*args, **kwargs)
22:46:04    File "/home/jenkins/agent/workspace/milvus-debug/milvus_benchmark/client.py", line 145, in query
22:46:04      status, result = self._milvus.search_vectors(self._table_name, top_k, nprobe, X)
22:46:04    File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 16, in wrapper
22:46:04      raise NotConnectError('Please connect to the server first')
22:46:04  milvus.client.exceptions.NotConnectError: Please connect to the server first
22:46:04  
22:46:04  2020-02-28:14:45:59,5 DEBUG    [k8s_runner.py:62] benchmark-test-ngvwt2j4
22:46:04  2020-02-28:14:45:59,5 DEBUG    [utils.py:257] helm uninstall -n milvus benchmark-test-ngvwt2j4
22:46:04  release "benchmark-test-ngvwt2j4" uninstalled
22:46:04  2020-02-28:14:45:59,379 DEBUG    [main.py:74] All task finished in queue: poseidon

```

**Expected behavior**

**Environment details**
GPU version with wal-enabled
```
2020-02-28 22:40:37,090 | INFO | default | [SERVER] Milvus Release version: v0.7.0, built at 2020-02-28 13:02.13
2020-02-28 22:40:37,090 | INFO | default | [SERVER] GPU edition
2020-02-28 22:40:37,112 | INFO | default | [ENGINE] Using SQLite
2020-02-28 22:40:37,306 | INFO | default | [WAL] record type 5 record lsn 0 error code  0
2020-02-28 22:40:37,306 | INFO | default | [WAL] record type 5 table  lsn 0
2020-02-28 22:40:37,306 | INFO | default | [STORAGE] S3 not enabled!
```

**Screenshots**

**Additional context**

**Comment by del-zhenwu** [comment]
```
2020-03-01 12:04:50,573 | INFO | default | [SERVER] Call stack:
2020-03-01 12:04:50,573 | INFO | default | [SERVER] ../bin/milvus_server() [0x6043d4]
2020-03-01 12:04:50,574 | INFO | default | [SERVER] ../bin/milvus_server() [0x604af8]
2020-03-01 12:04:50,574 | INFO | default | [SERVER] /usr/lib64/libc.so.6(+0x363b0) [0x7f4c52b373b0]
2020-03-01 12:04:50,575 | INFO | default | [SERVER] ../bin/milvus_server() [0x64d72c]
2020-03-01 12:04:50,575 | INFO | default | [SERVER] ../bin/milvus_server() [0x4b8f38]
2020-03-01 12:04:50,576 | INFO | default | [SERVER] ../bin/milvus_server() [0x4aa6aa]
2020-03-01 12:04:50,576 | INFO | default | [SERVER] ../bin/milvus_server() [0xed865f]
2020-03-01 12:04:50,576 | INFO | default | [SERVER] /usr/lib64/libpthread.so.0(+0x7e65) [0x7f4c5390be65]
2020-03-01 12:04:50,577 | INFO | default | [SERVER] /usr/lib64/libc.so.6(clone+0x6d) [0x7f4c52bff88d]
2020-03-01 12:04:51,010 | INFO | default | [SERVER] Server received critical signal: 11
2020-03-01 12:04:51,010 | INFO | default | [SERVER] Call stack:
2020-03-01 12:04:51,011 | INFO | default | [SERVER] ../bin/milvus_server() [0x6043d4]
2020-03-01 12:04:51,011 | INFO | default | [SERVER] ../bin/milvus_server() [0x604af8]
2020-03-01 12:04:51,012 | INFO | default | [SERVER] /usr/lib64/libc.so.6(+0x363b0) [0x7f4c52b373b0]
2020-03-01 12:04:51,012 | INFO | default | [SERVER] ../bin/milvus_server() [0x64d72c]
2020-03-01 12:04:51,013 | INFO | default | [SERVER] ../bin/milvus_server() [0x4b8f38]
2020-03-01 12:04:51,013 | INFO | default | [SERVER] ../bin/milvus_server() [0x4aa6aa]
2020-03-01 12:04:51,013 | INFO | default | [SERVER] ../bin/milvus_server() [0xed865f]
2020-03-01 12:04:51,014 | INFO | default | [SERVER] /usr/lib64/libpthread.so.0(+0x7e65) [0x7f4c5390be65]
2020-03-01 12:04:51,014 | INFO | default | [SERVER] /usr/lib64/libc.so.6(clone+0x6d) [0x7f4c52bff88d]
2020-03-01 12:04:51,259 | INFO | default | [WAL] record type 5 table  lsn 0
2020-03-01 12:04:51,404 | INFO | default | [SERVER] Server received critical signal: 11
2020-03-01 12:04:51,405 | INFO | default | [SERVER] Call stack:
2020-03-01 12:04:51,405 | INFO | default | [SERVER] ../bin/milvus_server() [0x6043d4]
2020-03-01 12:04:51,406 | INFO | default | [SERVER] ../bin/milvus_server() [0x604af8]
2020-03-01 12:04:51,406 | INFO | default | [SERVER] /usr/lib64/libc.so.6(+0x363b0) [0x7f4c52b373b0]
2020-03-01 12:04:51,406 | INFO | default | [SERVER] ../bin/milvus_server() [0x64d72c]
2020-03-01 12:04:51,407 | INFO | default | [SERVER] ../bin/milvus_server() [0x4b8f38]
2020-03-01 12:04:51,407 | INFO | default | [SERVER] ../bin/milvus_server() [0x4aa6aa]
2020-03-01 12:04:51,408 | INFO | default | [SERVER] ../bin/milvus_server() [0xed865f]
2020-03-01 12:04:51,408 | INFO | default | [SERVER] /usr/lib64/libpthread.so.0(+0x7e65) [0x7f4c5390be65]
2020-03-01 12:04:51,408 | INFO | default | [SERVER] /usr/lib64/libc.so.6(clone+0x6d) [0x7f4c52bff88d]
2020-03-01 12:04:51,747 | INFO | default | [SERVER] Server received critical signal: 11
2020-03-01 12:04:51,747 | INFO | default | [SERVER] Call stack:
2020-03-01 12:04:51,748 | INFO | default | [SERVER] ../bin/milvus_server() [0x6043d4]
2020-03-01 12:04:51,748 | INFO | default | [SERVER] ../bin/milvus_server() [0x604af8]
2020-03-01 12:04:51,749 | INFO | default | [SERVER] /usr/lib64/libc.so.6(+0x363b0) [0x7f4c52b373b0]
2020-03-01 12:04:51,749 | INFO | default | [SERVER] ../bin/milvus_server() [0x64d72c]
2020-03-01 12:04:51,750 | INFO | default | [SERVER] ../bin/milvus_server() [0x4b8f38]
2020-03-01 12:04:51,750 | INFO | default | [SERVER] ../bin/milvus_server() [0x4aa6aa]
2020-03-01 12:04:51,751 | INFO | default | [SERVER] ../bin/milvus_server() [0xed865f]
2020-03-01 12:04:51,751 | INFO | default | [SERVER] /usr/lib64/libpthread.so.0(+0x7e65) [0x7f4c5390be65]
2020-03-01 12:04:51,752 | INFO | default | [SERVER] /usr/lib64/libc.so.6(clone+0x6d) [0x7f4c52bff88d]
```
