### ISSUE TITLE
[Bug]: [benchmark][standalone]insert raise error: Connection timed out, keepalive watchdog timeout

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#14834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220104-b10c361
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc9.dev22
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

client pod: benchmark-cron-1641312000-3614219473

client logs:
```
[2022-01-04 16:03:41,091] [    INFO] - {'host': 'benchmark-cron-1641312000-4-milvus.qa-milvus.svc.cluster.local', 'port': 19530, 'deploy_mode': 'single', 'server_tag': '8c16m', 'deploy_opology': {'server': {'server_tag': '8c16m'}, 'milvus': {'deploy_mode': 'single'}}} (milvus_benchmark.main:64)
[2022-01-04 16:03:41,092] [   DEBUG] - Get runner (milvus_benchmark.main:82)
[2022-01-04 16:03:59,188] [    INFO] - Prepare to run cases (milvus_benchmark.main:86)
[2022-01-04 16:03:59,200] [   DEBUG] - Milvus exists_collection run in 0.0115s (milvus_benchmark.client:53)
[2022-01-04 16:04:00,264] [    INFO] - Create collection: <sift_128_euclidean> successfully (milvus_benchmark.client:149)
[2022-01-04 16:04:00,265] [   DEBUG] - Milvus create_collection run in 1.0641s (milvus_benchmark.client:53)
[2022-01-04 16:04:05,138] [   DEBUG] - The row count of entities to be inserted: 1000000 (milvus_benchmark.runners.accuracy:226)
[2022-01-04 16:04:05,154] [   DEBUG] - Milvus get_info run in 0.0146s (milvus_benchmark.client:53)
[2022-01-04 16:07:41,399] [   ERROR] - 
Addr [benchmark-cron-1641312000-4-milvus.qa-milvus.svc.cluster.local:19530] bulk_insert
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Connection timed out"
	debug_error_string = "{"created":"@1641312461.381701326","description":"Error received from peer ipv4:10.96.55.34:19530","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Connection timed out","grpc_status":14}"
>
	{'API start': '2022-01-04 16:04:05.750258', 'RPC start': '2022-01-04 16:04:05.750286', 'RPC error': '2022-01-04 16:07:41.399425'} (pymilvus.client.grpc_handler:84)
[2022-01-04 16:10:52,784] [   ERROR] - 
Addr [benchmark-cron-1641312000-4-milvus.qa-milvus.svc.cluster.local:19530] bulk_insert
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "keepalive watchdog timeout"
	debug_error_string = "{"created":"@1641312628.273850246","description":"Error received from peer ipv4:10.96.55.34:19530","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"keepalive watchdog timeout","grpc_status":14}"
>
	{'API start': '2022-01-04 16:07:43.496267', 'RPC start': '2022-01-04 16:07:43.496289', 'RPC error': '2022-01-04 16:10:52.784435'} (pymilvus.client.grpc_handler:84)
[2022-01-04 16:13:25,703] [   ERROR] - 
Addr [benchmark-cron-1641312000-4-milvus.qa-milvus.svc.cluster.local:19530] bulk_insert
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Connection timed out"
	debug_error_string = "{"created":"@1641312805.701731841","description":"Error received from peer ipv4:10.96.55.34:19530","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Connection timed out","grpc_status":14}"
>
	{'API start': '2022-01-04 16:10:55.853786', 'RPC start': '2022-01-04 16:10:55.853813', 'RPC error': '2022-01-04 16:13:25.703020'} (pymilvus.client.grpc_handler:84)
[2022-01-04 16:14:04,294] [   ERROR] - 
Addr [benchmark-cron-1641312000-4-milvus.qa-milvus.svc.cluster.local:19530] bulk_insert
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Connection timed out"
	debug_error_string = "{"created":"@1641312844.293712508","description":"Error received from peer ipv4:10.96.55.34:19530","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Connection timed out","grpc_status":14}"
>
	{'API start': '2022-01-04 16:13:28.010738', 'RPC start': '2022-01-04 16:13:28.010782', 'RPC error': '2022-01-04 16:14:04.294358'} (pymilvus.client.grpc_handler:84)
[2022-01-04 16:17:28,838] [   ERROR] - 
Addr [benchmark-cron-1641312000-4-milvus.qa-milvus.svc.cluster.local:19530] bulk_insert
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Connection timed out"
	debug_error_string = "{"created":"@1641313048.837743778","description":"Error received from peer ipv4:10.96.55.34:19530","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Connection timed out","grpc_status":14}"
>
	{'API start': '2022-01-04 16:14:06.586750', 'RPC start': '2022-01-04 16:14:06.586766', 'RPC error': '2022-01-04 16:17:28.838413'} (pymilvus.client.grpc_handler:84)
[2022-01-04 16:21:56,807] [   ERROR] - 
Addr [benchmark-cron-1641312000-4-milvus.qa-milvus.svc.cluster.local:19530] bulk_insert
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "keepalive watchdog timeout"
	debug_error_string = "{"created":"@1641313280.404868028","description":"Error received from peer ipv4:10.96.55.34:19530","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"keepalive watchdog timeout","grpc_status":14}"
>
	{'API start': '2022-01-04 16:17:33.689102', 'RPC start': '2022-01-04 16:17:33.689132', 'RPC error': '2022-01-04 16:21:56.807079'} (pymilvus.client.grpc_handler:84)
[2022-01-04 16:26:48,295] [   ERROR] - 
Addr [benchmark-cron-1641312000-4-milvus.qa-milvus.svc.cluster.local:19530] bulk_insert
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Connection timed out"
	debug_error_string = "{"created":"@1641313608.293964835","description":"Error received from peer ipv4:10.96.55.34:19530","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Connection timed out","grpc_status":14}"
>
	{'API start': '2022-01-04 16:22:18.343106', 'RPC start': '2022-01-04 16:22:18.343132', 'RPC error': '2022-01-04 16:26:48.295584'} (pymilvus.client.grpc_handler:84)
[2022-01-04 16:28:52,428] [   ERROR] - 
Addr [benchmark-cron-1641312000-4-milvus.qa-milvus.svc.cluster.local:19530] bulk_insert
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Connection timed out"
	debug_error_string = "{"created":"@1641313732.421874571","description":"Error received from peer ipv4:10.96.55.34:19530","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Connection timed out","grpc_status":14}"
>
	{'API start': '2022-01-04 16:26:53.359696', 'RPC start': '2022-01-04 16:26:53.359735', 'RPC error': '2022-01-04 16:28:52.428251'} (pymilvus.client.grpc_handler:84)
[2022-01-04 16:32:11,784] [   ERROR] - 
Addr [benchmark-cron-1641312000-4-milvus.qa-milvus.svc.cluster.local:19530] bulk_insert
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "keepalive watchdog timeout"
	debug_error_string = "{"created":"@1641313891.869898735","description":"Error received from peer ipv4:10.96.55.34:19530","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"keepalive watchdog timeout","grpc_status":14}"
>
	{'API start': '2022-01-04 16:28:56.756866', 'RPC start': '2022-01-04 16:28:56.756895', 'RPC error': '2022-01-04 16:32:11.784326'} (pymilvus.client.grpc_handler:84)
[2022-01-04 16:37:18,664] [   ERROR] - 
Addr [benchmark-cron-1641312000-4-milvus.qa-milvus.svc.cluster.local:19530] bulk_insert
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Connection timed out"
	debug_error_string = "{"created":"@1641314238.661784732","description":"Error received from peer ipv4:10.96.55.34:19530","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Connection timed out","grpc_status":14}"
>
	{'API start': '2022-01-04 16:32:13.870422', 'RPC start': '2022-01-04 16:32:13.870453', 'RPC error': '2022-01-04 16:37:18.664070'} (pymilvus.client.grpc_handler:84)
[2022-01-04 16:37:18,666] [   ERROR] - <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Connection timed out"
	debug_error_string = "{"created":"@1641314238.661784732","description":"Error received from peer ipv4:10.96.55.34:19530","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Connection timed out","grpc_status":14}"
> (milvus_benchmark.client:166)
[2022-01-04 16:37:18,666] [   DEBUG] - Milvus insert run in 1992.9166s (milvus_benchmark.client:53)
[2022-01-04 16:37:18,667] [   ERROR] -  (milvus_benchmark.main:118)
[2022-01-04 16:37:18,670] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 87, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/accuracy.py", line 243, in prepare
    assert res_ids == ids
AssertionError
 (milvus_benchmark.main:119)
[2022-01-04 16:37:18,671] [   DEBUG] - {'_version': '0.1', '_type': 'metric', 'run_id': 1641312221, 'mode': 'local', 'server': <milvus_benchmark.metrics.models.server.Server object at 0x7f6c1080e978>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware object at 0x7f6c1080eb70>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7f6c1080efd0>, 'status': 'RUN_FAILED', 'err_message': '', 'collection': {'dimension': 128, 'metric_type': 'l2', 'dataset_name': 'sift_128_euclidean', 'shards_num': None}, 'index': {}, 'search': None, 'run_params': None, 'metrics': {'type': 'ann_accuracy', 'value': {}}, 'datetime': '2022-01-04 16:03:41.091457', 'type': 'metric'} (milvus_benchmark.metric.api:29)
```

### Expected Behavior

argo task: benchmark-cron-1641312000

test yaml:
client-configmap:client-acc-sift-hnsw,instanceId:4, server-configmap:server-single-8c16m

server:
```
NAME                                                              READY   STATUS             RESTARTS   AGE     IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-cron-1641312000-4-etcd-0                                1/1     Running            0          107s    10.97.17.221   qa-node014.zilliz.local   <none>           <none>
benchmark-cron-1641312000-4-milvus-standalone-db57986d5-4wntq     1/1     Running            0          106s    10.97.12.221   qa-node015.zilliz.local   <none>           <none>
benchmark-cron-1641312000-4-minio-759c99b449-72hc7                1/1     Running            0          106s    10.97.12.224   qa-node015.zilliz.local   <none>           <none>
```

**Comment by czs007** [comment]
@wangting0128 @yanliang567 

looking at the log in https://podlog-dev.milvus.io/pod-logs?pod-name=benchmark-cron-1641312000-4-milvus-standalone-db57986d5-4wntq

```

[2022/01/04 16:00:52.001 +00:00] [DEBUG] [session_util.go:86] ["Session try to connect to etcd"]

{"level":"warn","ts":"2022-01-04T16:01:51.989Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00016ea80/#initially=[benchmark-cron-1641312000-4-etcd:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp: lookup benchmark-cron-1641312000-4-etcd on 10.96.0.10:53: server misbehaving\""}
```

You can see that etcd has not been connected

**Comment by yanliang567** [comment]
@LoveEachDay could you please help to check the etcd status at that time
/assign @LoveEachDay

**Comment by xiaofan-luan** [comment]
@LoveEachDay Do we want to keep track of this issue? @LoveEachDay

**Comment by yanliang567** [comment]
not reproduce recently, close for now
