### ISSUE TITLE
[Bug]: [benchmark][standalone]create index raise error: syncTimestamp Failed:context deadline exceeded

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#14833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220104-b10c361
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc9.dev22
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

client pod: benchmark-cluster-cron-1641330000-527344790

client logs:
```
[2022-01-04 21:05:06,823] [    INFO] - {'total_time': 38.4861, 'rps': 25983.4094, 'ni_time': 1.9243} (milvus_benchmark.runners.base:151)
[2022-01-04 21:05:09,500] [   DEBUG] - Milvus flush run in 2.5545s (milvus_benchmark.client:53)
[2022-01-04 21:05:09,508] [   DEBUG] - Row count: 1000000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:421)
[2022-01-04 21:05:09,510] [   DEBUG] - 1000000 (milvus_benchmark.runners.locust:299)
[2022-01-04 21:05:09,511] [   DEBUG] - Start build index for last file (milvus_benchmark.runners.locust:301)
[2022-01-04 21:05:09,513] [    INFO] - Building index start, collection_name: sift_1m_128_l2, index_type: IVF_SQ8, metric_type: L2 (milvus_benchmark.client:274)
[2022-01-04 21:05:09,514] [    INFO] - {'nlist': 1024} (milvus_benchmark.client:276)
[2022-01-04 21:05:09,516] [   DEBUG] - collection: sift_1m_128_l2 Index params: {'index_type': 'IVF_SQ8', 'metric_type': 'L2', 'params': {'nlist': 1024}} (milvus_benchmark.client:282)
[2022-01-04 21:05:20,708] [   ERROR] - Error: <BaseException: (code=1, message=syncTimestamp Failed:context deadline exceeded)> (pymilvus.client.grpc_handler:69)
[2022-01-04 21:05:20,713] [   ERROR] - Error: <BaseException: (code=1, message=syncTimestamp Failed:context deadline exceeded)> (pymilvus.client.grpc_handler:69)
[2022-01-04 21:05:20,715] [   ERROR] - Error: <BaseException: (code=1, message=syncTimestamp Failed:context deadline exceeded)> (pymilvus.client.grpc_handler:69)
[2022-01-04 21:05:20,718] [   ERROR] - <BaseException: (code=1, message=syncTimestamp Failed:context deadline exceeded)> (milvus_benchmark.main:118)
[2022-01-04 21:05:20,748] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 87, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/locust.py", line 303, in prepare
    self.milvus.create_index(index_field_name, case_param["index_type"], case_param["metric_type"], index_param=case_param["index_param"])
  File "/src/milvus_benchmark/client.py", line 49, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 283, in create_index
    res = self._milvus.create_index(tmp_collection_name, field_name, index_params, _async=_async)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 58, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 42, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 810, in create_index
    return handler.create_index(collection_name, field_name, params, timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 771, in create_index
    field_name=field_name, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 819, in wait_for_creating_index
    state, fail_reason = self.get_index_state(collection_name, field_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 812, in get_index_state
    raise BaseException(status.error_code, status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=syncTimestamp Failed:context deadline exceeded)>
 (milvus_benchmark.main:119)
[2022-01-04 21:05:20,751] [   DEBUG] - {'_version': '0.1', '_type': 'metric', 'run_id': 1641330232, 'mode': 'local', 'server': <milvus_benchmark.metrics.models.server.Server object at 0x7fdf56af0b38>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware object at 0x7fdf56af0cc0>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7fdf56af0da0>, 'status': 'RUN_FAILED', 'err_message': '', 'collection': {'dimension': 128, 'metric_type': 'l2', 'dataset_name': 'sift_1m_128_l2', 'collection_size': 1000000, 'other_fields': None, 'ni_per': 50000, 'shards_num': None}, 'index': {'index_type': 'ivf_sq8', 'index_param': {'nlist': 1024}}, 'search': {'nq': 1000, 'topk': 10, 'search_param': {'nprobe': 16}}, 'run_params': {'task': {'connection_num': 1, 'clients_num': 100, 'spawn_rate': 2, 'during_time': 600, 'types': [{'type': 'query', 'weight': 1, 'params': {'top_k': 10, 'nq': 1000, 'search_param': {'nprobe': 16}}}]}, 'connection_type': 'single'}, 'metrics': {'type': 'locust_search_performance', 'value': {}}, 'datetime': '2022-01-04 21:03:52.193256', 'type': 'metric'} (milvus_benchmark.metric.api:29)
```

### Expected Behavior

argo task: benchmark-cluster-cron-1641330000

test yaml:
client-configmap:client-search-locust-1000,instanceId:4, server-configmap:server-single-8c16m

server:
```
NAME                                                              READY   STATUS             RESTARTS   AGE     IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-cluster-cron-1641330000-4-etcd-0                        1/1     Running            0          95s     10.97.16.108   qa-node013.zilliz.local   <none>           <none>
benchmark-cluster-cron-1641330000-4-milvus-standalone-56c7d6sgm   1/1     Running            0          95s     10.97.19.92    qa-node016.zilliz.local   <none>           <none>
benchmark-cluster-cron-1641330000-4-minio-688b5ff64c-4vc5f        1/1     Running            0          95s     10.97.19.93    qa-node016.zilliz.local   <none>           <none>
```

### Steps To Reproduce

```markdown
1、create collection
2、build index of ivf_sq8
3、insert 1 million vectors
4、flush collection
5、build index with the same params <- raise error
```

### Anything else?

client-search-locust-1000:
```
locust_search_performance:
      collections:
        - 
          collection_name: sift_1m_128_l2
          ni_per: 50000
          build_index: true
          index_type: ivf_sq8
          index_param:
            nlist: 1024
          task: 
            connection_num: 1
            clients_num: 100
            spawn_rate: 2
            during_time: 600
            types:
              -
                type: query
                weight: 1
                params:
                  top_k: 10
                  nq: 1000
                  search_param:
                    nprobe: 16
```

**Comment by xiaocai2333** [comment]
RootCoord can't be connected.
```
"rootcoord ClientBase ReCall grpc first call get error "] [error="err: rpc error: code = DeadlineExceeded desc = context deadline exceeded\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:46 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:228 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall\n/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/client/client.go:327 github.com/milvus-io/milvus/internal/distributed/rootcoord/client.(*Client).AllocTimestamp\n/go/src/github.com/milvus-io/milvus/internal/proxy/timestamp.go:57 github.com/milvus-io/milvus/internal/proxy.(*timestampAllocator).alloc\n/go/src/github.com/milvus-io/milvus/internal/proxy/timestamp.go:77 github.com/milvus-io/milvus/internal/proxy.(*timestampAllocator).AllocOne\n/go/src/github.com/milvus-io/milvus/internal/proxy/channels_time_ticker.go:88 github.com/milvus-io/milvus/internal/proxy.(*channelsTimeTickerImpl).tick\n/go/src/github.com/milvus-io/milvus/internal/proxy/channels_time_ticker.go:155 github.com/milvus-io/milvus/internal/proxy.(*channelsTimeTickerImpl).tickLoop\n/usr/local/go/src/runtime/asm_amd64.s:1374 runtime.goexit\n"]
```

**Comment by xiaocai2333** [comment]
tso 5 seconds without allocation success, because RootCoord could not be connected.

![image](https://user-images.githubusercontent.com/46207236/149256018-c4276f31-7681-4878-ab3b-7be638428cd5.png)

**Comment by xiaocai2333** [comment]
Maybe RootCoord cannot be connected due to network fluctuations. 
@wangting0128 , please retest it, if it reproduces, let me know.

**Comment by xiaocai2333** [comment]
The same as #15522 .

**Comment by xiaofan-luan** [comment]
duplicated with #15522
