### ISSUE TITLE
Server crashed during adding vectors

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#1491]
**Describe the bug**
table/log path: 
```
2020-03-03 15:10:32,646 | DEBUG | default | [ENGINE] Adding 701466 vectors and uids took 0.271512 s
2020-03-03 15:10:32,646 | DEBUG | default | [ENGINE] Merging completed from /var/lib/milvus/db/tables/sift_50m_2048_128_l2/1583219430112702000 to /var/lib/milvus/db/tables/sift_50m_2048_128_l2/1583219431639931000
2020-03-03 15:10:32,678 | DEBUG | default | [ENGINE] Merging from /var/lib/milvus/db/tables/sift_50m_2048_128_l2/1583219430166507000 to /var/lib/milvus/db/tables/sift_50m_2048_128_l2/1583219431639931000
2020-03-03 15:10:32,690 | DEBUG | default | [ENGINE] Loading segment took 0.0124152 s
2020-03-03 15:10:32,991 | DEBUG | default | [ENGINE] Adding 36390 vectors and uids took 0.300632 s
2020-03-03 15:10:32,991 | DEBUG | default | [ENGINE] Merging completed from /var/lib/milvus/db/tables/sift_50m_2048_128_l2/1583219430166507000 to /var/lib/milvus/db/tables/sift_50m_2048_128_l2/1583219431639931000
2020-03-03 15:10:32,991 | DEBUG | default | [ENGINE] Initializing bloom filter took 0.00019186 s
2020-03-03 15:10:33,251 | DEBUG | default | [ENGINE] Adding 737856 ids to bloom filter took 0.259871 s
2020-03-03 15:10:33,251 | DEBUG | default | [ENGINE] Writing bloom filter took 6.533e-06 s
2020-03-03 15:10:33,251 | DEBUG | default | [ENGINE] Writing bloom filter took 0.260156 s in total
2020-03-03 15:10:33,426 | DEBUG | default | [ENGINE] Writing raw vectors took 0.174698 s
2020-03-03 15:10:33,429 | DEBUG | default | [ENGINE] Writing uids took 0.00298074 s
2020-03-03 15:10:33,429 | DEBUG | default | [ENGINE] Writing vectors and uids took 0.177836 s in total
2020-03-03 15:10:33,429 | DEBUG | default | [ENGINE] Writing deleted docs took 8.1342e-05 s
2020-03-03 15:10:33,436 | DEBUG | default | [ENGINE] Update 3 table files
2020-03-03 15:10:33,436 | DEBUG | default | [ENGINE] New merged segment 1583219431639931000 of size 389559730 bytes
2020-03-03 15:10:33,474 | DEBUG | default | [ENGINE] Unmark ongoing file:1583219430112702000 refcount:0
2020-03-03 15:10:33,474 | DEBUG | default | [ENGINE] Unmark ongoing file:1583219430166507000 refcount:0
2020-03-03 15:10:33,474 | DEBUG | default | [ENGINE] Server will shutdown, skip merge action for table: sift_50m_2048_128_l2
2020-03-03 15:10:33,474 | DEBUG | default | [ENGINE] Server will shutdown, skip merge action
2020-03-03 15:10:33,481 | DEBUG | default | [ENGINE] Update global lsn = 0
2020-03-03 15:10:33,482 | DEBUG | default | [ENGINE] Server will shutdown, skip merge action
2020-03-03 15:10:33,491 | DEBUG | default | [ENGINE] Begin WaitMergeFileFinish
2020-03-03 15:10:33,492 | DEBUG | default | [ENGINE] End WaitMergeFileFinish
2020-03-03 15:10:33,492 | DEBUG | default | [ENGINE] Begin WaitBuildIndexFinish
```
global . log
```
2020-03-03 15:10:15,549 | INFO | default | [WAL] record type 1 table sift_50m_2048_128_l2 lsn 210480754745
2020-03-03 15:10:15,664 | INFO | default | [WAL] record type 1 table sift_50m_2048_128_l2 lsn 210532754786
2020-03-03 15:10:15,863 | INFO | default | [WAL] record type 5 table sift_50m_2048_128_l2 lsn 210532754786
2020-03-03 15:10:15,863 | INFO | default | [WAL] record type 5 table sift_50m_2048_128_l2 lsn 210532754786
2020-03-03 15:10:19,052 | INFO | default | [WAL] sift_50m_2048_128_l2 insert in part  with lsn 210584754827
2020-03-03 15:10:22,575 | INFO | default | [WAL] sift_50m_2048_128_l2 insert in part  with lsn 214797504841
2020-03-03 15:10:25,830 | INFO | default | [WAL] sift_50m_2048_128_l2 is flushed by lsn 210532754786
2020-03-03 15:10:25,830 | INFO | default | [WAL] Delete wal file 48
2020-03-03 15:10:25,869 | INFO | default | [WAL] record type 1 table sift_50m_2048_128_l2 lsn 210584754827
2020-03-03 15:10:25,999 | INFO | default | [WAL] record type 1 table sift_50m_2048_128_l2 lsn 210587614868
2020-03-03 15:10:26,043 | INFO | default | [WAL] record type 1 table sift_50m_2048_128_l2 lsn 214797504841
2020-03-03 15:10:26,248 | INFO | default | [WAL] sift_50m_2048_128_l2 insert in part  with lsn 214849504882
2020-03-03 15:10:26,284 | INFO | default | [WAL] record type 1 table sift_50m_2048_128_l2 lsn 214849504882
2020-03-03 15:10:26,530 | INFO | default | [WAL] record type 5 table sift_50m_2048_128_l2 lsn 214849504882
2020-03-03 15:10:26,530 | INFO | default | [WAL] record type 5 table sift_50m_2048_128_l2 lsn 214849504882
2020-03-03 15:10:27,184 | INFO | default | [WAL] sift_50m_2048_128_l2 is flushed by lsn 214849504882
2020-03-03 15:10:27,184 | INFO | default | [WAL] Delete wal file 49
2020-03-03 15:10:27,243 | INFO | default | [WAL] record type 5 table  lsn 214849504882
2020-03-03 15:10:29,017 | INFO | default | [WAL] record type 5 table  lsn 214849504882
2020-03-03 15:10:29,938 | INFO | default | [WAL] sift_50m_2048_128_l2 insert in part  with lsn 219062254937
2020-03-03 15:10:29,938 | INFO | default | [WAL] record type 1 table sift_50m_2048_128_l2 lsn 214882582123
2020-03-03 15:10:30,112 | INFO | default | [WAL] sift_50m_2048_128_l2 is flushed by lsn 214882582123
2020-03-03 15:10:30,122 | INFO | default | [WAL] record type 1 table sift_50m_2048_128_l2 lsn 219062254937
2020-03-03 15:10:30,218 | INFO | default | [WAL] record type 5 table sift_50m_2048_128_l2 lsn 219062254937
2020-03-03 15:10:31,586 | INFO | default | [WAL] sift_50m_2048_128_l2 is flushed by lsn 219062254937
2020-03-03 15:10:31,586 | INFO | default | [WAL] Delete wal file 50
2020-03-03 15:10:31,649 | INFO | default | [WAL] record type 5 table  lsn 219062254937
2020-03-03 15:10:32,496 | INFO | default | [SERVER] Server received critical signal: 11
2020-03-03 15:10:32,496 | INFO | default | [SERVER] Call stack:
2020-03-03 15:10:32,496 | INFO | default | [SERVER] ../bin/milvus_server() [0x6057b4]
2020-03-03 15:10:32,496 | INFO | default | [SERVER] ../bin/milvus_server() [0x605ed8]
2020-03-03 15:10:32,496 | INFO | default | [SERVER] /usr/lib64/libc.so.6(+0x363b0) [0x7f40c6e653b0]
2020-03-03 15:10:32,496 | INFO | default | [SERVER] /usr/lib64/libc.so.6(+0x156426) [0x7f40c6f85426]
2020-03-03 15:10:32,496 | INFO | default | [SERVER] ../bin/milvus_server() [0x8af1b3]
2020-03-03 15:10:32,496 | INFO | default | [SERVER] ../bin/milvus_server() [0xa083e1]
2020-03-03 15:10:32,496 | INFO | default | [SERVER] ../bin/milvus_server() [0x7d45b8]
2020-03-03 15:10:32,496 | INFO | default | [SERVER] ../bin/milvus_server() [0x70d54c]
2020-03-03 15:10:32,496 | INFO | default | [SERVER] ../bin/milvus_server() [0x64c413]
2020-03-03 15:10:32,496 | INFO | default | [SERVER] ../bin/milvus_server() [0x4ae05a]
2020-03-03 15:10:32,496 | INFO | default | [SERVER] ../bin/milvus_server() [0x4a90a6]
2020-03-03 15:10:32,496 | INFO | default | [SERVER] ../bin/milvus_server() [0xedd4ff]
2020-03-03 15:10:32,496 | INFO | default | [SERVER] /usr/lib64/libpthread.so.0(+0x7e65) [0x7f40c7c39e65]
2020-03-03 15:10:32,496 | INFO | default | [SERVER] /usr/lib64/libc.so.6(clone+0x6d) [0x7f40c6f2d88d]
2020-03-03 15:10:32,540 | INFO | default | [WAL] record type 5 table  lsn 219062254937
```

**Steps/Code to reproduce behavior**
1. create table, create indxex type: ivf_sq8
2. add vectors, 100,000 vectors each time, using autoflush
3. server crashed when vectors count 13100000
```
2020-03-03:15:10:26,344 INFO     [client.py:33] Milvus insert run in 2.07s
2020-03-03:15:10:26,347 DEBUG    [runner.py:154] 12800000
2020-03-03:15:10:27,917 INFO     [runner.py:150] Start id: 13100000, end id: 13200000
2020-03-03:15:10:30,23 INFO     [client.py:33] Milvus insert run in 2.1s
2020-03-03:15:10:30,26 DEBUG    [runner.py:154] 13100000
2020-03-03:15:10:31,534 INFO     [runner.py:150] Start id: 13200000, end id: 13300000
<_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Broken pipe"
	debug_error_string = "{"created":"@1583219432.843873318","description":"Error received from peer ipv4:192.168.1.197:19513","file":"src/core/lib/surface/call.cc","file_line":1052,"grpc_message":"Broken pipe","grpc_status":14}"
>
2020-03-03:15:10:32,847 ERROR    [grpc_handler.py:594] <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Broken pipe"
	debug_error_string = "{"created":"@1583219432.843873318","description":"Error received from peer ipv4:192.168.1.197:19513","file":"src/core/lib/surface/call.cc","file_line":1052,"grpc_message":"Broken pipe","grpc_status":14}"
>
2020-03-03:15:10:32,862 ERROR    [client.py:71] Error occurred. Broken pipe
2020-03-03:15:10:32,862 INFO     [client.py:33] Milvus insert run in 1.32s
Traceback (most recent call last):
  File "main.py", line 171, in <module>
    main()
  File "main.py", line 167, in main
    runner.run(run_type, table)
  File "/home/zw/zilliz/milvus_benchmark/local_runner.py", line 45, in run
    res = self.do_insert(milvus_instance, table_name, data_type, dimension, table_size, ni_per)
  File "/home/zw/zilliz/milvus_benchmark/runner.py", line 154, in do_insert
    logger.debug(milvus.count())
  File "/home/zw/zilliz/milvus_benchmark/client.py", line 150, in count
    return self._milvus.get_table_row_count(self._table_name)[1]
  File "/usr/local/lib/python3.7/site-packages/milvus/client/stub.py", line 16, in wrapper
    raise NotConnectError('Please connect to the server first')
milvus.client.exceptions.NotConnectError: Please connect to the server first
```

**Expected behavior**

**Environment details**
using default config_server.yaml
index_type: ivf_sq8
wal enabled
index_file_size: 2048
datasets: sift-50m

```
Milvus Release version: v0.7.0, built at 2020-03-03 06:02.10, with OpenBLAS library.
You are using Milvus GPU edition
Last commit id: d460f48ce9d30ffcc09d17834272ce9855d9dadd

Loading configuration from: ../conf/server_config.yaml
Initializing log config from: ../conf/log_config.conf
S3 DISABLED !
GPU resources ENABLED !
FAISS hook AVX
Milvus server started successfully!
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 134217728 B, highwater 0 B)
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 134217728 B, highwater 134217728 B)
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 134217728 B, highwater 134217728 B)
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 134217728 B, highwater 134217728 B)
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 134217728 B, highwater 134217728 B)
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 134217728 B, highwater 134217728 B)
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 134217728 B, highwater 134217728 B)
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 134217728 B, highwater 134217728 B)
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 134217728 B, highwater 134217728 B)
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 134217728 B, highwater 134217728 B)
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 134217728 B, highwater 134217728 B)
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 134217728 B, highwater 134217728 B)
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 134217728 B, highwater 134217728 B)
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 134217728 B, highwater 134217728 B)
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 134217728 B, highwater 134217728 B)
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 134217728 B, highwater 134217728 B)
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 134217728 B, highwater 134217728 B)
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 134217728 B, highwater 134217728 B)
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 134217728 B, highwater 134217728 B)
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 134217728 B, highwater 134217728 B)
Milvus server is going to shutdown ...
```

**Screenshots**

**Additional context**

**Comment by JinHai-CN** [comment]
Call stack:
```
faiss::IndexFlat::add(long, float const*)

faiss::IndexIDMapTemplate<faiss::Index>::add_with_ids(long, float const*, long const*)

knowhere::IDMAP::AddWithoutId(std::shared_ptr<knowhere::Dataset> const&, std::shared_ptr<knowhere::Cfg> const&)

milvus::engine::BFIndex::AddWithoutIds(long const&, float const*, std::shared_ptr<knowhere::Cfg> const&)

milvus::engine::ExecutionEngineImpl::Load(bool)

milvus::scheduler::XBuildIndexTask::Load(milvus::scheduler::LoadType, unsigned char)

milvus::scheduler::Resource::loader_function()

execute_native_thread_routine
```
