### ISSUE TITLE
[Bug]: Proxy ut panic

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#15105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://github.com/milvus-io/milvus/runs/4758866227?check_suite_focus=true

```
2022-01-10T09:04:59.8263994Z [2022/01/10 09:04:59.825 +00:00] [ERROR] [service.go:166] ["DataCoord start failed"] [error="strconv.ParseInt: parsing \"channelwatch\": invalid syntax"] [stack="github.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).start\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:166\ngithub.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:214\ngithub.com/milvus-io/milvus/internal/proxy.runDataCoord.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/proxy_test.go:218"]
2022-01-10T09:04:59.8298982Z panic: strconv.ParseInt: parsing "channelwatch": invalid syntax
2022-01-10T09:04:59.8299616Z 
2022-01-10T09:04:59.8300082Z goroutine 232 [running]:
2022-01-10T09:04:59.8304724Z github.com/milvus-io/milvus/internal/proxy.runDataCoord.func1(0x3cf4601, 0x415d720, 0xc00061a3c0, 0xc0005a4dd8, 0xc0001b9b20)
2022-01-10T09:04:59.8319303Z 	/go/src/github.com/milvus-io/milvus/internal/proxy/proxy_test.go:220 +0x21c
2022-01-10T09:04:59.8345479Z created by github.com/milvus-io/milvus/internal/proxy.runDataCoord
2022-01-10T09:04:59.8346398Z 	/go/src/github.com/milvus-io/milvus/internal/proxy/proxy_test.go:207 +0x106
2022-01-10T09:04:59.8382769Z FAIL	github.com/milvus-io/milvus/internal/proxy	1.612s
```

**Comment by XuanYang-cn** [comment]
Fixed
