### ISSUE TITLE
Server crashed after search_vectors

### ISSUE THREAD

**Issue by sahuang** [milvus-io/milvus#1512]
**Describe the bug**
After calling search_vectors, server crashed and cannot reconnect.

**Steps/Code to reproduce behavior**
- Dataset: sift_50m_1024_128_l2
- Before search_vectors, connection with Milvus server is ok 
```bash
>>> milvus = get_milvus();milvus.connect(uri=uri)
Status(code=0, message='Success')
```
- call milvus.search_vectors with nq=1000, top_k=200, no return after 10 minutes
- interrupt, try connecting to milvus again and failed
```bash
>>> milvus = get_milvus();milvus.connect(uri="tcp://172.17.0.3:19530")
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 213, in connect
    grpc.channel_ready_future(self._channel).result(timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/grpc/_utilities.py", line 140, in result
    self._block(timeout)
  File "/usr/local/lib/python3.6/site-packages/grpc/_utilities.py", line 86, in _block
    raise grpc.FutureTimeoutError()
grpc.FutureTimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 58, in connect
    return self._handler.connect(host, port, uri, timeout)
  File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 217, in connect
    raise NotConnectError('Fail connecting to server on {}. Timeout'.format(self._uri))
milvus.client.exceptions.NotConnectError: Fail connecting to server on 172.17.0.3:19530. Timeout
```
- Server log:
```bash
2020-03-04 21:52:35,226 | INFO | default | [WAL] record type 5 record lsn 94040403543456 error code  0
2020-03-04 21:52:35,226 | INFO | default | [WAL] record type 5 table  lsn 0
2020-03-04 21:52:35,226 | INFO | default | [STORAGE] S3 not enabled!
2020-03-04 21:52:36,226 | INFO | default | [WAL] record type 5 table  lsn 0
2020-03-04 21:52:37,227 | INFO | default | [WAL] record type 5 table  lsn 0
2020-03-04 21:52:38,228 | INFO | default | [WAL] record type 5 table  lsn 0
......
2020-03-04 21:52:38,228 | INFO | default | [WAL] record type 5 table  lsn 0
2020-03-04 22:02:55,451 | INFO | default | [SERVER] Create new thread for request group: dql
2020-03-04 22:02:55,508 | INFO | default | [SERVER] Server received  critical signal: 11
2020-03-04 22:02:55,508 | INFO | default | [SERVER] Call stack:
2020-03-04 22:02:55,509 | INFO | default | [SERVER] ../bin/milvus_server(+0x286140) [0x55877a86e140]
2020-03-04 22:02:55,509 | INFO | default | [SERVER] ../bin/milvus_server(+0x2866f1) [0x55877a86e6f1]
2020-03-04 22:02:55,509 | INFO | default | [SERVER] /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7f0762b7cf20]
2020-03-04 22:02:55,509 | INFO | default | [SERVER] ../bin/milvus_server(+0x2d04e4) [0x55877a8b84e4]
2020-03-04 22:02:55,509 | INFO | default | [SERVER] ../bin/milvus_server(+0x147023) [0x55877a72f023]
2020-03-04 22:02:55,509 | INFO | default | [SERVER] ../bin/milvus_server(+0x1394fa) [0x55877a7214fa]
2020-03-04 22:02:55,509 | INFO | default | [SERVER] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xbd66f) [0x7f07635a266f]
2020-03-04 22:02:55,509 | INFO | default | [SERVER] /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7f07638756db]
2020-03-04 22:02:55,509 | INFO | default | [SERVER] /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f0762c5f88f]
```

**Expected behavior**
No crash

**Environment details**
- Master branch latest image (master-cpu-ubuntu18.04-release)
```bash
Milvus Release version: v0.7.0, built at 2020-03-04 13:14.43, with OpenBLAS library.
You are using Milvus CPU edition
Last commit id: fc8a6e0779a2c213834fd8edc9fe73ba2c797b7d

Loading configuration from: ../conf/server_config.yaml
Initializing log config from: ../conf/log_config.conf
S3 DISABLED !
FAISS hook AVX
Milvus server started successfully!
Milvus server is going to shutdown ...
```

**Comment by youny626** [comment]
File format changed for the new image. You need to re-insert the data.
