### ISSUE TITLE
[Bug]: segment id XXX not belong to collection id XXX

### ISSUE THREAD

**Issue by xxcheng0708** [milvus-io/milvus#15139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.0.0-pre-ga
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus v2.0.0rc9
- OS(Ubuntu or CentOS): Centos7.8
- CPU/Memory: 24C/256G
- GPU: None
- Others:
```

### Current Behavior

When I was running Milvus with two processes at the same time, one doing search and query every 5 seconds and the other doing small batches of inserts (10000 at a time) at the same time, rootcoord fell into an infinite loop. and rootcoord's log output "Segment id XXX not belong to collection Id XXX"
![微信图片_20220111100131](https://user-images.githubusercontent.com/33124611/148868371-80332a6e-09eb-4f95-869e-8054f60a8a25.png)

search and query operation:
![2022-01-11_100346](https://user-images.githubusercontent.com/33124611/148868615-111a5438-091b-40d6-ba57-4cc50516d3b0.png)

data insert operation:
![2022-01-11_100625](https://user-images.githubusercontent.com/33124611/148868720-142d0e6f-0505-4996-9304-2c95e0b36b14.png)

### Steps To Reproduce

```markdown
1、one process execute search and query every 5 seconds
2、another process execute data insert operation
```

**Comment by xxcheng0708** [comment]
logfile about rootcoord, datanode, proxy 链接：https://pan.baidu.com/s/17POvqL2OtyTMXthaM6xJpA 
提取码：txz1

**Comment by xige-16** [comment]
> logfile about rootcoord, datanode, proxy 链接：https://pan.baidu.com/s/17POvqL2OtyTMXthaM6xJpA 提取码：txz1

Could you provide the log of querycoord? @xxcheng0708

**Comment by xiaofan-luan** [comment]
hi @xxcheng0708 , thanks for your issue, we are investigating into it

**Comment by xxcheng0708** [comment]
> > logfile about rootcoord, datanode, proxy 链接：https://pan.baidu.com/s/17POvqL2OtyTMXthaM6xJpA 提取码：txz1
> 
> Could you provide the log of querycoord? @xxcheng0708

querycoord log file has updated to baidu cloud.

**Comment by xige-16** [comment]
> 

The problem may be that after compaction, datacoord failed to report a new segmentID to rootcoord. Could you please provide the log of datacoord？@xxcheng0708
```
[2022/01/11 01:25:38.345 +00:00] [DEBUG] [segment_replica.go:700] ["merge flushed segments"] ["compacted To segmentID"=430404883720175617] ["compacted From segmentIDs"="[430404878962262018,430392509501014017,430392512214204418,430404881767202818,430392506604322818,430392510942806017,430404880390946818,430404883025494018,430392508033007617,430392505857212419]"] ["partition ID"=430382968186863617] ["channel name"=by-dev-rootcoord-dml_1_430382961856023873v1]

```

**Comment by xiaofan-luan** [comment]
@sunby any idea?

**Comment by xxcheng0708** [comment]
> > 
> 
> The problem may be that after compaction, datacoord failed to report a new segmentID to rootcoord. Could you please provide the log of datacoord？@xxcheng0708
> 
> ```
> [2022/01/11 01:25:38.345 +00:00] [DEBUG] [segment_replica.go:700] ["merge flushed segments"] ["compacted To segmentID"=430404883720175617] ["compacted From segmentIDs"="[430404878962262018,430392509501014017,430392512214204418,430404881767202818,430392506604322818,430392510942806017,430404880390946818,430404883025494018,430392508033007617,430392505857212419]"] ["partition ID"=430382968186863617] ["channel name"=by-dev-rootcoord-dml_1_430382961856023873v1]
> ```
datacoord log file has updated to baidu cloud. @xige-16

**Comment by xiaofan-luan** [comment]
reasons might be compaction, @xige-16 we need better explain in the issue for bug tracing

**Comment by xige-16** [comment]
The bug should has been fixed.
/unassign
/assign @yanliang567

**Comment by yanliang567** [comment]
@xxcheng0708 could you please retry with latest master build? Also I believe you should first update the helm repo 
/assign @xxcheng0708

**Comment by yanliang567** [comment]
@ThreadDao could you also help to verify this issue?

/assign @ThreadDao 
/unassign

**Comment by ThreadDao** [comment]
Sometimes after inserting (include flush) 10 times (10000 at a time), if I insert it again, the following exception will be got:
It is worth noting that segments num 10 is the threshold of auto-compact.
```
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 539, in insert
    res = conn.bulk_insert(self._name, entities, partition_name, ids=None, timeout=timeout, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 77, in handler
    raise e
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 73, in handler
    return func(*args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 305, in bulk_insert
    raise err
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 301, in bulk_insert
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=getSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error)>
```

**Comment by ThreadDao** [comment]
If I create an index before insert and search process start, search get the following error
```
[2022-01-18 17:47:58,407 - INFO - ci_test]: start to search*** (test_insert_search_parallel.py:69)
Process Process-2:
Traceback (most recent call last):
  File "/Users/nausicca/projects/milvus/tests/python_client/scale/test_insert_search_parallel.py", line 70, in search_op
    results = collection.search(**search_param, timeout=30)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 692, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 77, in handler
    raise e
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 73, in handler
    return func(*args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 21, in handler
    return func(self, *args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 442, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 77, in handler
    raise e
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 73, in handler
    return func(*args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 391, in _execute_search_requests
    raise pre_err
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 382, in _execute_search_requests
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=no Available QueryNode result, filter reason [UnexpectedError] Assert "adapter->CheckSearch(conf, index_type, field_indexing->indexing_->index_mode())" at /go/src/github.com/milvus-io/milvus/internal/core/src/query/SearchOnSealed.cpp:99
 => [SearchOnSealed]Search params check failed
: id 430571320939390784)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/nausicca/projects/milvus/tests/python_client/scale/test_insert_search_parallel.py", line 84, in search_op
    raise Exception(str(e))
Exception: <BaseException: (code=1, message=no Available QueryNode result, filter reason [UnexpectedError] Assert "adapter->CheckSearch(conf, index_type, field_indexing->indexing_->index_mode())" at /go/src/github.com/milvus-io/milvus/internal/core/src/query/SearchOnSealed.cpp:99
 => [SearchOnSealed]Search params check failed
: id 430571320939390784)>
[2022-01-18 17:48:06,917 - INFO - ci_test]: (insert count: 10000, delete count: 0, upsert count: 0, timestamp: 430571332801396737) (test_insert_search_parallel.py:50)
[2022-01-18 17:48:09,606 - INFO - ci_test]: 20000 (test_insert_search_parallel.py:54)
[2022-01-18 17:48:09,609 - INFO - ci_test]: 1 finish. (test_insert_search_parallel.py:56)
[2022-01-18 17:48:09,612 - 
```

**Comment by yanliang567** [comment]
@xige-16 could you please help to check this issue

**Comment by xige-16** [comment]
> @xige-16 could you please help to check this issue

ok

**Comment by xige-16** [comment]
> ```python
>      search_param = {
>                     "data": [[random.random() for _ in range(dim)] for _ in range(5)],
>                     "anns_field": "embeedings",
>                     "param": {"metric_type": "L2"},
>                     "limit": 2}
> ```

The format of search params is not correct. Missing nprobe in Param.  link: https://milvus.io/docs/v2.0.0/search.md?cli#Prepare-search-parameters
```
    search_param = {
                "data": [[random.random() for _ in range(dim)] for _ in range(5)],
                "anns_field": "embeedings",
                "param": {"metric_type": "L2", "params": {"nprobe": 10}},
                "limit": 2}
```

**Comment by xige-16** [comment]
@ThreadDao 
/unassign 
/assign @ThreadDao

**Comment by ThreadDao** [comment]
It's hard for me to realize that my parameters are wrong with this terrible exception message!

**Comment by xige-16** [comment]
> It's hard for me to realize that my parameters are wrong with this terrible exception message!

After GA, we will optimize the return value.

**Comment by ThreadDao** [comment]
After updating search params, I re-run the scripts mentioned above with image `master-20220120-c132302` and passed. I think it is fixed. @xxcheng0708 Maybe you can update the milvus version. I will close it first and you can reopen the issue with more details.
