### ISSUE TITLE
[Bug]: [CI] Connect get TypeError: __init__() missing 1 required positional argument: 'message'

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#15236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.0.0rc10.dev6
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-15226/2/pipeline
```
=================================== FAILURES ===================================

[2022-01-15T01:58:56.212Z] ___ TestCollectionSearch.test_search_with_dup_primary_key[128-True-False-3] ____

[2022-01-15T01:58:56.212Z] [gw0] linux -- Python 3.6.8 /usr/local/bin/python3

[2022-01-15T01:58:56.212Z] [gw0] linux -- Python 3.6.8 /usr/local/bin/python3[gw0] linux -- Python 3.6.8 /usr/local/bin/python3

[2022-01-15T01:58:56.212Z] 

[2022-01-15T01:58:56.212Z] self = <test_search_20.TestCollectionSearch object at 0x7fe4c93ee208>, dim = 128

[2022-01-15T01:58:56.212Z] auto_id = True, _async = False, dup_times = 3

[2022-01-15T01:58:56.212Z] 

[2022-01-15T01:58:56.212Z]     @pytest.mark.tags(CaseLabel.L1)

[2022-01-15T01:58:56.212Z]     @pytest.mark.parametrize("dup_times", [1, 2, 3])

[2022-01-15T01:58:56.212Z]     def test_search_with_dup_primary_key(self, dim, auto_id, _async, dup_times):

[2022-01-15T01:58:56.212Z]         """

[2022-01-15T01:58:56.212Z]         target: test search with duplicate primary key

[2022-01-15T01:58:56.212Z]         method: 1.insert same data twice

[2022-01-15T01:58:56.212Z]                 2.search

[2022-01-15T01:58:56.212Z]         expected: search results are de-duplicated

[2022-01-15T01:58:56.212Z]         """

[2022-01-15T01:58:56.212Z]         # initialize with data

[2022-01-15T01:58:56.212Z]         nb = ct.default_nb

[2022-01-15T01:58:56.212Z]         nq = ct.default_nq

[2022-01-15T01:58:56.212Z]         collection_w, insert_data, _, insert_ids = self.init_collection_general(prefix, True, nb,

[2022-01-15T01:58:56.212Z]                                                                                 auto_id=auto_id,

[2022-01-15T01:58:56.212Z] >                                                                               dim=dim)[0:4]

[2022-01-15T01:58:56.212Z] 

[2022-01-15T01:58:56.212Z] testcases/test_search_20.py:889: 

[2022-01-15T01:58:56.212Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

[2022-01-15T01:58:56.212Z] base/client_base.py:150: in init_collection_general

[2022-01-15T01:58:56.212Z]     self._connect()

[2022-01-15T01:58:56.212Z] base/client_base.py:104: in _connect

[2022-01-15T01:58:56.212Z]     port=param_info.param_port)

[2022-01-15T01:58:56.212Z] base/connections_wrapper.py:35: in connect

[2022-01-15T01:58:56.212Z]     check_result = ResponseChecker(response, func_name, check_task, check_items, succ, alias=alias, **kwargs).run()

[2022-01-15T01:58:56.212Z] check/func_check.py:31: in run

[2022-01-15T01:58:56.212Z]     result = self.assert_succ(self.succ, True)

[2022-01-15T01:58:56.212Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

[2022-01-15T01:58:56.212Z] 

[2022-01-15T01:58:56.212Z] actual = False, expect = True

[2022-01-15T01:58:56.212Z] 

[2022-01-15T01:58:56.212Z]     @staticmethod

[2022-01-15T01:58:56.212Z]     def assert_succ(actual, expect):

[2022-01-15T01:58:56.213Z] >       assert actual is expect

[2022-01-15T01:58:56.213Z] E       AssertionError

[2022-01-15T01:58:56.213Z] 

[2022-01-15T01:58:56.213Z] check/func_check.py:73: AssertionError

[2022-01-15T01:58:56.213Z] ------------------------------ Captured log setup ------------------------------

[2022-01-15T01:58:56.213Z] [2022-01-15 01:58:42 - INFO - ci_test]: *********************************** setup *********************************** (client_base.py:51)

[2022-01-15T01:58:56.213Z] [2022-01-15 01:58:42 - INFO - ci_test]: [setup_method] Start setup test case test_search_with_dup_primary_key. (client_base.py:52)

[2022-01-15T01:58:56.213Z] ------------------------------ Captured log call -------------------------------

[2022-01-15T01:58:56.213Z] [2022-01-15 01:58:42 - INFO - ci_test]: Test case of search interface: initialize before test case (client_base.py:149)

[2022-01-15T01:58:56.213Z] [2022-01-15 01:58:42 - DEBUG - ci_test]: (api_request)  : [Connections.connect] args: ['default'], kwargs: {'host': 'ms-15226-2-pr-milvus.milvus-ci', 'port': '19530'} (api_request.py:55)

[2022-01-15T01:58:56.213Z] [2022-01-15 01:58:45 - ERROR - ci_test]: Traceback (most recent call last):

[2022-01-15T01:58:56.213Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 90, in _wait_for_channel_ready

[2022-01-15T01:58:56.213Z]     grpc.channel_ready_future(self._channel).result(timeout=3)

[2022-01-15T01:58:56.213Z]   File "/usr/local/lib/python3.6/site-packages/grpc/_utilities.py", line 140, in result

[2022-01-15T01:58:56.213Z]     self._block(timeout)

[2022-01-15T01:58:56.213Z]   File "/usr/local/lib/python3.6/site-packages/grpc/_utilities.py", line 86, in _block

[2022-01-15T01:58:56.213Z]     raise grpc.FutureTimeoutError()

[2022-01-15T01:58:56.213Z] grpc.FutureTimeoutError

[2022-01-15T01:58:56.213Z] 

[2022-01-15T01:58:56.213Z] During handling of the above exception, another exception occurred:

[2022-01-15T01:58:56.213Z] 

[2022-01-15T01:58:56.213Z] Traceback (most recent call last):

[2022-01-15T01:58:56.213Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper

[2022-01-15T01:58:56.213Z]     res = func(*args, **kwargs)

[2022-01-15T01:58:56.213Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 56, in api_request

[2022-01-15T01:58:56.213Z]     return func(*arg, **kwargs)

[2022-01-15T01:58:56.213Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/connections.py", line 156, in connect

[2022-01-15T01:58:56.213Z]     conn = connect_milvus(**kwargs)

[2022-01-15T01:58:56.213Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/connections.py", line 144, in connect_milvus

[2022-01-15T01:58:56.213Z]     gh._wait_for_channel_ready()

[2022-01-15T01:58:56.213Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 93, in _wait_for_channel_ready

[2022-01-15T01:58:56.213Z]     raise BaseException(f'Fail connecting to server on {self._uri}. Timeout')

[2022-01-15T01:58:56.213Z] TypeError: __init__() missing 1 required positional argument: 'message'

[2022-01-15T01:58:56.213Z]  (api_request.py:35)

[2022-01-15T01:58:56.213Z] [2022-01-15 01:58:45 - ERROR - ci_test]: (api_response) : __init__() missing 1 required positional argument: 'message' (api_request.py:36)
```

**Comment by yanliang567** [comment]
@XuanYang-cn looks like a pymilvus issue, please help
/unassign

**Comment by binbinlv** [comment]
Fixed, and closed.
