### ISSUE TITLE
[Bug]: [chaos] The querynode will be OOMKilled when load collection with insufficient memory

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#15379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220124-390cdd2
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: limit memory 1Gi
- GPU: 
- Others:
```

### Current Behavior

1. Deploy milvus cluster with querynode memory limit 1Gi
2. Load collection num_entities 300000, dim 512
3. Client get the following exception, and I suggest replacing the collection id with collection name.
```
[2022-01-25 06:58:55 - ERROR - pymilvus.decorators]: Error: <BaseException: (code=1, message=collection 430723517098691905 has not been loaded to memory or load failed)> (decorators.py:75)
[2022-01-25 06:58:55 - ERROR - ci_test]: Traceback (most recent call last):
  File "/workspace/milvus/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
    res = func(*args, **kwargs)
  File "/workspace/milvus/tests/python_client/utils/api_request.py", line 56, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 458, in load
    conn.load_collection(self._name, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 77, in handler
    raise e
  File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 73, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 656, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 77, in handler
    raise e
  File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 73, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 676, in wait_for_loading_collection
    return self._wait_for_loading_collection_v2(collection_name, timeout)
  File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 700, in _wait_for_loading_collection_v2
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=collection 430723517098691905 has not been loaded to memory or load failed)>
 (api_request.py:35)
```
4. The server querynode is OOMKilled due to OOMKilled
```
mic-memory-milvus-querynode-657644cc5b-v2579                  0/1     OOMKilled                    5          32m
```
[querynode.log](https://github.com/milvus-io/milvus/files/7931406/querynode.log)
[querynode2.log](https://github.com/milvus-io/milvus/files/7931407/querynode2.log)

But according to the grafana monitor the memory usage is very small: 
If load successfully memory usage is about 1.2Gi. So I guess querycoord thinks memory is enough but it's not.
![image](https://user-images.githubusercontent.com/27288593/150930859-1ff02377-8148-4131-a434-0d154ba239ec.png)

### Expected Behavior

1. Estimate the required memory as close to reality as possible
2. Replace collection id with collection name in client load failed exception
3. If the estimated memory is not enough to load, an exception will be returned and querynode will not be OOMKilled

**Comment by xiaofan-luan** [comment]
so far the estimation is not accurate. This is a big trouble but we don't have good support at knowhere side.
We'll leave this issue here until we have better solution
