### ISSUE TITLE
[Bug]: [chaos][standalone]search raise error when running hello_milvus.py after standalone pod recovered from pod kill

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#15374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220124-3a02430
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus-2.0.0rc10.dev11
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Run hello_milvus after chaos
```
[2022-01-25T02:36:59.273Z] Search...

[2022-01-25T02:36:59.273Z] Traceback (most recent call last):

[2022-01-25T02:36:59.273Z]   File "scripts/hello_milvus.py", line 113, in <module>

[2022-01-25T02:36:59.273Z]     hello_milvus(args.host)

[2022-01-25T02:36:59.273Z]   File "scripts/hello_milvus.py", line 88, in hello_milvus

[2022-01-25T02:36:59.273Z]     "count > 100", output_fields=["count", "random_value"], timeout=TIMEOUT

[2022-01-25T02:36:59.273Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 700, in search

[2022-01-25T02:36:59.273Z]     partition_names, output_fields, timeout, round_decimal, **kwargs)

[2022-01-25T02:36:59.273Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 49, in handler

[2022-01-25T02:36:59.273Z]     raise e

[2022-01-25T02:36:59.273Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 41, in handler

[2022-01-25T02:36:59.273Z]     return func(self, *args, **kwargs)

[2022-01-25T02:36:59.273Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 77, in handler

[2022-01-25T02:36:59.273Z]     raise e

[2022-01-25T02:36:59.273Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 73, in handler

[2022-01-25T02:36:59.273Z]     return func(*args, **kwargs)

[2022-01-25T02:36:59.273Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 21, in handler

[2022-01-25T02:36:59.273Z]     return func(self, *args, **kwargs)

[2022-01-25T02:36:59.273Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 444, in search

[2022-01-25T02:36:59.273Z]     return self._execute_search_requests(requests, timeout, **_kwargs)

[2022-01-25T02:36:59.273Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 77, in handler

[2022-01-25T02:36:59.273Z]     raise e

[2022-01-25T02:36:59.273Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 73, in handler

[2022-01-25T02:36:59.273Z]     return func(*args, **kwargs)

[2022-01-25T02:36:59.273Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 391, in _execute_search_requests

[2022-01-25T02:36:59.273Z]     raise pre_err

[2022-01-25T02:36:59.273Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 379, in _execute_search_requests

[2022-01-25T02:36:59.273Z]     response = ft.result()

[2022-01-25T02:36:59.273Z]   File "/usr/local/lib/python3.7/dist-packages/grpc/_channel.py", line 744, in result

[2022-01-25T02:36:59.273Z]     raise self

[2022-01-25T02:36:59.273Z] grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:

[2022-01-25T02:36:59.273Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2022-01-25T02:36:59.273Z] 	details = "Deadline Exceeded"

[2022-01-25T02:36:59.273Z] 	debug_error_string = "{"created":"@1643078218.537869772","description":"Error received from peer ipv4:10.96.18.117:19530","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Deadline Exceeded","grpc_status":4}"
```

### Expected Behavior

All work well

### Steps To Reproduce

```markdown
re-run pipline http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/302/pipeline/
```

### Anything else?

[artifacts-test-standalone-pod-kill-302-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/7930261/artifacts-test-standalone-pod-kill-302-pytest-logs.tar.gz)
[artifacts-test-standalone-pod-kill-302-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/7930263/artifacts-test-standalone-pod-kill-302-server-logs.1.tar.gz)

**Comment by yanliang567** [comment]
@xige-16 please take a look at this issue.
/assign @xige-16 
/unassign

**Comment by zhuwenxing** [comment]
```
[2022/01/25 02:35:16.885 +00:00] [ERROR] [root_coord.go:1389] ["DescribeCollection failed"] [role=rootcoord] ["collection name"=] [msgID=0] [error="can't find collection id : 430722919429508417"] [stack="github.com/milvus-io/milvus/internal/rootcoord.(*Core).DescribeCollection\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:1389\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).DescribeCollection\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:354\ngithub.com/milvus-io/milvus/internal/proto/rootcoordpb._RootCoord_DescribeCollection_Handler.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proto/rootcoordpb/root_coord.pb.go:915\ngithub.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38\ngithub.com/milvus-io/milvus/internal/proto/rootcoordpb._RootCoord_DescribeCollection_Handler\n\t/go/src/github.com/milvus-io/milvus/internal/proto/rootcoordpb/root_coord.pb.go:917\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1286\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1609\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:934"]
[2022/01/25 02:35:16.885 +00:00] [ERROR] [root_coord.go:1389] ["DescribeCollection failed"] [role=rootcoord] ["collection name"=] [msgID=0] [error="can't find collection id : 430722919429508417"] [stack="github.com/milvus-io/milvus/internal/rootcoord.(*Core).DescribeCollection\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:1389\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).DescribeCollection\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:354\ngithub.com/milvus-io/milvus/internal/proto/rootcoordpb._RootCoord_DescribeCollection_Handler.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proto/rootcoordpb/root_coord.pb.go:915\ngithub.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38\ngithub.com/milvus-io/milvus/internal/proto/rootcoordpb._RootCoord_DescribeCollection_Handler\n\t/go/src/github.com/milvus-io/milvus/internal/proto/rootcoordpb/root_coord.pb.go:917\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1286\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1609\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:934"]
[2022/01/25 02:35:16.885 +00:00] [ERROR] [segment_replica.go:660] ["Grpc error"] [error="describe collection 430722919429508417 from rootcoord wrong: DescribeCollection failed: can't find collection id : 430722919429508417"] [stack="github.com/milvus-io/milvus/internal/datanode.(*SegmentReplica).getCollectionSchema\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/segment_replica.go:660\ngithub.com/milvus-io/milvus/internal/datanode.(*SegmentReplica).initPKBloomFilter\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/segment_replica.go:417\ngithub.com/milvus-io/milvus/internal/datanode.(*SegmentReplica).addFlushedSegment\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/segment_replica.go:398\ngithub.com/milvus-io/milvus/internal/datanode.(*dataSyncService).initNodes\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/data_sync_service.go:191\ngithub.com/milvus-io/milvus/internal/datanode.newDataSyncService\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/data_sync_service.go:88\ngithub.com/milvus-io/milvus/internal/datanode.(*flowgraphManager).addAndStart\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_manager.go:57\ngithub.com/milvus-io/milvus/internal/datanode.(*DataNode).handlePutEvent\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/data_node.go:374\ngithub.com/milvus-io/milvus/internal/datanode.(*channelEventManager).Run.func1\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:77"]
[2022/01/25 02:35:16.885 +00:00] [WARN] [flow_graph_manager.go:59] ["new data sync service fail"] [vChannelName=by-dev-rootcoord-dml_0_430722919429508417v0] [error="describe collection 430722919429508417 from rootcoord wrong: DescribeCollection failed: can't find collection id : 430722919429508417"]
[2022/01/25 02:35:16.885 +00:00] [WARN] [event_manager.go:58] ["handle put event fail, starting retry"] [vChanName=by-dev-rootcoord-dml_0_430722919429508417v0] ["retry interval"=20s] [error="fail to add and start flowgraph for vChanName: by-dev-rootcoord-dml_0_430722919429508417v0, err: describe collection 430722919429508417 from rootcoord wrong: DescribeCollection failed: can't find collection id : 430722919429508417"]
[2022/01/25 02:35:16.885 +00:00] [ERROR] [segment_replica.go:660] ["Grpc error"] [error="describe collection 430722919429508417 from rootcoord wrong: DescribeCollection failed: can't find collection id : 430722919429508417"] [stack="github.com/milvus-io/milvus/internal/datanode.(*SegmentReplica).getCollectionSchema\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/segment_replica.go:660\ngithub.com/milvus-io/milvus/internal/datanode.(*SegmentReplica).initPKBloomFilter\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/segment_replica.go:417\ngithub.com/milvus-io/milvus/internal/datanode.(*SegmentReplica).addFlushedSegment\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/segment_replica.go:398\ngithub.com/milvus-io/milvus/internal/datanode.(*dataSyncService).initNodes\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/data_sync_service.go:191\ngithub.com/milvus-io/milvus/internal/datanode.newDataSyncService\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/data_sync_service.go:88\ngithub.com/milvus-io/milvus/internal/datanode.(*flowgraphManager).addAndStart\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_manager.go:57\ngithub.com/milvus-io/milvus/internal/datanode.(*DataNode).handlePutEvent\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/data_node.go:374\ngithub.com/milvus-io/milvus/internal/datanode.(*channelEventManager).Run.func1\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:77"]
[2022/01/25 02:35:16.885 +00:00] [WARN] [flow_graph_manager.go:59] ["new data sync service fail"] [vChannelName=by-dev-rootcoord-dml_1_430722919429508417v1] [error="describe collection 430722919429508417 from rootcoord wrong: DescribeCollection failed: can't find collection id : 430722919429508417"]
[2022/01/25 02:35:16.885 +00:00] [WARN] [event_manager.go:58] ["handle put event fail, starting retry"] [vChanName=by-dev-rootcoord-dml_1_430722919429508417v1] ["retry interval"=20s] [error="fail to add and start flowgraph for vChanName: by-dev-rootcoord-dml_1_430722919429508417v1, err: describe collection 430722919429508417 from rootcoord wrong: DescribeCollection failed: can't find collection id : 430722919429508417"]
[2022/01/25 02:35:17.885 +00:00] [DEBUG] [flow_graph_manager.go:38] ["received Vchannel Info"] [vChannelName=by-dev-rootcoord-dml_1_430722919429508417v1] ["Unflushed Segment Number"=0] ["Flushed Segment Number"=2]
[2022/01/25 02:35:17.885 +00:00] [DEBUG] [flow_graph_manager.go:38] ["received Vchannel Info"] [vChannelName=by-dev-rootcoord-dml_0_430722919429508417v0] ["Unflushed Segment Number"=0] ["Flushed Segment Number"=2]
[2022/01/25 02:35:17.890 +00:00] [DEBUG] [minio_kv.go:92] ["MinioKV new MinioKV success."]
```

**Comment by xige-16** [comment]
> 

It's log of datanode, not querynode

**Comment by zhuwenxing** [comment]
> > 
> 
> It's log of datanode, not querynode

All log was in one pod. I just  put the error log there.
You can access all log in https://github.com/milvus-io/milvus/files/7930263/artifacts-test-standalone-pod-kill-302-server-logs.1.tar.gz

**Comment by xige-16** [comment]
> 

What I mean is that there is also a problem with the datanode log. The datanode has been retrying to create a flowgraph with collection=430722919429508417, but rootcoord no longer has this collectionID, resulting in a failure to create a flowgraph.

**Comment by xige-16** [comment]
> > 
> 
> What I mean is that there is also a problem with the datanode log. The datanode has been retrying to create a flowgraph with collection=430722919429508417, but rootcoord no longer has this collectionID, resulting in a failure to create a flowgraph.

@XuanYang-cn Could you help check it out?

**Comment by xige-16** [comment]
There's also the issue of search timing out, which I'm still investigating.

**Comment by congqixia** [comment]
> > 
> 
> What I mean is that there is also a problem with the datanode log. The datanode has been retrying to create a flowgraph with collection=430722919429508417, but rootcoord no longer has this collectionID, resulting in a failure to create a flowgraph.

`430722919429508417` is not the collection id of `hello_milvus` so it shall not block the operations of `hello_milvus`

**Comment by xige-16** [comment]
> There's also the issue of search timing out, which I'm still investigating.

when querycoord restart and reload loadbalancetask (triggered by querynode down), it  did not correctly set the task's trigger condition. And when the loadbalancetask was executed, there was no querynode online. So  the task failed to execute and did not retry, then some data was not successfully recovered after node down.

**Comment by zhuwenxing** [comment]
It not reproduced yet, so remove the urgent label
