### ISSUE TITLE
[Bug]: [benchmark][standalone] search raise error proxy not healthy

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#15392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220125-9771059
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc10.dev14
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

client pod: benchmark-cluster-cron-1643144400-2659037415

client log:
```
[2022-01-25 22:19:35,553] [    INFO] - {'nq': 1200, 'topk': 1000, 'search_param': {'nprobe': 32}, 'filter': [{'range': {'float1': {'GT': -1.0, 'LT': 5000000.0}}}], 'guarantee_timestamp': None} (milvus_benchmark.runners.search:286)
[2022-01-25 22:19:40,083] [   ERROR] - RPC error: _execute_search_requests{'RPC start': '2022-01-25 22:19:35.605754', 'RPC error': '2022-01-25 22:19:40.083220'} (pymilvus.decorators:81)
[2022-01-25 22:19:40,084] [   ERROR] - RPC error: search{'RPC start': '2022-01-25 22:19:35.554539', 'RPC error': '2022-01-25 22:19:40.084421'} (pymilvus.decorators:81)
[2022-01-25 22:19:45,721] [   ERROR] - RPC error: [has_collection], <BaseException: (code=1, message=proxy not healthy)>, <Time:{'RPC start': '2022-01-25 22:19:41.087069', 'RPC error': '2022-01-25 22:19:45.721120'}> (pymilvus.decorators:73)
[2022-01-25 22:19:45,722] [   ERROR] - RPC error: [search], <BaseException: (code=1, message=proxy not healthy)>, <Time:{'RPC start': '2022-01-25 22:19:41.087028', 'RPC error': '2022-01-25 22:19:45.722166'}> (pymilvus.decorators:73)
[2022-01-25 22:19:45,725] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 95, in run_suite
    result = runner.run_case(case_metric, **case)
  File "/src/milvus_benchmark/runners/search.py", line 289, in run_case
    guarantee_timestamp=case_param["guarantee_timestamp"])
  File "/src/milvus_benchmark/client.py", line 49, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 322, in query
    result = self._milvus.search(tmp_collection_name, **params)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 829, in search
    partition_names, output_fields, timeout, round_decimal, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 18, in handler
    if not self.has_collection(collection_name):
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 156, in has_collection
    raise BaseException(reply.status.error_code, reply.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=proxy not healthy)>
 (milvus_benchmark.main:98)
[2022-01-25 22:19:45,725] [    INFO] - None (milvus_benchmark.main:99)
[2022-01-25 22:19:45,726] [   DEBUG] - {'type': 'insert_search_performance', 'value': {}} (milvus_benchmark.main:107)
[2022-01-25 22:19:45,726] [   DEBUG] - {'_version': '0.1', '_type': 'case', 'run_id': 1643148917, 'mode': 'local', 'server': <milvus_benchmark.metrics.models.server.Server object at 0x7fdf55ff93c8>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware object at 0x7fdf55ff9438>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7fdf55ff94a8>, 'status': 'RUN_FAILED', 'err_message': '<BaseException: (code=1, message=proxy not healthy)>\nTraceback (most recent call last):\n  File "main.py", line 95, in run_suite\n    result = runner.run_case(case_metric, **case)\n  File "/src/milvus_benchmark/runners/search.py", line 289, in run_case\n    guarantee_timestamp=case_param["guarantee_timestamp"])\n  File "/src/milvus_benchmark/client.py", line 49, in wrapper\n    result = func(*args, **kwargs)\n  File "/src/milvus_benchmark/client.py", line 322, in query\n    result = self._milvus.search(tmp_collection_name, **params)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 829, in search\n    partition_names, output_fields, timeout, round_decimal, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 56, in handler\n    raise e\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 41, in handler\n    return func(self, *args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler\n    raise e\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler\n    return func(*args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 18, in handler\n    if not self.has_collection(collection_name):\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 56, in handler\n    raise e\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 41, in handler\n    return func(self, *args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler\n    raise e\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler\n    return func(*args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 156, in has_collection\n    raise BaseException(reply.status.error_code, reply.status.reason)\npymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=proxy not healthy)>\n', 'collection': {'dimension': 128, 'metric_type': 'l2', 'dataset_name': 'sift_50m_128_l2', 'fields': None, 'shards_num': None}, 'index': {'index_type': 'ivf_flat', 'index_param': {'nlist': 2048}}, 'search': {'nq': 1200, 'topk': 1000, 'search_param': {'nprobe': 32}, 'filter': [{'range': {'float1': {'GT': -1.0, 'LT': 5000000.0}}}], 'guarantee_timestamp': None}, 'run_params': None, 'metrics': {'type': 'insert_search_performance', 'value': {}}, 'datetime': '2022-01-25 21:03:45.026547', 'type': 'metric'} (milvus_benchmark.metric.api:29)
[2022-01-25 22:19:45,735] [   DEBUG] - Start run query, run 1 of 2 (milvus_benchmark.runners.search:285)
[2022-01-25 22:19:45,736] [    INFO] - {'nq': 1, 'topk': 1, 'search_param': {'nprobe': 32}, 'filter': [{'range': {'float1': {'GT': -1.0, 'LT': 25000000.0}}}], 'guarantee_timestamp': None} (milvus_benchmark.runners.search:286)
[2022-01-25 22:19:45,737] [   ERROR] - RPC error: [has_collection], <BaseException: (code=1, message=proxy not healthy)>, <Time:{'RPC start': '2022-01-25 22:19:45.736725', 'RPC error': '2022-01-25 22:19:45.737724'}> (pymilvus.decorators:73)
[2022-01-25 22:19:45,738] [   ERROR] - RPC error: [search], <BaseException: (code=1, message=proxy not healthy)>, <Time:{'RPC start': '2022-01-25 22:19:45.736711', 'RPC error': '2022-01-25 22:19:45.738248'}> (pymilvus.decorators:73)
[2022-01-25 22:19:45,739] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 95, in run_suite
    result = runner.run_case(case_metric, **case)
  File "/src/milvus_benchmark/runners/search.py", line 289, in run_case
    guarantee_timestamp=case_param["guarantee_timestamp"])
  File "/src/milvus_benchmark/client.py", line 49, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 322, in query
    result = self._milvus.search(tmp_collection_name, **params)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 829, in search
    partition_names, output_fields, timeout, round_decimal, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 18, in handler
    if not self.has_collection(collection_name):
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 156, in has_collection
    raise BaseException(reply.status.error_code, reply.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=proxy not healthy)>
 (milvus_benchmark.main:98)
```

### Expected Behavior

argo task: benchmark-cluster-cron-1643144400

test yaml:
client-configmap:client-search-filter-sift50m-ivf-flat-2048,instanceId:5,server-configmap:server-single-16c64m

server:
```
NAME                                                              READY   STATUS      RESTARTS   AGE    IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-cluster-cron-1643144400-5-etcd-0                        1/1     Running     0          135m   10.97.16.73    qa-node013.zilliz.local   <none>           <none>
benchmark-cluster-cron-1643144400-5-milvus-standalone-6694zwbbd   1/1     Running     1          135m   10.97.20.7     qa-node018.zilliz.local   <none>           <none>
benchmark-cluster-cron-1643144400-5-minio-6d948f88d6-cl2mk        1/1     Running     0          135m   10.97.16.57    qa-node013.zilliz.local   <none>           <none>
```

### Steps To Reproduce

```markdown
1、create collection
2、create index of ivf_flat
3、insert 50 million vectors
4、flush collection
5、build index with the same params
6、load collection
7、search with parmas <- raise error
```

### Anything else?

client-search-filter-sift50m-ivf-flat-2048:
```
insert_search_performance:
      collections:
        -
          collection_name: sift_50m_128_l2
          ni_per: 50000
          other_fields: int1,int2,float1,double1
          build_index: true
          index_type: ivf_flat 
          index_param:
            nlist: 2048
          run_count: 2
          top_ks: [1, 10, 100, 1000]
          nqs: [1, 10, 100, 200, 500, 1000, 1200]
          filters:
            -
              range: "{'range': {'float1': {'GT': -1.0, 'LT': collection_size * 0.1}}}"
            -
              range: "{'range': {'float1': {'GT': -1.0, 'LT': collection_size * 0.5}}}"
            -
              range: "{'range': {'float1': {'GT': -1.0, 'LT': collection_size * 0.9}}}"
          search_params:
            -
              nprobe: 8
            -
              nprobe: 32

```

**Comment by yanliang567** [comment]
@xige-16 could you please help to take a look?
/assign @xige-16 
/unassign

**Comment by wangting0128** [comment]
argo task: benchmark-cluster-cron-1643230800

test yaml:
client-configmap:client-search-filter-sift50m-ivf-flat-2048,instanceId:5,server-configmap:server-single-16c64m

server:
```
NAME                                                              READY   STATUS      RESTARTS   AGE     IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-cluster-cron-1643230800-5-etcd-0                        1/1     Running     0          3h27m   10.97.16.43    qa-node013.zilliz.local   <none>           <none>
benchmark-cluster-cron-1643230800-5-milvus-standalone-5856k265h   1/1     Running     1          3h27m   10.97.20.32    qa-node018.zilliz.local   <none>           <none>
benchmark-cluster-cron-1643230800-5-minio-69766c7658-xd4vg        1/1     Running     0          3h27m   10.97.12.50    qa-node015.zilliz.local   <none>           <none>
```

client pod: benchmark-cluster-cron-1643230800-2342631029

client log:
```
[2022-01-26 22:37:13,554] [   ERROR] - RPC error: _execute_search_requests{'RPC start': '2022-01-26 22:36:55.558668', 'RPC error': '2022-01-26 22:37:13.554806'} (pymilvus.decorators:81)
[2022-01-26 22:37:13,556] [   ERROR] - RPC error: search{'RPC start': '2022-01-26 22:36:55.486501', 'RPC error': '2022-01-26 22:37:13.556053'} (pymilvus.decorators:81)
[2022-01-26 22:37:19,620] [   ERROR] - RPC error: [has_collection], <BaseException: (code=1, message=proxy not healthy)>, <Time:{'RPC start': '2022-01-26 22:37:14.558082', 'RPC error': '2022-01-26 22:37:19.620243'}> (pymilvus.decorators:73)
[2022-01-26 22:37:19,621] [   ERROR] - RPC error: [search], <BaseException: (code=1, message=proxy not healthy)>, <Time:{'RPC start': '2022-01-26 22:37:14.557994', 'RPC error': '2022-01-26 22:37:19.621394'}> (pymilvus.decorators:73)
[2022-01-26 22:37:19,626] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 95, in run_suite
    result = runner.run_case(case_metric, **case)
  File "/src/milvus_benchmark/runners/search.py", line 289, in run_case
    guarantee_timestamp=case_param["guarantee_timestamp"])
  File "/src/milvus_benchmark/client.py", line 49, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 322, in query
    result = self._milvus.search(tmp_collection_name, **params)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 829, in search
    partition_names, output_fields, timeout, round_decimal, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 18, in handler
    if not self.has_collection(collection_name):
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 156, in has_collection
    raise BaseException(reply.status.error_code, reply.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=proxy not healthy)>
 (milvus_benchmark.main:98)
```
