### ISSUE TITLE
[Bug]: Confusing exception message when searching with invalid parameters

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#15394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220125-6336e232
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Create hnsw index with `hnsw_index = {"index_type": "HNSW", "metric_type": "L2", "params": {"M": 48, "efConstruction": 64}}`
Search with invalid topk than less than ef:
```
[2022-01-26 12:00:39,430 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.07615927191418291, 0.12515280077280577, 0.04696407650548569, 0.05155591708707009, 0.08213173517661698, 0.11194120616099103, 0.019084058983515256, 0.1034841966396711, 0.05535563438952159, 0.08587730290790677, 0.05104304311098882, 0.006464468411336797, 0.051044307127992274, 0.02112441908934027, 0......, kwargs: {} (api_request.py:55)
[2022-01-26 12:00:39,660 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/nausicca/projects/milvus/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
    res = func(*args, **kwargs)
  File "/Users/nausicca/projects/milvus/tests/python_client/utils/api_request.py", line 56, in api_request
    return func(*arg, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 699, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 77, in handler
    raise e
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 73, in handler
    return func(*args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 21, in handler
    return func(self, *args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 444, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 77, in handler
    raise e
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 73, in handler
    return func(*args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 391, in _execute_search_requests
    raise pre_err
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 382, in _execute_search_requests
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=no Available QueryNode result, filter reason [UnexpectedError] Assert "adapter->CheckSearch(conf, index_type, field_indexing->indexing_->index_mode())" at /go/src/github.com/milvus-io/milvus/internal/core/src/query/SearchOnSealed.cpp:91
 => [SearchOnSealed]Search params check failed
: id 430747041004796612)>
 (api_request.py:35)
```

### Steps To Reproduce

```markdown
from base.client_base import TestcaseBase
from common import common_func as cf
from common import common_type as ct
from utils.util_log import test_log as log

default_schema = cf.gen_default_collection_schema()
default_search_field = ct.default_float_vec_field_name
default_field_name = ct.default_float_vec_field_name
hnsw_index = {"index_type": "HNSW", "metric_type": "L2", "params": {"M": 48, "efConstruction": 64}}
search_params = {"metric_type": "L2", "params": {"ef": 20}}


class TestHnsw(TestcaseBase):
    def test_hnsw_index(self):
        c_name = cf.gen_unique_str('hnsw')
        collection_w = self.init_collection_wrap(name=c_name)
        for i in range(5):
            df = cf.gen_default_dataframe_data(nb=3000)
            collection_w.insert(df)
        log.info(collection_w.num_entities)

        self.index_wrap.init_index(collection_w.collection, default_field_name, hnsw_index)

        assert len(collection_w.indexes) == 1
        log.info(collection_w.indexes[0].params)
        assert collection_w.indexes[0].params["index_type"] == hnsw_index["index_type"]

        collection_w.load()

        results, _ = collection_w.search(cf.gen_vectors(1, ct.default_dim), default_search_field,
                                         search_params, 10, timeout=30)
        log.info(results[0].ids)

        results, _ = collection_w.search(cf.gen_vectors(1, ct.default_dim), default_search_field,
                                         search_params, 30, timeout=30)
        log.info(results[0].ids)
```

**Comment by yanliang567** [comment]
@czs007 I think you are working on error msg refining work
/assign @czs007 
/unassign
