### ISSUE TITLE
[Bug]: error="The specified key does not exist." when creating index

### ISSUE THREAD

**Issue by sroshkul** [milvus-io/milvus#15418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.00
- Deployment mode(standalone or cluster): cluster(AWS EKS)
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others: using AWS S3 as storage and not Minio
```

### Current Behavior

_collection.create_index(field_name, index_params)_ call fails with:
```
Traceback (most recent call last):
  File "lib/python3.7/site-packages/pymilvus/orm/collection.py", line 1040, in create_index
    timeout=timeout, **kwargs)
  File "lib/python3.7/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "lib/python3.7/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "lib/python3.7/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "lib/python3.7/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 585, in create_index
    raise BaseException(Status.UNEXPECTED_ERROR, fail_reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=The specified key does not exist.)>
```

In **indexnode** pods logs we see following **ERROR**:
```
[2022/01/27 11:09:16.489 +00:00] [DEBUG] [parallel.go:80] [loadKey] [error="The specified key does not exist."] [idx=14]
[2022/01/27 11:09:16.489 +00:00] [DEBUG] [parallel.go:80] [loadKey] [error="The specified key does not exist."] [idx=12]
[2022/01/27 11:09:16.490 +00:00] [DEBUG] [parallel.go:80] [loadKey] [error="The specified key does not exist."] [idx=10]
[2022/01/27 11:09:16.490 +00:00] [DEBUG] [parallel.go:80] [loadKey] [error="The specified key does not exist."] [idx=8]
[2022/01/27 11:09:16.491 +00:00] [DEBUG] [parallel.go:80] [loadKey] [error="The specified key does not exist."] [idx=0]
[2022/01/27 11:09:16.504 +00:00] [DEBUG] [parallel.go:80] [loadKey] [error="The specified key does not exist."] [idx=18]
[2022/01/27 11:09:16.518 +00:00] [DEBUG] [parallel.go:80] [loadKey] [error="The specified key does not exist."] [idx=4]
[2022/01/27 11:09:16.521 +00:00] [DEBUG] [parallel.go:80] [loadKey] [error="The specified key does not exist."] [idx=6]
[2022/01/27 11:09:16.521 +00:00] [DEBUG] [parallel.go:80] [loadKey] [error="The specified key does not exist."] [idx=16]
[2022/01/27 11:09:16.527 +00:00] [DEBUG] [parallel.go:80] [loadKey] [error="The specified key does not exist."] [idx=2]
[2022/01/27 11:09:16.527 +00:00] [WARN] [task.go:365] ["loadKey from minio failed"] [error="The specified key does not exist."]
[2022/01/27 11:09:16.527 +00:00] [ERROR] [task.go:572] ["IndexNode IndexBuildTask Execute buildIndex failed"] [buildId=430776122976239624] [error="The specified key does not exist."] [stack="github.com/milvus-io/milvus/internal/indexnode.(*IndexBuildTask).Execute\n\t/go/src/github.com/milvus-io/milvus/internal/indexnode/task.go:572\ngithub.com/milvus-io/milvus/internal/indexnode.(*TaskScheduler).processTask\n\t/go/src/github.com/milvus-io/milvus/internal/indexnode/task_scheduler.go:277\ngithub.com/milvus-io/milvus/internal/indexnode.(*TaskScheduler).indexBuildLoop.func1\n\t/go/src/github.com/milvus-io/milvus/internal/indexnode/task_scheduler.go:296"]
[2022/01/27 11:09:16.533 +00:00] [ERROR] [task.go:223] ["IndexNode IndexBuildTask saveIndexMeta set indexMeta.state to IndexState_Failed"] [TaskState=Failed] [IndexBuildID=430776122976239624] [error="The specified key does not exist."] [stack="github.com/milvus-io/milvus/internal/indexnode.(*IndexBuildTask).saveIndexMeta.func1\n\t/go/src/github.com/milvus-io/milvus/internal/indexnode/task.go:223\ngithub.com/milvus-io/milvus/internal/util/retry.Do\n\t/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:34\ngithub.com/milvus-io/milvus/internal/indexnode.(*IndexBuildTask).saveIndexMeta\n\t/go/src/github.com/milvus-io/milvus/internal/indexnode/task.go:253\ngithub.com/milvus-io/milvus/internal/indexnode.(*IndexBuildTask).PostExecute\n\t/go/src/github.com/milvus-io/milvus/internal/indexnode/task.go:280\ngithub.com/milvus-io/milvus/internal/indexnode.(*TaskScheduler).processTask.func1\n\t/go/src/github.com/milvus-io/milvus/internal/indexnode/task_scheduler.go:257\ngithub.com/milvus-io/milvus/internal/indexnode.(*TaskScheduler).processTask\n\t/go/src/github.com/milvus-io/milvus/internal/indexnode/task_scheduler.go:279\ngithub.com/milvus-io/milvus/internal/indexnode.(*TaskScheduler).indexBuildLoop.func1\n\t/go/src/github.com/milvus-io/milvus/internal/indexnode/task_scheduler.go:296"]
```

### Expected Behavior

Create index w/o errors

### Steps To Reproduce

```markdown
1. Insert data
2. Run collection.create_index()
```

**Comment by xiaofan-luan** [comment]
@sroshkul could you please offer full log of all services? Thanks

**Comment by xiaofan-luan** [comment]
> 

Great, thanks. we are taking a look into it

**Comment by xiaofan-luan** [comment]
seems to be similar with #15439 
/assign @xiaocai2333

**Comment by xiaocai2333** [comment]
maybe similar with # 14918， please check your DataCoord GC config. @sroshkul

**Comment by sroshkul** [comment]
> maybe similar with #14918 ， please check your DataCoord GC config. @sroshkul

We did not change it - default 2.0.0 Helms files were used.
However, 
What should we look there? What should be there or should not?

**Comment by xiaocai2333** [comment]
<img width="920" alt="image" src="https://user-images.githubusercontent.com/46207236/154060643-fe8574cb-89f7-410f-99ba-41ff0c31f97f.png">

internal should less than dropTolerance.
