### ISSUE TITLE
[Bug]: [benchmark][cluster] search raise error: syncTimestamp Failed:context deadline exceeded

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#15522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220209-767b13f
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.1.dev1
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

client pod: benchmark-cron-1644422400-737302963

[client.log](https://github.com/milvus-io/milvus/files/8037587/client.log)

client logs:
```
[2022-02-09 18:13:54,650] [   DEBUG] - Start run query, run 1 of 30 (milvus_benchmark.runners.search:285)
[2022-02-09 18:13:54,651] [    INFO] - {'nq': 500, 'topk': 1000, 'search_param': {'nprobe': 32}, 'filter': [], 'guarantee_timestamp': None} (milvus_benchmark.runners.search:286)
[2022-02-09 18:14:06,870] [   DEBUG] - Milvus query run in 12.218s (milvus_benchmark.client:53)
[2022-02-09 18:14:06,871] [   DEBUG] - Start run query, run 2 of 30 (milvus_benchmark.runners.search:285)
[2022-02-09 18:14:06,872] [    INFO] - {'nq': 500, 'topk': 1000, 'search_param': {'nprobe': 32}, 'filter': [], 'guarantee_timestamp': None} (milvus_benchmark.runners.search:286)
[2022-02-09 18:14:17,474] [   DEBUG] - Milvus query run in 10.6017s (milvus_benchmark.client:53)
[2022-02-09 18:14:17,476] [   DEBUG] - Start run query, run 3 of 30 (milvus_benchmark.runners.search:285)
[2022-02-09 18:14:17,477] [    INFO] - {'nq': 500, 'topk': 1000, 'search_param': {'nprobe': 32}, 'filter': [], 'guarantee_timestamp': None} (milvus_benchmark.runners.search:286)
[2022-02-09 18:14:29,407] [   DEBUG] - Milvus query run in 11.9296s (milvus_benchmark.client:53)
[2022-02-09 18:14:29,409] [   DEBUG] - Start run query, run 4 of 30 (milvus_benchmark.runners.search:285)
[2022-02-09 18:14:29,410] [    INFO] - {'nq': 500, 'topk': 1000, 'search_param': {'nprobe': 32}, 'filter': [], 'guarantee_timestamp': None} (milvus_benchmark.runners.search:286)
[2022-02-09 18:14:42,314] [   ERROR] - RPC error: [_execute_search_requests], <BaseException: (code=1, message=syncTimestamp Failed:context deadline exceeded)>, <Time:{'RPC start': '2022-02-09 18:14:33.000948', 'RPC error': '2022-02-09 18:14:42.314237'}> (pymilvus.decorators:73)
[2022-02-09 18:14:42,315] [   ERROR] - RPC error: [search], <BaseException: (code=1, message=syncTimestamp Failed:context deadline exceeded)>, <Time:{'RPC start': '2022-02-09 18:14:29.411123', 'RPC error': '2022-02-09 18:14:42.315386'}> (pymilvus.decorators:73)
[2022-02-09 18:14:42,320] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 95, in run_suite
    result = runner.run_case(case_metric, **case)
  File "/src/milvus_benchmark/runners/search.py", line 289, in run_case
    guarantee_timestamp=case_param["guarantee_timestamp"])
  File "/src/milvus_benchmark/client.py", line 49, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 322, in query
    result = self._milvus.search(tmp_collection_name, **params)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 829, in search
    partition_names, output_fields, timeout, round_decimal, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 21, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 444, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 391, in _execute_search_requests
    raise pre_err
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 382, in _execute_search_requests
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=syncTimestamp Failed:context deadline exceeded)>
 (milvus_benchmark.main:98)
[2022-02-09 18:14:42,323] [    INFO] - None (milvus_benchmark.main:99)
[2022-02-09 18:14:42,323] [   DEBUG] - {'type': 'insert_search_performance', 'value': {}} (milvus_benchmark.main:107)
[2022-02-09 18:14:42,324] [   DEBUG] - {'_version': '0.1', '_type': 'case', 'run_id': 1644425153, 'mode': 'local', 'server': <milvus_benchmark.metrics.models.server.Server object at 0x7f3266c195f8>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware object at 0x7f3266c19518>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7f3266c19438>, 'status': 'RUN_FAILED', 'err_message': '<BaseException: (code=1, message=syncTimestamp Failed:context deadline exceeded)>\nTraceback (most recent call last):\n  File "main.py", line 95, in run_suite\n    result = runner.run_case(case_metric, **case)\n  File "/src/milvus_benchmark/runners/search.py", line 289, in run_case\n    guarantee_timestamp=case_param["guarantee_timestamp"])\n  File "/src/milvus_benchmark/client.py", line 49, in wrapper\n    result = func(*args, **kwargs)\n  File "/src/milvus_benchmark/client.py", line 322, in query\n    result = self._milvus.search(tmp_collection_name, **params)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 829, in search\n    partition_names, output_fields, timeout, round_decimal, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 56, in handler\n    raise e\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 41, in handler\n    return func(self, *args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler\n    raise e\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler\n    return func(*args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 21, in handler\n    return func(self, *args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 444, in search\n    return self._execute_search_requests(requests, timeout, **_kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler\n    raise e\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler\n    return func(*args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 391, in _execute_search_requests\n    raise pre_err\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 382, in _execute_search_requests\n    raise BaseException(response.status.error_code, response.status.reason)\npymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=syncTimestamp Failed:context deadline exceeded)>\n', 'collection': {'dimension': 128, 'metric_type': 'l2', 'dataset_name': 'sift_50m_128_l2', 'fields': None, 'shards_num': None}, 'index': {'index_type': 'ivf_flat', 'index_param': {'nlist': 2048}}, 'search': {'nq': 500, 'topk': 1000, 'search_param': {'nprobe': 32}, 'filter': [], 'guarantee_timestamp': None}, 'run_params': None, 'metrics': {'type': 'insert_search_performance', 'value': {}}, 'datetime': '2022-02-09 16:04:49.387347', 'type': 'metric'} (milvus_benchmark.metric.api:29)
```

### Expected Behavior

argo task: benchmark-cron-1644422400

test yaml: 
client-configmap:client-search-sift50m-ivf-flat-2048,instanceId:7,server-configmap:server-cluster-16c64m

server:
```
NAME                                                              READY   STATUS      RESTARTS   AGE    IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-cron-1644422400-7-etcd-0                                1/1     Running     0          176m   10.97.3.48     qa-node001.zilliz.local   <none>           <none>
benchmark-cron-1644422400-7-etcd-1                                1/1     Running     0          176m   10.97.4.212    qa-node002.zilliz.local   <none>           <none>
benchmark-cron-1644422400-7-etcd-2                                1/1     Running     0          176m   10.97.7.175    qa-node005.zilliz.local   <none>           <none>
benchmark-cron-1644422400-7-milvus-datacoord-67d4b79d8b-qljqr     1/1     Running     0          176m   10.97.6.59     qa-node004.zilliz.local   <none>           <none>
benchmark-cron-1644422400-7-milvus-datanode-5b88ffb765-mdz42      1/1     Running     0          176m   10.97.20.54    qa-node018.zilliz.local   <none>           <none>
benchmark-cron-1644422400-7-milvus-indexcoord-78454dbbdc-k59w4    1/1     Running     0          176m   10.97.9.182    qa-node007.zilliz.local   <none>           <none>
benchmark-cron-1644422400-7-milvus-indexnode-66479b9f7b-zjb2m     1/1     Running     0          176m   10.97.20.50    qa-node018.zilliz.local   <none>           <none>
benchmark-cron-1644422400-7-milvus-proxy-5b98b8df5f-58z5h         1/1     Running     0          176m   10.97.4.210    qa-node002.zilliz.local   <none>           <none>
benchmark-cron-1644422400-7-milvus-querycoord-75469d9648-csq5l    1/1     Running     0          176m   10.97.9.181    qa-node007.zilliz.local   <none>           <none>
benchmark-cron-1644422400-7-milvus-querynode-65f5f65d58-2h2wn     1/1     Running     0          176m   10.97.14.178   qa-node011.zilliz.local   <none>           <none>
benchmark-cron-1644422400-7-milvus-rootcoord-9fdf84658-rrmwl      1/1     Running     0          176m   10.97.9.185    qa-node007.zilliz.local   <none>           <none>
benchmark-cron-1644422400-7-minio-0                               1/1     Running     0          176m   10.97.20.49    qa-node018.zilliz.local   <none>           <none>
benchmark-cron-1644422400-7-minio-1                               1/1     Running     0          176m   10.97.20.51    qa-node018.zilliz.local   <none>           <none>
benchmark-cron-1644422400-7-minio-2                               1/1     Running     0          176m   10.97.20.52    qa-node018.zilliz.local   <none>           <none>
benchmark-cron-1644422400-7-minio-3                               1/1     Running     0          176m   10.97.20.53    qa-node018.zilliz.local   <none>           <none>
benchmark-cron-1644422400-7-pulsar-autorecovery-779f6d7d78kdkw8   1/1     Running     0          176m   10.97.8.45     qa-node006.zilliz.local   <none>           <none>
benchmark-cron-1644422400-7-pulsar-bastion-f8fdf8c96-vd8b5        1/1     Running     0          176m   10.97.8.47     qa-node006.zilliz.local   <none>           <none>
benchmark-cron-1644422400-7-pulsar-bookkeeper-0                   1/1     Running     0          176m   10.97.8.49     qa-node006.zilliz.local   <none>           <none>
benchmark-cron-1644422400-7-pulsar-bookkeeper-1                   1/1     Running     0          175m   10.97.4.215    qa-node002.zilliz.local   <none>           <none>
benchmark-cron-1644422400-7-pulsar-bookkeeper-2                   1/1     Running     0          174m   10.97.6.61     qa-node004.zilliz.local   <none>           <none>
benchmark-cron-1644422400-7-pulsar-broker-5885d7b79-dps7l         1/1     Running     0          176m   10.97.7.174    qa-node005.zilliz.local   <none>           <none>
benchmark-cron-1644422400-7-pulsar-proxy-6bc7658469-s2lrj         2/2     Running     0          176m   10.97.6.58     qa-node004.zilliz.local   <none>           <none>
benchmark-cron-1644422400-7-pulsar-zookeeper-0                    1/1     Running     0          176m   10.97.4.211    qa-node002.zilliz.local   <none>           <none>
benchmark-cron-1644422400-7-pulsar-zookeeper-1                    1/1     Running     0          176m   10.97.3.49     qa-node001.zilliz.local   <none>           <none>
benchmark-cron-1644422400-7-pulsar-zookeeper-2                    1/1     Running     0          175m   10.97.3.50     qa-node001.zilliz.local   <none>           <none>
benchmark-cron-1644422400-7-pulsar-zookeeper-metadata-ftfv4       0/1     Completed   0          176m   10.97.9.184    qa-node007.zilliz.local   <none>           <none>
```

### Steps To Reproduce

```markdown
1、create collection
2、build index of ivf_flat
3、insert 50 million vectors
4、flush collection
5、build index with the same params
6、load collection
7、search 30 times with specified params <- raise error
```

### Anything else?

client-search-sift50m-ivf-flat-2048:
```
insert_search_performance:
      collections:
        -
          collection_name: sift_50m_128_l2
          ni_per: 50000
          build_index: true
          index_type: ivf_flat 
          index_param:
            nlist: 2048
          run_count: 30
          top_ks: [1, 10, 100, 1000]
          nqs: [1, 10, 100, 500, 1000, 1200]
          search_params:
            -
              nprobe: 8
            -
              nprobe: 32
```

**Comment by xiaocai2333** [comment]
Proxy apply timestamp request from RootCoord time out. The request has a timeout of 5s, but it looks like that the request has time out before RootCoord receives the request.

**Comment by xiaofan-luan** [comment]
@xiaocai2333 by why? 5s seems to be fairly a long time

**Comment by jingkl** [comment]
milvus： master-20220515-338edcd3
pymilvus：pymilvus==2.1.0.dev39

argo
benchmark-cluster-cron-1652648400
server-configmap
server-single-16c64m
client-configmap
client-search-filter-sift50m-ivf-flat-2048

```
[2022-05-15 22:25:47,984] [   ERROR] - RPC error: [_execute_search_requests], <MilvusException: (code=1, message=syncTimestamp Failed:context deadline exceeded)>, <Time:{'RPC start': '2022-05-15 22:25:32.314887', 'RPC error': '2022-05-15 22:25:47.984026'}> (pymilvus.decorators:73)
[2022-05-15 22:25:47,985] [   ERROR] - RPC error: [search], <MilvusException: (code=1, message=syncTimestamp Failed:context deadline exceeded)>, <Time:{'RPC start': '2022-05-15 22:25:32.292785', 'RPC error': '2022-05-15 22:25:47.985109'}> (pymilvus.decorators:73)
[2022-05-15 22:25:47,990] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 95, in run_suite
    result = runner.run_case(case_metric, **case)
  File "/src/milvus_benchmark/runners/search.py", line 298, in run_case
    guarantee_timestamp=case_param["guarantee_timestamp"])
  File "/src/milvus_benchmark/client.py", line 49, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 324, in query
    result = self._milvus.search(tmp_collection_name, **params)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 842, in search
    partition_names, output_fields, timeout, round_decimal, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 21, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 481, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 428, in _execute_search_requests
    raise pre_err
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 419, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=syncTimestamp Failed:context deadline exceeded)>
```

server：
```
NAME                                                              READY   STATUS      RESTARTS   AGE     IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-cluster-cron-1652648400-5-etcd-0                        1/1     Running     0          2m52s   10.97.17.119   qa-node014.zilliz.local   <none>           <none>
benchmark-cluster-cron-1652648400-5-milvus-standalone-667c2b8ff   1/1     Running     0          2m52s   10.97.16.111   qa-node013.zilliz.local   <none>           <none>
benchmark-cluster-cron-1652648400-5-minio-55b68fb8b5-hld9p        1/1     Running     0          2m52s   10.97.19.82    qa-node016.zilliz.local   <none>           <none>
```

**Comment by xige-16** [comment]
/unassign
@xiaocai2333 is looking into this issue

**Comment by yanliang567** [comment]
similar to  #16943

**Comment by xiaocai2333** [comment]
log:
```
[2022/05/15 22:25:39.359 +00:00] [WARN] [client.go:248] ["rootcoord ClientBase ReCall grpc first call get error "] [error="err: rpc error: code = DeadlineExceeded desc = context deadline exceeded\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:247 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall\n/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/client/client.go:330 github.com/milvus-io/milvus/internal/distributed/rootcoord/client.(*Client).AllocTimestamp\n/go/src/github.com/milvus-io/milvus/internal/proxy/timestamp.go:61 github.com/milvus-io/milvus/internal/proxy.(*timestampAllocator).alloc\n/go/src/github.com/milvus-io/milvus/internal/proxy/timestamp.go:84 github.com/milvus-io/milvus/internal/proxy.(*timestampAllocator).AllocOne\n/go/src/github.com/milvus-io/milvus/internal/proxy/channels_time_ticker.go:93 github.com/milvus-io/milvus/internal/proxy.(*channelsTimeTickerImpl).tick\n/go/src/github.com/milvus-io/milvus/internal/proxy/channels_time_ticker.go:160 github.com/milvus-io/milvus/internal/proxy.(*channelsTimeTickerImpl).tickLoop\n/usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit\n"]
[2022/05/15 22:25:39.359 +00:00] [WARN] [channels_time_ticker.go:162] [channelsTimeTickerImpl.tickLoop] [error="syncTimestamp Failed:context deadline exceeded"]
```

from these logs, the grpc server of RootCoord is no longer avaliable.

**Comment by xiaocai2333** [comment]
It seems that all grpc services are unavailable. (querynode is searching)
```
[2022/05/15 22:25:39.355 +00:00] [ERROR] [client.go:230] ["querynode ClientBase Call grpc first call get error "] [error="err: context deadline exceeded\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:229 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).Call\n/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:250 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Search\n/go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:405 github.com/milvus-io/milvus/internal/proxy.(*searchTask).searchShard.func1\n/go/src/github.com/milvus-io/milvus/internal/proxy/task_policies.go:68 github.com/milvus-io/milvus/internal/proxy.roundRobinPolicy\n/go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:421 github.com/milvus-io/milvus/internal/proxy.(*searchTask).searchShard\n/go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:281 github.com/milvus-io/milvus/internal/proxy.(*searchTask).Execute.func1.1\n/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 golang.org/x/sync/errgroup.(*Group).Go.func1\n/usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit\n"] [stack="github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).Call\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:230\ngithub.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Search\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:250\ngithub.com/milvus-io/milvus/internal/proxy.(*searchTask).searchShard.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:405\ngithub.com/milvus-io/milvus/internal/proxy.roundRobinPolicy\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_policies.go:68\ngithub.com/milvus-io/milvus/internal/proxy.(*searchTask).searchShard\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:421\ngithub.com/milvus-io/milvus/internal/proxy.(*searchTask).Execute.func1.1\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:281\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57"]
[2022/05/15 22:25:39.355 +00:00] [WARN] [task_search.go:407] ["QueryNode search returns error"] [nodeID=2] [error="err: context deadline exceeded\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:229 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).Call\n/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:250 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Search\n/go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:405 github.com/milvus-io/milvus/internal/proxy.(*searchTask).searchShard.func1\n/go/src/github.com/milvus-io/milvus/internal/proxy/task_policies.go:68 github.com/milvus-io/milvus/internal/proxy.roundRobinPolicy\n/go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:421 github.com/milvus-io/milvus/internal/proxy.(*searchTask).searchShard\n/go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:281 github.com/milvus-io/milvus/internal/proxy.(*searchTask).Execute.func1.1\n/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 golang.org/x/sync/errgroup.(*Group).Go.func1\n/usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit\n"]
[2022/05/15 22:25:39.355 +00:00] [WARN] [task_policies.go:70] ["fail to Query with shard leader"] [leader=by-dev-rootcoord-dml_0_433231938340457793v0] [nodeID=2] [error="Invalid shard leader"]
```

**Comment by xiaocai2333** [comment]
querynode is searching.
```
{'nq': 1200, 'topk': 1000, 'search_param': {'nprobe': 32}, 'filter': [{'range': {'float1': {'GT': -1.0, 'LT': 25000000.0}}}]
```

cpu metrics
![origin_img_v2_047dffae-5a0b-405b-9442-1c91975462ag](https://user-images.githubusercontent.com/46207236/169775018-0b81dff0-ecf5-4dbf-a7a7-dfaf92388ce7.jpg)

memory metrics
![origin_img_v2_7242f13e-c7c9-43c0-b6e8-c5dfca5c72ag](https://user-images.githubusercontent.com/46207236/169775087-f49c3f2a-abe2-46b9-a0fc-38e10d7e17fa.jpg)

**Comment by czs007** [comment]
refer to  #17470
