### ISSUE TITLE
[Bug]: Segmentation fault using C++ SDK 

### ISSUE THREAD

**Issue by TannedCung** [milvus-io/milvus#15559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 1.1.1, 
- Deployment mode(standalone or cluster):standalone
- SDK version(C++ 1.1):
- OS: Ubuntu 
- CPU/Memory: i7-10400f + 16GB
- GPU: i used milvus cpu version
- Others:
```

### Current Behavior

Using SDK from branch 1.1.
- Create Collection name
- Create Index
- Search
- > Segmentation fault
Here are backtrace return by gdb:
```
Thread 1 "app" received signal SIGSEGV, Segmentation fault.
0x00005563f0e0e5f8 in std::vector<float, std::allocator<float> >::operator[](unsigned long) ()
(gdb) backtrace
#0  0x00005563f0e0e5f8 in std::vector<float, std::allocator<float> >::operator[](unsigned long) ()
#1  0x00005563f0e0ae1b in search(std::shared_ptr<milvus::Connection>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<milvus::Entity, std::allocator<milvus::Entity> >, std::vector<milvus::QueryResult, std::allocator<milvus::QueryResult> >&, long, long) ()
#2  0x00005563f0e0b574 in main ()
```

### Steps To Reproduce

```markdown
i used this script:
```cpp
#include "MilvusApi.h"
#include "Status.h"
#include "json.hpp"
#include "iostream"
#include <chrono>
#include <thread>

#define MILVUS_HOST "0.0.0.0"
#define MILVUS_PORT "19530"
#define COLLECTION_NAME "test2"

using json = nlohmann::json;

void search(std::shared_ptr<milvus::Connection> conn_milvus, const std::string &collection_name, std::vector<milvus::Entity> entity_array, milvus::TopKQueryResult &topk_query_result, int64_t top_k=1, int64_t nprobe=16)
{
  std::vector<std::string> partition_tags; //empty
  json json_params = {{"nprobe", nprobe}};

  milvus::Status stat = conn_milvus->Search(collection_name,
                                                  partition_tags,
                                                  entity_array,
                                                  top_k,
                                                  json_params.dump(),
                                                  topk_query_result);
  // by pass topk_query_result segment
  if (stat.ok()){
    std::cout << " ---> collection_name: " << collection_name;
    std::cout << " batch: " << topk_query_result.size()
      << "-- status: " << stat.message();
    std::cout << "-- distances: " << topk_query_result[0].distances[0];
    std::cout << "-- \n";
  }
}

int main()
{
  milvus::ConnectParam param = {MILVUS_HOST, MILVUS_PORT};
  std::shared_ptr<milvus::Connection> conn_milvus = milvus::Connection::Create();
  milvus::Status stat = conn_milvus->Connect(param);
  std::cout << "Connected with stat: " << stat.message() << std::endl;

  milvus::CollectionParam collection_param = {
      COLLECTION_NAME,
      512,
      2048,
      milvus::MetricType::L2};
  stat = conn_milvus->CreateCollection(collection_param);  
  std::cout << "CreateCollection with stat: " << stat.message() << std::endl;

  milvus::IndexParam index;

  json json_index_params = {{"nlist", 2048}};
  index.collection_name = COLLECTION_NAME;
  index.index_type = milvus::IndexType::IVFFLAT;
  index.extra_params = json_index_params.dump();
  stat = conn_milvus->CreateIndex(index);
  std::cout << "CreateIndex with stat: " << stat.message() << std::endl;
  
  std::vector<milvus::Entity> entity_array;
  std::vector<float> emb;
  for (int i = 0; i < 512; i++)
  {
    emb.push_back(0.1 + i/512.0);
  }

  milvus::Entity entity;
  entity.float_data.resize(512);
  entity.float_data = emb;
  entity_array.push_back(entity);

  // -------------------- search --------------------
  milvus::TopKQueryResult topk_query_result;
  search(conn_milvus, COLLECTION_NAME, entity_array, topk_query_result);
  // -------------------- end search --------------------
```
```
```

**Comment by TannedCung** [comment]
Btw, things works well with the collection created by pymilvus.
