### ISSUE TITLE
[Bug]: fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by Mercurialll** [milvus-io/milvus#15574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.0
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.0.0
- OS(Ubuntu or CentOS):  Ubuntu
- CPU/Memory: inteli7/32gb
- GPU: -
- Others: default milvus settings. 
- - "index_type": "IVF_FLAT", "nlist": 100, "metric_type": "IP".
- - there are 2 collections in DB: each <50k rows, each row consists of id and 256dim vector.
```

### Current Behavior

Milvus unpredictable exits docker container while ANN searching. I tried around 10 times, always different quantity of searches is needed to milvus be exited. On average after ~200 consequtive searches milvus will be exited. 
Each search spends around 0.2sec. 

### Expected Behavior

I expected Milvus will work infinitely :) 

### Steps To Reproduce

```markdown
1. fresh standalone milvus docker up with default milvus settings. 
2. create 2 collections.
3. fulfill with data:<50k rows, each row consists of id and 256dim vector.
4. create index "index_type": "IVF_FLAT", "nlist": 100, "metric_type": "IP".
5. conduct 100+ times consequently this: 
5.1. search in first collection, take IDs
5.2. search in second collection with expr="id in IDs".
6. Somewhere here you will get "fatal error: unexpected signal during runtime execution" + exited milvus with super-long log output.
```

**Comment by Mercurialll** [comment]
[milvus.log](https://github.com/milvus-io/milvus/files/8062610/milvus.log)

**Comment by xiaofan-luan** [comment]
very nice issue with detailed infomation, thanks @Mercurialll

**Comment by Mercurialll** [comment]
Also while I was testing, I got this errors with the same reproduce steps:
1. `[signal SIGSEGV: segmentation violation code=0x1 addr=0xffffffffffffffff pc=0x7f6d7b56b2d7]`
2. `free(): invalid next size (fast) ; SIGABRT: abort ; PC=0x7ff0f144bfb7 m=4 sigcode=18446744073709551610`
3. smth about `unsigned long < ...` . Didnt copy this unfortunately and now I cant find this.

**Comment by cydrain** [comment]
@Mercurialll

**Comment by Mercurialll** [comment]
Hi @cydrain ! Yes, I have negative IDs in collections, because my IDs are UINT64, but milvus supports only INT64, so we decided to "convert" UINT64 -> INT64 by subtracting 2 ** 63. Is it a problem that I have negativies IDs in collections?

**Comment by cydrain** [comment]
> Hi @cydrain ! Yes, I have negative IDs in collections, because my IDs are UINT64, but milvus supports only INT64, so we decided to "convert" UINT64 -> INT64 by subtracting 2 ** 63. Is it a problem that I have negativies IDs in collections?

Hi @Mercurialll , it's ok.
Can you give me your script to reproduce this issue?

**Comment by Mercurialll** [comment]
[requirements.txt](https://github.com/milvus-io/milvus/files/8078497/requirements.txt)

**Comment by cydrain** [comment]
get coredump traceback:

```
#16 0x00007fe78adc4298 in operator new(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#17 0x00007fe78a3cba3d in faiss::IndexIVFFlat::get_InvertedListScanner (this=0x7fe668026f20, store_pairs=<optimized out>) at IndexIVFFlat.cpp:238
        __PRETTY_FUNCTION__ = "virtual faiss::InvertedListScanner* faiss::IndexIVFFlat::get_InvertedListScanner(bool) const"
#18 0x00007fe78a3c4108 in faiss::IndexIVF::search_preassigned_without_codes(long, float const*, unsigned char const*, std::vector<unsigned long, std::allocator<unsigned long> >, bool, long, long const*, float const*, float*, long*, bool, faiss::IVFSearchParameters const*, faiss::BitsetView) [clone ._omp_fn.2] () at IndexIVF.cpp:638
        del = <optimized out>
        init_result = <optimized out>
        reorder_result = <optimized out>
        scan_one_list = <optimized out>
        del = <optimized out>
        init_result = <optimized out>
        reorder_result = <optimized out>
        scan_one_list = <optimized out>
        scanner = <optimized out>
        scanner = <optimized out>
        nprobe = <optimized out>
        max_codes = <optimized out>
        nlistv = <optimized out>
        ndis = <optimized out>
        nheap = <optimized out>
        interrupt = <optimized out>
        pmode = <optimized out>
        do_heap_init = false
        do_parallel = <optimized out>
        __PRETTY_FUNCTION__ = "virtual void faiss::IndexIVF::search_preassigned_without_codes(faiss::Index::idx_t, const float*, const uint8_t*, std::vector<long unsigned int>, bool, faiss::Index::idx_t, const idx_t*, const float*,"...
#19 0x00007fe785ac0edf in GOMP_parallel () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
No symbol table info available.
#20 0x00007fe78a3c1f71 in faiss::IndexIVF::search_preassigned_without_codes (this=this@entry=0x7fe668026f20, n=n@entry=1, 
    x=x@entry=0x7fe5f40283c0, 
    arranged_codes=arranged_codes@entry=0x7fe668da4210 "\373K\003=1\250p<\202i\245\275,߈\272\370%ܽ\360\301\336=u\030\221=\247꿽\211u\341=\223l\366<\377>^\272p\031\341=\305\347-\275\066\031\207\275\061>\362\274eR\301\274\"\r!=\201C\235\275\371C\346V\275\200\034\355;ϛ}\275!ؚ==1\316=\302\214\374\273Uк;;\274a=\252\v\345\275wk+\274\003\064H\275ũ\005=\024R\032=\023و\275\210\224!=\373,y\275\271\205[\275xh\237<J\365ʽ\204U\277\275\207\005\203\275\"\317D=\332\354c=:VI\275S\001\231\275[b˻\004Ut\275\341\221I=n\222g\275mW\302=\202\035Z:"..., 
---Type <return> to continue, or q <return> to quit---
    prefix_sum=std::vector of length 100, capacity 100 = {...}, is_sq8=<optimized out>, is_sq8@entry=false, k=<optimized out>, 
    keys=0x7fe5f40243b0, coarse_dis=0x7fe5f4022e90, distances=0x7fe5f4001a90, labels=0x7fe5f4027080, store_pairs=<optimized out>, params=0x0, 
    bitset=...) at IndexIVF.cpp:636
        nprobe = <optimized out>
        max_codes = 0
        nlistv = 0
        ndis = 0
        nheap = 0
        interrupt = false
        pmode = <optimized out>
        do_heap_init = true
        do_parallel = <optimized out>
        __PRETTY_FUNCTION__ = "virtual void faiss::IndexIVF::search_preassigned_without_codes(faiss::Index::idx_t, const float*, const uint8_t*, std::vector<long unsigned int>, bool, faiss::Index::idx_t, const idx_t*, const float*,"...
#21 0x00007fe78a3c933f in faiss::IndexIVF::search_without_codes (this=0x7fe668026f20, n=<optimized out>, x=0x7fe5f40283c0, 
    arranged_codes=0x7fe668da4210 "\373K\003=1\250p<\202i\245\275,߈\272\370%ܽ\360\301\336=u\030\221=\247꿽\211u\341=\223l\366<\377>^\272p\031\341=\305\347-\275\066\031\207\275\061>\362\274eR\301\274\"\r!=\201C\235\275\371C\346V\275\200\034\355;ϛ}\275!ؚ==1\316=\302\214\374\273Uк;;\274a=\252\v\345\275wk+\274\003\064H\275ũ\005=\024R\032=\023و\275\210\224!=\373,y\275\271\205[\275xh\237<J\365ʽ\204U\277\275\207\005\203\275\"\317D=\332\354c=:VI\275S\001\231\275[b˻\004Ut\275\341\221I=n\222g\275mW\302=\202\035Z:"..., prefix_sum=..., is_sq8=<optimized out>, k=10, 
    distances=0x7fe5f4001a90, labels=0x7fe5f4027080, bitset=...) at IndexIVF.cpp:371
        idx = std::unique_ptr<long []> = {get() = 0x7fe5f40243b0}
        coarse_dis = std::unique_ptr<float []> = {get() = 0x7fe5f4022e90}
        t0 = 1645095181288.323
#22 0x00007fe78a2e59af in milvus::knowhere::IVF_NM::QueryImpl (this=0x7fe6680fa010, n=1, query=0x7fe5f40283c0, k=10, distances=0x7fe5f4001a90, 
    labels=0x7fe5f4027080, config=..., bitset=...)
    at /home/caiyd/vec/milvus/internal/core/src/index/knowhere/knowhere/index/vector_offset_index/IndexIVF_NM.cpp:341
        params = std::shared_ptr<faiss::IVFSearchParameters> (use count 1, weak count 0) = {get() = 0x7fe5f4028b50}
        ivf_index = 0x7fe668026f20
        before = {__d = {__r = 1645095181288185154}}
        is_sq8 = false
        data = 0x7fe668da4210 "\373K\003=1\250p<\202i\245\275,߈\272\370%ܽ\360\301\336=u\030\221=\247꿽\211u\341=\223l\366<\377>^\272p\031\341=\305\347-\275\066\031\207\275\061>\362\274eR\301\274\"\r!=\201C\235\275\371C\346V\275\200\034\355;ϛ}\275!ؚ==1\316=\302\214\374\273Uк;;\274a=\252\v\345\275wk+\274\003\064H\275ũ\005=\024R\032=\023و\275\210\224!=\373,y\275\271\205[\275xh\237<J\365ʽ\204U\277\275\207\005\203\275\"\317D=\332\354c=:VI\275S\001\231\275[b˻\004Ut\275\341\221I=n\222g\275mW\302=\202\035Z:"...

        ivf_stats = std::shared_ptr<milvus::knowhere::IVFStatistics> (use count 2, weak count 0) = {get() = 0x7fe6680f7d20}
        after = {__d = {__r = 140625618020896}}
        search_cost = 6.9477325133984948e-310
        __PRETTY_FUNCTION__ = "virtual void milvus::knowhere::IVF_NM::QueryImpl(int64_t, const float*, int64_t, float*, int64_t*, const Config&, faiss::BitsetView)"
        __FUNCTION__ = "QueryImpl"
#23 0x00007fe78a2e4c04 in milvus::knowhere::IVF_NM::Query (this=0x7fe6680fa010, 
    dataset_ptr=std::shared_ptr<milvus::knowhere::Dataset> (use count 1, weak count 0) = {...}, config=..., bitset=...)
    at /home/caiyd/vec/milvus/internal/core/src/index/knowhere/knowhere/index/vector_offset_index/IndexIVF_NM.cpp:168
        k = 10
```

**Comment by Mercurialll** [comment]
@cydrain You mean "parallel search" == 2+ searches in milvus in one time?

**Comment by cydrain** [comment]
> @cydrain You mean "parallel search" == 2+ searches in milvus in one time?

@Mercurialll In your case, 10000 entities are inserted into 2 segments, Milvus will invoke 2 go routines for these 2 segments to do search, this is what I mean "parallel search from GO side".
I have found the root cause for this issue, I'll fix it soon.

**Comment by cydrain** [comment]
The root cause for this issue is because of this line:
```
template <typename T>
auto
ExecExprVisitor::ExecTermVisitorImpl(TermExpr& expr_raw) -> RetType {
    ... ...
    std::sort(expr.terms_.begin(), expr.terms_.end());
    ... ...
```

**Comment by jingkl** [comment]
The test result is that Expr has no problem with id lists of size 5000, further verification is needed for sizes over 5000.

**Comment by matrixji** [comment]
> The test result is that Expr has no problem with id lists of size 5000, further verification is needed for sizes over 5000.
> 
> ```
> image tag : milvusdb/milvus-dev:master-20220222-9a6ee617
> pymilvus version: pymilvus v2.0.0
> Deployment mode(standalone or cluster): cluster
> ```
> 
> @matrixji If possible, please verify. Thanks

Seems you may hope mention to @Mercurialll

**Comment by Mercurialll** [comment]
@matrixji hello!
First few tests I've conducted were successful : 1000 ANN searches with expr. were done without any troubles.
If I investigate something strange - I will get you known

**Comment by cydrain** [comment]
Hi @yanliang567 , this issue has been fixed, please verify and mark it to closed.

**Comment by yanliang567** [comment]
verified on latest master. close for now
