### ISSUE TITLE
[Bug]: Datanode panic after compact when entityExpiration is set to 120s

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#15573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220210-1a2a6927
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc10.dev7
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

`my-release-milvus-datanode-5d49fcf5c7-bqwdm         0/1     CrashLoopBackOff   8          64m`

log：
```
[2022/02/14 09:32:40.339 +00:00] [INFO] [compaction_executor.go:96] ["start to execute compaction"] [planID=431182619691712514]
[2022/02/14 09:32:40.339 +00:00] [INFO] [compaction_executor.go:96] ["start to execute compaction"] [planID=431182619691712515]
[2022/02/14 09:32:40.339 +00:00] [DEBUG] [compactor.go:333] ["compaction start"] [planID=431182619691712514] ["timeout in seconds"=60]
[2022/02/14 09:32:40.340 +00:00] [DEBUG] [compactor.go:356] ["inject elapse in ms"] [planID=431182619691712514] [elapse=0.059018]
panic: runtime error: index out of range [0] with length 0

goroutine 64592 [running]:
github.com/milvus-io/milvus/internal/datanode.(*compactionTask).compact(0xc0014540a0, 0x0, 0x0)
	/go/src/github.com/milvus-io/milvus/internal/datanode/compactor.go:383 +0x36fb
github.com/milvus-io/milvus/internal/datanode.(*compactionExecutor).executeTask(0xc0005962a0, 0x34cbb38, 0xc0014540a0)
	/go/src/github.com/milvus-io/milvus/internal/datanode/compaction_executor.go:98 +0x187
created by github.com/milvus-io/milvus/internal/datanode.(*compactionExecutor).executeWithState
	/go/src/github.com/milvus-io/milvus/internal/datanode/compaction_executor.go:75 +0x75
```

### Expected Behavior

all work well

### Steps To Reproduce

```markdown
1. deploy Milvus by the operator with config `entityExpiration: 120`
2. create collection with shard_num as 1 and insert and flush data for 10 times
3. wait for more than 120s to make sure entityExpiration taking effect.
4. call compact function by manual to trigger entityExpiration
5. call compact function by manual again
```

### Anything else?

[test-auto-expiration.zip](https://github.com/milvus-io/milvus/files/8059734/test-auto-expiration.zip)

**Comment by zhuwenxing** [comment]
output in step 4:
```
Compaction Plans:
 - compaction id: 431182230840672257
 - state: Completed
 - plans: [
Plan:
 - sources: [431182198360768514, 431182198033350659]
 - target: 431182230853517314
, 
Plan:
 - sources: [431182198360768513, 431182198033350662]
 - target: 431182230853517315
]
```
output in step 5:
```
segment info: []
```

**Comment by zhuwenxing** [comment]
> output in step 4:
> 
> ```
> Compaction Plans:
>  - compaction id: 431182230840672257
>  - state: Completed
>  - plans: [
> Plan:
>  - sources: [431182198360768514, 431182198033350659]
>  - target: 431182230853517314
> , 
> Plan:
>  - sources: [431182198360768513, 431182198033350662]
>  - target: 431182230853517315
> ]
> ```
> 
> output in step 5:
> 
> ```
> segment info: []
> ```

The segment is [] because the collection is not loaded

**Comment by zhuwenxing** [comment]
6. insert data and flush 
in step 6, datanode will crash.

**Comment by XuanYang-cn** [comment]
@zhuwenxing Please help to check if this has been fixed.
