### ISSUE TITLE
[Bug]: [chaos][datanode]search raise error when running test_e2e.py after datanode pod two replicas recovered from pod kill

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#15681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220218-d0110732
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.1.dev3
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Milvus cluster was deployed with two datanode replicas. Those two datanode pods all will be killed during the chaos.

```
[2022-02-20 19:47:15 - ERROR - ci_test]: Traceback (most recent call last):
  File "/home/runner/work/milvus/milvus/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
    res = func(*args, **kwargs)
  File "/home/runner/work/milvus/milvus/tests/python_client/utils/api_request.py", line 56, in api_request
    return func(*arg, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 697, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 49, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 82, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 21, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 444, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 82, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 391, in _execute_search_requests
    raise pre_err
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 379, in _execute_search_requests
    response = ft.result()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1645386435.300864568","description":"Error received from peer ipv4:127.0.0.1:19530","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
 (api_request.py:35)
[2022-02-20 19:47:15 - ERROR - ci_test]: (api_response) : <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1645386435.300864568","description":"Error received from peer ipv4:127.0.0.1:19530","file":"src/core/lib/surface/call.cc","file_line":1067,...... (api_request.py:36)
```

### Expected Behavior

all work well

### Steps To Reproduce

```markdown
see job link https://github.com/milvus-io/milvus/runs/5266344346?check_suite_focus=true
```

### Anything else?

failed job link
https://github.com/milvus-io/milvus/runs/5266344346?check_suite_focus=true

log
[chaos-test.zip](https://github.com/milvus-io/milvus/files/8113242/chaos-test.zip)

**Comment by zhuwenxing** [comment]
/unassign @yanliang567 
/assign @xige-16 
Please take a look

**Comment by bigsheeper** [comment]
QueryNode searched done and returned searchResult to searchResultChannel in Proxy immediately at **19:46:55**.
```
[2022/02/20 19:46:55.481 +00:00] [DEBUG] [query_collection.go:1126] ["QueryNode reduce data finished"] [msgID=431328067418113880]
[2022/02/20 19:46:55.482 +00:00] [DEBUG] [time_recorder.go:78] ["search 431328174884782081(nq=1, k=1), msgID = 431328067418113880: reduce result done, msgID = 431328067418113880 (1ms)"]
[2022/02/20 19:46:55.483 +00:00] [DEBUG] [query_collection.go:697] [translateHits:] [lenOfFieldIDs=0] [lenOfRawHits=1]
[2022/02/20 19:46:55.489 +00:00] [DEBUG] [query_collection.go:1202] ["QueryNode SearchResultMsg"] [collectionID=431328174884782081] [msgID=431328067418113880] [vChannels="[by-dev-rootcoord-dml_185_431328174884782081v1,by-dev-rootcoord-dml_184_431328174884782081v0]"] [sealedSegmentSearched="[431328175122284546,431328175122284545]"]
[2022/02/20 19:46:55.494 +00:00] [DEBUG] [proxy_session_manager.go:108] ["success to send search result"] [node=11] [base="msg_type:SearchResult msgID:431328067418113880 timestamp:431328176443752451 sourceID:11 "]
[2022/02/20 19:46:55.495 +00:00] [DEBUG] [time_recorder.go:78] ["search 431328174884782081(nq=1, k=1), msgID = 431328067418113880: publish search result, msgID = 431328067418113880 (12ms)"]
[2022/02/20 19:46:55.495 +00:00] [DEBUG] [time_recorder.go:78] ["search 431328174884782081(nq=1, k=1), msgID = 431328067418113880: all done, msgID = 431328067418113880 (18ms)"]
[2022/02/20 19:46:55.495 +00:00] [DEBUG] [query_collection.go:686] ["do query done in doUnsolvedMsg"] [collectionID=431328174884782081] [msgID=431328067418113880]
```

however, Proxy didn't get the the result from searchResultChannel and then search task timed out at **19:47:15**.
```
[2022/02/20 19:46:55.317 +00:00] [DEBUG] [task.go:1698] ["proxy sent one searchMsg"] [collectionID=431328174884782081] [msgID=431328067418113880] ["length of search msg"=1] [timeoutTs=431328181721759744]
[2022/02/20 19:46:55.318 +00:00] [DEBUG] [time_recorder.go:78] ["proxy execute search 431328067418113880: send search msg to message stream (5ms)"]
[2022/02/20 19:46:55.318 +00:00] [DEBUG] [time_recorder.go:78] ["proxy execute search 431328067418113880: done (10ms)"]
[2022/02/20 19:47:15.302 +00:00] [DEBUG] [task.go:1900] ["Proxy searchTask PostExecute Loop exit caused by ctx.Done"] [taskID=431328067418113880]
[2022/02/20 19:47:15.302 +00:00] [DEBUG] [time_recorder.go:78] ["searchTask PostExecute: done (19983ms)"]
```

**Comment by xiaofan-luan** [comment]
> searchResultChannel
how many query nodes do we have?

**Comment by bigsheeper** [comment]
> > searchResultChannel
> > how many query nodes do we have?

```
NAME                                                          READY   STATUS      RESTARTS   AGE
chaos-controller-manager-684f859946-grflb                     1/1     Running     0          15m
chaos-daemon-rrdlr                                            1/1     Running     0          15m
chaos-dashboard-6f744b6b8c-ltq2j                              1/1     Running     0          15m
test-datanode-pod-kill-etcd-0                                 1/1     Running     0          13m
test-datanode-pod-kill-milvus-datacoord-74f57648cb-lhzjl      1/1     Running     1          13m
test-datanode-pod-kill-milvus-datanode-7596df7d9-lsmqm        1/1     Running     0          4m23s
test-datanode-pod-kill-milvus-datanode-7596df7d9-wpxmr        1/1     Running     0          4m28s
test-datanode-pod-kill-milvus-indexcoord-[66](https://github.com/milvus-io/milvus/runs/5266344346?check_suite_focus=true#step:15:66)8cfc586f-rsk6q     1/1     Running     0          13m
test-datanode-pod-kill-milvus-indexnode-6d84459c9b-swvrw      1/1     Running     0          13m
test-datanode-pod-kill-milvus-proxy-54cbfff7dc-zq7wv          1/1     Running     1          13m
test-datanode-pod-kill-milvus-querycoord-5fb866bdd6-vhwrd     1/1     Running     0          13m
test-datanode-pod-kill-milvus-querynode-787f5d6478-xb29v      1/1     Running     0          13m
test-datanode-pod-kill-milvus-rootcoord-5999fd857b-sms9h      1/1     Running     1          13m
test-datanode-pod-kill-minio-0                                1/1     Running     0          13m
test-datanode-pod-kill-minio-1                                1/1     Running     0          13m
test-datanode-pod-kill-minio-2                                1/1     Running     0          13m
test-datanode-pod-kill-minio-3                                1/1     Running     0          13m
test-datanode-pod-kill-pulsar-autorecovery-[74](https://github.com/milvus-io/milvus/runs/5266344346?check_suite_focus=true#step:15:74)d8fcf5b9-pnlbn   1/1     Running     0          13m
test-datanode-pod-kill-pulsar-bookkeeper-0                    1/1     Running     0          13m
test-datanode-pod-kill-pulsar-bookkeeper-1                    1/1     Running     0          11m
test-datanode-pod-kill-pulsar-broker-6cbfd58[84](https://github.com/milvus-io/milvus/runs/5266344346?check_suite_focus=true#step:15:84)5-2lsn6         1/1     Running     0          13m
test-datanode-pod-kill-pulsar-proxy-7c4ccb8f6f-ngfjl          1/1     Running     0          13m
test-datanode-pod-kill-pulsar-zookeeper-0                     1/1     Running     0          13m
test-datanode-pod-kill-pulsar-zookeeper-metadata-krfl4        0/1     Completed   0          13m
```

One QueryNode and one Proxy

**Comment by bigsheeper** [comment]
> timestamp:431328176443752451 sourceID:11

QueryNode sent searchResult to Proxy sourceID: 11, and
Proxy server id is 11. Proxy doesn't get the result even though the grpc interface SendSearchResult() has returned, quite strange.

proxy log:
```
[2022/02/20 19:37:36.450 +00:00] [DEBUG] [session_util.go:175] ["Session get serverID success"] [key=id] [ServerId=11]
```

**Comment by xiaofan-luan** [comment]
keep watching on the progress~
