### ISSUE TITLE
[Bug]: [chaos]querynode panic during multiprocess of insert, flush, compact and query after restart docker 

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#15713]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: b0923f12
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc10.dev7
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

querynode panic during multiprocess of insert, flush, compact and query after restart docker 
```
      Name                     Command                  State                          Ports
----------------------------------------------------------------------------------------------------------------
milvus-datacoord    /tini -- milvus run datacoord    Up
milvus-datanode     /tini -- milvus run datanode     Up
milvus-etcd         etcd -advertise-client-url ...   Up             2379/tcp, 2380/tcp
milvus-indexcoord   /tini -- milvus run indexcoord   Up
milvus-indexnode    /tini -- milvus run indexnode    Up
milvus-minio        /usr/bin/docker-entrypoint ...   Up (healthy)   9000/tcp
milvus-proxy        /tini -- milvus run proxy        Up             0.0.0.0:19530->19530/tcp,:::19530->19530/tcp
milvus-pulsar       /bin/bash -c                     Up
                    bin/apply-co ...
milvus-querycoord   /tini -- milvus run querycoord   Up
milvus-querynode    /tini -- milvus run querynode    Exit 2
milvus-rootcoord    /tini -- milvus run rootcoord    Up
```

```
[2022/02/23 07:35:42.197 +00:00] [DEBUG] [segment_loader.go:371] ["Do insert done in segment loader"] [len=66000] [segmentID=431384574884839425] [collectionID=431384574504468481]
[2022/02/23 07:35:42.197 +00:00] [DEBUG] [segment_loader.go:219] ["loading bloom filter..."]
[2022/02/23 07:35:42.214 +00:00] [DEBUG] [segment_loader.go:227] ["loading delta..."]
[2022/02/23 07:35:42.214 +00:00] [INFO] [segment_loader.go:479] ["there are no delta logs saved with segment"] [segmentID=431384574884839425]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1ae27ce]

goroutine 148 [running]:
github.com/milvus-io/milvus/internal/querynode.(*segmentLoader).loadSegment(0xc000126600, 0xc0045dfa98, 0xc000000002, 0x2, 0x2)
	/go/src/github.com/milvus-io/milvus/internal/querynode/segment_loader.go:151 +0x15ae
github.com/milvus-io/milvus/internal/querynode.(*watchDmChannelsTask).Execute(0xc00054a060, 0x34c09d0, 0xc0003b1ac0, 0x0, 0x0)
	/go/src/github.com/milvus-io/milvus/internal/querynode/task.go:290 +0xf3f
github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).processTask(0xc0003b1b00, 0x34d38d8, 0xc00054a060, 0x34d1a50, 0xc00044ceb0)
	/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:61 +0x173
github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).taskLoop(0xc0003b1b00)
	/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:78 +0x15a
created by github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).Start
	/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:86 +0x5c
```

### Expected Behavior

Milvus works well during multiprocess of insert, flush, compact and query

### Steps To Reproduce

```markdown
1. deploy cluster milvus with docker-compose
2. run test_milvus_with_multi_process.py with `tasks = [insert_data]`
3. run `sudo systemctl restart docker` 
4. docker-compose up -d to start all containers bucause step 3 will cause all containers exit
5. run test_milvus_with_multi_process.py with `tasks = [insert_data, flush_data, compact_data, query_data]`
```

### Anything else?

script
change .txt to .py
[test_milvus_with_multi_process.txt](https://github.com/milvus-io/milvus/files/8122634/test_milvus_with_multi_process.txt)

logs
all logs: [cluster-03-25.log](https://github.com/milvus-io/milvus/files/8122706/cluster-03-25.log)
querynode log: 
[milvus-querynode.log](https://github.com/milvus-io/milvus/files/8122713/milvus-querynode.log)

**Comment by zhuwenxing** [comment]
In step 2, flush is not contained, just inserting data like a stream.

If tasks is [insert_data, flush_data, compact_data, query_data] in step 2, this issue is not reproduced, but query will hang for several minutes.

**Comment by zhuwenxing** [comment]
/assign @xige-16 
Please take a look.

**Comment by bigsheeper** [comment]
QueryNode print msgID crashed, msgID belongs to commonpb.BaseMsg, which is nill. Would fix by #15725

**Comment by xiaofan-luan** [comment]
@zhuwenxing should be fixed on https://github.com/milvus-io/milvus/pull/15725, could you please check on that?

**Comment by zhuwenxing** [comment]
Verified and passed in version `master-20220304-57b97ccb`

But there still will be some errors about load if run script immediately when all containers are ready after docker restart.
```
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=collection 431583883322720257 has not been loaded to memory or load failed)>
RPC error: [wait_for_loading_collection], <BaseException: (code=1, message=collection 431583883322720257 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-03-04 10:49:20.842630', 'RPC error': '2022-03-04 10:49:23.967830'}>
RPC error: [load_collection], <BaseException: (code=1, message=collection 431583883322720257 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-03-04 10:49:20.803971', 'RPC error': '2022-03-04 10:49:23.968158'}>
```
if waiting for several minutes, there will be no error about load.

@bigsheeper is this as expected?

**Comment by xiaofan-luan** [comment]
@zhuwenxing if this is not related to the panic we can probabaly only a another issue?

**Comment by zhuwenxing** [comment]
OK, I will close this issue, and open another one for this https://github.com/milvus-io/milvus/issues/15713#issuecomment-1058780074

**Comment by bigsheeper** [comment]
may same as #15952

**Comment by bigsheeper** [comment]
logs in cluster-03-04.log:

```
[34;1mmilvus-querynode |[0m [2022/03/04 02:49:21.722 +00:00] [WARN] [task_scheduler.go:63] ["partition 431583883322720258 hasn't been loaded or has been released"]
[34;1mmilvus-querynode |[0m [2022/03/04 02:49:21.722 +00:00] [ERROR] [impl.go:238] ["partition 431583883322720258 hasn't been loaded or has been released"] [stack="github.com/milvus-io/milvus/internal/querynode.(*QueryNode).WatchDmChannels.func1\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/impl.go:238\ngithub.com/milvus-io/milvus/internal/querynode.(*QueryNode).WatchDmChannels\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/impl.go:247\ngithub.com/milvus-io/milvus/internal/distributed/querynode.(*Server).WatchDmChannels\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/service.go:269\ngithub.com/milvus-io/milvus/internal/proto/querypb._QueryNode_WatchDmChannels_Handler.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proto/querypb/query_coord.pb.go:3420\ngithub.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38\ngithub.com/milvus-io/milvus/internal/proto/querypb._QueryNode_WatchDmChannels_Handler\n\t/go/src/github.com/milvus-io/milvus/internal/proto/querypb/query_coord.pb.go:3422\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1286\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1609\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:934"]
[34;1mmilvus-querynode |[0m [2022/03/04 02:49:22.222 +00:00] [INFO] [segment_loader.go:487] ["there are no delta logs saved with segment"] [segmentID=431583883493113857]
[34;1mmilvus-querynode |[0m [2022/03/04 02:49:22.222 +00:00] [ERROR] [segment_loader.go:155] ["load segment failed, set segment to meta failed"] [collectionID=431583883322720257] [partitionID=431583883322720258] [segmentID=431583883493113857] ["loadSegmentRequest msgID"=431583959669541834] [error="partition 431583883322720258 hasn't been loaded or has been released"] [stack="github.com/milvus-io/milvus/internal/querynode.(*segmentLoader).loadSegment\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/segment_loader.go:155\ngithub.com/milvus-io/milvus/internal/querynode.(*watchDmChannelsTask).Execute\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/task.go:297\ngithub.com/milvus-io/milvus/internal/querynode.(*taskScheduler).processTask\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:61\ngithub.com/milvus-io/milvus/internal/querynode.(*taskScheduler).taskLoop\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:78"]
[34;1mmilvus-querynode |[0m [2022/03/04 02:49:22.231 +00:00] [WARN] [task_scheduler.go:63] ["partition 431583883322720258 hasn't been loaded or has been released"]
[34;1mmilvus-querynode |[0m [2022/03/04 02:49:22.231 +00:00] [ERROR] [impl.go:238] ["partition 431583883322720258 hasn't been loaded or has been released"] [stack="github.com/milvus-io/milvus/internal/querynode.(*QueryNode).WatchDmChannels.func1\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/impl.go:238\ngithub.com/milvus-io/milvus/internal/querynode.(*QueryNode).WatchDmChannels\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/impl.go:247\ngithub.com/milvus-io/milvus/internal/distributed/querynode.(*Server).WatchDmChannels\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/service.go:269\ngithub.com/milvus-io/milvus/internal/proto/querypb._QueryNode_WatchDmChannels_Handler.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proto/querypb/query_coord.pb.go:3420\ngithub.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38\ngithub.com/milvus-io/milvus/internal/proto/querypb._QueryNode_WatchDmChannels_Handler\n\t/go/src/github.com/milvus-io/milvus/internal/proto/querypb/query_coord.pb.go:3422\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1286\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1609\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:934"]
[36mmilvus-datacoord |[0m [2022/03/04 02:54:00.953 +00:00] [INFO] [services.go:313] ["receive SaveBinlogPaths request"] [nodeID=15] [collectionID=431583883322720257] [segmentID=431584030160322561] [isFlush=false] [isDropped=false] [startPositions=null] [checkpoints="[{\"segmentID\":431584030160322561,\"position\":{\"channel_name\":\"by-dev-rootcoord-dml_0_431583883322720257v0\",\"msgID\":\"CAcQ/xEYACAA\",\"msgGroup\":\"by-dev-dataNode-15-431583883322720257\",\"timestamp\":431584035573596161},\"num_of_rows\":33000}]"]
[36mmilvus-datacoord |[0m [2022/03/04 02:54:00.954 +00:00] [INFO] [services.go:362] ["flush segment with meta"] [id=431584030160322561] [meta="[{\"fieldID\":100,\"binlogs\":[{\"entries_num\":33000,\"log_path\":\"files/insert_log/431583883322720257/431583883322720258/431584030160322561/100/431584035651977217\",\"log_size\":330609}]},{\"fieldID\":101,\"binlogs\":[{\"entries_num\":33000,\"log_path\":\"files/insert_log/431583883322720257/431583883322720258/431584030160322561/101/431584035651977218\",\"log_size\":17183}]},{\"fieldID\":102,\"binlogs\":[{\"entries_num\":33000,\"log_path\":\"files/insert_log/431583883322720257/431583883322720258/431584030160322561/102/431584035651977219\",\"log_size\":16919400}]},{\"binlogs\":[{\"entries_num\":33000,\"log_path\":\"files/insert_log/431583883322720257/431583883322720258/431584030160322561/0/431584035651977220\",\"log_size\":330609}]},{\"fieldID\":1,\"binlogs\":[{\"entries_num\":33000,\"log_path\":\"files/insert_log/431583883322720257/431583883322720258/431584030160322561/1/431584035651977221\",\"log_size\":646}]}]"]
[36mmilvus-datacoord |[0m [2022/03/04 02:54:02.216 +00:00] [INFO] [services.go:114] ["handle assign segment request"] [collectionID=431583883322720257] [partitionID=431583883322720258] [channelName=by-dev-rootcoord-dml_0_431583883322720257v0] [count=3000]
```
