### ISSUE TITLE
[Bug]: Embedded etcd ut panicked

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#15805]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2022/03/01 08:57:22.856 +00:00] [DEBUG] [embed_etcd_kv.go:181] ["LoadWithPrefix "] [prefix=/etcd/test/root/watch/a]
[2022/03/01 08:57:22.862 +00:00] [DEBUG] [embed_etcd_kv.go:181] ["LoadWithPrefix "] [prefix=/etcd/test/root/watch/y]
[2022/03/01 08:57:22.864 +00:00] [DEBUG] [embed_etcd_kv.go:181] ["LoadWithPrefix "] [prefix=/etcd/test/root/watch/z]
{"level":"info","ts":"2022-03-01T08:57:22.869Z","caller":"embed/etcd.go:367","msg":"closing etcd server","name":"default","data-dir":"etcd.test.data.dir","advertise-peer-urls":["http://localhost:2480"],"advertise-client-urls":["http://localhost:2479"]}
{"level":"info","ts":"2022-03-01T08:57:22.871Z","caller":"etcdserver/server.go:1438","msg":"skipped leadership transfer for single voting member cluster","local-member-id":"f228da3d709012fc","current-leader-member-id":"f228da3d709012fc"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1011431]

goroutine 596 [running]:
go.etcd.io/bbolt.(*Tx).Bucket(...)
	/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/tx.go:101
go.etcd.io/etcd/server/v3/mvcc/backend.(*baseReadTx).UnsafeRange(0xc0003a84b0, 0x1c9e028, 0x2489a80, 0xc0000430b0, 0x11, 0x12, 0x0, 0x0, 0x0, 0x1, ...)
	/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.0/mvcc/backend/read_tx.go:102 +0x7f1
go.etcd.io/etcd/server/v3/mvcc.(*storeTxnRead).rangeKeys(0xc0005231d0, 0x1c9d688, 0xc000044078, 0xc000302180, 0x17, 0x18, 0x0, 0x0, 0x0, 0x2b, ...)
	/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.0/mvcc/kvstore_txn.go:163 +0x949
go.etcd.io/etcd/server/v3/mvcc.(*storeTxnRead).Range(0xc0005231d0, 0x1c9d688, 0xc000044078, 0xc000302180, 0x17, 0x18, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.0/mvcc/kvstore_txn.go:62 +0x105
go.etcd.io/etcd/server/v3/mvcc.(*metricsTxnWrite).Range(0xc000523200, 0x1c9d688, 0xc000044078, 0xc000302180, 0x17, 0x18, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.0/mvcc/metrics_txn.go:41 +0x14c
go.etcd.io/etcd/server/v3/mvcc.(*readView).Range(0xc0002d2280, 0x1c9d688, 0xc000044078, 0xc000302180, 0x17, 0x18, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.0/mvcc/kv_view.go:41 +0x22d
go.etcd.io/etcd/server/v3/etcdserver/api/v3rpc.(*serverWatchStream).sendLoop(0xc000527500)
	/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.0/etcdserver/api/v3rpc/watch.go:396 +0x362
go.etcd.io/etcd/server/v3/etcdserver/api/v3rpc.(*watchServer).Watch.func1(0xc000527500)
	/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.0/etcdserver/api/v3rpc/watch.go:179 +0x39
created by go.etcd.io/etcd/server/v3/etcdserver/api/v3rpc.(*watchServer).Watch
	/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.0/etcdserver/api/v3rpc/watch.go:178 +0x399
FAIL	github.com/milvus-io/milvus/internal/kv/etcd	5.923s
FAIL
Makefile:171: recipe for target 'codecov-go' failed
Error: Process completed with exit code 2.
```

https://github.com/milvus-io/milvus/runs/5372337667?check_suite_focus=true

**Comment by yanliang567** [comment]
@XuanYang-cn are you going to fix this issue?
/assign @XuanYang-cn

**Comment by XuanYang-cn** [comment]
No reproducing lately
