### ISSUE TITLE
[Bug]: <BaseException: (code=1, message=no Available QueryNode result, filter reason [UnexpectedError] Assert "adapter->CheckSearch(conf, index_type, field_indexing->indexing_->index_mode())

### ISSUE THREAD

**Issue by sasan-ai** [milvus-io/milvus#15810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.1
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.1
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

`RPC error: [_execute_search_requests], <BaseException: (code=1, message=no Available QueryNode result, filter reason [UnexpectedError] Assert "adapter->CheckSearch(conf, index_type, field_indexing->indexing_->index_mode())" at /go/src/github.com/milvus-io/milvus/internal/core/src/query/SearchOnSealed.cpp:91
 => [SearchOnSealed]Search params check failed
: id 431533690844086303)>, <Time:{'RPC start': '2022-03-01 16:34:27.896721', 'RPC error': '2022-03-01 16:34:27.949486'}>
RPC error: [search], <BaseException: (code=1, message=no Available QueryNode result, filter reason [UnexpectedError] Assert "adapter->CheckSearch(conf, index_type, field_indexing->indexing_->index_mode())" at /go/src/github.com/milvus-io/milvus/internal/core/src/query/SearchOnSealed.cpp:91
 => [SearchOnSealed]Search params check failed
: id 431533690844086303)>, <Time:{'RPC start': '2022-03-01 16:34:27.781093', 'RPC error': '2022-03-01 16:34:27.950117'}>`

### Steps To Reproduce

```markdown
On some of the loaded partitions, doing search results in this error.
```

### Anything else?

`[2022/03/01 21:34:27.503 +00:00] [DEBUG] [collection.go:233] ["add vDeltaChannel to collection"] [collectionID=431420649320218625] [vDeltaChannel=by-dev-rootcoord-delta_2_431420649320218625v0]
[2022/03/01 21:34:27.503 +00:00] [DEBUG] [collection.go:233] ["add vDeltaChannel to collection"] [collectionID=431420649320218625] [vDeltaChannel=by-dev-rootcoord-delta_3_431420649320218625v1]
[2022/03/01 21:34:27.503 +00:00] [DEBUG] [collection.go:193] ["add pChannel to collection"] [collectionID=431420649320218625] [pChannel=by-dev-rootcoord-delta_2]
[2022/03/01 21:34:27.503 +00:00] [DEBUG] [collection.go:193] ["add pChannel to collection"] [collectionID=431420649320218625] [pChannel=by-dev-rootcoord-delta_3]
[2022/03/01 21:34:27.503 +00:00] [DEBUG] [collection.go:233] ["add vDeltaChannel to collection"] [collectionID=431420649320218625] [vDeltaChannel=by-dev-rootcoord-delta_2_431420649320218625v0]
[2022/03/01 21:34:27.503 +00:00] [DEBUG] [collection.go:233] ["add vDeltaChannel to collection"] [collectionID=431420649320218625] [vDeltaChannel=by-dev-rootcoord-delta_3_431420649320218625v1]
[2022/03/01 21:34:27.503 +00:00] [DEBUG] [collection.go:193] ["add pChannel to collection"] [collectionID=431420649320218625] [pChannel=by-dev-rootcoord-delta_2]
[2022/03/01 21:34:27.503 +00:00] [DEBUG] [collection.go:193] ["add pChannel to collection"] [collectionID=431420649320218625] [pChannel=by-dev-rootcoord-delta_3]
[2022/03/01 21:34:27.503 +00:00] [DEBUG] [tsafe_replica.go:82] ["add tSafe done"] [channel=by-dev-rootcoord-delta_2_431420649320218625v0]
[2022/03/01 21:34:27.503 +00:00] [DEBUG] [tsafe_replica.go:82] ["add tSafe done"] [channel=by-dev-rootcoord-delta_3_431420649320218625v1]
[2022/03/01 21:34:27.503 +00:00] [DEBUG] [task.go:584] ["WatchDeltaChannels done"] [collectionID=431420649320218625] [ChannelIDs="[by-dev-rootcoord-delta_2_431420649320218625v0 by-dev-rootcoord-delta_3_431420649320218625v1]\n"]
[2022/03/01 21:34:27.503 +00:00] [DEBUG] [task.go:131] ["Execute addQueryChannelTask"] [collectionID=431420649320218625]
[2022/03/01 21:34:27.503 +00:00] [DEBUG] [query_collection.go:219] ["add tSafeWatcher to queryCollection"] [collectionID=431420649320218625] [channel=by-dev-rootcoord-dml_3_431420649320218625v1]
[2022/03/01 21:34:27.503 +00:00] [DEBUG] [impl.go:291] ["watchDeltaChannelsTask WaitToFinish done"] [collectionID=431420649320218625] [nodeID=31]
[2022/03/01 21:34:27.503 +00:00] [DEBUG] [query_collection.go:183] ["register tSafe watcher and init watcher select case"] [collectionID=431420649320218625] ["dml channels"="[by-dev-rootcoord-dml_3_431420649320218625v1]"]
[2022/03/01 21:34:27.503 +00:00] [DEBUG] [query_collection.go:219] ["add tSafeWatcher to queryCollection"] [collectionID=431420649320218625] [channel=by-dev-rootcoord-delta_2_431420649320218625v0]
[2022/03/01 21:34:27.503 +00:00] [DEBUG] [query_collection.go:219] ["add tSafeWatcher to queryCollection"] [collectionID=431420649320218625] [channel=by-dev-rootcoord-delta_3_431420649320218625v1]
[2022/03/01 21:34:27.503 +00:00] [DEBUG] [query_collection.go:197] ["register tSafe watcher and init watcher select case"] [collectionID=431420649320218625] ["delta channels"="[by-dev-rootcoord-delta_2_431420649320218625v0,by-dev-rootcoord-delta_3_431420649320218625v1]"]
[2022/03/01 21:34:27.503 +00:00] [DEBUG] [task.go:152] ["add query collection"] [collectionID=431420649320218625]
time="2022-03-01T21:34:27Z" level=info msg="[Connected consumer]" consumerID=18 name=bbybw subscription=by-dev-queryNode-431420649320218625-31 topic="persistent://public/default/by-dev-search-0"
time="2022-03-01T21:34:27Z" level=info msg="[Created consumer]" consumerID=18 name=bbybw subscription=by-dev-queryNode-431420649320218625-31 topic="persistent://public/default/by-dev-search-0"
[2022/03/01 21:34:27.516 +00:00] [DEBUG] [mq_msgstream.go:636] ["MsgStream begin to seek"] [MessageID="CLmfARD/DhgAIAA="]
time="2022-03-01T21:34:27Z" level=info msg="Broker notification of Closed consumer: 18" local_addr="10.30.1.53:58890" remote_addr="pulsar://milvus2-pulsar-proxy:6650"
time="2022-03-01T21:34:27Z" level=info msg="[Reconnecting to broker in  100.843217ms]" consumerID=18 name=bbybw subscription=by-dev-queryNode-431420649320218625-31 topic="persistent://public/default/by-dev-search-0"
time="2022-03-01T21:34:27Z" level=info msg="[Connected consumer]" consumerID=18 name=bbybw subscription=by-dev-queryNode-431420649320218625-31 topic="persistent://public/default/by-dev-search-0"
time="2022-03-01T21:34:27Z" level=info msg="[Reconnected consumer to broker]" consumerID=18 name=bbybw subscription=by-dev-queryNode-431420649320218625-31 topic="persistent://public/default/by-dev-search-0"
[2022/03/01 21:34:27.621 +00:00] [DEBUG] [mq_msgstream.go:642] ["MsgStream seek finished"] [MessageID={}]
[2022/03/01 21:34:27.621 +00:00] [DEBUG] [task.go:172] ["querynode seek query channel: "] [consumeChannels="[by-dev-search-0]"] ["seek position"="\u0008\ufffd\ufffd\u0001\u0010\ufffd\u000e\u0018\u0000 \u0000"]
[2022/03/01 21:34:27.621 +00:00] [DEBUG] [task.go:188] ["start query collection"] [collectionID=431420649320218625]
[2022/03/01 21:34:27.621 +00:00] [DEBUG] [task.go:190] ["addQueryChannelTask done"] [collectionID=431420649320218625]
[2022/03/01 21:34:27.621 +00:00] [DEBUG] [impl.go:135] ["addQueryChannelTask WaitToFinish done"] [collectionID=431420649320218625] [queryChannel=by-dev-search-0] [queryResultChannel=by-dev-searchResult-0]
[2022/03/01 21:34:27.621 +00:00] [DEBUG] [query_collection.go:584] ["starting doUnsolvedMsg..."] [collectionID=431420649320218625]
[2022/03/01 21:34:27.646 +00:00] [INFO] [query_collection.go:431] ["Successfully changed global sealed segment info "] ["collection "=431420649320218625] ["online segments "="[{\"segmentID\":431420668626862082,\"collectionID\":431420649320218625,\"partitionID\":431420668535373825,\"nodeID\":31,\"segment_state\":3}]"] ["offline segments "=null]
[2022/03/01 21:34:27.646 +00:00] [INFO] [query_collection.go:431] ["Successfully changed global sealed segment info "] ["collection "=431420649320218625] ["online segments "="[{\"segmentID\":431420668626862081,\"collectionID\":431420649320218625,\"partitionID\":431420668535373825,\"nodeID\":32,\"segment_state\":3}]"] ["offline segments "=null]
[2022/03/01 21:34:27.649 +00:00] [DEBUG] [query_node.go:411] ["get SealedSegmentsChangeInfo from etcd"] [infoID=431533549205848096]
[2022/03/01 21:34:27.986 +00:00] [DEBUG] [query_collection.go:337] ["check if query timeout"] [collectionID=431420649320218625] [msgID=431533690844086303] [TimeoutTs=0] [curTime=431533711159721984] [timeoutTsPhysical=1970/01/01 00:00:00.000 +00:00] [curTimePhysical=2022/03/01 21:34:27.986 +00:00]
[2022/03/01 21:34:27.986 +00:00] [DEBUG] [time_recorder.go:78] ["receiveQueryMsg 431533690844086303: get searchable time done (0ms)"]
[2022/03/01 21:34:27.986 +00:00] [DEBUG] [query_collection.go:541] ["doing query in receiveQueryMsg..."] [collectionID=431420649320218625] [sm.GuaranteeTimestamp=1970/01/01 00:00:00.000 +00:00] [serviceTime=2022/03/01 21:34:27.587 +00:00] ["delta seconds"=18015210362] [msgID=431533690844086303] [msgType=search]
[2022/03/01 21:34:27.986 +00:00] [DEBUG] [query_collection.go:1060] ["historical search start"] [msgID=431533690844086303]
[2022/03/01 21:34:27.986 +00:00] [DEBUG] [historical.go:131] ["append search partition id"] [collectionID=431420649320218625] [partitionID=431420668535373825]
[2022/03/01 21:34:27.986 +00:00] [DEBUG] [segment.go:310] ["do search on segment"] [segmentID=431420668626862082] [segmentType=3]
Assert "adapter->CheckSearch(conf, index_type, field_indexing->indexing_->index_mode())" at /go/src/github.com/milvus-io/milvus/internal/core/src/query/SearchOnSealed.cpp:91
 => [SearchOnSealed]Search params check failed
[2022/03/01 21:34:27.986 +00:00] [WARN] [cgo_helper.go:54] ["Search failed, C Runtime Exception: [UnexpectedError] Assert \"adapter->CheckSearch(conf, index_type, field_indexing->indexing_->index_mode())\" at /go/src/github.com/milvus-io/milvus/internal/core/src/query/SearchOnSealed.cpp:91\n => [SearchOnSealed]Search params check failed\n"]
[2022/03/01 21:34:27.986 +00:00] [DEBUG] [time_recorder.go:78] ["receiveQueryMsg 431533690844086303: operation done (0ms)"]
[2022/03/01 21:34:27.986 +00:00] [DEBUG] [proxy_session_manager.go:108] ["success to send search result"] [node=37] [base="msg_type:SearchResult msgID:431533690844086303 timestamp:431533711147139073 sourceID:37 "]
[2022/03/01 21:34:27.986 +00:00] [DEBUG] [query_collection.go:566] ["do query failed in receiveQueryMsg, publish failed query result"] [collectionID=431420649320218625] [msgID=431533690844086303] [msgType=search]
[2022/03/01 21:34:27.986 +00:00] [WARN] [query_collection.go:371] ["[UnexpectedError] Assert \"adapter->CheckSearch(conf, index_type, field_indexing->indexing_->index_mode())\" at /go/src/github.com/milvus-io/milvus/internal/core/src/query/SearchOnSealed.cpp:91\n => [SearchOnSealed]Search params check failed"]
`

**Comment by yanliang567** [comment]
@sasan-ai Thank you for the issue. We did not see this error before. Do you happen to have a simple reproduce steps so that we can try to reproduce it? 
Also it would be great if you could upload the full logs for querynode and querycoord

/assign @sasan-ai 
/unassign

**Comment by sasan-ai** [comment]
index_param = {"index_type": "IVF_SQ8", 
                         "params":
                             {"nlist": 1200},
                         "metric_type": "L2"}

**Comment by yanliang567** [comment]
@soothing-rain could you please help on this issue?
/assign @soothing-rain 
/unassing @sasan-ai

**Comment by xiaofan-luan** [comment]
> 

please check if you search parameter is same (especially for metric type)

**Comment by whj0401** [comment]
It seems I met the same error.
The interesting thing is that when there are few entities (134) in the collection, my code runs smoothly.
However, when I increase the size of the database to over 15,000, I met the error.

I wonder whether it is really because of the wrong parameters since the code successfully runs while testing on a small dataset.
I am trapped here and really need some help.
Thanks in advance. I am looking forward to your reply @xiaofan-luan 

My code:
```
>>> x = numpy.random.random((128,))
>>> c
<Collection>:
-------------
<name>: test_PalmTree_OSS_DB
<partitions>: [{"name": "_default", "collection_name": "test_PalmTree_OSS_DB", "description": ""}]
<description>: OSS graph embedding database
<schema>: {
  auto_id: False
  description: OSS graph embedding database
  fields: [{
    name: func_id
    description: 
    type: 5
    is_primary: True
    auto_id: False
  }, {
    name: func_graph_vector
    description: 
    type: 101
    params: {'dim': 128}
  }]
}

>>> c.indexes[0].params
{'metric_type': 'IP', 'index_type': 'IVF_FLAT', 'params': {'nlist': 10}}
>>> c.num_entities
15038
>>> res = c.search(data=[x],
                        anns_field='func_graph_vector',
                        param={'metric_type': 'IP', 'nprobe': 1},
                        limit=10,
                        expr=None,
                        consistency_level='Strong')
```
The error message:
```
RPC error: [_execute_search_requests], <BaseException: (code=1, message=QueryNode search fail, reason [UnexpectedError] Assert "adapter->CheckSearch(conf, index_type, field_indexing->indexing_->index_mode())" at /root/milvus-2.0.2/milvus/internal/core/src/query/SearchOnSealed.cpp:91
 => [SearchOnSealed]Search params check failed
: id 432753758716312489)>, <Time:{'RPC start': '2022-04-25 02:50:18.687036', 'RPC error': '2022-04-25 02:50:18.914643'}>
RPC error: [search], <BaseException: (code=1, message=QueryNode search fail, reason [UnexpectedError] Assert "adapter->CheckSearch(conf, index_type, field_indexing->indexing_->index_mode())" at /root/milvus-2.0.2/milvus/internal/core/src/query/SearchOnSealed.cpp:91
 => [SearchOnSealed]Search params check failed
: id 432753758716312489)>, <Time:{'RPC start': '2022-04-25 02:50:18.685221', 'RPC error': '2022-04-25 02:50:18.914755'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/export/d1/hwangdz/py3-envs/milvus/lib/python3.7/site-packages/pymilvus/orm/collection.py", line 691, in search
    partition_names, output_fields, timeout, round_decimal, **kwargs)
  File "/export/d1/hwangdz/py3-envs/milvus/lib/python3.7/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/export/d1/hwangdz/py3-envs/milvus/lib/python3.7/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/export/d1/hwangdz/py3-envs/milvus/lib/python3.7/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/export/d1/hwangdz/py3-envs/milvus/lib/python3.7/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/export/d1/hwangdz/py3-envs/milvus/lib/python3.7/site-packages/pymilvus/decorators.py", line 21, in handler
    return func(self, *args, **kwargs)
  File "/export/d1/hwangdz/py3-envs/milvus/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 457, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/export/d1/hwangdz/py3-envs/milvus/lib/python3.7/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/export/d1/hwangdz/py3-envs/milvus/lib/python3.7/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/export/d1/hwangdz/py3-envs/milvus/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 404, in _execute_search_requests
    raise pre_err
  File "/export/d1/hwangdz/py3-envs/milvus/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 395, in _execute_search_requests
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=QueryNode search fail, reason [UnexpectedError] Assert "adapter->CheckSearch(conf, index_type, field_indexing->indexing_->index_mode())" at /root/milvus-2.0.2/milvus/internal/core/src/query/SearchOnSealed.cpp:91
 => [SearchOnSealed]Search params check failed
: id 432753758716312489)>
```

**Comment by yaroslavm** [comment]
Hi @whj0401, set `nprobe` as search param. I've written more details here: https://github.com/milvus-io/milvus/issues/15294
