### ISSUE TITLE
[Bug]: load segment hit nil pointer dereference

### ISSUE THREAD

**Issue by avsolatorio** [milvus-io/milvus#15824]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.0.1
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.0.1
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 64GB
- GPU: N/A
- Others: N/A
```

### Current Behavior

The `milvus-standalone` service dies when I load the collection after inserting 1M data. It also dies with just 500K of inserted data.

```python
In [2]: doc_milvus = DocumentsMilvusInterface(collection_id="test", dim=100)                                                                                            

In [3]:         num_entities = 1_000_000 
   ...:         data = [ 
   ...:             [i for i in range(num_entities)], 
   ...:             [i for i in np.random.randint(1950, 2023, num_entities)], 
   ...:             [i for i in np.random.randint(0, 5, num_entities)], 
   ...:             [i for i in np.random.randint(0, 2, num_entities)], 
   ...:             np.random.random((num_entities, doc_milvus.dim)).tolist(), 
   ...:         ]                                                                                                                                                       

In [4]: ins = doc_milvus.insert(data)                                                                                                                                   

In [5]: ins                                                                                                                                                             
Out[5]: (insert count: 1000000, delete count: 0, upsert count: 0, timestamp: 431542765419757569)

In [6]: doc_milvus.load_collection()                                                                                                                                    
grpc RpcError: [wait_for_loading_collection], <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, Socket closed>, <Time:{'RPC start': '2022-03-02 02:11:03.535764', 'gRPC error': '2022-03-02 02:11:04.543046'}>
```

The docker logs show the following:
```
[2022/03/02 07:11:04.041 +00:00] [DEBUG] [impl.go:795] ["ShowCollections Done"] [role=proxy] [MsgID=431542780073607174] [DbName=] [TimeStamp=0] [ShowType=InMemory] [CollectionNames="[documents$test]"] [result="status:<> collection_names:\"documents$test\" collection_ids:431542756572597569 created_timestamps:431542756572397572 created_utc_timestamps:1646204973497 inMemory_percentages:0 "]
[2022/03/02 07:11:04.048 +00:00] [DEBUG] [segment.go:500] [QueryNode::Segment::InsertBegin] [cNumOfRows=199971]
[2022/03/02 07:11:04.175 +00:00] [DEBUG] [segment_loader.go:371] ["Do insert done in segment loader"] [len=199971] [segmentID=431542766153760769] [collectionID=431542756572597569]
[2022/03/02 07:11:04.175 +00:00] [DEBUG] [segment_loader.go:219] ["loading bloom filter..."]
[2022/03/02 07:11:04.180 +00:00] [DEBUG] [segment_loader.go:227] ["loading delta..."]
[2022/03/02 07:11:04.180 +00:00] [INFO] [segment_loader.go:479] ["there are no delta logs saved with segment"] [segmentID=431542766153760769]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1ae25ae]

goroutine 278 [running]:
github.com/milvus-io/milvus/internal/querynode.(*segmentLoader).loadSegment(0xc0010ae960, 0xc02139fa98, 0xc000000002, 0x2, 0x2)
        /go/src/github.com/milvus-io/milvus/internal/querynode/segment_loader.go:151 +0x15ae
github.com/milvus-io/milvus/internal/querynode.(*watchDmChannelsTask).Execute(0xc005742930, 0x34c06d0, 0xc00027d940, 0x0, 0x0)
        /go/src/github.com/milvus-io/milvus/internal/querynode/task.go:290 +0xf3f
github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).processTask(0xc00027d980, 0x34d35d8, 0xc005742930, 0x34d1750, 0xc00048c0f0)
        /go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:61 +0x173
github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).taskLoop(0xc00027d980)
        /go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:78 +0x15a
created by github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).Start
        /go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:86 +0x5c
```

The `DocumentsMilvusInterface` is an interface that I implemented for my application,  shown below:

```python
from collections import OrderedDict
import numpy as np

from pymilvus import (
    connections, utility, Collection,
    CollectionSchema, FieldSchema, DataType,
)


class MilvusInterface:
    """This is the interface to the Milvus server."""

    def __init__(self, alias="default", host="localhost", port="19530"):
        self.alias = alias
        self.host = host
        self.port = port

    def connect(self):
        """Create a connection to the milvus server if not connected."""

        if not utility.connections.has_connection(self.alias):
            connections.connect(
                alias=self.alias,
                host=self.host,
                port=self.port)

    def disconnect(self):
        """Disconnect the connection to the milvus server."""
        connections.disconnect(self.alias)


class DocumentsMilvusInterface(MilvusInterface):
    """Interface for the documents collection."""

    def __init__(self, collection_id, dim):
        super().__init__()
        self.connect()

        self.index_params = {
            "metric_type": "IP",
            "index_type": "FLAT",
            "params": {},
        }

        self.collection_loaded = False
        self.dim = dim
        self.collection_id = collection_id
        self.collection_name = f"documents${self.collection_id}"

        self.field_schemas = OrderedDict()
        self.schema = self.create_schema()

    def create_schema(self):
        """Create schema for the documents collection."""

        self.field_schemas["int_id"] = FieldSchema(
            name="int_id",
            dtype=DataType.INT64,
            is_primary=True,
        )

        self.field_schemas["year"] = FieldSchema(
            name="year",
            dtype=DataType.INT64,
        )

        self.field_schemas["source"] = FieldSchema(
            name="source",
            dtype=DataType.INT64,
        )

        self.field_schemas["major_doc_type"] = FieldSchema(
            name="major_doc_type",
            dtype=DataType.INT64,
        )

        self.field_schemas["vector"] = FieldSchema(
            name="vector",
            dtype=DataType.FLOAT_VECTOR,
            dim=self.dim
        )

        schema = CollectionSchema(
            fields=[self.field_schemas[k] for k in self.field_schemas],
            description="Documents collection for semantic search."
        )

        return schema

    def get_or_create_collection(self):
        """Create collection if not available."""

        if not utility.has_collection(self.collection_name):
            collection = Collection(
                name=self.collection_name,
                schema=self.schema,
                using=self.alias,
                shards_num=5,
                consistency_level="Strong"
            )
        else:
            collection = Collection(self.collection_name)

        return collection

    def drop_collection(self):
        """Drop the documents cllection."""

        utility.drop_collection(self.collection_name)

    def insert(self, data, partition_name=None):
        """Insert data to the documents collection.

        :Example
        ```
        import numpy as np

        doc_milvus = DocumentsMilvusInterface(collection_id="test", dim=100)
        num_entities = 1_000_000
        data = [
            [i for i in range(num_entities)],
            [i for i in np.random.randint(1950, 2023, num_entities)],
            [i for i in np.random.randint(0, 5, num_entities)],
            [i for i in np.random.randint(0, 2, num_entities)],
            np.random.random((num_entities, doc_milvus.dim)).tolist(),
        ]
        doc_milvus.insert(data)
        ```
        """

        collection = self.get_or_create_collection()
        mr = collection.insert(data, partition_name=partition_name)

        return mr

    def delete(self, int_ids, partition_name=None):
        """Delete records from the collection corresponding to the provided `int_ids`."""

        expr = f"int_id in {int_ids}"
        collection = self.get_or_create_collection()
        collection.delete(expr, partition_name=partition_name)

    def create_vector_index(self):
        """Create the index for the vector field."""

        collection = self.get_or_create_collection()

        status = collection.create_index(
            field_name="vector",
            index_params=self.index_params
        )

        return status

    def drop_vector_index(self):
        """Drop the existing vector index."""

        collection = self.get_or_create_collection()

        collection.drop_index()

    def search(
            self, data, field_name, limit=10, expr=None, partition_names=None,
            output_fields=None, round_decimal=-1):
        """Search the documents collection."""

        assert field_name in self.field_schemas

        if isinstance(data, np.ndarray):
            if data.ndim == 1:
                data = data.reshape(1, -1)

            # Only support 2-d data.
            assert data.ndim == 2

            # Make sure the dimension is correct.
            assert data.shape[1] == self.dim

            # Milvus accepts lists.
            data = data.tolist()

        collection = self.get_or_create_collection()

        search_params = {"metric_type": "IP"}

        results = collection.search(
            data=data,
            anns_field=field_name,
            param=search_params,
            limit=limit,
            expr=expr,
            partition_names=partition_names,
            output_fields=output_fields,
            round_decimal=round_decimal,
            consistency_level="Strong"
        )

        return results

    def load_collection(self):
        """Load the collection to memory."""

        collection = self.get_or_create_collection()
        collection.load()

        self.collection_loaded = True

    def release_collection(self):
        """Release the collection from memory."""

        collection = self.get_or_create_collection()
        collection.release()

        self.collection_loaded = False

```

### Expected Behavior

I am expecting that the milvus server will not crash when loading the collection.

### Steps To Reproduce

```markdown
To reproduce:
1. Download the standalone docker-compose file: `wget https://github.com/milvus-io/milvus/releases/download/v2.0.1/milvus-standalone-docker-compose.yml -O docker-compose.yml`
2. Start the services: `sudo docker-compose up -d`
3. Install pymilvus: `pip install -U pymilvus`
4. Copy the code above in a Python/IPython shell.
```

**Comment by xiaofan-luan** [comment]
I will investigate into it

**Comment by xiaofan-luan** [comment]
duplicate with #15713

**Comment by xiaofan-luan** [comment]
should be fixed next version

**Comment by xiaofan-luan** [comment]
hi @avsolatorio, it should be fixed soon in the next release. You can use the day build or wait for the next release for now

**Comment by W2Q3Q1** [comment]
Hello, we are facing the same problem. Is there any thing we can do ourselves to prevent that crash, like avoid doing some specific actions? Do we have to wait for the next version?

**Comment by avsolatorio** [comment]
> 

I used the nightly build for now. :)

**Comment by avsolatorio** [comment]
> Hello, we are facing the same problem. Is there any thing we can do ourselves to prevent that crash, like avoid doing some specific actions? Do we have to wait for the next version?

I used the nightly build for now. :)

**Comment by xiaofan-luan** [comment]
> 

Hey @avsolatorio ,does daily build works for you? We will soon release 2.0.2 once all known issues solved

**Comment by avsolatorio** [comment]
> > 
> 
> Hey @avsolatorio ,does daily build works for you? We will soon release 2.0.2 once all known issues solved

Hello @xiaofan-luan , yes it got fixed on the daily build. :) 

Here's my milvus service, using the daily build with the fix.
```
  standalone:
    container_name: milvus-standalone
    # image: milvusdb/milvus:v2.0.1
    image: milvusdb/daily-build:master-20220302-27a7875a
    command: ["milvus", "run", "standalone"]
```

Here's a screenshot showing the search working with 1M records inserted in the index.

<img width="1224" alt="image" src="https://user-images.githubusercontent.com/3009596/158454834-0b8f794e-016b-4887-97af-d4f43bf3ee51.png">
