### ISSUE TITLE
[Bug]: [Nightly]Create partition failed for timeout error

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#15866]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 7a3a721
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.0.1.dev3 
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

create partition failed

### Expected Behavior

Create partition successfully

### Steps To Reproduce

Running nightly:
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/378/pipeline

```python
test case:


    def test_search_index_partitions_fuzzy(self, nb, nq, dim, partition_names, auto_id, _async):
        """
        target: test search from partitions
        method: search from partitions with fuzzy
                partition name
        expected: searched successfully
        """
        # 1. initialize with data
        collection_w, _, _, insert_ids = self.init_collection_general(prefix, True, nb,
                                                                      partition_num=1,
                                                                      auto_id=auto_id,
                                                                      dim=dim)[0:4]
        vectors = [[random.random() for _ in range(dim)] for _ in range(nq)]
        # 2. create index
        default_index = {"index_type": "IVF_FLAT", "params": {"nlist": 128}, "metric_type": "L2"}
        collection_w.create_index("float_vector", default_index)
        # 3. search through partitions
        log.info("test_search_index_partitions_fuzzy: searching through partitions")
        limit = 1000
        limit_check = limit
        par = collection_w.partitions
        if partition_names == ["search(.*)"]:
            insert_ids = insert_ids[par[0].num_entities:]
            if limit > par[1].num_entities:
                limit_check = par[1].num_entities
        collection_w.search(vectors[:nq], default_search_field,
                            default_search_params, limit, default_search_exp,
                            partition_names, _async=_async,
                            check_task=CheckTasks.check_search_results,
                            check_items={"nq": nq,
                                         "ids": insert_ids,
                                         "limit": limit_check,
                                         "_async": _async})
```

### Anything else?

1 Log:
[artifacts-milvus-distributed-master-378-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/378/artifact/artifacts-milvus-distributed-master-378-pymilvus-e2e-logs.tar.gz)

2 Test case fail time:
[2022-03-03T19:47:32.363Z] [gw3] [ 83%] FAILED testcases/test_search_20.py::TestCollectionSearch::test_search_index_partitions_fuzzy[5000-500-128-True-False-partition_names0] 

3 collection name: search_collection_eKlghgmV

4 Test case trace:
```
[2022-03-03T20:11:54.758Z] [2022-03-03 19:46:59 - DEBUG - ci_test]: (api_request)  : [Collection] args: ['search_collection_eKlghgmV', {
[2022-03-03T20:11:54.758Z]   auto_id: True
[2022-03-03T20:11:54.758Z]   description: 
[2022-03-03T20:11:54.758Z]   fields: [{
[2022-03-03T20:11:54.758Z]     name: int64
[2022-03-03T20:11:54.758Z]     description: 
[2022-03-03T20:11:54.758Z]     type: 5
[2022-03-03T20:11:54.758Z]     is_primary: True
[2022-03-03T20:11:54.758Z]     auto_id: True
[2022-03-03T20:11:54.758Z]   }, {
[2022-03-03T20:11:54.758Z]     name: float
[2022-03-03T20:11:54.758Z]     description: 
[2022-03-03T20:11:54.758Z]     type: 10
[2022-03-03T20:11:54.758Z]   }, {
[2022-03-03T20:11:54.758Z]     name: float_vector
[2022-03-03T20:11:54.758Z]     description: 
[2022-03-03T20:11:54.758Z]     type: 101
[2022-03-03T20:11:54.758Z]     params: {'dim': 1......, kwargs: {'consistency_level': 'Strong'} (api_request.py:55)
[2022-03-03T20:11:54.758Z] [2022-03-03 19:47:00 - DEBUG - ci_test]: (api_response) : <Collection>:
[2022-03-03T20:11:54.758Z] -------------
[2022-03-03T20:11:54.758Z] <name>: search_collection_eKlghgmV
[2022-03-03T20:11:54.758Z] <partitions>: [{"name": "_default", "collection_name": "search_collection_eKlghgmV", "description": ""}]
[2022-03-03T20:11:54.758Z] <description>: 
[2022-03-03T20:11:54.758Z] <schema>: {
[2022-03-03T20:11:54.758Z]   auto_id: True
[2022-03-03T20:11:54.758Z]   description: 
[2022-03-03T20:11:54.758Z]   fields: [{
[2022-03-03T20:11:54.758Z]     name: int64
[2022-03-03T20:11:54.758Z]     description: 
[2022-03-03T20:11:54.758Z]     type: 5
[2022-03-03T20:11:54.758Z]     is_primar......  (api_request.py:27)
[2022-03-03T20:11:54.758Z] [2022-03-03 19:47:00 - INFO - ci_test]: gen_partitions: creating partitions (common_func.py:481)
[2022-03-03T20:11:54.758Z] [2022-03-03 19:47:00 - DEBUG - ci_test]: (api_request)  : [Collection.create_partition] args: ['search_partition_0', 'search partition'], kwargs: {} (api_request.py:55)
[2022-03-03T20:11:54.758Z] [2022-03-03 19:47:30 - ERROR - pymilvus.decorators]: RPC error: [create_partition], <BaseException: (code=1, message=CreatePartition failed: message send timeout: TimeoutError)>, <Time:{'RPC start': '2022-03-03 19:47:00.468330', 'RPC error': '2022-03-03 19:47:30.476535'}> (decorators.py:73)
[2022-03-03T20:11:54.758Z] [2022-03-03 19:47:30 - ERROR - ci_test]: Traceback (most recent call last):
[2022-03-03T20:11:54.758Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
[2022-03-03T20:11:54.758Z]     res = func(*args, **kwargs)
[2022-03-03T20:11:54.758Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 56, in api_request
[2022-03-03T20:11:54.758Z]     return func(*arg, **kwargs)
[2022-03-03T20:11:54.758Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 871, in create_partition
[2022-03-03T20:11:54.758Z]     return Partition(self, partition_name, description=description)
[2022-03-03T20:11:54.758Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/partition.py", line 38, in __init__
[2022-03-03T20:11:54.758Z]     conn.create_partition(self._collection.name, self._name)
[2022-03-03T20:11:54.758Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 56, in handler
[2022-03-03T20:11:54.758Z]     raise e
[2022-03-03T20:11:54.759Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 41, in handler
[2022-03-03T20:11:54.759Z]     return func(self, *args, **kwargs)
[2022-03-03T20:11:54.759Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler
[2022-03-03T20:11:54.759Z]     raise e
[2022-03-03T20:11:54.759Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler
[2022-03-03T20:11:54.759Z]     return func(*args, **kwargs)
[2022-03-03T20:11:54.759Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 192, in create_partition
[2022-03-03T20:11:54.759Z]     raise BaseException(response.error_code, response.reason)
[2022-03-03T20:11:54.759Z] pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=CreatePartition failed: message send timeout: TimeoutError)>
[2022-03-03T20:11:54.759Z]  (api_request.py:35)
[2022-03-03T20:11:54.759Z] [2022-03-03 19:47:30 - ERROR - ci_test]: (api_response) : <BaseException: (code=1, message=CreatePartition failed: message send timeout: TimeoutError)> (api_request.py:36)
```

**Comment by jaime0815** [comment]
it seems like a connection timeout issue when Rootcoord access Pulsar 

`[2022/03/03 19:47:30.474 +00:00] [ERROR] [root_coord.go:1480] ["CreatePartition failed"] [role=rootcoord] ["collection name"=search_collection_eKlghgmV] ["partition name"=search_partition_0] [msgID=431577260832231332] [error="message send timeout: TimeoutError"] [stack="github.com/milvus-io/milvus/internal/rootcoord.(*Core).CreatePartition\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:1480\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).CreatePartition\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:364\ngithub.com/milvus-io/milvus/internal/proto/rootcoordpb._RootCoord_CreatePartition_Handler.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proto/rootcoordpb/root_coord.pb.go:1005\ngithub.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38\ngithub.com/milvus-io/milvus/internal/proto/rootcoordpb._RootCoord_CreatePartition_Handler\n\t/go/src/github.com/milvus-io/milvus/internal/proto/rootcoordpb/root_coord.pb.go:1007\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1286\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1609\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:934"]
`

**Comment by jaime0815** [comment]
NPE occurs at the same time in Plsuar log

> 19:47:00.476 [pulsar-io-4-1] INFO  org.apache.pulsar.broker.service.AbstractDispatcherSingleActiveConsumer - Removing consumer Consumer{subscription=PersistentSubscription{topic=persistent://public/default/by-dev-rootcoord-dml_7, name=by-dev-dataNode-13-431577319447461889}, consum
erId=2044, consumerName=yuhen, address=/10.202.31.252:36654}

19:47:00.476 [pulsar-io-4-1] INFO  org.apache.pulsar.broker.service.persistent.PersistentSubscription - [persistent://public/default/by-dev-rootcoord-dml_7][by-dev-dataNode-13-431577319447461889] Successfully disconnected consumers from subscription, proceeding with cursor reset

19:47:00.477 [BookKeeperClientWorker-OrderedExecutor-1-0] ERROR org.apache.bookkeeper.common.util.SafeRunnable - Unexpected throwable caught

java.lang.NullPointerException: null

        at org.apache.bookkeeper.mledger.impl.EntryImpl.getLength(EntryImpl.java:133) ~[org.apache.pulsar-managed-ledger-2.8.2.jar:2.8.2]

        at org.apache.bookkeeper.mledger.util.RangeCache.put(RangeCache.java:78) ~[org.apache.pulsar-managed-ledger-2.8.2.jar:2.8.2]

        at org.apache.bookkeeper.mledger.impl.EntryCacheImpl.insert(EntryCacheImpl.java:114) ~[org.apache.pulsar-managed-ledger-2.8.2.jar:2.8.2]

        at org.apache.bookkeeper.mledger.impl.OpAddEntry.safeRun(OpAddEntry.java:197) ~[org.apache.pulsar-managed-ledger-2.8.2.jar:2.8.2]

        at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36) [org.apache.bookkeeper-bookkeeper-common-4.14.3.jar:4.14.3]

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]

        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]

        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.72.Final.jar:4.1.72.Final]

        at java.lang.Thread.run(Thread.java:829) [?:?]

19:47:00.478 [BookKeeperClientWorker-OrderedExecutor-1-0] INFO  org.apache.bookkeeper.mledger.impl.ManagedCursorImpl - [public/default/persistent/by-dev-rootcoord-dml_7] Initiate reset position to 44:679 on cursor by-dev-dataNode-13-431577319447461889

19:47:00.478 [broker-topic-workers-OrderedScheduler-4-0] INFO  org.apache.bookkeeper.mledger.impl.ManagedCursorImpl - [public/default/persistent/by-dev-rootcoord-dml_7-by-dev-dataNode-13-431577319447461889] Rewind from 44:1 to 44:0

19:47:00.480 [BookKeeperClientWorker-OrderedExecutor-0-0] INFO  org.apache.bookkeeper.mledger.impl.ManagedCursorImpl - [public/default/persistent/by-dev-rootcoord-dml_7] reset position to 44:679 skipping from current read position 44:0 on cursor by-dev-dataNode-13-431577319447461889

**Comment by xiaofan-luan** [comment]
@jaime0815 we will close this issue if don't want to fix it? anything we can do to retry when pulsar hit error?

**Comment by binbinlv** [comment]
@jaime0815 

How about this issue? If there is no fix plan, and considering it has not been reproduced for a period of time, I will close this issue, thanks.

**Comment by binbinlv** [comment]
Close it first for not reproducable.
