### ISSUE TITLE
[Bug]:[chaos][minio]create collection raise error when running test_e2e.py after minio pod recovered from memory stress chaos

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#15873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220304-3e862ecd
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus==2.0.1.dev3
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2022-03-04 07:27:19 - ERROR - pymilvus.decorators]: RPC error: [has_collection], <BaseException: (code=1, message=syncTimestamp Failed:context canceled)>, <Time:{'RPC start': '2022-03-04 07:27:19.407906', 'RPC error': '2022-03-04 07:27:19.409503'}> (decorators.py:73)
[2022-03-04 07:27:19 - ERROR - ci_test]: Traceback (most recent call last):
  File "/home/runner/work/milvus/milvus/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
    res = func(*args, **kwargs)
  File "/home/runner/work/milvus/milvus/tests/python_client/utils/api_request.py", line 56, in api_request
    return func(*arg, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/orm/collection.py", line [125](https://github.com/zhuwenxing/milvus/runs/5418698574?check_suite_focus=true#step:12:125), in __init__
    has = conn.has_collection(self._name)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 156, in has_collection
    raise BaseException(reply.status.error_code, reply.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=syncTimestamp Failed:context canceled)>
 (api_request.py:35)
[2022-03-04 07:27:19 - ERROR - ci_test]: (api_response) : <BaseException: (code=1, message=syncTimestamp Failed:context canceled)> (api_request.py:36)
```

### Expected Behavior

all test cases passed

### Steps To Reproduce

```markdown
see https://github.com/zhuwenxing/milvus/runs/5418698574?check_suite_focus=true
```

### Anything else?

failed job: https://github.com/zhuwenxing/milvus/runs/5418698574?check_suite_focus=true

logs: https://github.com/zhuwenxing/milvus/suites/5532234335/artifacts/177812062

**Comment by yanliang567** [comment]
/assign @congqixia 
@congqixia could you please help on this issue?

/unassign

**Comment by xiaofan-luan** [comment]
keep tracking
