### ISSUE TITLE
[Bug]: [benchmark][cluster] Failed to insert 1b vector, message=getSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#15889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.2-20220304-3f34bc1a
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus==2.0.2.dev5
```

### Current Behavior

client pod:benchmark-wql8c-3437145852
client log

```
[2022-03-04 10:10:56,834] [   ERROR] - RPC error: [bulk_insert], <BaseException: (code=1, message=getSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error)>, <Time:{'RPC start': '2022-03-04 10:10:45.637427', 'RPC error': '2022-03-04 10:10:56.834459'}> (pymilvus.decorators:73)
[2022-03-04 10:10:56,836] [   ERROR] - <BaseException: (code=1, message=getSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error)> (milvus_benchmark.client:166)
[2022-03-04 10:10:56,838] [   DEBUG] - Milvus insert run in 11.2014s (milvus_benchmark.client:53)
[2022-03-04 10:11:06,840] [   DEBUG] - Row count: 126822458 in collection: <sift_1b_128_l2> (milvus_benchmark.client:421)
[2022-03-04 10:11:06,840] [   DEBUG] - 126822458 (milvus_benchmark.runners.base:89)
[2022-03-04 10:11:07,432] [   DEBUG] - Start id: 126950000, end id: 127000000 (milvus_benchmark.runners.base:76)
[2022-03-04 10:12:46,883] [   ERROR] - RPC error: [bulk_insert], <BaseException: (code=1, message=getSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error)>, <Time:{'RPC start': '2022-03-04 10:11:07.436282', 'RPC error': '2022-03-04 10:12:46.883326'}> (pymilvus.decorators:73)
[2022-03-04 10:12:46,884] [   ERROR] - <BaseException: (code=1, message=getSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error)> (milvus_benchmark.client:166)
[2022-03-04 10:13:47,694] [   ERROR] - RPC error: [describe_collection], <DescribeCollectionException: (code=1, message=syncTimestamp Failed:err: number of RootCoord is incorrect, 0
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:253 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall
/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/client/client.go:327 github.com/milvus-io/milvus/internal/distributed/rootcoord/client.(*Client).AllocTimestamp
/go/src/github.com/milvus-io/milvus/internal/proxy/timestamp.go:57 github.com/milvus-io/milvus/internal/proxy.(*timestampAllocator).alloc
/go/src/github.com/milvus-io/milvus/internal/proxy/timestamp.go:77 github.com/milvus-io/milvus/internal/proxy.(*timestampAllocator).AllocOne
/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:181 github.com/milvus-io/milvus/internal/proxy.(*baseTaskQueue).Enqueue
/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:357 github.com/milvus-io/milvus/internal/proxy.(*ddTaskQueue).Enqueue
/go/src/github.com/milvus-io/milvus/internal/proxy/impl.go:641 github.com/milvus-io/milvus/internal/proxy.(*Proxy).DescribeCollection
/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:463 github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).DescribeCollection
/go/src/github.com/milvus-io/milvus/internal/proto/milvuspb/milvus.pb.go:5950 github.com/milvus-io/milvus/internal/proto/milvuspb._MilvusService_DescribeCollection_Handler.func1
)>, <Time:{'RPC start': '2022-03-04 10:13:47.689562', 'RPC error': '2022-03-04 10:13:47.694178'}> (pymilvus.decorators:73)
[2022-03-04 10:13:47,694] [   ERROR] - RPC error: [bulk_insert], <DescribeCollectionException: (code=1, message=syncTimestamp Failed:err: number of RootCoord is incorrect, 0
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:253 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall
/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/client/client.go:327 github.com/milvus-io/milvus/internal/distributed/rootcoord/client.(*Client).AllocTimestamp
/go/src/github.com/milvus-io/milvus/internal/proxy/timestamp.go:57 github.com/milvus-io/milvus/internal/proxy.(*timestampAllocator).alloc
/go/src/github.com/milvus-io/milvus/internal/proxy/timestamp.go:77 github.com/milvus-io/milvus/internal/proxy.(*timestampAllocator).AllocOne
/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:181 github.com/milvus-io/milvus/internal/proxy.(*baseTaskQueue).Enqueue
/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:357 github.com/milvus-io/milvus/internal/proxy.(*ddTaskQueue).Enqueue
/go/src/github.com/milvus-io/milvus/internal/proxy/impl.go:641 github.com/milvus-io/milvus/internal/proxy.(*Proxy).DescribeCollection
/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:463 github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).DescribeCollection
/go/src/github.com/milvus-io/milvus/internal/proto/milvuspb/milvus.pb.go:5950 github.com/milvus-io/milvus/internal/proto/milvuspb._MilvusService_DescribeCollection_Handler.func1
)>, <Time:{'RPC start': '2022-03-04 10:13:47.689535', 'RPC error': '2022-03-04 10:13:47.694844'}> (pymilvus.decorators:73)
[2022-03-04 10:13:47,695] [   ERROR] - <DescribeCollectionException: (code=1, message=syncTimestamp Failed:err: number of RootCoord is incorrect, 0
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:253 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall
/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/client/client.go:327 github.com/milvus-io/milvus/internal/distributed/rootcoord/client.(*Client).AllocTimestamp
/go/src/github.com/milvus-io/milvus/internal/proxy/timestamp.go:57 github.com/milvus-io/milvus/internal/proxy.(*timestampAllocator).alloc
/go/src/github.com/milvus-io/milvus/internal/proxy/timestamp.go:77 github.com/milvus-io/milvus/internal/proxy.(*timestampAllocator).AllocOne
/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:181 github.com/milvus-io/milvus/internal/proxy.(*baseTaskQueue).Enqueue
/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:357 github.com/milvus-io/milvus/internal/proxy.(*ddTaskQueue).Enqueue
/go/src/github.com/milvus-io/milvus/internal/proxy/impl.go:641 github.com/milvus-io/milvus/internal/proxy.(*Proxy).DescribeCollection
/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:463 github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).DescribeCollection
/go/src/github.com/milvus-io/milvus/internal/proto/milvuspb/milvus.pb.go:5950 github.com/milvus-io/milvus/internal/proto/milvuspb._MilvusService_DescribeCollection_Handler.func1
)> (milvus_benchmark.client:166)
[2022-03-04 10:13:47,695] [   DEBUG] - Milvus insert run in 0.0062s (milvus_benchmark.client:53)
[2022-03-04 10:13:47,699] [   ERROR] - RPC error: [get_collection_stats], <BaseException: (code=1, message=syncTimestamp Failed:err: number of RootCoord is incorrect, 0
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:253 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall
/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/client/client.go:327 github.com/milvus-io/milvus/internal/distributed/rootcoord/client.(*Client).AllocTimestamp
/go/src/github.com/milvus-io/milvus/internal/proxy/timestamp.go:57 github.com/milvus-io/milvus/internal/proxy.(*timestampAllocator).alloc
/go/src/github.com/milvus-io/milvus/internal/proxy/timestamp.go:77 github.com/milvus-io/milvus/internal/proxy.(*timestampAllocator).AllocOne
/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:181 github.com/milvus-io/milvus/internal/proxy.(*baseTaskQueue).Enqueue
/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:357 github.com/milvus-io/milvus/internal/proxy.(*ddTaskQueue).Enqueue
/go/src/github.com/milvus-io/milvus/internal/proxy/impl.go:737 github.com/milvus-io/milvus/internal/proxy.(*Proxy).GetCollectionStatistics
/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:468 github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).GetCollectionStatistics
/go/src/github.com/milvus-io/milvus/internal/proto/milvuspb/milvus.pb.go:5968 github.com/milvus-io/milvus/internal/proto/milvuspb._MilvusService_GetCollectionStatistics_Handler.func1
)>, <Time:{'RPC start': '2022-03-04 10:13:47.695988', 'RPC error': '2022-03-04 10:13:47.699916'}> (pymilvus.decorators:73)
[2022-03-04 10:13:47,700] [   ERROR] - <BaseException: (code=1, message=syncTimestamp Failed:err: number of RootCoord is incorrect, 0
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:253 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall
/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/client/client.go:327 github.com/milvus-io/milvus/internal/distributed/rootcoord/client.(*Client).AllocTimestamp
/go/src/github.com/milvus-io/milvus/internal/proxy/timestamp.go:57 github.com/milvus-io/milvus/internal/proxy.(*timestampAllocator).alloc
/go/src/github.com/milvus-io/milvus/internal/proxy/timestamp.go:77 github.com/milvus-io/milvus/internal/proxy.(*timestampAllocator).AllocOne
/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:181 github.com/milvus-io/milvus/internal/proxy.(*baseTaskQueue).Enqueue
/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:357 github.com/milvus-io/milvus/internal/proxy.(*ddTaskQueue).Enqueue
/go/src/github.com/milvus-io/milvus/internal/proxy/impl.go:737 github.com/milvus-io/milvus/internal/proxy.(*Proxy).GetCollectionStatistics
/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:468 github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).GetCollectionStatistics
/go/src/github.com/milvus-io/milvus/internal/proto/milvuspb/milvus.pb.go:5968 github.com/milvus-io/milvus/internal/proto/milvuspb._MilvusService_GetCollectionStatistics_Handler.func1
)> (milvus_benchmark.main:118)
[2022-03-04 10:13:47,704] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 87, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/locust.py", line 428, in prepare
    self.insert(self.milvus, collection_name, case_param["data_type"], dimension, case_param["collection_size"], case_param["ni_per"])
  File "/src/milvus_benchmark/runners/base.py", line 129, in insert
    ni_time = self.insert_core(milvus, info, start_id, vectors)
  File "/src/milvus_benchmark/runners/base.py", line 89, in insert_core
    logger.debug(milvus.count())
  File "/src/milvus_benchmark/client.py", line 420, in count
    row_count = self._milvus.get_collection_stats(collection_name)["row_count"]
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 229, in get_collection_stats
    stats = handler.get_collection_stats(collection_name, timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 890, in get_collection_stats
    raise BaseException(status.error_code, status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=syncTimestamp Failed:err: number of RootCoord is incorrect, 0
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:253 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall
/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/client/client.go:327 github.com/milvus-io/milvus/internal/distributed/rootcoord/client.(*Client).AllocTimestamp
/go/src/github.com/milvus-io/milvus/internal/proxy/timestamp.go:57 github.com/milvus-io/milvus/internal/proxy.(*timestampAllocator).alloc
/go/src/github.com/milvus-io/milvus/internal/proxy/timestamp.go:77 github.com/milvus-io/milvus/internal/proxy.(*timestampAllocator).AllocOne
/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:181 github.com/milvus-io/milvus/internal/proxy.(*baseTaskQueue).Enqueue
/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:357 github.com/milvus-io/milvus/internal/proxy.(*ddTaskQueue).Enqueue
/go/src/github.com/milvus-io/milvus/internal/proxy/impl.go:737 github.com/milvus-io/milvus/internal/proxy.(*Proxy).GetCollectionStatistics
/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:468 github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).GetCollectionStatistics
/go/src/github.com/milvus-io/milvus/internal/proto/milvuspb/milvus.pb.go:5968 github.com/milvus-io/milvus/internal/proto/milvuspb._MilvusService_GetCollectionStatistics_Handler.func1
)>
 (milvus_benchmark.main:119)
```

### Expected Behavior

Argo : benchmark-wql8c
server-configmap
server-cluster-8c64m-datanode2-indexnode4-querynode6
client-configmap
client-random-locust-search-84h-1b

server:
```
AME                                                     READY   STATUS      RESTARTS   AGE     IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-wql8c-1-etcd-0                                 1/1     Running     0          3m43s   10.97.18.115   qa-node017.zilliz.local   <none>           <none>
benchmark-wql8c-1-etcd-1                                 1/1     Running     0          3m42s   10.97.3.149    qa-node001.zilliz.local   <none>           <none>
benchmark-wql8c-1-etcd-2                                 1/1     Running     0          3m42s   10.97.7.157    qa-node005.zilliz.local   <none>           <none>
benchmark-wql8c-1-milvus-datacoord-7f765f998d-85bd9      1/1     Running     0          3m42s   10.97.7.156    qa-node005.zilliz.local   <none>           <none>
benchmark-wql8c-1-milvus-datanode-75fb8bcdb5-hsr4r       1/1     Running     0          3m42s   10.97.14.126   qa-node011.zilliz.local   <none>           <none>
benchmark-wql8c-1-milvus-datanode-75fb8bcdb5-trdfv       1/1     Running     0          3m42s   10.97.10.151   qa-node008.zilliz.local   <none>           <none>
benchmark-wql8c-1-milvus-indexcoord-fb756f99c-xhl99      1/1     Running     0          3m43s   10.97.3.146    qa-node001.zilliz.local   <none>           <none>
benchmark-wql8c-1-milvus-indexnode-cb94ff4b8-46ng8       1/1     Running     0          3m42s   10.97.4.12     qa-node002.zilliz.local   <none>           <none>
benchmark-wql8c-1-milvus-indexnode-cb94ff4b8-fsdld       1/1     Running     0          3m42s   10.97.16.240   qa-node013.zilliz.local   <none>           <none>
benchmark-wql8c-1-milvus-indexnode-cb94ff4b8-kxb7d       1/1     Running     0          3m42s   10.97.17.202   qa-node014.zilliz.local   <none>           <none>
benchmark-wql8c-1-milvus-indexnode-cb94ff4b8-s7g6w       1/1     Running     0          3m42s   10.97.11.51    qa-node009.zilliz.local   <none>           <none>
benchmark-wql8c-1-milvus-proxy-648f75dd9c-lcf8d          1/1     Running     0          3m42s   10.97.7.155    qa-node005.zilliz.local   <none>           <none>
benchmark-wql8c-1-milvus-querycoord-847f554f58-llgnl     1/1     Running     0          3m42s   10.97.18.113   qa-node017.zilliz.local   <none>           <none>
benchmark-wql8c-1-milvus-querynode-d8c59d57d-42pwf       1/1     Running     0          3m42s   10.97.12.33    qa-node015.zilliz.local   <none>           <none>
benchmark-wql8c-1-milvus-querynode-d8c59d57d-jqkcj       1/1     Running     0          3m43s   10.97.20.213   qa-node018.zilliz.local   <none>           <none>
benchmark-wql8c-1-milvus-querynode-d8c59d57d-jqrqz       1/1     Running     0          3m42s   10.97.16.238   qa-node013.zilliz.local   <none>           <none>
benchmark-wql8c-1-milvus-querynode-d8c59d57d-kfjnh       1/1     Running     0          3m43s   10.97.17.203   qa-node014.zilliz.local   <none>           <none>
benchmark-wql8c-1-milvus-querynode-d8c59d57d-qzm7h       1/1     Running     0          3m42s   10.97.19.50    qa-node016.zilliz.local   <none>           <none>
benchmark-wql8c-1-milvus-querynode-d8c59d57d-v6bwc       1/1     Running     0          3m43s   10.97.16.239   qa-node013.zilliz.local   <none>           <none>
benchmark-wql8c-1-milvus-rootcoord-6dfb8d6cc6-9nwf2      1/1     Running     0          3m42s   10.97.14.127   qa-node011.zilliz.local   <none>           <none>
benchmark-wql8c-1-minio-0                                1/1     Running     0          3m42s   10.97.12.37    qa-node015.zilliz.local   <none>           <none>
benchmark-wql8c-1-minio-1                                1/1     Running     0          3m42s   10.97.19.52    qa-node016.zilliz.local   <none>           <none>
benchmark-wql8c-1-minio-2                                1/1     Running     0          3m42s   10.97.12.36    qa-node015.zilliz.local   <none>           <none>
benchmark-wql8c-1-minio-3                                1/1     Running     0          3m42s   10.97.12.35    qa-node015.zilliz.local   <none>           <none>
benchmark-wql8c-1-pulsar-autorecovery-54f486c496-vz9lf   1/1     Running     0          3m43s   10.97.16.237   qa-node013.zilliz.local   <none>           <none>
benchmark-wql8c-1-pulsar-bastion-57d5ddb49d-s7v5h        1/1     Running     0          3m43s   10.97.19.49    qa-node016.zilliz.local   <none>           <none>
benchmark-wql8c-1-pulsar-bookkeeper-0                    1/1     Running     0          3m42s   10.97.7.158    qa-node005.zilliz.local   <none>           <none>
benchmark-wql8c-1-pulsar-bookkeeper-1                    1/1     Running     0          112s    10.97.18.118   qa-node017.zilliz.local   <none>           <none>
benchmark-wql8c-1-pulsar-bookkeeper-2                    1/1     Running     0          86s     10.97.6.204    qa-node004.zilliz.local   <none>           <none>
benchmark-wql8c-1-pulsar-broker-848879f45d-kkwtn         1/1     Running     0          3m43s   10.97.17.201   qa-node014.zilliz.local   <none>           <none>
benchmark-wql8c-1-pulsar-proxy-6d9b8c9fb8-ntdkc          2/2     Running     0          3m42s   10.97.3.147    qa-node001.zilliz.local   <none>           <none>
benchmark-wql8c-1-pulsar-zookeeper-0                     1/1     Running     0          3m42s   10.97.18.114   qa-node017.zilliz.local   <none>           <none>
benchmark-wql8c-1-pulsar-zookeeper-1                     1/1     Running     0          3m22s   10.97.18.116   qa-node017.zilliz.local   <none>           <none>
benchmark-wql8c-1-pulsar-zookeeper-2                     1/1     Running     0          3m2s    10.97.18.117   qa-node017.zilliz.local   <none>           <none>
benchmark-wql8c-1-pulsar-zookeeper-metadata-sk5tt        0/1     Completed   0          3m43s   10.97.14.125   qa-node011.zilliz.local   <none>           <none>
```

### Steps To Reproduce

```markdown
、create collation
2、build index of ivf_sq8
3、insert 1b vectors -> raise error
4、flush collection
5、build index with the same params 
6、load collection
7、locust concurrent: query<-search, load, get<-query
```

### Anything else?

client-random-locust-search-84h-1b
```
{
	"config.yaml": "locust_random_performance:
		  collections:
		    -
		      milvus:
		        cache_config.insert_buffer_size: 2GB
		        engine_config.use_blas_threshold: 1100
		        wal_enable: true
		      collection_name: sift_1b_128_l2
		      ni_per: 50000
		      build_index: true
		      index_type: ivf_sq8
		      index_param:
		        nlist: 1024
		      task:
		        types:
		          -
		            type: query
		            weight: 20
		            params:
		              top_k: 10
		              nq: 10
		              search_param:
		                nprobe: 16
		          -
		            type: load
		            weight: 1
		          -
		            type: get
		            weight: 2
		            params:
		              ids_length: 10
		        connection_num: 1
		        clients_num: 20
		        spawn_rate: 2
		        during_time: 302400
		"
}
```

**Comment by jingkl** [comment]
The milvus client should not type out a bunch of useless messages that can confuse the user, for example
```
/go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:253 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall
```


The milvus server should not throw an error message directly, there should be a protection mechanism

**Comment by LoveEachDay** [comment]
`benchmark-wql8c` cluster deploys with a etcd cluster which does not use fast disk. The `rootcoord` failed to renew the lease because the etcd cluster leadership change.
