### ISSUE TITLE
[Bug]:  runtime error: integer divide by zero

### ISSUE THREAD

**Issue by AlviseSembenico** [milvus-io/milvus#15909]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.1
- Deployment mode(standalone or cluster): GCP K8S cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0
Same deployment followed in the docs
- 4 vCPU
- 16 Gb RAM
```

### Current Behavior

The datanode fails and the following errors pops up at every restart of the pods.
```
panic: runtime error: integer divide by zero

goroutine 279953 [running]:
github.com/milvus-io/milvus/internal/datanode.interface2FieldData(0x65, 0xc009098aa0, 0x0, 0x556, 0x0, 0x34b77d0, 0xc00205be40, 0x0, 0x0)
	/go/src/github.com/milvus-io/milvus/internal/datanode/compactor.go:663 +0x152f
github.com/milvus-io/milvus/internal/datanode.(*compactionTask).merge(0xc00642cd20, 0x34b78f0, 0xc00838bd60, 0xc0041b8de0, 0xc00014c480, 0x5fd8e170c380000, 0x0, 0x8, 0x0, 0x0, ...)
	/go/src/github.com/milvus-io/milvus/internal/datanode/compactor.go:283 +0xca5
github.com/milvus-io/milvus/internal/datanode.(*compactionTask).compact(0xc00642cd20, 0x0, 0x0)
	/go/src/github.com/milvus-io/milvus/internal/datanode/compactor.go:462 +0x1692
github.com/milvus-io/milvus/internal/datanode.(*compactionExecutor).executeTask(0xc0004e5020, 0x34ce878, 0xc00642cd20)
	/go/src/github.com/milvus-io/milvus/internal/datanode/compaction_executor.go:98 +0x187
created by github.com/milvus-io/milvus/internal/datanode.(*compactionExecutor).executeWithState
	/go/src/github.com/milvus-io/milvus/internal/datanode/compaction_executor.go:75 +0x75
```

**Comment by xiaofan-luan** [comment]
@letian-jiang please take a deep look into it~ thanks
