### ISSUE TITLE
load memory fail

### ISSUE THREAD

**Issue by lucky-zhao** [milvus-io/milvus#15952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- milvusdb/milvus-dev:2.0.2-latest
- milvus-sdk-java 2.0.4
- centos7
- CPU/Memory: 4 8
- GPU: 
- Others:
```

### Current Behavior

I started the service with docker compose. When I call it through the Java SDK, it often appears: 
io milvus. client. AbstractMilvusGrpcClient SearchRequest failed:
collection videt_ collection was not loaded into memory。

Even if I click and load through the page, it will fail. You can only restart the service, and then this problem occurs when you use it。

<img width="1651" alt="image" src="https://user-images.githubusercontent.com/45654758/157383478-14f3bfb6-9ccf-4027-90c0-fdb30f2c4217.png">
<img width="1807" alt="image" src="https://user-images.githubusercontent.com/45654758/157383554-c0c578de-87dc-405d-843f-2bb3d0f5bb3a.png">
This problem is so serious that Milvus cannot be used at all. Please tell me how to solve it

**Comment by yanliang567** [comment]
@lucky-zhao could you please help to upload the milvus logs for investigation? If you are running in cluster mode, please upload the querycoord and querynode logs

/assign @lucky-zhao 
/unassign

**Comment by lucky-zhao** [comment]
standalone

**Comment by lucky-zhao** [comment]
<img width="1751" alt="image" src="https://user-images.githubusercontent.com/45654758/157391023-e7f45dfb-4a4c-4ab4-b840-c75bdc36046e.png">

**Comment by lucky-zhao** [comment]
<img width="1750" alt="image" src="https://user-images.githubusercontent.com/45654758/157394483-b47d598f-cbc0-4104-99d0-fd1c96879bd2.png">

**Comment by lucky-zhao** [comment]
[milvus-load-fail.log](https://github.com/milvus-io/milvus/files/8212648/milvus-load-fail.log)

**Comment by xiaofan-luan** [comment]
Hi @lucky-zhao ,did you check if you have enough memory to load the collection?

**Comment by lucky-zhao** [comment]
> 嗨@ lucky-zhao，你检查了是否有足够的内存来加载集合？

yes,I thought of this for the first time, but we have enough memory.

**Comment by kingzcheung** [comment]
I also encountered the same problem when I try to release the collection and then load the collection again.

![image](https://user-images.githubusercontent.com/12839855/157409759-fa7f2d10-4688-475f-a20a-013fbd74ba40.png)

**Comment by kingzcheung** [comment]
Error in v2.0.1:

```shell
[2022/03/09 09:19:41.399 +00:00] [INFO] [segment_loader.go:479] ["there are no delta logs saved with segment"] [segmentID=431702838049767426]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1ae25ae]

goroutine 450 [running]:
github.com/milvus-io/milvus/internal/querynode.(*segmentLoader).loadSegment(0xc000878c60, 0xc001f59a98, 0xc000000002, 0x2, 0x2)
	/go/src/github.com/milvus-io/milvus/internal/querynode/segment_loader.go:151 +0x15ae
github.com/milvus-io/milvus/internal/querynode.(*watchDmChannelsTask).Execute(0xc001118240, 0x34c06d0, 0xc0005c42c0, 0x0, 0x0)
	/go/src/github.com/milvus-io/milvus/internal/querynode/task.go:290 +0xf3f
github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).processTask(0xc0005c4300, 0x34d35d8, 0xc001118240, 0x34d1750, 0xc0000fe7d0)
	/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:61 +0x173
github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).taskLoop(0xc0005c4300)
	/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:78 +0x15a
created by github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).Start
	/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:86 +0x5c
```
![image](https://user-images.githubusercontent.com/12839855/157411606-c44f0385-1316-4c5d-b1dd-869b5c953961.png)

**Comment by piggy2303** [comment]
same here :)

**Comment by drow931** [comment]
like this, load memory fail with no index.  next is error log

`
[2022/03/10 03:45:59.098 +00:00] [ERROR] [segment_loader.go:155] ["load segment failed, set segment to meta failed"] [collectionID=431719860908064769] [partitionID=431719860908064770] [segmentID=431719860934279171] ["loadSegmentRequest msgID"=431720186412138448] [error="partition 431719860908064770 hasn't been loaded or has been released"] [stack="github.com/milvus-io/milvus/internal/querynode.(*segmentLoader).loadSegment\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/segment_loader.go:155\ngithub.com/milvus-io/milvus/internal/querynode.(*watchDmChannelsTask).Execute\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/task.go:297\ngithub.com/milvus-io/milvus/internal/querynode.(*taskScheduler).processTask\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:61\ngithub.com/milvus-io/milvus/internal/querynode.(*taskScheduler).taskLoop\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:78"]
[2022/03/10 03:45:59.117 +00:00] [WARN] [task_scheduler.go:63] ["partition 431719860908064770 hasn't been loaded or has been released"]
[2022/03/10 03:45:59.118 +00:00] [ERROR] [impl.go:238] ["partition 431719860908064770 hasn't been loaded or has been released"] [stack="github.com/milvus-io/milvus/internal/querynode.(*QueryNode).WatchDmChannels.func1\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/impl.go:238\ngithub.com/milvus-io/milvus/internal/querynode.(*QueryNode).WatchDmChannels\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/impl.go:247\ngithub.com/milvus-io/milvus/internal/distributed/querynode.(*Server).WatchDmChannels\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/service.go:269\ngithub.com/milvus-io/milvus/internal/proto/querypb._QueryNode_WatchDmChannels_Handler.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proto/querypb/query_coord.pb.go:3420\ngithub.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38\ngithub.com/milvus-io/milvus/internal/proto/querypb._QueryNode_WatchDmChannels_Handler\n\t/go/src/github.com/milvus-io/milvus/internal/proto/querypb/query_coord.pb.go:3422\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1286\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1609\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:934"]
`

**Comment by drow931** [comment]
@yanliang567 @yhmo

**Comment by drow931** [comment]
Reproduce the problem， when create indexes immediately after inserting data will cause a load failure

**Comment by xiaofan-luan** [comment]
We will fix it ASAP~

**Comment by xiaofan-luan** [comment]
mark it as urgent, please help on investigating @bigsheeper

**Comment by yanliang567** [comment]
@binbinlv please pay attention to this issue, i think we should have covered this scenario.

**Comment by binbinlv** [comment]
OK, we covered the scenario that creating indexes immediately after inserting data, will investigate the difference between the issue and our test scenario.

**Comment by binbinlv** [comment]
Reproduced the issue, and the exact scenario will raise this load error is:
1 create a collection with 2 partitions [ note: more than 1 partition is a must condition]
2 insert 100000 entities to each partition [ note: insert should more than 16M for each shard, small quantity will not report this error]
3 load

and the reproduced script is:
```python
from pymilvus import CollectionSchema, FieldSchema
from pymilvus import Collection
from pymilvus import connections
from pymilvus import DataType
from pymilvus import Partition
from pymilvus import utility


dim = 128
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
schema = CollectionSchema(fields=[int64_field, float_field, float_vector])
connections.connect()


import numpy as np
collection = Collection("test_search_collection_binbin_0", schema=schema)
collection.create_partition(partition_name="search_partition_1", description="search partition")
par = collection.partitions
dim = 128
nb = 100000
import random
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors],  par[0].name)
res1=collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors],  par[1].name)
collection.load()
```

And the detail scenario comparisons are:
(1) insert small quantity (3000) entities to a collection with one partition + load : PASS
(2) insert 200000 entities to a collection with one partition + load : PASS
(3) insert small quantity (3000) to a collection with two partitions + load: PASS
(4) insert 50000 entities  to a collection with two partitions + load: PASS
**(5) insert 100000 to a collection with two partitions + load: FAIL**

**Comment by piggy2303** [comment]
I change to the older version 
image: milvusdb/milvus:v2.0.0
and for loop to load it with 2000 entities
not facing with this error 
@binbin12580 

you should use docker-compose to deploying
😄 good luck

**Comment by xiaofan-luan** [comment]
> I change to the older version image: milvusdb/milvus:v2.0.0 and for loop to load it with 2000 entities not facing with this error @binbin12580
> 
> you should use docker-compose to deploying 😄 good luck

Hi @piggy2303, we've fixed the issue in our daily build and soon on 2.0.2 release~ thanks for the patience

**Comment by xiaofan-luan** [comment]
should be fixed 16038

**Comment by pwichmann** [comment]
Ni hao, @xiaofan-luan,

Is v2.0.2 available already?
I ran into the same issue with Milvus v2.0.1:

```
[2022/03/17 12:03:00.112 +00:00] [ERROR] [global_meta_broker.go:229] ["empty index paths, segmentID = 431878090856857601, fieldID = 101, buildID = 431878133862629378"] [stack="github.com/milvus-io/milvus/internal/querycoord.(*globalMetaBroker).parseIndexInfo\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/global_meta_broker.go:229\ngithub.com/milvus-io/milvus/internal/querycoord.(*globalMetaBroker).getIndexInfo\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/global_meta_broker.go:312\ngithub.com/milvus-io/milvus/internal/querycoord.(*IndexChecker).checkIndexLoop\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/index_checker.go:183"]
[2022/03/17 12:03:00.113 +00:00] [DEBUG] [segment_loader.go:227] ["loading delta..."]
[2022/03/17 12:03:00.113 +00:00] [INFO] [segment_loader.go:479] ["there are no delta logs saved with segment"] [segmentID=431877516097486849]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1ae25ae]

goroutine 325 [running]:
github.com/milvus-io/milvus/internal/querynode.(*segmentLoader).loadSegment(0xc00053d080, 0xc0012eda98, 0xc000000002, 0x2, 0x2)
	/go/src/github.com/milvus-io/milvus/internal/querynode/segment_loader.go:151 +0x15ae
github.com/milvus-io/milvus/internal/querynode.(*watchDmChannelsTask).Execute(0xc0007c63f0, 0x34c06d0, 0xc0000e3fc0, 0x0, 0x0)
	/go/src/github.com/milvus-io/milvus/internal/querynode/task.go:290 +0xf3f
github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).processTask(0xc0002a6000, 0x34d35d8, 0xc0007c63f0, 0x34d1750, 0xc0003a0370)
	/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:61 +0x173
github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).taskLoop(0xc0002a6000)
	/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:78 +0x15a
created by github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).Start
	/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:86 +0x5c

```
