### ISSUE TITLE
[Bug]: Search raise error after upgrading from master-20220125-6336e232 to master-20220309-5fdef607

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#15965]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:  master-20220125-6336e232 to master-20220309-5fdef607
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc10.dev2
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

search raise error
```
Search...
Traceback (most recent call last):
  File "scripts/action_after_upgrade.py", line 44, in <module>
    task_1(data_size, host)
  File "scripts/action_after_upgrade.py", line 14, in task_1
    load_and_search(prefix)
  File "/home/runner/work/milvus/milvus/tests/python_client/deploy/scripts/utils.py", line [147](https://github.com/milvus-io/milvus/runs/5486590451?check_suite_focus=true#step:8:147), in load_and_search
    res = c.search(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 698, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/stub.py", line 50, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/stub.py", line 42, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/stub.py", line 1055, in search
    return handler.search(collection_name, data, anns_field, param, limit, expression,
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 87, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 69, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 106, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 646, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 87, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 69, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 607, in _execute_search_requests
    raise pre_err
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 595, in _execute_search_requests
    response = ft.result()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@[164](https://github.com/milvus-io/milvus/runs/5486590451?check_suite_focus=true#step:8:164)6859246.474350674","description":"Error received from peer ipv4:127.0.0.1:19530","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
```

### Expected Behavior

search works well

### Steps To Reproduce

```markdown
1. deploy old version Milvus
2. cd `tests/python_client/deploy/scripts` and run script `action_before_upgrade.py`
3. upgrade to new version Milvus
4. cd `tests/python_client/deploy/scripts` and run script `action_after_upgrade.py`

also see GitHub action https://github.com/milvus-io/milvus/runs/5486590451?check_suite_focus=true
```

### Anything else?

job link:  https://github.com/milvus-io/milvus/runs/5486590451?check_suite_focus=true
log: https://github.com/milvus-io/milvus/suites/5599298828/artifacts/181788739

**Comment by zhuwenxing** [comment]
This issue happens occasionally. On the latest try,https://github.com/milvus-io/milvus/runs/5490541863?check_suite_focus=true, it passed.
