### ISSUE TITLE
[Bug]: DataNode unittest timeout and paniked

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#15986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
2022-03-09T11:24:39.2066587Z panic: test timed out after 10m0s
2022-03-09T11:24:39.2069137Z 
2022-03-09T11:24:39.2069245Z goroutine 782 [running]:
2022-03-09T11:24:39.2069635Z testing.(*M).startAlarm.func1()
2022-03-09T11:24:39.2071974Z 	/usr/local/go/src/testing/testing.go:1700 +0x11f
2022-03-09T11:24:39.2072270Z created by time.goFunc
2022-03-09T11:24:39.2072525Z 	/usr/local/go/src/time/sleep.go:180 +0x52
2022-03-09T11:24:39.2072684Z 
2022-03-09T11:24:39.2072796Z goroutine 1 [chan receive, 9 minutes]:
2022-03-09T11:24:39.2073068Z testing.(*T).Run(0xc000102a80, 0x34ae6dc, 0x10, 0x3517830, 0x1)
2022-03-09T11:24:39.2073360Z 	/usr/local/go/src/testing/testing.go:1239 +0x610
2022-03-09T11:24:39.2073638Z testing.runTests.func1(0xc000102a80)
2022-03-09T11:24:39.2073922Z 	/usr/local/go/src/testing/testing.go:1511 +0xa7
2022-03-09T11:24:39.2074195Z testing.tRunner(0xc000102a80, 0xc00053fb88)
2022-03-09T11:24:39.2074469Z 	/usr/local/go/src/testing/testing.go:1193 +0x203
2022-03-09T11:24:39.2074792Z testing.runTests(0xc0002fc960, 0x46cce40, 0x38, 0x38, 0xc082417dc1732583, 0x8bb98397e3, 0x4795440, 0x40)
2022-03-09T11:24:39.2075311Z 	/usr/local/go/src/testing/testing.go:1509 +0x613
2022-03-09T11:24:39.2075576Z testing.(*M).Run(0xc0001cbc00, 0x0)
2022-03-09T11:24:39.2076024Z 	/usr/local/go/src/testing/testing.go:1417 +0x3b4
2022-03-09T11:24:39.2076991Z github.com/milvus-io/milvus/internal/datanode.TestMain(0xc0001cbc00)
2022-03-09T11:24:39.2077758Z 	/go/src/github.com/milvus-io/milvus/internal/datanode/data_node_test.go:58 +0x1f7
2022-03-09T11:24:39.2078374Z main.main()
2022-03-09T11:24:39.2087604Z 	_testmain.go:725 +0x392
2022-03-09T11:24:39.2088773Z 
2022-03-09T11:24:39.2093650Z goroutine 582 [chan receive, 9 minutes]:
2022-03-09T11:24:39.2099938Z testing.(*T).Run(0xc0007d8780, 0x34c16f0, 0x1c, 0xc000923870, 0x1)
2022-03-09T11:24:39.2102441Z 	/usr/local/go/src/testing/testing.go:1239 +0x610
2022-03-09T11:24:39.2106035Z github.com/milvus-io/milvus/internal/datanode.TestWatchChannel(0xc0007d8780)
2022-03-09T11:24:39.2109448Z 	/go/src/github.com/milvus-io/milvus/internal/datanode/data_node_test.go:541 +0x7fa
2022-03-09T11:24:39.2111138Z testing.tRunner(0xc0007d8780, 0x3517830)
2022-03-09T11:24:39.2115873Z 	/usr/local/go/src/testing/testing.go:1193 +0x203
2022-03-09T11:24:39.2119624Z created by testing.(*T).Run
2022-03-09T11:24:39.2123146Z 	/usr/local/go/src/testing/testing.go:1238 +0x5d8
```

https://github.com/milvus-io/milvus/runs/5478956225?check_suite_focus=true

Its `handle_watchinfo_out_of_date` in data_node_test.go:L541

**Comment by XuanYang-cn** [comment]
Stuck at pulsar-client-go Seek
```
2022-03-09T11:24:39.2588507Z goroutine 708 [chan receive, 9 minutes]:
2022-03-09T11:24:39.2588921Z github.com/apache/pulsar-client-go/pulsar.(*partitionConsumer).Seek(...)
2022-03-09T11:24:39.2589423Z 	/go/pkg/mod/github.com/milvus-io/pulsar-client-go@v0.6.5/pulsar/consumer_partition.go:379
2022-03-09T11:24:39.2590014Z github.com/apache/pulsar-client-go/pulsar.(*consumer).Seek(0xc000285d40, 0x386bf98, 0xc0006d51b8, 0x0, 0x0)
2022-03-09T11:24:39.2590549Z 	/go/pkg/mod/github.com/milvus-io/pulsar-client-go@v0.6.5/pulsar/consumer_impl.go:538 +0x565
2022-03-09T11:24:39.2591067Z github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/pulsar.(*Consumer).Chan.func1()
2022-03-09T11:24:39.2591599Z 	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/pulsar/pulsar_consumer.go:67 +0x1bf
2022-03-09T11:24:39.2591960Z sync.(*Once).doSlow(0xc000801a78, 0xc0003f0cd0)
2022-03-09T11:24:39.2592228Z 	/usr/local/go/src/sync/once.go:68 +0x10a
2022-03-09T11:24:39.2592486Z sync.(*Once).Do(0xc000801a78, 0xc0003f0cd0)
2022-03-09T11:24:39.2592744Z 	/usr/local/go/src/sync/once.go:59 +0x69
2022-03-09T11:24:39.2593219Z github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/pulsar.(*Consumer).Chan(0xc000801a40, 0xc000898b40)
2022-03-09T11:24:39.2593762Z 	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/pulsar/pulsar_consumer.go:54 +0x10b
2022-03-09T11:24:39.2594356Z github.com/milvus-io/milvus/internal/mq/msgstream.(*MqTtMsgStream).consumeToTtMsg(0xc000283e60, 0x386b518, 0xc000801a40)
2022-03-09T11:24:39.2595203Z 	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_msgstream.go:887 +0x1c8
2022-03-09T11:24:39.2595739Z created by github.com/milvus-io/milvus/internal/mq/msgstream.(*MqTtMsgStream).bufMsgPackToChannel
2022-03-09T11:24:39.2596263Z 	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_msgstream.go:800 +0x315
```

**Comment by XuanYang-cn** [comment]
```
   361 func (pc *partitionConsumer) Seek(msgID trackingMessageID) error {                                            
   362     req := &seekRequest{                                                                                      
   363         doneCh: make(chan struct{}),                                                                          
   364         msgID:  msgID,                                                                                        
   365     }                                                                                                         
   366     // it safe to change channel value here, since only one event is processed                                
   367     pc.reconnectCh = make(chan error, 1)                                                                      
   368     pc.eventsCh <- req                                                                                        
   369                                                                                                               
   370     // wait for the request to complete                                                                       
   371     <-req.doneCh                                                                                              
   372                                                                                                               
   373     // shall not wait, since req got error                                                                    
   374     if req.err != nil {                                                                                       
   375         return req.err                                                                                        
   376     }                                                                                                         
   377                                                                                                               
   378     // wait for reconnect to broker signal                                                                    
   379     err := <-pc.reconnectCh                                                                                   
   380     if err != nil {                                                                                           
   381         return err                                                                                            
   382     }                                                                                                         
   383                                                                                                               
   384     return nil                                                                                                
   385 } 
```

**Comment by XuanYang-cn** [comment]
Stuck at L379

**Comment by jennyli-z** [comment]
[Make all logs configurable for standalone/embedded Milvus. (#15926) · milvus-io/milvus@d5bae67](https://github.com/milvus-io/milvus/runs/5489978289?check_suite_focus=true)
https://github.com/milvus-io/milvus/actions/runs/1956708899
https://github.com/milvus-io/milvus/runs/5478633495?check_suite_focus=true

**Comment by XuanYang-cn** [comment]
Using rocksmq is just a work around, the underline problem is still there. So add this to backlog.
