### ISSUE TITLE
[Bug]: milvus-datanode CrashLoopBackOff

### ISSUE THREAD

**Issue by chunyuforka** [milvus-io/milvus#16103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.0.1
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS7.6
- CPU/Memory: 32/128
- GPU:  none
- Others:
```

## helm install milvus
```
# Use miniio's Gateway mode to integrate with OSS 
minio:
  enabled: true
  name: minio
  mode: standalone
  image:
    tag: "RELEASE.2020-11-06T23-17-07Z"
    pullPolicy: IfNotPresent
  accessKey: minioadmin
  secretKey: minioadmin
  existingSecret: ""
  bucketName: "oss-aiaas"
  rootPath: "milvus"

  gcsgateway:
    enabled: false
    replicas: 1
    gcsKeyJson: "/etc/credentials/gcs_key.json"
    projectId: ""

  s3gateway:
    enabled: true
    replicas: 3
    serviceEndpoint: "https://oss-cn-beijing-internal.aliyuncs.com"
    accessKey: "xxxx"
    secretKey: "xxxxxxxxx"


  nodeSelector:
    minio: 'true'
  service:
    type: ClusterIP
    port: 9000

  persistence:
    enabled: false
    existingClaim: ""
    storageClass: local-path
    accessMode: ReadWriteOnce
    size: 200Gi

# Use externalPulsar Cluster
externalPulsar:
  enabled: true
  host: pulsar-proxy.pulsar.svc.cluster.local
  port: 6650

```

### The following components are always down：
- milvus-datanode 
- milvus-querycoord  
- milvus-querynode

```
[root@Milvus-01 milvus]# kubectl get all -n milvus 
NAME                                     READY   STATUS             RESTARTS         AGE
pod/milvus-attu-7559b69d66-f788p         1/1     Running            0                134m
pod/milvus-datacoord-84479dd5f-cf9gt     1/1     Running            0                137m
pod/milvus-datanode-69bdd5c4fb-6fmnj     0/1     Running            24 (5m4s ago)    137m
pod/milvus-datanode-69bdd5c4fb-k2bs5     0/1     CrashLoopBackOff   23 (74s ago)     137m
pod/milvus-datanode-69bdd5c4fb-qnnqw     0/1     CrashLoopBackOff   23 (2m59s ago)   137m
pod/milvus-etcd-0                        1/1     Running            0                137m
pod/milvus-etcd-1                        1/1     Running            0                137m
pod/milvus-etcd-2                        1/1     Running            0                137m
pod/milvus-indexcoord-67fff4b7bc-kt8mg   1/1     Running            0                137m
pod/milvus-indexnode-56c6748799-cg8l9    1/1     Running            0                137m
pod/milvus-indexnode-56c6748799-p8lfl    1/1     Running            0                137m
pod/milvus-indexnode-56c6748799-r44jn    1/1     Running            0                137m
pod/milvus-minio-7989cd8459-ghpbk        1/1     Running            0                137m
pod/milvus-minio-7989cd8459-pg89d        1/1     Running            0                137m
pod/milvus-minio-7989cd8459-t9nd8        1/1     Running            0                137m
pod/milvus-proxy-79f5b897bd-7htmv        1/1     Running            0                137m
pod/milvus-proxy-79f5b897bd-g5rp4        1/1     Running            0                137m
pod/milvus-proxy-79f5b897bd-scg2l        1/1     Running            0                137m
pod/milvus-querycoord-9db97956b-vjznz    1/1     Running            0                137m
pod/milvus-querynode-7d44fb8fdf-h8g9b    1/1     Running            9 (97m ago)      137m
pod/milvus-querynode-7d44fb8fdf-lpdzw    1/1     Running            11 (95m ago)     137m
pod/milvus-querynode-7d44fb8fdf-tc9pf    1/1     Running            10 (94m ago)     137m
pod/milvus-rootcoord-5d598f67c4-d6hzc    1/1     Running            0                137m
```
## milvus-datanode Log
```
[root@AIaaS-Prod-CPU-Public-YF-Milvus-01 milvus]# kubectl logs -f --tail 100  pod/milvus-datanode-69bdd5c4fb-6fmnj -n milvus 
[2022/03/18 05:07:49.499 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:95] ["IBN timetick log"] [from=2022/03/18 04:54:06.374 +00:00] [to=2022/03/18 04:57:26.174 +00:00] [elapsed=3m19.8s] [start=431903013961465857] [end=431903066337837057] [vChannelName=by-dev-rootcoord-dml_3_431749408726450177v1]
[2022/03/18 05:07:49.545 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:95] ["IBN timetick log"] [from=2022/03/18 04:54:15.375 +00:00] [to=2022/03/18 04:57:35.175 +00:00] [elapsed=3m19.8s] [start=431903016321024001] [end=431903068697395201] [vChannelName=by-dev-rootcoord-dml_31_431900877456408577v1]
[2022/03/18 05:07:49.593 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:95] ["IBN timetick log"] [from=2022/03/18 04:54:06.574 +00:00] [to=2022/03/18 04:57:26.374 +00:00] [elapsed=3m19.8s] [start=431903014013894657] [end=431903066390265857] [vChannelName=by-dev-rootcoord-dml_2_431749408726450177v0]
[2022/03/18 05:07:49.608 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:95] ["IBN timetick log"] [from=2022/03/18 03:05:40.974 +00:00] [to=2022/03/18 03:09:00.775 +00:00] [elapsed=3m19.801s] [start=431901308609888257] [end=431901360986521601] [vChannelName=by-dev-rootcoord-dml_30_431900877456408577v0]
time="2022-03-18T05:07:50Z" level=error msg="[Failed to create consumer]" consumerID=12 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=ynics subscription=by-dev-dataNode-3132-431885383566360577 topic="persistent://public/default/by-dev-rootcoord-dml_8"
time="2022-03-18T05:07:50Z" level=error msg="[Failed to create consumer]" consumerID=12 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=ynics subscription=by-dev-dataNode-3132-431885383566360577 topic="persistent://public/default/by-dev-rootcoord-dml_8"
[2022/03/18 05:07:51.603 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:95] ["IBN timetick log"] [from=2022/03/18 04:57:26.374 +00:00] [to=2022/03/18 05:00:46.175 +00:00] [elapsed=3m19.801s] [start=431903066390265857] [end=431903118766899201] [vChannelName=by-dev-rootcoord-dml_3_431749408726450177v1]
[2022/03/18 05:07:51.655 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:95] ["IBN timetick log"] [from=2022/03/18 04:57:35.374 +00:00] [to=2022/03/18 05:00:55.175 +00:00] [elapsed=3m19.801s] [start=431903068749561857] [end=431903121126195201] [vChannelName=by-dev-rootcoord-dml_31_431900877456408577v1]
[2022/03/18 05:07:51.701 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:95] ["IBN timetick log"] [from=2022/03/18 04:57:26.575 +00:00] [to=2022/03/18 05:00:46.375 +00:00] [elapsed=3m19.8s] [start=431903066442956801] [end=431903118819328001] [vChannelName=by-dev-rootcoord-dml_2_431749408726450177v0]
[2022/03/18 05:07:51.716 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:95] ["IBN timetick log"] [from=2022/03/18 03:09:00.975 +00:00] [to=2022/03/18 03:12:20.775 +00:00] [elapsed=3m19.8s] [start=431901361038950401] [end=431901413415321601] [vChannelName=by-dev-rootcoord-dml_30_431900877456408577v0]
[2022/03/18 05:07:53.714 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:95] ["IBN timetick log"] [from=2022/03/18 05:00:46.375 +00:00] [to=2022/03/18 05:04:06.175 +00:00] [elapsed=3m19.8s] [start=431903118819328001] [end=431903171195699201] [vChannelName=by-dev-rootcoord-dml_3_431749408726450177v1]
[2022/03/18 05:07:53.780 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:95] ["IBN timetick log"] [from=2022/03/18 05:00:55.375 +00:00] [to=2022/03/18 05:04:15.175 +00:00] [elapsed=3m19.8s] [start=431903121178624001] [end=431903173554995201] [vChannelName=by-dev-rootcoord-dml_31_431900877456408577v1]
[2022/03/18 05:07:53.799 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:95] ["IBN timetick log"] [from=2022/03/18 05:00:46.574 +00:00] [to=2022/03/18 05:04:06.375 +00:00] [elapsed=3m19.801s] [start=431903118871494657] [end=431903171248128001] [vChannelName=by-dev-rootcoord-dml_2_431749408726450177v0]
[2022/03/18 05:07:53.811 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:95] ["IBN timetick log"] [from=2022/03/18 03:12:20.974 +00:00] [to=2022/03/18 03:15:40.775 +00:00] [elapsed=3m19.801s] [start=431901413467488257] [end=431901465844121601] [vChannelName=by-dev-rootcoord-dml_30_431900877456408577v0]
time="2022-03-18T05:07:53Z" level=error msg="[Failed to create consumer]" consumerID=13 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=fcxcx subscription=by-dev-dataNode-3132-431885383566360577 topic="persistent://public/default/by-dev-rootcoord-dml_8"
time="2022-03-18T05:07:53Z" level=error msg="[Failed to create consumer]" consumerID=13 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=fcxcx subscription=by-dev-dataNode-3132-431885383566360577 topic="persistent://public/default/by-dev-rootcoord-dml_8"
[2022/03/18 05:07:55.795 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:95] ["IBN timetick log"] [from=2022/03/18 05:04:06.375 +00:00] [to=2022/03/18 05:07:26.175 +00:00] [elapsed=3m19.8s] [start=431903171248128001] [end=431903223624499201] [vChannelName=by-dev-rootcoord-dml_3_431749408726450177v1]
[2022/03/18 05:07:55.864 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:95] ["IBN timetick log"] [from=2022/03/18 05:04:15.374 +00:00] [to=2022/03/18 05:07:35.175 +00:00] [elapsed=3m19.801s] [start=431903173607161857] [end=431903225983795201] [vChannelName=by-dev-rootcoord-dml_31_431900877456408577v1]
[2022/03/18 05:07:55.880 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:95] ["IBN timetick log"] [from=2022/03/18 05:04:06.575 +00:00] [to=2022/03/18 05:07:26.375 +00:00] [elapsed=3m19.8s] [start=431903171300556801] [end=431903223676928001] [vChannelName=by-dev-rootcoord-dml_2_431749408726450177v0]
[2022/03/18 05:07:55.899 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:95] ["IBN timetick log"] [from=2022/03/18 03:15:40.975 +00:00] [to=2022/03/18 03:19:00.775 +00:00] [elapsed=3m19.8s] [start=431901465896550401] [end=431901518272921601] [vChannelName=by-dev-rootcoord-dml_30_431900877456408577v0]
time="2022-03-18T05:07:56Z" level=error msg="[Failed to create consumer]" consumerID=14 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=hnyvh subscription=by-dev-dataNode-3132-431885383566360577 topic="persistent://public/default/by-dev-rootcoord-dml_8"
time="2022-03-18T05:07:56Z" level=error msg="[Failed to create consumer]" consumerID=14 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=hnyvh subscription=by-dev-dataNode-3132-431885383566360577 topic="persistent://public/default/by-dev-rootcoord-dml_8"
[2022/03/18 05:07:58.003 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:95] ["IBN timetick log"] [from=2022/03/18 03:19:00.975 +00:00] [to=2022/03/18 03:22:20.775 +00:00] [elapsed=3m19.8s] [start=431901518325350401] [end=431901570701721601] [vChannelName=by-dev-rootcoord-dml_30_431900877456408577v0]
time="2022-03-18T05:07:59Z" level=error msg="[Failed to create consumer]" consumerID=15 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=jmgai subscription=by-dev-dataNode-3132-431885383566360577 topic="persistent://public/default/by-dev-rootcoord-dml_8"
time="2022-03-18T05:07:59Z" level=error msg="[Failed to create consumer]" consumerID=15 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=jmgai subscription=by-dev-dataNode-3132-431885383566360577 topic="persistent://public/default/by-dev-rootcoord-dml_8"
[2022/03/18 05:08:00.094 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:95] ["IBN timetick log"] [from=2022/03/18 03:22:20.975 +00:00] [to=2022/03/18 03:25:40.775 +00:00] [elapsed=3m19.8s] [start=431901570754150401] [end=431901623130521601] [vChannelName=by-dev-rootcoord-dml_30_431900877456408577v0]
[2022/03/18 05:08:02.185 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:95] ["IBN timetick log"] [from=2022/03/18 03:25:40.975 +00:00] [to=2022/03/18 03:29:00.775 +00:00] [elapsed=3m19.8s] [start=431901623182950401] [end=431901675559321601] [vChannelName=by-dev-rootcoord-dml_30_431900877456408577v0]
time="2022-03-18T05:08:02Z" level=error msg="[Failed to create consumer]" consumerID=16 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=dpwzg subscription=by-dev-dataNode-3132-431885383566360577 topic="persistent://public/default/by-dev-rootcoord-dml_8"
time="2022-03-18T05:08:02Z" level=error msg="[Failed to create consumer]" consumerID=16 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=dpwzg subscription=by-dev-dataNode-3132-431885383566360577 topic="persistent://public/default/by-dev-rootcoord-dml_8"
[2022/03/18 05:08:04.299 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:95] ["IBN timetick log"] [from=2022/03/18 03:29:00.975 +00:00] [to=2022/03/18 03:32:20.774 +00:00] [elapsed=3m19.799s] [start=431901675611750401] [end=431901727987859457] [vChannelName=by-dev-rootcoord-dml_30_431900877456408577v0]
time="2022-03-18T05:08:05Z" level=error msg="[Failed to create consumer]" consumerID=17 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=ryjmk subscription=by-dev-dataNode-3132-431885383566360577 topic="persistent://public/default/by-dev-rootcoord-dml_8"
time="2022-03-18T05:08:05Z" level=error msg="[Failed to create consumer]" consumerID=17 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=ryjmk subscription=by-dev-dataNode-3132-431885383566360577 topic="persistent://public/default/by-dev-rootcoord-dml_8"
[2022/03/18 05:08:06.411 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:95] ["IBN timetick log"] [from=2022/03/18 03:32:20.974 +00:00] [to=2022/03/18 03:35:40.775 +00:00] [elapsed=3m19.801s] [start=431901728040288257] [end=431901780416921601] [vChannelName=by-dev-rootcoord-dml_30_431900877456408577v0]
[2022/03/18 05:08:08.517 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:95] ["IBN timetick log"] [from=2022/03/18 03:35:40.975 +00:00] [to=2022/03/18 03:39:00.775 +00:00] [elapsed=3m19.8s] [start=431901780469350401] [end=431901832845721601] [vChannelName=by-dev-rootcoord-dml_30_431900877456408577v0]
time="2022-03-18T05:08:08Z" level=error msg="[Failed to create consumer]" consumerID=18 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=nulro subscription=by-dev-dataNode-3132-431885383566360577 topic="persistent://public/default/by-dev-rootcoord-dml_8"
time="2022-03-18T05:08:08Z" level=error msg="[Failed to create consumer]" consumerID=18 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=nulro subscription=by-dev-dataNode-3132-431885383566360577 topic="persistent://public/default/by-dev-rootcoord-dml_8"
[2022/03/18 05:08:10.612 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:95] ["IBN timetick log"] [from=2022/03/18 03:39:00.975 +00:00] [to=2022/03/18 03:42:20.774 +00:00] [elapsed=3m19.799s] [start=431901832898150401] [end=431901885274259457] [vChannelName=by-dev-rootcoord-dml_30_431900877456408577v0]
time="2022-03-18T05:08:11Z" level=error msg="[Failed to create consumer]" consumerID=19 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=escnl subscription=by-dev-dataNode-3132-431885383566360577 topic="persistent://public/default/by-dev-rootcoord-dml_8"
time="2022-03-18T05:08:11Z" level=error msg="[Failed to create consumer]" consumerID=19 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=escnl subscription=by-dev-dataNode-3132-431885383566360577 topic="persistent://public/default/by-dev-rootcoord-dml_8"
[2022/03/18 05:08:12.709 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:95] ["IBN timetick log"] [from=2022/03/18 03:42:20.974 +00:00] [to=2022/03/18 03:45:40.775 +00:00] [elapsed=3m19.801s] [start=431901885326688257] [end=431901937703321601] [vChannelName=by-dev-rootcoord-dml_30_431900877456408577v0]
[2022/03/18 05:08:14.807 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:95] ["IBN timetick log"] [from=2022/03/18 03:45:40.975 +00:00] [to=2022/03/18 03:49:00.775 +00:00] [elapsed=3m19.8s] [start=431901937755750401] [end=431901990132121601] [vChannelName=by-dev-rootcoord-dml_30_431900877456408577v0]
time="2022-03-18T05:08:14Z" level=error msg="[Failed to create consumer]" consumerID=20 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=msfwt subscription=by-dev-dataNode-3132-431885383566360577 topic="persistent://public/default/by-dev-rootcoord-dml_8"
time="2022-03-18T05:08:14Z" level=error msg="[Failed to create consumer]" consumerID=20 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=msfwt subscription=by-dev-dataNode-3132-431885383566360577 topic="persistent://public/default/by-dev-rootcoord-dml_8"
[2022/03/18 05:08:16.899 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:95] ["IBN timetick log"] [from=2022/03/18 03:49:00.975 +00:00] [to=2022/03/18 03:52:20.775 +00:00] [elapsed=3m19.8s] [start=431901990184550401] [end=431902042560921601] [vChannelName=by-dev-rootcoord-dml_30_431900877456408577v0]
time="2022-03-18T05:08:17Z" level=error msg="[Failed to create consumer]" consumerID=21 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=emxei subscription=by-dev-dataNode-3132-431885383566360577 topic="persistent://public/default/by-dev-rootcoord-dml_8"
time="2022-03-18T05:08:17Z" level=error msg="[Failed to create consumer]" consumerID=21 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=emxei subscription=by-dev-dataNode-3132-431885383566360577 topic="persistent://public/default/by-dev-rootcoord-dml_8"
[2022/03/18 05:08:18.990 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:95] ["IBN timetick log"] [from=2022/03/18 03:52:20.975 +00:00] [to=2022/03/18 03:55:40.774 +00:00] [elapsed=3m19.799s] [start=431902042613350401] [end=431902094989459457] [vChannelName=by-dev-rootcoord-dml_30_431900877456408577v0]
time="2022-03-18T05:08:20Z" level=error msg="[Failed to create consumer]" consumerID=22 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=kmhle subscription=by-dev-dataNode-3132-431885383566360577 topic="persistent://public/default/by-dev-rootcoord-dml_8"
time="2022-03-18T05:08:20Z" level=error msg="[Failed to create consumer]" consumerID=22 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=kmhle subscription=by-dev-dataNode-3132-431885383566360577 topic="persistent://public/default/by-dev-rootcoord-dml_8"
[2022/03/18 05:08:21.099 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:95] ["IBN timetick log"] [from=2022/03/18 03:55:40.975 +00:00] [to=2022/03/18 03:59:00.775 +00:00] [elapsed=3m19.8s] [start=431902095042150401] [end=431902147418521601] [vChannelName=by-dev-rootcoord-dml_30_431900877456408577v0]
[2022/03/18 05:08:23.208 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:95] ["IBN timetick log"] [from=2022/03/18 03:59:00.975 +00:00] [to=2022/03/18 04:02:20.775 +00:00] [elapsed=3m19.8s] [start=431902147470950401] [end=431902199847321601] [vChannelName=by-dev-rootcoord-dml_30_431900877456408577v0]
time="2022-03-18T05:08:23Z" level=error msg="[Failed to create consumer]" consumerID=23 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=gfahe subscription=by-dev-dataNode-3132-431885383566360577 topic="persistent://public/default/by-dev-rootcoord-dml_8"
time="2022-03-18T05:08:23Z" level=error msg="[Failed to create consumer]" consumerID=23 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=gfahe subscription=by-dev-dataNode-3132-431885383566360577 topic="persistent://public/default/by-dev-rootcoord-dml_8"
[2022/03/18 05:08:25.290 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:95] ["IBN timetick log"] [from=2022/03/18 04:02:20.974 +00:00] [to=2022/03/18 04:05:40.775 +00:00] [elapsed=3m19.801s] [start=431902199899488257] [end=431902252276121601] [vChannelName=by-dev-rootcoord-dml_30_431900877456408577v0]
time="2022-03-18T05:08:26Z" level=error msg="[Failed to create consumer]" consumerID=24 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=zwogr subscription=by-dev-dataNode-3132-431885383566360577 topic="persistent://public/default/by-dev-rootcoord-dml_8"
time="2022-03-18T05:08:26Z" level=error msg="[Failed to create consumer]" consumerID=24 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=zwogr subscription=by-dev-dataNode-3132-431885383566360577 topic="persistent://public/default/by-dev-rootcoord-dml_8"
[2022/03/18 05:08:27.381 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:95] ["IBN timetick log"] [from=2022/03/18 04:05:40.974 +00:00] [to=2022/03/18 04:09:00.775 +00:00] [elapsed=3m19.801s] [start=431902252328288257] [end=431902304704921601] [vChannelName=by-dev-rootcoord-dml_30_431900877456408577v0]
[2022/03/18 05:08:29.478 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:95] ["IBN timetick log"] [from=2022/03/18 04:09:00.975 +00:00] [to=2022/03/18 04:12:20.775 +00:00] [elapsed=3m19.8s] [start=431902304757350401] [end=431902357133721601] [vChannelName=by-dev-rootcoord-dml_30_431900877456408577v0]
panic: Failed to create consumer by-dev-rootcoord-dml_8, error = All attempts results:
attempt #1:server error: PersistenceError: java.util.concurrent.CompletionException: java.lang.NullPointerException
attempt #2:server error: ConsumerBusy: Exclusive consumer is already connected
attempt #3:server error: ConsumerBusy: Exclusive consumer is already connected
attempt #4:server error: ConsumerBusy: Exclusive consumer is already connected
attempt #5:server error: ConsumerBusy: Exclusive consumer is already connected
attempt #6:server error: ConsumerBusy: Exclusive consumer is already connected
attempt #7:server error: ConsumerBusy: Exclusive consumer is already connected
attempt #8:server error: ConsumerBusy: Exclusive consumer is already connected
attempt #9:server error: ConsumerBusy: Exclusive consumer is already connected
attempt #10:server error: ConsumerBusy: Exclusive consumer is already connected
attempt #11:server error: ConsumerBusy: Exclusive consumer is already connected
attempt #12:server error: ConsumerBusy: Exclusive consumer is already connected
attempt #13:server error: ConsumerBusy: Exclusive consumer is already connected
attempt #14:server error: ConsumerBusy: Exclusive consumer is already connected
attempt #15:server error: ConsumerBusy: Exclusive consumer is already connected
attempt #16:server error: ConsumerBusy: Exclusive consumer is already connected
attempt #17:server error: ConsumerBusy: Exclusive consumer is already connected
attempt #18:server error: ConsumerBusy: Exclusive consumer is already connected
attempt #19:server error: ConsumerBusy: Exclusive consumer is already connected
attempt #20:server error: ConsumerBusy: Exclusive consumer is already connected


goroutine 285 [running]:
github.com/milvus-io/milvus/internal/msgstream.(*MqTtMsgStream).AsConsumerWithPosition(0xc000671560, 0xc0001e9e40, 0x1, 0x1, 0xc0001a4c00, 0x27, 0x1)
	/go/src/github.com/milvus-io/milvus/internal/msgstream/mq_msgstream.go:742 +0x2a7
github.com/milvus-io/milvus/internal/msgstream.(*MqTtMsgStream).AsConsumer(0xc000671560, 0xc0001e9e40, 0x1, 0x1, 0xc0001a4c00, 0x27)
	/go/src/github.com/milvus-io/milvus/internal/msgstream/mq_msgstream.go:710 +0x66
github.com/milvus-io/milvus/internal/datanode.newDmInputNode(0x34c06d0, 0xc000638940, 0xc00062a0c0, 0xc000817900, 0xc000036d80, 0x2b, 0x2)
	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_dmstream_input_node.go:46 +0x250
github.com/milvus-io/milvus/internal/datanode.(*dataSyncService).initNodes(0xc0006fe600, 0xc000540000, 0x34c06d0, 0xc000638940)
	/go/src/github.com/milvus-io/milvus/internal/datanode/data_sync_service.go:209 +0x1516
github.com/milvus-io/milvus/internal/datanode.newDataSyncService(0x34c06d0, 0xc000384440, 0xc0002bb000, 0x34dfc38, 0xc00086daa0, 0x34b45f0, 0xc0001e9ae0, 0x34c0ee8, 0xc00087e400, 0xc000540000, ...)
	/go/src/github.com/milvus-io/milvus/internal/datanode/data_sync_service.go:88 +0x228
github.com/milvus-io/milvus/internal/datanode.(*flowgraphManager).addAndStart(0xc0004db620, 0xc000738a00, 0xc000540000, 0x28, 0x1)
	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_manager.go:57 +0x9ea
github.com/milvus-io/milvus/internal/datanode.(*DataNode).handlePutEvent(0xc000738a00, 0xc00090b180, 0x1897596, 0x324be23)
	/go/src/github.com/milvus-io/milvus/internal/datanode/data_node.go:373 +0x92
github.com/milvus-io/milvus/internal/datanode.(*channelEventManager).Run.func1(0xc00061c5a0)
	/go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:56 +0x153
created by github.com/milvus-io/milvus/internal/datanode.(*channelEventManager).Run
	/go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:49 +0x3f
```

**Comment by yanliang567** [comment]
i guess it was caused by no access to minio, while maybe we need a more specific error message for this case. @LoveEachDay  could you please help to double check the root cause?
/assign @LoveEachDay 
/unassign

**Comment by LoveEachDay** [comment]
The error message: `server error: ConsumerBusy: Exclusive consumer is already connected" name=msfwt subscription=by-dev-dataNode-3132-431885383566360577 topic="persistent://public/default/by-dev-rootcoord-dml_8` is clear. 
This is not minio related. It's about pulsar subscription. It seems we have an exclusive subscription but want multiple consumers under the same subscription.
/unassign

**Comment by yanliang567** [comment]
@sunby please help on this issue.
/assign @sunby
