### ISSUE TITLE
Lab Test 2: 100-Million-Scale Vector Similarity Search ,after the load the command,querynode crash[Bug]: 

### ISSUE THREAD

**Issue by yangyongjx** [milvus-io/milvus#16119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:milvus-dev:master-20220316-d65cf530
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.0.0
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory:  Intel(R) Xeon(R) Platinum 8374C CPU @ 2.70GHz(16 core)/128G
- GPU: no
- Others:
```

### Current Behavior

after exec the command python3 main.py --collection ann_100m_sq8 --load,the querynode crash

### Expected Behavior

load the data success
[logs202203211215.tar.gz](https://github.com/milvus-io/milvus/files/8313071/logs202203211215.tar.gz)

### Steps To Reproduce

```markdown
1: python3 main.py --collection ann_100m_sq8 --create
2:python3 main.py --collection=ann_100m_sq8 --insert
3:python3 main.py --collection ann_100m_sq8 --index_type IVF_SQ8 --create_index
4:python3 main.py --collection ann_100m_sq8 --load
```

**Comment by yanliang567** [comment]
@congqixia could you please help on this issue?
/assign @congqixia 
/unassign

**Comment by congqixia** [comment]
in querynode log, the "unexpected signal" is found:
```
{"log":"fatal error: unexpected signal during runtime execution\n","stream":"stderr","time":"2022-03-21T02:31:53.938962678Z"}
{"log":"fatal error: unexpected signal during runtime execution\n","stream":"stderr","time":"2022-03-21T02:31:53.939005195Z"}
{"log":"fatal error: unexpected signal during runtime execution\n","stream":"stderr","time":"2022-03-21T02:31:53.939044079Z"}
{"log":"[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x7f9ef0641583]\n","stream":"stderr","time":"2022-03-21T02:31:53.941455385Z"}
{"log":"\n","stream":"stderr","time":"2022-03-21T02:31:53.94153869Z"}
{"log":"runtime stack:\n","stream":"stderr","time":"2022-03-21T02:31:53.941546454Z"}
{"log":"runtime.throw(0x33d4ab4, 0x2a)\n","stream":"stderr","time":"2022-03-21T02:31:53.941828489Z"}
{"log":"\u0009/usr/local/go/src/runtime/panic.go:1117 +0x72\n","stream":"stderr","time":"2022-03-21T02:31:53.942120756Z"}
{"log":"runtime.sigpanic()\n","stream":"stderr","time":"2022-03-21T02:31:53.942254702Z"}
{"log":"\u0009/usr/local/go/src/runtime/signal_unix.go:718 +0x2e5\n","stream":"stderr","time":"2022-03-21T02:31:53.942502056Z"}
{"log":"\n","stream":"stderr","time":"2022-03-21T02:31:53.942558555Z"}
{"log":"goroutine 3622430 [syscall]:\n","stream":"stderr","time":"2022-03-21T02:31:53.942748022Z"}
{"log":"runtime.cgocall(0x1c6bd9f, 0xc00482cc88, 0xc002f2e008)\n","stream":"stderr","time":"2022-03-21T02:31:53.943035472Z"}
{"log":"\u0009/usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc00482cc58 sp=0xc00482cc20 pc=0x7c9b3b\n","stream":"stderr","time":"2022-03-21T02:31:53.943504483Z"}
{"log":"github.com/milvus-io/milvus/internal/querynode._Cfunc_Search(0x7f9e340058e0, 0x7f9cf8ee57b0, 0x7f97585492f0, 0x5fea94443cc0007, 0xc002f2e008, 0x5fe9472da1c0005, 0xd1a500000000, 0x0)\n","stream":"stderr","time":"2022-03-21T02:31:53.944139056Z"}
{"log":"\u0009_cgo_gotypes.go:727 +0x51 fp=0xc00482cc88 sp=0xc00482cc58 pc=0x1c3ab71\n","stream":"stderr","time":"2022-03-21T02:31:53.944607503Z"}
{"log":"github.com/milvus-io/milvus/internal/querynode.(*Segment).search.func1(0xc000511c70, 0xc002ebf4a0, 0x7f97585492f0, 0x5fea94443cc0007, 0xc002f2e008, 0xc002f2e000, 0x0)\n","stream":"stderr","time":"2022-03-21T02:31:53.945180589Z"}
{"log":"\u0009/go/src/github.com/milvus-io/milvus/internal/querynode/segment.go:315 +0x125 fp=0xc00482ccf0 sp=0xc00482cc88 pc=0x1c55805\n","stream":"stderr","time":"2022-03-21T02:31:53.945657403Z"}
{"log":"github.com/milvus-io/milvus/internal/querynode.(*Segment).search(0xc000511c70, 0xc002ebf4a0, 0xc002ebf4b8, 0x1, 0x1, 0xc00482ced0, 0x1, 0x1, 0x0, 0x0, ...)\n","stream":"stderr","time":"2022-03-21T02:31:53.946494537Z"}
{"log":"\u0009/go/src/github.com/milvus-io/milvus/internal/querynode/segment.go:315 +0x3b7 fp=0xc00482ce50 sp=0xc00482ccf0 pc=0x1c4baf7\n","stream":"stderr","time":"2022-03-21T02:31:53.946943627Z"}
{"log":"github.com/milvus-io/milvus/internal/querynode.(*historical).searchSegments.func1(0xc0039d20c0, 0xc002ebf4a0, 0xc002ebf4b8, 0x1, 0x1, 0x5fea94443cc0007, 0xc0039d20b0, 0xc0039c8fc0, 0xc0039ce198, 0xc0039ce1b0, ...)\n","stream":"stderr","time":"2022-03-21T02:31:53.947761347Z"}
{"log":"\u0009/go/src/github.com/milvus-io/milvus/internal/querynode/historical.go:189 +0x12c fp=0xc00482cf88 sp=0xc00482ce50 pc=0x1c4f34c\n","stream":"stderr","time":"2022-03-21T02:31:53.948224167Z"}
{"log":"runtime.goexit()\n","stream":"stderr","time":"2022-03-21T02:31:53.948336496Z"}
{"log":"\u0009/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc00482cf90 sp=0xc00482cf88 pc=0x839201\n","stream":"stderr","time":"2022-03-21T02:31:53.948809564Z"}
{"log":"created by github.com/milvus-io/milvus/internal/querynode.(*historical).searchSegments\n","stream":"stderr","time":"2022-03-21T02:31:53.948921851Z"}
{"log":"\u0009/go/src/github.com/milvus-io/milvus/internal/querynode/historical.go:181 +0x330\n","stream":"stderr","time":"2022-03-21T02:31:53.949209733Z"}
{"log":"\n","stream":"stderr","time":"2022-03-21T02:31:53.949261259Z"}
{"log":"goroutine 1 [chan receive, 3841 minutes]:\n","stream":"stderr","time":"2022-03-21T02:31:53.949547069Z"}
{"log":"github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run(0xc000795ea0, 0xc000010000, 0x0, 0x0)\n","stream":"stderr","time":"2022-03-21T02:31:53.949912006Z"}
{"log":"\u0009/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:496 +0x438\n","stream":"stderr","time":"2022-03-21T02:31:53.950177283Z"}
{"log":"github.com/milvus-io/milvus/cmd/milvus.RunMilvus(0xc00003c090, 0x3, 0x3)\n","stream":"stderr","time":"2022-03-21T02:31:53.95051464Z"}
{"log":"\u0009/go/src/github.com/milvus-io/milvus/cmd/milvus/milvus.go:316 +0x972\n","stream":"stderr","time":"2022-03-21T02:31:53.950728164Z"}
{"log":"main.main()\n","stream":"stderr","time":"2022-03-21T02:31:53.950825833Z"}
{"log":"\u0009/go/src/github.com/milvus-io/milvus/cmd/main.go:26 +0x45\n","stream":"stderr","time":"2022-03-21T02:31:53.95104214Z"}
{"log":"\n","stream":"stderr","time":"2022-03-21T02:31:53.951075074Z"}
{"log":"goroutine 17 [syscall, locked to thread]:\n","stream":"stderr","time":"2022-03-21T02:31:53.951258703Z"}
{"log":"runtime.goexit()\n","stream":"stderr","time":"2022-03-21T02:31:53.951347044Z"}
{"log":"\u0009/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1\n","stream":"stderr","time":"2022-03-21T02:31:53.95157288Z"}
{"log":"\n","stream":"stderr","time":"2022-03-21T02:31:53.951603598Z"}
{"log":"goroutine 80960 [select, 7 minutes]:\n","stream":"stderr","time":"2022-03-21T02:31:53.9518385Z"}
{"log":"fatal error: unexpected signal during runtime execution\n","stream":"stderr","time":"2022-03-21T02:31:53.965047447Z"}
{"log":"fatal error: unexpected signal during runtime execution\n","stream":"stderr","time":"2022-03-21T02:31:53.986787942Z"}
```
Might be the same as #15896  @soothing-rain @cydrain

**Comment by cydrain** [comment]
Hi @yangyongjx , can you attach your script here ?

**Comment by yangyongjx** [comment]
use this https://github.com/milvus-io/bootcamp/blob/master/benchmark_test/scripts/main.py script
