### ISSUE TITLE
[Bug]: Create index raise error after all standalone pod recovered from pod kill

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#16145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220322-1c4b949a
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.0.2.dev5
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
RPC error: [create_index], <BaseException: (code=1, message=CreateIndex failed: getSegmentInfo from data service failed, error = failed to get segment 432006794067836930)>, <Time:{'RPC start': '2022-03-22 18:52:18.631912', 'RPC error': '2022-03-22 18:52:18.697852'}>
Traceback (most recent call last):
  File "chaos/scripts/verify_all_collections.py", line 116, in <module>
    hello_milvus(collection_name)
  File "chaos/scripts/verify_all_collections.py", line 67, in hello_milvus
    collection.create_index(field_name="float_vector", index_params=default_index)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 1032, in create_index
    return conn.create_index(self._name, field_name, index_params,
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 592, in create_index
    raise BaseException(status.error_code, status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=CreateIndex failed: getSegmentInfo from data service failed, error = failed to get segment 432006794067836930)>
```

### Expected Behavior

all test cases passed

### Steps To Reproduce

```markdown
see https://github.com/milvus-io/milvus/runs/5649221140?check_suite_focus=true
```

### Anything else?

failed job: https://github.com/milvus-io/milvus/runs/5649221140?check_suite_focus=true
log: [logs-allstandalone](https://github.com/milvus-io/milvus/suites/5758309064/artifacts/191399581)

**Comment by yanliang567** [comment]
@xiaocai2333 could you please help on this issue? it looks like a regression issue this week.

/assign @xiaocai2333 
/unassign

**Comment by xiaocai2333** [comment]
All right! I will check it.

**Comment by zhuwenxing** [comment]
Not reproduced yet, so remove the urgent label.
