### ISSUE TITLE
[Bug]: Search raise error after docker-compose restart milvus 

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#16147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220322-1c4b949a
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-2.0.0rc10.dev2
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
Search...
Traceback (most recent call last):
  File "scripts/action_after_reinstall.py", line 43, in <module>
    task_1(data_size, host)
  File "scripts/action_after_reinstall.py", line 14, in task_1
    load_and_search(prefix)
  File "/home/runner/work/milvus/milvus/tests/python_client/deploy/scripts/utils.py", line 147, in load_and_search
    res = c.search(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 698, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/stub.py", line 50, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/stub.py", line 42, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/stub.py", line 1055, in search
    return handler.search(collection_name, data, anns_field, param, limit, expression,
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 87, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 69, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 106, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 646, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 87, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 69, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 607, in _execute_search_requests
    raise pre_err
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 595, in _execute_search_requests
    response = ft.result()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1647982562.510434201","description":"Error received from peer ipv4:127.0.0.1:19530","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Deadline Exceeded","grpc_status":4}"
```

### Expected Behavior

all test cases passed

### Steps To Reproduce

```markdown
see https://github.com/milvus-io/milvus/runs/5650819759?check_suite_focus=true
```

### Anything else?

failed job: https://github.com/milvus-io/milvus/runs/5650819759?check_suite_focus=true
log: https://github.com/milvus-io/milvus/suites/5759862209/artifacts/191477048

**Comment by yanliang567** [comment]
@sunby could you please help on this issue, it is reported frequently recently in community. 

/assign @sunby 
/unassign

**Comment by zhuwenxing** [comment]
failed job: https://github.com/zhuwenxing/milvus/runs/5666841651?check_suite_focus=true
log: https://github.com/zhuwenxing/milvus/suites/5775653160/artifacts/192383950

**Comment by zhuwenxing** [comment]
This does not 100% happen. In the Milvus origin repo, this action job passed, but in my fork repo, it failed.

**Comment by zhuwenxing** [comment]
* failed job: https://github.com/milvus-io/milvus/runs/5682811757?check_suite_focus=true
search raise error when docker-compose down then docker-compose up

* failed job: https://github.com/milvus-io/milvus/runs/5682811757?check_suite_focus=true
search raise error when docker-compose restart

**Comment by zhuwenxing** [comment]
/assign @xige-16 
Please help to take a look, it happened a lot recently

**Comment by zhuwenxing** [comment]
/assign @jaime0815 

please help to take a look

**Comment by jaime0815** [comment]
![image](https://user-images.githubusercontent.com/4024711/160354862-bf61d560-5f33-4724-8d8d-cdfda8767ac4.png)
found a lot of WARN about put kv  data into Etcd failed.

**Comment by jaime0815** [comment]
> 
```
[35;1mmilvus-querycoord |ESC[0m [2022/03/23 20:57:08.247 +00:00] [ERROR] [task_scheduler.go:236] ["reloadFromKV: taskStateInfo and triggerTaskInfo are inconsistent"] [stack="github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).reloadFromKV\n\t/go/src/github.com/mil
vus-io/milvus/internal/querycoord/task_scheduler.go:236\ngithub.com/milvus-io/milvus/internal/querycoord.newTaskScheduler\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:174\ngithub.com/milvus-io/milvus/internal/querycoord.(*QueryCoord).Init.func1\n\t
/go/src/github.com/milvus-io/milvus/internal/querycoord/query_coord.go:204\nsync.(*Once).doSlow\n\t/usr/local/go/src/sync/once.go:68\nsync.(*Once).Do\n\t/usr/local/go/src/sync/once.go:59\ngithub.com/milvus-io/milvus/internal/querycoord.(*QueryCoord).Init\n\t/go/src/github.com/mil
vus-io/milvus/internal/querycoord/query_coord.go:138\ngithub.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/service.go:226\ngithub.com/milvus-io/milvus/internal/distributed/querycoord.(*Se
rver).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/service.go:95\ngithub.com/milvus-io/milvus/cmd/components.(*QueryCoord).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/query_coord.go:50\ngithub.com/milvus-io/milvus/cmd/roles.(*MilvusRole
s).runQueryCoord.func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:189"]
```
According to the ERROR log, it seems a local environmental issue, your Etcd has dirty data.

**Comment by jaime0815** [comment]
> * failed job: https://github.com/milvus-io/milvus/runs/5682811757?check_suite_focus=true
>   search raise error when docker-compose down then docker-compose up
> * failed job: https://github.com/milvus-io/milvus/runs/5682811757?check_suite_focus=true
>   search raise error when docker-compose restart

![image](https://user-images.githubusercontent.com/4024711/160358714-1f3d2e13-1b45-48ab-8ad2-39d199887b33.png)

there is a different issue with the above one,  putting data into Etcd failed.

**Comment by AlviseSembenico** [comment]
Hi, I am having the same problem on K8S after a restart of the service if any collection was already loaded
