### ISSUE TITLE
[Bug]: [Chaos][minio]Load failed when verifying all collections after minio pod recovered from pod kill

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#16308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220330-0f53989f
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.0.2.dev10
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
21:41:04  check collection Checker__cRCvJD5D
21:41:04  collection is exist
21:41:04  
21:41:04  Create collection...
21:41:04  
21:41:04  Insert 3000 vectors cost 0.2264 seconds
21:41:04  
21:41:04  Get collection entities...
21:41:04  6310
21:41:04  
21:41:04  Get collection entities cost 3.0213 seconds
21:41:04  
21:41:04  Create index...
21:41:04  
21:41:04  Create index cost 2.1812 seconds
21:41:04  
21:41:04  load collection...
21:41:04  Traceback (most recent call last):
21:41:04    File "scripts/verify_all_collections.py", line 116, in <module>
21:41:04      hello_milvus(collection_name)
21:41:04    File "scripts/verify_all_collections.py", line 72, in hello_milvus
21:41:04      collection.load()
21:41:04    File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 453, in load
21:41:04      conn.load_collection(self._name, timeout=timeout, **kwargs)
21:41:04    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 56, in handler
21:41:04      raise e
21:41:04    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 41, in handler
21:41:04      return func(self, *args, **kwargs)
21:41:04    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 74, in handler
21:41:04      raise e
21:41:04    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 70, in handler
21:41:04      return func(*args, **kwargs)
21:41:04    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 669, in load_collection
21:41:04      self.wait_for_loading_collection(collection_name, timeout)
21:41:04    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 56, in handler
21:41:04      raise e
21:41:04    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 41, in handler
21:41:04      return func(self, *args, **kwargs)
21:41:04    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 74, in handler
21:41:04      raise e
21:41:04    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 70, in handler
21:41:04      return func(*args, **kwargs)
21:41:04    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 689, in wait_for_loading_collection
21:41:04      return self._wait_for_loading_collection_v2(collection_name, timeout)
21:41:04    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 713, in _wait_for_loading_collection_v2
21:41:04      raise BaseException(response.status.error_code, response.status.reason)
21:41:04  pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=collection 432183004226125825 has not been loaded to memory or load failed)>
```

### Expected Behavior

all test cases passed

### Steps To Reproduce

```markdown
see http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/2418/pipeline
```

### Anything else?

logs:
[artifacts-minio-pod-kill-2418-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/8385361/artifacts-minio-pod-kill-2418-server-logs.tar.gz)

**Comment by yanliang567** [comment]
@soothing-rain could you please take a look at this issue?
/assign @soothing-rain 
/unassign
