### ISSUE TITLE
[Bug]: [benchmark][cluster] Milvus search reports an error "StatusCode.DEADLINE_EXCEEDED"

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#16356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220401-5494f3c
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus==2.0.2.dev5
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo
benchmark-cron-1648828800
server-configmap
server-cluster-8c16m
client-configmap
client-acc-glove-ivf-flat

client log
```
[2022-04-01 17:39:46,275] [   ERROR] - grpc RpcError: [_execute_search_requests], <_MultiThreadedRendezvous: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded>, <Time:{'RPC start': '2022-04-01 17:34:46.271043', 'gRPC error': '2022-04-01 17:39:46.275529'}> (pymilvus.decorators:81)
[2022-04-01 17:39:46,276] [   ERROR] - grpc RpcError: [search], <_MultiThreadedRendezvous: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded>, <Time:{'RPC start': '2022-04-01 17:34:45.884496', 'gRPC error': '2022-04-01 17:39:46.276905'}> (pymilvus.decorators:81)
[2022-04-01 17:39:46,282] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 95, in run_suite
    result = runner.run_case(case_metric, **case)
  File "/src/milvus_benchmark/runners/accuracy.py", line 282, in run_case
    guarantee_timestamp=case_param["guarantee_timestamp"])
  File "/src/milvus_benchmark/client.py", line 49, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 324, in query
    result = self._milvus.search(tmp_collection_name, **params)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 829, in search
    partition_names, output_fields, timeout, round_decimal, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 49, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 82, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 21, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 457, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 82, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 404, in _execute_search_requests
    raise pre_err
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 392, in _execute_search_requests
    response = ft.result()
  File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1648834786.271811905","description":"Error received from peer ipv4:10.96.181.11:19530","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
 (milvus_benchmark.main:98)
[2022-04-01 17:39:46,282] [    INFO] - None (milvus_benchmark.main:99)
[2022-04-01 17:39:46,283] [   DEBUG] - {'type': 'ann_accuracy', 'value': {}} (milvus_benchmark.main:107)
```
server:
```
NAME                                                             READY   STATUS      RESTARTS   AGE     IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-cron-1648828800-5-etcd-0                               1/1     Running     0          2m55s   10.97.16.208   qa-node013.zilliz.local   <none>           <none>
benchmark-cron-1648828800-5-etcd-1                               1/1     Running     0          2m54s   10.97.17.212   qa-node014.zilliz.local   <none>           <none>
benchmark-cron-1648828800-5-etcd-2                               1/1     Running     0          2m54s   10.97.16.210   qa-node013.zilliz.local   <none>           <none>
benchmark-cron-1648828800-5-milvus-datacoord-65dcb77cc6-4ns5w    1/1     Running     0          2m55s   10.97.9.52     qa-node007.zilliz.local   <none>           <none>
benchmark-cron-1648828800-5-milvus-datanode-797fd994bc-rgm6c     1/1     Running     0          2m55s   10.97.20.153   qa-node018.zilliz.local   <none>           <none>
benchmark-cron-1648828800-5-milvus-indexcoord-57fdb9c8b9-s9lzc   1/1     Running     0          2m55s   10.97.5.235    qa-node003.zilliz.local   <none>           <none>
benchmark-cron-1648828800-5-milvus-indexnode-bcb76b774-dqgd4     1/1     Running     0          2m55s   10.97.12.180   qa-node015.zilliz.local   <none>           <none>
benchmark-cron-1648828800-5-milvus-proxy-778db6c9b9-ktrj5        1/1     Running     0          2m55s   10.97.18.189   qa-node017.zilliz.local   <none>           <none>
benchmark-cron-1648828800-5-milvus-querycoord-5474cc9d98-lbdhd   1/1     Running     0          2m55s   10.97.18.188   qa-node017.zilliz.local   <none>           <none>
benchmark-cron-1648828800-5-milvus-querynode-765465f7b-zh4gh     1/1     Running     0          2m54s   10.97.17.209   qa-node014.zilliz.local   <none>           <none>
benchmark-cron-1648828800-5-milvus-rootcoord-6bf64c75b-mrq4z     1/1     Running     0          2m55s   10.97.5.236    qa-node003.zilliz.local   <none>           <none>
benchmark-cron-1648828800-5-minio-0                              1/1     Running     0          2m55s   10.97.19.72    qa-node016.zilliz.local   <none>           <none>
benchmark-cron-1648828800-5-minio-1                              1/1     Running     0          2m55s   10.97.19.71    qa-node016.zilliz.local   <none>           <none>
benchmark-cron-1648828800-5-minio-2                              1/1     Running     0          2m55s   10.97.19.73    qa-node016.zilliz.local   <none>           <none>
benchmark-cron-1648828800-5-minio-3                              1/1     Running     0          2m54s   10.97.19.74    qa-node016.zilliz.local   <none>           <none>
benchmark-cron-1648828800-5-pulsar-bookie-0                      1/1     Running     0          2m54s   10.97.3.225    qa-node001.zilliz.local   <none>           <none>
benchmark-cron-1648828800-5-pulsar-bookie-1                      1/1     Running     0          2m54s   10.97.5.238    qa-node003.zilliz.local   <none>           <none>
benchmark-cron-1648828800-5-pulsar-bookie-2                      1/1     Running     0          2m54s   10.97.18.194   qa-node017.zilliz.local   <none>           <none>
benchmark-cron-1648828800-5-pulsar-bookie-init-jhrvb             0/1     Completed   0          2m55s   10.97.3.223    qa-node001.zilliz.local   <none>           <none>
benchmark-cron-1648828800-5-pulsar-broker-0                      1/1     Running     0          2m55s   10.97.9.53     qa-node007.zilliz.local   <none>           <none>
benchmark-cron-1648828800-5-pulsar-proxy-0                       1/1     Running     0          2m55s   10.97.5.237    qa-node003.zilliz.local   <none>           <none>
benchmark-cron-1648828800-5-pulsar-pulsar-init-fkkd9             0/1     Completed   0          2m55s   10.97.3.222    qa-node001.zilliz.local   <none>           <none>
benchmark-cron-1648828800-5-pulsar-recovery-0                    1/1     Running     0          2m55s   10.97.18.187   qa-node017.zilliz.local   <none>           <none>
benchmark-cron-1648828800-5-pulsar-zookeeper-0                   1/1     Running     0          2m55s   10.97.3.224    qa-node001.zilliz.local   <none>           <none>
benchmark-cron-1648828800-5-pulsar-zookeeper-1                   1/1     Running     0          2m32s   10.97.18.195   qa-node017.zilliz.local   <none>           <none>
benchmark-cron-1648828800-5-pulsar-zookeeper-2                   1/1     Running     0          2m4s    10.97.4.194    qa-node002.zilliz.local   <none>           <none>
```

### Steps To Reproduce

```markdown
1.create a collection
2.insert data
3.create an index with ivf flat
4.load collection
5.query->rasie error
```

### Anything else?

client-acc-glove-ivf-flat
```
{
	"config.yaml": "ann_accuracy:
		  collections:
		    -
		      milvus:
		        cache_config.cpu_cache_capacity: 16GB
		        engine_config.use_blas_threshold: 1100
		      server:
		        cpus: 12
		      source_file: /test/milvus/ann_hdf5/glove-200-angular.hdf5
		      collection_name: glove_200_angular
		      index_types: ['ivf_flat']
		      index_params:
		        nlist: [1024]
		      top_ks: [10]
		      nqs: [10000]
		      search_params:
		        nprobe: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512]
		"
}
```

**Comment by jingkl** [comment]
This issue is the same as issue 16026, which reports the same error

**Comment by congqixia** [comment]
From the proxy log([link](https://kibana-dev.milvus.io/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-03-31T16:00:00.000Z',to:now))&_a=(columns:!(log),filters:!(),index:ad1e1c50-c9d9-11eb-9e1a-b3dcad9693fd,interval:auto,query:(language:kuery,query:'kubernetes.pod_name.keyword%20:%20%22benchmark-cron-1648828800-5-milvus-proxy-778db6c9b9-ktrj5%22%20and%20log%20:%20%22Search%20failed%20to%22'),sort:!(!('@timestamp',desc)))))
```
[2022/04/01 17:39:46.271 +00:00] [WARN] [impl.go:2474] ["Search failed to WaitToFinish"] [error="proxy TaskCondition context Done"] [traceID=74296bfbaf26c77] [role=proxy] [msgID=432230770626548684] [db=] [collection=glove_200_angular] [partitions="[]"] [dsl=] [len(PlaceholderGroup)=5262070] [OutputFields="[]"] [search_params="[{\"key\":\"anns_field\",\"value\":\"float_vector\"},{\"key\":\"topk\",\"value\":\"10\"},{\"key\":\"metric_type\",\"value\":\"IP\"},{\"key\":\"params\",\"value\":\"{\\\"nprobe\\\":512}\"},{\"key\":\"round_decimal\",\"value\":\"-1\"}]"] [travel_timestamp=0] [guarantee_timestamp=432232066160001024] 
```
This is the only search failed and the reason was context done(timeout).
Inspected the querynode log ([link](https://kibana-dev.milvus.io/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-04-01T09:00:00.000Z',to:now))&_a=(columns:!(log),filters:!(),index:ad1e1c50-c9d9-11eb-9e1a-b3dcad9693fd,interval:auto,query:(language:kuery,query:'kubernetes.pod_name.keyword%20:%20%22benchmark-cron-1648828800-5-milvus-querynode-765465f7b-zh4gh%22%20and%20log:%20%22432230770626548684%22'),sort:!(!('@timestamp',desc))))) :
```
[2022/04/01 17:40:31.422 +00:00] [DEBUG] [time_recorder.go:78] ["search 432230645846183233(nq=6553, k=10), msgID = 432230770626548684: historical search done, msgID = 432230770626548684 (344907ms)"] 
```
This historical search costed more  344 seconds, which caused search timeout.

**Comment by xiaofan-luan** [comment]
emm, why does it take so long to search? what is the data size?

**Comment by jingkl** [comment]
> emm, why does it take so long to search? what is the data size?

data size is 1183514
