### ISSUE TITLE
[Bug]: [chaos][standalone]Load failed when verifying all collections after standalone pod recovered from pod kill

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#16389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220405-73231808
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.0.2.dev10
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2022-04-05T13:12:00.370Z] load collection...

[2022-04-05T13:12:00.370Z] Traceback (most recent call last):

[2022-04-05T13:12:00.370Z]   File "scripts/verify_all_collections.py", line 116, in <module>

[2022-04-05T13:12:00.370Z]     hello_milvus(collection_name)

[2022-04-05T13:12:00.370Z]   File "scripts/verify_all_collections.py", line 72, in hello_milvus

[2022-04-05T13:12:00.370Z]     collection.load()

[2022-04-05T13:12:00.370Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 453, in load

[2022-04-05T13:12:00.370Z]     conn.load_collection(self._name, timeout=timeout, **kwargs)

[2022-04-05T13:12:00.370Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 56, in handler

[2022-04-05T13:12:00.370Z]     raise e

[2022-04-05T13:12:00.370Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 41, in handler

[2022-04-05T13:12:00.370Z]     return func(self, *args, **kwargs)

[2022-04-05T13:12:00.370Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 74, in handler

[2022-04-05T13:12:00.370Z]     raise e

[2022-04-05T13:12:00.370Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 70, in handler

[2022-04-05T13:12:00.370Z]     return func(*args, **kwargs)

[2022-04-05T13:12:00.370Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 669, in load_collection

[2022-04-05T13:12:00.370Z]     self.wait_for_loading_collection(collection_name, timeout)

[2022-04-05T13:12:00.370Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 56, in handler

[2022-04-05T13:12:00.371Z]     raise e

[2022-04-05T13:12:00.371Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 41, in handler

[2022-04-05T13:12:00.371Z]     return func(self, *args, **kwargs)

[2022-04-05T13:12:00.371Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 74, in handler

[2022-04-05T13:12:00.371Z]     raise e

[2022-04-05T13:12:00.371Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 70, in handler

[2022-04-05T13:12:00.371Z]     return func(*args, **kwargs)

[2022-04-05T13:12:00.371Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 689, in wait_for_loading_collection

[2022-04-05T13:12:00.371Z]     return self._wait_for_loading_collection_v2(collection_name, timeout)

[2022-04-05T13:12:00.371Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 713, in _wait_for_loading_collection_v2

[2022-04-05T13:12:00.371Z]     raise BaseException(response.status.error_code, response.status.reason)

[2022-04-05T13:12:00.371Z] pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=collection 432318420536262657 has not been loaded to memory or load failed)>
```

### Expected Behavior

all test cases all passed

### Steps To Reproduce

```markdown
see http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/2764/pipeline/208
```

### Anything else?

log: [artifacts-standalone-pod-kill-2764-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/8422884/artifacts-standalone-pod-kill-2764-server-logs.tar.gz)

**Comment by yanliang567** [comment]
/assign @soothing-rain 
@soothing-rain could you please hlep on this issue?

/unassign
