### ISSUE TITLE
[Bug]: [benchmark][cluster] Minio crash and querynode restart, client connection raise error: proxy not healthy

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#16413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220406-909dd73
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.0.dev18
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task: benchmark-cluster-cron-1649278800

test yaml:
client-configmap:client-search-locust,instanceId:3,server-configmap:server-cluster-8c16m

client pod: benchmark-cluster-cron-1649278800-2687487343

client log:
```
[2022-04-06 21:24:08,521] [    INFO] - Prepare to run cases (milvus_benchmark.main:86)
[2022-04-06 21:24:08,532] [   ERROR] - RPC error: [has_collection], <BaseException: (code=1, message=proxy not healthy)>, <Time:{'RPC start': '2022-04-06 21:24:08.522133', 'RPC error': '2022-04-06 21:24:08.532877'}> (pymilvus.decorators:73)
[2022-04-06 21:24:08,533] [   ERROR] - <BaseException: (code=1, message=proxy not healthy)> (milvus_benchmark.main:118)
[2022-04-06 21:24:08,539] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 87, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/locust.py", line 283, in prepare
    if self.milvus.exists_collection():
  File "/src/milvus_benchmark/client.py", line 49, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 474, in exists_collection
    res = self._milvus.has_collection(collection_name)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 140, in has_collection
    return handler.has_collection(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 170, in has_collection
    raise BaseException(reply.status.error_code, reply.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=proxy not healthy)>
 (milvus_benchmark.main:119)
[2022-04-06 21:24:08,544] [   DEBUG] - {'_version': '0.1', '_type': 'metric', 'run_id': 1649283765, 'mode': 'local', 'server': <milvus_benchmark.metrics.models.server.Server object at 0x7f2193f10940>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware object at 0x7f2193f10dd8>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7f2193f10be0>, 'status': 'RUN_FAILED', 'err_message': '', 'collection': {'dimension': 128, 'metric_type': 'l2', 'dataset_name': 'sift_1m_128_l2', 'collection_size': 1000000, 'other_fields': None, 'ni_per': 50000, 'shards_num': None}, 'index': {'index_type': 'ivf_sq8', 'index_param': {'nlist': 1024}}, 'search': {'nq': 1, 'topk': 10, 'search_param': {'nprobe': 16}}, 'run_params': {'task': {'connection_num': 1, 'clients_num': 100, 'spawn_rate': 2, 'during_time': 600, 'types': [{'type': 'query', 'weight': 1, 'params': {'top_k': 10, 'nq': 1, 'search_param': {'nprobe': 16}}}]}, 'connection_type': 'single'}, 'metrics': {'type': 'locust_search_performance', 'value': {}}, 'datetime': '2022-04-06 21:24:08.467550', 'type': 'metric'} (milvus_benchmark.metric.api:29)
```

server:
```
NAME                                                              READY   STATUS             RESTARTS   AGE    IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-cluster-cron-1649278800-3-etcd-0                        1/1     Running            0          6h2m   10.97.17.110   qa-node014.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649278800-3-etcd-1                        1/1     Running            0          6h2m   10.97.16.17    qa-node013.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649278800-3-etcd-2                        1/1     Running            0          6h2m   10.97.17.111   qa-node014.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649278800-3-milvus-datacoord-7d5cdb7cm9   1/1     Running            0          6h2m   10.97.5.17     qa-node003.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649278800-3-milvus-datanode-6f9d884ngvr   1/1     Running            0          6h2m   10.97.11.13    qa-node009.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649278800-3-milvus-indexcoord-f77fqfkrx   1/1     Running            0          6h2m   10.97.18.133   qa-node017.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649278800-3-milvus-indexnode-84c7d7rzd9   1/1     Running            0          6h2m   10.97.20.124   qa-node018.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649278800-3-milvus-proxy-55795dcfcqrbwv   1/1     Running            0          6h2m   10.97.18.135   qa-node017.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649278800-3-milvus-querycoord-6798h7f6b   1/1     Running            0          6h2m   10.97.5.19     qa-node003.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649278800-3-milvus-querynode-55d645grkk   1/1     Running            24         6h2m   10.97.20.125   qa-node018.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649278800-3-milvus-rootcoord-5d6b58g42q   1/1     Running            0          6h2m   10.97.5.15     qa-node003.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649278800-3-minio-0                       0/1     CrashLoopBackOff   75         6h2m   10.97.12.93    qa-node015.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649278800-3-minio-1                       1/1     Running            0          6h2m   10.97.19.123   qa-node016.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649278800-3-minio-2                       1/1     Running            0          6h2m   10.97.19.124   qa-node016.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649278800-3-minio-3                       1/1     Running            0          6h2m   10.97.12.89    qa-node015.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649278800-3-pulsar-bookie-0               1/1     Running            0          6h2m   10.97.18.138   qa-node017.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649278800-3-pulsar-bookie-1               1/1     Running            0          6h2m   10.97.9.52     qa-node007.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649278800-3-pulsar-bookie-2               1/1     Running            0          6h2m   10.97.5.21     qa-node003.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649278800-3-pulsar-bookie-init-rc7hz      0/1     Completed          0          6h2m   10.97.18.134   qa-node017.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649278800-3-pulsar-broker-0               1/1     Running            0          6h2m   10.97.9.51     qa-node007.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649278800-3-pulsar-proxy-0                1/1     Running            0          6h2m   10.97.3.234    qa-node001.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649278800-3-pulsar-pulsar-init-hmnxq      0/1     Completed          0          6h2m   10.97.9.50     qa-node007.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649278800-3-pulsar-recovery-0             1/1     Running            0          6h2m   10.97.3.233    qa-node001.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649278800-3-pulsar-zookeeper-0            1/1     Running            0          6h2m   10.97.5.20     qa-node003.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649278800-3-pulsar-zookeeper-1            1/1     Running            0          6h2m   10.97.10.56    qa-node008.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649278800-3-pulsar-zookeeper-2            1/1     Running            0          6h1m   10.97.3.235    qa-node001.zilliz.local   <none>           <none>
```

**Comment by wangting0128** [comment]
argo task: benchmark-cluster-cron-1649365200

test yaml: client-configmap:client-search-locust,instanceId:3,server-configmap:server-cluster-8c16m

server:
```
NAME                                                              READY   STATUS             RESTARTS   AGE     IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-cluster-cron-1649365200-3-etcd-0                        1/1     Running            0          5h49m   10.97.17.2     qa-node014.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649365200-3-etcd-1                        1/1     Running            0          5h49m   10.97.16.84    qa-node013.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649365200-3-etcd-2                        1/1     Running            0          5h49m   10.97.17.7     qa-node014.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649365200-3-milvus-datacoord-5899465ch8   1/1     Running            0          5h49m   10.97.9.172    qa-node007.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649365200-3-milvus-datanode-6bf9d6ffzpz   1/1     Running            0          5h49m   10.97.11.249   qa-node009.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649365200-3-milvus-indexcoord-58cdd2v8l   1/1     Running            0          5h49m   10.97.9.168    qa-node007.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649365200-3-milvus-indexnode-7b4d68vmgl   1/1     Running            0          5h49m   10.97.12.29    qa-node015.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649365200-3-milvus-proxy-78cc8b4bdgfzrh   1/1     Running            0          5h49m   10.97.9.169    qa-node007.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649365200-3-milvus-querycoord-76ddrbt4n   1/1     Running            0          5h49m   10.97.9.170    qa-node007.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649365200-3-milvus-querynode-56ff4p42pj   1/1     Running            23         5h49m   10.97.17.243   qa-node014.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649365200-3-milvus-rootcoord-6757cznwlr   1/1     Running            0          5h49m   10.97.9.166    qa-node007.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649365200-3-minio-0                       0/1     CrashLoopBackOff   72         5h49m   10.97.19.94    qa-node016.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649365200-3-minio-1                       1/1     Running            0          5h49m   10.97.19.93    qa-node016.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649365200-3-minio-2                       1/1     Running            0          5h49m   10.97.19.90    qa-node016.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649365200-3-minio-3                       1/1     Running            0          5h49m   10.97.16.80    qa-node013.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649365200-3-pulsar-bookie-0               0/1     Init:0/1           0          5h49m   <none>         qa-node007.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649365200-3-pulsar-bookie-1               1/1     Running            0          5h49m   10.97.5.250    qa-node003.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649365200-3-pulsar-bookie-2               1/1     Running            0          5h49m   10.97.3.63     qa-node001.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649365200-3-pulsar-bookie-init-jpjcz      0/1     Completed          0          5h49m   10.97.9.171    qa-node007.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649365200-3-pulsar-broker-0               1/1     Running            0          5h49m   10.97.19.89    qa-node016.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649365200-3-pulsar-proxy-0                1/1     Running            0          5h49m   10.97.18.166   qa-node017.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649365200-3-pulsar-pulsar-init-285z9      0/1     Completed          0          5h49m   10.97.9.167    qa-node007.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649365200-3-pulsar-recovery-0             1/1     Running            0          5h49m   10.97.3.62     qa-node001.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649365200-3-pulsar-zookeeper-0            1/1     Running            0          5h49m   10.97.5.249    qa-node003.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649365200-3-pulsar-zookeeper-1            1/1     Running            0          5h48m   10.97.4.190    qa-node002.zilliz.local   <none>           <none>
benchmark-cluster-cron-1649365200-3-pulsar-zookeeper-2            1/1     Running            0          5h48m   10.97.4.191    qa-node002.zilliz.local   <none>           <none>
```

**Comment by yanliang567** [comment]
/assign @congqixia 
@congqixia could you please help to take a look at this issue

/unassign
