### ISSUE TITLE
[Bug]: [chaos] Create index failed after etcd pod recovered from network latency chaos

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#16412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220406-909dd737
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus==2.0.2.dev10
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2022-04-06T15:03:57.777Z] check collection Checker__ZW9fEoHz

[2022-04-06T15:03:57.777Z] collection is exist

[2022-04-06T15:03:57.777Z] 

[2022-04-06T15:03:57.777Z] Create collection...

[2022-04-06T15:03:57.777Z] 

[2022-04-06T15:03:57.777Z] Insert 3000 vectors cost 0.2337 seconds

[2022-04-06T15:03:57.777Z] 

[2022-04-06T15:03:57.777Z] Get collection entities...

[2022-04-06T15:03:57.777Z] 6890

[2022-04-06T15:03:57.777Z] 

[2022-04-06T15:03:57.777Z] Get collection entities cost 3.0250 seconds

[2022-04-06T15:03:57.777Z] 

[2022-04-06T15:03:57.777Z] Create index...

[2022-04-06T15:03:57.777Z] Traceback (most recent call last):

[2022-04-06T15:03:57.777Z]   File "scripts/verify_all_collections.py", line 116, in <module>

[2022-04-06T15:03:57.777Z]     hello_milvus(collection_name)

[2022-04-06T15:03:57.777Z]   File "scripts/verify_all_collections.py", line 67, in hello_milvus

[2022-04-06T15:03:57.777Z]     collection.create_index(field_name="float_vector", index_params=default_index)

[2022-04-06T15:03:57.777Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 1033, in create_index

[2022-04-06T15:03:57.777Z]     timeout=timeout, **kwargs)

[2022-04-06T15:03:57.777Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 56, in handler

[2022-04-06T15:03:57.777Z]     raise e

[2022-04-06T15:03:57.777Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 41, in handler

[2022-04-06T15:03:57.777Z]     return func(self, *args, **kwargs)

[2022-04-06T15:03:57.777Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 74, in handler

[2022-04-06T15:03:57.777Z]     raise e

[2022-04-06T15:03:57.777Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 70, in handler

[2022-04-06T15:03:57.777Z]     return func(*args, **kwargs)

[2022-04-06T15:03:57.777Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 592, in create_index

[2022-04-06T15:03:57.777Z]     raise BaseException(status.error_code, status.reason)

[2022-04-06T15:03:57.777Z] pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=CreateIndex failed: getSegmentInfo from data service failed, error = failed to get segment 432342920604418049)>
```

### Expected Behavior

all test cases passed

### Steps To Reproduce

```markdown
see pipeline http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/2869/pipeline/208
```

### Anything else?

log：
[artifacts-etcd-network-latency-2869-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/8439473/artifacts-etcd-network-latency-2869-server-logs.1.tar.gz)

**Comment by yanliang567** [comment]
@DragonDriver could u please help in this issue?
/assign @DragonDriver 
/unassign

**Comment by DragonDriver** [comment]
@xiaocai2333 will resolve this.
/assign @xiaocai2333 
/unassign
