### ISSUE TITLE
[Bug]: proxy not healthy

### ISSUE THREAD

**Issue by jiaminger** [milvus-io/milvus#16411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.1-1-1
- Deployment mode(standalone or cluster): standalone (use apt install)
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 
- OS(Ubuntu or CentOS): Ubuntu 18
- CPU/Memory: 64G
- GPU: tesla t4
- Others:
```

### Current Behavior

When I do connection and create collection, <BaseException: (code=1, message=proxy not healthy)> happens, the error msg as follows:
RPC error: [has_collection], <BaseException: (code=1, message=proxy not healthy)>, <Time:{'RPC start': '2022-04-07 12:19:04.199833', 'RPC error': '2022-04-07 12:19:04.201820'}>
Traceback (most recent call last):
  File "/home/eagle/zhangjw/py_workspace/pytorch-car-cls/hello_milvus.py", line 369, in <module>
    query()
  File "/home/eagle/zhangjw/py_workspace/pytorch-car-cls/hello_milvus.py", line 297, in query
    features_db = Collection(collection_name, consistency_level="Strong")
  File "/home/eagle/anaconda3/lib/python3.9/site-packages/pymilvus/orm/collection.py", line 125, in __init__
    has = conn.has_collection(self._name)
  File "/home/eagle/anaconda3/lib/python3.9/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/home/eagle/anaconda3/lib/python3.9/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/home/eagle/anaconda3/lib/python3.9/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/home/eagle/anaconda3/lib/python3.9/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/home/eagle/anaconda3/lib/python3.9/site-packages/pymilvus/client/grpc_handler.py", line 169, in has_collection
    raise BaseException(reply.status.error_code, reply.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=proxy not healthy)>

### Expected Behavior

When I do connection and create collection, list collection should be work

**Comment by jiaminger** [comment]
I can't find a solution, I use apt remove and apt install again. The problem is solved temporarily, I don't know why.

**Comment by soothing-rain** [comment]
Hey @jiaminger sometimes Milvus needs some time to fully start up, especially when there are a lot of data & services states to process.

The proxy service should usually become healthy after a while, if not, feel free to send us logs so that we can further investigate!

**Comment by xiaofan-luan** [comment]
> I can't find a solution, I use apt remove milvus and apt install again. The problem is solved temporarily, I don't know why.

looks like proxy is crashed, we may need more information about why proxy is crashed

**Comment by yanliang567** [comment]
@jiaminger could you please retry on lastest 2.0.2 and help to upload the logs according to https://github.com/milvus-io/milvus/tree/master/deployments/export-log

/assign @jiaminger 
/unassign

**Comment by hopekkl123** [comment]
I also encountered the same problem,

**environment：**

- Milvus version: 2.0.2
- Deployment mode(standalone or cluster): standalone (use apt install)
- SDK version(e.g. pymilvus v2.0.2): pymilvus 
- OS(Ubuntu or CentOS): Ubuntu 22

- Others:

`Traceback (most recent call last):
  File "/home/mong/hello_milvus.py", line 34, in <module>
    has = utility.has_collection("hello_milvus")
  File "/usr/local/lib/python3.10/dist-packages/pymilvus/orm/utility.py", line 354, in has_collection
    return _get_connection(using).has_collection(collection_name)
  File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pymilvus/client/grpc_handler.py", line 169, in has_collection
    raise BaseException(reply.status.error_code, reply.status.reason)`

Currently the problem is not resolved。

**Comment by xiaofan-luan** [comment]
> I also encountered the same problem,
> 
> **environment：**
> 
> * Milvus version: 2.0.2
> * Deployment mode(standalone or cluster): standalone (use apt install)
> * SDK version(e.g. pymilvus v2.0.2): pymilvus
> * OS(Ubuntu or CentOS): Ubuntu 22
> * Others:
> 
> `root@mon:/home/motiong# python3 hello_milvus.py
> 
> === start connecting to Milvus ===
> 
> RPC error: [has_collection], <BaseException: (code=1, message=proxy not healthy)>, <Time:{'RPC start': '2023-07-20 03:21:22.783335', 'RPC error': '2023-07-20 03:21:22.784300'}> Traceback (most recent call last): File "/home/mon/hello_milvus.py", line 34, in has = utility.has_collection("hello_milvus") File "/usr/local/lib/python3.10/dist-packages/pymilvus/orm/utility.py", line 354, in has_collection return _get_connection(using).has_collection(collection_name) File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 56, in handler raise e File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 41, in handler return func(self, *args, **kwargs) File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 74, in handler raise e File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 70, in handler return func(*args, **kwargs) File "/usr/local/lib/python3.10/dist-packages/pymilvus/client/grpc_handler.py", line 169, in has_collection raise BaseException(reply.status.error_code, reply.status.reason) pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=proxy not healthy)>`
> 
> Currently the problem is not resolved。

you will need to offer detailed server side logs for further investigation
