### ISSUE TITLE
Add binary vectors failed with java-sdk

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#1642]
**Describe the bug**
```
test_add_vectors_binary (io.milvus.client.MilvusGrpcClient@449a4f23, L2_BYIbxzorUJ)
java.lang.NoSuchMethodError: java.nio.ByteBuffer.rewind()Ljava/nio/ByteBuffer;
	at io.milvus.client.MilvusGrpcClient.buildRowRecordList(MilvusGrpcClient.java:1080)
	at io.milvus.client.MilvusGrpcClient.insert(MilvusGrpcClient.java:400)
	at com.TestAddVectors.test_add_vectors_binary(TestAddVectors.java:132)
	at com.MainClass.main(MainClass.java:146)
... Removed 22 stack frames
```
**Steps/Code to reproduce behavior**
```
    public static List<ByteBuffer> genBinaryVectors(int nb, int dimension) {
        List<ByteBuffer> xb = new ArrayList<>();
        for (int i = 0; i < nb; ++i) {
            byte[] array = new byte[dimension];
            for (int j = 0; j < dimension; j++) {
                Integer num = (int)Math.round(Math.random());
                array[j] = num.byteValue();
            }
            ByteBuffer buffer = ByteBuffer.wrap(array);
            xb.add(buffer);
        }
        return xb;
    }

```
```
InsertParam insertParam = new InsertParam.Builder(collectionName).withBinaryVectors(vectorsBinary).build();
        InsertResponse res = client.insert(insertParam);
```
**Expected behavior**

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)

**Screenshots**

**Additional context**

**Comment by youny626** [comment]
I couldn't reproduce it. This has something to do with your JDK that somehow compiled incompatible bytecode
Can you try adding this to your pom.xml ?
```
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>8</source>
                    <target>8</target>
                </configuration>
                <version>3.8.1</version>
            </plugin>
        </plugins>
    </build>
```
If this does not work, try `0.6.0-SNAPSHOT`

**Comment by del-zhenwu** [comment]
```
信息: Created collection successfully!
CollectionMapping = {collectionName = L2_ICjgtKGXyY, dimension = 128, indexFileSize = 50, metricType = L2}
三月 19, 2020 6:40:19 下午 io.milvus.client.MilvusGrpcClient logSevere
严重: Insert vectors failed:
error_code: ILLEGAL_ROWRECORD
reason: "Table metric type doesn\'t support binary vectors."
```

**Comment by youny626** [comment]
> With the current version:
> 
> ```
> 严重: Insert vectors failed:
> error_code: ILLEGAL_DIMENSION
> reason: "The vector dimension must be equal to the table dimension."
> ```

When you create the byte array, the dimension should be the original dimension / 8. Since 8 bits constitute a byte.

**Comment by del-zhenwu** [comment]
close
