### ISSUE TITLE
[Bug]: querynode retrieve core dump randomly

### ISSUE THREAD

**Issue by jaime0815** [milvus-io/milvus#16429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): MAC X86
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I am not sure it is related to dmlChannelNum configuration within milvus.yaml,  the following error will occur randomly when set to 4 and run e2e  tests.

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7fb178101000 pc=0x7fb1e2c62643]

runtime stack:
runtime.throw({0x387642a, 0x46268})
        /usr/local/go/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:719 +0x396

goroutine 14647 [syscall]:
runtime.cgocall(0x1d821f1, 0xc0011c4c58)
        /usr/local/go/src/runtime/cgocall.go:156 +0x5c fp=0xc0011c4c30 sp=0xc0011c4bf8 pc=0x8fd1dc
github.com/milvus-io/milvus/internal/querynode._Cfunc_Retrieve(0x7fb190001080, 0x7fb04004c8b0, 0x6001f7b48380004, 0xc0010de3c0)
        _cgo_gotypes.go:711 +0x55 fp=0xc0011c4c58 sp=0xc0011c4c30 pc=0x1cfac35
github.com/milvus-io/milvus/internal/querynode.(*Segment).retrieve.func1(0x3825c98, 0xb, 0xc1a54c, 0xc0010de3c0)
        /home/yun/milvus/internal/querynode/segment.go:347 +0xa6 fp=0xc0011c4cb0 sp=0xc0011c4c58 pc=0x1d0ede6
github.com/milvus-io/milvus/internal/querynode.(*Segment).retrieve(0xc0020f2340, 0xc0010de390)
        /home/yun/milvus/internal/querynode/segment.go:347 +0x125 fp=0xc0011c4d70 sp=0xc0011c4cb0 pc=0x1d0ea65
github.com/milvus-io/milvus/internal/querynode.(*historical).retrieve(0xc000bfca50, 0x6001f7ac8f40002, {0x0, 0x80000000, 0x1}, {0x3ba3ce8, 0xc001806060}, 0xc001f610e0)
        /home/yun/milvus/internal/querynode/historical.go:82 +0x4e5 fp=0xc0011c4f50 sp=0xc0011c4d70 pc=0x1cc6385
github.com/milvus-io/milvus/internal/querynode.(*queryCollection).retrieve(0xc0004dc960, {0x3babf90, 0xc0004d60f0})
        /home/yun/milvus/internal/querynode/query_collection.go:1309 +0x4ec fp=0xc0011c5760 sp=0xc0011c4f50 pc=0x1cded0c
github.com/milvus-io/milvus/internal/querynode.(*queryCollection).doUnsolvedQueryMsg(0xc0004dc960)
        /home/yun/milvus/internal/querynode/query_collection.go:673 +0x184d fp=0xc0011c5fc8 sp=0xc0011c5760 pc=0x1cd6f6d
github.com/milvus-io/milvus/internal/querynode.(*queryCollection).start·dwrap·35()
        /home/yun/milvus/internal/querynode/query_collection.go:160 +0x26 fp=0xc0011c5fe0 sp=0xc0011c5fc8 pc=0x1ccfee6
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0011c5fe8 sp=0xc0011c5fe0 pc=0x9634a1
created by github.com/milvus-io/milvus/internal/querynode.(*queryCollection).start
        /home/yun/milvus/internal/querynode/query_collection.go:160 +0x109

goroutine 1 [chan receive]:
github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run(0xc0003a3e90, 0x0, {0x0, 0x0})
        /home/yun/milvus/cmd/roles/roles.go:502 +0xc8b
github.com/milvus-io/milvus/cmd/milvus.RunMilvus({0xc000196060, 0x3, 0x3})
        /home/yun/milvus/cmd/milvus/milvus.go:325 +0xa12
main.main()
        /home/yun/milvus/cmd/main.go:26 +0x2e

goroutine 17312 [syscall]:
github.com/confluentinc/confluent-kafka-go/kafka._Cfunc__rk_queue_poll(0x7fb1000cab00, 0x64, 0xc002cd5358, 0xc0006386f0, 0x0)
        _cgo_gotypes.go:642 +0x4d
github.com/confluentinc/confluent-kafka-go/kafka.(*handle).eventPoll.func1(0xc001553e20, 0xc001553d18, 0x0, 0x1, 0x0)
        /home/yun/go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.8.2/kafka/event.go:168 +0xcd
github.com/confluentinc/confluent-kafka-go/kafka.(*handle).eventPoll(0xc0001fd148, 0xc00152a3c0, 0x64, 0x10000c0010b1f48, 0xc0001835c0)
        /home/yun/go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.8.2/kafka/event.go:168 +0x114
github.com/confluentinc/confluent-kafka-go/kafka.consumerReader(0xc0001fd140, 0xc000696a20)
        /home/yun/go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.8.2/kafka/consumer.go:573 +0x52
github.com/confluentinc/confluent-kafka-go/kafka.NewConsumer.func7()
        /home/yun/go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.8.2/kafka/consumer.go:556 +0x29
created by github.com/confluentinc/confluent-kafka-go/kafka.NewConsumer
        /home/yun/go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.8.2/kafka/consumer.go:555 +0x37b

```

**Comment by xiaofan-luan** [comment]
find thi issue in pulsar environment

**Comment by LoveEachDay** [comment]
Another user case: milvus cluster (v2.0.2) with pulsar.
[logs.tar.gz](https://github.com/milvus-io/milvus/files/8696961/logs.tar.gz)

**Comment by xiaofan-luan** [comment]
@bigsheeper any progress on it?

**Comment by xiaofan-luan** [comment]
@bigsheeper is this still a issue?

**Comment by bigsheeper** [comment]
> @bigsheeper is this still a issue?

Didn't appear for a long time, we could keep it open
