### ISSUE TITLE
[Bug]: [kafka][nightly] Drop collection failed for timeout

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#16515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: latest
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Drop collection failed for timeout

### Expected Behavior

Drop collection successfully

### Steps To Reproduce

```markdown
Running nightly:
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/475/pipeline

test case:

@pytest.mark.tags(CaseLabel.L1)
    def test_collection_after_drop(self):
        """
        target: test create collection after create and drop
        method: 1. create a 2. drop a 3, re-create a
        expected: no exception
        """
        c_name = cf.gen_unique_str(prefix)
        collection_w = self.init_collection_wrap(name=c_name, check_task=CheckTasks.check_collection_property,
                                                 check_items={exp_name: c_name, exp_schema: default_schema})
        collection_w.drop()
        assert not self.utility_wrap.has_collection(collection_w.name)[0]
        self.init_collection_wrap(name=c_name, check_task=CheckTasks.check_collection_property,
                                  check_items={exp_name: c_name, exp_schema: default_schema})
        assert self.utility_wrap.has_collection(c_name)[0]
```

### Anything else?

1. milvus logs:
[artifacts-milvus-distributed-kafka-master-475-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/475/artifact/artifacts-milvus-distributed-kafka-master-475-pymilvus-e2e-logs.tar.gz)

2. failed timeline:
[2022-04-18T01:03:32.470Z] [gw5] [  5%] FAILED testcases/test_collection.py::TestCollectionOperation::test_collection_after_drop 

3. collection name:
collection_io0xUqsB

4. test error:
```
[2022-04-18T02:16:50.629Z] [2022-04-18 01:03:10 - DEBUG - ci_test]: (api_request)  : [Collection.drop] args: [], kwargs: {'timeout': 20} (api_request.py:55)
[2022-04-18T02:16:50.629Z] [2022-04-18 01:03:30 - ERROR - pymilvus.decorators]: grpc RpcError: [drop_collection], <_MultiThreadedRendezvous: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded>, <Time:{'RPC start': '2022-04-18 01:03:10.388202', 'gRPC error': '2022-04-18 01:03:30.389231'}> (decorators.py:81)
[2022-04-18T02:16:50.629Z] [2022-04-18 01:03:30 - ERROR - ci_test]: Traceback (most recent call last):
[2022-04-18T02:16:50.629Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
[2022-04-18T02:16:50.629Z]     res = func(*args, **kwargs)
[2022-04-18T02:16:50.629Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 56, in api_request
[2022-04-18T02:16:50.629Z]     return func(*arg, **kwargs)
[2022-04-18T02:16:50.629Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 419, in drop
[2022-04-18T02:16:50.629Z]     conn.drop_collection(self._name, timeout=timeout, **kwargs)
[2022-04-18T02:16:50.629Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 49, in handler
[2022-04-18T02:16:50.629Z]     raise e
[2022-04-18T02:16:50.629Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 41, in handler
[2022-04-18T02:16:50.629Z]     return func(self, *args, **kwargs)
[2022-04-18T02:16:50.629Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 82, in handler
[2022-04-18T02:16:50.629Z]     raise e
[2022-04-18T02:16:50.629Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler
[2022-04-18T02:16:50.629Z]     return func(*args, **kwargs)
[2022-04-18T02:16:50.629Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 154, in drop_collection
[2022-04-18T02:16:50.629Z]     status = rf.result()
[2022-04-18T02:16:50.629Z]   File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 744, in result
[2022-04-18T02:16:50.629Z]     raise self
[2022-04-18T02:16:50.629Z] grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
[2022-04-18T02:16:50.629Z] 	status = StatusCode.DEADLINE_EXCEEDED
[2022-04-18T02:16:50.629Z] 	details = "Deadline Exceeded"
[2022-04-18T02:16:50.629Z] 	debug_error_string = "{"created":"@1650243810.388772927","description":"Error received from peer ipv4:10.201.56.214:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Deadline Exceeded","grpc_status":4}"
[2022-04-18T02:16:50.629Z] >
[2022-04-18T02:16:50.629Z]  (api_request.py:35)
[2022-04-18T02:16:50.629Z] [2022-04-18 01:03:30 - ERROR - ci_test]: (api_response) : <_MultiThreadedRendezvous of RPC that terminated with:
[2022-04-18T02:16:50.629Z] 	status = StatusCode.DEADLINE_EXCEEDED
[2022-04-18T02:16:50.629Z] 	details = "Deadline Exceeded"
[2022-04-18T02:16:50.629Z] 	debug_error_string = "{"created":"@1650243810.388772927","description":"Error received from peer ipv4:10.201.56.214:19530","file":"src/core/lib/surface/call.cc","file_line":1...... (api_request.py:36)
```

**Comment by binbinlv** [comment]
This issue has not been reproduced recently, so close it first and will reopen it if it occurs in the future.
