### ISSUE TITLE
[Bug]: [kafka][nightly] Search collection failed for timeout 

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#16516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:latest
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Search collection failed for timeout 

### Expected Behavior

Search collection successfully

### Steps To Reproduce

```markdown
Running nightly:

https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/474/pipeline

test case
1、


@pytest.mark.tags(CaseLabel.L1)
    def test_search_load_flush_load(self, nb, nq, dim, auto_id, _async):
        """
        target: test search when load before flush
        method: 1. insert data and load
                2. flush, and load
                3. search the collection
        expected: search success with limit(topK)
        """
        # 1. initialize with data
        collection_w = self.init_collection_general(prefix, auto_id=auto_id, dim=dim)[0]
        # 2. insert data
        insert_ids = cf.insert_data(collection_w, nb, auto_id=auto_id, dim=dim)[3]
        # 3. load data
        collection_w.load()
        # 4. flush and load
        collection_w.num_entities
        collection_w.load()
        # 5. search
        vectors = [[random.random() for _ in range(dim)] for _ in range(nq)]
        collection_w.search(vectors[:nq], default_search_field,
                            default_search_params, default_limit,
                            default_search_exp, _async=_async,
                            check_task=CheckTasks.check_search_results,
                            check_items={"nq": nq,
                                         "ids": insert_ids,
                                         "limit": default_limit,
                                         "_async": _async})


2、

```python
 @pytest.mark.tags(CaseLabel.L1)
    def test_alias_exec_operations_as_collection(self):
        """
        target: test alias 
                1.creating partition, 
                2.inserting data, 
                3.creating index, 
                4.loading collection,  
                5.searching, 
                6.releasing collection,
        method: follow the steps in target
        expected: all steps operated by alias can work
        """
        create_partition_flag = True
        insert_data_flag = True
        create_index_flag = True
        load_collection_flag = True
        search_flag = True
        release_collection_flag = True

        self._connect()
        c_name = cf.gen_unique_str("collection")
        collection_w = self.init_collection_wrap(name=c_name, schema=default_schema,
                                                 check_task=CheckTasks.check_collection_property,
                                                 check_items={exp_name: c_name, exp_schema: default_schema})
        alias_name = cf.gen_unique_str(prefix)
        self.utility_wrap.create_alias(collection_w.name, alias_name)
        # collection_w.create_alias(alias_name)
        collection_alias, _ = self.collection_wrap.init_collection(name=alias_name,
                                                                   check_task=CheckTasks.check_collection_property,
                                                                   check_items={exp_name: alias_name,
                                                                                exp_schema: default_schema})
        
        # create partition by alias
        partition_name = cf.gen_unique_str("partition")
        try:
            collection_alias.create_partition(partition_name)
        except Exception as e:
            log.info(f"alias create partition failed with exception {e}")
            create_partition_flag = False
            collection_w.create_partition(partition_name)
        
        # assert partition
        pytest.assume(create_partition_flag is True and
                      [p.name for p in collection_alias.partitions] == [p.name for p in collection_w.partitions])
        
        # insert data by alias
        df = cf.gen_default_dataframe_data(ct.default_nb)
        try:
            collection_alias.insert(data=df)
        except Exception as e:
            log.info(f"alias insert data failed with exception {e}")
            insert_data_flag = False
            collection_w.insert(data=df)
        
        # assert insert data
        pytest.assume(insert_data_flag is True and
                      collection_alias.num_entities == ct.default_nb and
                      collection_w.num_entities == ct.default_nb)            

        # create index by alias
        default_index = {"index_type": "IVF_FLAT", "params": {"nlist": 128}, "metric_type": "L2"}
        try:
            collection_alias.create_index(field_name="float_vector", index_params=default_index)
        except Exception as e:
            log.info(f"alias create index failed with exception {e}")
            create_index_flag = False
            collection_w.create_index(field_name="float_vector", index_params=default_index)
        
        # assert create index
        pytest.assume(create_index_flag is True and
                      collection_alias.has_index() is True and
                      collection_w.has_index()[0] is True)
        
        # load by alias
        try:
            collection_alias.load()
        except Exception as e:
            log.info(f"alias load collection failed with exception {e}")
            load_collection_flag = False
            collection_w.load()
        # assert load
        pytest.assume(load_collection_flag is True)

        # search by alias
        topK = 5
        search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
             
        query = [[random.random() for _ in range(ct.default_dim)] for _ in range(1)]
        alias_res = None
        try:
            alias_res = collection_alias.search(
                query, "float_vector", search_params, topK,
                "int64 >= 0", output_fields=["int64"]
            )
        except Exception as e:
            log.info(f"alias search failed with exception {e}")
            search_flag = False
          
        collection_res, _ = collection_w.search(
            query, "float_vector", search_params, topK,
            "int64 >= 0", output_fields=["int64"]
        )
        # assert search
        pytest.assume(search_flag is True and alias_res[0].ids == collection_res[0].ids)

        # release by alias
        try:
            collection_alias.release()
        except Exception as e:
            log.info(f"alias release failed with exception {e}")
            release_collection_flag = False
            collection_w.release()
        # assert release
        pytest.assume(release_collection_flag is True)

```
```


### Anything else?

1. milvus logs:
[artifacts-milvus-distributed-kafka-master-474-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/474/artifact/artifacts-milvus-distributed-kafka-master-474-pymilvus-e2e-logs.tar.gz)

2. other clues:
(1) for  failed case: test_alias_exec_operations_as_collection
collection name: collection_4B84EaBX

(2) for failed case: test_search_load_flush_load
collection name: search_collection_FzaJ8hbx

**Comment by binbinlv** [comment]
Similar issue in the following nightly:
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/469/pipeline

1. logs: 
[artifacts-milvus-distributed-kafka-master-469-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/469/artifact/artifacts-milvus-distributed-kafka-master-469-pymilvus-e2e-logs.tar.gz)

2. test case:
test_search_load_flush_load

3. collection name: search_collection_wvT1CpGx

**Comment by binbinlv** [comment]
Similar issue in the following nighlty:
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/466/pipeline

1.milvus logs: 
[artifacts-milvus-distributed-kafka-master-466-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/466/artifact/artifacts-milvus-distributed-kafka-master-466-pymilvus-e2e-logs.tar.gz)
2. test case: test_search_load_flush_load
3. collection name: search_collection_Vs7wBOYI

**Comment by binbinlv** [comment]
The test case failed is the same with #15628, not sure whether the root cause is the same, need investigation furthur.

**Comment by binbinlv** [comment]
Same error appears in the following nightly:

[2022-04-18T15:29:01.656Z] [gw4] [ 64%] FAILED testcases/test_search_20.py::TestCollectionSearch::test_search_load_flush_load[3000-500-128-False-False] 

1 milvus logs: [artifacts-milvus-distributed-kafka-master-476-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/476/artifact/artifacts-milvus-distributed-kafka-master-476-pymilvus-e2e-logs.tar.gz)

2 test case: test_search_load_flush_load

3. collection name: search_collection_P33EXEgH

**Comment by jaime0815** [comment]
there is a known issue #15628, due to the latency of Kafka consumers, it is easy to reproduce relatively.

**Comment by binbinlv** [comment]
Search timeout in the following nighlty:
https://ci.milvus.io:18080/jenkins/blue/rest/organizations/jenkins/pipelines/milvus-nightly-ci/branches/master/runs/497/nodes/64/steps/178/log/?start=0

1. milvus log:
2. collection name: search_collection_BSlw69gP
3. FAILED timeline: [2022-04-28T15:51:01.130Z] [gw5] [ 90%] FAILED testcases/test_search_20.py::TestCollectionSearch::test_search_multi_collections[5000-2-128-False-False] 
4. test logs:
```
[2022-04-28T16:07:59.504Z] [2022-04-28 15:50:38 - INFO - ci_test]: insert_data: inserted data into collection search_collection_BSlw69gP (num_entities: 5000) (client_base.py:175)
[2022-04-28T16:07:59.504Z] [2022-04-28 15:50:38 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 20], kwargs: {} (api_request.py:55)
[2022-04-28T16:07:59.504Z] [2022-04-28 15:50:39 - DEBUG - ci_test]: (api_response) : None  (api_request.py:27)
[2022-04-28T16:07:59.504Z] [2022-04-28 15:50:39 - INFO - ci_test]: test_search_multi_collections: searching 10 entities (nq = 2) from collection search_collection_BSlw69gP (test_search_20.py:1980)
[2022-04-28T16:07:59.504Z] [2022-04-28 15:50:39 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.8583880801631779, 0.7057715077949269, 0.06647727938200687, 0.7509128859282145, 0.25967420165362864, 0.042217752084957816, 0.6737579450154418, 0.6429662757319993, 0.33316519848338344, 0.31238744882725555, 0.22813488789988134, 0.43517764639151124, 0.25576062195474747, 0.7464880836356212, 0.314977......, kwargs: {'_async': False} (api_request.py:55)
[2022-04-28T16:07:59.504Z] [2022-04-28 15:50:59 - ERROR - pymilvus.decorators]: grpc RpcError: [_execute_search_requests], <_MultiThreadedRendezvous: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded>, <Time:{'RPC start': '2022-04-28 15:50:39.666658', 'gRPC error': '2022-04-28 15:50:59.667364'}> (decorators.py:81)
[2022-04-28T16:07:59.504Z] [2022-04-28 15:50:59 - ERROR - pymilvus.decorators]: grpc RpcError: [search], <_MultiThreadedRendezvous: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded>, <Time:{'RPC start': '2022-04-28 15:50:39.663265', 'gRPC error': '2022-04-28 15:50:59.667686'}> (decorators.py:81)
[2022-04-28T16:07:59.504Z] [2022-04-28 15:50:59 - ERROR - ci_test]: Traceback (most recent call last):
[2022-04-28T16:07:59.504Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 41, in handler
[2022-04-28T16:07:59.504Z]     return func(self, *args, **kwargs)
[2022-04-28T16:07:59.504Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 82, in handler
[2022-04-28T16:07:59.504Z]     raise e
[2022-04-28T16:07:59.504Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler
[2022-04-28T16:07:59.504Z]     return func(*args, **kwargs)
[2022-04-28T16:07:59.504Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 21, in handler
[2022-04-28T16:07:59.504Z]     return func(self, *args, **kwargs)
[2022-04-28T16:07:59.504Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 481, in search
[2022-04-28T16:07:59.505Z]     return self._execute_search_requests(requests, timeout, **_kwargs)
[2022-04-28T16:07:59.505Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 82, in handler
[2022-04-28T16:07:59.505Z]     raise e
[2022-04-28T16:07:59.505Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler
[2022-04-28T16:07:59.505Z]     return func(*args, **kwargs)
[2022-04-28T16:07:59.505Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 428, in _execute_search_requests
[2022-04-28T16:07:59.505Z]     raise pre_err
[2022-04-28T16:07:59.505Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 416, in _execute_search_requests
[2022-04-28T16:07:59.505Z]     response = ft.result()
[2022-04-28T16:07:59.505Z]   File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 744, in result
[2022-04-28T16:07:59.505Z]     raise self
[2022-04-28T16:07:59.505Z] grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
[2022-04-28T16:07:59.505Z] 	status = StatusCode.DEADLINE_EXCEEDED
[2022-04-28T16:07:59.505Z] 	details = "Deadline Exceeded"
[2022-04-28T16:07:59.505Z] 	debug_error_string = "{"created":"@1651161059.666993863","description":"Error received from peer ipv4:10.201.63.145:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Deadline Exceeded","grpc_status":4}"
[2022-04-28T16:07:59.505Z] >
[2022-04-28T16:07:59.505Z] 
[2022-04-28T16:07:59.505Z] During handling of the above exception, another exception occurred:
[2022-04-28T16:07:59.505Z] 
[2022-04-28T16:07:59.505Z] Traceback (most recent call last):
[2022-04-28T16:07:59.505Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
[2022-04-28T16:07:59.505Z]     res = func(*args, **kwargs)
[2022-04-28T16:07:59.505Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 56, in api_request
[2022-04-28T16:07:59.505Z]     return func(*arg, **kwargs)
[2022-04-28T16:07:59.505Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 673, in search
[2022-04-28T16:07:59.505Z]     partition_names, output_fields, timeout, round_decimal, **kwargs)
[2022-04-28T16:07:59.505Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 49, in handler
[2022-04-28T16:07:59.505Z]     raise MilvusException(Status.UNEXPECTED_ERROR, str(e))
[2022-04-28T16:07:59.505Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
[2022-04-28T16:07:59.505Z] 	status = StatusCode.DEADLINE_EXCEEDED
[2022-04-28T16:07:59.505Z] 	details = "Deadline Exceeded"
[2022-04-28T16:07:59.505Z] 	debug_error_string = "{"created":"@1651161059.666993863","description":"Error received from peer ipv4:10.201.63.145:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Deadline Exceeded","grpc_status":4}"
[2022-04-28T16:07:59.505Z] >)>
[2022-04-28T16:07:59.505Z]  (api_request.py:35)
[2022-04-28T16:07:59.505Z] [2022-04-28 15:50:59 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
[2022-04-28T16:07:59.505Z] 	status = StatusCode.DEADLINE_EXCEEDED
[2022-04-28T16:07:59.505Z] 	details = "Deadline Exceeded"
[2022-04-28T16:07:59.505Z] 	debug_error_string = "{"created":"@1651161059.666993863","description":"Error received from peer ipv4:10.201.63.145:19530","file":"src/core...... 
```

**Comment by binbinlv** [comment]
Search timeout was reproduced in the latest nightly:
1. https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/534/pipeline/
1.1 milvus log:  
[artifacts-milvus-distributed-kafka-master-534-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/534/artifact/artifacts-milvus-distributed-kafka-master-534-pymilvus-e2e-logs.tar.gz)
1.2 collection name: search_collection_JW8Dpiml
1.3  Failed timeline: 
[2022-05-16T19:46:23.654Z] [gw1] [ 78%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_multi_collections[3000-2-8-True-True] 


2. https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/533/pipeline
2.1 milvus log:
[artifacts-milvus-distributed-kafka-master-533-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/533/artifact/artifacts-milvus-distributed-kafka-master-533-pymilvus-e2e-logs.tar.gz)
2.2 collection name: e2e__HkIHup5h
2.3 Failed timeline:
[2022-05-16T15:09:26.331Z] [gw5] [ 21%] FAILED testcases/test_e2e.py::TestE2e::test_milvus_default

**Comment by jaime0815** [comment]
> Search timeout was reproduced in the latest nightly:
> 
> 1. https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/534/pipeline/
>    1.1 milvus log:
>    [artifacts-milvus-distributed-kafka-master-534-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/534/artifact/artifacts-milvus-distributed-kafka-master-534-pymilvus-e2e-logs.tar.gz)
>    1.2 collection name: search_collection_JW8Dpiml
>    1.3  Failed timeline:
>    [2022-05-16T19:46:23.654Z] [gw1] [ 78%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_multi_collections[3000-2-8-True-True]
> 2. https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/533/pipeline
>    2.1 milvus log:
>    [artifacts-milvus-distributed-kafka-master-533-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/533/artifact/artifacts-milvus-distributed-kafka-master-533-pymilvus-e2e-logs.tar.gz)
>    2.2 collection name: e2e__HkIHup5h
>    2.3 Failed timeline:
>    [2022-05-16T15:09:26.331Z] [gw5] [ 21%] FAILED testcases/test_e2e.py::TestE2e::test_milvus_default

nightly 533: panic because of DropVirtualChannel failed 
```
[2022/05/16 15:04:16.035 +00:00] [WARN] [flush_manager.go:696] ["failed to DropVirtualChannel"] [channel=by-dev-rootcoord-dml_94_433248867774103553v0] [error="All attempts results:\nattempt #1:data service DropVirtualCha
nnel failed, reason = channel by-dev-rootcoord-dml_94_433248867774103553v0 is not watched on node 12\nattempt #2:data service DropVirtualChannel failed, reason = channel by-dev-rootcoord-dml_94_433248867774103553v0 is no
t watched on node 12\nattempt #3:data service DropVirtualChannel failed, reason = channel by-dev-rootcoord-dml_94_433248867774103553v0 is not watched on node 12\nattempt #4:data service DropVirtualChannel failed, reason
= channel by-dev-rootcoord-dml_94_433248867774103553v0 is not watched on node 12\nattempt #5:data service DropVirtualChannel failed, reason = channel by-dev-rootcoord-dml_94_433248867774103553v0 is not watched on node 12
\nattempt #6:data service DropVirtualChannel failed, reason = channel by-dev-rootcoord-dml_94_433248867774103553v0 is not watched on node 12\nattempt #7:data service DropVirtualChannel failed, reason = channel by-dev-roo
tcoord-dml_94_433248867774103553v0 is not watched on node 12\nattempt #8:data service DropVirtualChannel failed, reason = channel by-dev-rootcoord-dml_94_433248867774103553v0 is not watched on node 12\nattempt #9:data se
rvice DropVirtualChannel failed, reason = channel by-dev-rootcoord-dml_94_433248867774103553v0 is not watched on node 12\nattempt #10:data service DropVirtualChannel failed, reason = channel by-dev-rootcoord-dml_94_433248867774103553v0 is not watched on node 12\n"]

[2022/05/16 15:04:16.035 +00:00] [INFO] [flow_graph_dd_node.go:319] ["ddNode add unflushed segment"] [collectionID=433248916165885954] ["No. Segment"=0]

panic: All attempts results:

attempt #1:data service DropVirtualChannel failed, reason = channel by-dev-rootcoord-dml_94_433248867774103553v0 is not watched on node 12

attempt #2:data service DropVirtualChannel failed, reason = channel by-dev-rootcoord-dml_94_433248867774103553v0 is not watched on node 12

attempt #3:data service DropVirtualChannel failed, reason = channel by-dev-rootcoord-dml_94_433248867774103553v0 is not watched on node 12

attempt #4:data service DropVirtualChannel failed, reason = channel by-dev-rootcoord-dml_94_433248867774103553v0 is not watched on node 12

attempt #5:data service DropVirtualChannel failed, reason = channel by-dev-rootcoord-dml_94_433248867774103553v0 is not watched on node 12

attempt #6:data service DropVirtualChannel failed, reason = channel by-dev-rootcoord-dml_94_433248867774103553v0 is not watched on node 12

attempt #7:data service DropVirtualChannel failed, reason = channel by-dev-rootcoord-dml_94_433248867774103553v0 is not watched on node 12

attempt #8:data service DropVirtualChannel failed, reason = channel by-dev-rootcoord-dml_94_433248867774103553v0 is not watched on node 12

attempt #9:data service DropVirtualChannel failed, reason = channel by-dev-rootcoord-dml_94_433248867774103553v0 is not watched on node 12

attempt #10:data service DropVirtualChannel failed, reason = channel by-dev-rootcoord-dml_94_433248867774103553v0 is not watched on node 12





goroutine 4241 [running]:

github.com/milvus-io/milvus/internal/datanode.dropVirtualChannelFunc.func1(0x0, 0x0, 0x0)

        /go/src/github.com/milvus-io/milvus/internal/datanode/flush_manager.go:697 +0x10bf

github.com/milvus-io/milvus/internal/datanode.(*rendezvousFlushManager).startDropping.func1(0xc002b100b0)

        /go/src/github.com/milvus-io/milvus/internal/datanode/flush_manager.go:526 +0x1cb

created by github.com/milvus-io/milvus/internal/datanode.(*rendezvousFlushManager).startDropping

        /go/src/github.com/milvus-io/milvus/internal/datanode/flush_manager.go:510 +0x7e
```

**Comment by binbinlv** [comment]
@jaime0815  Could you help to confirm whether it is the same root cause for the latest nightly:

https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/535/pipeline

Failed cases:
FAILED testcases/test_search.py::TestCollectionSearch::test_search_multi_collections[5000-2-128-True-False]
FAILED testcases/test_search.py::TestCollectionSearch::test_search_multi_collections[3000-2-8-True-True]
FAILED testcases/test_search.py::TestCollectionSearch::test_search_multi_collections[3000-500-128-True-True]

Take the first failed cases for an example:

(1) milvus log:
[artifacts-milvus-distributed-kafka-master-535-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/535/artifact/artifacts-milvus-distributed-kafka-master-535-pymilvus-e2e-logs.tar.gz)

(2) collection name:  search_collection_gI2bFL6k

(3) FAILED timeline:
[2022-05-17T15:40:58.344Z] [gw3] [ 76%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_multi_collections[5000-2-128-True-False]

**Comment by binbinlv** [comment]
Set this issue as critical urgent for reproduction in every nightly tests (only kafka pipeline)

**Comment by jaime0815** [comment]
> @jaime0815 Could you help to confirm whether it is the same root cause for the latest nightly:
> 
> https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/535/pipeline
> 
> Failed cases: FAILED testcases/test_search.py::TestCollectionSearch::test_search_multi_collections[5000-2-128-True-False] FAILED testcases/test_search.py::TestCollectionSearch::test_search_multi_collections[3000-2-8-True-True] FAILED testcases/test_search.py::TestCollectionSearch::test_search_multi_collections[3000-500-128-True-True]
> 
> Take the first failed cases for an example:
> 
> (1) milvus log: [artifacts-milvus-distributed-kafka-master-535-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/535/artifact/artifacts-milvus-distributed-kafka-master-535-pymilvus-e2e-logs.tar.gz)
> 
> (2) collection name: search_collection_gI2bFL6k
> 
> (3) FAILED timeline: [2022-05-17T15:40:58.344Z] [gw3] [ 76%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_multi_collections[5000-2-128-True-False]

all failed cases search timeout

**Comment by binbinlv** [comment]
Similar issue in the latest nightly:

Three Failed cases：
（1）
[2022-05-19T19:47:18.429Z] [gw4] [ 77%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_index_partitions_fuzzy[3000-500-128-True-False-partition_names1] 

（2） 
[2022-05-19T19:47:20.586Z] [gw5] [ 77%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_with_consistency_session[500-8-False-True] 
（3）
[2022-05-19T19:47:21.959Z] [gw2] [ 77%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_with_output_fields[3000-500-8-True-False] 

Take the first failed cases as an example:
(1) milvus logs:
[artifacts-milvus-distributed-kafka-master-540-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/540/artifact/artifacts-milvus-distributed-kafka-master-540-pymilvus-e2e-logs.tar.gz)

(2)  collection name: search_collection_GBWT9HQC
(3) FAILED timeline:
[2022-05-19T19:47:18.429Z]

**Comment by jaime0815** [comment]
> > @jaime0815 Could you help to confirm whether it is the same root cause for the latest nightly:
> > https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/535/pipeline
> > Failed cases: FAILED testcases/test_search.py::TestCollectionSearch::test_search_multi_collections[5000-2-128-True-False] FAILED testcases/test_search.py::TestCollectionSearch::test_search_multi_collections[3000-2-8-True-True] FAILED testcases/test_search.py::TestCollectionSearch::test_search_multi_collections[3000-500-128-True-True]
> > Take the first failed cases for an example:
> > (1) milvus log: [artifacts-milvus-distributed-kafka-master-535-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/535/artifact/artifacts-milvus-distributed-kafka-master-535-pymilvus-e2e-logs.tar.gz)
> > (2) collection name: search_collection_gI2bFL6k
> > (3) FAILED timeline: [2022-05-17T15:40:58.344Z] [gw3] [ 76%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_multi_collections[5000-2-128-True-False]
> 
> all failed cases search timeout

wait service time avaliable timeout 
```
[2022/05/18 15
:43:52.433 +00:00] [WARN] [query_shard.go:256] ["waitUntilServiceable timeout"] ["serviceable ts"=433294700325109761] ["guarantee ts"=433294832406102019] [
channel=by-dev-rootcoord-dml_124_433294831383740417v1]
[2022/05/18 15
:43:52.433 +00:00] [WARN] [impl.go:595] ["QueryService failed to search"] [vchannel=by-dev-rootcoord-dml_124_433294831383740417v1] [segmentIDs="[4332948314
09954817]"] [error="context canceled"]
```

there is a big gap between service ts and guarantee ts 
```
15:43:31.858 +00:00] [DEBUG] [flow_graph_service_time_node.go:72] ["update tSafe:"] [collectionID=433294831383740417] [tSafe=433294206497980418] [tSafe_p=2022/05/18 15:03:44.739 +00:00] [channel=by-dev-rootcoord-delta_123_433294831383740417v0]
```

**Comment by jaime0815** [comment]
#17147 also may cause hang.
