### ISSUE TITLE
[Bug]: DataCoord ut failed

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#16528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others: 

/assign
```

### Current Behavior

```
2022-04-18T11:35:24.0700541Z [2022/04/18 11:35:24.069 +00:00] [DEBUG] [channel_checker.go:96] ["timer started"] ["watch state"=ToRelease] [nodeID=119] ["channel name"=channel1] ["timeout time"=2022/04/18 11:35:44.068 +00:00]
2022-04-18T11:35:25.0733185Z [2022/04/18 11:35:25.072 +00:00] [INFO] [channel_manager.go:677] ["watch etcd loop quit"]
2022-04-18T11:35:25.0776292Z     channel_manager_test.go:43: 
2022-04-18T11:35:25.0776946Z         	Error Trace:	channel_manager_test.go:43
2022-04-18T11:35:25.0777556Z         	            				channel_manager_test.go:273
2022-04-18T11:35:25.0778170Z         	Error:      	Received unexpected error:
2022-04-18T11:35:25.0779011Z         	            	there is no value on key = /etcd/test/root/TestChannelManager_StateTransfer/channelwatch/121/channel1
2022-04-18T11:35:25.0780669Z         	Test:       	TestChannelManager_StateTransfer/toRelease-ReleaseFail-CleanUpAndDelete-Reassign-ToWatch
2022-04-18T11:35:25.0792563Z     channel_manager_test.go:47: 
2022-04-18T11:35:25.0793205Z         	Error Trace:	channel_manager_test.go:47
2022-04-18T11:35:25.0793817Z         	            				channel_manager_test.go:273
2022-04-18T11:35:25.0794426Z         	Error:      	Received unexpected error:
2022-04-18T11:35:25.0797480Z         	            	invalid event: ChannelWatchInfo with nil VChannelInfo, key: fakeKey
2022-04-18T11:35:25.0799353Z         	Test:       	TestChannelManager_StateTransfer/toRelease-ReleaseFail-CleanUpAndDelete-Reassign-ToWatch
2022-04-18T11:35:25.0800086Z     channel_manager_test.go:48: 
2022-04-18T11:35:25.0800436Z         	Error Trace:	channel_manager_test.go:48
2022-04-18T11:35:25.0801063Z         	            				channel_manager_test.go:273
2022-04-18T11:35:25.0801387Z         	Error:      	Not equal: 
2022-04-18T11:35:25.0801680Z         	            	expected: 0
2022-04-18T11:35:25.0801953Z         	            	actual  : 2
2022-04-18T11:35:25.0802643Z         	Test:       	TestChannelManager_StateTransfer/toRelease-ReleaseFail-CleanUpAndDelete-Reassign-ToWatch
2022-04-18T11:35:25.0803328Z --- FAIL: TestChannelManager_StateTransfer (5.13s)
2022-04-18T11:35:25.0803937Z     --- PASS: TestChannelManager_StateTransfer/toWatch-WatchSuccess (1.01s)
2022-04-18T11:35:25.0804608Z     --- PASS: TestChannelManager_StateTransfer/ToWatch-WatchFail-ToRelease (1.01s)
2022-04-18T11:35:25.0805231Z     --- PASS: TestChannelManager_StateTransfer/ToWatch-Timeout (1.01s)
2022-04-18T11:35:25.0805976Z     --- PASS: TestChannelManager_StateTransfer/toRelease-ReleaseSuccess-Delete-reassign-ToWatch (1.01s)
2022-04-18T11:35:25.0806874Z     --- FAIL: TestChannelManager_StateTransfer/toRelease-ReleaseFail-CleanUpAndDelete-Reassign-ToWatch (1.07s)
2022-04-18T11:35:25.0831751Z panic: runtime error: invalid memory address or nil pointer dereference [recovered]
2022-04-18T11:35:25.0832284Z 	panic: runtime error: invalid memory address or nil pointer dereference
2022-04-18T11:35:25.0832763Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x25c50ea]
2022-04-18T11:35:25.0833020Z 
2022-04-18T11:35:25.0833145Z goroutine 180 [running]:
2022-04-18T11:35:25.0833486Z testing.tRunner.func1.2(0x3e34c20, 0x5712550)
2022-04-18T11:35:25.0833861Z 	/usr/local/go/src/testing/testing.go:1143 +0x49f
2022-04-18T11:35:25.0834209Z testing.tRunner.func1(0xc000886180)
2022-04-18T11:35:25.0834573Z 	/usr/local/go/src/testing/testing.go:1146 +0x695
2022-04-18T11:35:25.0834894Z panic(0x3e34c20, 0x5712550)
2022-04-18T11:35:25.0835226Z 	/usr/local/go/src/runtime/panic.go:971 +0x499
2022-04-18T11:35:25.0836036Z github.com/milvus-io/milvus/internal/datacoord.checkWatchInfoWithState(0xc000886180, 0x4545b28, 0xc0000c9878, 0x2, 0x79, 0x4089873, 0x8, 0x9)
2022-04-18T11:35:25.0836759Z 	/go/src/github.com/milvus-io/milvus/internal/datacoord/channel_manager_test.go:49 +0x32a
2022-04-18T11:35:25.0837465Z github.com/milvus-io/milvus/internal/datacoord.TestChannelManager_StateTransfer.func7(0xc000886180)
2022-04-18T11:35:25.0838567Z 	/go/src/github.com/milvus-io/milvus/internal/datacoord/channel_manager_test.go:273 +0xa95
2022-04-18T11:35:25.0839011Z testing.tRunner(0xc000886180, 0xc000528460)
2022-04-18T11:35:25.0839369Z 	/usr/local/go/src/testing/testing.go:1193 +0x203
2022-04-18T11:35:25.0839699Z created by testing.(*T).Run
2022-04-18T11:35:25.0840044Z 	/usr/local/go/src/testing/testing.go:1238 +0x5d8
2022-04-18T11:35:25.0883541Z FAIL	github.com/milvus-io/milvus/internal/datacoord	5.377s
```

**Comment by XuanYang-cn** [comment]
Already marked a TODO:

```
  263         // TODO: cancel could arrive earlier than etcd action watch channel
  264         // if etcd has poor response latency.
  265         time.Sleep(time.Second)
  266         cancel()
  267         wg.Wait()
  268
  269         w, err := metakv.Load(path.Join(prefix, strconv.FormatInt(nodeID, 10)))
  270         assert.Error(t, err)
  271         assert.Empty(t, w)
  272         
  273         checkWatchInfoWithState(t, metakv, datapb.ChannelWatchState_ToWatch, oldNode, channel1, collectionID)
```

Shouldn't be a problem shortly

**Comment by XuanYang-cn** [comment]
Closing this issue
