### ISSUE TITLE
[Bug]:[chaos][querynode] Search failed with error message `no shard leaders available for channel`

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#16562]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220420-6f75d02c
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.1.0.dev26
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

After Milvus recovery from querynode pod kill chaos, search raise error when running `hello_milvus.py`

```
Search...
Traceback (most recent call last):
  File "chaos/scripts/hello_milvus.py", line 114, in <module>
    hello_milvus(args.host)
  File "chaos/scripts/hello_milvus.py", line 87, in hello_milvus
    res = collection.search(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 673, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line [41](https://github.com/milvus-io/milvus/runs/6100530471?check_suite_focus=true#step:14:41), in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 21, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 480, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line [42](https://github.com/milvus-io/milvus/runs/6100530471?check_suite_focus=true#step:14:42)7, in _execute_search_requests
    raise pre_err
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 418, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=no shard leaders available for channel: by-dev-rootcoord-dml_0_[43](https://github.com/milvus-io/milvus/runs/6100530471?check_suite_focus=true#step:14:43)2663[48](https://github.com/milvus-io/milvus/runs/6100530471?check_suite_focus=true#step:14:48)6[50](https://github.com/milvus-io/milvus/runs/6100530471?check_suite_focus=true#step:14:50)56187[53](https://github.com/milvus-io/milvus/runs/6100530471?check_suite_focus=true#step:14:53)v0, leaders: [1], err: Invalid shard leader)>
```

### Expected Behavior

all test cases pass

### Steps To Reproduce

```markdown
see https://github.com/milvus-io/milvus/runs/6100530471?check_suite_focus=true
```

### Anything else?

failed job：https://github.com/milvus-io/milvus/runs/6100530471?check_suite_focus=true
log： https://github.com/milvus-io/milvus/suites/6194816081/artifacts/218327089

**Comment by yanliang567** [comment]
@congqixia could you please help to take a look at this issue?
/assign @congqixia 
/unassign

**Comment by binbinlv** [comment]
Same error in the following nightly:
https://ci.milvus.io:18080/jenkins/blue/rest/organizations/jenkins/pipelines/milvus-nightly-ci/branches/master/runs/480/nodes/64/steps/178/log/?start=0

1. milvus log:
[artifacts-milvus-distributed-kafka-master-480-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/480/artifact/artifacts-milvus-distributed-kafka-master-480-pymilvus-e2e-logs.tar.gz)

2. collection name: search_collection_rPp8cWc8
3. Failed timeline:
 [2022-04-20T15:24:55.428Z] [gw4] [ 57%] FAILED testcases/test_search_20.py::TestCollectionSearch::test_search_collection_after_release_load[3000-2-8-True-False] 

4. Test logs:
```
[2022-04-20T16:14:05.715Z] [2022-04-20 15:24:53 - INFO - ci_test]: test_search_collection_after_release_load: searching after load (test_search_20.py:1083)
[2022-04-20T16:14:05.715Z] [2022-04-20 15:24:53 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.47381934538689907, 0.6808527158885336, 0.4132508704226502, 0.17378822877004796, 0.13772158888950903, 0.3259052076372819, 0.8017614096081976, 0.9553867581920656], [0.5321185894441587, 0.49930338339869296, 0.3913632425613697, 0.644775691291042, 0.47604794787395677, 0.7325442680677597, 0.066969729......, kwargs: {'_async': False, 'travel_timestamp': 432660358535053317} (api_request.py:55)
[2022-04-20T16:14:05.715Z] [2022-04-20 15:24:53 - ERROR - pymilvus.decorators]: RPC error: [_execute_search_requests], <MilvusException: (code=1, message=no shard leaders available for channel: by-dev-rootcoord-dml_175_432660358456410113v1, leaders: [9], err: fail to Search, QueryNode ID=9, reason=Search 9 failed, reason cannot find segment 432660358509363202 in QueryNode err %!w(<nil>))>, <Time:{'RPC start': '2022-04-20 15:24:53.522001', 'RPC error': '2022-04-20 15:24:53.859847'}> (decorators.py:73)
[2022-04-20T16:14:05.715Z] [2022-04-20 15:24:53 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=no shard leaders available for channel: by-dev-rootcoord-dml_175_432660358456410113v1, leaders: [9], err: fail to Search, QueryNode ID=9, reason=Search 9 failed, reason cannot find segment 432660358509363202 in QueryNode err %!w(<nil>))>, <Time:{'RPC start': '2022-04-20 15:24:53.517725', 'RPC error': '2022-04-20 15:24:53.860471'}> (decorators.py:73)
[2022-04-20T16:14:05.715Z] [2022-04-20 15:24:53 - ERROR - ci_test]: Traceback (most recent call last):
[2022-04-20T16:14:05.715Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
[2022-04-20T16:14:05.715Z]     res = func(*args, **kwargs)
[2022-04-20T16:14:05.715Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 56, in api_request
[2022-04-20T16:14:05.715Z]     return func(*arg, **kwargs)
[2022-04-20T16:14:05.715Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 674, in search
[2022-04-20T16:14:05.715Z]     partition_names, output_fields, timeout, round_decimal, **kwargs)
[2022-04-20T16:14:05.715Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 56, in handler
[2022-04-20T16:14:05.715Z]     raise e
[2022-04-20T16:14:05.715Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 41, in handler
[2022-04-20T16:14:05.715Z]     return func(self, *args, **kwargs)
[2022-04-20T16:14:05.715Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler
[2022-04-20T16:14:05.715Z]     raise e
[2022-04-20T16:14:05.715Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler
[2022-04-20T16:14:05.715Z]     return func(*args, **kwargs)
[2022-04-20T16:14:05.715Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 21, in handler
[2022-04-20T16:14:05.715Z]     return func(self, *args, **kwargs)
[2022-04-20T16:14:05.715Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 480, in search
[2022-04-20T16:14:05.715Z]     return self._execute_search_requests(requests, timeout, **_kwargs)
[2022-04-20T16:14:05.715Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler
[2022-04-20T16:14:05.715Z]     raise e
[2022-04-20T16:14:05.715Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler
[2022-04-20T16:14:05.715Z]     return func(*args, **kwargs)
[2022-04-20T16:14:05.715Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 427, in _execute_search_requests
[2022-04-20T16:14:05.715Z]     raise pre_err
[2022-04-20T16:14:05.715Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 418, in _execute_search_requests
[2022-04-20T16:14:05.715Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2022-04-20T16:14:05.715Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=no shard leaders available for channel: by-dev-rootcoord-dml_175_432660358456410113v1, leaders: [9], err: fail to Search, QueryNode ID=9, reason=Search 9 failed, reason cannot find segment 432660358509363202 in QueryNode err %!w(<nil>))>
[2022-04-20T16:14:05.716Z]  (api_request.py:35)
```

**Comment by ThreadDao** [comment]
1. Test case:
```Python
    @pytest.mark.tags(CaseLabel.L3)
    def test_load_replica_change(self):
        """
        target: test load replica change
        method: 1.load with replica 1
                2.load with a new replica number
                3.release collection
                4.load with a new replica
        expected: The second time successfully loaded with a new replica number
        """
        # create, insert
        collection_w = self.init_collection_wrap(cf.gen_unique_str(prefix))
        df = cf.gen_default_dataframe_data()
        insert_res, _ = collection_w.insert(df)
        assert collection_w.num_entities == ct.default_nb

        collection_w.load(replica_number=1)
        collection_w.query(expr=f"{ct.default_int64_field_name} in [0]")
        collection_w.load(replica_number=2)
        collection_w.get_replicas()

        collection_w.release()
        collection_w.load(replica_number=2)
        collection_w.query(expr=f"{ct.default_int64_field_name} in [0]")
```
2. Case runing result:
```
name>: collection_5OpNL3Ce
<partitions>: [{"name": "_default", "collection_name": "collection_5OpNL3Ce", "description": ""}]
<description>: 
<schema>: {
  auto_id: False
  description: 
  fields: [{
    name: int64
    description: 
    type: 5
    is_primary: True
    a......  (api_request.py:27)
[2022-04-24 16:21:25,630 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [      int64   float                                       float_vector
0         0     0.0  [0.007436856784492043, 0.09394764771862305, 0....
1         1     1.0  [0.01739919203371784, 0.12882032073533647, 0.1...
2         2     2.0  [0.06114443129401205, 0.11334566764309541, 0.0...
3         3    ......, kwargs: {'timeout': 20} (api_request.py:55)
[2022-04-24 16:21:26,170 - DEBUG - ci_test]: (api_response) : (insert count: 3000, delete count: 0, upsert count: 0, timestamp: 432744296864546818)  (api_request.py:27)
[2022-04-24 16:21:29,331 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 20], kwargs: {} (api_request.py:55)
[2022-04-24 16:21:30,485 - DEBUG - ci_test]: (api_response) : None  (api_request.py:27)
[2022-04-24 16:21:30,485 - DEBUG - ci_test]: (api_request)  : [Collection.query] args: ['int64 in [0]', None, None, 20], kwargs: {} (api_request.py:55)
[2022-04-24 16:21:30,810 - DEBUG - ci_test]: (api_response) : [{'int64': 0}]  (api_request.py:27)
[2022-04-24 16:21:30,810 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 2, 20], kwargs: {} (api_request.py:55)
[2022-04-24 16:21:30,839 - DEBUG - ci_test]: (api_response) : None  (api_request.py:27)
[2022-04-24 16:21:30,840 - DEBUG - ci_test]: (api_request)  : [Collection.get_replicas] args: [20], kwargs: {} (api_request.py:55)
[2022-04-24 16:21:30,864 - DEBUG - ci_test]: (api_response) : Replica groups:
- Group: <group_id:432742929234133176>, <group_nodes:(9, 10)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_34_432744296733736961v0>, <shard_leader:10>, <shard_nodes:[9]>, Shard: <channel_name:by-dev-rootcoord-dml_35_432744296733736961v1>, <shard_leader:11>, <shard_nodes:[10]>]......  (api_request.py:27)
[2022-04-24 16:21:30,864 - DEBUG - ci_test]: (api_request)  : [Collection.release] args: [], kwargs: {'timeout': 20} (api_request.py:55)
[2022-04-24 16:21:32,086 - DEBUG - ci_test]: (api_response) : None  (api_request.py:27)
[2022-04-24 16:21:32,086 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 2, 20], kwargs: {} (api_request.py:55)
[2022-04-24 16:21:33,260 - DEBUG - ci_test]: (api_response) : None  (api_request.py:27)
[2022-04-24 16:21:33,260 - DEBUG - ci_test]: (api_request)  : [Collection.query] args: ['int64 in [0]', None, None, 20], kwargs: {} (api_request.py:55)
[2022-04-24 16:21:33,293 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/nausicca/projects/milvus/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
    res = func(*args, **kwargs)
  File "/Users/nausicca/projects/milvus/tests/python_client/utils/api_request.py", line 56, in api_request
    return func(*arg, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 752, in query
    res = conn.query(self._name, expr, output_fields, partition_names, timeout, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 1002, in query
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=no shard leaders available for channel: by-dev-rootcoord-dml_35_432744296733736961v1, leaders: [11], err: fail to Query, QueryNode ID = 11, reason=collection hasn't been loaded or has been released, collection id = 432744296733736961)>
 (api_request.py:35)
[2022-04-24 16:21:33,293 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=no shard leaders available for channel: by-dev-rootcoord-dml_35_432744296733736961v1, leaders: [11], err: fail to Query, QueryNode ID = 11, reason=collection hasn't been loaded or has been released, collection id = 432744296733736961)> (api_request.py:36)
FAILED
```
3. Server log
[milvus_logs.tar.gz](https://github.com/milvus-io/milvus/files/8549339/milvus_logs.tar.gz)

**Comment by congqixia** [comment]
I think #16620 shall fix this problem

**Comment by congqixia** [comment]
@zhuwenxing @binbinlv @ThreadDao there 3 error has different error message and are not the same problem. #16620 shall fix segment not found problem, which was @binbinlv 's issue.

**Comment by ThreadDao** [comment]
@congqixia Please ignore my comment. I have logged my problem on a new issue #16641

**Comment by zhuwenxing** [comment]
This issue is not reproduced with version `master-20220427-0a953948` temporary.
