### ISSUE TITLE
[Bug]: [nightly] Calculate distance failed reporting "failed to fetch vectors"

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#16565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: latest
- Deployment mode(standalone or cluster): pulsar cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.1.0.dev26 
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Calculate distance failed reporting "failed to fetch vectors"

### Expected Behavior

Calculate distance successfully without any errors

### Steps To Reproduce

Running nightly:
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/480/pipeline/190

1. milvus logs:
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/480/artifacts
artifacts-milvus-distributed-pulsar-master-480-pymilvus-e2e-logs.tar.gz

2. collection name: utility_EJBXObJ8

3. Failed timeline:
[2022-04-20T15:57:48.978Z] [gw4] [ 98%] FAILED testcases/test_utility.py::TestUtilityBase::test_calc_distance_right_vectors_and_partition_ids[metric_type-L2-False] 

4. test logs:
```
[2022-04-20T16:15:20.403Z] [2022-04-20 15:57:47 - DEBUG - ci_test]: (api_request)  : [calc_distance] args: [{'ids': [0, 1, 2, 3, 4], 'collection': 'utility_EJBXObJ8', 'partition': '_default', 'field': 'float_vector'}, {'float_vectors': [[0.10299987616484915, 0.13604863730436437, 0.1509957630509533, 0.004591556899407486, 0.03838861188826867, 0.1305562530617854, 0.027503442880233795, 0.03138685897962961, 0......, kwargs: {} (api_request.py:55)

[2022-04-20T16:15:20.403Z] [2022-04-20 15:57:47 - ERROR - pymilvus.decorators]: RPC error: [calc_distance], <MilvusException: (code=1, message=failed to fetch vectors)>, <Time:{'RPC start': '2022-04-20 15:57:47.216883', 'RPC error': '2022-04-20 15:57:47.445551'}> (decorators.py:73)

[2022-04-20T16:15:20.403Z] [2022-04-20 15:57:47 - ERROR - ci_test]: Traceback (most recent call last):

[2022-04-20T16:15:20.403Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper

[2022-04-20T16:15:20.403Z]     res = func(*args, **kwargs)

[2022-04-20T16:15:20.403Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 56, in api_request

[2022-04-20T16:15:20.403Z]     return func(*arg, **kwargs)

[2022-04-20T16:15:20.403Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/utility.py", line 489, in calc_distance

[2022-04-20T16:15:20.403Z]     res = _get_connection(using).calc_distance(vectors_left, vectors_right, params, timeout)

[2022-04-20T16:15:20.403Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 56, in handler

[2022-04-20T16:15:20.403Z]     raise e

[2022-04-20T16:15:20.403Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 41, in handler

[2022-04-20T16:15:20.403Z]     return func(self, *args, **kwargs)

[2022-04-20T16:15:20.404Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler

[2022-04-20T16:15:20.404Z]     raise e

[2022-04-20T16:15:20.404Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler

[2022-04-20T16:15:20.404Z]     return func(*args, **kwargs)

[2022-04-20T16:15:20.404Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 1089, in calc_distance

[2022-04-20T16:15:20.404Z]     raise MilvusException(status.error_code, status.reason)

[2022-04-20T16:15:20.404Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=failed to fetch vectors)>
```

**Comment by binbinlv** [comment]
Same issue occurs in the following nightly:
https://ci.milvus.io:18080/jenkins/blue/rest/organizations/jenkins/pipelines/milvus-nightly-ci/branches/master/runs/482/nodes/129/steps/178/log/?start=0


1. milvus logs:
[artifacts-milvus-distributed-pulsar-master-482-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/482/artifact/artifacts-milvus-distributed-pulsar-master-482-pymilvus-e2e-logs.tar.gz)

2. collection name: utility_UnP3dOr2

3. Failed timeline:
[2022-04-21T15:49:40.869Z] [gw3] [ 97%] FAILED testcases/test_utility.py::TestUtilityBase::test_calc_distance_from_partitions[metric-IP-True] 

4. test logs:
```
[2022-04-21T16:09:14.369Z] [2022-04-21 15:49:38 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None], kwargs: {'timeout': 20} (api_request.py:55)
[2022-04-21T16:09:14.369Z] [2022-04-21 15:49:38 - DEBUG - ci_test]: (api_response) : None  (api_request.py:27)
[2022-04-21T16:09:14.369Z] [2022-04-21 15:49:38 - INFO - ci_test]: Extract entities from two partitions for distance calculating (test_utility.py:1218)
[2022-04-21T16:09:14.369Z] [2022-04-21 15:49:38 - INFO - ci_test]: Calculate distance between entities from two partitions (test_utility.py:1223)
[2022-04-21T16:09:14.369Z] [2022-04-21 15:49:38 - DEBUG - ci_test]: (api_request)  : [calc_distance] args: [{'ids': [0, 1, 2, 3, 4], 'collection': 'utility_UnP3dOr2', 'partition': '_default', 'field': 'float_vector'}, {'ids': [5, 6, 7, 8, 9], 'collection': 'utility_UnP3dOr2', 'partition': 'search_partition_0', 'field': 'float_vector'}, {'metric': 'IP', 'sqrt': True}, 20, 'default'], kwargs: {} (api_request.py:55)
[2022-04-21T16:09:14.369Z] [2022-04-21 15:49:39 - ERROR - pymilvus.decorators]: RPC error: [calc_distance], <MilvusException: (code=1, message=failed to fetch vectors)>, <Time:{'RPC start': '2022-04-21 15:49:38.940360', 'RPC error': '2022-04-21 15:49:39.173460'}> (decorators.py:73)
[2022-04-21T16:09:14.369Z] [2022-04-21 15:49:39 - ERROR - ci_test]: Traceback (most recent call last):
[2022-04-21T16:09:14.369Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
[2022-04-21T16:09:14.369Z]     res = func(*args, **kwargs)
[2022-04-21T16:09:14.369Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 56, in api_request
[2022-04-21T16:09:14.369Z]     return func(*arg, **kwargs)
[2022-04-21T16:09:14.369Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/utility.py", line 489, in calc_distance
[2022-04-21T16:09:14.369Z]     res = _get_connection(using).calc_distance(vectors_left, vectors_right, params, timeout)
[2022-04-21T16:09:14.369Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 56, in handler
[2022-04-21T16:09:14.369Z]     raise e
[2022-04-21T16:09:14.369Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 41, in handler
[2022-04-21T16:09:14.369Z]     return func(self, *args, **kwargs)
[2022-04-21T16:09:14.369Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler
[2022-04-21T16:09:14.370Z]     raise e
[2022-04-21T16:09:14.370Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler
[2022-04-21T16:09:14.370Z]     return func(*args, **kwargs)
[2022-04-21T16:09:14.370Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 1089, in calc_distance
[2022-04-21T16:09:14.370Z]     raise MilvusException(status.error_code, status.reason)
[2022-04-21T16:09:14.370Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=failed to fetch vectors)>
```

5. test cases:
```python
@pytest.mark.tags(CaseLabel.L2)
    def test_calc_distance_from_partitions(self, metric_field, metric, sqrt):
        """
        target: test calculated distance between entities from partitions
        method: calculate distance between entities from two partitions
        expected: distance calculated successfully
        """
        log.info("Create connection")
        self._connect()
        nb = 10
        collection_w, vectors, _, insert_ids, _ = self.init_collection_general(prefix, True, nb, partition_num=1)
        partitions = collection_w.partitions
        middle = len(insert_ids) // 2
        params = {metric_field: metric, "sqrt": sqrt}
        vectors_l = vectors[0].loc[:, default_field_name]
        vectors_r = vectors[1].loc[:, default_field_name]
        log.info("Extract entities from two partitions for distance calculating")
        op_l = {"ids": insert_ids[:middle], "collection": collection_w.name,
                "partition": partitions[0].name, "field": default_field_name}
        op_r = {"ids": insert_ids[middle:], "collection": collection_w.name,
                "partition": partitions[1].name, "field": default_field_name}
        log.info("Calculate distance between entities from two partitions")
        self.utility_wrap.calc_distance(op_l, op_r, params,
                                        check_task=CheckTasks.check_distance,
                                        check_items={"vectors_l": vectors_l,
                                                     "vectors_r": vectors_r,
                                                     "metric": metric,
                                                     "sqrt": sqrt})
```

**Comment by binbinlv** [comment]
Set this issue as critical for reproduction.

**Comment by binbinlv** [comment]
not reproduced very frequently, so cancel critial label.

**Comment by binbinlv** [comment]
Not reproduced for a long time, so close it first and will reopen it if it occurs again.
