### ISSUE TITLE
[Bug]: Rpc timeout when load collection with invalid replica number

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#16576]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220420-6f75d02c
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.1.0.dev29
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others: 

queryNode:
      replicas: 1
  config:
    common:
      retentionDuration: 40
    queryNode:
      gracefulTime: 0
```
```


### Current Behavior

1. test case
```Python
    @pytest.mark.parametrize("replicas", [-1, 0])
    def test_load_replica_invalid_number(self, replicas):
        """
        target: test load partition with invalid replica number
        method: load with invalid replica number
        expected: raise exception
        """
        # create, insert
        collection_w = self.init_collection_wrap(cf.gen_unique_str(prefix))
        df = cf.gen_default_dataframe_data()
        insert_res, _ = collection_w.insert(df)
        assert collection_w.num_entities == ct.default_nb

        # load with non-number replicas
        error = {ct.err_code: 0, ct.err_msg: "xxxx"}
        collection_w.load(replica_number=replicas, check_task=CheckTasks.err_res, check_items=error)
```
2. Case running result:
```
[2022-04-21 16:56:25,990 - DEBUG - ci_test]: (api_request)  : [Collection] args: ['collection_Jbn1luqV', {
  auto_id: False
  description: 
  fields: [{
    name: int64
    description: 
    type: 5
    is_primary: True
    auto_id: False
  }, {
    name: float
    description: 
    type: 10
  }, {
    name: float_vector
    description: 
    type: 101
    params: {'dim': 128}
 ......, kwargs: {'consistency_level': 'Strong'} (api_request.py:55)
[2022-04-21 16:56:26,054 - DEBUG - ci_test]: (api_response) : <Collection>:
-------------
<name>: collection_Jbn1luqV
<partitions>: [{"name": "_default", "collection_name": "collection_Jbn1luqV", "description": ""}]
<description>: 
<schema>: {
  auto_id: False
  description: 
  fields: [{
    name: int64
    description: 
    type: 5
    is_primary: True
    a......  (api_request.py:27)
[2022-04-21 16:56:26,162 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [      int64   float                                       float_vector
0         0     0.0  [0.04928801851613454, 0.14342080527376777, 0.0...
1         1     1.0  [0.09082376455130504, 0.06088637195456612, 0.0...
2         2     2.0  [0.07811885480781058, 0.14118085289176174, 0.0...
3         3    ......, kwargs: {'timeout': 20} (api_request.py:55)
[2022-04-21 16:56:27,423 - DEBUG - ci_test]: (api_response) : (insert count: 3000, delete count: 0, upsert count: 0, timestamp: 432676900005740545)  (api_request.py:27)
[2022-04-21 16:56:30,582 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 20, 0], kwargs: {} (api_request.py:55)
[2022-04-21 16:56:39,634 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 82, in handler
    raise e
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 694, in load_collection
    response = rf.result()
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1650531399.633642000","description":"Error received from peer ipv4:10.98.0.4:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nausicca/projects/milvus/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
    res = func(*args, **kwargs)
  File "/Users/nausicca/projects/milvus/tests/python_client/utils/api_request.py", line 56, in api_request
    return func(*arg, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 435, in load
    conn.load_collection(self._name, timeout=timeout, replica_number=replica_number, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 52, in handler
    raise MilvusException(Status.UNEXPECTED_ERROR, "rpc timeout")
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=rpc timeout)>
 (api_request.py:35)
[2022-04-21 16:56:39,634 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=rpc timeout)> (api_request.py:36)
FAILED
```
3. Proxy log
[proxy.log](https://github.com/milvus-io/milvus/files/8529522/proxy.log)

**Comment by ThreadDao** [comment]
The issue cannot be reproduced in this case. close first
