### ISSUE TITLE
[Bug]: Querycoord panic when get collection replicas

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#16574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220420-6f75d02c
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.1.0.dev28
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others: 

queryNode:
      replicas: 1
  config:
    common:
      retentionDuration: 40
    queryNode:
      gracefulTime: 0
```
```


### Current Behavior

1. test case
```Python
    @pytest.mark.tags(CaseLabel.L2)
    def test_load_replica(self):
        """
        target: test load collection with non-number replicas
        method: load with non-number replicas
        expected: raise exceptions
        """
        # create, insert
        collection_w = self.init_collection_wrap(cf.gen_unique_str(prefix))
        df = cf.gen_default_dataframe_data()
        insert_res, _ = collection_w.insert(df)
        assert collection_w.num_entities == ct.default_nb

        # load with non-number replicas
        collection_w.load(replica_number=None)
        collection_w.query(expr=f"{ct.default_int64_field_name} in [0]")
        collection_w.get_replicas()
```
2. Case run
```
<name>: collection_RzmnS20H
<partitions>: [{"name": "_default", "collection_name": "collection_RzmnS20H", "description": ""}]
<description>: 
<schema>: {
  auto_id: False
  description: 
  fields: [{
    name: int64
    description: 
    type: 5
    is_primary: True
    a......  (api_request.py:27)
[2022-04-21 16:21:55,901 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [      int64   float                                       float_vector
0         0     0.0  [0.09497191198491801, 0.006076621379380047, 0....
1         1     1.0  [0.12788227666651286, 0.07997366536352453, 0.1...
2         2     2.0  [0.03174162182996275, 0.02525229229922144, 0.0...
3         3    ......, kwargs: {'timeout': 20} (api_request.py:55)
[2022-04-21 16:21:56,986 - DEBUG - ci_test]: (api_response) : (insert count: 3000, delete count: 0, upsert count: 0, timestamp: 432676357236588546)  (api_request.py:27)
[2022-04-21 16:22:00,216 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 20, None], kwargs: {} (api_request.py:55)
[2022-04-21 16:22:01,379 - DEBUG - ci_test]: (api_response) : None  (api_request.py:27)
[2022-04-21 16:22:01,380 - DEBUG - ci_test]: (api_request)  : [Collection.query] args: ['int64 in [0]', None, None, 20], kwargs: {} (api_request.py:55)
[2022-04-21 16:22:01,603 - DEBUG - ci_test]: (api_response) : [{'int64': 0}]  (api_request.py:27)
[2022-04-21 16:22:01,604 - DEBUG - ci_test]: (api_request)  : [Collection.get_replicas] args: [20], kwargs: {} (api_request.py:55)
[2022-04-21 16:22:02,667 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 82, in handler
    raise e
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 1185, in get_replicas
    response = future.result()
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "err: rpc error: code = Unavailable desc = error reading from server: EOF
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:258 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall
/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/client/client.go:306 github.com/milvus-io/milvus/internal/distributed/querycoord/client.(*Client).GetReplicas
/go/src/github.com/milvus-io/milvus/internal/proxy/impl.go:3988 github.com/milvus-io/milvus/internal/proxy.(*Proxy).GetReplicas
/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:673 github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).GetReplicas
/go/src/github.com/milvus-io/milvus/internal/proto/milvuspb/milvus.pb.go:7399 github.com/milvus-io/milvus/internal/proto/milvuspb._MilvusService_GetReplicas_Handler.func1
/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/auth/auth.go:47 github.com/grpc-ecosystem/go-grpc-middleware/auth.UnaryServerInterceptor.func1
/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38 github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1
/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
"
	debug_error_string = "{"created":"@1650529322.653098000","description":"Error received from peer ipv4:10.98.0.4:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"err: rpc error: code = Unavailable desc = error reading from server: EOF\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:258 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall\n/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/client/client.go:306 github.com/milvus-io/milvus/internal/distributed/querycoord/client.(*Client).GetReplicas\n/go/src/github.com/milvus-io/milvus/internal/proxy/impl.go:3988 github.com/milvus-io/milvus/internal/proxy.(*Proxy).GetReplicas\n/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:673 github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).GetReplicas\n/go/src/github.com/milvus-io/milvus/internal/proto/milvuspb/milvus.pb.go:7399 github.com/milvus-io/milvus/internal/proto/milvuspb._MilvusService_GetReplicas_Handler.func1\n/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/auth/auth.go:47 github.com/grpc-ecosystem/go-grpc-middleware/auth.UnaryServerInterceptor.func1\n/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38 github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1\n/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n","grpc_status":2}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nausicca/projects/milvus/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
    res = func(*args, **kwargs)
  File "/Users/nausicca/projects/milvus/tests/python_client/utils/api_request.py", line 56, in api_request
    return func(*arg, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 1184, in get_replicas
    return conn.get_replicas(self.name, timeout=timeout, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 47, in handler
    raise MilvusException(Status.UNEXPECTED_ERROR, str(e))
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "err: rpc error: code = Unavailable desc = error reading from server: EOF
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:258 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall
/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/client/client.go:306 github.com/milvus-io/milvus/internal/distributed/querycoord/client.(*Client).GetReplicas
/go/src/github.com/milvus-io/milvus/internal/proxy/impl.go:3988 github.com/milvus-io/milvus/internal/proxy.(*Proxy).GetReplicas
/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:673 github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).GetReplicas
/go/src/github.com/milvus-io/milvus/internal/proto/milvuspb/milvus.pb.go:7399 github.com/milvus-io/milvus/internal/proto/milvuspb._MilvusService_GetReplicas_Handler.func1
/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/auth/auth.go:47 github.com/grpc-ecosystem/go-grpc-middleware/auth.UnaryServerInterceptor.func1
/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38 github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1
/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
"
	debug_error_string = "{"created":"@1650529322.653098000","description":"Error received from peer ipv4:10.98.0.4:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"err: rpc error: code = Unavailable desc = error reading from server: EOF\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:258 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall\n/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/client/client.go:306 github.com/milvus-io/milvus/internal/distributed/querycoord/client.(*Client).GetReplicas\n/go/src/github.com/milvus-io/milvus/internal/proxy/impl.go:3988 github.com/milvus-io/milvus/internal/proxy.(*Proxy).GetReplicas\n/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:673 github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).GetReplicas\n/go/src/github.com/milvus-io/milvus/internal/proto/milvuspb/milvus.pb.go:7399 github.com/milvus-io/milvus/internal/proto/milvuspb._MilvusService_GetReplicas_Handler.func1\n/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/auth/auth.go:47 github.com/grpc-ecosystem/go-grpc-middleware/auth.UnaryServerInterceptor.func1\n/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38 github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1\n/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n","grpc_status":2}"
>)>
 (api_request.py:35)
[2022-04-21 16:22:02,669 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "err: rpc error: code = Unavailable desc = error reading from server: EOF
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io...... (api_request.py:36)
FAILED
```
3. querycoord logs
[querycoord.log](https://github.com/milvus-io/milvus/files/8529280/querycoord.log)
[querycoord3.log](https://github.com/milvus-io/milvus/files/8529282/querycoord3.log)

**Comment by ThreadDao** [comment]
Fixed
