### ISSUE TITLE
[Bug]: [test-string]Insert failed with error "The types of schema and data do not match"

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#16587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:xige-16-segcore-load-string-730dc97bd-20220420
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.1.0.dev29
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
>>> import random
>>> from pymilvus import (
...     connections, list_collections,
...     FieldSchema, CollectionSchema, DataType,
...     Collection, utility
... )
>>> connections.connect(host="10.97.16.58",port="19530")
>>> dim = 8
>>> default_fields = [
...     FieldSchema(name="count", dtype=DataType.INT64, is_primary=True),
...     FieldSchema(name="float", dtype=DataType.FLOAT),
...     FieldSchema(name="str_field", dtype=DataType.VARCHAR, max_length_per_row=2000),
...     FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
... ]
>>> default_schema = CollectionSchema(fields=default_fields, description="test collection")
>>> 
>>> collection = Collection(name="bbbbb", schema=default_schema)
>>> 
>>> # insert data
>>> nb = 500
>>> data = [
...     [i for i in range(nb)],
...     [float(i) for i in range(nb)],
...     [str(random.random()) for _ in range(nb)],
...     [[random.random() for _ in range(dim)] for _ in range(nb)]
... ]
>>> res = collection.insert(data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 511, in insert
    raise SchemaNotReadyException(0, ExceptionsMessage.TypeOfDataAndSchemaInconsistent)
pymilvus.exceptions.SchemaNotReadyException: <SchemaNotReadyException: (code=0, message=The types of schema and data do not match.)>
```

### Expected Behavior

should insert successfully

**Comment by DragonDriver** [comment]
try:
```python
data = [
    [i for i in range(nb)],
    [np.float32(i) for i in range(nb)],
    [str(random.random()) for _ in range(nb)],
    [[random.random() for _ in range(dim)] for _ in range(nb)]
]
```
PyMilvus will infer the data type from insert data, since there is only float type in Python, so PyMilvus will consider the type of floating data as DataType.DOUBLE. Similar to integer type, int will be inferred as DataType.INT64. So you should explicitly use `numpy` or `pandas`.

/assign @jingkl

**Comment by jingkl** [comment]
I still get an error after changing it!
<img width="1418" alt="截屏2022-04-22 15 20 53" src="https://user-images.githubusercontent.com/34296482/164626431-2d93dbfb-f018-472e-9fd2-e73a96310e22.png">
/assign @DragonDriver

**Comment by DragonDriver** [comment]
try `np.float32` instead of `np.float`.

**Comment by jingkl** [comment]
> try `np.float32` instead of `np.float`.

Verified, inserted successfully，I also need to discuss the old and new interfaces

**Comment by jingkl** [comment]
To be discussed in the next version, not relevant to this side of string so turn off
