### ISSUE TITLE
[Bug]: [test-string] The error message for load failure needs to be more standardised

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#16586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Load failure error, this can be changed to collection.name has not been loaded to memory or load failed, which is more in line with the specification

```
[2022-04-21 23:12:01 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=collection 432682805904801793 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-04-21 23:12:00.736267', 'RPC error': '2022-04-21 23:12:01.295755'}> (decorators.py:73)
[2022-04-21 23:12:01 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=collection 432682805904801793 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-04-21 23:12:00.685434', 'RPC error': '2022-04-21 23:12:01.295959'}> (decorators.py:73)
[2022-04-21 23:12:01 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/jingjing/Workspace/milvus_modify/tests/python_client/utils/api_request.py", line 23, in inner_wrapper
    res = func(*args, **kwargs)
  File "/Users/jingjing/Workspace/milvus_modify/tests/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 435, in load
    conn.load_collection(self._name, timeout=timeout, replica_number=replica_number, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 699, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 713, in wait_for_loading_collection
    return self._wait_for_loading_collection(collection_name, timeout)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 742, in _wait_for_loading_collection
    progress = self.get_collection_loading_progress(collection_name, timeout)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 721, in get_collection_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection 432682805904801793 has not been loaded to memory or load failed)>
 (api_request.py:36)
[2022-04-21 23:12:01 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=collection 432682805904801793 has not been loaded to memory or load failed)> (api_request.py:37)
```

**Comment by jingkl** [comment]
pymilvus:2.1.0.dev55
milvus tag: master-20220511-9e6d9fb7
Such issues have been verified to be fixed
