### ISSUE TITLE
[Bug]: [test-string]collection.load() error causes the search to not work properly

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#16589]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:xige-16-segcore-load-string-730dc97bd-20220420
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.1.0.dev29
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

testcase：
```
@pytest.mark.tags(CaseLabel.L0)
    def test_search_normal(self, nq, dim, auto_id):
        """
        target: test search normal case
        method: create connection, collection, insert and search
        expected: 1. search returned with 0 before travel timestamp
                  2. search successfully with limit(topK) after travel timestamp
        """
        # 1. initialize with data
        collection_w, _, _, insert_ids, time_stamp = \
            self.init_collection_general(prefix, True, auto_id=auto_id, dim=dim)[0:5]
        # 2. search before insert time_stamp
        log.info("test_search_normal: searching collection %s" % collection_w.name)
        vectors = [[random.random() for _ in range(dim)] for _ in range(nq)]
        collection_w.search(vectors[:nq], default_search_field,
                            default_search_params, default_limit,
                            default_search_exp,
                            travel_timestamp=time_stamp - 1,
                            check_task=CheckTasks.check_search_results,
                            check_items={"nq": nq,
                                         "ids": [],
                                         "limit": 0})
        # 3. search after insert time_stamp
        collection_w.search(vectors[:nq], default_search_field,
                            default_search_params, default_limit,
                            default_search_exp,
                            travel_timestamp=time_stamp,
                            guarantee_timestamp=0,
                            check_task=CheckTasks.check_search_results,
                            check_items={"nq": nq,
                                         "ids": insert_ids,
                                         "limit": default_limit})
``````

```
def init_collection_general(self, prefix, insert_data=False, nb=ct.default_nb,
                                partition_num=0, is_binary=False, is_all_data_type=False,
                                auto_id=False, dim=ct.default_dim, is_index=False, primary_field=ct.default_int64_field_name):
        """
        target: create specified collections
        method: 1. create collections (binary/non-binary, default/all data type, auto_id or not)
                2. create partitions if specified
                3. insert specified (binary/non-binary, default/all data type) data
                   into each partition if any
                4. not load if specifying is_index as True
        expected: return collection and raw data, insert ids
        """
        log.info("Test case of search interface: initialize before test case")
        self._connect()
        collection_name = cf.gen_unique_str(prefix)
        vectors = []
        binary_raw_vectors = []
        insert_ids = []
        time_stamp = 0
        # 1 create collection
        default_schema = cf.gen_default_collection_schema(auto_id=auto_id, dim=dim, primary_field=primary_field)
        if is_binary:
            default_schema = cf.gen_default_binary_collection_schema(auto_id=auto_id, dim=dim, primary_field=primary_field)
        if is_all_data_type:
            default_schema = cf.gen_collection_schema_all_datatype(auto_id=auto_id, dim=dim, primary_field=primary_field)
        log.info("init_collection_general: collection creation")
        collection_w = self.init_collection_wrap(name=collection_name,
                                                 schema=default_schema)
        # 2 add extra partitions if specified (default is 1 partition named "_default")
        if partition_num > 0:
            cf.gen_partitions(collection_w, partition_num)
        # 3 insert data if specified
        if insert_data:
            collection_w, vectors, binary_raw_vectors, insert_ids, time_stamp = \
                cf.insert_data(collection_w, nb, is_binary, is_all_data_type, auto_id=auto_id, dim=dim)
            assert collection_w.is_empty is False
            assert collection_w.num_entities == nb
            log.info("insert_data: inserted data into collection %s (num_entities: %s)"
                     % (collection_w.name, nb))
            # This condition will be removed after auto index feature
            if not is_index:
                collection_w.load()

        return collection_w, vectors, binary_raw_vectors, insert_ids, time_stamp
```

log；
```
[2022-04-21 23:11:56 - INFO - ci_test]: insert_data: inserting data into collection search_collection_rIBxWKfl (num_entities: 3000) (common_func.py:565)
[2022-04-21 23:11:56 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [      int64   float varchar                                       float_vector
0         0     0.0       0  [0.3928730346203407, 0.4678997336054504, 0.081...
1         1     1.0       1  [0.20745681734876953, 0.44751380916018585, 0.5...
2         2     2.0       2  [0.2656417918938573, 0.5326812693......, kwargs: {'timeout': 20} (api_request.py:56)
[2022-04-21 23:11:56 - DEBUG - ci_test]: (api_response) : (insert count: 3000, delete count: 0, upsert count: 0, timestamp: 432682805983182849)  (api_request.py:28)
[2022-04-21 23:12:00 - INFO - ci_test]: insert_data: inserted data into collection search_collection_rIBxWKfl (num_entities: 3000) (client_base.py:184)
[2022-04-21 23:12:00 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None], kwargs: {'timeout': 20} (api_request.py:56)
[2022-04-21 23:12:01 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=collection 432682805904801793 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-04-21 23:12:00.736267', 'RPC error': '2022-04-21 23:12:01.295755'}> (decorators.py:73)
[2022-04-21 23:12:01 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=collection 432682805904801793 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-04-21 23:12:00.685434', 'RPC error': '2022-04-21 23:12:01.295959'}> (decorators.py:73)
[2022-04-21 23:12:01 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/jingjing/Workspace/milvus_modify/tests/python_client/utils/api_request.py", line 23, in inner_wrapper
    res = func(*args, **kwargs)
  File "/Users/jingjing/Workspace/milvus_modify/tests/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 435, in load
    conn.load_collection(self._name, timeout=timeout, replica_number=replica_number, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 699, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 713, in wait_for_loading_collection
    return self._wait_for_loading_collection(collection_name, timeout)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 742, in _wait_for_loading_collection
    progress = self.get_collection_loading_progress(collection_name, timeout)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 721, in get_collection_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection 432682805904801793 has not been loaded to memory or load failed)>
 (api_request.py:36)
[2022-04-21 23:12:01 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=collection 432682805904801793 has not been loaded to memory or load failed)> (api_request.py:37)
```

### Expected Behavior

Search normally

### Anything else?

cluster：
```
test-string-etcd-0                                                1/1     Running     0          13h     10.97.5.4      qa-node003.zilliz.local   <none>           <none>
test-string-etcd-1                                                1/1     Running     0          13h     10.97.16.63    qa-node013.zilliz.local   <none>           <none>
test-string-etcd-2                                                1/1     Running     0          13h     10.97.20.253   qa-node018.zilliz.local   <none>           <none>
test-string-milvus-datacoord-7fcd5c7494-lhhm9                     1/1     Running     0          13h     10.97.5.254    qa-node003.zilliz.local   <none>           <none>
test-string-milvus-datanode-5b46c896c5-2tjpj                      1/1     Running     0          13h     10.97.5.2      qa-node003.zilliz.local   <none>           <none>
test-string-milvus-indexcoord-898987849-2gqg8                     1/1     Running     0          13h     10.97.16.57    qa-node013.zilliz.local   <none>           <none>
test-string-milvus-indexnode-856479cb96-zvpgd                     1/1     Running     0          13h     10.97.5.253    qa-node003.zilliz.local   <none>           <none>
test-string-milvus-proxy-98df7769f-jzd5n                          1/1     Running     1          13h     10.97.16.58    qa-node013.zilliz.local   <none>           <none>
test-string-milvus-querycoord-56fb69c7c4-qdxpv                    1/1     Running     0          13h     10.97.5.250    qa-node003.zilliz.local   <none>           <none>
test-string-milvus-querynode-8d6579b78-cqx4w                      1/1     Running     0          13h     10.97.16.60    qa-node013.zilliz.local   <none>           <none>
test-string-milvus-rootcoord-5cbddbb4b6-hbffm                     1/1     Running     1          13h     10.97.16.59    qa-node013.zilliz.local   <none>           <none>
test-string-minio-0                                               1/1     Running     0          13h     10.97.20.249   qa-node018.zilliz.local   <none>           <none>
test-string-minio-1                                               1/1     Running     0          13h     10.97.16.65    qa-node013.zilliz.local   <none>           <none>
test-string-minio-2                                               1/1     Running     0          13h     10.97.16.64    qa-node013.zilliz.local   <none>           <none>
test-string-minio-3                                               1/1     Running     0          13h     10.97.20.251   qa-node018.zilliz.local   <none>           <none>
test-string-pulsar-bookie-0                                       1/1     Running     0          13h     10.97.20.250   qa-node018.zilliz.local   <none>           <none>
test-string-pulsar-bookie-1                                       1/1     Running     0          13h     10.97.20.252   qa-node018.zilliz.local   <none>           <none>
test-string-pulsar-bookie-2                                       1/1     Running     0          13h     10.97.20.254   qa-node018.zilliz.local   <none>           <none>
test-string-pulsar-bookie-init-9q276                              0/1     Completed   0          13h     10.97.5.252    qa-node003.zilliz.local   <none>           <none>
test-string-pulsar-broker-0                                       1/1     Running     0          13h     10.97.20.248   qa-node018.zilliz.local   <none>           <none>
test-string-pulsar-proxy-0                                        1/1     Running     0          13h     10.97.16.62    qa-node013.zilliz.local   <none>           <none>
test-string-pulsar-pulsar-init-26fwn                              0/1     Completed   0          13h     10.97.5.251    qa-node003.zilliz.local   <none>           <none>
test-string-pulsar-recovery-0                                     1/1     Running     0          13h     10.97.16.61    qa-node013.zilliz.local   <none>           <none>
test-string-pulsar-zookeeper-0                                    1/1     Running     0          13h     10.97.5.3      qa-node003.zilliz.local   <none>           <none>
test-string-pulsar-zookeeper-1                                    1/1     Running     0          13h     10.97.16.66    qa-node013.zilliz.local   <none>           <none>
test-string-pulsar-zookeeper-2                                    1/1     Running     0          13h     10.97.16.67    qa-node013.zilliz.local   <none>           <none>

```

**Comment by xige-16** [comment]
utry to update the pymilvus version to  2.1.0.dev29.

**Comment by xige-16** [comment]
The issue should has been fixed, Trouble you check it. @jingkl

**Comment by jingkl** [comment]
pymilvus 2.1.0.dev36
milvus tag： xige-16-segcore-load-string-ea423ac9d-20220429
Fixed, testcase passed
