### ISSUE TITLE
[Bug]: [embd] Start milvus failed with panic "invalid memory address or nil pointer dereference" when there is no right to create directory for etcd

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#16621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: embd
- Deployment mode(standalone or cluster):NA
- SDK version(e.g. pymilvus v2.0.0rc2):NA
- OS(Ubuntu or CentOS): mac intel
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
>>> milvus.start()
>>> panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x103ca6361]

goroutine 146 [running]:
github.com/milvus-io/milvus/internal/util/etcd.GetEmbedEtcdClient(...)
	/Users/binbin/zillizProjects/milvus-embedding/internal/util/etcd/etcd_server.go:23
github.com/milvus-io/milvus/internal/util/etcd.GetEtcdClient(0x105fc74bb)
	/Users/binbin/zillizProjects/milvus-embedding/internal/util/etcd/etcd_util.go:29 +0x21
github.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).init(0xc0005ae2c0)
	/Users/binbin/zillizProjects/milvus-embedding/internal/distributed/rootcoord/service.go:162 +0x127
{"level":"info","ts":"2022-04-24T16:40:15.173+0800","caller":"embed/etcd.go:131","msg":"configuring peer listeners","listen-peer-urls":["http://localhost:2380"]}
{"level":"info","ts":"2022-04-24T16:40:15.175+0800","caller":"embed/etcd.go:139","msg":"configuring client listeners","listen-client-urls":["http://localhost:2379"]}
{"level":"info","ts":"2022-04-24T16:40:15.176+0800","caller":"embed/etcd.go:307","msg":"starting an etcd server","etcd-version":"3.5.0","git-sha":"Not provided (use ./build instead of go build)","go-version":"go1.17.3","go-os":"darwin","go-arch":"amd64","max-cpu-set":8,"max-cpu-available":8,"member-initialized":false,"name":"default","data-dir":"default.etcd","wal-dir":"","wal-dir-dedicated":"","member-dir":"default.etcd/member","force-new-cluster":false,"heartbeat-interval":"100ms","election-timeout":"1s","initial-election-tick-advance":true,"snapshot-count":100000,"snapshot-catchup-entries":5000,"initial-advertise-peer-urls":["http://localhost:2380"],"listen-peer-urls":["http://localhost:2380"],"advertise-client-urls":["http://localhost:2379"],"listen-client-urls":["http://localhost:2379"],"listen-metrics-urls":[],"cors":["*"],"host-whitelist":["*"],"initial-cluster":"default=http://localhost:2380","initial-cluster-state":"new","initial-cluster-token":"etcd-cluster","quota-size-bytes":2147483648,"pre-vote":true,"initial-corrupt-check":false,"corrupt-check-time-interval":"0s","auto-compaction-mode":"","auto-compaction-retention":"0s","auto-compaction-interval":"0s","discovery-url":"","discovery-proxy":"","downgrade-check-interval":"5s"}
{"level":"info","ts":"2022-04-24T16:40:15.176+0800","caller":"embed/etcd.go:367","msg":"closing etcd server","name":"default","data-dir":"default.etcd","advertise-peer-urls":["http://localhost:2380"],"advertise-client-urls":["http://localhost:2379"]}
{"level":"info","ts":"2022-04-24T16:40:15.176+0800","caller":"embed/etcd.go:369","msg":"closed etcd server","name":"default","data-dir":"default.etcd","advertise-peer-urls":["http://localhost:2380"],"advertise-client-urls":["http://localhost:2379"]}
```

### Expected Behavior

start milvus successfully

### Steps To Reproduce

```markdown
https://github.com/milvus-io/embd-milvus
```

**Comment by soothing-rain** [comment]
@binbinlv this is done.
