### ISSUE TITLE
[Bug]: [embd] Panic occurs when call start interface twice reporting "duplicate metrics collector registration attempted" 

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#16647]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: NA (embed milvus -- latest)
- Deployment mode(standalone or cluster):NA
- SDK version(e.g. pymilvus v2.0.0rc2):NA
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Panic occurs when call start interface twice reporting "duplicate metrics collector registration attempted" 

```
>>> panic: duplicate metrics collector registration attempted

goroutine 50 [running, locked to thread]:
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc0000ad130, {0xc00065d648, 0x1, 0x105a82891})
	/Users/binbin/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:403 +0x7f
github.com/milvus-io/milvus/internal/metrics.RegisterRootCoord(0xc00065d658)
	/Users/binbin/zillizProjects/milvus-embd/internal/metrics/rootcoord_metrics.go:354 +0x65
github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runRootCoord(0x1087a75f2, {0x1092924d0, 0xc001d7ba00}, 0x1)
	/Users/binbin/zillizProjects/milvus-embd/cmd/roles/roles.go:118 +0xf3
github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run(0xc00065dd28, 0x1, {0x0, 0x0})
	/Users/binbin/zillizProjects/milvus-embd/cmd/roles/roles.go:388 +0x518
github.com/milvus-io/milvus/cmd/milvus.RunMilvus({0xc001d3db00, 0x3, 0x3})
	/Users/binbin/zillizProjects/milvus-embd/cmd/milvus/milvus.go:331 +0xa25
main.startEmbedded()
	/Users/binbin/zillizProjects/milvus-embd/pkg/embedded/embedded.go:29 +0x77
```

### Expected Behavior

Report errors

### Steps To Reproduce

```markdown
>>> milvus.start()
>>> milvus.start()
```

**Comment by soothing-rain** [comment]
done.
