### ISSUE TITLE
[Bug]: [test-string] Error re-creating an index after deletion of the index

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#16699]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:xige-16-segcore-load-string-b50e5bf72-20220425
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.1.0.dev33
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

testcase：

```
@pytest.mark.tags(CaseLabel.L2)
    def test_create_drop_index_repeated(self):
        """
        target: test create / drop index repeatedly, use the same index params
        method: create index, drop index, four times
        expected: return code 0
        """
        c_name = cf.gen_unique_str(prefix)
        collection_w = self.init_collection_wrap(name=c_name)
        data = cf.gen_default_list_data(nb=3000)
        collection_w.insert(data=data)
        collection_w.create_index(default_float_vec_field_name, default_index_params)
        collection_w.drop_index()
        collection_w.create_index(default_float_vec_field_name, default_index_params)
```
error log：

```
[2022-04-28 10:25:53 - DEBUG - ci_test]: (api_response) : Status(code=0, message='')  (api_request.py:28)
[2022-04-28 10:25:53 - DEBUG - ci_test]: (api_request)  : [Collection.drop_index] args: [], kwargs: {'timeout': 20} (api_request.py:56)
[2022-04-28 10:25:53 - DEBUG - ci_test]: (api_response) : None  (api_request.py:28)
[2022-04-28 10:25:53 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['float_vector', {'index_type': 'IVF_SQ8', 'metric_type': 'L2', 'params': {'nlist': 64}}], kwargs: {'timeout': 40} (api_request.py:56)
[2022-04-28 10:25:54 - ERROR - pymilvus.decorators]: RPC error: [get_index_state], <MilvusException: (code=1, message=DescribeSegments failed: cannot find index, id = 432829301482586113)>, <Time:{'RPC start': '2022-04-28 10:25:54.456234', 'RPC error': '2022-04-28 10:25:54.480655'}> (decorators.py:73)
[2022-04-28 10:25:54 - ERROR - pymilvus.decorators]: RPC error: [wait_for_creating_index], <MilvusException: (code=1, message=DescribeSegments failed: cannot find index, id = 432829301482586113)>, <Time:{'RPC start': '2022-04-28 10:25:53.953333', 'RPC error': '2022-04-28 10:25:54.481128'}> (decorators.py:73)
[2022-04-28 10:25:54 - ERROR - pymilvus.decorators]: RPC error: [create_index], <MilvusException: (code=1, message=DescribeSegments failed: cannot find index, id = 432829301482586113)>, <Time:{'RPC start': '2022-04-28 10:25:53.871939', 'RPC error': '2022-04-28 10:25:54.481282'}> (decorators.py:73)
[2022-04-28 10:25:54 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/jingjing/Workspace/milvus_modify/tests/python_client/utils/api_request.py", line 23, in inner_wrapper
    res = func(*args, **kwargs)
  File "/Users/jingjing/Workspace/milvus_modify/tests/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 1030, in create_index
    return conn.create_index(self._name, field_name, index_params,
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 625, in create_index
    index_success, fail_reason = self.wait_for_creating_index(collection_name=collection_name,
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 679, in wait_for_creating_index
    state, fail_reason = self.get_index_state(collection_name, field_name, timeout, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 671, in get_index_state
    raise MilvusException(status.error_code, status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=DescribeSegments failed: cannot find index, id = 432829301482586113)>
 (api_request.py:36)
[2022-04-28 10:25:54 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=DescribeSegments failed: cannot find index, id = 432829301482586113)> (api_request.py:37)
```

**Comment by xige-16** [comment]
I'm working on this issue.

**Comment by xige-16** [comment]
This issue has not been reproduced in the corresponding version. @jingkl

**Comment by xige-16** [comment]
The issue should has been fixed, Trouble you check it with lastet milvus version. @jingkl

**Comment by jingkl** [comment]
pymilvus:2.1.0.dev47
milvus:[master-20220507-92b6293b](https://hub.docker.com/layers/milvus-dev/milvusdb/milvus-dev/master-20220507-92b6293b/images/sha256-7551a4bf642725f2653cf7c6841c24909f6a0036da04e8487f7bb0f1e51a9b21?context=explore)
test log:
```
pe': 'L2', 'params': {'nlist': 64}}], kwargs: {'timeout': 40} (api_request.py:56)
[2022-05-07 15:44:01 - ERROR - pymilvus.decorators]: RPC error: [get_index_state], <MilvusException: (code=1, message=DescribeSegments failed: cannot find index, id = 433038148777803777)>, <Time:{'RPC start': '2022-05-07 15:44:01.651285', 'RPC error': '2022-05-07 15:44:01.674452'}> (decorators.py:73)
[2022-05-07 15:44:01 - ERROR - pymilvus.decorators]: RPC error: [wait_for_creating_index], <MilvusException: (code=1, message=DescribeSegments failed: cannot find index, id = 433038148777803777)>, <Time:{'RPC start': '2022-05-07 15:44:01.146405', 'RPC error': '2022-05-07 15:44:01.674803'}> (decorators.py:73)
[2022-05-07 15:44:01 - ERROR - pymilvus.decorators]: RPC error: [create_index], <MilvusException: (code=1, message=DescribeSegments failed: cannot find index, id = 433038148777803777)>, <Time:{'RPC start': '2022-05-07 15:44:01.063830', 'RPC error': '2022-05-07 15:44:01.674961'}> (decorators.py:73)
[2022-05-07 15:44:01 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/jingjing/Workspace/milvus_modify/tests/python_client/utils/api_request.py", line 23, in inner_wrapper
    res = func(*args, **kwargs)
  File "/Users/jingjing/Workspace/milvus_modify/tests/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 1044, in create_index
    return conn.create_index(self._name, field_name, index_params,
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 641, in create_index
    index_success, fail_reason = self.wait_for_creating_index(collection_name=collection_name,
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 695, in wait_for_creating_index
    state, fail_reason = self.get_index_state(collection_name, field_name, timeout, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 687, in get_index_state
    raise MilvusException(status.error_code, status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=DescribeSegments failed: cannot find index, id = 433038148777803777)>
 (api_request.py:36)
[2022-05-07 15:44:01 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=DescribeSegments failed: cannot find index, id = 433038148777803777)> (api_request.py:37)
```

**Comment by jingkl** [comment]
assign @xige-16 @DragonDriver

**Comment by xige-16** [comment]
The reason is that the old index of some segments was not deleted when the index was dropped. When the index was created for the second time, the old index id was used to query the progress of segment build index, so the error "index id not found" was reported.

**Comment by xige-16** [comment]
The bug should has been fixed , please check it. @jingkl

**Comment by jingkl** [comment]
pymilvus：2.1.0.dev51
milvus：
master-20220507-c7935d1a
It has been verified that no errors are reported
