### ISSUE TITLE
[Bug]: [replica] Check if collection is loaded when get replica

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#16726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220428-68b1b82f
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.1.0.dev33
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
    def test_get_collection_replicas_not_loaded(self):
        # create, insert
        collection_w = self.init_collection_wrap(cf.gen_unique_str(prefix))
        df = cf.gen_default_dataframe_data()
        insert_res, _ = collection_w.insert(df)
        assert collection_w.num_entities == ct.default_nb

        replicas, _ = collection_w.get_replicas()
        log.debug(replicas)
```
```
[2022-04-29 10:59:17,122 - DEBUG - ci_test]: (api_request)  : [Collection.get_replicas] args: [20], kwargs: {} (api_request.py:55)
[2022-04-29 10:59:17,169 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/nausicca/projects/milvus/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
    res = func(*args, **kwargs)
  File "/Users/nausicca/projects/milvus/tests/python_client/utils/api_request.py", line 56, in api_request
    return func(*arg, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 1183, in get_replicas
    return conn.get_replicas(self.name, timeout=timeout, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 1161, in get_replicas
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=15, message=getCollectionInfoByID: can't find collectionID=432852474548191233 in collectionInfo)>
 (api_request.py:35)
[2022-04-29 10:59:17,169 - ERROR - ci_test]: (api_response) : <MilvusException: (code=15, message=getCollectionInfoByID: can't find collectionID=432852474548191233 in collectionInfo)> (api_request.py:36)
```

### Expected Behavior

No collection id in exception msg

**Comment by yanliang567** [comment]
@ThreadDao is this still an issue

**Comment by ThreadDao** [comment]
> @ThreadDao is this still an issue

Yes. because no one has fixed it

**Comment by yanliang567** [comment]
@yah01 any updates?

**Comment by yah01** [comment]
> @yah01 any updates?

WIP

**Comment by yah01** [comment]
@ThreadDao 
Just fixed with #17269, it should be "collection not found, maybe not loaded" now

**Comment by ThreadDao** [comment]
> @ThreadDao Just fixed with #17269, it should be "collection not found, maybe not loaded" now

Verified `master-20220530-11834a09`
