### ISSUE TITLE
[Bug]: [nightly] load failed reporting "collection  ***  has not been loaded to memory or load failed"

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#16793]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: latest
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

load failed reporting "collection  ***  has not been loaded to memory or load failed"

### Expected Behavior

load successfully

### Steps To Reproduce

nightly:
https://ci.milvus.io:18080/jenkins/blue/rest/organizations/jenkins/pipelines/milvus-nightly-ci/branches/master/runs/510/nodes/124/steps/166/log/?start=0

```python
    def test_search_after_different_index_with_params(self, dim, index, params, auto_id, _async):
        """
        target: test search after different index
        method: test search after different index and corresponding search params
        expected: search successfully with limit(topK)
        """
        # 1. initialize with data
        collection_w, _, _, insert_ids, time_stamp = self.init_collection_general(prefix, True, 5000,
                                                                                  partition_num=1,
                                                                                  auto_id=auto_id,
                                                                                  dim=dim, is_index=True)[0:5]
        # 2. create index and load
        if params.get("m"):
            if (dim % params["m"]) != 0:
                params["m"] = dim // 4
        if params.get("PQM"):
            if (dim % params["PQM"]) != 0:
                params["PQM"] = dim // 4
        default_index = {"index_type": index, "params": params, "metric_type": "L2"}
        collection_w.create_index("float_vector", default_index)
        collection_w.load()
```

### Milvus Log

1. https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/510/artifacts

artifacts-milvus-standalone-master-510-pymilvus-e2e-logs.tar.gz

2. Failed time:
[2022-05-04T19:18:07.870Z] [gw1] [ 56%] FAILED testcases/test_search_20.py::TestCollectionSearch::test_search_after_index_different_metric_type[128-False-True-RHNSW_PQ-params7] 

3. collection name:
search_collection_rvsMn2ze

4. test error:

```
[2022-05-04T20:22:30.545Z] [2022-05-04 19:17:58 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=collection 432981086363451395 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-05-04 19:16:15.432499', 'RPC error': '2022-05-04 19:17:58.948089'}> (decorators.py:73)
[2022-05-04T20:22:30.545Z] [2022-05-04 19:17:58 - ERROR - ci_test]: Traceback (most recent call last):
[2022-05-04T20:22:30.545Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
[2022-05-04T20:22:30.545Z]     res = func(*args, **kwargs)
[2022-05-04T20:22:30.545Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 56, in api_request
[2022-05-04T20:22:30.545Z]     return func(*arg, **kwargs)
[2022-05-04T20:22:30.545Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 435, in load
[2022-05-04T20:22:30.545Z]     conn.load_collection(self._name, timeout=timeout, replica_number=replica_number, **kwargs)
[2022-05-04T20:22:30.545Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 56, in handler
[2022-05-04T20:22:30.545Z]     raise e
[2022-05-04T20:22:30.545Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 41, in handler
[2022-05-04T20:22:30.545Z]     return func(self, *args, **kwargs)
[2022-05-04T20:22:30.545Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler
[2022-05-04T20:22:30.545Z]     raise e
[2022-05-04T20:22:30.545Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler
[2022-05-04T20:22:30.545Z]     return func(*args, **kwargs)
[2022-05-04T20:22:30.545Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 700, in load_collection
[2022-05-04T20:22:30.545Z]     self.wait_for_loading_collection(collection_name, timeout)
[2022-05-04T20:22:30.545Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 56, in handler
[2022-05-04T20:22:30.545Z]     raise e
[2022-05-04T20:22:30.545Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 41, in handler
[2022-05-04T20:22:30.545Z]     return func(self, *args, **kwargs)
[2022-05-04T20:22:30.545Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler
[2022-05-04T20:22:30.545Z]     raise e
[2022-05-04T20:22:30.545Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler
[2022-05-04T20:22:30.545Z]     return func(*args, **kwargs)
[2022-05-04T20:22:30.545Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 711, in wait_for_loading_collection
[2022-05-04T20:22:30.545Z]     return self._wait_for_loading_collection(collection_name, timeout)
[2022-05-04T20:22:30.545Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 740, in _wait_for_loading_collection
[2022-05-04T20:22:30.546Z]     progress = self.get_collection_loading_progress(collection_name, timeout)
[2022-05-04T20:22:30.546Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 719, in get_collection_loading_progress
[2022-05-04T20:22:30.546Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2022-05-04T20:22:30.546Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection 432981086363451395 has not been loaded to memory or load failed)>
[2022-05-04T20:22:30.546Z]  (api_request.py:35)
[2022-05-04T20:22:30.546Z] [2022-05-04 19:17:58 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=collection 432981086363451395 has not been loaded to memory or load failed)> (api_request.py:36)
```

**Comment by yanliang567** [comment]
@binbinlv any special node replicas or memory replicas configured here ?

**Comment by binbinlv** [comment]
Reproduced frequently, so set it as urgent.

**Comment by binbinlv** [comment]
Has not been reproduced for several days, so close it first and will reopen it if it occurs in the furture.
