### ISSUE TITLE
[Bug]: [nightly] Test pipeline hangs for cluster mode

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#16809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 7cc995d
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): latest
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Test pipeline hangs for cluster mode

### Expected Behavior

Tests executed successfully

### Steps To Reproduce

```markdown
Nightly:
https://ci.milvus.io:18080/jenkins/blue/rest/organizations/jenkins/pipelines/milvus-nightly-ci/branches/master/runs/512/nodes/190/steps/211/log/?start=0
```

### Milvus Log

```markdown
logs:
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/512/artifacts/

artifacts-milvus-distributed-pulsar-master-512-pymilvus-e2e-logs.tar.gz

Some clues:

time="2022-05-05T21:01:19Z" level=warning msg="[Failed to connect to broker.]" error="dial tcp: lookup mdp-512-n-pulsar-proxy on 10.201.0.10:53: no such host" remote_addr="pulsar://mdp-512-n-pulsar-proxy:6650"

[2022/05/05 21:01:19.761 +00:00] [ERROR] [pulsar_consumer.go:122] ["failed to unsubscribe"] [subscription=by-dev-dataCoord] [error="All attempts results:\nattempt #1:topic persistent://public/default/by-dev-datacoord-timetick-channel, subscription by-dev-dataCoord: connection closed\nattempt #2:topic persistent://public/default/by-dev-datacoord-timetick-channel, subscription by-dev-dataCoord: connection closed\nattempt #3:topic persistent://public/default/by-dev-datacoord-timetick-channel, subscription by-dev-dataCoord: connection closed\nattempt #4:topic persistent://public/default/by-dev-datacoord-timetick-channel, subscription by-dev-dataCoord: connection closed\nattempt #5:topic persistent://public/default/by-dev-datacoord-timetick-channel, subscription by-dev-dataCoord: connection closed\nattempt #6:topic persistent://public/default/by-dev-datacoord-timetick-channel, subscription by-dev-dataCoord: connection closed\n"] [stack="github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/pulsar.(*Consumer).Close.func1\n\t/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/pulsar/pulsar_consumer.go:122\nsync.(*Once).doSlow\n\t/usr/local/go/src/sync/once.go:68\nsync.(*Once).Do\n\t/usr/local/go/src/sync/once.go:59\ngithub.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/pulsar.(*Consumer).Close\n\t/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/pulsar/pulsar_consumer.go:114\ngithub.com/milvus-io/milvus/internal/mq/msgstream.(*mqMsgStream).Close\n\t/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_msgstream.go:199\ngithub.com/milvus-io/milvus/internal/datacoord.(*Server).handleDataNodeTimetickMsgstream.func1\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/server.go:478\ngithub.com/milvus-io/milvus/internal/datacoord.(*Server).handleDataNodeTimetickMsgstream\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/server.go:484"]

time="2022-05-05T21:01:19Z" level=info msg="Closing consumer=1" consumerID=1 name=zsplm subscription=by-dev-dataCoord topic="persistent://public/default/by-dev-datacoord-timetick-channel"

time="2022-05-05T21:01:19Z" level=warning msg="[Failed to close consumer]" consumerID=1 error="connection closed" name=zsplm subscription=by-dev-dataCoord topic="persistent://public/default/by-dev-datacoord-timetick-channel"

[2022/05/05 21:01:19.762 +00:00] [ERROR] [server.go:475] ["Failed to close ttMessage"] [recovered="All attempts results:\nattempt #1:topic persistent://public/default/by-dev-datacoord-timetick-channel, subscription by-dev-dataCoord: connection closed\nattempt #2:topic persistent://public/default/by-dev-datacoord-timetick-channel, subscription by-dev-dataCoord: connection closed\nattempt #3:topic persistent://public/default/by-dev-datacoord-timetick-channel, subscription by-dev-dataCoord: connection closed\nattempt #4:topic persistent://public/default/by-dev-datacoord-timetick-channel, subscription by-dev-dataCoord: connection closed\nattempt #5:topic persistent://public/default/by-dev-datacoord-timetick-channel, subscription by-dev-dataCoord: connection closed\nattempt #6:topic persistent://public/default/by-dev-datacoord-timetick-channel, subscription by-dev-dataCoord: connection closed\n"] [stack="github.com/milvus-io/milvus/internal/datacoord.(*Server).handleDataNodeTimetickMsgstream.func1.1\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/server.go:475\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:965\ngithub.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/pulsar.(*Consumer).Close.func1\n\t/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/pulsar/pulsar_consumer.go:123\nsync.(*Once).doSlow\n\t/usr/local/go/src/sync/once.go:68\nsync.(*Once).Do\n\t/usr/local/go/src/sync/once.go:59\ngithub.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/pulsar.(*Consumer).Close\n\t/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/pulsar/pulsar_consumer.go:114\ngithub.com/milvus-io/milvus/internal/mq/msgstream.(*mqMsgStream).Close\n\t/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_msgstream.go:199\ngithub.com/milvus-io/milvus/internal/datacoord.(*Server).handleDataNodeTimetickMsgstream.func1\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/server.go:478\ngithub.com/milvus-io/milvus/internal/datacoord.(*Server).handleDataNodeTimetickMsgstream\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/server.go:484"]
```
```


### Anything else?

_No response_

**Comment by binbinlv** [comment]
Similar issue in the following nightly: [in cluster mode, both in pulsar cluster and kafka cluster mode]

https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/511/pipeline/157

https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/510/pipeline/145

https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/509/pipeline

**Comment by binbinlv** [comment]
Block nightly CI tests for cluster mode, so set it as critical urgent.

**Comment by binbinlv** [comment]
Still exists in the latest nightly:
1. logs:
[artifacts-milvus-distributed-pulsar-master-520-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/520/artifact/artifacts-milvus-distributed-pulsar-master-520-pymilvus-e2e-logs.tar.gz)

2. test logs: (cluster pulsar)
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/520/pipeline

**Comment by binbinlv** [comment]
@congqixia 
could you help to have a check?

**Comment by binbinlv** [comment]
@congqixia could you please have a check? Thanks.

The tests still hang in the latest nightly: （be688d8）
Confirmed this nightly includes the fix commit: 34833680daa5e23a59d5db6998004be83f6abf20
nightly commit:
commit be688d894aaf16f84fd3ba04237075c3d2eb2fa3
Author: Jiquan Long <jiquan.long@zilliz.com>
Date:   Tue May 10 21:07:53 2022 +0800

    Forbid multiple indexes on same field (#16875)

    Signed-off-by: dragondriver <jiquan.long@zilliz.com>

Fixing PR commit:
commit 34833680daa5e23a59d5db6998004be83f6abf20
Author: congqixia <congqi.xia@zilliz.com>
Date:   Tue May 10 18:09:53 2022 +0800

    Add lock before query release collection from replica (#16880)

    Signed-off-by: Congqi Xia <congqi.xia@zilliz.com>


1. logs:
[artifacts-milvus-distributed-pulsar-master-522-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/522/artifact/artifacts-milvus-distributed-pulsar-master-522-pymilvus-e2e-logs.tar.gz)

2. test logs:
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/522/pipeline

some clues in log file: mdp-522-n-milvus-querycoord-5cbf844456-5rwrf_milvus-ci_querycoord-3a2513c5330b18be20c710dee253aba66279210423f822a00ce83e2df3c0b663.log

```
panic: All attempts results:

attempt #1:err: find no available datacoord, check datacoord state

, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace

/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:256 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall

/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:114 github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).GetComponentStates

/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:62 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates.func1

/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:37 github.com/milvus-io/milvus/internal/util/retry.Do

/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:86 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates

/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:101 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentHealthy

/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/service.go:184 github.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).init

/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/service.go:96 github.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).Run

/go/src/github.com/milvus-io/milvus/cmd/components/query_coord.go:50 github.com/milvus-io/milvus/cmd/components.(*QueryCoord).Run
```

**Comment by binbinlv** [comment]
And the following nightly hangs too:
[artifacts-milvus-distributed-pulsar-master-521-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/521/artifact/artifacts-milvus-distributed-pulsar-master-521-pymilvus-e2e-logs.tar.gz)

**Comment by binbinlv** [comment]
It is still reproduced in the latest nightly:
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/523/pipeline

The nightly commit is just the PR to be fixed:
commit a8b81e215bff189866fbfb7f474979ea5ab5d589
Author: congqixia <congqi.xia@zilliz.com>
Date:   Wed May 11 21:57:53 2022 +0800

    Fix deadlock in release replica (#16925)

    Signed-off-by: Congqi Xia <congqi.xia@zilliz.com>

1. logs:

[artifacts-milvus-distributed-pulsar-master-523-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/523/artifact/artifacts-milvus-distributed-pulsar-master-523-pymilvus-e2e-logs.tar.gz)

And it seems that actually it runs very slowly, maybe not hangs this time, need furthur check ,thanks.

**Comment by binbinlv** [comment]
Similar in the following nightly:
[artifacts-milvus-distributed-pulsar-master-524-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/524/artifact/artifacts-milvus-distributed-pulsar-master-524-pymilvus-e2e-logs.tar.gz)

**Comment by binbinlv** [comment]
Similar phenomenon in the latest nightly:
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/526/pipeline/157

logs:
[artifacts-milvus-distributed-pulsar-master-526-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/526/artifact/artifacts-milvus-distributed-pulsar-master-526-pymilvus-e2e-logs.tar.gz)

**Comment by binbinlv** [comment]
Similar phenomenon in the latest nightly:

https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/525/pipeline/190

logs:
[artifacts-milvus-distributed-pulsar-master-525-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/525/artifact/artifacts-milvus-distributed-pulsar-master-525-pymilvus-e2e-logs.tar.gz)

**Comment by binbinlv** [comment]
@congqixia 

How about this issue now?

Continuously hang in the nightly tests:

https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/532/pipeline/190

logs:
[artifacts-milvus-distributed-pulsar-master-532-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/532/artifact/artifacts-milvus-distributed-pulsar-master-532-pymilvus-e2e-logs.tar.gz)

**Comment by congqixia** [comment]
working on it.

**Comment by jaime0815** [comment]
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/531/artifacts


nightly hang due to datanode core dump.

```
[2022/05/15 15:11:50.589 +00:00] [WARN] [flush_manager.go:696] ["failed to DropVirtualChannel"] [channel=by-dev-rootcoord-dml_90_433226329834651649v0] [error="All attempts results:\nattempt #1:data service DropVirtualChannel failed, reason = channel by-dev-rootcoord-dml_90_433226329834651649v0 is not watched on node 10\nattempt #2:data service DropVirtualChannel failed, reason = channel by-dev-rootcoord-dml_90_433226329834651649v0 is not watched on node 10\nattempt #3:data service DropVirtualChannel failed, reason = channel by-dev-rootcoord-dml_90_433226329834651649v0 is not watched on node 10\nattempt #4:data service DropVirtualChannel failed, reason = channel by-dev-rootcoord-dml_90_433226329834651649v0 is not watched on node 10\nattempt #5:data service DropVirtualChannel failed, reason = channel by-dev-rootcoord-dml_90_433226329834651649v0 is not watched on node 10\nattempt #6:data service DropVirtualChannel failed, reason = channel by-dev-rootcoord-dml_90_433226329834651649v0 is not watched on node 10\nattempt #7:data service DropVirtualChannel failed, reason = channel by-dev-rootcoord-dml_90_433226329834651649v0 is not watched on node 10\nattempt #8:data service DropVirtualChannel failed, reason = channel by-dev-rootcoord-dml_90_433226329834651649v0 is not watched on node 10\nattempt #9:data service DropVirtualChannel failed, reason = channel by-dev-rootcoord-dml_90_433226329834651649v0 is not watched on node 10\nattempt #10:data service DropVirtualChannel failed, reason = channel by-dev-rootcoord-dml_90_433226329834651649v0 is not watched on node 10\n"]

panic: All attempts results:

attempt #1:data service DropVirtualChannel failed, reason = channel by-dev-rootcoord-dml_90_433226329834651649v0 is not watched on node 10

attempt #2:data service DropVirtualChannel failed, reason = channel by-dev-rootcoord-dml_90_433226329834651649v0 is not watched on node 10

attempt #3:data service DropVirtualChannel failed, reason = channel by-dev-rootcoord-dml_90_433226329834651649v0 is not watched on node 10

attempt #4:data service DropVirtualChannel failed, reason = channel by-dev-rootcoord-dml_90_433226329834651649v0 is not watched on node 10

attempt #5:data service DropVirtualChannel failed, reason = channel by-dev-rootcoord-dml_90_433226329834651649v0 is not watched on node 10

attempt #6:data service DropVirtualChannel failed, reason = channel by-dev-rootcoord-dml_90_433226329834651649v0 is not watched on node 10

attempt #7:data service DropVirtualChannel failed, reason = channel by-dev-rootcoord-dml_90_433226329834651649v0 is not watched on node 10

attempt #8:data service DropVirtualChannel failed, reason = channel by-dev-rootcoord-dml_90_433226329834651649v0 is not watched on node 10

attempt #9:data service DropVirtualChannel failed, reason = channel by-dev-rootcoord-dml_90_433226329834651649v0 is not watched on node 10

attempt #10:data service DropVirtualChannel failed, reason = channel by-dev-rootcoord-dml_90_433226329834651649v0 is not watched on node 10


goroutine 12996 [running]:

[github.com/milvus-io/milvus/internal/datanode.dropVirtualChannelFunc.func1](http://github.com/milvus-io/milvus/internal/datanode.dropVirtualChannelFunc.func1)(0x0, 0x0, 0x0)

        /go/src/[github.com/milvus-io/milvus/internal/datanode/flush_manager.go:697](http://github.com/milvus-io/milvus/internal/datanode/flush_manager.go:697) +0x10bf

[github.com/milvus-io/milvus/internal/datanode.(*rendezvousFlushManager).startDropping.func1(0xc003b31760)](http://github.com/milvus-io/milvus/internal/datanode.(*rendezvousFlushManager).startDropping.func1(0xc003b31760))

        /go/src/[github.com/milvus-io/milvus/internal/datanode/flush_manager.go:526](http://github.com/milvus-io/milvus/internal/datanode/flush_manager.go:526) +0x1cb

created by [github.com/milvus-io/milvus/internal/datanode.(*rendezvousFlushManager).startDropping](http://github.com/milvus-io/milvus/internal/datanode.(*rendezvousFlushManager).startDropping)

        /go/src/[github.com/milvus-io/milvus/internal/datanode/flush_manager.go:510](http://github.com/milvus-io/milvus/internal/datanode/flush_manager.go:510) +0x7e

```

**Comment by binbinlv** [comment]
The cluster pipeline did not hang last nightly, fixed and close this issue.

(1) https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/533/pipeline

(2)https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/534/pipeline/141
