### ISSUE TITLE
[Bug]: Flush stuck

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#16819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

{"level":"INFO","time":"2022/05/06 13:56:42.170 +00:00","caller":"flow_graph_dd_node.go:136","message":"Filtering Insert Messages","Message endts":433019725736312834,"FilterThreshold":433021341487333377}
{"level":"INFO","time":"2022/05/06 13:56:42.171 +00:00","caller":"flow_graph_dd_node.go:136","message":"Filtering Insert Messages","Message endts":433019725736312834,"FilterThreshold":433021341487333377}
{"level":"INFO","time":"2022/05/06 13:56:42.186 +00:00","caller":"flow_graph_insert_buffer_node.go:241","message":"insert seg buffer status","No.":0,"segmentID":433019724097912834,"vchannel name":"milvus-rootcoord-dml_11_433019501078904833v1","buffer size":9464,"buffer limit":8192}
{"level":"INFO","time":"2022/05/06 13:56:42.186 +00:00","caller":"flow_graph_insert_buffer_node.go:292","message":"Auto flush","segment id":433019724097912834,"vchannel name":"milvus-rootcoord-dml_11_433019501078904833v1"}
{"level":"INFO","time":"2022/05/06 13:56:42.310 +00:00","caller":"segment_replica.go:243","message":"Add new segment","segment ID":433019725788741633,"collection ID":433019501078904833,"partition ID":433019501078904834,"channel name":"milvus-rootcoord-dml_11_433019501078904833v1"}
{"level":"INFO","time":"2022/05/06 13:56:42.310 +00:00","caller":"segment_replica.go:614","message":"updating segment","Segment ID":433019725788741633,"numRows":6381}
{"level":"INFO","time":"2022/05/06 13:56:42.312 +00:00","caller":"segment_replica.go:125","message":"update pk range","collectionID":433019501078904833,"partitionID":433019501078904834,"segmentID":433019725788741633,"channel":"milvus-rootcoord-dml_11_433019501078904833v1","num_rows":6381,"minPK":231334,"maxPK":92933290}
{"level":"WARN","time":"2022/05/06 13:56:42.319 +00:00","caller":"flush_manager.go:783","message":"failed to SaveBinlogPaths","error":"All attempts results:\nattempt #1:data service save bin log path failed, reason = failed to get segment 433019556797612034\nattempt #2:data service save bin log path failed, reason = failed to get segment 433019556797612034\nattempt #3:data service save bin log path failed, reason = failed to get segment 433019556797612034\nattempt #4:data service save bin log path failed, reason = failed to get segment 433019556797612034\nattempt #5:data service save bin log path failed, reason = failed to get segment 433019556797612034\nattempt #6:data service save bin log path failed, reason = failed to get segment 433019556797612034\nattempt #7:data service save bin log path failed, reason = failed to get segment 433019556797612034\nattempt #8:data service save bin log path failed, reason = failed to get segment 433019556797612034\nattempt #9:data service save bin log path failed, reason = failed to get segment 433019556797612034\nattempt #10:data service save bin log path failed, reason = failed to get segment 433019556797612034\n"}
panic: All attempts results:
attempt #1:data service save bin log path failed, reason = failed to get segment 433019556797612034
attempt #2:data service save bin log path failed, reason = failed to get segment 433019556797612034
attempt #3:data service save bin log path failed, reason = failed to get segment 433019556797612034
attempt #4:data service save bin log path failed, reason = failed to get segment 433019556797612034
attempt #5:data service save bin log path failed, reason = failed to get segment 433019556797612034
attempt #6:data service save bin log path failed, reason = failed to get segment 433019556797612034
attempt #7:data service save bin log path failed, reason = failed to get segment 433019556797612034
attempt #8:data service save bin log path failed, reason = failed to get segment 433019556797612034
attempt #9:data service save bin log path failed, reason = failed to get segment 433019556797612034
attempt #10:data service save bin log path failed, reason = failed to get segment 433019556797612034

goroutine 32099 [running]:
github.com/milvus-io/milvus/internal/datanode.flushNotifyFunc.func1(0xc04f2f9a40)
	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_manager.go:785 +0x151f
github.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).waitFinish(0xc0000fb080, 0xc000de1740, 0xc04d7fa1f0)
	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_task.go:195 +0xbd
created by github.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).init.func1
	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_task.go:119 +0xb0

datanode and datacoord log are list as follow

[datanode (1).log](https://github.com/milvus-io/milvus/files/8641556/datanode.1.log)
[datacoord (1).log](https://github.com/milvus-io/milvus/files/8641557/datacoord.1.log)

### Expected Behavior

flush should be idempotent with no error

**Comment by xiaofan-luan** [comment]
@sunby please help on investigation
