### ISSUE TITLE
[Bug]: [nightly] Milvus is panic showing fatal segment error

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#16811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 7cc995d
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.1.0.dev36
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Milvus is panic showing fatal segment error

### Expected Behavior

No panic

### Steps To Reproduce

```markdown
Nightly:
https://ci.milvus.io:18080/jenkins/blue/rest/organizations/jenkins/pipelines/milvus-nightly-ci/branches/master/runs/512/nodes/124/steps/145/log/?start=0
```

### Milvus Log

```markdown
1. milvus logs:

https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/512/artifacts
artifacts-milvus-standalone-master-512-pymilvus-e2e-logs.tar.gz

2. panic info:

panic files:

ms-512-n-milvus-standalone-5c774577df-68mtq_milvus-ci_standalone-12d1cfef5090c482ae7141539d79b38658d074dda26bbcd03a1a0710130f7233.log:	/usr/local/go/src/runtime/panic.go:1117 +0x72
ms-512-n-milvus-standalone-5c774577df-68mtq_milvus-ci_standalone-12d1cfef5090c482ae7141539d79b38658d074dda26bbcd03a1a0710130f7233.log:runtime.sigpanic()
ms-512-n-milvus-standalone-5c774577df-68mtq_milvus-ci_standalone-1b0d0289312bdb95718ca49ff39c367dfb17f62e8ae627e37c7a5fd1b9ae34f1.log:	/usr/local/go/src/runtime/panic.go:1117 +0x72
ms-512-n-milvus-standalone-5c774577df-68mtq_milvus-ci_standalone-1b0d0289312bdb95718ca49ff39c367dfb17f62e8ae627e37c7a5fd1b9ae34f1.log:runtime.sigpanic()
ms-512-n-milvus-standalone-5c774577df-68mtq_milvus-ci_standalone-1b0d0289312bdb95718ca49ff39c367dfb17f62e8ae627e37c7a5fd1b9ae34f1.log:	/usr/local/go/src/runtime/panic.go:1117 +0x72
ms-512-n-milvus-standalone-5c774577df-68mtq_milvus-ci_standalone-1b0d0289312bdb95718ca49ff39c367dfb17f62e8ae627e37c7a5fd1b9ae34f1.log:runtime.sigpanic()
ms-512-n-milvus-standalone-5c774577df-68mtq_milvus-ci_standalone-5a8bbbefec6d876821a93aeb0cc7442308957f36208f7414c15fbd2bedde5112.log:	/usr/local/go/src/runtime/panic.go:1117 +0x72
ms-512-n-milvus-standalone-5c774577df-68mtq_milvus-ci_standalone-5a8bbbefec6d876821a93aeb0cc7442308957f36208f7414c15fbd2bedde5112.log:runtime.sigpanic()
ms-512-n-milvus-standalone-5c774577df-68mtq_milvus-ci_standalone-67bdd6184bbf3a06c167e0cbf1bbd087777fca5954b40d54738b9e0fe6d74ef4.log:	/usr/local/go/src/runtime/panic.go:1117 +0x72
ms-512-n-milvus-standalone-5c774577df-68mtq_milvus-ci_standalone-67bdd6184bbf3a06c167e0cbf1bbd087777fca5954b40d54738b9e0fe6d74ef4.log:runtime.sigpanic()
ms-512-n-milvus-standalone-5c774577df-68mtq_milvus-ci_standalone-788777601e8ffc8efa42c9a7eb3cf721c388786afdcc4a160d5762fe1fe002df.log:	/usr/local/go/src/runtime/panic.go:1117 +0x72
ms-512-n-milvus-standalone-5c774577df-68mtq_milvus-ci_standalone-788777601e8ffc8efa42c9a7eb3cf721c388786afdcc4a160d5762fe1fe002df.log:runtime.sigpanic()
ms-512-n-milvus-standalone-5c774577df-68mtq_milvus-ci_standalone-8cd7981cc4aa4b6accab1a46042d9ae86d1a83af488d02c0a2e923457a0b5901.log:	/usr/local/go/src/runtime/panic.go:1117 +0x72
ms-512-n-milvus-standalone-5c774577df-68mtq_milvus-ci_standalone-8cd7981cc4aa4b6accab1a46042d9ae86d1a83af488d02c0a2e923457a0b5901.log:runtime.sigpanic()
```

single panic info in one log file
``` 
fatal error: unexpected signal during runtime execution

[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7f9bb17550f1]



runtime stack:

runtime.throw(0x3cb1fe6, 0x2a)

        /usr/local/go/src/runtime/panic.go:1117 +0x72

runtime.sigpanic()

        /usr/local/go/src/runtime/signal_unix.go:718 +0x2e5



goroutine 402911 [syscall]:

runtime.cgocall(0x219ccda, 0xc003aab168, 0xc00510cb00)

        /usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc003aab138 sp=0xc003aab100 pc=0x833b5b

github.com/milvus-io/milvus/internal/querynode._Cfunc_Marshal(0xc00510cb00, 0xc0074ba110, 0x7f9b5417c1a0, 0x2, 0xc004ab0aa0, 0x1, 0x0, 0x0)

        _cgo_gotypes.go:553 +0x51 fp=0xc003aab168 sp=0xc003aab138 pc=0x20f1051

github.com/milvus-io/milvus/internal/querynode.marshal.func1(0xc00510cb00, 0xc0074ba110, 0xc003445170, 0x2, 0xc004ab0aa0, 0xc000000001, 0x1, 0x2)

        /go/src/github.com/milvus-io/milvus/internal/querynode/reduce.go:91 +0xe8 fp=0xc003aab1c0 sp=0xc003aab168 pc=0x21112e8

github.com/milvus-io/milvus/internal/querynode.marshal(0x60256e335b40001, 0x0, 0xc0074ba0f0, 0x2, 0x2, 0xc003445170, 0x2, 0xc004ab0aa0, 0x1, 0x2, ...)

        /go/src/github.com/milvus-io/milvus/internal/querynode/reduce.go:91 +0x434 fp=0xc003aab350 sp=0xc003aab1c0 pc=0x20fffb4

github.com/milvus-io/milvus/internal/querynode.(*queryShard).searchFollower(0xc0001a4a80, 0x3fcd9f0, 0xc00236f080, 0xc002985900, 0xc002b132f0, 0x1, 0x1, 0x60256e335b40001, 0x0, 0x0, ...)

        /go/src/github.com/milvus-io/milvus/internal/querynode/query_shard.go:538 +0x7a5 fp=0xc003aab780 sp=0xc003aab350 pc=0x20c3f85

github.com/milvus-io/milvus/internal/querynode.(*queryShard).search(0xc0001a4a80, 0x3fcd9f0, 0xc00236f080, 0xc002985900, 0x0, 0x0, 0x0)

        /go/src/github.com/milvus-io/milvus/internal/querynode/query_shard.go:358 +0x5e5 fp=0xc003aaba28 sp=0xc003aab780 pc=0x20c1025
```
```


### Anything else?

_No response_

**Comment by xige-16** [comment]
This issue has not been reproduced locally, I will continue to investigate it.

**Comment by xige-16** [comment]
pr#16815 may has fixed the issue.

**Comment by xige-16** [comment]
If the real topk statistics are not accurate when reducing, it will cause panic at https://github.com/milvus-io/milvus/blob/92b6293be4c0091cd2a3fbaf900f1212c9425ebe/internal/core/src/segcore/reduce_c.cpp#L180

**Comment by binbinlv** [comment]
Has not been reproduced for several days, fixed and closed.
