### ISSUE TITLE
[Bug]: Load collection rpc timeout `failed to execute task: call query coordinator LoadCollection: context canceled`

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#16824]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220506-67ce206c
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.1.0.dev39
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. Deploy milvus cluster with 2 queryNodes
2. Run the scale replica case 3 times: first scale out qn from 2 to 3; second scale in qn from 3 back to 2; the third time, load collection rpc timeout before scaling
```
<name>: scale_out_hJbMxERj
<partitions>: [{"name": "_default", "collection_name": "scale_out_hJbMxERj", "description": ""}]
<description>: 
<schema>: {
  auto_id: False
  description: 
  fields: [{
    name: int64
    description: 
    type: 5
    is_primary: True
    aut......  (api_request.py:27)
[2022-05-07 10:47:20,956 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [      int64   float varchar                                       float_vector
0         0     0.0       0  [0.10837128056110956, 0.11934682565642714, 0.1...
1         1     1.0       1  [0.1513788033690372, 0.07115828676421432, 0.14...
2         2     2.0       2  [0.07736674641591851, 0.099286343......, kwargs: {'timeout': 20} (api_request.py:55)
[2022-05-07 10:47:26,151 - DEBUG - ci_test]: (api_response) : (insert count: 3000, delete count: 0, upsert count: 0, timestamp: 433033483638538241)  (api_request.py:27)
[2022-05-07 10:47:28,985 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [      int64   float varchar                                       float_vector
0      3000  3000.0    3000  [0.13683284372574187, 0.13324091759978812, 0.0...
1      3001  3001.0    3001  [0.07756376472561917, 0.009671094645922414, 0....
2      3002  3002.0    3002  [0.0964004848486105, 0.0606957499......, kwargs: {'timeout': 20} (api_request.py:55)
[2022-05-07 10:47:32,563 - DEBUG - ci_test]: (api_response) : (insert count: 3000, delete count: 0, upsert count: 0, timestamp: 433033485316521986)  (api_request.py:27)
[2022-05-07 10:47:35,454 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [      int64   float varchar                                       float_vector
0      6000  6000.0    6000  [0.007537154795726843, 0.12755504530049896, 0....
1      6001  6001.0    6001  [0.11609520173156541, 0.08231975044226311, 0.1...
2      6002  6002.0    6002  [0.09136053311447388, 0.035089866......, kwargs: {'timeout': 20} (api_request.py:55)
[2022-05-07 10:47:38,885 - DEBUG - ci_test]: (api_response) : (insert count: 3000, delete count: 0, upsert count: 0, timestamp: 433033486968029186)  (api_request.py:27)
[2022-05-07 10:47:41,638 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 2, 20], kwargs: {} (api_request.py:55)
[2022-05-07 10:51:10,724 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 82, in handler
    raise e
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 695, in load_collection
    response = rf.result()
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1651891870.716647000","description":"Error received from peer ipv4:10.98.0.4:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nausicca/projects/milvus/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
    res = func(*args, **kwargs)
  File "/Users/nausicca/projects/milvus/tests/python_client/utils/api_request.py", line 56, in api_request
    return func(*arg, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 435, in load
    conn.load_collection(self._name, timeout=timeout, replica_number=replica_number, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 52, in handler
    raise MilvusException(Status.UNEXPECTED_ERROR, "rpc timeout")
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=rpc timeout)>
 (api_request.py:35)
[2022-05-07 10:51:10,724 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=rpc timeout)> (api_request.py:36)
[2022-05-07 10:51:10,724 - INFO - ci_test]: Test finished (test_query_node_scale.py:217)
FAILED
```

**scale replica case:**
```
        release_name = "mic-zong"
        mic = MilvusOperator()
        if mic.wait_for_healthy(release_name, constants.NAMESPACE, timeout=1800):
            host = mic.endpoint(release_name, constants.NAMESPACE).split(':')[0]
        else:
            raise MilvusException(message=f'Milvus healthy timeout 1800s')

        try:
            scale_querynode = 2/ 3/ 4
            connections.connect("default", host=host, port=19530)

            collection_w = ApiCollectionWrapper()
            collection_w.init_collection(name=cf.gen_unique_str("scale_out"), schema=cf.gen_default_collection_schema())

            # insert sealed segments
            for i in range(3):
                df = cf.gen_default_dataframe_data(start=i * ct.default_nb)
                collection_w.insert(df)
                assert collection_w.num_entities == (i + 1) * ct.default_nb

            collection_w.load(replica_number=2)

            @counter
            def do_search():
                """ do search """
                search_res, is_succ = collection_w.search(cf.gen_vectors(1, ct.default_dim),
                                                          ct.default_float_vec_field_name, ct.default_search_params,
                                                          ct.default_limit, check_task=CheckTasks.check_nothing)
                assert len(search_res) == 1
                return search_res, is_succ

            def loop_search():
                """ continuously search """
                while True:
                    do_search()

            threading.Thread(target=loop_search, args=(), daemon=True).start()

            # scale out
            mic.upgrade(release_name, {'spec.components.queryNode.replicas': scale_querynode}, constants.NAMESPACE)
            mic.wait_for_healthy(release_name, constants.NAMESPACE)
            wait_pods_ready(constants.NAMESPACE, f"app.kubernetes.io/instance={release_name}")
            log.debug("Scale out querynode success")

            time.sleep(50)
            scale_common.check_succ_rate(do_search)
            log.debug("Scale out test finished")
```
Server logs:
[mic_logs.tar.gz](https://github.com/milvus-io/milvus/files/8644365/mic_logs.tar.gz)

### Expected Behavior

Load sccessfully

**Comment by congqixia** [comment]
Hi @ThreadDao does this problem still exist?

**Comment by ThreadDao** [comment]
> Hi @ThreadDao does this problem still exist?

wow! no reproduce `master-20220520-d525e955`
