### ISSUE TITLE
[Bug]: Load collection will fail with rpc timeout after running the multi replicas chaos test multiple times

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#16851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220507-c7935d1a
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.0.dev48
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2022-05-09 14:57:34 - ERROR - pymilvus.decorators]: grpc RpcError: [load_collection], <_MultiThreadedRendezvous: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded>, <Time:{'RPC start': '2022-05-09 14:57:14.935122', 'gRPC error': '2022-05-09 14:57:34.930281'}> (decorators.py:81)
[2022-05-09 14:57:34 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/zilliz/opt/anaconda3/envs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/opt/anaconda3/envs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 82, in handler
    raise e
  File "/Users/zilliz/opt/anaconda3/envs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/Users/zilliz/opt/anaconda3/envs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 711, in load_collection
    response = rf.result()
  File "/Users/zilliz/opt/anaconda3/envs/milvus/lib/python3.8/site-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "{"created":"@1652079454.929754000","description":"Error received from peer ipv4:10.96.240.3:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zilliz/workspace/backup/milvus/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
    res = func(*args, **kwargs)
  File "/Users/zilliz/workspace/backup/milvus/tests/python_client/utils/api_request.py", line 56, in api_request
    return func(*arg, **kwargs)
  File "/Users/zilliz/opt/anaconda3/envs/milvus/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 449, in load
    conn.load_collection(self._name, timeout=timeout, replica_number=replica_number, **kwargs)
  File "/Users/zilliz/opt/anaconda3/envs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 52, in handler
    raise MilvusException(Status.UNEXPECTED_ERROR, "rpc timeout")
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=rpc timeout)>
 (api_request.py:35)
[2022-05-09 14:57:34 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=rpc timeout)> (api_request.py:36)

```

### Steps To Reproduce

```markdown
running the multi replicas chaos test(https://github.com/milvus-io/milvus/blob/master/tests/python_client/chaos/test_chaos_multi_replicas.py) multiple times
```

**Comment by zhuwenxing** [comment]
maybe the file is too big, it can not upload to github.
you can get it by the google driver link https://drive.google.com/file/d/14cjbhrLfyxphR9GkjN1dULO0pSzAzMAj/view?usp=sharing

**Comment by zhuwenxing** [comment]
need to check the behavior on the latest image version

**Comment by xiaofan-luan** [comment]
mark as open
