### ISSUE TITLE
[Bug]: Error in creating index, "describe_index() got multiple values for argument 'index_name'"

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#16888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):2.1.0.dev54
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

testcase：
```
[2022-05-10T09:46:46.459Z] index_param = {'index_type': 'FLAT', 'metric_type': 'L2', 'params': {'nlist': 128}}

[2022-05-10T09:46:46.459Z] 

[2022-05-10T09:46:46.459Z]     @pytest.mark.tags(CaseLabel.L1)

[2022-05-10T09:46:46.459Z]     @pytest.mark.parametrize("data", [cf.gen_default_list_data(nb=3000)])

[2022-05-10T09:46:46.459Z]     @pytest.mark.parametrize("index_param", cf.gen_simple_index())

[2022-05-10T09:46:46.459Z]     def test_partition_delete_indexed_data(self, data, index_param):

[2022-05-10T09:46:46.459Z]         """

[2022-05-10T09:46:46.459Z]         target: verify delete entities with an expression condition from an indexed partition

[2022-05-10T09:46:46.459Z]         method: 1. create collection

[2022-05-10T09:46:46.459Z]                 2. create an index

[2022-05-10T09:46:46.459Z]                 3. create a partition

[2022-05-10T09:46:46.459Z]                 4. insert same data

[2022-05-10T09:46:46.459Z]                 5. delete entities with an expression condition

[2022-05-10T09:46:46.459Z]         expected: delete successfully

[2022-05-10T09:46:46.459Z]         issue #15456

[2022-05-10T09:46:46.459Z]         """

[2022-05-10T09:46:46.459Z]         # create collection

[2022-05-10T09:46:46.459Z]         collection_w = self.init_collection_wrap()

[2022-05-10T09:46:46.459Z]     

[2022-05-10T09:46:46.459Z]         # create index of collection

[2022-05-10T09:46:46.459Z] >       collection_w.create_index(ct.default_float_vec_field_name, index_param)

[2022-05-10T09:46:46.459Z] 

[2022-05-10T09:46:46.459Z] testcases/test_partition.py:968: 
```
error log：

```
[2022-05-10T09:46:46.460Z] [2022-05-10 09:46:36 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['float_vector', {'index_type': 'FLAT', 'metric_type': 'L2', 'params': {'nlist': 128}}], kwargs: {'timeout': 40, 'index_name': '_default_idx'} (api_request.py:55)

[2022-05-10T09:46:46.460Z] [2022-05-10 09:46:36 - ERROR - pymilvus.decorators]: Unexcepted error: [describe_index], describe_index() got multiple values for argument 'index_name', <Time: {'RPC start': '2022-05-10 09:46:36.270363', 'Exception': '2022-05-10 09:46:36.270380'}> (decorators.py:85)

[2022-05-10T09:46:46.460Z] [2022-05-10 09:46:36 - ERROR - pymilvus.decorators]: Unexcepted error: [create_index], describe_index() got multiple values for argument 'index_name', <Time: {'RPC start': '2022-05-10 09:46:36.266416', 'Exception': '2022-05-10 09:46:36.270631'}> (decorators.py:85)

[2022-05-10T09:46:46.460Z] [2022-05-10 09:46:36 - ERROR - ci_test]: Traceback (most recent call last):

[2022-05-10T09:46:46.460Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper

[2022-05-10T09:46:46.460Z]     res = func(*args, **kwargs)

[2022-05-10T09:46:46.460Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 56, in api_request

[2022-05-10T09:46:46.460Z]     return func(*arg, **kwargs)

[2022-05-10T09:46:46.460Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 1049, in create_index

[2022-05-10T09:46:46.460Z]     timeout=timeout, **kwargs)

[2022-05-10T09:46:46.460Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 56, in handler

[2022-05-10T09:46:46.460Z]     raise e

[2022-05-10T09:46:46.460Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 41, in handler

[2022-05-10T09:46:46.460Z]     return func(self, *args, **kwargs)

[2022-05-10T09:46:46.460Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 86, in handler

[2022-05-10T09:46:46.460Z]     raise e

[2022-05-10T09:46:46.460Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler

[2022-05-10T09:46:46.460Z]     return func(*args, **kwargs)

[2022-05-10T09:46:46.460Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 604, in create_index

[2022-05-10T09:46:46.460Z]     raise err

[2022-05-10T09:46:46.460Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 593, in create_index

[2022-05-10T09:46:46.460Z]     index_desc = self.describe_index(collection_name, index_name, timeout=timeout, **kwargs)

[2022-05-10T09:46:46.460Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 56, in handler

[2022-05-10T09:46:46.460Z]     raise e

[2022-05-10T09:46:46.460Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 41, in handler

[2022-05-10T09:46:46.460Z]     return func(self, *args, **kwargs)

[2022-05-10T09:46:46.460Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 86, in handler

[2022-05-10T09:46:46.460Z]     raise e

[2022-05-10T09:46:46.460Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler

[2022-05-10T09:46:46.460Z]     return func(*args, **kwargs)

[2022-05-10T09:46:46.461Z] TypeError: describe_index() got multiple values for argument 'index_name'

[2022-05-10T09:46:46.461Z]  (api_request.py:35)

[2022-05-10T09:46:46.461Z] [2022-05-10 09:46:36 - ERROR - ci_test]: (api_response) : describe_index() got multiple values for argument 'index_name' (api_request.py:36)
```

Jenkins： https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-16884/2/pipeline

**Comment by jingkl** [comment]
pr：#16884

**Comment by xige-16** [comment]
Because the describe_index interface in grpc_handler.py needs to pass in the parameter index_name, if there is also an index_name parameter in kwargs, it will prompt dup index_name in params.

**Comment by jingkl** [comment]
Verified, turn off issue
