### ISSUE TITLE
[Bug]: [memory] The querynode OOMKilled while loading collection with insufficient memory

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#16887]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220510-2d0f908d
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.1.0.dev39
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others: 
queryNode:
  replicas: 2
    resources:
      limits:
        memory: 2Gi
```

### Current Behavior

1. Deploy milvus cluster with 2 querynodes, and limit memory 2Gi
2. Create a collection and insert 250,000 entities and dim 512 (about 250MB size)
3.  Load the collection with 2 replica numbers and one of the querynode OOMKilled and CrashLoopBackOff
 `load` does not throw an exception and actually fails; 
  `query` return empty result; 
 `get_replicas` return correct expected replicas info
 `get_query_segment_info` said that xxx querynode is offline

A few minutes later, the OOMKilled querynode restart and running, and query shows collection not loaded into memory
```
[2022-05-10 17:10:29,127 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 2, 20], kwargs: {} (api_request.py:55)
[2022-05-10 17:10:49,826 - DEBUG - ci_test]: (api_response) : None  (api_request.py:27)
[2022-05-10 17:10:49,826 - DEBUG - ci_test]: (api_request)  : [Collection.get_replicas] args: [20], kwargs: {} (api_request.py:55)
[2022-05-10 17:10:49,869 - DEBUG - ci_test]: (api_response) : Replica groups:
- Group: <group_id:433107190231859215>, <group_nodes:(7,)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_433107334371475457v0>, <shard_leader:7>, <shard_nodes:[7]>, Shard: <channel_name:by-dev-rootcoord-dml_1_433107334371475457v1>, <shard_leader:7>, <shard_nodes:[7]>]>
- Grou......  (api_request.py:27)
[2022-05-10 17:10:49,869 - DEBUG - ci_test]: Replica groups:
- Group: <group_id:433107190231859215>, <group_nodes:(7,)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_433107334371475457v0>, <shard_leader:7>, <shard_nodes:[7]>, Shard: <channel_name:by-dev-rootcoord-dml_1_433107334371475457v1>, <shard_leader:7>, <shard_nodes:[7]>]>
- Group: <group_id:433107190231859214>, <group_nodes:(12,)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_1_433107334371475457v1>, <shard_leader:12>, <shard_nodes:[12]>, Shard: <channel_name:by-dev-rootcoord-dml_0_433107334371475457v0>, <shard_leader:12>, <shard_nodes:[12]>]> (test_chaos_memory_stress.py:297)
[2022-05-10 17:10:49,870 - DEBUG - ci_test]: (api_request)  : [Collection.query] args: ['int64 in [0]', None, None, 20], kwargs: {} (api_request.py:55)
[2022-05-10 17:10:55,265 - DEBUG - ci_test]: (api_response) : []  (api_request.py:27)
```

**Server logs:** 
[mic_logs.tar.gz](https://github.com/milvus-io/milvus/files/8660466/mic_logs.tar.gz)

The memory usage of the never OOMKilled querynode: 
![image](https://user-images.githubusercontent.com/27288593/167602853-ab25141d-b630-4461-8942-55a13f042f00.png)

The memory usage of the querynodes when memory is sufficient (limit querynode.memory.limit: 12Gi):
![image](https://user-images.githubusercontent.com/27288593/167603865-8498460e-014c-4a84-8261-df7b7ee38328.png)
![image](https://user-images.githubusercontent.com/27288593/167603995-fcbbae51-7fc7-4110-b447-3b8f632953a9.png)

### Expected Behavior

Loading a collection can throw an exception when there is not enough memory

**Comment by congqixia** [comment]
/unassign
/assign @xige-16 
Might related to #16150 , load memory problem.

**Comment by xiaofan-luan** [comment]
I'm working on a dynamic gc tuner which could help a little bit on this issue

**Comment by yah01** [comment]
> I'm working on a dynamic gc tuner which could help a little bit on this issue

Also, loading the segments' fields concurrently should help on this, which allows the runtime to GC loaded fields. #17273

**Comment by yah01** [comment]
@ThreadDao 
#17421 could reduce the memory usage while loading.
Saw the data you inserted should be about 488MiB (not 250 MiB), I'm not sure whether 2GiB is enough to load as not causing OOM

**Comment by yanliang567** [comment]
@ThreadDao could you please help to verify the fix

**Comment by ThreadDao** [comment]
image `master-20220614-f9553970`
1. Deploy cluster with 2 querynodes and limit their memory to 2 Gi
2. If Insert 250000 entities of dim 512, loading 2 replicas successfully as querynode's memory is sufficient
3. Insert 500000 entities of dim 512，load collection with 2 replicas and then two querynodes OOMKilled and restart successfully, querycoord crash and failed to restart.
 
See this issue #17253  for details. I will re-verify this issue after 17253 fixed.
```
[2022/06/14 16:17:11.744 +00:00] [ERROR] [global_meta_broker.go:522] ["QueryCoord release reference lock on segments failed"] [segmentIDs="[433906734591377409,433906722650456065,433906781554475009,433906714668433410,433906722637611009,433906741774123009,433906769508958210,433906786042056001,433906786154840065,433906790060785665,433906718482628609,433906707629867010,433906741787230209,433906769508958209,433906786181316610,433906801280811010,433906781554475010,433906707616497666,433906722637611010,433906741787230210,433906769495851009,433906777229099009,433906790074155009,433906737998987266,433906711089905666,433906797546831873,433906793586622466,433906726569508865,433906797519044609,433906797534773249,433906711103012866,433906805344567297,433906730527883266,433906714668433409,433906714655064065,433906718469259265,433906801293918210,433906737973035010,433906714655064066,433906769495851010,433906730515038210,433906793600253953,433906797637009409,433906805331722241,433906707629867009,433906722663563265,433906805356888065,433906718469259266,433906781475569665,433906773493547010,433906777215991809,433906726595985409,433906790074155010,433906773493547009,433906790048727041,433906801293918209,433906805356888066,433906793600253954,433906773493547011,433906781475569666,433906734565100865,433906737973035009,433906801280811009,433906711089905665,433906726569508866,433906777229099010,433906741774123010,433906726582616065,433906730527883265,433906734578008065,433906777176670209,433906711103012865,433906786181316609,433906773510062081,433906793586622465,433906707616497665,433906718482628610,433906730515038209,433906737998987265,433906734591377410]"] ["failed reason"="etcdserver: too many operations in txn request"] [stack="github.com/milvus-io/milvus/internal/querycoord.(*globalMetaBroker).releaseSegmentReferLock.func1\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/global_meta_broker.go:522\ngithub.com/milvus-io/milvus/internal/util/retry.Do\n\t/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:37\ngithub.com/milvus-io/milvus/internal/querycoord.(*globalMetaBroker).releaseSegmentReferLock\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/global_meta_broker.go:513\ngithub.com/milvus-io/milvus/internal/querycoord.(*loadSegmentTask).postExecute\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:1270\ngithub.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processTask.func2\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:521\ngithub.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processTask\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:550\ngithub.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processActivateTaskLoop.func1\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:872"]
panic: All attempts results:
attempt #1:etcdserver: too many operations in txn request
attempt #2:etcdserver: too many operations in txn request
attempt #3:etcdserver: too many operations in txn request
attempt #4:etcdserver: too many operations in txn request
attempt #5:etcdserver: too many operations in txn request
attempt #6:etcdserver: too many operations in txn request
attempt #7:etcdserver: too many operations in txn request
attempt #8:context deadline exceeded


goroutine 235 [running]:
github.com/milvus-io/milvus/internal/querycoord.(*loadSegmentTask).postExecute(0xc0012ed450, 0x42ace70, 0xc000286200, 0x1, 0x2167959)
	/go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:1271 +0x27b
github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processTask.func2(0x42d06e0, 0xc0006325a0, 0x42e4650, 0xc0012ed450, 0xc000d09b40)
	/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:521 +0x126
github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processTask(0xc000e88b00, 0x42e4650, 0xc0012ed450, 0x4273820, 0xc000cba9d0)
	/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:550 +0xde5
github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processActivateTaskLoop.func1(0xc000e88b00, 0x42e4650, 0xc0012ed450)
	/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:872 +0x3f
created by github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processActivateTaskLoop
	/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:871 +0x151
```

**Comment by ThreadDao** [comment]
Image `master-20220616-00089de2`, fixed
Loading collection with insufficient memory：
- the two querynodes not OOMKilled
- Although the client does not throw exception, the server loaded failed actually.
- So call `get_replicas`、`loading_progress` gets not loaded exception.
- `get_query_segment_info` not thrown any exception but return empty list.

 After increasing the memory limit, everything is fine!
