### ISSUE TITLE
SQ8H search failed run on base dataset sift-1b

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#1689]
**Describe the bug**
```
10:41:58  2020-03-18:02:41:57,993 INFO     [runner.py:196] Start query, query params: top-k: 1, nq: 200, actually length of vectors: 200
10:41:58  2020-03-18:02:41:57,993 INFO     [runner.py:198] Start run query, run 1 of 2
10:42:11  2020-03-18:02:42:10,608 ERROR    [client.py:71] out of memory: CPU2GPU:1
10:42:11  2020-03-18:02:42:10,608 ERROR    [main.py:69] Status not ok
10:42:11  2020-03-18:02:42:10,611 ERROR    [main.py:70] Traceback (most recent call last):
10:42:11    File "main.py", line 67, in queue_worker
10:42:11      runner.run(run_type, collection)
10:42:11    File "/home/jenkins/agent/workspace/milvus-debug/milvus_benchmark/k8s_runner.py", line 195, in run
10:42:11      res = self.do_query(milvus_instance, collection_name, top_ks, nqs, run_count, search_param)
10:42:11    File "/home/jenkins/agent/workspace/milvus-debug/milvus_benchmark/runner.py", line 200, in do_query
10:42:11      query_res = milvus.query(vectors, top_k, search_param=search_param)
10:42:11    File "/home/jenkins/agent/workspace/milvus-debug/milvus_benchmark/client.py", line 31, in wrapper
10:42:11      result = func(*args, **kwargs)
10:42:11    File "/home/jenkins/agent/workspace/milvus-debug/milvus_benchmark/client.py", line 145, in query
10:42:11      self.check_status(status)
10:42:11    File "/home/jenkins/agent/workspace/milvus-debug/milvus_benchmark/client.py", line 72, in check_status
10:42:11      raise Exception("Status not ok")
10:42:11  Exception: Status not ok
10:42:11  
```

```
Error, can't get gpu: -1resource
2020-03-18 00:16:55,806 | ERROR | default | [ENGINE] Error in void faiss::gpu::allocMemorySpaceV(faiss::gpu::MemorySpace, void**, size_t) at gpu/utils/MemorySpace.cpp:26: Error: 'err == cudaSuccess' failed: failed to cudaMalloc 8388608 bytes (error 2 out of memory)
2020-03-18 00:16:55,806 | ERROR | default | [WRAPPER] Error in virtual knowhere::DatasetPtr knowhere::IVF::Search(const DatasetPtr&, const Config&) at IndexIVF.cpp:139: Error in virtual void knowhere::IVFSQHybrid::search_impl(int64_t, const float*, int64_t, float*, int64_t*, const Config&) at IndexIVFSQHybrid.cpp:124: Hybrid Search Error, can't get gpu: -1resource
2020-03-18 00:16:55,806 | ERROR | default | [ENGINE] Search error:Error in virtual knowhere::DatasetPtr knowhere::IVF::Search(const DatasetPtr&, const Config&) at IndexIVF.cpp:139: Error in virtual void knowhere::IVFSQHybrid::search_impl(int64_t, const float*, int64_t, float*, int64_t*, const Config&) at IndexIVFSQHybrid.cpp:124: Hybrid Search Error, can't get gpu: -1resource
2020-03-18 00:16:55,846 | ERROR | default | [ENGINE] Error in void faiss::gpu::allocMemorySpaceV(faiss::gpu::MemorySpace, void**, size_t) at gpu/utils/MemorySpace.cpp:26: Error: 'err == cudaSuccess' failed: failed to cudaMalloc 8388608 bytes (error 2 out of memory)
2020-03-18 00:16:55,847 | ERROR | default | [WRAPPER] Error in virtual knowhere::DatasetPtr knowhere::IVF::Search(const DatasetPtr&, const Config&) at IndexIVF.cpp:139: Error in virtual void knowhere::IVFSQHybrid::search_impl(int64_t, const float*, int64_t, float*, int64_t*, const Config&) at IndexIVFSQHybrid.cpp:124: Hybrid Search Error, can't get gpu: -1resource
2020-03-18 00:16:55,848 | ERROR | default | [ENGINE] Search error:Error in virtual knowhere::DatasetPtr knowhere::IVF::Search(const DatasetPtr&, const Config&) at IndexIVF.cpp:139: Error in virtual void knowhere::IVFSQHybrid::search_impl(int64_t, const float*, int64_t, float*, int64_t*, const Config&) at IndexIVFSQHybrid.cpp:124: Hybrid Search Error, can't get gpu: -1resource
2020-03-18 00:16:55,852 | ERROR | default | [SERVER] Request failed with code: Error code(50003): Error in virtual knowhere::DatasetPtr knowhere::IVF::Search(const DatasetPtr&, const Config&) at IndexIVF.cpp:139: Error in virtual void knowhere::IVFSQHybrid::search_impl(int64_t, const float*, int64_t, float*, int64_t*, const Config&) at IndexIVFSQHybrid.cpp:124: Hybrid Search Error, can't get gpu: -1resource
```

**Steps/Code to reproduce behavior**
Run search with GPU-version, 
gpu-threshold: 200
gpu-cache-size: 4,6
nq: 200

**Expected behavior**

**Environment details**
2 GPU-card(8G)

**Screenshots**

**Additional context**

**Comment by JinHai-CN** [comment]
I suppose the GPU cache size is too big and GPU memory size isn't bigger for SQ8H searching.

**Comment by cydrain** [comment]
milvusdb/daily-build:ubuntu18.04-gpu-20200315   ==> can reproduce

Welcome to Milvus!
Milvus Release version: v0.7.0, built at 2020-03-15 12:47.26, with OpenBLAS library.
You are using Milvus GPU edition
Last commit id: 6c826c1308cfa0982652ccb687c87e6dd8c1b727

2020-03-20 17:41:51,668 | ERROR | default | [ENGINE] Error in void faiss::gpu::allocMemorySpaceV(faiss::gpu::MemorySpace, void**, size_t) at gpu/utils/MemorySpace.cpp:26: Error: 'err == cudaSuccess' failed: failed to cudaMalloc 8388608 bytes (error 2 out of memory)
2020-03-20 17:41:51,707 | ERROR | default | [ENGINE] Error in void faiss::gpu::allocMemorySpaceV(faiss::gpu::MemorySpace, void**, size_t) at gpu/utils/MemorySpace.cpp:26: Error: 'err == cudaSuccess' failed: failed to cudaMalloc 8388608 bytes (error 2 out of memory)
2020-03-20 17:41:51,712 | ERROR | default | [SERVER] Request failed with code: Error code(30117): out of memory: CPU2GPU:0


=====================================================================
milvusdb/daily-build:ubuntu18.04-gpu-20200314  ==> no this issue

Welcome to Milvus!
Milvus Release version: v0.7.0, built at 2020-03-14 10:22.02, with OpenBLAS library.
You are using Milvus GPU edition
Last commit id: 1b60e3bca6bd99c01f4825ba1d3c0275ca92ca1c

**Comment by cydrain** [comment]
this issue is caused by PR#1648

**Comment by del-zhenwu** [comment]
log path:
```
/test/milvus/db_data_7/sift_1b_2048_128_l2_sq8h_wal/logs/milvus-20-03-26-23:23-error.log
```
commit id: 207b854c3f331555e92d95aacba697d3ad823bd2

**Comment by del-zhenwu** [comment]
config items:
```
        cache_config.cpu_cache_capacity: 150
        engine_config.use_blas_threshold: 1100
        engine_config.gpu_search_threshold: 1
        gpu_resource_config.enable: true
        gpu_resource_config.cache_capacity: 6
        gpu_resource_config.search_resources:
          - gpu0
          - gpu1
        gpu_resource_config.build_index_resources:
          - gpu0
          - gpu1
```

**Comment by del-zhenwu** [comment]
re-produced on athena(12G/GPU)

**Comment by del-zhenwu** [comment]
Also re-produced with dataset: `sift-50m`, log path:
```
/test/milvus/db_data_7/sift_50m_2048_128_l2_ivf_wal/logs/milvus-20-03-27-00:29-error.log
```
config_item:
```
00:30:26  2020-03-26:16:30:25,638 DEBUG    [k8s_runner.py:83] {'server': {'db_config.primary_path': '/test/milvus/db_data_7/sift_50m_2048_128_l2_ivf_wal', 'cache_config.cpu_cache_capacity': 64, 'engine_config.use_blas_threshold': 0, 'engine_config.gpu_search_threshold': 200, 'gpu_resource_config.enable': True, 'gpu_resource_config.cache_capacity': 6, 'gpu_resource_config.search_resources': ['gpu0', 'gpu1'], 'gpu_resource_config.build_index_resources': ['gpu0', 'gpu1'], 'wal_enable': True}, 'collection_name': 'sift_50m_2048_128_l2', 'run_count': 2, 'top_ks': [1, 10, 100, 1000], 'nqs': [1, 10, 100, 200, 500, 1000], 'search_params': [{'nprobe': 8}, {'nprobe': 32}]}
```

**Comment by del-zhenwu** [comment]
fixed
