### ISSUE TITLE
[Bug]: Create index failed with error message `context canceled` after Milvus recovered from indexnode pod kill chaos

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#16932]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220511-a8b81e21
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.0.dev56 
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
check collection Checker__QGjoo9R1
collection is exist

Create collection...

Insert 3000 vectors cost 0.4657 seconds

Get collection entities...
[21](https://github.com/milvus-io/milvus/runs/6393914832?check_suite_focus=true#step:15:21)000

Get collection entities cost 3.1080 seconds

Create index...
Traceback (most recent call last):
  File "chaos/scripts/verify_all_collections.py", line 1[24](https://github.com/milvus-io/milvus/runs/6393914832?check_suite_focus=true#step:15:24), in <module>
    hello_milvus(collection_name)
  File "chaos/scripts/verify_all_collections.py", line 69, in hello_milvus
    collection.create_index(field_name="float_vector", index_params=default_index)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 1053, in create_index
    return conn.create_index(self._name, field_name, index_params,
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 650, in create_index
    raise MilvusException(Status.UNEXPECTED_ERROR, fail_reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=context canceled)>
```

### Expected Behavior

all test cases passed

### Steps To Reproduce

```markdown
see https://github.com/milvus-io/milvus/runs/6393914832?check_suite_focus=true
```

### Anything else?

failed job: https://github.com/milvus-io/milvus/runs/6393914832?check_suite_focus=true

log: https://github.com/milvus-io/milvus/suites/6468587424/artifacts/239168129

**Comment by zhuwenxing** [comment]
In Jenkins pipeline, there is a same issue for this case.
```
21:29:16  check collection Checker__E7EYFfE1
21:29:16  collection is exist
21:29:16  
21:29:16  Create collection...
21:29:16  
21:29:16  Insert 3000 vectors cost 0.1997 seconds
21:29:16  
21:29:16  Get collection entities...
21:29:16  21000
21:29:16  
21:29:16  Get collection entities cost 3.0450 seconds
21:29:16  
21:29:16  Create index...
21:29:16  Traceback (most recent call last):
21:29:16    File "scripts/verify_all_collections.py", line 124, in <module>
21:29:16      hello_milvus(collection_name)
21:29:16    File "scripts/verify_all_collections.py", line 69, in hello_milvus
21:29:16      collection.create_index(field_name="float_vector", index_params=default_index)
21:29:16    File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 1049, in create_index
21:29:16      timeout=timeout, **kwargs)
21:29:16    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 56, in handler
21:29:16      raise e
21:29:16    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 41, in handler
21:29:16      return func(self, *args, **kwargs)
21:29:16    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 74, in handler
21:29:16      raise e
21:29:16    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 70, in handler
21:29:16      return func(*args, **kwargs)
21:29:16    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 645, in create_index
21:29:16      raise MilvusException(Status.UNEXPECTED_ERROR, fail_reason)
21:29:16  pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Get "http://indexnode-pod-kill-4664-minio:9000/milvus-bucket/file/insert_log/433134065784455169/433134065784455170/433134067462176770/103/433134068143489028": context canceled)>
```
failed job: http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/4664/pipeline
log: [artifacts-indexnode-pod-kill-4664-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/8674598/artifacts-indexnode-pod-kill-4664-server-logs.tar.gz)

**Comment by zhuwenxing** [comment]
failed job: https://github.com/milvus-io/milvus/runs/6442743231?check_suite_focus=true
log: https://github.com/milvus-io/milvus/suites/6514060864/artifacts/242431755
This issue will appear steadily, so increase the level.

**Comment by zhuwenxing** [comment]
failed job: https://github.com/milvus-io/milvus/runs/6513048409?check_suite_focus=true
log: https://github.com/milvus-io/milvus/suites/6580724775/artifacts/246629822

**Comment by xiaocai2333** [comment]
From the IndexCoord log, there is an index build failed. But the log of the indexnode before being killed is not collected, so it is not certain why it failed.
If you can reproduce it in Jenkins, please collect the log of indexnode before being killed. @zhuwenxing

**Comment by xiaocai2333** [comment]
IndexCoord log
```
[2022/05/19 18:57:07.640 +00:00] [DEBUG] [index_coord.go:509] ["IndexCoord get index states success"] [total=6] [None=0] [Unissued=0] [InProgress=0] [Finished=5] [Failed=1]
```

**Comment by zhuwenxing** [comment]
The pipeline http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/5163/pipeline
This is all indexnode log
[chaos-indexnode.zip](https://github.com/milvus-io/milvus/files/8739953/chaos-indexnode.zip)

[artifacts-indexnode-pod-kill-5163-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/8739970/artifacts-indexnode-pod-kill-5163-server-logs.tar.gz)

**Comment by xiaocai2333** [comment]
indexnode log:
```
[2022/05/20 11:08:55.303 +00:00] [WARN] [minio_chunk_manager.go:188] ["failed to read object"] [path=file/insert_log/433335784140963841/433335784140963842/433335785661399041/103/433335786303651844] [error="context canceled"]

[2022/05/20 11:08:55.303 +00:00] [ERROR] [parallel.go:87] [loadKey] [error="context canceled"] [idx=0] [stack="github.com/milvus-io/milvus/internal/util/funcutil.ProcessFuncParallel.func3\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/parallel.go:87"]

[2022/05/20 11:08:55.303 +00:00] [DEBUG] [parallel.go:51] [loadKey] ["time cost"=169.999µs]

[2022/05/20 11:08:55.303 +00:00] [WARN] [task.go:373] ["loadKey from minio failed"] [error="context canceled"]

[2022/05/20 11:08:55.303 +00:00] [ERROR] [task.go:560] ["IndexNode IndexBuildTask Execute buildIndex failed"] [buildId=433335810101870596] [error="context canceled"] [stack="github.com/milvus-io/milvus/internal/indexnode.(*IndexBuildTask).Execute\n\t/go/src/github.com/milvus-io/milvus/internal/indexnode/task.go:560\ngithub.com/milvus-io/milvus/internal/indexnode.(*TaskScheduler).processTask\n\t/go/src/github.com/milvus-io/milvus/internal/indexnode/task_scheduler.go:277\ngithub.com/milvus-io/milvus/internal/indexnode.(*TaskScheduler).indexBuildLoop.func1\n\t/go/src/github.com/milvus-io/milvus/internal/indexnode/task_scheduler.go:296"]

[2022/05/20 11:08:55.305 +00:00] [DEBUG] [task.go:285] ["IndexNode IndexBuildTask PostExecute..."] [buildId=433335810101870596]

```

**Comment by zhuwenxing** [comment]
Verified and passed in version `master-20220524-a0cef3a0`
