### ISSUE TITLE
[Bug]: Create index failed with error message `Client disconnected before response was ready` after Milvus recovered from minio pod kill chaos

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#16933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220511-a8b81e21
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus==2.1.0.dev56
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
check collection Checker__67iYj35l
collection is exist

Create collection...

Insert 3000 vectors cost 0.5159 seconds

Get collection entities...
21000

Get collection entities cost 2.6348 seconds

Create index...
Traceback (most recent call last):
  File "chaos/scripts/verify_all_collections.py", line [124](https://github.com/milvus-io/milvus/runs/6393915514?check_suite_focus=true#step:15:124), in <module>
    hello_milvus(collection_name)
  File "chaos/scripts/verify_all_collections.py", line 69, in hello_milvus
    collection.create_index(field_name="float_vector", index_params=default_index)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 1053, in create_index
    return conn.create_index(self._name, field_name, index_params,
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 650, in create_index
    raise MilvusException(Status.UNEXPECTED_ERROR, fail_reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Client disconnected before response was ready)>

```

### Steps To Reproduce

```markdown
see https://github.com/milvus-io/milvus/runs/6393915514?check_suite_focus=true
```

### Anything else?

failed job: https://github.com/milvus-io/milvus/runs/6393915514?check_suite_focus=true
log: https://github.com/milvus-io/milvus/suites/6468587424/artifacts/239168130

**Comment by zhuwenxing** [comment]
In the Jenkins pipeline, this case also failed, but the error message is `Server not initialized, please try again`.
failed job: http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/4671/pipeline
log:
[artifacts-minio-pod-kill-4671-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/8674557/artifacts-minio-pod-kill-4671-server-logs.tar.gz)

**Comment by zhuwenxing** [comment]
failed job: https://github.com/milvus-io/milvus/runs/6442743433?check_suite_focus=true
log: https://github.com/milvus-io/milvus/suites/6514060864/artifacts/242431756
This issue will appear steadily, so increase the level

**Comment by zhuwenxing** [comment]
Not reproduced in version `master-20220524-a0cef3a0`.
If there is any fix, please comment here @xiaocai2333

**Comment by xiaocai2333** [comment]
maybe similar as #16932 
If reproduce it , comment here.

**Comment by zhuwenxing** [comment]
Not reproduced, so close it
