### ISSUE TITLE
[Bug]: Search raises error with message `query shard xxx does not exist` after restarting Milvus

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#16948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220511-a8b81e21
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.1.0.dev50
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
11:09:39  collection name: task_1_IVF_SQ8
11:09:39  release collection
11:09:39  load collection
11:09:39  load time: 1.6335
11:09:39  {'metric_type': 'L2', 'params': {'nprobe': 10}}
11:09:39  
11:09:39  Search...
11:09:39  Traceback (most recent call last):
11:09:39    File "action_after_reinstall.py", line 86, in <module>
11:09:39      task_1(data_size, host)
11:09:39    File "action_after_reinstall.py", line 16, in task_1
11:09:39      load_and_search(prefix)
11:09:39    File "/home/jenkins/agent/workspace/tests/python_client/deploy/scripts/utils.py", line 158, in load_and_search
11:09:39      "count > 500", output_fields=["count", "random_value"], timeout=120
11:09:39    File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 688, in search
11:09:39      partition_names, output_fields, timeout, round_decimal, **kwargs)
11:09:39    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 56, in handler
11:09:39      raise e
11:09:39    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 41, in handler
11:09:39      return func(self, *args, **kwargs)
11:09:39    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 74, in handler
11:09:39      raise e
11:09:39    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 70, in handler
11:09:39      return func(*args, **kwargs)
11:09:39    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 21, in handler
11:09:39      return func(self, *args, **kwargs)
11:09:39    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 497, in search
11:09:39      return self._execute_search_requests(requests, timeout, **_kwargs)
11:09:39    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 74, in handler
11:09:39      raise e
11:09:39    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 70, in handler
11:09:39      return func(*args, **kwargs)
11:09:39    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 444, in _execute_search_requests
11:09:39      raise pre_err
11:09:39    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 435, in _execute_search_requests
11:09:39      raise MilvusException(response.status.error_code, response.status.reason)
11:09:39  pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=12, reason=query shard(channel)  by-dev-rootcoord-dml_4_433146928313663489v0  does not exist
11:09:39  )>
```

### Expected Behavior

all test cases passed

### Steps To Reproduce

```markdown
see http://10.100.32.144:8080/blue/organizations/jenkins/deploy_test/detail/deploy_test/559/pipeline
```

### Anything else?

log:
[artifacts-cluster-reinstall-559-logs.tar.gz](https://github.com/milvus-io/milvus/files/8676467/artifacts-cluster-reinstall-559-logs.tar.gz)

**Comment by zhuwenxing** [comment]
If the num of querynode is 1,  then there will be no issue.
http://10.100.32.144:8080/view/deploy%20test/job/deploy_test/561/

**Comment by zhuwenxing** [comment]
/assign @sunby 

Please take a look

**Comment by zhuwenxing** [comment]
Not reproduced for now.

It has passed in recent days
http://10.100.32.144:8080/blue/organizations/jenkins/deploy_test/detail/deploy_test/587/pipeline/60
