### ISSUE TITLE
[Bug]: [memory]Search failed `RPC terminated with Deadline Exceeded` while applying stress memory on one querynode

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#16965]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220513-c5149c7e
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.1.0.dev56
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. Deploy milvus cluster with 5 querynodes and limit their memory 6Gi
2. Create the collection `stress_replicas_2` with `dim=128` and insert 1000,000 entities (About 500M size)
3. Load the collection with `replica_numer=2` successfully and query successfully
4. Release collection
5. Apply memory stress on **querynode-11** 5Gi for 5 miniutes. BTW the querynode is still running, didn't OOM
6. Load the collection with `replica_numer=2` didn't return exception
7. Search failed `_MultiThreadedRendezvous of RPC that terminated with: status = StatusCode.DEADLINE_EXCEEDED`

Client logs:
```
<partitions>: [{"name": "_default", "collection_name": "stress_replicas_2", "description": ""}]
    auto_......  (api_request.py:27)
[2022-05-13 11:36:59,657 - DEBUG - ci_test]: 1000000 (test_chaos_memory_stress.py:281)
[2022-05-13 11:36:59,665 - DEBUG - ci_test]: {'apiVersion': 'chaos-mesh.org/v1alpha1', 'kind': 'StressChaos', 'metadata': {'name': 'test-querynode-memory-stress-replica', 'namespace': 'chaos-testing'}, 'spec': {'selector': {'pods': {'chaos-testing': ['mic-replica-milvus-querynode-77587bf7b9-xqktw']}}, 'mode': 'all', 'stressors': {'memory': {'workers': 4, 'size': '5Gi'}, 'duration': '5m'}}} (test_chaos_memory_stress.py:315)
[2022-05-13 11:36:59,848 - DEBUG - ci_test]: create custom resource response: {'apiVersion': 'chaos-mesh.org/v1alpha1', 'kind': 'StressChaos', 'metadata': {'creationTimestamp': '2022-05-13T03:36:59Z', 'generation': 1, 'managedFields': [{'apiVersion': 'chaos-mesh.org/v1alpha1', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:spec': {'.': {}, 'f:mode': {}, 'f:selector': {'.': {}, 'f:pods': {'.': {}, 'f:chaos-testing': {}}}, 'f:stressors': {'.': {}, 'f:memory': {'.': {}, 'f:size': {}, 'f:workers': {}}}}}, 'manager': 'OpenAPI-Generator', 'operation': 'Update', 'time': '2022-05-13T03:36:59Z'}], 'name': 'test-querynode-memory-stress-replica', 'namespace': 'chaos-testing', 'resourceVersion': '328779406', 'uid': '167ab24d-84ec-4971-a2c7-a28ab8810dff'}, 'spec': {'mode': 'all', 'selector': {'namespaces': ['chaos-testing'], 'pods': {'chaos-testing': ['mic-replica-milvus-querynode-77587bf7b9-xqktw']}}, 'stressors': {'memory': {'size': '5Gi', 'workers': 4}}}, 'status': {'experiment': {}}} (cus_resource_opts.py:29)
[2022-05-13 11:36:59,850 - DEBUG - ci_test]: chaos injected (test_chaos_memory_stress.py:321)
[2022-05-13 11:37:19,854 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 2, 60], kwargs: {} (api_request.py:55)
[2022-05-13 11:37:19,883 - DEBUG - ci_test]: (api_response) : None  (api_request.py:27)
[2022-05-13 11:37:19,884 - DEBUG - ci_test]: (api_request)  : [loading_progress] args: ['stress_replicas_2', None, 'default'], kwargs: {} (api_request.py:55)
[2022-05-13 11:37:19,935 - DEBUG - ci_test]: (api_response) : {'loading_progress': '100%', 'num_loaded_partitions': 1, 'not_loaded_partitions': []}  (api_request.py:27)
[2022-05-13 11:37:19,936 - DEBUG - ci_test]: (api_request)  : [Collection.get_replicas] args: [20], kwargs: {} (api_request.py:55)
[2022-05-13 11:37:19,992 - DEBUG - ci_test]: (api_response) : Replica groups:
- Group: <group_id:433169527983833115>, <group_nodes:(12, 10, 11)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_433169976934531073v0>, <shard_leader:10>, <shard_nodes:[10, 12]>, Shard: <channel_name:by-dev-rootcoord-dml_1_433169976934531073v1>, <shard_leader:11>, <shard_node......  (api_request.py:27)
[2022-05-13 11:37:19,992 - DEBUG - ci_test]: Replica groups:
- Group: <group_id:433169527983833115>, <group_nodes:(12, 10, 11)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_433169976934531073v0>, <shard_leader:10>, <shard_nodes:[10, 12]>, Shard: <channel_name:by-dev-rootcoord-dml_1_433169976934531073v1>, <shard_leader:11>, <shard_nodes:[11, 12, 10]>]>
- Group: <group_id:433169527983833116>, <group_nodes:(2, 3)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_1_433169976934531073v1>, <shard_leader:2>, <shard_nodes:[2]>, Shard: <channel_name:by-dev-rootcoord-dml_0_433169976934531073v0>, <shard_leader:3>, <shard_nodes:[3]>]> (test_chaos_memory_stress.py:327)
[2022-05-13 11:37:19,994 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.13616394827519465, 0.09402187932507822, 0.08061922683722363, 0.025335319100383096, 0.1295565468959351, 0.08482925275568598, 0.09108119370075841, 0.018177115467628, 0.15528947576406632, 0.04431574924043307, 0.07072644871312972, 0.1538986951476478, 0.02936220787062997, 0.07696925070328742, 0.0511......, kwargs: {} (api_request.py:55)
[2022-05-13 11:38:20,074 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 82, in handler
    raise e
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 21, in handler
    return func(self, *args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 499, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 82, in handler
    raise e
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 446, in _execute_search_requests
    raise pre_err
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 434, in _execute_search_requests
    response = ft.result()
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1652413100.059277000","description":"Error received from peer ipv4:10.98.0.7:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nausicca/projects/milvus/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
    res = func(*args, **kwargs)
  File "/Users/nausicca/projects/milvus/tests/python_client/utils/api_request.py", line 56, in api_request
    return func(*arg, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 690, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 49, in handler
    raise MilvusException(Status.UNEXPECTED_ERROR, str(e))
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1652413100.059277000","description":"Error received from peer ipv4:10.98.0.7:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>)>
 (api_request.py:35)
[2022-05-13 11:38:20,076 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1652413100.059277000","description":"Error received from peer ipv4:10.98.0.7:19530","file":"src/core/lib...... (api_request.py:36)
FAILED
```

**Server logs:** 
[mic_logs.tar.gz](https://github.com/milvus-io/milvus/files/8683960/mic_logs.tar.gz)

### Expected Behavior

Search successfully

### Anything else?

1. Server config
```
queryNode:
      replicas: 5
      resources:
        limits:
          memory: 6Gi
  config:
    log:
      level: debug
    common:
      retentionDuration: 40
    queryNode:
      gracefulTime: 0
```

2. chaos yaml
```
spec:
  selector:
    pods:
      chaos-testing:
        - mic-replica-milvus-querynode-77587bf7b9-xqktw
  mode: all
  stressors:
    memory:
      workers: 4
      size: 5Gi
    duration: 5m
```

**Comment by congqixia** [comment]
Hi @ThreadDao , the original log has logic problem. The related pr has been merged. Could you please kindly redo the test and provide the log again?

**Comment by ThreadDao** [comment]
> This problem can be reproduced with commit [c5149c7e](https://github.com/milvus-io/milvus/commit/c5149c7e85ab86c8dec67226f8e45d859ede9970) as specified.
> 
> The reason is that querynode has some probability of not watching correct DML channels, which leads to queryshard being unable to update DML tsafe and waiting indefinitely.
> 
> This problem can not be reproduced with the latest master branch. We think it has been resolved by some PR regarding to querycoord scheduling.

Yeah!  I verified on image `master-20220519-7eb6fcfb` that there is no problem. So close the issue
