### ISSUE TITLE
[Bug]: Search failed for the collection which index is `IVF_FLAT` after the replicas changed from 1 to 2

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#16979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220513-f0dee539
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.0.dev48
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Search succeed  for collection `task_3_FLAT` but failed for collection `task_3_IVF_FLAT`
The difference for two collections is the index they have
```
collection name: task_3_FLAT
release collection
load collection
Replica groups:
- Group: <group_id:433173802180149467>, <group_nodes:(7, 6)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_433173825830256641v0>, <shard_leader:6>, <shard_nodes:[6]>, Shard: <channel_name:by-dev-rootcoord-dml_1_433173825830256641v1>, <shard_leader:7>, <shard_nodes:[7]>]>
- Group: <group_id:433173802180149466>, <group_nodes:(1, 3, 2)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_433173825830256641v0>, <shard_leader:3>, <shard_nodes:[3, 1]>, Shard: <channel_name:by-dev-rootcoord-dml_1_433173825830256641v1>, <shard_leader:3>, <shard_nodes:[3, 1]>]>
load time: 1.7717
{'metric_type': 'L2', 'params': {'nprobe': 10}}

Search...
(distance: 31.03946304321289, id: 572) -14.0
(distance: 31.64992904663086, id: 1488) -17.0
(distance: 31.690767288208008, id: 1664) -16.0
(distance: 31.88949966430664, id: 1701) -15.0
(distance: 32.049922943115234, id: 1823) -14.0
[572, 1488, 1664, 1701, 1823]
search latency: 0.0833s
{'count': 2, 'random_value': -17.0}
{'count': 4, 'random_value': -12.0}
{'count': 6, 'random_value': -17.0}
{'count': 8, 'random_value': -11.0}
query latency: 0.0458s

```

```
collection name: task_3_IVF_FLAT
release collection
load collection
Replica groups:
- Group: <group_id:433173802180149488>, <group_nodes:(6, 1)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_2_433173827586621441v0>, <shard_leader:1>, <shard_nodes:[1]>, Shard: <channel_name:by-dev-rootcoord-dml_3_433173827586621441v1>, <shard_leader:6>, <shard_nodes:[6]>]>
- Group: <group_id:433173802180149487>, <group_nodes:(7, 3, 2)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_2_433173827586621441v0>, <shard_leader:7>, <shard_nodes:[7]>, Shard: <channel_name:by-dev-rootcoord-dml_3_433173827586621441v1>, <shard_leader:2>, <shard_nodes:[2, 7]>]>
load time: 1.3363
{'metric_type': 'L2', 'params': {'nprobe': 10}}

Search...
grpc RpcError: [_execute_search_requests], <_MultiThreadedRendezvous: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded>, <Time:{'RPC start': '2022-05-13 15:56:32.075081', 'gRPC error': '2022-05-13 15:58:32.084168'}>
grpc RpcError: [search], <_MultiThreadedRendezvous: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded>, <Time:{'RPC start': '2022-05-13 15:56:32.006276', 'gRPC error': '2022-05-13 15:58:32.084339'}>
Traceback (most recent call last):
  File "/Users/zilliz/opt/anaconda3/envs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/opt/anaconda3/envs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 82, in handler
    raise e
  File "/Users/zilliz/opt/anaconda3/envs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/Users/zilliz/opt/anaconda3/envs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 21, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/opt/anaconda3/envs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 497, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/Users/zilliz/opt/anaconda3/envs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 82, in handler
    raise e
  File "/Users/zilliz/opt/anaconda3/envs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/Users/zilliz/opt/anaconda3/envs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 444, in _execute_search_requests
    raise pre_err
  File "/Users/zilliz/opt/anaconda3/envs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 432, in _execute_search_requests
    response = ft.result()
  File "/Users/zilliz/opt/anaconda3/envs/milvus/lib/python3.8/site-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "{"created":"@1652428712.083928000","description":"Error received from peer ipv4:10.96.0.236:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "action_after_upgrade.py", line 96, in <module>
    task_3(data_size, host)
  File "action_after_upgrade.py", line 51, in task_3
    load_and_search(prefix, replicas=NUM_REPLICAS)
  File "/Users/zilliz/workspace/backup/milvus/tests/python_client/deploy/scripts/utils.py", line 157, in load_and_search
    res = c.search(
  File "/Users/zilliz/opt/anaconda3/envs/milvus/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 686, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/Users/zilliz/opt/anaconda3/envs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 49, in handler
    raise MilvusException(Status.UNEXPECTED_ERROR, str(e))
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "{"created":"@1652428712.083928000","description":"Error received from peer ipv4:10.96.0.236:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>)>
```

### Expected Behavior

all test cases passed

### Steps To Reproduce

```markdown
Notice, here we did not do upgrading, two steps were running with the latest version Milvus
And for simple, we just pick `task_3` to run, so you can comment out other tasks like this

  connections.connect(host=host, port=19530, timeout=60)
  ms = MilvusSys()
  # task_1(data_size, host)
  # task_2(data_size, host)
  if len(ms.query_nodes) >= NUM_REPLICAS:
      task_3(data_size, host)
      # task_4(data_size, host)
      # task_5(data_size, host)

and change the all_index_types = ["FLAT", "IVF_FLAT", "IVF_SQ8"] in `utils.py` 

The scripts can be found in the dir `tests/python_client/deploy/scripts`

1. run `python action_before_upgrade.py`
2. run `python action_after_upgrade.py`
```

### Anything else?

server log:
[test-multi-replicas-05-13-16-23.zip](https://github.com/milvus-io/milvus/files/8685454/test-multi-replicas-05-13-16-23.zip)

**Comment by congqixia** [comment]
@zhuwenxing This problem does not reproduce with latest master branch. #17034 shall be the fixing PR. Could you please verify?
/unassign
/assign @zhuwenxing

**Comment by zhuwenxing** [comment]
verified and passed in version `master-20220519-e05cfe19`
