### ISSUE TITLE
 the newest pymilvus client connect milvus 2.0.2 occurs core dump

### ISSUE THREAD

**Issue by jaime0815** [milvus-io/milvus#16989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

It seems a backward compatibility issue, use the newest pymilvus client to run nightly test cases with milvus 2.0.2, and query node core dump.

```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  unsupported data type
SIGABRT: abort
PC=0x7f8fa6e14e87 m=10 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f8fa6e14e87
stack: frame={sp:0x7f8f5affaa60, fp:0x0} stack=[0x7f8f5a7fb628,0x7f8f5affb228)
00007f8f5affa960:  0000000000000000  0000000000000000
00007f8f5affa970:  0000000000000000  0000000000000000
00007f8f5affa980:  0000000000000000  0000000000000000
00007f8f5affa990:  fffffffffffffff8  0000000000000001
00007f8f5affa9a0:  0000000000000000  0000000000000000
00007f8f5affa9b0:  0000000000000000  0000000000000030
00007f8f5affa9c0:  0000000000000007  0000000000000000
00007f8f5affa9d0:  0000000000000001  00007f8fa86ef8ff
00007f8f5affa9e0:  0000000000000000  0000000000000000
00007f8f5affa9f0:  0000000000000000  0000000000000000
00007f8f5affaa00:  0000000000000000  0000000000000000
00007f8f5affaa10:  0000000000000000  00007f8fa86f5d60
00007f8f5affaa20:  4000000000000000  0000000000000000
00007f8f5affaa30:  0000000000000000  0000000000000000
00007f8f5affaa40:  0000000000000000  0000000000000000
00007f8f5affaa50:  00007f8f5affac80  00007f8f5affac88
00007f8f5affaa60: <0000000000000000  00007f8f4c02eda0
00007f8f5affaa70:  726f746365567461  5f6570797420200a
00007f8f5affaa80:  203a736d61726170  656b202020200a3c
00007f8f5affaa90:  226d696422203a79  6c6176202020200a
00007f8f5affaaa0:  38323122203a6575  0a3e0a3e20200a22
00007f8f5affaab0:  616420200a227261  3a657079745f6174
00007f8f5affaac0:  797420200a313220  6d617261705f6570
00007f8f5affaad0:  2020200a3c203a73  6d22203a79656b20
00007f8f5affaae0:  fffffffe7fffffff  ffffffffffffffff
00007f8f5affaaf0:  ffffffffffffffff  ffffffffffffffff
00007f8f5affab00:  ffffffffffffffff  ffffffffffffffff
00007f8f5affab10:  ffffffffffffffff  ffffffffffffffff
00007f8f5affab20:  ffffffffffffffff  ffffffffffffffff
00007f8f5affab30:  ffffffffffffffff  ffffffffffffffff
00007f8f5affab40:  ffffffffffffffff  ffffffffffffffff
00007f8f5affab50:  ffffffffffffffff  ffffffffffffffff
runtime: unknown pc 0x7f8fa6e14e87
stack: frame={sp:0x7f8f5affaa60, fp:0x0} stack=[0x7f8f5a7fb628,0x7f8f5affb228)
00007f8f5affa960:  0000000000000000  0000000000000000
00007f8f5affa970:  0000000000000000  0000000000000000
00007f8f5affa980:  0000000000000000  0000000000000000
00007f8f5affa990:  fffffffffffffff8  0000000000000001
00007f8f5affa9a0:  0000000000000000  0000000000000000
00007f8f5affa9b0:  0000000000000000  0000000000000030
00007f8f5affa9c0:  0000000000000007  0000000000000000
00007f8f5affa9d0:  0000000000000001  00007f8fa86ef8ff
00007f8f5affa9e0:  0000000000000000  0000000000000000
00007f8f5affa9f0:  0000000000000000  0000000000000000
00007f8f5affaa00:  0000000000000000  0000000000000000
00007f8f5affaa10:  0000000000000000  00007f8fa86f5d60
00007f8f5affaa20:  4000000000000000  0000000000000000
00007f8f5affaa30:  0000000000000000  0000000000000000
00007f8f5affaa40:  0000000000000000  0000000000000000
00007f8f5affaa50:  00007f8f5affac80  00007f8f5affac88
00007f8f5affaa60: <0000000000000000  00007f8f4c02eda0
00007f8f5affaa70:  726f746365567461  5f6570797420200a
00007f8f5affaa80:  203a736d61726170  656b202020200a3c
00007f8f5affaa90:  226d696422203a79  6c6176202020200a
00007f8f5affaaa0:  38323122203a6575  0a3e0a3e20200a22
00007f8f5affaab0:  616420200a227261  3a657079745f6174
00007f8f5affaac0:  797420200a313220  6d617261705f6570
00007f8f5affaad0:  2020200a3c203a73  6d22203a79656b20
00007f8f5affaae0:  fffffffe7fffffff  ffffffffffffffff
00007f8f5affaaf0:  ffffffffffffffff  ffffffffffffffff
00007f8f5affab00:  ffffffffffffffff  ffffffffffffffff
00007f8f5affab10:  ffffffffffffffff  ffffffffffffffff
00007f8f5affab20:  ffffffffffffffff  ffffffffffffffff
00007f8f5affab30:  ffffffffffffffff  ffffffffffffffff
00007f8f5affab40:  ffffffffffffffff  ffffffffffffffff
00007f8f5affab50:  ffffffffffffffff  ffffffffffffffff

goroutine 407 [syscall]:
runtime.cgocall(0x1c6356c, 0xc001af6990, 0x1ac)
        /usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc001af6960 sp=0xc001af6928 pc=0x7c933b
[github.com/milvus-io/milvus/internal/querynode._Cfunc_NewCollection](http://github.com/milvus-io/milvus/internal/querynode._Cfunc_NewCollection)(0x7f8f4c000d50, 0x0)
        _cgo_gotypes.go:595 +0x45 fp=0xc001af6990 sp=0xc001af6960 pc=0x1c36a65
[github.com/milvus-io/milvus/internal/querynode.newCollection](http://github.com/milvus-io/milvus/internal/querynode.newCollection)(0x602f68c7db00001, 0xc001895f20, 0x602f68c7db00001)
        /go/src/[github.com/milvus-io/milvus/internal/querynode/collection.go:299](http://github.com/milvus-io/milvus/internal/querynode/collection.go:299) +0xa6 fp=0xc001af6a88 sp=0xc001af6990 pc=0x1c3a2e6
[github.com/milvus-io/milvus/internal/querynode.(*collectionReplica).addCollection](http://github.com/milvus-io/milvus/internal/querynode.(*collectionReplica).addCollection)(0xc000812780, 0x602f68c7db00001, 0xc001895f20, 0x0)
        /go/src/[github.com/milvus-io/milvus/internal/querynode/collection_replica.go:211](http://github.com/milvus-io/milvus/internal/querynode/collection_replica.go:211) +0xd9 fp=0xc001af6b50 sp=0xc001af6a88 pc=0x1c3b399
[github.com/milvus-io/milvus/internal/querynode.(*watchDmChannelsTask).Execute](http://github.com/milvus-io/milvus/internal/querynode.(*watchDmChannelsTask).Execute)(0xc001f2a8d0, 0x36691f0, 0xc00041dc00, 0x0, 0x0)
        /go/src/[github.com/milvus-io/milvus/internal/querynode/task.go:263](http://github.com/milvus-io/milvus/internal/querynode/task.go:263) +0xa02 fp=0xc001af7ea8 sp=0xc001af6b50 pc=0x1c2a202
[github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).processTask](http://github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).processTask)(0xc00041dc40, 0x367e3d8, 0xc001f2a8d0, 0x367b7d0, 0xc00051a460)
        /go/src/[github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:61](http://github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:61) +0x173 fp=0xc001af7f40 sp=0xc001af7ea8 pc=0x1c33eb3
[github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).taskLoop(0xc00041dc40)](http://github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).taskLoop(0xc00041dc40))
        /go/src/[github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:78](http://github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:78) +0x15a fp=0xc001af7fd8 sp=0xc001af7f40 pc=0x1c3421a
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc001af7fe0 sp=0xc001af7fd8 pc=0x838a01
created by [github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).Start](http://github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).Start)
        /go/src/[github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:86](http://github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:86) +0x5c

goroutine 1 [chan receive]:
[github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run](http://github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run)(0xc000d87ee0, 0x1, 0x0, 0x0)
        /go/src/[github.com/milvus-io/milvus/cmd/roles/roles.go:495](http://github.com/milvus-io/milvus/cmd/roles/roles.go:495) +0x438
main.main()
        /go/src/[github.com/milvus-io/milvus/cmd/main.go:296](http://github.com/milvus-io/milvus/cmd/main.go:296) +0x692
```

**Comment by longjiquan** [comment]
`NewCollection` cgo call didn't catch exception, so core dump occured.

Old milvus didn't support string, so newer case with string type entered function `NewCollection` will fail. I'll fix this issue soon. thx for pointing out this. @jaime0815 

/assign
