### ISSUE TITLE
[Bug]: [memory] Release collection hangs after the querynode OOMKilled and restarting

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#16995]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220513-f0dee539
- Deployment mode(standalone or cluster): cluster 
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.1.0.dev56
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. Deploy milvus cluster with 2 querynodes, limit their memory 6Gi
2. Create an collection and insert 1000,000 entities
3. Load with 2 replicas and query successfully
4. Apply memory stress 6Gi on one querynode and it OOMKilled
5. After removing memory stress and querynode back to running
6. Release collection hangs
```
[2022-05-14 13:05:45,094 - DEBUG - ci_test]: (api_request)  : [Collection.release] args: [], kwargs: {'timeout': 20} (api_request.py:55)
[2022-05-14 13:09:14,167 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 82, in handler
    raise e
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 788, in release_collection
    response = rf.result()
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1652504954.161959000","description":"Error received from peer ipv4:10.98.0.9:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nausicca/projects/milvus/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
    res = func(*args, **kwargs)
  File "/Users/nausicca/projects/milvus/tests/python_client/utils/api_request.py", line 56, in api_request
    return func(*arg, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 478, in release
    conn.release_collection(self._name, timeout=timeout, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 52, in handler
    raise MilvusException(Status.UNEXPECTED_ERROR, "rpc timeout")
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=rpc timeout)>
 (api_request.py:35)
```

**Server logs:** 
[mic_logs.tar.gz](https://github.com/milvus-io/milvus/files/8692251/mic_logs.tar.gz)

### Expected Behavior

Release collection successfully

### Steps To Reproduce

```markdown
/chaos/test_memory_stress.py::TestMemoryStressReplicaLoadBalance

    def test_memory_stress_replicas_load_balance_single_node(self, prepare_collection):
        collection_w = prepare_collection
        utility_w = ApiUtilityWrapper()

        # load and searchc
        collection_w.load(replica_number=2)
        progress, _ = utility_w.loading_progress(collection_w.name)
        assert progress["loading_progress"] == "100%"
        query_res, _ = collection_w.query("int64 in [0]")
        assert len(query_res) != 0

        # apply memory stress
        chaos_config = gen_experiment_config("./chaos_objects/memory_stress/chaos_querynode_memory_stress.yaml")

        # Update config
        chaos_config['spec']['mode'] = "one"
        chaos_config['spec']['stressors']['memory']['size'] = '6Gi'
        chaos_config['spec']['duration'] = "1m"
        log.debug(chaos_config)
        duration = chaos_config.get('spec').get('duration')
        duration = duration.replace('h', '*3600+').replace('m', '*60+').replace('s', '*1+') + '+0'
        chaos_res = CusResource(kind=chaos_config['kind'],
                                group=constants.CHAOS_GROUP,
                                version=constants.CHAOS_VERSION,
                                namespace=constants.CHAOS_NAMESPACE)
        chaos_res.create(chaos_config)

        sleep(eval(duration))
        chaos_res.delete(metadata_name=chaos_config.get('metadata', None).get('name', None))
        
        # release and load again
        collection_w.release()
        collection_w.load(replica_number=2)
        progress, _ = utility_w.loading_progress(collection_w.name)
        assert progress["loading_progress"] == "100%"
        search_res, _ = collection_w.search(cf.gen_vectors(1, dim=self.dim),
                                            ct.default_float_vec_field_name, ct.default_search_params,
                                            ct.default_limit, timeout=120)
        assert 1 == len(search_res) and ct.default_limit == len(search_res[0])
```

### Anything else?

mic config
```
queryNode:
      replicas: 2
      resources:
        limits:
          memory: 6Gi
```
chaos config:
```
spec:
  selector:
    namespaces:
      - chaos-testing
    labelSelectors:
      app.kubernetes.io/name: milvus
      app.kubernetes.io/instance: mic-memory
      app.kubernetes.io/component: querynode
  mode: one
  value: "2"
  stressors:
    memory:
      workers: 4
      size: 6Gi
  duration: 1m
```

**Comment by yanliang567** [comment]
/assign @congqixia 
@congqixia  could you please help to look at this issue?

/unassign

**Comment by congqixia** [comment]
#17064 shall fix this issue. Could you please verify @ThreadDao 
/unassign
/assign @ThreadDao

**Comment by ThreadDao** [comment]
> #17064 shall fix this issue. Could you please verify @ThreadDao /unassign /assign @ThreadDao

I did not reproduce on image `master-20220519-e05cfe19`. So ignore this issue for now
