### ISSUE TITLE
[Bug]:[Benchmark][cluster] Milvus  search raise an error"message=Invalid shard leader"

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#17037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220515-338edcd3
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus==2.1.0.dev39restart and search raise error
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo：
benchmark-cron-1652630400
server-configmap
server-cluster-16c64m
client-configmap
client-search-sift50m-ivf-flat-2048

client log:

```
[2022-05-15 19:01:13,897] [   ERROR] - RPC error: [_execute_search_requests], <MilvusException: (code=1, message=Invalid shard leader)>, <Time:{'RPC start': '2022-05-15 19:01:13.879845', 'RPC error': '2022-05-15 19:01:13.897846'}> (pymilvus.decorators:73)
[2022-05-15 19:01:13,899] [   ERROR] - RPC error: [search], <MilvusException: (code=1, message=Invalid shard leader)>, <Time:{'RPC start': '2022-05-15 19:01:13.867827', 'RPC error': '2022-05-15 19:01:13.899172'}> (pymilvus.decorators:73)
[2022-05-15 19:01:13,901] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 95, in run_suite
    result = runner.run_case(case_metric, **case)
  File "/src/milvus_benchmark/runners/search.py", line 298, in run_case
    guarantee_timestamp=case_param["guarantee_timestamp"])
  File "/src/milvus_benchmark/client.py", line 49, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 324, in query
    result = self._milvus.search(tmp_collection_name, **params)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 842, in search
    partition_names, output_fields, timeout, round_decimal, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 21, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 481, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 428, in _execute_search_requests
    raise pre_err
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 419, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Invalid shard leader)>
```
milvus：master-20220515-338edcd3
pymilvus：pymilvus==2.1.0.dev39

```
NAME                                                             READY   STATUS      RESTARTS   AGE     IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-cron-1652630400-7-etcd-0                               1/1     Running     0          6m4s    10.97.16.72    qa-node013.zilliz.local   <none>           <none>
benchmark-cron-1652630400-7-etcd-1                               1/1     Running     0          6m4s    10.97.17.107   qa-node014.zilliz.local   <none>           <none>
benchmark-cron-1652630400-7-etcd-2                               1/1     Running     0          6m3s    10.97.16.74    qa-node013.zilliz.local   <none>           <none>
benchmark-cron-1652630400-7-milvus-datacoord-567f5f77c7-ncrvz    1/1     Running     1          6m4s    10.97.4.179    qa-node002.zilliz.local   <none>           <none>
benchmark-cron-1652630400-7-milvus-datanode-5bb44d8788-479bc     1/1     Running     1          6m4s    10.97.17.102   qa-node014.zilliz.local   <none>           <none>
benchmark-cron-1652630400-7-milvus-indexcoord-84d4fdc8f8-hn4p5   1/1     Running     0          6m4s    10.97.4.176    qa-node002.zilliz.local   <none>           <none>
benchmark-cron-1652630400-7-milvus-indexnode-7dc9d99875-nw8nr    1/1     Running     0          6m4s    10.97.16.49    qa-node013.zilliz.local   <none>           <none>
benchmark-cron-1652630400-7-milvus-proxy-5894979fb6-gvvmn        1/1     Running     1          6m4s    10.97.4.177    qa-node002.zilliz.local   <none>           <none>
benchmark-cron-1652630400-7-milvus-querycoord-7b84bcc95c-qkgzv   1/1     Running     1          6m4s    10.97.4.178    qa-node002.zilliz.local   <none>           <none>
benchmark-cron-1652630400-7-milvus-querynode-75d7bf9685-ftbsz    1/1     Running     0          6m4s    10.97.20.97    qa-node018.zilliz.local   <none>           <none>
benchmark-cron-1652630400-7-milvus-rootcoord-5fd796ff85-4b585    1/1     Running     1          6m5s    10.97.4.175    qa-node002.zilliz.local   <none>           <none>
benchmark-cron-1652630400-7-minio-0                              1/1     Running     0          6m4s    10.97.19.32    qa-node016.zilliz.local   <none>           <none>
benchmark-cron-1652630400-7-minio-1                              1/1     Running     0          6m4s    10.97.19.34    qa-node016.zilliz.local   <none>           <none>
benchmark-cron-1652630400-7-minio-2                              1/1     Running     0          6m4s    10.97.19.37    qa-node016.zilliz.local   <none>           <none>
benchmark-cron-1652630400-7-minio-3                              1/1     Running     0          6m4s    10.97.19.38    qa-node016.zilliz.local   <none>           <none>
benchmark-cron-1652630400-7-pulsar-bookie-0                      1/1     Running     0          6m4s    10.97.19.33    qa-node016.zilliz.local   <none>           <none>
benchmark-cron-1652630400-7-pulsar-bookie-1                      1/1     Running     0          6m4s    10.97.9.245    qa-node007.zilliz.local   <none>           <none>
benchmark-cron-1652630400-7-pulsar-bookie-2                      1/1     Running     0          6m3s    10.97.5.17     qa-node003.zilliz.local   <none>           <none>
benchmark-cron-1652630400-7-pulsar-bookie-init-ptb54             0/1     Completed   0          6m4s    10.97.5.2      qa-node003.zilliz.local   <none>           <none>
benchmark-cron-1652630400-7-pulsar-broker-0                      1/1     Running     0          6m4s    10.97.12.5     qa-node015.zilliz.local   <none>           <none>
benchmark-cron-1652630400-7-pulsar-proxy-0                       1/1     Running     0          6m4s    10.97.18.12    qa-node017.zilliz.local   <none>           <none>
benchmark-cron-1652630400-7-pulsar-pulsar-init-jhrvg             0/1     Completed   0          6m4s    10.97.19.5     qa-node016.zilliz.local   <none>           <none>
benchmark-cron-1652630400-7-pulsar-recovery-0                    1/1     Running     0          6m4s    10.97.3.7      qa-node001.zilliz.local   <none>           <none>
benchmark-cron-1652630400-7-pulsar-zookeeper-0                   1/1     Running     0          6m4s    10.97.5.7      qa-node003.zilliz.local   <none>           <none>
benchmark-cron-1652630400-7-pulsar-zookeeper-1                   1/1     Running     0          4m45s   10.97.3.9      qa-node001.zilliz.local   <none>           <none>
benchmark-cron-1652630400-7-pulsar-zookeeper-2                   1/1     Running     0          4m2s    10.97.19.40    qa-node016.zilliz.local   <none>           <none>
```

### Steps To Reproduce

```markdown
1、create collection
2、create index of ivf_flat
3、insert 50m million vectors
4、flush collection
5、build index with the same params
6、load collection
7、search -> raise error
```

### Milvus Log

```
config yaml:
{
	"config.yaml": "insert_search_performance:
		  collections:
		    -
		      collection_name: sift_50m_128_l2
		      ni_per: 50000
		      build_index: true
		      index_type: ivf_flat 
		      index_param:
		        nlist: 2048
		      run_count: 30
		      top_ks: [1, 10, 100, 1000]
		      nqs: [1, 10, 100, 500, 1000, 1200]
		      search_params:
		        -
		          nprobe: 8
		        -
		          nprobe: 32
		"
}
```

**Comment by jingkl** [comment]
argo
benchmark-cron-1652544000
server-configmap
server-cluster-16c64m
client-configmap
client-search-sift50m-ivf-flat-2048


pymilvus==2.1.0.dev39
master-20220514-328ab7ec

```
[2022-05-14 18:30:42,207] [   ERROR] - RPC error: [_execute_search_requests], <MilvusException: (code=1, message=Invalid shard leader)>, <Time:{'RPC start': '2022-05-14 18:30:42.195572', 'RPC error': '2022-05-14 18:30:42.207698'}> (pymilvus.decorators:73)
[2022-05-14 18:30:42,208] [   ERROR] - RPC error: [search], <MilvusException: (code=1, message=Invalid shard leader)>, <Time:{'RPC start': '2022-05-14 18:30:42.183320', 'RPC error': '2022-05-14 18:30:42.208465'}> (pymilvus.decorators:73)
[2022-05-14 18:30:42,210] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 95, in run_suite
    result = runner.run_case(case_metric, **case)
  File "/src/milvus_benchmark/runners/search.py", line 298, in run_case
    guarantee_timestamp=case_param["guarantee_timestamp"])
  File "/src/milvus_benchmark/client.py", line 49, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 324, in query
    result = self._milvus.search(tmp_collection_name, **params)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 842, in search
    partition_names, output_fields, timeout, round_decimal, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 21, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 481, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 428, in _execute_search_requests
    raise pre_err
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 419, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Invalid shard leader)>
 (milvus_benchmark.main:98)
[2022-05-14 18:30:42,212] [    INFO] - None (milvus_benchmark.main:99)
[2022-05-14 18:30:42,213] [   DEBUG] - {'type': 'insert_search_performance', 'value': {}} (milvus_benchmark.main:107)
```

```
NAME                                                             READY   STATUS      RESTARTS   AGE     IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-cron-1652544000-7-etcd-0                               1/1     Running     0          5m2s    10.97.16.3     qa-node013.zilliz.local   <none>           <none>
benchmark-cron-1652544000-7-etcd-1                               1/1     Running     0          5m2s    10.97.17.237   qa-node014.zilliz.local   <none>           <none>
benchmark-cron-1652544000-7-etcd-2                               1/1     Running     0          5m2s    10.97.17.239   qa-node014.zilliz.local   <none>           <none>
benchmark-cron-1652544000-7-milvus-datacoord-647594f9cc-srkwm    1/1     Running     0          5m2s    10.97.4.63     qa-node002.zilliz.local   <none>           <none>
benchmark-cron-1652544000-7-milvus-datanode-5f75bc5b98-279lp     1/1     Running     0          5m2s    10.97.16.247   qa-node013.zilliz.local   <none>           <none>
benchmark-cron-1652544000-7-milvus-indexcoord-54645db57b-xhv8t   1/1     Running     0          5m2s    10.97.4.62     qa-node002.zilliz.local   <none>           <none>
benchmark-cron-1652544000-7-milvus-indexnode-f7b6f74d7-fw6fh     1/1     Running     0          5m2s    10.97.10.11    qa-node008.zilliz.local   <none>           <none>
benchmark-cron-1652544000-7-milvus-proxy-68c46f66f4-dst82        1/1     Running     0          5m2s    10.97.4.61     qa-node002.zilliz.local   <none>           <none>
benchmark-cron-1652544000-7-milvus-querycoord-8486dc4c79-7w6ps   1/1     Running     0          5m2s    10.97.4.64     qa-node002.zilliz.local   <none>           <none>
benchmark-cron-1652544000-7-milvus-querynode-f6bbb674f-mb85t     1/1     Running     0          5m2s    10.97.20.39    qa-node018.zilliz.local   <none>           <none>
benchmark-cron-1652544000-7-milvus-rootcoord-5bf89cf9c7-57fgh    1/1     Running     0          5m2s    10.97.4.65     qa-node002.zilliz.local   <none>           <none>
benchmark-cron-1652544000-7-minio-0                              1/1     Running     0          5m2s    10.97.19.172   qa-node016.zilliz.local   <none>           <none>
benchmark-cron-1652544000-7-minio-1                              1/1     Running     0          5m2s    10.97.12.242   qa-node015.zilliz.local   <none>           <none>
benchmark-cron-1652544000-7-minio-2                              1/1     Running     0          5m2s    10.97.19.178   qa-node016.zilliz.local   <none>           <none>
benchmark-cron-1652544000-7-minio-3                              1/1     Running     0          5m2s    10.97.19.182   qa-node016.zilliz.local   <none>           <none>
benchmark-cron-1652544000-7-pulsar-bookie-0                      1/1     Running     0          5m2s    10.97.19.174   qa-node016.zilliz.local   <none>           <none>
benchmark-cron-1652544000-7-pulsar-bookie-1                      1/1     Running     0          5m2s    10.97.5.216    qa-node003.zilliz.local   <none>           <none>
benchmark-cron-1652544000-7-pulsar-bookie-2                      1/1     Running     0          5m1s    10.97.19.183   qa-node016.zilliz.local   <none>           <none>
benchmark-cron-1652544000-7-pulsar-bookie-init-dpczm             0/1     Completed   0          5m2s    10.97.5.205    qa-node003.zilliz.local   <none>           <none>
benchmark-cron-1652544000-7-pulsar-broker-0                      1/1     Running     0          5m2s    10.97.12.240   qa-node015.zilliz.local   <none>           <none>
benchmark-cron-1652544000-7-pulsar-proxy-0                       1/1     Running     0          5m2s    10.97.11.229   qa-node009.zilliz.local   <none>           <none>
benchmark-cron-1652544000-7-pulsar-pulsar-init-ms8q8             0/1     Completed   0          5m2s    10.97.5.204    qa-node003.zilliz.local   <none>           <none>
benchmark-cron-1652544000-7-pulsar-recovery-0                    1/1     Running     0          5m2s    10.97.3.158    qa-node001.zilliz.local   <none>           <none>
benchmark-cron-1652544000-7-pulsar-zookeeper-0                   1/1     Running     0          5m2s    10.97.5.208    qa-node003.zilliz.local   <none>           <none>
benchmark-cron-1652544000-7-pulsar-zookeeper-1                   1/1     Running     0          3m53s   10.97.18.171   qa-node017.zilliz.local   <none>           <none>
benchmark-cron-1652544000-7-pulsar-zookeeper-2                   1/1     Running     0          3m      10.97.18.173   qa-node017.zilliz.local   <none>           <none>
```

**Comment by jingkl** [comment]
argo
benchmark-cron-1652457600
server-configmap
server-cluster-16c64m
client-configmap
client-search-sift50m-ivf-flat-2048

client log

```
[2022-05-13 18:33:15,713] [   ERROR] - RPC error: [_execute_search_requests], <MilvusException: (code=1, message=Invalid shard leader)>, <Time:{'RPC start': '2022-05-13 18:33:15.701992', 'RPC error': '2022-05-13 18:33:15.713655'}> (pymilvus.decorators:73)
[2022-05-13 18:33:15,714] [   ERROR] - RPC error: [search], <MilvusException: (code=1, message=Invalid shard leader)>, <Time:{'RPC start': '2022-05-13 18:33:15.691455', 'RPC error': '2022-05-13 18:33:15.714315'}> (pymilvus.decorators:73)
[2022-05-13 18:33:15,715] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 95, in run_suite
    result = runner.run_case(case_metric, **case)
  File "/src/milvus_benchmark/runners/search.py", line 298, in run_case
    guarantee_timestamp=case_param["guarantee_timestamp"])
  File "/src/milvus_benchmark/client.py", line 49, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 324, in query
    result = self._milvus.search(tmp_collection_name, **params)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 842, in search
    partition_names, output_fields, timeout, round_decimal, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 21, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 481, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 428, in _execute_search_requests
    raise pre_err
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 419, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Invalid shard leader)>
```

 milvus: master-20220513-23f7ef93
pymilvus:pymilvus==2.1.0.dev39
```
NAME                                                             READY   STATUS      RESTARTS   AGE     IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-cron-1652457600-7-etcd-0                               1/1     Running     0          6m7s    10.97.17.51    qa-node014.zilliz.local   <none>           <none>
benchmark-cron-1652457600-7-etcd-1                               1/1     Running     0          6m7s    10.97.16.202   qa-node013.zilliz.local   <none>           <none>
benchmark-cron-1652457600-7-etcd-2                               1/1     Running     0          6m6s    10.97.17.53    qa-node014.zilliz.local   <none>           <none>
benchmark-cron-1652457600-7-milvus-datacoord-796495cbc8-g2s68    1/1     Running     1          6m8s    10.97.3.31     qa-node001.zilliz.local   <none>           <none>
benchmark-cron-1652457600-7-milvus-datanode-576f6895c5-stdkd     1/1     Running     1          6m8s    10.97.17.32    qa-node014.zilliz.local   <none>           <none>
benchmark-cron-1652457600-7-milvus-indexcoord-69fcd7d79c-5b7t7   1/1     Running     0          6m8s    10.97.3.33     qa-node001.zilliz.local   <none>           <none>
benchmark-cron-1652457600-7-milvus-indexnode-84d7bc4d64-2pfkt    1/1     Running     0          6m8s    10.97.20.239   qa-node018.zilliz.local   <none>           <none>
benchmark-cron-1652457600-7-milvus-proxy-65578674dc-zhrfl        1/1     Running     1          6m8s    10.97.5.243    qa-node003.zilliz.local   <none>           <none>
benchmark-cron-1652457600-7-milvus-querycoord-547fd45c4b-t5th9   1/1     Running     1          6m8s    10.97.3.34     qa-node001.zilliz.local   <none>           <none>
benchmark-cron-1652457600-7-milvus-querynode-789858b7db-7s7hq    1/1     Running     0          6m8s    10.97.16.196   qa-node013.zilliz.local   <none>           <none>
benchmark-cron-1652457600-7-milvus-rootcoord-787fdb4c8b-xqc8r    1/1     Running     1          6m8s    10.97.3.32     qa-node001.zilliz.local   <none>           <none>
benchmark-cron-1652457600-7-minio-0                              1/1     Running     0          6m6s    10.97.12.198   qa-node015.zilliz.local   <none>           <none>
benchmark-cron-1652457600-7-minio-1                              1/1     Running     0          6m6s    10.97.12.203   qa-node015.zilliz.local   <none>           <none>
benchmark-cron-1652457600-7-minio-2                              1/1     Running     0          6m6s    10.97.12.205   qa-node015.zilliz.local   <none>           <none>
benchmark-cron-1652457600-7-minio-3                              1/1     Running     0          6m5s    10.97.12.206   qa-node015.zilliz.local   <none>           <none>
benchmark-cron-1652457600-7-pulsar-bookie-0                      1/1     Running     0          6m7s    10.97.18.81    qa-node017.zilliz.local   <none>           <none>
benchmark-cron-1652457600-7-pulsar-bookie-1                      1/1     Running     0          6m6s    10.97.12.201   qa-node015.zilliz.local   <none>           <none>
benchmark-cron-1652457600-7-pulsar-bookie-2                      1/1     Running     0          6m5s    10.97.9.185    qa-node007.zilliz.local   <none>           <none>
benchmark-cron-1652457600-7-pulsar-bookie-init-fh97k             0/1     Completed   0          6m8s    10.97.18.78    qa-node017.zilliz.local   <none>           <none>
benchmark-cron-1652457600-7-pulsar-broker-0                      1/1     Running     0          6m8s    10.97.11.198   qa-node009.zilliz.local   <none>           <none>
benchmark-cron-1652457600-7-pulsar-proxy-0                       1/1     Running     0          6m7s    10.97.5.244    qa-node003.zilliz.local   <none>           <none>
benchmark-cron-1652457600-7-pulsar-pulsar-init-rtcf4             0/1     Completed   0          6m8s    10.97.9.177    qa-node007.zilliz.local   <none>           <none>
benchmark-cron-1652457600-7-pulsar-recovery-0                    1/1     Running     0          6m7s    10.97.3.35     qa-node001.zilliz.local   <none>           <none>
benchmark-cron-1652457600-7-pulsar-zookeeper-0                   1/1     Running     0          6m7s    10.97.9.182    qa-node007.zilliz.local   <none>           <none>
benchmark-cron-1652457600-7-pulsar-zookeeper-1                   1/1     Running     0          4m48s   10.97.11.205   qa-node009.zilliz.local   <none>           <none>
benchmark-cron-1652457600-7-pulsar-zookeeper-2                   1/1     Running     0          4m27s   10.97.11.207   qa-node009.zilliz.local   <none>           <none>
```

**Comment by xiaofan-luan** [comment]
@jinkl is this still a issue?

**Comment by jingkl** [comment]
Milvus : master-20220531-72f454e0
pymilvus-2.1.0.dev67
Verified, no errors reported, close issue

**Comment by jingkl** [comment]
same as issue：#16943
