### ISSUE TITLE
[Bug]: Load with replica_number=2, Query hangs forever

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#17038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

QueryNodes number: 5
replica_number: 2
commit: e38c6f6c4

The next drop_collection hangs forever for the same collection.
The following loads hangs forever for new collections. 
```
 5036 pts/8    Sl     2:14 ./milvus run datanode
 5037 pts/8    Sl     0:04 ./milvus run datacoord
 5038 pts/8    Sl     0:31 ./milvus run querynode
 5039 pts/8    Sl     0:13 ./milvus run querycoord
 5040 pts/8    Sl     4:23 ./milvus run indexnode
 5041 pts/8    Sl     0:05 ./milvus run indexcoord
 5042 pts/8    Sl     1:46 ./milvus run proxy
 5043 pts/8    Sl    10:57 ./milvus run rootcoord
 6486 pts/8    Sl    13:26 ./milvus run querynode --alias=1
 6487 pts/8    Sl     0:24 ./milvus run querynode --alias=2
 6488 pts/8    Sl     0:17 ./milvus run querynode --alias=3
 6489 pts/8    Sl    13:24 ./milvus run querynode --alias=4
```
**scripts:**

```python
import time

import numpy as np
from pymilvus import (
    connections,
    utility,
    FieldSchema, CollectionSchema, DataType,
    Collection,
)

fmt = "\n=== {:30} ===\n"
search_latency_fmt = "search latency = {:.4f}s"
num_entities, dim = 25000, 512

print(fmt.format("start connecting to Milvus"))
connections.connect("default", host="localhost", port="19530")

if utility.has_collection("hello_milvus"):
    utility.drop_collection("hello_milvus")
    print(f"Drop existing collection hello_milvus")

fields = [
    FieldSchema(name="pk", dtype=DataType.INT64, is_primary=True, auto_id=False),
    FieldSchema(name="random", dtype=DataType.DOUBLE),
    FieldSchema(name="embeddings", dtype=DataType.FLOAT_VECTOR, dim=dim)
]

schema = CollectionSchema(fields, "hello_milvus is the simplest demo to introduce the APIs")

print(fmt.format("Create collection `hello_milvus`"))
hello_milvus = Collection("hello_milvus", schema)

print(fmt.format("Start inserting entities"))
rng = np.random.default_rng(seed=19530)
entities = [
    # provide the pk field because `auto_id` is set to False
    [i for i in range(num_entities)],
    rng.random(num_entities).tolist(),  # field random, only supports list
    rng.random((num_entities, dim)),    # field embeddings, supports numpy.ndarray and list
]

for i in range(10):
    insert_result = hello_milvus.insert(entities)
    print(f"Number of entities in Milvus: {hello_milvus.num_entities}")  # check the num_entites

print(fmt.format("Start Creating index IVF_FLAT"))
index = {
    "index_type": "IVF_FLAT",
    "metric_type": "L2",
    "params": {"nlist": 128},
}

hello_milvus.create_index("embeddings", index)

print(fmt.format("Start loading"))
hello_milvus.load(replica_number=2)

print(f"{utility.loading_progress(hello_milvus.name)}")

# -----------------------------------------------------------------------------
# search based on vector similarity
print(fmt.format("Start searching based on vector similarity"))
vectors_to_search = entities[-1][-2:]
search_params = {
    "metric_type": "l2",
    "params": {"nprobe": 10},
}

start_time = time.time()
result = hello_milvus.search(vectors_to_search, "embeddings", search_params, limit=3, output_fields=["random"])
end_time = time.time()

for hits in result:
    for hit in hits:
        print(f"hit: {hit}, random field: {hit.entity.get('random')}")
print(search_latency_fmt.format(end_time - start_time))

# -----------------------------------------------------------------------------
# query based on scalar filtering(boolean, int, etc.)
print(fmt.format("Start querying with `random > 0.5`"))

start_time = time.time()
result = hello_milvus.query(expr="random > 0.5", output_fields=["random", "embeddings"])
end_time = time.time()

print(f"query result:\n-{result[0]}")
print(search_latency_fmt.format(end_time - start_time))

# -----------------------------------------------------------------------------
# hybrid search
print(fmt.format("Start hybrid searching with `random > 0.5`"))

start_time = time.time()
result = hello_milvus.search(vectors_to_search, "embeddings", search_params, limit=3, expr="random > 0.5", output_fields=["random"])
end_time = time.time()

for hits in result:
    for hit in hits:
        print(f"hit: {hit}, random field: {hit.entity.get('random')}")
print(search_latency_fmt.format(end_time - start_time))

###############################################################################
# 6. delete entities by PK
# You can delete entities by their PK values using boolean expressions.
ids = insert_result.primary_keys
expr = f"pk in [{ids[0]}, {ids[1]}]"
print(fmt.format(f"Start deleting with expr `{expr}`"))

result = hello_milvus.query(expr=expr, output_fields=["random", "embeddings"])
print(f"query before delete by expr=`{expr}` -> result: \n-{result[0]}\n-{result[1]}\n")

hello_milvus.delete(expr)

result = hello_milvus.query(expr=expr, output_fields=["random", "embeddings"])
print(f"query after delete by expr=`{expr}` -> result: {result}\n")
```

**Comment by XuanYang-cn** [comment]
The stocking log
```
=== start connecting to Milvus     ===

Does collection hello_milvus exist in Milvus: False

=== Create collection `hello_milvus` ===


=== Start inserting entities       ===

Number of entities in Milvus: 25000
Number of entities in Milvus: 50000
Number of entities in Milvus: 75000
Number of entities in Milvus: 100000
Number of entities in Milvus: 125000
Number of entities in Milvus: 150000
Number of entities in Milvus: 175000
Number of entities in Milvus: 200000
Number of entities in Milvus: 225000
Number of entities in Milvus: 250000

=== Start Creating index IVF_FLAT  ===


=== Start loading                  ===

{'loading_progress': '100%', 'num_loaded_partitions': 1, 'not_loaded_partitions': []}

=== Start searching based on vector similarity ===

hit: (distance: 0.0, id: 24998), random field: 0.03497599168206422
hit: (distance: 73.14198303222656, id: 14720), random field: 0.5026364973541553
hit: (distance: 0.0, id: 24999), random field: 0.8811798454474418
hit: (distance: 71.30453491210938, id: 8248), random field: 0.14827029557931348
search latency = 0.0978s

=== Start querying with `random > 0.5` ===

^CTraceback (most recent call last):
  File "examples/hello_milvus.py", line 134, in <module>
    result = hello_milvus.query(expr="random > 0.5", output_fields=["random", "embeddings"])
  File "/home/yangxuan/.virtualenvs/py36milvus/lib/python3.6/site-packages/pymilvus-2.1.0.dev57-py3.6.egg/pymilvus/orm/collection.py", line 772, in query
  File "/home/yangxuan/.virtualenvs/py36milvus/lib/python3.6/site-packages/pymilvus-2.1.0.dev57-py3.6.egg/pymilvus/decorators.py", line 41, in handler
```

**Comment by congqixia** [comment]
@XuanYang-cn After #17058 is merged, this issue shall be resolved. Could you please verify?
/unassign
/assign @XuanYang-cn

**Comment by XuanYang-cn** [comment]
verified and fixed
