### ISSUE TITLE
[Bug]: Search and query failed if output_fields is `["int64", "float", "varchar"]`

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#17043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220516-e38c6f6c
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.0.dev57
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

search failed if `output_fields=["int64", "float", "varchar"]`, but ok for `output_fields=["int64", "float"]`
```
Search...
RPC error: [_execute_search_requests], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=6, reason=Search 8 failed, reason [UnexpectedError] Assert "field_data->num_chunk() == 1" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:521
 => num chunk not equal to 1 for sealed segment, num_chunk: 0 err %!w(<nil>))>, <Time:{'RPC start': '2022-05-16 21:28:17.756117', 'RPC error': '2022-05-16 21:28:17.787853'}>
RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=6, reason=Search 8 failed, reason [UnexpectedError] Assert "field_data->num_chunk() == 1" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:521
 => num chunk not equal to 1 for sealed segment, num_chunk: 0 err %!w(<nil>))>, <Time:{'RPC start': '2022-05-16 21:28:17.699162', 'RPC error': '2022-05-16 21:28:17.788000'}>
Traceback (most recent call last):
  File "hello_milvus.py", line 117, in <module>
    hello_milvus(args.host)
  File "hello_milvus.py", line 90, in hello_milvus
    res = collection.search(
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 690, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/decorators.py", line 21, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 499, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 446, in _execute_search_requests
    raise pre_err
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 437, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=6, reason=Search 8 failed, reason [UnexpectedError] Assert "field_data->num_chunk() == 1" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:521
 => num chunk not equal to 1 for sealed segment, num_chunk: 0 err %!w(<nil>))>
```

### Expected Behavior

search success if the params are correct; if params are not correct, please report an easy-to-read error message

### Steps To Reproduce

 ```python
import random
import numpy as np
import time
import argparse
from pymilvus import (
    connections, list_collections,
    FieldSchema, CollectionSchema, DataType,
    Collection
)
TIMEOUT = 120


def hello_milvus(host="127.0.0.1"):
    import time
    # create connection
    connections.connect(host=host, port="19530")

    print(f"\nList collections...")
    print(list_collections())

    # create collection
    dim = 128
    default_fields = [
        FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True),
        FieldSchema(name="float", dtype=DataType.FLOAT),
        FieldSchema(name="varchar", dtype=DataType.VARCHAR, max_length_per_row=65535),
        FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
    ]
    default_schema = CollectionSchema(fields=default_fields, description="test collection")

    print(f"\nCreate collection...")
    collection = Collection(name="hello_milvus", schema=default_schema)

    print(f"\nList collections...")
    print(list_collections())

    #  insert data
    nb = 3000
    vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
    t0 = time.time()
    collection.insert(
        [
            [i for i in range(nb)],
            [np.float32(i) for i in range(nb)],
            [str(i) for i in range(nb)],
            vectors
        ]
    )
    t1 = time.time()
    print(f"\nInsert {nb} vectors cost {t1 - t0:.4f} seconds")

    t0 = time.time()
    print(f"\nGet collection entities...")
    print(collection.num_entities)
    t1 = time.time()
    print(f"\nGet collection entities cost {t1 - t0:.4f} seconds")

    # create index and load table
    default_index = {"index_type": "IVF_SQ8", "metric_type": "L2", "params": {"nlist": 64}}
    print(f"\nCreate index...")
    t0 = time.time()
    collection.create_index(field_name="float_vector", index_params=default_index, index_name="vector_index")
    collection.create_index(field_name="varchar", index_params={}, index_name="string_index")
    t1 = time.time()
    print(f"\nCreate index cost {t1 - t0:.4f} seconds")
    print(f"\nload collection...")
    t0 = time.time()
    collection.load()
    t1 = time.time()
    print(f"\nload collection cost {t1 - t0:.4f} seconds")

    # load and search
    topK = 5
    search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
    t0 = time.time()
    print(f"\nSearch...")
    # define output_fields of search result
    res = collection.search(
        vectors[-2:], "float_vector", search_params, topK,
        "int64 > 100", output_fields=["int64", "float", "varchar"], timeout=TIMEOUT
    )
    t1 = time.time()
    print(f"search cost  {t1 - t0:.4f} seconds")
    # show result
    for hits in res:
        for hit in hits:
            # Get value of the random value field for search result
            print(hit, hit.entity.get("float"))

    # query
    expr = "int64 in [2,4,6,8]"
    output_fields = ["int64", "float", "varchar"]
    res = collection.query(expr, output_fields, timeout=TIMEOUT)
    sorted_res = sorted(res, key=lambda k: k['int64'])
    for r in sorted_res:
        print(r)
    # collection.release()


parser = argparse.ArgumentParser(description='host ip')
parser.add_argument('--host', type=str, default='127.0.0.1', help='host ip')
args = parser.parse_args()
# add time stamp
print(f"\nStart time: {time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(time.time()))}")
hello_milvus(args.host)
```

**Comment by yanliang567** [comment]
sounds like a string support related issue. @xige-16 could you please take a look?

/assign @xige-16 
/unassign

**Comment by xige-16** [comment]
> 

Okey

**Comment by xige-16** [comment]
If the index for VarChar field has been created, then the querynode loads the index file of the varchar field when loading, so there is no original string data in the querynode memory, and the original data cannot be retrieved through the output field when searching. This is a bug. I'm fixing it.

**Comment by xiaofan-luan** [comment]
> 

So I guess currently retrieve should happen on chunkManager?

**Comment by xige-16** [comment]
> .

Yes

**Comment by zhuwenxing** [comment]
verified and passed in version `master-20220526-56778787`
