### ISSUE TITLE
[Bug]: QueryCoord cannot recover from failover when querynode > 1 and replica_number = 2

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#17053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

QueryNodes number: 5
replica number: 2

- prepare_data(), run_test(1)

- stop all services
- start all services

- run_test(1), search failed: 
```
=== start connecting to Milvus     ===

START TESTING
Checking if data prepared
Number of entities in Milvus: 60000
replicas: Replica groups:
- Group: <group_id:433263625676259330>, <group_nodes:(8, 6, 7, 14, 19, 21, 18, 20)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_433263650322451777v0>, <shard_leader:8>, <shard_nodes:[8, 6]>, Shard: <channel_name:by-dev-rootcoord-dml_1_433263650322451777v1>, <shard_leader:6>, <shard_nodes:[6]>]>
- Group: <group_id:433263625676259331>, <group_nodes:(3, 9)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_433263650322451777v0>, <shard_leader:9>, <shard_nodes:[9]>, Shard: <channel_name:by-dev-rootcoord-dml_1_433263650322451777v1>, <shard_leader:3>, <shard_nodes:[3]>]>

=== Start searching based on vector similarity ===

RPC error: [_execute_search_requests], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to get shard leaders from QueryCoord: no replica available)>, <Time:{'RPC start': '2022-05-17 14:46:24.624580', 'RPC error': '2022-05-17 14:46:24.626210'}>
RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to get shard leaders from QueryCoord: no replica available)>, <Time:{'RPC start': '2022-05-17 14:46:24.622620', 'RPC error': '2022-05-17 14:46:24.626328'}>
Traceback (most recent call last):
  File "examples/hello_milvus.py", line 112, in <module>
    run_test(1)
  File "examples/hello_milvus.py", line 101, in run_test
    result = hello_milvus.search(vectors, "embeddings", search_params, limit=3, output_fields=["random"])
  File "/home/yangxuan/.virtualenvs/py36milvus/lib/python3.6/site-packages/pymilvus-2.1.0.dev57-py3.6.egg/pymilvus/orm/collection.py", line 691, in search
  File "/home/yangxuan/.virtualenvs/py36milvus/lib/python3.6/site-packages/pymilvus-2.1.0.dev57-py3.6.egg/pymilvus/decorators.py", line 56, in handler
  File "/home/yangxuan/.virtualenvs/py36milvus/lib/python3.6/site-packages/pymilvus-2.1.0.dev57-py3.6.egg/pymilvus/decorators.py", line 41, in handler
  File "/home/yangxuan/.virtualenvs/py36milvus/lib/python3.6/site-packages/pymilvus-2.1.0.dev57-py3.6.egg/pymilvus/decorators.py", line 74, in handler
  File "/home/yangxuan/.virtualenvs/py36milvus/lib/python3.6/site-packages/pymilvus-2.1.0.dev57-py3.6.egg/pymilvus/decorators.py", line 70, in handler
  File "/home/yangxuan/.virtualenvs/py36milvus/lib/python3.6/site-packages/pymilvus-2.1.0.dev57-py3.6.egg/pymilvus/decorators.py", line 21, in handler
  File "/home/yangxuan/.virtualenvs/py36milvus/lib/python3.6/site-packages/pymilvus-2.1.0.dev57-py3.6.egg/pymilvus/client/grpc_handler.py", line 499, in search
  File "/home/yangxuan/.virtualenvs/py36milvus/lib/python3.6/site-packages/pymilvus-2.1.0.dev57-py3.6.egg/pymilvus/decorators.py", line 74, in handler
  File "/home/yangxuan/.virtualenvs/py36milvus/lib/python3.6/site-packages/pymilvus-2.1.0.dev57-py3.6.egg/pymilvus/decorators.py", line 70, in handler
  File "/home/yangxuan/.virtualenvs/py36milvus/lib/python3.6/site-packages/pymilvus-2.1.0.dev57-py3.6.egg/pymilvus/client/grpc_handler.py", line 446, in _execute_search_requests
  File "/home/yangxuan/.virtualenvs/py36milvus/lib/python3.6/site-packages/pymilvus-2.1.0.dev57-py3.6.egg/pymilvus/client/grpc_handler.py", line 437, in _execute_search_requests
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to get shard leaders from QueryCoord: no replica available)>
```

QueryCoord abnormal logs:
```
[2022/05/17 14:47:32.621 +08:00] [WARN] [query_coord.go:605] ["loadBalanceSegmentLoop: get node info from QueryNode failed"] [nodeID=3] [collection=433263650322451777] [replica=433263625676259331] [error="getNodeInfo: queryNode is offline"]
[2022/05/17 14:47:32.621 +08:00] [WARN] [query_coord.go:605] ["loadBalanceSegmentLoop: get node info from QueryNode failed"] [nodeID=9] [collection=433263650322451777] [replica=433263625676259331] [error="getNodeInfo: queryNode is offline"]
[2022/05/17 14:47:32.621 +08:00] [INFO] [query_coord.go:634] ["loadBalanceSegmentLoop: memory usage rate of all online QueryNode"] [collection=433263650322451777] [replica=433263625676259331] ["mem rate"="{\"14\":0.254889757671066,\"18\":0.254889757671066,\"19\":0.254889757671066,\"20\":0.254889757671066,\"21\":0.254889757671066}"]
[2022/05/17 14:47:32.621 +08:00] [INFO] [query_coord.go:637] ["loadBalanceSegmentLoop: there are too few available query nodes to balance"] [collection=433263650322451777] [replica=433263625676259331] [onlineNodeIDs="[3,9]"] [availableNodeIDs="[]"]
[2022/05/17 14:48:32.601 +08:00] [WARN] [query_coord.go:605] ["loadBalanceSegmentLoop: get node info from QueryNode failed"] [nodeID=3] [collection=433263650322451777] [replica=433263625676259331] [error="getNodeInfo: queryNode is offline"]
[2022/05/17 14:48:32.601 +08:00] [WARN] [query_coord.go:605] ["loadBalanceSegmentLoop: get node info from QueryNode failed"] [nodeID=9] [collection=433263650322451777] [replica=433263625676259331] [error="getNodeInfo: queryNode is offline"]
[2022/05/17 14:48:32.601 +08:00] [INFO] [query_coord.go:634] ["loadBalanceSegmentLoop: memory usage rate of all online QueryNode"] [collection=433263650322451777] [replica=433263625676259331] ["mem rate"={}]
[2022/05/17 14:48:32.601 +08:00] [INFO] [query_coord.go:637] ["loadBalanceSegmentLoop: there are too few available query nodes to balance"] [collection=433263650322451777] [replica=433263625676259331] [onlineNodeIDs="[3,9]"] [availableNodeIDs="[]"]
[2022/05/17 14:48:32.601 +08:00] [WARN] [query_coord.go:605] ["loadBalanceSegmentLoop: get node info from QueryNode failed"] [nodeID=8] [collection=433263650322451777] [replica=433263625676259330] [error="getNodeInfo: queryNode is offline"]
[2022/05/17 14:48:32.601 +08:00] [WARN] [query_coord.go:605] ["loadBalanceSegmentLoop: get node info from QueryNode failed"] [nodeID=6] [collection=433263650322451777] [replica=433263625676259330] [error="getNodeInfo: queryNode is offline"]
[2022/05/17 14:48:32.601 +08:00] [WARN] [query_coord.go:605] ["loadBalanceSegmentLoop: get node info from QueryNode failed"] [nodeID=7] [collection=433263650322451777] [replica=433263625676259330] [error="getNodeInfo: queryNode is offline"]
[2022/05/17 14:48:32.621 +08:00] [INFO] [query_coord.go:634] ["loadBalanceSegmentLoop: memory usage rate of all online QueryNode"] [collection=433263650322451777] [replica=433263625676259330] ["mem rate"="{\"14\":0.25501191876342083,\"18\":0.25501191876342083,\"19\":0.25501191876342083,\"20\":0.25501191876342083,\"21\":0.25501191876342083}"]
```

### Expected Behavior

The script:

- before restart: run with `prepare_data()` and `run_test(1)`
- after restart: run with `run_test(1)`

```python
import time

import numpy as np
from pymilvus import (
    connections,
    utility,
    FieldSchema, CollectionSchema, DataType,
    Collection,
)

fmt = "\n=== {:30} ===\n"
search_latency_fmt = "search latency = {:.4f}s"
num_entities, dim = 3000, 8
rng = np.random.default_rng(seed=19530)

print(fmt.format("start connecting to Milvus"))
connections.connect("default", host="localhost", port="19530")


def prepare_data():
    print(fmt.format("Preparing data for tests"))

    if utility.has_collection("hello_milvus"):
        utility.drop_collection("hello_milvus")
        print(f"Drop collection hello_milvus")

    fields = [
        FieldSchema(name="pk", dtype=DataType.INT64, is_primary=True, auto_id=False),
        FieldSchema(name="random", dtype=DataType.DOUBLE),
        FieldSchema(name="embeddings", dtype=DataType.FLOAT_VECTOR, dim=dim)
    ]

    schema = CollectionSchema(fields, "hello_milvus is the simplest demo to introduce the APIs")

    print(fmt.format("Create collection `hello_milvus`"))
    hello_milvus = Collection("hello_milvus", schema, consistency_level="Strong")

    print(fmt.format("Start inserting entities"))
    entities = [
        # provide the pk field because `auto_id` is set to False
        [i for i in range(num_entities)],
        rng.random(num_entities).tolist(),  # field random, only supports list
        rng.random((num_entities, dim)),    # field embeddings, supports numpy.ndarray and list
    ]

    for i in range(20):
        print(fmt.format(f"The No{i} insert"))
        hello_milvus.insert(entities)

    print(f"Number of entities in Milvus: {hello_milvus.num_entities}")  # check the num_entites

    print(fmt.format("Start Creating index IVF_FLAT"))
    index = {
        "index_type": "IVF_FLAT",
        "metric_type": "L2",
        "params": {"nlist": 128},
    }

    hello_milvus.create_index("embeddings", index)

    print(fmt.format("Start loading"))
    hello_milvus.load(replica_number=2)


def run_test(num=1):
    print("START TESTING")
    print("Checking if data prepared")
    assert utility.has_collection("hello_milvus") is True

    hello_milvus = Collection("hello_milvus")

    print(f"Number of entities in Milvus: {hello_milvus.num_entities}")
    print(f"replicas: {hello_milvus.get_replicas()}")

    vectors = rng.random((2, dim))

    print(fmt.format("Start searching based on vector similarity"))
    search_params = {
        "metric_type": "l2",
        "params": {"nprobe": 10},
    }

    for i in range(num):
        start_time = time.time()
        result = hello_milvus.search(vectors, "embeddings", search_params, limit=3, output_fields=["random"])
        end_time = time.time()

        for hits in result:
            for hit in hits:
                print(f"hit: {hit}, random field: {hit.entity.get('random')}")
        print(search_latency_fmt.format(end_time - start_time))


if __name__ == "__main__":
    prepare_data()
    run_test(1)
```

**Comment by XuanYang-cn** [comment]
```
replicas: Replica groups:
- Group: <group_id:433263625676259330>, <group_nodes:(8, 6, 7, 14, 19, 21, 18, 20)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_433263650322451777v0>, <shard_leader:8>, <shard_nodes:[8, 6]>, Shard: <channel_name:by-dev-rootcoord-dml_1_433263650322451777v1>, <shard_leader:6>, <shard_nodes:[6]>]>
- Group: <group_id:433263625676259331>, <group_nodes:(3, 9)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_433263650322451777v0>, <shard_leader:9>, <shard_nodes:[9]>, Shard: <channel_name:by-dev-rootcoord-dml_1_433263650322451777v1>, <shard_leader:3>, <shard_nodes:[3]>]>
```

3, 6, 7, 8, 9 is the old QueryNodes

14, 19, 21, 18, 20 the restarted QueryNodes

**Comment by yah01** [comment]
Hi @XuanYang-cn 
This should be fixed with #17064, and I can't reproduce it now

**Comment by XuanYang-cn** [comment]
Tested on f93e5a7d42fdf0aa53f3336ec3782a8dfd546bed, QueryCoord is recovered 

@yah01 is this normal?
```
replicas: Replica groups:
- Group: <group_id:433417951046533122>, <group_nodes:(9, 5, 20, 21, 16)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_2_433417956088872961v0>, <shard_leader:5>, <shard_nodes:[5, 20]>, Shard: <channel_name:by-dev-rootcoord-dml_3_433417956088872961v1>, <shard_leader:20>, <shard_nodes:[20]>]>
- Group: <group_id:433417951046533123>, <group_nodes:(18, 19)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_2_433417956088872961v0>, <shard_leader:18>, <shard_nodes:[18]>, Shard: <channel_name:by-dev-rootcoord-dml_3_433417956088872961v1>, <shard_leader:11>, <shard_nodes:[11]>]>
```

**Comment by yah01** [comment]
@XuanYang-cn This should be fixed with the two PRs above:
![image](https://user-images.githubusercontent.com/12216890/170461832-491bb219-7361-4010-8680-cbb398a48016.png)

**Comment by yah01** [comment]
> Why are the same replica group sharing the same shard_leader? Group_1 both shards are using 66 as the leader, Group_2 both shards are using 67 as the leader, is this normal? @yah01

it looks normal, the new nodes are added one by one, the first node been added would take all segments and dmchannels. The LoadBalance mechanism may rebalance some segments to the other nodes.

**Comment by XuanYang-cn** [comment]
lgtm
