### ISSUE TITLE
[Bug]: search error "Invalid shard leader" after bulk load 2m data for 3 times

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#17077]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220517-127dd34b
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus-2.1.0.dev58
```

### Current Behavior

search returns error:
```
[2022-05-18 14:45:35,510 - INFO - ci_test]:  collection entities: 6000000 in 0.5693800449371338 (test_bulk_load.py:1797)
[2022-05-18 14:45:56,096 - INFO - ci_test]: query seg info: 3 segs loaded. (test_bulk_load.py:1803)
[2022-05-18 14:45:56,159 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/yanliang/fork/milvus/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
    res = func(*args, **kwargs)
  File "/Users/yanliang/fork/milvus/tests/python_client/utils/api_request.py", line 56, in api_request
    return func(*arg, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 690, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 21, in handler
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 499, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 446, in _execute_search_requests
    raise pre_err
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 437, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Invalid shard leader)>
 (api_request.py:35)
```

### Expected Behavior

search successfully

### Steps To Reproduce

```markdown
1. bulk load 128d-2 million data from numpy file for 3 times
2. collection.load()
3. search
```

### Milvus Log

[invalid.shard.leader.log.zip](https://github.com/milvus-io/milvus/files/8714046/invalid.shard.leader.log.zip)

**Comment by yanliang567** [comment]
@soothing-rain not sure it was caused by memory replica(although i have multi-replicas) code or not, please take a look first.

/assign @soothing-rain 
/unassign

**Comment by soothing-rain** [comment]
> @soothing-rain not sure it was caused by memory replica(although i have multi-replicas) code or not, please take a look first.
> 
> /assign @soothing-rain /unassign

I think it is related to multi-replicas as "shard leader" is the concept introduced by multi-replicas :)

**Comment by yanliang567** [comment]
@congqixia could you please also take a look

**Comment by yanliang567** [comment]
@congqixia  any updates?

**Comment by congqixia** [comment]
"Invalid shard leader" issue should has been fixed. Could you please verify? @yanliang567

**Comment by yanliang567** [comment]
not reproduce recently, close
