### ISSUE TITLE
[Bug]: Search failed `fail to get shard leaders from QueryCoord: no replica available` after upgrading milvus image

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#17091]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. Deploy milvus `127dd34b` with 5 querynodes and limit memory 6Gi
2. Create collection with 2 shards and insert 5000 entities (2 segments)
3. Load collection with 2 replicas
```
- Group: <group_id:433288700367732739>, <group_nodes:(9, 4, 3)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_433288931294314497v0>, <shard_leader:4>, <shard_nodes:[4]>, Shard: <channel_name:by-dev-rootcoord-dml_1_433288931294314497v1>, <shard_leader:9>, <shard_nodes:[9]>]>
- Group: <group_id:433288700367732738>, <group_nodes:(7, 2)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_433288931294314497v0>, <shard_leader:7>, <shard_nodes:[7]>, Shard: <channel_name:by-dev-rootcoord-dml_1_433288931294314497v1>, <shard_leader:2>, <shard_nodes:[2, 7]>]> (test_chaos_memory_stress.py:669)
```
4. Apply memory stress on querynode-7 and trigger load balance task
```
c.get_query_segment_info('stress_replicas_2')
[segmentID: 433288931594469377
collectionID: 433288931294314497
partitionID: 433288931294314498
mem_size: 1310524
num_rows: 2501
nodeID: 2
state: Sealed
, segmentID: 433288931594469378
collectionID: 433288931294314497
partitionID: 433288931294314498
mem_size: 1309476
num_rows: 2499
nodeID: 2
state: Sealed
, segmentID: 433288931594469377
collectionID: 433288931294314497
partitionID: 433288931294314498
mem_size: 1310524
num_rows: 2501
nodeID: 7
state: Sealed
, segmentID: 433288931594469378
collectionID: 433288931294314497
partitionID: 433288931294314498
mem_size: 1309476
num_rows: 2499
nodeID: 7
state: Sealed
, segmentID: 433288931594469377
collectionID: 433288931294314497
partitionID: 433288931294314498
mem_size: 1310524
num_rows: 2501
nodeID: 9
state: Sealed
, segmentID: 433288931594469378
collectionID: 433288931294314497
partitionID: 433288931294314498
mem_size: 1309476
num_rows: 2499
nodeID: 9
state: Sealed
]
```
5. Upgrade milvus image to `master-20220518-cf08b5aa`
```
Replica groups:
- Group: <group_id:433288700367732739>, <group_nodes:(21, 22)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_433288931294314497v0>, <shard_leader:4>, <shard_nodes:[4]>, Shard: <channel_name:by-dev-rootcoord-dml_1_433288931294314497v1>, <shard_leader:9>, <shard_nodes:[9]>]>
- Group: <group_id:433288700367732738>, <group_nodes:(20, 23, 24)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_433288931294314497v0>, <shard_leader:7>, <shard_nodes:[7, 23, 24]>, Shard: <channel_name:by-dev-rootcoord-dml_1_433288931294314497v1>, <shard_leader:2>, <shard_nodes:[2, 23, 24]>]>
```
Unfortunately, the loaded segment info is clearly incorrect. Because querynode-23 and querynode-24 are same replica group
```
[segmentID: 433288931594469378
collectionID: 433288931294314497
partitionID: 433288931294314498
mem_size: 1309476
num_rows: 2499
nodeID: 23
state: Sealed
, segmentID: 433288931594469377
collectionID: 433288931294314497
partitionID: 433288931294314498
mem_size: 1310524
num_rows: 2501
nodeID: 23
state: Sealed
, segmentID: 433288931594469377
collectionID: 433288931294314497
partitionID: 433288931294314498
mem_size: 1310524
num_rows: 2501
nodeID: 24
state: Sealed
, segmentID: 433288931594469378
collectionID: 433288931294314497
partitionID: 433288931294314498
mem_size: 1309476
num_rows: 2499
nodeID: 24
state: Sealed
]
```
There is no doubt that the search failed
```
[2022-05-18 18:22:32,284 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.14088481606541567, 0.07025815325323675, 0.06019402117886241, 0.11465665885589994, 0.13967973734225403, 0.10320031099921194, 0.13164965076176413, 0.09470515076746491, 0.06808573841402137, 0.03835962250897561, 0.02184936031691009, 0.03885118317655895, 0.007543201943804777, 0.05363320141389615, 0......., kwargs: {} (api_request.py:55)
[2022-05-18 18:22:32,337 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/nausicca/projects/milvus/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
    res = func(*args, **kwargs)
  File "/Users/nausicca/projects/milvus/tests/python_client/utils/api_request.py", line 56, in api_request
    return func(*arg, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 690, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 21, in handler
    return func(self, *args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 499, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 446, in _execute_search_requests
    raise pre_err
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 437, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to get shard leaders from QueryCoord: no replica available)>
 (api_request.py:35)
```

**Server logs:**
[mic_logs_pre.tar.gz](https://github.com/milvus-io/milvus/files/8715607/mic_logs_pre.tar.gz)
[mic_logs.tar.gz](https://github.com/milvus-io/milvus/files/8715609/mic_logs.tar.gz)

### Expected Behavior

Replicas are available and search successfully

### Anything else?

`kubectl apply -f xxx.yaml`
```
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: test-querynode-memory-stress-replica
  namespace: chaos-testing
spec:
  selector:
    pods:
      chaos-testing:
        - mic-replica-milvus-querynode-bc9cd799b-wfrnd
  mode: all
  stressors:
    memory:
      workers: 4
      size: 60%
  duration: 3m
```

**Comment by yanliang567** [comment]
@yah01 @congqixia any updates for this issue?

**Comment by congqixia** [comment]
@yanliang567 #17183 shall fix this issue

**Comment by yanliang567** [comment]
@ThreadDao any chance to verify it?

/assign @ThreadDao

**Comment by ThreadDao** [comment]
@yanliang567 @congqixia 
image: upgrade 'master-20220517-127dd34b' to `master-20220606-45febac2`
**Before upgrade:**
1. replicas
```
c.get_replicas('stress_replicas_1')
Replica groups:
- Group: <group_id:433717620156923906>, <group_nodes:(4, 3)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_433717720658214913v0>, <shard_leader:3>, <shard_nodes:[3, 4]>, Shard: <channel_name:by-dev-rootcoord-dml_1_433717720658214913v1>, <shard_leader:4>, <shard_nodes:[4]>]>
- Group: <group_id:433717620156923907>, <group_nodes:(2, 5, 1)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_433717720658214913v0>, <shard_leader:1>, <shard_nodes:[1]>, Shard: <channel_name:by-dev-rootcoord-dml_1_433717720658214913v1>, <shard_leader:2>, <shard_nodes:[2]>]>
```
2. segment info
```
[segmentID: 433717723764621313
...
num_rows: 2501
nodeID: 4
state: Sealed
, segmentID: 433717723764621314
...
num_rows: 2499
nodeID: 4
state: Sealed
, segmentID: 433717723764621313
...
num_rows: 2501
nodeID: 2
state: Sealed
, segmentID: 433717723764621314
...
num_rows: 2499
nodeID: 2
state: Sealed
]
```
3. Search successfully

 **After upgrade:**
1. replicas
```
c.get_replicas('stress_replicas_1')
Replica groups:
- Group: <group_id:433717620156923907>, <group_nodes:(5, 22, 23, 24)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_433717720658214913v0>, <shard_leader:24>, <shard_nodes:[24]>, Shard: <channel_name:by-dev-rootcoord-dml_1_433717720658214913v1>, <shard_leader:22>, <shard_nodes:[22]>]>
- Group: <group_id:433717620156923906>, <group_nodes:(13, 21, 25)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_433717720658214913v0>, <shard_leader:13>, <shard_nodes:[13, 25]>, Shard: <channel_name:by-dev-rootcoord-dml_1_433717720658214913v1>, <shard_leader:21>, <shard_nodes:[21, 25]>]>
```
2. segment info
```
RPC error: [get_query_segment_info], <MilvusException: (code=1, message=getSegmentInfo: queryNode 5 is offline)>, <Time:{'RPC start': '2022-06-06 16:38:06.275706', 'RPC error': '2022-06-06 16:38:06.290885'}>
```
3. Search get an empty result sometimes
```
[2022-06-06 16:29:54,515 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.033395766377843396, 0.024934000166736726, 0.10580739494561359, 0.13089108431737514, 0.00010027176073052918, 0.07618752871006754, 0.1288299570497216, 0.061037114741889005, 0.0032823944026858488, 0.13437802877998564, 0.05802085095080547, 0.006366934999262451, 0.000860796533769712, 0.0577193268328......, kwargs: {} (api_request.py:55)
[2022-06-06 16:29:54,738 - DEBUG - ci_test]: (api_response) : ['[]']  (api_request.py:27)
```

**Server logs:** 
[mic_logs.tar.gz](https://github.com/milvus-io/milvus/files/8843051/mic_logs.tar.gz)

**Comment by ThreadDao** [comment]
image: upgrade `master-20220517-127dd34b` to `master-20220614-f9553970`
Before upgrade:
```
c.get_replicas('stress_issue_17091')
Replica groups:
- Group: <group_id:433907844438032386>, <group_nodes:(9, 10)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_433908022987132225v0>, <shard_leader:9>, <shard_nodes:[9]>, Shard: <channel_name:by-dev-rootcoord-dml_1_433908022987132225v1>, <shard_leader:10>, <shard_nodes:[10, 9]>]>
- Group: <group_id:433907844438032387>, <group_nodes:(12, 2, 11)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_433908022987132225v0>, <shard_leader:12>, <shard_nodes:[12]>, Shard: <channel_name:by-dev-rootcoord-dml_1_433908022987132225v1>, <shard_leader:2>, <shard_nodes:[2]>]>
c.get_query_segment_info('stress_issue_17091')
[segmentID: 433908023222861826
collectionID: 433908022987132225
partitionID: 433908022987132226
mem_size: 1309476
num_rows: 2499
nodeID: 9
state: Sealed
, segmentID: 433908023222861825
collectionID: 433908022987132225
partitionID: 433908022987132226
mem_size: 1310524
num_rows: 2501
nodeID: 9
state: Sealed
, segmentID: 433908023222861825
collectionID: 433908022987132225
partitionID: 433908022987132226
mem_size: 1310524
num_rows: 2501
nodeID: 2
state: Sealed
, segmentID: 433908023222861826
collectionID: 433908022987132225
partitionID: 433908022987132226
mem_size: 1309476
num_rows: 2499
nodeID: 12
state: Sealed
]
```

Apply memory stress on querynode-9 and load balance occur, then upgrade milvus image:
```
c.get_replicas('stress_issue_17091')
Replica groups:
- Group: <group_id:433907844438032386>, <group_nodes:(25, 50, 52)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_433908022987132225v0>, <shard_leader:9>, <shard_nodes:[9, 50, 52]>, Shard: <channel_name:by-dev-rootcoord-dml_1_433908022987132225v1>, <shard_leader:50>, <shard_nodes:[50, 52]>]>
- Group: <group_id:433907844438032387>, <group_nodes:(35, 42, 51, 53)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_433908022987132225v0>, <shard_leader:51>, <shard_nodes:[51]>, Shard: <channel_name:by-dev-rootcoord-dml_1_433908022987132225v1>, <shard_leader:42>, <shard_nodes:[42]>]>
c.get_query_segment_info('stress_issue_17091')
RPC error: [get_query_segment_info], <MilvusException: (code=1, message=getSegmentInfo: queryNode 35 is offline)>, <Time:{'RPC start': '2022-06-15 01:57:43.964952', 'RPC error': '2022-06-15 01:57:43.990179'}>
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 904, in get_query_segment_info
    return handler.get_query_segment_info(collection_name, timeout=timeout, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 61, in handler
    raise e
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 44, in handler
    return func(self, *args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 79, in handler
    raise e
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 75, in handler
    return func(*args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 460, in get_query_segment_info
    raise MilvusException(status.error_code, status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=getSegmentInfo: queryNode 35 is offline)>
```
No release and re-load, search get empty result:
```
[2022-06-15 01:59:29,240 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.12766300616366527, 0.057423270922657414, 0.06865180122425295, 0.1414733656614521, 0.14380664066393578, 0.08741376366353874, 0.05362716333141878, 0.08742817480377617, 0.039018029497714685, 0.1351191903634582, 0.10147747184830987, 0.016249181731378477, 0.003684671331577325, 0.07441116232530463, 0......, kwargs: {} (api_request.py:55)
[2022-06-15 01:59:29,590 - DEBUG - ci_test]: (api_response) : ['[]']  (api_request.py:27)
[2022-06-15 01:59:29,591 - DEBUG - ci_test]: (api_request)  : [Collection.query] args: ['int64 in [2]', None, None, 20], kwargs: {} (api_request.py:55)
[2022-06-15 01:59:29,793 - DEBUG - ci_test]: (api_response) : [{'int64': 2}]  (api_request.py:27)
```
If release collection and re-load, search successfully, replicas info is correct, failed to get segment info:
```
[2022-06-15 02:04:51,740 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=getSegmentInfo: queryNode 35 is offline)> (api_request.py:36)
FAILED
```

Server logs:  
[mic_logs.tar.gz](https://github.com/milvus-io/milvus/files/8902757/mic_logs.tar.gz)

**Comment by yanliang567** [comment]
querynode offline issue: #17411

**Comment by ThreadDao** [comment]
Upgrade version from `2.0.2` to `master-20220616-00089de2` successfully! Everything looks fine!
1. Deploy milvus cluster `2.0.2`, and limit 5 querynodes memory limit
2. Insert data and load
3. Apply memory stress on one querynode which loaded the segment, but load balance failed
4. Upgrade milvus image to `master-20220616-00089de2`, load, search, release and load replicas ... are both successfully

@yanliang567 Do we need to consider the version upgrade between master-dev? If we don't think it's a problem, close this issue?
