### ISSUE TITLE
[Bug]: [tls] No type check for "secure" parameter in "connect" interface

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#17115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: latest
- Deployment mode(standalone or cluster): both
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.0.dev60
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior
```markdown
No type check for "secure" parameter in "connect" interface
```

### Expected Behavior

```markdown
 * *secure* (``bool``) --
                Optional. Default is false. If set to true, tls will be enabled.
```

### Steps To Reproduce

```markdown
connections.connect(host=***, port="19530", secure="string", client_key_path="/milvus/configs/cert/client.key", client_pem_path="/milvus/configs/cert/client.pem", ca_pem_path="/milvus/configs/cert/ca.pem", server_name="localhost")
```

### Milvus Log

NA

**Comment by binbinlv** [comment]
Keep opening

**Comment by XuanYang-cn** [comment]
pymilvus-2.2.0.dev30
/unassign
/assign @binbinlv

**Comment by binbinlv** [comment]
Fixed and close this issue.
Name: pymilvus
Version: 2.2.0.dev30
```
>>> connections.connect(host="10.100.31.107", port="19530", secure="string")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/binbin/embedded-test-env-3.8/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 300, in connect
    connect_milvus(**kwargs, password=password)
  File "/binbin/embedded-test-env-3.8/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 270, in connect_milvus
    gh = GrpcHandler(**kwargs)
  File "/binbin/embedded-test-env-3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 84, in __init__
    self._set_authorization(**kwargs)
  File "/binbin/embedded-test-env-3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 100, in _set_authorization
    raise ParamError("secure must be bool type")
pymilvus.exceptions.ParamError: secure must be bool type
```
