### ISSUE TITLE
[Bug]: Search failed with error `fail to get shard leaders from QueryCoord: no replica available` after etcd pod kill chaos

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#17119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220517-127dd34b
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus==2.1.0.dev57
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
Traceback (most recent call last):

  File "chaos/scripts/hello_milvus.py", line 116, in <module>
load collection...
    hello_milvus(args.host)

  File "chaos/scripts/hello_milvus.py", line 89, in hello_milvus
load collection cost 0.0490 seconds
    res = collection.search(

  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 690, in search
Search...
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 21, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 499, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 446, in _execute_search_requests
    raise pre_err
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 4[37](https://github.com/milvus-io/milvus/runs/6476641158?check_suite_focus=true#step:14:38), in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to get shard leaders from QueryCoord: no replica available)>
```

### Expected Behavior

all test cases passed

### Steps To Reproduce

```markdown
see https://github.com/milvus-io/milvus/runs/6476641158?check_suite_focus=true
```

### Milvus Log

failed job: https://github.com/milvus-io/milvus/runs/6476641158?check_suite_focus=true
log: https://github.com/milvus-io/milvus/suites/6546060257/artifacts/244465432

### Anything else?

It may same as https://github.com/milvus-io/milvus/issues/16900

**Comment by yanliang567** [comment]
sounds like a similar issue to #17098 
@letian-jiang could you please take a look at this issue?

/assign @letian-jiang 
/unassign

**Comment by zhuwenxing** [comment]
This issue did not happen in today's GitHub action. Not sure whether yesterday's PR fixed it. Because pod kill of etcd will cause many components of Milvus restart.
So the root cause of this issue may be the restart of Milvus components.

**Comment by zhuwenxing** [comment]
Not reproduced, so close it
