### ISSUE TITLE
[Bug]: proxy paniked when CreateSearchPlan

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#17128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-17120/4/pipeline

```
1384767
1384768 [2022/05/20 05:40:47.161 +00:00] [DEBUG] [impl.go:570] ["Received SearchRequest"] [vchannel=by-dev-rootcoord-dml_68_433330649355517965v1] [segmentIDs="[433330649381208066        ]"]
1384769
1384770 [2022/05/20 05:40:47.161 +00:00] [DEBUG] [query_shard.go:244] ["serviceable check start"] [tsType="Delta tSafe"] ["guarantee ts"=433330650390200323] ["serviceable ts"=433        330650324926466] [channel=by-dev-rootcoord-dml_68_433330649355517965v1]
1384771
1384772 [2022/05/20 05:40:47.161 +00:00] [DEBUG] [query_shard.go:253] ["serviceable ts before guarantee ts"] ["serviceable ts"=433330650324926466] ["guarantee ts"=433330650390200        323] [channel=by-dev-rootcoord-dml_68_433330649355517965v1]
1384773
1384774 panic: runtime error: index out of range [-1]
1384775
1384776     panic: runtime error: index out of range [-1] [recovered]
1384777
1384778     panic: runtime error: index out of range [-1]
1384779
1384780
1384781
1384782 goroutine 819014 [running]:
1384783
1384784 github.com/milvus-io/milvus/internal/parser/planparserv2/generated.(*PlanParser).expr.func2(0xc006bfd310, 0xc0047f6800)
1384785
1384786     /go/src/github.com/milvus-io/milvus/internal/parser/planparserv2/generated/plan_parser.go:1473 +0x145
1384787
1384788 panic(0x3bb2440, 0xc009034870)
1384789
1384790     /usr/local/go/src/runtime/panic.go:965 +0x1b9
1384791
1384792 github.com/antlr/antlr4/runtime/Go/antlr.(*CommonTokenStream).NextTokenOnChannel(0xc0022e4040, 0xffffffffffffffff, 0x0, 0x0)
1384793
1384794     /go/pkg/mod/github.com/antlr/antlr4/runtime/!go/antlr@v0.0.0-20210826220005-b48c857c3a0e/common_token_stream.go:208 +0x15b
1384795
1384796 github.com/antlr/antlr4/runtime/Go/antlr.(*CommonTokenStream).adjustSeekIndex(...)
1384797
1384798     /go/pkg/mod/github.com/antlr/antlr4/runtime/!go/antlr@v0.0.0-20210826220005-b48c857c3a0e/common_token_stream.go:376
1384799
1384800 github.com/antlr/antlr4/runtime/Go/antlr.(*CommonTokenStream).Seek(0xc0022e4040, 0xffffffffffffffff)
1384801
1384802     /go/pkg/mod/github.com/antlr/antlr4/runtime/!go/antlr@v0.0.0-20210826220005-b48c857c3a0e/common_token_stream.go:72 +0x45
1384803
1384804 github.com/antlr/antlr4/runtime/Go/antlr.(*ParserATNSimulator).AdaptivePredict.func1(0xc00836dc20, 0x40da838, 0xc0022e4040, 0xffffffffffffffff, 0x0)
```

**Comment by congqixia** [comment]
@XuanYang-cn dup #17126

**Comment by XuanYang-cn** [comment]
dup and close
