### ISSUE TITLE
[Enhancement]: The statement of the expression reporting an error is not clear and cannot be seen as not matching ""

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#17127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

testcase：
```
[2022-05-19T16:27:28.390Z] 
[2022-05-19T16:27:28.390Z]     @pytest.mark.tags(CaseLabel.L2)
[2022-05-19T16:27:28.390Z]     def test_query_expr_non_primary_fields(self):
[2022-05-19T16:27:28.390Z]         """
[2022-05-19T16:27:28.390Z]         target: test query on non-primary non-vector fields
[2022-05-19T16:27:28.390Z]         method: query on non-primary non-vector fields
[2022-05-19T16:27:28.390Z]         expected: verify query result
[2022-05-19T16:27:28.390Z]         """
[2022-05-19T16:27:28.390Z]         self._connect()
[2022-05-19T16:27:28.390Z]         # construct dataframe and inert data
[2022-05-19T16:27:28.390Z]         df = pd.DataFrame({
[2022-05-19T16:27:28.390Z]             ct.default_int64_field_name: pd.Series(data=[i for i in range(ct.default_nb)]),
[2022-05-19T16:27:28.390Z]             ct.default_int32_field_name: pd.Series(data=[np.int32(i) for i in range(ct.default_nb)], dtype="int32"),
[2022-05-19T16:27:28.390Z]             ct.default_int16_field_name: pd.Series(data=[np.int16(i) for i in range(ct.default_nb)], dtype="int16"),
[2022-05-19T16:27:28.390Z]             ct.default_float_field_name: pd.Series(data=[np.float32(i) for i in range(ct.default_nb)], dtype="float32"),
[2022-05-19T16:27:28.390Z]             ct.default_double_field_name: pd.Series(data=[np.double(i) for i in range(ct.default_nb)], dtype="double"),
[2022-05-19T16:27:28.390Z]             ct.default_string_field_name: pd.Series(data=[str(i) for i in range(ct.default_nb)], dtype="string"),
[2022-05-19T16:27:28.390Z]             ct.default_float_vec_field_name: cf.gen_vectors(ct.default_nb, ct.default_dim)
[2022-05-19T16:27:28.390Z]         })
[2022-05-19T16:27:28.390Z]         self.collection_wrap.construct_from_dataframe(cf.gen_unique_str(prefix), df,
[2022-05-19T16:27:28.390Z]                                                       primary_field=ct.default_int64_field_name)
[2022-05-19T16:27:28.390Z]         assert self.collection_wrap.num_entities == ct.default_nb
[2022-05-19T16:27:28.390Z]         self.collection_wrap.load()
[2022-05-19T16:27:28.390Z]     
[2022-05-19T16:27:28.390Z]         # query by non_primary non_vector scalar field
[2022-05-19T16:27:28.390Z]         non_primary_field = [ct.default_int32_field_name, ct.default_int16_field_name,
[2022-05-19T16:27:28.390Z]                              ct.default_float_field_name, ct.default_double_field_name, ct.default_string_field_name]
[2022-05-19T16:27:28.390Z]     
[2022-05-19T16:27:28.390Z]         # exp res: first two rows and all fields expect last vec field
[2022-05-19T16:27:28.390Z]         res = df.iloc[:2, :-1].to_dict('records')
[2022-05-19T16:27:28.390Z]         for field in non_primary_field:
[2022-05-19T16:27:28.390Z]             filter_values = df[field].tolist()[:2]
[2022-05-19T16:27:28.390Z]             term_expr = f'{field} in {filter_values}'
[2022-05-19T16:27:28.390Z]             self.collection_wrap.query(term_expr, output_fields=["*"],
[2022-05-19T16:27:28.390Z] >                                      check_task=CheckTasks.check_query_results, check_items={exp_res: res})
```
```

'double': 1.0, 'varchar': '1', 'int32': 1, 'int16': 1, 'float': 1.0}]  (api_request.py:27)
[2022-05-19T16:27:28.391Z] [2022-05-19 15:09:04 - DEBUG - ci_test]: (api_request)  : [Collection.query] args: ["varchar in ['0', '1']", ['*'], None, 20], kwargs: {} (api_request.py:55)
[2022-05-19T16:27:28.391Z] [2022-05-19 15:09:04 - ERROR - pymilvus.decorators]: RPC error: [query], <MilvusException: (code=1, message=cannot parse expression: varchar in ['0', '1'], error: line 1:19 token recognition error at: ''')>, <Time:{'RPC start': '2022-05-19 15:09:04.328408', 'RPC error': '2022-05-19 15:09:04.339856'}> (decorators.py:73)
[2022-05-19T16:27:28.391Z] [2022-05-19 15:09:04 - ERROR - ci_test]: Traceback (most recent call last):
[2022-05-19T16:27:28.391Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
[2022-05-19T16:27:28.391Z]     res = func(*args, **kwargs)
[2022-05-19T16:27:28.391Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 56, in api_request
[2022-05-19T16:27:28.391Z]     return func(*arg, **kwargs)
[2022-05-19T16:27:28.391Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 772, in query
[2022-05-19T16:27:28.391Z]     res = conn.query(self._name, expr, output_fields, partition_names, timeout, **kwargs)
[2022-05-19T16:27:28.391Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 56, in handler
[2022-05-19T16:27:28.391Z]     raise e
[2022-05-19T16:27:28.391Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 41, in handler
[2022-05-19T16:27:28.391Z]     return func(self, *args, **kwargs)
[2022-05-19T16:27:28.391Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler
[2022-05-19T16:27:28.391Z]     raise e
[2022-05-19T16:27:28.391Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 70, in handler
[2022-05-19T16:27:28.391Z]     return func(*args, **kwargs)
[2022-05-19T16:27:28.391Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 1033, in query
[2022-05-19T16:27:28.391Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2022-05-19T16:27:28.391Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=cannot parse expression: varchar in ['0', '1'], error: line 1:19 token recognition error at: ''')>
[2022-05-19T16:27:28.391Z]  (api_request.py:35)
[2022-05-19T16:27:28.391Z] [2022-05-19 15:09:04 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=cannot parse expression: varchar in ['0', '1'], error: line 1:19 token recognition error at: ''')> (api_request.py:36)
```

### Why is this needed?
Unable to determine the error

**Comment by jingkl** [comment]
expression = 'int64 == varchar'
```

 raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Query, QueryNode ID = 5, reason=Query 5 failed, reason [UnexpectedError] Assert "incompitible data type" at /go/src/[github.com/milvus-io/milvus/internal/core/src/query/Relational.h:33](http://github.com/milvus-io/milvus/internal/core/src/query/Relational.h:33)
 err %!w(<nil>))>
 (api_request.py:35)
[2022-05-24 14:50:18 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Query, QueryNode ID = 5, reason=Query 5 failed, reason [UnexpectedError] Assert "incompitible data type" at /go/src/[github.com/milvus-io/milvus/internal/core/src/query/Relational.h:33](http://github.com/milvus-io/milvus/internal/core/src/query/Relational.h:33)
 err %!w(<nil>))> (api_request.py:36)
```

**Comment by jingkl** [comment]
Verified, close issue
master-20220601-63a31ccb
pymilvus 2.1.0dev67
