### ISSUE TITLE
[Bug]: Antlr PlanParser Panicked in e2e test

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#17126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Running ci e2e test case proxy panicked with log showing error in antlr

### Expected Behavior

e2e passes

### Milvus Log

```

panic: NextToken requires a non-nil input stream. [recovered]

	panic: NextToken requires a non-nil input stream.



goroutine 43552 [running]:

github.com/milvus-io/milvus/internal/parser/planparserv2/generated.(*PlanParser).expr.func2(0xc00246f310, 0xc0099e32f8)

	/go/src/github.com/milvus-io/milvus/internal/parser/planparserv2/generated/plan_parser.go:1473 +0x145

panic(0x3969a20, 0x404b880)

	/usr/local/go/src/runtime/panic.go:965 +0x1b9

github.com/antlr/antlr4/runtime/Go/antlr.(*BaseLexer).NextToken(0xc001761040, 0x0, 0x0)

	/go/pkg/mod/github.com/antlr/antlr4/runtime/!go/antlr@v0.0.0-20210826220005-b48c857c3a0e/lexer.go:182 +0x2b8

github.com/antlr/antlr4/runtime/Go/antlr.(*CommonTokenStream).fetch(0xc008b07800, 0x1, 0xc003bb03b0)

	/go/pkg/mod/github.com/antlr/antlr4/runtime/!go/antlr@v0.0.0-20210826220005-b48c857c3a0e/common_token_stream.go:128 +0x67

github.com/antlr/antlr4/runtime/Go/antlr.(*CommonTokenStream).Sync(0xc008b07800, 0x1a75, 0xc003bb0480)

	/go/pkg/mod/github.com/antlr/antlr4/runtime/!go/antlr@v0.0.0-20210826220005-b48c857c3a0e/common_token_stream.go:113 +0x46

github.com/antlr/antlr4/runtime/Go/antlr.(*CommonTokenStream).Consume(0xc008b07800)

	/go/pkg/mod/github.com/antlr/antlr4/runtime/!go/antlr@v0.0.0-20210826220005-b48c857c3a0e/common_token_stream.go:102 +0x5f

github.com/antlr/antlr4/runtime/Go/antlr.(*ParserATNSimulator).execATN(0xc0032468a0, 0xc00626c900, 0xc003bb0380, 0x40da838, 0xc008b07800, 0x1a74, 0x7f64bcc98430, 0xc003e0d560, 0xc00003e000)

	/go/pkg/mod/github.com/antlr/antlr4/runtime/!go/antlr@v0.0.0-20210826220005-b48c857c3a0e/parser_atn_simulator.go:275 +0x3ea

github.com/antlr/antlr4/runtime/Go/antlr.(*ParserATNSimulator).AdaptivePredict(0xc0032468a0, 0x40da838, 0xc008b07800, 0x1, 0x7f64bcc98430, 0xc003e0d560, 0x0)

	/go/pkg/mod/github.com/antlr/antlr4/runtime/!go/antlr@v0.0.0-20210826220005-b48c857c3a0e/parser_atn_simulator.go:146 +0x54a

github.com/milvus-io/milvus/internal/parser/planparserv2/generated.(*PlanParser).expr(0xc0099e32f8, 0x0, 0x40e9e28, 0xc003e0d560)

	/go/src/github.com/milvus-io/milvus/internal/parser/planparserv2/generated/plan_parser.go:2025 +0x3285

github.com/milvus-io/milvus/internal/parser/planparserv2/generated.(*PlanParser).Expr(...)

	/go/src/github.com/milvus-io/milvus/internal/parser/planparserv2/generated/plan_parser.go:1449

github.com/milvus-io/milvus/internal/parser/planparserv2.handleExpr(0xc00793c660, 0xc0025cc000, 0x7105, 0x39fcd40, 0xc005254e70)

	/go/src/github.com/milvus-io/milvus/internal/parser/planparserv2/plan_parser_v2.go:22 +0x133

github.com/milvus-io/milvus/internal/parser/planparserv2.ParseExpr(0xc00793c660, 0xc0025cc000, 0x7105, 0x0, 0x3d3d925, 0x11)

	/go/src/github.com/milvus-io/milvus/internal/parser/planparserv2/plan_parser_v2.go:36 +0x6c

github.com/milvus-io/milvus/internal/parser/planparserv2.CreateSearchPlan(0xc006386300, 0xc0025cc000, 0x7105, 0xc00681e7c0, 0xc, 0xc0015d0ff0, 0x19, 0x0, 0x0)

	/go/src/github.com/milvus-io/milvus/internal/parser/planparserv2/plan_parser_v2.go:79 +0x75

github.com/milvus-io/milvus/internal/proxy.(*searchTask).PreExecute(0xc0012bd4a0, 0x40b2db8, 0xc005254b40, 0x0, 0x0)

	/go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:190 +0x1885

github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask(0xc0000b9630, 0x40d86f8, 0xc0012bd4a0, 0x40d4ac0, 0xc000012c58)

	/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:452 +0x56b

created by github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).queryLoop

	/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:525 +0x1a5

```

### Anything else?

pipe line link:
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-17120/3/pipeline

**Comment by congqixia** [comment]
hi @longjiquan , I was wondering that whether you could help on this issue?
/assign @longjiquan

**Comment by longjiquan** [comment]
> hi @longjiquan , I was wondering that whether you could help on this issue? /assign @longjiquan

OK, I'll fix this soon.

**Comment by XuanYang-cn** [comment]
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-17120/4/pipeline

```
1384767
1384768 [2022/05/20 05:40:47.161 +00:00] [DEBUG] [impl.go:570] ["Received SearchRequest"] [vchannel=by-dev-rootcoord-dml_68_433330649355517965v1] [segmentIDs="[433330649381208066        ]"]
1384769
1384770 [2022/05/20 05:40:47.161 +00:00] [DEBUG] [query_shard.go:244] ["serviceable check start"] [tsType="Delta tSafe"] ["guarantee ts"=433330650390200323] ["serviceable ts"=433        330650324926466] [channel=by-dev-rootcoord-dml_68_433330649355517965v1]
1384771
1384772 [2022/05/20 05:40:47.161 +00:00] [DEBUG] [query_shard.go:253] ["serviceable ts before guarantee ts"] ["serviceable ts"=433330650324926466] ["guarantee ts"=433330650390200        323] [channel=by-dev-rootcoord-dml_68_433330649355517965v1]
1384773
1384774 panic: runtime error: index out of range [-1]
1384775
1384776     panic: runtime error: index out of range [-1] [recovered]
1384777
1384778     panic: runtime error: index out of range [-1]
1384779
1384780
1384781
1384782 goroutine 819014 [running]:
1384783
1384784 github.com/milvus-io/milvus/internal/parser/planparserv2/generated.(*PlanParser).expr.func2(0xc006bfd310, 0xc0047f6800)
1384785
1384786     /go/src/github.com/milvus-io/milvus/internal/parser/planparserv2/generated/plan_parser.go:1473 +0x145
1384787
1384788 panic(0x3bb2440, 0xc009034870)
1384789
1384790     /usr/local/go/src/runtime/panic.go:965 +0x1b9
1384791
1384792 github.com/antlr/antlr4/runtime/Go/antlr.(*CommonTokenStream).NextTokenOnChannel(0xc0022e4040, 0xffffffffffffffff, 0x0, 0x0)
1384793
1384794     /go/pkg/mod/github.com/antlr/antlr4/runtime/!go/antlr@v0.0.0-20210826220005-b48c857c3a0e/common_token_stream.go:208 +0x15b
1384795
1384796 github.com/antlr/antlr4/runtime/Go/antlr.(*CommonTokenStream).adjustSeekIndex(...)
1384797
1384798     /go/pkg/mod/github.com/antlr/antlr4/runtime/!go/antlr@v0.0.0-20210826220005-b48c857c3a0e/common_token_stream.go:376
1384799
1384800 github.com/antlr/antlr4/runtime/Go/antlr.(*CommonTokenStream).Seek(0xc0022e4040, 0xffffffffffffffff)
1384801
1384802     /go/pkg/mod/github.com/antlr/antlr4/runtime/!go/antlr@v0.0.0-20210826220005-b48c857c3a0e/common_token_stream.go:72 +0x45
1384803
1384804 github.com/antlr/antlr4/runtime/Go/antlr.(*ParserATNSimulator).AdaptivePredict.func1(0xc00836dc20, 0x40da838, 0xc0022e4040, 0xffffffffffffffff, 0x0)
```

**Comment by longjiquan** [comment]
fixed by #17129
