### ISSUE TITLE
concurrency issue between close and operate node in flowgraph

### ISSUE THREAD

**Issue by jaime0815** [milvus-io/milvus#17147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Some mq stream will be closed when the node close is invoked within the flowGraph, but node Operate still working and sending messages to mq stream.

```
[2022/05/21 22:59:09.734 +08:00] [INFO] [data_sync_service.go:131] ["dataSyncService closing flowgraph"] [collectionID=433362031280390145] [vChanName=by-dev-rootcoord-dml_3_433362031280390145v169]
[2022/05/21 22:59:09.734 +08:00] [WARN] [input_node.go:67] ["Receive Msg failed from upstream node"] ["input node"=dmInputNode-data-433362031280390145-by-dev-rootcoord-dml_3_433362031280390145v169]
panic: interface conversion: kafka.Event is nil, not *kafka.Message

goroutine 37338 [running]:
github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/kafka.(*kafkaProducer).Send(0xc008cc41b0, {0x73f24c0, 0xc008c9bf50}, 0x18)
        /Users/zilliz/workspace/dev/milvus/internal/mq/msgstream/mqwrapper/kafka/kafka_producer.go:37 +0x156
github.com/milvus-io/milvus/internal/mq/msgstream.(*mqMsgStream).Produce(0xc004d0acc0, 0x0)
        /Users/zilliz/workspace/dev/milvus/internal/mq/msgstream/mq_msgstream.go:286 +0x59b
github.com/milvus-io/milvus/internal/datanode.(*ddNode).sendDeltaTimeTick(0xc008cb85a0, 0x6039c82fa500001)
        /Users/zilliz/workspace/dev/milvus/internal/datanode/flow_graph_dd_node.go:255 +0x2c2
github.com/milvus-io/milvus/internal/datanode.(*ddNode).forwardDeleteMsg(0x6fe20e0, {0x0, 0x0, 0xc0087ec9e8}, 0xc005a597b8, 0x86645e0)
        /Users/zilliz/workspace/dev/milvus/internal/datanode/flow_graph_dd_node.go:228 +0x16f
github.com/milvus-io/milvus/internal/datanode.(*ddNode).Operate(0xc008cb85a0, {0xc008cbcde0, 0xc008e84100, 0x34})
        /Users/zilliz/workspace/dev/milvus/internal/datanode/flow_graph_dd_node.go:166 +0x5ad
github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work(0xc008cf6070)
        /Users/zilliz/workspace/dev/milvus/internal/util/flowgraph/node.go:100 +0x1d3
created by github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start
        /Users/zilliz/workspace/dev/milvus/internal/util/flowgraph/node.go:68 +0x74
```

**Comment by xiaofan-luan** [comment]
seems that we can add a close mark and lock to guard.
the close and delete are triggered by different processes and hard to sync with each other

**Comment by jaime0815** [comment]
We will not fix this issue in the short term, [pr 17317]( https://github.com/milvus-io/milvus/pull/17317) can skip errors that report from MQ.

the final solution should guarantee to stop the operation of all nodes within the flowgraph.
