### ISSUE TITLE
[Bug]: Search failed with error message `empty slice nqs is not allowed`

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#17167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220523-08a4dff4
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-2.1.0.dev50
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2022-05-23T09:11:37.358Z] Search...

[2022-05-23T09:11:37.358Z] Traceback (most recent call last):

[2022-05-23T09:11:37.358Z]   File "action_before_reinstall.py", line 84, in <module>

[2022-05-23T09:11:37.358Z]     task_1(data_size, host)

[2022-05-23T09:11:37.358Z]   File "action_before_reinstall.py", line 19, in task_1

[2022-05-23T09:11:37.358Z]     load_and_search(prefix)

[2022-05-23T09:11:37.358Z]   File "/home/jenkins/agent/workspace/tests/python_client/deploy/scripts/utils.py", line 158, in load_and_search

[2022-05-23T09:11:37.358Z]     "count > 500", output_fields=["count", "random_value"], timeout=120

[2022-05-23T09:11:37.358Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 688, in search

[2022-05-23T09:11:37.358Z]     partition_names, output_fields, timeout, round_decimal, **kwargs)

[2022-05-23T09:11:37.358Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 56, in handler

[2022-05-23T09:11:37.358Z]     raise e

[2022-05-23T09:11:37.358Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 41, in handler

[2022-05-23T09:11:37.358Z]     return func(self, *args, **kwargs)

[2022-05-23T09:11:37.358Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 74, in handler

[2022-05-23T09:11:37.358Z]     raise e

[2022-05-23T09:11:37.358Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 70, in handler

[2022-05-23T09:11:37.358Z]     return func(*args, **kwargs)

[2022-05-23T09:11:37.358Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 21, in handler

[2022-05-23T09:11:37.358Z]     return func(self, *args, **kwargs)

[2022-05-23T09:11:37.358Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 497, in search

[2022-05-23T09:11:37.359Z]     return self._execute_search_requests(requests, timeout, **_kwargs)

[2022-05-23T09:11:37.359Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 74, in handler

[2022-05-23T09:11:37.359Z]     raise e

[2022-05-23T09:11:37.359Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 70, in handler

[2022-05-23T09:11:37.359Z]     return func(*args, **kwargs)

[2022-05-23T09:11:37.359Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 444, in _execute_search_requests

[2022-05-23T09:11:37.359Z]     raise pre_err

[2022-05-23T09:11:37.359Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 435, in _execute_search_requests

[2022-05-23T09:11:37.359Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2022-05-23T09:11:37.359Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=5, reason=Search 2 failed, reason empty slice nqs is not allowed err %!w(<nil>))>
```

### Expected Behavior

all operations work well

### Steps To Reproduce

```markdown
1. deploy Milvus with version `master-20220523-08a4dff4`
2. cd `tests/python_client/deploy/scripts` and run script `python action_before_reinstall.py `
```

### Milvus Log

[artifacts-cluster-reinstall-607-logs.tar.gz](https://github.com/milvus-io/milvus/files/8753527/artifacts-cluster-reinstall-607-logs.tar.gz)

**Comment by yanliang567** [comment]
@zhuwenxing please retry with latest pymilvus==2.1.0.dev62

**Comment by XuanYang-cn** [comment]
> @zhuwenxing please retry with latest pymilvus==2.1.0.dev62

dev62 is a bug version, please try dev61 instead

**Comment by zhuwenxing** [comment]
With the following config, it works well
Milvus version : master-20220523-cce533c2 (https://github.com/milvus-io/milvus/pull/17168 not in this version)
pymilvus version: pymilvus-2.1.0.dev61
