### ISSUE TITLE
[Bug]: can not connect milvus

### ISSUE THREAD

**Issue by Perfeee** [milvus-io/milvus#17172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.0.0-pre-ga
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):2.0.2
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When i try to connect milvus, i get this error :

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/13135597/169825634-822ffa15-e9dd-435a-903c-6b3e74478574.png">

### Expected Behavior

Connect success without error.

### Steps To Reproduce

```markdown
python hello_milvus.py
```

### Milvus Log

=== start connecting to Milvus     ===

Traceback (most recent call last):
  File "/home/kg_test/anaconda3/envs/python3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 92, in _wait_for_channel_ready
    grpc.channel_ready_future(self._channel).result(timeout=3)
  File "/home/kg_test/anaconda3/envs/python3.8/lib/python3.8/site-packages/grpc/_utilities.py", line 140, in result
    self._block(timeout)
  File "/home/kg_test/anaconda3/envs/python3.8/lib/python3.8/site-packages/grpc/_utilities.py", line 86, in _block
    raise grpc.FutureTimeoutError()
grpc.FutureTimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hello_milvus.py", line 32, in <module>
    connections.connect("default", host="localhost", port="9530")
  File "/home/kg_test/anaconda3/envs/python3.8/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 156, in connect
    conn = connect_milvus(**kwargs)
  File "/home/kg_test/anaconda3/envs/python3.8/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 144, in connect_milvus
    gh._wait_for_channel_ready()
  File "/home/kg_test/anaconda3/envs/python3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 95, in _wait_for_channel_ready
    raise BaseException(Status.CONNECT_FAILED, f'Fail connecting to server on {self._uri}. Timeout')
pymilvus.client.exceptions.BaseException: <BaseException: (code=2, message=Fail connecting to server on localhost:9530. Timeout)>

**Comment by yanliang567** [comment]
@Perfeee thank you for the issue. Did you change any configurations as i believe the default port for Milvus is 19530 instead of 9530. Also could you please retry with latest release v2.0.2 and the pymilvus 2.0.2?

/assign @Perfeee 
/unassign

**Comment by Perfeee** [comment]
@yanliang567 thank you for reply, i have solved this problem after the upgrade and resetting  the port number.

**Comment by yanliang567** [comment]
great, i will close this issue now.
