### ISSUE TITLE
[Bug]: data service DropVirtualChannel failed

### ISSUE THREAD

**Issue by angelapytao** [milvus-io/milvus#17233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.2
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): centos(k8s)
- CPU/Memory: unlimited
- GPU: 
- Others:
```

### Current Behavior

```When etcd crash, then restart etcd. etcd recoveried. And restart Milvus cluster. datanode cannot get up.```

### Expected Behavior

When I restart datanode, datanode should get up.

### Milvus Log

[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
[2022/05/26 07:50:12.215 +00:00] [DEBUG] [flow_graph_dd_node.go:96] ["ddNode in dropMode"] ["vchannel name"=by-dev-rootcoord-dml_1_432471233046773761v1] ["collection ID"=432471233046773761]
time="2022-05-26T07:50:12Z" level=info msg="The consumer[3] successfully unsubscribed" consumerID=3 name=nsacl subscription=by-dev-dataNode-6078-432471233046773761 topic="persistent://public/default/by-dev-rootcoord-dml_1"
time="2022-05-26T07:50:12Z" level=info msg="Closing consumer=3" consumerID=3 name=nsacl subscription=by-dev-dataNode-6078-432471233046773761 topic="persistent://public/default/by-dev-rootcoord-dml_1"
time="2022-05-26T07:50:12Z" level=info msg="[Closed consumer]" consumerID=3 name=nsacl subscription=by-dev-dataNode-6078-432471233046773761 topic="persistent://public/default/by-dev-rootcoord-dml_1"
[2022/05/26 07:50:12.216 +00:00] [DEBUG] [input_node.go:48] ["message stream closed"] ["node name"=dmInputNode-432471233046773761-by-dev-rootcoord-dml_1_432471233046773761v1]
time="2022-05-26T07:50:12Z" level=info msg="[Closing producer]" producerID=5 producer_name=pulsar-1-284442 topic="persistent://public/default/by-dev-rootcoord-delta_1"
time="2022-05-26T07:50:12Z" level=info msg="[Closed producer]" producerID=5 producer_name=pulsar-1-284442 topic="persistent://public/default/by-dev-rootcoord-delta_1"
[2022/05/26 07:50:12.216 +00:00] [WARN] [flow_graph_dd_node.go:84] ["Type assertion failed for MsgStreamMsg"]
time="2022-05-26T07:50:12Z" level=info msg="[Closing producer]" producerID=6 producer_name=pulsar-2-299784 topic="persistent://public/default/by-dev-datacoord-timetick-channel"
time="2022-05-26T07:50:12Z" level=info msg="[Closed producer]" producerID=6 producer_name=pulsar-2-299784 topic="persistent://public/default/by-dev-datacoord-timetick-channel"
[2022/05/26 07:50:12.224 +00:00] [INFO] [flow_graph_delete_node.go:100] ["Flowgraph Delete Node closing"]
[2022/05/26 07:50:12.224 +00:00] [INFO] [flow_graph_manager.go:81] ["release flowgraph resources end"] [Vchannel=by-dev-rootcoord-dml_1_432471233046773761v1]
[2022/05/26 07:50:12.225 +00:00] [WARN] [flow_graph_delete_node.go:219] ["type assertion failed for flowGraphMsg"]
[2022/05/26 07:50:12.225 +00:00] [WARN] [flow_graph_insert_buffer_node.go:168] ["type assertion failed for flowGraphMsg"]
[2022/05/26 07:50:12.767 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:97] ["IBN timetick log"] [from=2022/05/21 01:36:27.359 +00:00] [to=2022/05/21 01:39:47.158 +00:00] [elapsed=3m19.799s] [start=433349456654237698] [end=433349509030346754] [vChannelName=by-dev-rootcoord-dml_0_433349404198961153v0]
[2022/05/26 07:50:12.833 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:97] ["IBN timetick log"] [from=2022/05/21 01:36:27.359 +00:00] [to=2022/05/21 01:39:47.158 +00:00] [elapsed=3m19.799s] [start=433349456654237698] [end=433349509030346754] [vChannelName=by-dev-rootcoord-dml_1_433349404198961153v1]
[2022/05/26 07:50:19.004 +00:00] [INFO] [data_node.go:325] ["DataNode is handling watchInfo put event"] [key=by-dev/meta/channelwatch/6078/by-dev-rootcoord-dml_0_432471233046773761v0] [state=ToRelease]
[2022/05/26 07:50:19.287 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:97] ["IBN timetick log"] [from=2022/05/21 01:39:47.408 +00:00] [to=2022/05/21 01:43:07.208 +00:00] [elapsed=3m19.8s] [start=433349509095882753] [end=433349561472253953] [vChannelName=by-dev-rootcoord-dml_0_433349404198961153v0]
[2022/05/26 07:50:19.344 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:97] ["IBN timetick log"] [from=2022/05/21 01:39:47.408 +00:00] [to=2022/05/21 01:43:07.208 +00:00] [elapsed=3m19.8s] [start=433349509095882753] [end=433349561472253953] [vChannelName=by-dev-rootcoord-dml_1_433349404198961153v1]
[2022/05/26 07:50:25.366 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:97] ["IBN timetick log"] [from=2022/05/21 01:43:07.408 +00:00] [to=2022/05/21 01:46:27.208 +00:00] [elapsed=3m19.8s] [start=433349561524682753] [end=433349613901053953] [vChannelName=by-dev-rootcoord-dml_0_433349404198961153v0]
[2022/05/26 07:50:25.403 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:97] ["IBN timetick log"] [from=2022/05/21 01:43:07.408 +00:00] [to=2022/05/21 01:46:27.208 +00:00] [elapsed=3m19.8s] [start=433349561524682753] [end=433349613901053953] [vChannelName=by-dev-rootcoord-dml_1_433349404198961153v1]
[2022/05/26 07:50:32.690 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:97] ["IBN timetick log"] [from=2022/05/21 01:46:27.358 +00:00] [to=2022/05/21 01:49:47.158 +00:00] [elapsed=3m19.8s] [start=433349613940375554] [end=433349666316746754] [vChannelName=by-dev-rootcoord-dml_0_433349404198961153v0]
[2022/05/26 07:50:32.732 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:97] ["IBN timetick log"] [from=2022/05/21 01:46:27.358 +00:00] [to=2022/05/21 01:49:47.158 +00:00] [elapsed=3m19.8s] [start=433349613940375554] [end=433349666316746754] [vChannelName=by-dev-rootcoord-dml_1_433349404198961153v1]
[2022/05/26 07:50:33.509 +00:00] [WARN] [flush_manager.go:697] ["failed to DropVirtualChannel"] [channel=by-dev-rootcoord-dml_1_432471233046773761v1] [error="All attempts results:\nattempt #1:data service DropVirtualChannel failed, reason = etcdserver: request is too large\nattempt #2:data service DropVirtualChannel failed, reason = etcdserver: request is too large\nattempt #3:data service DropVirtualChannel failed, reason = etcdserver: request is too large\nattempt #4:data service DropVirtualChannel failed, reason = etcdserver: request is too large\nattempt #5:data service DropVirtualChannel failed, reason = etcdserver: request is too large\nattempt #6:data service DropVirtualChannel failed, reason = etcdserver: request is too large\nattempt #7:data service DropVirtualChannel failed, reason = etcdserver: request is too large\nattempt #8:data service DropVirtualChannel failed, reason = etcdserver: request is too large\nattempt #9:data service DropVirtualChannel failed, reason = etcdserver: request is too large\nattempt #10:data service DropVirtualChannel failed, reason = etcdserver: request is too large\n"]
panic: All attempts results:
attempt #1:data service DropVirtualChannel failed, reason = etcdserver: request is too large
attempt #2:data service DropVirtualChannel failed, reason = etcdserver: request is too large
attempt #3:data service DropVirtualChannel failed, reason = etcdserver: request is too large
attempt #4:data service DropVirtualChannel failed, reason = etcdserver: request is too large
attempt #5:data service DropVirtualChannel failed, reason = etcdserver: request is too large
attempt #6:data service DropVirtualChannel failed, reason = etcdserver: request is too large
attempt #7:data service DropVirtualChannel failed, reason = etcdserver: request is too large
attempt #8:data service DropVirtualChannel failed, reason = etcdserver: request is too large
attempt #9:data service DropVirtualChannel failed, reason = etcdserver: request is too large
attempt #10:data service DropVirtualChannel failed, reason = etcdserver: request is too large

goroutine 23949 [running]:
github.com/milvus-io/milvus/internal/datanode.dropVirtualChannelFunc.func1(0xc0034f7400, 0x1a, 0x20)
	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_manager.go:698 +0x103e
github.com/milvus-io/milvus/internal/datanode.(*rendezvousFlushManager).startDropping.func1(0xc000669e40)
	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_manager.go:527 +0x1cb
created by github.com/milvus-io/milvus/internal/datanode.(*rendezvousFlushManager).startDropping
	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_manager.go:511 +0x7e

**Comment by yanliang567** [comment]
@zhuwenxing is this a known issue to us?
/assign @zhuwenxing

**Comment by xiaofan-luan** [comment]
@aakejiang is this is the same issue as the previous bug?

**Comment by xiaofan-luan** [comment]
seems that there are some atomic/idempotent issue  causing retry failure

**Comment by zhuwenxing** [comment]
> @zhuwenxing is this a known issue to us? /assign @zhuwenxing

I have not yet encountered a case where after etcd pod kill, etcd restores, but Milvus components do not.

**Comment by soothing-rain** [comment]
IMO it is related to: https://github.com/milvus-io/milvus/issues/16047

We are probably gonna escalate this issue.

**Comment by xiaofan-luan** [comment]
@wayblink pls help on check if #17386 help on this issue

**Comment by xiaofan-luan** [comment]
> 

Hi @angelapytao do you still have datanode log for that environment, still need to ensure which is key reason why this keyvalue is too large
