### ISSUE TITLE
[Bug]: [Nightly] Panic occurs during nightly tests reporting "set tSafe failed" when deleting collection

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#17265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 30610c4
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Panic occurs:

```
[2022/05/29 15:42:34.876 +00:00] [INFO] [task.go:647] ["Releasing tSafe in releaseCollectionTask..."] [collectionID=433543946712383489] [vDeltaChannel=by-dev-rootcoord-delta_62_433543946712383489v0]

[2022/05/29 15:42:34.876 +00:00] [INFO] [tsafe_replica.go:131] ["remove tSafe replica"] [vChannel=by-dev-rootcoord-delta_62_433543946712383489v0]

[2022/05/29 15:42:34.876 +00:00] [INFO] [partition.go:64] ["remove a segment from replica"] [collectionID=433543946712383489] [partitionID=433543946712383490] [segmentID=433543946816978945]

[2022/05/29 15:42:34.876 +00:00] [INFO] [segment.go:228] ["delete segment from memory"] [collectionID=433543946712383489] [partitionID=433543946712383490] [segmentID=433543946816978945]

[2022/05/29 15:42:34.876 +00:00] [INFO] [partition.go:64] ["remove a segment from replica"] [collectionID=433543946712383489] [partitionID=433543946712383490] [segmentID=433543946816978946]

[2022/05/29 15:42:34.876 +00:00] [INFO] [segment.go:228] ["delete segment from memory"] [collectionID=433543946712383489] [partitionID=433543946712383490] [segmentID=433543946816978946]

[2022/05/29 15:42:34.877 +00:00] [INFO] [collection.go:343] ["delete collection"] [collectionID=433543946712383489]

[2022/05/29 15:42:34.877 +00:00] [DEBUG] [flow_graph_service_time_node.go:53] ["type assertion failed for serviceTimeMsg because it's nil"]

panic: serviceTimeNode setTSafe timeout, collectionID = 433543946712383489, err = set tSafe failed, err = cannot found tSafer, vChannel = by-dev-rootcoord-dml_63_433543946712383489v1



goroutine 2559105 [running]:

github.com/milvus-io/milvus/internal/querynode.(*serviceTimeNode).Operate(0xc00f11d740, 0xc006861f80, 0x1, 0x1, 0x5b972d8, 0x0, 0x0)

        /go/src/github.com/milvus-io/milvus/internal/querynode/flow_graph_service_time_node.go:68 +0xa1a

github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work(0xc003c0eaf0)

        /go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:100 +0x214

created by github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start

        /go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:68 +0x55
```

### Expected Behavior

No panic

### Steps To Reproduce

```markdown
Nightly:

https://ci.milvus.io:18080/jenkins/blue/rest/organizations/jenkins/pipelines/milvus-nightly-ci/branches/master/runs/559/nodes/124/steps/166/log/?start=0
```

### Milvus Log

Milvus logs:

[artifacts-milvus-standalone-master-559-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/559/artifact/artifacts-milvus-standalone-master-559-pymilvus-e2e-logs.tar.gz)

panic log file:

ms-559-n-milvus-standalone-6b67c9cf5b-5lzhn_milvus-ci_standalone-4f965366fe82003fc6b227e99cba7bfb17c2ecb88c3bc8638cf8b8bb368bacbe.log

**Comment by yanliang567** [comment]
@soothing-rain could you please help to take a look?

/assign @soothing-rain 
/unassign

**Comment by binbinlv** [comment]
Has not been reproduced, so close it first, and will reopen it if it occurs in the future.
