### ISSUE TITLE
[Bug]: querynode terminated

### ISSUE THREAD

**Issue by WangErXiao** [milvus-io/milvus#17277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.2
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

[2022/05/30 05:59:56.663 +00:00] [DEBUG] [segment.go:313] ["do search on segment"] [segmentID=433464032149372929] [segmentType=3]
[2022/05/30 05:59:56.674 +00:00] [DEBUG] [segment.go:313] ["do search on segment"] [segmentID=433464032149372929] [segmentType=3]
terminate called after throwing an instance of 'terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively

**Comment by xiaofan-luan** [comment]
@WangErXiao hi there, what index are you using and what is the search/index parameter?

**Comment by WangErXiao** [comment]
index: ivf_pq,nlist = 1024
search: nq = 1 ,topk=300, nprobe= 60
data size: 60million
querynode: (8C 16G )* 14

**Comment by WangErXiao** [comment]
qps = 15

**Comment by xiaofan-luan** [comment]
> index: ivf_pq,nlist = 1024 search: nq = 1 ,topk=300, nprobe= 60 data size: 60million querynode: (8C 16G )* 14

Thanks, we are working on reproduction

**Comment by WangErXiao** [comment]
dimension = 64

**Comment by WangErXiao** [comment]
we have a scalar field , a enum (1,2,3,4),every has 15million

**Comment by xiaofan-luan** [comment]
> we have a scalar field , a enum (1,2,3,4),every has 15million

So you first filter with a enum(with only 1/4 of the data valid for search), am I correcty?

**Comment by WangErXiao** [comment]
sometime we may use 'or'，such as 1 or 2

**Comment by yanliang567** [comment]
@sunby I think you were working on this issue
/assign @sunby 
/unassign

**Comment by cydrain** [comment]
@WangErXiao can you paste the logs of query_node when this issue happen ?

**Comment by cydrain** [comment]
> seems to be a deadlock issue, @cydrain any idea on this

"terminate called recursively" will be reported in 2 scenarios:
1. unique_lock is used recursively
2. exception is thrown out in multi-thread but not caught correctly

Check all segcore code where unique_lock is used, there is no scenario 1,
so there should be some places where exception is thrown out in multi-thread.

**Comment by cydrain** [comment]
in the path from segcore to faiss search, see no multi-thread
```
#0  faiss::IndexIVF::search (this=0x55e6dd183f50, n=5, x=0x55e6dd2984c0, k=5, distances=0x55e6e1550b10, labels=0x55e6e09b5bf0, bitset=...) at IndexIVF.cpp:327
#1  0x00007f17b71240cb in milvus::knowhere::IVF::QueryImpl (this=0x55e6dd237910, n=5, data=0x55e6dd2984c0, k=5, distances=0x55e6e1550b10, labels=0x55e6e09b5bf0, config=..., bitset=...) at /home/caiyd/vec/milvus/cmake_build/3rdparty_download/knowhere-subbuild/src/knowhere_ep/knowhere/knowhere/index/vector_index/IndexIVF.cpp:329
#2  0x00007f17b7122faa in milvus::knowhere::IVF::Query (this=0x55e6dd237910, dataset_ptr=std::shared_ptr<milvus::knowhere::Dataset> (use count 1, weak count 0) = {...}, config=..., bitset=...) at /home/caiyd/vec/milvus/cmake_build/3rdparty_download/knowhere-subbuild/src/knowhere_ep/knowhere/knowhere/index/vector_index/IndexIVF.cpp:122
#3  0x00007f17b8e3941f in milvus::query::<lambda()>::operator()(void) const (__closure=0x7ffdd63c9d00) at /home/caiyd/vec/milvus/internal/core/src/query/SearchOnSealed.cpp:92
#4  0x00007f17b8e397af in milvus::query::SearchOnSealed (schema=..., record=..., search_info=..., query_data=0x55e6dd2984c0, num_queries=5, bitset=..., result=..., segment_id=-1) at /home/caiyd/vec/milvus/internal/core/src/query/SearchOnSealed.cpp:93
#5  0x00007f17b8d1d851 in milvus::segcore::SegmentSealedImpl::vector_search (this=0x55e6dd25f200, vec_count=100000, search_info=..., query_data=0x55e6dd2984c0, query_count=5, timestamp=18446744073709551615, bitset=..., output=...) at /home/caiyd/vec/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:323
#6  0x00007f17b8d9ed1a in milvus::query::ExecPlanNodeVisitor::VectorVisitorImpl<milvus::FloatVector> (this=0x7ffdd63ca2e0, node=...) at /home/caiyd/vec/milvus/internal/core/src/query/visitors/ExecPlanNodeVisitor.cpp:110
#7  0x00007f17b8d9d4d1 in milvus::query::ExecPlanNodeVisitor::visit (this=0x7ffdd63ca2e0, node=...) at /home/caiyd/vec/milvus/internal/core/src/query/visitors/ExecPlanNodeVisitor.cpp:154
#8  0x00007f17b8e5c77c in milvus::query::FloatVectorANNS::accept (this=0x55e6dd405d50, visitor=...) at /home/caiyd/vec/milvus/internal/core/src/query/generated/PlanNode.cpp:20
#9  0x00007f17b8d8d242 in milvus::query::ExecPlanNodeVisitor::get_moved_result (this=0x7ffdd63ca2e0, node=...) at /home/caiyd/vec/milvus/internal/core/src/query/generated/ExecPlanNodeVisitor.h:47
#10 0x00007f17b8d8b05a in milvus::segcore::SegmentInternalInterface::Search (this=0x55e6dd25f200, plan=0x55e6dd1fccd0, placeholder_group=..., timestamp=10000000) at /home/caiyd/vec/milvus/internal/core/src/segcore/SegmentInterface.cpp:105
#11 0x00007f17b8cdd85c in Search (c_segment=0x55e6dd25f200, c_plan=0x55e6dd1fccd0, c_placeholder_group=0x55e6dd1c88f0, timestamp=10000000, result=0x7ffdd63ca5d0, segment_id=-1) at /home/caiyd/vec/milvus/internal/core/src/segcore/segment_c.cpp:70
```

**Comment by cydrain** [comment]
```
[2022/05/30 05:59:56.663 +00:00] [DEBUG] [segment.go:313] ["do search on segment"] [segmentID=433464032149372929] [segmentType=3]
[2022/05/30 05:59:56.674 +00:00] [DEBUG] [segment.go:313] ["do search on segment"] [segmentID=433464032149372929] [segmentType=3]
```
@xige-16 do you know why one segment is searched twice?

**Comment by xiaofan-luan** [comment]
> ```
> [2022/05/30 05:59:56.663 +00:00] [DEBUG] [segment.go:313] ["do search on segment"] [segmentID=433464032149372929] [segmentType=3]
> [2022/05/30 05:59:56.674 +00:00] [DEBUG] [segment.go:313] ["do search on segment"] [segmentID=433464032149372929] [segmentType=3]
> ```
> 
> @xige-16 do you know why one segment is searched twice?

They have different timestamp and I guess concurrent search is highly possible for Java client

**Comment by xiaofan-luan** [comment]
> > ```
> > [2022/05/30 05:59:56.663 +00:00] [DEBUG] [segment.go:313] ["do search on segment"] [segmentID=433464032149372929] [segmentType=3]
> > [2022/05/30 05:59:56.674 +00:00] [DEBUG] [segment.go:313] ["do search on segment"] [segmentID=433464032149372929] [segmentType=3]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @xige-16 do you know why one segment is searched twice?
> 
> They have different timestamp and I guess concurrent search is highly possible for Java client

This doesn't mean that one single request search the segment twice

**Comment by xiaofan-luan** [comment]
@cydrain any progress on this one?
