### ISSUE TITLE
[Bug]: Milvus Pods restarting on Google Cloud after a big insert

### ISSUE THREAD

**Issue by kevinzezel** [milvus-io/milvus#17280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 
- Deployment mode(standalone or cluster): cluster on Google Cloud v2.0.2
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.0.2
- CPU/Memory: 3 nodes -> 64 cores / 512gb
```

### Current Behavior

I was inserting a base of 50 million embeddings with 512 dimensions by pymilvus v2.0.2. Everything went well and I managed to do the search. Then I realized I had forgotten to upload one of my indices. So i deleted the collection, create a new one and started to insert everything again. Suddenly the pymilvus stopped inserting and freeze. No errors appeared in python, only in milvus cluster. Logs:

```
[2022/05/30 12:48:30.615 +00:00] [INFO] [flow_graph_dd_node.go:136] ["Filtering Insert Messages"] ["Message endts"=433503327906955265] [FilterThreshold=433563865568247809]
[2022/05/30 12:48:30.650 +00:00] [INFO] [flow_graph_dd_node.go:136] ["Filtering Insert Messages"] ["Message endts"=433503328575422465] [FilterThreshold=433563865568247809]
[2022/05/30 12:48:30.650 +00:00] [INFO] [flow_graph_dd_node.go:136] ["Filtering Insert Messages"] ["Message endts"=433503328575422465] [FilterThreshold=433563865568247809]
[2022/05/30 12:48:30.650 +00:00] [INFO] [flow_graph_dd_node.go:136] ["Filtering Insert Messages"] ["Message endts"=433503328575422465] [FilterThreshold=433563865568247809]
[2022/05/30 12:48:30.667 +00:00] [INFO] [flow_graph_dd_node.go:136] ["Filtering Insert Messages"] ["Message endts"=433503328889995266] [FilterThreshold=433563865568247809]
[2022/05/30 12:48:30.667 +00:00] [INFO] [flow_graph_dd_node.go:136] ["Filtering Insert Messages"] ["Message endts"=433503328889995266] [FilterThreshold=433563865568247809]
[2022/05/30 12:48:30.667 +00:00] [INFO] [flow_graph_dd_node.go:136] ["Filtering Insert Messages"] ["Message endts"=433503328889995266] [FilterThreshold=433563865568247809]
[2022/05/30 12:48:30.753 +00:00] [INFO] [flow_graph_dd_node.go:136] ["Filtering Insert Messages"] ["Message endts"=433503330279358466] [FilterThreshold=433563865568247809]
[2022/05/30 12:48:30.753 +00:00] [INFO] [flow_graph_dd_node.go:136] ["Filtering Insert Messages"] ["Message endts"=433503330279358466] [FilterThreshold=433563865568247809]
[2022/05/30 12:48:30.753 +00:00] [INFO] [flow_graph_dd_node.go:136] ["Filtering Insert Messages"] ["Message endts"=433503330279358466] [FilterThreshold=433563865568247809]
[2022/05/30 12:48:34.707 +00:00] [WARN] [flush_manager.go:697] ["failed to DropVirtualChannel"] [channel=by-dev-rootcoord-dml_32_433500020147748865v0] [error="All attempts results:\nattempt #1:data service DropVirtualChannel failed, reason = rpc error: code = ResourceExhausted desc = trying to send message larger than max (4967850 vs. 2097152)\nattempt #2:data service DropVirtualChannel failed, reason = rpc error: code = ResourceExhausted desc = trying to send message larger than max (4961347 vs. 2097152)\nattempt #3:data service DropVirtualChannel failed, reason = rpc error: code = ResourceExhausted desc = trying to send message larger than max (5021698 vs. 2097152)\nattempt #4:data service DropVirtualChannel failed, reason = rpc error: code = ResourceExhausted desc = trying to send message larger than max (4961321 vs. 2097152)\nattempt #5:data service DropVirtualChannel failed, reason = rpc error: code = ResourceExhausted desc = trying to send message larger than max (5000166 vs. 2097152)\nattempt #6:data service DropVirtualChannel failed, reason = rpc error: code = ResourceExhausted desc = trying to send message larger than max (4963462 vs. 2097152)\nattempt #7:data service DropVirtualChannel failed, reason = rpc error: code = ResourceExhausted desc = trying to send message larger than max (5000133 vs. 2097152)\nattempt #8:data service DropVirtualChannel failed, reason = rpc error: code = ResourceExhausted desc = trying to send message larger than max (4961274 vs. 2097152)\nattempt #9:data service DropVirtualChannel failed, reason = rpc error: code = ResourceExhausted desc = trying to send message larger than max (4963513 vs. 2097152)\nattempt #10:data service DropVirtualChannel failed, reason = rpc error: code = ResourceExhausted desc = trying to send message larger than max (5002310 vs. 2097152)\n"]
panic: All attempts results:
attempt #1:data service DropVirtualChannel failed, reason = rpc error: code = ResourceExhausted desc = trying to send message larger than max (4967850 vs. 2097152)
attempt #2:data service DropVirtualChannel failed, reason = rpc error: code = ResourceExhausted desc = trying to send message larger than max (4961347 vs. 2097152)
attempt #3:data service DropVirtualChannel failed, reason = rpc error: code = ResourceExhausted desc = trying to send message larger than max (5021698 vs. 2097152)
attempt #4:data service DropVirtualChannel failed, reason = rpc error: code = ResourceExhausted desc = trying to send message larger than max (4961321 vs. 2097152)
attempt #5:data service DropVirtualChannel failed, reason = rpc error: code = ResourceExhausted desc = trying to send message larger than max (5000166 vs. 2097152)
attempt #6:data service DropVirtualChannel failed, reason = rpc error: code = ResourceExhausted desc = trying to send message larger than max (4963462 vs. 2097152)
attempt #7:data service DropVirtualChannel failed, reason = rpc error: code = ResourceExhausted desc = trying to send message larger than max (5000133 vs. 2097152)
attempt #8:data service DropVirtualChannel failed, reason = rpc error: code = ResourceExhausted desc = trying to send message larger than max (4961274 vs. 2097152)
attempt #9:data service DropVirtualChannel failed, reason = rpc error: code = ResourceExhausted desc = trying to send message larger than max (4963513 vs. 2097152)
attempt #10:data service DropVirtualChannel failed, reason = rpc error: code = ResourceExhausted desc = trying to send message larger than max (5002310 vs. 2097152)


goroutine 752 [running]:
github.com/milvus-io/milvus/internal/datanode.dropVirtualChannelFunc.func1(0xc0038c7000, 0x10e, 0x200)
	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_manager.go:698 +0x103e
github.com/milvus-io/milvus/internal/datanode.(*rendezvousFlushManager).startDropping.func1(0xc000693c30)
	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_manager.go:527 +0x1cb
created by github.com/milvus-io/milvus/internal/datanode.(*rendezvousFlushManager).startDropping
	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_manager.go:511 +0x7e

```
Python code:

```
from pymilvus import (
    connections,
    list_collections,
    FieldSchema, CollectionSchema, DataType,
    Collection, Index, utility
)

connections.connect("default", host=host_ip, port='19530')

collection_name = 'facerec_embeddings'

default_fields = [
    FieldSchema(name="id", dtype=DataType.INT64, is_primary=True, auto_id=True),
    FieldSchema(name="idx", dtype=DataType.INT64),
    FieldSchema(name="timestamp", dtype=DataType.INT64),
    FieldSchema(name="birthdate", dtype=DataType.INT64),
    FieldSchema(name="dif1", dtype=DataType.INT64),
    FieldSchema(name="dif2", dtype=DataType.INT64),
    FieldSchema(name="dif3", dtype=DataType.INT64),
    FieldSchema(name="embedding", dtype=DataType.FLOAT_VECTOR, dim=512)
]
default_schema = CollectionSchema(fields=default_fields, description="embedding collection")
collection = Collection(name=collection_name , schema=default_schema)
collection.load()

batch_size = 10000
num = math.ceil(data.shape[0]/batch_size)
for i in range(num):
        batch = data[i*batch_size:i*batch_size+batch_size].copy()
        mr = collection.insert(data=batch)

# Then I realized I had forgotten to upload one of my indices..

collection_name = 'facerec_embeddings'
utility.drop_collection(collection_name)

default_fields = [
    FieldSchema(name="id", dtype=DataType.INT64, is_primary=True, auto_id=True),
    FieldSchema(name="idx", dtype=DataType.INT64),
    FieldSchema(name="timestamp", dtype=DataType.INT64),
    FieldSchema(name="birthdate", dtype=DataType.INT64),
    FieldSchema(name="dif1", dtype=DataType.INT64),
    FieldSchema(name="dif2", dtype=DataType.INT64),
    FieldSchema(name="dif3", dtype=DataType.INT64),
    FieldSchema(name="dif4", dtype=DataType.INT64), # new 
    FieldSchema(name="embedding", dtype=DataType.FLOAT_VECTOR, dim=512)
]
default_schema = CollectionSchema(fields=default_fields, description="embedding collection")
collection = Collection(name=collection_name , schema=default_schema)
collection.load()


batch_size = 10000
num = math.ceil(data.shape[0]/batch_size)
for i in range(num):
        batch = data[i*batch_size:i*batch_size+batch_size].copy()
        mr = collection.insert(data=batch) # stopped after a few seconds
        


```

And now no command from pymilvus works, nor from milvus cli.

**Comment by xiaofan-luan** [comment]
seems to be same as #16657

**Comment by xiaofan-luan** [comment]
@aakejiang could you quickly double check if this is the same issue?

**Comment by aakejiang** [comment]
yes, same problem also happened in https://github.com/milvus-io/milvus/issues/16657 , @sunby will work on it

/assign @sunby 
/unassign
