### ISSUE TITLE
[Bug]: [benchmark][standalone]Milvus call has collection rasie error"StatusCode.UNAVAILABLE, failed to connect to all addresses”

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#17284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220530-c88514bc
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus==2.1.0.dev63
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server-instance
benchmark-cron-1653926400
server-configmap
server-single-16c64m
client-configmap
client-search-sift50m-ivf-flat-2048
The scenario is the same as issue: #16941, the error reporting is different
```
NAME                                                             READY   STATUS      RESTARTS   AGE     IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-cron-1653926400-6-etcd-0                               1/1     Running     0          2m21s   10.97.16.148   qa-node013.zilliz.local   <none>           <none>
benchmark-cron-1653926400-6-milvus-standalone-77cb4f87dd-8nwzb   1/1     Running     0          2m21s   10.97.20.78    qa-node018.zilliz.local   <none>           <none>
benchmark-cron-1653926400-6-minio-d8cc966d6-txfqf                1/1     Running     0          2m21s   10.97.16.146   qa-node013.zilliz.local   <none>           <none>
```

client
```
2022-05-30 18:30:27,474] [   DEBUG] - Start run query, run 1 of 30 (milvus_benchmark.runners.search:294)
[2022-05-30 18:30:27,475] [    INFO] - {'nq': 1000, 'topk': 10, 'search_param': {'nprobe': 32}, 'filter': [], 'guarantee_timestamp': None} (milvus_benchmark.runners.search:295)
[2022-05-30 18:30:27,476] [   ERROR] - grpc RpcError: [has_collection], <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>, <Time:{'RPC start': '2022-05-30 18:30:27.476443', 'gRPC error': '2022-05-30 18:30:27.476925'}> (pymilvus.decorators:84)
[2022-05-30 18:30:28,480] [   ERROR] - grpc RpcError: [has_collection], <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>, <Time:{'RPC start': '2022-05-30 18:30:28.478656', 'gRPC error': '2022-05-30 18:30:28.480388'}> (pymilvus.decorators:84)
[2022-05-30 18:30:29,483] [   ERROR] - grpc RpcError: [has_collection], <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>, <Time:{'RPC start': '2022-05-30 18:30:29.482405', 'gRPC error': '2022-05-30 18:30:29.483253'}> (pymilvus.decorators:84)
[2022-05-30 18:30:30,485] [   ERROR] - grpc RpcError: [has_collection], <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>, <Time:{'RPC start': '2022-05-30 18:30:30.484677', 'gRPC error': '2022-05-30 18:30:30.485488'}> (pymilvus.decorators:84)
[2022-05-30 18:30:31,493] [   ERROR] - grpc RpcError: [has_collection], <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>, <Time:{'RPC start': '2022-05-30 18:30:31.492650', 'gRPC error': '2022-05-30 18:30:31.493595'}> (pymilvus.decorators:84)
[2022-05-30 18:30:32,499] [   ERROR] - grpc RpcError: [has_collection], <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>, <Time:{'RPC start': '2022-05-30 18:30:32.498410', 'gRPC error': '2022-05-30 18:30:32.499218'}> (pymilvus.decorators:84)
[2022-05-30 18:30:33,898] [   ERROR] - grpc RpcError: [has_collection], <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>, <Time:{'RPC start': '2022-05-30 18:30:33.511306', 'gRPC error': '2022-05-30 18:30:33.896991'}> (pymilvus.decorators:84)
[2022-05-30 18:30:34,911] [   ERROR] - grpc RpcError: [has_collection], <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>, <Time:{'RPC start': '2022-05-30 18:30:34.905384', 'gRPC error': '2022-05-30 18:30:34.911675'}> (pymilvus.decorators:84)
[2022-05-30 18:30:35,917] [   ERROR] - grpc RpcError: [has_collection], <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>, <Time:{'RPC start': '2022-05-30 18:30:35.916913', 'gRPC error': '2022-05-30 18:30:35.917737'}> (pymilvus.decorators:84)
[2022-05-30 18:30:36,920] [   ERROR] - grpc RpcError: [has_collection], <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>, <Time:{'RPC start': '2022-05-30 18:30:36.919249', 'gRPC error': '2022-05-30 18:30:36.919927'}> (pymilvus.decorators:84)
[2022-05-30 18:30:36,920] [   ERROR] - RPC error: [search], <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1653935436.919548848","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":5419,"referenced_errors":[{"created":"@1653935433.896445936","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
>)>, <Time:{'RPC start': '2022-05-30 18:30:27.476188', 'RPC error': '2022-05-30 18:30:36.920720'}> (pymilvus.decorators:76)
[2022-05-30 18:30:36,921] [   ERROR] - Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 44, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 73, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 207, in has_collection
    reply = rf.result()
  File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1653935436.919548848","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":5419,"referenced_errors":[{"created":"@1653935433.896445936","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 95, in run_suite
    result = runner.run_case(case_metric, **case)
  File "/src/milvus_benchmark/runners/search.py", line 298, in run_case
    guarantee_timestamp=case_param["guarantee_timestamp"])
  File "/src/milvus_benchmark/client.py", line 50, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 325, in query
    result = self._milvus.search(tmp_collection_name, **params)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 842, in search
    partition_names, output_fields, timeout=timeout, round_decimal=round_decimal, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 59, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 44, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 77, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 73, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 429, in search
    if not self.has_collection(collection_name, timeout):
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 56, in handler
    raise MilvusException(Status.UNEXPECTED_ERROR, str(e))
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1653935436.919548848","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":5419,"referenced_errors":[{"created":"@1653935433.896445936","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
>)>
 (milvus_benchmark.main:98)
```

**Comment by jingkl** [comment]
```
perfix_expr = "varchar startsWith \"0\""
  @pytest.mark.tags(CaseLabel.L2)
    def test_search_string_field_not_primary_perfix(self, auto_id, _async):
        """
        target: test search with string expr and string field is not primary
        method: create collection and insert data 
                create index and collection load
                collection search uses string expr in string field, string field is not primary
        expected: Search successfully
        """
        # 1. initialize with data
        collection_w, _, _, insert_ids = \
            self.init_collection_general(prefix, True, auto_id=auto_id, dim=default_dim)[0:4]
        # data = cf.gen_default_list_data()
        # # data =cf.gen_default_string_data(ct.default_nb)
        # collection_w.insert(data)
        # collection_w.load()
        # 2. search
        log.info("test_search_string_field_not_primary: searching collection %s" % collection_w.name)
        vectors = [[random.random() for _ in range(default_dim)] for _ in range(default_nq)]
        output_fields = [default_string_field_name, default_float_field_name]
        collection_w.search(vectors[:default_nq], default_search_field,
                            default_search_params, default_limit, 
                            perfix_expr,
                            output_fields=output_fields,
                            _async=_async,
                            travel_timestamp=0
                            )
message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=4, reason=Search 4 failed, reason [UnexpectedError] unsupported operator type: 8 err %!w(<nil>)
```

**Comment by jingkl** [comment]
expression = 'int64 == varchar'
```

 raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Query, QueryNode ID = 5, reason=Query 5 failed, reason [UnexpectedError] Assert "incompitible data type" at /go/src/[github.com/milvus-io/milvus/internal/core/src/query/Relational.h:33](http://github.com/milvus-io/milvus/internal/core/src/query/Relational.h:33)
 err %!w(<nil>))>
 (api_request.py:35)
[2022-05-24 14:50:18 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Query, QueryNode ID = 5, reason=Query 5 failed, reason [UnexpectedError] Assert "incompitible data type" at /go/src/[github.com/milvus-io/milvus/internal/core/src/query/Relational.h:33](http://github.com/milvus-io/milvus/internal/core/src/query/Relational.h:33)
 err %!w(<nil>))> (api_request.py:36)
```

**Comment by yanliang567** [comment]
is it the same root cause of #17288 ? @congqixia 
/assign @congqixia 
/unassign

**Comment by congqixia** [comment]
Cannot find and log related to "benchmark-cron-1653926400-6-milvus-standalone-77cb4f87dd-8nwzb" in kibana. Anything wrong with the system?
@yanliang567

**Comment by jingkl** [comment]
The logs were not collected on this side one day @congqixia

**Comment by jingkl** [comment]
same as issue #17288
