### ISSUE TITLE
[Bug]: [benchmark][cluster] search raise error: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#17305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220531-72f454e0
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.0.dev67
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task: benchmark-cron-1654012800

test yaml:
client-configmap:client-acc-glove-ivf-flat,instanceId:5,server-configmap:server-cluster-8c16m

server:
```
NAME                                                              READY   STATUS      RESTARTS   AGE     IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-cron-1654012800-5-etcd-0                                1/1     Running     0          150m    10.97.16.104   qa-node013.zilliz.local   <none>           <none>
benchmark-cron-1654012800-5-etcd-1                                1/1     Running     0          150m    10.97.17.118   qa-node014.zilliz.local   <none>           <none>
benchmark-cron-1654012800-5-etcd-2                                1/1     Running     0          150m    10.97.16.106   qa-node013.zilliz.local   <none>           <none>
benchmark-cron-1654012800-5-milvus-datacoord-5d68fd56c9-nmll9     1/1     Running     0          150m    10.97.4.146    qa-node002.zilliz.local   <none>           <none>
benchmark-cron-1654012800-5-milvus-datanode-8699cc4b7d-mxjs2      1/1     Running     0          150m    10.97.20.210   qa-node018.zilliz.local   <none>           <none>
benchmark-cron-1654012800-5-milvus-indexcoord-66895d86d4-dz5b4    1/1     Running     0          150m    10.97.4.148    qa-node002.zilliz.local   <none>           <none>
benchmark-cron-1654012800-5-milvus-indexnode-586cf4c8c7-jgr9j     1/1     Running     0          150m    10.97.17.116   qa-node014.zilliz.local   <none>           <none>
benchmark-cron-1654012800-5-milvus-proxy-5d97c7cfd4-xngb8         1/1     Running     0          150m    10.97.4.147    qa-node002.zilliz.local   <none>           <none>
benchmark-cron-1654012800-5-milvus-querycoord-86b5f79d8c-5hs9k    1/1     Running     0          150m    10.97.5.15     qa-node003.zilliz.local   <none>           <none>
benchmark-cron-1654012800-5-milvus-querynode-767cc9b7dc-87qgb     1/1     Running     0          150m    10.97.16.101   qa-node013.zilliz.local   <none>           <none>
benchmark-cron-1654012800-5-milvus-rootcoord-7c95cf98cf-qp7wx     1/1     Running     0          150m    10.97.3.44     qa-node001.zilliz.local   <none>           <none>
benchmark-cron-1654012800-5-minio-0                               1/1     Running     0          150m    10.97.19.105   qa-node016.zilliz.local   <none>           <none>
benchmark-cron-1654012800-5-minio-1                               1/1     Running     0          150m    10.97.19.104   qa-node016.zilliz.local   <none>           <none>
benchmark-cron-1654012800-5-minio-2                               1/1     Running     0          150m    10.97.19.121   qa-node016.zilliz.local   <none>           <none>
benchmark-cron-1654012800-5-minio-3                               1/1     Running     0          150m    10.97.12.177   qa-node015.zilliz.local   <none>           <none>
benchmark-cron-1654012800-5-pulsar-bookie-0                       1/1     Running     0          150m    10.97.19.117   qa-node016.zilliz.local   <none>           <none>
benchmark-cron-1654012800-5-pulsar-bookie-1                       1/1     Running     0          150m    10.97.9.171    qa-node007.zilliz.local   <none>           <none>
benchmark-cron-1654012800-5-pulsar-bookie-2                       1/1     Running     0          150m    10.97.19.133   qa-node016.zilliz.local   <none>           <none>
benchmark-cron-1654012800-5-pulsar-bookie-init-thjjq              0/1     Completed   0          150m    10.97.3.45     qa-node001.zilliz.local   <none>           <none>
benchmark-cron-1654012800-5-pulsar-broker-0                       1/1     Running     0          150m    10.97.5.26     qa-node003.zilliz.local   <none>           <none>
benchmark-cron-1654012800-5-pulsar-proxy-0                        1/1     Running     0          150m    10.97.3.46     qa-node001.zilliz.local   <none>           <none>
benchmark-cron-1654012800-5-pulsar-pulsar-init-mfwxx              0/1     Completed   0          150m    10.97.18.137   qa-node017.zilliz.local   <none>           <none>
benchmark-cron-1654012800-5-pulsar-recovery-0                     1/1     Running     0          150m    10.97.12.170   qa-node015.zilliz.local   <none>           <none>
benchmark-cron-1654012800-5-pulsar-zookeeper-0                    1/1     Running     0          150m    10.97.9.167    qa-node007.zilliz.local   <none>           <none>
benchmark-cron-1654012800-5-pulsar-zookeeper-1                    1/1     Running     0          150m    10.97.18.145   qa-node017.zilliz.local   <none>           <none>
benchmark-cron-1654012800-5-pulsar-zookeeper-2                    1/1     Running     0          148m    10.97.11.118   qa-node009.zilliz.local   <none>           <none>
```

client pod:  benchmark-cron-1654012800-1191786796

client log:
```
[2022-05-31 17:38:52,100] [   DEBUG] - Milvus query run in 208.391s (milvus_benchmark.client:54)
[2022-05-31 17:42:09,081] [   DEBUG] - Milvus query run in 196.9717s (milvus_benchmark.client:54)
[2022-05-31 17:42:10,340] [    INFO] - {'acc': 0.978, 'search_rps': 196.97172284126282, 'rps_pv': 19.69717228412628} (milvus_benchmark.main:99)
[2022-05-31 17:42:10,341] [   DEBUG] - {'type': 'ann_accuracy', 'value': {'acc': 0.978, 'search_rps': 196.97172284126282, 'rps_pv': 19.69717228412628}} (milvus_benchmark.main:107)
[2022-05-31 17:42:10,342] [   DEBUG] - {'_version': '0.1', '_type': 'case', 'run_id': 1654021840, 'mode': 'local', 'server': <milvus_benchmark.metrics.models.server.Server object at 0x7efde45c77f0>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware object at 0x7efde45c7860>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7efde45c7940>, 'status': 'RUN_SUCC', 'err_message': '', 'collection': {'dimension': 200, 'metric_type': 'ip', 'dataset_name': 'glove_200_angular', 'shards_num': None}, 'index': {'index_type': 'ivf_flat', 'index_param': {'nlist': 1024}}, 'search': {'nq': 10000, 'topk': 10, 'search_param': {'nprobe': 256}, 'filter': [], 'guarantee_timestamp': None}, 'run_params': None, 'metrics': {'type': 'ann_accuracy', 'value': {'acc': 0.978, 'search_rps': 196.97172284126282, 'rps_pv': 19.69717228412628}}, 'datetime': '2022-05-31 16:07:21.589072', 'type': 'metric'} (milvus_benchmark.metric.api:30)
[2022-05-31 17:47:10,725] [   ERROR] - grpc RpcError: [_execute_search_requests], <_MultiThreadedRendezvous: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded>, <Time:{'RPC start': '2022-05-31 17:42:10.723390', 'gRPC error': '2022-05-31 17:47:10.725090'}> (pymilvus.decorators:86)
[2022-05-31 17:47:10,727] [   ERROR] - grpc RpcError: [search], <_MultiThreadedRendezvous: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded>, <Time:{'RPC start': '2022-05-31 17:42:10.356578', 'gRPC error': '2022-05-31 17:47:10.727078'}> (pymilvus.decorators:86)
[2022-05-31 17:47:10,733] [   ERROR] - Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 44, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 87, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 75, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 449, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 87, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 75, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 411, in _execute_search_requests
    raise pre_err
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 399, in _execute_search_requests
    response = ft.result()
  File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1654019230.724024641","description":"Error received from peer ipv4:10.96.244.24:19530","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 95, in run_suite
    result = runner.run_case(case_metric, **case)
  File "/src/milvus_benchmark/runners/accuracy.py", line 282, in run_case
    guarantee_timestamp=case_param["guarantee_timestamp"])
  File "/src/milvus_benchmark/client.py", line 50, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 325, in query
    result = self._milvus.search(tmp_collection_name, **params)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 842, in search
    partition_names, output_fields, timeout=timeout, round_decimal=round_decimal, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 52, in handler
    raise MilvusException(Status.UNEXPECTED_ERROR, str(e))
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1654019230.724024641","description":"Error received from peer ipv4:10.96.244.24:19530","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>)>
 (milvus_benchmark.main:98)
[2022-05-31 17:47:10,734] [    INFO] - None (milvus_benchmark.main:99)
[2022-05-31 17:47:10,734] [   DEBUG] - {'type': 'ann_accuracy', 'value': {}} (milvus_benchmark.main:107)
[2022-05-31 17:47:10,735] [   DEBUG] - {'_version': '0.1', '_type': 'case', 'run_id': 1654021840, 'mode': 'local', 'server': <milvus_benchmark.metrics.models.server.Server object at 0x7efde45c7e80>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware object at 0x7efde45c7da0>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7efde45c7cc0>, 'status': 'RUN_FAILED', 'err_message': '<MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.DEADLINE_EXCEEDED\n\tdetails = "Deadline Exceeded"\n\tdebug_error_string = "{"created":"@1654019230.724024641","description":"Error received from peer ipv4:10.96.244.24:19530","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Deadline Exceeded","grpc_status":4}"\n>)>\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 44, in handler\n    return func(self, *args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 87, in handler\n    raise e\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 75, in handler\n    return func(*args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 449, in search\n    return self._execute_search_requests(requests, timeout, **_kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 87, in handler\n    raise e\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 75, in handler\n    return func(*args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 411, in _execute_search_requests\n    raise pre_err\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 399, in _execute_search_requests\n    response = ft.result()\n  File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 744, in result\n    raise self\ngrpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.DEADLINE_EXCEEDED\n\tdetails = "Deadline Exceeded"\n\tdebug_error_string = "{"created":"@1654019230.724024641","description":"Error received from peer ipv4:10.96.244.24:19530","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Deadline Exceeded","grpc_status":4}"\n>\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "main.py", line 95, in run_suite\n    result = runner.run_case(case_metric, **case)\n  File "/src/milvus_benchmark/runners/accuracy.py", line 282, in run_case\n    guarantee_timestamp=case_param["guarantee_timestamp"])\n  File "/src/milvus_benchmark/client.py", line 50, in wrapper\n    result = func(*args, **kwargs)\n  File "/src/milvus_benchmark/client.py", line 325, in query\n    result = self._milvus.search(tmp_collection_name, **params)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 842, in search\n    partition_names, output_fields, timeout=timeout, round_decimal=round_decimal, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 52, in handler\n    raise MilvusException(Status.UNEXPECTED_ERROR, str(e))\npymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.DEADLINE_EXCEEDED\n\tdetails = "Deadline Exceeded"\n\tdebug_error_string = "{"created":"@1654019230.724024641","description":"Error received from peer ipv4:10.96.244.24:19530","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Deadline Exceeded","grpc_status":4}"\n>)>\n', 'collection': {'dimension': 200, 'metric_type': 'ip', 'dataset_name': 'glove_200_angular', 'shards_num': None}, 'index': {'index_type': 'ivf_flat', 'index_param': {'nlist': 1024}}, 'search': {'nq': 10000, 'topk': 10, 'search_param': {'nprobe': 512}, 'filter': [], 'guarantee_timestamp': None}, 'run_params': None, 'metrics': {'type': 'ann_accuracy', 'value': {}}, 'datetime': '2022-05-31 16:07:21.589072', 'type': 'metric'} (milvus_benchmark.metric.api:30)
[2022-05-31 17:47:10,745] [   DEBUG] - {'_version': '0.1', '_type': 'metric', 'run_id': 1654021840, 'mode': 'local', 'server': <milvus_benchmark.metrics.models.server.Server object at 0x7efde5e93cc0>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware object at 0x7efde5e93898>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7efde5e93dd8>, 'status': 'RUN_FAILED', 'err_message': '', 'collection': {'dimension': 200, 'metric_type': 'ip', 'dataset_name': 'glove_200_angular', 'shards_num': None}, 'index': {}, 'search': None, 'run_params': None, 'metrics': {'type': 'ann_accuracy', 'value': {}}, 'datetime': '2022-05-31 16:07:21.589072', 'type': 'metric'} (milvus_benchmark.metric.api:30)
```

### Anything else?

client-acc-glove-ivf-flat:
```
    ann_accuracy:
      collections:
        -
          source_file: /test/milvus/ann_hdf5/glove-200-angular.hdf5
          collection_name: glove_200_angular
          index_types: ['ivf_flat']
          index_params:
            nlist: [1024]
          top_ks: [10]
          nqs: [10000]
          search_params:
            nprobe: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512]
```

**Comment by wangting0128** [comment]
verify：master-20220606-f38637c2
