### ISSUE TITLE
[Bug]: Milvus run as mixture of multiple kinds of coordinators not working

### ISSUE THREAD

**Issue by haorenfsa** [milvus-io/milvus#17331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.0.2+
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

panic

### Expected Behavior

run successfully

### Steps To Reproduce

```markdown
milvus run mixture -rootcoord -datacoord
```

### Milvus Log

root@debug:/milvus# milvus run mixture -rootcoord -datacoord
2022/06/01 17:13:10 maxprocs: Updating GOMAXPROCS=4: determined from CPU quota
    __  _________ _   ____  ______
   /  |/  /  _/ /| | / / / / / __/
  / /|_/ // // /_| |/ / /_/ /\ \
 /_/  /_/___/____/___/\____/___/

Welcome to use Milvus!
Version:   a8b81e21
Built:     Wed May 11 14:02:31 UTC 2022
GitCommit: a8b81e21
GoVersion: go version go1.16.9 linux/amd64

open pid file: /run/milvus/mixture.pid
lock pid file: /run/milvus/mixture.pid
[2022/06/01 17:13:10.287 +00:00] [INFO] [roles.go:349] ["starting running Milvus components"]
[2022/06/01 17:13:10.289 +00:00] [DEBUG] [component_param.go:757] ["init cacheSize"] ["cacheSize (GB)"=0]
[2022/06/01 17:13:10.289 +00:00] [DEBUG] [component_param.go:789] ["query node init gracefulTime"] [gracefulTime=0]
[2022/06/01 17:13:10.294 +00:00] [DEBUG] [grpc_param.go:150] [initServerMaxSendSize] [role=rootcoord] [grpc.serverMaxSendSize=2147483647]
[2022/06/01 17:13:10.294 +00:00] [DEBUG] [grpc_param.go:174] [initServerMaxRecvSize] [role=rootcoord] [grpc.serverMaxRecvSize=2147483647]
[2022/06/01 17:13:10.294 +00:00] [DEBUG] [service.go:157] ["init params done.."]
[2022/06/01 17:13:10.295 +00:00] [DEBUG] [component_param.go:757] ["init cacheSize"] ["cacheSize (GB)"=0]
[2022/06/01 17:13:10.295 +00:00] [DEBUG] [component_param.go:789] ["query node init gracefulTime"] [gracefulTime=0]
panic: http: multiple registrations for /healthz

goroutine 147 [running]:
net/http.(*ServeMux).Handle(0x5556b80, 0x3c652dd, 0x8, 0x3fa3c60, 0xc000569b40)
	/usr/local/go/src/net/http/server.go:2444 +0x2c5
net/http.Handle(...)
	/usr/local/go/src/net/http/server.go:2487
[github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runDataCoord.func1](http://github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runDataCoord.func1)(0xc00048f700, 0x3fdb110, 0xc000450400, 0xc0005e7fc8, 0xc0004ee870)
	/go/src/[github.com/milvus-io/milvus/cmd/roles/roles.go:239](http://github.com/milvus-io/milvus/cmd/roles/roles.go:239) +0x212
created by [github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runDataCoord](http://github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runDataCoord)
	/go/src/[github.com/milvus-io/milvus/cmd/roles/roles.go:222](http://github.com/milvus-io/milvus/cmd/roles/roles.go:222) +0xb0
root@etcd-debug:/milvus# command terminated with exit code 137

**Comment by yanliang567** [comment]
@xiaofan-luan could you please have someone take look at this issue? I think it blocks us from further testing

/assign @xiaofan-luan 
/unassign

**Comment by haorenfsa** [comment]
Testing: milvus-io/milvus-operator#143

**Comment by haorenfsa** [comment]
Fixed
