### ISSUE TITLE
[Bug]: Search failed with error message `code=1, message=fail to search on all shard leaders, err=err: context deadline exceeded` after Milvus recovered from querynode pod kill chaos

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#17367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220602-48cf63a2
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.1.0.dev66
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

run hello_milvus after chaos
```
Traceback (most recent call last):
  File "chaos/scripts/hello_milvus.py", line 116, in <module>
    hello_milvus(args.host)
  File "chaos/scripts/hello_milvus.py", line 89, in hello_milvus
    res = collection.search(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 689, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line [61](https://github.com/milvus-io/milvus/runs/6730847207?check_suite_focus=true#step:14:62), in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x[64](https://github.com/milvus-io/milvus/runs/6730847207?check_suite_focus=true#step:14:65)/lib/python3.8/site-packages/pymilvus/decorators.py", line 44, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 79, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 75, in handler
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 449, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 79, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 75, in handler
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 411, in _execute_search_requests
    raise pre_err
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 402, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=err: context deadline exceeded
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:226 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).Call
/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:222 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Search
/go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:416 github.com/milvus-io/milvus/internal/proxy.(*searchTask).searchShard.func1
/go/src/github.com/milvus-io/milvus/internal/proxy/task_policies.go:55 github.com/milvus-io/milvus/internal/proxy.roundRobinPolicy
/go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:434 github.com/milvus-io/milvus/internal/proxy.(*searchTask).searchShard
/go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:297 github.com/milvus-io/milvus/internal/proxy.(*searchTask).Execute.func1.1
/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-03[68](https://github.com/milvus-io/milvus/runs/6730847207?check_suite_focus=true#step:14:69)12b2e83c/errgroup/errgroup.go:57 golang.org/x/sync/errgroup.(*Group).Go.func1
/usr/local/go/src/runtime/asm_amd64.s:13[71](https://github.com/milvus-io/milvus/runs/6730847207?check_suite_focus=true#step:14:72) runtime.goexit
)>
```

### Expected Behavior

all test cases passed

### Steps To Reproduce

```markdown
see https://github.com/milvus-io/milvus/runs/6730847207?check_suite_focus=true
```

### Milvus Log

failed job: https://github.com/milvus-io/milvus/runs/6730847207?check_suite_focus=true
log: https://github.com/milvus-io/milvus/suites/6786357679/artifacts/260131722

failed job: https://github.com/milvus-io/milvus/runs/6746619192?check_suite_focus=true
log: https://github.com/milvus-io/milvus/suites/6800772748/artifacts/261201964

### Anything else?

This issue appears stably

**Comment by zhuwenxing** [comment]
failed job: http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/6086/pipeline
log: [artifacts-querynode-pod-kill-6086-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/8841481/artifacts-querynode-pod-kill-6086-server-logs.tar.gz)

**Comment by congqixia** [comment]
@jiaoew1991 could you please help investigate this?
/unassign @yanliang567 
/assgin @jiaoew1991

**Comment by jiaoew1991** [comment]
By analyzing the log, we can find that the proxy tries to use the old querynode ip: **10.244.0.18**, the real querynode ip is **10.244.0.70**

![image](https://user-images.githubusercontent.com/2297455/172130006-c0606a4e-4ef0-4fa3-9efa-b6e7aaf437da.png)

from the code in the proxy/task_search.go, we can find that error handler did not handle this case correctly (cached shard leader caused grpc timeout). 
<img width="725" alt="image" src="https://user-images.githubusercontent.com/2297455/172130202-476b7cea-581b-410c-bc4a-4320e7157f04.png">

We need to add more error handling logic

**Comment by congqixia** [comment]
@zhuwenxing could you please verify after commit de8f2f76
/unassign @jiaoew1991 
/assign @zhuwenxing

**Comment by zhuwenxing** [comment]
in version `master-20220607-af108b5b`, it still failed.
failed job: http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/6267/pipeline

log: [artifacts-querynode-pod-kill-6267-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/8858083/artifacts-querynode-pod-kill-6267-server-logs.1.tar.gz)


```

[2022-06-08T02:48:49.360Z] Search...

[2022-06-08T02:48:49.360Z] Traceback (most recent call last):

[2022-06-08T02:48:49.360Z]   File "scripts/hello_milvus.py", line 116, in <module>

[2022-06-08T02:48:49.360Z]     hello_milvus(args.host)

[2022-06-08T02:48:49.360Z]   File "scripts/hello_milvus.py", line 91, in hello_milvus

[2022-06-08T02:48:49.360Z]     "int64 > 100", output_fields=["int64", "float"], timeout=TIMEOUT

[2022-06-08T02:48:49.360Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 690, in search

[2022-06-08T02:48:49.360Z]     partition_names, output_fields, round_decimal, timeout=timeout, **kwargs)

[2022-06-08T02:48:49.360Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 61, in handler

[2022-06-08T02:48:49.360Z]     raise e

[2022-06-08T02:48:49.360Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 44, in handler

[2022-06-08T02:48:49.360Z]     return func(self, *args, **kwargs)

[2022-06-08T02:48:49.360Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 79, in handler

[2022-06-08T02:48:49.360Z]     raise e

[2022-06-08T02:48:49.360Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 75, in handler

[2022-06-08T02:48:49.360Z]     return func(*args, **kwargs)

[2022-06-08T02:48:49.360Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 449, in search

[2022-06-08T02:48:49.360Z]     return self._execute_search_requests(requests, timeout, **_kwargs)

[2022-06-08T02:48:49.360Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 79, in handler

[2022-06-08T02:48:49.360Z]     raise e

[2022-06-08T02:48:49.360Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 75, in handler

[2022-06-08T02:48:49.360Z]     return func(*args, **kwargs)

[2022-06-08T02:48:49.360Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 411, in _execute_search_requests

[2022-06-08T02:48:49.360Z]     raise pre_err

[2022-06-08T02:48:49.360Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 402, in _execute_search_requests

[2022-06-08T02:48:49.360Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2022-06-08T02:48:49.361Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=err: failed to connect 10.97.5.7:21123, reason: context deadline exceeded

[2022-06-08T02:48:49.361Z] , /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace

[2022-06-08T02:48:49.361Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:226 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).Call

[2022-06-08T02:48:49.361Z] /go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:222 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Search

[2022-06-08T02:48:49.361Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:417 github.com/milvus-io/milvus/internal/proxy.(*searchTask).searchShard.func1

[2022-06-08T02:48:49.361Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_policies.go:55 github.com/milvus-io/milvus/internal/proxy.roundRobinPolicy

[2022-06-08T02:48:49.361Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:436 github.com/milvus-io/milvus/internal/proxy.(*searchTask).searchShard

[2022-06-08T02:48:49.361Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:298 github.com/milvus-io/milvus/internal/proxy.(*searchTask).Execute.func1.1

[2022-06-08T02:48:49.361Z] /go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 golang.org/x/sync/errgroup.(*Group).Go.func1

[2022-06-08T02:48:49.361Z] /usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit
```

**Comment by zhuwenxing** [comment]
/assign @jiaoew1991 
/assign @congqixia 
This is still stable to reproduce

**Comment by zhuwenxing** [comment]
Milvus version `master-20220608-6d078ebe`

failed job: https://github.com/milvus-io/milvus/runs/6800569525?check_suite_focus=true
log: https://github.com/milvus-io/milvus/suites/6850926209/artifacts/264489127

log
```
[2022/06/08 19:51:55.347 +00:00] [WARN] [task_search.go:438] ["fail to search to all shard leaders"] ["shard leaders"="[{}]"]
[2022/06/08 19:51:55.347 +00:00] [DEBUG] [time_recorder.go:78] ["proxy execute search 433774259137470359: done (5002ms)"]
Error: 6/08 19:51:55.347 +00:00] [ERROR] [task_scheduler.go:468] ["Failed to execute task: fail to search on all shard leaders, err=err: failed to connect 10.244.0.13:21123, reason: context deadline exceeded\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:226 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).Call\n/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:222 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Search\n/go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:417 github.com/milvus-io/milvus/internal/proxy.(*searchTask).searchShard.func1\n/go/src/github.com/milvus-io/milvus/internal/proxy/task_policies.go:55 github.com/milvus-io/milvus/internal/proxy.roundRobinPolicy\n/go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:436 github.com/milvus-io/milvus/internal/proxy.(*searchTask).searchShard\n/go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:298 github.com/milvus-io/milvus/internal/proxy.(*searchTask).Execute.func1.1\n/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 golang.org/x/sync/errgroup.(*Group).Go.func1\n/usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit\n"] [traceID=44b17fc49a0a4407] [stack="github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:468"]
[2022/06/08 19:51:55.348 +00:00] [WARN] [impl.go:2488] ["Search failed to WaitToFinish"] [error="fail to search on all shard leaders, err=err: failed to connect 10.244.0.13:21123, reason: context deadline exceeded\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:226 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).Call\n/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:222 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Search\n/go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:417 github.com/milvus-io/milvus/internal/proxy.(*searchTask).searchShard.func1\n/go/src/github.com/milvus-io/milvus/internal/proxy/task_policies.go:55 github.com/milvus-io/milvus/internal/proxy.roundRobinPolicy\n/go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:436 github.com/milvus-io/milvus/internal/proxy.(*searchTask).searchShard\n/go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:298 github.com/milvus-io/milvus/internal/proxy.(*searchTask).Execute.func1.1\n/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 golang.org/x/sync/errgroup.(*Group).Go.func1\n/usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit\n"] [traceID=44b17fc49a0a4407] [role=proxy] [msgID=433774259137470359] [db=] [collection=hello_milvus] [partitions="[]"] [dsl="int64 > 100"] [len(PlaceholderGroup)=1039] [OutputFields="[int64,float]"] [search_params="[{\"key\":\"anns_field\",\"value\":\"float_vector\"},{\"key\":\"topk\",\"value\":\"5\"},{\"key\":\"metric_type\",\"value\":\"L2\"},{\"key\":\"params\",\"value\":\"{\\\"nprobe\\\":10}\"},{\"key\":\"round_decimal\",\"value\":\"-1\"}]"] [travel_timestamp=0] [guarantee_timestamp=2]
```

**Comment by zhuwenxing** [comment]
It still failed after waiting for 120s after all pods were ready.
https://github.com/zhuwenxing/milvus/runs/6805488544?check_suite_focus=true

error message `message=fail to search on all shard leaders, err=err: failed to connect 10.244.0.20:21123`

**Comment by jiaoew1991** [comment]
from the querycoord's log, we can find it's caused by loadBalanceTask failed. 
<img width="1329" alt="image" src="https://user-images.githubusercontent.com/2297455/172821386-301a283e-c0fb-4b65-a73f-3df4568f6199.png">

in loadBalanceTask.getReplica this error is sent to the upper layer, which will cause the task to be unable to be consumed and executed infinitely
Finally rebalance will never be triggered, causing ShardLeader never be updated

**Comment by jiaoew1991** [comment]
https://github.com/milvus-io/milvus/pull/17484 fix the error handling, related to this issue too

**Comment by zhuwenxing** [comment]
There are still cases of search failure, but now it is not 100%.
failed job: http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/6444/pipeline
log: [artifacts-querynode-pod-kill-6444-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/8890705/artifacts-querynode-pod-kill-6444-server-logs.tar.gz)

**Comment by zhuwenxing** [comment]
/assign @jiaoew1991 
Please help to take a look

**Comment by zhuwenxing** [comment]
failed job: http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/6476/pipeline
log:  [artifacts-querynode-pod-kill-6476-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/8896175/artifacts-querynode-pod-kill-6476-server-logs.tar.gz)

**Comment by jiaoew1991** [comment]
fix by #17546

**Comment by zhuwenxing** [comment]
@jiaoew1991 @congqixia 
for now, this one `context deadline exceeded` is not reproduced yet, but there are still some other issues about search failure caused by querynode pod kill or pod failure.
please help to take a look.
related issues:
https://github.com/milvus-io/milvus/issues/17203
https://github.com/milvus-io/milvus/issues/17556

**Comment by yah01** [comment]
/assign @zhuwenxing 
should be fixed with #17560

**Comment by zhuwenxing** [comment]
/assign @yah01

in version `master-20220616-53a49a92`, search failed when running `verify_all_collections.py` with same error message

failed job: https://github.com/milvus-io/milvus/runs/6924247539?check_suite_focus=true
log: https://github.com/milvus-io/milvus/suites/6967316556/artifacts/272180536

**Comment by yah01** [comment]
> /assign @yah01
> 
> in version `master-20220616-53a49a92`, search failed when running `verify_all_collections.py` with same error message
> 
> failed job: https://github.com/milvus-io/milvus/runs/6924247539?check_suite_focus=true log: https://github.com/milvus-io/milvus/suites/6967316556/artifacts/272180536

/assign @zhuwenxing 
looks same as #17556, #17608 should fix this.

**Comment by yah01** [comment]
/assign @zhuwenxing 
Fix patch #17616,
it is ready to be verified now

**Comment by yah01** [comment]
/assign @zhuwenxing 
same as #17553
