### ISSUE TITLE
[Bug]: [benchmark][cluster] Load 1 million vectors failed: collection sift_1m_128_l2 has not been loaded to memory or load failed

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#17371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220602-48cf63a2
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.0.dev67
- OS(Ubuntu or CentOS):  
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task: benchmark-cluster-cron-1654376400

test yaml:
client-configmap:client-search-locust,instanceId:3,server-configmap:server-cluster-8c16m

server:
```
NAME                                                              READY   STATUS      RESTARTS   AGE     IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-cluster-cron-1654376400-3-etcd-0                        1/1     Running     0          3h2m    10.97.16.141   qa-node013.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654376400-3-etcd-1                        1/1     Running     0          3h2m    10.97.17.25    qa-node014.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654376400-3-etcd-2                        1/1     Running     0          3h2m    10.97.16.144   qa-node013.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654376400-3-milvus-datacoord-68cc45d85c   1/1     Running     0          3h2m    10.97.4.129    qa-node002.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654376400-3-milvus-datanode-698645flwxb   1/1     Running     1          3h2m    10.97.20.50    qa-node018.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654376400-3-milvus-indexcoord-d7bbh5f5f   1/1     Running     0          3h2m    10.97.9.63     qa-node007.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654376400-3-milvus-indexnode-79b8chwbq8   1/1     Running     0          3h2m    10.97.17.21    qa-node014.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654376400-3-milvus-proxy-6cc9c79ccvqrsq   1/1     Running     0          3h2m    10.97.9.66     qa-node007.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654376400-3-milvus-querycoord-7f85c5ccv   1/1     Running     0          3h2m    10.97.4.128    qa-node002.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654376400-3-milvus-querynode-84fdfkj8p6   1/1     Running     0          3h2m    10.97.11.119   qa-node009.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654376400-3-milvus-rootcoord-55465xgvk4   1/1     Running     0          3h2m    10.97.4.127    qa-node002.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654376400-3-minio-0                       1/1     Running     0          3h2m    10.97.12.101   qa-node015.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654376400-3-minio-1                       1/1     Running     0          3h2m    10.97.12.103   qa-node015.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654376400-3-minio-2                       1/1     Running     0          3h2m    10.97.12.104   qa-node015.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654376400-3-minio-3                       1/1     Running     0          3h2m    10.97.12.105   qa-node015.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654376400-3-pulsar-bookie-0               1/1     Running     0          3h2m    10.97.3.43     qa-node001.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654376400-3-pulsar-bookie-1               1/1     Running     0          3h2m    10.97.9.70     qa-node007.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654376400-3-pulsar-bookie-2               1/1     Running     0          3h2m    10.97.3.46     qa-node001.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654376400-3-pulsar-bookie-init-n6k9f      0/1     Completed   0          3h2m    10.97.9.65     qa-node007.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654376400-3-pulsar-broker-0               1/1     Running     0          3h2m    10.97.12.102   qa-node015.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654376400-3-pulsar-proxy-0                1/1     Running     0          3h2m    10.97.12.107   qa-node015.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654376400-3-pulsar-pulsar-init-qdtdc      0/1     Completed   0          3h2m    10.97.9.64     qa-node007.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654376400-3-pulsar-recovery-0             1/1     Running     0          3h2m    10.97.12.106   qa-node015.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654376400-3-pulsar-zookeeper-0            1/1     Running     0          3h2m    10.97.3.42     qa-node001.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654376400-3-pulsar-zookeeper-1            1/1     Running     0          3h1m    10.97.9.72     qa-node007.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654376400-3-pulsar-zookeeper-2            1/1     Running     0          3h      10.97.9.74     qa-node007.zilliz.local   <none>           <none>
```

client pod: benchmark-cluster-cron-1654376400-900859666

client log:
```
[2022-06-04 21:11:42,045] [    INFO] - Prepare to run cases (milvus_benchmark.main:86)
[2022-06-04 21:11:42,068] [   DEBUG] - Milvus exists_collection run in 0.0219s (milvus_benchmark.client:54)
[2022-06-04 21:11:42,233] [    INFO] - Create collection: <sift_1m_128_l2> successfully (milvus_benchmark.client:150)
[2022-06-04 21:11:42,235] [   DEBUG] - Milvus create_collection run in 0.1661s (milvus_benchmark.client:54)
[2022-06-04 21:11:42,235] [    INFO] - Building index start, collection_name: sift_1m_128_l2, index_type: IVF_SQ8, metric_type: L2 (milvus_benchmark.client:277)
[2022-06-04 21:11:42,236] [    INFO] - {'nlist': 1024} (milvus_benchmark.client:279)
[2022-06-04 21:11:42,237] [   DEBUG] - collection: sift_1m_128_l2 Index params: {'index_type': 'IVF_SQ8', 'metric_type': 'L2', 'params': {'nlist': 1024}} (milvus_benchmark.client:285)
[2022-06-04 21:11:42,790] [   DEBUG] - Building index done, collection_name: sift_1m_128_l2, response: Status(code=0, message='') (milvus_benchmark.client:287)
[2022-06-04 21:11:42,832] [   DEBUG] - Milvus create_index run in 0.5967s (milvus_benchmark.client:54)
[2022-06-04 21:11:42,836] [    INFO] - None (milvus_benchmark.client:294)
[2022-06-04 21:11:42,837] [   DEBUG] - {'index_type': 'flat', 'metric_type': None, 'index_param': None} (milvus_benchmark.runners.locust:299)
[2022-06-04 21:11:42,840] [   DEBUG] - Milvus get_info run in 0.0028s (milvus_benchmark.client:54)
[2022-06-04 21:11:44,225] [   DEBUG] - Start id: 0, end id: 50000 (milvus_benchmark.runners.base:76)
[2022-06-04 21:11:47,646] [   DEBUG] - Milvus insert run in 3.4156s (milvus_benchmark.client:54)
[2022-06-04 21:11:47,654] [   DEBUG] - Row count: 0 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-04 21:11:47,655] [   DEBUG] - 0 (milvus_benchmark.runners.base:90)
[2022-06-04 21:11:48,233] [   DEBUG] - Start id: 50000, end id: 100000 (milvus_benchmark.runners.base:76)
[2022-06-04 21:11:51,354] [   DEBUG] - Milvus insert run in 3.1184s (milvus_benchmark.client:54)
[2022-06-04 21:11:51,358] [   DEBUG] - Row count: 0 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-04 21:11:51,358] [   DEBUG] - 0 (milvus_benchmark.runners.base:90)
[2022-06-04 21:11:52,761] [   DEBUG] - Start id: 100000, end id: 150000 (milvus_benchmark.runners.base:76)
[2022-06-04 21:11:56,358] [   DEBUG] - Milvus insert run in 3.5942s (milvus_benchmark.client:54)
[2022-06-04 21:11:56,370] [   DEBUG] - Row count: 100000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-04 21:11:56,370] [   DEBUG] - 100000 (milvus_benchmark.runners.base:90)
[2022-06-04 21:11:57,006] [   DEBUG] - Start id: 150000, end id: 200000 (milvus_benchmark.runners.base:76)
[2022-06-04 21:12:00,049] [   DEBUG] - Milvus insert run in 3.0399s (milvus_benchmark.client:54)
[2022-06-04 21:12:00,053] [   DEBUG] - Row count: 100000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-04 21:12:00,054] [   DEBUG] - 100000 (milvus_benchmark.runners.base:90)
[2022-06-04 21:12:01,524] [   DEBUG] - Start id: 200000, end id: 250000 (milvus_benchmark.runners.base:76)
[2022-06-04 21:12:04,643] [   DEBUG] - Milvus insert run in 3.0175s (milvus_benchmark.client:54)
[2022-06-04 21:12:05,029] [   DEBUG] - Row count: 200000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-04 21:12:05,030] [   DEBUG] - 200000 (milvus_benchmark.runners.base:90)
[2022-06-04 21:12:05,666] [   DEBUG] - Start id: 250000, end id: 300000 (milvus_benchmark.runners.base:76)
[2022-06-04 21:12:08,743] [   DEBUG] - Milvus insert run in 3.0744s (milvus_benchmark.client:54)
[2022-06-04 21:12:08,749] [   DEBUG] - Row count: 200000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-04 21:12:08,750] [   DEBUG] - 200000 (milvus_benchmark.runners.base:90)
[2022-06-04 21:12:09,893] [   DEBUG] - Start id: 300000, end id: 350000 (milvus_benchmark.runners.base:76)
[2022-06-04 21:12:13,304] [   DEBUG] - Milvus insert run in 3.0376s (milvus_benchmark.client:54)
[2022-06-04 21:12:13,317] [   DEBUG] - Row count: 300000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[2022-06-04 21:12:13,319] [   DEBUG] - 300000 (milvus_benchmark.runners.base:90)
[2022-06-04 21:12:13,771] [   DEBUG] - Start id: 350000, end id: 400000 (milvus_benchmark.runners.base:76)
[2022-06-04 21:12:16,747] [   DEBUG] - Milvus insert run in 2.9279s (milvus_benchmark.client:54)
[2022-06-04 21:12:16,752] [   DEBUG] - Row count: 300000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-04 21:12:16,753] [   DEBUG] - 300000 (milvus_benchmark.runners.base:90)
[2022-06-04 21:12:18,025] [   DEBUG] - Start id: 400000, end id: 450000 (milvus_benchmark.runners.base:76)
[2022-06-04 21:12:20,916] [   DEBUG] - Milvus insert run in 2.8859s (milvus_benchmark.client:54)
[2022-06-04 21:12:20,935] [   DEBUG] - Row count: 400000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-04 21:12:20,937] [   DEBUG] - 400000 (milvus_benchmark.runners.base:90)
[2022-06-04 21:12:21,822] [   DEBUG] - Start id: 450000, end id: 500000 (milvus_benchmark.runners.base:76)
[2022-06-04 21:12:24,855] [   DEBUG] - Milvus insert run in 3.0299s (milvus_benchmark.client:54)
[2022-06-04 21:12:24,860] [   DEBUG] - Row count: 400000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-04 21:12:24,861] [   DEBUG] - 400000 (milvus_benchmark.runners.base:90)
[2022-06-04 21:12:26,970] [   DEBUG] - Start id: 500000, end id: 550000 (milvus_benchmark.runners.base:76)
[2022-06-04 21:12:29,869] [   DEBUG] - Milvus insert run in 2.8956s (milvus_benchmark.client:54)
[2022-06-04 21:12:29,882] [   DEBUG] - Row count: 500000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-04 21:12:29,884] [   DEBUG] - 500000 (milvus_benchmark.runners.base:90)
[2022-06-04 21:12:30,351] [   DEBUG] - Start id: 550000, end id: 600000 (milvus_benchmark.runners.base:76)
[2022-06-04 21:12:33,265] [   DEBUG] - Milvus insert run in 2.9106s (milvus_benchmark.client:54)
[2022-06-04 21:12:33,269] [   DEBUG] - Row count: 500000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-04 21:12:33,270] [   DEBUG] - 500000 (milvus_benchmark.runners.base:90)
[2022-06-04 21:12:34,317] [   DEBUG] - Start id: 600000, end id: 650000 (milvus_benchmark.runners.base:76)
[2022-06-04 21:12:37,247] [   DEBUG] - Milvus insert run in 2.9266s (milvus_benchmark.client:54)
[2022-06-04 21:12:37,746] [   DEBUG] - Row count: 600000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-04 21:12:37,812] [   DEBUG] - 600000 (milvus_benchmark.runners.base:90)
[2022-06-04 21:12:38,363] [   DEBUG] - Start id: 650000, end id: 700000 (milvus_benchmark.runners.base:76)
[2022-06-04 21:12:41,373] [   DEBUG] - Milvus insert run in 3.0062s (milvus_benchmark.client:54)
[2022-06-04 21:12:41,377] [   DEBUG] - Row count: 600000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-04 21:12:41,378] [   DEBUG] - 600000 (milvus_benchmark.runners.base:90)
[2022-06-04 21:12:43,126] [   DEBUG] - Start id: 700000, end id: 750000 (milvus_benchmark.runners.base:76)
[2022-06-04 21:12:46,141] [   DEBUG] - Milvus insert run in 3.0101s (milvus_benchmark.client:54)
[2022-06-04 21:12:46,153] [   DEBUG] - Row count: 700000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-04 21:12:46,154] [   DEBUG] - 700000 (milvus_benchmark.runners.base:90)
[2022-06-04 21:12:46,971] [   DEBUG] - Start id: 750000, end id: 800000 (milvus_benchmark.runners.base:76)
[2022-06-04 21:12:49,929] [   DEBUG] - Milvus insert run in 2.9368s (milvus_benchmark.client:54)
[2022-06-04 21:12:49,934] [   DEBUG] - Row count: 700000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-04 21:12:49,936] [   DEBUG] - 700000 (milvus_benchmark.runners.base:90)
[2022-06-04 21:12:51,839] [   DEBUG] - Start id: 800000, end id: 850000 (milvus_benchmark.runners.base:76)
[2022-06-04 21:12:54,916] [   DEBUG] - Milvus insert run in 3.0738s (milvus_benchmark.client:54)
[2022-06-04 21:12:54,932] [   DEBUG] - Row count: 800000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-04 21:12:54,933] [   DEBUG] - 800000 (milvus_benchmark.runners.base:90)
[2022-06-04 21:12:55,718] [   DEBUG] - Start id: 850000, end id: 900000 (milvus_benchmark.runners.base:76)
[2022-06-04 21:12:58,832] [   DEBUG] - Milvus insert run in 3.1107s (milvus_benchmark.client:54)
[2022-06-04 21:12:58,837] [   DEBUG] - Row count: 800000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-04 21:12:58,838] [   DEBUG] - 800000 (milvus_benchmark.runners.base:90)
[2022-06-04 21:12:59,933] [   DEBUG] - Start id: 900000, end id: 950000 (milvus_benchmark.runners.base:76)
[2022-06-04 21:13:02,947] [   DEBUG] - Milvus insert run in 3.0097s (milvus_benchmark.client:54)
[2022-06-04 21:13:02,964] [   DEBUG] - Row count: 900000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-04 21:13:02,965] [   DEBUG] - 900000 (milvus_benchmark.runners.base:90)
[2022-06-04 21:13:03,968] [   DEBUG] - Start id: 950000, end id: 1000000 (milvus_benchmark.runners.base:76)
[2022-06-04 21:13:07,148] [   DEBUG] - Milvus insert run in 3.1782s (milvus_benchmark.client:54)
[2022-06-04 21:13:07,152] [   DEBUG] - Row count: 900000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-04 21:13:07,153] [   DEBUG] - 900000 (milvus_benchmark.runners.base:90)
[2022-06-04 21:13:07,154] [    INFO] - {'total_time': 62.0781, 'rps': 16108.7446, 'ni_time': 3.1039} (milvus_benchmark.runners.base:152)
[2022-06-04 21:13:09,332] [   DEBUG] - Milvus flush run in 2.0489s (milvus_benchmark.client:54)
[2022-06-04 21:13:09,337] [   DEBUG] - Row count: 1000000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-04 21:13:09,338] [   DEBUG] - 1000000 (milvus_benchmark.runners.locust:308)
[2022-06-04 21:13:09,339] [   DEBUG] - Start build index for last file (milvus_benchmark.runners.locust:310)
[2022-06-04 21:13:09,339] [    INFO] - Building index start, collection_name: sift_1m_128_l2, index_type: IVF_SQ8, metric_type: L2 (milvus_benchmark.client:277)
[2022-06-04 21:13:09,340] [    INFO] - {'nlist': 1024} (milvus_benchmark.client:279)
[2022-06-04 21:13:09,341] [   DEBUG] - collection: sift_1m_128_l2 Index params: {'index_type': 'IVF_SQ8', 'metric_type': 'L2', 'params': {'nlist': 1024}} (milvus_benchmark.client:285)
[2022-06-04 21:14:04,028] [   DEBUG] - Building index done, collection_name: sift_1m_128_l2, response: Status(code=0, message='') (milvus_benchmark.client:287)
[2022-06-04 21:14:04,029] [   DEBUG] - Milvus create_index run in 54.6892s (milvus_benchmark.client:54)
[2022-06-04 21:14:04,030] [   DEBUG] - {'flush_time': 2.0504, 'build_time': 54.6901} (milvus_benchmark.runners.locust:314)
[2022-06-04 21:14:04,034] [   DEBUG] - Row count: 1000000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-04 21:14:04,034] [    INFO] - 1000000 (milvus_benchmark.runners.locust:315)
[2022-06-04 21:14:04,035] [    INFO] - Start load collection (milvus_benchmark.runners.locust:316)
[2022-06-04 21:14:12,249] [   ERROR] - RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=collection sift_1m_128_l2 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-06-04 21:14:04.108616', 'RPC error': '2022-06-04 21:14:12.249292'}> (pymilvus.decorators:78)
[2022-06-04 21:14:12,250] [   ERROR] - RPC error: [load_collection], <MilvusException: (code=1, message=collection sift_1m_128_l2 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-06-04 21:14:04.035746', 'RPC error': '2022-06-04 21:14:12.250285'}> (pymilvus.decorators:78)
[2022-06-04 21:14:12,250] [   ERROR] - <MilvusException: (code=1, message=collection sift_1m_128_l2 has not been loaded to memory or load failed)> (milvus_benchmark.main:118)
[2022-06-04 21:14:12,254] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 87, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/locust.py", line 318, in prepare
    self.milvus.load_collection(replica_number=replica_number)
  File "/src/milvus_benchmark/client.py", line 50, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 492, in load_collection
    return self._milvus.load_collection(collection_name, **params)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 192, in load_collection
    return handler.load_collection(collection_name=collection_name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 61, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 44, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 79, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 75, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 686, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 61, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 44, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 79, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 75, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 697, in wait_for_loading_collection
    return self._wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 726, in _wait_for_loading_collection
    progress = self.get_collection_loading_progress(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 705, in get_collection_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection sift_1m_128_l2 has not been loaded to memory or load failed)>
 (milvus_benchmark.main:119)
[2022-06-04 21:14:12,254] [   DEBUG] - {'_version': '0.1', '_type': 'metric', 'run_id': 1654383247, 'mode': 'local', 'server': <milvus_benchmark.metrics.models.server.Server object at 0x7f9e649cb080>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware object at 0x7f9e649cb4e0>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7f9e649cb358>, 'status': 'RUN_FAILED', 'err_message': '', 'collection': {'dimension': 128, 'metric_type': 'l2', 'dataset_name': 'sift_1m_128_l2', 'collection_size': 1000000, 'other_fields': None, 'ni_per': 50000, 'shards_num': None}, 'index': {'index_type': 'ivf_sq8', 'index_param': {'nlist': 1024}}, 'search': {'nq': 1, 'topk': 10, 'search_param': {'nprobe': 16}}, 'run_params': {'task': {'connection_num': 1, 'clients_num': 100, 'spawn_rate': 2, 'during_time': 600, 'types': [{'type': 'query', 'weight': 1, 'params': {'top_k': 10, 'nq': 1, 'search_param': {'nprobe': 16}}}]}, 'connection_type': 'single'}, 'metrics': {'type': 'locust_search_performance', 'value': {}}, 'datetime': '2022-06-04 21:11:41.982015', 'type': 'metric'} (milvus_benchmark.metric.api:30)

```

**Comment by xige-16** [comment]
```
Built:     Mon Apr 11 01:52:08 UTC 2022

GitCommit: 994bb829

GoVersion: go version go1.16.9 linux/amd64



open pid file: /run/milvus/querynode.pid

lock pid file: /run/milvus/querynode.pid
```

**Comment by xige-16** [comment]
```
Built:     Thu Jun  2 11:52:55 UTC 2022

GitCommit: 48cf63a2

GoVersion: go version go1.16.9 linux/amd64



open pid file: /run/milvus/querycoord.pid

lock pid file: /run/milvus/querycoord.pid
```

**Comment by xige-16** [comment]
```
[2022/06/04 21:14:11.884 +00:00] [WARN] [client.go:245] ["querynode ClientBase ReCall grpc first call get error "] [error="err: rpc error: code = Unimplemented desc = unknown method SyncReplicaSegments for service milvus.proto.query.QueryNode\n, 

```

**Comment by xige-16** [comment]
> ```
> Built:     Mon Apr 11 01:52:08 UTC 2022
> 
> GitCommit: 994bb829
> 
> GoVersion: go version go1.16.9 linux/amd64
> 
> 
> 
> open pid file: /run/milvus/querynode.pid
> 
> lock pid file: /run/milvus/querynode.pid
> ```

The versions of querycoord and querynode are inconsistent

**Comment by xige-16** [comment]
@wangting0128

**Comment by jingkl** [comment]
Version inconsistency, close issue
