### ISSUE TITLE
[Bug]: [benchmark][cluster] querycoord crash, and load failed: err: context deadline exceeded

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#17372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220602-48cf63a2
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.0.dev67
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task: benchmark-cluster-cron-1654290000

test yaml:
client-configmap:client-search-locust,instanceId:3,server-configmap:server-cluster-8c16m

server:
```
NAME                                                              READY   STATUS             RESTARTS   AGE    IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-cluster-cron-1654290000-3-etcd-0                        1/1     Running            0          170m   10.97.16.89    qa-node013.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654290000-3-etcd-1                        1/1     Running            0          170m   10.97.17.216   qa-node014.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654290000-3-etcd-2                        1/1     Running            0          170m   10.97.16.91    qa-node013.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654290000-3-milvus-datacoord-54d9d7m49m   1/1     Running            0          170m   10.97.18.179   qa-node017.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654290000-3-milvus-datanode-5b54866rpgp   1/1     Running            0          170m   10.97.19.84    qa-node016.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654290000-3-milvus-indexcoord-5b8c4pn96   1/1     Running            0          170m   10.97.18.182   qa-node017.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654290000-3-milvus-indexnode-78446fhvpq   1/1     Running            0          170m   10.97.20.35    qa-node018.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654290000-3-milvus-proxy-7cbbbb9dcxm2mz   1/1     Running            0          170m   10.97.5.48     qa-node003.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654290000-3-milvus-querycoord-5c9f2nmkj   0/1     CrashLoopBackOff   35         170m   10.97.10.145   qa-node008.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654290000-3-milvus-querynode-7c9444j77z   1/1     Running            0          170m   10.97.10.144   qa-node008.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654290000-3-milvus-rootcoord-bc896wrkdj   1/1     Running            0          170m   10.97.18.178   qa-node017.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654290000-3-minio-0                       1/1     Running            0          170m   10.97.12.204   qa-node015.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654290000-3-minio-1                       1/1     Running            0          170m   10.97.12.205   qa-node015.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654290000-3-minio-2                       1/1     Running            0          170m   10.97.12.206   qa-node015.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654290000-3-minio-3                       1/1     Running            0          170m   10.97.12.207   qa-node015.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654290000-3-pulsar-bookie-0               1/1     Running            0          170m   10.97.5.55     qa-node003.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654290000-3-pulsar-bookie-1               1/1     Running            0          170m   10.97.12.221   qa-node015.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654290000-3-pulsar-bookie-2               1/1     Running            0          170m   10.97.5.58     qa-node003.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654290000-3-pulsar-bookie-init-nl6mf      0/1     Completed          0          170m   10.97.5.49     qa-node003.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654290000-3-pulsar-broker-0               1/1     Running            0          170m   10.97.11.91    qa-node009.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654290000-3-pulsar-proxy-0                1/1     Running            0          170m   10.97.18.183   qa-node017.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654290000-3-pulsar-pulsar-init-dnc96      0/1     Completed          0          170m   10.97.5.47     qa-node003.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654290000-3-pulsar-recovery-0             1/1     Running            0          170m   10.97.18.180   qa-node017.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654290000-3-pulsar-zookeeper-0            1/1     Running            0          170m   10.97.5.54     qa-node003.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654290000-3-pulsar-zookeeper-1            1/1     Running            0          170m   10.97.3.206    qa-node001.zilliz.local   <none>           <none>
benchmark-cluster-cron-1654290000-3-pulsar-zookeeper-2            1/1     Running            0          169m   10.97.12.223   qa-node015.zilliz.local   <none>           <none>
```

client pod: benchmark-cluster-cron-1654290000-4007998499

client log:
```
[2022-06-03 21:10:26,519] [    INFO] - Prepare to run cases (milvus_benchmark.main:86)
[2022-06-03 21:10:26,532] [   DEBUG] - Milvus exists_collection run in 0.0117s (milvus_benchmark.client:54)
[2022-06-03 21:10:26,681] [    INFO] - Create collection: <sift_1m_128_l2> successfully (milvus_benchmark.client:150)
[2022-06-03 21:10:26,682] [   DEBUG] - Milvus create_collection run in 0.149s (milvus_benchmark.client:54)
[2022-06-03 21:10:26,682] [    INFO] - Building index start, collection_name: sift_1m_128_l2, index_type: IVF_SQ8, metric_type: L2 (milvus_benchmark.client:277)
[2022-06-03 21:10:26,683] [    INFO] - {'nlist': 1024} (milvus_benchmark.client:279)
[2022-06-03 21:10:26,684] [   DEBUG] - collection: sift_1m_128_l2 Index params: {'index_type': 'IVF_SQ8', 'metric_type': 'L2', 'params': {'nlist': 1024}} (milvus_benchmark.client:285)
[2022-06-03 21:10:27,219] [   DEBUG] - Building index done, collection_name: sift_1m_128_l2, response: Status(code=0, message='') (milvus_benchmark.client:287)
[2022-06-03 21:10:27,220] [   DEBUG] - Milvus create_index run in 0.5374s (milvus_benchmark.client:54)
[2022-06-03 21:10:27,225] [    INFO] - None (milvus_benchmark.client:294)
[2022-06-03 21:10:27,226] [   DEBUG] - {'index_type': 'flat', 'metric_type': None, 'index_param': None} (milvus_benchmark.runners.locust:299)
[2022-06-03 21:10:27,230] [   DEBUG] - Milvus get_info run in 0.0027s (milvus_benchmark.client:54)
[2022-06-03 21:10:28,540] [   DEBUG] - Start id: 0, end id: 50000 (milvus_benchmark.runners.base:76)
[2022-06-03 21:10:32,912] [   DEBUG] - Milvus insert run in 4.3644s (milvus_benchmark.client:54)
[2022-06-03 21:10:32,943] [   DEBUG] - Row count: 0 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-03 21:10:32,960] [   DEBUG] - 0 (milvus_benchmark.runners.base:90)
[2022-06-03 21:10:33,732] [   DEBUG] - Start id: 50000, end id: 100000 (milvus_benchmark.runners.base:76)
[2022-06-03 21:10:38,181] [   DEBUG] - Milvus insert run in 4.4448s (milvus_benchmark.client:54)
[2022-06-03 21:10:38,187] [   DEBUG] - Row count: 0 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-03 21:10:38,188] [   DEBUG] - 0 (milvus_benchmark.runners.base:90)
[2022-06-03 21:10:39,246] [   DEBUG] - Start id: 100000, end id: 150000 (milvus_benchmark.runners.base:76)
[2022-06-03 21:10:43,254] [   DEBUG] - Milvus insert run in 4.0042s (milvus_benchmark.client:54)
[2022-06-03 21:10:43,277] [   DEBUG] - Row count: 100000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-03 21:10:43,280] [   DEBUG] - 100000 (milvus_benchmark.runners.base:90)
[2022-06-03 21:10:44,050] [   DEBUG] - Start id: 150000, end id: 200000 (milvus_benchmark.runners.base:76)
[2022-06-03 21:10:48,150] [   DEBUG] - Milvus insert run in 4.0951s (milvus_benchmark.client:54)
[2022-06-03 21:10:48,155] [   DEBUG] - Row count: 100000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-03 21:10:48,156] [   DEBUG] - 100000 (milvus_benchmark.runners.base:90)
[2022-06-03 21:10:49,335] [   DEBUG] - Start id: 200000, end id: 250000 (milvus_benchmark.runners.base:76)
[2022-06-03 21:10:53,694] [   DEBUG] - Milvus insert run in 4.3516s (milvus_benchmark.client:54)
[2022-06-03 21:10:53,718] [   DEBUG] - Row count: 200000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-03 21:10:53,720] [   DEBUG] - 200000 (milvus_benchmark.runners.base:90)
[2022-06-03 21:10:54,363] [   DEBUG] - Start id: 250000, end id: 300000 (milvus_benchmark.runners.base:76)
[2022-06-03 21:10:59,237] [   DEBUG] - Milvus insert run in 4.8707s (milvus_benchmark.client:54)
[2022-06-03 21:10:59,245] [   DEBUG] - Row count: 200000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-03 21:10:59,247] [   DEBUG] - 200000 (milvus_benchmark.runners.base:90)
[2022-06-03 21:11:00,481] [   DEBUG] - Start id: 300000, end id: 350000 (milvus_benchmark.runners.base:76)
[2022-06-03 21:11:04,743] [   DEBUG] - Milvus insert run in 4.2557s (milvus_benchmark.client:54)
[2022-06-03 21:11:04,766] [   DEBUG] - Row count: 300000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-03 21:11:04,767] [   DEBUG] - 300000 (milvus_benchmark.runners.base:90)
[2022-06-03 21:11:05,420] [   DEBUG] - Start id: 350000, end id: 400000 (milvus_benchmark.runners.base:76)
[2022-06-03 21:11:09,742] [   DEBUG] - Milvus insert run in 4.3195s (milvus_benchmark.client:54)
[2022-06-03 21:11:09,751] [   DEBUG] - Row count: 300000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-03 21:11:09,752] [   DEBUG] - 300000 (milvus_benchmark.runners.base:90)
[2022-06-03 21:11:10,818] [   DEBUG] - Start id: 400000, end id: 450000 (milvus_benchmark.runners.base:76)
[2022-06-03 21:11:15,224] [   DEBUG] - Milvus insert run in 4.4005s (milvus_benchmark.client:54)
[2022-06-03 21:11:15,238] [   DEBUG] - Row count: 400000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-03 21:11:15,239] [   DEBUG] - 400000 (milvus_benchmark.runners.base:90)
[2022-06-03 21:11:15,866] [   DEBUG] - Start id: 450000, end id: 500000 (milvus_benchmark.runners.base:76)
[2022-06-03 21:11:20,377] [   DEBUG] - Milvus insert run in 4.5067s (milvus_benchmark.client:54)
[2022-06-03 21:11:20,382] [   DEBUG] - Row count: 400000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-03 21:11:20,383] [   DEBUG] - 400000 (milvus_benchmark.runners.base:90)
[2022-06-03 21:11:21,451] [   DEBUG] - Start id: 500000, end id: 550000 (milvus_benchmark.runners.base:76)
[2022-06-03 21:11:26,274] [   DEBUG] - Milvus insert run in 4.8164s (milvus_benchmark.client:54)
[2022-06-03 21:11:26,292] [   DEBUG] - Row count: 500000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-03 21:11:26,293] [   DEBUG] - 500000 (milvus_benchmark.runners.base:90)
[2022-06-03 21:11:26,973] [   DEBUG] - Start id: 550000, end id: 600000 (milvus_benchmark.runners.base:76)
[2022-06-03 21:11:32,315] [   DEBUG] - Milvus insert run in 5.3352s (milvus_benchmark.client:54)
[2022-06-03 21:11:32,332] [   DEBUG] - Row count: 500000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-03 21:11:32,336] [   DEBUG] - 500000 (milvus_benchmark.runners.base:90)
[2022-06-03 21:11:33,383] [   DEBUG] - Start id: 600000, end id: 650000 (milvus_benchmark.runners.base:76)
[2022-06-03 21:11:37,908] [   DEBUG] - Milvus insert run in 4.5203s (milvus_benchmark.client:54)
[2022-06-03 21:11:37,931] [   DEBUG] - Row count: 600000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-03 21:11:37,932] [   DEBUG] - 600000 (milvus_benchmark.runners.base:90)
[2022-06-03 21:11:38,765] [   DEBUG] - Start id: 650000, end id: 700000 (milvus_benchmark.runners.base:76)
[2022-06-03 21:11:43,291] [   DEBUG] - Milvus insert run in 4.5217s (milvus_benchmark.client:54)
[2022-06-03 21:11:43,298] [   DEBUG] - Row count: 600000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-03 21:11:43,299] [   DEBUG] - 600000 (milvus_benchmark.runners.base:90)
[2022-06-03 21:11:44,450] [   DEBUG] - Start id: 700000, end id: 750000 (milvus_benchmark.runners.base:76)
[2022-06-03 21:11:50,772] [   DEBUG] - Milvus insert run in 4.9052s (milvus_benchmark.client:54)
[2022-06-03 21:11:50,790] [   DEBUG] - Row count: 700000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-03 21:11:50,791] [   DEBUG] - 700000 (milvus_benchmark.runners.base:90)
[2022-06-03 21:11:52,026] [   DEBUG] - Start id: 750000, end id: 800000 (milvus_benchmark.runners.base:76)
[2022-06-03 21:11:56,394] [   DEBUG] - Milvus insert run in 4.3621s (milvus_benchmark.client:54)
[2022-06-03 21:11:56,403] [   DEBUG] - Row count: 700000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-03 21:11:56,405] [   DEBUG] - 700000 (milvus_benchmark.runners.base:90)
[2022-06-03 21:11:57,243] [   DEBUG] - Start id: 800000, end id: 850000 (milvus_benchmark.runners.base:76)
[2022-06-03 21:12:01,829] [   DEBUG] - Milvus insert run in 4.576s (milvus_benchmark.client:54)
[2022-06-03 21:12:01,851] [   DEBUG] - Row count: 800000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-03 21:12:01,852] [   DEBUG] - 800000 (milvus_benchmark.runners.base:90)
[2022-06-03 21:12:02,767] [   DEBUG] - Start id: 850000, end id: 900000 (milvus_benchmark.runners.base:76)
[2022-06-03 21:12:07,211] [   DEBUG] - Milvus insert run in 4.4397s (milvus_benchmark.client:54)
[2022-06-03 21:12:08,013] [   DEBUG] - Row count: 800000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-03 21:12:08,018] [   DEBUG] - 800000 (milvus_benchmark.runners.base:90)
[2022-06-03 21:12:09,415] [   DEBUG] - Start id: 900000, end id: 950000 (milvus_benchmark.runners.base:76)
[2022-06-03 21:12:13,626] [   DEBUG] - Milvus insert run in 4.2062s (milvus_benchmark.client:54)
[2022-06-03 21:12:13,642] [   DEBUG] - Row count: 900000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-03 21:12:13,643] [   DEBUG] - 900000 (milvus_benchmark.runners.base:90)
[2022-06-03 21:12:14,567] [   DEBUG] - Start id: 950000, end id: 1000000 (milvus_benchmark.runners.base:76)
[2022-06-03 21:12:19,074] [   DEBUG] - Milvus insert run in 4.5044s (milvus_benchmark.client:54)
[2022-06-03 21:12:19,081] [   DEBUG] - Row count: 900000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-03 21:12:19,082] [   DEBUG] - 900000 (milvus_benchmark.runners.base:90)
[2022-06-03 21:12:19,084] [    INFO] - {'total_time': 90.6615, 'rps': 11030.0437, 'ni_time': 4.5331} (milvus_benchmark.runners.base:152)
[2022-06-03 21:12:21,297] [   DEBUG] - Milvus flush run in 2.0244s (milvus_benchmark.client:54)
[2022-06-03 21:12:21,302] [   DEBUG] - Row count: 1000000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-03 21:12:21,302] [   DEBUG] - 1000000 (milvus_benchmark.runners.locust:308)
[2022-06-03 21:12:21,303] [   DEBUG] - Start build index for last file (milvus_benchmark.runners.locust:310)
[2022-06-03 21:12:21,303] [    INFO] - Building index start, collection_name: sift_1m_128_l2, index_type: IVF_SQ8, metric_type: L2 (milvus_benchmark.client:277)
[2022-06-03 21:12:21,304] [    INFO] - {'nlist': 1024} (milvus_benchmark.client:279)
[2022-06-03 21:12:21,304] [   DEBUG] - collection: sift_1m_128_l2 Index params: {'index_type': 'IVF_SQ8', 'metric_type': 'L2', 'params': {'nlist': 1024}} (milvus_benchmark.client:285)
[2022-06-03 21:13:41,956] [   DEBUG] - Building index done, collection_name: sift_1m_128_l2, response: Status(code=0, message='') (milvus_benchmark.client:287)
[2022-06-03 21:13:41,958] [   DEBUG] - Milvus create_index run in 80.6551s (milvus_benchmark.client:54)
[2022-06-03 21:13:41,960] [   DEBUG] - {'flush_time': 2.0256, 'build_time': 80.6566} (milvus_benchmark.runners.locust:314)
[2022-06-03 21:13:41,965] [   DEBUG] - Row count: 1000000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:425)
[2022-06-03 21:13:41,966] [    INFO] - 1000000 (milvus_benchmark.runners.locust:315)
[2022-06-03 21:13:41,967] [    INFO] - Start load collection (milvus_benchmark.runners.locust:316)
[2022-06-03 21:14:08,305] [   ERROR] - RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=err: context deadline exceeded
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:253 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall
/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/client/client.go:155 github.com/milvus-io/milvus/internal/distributed/querycoord/client.(*Client).ShowCollections
/go/src/github.com/milvus-io/milvus/internal/proxy/task.go:1282 github.com/milvus-io/milvus/internal/proxy.(*showCollectionsTask).Execute
/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:465 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask
/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:494 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop
/usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit
)>, <Time:{'RPC start': '2022-06-03 21:13:42.012473', 'RPC error': '2022-06-03 21:14:08.305612'}> (pymilvus.decorators:78)
[2022-06-03 21:14:09,418] [   ERROR] - RPC error: [load_collection], <MilvusException: (code=1, message=err: context deadline exceeded
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:253 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall
/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/client/client.go:155 github.com/milvus-io/milvus/internal/distributed/querycoord/client.(*Client).ShowCollections
/go/src/github.com/milvus-io/milvus/internal/proxy/task.go:1282 github.com/milvus-io/milvus/internal/proxy.(*showCollectionsTask).Execute
/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:465 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask
/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:494 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop
/usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit
)>, <Time:{'RPC start': '2022-06-03 21:13:41.968508', 'RPC error': '2022-06-03 21:14:09.418632'}> (pymilvus.decorators:78)
[2022-06-03 21:14:09,419] [   ERROR] - <MilvusException: (code=1, message=err: context deadline exceeded
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:253 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall
/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/client/client.go:155 github.com/milvus-io/milvus/internal/distributed/querycoord/client.(*Client).ShowCollections
/go/src/github.com/milvus-io/milvus/internal/proxy/task.go:1282 github.com/milvus-io/milvus/internal/proxy.(*showCollectionsTask).Execute
/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:465 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask
/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:494 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop
/usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit
)> (milvus_benchmark.main:118)
[2022-06-03 21:14:09,424] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 87, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/locust.py", line 318, in prepare
    self.milvus.load_collection(replica_number=replica_number)
  File "/src/milvus_benchmark/client.py", line 50, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 492, in load_collection
    return self._milvus.load_collection(collection_name, **params)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 192, in load_collection
    return handler.load_collection(collection_name=collection_name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 61, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 44, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 79, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 75, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 686, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 61, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 44, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 79, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 75, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 697, in wait_for_loading_collection
    return self._wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 726, in _wait_for_loading_collection
    progress = self.get_collection_loading_progress(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 705, in get_collection_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=err: context deadline exceeded
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:253 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall
/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/client/client.go:155 github.com/milvus-io/milvus/internal/distributed/querycoord/client.(*Client).ShowCollections
/go/src/github.com/milvus-io/milvus/internal/proxy/task.go:1282 github.com/milvus-io/milvus/internal/proxy.(*showCollectionsTask).Execute
/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:465 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask
/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:494 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop
/usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit
)>
 (milvus_benchmark.main:119)
[2022-06-03 21:14:09,425] [   DEBUG] - {'_version': '0.1', '_type': 'metric', 'run_id': 1654300319, 'mode': 'local', 'server': <milvus_benchmark.metrics.models.server.Server object at 0x7fd34a019c18>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware object at 0x7fd34a019940>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7fd34a019dd8>, 'status': 'RUN_FAILED', 'err_message': '', 'collection': {'dimension': 128, 'metric_type': 'l2', 'dataset_name': 'sift_1m_128_l2', 'collection_size': 1000000, 'other_fields': None, 'ni_per': 50000, 'shards_num': None}, 'index': {'index_type': 'ivf_sq8', 'index_param': {'nlist': 1024}}, 'search': {'nq': 1, 'topk': 10, 'search_param': {'nprobe': 16}}, 'run_params': {'task': {'connection_num': 1, 'clients_num': 100, 'spawn_rate': 2, 'during_time': 600, 'types': [{'type': 'query', 'weight': 1, 'params': {'top_k': 10, 'nq': 1, 'search_param': {'nprobe': 16}}}]}, 'connection_type': 'single'}, 'metrics': {'type': 'locust_search_performance', 'value': {}}, 'datetime': '2022-06-03 21:10:26.482715', 'type': 'metric'} (milvus_benchmark.metric.api:30)
```

**Comment by xige-16** [comment]
```
Welcome to use Milvus!

Version:   994bb829

Built:     Mon Apr 11 01:52:08 UTC 2022

GitCommit: 994bb829

GoVersion: go version go1.16.9 linux/amd64
```

**Comment by xige-16** [comment]
```
Built:     Thu Jun  2 11:52:55 UTC 2022

GitCommit: 48cf63a2

GoVersion: go version go1.16.9 linux/amd64



open pid file: /run/milvus/querycoord.pid

lock pid file: /run/milvus/querycoord.pid
```

**Comment by xige-16** [comment]
```
[2022/06/03 21:13:48.044 +00:00] [ERROR] [global_meta_broker.go:516] ["QueryCoord release reference lock on segments failed"] [segmentIDs="[433662362881884161,433662362881884162]"] [error="err: rpc error: code = Unimplemented desc = unknown method ReleaseSegmentLock for service milvus.proto.data.DataCoord
```
The versions of querycoord and datacoord are inconsistent

**Comment by jingkl** [comment]
Querynode and querycoord versions do not match, close issue
