### ISSUE TITLE
[Bug]: Search failed with error message `Deadline Exceeded` after Milvus reinstall or upgrade

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#17383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220602-48cf63a2
- Deployment mode(standalone or cluster): standalone and cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.1.0.dev66
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
15:26:47  collection name: task_2_FLAT
15:26:47  release collection
15:26:47  load collection
15:26:47  load time: 3.1334
15:26:47  {'metric_type': 'L2', 'params': {'nprobe': 10}}
15:26:47  
15:26:47  Search...
15:26:47  Traceback (most recent call last):
15:26:47    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 44, in handler
15:26:47      return func(self, *args, **kwargs)
15:26:47    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 87, in handler
15:26:47      raise e
15:26:47    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 75, in handler
15:26:47      return func(*args, **kwargs)
15:26:47    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 449, in search
15:26:47      return self._execute_search_requests(requests, timeout, **_kwargs)
15:26:47    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 87, in handler
15:26:47      raise e
15:26:47    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 75, in handler
15:26:47      return func(*args, **kwargs)
15:26:47    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 411, in _execute_search_requests
15:26:47      raise pre_err
15:26:47    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 399, in _execute_search_requests
15:26:47      response = ft.result()
15:26:47    File "/usr/local/lib/python3.7/dist-packages/grpc/_channel.py", line 744, in result
15:26:47      raise self
15:26:47  grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
15:26:47  	status = StatusCode.DEADLINE_EXCEEDED
15:26:47  	details = "Deadline Exceeded"
15:26:47  	debug_error_string = "{"created":"@1654500401.994530935","description":"Error received from peer ipv4:10.96.56.211:19530","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Deadline Exceeded","grpc_status":4}"
15:26:47  >
15:26:47  
15:26:47  During handling of the above exception, another exception occurred:
15:26:47  
15:26:47  Traceback (most recent call last):
15:26:47    File "action_after_reinstall.py", line 44, in <module>
15:26:47      task_2(data_size, host)
15:26:47    File "action_after_reinstall.py", line 28, in task_2
15:26:47      load_and_search(prefix)
15:26:47    File "/home/jenkins/agent/workspace/tests/python_client/deploy/scripts/utils.py", line 158, in load_and_search
15:26:47      "count > 500", output_fields=["count", "random_value"], timeout=120
15:26:47    File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 690, in search
15:26:47      partition_names, output_fields, round_decimal, timeout=timeout, **kwargs)
15:26:47    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 52, in handler
15:26:47      raise MilvusException(Status.UNEXPECTED_ERROR, str(e))
15:26:47  pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
15:26:47  	status = StatusCode.DEADLINE_EXCEEDED
15:26:47  	details = "Deadline Exceeded"
15:26:47  	debug_error_string = "{"created":"@1654500401.994530935","description":"Error received from peer ipv4:10.96.56.211:19530","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Deadline Exceeded","grpc_status":4}"
15:26:47  >)>
```

### Expected Behavior

all test cases passed

### Steps To Reproduce

```markdown
see https://github.com/milvus-io/milvus/runs/6747206656?check_suite_focus=true
```

### Milvus Log

failed job: http://10.100.32.144:8080/blue/organizations/jenkins/deploy_test/detail/deploy_test/726/pipeline
log: [artifacts-cluster-reinstall-726-logs.tar.gz](https://github.com/milvus-io/milvus/files/8842835/artifacts-cluster-reinstall-726-logs.tar.gz)
 

### Anything else?

This also failed in other tests

* standalone reinstall: https://github.com/milvus-io/milvus/runs/6747206623?check_suite_focus=true
* standalone upgrade: http://10.100.32.144:8080/blue/organizations/jenkins/deploy_test/detail/deploy_test/712/pipeline

* cluster upgrade: http://10.100.32.144:8080/view/deploy%20test/job/deploy_test/728/
*  cluster with kafka mq reinstall:  http://10.100.32.144:8080/blue/organizations/jenkins/deploy_test_kafka/detail/deploy_test_kafka/60/pipeline

The upgrade pipeline will also have a restart action in it, so both may be the same reason.

**Comment by zhuwenxing** [comment]
@congqixia some updates:
I have tried deploy test in GitHub Action and Jenkins with version `master-20220606-ac6394d0`.
The tests almost all passed, and the failed tests all failed in deployment(known issue)

**Comment by zhuwenxing** [comment]
In today's deploy test in github action and jenkins, all tests are passed.
* https://github.com/milvus-io/milvus/actions/runs/2450298379

Have no idea which PR fixed this issue.

**Comment by zhuwenxing** [comment]
This happened again!

http://10.100.32.144:8080/blue/organizations/jenkins/deploy_test/detail/deploy_test/927/pipeline
http://10.100.32.144:8080/blue/organizations/jenkins/deploy_test/detail/deploy_test/923/pipeline
http://10.100.32.144:8080/blue/organizations/jenkins/deploy_test/detail/deploy_test/923/pipeline

**Comment by yanliang567** [comment]
@congqixia any updates?

**Comment by jiaoew1991** [comment]
> @congqixia any updates?
From the logs only can figure out the querynode did not set tsafe timestamp of the delta channel correctly.  
We need add more logs and build  a new image,  retest it.

**Comment by jiaoew1991** [comment]
We found 2 prs related to this issue

#17550  after new datanode online, caused infinite loop, 
#17642  new querynode cannot consume TT message from plusar

**Comment by zhuwenxing** [comment]
Not reproduced yet. remove the critical label.

**Comment by jinuhwang** [comment]
Any update here? I still have this issue
