### ISSUE TITLE
[Bug]: [kafka] Drop collection failed for timeout

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#17405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):  cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.1.0.dev66
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Drop collection failed for timeout

```


[2022-06-06T20:14:08.154Z] [2022-06-06 19:00:24 - DEBUG - ci_test]: (api_request)  : [Collection.drop] args: [], kwargs: {'timeout': 20} (api_request.py:55)

[2022-06-06T20:14:08.154Z] [2022-06-06 19:00:46 - ERROR - pymilvus.decorators]: grpc RpcError: [drop_collection], <_MultiThreadedRendezvous: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded>, <Time:{'RPC start': '2022-06-06 19:00:26.104272', 'gRPC error': '2022-06-06 19:00:46.105010'}> (decorators.py:86)

[2022-06-06T20:14:08.154Z] [2022-06-06 19:00:46 - ERROR - ci_test]: Traceback (most recent call last):

[2022-06-06T20:14:08.155Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 44, in handler

[2022-06-06T20:14:08.155Z]     return func(self, *args, **kwargs)

[2022-06-06T20:14:08.155Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 87, in handler

[2022-06-06T20:14:08.155Z]     raise e

[2022-06-06T20:14:08.155Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 75, in handler

[2022-06-06T20:14:08.155Z]     return func(*args, **kwargs)

[2022-06-06T20:14:08.155Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 197, in drop_collection

[2022-06-06T20:14:08.155Z]     status = rf.result()

[2022-06-06T20:14:08.155Z]   File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 744, in result

[2022-06-06T20:14:08.155Z]     raise self

[2022-06-06T20:14:08.155Z] grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:

[2022-06-06T20:14:08.155Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2022-06-06T20:14:08.155Z] 	details = "Deadline Exceeded"

[2022-06-06T20:14:08.155Z] 	debug_error_string = "{"created":"@1654542046.104609467","description":"Error received from peer ipv4:10.201.151.218:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Deadline Exceeded","grpc_status":4}"
```

### Expected Behavior

Drop collection successfully

### Steps To Reproduce

```markdown
Nightly:
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/577/pipeline

Test cases:

@pytest.mark.tags(CaseLabel.L1)
    def test_collection_after_drop(self):
        """
        target: test create collection after create and drop
        method: 1. create a 2. drop a 3, re-create a
        expected: no exception
        """
        c_name = cf.gen_unique_str(prefix)
        collection_w = self.init_collection_wrap(name=c_name, check_task=CheckTasks.check_collection_property,
                                                 check_items={exp_name: c_name, exp_schema: default_schema})
        collection_w.drop()
        assert not self.utility_wrap.has_collection(collection_w.name)[0]
        self.init_collection_wrap(name=c_name, check_task=CheckTasks.check_collection_property,
                                  check_items={exp_name: c_name, exp_schema: default_schema})
        assert self.utility_wrap.has_collection(c_name)[0]
```

### Milvus Log

1.Milvus logs: 
[artifacts-milvus-distributed-kafka-master-577-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/577/artifact/artifacts-milvus-distributed-kafka-master-577-pymilvus-e2e-logs.tar.gz)

2. collection name: collection_uzQbddIf

**Comment by binbinlv** [comment]
Has not been reproduced, so close it first, and will reopen it if it occurs in the future.
