### ISSUE TITLE
[Bug]:[benchmark][standalone] Milvus search rasie an error"message=proxy not healthy"

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#17436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220607-f31be941
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.1.0.dev67
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server-instance
benchmark-cron-1654617600-6
server-configmap
server-single-16c64m
client-configmap
client-search-sift50m-ivf-flat-2048

server:
```
benchmark-cron-1654617600-6-etcd-0                                1/1     Running     0          2m16s   10.97.16.122   qa-node013.zilliz.local   <none>           <none>
benchmark-cron-1654617600-6-milvus-standalone-7d47cfd6c6-gznwz    1/1     Running     0          2m16s   10.97.20.146   qa-node018.zilliz.local   <none>           <none>
benchmark-cron-1654617600-6-minio-546d69bc69-d4tth                1/1     Running     0          2m16s   10.97.19.42    qa-node016.zilliz.local   <none>           <none>
```
client:
```
[2022-06-07 20:15:43,253] [   DEBUG] - Start run query, run 1 of 30 (milvus_benchmark.runners.search:294)
[2022-06-07 20:15:43,255] [    INFO] - {'nq': 1200, 'topk': 1000, 'search_param': {'nprobe': 32}, 'filter': [], 'guarantee_timestamp': None} (milvus_benchmark.runners.search:295)
[2022-06-07 20:15:43,258] [   ERROR] - RPC error: [has_collection], <MilvusException: (code=1, message=proxy not healthy)>, <Time:{'RPC start': '2022-06-07 20:15:43.257184', 'RPC error': '2022-06-07 20:15:43.258153'}> (pymilvus.decorators:78)
[2022-06-07 20:15:43,258] [   ERROR] - RPC error: [search], <MilvusException: (code=1, message=proxy not healthy)>, <Time:{'RPC start': '2022-06-07 20:15:43.256821', 'RPC error': '2022-06-07 20:15:43.258744'}> (pymilvus.decorators:78)
[2022-06-07 20:15:43,259] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 95, in run_suite
    result = runner.run_case(case_metric, **case)
  File "/src/milvus_benchmark/runners/search.py", line 298, in run_case
    guarantee_timestamp=case_param["guarantee_timestamp"])
  File "/src/milvus_benchmark/client.py", line 50, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 325, in query
    result = self._milvus.search(tmp_collection_name, **params)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 842, in search
    partition_names, output_fields, timeout=timeout, round_decimal=round_decimal, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 61, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 44, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 79, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 75, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 429, in search
    if not self.has_collection(collection_name, timeout):
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 61, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 44, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 79, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 75, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 211, in has_collection
    raise MilvusException(reply.status.error_code, reply.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=proxy not healthy)>
```

### Anything else?

```
"config.yaml": "insert_search_performance:
		  collections:
		    -
		      collection_name: sift_50m_128_l2
		      ni_per: 50000
		      build_index: true
		      index_type: ivf_flat 
		      index_param:
		        nlist: 2048
		      run_count: 30
		      top_ks: [1, 10, 100, 1000]
		      nqs: [1, 10, 100, 500, 1000, 1200]
		      search_params:
		        -
		          nprobe: 8
		        -
		          nprobe: 32
```

**Comment by bigsheeper** [comment]
Didn't reproduce for many days, move to 2.1GA

**Comment by bigsheeper** [comment]
Milvus disconnected from etcd:
```
[2022/06/07 20:15:42.226 +00:00] [ERROR] [data_node.go:183] ["Data Node disconnected from etcd, process will exit"] ["Server Id"=6] [stack="github.com/milvus-io/milvus/internal/datanode.(*DataNode).Register.func1\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/data_node.go:183"]
[2022/06/07 20:15:42.226 +00:00] [INFO] [flow_graph_manager.go:143] ["start drop all flowgraph resources in DataNode"]
[2022/06/07 20:15:42.227 +00:00] [WARN] [session_util.go:266] ["session keepalive channel closed"]
[2022/06/07 20:15:42.226 +00:00] [ERROR] [server.go:228] ["disconnected from etcd and exited"] [module=DataCoord] [serverID=1] [stack="github.com/milvus-io/milvus/internal/datacoord.(*Server).Register.func1\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/server.go:228"]
[2022/06/07 20:15:42.227 +00:00] [WARN] [session_util.go:445] ["connection lost detected, shuting down"]
[2022/06/07 20:15:42.227 +00:00] [ERROR] [query_node.go:161] ["Query Node disconnected from etcd, process will exit"] ["Server Id"=4] [stack="github.com/milvus-io/milvus/internal/querynode.(*QueryNode).Register.func1\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/query_node.go:161"]
[2022/06/07 20:15:42.227 +00:00] [WARN] [session_util.go:445] ["connection lost detected, shuting down"]
[2022/06/07 20:15:42.227 +00:00] [INFO] [index_coord.go:303] ["close the task scheduler of IndexCoord"]
[2022/06/07 20:15:42.227 +00:00] [INFO] [query_coord.go:262] ["close index checker ..."]
[2022/06/07 20:15:42.228 +00:00] [INFO] [channel_unsubscribe.go:140] ["channelUnsubscribeHandler ctx done, handleChannelUnsubscribeLoop end"]
[2022/06/07 20:15:42.228 +00:00] [INFO] [query_coord.go:272] ["cancel the loop of QueryCoord"]
[2022/06/07 20:15:42.228 +00:00] [INFO] [data_node.go:242] ["watch etcd loop quit"]
[2022/06/07 20:15:42.228 +00:00] [INFO] [query_node.go:327] ["query node watchChangeInfo close"]
[2022/06/07 20:15:42.228 +00:00] [WARN] [task_scheduler.go:178] ["QueryNode sop schedulerReadTasks"]
[2022/06/07 20:15:42.228 +00:00] [DEBUG] [task_scheduler.go:252] ["QueryNode stop executeReadTasks"] [NodeID=4]
[2022/06/07 20:15:42.227 +00:00] [WARN] [session_util.go:266] ["session keepalive channel closed"]
[2022/06/07 20:15:42.227 +00:00] [ERROR] [proxy.go:126] ["Proxy disconnected from etcd, process will exit"] ["Server Id"=8] [stack="github.com/milvus-io/milvus/internal/proxy.(*Proxy).Register.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/proxy.go:126"]
[2022/06/07 20:15:42.227 +00:00] [ERROR] [root_coord.go:958] ["Root Coord disconnected from etcd, process will exit"] ["Server Id"=5] [stack="github.com/milvus-io/milvus/internal/rootcoord.(*Core).Register.func1\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:958"]
```

**Comment by Uzay-G** [comment]
I am also having this issue? Is there anything I can do about it? I've attached etcd logs.

milvus can't connect to etcd and it seems etcd dies for some reason, with message `Err: connection error: desc = "transport: Error while dialing dial tcp 0.0.0.0:2379: connect: connection refused". Reconnecting...`

I can no longer use/connect to my milvus setup

[etcdlogs.txt](https://github.com/milvus-io/milvus/files/9356777/etcdlogs.txt)

**Comment by LoveEachDay** [comment]
@Uzay-G  From the attached log:
```
36mmilvus-etcd   |[0m {"level":"info","ts":"2022-08-05T08:55:00.611Z","caller":"osutil/interrupt_unix.go:64","msg":"received signal; shutting down","signal":"terminated"}
[36mmilvus-etcd   |[0m {"level":"info","ts":"2022-08-05T08:55:00.611Z","caller":"embed/etcd.go:367","msg":"closing etcd server","name":"default","data-dir":"/etcd","advertise-peer-urls":["http://localhost:2380"],"advertise-client-urls":["http://127.0.0.1:2379"]}
[36mmilvus-etcd   |[0m WARNING: 2022/08/05 08:55:00 [core] grpc: addrConn.createTransport failed to connect to {0.0.0.0:2379 0.0.0.0:2379 <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp 0.0.0.0:2379: connect: connection refused". Reconnecting...
```
The `connection refused` error is raised, because the etcd container has received terminated signal which closed the listening port.

**Comment by Uzay-G** [comment]
@LoveEachDay I didn't send any termination signal to etcd, I actually stopped and started the container to test it again several times. Do you have any idea what could be causing this to happen/this signal to send?

**Comment by LoveEachDay** [comment]
@Uzay-G Did you maually stop etcd container? 
Seems you are deploying milvus using `docker-compose`. After your test is done, you'd run `docker-compose down` then remove the `volumes` directory under the current directory.

**Comment by Uzay-G** [comment]
I did not stop it manually. That's why I'm flagging this issue - I don't know why etcd is getting shut down because I am not making it stop.

**Comment by LoveEachDay** [comment]
@Uzay-G Could you run `docker-compose ps` to show the container status?

**Comment by Uzay-G** [comment]
```

**Comment by Uzay-G** [comment]
The memory usage of the `milvus-etcd` is spiking and causing the container to go OOM and shut down. I wonder why :thinking:

**Comment by Uzay-G** [comment]
`milvus-etcd` is somehow hitting the memory limit of 7.5GB of ram/container on my machine. Is there a reason this might be happening? How could it be fixed on my end? Is it just because I have too much data? I have like 80k vectors saved.

**Comment by yanliang567** [comment]
> `milvus-etcd` is somehow hitting the memory limit of 7.5GB of ram/container on my machine. Is there a reason this might be happening? How could it be fixed on my end? Is it just because I have too much data? I have like 80k vectors saved.

i suggest you file a new issue for this.

**Comment by Uzay-G** [comment]
#18707
