### ISSUE TITLE
[Bug]: Load collection failed after Milvus  standalone upgrading form v2.0.2 to master-20220608-6426e3d0

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#17443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.0.2 to master-20220608-6426e3d0
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.0.dev69
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

load collection after upgrading 
```
16:41:52  collection name: task_2_ANNOY
16:41:52  release collection
16:41:52  load collection
16:41:52  Traceback (most recent call last):
16:41:52    File "action_after_upgrade.py", line 94, in <module>
16:41:52      task_2(data_size, host)
16:41:52    File "action_after_upgrade.py", line 33, in task_2
16:41:52      load_and_search(prefix)
16:41:52    File "/home/jenkins/agent/workspace/tests/python_client/deploy/scripts/utils.py", line 142, in load_and_search
16:41:52      c.load()
16:41:52    File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 450, in load
16:41:52      conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
16:41:52    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 61, in handler
16:41:52      raise e
16:41:52    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 44, in handler
16:41:52      return func(self, *args, **kwargs)
16:41:52    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 79, in handler
16:41:52      raise e
16:41:52    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 75, in handler
16:41:52      return func(*args, **kwargs)
16:41:52    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 686, in load_collection
16:41:52      self.wait_for_loading_collection(collection_name, timeout)
16:41:52    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 61, in handler
16:41:52      raise e
16:41:52    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 44, in handler
16:41:52      return func(self, *args, **kwargs)
16:41:52    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 79, in handler
16:41:52      raise e
16:41:52    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 75, in handler
16:41:52      return func(*args, **kwargs)
16:41:52    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 697, in wait_for_loading_collection
16:41:52      return self._wait_for_loading_collection(collection_name, timeout)
16:41:52    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 726, in _wait_for_loading_collection
16:41:52      progress = self.get_collection_loading_progress(collection_name, timeout)
16:41:52    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 705, in get_collection_loading_progress
16:41:52      raise MilvusException(response.status.error_code, response.status.reason)
16:41:52  pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection task_2_ANNOY has not been loaded to memory or load failed)>
```

### Expected Behavior

all test cases passed

### Steps To Reproduce

```markdown
see http://10.100.32.144:8080/blue/organizations/jenkins/deploy_test/detail/deploy_test/768/
```

### Milvus Log

failed job: http://10.100.32.144:8080/blue/organizations/jenkins/deploy_test/detail/deploy_test/768/pipeline

log: [artifacts-standalone-upgrade-768-logs.tar.gz](https://github.com/milvus-io/milvus/files/8860098/artifacts-standalone-upgrade-768-logs.tar.gz)
 

### Anything else?

The deploy test would have all hanged, but this accidentally did not hang, but failed to load

**Comment by xiaofan-luan** [comment]
xige-16 is working on it

**Comment by yanliang567** [comment]
@zhuwenxing please help to verify for https://github.com/milvus-io/milvus/issues/17431 fixed

/assign @zhuwenxing 
/unassign

**Comment by zhuwenxing** [comment]
not reproduced yet with master-latest
