### ISSUE TITLE
[Bug]: querynode restart when search

### ISSUE THREAD

**Issue by qi49125** [milvus-io/milvus#17453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:milvus-debug
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.0.2
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

[2022/06/08 12:09:56.416 +00:00] [DEBUG] [query_collection.go:350] ["check if query timeout"] [collectionID=432520058327793665] [msgID=433764162499263364] [TimeoutTs=0] [curTime=433767106849275904] [timeoutTsPhysical=1970/01/01 00:00:00.000 +00:00] [curTimePhysical=2022/06/08 12:09:56.416 +00:00]
[2022/06/08 12:09:56.416 +00:00] [DEBUG] [query_collection.go:536] ["query node::receiveQueryMsg: add to unsolvedMsg"] [collectionID=432520058327793665] [sm.GuaranteeTimestamp=2022/06/08 12:09:56.361 +00:00] [serviceTime=2022/06/08 12:09:56.012 +00:00] ["delta seconds"=0] [msgID=433764162499263364] [msgType=search]
[2022/06/08 12:09:56.494 +00:00] [DEBUG] [query_collection.go:631] ["get query message from unsolvedMsg"] [collectionID=432520058327793665] [msgID=433764162499263364] [reqTime_p=2022/06/08 12:09:56.361 +00:00] [serviceTime_p=2022/06/08 12:09:56.212 +00:00] [guaranteeTime_l=433767106834857987] [serviceTime_l=433767106795798529]
[2022/06/08 12:09:56.494 +00:00] [DEBUG] [query_collection.go:350] ["check if query timeout"] [collectionID=432520058327793665] [msgID=433764162499263364] [TimeoutTs=0] [curTime=433767106869723136] [timeoutTsPhysical=1970/01/01 00:00:00.000 +00:00] [curTimePhysical=2022/06/08 12:09:56.494 +00:00]
[2022/06/08 12:09:56.494 +00:00] [DEBUG] [query_collection.go:656] ["query node::doUnsolvedMsg: add to unsolvedMsg"] [collectionID=432520058327793665] [sm.BeginTs=2022/06/08 12:09:56.361 +00:00] [serviceTime=2022/06/08 12:09:56.212 +00:00] ["delta seconds"=0] [msgID=433764162499263364]
[2022/06/08 12:09:56.695 +00:00] [DEBUG] [query_collection.go:631] ["get query message from unsolvedMsg"] [collectionID=432520058327793665] [msgID=433764162499263364] [reqTime_p=2022/06/08 12:09:56.361 +00:00] [serviceTime_p=2022/06/08 12:09:56.412 +00:00] [guaranteeTime_l=433767106834857987] [serviceTime_l=433767106848227329]
[2022/06/08 12:09:56.695 +00:00] [DEBUG] [query_collection.go:350] ["check if query timeout"] [collectionID=432520058327793665] [msgID=433764162499263364] [TimeoutTs=0] [curTime=433767106922414080] [timeoutTsPhysical=1970/01/01 00:00:00.000 +00:00] [curTimePhysical=2022/06/08 12:09:56.695 +00:00]
[2022/06/08 12:09:56.695 +00:00] [DEBUG] [query_collection.go:674] ["doing search in doUnsolvedMsg..."] [collectionID=432520058327793665] [msgID=433764162499263364]
[2022/06/08 12:09:56.697 +00:00] [DEBUG] [query_collection.go:1082] ["historical search start"] [msgID=433764162499263364]
[2022/06/08 12:09:56.697 +00:00] [DEBUG] [historical.go:124] ["no partition specified, search all partitions"] [collectionID=432520058327793665] ["all partitions"="[432520058327793666,432520058354008065,432520116838334465,432520296852619265,432520658008408065,432521274662846465,432522044907454465,432522045457956865,432522154680254465,432523724490276865,432525061778571265,432525394727665665,432526620539224065,432527149113278465,432527282846302209,432527757418430465,432527801563480065,432529593881329665,432531566659108865,432531774382014465,432531856695230465,432531865332875265,432532463244279809,432532511911051265,432534662999179265,432536414488100865,432536414566744065,432536414802673665,432536772681662465,432537255773732865,432537330733809665,432541498731921409,432541503358763009,432541505429438465,432541542431064065,432541542666993665,432541907506167809,432542867805175809,432544824958910465,432601772321931265,432601776240984065]"]
[2022/06/08 12:09:56.697 +00:00] [DEBUG] [segment.go:313] ["do search on segment"] [segmentID=432520075118116865] [segmentType=3]
=================================================================
==8==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x62d0000c6400 at pc 0x7fc027f58d6d bp 0x7fbff85e9310 sp 0x7fbff85e9300
READ of size 8 at 0x62d0000c6400 thread T3
    #0 0x7fc027f58d6c in milvus::segcore::SegmentSealedImpl::get_deleted_bitmap(long, unsigned long, long, bool) const /milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:272
    #1 0x7fc027f59494 in milvus::segcore::SegmentSealedImpl::get_filtered_bitmap(faiss::BitsetView const&, long, unsigned long) const /milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:290
    #2 0x7fc02807ac80 in void milvus::query::ExecPlanNodeVisitor::VectorVisitorImpl<milvus::FloatVector>(milvus::query::VectorPlanNode&) (/milvus/lib/libmilvus_segcore.so+0x9f0c80)
    #3 0x7fc028077292 in milvus::query::ExecPlanNodeVisitor::visit(milvus::query::FloatVectorANNS&) /milvus/internal/core/src/query/visitors/ExecPlanNodeVisitor.cpp:154
    #4 0x7fc02823eeb6 in milvus::query::FloatVectorANNS::accept(milvus::query::PlanNodeVisitor&) /milvus/internal/core/src/query/generated/PlanNode.cpp:20
    #5 0x7fc028051597 in milvus::query::ExecPlanNodeVisitor::get_moved_result(milvus::query::PlanNode&) /milvus/internal/core/src/query/generated/ExecPlanNodeVisitor.h:47
    #6 0x7fc02804cb2c in milvus::segcore::SegmentInternalInterface::Search(milvus::query::Plan const*, milvus::query::PlaceholderGroup const&, unsigned long) const /milvus/internal/core/src/segcore/SegmentInterface.cpp:105
    #7 0x7fc027ecf8dc in Search /milvus/internal/core/src/segcore/segment_c.cpp:70
    #8 0x1d7a95d in _cgo_30d863aaae48_Cfunc_Search (/milvus/bin/milvus+0x1d7a95d)
    #9 0x942f2f in runtime.asmcgocall /root/.gvm/gos/go1.16.9/src/runtime/asm_amd64.s:667

0x62d0000c6400 is located 0 bytes to the right of 32768-byte region [0x62d0000be400,0x62d0000c6400)
allocated by thread T3 here:
    #0 0x7fc02993d587 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cc:104
    #1 0x7fc027f43aca in __gnu_cxx::new_allocator<fluent::NamedType<long, milvus::impl::SegOffsetTag, fluent::Arithmetic> >::allocate(unsigned long, void const*) /usr/include/c++/9/ext/new_allocator.h:114
    #2 0x7fc027f3d460 in std::allocator_traits<std::allocator<fluent::NamedType<long, milvus::impl::SegOffsetTag, fluent::Arithmetic> > >::allocate(std::allocator<fluent::NamedType<long, milvus::impl::SegOffsetTag, fluent::Arithmetic> >&, unsigned long) /usr/include/c++/9/bits/alloc_traits.h:443
    #3 0x7fc027f36a33 in std::_Vector_base<fluent::NamedType<long, milvus::impl::SegOffsetTag, fluent::Arithmetic>, std::allocator<fluent::NamedType<long, milvus::impl::SegOffsetTag, fluent::Arithmetic> > >::_M_allocate(unsigned long) (/milvus/lib/libmilvus_segcore.so+0x8aca33)
    #4 0x7fc027f2f0a8 in void std::vector<fluent::NamedType<long, milvus::impl::SegOffsetTag, fluent::Arithmetic>, std::allocator<fluent::NamedType<long, milvus::impl::SegOffsetTag, fluent::Arithmetic> > >::_M_realloc_insert<fluent::NamedType<long, milvus::impl::SegOffsetTag, fluent::Arithmetic> const&>(__gnu_cxx::__normal_iterator<fluent::NamedType<long, milvus::impl::SegOffsetTag, fluent::Arithmetic>*, std::vector<fluent::NamedType<long, milvus::impl::SegOffsetTag, fluent::Arithmetic>, std::allocator<fluent::NamedType<long, milvus::impl::SegOffsetTag, fluent::Arithmetic> > > >, fluent::NamedType<long, milvus::impl::SegOffsetTag, fluent::Arithmetic> const&) (/milvus/lib/libmilvus_segcore.so+0x8a50a8)
    #5 0x7fc027f2645e in std::vector<fluent::NamedType<long, milvus::impl::SegOffsetTag, fluent::Arithmetic>, std::allocator<fluent::NamedType<long, milvus::impl::SegOffsetTag, fluent::Arithmetic> > >::push_back(fluent::NamedType<long, milvus::impl::SegOffsetTag, fluent::Arithmetic> const&) /usr/include/c++/9/bits/stl_vector.h:1195
    #6 0x7fc028065e74 in milvus::segcore::ScalarIndexVector::do_search_ids(std::vector<long, std::allocator<long> > const&) const /milvus/internal/core/src/segcore/ScalarIndex.cpp:60
    #7 0x7fc027f58b3c in milvus::segcore::SegmentSealedImpl::get_deleted_bitmap(long, unsigned long, long, bool) const /milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:254
    #8 0x7fc027f59494 in milvus::segcore::SegmentSealedImpl::get_filtered_bitmap(faiss::BitsetView const&, long, unsigned long) const /milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:290
    #9 0x7fc02807ac80 in void milvus::query::ExecPlanNodeVisitor::VectorVisitorImpl<milvus::FloatVector>(milvus::query::VectorPlanNode&) (/milvus/lib/libmilvus_segcore.so+0x9f0c80)
    #10 0x7fc028077292 in milvus::query::ExecPlanNodeVisitor::visit(milvus::query::FloatVectorANNS&) /milvus/internal/core/src/query/visitors/ExecPlanNodeVisitor.cpp:154
    #11 0x7fc02823eeb6 in milvus::query::FloatVectorANNS::accept(milvus::query::PlanNodeVisitor&) /milvus/internal/core/src/query/generated/PlanNode.cpp:20
    #12 0x7fc028051597 in milvus::query::ExecPlanNodeVisitor::get_moved_result(milvus::query::PlanNode&) /milvus/internal/core/src/query/generated/ExecPlanNodeVisitor.h:47
    #13 0x7fc02804cb2c in milvus::segcore::SegmentInternalInterface::Search(milvus::query::Plan const*, milvus::query::PlaceholderGroup const&, unsigned long) const /milvus/internal/core/src/segcore/SegmentInterface.cpp:105
    #14 0x7fc027ecf8dc in Search /milvus/internal/core/src/segcore/segment_c.cpp:70
    #15 0x1d7a95d in _cgo_30d863aaae48_Cfunc_Search (/milvus/bin/milvus+0x1d7a95d)
    #16 0x942f2f in runtime.asmcgocall /root/.gvm/gos/go1.16.9/src/runtime/asm_amd64.s:667

Thread T3 created by T0 here:
    #0 0x7fc029868815 in __interceptor_pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cc:208
    #1 0x1d7bd46 in _cgo_try_pthread_create (/milvus/bin/milvus+0x1d7bd46)
    #2 0x1d7bf73 in _cgo_sys_thread_start (/milvus/bin/milvus+0x1d7bf73)
    #3 0x1d7c4a2 in x_cgo_thread_start (/milvus/bin/milvus+0x1d7c4a2)
    #4 0x942f6c in runtime.asmcgocall /root/.gvm/gos/go1.16.9/src/runtime/asm_amd64.s:697
    #5 0x90f105 in runtime.newm /root/.gvm/gos/go1.16.9/src/runtime/proc.go:2123
    #6 0x90f904 in runtime.startm /root/.gvm/gos/go1.16.9/src/runtime/proc.go:2378
    #7 0x90fec5 in runtime.wakep /root/.gvm/gos/go1.16.9/src/runtime/proc.go:2477
    #8 0x93ad36 in runtime.newproc.func1 /root/.gvm/gos/go1.16.9/src/runtime/proc.go:4029
    #9 0x941505 in runtime.systemstack /root/.gvm/gos/go1.16.9/src/runtime/asm_amd64.s:379

SUMMARY: AddressSanitizer: heap-buffer-overflow /milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:272 in milvus::segcore::SegmentSealedImpl::get_deleted_bitmap(long, unsigned long, long, bool) const
Shadow bytes around the buggy address:
  0x0c5a80010c30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c5a80010c40: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c5a80010c50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c5a80010c60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c5a80010c70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c5a80010c80:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5a80010c90: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5a80010ca0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5a80010cb0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5a80010cc0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5a80010cd0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==8==ABORTING

**Comment by longjiquan** [comment]
@qi49125 thx for the very detailed information. We'll fix this soon.

**Comment by xiaofan-luan** [comment]
@qi49125 thanks for the patience, we will work on this!

**Comment by longjiquan** [comment]
@qi49125 sorry, but maybe you can wait for the Milvus 2.1 release. We have fixed many search issues, some of them are related to what you described above.

**Comment by jaime0815** [comment]
the related implementation has been reconstructed within 2.1 version,   and it works with 2.1  after verify
