### ISSUE TITLE
[Bug]: Standalone CrashLoopBackOff after standalone pod kill chaos

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#17515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220613-b3f0bbad
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus==2.1.0.dev69
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
2022/06/13 04:49:04.414 +00:00] [DEBUG] [global_rmq.go:97] [RocksmqRetentionTimeInMinutes=10080] [RocksmqRetentionSizeInMB=8192] [RocksmqPageSize=2147483648]
[2022/06/13 04:49:04.414 +00:00] [DEBUG] [rocksmq_impl.go:156] ["Start rocksmq "] ["max proc"=96] [parallism=4]
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x7fdc068047f0]

runtime stack:
runtime.throw(0x3f7b77a, 0x2a)
	/usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:718 +0x2e5

goroutine 1 [syscall]:
runtime.cgocall(0x228fce9, 0xc000988f20, 0xc000693628)
	/usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc000988ef0 sp=0xc000988eb8 pc=0x85265b
github.com/tecbot/gorocksdb._Cfunc_rocksdb_get(0x7fdc02208060, 0x7fdc022c4900, 0xc000ddf168, 0x6, 0xc000ddf170, 0xc000693628, 0x0)
	_cgo_gotypes.go:1597 +0x49 fp=0xc000988f20 sp=0xc000988ef0 pc=0x15460e9
github.com/tecbot/gorocksdb.(*DB).Get.func1(0xc000dfc7a0, 0xc000989058, 0xc000ddf168, 0xc000ddf168, 0x6, 0x8, 0xc000ddf170, 0xc000693628, 0xc000989000)
	/go/pkg/mod/github.com/tecbot/gorocksdb@v0.0.0-20191217155057-f0fad39f321c/db.go:247 +0x105 fp=0xc000988f78 sp=0xc000988f20 pc=0x155c065
github.com/tecbot/gorocksdb.(*DB).Get(0xc000dfc7a0, 0xc000989058, 0xc000ddf168, 0x6, 0x8, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/tecbot/gorocksdb@v0.0.0-20191217155057-f0fad39f321c/db.go:247 +0xf9 fp=0xc000989010 sp=0xc000988f78 pc=0x154f3b9
github.com/milvus-io/milvus/internal/kv/rocksdb.(*RocksdbKV).Load(0xc000defa70, 0x3f1f235, 0x6, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/milvus-io/milvus/internal/kv/rocksdb/rocksdb_kv.go:106 +0x11c fp=0xc0009890b8 sp=0xc000989010 pc=0x156ab1c
github.com/milvus-io/milvus/internal/tso.(*timestampOracle).loadTimestamp(0xc0005a3090, 0x8, 0x8, 0x853845, 0xc000989188, 0x89266a)
	/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:77 +0x49 fp=0xc000989128 sp=0xc0009890b8 pc=0x15036a9
github.com/milvus-io/milvus/internal/tso.(*timestampOracle).InitTimestamp(0xc0005a3090, 0xc0005a3001, 0xc000de8e80)
	/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:104 +0x45 fp=0xc0009892b0 sp=0xc000989128 pc=0x1503a85
github.com/milvus-io/milvus/internal/tso.(*GlobalTSOAllocator).Initialize(0xc000de8e70, 0xc000de8e80, 0x42cb620)
	/go/src/github.com/milvus-io/milvus/internal/tso/global_allocator.go:86 +0x2e fp=0xc0009892d8 sp=0xc0009892b0 pc=0x1502f2e
github.com/milvus-io/milvus/internal/allocator.(*GlobalIDAllocator).Initialize(...)
	/go/src/github.com/milvus-io/milvus/internal/allocator/global_id.go:51
github.com/milvus-io/milvus/internal/mq/mqimpl/rocksmq/server.NewRocksMQ(0xc00079e330, 0x18, 0x0, 0x0, 0x3, 0xf, 0xb)
	/go/src/github.com/milvus-io/milvus/internal/mq/mqimpl/rocksmq/server/rocksmq_impl.go:195 +0x798 fp=0xc0009894a0 sp=0xc0009892d8 pc=0x1570718
github.com/milvus-io/milvus/internal/mq/mqimpl/rocksmq/server.InitRocksMQ.func1()
	/go/src/github.com/milvus-io/milvus/internal/mq/mqimpl/rocksmq/server/global_rmq.go:99 +0x5c5 fp=0xc0009896a0 sp=0xc0009894a0 pc=0x157e005
sync.(*Once).doSlow(0x5bad7a8, 0xc000989710)
	/usr/local/go/src/sync/once.go:68 +0xec fp=0xc0009896f0 sp=0xc0009896a0 pc=0x8cd80c
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:59
github.com/milvus-io/milvus/internal/mq/mqimpl/rocksmq/server.InitRocksMQ(0xc00079e330, 0x18, 0xc, 0xc00079e330)
	/go/src/github.com/milvus-io/milvus/internal/mq/mqimpl/rocksmq/server/global_rmq.go:52 +0x9f fp=0xc000989740 sp=0xc0009896f0 pc=0x156fd5f
github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run(0xc0007d4890, 0xc000012001, 0x0, 0x0)
	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:371 +0x10e5 fp=0xc000989e38 sp=0xc000989740 pc=0x2284945
github.com/milvus-io/milvus/cmd/milvus.RunMilvus(0xc000050090, 0x3, 0x3)
	/go/src/github.com/milvus-io/milvus/cmd/milvus/milvus.go:333 +0x85b fp=0xc000989f60 sp=0xc000989e38 pc=0x228c1bb
main.main()
	/go/src/github.com/milvus-io/milvus/cmd/main.go:26 +0x45 fp=0xc000989f88 sp=0xc000989f60 pc=0x228cc25
runtime.main()
	/usr/local/go/src/runtime/proc.go:225 +0x256 fp=0xc000989fe0 sp=0xc000989f88 pc=0x88a1b6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000989fe8 sp=0xc000989fe0 pc=0x8c2101

goroutine 274 [chan receive]:
github.com/panjf2000/ants/v2.(*Pool).purgePeriodically(0xc0007d8150)
	/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.8/pool.go:69 +0x109
created by github.com/panjf2000/ants/v2.NewPool
	/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.8/pool.go:137 +0x232

```

```
12:51:33  + kubectl get pods -o wide
12:51:33  + grep standalone-pod-kill-6433
12:51:34  standalone-pod-kill-6433-etcd-0                               1/1     Running            0          17m     10.97.20.85    qa-node018.zilliz.local   <none>           <none>
12:51:34  standalone-pod-kill-6433-milvus-standalone-6998465787-2xxfc   0/1     CrashLoopBackOff   7          11m     10.97.20.231   qa-node018.zilliz.local   <none>           <none>
12:51:34  standalone-pod-kill-6433-minio-858588c58d-4xmmp               1/1     Running            0          17m     10.97.20.83    qa-node018.zilliz.local   <none>           <none>
```

### Expected Behavior

Milvus recovery and all test cases pass

### Steps To Reproduce

```markdown
see http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/6433/pipeline
```

### Milvus Log

failed job: http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/6433/pipeline
log:[artifacts-standalone-pod-kill-6433-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/8888090/artifacts-standalone-pod-kill-6433-server-logs.tar.gz)

**Comment by zhuwenxing** [comment]
failed job：https://github.com/zhuwenxing/milvus/runs/6855611554?check_suite_focus=true

**Comment by zhuwenxing** [comment]
This also happened when Milvus  standalone  upgrading to the `master-20220613-e6225d92` 

failed job: http://10.100.32.144:8080/blue/organizations/jenkins/deploy_test/detail/deploy_test/793/pipeline
log: [artifacts-standalone-upgrade-793-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/8889494/artifacts-standalone-upgrade-793-logs.1.tar.gz)

**Comment by zhuwenxing** [comment]
tests of standalone pod kill, standalone reinstallation, and standalone upgrading all passed.

So remove critical label
