### ISSUE TITLE
[Bug]: [Nightly] Panic occurs after "release collection from query nodes failed"

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#17526]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: c77bc81
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus==2.1.0.dev69
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Panic occurs:

mdp-585-n-milvus-querycoord-678866dc6c-gsfxm_milvus-ci_querycoord-ab293c0a189dd89b20c4b3ee53465ba5d852f1e11068286c22743f3fec01ac9f.log:panic: All attempts results:

```
[2022/06/10 21:03:02.232 +00:00] [DEBUG] [retry.go:39] ["retry func failed"] ["retry time"=0] [error="context canceled"]

[2022/06/10 21:03:02.231 +00:00] [ERROR] [impl.go:382] ["release collection from query nodes failed"] [role=querycoord] [collectionID=433818959911583745] [msgID=0] [error=timeout] [stack="github.com/milvus-io/milvus/internal/querycoord.(*QueryCoord).ReleaseCollection\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/impl.go:382\ngithub.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).ReleaseCollection\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/service.go:351\ngithub.com/milvus-io/milvus/internal/proto/querypb._QueryCoord_ReleaseCollection_Handler.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proto/querypb/query_coord.pb.go:3370\ngithub.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38\ngithub.com/milvus-io/milvus/internal/proto/querypb._QueryCoord_ReleaseCollection_Handler\n\t/go/src/github.com/milvus-io/milvus/internal/proto/querypb/query_coord.pb.go:3372\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1286\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1609\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:934"]

panic: All attempts results:

attempt #1:context canceled

attempt #2:context canceled





goroutine 6187019 [running]:

github.com/milvus-io/milvus/internal/querycoord.(*loadSegmentTask).postExecute(0xc00147c960, 0x42a8d38, 0xc00115bb90, 0x1, 0x3f43fdd)

        /go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:1263 +0x27b

github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processTask.func2(0x42cc420, 0xc0013a2a20, 0x42dd658, 0xc00147c960, 0x42a8d38, 0xc00115bb90)

        /go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:521 +0x127

github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processTask(0xc000d40800, 0x42dd658, 0xc00147c960, 0x426f640, 0xc001393e60)

        /go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:529 +0x87c

github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processActivateTaskLoop.func1(0xc000d40800, 0x42dd658, 0xc00147c960)
```

### Expected Behavior

No panic, and tests run successfully

### Steps To Reproduce

```markdown
Running nightly:
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/585/pipeline
```

### Milvus Log

[artifacts-milvus-distributed-pulsar-master-585-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/585/artifact/artifacts-milvus-distributed-pulsar-master-585-pymilvus-e2e-logs.tar.gz)

**Comment by binbinlv** [comment]
Has not been reproduced for a period of time, so close it first. And will reopen if it occurs in the future.
