### ISSUE TITLE
[Bug]: The queryCoord `panic: All attempts results` when loading two replicas

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#17523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220613-d1de8cab
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.1.0.dev67
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. Deploy cluster with 2 querynodes, and limit their memory 2Gi
2. Insert entities: `dim=512, nb=500000, ni=25000 （num of insert each time)`
3. Load collection with `replica_number=2`
queryCoord crash and panic
```
[2022/06/13 07:32:38.673 +00:00] [ERROR] [global_meta_broker.go:522] ["QueryCoord release reference lock on segments failed"] [segmentIDs="[433875763812106242,433875774952964097,433875969280311298,433875966016618497,433875966003511297,433875969280311297,433875962858045442,433875741319888897,433875949829226498,433875959620304898,433875949816119298,433875969293418497,433875744976797698,433875763824951298,433875953263312897,433875760194256897,433875741319888898,433875752814903298,433875752828010498,433875774939856898,433875943039696898,433875962871152641,433875748922327042,433875969267466241,433875744989904898,433875939828695042,433875946316496898,433875774939856897,433875760220733441,433875774952964098,433875943026851841,433875949829226497,433875771191197698,433875943026851842,433875744989904897,433875756366954497,433875748908957698,433875767573610497,433875946329604098,433875748908957697,433875767560703298,433875966016618498,433875771191197697,433875953263312898,433875752814903297,433875946316496897,433875760194256898,433875943039696897,433875959620304897,433875756353847298,433875748922327041,433875953250667841,433875962871152642,433875763824951297,433875939828695041,433875767573610498,433875956513898498,433875771207974914,433875946329604097,433875953250667842,433875966003511298,433875756353847297,433875771207974913,433875956513898497,433875962858045441,433875956500791297,433875767560703297,433875741309665282,433875949816119297,433875959633674241,433875763812106241,433875939841540098,433875956500791298,433875744976797697,433875939841540097,433875741309665281,433875756366954498,433875959633674242,433875760207626241,433875752828010497]"] ["failed reason"="etcdserver: too many operations in txn request"] [stack="github.com/milvus-io/milvus/internal/querycoord.(*globalMetaBroker).releaseSegmentReferLock.func1\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/global_meta_broker.go:522\ngithub.com/milvus-io/milvus/internal/util/retry.Do\n\t/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:37\ngithub.com/milvus-io/milvus/internal/querycoord.(*globalMetaBroker).releaseSegmentReferLock\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/global_meta_broker.go:513\ngithub.com/milvus-io/milvus/internal/querycoord.(*loadSegmentTask).postExecute\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:1262\ngithub.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processTask.func2\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:521\ngithub.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processTask\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:563\ngithub.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processActivateTaskLoop.func1\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:866"]
panic: All attempts results:
attempt #1:etcdserver: too many operations in txn request
attempt #2:etcdserver: too many operations in txn request
attempt #3:etcdserver: too many operations in txn request
attempt #4:etcdserver: too many operations in txn request
attempt #5:etcdserver: too many operations in txn request
attempt #6:etcdserver: too many operations in txn request
attempt #7:etcdserver: too many operations in txn request
attempt #8:context deadline exceeded


goroutine 251 [running]:
github.com/milvus-io/milvus/internal/querycoord.(*loadSegmentTask).postExecute(0xc00021e730, 0x42aa4d8, 0xc0005277d0, 0x1, 0x3f5b331)
	/go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:1263 +0x27b
github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processTask.func2(0x42cdbc0, 0xc00033ab40, 0x42dee38, 0xc00021e730, 0x42aa4d8, 0xc0005277d0)
	/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:521 +0x127
github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processTask(0xc000db2e00, 0x42dee38, 0xc00021e730, 0x0, 0x0)
	/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:563 +0x1310
github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processActivateTaskLoop.func1(0xc000db2e00, 0x42dee38, 0xc00021e730)
	/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:866 +0x3f
created by github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processActivateTaskLoop
	/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:865 +0x151
```
Client exception:
```
[2022-06-13 15:31:47,267 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 2, 20], kwargs: {} (api_request.py:55)
[2022-06-13 15:32:04,233 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/nausicca/projects/milvus/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
    res = func(*args, **kwargs)
  File "/Users/nausicca/projects/milvus/tests/python_client/utils/api_request.py", line 56, in api_request
    return func(*arg, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 450, in load
    conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 61, in handler
    raise e
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 44, in handler
    return func(self, *args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 79, in handler
    raise e
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 75, in handler
    return func(*args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 686, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 61, in handler
    raise e
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 44, in handler
    return func(self, *args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 79, in handler
    raise e
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 75, in handler
    return func(*args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 697, in wait_for_loading_collection
    return self._wait_for_loading_collection(collection_name, timeout)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 726, in _wait_for_loading_collection
    progress = self.get_collection_loading_progress(collection_name, timeout)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 705, in get_collection_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=QueryCoord is not healthy)>
 (api_request.py:35)
[2022-06-13 15:32:04,234 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=QueryCoord is not healthy)> (api_request.py:36)
FAILED
```

Server logs:
[mic_logs.tar.gz](https://github.com/milvus-io/milvus/files/8889066/mic_logs.tar.gz)

```
spec:
  dependencies:
    etcd:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
        values:
          persistence:
            storageClass: local-path
    pulsar:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
        values:
          proxy:
            configData:
              httpNumThreads: "80"
          zookeeper:
            volumes:
              data:
                storageClassName: local-path
            bookkeeper:
              volumes:
                journal:
                  storageClassName: local-path
                ledgers:
                  storageClassName: local-path
    storage:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
        values:
          persistence:
            storageClass: local-path
  components:
    image: harbor.zilliz.cc/milvus/milvus:master-20220613-d1de8cab
    #image: milvusdb/milvus-dev:master-20220513-c5149c7e
    proxy:
      serviceType: LoadBalancer
    queryNode:
      replicas: 2
      resources:
       limits:
         memory: 2Gi
  config:
    log:
      level: debug
    common:
      retentionDuration: 40
    queryNode:
      gracefulTime: 0
```

**Comment by yanliang567** [comment]
/assign @congqixia 
@congqixia sounds like a issue with mulit memory replicas

/unassign

**Comment by xiaofan-luan** [comment]
/assign @xiaocai2333 
should not multi save in a txn.

**Comment by xiaofan-luan** [comment]
Another question, why add lock successfully but release failed? @xiaocai2333

**Comment by xiaocai2333** [comment]
> Another question, why add lock successfully but release failed? @xiaocai2333

I did a test locally, the same number of keys (160), etcdKV multiSave can be successful, but multiRemove will report the error.

**Comment by xiaocai2333** [comment]
> Another question, why add lock successfully but release failed? @xiaocai2333

this is a bug, in the case of multiple replicas, multiple locks will be added to a segment. When the lock is released, all the locks of the same nodeID on the segment will be obtained, so there are more keys when releasing the lock than when locking.

**Comment by xiaocai2333** [comment]
@ThreadDao pr is merged, please verify it.
/unassign
/assign @ThreadDao

**Comment by BUPTAnderson** [comment]
@xiaocai2333 after i merged the pr #17544, the datacoord can not start.

```
[2022/06/16 18:50:33.507 +08:00] [ERROR] [segment_reference_manager.go:57] ["unmarshal segment reference lock failed"] [error="proto: cannot parse invalid wire-format data"] [stack="github.com/milvus-io/milvus/internal/datacoord.NewSegmentReferenceManager
/opt/milvus/internal/datacoord/segment_reference_manager.go:57\ngithub.com/milvus-io/milvus/internal/datacoord.(*Server).initServiceDiscovery
/opt/milvus/internal/datacoord/server.go:465\ngithub.com/milvus-io/milvus/internal/datacoord.(*Server).Start
/opt/milvus/internal/datacoord/server.go:291\ngithub.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).start
/opt/milvus/internal/distributed/datacoord/service.go:162\ngithub.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).Run
/opt/milvus/internal/distributed/datacoord/service.go:212\ngithub.com/milvus-io/milvus/cmd/components.(*DataCoord).Run
/opt/milvus/cmd/components/data_coord.go:47\ngithub.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runDataCoord.func1
/opt/milvus/cmd/roles/roles.go:251"]
[2022/06/16 18:50:33.508 +08:00] [ERROR] [service.go:164] ["DataCoord start failed"] [error="proto: cannot parse invalid wire-format data"] [stack="github.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).start
/opt/milvus/internal/distributed/datacoord/service.go:164\ngithub.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).Run
/opt/milvus/internal/distributed/datacoord/service.go:212\ngithub.com/milvus-io/milvus/cmd/components.(*DataCoord).Run
/opt/milvus/cmd/components/data_coord.go:47\ngithub.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runDataCoord.func1
/opt/milvus/cmd/roles/roles.go:251"]
```

**Comment by xiaocai2333** [comment]
@BUPTAnderson  Yes, we made an incompatible change here, you need to re-execute your service with a new version of milvus.

**Comment by BUPTAnderson** [comment]
> @BUPTAnderson Yes, we made an incompatible change here, you need to re-execute your service with a new version of milvus.

got it
