### ISSUE TITLE
[Bug]: Query timeout after Milvus cluster upgrading

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#17540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.0.2 --> master-20220613-e9dcda16
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.1.0.dev69
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Search latency is very large and query timeout
```
Search...
(distance: 31.969785690307617, id: 2015) -14.0
(distance: 32.696746826171875, id: 952) -11.0
(distance: 32.8[47](https://github.com/milvus-io/milvus/runs/6869230327?check_suite_focus=true#step:14:48)53036[49](https://github.com/milvus-io/milvus/runs/6869230327?check_suite_focus=true#step:14:50)90234, id: 2537) -13.0
(distance: 32.95743179321289, id: 863) -11.0
(distance: 33.11928939819336, id: 1780) -16.0
[2015, 952, 2537, 863, 1780]
search latency: 88.22
[51](https://github.com/milvus-io/milvus/runs/6869230327?check_suite_focus=true#step:14:52)s
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 44, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 87, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 75, in handler
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 978, in query
    response = future.result()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655154256.425830434","description":"Error received from peer ipv4:127.0.0.1:19[53](https://github.com/milvus-io/milvus/runs/6869230327?check_suite_focus=true#step:14:54)0","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "scripts/action_after_upgrade.py", line 93, in <module>
    task_1(data_size, host)
  File "scripts/action_after_upgrade.py", line 18, in task_1
    load_and_search(prefix)
  File "/home/runner/work/milvus/milvus/tests/python_client/deploy/scripts/utils.py", line 172, in load_and_search
    res = c.query(expr, output_fields, timeout=20)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 771, in query
    res = conn.query(self._name, expr, output_fields, partition_names, timeout=timeout, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line [55](https://github.com/milvus-io/milvus/runs/6869230327?check_suite_focus=true#step:14:56), in handler
    raise MilvusException(Status.UNEXPECTED_ERROR, "rpc timeout")
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=rpc timeout)>
```

### Expected Behavior

all test cases passed

### Steps To Reproduce

```markdown
see https://github.com/milvus-io/milvus/runs/6869230327?check_suite_focus=true
```

### Milvus Log

failed job: https://github.com/milvus-io/milvus/runs/6869230327?check_suite_focus=true
log: https://github.com/milvus-io/milvus/suites/6915452295/artifacts/268758516

### Anything else?

It is not a stable issue, not sure whether it is because of network problems

It works well in Jenkins and another GitHub action job: https://github.com/zhuwenxing/milvus/runs/6869321657?check_suite_focus=true

**Comment by yanliang567** [comment]
keep in my plate for now, to see if it reproduces stably or not.
