### ISSUE TITLE
[Bug]: [bulkload]failed to load collection after bulk load data

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#17600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220615-54aeb077
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.0.dev74
```

### Current Behavior

error pops up when collection.load() after bulk load data
```
[2022-06-16 19:26:17 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=call query coordinator LoadCollection: err: find no available querycoord, check querycoord state
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:253 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall
/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/client/client.go:169 github.com/milvus-io/milvus/internal/distributed/querycoord/client.(*Client).LoadCollection
/go/src/github.com/milvus-io/milvus/internal/proxy/task.go:2759 github.com/milvus-io/milvus/internal/proxy.(*loadCollectionTask).Execute
/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:465 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask
/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:494 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop
/usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit
)>, <Time:{'RPC start': '2022-06-16 19:26:17.139870', 'RPC error': '2022-06-16 19:26:17.165936'}> (decorators.py:78)
[2022-06-16 19:26:17 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/yanliang/fork/milvus/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
    res = func(*args, **kwargs)
  File "/Users/yanliang/fork/milvus/tests/python_client/utils/api_request.py", line 56, in api_request
    return func(*arg, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 465, in load
    conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 61, in handler
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 44, in handler
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 79, in handler
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 75, in handler
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 684, in load_collection
    raise MilvusException(response.error_code, response.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=call query coordinator LoadCollection: err: find no available querycoord, check querycoord state
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:253 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall
/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/client/client.go:169 github.com/milvus-io/milvus/internal/distributed/querycoord/client.(*Client).LoadCollection
/go/src/github.com/milvus-io/milvus/internal/proxy/task.go:2759 github.com/milvus-io/milvus/internal/proxy.(*loadCollectionTask).Execute
/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:465 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask
/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:494 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop
/usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit
)>
 (api_request.py:35)
[2022-06-16 19:26:17 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=call query coordinator LoadCollection: err: find no available querycoord, check querycoord state
```

### Expected Behavior

load successfully and avaiable for search

### Steps To Reproduce

```markdown
run  test_bulk_load.py or test_bulk_load.py::TestBulkLoad::test_float_vector_from_numpy_file
```

### Milvus Log

check collection name: test_bXU7XuuM or test_21vyjx4r
[bulkload.collectionloadfail.log.tar.gz](https://github.com/milvus-io/milvus/files/8918440/bulkload.collectionloadfail.log.tar.gz)

### Anything else?

sometimes timeout error
```
[2022-06-16 19:13:43 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 20], kwargs: {} (api_request.py:55)
[2022-06-16 19:14:03 - ERROR - pymilvus.decorators]: grpc RpcError: [load_collection], <_MultiThreadedRendezvous: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded>, <Time:{'RPC start': '2022-06-16 19:13:43.750507', 'gRPC error': '2022-06-16 19:14:03.754608'}> (decorators.py:86)
[2022-06-16 19:14:03 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 44, in handler
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 87, in handler
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 75, in handler
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 682, in load_collection
    response = rf.result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655378043.754165000","description":"Error received from peer ipv4:10.98.0.8:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yanliang/fork/milvus/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
    res = func(*args, **kwargs)
  File "/Users/yanliang/fork/milvus/tests/python_client/utils/api_request.py", line 56, in api_request
    return func(*arg, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 465, in load
    conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 55, in handler
    raise MilvusException(Status.UNEXPECTED_ERROR, "rpc timeout")
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=rpc timeout)>
 (api_request.py:35)
[2022-06-16 19:14:03 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=rpc timeout)> (api_request.py:36)
```

**Comment by yanliang567** [comment]
@soothing-rain I set it to urgent as it blocks the feature bulk load
/assign @soothing-rain 
/unassign

**Comment by soothing-rain** [comment]
![image](https://user-images.githubusercontent.com/69466447/174078400-6d145b4c-6160-420c-aa2a-8fb33dbc7f21.png)

Not able to reproduce with the latest master branch and a clean Etcd.

Can you double check with the latest code? We recently changed some proto/meta which might cause some inconsistency.

**Comment by yanliang567** [comment]
not reproduced on [master-20220616-53a49a92]

**Comment by yhmo** [comment]
Reproduce steps:
1. create collection
2. bulkload 10 row-based json files
3. load collection
4. get num_entities of collection

Could hang at step 4, the client num_entities call flush() then GetFlushState() to wait flush finish, it receive some segment ids from flush(), then call GetFlushState() to check flushed state, but these segment flushed state always false.

**Comment by yhmo** [comment]
Reproduce script:
[example_bulkload.txt](https://github.com/milvus-io/milvus/files/8933271/example_bulkload.txt)

**Comment by xiaofan-luan** [comment]
@soothing-rain is there still a issue?

**Comment by soothing-rain** [comment]
No it should have been fixed for a while

/unassign
/assign @yanliang567
