### ISSUE TITLE
[Bug]: Create index failed showing "CreateIndex Timeout"

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#17611]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:latest
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2022-06-16T16:23:08.092Z] [2022-06-16 15:14:23 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['float_vector', {'index_type': 'IVF_FLAT', 'metric_type': 'IP', 'params': {'nlist': 64}}], kwargs: {'timeout': 40, 'index_name': '_default_idx'} (api_request.py:55)

[2022-06-16T16:23:08.092Z] [2022-06-16 15:15:03 - ERROR - pymilvus.decorators]: RPC error: [wait_for_creating_index], <MilvusException: (code=1, message=CreateIndex Timeout)>, <Time:{'RPC start': '2022-06-16 15:14:23.755124', 'RPC error': '2022-06-16 15:15:03.858443'}> (decorators.py:78)

[2022-06-16T16:23:08.092Z] [2022-06-16 15:15:03 - ERROR - pymilvus.decorators]: RPC error: [create_index], <MilvusException: (code=1, message=CreateIndex Timeout)>, <Time:{'RPC start': '2022-06-16 15:14:21.379270', 'RPC error': '2022-06-16 15:15:03.858782'}> (decorators.py:78)

[2022-06-16T16:23:08.092Z] [2022-06-16 15:15:03 - ERROR - ci_test]: Traceback (most recent call last):

[2022-06-16T16:23:08.092Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper

[2022-06-16T16:23:08.092Z]     res = func(*args, **kwargs)

[2022-06-16T16:23:08.092Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 56, in api_request

[2022-06-16T16:23:08.092Z]     return func(*arg, **kwargs)

[2022-06-16T16:23:08.092Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 1053, in create_index

[2022-06-16T16:23:08.092Z]     timeout=timeout, **kwargs)

[2022-06-16T16:23:08.092Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 61, in handler

[2022-06-16T16:23:08.092Z]     raise e

[2022-06-16T16:23:08.092Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 44, in handler

[2022-06-16T16:23:08.092Z]     return func(self, *args, **kwargs)

[2022-06-16T16:23:08.092Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 79, in handler

[2022-06-16T16:23:08.092Z]     raise e

[2022-06-16T16:23:08.092Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 75, in handler

[2022-06-16T16:23:08.092Z]     return func(*args, **kwargs)

[2022-06-16T16:23:08.092Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 598, in create_index

[2022-06-16T16:23:08.092Z]     index_name=index_name)

[2022-06-16T16:23:08.092Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 61, in handler

[2022-06-16T16:23:08.092Z]     raise e

[2022-06-16T16:23:08.092Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 44, in handler

[2022-06-16T16:23:08.092Z]     return func(self, *args, **kwargs)

[2022-06-16T16:23:08.092Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 79, in handler

[2022-06-16T16:23:08.092Z]     raise e

[2022-06-16T16:23:08.092Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 75, in handler

[2022-06-16T16:23:08.092Z]     return func(*args, **kwargs)

[2022-06-16T16:23:08.093Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 673, in wait_for_creating_index

[2022-06-16T16:23:08.093Z]     raise MilvusException(1, "CreateIndex Timeout")

[2022-06-16T16:23:08.093Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=CreateIndex Timeout)>
```

### Expected Behavior

No error

### Steps To Reproduce

```markdown
Running nightly:
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/596/pipeline
```

### Milvus Log

1. milvus log:
[artifacts-milvus-distributed-pulsar-master-596-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/596/artifact/artifacts-milvus-distributed-pulsar-master-596-pymilvus-e2e-logs.tar.gz)

2. collection name: index_n4GaYkkd

**Comment by xiaocai2333** [comment]
sorry, my bad, when GetIndexState, I got all the segments in the meta.
If there is multiple collections, it will get all segments of all collections. I will fix it.

**Comment by xiaocai2333** [comment]
When segments was compacted, RootCoord not notify IndexCoord to remove the indexes on old segments. IndexCoord acquires the lock failed from DataCoord. It will retry util timeout.

pr #17490  will fix it.

**Comment by xiaocai2333** [comment]
pr  #17490 is merged, please check it.
/unassign
/assign @xiaocai2333

**Comment by binbinlv** [comment]
From CI, it not occurs, so cancel the urgent first, and will close it if it is OK in today's nightly.

**Comment by binbinlv** [comment]
It is not reproduced from nightly, so fixed. Close it.
