### ISSUE TITLE
[Bug]: [kafka] Search failed for "fail to search on all shard leader, reason cannot find sealed segment 433954856578318337 in QueryNode"

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#17610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: latest
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/597/pipeline/

```
[2022-06-16T20:11:03.420Z] [2022-06-16 19:06:48 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.04391477498963806, 0.09329465701626809, 0.06816913869839321, 0.0631772495394412, 0.022763909690302144, 0.0021298151162184474, 0.03260865849978516, 0.06299651240119745, 0.09458848081577231, 0.002271762953380622, 0.07434198426325017, 0.1421428663310066, 0.11422547261201617, 0.030116180897667714, ......, kwargs: {} (api_request.py:55)

[2022-06-16T20:11:03.420Z] [2022-06-16 19:06:48 - ERROR - pymilvus.decorators]: RPC error: [_execute_search_requests], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=Search 1 failed, reason cannot find sealed segment 433954856578318337 in QueryNode err %!w(<nil>))>, <Time:{'RPC start': '2022-06-16 19:06:48.046693', 'RPC error': '2022-06-16 19:06:48.393420'}> (decorators.py:78)

[2022-06-16T20:11:03.420Z] [2022-06-16 19:06:48 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=Search 1 failed, reason cannot find sealed segment 433954856578318337 in QueryNode err %!w(<nil>))>, <Time:{'RPC start': '2022-06-16 19:06:48.042160', 'RPC error': '2022-06-16 19:06:48.393729'}> (decorators.py:78)

[2022-06-16T20:11:03.420Z] [2022-06-16 19:06:48 - ERROR - ci_test]: Traceback (most recent call last):

[2022-06-16T20:11:03.420Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper

[2022-06-16T20:11:03.420Z]     res = func(*args, **kwargs)

[2022-06-16T20:11:03.420Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 56, in api_request

[2022-06-16T20:11:03.420Z]     return func(*arg, **kwargs)

[2022-06-16T20:11:03.420Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 690, in search

[2022-06-16T20:11:03.420Z]     partition_names, output_fields, round_decimal, timeout=timeout, **kwargs)

[2022-06-16T20:11:03.420Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 61, in handler

[2022-06-16T20:11:03.420Z]     raise e

[2022-06-16T20:11:03.420Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 44, in handler

[2022-06-16T20:11:03.420Z]     return func(self, *args, **kwargs)

[2022-06-16T20:11:03.420Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 79, in handler

[2022-06-16T20:11:03.420Z]     raise e

[2022-06-16T20:11:03.420Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 75, in handler

[2022-06-16T20:11:03.420Z]     return func(*args, **kwargs)

[2022-06-16T20:11:03.420Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 449, in search

[2022-06-16T20:11:03.420Z]     return self._execute_search_requests(requests, timeout, **_kwargs)

[2022-06-16T20:11:03.420Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 79, in handler

[2022-06-16T20:11:03.420Z]     raise e

[2022-06-16T20:11:03.420Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 75, in handler

[2022-06-16T20:11:03.420Z]     return func(*args, **kwargs)

[2022-06-16T20:11:03.420Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 411, in _execute_search_requests

[2022-06-16T20:11:03.420Z]     raise pre_err

[2022-06-16T20:11:03.420Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 402, in _execute_search_requests

[2022-06-16T20:11:03.420Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2022-06-16T20:11:03.420Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=Search 1 failed, reason cannot find sealed segment 433954856578318337 in QueryNode err %!w(<nil>))>

[2022-06-16T20:11:03.420Z]  (api_request.py:35)

[2022-06-16T20:11:03.420Z] [2022-06-16 19:06:48 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=Search 1 failed, reason cannot find sealed segment 433954856578318337 in QueryNode err %!w(<nil>))> (api_request.py:36)
```

### Expected Behavior

No error

### Steps To Reproduce

```markdown
Running nightly:
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/597/pipeline/
```

### Milvus Log

1. milvus log: 
[artifacts-milvus-distributed-kafka-master-597-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/597/artifact/artifacts-milvus-distributed-kafka-master-597-pymilvus-e2e-logs.tar.gz)

2. collection name: compact_tgWHMJfQ

**Comment by binbinlv** [comment]
Not reproduced for a period of time, close it first and will reopen it if it occurs in the future.
