### ISSUE TITLE
[Bug]: Load failed with error message `collection xxx has not been loaded to memory or load failed` after  `allcluster` pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#17645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220619-516d9147
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.1.0.dev69
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
Traceback (most recent call last):
  File "chaos/scripts/hello_milvus.py", line 116, in <module>
    hello_milvus(args.host)
  File "chaos/scripts/hello_milvus.py", line 79, in hello_milvus
    collection.load()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 450, in load
    conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 61, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 44, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 79, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 75, in handler
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 686, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 61, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 44, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 79, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 75, in handler
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 697, in wait_for_loading_collection
    return self._wait_for_loading_collection(collection_name, timeout)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 726, in _wait_for_loading_collection
    progress = self.get_collection_loading_progress(collection_name, timeout)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 705, in get_collection_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection hello_milvus has not been loaded to memory or load failed)>
```

### Expected Behavior

all test cases passed

### Steps To Reproduce

```markdown
see https://github.com/milvus-io/milvus/runs/6956973459?check_suite_focus=true
```

### Milvus Log

failed job: https://github.com/milvus-io/milvus/runs/6956973459?check_suite_focus=true
log: https://github.com/milvus-io/milvus/suites/6997534572/artifacts/274320003

### Anything else?

some related issue

https://github.com/milvus-io/milvus/issues/17607

**Comment by zhuwenxing** [comment]
/assign @wayblink 
/assign @yah01 
please help to take a look!

**Comment by xiaocai2333** [comment]
When loading Segment, if the segment is compacted, the binlog file will not be deleted due to the reference lock, but the index files will be deleted.

I have a suggestion, when there is reference lock on the segment, the segment can not be compacted.
/assign

**Comment by xiaocai2333** [comment]
This problem did not occur before, because the segment was compacted before, RootCoord did not notify IndexCoord to delete the corresponding index.

**Comment by xiaofan-luan** [comment]
> When loading Segment, if the segment is compacted, the binlog file will not be deleted due to the reference lock, but the index files will be deleted.
> 
> I have a suggestion, when there is reference lock on the segment, the segment can not be compacted. /assign

We should have this on 2.1, there are a lot of issue relies on reference lock issue

**Comment by xiaocai2333** [comment]
> > When loading Segment, if the segment is compacted, the binlog file will not be deleted due to the reference lock, but the index files will be deleted.
> > I have a suggestion, when there is reference lock on the segment, the segment can not be compacted. /assign
> 
> We should have this on 2.1, there are a lot of issue relies on reference lock issue

working on it~

**Comment by zhuwenxing** [comment]
/assign @xiaocai2333 

version `master-20220620-32a3ed07`
failed job: https://github.com/milvus-io/milvus/runs/6972484048?check_suite_focus=true
log: https://github.com/milvus-io/milvus/suites/7011809634/artifacts/275312844 (log is in dir `data-consist-test`)

**Comment by zhuwenxing** [comment]
indexcoord: https://github.com/milvus-io/milvus/runs/6972483329?check_suite_focus=true

**Comment by zhuwenxing** [comment]
pulsar pod kill
failed job: https://github.com/milvus-io/milvus/runs/7029767749?check_suite_focus=true
log:https://github.com/milvus-io/milvus/suites/7066674819/artifacts/278802690 (log is in dir `data-consist-test`)

querycoord pod kill
failed job: https://github.com/milvus-io/milvus/runs/7029767856?check_suite_focus=true
log: https://github.com/milvus-io/milvus/suites/7066674819/artifacts/278802691 (log is in dir `data-consist-test`)

**Comment by congqixia** [comment]
letian's PR #17715 has some problem. And @xiaofan-luan is doing some refactoring about handoff handler, PR #17805
/assign @xiaofan-luan

**Comment by zhuwenxing** [comment]
failed job: https://github.com/zhuwenxing/milvus/runs/7079306151?check_suite_focus=true
log: https://github.com/zhuwenxing/milvus/suites/7113331109/artifacts/281973261 (log is in dir `data-consist-test`)

This issue only happened in the e2e test stage after `data consist test`, and I am confused about this phenomenon.

**Comment by yanliang567** [comment]
not reproduce these day, degrade priority

**Comment by zhuwenxing** [comment]
A new failed job: http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test-kafka/detail/chaos-test-kafka/377/pipeline
log:  [artifacts-minio-pod-kill-377-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9068394/artifacts-minio-pod-kill-377-server-logs.tar.gz)
