### ISSUE TITLE
[Bug]: pymilvus 2.0.2 fails to search against Milvus 2.1 master build on collections that created on 2.0.2

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#17656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvus 2.0.2 -> master-20220620-f123d657
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.0.2
```

### Current Behavior

1. deploy Milvus 2.0.2 and pymilvus 2.0.2
2. create collection, insert data, create index and load()
3. verify search successfully
4. upgrade Milvus to 2.1(master-20220620-f123d657)
5. load the previous collection again with pymilvus 2.0.2
```
RPC error: [load_collection], <BaseException: (code=5, message=collection has already been loaded, and the number of replicas 1 is not same as the request's 0. Should release first then reload with the new number of replicas)>, <Time:{'RPC start': '2022-06-20 17:52:45.709906', 'RPC error': '2022-06-20 17:52:45.729260'}>
Traceback (most recent call last):
  File "/Users/yanliang/PycharmProjects/hello_milvus/hello_milmil.py", line 30, in <module>
    collection.load()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 453, in load
    conn.load_collection(self._name, timeout=timeout, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 666, in load_collection
    raise BaseException(response.error_code, response.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=5, message=collection has already been loaded, and the number of replicas 1 is not same as the request's 0. Should release first then reload with the new number of replicas)>

```
7. search the previous collection with pymilvus 2.0.2
```
RPC error: [_execute_search_requests], <BaseException: (code=1, message=fail to search on all shard leaders, err=All attempts results:
attempt #1:fail to get shard leaders from QueryCoord: no replica available
attempt #2:fail to get shard leaders from QueryCoord: no replica available
attempt #3:fail to get shard leaders from QueryCoord: no replica available
attempt #4:fail to get shard leaders from QueryCoord: no replica available
attempt #5:fail to get shard leaders from QueryCoord: no replica available
attempt #6:fail to get shard leaders from QueryCoord: no replica available
attempt #7:fail to get shard leaders from QueryCoord: no replica available
attempt #8:context deadline exceeded
)>, <Time:{'RPC start': '2022-06-20 17:48:48.740841', 'RPC error': '2022-06-20 17:48:58.857898'}>
RPC error: [search], <BaseException: (code=1, message=fail to search on all shard leaders, err=All attempts results:
attempt #1:fail to get shard leaders from QueryCoord: no replica available
attempt #2:fail to get shard leaders from QueryCoord: no replica available
attempt #3:fail to get shard leaders from QueryCoord: no replica available
attempt #4:fail to get shard leaders from QueryCoord: no replica available
attempt #5:fail to get shard leaders from QueryCoord: no replica available
attempt #6:fail to get shard leaders from QueryCoord: no replica available
attempt #7:fail to get shard leaders from QueryCoord: no replica available
attempt #8:context deadline exceeded
)>, <Time:{'RPC start': '2022-06-20 17:48:48.703644', 'RPC error': '2022-06-20 17:48:58.858398'}>
Traceback (most recent call last):
  File "/Users/yanliang/PycharmProjects/hello_milvus/hello_milmil.py", line 55, in <module>
    results = collection.search(search_vec, embedding_field.name, search_params, limit)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 690, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 21, in handler
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 457, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 404, in _execute_search_requests
    raise pre_err
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 395, in _execute_search_requests
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=fail to search on all shard leaders, err=All attempts results:
attempt #1:fail to get shard leaders from QueryCoord: no replica available
attempt #2:fail to get shard leaders from QueryCoord: no replica available
attempt #3:fail to get shard leaders from QueryCoord: no replica available
attempt #4:fail to get shard leaders from QueryCoord: no replica available
attempt #5:fail to get shard leaders from QueryCoord: no replica available
attempt #6:fail to get shard leaders from QueryCoord: no replica available
attempt #7:fail to get shard leaders from QueryCoord: no replica available
attempt #8:context deadline exceeded
)>
```

### Expected Behavior

no need to change any existing code
load and search successfully with pymilus 2.0.2

### Milvus Log

[fail.search.202.log.tar.gz](https://github.com/milvus-io/milvus/files/8944995/fail.search.202.log.tar.gz)
 

### Anything else?

Even the collection was created on 2.1, it was not able to load it twice with pymivlus 2.0.2

**Comment by XuanYang-cn** [comment]
/unassign
/assign @yanliang567 
Please help varify
