### ISSUE TITLE
[Bug]: reduce search result  occurs core dump

### ISSUE THREAD

**Issue by jaime0815** [milvus-io/milvus#17679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
{"log":"panic: runtime error: invalid memory address or nil pointer dereference\n","stream":"stderr","time":"2022-06-20T16:21:02.195207312Z"}
{"log":"[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x22430b9]\n","stream":"stderr","time":"2022-06-20T16:21:02.195223524Z"}
{"log":"\n","stream":"stderr","time":"2022-06-20T16:21:02.195225428Z"}
{"log":"goroutine 180389 [running]:\n","stream":"stderr","time":"2022-06-20T16:21:02.19522731Z"}
{"log":"github.com/milvus-io/milvus/internal/querynode.reduceSearchResultsAndFillData(0xc00d8ca940, 0xc004609110, 0xd, 0xd, 0xd, 0xc00f6a7708, 0x1, 0x2, 0xc00f6a77f0, 0x1, ...)\n","stream":"stderr","time":"2022-06-20T16:21:02.195229453Z"}
{"log":"\u0009/go/src/github.com/milvus-io/milvus/internal/querynode/reduce.go:95 +0xb9\n","stream":"stderr","time":"2022-06-20T16:21:02.195231867Z"}
{"log":"github.com/milvus-io/milvus/internal/querynode.(*searchTask).reduceResults(0xc0143b7b80, 0xc01395ff68, 0xc004609110, 0xd, 0xd, 0x0, 0x0)\n","stream":"stderr","time":"2022-06-20T16:21:02.195234536Z"}
{"log":"\u0009/go/src/github.com/milvus-io/milvus/internal/querynode/task_search.go:207 +0x399\n","stream":"stderr","time":"2022-06-20T16:21:02.195236115Z"}
{"log":"github.com/milvus-io/milvus/internal/querynode.(*searchTask).searchOnStreaming(0xc0143b7b80, 0x0, 0x0)\n","stream":"stderr","time":"2022-06-20T16:21:02.195237733Z"}
{"log":"\u0009/go/src/github.com/milvus-io/milvus/internal/querynode/task_search.go:118 +0x7ce\n","stream":"stderr","time":"2022-06-20T16:21:02.195239383Z"}
{"log":"github.com/milvus-io/milvus/internal/querynode.(*searchTask).Execute(0xc0143b7b80, 0x43410d0, 0xc000026140, 0x0, 0x0)\n","stream":"stderr","time":"2022-06-20T16:21:02.195242524Z"}
{"log":"\u0009/go/src/github.com/milvus-io/milvus/internal/querynode/task_search.go:157 +0xac\n","stream":"stderr","time":"2022-06-20T16:21:02.195244611Z"}
{"log":"github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).processReadTask(0xc0006e8800, 0x436d1d0, 0xc0143b7b80)\n","stream":"stderr","time":"2022-06-20T16:21:02.195251745Z"}
{"log":"\u0009/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:308 +0xdb\n","stream":"stderr","time":"2022-06-20T16:21:02.1952537Z"}
{"log":"github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).executeReadTasks.func1(0xc002c3f640, 0xc0006e8800, 0x436d1d0, 0xc0143b7b80)\n","stream":"stderr","time":"2022-06-20T16:21:02.195255511Z"}
{"log":"\u0009/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:261 +0x6b\n","stream":"stderr","time":"2022-06-20T16:21:02.195257464Z"}
{"log":"created by github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).executeReadTasks\n","stream":"stderr","time":"2022-06-20T16:21:02.19526051Z"}
{"log":"\u0009/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:259 +0x2b6\n","stream":"stderr","time":"2022-06-20T16:21:02.195262299Z"}
```

**Comment by czs007** [comment]
@bigsheeper  is fixing

**Comment by bigsheeper** [comment]
fix should be fixed @jaime0815
