### ISSUE TITLE
[Bug]: [memory] Flushing hangs and search failed if apply memory stress on standalone during insert

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#17697]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. Deploy standalone and limit memory 6Gi
2. Apply memory stress on standalone during insert, and insert get the memory exception:
```
stressors:
    memory:
      workers: 4
      size: 6Gi
  duration: 5m
```
```
[2022-06-22 10:24:28,472 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=IO error: While appending to file: /var/lib/milvus/rdb_data/000008.sst: Cannot allocate memory)> (api_request.py:36)
```
3. The standalone pod isn't OOMKilled, because stress-ng processes are OOMkilled. Try to flush data by `collection.num_entities` and hangs, and some server error logs are found:
```
39857 [2022/06/22 02:46:34.638 +00:00] [WARN] [timeticksync.go:328] ["SendTimeTickToChannel fail"] [error="IO error: While appending to file: /var/lib/milvus/rdb_data/000008.sst:       Cannot allocate memory"]
39858 [2022/06/22 02:46:34.638 +00:00] [ERROR] [dml_channels.go:113] ["Broadcast failed"] [error="IO error: While appending to file: /var/lib/milvus/rdb_data/000008.sst: Cannot a      llocate memory"] [chanName=milvus-chaos-rootcoord-dml_0] [stack="github.com/milvus-io/milvus/internal/rootcoord.(*dmlChannels).broadcast\n\t/go/src/github.com/milvus-io/mil      vus/internal/rootcoord/dml_channels.go:113\ngithub.com/milvus-io/milvus/internal/rootcoord.(*timetickSync).sendTimeTickToChannel\n\t/go/src/github.com/milvus-io/milvus/inte      rnal/rootcoord/timeticksync.go:366\ngithub.com/milvus-io/milvus/internal/rootcoord.(*timetickSync).startWatch.func1\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoor      d/timeticksync.go:327"]
39859 [2022/06/22 02:46:34.638 +00:00] [WARN] [timeticksync.go:328] ["SendTimeTickToChannel fail"] [error="IO error: While appending to file: /var/lib/milvus/rdb_data/000008.sst:       Cannot allocate memory"]
```
4. Try to load collection and search but failed
```
[2022-06-22 10:45:01,034 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.08863179376716168, 0.032708420928775496, 0.13689518294854128, 0.09302608782009897, 0.024897267693386484, 0.1303349446796926, 0.07608595949593945, 0.10019245729672271, 0.0418417386212381, 0.10393745344892207, 0.13647650988503673, 0.030232635132069915, 0.03778546127370658, 0.029335601673712988, 0......, kwargs: {} (api_request.py:55)
[2022-06-22 10:45:21,071 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 44, in handler
    return func(self, *args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 87, in handler
    raise e
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 75, in handler
    return func(*args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 449, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 87, in handler
    raise e
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 75, in handler
    return func(*args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 411, in _execute_search_requests
    raise pre_err
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 399, in _execute_search_requests
    response = ft.result()
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655865921.065783000","description":"Error received from peer ipv4:10.98.0.5:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nausicca/projects/milvus/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
    res = func(*args, **kwargs)
  File "/Users/nausicca/projects/milvus/tests/python_client/utils/api_request.py", line 56, in api_request
    return func(*arg, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 689, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 52, in handler
    raise MilvusException(Status.UNEXPECTED_ERROR, str(e))
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655865921.065783000","description":"Error received from peer ipv4:10.98.0.5:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>)>
 (api_request.py:35)
[2022-06-22 10:45:21,071 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655865921.065783000","description":"Error received from peer ipv4:10.98.0.5:19530","file":"src/core/lib...... (api_request.py:36)
FAILED
```
The error log about search of standalone server
```
37944 [2022/06/22 02:45:01.073 +00:00] [ERROR] [shard_cluster.go:747] ["stream operation failed: deadline exceed"] [stack="github.com/milvus-io/milvus/internal/querynode.(*ShardC      luster).Search\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/shard_cluster.go:747\ngithub.com/milvus-io/milvus/internal/querynode.(*QueryNode).Search\n\t/go/src      /github.com/milvus-io/milvus/internal/querynode/impl.go:547\ngithub.com/milvus-io/milvus/internal/distributed/querynode.(*Server).Search\n\t/go/src/github.com/milvus-io/mil      vus/internal/distributed/querynode/service.go:298\ngithub.com/milvus-io/milvus/internal/proto/querypb._QueryNode_Search_Handler.func1\n\t/go/src/github.com/milvus-io/milvus      /internal/proto/querypb/query_coord.pb.go:4009\ngithub.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc      -ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38\ngithub.com/milvus-io/milvus/internal/proto/querypb._QueryNode_Search_Handler\n\t/go/src/      github.com/milvus-io/milvus/internal/proto/querypb/query_coord.pb.go:4011\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/se      rver.go:1286\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1609\ngoogle.golang.org/grpc.(*Server).serveStreams.func      1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:934"]
```

**Server logs:** 
[standalone.log](https://github.com/milvus-io/milvus/files/8954066/standalone.log)
 
**Pod memory monitoring：**
![image](https://user-images.githubusercontent.com/27288593/174934344-126bdb32-fd07-4e5f-92be-b6e2af8bf820.png)

### Steps To Reproduce

```markdown
def test_chaos_memory_stress_insert_standalone(self, host):
        """
        target:
        method:
        expected:
        """
        connections.connect("default", host=host, port=19530)
        collection_w = ApiCollectionWrapper()
        c_name = "stress_standalone"
        collection_w.init_collection(name=c_name,
                                     schema=cf.gen_default_collection_schema())

        nb = 1000

        def do_insert():
            """ do search """
            df = cf.gen_default_dataframe_data(nb=nb)
            res, is_succ = collection_w.insert(df)
            assert res.insert_count == nb
            return res, is_succ

        def loop_insert():
            """ continuously search """
            for i in range(150):
                do_insert()

        # t_insert = threading.Thread(target=loop_insert, args=())
        # t_insert.start()

        chaos_config = gen_experiment_config("./chaos_objects/memory_stress/chaos_standalone_memory_stress.yaml")

        # Update config
        log.debug(chaos_config)
        chaos_res = CusResource(kind=chaos_config['kind'],
                                group=constants.CHAOS_GROUP,
                                version=constants.CHAOS_VERSION,
                                namespace=constants.CHAOS_NAMESPACE)
        # chaos_res.create(chaos_config)
        # chaos_start = time.time()
        # log.debug("chaos injected")

        # t_insert.join()

        # log.debug(collection_w.num_entities)
        collection_w.load()
        search_res, _ = collection_w.search(cf.gen_vectors(ct.default_nq, ct.default_dim),
                                            ct.default_float_vec_field_name,
                                            ct.default_search_params, ct.default_limit)
```

**Comment by yanliang567** [comment]
postpone to 2.1 GA

**Comment by longjiquan** [comment]
What's the expected behavior of Milvus under memory stress? @ThreadDao 
Both the `flush` and the `search` rely on the timetick to be done. Our timetick based on mq, here for standalone implemented by `rocksmq`, we can't update the timetick due to the memory stress. So `flush` and `search` hang.
BTW:
1, It seems there's no need to call `flush` since we are inserting entities continousingly, we'll remove the dependency between `num_entities` and `flush`;
2, You can try `search` with `Eventually` consistency, which is not affected by the timetick and so should be executed sucussfully;

**Comment by ThreadDao** [comment]
> What's the expected behavior of Milvus under memory stress? @ThreadDao , I think this issue was normal under our system architecture. Both the `flush` and the `search` rely on the timetick to be done. Our timetick based on mq, here for standalone implemented by `rocksmq`, we can't update the timetick due to the memory stress. So `flush` and `search` hang. BTW: 1, It seems there's no need to call `flush` since we are inserting entities continousingly, we'll remove the dependency between `num_entities` and `flush` later; 2, You can try `search` with `Eventually` consistency, which is not affected by the timetick and so should be executed sucussfully;

Expected behavior: After removing memory chaos, standalone is available, including flush, and load search..

**Comment by longjiquan** [comment]
It seems that rocksdb didn't recover after memory chaos. Can we wait to do `flush` and `search` until we can insert into the collection? @ThreadDao

**Comment by ThreadDao** [comment]
Image ``:
After standalone restarted because of OOM, the growing data inserted before restarted is gone.

Client log: [standalone-client.log](https://github.com/milvus-io/milvus/files/9038531/standalone-client.log)

Server log: 
[standalone.log](https://github.com/milvus-io/milvus/files/9038533/standalone.log)

collectionId: 
```
2328 [2022/07/04 09:45:42.676 +00:00] [INFO] [task.go:513] ["send insert request to virtual channels"] [collection=stress_standalone] [partition=_default] [collection_id=434353602507571201] [partition_id=434353602507571202] [virtual_channels="[milvus-chaos-rootcoord-dml_4_43     4353602507571201v0,milvus-chaos-rootcoord-dml_5_434353602507571201v1]"] [task_id=434353650759368710]
```
data: 
[milvus-chaos-files_insert_log.zip](https://github.com/milvus-io/milvus/files/9038560/milvus-chaos-files_insert_log.zip)

**Comment by longjiquan** [comment]
Do we have the log before pod restarts? @ThreadDao

**Comment by longjiquan** [comment]
When you insert entities into collection under memory stress, in fact it's not accepted by the Milvus. We didn't expose these API ago. Fortuanately, you can also check if insert is sucessful via:
```python
len(insert_response._mr._raw.err_index)
```

**Comment by longjiquan** [comment]
`num_entities` only count the inserted entities after memory stress, which can be found in restarted `standalone.log`.

**Comment by ThreadDao** [comment]
1. Class `MutationResult` has no properties `succ_count` and `err_count`
2. `succ_count + err_count != insert_count`
```
(api_response) : (insert count: 1000, delete count: 0, upsert count: 0, timestamp: 434370632467349505, succ_count: 0, err_count:0)  (api_request.py:27)
```
3. Flush hangs after removing memory chaos and standalone back to running

**Comment by longjiquan** [comment]
@ThreadDao Sorry for the late reply.
1. Fixed by https://github.com/milvus-io/pymilvus/pull/1062;
2. I'll fix this soon;
3. Working on it;

**Comment by ThreadDao** [comment]
@longjiquan  The log you want before the standalone restart
Image: `2.1.0-20220713-9059dba3`

[client.log](https://github.com/milvus-io/milvus/files/9103800/client.log)

[standalone_pre.log](https://github.com/milvus-io/milvus/files/9103803/standalone_pre.log)

[standalone.log](https://github.com/milvus-io/milvus/files/9103821/standalone.log)

**Comment by longjiquan** [comment]
```
[2022/07/13 15:24:49.000 +00:00] [INFO] [datanode/flow_graph_dmstream_input_node.go:49] ["datanode AsConsumer"] ["physical channel"=milvus-chaos-rootcoord-dml_14] [subName=milvus-chaos-dataNode-14-434562863600500737] ["collection ID"=434562863600500737]
[2022/07/13 15:24:49.000 +00:00] [INFO] [datanode/flow_graph_dmstream_input_node.go:54] ["datanode begin to seek"] ["physical channel"=milvus-chaos-rootcoord-dml_14] ["collection ID"=434562863600500737]
[2022/07/13 15:24:49.000 +00:00] [INFO] [msgstream/mq_msgstream.go:883] ["MsgStream begin to seek start msg: "] [channel=milvus-chaos-rootcoord-dml_14] [MessageID={}]
[2022/07/13 15:24:49.000 +00:00] [WARN] [server/rocksmq_impl.go:762] ["RocksMQ: trying to seek to no exist position, reset current id"] [topic=milvus-chaos-rootcoord-dml_14] [group=milvus-chaos-dataNode-14-434562863600500737] [msgId=434551694038664728]
[2022/07/13 15:24:49.000 +00:00] [DEBUG] [server/rocksmq_impl.go:799] ["successfully seek"] [topic=milvus-chaos-rootcoord-dml_14] [group=milvus-chaos-dataNode-14-434562863600500737] [msgId=434551694038664728]
```

**Comment by longjiquan** [comment]
After standalone recovered from memory stress, datanode tried to seek to a position of rmq, but the related message id is not found in rocksdb.

**Comment by longjiquan** [comment]
![image](https://user-images.githubusercontent.com/31589260/178933811-66d58450-a3c0-419b-b842-a14ee2ed9f49.png)

**Comment by longjiquan** [comment]
![image](https://user-images.githubusercontent.com/31589260/178942628-529477cb-1702-4184-8686-9dc44a121cc2.png)

**Comment by longjiquan** [comment]
![image](https://user-images.githubusercontent.com/31589260/178942876-c0b86675-3ae5-4210-b7bd-6aedbc530afb.png)

**Comment by longjiquan** [comment]
Milvus standalone use rocksdb as message queue. In this case, the data path of rocksdb didn't mount outside, so after standalone restarted, all data in rocksmq has lost, which is inconsistent with meta stored in etcd.

**Comment by yanliang567** [comment]
I think we shall 
1. create an issue to milvus operator, to make sure data in rocksmq is persisted @ThreadDao 
2. design a way to notify users that some data could be lost, instead of hang the system/collection @longjiquan any ideas?

**Comment by longjiquan** [comment]
@ThreadDao @yanliang567 Yeah, I agree we need some solutions when system meets these issues. But now under current mechanism of Milvus, it's hard to say whether data is lost or there is no data at all in this case.

**Comment by xiaofan-luan** [comment]
> @ThreadDao @yanliang567 Yeah, I agree we need some solutions when system meets these issues. But now under current mechanism of Milvus, it's hard to say whether data is lost or there is no data at all in this case.

Agree, we should never change our persistent directory, the database itself can only hang and wait for human.
