### ISSUE TITLE
[Bug]: Create index timeout after all kinds of pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#17733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220623-216e2f80
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus==2.1.0.dev83
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Create index timeout when running `test_e2e.py`
```
12:08:06  [2022-06-23 04:07:19 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['float_vector', {'index_type': 'IVF_SQ8', 'params': {'nlist': 64}, 'metric_type': 'L2'}], kwargs: {'name': 'test_sMLkyshB', 'timeout': 40, 'index_name': '_default_idx'} (api_request.py:55)
12:08:06  [2022-06-23 04:07:59 - ERROR - pymilvus.decorators]: RPC error: [wait_for_creating_index], <MilvusException: (code=1, message=CreateIndex Timeout)>, <Time:{'RPC start': '2022-06-23 04:07:19.260374', 'RPC error': '2022-06-23 04:07:59.705880'}> (decorators.py:78)
12:08:06  [2022-06-23 04:07:59 - ERROR - pymilvus.decorators]: RPC error: [create_index], <MilvusException: (code=1, message=CreateIndex Timeout)>, <Time:{'RPC start': '2022-06-23 04:07:19.216380', 'RPC error': '2022-06-23 04:07:59.706429'}> (decorators.py:78)
12:08:06  [2022-06-23 04:07:59 - ERROR - ci_test]: Traceback (most recent call last):
12:08:06    File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
12:08:06      res = func(*args, **kwargs)
12:08:06    File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 56, in api_request
12:08:06      return func(*arg, **kwargs)
12:08:06    File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 1078, in create_index
12:08:06      timeout=timeout, **kwargs)
12:08:06    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 61, in handler
12:08:06      raise e
12:08:06    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 44, in handler
12:08:06      return func(self, *args, **kwargs)
12:08:06    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 79, in handler
12:08:06      raise e
12:08:06    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 75, in handler
12:08:06      return func(*args, **kwargs)
12:08:06    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 604, in create_index
12:08:06      timeout=timeout)
12:08:06    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 61, in handler
12:08:06      raise e
12:08:06    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 44, in handler
12:08:06      return func(self, *args, **kwargs)
12:08:06    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 79, in handler
12:08:06      raise e
12:08:06    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 75, in handler
12:08:06      return func(*args, **kwargs)
12:08:06    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 679, in wait_for_creating_index
12:08:06      raise MilvusException(1, "CreateIndex Timeout")
12:08:06  pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=CreateIndex Timeout)>
12:08:06   (api_request.py:35)
12:08:06  [2022-06-23 04:07:59 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=CreateIndex Timeout)> (api_request.py:36)
```

### Expected Behavior

all test cases passed

### Steps To Reproduce

```markdown
see http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/7073/pipeline
```

### Milvus Log

failed job: http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/7073/pipeline
log: [artifacts-querynode-pod-kill-7073-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/8963899/artifacts-querynode-pod-kill-7073-server-logs.tar.gz)

**Comment by zhuwenxing** [comment]
This issue happened in all pod kill chaos tests, and it works well in `master-20220622-f4c6a673`.

So it would be the PR merged in today that caused this problem, maybe https://github.com/milvus-io/milvus/pull/17717 ?

**Comment by zhuwenxing** [comment]
/assign @xiaocai2333 

Please help to take a look!

**Comment by zhuwenxing** [comment]
Not reproduced in `master-20220623-e8f53af7`
