### ISSUE TITLE
[Bug]: [kafka] Drop collection failed for timeout

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#17750]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: latest 
- Deployment mode(standalone or cluster):cluster, kafka
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.1.0.dev83
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Drop collection failed for timeout

```
[2022-06-23T19:56:37.336Z] [2022-06-23 19:01:26 - DEBUG - ci_test]: (api_request)  : [Collection.drop] args: [], kwargs: {'timeout': 20} (api_request.py:55)

[2022-06-23T19:56:37.336Z] [2022-06-23 19:01:46 - ERROR - pymilvus.decorators]: grpc RpcError: [drop_collection], <_MultiThreadedRendezvous: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded>, <Time:{'RPC start': '2022-06-23 19:01:26.479657', 'gRPC error': '2022-06-23 19:01:46.481086'}> (decorators.py:86)

[2022-06-23T19:56:37.336Z] [2022-06-23 19:01:46 - ERROR - ci_test]: Traceback (most recent call last):

[2022-06-23T19:56:37.336Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 44, in handler

[2022-06-23T19:56:37.336Z]     return func(self, *args, **kwargs)

[2022-06-23T19:56:37.336Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 87, in handler

[2022-06-23T19:56:37.336Z]     raise e

[2022-06-23T19:56:37.336Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 75, in handler

[2022-06-23T19:56:37.336Z]     return func(*args, **kwargs)

[2022-06-23T19:56:37.336Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 202, in drop_collection

[2022-06-23T19:56:37.336Z]     status = rf.result()

[2022-06-23T19:56:37.336Z]   File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 744, in result

[2022-06-23T19:56:37.336Z]     raise self

[2022-06-23T19:56:37.336Z] grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:

[2022-06-23T19:56:37.336Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2022-06-23T19:56:37.336Z] 	details = "Deadline Exceeded"

[2022-06-23T19:56:37.336Z] 	debug_error_string = "{"created":"@1656010906.480626430","description":"Error received from peer ipv4:10.201.215.29:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Deadline Exceeded","grpc_status":4}"

[2022-06-23T19:56:37.336Z] >

[2022-06-23T19:56:37.336Z] 

[2022-06-23T19:56:37.336Z] During handling of the above exception, another exception occurred:

[2022-06-23T19:56:37.336Z] 

[2022-06-23T19:56:37.336Z] Traceback (most recent call last):

[2022-06-23T19:56:37.336Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper

[2022-06-23T19:56:37.336Z]     res = func(*args, **kwargs)

[2022-06-23T19:56:37.336Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 56, in api_request

[2022-06-23T19:56:37.336Z]     return func(*arg, **kwargs)

[2022-06-23T19:56:37.336Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 435, in drop

[2022-06-23T19:56:37.336Z]     conn.drop_collection(self._name, timeout=timeout, **kwargs)

[2022-06-23T19:56:37.336Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 52, in handler

[2022-06-23T19:56:37.336Z]     raise MilvusException(Status.UNEXPECTED_ERROR, str(e))

[2022-06-23T19:56:37.336Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:

[2022-06-23T19:56:37.336Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2022-06-23T19:56:37.336Z] 	details = "Deadline Exceeded"

[2022-06-23T19:56:37.336Z] 	debug_error_string = "{"created":"@1656010906.480626430","description":"Error received from peer ipv4:10.201.215.29:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Deadline Exceeded","grpc_status":4}"

[2022-06-23T19:56:37.336Z] >)>

[2022-06-23T19:56:37.336Z]  (api_request.py:35)

[2022-06-23T19:56:37.336Z] [2022-06-23 19:01:46 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:

[2022-06-23T19:56:37.336Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2022-06-23T19:56:37.336Z] 	details = "Deadline Exceeded"

[2022-06-23T19:56:37.336Z] 	debug_error_string = "{"created":"@1656010906.480626430","description":"Error received from peer ipv4:10.201.215.29:19530","file":"src/core...... (api_request.py:36)
```

### Expected Behavior

No deadline error

### Steps To Reproduce

```markdown
Running nightly:
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/612/pipeline/145
```

### Milvus Log

1. Milvus logs:
[artifacts-milvus-distributed-kafka-master-612-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/612/artifact/artifacts-milvus-distributed-kafka-master-612-pymilvus-e2e-logs.tar.gz)

2. collection name: collection_H0z6IlBT

**Comment by binbinlv** [comment]
Similar issue appears again in the following latest nightly:
https://ci.milvus.io:18080/jenkins/blue/rest/organizations/jenkins/pipelines/milvus-nightly-ci/branches/master/runs/640/nodes/64/steps/178/log/?start=0

1. milvus log:
[artifacts-milvus-distributed-kafka-master-640-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/640/artifact/artifacts-milvus-distributed-kafka-master-640-pymilvus-e2e-logs.tar.gz)

2. collection name: collection_lyAwVjvN
3. Failed time:
[2022-07-07T19:01:18.049Z] [gw5] [  5%] FAILED testcases/test_collection.py::TestCollectionOperation::test_collection_after_drop

**Comment by binbinlv** [comment]
Similar issue appears again in the following latest nightly:
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/665/pipeline

1. milvus log:
[artifacts-milvus-distributed-kafka-master-665-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/665/artifact/artifacts-milvus-distributed-kafka-master-665-pymilvus-e2e-logs.tar.gz)
2. collection name: collection_U9mrHkwG
3. Failed time:
[2022-07-20T15:04:17.180Z] [gw0] [  4%] FAILED testcases/test_collection.py::TestCollectionOperation::test_collection_after_drop

**Comment by binbinlv** [comment]
Similar issue appears again in the following latest nightly:
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/676/pipeline

1. milvus log: [artifacts-milvus-distributed-kafka-master-676-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/676/artifact/artifacts-milvus-distributed-kafka-master-676-pymilvus-e2e-logs.tar.gz)
2. collection name: collection_fK0kt7bT
3. Failed time: [2022-07-25T19:02:23.118Z] [gw0] [  5%] FAILED testcases/test_collection.py::TestCollectionOperation::test_collection_after_drop

**Comment by binbinlv** [comment]
Same issue appears again in the following latest nightly:
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/25/pipeline

1. milvus log: [artifacts-milvus-distributed-kafka-nightly-25-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/25/artifact/artifacts-milvus-distributed-kafka-nightly-25-pymilvus-e2e-logs.tar.gz)
2. collection name: collection_cDgpBVN5
3. Failed time:
[2022-08-08T19:02:05.945Z] [gw0] [  5%] FAILED testcases/test_collection.py::TestCollectionOperation::test_collection_after_drop

**Comment by binbinlv** [comment]
Same issue appears again in the following latest 2.1.* nightly:

https://jenkins.milvus.io:18080/blue/organizations/jenkins/qa%2Fmilvus-release-nightly/detail/milvus-release-nightly/53/pipeline/177

1. milvus log:
[milvus-distributed-kafka-53-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/qa/job/milvus-release-nightly/53/artifact/milvus-distributed-kafka-53-pymilvus-e2e-logs.tar.gz)

2. collection name:
collection_iE2qHX8J

3. Failed timeline:
[2022-08-21T23:20:52.893Z] [gw5] [  4%] FAILED testcases/test_collection.py::TestCollectionOperation::test_collection_after_drop

**Comment by NicoYuan1986** [comment]
Same issue appears again in the following latest master nightly:
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/69/pipeline/155

1. milvus log: [artifacts-milvus-distributed-kafka-nightly-69-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/69/artifact/artifacts-milvus-distributed-kafka-nightly-69-pymilvus-e2e-logs.tar.gz)
2. collection name: collection_p0M8LZ9I
3. Failed timeline: [2022-08-30T19:01:55.619Z] [gw1] [  5%] FAILED testcases/test_collection.py::TestCollectionOperation::test_collection_after_drop

**Comment by NicoYuan1986** [comment]
Same issue appears again in the following latest 2.1.* nightly:
https://jenkins.milvus.io:18080/blue/organizations/jenkins/qa%2Fmilvus-release-nightly/detail/milvus-release-nightly/74/pipeline/177
1. milvus log: [milvus-distributed-kafka-74-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/qa/job/milvus-release-nightly/74/artifact/milvus-distributed-kafka-74-pymilvus-e2e-logs.tar.gz)
2. collection name: collection_grse0k0G
3. Failed timeline: [2022-09-01T20:23:01.911Z] [gw5] [  3%] FAILED testcases/test_collection.py::TestCollectionOperation::test_collection_after_drop

**Comment by NicoYuan1986** [comment]
Same issue appears again in the following  2.1.* branch:
https://jenkins.milvus.io:18080/blue/organizations/jenkins/qa%2Fmilvus-release-nightly/detail/milvus-release-nightly/84/pipeline/193

1. milvus log: [milvus-distributed-kafka-84-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/qa/job/milvus-release-nightly/84/artifact/milvus-distributed-kafka-84-pymilvus-e2e-logs.tar.gz)
2. collection name: collection_bNn4gA3F
3. Failed timeline: [2022-09-06T20:25:31.720Z] [gw5] [ 6%] FAILED testcases/test_collection.py::TestCollectionOperation::test_collection_after_drop
4. error message:
```
2022-09-07T04:20:19.20463164+08:00 stderr F panic: new session error, maybe can not connect to etcd
2022-09-07T04:20:19.204650424+08:00 stderr F
2022-09-07T04:20:19.204656778+08:00 stderr F goroutine 31 [running]:
2022-09-07T04:20:19.204660957+08:00 stderr F github.com/milvus-io/milvus/internal/distributed/datanode.(*Server).init(0xc000cdd5e0, 0x8bdf3e, 0xc000f0c498)
2022-09-07T04:20:19.204664617+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/distributed/datanode/service.go:252 +0x204b
2022-09-07T04:20:19.204668057+08:00 stderr F github.com/milvus-io/milvus/internal/distributed/datanode.(*Server).Run(0xc000cdd5e0, 0x0, 0x0)
2022-09-07T04:20:19.204678105+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/distributed/datanode/service.go:166 +0x2f
2022-09-07T04:20:19.204682733+08:00 stderr F github.com/milvus-io/milvus/cmd/components.(*DataNode).Run(0xc0006ba990, 0xffffffffffffffff, 0x8)
2022-09-07T04:20:19.20468665+08:00 stderr F     /go/src/github.com/milvus-io/milvus/cmd/components/data_node.go:50 +0x33
2022-09-07T04:20:19.204698782+08:00 stderr F github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runDataNode.func1(0x0, 0x0, 0x40bf500, 0x43b0030, 0xc000ce6d00, 0xc000cf40a8, 0xc000f0c3e0, 0xc000f0c490)
2022-09-07T04:20:19.204703339+08:00 stderr F    /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:283 +0x165
2022-09-07T04:20:19.204707113+08:00 stderr F created by github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runDataNode
2022-09-07T04:20:19.204710744+08:00 stderr F    /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:264 +0xda
```

**Comment by NicoYuan1986** [comment]
Same issue appears again in the following 2.1.* branch:
https://jenkins.milvus.io:18080/blue/organizations/jenkins/qa%2Fmilvus-release-nightly/detail/milvus-release-nightly/103/pipeline/158
1. milvus log: [milvus-distributed-kafka-103-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/qa/job/milvus-release-nightly/103/artifact/milvus-distributed-kafka-103-pymilvus-e2e-logs.tar.gz)
2. collection name: collection_3Hf6Urea
3. Failed timeline: [2022-09-15T20:24:58.794Z] [gw5] [  5%] FAILED testcases/test_collection.py::TestCollectionOperation::test_collection_after_drop
4. error message:
```
[2022-09-15T21:25:10.907Z] [2022-09-15 20:24:58 - ERROR - pymilvus.decorators]: RPC error: [drop_collection], <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
[2022-09-15T21:25:10.907Z] 	status = StatusCode.DEADLINE_EXCEEDED
[2022-09-15T21:25:10.907Z] 	details = "Deadline Exceeded"
[2022-09-15T21:25:10.907Z] 	debug_error_string = "UNKNOWN:Deadline Exceeded {grpc_status:4, created_time:"2022-09-15T20:24:58.37553633+00:00"}"
[2022-09-15T21:25:10.907Z] >)>, <Time:{'RPC start': '2022-09-15 20:24:38.375204', 'RPC error': '2022-09-15 20:24:58.376076'}> (decorators.py:95)
[2022-09-15T21:25:10.907Z] [2022-09-15 20:24:58 - ERROR - ci_test]: Traceback (most recent call last):
[2022-09-15T21:25:10.907Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 48, in handler
[2022-09-15T21:25:10.907Z]     return func(self, *args, **kwargs)
[2022-09-15T21:25:10.907Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 205, in drop_collection
[2022-09-15T21:25:10.907Z]     status = rf.result()
[2022-09-15T21:25:10.907Z]   File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 744, in result
[2022-09-15T21:25:10.907Z]     raise self
[2022-09-15T21:25:10.907Z] grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
[2022-09-15T21:25:10.907Z] 	status = StatusCode.DEADLINE_EXCEEDED
[2022-09-15T21:25:10.907Z] 	details = "Deadline Exceeded"
[2022-09-15T21:25:10.907Z] 	debug_error_string = "UNKNOWN:Deadline Exceeded {grpc_status:4, created_time:"2022-09-15T20:24:58.37553633+00:00"}"
[2022-09-15T21:25:10.907Z] >
[2022-09-15T21:25:10.907Z] 
[2022-09-15T21:25:10.907Z] During handling of the above exception, another exception occurred:
[2022-09-15T21:25:10.907Z] 
[2022-09-15T21:25:10.907Z] Traceback (most recent call last):
[2022-09-15T21:25:10.907Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
[2022-09-15T21:25:10.907Z]     res = func(*args, **kwargs)
[2022-09-15T21:25:10.907Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 56, in api_request
[2022-09-15T21:25:10.907Z]     return func(*arg, **kwargs)
[2022-09-15T21:25:10.907Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 435, in drop
[2022-09-15T21:25:10.907Z]     conn.drop_collection(self._name, timeout=timeout, **kwargs)
[2022-09-15T21:25:10.907Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 96, in handler
[2022-09-15T21:25:10.907Z]     raise e
[2022-09-15T21:25:10.907Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 92, in handler
[2022-09-15T21:25:10.907Z]     return func(*args, **kwargs)
[2022-09-15T21:25:10.907Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 56, in handler
[2022-09-15T21:25:10.907Z]     raise MilvusException(Status.UNEXPECTED_ERROR, str(e))
[2022-09-15T21:25:10.907Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
[2022-09-15T21:25:10.907Z] 	status = StatusCode.DEADLINE_EXCEEDED
[2022-09-15T21:25:10.907Z] 	details = "Deadline Exceeded"
[2022-09-15T21:25:10.907Z] 	debug_error_string = "UNKNOWN:Deadline Exceeded {grpc_status:4, created_time:"2022-09-15T20:24:58.37553633+00:00"}"
[2022-09-15T21:25:10.907Z] >)>
[2022-09-15T21:25:10.907Z]  (api_request.py:35)
[2022-09-15T21:25:10.907Z] [2022-09-15 20:24:58 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
[2022-09-15T21:25:10.907Z] 	status = StatusCode.DEADLINE_EXCEEDED
[2022-09-15T21:25:10.907Z] 	details = "Deadline Exceeded"
[2022-09-15T21:25:10.907Z] 	debug_error_string = "UNKNOWN:Deadline Exceeded {grpc_status:4, created_time:"2022-09-15T20:24:58.37553633+00:00"}"
[2022-09-15T21:25:10.907Z] >)> (api_request.py:36)
```

**Comment by NicoYuan1986** [comment]
Same issue appears again in the following 2.1.* branch:
https://jenkins.milvus.io:18080/blue/organizations/jenkins/qa%2Fmilvus-release-nightly/detail/milvus-release-nightly/110/pipeline/177
1. milvus log: [milvus-distributed-kafka-110-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/qa/job/milvus-release-nightly/110/artifact/milvus-distributed-kafka-110-pymilvus-e2e-logs.tar.gz)
2. collection name: collection_ffKHaiav
3. Failed timeline: [2022-09-18T23:24:23.965Z] [gw5] [  5%] FAILED testcases/test_collection.py::TestCollectionOperation::test_collection_after_drop
4. error message:
```
[2022-09-19T00:17:07.123Z] [2022-09-18 23:24:03 - ERROR - pymilvus.decorators]: RPC error: [drop_collection], <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
[2022-09-19T00:17:07.123Z] 	status = StatusCode.DEADLINE_EXCEEDED
[2022-09-19T00:17:07.123Z] 	details = "Deadline Exceeded"
[2022-09-19T00:17:07.123Z] 	debug_error_string = "UNKNOWN:Deadline Exceeded {grpc_status:4, created_time:"2022-09-18T23:24:03.903742266+00:00"}"
[2022-09-19T00:17:07.123Z] >)>, <Time:{'RPC start': '2022-09-18 23:23:43.903654', 'RPC error': '2022-09-18 23:24:03.904324'}> (decorators.py:95)
[2022-09-19T00:17:07.123Z] [2022-09-18 23:24:03 - ERROR - ci_test]: Traceback (most recent call last):
[2022-09-19T00:17:07.123Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 48, in handler
[2022-09-19T00:17:07.123Z]     return func(self, *args, **kwargs)
[2022-09-19T00:17:07.123Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 205, in drop_collection
[2022-09-19T00:17:07.123Z]     status = rf.result()
[2022-09-19T00:17:07.123Z]   File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 744, in result
[2022-09-19T00:17:07.123Z]     raise self
[2022-09-19T00:17:07.123Z] grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
[2022-09-19T00:17:07.123Z] 	status = StatusCode.DEADLINE_EXCEEDED
[2022-09-19T00:17:07.123Z] 	details = "Deadline Exceeded"
[2022-09-19T00:17:07.123Z] 	debug_error_string = "UNKNOWN:Deadline Exceeded {grpc_status:4, created_time:"2022-09-18T23:24:03.903742266+00:00"}"
[2022-09-19T00:17:07.123Z] >
[2022-09-19T00:17:07.123Z] 
[2022-09-19T00:17:07.123Z] During handling of the above exception, another exception occurred:
[2022-09-19T00:17:07.123Z] 
[2022-09-19T00:17:07.123Z] Traceback (most recent call last):
[2022-09-19T00:17:07.123Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
[2022-09-19T00:17:07.123Z]     res = func(*args, **kwargs)
[2022-09-19T00:17:07.123Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 56, in api_request
[2022-09-19T00:17:07.123Z]     return func(*arg, **kwargs)
[2022-09-19T00:17:07.123Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 435, in drop
[2022-09-19T00:17:07.123Z]     conn.drop_collection(self._name, timeout=timeout, **kwargs)
[2022-09-19T00:17:07.123Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 96, in handler
[2022-09-19T00:17:07.123Z]     raise e
[2022-09-19T00:17:07.123Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 92, in handler
[2022-09-19T00:17:07.123Z]     return func(*args, **kwargs)
[2022-09-19T00:17:07.123Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 56, in handler
[2022-09-19T00:17:07.123Z]     raise MilvusException(Status.UNEXPECTED_ERROR, str(e))
[2022-09-19T00:17:07.123Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
[2022-09-19T00:17:07.123Z] 	status = StatusCode.DEADLINE_EXCEEDED
[2022-09-19T00:17:07.123Z] 	details = "Deadline Exceeded"
[2022-09-19T00:17:07.123Z] 	debug_error_string = "UNKNOWN:Deadline Exceeded {grpc_status:4, created_time:"2022-09-18T23:24:03.903742266+00:00"}"
[2022-09-19T00:17:07.123Z] >)>
[2022-09-19T00:17:07.123Z]  (api_request.py:35)
[2022-09-19T00:17:07.123Z] [2022-09-18 23:24:03 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
[2022-09-19T00:17:07.123Z] 	status = StatusCode.DEADLINE_EXCEEDED
[2022-09-19T00:17:07.123Z] 	details = "Deadline Exceeded"
[2022-09-19T00:17:07.123Z] 	debug_error_string = "UNKNOWN:Deadline Exceeded {grpc_status:4, created_time:"2022-09-18T23:24:03.903742266+00:00"}"
[2022-09-19T00:17:07.124Z] >)> (api_request.py:36)
```

**Comment by NicoYuan1986** [comment]
This issue no longer occurs in master(c58a8d8).
