### ISSUE TITLE
[Bug]: Load timeout after Milvus recovered from standalone pod kill chaos

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#17768]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220623-9cd454e5
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-2.1.0.dev83
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

load timeout when running `test_e2e.py` after chaos

```
00:16:56  [2022-06-23 16:16:34 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 20], kwargs: {} (api_request.py:55)
00:16:56  [2022-06-23 16:16:54 - ERROR - pymilvus.decorators]: grpc RpcError: [load_collection], <_MultiThreadedRendezvous: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded>, <Time:{'RPC start': '2022-06-23 16:16:34.155341', 'gRPC error': '2022-06-23 16:16:54.155750'}> (decorators.py:86)
00:16:56  [2022-06-23 16:16:54 - ERROR - ci_test]: Traceback (most recent call last):
00:16:56    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 44, in handler
00:16:56      return func(self, *args, **kwargs)
00:16:56    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 87, in handler
00:16:56      raise e
00:16:56    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 75, in handler
00:16:56      return func(*args, **kwargs)
00:16:56    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 687, in load_collection
00:16:56      response = rf.result()
00:16:56    File "/usr/local/lib/python3.7/dist-packages/grpc/_channel.py", line 744, in result
00:16:56      raise self
00:16:56  grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
00:16:56  	status = StatusCode.DEADLINE_EXCEEDED
00:16:56  	details = "Deadline Exceeded"
00:16:56  	debug_error_string = "{"created":"@1656001014.155524401","description":"Error received from peer ipv4:10.96.141.29:19530","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Deadline Exceeded","grpc_status":4}"
00:16:56  >
00:16:56  
00:16:56  During handling of the above exception, another exception occurred:
00:16:56  
00:16:56  Traceback (most recent call last):
00:16:56    File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
00:16:56      res = func(*args, **kwargs)
00:16:56    File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 56, in api_request
00:16:56      return func(*arg, **kwargs)
00:16:56    File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 469, in load
00:16:56      conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
00:16:56    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 55, in handler
00:16:56      raise MilvusException(Status.UNEXPECTED_ERROR, "rpc timeout")
00:16:56  pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=rpc timeout)>
00:16:56   (api_request.py:35)
00:16:56  [2022-06-23 16:16:54 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=rpc timeout)> (api_request.py:36)
```

### Expected Behavior

all test cases passed

### Steps To Reproduce

```markdown
see http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test-kafka/detail/chaos-test-kafka/118/pipeline
```

### Milvus Log

failed job: http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test-kafka/detail/chaos-test-kafka/118/pipeline

log: [artifacts-standalone-pod-kill-118-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/8972998/artifacts-standalone-pod-kill-118-server-logs.tar.gz)
 

### Anything else?

Not a stable issue

**Comment by jaime0815** [comment]
There is the standalone mode with rocksmq
