### ISSUE TITLE
[Bug]: Indexcoord panic: failed to handle etcd request, exit.. 

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#17833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220626-9d2e5aac
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.1.0.dev83
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. Deploy milvus cluster with 2 datanodes
2. Scale out datanode from 2 to 3 while inserting entities
3. Indexcoord panic and restart
```
1157 [2022/06/27 08:19:25.795 +00:00] [DEBUG] [index_coord.go:341] ["get IndexCoord component states ..."]
1158 [2022/06/27 08:19:25.795 +00:00] [DEBUG] [index_coord.go:361] ["IndexCoord GetComponentStates"] ["IndexCoord component state"="nodeID:1 role:\"IndexCoord\" state_code:Healthy "]
1159 [2022/06/27 08:19:29.405 +00:00] [ERROR] [index_coord.go:874] ["received error event from etcd watcher"] [path=indexes] [error="etcdserver: mvcc: required revision has been compacted"] [stack="github.com/milvus-io/milvus/internal/indexcoord.(*IndexCoord).watchMetaLoop\n     \t/go/src/github.com/milvus-io/milvus/internal/indexcoord/index_coord.go:874"]
1160 panic: failed to handle etcd request, exit..
1161 
1162 goroutine 215 [running]:
1163 github.com/milvus-io/milvus/internal/indexcoord.(*IndexCoord).watchMetaLoop(0xc0003c2140)
1164     /go/src/github.com/milvus-io/milvus/internal/indexcoord/index_coord.go:875 +0x126b
1165 created by github.com/milvus-io/milvus/internal/indexcoord.(*IndexCoord).Start.func1
1166     /go/src/github.com/milvus-io/milvus/internal/indexcoord/index_coord.go:270 +0x15e
```
4. describe etcd pod:
```
I0627 16:55:02.743752   19468 request.go:645] Throttling request took 1.125594503s, request: GET:https://10.100.32.1:6443/apis/flows.knative.dev/v1alpha1?timeout=32s
Name:         scale-data-etcd-0
Namespace:    chaos-testing
Priority:     0
Node:         qa-node017.zilliz.local/10.100.32.25
Start Time:   Mon, 27 Jun 2022 16:19:29 +0800
Labels:       app.kubernetes.io/instance=scale-data-etcd
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=etcd
              controller-revision-hash=scale-data-etcd-6cd89ffbc5
              helm.sh/chart=etcd-6.3.3
              statefulset.kubernetes.io/pod-name=scale-data-etcd-0
Annotations:  <none>
Status:       Running
IP:           10.97.18.179
IPs:
  IP:           10.97.18.179
Controlled By:  StatefulSet/scale-data-etcd
Containers:
  etcd:
    Container ID:   docker://77acf4aa7719a83bc39976a7c973078b28bb7a117911509d2980ffe3f450b64c
    Image:          docker.io/bitnami/etcd:3.5.0-debian-10-r24
    Image ID:       docker-pullable://bitnami/etcd@sha256:914039ec8f4ba2c53580195bb21f487a1a86f6c3cd7275a1ec451e03c6c52dd1
    Ports:          2379/TCP, 2380/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Running
      Started:      Mon, 27 Jun 2022 16:19:30 +0800
    Ready:          True
    Restart Count:  0
    Liveness:       exec [/opt/bitnami/scripts/etcd/healthcheck.sh] delay=60s timeout=5s period=30s #success=1 #failure=5
    Readiness:      exec [/opt/bitnami/scripts/etcd/healthcheck.sh] delay=60s timeout=5s period=10s #success=1 #failure=5
    Environment:
      BITNAMI_DEBUG:                     false
      MY_POD_IP:                          (v1:status.podIP)
      MY_POD_NAME:                       scale-data-etcd-0 (v1:metadata.name)
      ETCDCTL_API:                       3
      ETCD_ON_K8S:                       yes
      ETCD_START_FROM_SNAPSHOT:          no
      ETCD_DISASTER_RECOVERY:            no
      ETCD_NAME:                         $(MY_POD_NAME)
      ETCD_DATA_DIR:                     /bitnami/etcd/data
      ETCD_LOG_LEVEL:                    info
      ALLOW_NONE_AUTHENTICATION:         yes
      ETCD_ADVERTISE_CLIENT_URLS:        http://$(MY_POD_NAME).scale-data-etcd-headless.chaos-testing.svc.cluster.local:2379
      ETCD_LISTEN_CLIENT_URLS:           http://0.0.0.0:2379
      ETCD_INITIAL_ADVERTISE_PEER_URLS:  http://$(MY_POD_NAME).scale-data-etcd-headless.chaos-testing.svc.cluster.local:2380
      ETCD_LISTEN_PEER_URLS:             http://0.0.0.0:2380
      ETCD_AUTO_COMPACTION_MODE:         revision
      ETCD_AUTO_COMPACTION_RETENTION:    1000
      ETCD_INITIAL_CLUSTER_TOKEN:        etcd-cluster-k8s
      ETCD_INITIAL_CLUSTER_STATE:        new
      ETCD_INITIAL_CLUSTER:              scale-data-etcd-0=http://scale-data-etcd-0.scale-data-etcd-headless.chaos-testing.svc.cluster.local:2380,scale-data-etcd-1=http://scale-data-etcd-1.scale-data-etcd-headless.chaos-testing.svc.cluster.local:2380,scale-data-etcd-2=http://scale-data-etcd-2.scale-data-etcd-headless.chaos-testing.svc.cluster.local:2380
      ETCD_CLUSTER_DOMAIN:               scale-data-etcd-headless.chaos-testing.svc.cluster.local
      ETCD_QUOTA_BACKEND_BYTES:          4294967296
      ETCD_HEARTBEAT_INTERVAL:           500
      ETCD_ELECTION_TIMEOUT:             2500
    Mounts:
      /bitnami/etcd from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-cww7v (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-scale-data-etcd-0
    ReadOnly:   false
  default-token-cww7v:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-cww7v
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From                              Message
  ----    ------     ----  ----                              -------
  Normal  Scheduled  35m                                     Successfully assigned chaos-testing/scale-data-etcd-0 to qa-node017.zilliz.local
  Normal  Pulled     35m   kubelet, qa-node017.zilliz.local  Container image "docker.io/bitnami/etcd:3.5.0-debian-10-r24" already present on machine
  Normal  Created    35m   kubelet, qa-node017.zilliz.local  Created container etcd
  Normal  Started    35m   kubelet, qa-node017.zilliz.local  Started container etcd
```

**Indexcoord log:**  
[indexcoord.log](https://github.com/milvus-io/milvus/files/8990274/indexcoord.log)

### Steps To Reproduce

```markdown
pytest scale/test_data_node_scale.py -v -s
```

**Comment by xiaocai2333** [comment]
we hold this error, please check it~ @ThreadDao 
/unassign
/assign @ThreadDao

**Comment by ThreadDao** [comment]
> we hold this error, please check it~ @ThreadDao /unassign /assign @ThreadDao

No reproduction on image `2.1.0-20220628-5b26b310`.  Let this issue sit for a while

**Comment by ThreadDao** [comment]
Closed. Reopen when there is a reproduce
