### ISSUE TITLE
[Bug]: arrow builder is nullptr

### ISSUE THREAD

**Issue by BUPTAnderson** [milvus-io/milvus#17851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-2.0.1
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 32core/196GB
- GPU: 
- Others:
```

### Current Behavior

datnode exits abnormally while user is inserting data

### Expected Behavior

datanode running healthily

### Milvus Log

```
panic: insertBufferNode flushBufferData failed, err = All attempts results:
attempt #1:[UnexpectedError] arrow builder is nullptr
attempt #2:[UnexpectedError] arrow builder is nullptr
attempt #3:[UnexpectedError] arrow builder is nullptr
attempt #4:[UnexpectedError] arrow builder is nullptr
attempt #5:[UnexpectedError] arrow builder is nullptr


goroutine 17339136 [running]:
github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Operate(0xc0007cb590, 0xc002dd4b70, 0x1, 0x1, 0x4256220, 0xc0033a45a0, 0x0)
        /opt/milvus/internal/datanode/flow_graph_insert_buffer_node.go:376 +0x3895
github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work(0xc003008b00)
        /opt/milvus/internal/util/flowgraph/node.go:102 +0x23b
created by github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start
        /opt/milvus/internal/util/flowgraph/node.go:70 +0x70
```

**Comment by letian-jiang** [comment]
Unfortunately, I cannot reproduce locally. 
@BUPTAnderson It would be very nice of you to provide the script or logs to us.

**Comment by xiaofan-luan** [comment]
> Unfortunately, I cannot reproduce locally. @BUPTAnderson It would be very nice of you to provide the script or logs to us.

I don't think we need to reproduce this issue, just check the code where this error could thrown out.

**Comment by xiaofan-luan** [comment]
There must be somewhere we misuse eventwriter without init it?

**Comment by BUPTAnderson** [comment]
> Unfortunately, I cannot reproduce locally. @BUPTAnderson It would be very nice of you to provide the script or logs to us.

the datanode log:
```
[2022/06/27 18:22:47.140 +08:00] [INFO] [segment_replica.go:625] ["updating segment"] ["Segment ID"=434195724883722241] [numRows=6]
[2022/06/27 18:22:47.140 +08:00] [INFO] [segment_replica.go:159] ["update pk range"] [collectionID=434192070176669697] [partitionID=434192073820733441] [segmentID=434195724883722241] [channel=by-dev-rootcoord-dml_22_434192070176669697v0] [num_rows=3209] [minPK=1001711116065925] [maxPK=1002511144059205]
[2022/06/27 18:22:47.143 +08:00] [INFO] [segment_replica.go:159] ["update pk range"] [collectionID=434192070176669697] [partitionID=434192073820733441] [segmentID=434195724883722241] [channel=by-dev-rootcoord-dml_22_434192070176669697v0] [num_rows=3209] [minPK=1001711116065925] [maxPK=1002511144059205]
[2022/06/27 18:22:47.149 +08:00] [INFO] [segment_replica.go:159] ["update pk range"] [collectionID=434192070176669697] [partitionID=434192073820733441] [segmentID=434195724883722241] [channel=by-dev-rootcoord-dml_22_434192070176669697v0] [num_rows=3209] [minPK=1001711116065925] [maxPK=1002511144059205]
[2022/06/27 18:22:47.152 +08:00] [INFO] [segment_replica.go:159] ["update pk range"] [collectionID=434192070176669697] [partitionID=434192073820733441] [segmentID=434195724883722241] [channel=by-dev-rootcoord-dml_22_434192070176669697v0] [num_rows=3209] [minPK=1001711116065925] [maxPK=1002511144059205]
[2022/06/27 18:22:47.155 +08:00] [INFO] [segment_replica.go:159] ["update pk range"] [collectionID=434192070176669697] [partitionID=434192073820733441] [segmentID=434195724883722241] [channel=by-dev-rootcoord-dml_22_434192070176669697v0] [num_rows=3209] [minPK=1001711116065925] [maxPK=1002511144059205]
[2022/06/27 18:22:47.158 +08:00] [INFO] [segment_replica.go:159] ["update pk range"] [collectionID=434192070176669697] [partitionID=434192073820733441] [segmentID=434195724883722241] [channel=by-dev-rootcoord-dml_22_434192070176669697v0] [num_rows=3209] [minPK=1001711116065925] [maxPK=1002511144059205]
[2022/06/27 18:22:47.166 +08:00] [INFO] [flow_graph_insert_buffer_node.go:249] ["insert seg buffer status"] [No.=0] [segmentID=434195724883722241] ["vchannel name"=by-dev-rootcoord-dml_22_434192070176669697v0] ["buffer size"=3209] ["buffer limit"=8192]
[2022/06/27 18:22:47.340 +08:00] [INFO] [segment_replica.go:625] ["updating segment"] ["Segment ID"=434195724883722241] [numRows=4]
[2022/06/27 18:22:47.340 +08:00] [INFO] [segment_replica.go:159] ["update pk range"] [collectionID=434192070176669697] [partitionID=434192073820733441] [segmentID=434195724883722241] [channel=by-dev-rootcoord-dml_22_434192070176669697v0] [num_rows=3213] [minPK=1001711116065925] [maxPK=1002511144059205]
[2022/06/27 18:22:47.344 +08:00] [INFO] [segment_replica.go:159] ["update pk range"] [collectionID=434192070176669697] [partitionID=434192073820733441] [segmentID=434195724883722241] [channel=by-dev-rootcoord-dml_22_434192070176669697v0] [num_rows=3213] [minPK=1001711116065925] [maxPK=1002511144059205]
[2022/06/27 18:22:47.344 +08:00] [ERROR] [flow_graph_insert_buffer_node.go:375] ["insertBufferNode flushBufferData failed, err = All attempts results:\nattempt #1:[UnexpectedError] arrow builder is nullptr\nattempt #2:[UnexpectedError] arrow builder is nullptr\nattempt #3:[UnexpectedError] arrow builder is nullptr\nattempt #4:[UnexpectedError] arrow builder is nullptr\nattempt #5:[UnexpectedError] arrow builder is nullptr\n"] [stack="github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Operate\n\t/opt/milvus/internal/datanode/flow_graph_insert_buffer_node.go:375\ngithub.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work\n\t/opt/milvus/internal/util/flowgraph/node.go:102"]
```

the `collectionID=434192070176669697` schema:
```
{
  auto_id: False
  description: ci cv finegrain-nextvlad-v2 feedvideo collection
  fields: [{
    name: id
    description: feedid
    type: 5
    is_primary: True
    auto_id: False
  }, {
    name: embedding
    description: feed embedding
    type: 101
    params: {'dim': 512}
  }, {
    name: embed_insert_time
    description: timestamp: second
    type: 5
  }, {
    name: feed_create_time
    description: timestamp: second
    type: 5
  }]
}
```

**Comment by letian-jiang** [comment]
For FloatVector/BinaryVector datatype, we lazily init the arrow builder when we add values into the payload.
But in FinishPayloadWriter, we check whether the arrow builder is nullptr. This is a suspicious cause.
