### ISSUE TITLE
[Bug]: Indexcoord panic: All attempts results: attempt #1:function CompareAndSwap error for compare is false for key: indexcoord

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#17864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220628-899a9bf8
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. Run case `test_expand_index_node` of `/tests/python_client/scale/test_index_node_scale.py`
```
[2022/06/28 06:50:45.163 +00:00] [WARN] [tso.go:177] ["clock offset is huge, check network latency and clock skew"] [jet-lag=198.189775ms] [prev-physical=2022/06/28 06:50:44.964 +00:00] [now=2022/06/28 06:50:45.163 +00:00]
[2022/06/28 06:50:49.679 +00:00] [DEBUG] [retry.go:39] ["retry func failed"] ["retry time"=20] [error="function CompareAndSwap error for compare is false for key: indexcoord"]
panic: All attempts results:
attempt #1:function CompareAndSwap error for compare is false for key: indexcoord
attempt #2:function CompareAndSwap error for compare is false for key: indexcoord
attempt #3:function CompareAndSwap error for compare is false for key: indexcoord
attempt #4:function CompareAndSwap error for compare is false for key: indexcoord
attempt #5:function CompareAndSwap error for compare is false for key: indexcoord
attempt #6:function CompareAndSwap error for compare is false for key: indexcoord
attempt #7:function CompareAndSwap error for compare is false for key: indexcoord
attempt #8:function CompareAndSwap error for compare is false for key: indexcoord
attempt #9:function CompareAndSwap error for compare is false for key: indexcoord
attempt #10:function CompareAndSwap error for compare is false for key: indexcoord
attempt #11:function CompareAndSwap error for compare is false for key: indexcoord


goroutine 143 [running]:
github.com/milvus-io/milvus/internal/util/sessionutil.(*Session).Register(0xc0005da480)
    /go/src/github.com/milvus-io/milvus/internal/util/sessionutil/session_util.go:129 +0xc6
github.com/milvus-io/milvus/internal/indexcoord.(*IndexCoord).Register(0xc000c36140, 0x12, 0x0)
    /go/src/github.com/milvus-io/milvus/internal/indexcoord/index_coord.go:132 +0x33
github.com/milvus-io/milvus/internal/distributed/indexcoord.(*Server).start(0xc000c2a540, 0x18, 0x0)
    /go/src/github.com/milvus-io/milvus/internal/distributed/indexcoord/service.go:156 +0xa9
github.com/milvus-io/milvus/internal/distributed/indexcoord.(*Server).Run(0xc000c2a540, 0x0, 0x0)
    /go/src/github.com/milvus-io/milvus/internal/distributed/indexcoord/service.go:81 +0x7e
github.com/milvus-io/milvus/cmd/components.(*IndexCoord).Run(0xc00058c6b0, 0xffffffffffffffff, 0x8)
    /go/src/github.com/milvus-io/milvus/cmd/components/index_coord.go:48 +0x32
github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runIndexCoord.func1(0x2ea9900, 0x31935f0, 0xc0005d4600, 0xc00058c0a8, 0xc0005d6070, 0xc0005d6120)
    /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:315 +0x125
created by github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runIndexCoord
    /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:296 +0xba
```

**Server logs:**
[mic_logs.tar.gz](https://github.com/milvus-io/milvus/files/8998481/mic_logs.tar.gz)

**Comment by xiaofan-luan** [comment]
@xiaocai2333 is fixing it

**Comment by xiaocai2333** [comment]
Has it reappeared? This may be an issue caused by the wrong deployment of the cluster. @ThreadDao

**Comment by xiaofan-luan** [comment]
@wayblink should fix this issue after backup coordinator is supported
