### ISSUE TITLE
[Bug]: [Nightly] Get segment info failed showing "getSegmentInfo: queryNode 2 is offline"

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#17889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 4ae1ca2
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.1.0.dev87
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Get segment info failed showing "getSegmentInfo: queryNode 2 is offline"

### Steps To Reproduce

```markdown
Running nightly:

the following cases includes interface "get_query_segment_info"

[2022-06-28T20:07:22.250Z] FAILED testcases/test_utility.py::TestUtilityAdvanced::test_get_query_segment_info_empty_collection
[2022-06-28T20:07:22.250Z] FAILED testcases/test_utility.py::TestUtilityAdvanced::test_get_growing_query_segment_info
[2022-06-28T20:07:22.250Z] FAILED testcases/test_utility.py::TestUtilityAdvanced::test_get_growing_segment_info_after_load
[2022-06-28T20:07:22.250Z] FAILED testcases/test_utility.py::TestUtilityAdvanced::test_get_sealed_query_segment_info
[2022-06-28T20:07:22.250Z] FAILED testcases/test_utility.py::TestUtilityAdvanced::test_load_balance_normal
[2022-06-28T20:07:22.250Z] FAILED testcases/test_utility.py::TestUtilityAdvanced::test_get_sealed_query_segment_info_after_create_index
[2022-06-28T20:07:22.250Z] FAILED testcases/test_utility.py::TestUtilityAdvanced::test_load_balance_with_src_node_not_exist
[2022-06-28T20:07:22.250Z] FAILED testcases/test_utility.py::TestUtilityAdvanced::test_load_balance_with_one_sealed_segment_id_not_exist
[2022-06-28T20:07:22.250Z] FAILED testcases/test_utility.py::TestUtilityAdvanced::test_load_balance_with_all_dst_node_not_exist
```
```


### Milvus Log

1.milvus log:
[artifacts-milvus-distributed-pulsar-master-622-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/622/artifact/artifacts-milvus-distributed-pulsar-master-622-pymilvus-e2e-logs.tar.gz)

2. collection name: utility_xHrAoM0q
3. test case failed time:
[2022-06-28T19:42:41.452Z] ~ [2022-06-28T19:42:59.513Z]
4. test case error trace:
```
[2022-06-28T20:07:22.236Z] [2022-06-28 19:42:40 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 20], kwargs: {} (api_request.py:55)
[2022-06-28T20:07:22.236Z] [2022-06-28 19:42:41 - DEBUG - ci_test]: (api_response) : None  (api_request.py:27)
[2022-06-28T20:07:22.236Z] [2022-06-28 19:42:41 - DEBUG - ci_test]: (api_request)  : [get_query_segment_info] args: ['utility_xHrAoM0q', 20, 'default'], kwargs: {} (api_request.py:55)
[2022-06-28T20:07:22.236Z] [2022-06-28 19:42:41 - ERROR - pymilvus.decorators]: RPC error: [get_query_segment_info], <MilvusException: (code=1, message=getSegmentInfo: queryNode 2 is offline)>, <Time:{'RPC start': '2022-06-28 19:42:41.185158', 'RPC error': '2022-06-28 19:42:41.191304'}> (decorators.py:94)
[2022-06-28T20:07:22.236Z] [2022-06-28 19:42:41 - ERROR - ci_test]: Traceback (most recent call last):
[2022-06-28T20:07:22.236Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
[2022-06-28T20:07:22.236Z]     res = func(*args, **kwargs)
[2022-06-28T20:07:22.236Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 56, in api_request
[2022-06-28T20:07:22.236Z]     return func(*arg, **kwargs)
[2022-06-28T20:07:22.236Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/utility.py", line 575, in get_query_segment_info
[2022-06-28T20:07:22.236Z]     return _get_connection(using).get_query_segment_info(collection_name, timeout=timeout)
[2022-06-28T20:07:22.236Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 95, in handler
[2022-06-28T20:07:22.236Z]     raise e
[2022-06-28T20:07:22.236Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 91, in handler
[2022-06-28T20:07:22.236Z]     return func(*args, **kwargs)
[2022-06-28T20:07:22.236Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 73, in handler
[2022-06-28T20:07:22.236Z]     raise e
[2022-06-28T20:07:22.236Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 48, in handler
[2022-06-28T20:07:22.236Z]     return func(self, *args, **kwargs)
[2022-06-28T20:07:22.236Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 449, in get_query_segment_info
[2022-06-28T20:07:22.236Z]     raise MilvusException(status.error_code, status.reason)
[2022-06-28T20:07:22.236Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=getSegmentInfo: queryNode 2 is offline)>
[2022-06-28T20:07:22.236Z]  (api_request.py:35)
[2022-06-28T20:07:22.236Z] [2022-06-28 19:42:41 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=getSegmentInfo: queryNode 2 is offline)> (api_request.py:36)
[2022-06-28T20:07:22.236Z] ___________ TestUtilityAdvanced.test_get_growing_query_segment_info ____________
```

### Anything else?

_No response_

**Comment by yah01** [comment]
Same as #17411, which will be fixed with making the GetQuerySegmentInfo return only sealed segments

**Comment by binbinlv** [comment]
It occurs frequently in master branch, so set it as urgent.

**Comment by binbinlv** [comment]
It is fixed, and no this error recently, so close it.
