### ISSUE TITLE
[Bug]: Milvus  crashed with panic "SnapShotKV MultiSaveAndRemoveWithPrefix fail"

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#17928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 7c20ac02a
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.0.dev87
- OS(Ubuntu or CentOS): ubuntu18.04
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

 When I raised this pr : https://github.com/milvus-io/milvus/pull/17918 
ci-test  appears  could not connect milvus with panic "SnapShotKV MultiSaveAndRemoveWithPrefix fail"

### Expected Behavior

 Milvus shouldn't crash

### Steps To Reproduce
Running CI
https://github.com/milvus-io/milvus/pull/17918 

_No response_

### Milvus Log
 
see comment

**Comment by binbinlv** [comment]
Some info may be a help:
1. Test case fail time: about. [2022-06-29T11:24:10.594Z
2. panic time: about 2022/06/29 11:23:32.511
3. panic file:
ms-17918-1-pr-milvus-standalone-69d89fb757-ff6xr_milvus-ci_standalone-433af1a163f02ddafd54a181e3a28dac45c7032911c0e46d243ff978e75bc222.log:panic: SnapShotKV MultiSaveAndRemoveWithPrefix fail
ms-17918-1-pr-milvus-standalone-69d89fb757-ff6xr_milvus-ci_standalone-a6717aa0cc293711b1ec4a8416b6b4942fffc48dbf248f125db3694dee788465.log:panic: All attempts results:
ms-17918-1-pr-milvus-standalone-69d89fb757-ff6xr_milvus-ci_standalone-a6717aa0cc293711b1ec4a8416b6b4942fffc48dbf248f125db3694dee788465.log:panic: All attempts results:

4. panic :
```
[2022/06/29 11:23:32.407 +00:00] [INFO] [timeticksync.go:233] ["ddl not finished"] ["source id"=8] ["curr ts"=434242005752611079] [ddlMinTs=434242005752610981] [reason=gRPC]

[2022/06/29 11:23:32.511 +00:00] [WARN] [etcd_kv.go:684] ["Slow etcd operation multi save"] ["time spent"=10.001122289s]

[2022/06/29 11:23:32.511 +00:00] [ERROR] [meta_table.go:738] ["SnapShotKV MultiSaveAndRemoveWithPrefix fail"] [error="context deadline exceeded"] [stack="github.com/milvus-io/milvus/internal/rootcoord.(*MetaTable).DeletePartition\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/meta_table.go:738\ngithub.com/milvus-io/milvus/internal/rootcoord.(*DropPartitionReqTask).Execute.func1\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/task.go:666\ngithub.com/milvus-io/milvus/internal/rootcoord.(*DropPartitionReqTask).Execute\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/task.go:679\ngithub.com/milvus-io/milvus/internal/rootcoord.executeTask.func1\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/task.go:63"]

[2022/06/29 11:23:32.511 +00:00] [DEBUG] [timeticksync.go:190] ["remove ddl timetick"] [ts=434242005752610981] [len(ddlTsSet)=0] [reason="drop partition search_partition_0"]

{"level":"warn","ts":"2022-06-29T11:23:32.511Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000539340/#initially=[ms-17918-1-pr-etcd:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}

panic: SnapShotKV MultiSaveAndRemoveWithPrefix fail



goroutine 260383 [running]:

github.com/milvus-io/milvus/internal/rootcoord.(*MetaTable).DeletePartition(0xc0007dc400, 0x606bccd4ea80001, 0xc00ac912a8, 0x12, 0x606bccdb37000a5, 0xc0042d6160, 0xa2, 0x0, 0x0, 0x0)

        /go/src/github.com/milvus-io/milvus/internal/rootcoord/meta_table.go:739 +0x1926

github.com/milvus-io/milvus/internal/rootcoord.(*DropPartitionReqTask).Execute.func1(0x0, 0x0)

        /go/src/github.com/milvus-io/milvus/internal/rootcoord/task.go:666 +0x29d

github.com/milvus-io/milvus/internal/rootcoord.(*DropPartitionReqTask).Execute(0xc002947aa0, 0x31935d8, 0xc005358e10, 0xc0010be0f0, 0x2ea99c8)

        /go/src/github.com/milvus-io/milvus/internal/rootcoord/task.go:679 +0x565

github.com/milvus-io/milvus/internal/rootcoord.executeTask.func1(0x31949f8, 0xc002947aa0, 0xc00d82e6c0)

        /go/src/github.com/milvus-io/milvus/internal/rootcoord/task.go:63 +0x45

created by github.com/milvus-io/milvus/internal/rootcoord.executeTask

        /go/src/github.com/milvus-io/milvus/internal/rootcoord/task.go:62 +0x89
```

**Comment by binbinlv** [comment]
Milvus logs:
[ms-17918-1-pr.zip](https://github.com/milvus-io/milvus/files/9016038/ms-17918-1-pr.zip)

**Comment by xiaofan-luan** [comment]
seems like a etcd timeout issue, the panic seems to be not a bug.
We will refine the code logic in later release, so far keep it as is
