### ISSUE TITLE
[Bug]: Status code error, there is an exception that returns a status code of 0 

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#17985]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.1.0.dev92
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When I delete an index with an invalid collection name, the status code is 0

`[2022-07-01 10:57:04,212 - ERROR - ci_test]: (api_response) : <IndexNotExistException: (code=0, message=Index doesn't exist.)> (api_request.py:36)
`

### Expected Behavior

When an exception is returned, the code should not be  zero

### Steps To Reproduce

```markdown
drop index with invalid collection name
```

**Comment by elstic** [comment]
> @elstic could you offer detailed logs and your test steps so we can investigae?

@xiaofan-luan @XuanYang-cn   Here are the parameters I used and the corresponding logs：

```
[2022-07-08 15:38:26,218 - DEBUG - ci_test]: (api_request)  : [Collection] args: ['index_nycGWnlh', {
  auto_id: False
  description: 
  fields: [{
    name: int64
    description: 
    type: 5
    is_primary: True
    auto_id: False
  }, {
    name: float
    description: 
    type: 10
  }, {
    name: varchar
    description: 
    type: 21
    params: {'max_length': 65535}
  }......, kwargs: {'consistency_level': 'Strong'} (api_request.py:52)
[2022-07-08 15:38:26,269 - DEBUG - ci_test]: (api_response) : <Collection>:
-------------
<name>: index_nycGWnlh
<partitions>: [{"name": "_default", "collection_name": "index_nycGWnlh", "description": ""}]
<description>: 
<schema>: {
  auto_id: False
  description: 
  fields: [{
    name: int64
    description: 
    type: 5
    is_primary: True
    auto_id: Fa......  (api_request.py:27)
[2022-07-08 15:38:26,269 - DEBUG - ci_test]: (api_request)  : [Collection.drop_index] args: [], kwargs: {'timeout': 20, 'index_name': 'binary_vector'} (api_request.py:52)

[2022-07-08 15:38:26,277 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/xxx/vscode/milvus/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
    res = func(*args, **kwargs)
  File "/Users/xxx/vscode/milvus/tests/python_client/utils/api_request.py", line 53, in api_request
    return func(*arg, **kwargs)
  File "/Users/xxx/vscode/milvus/tests/python_client/venv/lib/python3.9/site-packages/pymilvus/orm/collection.py", line 1152, in drop_index
    raise IndexNotExistException(0, ExceptionsMessage.IndexNotExist)
pymilvus.exceptions.IndexNotExistException: <IndexNotExistException: (code=0, message=Index doesn't exist.)>
 (api_request.py:35)
[2022-07-08 15:38:26,277 - ERROR - ci_test]: (api_response) : <IndexNotExistException: (code=0, message=Index doesn't exist.)> (api_request.py:36)

```
I think since there is an exception, the error_code should not be 0  

The corresponding code location might be here ： https://github.com/milvus-io/pymilvus/blob/master/pymilvus/orm/collection.py#L1152


With a conversation：
Wang: I think the error code should be categorized, -100 to -200 means A error, -200 to -300 means B error
Yang: No time now
Wang: So is it okay to have an Exception code that is not set to 0? 
Yang: Yes, you can raise issue assign to me
