### ISSUE TITLE
[Bug]: [benchmark][cluster]Milvus  100m data load failed ,raise ad error"collection has not been loaded to memory or load failed"

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#18158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.0-20220707-98a1e20e
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.1.0dev87
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server-instance
benchmark-tag-no-clean-swfjs-1
server-configmap
server-cluster-8c64m-kafka
client-configmap
client-random-locust-100m-ddl-r8-w2

server:
```
benchmark-tag-no-clean-swfjs-1-etcd-0                             1/1     Running     0          13h     10.97.16.31    qa-node013.zilliz.local   <none>           <none>
benchmark-tag-no-clean-swfjs-1-etcd-1                             1/1     Running     0          13h     10.97.17.15    qa-node014.zilliz.local   <none>           <none>
benchmark-tag-no-clean-swfjs-1-etcd-2                             1/1     Running     0          13h     10.97.17.14    qa-node014.zilliz.local   <none>           <none>
benchmark-tag-no-clean-swfjs-1-kafka-0                            1/1     Running     1          13h     10.97.13.48    qa-node010.zilliz.local   <none>           <none>
benchmark-tag-no-clean-swfjs-1-kafka-1                            1/1     Running     1          13h     10.97.4.112    qa-node002.zilliz.local   <none>           <none>
benchmark-tag-no-clean-swfjs-1-kafka-2                            1/1     Running     1          13h     10.97.18.201   qa-node017.zilliz.local   <none>           <none>
benchmark-tag-no-clean-swfjs-1-milvus-datacoord-57f86494f6bc76z   1/1     Running     0          13h     10.97.13.47    qa-node010.zilliz.local   <none>           <none>
benchmark-tag-no-clean-swfjs-1-milvus-datanode-74788d45d5-cbtwp   1/1     Running     0          13h     10.97.17.11    qa-node014.zilliz.local   <none>           <none>
benchmark-tag-no-clean-swfjs-1-milvus-indexcoord-78847d67cjp8gh   1/1     Running     0          13h     10.97.13.46    qa-node010.zilliz.local   <none>           <none>
benchmark-tag-no-clean-swfjs-1-milvus-indexnode-5bf57589d6cccmj   1/1     Running     0          13h     10.97.20.105   qa-node018.zilliz.local   <none>           <none>
benchmark-tag-no-clean-swfjs-1-milvus-proxy-54bb49c779-tfcdd      1/1     Running     0          13h     10.97.13.44    qa-node010.zilliz.local   <none>           <none>
benchmark-tag-no-clean-swfjs-1-milvus-querycoord-84d9f5785dbf45   1/1     Running     0          13h     10.97.13.45    qa-node010.zilliz.local   <none>           <none>
benchmark-tag-no-clean-swfjs-1-milvus-querynode-75d8564f4dn5dmw   1/1     Running     0          13h     10.97.16.29    qa-node013.zilliz.local   <none>           <none>
benchmark-tag-no-clean-swfjs-1-milvus-rootcoord-74df4b9d5bwd8l8   1/1     Running     0          13h     10.97.13.43    qa-node010.zilliz.local   <none>           <none>
benchmark-tag-no-clean-swfjs-1-minio-0                            1/1     Running     0          13h     10.97.12.119   qa-node015.zilliz.local   <none>           <none>
benchmark-tag-no-clean-swfjs-1-minio-1                            1/1     Running     0          13h     10.97.12.122   qa-node015.zilliz.local   <none>           <none>
benchmark-tag-no-clean-swfjs-1-minio-2                            1/1     Running     0          13h     10.97.12.120   qa-node015.zilliz.local   <none>           <none>
benchmark-tag-no-clean-swfjs-1-minio-3                            1/1     Running     0          13h     10.97.12.121   qa-node015.zilliz.local   <none>           <none>
benchmark-tag-no-clean-swfjs-1-zookeeper-0                        1/1     Running     0          13h     10.97.4.111    qa-node002.zilliz.local   <none>           <none>
benchmark-tag-no-clean-swfjs-1-zookeeper-1                        1/1     Running     0          13h     10.97.18.202   qa-node017.zilliz.local   <none>           <none>
benchmark-tag-no-clean-swfjs-1-zookeeper-2                        1/1     Running     0          13h     10.97.13.49    qa-node010.zilliz.local   <none>           <none>
```
client:
```
[2022-07-07 15:26:55,832] [   DEBUG] - Row count: 100000000 in collection: <sift_100m_128_l2> (milvus_benchmark.client:428)
[2022-07-07 15:26:55,833] [    INFO] - 100000000 (milvus_benchmark.runners.locust:455)
[2022-07-07 15:26:55,836] [    INFO] - Start load collection (milvus_benchmark.runners.locust:456)
[2022-07-07 15:28:27,498] [   ERROR] - RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=collection sift_100m_128_l2 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-07-07 15:26:56.592475', 'RPC error': '2022-07-07 15:28:27.498443'}> (pymilvus.decorators:94)
[2022-07-07 15:28:27,502] [   ERROR] - RPC error: [load_collection], <MilvusException: (code=1, message=collection sift_100m_128_l2 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-07-07 15:26:55.837679', 'RPC error': '2022-07-07 15:28:27.502235'}> (pymilvus.decorators:94)
[2022-07-07 15:28:27,503] [   ERROR] - <MilvusException: (code=1, message=collection sift_100m_128_l2 has not been loaded to memory or load failed)> (milvus_benchmark.main:118)
[2022-07-07 15:28:27,512] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 87, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/locust.py", line 458, in prepare
    self.milvus.load_collection(replica_number=replica_number)
  File "/src/milvus_benchmark/client.py", line 50, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 495, in load_collection
    return self._milvus.load_collection(collection_name, **params)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 192, in load_collection
    return handler.load_collection(collection_name=collection_name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 95, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 91, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 73, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 48, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 666, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 95, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 91, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 73, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 48, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 675, in wait_for_loading_collection
    return self._wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 704, in _wait_for_loading_collection
    progress = self.get_collection_loading_progress(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 683, in get_collection_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection sift_100m_128_l2 has not been loaded to memory or load failed)>
 (milvus_benchmark.main:119)
```

### Steps To Reproduce

```markdown
1、create collection
2、create index of ivf_sq8
3、insert 100m million vectors
4、flush collection
5、build index with the same params
6、load collection raise an error
```

### Anything else?

client-random-locust-100m-ddl-r8-w2:

```
locust_random_performance:
      collections:
        -
          collection_name: sift_100m_128_l2
          ni_per: 50000
          build_index: true
          index_type: ivf_sq8
          index_param:
            nlist: 2048
          task:
            types:
              -
                type: query
                weight: 8
                params:
                  top_k: 10
                  nq: 10
                  search_param:
                    nprobe: 16
              -
                type: load
                weight: 1
              -
                type: get
                weight: 8
                params:
                  ids_length: 10
              -
                type: scene_test
                weight: 2
            connection_num: 1
            clients_num: 20
            spawn_rate: 2
            during_time: 84h
```

**Comment by jingkl** [comment]
This problem has been solved, but a new issue  #18232  has arisen, so turn this off
