### ISSUE TITLE
[Bug]: Create collection failed for Milvus with kafka mq 

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#18164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220707-58a9a0b7
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

create collection when running `python3 action_before_reinstall.py` for deploy test

```
18:06:37  Create collection...
18:06:37  Traceback (most recent call last):
18:06:37    File "action_before_reinstall.py", line 43, in <module>
18:06:37      task_1(data_size, host)
18:06:37    File "action_before_reinstall.py", line 15, in task_1
18:06:37      create_collections_and_insert_data(prefix,data_size)
18:06:37    File "/home/jenkins/agent/workspace/tests/python_client/deploy/scripts/utils.py", line 84, in create_collections_and_insert_data
18:06:37      collection = Collection(name=col_name, schema=default_schema) 
18:06:37    File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 139, in __init__
18:06:37      consistency_level=consistency_level)
18:06:37    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 95, in handler
18:06:37      raise e
18:06:37    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 91, in handler
18:06:37      return func(*args, **kwargs)
18:06:37    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 73, in handler
18:06:37      raise e
18:06:37    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 48, in handler
18:06:37      return func(self, *args, **kwargs)
18:06:37    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 197, in create_collection
18:06:37      raise MilvusException(status.error_code, status.reason)
18:06:37  pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=CreateCollection failed: send dd create collection req failed, error = Broker: Invalid replication factor)>
```

### Expected Behavior

all test cases passed

### Steps To Reproduce

```markdown
see http://10.100.32.144:8080/blue/organizations/jenkins/deploy_test_kafka/detail/deploy_test_kafka/101/pipeline
```

### Milvus Log

failed job: http://10.100.32.144:8080/blue/organizations/jenkins/deploy_test_kafka/detail/deploy_test_kafka/101/pipeline
log: [artifacts-cluster-reinstall-101-logs.tar.gz](https://github.com/milvus-io/milvus/files/9068560/artifacts-cluster-reinstall-101-logs.tar.gz)

**Comment by zhuwenxing** [comment]
It should be an occasional problem, but we can still investigate the reasons

**Comment by xiaofan-luan** [comment]
keep it open
