### ISSUE TITLE
[Bug]: datanode crash with error MetadataError Consumer not found

### ISSUE THREAD

**Issue by BUPTAnderson** [milvus-io/milvus#18206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.0.1
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 32Cores/192GB
- GPU: 
- Others:
```

### Current Behavior

datanode crash after running about 2 days.
datanode error log:
```
[2022/07/09 22:21:52.176 +08:00] [ERROR] [pulsar_consumer.go:134] ["failed to unsubscribe"] [subscription=by-dev-dataNode-30-434165452428804097] [error="All attempts results:\nattempt #1:topic persistent://public/default/by-dev-rootcoord-dml_13, subscription by-dev-dataNode-30-434165452428804097: server error: MetadataError: Consumer not found\nattempt #2:topic persistent://public/default/by-dev-rootcoord-dml_13, subscription by-dev-dataNode-30-434165452428804097: server error: MetadataError: Consumer not found\nattempt #3:topic persistent://public/default/by-dev-rootcoord-dml_13, subscription by-dev-dataNode-30-434165452428804097: server error: MetadataError: Consumer not found\nattempt #4:topic persistent://public/default/by-dev-rootcoord-dml_13, subscription by-dev-dataNode-30-434165452428804097: server error: MetadataError: Consumer not found\nattempt #5:topic persistent://public/default/by-dev-rootcoord-dml_13, subscription by-dev-dataNode-30-434165452428804097: server error: MetadataError: Consumer not found\nattempt #6:topic persistent://public/default/by-dev-rootcoord-dml_13, subscription by-dev-dataNode-30-434165452428804097: server error: MetadataError: Consumer not found\nattempt #7:topic persistent://public/default/by-dev-rootcoord-dml_13, subscription by-dev-dataNode-30-434165452428804097: server error: MetadataError: Consumer not found\nattempt #8:topic persistent://public/default/by-dev-rootcoord-dml_13, subscription by-dev-dataNode-30-434165452428804097: server error: MetadataError: Consumer not found\nattempt #9:topic persistent://public/default/by-dev-rootcoord-dml_13, subscription by-dev-dataNode-30-434165452428804097: server error: MetadataError: Consumer not found\nattempt #10:topic persistent://public/default/by-dev-rootcoord-dml_13, subscription by-dev-dataNode-30-434165452428804097: server error: MetadataError: Consumer not found\nattempt #11:topic persistent://public/default/by-dev-rootcoord-dml_13, subscription by-dev-dataNode-30-434165452428804097: server error: MetadataError: Consumer not found\n"] [stack="github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/pulsar.(*Consumer).Close.func1\n\t/opt/milvus/internal/mq/msgstream/mqwrapper/pulsar/pulsar_consumer.go:134\nsync.(*Once).doSlow\n\t/usr/local/go/src/sync/once.go:68\nsync.(*Once).Do\n\t/usr/local/go/src/sync/once.go:59\ngithub.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/pulsar.(*Consumer).Close\n\t/opt/milvus/internal/mq/msgstream/mqwrapper/pulsar/pulsar_consumer.go:114\ngithub.com/milvus-io/milvus/internal/mq/msgstream.(*mqMsgStream).Close\n\t/opt/milvus/internal/mq/msgstream/mq_msgstream.go:199\ngithub.com/milvus-io/milvus/internal/mq/msgstream.(*MqTtMsgStream).Close\n\t/opt/milvus/internal/mq/msgstream/mq_msgstream.go:668\ngithub.com/milvus-io/milvus/internal/util/flowgraph.(*InputNode).Close\n\t/opt/milvus/internal/util/flowgraph/input_node.go:47\ngithub.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Close\n\t/opt/milvus/internal/util/flowgraph/node.go:130\ngithub.com/milvus-io/milvus/internal/util/flowgraph.(*TimeTickedFlowGraph).Close.func1\n\t/opt/milvus/internal/util/flowgraph/flow_graph.go:93\nsync.(*Once).doSlow\n\t/usr/local/go/src/sync/once.go:68\nsync.(*Once).Do\n\t/usr/local/go/src/sync/once.go:59\ngithub.com/milvus-io/milvus/internal/util/flowgraph.(*TimeTickedFlowGraph).Close\n\t/opt/milvus/internal/util/flowgraph/flow_graph.go:89\ngithub.com/milvus-io/milvus/internal/datanode.(*dataSyncService).close\n\t/opt/milvus/internal/datanode/data_sync_service.go:137\ngithub.com/milvus-io/milvus/internal/datanode.(*flowgraphManager).release\n\t/opt/milvus/internal/datanode/flow_graph_manager.go:79\ngithub.com/milvus-io/milvus/internal/datanode.(*DataNode).tryToReleaseFlowgraph\n\t/opt/milvus/internal/datanode/data_node.go:422\ngithub.com/milvus-io/milvus/internal/datanode.(*DataNode).handlePutEvent\n\t/opt/milvus/internal/datanode/data_node.go:409\ngithub.com/milvus-io/milvus/internal/datanode.(*channelEventManager).retryHandlePutEvent\n\t/opt/milvus/internal/datanode/event_manager.go:88\ngithub.com/milvus-io/milvus/internal/datanode.(*channelEventManager).Run.func1\n\t/opt/milvus/internal/datanode/event_manager.go:70"]
```

```
time="2022-07-09T22:21:43+08:00" level=info msg="Closing consumer=9763" consumerID=9763 name=royut subscription=by-dev-dataNode-30-434165452376637441 topic="persistent://public/default/by-dev-rootcoord-dml_11"
time="2022-07-09T22:21:43+08:00" level=warning msg="[Failed to close consumer]" consumerID=9763 error="server error: MetadataError: Consumer not found" name=royut subscription=by-dev-dataNode-30-434165452376637441 topic="persistent://public/default/by-dev-rootcoord-dml_11"
time="2022-07-09T22:21:43+08:00" level=info msg="[Closing producer]" producerID=19525 producer_name=pulsar-cluster-0-17484 topic="persistent://public/default/by-dev-rootcoord-delta_11"
time="2022-07-09T22:21:43+08:00" level=info msg="[Closed producer]" producerID=19525 producer_name=pulsar-cluster-0-17484 topic="persistent://public/default/by-dev-rootcoord-delta_11"
time="2022-07-09T22:21:43+08:00" level=info msg="[Closing producer]" producerID=19526 producer_name=pulsar-cluster-1-19923 topic="persistent://public/default/by-dev-datacoord-timetick-channel"
time="2022-07-09T22:21:43+08:00" level=info msg="[Closed producer]" producerID=19526 producer_name=pulsar-cluster-1-19923 topic="persistent://public/default/by-dev-datacoord-timetick-channel"
time="2022-07-09T22:21:47+08:00" level=error msg="[Failed to unsubscribe consumer]" consumerID=9756 error="server error: MetadataError: Consumer not found" name=flrfb subscription=by-dev-dataNode-30-434165452428804097 topic="persistent://public/default/by-dev-rootcoord-dml_13"
time="2022-07-09T22:21:50+08:00" level=info msg="[Connected consumer]" consumerID=9764 name=zzmwq subscription=by-dev-dataNode-30-434165452376637441 topic="persistent://public/default/by-dev-rootcoord-dml_10"
time="2022-07-09T22:21:50+08:00" level=info msg="[Created consumer]" consumerID=9764 name=zzmwq subscription=by-dev-dataNode-30-434165452376637441 topic="persistent://public/default/by-dev-rootcoord-dml_10"
time="2022-07-09T22:21:50+08:00" level=info msg="Broker notification of Closed consumer: 9764" local_addr="10.97.109.218:33064" remote_addr="pulsar://hadoop2038.rz.momo.com:6650"
time="2022-07-09T22:21:50+08:00" level=info msg="[Reconnecting to broker in  103.004469ms]" consumerID=9764 name=zzmwq subscription=by-dev-dataNode-30-434165452376637441 topic="persistent://public/default/by-dev-rootcoord-dml_10"
time="2022-07-09T22:21:50+08:00" level=info msg="[Connected consumer]" consumerID=9764 name=zzmwq subscription=by-dev-dataNode-30-434165452376637441 topic="persistent://public/default/by-dev-rootcoord-dml_10"
time="2022-07-09T22:21:50+08:00" level=info msg="[Reconnected consumer to broker]" consumerID=9764 name=zzmwq subscription=by-dev-dataNode-30-434165452376637441 topic="persistent://public/default/by-dev-rootcoord-dml_10"
time="2022-07-09T22:21:50+08:00" level=info msg="[Created producer]" cnx="10.97.109.218:33064 -> 10.97.100.141:6650" producerID=19527 producer_name=pulsar-cluster-0-17485 topic="persistent://public/default/by-dev-rootcoord-delta_10"
time="2022-07-09T22:21:50+08:00" level=info msg="[Created producer]" cnx="10.97.109.218:58442 -> 10.97.101.168:6650" producerID=19528 producer_name=pulsar-cluster-1-19924 topic="persistent://public/default/by-dev-datacoord-timetick-channel"
time="2022-07-09T22:21:50+08:00" level=info msg="The consumer[9764] successfully unsubscribed" consumerID=9764 name=zzmwq subscription=by-dev-dataNode-30-434165452376637441 topic="persistent://public/default/by-dev-rootcoord-dml_10"
time="2022-07-09T22:21:50+08:00" level=info msg="Closing consumer=9764" consumerID=9764 name=zzmwq subscription=by-dev-dataNode-30-434165452376637441 topic="persistent://public/default/by-dev-rootcoord-dml_10"
time="2022-07-09T22:21:50+08:00" level=warning msg="[Failed to close consumer]" consumerID=9764 error="server error: MetadataError: Consumer not found" name=zzmwq subscription=by-dev-dataNode-30-434165452376637441 topic="persistent://public/default/by-dev-rootcoord-dml_10"
time="2022-07-09T22:21:50+08:00" level=info msg="[Closing producer]" producerID=19527 producer_name=pulsar-cluster-0-17485 topic="persistent://public/default/by-dev-rootcoord-delta_10"
time="2022-07-09T22:21:50+08:00" level=info msg="[Closed producer]" producerID=19527 producer_name=pulsar-cluster-0-17485 topic="persistent://public/default/by-dev-rootcoord-delta_10"
time="2022-07-09T22:21:50+08:00" level=info msg="[Closing producer]" producerID=19528 producer_name=pulsar-cluster-1-19924 topic="persistent://public/default/by-dev-datacoord-timetick-channel"
time="2022-07-09T22:21:50+08:00" level=info msg="[Closed producer]" producerID=19528 producer_name=pulsar-cluster-1-19924 topic="persistent://public/default/by-dev-datacoord-timetick-channel"
panic: All attempts results:
attempt #1:topic persistent://public/default/by-dev-rootcoord-dml_13, subscription by-dev-dataNode-30-434165452428804097: server error: MetadataError: Consumer not found
attempt #2:topic persistent://public/default/by-dev-rootcoord-dml_13, subscription by-dev-dataNode-30-434165452428804097: server error: MetadataError: Consumer not found
attempt #3:topic persistent://public/default/by-dev-rootcoord-dml_13, subscription by-dev-dataNode-30-434165452428804097: server error: MetadataError: Consumer not found
attempt #4:topic persistent://public/default/by-dev-rootcoord-dml_13, subscription by-dev-dataNode-30-434165452428804097: server error: MetadataError: Consumer not found
attempt #5:topic persistent://public/default/by-dev-rootcoord-dml_13, subscription by-dev-dataNode-30-434165452428804097: server error: MetadataError: Consumer not found
attempt #6:topic persistent://public/default/by-dev-rootcoord-dml_13, subscription by-dev-dataNode-30-434165452428804097: server error: MetadataError: Consumer not found
attempt #7:topic persistent://public/default/by-dev-rootcoord-dml_13, subscription by-dev-dataNode-30-434165452428804097: server error: MetadataError: Consumer not found
attempt #8:topic persistent://public/default/by-dev-rootcoord-dml_13, subscription by-dev-dataNode-30-434165452428804097: server error: MetadataError: Consumer not found
attempt #9:topic persistent://public/default/by-dev-rootcoord-dml_13, subscription by-dev-dataNode-30-434165452428804097: server error: MetadataError: Consumer not found
attempt #10:topic persistent://public/default/by-dev-rootcoord-dml_13, subscription by-dev-dataNode-30-434165452428804097: server error: MetadataError: Consumer not found
attempt #11:topic persistent://public/default/by-dev-rootcoord-dml_13, subscription by-dev-dataNode-30-434165452428804097: server error: MetadataError: Consumer not found


goroutine 56522138 [running]:
github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/pulsar.(*Consumer).Close.func1()
	/opt/milvus/internal/mq/msgstream/mqwrapper/pulsar/pulsar_consumer.go:135 +0x472
sync.(*Once).doSlow(0xca6ef7bc08, 0xc2e18f49e8)
	/usr/local/go/src/sync/once.go:68 +0xec
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:59
github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/pulsar.(*Consumer).Close(0xca6ef7bbd0)
	/opt/milvus/internal/mq/msgstream/mqwrapper/pulsar/pulsar_consumer.go:114 +0x65
github.com/milvus-io/milvus/internal/mq/msgstream.(*mqMsgStream).Close(0xca6867f200)
	/opt/milvus/internal/mq/msgstream/mq_msgstream.go:199 +0x1c8
github.com/milvus-io/milvus/internal/mq/msgstream.(*MqTtMsgStream).Close(0xca6867f200)
	/opt/milvus/internal/mq/msgstream/mq_msgstream.go:668 +0x45
github.com/milvus-io/milvus/internal/util/flowgraph.(*InputNode).Close(0xca77640720)
	/opt/milvus/internal/util/flowgraph/input_node.go:47 +0x49
github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Close(0xca50e3ad80)
	/opt/milvus/internal/util/flowgraph/node.go:130 +0x54
github.com/milvus-io/milvus/internal/util/flowgraph.(*TimeTickedFlowGraph).Close.func1()
	/opt/milvus/internal/util/flowgraph/flow_graph.go:93 +0xc5
sync.(*Once).doSlow(0xc83d4d4a88, 0xc2e18f4d00)
	/usr/local/go/src/sync/once.go:68 +0xec
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:59
github.com/milvus-io/milvus/internal/util/flowgraph.(*TimeTickedFlowGraph).Close(0xc83d4d4a80)
	/opt/milvus/internal/util/flowgraph/flow_graph.go:89 +0x65
github.com/milvus-io/milvus/internal/datanode.(*dataSyncService).close(0xc7c20b6780)
	/opt/milvus/internal/datanode/data_sync_service.go:137 +0x24a
github.com/milvus-io/milvus/internal/datanode.(*flowgraphManager).release(0xc000e55b30, 0xc359c6bef0, 0x2c)
	/opt/milvus/internal/datanode/flow_graph_manager.go:79 +0x1d2
github.com/milvus-io/milvus/internal/datanode.(*DataNode).tryToReleaseFlowgraph(0xc00006e900, 0xc359c6bef0, 0x2c)
	/opt/milvus/internal/datanode/data_node.go:422 +0x5e
github.com/milvus-io/milvus/internal/datanode.(*DataNode).handlePutEvent(0xc00006e900, 0xc70c60c340, 0xa1a, 0x45d8b40, 0x4a782e700)
	/opt/milvus/internal/datanode/data_node.go:409 +0xcb6
github.com/milvus-io/milvus/internal/datanode.(*channelEventManager).retryHandlePutEvent(0xc2e173e100, 0x1, 0xc359c6bef0, 0x2c, 0xa1a, 0xc70c60c340)
	/opt/milvus/internal/datanode/event_manager.go:88 +0x118
github.com/milvus-io/milvus/internal/datanode.(*channelEventManager).Run.func1(0xc2e173e100)
	/opt/milvus/internal/datanode/event_manager.go:70 +0x165
created by github.com/milvus-io/milvus/internal/datanode.(*channelEventManager).Run
	/opt/milvus/internal/datanode/event_manager.go:64 +0x3f
```

### Expected Behavior

datanode running healthily

**Comment by BUPTAnderson** [comment]
I have collected all logs of the cluster, download link is as follows:
链接: https://pan.baidu.com/s/158zMtXaKEIdH9CwbPlD9oQ?pwd=52sp 提取码: 52sp

**Comment by xiaofan-luan** [comment]
The reason is pulsar go client didn't throw pulsar.Result as expected.
They simple throw an error with string Consumer not found.
we check pulsar error but it doen't work, so after multiple retries datanode crashed.

We just check the error string for now.

**Comment by xiaofan-luan** [comment]
18207,18209 should fix the issue, clean it for now
