### ISSUE TITLE
[Bug]: [benchmark][cluster]Milvus 100m data load failed,raise an error"collection  has not been loaded to memory or load failed"

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#18232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.0-20220711-1c74adcf
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.1.0dev98
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server-instance
fouram-tag-no-clean-fnd8j-1
server-configmap
server-cluster-8c64m-querynode2
client-configmap
client-random-locust-search-filter-100m-ddl-r8-w2-replica2

```
fouram-tag-no-clean-fnd8j-1-etcd-0                               1/1     Running     0               13h   10.104.4.183   4am-node11   <none>           <none>
fouram-tag-no-clean-fnd8j-1-etcd-1                               1/1     Running     0               13h   10.104.6.139   4am-node13   <none>           <none>
fouram-tag-no-clean-fnd8j-1-etcd-2                               1/1     Running     0               13h   10.104.9.83    4am-node14   <none>           <none>
fouram-tag-no-clean-fnd8j-1-milvus-datacoord-6749dfd5c9-s9jf9    1/1     Running     1 (13h ago)     13h   10.104.4.175   4am-node11   <none>           <none>
fouram-tag-no-clean-fnd8j-1-milvus-datanode-547c4c5db8-sbjs5     1/1     Running     1 (13h ago)     13h   10.104.6.133   4am-node13   <none>           <none>
fouram-tag-no-clean-fnd8j-1-milvus-indexcoord-7ddd89b8b4-zkqkp   1/1     Running     1 (13h ago)     13h   10.104.4.174   4am-node11   <none>           <none>
fouram-tag-no-clean-fnd8j-1-milvus-indexnode-7d976584ff-rd9sc    1/1     Running     0               13h   10.104.1.182   4am-node10   <none>           <none>
fouram-tag-no-clean-fnd8j-1-milvus-proxy-65c899ddf6-hm2gp        1/1     Running     1 (13h ago)     13h   10.104.6.132   4am-node13   <none>           <none>
fouram-tag-no-clean-fnd8j-1-milvus-querycoord-7cf9bc7f9f-h2vkp   1/1     Running     1 (13h ago)     13h   10.104.9.74    4am-node14   <none>           <none>
fouram-tag-no-clean-fnd8j-1-milvus-querynode-5659866bb9-8lzwc    1/1     Running     1 (10h ago)     13h   10.104.5.120   4am-node12   <none>           <none>
fouram-tag-no-clean-fnd8j-1-milvus-querynode-5659866bb9-9554r    1/1     Running     0               13h   10.104.9.76    4am-node14   <none>           <none>
fouram-tag-no-clean-fnd8j-1-milvus-rootcoord-76b49c7c8c-gstps    1/1     Running     1 (13h ago)     13h   10.104.4.169   4am-node11   <none>           <none>
fouram-tag-no-clean-fnd8j-1-minio-0                              1/1     Running     0               13h   10.104.5.122   4am-node12   <none>           <none>
fouram-tag-no-clean-fnd8j-1-minio-1                              1/1     Running     0               13h   10.104.4.182   4am-node11   <none>           <none>
fouram-tag-no-clean-fnd8j-1-minio-2                              1/1     Running     0               13h   10.104.6.140   4am-node13   <none>           <none>
fouram-tag-no-clean-fnd8j-1-minio-3                              1/1     Running     0               13h   10.104.9.81    4am-node14   <none>           <none>
fouram-tag-no-clean-fnd8j-1-pulsar-bookie-0                      1/1     Running     0               13h   10.104.4.181   4am-node11   <none>           <none>
fouram-tag-no-clean-fnd8j-1-pulsar-bookie-1                      1/1     Running     0               13h   10.104.6.138   4am-node13   <none>           <none>
fouram-tag-no-clean-fnd8j-1-pulsar-bookie-2                      1/1     Running     0               13h   10.104.9.82    4am-node14   <none>           <none>
fouram-tag-no-clean-fnd8j-1-pulsar-bookie-init-qnrzv             0/1     Completed   0               13h   10.104.4.172   4am-node11   <none>           <none>
fouram-tag-no-clean-fnd8j-1-pulsar-broker-0                      1/1     Running     0               13h   10.104.9.75    4am-node14   <none>           <none>
fouram-tag-no-clean-fnd8j-1-pulsar-proxy-0                       1/1     Running     0               13h   10.104.4.171   4am-node11   <none>           <none>
fouram-tag-no-clean-fnd8j-1-pulsar-pulsar-init-rff28             0/1     Completed   0               13h   10.104.4.173   4am-node11   <none>           <none>
fouram-tag-no-clean-fnd8j-1-pulsar-recovery-0                    1/1     Running     0               13h   10.104.4.170   4am-node11   <none>           <none>
fouram-tag-no-clean-fnd8j-1-pulsar-zookeeper-0                   1/1     Running     0               13h   10.104.4.184   4am-node11   <none>           <none>
fouram-tag-no-clean-fnd8j-1-pulsar-zookeeper-1                   1/1     Running     0               13h   10.104.6.142   4am-node13   <none>           <none>
fouram-tag-no-clean-fnd8j-1-pulsar-zookeeper-2                   1/1     Running     0               13h   10.104.5.124   4am-node12   <none>           <none>
```

```
[2022-07-11 15:33:08,752] [   ERROR] - RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=collection sift_100m_128_l2 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-07-11 15:31:27.898957', 'RPC error': '2022-07-11 15:33:08.752486'}> (pymilvus.decorators:94)
[2022-07-11 15:33:08,753] [   ERROR] - RPC error: [load_collection], <MilvusException: (code=1, message=collection sift_100m_128_l2 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-07-11 15:31:27.448521', 'RPC error': '2022-07-11 15:33:08.753152'}> (pymilvus.decorators:94)
[2022-07-11 15:33:08,753] [   ERROR] - <MilvusException: (code=1, message=collection sift_100m_128_l2 has not been loaded to memory or load failed)> (milvus_benchmark.main:118)
[2022-07-11 15:33:08,756] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 87, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/locust.py", line 458, in prepare
    self.milvus.load_collection(replica_number=replica_number)
  File "/src/milvus_benchmark/client.py", line 50, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 495, in load_collection
    return self._milvus.load_collection(collection_name, **params)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/stub.py", line 195, in load_collection
    return handler.load_collection(collection_name=collection_name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 95, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 91, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 73, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 48, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 673, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 95, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 91, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 73, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 48, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 682, in wait_for_loading_collection
    return self._wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 711, in _wait_for_loading_collection
    progress = self.get_collection_loading_progress(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 690, in get_collection_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection sift_100m_128_l2 has not been loaded to memory or load failed)>
 (milvus_benchmark.main:119)
[2022-07-11 15:33:08,756] [   DEBUG] - {'_version': '0.1', '_type': 'metric', 'run_id': 1657549764, 'mode': 'local', 'server': <milvus_benchmark.metrics.models.server.Server object at 0x7f39e211a430>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware object at 0x7f39e0af4580>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7f39e0af41c0>, 'status': 'RUN_FAILED', 'err_message': '', 'collection': {'dimension': 128, 'metric_type': 'l2', 'dataset_name': 'sift_100m_128_l2', 'collection_size': 100000000, 'other_fields': 'float1', 'ni_per': 50000, 'shards_num': None}, 'index': {'index_type': 'ivf_sq8', 'index_param': {'nlist': 2048}}, 'search': None, 'run_params': {'task': {'types': [{'type': 'query', 'weight': 20, 'params': {'top_k': 10, 'nq': 10, 'search_param': {'nprobe': 16}, 'filters': [{'range': "{'range': {'float1': {'GT': -1.0, 'LT': collection_size * 0.5}}}"}]}}, {'type': 'load', 'weight': 1, 'params': {'replica_number': 2}}, {'type': 'get', 'weight': 10, 'params': {'ids_length': 10}}, {'type': 'scene_test', 'weight': 2}], 'connection_num': 1, 'clients_num': 20, 'spawn_rate': 2, 'during_time': '84h'}, 'connection_type': 'single'}, 'metrics': {'type': 'locust_random_performance', 'value': {}}, 'datetime': '2022-07-11 12:37:46.881794', 'type': 'metric'} (milvus_benchmark.metric.api:30)
```

**Comment by jennyli-z** [comment]
very urgent & important bug, many jobs is waiting the resource as the bug block the test.

**Comment by jingkl** [comment]
server-instance
benchmark-tag-no-clean-5cssg-1
server-configmap
server-cluster-8c64m-kafka
client-configmap
client-random-locust-100m-ddl-r8-w2



```
benchmark-tag-no-clean-5cssg-1-etcd-0                             1/1     Running     0          13h     10.97.17.95    qa-node014.zilliz.local   <none>           <none>
benchmark-tag-no-clean-5cssg-1-etcd-1                             1/1     Running     0          13h     10.97.16.206   qa-node013.zilliz.local   <none>           <none>
benchmark-tag-no-clean-5cssg-1-etcd-2                             1/1     Running     0          13h     10.97.16.205   qa-node013.zilliz.local   <none>           <none>
benchmark-tag-no-clean-5cssg-1-kafka-0                            1/1     Running     2          13h     10.97.5.160    qa-node003.zilliz.local   <none>           <none>
benchmark-tag-no-clean-5cssg-1-kafka-1                            1/1     Running     2          13h     10.97.18.218   qa-node017.zilliz.local   <none>           <none>
benchmark-tag-no-clean-5cssg-1-kafka-2                            1/1     Running     2          13h     10.97.13.55    qa-node010.zilliz.local   <none>           <none>
benchmark-tag-no-clean-5cssg-1-milvus-datacoord-6d7fbd5bc4jttf9   1/1     Running     0          13h     10.97.13.52    qa-node010.zilliz.local   <none>           <none>
benchmark-tag-no-clean-5cssg-1-milvus-datanode-69b8bcd8d9-784n5   1/1     Running     0          13h     10.97.20.189   qa-node018.zilliz.local   <none>           <none>
benchmark-tag-no-clean-5cssg-1-milvus-indexcoord-546db775bx7zxt   1/1     Running     0          13h     10.97.16.201   qa-node013.zilliz.local   <none>           <none>
benchmark-tag-no-clean-5cssg-1-milvus-indexnode-77b84589ddpl66m   1/1     Running     0          13h     10.97.16.202   qa-node013.zilliz.local   <none>           <none>
benchmark-tag-no-clean-5cssg-1-milvus-proxy-65d7bbf669-s95q7      1/1     Running     0          13h     10.97.13.53    qa-node010.zilliz.local   <none>           <none>
benchmark-tag-no-clean-5cssg-1-milvus-querycoord-668765c8fjt7r6   1/1     Running     0          13h     10.97.13.54    qa-node010.zilliz.local   <none>           <none>
benchmark-tag-no-clean-5cssg-1-milvus-querynode-6fb4cb79fd7rqxk   1/1     Running     0          13h     10.97.17.93    qa-node014.zilliz.local   <none>           <none>
benchmark-tag-no-clean-5cssg-1-milvus-rootcoord-d5d4c6dc8-ghvf5   1/1     Running     0          13h     10.97.13.51    qa-node010.zilliz.local   <none>           <none>
benchmark-tag-no-clean-5cssg-1-minio-0                            1/1     Running     0          13h     10.97.12.29    qa-node015.zilliz.local   <none>           <none>
benchmark-tag-no-clean-5cssg-1-minio-1                            1/1     Running     0          13h     10.97.12.30    qa-node015.zilliz.local   <none>           <none>
benchmark-tag-no-clean-5cssg-1-minio-2                            1/1     Running     0          13h     10.97.12.31    qa-node015.zilliz.local   <none>           <none>
benchmark-tag-no-clean-5cssg-1-minio-3                            1/1     Running     0          13h     10.97.12.34    qa-node015.zilliz.local   <none>           <none>
benchmark-tag-no-clean-5cssg-1-zookeeper-0                        1/1     Running     0          13h     10.97.18.217   qa-node017.zilliz.local   <none>           <none>
benchmark-tag-no-clean-5cssg-1-zookeeper-1                        1/1     Running     0          13h     10.97.5.159    qa-node003.zilliz.local   <none>           <none>
benchmark-tag-no-clean-5cssg-1-zookeeper-2                        1/1     Running     0          13h     10.97.13.56    qa-node010.zilliz.local   <none>           <none>
```

```
2022-07-11 15:51:17,963] [    INFO] - Start load collection (milvus_benchmark.runners.locust:456)
[2022-07-11 15:52:12,732] [   ERROR] - RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=collection sift_100m_128_l2 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-07-11 15:51:18.921498', 'RPC error': '2022-07-11 15:52:12.732660'}> (pymilvus.decorators:94)
[2022-07-11 15:52:12,733] [   ERROR] - RPC error: [load_collection], <MilvusException: (code=1, message=collection sift_100m_128_l2 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-07-11 15:51:17.964040', 'RPC error': '2022-07-11 15:52:12.733549'}> (pymilvus.decorators:94)
[2022-07-11 15:52:12,733] [   ERROR] - <MilvusException: (code=1, message=collection sift_100m_128_l2 has not been loaded to memory or load failed)> (milvus_benchmark.main:118)
[2022-07-11 15:52:12,736] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 87, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/locust.py", line 458, in prepare
    self.milvus.load_collection(replica_number=replica_number)
  File "/src/milvus_benchmark/client.py", line 50, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 495, in load_collection
    return self._milvus.load_collection(collection_name, **params)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 195, in load_collection
    return handler.load_collection(collection_name=collection_name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 95, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 91, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 73, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 48, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 673, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 95, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 91, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 73, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 48, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 682, in wait_for_loading_collection
    return self._wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 711, in _wait_for_loading_collection
    progress = self.get_collection_loading_progress(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 690, in get_collection_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection sift_100m_128_l2 has not been loaded to memory or load failed)>
 (milvus_benchmark.main:119)
```

**Comment by jiaoew1991** [comment]
![image](https://user-images.githubusercontent.com/2297455/178399686-748356ba-ad2d-4ca2-8fb4-8fd6f637aae8.png)
through the logs we can see the memory of Querynode was reached the quota, it can not load more segments into memory.

**Comment by jiaoew1991** [comment]
<img width="1400" alt="image" src="https://user-images.githubusercontent.com/2297455/178495797-2b1df8d8-bf0d-4a89-90a3-2b84f92daaf3.png">

<img width="851" alt="image" src="https://user-images.githubusercontent.com/2297455/178495345-ae41fb30-3a4a-42c4-9a8d-fb3925783fae.png">
the querynode pod's memory is about 50G, but the Go part is only 1G, most of the is used by CGO

**Comment by jingkl** [comment]
server-instance
benchmark-tag-no-clean-8hckl-1
server-configmap
server-cluster-8c64m-querynode2
client-configmap
client-random-locust-search-filter-100m-ddl-r8-w2-replica2
2.1.0-20220712-c3ddb1fe
pymilvus 2.1.0dev98

```

benchmark-tag-no-clean-8hckl-1-etcd-0                             1/1     Running     0          14h   10.97.16.48    qa-node013.zilliz.local   <none>           <none>
benchmark-tag-no-clean-8hckl-1-etcd-1                             1/1     Running     0          14h   10.97.17.49    qa-node014.zilliz.local   <none>           <none>
benchmark-tag-no-clean-8hckl-1-etcd-2                             1/1     Running     0          14h   10.97.17.50    qa-node014.zilliz.local   <none>           <none>
benchmark-tag-no-clean-8hckl-1-milvus-datacoord-6bcd69896bgrjxb   1/1     Running     0          14h   10.97.13.68    qa-node010.zilliz.local   <none>           <none>
benchmark-tag-no-clean-8hckl-1-milvus-datanode-57d96495d7-xd7tv   1/1     Running     0          14h   10.97.20.7     qa-node018.zilliz.local   <none>           <none>
benchmark-tag-no-clean-8hckl-1-milvus-indexcoord-7fd4cb6d47jgt5   1/1     Running     0          14h   10.97.13.65    qa-node010.zilliz.local   <none>           <none>
benchmark-tag-no-clean-8hckl-1-milvus-indexnode-69b78cfdcb8pqbt   1/1     Running     0          14h   10.97.20.10    qa-node018.zilliz.local   <none>           <none>
benchmark-tag-no-clean-8hckl-1-milvus-proxy-7978fcc8df-xx2fr      1/1     Running     0          14h   10.97.13.64    qa-node010.zilliz.local   <none>           <none>
benchmark-tag-no-clean-8hckl-1-milvus-querycoord-676fdb89dfqpnc   1/1     Running     0          14h   10.97.13.67    qa-node010.zilliz.local   <none>           <none>
benchmark-tag-no-clean-8hckl-1-milvus-querynode-55dc5c5d7dxs4sn   1/1     Running     0          14h   10.97.19.88    qa-node016.zilliz.local   <none>           <none>
benchmark-tag-no-clean-8hckl-1-milvus-querynode-55dc5c5d7dxshxr   1/1     Running     0          14h   10.97.20.8     qa-node018.zilliz.local   <none>           <none>
benchmark-tag-no-clean-8hckl-1-milvus-rootcoord-5bc69795cdbflk9   1/1     Running     0          14h   10.97.13.66    qa-node010.zilliz.local   <none>           <none>
benchmark-tag-no-clean-8hckl-1-minio-0                            1/1     Running     0          14h   10.97.16.44    qa-node013.zilliz.local   <none>           <none>
benchmark-tag-no-clean-8hckl-1-minio-1                            1/1     Running     0          14h   10.97.16.50    qa-node013.zilliz.local   <none>           <none>
benchmark-tag-no-clean-8hckl-1-minio-2                            1/1     Running     0          14h   10.97.16.49    qa-node013.zilliz.local   <none>           <none>
benchmark-tag-no-clean-8hckl-1-minio-3                            1/1     Running     0          14h   10.97.16.62    qa-node013.zilliz.local   <none>           <none>
benchmark-tag-no-clean-8hckl-1-pulsar-bookie-0                    1/1     Running     0          14h   10.97.16.60    qa-node013.zilliz.local   <none>           <none>
benchmark-tag-no-clean-8hckl-1-pulsar-bookie-1                    1/1     Running     0          14h   10.97.20.13    qa-node018.zilliz.local   <none>           <none>
benchmark-tag-no-clean-8hckl-1-pulsar-bookie-2                    1/1     Running     0          14h   10.97.16.64    qa-node013.zilliz.local   <none>           <none>
benchmark-tag-no-clean-8hckl-1-pulsar-bookie-init-5n6td           0/1     Completed   0          14h   10.97.3.56     qa-node001.zilliz.local   <none>           <none>
benchmark-tag-no-clean-8hckl-1-pulsar-broker-0                    1/1     Running     0          14h   10.97.16.37    qa-node013.zilliz.local   <none>           <none>
benchmark-tag-no-clean-8hckl-1-pulsar-proxy-0                     1/1     Running     0          14h   10.97.3.55     qa-node001.zilliz.local   <none>           <none>
benchmark-tag-no-clean-8hckl-1-pulsar-pulsar-init-w5hkv           0/1     Completed   0          14h   10.97.3.57     qa-node001.zilliz.local   <none>           <none>
benchmark-tag-no-clean-8hckl-1-pulsar-recovery-0                  1/1     Running     0          14h   10.97.18.207   qa-node017.zilliz.local   <none>           <none>
benchmark-tag-no-clean-8hckl-1-pulsar-zookeeper-0                 1/1     Running     0          14h   10.97.16.47    qa-node013.zilliz.local   <none>           <none>
benchmark-tag-no-clean-8hckl-1-pulsar-zookeeper-1                 1/1     Running     0          14h   10.97.3.59     qa-node001.zilliz.local   <none>           <none>
benchmark-tag-no-clean-8hckl-1-pulsar-zookeeper-2                 1/1     Running     0          14h   10.97.16.69    qa-node013.zilliz.local   <none>           <none>
```



```
[2022-07-12 16:10:26,608] [   ERROR] - RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=collection sift_100m_128_l2 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-07-12 16:07:38.441158', 'RPC error': '2022-07-12 16:10:26.608069'}> (pymilvus.decorators:94)
[2022-07-12 16:10:26,609] [   ERROR] - RPC error: [load_collection], <MilvusException: (code=1, message=collection sift_100m_128_l2 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-07-12 16:07:37.475839', 'RPC error': '2022-07-12 16:10:26.609314'}> (pymilvus.decorators:94)
[2022-07-12 16:10:26,609] [   ERROR] - <MilvusException: (code=1, message=collection sift_100m_128_l2 has not been loaded to memory or load failed)> (milvus_benchmark.main:118)
[2022-07-12 16:10:26,612] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 87, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/locust.py", line 458, in prepare
    self.milvus.load_collection(replica_number=replica_number)
  File "/src/milvus_benchmark/client.py", line 50, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 495, in load_collection
    return self._milvus.load_collection(collection_name, **params)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 195, in load_collection
    return handler.load_collection(collection_name=collection_name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 95, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 91, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 73, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 48, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 673, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 95, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 91, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 73, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 48, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 682, in wait_for_loading_collection
    return self._wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 711, in _wait_for_loading_collection
    progress = self.get_collection_loading_progress(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 690, in get_collection_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection sift_100m_128_l2 has not been loaded to memory or load failed)>
```

**Comment by jiaoew1991** [comment]
@jingkl pls verify it with pr https://github.com/milvus-io/milvus/pull/18269
/unassign

**Comment by jingkl** [comment]
image 2.1.0-20220714-e8ac3664
pymilvus 2.1.0dev98
Verified that no more errors are reported
