### ISSUE TITLE
[Bug]: Datacoord keep CrashLoopBackOff after minio pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#18270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220713-a47a414d
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/12268675/178762292-967e538c-2fe3-483a-97b0-b906c4ebdab1.png)
```
[2022/07/13 12:14:25.106 +00:00] [INFO] [datacoord/session_manager.go:152] ["success to execute compaction"] [node=13] [planID=434559900645064706]
[2022/07/13 12:14:25.153 +00:00] [INFO] [datacoord/compaction_trigger.go:256] ["time cost of generating global compaction"] [planID=434559900720824321] ["time cost"=92] [collectionID=0] [channel=by-dev-rootcoord-dml_6_434559693652230145v0] [partitionID=434559693652230146]
[2022/07/13 12:14:25.337 +00:00] [INFO] [datacoord/garbage_collector.go:157] ["scan result"] [valid=210] [missing=140] ["removed keys"="[]"]
[2022/07/13 12:14:25.362 +00:00] [INFO] [datacoord/session_manager.go:152] ["success to execute compaction"] [node=13] [planID=434559900720824321]
[2022/07/13 12:14:26.272 +00:00] [INFO] [datacoord/services.go:788] ["receive complete compaction request"] [planID=434559900720824321] [segmentID=434559900798156801]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x19feded]

goroutine 279 [running]:
github.com/milvus-io/milvus/internal/datacoord.(*meta).CompleteMergeCompaction(0xc00018ff40, 0xc0012cc800, 0x7, 0x8, 0xc00053bb80, 0xc000da7610, 0x0, 0x0)
	/go/src/github.com/milvus-io/milvus/internal/datacoord/meta.go:807 +0x52d
github.com/milvus-io/milvus/internal/datacoord.(*compactionPlanHandler).handleMergeCompactionResult(...)
	/go/src/github.com/milvus-io/milvus/internal/datacoord/compaction.go:232
github.com/milvus-io/milvus/internal/datacoord.(*compactionPlanHandler).completeCompaction(0xc00053b880, 0xc00053bb80, 0x0, 0x0)
	/go/src/github.com/milvus-io/milvus/internal/datacoord/compaction.go:206 +0x47a
github.com/milvus-io/milvus/internal/datacoord.(*Server).CompleteCompaction(0xc0000b6000, 0x31ac858, 0xc0012a3d10, 0xc00053bb80, 0x2db49a0, 0x0, 0x31e0970)
	/go/src/github.com/milvus-io/milvus/internal/datacoord/services.go:807 +0x738
github.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).CompleteCompaction(0xc00009c300, 0x31ac858, 0xc0012a3d10, 0xc00053bb80, 0xc00009c300, 0x3175440, 0xc001429900)
	/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:296 +0x52
github.com/milvus-io/milvus/internal/proto/datapb._DataCoord_CompleteCompaction_Handler.func1(0x31ac858, 0xc0012a3d10, 0x2d06400, 0xc00053bb80, 0x2e113a9, 0xd, 0x2e6fc8a, 0x2f)
	/go/src/github.com/milvus-io/milvus/internal/proto/datapb/data_coord.pb.go:5143 +0x89
github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1(0x31ac858, 0xc0012a3a70, 0x2d06400, 0xc00053bb80, 0xc000ceffe0, 0xc0004819e0, 0xc000d80ba0, 0x75f4c6, 0x2c633c0, 0xc0012a3a70)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38 +0x119
github.com/milvus-io/milvus/internal/proto/datapb._DataCoord_CompleteCompaction_Handler(0x2db49a0, 0xc00009c300, 0x31ac858, 0xc0012a3a70, 0xc000b18d80, 0xc000b20d90, 0x31ac858, 0xc0012a3a70, 0xc000128900, 0x2f8)
	/go/src/github.com/milvus-io/milvus/internal/proto/datapb/data_coord.pb.go:5145 +0x150
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000b3a540, 0x31c5cb8, 0xc0004ccb60, 0xc000caa5a0, 0xc000b25ef0, 0x44c8488, 0x0, 0x0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1282 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000b3a540, 0x31c5cb8, 0xc0004ccb60, 0xc000caa5a0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1616 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0009f87b0, 0xc000b3a540, 0x31c5cb8, 0xc0004ccb60, 0xc000caa5a0)
	/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:921 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:919 +0x1fd

```

### Expected Behavior

all test cases passed

### Steps To Reproduce

```markdown
see https://github.com/zhuwenxing/milvus/runs/7320269427?check_suite_focus=true
```

### Milvus Log

failed job: https://github.com/zhuwenxing/milvus/runs/7320269427?check_suite_focus=true
log: https://github.com/zhuwenxing/milvus/suites/7338159561/artifacts/297310154

**Comment by soothing-rain** [comment]
The fix is easy. But why do you think the segment start position is empty? @sunby 

https://github.com/milvus-io/milvus/blob/master/internal/datacoord/meta.go#L807

**Comment by xiaofan-luan** [comment]
> The fix is easy. But why do you think the segment start position is empty? @sunby
> 
> https://github.com/milvus-io/milvus/blob/master/internal/datacoord/meta.go#L807

might because the insert is not large enough to do a save bin log path?

**Comment by zhuwenxing** [comment]
This reproduced again, any progress?
failed job: http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test-kafka/detail/chaos-test-kafka/665/pipeline
log:[artifacts-minio-pod-kill-665-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9137077/artifacts-minio-pod-kill-665-server-logs.tar.gz)

**Comment by zhuwenxing** [comment]
Reproduced in GitHub action
failed job: https://github.com/milvus-io/milvus/runs/7415702986?check_suite_focus=true
log: https://github.com/milvus-io/milvus/suites/7427352618/artifacts/303375456

**Comment by zhuwenxing** [comment]
Not reproduced recently
