### ISSUE TITLE
[Bug]: load failed for timeout reporting "Deadline Exceeded"

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#18287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.0 latest (94b16a1a)
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.1.0.dev83
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

load failed for timeout reporting "Deadline Exceeded"

### Expected Behavior

load successfully

### Steps To Reproduce

```markdown
Running nightly:
https://ci.milvus.io:18080/jenkins/blue/rest/organizations/jenkins/pipelines/milvus-release-nightly/runs/154/nodes/215/steps/239/log/?start=0
```

### Milvus Log

1. milvus log:  [milvus-distributed-pulsar-154-pymilvus-e2e-logs.tar.gz](https://ci.milvus.io:18080/jenkins/job/milvus-release-nightly/154/artifact/milvus-distributed-pulsar-154-pymilvus-e2e-logs.tar.gz)
2. For failed case 1: "test_delete.py::TestDeleteOperation::test_delete_from_partitions_with_same_ids"
(1) collection name: delete_D1fQPEqQ
(2) Failed time: [2022-07-14T23:50:31.107Z] [gw3] [ 21%] FAILED testcases/test_delete.py::TestDeleteOperation::test_delete_from_partitions_with_same_ids 
(3)test logs:
```
[2022-07-15T00:50:13.077Z] [2022-07-14 23:49:59 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 20], kwargs: {} (api_request.py:55)

[2022-07-15T00:50:13.077Z] [2022-07-14 23:50:19 - ERROR - pymilvus.decorators]: grpc RpcError: [load_collection], <_MultiThreadedRendezvous: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded>, <Time:{'RPC start': '2022-07-14 23:49:59.712377', 'gRPC error': '2022-07-14 23:50:19.713290'}> (decorators.py:86)

[2022-07-15T00:50:13.077Z] [2022-07-14 23:50:19 - ERROR - ci_test]: Traceback (most recent call last):

[2022-07-15T00:50:13.077Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 44, in handler

[2022-07-15T00:50:13.077Z]     return func(self, *args, **kwargs)

[2022-07-15T00:50:13.077Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 87, in handler

[2022-07-15T00:50:13.077Z]     raise e

[2022-07-15T00:50:13.077Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 75, in handler

[2022-07-15T00:50:13.077Z]     return func(*args, **kwargs)

[2022-07-15T00:50:13.077Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 687, in load_collection

[2022-07-15T00:50:13.077Z]     response = rf.result()

[2022-07-15T00:50:13.077Z]   File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 744, in result

[2022-07-15T00:50:13.077Z]     raise self

[2022-07-15T00:50:13.077Z] grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:

[2022-07-15T00:50:13.077Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2022-07-15T00:50:13.077Z] 	details = "Deadline Exceeded"

[2022-07-15T00:50:13.077Z] 	debug_error_string = "{"created":"@1657842619.712917304","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":81,"grpc_status":4}"

[2022-07-15T00:50:13.077Z] >

[2022-07-15T00:50:13.077Z] 

[2022-07-15T00:50:13.077Z] During handling of the above exception, another exception occurred:

[2022-07-15T00:50:13.077Z] 

[2022-07-15T00:50:13.077Z] Traceback (most recent call last):

[2022-07-15T00:50:13.077Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper

[2022-07-15T00:50:13.077Z]     res = func(*args, **kwargs)

[2022-07-15T00:50:13.077Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 56, in api_request

[2022-07-15T00:50:13.077Z]     return func(*arg, **kwargs)

[2022-07-15T00:50:13.077Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 469, in load

[2022-07-15T00:50:13.077Z]     conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)

[2022-07-15T00:50:13.077Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 55, in handler

[2022-07-15T00:50:13.077Z]     raise MilvusException(Status.UNEXPECTED_ERROR, "rpc timeout")

[2022-07-15T00:50:13.077Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=rpc timeout)>

[2022-07-15T00:50:13.077Z]  (api_request.py:35)
```

3. For failed case 2: "test_index.py::TestNewIndexBase::test_create_index_search_with_query_vectors_ip"
(1)collection name: index_uU7vgteR
(2) Failed time:  [2022-07-14T23:50:41.060Z] [gw2] [ 21%] FAILED testcases/test_index.py::TestNewIndexBase::test_create_index_search_with_query_vectors_ip 
(3) test logs: 
```
[2022-07-15T00:50:13.079Z] [2022-07-14 23:50:19 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 20], kwargs: {} (api_request.py:55)
[2022-07-15T00:50:13.079Z] [2022-07-14 23:50:39 - ERROR - pymilvus.decorators]: grpc RpcError: [load_collection], <_MultiThreadedRendezvous: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded>, <Time:{'RPC start': '2022-07-14 23:50:19.735060', 'gRPC error': '2022-07-14 23:50:39.736586'}> (decorators.py:86)
[2022-07-15T00:50:13.079Z] [2022-07-14 23:50:39 - ERROR - ci_test]: Traceback (most recent call last):
[2022-07-15T00:50:13.079Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 44, in handler
[2022-07-15T00:50:13.079Z]     return func(self, *args, **kwargs)
[2022-07-15T00:50:13.079Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 87, in handler
[2022-07-15T00:50:13.079Z]     raise e
[2022-07-15T00:50:13.079Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 75, in handler
[2022-07-15T00:50:13.079Z]     return func(*args, **kwargs)
[2022-07-15T00:50:13.079Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 687, in load_collection
[2022-07-15T00:50:13.079Z]     response = rf.result()
[2022-07-15T00:50:13.080Z]   File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 744, in result
[2022-07-15T00:50:13.080Z]     raise self
[2022-07-15T00:50:13.080Z] grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
[2022-07-15T00:50:13.080Z] 	status = StatusCode.DEADLINE_EXCEEDED
[2022-07-15T00:50:13.080Z] 	details = "Deadline Exceeded"
[2022-07-15T00:50:13.080Z] 	debug_error_string = "{"created":"@1657842639.735945590","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":81,"grpc_status":4}"
```

**Comment by weiliu1031** [comment]
root cause: 
pulsar broker lost connection with zk,  and the recovery cost about two minutes(23:49:59 ~23:51:19), which means the pulsar borker are unavailable in that period。 and the watchDmTask in loadCollection request hang on until pulsar broker is online。

and the loadCollection operation just wait for about 20s, then it got timeout.

**Comment by xiaofan-luan** [comment]
> root cause: pulsar broker lost connection with zk, and the recovery cost about two minutes(23:49:59 ~23:51:19), which means the pulsar borker are unavailable in that period。 and the watchDmTask in loadCollection request hang on until pulsar broker is online。
> 
> and the loadCollection operation just wait for about 20s, then it got timeout.

Milvus should be recovered after pulsar recover, does that meet expectation?

**Comment by weiliu1031** [comment]
> > root cause: pulsar broker lost connection with zk, and the recovery cost about two minutes(23:49:59 ~23:51:19), which means the pulsar borker are unavailable in that period。 and the watchDmTask in loadCollection request hang on until pulsar broker is online。
> > and the loadCollection operation just wait for about 20s, then it got timeout.
> 
> Milvus should be recovered after pulsar recover, does that meet expectation?

milvus service did recovered, service is back.

**Comment by yanliang567** [comment]
@binbinlv does it reproduce recently

**Comment by binbinlv** [comment]
No, it has not been reproduced recently.

**Comment by binbinlv** [comment]
This issue is the same with #18846, so close this one.
