### ISSUE TITLE
[Bug]: [benchmark][standalone]Milvus load 10m data failed ，raise an error"StatusCode.UNAVAILABLE，failed to connect to all addresses"

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#18327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.0-20220714-94b16a1a
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.1.0dev98
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server-instance
fouram-mkpkn-1
server-configmap
server-single-8c16m
client-configmap
client-random-locust-10m-ddl-r8-w2-2h-noindex

<img width="1348" alt="截屏2022-07-19 15 00 30" src="https://user-images.githubusercontent.com/34296482/179686674-04483de5-fbd1-4f8b-bafe-f083e4f45123.png">

```
[2022-07-19 06:36:10,717] [ WARNING] - [93mRetry [wait_for_loading_collection] No.7 in 12.8s, retry reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:68)
[2022-07-19 06:36:23,518] [   ERROR] - RPC error: [wait_for_loading_collection], <MilvusUnavaliableException: (code=1, message=server unavaliable: Retry run out of 7 retry times)>, <Time:{'RPC start': '2022-07-19 06:35:25.212694', 'RPC error': '2022-07-19 06:36:23.518513'}> (pymilvus.decorators:94)
[2022-07-19 06:36:23,519] [   ERROR] - RPC error: [load_collection], <MilvusUnavaliableException: (code=1, message=server unavaliable: Retry run out of 7 retry times)>, <Time:{'RPC start': '2022-07-19 06:35:25.108777', 'RPC error': '2022-07-19 06:36:23.519121'}> (pymilvus.decorators:94)
[2022-07-19 06:36:23,519] [   ERROR] - <MilvusUnavaliableException: (code=1, message=server unavaliable: Retry run out of 7 retry times)> (milvus_benchmark.main:118)
[2022-07-19 06:36:23,520] [   ERROR] - Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 48, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 682, in wait_for_loading_collection
    return self._wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 711, in _wait_for_loading_collection
    progress = self.get_collection_loading_progress(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 687, in get_collection_loading_progress
    response = future.result()
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1658212583.518167795","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3260,"referenced_errors":[{"created":"@1658212583.518166808","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":167,"grpc_status":14}]}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 87, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/locust.py", line 458, in prepare
    self.milvus.load_collection(replica_number=replica_number)
  File "/src/milvus_benchmark/client.py", line 51, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 565, in load_collection
    return self._milvus.load_collection(collection_name, **params)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/stub.py", line 195, in load_collection
    return handler.load_collection(collection_name=collection_name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 95, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 91, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 73, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 48, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 673, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 95, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 91, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 64, in handler
    raise MilvusUnavaliableException(Status.UNEXPECTED_ERROR, f"server unavaliable: {timeout_msg}")
pymilvus.exceptions.MilvusUnavaliableException: <MilvusUnavaliableException: (code=1, message=server unavaliable: Retry run out of 7 retry times)>
 (milvus_benchmark.main:119)
```

### Anything else?

client-random-locust-10m-ddl-r8-w2-2h-noindex

```
{
	"config.yaml": "locust_random_performance:
		  collections:
		    -
		      collection_name: sift_10m_128_l2
		      ni_per: 50000
		      build_index: false
		      index_type: ivf_sq8
		      index_param:
		        nlist: 2048
		      task:
		        types:
		          -
		            type: query
		            weight: 8
		            params:
		              top_k: 10
		              nq: 10
		              search_param:
		                nprobe: 16
		          -
		            type: load
		            weight: 1
		          -
		            type: get
		            weight: 8
		            params:
		              ids_length: 10
		          -
		            type: scene_test
		            weight: 2
		        connection_num: 1
		        clients_num: 20
		        spawn_rate: 2
		        during_time: 2h
		"
}
```

**Comment by jingkl** [comment]
server-instance
fouram-lr5r4-1
server-configmap
server-single-8c16m-ssd
client-configmap
client-random-locust-10m-ddl-r8-w2-2h-noindex

2.1.0-20220719-42ee90c7
pymilvus 2.1.0dev103


```
fouram-lr5r4-1-etcd-0                                            1/1     Running       0               2m7s    10.104.1.39    4am-node10   <none>           <none>
fouram-lr5r4-1-milvus-standalone-5fcbbb9d9f-7zfjc                1/1     Running       0               2m7s    10.104.1.40    4am-node10   <none>           <none>
fouram-lr5r4-1-minio-5d76b685bc-bjj7t                            1/1     Running       0               2m7s    10.104.5.75    4am-node12   <none>           <none>
```

```
[2022-07-19 07:28:02,275] [ WARNING] - [93m[wait_for_loading_collection] retry:4, cost: 0.27s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:69)
[2022-07-19 07:28:02,546] [ WARNING] - [93m[wait_for_loading_collection] retry:5, cost: 0.81s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:69)
[2022-07-19 07:28:03,358] [ WARNING] - [93m[wait_for_loading_collection] retry:6, cost: 2.43s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:69)
[2022-07-19 07:28:05,789] [ WARNING] - [93m[wait_for_loading_collection] retry:7, cost: 7.290000000000001s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:69)
[2022-07-19 07:28:13,081] [ WARNING] - [93m[wait_for_loading_collection] retry:8, cost: 21.870000000000005s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:69)
[2022-07-19 07:28:34,953] [ WARNING] - [93m[wait_for_loading_collection] retry:9, cost: 60s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:69)
[2022-07-19 07:29:34,955] [ WARNING] - [93m[wait_for_loading_collection] retry:10, cost: 60s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:69)
[2022-07-19 07:30:34,959] [   ERROR] - RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=collection sift_10m_128_l2 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-07-19 07:27:53.454496', 'RPC error': '2022-07-19 07:30:34.959640'}> (pymilvus.decorators:95)
[2022-07-19 07:30:34,960] [   ERROR] - RPC error: [load_collection], <MilvusException: (code=1, message=collection sift_10m_128_l2 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-07-19 07:27:53.397449', 'RPC error': '2022-07-19 07:30:34.960219'}> (pymilvus.decorators:95)
[2022-07-19 07:30:34,960] [   ERROR] - <MilvusException: (code=1, message=collection sift_10m_128_l2 has not been loaded to memory or load failed)> (milvus_benchmark.main:118)
[2022-07-19 07:30:34,961] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 87, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/locust.py", line 458, in prepare
    self.milvus.load_collection(replica_number=replica_number)
  File "/src/milvus_benchmark/client.py", line 51, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 565, in load_collection
    return self._milvus.load_collection(collection_name, **params)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/stub.py", line 195, in load_collection
    return handler.load_collection(collection_name=collection_name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 96, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 92, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 48, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 673, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 96, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 92, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 48, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 682, in wait_for_loading_collection
    return self._wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 711, in _wait_for_loading_collection
    progress = self.get_collection_loading_progress(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 690, in get_collection_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection sift_10m_128_l2 has not been loaded to memory or load failed)>
 (milvus_benchmark.main:119)
```

<img width="1338" alt="截屏2022-07-19 15 36 35" src="https://user-images.githubusercontent.com/34296482/179694037-ceb28b65-eb6f-4c5f-bba3-186cea62f39b.png">

**Comment by xige-16** [comment]
usageAfterLoad is based on binlog.logsize statistics, but the logsize recorded by datacoord is the compressed size, which will cause the querynode's estimate of the segmentsize to be smaller, and it will also lead to higher load concurrency. 
At this time, the memory may not be enough.
```
[2022/07/19 07:27:53.770 +00:00] [DEBUG] [querynode/segment_loader.go:808] ["predict memory usage while loading (in MiB)"] [usage=6161] [usageAfterLoad=3248]
[2022/07/19 07:27:53.771 +00:00] [DEBUG] [querynode/segment_loader.go:172] ["start to load segments in parallel"] [segmentNum=14] [concurrencyLevel=8]
```

**Comment by xige-16** [comment]
releated pr: https://github.com/milvus-io/milvus/pull/18336

**Comment by jingkl** [comment]
server-instance
fouram-248b6-1
server-configmap
server-single-8c16m
client-configmap
client-random-locust-10m-ddl-r8-w2-2h-noindex

2.1.0-20220719-69aea00c
pymilvus 2.1.0dev103
The memory keeps going up, noindex's 10m of data was only 5g originally, so why is the memory used up to about 11g？

<img width="1378" alt="截屏2022-07-20 11 38 39" src="https://user-images.githubusercontent.com/34296482/179891367-e0928081-1df7-41f1-9795-85d1674085b3.png">

**Comment by jingkl** [comment]
server-instance
fouram-phrj8-1
server-configmap
server-single-8c16m
client-configmap
client-random-locust-10m-ddl-r8-w2-2h
2.1.0-20220719-69aea00c
pymilvus 2.1.0dev103

Creating indexes is also a gradual increase in memory as well

<img width="1382" alt="截屏2022-07-21 10 24 21" src="https://user-images.githubusercontent.com/34296482/180116569-a0ac3ae5-8f28-4cc2-90e8-bb1b68f3d6ac.png">

**Comment by jingkl** [comment]
This issue does not currently exist, so close issue first
