### ISSUE TITLE
[Bug]: Search raise error after docker restart when upgrading Milvus from 2.0.2 to 2.1  fininshed if waiting time is 3 minutes

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#18379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.2 --> 2.1.0-20220722-6521f6da
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

see https://github.com/zhuwenxing/milvus/runs/7478024677?check_suite_focus=true
search after docker restart
```
Search...
attempt #2:fail to get shard leaders from QueryCoord: no replica available
attempt #3:fail to get shard leaders from QueryCoord: no replica available
attempt #4:fail to get shard leaders from QueryCoord: no replica available
attempt #5:fail to get shard leaders from QueryCoord: no replica available
attempt #6:fail to get shard leaders from QueryCoord: no replica available
attempt #7:fail to get shard leaders from QueryCoord: no replica available
attempt #8:context deadline exceeded
)>, <Time:{'RPC start': '2022-07-23 02:44:29.006972', 'RPC error': '2022-07-23 02:44:39.030406'}>
Traceback (most recent call last):
  File "scripts/action_after_upgrade.py", line 98, in <module>
    task_1(data_size, host)
  File "scripts/action_after_upgrade.py", line 19, in task_1
    load_and_search(prefix)
  File "/home/runner/work/milvus/milvus/tests/python_client/deploy/scripts/utils.py", line 1[59](https://github.com/zhuwenxing/milvus/runs/7478024677?check_suite_focus=true#step:14:60), in load_and_search
    res = c.search(
  File "/opt/hostedtoolcache/Python/3.8.13/x[64](https://github.com/zhuwenxing/milvus/runs/7478024677?check_suite_focus=true#step:14:65)/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 712, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 96, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 92, in handler
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 48, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 446, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 410, in _execute_search_requests
    raise pre_err
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 401, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:
attempt #1:fail to get shard leaders from QueryCoord: no replica available
attempt #2:fail to get shard leaders from QueryCoord: no replica available
attempt #3:fail to get shard leaders from QueryCoord: no replica available
attempt #4:fail to get shard leaders from QueryCoord: no replica available
attempt #5:fail to get shard leaders from QueryCoord: no replica available
attempt #6:fail to get shard leaders from QueryCoord: no replica available
attempt #7:fail to get shard leaders from QueryCoord: no replica available
attempt #8:context deadline exceeded
```

### Expected Behavior

all test cases passed

### Steps To Reproduce

```markdown
see https://github.com/zhuwenxing/milvus/runs/7478024677?check_suite_focus=true
```

### Milvus Log

failed job: https://github.com/zhuwenxing/milvus/runs/7478024677?check_suite_focus=true
log: https://github.com/zhuwenxing/milvus/runs/7478024677?check_suite_focus=true

log is in `third deploy` dir 

### Anything else?

related issue 

* https://github.com/milvus-io/milvus/issues/18377

* https://github.com/milvus-io/milvus/issues/18316

**Comment by zhuwenxing** [comment]
If the waiting time is longer, this issue will not happen,so remove critical label
