### ISSUE TITLE
[Bug]: List collection raise `Server unavailable` after waiting  120s when Milvus cluster reinstall finished

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#18380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.0-20220722-6521f6da
- Deployment mode(standalone or cluster): cluster by docker-compose
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

running the second test after reinstalling
```
[list_collections] retry:4, cost: 0.27s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>
[list_collections] retry:5, cost: 0.81s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>
[list_collections] retry:6, cost: 2.43s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>
[list_collections] retry:7, cost: 7.290000000000001s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>
[list_collections] retry:8, cost: 21.870000000000005s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>
[list_collections] retry:9, cost: 60s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>
[list_collections] retry:10, cost: 60s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>
RPC error: [list_collections], <MilvusUnavaliableException: (code=1, message=server unavaliable: Retry run out of 10 retry times)>, <Time:{'RPC start': '2022-07-23 04:07:03.956110', 'RPC error': '2022-07-23 04:09:36.927093'}>
data size: 3000
List collections...
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 48, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 237, in list_collections
    response = rf.result()
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "internal: Milvus Proxy is not ready yet. please wait"
	debug_error_string = "{"created":"@1658549376.926861624","description":"Error received from peer ipv4:127.0.0.1:[19](https://github.com/zhuwenxing/milvus/runs/7478489014?check_suite_focus=true#step:11:20)530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"internal: Milvus Proxy is not ready yet. please wait","grpc_status":14}"
>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "scripts/action_after_reinstall.py", line 43, in <module>
    task_1(data_size, host)
  File "scripts/action_after_reinstall.py", line 13, in task_1
    get_collections(prefix)
  File "/home/runner/work/milvus/milvus/tests/python_client/deploy/scripts/utils.py", line 59, in get_collections
    col_list = filter_collections_by_prefix(prefix)
  File "/home/runner/work/milvus/milvus/tests/python_client/deploy/scripts/utils.py", line [21](https://github.com/zhuwenxing/milvus/runs/7478489014?check_suite_focus=true#step:11:22), in filter_collections_by_prefix
    col_list = list_collections()
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pymilvus/orm/utility.py", line 4[27](https://github.com/zhuwenxing/milvus/runs/7478489014?check_suite_focus=true#step:11:28), in list_collections
    return _get_connection(using).list_collections(timeout=timeout)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 96, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 92, in handler
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 64, in handler
    raise MilvusUnavaliableException(Status.UNEXPECTED_ERROR, f"server unavaliable: {timeout_msg}")
pymilvus.exceptions.MilvusUnavaliableException: <MilvusUnavaliableException: (code=1, message=server unavaliable: Retry run out of 10 retry times)>
Error: Process completed with exit code 1.
```

### Expected Behavior

all test cases passed

### Steps To Reproduce

```markdown
see https://github.com/zhuwenxing/milvus/runs/7478489014?check_suite_focus=true
```

### Milvus Log

failed job: https://github.com/zhuwenxing/milvus/runs/7478489014?check_suite_focus=true
log: https://github.com/zhuwenxing/milvus/suites/7486835334/artifacts/307228110

### Anything else?

I have run another test that changed the waiting time to 180s, and then this issue seems not to happen

see https://github.com/zhuwenxing/milvus/actions/runs/2722570840

**Comment by zhuwenxing** [comment]
So the point is with this image, the waiting time for service available is longer than before

**Comment by zhuwenxing** [comment]
not reproduced yet, so close it.
