### ISSUE TITLE
[Bug]: [benchmark][standalone]Milvus load 50m data failed, raise an error"syncTimestamp Failed:context deadline exceeded"

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#18398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.0-20220723-1e038a75
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):2.1.0dev103
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server-instance
fouram-cluster-cron-9mjrz-1
server-configmap
server-single-32c128m
client-configmap
client-get-local50m-512

server:
```
fouram-cluster-cron-9mjrz-1-etcd-0                               1/1     Running     0               111s    10.104.9.110   4am-node14   <none>
     <none>
fouram-cluster-cron-9mjrz-1-milvus-standalone-6d5b9c5898-glvbn   1/1     Running     0               111s    10.104.5.189   4am-node12   <none>
     <none>
fouram-cluster-cron-9mjrz-1-minio-68db9885f6-hbzrh               1/1     Running     0               111s    10.104.5.185   4am-node12   <none>
     <none>
```

```
[2022-07-25 04:28:06,480] [   ERROR] - RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=syncTimestamp Failed:context deadline exceeded)>, <Time:{'RPC start': '2022-07-25 04:27:50.453416', 'RPC error': '2022-07-25 04:28:06.480617'}> (pymilvus.decorators:95)
[2022-07-25 04:28:06,480] [   ERROR] - RPC error: [load_collection], <MilvusException: (code=1, message=syncTimestamp Failed:context deadline exceeded)>, <Time:{'RPC start': '2022-07-25 04:27:50.079745', 'RPC error': '2022-07-25 04:28:06.480830'}> (pymilvus.decorators:95)
[2022-07-25 04:28:06,480] [   ERROR] - <MilvusException: (code=1, message=syncTimestamp Failed:context deadline exceeded)> (milvus_benchmark.main:118)
[2022-07-25 04:28:06,481] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 87, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/get.py", line 131, in prepare
    self.milvus.load_collection(replica_number=replica_number, timeout=1200)
  File "/src/milvus_benchmark/client.py", line 51, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 571, in load_collection
    return self._milvus.load_collection(collection_name, **params)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/stub.py", line 195, in load_collection
    return handler.load_collection(collection_name=collection_name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 96, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 92, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 48, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 673, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 96, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 92, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 48, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 682, in wait_for_loading_collection
    return self._wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 711, in _wait_for_loading_collection
    progress = self.get_collection_loading_progress(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 690, in get_collection_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=syncTimestamp Failed:context deadline exceeded)>
 (milvus_benchmark.main:119)

```
standalone memory:
<img width="1389" alt="截屏2022-07-25 14 10 11" src="https://user-images.githubusercontent.com/34296482/180709860-e981f9d3-e3db-4aa3-96d1-14e01a1d575e.png">

### Anything else?

client-get-local50m-512:

```
{
	"config.yaml": "insert_get_performance:
		  collections:
		    -
		      milvus:
		        db_config.primary_path: /test/milvus/db_data_011/local_50m_512_l2
		      collection_name: local_50m_512_l2
		      ni_per: 50000
		      build_index: false
		      index_type: ivf_sq8
		      index_param:
		        nlist: 1024
		      ids_length_list:
		        [1, 100, 10000]
		"
}
```

**Comment by xiaofan-luan** [comment]
could you check whether reduce concurrency help on this issue?

**Comment by yah01** [comment]
> could you check whether reduce concurrency help on this issue?

This should help, according to the logs, the concurrency level for this request is 30, which is too high.

**Comment by xiaofan-luan** [comment]
> > could you check whether reduce concurrency help on this issue?
> 
> This should help, according to the logs, the concurrency level for this request is 30, which is too high.

how did we calculate the number 30?

**Comment by yah01** [comment]
> > > could you check whether reduce concurrency help on this issue?
> > 
> > 
> > This should help, according to the logs, the concurrency level for this request is 30, which is too high.
> 
> how did we calculate the number 30?

In this case, this single request contains 30 segments, the segment loader predicts memory usage for this request with:
predict = sum{segment.size} + max_segment_size * level * factor
which level is the concurrency level, and the factor is 3.0 by default.
the level is checked with this formula from min(segment_num, cpuPoolSize), goes the half of it if failed. For this, it passed the check for the first time.

**Comment by xiaofan-luan** [comment]
> > > > could you check whether reduce concurrency help on this issue?
> > > 
> > > 
> > > This should help, according to the logs, the concurrency level for this request is 30, which is too high.
> > 
> > 
> > how did we calculate the number 30?
> 
> In this case, this single request contains 30 segments, the segment loader predicts memory usage for this request with: predict = sum{segment.size} + max_segment_size * level * factor
> 
> which level is the concurrency level, and the factor is 3.0 by default. the level is checked with this formula from min(segment_num, cpuPoolSize), goes the half of it if failed. For this, it passed the check for the first time.

so the restriction is predict < physical machine memory?

**Comment by xiaofan-luan** [comment]
sum{segment.size}  is the estimation or real memory usage?

**Comment by yah01** [comment]
> 

used_memory + predict < total_memory * limit_factor

which limit_factor is 0.9 by default.

**Comment by xiaofan-luan** [comment]
cause segment.size may not be accurate enough?

**Comment by yah01** [comment]
> sum{segment.size} is the estimation or real memory usage?

It is calculated with `LogSize` field from binlogs, which may be not accurate

**Comment by jingkl** [comment]
2.1.0-20220727-7169256c
pymilvus 2.1.0dev103

**Comment by jingkl** [comment]
Verified that the problem has been fixed, so close the issue
