### ISSUE TITLE
[Bug]: grpc RpcError: [has_collection], <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>,

### ISSUE THREAD

**Issue by w5688414** [milvus-io/milvus#18462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):2.02
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
(base) root@instance-3bwob41y-03 milvus_update # python hello_milvus.py

=== start connecting to Milvus     ===

grpc RpcError: [has_collection], <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>, <Time:{'RPC start': '2022-07-29 21:39:11.966820', 'gRPC error': '2022-07-29 21:39:11.967853'}>
grpc RpcError: [has_collection], <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>, <Time:{'RPC start': '2022-07-29 21:39:12.969089', 'gRPC error': '2022-07-29 21:39:12.969910'}>
grpc RpcError: [has_collection], <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>, <Time:{'RPC start': '2022-07-29 21:39:13.971147', 'gRPC error': '2022-07-29 21:39:13.971972'}>
grpc RpcError: [has_collection], <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>, <Time:{'RPC start': '2022-07-29 21:39:14.973219', 'gRPC error': '2022-07-29 21:39:14.974049'}>
```

here is my docker compose file:

```
      1 version: '3.5'
      2
      3 services:
      4   etcd:
      5     container_name: milvus-etcd
      6     image: quay.io/coreos/etcd:v3.5.0
      7     environment:
      8       - ETCD_AUTO_COMPACTION_MODE=revision
      9       - ETCD_AUTO_COMPACTION_RETENTION=1000
     10       - ETCD_QUOTA_BACKEND_BYTES=4294967296
     11     volumes:
     12       - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
     13     command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
     14
     15   minio:
     16     container_name: milvus-minio
     17     image: minio/minio:RELEASE.2022-03-17T06-34-49Z
     18     environment:
     19       MINIO_ACCESS_KEY: minioadmin
     20       MINIO_SECRET_KEY: minioadmin
     21     volumes:
     22       - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
     23     command: minio server /minio_data
     24     healthcheck:
     25       test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
     26       interval: 30s
     27       timeout: 20s
     28       retries: 3
     29
     30   standalone:
     31     container_name: milvus-standalone
     32     image: milvusdb/milvus:v2.1.0
     33     command: ["milvus", "run", "standalone"]
     34     environment:
     35       ETCD_ENDPOINTS: etcd:2379
     36       MINIO_ADDRESS: minio:9000
     37     volumes:
     38       - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
     39     ## ports:
     40     ##   - "8530:8530"
     41     depends_on:
     42       - "etcd"
     43       - "minio"
     44     network_mode: host
     45 networks:
     46   default:
     47     name: milvus
```

docker ps log is:

```
          Name                         Command                  State             Ports
----------------------------------------------------------------------------------------------
21d08e959606_milvus-etcd    etcd -advertise-client-url ...   Up             2379/tcp, 2380/tcp
a5fdb9dca423_milvus-minio   /usr/bin/docker-entrypoint ...   Up (healthy)   9000/tcp
milvus-standalone           /tini -- milvus run standalone   Up
```

### Steps To Reproduce

```markdown
1.https://milvus.io/docs/v2.1.x/install_standalone-docker.md install milvus from docker
2. modify docker-compose.yml
3. restart milvus
4. go to milvus container, and change milvus defult port 19530 to 8530 
5. restart milvus-standalonne
6. modify corresponding port and run hello_milvus.py and the error occurs
```

**Comment by yanliang567** [comment]
@w5688414 thank you for the issue, could you please use docker-compose logs > milvus.log to export the logs.

/assign @w5688414 
/unassign

**Comment by w5688414** [comment]
[milvus.log](https://github.com/milvus-io/milvus/files/9227998/milvus.log)
 here is the log

**Comment by yanliang567** [comment]
@LoveEachDay could you please help on this issue?
/assign @LoveEachDay

**Comment by LoveEachDay** [comment]
```
 30   standalone:
 31     container_name: milvus-standalone
 32     image: milvusdb/milvus:v2.1.0
 33     command: ["milvus", "run", "standalone"]
 34     environment:
 35       ETCD_ENDPOINTS: etcd:2379
 36       MINIO_ADDRESS: minio:9000
 37     volumes:
 38       - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
 39     ## ports:
 40     ##   - "8530:8530"
 41     depends_on:
 42       - "etcd"
 43       - "minio"
 44     network_mode: host
 45 networks:
 46   default:
 47     name: milvus
```
You cannot use `network_mode: host` here, remove this setting. That's why the dns query failed. 
If you want to expose milvus service, just add expose ports in the `ports` section.

/unassign 
/assign @w5688414

**Comment by w5688414** [comment]
if i just modify the ports, I cannot connect the milvus, here is the log for using hello_milvus.py.

```
Traceback (most recent call last):
  File "hello_milvus.py", line 32, in <module>
    connections.connect("default", host="0.0.0.0", port="8530")
  File "/home/.../miniconda3/envs/paddlenlp/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 262, in connect
    connect_milvus(**kwargs, password=password)
  File "/home/chenzeyu01/miniconda3/envs/paddlenlp/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 233, in connect_milvus
    gh._wait_for_channel_ready()
  File "/home/.../miniconda3/envs/paddlenlp/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 118, in _wait_for_channel_ready
    raise MilvusException(Status.CONNECT_FAILED, f'Fail connecting to server on {self._address}. Timeout')
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on 0.0.0.0:8530. Timeout)>
```
