### ISSUE TITLE
[Bug]: [e2e] failed to get failed to get segment when run `test_create_index_multithread`

### ISSUE THREAD

**Issue by jennyli-z** [milvus-io/milvus#18474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-18472/2/pipeline/142
part of error message
```

[2022-08-01T03:36:16.392Z] [2022-08-01 03:36:03 - ERROR - pymilvus.decorators]: RPC error: [create_index], <MilvusException: (code=1, message=CreateIndex failed: failed to get segment 434982082049474561)>, <Time:{'RPC start': '2022-08-01 03:35:58.905187', 'RPC error': '2022-08-01 03:36:03.646536'}> (decorators.py:95)

[2022-08-01T03:36:16.392Z] [2022-08-01 03:36:03 - ERROR - ci_test]: Traceback (most recent call last):

[2022-08-01T03:36:16.392Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2022-08-01T03:36:16.392Z]     res = func(*args, **_kwargs)

[2022-08-01T03:36:16.392Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2022-08-01T03:36:16.392Z]     return func(*arg, **kwargs)

[2022-08-01T03:36:16.392Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 1078, in create_index

[2022-08-01T03:36:16.392Z]     timeout=timeout, **kwargs)

[2022-08-01T03:36:16.392Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 96, in handler

[2022-08-01T03:36:16.392Z]     raise e

[2022-08-01T03:36:16.392Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 92, in handler

[2022-08-01T03:36:16.392Z]     return func(*args, **kwargs)

[2022-08-01T03:36:16.392Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler

[2022-08-01T03:36:16.392Z]     raise e

[2022-08-01T03:36:16.393Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 48, in handler

[2022-08-01T03:36:16.393Z]     return func(self, *args, **kwargs)

[2022-08-01T03:36:16.393Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 585, in create_index

[2022-08-01T03:36:16.393Z]     raise MilvusException(status.error_code, status.reason)

[2022-08-01T03:36:16.393Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=CreateIndex failed: failed to get segment 434982082049474561)>

[2022-08-01T03:36:16.393Z]  (api_request.py:39)

[2022-08-01T03:36:16.393Z] [2022-08-01 03:36:03 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=CreateIndex failed: failed to get segment 434982082049474561)> (api_request.py:40)

[2022-08-01T03:36:16.393Z] [2022-08-01 03:36:03 - ERROR - ci_test]: Traceback (most recent call last):

[2022-08-01T03:36:16.393Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/util_pymilvus.py", line 1112, in run

[2022-08-01T03:36:16.393Z]     super(MyThread, self).run()

[2022-08-01T03:36:16.393Z]   File "/usr/local/lib/python3.6/threading.py", line 864, in run

[2022-08-01T03:36:16.393Z]     self._target(*self._args, **self._kwargs)

[2022-08-01T03:36:16.393Z]   File "/home/jenkins/agent/workspace/tests/python_client/testcases/test_index.py", line 563, in build

[2022-08-01T03:36:16.393Z]     collection_w.create_index(ct.default_float_vec_field_name, default_index_params)

[2022-08-01T03:36:16.393Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/wrapper.py", line 33, in inner_wrapper

[2022-08-01T03:36:16.393Z]     res, result = func(*args, **kwargs)

[2022-08-01T03:36:16.393Z]   File "/home/jenkins/agent/workspace/tests/python_client/base/collection_wrapper.py", line 230, in create_index

[2022-08-01T03:36:16.393Z]     field_name=field_name, index_params=index_params, **kwargs).run()

[2022-08-01T03:36:16.393Z]   File "/home/jenkins/agent/workspace/tests/python_client/check/func_check.py", line 33, in run

[2022-08-01T03:36:16.393Z]     result = self.assert_succ(self.succ, True)

[2022-08-01T03:36:16.393Z]   File "/home/jenkins/agent/workspace/tests/python_client/check/func_check.py", line 84, in assert_succ

[2022-08-01T03:36:16.393Z]     assert actual is expect

[2022-08-01T03:36:16.393Z] AssertionError

[2022-08-01T03:36:16.393Z]  (util_pymilvus.py:1115)
```

### Expected Behavior

passed the case

### Milvus Log

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-18472/2/artifacts

**Comment by jennyli-z** [comment]
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/8/pipeline also in nightly

**Comment by xiaofan-luan** [comment]
/assign @longjiquan 
just need to make sure if this is due to compaction. Once the fix the refactoring the rootcoord this should no longer be a issue.
