### ISSUE TITLE
[Bug]: Server unavaliable while inserting data into multi shards collection

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#18485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.1.0
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: dataNode.resource.limit.cpu: 6
- GPU: 
- Others:
```

### Current Behavior

```python
    def test_issue_18480(self):
        # connect
        self._connect()

        # collection fields and schema
        int_fields = cf.gen_int64_field(name="pk", is_primary=True)
        timestam_fields = cf.gen_double_field(name="timestam")
        vec_fields = cf.gen_float_vec_field(name="feature", dim=3840)
        fields = [int_fields, timestam_fields, vec_fields]
        schema, _ = ApiCollectionSchemaWrapper().init_collection_schema(fields=fields, auto_id=True)

        # create collection with 16 shard_num
        for i in range(20):
              collection_w = self.init_collection_wrap(name=cf.gen_unique_str(f"issue_"), schema=schema, shards_num=16)

        collections, _ = self.utility_wrap.list_collections()
        collection_w = ApiCollectionWrapper()
        for c in collections:
            collection_w.init_collection(name=c)

            for i in range(5):
                df = pd.DataFrame({
                    "timestam": pd.Series(data=[np.double(i) for i in range(0, 1000)], dtype="double"),
                    "feature": cf.gen_vectors(1000, dim=3840)
                })
                insert_res, _ = collection_w.insert(df, timeout=120)
            log.debug(collection_w.num_entities)

            collection_w.load(timeout=120)
            collection_w.query(expr=f"pk in {insert_res.primary_keys[0:10]}", timeout=120)
            default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
            collection_w.search(cf.gen_vectors(2, dim=3840), "feature",
                                default_search_params, 10, timeout_decorator=120)
```

Client exception:
```
[2022-08-01 19:02:12,404 - DEBUG - ci_test]: (api_response) : <Collection>:
-------------
<name>: issue__iQtUGjha
<partitions>: [{"name": "_default", "collection_name": "issue__iQtUGjha", "description": ""}]
<description>:
<schema>: {
  auto_id: True
  description:
  fields: [{
    name: pk
    description:
    type: 5
    is_primary: True
    auto_id: True......  (api_request.py:27)
[2022-08-01 19:02:13,222 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [     timestam                                            feature
0         0.0  [0.026547804668946236, 0.016443410173252505, 0...
1         1.0  [0.012490799184715237, 0.0008050827156197791, ...
2         2.0  [0.015066098713371667, 0.010100728612544307, 0...
3         3.0  [0.012933082823743877, 0......, kwargs: {'timeout': 120} (api_request.py:55)
[2022-08-01 19:36:17,375 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 44, in handler
    return func(self, *args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 87, in handler
    raise e
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 75, in handler
    return func(*args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 365, in bulk_insert
    raise err
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 355, in bulk_insert
    response = rf.result()
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
    status = StatusCode.UNAVAILABLE
    details = "Operation timed out"
    debug_error_string = "{"created":"@1659353777.371930000","description":"Error received from peer ipv4:10.100.31.101:19530","file":"src/core/lib/surface/call.cc","file_line":967,"grpc_message":"Operation timed out","grpc_status":14}"
>
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nausicca/projects/milvus/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
    res = func(*args, **kwargs)
  File "/Users/nausicca/projects/milvus/tests/python_client/utils/api_request.py", line 56, in api_request
    return func(*arg, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 550, in insert
    res = conn.bulk_insert(self._name, entities, partition_name, ids=None, timeout=timeout, schema=schema_dict, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 57, in handler
    raise MilvusUnavaliableException(Status.UNEXPECTED_ERROR, "server unavaliable")
pymilvus.exceptions.MilvusUnavaliableException: <MilvusUnavaliableException: (code=1, message=server unavaliable)>
 (api_request.py:35)
[2022-08-01 19:36:17,376 - ERROR - ci_test]: (api_response) : <MilvusUnavaliableException: (code=1, message=server unavaliable)> (api_request.py:36)
FAILED
```

Client log:
[client.log](https://github.com/milvus-io/milvus/files/9234444/client.log)

Server logs: 
[mic_logs.tar.gz](https://github.com/milvus-io/milvus/files/9234446/mic_logs.tar.gz)

**Comment by yanliang567** [comment]
@ThreadDao did any milvus pods crash?

**Comment by ThreadDao** [comment]
> @ThreadDao did any milvus pods crash?

No. So I guess this is a timeout problem?

**Comment by zhagnlu** [comment]
![image](https://user-images.githubusercontent.com/11935707/182993511-65e09017-ebdc-44b2-8fd5-da86e15768bd.png)
from the proxy log, the program use sdk will check collection and partition info before insert, but hang for more than 1 hours and insert request not be send to proxy,  something wrong between client and proxy, from the warning, maybe connection network problems and have grpc error, but no detailed logs.

**Comment by zhagnlu** [comment]
I try this code locally for lots of times to catch more details, but it fails to reproduce this error. may it is related with network situation, so just keep watch now

**Comment by zhagnlu** [comment]
No other error found under other role like datanode, querynode etc. It is caused by python client and proxy.  for more detail, I try this code locally for lots of times to catch more info, but it fails to reproduce this error. may it is related with network situation, so just keep watching it
