### ISSUE TITLE
[Bug]: Data node crash

### ISSUE THREAD

**Issue by WeiDong-Shi** [milvus-io/milvus#18515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.0
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.0
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 64C / 256G
- GPU: 
- Others:
```

### Current Behavior

I crashed one of the five data nodes inexplicably without writing.

### Milvus Log

```text
[2022/08/03 06:56:58.881 +00:00] [DEBUG] [datanode/flow_graph_insert_buffer_node.go:97] ["IBN timetick log"] [from=2022/08/03 05:59:39.275 +00:00] [to=2022/08/03 06:02:59.127 +00:00] [elapsed=3m19.852s] [start=435029640288665601] [end=435029692678668289] [vChannelName=by-dev-rootcoord-dml_152_435027467403264001v3]
[2022/08/03 06:56:59.187 +00:00] [DEBUG] [datanode/flow_graph_insert_buffer_node.go:97] ["IBN timetick log"] [from=2022/08/03 05:59:38.525 +00:00] [to=2022/08/03 06:02:58.326 +00:00] [elapsed=3m19.801s] [start=435029640092057601] [end=435029692468690945] [vChannelName=by-dev-rootcoord-dml_153_435027467403264001v4]
[2022/08/03 06:56:59.336 +00:00] [DEBUG] [datanode/flow_graph_dd_node.go:287] ["DDNode sent delta timeTick"] [collectionID=435027467403264001] [ts=435029706466918401] [ts_p=2022/08/03 06:03:51.725 +00:00] [channel=by-dev-rootcoord-dml_152_435027467403264001v3]
[2022/08/03 06:57:00.695 +00:00] [DEBUG] [datanode/flow_graph_insert_buffer_node.go:97] ["IBN timetick log"] [from=2022/08/03 06:02:59.325 +00:00] [to=2022/08/03 06:06:19.125 +00:00] [elapsed=3m19.8s] [start=435029692730572803] [end=435029745106944001] [vChannelName=by-dev-rootcoord-dml_152_435027467403264001v3]
[2022/08/03 06:57:01.078 +00:00] [DEBUG] [datanode/flow_graph_insert_buffer_node.go:97] ["IBN timetick log"] [from=2022/08/03 06:02:58.531 +00:00] [to=2022/08/03 06:06:18.325 +00:00] [elapsed=3m19.794s] [start=435029692522430465] [end=435029744897228801] [vChannelName=by-dev-rootcoord-dml_153_435027467403264001v4]
[2022/08/03 06:57:02.505 +00:00] [ERROR] [pulsar/pulsar_consumer.go:136] ["failed to unsubscribe"] [subscription=by-dev-dataNode-62-435027173251743745] [error="All attempts results:\nattempt #1:topic persistent://public/default/by-dev-rootcoord-dml_142, subscription by-dev-dataNode-62-435027173251743745: request timed out\nattempt #2:topic persistent://public/default/by-dev-rootcoord-dml_142, subscription by-dev-dataNode-62-435027173251743745: request timed out\nattempt #3:topic persistent://public/default/by-dev-rootcoord-dml_142, subscription by-dev-dataNode-62-435027173251743745: request timed out\nattempt #4:topic persistent://public/default/by-dev-rootcoord-dml_142, subscription by-dev-dataNode-62-435027173251743745: connection closed\nattempt #5:topic persistent://public/default/by-dev-rootcoord-dml_142, subscription by-dev-dataNode-62-435027173251743745: connection closed\nattempt #6:topic persistent://public/default/by-dev-rootcoord-dml_142, subscription by-dev-dataNode-62-435027173251743745: connection closed\nattempt #7:topic persistent://public/default/by-dev-rootcoord-dml_142, subscription by-dev-dataNode-62-435027173251743745: connection closed\nattempt #8:topic persistent://public/default/by-dev-rootcoord-dml_142, subscription by-dev-dataNode-62-435027173251743745: connection closed\nattempt #9:topic persistent://public/default/by-dev-rootcoord-dml_142, subscription by-dev-dataNode-62-435027173251743745: connection closed\nattempt #10:topic persistent://public/default/by-dev-rootcoord-dml_142, subscription by-dev-dataNode-62-435027173251743745: connection closed\nattempt #11:topic persistent://public/default/by-dev-rootcoord-dml_142, subscription by-dev-dataNode-62-435027173251743745: connection closed\n"] [stack="github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/pulsar.(*Consumer).Close.func1\n\t/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/pulsar/pulsar_consumer.go:136\nsync.(*Once).doSlow\n\t/usr/local/go/src/sync/once.go:68\nsync.(*Once).Do\n\t/usr/local/go/src/sync/once.go:59\ngithub.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/pulsar.(*Consumer).Close\n\t/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/pulsar/pulsar_consumer.go:115\ngithub.com/milvus-io/milvus/internal/mq/msgstream.(*mqMsgStream).Close\n\t/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_msgstream.go:200\ngithub.com/milvus-io/milvus/internal/mq/msgstream.(*MqTtMsgStream).Close\n\t/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_msgstream.go:669\ngithub.com/milvus-io/milvus/internal/util/flowgraph.(*InputNode).Close\n\t/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/input_node.go:47\ngithub.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Close\n\t/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:130\ngithub.com/milvus-io/milvus/internal/util/flowgraph.(*TimeTickedFlowGraph).Close.func1\n\t/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/flow_graph.go:93\nsync.(*Once).doSlow\n\t/usr/local/go/src/sync/once.go:68\nsync.(*Once).Do\n\t/usr/local/go/src/sync/once.go:59\ngithub.com/milvus-io/milvus/internal/util/flowgraph.(*TimeTickedFlowGraph).Close\n\t/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/flow_graph.go:89\ngithub.com/milvus-io/milvus/internal/datanode.(*dataSyncService).close\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/data_sync_service.go:150\ngithub.com/milvus-io/milvus/internal/datanode.(*flowgraphManager).release\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_manager.go:79\ngithub.com/milvus-io/milvus/internal/datanode.(*DataNode).tryToReleaseFlowgraph\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/data_node.go:423\ngithub.com/milvus-io/milvus/internal/datanode.(*DataNode).handlePutEvent\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/data_node.go:385\ngithub.com/milvus-io/milvus/internal/datanode.(*channelEventManager).retryHandlePutEvent\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:88\ngithub.com/milvus-io/milvus/internal/datanode.(*channelEventManager).Run.func1\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:70"]
panic: All attempts results:
attempt #1:topic persistent://public/default/by-dev-rootcoord-dml_142, subscription by-dev-dataNode-62-435027173251743745: request timed out
attempt #2:topic persistent://public/default/by-dev-rootcoord-dml_142, subscription by-dev-dataNode-62-435027173251743745: request timed out
attempt #3:topic persistent://public/default/by-dev-rootcoord-dml_142, subscription by-dev-dataNode-62-435027173251743745: request timed out
attempt #4:topic persistent://public/default/by-dev-rootcoord-dml_142, subscription by-dev-dataNode-62-435027173251743745: connection closed
attempt #5:topic persistent://public/default/by-dev-rootcoord-dml_142, subscription by-dev-dataNode-62-435027173251743745: connection closed
attempt #6:topic persistent://public/default/by-dev-rootcoord-dml_142, subscription by-dev-dataNode-62-435027173251743745: connection closed
attempt #7:topic persistent://public/default/by-dev-rootcoord-dml_142, subscription by-dev-dataNode-62-435027173251743745: connection closed
attempt #8:topic persistent://public/default/by-dev-rootcoord-dml_142, subscription by-dev-dataNode-62-435027173251743745: connection closed
attempt #9:topic persistent://public/default/by-dev-rootcoord-dml_142, subscription by-dev-dataNode-62-435027173251743745: connection closed
attempt #10:topic persistent://public/default/by-dev-rootcoord-dml_142, subscription by-dev-dataNode-62-435027173251743745: connection closed
attempt #11:topic persistent://public/default/by-dev-rootcoord-dml_142, subscription by-dev-dataNode-62-435027173251743745: connection closed


goroutine 283 [running]:
github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/pulsar.(*Consumer).Close.func1()
	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/pulsar/pulsar_consumer.go:137 +0x472
sync.(*Once).doSlow(0xc0058fa3f8, 0xc006e4a9e8)
	/usr/local/go/src/sync/once.go:68 +0xec
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:59
github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/pulsar.(*Consumer).Close(0xc0058fa3c0)
	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/pulsar/pulsar_consumer.go:115 +0x65
github.com/milvus-io/milvus/internal/mq/msgstream.(*mqMsgStream).Close(0xc000ede200)
	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_msgstream.go:200 +0x1c8
github.com/milvus-io/milvus/internal/mq/msgstream.(*MqTtMsgStream).Close(0xc000ede200)
	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_msgstream.go:669 +0x45
github.com/milvus-io/milvus/internal/util/flowgraph.(*InputNode).Close(0xc0049e0780)
	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/input_node.go:47 +0x49
github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Close(0xc0042ded80)
	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:130 +0x54
github.com/milvus-io/milvus/internal/util/flowgraph.(*TimeTickedFlowGraph).Close.func1()
	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/flow_graph.go:93 +0xc5
sync.(*Once).doSlow(0xc000c8c4a8, 0xc006e4ad00)
	/usr/local/go/src/sync/once.go:68 +0xec
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:59
github.com/milvus-io/milvus/internal/util/flowgraph.(*TimeTickedFlowGraph).Close(0xc000c8c4a0)
	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/flow_graph.go:89 +0x65
github.com/milvus-io/milvus/internal/datanode.(*dataSyncService).close(0xc0005dde10)
	/go/src/github.com/milvus-io/milvus/internal/datanode/data_sync_service.go:150 +0x24a
github.com/milvus-io/milvus/internal/datanode.(*flowgraphManager).release(0xc000039500, 0xc0083fe210, 0x2d)
	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_manager.go:79 +0x1d2
github.com/milvus-io/milvus/internal/datanode.(*DataNode).tryToReleaseFlowgraph(0xc0006f7800, 0xc0083fe210, 0x2d)
	/go/src/github.com/milvus-io/milvus/internal/datanode/data_node.go:423 +0x5e
github.com/milvus-io/milvus/internal/datanode.(*DataNode).handlePutEvent(0xc0006f7800, 0xc00749a8c0, 0x3, 0x5a5b280, 0x4a80a4945)
	/go/src/github.com/milvus-io/milvus/internal/datanode/data_node.go:385 +0x13f1
github.com/milvus-io/milvus/internal/datanode.(*channelEventManager).retryHandlePutEvent(0xc0001b4e40, 0x1, 0xc0083fe210, 0x2d, 0x3, 0xc00749a8c0)
	/go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:88 +0x118
github.com/milvus-io/milvus/internal/datanode.(*channelEventManager).Run.func1(0xc0001b4e40)
	/go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:70 +0x165
created by github.com/milvus-io/milvus/internal/datanode.(*channelEventManager).Run
	/go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:64 +0x3f
```

**Comment by yanliang567** [comment]
Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
/assign @WeiDong-Shi 
/unassign

**Comment by gaofengliu0** [comment]
I have the same problem

**Comment by xiaofan-luan** [comment]
> I have the same problem

you can unsubscribe the topic mannaully for recovery
