### ISSUE TITLE
[Bug]: Create collection failed with error message `CreateCollection failed: send dd create collection req failed, error = Broker: Invalid replication factor`

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#18510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220802-6e78314
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.0.dev103
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Create collection failed when run `test_e2e.py` after installation
```
23:22:56  [2022-08-02 15:22:55 - ERROR - pymilvus.client.grpc_handler]: error_code: UnexpectedError
23:22:56  reason: "CreateCollection failed: send dd create collection req failed, error = Broker: Invalid replication factor"
23:22:56   (grpc_handler.py:196)
23:22:56  [2022-08-02 15:22:55 - ERROR - pymilvus.decorators]: RPC error: [create_collection], <MilvusException: (code=1, message=CreateCollection failed: send dd create collection req failed, error = Broker: Invalid replication factor)>, <Time:{'RPC start': '2022-08-02 15:22:53.345592', 'RPC error': '2022-08-02 15:22:55.537485'}> (decorators.py:95)
23:22:56  [2022-08-02 15:22:55 - ERROR - ci_test]: Traceback (most recent call last):
23:22:56    File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
23:22:56      res = func(*args, **_kwargs)
23:22:56    File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
23:22:56      return func(*arg, **kwargs)
23:22:56    File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 139, in __init__
23:22:56      consistency_level=consistency_level)
23:22:56    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 96, in handler
23:22:56      raise e
23:22:56    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 92, in handler
23:22:56      return func(*args, **kwargs)
23:22:56    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 74, in handler
23:22:56      raise e
23:22:56    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 48, in handler
23:22:56      return func(self, *args, **kwargs)
23:22:56    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 197, in create_collection
23:22:56      raise MilvusException(status.error_code, status.reason)
23:22:56  pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=CreateCollection failed: send dd create collection req failed, error = Broker: Invalid replication factor)>
23:22:56   (api_request.py:39)
23:22:56  [2022-08-02 15:22:55 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=CreateCollection failed: send dd create collection req failed, error = Broker: Invalid replication factor)> (api_request.py:40)
```

### Expected Behavior

All test cases passed

### Steps To Reproduce

```markdown
1. install milvus
2. run [test_e2e.py](https://github.com/milvus-io/milvus/blob/master/tests/python_client/testcases/test_e2e.py)
```

### Milvus Log

failed job: chaos-test-kafka/48
log:
[artifacts-indexnode-pod-failure-48-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/9247427/artifacts-indexnode-pod-failure-48-server-logs.1.tar.gz)

[artifacts-indexnode-pod-failure-48-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9247429/artifacts-indexnode-pod-failure-48-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
failed job:chaos-test-kafka/71/
log:
[artifacts-indexcoord-pod-failure-71-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9256369/artifacts-indexcoord-pod-failure-71-server-logs.tar.gz)
[artifacts-indexcoord-pod-failure-71-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9256371/artifacts-indexcoord-pod-failure-71-pytest-logs.tar.gz)

**Comment by jiaoew1991** [comment]
@zhuwenxing could you confirm the config of kafka is correct ? from the kafka's log we can find lots of Unknown host error 
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/2297455/182839926-ee73b983-ca4e-4bcb-ab13-bc8c16f6bda0.png">

**Comment by zhuwenxing** [comment]
![image](https://user-images.githubusercontent.com/12268675/182843905-848ce372-ddaa-44f6-8fde-3cfa05d4a170.png)
all tests using the same config, so the config of Kafka should be OK.

Maybe there is a thing that needs to be concerned about, three pods of Kafka all restarted during deployment before test_e2e.

![image](https://user-images.githubusercontent.com/12268675/182844729-181e2f3e-9e83-4687-836b-619a5e89ec30.png)

**Comment by zhuwenxing** [comment]
The config of Kafka is 
```
kafka:
  enabled: false
  name: kafka
  replicaCount: 3
  defaultReplicationFactor: 2
```

**Comment by zhuwenxing** [comment]
A new failed job: [/chaos-test-kafka/detail/chaos-test-kafka/86](https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka/detail/chaos-test-kafka/86/pipeline)

[artifacts-querycoord-pod-kill-86-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9266568/artifacts-querycoord-pod-kill-86-pytest-logs.tar.gz)
[artifacts-querycoord-pod-kill-86-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9266572/artifacts-querycoord-pod-kill-86-server-logs.tar.gz)

although three pods have restarted, they are all running and ready before running `test_e2e.py`
![image](https://user-images.githubusercontent.com/12268675/183030160-958a7a1f-5beb-41c6-b2c9-f6e88731cf2f.png)

**Comment by zhuwenxing** [comment]
@LoveEachDay 
Please help to have a look. It seems Kafka is not ready though pods are all running as shown

**Comment by yanliang567** [comment]
@jiaoew1991 any updates?

**Comment by LoveEachDay** [comment]
@zhuwenxing Why set the `defaultReplicationFactor` to 2? 

> The config of Kafka is
> 
> ```
> kafka:
>   enabled: false
>   name: kafka
>   replicaCount: 3
>   defaultReplicationFactor: 2
> ```

**Comment by zhuwenxing** [comment]
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka/detail/chaos-test-kafka/234/pipeline

[artifacts-rootcoord-pod-failure-234-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9286635/artifacts-rootcoord-pod-failure-234-server-logs.tar.gz)
[artifacts-rootcoord-pod-failure-234-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9286641/artifacts-rootcoord-pod-failure-234-pytest-logs.tar.gz)

In this failed job, creating a collection works well, but when inserting data, this issue happened.

```
10:33:40  [2022-08-09 02:33:40 - ERROR - pymilvus.decorators]: RPC error: [bulk_insert], <MilvusException: (code=1, message=Broker: Invalid replication factor)>, <Time:{'RPC start': '2022-08-09 02:33:40.682375', 'RPC error': '2022-08-09 02:33:40.761537'}> (decorators.py:95)
10:33:40  [2022-08-09 02:33:40 - ERROR - ci_test]: Traceback (most recent call last):
10:33:40    File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
10:33:40      res = func(*args, **_kwargs)
10:33:40    File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
10:33:40      return func(*arg, **kwargs)
10:33:40    File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 550, in insert
10:33:40      res = conn.bulk_insert(self._name, entities, partition_name, ids=None, timeout=timeout, schema=schema_dict, **kwargs)
10:33:40    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 96, in handler
10:33:40      raise e
10:33:40    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 92, in handler
10:33:40      return func(*args, **kwargs)
10:33:40    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 74, in handler
10:33:40      raise e
10:33:40    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 48, in handler
10:33:40      return func(self, *args, **kwargs)
10:33:40    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 359, in bulk_insert
10:33:40      raise err
10:33:40    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 355, in bulk_insert
10:33:40      raise MilvusException(response.status.error_code, response.status.reason)
10:33:40  pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Broker: Invalid replication factor)>
10:33:40   (api_request.py:39)
10:33:40  [2022-08-09 02:33:40 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Broker: Invalid replication factor)> (api_request.py:40)
10:33:41  FAILED
10:33:41  ------------------------------ live log teardown -------------------------------
10:33:41  [2022-08-09 02:33:40 - INFO - ci_test]: *********************************** teardown *********************************** (client_base.py:47)
10:33:41  [2022-08-09 02:33:40 - INFO - ci_test]: [teardown_method] Start teardown test case test_milvus_default... (client_base.py:48)
10:33:41  [2022-08-09 02:33:41 - INFO - ci_test]: [test][2022-08-09T02:33:40Z] [0.11492296s] e2e__C7Djvefp drop -> None (wrapper.py:30)
10:33:41  [2022-08-09 02:33:41 - INFO - ci_test]: [teardown_class] Start teardown class... (client_base.py:33)
10:33:41  
10:33:41  
10:33:41  =================================== FAILURES ===================================
10:33:41  _________________________ TestE2e.test_milvus_default __________________________
10:33:41  
10:33:41  self = <test_e2e.TestE2e object at 0x7f7ceefcccf8>
10:33:41  
10:33:41      @pytest.mark.tags(CaseLabel.L1)
10:33:41      def test_milvus_default(self):
10:33:41          # create
10:33:41          name = cf.gen_unique_str(prefix)
10:33:41          t0 = time.time()
10:33:41          collection_w = self.init_collection_wrap(name=name, active_trace=True)
10:33:41          tt = time.time() - t0
10:33:41          assert collection_w.name == name
10:33:41          entities = collection_w.num_entities
10:33:41          log.info(f"assert create collection: {tt}, init_entities: {entities}")
10:33:41      
10:33:41          # insert
10:33:41          data = cf.gen_default_list_data()
10:33:41          t0 = time.time()
10:33:41  >       _, res = collection_w.insert(data)
10:33:41  
10:33:41  ../testcases/test_e2e.py:29: 
```

**Comment by zhuwenxing** [comment]
Not reproduced when adding waiting time after deployment
