### ISSUE TITLE
[Bug]: Search failed with error message `fail to get shard leaders from QueryCoord: no replica available` without any chaos

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#18556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220805-c5c3392
- Deployment mode(standalone or cluster):cluster with Kafka as MQ
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Run test_e2e.py after installation
```
23:06:01  [2022-08-08 15:06:00 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:
23:06:01  attempt #1:fail to get shard leaders from QueryCoord: no replica available
23:06:01  attempt #2:fail to get shard leaders from QueryCoord: no replica available
23:06:01  attempt #3:fail to get shard leaders from QueryCoord: no replica available
23:06:01  attempt #4:fail to get shard leaders from QueryCoord: no replica available
23:06:01  attempt #5:fail to get shard leaders from QueryCoord: no replica available
23:06:01  attempt #6:fail to get shard leaders from QueryCoord: no replica available
23:06:01  attempt #7:fail to get shard leaders from QueryCoord: no replica available
23:06:01  attempt #8:context deadline exceeded
23:06:01  )>, <Time:{'RPC start': '2022-08-08 15:05:50.292791', 'RPC error': '2022-08-08 15:06:00.297066'}> (decorators.py:95)
23:06:01  [2022-08-08 15:06:00 - ERROR - ci_test]: Traceback (most recent call last):
23:06:01    File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
23:06:01      res = func(*args, **_kwargs)
23:06:01    File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
23:06:01      return func(*arg, **kwargs)
23:06:01    File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 713, in search
23:06:01      partition_names, output_fields, round_decimal, timeout=timeout, schema=schema_dict, **kwargs)
23:06:01    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 96, in handler
23:06:01      raise e
23:06:01    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 92, in handler
23:06:01      return func(*args, **kwargs)
23:06:01    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 74, in handler
23:06:01      raise e
23:06:01    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 48, in handler
23:06:01      return func(self, *args, **kwargs)
23:06:01    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 446, in search
23:06:01      return self._execute_search_requests(requests, timeout, **_kwargs)
23:06:01    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 410, in _execute_search_requests
23:06:01      raise pre_err
23:06:01    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 401, in _execute_search_requests
23:06:01      raise MilvusException(response.status.error_code, response.status.reason)
23:06:01  pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:
23:06:01  attempt #1:fail to get shard leaders from QueryCoord: no replica available
23:06:01  attempt #2:fail to get shard leaders from QueryCoord: no replica available
23:06:01  attempt #3:fail to get shard leaders from QueryCoord: no replica available
23:06:01  attempt #4:fail to get shard leaders from QueryCoord: no replica available
23:06:01  attempt #5:fail to get shard leaders from QueryCoord: no replica available
23:06:01  attempt #6:fail to get shard leaders from QueryCoord: no replica available
23:06:01  attempt #7:fail to get shard leaders from QueryCoord: no replica available
23:06:01  attempt #8:context deadline exceeded
23:06:01  )>
23:06:01   (api_request.py:39)
23:06:01  [2022-08-08 15:06:00 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:
23:06:01  attempt #1:fail to get shard leaders from QueryCoord: no replica available
23:06:01  attempt #2:fail to get shard leaders from QueryCoord: no replica available
23:06:01  attempt #3:fail to get shard leaders from QueryCoord...... (api_request.py:40)
23:06:01  FAILED
```

### Expected Behavior

all test cases passed

### Steps To Reproduce

```markdown
1. install Milvus with Kafka as MQ
2. run test_e2e.py
```

### Milvus Log

[artifacts-proxy-pod-kill-195-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9286091/artifacts-proxy-pod-kill-195-server-logs.tar.gz)

[artifacts-proxy-pod-kill-195-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9286093/artifacts-proxy-pod-kill-195-pytest-logs.tar.gz)

### Anything else?

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka/detail/chaos-test-kafka/195/pipeline

**Comment by zhuwenxing** [comment]
Not reproduced anymore, so close it!
