### ISSUE TITLE
[Bug]: [Embed] Error “Unable to import required dependencies: numpy” when start embeded milvus and import pymilvus in "mac intel" in the one python terminal

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#18557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Embedded Milvus version: latest
- Deployment mode(standalone or cluster): NA
- SDK version(e.g. pymilvus v2.0.0rc2):any
- OS(Ubuntu or CentOS): Mac intel
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
>>> import milvus
--- if you are running Milvus for the first time, type milvus.before() for pre-run instructions ---
--- otherwise, type milvus.start() ---
>>>
>>>
>>> milvus.start()
>>>
>>>
>>>
>>>
>>>
>>>
>>>
>>>
>>>
>>>
>>> ---Milvus Proxy successfully initialized and ready to serve!---

>>>
>>> from pymilvus import (
... connections,
... utility,
... FieldSchema, CollectionSchema, DataType,
... Collection,
...
...  )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/embeded_milvus/embed-test-env-3.9/lib/python3.9/site-packages/pymilvus/__init__.py", line 31, in <module>
    from .orm.collection import Collection
  File "/Users/binbin/embeded_milvus/embed-test-env-3.9/lib/python3.9/site-packages/pymilvus/orm/collection.py", line 14, in <module>
    import pandas
  File "/Users/binbin/embeded_milvus/embed-test-env-3.9/lib/python3.9/site-packages/pandas/__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/Users/binbin/embeded_milvus/embed-test-env-3.9/bin/python3"
  * The NumPy version is: "1.23.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: dlopen(/Users/binbin/embeded_milvus/embed-test-env-3.9/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so, 2): Symbol not found: ___addtf3
  Referenced from: /Users/binbin/embeded_milvus/embed-test-env-3.9/lib/python3.9/site-packages/numpy/core/../.dylibs/libquadmath.0.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/binbin/embeded_milvus/embed-test-env-3.9/lib/python3.9/site-packages/numpy/core/../.dylibs/libquadmath.0.dylib
```

### Expected Behavior

No error

### Steps To Reproduce

```markdown
1. install milvus from testpypi: pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple milvus==2.1.1.dev4
2. run in python terminal:
import milvus
milvus.before()
milvus.start()
from pymilvus import CollectionSchema, FieldSchema
```

**Comment by binbinlv** [comment]
If start milvus in one python terminal, and start another terminal to call pymilvus interface, it is good.

**Comment by soothing-rain** [comment]
fixed.

/unassign
/assign @binbinlv

**Comment by binbinlv** [comment]
Verified, and fixed.
