### ISSUE TITLE
[Bug]: [Nightly] Query failed reporting "fail to search on all shard leaders, err=fail to Query, QueryNode ID = 8, reason=ShardCluster for ...is no available"

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#18659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master (2bb9961)
- Deployment mode(standalone or cluster):clusetr (pulsar)
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.2.0.dev6
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```markdown
Query failed reporting:
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Query, QueryNode ID = 8, reason=ShardCluster for by-dev-rootcoord-dml_105_435264857545113601v0 replicaID 435264769194984499 is no available)>
```

### Expected Behavior

No error

### Steps To Reproduce

```markdown
Nightly:
https://jenkins.milvus.io:18080/blue/rest/organizations/jenkins/pipelines/Milvus%20Nightly%20CI/branches/master/runs/34/nodes/143/steps/195/log/?start=0
```

### Milvus Log

1. milvus log: [artifacts-milvus-distributed-pulsar-nightly-34-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/34/artifact/artifacts-milvus-distributed-pulsar-nightly-34-pymilvus-e2e-logs.tar.gz)
2. collection name: delete_I32u1yCp
3. Failed timeline:
[2022-08-13T15:14:55.258Z] [gw0] [ 23%] FAILED testcases/test_delete.py::TestDeleteOperation::test_delete_sealed_segment_without_flush 
4. error message:
```
[2022-08-13T16:09:12.954Z] [2022-08-13 15:14:45 - ERROR - ci_test]: Traceback (most recent call last):
[2022-08-13T16:09:12.954Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2022-08-13T16:09:12.954Z]     res = func(*args, **_kwargs)
[2022-08-13T16:09:12.954Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2022-08-13T16:09:12.954Z]     return func(*arg, **kwargs)
[2022-08-13T16:09:12.954Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 801, in query
[2022-08-13T16:09:12.954Z]     res = conn.query(self._name, expr, output_fields, partition_names, timeout=timeout, schema=schema_dict, **kwargs)
[2022-08-13T16:09:12.954Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 96, in handler
[2022-08-13T16:09:12.954Z]     raise e
[2022-08-13T16:09:12.954Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 92, in handler
[2022-08-13T16:09:12.954Z]     return func(*args, **kwargs)
[2022-08-13T16:09:12.954Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler
[2022-08-13T16:09:12.954Z]     raise e
[2022-08-13T16:09:12.954Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 48, in handler
[2022-08-13T16:09:12.954Z]     return func(self, *args, **kwargs)
[2022-08-13T16:09:12.954Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 979, in query
[2022-08-13T16:09:12.954Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2022-08-13T16:09:12.954Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Query, QueryNode ID = 8, reason=ShardCluster for by-dev-rootcoord-dml_105_435264857545113601v0 replicaID 435264769194984499 is no available)>
```

**Comment by congqixia** [comment]
After inspecting the log, the `Query` request was dispatched to querynode before the loading procedure is completed.
Here are some proof log:
```
28337:2022-08-13T23:14:25.037837524+08:00 stdout F [2022/08/13 15:14:25.037 +00:00] [DEBUG] [proxy/impl.go:458] ["LoadCollection received"] [traceID=3c4cc1d4947dd9a4] [role=proxy] [db=] [collection=delete_I32u1yCp]
28339:2022-08-13T23:14:25.038035237+08:00 stdout F [2022/08/13 15:14:25.038 +00:00] [DEBUG] [proxy/impl.go:480] ["LoadCollection enqueued"] [traceID=3c4cc1d4947dd9a4] [role=proxy] [MsgID=435264827372432074] [BeginTS=435264858357760007] [EndTS=435264858357760007] [db=] [collection=delete_I32u1yCp]
28342:2022-08-13T23:14:25.038112639+08:00 stdout F [2022/08/13 15:14:25.038 +00:00] [DEBUG] [proxy/task.go:1995] ["send LoadCollectionRequest to query coordinator"] [role=proxy] [msgID=435264827372432074] [collectionID=435264857545113601] [schema="name:\"delete_I32u1yCp\" fields:<fieldID:100 name:\"int64\" is_primary_key:true data_type:Int64 > fields:<fieldID:101 name:\"float\" data_type:Float > fields:<fieldID:102 name:\"varchar\" data_type:VarChar type_params:<key:\"max_length\" value:\"65535\" > > fields:<fieldID:103 name:\"float_vector\" data_type:FloatVector type_params:<key:\"dim\" value:\"128\" > > "]
28344:2022-08-13T23:14:25.082117565+08:00 stdout F [2022/08/13 15:14:25.082 +00:00] [DEBUG] [proxy/impl.go:510] ["LoadCollection done"] [traceID=3c4cc1d4947dd9a4] [role=proxy] [MsgID=435264827372432074] [BeginTS=435264858357760007] [EndTS=435264858357760007] [db=] [collection=delete_I32u1yCp]
28345:2022-08-13T23:14:25.082856397+08:00 stdout F [2022/08/13 15:14:25.082 +00:00] [DEBUG] [proxy/impl.go:945] ["ShowCollections received"] [role=proxy] [DbName=] [TimeStamp=0] [ShowType=InMemory] [CollectionNames="[delete_I32u1yCp]"]
28347:2022-08-13T23:14:25.083091941+08:00 stdout F [2022/08/13 15:14:25.083 +00:00] [DEBUG] [proxy/impl.go:973] ["ShowCollections enqueued"] [role=proxy] [MsgID=435264827372432075] [DbName=] [TimeStamp=0] [ShowType=InMemory] [CollectionNames="[delete_I32u1yCp]"]
28348:2022-08-13T23:14:25.083995918+08:00 stdout F [2022/08/13 15:14:25.083 +00:00] [DEBUG] [proxy/meta_cache.go:222] ["QueryCoord show collections"] [collID=435264857545113601] [collections="[435264857545113601]"] [collectionsInMemoryPercentages="[0]"]
...
...
...
28644:2022-08-13T23:14:44.190799364+08:00 stdout F [2022/08/13 15:14:44.190 +00:00] [DEBUG] [proxy/impl.go:945] ["ShowCollections received"] [role=proxy] [DbName=] [TimeStamp=0] [ShowType=InMemory] [CollectionNames="[delete_I32u1yCp]"]
28646:2022-08-13T23:14:44.191079746+08:00 stdout F [2022/08/13 15:14:44.191 +00:00] [DEBUG] [proxy/impl.go:973] ["ShowCollections enqueued"] [role=proxy] [MsgID=435264827372437131] [DbName=] [TimeStamp=0] [ShowType=InMemory] [CollectionNames="[delete_I32u1yCp]"]
28647:2022-08-13T23:14:44.192021615+08:00 stdout F [2022/08/13 15:14:44.191 +00:00] [DEBUG] [proxy/meta_cache.go:222] ["QueryCoord show collections"] [collID=435264857545113601] [collections="[435264857545113601]"] [collectionsInMemoryPercentages="[0]"]
28651:2022-08-13T23:14:44.693356874+08:00 stdout F [2022/08/13 15:14:44.693 +00:00] [DEBUG] [proxy/impl.go:945] ["ShowCollections received"] [role=proxy] [DbName=] [TimeStamp=0] [ShowType=InMemory] [CollectionNames="[delete_I32u1yCp]"]
28653:2022-08-13T23:14:44.693602923+08:00 stdout F [2022/08/13 15:14:44.693 +00:00] [DEBUG] [proxy/impl.go:973] ["ShowCollections enqueued"] [role=proxy] [MsgID=435264827372437132] [DbName=] [TimeStamp=0] [ShowType=InMemory] [CollectionNames="[delete_I32u1yCp]"]
28654:2022-08-13T23:14:44.694526583+08:00 stdout F [2022/08/13 15:14:44.694 +00:00] [DEBUG] [proxy/meta_cache.go:222] ["QueryCoord show collections"] [collID=435264857545113601] [collections="[435264857545113601]"] [collectionsInMemoryPercentages="[0]"]
28665:2022-08-13T23:14:45.197800019+08:00 stdout F [2022/08/13 15:14:45.197 +00:00] [DEBUG] [proxy/impl.go:2790] ["Query received"] [traceID=15d7b2f0cde1c18c] [role=proxy] [db=] [collection=delete_I32u1yCp] [partitions="[]"] [expr="int64 in [0]"] [OutputFields="[]"] [travel_timestamp=0] [guarantee_timestamp=0]
28668:2022-08-13T23:14:45.198112937+08:00 stdout F [2022/08/13 15:14:45.198 +00:00] [DEBUG] [proxy/impl.go:2824] ["Query enqueued"] [traceID=15d7b2f0cde1c18c] [role=proxy] [msgID=435264827372437135] [db=] [collection=delete_I32u1yCp] [partitions="[]"]
28669:2022-08-13T23:14:45.19812518+08:00 stdout F [2022/08/13 15:14:45.198 +00:00] [INFO] [proxy/task_query.go:105] ["Validate collection name."] [collectionName=delete_I32u1yCp] [msgID=435264827372437135] [requestType=query]
28670:2022-08-13T23:14:45.198139322+08:00 stdout F [2022/08/13 15:14:45.198 +00:00] [INFO] [proxy/task_query.go:116] ["Get collection ID by name"] [collectionID=435264857545113601] ["collection name"=delete_I32u1yCp] [msgID=435264827372437135] [requestType=query]
28672:2022-08-13T23:14:45.198156647+08:00 stdout F [2022/08/13 15:14:45.198 +00:00] [DEBUG] [proxy/task_query.go:137] ["Get partitions in collection."] [collectionName=delete_I32u1yCp] [msgID=435264827372437135] [requestType=query]
28673:2022-08-13T23:14:45.198505099+08:00 stdout F [2022/08/13 15:14:45.198 +00:00] [DEBUG] [proxy/meta_cache.go:222] ["QueryCoord show collections"] [collID=435264857545113601] [collections="[435264857545113601]"] [collectionsInMemoryPercentages="[0]"]
28674:2022-08-13T23:14:45.198755859+08:00 stdout F [2022/08/13 15:14:45.198 +00:00] [WARN] [proxy/task_search.go:485] ["collection not fully loaded, search on these partitions"] [collection=delete_I32u1yCp] [collectionID=435264857545113601] [partitionIDs="[435264857545113602]"]
28678:2022-08-13T23:14:45.19977526+08:00 stdout F [2022/08/13 15:14:45.199 +00:00] [DEBUG] [proxy/meta_cache.go:222] ["QueryCoord show collections"] [collID=435264857545113601] [collections="[435264857545113601]"] [collectionsInMemoryPercentages="[0]"]
28679:2022-08-13T23:14:45.199786392+08:00 stdout F [2022/08/13 15:14:45.199 +00:00] [INFO] [proxy/meta_cache.go:582] ["no shard cache for collection, try to get shard leaders from QueryCoord"] [collectionName=delete_I32u1yCp]
28680:2022-08-13T23:14:45.200536463+08:00 stdout F [2022/08/13 15:14:45.200 +00:00] [WARN] [proxy/task_query.go:327] ["QueryNode query result error"] [msgID=435264827372437135] [nodeID=8] [reason="ShardCluster for by-dev-rootcoord-dml_105_435264857545113601v0 replicaID 435264769194984499 is no available"]
28681:2022-08-13T23:14:45.200555263+08:00 stdout F [2022/08/13 15:14:45.200 +00:00] [WARN] [proxy/task_policies.go:114] ["failed to do query with node"] [nodeID=8] [dmlChannels="[by-dev-rootcoord-dml_105_435264857545113601v0]"] [error="fail to Query, QueryNode ID = 8, reason=ShardCluster for by-dev-rootcoord-dml_105_435264857545113601v0 replicaID 435264769194984499 is no available"]
```
Note that collection `inMemoryPercentage` was still 0 before `query` request arrived.

There are two problem here:
- Why pymilvus stop check load percentage before collection is actually loaded
- `checkIfLoaded` function does not work and the request was dispatched to querynode

Could please help check this? @XuanYang-cn 
/assign @XuanYang-cn

**Comment by XuanYang-cn** [comment]
pymilvus-2.2.0.dev23 @binbinlv  Please use this version to test

**Comment by binbinlv** [comment]
> pymilvus-2.2.0.dev23 @binbinlv Please use this version to test

OK, verifying in next several nightlys.

**Comment by binbinlv** [comment]
It has not been reproduced for several days, fixed. So close it.
