### ISSUE TITLE
[Bug]: CreateIndex failed: creating multiple indexes on same field is not supported

### ISSUE THREAD

**Issue by powerdy** [milvus-io/milvus#18669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0.2
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):java-sdk
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

when I drop the exists index and create a new index ,the error happend and I see the message:

2022-08-15 20:35:41 io.milvus.client.AbstractMilvusGrpcClient logInfo 
INFO: DropIndexParam{collectionName='item2vec_online_v1', fieldName='item2vec'}
2022-08-15 20:35:41 io.milvus.client.AbstractMilvusGrpcClient logInfo 
INFO: DropIndexRequest successfully! Collection name:item2vec_online_v1
R{status=0, data=RpcStatus{msg='Success'}}
2022-08-15 20:35:41 io.milvus.client.AbstractMilvusGrpcClient logInfo 
INFO: CreateIndexParam{collectionName='item2vec_online_v1', fieldName='item2vec', params='{metric_type=L2, params={"nlist":256}, index_type=IVF_FLAT}'}
2022-08-15 20:35:41 io.milvus.client.AbstractMilvusGrpcClient logError 
ERROR: CreateIndexRequest failed! Collection name:item2vec_online_v1 Field name:item2vec
CreateIndex failed: creating multiple indexes on same field is not supported, collection: item2vec_online_v1, field: item2vec, index name: idx_item2vec_v2, new index name: _default_idx
2022-08-15 20:35:41 io.milvus.client.AbstractMilvusGrpcClient logInfo 
INFO: GetIndexBuildProgressParam{collectionName='item2vec_online_v1'}
2022-08-15 20:35:41 io.milvus.client.AbstractMilvusGrpcClient logError 
ERROR: GetIndexBuildProgressRequest failed:
no index is created
Exception in thread "main" java.lang.RuntimeException: no index is created
	at com.io.milvus.testController.handleResponseStatus(testController.java:127)
	at com.io.milvus.testController.getIndexCount(testController.java:120)
	at com.io.milvus.testController.main(testController.java:206)

### Expected Behavior

when I drop the exists index and create a new index ,the new index create successfully

### Steps To Reproduce

```markdown
- Milvus version:2.1.0
- Deployment mode:standalone
- SDK version:java-sdk-2.0.4
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 
- GPU: 
- Others:
```

### Milvus Log

when I drop the exists index and create a new index ,the error happend and I see the message:

2022-08-15 20:35:41 io.milvus.client.AbstractMilvusGrpcClient logInfo 
INFO: DropIndexParam{collectionName='item2vec_online_v1', fieldName='item2vec'}
2022-08-15 20:35:41 io.milvus.client.AbstractMilvusGrpcClient logInfo 
INFO: DropIndexRequest successfully! Collection name:item2vec_online_v1
R{status=0, data=RpcStatus{msg='Success'}}
2022-08-15 20:35:41 io.milvus.client.AbstractMilvusGrpcClient logInfo 
INFO: CreateIndexParam{collectionName='item2vec_online_v1', fieldName='item2vec', params='{metric_type=L2, params={"nlist":256}, index_type=IVF_FLAT}'}
2022-08-15 20:35:41 io.milvus.client.AbstractMilvusGrpcClient logError 
ERROR: CreateIndexRequest failed! Collection name:item2vec_online_v1 Field name:item2vec
CreateIndex failed: creating multiple indexes on same field is not supported, collection: item2vec_online_v1, field: item2vec, index name: idx_item2vec_v2, new index name: _default_idx
2022-08-15 20:35:41 io.milvus.client.AbstractMilvusGrpcClient logInfo 
INFO: GetIndexBuildProgressParam{collectionName='item2vec_online_v1'}
2022-08-15 20:35:41 io.milvus.client.AbstractMilvusGrpcClient logError 
ERROR: GetIndexBuildProgressRequest failed:
no index is created
Exception in thread "main" java.lang.RuntimeException: no index is created
	at com.io.milvus.testController.handleResponseStatus(testController.java:127)
	at com.io.milvus.testController.getIndexCount(testController.java:120)
	at com.io.milvus.testController.main(testController.java:206)

### Anything else?

No

**Comment by yanliang567** [comment]
@powerdy thank you for the issue, but this is by design for now.
