### ISSUE TITLE
[Bug]: server Unavailable when creating index "RHNSW_PQ" with PQM=0

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#18671]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:bb02748
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0.dev9
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2022-08-16 10:12:52 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['float_vector', {'index_type': 'RHNSW_PQ', 'params': {'M': 48, 'efConstruction': 500, 'PQM': 0}, 'metric_type': 'L2'}], kwargs: {'timeout': 40, 'index_name': '_default_idx'} (api_request.py:56)
[2022-08-16 10:12:52 - WARNING - pymilvus.decorators]: [describe_collection] retry:4, cost: 0.27s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses> (decorators.py:69)
[2022-08-16 10:12:53 - WARNING - pymilvus.decorators]: [describe_collection] retry:5, cost: 0.81s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses> (decorators.py:69)
[2022-08-16 10:12:53 - WARNING - pymilvus.decorators]: [describe_collection] retry:6, cost: 2.43s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses> (decorators.py:69)
[2022-08-16 10:12:56 - WARNING - pymilvus.decorators]: [describe_collection] retry:7, cost: 7.290000000000001s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses> (decorators.py:69)
[2022-08-16 10:13:03 - WARNING - pymilvus.decorators]: [describe_collection] retry:8, cost: 21.870000000000005s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses> (decorators.py:69)
[2022-08-16 10:13:25 - WARNING - pymilvus.decorators]: [describe_collection] retry:9, cost: 60s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses> (decorators.py:69)
[2022-08-16 10:14:25 - ERROR - pymilvus.decorators]: RPC error: [describe_collection], <MilvusUnavailableException: (code=1, message=server Unavailable: Retry timeout: 40s)>, <Time:{'RPC start': '2022-08-16 10:12:52.673585', 'RPC error': '2022-08-16 10:14:25.519746'}> (decorators.py:95)
[2022-08-16 10:14:25 - ERROR - pymilvus.decorators]: RPC error: [create_index], <MilvusUnavailableException: (code=1, message=server Unavailable: Retry timeout: 40s)>, <Time:{'RPC start': '2022-08-16 10:12:52.555311', 'RPC error': '2022-08-16 10:14:25.520025'}> (decorators.py:95)
[2022-08-16 10:14:25 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/zilliz/virtual-environment/test2/lib/python3.8/site-packages/pymilvus/decorators.py", line 48, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/virtual-environment/test2/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 231, in describe_collection
    response = rf.result()
  File "/Users/zilliz/virtual-environment/test2/lib/python3.8/site-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1660616065.519317000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3261,"referenced_errors":[{"created":"@1660616065.519315000","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":167,"grpc_status":14}]}"
>

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/zilliz/nico/milvus/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/Users/zilliz/nico/milvus/tests/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/Users/zilliz/virtual-environment/test2/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 1082, in create_index
    return conn.create_index(self._name, field_name, index_params,
  File "/Users/zilliz/virtual-environment/test2/lib/python3.8/site-packages/pymilvus/decorators.py", line 96, in handler
    raise e
  File "/Users/zilliz/virtual-environment/test2/lib/python3.8/site-packages/pymilvus/decorators.py", line 92, in handler
    return func(*args, **kwargs)
  File "/Users/zilliz/virtual-environment/test2/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/Users/zilliz/virtual-environment/test2/lib/python3.8/site-packages/pymilvus/decorators.py", line 48, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/virtual-environment/test2/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 531, in create_index
    collection_desc = self.describe_collection(collection_name, timeout=timeout, **copy_kwargs)
  File "/Users/zilliz/virtual-environment/test2/lib/python3.8/site-packages/pymilvus/decorators.py", line 96, in handler
    raise e
  File "/Users/zilliz/virtual-environment/test2/lib/python3.8/site-packages/pymilvus/decorators.py", line 92, in handler
    return func(*args, **kwargs)
  File "/Users/zilliz/virtual-environment/test2/lib/python3.8/site-packages/pymilvus/decorators.py", line 64, in handler
    raise MilvusUnavailableException(Status.UNEXPECTED_ERROR, f"server Unavailable: {timeout_msg}")
pymilvus.exceptions.MilvusUnavailableException: <MilvusUnavailableException: (code=1, message=server Unavailable: Retry timeout: 40s)>
 (api_request.py:39)
[2022-08-16 10:14:25 - ERROR - ci_test]: (api_response) : <MilvusUnavailableException: (code=1, message=server Unavailable: Retry timeout: 40s)> (api_request.py:40)
```

### Expected Behavior

No crushed.

### Steps To Reproduce

```python
@pytest.mark.tags(CaseLabel.L1)
    @pytest.mark.parametrize("index, params",
                             zip(ct.all_index_types[:9],
                                 ct.default_index_params[:9]))
    def test_search_after_different_index_with_params(self, dim, index, params, auto_id, _async):
        """
        target: test search after different index
        method: test search after different index and corresponding search params
        expected: search successfully with limit(topK)
        """
        # 1. initialize with data
        collection_w, _, _, insert_ids, time_stamp = self.init_collection_general(prefix, True, 5000,
                                                                                  partition_num=1,
                                                                                  auto_id=auto_id,
                                                                                  dim=dim, is_index=True)[0:5]
        # 2. create index and load
        if params.get("m"):
            if (dim % params["m"]) != 0:
                params["m"] = dim // 4
        if params.get("PQM"):
            if (dim % params["PQM"]) != 0:
                params["PQM"] = dim // 4
        default_index = {"index_type": index, "params": params, "metric_type": "L2"}
        collection_w.create_index("float_vector", default_index)
        collection_w.load()
        # 3. search
        search_params = cf.gen_search_param(index)
        vectors = [[random.random() for _ in range(dim)] for _ in range(default_nq)]
        for search_param in search_params:
            log.info("Searching with search params: {}".format(search_param))
            collection_w.search(vectors[:default_nq], default_search_field,
                                search_param, default_limit,
                                default_search_exp, _async=_async,
                                travel_timestamp=time_stamp,
                                check_task=CheckTasks.check_search_results,
                                check_items={"nq": default_nq,
                                             "ids": insert_ids,
                                             "limit": default_limit,
                                             "_async": _async})

```

**Comment by NicoYuan1986** [comment]
[test0816.txt](https://github.com/milvus-io/milvus/files/9347645/test0816.txt)

**Comment by NicoYuan1986** [comment]
The case runs perfectly now.
