### ISSUE TITLE
[Bug]: [mysql] Create index failed reporting "CreateIndex failed: Error 1062: Duplicate entry '435340353625128961-default_index_name' for key 'indexes.tenant_id'" after index dropped

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#18685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: latest (master-20220816-80543cb)
- Deployment mode(standalone or cluster): both
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus==2.2.0.dev8
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Create index failed reporting "CreateIndex failed: Error 1062: Duplicate entry '435340353625128961-default_index_name' for key 'indexes.tenant_id'" after index dropped

```
[2022-08-17T00:02:03.564Z] [2022-08-16 23:14:16 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['float_vector', {'index_type': 'IVF_PQ', 'metric_type': 'L2', 'params': {'nlist': 128, 'm': 16, 'nbits': 8}}], kwargs: {'timeout': 40, 'index_name': 'default_index_name'} (api_request.py:56)
[2022-08-17T00:02:03.564Z] [2022-08-16 23:14:17 - DEBUG - ci_test]: (api_response) : Status(code=0, message='')  (api_request.py:31)
[2022-08-17T00:02:03.564Z] [2022-08-16 23:14:17 - DEBUG - ci_test]: (api_request)  : [Collection.drop_index] args: [], kwargs: {'timeout': 20, 'index_name': 'default_index_name'} (api_request.py:56)
[2022-08-17T00:02:03.564Z] [2022-08-16 23:14:17 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)
[2022-08-17T00:02:03.564Z] [2022-08-16 23:14:17 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['float_vector', {'index_type': 'IVF_PQ', 'metric_type': 'L2', 'params': {'nlist': 128, 'm': 16, 'nbits': 8}}], kwargs: {'timeout': 40, 'index_name': 'default_index_name'} (api_request.py:56)
[2022-08-17T00:02:03.564Z] [2022-08-16 23:14:17 - ERROR - pymilvus.decorators]: RPC error: [create_index], <MilvusException: (code=1, message=CreateIndex failed: Error 1062: Duplicate entry '435340353625128961-default_index_name' for key 'indexes.tenant_id')>, <Time:{'RPC start': '2022-08-16 23:14:17.163787', 'RPC error': '2022-08-16 23:14:17.171063'}> (decorators.py:95)
[2022-08-17T00:02:03.564Z] [2022-08-16 23:14:17 - ERROR - ci_test]: Traceback (most recent call last):
[2022-08-17T00:02:03.564Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2022-08-17T00:02:03.564Z]     res = func(*args, **_kwargs)
[2022-08-17T00:02:03.564Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2022-08-17T00:02:03.564Z]     return func(*arg, **kwargs)
[2022-08-17T00:02:03.564Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 1083, in create_index
[2022-08-17T00:02:03.564Z]     timeout=timeout, **kwargs)
[2022-08-17T00:02:03.564Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 96, in handler
[2022-08-17T00:02:03.564Z]     raise e
[2022-08-17T00:02:03.564Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 92, in handler
[2022-08-17T00:02:03.564Z]     return func(*args, **kwargs)
[2022-08-17T00:02:03.564Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler
[2022-08-17T00:02:03.564Z]     raise e
[2022-08-17T00:02:03.564Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 48, in handler
[2022-08-17T00:02:03.564Z]     return func(self, *args, **kwargs)
[2022-08-17T00:02:03.564Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 591, in create_index
[2022-08-17T00:02:03.564Z]     raise MilvusException(status.error_code, status.reason)
[2022-08-17T00:02:03.564Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=CreateIndex failed: Error 1062: Duplicate entry '435340353625128961-default_index_name' for key 'indexes.tenant_id')>
[2022-08-17T00:02:03.564Z]  (api_request.py:39)
[2022-08-17T00:02:03.564Z] [2022-08-16 23:14:17 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=CreateIndex failed: Error 1062: Duplicate entry '435340353625128961-default_index_name' for key 'indexes.tenant_id')> (api_request.py:40)
```

### Expected Behavior

No error for multiple "create index + drop index"

### Steps To Reproduce

```markdown
Running Nightly enabling mysql

https://jenkins.milvus.io:18080/blue/organizations/jenkins/qa%2Fmilvus-nightly-manually-debug/detail/milvus-nightly-manually-debug/32/pipeline/112/
```

### Milvus Log

All the pipelines are failed including Cluster kafka, cluster pulsar and standalone, so take standalone as example:
1. milvus log:
[milvus-standalone-32-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/qa/job/milvus-nightly-manually-debug/32/artifact/milvus-standalone-32-pymilvus-e2e-logs.tar.gz)

2. collection name: index_t2eWqBXY (taking one failed case as an example)

3. Failed timeline:
[2022-08-16T23:14:17.385Z] [gw4] [ 20%] FAILED testcases/test_index.py::TestNewIndexBase::test_create_drop_index_repeatedly[get_simple_index3] 

4. FAILED cases:
```python
    @pytest.mark.tags(CaseLabel.L2)
    def test_create_drop_index_repeatedly(self, get_simple_index):
        """
        target: test create / drop index repeatedly, use the same index params
        method: create index, drop index, four times
        expected: return code 0
        """
        c_name = cf.gen_unique_str(prefix)
        collection_w = self.init_collection_wrap(name=c_name)
        if get_simple_index["index_type"] != "FLAT":
            for i in range(4):
                collection_w.create_index(ct.default_float_vec_field_name, get_simple_index,
                                          index_name=ct.default_index_name)
                assert len(collection_w.indexes) == 1
                collection_w.drop_index(index_name=ct.default_index_name)
                assert len(collection_w.indexes) == 0
```

**Comment by aakejiang** [comment]
Fixed

**Comment by binbinlv** [comment]
OK, will verify through mysql nightly tonight.

**Comment by binbinlv** [comment]
Fixed, so close this issue.
