### ISSUE TITLE
[Bug]: Search failed with error `Search 15 failed, reason cannot find sealed segment 435367813025103874 in QueryNode err ` after pulsar pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#18705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.0-20220817-1e1b63d8
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.2.0.dev8
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

search raise error when running `verify_all_collections.py` after pulsar pod kill chaos test

```
12:25:21  + python3 scripts/verify_all_collections.py --host 10.101.70.215
12:25:28  RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=Search 15 failed, reason cannot find sealed segment 435367813025103874 in QueryNode err %!w(<nil>))>, <Time:{'RPC start': '2022-08-18 04:25:27.077005', 'RPC error': '2022-08-18 04:25:27.311795'}>
12:25:28  
12:25:28  Start time: 2022-08-18 04:25:22
12:25:28  
12:25:28  List collections...
12:25:28  ['hello_milvus', 'Checker__M24TUGyZ', 'Checker__JaTB7uI0', 'SearchChecker__zI7xivZv', 'FlushChecker__mOhPsmE3', 'InsertChecker__9e39JrSS', 'Checker__y3e2WcCd', 'DeleteChecker__6u6xxXbj', 'Checker__uqGUowDN', 'QueryChecker__QVQKrA56', 'CreateChecker__Ax0U541p', 'Checker__GaUdc60p', 'Checker__jSFw7g3R', 'IndexChecker__oX7uDKtw']
12:25:28  selected_collections is
12:25:28  ['Checker__M24TUGyZ', 'Checker__JaTB7uI0', 'Checker__y3e2WcCd', 'Checker__uqGUowDN', 'Checker__GaUdc60p', 'Checker__jSFw7g3R', 'SearchChecker__zI7xivZv', 'FlushChecker__mOhPsmE3', 'InsertChecker__9e39JrSS', 'DeleteChecker__6u6xxXbj', 'QueryChecker__QVQKrA56', 'CreateChecker__Ax0U541p', 'IndexChecker__oX7uDKtw']
12:25:28  check collection Checker__M24TUGyZ
12:25:28  collection is exist
12:25:28  
12:25:28  Create collection...
12:25:28  
12:25:28  Insert 3000 vectors cost 0.1202 seconds
12:25:28  
12:25:28  Get collection entities...
12:25:28  36490
12:25:28  
12:25:28  Get collection entities cost 3.0204 seconds
12:25:28  
12:25:28  Create index...
12:25:28  
12:25:28  Create index cost 1.5947 seconds
12:25:28  
12:25:28  Get replicas number
12:25:28  
12:25:28  Replicas number is 1
12:25:28  
12:25:28  load collection...
12:25:28  
12:25:28  load collection cost 0.0038 seconds
12:25:28  
12:25:28  Search...
12:25:28  Traceback (most recent call last):
12:25:28    File "scripts/verify_all_collections.py", line 138, in <module>
12:25:28      hello_milvus(collection_name)
12:25:28    File "scripts/verify_all_collections.py", line 95, in hello_milvus
12:25:28      "int64 > 100", output_fields=["int64", "float"], timeout=TIMEOUT
12:25:28    File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 718, in search
12:25:28      partition_names, output_fields, round_decimal, timeout=timeout, schema=schema_dict, **kwargs)
12:25:28    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 96, in handler
12:25:28      raise e
12:25:28    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 92, in handler
12:25:28      return func(*args, **kwargs)
12:25:28    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 74, in handler
12:25:28      raise e
12:25:28    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 48, in handler
12:25:28      return func(self, *args, **kwargs)
12:25:28    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 452, in search
12:25:28      return self._execute_search_requests(requests, timeout, **_kwargs)
12:25:28    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 416, in _execute_search_requests
12:25:28      raise pre_err
12:25:28    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 407, in _execute_search_requests
12:25:28      raise MilvusException(response.status.error_code, response.status.reason)
12:25:28  pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=Search 15 failed, reason cannot find sealed segment 435367813025103874 in QueryNode err %!w(<nil>))>
```

### Expected Behavior

all test cases passed

### Steps To Reproduce

```markdown
see Anything else
```

### Milvus Log

failed job:  chaos-test/495/pipeline
log:
[artifacts-pulsar-pod-kill-495-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/9368049/artifacts-pulsar-pod-kill-495-server-logs.1.tar.gz)
[artifacts-pulsar-pod-kill-495-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9368051/artifacts-pulsar-pod-kill-495-pytest-logs.tar.gz)

### Anything else?

![image](https://user-images.githubusercontent.com/12268675/185305918-22572c24-a87e-410c-a854-12a13585b81c.png)

**Comment by binbinlv** [comment]
This error occurs in the nightly for the 2.1.1 branch:
https://jenkins.milvus.io:18080/blue/organizations/jenkins/qa%2Fmilvus-release-nightly/detail/milvus-release-nightly/46/pipeline

1. log: [milvus-distributed-kafka-46-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/qa/job/milvus-release-nightly/46/artifact/milvus-distributed-kafka-46-pymilvus-e2e-logs.tar.gz)
2. collection name: search_collection_n4x0WwiB
3. Failed timeline: [2022-08-18T20:38:12.698Z] [gw4] [ 56%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_after_different_index_with_params[128-False-True-RHNSW_FLAT-params6] 
4. test error trace:
```
[2022-08-18T21:23:50.981Z] testcases/test_search.py:1245: 

[2022-08-18T21:23:50.981Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

[2022-08-18T21:23:50.981Z] utils/wrapper.py:33: in inner_wrapper

[2022-08-18T21:23:50.981Z]     result = func(*args, **kwargs)

[2022-08-18T21:23:50.981Z] base/collection_wrapper.py:153: in search

[2022-08-18T21:23:50.981Z]     timeout=timeout, **kwargs).run()

[2022-08-18T21:23:50.981Z] check/func_check.py:56: in run

[2022-08-18T21:23:50.981Z]     result = self.check_search_results(self.response, self.func_name, self.check_items)

[2022-08-18T21:23:50.981Z] check/func_check.py:205: in check_search_results

[2022-08-18T21:23:50.981Z]     search_res = search_res.result()

[2022-08-18T21:23:50.981Z] /usr/local/lib/python3.6/site-packages/pymilvus/orm/future.py:30: in result

[2022-08-18T21:23:50.981Z]     return self.on_response(self._f.result())

[2022-08-18T21:23:50.981Z] /usr/local/lib/python3.6/site-packages/pymilvus/client/asynch.py:185: in result

[2022-08-18T21:23:50.981Z]     self.exception()

[2022-08-18T21:23:50.981Z] /usr/local/lib/python3.6/site-packages/pymilvus/client/asynch.py:242: in exception

[2022-08-18T21:23:50.981Z]     raise self._exception

[2022-08-18T21:23:50.981Z] /usr/local/lib/python3.6/site-packages/pymilvus/client/asynch.py:232: in done

[2022-08-18T21:23:50.981Z]     self._results = self.on_response(self._response)

[2022-08-18T21:23:50.981Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

[2022-08-18T21:23:50.981Z] 

[2022-08-18T21:23:50.981Z] self = <pymilvus.client.asynch.ChunkedSearchFuture object at 0x7f02ea90d198>

[2022-08-18T21:23:50.981Z] response = [status {

[2022-08-18T21:23:50.981Z]   error_code: UnexpectedError

[2022-08-18T21:23:50.981Z]   reason: "fail to search on all shard leaders, err=fail to Search, QueryNode ID=16, reason=Search 16 failed, reason cannot find sealed segment 435383195913420801 in QueryNode err %!w(<nil>)"

[2022-08-18T21:23:50.981Z] }

[2022-08-18T21:23:50.981Z] ]

[2022-08-18T21:23:50.981Z] 

[2022-08-18T21:23:50.981Z]     def on_response(self, response):

[2022-08-18T21:23:50.981Z]         for raw in response:

[2022-08-18T21:23:50.981Z]             if raw.status.error_code != 0:

[2022-08-18T21:23:50.981Z] >               raise MilvusException(raw.status.error_code, raw.status.reason)

[2022-08-18T21:23:50.981Z] E               pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=16, reason=Search 16 failed, reason cannot find sealed segment 435383195913420801 in QueryNode err %!w(<nil>))>

[2022-08-18T21:23:50.981Z] 
```

**Comment by binbinlv** [comment]
Reproduced in function nightly, so set it as urgent.

**Comment by zhuwenxing** [comment]
It reproduced stably

**Comment by NicoYuan1986** [comment]
This error occurs in the nightly for the master(1527aee) branch:
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/66/pipeline/143

milvus log: [artifacts-milvus-distributed-kafka-nightly-66-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/66/artifact/artifacts-milvus-distributed-kafka-nightly-66-pymilvus-e2e-logs.tar.gz)
pymilvus: 2.2.0.dev23
collection name: search_collection_Ti6uoXSM
Failed timeline: [2022-08-29T15:18:22.754Z] [gw1] [ 45%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_with_dup_primary_key[8-True-False-3] 
test error:
```
[2022-08-29T16:00:24.595Z] [2022-08-29 15:18:22 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=12, reason=Search 13 failed, reason cannot find sealed segment 435627307350822209 in QueryNode err %!w(<nil>))>, <Time:{'RPC start': '2022-08-29 15:18:21.638138', 'RPC error': '2022-08-29 15:18:22.037138'}> (decorators.py:100)
[2022-08-29T16:00:24.595Z] [2022-08-29 15:18:22 - ERROR - ci_test]: Traceback (most recent call last):
[2022-08-29T16:00:24.595Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2022-08-29T16:00:24.595Z]     res = func(*args, **_kwargs)
[2022-08-29T16:00:24.595Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2022-08-29T16:00:24.595Z]     return func(*arg, **kwargs)
[2022-08-29T16:00:24.595Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 717, in search
[2022-08-29T16:00:24.595Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,
[2022-08-29T16:00:24.595Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 101, in handler
[2022-08-29T16:00:24.595Z]     raise e
[2022-08-29T16:00:24.595Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 97, in handler
[2022-08-29T16:00:24.595Z]     return func(*args, **kwargs)
[2022-08-29T16:00:24.595Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 127, in handler
[2022-08-29T16:00:24.595Z]     ret = func(self, *args, **kwargs)
[2022-08-29T16:00:24.595Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 79, in handler
[2022-08-29T16:00:24.595Z]     raise e
[2022-08-29T16:00:24.595Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2022-08-29T16:00:24.595Z]     return func(self, *args, **kwargs)
[2022-08-29T16:00:24.595Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 473, in search
[2022-08-29T16:00:24.595Z]     return self._execute_search_requests(requests, timeout, **_kwargs)
[2022-08-29T16:00:24.595Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 437, in _execute_search_requests
[2022-08-29T16:00:24.595Z]     raise pre_err
[2022-08-29T16:00:24.595Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 428, in _execute_search_requests
[2022-08-29T16:00:24.595Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2022-08-29T16:00:24.595Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=12, reason=Search 13 failed, reason cannot find sealed segment 435627307350822209 in QueryNode err %!w(<nil>))>
[2022-08-29T16:00:24.595Z]  (api_request.py:39)
[2022-08-29T16:00:24.595Z] [2022-08-29 15:18:22 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=12, reason=Search 13 failed, reason cannot find sealed segment 435627307350822209 in QueryNode err %!w(<nil>))> (api_request.py:40)
```

**Comment by NicoYuan1986** [comment]
The latest error for 2.1.1 branch:
https://jenkins.milvus.io:18080/blue/organizations/jenkins/qa%2Fmilvus-release-nightly/detail/milvus-release-nightly/72/pipeline/177
1. pymilvus: 2.1.2.dev2
2. FAILED time: [2022-08-31T20:29:04.876Z] [gw0] [ 40%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_with_ndarray[128-True-False] 
3. collection name: search_collection_umifIDDF
4. milvus log: [milvus-distributed-pulsar-72-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/qa/job/milvus-release-nightly/72/artifact/milvus-distributed-pulsar-72-pymilvus-e2e-logs.tar.gz)
5. error message:
```
[2022-08-31T21:10:36.856Z] [2022-08-31 20:29:04 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=Search 17 failed, reason cannot find sealed segment 435677492719386625 in QueryNode err %!w(<nil>))>, <Time:{'RPC start': '2022-08-31 20:29:03.850794', 'RPC error': '2022-08-31 20:29:04.459141'}> (decorators.py:95)
[2022-08-31T21:10:36.856Z] [2022-08-31 20:29:04 - ERROR - ci_test]: Traceback (most recent call last):
[2022-08-31T21:10:36.856Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
[2022-08-31T21:10:36.856Z]     res = func(*args, **kwargs)
[2022-08-31T21:10:36.856Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 56, in api_request
[2022-08-31T21:10:36.856Z]     return func(*arg, **kwargs)
[2022-08-31T21:10:36.856Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 713, in search
[2022-08-31T21:10:36.856Z]     partition_names, output_fields, round_decimal, timeout=timeout, schema=schema_dict, **kwargs)
[2022-08-31T21:10:36.856Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 96, in handler
[2022-08-31T21:10:36.856Z]     raise e
[2022-08-31T21:10:36.856Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 92, in handler
[2022-08-31T21:10:36.856Z]     return func(*args, **kwargs)
[2022-08-31T21:10:36.856Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler
[2022-08-31T21:10:36.856Z]     raise e
[2022-08-31T21:10:36.856Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 48, in handler
[2022-08-31T21:10:36.856Z]     return func(self, *args, **kwargs)
[2022-08-31T21:10:36.856Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 446, in search
[2022-08-31T21:10:36.856Z]     return self._execute_search_requests(requests, timeout, **_kwargs)
[2022-08-31T21:10:36.856Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 410, in _execute_search_requests
[2022-08-31T21:10:36.856Z]     raise pre_err
[2022-08-31T21:10:36.856Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 401, in _execute_search_requests
[2022-08-31T21:10:36.856Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2022-08-31T21:10:36.856Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=Search 17 failed, reason cannot find sealed segment 435677492719386625 in QueryNode err %!w(<nil>))>
[2022-08-31T21:10:36.856Z]  (api_request.py:35)
[2022-08-31T21:10:36.856Z] [2022-08-31 20:29:04 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=Search 17 failed, reason cannot find sealed segment 435677492719386625 in QueryNode err %!w(<nil>))> (api_request.py:36)
```

**Comment by zhuwenxing** [comment]
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-for-release/detail/chaos-test-for-release/323/pipeline

log:
[artifacts-pulsar-pod-failure-323-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9531752/artifacts-pulsar-pod-failure-323-server-logs.tar.gz)
[artifacts-pulsar-pod-failure-323-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9531753/artifacts-pulsar-pod-failure-323-pytest-logs.tar.gz)

**Comment by congqixia** [comment]
Hi @zhuwenxing does this problem still persist in querycoord v2?

**Comment by zhuwenxing** [comment]
verified and passed in version `master-20221020-e8ca754d`
