### ISSUE TITLE
[Bug]: [Nightly] Search failed reporting "fail to Search, QueryNode ID=5, reason=query node 0 is not ready"

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#18721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.0-20220818-9353dfb8
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Search failed reporting "fail to Search, QueryNode ID=5, reason=query node 0 is not ready":
```

[2022-08-18T21:23:50.981Z] [2022-08-18 20:37:27 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.048435518311387704, 0.9485538120880068, 0.4922480825334399, 0.4757377200595889, 0.7645725779543114, 0.9305821043574852, 0.16225470923699747, 0.19130132151595958, 0.3324207589842708, 0.9108289094072408, 0.3572036261480994, 0.9555659360201715, 0.788803687830812, 0.03990401741899274, 0.50493248585......, kwargs: {'_async': False} (api_request.py:55)

[2022-08-18T21:23:50.981Z] [2022-08-18 20:37:31 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to Search, QueryNode ID=5, reason=query node 0 is not ready)>, <Time:{'RPC start': '2022-08-18 20:37:27.087356', 'RPC error': '2022-08-18 20:37:31.632137'}> (decorators.py:95)

[2022-08-18T21:23:50.981Z] [2022-08-18 20:37:31 - ERROR - ci_test]: Traceback (most recent call last):

[2022-08-18T21:23:50.981Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper

[2022-08-18T21:23:50.981Z]     res = func(*args, **kwargs)

[2022-08-18T21:23:50.981Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 56, in api_request

[2022-08-18T21:23:50.981Z]     return func(*arg, **kwargs)

[2022-08-18T21:23:50.981Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 713, in search

[2022-08-18T21:23:50.981Z]     partition_names, output_fields, round_decimal, timeout=timeout, schema=schema_dict, **kwargs)

[2022-08-18T21:23:50.981Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 96, in handler

[2022-08-18T21:23:50.981Z]     raise e

[2022-08-18T21:23:50.981Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 92, in handler

[2022-08-18T21:23:50.981Z]     return func(*args, **kwargs)

[2022-08-18T21:23:50.981Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler

[2022-08-18T21:23:50.981Z]     raise e

[2022-08-18T21:23:50.981Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 48, in handler

[2022-08-18T21:23:50.981Z]     return func(self, *args, **kwargs)

[2022-08-18T21:23:50.981Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 446, in search

[2022-08-18T21:23:50.981Z]     return self._execute_search_requests(requests, timeout, **_kwargs)

[2022-08-18T21:23:50.981Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 410, in _execute_search_requests

[2022-08-18T21:23:50.981Z]     raise pre_err

[2022-08-18T21:23:50.981Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 401, in _execute_search_requests

[2022-08-18T21:23:50.981Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2022-08-18T21:23:50.981Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to Search, QueryNode ID=5, reason=query node 0 is not ready)>

[2022-08-18T21:23:50.981Z]  (api_request.py:35)

[2022-08-18T21:23:50.981Z] [2022-08-18 20:37:31 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to Search, QueryNode ID=5, reason=query node 0 is not ready)> (api_request.py:36)
```

### Expected Behavior

Search successfully

### Steps To Reproduce

```markdown
Running nightly:
https://jenkins.milvus.io:18080/blue/organizations/jenkins/qa%2Fmilvus-release-nightly/detail/milvus-release-nightly/46/pipeline
```

### Milvus Log

1. milvus log:[milvus-distributed-kafka-46-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/qa/job/milvus-release-nightly/46/artifact/milvus-distributed-kafka-46-pymilvus-e2e-logs.tar.gz)
2. collection name: search_collection_XnNRYGDl
3. Failed timeline: [2022-08-18T20:37:32.404Z] [gw3] [ 55%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_with_dup_primary_key[128-True-False-1]

**Comment by congqixia** [comment]
Hi @binbinlv, the link of the log returns an error. And the run 46 cannot be find in nightly run list.

**Comment by binbinlv** [comment]
@congqixia  I could download it successfully, maybe it is because is in the qa namespace, maybe you did not have access. 
I will give to you offline. Thanks.

**Comment by congqixia** [comment]
@binbinlv from the log, querynode disconnected from the etcd:
```
2022-08-19T05:24:06.94863593+08:00 stderr F panic: rpc error: code = Canceled desc = latest balancer error: last connection error: connection error: desc = "transport: Error while dialing dial tcp: lookup mdk-release-46-n-etcd on 10.255.0.10:53: server misbehaving"
```
And from etcd log, the etcd server was killed according to the log:
```
2022-08-19T05:24:05.120261349+08:00 stderr F {"level":"info","ts":"2022-08-18T21:24:05.120Z","caller":"osutil/interrupt_unix.go:64","msg":"received signal; shutting down","signal":"terminated"}
2022-08-19T05:24:05.120287261+08:00 stderr F {"level":"info","ts":"2022-08-18T21:24:05.120Z","caller":"embed/etcd.go:367","msg":"closing etcd server","name":"mdk-release-46-n-etcd-0","data-dir":"/bitnami/etcd/data","advertise-peer-urls":["http://mdk-release-46-n-etcd-0.mdk-release-46-n-etcd-headless.milvus-ci.svc.cluster.local:2380"],"advertise-client-urls":["http://mdk-release-46-n-etcd-0.mdk-release-46-n-etcd-headless.milvus-ci.svc.cluster.local:2379"]}
...
```

**Comment by congqixia** [comment]
> @binbinlv from the log, querynode disconnected from the etcd:
> 
> ```
> 2022-08-19T05:24:06.94863593+08:00 stderr F panic: rpc error: code = Canceled desc = latest balancer error: last connection error: connection error: desc = "transport: Error while dialing dial tcp: lookup mdk-release-46-n-etcd on 10.255.0.10:53: server misbehaving"
> ```
> 
> And from etcd log, the etcd server was killed according to the log:
> 
> ```
> 2022-08-19T05:24:05.120261349+08:00 stderr F {"level":"info","ts":"2022-08-18T21:24:05.120Z","caller":"osutil/interrupt_unix.go:64","msg":"received signal; shutting down","signal":"terminated"}
> 2022-08-19T05:24:05.120287261+08:00 stderr F {"level":"info","ts":"2022-08-18T21:24:05.120Z","caller":"embed/etcd.go:367","msg":"closing etcd server","name":"mdk-release-46-n-etcd-0","data-dir":"/bitnami/etcd/data","advertise-peer-urls":["http://mdk-release-46-n-etcd-0.mdk-release-46-n-etcd-headless.milvus-ci.svc.cluster.local:2380"],"advertise-client-urls":["http://mdk-release-46-n-etcd-0.mdk-release-46-n-etcd-headless.milvus-ci.svc.cluster.local:2379"]}
> ...
> ```

Please ignore this comment. These logs are from the end of the nightly

**Comment by congqixia** [comment]
The actual panic reason was:
```
2022-08-19T04:37:26.806070463+08:00 stderr F milvus: rdkafka_broker.c:5467: void rd_kafka_broker_destroy_final(rd_kafka_broker_t *): Assertion `thrd_is_current(rkb->rkb_thread)' failed.
```

**Comment by binbinlv** [comment]
Same issue occurs again:
https://jenkins.milvus.io:18080/blue/organizations/jenkins/qa%2Fmilvus-release-nightly/detail/milvus-release-nightly/50/pipeline/177

1. milvus log:
[milvus-distributed-kafka-50-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/qa/job/milvus-release-nightly/50/artifact/milvus-distributed-kafka-50-pymilvus-e2e-logs.tar.gz)

2. collection name: query_FE5RVxgr

3. Failed testcase:
[2022-08-20T20:53:22.687Z] [gw2] [ 94%] FAILED testcases/test_utility.py::TestUtilityBase::test_loading_progress_with_release_partition

**Comment by NicoYuan1986** [comment]
The error hasn't appeared these days.So close it first and will reopen it if it occurs in the future.
