### ISSUE TITLE
[Bug]: Search failed with error `ShardCluster for by-dev-rootcoord-dml_8_435422380333989889v0 replicaID 435422368070369315 is no available` after querynode pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#18759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220820-9589bd3
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.2.0.dev19
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/12268675/185836677-dbc6ebea-e697-4b2c-bf49-c3b82eb1a300.png)

```
22:17:39  check collection Checker__bK7yEnUJ
22:17:39  collection is exist
22:17:39  
22:17:39  Create collection...
22:17:39  
22:17:39  Insert 3000 vectors cost 0.0969 seconds
22:17:39  
22:17:39  Get collection entities...
22:17:39  38120
22:17:39  
22:17:39  Get collection entities cost 3.0320 seconds
22:17:39  
22:17:39  Create index...
22:17:39  
22:17:39  Create index cost 0.5139 seconds
22:17:39  
22:17:39  Get replicas number
22:17:39  
22:17:39  Replicas number is 1
22:17:39  
22:17:39  load collection...
22:17:39  
22:17:39  load collection cost 0.0027 seconds
22:17:39  
22:17:39  Search...
22:17:39  Traceback (most recent call last):
22:17:39    File "scripts/verify_all_collections.py", line 138, in <module>
22:17:39      hello_milvus(collection_name)
22:17:39    File "scripts/verify_all_collections.py", line 95, in hello_milvus
22:17:39      "int64 > 100", output_fields=["int64", "float"], timeout=TIMEOUT
22:17:39    File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 718, in search
22:17:39      partition_names, output_fields, round_decimal, timeout=timeout, schema=schema_dict, **kwargs)
22:17:39    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 96, in handler
22:17:39      raise e
22:17:39    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 92, in handler
22:17:39      return func(*args, **kwargs)
22:17:39    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 74, in handler
22:17:39      raise e
22:17:39    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 48, in handler
22:17:39      return func(self, *args, **kwargs)
22:17:39    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 452, in search
22:17:39      return self._execute_search_requests(requests, timeout, **_kwargs)
22:17:39    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 416, in _execute_search_requests
22:17:39      raise pre_err
22:17:39    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 407, in _execute_search_requests
22:17:39      raise MilvusException(response.status.error_code, response.status.reason)
22:17:39  pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=3, reason=ShardCluster for by-dev-rootcoord-dml_8_435422380333989889v0 replicaID 435422368070369315 is no available)>
```

### Expected Behavior

all test cases passed

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/586/pipeline

log:
[artifacts-querynode-pod-failure-586-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9391156/artifacts-querynode-pod-failure-586-server-logs.tar.gz)
[artifacts-querynode-pod-failure-586-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9391157/artifacts-querynode-pod-failure-586-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
same for etcd pod kill
failed job：https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/646/pipeline
log： 
[artifacts-etcd-pod-kill-646-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9398864/artifacts-etcd-pod-kill-646-server-logs.tar.gz)
[artifacts-etcd-pod-kill-646-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9398866/artifacts-etcd-pod-kill-646-pytest-logs.tar.gz)

```
21:57:05  check collection Checker__iwXZZzjs
21:57:05  collection is exist
21:57:05  
21:57:05  Create collection...
21:57:05  
21:57:05  Insert 3000 vectors cost 0.0719 seconds
21:57:05  
21:57:05  Get collection entities...
21:57:05  36424
21:57:05  
21:57:05  Get collection entities cost 3.0196 seconds
21:57:05  
21:57:05  Create index...
21:57:05  
21:57:05  Create index cost 0.5077 seconds
21:57:05  
21:57:05  Get replicas number
21:57:05  
21:57:05  Replicas number is 1
21:57:05  
21:57:05  load collection...
21:57:05  
21:57:05  load collection cost 0.0034 seconds
21:57:05  
21:57:05  Search...
21:57:05  Traceback (most recent call last):
21:57:05    File "scripts/verify_all_collections.py", line 138, in <module>
21:57:05      hello_milvus(collection_name)
21:57:05    File "scripts/verify_all_collections.py", line 95, in hello_milvus
21:57:05      "int64 > 100", output_fields=["int64", "float"], timeout=TIMEOUT
21:57:05    File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 718, in search
21:57:05      partition_names, output_fields, round_decimal, timeout=timeout, schema=schema_dict, **kwargs)
21:57:05    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 96, in handler
21:57:05      raise e
21:57:05    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 92, in handler
21:57:05      return func(*args, **kwargs)
21:57:05    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 74, in handler
21:57:05      raise e
21:57:05    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 48, in handler
21:57:05      return func(self, *args, **kwargs)
21:57:05    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 452, in search
21:57:05      return self._execute_search_requests(requests, timeout, **_kwargs)
21:57:05    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 416, in _execute_search_requests
21:57:05      raise pre_err
21:57:05    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 407, in _execute_search_requests
21:57:05      raise MilvusException(response.status.error_code, response.status.reason)
21:57:05  pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=17, reason=ShardCluster for by-dev-rootcoord-dml_12_435467325233954821v0 replicaID 435467314490769453 is no available)>
```

**Comment by soothing-rain** [comment]
Also reported in other user's chaos tests.

**Comment by zhuwenxing** [comment]
image version: 2.1.0-20220901-494445b
failed job:https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-for-release/detail/chaos-test-for-release/118/pipeline/70
log:
[artifacts-querynode-pod-kill-118-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9474790/artifacts-querynode-pod-kill-118-server-logs.tar.gz)

[artifacts-querynode-pod-kill-118-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9474793/artifacts-querynode-pod-kill-118-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
This also happened when running pulsar pod kill chaos test

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-for-release/detail/chaos-test-for-release/241/pipeline

log:
[artifacts-pulsar-pod-kill-241-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9503303/artifacts-pulsar-pod-kill-241-pytest-logs.tar.gz)
[artifacts-pulsar-pod-kill-241-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9503304/artifacts-pulsar-pod-kill-241-server-logs.tar.gz)

**Comment by zhuwenxing** [comment]
@jiaoew1991  
any progress? it is still stable happened in 2.1.0-latest.

**Comment by zhuwenxing** [comment]
> any progress? it is still stable happened in 2.1.0-latest.
@jiaoew1991 
sorry for the wrong information, it is still stable in the master branch but has not happened in the 2.1 branch.

Do you know which PR fixed this in 2.1?

**Comment by jiaoew1991** [comment]
can you retry it with QueryCoordV2
/assign @zhuwenxing 
/unassign

**Comment by zhuwenxing** [comment]
It not reproduced in master now, so close it
