### ISSUE TITLE
[Bug]: Load timeout after pulsar and querycoord pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#18757]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220820-9589bd3
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.2.0.dev19
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/12268675/185832619-7916bf55-db59-4e8e-af12-71223baf4f34.png)
client:
```
21:58:14  [2022-08-21 13:57:52 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 20], kwargs: {} (api_request.py:56)
21:58:14  [2022-08-21 13:58:12 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)>, <Time:{'RPC start': '2022-08-21 13:57:52.440478', 'RPC error': '2022-08-21 13:58:12.441587'}> (decorators.py:95)
21:58:14  [2022-08-21 13:58:12 - ERROR - ci_test]: Traceback (most recent call last):
21:58:14    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 48, in handler
21:58:14      return func(self, *args, **kwargs)
21:58:14    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 674, in load_collection
21:58:14      response = rf.result()
21:58:14    File "/usr/local/lib/python3.7/dist-packages/grpc/_channel.py", line 744, in result
21:58:14      raise self
21:58:14  grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
21:58:14  	status = StatusCode.DEADLINE_EXCEEDED
21:58:14  	details = "Deadline Exceeded"
21:58:14  	debug_error_string = "{"created":"@1661090292.441145605","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":81,"grpc_status":4}"
21:58:14  >
21:58:14  
21:58:14  During handling of the above exception, another exception occurred:
21:58:14  
21:58:14  Traceback (most recent call last):
21:58:14    File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
21:58:14      res = func(*args, **_kwargs)
21:58:14    File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
21:58:14      return func(*arg, **kwargs)
21:58:14    File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 474, in load
21:58:14      conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
21:58:14    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 96, in handler
21:58:14      raise e
21:58:14    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 92, in handler
21:58:14      return func(*args, **kwargs)
21:58:14    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 62, in handler
21:58:14      raise MilvusException(Status.UNEXPECTED_ERROR, f"rpc deadline exceeded: {timeout_msg}")
21:58:14  pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)>
21:58:14   (api_request.py:39)
21:58:14  [2022-08-21 13:58:12 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)> (api_request.py:40)
```
server
```
21:58:16  [2022/08/21 13:57:52.441 +00:00] [DEBUG] [proxy/impl.go:480] ["LoadCollection enqueued"] [traceID=4db7813f6518a23d] [role=proxy] [MsgID=435444604582026062] [BeginTS=435444848375889925] [EndTS=435444848375889925] [db=] [collection=e2e__AAb5TSIt]
21:58:16  [2022/08/21 13:57:52.441 +00:00] [DEBUG] [proxy/task.go:1953] ["loadCollectionTask PreExecute"] [role=proxy] [msgID=435444604582026062]
21:58:16  [2022/08/21 13:57:52.441 +00:00] [DEBUG] [proxy/task.go:1972] ["loadCollectionTask Execute"] [role=proxy] [msgID=435444604582026062]
21:58:16  [2022/08/21 13:57:52.441 +00:00] [DEBUG] [proxy/task.go:1995] ["send LoadCollectionRequest to query coordinator"] [role=proxy] [msgID=435444604582026062] [collectionID=435444847445540865] [schema="name:\"e2e__AAb5TSIt\" fields:<fieldID:100 name:\"int64\" is_primary_key:true data_type:Int64 > fields:<fieldID:101 name:\"float\" data_type:Float > fields:<fieldID:102 name:\"varchar\" data_type:VarChar type_params:<key:\"max_length\" value:\"65535\" > > fields:<fieldID:103 name:\"float_vector\" data_type:FloatVector type_params:<key:\"dim\" value:\"128\" > > "]
21:58:16  [2022/08/21 13:58:12.441 +00:00] [WARN] [proxy/impl.go:490] ["LoadCollection failed to WaitToFinish"] [error="proxy TaskCondition context Done"] [traceID=4db7813f6518a23d] [role=proxy] [MsgID=435444604582026062] [BeginTS=435444848375889925] [EndTS=435444848375889925] [db=] [collection=e2e__AAb5TSIt]
21:58:16  [2022/08/21 13:58:12.441 +00:00] [WARN] [grpcclient/client.go:251] ["querycoord ClientBase ReCall grpc first call get error "] [error="err: rpc error: code = Canceled desc = context canceled\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:250 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall\n/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/client/client.go:174 github.com/milvus-io/milvus/internal/distributed/querycoord/client.(*Client).LoadCollection\n/go/src/github.com/milvus-io/milvus/internal/proxy/task.go:1998 github.com/milvus-io/milvus/internal/proxy.(*loadCollectionTask).Execute\n/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:465 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask\n/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:494 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop\n/usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit\n"]
21:58:16  [2022/08/21 13:58:12.441 +00:00] [ERROR] [proxy/task_scheduler.go:468] ["Failed to execute task: call query coordinator LoadCollection: context canceled"] [traceID=4db7813f6518a23d] [stack="github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:468\ngithub.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:494"]
```

### Expected Behavior

all test cases passed

### Milvus Log

failed job: 
https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/596/pipeline

log:
[artifacts-pulsar-pod-kill-596-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9391051/artifacts-pulsar-pod-kill-596-server-logs.tar.gz)

[artifacts-pulsar-pod-kill-596-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9391052/artifacts-pulsar-pod-kill-596-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
querycoord pod kill
* failed job
    *  https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/643/pipeline
* log: 
    * [artifacts-querycoord-pod-kill-643-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9398774/artifacts-querycoord-pod-kill-643-server-logs.tar.gz)
    * [artifacts-querycoord-pod-kill-643-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9398778/artifacts-querycoord-pod-kill-643-pytest-logs.tar.gz)

**Comment by weiliu1031** [comment]
> querycoord pod kill
> 
> * failed job
>   
>   * https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/643/pipeline
> * log:
>   
>   * [artifacts-querycoord-pod-kill-643-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9398774/artifacts-querycoord-pod-kill-643-server-logs.tar.gz)
>   * [artifacts-querycoord-pod-kill-643-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9398778/artifacts-querycoord-pod-kill-643-pytest-logs.tar.gz)

this one is same question with https://github.com/milvus-io/milvus/issues/18664

**Comment by weiliu1031** [comment]
> /assign @zhuwenxing

please verify on this

**Comment by zhuwenxing** [comment]
Not reproduced yet, so close it for now.
