### ISSUE TITLE
[Bug]: Create index timeout after indexnode pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#18758]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220820-9589bd3
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.2.0.dev19
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/12268675/185833535-fb12b4b6-3985-4f7b-8b21-0ef74f480aaa.png)

```
21:38:02  [2022-08-21 13:37:00 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['float_vector', {'index_type': 'IVF_SQ8', 'params': {'nlist': 64}, 'metric_type': 'L2'}], kwargs: {'name': 'test_EpgwYfmS', 'timeout': 40, 'index_name': '_default_idx'} (api_request.py:56)
21:38:02  [2022-08-21 13:37:40 - ERROR - pymilvus.decorators]: RPC error: [create_index], <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 40s)>, <Time:{'RPC start': '2022-08-21 13:37:00.623180', 'RPC error': '2022-08-21 13:37:40.627555'}> (decorators.py:95)
21:38:02  [2022-08-21 13:37:40 - ERROR - ci_test]: Traceback (most recent call last):
21:38:02    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 48, in handler
21:38:02      return func(self, *args, **kwargs)
21:38:02    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 588, in create_index
21:38:02      status = future.result()
21:38:02    File "/usr/local/lib/python3.7/dist-packages/grpc/_channel.py", line 744, in result
21:38:02      raise self
21:38:02  grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
21:38:02  	status = StatusCode.DEADLINE_EXCEEDED
21:38:02  	details = "Deadline Exceeded"
21:38:02  	debug_error_string = "{"created":"@1661089060.627237754","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":81,"grpc_status":4}"
21:38:02  >
21:38:02  
21:38:02  During handling of the above exception, another exception occurred:
21:38:02  
21:38:02  Traceback (most recent call last):
21:38:02    File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
21:38:02      res = func(*args, **_kwargs)
21:38:02    File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
21:38:02      return func(*arg, **kwargs)
21:38:02    File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 1083, in create_index
21:38:02      timeout=timeout, **kwargs)
21:38:02    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 96, in handler
21:38:02      raise e
21:38:02    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 92, in handler
21:38:02      return func(*args, **kwargs)
21:38:02    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 62, in handler
21:38:02      raise MilvusException(Status.UNEXPECTED_ERROR, f"rpc deadline exceeded: {timeout_msg}")
21:38:02  pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 40s)>
21:38:02   (api_request.py:39)
21:38:02  [2022-08-21 13:37:40 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 40s)> (api_request.py:40)
```

### Expected Behavior

all test cases passed

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/594/pipeline
log:
[artifacts-indexnode-pod-kill-594-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9391093/artifacts-indexnode-pod-kill-594-server-logs.tar.gz)
[artifacts-indexnode-pod-kill-594-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9391095/artifacts-indexnode-pod-kill-594-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/780/pipeline
[artifacts-indexnode-pod-kill-780-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9441088/artifacts-indexnode-pod-kill-780-server-logs.tar.gz)
[artifacts-indexnode-pod-kill-780-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9441090/artifacts-indexnode-pod-kill-780-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/796/pipeline
log:
[artifacts-indexnode-pod-kill-796-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9441116/artifacts-indexnode-pod-kill-796-server-logs.tar.gz)
[artifacts-indexnode-pod-kill-796-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9441118/artifacts-indexnode-pod-kill-796-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
It reproduced stably, so set it as critical

**Comment by zhuwenxing** [comment]
It also happened in 2.1.0 branch

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-for-release/detail/chaos-test-for-release/9/pipeline/

log:
[artifacts-indexnode-pod-kill-9-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9451135/artifacts-indexnode-pod-kill-9-server-logs.tar.gz)
[artifacts-indexnode-pod-kill-9-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9451137/artifacts-indexnode-pod-kill-9-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
chaos type: pod-kill image tag: 2.1.0-20220921-a0ab90ea target pod: indexnode
failed job:https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-for-release/detail/chaos-test-for-release/746/pipeline
log:
[artifacts-indexnode-pod-kill-746-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9621623/artifacts-indexnode-pod-kill-746-server-logs.tar.gz)

[artifacts-indexnode-pod-kill-746-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9621624/artifacts-indexnode-pod-kill-746-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
Verified and passed in version `master-20221020-e8ca754d`
