### ISSUE TITLE
[Bug]: Search failed when running `verify_all_collections.py` with error `stream operation failed: deadline exceed`  after querynode pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#18756]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220820-9589bd3
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):  pymilvus==2.2.0.dev19
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
21:55:03  check collection Checker__9qMXgxJ5
21:55:03  collection is exist
21:55:03  
21:55:03  Create collection...
21:55:03  
21:55:03  Insert 3000 vectors cost 0.2967 seconds
21:55:03  
21:55:03  Get collection entities...
21:55:03  38240
21:55:03  
21:55:03  Get collection entities cost 2.5238 seconds
21:55:03  
21:55:03  Create index...
21:55:03  
21:55:03  Create index cost 0.5135 seconds
21:55:03  
21:55:03  Get replicas number
21:55:03  
21:55:03  Replicas number is 1
21:55:03  
21:55:03  load collection...
21:55:03  
21:55:03  load collection cost 0.0026 seconds
21:55:03  
21:55:03  Search...
21:55:03  Traceback (most recent call last):
21:55:03    File "scripts/verify_all_collections.py", line 138, in <module>
21:55:03      hello_milvus(collection_name)
21:55:03    File "scripts/verify_all_collections.py", line 95, in hello_milvus
21:55:03      "int64 > 100", output_fields=["int64", "float"], timeout=TIMEOUT
21:55:03    File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 718, in search
21:55:03      partition_names, output_fields, round_decimal, timeout=timeout, schema=schema_dict, **kwargs)
21:55:03    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 96, in handler
21:55:03      raise e
21:55:03    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 92, in handler
21:55:03      return func(*args, **kwargs)
21:55:03    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 74, in handler
21:55:03      raise e
21:55:03    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 48, in handler
21:55:03      return func(self, *args, **kwargs)
21:55:03    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 452, in search
21:55:03      return self._execute_search_requests(requests, timeout, **_kwargs)
21:55:03    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 416, in _execute_search_requests
21:55:03      raise pre_err
21:55:03    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 407, in _execute_search_requests
21:55:03      raise MilvusException(response.status.error_code, response.status.reason)
21:55:03  pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=13, reason=stream operation failed: deadline exceed)>

```

### Expected Behavior

all test cases passed

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/598/pipeline
log:
[artifacts-querynode-pod-kill-598-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9391007/artifacts-querynode-pod-kill-598-server-logs.tar.gz)

[artifacts-querynode-pod-kill-598-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9391009/artifacts-querynode-pod-kill-598-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
querynode pod failure 

Not exactly the same, the new error message is `pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=2, reason=stream operation failed: taskScheduler AddReadTask context is done)>`

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/913/pipeline
log:
[artifacts-querynode-pod-failure-913-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9474357/artifacts-querynode-pod-failure-913-server-logs.tar.gz)
[artifacts-querynode-pod-failure-913-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9474358/artifacts-querynode-pod-failure-913-pytest-logs.tar.gz)

**Comment by binbinlv** [comment]
Same error appears in CI (query interface):
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-19207/14/pipeline/142/

1. milvus log: [artifacts-milvus-distributed-PR-19207-14-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20HA%20CI/job/PR-19207/14/artifact/artifacts-milvus-distributed-PR-19207-14-pymilvus-e2e-logs.tar.gz)
2. collection name: delete_7gNmV7DL
3. errors:
```
[2022-09-16T06:44:58.118Z] [2022-09-16 06:44:45 - DEBUG - ci_test]: (api_request)  : [Collection.query] args: ['int64 in [0]', None, None, 20], kwargs: {} (api_request.py:56)
[2022-09-16T06:44:58.118Z] [2022-09-16 06:44:45 - ERROR - pymilvus.decorators]: RPC error: [query], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Query, QueryNode ID = 5, reason=stream operation failed: deadline exceed)>, <Time:{'RPC start': '2022-09-16 06:44:45.731970', 'RPC error': '2022-09-16 06:44:45.736601'}> (decorators.py:100)
[2022-09-16T06:44:58.118Z] [2022-09-16 06:44:45 - ERROR - ci_test]: Traceback (most recent call last):
[2022-09-16T06:44:58.118Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2022-09-16T06:44:58.119Z]     res = func(*args, **_kwargs)
[2022-09-16T06:44:58.119Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2022-09-16T06:44:58.119Z]     return func(*arg, **kwargs)
[2022-09-16T06:44:58.119Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 805, in query
[2022-09-16T06:44:58.119Z]     res = conn.query(self._name, expr, output_fields, partition_names, timeout=timeout, schema=schema_dict, **kwargs)
[2022-09-16T06:44:58.119Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 101, in handler
[2022-09-16T06:44:58.119Z]     raise e
[2022-09-16T06:44:58.119Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 97, in handler
[2022-09-16T06:44:58.119Z]     return func(*args, **kwargs)
[2022-09-16T06:44:58.119Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 127, in handler
[2022-09-16T06:44:58.119Z]     ret = func(self, *args, **kwargs)
[2022-09-16T06:44:58.119Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 79, in handler
[2022-09-16T06:44:58.119Z]     raise e
[2022-09-16T06:44:58.119Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 50, in handler
[2022-09-16T06:44:58.119Z]     return func(self, *args, **kwargs)
[2022-09-16T06:44:58.119Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 962, in query
[2022-09-16T06:44:58.119Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2022-09-16T06:44:58.119Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Query, QueryNode ID = 5, reason=stream operation failed: deadline exceed)>
[2022-09-16T06:44:58.119Z]  (api_request.py:39)
[2022-09-16T06:44:58.119Z] [2022-09-16 06:44:45 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Query, QueryNode ID = 5, reason=stream operation failed: deadline exceed)> (api_request.py:40)
```

**Comment by jiaoew1991** [comment]
/assign @sunby 
/unassign 

it still happened with QueryCoordV2

**Comment by zhuwenxing** [comment]
failed in CI 
failed job: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-19267/1/pipeline/


failed case: FAILED testcases/test_delete.py::TestDeleteOperation::test_delete_sealed_data_channel_delete 
```
436093198101118980, success count: 0, err count: 0)  (api_request.py:31)

[2022-09-19T04:58:58.906Z] [2022-09-19 04:58:50 - DEBUG - ci_test]: (api_request)  : [Collection.query] args: ['int64 in [0]', None, None, 20], kwargs: {} (api_request.py:56)

[2022-09-19T04:58:58.906Z] [2022-09-19 04:58:50 - ERROR - pymilvus.decorators]: RPC error: [query], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Query, QueryNode ID = 4, reason=stream operation failed: deadline exceed)>, <Time:{'RPC start': '2022-09-19 04:58:50.406961', 'RPC error': '2022-09-19 04:58:50.409639'}> (decorators.py:100)

[2022-09-19T04:58:58.906Z] [2022-09-19 04:58:50 - ERROR - ci_test]: Traceback (most recent call last):

[2022-09-19T04:58:58.906Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2022-09-19T04:58:58.906Z]     res = func(*args, **_kwargs)

[2022-09-19T04:58:58.906Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2022-09-19T04:58:58.906Z]     return func(*arg, **kwargs)

[2022-09-19T04:58:58.906Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 805, in query

[2022-09-19T04:58:58.906Z]     res = conn.query(self._name, expr, output_fields, partition_names, timeout=timeout, schema=schema_dict, **kwargs)

[2022-09-19T04:58:58.906Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 101, in handler

[2022-09-19T04:58:58.906Z]     raise e

[2022-09-19T04:58:58.906Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 97, in handler

[2022-09-19T04:58:58.906Z]     return func(*args, **kwargs)

[2022-09-19T04:58:58.906Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 127, in handler

[2022-09-19T04:58:58.906Z]     ret = func(self, *args, **kwargs)

[2022-09-19T04:58:58.906Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 79, in handler

[2022-09-19T04:58:58.906Z]     raise e

[2022-09-19T04:58:58.906Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 50, in handler

[2022-09-19T04:58:58.906Z]     return func(self, *args, **kwargs)

[2022-09-19T04:58:58.906Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 962, in query

[2022-09-19T04:58:58.906Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2022-09-19T04:58:58.906Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Query, QueryNode ID = 4, reason=stream operation failed: deadline exceed)>

[2022-09-19T04:58:58.906Z]  (api_request.py:39)

[2022-09-19T04:58:58.906Z] [2022-09-19 04:58:50 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Query, QueryNode ID = 4, reason=stream operation failed: deadline exceed)> (api_request.py:40)
```
