### ISSUE TITLE
Annoy search failed

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#1881]
**Describe the bug**
```
02:39:50  2020-04-07:18:39:49,274 INFO     [client.py:209] Server command: get_config *, result: {"cache_config":{"cache_insert_data":"false","cpu_cache_capacity":"32","cpu_cache_threshold":"0.7","insert_buffer_size":"1"},"db_config":{"archive_days_threshold":"0","archive_disk_threshold":"0","auto_flush_interval":"1","backend_url":"sqlite://:@:/","preload_table":""},"engine_config":{"omp_thread_num":"0","use_avx512":"true","use_blas_threshold":"0"},"metric_config":{"address":"192.168.1.237","enable_monitor":"true","port":"9091"},"server_config":{"address":"0.0.0.0","deploy_mode":"single","port":"19530","time_zone":"UTC+8","web_port":"19121"},"storage_config":{"primary_path":"/test/milvus/db_data_7/sift_10m_1024_128_l2_annoy_wal","s3_access_key":"minioadmin","s3_address":"127.0.0.1","s3_bucket":"milvus-bucket","s3_enable":"false","s3_port":"9000","s3_secret_key":"minioadmin","secondary_path":""},"tracing_config":{"json_config_path":""},"wal_config":{"buffer_size":"128","enable":"true","recovery_error_ignore":"true","wal_path":"/test/milvus/db_data_7/sift_10m_1024_128_l2_annoy_wal/wal"}}
02:39:50  2020-04-07:18:39:49,290 INFO     [k8s_runner.py:230] 10000000
02:39:50  2020-04-07:18:39:49,299 INFO     [k8s_runner.py:232] {'index_type': 'annoy', 'index_param': {'n_trees': 8}}
02:39:50  2020-04-07:18:39:49,315 INFO     [client.py:34] Milvus preload_collection run in 0.02s
02:39:50  2020-04-07:18:39:49,315 INFO     [k8s_runner.py:234] Start warm up query
02:39:50  2020-04-07:18:39:50,343 INFO     [runner.py:196] Start query, query params: top-k: 1, nq: 1, actually length of vectors: 1
02:39:50  2020-04-07:18:39:50,343 INFO     [runner.py:198] Start run query, run 1 of 2
02:39:50  2020-04-07:18:39:50,352 ERROR    [client.py:72] Failed to load index file: DISK2CPU
02:39:50  2020-04-07:18:39:50,352 ERROR    [main.py:69] Status not ok
02:39:50  2020-04-07:18:39:50,354 ERROR    [main.py:70] Traceback (most recent call last):
02:39:50    File "main.py", line 67, in queue_worker
02:39:50      runner.run(run_type, collection)
02:39:50    File "/home/jenkins/agent/workspace/milvus-benchmark/milvus_benchmark/k8s_runner.py", line 235, in run
02:39:50      res = self.do_query(milvus_instance, collection_name, [1], [1], 2, search_param=search_params[0])
02:39:50    File "/home/jenkins/agent/workspace/milvus-benchmark/milvus_benchmark/runner.py", line 200, in do_query
02:39:50      query_res = milvus.query(vectors, top_k, search_param=search_param)
02:39:50    File "/home/jenkins/agent/workspace/milvus-benchmark/milvus_benchmark/client.py", line 32, in wrapper
02:39:50      result = func(*args, **kwargs)
02:39:50    File "/home/jenkins/agent/workspace/milvus-benchmark/milvus_benchmark/client.py", line 146, in query
02:39:50      self.check_status(status)
02:39:50    File "/home/jenkins/agent/workspace/milvus-benchmark/milvus_benchmark/client.py", line 73, in check_status
02:39:50      raise Exception("Status not ok")
02:39:50  Exception: Status not ok
```
**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)

**Screenshots**

**Additional context**

**Comment by del-zhenwu** [comment]
```
2020-04-08 02:39:50,356 | ERROR | default | [ENGINE] ExecutionEngineImpl: index is null, failed to search
2020-04-08 02:39:50,356 | ERROR | default | [ENGINE] Failed to load vector index: std::bad_alloc
2020-04-08 02:39:50,356 | ERROR | default | [ENGINE] Failed to load index from /test/milvus/db_data_7/sift_10m_1024_128_l2_annoy_wal/db/tables/sift_10m_1024_128_l2/1583586239353258000/1585966372400991000
2020-04-08 02:39:50,357 | ERROR | default | [ENGINE] ExecutionEngineImpl: index is null, failed to search
2020-04-08 02:39:50,357 | ERROR | default | [ENGINE] Failed to load vector index: std::bad_alloc
2020-04-08 02:39:50,357 | ERROR | default | [ENGINE] Failed to load index from /test/milvus/db_data_7/sift_10m_1024_128_l2_annoy_wal/db/tables/sift_10m_1024_128_l2/1583586495355089000/1585966415631452000
2020-04-08 02:39:50,357 | ERROR | default | [SERVER] Request failed with code: Error code(30001): Failed to load index file: DISK2CPU
```
