### ISSUE TITLE
[Bug]: Search failed after upgrade from 2.1.0 to master-20220820-9589bd3 and later images

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#18824]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220820-9589bd3
- Deployment mode(standalone or cluster): both
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus==2.2.0.dev19
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Search failed after upgrade
```
collection name: task_1_ANNOY
load collection
load time: 0.0066
{'metric_type': 'L2', 'params': {'search_k': 1000}}

Search...
Traceback (most recent call last):
  File "scripts/action_after_upgrade.py", line 98, in <module>
    task_1(data_size, host)
  File "scripts/action_after_upgrade.py", line 19, in task_1
    load_and_search(prefix)
  File "/home/runner/work/milvus/milvus/tests/python_client/deploy/scripts/utils.py", line 165, in load_and_search
    res = c.search(
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 717, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 96, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 92, in handler
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 48, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 452, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 416, in _execute_search_requests
    raise pre_err
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 407, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=9, reason=ShardCluster for by-dev-rootcoord-dml_10_435428525[39](https://github.com/milvus-io/milvus/runs/7934118743?check_suite_focus=true#step:14:40)3051649v0 replicaID 435[42](https://github.com/milvus-io/milvus/runs/7934118743?check_suite_focus=true#step:14:43)8[50](https://github.com/milvus-io/milvus/runs/7934118743?check_suite_focus=true#step:14:51)97669099[59](https://github.com/milvus-io/milvus/runs/7934118743?check_suite_focus=true#step:14:60) is no available)>
```

### Expected Behavior

all test cases passed

### Steps To Reproduce

```markdown
see https://github.com/milvus-io/milvus/runs/7934118743?check_suite_focus=true
```

### Milvus Log

failed job: https://github.com/milvus-io/milvus/runs/7934118743?check_suite_focus=true
log: https://github.com/milvus-io/milvus/suites/7904196603/artifacts/336261370

failed job: https://github.com/milvus-io/milvus/runs/7934118825?check_suite_focus=true
log: https://github.com/milvus-io/milvus/suites/7904196603/artifacts/336261369

### Anything else?

It works well in master-20220819-fc42ee5 so that the issue may be introduced between master-20220819-fc42ee5 and master-20220820-9589bd3

**Comment by zhuwenxing** [comment]
I check the PRs between two images, https://github.com/milvus-io/milvus/pull/18290 is the only PR that changed the code

**Comment by jiaoew1991** [comment]
from the log we can find that outdated node did not cleanup from metadata
(`nodeId=4` is the old node, `nodeId=9` is current node)
<img width="1469" alt="image" src="https://user-images.githubusercontent.com/2297455/187147943-446c8269-5bb5-498e-bcde-94d1ed2ae672.png">

further more there is only one node online, so the balance task cannot be trigger 
<img width="1443" alt="image" src="https://user-images.githubusercontent.com/2297455/187148748-29875468-4b08-45f3-8d24-21ebc95d6ed1.png">

The QueryCoordV2 will fix bugs like this situation, we can look forward to it

**Comment by jiaoew1991** [comment]
we can retry it with querycoordV2

/assign @zhuwenxing 
/unassign

**Comment by zhuwenxing** [comment]
It works well for 2.1.4 --> master-20221010-85e04d84, so close it.
