### ISSUE TITLE
[Bug]: Search failed with error `ShardCluster for by-dev-rootcoord-dml_xxxv1 replicaID xxx is no available` after upgrade or reinstallation

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#18828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.0-20220824-85bbba95
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2022-08-25T05:22:49.101Z] =========================== short test summary info ============================

[2022-08-25T05:22:49.101Z] FAILED testcases/test_action_second_deployment.py::TestActionSecondDeployment::test_check[deploy_test_index_type_BIN_IVF_FLAT_is_compacted_is_compacted_segment_status_all_is_vector_indexed_is_vector_indexed_is_string_indexed_is_string_indexed_replica_number_2_is_deleted_is_deleted_data_size_3000]

[2022-08-25T05:22:49.101Z] FAILED testcases/test_action_second_deployment.py::TestActionSecondDeployment::test_check[deploy_test_index_type_BIN_IVF_FLAT_is_compacted_not_compacted_segment_status_all_is_vector_indexed_is_vector_indexed_is_string_indexed_is_string_indexed_replica_number_2_is_deleted_is_deleted_data_size_3000]

[2022-08-25T05:22:49.101Z] FAILED testcases/test_action_second_deployment.py::TestActionSecondDeployment::test_check[deploy_test_index_type_BIN_IVF_FLAT_is_compacted_is_compacted_segment_status_all_is_vector_indexed_is_vector_indexed_is_string_indexed_not_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000]

[2022-08-25T05:22:49.101Z] FAILED testcases/test_action_second_deployment.py::TestActionSecondDeployment::test_check[deploy_test_index_type_BIN_IVF_FLAT_is_compacted_is_compacted_segment_status_all_is_vector_indexed_is_vector_indexed_is_string_indexed_is_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000]

[2022-08-25T05:22:49.101Z] FAILED testcases/test_action_second_deployment.py::TestActionSecondDeployment::test_check[deploy_test_index_type_BIN_IVF_FLAT_is_compacted_not_compacted_segment_status_all_is_vector_indexed_is_vector_indexed_is_string_indexed_is_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000]

[2022-08-25T05:22:49.101Z] FAILED testcases/test_action_second_deployment.py::TestActionSecondDeployment::test_check[deploy_test_index_type_HNSW_is_compacted_not_compacted_segment_status_all_is_vector_indexed_is_vector_indexed_is_string_indexed_is_string_indexed_replica_number_2_is_deleted_is_deleted_data_size_3000]

[2022-08-25T05:22:49.101Z] =================== 6 failed, 92 passed in 532.53s (0:08:52) ===================
```

error
```
[2022-08-25T05:22:49.100Z] [2022-08-25 05:22:13 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.09528332629853829, 0.07664601923178825, 0.11831444816566296, 0.03258097764454299, 0.07937881005762316, 0.06692384312195564, 0.07470019680492655, 0.05553175865817177, 0.1178697058730574, 0.08056297591600146, 0.021980011028491266, 0.09184858359008219, 0.03749160597168563, 0.05370190391705239, 0.0......, kwargs: {} (api_request.py:56)

[2022-08-25T05:22:49.100Z] [2022-08-25 05:22:13 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=14, reason=ShardCluster for by-dev-rootcoord-dml_221_435527069528752129v1 replicaID 435527013730355506 is no available)>, <Time:{'RPC start': '2022-08-25 05:22:13.208956', 'RPC error': '2022-08-25 05:22:13.213810'}> (decorators.py:95)

[2022-08-25T05:22:49.100Z] [2022-08-25 05:22:13 - ERROR - ci_test]: Traceback (most recent call last):

[2022-08-25T05:22:49.100Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2022-08-25T05:22:49.100Z]     res = func(*args, **_kwargs)

[2022-08-25T05:22:49.100Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2022-08-25T05:22:49.100Z]     return func(*arg, **kwargs)

[2022-08-25T05:22:49.100Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 718, in search

[2022-08-25T05:22:49.100Z]     partition_names, output_fields, round_decimal, timeout=timeout, schema=schema_dict, **kwargs)

[2022-08-25T05:22:49.100Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 96, in handler

[2022-08-25T05:22:49.100Z]     raise e

[2022-08-25T05:22:49.100Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 92, in handler

[2022-08-25T05:22:49.100Z]     return func(*args, **kwargs)

[2022-08-25T05:22:49.100Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 74, in handler

[2022-08-25T05:22:49.100Z]     raise e

[2022-08-25T05:22:49.100Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 48, in handler

[2022-08-25T05:22:49.100Z]     return func(self, *args, **kwargs)

[2022-08-25T05:22:49.100Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 452, in search

[2022-08-25T05:22:49.100Z]     return self._execute_search_requests(requests, timeout, **_kwargs)

[2022-08-25T05:22:49.100Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 416, in _execute_search_requests

[2022-08-25T05:22:49.101Z]     raise pre_err

[2022-08-25T05:22:49.101Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 407, in _execute_search_requests

[2022-08-25T05:22:49.101Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2022-08-25T05:22:49.101Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=14, reason=ShardCluster for by-dev-rootcoord-dml_221_435527069528752129v1 replicaID 435527013730355506 is no available)>

[2022-08-25T05:22:49.101Z]  (api_request.py:39)

[2022-08-25T05:22:49.101Z] [2022-08-25 05:22:13 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=14, reason=ShardCluster for by-dev-rootcoord-dml_221_435527069528752129v1 replicaID 435527013730355506 is no available)> (api_request.py:40)
```

### Expected Behavior

all test cases passed

### Steps To Reproduce

```markdown
see anything else
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test/detail/deploy_test/131/pipeline
log:
[artifacts-cluster-upgrade-131-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/9422272/artifacts-cluster-upgrade-131-server-logs.1.tar.gz)
[artifacts-cluster-upgrade-131-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9422277/artifacts-cluster-upgrade-131-pytest-logs.tar.gz)

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test/detail/deploy_test/130/pipeline
log: 
[artifacts-standalone-upgrade-130-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9422284/artifacts-standalone-upgrade-130-server-logs.tar.gz)
[artifacts-standalone-upgrade-130-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9422285/artifacts-standalone-upgrade-130-pytest-logs.tar.gz)
 

### Anything else?

![image](https://user-images.githubusercontent.com/12268675/186598240-c2a89343-14f7-41b9-a0ea-bb0ce03d1952.png)

**Comment by zhuwenxing** [comment]
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test/detail/deploy_test/129/pipeline
log:
[artifacts-cluster-reinstall-129-server-logs (2).tar.gz](https://github.com/milvus-io/milvus/files/9429548/artifacts-cluster-reinstall-129-server-logs.2.tar.gz)

[artifacts-cluster-reinstall-129-pytest-logs (2).tar.gz](https://github.com/milvus-io/milvus/files/9429549/artifacts-cluster-reinstall-129-pytest-logs.2.tar.gz)

**Comment by zhuwenxing** [comment]
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_for_release/detail/deploy_test_for_release/8/pipeline

log: 
[artifacts-cluster-reinstall-8-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9445407/artifacts-cluster-reinstall-8-pytest-logs.tar.gz)
[artifacts-cluster-reinstall-8-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9445408/artifacts-cluster-reinstall-8-server-logs.tar.gz)

you can get the whole log by following setting
![image](https://user-images.githubusercontent.com/12268675/187226787-e611ae51-1228-48ee-899c-23aacd6e7633.png)

**Comment by zhuwenxing** [comment]
> failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_for_release/detail/deploy_test_for_release/8/pipeline
> 
> log: [artifacts-cluster-reinstall-8-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9445407/artifacts-cluster-reinstall-8-pytest-logs.tar.gz) [artifacts-cluster-reinstall-8-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9445408/artifacts-cluster-reinstall-8-server-logs.tar.gz)
> 
> you can get the whole log by following setting ![image](https://user-images.githubusercontent.com/12268675/187226787-e611ae51-1228-48ee-899c-23aacd6e7633.png)


The collection name is also the failed test case name.
* deploy_test_index_type_BIN_IVF_FLAT_is_compacted_not_compacted_segment_status_all_is_vector_indexed_not_vector_indexed_is_string_indexed_is_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000
* deploy_test_index_type_BIN_IVF_FLAT_is_compacted_is_compacted_segment_status_all_is_vector_indexed_not_vector_indexed_is_string_indexed_is_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000

**Comment by zhuwenxing** [comment]
upgrade : v2.1.0 --> 2.1.0-20220830-a926a7d2
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_for_release/detail/deploy_test_for_release/10/pipeline/274

log:
[artifacts-cluster-upgrade-10-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9450437/artifacts-cluster-upgrade-10-server-logs.tar.gz)
[artifacts-cluster-upgrade-10-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9450445/artifacts-cluster-upgrade-10-pytest-logs.tar.gz)

two cases failed with error message `fail to search on all shard leaders, err=fail to Search, QueryNode ID=13, reason=ShardCluster for by-dev-rootcoord-dml_xxx replicaID xxx is no available`

**Comment by zhuwenxing** [comment]
standalone reinstall: 2.1.0-20220830-a926a7d2
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_for_release/detail/deploy_test_for_release/16/pipeline

log:
[artifacts-standalone-reinstall-16-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9450789/artifacts-standalone-reinstall-16-server-logs.tar.gz)
[artifacts-standalone-reinstall-16-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9450794/artifacts-standalone-reinstall-16-pytest-logs.tar.gz)

one cases failed with error message `fail to search on all shard leaders, err=fail to Search, QueryNode ID=10, reason=ShardCluster for by-dev-rootcoord-dml_98_435642516789264385v0 replicaID 435642493582442890 is no available`

**Comment by jiaoew1991** [comment]
same as https://github.com/milvus-io/milvus/issues/18799#issuecomment-1231519114

**Comment by jiaoew1991** [comment]
After the upgrade/reinstallation, there are still old nodes in etcd, and the sync segment is before the offline node is removed. Causes QueryNode's segment replica information to include the offline node. then the search request will try to get result from the offline node.

**Comment by zhuwenxing** [comment]
v2.1.0 --> 2.1.0-20220902-853793a

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_for_release/detail/deploy_test_for_release/34/pipeline

log:
[artifacts-cluster-upgrade-34-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9487650/artifacts-cluster-upgrade-34-pytest-logs.tar.gz)

[artifacts-cluster-upgrade-34-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9487652/artifacts-cluster-upgrade-34-server-logs.tar.gz)

**Comment by zhuwenxing** [comment]
v2.1.0  --> 2.1.0-20220906-7affd93
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_for_release/detail/deploy_test_for_release/58/pipeline

log:
[artifacts-cluster-upgrade-58-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9503205/artifacts-cluster-upgrade-58-pytest-logs.tar.gz)
[artifacts-cluster-upgrade-58-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9503208/artifacts-cluster-upgrade-58-server-logs.tar.gz)

![image](https://user-images.githubusercontent.com/12268675/188802405-1c1c2fe6-f47e-47f1-a839-eeec2200602d.png)

![image](https://user-images.githubusercontent.com/12268675/188802504-2deac5b8-4519-47d4-9a08-5dc76704ebd2.png)

**Comment by zhuwenxing** [comment]
Not reproduced recently, but the issue changed to search timeout https://github.com/milvus-io/milvus/issues/19087

**Comment by zhuwenxing** [comment]
@congqixia 
Please help to take a look for latest failed job

**Comment by zhuwenxing** [comment]
Kafka cluster upgrade
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_kafka_for_release/detail/deploy_test_kafka_for_release/56/pipeline

log:
[artifacts-cluster-upgrade-56-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9525368/artifacts-cluster-upgrade-56-server-logs.tar.gz)

[artifacts-cluster-upgrade-56-pytest-logs (2).tar.gz](https://github.com/milvus-io/milvus/files/9525369/artifacts-cluster-upgrade-56-pytest-logs.2.tar.gz)

**Comment by zhuwenxing** [comment]
kafka version
cluster reinstall `2.1.0-20220913-3c3ba55`
failed job:
https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_kafka_for_release/detail/deploy_test_kafka_for_release/96/pipeline/300
log:
[artifacts-cluster-reinstall-96-pytest-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/9571624/artifacts-cluster-reinstall-96-pytest-logs.1.tar.gz)
[artifacts-cluster-reinstall-96-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/9571625/artifacts-cluster-reinstall-96-server-logs.1.tar.gz)

![image](https://user-images.githubusercontent.com/12268675/190310330-22dabbf9-5fc4-4be6-9d96-62216d11c990.png)

**Comment by zhuwenxing** [comment]
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_kafka_for_release/detail/deploy_test_kafka_for_release/131/pipeline

log:
[artifacts-cluster-reinstall-131-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9605320/artifacts-cluster-reinstall-131-server-logs.tar.gz)
[artifacts-cluster-reinstall-131-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9605322/artifacts-cluster-reinstall-131-pytest-logs.tar.gz)

collection name: `deploy_test_index_type_BIN_IVF_FLAT_is_compacted_not_compacted_segment_status_all_is_vector_indexed_not_vector_indexed_is_string_indexed_is_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000`

```
[2022-09-20T06:50:22.045Z] [2022-09-20 06:44:28 - DEBUG - ci_test]: (api_request)  : [Collection.drop_index] args: [], kwargs: {'timeout': 20, 'index_name': '_default_string_idx'} (api_request.py:56)
[2022-09-20T06:50:22.045Z] [2022-09-20 06:44:28 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)
[2022-09-20T06:50:22.045Z] [2022-09-20 06:44:28 - INFO - ci_test]: [test][2022-09-20T06:44:28Z] [0.01042321s] deploy_test_index_type_BIN_IVF_FLAT_is_compacted_not_compacted_segment_status_all_is_vector_indexed_not_vector_indexed_is_string_indexed_is_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000 drop_index -> None (wrapper.py:30)
[2022-09-20T06:50:22.045Z] [2022-09-20 06:44:28 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[b'\x98\xe8\x02M[@\xaa\xf7CjF\xa8\xee\xdeG\xba', b's\xb5L0Hj\xd7\x93\xc0\xa2zkDQi\xcc'], 'binary_vector', {'metric_type': 'HAMMING', 'params': {'nprobe': 10}}, 10, 'int64 >= 0', None, ['int64'], 20, -1], kwargs: {} (api_request.py:56)
[2022-09-20T06:50:22.045Z] [2022-09-20 06:44:35 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=22, reason=Search 21 failed, reason cannot find sealed segment 436117112487936002 in QueryNode err %!w(<nil>))>, <Time:{'RPC start': '2022-09-20 06:44:28.760546', 'RPC error': '2022-09-20 06:44:35.289798'}> (decorators.py:100)
[2022-09-20T06:50:22.045Z] [2022-09-20 06:44:35 - ERROR - ci_test]: Traceback (most recent call last):
[2022-09-20T06:50:22.045Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2022-09-20T06:50:22.045Z]     res = func(*args, **_kwargs)
[2022-09-20T06:50:22.045Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2022-09-20T06:50:22.045Z]     return func(*arg, **kwargs)
[2022-09-20T06:50:22.045Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 718, in search
[2022-09-20T06:50:22.045Z]     partition_names, output_fields, round_decimal, timeout=timeout, schema=schema_dict, **kwargs)
[2022-09-20T06:50:22.045Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 101, in handler
[2022-09-20T06:50:22.045Z]     raise e
[2022-09-20T06:50:22.045Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 97, in handler
[2022-09-20T06:50:22.045Z]     return func(*args, **kwargs)
[2022-09-20T06:50:22.045Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 127, in handler
[2022-09-20T06:50:22.045Z]     ret = func(self, *args, **kwargs)
[2022-09-20T06:50:22.045Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 79, in handler
[2022-09-20T06:50:22.045Z]     raise e
[2022-09-20T06:50:22.045Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 50, in handler
[2022-09-20T06:50:22.045Z]     return func(self, *args, **kwargs)
[2022-09-20T06:50:22.045Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 472, in search
[2022-09-20T06:50:22.045Z]     return self._execute_search_requests(requests, timeout, **_kwargs)
[2022-09-20T06:50:22.045Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 436, in _execute_search_requests
[2022-09-20T06:50:22.045Z]     raise pre_err
[2022-09-20T06:50:22.045Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 427, in _execute_search_requests
[2022-09-20T06:50:22.045Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2022-09-20T06:50:22.045Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=22, reason=Search 21 failed, reason cannot find sealed segment 436117112487936002 in QueryNode err %!w(<nil>))>
[2022-09-20T06:50:22.045Z]  (api_request.py:39)
```

**Comment by congqixia** [comment]
Hi @zhuwenxing , does this problem still persist in querycoord v2?

**Comment by yanliang567** [comment]
@zhuwenxing any chance to verify the fix?
