### ISSUE TITLE
[Bug]: [Diskann Index]Milvus binary vectors not support diskann index, so an error should be reported instead of a timeout

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#18837]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:xige-16-build-diskann-25-11-15-f2d2afc0f-20220825
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0dev23
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

**Milvus binary vectors do not support diskann index, should change the timeout to run out of exception**

testcase：
   ```
    @pytest.mark.tags(CaseLabel.L1)
    def test_create_diskann_index_with_binary(self):
        """
        target: test create diskann index with binary vector
        method: 1.create collection and insert binary data
                       2.create diskann index 
        expected: report an error
        """
        c_name = cf.gen_unique_str(prefix)
        collection_w = self.init_collection_wrap(name=c_name, schema=default_binary_schema)
        df, _ = cf.gen_default_binary_dataframe_data()
        collection_w.insert(data=df)
        collection_w.create_index(default_binary_vec_field_name, ct.default_diskann_index, index_name=binary_field_name)
```

log：
```

[2022-08-25 18:38:32 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['binary_vector', {'index_type': 'DISKANN', 'metric_type': 'L2', 'params': {}}], kwargs: {'timeout': 40, 'index_name': 'binary_vector'} (api_request.py:56)
[2022-08-25 18:39:15 - ERROR - pymilvus.decorators]: RPC error: [wait_for_creating_index], <MilvusException: (code=1, message=CreateIndex Timeout)>, <Time:{'RPC start': '2022-08-25 18:38:35.154907', 'RPC error': '2022-08-25 18:39:15.218184'}> (decorators.py:100)
[2022-08-25 18:39:15 - ERROR - pymilvus.decorators]: RPC error: [create_index], <MilvusException: (code=1, message=CreateIndex Timeout)>, <Time:{'RPC start': '2022-08-25 18:38:32.402984', 'RPC error': '2022-08-25 18:39:15.218698'}> (decorators.py:100)
[2022-08-25 18:39:15 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/jingjing/Workspace/milvus/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/Users/jingjing/Workspace/milvus/tests/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 1082, in create_index
    return conn.create_index(self._name, field_name, index_params,
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 101, in handler
    raise e
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 97, in handler
    return func(*args, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 127, in handler
    ret = func(self, *args, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 79, in handler
    raise e
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 615, in create_index
    index_success, fail_reason = self.wait_for_creating_index(collection_name=collection_name,
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 101, in handler
    raise e
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 97, in handler
    return func(*args, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 127, in handler
    ret = func(self, *args, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 79, in handler
    raise e
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 688, in wait_for_creating_index
    raise MilvusException(1, "CreateIndex Timeout")
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=CreateIndex Timeout)>
 (api_request.py:39)
[2022-08-25 18:39:15 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=CreateIndex Timeout)> (api_request.py:40)
```

### Steps To Reproduce

```markdown
1. create collection
2. insert binary vector data
3. create a diskann index
```

**Comment by xige-16** [comment]
it will be fixed soon.

**Comment by xige-16** [comment]
build disk index for binary vector, throw the error message:
```
message=field data type BinaryVector don't support the index build type DISKANN
```

should has been fixed, please verify @jingkl 
/assign @jingkl 
/unassign @xige-16

**Comment by jingkl** [comment]
**This has been verified and the following is the output error statement**
master-20220929-64662919
pymilvus.2.2.0dev36

```
[2022-09-29 22:41:09 - ERROR - pymilvus.decorators]: RPC error: [create_index], <MilvusException: (code=1, message=field data type BinaryVector don't support the index build type DISKANN)>, <Time:{'RPC start': '2022-09-29 22:41:06.100645', 'RPC error': '2022-09-29 22:41:09.599847'}> (decorators.py:111)
[2022-09-29 22:41:09 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/jingjing/Workspace/milvus/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/Users/jingjing/Workspace/milvus/tests/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 1086, in create_index
    return conn.create_index(self._name, field_name, index_params,
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 112, in handler
    raise e
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 108, in handler
    return func(*args, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 139, in handler
    ret = func(self, *args, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 88, in handler
    raise e
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 565, in create_index
    raise MilvusException(status.error_code, status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=field data type BinaryVector don't support the index build type DISKANN)>
 (api_request.py:39)
[2022-09-29 22:41:09 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=field data type BinaryVector don't support the index build type DISKANN)> (api_request.py:40)
```
