### ISSUE TITLE
[Bug]: [benchmark][standalone]Milvus load collection failed,raise an error"collection has not been loaded to memory or load failed"

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#18845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.0-20220823-0c695347
- Deployment mode(standalone or cluster):stanalone
- SDK version(e.g. pymilvus v2.0.0rc2):2.1.2dev2
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server-instance
fouram-znxhg-5
server-configmap
server-single-16c64m
client-configmap
client-search-filter-sift50m-ivf-flat-2048
sever:
```
fouram-znxhg-5-etcd-0                                            1/1     Running    0             2m2s   10.104.1.161   4am-node10   <none>           <none>
fouram-znxhg-5-milvus-standalone-56b684b5dc-zhvcw                1/1     Running    0             2m2s   10.104.4.60    4am-node11   <none>           <none>
fouram-znxhg-5-minio-fb879c796-2wbzb                             1/1     Running    0             2m2s   10.104.4.61    4am-node11   <none>           <none>

```
log:

```
[2022-08-25 10:58:52,901] [    INFO] - Start load collection (milvus_benchmark.runners.search:293)
[2022-08-25 11:04:48,342] [   ERROR] - RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=collection sift_50m_128_l2 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-08-25 10:58:53.198939', 'RPC error': '2022-08-25 11:04:48.341908'}> (pymilvus.decorators:95)
[2022-08-25 11:04:48,342] [   ERROR] - RPC error: [load_collection], <MilvusException: (code=1, message=collection sift_50m_128_l2 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-08-25 10:58:52.901199', 'RPC error': '2022-08-25 11:04:48.342846'}> (pymilvus.decorators:95)
[2022-08-25 11:04:48,343] [   ERROR] - <MilvusException: (code=1, message=collection sift_50m_128_l2 has not been loaded to memory or load failed)> (milvus_benchmark.main:118)
[2022-08-25 11:04:48,345] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 87, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/search.py", line 295, in prepare
    self.milvus.load_collection(replica_number=replica_number, timeout=1200)
  File "/src/milvus_benchmark/client.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 581, in load_collection
    return self._milvus.load_collection(collection_name, **params)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/stub.py", line 195, in load_collection
    return handler.load_collection(collection_name=collection_name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 96, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 92, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 48, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 673, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 96, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 92, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 48, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 682, in wait_for_loading_collection
    return self._wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 711, in _wait_for_loading_collection
    progress = self.get_collection_loading_progress(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 690, in get_collection_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection sift_50m_128_l2 has not been loaded to memory or load failed)>
 (milvus_benchmark.main:119)
```
standalone:
<img width="1384" alt="截屏2022-08-26 10 47 18" src="https://user-images.githubusercontent.com/34296482/186807060-030d0fed-654b-4284-9318-e11494cbc4a6.png">

### Anything else?

client-search-filter-sift50m-ivf-flat-2048
```
    insert_search_performance:
      collections:
        -
          milvus:
            db_config.primary_path: /test/milvus/distribued/sift_50m_128_l2_ivf_flat
            wal_enable: true
          collection_name: sift_50m_128_l2
          ni_per: 50000
          other_fields: int1,int2,float1,double1
          build_index: true
          index_type: ivf_flat 
          index_param:
            nlist: 2048
          run_count: 2
          top_ks: [1, 10, 100, 1000]
          nqs: [1, 10, 100, 200, 500, 1000, 1200]
          filters:
            -
              range: "{'range': {'float1': {'GT': -1.0, 'LT': collection_size * 0.1}}}"
            -
              range: "{'range': {'float1': {'GT': -1.0, 'LT': collection_size * 0.5}}}"
            -
              range: "{'range': {'float1': {'GT': -1.0, 'LT': collection_size * 0.9}}}"
          search_params:
            -
              nprobe: 8
            -
              nprobe: 32
```

**Comment by yanliang567** [comment]
it looks like OOM, but we need to figure out 
1. does loading collection cost more memory?
2. or what tasks cost more memory at that time?
/assign @xige-16 
/unassign

**Comment by xige-16** [comment]
/assign @jiaoew1991 
please help

**Comment by jingkl** [comment]
server-instance
fouram-cluster-cron-1661893200-1
server-configmap
server-single-32c128m
client-configmap
client-get-local50m-512
2.1.0-20220830-a926a7d2
2.1.2dev2

```
fouram-cluster-cron-1661893200-1-etcd-0                           1/1     Running    0             2m8s    10.104.6.182   4am-node13   <none>           <none>
fouram-cluster-cron-1661893200-1-milvus-standalone-dcb7447957nv   1/1     Running    0             2m8s    10.104.4.150   4am-node11   <none>           <none>
fouram-cluster-cron-1661893200-1-minio-859ccbc89-xnjqt            1/1     Running    0             2m8s    10.104.6.147   4am-node13   <none>           <none>
```

```
[2022-08-30 22:55:42,487] [   ERROR] - RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=collection local_50m_512_l2 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-08-30 22:50:17.076853', 'RPC error': '2022-08-30 22:55:42.487285'}> (pymilvus.decorators:100)
[2022-08-30 22:55:42,487] [   ERROR] - RPC error: [load_collection], <MilvusException: (code=1, message=collection local_50m_512_l2 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-08-30 22:50:16.622221', 'RPC error': '2022-08-30 22:55:42.487575'}> (pymilvus.decorators:100)
[2022-08-30 22:55:42,487] [   ERROR] - <MilvusException: (code=1, message=collection local_50m_512_l2 has not been loaded to memory or load failed)> (milvus_benchmark.main:118)
[2022-08-30 22:55:42,488] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 87, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/get.py", line 131, in prepare
    self.milvus.load_collection(replica_number=replica_number, timeout=1200)
  File "/src/milvus_benchmark/client.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 591, in load_collection
    return self._milvus.load_collection(collection_name, **params)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/stub.py", line 195, in load_collection
    return handler.load_collection(collection_name=collection_name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 101, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 97, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 127, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 79, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 700, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 101, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 97, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 127, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 79, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 709, in wait_for_loading_collection
    return self._wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 738, in _wait_for_loading_collection
    progress = self.get_collection_loading_progress(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 717, in get_collection_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection local_50m_512_l2 has not been loaded to memory or load failed)>
 (milvus_benchmark.main:119)
```

**Comment by jiaoew1991** [comment]
this case can pass at 2.1.0 but failed after 2.1.2, need invest what different between this 2 versions

**Comment by jingkl** [comment]
@aoiasd Is there any progress?

**Comment by jingkl** [comment]
server-instance
fouram-cluster-cron-1663016400-5
server-configmap
server-single-16c64m
client-configmap
client-search-filter-sift50m-ivf-flat-2048

milvus: 2.1.0-20220909-36e333d
pymilvus :2.1.2dev9

```
fouram-cluster-cron-1663016400-5-etcd-0                           1/1     Running     0              2m30s   10.104.9.22    4am-node
14   <none>           <none>
fouram-cluster-cron-1663016400-5-milvus-standalone-6b666dcskxwp   1/1     Running     0              2m30s   10.104.1.72    4am-node
10   <none>           <none>
fouram-cluster-cron-1663016400-5-minio-7785b8b4b8-lzgc4           1/1     Running     0              2m30s   10.104.9.3     4am-node
14   <none>           <none>
```

```
[2022-09-12 22:38:22,260] [   ERROR] - RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=collection sift_50m_128_l2 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-09-12 22:31:13.593193', 'RPC error': '2022-09-12 22:38:22.259854'}> (pymilvus.decorators:95)
[2022-09-12 22:38:22,260] [   ERROR] - RPC error: [load_collection], <MilvusException: (code=1, message=collection sift_50m_128_l2 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-09-12 22:31:13.375420', 'RPC error': '2022-09-12 22:38:22.260486'}> (pymilvus.decorators:95)
[2022-09-12 22:38:22,260] [   ERROR] - <MilvusException: (code=1, message=collection sift_50m_128_l2 has not been loaded to memory or load failed)> (milvus_benchmark.main:118)
[2022-09-12 22:38:22,261] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 87, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/search.py", line 295, in prepare
    self.milvus.load_collection(replica_number=replica_number, timeout=1200)
  File "/src/milvus_benchmark/client.py", line 53, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 592, in load_collection
    return self._milvus.load_collection(collection_name, **params)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/stub.py", line 195, in load_collection
    return handler.load_collection(collection_name=collection_name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 96, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 92, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 48, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 673, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 96, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 92, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 48, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 682, in wait_for_loading_collection
    return self._wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 711, in _wait_for_loading_collection
    progress = self.get_collection_loading_progress(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 690, in get_collection_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection sift_50m_128_l2 has not been loaded to memory or load failed)>
 (milvus_benchmark.main:119)
```

**Comment by jingkl** [comment]
server-instance
fouram-cluster-cron-1663621200-1
server-configmap
server-single-32c128m
client-configmap
client-get-local50m-512

2.1.0-20220916-3c3ba55c
2.1.2dev9
server
```
NAME                                                              READY   STATUS             RESTARTS        AGE     IP
NODE         NOMINATED NODE   READINESS GATES
fouram-cluster-cron-1663621200-1-etcd-0                           1/1     Running            0               2m6s    10.104.1.115
4am-node10   <none>           <none>
fouram-cluster-cron-1663621200-1-milvus-standalone-85fcbbchlcgk   1/1     Running            0               2m6s    10.104.5.36
4am-node12   <none>           <none>
fouram-cluster-cron-1663621200-1-minio-5ccb959954-kvh55           1/1     Running            0               2m6s    10.104.1.97
4am-node10   <none>           <none>
```
client log
```
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 92, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 48, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 673, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 96, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 92, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 48, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 682, in wait_for_loading_collection
    return self._wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 711, in _wait_for_loading_collection
    progress = self.get_collection_loading_progress(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 690, in get_collection_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection local_50m_512_l2 has not been loaded to memory or
 load failed)>
 (milvus_benchmark.main:119)
```
