### ISSUE TITLE
[Bug]: When create index using same paramters, it still raise error `CreateIndex failed: index already exist, but parameters are inconsistent` after indexcoord pod chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#18870]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220826-c4a9e13
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.2.0.dev23
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/12268675/187111053-6f99454d-a87b-43e7-8621-e3f2c335bff6.png)
When killing other pods, this test case works well

collection name: `hello_milvus`
```
22:11:18  Insert 3000 vectors cost 0.1604 seconds
22:11:18  
22:11:18  Get collection entities...
22:11:18  6000
22:11:18  
22:11:18  Get collection entities cost 2.5322 seconds
22:11:18  
22:11:18  Create index...
22:11:18  Traceback (most recent call last):
22:11:18    File "scripts/hello_milvus.py", line 124, in <module>
22:11:18      hello_milvus(args.host)
22:11:18    File "scripts/hello_milvus.py", line 75, in hello_milvus
22:11:18      collection.create_index(field_name="float_vector", index_params=default_index)
22:11:18    File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 1083, in create_index
22:11:18      timeout=timeout, **kwargs)
22:11:18    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 101, in handler
22:11:18      raise e
22:11:18    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 97, in handler
22:11:18      return func(*args, **kwargs)
22:11:18    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 127, in handler
22:11:18      ret = func(self, *args, **kwargs)
22:11:18    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 79, in handler
22:11:18      raise e
22:11:18    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 50, in handler
22:11:18      return func(self, *args, **kwargs)
22:11:18    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 612, in create_index
22:11:18      raise MilvusException(status.error_code, status.reason)
22:11:18  pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=CreateIndex failed: index already exist, but parameters are inconsistent)>
```

### Expected Behavior

all test cases passed

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/807/pipeline
log:
[artifacts-indexcoord-pod-failure-807-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9441153/artifacts-indexcoord-pod-failure-807-server-logs.tar.gz)
[artifacts-indexcoord-pod-failure-807-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9441154/artifacts-indexcoord-pod-failure-807-pytest-logs.tar.gz)

failed job:https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/795/pipeline
log:
[artifacts-indexcoord-pod-kill-795-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9441165/artifacts-indexcoord-pod-kill-795-server-logs.tar.gz)
[artifacts-indexcoord-pod-kill-795-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9441167/artifacts-indexcoord-pod-kill-795-pytest-logs.tar.gz)

### Anything else?

This issue reproduced stably

**Comment by zhuwenxing** [comment]
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/853/pipeline
log:
[artifacts-etcd-pod-kill-853-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9457772/artifacts-etcd-pod-kill-853-server-logs.tar.gz)
[artifacts-etcd-pod-kill-853-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9457775/artifacts-etcd-pod-kill-853-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
standalone pod kill
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/855/pipeline
log:
[artifacts-standalone-pod-failure-855-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9457789/artifacts-standalone-pod-failure-855-server-logs.tar.gz)
[artifacts-standalone-pod-failure-855-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9457790/artifacts-standalone-pod-failure-855-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
Not reproduced yet, so close it.
