### ISSUE TITLE
[Bug]: [Nightly]CreateCollection failed with the reason: DataCoord 16 is not ready

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#18891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master(c4a9e13)
- Deployment mode(standalone or cluster):cluster(pulsar)
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0.dev23
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

A few cases went wrong with the message 'CreateCollection failed: data coord watch channels failed, reason = DataCoord 16 is not ready'
Start at about 2022-08-27T19:07:04.117Z

```
[2022-08-27T19:07:04.117Z] [gw0] [ 24%] FAILED testcases/test_index.py::TestNewIndexBase::test_drop_index_repeatedly[get_simple_index5] 
[2022-08-27T19:07:04.117Z] testcases/test_index.py::TestNewIndexBase::test_create_drop_index_repeatedly[get_simple_index1] 
[2022-08-27T19:07:04.117Z] [gw0] [ 24%] FAILED testcases/test_index.py::TestNewIndexBase::test_create_drop_index_repeatedly[get_simple_index1] 
[2022-08-27T19:07:04.117Z] [gw1] [ 24%] FAILED testcases/test_delete.py::TestDeleteString::test_delete_insert_same_id_sealed_string[False] 
[2022-08-27T19:07:04.117Z] [gw3] [ 24%] FAILED testcases/test_query.py::TestQueryOperation::test_query_without_loading 
[2022-08-27T19:07:04.117Z] [gw5] [ 24%] FAILED testcases/test_index.py::TestNewIndexBase::test_create_index_search_with_query_vectors_ip 
[2022-08-27T19:07:04.117Z] testcases/test_index.py::TestNewIndexBase::test_drop_index[get_simple_index1] 
[2022-08-27T19:07:04.117Z] testcases/test_index.py::TestIndexParams::test_index_field_name_invalid[field_name2] 
[2022-08-27T19:07:04.117Z] testcases/test_query.py::TestQueryOperation::test_query_expr_single_term_array[int64 in [0]] 
[2022-08-27T19:07:04.117Z] testcases/test_index.py::TestNewIndexBase::test_create_drop_index_repeatedly[get_simple_index7] 
[2022-08-27T19:07:04.117Z] [gw5] [ 24%] FAILED testcases/test_index.py::TestNewIndexBase::test_drop_index[get_simple_index1] 
[2022-08-27T19:07:04.117Z] [gw1] [ 24%] FAILED testcases/test_index.py::TestIndexParams::test_index_field_name_invalid[field_name2] 
[2022-08-27T19:07:04.117Z] [gw3] [ 24%] FAILED testcases/test_query.py::TestQueryOperation::test_query_expr_single_term_array[int64 in [0]] 
[2022-08-27T19:07:04.117Z] [gw0] [ 24%] FAILED testcases/test_index.py::TestNewIndexBase::test_create_drop_index_repeatedly[get_simple_index7] 
[2022-08-27T19:07:04.117Z] testcases/test_index.py::TestNewIndexBase::test_drop_index[get_simple_index7] 
[2022-08-27T19:07:04.118Z] testcases/test_index.py::TestIndexParams::test_index_field_name_invalid[12-s] 
[2022-08-27T19:07:04.118Z] testcases/test_query.py::TestQueryOperation::test_query_binary_expr_single_term_array[int64 in [0]] 
[2022-08-27T19:07:04.372Z] testcases/test_index.py::TestNewIndexBase::test_drop_index_ip[get_simple_index4] 
[2022-08-27T19:07:04.374Z] [gw1] [ 24%] PASSED testcases/test_index.py::TestIndexParams::test_index_field_name_invalid[12-s] 
[2022-08-27T19:07:04.374Z] [gw2] [ 24%] FAILED testcases/test_index.py::TestNewIndexBase::test_index_collection_with_after_load 
[2022-08-27T19:07:04.374Z] testcases/test_index.py::TestNewIndexBinary::test_drop_index_partition 
[2022-08-27T19:07:04.374Z] [gw4] [ 24%] FAILED testcases/test_insert.py::TestInsertOperation::test_insert_multi_times[4096] 
[2022-08-27T19:07:04.374Z] testcases/test_index.py::TestIndexParams::test_index_field_name_not_existed 
[2022-08-27T19:07:04.374Z] testcases/test_insert.py::TestInsertOperation::test_insert_all_datatype_collection 
```

### Expected Behavior

PASSED

### Steps To Reproduce

```markdown
See nightly log:
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/63/pipeline/187
```

### Milvus Log

1. milvus log: [artifacts-milvus-distributed-pulsar-nightly-63-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/63/artifact/artifacts-milvus-distributed-pulsar-nightly-63-pymilvus-e2e-logs.tar.gz)

2. error:

```
[2022-08-27T19:52:05.779Z] [2022-08-27 19:07:03 - ERROR - pymilvus.decorators]: RPC error: [bulk_insert], <MilvusException: (code=1, message=getSegmentID failed: SegmentIDAllocator failRemainRequest err:syncSegmentID Failed:DataCoord is not serving)>, <Time:{'RPC start': '2022-08-27 19:07:02.718307', 'RPC error': '2022-08-27 19:07:03.765164'}> (decorators.py:100)
[2022-08-27T19:52:05.780Z] [2022-08-27 19:07:03 - ERROR - ci_test]: Traceback (most recent call last):
[2022-08-27T19:52:05.780Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2022-08-27T19:52:05.780Z]     res = func(*args, **_kwargs)
[2022-08-27T19:52:05.780Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2022-08-27T19:52:05.780Z]     return func(*arg, **kwargs)
[2022-08-27T19:52:05.780Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 555, in insert
[2022-08-27T19:52:05.780Z]     res = conn.bulk_insert(self._name, entities, partition_name, ids=None, timeout=timeout, schema=schema_dict, **kwargs)
[2022-08-27T19:52:05.780Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 101, in handler
[2022-08-27T19:52:05.780Z]     raise e
[2022-08-27T19:52:05.780Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 97, in handler
[2022-08-27T19:52:05.780Z]     return func(*args, **kwargs)
[2022-08-27T19:52:05.780Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 127, in handler
[2022-08-27T19:52:05.780Z]     ret = func(self, *args, **kwargs)
[2022-08-27T19:52:05.780Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 79, in handler
[2022-08-27T19:52:05.780Z]     raise e
[2022-08-27T19:52:05.780Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2022-08-27T19:52:05.780Z]     return func(self, *args, **kwargs)
[2022-08-27T19:52:05.780Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 386, in bulk_insert
[2022-08-27T19:52:05.780Z]     raise err
[2022-08-27T19:52:05.780Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 382, in bulk_insert
[2022-08-27T19:52:05.780Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2022-08-27T19:52:05.780Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=getSegmentID failed: SegmentIDAllocator failRemainRequest err:syncSegmentID Failed:DataCoord is not serving)>
[2022-08-27T19:52:05.780Z]  (api_request.py:39)
[2022-08-27T19:52:05.780Z] [2022-08-27 19:07:03 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=getSegmentID failed: SegmentIDAllocator failRemainRequest err:syncSegmentID Failed:DataCoord is not serving)> (api_request.py:40)
```

**Comment by ThreadDao** [comment]
I encounter the same problem on image `master-20220906-8dce723`
client logs:
```
[2022-09-06 07:17:45,183 - DEBUG - ci_test]: (api_response) : (insert count: 50000, delete count: 0, upsert count: 0, timestamp: 435
800942688600065, success count: 50000, err count: 0)  (api_request.py:31)
[2022-09-06 07:17:53,442 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [
 float_vector
0      [0.07441863528821302, 0.00012158219692708906, ...
1      [0.038857040752534995, 0.07452829135683132, 0....
2      [0.043996923450585465, 0.012897130690192365, 0...
3      [0.02967087504643306, 0.0553142198479125, 0.00...
4      [0.0566......, kwargs: {'timeout': 60} (api_request.py:56)
[2022-09-06 07:18:06,279 - ERROR - ci_test]: Traceback (most recent call last):
  File "/src/milvus/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/src/milvus/tests/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 555, in insert
    res = conn.bulk_insert(self._name, entities, partition_name, ids=None, timeout=timeout, schema=schema_dict, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 101, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 97, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 127, in handler
```

Server pod: 
- cluster: devops
- namespace: chaos-testing
- pods
```
standalone-index-oom-etcd-0                                  1/1     Running       0               24m
standalone-index-oom-etcd-1                                  1/1     Running       0               24m
standalone-index-oom-etcd-2                                  1/1     Running       0               24m
standalone-index-oom-milvus-standalone-669c68947b-zv6js      1/1     Running       0               22m
standalone-index-oom-minio-0                                 1/1     Running       0               24m
standalone-index-oom-minio-1                                 1/1     Running       0               24m
standalone-index-oom-minio-2                                 1/1     Running       0               24m
standalone-index-oom-minio-3                                 1/1     Running       0               24m
```
Server logs:  
[standalone-index-oom.log](https://github.com/milvus-io/milvus/files/9494377/standalone-index-oom.log)
```
3891 [2022/09/06 07:18:06.275 +00:00] [ERROR] [proxy/task_insert.go:379] ["allocate segmentID for insert data failed"] [collectionID=435800845776784709] ["channel name"=standalon     e-index-oom-rootcoord-dml_1_435800845776784709v1] ["allocate count"=25092] [error="getSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error"] [stack="githu     b.com/milvus-io/milvus/internal/proxy.(*insertTask).assignSegmentID\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_insert.go:379\ngithub.com/milvus-io/milvus/int     ernal/proxy.(*insertTask).Execute\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_insert.go:456\ngithub.com/milvus-io/milvus/internal/proxy.(*taskScheduler).proce     ssTask\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:465"]
3892 [2022/09/06 07:18:06.275 +00:00] [ERROR] [proxy/task_insert.go:458] ["assign segmentID and repack insert data failed"] [msgID=435800845777835549] [collectionID=4358008457767     84709] [error="getSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error"] [stack="github.com/milvus-io/milvus/internal/proxy.(*insertTask).Execute\n\t/go/s     rc/github.com/milvus-io/milvus/internal/proxy/task_insert.go:458\ngithub.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask\n\t/go/src/github.com/milvus-io/mil     vus/internal/proxy/task_scheduler.go:465"]
3893 [2022/09/06 07:18:06.275 +00:00] [DEBUG] [timerecord/time_recorder.go:91] ["proxy execute insert 435800845777835549: insert execute done (10010ms)"]
3894 [2022/09/06 07:18:06.275 +00:00] [ERROR] [proxy/task_scheduler.go:468] ["Failed to execute task: getSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error"]      [traceID=4123eca32cd41ff6] [stack="github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_schedu     ler.go:468"]
```

**Comment by czs007** [comment]
![image](https://user-images.githubusercontent.com/59249785/188577880-ba7bcc73-3dcf-4696-8c28-d4a7b424a1e2.png)
@sunby  continue cause the obtained segment quota is not enough, so an error is reported  in proxy " failed: SegmentIDAllocator failRemainRequest unexpected error".

**Comment by NicoYuan1986** [comment]
This issue no longer occurs in master(c58a8d8).
