### ISSUE TITLE
[Bug]: [Nightly]Search failed with message "Invalid shard leader"

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#18899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master(1527aee)
- Deployment mode(standalone or cluster):cluster(kafka)
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0.dev23
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

A  case went wrong with the message 'Invalid shard leader'
Start at about 2022-08-29T19:13:06.419Z

### Expected Behavior

PASSED

### Steps To Reproduce

```markdown
See nightly log:
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/67/pipeline/155
```

### Milvus Log

1. milvus log:[artifacts-milvus-distributed-kafka-nightly-67-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/67/artifact/artifacts-milvus-distributed-kafka-nightly-67-pymilvus-e2e-logs.tar.gz)
2. collection name: search_collection_Ttcvb4MG
3. error:
```
[2022-08-29T19:56:38.352Z] _ TestCollectionSearch.test_search_after_different_index_with_params[8-False-True-RHNSW_PQ-params7] _
[2022-08-29T19:56:38.352Z] [gw4] linux -- Python 3.8.13 /usr/local/bin/python3
[2022-08-29T19:56:38.352Z] 
[2022-08-29T19:56:38.352Z] self = <test_search.TestCollectionSearch object at 0x7fe762787f70>, dim = 8
[2022-08-29T19:56:38.352Z] index = 'RHNSW_PQ', params = {'M': 48, 'PQM': 8, 'efConstruction': 500}
[2022-08-29T19:56:38.352Z] auto_id = False, _async = True
[2022-08-29T19:56:38.352Z] 
[2022-08-29T19:56:38.352Z]     @pytest.mark.tags(CaseLabel.L1)
[2022-08-29T19:56:38.352Z]     @pytest.mark.parametrize("index, params",
[2022-08-29T19:56:38.352Z]                              zip(ct.all_index_types[:9],
[2022-08-29T19:56:38.352Z]                                  ct.default_index_params[:9]))
[2022-08-29T19:56:38.352Z]     def test_search_after_different_index_with_params(self, dim, index, params, auto_id, _async):
[2022-08-29T19:56:38.352Z]         """
[2022-08-29T19:56:38.352Z]         target: test search after different index
[2022-08-29T19:56:38.352Z]         method: test search after different index and corresponding search params
[2022-08-29T19:56:38.352Z]         expected: search successfully with limit(topK)
[2022-08-29T19:56:38.352Z]         """
[2022-08-29T19:56:38.352Z]         # 1. initialize with data
[2022-08-29T19:56:38.352Z]         collection_w, _, _, insert_ids, time_stamp = self.init_collection_general(prefix, True, 5000,
[2022-08-29T19:56:38.352Z]                                                                                   partition_num=1,
[2022-08-29T19:56:38.352Z]                                                                                   auto_id=auto_id,
[2022-08-29T19:56:38.352Z]                                                                                   dim=dim, is_index=True)[0:5]
[2022-08-29T19:56:38.352Z]         # 2. create index and load
[2022-08-29T19:56:38.352Z]         if params.get("m"):
[2022-08-29T19:56:38.352Z]             if (dim % params["m"]) != 0:
[2022-08-29T19:56:38.352Z]                 params["m"] = dim // 4
[2022-08-29T19:56:38.352Z]         if params.get("PQM"):
[2022-08-29T19:56:38.352Z]             if (dim % params["PQM"]) != 0:
[2022-08-29T19:56:38.352Z]                 params["PQM"] = dim // 4
[2022-08-29T19:56:38.352Z]         default_index = {"index_type": index, "params": params, "metric_type": "L2"}
[2022-08-29T19:56:38.352Z]         collection_w.create_index("float_vector", default_index)
[2022-08-29T19:56:38.352Z]         collection_w.load()
[2022-08-29T19:56:38.352Z]         # 3. search
[2022-08-29T19:56:38.352Z]         search_params = cf.gen_search_param(index)
[2022-08-29T19:56:38.352Z]         vectors = [[random.random() for _ in range(dim)] for _ in range(default_nq)]
[2022-08-29T19:56:38.352Z]         for search_param in search_params:
[2022-08-29T19:56:38.352Z]             log.info("Searching with search params: {}".format(search_param))
[2022-08-29T19:56:38.352Z] >           collection_w.search(vectors[:default_nq], default_search_field,
[2022-08-29T19:56:38.352Z]                                 search_param, default_limit,
[2022-08-29T19:56:38.352Z]                                 default_search_exp, _async=_async,
[2022-08-29T19:56:38.352Z]                                 travel_timestamp=time_stamp,
[2022-08-29T19:56:38.352Z]                                 check_task=CheckTasks.check_search_results,
[2022-08-29T19:56:38.352Z]                                 check_items={"nq": default_nq,
[2022-08-29T19:56:38.352Z]                                              "ids": insert_ids,
[2022-08-29T19:56:38.352Z]                                              "limit": default_limit,
[2022-08-29T19:56:38.352Z]                                              "_async": _async})
[2022-08-29T19:56:38.352Z] 
[2022-08-29T19:56:38.352Z] testcases/test_search.py:1301: 
[2022-08-29T19:56:38.352Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[2022-08-29T19:56:38.352Z] utils/wrapper.py:33: in inner_wrapper
[2022-08-29T19:56:38.352Z]     res, result = func(*args, **kwargs)
[2022-08-29T19:56:38.352Z] base/collection_wrapper.py:162: in search
[2022-08-29T19:56:38.352Z]     check_result = ResponseChecker(res, func_name, check_task, check_items, check,
[2022-08-29T19:56:38.352Z] check/func_check.py:57: in run
[2022-08-29T19:56:38.352Z]     result = self.check_search_results(self.response, self.func_name, self.check_items)
[2022-08-29T19:56:38.352Z] check/func_check.py:213: in check_search_results
[2022-08-29T19:56:38.352Z]     search_res = search_res.result()
[2022-08-29T19:56:38.352Z] /usr/local/lib/python3.8/site-packages/pymilvus/orm/future.py:30: in result
[2022-08-29T19:56:38.352Z]     return self.on_response(self._f.result())
[2022-08-29T19:56:38.352Z] /usr/local/lib/python3.8/site-packages/pymilvus/client/asynch.py:185: in result
[2022-08-29T19:56:38.352Z]     self.exception()
[2022-08-29T19:56:38.352Z] /usr/local/lib/python3.8/site-packages/pymilvus/client/asynch.py:242: in exception
[2022-08-29T19:56:38.352Z]     raise self._exception
[2022-08-29T19:56:38.352Z] /usr/local/lib/python3.8/site-packages/pymilvus/client/asynch.py:232: in done
[2022-08-29T19:56:38.352Z]     self._results = self.on_response(self._response)
[2022-08-29T19:56:38.352Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[2022-08-29T19:56:38.352Z] 
[2022-08-29T19:56:38.352Z] self = <pymilvus.client.asynch.ChunkedSearchFuture object at 0x7fe7627b61c0>
[2022-08-29T19:56:38.352Z] response = [status {
[2022-08-29T19:56:38.352Z]   error_code: UnexpectedError
[2022-08-29T19:56:38.352Z]   reason: "Invalid shard leader"
[2022-08-29T19:56:38.352Z] }
[2022-08-29T19:56:38.352Z] ]
[2022-08-29T19:56:38.352Z] 
[2022-08-29T19:56:38.352Z]     def on_response(self, response):
[2022-08-29T19:56:38.352Z]         for raw in response:
[2022-08-29T19:56:38.352Z]             if raw.status.error_code != 0:
[2022-08-29T19:56:38.352Z] >               raise MilvusException(raw.status.error_code, raw.status.reason)
[2022-08-29T19:56:38.352Z] E               pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Invalid shard leader)>
[2022-08-29T19:56:38.352Z] 
```

**Comment by NicoYuan1986** [comment]
The same issue occurs:
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/78/pipeline/143
1. milvus:master(68a6587) pymilvus:2.2.0.dev26
2. FAILED time: [2022-09-04T15:48:59.968Z] [gw1] [ 83%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_multi_collections[5000-2-8-True-True]
3. collection name: search_collection_lFYRfA0P
4. milvus log: [artifacts-milvus-distributed-kafka-nightly-78-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/78/artifact/artifacts-milvus-distributed-kafka-nightly-78-pymilvus-e2e-logs.tar.gz)
5. error message:
```
[2022-09-04T16:15:31.840Z] self = <pymilvus.client.asynch.ChunkedSearchFuture object at 0x7f2491554730>
[2022-09-04T16:15:31.840Z] response = [status {
[2022-09-04T16:15:31.840Z]   error_code: UnexpectedError
[2022-09-04T16:15:31.840Z]   reason: "Invalid shard leader"
[2022-09-04T16:15:31.840Z] }
[2022-09-04T16:15:31.840Z] ]
[2022-09-04T16:15:31.840Z] 
[2022-09-04T16:15:31.840Z]     def on_response(self, response):
[2022-09-04T16:15:31.840Z]         for raw in response:
[2022-09-04T16:15:31.840Z]             if raw.status.error_code != 0:
[2022-09-04T16:15:31.840Z] >               raise MilvusException(raw.status.error_code, raw.status.reason)
[2022-09-04T16:15:31.840Z] E               pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Invalid shard leader)>
[2022-09-04T16:15:31.840Z] 
[2022-09-04T16:15:31.840Z] /usr/local/lib/python3.8/site-packages/pymilvus/client/asynch.py:250: MilvusException
```

**Comment by congqixia** [comment]
Shall be fixed by v2 pr, does this issue still persist?

**Comment by NicoYuan1986** [comment]
> Shall be fixed by v2 pr, does this issue still persist?

The issue came up only once 2 days ago.
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/112/pipeline/155
timeline:[2022-09-21T17:24:30.895Z] [gw3] [ 77%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_multi_collections[5000-500-128-False-False]
```
[2022-09-21T19:03:09.743Z] [2022-09-21 17:24:25 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=Invalid shard leader)>, <Time:{'RPC start': '2022-09-21 17:24:20.818600', 'RPC error': '2022-09-21 17:24:25.438957'}> (decorators.py:100)
[2022-09-21T19:03:09.743Z] [2022-09-21 17:24:25 - ERROR - ci_test]: Traceback (most recent call last):
[2022-09-21T19:03:09.743Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2022-09-21T19:03:09.743Z]     res = func(*args, **_kwargs)
[2022-09-21T19:03:09.743Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2022-09-21T19:03:09.743Z]     return func(*arg, **kwargs)
[2022-09-21T19:03:09.743Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 717, in search
[2022-09-21T19:03:09.743Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,
[2022-09-21T19:03:09.743Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 101, in handler
[2022-09-21T19:03:09.743Z]     raise e
[2022-09-21T19:03:09.743Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 97, in handler
[2022-09-21T19:03:09.743Z]     return func(*args, **kwargs)
[2022-09-21T19:03:09.743Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 127, in handler
[2022-09-21T19:03:09.743Z]     ret = func(self, *args, **kwargs)
[2022-09-21T19:03:09.743Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 79, in handler
[2022-09-21T19:03:09.743Z]     raise e
[2022-09-21T19:03:09.743Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2022-09-21T19:03:09.743Z]     return func(self, *args, **kwargs)
[2022-09-21T19:03:09.743Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 472, in search
[2022-09-21T19:03:09.743Z]     return self._execute_search_requests(requests, timeout, **_kwargs)
[2022-09-21T19:03:09.743Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 436, in _execute_search_requests
[2022-09-21T19:03:09.743Z]     raise pre_err
[2022-09-21T19:03:09.743Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 427, in _execute_search_requests
[2022-09-21T19:03:09.743Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2022-09-21T19:03:09.743Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Invalid shard leader)>
[2022-09-21T19:03:09.743Z]  (api_request.py:39)
[2022-09-21T19:03:09.743Z] [2022-09-21 17:24:25 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Invalid shard leader)> (api_request.py:40)
```

**Comment by NicoYuan1986** [comment]
This issue no longer occurs in master(c58a8d8).
