### ISSUE TITLE
[Bug]: [Nightly]Test collection failed with the message "rpc deadline exceeded: Retry timeout: 20s"

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#18900]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.*(3de4af43)
- Deployment mode(standalone or cluster):cluster(kafka)
- SDK version(e.g. pymilvus v2.0.0rc2):2.1.2.dev2
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The case test_collection.py::TestCollectionParams::test_collection failed at about 
[2022-08-29T20:23:46.964Z] [gw0] [  3%] FAILED testcases/test_collection.py::TestCollectionParams::test_collection

### Expected Behavior

PASSED

### Steps To Reproduce

```markdown
See nightly log:
https://jenkins.milvus.io:18080/blue/organizations/jenkins/qa%2Fmilvus-release-nightly/detail/milvus-release-nightly/68/pipeline/177
```

### Milvus Log

1. milvus log:[milvus-distributed-kafka-68-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/qa/job/milvus-release-nightly/68/artifact/milvus-distributed-kafka-68-pymilvus-e2e-logs.tar.gz)
2. error message:
```
[2022-08-29T21:15:58.137Z] [2022-08-29 20:23:26 - ERROR - pymilvus.decorators]: RPC error: [list_collections], <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)>, <Time:{'RPC start': '2022-08-29 20:23:06.659608', 'RPC error': '2022-08-29 20:23:26.660279'}> (decorators.py:95)
[2022-08-29T21:15:58.137Z] [2022-08-29 20:23:26 - ERROR - ci_test]: Traceback (most recent call last):
[2022-08-29T21:15:58.137Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 48, in handler
[2022-08-29T21:15:58.137Z]     return func(self, *args, **kwargs)
[2022-08-29T21:15:58.137Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 237, in list_collections
[2022-08-29T21:15:58.137Z]     response = rf.result()
[2022-08-29T21:15:58.137Z]   File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 744, in result
[2022-08-29T21:15:58.137Z]     raise self
[2022-08-29T21:15:58.137Z] grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
[2022-08-29T21:15:58.137Z] 	status = StatusCode.DEADLINE_EXCEEDED
[2022-08-29T21:15:58.137Z] 	details = "Deadline Exceeded"
[2022-08-29T21:15:58.137Z] 	debug_error_string = "UNKNOWN:Deadline Exceeded {grpc_status:4, created_time:"2022-08-29T20:23:26.659785983+00:00"}"
[2022-08-29T21:15:58.137Z] >
[2022-08-29T21:15:58.137Z] 
[2022-08-29T21:15:58.137Z] During handling of the above exception, another exception occurred:
[2022-08-29T21:15:58.137Z] 
[2022-08-29T21:15:58.137Z] Traceback (most recent call last):
[2022-08-29T21:15:58.137Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
[2022-08-29T21:15:58.137Z]     res = func(*args, **kwargs)
[2022-08-29T21:15:58.137Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 56, in api_request
[2022-08-29T21:15:58.137Z]     return func(*arg, **kwargs)
[2022-08-29T21:15:58.137Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/utility.py", line 427, in list_collections
[2022-08-29T21:15:58.137Z]     return _get_connection(using).list_collections(timeout=timeout)
[2022-08-29T21:15:58.137Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 96, in handler
[2022-08-29T21:15:58.137Z]     raise e
[2022-08-29T21:15:58.137Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 92, in handler
[2022-08-29T21:15:58.137Z]     return func(*args, **kwargs)
[2022-08-29T21:15:58.137Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 62, in handler
[2022-08-29T21:15:58.137Z]     raise MilvusException(Status.UNEXPECTED_ERROR, f"rpc deadline exceeded: {timeout_msg}")
[2022-08-29T21:15:58.137Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)>
[2022-08-29T21:15:58.137Z]  (api_request.py:35)
[2022-08-29T21:15:58.137Z] [2022-08-29 20:23:26 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)> 
```
3. panic log:
ci.var.log.containers.mdk-release-68-n-milvus-querynode-5b9f44fd4c-bm7jl_milvus-ci_querynode-93746ce53ee3c38862cc6dcf751d0cc9e04ed8c6ad9919b6fa9103c962339b4e.log
```
2022-08-30T04:18:23.689676639+08:00 stdout F [2022/08/29 20:18:23.689 +00:00] [ERROR] [querynode/query_node.go:229] ["QueryNode init vector storage failed"] [error="All attempts results:\nattempt #1:Server not initialized, please try again.\nattempt #2:Server not initialized, please try again.\nattempt #3:Server not initialized, please try again.\nattempt #4:Server not initialized, please try again.\nattempt #5:Server not initialized, please try again.\nattempt #6:Server not initialized, please try again.\nattempt #7:Server not initialized, please try again.\nattempt #8:Server not initialized, please try again.\nattempt #9:Server not initialized, please try again.\nattempt #10:Server not initialized, please try again.\nattempt #11:Server not initialized, please try again.\n"] [stack="github.com/milvus-io/milvus/internal/querynode.(*QueryNode).Init.func1\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/query_node.go:229\nsync.(*Once).doSlow\n\t/usr/local/go/src/sync/once.go:68\nsync.(*Once).Do\n\t/usr/local/go/src/sync/once.go:59\ngithub.com/milvus-io/milvus/internal/querynode.(*QueryNode).Init\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/query_node.go:215\ngithub.com/milvus-io/milvus/internal/distributed/querynode.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/service.go:120\ngithub.com/milvus-io/milvus/internal/distributed/querynode.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/service.go:196\ngithub.com/milvus-io/milvus/cmd/components.(*QueryNode).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/query_node.go:51\ngithub.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runQueryNode.func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:218"]
2022-08-30T04:18:23.689709114+08:00 stdout F [2022/08/29 20:18:23.689 +00:00] [ERROR] [querynode/service.go:121] ["QueryNode init error: "] [error="All attempts results:\nattempt #1:Server not initialized, please try again.\nattempt #2:Server not initialized, please try again.\nattempt #3:Server not initialized, please try again.\nattempt #4:Server not initialized, please try again.\nattempt #5:Server not initialized, please try again.\nattempt #6:Server not initialized, please try again.\nattempt #7:Server not initialized, please try again.\nattempt #8:Server not initialized, please try again.\nattempt #9:Server not initialized, please try again.\nattempt #10:Server not initialized, please try again.\nattempt #11:Server not initialized, please try again.\n"] [stack="github.com/milvus-io/milvus/internal/distributed/querynode.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/service.go:121\ngithub.com/milvus-io/milvus/internal/distributed/querynode.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/service.go:196\ngithub.com/milvus-io/milvus/cmd/components.(*QueryNode).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/query_node.go:51\ngithub.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runQueryNode.func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:218"]
2022-08-30T04:18:23.691886117+08:00 stderr F panic: All attempts results:
2022-08-30T04:18:23.691914509+08:00 stderr F attempt #1:Server not initialized, please try again.
2022-08-30T04:18:23.691920791+08:00 stderr F attempt #2:Server not initialized, please try again.
2022-08-30T04:18:23.69192537+08:00 stderr F attempt #3:Server not initialized, please try again.
2022-08-30T04:18:23.691929843+08:00 stderr F attempt #4:Server not initialized, please try again.
2022-08-30T04:18:23.691938904+08:00 stderr F attempt #5:Server not initialized, please try again.
2022-08-30T04:18:23.691943213+08:00 stderr F attempt #6:Server not initialized, please try again.
2022-08-30T04:18:23.691946665+08:00 stderr F attempt #7:Server not initialized, please try again.
2022-08-30T04:18:23.691950811+08:00 stderr F attempt #8:Server not initialized, please try again.
2022-08-30T04:18:23.691954799+08:00 stderr F attempt #9:Server not initialized, please try again.
2022-08-30T04:18:23.691958785+08:00 stderr F attempt #10:Server not initialized, please try again.
2022-08-30T04:18:23.691962611+08:00 stderr F attempt #11:Server not initialized, please try again.
2022-08-30T04:18:23.691966135+08:00 stderr F
2022-08-30T04:18:23.691970276+08:00 stderr F
2022-08-30T04:18:23.691974565+08:00 stderr F goroutine 140 [running]:
2022-08-30T04:18:23.691979191+08:00 stderr F github.com/milvus-io/milvus/cmd/components.(*QueryNode).Run(0xc000011020, 0xffffffffffffffff, 0x8)
2022-08-30T04:18:23.691983912+08:00 stderr F    /go/src/github.com/milvus-io/milvus/cmd/components/query_node.go:52 +0x98
2022-08-30T04:18:23.691996646+08:00 stderr F github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runQueryNode.func1(0x0, 0x0, 0x40b9000, 0x43a9110, 0xc000be4bc0, 0xc0000138d0, 0xc000bce040, 0xc000bce0f0)
2022-08-30T04:18:23.692003103+08:00 stderr F    /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:218 +0x165
2022-08-30T04:18:23.692006916+08:00 stderr F created by github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runQueryNode
2022-08-30T04:18:23.692011439+08:00 stderr F    /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:199 +0xda

```

**Comment by weiliu1031** [comment]
log not found!

**Comment by NicoYuan1986** [comment]
> log not found!

I have sent it to you.

**Comment by weiliu1031** [comment]
root cause:
1. proxy submit createCollection/listCollection to it's ddTaskQueue
2. proxy's task_scheduler process dd task in serial
3. createCollection request came, then listCollection request came
4. createCollection hang for about 3min, so listCollection timeout before start to schedule.

**Comment by NicoYuan1986** [comment]
Yestarday:
https://jenkins.milvus.io:18080/blue/organizations/jenkins/qa%2Fmilvus-release-nightly/detail/milvus-release-nightly/85/pipeline/154
1. milvus: 2.1.* pymilvus:2.1.2.dev2
2. collection name: collection_ubZJPP1o
3. failed time: [2022-09-06T23:22:58.346Z] [gw5] [  5%] FAILED testcases/test_collection.py::TestCollectionParams::test_collection_binary
4. milvus log: [milvus-distributed-kafka-85-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/qa/job/milvus-release-nightly/85/artifact/milvus-distributed-kafka-85-pymilvus-e2e-logs.tar.gz)
5. error message: 
```
[2022-09-07T00:21:03.609Z] [2022-09-06 23:22:55 - ERROR - pymilvus.decorators]: RPC error: [list_collections], <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)>, <Time:{'RPC start': '2022-09-06 23:22:35.725646', 'RPC error': '2022-09-06 23:22:55.726344'}> (decorators.py:95)
[2022-09-07T00:21:03.609Z] [2022-09-06 23:22:55 - ERROR - ci_test]: Traceback (most recent call last):
[2022-09-07T00:21:03.609Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 48, in handler
[2022-09-07T00:21:03.609Z]     return func(self, *args, **kwargs)
[2022-09-07T00:21:03.609Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 237, in list_collections
[2022-09-07T00:21:03.609Z]     response = rf.result()
[2022-09-07T00:21:03.609Z]   File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 744, in result
[2022-09-07T00:21:03.609Z]     raise self
[2022-09-07T00:21:03.609Z] grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
[2022-09-07T00:21:03.609Z] 	status = StatusCode.DEADLINE_EXCEEDED
[2022-09-07T00:21:03.609Z] 	details = "Deadline Exceeded"
[2022-09-07T00:21:03.609Z] 	debug_error_string = "UNKNOWN:Deadline Exceeded {grpc_status:4, created_time:"2022-09-06T23:22:55.725905647+00:00"}"
[2022-09-07T00:21:03.609Z] >
[2022-09-07T00:21:03.609Z] 
[2022-09-07T00:21:03.609Z] During handling of the above exception, another exception occurred:
[2022-09-07T00:21:03.609Z] 
[2022-09-07T00:21:03.609Z] Traceback (most recent call last):
[2022-09-07T00:21:03.609Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
[2022-09-07T00:21:03.609Z]     res = func(*args, **kwargs)
[2022-09-07T00:21:03.609Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 56, in api_request
[2022-09-07T00:21:03.609Z]     return func(*arg, **kwargs)
[2022-09-07T00:21:03.609Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/utility.py", line 427, in list_collections
[2022-09-07T00:21:03.609Z]     return _get_connection(using).list_collections(timeout=timeout)
[2022-09-07T00:21:03.609Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 96, in handler
[2022-09-07T00:21:03.609Z]     raise e
[2022-09-07T00:21:03.609Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 92, in handler
[2022-09-07T00:21:03.609Z]     return func(*args, **kwargs)
[2022-09-07T00:21:03.609Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 62, in handler
[2022-09-07T00:21:03.609Z]     raise MilvusException(Status.UNEXPECTED_ERROR, f"rpc deadline exceeded: {timeout_msg}")
[2022-09-07T00:21:03.609Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)>
[2022-09-07T00:21:03.609Z]  (api_request.py:35)
[2022-09-07T00:21:03.609Z] [2022-09-06 23:22:55 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)> 
```

**Comment by NicoYuan1986** [comment]
Yestarday:
https://jenkins.milvus.io:18080/blue/organizations/jenkins/qa%2Fmilvus-release-nightly/detail/milvus-release-nightly/99/pipeline/177

1. milvus: 2.1.*(3c3ba55c) pymilvus:2.1.2.dev9
2. collection name: collection_vvKpazkz
3. failed time: [2022-09-13T20:23:30.419Z] [gw0] [  4%] FAILED testcases/test_collection.py::TestCollectionParams::test_collection
4. milvus log: [milvus-distributed-kafka-99-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/qa/job/milvus-release-nightly/99/artifact/milvus-distributed-kafka-99-pymilvus-e2e-logs.tar.gz)
5. error message:
```
[2022-09-13T21:22:52.000Z] [2022-09-13 20:23:10 - ERROR - pymilvus.decorators]: RPC error: [list_collections], <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)>, <Time:{'RPC start': '2022-09-13 20:22:50.206916', 'RPC error': '2022-09-13 20:23:10.208189'}> (decorators.py:95)
[2022-09-13T21:22:52.000Z] [2022-09-13 20:23:10 - ERROR - ci_test]: Traceback (most recent call last):
[2022-09-13T21:22:52.000Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 48, in handler
[2022-09-13T21:22:52.000Z]     return func(self, *args, **kwargs)
[2022-09-13T21:22:52.000Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 237, in list_collections
[2022-09-13T21:22:52.000Z]     response = rf.result()
[2022-09-13T21:22:52.000Z]   File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 744, in result
[2022-09-13T21:22:52.000Z]     raise self
[2022-09-13T21:22:52.000Z] grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
[2022-09-13T21:22:52.000Z] 	status = StatusCode.DEADLINE_EXCEEDED
[2022-09-13T21:22:52.000Z] 	details = "Deadline Exceeded"
[2022-09-13T21:22:52.000Z] 	debug_error_string = "UNKNOWN:Deadline Exceeded {created_time:"2022-09-13T20:23:10.20775414+00:00", grpc_status:4}"
[2022-09-13T21:22:52.000Z] >
[2022-09-13T21:22:52.000Z] 
[2022-09-13T21:22:52.000Z] During handling of the above exception, another exception occurred:
[2022-09-13T21:22:52.000Z] 
[2022-09-13T21:22:52.000Z] Traceback (most recent call last):
[2022-09-13T21:22:52.000Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
[2022-09-13T21:22:52.000Z]     res = func(*args, **kwargs)
[2022-09-13T21:22:52.000Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 56, in api_request
[2022-09-13T21:22:52.000Z]     return func(*arg, **kwargs)
[2022-09-13T21:22:52.000Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/utility.py", line 427, in list_collections
[2022-09-13T21:22:52.000Z]     return _get_connection(using).list_collections(timeout=timeout)
[2022-09-13T21:22:52.000Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 96, in handler
[2022-09-13T21:22:52.000Z]     raise e
[2022-09-13T21:22:52.000Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 92, in handler
[2022-09-13T21:22:52.000Z]     return func(*args, **kwargs)
[2022-09-13T21:22:52.000Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 62, in handler
[2022-09-13T21:22:52.000Z]     raise MilvusException(Status.UNEXPECTED_ERROR, f"rpc deadline exceeded: {timeout_msg}")
[2022-09-13T21:22:52.000Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)>
[2022-09-13T21:22:52.000Z]  (api_request.py:35)
[2022-09-13T21:22:52.000Z] [2022-09-13 20:23:10 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)> (api_request.py:36)
```

**Comment by NicoYuan1986** [comment]
Recently: https://jenkins.milvus.io:18080/blue/organizations/jenkins/qa%2Fmilvus-release-nightly/detail/milvus-release-nightly/106/pipeline/177
1. milvus: 2.1.*(3c3ba55c)  pymilvus: 2.1.2.dev9
2. collection name: coll__jMWdNsuQ
3. failed time: [2022-09-16T23:32:30.384Z] [gw2] [ 37%] FAILED testcases/test_partition.py::TestPartitionOperations::test_partition_release_after_collection_released 
4. milvus log: [milvus-distributed-kafka-106-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/qa/job/milvus-release-nightly/106/artifact/milvus-distributed-kafka-106-pymilvus-e2e-logs.tar.gz)
5. error message:
```
[2022-09-17T00:14:33.157Z] [2022-09-16 23:32:29 - ERROR - pymilvus.decorators]: RPC error: [release_collection], <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)>, <Time:{'RPC start': '2022-09-16 23:32:09.220385', 'RPC error': '2022-09-16 23:32:29.220995'}> (decorators.py:95)
[2022-09-17T00:14:33.157Z] [2022-09-16 23:32:29 - ERROR - ci_test]: Traceback (most recent call last):
[2022-09-17T00:14:33.157Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 48, in handler
[2022-09-17T00:14:33.157Z]     return func(self, *args, **kwargs)
[2022-09-17T00:14:33.157Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 722, in release_collection
[2022-09-17T00:14:33.157Z]     response = rf.result()
[2022-09-17T00:14:33.157Z]   File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 744, in result
[2022-09-17T00:14:33.157Z]     raise self
[2022-09-17T00:14:33.157Z] grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
[2022-09-17T00:14:33.157Z] 	status = StatusCode.DEADLINE_EXCEEDED
[2022-09-17T00:14:33.157Z] 	details = "Deadline Exceeded"
[2022-09-17T00:14:33.157Z] 	debug_error_string = "UNKNOWN:Deadline Exceeded {grpc_status:4, created_time:"2022-09-16T23:32:29.220725188+00:00"}"
[2022-09-17T00:14:33.157Z] >
[2022-09-17T00:14:33.157Z] 
[2022-09-17T00:14:33.157Z] During handling of the above exception, another exception occurred:
[2022-09-17T00:14:33.157Z] 
[2022-09-17T00:14:33.157Z] Traceback (most recent call last):
[2022-09-17T00:14:33.157Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
[2022-09-17T00:14:33.157Z]     res = func(*args, **kwargs)
[2022-09-17T00:14:33.157Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 56, in api_request
[2022-09-17T00:14:33.157Z]     return func(*arg, **kwargs)
[2022-09-17T00:14:33.157Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 496, in release
[2022-09-17T00:14:33.157Z]     conn.release_collection(self._name, timeout=timeout, **kwargs)
[2022-09-17T00:14:33.157Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 96, in handler
[2022-09-17T00:14:33.157Z]     raise e
[2022-09-17T00:14:33.157Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 92, in handler
[2022-09-17T00:14:33.157Z]     return func(*args, **kwargs)
[2022-09-17T00:14:33.157Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 62, in handler
[2022-09-17T00:14:33.157Z]     raise MilvusException(Status.UNEXPECTED_ERROR, f"rpc deadline exceeded: {timeout_msg}")
[2022-09-17T00:14:33.157Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)>
[2022-09-17T00:14:33.157Z]  (api_request.py:35)
[2022-09-17T00:14:33.157Z] [2022-09-16 23:32:29 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)> (api_request.py:36)
```

**Comment by NicoYuan1986** [comment]
Recently: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/123/pipeline/155/
1. milvus: master(911ea6c)  pymilvus: 2.2.0.dev33
2. collection name: query_nnyxgs6T
3. failed time: [2022-09-26T22:10:45.408Z] [gw2] [ 51%] FAILED testcases/test_query.py::TestqueryString::test_query_string_is_primary[varchar not in ["0", "1", "2"]]
4. milvus log: [artifacts-milvus-distributed-kafka-nightly-123-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/123/artifact/artifacts-milvus-distributed-kafka-nightly-123-pymilvus-e2e-logs.tar.gz)
5. error message:
```
[2022-09-26 22:10:21,968 - ERROR - ci_test]: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 884, in flush
    response = future.result()
  File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "{"created":"@1664230221.966727726","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":81,"grpc_status":4}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 408, in flush
    conn.flush([self.name], timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 113, in handler
    raise e
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 139, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 65, in handler
    raise MilvusException(Status.UNEXPECTED_ERROR, f"rpc deadline exceeded: {timeout_msg}")
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)>
 (api_request.py:39)
[2022-09-26 22:10:21,968 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)> (api_request.py:40)
```
