### ISSUE TITLE
[Bug]: [tracing] Search with invalid "client_request_id" leads normal search (without this param) broken

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#18903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master latest
- Deployment mode(standalone or cluster): both
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0.dev23
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Search with invalid "client_request_id" leads normal search (without this param) broken

```
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, expr="int64 >= 0", client_request_id=999888001, log_level="debug")
Unexcepted error: [search], Expected str, not <class 'int'>, <Time: {'RPC start': '2022-08-30 15:42:21.792461', 'Exception': '2022-08-30 15:42:21.794535'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/towhee-statistics-3.8/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 717, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/Users/binbin/towhee-statistics-3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 113, in handler
    raise e
  File "/Users/binbin/towhee-statistics-3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 97, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/towhee-statistics-3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 127, in handler
    ret = func(self, *args, **kwargs)
  File "/Users/binbin/towhee-statistics-3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 79, in handler
    raise e
  File "/Users/binbin/towhee-statistics-3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/towhee-statistics-3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 473, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/Users/binbin/towhee-statistics-3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 437, in _execute_search_requests
    raise pre_err
  File "/Users/binbin/towhee-statistics-3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 425, in _execute_search_requests
    response = ft.result()
  File "/Users/binbin/towhee-statistics-3.8/lib/python3.8/site-packages/grpc/_interceptor.py", line 126, in result
    raise self._exception
  File "/Users/binbin/towhee-statistics-3.8/lib/python3.8/site-packages/grpc/_interceptor.py", line 298, in future
    return self._interceptor.intercept_unary_unary(
  File "/Users/binbin/towhee-statistics-3.8/lib/python3.8/site-packages/pymilvus/client/interceptor.py", line 32, in intercept_unary_unary
    response = continuation(new_details, next(new_request_iterator))
  File "/Users/binbin/towhee-statistics-3.8/lib/python3.8/site-packages/grpc/_interceptor.py", line 289, in continuation
    return self._thunk(new_method).future(
  File "/Users/binbin/towhee-statistics-3.8/lib/python3.8/site-packages/grpc/_channel.py", line 972, in future
    call = self._managed_call(
  File "/Users/binbin/towhee-statistics-3.8/lib/python3.8/site-packages/grpc/_channel.py", line 1301, in create
    call = state.channel.integrated_call(flags, method, host, deadline,
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 474, in grpc._cython.cygrpc.Channel.integrated_call
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 294, in grpc._cython.cygrpc._integrated_call
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 218, in grpc._cython.cygrpc._call
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 246, in grpc._cython.cygrpc._call
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 89, in grpc._cython.cygrpc._operate
  File "src/python/grpcio/grpc/_cython/_cygrpc/tag.pyx.pxi", line 64, in grpc._cython.cygrpc._BatchOperationTag.prepare
  File "src/python/grpcio/grpc/_cython/_cygrpc/operation.pyx.pxi", line 37, in grpc._cython.cygrpc.SendInitialMetadataOperation.c
  File "src/python/grpcio/grpc/_cython/_cygrpc/metadata.pyx.pxi", line 43, in grpc._cython.cygrpc._store_c_metadata
  File "src/python/grpcio/grpc/_cython/_cygrpc/grpc_string.pyx.pxi", line 40, in grpc._cython.cygrpc._encode
TypeError: Expected str, not <class 'int'>
>>>
>>>
>>>
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
Unexcepted error: [search], Expected str, not <class 'int'>, <Time: {'RPC start': '2022-08-30 15:42:29.665886', 'Exception': '2022-08-30 15:42:29.667360'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/towhee-statistics-3.8/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 717, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/Users/binbin/towhee-statistics-3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 113, in handler
    raise e
  File "/Users/binbin/towhee-statistics-3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 97, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/towhee-statistics-3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 127, in handler
    ret = func(self, *args, **kwargs)
  File "/Users/binbin/towhee-statistics-3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 79, in handler
    raise e
  File "/Users/binbin/towhee-statistics-3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/towhee-statistics-3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 473, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/Users/binbin/towhee-statistics-3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 437, in _execute_search_requests
    raise pre_err
  File "/Users/binbin/towhee-statistics-3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 425, in _execute_search_requests
    response = ft.result()
  File "/Users/binbin/towhee-statistics-3.8/lib/python3.8/site-packages/grpc/_interceptor.py", line 126, in result
    raise self._exception
  File "/Users/binbin/towhee-statistics-3.8/lib/python3.8/site-packages/grpc/_interceptor.py", line 298, in future
    return self._interceptor.intercept_unary_unary(
  File "/Users/binbin/towhee-statistics-3.8/lib/python3.8/site-packages/pymilvus/client/interceptor.py", line 32, in intercept_unary_unary
    response = continuation(new_details, next(new_request_iterator))
  File "/Users/binbin/towhee-statistics-3.8/lib/python3.8/site-packages/grpc/_interceptor.py", line 289, in continuation
    return self._thunk(new_method).future(
  File "/Users/binbin/towhee-statistics-3.8/lib/python3.8/site-packages/grpc/_channel.py", line 972, in future
    call = self._managed_call(
  File "/Users/binbin/towhee-statistics-3.8/lib/python3.8/site-packages/grpc/_channel.py", line 1301, in create
    call = state.channel.integrated_call(flags, method, host, deadline,
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 474, in grpc._cython.cygrpc.Channel.integrated_call
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 294, in grpc._cython.cygrpc._integrated_call
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 218, in grpc._cython.cygrpc._call
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 246, in grpc._cython.cygrpc._call
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 89, in grpc._cython.cygrpc._operate
  File "src/python/grpcio/grpc/_cython/_cygrpc/tag.pyx.pxi", line 64, in grpc._cython.cygrpc._BatchOperationTag.prepare
  File "src/python/grpcio/grpc/_cython/_cygrpc/operation.pyx.pxi", line 37, in grpc._cython.cygrpc.SendInitialMetadataOperation.c
  File "src/python/grpcio/grpc/_cython/_cygrpc/metadata.pyx.pxi", line 43, in grpc._cython.cygrpc._store_c_metadata
  File "src/python/grpcio/grpc/_cython/_cygrpc/grpc_string.pyx.pxi", line 40, in grpc._cython.cygrpc._encode
TypeError: Expected str, not <class 'int'>
```

### Expected Behavior

Invalid parameters of one search request should not influence other search requests

### Milvus Log

```python
from pymilvus import CollectionSchema, FieldSchema
from pymilvus import Collection
from pymilvus import connections
from pymilvus import DataType
from pymilvus import Partition
from pymilvus import utility

connections.connect(host="localhost")

dim = 128
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
bool_field = FieldSchema(name="bool", dtype=DataType.BOOL)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
schema = CollectionSchema(fields=[int64_field, float_field, bool_field, float_vector])
collection = Collection("test_search_collection_binbin_1", schema=schema)
import numpy as np
import random
nb=1000
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], [np.bool(i) for i in range(nb)], vectors])
collection.load()
default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
nq = 2
limit = 10

print("Search with valid client_request_id, expected as success")
res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, expr="int64 >= 0", client_request_id="999888001", log_level="debug")

print("Search without client_request_id, expected as success")
res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")

print("Search with invalid client_request_id, expected as fail")
try:
   res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, expr="int64 >= 0", client_request_id=999888001, log_level="debug")
except Exception as e:
   print(e)

print("Search without client_request_id, expected as success")
res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
```

**Comment by binbinlv** [comment]
And if search with valid client_request_id again, then normal search (without client_request_id) successfully again.

So it seems some state of grpc is not reset to original value when abort a search request.
