### ISSUE TITLE
[Bug]: [Diskann Index]Milvus create diskann index and then search, in which the search parameter passes a number and an error is reported

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#18958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:xige-16-build-diskann-31-11-55-27a9f4115-20220831
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0.dev23
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

default_diskann_search_params ={"metric_type": "L2", "params": {"search_list": 30}}
testcase:
```
    @pytest.mark.tags(CaseLabel.L1)
    def test_create_index_with_diskann_normal(self):
        """
        target: test create index with diskann
        method: 1.create collection and insert data 
                2.create diskann index ,then load
                3.search 
        expected: create index successfully
        """
        c_name = cf.gen_unique_str(prefix)
        collection_w = self.init_collection_wrap(name=c_name)
        data = cf.gen_default_list_data()
        collection_w.insert(data=data)
        index, _ = self.index_wrap.init_index(collection_w.collection, default_float_vec_field_name, ct.default_diskann_index)
        cf.assert_equal_index(index, collection_w.indexes[0])
        collection_w.load()
        assert collection_w.num_entities == default_nb
        vectors = [[random.random() for _ in range(default_dim)] for _ in range(default_nq)]
        search_res, _=collection_w.search(vectors[:default_nq], default_search_field,
                            ct.default_diskann_search_params, default_limit,
                            default_search_exp)
        assert len(search_res[0]) == ct.default_limit
```

log:
```

[2022-08-31 17:44:54 - DEBUG - ci_test]: (api_response) : <pymilvus.orm.index.Index object at 0x7fdd495136a0>  (api_request.py:31)
[2022-08-31 17:44:54 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 20], kwargs: {} (api_request.py:56)
[2022-08-31 17:45:08 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)
[2022-08-31 17:45:08 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 20} (api_request.py:56)
[2022-08-31 17:45:08 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)
[2022-08-31 17:45:08 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.3705810970408612, 0.07658051666198762, 0.5845448237972983, 0.09716272091242384, 0.5596291786573331, 0.8783417161695668, 0.6703133295980618, 0.12278385427673855, 0.5336630865419483, 0.7193538772873748, 0.28934372908458117, 0.30040979149511116, 0.1804531162406403, 0.4005707143286996, 0.4971284972......, kwargs: {} (api_request.py:56)
[2022-08-31 17:45:08 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=2, reason=Search 2 failed, reason [UnexpectedError] [json.exception.type_error.302] type must be string, but is number err %!w(<nil>))>, <Time:{'RPC start': '2022-08-31 17:45:08.065876', 'RPC error': '2022-08-31 17:45:08.392369'}> (decorators.py:95)
[2022-08-31 17:45:08 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/jingjing/Workspace/milvus_diskann/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/Users/jingjing/Workspace/milvus_diskann/tests/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 717, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 96, in handler
    raise e
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 92, in handler
    return func(*args, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/decorators.py", line 48, in handler
    return func(self, *args, **kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 452, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 416, in _execute_search_requests
    raise pre_err
  File "/Users/jingjing/miniconda3/envs/bbb/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 407, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=2, reason=Search 2 failed, reason [UnexpectedError] [json.exception.type_error.302] type must be string, but is number err %!w(<nil>))>
 (api_request.py:39)
[2022-08-31 17:45:08 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=2, reason=Search 2 failed, reason [UnexpectedError] [json.exception.type_error.302] type must be string, but is number err %!w(<nil>))> (api_request.py:40)
```

**Comment by xige-16** [comment]
The type of search list is int, but when segcore checks the type of search list, it is checked as string, I will fix it.

**Comment by xige-16** [comment]
has fixed, please verify @jingkl 
/assign @jingkl 
/unassign @jingkl

**Comment by jingkl** [comment]
This question has been verified
master-20220929-64662919
pymilvus.2.2.0dev36
