### ISSUE TITLE
[Bug]: [Nightly]Search failed with reason "Search 13 failed, cannot find sealed segment 435627307350822209 in QueryNode err %!w(<nil>)"

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#18961]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.*(41fa0686)
- Deployment mode(standalone or cluster):cluster(pulsar)
- SDK version(e.g. pymilvus v2.0.0rc2):2.1.2.dev2
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2022-08-31T21:10:36.856Z] [2022-08-31 20:29:04 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=Search 17 failed, reason cannot find sealed segment 435677492719386625 in QueryNode err %!w(<nil>))>, <Time:{'RPC start': '2022-08-31 20:29:03.850794', 'RPC error': '2022-08-31 20:29:04.459141'}> (decorators.py:95)
[2022-08-31T21:10:36.856Z] [2022-08-31 20:29:04 - ERROR - ci_test]: Traceback (most recent call last):
[2022-08-31T21:10:36.856Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
[2022-08-31T21:10:36.856Z]     res = func(*args, **kwargs)
[2022-08-31T21:10:36.856Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 56, in api_request
[2022-08-31T21:10:36.856Z]     return func(*arg, **kwargs)
[2022-08-31T21:10:36.856Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 713, in search
[2022-08-31T21:10:36.856Z]     partition_names, output_fields, round_decimal, timeout=timeout, schema=schema_dict, **kwargs)
[2022-08-31T21:10:36.856Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 96, in handler
[2022-08-31T21:10:36.856Z]     raise e
[2022-08-31T21:10:36.856Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 92, in handler
[2022-08-31T21:10:36.856Z]     return func(*args, **kwargs)
[2022-08-31T21:10:36.856Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler
[2022-08-31T21:10:36.856Z]     raise e
[2022-08-31T21:10:36.856Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 48, in handler
[2022-08-31T21:10:36.856Z]     return func(self, *args, **kwargs)
[2022-08-31T21:10:36.856Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 446, in search
[2022-08-31T21:10:36.856Z]     return self._execute_search_requests(requests, timeout, **_kwargs)
[2022-08-31T21:10:36.856Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 410, in _execute_search_requests
[2022-08-31T21:10:36.856Z]     raise pre_err
[2022-08-31T21:10:36.856Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 401, in _execute_search_requests
[2022-08-31T21:10:36.856Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2022-08-31T21:10:36.856Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=Search 17 failed, reason cannot find sealed segment 435677492719386625 in QueryNode err %!w(<nil>))>
[2022-08-31T21:10:36.856Z]  (api_request.py:35)
[2022-08-31T21:10:36.856Z] [2022-08-31 20:29:04 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=Search 17 failed, reason cannot find sealed segment 435677492719386625 in QueryNode err %!w(<nil>))> (api_request.py:36)
```

### Expected Behavior

PASSED

### Steps To Reproduce

```markdown
nightly :
https://jenkins.milvus.io:18080/blue/organizations/jenkins/qa%2Fmilvus-release-nightly/detail/milvus-release-nightly/72/pipeline/177
```

### Milvus Log

1. FAILED time: [2022-08-31T20:29:04.876Z] [gw0] [ 40%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_with_ndarray[128-True-False]
2. collection name: search_collection_umifIDDF
3. milvus log: [milvus-distributed-pulsar-72-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/qa/job/milvus-release-nightly/72/artifact/milvus-distributed-pulsar-72-pymilvus-e2e-logs.tar.gz)

**Comment by NicoYuan1986** [comment]
Similar error:
The error occurs in the nightly for the master(https://github.com/milvus-io/milvus/commit/1527aee019bb20fa564f98e1f27712535cd20bd3) branch:
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/66/pipeline/143
1. milvus log: [artifacts-milvus-distributed-kafka-nightly-66-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/66/artifact/artifacts-milvus-distributed-kafka-nightly-66-pymilvus-e2e-logs.tar.gz)
2. pymilvus: 2.2.0.dev23
3. collection name: search_collection_Ti6uoXSM
4. Failed timeline: [2022-08-29T15:18:22.754Z] [gw1] [ 45%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_with_dup_primary_key[8-True-False-3]
5. test error:
```
[2022-08-29T16:00:24.595Z] [2022-08-29 15:18:22 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=12, reason=Search 13 failed, reason cannot find sealed segment 435627307350822209 in QueryNode err %!w(<nil>))>, <Time:{'RPC start': '2022-08-29 15:18:21.638138', 'RPC error': '2022-08-29 15:18:22.037138'}> (decorators.py:100)
[2022-08-29T16:00:24.595Z] [2022-08-29 15:18:22 - ERROR - ci_test]: Traceback (most recent call last):
[2022-08-29T16:00:24.595Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2022-08-29T16:00:24.595Z]     res = func(*args, **_kwargs)
[2022-08-29T16:00:24.595Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2022-08-29T16:00:24.595Z]     return func(*arg, **kwargs)
[2022-08-29T16:00:24.595Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 717, in search
[2022-08-29T16:00:24.595Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,
[2022-08-29T16:00:24.595Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 101, in handler
[2022-08-29T16:00:24.595Z]     raise e
[2022-08-29T16:00:24.595Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 97, in handler
[2022-08-29T16:00:24.595Z]     return func(*args, **kwargs)
[2022-08-29T16:00:24.595Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 127, in handler
[2022-08-29T16:00:24.595Z]     ret = func(self, *args, **kwargs)
[2022-08-29T16:00:24.595Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 79, in handler
[2022-08-29T16:00:24.595Z]     raise e
[2022-08-29T16:00:24.595Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2022-08-29T16:00:24.595Z]     return func(self, *args, **kwargs)
[2022-08-29T16:00:24.595Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 473, in search
[2022-08-29T16:00:24.595Z]     return self._execute_search_requests(requests, timeout, **_kwargs)
[2022-08-29T16:00:24.595Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 437, in _execute_search_requests
[2022-08-29T16:00:24.595Z]     raise pre_err
[2022-08-29T16:00:24.595Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 428, in _execute_search_requests
[2022-08-29T16:00:24.595Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2022-08-29T16:00:24.595Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=12, reason=Search 13 failed, reason cannot find sealed segment 435627307350822209 in QueryNode err %!w(<nil>))>
[2022-08-29T16:00:24.595Z]  (api_request.py:39)
[2022-08-29T16:00:24.595Z] [2022-08-29 15:18:22 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=12, reason=Search 13 failed, reason cannot find sealed segment 435627307350822209 in QueryNode err %!w(<nil>))> (api_request.py:40)
```

**Comment by NicoYuan1986** [comment]
Latest:
The error occurs in the nightly for the master(68a6587) branch:https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/78/pipeline/187/
1. milvus log: [artifacts-milvus-distributed-pulsar-nightly-78-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/78/artifact/artifacts-milvus-distributed-pulsar-nightly-78-pymilvus-e2e-logs.tar.gz)
2. pymilvus: 2.2.0.dev26
3. collection name: search_collection_etqY7wg3
4. Failed timeline:[2022-09-04T15:21:04.631Z] [gw2] [ 47%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_with_dup_primary_key[128-False-False-1]
5. test error:
```
[2022-09-04T16:05:50.468Z] [2022-09-04 15:21:04 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=Search 16 failed, reason cannot find sealed segment 435763245184450561 in QueryNode err %!w(<nil>))>, <Time:{'RPC start': '2022-09-04 15:21:03.808108', 'RPC error': '2022-09-04 15:21:04.094567'}> (decorators.py:100)
[2022-09-04T16:05:50.468Z] [2022-09-04 15:21:04 - ERROR - ci_test]: Traceback (most recent call last):
[2022-09-04T16:05:50.468Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2022-09-04T16:05:50.468Z]     res = func(*args, **_kwargs)
[2022-09-04T16:05:50.468Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2022-09-04T16:05:50.468Z]     return func(*arg, **kwargs)
[2022-09-04T16:05:50.468Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 717, in search
[2022-09-04T16:05:50.468Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,
[2022-09-04T16:05:50.468Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 101, in handler
[2022-09-04T16:05:50.468Z]     raise e
[2022-09-04T16:05:50.468Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 97, in handler
[2022-09-04T16:05:50.468Z]     return func(*args, **kwargs)
[2022-09-04T16:05:50.468Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 127, in handler
[2022-09-04T16:05:50.468Z]     ret = func(self, *args, **kwargs)
[2022-09-04T16:05:50.468Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 79, in handler
[2022-09-04T16:05:50.468Z]     raise e
[2022-09-04T16:05:50.468Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2022-09-04T16:05:50.468Z]     return func(self, *args, **kwargs)
[2022-09-04T16:05:50.468Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 473, in search
[2022-09-04T16:05:50.468Z]     return self._execute_search_requests(requests, timeout, **_kwargs)
[2022-09-04T16:05:50.468Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 437, in _execute_search_requests
[2022-09-04T16:05:50.468Z]     raise pre_err
[2022-09-04T16:05:50.468Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 428, in _execute_search_requests
[2022-09-04T16:05:50.468Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2022-09-04T16:05:50.468Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=Search 16 failed, reason cannot find sealed segment 435763245184450561 in QueryNode err %!w(<nil>))>
[2022-09-04T16:05:50.468Z]  (api_request.py:39)
[2022-09-04T16:05:50.468Z] [2022-09-04 15:21:04 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=Search 16 failed, reason cannot find sealed segment 435763245184450561 in QueryNode err %!w(<nil>))> (api_request.py:40)
```

**Comment by jiaoew1991** [comment]
one of the querynode which id is 10 has restarted, the restart reason should be figured out in another issue, after restarted there were 2 shard leaders in one shard, which caused brain split, some segments which should be online been released

we will try to find the reason.

**Comment by jiaoew1991** [comment]
fixed by https://github.com/milvus-io/milvus/pull/19064

**Comment by NicoYuan1986** [comment]
Latest:
The error occurs in the nightly for the 2.1.* branch: https://jenkins.milvus.io:18080/blue/organizations/jenkins/qa%2Fmilvus-release-nightly/detail/milvus-release-nightly/89/pipeline/177
1. milvus log: [milvus-distributed-kafka-89-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/qa/job/milvus-release-nightly/89/artifact/milvus-distributed-kafka-89-pymilvus-e2e-logs.tar.gz)
2. pymilvus: 2.1.2.dev2
3. collection name: search_collection_k1mmP7dI
4. Failed timeline: 3. [2022-09-08T23:35:09.352Z] [gw4] [ 42%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_after_different_index_with_params[8-False-False-RHNSW_FLAT-params6] 
5. test error: 
```
[2022-09-09T00:22:58.242Z] [2022-09-08 23:35:08 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=5, reason=Search 14 failed, reason cannot find sealed segment 435861612911394818 in QueryNode err %!w(<nil>))>, <Time:{'RPC start': '2022-09-08 23:35:08.334450', 'RPC error': '2022-09-08 23:35:08.650798'}> (decorators.py:95)
[2022-09-09T00:22:58.242Z] [2022-09-08 23:35:08 - ERROR - ci_test]: Traceback (most recent call last):
[2022-09-09T00:22:58.242Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
[2022-09-09T00:22:58.242Z]     res = func(*args, **kwargs)
[2022-09-09T00:22:58.242Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 56, in api_request
[2022-09-09T00:22:58.242Z]     return func(*arg, **kwargs)
[2022-09-09T00:22:58.242Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 713, in search
[2022-09-09T00:22:58.242Z]     partition_names, output_fields, round_decimal, timeout=timeout, schema=schema_dict, **kwargs)
[2022-09-09T00:22:58.242Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 96, in handler
[2022-09-09T00:22:58.242Z]     raise e
[2022-09-09T00:22:58.242Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 92, in handler
[2022-09-09T00:22:58.242Z]     return func(*args, **kwargs)
[2022-09-09T00:22:58.242Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler
[2022-09-09T00:22:58.242Z]     raise e
[2022-09-09T00:22:58.242Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 48, in handler
[2022-09-09T00:22:58.242Z]     return func(self, *args, **kwargs)
[2022-09-09T00:22:58.242Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 446, in search
[2022-09-09T00:22:58.242Z]     return self._execute_search_requests(requests, timeout, **_kwargs)
[2022-09-09T00:22:58.242Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 410, in _execute_search_requests
[2022-09-09T00:22:58.242Z]     raise pre_err
[2022-09-09T00:22:58.242Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 401, in _execute_search_requests
[2022-09-09T00:22:58.242Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2022-09-09T00:22:58.242Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=5, reason=Search 14 failed, reason cannot find sealed segment 435861612911394818 in QueryNode err %!w(<nil>))>
[2022-09-09T00:22:58.242Z]  (api_request.py:35)
[2022-09-09T00:22:58.242Z] [2022-09-08 23:35:08 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=5, reason=Search 14 failed, reason cannot find sealed segment 435861612911394818 in QueryNode err %!w(<nil>))> (api_request.py:36)
```

**Comment by NicoYuan1986** [comment]
Latest:
The error occurs in the nightly for the 2.1.* branch: https://jenkins.milvus.io:18080/blue/organizations/jenkins/qa%2Fmilvus-release-nightly/detail/milvus-release-nightly/113/pipeline/177
1. milvus log: [milvus-distributed-kafka-113-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/qa/job/milvus-release-nightly/113/artifact/milvus-distributed-kafka-113-pymilvus-e2e-logs.tar.gz)
2. pymilvus: 2.1.2.dev9
3. collection name: search_collection_3TiL5POS
4. Failed timeline: [2022-09-20T20:33:10.374Z] [gw4] [ 41%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_after_different_index_with_params[8-False-False-FLAT-params0]
5. test error:
```
[2022-09-20T21:17:40.388Z] [2022-09-20 20:33:09 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=13, reason=Search 13 failed, reason cannot find sealed segment 436130541598932993 in QueryNode err %!w(<nil>))>, <Time:{'RPC start': '2022-09-20 20:33:09.366359', 'RPC error': '2022-09-20 20:33:09.840887'}> (decorators.py:95)
[2022-09-20T21:17:40.388Z] [2022-09-20 20:33:09 - ERROR - ci_test]: Traceback (most recent call last):
[2022-09-20T21:17:40.388Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
[2022-09-20T21:17:40.388Z]     res = func(*args, **kwargs)
[2022-09-20T21:17:40.388Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 56, in api_request
[2022-09-20T21:17:40.388Z]     return func(*arg, **kwargs)
[2022-09-20T21:17:40.388Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 713, in search
[2022-09-20T21:17:40.388Z]     partition_names, output_fields, round_decimal, timeout=timeout, schema=schema_dict, **kwargs)
[2022-09-20T21:17:40.388Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 96, in handler
[2022-09-20T21:17:40.388Z]     raise e
[2022-09-20T21:17:40.388Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 92, in handler
[2022-09-20T21:17:40.388Z]     return func(*args, **kwargs)
[2022-09-20T21:17:40.388Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler
[2022-09-20T21:17:40.388Z]     raise e
[2022-09-20T21:17:40.388Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 48, in handler
[2022-09-20T21:17:40.388Z]     return func(self, *args, **kwargs)
[2022-09-20T21:17:40.388Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 446, in search
[2022-09-20T21:17:40.388Z]     return self._execute_search_requests(requests, timeout, **_kwargs)
[2022-09-20T21:17:40.388Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 410, in _execute_search_requests
[2022-09-20T21:17:40.388Z]     raise pre_err
[2022-09-20T21:17:40.388Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 401, in _execute_search_requests
[2022-09-20T21:17:40.388Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2022-09-20T21:17:40.388Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=13, reason=Search 13 failed, reason cannot find sealed segment 436130541598932993 in QueryNode err %!w(<nil>))>
[2022-09-20T21:17:40.388Z]  (api_request.py:35)
[2022-09-20T21:17:40.388Z] [2022-09-20 20:33:09 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=13, reason=Search 13 failed, reason cannot find sealed segment 436130541598932993 in QueryNode err %!w(<nil>))> (api_request.py:36)
```

**Comment by NicoYuan1986** [comment]
Latest:
The error occurs in the nightly for the master branch:https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/123/pipeline/155/
1. pymilvus: 2.2.0.dev33
2. milvus log: [artifacts-milvus-distributed-kafka-nightly-123-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/123/artifact/artifacts-milvus-distributed-kafka-nightly-123-pymilvus-e2e-logs.tar.gz)
3. collection name: search_collection_gLk8lp0G
4. Failed timeline: [2022-09-26T23:09:33.107Z] [gw1] [ 64%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_after_index_different_metric_type[128-True-False-ANNOY-params5]
5. test error:
```
[2022-09-26 23:09:31,374 - ERROR - ci_test]: Traceback (most recent call last):
  File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 717, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 113, in handler
    raise e
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 139, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 89, in handler
    raise e
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 464, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 428, in _execute_search_requests
    raise pre_err
  File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 419, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=3, reason=Search 3 failed, reason cannot find sealed segment 436266831372408601 in QueryNode err %!w(<nil>))>
 (api_request.py:39)
[2022-09-26 23:09:31,374 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=3, reason=Search 3 failed, reason cannot find sealed segment 436266831372408601 in QueryNode err %!w(<nil>))> (api_request.py:40)
```

**Comment by NicoYuan1986** [comment]
This issue no longer occurs in master(a8cabbf).
