### ISSUE TITLE
[Bug]: [Diskann Index]Milvus searches after creating a diskann index and reports an unclear error when entering out-of-range search parameters

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#18978]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: xige-16-build-diskann-31-21-45-b7691531a-20220831
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0.dev23
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

**There are two problems with this log.
1. the error reporting statements in the log are too long and unclear
2. The parameter range of search_list is incorrect and does not match the maximum search list of 65535*3**

server：

```
fouram-jj-ntdxn-1-etcd-0                                          1/1     Running   0          102s    10.104.5.25    4am-node12   <
none>           <none>
fouram-jj-ntdxn-1-milvus-standalone-7b97966884-djnj4              1/1     Running   0          102s    10.104.9.253   4am-node14   <
none>           <none>
fouram-jj-ntdxn-1-minio-554cbcd9f9-jbq7k                          1/1     Running   0          102s    10.104.5.24    4am-node12   <
none>           <none>
```

log：
```
[2022-09-01 21:36:00,240] [    INFO] - {'nq': 500, 'topk': 100, 'search_param': {'search_list': 50}, 'filter': [], 'guarantee_timestamp': None} (milvus_benchmark.runners.search:307)
[2022-09-01 21:36:00,282] [   ERROR] - RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=2, reason=Search 2 failed, reason [UnexpectedError] Error in void knowhere::{anonymous}::CheckNumericParamAndSet(const Config&, const string&, std::optional<_Tp>, std::optional<_Tp>, T&) [with T = unsigned int; knowhere::Config = nlohmann::basic_json<>; std::string = std::__cxx11::basic_string<char>] at IndexDiskANNConfig.cpp:83: Param 'search_list_size'(50) is not in range [100, 4294967295] err %!w(<nil>))>, <Time:{'RPC start': '2022-09-01 21:36:00.240572', 'RPC error': '2022-09-01 21:36:00.282079'}> (pymilvus.decorators:100)
[2022-09-01 21:36:00,282] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 95, in run_suite
    result = runner.run_case(case_metric, **case)
  File "/src/milvus_benchmark/runners/search.py", line 309, in run_case
    _query_res = self.milvus.query(case_param["vector_query"], filter_query=case_param["filter_query"],
  File "/src/milvus_benchmark/client.py", line 53, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 339, in query
    result = self._milvus.search(tmp_collection_name, **params)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/stub.py", line 844, in search
    return handler.search(collection_name, data, anns_field, param, limit, expression,
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 101, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 97, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 127, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 79, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 473, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 437, in _execute_search_requests
    raise pre_err
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 428, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=2, reason=Search 2 failed, reason [UnexpectedError] Error in void knowhere::{anonymous}::CheckNumericParamAndSet(const Config&, const string&, std::optional<_Tp>, std::optional<_Tp>, T&) [with T = unsigned int; knowhere::Config = nlohmann::basic_json<>; std::string = std::__cxx11::basic_string<char>] at IndexDiskANNConfig.cpp:83: Param 'search_list_size'(50) is not in range [100, 4294967295] err %!w(<nil>))>
```

**Comment by xige-16** [comment]
The value range of the search list is (topk, topk * 10). If the search list is not in this range, an error will be reported. In addition, the error message is not good. I will fix it sson.

**Comment by xige-16** [comment]
if search_list < top, the error msg will be "search_list should be greater than topk"
if search_list > topk * 10 or search_list > 65535, the error msg will be "search_list should less than min(topk*10, 65535)"

**Comment by xige-16** [comment]
please verify @jingkl 
/assign @jingkl 
/unassign @xige-16

**Comment by jingkl** [comment]
search_list<topk will still have some cases that will pass

```
@pytest.mark.tags(CaseLabel.L1)
    def test_search_invalid_params_with_diskann_A(self, dim, auto_id):
        """
        target: test delete after creating index
        method: 1.create collection , insert data, primary_field is string field
                2.create index 
                3.search with invalid params, where search_list < topk 
                (search list range in [topk, topk*10])
        expected: assert index and deleted id not in search result
        """
        # 1. initialize with data
        collection_w, _, _, insert_ids = \
            self.init_collection_general(prefix, True, auto_id=auto_id, dim=dim, is_index=True)[0:4]
        # 2. create index
        collection_w.load()
        default_index = {"index_type": "DISKANN", "metric_type":"L2", "params": {}}
        collection_w.create_index(ct.default_float_vec_field_name, default_index)
        
        default_search_params ={"metric_type": "L2", "params": {"search_list": 5}}
        vectors = [[random.random() for _ in range(dim)] for _ in range(default_nq)]
        output_fields = [default_int64_field_name, default_float_field_name,  default_string_field_name]
        search_res, _ = collection_w.search(vectors[:default_nq], default_search_field,
                            default_search_params, default_limit, 
                            default_search_exp,
                            output_fields=output_fields,
                            travel_timestamp=0,
                            check_task=CheckTasks.check_search_results,
                            check_items={"nq": default_nq,
                                         "ids": insert_ids,
                                         "limit": default_limit}
                            )
```
<img width="1103" alt="截屏2022-09-29 23 02 31" src="https://user-images.githubusercontent.com/34296482/193067758-1c9ecba8-c32d-4a69-9e24-ce78082ea462.png">

**Comment by jingkl** [comment]
Please verify @xige-16 
/unassign @jingkl 
master-20220929-64662919
pymilvus.2.2.0dev36
