### ISSUE TITLE
[Bug]: v2.1.1 Service often goes down

### ISSUE THREAD

**Issue by bestRiven** [milvus-io/milvus#19008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.1
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

[2022/09/04 22:29:18.505 +00:00] [ERROR] [datanode/flow_graph_delete_node.go:248] ["failed to flush delete data, err = All attempts results:\nattempt #1:invalid start/end timestamp\nattempt #2:invalid start/end timestamp\nattempt #3:invalid start/end timestamp\nattempt #4:invalid start/end timestamp\nattempt #5:invalid start/end timestamp\n"] [stack="[github.com/milvus-io/milvus/internal/datanode.(*deleteNode).Operate\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_delete_node.go:248\ngithub.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work\n\t/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:102](http://github.com/milvus-io/milvus/internal/datanode.(*deleteNode).Operate/n/t/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_delete_node.go:248/ngithub.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work/n/t/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:102)"]
panic: failed to flush delete data, err = All attempts results:
attempt #1:invalid start/end timestamp
attempt #2:invalid start/end timestamp
attempt #3:invalid start/end timestamp
attempt #4:invalid start/end timestamp
attempt #5:invalid start/end timestamp
goroutine 543862 [running]:
[github.com/milvus-io/milvus/internal/datanode.(*deleteNode).Operate](http://github.com/milvus-io/milvus/internal/datanode.(*deleteNode).Operate)(0xc004045ef0, 0xc00a835c50, 0x1, 0x1, 0x0, 0x0, 0x0)
        /go/src/[github.com/milvus-io/milvus/internal/datanode/flow_graph_delete_node.go:249](http://github.com/milvus-io/milvus/internal/datanode/flow_graph_delete_node.go:249) +0x10c5
[github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work(0xc03219ab80)](http://github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work(0xc03219ab80))
        /go/src/[github.com/milvus-io/milvus/internal/util/flowgraph/node.go:102](http://github.com/milvus-io/milvus/internal/util/flowgraph/node.go:102) +0x23b
created by [github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start](http://github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start)
        /go/src/[github.com/milvus-io/milvus/internal/util/flowgraph/node.go:70](http://github.com/milvus-io/milvus/internal/util/flowgraph/node.go:70) +0x70

### Milvus Log

[2022/09/04 22:29:18.505 +00:00] [ERROR] [datanode/flow_graph_delete_node.go:248] ["failed to flush delete data, err = All attempts results:\nattempt #1:invalid start/end timestamp\nattempt #2:invalid start/end timestamp\nattempt #3:invalid start/end timestamp\nattempt #4:invalid start/end timestamp\nattempt #5:invalid start/end timestamp\n"] [stack="[github.com/milvus-io/milvus/internal/datanode.(*deleteNode).Operate\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_delete_node.go:248\ngithub.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work\n\t/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:102](http://github.com/milvus-io/milvus/internal/datanode.(*deleteNode).Operate/n/t/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_delete_node.go:248/ngithub.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work/n/t/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:102)"]
panic: failed to flush delete data, err = All attempts results:
attempt #1:invalid start/end timestamp
attempt #2:invalid start/end timestamp
attempt #3:invalid start/end timestamp
attempt #4:invalid start/end timestamp
attempt #5:invalid start/end timestamp
goroutine 543862 [running]:
[github.com/milvus-io/milvus/internal/datanode.(*deleteNode).Operate](http://github.com/milvus-io/milvus/internal/datanode.(*deleteNode).Operate)(0xc004045ef0, 0xc00a835c50, 0x1, 0x1, 0x0, 0x0, 0x0)
        /go/src/[github.com/milvus-io/milvus/internal/datanode/flow_graph_delete_node.go:249](http://github.com/milvus-io/milvus/internal/datanode/flow_graph_delete_node.go:249) +0x10c5
[github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work(0xc03219ab80)](http://github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work(0xc03219ab80))
        /go/src/[github.com/milvus-io/milvus/internal/util/flowgraph/node.go:102](http://github.com/milvus-io/milvus/internal/util/flowgraph/node.go:102) +0x23b
created by [github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start](http://github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start)
        /go/src/[github.com/milvus-io/milvus/internal/util/flowgraph/node.go:70](http://github.com/milvus-io/milvus/internal/util/flowgraph/node.go:70) +0x70

**Comment by yanliang567** [comment]
@bestRiven thank you for the issue, could you please share more details about the reproduce steps? Also please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation.

/assign @bestRiven 
/unassign

**Comment by bestRiven** [comment]
链接: https://pan.baidu.com/s/1TKyDEk0FNLc8VhP3Nd66ag 提取码: 9h6q

**Comment by mausch** [comment]
I think this is a duplicate of https://github.com/milvus-io/milvus/issues/18565

**Comment by JackLCL** [comment]
@bestRiven 
Milvus 2.1.2 is released. You can this new version to check whether your problem is solved.
