### ISSUE TITLE
[Bug]: [Nightly]Search failed reporting "code=1, message=, context deadline exceeded"

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#19014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master(68a6587)
- Deployment mode(standalone or cluster):cluster(pulsar)
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0.dev26
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Search failed reporting "code=1, message=, context deadline exceeded".
```
[2022-09-04T16:05:50.465Z] [2022-09-04 15:20:12 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=, context deadline exceeded)>, <Time:{'RPC start': '2022-09-04 15:20:11.047083', 'RPC error': '2022-09-04 15:20:12.093334'}> (decorators.py:100)
[2022-09-04T16:05:50.465Z] [2022-09-04 15:20:12 - ERROR - ci_test]: Traceback (most recent call last):
[2022-09-04T16:05:50.465Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2022-09-04T16:05:50.465Z]     res = func(*args, **_kwargs)
[2022-09-04T16:05:50.465Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2022-09-04T16:05:50.465Z]     return func(*arg, **kwargs)
[2022-09-04T16:05:50.465Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 474, in load
[2022-09-04T16:05:50.465Z]     conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
[2022-09-04T16:05:50.465Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 101, in handler
[2022-09-04T16:05:50.465Z]     raise e
[2022-09-04T16:05:50.465Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 97, in handler
[2022-09-04T16:05:50.465Z]     return func(*args, **kwargs)
[2022-09-04T16:05:50.465Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 127, in handler
[2022-09-04T16:05:50.465Z]     ret = func(self, *args, **kwargs)
[2022-09-04T16:05:50.465Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 79, in handler
[2022-09-04T16:05:50.465Z]     raise e
[2022-09-04T16:05:50.465Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2022-09-04T16:05:50.465Z]     return func(self, *args, **kwargs)
[2022-09-04T16:05:50.465Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 697, in load_collection
[2022-09-04T16:05:50.465Z]     raise MilvusException(response.error_code, response.reason)
[2022-09-04T16:05:50.465Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=, context deadline exceeded)>
[2022-09-04T16:05:50.465Z]  (api_request.py:39)
[2022-09-04T16:05:50.465Z] [2022-09-04 15:20:12 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=, context deadline exceeded)> (api_request.py:40)
```

### Expected Behavior

PASSED

### Steps To Reproduce

```markdown
nightly: 
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/78/pipeline/187/
```

### Milvus Log

1. FAILED time: [2022-09-04T15:20:12.496Z] [gw2] [ 45%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_with_dup_primary_key[8-False-False-3] 
2. collection name: search_collection_SJuVm9P5
3. milvus log: [artifacts-milvus-distributed-pulsar-nightly-78-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/78/artifact/artifacts-milvus-distributed-pulsar-nightly-78-pymilvus-e2e-logs.tar.gz)

**Comment by weiliu1031** [comment]
same problem with https://github.com/milvus-io/milvus/issues/18846#issuecomment-1236520468

query node restart cause load collection failed.

**Comment by NicoYuan1986** [comment]
Same with #18846
