### ISSUE TITLE
[Bug]: Create index timeout for 2.1 branch image sometimes

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#19011]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.0-20220902-853793a
- Deployment mode(standalone or cluster):both
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus==2.2.0.dev26
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/12268675/188353483-1bd0f812-86b2-48db-8dc0-2e2b004c646d.png)
```
[2022-09-05T02:46:57.523Z] [2022-09-05 02:44:23 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['binary_vector', {'index_type': 'BIN_IVF_FLAT', 'params': {'nlist': 128}, 'metric_type': 'HAMMING'}], kwargs: {'timeout': 40, 'index_name': '_default_idx'} (api_request.py:56)
[2022-09-05T02:46:57.523Z] [2022-09-05 02:45:04 - ERROR - pymilvus.decorators]: RPC error: [wait_for_creating_index], <MilvusException: (code=1, message=CreateIndex Timeout)>, <Time:{'RPC start': '2022-09-05 02:44:23.934422', 'RPC error': '2022-09-05 02:45:04.239861'}> (decorators.py:100)
[2022-09-05T02:46:57.523Z] [2022-09-05 02:45:04 - ERROR - pymilvus.decorators]: RPC error: [create_index], <MilvusException: (code=1, message=CreateIndex Timeout)>, <Time:{'RPC start': '2022-09-05 02:44:23.795364', 'RPC error': '2022-09-05 02:45:04.240064'}> (decorators.py:100)
[2022-09-05T02:46:57.523Z] [2022-09-05 02:45:04 - ERROR - ci_test]: Traceback (most recent call last):
[2022-09-05T02:46:57.523Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2022-09-05T02:46:57.523Z]     res = func(*args, **_kwargs)
[2022-09-05T02:46:57.523Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2022-09-05T02:46:57.523Z]     return func(*arg, **kwargs)
[2022-09-05T02:46:57.523Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 1087, in create_index
[2022-09-05T02:46:57.523Z]     timeout=timeout, **kwargs)
[2022-09-05T02:46:57.523Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 101, in handler
[2022-09-05T02:46:57.523Z]     raise e
[2022-09-05T02:46:57.523Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 97, in handler
[2022-09-05T02:46:57.523Z]     return func(*args, **kwargs)
[2022-09-05T02:46:57.523Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 127, in handler
[2022-09-05T02:46:57.523Z]     ret = func(self, *args, **kwargs)
[2022-09-05T02:46:57.523Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 79, in handler
[2022-09-05T02:46:57.523Z]     raise e
[2022-09-05T02:46:57.523Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 50, in handler
[2022-09-05T02:46:57.523Z]     return func(self, *args, **kwargs)
[2022-09-05T02:46:57.523Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 617, in create_index
[2022-09-05T02:46:57.523Z]     timeout=timeout)
[2022-09-05T02:46:57.523Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 101, in handler
[2022-09-05T02:46:57.523Z]     raise e
[2022-09-05T02:46:57.523Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 97, in handler
[2022-09-05T02:46:57.523Z]     return func(*args, **kwargs)
[2022-09-05T02:46:57.523Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 127, in handler
[2022-09-05T02:46:57.523Z]     ret = func(self, *args, **kwargs)
[2022-09-05T02:46:57.523Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 79, in handler
[2022-09-05T02:46:57.523Z]     raise e
[2022-09-05T02:46:57.523Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 50, in handler
[2022-09-05T02:46:57.523Z]     return func(self, *args, **kwargs)
[2022-09-05T02:46:57.523Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 688, in wait_for_creating_index
[2022-09-05T02:46:57.523Z]     raise MilvusException(1, "CreateIndex Timeout")
[2022-09-05T02:46:57.523Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=CreateIndex Timeout)>
[2022-09-05T02:46:57.523Z]  (api_request.py:39)
[2022-09-05T02:46:57.523Z] [2022-09-05 02:45:04 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=CreateIndex Timeout)> (api_request.py:40)
```

### Expected Behavior

all test cases passed

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_for_release/detail/deploy_test_for_release/19/pipeline

log:
[artifacts-cluster-reinstall-19-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9486455/artifacts-cluster-reinstall-19-pytest-logs.tar.gz)
[artifacts-cluster-reinstall-19-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9486457/artifacts-cluster-reinstall-19-server-logs.tar.gz)

**Comment by zhuwenxing** [comment]
It blocked many tests, so set it as critical

**Comment by zhuwenxing** [comment]
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_for_release/detail/deploy_test_for_release/50/pipeline

The different thing is creating index timeout after the second Milvus deployment.

log:
[Uploading artifacts-cluster-upgrade-50-pytest-logs (1).tar.gz…]()
[artifacts-cluster-upgrade-50-server-logs (2).tar.gz](https://github.com/milvus-io/milvus/files/9493814/artifacts-cluster-upgrade-50-server-logs.2.tar.gz)


In the following log, you can search `pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=CreateIndex Timeout)>`, and you can find 17 items.
[qa-jenkins.milvus.io-deploy_test_for_release-50-pipeline.txt](https://github.com/milvus-io/milvus/files/9493904/qa-jenkins.milvus.io-deploy_test_for_release-50-pipeline.txt)

**Comment by zhuwenxing** [comment]
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_for_release/detail/deploy_test_for_release/51/pipeline/242/

In this job reinstallation or upgrade is skipped, but the second test is still failed with many test cases due to creating index out.
[artifacts-cluster-reinstall-51-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9494367/artifacts-cluster-reinstall-51-server-logs.tar.gz)

[artifacts-cluster-reinstall-51-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9494372/artifacts-cluster-reinstall-51-pytest-logs.tar.gz)

![image](https://user-images.githubusercontent.com/12268675/188575112-eec9d49e-ee5a-4033-882d-f2e8e3f8e379.png)
All cases failed due to creating index timeout

**Comment by bigsheeper** [comment]
indexCoord keeps trying to get free worker node, but failed because indexNode is busy excuting index bulding task and excuting  serially. While tests are run concurrentlly, timeout of 40 seconds may not be enough.@zhuwenxing

![image](https://user-images.githubusercontent.com/42060877/188586876-00cdf7f6-6829-45ed-9b88-04c37ad31855.png)

**Comment by zhuwenxing** [comment]
I have update the timeout to 100s , but there are still many cases failed
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_for_release/detail/deploy_test_for_release/52/pipeline

log:
[artifacts-cluster-reinstall-52-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9495926/artifacts-cluster-reinstall-52-server-logs.tar.gz)
[artifacts-cluster-reinstall-52-pytest-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/9495927/artifacts-cluster-reinstall-52-pytest-logs.1.tar.gz)

**Comment by bigsheeper** [comment]
There are 98 tests in test_action_first_deployment.py:
```
(milvus2) sheep@sheep:~/workspace/milvus/tests/python_client/deploy/testcases$ pytest test_action_first_deployment.py --collect-only
.....
selected 98 items
------------------------------ generated html file: file:///tmp/ci_logs/report.html ------------------------------
Results (0.05s):
```



However, currently indexCoord schedules index building tasks randomly, which means the former task would be excueted after many tasks. We should pick the former tasks to execute as soon as possible. see #19076 

There're 8 tasks for each test, each building index task costs about 10 seconds:
![image](https://user-images.githubusercontent.com/42060877/188814921-83fc146a-d5a5-4417-8923-ab2fd1a6f7c9.png)

And the concurrency of tests is `-n 6`. So after #19076 merged, the timeout should be greater than `8 * 10 * 6` seconds, I suggest to set timeout to 10 minutes @zhuwenxing

**Comment by bigsheeper** [comment]
> I have update the timeout to 100s , but there are still many cases failed failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_for_release/detail/deploy_test_for_release/52/pipeline
> 
> log: [artifacts-cluster-reinstall-52-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9495926/artifacts-cluster-reinstall-52-server-logs.tar.gz) [artifacts-cluster-reinstall-52-pytest-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/9495927/artifacts-cluster-reinstall-52-pytest-logs.1.tar.gz)


For No.52 failed job, index builds slowly (about **10seconds**)：
![image](https://user-images.githubusercontent.com/42060877/188835290-259b9f7c-f999-4bc2-95bc-823f43ad8fd2.png)

For No.62 successful job, index builds very fast (about **100ms**):
![image](https://user-images.githubusercontent.com/42060877/188835290-259b9f7c-f999-4bc2-95bc-823f43ad8fd2.png)


However, there is nearly no change about index between 1d8d919 (No.52 failed job) and a926a7d (No.62 successful job):
https://github.com/milvus-io/milvus/commits/2.1.0
![image](https://user-images.githubusercontent.com/42060877/188836254-f5474d97-7e7c-492d-909c-376587aebc88.png)


So maybe the hardware resources for these jobs are different.@zhuwenxing

**Comment by zhuwenxing** [comment]
When indexnode is in the machine that has better performance, this issue would not happen.

**Comment by zhuwenxing** [comment]
not reproduced yet, so close it
