### ISSUE TITLE
Annoy search crashed

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#1903]
**Describe the bug**
```
2020-04-11 13:44:10,704 | INFO | default | [SERVER] [search][0] Search start in gRPC server
2020-04-11 13:44:10,704 | INFO | default | [SERVER] [search][0] Search pre-execute. Check search parameters
2020-04-11 13:44:10,704 | INFO | default | [SERVER] [search][0] Search execute.
2020-04-11 13:44:10,707 | INFO | default | [SERVER] [search][0] Search done.
2020-04-11 13:44:10,717 | INFO | default | [SERVER] [search][0] Search start in gRPC server
2020-04-11 13:44:10,717 | INFO | default | [SERVER] [search][0] Search pre-execute. Check search parameters
2020-04-11 13:44:10,717 | INFO | default | [SERVER] [search][0] Search execute.
2020-04-11 13:44:10,720 | INFO | default | [SERVER] [search][0] Search done.
2020-04-11 13:44:10,731 | INFO | default | [SERVER] [search][0] Search start in gRPC server
2020-04-11 13:44:10,731 | INFO | default | [SERVER] [search][0] Search pre-execute. Check search parameters
2020-04-11 13:44:10,731 | INFO | default | [SERVER] [search][0] Search execute.
2020-04-11 13:44:10,733 | INFO | default | [SERVER] Server received critical signal: 11
2020-04-11 13:44:10,733 | INFO | default | [SERVER] Call stack:
2020-04-11 13:44:10,734 | INFO | default | [SERVER] ../bin/milvus_server(+0x24aad0) [0x55afc1227ad0]
2020-04-11 13:44:10,734 | INFO | default | [SERVER] ../bin/milvus_server(+0x24b081) [0x55afc1228081]
2020-04-11 13:44:10,734 | INFO | default | [SERVER] /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7f297a6edf20]
2020-04-11 13:44:10,734 | INFO | default | [SERVER] ../bin/milvus_server(+0x2a61cc) [0x55afc12831cc]
2020-04-11 13:44:10,734 | INFO | default | [SERVER] ../bin/milvus_server(+0x2ab638) [0x55afc1288638]
2020-04-11 13:44:10,734 | INFO | default | [SERVER] ../bin/milvus_server(+0x121793) [0x55afc10fe793]
2020-04-11 13:44:10,734 | INFO | default | [SERVER] ../bin/milvus_server(+0x10ebaa) [0x55afc10ebbaa]
2020-04-11 13:44:10,734 | INFO | default | [SERVER] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xbd6df) [0x7f297b1136df]
2020-04-11 13:44:10,734 | INFO | default | [SERVER] /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7f297b3e66db]
2020-04-11 13:44:10,734 | INFO | default | [SERVER] /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f297a7d088f]
```
**Steps/Code to reproduce behavior**
dataset: `/test/milvus/db_data_7/sift_10m_1024_128_l2_annoy_wal`, index created on 4-11
index_params: n_tree:4
search_k: 100
nq: 10
top_k: 100

```
13:44:11  2020-04-11:05:44:10,697 INFO     [runner.py:196] Start query, query params: top-k: 10, nq: 10, actually length of vectors: 10
13:44:11  2020-04-11:05:44:10,697 INFO     [runner.py:198] Start run query, run 1 of 2
13:44:11  2020-04-11:05:44:10,707 INFO     [client.py:34] Milvus query run in 0.01s
13:44:11  2020-04-11:05:44:10,707 INFO     [runner.py:198] Start run query, run 2 of 2
13:44:11  2020-04-11:05:44:10,719 INFO     [client.py:34] Milvus query run in 0.01s
13:44:11  2020-04-11:05:44:10,719 INFO     [runner.py:204] Min query time: 0.01
13:44:11  2020-04-11:05:44:10,719 INFO     [runner.py:196] Start query, query params: top-k: 100, nq: 10, actually length of vectors: 10
13:44:11  2020-04-11:05:44:10,719 INFO     [runner.py:198] Start run query, run 1 of 2
13:46:03  <_MultiThreadedRendezvous of RPC that terminated with:
13:46:03  	status = StatusCode.UNAVAILABLE
13:46:03  	details = "Socket closed"
13:46:03  	debug_error_string = "{"created":"@1586583949.451876773","description":"Error received from peer ipv4:10.44.0.1:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}"
13:46:03  >
13:46:03  2020-04-11:05:45:49,452 ERROR    [grpc_handler.py:919] <_MultiThreadedRendezvous of RPC that terminated with:
13:46:03  	status = StatusCode.UNAVAILABLE
13:46:03  	details = "Socket closed"
13:46:03  	debug_error_string = "{"created":"@1586583949.451876773","description":"Error received from peer ipv4:10.44.0.1:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}"
13:46:03  >
13:46:03  2020-04-11:05:45:49,452 ERROR    [client.py:72] Error occurred: Socket closed
13:46:03  2020-04-11:05:45:49,452 ERROR    [main.py:69] Status not ok
13:46:03  2020-04-11:05:45:49,452 ERROR    [main.py:70] Traceback (most recent call last):
13:46:03    File "main.py", line 67, in queue_worker
13:46:03      runner.run(run_type, collection)
13:46:03    File "/home/jenkins/agent/workspace/milvus-debug/milvus_benchmark/k8s_runner.py", line 239, in run
13:46:03      res = self.do_query(milvus_instance, collection_name, top_ks, nqs, run_count, search_param)
13:46:03    File "/home/jenkins/agent/workspace/milvus-debug/milvus_benchmark/runner.py", line 200, in do_query
13:46:03      query_res = milvus.query(vectors, top_k, search_param=search_param)
13:46:03    File "/home/jenkins/agent/workspace/milvus-debug/milvus_benchmark/client.py", line 32, in wrapper
13:46:03      result = func(*args, **kwargs)
13:46:03    File "/home/jenkins/agent/workspace/milvus-debug/milvus_benchmark/client.py", line 146, in query
13:46:03      self.check_status(status)
13:46:03    File "/home/jenkins/agent/workspace/milvus-debug/milvus_benchmark/client.py", line 73, in check_status
13:46:03      raise Exception("Status not ok")
13:46:03  Exception: Status not ok
```

**Expected behavior**

**Environment details**
image_info: master-cpu-ubuntu
image_id:
```
ac8f
```
config:
```
{'db_config.primary_path': '/test/milvus/db_data_7/sift_10m_1024_128_l2_annoy_wal', 'cache_config.cpu_cache_capacity': 32, 'engine_config.use_blas_threshold': 0, 'engine_config.gpu_search_threshold': 200, 'gpu_resource_config.enable': True, 'gpu_resource_config.cache_capacity': 6, 'gpu_resource_config.search_resources': ['gpu0', 'gpu1'], 'gpu_resource_config.build_index_resources': ['gpu0', 'gpu1'], 'wal_enable': True}
```

**Screenshots**

**Additional context**

**Comment by del-zhenwu** [comment]
```
13:44:11  2020-04-11:05:44:09,595 INFO     [k8s_runner.py:238] Search param: {"search_k": 100}

```

**Comment by tinkerlin** [comment]
@del-zhenwu regression test

**Comment by del-zhenwu** [comment]
fixed
