### ISSUE TITLE
[Bug]: [Diskann Index]Milvus creates a diskann index that exceeds the MaxDiskUsagePercentage setting of the disk, no error is reported

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#19041]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:xige-16-build-diskann-2-22-10-19ae79b50-20220905
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0dev23
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server-instance
fouram-jj-no-clean-96pwr-1
server-configmap
server-single-8c32m-diskann
client-configmap
client-search-sift20m-diskann-searchlist30

<img width="1440" alt="截屏2022-09-06 10 24 03" src="https://user-images.githubusercontent.com/34296482/188557131-1d0fc629-b2a1-4737-a10e-523fd584d511.png">

```
[2022-09-05 13:23:23,754] [   DEBUG] - 20000000 (milvus_benchmark.runners.search:283)
[2022-09-05 13:23:23,754] [   DEBUG] - Start build index for last file (milvus_benchmark.runners.search:285)
[2022-09-05 13:23:23,755] [    INFO] - Building index start, collection_name: sift_20m_128_l2, index_type: DISKANN, metric_type: L2 (milvus_benchmark.client:295)
[2022-09-05 13:23:23,755] [   DEBUG] - collection: sift_20m_128_l2 Index params: {'index_type': 'DISKANN', 'metric_type': 'L2', 'params': {}} (milvus_benchmark.client:304)
[2022-09-05 15:02:19,886] [   DEBUG] - Building index done, collection_name: sift_20m_128_l2, response: Status(code=0, message='') (milvus_benchmark.client:306)
[2022-09-05 15:02:19,887] [   DEBUG] - Milvus create_index run in 5936.1321s (milvus_benchmark.client:57)
[2022-09-05 15:02:19,887] [   DEBUG] - {'flush_time': 2.5135, 'build_time': 5936.1322} (milvus_benchmark.runners.search:290)
[2022-09-05 15:02:19,888] [   DEBUG] - Row count: 20000000 in collection: <sift_20m_128_l2> (milvus_benchmark.client:520)
[2022-09-05 15:02:19,888] [    INFO] - 20000000 (milvus_benchmark.runners.search:292)
[2022-09-05 15:02:19,888] [    INFO] - Start load collection (milvus_benchmark.runners.search:293)
[2022-09-05 15:22:19,999] [   ERROR] - RPC error: [wait_for_loading_collection], <MilvusException: (code=-1, message=wait for loading collection timeout)>, <Time:{'RPC start': '2022-09-05 15:02:19.946514', 'RPC error': '2022-09-05 15:22:19.999270'}> (pymilvus.decorators:100)
[2022-09-05 15:22:19,999] [   ERROR] - RPC error: [load_collection], <MilvusException: (code=-1, message=wait for loading collection timeout)>, <Time:{'RPC start': '2022-09-05 15:02:19.888852', 'RPC error': '2022-09-05 15:22:19.999855'}> (pymilvus.decorators:100)
[2022-09-05 15:22:19,999] [   ERROR] - <MilvusException: (code=-1, message=wait for loading collection timeout)> (milvus_benchmark.main:118)
[2022-09-05 15:22:20,001] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 87, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/search.py", line 295, in prepare
    self.milvus.load_collection(replica_number=replica_number, timeout=1200)
  File "/src/milvus_benchmark/client.py", line 53, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 592, in load_collection
    return self._milvus.load_collection(collection_name, **params)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/stub.py", line 195, in load_collection
    return handler.load_collection(collection_name=collection_name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 101, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 97, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 127, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 79, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 700, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 101, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 97, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 127, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 79, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 709, in wait_for_loading_collection
    return self._wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 743, in _wait_for_loading_collection
    raise MilvusException(-1, "wait for loading collection timeout")
pymilvus.exceptions.MilvusException: <MilvusException: (code=-1, message=wait for loading collection timeout)>
 (milvus_benchmark.main:119)
```

### Expected Behavior

Exceeding the MaxDiskUsagePercentage of the disk should return a failure to build the index or an indication that the disk is undersized

### Steps To Reproduce

```markdown
1. Create a collection
2. build diskann index
3. insert 20m data
4. build index again, At this point the indexnode should exceed the resource limit of the disk and an error should be reported
```

### Anything else?

```
{
	"config.yaml": "server:
		  server_tag: \"8c32m\"
		milvus:
		  deploy_mode: \"single\"
		server_resource:
		  standalone:
		    resources:
		        limits:
		          ephemeral-storage: 10Gi
		    disk:
		      enabled: true
		      size:
		        enabled: true
		  common:
		    compaction: 
		      retentionDuration: 0
		"
}
```

**Comment by jingkl** [comment]
server-instance
fouram-test-no-clean-qmd2b-1
server-configmap
server-cluster-2c8m-diskann-limit
client-configmap
client-search-sift10m-diskann-searchlist


image:master-20221020-36accde0

```
fouram-test-no-clean-qmd2b-1-etcd-0                               1/1     Running                  0               13h     10.104.1.39    4am-node10   <none>           <none>
fouram-test-no-clean-qmd2b-1-etcd-1                               1/1     Running                  0               13h     10.104.6.75    4am-node13   <none>           <none>
fouram-test-no-clean-qmd2b-1-etcd-2                               1/1     Running                  0               13h     10.104.4.147   4am-node11   <none>           <none>
fouram-test-no-clean-qmd2b-1-milvus-datacoord-564474-7kw7m        1/1     Running                  0               13h     10.104.4.139   4am-node11   <none>           <none>
fouram-test-no-clean-qmd2b-1-milvus-datanode-68679d95d7-g4lvb     1/1     Running                  0               13h     10.104.6.65    4am-node13   <none>           <none>
fouram-test-no-clean-qmd2b-1-milvus-indexcoord-86c86c46f5-f2lqg   1/1     Running                  0               13h     10.104.1.34    4am-node10   <none>           <none>
fouram-test-no-clean-qmd2b-1-milvus-indexnode-6d994c9d6f-2j4jg    0/1     Error                    1 (10h ago)     10h     10.104.1.100   4am-node10   <none>           <none>
fouram-test-no-clean-qmd2b-1-milvus-indexnode-6d994c9d6f-4khk9    1/1     Running                  5 (33m ago)     37m     10.104.1.123   4am-node10   <none>           <none>
fouram-test-no-clean-qmd2b-1-milvus-indexnode-6d994c9d6f-59xvk    0/1     Error                    4 (3h41m ago)   3h43m   10.104.6.165   4am-node13   <none>           <none>
fouram-test-no-clean-qmd2b-1-milvus-indexnode-6d994c9d6f-6hgpc    0/1     Error                    0               92m     10.104.1.122   4am-node10   <none>           <none>
fouram-test-no-clean-qmd2b-1-milvus-indexnode-6d994c9d6f-7dc8w    0/1     Error                    0               7h31m   10.104.6.159   4am-node13   <none>           <none>
fouram-test-no-clean-qmd2b-1-milvus-indexnode-6d994c9d6f-7tds4    0/1     Error                    0               9h      10.104.1.106   4am-node10   <none>           <none>
fouram-test-no-clean-qmd2b-1-milvus-indexnode-6d994c9d6f-9hgbl    0/1     Error                    1               4h42m   10.104.6.163   4am-node13   <none>           <none>
fouram-test-no-clean-qmd2b-1-milvus-indexnode-6d994c9d6f-clpb9    0/1     Error                    1 (12h ago)     12h     10.104.5.134   4am-node12   <none>           <none>
fouram-test-no-clean-qmd2b-1-milvus-indexnode-6d994c9d6f-h572c    0/1     Error                    4 (12h ago)     12h     10.104.1.49    4am-node10   <none>           <none>
fouram-test-no-clean-qmd2b-1-milvus-indexnode-6d994c9d6f-lv2n8    0/1     Error                    4 (6h29m ago)   6h31m   10.104.6.160   4am-node13   <none>           <none>
fouram-test-no-clean-qmd2b-1-milvus-indexnode-6d994c9d6f-ngx78    0/1     ContainerStatusUnknown   2 (5h36m ago)   5h37m   10.104.6.162   4am-node13   <none>           <none>
fouram-test-no-clean-qmd2b-1-milvus-indexnode-6d994c9d6f-nx4h9    0/1     Error                    2               4h14m   10.104.6.164   4am-node13   <none>           <none>
fouram-test-no-clean-qmd2b-1-milvus-indexnode-6d994c9d6f-qdcxs    0/1     Error                    4               11h     10.104.6.94    4am-node13   <none>           <none>
fouram-test-no-clean-qmd2b-1-milvus-indexnode-6d994c9d6f-s9j9z    0/1     Error                    2 (8h ago)      8h      10.104.1.107   4am-node10   <none>           <none>
fouram-test-no-clean-qmd2b-1-milvus-indexnode-6d994c9d6f-sxj28    0/1     Error                    0               3h19m   10.104.6.166   4am-node13   <none>           <none>
fouram-test-no-clean-qmd2b-1-milvus-indexnode-6d994c9d6f-t7nfd    0/1     ContainerStatusUnknown   1 (13h ago)     13h     10.104.1.31    4am-node10   <none>           <none>
fouram-test-no-clean-qmd2b-1-milvus-indexnode-6d994c9d6f-v6ksl    0/1     ContainerStatusUnknown   2 (11h ago)     11h     10.104.6.95    4am-node13   <none>           <none>
fouram-test-no-clean-qmd2b-1-milvus-indexnode-6d994c9d6f-vn48q    0/1     Error                    4               6h7m    10.104.6.161   4am-node13   <none>           <none>
fouram-test-no-clean-qmd2b-1-milvus-indexnode-6d994c9d6f-whhsh    0/1     ContainerStatusUnknown   1               147m    <none>         4am-node10   <none>           <none>
fouram-test-no-clean-qmd2b-1-milvus-indexnode-6d994c9d6f-xhr6j    0/1     Error                    2               11h     10.104.6.92    4am-node13   <none>           <none>
fouram-test-no-clean-qmd2b-1-milvus-proxy-779467fc7f-djp6t        1/1     Running                  0               13h     10.104.4.138   4am-node11   <none>           <none>
fouram-test-no-clean-qmd2b-1-milvus-querycoord-7c776f6b4d-742mk   1/1     Running                  0               13h     10.104.6.69    4am-node13   <none>           <none>
fouram-test-no-clean-qmd2b-1-milvus-querynode-646f856cdc-xgxzc    1/1     Running                  6 (12h ago)     13h     10.104.4.136   4am-node11   <none>           <none>
fouram-test-no-clean-qmd2b-1-milvus-rootcoord-5889cd598d-qwlsf    1/1     Running                  0               13h     10.104.6.66    4am-node13   <none>           <none>
fouram-test-no-clean-qmd2b-1-minio-0                              1/1     Running                  0               13h     10.104.4.145   4am-node11   <none>           <none>
fouram-test-no-clean-qmd2b-1-minio-1                              1/1     Running                  0               13h     10.104.6.71    4am-node13   <none>           <none>
fouram-test-no-clean-qmd2b-1-minio-2                              1/1     Running                  0               13h     10.104.1.41    4am-node10   <none>           <none>
fouram-test-no-clean-qmd2b-1-minio-3                              1/1     Running                  0               13h     10.104.5.129   4am-node12   <none>           <none>
fouram-test-no-clean-qmd2b-1-pulsar-bookie-0                      1/1     Running                  0               13h     10.104.4.143   4am-node11   <none>           <none>
fouram-test-no-clean-qmd2b-1-pulsar-bookie-1                      1/1     Running                  0               13h     10.104.1.40    4am-node10   <none>           <none>
fouram-test-no-clean-qmd2b-1-pulsar-bookie-2                      1/1     Running                  0               13h     10.104.6.76    4am-node13   <none>           <none>
fouram-test-no-clean-qmd2b-1-pulsar-bookie-init-drxmn             0/1     Completed                0               13h     10.104.1.33    4am-node10   <none>           <none>
fouram-test-no-clean-qmd2b-1-pulsar-broker-0                      1/1     Running                  0               13h     10.104.6.68    4am-node13   <none>           <none>
fouram-test-no-clean-qmd2b-1-pulsar-proxy-0                       1/1     Running                  0               13h     10.104.6.67    4am-node13   <none>           <none>
fouram-test-no-clean-qmd2b-1-pulsar-pulsar-init-prcmg             0/1     Completed                0               13h     10.104.1.32    4am-node10   <none>           <none>
fouram-test-no-clean-qmd2b-1-pulsar-recovery-0                    1/1     Running                  0               13h     10.104.4.137   4am-node11   <none>           <none>
fouram-test-no-clean-qmd2b-1-pulsar-zookeeper-0                   1/1     Running                  0               13h     10.104.5.127   4am-node12   <none>           <none>
fouram-test-no-clean-qmd2b-1-pulsar-zookeeper-1                   1/1     Running                  0               13h     10.104.1.43    4am-node10   <none>           <none>
fouram-test-no-clean-qmd2b-1-pulsar-zookeeper-2                   1/1     Running                  0               13h     10.104.4.149   4am-node11   <none>           <none>
```

```
[2022-10-20 13:32:03,468] [    INFO] - Start load collection (milvus_benchmark.runners.search:293)
[2022-10-20 13:42:30,412] [   ERROR] - RPC error: [get_loading_progress], <MilvusException: (code=1, message=collection 436803118641971204 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-10-20 13:42:30.410387', 'RPC error': '2022-10-20 13:42:30.412576'}> (pymilvus.decorators:112)
[2022-10-20 13:42:30,413] [   ERROR] - RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=collection 436803118641971204 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-10-20 13:32:03.486398', 'RPC error': '2022-10-20 13:42:30.413506'}> (pymilvus.decorators:112)
[2022-10-20 13:42:30,413] [   ERROR] - RPC error: [load_collection], <MilvusException: (code=1, message=collection 436803118641971204 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-10-20 13:32:03.468198', 'RPC error': '2022-10-20 13:42:30.413604'}> (pymilvus.decorators:112)
[2022-10-20 13:42:30,413] [   ERROR] - <MilvusException: (code=1, message=collection 436803118641971204 has not been loaded to memory or load failed)> (milvus_benchmark.main:118)
[2022-10-20 13:42:30,421] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 87, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/search.py", line 295, in prepare
    self.milvus.load_collection(replica_number=replica_number, timeout=1200)
  File "/src/milvus_benchmark/client.py", line 53, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 592, in load_collection
    return self._milvus.load_collection(collection_name, **params)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/stub.py", line 195, in load_collection
    return handler.load_collection(collection_name=collection_name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 113, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 139, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 89, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 665, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 113, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 139, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 89, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 683, in wait_for_loading_collection
    progress = self.get_loading_progress(collection_name, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 113, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 139, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 89, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 744, in get_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection 436803118641971204 has not been loaded to memory or load failed)>
 (milvus_benchmark.main:119)
```

server config:

```
data:
  config.yaml: |
    server:
      server_tag: "2c8m"
    milvus:
      deploy_mode: "cluster"
    server_resource:
      indexNode:
        resources:
          limits:
            ephemeral-storage: 100Gi
        disk:
          enabled: true
          size:
            enabled: true
      queryNode:
        resources:
          limits:
            ephemeral-storage: 5Gi
        disk:
          enabled: true
          size:
            enabled: true
      queryCoordinator:
        taskMergeCap: 2
```

**Comment by xige-16** [comment]
@jingkl  please verify
/assign @jingkl

**Comment by jingkl** [comment]
server-instance
fouram-tag-no-clean-xpr5l-1
server-configmap
server-cluster-2c8m-diskann-limit
client-configmap
client-search-sift10m-diskann-searchlist

master-20221026-b213297d
2.2.0.dev63

```
fouram-tag-no-clean-vq45f-1-etcd-0                                1/1     Running                  0              13h     [10.104.9.235](http://10.104.9.235/)   4am-node14   <none>           <none>
fouram-tag-no-clean-vq45f-1-milvus-standalone-7c9c975786-qhljl    1/1     Running                  2 (12h ago)    12h     [10.104.9.38](http://10.104.9.38/)    4am-node14   <none>           <none>
fouram-tag-no-clean-vq45f-1-minio-5cbb69b49d-9cnfb                1/1     Running                  0              13h     [10.104.9.234](http://10.104.9.234/)   4am-node14   <none>           <none>
fouram-tag-no-clean-xpr5l-1-etcd-0                                1/1     Running                  0              11h     [10.104.9.69](http://10.104.9.69/)    4am-node14   <none>           <none>
fouram-tag-no-clean-xpr5l-1-etcd-1                                1/1     Running                  0              11h     [10.104.6.158](http://10.104.6.158/)   4am-node13   <none>           <none>
fouram-tag-no-clean-xpr5l-1-etcd-2                                1/1     Running                  0              11h     [10.104.1.8](http://10.104.1.8/)     4am-node10   <none>           <none>
fouram-tag-no-clean-xpr5l-1-milvus-datacoord-559fc6fb79-cqclv     1/1     Running                  0              11h     [10.104.5.194](http://10.104.5.194/)   4am-node12   <none>           <none>
fouram-tag-no-clean-xpr5l-1-milvus-datanode-989c9b785-tlkqr       1/1     Running                  0              11h     [10.104.5.195](http://10.104.5.195/)   4am-node12   <none>           <none>
fouram-tag-no-clean-xpr5l-1-milvus-indexcoord-64b9b8c847-5hxbq    1/1     Running                  0              11h     [10.104.5.197](http://10.104.5.197/)   4am-node12   <none>           <none>
fouram-tag-no-clean-xpr5l-1-milvus-indexnode-79d4998c95-chthd     1/1     Running                  2 (6h4m ago)   11h     [10.104.5.198](http://10.104.5.198/)   4am-node12   <none>           <none>
fouram-tag-no-clean-xpr5l-1-milvus-proxy-586b44bd5-k2zn2          1/1     Running                  0              11h     [10.104.5.192](http://10.104.5.192/)   4am-node12   <none>           <none>
fouram-tag-no-clean-xpr5l-1-milvus-querycoord-5884fdd788-kgnqv    1/1     Running                  0              11h     [10.104.5.193](http://10.104.5.193/)   4am-node12   <none>           <none>
fouram-tag-no-clean-xpr5l-1-milvus-querynode-7cfc6bd77c-f6q44     0/1     Error                    3 (9h ago)     11h     [10.104.9.57](http://10.104.9.57/)    4am-node14   <none>           <none>
fouram-tag-no-clean-xpr5l-1-milvus-querynode-7cfc6bd77c-rh472     0/1     ContainerStatusUnknown   3 (8h ago)     8h      [10.104.9.170](http://10.104.9.170/)   4am-node14   <none>           <none>
fouram-tag-no-clean-xpr5l-1-milvus-querynode-7cfc6bd77c-xrvxz     1/1     Running                  0              8h      [10.104.4.65](http://10.104.4.65/)    4am-node11   <none>           <none>
fouram-tag-no-clean-xpr5l-1-milvus-rootcoord-568744d45b-v9fw6     1/1     Running                  0              11h     [10.104.5.196](http://10.104.5.196/)   4am-node12   <none>           <none>
fouram-tag-no-clean-xpr5l-1-minio-0                               1/1     Running                  0              11h     [10.104.9.66](http://10.104.9.66/)    4am-node14   <none>           <none>
fouram-tag-no-clean-xpr5l-1-minio-1                               1/1     Running                  0              11h     [10.104.6.160](http://10.104.6.160/)   4am-node13   <none>           <none>
fouram-tag-no-clean-xpr5l-1-minio-2                               1/1     Running                  0              11h     [10.104.1.10](http://10.104.1.10/)    4am-node10   <none>           <none>
fouram-tag-no-clean-xpr5l-1-minio-3                               1/1     Running                  0              11h     [10.104.5.200](http://10.104.5.200/)   4am-node12   <none>           <none>
fouram-tag-no-clean-xpr5l-1-pulsar-bookie-0                       1/1     Running                  0              11h     [10.104.6.162](http://10.104.6.162/)   4am-node13   <none>           <none>
fouram-tag-no-clean-xpr5l-1-pulsar-bookie-1                       1/1     Running                  0              11h     [10.104.9.74](http://10.104.9.74/)    4am-node14   <none>           <none>
fouram-tag-no-clean-xpr5l-1-pulsar-bookie-2                       1/1     Running                  0              11h     [10.104.1.13](http://10.104.1.13/)    4am-node10   <none>           <none>
fouram-tag-no-clean-xpr5l-1-pulsar-bookie-init-9jjqd              0/1     Completed                0              11h     [10.104.9.56](http://10.104.9.56/)    4am-node14   <none>           <none>
fouram-tag-no-clean-xpr5l-1-pulsar-broker-0                       1/1     Running                  0              11h     [10.104.6.154](http://10.104.6.154/)   4am-node13   <none>           <none>
fouram-tag-no-clean-xpr5l-1-pulsar-proxy-0                        1/1     Running                  0              11h     [10.104.6.155](http://10.104.6.155/)   4am-node13   <none>           <none>
fouram-tag-no-clean-xpr5l-1-pulsar-pulsar-init-7qjm7              0/1     Completed                0              11h     [10.104.9.58](http://10.104.9.58/)    4am-node14   <none>           <none>
fouram-tag-no-clean-xpr5l-1-pulsar-recovery-0                     1/1     Running                  0              11h     [10.104.9.59](http://10.104.9.59/)    4am-node14   <none>           <none>
fouram-tag-no-clean-xpr5l-1-pulsar-zookeeper-0                    1/1     Running                  0              11h     [10.104.9.65](http://10.104.9.65/)    4am-node14   <none>           <none>
fouram-tag-no-clean-xpr5l-1-pulsar-zookeeper-1                    1/1     Running                  0              11h     [10.104.5.202](http://10.104.5.202/)   4am-node12   <none>           <none>
fouram-tag-no-clean-xpr5l-1-pulsar-zookeeper-2                    1/1     Running                  0              11h     [10.104.1.21](http://10.104.1.21/)    4am-node10   <none>           <none>
```

```

[2022-10-26 16:50:24,992] [    INFO] - 10000000 (milvus_benchmark.runners.search:292)
[2022-10-26 16:50:24,992] [    INFO] - Start load collection (milvus_benchmark.runners.search:293)
[2022-10-26 17:09:12,909] [   ERROR] - RPC error: [get_loading_progress], <MilvusException: (code=1, message=collection 436939751384678403 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-10-26 17:09:12.907170', 'RPC error': '2022-10-26 17:09:12.908906'}> (pymilvus.decorators:108)
[2022-10-26 17:09:12,909] [   ERROR] - RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=collection 436939751384678403 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-10-26 16:50:25.010022', 'RPC error': '2022-10-26 17:09:12.909524'}> (pymilvus.decorators:108)
[2022-10-26 17:09:12,909] [   ERROR] - RPC error: [load_collection], <MilvusException: (code=1, message=collection 436939751384678403 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-10-26 16:50:24.992150', 'RPC error': '2022-10-26 17:09:12.909621'}> (pymilvus.decorators:108)
[2022-10-26 17:09:12,909] [   ERROR] - <MilvusException: (code=1, message=collection 436939751384678403 has not been loaded to memory or load failed)> (milvus_benchmark.main:118)
[2022-10-26 17:09:12,912] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 87, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/search.py", line 295, in prepare
    self.milvus.load_collection(replica_number=replica_number, timeout=1200)
  File "/src/milvus_benchmark/client.py", line 53, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 592, in load_collection
    return self._milvus.load_collection(collection_name, **params)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/stub.py", line 193, in load_collection
    return handler.load_collection(collection_name, replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 651, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 669, in wait_for_loading_collection
    progress = self.get_loading_progress(collection_name, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 730, in get_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection 436939751384678403 has not been loaded to memory or load failed)>
 (milvus_benchmark.main:119)
```

**Comment by jingkl** [comment]
querynode this will be kill phenomenon, not as expected @xige-16

**Comment by xige-16** [comment]
> querynode this will be kill phenomenon, not as expected @xige-16

![nldqXThZ9p](https://user-images.githubusercontent.com/20124155/200728298-dd3dfe3e-9def-4a95-8328-fb5e48adf622.png)

parrael append disk index err， has been fix by https://github.com/milvus-io/milvus/pull/20200

**Comment by xige-16** [comment]
@jingkl  please verify again, Thx

**Comment by czs007** [comment]
@jingkl can this be closed ?
