### ISSUE TITLE
[Bug]: Field name can only contain numbers, letters, and underscore

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#19053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220906-8dce723
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0.dev26
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When creating  a field name containing numbers, letters, dollar signs ($), and underscores (_),for example '_1nt$', error occurs.
```
[2022-09-06 15:58:29 - ERROR - pymilvus.client.grpc_handler]: error_code: UnexpectedError
reason: "Invalid field name: _1nt$. Field name cannot only contain numbers, letters, and underscores."
 (grpc_handler.py:218)
[2022-09-06 15:58:29 - ERROR - pymilvus.decorators]: RPC error: [create_collection], <MilvusException: (code=1, message=Invalid field name: _1nt$. Field name cannot only contain numbers, letters, and underscores.)>, <Time:{'RPC start': '2022-09-06 15:58:29.129205', 'RPC error': '2022-09-06 15:58:29.152901'}> (decorators.py:100)
[2022-09-06 15:58:29 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/zilliz/nico/milvus/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/Users/zilliz/nico/milvus/tests/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/Users/zilliz/virtual-environment/test2/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 139, in __init__
    conn.create_collection(self._name, fields=schema.to_dict(), shards_num=self._shards_num,
  File "/Users/zilliz/virtual-environment/test2/lib/python3.8/site-packages/pymilvus/decorators.py", line 101, in handler
    raise e
  File "/Users/zilliz/virtual-environment/test2/lib/python3.8/site-packages/pymilvus/decorators.py", line 97, in handler
    return func(*args, **kwargs)
  File "/Users/zilliz/virtual-environment/test2/lib/python3.8/site-packages/pymilvus/decorators.py", line 127, in handler
    ret = func(self, *args, **kwargs)
  File "/Users/zilliz/virtual-environment/test2/lib/python3.8/site-packages/pymilvus/decorators.py", line 79, in handler
    raise e
  File "/Users/zilliz/virtual-environment/test2/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/virtual-environment/test2/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 219, in create_collection
    raise MilvusException(status.error_code, status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Invalid field name: _1nt$. Field name cannot only contain numbers, letters, and underscores.)>
 (api_request.py:39)
[2022-09-06 15:58:29 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Invalid field name: _1nt$. Field name cannot only contain numbers, letters, and underscores.)> (api_request.py:40)
```

### Expected Behavior

There shouldn't be an error because of the rules mentioned on this web page: https://milvus.io/docs/v2.1.x/limitations.md#Naming-rules .
"The name of a resource can contain numbers, letters, dollar signs ($), and underscores (_). A resource name must start with a letter or an underscore (_)."
Or the document should be modified.

### Steps To Reproduce

```python
    @pytest.mark.tags(CaseLabel.L2)
    @pytest.mark.parametrize("name", ["_co11ection$","co11_$uper"])
    def test_collection_naming_rules(self, name):
        """
        target: test collection with valid name
        method: 1. connect milvus
                2. Create a field with a name which uses all the supported elements in the naming rules
                3. Create a collection with a name which uses all the supported elements in the naming rules
        expected: Collection created successfully
        """
        self._connect()
        fields = [cf.gen_int64_field(), cf.gen_int64_field("_1nt$"), cf.gen_float_vec_field("f10at_$")]
        schema = cf.gen_collection_schema(fields=fields, primary_field=ct.default_int64_field_name)
        self.collection_wrap.init_collection(name, schema=schema,
                                             check_task=CheckTasks.check_collection_property,
                                             check_items={exp_name: name, exp_schema: schema})
```

### Milvus Log

[test.log](https://github.com/milvus-io/milvus/files/9494813/test.log)

**Comment by yanliang567** [comment]
@NicoYuan1986 I think this is a design change, $ is not supported in collection name, as well as partition name. Please update the testcase accordingly. 

@YiyunNi could you please help to update the related documents?

**Comment by YiyunNi** [comment]
The doc has already been updated with this [PR](https://github.com/milvus-io/milvus-docs/pull/1799). Please check the latest version here https://milvus.io/docs/v2.1.x/limitations.md.

**Comment by NicoYuan1986** [comment]
The testcases have been changed accordingly.
