### ISSUE TITLE
[Bug]: [Nightly]Search timeout reporting "new session error, maybe can not connect to etcd"

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#19068]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.*(7affd939)
- Deployment mode(standalone or cluster):cluster(kafka)
- SDK version(e.g. pymilvus v2.0.0rc2):2.1.2.dev2
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When test collection after drop, error occurs.
```
[2022-09-06T21:19:37.319Z] [2022-09-06 20:25:11 - ERROR - pymilvus.decorators]: RPC error: [drop_collection], <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
[2022-09-06T21:19:37.319Z] 	status = StatusCode.DEADLINE_EXCEEDED
[2022-09-06T21:19:37.319Z] 	details = "Deadline Exceeded"
[2022-09-06T21:19:37.319Z] 	debug_error_string = "UNKNOWN:Deadline Exceeded {created_time:"2022-09-06T20:25:11.397927901+00:00", grpc_status:4}"
[2022-09-06T21:19:37.319Z] >)>, <Time:{'RPC start': '2022-09-06 20:24:51.397644', 'RPC error': '2022-09-06 20:25:11.398394'}> (decorators.py:95)
[2022-09-06T21:19:37.319Z] [2022-09-06 20:25:11 - ERROR - ci_test]: Traceback (most recent call last):
[2022-09-06T21:19:37.319Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 48, in handler
[2022-09-06T21:19:37.319Z]     return func(self, *args, **kwargs)
[2022-09-06T21:19:37.319Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 205, in drop_collection
[2022-09-06T21:19:37.319Z]     status = rf.result()
[2022-09-06T21:19:37.319Z]   File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 744, in result
[2022-09-06T21:19:37.319Z]     raise self
[2022-09-06T21:19:37.319Z] grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
[2022-09-06T21:19:37.319Z] 	status = StatusCode.DEADLINE_EXCEEDED
[2022-09-06T21:19:37.319Z] 	details = "Deadline Exceeded"
[2022-09-06T21:19:37.319Z] 	debug_error_string = "UNKNOWN:Deadline Exceeded {created_time:"2022-09-06T20:25:11.397927901+00:00", grpc_status:4}"
[2022-09-06T21:19:37.319Z] >
[2022-09-06T21:19:37.319Z] 
[2022-09-06T21:19:37.319Z] During handling of the above exception, another exception occurred:
[2022-09-06T21:19:37.319Z] 
[2022-09-06T21:19:37.319Z] Traceback (most recent call last):
[2022-09-06T21:19:37.319Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
[2022-09-06T21:19:37.319Z]     res = func(*args, **kwargs)
[2022-09-06T21:19:37.319Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 56, in api_request
[2022-09-06T21:19:37.319Z]     return func(*arg, **kwargs)
[2022-09-06T21:19:37.319Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 435, in drop
[2022-09-06T21:19:37.319Z]     conn.drop_collection(self._name, timeout=timeout, **kwargs)
[2022-09-06T21:19:37.319Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 96, in handler
[2022-09-06T21:19:37.319Z]     raise e
[2022-09-06T21:19:37.319Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 92, in handler
[2022-09-06T21:19:37.319Z]     return func(*args, **kwargs)
[2022-09-06T21:19:37.319Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 56, in handler
[2022-09-06T21:19:37.319Z]     raise MilvusException(Status.UNEXPECTED_ERROR, str(e))
[2022-09-06T21:19:37.319Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
[2022-09-06T21:19:37.319Z] 	status = StatusCode.DEADLINE_EXCEEDED
[2022-09-06T21:19:37.319Z] 	details = "Deadline Exceeded"
[2022-09-06T21:19:37.319Z] 	debug_error_string = "UNKNOWN:Deadline Exceeded {created_time:"2022-09-06T20:25:11.397927901+00:00", grpc_status:4}"
[2022-09-06T21:19:37.319Z] >)>
[2022-09-06T21:19:37.319Z]  (api_request.py:35)
[2022-09-06T21:19:37.319Z] [2022-09-06 20:25:11 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
[2022-09-06T21:19:37.319Z] 	status = StatusCode.DEADLINE_EXCEEDED
[2022-09-06T21:19:37.319Z] 	details = "Deadline Exceeded"
[2022-09-06T21:19:37.319Z] 	debug_error_string = "UNKNOWN:Deadline Exceeded {created_time:"2022-09-06T20:25:11.397927901+00:00", grpc_status:4}"
[2022-09-06T21:19:37.319Z] >)> (api_request.py:36)
```

### Expected Behavior

PASSED

### Steps To Reproduce

```markdown
nightly:
https://jenkins.milvus.io:18080/blue/organizations/jenkins/qa%2Fmilvus-release-nightly/detail/milvus-release-nightly/84/pipeline/193
```

### Milvus Log

1. log: [milvus-distributed-kafka-84-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/qa/job/milvus-release-nightly/84/artifact/milvus-distributed-kafka-84-pymilvus-e2e-logs.tar.gz)
2. collection name: collection_bNn4gA3F
3. failed time:[2022-09-06T20:25:31.720Z] [gw5] [  6%] FAILED testcases/test_collection.py::TestCollectionOperation::test_collection_after_drop 
4. error message:
```
2022-09-07T04:20:19.20463164+08:00 stderr F panic: new session error, maybe can not connect to etcd
2022-09-07T04:20:19.204650424+08:00 stderr F
2022-09-07T04:20:19.204656778+08:00 stderr F goroutine 31 [running]:
2022-09-07T04:20:19.204660957+08:00 stderr F github.com/milvus-io/milvus/internal/distributed/datanode.(*Server).init(0xc000cdd5e0, 0x8bdf3e, 0xc000f0c498)
2022-09-07T04:20:19.204664617+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/distributed/datanode/service.go:252 +0x204b
2022-09-07T04:20:19.204668057+08:00 stderr F github.com/milvus-io/milvus/internal/distributed/datanode.(*Server).Run(0xc000cdd5e0, 0x0, 0x0)
2022-09-07T04:20:19.204678105+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/distributed/datanode/service.go:166 +0x2f
2022-09-07T04:20:19.204682733+08:00 stderr F github.com/milvus-io/milvus/cmd/components.(*DataNode).Run(0xc0006ba990, 0xffffffffffffffff, 0x8)
2022-09-07T04:20:19.20468665+08:00 stderr F     /go/src/github.com/milvus-io/milvus/cmd/components/data_node.go:50 +0x33
2022-09-07T04:20:19.204698782+08:00 stderr F github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runDataNode.func1(0x0, 0x0, 0x40bf500, 0x43b0030, 0xc000ce6d00, 0xc000cf40a8, 0xc000f0c3e0, 0xc000f0c490)
2022-09-07T04:20:19.204703339+08:00 stderr F    /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:283 +0x165
2022-09-07T04:20:19.204707113+08:00 stderr F created by github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runDataNode
2022-09-07T04:20:19.204710744+08:00 stderr F    /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:264 +0xda
```

**Comment by NicoYuan1986** [comment]
Same with #17750
