### ISSUE TITLE
[Bug]: Milvus crashed with error "connection error: desc = transport: Error while dialing dial tcp: xxx"

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#19085]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:32fa677
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0.dev26
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When i pull requests, an error occurs:
```
[2022-09-07T09:49:47.703Z] [2022-09-07 09:49:42 - ERROR - ci_test]: Traceback (most recent call last):
[2022-09-07T09:49:47.703Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 121, in _wait_for_channel_ready
[2022-09-07T09:49:47.703Z]     grpc.channel_ready_future(self._channel).result(timeout=3)
[2022-09-07T09:49:47.703Z]   File "/usr/local/lib/python3.6/site-packages/grpc/_utilities.py", line 139, in result
[2022-09-07T09:49:47.703Z]     self._block(timeout)
[2022-09-07T09:49:47.703Z]   File "/usr/local/lib/python3.6/site-packages/grpc/_utilities.py", line 85, in _block
[2022-09-07T09:49:47.703Z]     raise grpc.FutureTimeoutError()
[2022-09-07T09:49:47.703Z] grpc.FutureTimeoutError
[2022-09-07T09:49:47.703Z] 
[2022-09-07T09:49:47.703Z] During handling of the above exception, another exception occurred:
[2022-09-07T09:49:47.703Z] 
[2022-09-07T09:49:47.703Z] Traceback (most recent call last):
[2022-09-07T09:49:47.703Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2022-09-07T09:49:47.703Z]     res = func(*args, **_kwargs)
[2022-09-07T09:49:47.703Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2022-09-07T09:49:47.703Z]     return func(*arg, **kwargs)
[2022-09-07T09:49:47.703Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/connections.py", line 300, in connect
[2022-09-07T09:49:47.703Z]     connect_milvus(**kwargs, password=password)
[2022-09-07T09:49:47.703Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/connections.py", line 271, in connect_milvus
[2022-09-07T09:49:47.703Z]     gh._wait_for_channel_ready()
[2022-09-07T09:49:47.703Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 124, in _wait_for_channel_ready
[2022-09-07T09:49:47.703Z]     raise MilvusException(Status.CONNECT_FAILED, f'Fail connecting to server on {self._address}. Timeout')
[2022-09-07T09:49:47.703Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on ms-19051-4-pr-milvus.milvus-ci:19530. Timeout)>
[2022-09-07T09:49:47.703Z]  (api_request.py:39)
[2022-09-07T09:49:47.703Z] [2022-09-07 09:49:42 - ERROR - ci_test]: (api_response) : <MilvusException: (code=2, message=Fail connecting to server on ms-19051-4-pr-milvus.milvus-ci:19530. Timeout)> (api_request.py:40)
```

### Expected Behavior

PASSED

### Steps To Reproduce

```markdown
Detailed Log: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-19051/4/pipeline/107/
```

### Milvus Log

1. milvus log: [artifacts-milvus-standalone-PR-19051-4-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20HA%20CI/job/PR-19051/4/artifact/artifacts-milvus-standalone-PR-19051-4-pymilvus-e2e-logs.tar.gz)
2. error message:
```
2022-09-07T17:50:04.520713842+08:00 stdout F [2022/09/07 09:50:04.520 +00:00] [ERROR] [querynode/shard_segment_detector.go:132] ["failed to handle watch segment error, panic"] [error="rpc error: code = Canceled desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp: lookup ms-19051-4-pr-etcd on 10.255.0.10:53: server misbehaving\""] [stack="github.com/milvus-io/milvus/internal/querynode.(*etcdShardSegmentDetector).watch\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/shard_segment_detector.go:132"]
2022-09-07T17:50:04.52394053+08:00 stderr F panic: rpc error: code = Canceled desc = latest balancer error: last connection error: connection error: desc = "transport: Error while dialing dial tcp: lookup ms-19051-4-pr-etcd on 10.255.0.10:53: server misbehaving"
2022-09-07T17:50:04.523964776+08:00 stderr F
2022-09-07T17:50:04.523971103+08:00 stderr F goroutine 1136858 [running]:
2022-09-07T17:50:04.52398437+08:00 stderr F github.com/milvus-io/milvus/internal/querynode.(*etcdShardSegmentDetector).watch(0xc0096f9db0, 0xc022b212c0, 0x60c5d10e77be576, 0x60c5d10ea540ac6, {0xc00aa8a2d0, 0x2d})
2022-09-07T17:50:04.523996628+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/querynode/shard_segment_detector.go:133 +0x69d
2022-09-07T17:50:04.524002382+08:00 stderr F created by github.com/milvus-io/milvus/internal/querynode.(*etcdShardSegmentDetector).watchSegments
2022-09-07T17:50:04.524009859+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/querynode/shard_segment_detector.go:108 +0x8cc
```
more details: 
ci.var.log.containers.ms-19051-4-pr-milvus-standalone-7cbcd69f4f-5wsd8_milvus-ci_standalone-f3e52d0bd62b944b3cb120c0b8b58babd790e0cb25bc83b04a0b96b2c04a0f3b.log:2022-09-07T17:50:04.520713842+08:00 stdout F [2022/09/07 09:50:04.520 +00:00] [ERROR] [querynode/shard_segment_detector.go:132] ["failed to handle watch segment error, panic"] [error="rpc error: code = Canceled desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp: lookup ms-19051-4-pr-etcd on 10.255.0.10:53: server misbehaving\""] [stack="github.com/milvus-io/milvus/internal/querynode.(*etcdShardSegmentDetector).watch\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/shard_segment_detector.go:132"]
ci.var.log.containers.ms-19051-4-pr-milvus-standalone-7cbcd69f4f-5wsd8_milvus-ci_standalone-f3e52d0bd62b944b3cb120c0b8b58babd790e0cb25bc83b04a0b96b2c04a0f3b.log:2022-09-07T17:50:04.52394053+08:00 stderr F panic: rpc error: code = Canceled desc = latest balancer error: last connection error: connection error: desc = "transport: Error while dialing dial tcp: lookup ms-19051-4-pr-etcd on 10.255.0.10:53: server misbehaving"

**Comment by msaoudallah** [comment]
@NicoYuan1986 , have you found any solution ?

**Comment by NicoYuan1986** [comment]
> @NicoYuan1986 , have you found any solution ?

The connection error has not appeared after that. But we have a similar issue #21085 . You can keep an eye on it.

**Comment by anzemur** [comment]
@NicoYuan1986 My standalone container always crashes after it is running for some time.

**Comment by yanliang567** [comment]
> @NicoYuan1986 My standalone container always crashes after it is running for some time.

please file a new issue with milvus logs attached, thanks.
