### ISSUE TITLE
[Bug]: Search failed with `Deadline Exceeded` after reinstallation when using Kakfa as MQ

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#19087]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.0-20220906-7affd93
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):  pymilvus==2.2.0.dev26
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

search failed with error 
```
[2022-09-07T10:25:42.385Z] + python3 scripts/second_recall_test.py --host 10.101.155.124

[2022-09-07T10:29:18.766Z] RPC error: [search], <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:

[2022-09-07T10:29:18.766Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2022-09-07T10:29:18.766Z] 	details = "Deadline Exceeded"

[2022-09-07T10:29:18.766Z] 	debug_error_string = "{"created":"@1662546543.939990159","description":"Error received from peer ipv4:10.101.155.124:19530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"Deadline Exceeded","grpc_status":4}"

[2022-09-07T10:29:18.766Z] >)>, <Time:{'RPC start': '2022-09-07 10:25:43.816372', 'RPC error': '2022-09-07 10:29:03.943377'}>

[2022-09-07T10:29:18.766Z] 

[2022-09-07T10:29:18.766Z] Search...

[2022-09-07T10:29:18.766Z] Traceback (most recent call last):

[2022-09-07T10:29:18.766Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 50, in handler

[2022-09-07T10:29:18.766Z]     return func(self, *args, **kwargs)

[2022-09-07T10:29:18.766Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 473, in search

[2022-09-07T10:29:18.766Z]     return self._execute_search_requests(requests, timeout, **_kwargs)

[2022-09-07T10:29:18.766Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 437, in _execute_search_requests

[2022-09-07T10:29:18.766Z]     raise pre_err

[2022-09-07T10:29:18.766Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 425, in _execute_search_requests

[2022-09-07T10:29:18.766Z]     response = ft.result()

[2022-09-07T10:29:18.766Z]   File "/usr/local/lib/python3.7/dist-packages/grpc/_channel.py", line 744, in result

[2022-09-07T10:29:18.766Z]     raise self

[2022-09-07T10:29:18.766Z] grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:

[2022-09-07T10:29:18.766Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2022-09-07T10:29:18.766Z] 	details = "Deadline Exceeded"

[2022-09-07T10:29:18.766Z] 	debug_error_string = "{"created":"@1662546543.939990159","description":"Error received from peer ipv4:10.101.155.124:19530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"Deadline Exceeded","grpc_status":4}"

[2022-09-07T10:29:18.766Z] >

[2022-09-07T10:29:18.766Z] 

[2022-09-07T10:29:18.766Z] During handling of the above exception, another exception occurred:

[2022-09-07T10:29:18.766Z] 

[2022-09-07T10:29:18.766Z] Traceback (most recent call last):

[2022-09-07T10:29:18.766Z]   File "scripts/second_recall_test.py", line 64, in <module>

[2022-09-07T10:29:18.766Z]     search_test(host)

[2022-09-07T10:29:18.766Z]   File "scripts/second_recall_test.py", line 34, in search_test

[2022-09-07T10:29:18.766Z]     test[:nq], "float_vector", search_params, topK, output_fields=["int64"], timeout=TIMEOUT

[2022-09-07T10:29:18.766Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 718, in search

[2022-09-07T10:29:18.766Z]     partition_names, output_fields, round_decimal, timeout=timeout, schema=schema_dict, **kwargs)

[2022-09-07T10:29:18.766Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 101, in handler

[2022-09-07T10:29:18.766Z]     raise e

[2022-09-07T10:29:18.766Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 97, in handler

[2022-09-07T10:29:18.766Z]     return func(*args, **kwargs)

[2022-09-07T10:29:18.766Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 127, in handler

[2022-09-07T10:29:18.766Z]     ret = func(self, *args, **kwargs)

[2022-09-07T10:29:18.766Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 59, in handler

[2022-09-07T10:29:18.766Z]     raise MilvusException(Status.UNEXPECTED_ERROR, str(e))

[2022-09-07T10:29:18.766Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:

[2022-09-07T10:29:18.766Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2022-09-07T10:29:18.766Z] 	details = "Deadline Exceeded"

[2022-09-07T10:29:18.766Z] 	debug_error_string = "{"created":"@1662546543.939990159","description":"Error received from peer ipv4:10.101.155.124:19530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"Deadline Exceeded","grpc_status":4}"

[2022-09-07T10:29:18.766Z] >)>

script returned exit code 1
```

### Expected Behavior

all test cases passed

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_for_release/detail/deploy_test_for_release/78/pipeline

log:
[artifacts-cluster-reinstall-78-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9505628/artifacts-cluster-reinstall-78-server-logs.tar.gz)
[artifacts-cluster-reinstall-78-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9505630/artifacts-cluster-reinstall-78-pytest-logs.tar.gz)

### Anything else?

![image](https://user-images.githubusercontent.com/12268675/188865710-0759fd67-765f-46a7-954e-8b90ccea554f.png)

**Comment by zhuwenxing** [comment]
version 2.1.0-20220907-7b4dde4

cluster reinstall 
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_for_release/detail/deploy_test_for_release/91/pipeline
log:
[artifacts-cluster-reinstall-91-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9523168/artifacts-cluster-reinstall-91-server-logs.tar.gz)
[artifacts-cluster-reinstall-91-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9523170/artifacts-cluster-reinstall-91-pytest-logs.tar.gz)



standalone reinstall
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_for_release/detail/deploy_test_for_release/90/pipeline

[artifacts-standalone-reinstall-90-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9523173/artifacts-standalone-reinstall-90-server-logs.tar.gz)
[artifacts-standalone-reinstall-90-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9523175/artifacts-standalone-reinstall-90-pytest-logs.tar.gz)

**Comment by jiaoew1991** [comment]
because of delta channel have not received message for a long time, so the query task cannot be executed, after 20s query timeout

**Comment by jiaoew1991** [comment]
the statslog have some errors caused datanode load segment failed and start `flowgraph` failed. 

the `querynode` wait for datanode's `timetick` message to make `shard` available, but datanode's `flowgraph` start failed caused the `timetick` message will not be produced.

**Comment by zhuwenxing** [comment]
This issue has not happened in the pulsar version, but when Kafka is as MQ, this issue still occurs.


cluster upgrade
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_kafka_for_release/detail/deploy_test_kafka_for_release/98/pipeline

cluster reinstall 
https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_kafka_for_release/detail/deploy_test_kafka_for_release/96/pipeline

**Comment by zhuwenxing** [comment]
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_kafka_for_release/detail/deploy_test_kafka_for_release/135/pipeline
log:
[artifacts-cluster-reinstall-135-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9606882/artifacts-cluster-reinstall-135-server-logs.tar.gz)
[artifacts-cluster-reinstall-135-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9606886/artifacts-cluster-reinstall-135-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
/unassign 
/assign @jiaoew1991 
please help to take a look!

**Comment by jiaoew1991** [comment]
the root cause is quite like https://github.com/milvus-io/milvus/issues/20723, we can hold it until QueryNodeV2 is finished, it will remove DeltaChannel

**Comment by yanliang567** [comment]
remove critical urgent as comments above
