### ISSUE TITLE
[Bug]: Flush collection gets exception message : DataCoord 3 is not ready

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#19094]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220907-39b847b
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.0.dev26
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. Deploy milvus cluster
2. Insert 5m entities and flush once, flush gets the exception message
```
[2022-09-07 09:54:29,184 - DEBUG - ci_test]: (api_response) : (insert count: 50000, delete count: 0, upsert count: 0, timestamp: 435826056923709441, success count: 50000, err count: 0)  (api_request.py:31)
[2022-09-07 09:54:29,184 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 60} (api_request.py:56)
[2022-09-07 12:45:03,676 - ERROR - ci_test]: Traceback (most recent call last):
  File "/src/milvus/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/src/milvus/tests/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 408, in flush
    conn.flush([self.name], timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 101, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 97, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 127, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 79, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 947, in flush
    _check()
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 935, in _check
    self._wait_for_flushed(segment_ids)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 914, in _wait_for_flushed
    flush_ret = self.get_flush_state(segment_ids, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 101, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 97, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 127, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 79, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 898, in get_flush_state
    raise MilvusException(status.error_code, status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=DataCoord 3 is not ready)>
 (api_request.py:39)
```

Client pods: devops cluster, chaos-testing namespace
```
scale-out-index-node-czpkq-3283257497
```
Server pods: devops cluster, chaos-testing namespace
Note: Datanode pod restart many times because of oomkilled
```
NAME                                                 READY   STATUS    RESTARTS   AGE
scale-out-index-milvus-datacoord-67b9994bd8-jjzlh    1/1     Running   0          94s
scale-out-index-milvus-datanode-65956564b7-q8t92     1/1     Running   0          94s
scale-out-index-milvus-indexcoord-75ff8fdc48-dblvr   1/1     Running   0          94s
scale-out-index-milvus-indexnode-794d499f77-2bf28    1/1     Running   0          94s
scale-out-index-milvus-proxy-84db5df8f9-t4ccb        1/1     Running   0          94s
scale-out-index-milvus-querycoord-5bd4f58d4d-8cxdc   1/1     Running   0          94s
scale-out-index-milvus-querynode-75b667b9d7-ngr5j    1/1     Running   0          94s
scale-out-index-milvus-rootcoord-5b759c4b8d-mzw96    1/1     Running   0          94s
```

**Comment by NicoYuan1986** [comment]
Similar situation for 2.1 branch:
https://jenkins.milvus.io:18080/blue/organizations/jenkins/qa%2Fmilvus-release-nightly/detail/milvus-release-nightly/86/pipeline/212
1. [milvus-distributed-pulsar-86-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/qa/job/milvus-release-nightly/86/artifact/milvus-distributed-pulsar-86-pymilvus-e2e-logs.tar.gz)
2. collection name:  index_8CIugXgb
3. error:
```
[2022-09-07T21:25:51.719Z] [2022-09-07 20:26:49 - ERROR - pymilvus.decorators]: RPC error: [get_flush_state], <MilvusException: (code=1, message=DataCoord 0 is not ready)>, <Time:{'RPC start': '2022-09-07 20:26:47.453005', 'RPC error': '2022-09-07 20:26:49.190665'}> (decorators.py:95)
[2022-09-07T21:25:51.719Z] [2022-09-07 20:26:49 - ERROR - pymilvus.decorators]: RPC error: [flush], <MilvusException: (code=1, message=DataCoord 0 is not ready)>, <Time:{'RPC start': '2022-09-07 20:26:44.935619', 'RPC error': '2022-09-07 20:26:49.191116'}> (decorators.py:95)
```

**Comment by soothing-rain** [comment]
> 

It appears that neither of these two links works.

**Comment by soothing-rain** [comment]
> Similar situation for 2.1 branch: https://jenkins.milvus.io:18080/blue/organizations/jenkins/qa%2Fmilvus-release-nightly/detail/milvus-release-nightly/86/pipeline/212
> 
> 1. [milvus-distributed-pulsar-86-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/qa/job/milvus-release-nightly/86/artifact/milvus-distributed-pulsar-86-pymilvus-e2e-logs.tar.gz)
> 2. collection name:  index_8CIugXgb
> 3. error:
> 
> ```
> [2022-09-07T21:25:51.719Z] [2022-09-07 20:26:49 - ERROR - pymilvus.decorators]: RPC error: [get_flush_state], <MilvusException: (code=1, message=DataCoord 0 is not ready)>, <Time:{'RPC start': '2022-09-07 20:26:47.453005', 'RPC error': '2022-09-07 20:26:49.190665'}> (decorators.py:95)
> [2022-09-07T21:25:51.719Z] [2022-09-07 20:26:49 - ERROR - pymilvus.decorators]: RPC error: [flush], <MilvusException: (code=1, message=DataCoord 0 is not ready)>, <Time:{'RPC start': '2022-09-07 20:26:44.935619', 'RPC error': '2022-09-07 20:26:49.191116'}> (decorators.py:95)
> ```

Neither of the links works.
