### ISSUE TITLE
[Bug]: [Nightly] Query failed with message "code=1, message=err: failed to connect 10.105.7.184:21123, reason: context deadline exceeded"

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#19127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.*(a99a9669)
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.1.2.dev2
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Query failed:
```
[2022-09-09T00:22:58.238Z] [2022-09-08 23:34:24 - ERROR - pymilvus.decorators]: RPC error: [query], <MilvusException: (code=1, message=err: failed to connect 10.105.7.184:21123, reason: context deadline exceeded
[2022-09-09T00:22:58.238Z] , /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
[2022-09-09T00:22:58.238Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:232 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).Call
[2022-09-09T00:22:58.238Z] /go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:227 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Query
[2022-09-09T00:22:58.238Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_query.go:360 github.com/milvus-io/milvus/internal/proxy.(*queryTask).queryShard.func1
[2022-09-09T00:22:58.238Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_policies.go:55 github.com/milvus-io/milvus/internal/proxy.roundRobinPolicy
[2022-09-09T00:22:58.238Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_query.go:383 github.com/milvus-io/milvus/internal/proxy.(*queryTask).queryShard
[2022-09-09T00:22:58.238Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_query.go:256 github.com/milvus-io/milvus/internal/proxy.(*queryTask).Execute.func1.1
[2022-09-09T00:22:58.238Z] /go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 golang.org/x/sync/errgroup.(*Group).Go.func1
[2022-09-09T00:22:58.238Z] /usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit
[2022-09-09T00:22:58.238Z] )>, <Time:{'RPC start': '2022-09-08 23:34:14.318876', 'RPC error': '2022-09-08 23:34:24.324434'}> (decorators.py:95)
[2022-09-09T00:22:58.238Z] [2022-09-08 23:34:24 - ERROR - ci_test]: Traceback (most recent call last):
[2022-09-09T00:22:58.238Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
[2022-09-09T00:22:58.238Z]     res = func(*args, **kwargs)
[2022-09-09T00:22:58.238Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 56, in api_request
[2022-09-09T00:22:58.238Z]     return func(*arg, **kwargs)
[2022-09-09T00:22:58.238Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 796, in query
[2022-09-09T00:22:58.239Z]     res = conn.query(self._name, expr, output_fields, partition_names, timeout=timeout, schema=schema_dict, **kwargs)
[2022-09-09T00:22:58.239Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 96, in handler
[2022-09-09T00:22:58.239Z]     raise e
[2022-09-09T00:22:58.239Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 92, in handler
[2022-09-09T00:22:58.239Z]     return func(*args, **kwargs)
[2022-09-09T00:22:58.239Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler
[2022-09-09T00:22:58.239Z]     raise e
[2022-09-09T00:22:58.239Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 48, in handler
[2022-09-09T00:22:58.239Z]     return func(self, *args, **kwargs)
[2022-09-09T00:22:58.239Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 974, in query
[2022-09-09T00:22:58.239Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2022-09-09T00:22:58.239Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=err: failed to connect 10.105.7.184:21123, reason: context deadline exceeded
[2022-09-09T00:22:58.239Z] , /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
[2022-09-09T00:22:58.239Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:232 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).Call
[2022-09-09T00:22:58.239Z] /go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:227 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Query
[2022-09-09T00:22:58.239Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_query.go:360 github.com/milvus-io/milvus/internal/proxy.(*queryTask).queryShard.func1
[2022-09-09T00:22:58.239Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_policies.go:55 github.com/milvus-io/milvus/internal/proxy.roundRobinPolicy
[2022-09-09T00:22:58.239Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_query.go:383 github.com/milvus-io/milvus/internal/proxy.(*queryTask).queryShard
[2022-09-09T00:22:58.239Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_query.go:256 github.com/milvus-io/milvus/internal/proxy.(*queryTask).Execute.func1.1
[2022-09-09T00:22:58.239Z] /go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 golang.org/x/sync/errgroup.(*Group).Go.func1
[2022-09-09T00:22:58.239Z] /usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit
[2022-09-09T00:22:58.239Z] )>
[2022-09-09T00:22:58.239Z]  (api_request.py:35)
[2022-09-09T00:22:58.239Z] [2022-09-08 23:34:24 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=err: failed to connect 10.105.7.184:21123, reason: context deadline exceeded
[2022-09-09T00:22:58.239Z] , /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
[2022-09-09T00:22:58.239Z] /go/src/github.com/milvus-io/milvus/internal/util/grp...... (api_request.py:36)
```

### Expected Behavior

PASS

### Steps To Reproduce

nightly: https://jenkins.milvus.io:18080/blue/organizations/jenkins/qa%2Fmilvus-release-nightly/detail/milvus-release-nightly/89/pipeline/177/

### Milvus Log

1. collection name: query_J3QACFez
2. failed time line: [2022-09-08T23:34:32.593Z] [gw5] [ 39%] FAILED testcases/test_query.py::TestQueryParams::test_query_output_primary_field
3. log: [milvus-distributed-kafka-89-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/qa/job/milvus-release-nightly/89/artifact/milvus-distributed-kafka-89-pymilvus-e2e-logs.tar.gz)
4. some information: 
```
2022-09-09T07:19:59.275447104+08:00 stderr F panic: new session error, maybe can not connect to etcd
2022-09-09T07:19:59.275475513+08:00 stderr F
2022-09-09T07:19:59.275482387+08:00 stderr F goroutine 113 [running]:
2022-09-09T07:19:59.275495182+08:00 stderr F github.com/milvus-io/milvus/internal/distributed/datanode.(*Server).init(0xc000bd7720, 0x8bdf3e, 0xc000bcc0f8)
2022-09-09T07:19:59.275501346+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/distributed/datanode/service.go:252 +0x204b
2022-09-09T07:19:59.275506856+08:00 stderr F github.com/milvus-io/milvus/internal/distributed/datanode.(*Server).Run(0xc000bd7720, 0x0, 0x0)
2022-09-09T07:19:59.275511754+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/distributed/datanode/service.go:166 +0x2f
2022-09-09T07:19:59.275520095+08:00 stderr F github.com/milvus-io/milvus/cmd/components.(*DataNode).Run(0xc00013c150, 0xffffffffffffffff, 0x8)
2022-09-09T07:19:59.275525123+08:00 stderr F    /go/src/github.com/milvus-io/milvus/cmd/components/data_node.go:50 +0x33
2022-09-09T07:19:59.275530242+08:00 stderr F github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runDataNode.func1(0x0, 0x0, 0x40c0700, 0x43b1630, 0xc000534b40, 0xc00020c030, 0xc000bcc040, 0xc000bcc0f0)
2022-09-09T07:19:59.275550895+08:00 stderr F    /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:283 +0x165
2022-09-09T07:19:59.275560635+08:00 stderr F created by github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runDataNode
2022-09-09T07:19:59.275565879+08:00 stderr F    /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:264 +0xda
```

**Comment by weiliu1031** [comment]
cause query node crash when this query happen. 
recently, we notice that query node will crash at search process, and this will cause different problems， such as:
1. load Collection failed 
2. Search Failed 

the reason of why query node crash during seach process is still in investigating.

**Comment by NicoYuan1986** [comment]
Recently, The issue occurs in https://jenkins.milvus.io:18080/blue/organizations/jenkins/qa%2Fmilvus-release-nightly/detail/milvus-release-nightly/127/pipeline/177.
1. milvus log: [milvus-distributed-kafka-127-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/qa/job/milvus-release-nightly/127/artifact/milvus-distributed-kafka-127-pymilvus-e2e-logs.tar.gz)
2. collection name: coll__T8vdSsMF
3. FAILED timeline: [2022-09-27T20:33:35.147Z] [gw3] [ 37%] FAILED testcases/test_partition.py::TestPartitionOperations::test_partition_release_after_collection_released
4. error message:
```
[2022-09-27T21:17:04.042Z] [2022-09-27 20:33:31 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=err: failed to connect 10.105.1.238:21123, reason: context deadline exceeded
[2022-09-27T21:17:04.042Z] , /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
[2022-09-27T21:17:04.042Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:232 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).Call
[2022-09-27T21:17:04.042Z] /go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:213 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Search
[2022-09-27T21:17:04.042Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:445 github.com/milvus-io/milvus/internal/proxy.(*searchTask).searchShard.func1
[2022-09-27T21:17:04.042Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_policies.go:55 github.com/milvus-io/milvus/internal/proxy.roundRobinPolicy
[2022-09-27T21:17:04.042Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:465 github.com/milvus-io/milvus/internal/proxy.(*searchTask).searchShard
[2022-09-27T21:17:04.042Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:324 github.com/milvus-io/milvus/internal/proxy.(*searchTask).Execute.func1.1
[2022-09-27T21:17:04.042Z] /go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 golang.org/x/sync/errgroup.(*Group).Go.func1
[2022-09-27T21:17:04.042Z] /usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit
[2022-09-27T21:17:04.042Z] )>, <Time:{'RPC start': '2022-09-27 20:33:21.298686', 'RPC error': '2022-09-27 20:33:31.305235'}> (decorators.py:95)
[2022-09-27T21:17:04.042Z] [2022-09-27 20:33:31 - ERROR - ci_test]: Traceback (most recent call last):
[2022-09-27T21:17:04.042Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
[2022-09-27T21:17:04.042Z]     res = func(*args, **kwargs)
[2022-09-27T21:17:04.042Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 56, in api_request
[2022-09-27T21:17:04.042Z]     return func(*arg, **kwargs)
[2022-09-27T21:17:04.042Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/partition.py", line 432, in search
[2022-09-27T21:17:04.042Z]     expr, [self._name], output_fields, round_decimal, timeout=timeout, schema=schema_dict, **kwargs)
[2022-09-27T21:17:04.042Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 96, in handler
[2022-09-27T21:17:04.042Z]     raise e
[2022-09-27T21:17:04.042Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 92, in handler
[2022-09-27T21:17:04.042Z]     return func(*args, **kwargs)
[2022-09-27T21:17:04.042Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler
[2022-09-27T21:17:04.042Z]     raise e
[2022-09-27T21:17:04.042Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 48, in handler
[2022-09-27T21:17:04.042Z]     return func(self, *args, **kwargs)
[2022-09-27T21:17:04.042Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 446, in search
[2022-09-27T21:17:04.042Z]     return self._execute_search_requests(requests, timeout, **_kwargs)
[2022-09-27T21:17:04.042Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 410, in _execute_search_requests
[2022-09-27T21:17:04.042Z]     raise pre_err
[2022-09-27T21:17:04.042Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 401, in _execute_search_requests
[2022-09-27T21:17:04.042Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2022-09-27T21:17:04.042Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=err: failed to connect 10.105.1.238:21123, reason: context deadline exceeded
[2022-09-27T21:17:04.042Z] , /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
[2022-09-27T21:17:04.042Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:232 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).Call
[2022-09-27T21:17:04.042Z] /go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:213 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Search
[2022-09-27T21:17:04.042Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:445 github.com/milvus-io/milvus/internal/proxy.(*searchTask).searchShard.func1
[2022-09-27T21:17:04.042Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_policies.go:55 github.com/milvus-io/milvus/internal/proxy.roundRobinPolicy
[2022-09-27T21:17:04.042Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:465 github.com/milvus-io/milvus/internal/proxy.(*searchTask).searchShard
[2022-09-27T21:17:04.042Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:324 github.com/milvus-io/milvus/internal/proxy.(*searchTask).Execute.func1.1
[2022-09-27T21:17:04.042Z] /go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 golang.org/x/sync/errgroup.(*Group).Go.func1
[2022-09-27T21:17:04.042Z] /usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit
[2022-09-27T21:17:04.042Z] )>
[2022-09-27T21:17:04.042Z]  (api_request.py:35)
[2022-09-27T21:17:04.042Z] [2022-09-27 20:33:31 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=err: failed to connect 10.105.1.238:21123, reason: context deadline exceeded
[2022-09-27T21:17:04.042Z] , /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
[2022-09-27T21:17:04.042Z] /go/src/github.com/milvus-io/milvus/internal/util/grp...... (api_request.py:36)
```
