### ISSUE TITLE
[Bug]: Create index failed reporting "IndexCoord 0 is not ready"

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#19143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:687291b
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0.dev30
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

When i pull request, Case "test_load_partition_after_index_binary" failed reporting "IndexCoord 0 is not ready".
```
[2022-09-09T09:14:36.151Z] [2022-09-09 09:14:23 - ERROR - pymilvus.decorators]: RPC error: [create_index], <MilvusException: (code=1, message=IndexCoord 0 is not ready)>, <Time:{'RPC start': '2022-09-09 09:14:22.776768', 'RPC error': '2022-09-09 09:14:23.045287'}> (decorators.py:100)
[2022-09-09T09:14:36.151Z] [2022-09-09 09:14:23 - ERROR - ci_test]: Traceback (most recent call last):
[2022-09-09T09:14:36.151Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2022-09-09T09:14:36.151Z]     res = func(*args, **_kwargs)
[2022-09-09T09:14:36.151Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2022-09-09T09:14:36.151Z]     return func(*arg, **kwargs)
[2022-09-09T09:14:36.151Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 1087, in create_index
[2022-09-09T09:14:36.151Z]     timeout=timeout, **kwargs)
[2022-09-09T09:14:36.151Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 101, in handler
[2022-09-09T09:14:36.151Z]     raise e
[2022-09-09T09:14:36.151Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 97, in handler
[2022-09-09T09:14:36.151Z]     return func(*args, **kwargs)
[2022-09-09T09:14:36.151Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 127, in handler
[2022-09-09T09:14:36.151Z]     ret = func(self, *args, **kwargs)
[2022-09-09T09:14:36.151Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 79, in handler
[2022-09-09T09:14:36.151Z]     raise e
[2022-09-09T09:14:36.151Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 50, in handler
[2022-09-09T09:14:36.151Z]     return func(self, *args, **kwargs)
[2022-09-09T09:14:36.151Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 576, in create_index
[2022-09-09T09:14:36.151Z]     raise MilvusException(status.error_code, status.reason)
[2022-09-09T09:14:36.151Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=IndexCoord 0 is not ready)>
[2022-09-09T09:14:36.151Z]  (api_request.py:39)
[2022-09-09T09:14:36.151Z] [2022-09-09 09:14:23 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=IndexCoord 0 is not ready)> (api_request.py:40)
```

### Expected Behavior

PASS

### Steps To Reproduce

```markdown
log: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-19116/4/pipeline/142/
```

### Milvus Log

1. collection name: collection_iX1yw4dK
2. failed timeline: [2022-09-09T09:14:36.147Z] [gw4] [  8%] FAILED testcases/test_collection.py::TestLoadPartition::test_load_partition_after_index_binary[SUBSTRUCTURE-binary_index0] 
3. log: [artifacts-milvus-distributed-PR-19116-4-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20HA%20CI/job/PR-19116/4/artifact/artifacts-milvus-distributed-PR-19116-4-pymilvus-e2e-logs.tar.gz)
4. some message:
```
2022-09-09T17:15:22.287251491+08:00 stderr F panic: rpc error: code = Canceled desc = latest balancer error: last connection error: connection error: desc = "transport: Error while dialing dial tcp: lookup ms-19116-4-pr-etcd on 10.255.0.10:53: server misbehaving"
2022-09-09T17:15:22.287271693+08:00 stderr F
2022-09-09T17:15:22.287278832+08:00 stderr F goroutine 560408 [running]:
2022-09-09T17:15:22.287290263+08:00 stderr F github.com/milvus-io/milvus/internal/querynode.(*etcdShardNodeDetector).watch(0xc00636b310, 0xc007d9ca80, 0x60c8606550b8235, 0x60c860658040489)
2022-09-09T17:15:22.287295492+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/querynode/shard_node_detector.go:155 +0x6b7
2022-09-09T17:15:22.287307286+08:00 stderr F created by github.com/milvus-io/milvus/internal/querynode.(*etcdShardNodeDetector).watchNodes
2022-09-09T17:15:22.287311494+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/querynode/shard_node_detector.go:123 +0x9d3
2022-09-09T17:15:22.294778899+08:00 stderr F panic: rpc error: code = Canceled desc = latest balancer error: last connection error: connection error: desc = "transport: Error while dialing dial tcp: lookup ms-19116-4-pr-etcd on 10.255.0.10:53: server misbehaving"
2022-09-09T17:15:22.294806578+08:00 stderr F
2022-09-09T17:15:22.294817795+08:00 stderr F goroutine 265536 [running]:
2022-09-09T17:15:22.29482894+08:00 stderr F github.com/milvus-io/milvus/internal/querynode.(*etcdShardNodeDetector).watch(0xc0071767d0, 0xc00fc09a40, 0x60c860655023917, 0x60c8606580401af)
```

**Comment by bigsheeper** [comment]
@NicoYuan1986 is this issue deployed in cluster?  I noticed that the `Deployment mode` is `cluster` while the log is standalone.

**Comment by bigsheeper** [comment]
querynode failed to connect to ETCD when detect shard node:
```
2022-09-09T17:15:22.279761477+08:00 stdout F [2022/09/09 09:15:22.279 +00:00] [ERROR] [querynode/shard_node_detector.go:154] ["failed to handle watch node error"] [error="rpc error: code = Canceled desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp: lookup ms-19116-4-pr-etcd on 10.255.0.10:53: server misbehaving\""] [stack="github.com/milvus-io/milvus/internal/querynode.(*etcdShardNodeDetector).watch\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/shard_node_detector.go:154"]
2022-09-09T17:15:22.279782406+08:00 stdout F [2022/09/09 09:15:22.279 +00:00] [ERROR] [querynode/shard_node_detector.go:154] ["failed to handle watch node error"] [error="rpc error: code = Canceled desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp: lookup ms-19116-4-pr-etcd on 10.255.0.10:53: server misbehaving\""] [stack="github.com/milvus-io/milvus/internal/querynode.(*etcdShardNodeDetector).watch\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/shard_node_detector.go:154"]
2022-09-09T17:15:22.27979041+08:00 stdout F [2022/09/09 09:15:22.279 +00:00] [ERROR] [querynode/shard_node_detector.go:154] ["failed to handle watch node error"] [error="rpc error: code = Canceled desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp: lookup ms-19116-4-pr-etcd on 10.255.0.10:53: server misbehaving\""] [stack="github.com/milvus-io/milvus/internal/querynode.(*etcdShardNodeDetector).watch\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/shard_node_detector.go:154"]
2022-09-09T17:15:22.287251491+08:00 stderr F panic: rpc error: code = Canceled desc = latest balancer error: last connection error: connection error: desc = "transport: Error while dialing dial tcp: lookup ms-19116-4-pr-etcd on 10.255.0.10:53: server misbehaving"
2022-09-09T17:15:22.287271693+08:00 stderr F 
```

**Comment by NicoYuan1986** [comment]
> @NicoYuan1986 is this issue deployed in cluster? I noticed that the `Deployment mode` is `cluster` while the log is standalone.

Sorry, I posted the wrong link.The issue is deployed in cluster.The correct link has been added.

**Comment by bigsheeper** [comment]
IndexCoord SIGSEGV
```
2022-09-09T17:14:40.387153453+08:00 stdout F [2022/09/09 09:14:40.387 +00:00] [DEBUG] [indexcoord/node_manager.go:66] ["IndexNode NodeManager setClient success"] [nodeID=4] ["IndexNode num"=1]
2022-09-09T17:14:40.387163151+08:00 stdout F [2022/09/09 09:14:40.387 +00:00] [DEBUG] [indexcoord/index_coord.go:206] [IndexCoord] ["IndexNode number"=1]
2022-09-09T17:14:40.38963631+08:00 stdout F [2022/09/09 09:14:40.389 +00:00] [INFO] [storage/minio_chunk_manager.go:109] ["minio chunk manager init success."] [bucketname=milvus-bucket] [root=file]
2022-09-09T17:14:40.389653124+08:00 stdout F [2022/09/09 09:14:40.389 +00:00] [DEBUG] [indexcoord/index_coord.go:218] ["IndexCoord new minio chunkManager success"]
2022-09-09T17:14:40.389661999+08:00 stdout F [2022/09/09 09:14:40.389 +00:00] [INFO] [indexcoord/flush_segment_watcher.go:100] ["flushSegmentWatcher reloadFromKV"]
2022-09-09T17:14:40.392753749+08:00 stderr F panic: runtime error: invalid memory address or nil pointer dereference
2022-09-09T17:14:40.392769339+08:00 stderr F [signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0x198afce]
2022-09-09T17:14:40.392772094+08:00 stderr F 
2022-09-09T17:14:40.392774866+08:00 stderr F goroutine 213 [running]:
2022-09-09T17:14:40.392777627+08:00 stderr F github.com/milvus-io/milvus/internal/indexcoord.(*flushedSegmentWatcher).pullSegmentInfo(0xc000f90000, 0x60c860e763f1226)
2022-09-09T17:14:40.39278009+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/indexcoord/flush_segment_watcher.go:563 +0xce
2022-09-09T17:14:40.392790132+08:00 stderr F github.com/milvus-io/milvus/internal/indexcoord.(*flushedSegmentWatcher).prepare(0xc000f90040?, 0x60c860e763f1226)
2022-09-09T17:14:40.392793096+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/indexcoord/flush_segment_watcher.go:591 +0x3b
2022-09-09T17:14:40.392795463+08:00 stderr F github.com/milvus-io/milvus/internal/indexcoord.(*flushedSegmentWatcher).enqueueInternalTask(0xc000f90000, 0x12?)
2022-09-09T17:14:40.392799877+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/indexcoord/flush_segment_watcher.go:142 +0xa5
2022-09-09T17:14:40.392806863+08:00 stderr F github.com/milvus-io/milvus/internal/indexcoord.(*flushedSegmentWatcher).reloadFromKV(0xc000f90000)
2022-09-09T17:14:40.392809273+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/indexcoord/flush_segment_watcher.go:114 +0x367
2022-09-09T17:14:40.39281608+08:00 stderr F github.com/milvus-io/milvus/internal/indexcoord.newFlushSegmentWatcher({0x3016628?, 0xc000255fc0?}, {0x3033898?, 0xc000590d50}, 0xc00068f320, 0xc0004227e0, 0xc000cb4160)
2022-09-09T17:14:40.392820683+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/indexcoord/flush_segment_watcher.go:92 +0x1b7
2022-09-09T17:14:40.392823171+08:00 stderr F github.com/milvus-io/milvus/internal/indexcoord.(*IndexCoord).Init.func1()
2022-09-09T17:14:40.392825619+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/indexcoord/index_coord.go:222 +0x1056
2022-09-09T17:14:40.392831887+08:00 stderr F sync.(*Once).doSlow(0xc000123000?, 0x673976?)
2022-09-09T17:14:40.392834445+08:00 stderr F 	/usr/local/go/src/sync/once.go:68 +0xc2
```

**Comment by bigsheeper** [comment]
same as https://github.com/milvus-io/milvus/issues/19164
/unassign
/assign @xiaocai2333

**Comment by xiaocai2333** [comment]
fixed, please verify it. @NicoYuan1986 
/unassign
/assign @NicoYuan1986

**Comment by NicoYuan1986** [comment]
Thanks! The issue has been solved!
