### ISSUE TITLE
[Bug]: Indexcoord panics when starts with existing `FlushedSegments`

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#19167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: ec48e24
- Deployment mode(standalone or cluster): both
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

`Indexcoord` panics when starts with existing `FlushedSegments` kv values

### Expected Behavior

`Indexcoord` shall not panic when starts with existing `FlushedSegments` kv

### Milvus Log

```
2022-09-13T12:44:03.125147455+08:00 stdout F [2022/09/13 04:44:03.125 +00:00] [INFO] [indexcoord/flush_segment_watcher.go:100] ["flushSegmentWatcher reloadFromKV"]
2022-09-13T12:44:03.127977838+08:00 stderr F panic: runtime error: invalid memory address or nil pointer dereference
2022-09-13T12:44:03.127997091+08:00 stderr F [signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0x198c14e]
2022-09-13T12:44:03.128001616+08:00 stderr F 
2022-09-13T12:44:03.128005577+08:00 stderr F goroutine 160 [running]:
2022-09-13T12:44:03.128010457+08:00 stderr F github.com/milvus-io/milvus/internal/indexcoord.(*flushedSegmentWatcher).pullSegmentInfo(0xc0005c6240, 0x60cd44365bccb88)
2022-09-13T12:44:03.128019526+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/indexcoord/flush_segment_watcher.go:563 +0xce
2022-09-13T12:44:03.128029448+08:00 stderr F github.com/milvus-io/milvus/internal/indexcoord.(*flushedSegmentWatcher).prepare(0xc0005c6280?, 0x60cd44365bccb88)
2022-09-13T12:44:03.128043039+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/indexcoord/flush_segment_watcher.go:591 +0x3b
2022-09-13T12:44:03.128046092+08:00 stderr F github.com/milvus-io/milvus/internal/indexcoord.(*flushedSegmentWatcher).enqueueInternalTask(0xc0005c6240, 0x12?)
2022-09-13T12:44:03.128049611+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/indexcoord/flush_segment_watcher.go:142 +0xa5
2022-09-13T12:44:03.128053059+08:00 stderr F github.com/milvus-io/milvus/internal/indexcoord.(*flushedSegmentWatcher).reloadFromKV(0xc0005c6240)
2022-09-13T12:44:03.128056563+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/indexcoord/flush_segment_watcher.go:114 +0x367
2022-09-13T12:44:03.128066722+08:00 stderr F github.com/milvus-io/milvus/internal/indexcoord.newFlushSegmentWatcher({0x3017b28?, 0xc0006ec1c0?}, {0x3034da0?, 0xc0005be618}, 0xc00022d500, 0xc0006bc540, 0xc00129a160)
2022-09-13T12:44:03.128083111+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/indexcoord/flush_segment_watcher.go:92 +0x1b7
2022-09-13T12:44:03.128086415+08:00 stderr F github.com/milvus-io/milvus/internal/indexcoord.(*IndexCoord).Init.func1()
2022-09-13T12:44:03.128089873+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/indexcoord/index_coord.go:222 +0x1056
2022-09-13T12:44:03.128104936+08:00 stderr F sync.(*Once).doSlow(0xc000181400?, 0x673976?)
2022-09-13T12:44:03.128110041+08:00 stderr F 	/usr/local/go/src/sync/once.go:68 +0xc2
2022-09-13T12:44:03.128112944+08:00 stderr F sync.(*Once).Do(...)
2022-09-13T12:44:03.128116241+08:00 stderr F 	/usr/local/go/src/sync/once.go:59
2022-09-13T12:44:03.128119976+08:00 stderr F github.com/milvus-io/milvus/internal/indexcoord.(*IndexCoord).Init(0xc00129a160?)
2022-09-13T12:44:03.128123827+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/indexcoord/index_coord.go:159 +0x95
2022-09-13T12:44:03.128127145+08:00 stderr F github.com/milvus-io/milvus/internal/distributed/indexcoord.(*Server).init(0xc001260580)
2022-09-13T12:44:03.128131311+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/distributed/indexcoord/service.go:118 +0x4df
2022-09-13T12:44:03.128135099+08:00 stderr F github.com/milvus-io/milvus/internal/distributed/indexcoord.(*Server).Run(0xc00125ff60?)
2022-09-13T12:44:03.128147582+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/distributed/indexcoord/service.go:81 +0x25
2022-09-13T12:44:03.128150681+08:00 stderr F github.com/milvus-io/milvus/cmd/components.(*IndexCoord).Run(0x437e020?)
2022-09-13T12:44:03.12815424+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/cmd/components/index_coord.go:48 +0x1c
2022-09-13T12:44:03.128164721+08:00 stderr F github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runIndexCoord.func1()
2022-09-13T12:44:03.128171438+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:315 +0x1d5
2022-09-13T12:44:03.128174843+08:00 stderr F created by github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runIndexCoord
2022-09-13T12:44:03.12817937+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:296 +0xf8

```

**Comment by congqixia** [comment]
Related to #19164
