### ISSUE TITLE
[Bug]: indexcoord painc with error `panic: runtime error: invalid memory address or nil pointer dereference` after indexcoord pod failure chaos test 

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#19164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220909-4de1bfe
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/12268675/189800124-aa0cd9eb-21e4-42e2-bfa6-7a0f43adb733.png)

```
[2022/09/13 03:09:33.392 +00:00] [DEBUG] [indexcoord/index_coord.go:218] ["IndexCoord new minio chunkManager success"]
[2022/09/13 03:09:33.392 +00:00] [INFO] [indexcoord/flush_segment_watcher.go:100] ["flushSegmentWatcher reloadFromKV"]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0x198b48e]

goroutine 146 [running]:
github.com/milvus-io/milvus/internal/indexcoord.(*flushedSegmentWatcher).pullSegmentInfo(0xc000b400c0, 0x60cd3115bd70d92)
	/go/src/github.com/milvus-io/milvus/internal/indexcoord/flush_segment_watcher.go:563 +0xce
github.com/milvus-io/milvus/internal/indexcoord.(*flushedSegmentWatcher).prepare(0xc000b40100?, 0x60cd3115bd70d92)
	/go/src/github.com/milvus-io/milvus/internal/indexcoord/flush_segment_watcher.go:591 +0x3b
github.com/milvus-io/milvus/internal/indexcoord.(*flushedSegmentWatcher).enqueueInternalTask(0xc000b400c0, 0x12?)
	/go/src/github.com/milvus-io/milvus/internal/indexcoord/flush_segment_watcher.go:142 +0xa5
github.com/milvus-io/milvus/internal/indexcoord.(*flushedSegmentWatcher).reloadFromKV(0xc000b400c0)
	/go/src/github.com/milvus-io/milvus/internal/indexcoord/flush_segment_watcher.go:114 +0x367
github.com/milvus-io/milvus/internal/indexcoord.newFlushSegmentWatcher({0x30166e8?, 0xc0005789c0?}, {0x3033958?, 0xc0004527c8}, 0xc0010aab40, 0xc0005af2d0, 0xc0005322c0)
	/go/src/github.com/milvus-io/milvus/internal/indexcoord/flush_segment_watcher.go:92 +0x1b7
github.com/milvus-io/milvus/internal/indexcoord.(*IndexCoord).Init.func1()
	/go/src/github.com/milvus-io/milvus/internal/indexcoord/index_coord.go:222 +0x1056
sync.(*Once).doSlow(0xc0000ab800?, 0x673976?)
	/usr/local/go/src/sync/once.go:68 +0xc2
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:59
github.com/milvus-io/milvus/internal/indexcoord.(*IndexCoord).Init(0xc0005322c0?)
	/go/src/github.com/milvus-io/milvus/internal/indexcoord/index_coord.go:159 +0x95
github.com/milvus-io/milvus/internal/distributed/indexcoord.(*Server).init(0xc000a34f80)
	/go/src/github.com/milvus-io/milvus/internal/distributed/indexcoord/service.go:118 +0x4df
github.com/milvus-io/milvus/internal/distributed/indexcoord.(*Server).Run(0xc0003c1f60?)
	/go/src/github.com/milvus-io/milvus/internal/distributed/indexcoord/service.go:81 +0x25
github.com/milvus-io/milvus/cmd/components.(*IndexCoord).Run(0x437d020?)
	/go/src/github.com/milvus-io/milvus/cmd/components/index_coord.go:48 +0x1c
github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runIndexCoord.func1()
	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:315 +0x1d5
created by github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runIndexCoord
	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:296 +0xf8

```

### Expected Behavior

all test cases passed

### Milvus Log

failed job:  https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/1186/pipeline

log:
[artifacts-indexcoord-pod-failure-1186-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/9553252/artifacts-indexcoord-pod-failure-1186-server-logs.1.tar.gz)
[artifacts-indexcoord-pod-failure-1186-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9553253/artifacts-indexcoord-pod-failure-1186-pytest-logs.tar.gz)

**Comment by xiaocai2333** [comment]
fixed, please verify @zhuwenxing 
/assign @zhuwenxing

**Comment by zhuwenxing** [comment]
verified and passed in `master-20220919-8ac30397`
