### ISSUE TITLE
[Bug]: IndexCoord panics when enqueueTask run with internal timer

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#19179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 91663a6
- Deployment mode(standalone or cluster): both
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

IndexCoord panics when enqueueTask run with internal timer

### Expected Behavior

`enqueueInternalTask` shall work with internal timer lopp without panics

### Milvus Log

```
2022-09-13T12:43:59.703256999+08:00 stdout F [2022/09/13 04:43:59.703 +00:00] [DEBUG] [indexcoord/index_coord.go:1049] ["watchFlushedSegmentLoop watch event"] [segID=435956649882864512]
2022-09-13T12:43:59.703290253+08:00 stdout F [2022/09/13 04:43:59.703 +00:00] [INFO] [indexcoord/flush_segment_watcher.go:540] ["IndexCoord write handoff task success"] [collID=435956649882864382] [partID=435956649882864383] [segID=435956649882864515]
2022-09-13T12:43:59.705630154+08:00 stdout F [2022/09/13 04:43:59.704 +00:00] [INFO] [indexcoord/flush_segment_watcher.go:553] ["IndexCoord remove flushed segment success"] [collID=435956649882864382] [partID=435956649882864383] [segID=435956649882864515]
2022-09-13T12:43:59.705678052+08:00 stdout F [2022/09/13 04:43:59.704 +00:00] [DEBUG] [indexcoord/flush_segment_watcher.go:231] ["IndexCoord flushedSegmentWatcher schedule internal tasks"] ["internal task num"=1]
2022-09-13T12:43:59.70848014+08:00 stdout F [2022/09/13 04:43:59.708 +00:00] [DEBUG] [indexcoord/flush_segment_watcher.go:370] ["IndexCoord flushedSegmentWatcher process internal task"] [segID=435956649882864512] [state=Init]
2022-09-13T12:43:59.708501283+08:00 stdout F [2022/09/13 04:43:59.708 +00:00] [DEBUG] [indexcoord/flush_segment_watcher.go:510] ["IndexCoord flushedSegmentWatcher construct tasks by segment info"] [segID=435956649882864512] [compactionFrom="[]"]
2022-09-13T12:43:59.708505676+08:00 stdout F [2022/09/13 04:43:59.708 +00:00] [DEBUG] [indexcoord/flush_segment_watcher.go:514] ["segment no need to build index"] [segmentID=435956649882864512] ["num of rows"=741] ["collection indexes num"=0]
2022-09-13T12:43:59.708511381+08:00 stdout F [2022/09/13 04:43:59.708 +00:00] [DEBUG] [indexcoord/flush_segment_watcher.go:231] ["IndexCoord flushedSegmentWatcher schedule internal tasks"] ["internal task num"=1]
2022-09-13T12:43:59.70869136+08:00 stdout F [2022/09/13 04:43:59.708 +00:00] [DEBUG] [indexcoord/flush_segment_watcher.go:370] ["IndexCoord flushedSegmentWatcher process internal task"] [segID=435956649882864512] [state=InProgress]
2022-09-13T12:43:59.70874072+08:00 stdout F [2022/09/13 04:43:59.708 +00:00] [DEBUG] [indexcoord/flush_segment_watcher.go:231] ["IndexCoord flushedSegmentWatcher schedule internal tasks"] ["internal task num"=1]
2022-09-13T12:43:59.708748376+08:00 stdout F [2022/09/13 04:43:59.708 +00:00] [DEBUG] [indexcoord/flush_segment_watcher.go:370] ["IndexCoord flushedSegmentWatcher process internal task"] [segID=435956649882864512] [state=Done]
2022-09-13T12:43:59.715960701+08:00 stdout F [2022/09/13 04:43:59.715 +00:00] [INFO] [indexcoord/flush_segment_watcher.go:540] ["IndexCoord write handoff task success"] [collID=435956649882864382] [partID=435956649882864383] [segID=435956649882864512]
2022-09-13T12:43:59.719408496+08:00 stdout F [2022/09/13 04:43:59.719 +00:00] [INFO] [indexcoord/flush_segment_watcher.go:553] ["IndexCoord remove flushed segment success"] [collID=435956649882864382] [partID=435956649882864383] [segID=435956649882864512]
2022-09-13T12:43:59.721761581+08:00 stderr F panic: runtime error: invalid memory address or nil pointer dereference
2022-09-13T12:43:59.721814933+08:00 stderr F [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1987ddc]
2022-09-13T12:43:59.721820387+08:00 stderr F 
2022-09-13T12:43:59.721824921+08:00 stderr F goroutine 363 [running]:
2022-09-13T12:43:59.721829228+08:00 stderr F github.com/milvus-io/milvus/internal/indexcoord.(*flushedSegmentWatcher).getInternalTask(0xc00076ca80, 0x60cd44365bccb80?)
2022-09-13T12:43:59.721841534+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/indexcoord/flush_segment_watcher.go:302 +0xbc
2022-09-13T12:43:59.721845352+08:00 stderr F github.com/milvus-io/milvus/internal/indexcoord.(*flushedSegmentWatcher).prepare(0xc00076cac0?, 0x60cd44365bccb80)
2022-09-13T12:43:59.721848085+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/indexcoord/flush_segment_watcher.go:600 +0x26d
2022-09-13T12:43:59.721851084+08:00 stderr F github.com/milvus-io/milvus/internal/indexcoord.(*flushedSegmentWatcher).enqueueInternalTask(0xc00076ca80, 0x12?)
2022-09-13T12:43:59.721854031+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/indexcoord/flush_segment_watcher.go:142 +0xa5
2022-09-13T12:43:59.721857492+08:00 stderr F github.com/milvus-io/milvus/internal/indexcoord.(*IndexCoord).watchFlushedSegmentLoop(0xc000472dc0)
2022-09-13T12:43:59.721860192+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/indexcoord/index_coord.go:1050 +0xc25
2022-09-13T12:43:59.721862933+08:00 stderr F created by github.com/milvus-io/milvus/internal/indexcoord.(*IndexCoord).Start.func1
2022-09-13T12:43:59.721865533+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/indexcoord/index_coord.go:252 +0xca

```

**Comment by congqixia** [comment]
Fixed by #19374 19163
