### ISSUE TITLE
[Bug]: Create index failed reporting "get collection statistics resp is nil"

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#19199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master (94da9dcd4)
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.2.0.dev30
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Create index failed reporting "get collection statistics resp is nil"
```
[2022-09-14T06:59:31.781Z] [2022-09-14 06:59:17 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['float_vector', {'index_type': 'IVF_FLAT', 'params': {'nlist': 128}, 'metric_type': 'L2'}], kwargs: {'timeout': 40, 'index_name': '_default_idx'} (api_request.py:56)

[2022-09-14T06:59:31.781Z] [2022-09-14 06:59:19 - ERROR - pymilvus.decorators]: RPC error: [create_index], <MilvusException: (code=1, message=get collection statistics resp is nil)>, <Time:{'RPC start': '2022-09-14 06:59:17.247102', 'RPC error': '2022-09-14 06:59:19.647752'}> (decorators.py:100)

[2022-09-14T06:59:31.781Z] [2022-09-14 06:59:19 - ERROR - ci_test]: Traceback (most recent call last):

[2022-09-14T06:59:31.781Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2022-09-14T06:59:31.781Z]     res = func(*args, **_kwargs)

[2022-09-14T06:59:31.781Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2022-09-14T06:59:31.781Z]     return func(*arg, **kwargs)

[2022-09-14T06:59:31.781Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 1087, in create_index

[2022-09-14T06:59:31.781Z]     timeout=timeout, **kwargs)

[2022-09-14T06:59:31.781Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 101, in handler

[2022-09-14T06:59:31.781Z]     raise e

[2022-09-14T06:59:31.781Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 97, in handler

[2022-09-14T06:59:31.781Z]     return func(*args, **kwargs)

[2022-09-14T06:59:31.781Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 127, in handler

[2022-09-14T06:59:31.781Z]     ret = func(self, *args, **kwargs)

[2022-09-14T06:59:31.781Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 79, in handler

[2022-09-14T06:59:31.781Z]     raise e

[2022-09-14T06:59:31.781Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 50, in handler

[2022-09-14T06:59:31.781Z]     return func(self, *args, **kwargs)

[2022-09-14T06:59:31.781Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 576, in create_index

[2022-09-14T06:59:31.781Z]     raise MilvusException(status.error_code, status.reason)

[2022-09-14T06:59:31.781Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=get collection statistics resp is nil)>

[2022-09-14T06:59:31.781Z]  (api_request.py:39)

[2022-09-14T06:59:31.781Z] [2022-09-14 06:59:19 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=get collection statistics resp is nil)> (api_request.py:40)
```

### Expected Behavior

No error

### Steps To Reproduce

```markdown
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-19193/2/pipeline/
```

### Milvus Log

1. milvus log:
[artifacts-milvus-distributed-PR-19193-2-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20HA%20CI/job/PR-19193/2/artifact/artifacts-milvus-distributed-PR-19193-2-pymilvus-e2e-logs.tar.gz)

2. collection name: search_collection_LUJQYUlS
3. Failed timeline:
[2022-09-14T06:59:28.463Z] [gw5] [ 40%] FAILED testcases/test_search.py::TestCollectionSearchInvalid::test_search_different_index_invalid_params[IVF_FLAT-params0]

**Comment by binbinlv** [comment]
From the error, this issue is the same with #6836. Open this new issue to track in case that the original issue is too old.

**Comment by xiaocai2333** [comment]
same as #19164 ,has been fixed, please verify
/unassign 
/assign @binbinlv

**Comment by binbinlv** [comment]
Fixed and closed.
