### ISSUE TITLE
[Bug]: Release collection timeout after many pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#19233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220916-58d3a49
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/12268675/190560521-5d46f603-f0ff-4cb4-b7f8-7f8eb1181fef.png)

```
2022-09-16T03:50:51.298Z] + pytest -s -v testcases/test_data_persistence.py --host 10.101.184.5 --log-cli-level=INFO --capture=no

[2022-09-16T03:50:54.549Z] [get_env_variable] failed to get environment variables : 'CI_LOG_PATH', use default path : /tmp/ci_logs/

[2022-09-16T03:50:54.549Z] ============================= test session starts ==============================

[2022-09-16T03:50:54.549Z] platform linux -- Python 3.7.3, pytest-6.2.2, py-1.11.0, pluggy-0.13.1 -- /usr/bin/python3

[2022-09-16T03:50:54.549Z] cachedir: .pytest_cache

[2022-09-16T03:50:54.549Z] metadata: {'Python': '3.7.3', 'Platform': 'Linux-4.18.0-372.16.1.el8_6.x86_64-x86_64-with-debian-10.12', 'Packages': {'pytest': '6.2.2', 'py': '1.11.0', 'pluggy': '0.13.1'}, 'Plugins': {'allure-pytest': '2.7.0', 'assume': '2.4.3', 'cov': '2.8.1', 'forked': '1.4.0', 'html': '3.1.1', 'level': '0.1.1', 'metadata': '2.0.1', 'parallel': '0.1.1', 'print': '0.2.1', 'random-order': '1.0.4', 'repeat': '0.8.0', 'reportportal': '5.0.10', 'rerunfailures': '9.1.1', 'tags': '1.7.2', 'timeout': '1.3.3', 'sugar': '0.9.5', 'xdist': '2.5.0'}, 'CI': 'true', 'BUILD_NUMBER': '1266', 'BUILD_ID': '1266', 'BUILD_URL': 'https://qa-jenkins.milvus.io/job/chaos-test/1266/', 'NODE_NAME': 'chaos-test-1266-p5gzl-fcmth-nbw7q', 'JOB_NAME': 'chaos-test', 'BUILD_TAG': 'jenkins-chaos-test-1266', 'EXECUTOR_NUMBER': '0', 'JENKINS_URL': 'https://qa-jenkins.milvus.io/', 'WORKSPACE': '/home/jenkins/agent/workspace', 'GIT_COMMIT': '0f0b1703c4ce370b03115ba849e92157505e5ea8', 'GIT_URL': 'git@github.com:zilliztech/test-jobs.git', 'GIT_BRANCH': 'origin/main'}

[2022-09-16T03:50:54.549Z] Test order randomisation NOT enabled. Enable with --random-order or --random-order-bucket=<bucket_type>

[2022-09-16T03:50:54.549Z] tags: all

[2022-09-16T03:50:54.549Z] rootdir: /home/jenkins/agent/workspace/tests/python_client, configfile: pytest.ini

[2022-09-16T03:50:54.549Z] plugins: allure-pytest-2.7.0, assume-2.4.3, cov-2.8.1, forked-1.4.0, html-3.1.1, level-0.1.1, metadata-2.0.1, parallel-0.1.1, print-0.2.1, random-order-1.0.4, repeat-0.8.0, reportportal-5.0.10, rerunfailures-9.1.1, tags-1.7.2, timeout-1.3.3, sugar-0.9.5, xdist-2.5.0

[2022-09-16T03:50:54.549Z] collecting ... collected 1 item

[2022-09-16T03:50:54.549Z] 
selected 1 items

[2022-09-16T03:50:54.549Z] 

[2022-09-16T03:50:54.549Z] testcases/test_data_persistence.py::TestDataPersistence::test_milvus_default 

[2022-09-16T03:50:54.549Z] -------------------------------- live log setup --------------------------------

[2022-09-16T03:50:54.549Z] [2022-09-16 03:50:53 - INFO - ci_test]: ################################################################################ (conftest.py:189)

[2022-09-16T03:50:54.549Z] [2022-09-16 03:50:53 - INFO - ci_test]: [initialize_milvus] Log cleaned up, start testing... (conftest.py:190)

[2022-09-16T03:50:54.549Z] [2022-09-16 03:50:53 - INFO - ci_test]: [setup_class] Start setup class... (client_base.py:30)

[2022-09-16T03:50:54.549Z] [2022-09-16 03:50:53 - INFO - ci_test]: *********************************** setup *********************************** (client_base.py:36)

[2022-09-16T03:50:54.549Z] [2022-09-16 03:50:53 - INFO - ci_test]: [setup_method] Start setup test case test_milvus_default. (client_base.py:37)

[2022-09-16T03:50:54.549Z] -------------------------------- live log call ---------------------------------

[2022-09-16T03:50:54.549Z] [2022-09-16 03:50:53 - INFO - ci_test]: [test][2022-09-16T03:50:53Z] [0.00265568s] Hello_Milvus flush -> None (wrapper.py:30)

[2022-09-16T03:50:54.549Z] [2022-09-16 03:50:53 - INFO - ci_test]: assert create collection: 0.029094219207763672, init_entities: 6000 (test_data_persistence.py:28)

[2022-09-16T03:50:54.550Z] [2022-09-16 03:50:54 - INFO - ci_test]: [test][2022-09-16T03:50:54Z] [0.37852979s] Hello_Milvus insert -> (insert count: 3000, delete count: 0, upsert count: 0, timestamp: 436024181894152193, success count: 3000, err count: 0) (wrapper.py:30)

[2022-09-16T03:50:54.550Z] [2022-09-16 03:50:54 - INFO - ci_test]: assert insert: 0.37873172760009766 (test_data_persistence.py:35)

[2022-09-16T03:50:57.801Z] [2022-09-16 03:50:57 - INFO - ci_test]: [test][2022-09-16T03:50:54Z] [2.90376290s] Hello_Milvus flush -> None (wrapper.py:30)

[2022-09-16T03:50:57.801Z] [2022-09-16 03:50:57 - INFO - ci_test]: [test][2022-09-16T03:50:57Z] [0.00279894s] Hello_Milvus flush -> None (wrapper.py:30)

[2022-09-16T03:50:57.801Z] [2022-09-16 03:50:57 - INFO - ci_test]: [test][2022-09-16T03:50:57Z] [0.00218254s] Hello_Milvus flush -> None (wrapper.py:30)

[2022-09-16T03:50:57.801Z] [2022-09-16 03:50:57 - INFO - ci_test]: assert flush: 2.908048629760742, entities: 9000 (test_data_persistence.py:45)

[2022-09-16T03:51:03.029Z] [2022-09-16 03:51:02 - INFO - ci_test]: [test][2022-09-16T03:50:57Z] [5.38937144s] Hello_Milvus load -> None (wrapper.py:30)

[2022-09-16T03:51:03.283Z] [2022-09-16 03:51:03 - INFO - ci_test]: [test][2022-09-16T03:51:02Z] [0.34834724s] Hello_Milvus search -> <pymilvus.orm.search.SearchResult object at 0x7f7a72a63b38> (wrapper.py:30)

[2022-09-16T03:51:03.283Z] [2022-09-16 03:51:03 - INFO - ci_test]: assert search: 0.34856200218200684 (test_data_persistence.py:56)

[2022-09-16T03:51:25.252Z] [2022-09-16 03:51:23 - ERROR - pymilvus.decorators]: RPC error: [release_collection], <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)>, <Time:{'RPC start': '2022-09-16 03:51:03.156510', 'RPC error': '2022-09-16 03:51:23.157455'}> (decorators.py:100)

[2022-09-16T03:51:25.252Z] [2022-09-16 03:51:23 - ERROR - ci_test]: Traceback (most recent call last):

[2022-09-16T03:51:25.252Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 50, in handler

[2022-09-16T03:51:25.252Z]     return func(self, *args, **kwargs)

[2022-09-16T03:51:25.252Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 714, in release_collection

[2022-09-16T03:51:25.252Z]     response = rf.result()

[2022-09-16T03:51:25.252Z]   File "/usr/local/lib/python3.7/dist-packages/grpc/_channel.py", line 744, in result

[2022-09-16T03:51:25.252Z]     raise self

[2022-09-16T03:51:25.252Z] grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:

[2022-09-16T03:51:25.252Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2022-09-16T03:51:25.252Z] 	details = "Deadline Exceeded"

[2022-09-16T03:51:25.252Z] 	debug_error_string = "{"created":"@1663300283.157044599","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":81,"grpc_status":4}"

[2022-09-16T03:51:25.252Z] >

[2022-09-16T03:51:25.252Z] 

[2022-09-16T03:51:25.252Z] During handling of the above exception, another exception occurred:

[2022-09-16T03:51:25.252Z] 

[2022-09-16T03:51:25.252Z] Traceback (most recent call last):

[2022-09-16T03:51:25.252Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2022-09-16T03:51:25.252Z]     res = func(*args, **_kwargs)

[2022-09-16T03:51:25.252Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2022-09-16T03:51:25.252Z]     return func(*arg, **kwargs)

[2022-09-16T03:51:25.252Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 501, in release

[2022-09-16T03:51:25.252Z]     conn.release_collection(self._name, timeout=timeout, **kwargs)

[2022-09-16T03:51:25.252Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 101, in handler

[2022-09-16T03:51:25.252Z]     raise e

[2022-09-16T03:51:25.252Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 97, in handler

[2022-09-16T03:51:25.252Z]     return func(*args, **kwargs)

[2022-09-16T03:51:25.252Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 127, in handler

[2022-09-16T03:51:25.252Z]     ret = func(self, *args, **kwargs)

[2022-09-16T03:51:25.252Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 67, in handler

[2022-09-16T03:51:25.252Z]     raise MilvusException(Status.UNEXPECTED_ERROR, f"rpc deadline exceeded: {timeout_msg}")

[2022-09-16T03:51:25.252Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)>

[2022-09-16T03:51:25.252Z]  (api_request.py:39)

[2022-09-16T03:51:25.252Z] [2022-09-16 03:51:23 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)> (api_request.py:40)

[2022-09-16T03:51:25.252Z] FAILED
```

### Expected Behavior

all test cases passed

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/1266/pipeline

log:
[artifacts-querycoord-pod-kill-1266-pytest-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/9580835/artifacts-querycoord-pod-kill-1266-pytest-logs.1.tar.gz)
[artifacts-querycoord-pod-kill-1266-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/9580836/artifacts-querycoord-pod-kill-1266-server-logs.1.tar.gz)

### Anything else?

same as https://github.com/milvus-io/milvus/issues/19232

many other pod chaos tests also have this issue

failed jobs:
querynode: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/1267/pipeline
querycoord:https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/1266/pipeline

**Comment by xiaofan-luan** [comment]
/assign @longjiquan 

pls help on investigate

**Comment by zhuwenxing** [comment]
Almost all pod kill test cases have this issue, I just pick one for the display

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/1563/pipeline/244/
log:
[artifacts-etcd-pod-failure-1563-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9642396/artifacts-etcd-pod-failure-1563-server-logs.tar.gz)
[artifacts-etcd-pod-failure-1563-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9642400/artifacts-etcd-pod-failure-1563-pytest-logs.tar.gz)

Those test cases failed due to release timeout 
```
[2022-09-25T21:46:41.159Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[Checker__1K9ASsh0]
[2022-09-25T21:46:41.159Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[Checker__oZBMMvQQ]
[2022-09-25T21:46:41.159Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[Checker__uyDS6IFp]
[2022-09-25T21:46:41.159Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[Checker__aKubyApi]
```

```
[2022-09-25T21:46:41.148Z] [2022-09-25 21:44:05 - INFO - ci_test]: [test][2022-09-25T21:44:04Z] [0.38347072s] Checker__1K9ASsh0 search -> <pymilvus.orm.search.SearchResult object at 0x7f5585de4860> (wrapper.py:30)
[2022-09-25T21:46:41.148Z] [2022-09-25 21:44:05 - INFO - ci_test]: assert search: 0.38370466232299805 (test_all_collections_after_chaos.py:63)
[2022-09-25T21:46:41.148Z] [2022-09-25 21:44:05 - DEBUG - ci_test]: (api_request)  : [Collection.release] args: [], kwargs: {'timeout': 20} (api_request.py:56)
[2022-09-25T21:46:41.148Z] [2022-09-25 21:44:25 - ERROR - pymilvus.decorators]: RPC error: [release_collection], <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)>, <Time:{'RPC start': '2022-09-25 21:44:05.240041', 'RPC error': '2022-09-25 21:44:25.241415'}> (decorators.py:100)
[2022-09-25T21:46:41.148Z] [2022-09-25 21:44:25 - ERROR - ci_test]: Traceback (most recent call last):
[2022-09-25T21:46:41.148Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 50, in handler
[2022-09-25T21:46:41.148Z]     return func(self, *args, **kwargs)
[2022-09-25T21:46:41.148Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 714, in release_collection
[2022-09-25T21:46:41.148Z]     response = rf.result()
[2022-09-25T21:46:41.148Z]   File "/usr/local/lib/python3.7/dist-packages/grpc/_channel.py", line 744, in result
[2022-09-25T21:46:41.148Z]     raise self
[2022-09-25T21:46:41.148Z] grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
[2022-09-25T21:46:41.148Z] 	status = StatusCode.DEADLINE_EXCEEDED
[2022-09-25T21:46:41.148Z] 	details = "Deadline Exceeded"
[2022-09-25T21:46:41.148Z] 	debug_error_string = "{"created":"@1664142265.241033049","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":81,"grpc_status":4}"
[2022-09-25T21:46:41.148Z] >
[2022-09-25T21:46:41.148Z] 
[2022-09-25T21:46:41.148Z] During handling of the above exception, another exception occurred:
[2022-09-25T21:46:41.148Z] 
[2022-09-25T21:46:41.148Z] Traceback (most recent call last):
[2022-09-25T21:46:41.148Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2022-09-25T21:46:41.148Z]     res = func(*args, **_kwargs)
[2022-09-25T21:46:41.148Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2022-09-25T21:46:41.148Z]     return func(*arg, **kwargs)
[2022-09-25T21:46:41.148Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 501, in release
[2022-09-25T21:46:41.148Z]     conn.release_collection(self._name, timeout=timeout, **kwargs)
[2022-09-25T21:46:41.148Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 101, in handler
[2022-09-25T21:46:41.148Z]     raise e
[2022-09-25T21:46:41.148Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 97, in handler
[2022-09-25T21:46:41.148Z]     return func(*args, **kwargs)
[2022-09-25T21:46:41.148Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 127, in handler
[2022-09-25T21:46:41.148Z]     ret = func(self, *args, **kwargs)
[2022-09-25T21:46:41.148Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 67, in handler
[2022-09-25T21:46:41.148Z]     raise MilvusException(Status.UNEXPECTED_ERROR, f"rpc deadline exceeded: {timeout_msg}")
[2022-09-25T21:46:41.148Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)>
[2022-09-25T21:46:41.148Z]  (api_request.py:39)
[2022-09-25T21:46:41.148Z] [2022-09-25 21:44:25 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)>
```

**Comment by longjiquan** [comment]
![image](https://user-images.githubusercontent.com/31589260/193249754-ed94acc2-b7bc-4d47-941c-0c7141a5aa84.png)

![image](https://user-images.githubusercontent.com/31589260/193249856-28c12fb2-da9d-4881-ac24-50e10baf794a.png)

**Comment by longjiquan** [comment]
`ReleaseCollection` wait until all segments released, and the time of this process exceeds `30s`.

**Comment by longjiquan** [comment]
finding why...

**Comment by longjiquan** [comment]
#19513 may already fix this issue. Please help to reproduce this again, thx @zhuwenxing 
/assign @zhuwenxing

**Comment by zhuwenxing** [comment]
Not reproduced
