### ISSUE TITLE
[Bug]: querycoordv2 crashed with painc "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#19236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master (18817a4)
- Deployment mode(standalone or cluster): both (standalone, cluster)
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

querycoordv2 crashed with painc "invalid memory address or nil pointer dereference"
```
2022-09-16T04:04:59.323890977+08:00 stdout F [2022/09/15 20:04:59.323 +00:00] [INFO] [observers/collection_observer.go:139] ["collection targets"] [collectionID=436016321950534293] [segment-target-num=4] [channel-target-num=2] [total-target-num=6]
2022-09-16T04:04:59.323985134+08:00 stdout F [2022/09/15 20:04:59.323 +00:00] [INFO] [observers/collection_observer.go:167] ["collection load progress"] [collectionID=436016321950534293] [sub-channel-count=2] [load-segment-count=0]
2022-09-16T04:04:59.324071572+08:00 stdout F [2022/09/15 20:04:59.324 +00:00] [INFO] [observers/collection_observer.go:139] ["collection targets"] [collectionID=436016321950534686] [segment-target-num=0] [channel-target-num=128] [total-target-num=128]
2022-09-16T04:04:59.324363149+08:00 stdout F [2022/09/15 20:04:59.324 +00:00] [INFO] [observers/collection_observer.go:167] ["collection load progress"] [collectionID=436016321950534686] [sub-channel-count=126] [load-segment-count=0]
2022-09-16T04:04:59.324383879+08:00 stdout F [2022/09/15 20:04:59.324 +00:00] [INFO] [observers/collection_observer.go:185] ["collection load status updated"] [collectionID=436016321950534686] [loadPercentage=98] [collectionStatus=1]
2022-09-16T04:04:59.327693302+08:00 stderr F panic: runtime error: invalid memory address or nil pointer dereference
2022-09-16T04:04:59.32771444+08:00 stderr F [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1ca4d75]
2022-09-16T04:04:59.327721733+08:00 stderr F
2022-09-16T04:04:59.327729129+08:00 stderr F goroutine 1078 [running]:
2022-09-16T04:04:59.327744677+08:00 stderr F github.com/milvus-io/milvus/internal/querycoordv2/checkers.(*SegmentChecker).findNeedReleasedGrowingSegments(0xc00219f020, 0x2ff1bf8?)
2022-09-16T04:04:59.327754502+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/querycoordv2/checkers/segment_checker.go:170 +0xf5
2022-09-16T04:04:59.327768288+08:00 stderr F github.com/milvus-io/milvus/internal/querycoordv2/checkers.(*SegmentChecker).checkReplica(0xc00219f020, {0x2ff1bf8, 0xc000fff540}, 0xc00fa417f0)
2022-09-16T04:04:59.327777293+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/querycoordv2/checkers/segment_checker.go:79 +0x405
2022-09-16T04:04:59.327785119+08:00 stderr F github.com/milvus-io/milvus/internal/querycoordv2/checkers.(*SegmentChecker).Check(0xc00219f020, {0x2ff1bf8, 0xc000fff540})
2022-09-16T04:04:59.32779908+08:00 stderr F     /go/src/github.com/milvus-io/milvus/internal/querycoordv2/checkers/segment_checker.go:48 +0x2f4
2022-09-16T04:04:59.32780736+08:00 stderr F github.com/milvus-io/milvus/internal/querycoordv2/checkers.(*CheckerController).check(0xc000242a10, {0x2ff1bf8, 0xc000fff540})
2022-09-16T04:04:59.327827983+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/querycoordv2/checkers/controller.go:92 +0x230
2022-09-16T04:04:59.327837438+08:00 stderr F github.com/milvus-io/milvus/internal/querycoordv2/checkers.(*CheckerController).Start.func1()
2022-09-16T04:04:59.327844322+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/querycoordv2/checkers/controller.go:76 +0xa9
2022-09-16T04:04:59.327869703+08:00 stderr F created by github.com/milvus-io/milvus/internal/querycoordv2/checkers.(*CheckerController).Start
2022-09-16T04:04:59.327884806+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/querycoordv2/checkers/controller.go:62 +0x8a
```

### Expected Behavior

No error

### Steps To Reproduce

```markdown
Nightly:
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/101/pipeline/135
```

### Milvus Log

[artifacts-milvus-standalone-nightly-101-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/101/artifact/artifacts-milvus-standalone-nightly-101-pymilvus-e2e-logs.tar.gz)

**Comment by NicoYuan1986** [comment]
This issue no longer occurs in master(a8cabbf).
