### ISSUE TITLE
[Bug]: Loading collection timeout after many pod kill chaos test in master branch

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#19232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220916-58d3a49
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/12268675/190559445-a07be4c9-c591-4568-8b90-5cb09a4cde9c.png)

```
[2022-09-16T03:50:51.033Z] + pytest -s -v ../testcases/test_e2e.py --host 10.101.184.5 --log-cli-level=INFO --capture=no

[2022-09-16T03:50:54.287Z] [get_env_variable] failed to get environment variables : 'CI_LOG_PATH', use default path : /tmp/ci_logs/

[2022-09-16T03:50:54.287Z] ============================= test session starts ==============================

[2022-09-16T03:50:54.287Z] platform linux -- Python 3.7.3, pytest-6.2.2, py-1.11.0, pluggy-0.13.1 -- /usr/bin/python3

[2022-09-16T03:50:54.287Z] cachedir: .pytest_cache

[2022-09-16T03:50:54.287Z] metadata: {'Python': '3.7.3', 'Platform': 'Linux-4.18.0-372.16.1.el8_6.x86_64-x86_64-with-debian-10.12', 'Packages': {'pytest': '6.2.2', 'py': '1.11.0', 'pluggy': '0.13.1'}, 'Plugins': {'allure-pytest': '2.7.0', 'assume': '2.4.3', 'cov': '2.8.1', 'forked': '1.4.0', 'html': '3.1.1', 'level': '0.1.1', 'metadata': '2.0.1', 'parallel': '0.1.1', 'print': '0.2.1', 'random-order': '1.0.4', 'repeat': '0.8.0', 'reportportal': '5.0.10', 'rerunfailures': '9.1.1', 'tags': '1.7.2', 'timeout': '1.3.3', 'sugar': '0.9.5', 'xdist': '2.5.0'}, 'CI': 'true', 'BUILD_NUMBER': '1266', 'BUILD_ID': '1266', 'BUILD_URL': 'https://qa-jenkins.milvus.io/job/chaos-test/1266/', 'NODE_NAME': 'chaos-test-1266-p5gzl-fcmth-nbw7q', 'JOB_NAME': 'chaos-test', 'BUILD_TAG': 'jenkins-chaos-test-1266', 'EXECUTOR_NUMBER': '0', 'JENKINS_URL': 'https://qa-jenkins.milvus.io/', 'WORKSPACE': '/home/jenkins/agent/workspace', 'GIT_COMMIT': '0f0b1703c4ce370b03115ba849e92157505e5ea8', 'GIT_URL': 'git@github.com:zilliztech/test-jobs.git', 'GIT_BRANCH': 'origin/main'}

[2022-09-16T03:50:54.287Z] Test order randomisation NOT enabled. Enable with --random-order or --random-order-bucket=<bucket_type>

[2022-09-16T03:50:54.287Z] tags: all

[2022-09-16T03:50:54.287Z] rootdir: /home/jenkins/agent/workspace/tests/python_client, configfile: pytest.ini

[2022-09-16T03:50:54.287Z] plugins: allure-pytest-2.7.0, assume-2.4.3, cov-2.8.1, forked-1.4.0, html-3.1.1, level-0.1.1, metadata-2.0.1, parallel-0.1.1, print-0.2.1, random-order-1.0.4, repeat-0.8.0, reportportal-5.0.10, rerunfailures-9.1.1, tags-1.7.2, timeout-1.3.3, sugar-0.9.5, xdist-2.5.0

[2022-09-16T03:50:54.287Z] collecting ... collected 1 item

[2022-09-16T03:50:54.287Z] 
selected 1 items

[2022-09-16T03:50:54.287Z] 

[2022-09-16T03:50:54.287Z] ../testcases/test_e2e.py::TestE2e::test_milvus_default 

[2022-09-16T03:50:54.287Z] -------------------------------- live log setup --------------------------------

[2022-09-16T03:50:54.287Z] [2022-09-16 03:50:53 - INFO - ci_test]: ################################################################################ (conftest.py:189)

[2022-09-16T03:50:54.287Z] [2022-09-16 03:50:53 - INFO - ci_test]: [initialize_milvus] Log cleaned up, start testing... (conftest.py:190)

[2022-09-16T03:50:54.287Z] [2022-09-16 03:50:53 - INFO - ci_test]: [setup_class] Start setup class... (client_base.py:30)

[2022-09-16T03:50:54.287Z] [2022-09-16 03:50:53 - INFO - ci_test]: *********************************** setup *********************************** (client_base.py:36)

[2022-09-16T03:50:54.287Z] [2022-09-16 03:50:53 - INFO - ci_test]: [setup_method] Start setup test case test_milvus_default. (client_base.py:37)

[2022-09-16T03:50:54.287Z] -------------------------------- live log call ---------------------------------

[2022-09-16T03:50:54.287Z] [2022-09-16 03:50:53 - INFO - ci_test]: [test][2022-09-16T03:50:53Z] [0.00347669s] e2e__kHSiMM0x flush -> None (wrapper.py:30)

[2022-09-16T03:50:54.287Z] [2022-09-16 03:50:53 - INFO - ci_test]: assert create collection: 0.3449833393096924, init_entities: 0 (test_e2e.py:24)

[2022-09-16T03:50:55.209Z] [2022-09-16 03:50:54 - INFO - ci_test]: [test][2022-09-16T03:50:54Z] [0.82055644s] e2e__kHSiMM0x insert -> (insert count: 3000, delete count: 0, upsert count: 0, timestamp: 436024181907259393, success count: 3000, err count: 0) (wrapper.py:30)

[2022-09-16T03:50:55.210Z] [2022-09-16 03:50:54 - INFO - ci_test]: assert insert: 0.8208045959472656 (test_e2e.py:31)

[2022-09-16T03:50:57.714Z] [2022-09-16 03:50:57 - INFO - ci_test]: [test][2022-09-16T03:50:54Z] [2.51318009s] e2e__kHSiMM0x flush -> None (wrapper.py:30)

[2022-09-16T03:51:02.941Z] [2022-09-16 03:51:02 - INFO - ci_test]: [test][2022-09-16T03:50:57Z] [4.94468727s] e2e__kHSiMM0x flush -> None (wrapper.py:30)

[2022-09-16T03:51:02.941Z] [2022-09-16 03:51:02 - INFO - ci_test]: [test][2022-09-16T03:51:02Z] [0.00282986s] e2e__kHSiMM0x flush -> None (wrapper.py:30)

[2022-09-16T03:51:02.941Z] [2022-09-16 03:51:02 - INFO - ci_test]: assert flush: 7.83605170249939, entities: 3000 (test_e2e.py:41)

[2022-09-16T03:51:24.831Z] [2022-09-16 03:51:24 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=-1, message=wait for loading collection timeout)>, <Time:{'RPC start': '2022-09-16 03:51:02.817745', 'RPC error': '2022-09-16 03:51:24.066693'}> (decorators.py:100)

[2022-09-16T03:51:24.831Z] [2022-09-16 03:51:24 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=-1, message=wait for loading collection timeout)>, <Time:{'RPC start': '2022-09-16 03:51:02.811977', 'RPC error': '2022-09-16 03:51:24.067074'}> (decorators.py:100)

[2022-09-16T03:51:24.831Z] [2022-09-16 03:51:24 - ERROR - ci_test]: Traceback (most recent call last):

[2022-09-16T03:51:24.831Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2022-09-16T03:51:24.831Z]     res = func(*args, **_kwargs)

[2022-09-16T03:51:24.831Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2022-09-16T03:51:24.831Z]     return func(*arg, **kwargs)

[2022-09-16T03:51:24.831Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 474, in load

[2022-09-16T03:51:24.831Z]     conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)

[2022-09-16T03:51:24.831Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 101, in handler

[2022-09-16T03:51:24.831Z]     raise e

[2022-09-16T03:51:24.831Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 97, in handler

[2022-09-16T03:51:24.831Z]     return func(*args, **kwargs)

[2022-09-16T03:51:24.831Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 127, in handler

[2022-09-16T03:51:24.831Z]     ret = func(self, *args, **kwargs)

[2022-09-16T03:51:24.831Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 79, in handler

[2022-09-16T03:51:24.831Z]     raise e

[2022-09-16T03:51:24.831Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 50, in handler

[2022-09-16T03:51:24.831Z]     return func(self, *args, **kwargs)

[2022-09-16T03:51:24.831Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 664, in load_collection

[2022-09-16T03:51:24.832Z]     self.wait_for_loading_collection(collection_name, timeout)

[2022-09-16T03:51:24.832Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 101, in handler

[2022-09-16T03:51:24.832Z]     raise e

[2022-09-16T03:51:24.832Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 97, in handler

[2022-09-16T03:51:24.832Z]     return func(*args, **kwargs)

[2022-09-16T03:51:24.832Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 127, in handler

[2022-09-16T03:51:24.832Z]     ret = func(self, *args, **kwargs)

[2022-09-16T03:51:24.832Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 79, in handler

[2022-09-16T03:51:24.832Z]     raise e

[2022-09-16T03:51:24.832Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 50, in handler

[2022-09-16T03:51:24.832Z]     return func(self, *args, **kwargs)

[2022-09-16T03:51:24.832Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 673, in wait_for_loading_collection

[2022-09-16T03:51:24.832Z]     return self._wait_for_loading_collection(collection_name, timeout)

[2022-09-16T03:51:24.832Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 707, in _wait_for_loading_collection

[2022-09-16T03:51:24.832Z]     raise MilvusException(-1, "wait for loading collection timeout")

[2022-09-16T03:51:24.832Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=-1, message=wait for loading collection timeout)>

[2022-09-16T03:51:24.832Z]  (api_request.py:39)

[2022-09-16T03:51:24.832Z] [2022-09-16 03:51:24 - ERROR - ci_test]: (api_response) : <MilvusException: (code=-1, message=wait for loading collection timeout)> (api_request.py:40)

[2022-09-16T03:51:24.832Z] FAILED
```

### Expected Behavior

all test cases passed

### Milvus Log

chaos type: pod-kill image tag: master-20220916-58d3a49 target pod: querycoord
failed job:https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/1266/pipeline

[artifacts-querycoord-pod-kill-1266-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9580795/artifacts-querycoord-pod-kill-1266-pytest-logs.tar.gz)
[artifacts-querycoord-pod-kill-1266-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9580796/artifacts-querycoord-pod-kill-1266-server-logs.tar.gz)

### Anything else?

Only etcd and standalone passed the pod kill chaos test, other components all failed.

some other failed jobs:
rootcoord:  https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/1268/pipeline/
querynode: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/1267/pipeline
pulsar: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/1265/pipeline
.....

**Comment by zhuwenxing** [comment]
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/1563/pipeline/244/
log:
[artifacts-etcd-pod-failure-1563-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9642396/artifacts-etcd-pod-failure-1563-server-logs.tar.gz)
[artifacts-etcd-pod-failure-1563-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9642400/artifacts-etcd-pod-failure-1563-pytest-logs.tar.gz)

```
[2022-09-25T21:46:41.159Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[FlushChecker__8eoxGCZL]
[2022-09-25T21:46:41.159Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[InsertChecker__Vp8sGxDV]
[2022-09-25T21:46:41.159Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[Checker__Ui9bM7Fh]
```



Those three cases failed due to loading collection timeout

```
[2022-09-25T21:46:41.158Z] [2022-09-25 21:45:46 - INFO - ci_test]: assert index: 6.082829236984253 (test_all_collections_after_chaos.py:77)

[2022-09-25T21:46:41.158Z] [2022-09-25 21:45:46 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 20], kwargs: {} (api_request.py:56)

[2022-09-25T21:46:41.158Z] [2022-09-25 21:46:08 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=-1, message=wait for loading collection timeout)>, <Time:{'RPC start': '2022-09-25 21:45:47.401513', 'RPC error': '2022-09-25 21:46:08.477280'}> (decorators.py:100)

[2022-09-25T21:46:41.158Z] [2022-09-25 21:46:08 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=-1, message=wait for loading collection timeout)>, <Time:{'RPC start': '2022-09-25 21:45:46.864237', 'RPC error': '2022-09-25 21:46:08.477580'}> (decorators.py:100)

[2022-09-25T21:46:41.159Z] [2022-09-25 21:46:08 - ERROR - ci_test]: Traceback (most recent call last):

[2022-09-25T21:46:41.159Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2022-09-25T21:46:41.159Z]     res = func(*args, **_kwargs)

[2022-09-25T21:46:41.159Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2022-09-25T21:46:41.159Z]     return func(*arg, **kwargs)

[2022-09-25T21:46:41.159Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 474, in load

[2022-09-25T21:46:41.159Z]     conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)

[2022-09-25T21:46:41.159Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 101, in handler

[2022-09-25T21:46:41.159Z]     raise e

[2022-09-25T21:46:41.159Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 97, in handler

[2022-09-25T21:46:41.159Z]     return func(*args, **kwargs)

[2022-09-25T21:46:41.159Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 127, in handler

[2022-09-25T21:46:41.159Z]     ret = func(self, *args, **kwargs)

[2022-09-25T21:46:41.159Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 79, in handler

[2022-09-25T21:46:41.159Z]     raise e

[2022-09-25T21:46:41.159Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 50, in handler

[2022-09-25T21:46:41.159Z]     return func(self, *args, **kwargs)

[2022-09-25T21:46:41.159Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 664, in load_collection

[2022-09-25T21:46:41.159Z]     self.wait_for_loading_collection(collection_name, timeout)

[2022-09-25T21:46:41.159Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 101, in handler

[2022-09-25T21:46:41.159Z]     raise e

[2022-09-25T21:46:41.159Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 97, in handler

[2022-09-25T21:46:41.159Z]     return func(*args, **kwargs)

[2022-09-25T21:46:41.159Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 127, in handler

[2022-09-25T21:46:41.159Z]     ret = func(self, *args, **kwargs)

[2022-09-25T21:46:41.159Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 79, in handler

[2022-09-25T21:46:41.159Z]     raise e

[2022-09-25T21:46:41.159Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 50, in handler

[2022-09-25T21:46:41.159Z]     return func(self, *args, **kwargs)

[2022-09-25T21:46:41.159Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 673, in wait_for_loading_collection

[2022-09-25T21:46:41.159Z]     return self._wait_for_loading_collection(collection_name, timeout)

[2022-09-25T21:46:41.159Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 707, in _wait_for_loading_collection

[2022-09-25T21:46:41.159Z]     raise MilvusException(-1, "wait for loading collection timeout")

[2022-09-25T21:46:41.159Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=-1, message=wait for loading collection timeout)>

[2022-09-25T21:46:41.159Z]  (api_request.py:39)

[2022-09-25T21:46:41.159Z] [2022-09-25 21:46:08 - ERROR - ci_test]: (api_response) : <MilvusException: (code=-1, message=wait for loading collection timeout)> (api_request.py:40)
```

**Comment by yah01** [comment]
/assign @zhuwenxing 
I just run a chaos test, and this error no longer occurs, should have been fixed

**Comment by zhuwenxing** [comment]
Not reproduced, so close it!
