### ISSUE TITLE
[Bug]: Search failed with error `ShardCluster for by-dev-rootcoord-dml_xxx replicaID xxx is no available` after pulsar pod failure chaos test in 2.1 branch 

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#19269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.0-20220916-3c3ba55c 
- Deployment mode(standalone or cluster): cluster 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```

[2022-09-18T14:52:54.349Z] [2022-09-18 14:52:54 - INFO - ci_test]: assert flush: 3.0225107669830322, entities: 36970 (test_all_collections_after_chaos.py:52)

[2022-09-18T14:52:54.349Z] [2022-09-18 14:52:54 - INFO - ci_test]: [test][2022-09-18T14:52:54Z] [0.00424329s] Checker__2hVc7Dez load -> None (wrapper.py:30)

[2022-09-18T14:52:54.349Z] [2022-09-18 14:52:54 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=7, reason=ShardCluster for by-dev-rootcoord-dml_9_436079744828309505v1 replicaID 436079731111624768 is no available)>, <Time:{'RPC start': '2022-09-18 14:52:54.023798', 'RPC error': '2022-09-18 14:52:54.026139'}> (decorators.py:100)

[2022-09-18T14:52:54.349Z] [2022-09-18 14:52:54 - ERROR - ci_test]: Traceback (most recent call last):

[2022-09-18T14:52:54.349Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2022-09-18T14:52:54.349Z]     res = func(*args, **_kwargs)

[2022-09-18T14:52:54.349Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2022-09-18T14:52:54.349Z]     return func(*arg, **kwargs)

[2022-09-18T14:52:54.349Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 718, in search

[2022-09-18T14:52:54.349Z]     partition_names, output_fields, round_decimal, timeout=timeout, schema=schema_dict, **kwargs)

[2022-09-18T14:52:54.349Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 101, in handler

[2022-09-18T14:52:54.349Z]     raise e

[2022-09-18T14:52:54.349Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 97, in handler

[2022-09-18T14:52:54.349Z]     return func(*args, **kwargs)

[2022-09-18T14:52:54.349Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 127, in handler

[2022-09-18T14:52:54.349Z]     ret = func(self, *args, **kwargs)

[2022-09-18T14:52:54.349Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 79, in handler

[2022-09-18T14:52:54.349Z]     raise e

[2022-09-18T14:52:54.349Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 50, in handler

[2022-09-18T14:52:54.349Z]     return func(self, *args, **kwargs)

[2022-09-18T14:52:54.349Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 472, in search

[2022-09-18T14:52:54.349Z]     return self._execute_search_requests(requests, timeout, **_kwargs)

[2022-09-18T14:52:54.349Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 436, in _execute_search_requests

[2022-09-18T14:52:54.349Z]     raise pre_err

[2022-09-18T14:52:54.349Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 427, in _execute_search_requests

[2022-09-18T14:52:54.349Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2022-09-18T14:52:54.349Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=7, reason=ShardCluster for by-dev-rootcoord-dml_9_436079744828309505v1 replicaID 436079731111624768 is no available)>

[2022-09-18T14:52:54.349Z]  (api_request.py:39)

[2022-09-18T14:52:54.349Z] [2022-09-18 14:52:54 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=7, reason=ShardCluster for by-dev-rootcoord-dml_9_436079744828309505v1 replicaID 436079731111624768 is no available)> (api_request.py:40)

[2022-09-18T14:52:54.349Z] FAILED
```

### Expected Behavior

all test cases passed

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-for-release/detail/chaos-test-for-release/649/pipeline

log:
[artifacts-pulsar-pod-failure-649-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9596186/artifacts-pulsar-pod-failure-649-server-logs.tar.gz)
[artifacts-pulsar-pod-failure-649-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9596187/artifacts-pulsar-pod-failure-649-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-for-release/detail/chaos-test-for-release/702/pipeline
log:
[artifacts-pulsar-pod-failure-702-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9606820/artifacts-pulsar-pod-failure-702-pytest-logs.tar.gz)
[artifacts-pulsar-pod-failure-702-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9606822/artifacts-pulsar-pod-failure-702-server-logs.tar.gz)

**Comment by zhuwenxing** [comment]
It reproduced stable, so set it as critical
chaos type: pod-failure image tag: 2.1.0-20220922-4798fa78 target pod: pulsar
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-for-release/detail/chaos-test-for-release/799/pipeline/244

collection name: `Checker__lJBSIpje`
log:
[artifacts-pulsar-pod-failure-799-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9632052/artifacts-pulsar-pod-failure-799-pytest-logs.tar.gz)
[artifacts-pulsar-pod-failure-799-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9632055/artifacts-pulsar-pod-failure-799-server-logs.tar.gz)

**Comment by zhuwenxing** [comment]
Though it still reproduced in 2.1, but it was fixed in master, so close it
