### ISSUE TITLE
[Bug]: Cannot create binary_vector collections whose dimensions are not multiples of 8

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#19321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.2.dev2
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2022-09-21 03:39:32 -  INFO - fouram]: [Base] Create collection fouram_n7Qn0Kss (base.py:59)
[2022-09-21 03:39:32 - DEBUG - fouram]: (api_request)  : [Collection] args: ['fouram_n7Qn0Kss', {
  auto_id: False
  description: 
  fields: [{
    name: id
    description: 
    type: 5
    is_primary: True
    auto_id: False
  }, {
    name: binary_vector
    description: 
    type: 100
    params: {'dim': 27983}
  }]
}, 'default', 2], kwargs: {'dim': 27983, 'consistency_level': 'Strong'} (api_request.py:53)
[2022-09-21 03:39:32 - ERROR - fouram]: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 92, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 48, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 196, in create_collection
    LOGGER.error(status)
  File "/usr/lib/python3.8/logging/__init__.py", line 1463, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1577, in _log
    self.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1587, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1649, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/usr/local/lib/python3.8/dist-packages/_pytest/logging.py", line 331, in emit
    super().emit(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.8/dist-packages/_pytest/logging.py", line 92, in format
    return super().format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 667, in format
    s = self.formatMessage(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 636, in formatMessage
    return self._style.format(record)
  File "/usr/local/lib/python3.8/dist-packages/_pytest/logging.py", line 190, in format
    return self._fmt % record.__dict__
KeyError: 'fn'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/src/fouram/client/util/api_request.py", line 21, in inner_wrapper
    res = func(*args, **kwargs)
  File "/src/fouram/client/util/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 138, in __init__
    conn.create_collection(self._name, fields=schema.to_dict(), shards_num=self._shards_num,
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 107, in handler
    LOGGER.error(f"Unexcepted error: [{inner_name}], {e}, <Time: {record_dict}>")
  File "/usr/lib/python3.8/logging/__init__.py", line 1463, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1577, in _log
    self.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1587, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1649, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/usr/local/lib/python3.8/dist-packages/_pytest/logging.py", line 331, in emit
    super().emit(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.8/dist-packages/_pytest/logging.py", line 92, in format
    return super().format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 667, in format
    s = self.formatMessage(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 636, in formatMessage
    return self._style.format(record)
  File "/usr/local/lib/python3.8/dist-packages/_pytest/logging.py", line 190, in format
    return self._fmt % record.__dict__
KeyError: 'fn'
 (api_request.py:35)
[2022-09-21 03:39:32 - ERROR - fouram]: (api_response) : 'fn' (api_request.py:36)
[2022-09-21 03:39:32 - ERROR - fouram]: [CheckFunc] Request check failed, response:'fn' (func_check.py:40)
```

**Comment by XuanYang-cn** [comment]
pymilvus-2.2.0.dev33 Please use this PyMilvus, which will raise a proper exception

**Comment by jiaoew1991** [comment]
After discussed with @cydrain you can padding 0 at end to make dimension is multiples of 8, there will be affect to the correctness and recall

**Comment by yanliang567** [comment]
> @wangting0128 , After discussed with @cydrain you can padding 0 at end to make dimension is multiples of 8, there will be affect to the correctness and recall

can we offer a better solution without correctness affection?
