### ISSUE TITLE
[Bug]: Search get empty result after upgrading from v2.1.2 to master-20220921-42d371fd

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#19337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.1.2 --> master-20220921-42d371fd
- Deployment mode(standalone or cluster): standalone and cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

collection name: `sift_128_euclidean`

```
[2022-09-21T08:16:13.225Z] + python3 scripts/second_recall_test.py --host 10.101.159.212

[2022-09-21T08:16:15.105Z] 

[2022-09-21T08:16:15.105Z] Search...

[2022-09-21T08:16:15.105Z] search cost  0.2229 seconds

[2022-09-21T08:16:15.105Z] Traceback (most recent call last):

[2022-09-21T08:16:15.105Z]   File "scripts/second_recall_test.py", line 64, in <module>

[2022-09-21T08:16:15.105Z]     search_test(host)

[2022-09-21T08:16:15.105Z]   File "scripts/second_recall_test.py", line 50, in search_test

[2022-09-21T08:16:15.105Z]     assert len(item) == len(true_ids[index]), f"get {len(item)} but expect {len(true_ids[index])}"

[2022-09-21T08:16:15.105Z] AssertionError: get 0 but expect 100

script returned exit code 1
```

### Expected Behavior

all test cases passed

### Milvus Log

deploy task: upgrade old image tag: v2.1.2 new image tag: master-latest
failed job:  https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test/detail/deploy_test/276/pipeline
log:

[artifacts-standalone-upgrade-276-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9614975/artifacts-standalone-upgrade-276-pytest-logs.tar.gz)
[artifacts-standalone-upgrade-276-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9614976/artifacts-standalone-upgrade-276-server-logs.tar.gz)

**Comment by zhuwenxing** [comment]
It reproduced stable, so set is as critical!

**Comment by zhuwenxing** [comment]
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test/detail/deploy_test/284/pipeline/293
log:
[artifacts-cluster-upgrade-284-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9632198/artifacts-cluster-upgrade-284-server-logs.tar.gz)
[artifacts-cluster-upgrade-284-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9632199/artifacts-cluster-upgrade-284-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
It works well when upgrading v2.1.2 to master-20220925-91df8f2d, no idea which PR has fixed this.
But there is one thing strange, in the second recall test, the recall becomes 1.0 which was 0.98 before 

Corresponding test job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test/detail/deploy_test/298/pipeline/293
