### ISSUE TITLE
[Bug]: [Nightly] Cases failed for 'Deadline Exceeded' get much more these days

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#19385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:5f02f09
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0.dev30
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

There are two kinds of error messages:
1.
```
<MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)>
```
2.
```
[2022-09-22T18:41:41.350Z] [2022-09-22 15:33:46 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
[2022-09-22T18:41:41.350Z] 	status = StatusCode.DEADLINE_EXCEEDED
[2022-09-22T18:41:41.350Z] 	details = "Deadline Exceeded"
[2022-09-22T18:41:41.350Z] 	debug_error_string = "{"created":"@1663860826.460754424","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":81,"grpc_status":4}"
```

### Expected Behavior

PASS

### Steps To Reproduce

```markdown
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/114/pipeline/143/
```

### Milvus Log

1. milvus log: [artifacts-milvus-distributed-kafka-nightly-114-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/114/artifact/artifacts-milvus-distributed-kafka-nightly-114-pymilvus-e2e-logs.tar.gz)
2. Cases failed for error message 1:
```
test_search.py::TestCollectionSearchInvalid::test_search_with_expression_join_two_fields[int64_1 * int64_2 == 8]
test_query.py::TestQueryOperation::test_query_expr_single_term_array[int64 in [0]]
test_search.py::TestCollectionSearch::test_search_normal_default_params[8-True-False-search_params0]
test_search.py::TestCollectionSearch::test_search_load_flush_load[5000-2-128-True-False]
test_search.py::TestCollectionSearchInvalid::test_search_param_invalid_expr_bool[get_invalid_expr_bool_value0]
test_search.py::TestCollectionSearch::test_search_after_different_index_with_params[8-True-True-ANNOY-params5]
```
3. Cases failed for error message 2:
```
test_search.py::TestCollectionSearch::test_search_normal_default_params[8-False-True-search_params0]
test_search.py::TestCollectionSearch::test_search_normal_default_params[8-True-False-search_params2]
test_search.py::TestCollectionSearch::test_search_normal[2-8-True-False]
test_query.py::TestQueryOperation::test_query_after_search
test_search.py::TestCollectionSearch::test_search_HNSW_index_with_max_ef[False-False-8-4]
test_search.py::TestCollectionSearch::test_search_normal_default_params[128-False-False-search_params0]
test_search.py::TestCollectionSearch::test_search_after_index_different_metric_type[128-True-False-IVF_FLAT-params1]
test_search.py::TestCollectionSearch::test_search_index_partitions[3000-500-128-False-True]
test_search.py::TestCollectionSearch::test_search_collection_after_release_load[3000-2-8-False-False]
```

**Comment by binbinlv** [comment]
/assign @jaime0815 
@jaime0815 
This issue appears in the kafka pipeline only yesterday, so could you please have a look first?
Thanks.

**Comment by jaime0815** [comment]
Some issues have already been fixed,  can you update the latest test results here? I will track this issue continually.

**Comment by NicoYuan1986** [comment]
This issue also starts to appear in pulsar and standalone.
Here is the information about error message 1 mentioned above.
1. failed cases in https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/124/ :
```
[2022-09-27T16:06:11.775Z] [gw4] [ 49%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_with_hit_vectors[500-128-False]
[2022-09-27T16:10:30.442Z] [gw1] [ 50%] FAILED testcases/test_query.py::TestqueryString::test_query_string_is_primary[(varchar > "0" && varchar < "100") or (varchar > "200" && varchar < "300")]
[2022-09-27T16:15:25.244Z] [gw0] [ 51%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_after_index_different_metric_type[8-True-True-FLAT-params0]
```
There are more examples in 125.
2. Take one for example: [2022-09-27T16:06:11.775Z] [gw4] [ 49%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_with_hit_vectors[500-128-False]
3. collection name: search_collection_x3GZTAhj
4. Detailed error information: 
```
[2022-09-27 16:06:01,742 - ERROR - ci_test]: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 884, in flush
    response = future.result()
  File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "{"created":"@1664294761.740735459","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":81,"grpc_status":4}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 408, in flush
    conn.flush([self.name], timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 113, in handler
    raise e
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 139, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 65, in handler
    raise MilvusException(Status.UNEXPECTED_ERROR, f"rpc deadline exceeded: {timeout_msg}")
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)>
 (api_request.py:39)
[2022-09-27 16:06:01,742 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)> (api_request.py:40)
```

**Comment by NicoYuan1986** [comment]
Here is the information about error message 2 mentioned above.
1. failed cases in https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/124/ :
```
[2022-09-27T16:06:03.703Z] [gw0] [ 49%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_after_index_different_metric_type[8-False-True-ANNOY-params5]
[2022-09-27T16:07:45.873Z] [gw0] [ 50%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_after_index_different_metric_type[8-True-False-FLAT-params0]
[2022-09-27T16:07:56.708Z] [gw3] [ 50%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_HNSW_index_with_min_ef[True-False-10-8-64]
[2022-09-27T16:10:42.287Z] [gw0] [ 50%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_after_index_different_metric_type[8-True-False-IVF_SQ8-params2]
```
There are more examples in 125.
2. milvus log: [artifacts-milvus-distributed-kafka-nightly-124-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/124/artifact/artifacts-milvus-distributed-kafka-nightly-124-pymilvus-e2e-logs.tar.gz)
3. take one for example: [2022-09-27T16:06:03.703Z] [gw0] [ 49%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_after_index_different_metric_type[8-False-True-ANNOY-params5]
4. collection name: search_collection_u3Rmrdyd
5. Detailed error information:
```
[2022-09-27 16:07:44,054 - ERROR - ci_test]: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 464, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 428, in _execute_search_requests
    raise pre_err
  File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 416, in _execute_search_requests
    response = ft.result()
  File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "{"created":"@1664294864.052752358","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":81,"grpc_status":4}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 717, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 113, in handler
    raise e
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 139, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 59, in handler
    raise MilvusException(Status.UNEXPECTED_ERROR, str(e))
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "{"created":"@1664294864.052752358","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":81,"grpc_status":4}"
>)>
 (api_request.py:39)
[2022-09-27 16:07:44,054 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "{"created":"@1664294864.052752358","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_f...... (api_request.py:40)
```

**Comment by NicoYuan1986** [comment]
The issue has been solved.
