### ISSUE TITLE
[Bug]: [Nightly] Load balance failed reporting 'failed to balance segments, err=TaskStale'

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#19386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:5f02f09
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0.dev30
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Load balance failed reporting 'failed to balance segments, err=TaskStale'.
```
[2022-09-22T18:41:41.366Z] [2022-09-22 18:10:29 - ERROR - pymilvus.decorators]: RPC error: [load_balance], <MilvusException: (code=1, message=failed to balance segments, err=TaskStale)>, <Time:{'RPC start': '2022-09-22 18:10:29.127591', 'RPC error': '2022-09-22 18:10:29.612304'}> (decorators.py:100)
[2022-09-22T18:41:41.366Z] [2022-09-22 18:10:29 - ERROR - ci_test]: Traceback (most recent call last):
[2022-09-22T18:41:41.366Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2022-09-22T18:41:41.366Z]     res = func(*args, **_kwargs)
[2022-09-22T18:41:41.366Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2022-09-22T18:41:41.366Z]     return func(*arg, **kwargs)
[2022-09-22T18:41:41.366Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/utility.py", line 543, in load_balance
[2022-09-22T18:41:41.366Z]     return _get_connection(using).load_balance(collection_name, src_node_id, dst_node_ids, sealed_segment_ids, timeout=timeout)
[2022-09-22T18:41:41.366Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 101, in handler
[2022-09-22T18:41:41.366Z]     raise e
[2022-09-22T18:41:41.366Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 97, in handler
[2022-09-22T18:41:41.366Z]     return func(*args, **kwargs)
[2022-09-22T18:41:41.366Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 127, in handler
[2022-09-22T18:41:41.366Z]     ret = func(self, *args, **kwargs)
[2022-09-22T18:41:41.366Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 79, in handler
[2022-09-22T18:41:41.366Z]     raise e
[2022-09-22T18:41:41.366Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2022-09-22T18:41:41.366Z]     return func(self, *args, **kwargs)
[2022-09-22T18:41:41.366Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 1042, in load_balance
[2022-09-22T18:41:41.366Z]     raise MilvusException(status.error_code, status.reason)
[2022-09-22T18:41:41.366Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=failed to balance segments, err=TaskStale)>
[2022-09-22T18:41:41.366Z]  (api_request.py:39)
[2022-09-22T18:41:41.366Z] [2022-09-22 18:10:29 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=failed to balance segments, err=TaskStale)> (api_request.py:40)
```

### Expected Behavior

PASSED

### Steps To Reproduce

```markdown
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/114/pipeline/143/
```

### Milvus Log

1. milvus log: [artifacts-milvus-distributed-kafka-nightly-114-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/114/artifact/artifacts-milvus-distributed-kafka-nightly-114-pymilvus-e2e-logs.tar.gz)
2. collection name: utility_Wk9P7ZE4
3. failed timeline: [2022-09-22T18:10:36.576Z] [gw0] [ 99%] FAILED testcases/test_utility.py::TestUtilityAdvanced::test_load_balance_normal

**Comment by yah01** [comment]
/assign
/assign @NicoYuan1986 
should be fixed with #19400, plz help check it

**Comment by NicoYuan1986** [comment]
> 3\. test_load_balance_normal

Thank you for your work!🌸
I'll check it.

**Comment by NicoYuan1986** [comment]
The issue has been fixed.

**Comment by NicoYuan1986** [comment]
The issue appears again.
nightly: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/172/pipeline/187

milvus: 2f19e65
pymilvus: 2.0.0.dev63

1. milvus log: [artifacts-milvus-distributed-pulsar-nightly-172-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/172/artifact/artifacts-milvus-distributed-pulsar-nightly-172-pymilvus-e2e-logs.tar.gz)
2. collection name: utility_mV0pt4FU
3. failed time: [2022-10-24T19:32:54.953Z] [gw4] [ 98%] FAILED testcases/test_utility.py::TestUtilityAdvanced::test_load_balance_normal

**Comment by yah01** [comment]
/assign @NicoYuan1986 
#20263 fixed it

**Comment by NicoYuan1986** [comment]
Fixed!

**Comment by NicoYuan1986** [comment]
The issue appeared again in the latest nightly report. Could you help have a look? @yah01 

nightly: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/186/pipeline/187

milvus: c5cd92d
pymilvus: 2.2.0.dev71

1. log: [artifacts-milvus-distributed-pulsar-nightly-186-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/186/artifact/artifacts-milvus-distributed-pulsar-nightly-186-pymilvus-e2e-logs.tar.gz)
2. collection name: utility_k6OytYZo
3. failed time: [2022-11-07T18:49:04.420Z] [gw1] [ 97%] FAILED testcases/test_utility.py::TestUtilityAdvanced::test_load_balance_normal

**Comment by NicoYuan1986** [comment]
It doesn't seem to be getting better. https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/187/pipeline/155/

milvus: a2bf502
pymilvus: 2.2.0.dev72

1. log: [artifacts-milvus-distributed-kafka-nightly-187-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/187/artifact/artifacts-milvus-distributed-kafka-nightly-187-pymilvus-e2e-logs.tar.gz)
2. collection name: utility_kIZyrEeG
3. failed time: [2022-11-08T18:55:48.437Z] [gw4] [ 96%] FAILED testcases/test_utility.py::TestUtilityAdvanced::test_load_balance_normal

**Comment by NicoYuan1986** [comment]
Latest: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/191/pipeline/155

milvus: b0a0798
pymilvus: 2.2.0.dev72

1. log: [artifacts-milvus-distributed-kafka-nightly-191-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/191/artifact/artifacts-milvus-distributed-kafka-nightly-191-pymilvus-e2e-logs.tar.gz)
2. collection name: utility_J340eDDl
3. failed time:  [2022-11-15T18:50:57.609Z] [gw4] [ 97%] FAILED testcases/test_utility.py::TestUtilityAdvanced::test_load_balance_normal

**Comment by yah01** [comment]
/assign @NicoYuan1986 
plz retry with #20636 for v2.2.0

**Comment by NicoYuan1986** [comment]
The issue appeared again in the latest nightly report for v2.2.0
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/4/pipeline/187

milvus: 279cf6f
pymilvus: 2.2.0.dev71

1. log: [artifacts-milvus-distributed-pulsar-nightly-4-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/4/artifact/artifacts-milvus-distributed-pulsar-nightly-4-pymilvus-e2e-logs.tar.gz)
2. collection name: utility_naZ4GkQN
3. failed time: [2022-11-16T20:53:29.319Z] [gw0] [ 97%] FAILED testcases/test_utility.py::TestUtilityAdvanced::test_load_balance_normal

**Comment by NicoYuan1986** [comment]
The error appeared for both master and 2.2.0 branch yesterday.

milvus: 2.2.0(e7429f8)
pymilvus: 2.2.0.dev71

1. log: [artifacts-milvus-distributed-pulsar-nightly-6-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/6/artifact/artifacts-milvus-distributed-pulsar-nightly-6-pymilvus-e2e-logs.tar.gz)
2. collection name: utility_PMGOt6Un
3. FAILED timeline: [2022-11-18T20:53:29.423Z] [gw2] [ 97%] FAILED testcases/test_utility.py::TestUtilityAdvanced::test_load_balance_normal

**Comment by NicoYuan1986** [comment]
Fixed.
