### ISSUE TITLE
[Bug]: [benchmark][cluster]Milvus search failed ,raise an error"fail to get shard leaders from QueryCoord"

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#19399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220922-5f02f097
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0dev32
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server-instance
fouram-cron-1663862400-7
server-configmap
server-cluster-16c64m
client-configmap
client-search-sift50m-ivf-flat-2048

server:
```
fouram-cron-1663862400-7-etcd-0                                   1/1     Running     0               10m     10.104.1.14    4am-node10   <none>           <none>
fouram-cron-1663862400-7-etcd-1                                   1/1     Running     0               10m     10.104.6.173   4am-node13   <none>           <none>
fouram-cron-1663862400-7-etcd-2                                   1/1     Running     0               10m     10.104.5.136   4am-node12   <none>           <none>
fouram-cron-1663862400-7-milvus-datacoord-cf5445798-c9htw         1/1     Running     0               10m     10.104.4.126   4am-node11   <none>           <none>
fouram-cron-1663862400-7-milvus-datanode-bbc669597-llr8p          1/1     Running     1 (4m10s ago)   10m     10.104.4.128   4am-node11   <none>           <none>
fouram-cron-1663862400-7-milvus-indexcoord-6b5bbd4b5-sc2vd        1/1     Running     1 (4m10s ago)   10m     10.104.1.251   4am-node10   <none>           <none>
fouram-cron-1663862400-7-milvus-indexnode-68b4b94b54-r4f7j        1/1     Running     0               10m     10.104.9.75    4am-node14   <none>           <none>
fouram-cron-1663862400-7-milvus-proxy-84f87c5d8f-4zbf4            1/1     Running     0               10m     10.104.9.78    4am-node14   <none>           <none>
fouram-cron-1663862400-7-milvus-querycoord-7fddc75878-mktzw       1/1     Running     1 (4m10s ago)   10m     10.104.1.253   4am-node10   <none>           <none>
fouram-cron-1663862400-7-milvus-querynode-56fcd69b96-mj6ck        1/1     Running     0               10m     10.104.5.113   4am-node12   <none>           <none>
fouram-cron-1663862400-7-milvus-rootcoord-5d87945798-kzl5j        1/1     Running     0               10m     10.104.9.77    4am-node14   <none>           <none>
fouram-cron-1663862400-7-minio-0                                  1/1     Running     0               10m     10.104.9.74    4am-node14   <none>           <none>
fouram-cron-1663862400-7-minio-1                                  1/1     Running     0               10m     10.104.1.249   4am-node10   <none>           <none>
fouram-cron-1663862400-7-minio-2                                  1/1     Running     0               10m     10.104.4.127   4am-node11   <none>           <none>
fouram-cron-1663862400-7-minio-3                                  1/1     Running     0               10m     10.104.6.152   4am-node13   <none>           <none>
fouram-cron-1663862400-7-pulsar-bookie-0                          1/1     Running     0               10m     10.104.6.166   4am-node13   <none>           <none>
fouram-cron-1663862400-7-pulsar-bookie-1                          1/1     Running     0               10m     10.104.1.15    4am-node10   <none>           <none>
fouram-cron-1663862400-7-pulsar-bookie-2                          1/1     Running     0               10m     10.104.9.85    4am-node14   <none>           <none>
fouram-cron-1663862400-7-pulsar-bookie-init-bdm5t                 0/1     Completed   0               10m     10.104.4.125   4am-node11   <none>           <none>
fouram-cron-1663862400-7-pulsar-broker-0                          1/1     Running     0               10m     10.104.1.252   4am-node10   <none>           <none>
fouram-cron-1663862400-7-pulsar-proxy-0                           1/1     Running     0               10m     10.104.6.153   4am-node13   <none>           <none>
fouram-cron-1663862400-7-pulsar-pulsar-init-hj42k                 0/1     Completed   0               10m     10.104.1.246   4am-node10   <none>           <none>
fouram-cron-1663862400-7-pulsar-recovery-0                        1/1     Running     0               10m     10.104.1.247   4am-node10   <none>           <none>
fouram-cron-1663862400-7-pulsar-zookeeper-0                       1/1     Running     0               10m     10.104.6.171   4am-node13   <none>           <none>
fouram-cron-1663862400-7-pulsar-zookeeper-1                       1/1     Running     0               8m55s   10.104.1.19    4am-node10   <none>           <none>
fouram-cron-1663862400-7-pulsar-zookeeper-2                       1/1     Running     0               8m19s   10.104.5.138   4am-node12   <none>           <none>
```
client log:
```
[2022-09-22 17:12:21,397] [   DEBUG] - {'type': 'insert_search_performance', 'value': {}} (milvus_benchmark.main:107)
[2022-09-22 17:12:21,397] [   DEBUG] - {'_version': '0.1', '_type': 'case', 'run_id': 1663870325, 'mode': 'local', 'server': <milvus_benchmark.metrics.models.server.Server object at 0x7fd478062c70>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware object at 0x7fd478062bb0>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7fd478062b20>, 'status': 'RUN_FAILED', 'err_message': '<MilvusException: (code=1, message=All attempts results:\nattempt #1:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_0_436171697759653190v0 is not available in any replica\nattempt #2:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_0_436171697759653190v0 is not available in any replica\nattempt #3:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_0_436171697759653190v0 is not available in any replica\nattempt #4:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_0_436171697759653190v0 is not available in any replica\nattempt #5:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_0_436171697759653190v0 is not available in any replica\nattempt #6:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_0_436171697759653190v0 is not available in any replica\nattempt #7:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_1_436171697759653190v1 is not available in any replica\nattempt #8:context deadline exceeded\n)>\nTraceback (most recent call last):\n  File "main.py", line 95, in run_suite\n    result = runner.run_case(case_metric, **case)\n  File "/src/milvus_benchmark/runners/search.py", line 309, in run_case\n    _query_res = self.milvus.query(case_param["vector_query"], filter_query=case_param["filter_query"],\n  File "/src/milvus_benchmark/client.py", line 53, in wrapper\n    result = func(*args, **kwargs)\n  File "/src/milvus_benchmark/client.py", line 346, in query\n    result = self._milvus.search(tmp_collection_name, **params)\n  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/stub.py", line 844, in search\n    return handler.search(collection_name, data, anns_field, param, limit, expression,\n  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 113, in handler\n    raise e\n  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler\n    return func(*args, **kwargs)\n  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 139, in handler\n    ret = func(self, *args, **kwargs)\n  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 89, in handler\n    raise e\n  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 51, in handler\n    return func(self, *args, **kwargs)\n  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 472, in search\n    return self._execute_search_requests(requests, timeout, **_kwargs)\n  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 436, in _execute_search_requests\n    raise pre_err\n  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 427, in _execute_search_requests\n    raise MilvusException(response.status.error_code, response.status.reason)\npymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=All attempts results:\nattempt #1:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_0_436171697759653190v0 is not available in any replica\nattempt #2:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_0_436171697759653190v0 is not available in any replica\nattempt #3:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_0_436171697759653190v0 is not available in any replica\nattempt #4:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_0_436171697759653190v0 is not available in any replica\nattempt #5:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_0_436171697759653190v0 is not available in any replica\nattempt #6:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_0_436171697759653190v0 is not available in any replica\nattempt #7:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_1_436171697759653190v1 is not available in any replica\nattempt #8:context deadline exceeded\n)>\n', 'collection': {'dimension': 128, 'metric_type': 'l2', 'dataset_name': 'sift_50m_128_l2', 'fields': None, 'shards_num': None}, 'index': {'index_type': 'ivf_flat', 'index_param': {'nlist': 2048}}, 'search': {'nq': 1000, 'topk': 10, 'search_param': {'nprobe': 32}, 'filter': [], 'guarantee_timestamp': None}, 'run_params': None, 'metrics': {'type': 'insert_search_performance', 'value': {}}, 'datetime': '2022-09-22 16:12:40.046444', 'type': 'metric'} (milvus_benchmark.metric.api:30)
[2022-09-22 17:12:21,403] [   DEBUG] - Start run query, run 1 of 30 (milvus_benchmark.runners.search:306)
[2022-09-22 17:12:21,403] [    INFO] - {'nq': 1000, 'topk': 100, 'search_param': {'nprobe': 32}, 'filter': [], 'guarantee_timestamp': None} (milvus_benchmark.runners.search:307)
[2022-09-22 17:12:36,412] [   ERROR] - RPC error: [search], <MilvusException: (code=1, message=All attempts results:
attempt #1:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_0_436171697759653190v0 is not available in any replica
attempt #2:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_0_436171697759653190v0 is not available in any replica
attempt #3:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_0_436171697759653190v0 is not available in any replica
attempt #4:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_0_436171697759653190v0 is not available in any replica
attempt #5:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_0_436171697759653190v0 is not available in any replica
attempt #6:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_0_436171697759653190v0 is not available in any replica
attempt #7:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_0_436171697759653190v0 is not available in any replica
attempt #8:context deadline exceeded
)>, <Time:{'RPC start': '2022-09-22 17:12:21.403442', 'RPC error': '2022-09-22 17:12:36.412447'}> (pymilvus.decorators:112)
[2022-09-22 17:12:36,413] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 95, in run_suite
    result = runner.run_case(case_metric, **case)
  File "/src/milvus_benchmark/runners/search.py", line 309, in run_case
    _query_res = self.milvus.query(case_param["vector_query"], filter_query=case_param["filter_query"],
  File "/src/milvus_benchmark/client.py", line 53, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 346, in query
    result = self._milvus.search(tmp_collection_name, **params)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/stub.py", line 844, in search
    return handler.search(collection_name, data, anns_field, param, limit, expression,
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 113, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 139, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 89, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 472, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 436, in _execute_search_requests
    raise pre_err
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 427, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=All attempts results:
attempt #1:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_0_436171697759653190v0 is not available in any replica
attempt #2:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_0_436171697759653190v0 is not available in any replica
attempt #3:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_0_436171697759653190v0 is not available in any replica
attempt #4:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_0_436171697759653190v0 is not available in any replica
attempt #5:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_0_436171697759653190v0 is not available in any replica
attempt #6:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_0_436171697759653190v0 is not available in any replica
attempt #7:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_0_436171697759653190v0 is not available in any replica
attempt #8:context deadline exceeded
```

### Steps To Reproduce

```markdown
1.create an collection
2.create ivf flat index
3.insert data
4.create index again and load
5.search with error
```

### Anything else?

client-search-sift50m-ivf-flat-2048:
```
"config.yaml": "insert_search_performance:
		  collections:
		    -
		      collection_name: sift_50m_128_l2
		      ni_per: 50000
		      build_index: true
		      index_type: ivf_flat 
		      index_param:
		        nlist: 2048
		      run_count: 30
		      top_ks: [1, 10, 100, 1000]
		      nqs: [1, 10, 100, 500, 1000, 1200]
		      search_params:
		        -
		          nprobe: 8
		        -
		          nprobe: 32
```

**Comment by jingkl** [comment]
server-instance
fouram-qh54c-1
server-configmap
server-single-16c64m
client-configmap
client-search-sift50m-ivf-flat-2048
master-20220929-64662919
2.2.0.dev32

`This scenario now has a search timeout and hung, so I don't think it's fixed`

```
fouram-qh54c-1-etcd-0                                             1/1     Running     0               2m12s   10.104.4.188   4am-node11   <none>           <none>
fouram-qh54c-1-milvus-standalone-6789b5d65d-2gslc                 1/1     Running     0               2m12s   10.104.5.190   4am-node12   <none>           <none>
fouram-qh54c-1-minio-7948c94df5-h6bjj                             1/1     Running     0               2m12s   10.104.4.187   4am-node11   <none>           <none>
```


```
       [2022-09-30 00:51:22,609] [ WARNING] - [search] retry:4, cost: 0.27s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, fai
led to connect to all addresses> (pymilvus.decorators:72)
[2022-09-30 00:51:22,883] [ WARNING] - [search] retry:5, cost: 0.81s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, fai
led to connect to all addresses> (pymilvus.decorators:72)
[2022-09-30 00:51:23,699] [ WARNING] - [search] retry:6, cost: 2.43s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, fai
led to connect to all addresses> (pymilvus.decorators:72)
[2022-09-30 00:51:26,134] [ WARNING] - [search] retry:7, cost: 7.290000000000001s, reason: <_MultiThreadedRendezvous: StatusCode.UNA
VAILABLE, failed to connect to all addresses> (pymilvus.decorators:72)
[2022-09-30 00:51:33,430] [ WARNING] - [search] retry:8, cost: 21.870000000000005s, reason: <_MultiThreadedRendezvous: StatusCode.UN
AVAILABLE, failed to connect to all addresses> (pymilvus.decorators:72)
[2022-09-30 00:51:55,306] [ WARNING] - [search] retry:9, cost: 60s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, faile
d to connect to all addresses> (pymilvus.decorators:72)
[2022-09-30 00:52:55,311] [ WARNING] - [search] retry:10, cost: 60s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, fail
ed to connect to all addresses> (pymilvus.decorators:72)
[2022-09-30 00:58:55,318] [   ERROR] - RPC error: [search], <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that
 terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "{"created":"@1664499535.317435595","description":"Error received from peer ipv4:10.255.135.219:19530",
"file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>)>, <Time:{'RPC start': '2022-09-30 00:51:21.759686', 'RPC error': '2022-09-30 00:58:55.318686'}> (pymilvus.decorators:112)
[2022-09-30 00:58:55,320] [   ERROR] - Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 472, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 436, in _execute_search_requests
    raise pre_err
File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 424, in _execute_search_requests
    response = ft.result()
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "{"created":"@1664499535.317435595","description":"Error received from peer ipv4:10.255.135.219:19530",
"file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "main.py", line 95, in run_suite
    result = runner.run_case(case_metric, **case)
  File "/src/milvus_benchmark/runners/search.py", line 309, in run_case
    _query_res = self.milvus.query(case_param["vector_query"], filter_query=case_param["filter_query"],
  File "/src/milvus_benchmark/client.py", line 53, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 346, in query
    result = self._milvus.search(tmp_collection_name, **params)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/stub.py", line 844, in search
    return handler.search(collection_name, data, anns_field, param, limit, expression,
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 113, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 139, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 59, in handler
    raise MilvusException(Status.UNEXPECTED_ERROR, str(e))
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "{"created":"@1664499535.317435595","description":"Error received from peer ipv4:10.255.135.219:19530",
"file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"Deadline Exceeded","grpc_status":4}
```

**Comment by jingkl** [comment]
This currently has a load failure problem, see issue：#20630

**Comment by yanliang567** [comment]
@jingkl please retry as the issue above was fixed
