### ISSUE TITLE
[Bug]: [benchmark][standalone]Milvus search time out, raise an error"server Unavailable: Retry timeout: 300s"

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#19397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220922-5f02f097
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0dev30
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server-instance
fouram-cron-1663862400-6
server-configmap
server-single-16c64m
client-configmap
client-search-sift50m-ivf-flat-2048
sever:
```
fouram-cron-1663862400-6-etcd-0                                   1/1     Running     0               10m     10.104.4.133   4am-node11   <none>           <none>
fouram-cron-1663862400-6-milvus-standalone-5d5564dd4-6f742        1/1     Running     0               10m     10.104.9.79    4am-node14   <none>           <none>
fouram-cron-1663862400-6-minio-86bbd74dbb-zbqhp                   1/1     Running     0               10m     10.104.4.113   4am-node11   <none>           <none>
```
client log:
```
[2022-09-22 22:04:12,935] [    INFO] - {'nq': 500, 'topk': 1000, 'search_param': {'nprobe': 8}, 'filter': [], 'guarantee_timestamp': None} (milvus_benchmark.runners.search:307)
[2022-09-22 22:08:22,412] [ WARNING] - [93m[search] retry:4, cost: 0.27s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:72)
[2022-09-22 22:08:22,686] [ WARNING] - [93m[search] retry:5, cost: 0.81s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:72)
[2022-09-22 22:08:23,501] [ WARNING] - [93m[search] retry:6, cost: 2.43s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:72)
[2022-09-22 22:08:25,934] [ WARNING] - [93m[search] retry:7, cost: 7.290000000000001s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:72)
[2022-09-22 22:08:33,229] [ WARNING] - [93m[search] retry:8, cost: 21.870000000000005s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:72)
[2022-09-22 22:08:55,103] [ WARNING] - [93m[search] retry:9, cost: 60s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:72)
[2022-09-22 22:09:55,107] [   ERROR] - RPC error: [search], <MilvusUnavailableException: (code=1, message=server Unavailable: Retry timeout: 300s)>, <Time:{'RPC start': '2022-09-22 22:04:12.935554', 'RPC error': '2022-09-22 22:09:55.107171'}> (pymilvus.decorators:112)
[2022-09-22 22:09:55,109] [   ERROR] - Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 472, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 436, in _execute_search_requests
    raise pre_err
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 424, in _execute_search_requests
    response = ft.result()
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1663884595.106763193","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3260,"referenced_errors":[{"created":"@1663884595.106762461","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":167,"grpc_status":14}]}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 95, in run_suite
    result = runner.run_case(case_metric, **case)
  File "/src/milvus_benchmark/runners/search.py", line 309, in run_case
    _query_res = self.milvus.query(case_param["vector_query"], filter_query=case_param["filter_query"],
  File "/src/milvus_benchmark/client.py", line 53, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 346, in query
    result = self._milvus.search(tmp_collection_name, **params)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/stub.py", line 844, in search
    return handler.search(collection_name, data, anns_field, param, limit, expression,
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 113, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 139, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 67, in handler
    raise MilvusUnavailableException(Status.UNEXPECTED_ERROR, f"server Unavailable: {timeout_msg}")
pymilvus.exceptions.MilvusUnavailableException: <MilvusUnavailableException: (code=1, message=server Unavailable: Retry timeout: 300s)>
 (milvus_benchmark.main:98)
```

### Steps To Reproduce

```markdown
1.create an collection
2.create ivf flat index
3.insert data
4.create index again and load
5.search with error
```

### Anything else?

  
client-search-sift50m-ivf-flat-2048:
config.yaml: |
    insert_search_performance:
      collections:
        -
          collection_name: sift_50m_128_l2
          ni_per: 50000
          build_index: true
          index_type: ivf_flat 
          index_param:
            nlist: 2048
          run_count: 30
          top_ks: [1, 10, 100, 1000]
          nqs: [1, 10, 100, 500, 1000, 1200]
          search_params:
            -
              nprobe: 8
            -
              nprobe: 32

**Comment by jingkl** [comment]
**Milvus search timed out and hung**


server-instance
fouram-cron-1664121600-6
server-configmap
server-single-16c64m
client-configmap
client-search-sift50m-ivf-flat-2048

master-20220925-91df8f2d

```
fouram-cron-1664121600-6-etcd-0                                   1/1     Running             0               2m23s   10.104.1.114   4am-node10   <none>           <none>
fouram-cron-1664121600-6-milvus-standalone-7d47455587-nwlpv       1/1     Running             0               2m23s   10.104.4.86    4am-node11   <none>           <none>
fouram-cron-1664121600-6-minio-569cd6cc78-jp4wx                   1/1     Running             0               2m23s   10.104.1.92    4am-node10   <none>           <none>
```

```
[2022-09-25 21:47:08,448] [    INFO] - {'nq': 500, 'topk': 100, 'search_param': {'nprobe': 8}, 'filter': [], 'guarantee_timestamp': None} (milvus_benchmark.runners.search:307)
[2022-09-25 21:47:09,004] [ WARNING] - [93m[search] retry:4, cost: 0.27s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:72)
[2022-09-25 21:47:09,278] [ WARNING] - [93m[search] retry:5, cost: 0.81s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:72)
[2022-09-25 21:47:10,092] [ WARNING] - [93m[search] retry:6, cost: 2.43s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:72)
[2022-09-25 21:47:12,527] [ WARNING] - [93m[search] retry:7, cost: 7.290000000000001s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:72)
[2022-09-25 21:47:19,821] [ WARNING] - [93m[search] retry:8, cost: 21.870000000000005s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:72)
[2022-09-25 21:47:41,696] [ WARNING] - [93m[search] retry:9, cost: 60s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:72)
[2022-09-25 21:48:41,701] [ WARNING] - [93m[search] retry:10, cost: 60s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:72)
[2022-09-25 21:51:20,897] [   DEBUG] - Milvus query run in 252.449s (milvus_benchmark.client:57)
[2022-09-25 21:51:20,898] [   DEBUG] - Start run query, run 28 of 30 (milvus_benchmark.runners.search:306)
[2022-09-25 21:51:20,898] [    INFO] - {'nq': 500, 'topk': 100, 'search_param': {'nprobe': 8}, 'filter': [], 'guarantee_timestamp': None} (milvus_benchmark.runners.search:307)
[2022-09-25 21:53:07,542] [   DEBUG] - Milvus query run in 106.6429s (milvus_benchmark.client:57)
[2022-09-25 21:53:07,542] [   DEBUG] - Start run query, run 29 of 30 (milvus_benchmark.runners.search:306)
[2022-09-25 21:53:07,542] [    INFO] - {'nq': 500, 'topk': 100, 'search_param': {'nprobe': 8}, 'filter': [], 'guarantee_timestamp': None} (milvus_benchmark.runners.search:307)
[2022-09-25 21:54:49,467] [   DEBUG] - Milvus query run in 101.9246s (milvus_benchmark.client:57)
[2022-09-25 21:54:49,468] [   DEBUG] - Start run query, run 30 of 30 (milvus_benchmark.runners.search:306)
[2022-09-25 21:54:49,468] [    INFO] - {'nq': 500, 'topk': 100, 'search_param': {'nprobe': 8}, 'filter': [], 'guarantee_timestamp': None} (milvus_benchmark.runners.search:307)
[2022-09-25 21:56:27,369] [   DEBUG] - Milvus query run in 97.9007s (milvus_benchmark.client:57)
[2022-09-25 21:56:27,370] [    INFO] - Min query time: 96.42, avg query time: 139.81 (milvus_benchmark.runners.search:316)
[2022-09-25 21:56:27,370] [    INFO] - {'insert': {'total_time': 1501.9364, 'rps': 33290.3571, 'ni_time': 1.5019}, 'build_time': 1118.7381, 'search_time': 96.4193, 'avc_search_time': 139.8077} (milvus_benchmark.main:99)
[2022-09-25 21:56:27,370] [   DEBUG] - {'type': 'insert_search_performance', 'value': {'insert': {'total_time': 1501.9364, 'rps': 33290.3571, 'ni_time': 1.5019}, 'build_time': 1118.7381, 'search_time': 96.4193, 'avc_search_time': 139.8077}} (milvus_benchmark.main:107)
[2022-09-25 21:56:27,370] [   DEBUG] - {'_version': '0.1', '_type': 'case', 'run_id': 1664126558, 'mode': 'local', 'server': <milvus_benchmark.metrics.models.server.Server object at 0x7ff6e58a4fd0>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware object at 0x7ff6e58a4f40>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7ff6e58a4e80>, 'status': 'RUN_SUCC', 'err_message': '', 'collection': {'dimension': 128, 'metric_type': 'l2', 'dataset_name': 'sift_50m_128_l2', 'fields': None, 'shards_num': None}, 'index': {'index_type': 'ivf_flat', 'index_param': {'nlist': 2048}}, 'search': {'nq': 500, 'topk': 100, 'search_param': {'nprobe': 8}, 'filter': [], 'guarantee_timestamp': None}, 'run_params': None, 'metrics': {'type': 'insert_search_performance', 'value': {'insert': {'total_time': 1501.9364, 'rps': 33290.3571, 'ni_time': 1.5019}, 'build_time': 1118.7381, 'search_time': 96.4193, 'avc_search_time': 139.8077}}, 'datetime': '2022-09-25 16:03:55.259938', 'type': 'metric'} (milvus_benchmark.metric.api:30)
[2022-09-25 21:56:27,379] [   DEBUG] - Start run query, run 1 of 30 (milvus_benchmark.runners.search:306)
[2022-09-25 21:56:27,379] [    INFO] - {'nq': 500, 'topk': 1000, 'search_param': {'nprobe': 8}, 'filter': [], 'guarantee_timestamp': None} (milvus_benchmark.runners.search:307)
[2022-09-25 22:01:11,945] [   DEBUG] - Milvus query run in 284.5659s (milvus_benchmark.client:57)
[2022-09-25 22:01:11,945] [   DEBUG] - Start run query, run 2 of 30 (milvus_benchmark.runners.search:306)
[2022-09-25 22:01:11,945] [    INFO] - {'nq': 500, 'topk': 1000, 'search_param': {'nprobe': 8}, 'filter': [], 'guarantee_timestamp': None} (milvus_benchmark.runners.search:307)
```

**Comment by yah01** [comment]
/assign @jingkl 
plz retry with the latest commit, the PR #19414 should fix this

**Comment by jingkl** [comment]
server-instance
fouram-r6z57-1
server-configmap
server-single-16c64m
client-configmap
client-search-sift50m-ivf-flat-2048

master-20220929-3a770f7d
2.2.0dev32
```
fouram-r6z57-1-etcd-0                                             1/1     Running     0               17m     10.104.4.67    4am-node11   <none>           <none>
fouram-r6z57-1-milvus-standalone-779cb8b9d-mqlf2                  1/1     Running     0               17m     10.104.1.18    4am-node10   <none>           <none>
fouram-r6z57-1-minio-7d6b5696df-52kbx                             1/1     Running     0               17m     10.104.4.68    4am-node11   <none>           <none>
```
```
[2022-09-29 08:34:36,011] [    INFO] - {'nq': 100, 'topk': 1, 'search_param': {'nprobe': 8}, 'filter': [], 'guarantee_timestamp': None} (milvus_benchmark.runners.search:307)
[2022-09-29 08:34:36,543] [ WARNING] - [93m[search] retry:4, cost: 0.27s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:72)
[2022-09-29 08:34:36,815] [ WARNING] - [93m[search] retry:5, cost: 0.81s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:72)
[2022-09-29 08:34:37,629] [ WARNING] - [93m[search] retry:6, cost: 2.43s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>[0m (pymilvus.decorators:72)
[2022-09-29 08:34:40,061] [ WARNING] - [93m[search] retry:7, cost: 7.290000000000001s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>[0m (pymilvus.decorators:72)
[2022-09-29 08:34:47,354] [ WARNING] - [93m[search] retry:8, cost: 21.870000000000005s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>[0m (pymilvus.decorators:72)
[2022-09-29 08:35:09,227] [ WARNING] - [93m[search] retry:9, cost: 60s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>[0m (pymilvus.decorators:72)
[2022-09-29 08:36:09,232] [   ERROR] - RPC error: [search], <MilvusException: (code=1, message=collection:sift_50m_128_l2 or partition:[] not loaded into memory when search)>, <Time:{'RPC start': '2022-09-29 08:34:36.011276', 'RPC error': '2022-09-29 08:36:09.232755'}> (pymilvus.decorators:112)
[2022-09-29 08:36:09,235] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 95, in run_suite
    result = runner.run_case(case_metric, **case)
  File "/src/milvus_benchmark/runners/search.py", line 309, in run_case
    _query_res = self.milvus.query(case_param["vector_query"], filter_query=case_param["filter_query"],
  File "/src/milvus_benchmark/client.py", line 53, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 346, in query
    result = self._milvus.search(tmp_collection_name, **params)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/stub.py", line 844, in search
    return handler.search(collection_name, data, anns_field, param, limit, expression,
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 113, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 139, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 89, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 472, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 436, in _execute_search_requests
    raise pre_err
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 427, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection:sift_50m_128_l2 or partition:[] not loaded into memory when search)>
```

**Comment by jingkl** [comment]
server-instance
fouram-r6z57-1
server-configmap
server-single-16c64m
client-configmap
client-search-sift50m-ivf-flat-2048

master-20220929-3a770f7d
2.2.0dev32
```
fouram-r6z57-1-etcd-0                                             1/1     Running     0               17m     10.104.4.67    4am-node11   <none>           <none>
fouram-r6z57-1-milvus-standalone-779cb8b9d-mqlf2                  1/1     Running     0               17m     10.104.1.18    4am-node10   <none>           <none>
fouram-r6z57-1-minio-7d6b5696df-52kbx                             1/1     Running     0               17m     10.104.4.68    4am-node11   <none>           <none>
```
```
[2022-09-29 08:34:36,011] [    INFO] - {'nq': 100, 'topk': 1, 'search_param': {'nprobe': 8}, 'filter': [], 'guarantee_timestamp': None} (milvus_benchmark.runners.search:307)
[2022-09-29 08:34:36,543] [ WARNING] - [93m[search] retry:4, cost: 0.27s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:72)
[2022-09-29 08:34:36,815] [ WARNING] - [93m[search] retry:5, cost: 0.81s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:72)
[2022-09-29 08:34:37,629] [ WARNING] - [93m[search] retry:6, cost: 2.43s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>[0m (pymilvus.decorators:72)
[2022-09-29 08:34:40,061] [ WARNING] - [93m[search] retry:7, cost: 7.290000000000001s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>[0m (pymilvus.decorators:72)
[2022-09-29 08:34:47,354] [ WARNING] - [93m[search] retry:8, cost: 21.870000000000005s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>[0m (pymilvus.decorators:72)
[2022-09-29 08:35:09,227] [ WARNING] - [93m[search] retry:9, cost: 60s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>[0m (pymilvus.decorators:72)
[2022-09-29 08:36:09,232] [   ERROR] - RPC error: [search], <MilvusException: (code=1, message=collection:sift_50m_128_l2 or partition:[] not loaded into memory when search)>, <Time:{'RPC start': '2022-09-29 08:34:36.011276', 'RPC error': '2022-09-29 08:36:09.232755'}> (pymilvus.decorators:112)
[2022-09-29 08:36:09,235] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 95, in run_suite
    result = runner.run_case(case_metric, **case)
  File "/src/milvus_benchmark/runners/search.py", line 309, in run_case
    _query_res = self.milvus.query(case_param["vector_query"], filter_query=case_param["filter_query"],
  File "/src/milvus_benchmark/client.py", line 53, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 346, in query
    result = self._milvus.search(tmp_collection_name, **params)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/stub.py", line 844, in search
    return handler.search(collection_name, data, anns_field, param, limit, expression,
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 113, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 139, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 89, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 472, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 436, in _execute_search_requests
    raise pre_err
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 427, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection:sift_50m_128_l2 or partition:[] not loaded into memory when search)>
```

**Comment by yah01** [comment]
/assign @jingkl 
plz check this as many patches have been merged

**Comment by jingkl** [comment]
master-20221019-99df2d9b
pymilvus 2.2.0dev45
This problem has been fixed, turn off issue
