### ISSUE TITLE
[Bug]: Create index for varchar field timeout after Milvus reinstallation in master branch

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#19446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220926-804c18df
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.2.0.dev30
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2022-09-26T09:14:55.762Z] [2022-09-26 09:10:57 - INFO - ci_test]: inserted 3000 data into collection deploy_test_index_type_BIN_IVF_FLAT_is_compacted_not_compacted_segment_status_all_is_vector_indexed_is_vector_indexed_is_string_indexed_is_string_indexed_replica_number_0_is_deleted_is_deleted_data_size_3000 (common_func.py:684)
[2022-09-26T09:14:55.762Z] [2022-09-26 09:10:57 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [      int64   float varchar                                      binary_vector
[2022-09-26T09:14:55.762Z] 0         0     0.0       0  b'\xdb\xdf\x18\x9a\xf6\x0e&\xb1\x9c}\xfc\x16\x...
[2022-09-26T09:14:55.762Z] 1         1     1.0       1  b'\xc6\x1aP\xd0\xe2\xb4}\x83\xf7\x06X \x9c\x9a6U'
[2022-09-26T09:14:55.762Z] 2         2     2.0       2  b'\x86D\xf5\x8f\x0e\xd34\xe6\xa1]......, kwargs: {'timeout': 20} (api_request.py:56)
[2022-09-26T09:14:55.762Z] [2022-09-26 09:10:57 - DEBUG - ci_test]: (api_response) : (insert count: 3000, delete count: 0, upsert count: 0, timestamp: 436255708385640449, success count: 3000, err count: 0)  (api_request.py:31)
[2022-09-26T09:14:55.762Z] [2022-09-26 09:10:57 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 20} (api_request.py:56)
[2022-09-26T09:14:55.762Z] [2022-09-26 09:11:00 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)
[2022-09-26T09:14:55.762Z] [2022-09-26 09:11:00 - DEBUG - ci_test]: (api_request)  : [Collection.delete] args: ['int64 in [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]', None, 20], kwargs: {} (api_request.py:56)
[2022-09-26T09:14:55.762Z] [2022-09-26 09:11:00 - DEBUG - ci_test]: (api_response) : (insert count: 0, delete count: 10, upsert count: 0, timestamp: 436255709171810306, success count: 0, err count: 0)  (api_request.py:31)
[2022-09-26T09:14:55.762Z] [2022-09-26 09:11:00 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['binary_vector', {'index_type': 'BIN_IVF_FLAT', 'params': {'nlist': 128}, 'metric_type': 'HAMMING'}], kwargs: {'timeout': 40, 'index_name': '_default_idx'} (api_request.py:56)
[2022-09-26T09:14:55.762Z] [2022-09-26 09:11:11 - DEBUG - ci_test]: (api_response) : Status(code=0, message='')  (api_request.py:31)
[2022-09-26T09:14:55.762Z] [2022-09-26 09:11:11 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['varchar', {}], kwargs: {'timeout': 40, 'index_name': '_default_string_idx'} (api_request.py:56)
[2022-09-26T09:14:55.762Z] [2022-09-26 09:11:51 - ERROR - pymilvus.decorators]: RPC error: [wait_for_creating_index], <MilvusException: (code=1, message=CreateIndex Timeout)>, <Time:{'RPC start': '2022-09-26 09:11:11.524852', 'RPC error': '2022-09-26 09:11:51.587205'}> (decorators.py:100)
[2022-09-26T09:14:55.762Z] [2022-09-26 09:11:51 - ERROR - pymilvus.decorators]: RPC error: [create_index], <MilvusException: (code=1, message=CreateIndex Timeout)>, <Time:{'RPC start': '2022-09-26 09:11:11.507777', 'RPC error': '2022-09-26 09:11:51.587436'}> (decorators.py:100)
[2022-09-26T09:14:55.762Z] [2022-09-26 09:11:51 - ERROR - ci_test]: Traceback (most recent call last):
[2022-09-26T09:14:55.762Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2022-09-26T09:14:55.762Z]     res = func(*args, **_kwargs)
[2022-09-26T09:14:55.762Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2022-09-26T09:14:55.762Z]     return func(*arg, **kwargs)
[2022-09-26T09:14:55.762Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 1087, in create_index
[2022-09-26T09:14:55.762Z]     timeout=timeout, **kwargs)
[2022-09-26T09:14:55.762Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 101, in handler
[2022-09-26T09:14:55.762Z]     raise e
[2022-09-26T09:14:55.762Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 97, in handler
[2022-09-26T09:14:55.762Z]     return func(*args, **kwargs)
[2022-09-26T09:14:55.762Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 127, in handler
[2022-09-26T09:14:55.762Z]     ret = func(self, *args, **kwargs)
[2022-09-26T09:14:55.762Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 79, in handler
[2022-09-26T09:14:55.762Z]     raise e
[2022-09-26T09:14:55.762Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 50, in handler
[2022-09-26T09:14:55.762Z]     return func(self, *args, **kwargs)
[2022-09-26T09:14:55.762Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 581, in create_index
[2022-09-26T09:14:55.762Z]     timeout=timeout)
[2022-09-26T09:14:55.762Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 101, in handler
[2022-09-26T09:14:55.762Z]     raise e
[2022-09-26T09:14:55.762Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 97, in handler
[2022-09-26T09:14:55.762Z]     return func(*args, **kwargs)
[2022-09-26T09:14:55.762Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 127, in handler
[2022-09-26T09:14:55.762Z]     ret = func(self, *args, **kwargs)
[2022-09-26T09:14:55.762Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 79, in handler
[2022-09-26T09:14:55.762Z]     raise e
[2022-09-26T09:14:55.762Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 50, in handler
[2022-09-26T09:14:55.762Z]     return func(self, *args, **kwargs)
[2022-09-26T09:14:55.762Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 652, in wait_for_creating_index
[2022-09-26T09:14:55.762Z]     raise MilvusException(1, "CreateIndex Timeout")
[2022-09-26T09:14:55.762Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=CreateIndex Timeout)>
[2022-09-26T09:14:55.762Z]  (api_request.py:39)
```

### Expected Behavior

all test cases passed

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test/detail/deploy_test/301/pipeline

log:
[artifacts-standalone-reinstall-301-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9645232/artifacts-standalone-reinstall-301-server-logs.tar.gz)

[artifacts-standalone-reinstall-301-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9645235/artifacts-standalone-reinstall-301-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
It reproduced stable, so set it as critical.


![image](https://user-images.githubusercontent.com/12268675/192445990-ee823c56-9a19-49c6-8a35-5c2ced7207f3.png)

```
[2022-09-26T09:14:55.768Z] [2022-09-26 09:11:25 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['varchar', {}], kwargs: {'timeout': 40, 'index_name': '_default_string_idx'} (api_request.py:56)
[2022-09-26T09:14:55.768Z] [2022-09-26 09:12:05 - ERROR - pymilvus.decorators]: RPC error: [wait_for_creating_index], <MilvusException: (code=1, message=CreateIndex Timeout)>, <Time:{'RPC start': '2022-09-26 09:11:25.712961', 'RPC error': '2022-09-26 09:12:05.949158'}> (decorators.py:100)
[2022-09-26T09:14:55.768Z] [2022-09-26 09:12:05 - ERROR - pymilvus.decorators]: RPC error: [create_index], <MilvusException: (code=1, message=CreateIndex Timeout)>, <Time:{'RPC start': '2022-09-26 09:11:25.688848', 'RPC error': '2022-09-26 09:12:05.949364'}> (decorators.py:100)
[2022-09-26T09:14:55.768Z] [2022-09-26 09:12:05 - ERROR - ci_test]: Traceback (most recent call last):
[2022-09-26T09:14:55.768Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2022-09-26T09:14:55.768Z]     res = func(*args, **_kwargs)
[2022-09-26T09:14:55.768Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2022-09-26T09:14:55.768Z]     return func(*arg, **kwargs)
[2022-09-26T09:14:55.768Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 1087, in create_index
[2022-09-26T09:14:55.768Z]     timeout=timeout, **kwargs)
[2022-09-26T09:14:55.768Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 101, in handler
[2022-09-26T09:14:55.768Z]     raise e
[2022-09-26T09:14:55.768Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 97, in handler
[2022-09-26T09:14:55.768Z]     return func(*args, **kwargs)
[2022-09-26T09:14:55.768Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 127, in handler
[2022-09-26T09:14:55.768Z]     ret = func(self, *args, **kwargs)
[2022-09-26T09:14:55.768Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 79, in handler
[2022-09-26T09:14:55.768Z]     raise e
[2022-09-26T09:14:55.768Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 50, in handler
[2022-09-26T09:14:55.768Z]     return func(self, *args, **kwargs)
[2022-09-26T09:14:55.768Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 581, in create_index
[2022-09-26T09:14:55.768Z]     timeout=timeout)
[2022-09-26T09:14:55.768Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 101, in handler
[2022-09-26T09:14:55.768Z]     raise e
[2022-09-26T09:14:55.768Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 97, in handler
[2022-09-26T09:14:55.768Z]     return func(*args, **kwargs)
[2022-09-26T09:14:55.768Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 127, in handler
[2022-09-26T09:14:55.768Z]     ret = func(self, *args, **kwargs)
[2022-09-26T09:14:55.768Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 79, in handler
[2022-09-26T09:14:55.768Z]     raise e
[2022-09-26T09:14:55.768Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 50, in handler
[2022-09-26T09:14:55.768Z]     return func(self, *args, **kwargs)
[2022-09-26T09:14:55.768Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 652, in wait_for_creating_index
[2022-09-26T09:14:55.768Z]     raise MilvusException(1, "CreateIndex Timeout")
[2022-09-26T09:14:55.768Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=CreateIndex Timeout)>
[2022-09-26T09:14:55.768Z]  (api_request.py:39)
[2022-09-26T09:14:55.768Z] [2022-09-26 09:12:05 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=CreateIndex Timeout)> (api_request.py:40)
```

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test/detail/deploy_test/301/pipeline
log:
[artifacts-standalone-reinstall-301-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/9652120/artifacts-standalone-reinstall-301-server-logs.1.tar.gz)

[artifacts-standalone-reinstall-301-pytest-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/9652121/artifacts-standalone-reinstall-301-pytest-logs.1.tar.gz)

**Comment by longjiquan** [comment]
```log
[2022/09/26 09:14:41.630 +00:00] [INFO] [indexcoord/index_coord.go:493] ["IndexCoord get index state success"] [collectionID=436255597292790218] [indexName=_default_string_idx] [state=Finished]
```

**Comment by zhuwenxing** [comment]
This issue can be reproduced in `master-20220926-804c18df` before reinstallation, but not in the current master-latest like `master-20220930-1919353f`. 

Even though, after reinstallation, this issue can still be reproduced in master latest, like `master-20220930-1919353f`

**Comment by zhuwenxing** [comment]
master-20220930-1919353f
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test/detail/deploy_test/322/pipeline/299/

log:

[artifacts-standalone-reinstall-322-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9683158/artifacts-standalone-reinstall-322-server-logs.tar.gz)
[artifacts-standalone-reinstall-322-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9683161/artifacts-standalone-reinstall-322-pytest-logs.tar.gz)






```
[2022-09-30T09:28:53.865Z] <name>: deploy_test_index_type_HNSW_is_compacted_not_compacted_segment_status_only_growing_is_vector_indexed_is_vector_indexed_is_string_indexed_not_string_indexed_replica_number_0_is_deleted_is_deleted_data_size_3000
[2022-09-30T09:28:53.865Z] <partitions>: [{"name": "_default", "collection_name":......  (api_request.py:31)
[2022-09-30T09:28:53.865Z] [2022-09-30 09:20:59 - INFO - ci_test]: inserted 3000 data into collection deploy_test_index_type_HNSW_is_compacted_not_compacted_segment_status_only_growing_is_vector_indexed_is_vector_indexed_is_string_indexed_not_string_indexed_replica_number_0_is_deleted_is_deleted_data_size_3000 (common_func.py:684)
[2022-09-30T09:28:53.865Z] [2022-09-30 09:20:59 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [      int64   float varchar                                       float_vector
[2022-09-30T09:28:53.865Z] 0         0     0.0       0  [0.07240292862889093, 0.08823322087265024, 0.1...
[2022-09-30T09:28:53.865Z] 1         1     1.0       1  [0.09865428973088643, 0.07459551344740982, 0.0...
[2022-09-30T09:28:53.865Z] 2         2     2.0       2  [0.12992983309491024, 0.051220296......, kwargs: {'timeout': 20} (api_request.py:56)
[2022-09-30T09:28:53.865Z] [2022-09-30 09:21:00 - DEBUG - ci_test]: (api_response) : (insert count: 3000, delete count: 0, upsert count: 0, timestamp: 436346463196807169, success count: 3000, err count: 0)  (api_request.py:31)
[2022-09-30T09:28:53.865Z] [2022-09-30 09:21:00 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 20} (api_request.py:56)
[2022-09-30T09:28:53.865Z] [2022-09-30 09:21:03 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)
[2022-09-30T09:28:53.865Z] [2022-09-30 09:21:03 - INFO - ci_test]: [test][2022-09-30T09:21:00Z] [3.02998000s] deploy_test_index_type_HNSW_is_compacted_not_compacted_segment_status_only_growing_is_vector_indexed_is_vector_indexed_is_string_indexed_not_string_indexed_replica_number_0_is_deleted_is_deleted_data_size_3000 flush -> None (wrapper.py:30)
[2022-09-30T09:28:53.865Z] [2022-09-30 09:21:03 - DEBUG - ci_test]: (api_request)  : [Collection.delete] args: ['int64 in [0,1,2,3,4,5,6,7,8,9]', None, 20], kwargs: {} (api_request.py:56)
[2022-09-30T09:28:53.865Z] [2022-09-30 09:21:03 - DEBUG - ci_test]: (api_response) : (insert count: 0, delete count: 10, upsert count: 0, timestamp: 436346463996346372, success count: 0, err count: 0)  (api_request.py:31)
[2022-09-30T09:28:53.865Z] [2022-09-30 09:21:03 - INFO - ci_test]: [test][2022-09-30T09:21:03Z] [0.00189369s] deploy_test_index_type_HNSW_is_compacted_not_compacted_segment_status_only_growing_is_vector_indexed_is_vector_indexed_is_string_indexed_not_string_indexed_replica_number_0_is_deleted_is_deleted_data_size_3000 delete -> (insert count: 0, delete count: 10, upsert count: 0, timestamp: 436346463996346372, success count: 0, err count: 0) (wrapper.py:30)
[2022-09-30T09:28:53.865Z] [2022-09-30 09:21:03 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.00979697186970924, 0.15468895174235694, 0.08725491395013962, 0.024958289549485715, 0.14077295653068483, 0.000949355886638952, 0.09411812548819425, 0.07553452989124287, 0.07950877145550508, 0.05408657296234875, 0.03464951647037795, 0.06499997245645057, 0.01072572295293969, 0.029036586611494542, ......, kwargs: {} (api_request.py:56)
[2022-09-30T09:28:53.865Z] [2022-09-30 09:21:03 - DEBUG - ci_test]: (api_response) : ["['(distance: 0.3445100784301758, id: 279)', '(distance: 0.34661006927490234, id: 2170)', '(distance: 0.3485267162322998, id: 999)', '(distance: 0.35012680292129517, id: 2710)', '(distance: 0.35346880555152893, id: 1493)', '(distance: 0.35518544912338257, id: 2875)', '(distance: 0.35999372601509094......  (api_request.py:31)
[2022-09-30T09:28:53.865Z] [2022-09-30 09:21:03 - INFO - ci_test]: search_results_check: checking the searching results (func_check.py:209)
[2022-09-30T09:28:53.865Z] [2022-09-30 09:21:03 - INFO - ci_test]: search_results_check: Numbers of query searched is correct (func_check.py:224)
[2022-09-30T09:28:53.865Z] [2022-09-30 09:21:03 - INFO - ci_test]: search_results_check: limit (topK) and ids searched for 2 queries are correct (func_check.py:243)
[2022-09-30T09:28:53.865Z] [2022-09-30 09:21:03 - INFO - ci_test]: [test][2022-09-30T09:21:03Z] [0.21967678s] deploy_test_index_type_HNSW_is_compacted_not_compacted_segment_status_only_growing_is_vector_indexed_is_vector_indexed_is_string_indexed_not_string_indexed_replica_number_0_is_deleted_is_deleted_data_size_3000 search -> <pymilvus.orm.search.SearchResult object at 0x7f63bc4ee908> (wrapper.py:30)
[2022-09-30T09:28:53.865Z] [2022-09-30 09:21:03 - DEBUG - ci_test]: (api_request)  : [Collection.query] args: ['int64 in [0, 1]', ['int64'], None, 20], kwargs: {} (api_request.py:56)
[2022-09-30T09:28:53.865Z] [2022-09-30 09:21:03 - DEBUG - ci_test]: (api_response) : []  (api_request.py:31)
[2022-09-30T09:28:53.865Z] [2022-09-30 09:21:03 - INFO - ci_test]: [test][2022-09-30T09:21:03Z] [0.19795878s] deploy_test_index_type_HNSW_is_compacted_not_compacted_segment_status_only_growing_is_vector_indexed_is_vector_indexed_is_string_indexed_not_string_indexed_replica_number_0_is_deleted_is_deleted_data_size_3000 query -> [] (wrapper.py:30)
[2022-09-30T09:28:53.866Z] [2022-09-30 09:21:03 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['float_vector', {'index_type': 'IVF_FLAT', 'params': {'nlist': 128}, 'metric_type': 'L2'}], kwargs: {'timeout': 40, 'index_name': 'test_kWDtSM1K'} (api_request.py:56)
[2022-09-30T09:28:53.866Z] [2022-09-30 09:21:14 - DEBUG - ci_test]: (api_response) : Status(code=0, message='')  (api_request.py:31)
[2022-09-30T09:28:53.866Z] [2022-09-30 09:21:14 - INFO - ci_test]: [test][2022-09-30T09:21:03Z] [11.38881616s] deploy_test_index_type_HNSW_is_compacted_not_compacted_segment_status_only_growing_is_vector_indexed_is_vector_indexed_is_string_indexed_not_string_indexed_replica_number_0_is_deleted_is_deleted_data_size_3000 create_index -> Status(code=0, message='') (wrapper.py:30)
[2022-09-30T09:28:53.866Z] [2022-09-30 09:21:14 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['varchar', {}], kwargs: {'timeout': 40, 'index_name': 'test_Km9LUZWc'} (api_request.py:56)
[2022-09-30T09:28:53.866Z] [2022-09-30 09:21:35 - WARNING - pymilvus.decorators]: [93m[get_index_state] retry:4, cost: 0.27s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (decorators.py:72)
[2022-09-30T09:28:53.866Z] [2022-09-30 09:21:36 - WARNING - pymilvus.decorators]: [93m[get_index_state] retry:5, cost: 0.81s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (decorators.py:72)
[2022-09-30T09:28:53.866Z] [2022-09-30 09:21:36 - WARNING - pymilvus.decorators]: [93m[get_index_state] retry:6, cost: 2.43s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (decorators.py:72)
[2022-09-30T09:28:53.866Z] [2022-09-30 09:21:39 - WARNING - pymilvus.decorators]: [93m[get_index_state] retry:7, cost: 7.290000000000001s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (decorators.py:72)
[2022-09-30T09:28:53.866Z] [2022-09-30 09:21:46 - WARNING - pymilvus.decorators]: [93m[get_index_state] retry:8, cost: 21.870000000000005s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (decorators.py:72)
[2022-09-30T09:28:53.866Z] [2022-09-30 09:22:08 - WARNING - pymilvus.decorators]: [93m[get_index_state] retry:9, cost: 60s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (decorators.py:72)
[2022-09-30T09:28:53.866Z] [2022-09-30 09:23:08 - ERROR - pymilvus.decorators]: RPC error: [get_index_state], <MilvusUnavailableException: (code=1, message=server Unavailable: Retry timeout: 40s)>, <Time:{'RPC start': '2022-09-30 09:21:34.898667', 'RPC error': '2022-09-30 09:23:08.540616'}> (decorators.py:112)
[2022-09-30T09:28:53.866Z] [2022-09-30 09:23:08 - WARNING - pymilvus.decorators]: [93mRetry timeout: 40s[0m (decorators.py:80)
[2022-09-30T09:28:53.866Z] [2022-09-30 09:23:08 - ERROR - pymilvus.decorators]: RPC error: [wait_for_creating_index], <MilvusException: (code=1, message=Retry timeout: 40s, message=server Unavailable: Retry timeout: 40s)>, <Time:{'RPC start': '2022-09-30 09:21:14.992868', 'RPC error': '2022-09-30 09:23:08.541065'}> (decorators.py:112)
[2022-09-30T09:28:53.866Z] [2022-09-30 09:23:08 - WARNING - pymilvus.decorators]: [93mRetry timeout: 40s[0m (decorators.py:80)
[2022-09-30T09:28:53.866Z] [2022-09-30 09:23:08 - ERROR - pymilvus.decorators]: RPC error: [create_index], <MilvusException: (code=1, message=Retry timeout: 40s, message=Retry timeout: 40s, message=server Unavailable: Retry timeout: 40s)>, <Time:{'RPC start': '2022-09-30 09:21:14.894741', 'RPC error': '2022-09-30 09:23:08.541192'}> (decorators.py:112)
[2022-09-30T09:28:53.866Z] [2022-09-30 09:23:08 - ERROR - ci_test]: Traceback (most recent call last):
[2022-09-30T09:28:53.866Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 51, in handler
[2022-09-30T09:28:53.866Z]     return func(self, *args, **kwargs)
[2022-09-30T09:28:53.866Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 625, in get_index_state
[2022-09-30T09:28:53.866Z]     response = rf.result()
[2022-09-30T09:28:53.866Z]   File "/usr/local/lib/python3.7/dist-packages/grpc/_channel.py", line 744, in result
[2022-09-30T09:28:53.866Z]     raise self
[2022-09-30T09:28:53.866Z] grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
[2022-09-30T09:28:53.866Z] 	status = StatusCode.UNAVAILABLE
[2022-09-30T09:28:53.866Z] 	details = "failed to connect to all addresses"
[2022-09-30T09:28:53.866Z] 	debug_error_string = "{"created":"@1664529788.539397870","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3260,"referenced_errors":[{"created":"@1664529788.539396828","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":167,"grpc_status":14}]}"
[2022-09-30T09:28:53.866Z] >
[2022-09-30T09:28:53.866Z] 
[2022-09-30T09:28:53.866Z] During handling of the above exception, another exception occurred:
[2022-09-30T09:28:53.866Z] 
[2022-09-30T09:28:53.866Z] Traceback (most recent call last):
[2022-09-30T09:28:53.866Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 51, in handler
[2022-09-30T09:28:53.866Z]     return func(self, *args, **kwargs)
[2022-09-30T09:28:53.866Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 636, in wait_for_creating_index
[2022-09-30T09:28:53.866Z]     state, fail_reason = self.get_index_state(collection_name=collection_name, index_name=index_name, timeout=timeout)
[2022-09-30T09:28:53.866Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 113, in handler
[2022-09-30T09:28:53.866Z]     raise e
[2022-09-30T09:28:53.866Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 109, in handler
[2022-09-30T09:28:53.866Z]     return func(*args, **kwargs)
[2022-09-30T09:28:53.866Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 139, in handler
[2022-09-30T09:28:53.866Z]     ret = func(self, *args, **kwargs)
[2022-09-30T09:28:53.866Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 67, in handler
[2022-09-30T09:28:53.866Z]     raise MilvusUnavailableException(Status.UNEXPECTED_ERROR, f"server Unavailable: {timeout_msg}")
[2022-09-30T09:28:53.866Z] pymilvus.exceptions.MilvusUnavailableException: <MilvusUnavailableException: (code=1, message=server Unavailable: Retry timeout: 40s)>
[2022-09-30T09:28:53.866Z] 
[2022-09-30T09:28:53.866Z] During handling of the above exception, another exception occurred:
[2022-09-30T09:28:53.866Z] 
[2022-09-30T09:28:53.866Z] Traceback (most recent call last):
[2022-09-30T09:28:53.866Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 51, in handler
[2022-09-30T09:28:53.866Z]     return func(self, *args, **kwargs)
[2022-09-30T09:28:53.866Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 573, in create_index
[2022-09-30T09:28:53.866Z]     timeout=timeout)
[2022-09-30T09:28:53.866Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 113, in handler
[2022-09-30T09:28:53.866Z]     raise e
[2022-09-30T09:28:53.866Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 109, in handler
[2022-09-30T09:28:53.866Z]     return func(*args, **kwargs)
[2022-09-30T09:28:53.866Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 139, in handler
[2022-09-30T09:28:53.866Z]     ret = func(self, *args, **kwargs)
[2022-09-30T09:28:53.866Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 81, in handler
[2022-09-30T09:28:53.866Z]     raise MilvusException(e.code, f"{timeout_msg}, message={e.message}")
[2022-09-30T09:28:53.866Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 40s, message=server Unavailable: Retry timeout: 40s)>
[2022-09-30T09:28:53.866Z] 
[2022-09-30T09:28:53.866Z] During handling of the above exception, another exception occurred:
[2022-09-30T09:28:53.866Z] 
[2022-09-30T09:28:53.866Z] Traceback (most recent call last):
[2022-09-30T09:28:53.866Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2022-09-30T09:28:53.866Z]     res = func(*args, **_kwargs)
[2022-09-30T09:28:53.866Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2022-09-30T09:28:53.866Z]     return func(*arg, **kwargs)
[2022-09-30T09:28:53.866Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 1087, in create_index
[2022-09-30T09:28:53.866Z]     timeout=timeout, **kwargs)
[2022-09-30T09:28:53.866Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 113, in handler
[2022-09-30T09:28:53.866Z]     raise e
[2022-09-30T09:28:53.866Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 109, in handler
[2022-09-30T09:28:53.866Z]     return func(*args, **kwargs)
[2022-09-30T09:28:53.866Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 139, in handler
[2022-09-30T09:28:53.866Z]     ret = func(self, *args, **kwargs)
[2022-09-30T09:28:53.866Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 81, in handler
[2022-09-30T09:28:53.866Z]     raise MilvusException(e.code, f"{timeout_msg}, message={e.message}")
[2022-09-30T09:28:53.866Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 40s, message=Retry timeout: 40s, message=server Unavailable: Retry timeout: 40s)>
[2022-09-30T09:28:53.866Z]  (api_request.py:39)
[2022-09-30T09:28:53.866Z] [2022-09-30 09:23:08 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 40s, message=Retry timeout: 40s, message=server Unavailable: Retry timeout: 40s)> (api_request.py:40)
```

**Comment by zhuwenxing** [comment]
verifying
