### ISSUE TITLE
[Bug]: Proxy crash due to fatal error "concurrent map iteration and map write"

### ISSUE THREAD

**Issue by bigsheeper** [milvus-io/milvus#19454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.2-3c3ba55c
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): milvus-sdk-go github.com/milvus-io/milvus-sdk-go/v2 v2.1.2-0.20220823032848-8832edc6f96e
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Proxy crashed due to fatal error "concurrent map iteration and map write":
```
fatal error: concurrent map iteration and map write

goroutine 7154159 [running]:
runtime.throw(0x40578d8, 0x26)
	/usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc00881b538 sp=0xc00881b508 pc=0x887972
runtime.mapiternext(0xc00881b608)
	/usr/local/go/src/runtime/map.go:858 +0x54c fp=0xc00881b5b8 sp=0xc00881b538 pc=0x85ffec
github.com/milvus-io/milvus/internal/proxy.(*collectionInfo).CloneShardLeaders(0xc0063f4680, 0xc000e03380)
	/go/src/github.com/milvus-io/milvus/internal/proxy/meta_cache.go:85 +0xa5 fp=0xc00881b678 sp=0xc00881b5b8 pc=0x20ffb25
github.com/milvus-io/milvus/internal/proxy.(*MetaCache).GetShards(0xc0007241c0, 0x43b28d8, 0xc00b92c240, 0x1, 0xc0076d3160, 0x20, 0x0, 0x0, 0x0)
	/go/src/github.com/milvus-io/milvus/internal/proxy/meta_cache.go:608 +0x60d fp=0xc00881b818 sp=0xc00881b678 pc=0x2105e2d
github.com/milvus-io/milvus/internal/proxy.(*searchTask).Execute.func1(0xc00a859601, 0x27, 0xc007bb7b00)
	/go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:304 +0x91 fp=0xc00881b938 sp=0xc00881b818 pc=0x215e551
github.com/milvus-io/milvus/internal/proxy.(*searchTask).Execute(0xc006d118c0, 0x43b28d8, 0xc00b6ddfb0, 0x0, 0x0)
	/go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:331 +0x21e fp=0xc00881bbc8 sp=0xc00881b938 pc=0x214e83e
github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask(0xc000d12320, 0x43d9860, 0xc006d118c0, 0x43d5758, 0xc0007092c0)
	/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:465 +0x996 fp=0xc00881bfb8 sp=0xc00881bbc8 pc=0x2149c36
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc00881bfc0 sp=0xc00881bfb8 pc=0x8c2101
created by github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).queryLoop
	/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:525 +0x1a5
```

### Milvus Log

full proxy log:
[proxy_crash.log](https://github.com/milvus-io/milvus/files/9646117/proxy_crash.log)

**Comment by xiaofan-luan** [comment]
Should not even clone shards.

And all cache should the immutable(Copy on write). so no need to lock it and copy
