### ISSUE TITLE
[Bug]: [Nightly][kafka]Search failed reporting 'fail to search on all shard leaders, err=fail to Search, QueryNode ID=3, reason=Search 13 failed, reason  err err: rpc error: code = Canceled desc = context canceled'

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#19477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:911ea6c
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0.dev33
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Search failed reporting 'fail to search on all shard leaders, err=fail to Search, QueryNode ID=3, reason=Search 13 failed, reason  err err: rpc error: code = Canceled desc = context canceled'
```
[2022-09-26 21:50:46,932 - ERROR - ci_test]: Traceback (most recent call last):
  File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 717, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 113, in handler
    raise e
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 139, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 89, in handler
    raise e
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 464, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 428, in _execute_search_requests
    raise pre_err
  File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 419, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=3, reason=Search 13 failed, reason  err err: rpc error: code = Canceled desc = context canceled
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:232 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).Call
/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:227 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Search
/go/src/github.com/milvus-io/milvus/internal/querynode/shard_cluster.go:1058 github.com/milvus-io/milvus/internal/querynode.(*ShardCluster).Search.func2
/usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit
)>
 (api_request.py:39)
[2022-09-26 21:50:46,932 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=3, reason=Search 13 failed, reason  err err: rpc error: code = Canceled desc = context canceled
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/mi...... (api_request.py:40)
```

### Expected Behavior

PASSED

### Steps To Reproduce

```markdown
nightly: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/123/pipeline/155/
```

### Milvus Log

1. milvus log: [artifacts-milvus-distributed-kafka-nightly-123-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/123/artifact/artifacts-milvus-distributed-kafka-nightly-123-pymilvus-e2e-logs.tar.gz)
2. collection name:   search_collection_ANri5ztj
3. failed timeline: [2022-09-26T21:50:50.680Z] [gw0] [ 44%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_HNSW_index_with_max_ef[True-False-512-4]

**Comment by binbinlv** [comment]
@jaime0815 
This is the latest nightly issue occurring in kafka pipeline, could you help to have a look first? Thanks.
