### ISSUE TITLE
[Bug]: Datanode keep restarting during sending requests after upgrading from v2.1.2 to master-20220927-f6e7b92d

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#19478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.1.2 --> master-20220927-f6e7b92d
- Deployment mode(standalone or cluster): both
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/12268675/192458887-e2ffad4b-0c33-485a-b585-4a94b6aa4e1b.png)

```
[2022/09/27 06:51:55.705 +00:00] [DEBUG] [datanode/compactor.go:537] ["download deltalogs elapse in ms"] [planID=436275685000618504] [elapse=7.090695]
[2022/09/27 06:51:55.705 +00:00] [DEBUG] [datanode/compactor.go:476] ["inject elapse in ms"] [planID=436275685000618504] [elapse=0.030194]
[2022/09/27 06:51:55.705 +00:00] [DEBUG] [datanode/compactor.go:562] ["upload delta log elapse in ms"] [planID=436275685000618502] [elapse=23.505509]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x267d56e]

goroutine 3880656 [running]:
github.com/milvus-io/milvus/internal/datanode.(*SegmentReplica).mergeFlushedSegments(0xc001b917a0, 0xc0692e8f00, 0x60df66c8c9a2208, {0xc09720dce0?, 0x4, 0xc041c2e680?})
	/go/src/github.com/milvus-io/milvus/internal/datanode/segment_replica.go:782 +0x9ce
github.com/milvus-io/milvus/internal/datanode.(*compactionTask).compact(0xc064da6a00)
	/go/src/github.com/milvus-io/milvus/internal/datanode/compactor.go:613 +0x1ce5
github.com/milvus-io/milvus/internal/datanode.(*compactionExecutor).executeTask(0xc000416000, {0x3e29e10, 0xc064da6a00})
	/go/src/github.com/milvus-io/milvus/internal/datanode/compaction_executor.go:84 +0x183
created by github.com/milvus-io/milvus/internal/datanode.(*compactionExecutor).executeWithState
	/go/src/github.com/milvus-io/milvus/internal/datanode/compaction_executor.go:63 +0x99
```

```
[2022/09/27 06:45:18.048 +00:00] [INFO] [datanode/flow_graph_dmstream_input_node.go:49] ["datanode AsConsumer"] ["physical channel"=by-dev-rootcoord-dml_84] [subName=by-dev-dataNode-36-by-dev-rootcoord-dml_84_436275555857334273v0] ["collection ID"=436275555857334273]
[2022/09/27 06:45:18.048 +00:00] [INFO] [datanode/flow_graph_dmstream_input_node.go:54] ["datanode begin to seek"] ["seek msgID"="\u0008\ufffd\u0011\u0010\ufffd\u0004\u0018\u0000 \u0000"] ["physical channel"=by-dev-rootcoord-dml_84] ["collection ID"=436275555857334273]
[2022/09/27 06:45:18.048 +00:00] [INFO] [msgstream/mq_msgstream.go:883] ["MsgStream begin to seek start msg: "] [channel=by-dev-rootcoord-dml_84] [MessageID="CPgREOIEGAAgAA=="]
panic: Failed to create consumer by-dev-rootcoord-dml_255, error = All attempts results:
attempt #1:connection closed
attempt #2:server error: ConsumerBusy: Exclusive consumer is already connected


goroutine 216726 [running]:
github.com/milvus-io/milvus/internal/mq/msgstream.(*MqTtMsgStream).AsConsumerWithPosition(0xc00d06a400, {0xc000af3f20?, 0x1, 0x11db987?}, {0xc001025b40, 0x40}, 0x1)
	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_msgstream.go:658 +0x285
github.com/milvus-io/milvus/internal/mq/msgstream.(*MqTtMsgStream).AsConsumer(0xc0293cdf20?, {0xc000af3f20?, 0x3dfd858?, 0x3?}, {0xc001025b40?, 0xe5?})
	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_msgstream.go:627 +0x29
github.com/milvus-io/milvus/internal/datanode.newDmInputNode({0x3e1f718, 0xc031b76480}, 0xc0370d3260, 0xc00a8eb3b0)
	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_dmstream_input_node.go:47 +0x288
github.com/milvus-io/milvus/internal/datanode.(*dataSyncService).initNodes(0xc01a55d930, 0xc01a55d5f0)
	/go/src/github.com/milvus-io/milvus/internal/datanode/data_sync_service.go:283 +0x1605
github.com/milvus-io/milvus/internal/datanode.newDataSyncService({0x3e1f718, 0xc000b248c0}, 0xc00baba000, 0xc0370d3800, {0x3e3d4a8, 0xc0370d33e0}, {0x3e16c90?, 0xc004463a20}, {0x7fe54fd45f00, 0xc000d923f0}, ...)
	/go/src/github.com/milvus-io/milvus/internal/datanode/data_sync_service.go:109 +0x6aa
github.com/milvus-io/milvus/internal/datanode.(*flowgraphManager).addAndStart(0xc000d924b0, 0xc0004b0200, 0xc01a55d5f0)
	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_manager.go:52 +0x5c7
github.com/milvus-io/milvus/internal/datanode.(*DataNode).handlePutEvent(0xc0004b0200, 0xc01d735900, 0x5318040?)
	/go/src/github.com/milvus-io/milvus/internal/datanode/data_node.go:398 +0xa8
github.com/milvus-io/milvus/internal/datanode.(*channelEventManager).retryHandlePutEvent(0xc01d735940, {0x1, {0xc0293cdf20, 0x2d}, 0x1, 0xc01d735900})
	/go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:88 +0x10f
github.com/milvus-io/milvus/internal/datanode.(*channelEventManager).Run.func1()
	/go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:70 +0x12e
created by github.com/milvus-io/milvus/internal/datanode.(*channelEventManager).Run
	/go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:64 +0x56
```

### Expected Behavior

all pods can be ready after upgrading

### Milvus Log

deploy task: upgrade old image tag: v2.1.2 new image tag: master-20220927-f6e7b92d
failed job:https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test/detail/deploy_test/308/pipeline
[artifacts-cluster-upgrade-308-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/9652793/artifacts-cluster-upgrade-308-server-logs.1.tar.gz)
[artifacts-cluster-upgrade-308-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9652795/artifacts-cluster-upgrade-308-pytest-logs.tar.gz)

### Anything else?

I think the restart should not be caused by upgrading but caused by the request after the upgrade

**Comment by zhuwenxing** [comment]
same for standalone
![image](https://user-images.githubusercontent.com/12268675/192463386-62ad8a57-c090-429a-891f-6ee0b7c38305.png)

failed job:https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test/detail/deploy_test/307/pipeline
log:
[artifacts-standalone-upgrade-307-server-logs (2).tar.gz](https://github.com/milvus-io/milvus/files/9652936/artifacts-standalone-upgrade-307-server-logs.2.tar.gz)

[artifacts-standalone-upgrade-307-pytest-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/9652938/artifacts-standalone-upgrade-307-pytest-logs.1.tar.gz)

**Comment by zhuwenxing** [comment]
This also happened when reinstalling with master latest

failed job:https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test/detail/deploy_test/356/pipeline
log:
[artifacts-cluster-reinstall-356-server-logs (2).tar.gz](https://github.com/milvus-io/milvus/files/9738946/artifacts-cluster-reinstall-356-server-logs.2.tar.gz)

[artifacts-cluster-reinstall-356-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9738947/artifacts-cluster-reinstall-356-pytest-logs.tar.gz)

**Comment by XuanYang-cn** [comment]
For upgrade cases, the codes in master branch is too old. Please try master after this commit a0ce533727de0ba67cbdc517bfd101cc6330bb51
```
goroutine 3880656 [running]:
github.com/milvus-io/milvus/internal/datanode.(*SegmentReplica).mergeFlushedSegments(0xc001b917a0, 0xc0692e8f00, 0x60df66c8c9a2208, {0xc09720dce0?, 0x4, 0xc041c2e680?})
	/go/src/github.com/milvus-io/milvus/internal/datanode/segment_replica.go:782 +0x9ce
github.com/milvus-io/milvus/internal/datanode.(*compactionTask).compact(0xc064da6a00)
	/go/src/github.com/milvus-io/milvus/internal/datanode/compactor.go:613 +0x1ce5
```

I'm checking master reinstall cases now

**Comment by XuanYang-cn** [comment]
/assign @zhuwenxing 
/unassign
Please help verifying the latest master

**Comment by zhuwenxing** [comment]
Not reproduced, close it!
