### ISSUE TITLE
[Bug]: Querynode crash after pulsar pod failure chaos test for 2.1 branch

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#19472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.0-20220926-2753e054
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/12268675/192450619-4ed2f541-bb4d-4435-acd6-61749f2cbbb7.png)

log in querynode 
```
[2022/09/26 23:39:48.305 +00:00] [INFO] [querynode/task.go:315] ["watchDMChannel, add check points info for flushed segments done"] [collectionID=436269177887260673] [flushedSegmentIDs="[436269197036879874,436269187495100417,436269190771638273,436269193878044673,436269184414908418,436269185266876417,436269191898857474,436269184139395074,436269183195676674,436269194979049474,436269196158959618,436269192751087618,436269188608950274,436269186577596418,436269189919670273]"]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x22631f4]

goroutine 282 [running]:
github.com/milvus-io/milvus/internal/querynode.(*watchDmChannelsTask).Execute(0xc000d9fc80, 0x43b29d0, 0xc000e3d300, 0x0, 0x0)
	/go/src/github.com/milvus-io/milvus/internal/querynode/task.go:328 +0x2794
github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).processTask(0xc0006bc980, 0x43c8fe0, 0xc000d9fc80, 0x43c8ed8, 0xc0002de820)
	/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:110 +0x173
github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).taskLoop(0xc0006bc980)
	/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:127 +0x15a
created by github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).Start
	/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:135 +0x67
```

### Expected Behavior

all pod ready after chaos and all test passed

### Milvus Log

chaos type: pod-failure image tag: 2.1.0-20220926-2753e054 target pod: pulsar
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-for-release/detail/chaos-test-for-release/900/pipeline

log:
[artifacts-pulsar-pod-failure-900-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/9652345/artifacts-pulsar-pod-failure-900-server-logs.1.tar.gz)
[artifacts-pulsar-pod-failure-900-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9652347/artifacts-pulsar-pod-failure-900-pytest-logs.tar.gz)

### Anything else?

It is not a stable issue, at least, it passed for the latest job.
But for the pulsar pod failure chaos test, when all pods can be ready, the second test can not be passed.

**Comment by zhuwenxing** [comment]
Not reproduced in 2.1 and master branch, so close it
