### ISSUE TITLE
[Bug]: [Upgrade] Insert data raise error `getSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error` after upgrading from 2.1.2 to master-20220926-804c18df 

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#19473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.1.2 --> master-20220926-804c18df
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/12268675/192454112-e75290cf-ea14-458e-99cf-bcaacdf4c2d2.png)

```
[2022-09-26T09:27:13.427Z] Create collection...

[2022-09-26T09:27:13.427Z] collection name: task_1_FLAT

[2022-09-26T09:27:13.427Z] begin insert, count: 3000 nb: 300

[2022-09-26T09:27:13.427Z] [1/10] insert 300 data, time: 0.0535

[2022-09-26T09:27:13.427Z] [2/10] insert 300 data, time: 0.0557

[2022-09-26T09:27:13.427Z] [3/10] insert 300 data, time: 0.5582

[2022-09-26T09:27:13.427Z] [4/10] insert 300 data, time: 1.9090

[2022-09-26T09:27:13.427Z] [5/10] insert 300 data, time: 0.9004

[2022-09-26T09:27:13.427Z] [6/10] insert 300 data, time: 2.3828

[2022-09-26T09:27:13.427Z] [7/10] insert 300 data, time: 1.5391

[2022-09-26T09:27:13.427Z] Traceback (most recent call last):

[2022-09-26T09:27:13.427Z]   File "scripts/action_after_upgrade.py", line 98, in <module>

[2022-09-26T09:27:13.427Z]     task_1(data_size, host)

[2022-09-26T09:27:13.427Z]   File "scripts/action_after_upgrade.py", line 20, in task_1

[2022-09-26T09:27:13.427Z]     create_collections_and_insert_data(prefix, data_size)

[2022-09-26T09:27:13.427Z]   File "/home/jenkins/agent/workspace/tests/python_client/deploy/scripts/utils.py", line 91, in create_collections_and_insert_data

[2022-09-26T09:27:13.427Z]     vectors[nb*j:nb*j+nb]

[2022-09-26T09:27:13.427Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 555, in insert

[2022-09-26T09:27:13.427Z]     res = conn.bulk_insert(self._name, entities, partition_name, ids=None, timeout=timeout, schema=schema_dict, **kwargs)

[2022-09-26T09:27:13.427Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 101, in handler

[2022-09-26T09:27:13.427Z]     raise e

[2022-09-26T09:27:13.427Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 97, in handler

[2022-09-26T09:27:13.427Z]     return func(*args, **kwargs)

[2022-09-26T09:27:13.427Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 127, in handler

[2022-09-26T09:27:13.427Z]     ret = func(self, *args, **kwargs)

[2022-09-26T09:27:13.427Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 79, in handler

[2022-09-26T09:27:13.427Z]     raise e

[2022-09-26T09:27:13.427Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 50, in handler

[2022-09-26T09:27:13.427Z]     return func(self, *args, **kwargs)

[2022-09-26T09:27:13.427Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 385, in bulk_insert

[2022-09-26T09:27:13.427Z]     raise err

[2022-09-26T09:27:13.427Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 381, in bulk_insert

[2022-09-26T09:27:13.427Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2022-09-26T09:27:13.427Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=getSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error)>
```

### Expected Behavior

all test cases passed

### Milvus Log

deploy task: upgrade old image tag: v2.1.2 new image tag: master-20220926-804c18df

failed job:
https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test/detail/deploy_test/304/pipeline

log:

[artifacts-cluster-upgrade-304-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9652468/artifacts-cluster-upgrade-304-server-logs.tar.gz)

[artifacts-cluster-upgrade-304-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9652469/artifacts-cluster-upgrade-304-pytest-logs.tar.gz)

**Comment by soothing-rain** [comment]
@zhuwenxing The logs as appeared in `cluster-upgrade-304/second_deployment/pod_log/cluster-upgrade-304-milvus-proxy-665dfc8977-q8qnp.log` is not complete.

Can you provide the full logs? Also can you let me know if the proxy services restarted during the test, and if so, why? Thanks.

**Comment by zhuwenxing** [comment]
> @zhuwenxing The logs as appeared in `cluster-upgrade-304/second_deployment/pod_log/cluster-upgrade-304-milvus-proxy-665dfc8977-q8qnp.log` is not complete.
> 
> Can you provide the full logs? Also can you let me know if the proxy services restarted during the test, and if so, why? Thanks.


Proxy has not restarted, but datanode has restarted several times.

```
 + kubectl get pods -o wide
 + grep cluster-upgrade-304
 cluster-upgrade-304-etcd-0                                       1/1     Running     0                 34m     10.102.9.6      devops-node13   <none>           <none>
 cluster-upgrade-304-etcd-1                                       1/1     Running     0                 34m     10.102.10.184   devops-node20   <none>           <none>
 cluster-upgrade-304-etcd-2                                       1/1     Running     0                 34m     10.102.7.111    devops-node11   <none>           <none>
 cluster-upgrade-304-milvus-datacoord-589bd697f7-5jslz            1/1     Running     0                 34m     10.102.9.13     devops-node13   <none>           <none>
 cluster-upgrade-304-milvus-datanode-5c79cf6945-psgkw             1/1     Running     6 (12m ago)       34m     10.102.9.246    devops-node13   <none>           <none>
 cluster-upgrade-304-milvus-datanode-5c79cf6945-vdwz2             1/1     Running     5 (4m37s ago)     34m     10.102.10.180   devops-node20   <none>           <none>
 cluster-upgrade-304-milvus-indexcoord-8548bf6cf9-xtd6c           1/1     Running     0                 34m     10.102.9.8      devops-node13   <none>           <none>
 cluster-upgrade-304-milvus-indexnode-67c87fb949-mm49f            1/1     Running     0                 34m     10.102.7.108    devops-node11   <none>           <none>
 cluster-upgrade-304-milvus-indexnode-67c87fb949-pmj44            1/1     Running     0                 34m     10.102.7.109    devops-node11   <none>           <none>
 cluster-upgrade-304-milvus-indexnode-67c87fb949-wxmkg            1/1     Running     0                 34m     10.102.6.238    devops-node10   <none>           <none>
 cluster-upgrade-304-milvus-proxy-665dfc8977-q8qnp                1/1     Running     0                 34m     10.102.9.254    devops-node13   <none>           <none>
 cluster-upgrade-304-milvus-querycoord-646c54988d-54q4t           1/1     Running     0                 34m     10.102.9.16     devops-node13   <none>           <none>
 cluster-upgrade-304-milvus-querynode-59c46c776-9qzmk             1/1     Running     0                 34m     10.102.10.181   devops-node20   <none>           <none>
 cluster-upgrade-304-milvus-querynode-59c46c776-bkq6f             1/1     Running     0                 34m     10.102.9.244    devops-node13   <none>           <none>
 cluster-upgrade-304-milvus-querynode-59c46c776-w6rdv             1/1     Running     0                 34m     10.102.7.110    devops-node11   <none>           <none>
 cluster-upgrade-304-milvus-rootcoord-cdd5995dd-fjgvf             1/1     Running     0                 34m     10.102.9.5      devops-node13   <none>           <none>
 cluster-upgrade-304-minio-0                                      1/1     Running     0                 34m     10.102.9.14     devops-node13   <none>           <none>
 cluster-upgrade-304-minio-1                                      1/1     Running     0                 34m     10.102.10.183   devops-node20   <none>           <none>
 cluster-upgrade-304-minio-2                                      1/1     Running     0                 34m     10.102.5.129    devops-node21   <none>           <none>
 cluster-upgrade-304-minio-3                                      1/1     Running     0                 34m     10.102.7.112    devops-node11   <none>           <none>
 cluster-upgrade-304-pulsar-bookie-0                              1/1     Running     0                 34m     10.102.9.7      devops-node13   <none>           <none>
 cluster-upgrade-304-pulsar-bookie-1                              1/1     Running     0                 34m     10.102.5.128    devops-node21   <none>           <none>
 cluster-upgrade-304-pulsar-bookie-init-f2cc9                     0/1     Completed   0                 34m     10.102.9.18     devops-node13   <none>           <none>
 cluster-upgrade-304-pulsar-broker-0                              1/1     Running     0                 34m     10.102.9.15     devops-node13   <none>           <none>
 cluster-upgrade-304-pulsar-proxy-0                               1/1     Running     0                 34m     10.102.9.19     devops-node13   <none>           <none>
 cluster-upgrade-304-pulsar-pulsar-init-hhwk8                     0/1     Completed   0                 34m     10.102.9.247    devops-node13   <none>           <none>
 cluster-upgrade-304-pulsar-recovery-0                            1/1     Running     0                 33m     10.102.9.20     devops-node13   <none>           <none>
 cluster-upgrade-304-pulsar-zookeeper-0                           1/1     Running     0                 34m     10.102.9.17     devops-node13   <none>           <none>
```

**Comment by zhuwenxing** [comment]
>Can you provide the full logs?

for the full logs, you can go to Loki to get it

**Comment by zhuwenxing** [comment]
I rerun a test for v2.1.2 --> master-20220926-804c18df, this issue was not reproduced. So this issue would be a not stable issue.

**Comment by soothing-rain** [comment]
@zhuwenxing Shall we deprioritize this issue as it doesn't occur very often?

/assign @zhuwenxing
