### ISSUE TITLE
[Bug]: [diskann]Milvus create diskann index, then load failed"collection sift_100m_128_l2 has not been loaded to memory or load failed""

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#19493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220927-6972efe6
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus2.2.0dev32
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server-instance
fouram-tag-no-clean-9hjnk-1
server-configmap
server-single-8c32m256d-diskann
client-configmap
client-random-locust-100m-ddl-r8-w2-diskann

```
fouram-tag-no-clean-9hjnk-1-etcd-0                                1/1     Running     0              114s    10.104.4.36    4am-node11   <none>           <none>
fouram-tag-no-clean-9hjnk-1-milvus-standalone-78cd974c58-ld2vs    1/1     Running     0              114s    10.104.4.38    4am-node11   <none>           <none>
fouram-tag-no-clean-9hjnk-1-minio-746f6bf44d-rczkz                1/1     Running     0              114s    10.104.4.37    4am-node11   <none>           <none>
```

```
[2022-09-28 00:22:22,865] [   ERROR] - RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=collection sift_100m_128_l2 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-09-28 00:12:21.657526', 'RPC error': '2022-09-28 00:22:22.864978'}> (pymilvus.decorators:112)
[2022-09-28 00:22:22,866] [   ERROR] - RPC error: [load_collection], <MilvusException: (code=1, message=collection sift_100m_128_l2 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-09-28 00:12:21.628063', 'RPC error': '2022-09-28 00:22:22.866143'}> (pymilvus.decorators:112)
[2022-09-28 00:22:22,866] [   ERROR] - <MilvusException: (code=1, message=collection sift_100m_128_l2 has not been loaded to memory or load failed)> (milvus_benchmark.main:118)
[2022-09-28 00:22:22,870] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 87, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/locust.py", line 461, in prepare
    self.milvus.load_collection(replica_number=replica_number)
  File "/src/milvus_benchmark/client.py", line 53, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 592, in load_collection
    return self._milvus.load_collection(collection_name, **params)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/stub.py", line 195, in load_collection
    return handler.load_collection(collection_name=collection_name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 113, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 139, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 89, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 664, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 113, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 139, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 89, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 673, in wait_for_loading_collection
    return self._wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 702, in _wait_for_loading_collection
    progress = self.get_collection_loading_progress(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 681, in get_collection_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection sift_100m_128_l2 has not been loaded to memory or load failed)>
 (milvus_benchmark.main:119)
```
memory:
<img width="1381" alt="截屏2022-09-28 10 19 43" src="https://user-images.githubusercontent.com/34296482/192672741-ed22fc6c-b317-4f4d-8839-a3cfb8c8f3d1.png">

### Anything else?

client-random-locust-100m-ddl-r8-w2-diskann:
```
{
	"config.yaml": "locust_random_performance:
		  collections:
		    -
		      collection_name: sift_100m_128_l2
		      ni_per: 50000
		      build_index: true
		      index_type: diskann
		      index_param: {}
		      task:
		        types:
		          -
		            type: query
		            weight: 8
		            params:
		              top_k: 10
		              nq: 10
		              search_param:
		                nprobe: 16
		          -
		            type: load
		            weight: 1
		          -
		            type: get
		            weight: 8
		            params:
		              ids_length: 10
		          -
		            type: scene_test
		            weight: 2
		        connection_num: 1
		        clients_num: 20
		        spawn_rate: 2
		        during_time: 12h
		"
```

**Comment by xige-16** [comment]
disk ann index releated
```
[error="[UnexpectedError] Error in int64_t knowhere::IndexDiskANN<T>::Dim() [with T = float; int64_t = long int] at IndexDiskANN.cpp:503: index is not ready yet.
```

**Comment by xige-16** [comment]
Part of the index file data is lost
```
File size mismatch for /tmp/diskann/index_files/436318674013274814/1/_disk.index (size: 2147483648) with meta-data size: 2231369728
```

**Comment by xige-16** [comment]
The reason for data loss is that when the data is sliced, the offset value overflows. As a result, part of the index data is not uploaded to s3.
https://github.com/milvus-io/milvus/blob/0ac4bc32a5b1af9f91896290d23c72ad0ff55714/internal/core/src/storage/DiskFileManagerImpl.cpp#L96-L111

**Comment by xige-16** [comment]
please verify @jingkl 
/unassign
/assign @jingkl

**Comment by yanliang567** [comment]
verified on  master-20221009-49daee2e: loaded successfully for sift_100m
https://argo-workflows.zilliz.cc/workflows/qa/fouram-tag-no-clean-9hjnk-xlgsv?tab=workflow&nodeId=fouram-tag-no-clean-9hjnk-xlgsv-2610521050
