### ISSUE TITLE
[Bug]: [benchmark]Milvus load failed, raise an error"collection fouram_IVTfYjQ3 has not been loaded to memory or load failed"

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#19567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220928-a8cabbfa 
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0dev32
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

milvus-image-repository
harbor.milvus.io/milvus/milvus
deploy_tool
helm
release_name_prefix
fouramf-cron-1664380800
deploy_config
empty-file
case_params
empty-file
other_params
 --milvus_tag_prefix=master -s --tag_repository="harbor.milvus.io/dockerhub/milvusdb/milvus" 
case_name
test_search_filter_time

```
NAME                                                              READY   STATUS      RESTARTS       AGE    IP             NODE         NOMINATED NODE   READINESS GATES
fouramf-cron-1664380800-82-7904-etcd-0                            1/1     Running     0              112s   10.104.9.188   4am-node14   <none>           <none>
fouramf-cron-1664380800-82-7904-milvus-standalone-77cb9cfb98pv7   1/1     Running     0              112s   10.104.4.50    4am-node11   <none>           <none>
fouramf-cron-1664380800-82-7904-minio-6d777479c6-nb6q4            1/1     Running     0              112s   10.104.9.189   4am-node14   <none>           <none> (cli_client.py:123)
```

```
2022-09-28 16:38:13 - DEBUG - fouram]: (api_request)  : [Collection.load] args: [None, 1, None], kwargs: {} (api_request.py:53)"
[2022-09-28 16:48:14 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=collection fouram_IVTfYjQ3 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-09-28 16:38:14.015569', 'RPC error': '2022-09-28 16:48:14.777788'}> (decorators.py:112)"
[2022-09-28 16:48:14 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=collection fouram_IVTfYjQ3 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-09-28 16:38:13.888174', 'RPC error': '2022-09-28 16:48:14.777974'}> (decorators.py:112)"
[2022-09-28 16:48:14 - ERROR - fouram]: Traceback (most recent call last):
  File "/src/fouram/client/util/api_request.py", line 21, in inner_wrapper
    res = func(*args, **kwargs)
  File "/src/fouram/client/util/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 474, in load
    conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 113, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 139, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 89, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 664, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 113, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 139, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 89, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 673, in wait_for_loading_collection
    return self._wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 702, in _wait_for_loading_collection
    progress = self.get_collection_loading_progress(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 681, in get_collection_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection fouram_IVTfYjQ3 has not been loaded to memory or load failed)>
 (api_request.py:35)"
[2022-09-28 16:48:14 - ERROR - fouram]: (api_response) : <MilvusException: (code=1, message=collection fouram_IVTfYjQ3 has not been loaded to memory or load failed)> (api_request.py:36)"
[2022-09-28 16:48:14 - ERROR - fouram]: [CheckFunc] Request check failed, response:<MilvusException: (code=1, message=collection fouram_IVTfYjQ3 has not been loaded to memory or load failed)> (func_check.py:40)"
```

**Comment by yanliang567** [comment]
seems that fixes above not working, it reproduced on  master-20220930-e6c7286b

**Comment by yah01** [comment]
/assign @jingkl 
#19577 #19583 fixed it

**Comment by yanliang567** [comment]
not reproduced recently
