### ISSUE TITLE
[Bug]: Search failed with error `Search 17 failed, reason [UnexpectedError] Assert "System Field RowID or Timestamp is not loaded" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:396` after etcd pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#19579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220929-d79f88c5
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus==2.2.0.dev33
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/12268675/193178445-e836a718-aaa0-4297-98ea-93ebfab585e8.png)

```
[2022-09-29T21:03:17.710Z] [2022-09-29 21:02:26 - INFO - ci_test]: [test][2022-09-29T21:02:25Z] [0.13013328s] Checker__OGmxn8qp load -> None (wrapper.py:30)

[2022-09-29T21:03:17.710Z] [2022-09-29 21:02:26 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.12342888703574639, 0.07515275385268105, 0.08720777428875, 0.02925586159725634, 0.1267873428384587, 0.015177144761934219, 0.10912390028395587, 0.0053150740415805545, 0.01176917228405538, 0.06948338790746751, 0.003945952671581721, 0.030559212740576207, 0.005098919550058016, 0.1386284778449793, 0......., kwargs: {} (api_request.py:56)

[2022-09-29T21:03:17.710Z] [2022-09-29 21:02:26 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=17, reason=Search 18 failed, reason [UnexpectedError] Assert "System Field RowID or Timestamp is not loaded" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:396

[2022-09-29T21:03:17.710Z]  err %!w(<nil>))>, <Time:{'RPC start': '2022-09-29 21:02:26.029212', 'RPC error': '2022-09-29 21:02:26.310510'}> (decorators.py:112)

[2022-09-29T21:03:17.710Z] [2022-09-29 21:02:26 - ERROR - ci_test]: Traceback (most recent call last):

[2022-09-29T21:03:17.710Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2022-09-29T21:03:17.710Z]     res = func(*args, **_kwargs)

[2022-09-29T21:03:17.710Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2022-09-29T21:03:17.710Z]     return func(*arg, **kwargs)

[2022-09-29T21:03:17.710Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 718, in search

[2022-09-29T21:03:17.710Z]     partition_names, output_fields, round_decimal, timeout=timeout, schema=schema_dict, **kwargs)

[2022-09-29T21:03:17.710Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 113, in handler

[2022-09-29T21:03:17.710Z]     raise e

[2022-09-29T21:03:17.710Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 109, in handler

[2022-09-29T21:03:17.710Z]     return func(*args, **kwargs)

[2022-09-29T21:03:17.710Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 139, in handler

[2022-09-29T21:03:17.710Z]     ret = func(self, *args, **kwargs)

[2022-09-29T21:03:17.710Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 89, in handler

[2022-09-29T21:03:17.710Z]     raise e

[2022-09-29T21:03:17.710Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 51, in handler

[2022-09-29T21:03:17.710Z]     return func(self, *args, **kwargs)

[2022-09-29T21:03:17.710Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 464, in search

[2022-09-29T21:03:17.710Z]     return self._execute_search_requests(requests, timeout, **_kwargs)

[2022-09-29T21:03:17.710Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 428, in _execute_search_requests

[2022-09-29T21:03:17.710Z]     raise pre_err

[2022-09-29T21:03:17.710Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 419, in _execute_search_requests

[2022-09-29T21:03:17.710Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2022-09-29T21:03:17.710Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=17, reason=Search 18 failed, reason [UnexpectedError] Assert "System Field RowID or Timestamp is not loaded" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:396

[2022-09-29T21:03:17.710Z]  err %!w(<nil>))>

[2022-09-29T21:03:17.710Z]  (api_request.py:39)
```

### Expected Behavior

all test cases passed

### Milvus Log

chaos type: pod-kill image tag: master-20220929-d79f88c5 target pod: etcd
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/1725/pipeline/244/

log:
[artifacts-etcd-pod-kill-1725-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9680319/artifacts-etcd-pod-kill-1725-pytest-logs.tar.gz)

[artifacts-etcd-pod-kill-1725-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9680320/artifacts-etcd-pod-kill-1725-server-logs.tar.gz)

**Comment by zhuwenxing** [comment]
This issue also happened for datanode pod kill chaos test

chaos type: pod-kill image tag: master-20221006-e1124765 target pod: datanode
```

[2022-10-07T20:39:04.669Z] [2022-10-07 20:37:51 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 20], kwargs: {} (api_request.py:56)

[2022-10-07T20:39:04.669Z] [2022-10-07 20:37:51 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)

[2022-10-07T20:39:04.669Z] [2022-10-07 20:37:51 - INFO - ci_test]: [test][2022-10-07T20:37:51Z] [0.49705475s] Checker__xl2miCke load -> None (wrapper.py:30)

[2022-10-07T20:39:04.669Z] [2022-10-07 20:37:51 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.0671464093367479, 0.13773065863202874, 0.05801751082377284, 0.08435612315859688, 0.1127830582758124, 0.08559163609812086, 0.1355044696681561, 0.08105432979908883, 0.059678884189029016, 0.06661137021508255, 0.12405056088422507, 0.10673686082732373, 0.060365177521690766, 0.01635682279790765, 0.14......, kwargs: {} (api_request.py:56)

[2022-10-07T20:39:04.669Z] [2022-10-07 20:37:51 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=4, reason=Search 2 failed, reason [UnexpectedError] Assert "System Field RowID or Timestamp is not loaded" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:396

[2022-10-07T20:39:04.669Z]  err %!w(<nil>))>, <Time:{'RPC start': '2022-10-07 20:37:51.650922', 'RPC error': '2022-10-07 20:37:51.918067'}> (decorators.py:112)

[2022-10-07T20:39:04.669Z] [2022-10-07 20:37:51 - ERROR - ci_test]: Traceback (most recent call last):

[2022-10-07T20:39:04.669Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2022-10-07T20:39:04.669Z]     res = func(*args, **_kwargs)

[2022-10-07T20:39:04.669Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2022-10-07T20:39:04.669Z]     return func(*arg, **kwargs)

[2022-10-07T20:39:04.669Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 718, in search

[2022-10-07T20:39:04.669Z]     partition_names, output_fields, round_decimal, timeout=timeout, schema=schema_dict, **kwargs)

[2022-10-07T20:39:04.669Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 113, in handler

[2022-10-07T20:39:04.669Z]     raise e

[2022-10-07T20:39:04.669Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 109, in handler

[2022-10-07T20:39:04.669Z]     return func(*args, **kwargs)

[2022-10-07T20:39:04.669Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 139, in handler

[2022-10-07T20:39:04.669Z]     ret = func(self, *args, **kwargs)

[2022-10-07T20:39:04.669Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 89, in handler

[2022-10-07T20:39:04.669Z]     raise e

[2022-10-07T20:39:04.669Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 51, in handler

[2022-10-07T20:39:04.669Z]     return func(self, *args, **kwargs)

[2022-10-07T20:39:04.669Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 464, in search

[2022-10-07T20:39:04.669Z]     return self._execute_search_requests(requests, timeout, **_kwargs)

[2022-10-07T20:39:04.669Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 428, in _execute_search_requests

[2022-10-07T20:39:04.669Z]     raise pre_err

[2022-10-07T20:39:04.669Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 419, in _execute_search_requests

[2022-10-07T20:39:04.669Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2022-10-07T20:39:04.669Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=4, reason=Search 2 failed, reason [UnexpectedError] Assert "System Field RowID or Timestamp is not loaded" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:396

[2022-10-07T20:39:04.669Z]  err %!w(<nil>))>

[2022-10-07T20:39:04.669Z]  (api_request.py:39)

[2022-10-07T20:39:04.669Z] [2022-10-07 20:37:51 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=4, reason=Search 2 failed, reason [UnexpectedError] Assert "System Field RowID or Timestamp is not loaded" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:3...... (api_request.py:40)
```


failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/1948/pipeline
log:
[artifacts-datanode-pod-kill-1948-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9738274/artifacts-datanode-pod-kill-1948-server-logs.tar.gz)

[artifacts-datanode-pod-kill-1948-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9738275/artifacts-datanode-pod-kill-1948-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
Not reproduced
