### ISSUE TITLE
[Bug]: Malformed expression causes seg fault on delete operation

### ISSUE THREAD

**Issue by JohannesMessner** [milvus-io/milvus#19617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.1.4
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.1.3
- OS(Ubuntu or CentOS): Ubuntu 20.04.3 LTS
- CPU/Memory:  Intel i7-1195G7 11th Gen, 16GB RAM
- GPU: N/A
- Others: N/A
```

### Current Behavior

Passing a non-valid `expr` to `collection.delete()` causes a seg fault in `milvusdb`, taking down the DB.

### Expected Behavior

I think the non-valid expression should either be refused outright, or fail more gracefully.

### Steps To Reproduce

```markdown
1. Environment as described above
2. Start Milvus DB via docker compose
3. Run the following:

import numpy as np
from pymilvus import connections, Collection, FieldSchema, DataType, CollectionSchema

alias = 'test_alias'
conn = connections.connect(host='localhost', port=19530, alias=alias)

document_id = FieldSchema(name='document_id', dtype=DataType.VARCHAR, max_length=1024, is_primary=True)
embedding = FieldSchema(name='embedding', dtype=DataType.FLOAT_VECTOR, dim=5)

schema = CollectionSchema(fields=[document_id, embedding])
coll = Collection(
    name='test_collection',
    schema=schema,
    using=alias,
)

ids, embeddings = ['1'], [np.array([1,2,3,4,5])]
coll.insert([ids, embeddings])


coll.delete(expr='["1"]', consistency_level='Strong')
```

### Milvus Log

Error:
```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xf8 pc=0x211648c]
```
Full logs:
[milvus.log](https://github.com/milvus-io/milvus/files/9734013/milvus.log)

**Comment by yanliang567** [comment]
@binbinlv I think we should had this scenario in ci test, please confirm

**Comment by soothing-rain** [comment]
```
[32mmilvus-standalone |[0m [2022/10/07 12:47:16.008 +00:00] [INFO] [proxy/impl.go:2307] ["Start processing delete request in Proxy"] [traceID=b0556acd118ef0e]
[32mmilvus-standalone |[0m [2022/10/07 12:47:16.008 +00:00] [DEBUG] [proxy/impl.go:2347] ["Enqueue delete request in Proxy"] [role=proxy] [db=] [collection=test_collection] [partition=] [expr="[\"1\"]"]
[32mmilvus-standalone |[0m [2022/10/07 12:47:16.008 +00:00] [DEBUG] [allocator/id.go:140] ["IDAllocator pickCanDoFunc"] [need=1] [total=199959] [remainReqCnt=0]
[32mmilvus-standalone |[0m [2022/10/07 12:47:16.008 +00:00] [DEBUG] [proxy/impl.go:2368] ["Detail of delete request in Proxy"] [role=proxy] [msgID=436508244855226410] [timestamp=436508252169043973] [db=] [collection=test_collection] [partition=] [expr="[\"1\"]"] [traceID=b0556acd118ef0e]
[32mmilvus-standalone |[0m [2022/10/07 12:47:16.008 +00:00] [DEBUG] [proxy/task_scheduler.go:257] ["Proxy dmTaskQueue popPChanStats"] [taskID=436508244855226410]
[32mmilvus-standalone |[0m panic: runtime error: invalid memory address or nil pointer dereference
[32mmilvus-standalone |[0m [signal SIGSEGV: segmentation violation code=0x1 addr=0xf8 pc=0x211648c]
[32mmilvus-standalone |[0m 
[32mmilvus-standalone |[0m goroutine 17411336 [running]:
[32mmilvus-standalone |[0m github.com/milvus-io/milvus/internal/proxy.(*parserContext).handleExpr(0xc003129530, 0xc0046fd878, 0xc0046fd878, 0x0, 0x0)
[32mmilvus-standalone |[0m 	/go/src/github.com/milvus-io/milvus/internal/proxy/plan_parser.go:861 +0xcc
[32mmilvus-standalone |[0m github.com/milvus-io/milvus/internal/proxy.parseExpr(0xc000c29140, 0xc0056b1758, 0x5, 0x0, 0x0, 0x0)
[32mmilvus-standalone |[0m 	/go/src/github.com/milvus-io/milvus/internal/proxy/plan_parser.go:270 +0xf9
[32mmilvus-standalone |[0m github.com/milvus-io/milvus/internal/proxy.createExprPlan(0xc0087f0ae0, 0xc0056b1758, 0x5, 0x3, 0x3, 0x43c6d70)
[32mmilvus-standalone |[0m 	/go/src/github.com/milvus-io/milvus/internal/proxy/plan_parser.go:906 +0x67
[32mmilvus-standalone |[0m github.com/milvus-io/milvus/internal/proxy.getPrimaryKeysFromExpr(0xc0087f0ae0, 0xc0056b1758, 0x5, 0xc0056b1760, 0xf, 0xc0087f0ae0, 0x0)
[32mmilvus-standalone |[0m 	/go/src/github.com/milvus-io/milvus/internal/proxy/task.go:2569 +0x6c
[32mmilvus-standalone |[0m github.com/milvus-io/milvus/internal/proxy.(*deleteTask).PreExecute(0xc000d3e680, 0x43b7db8, 0xc005e40330, 0x1, 0x100)
[32mmilvus-standalone |[0m 	/go/src/github.com/milvus-io/milvus/internal/proxy/task.go:2662 +0x476
[32mmilvus-standalone |[0m github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask(0xc00211ef00, 0x43de340, 0xc000d3e680, 0x43dac60, 0xc004138b70)
[32mmilvus-standalone |[0m 	/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:452 +0x56b
[32mmilvus-standalone |[0m created by github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).manipulationLoop
[32mmilvus-standalone |[0m 	/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:509 +0x177
```

Was a nullptr deference.

/unassign
/assign @cydrain

**Comment by binbinlv** [comment]
> @binbinlv I think we should had this scenario in ci test, please confirm

Yes, we had test cases covering the scenario deleting using invalid expression (invalid type like (1),  invalid value like ("12-s", '()'), but this issue only happens when expr = '[]', and we did not cover this corner case in invalid expressions.

Will add it.

**Comment by xiaofan-luan** [comment]
@JohannesMessner should be fixed on latest master branch, thanks for pointing it out
