### ISSUE TITLE
[Bug]: Standalone panic during test after standalone pod kill or pod failure chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#19619]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20221006-e1124765
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus==2.2.0.dev33
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Almost test cases failed due to connection,  then find it was caused by standalone restarting 

```
+ kubectl get pods -o wide
 + grep standalone-pod-kill-1946
 standalone-pod-kill-1946-etcd-0                               1/1     Running       0               18m     10.102.6.138    devops-node10   <none>           <none>
 standalone-pod-kill-1946-milvus-standalone-756fd45dc6-x45xn   0/1     Running       5 (2m38s ago)   18m     10.102.10.46    devops-node20   <none>           <none>
 standalone-pod-kill-1946-minio-fbdf4f6d8-q8kzc                1/1     Running       0               18m     10.102.6.139    devops-node10   <none>           <none>
```

panic log:
```
2022/10/07 20:36:48.738 +00:00] [INFO] [datanode/segment_replica.go:456] ["begin to init pk bloom filter"] [segmentID=436515598023200107] ["stats bin logs"=1]
[2022/10/07 20:36:48.779 +00:00] [INFO] [datanode/segment_replica.go:777] ["merge flushed segments"] ["segment ID"=436515598023200107] ["collection ID"=436515410687233449] ["partition ID"=436515410687233450] ["compacted from"="[436515410687234006,436515410687234041,436515410687234522,436515410687234249,436515410687234057,436515410687234351,436515410687234126,436515410687233980]"] [planID=436515598023200105] ["channel name"=by-dev-rootcoord-dml_6_436515410687233449v0]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x26bb10e]

goroutine 394315 [running]:
github.com/milvus-io/milvus/internal/datanode.(*SegmentReplica).mergeFlushedSegments(0xc006b4eea0, 0xc0190d4300, 0x60ed09fa7170d69, {0xc002529d80?, 0x8, 0x1?})
	/go/src/github.com/milvus-io/milvus/internal/datanode/segment_replica.go:782 +0x9ce
github.com/milvus-io/milvus/internal/datanode.(*DataNode).SyncSegments(0xc000c08500, {0x3e81d98, 0xc006133710}, 0xc00755a770)
	/go/src/github.com/milvus-io/milvus/internal/datanode/data_node.go:933 +0x9b6
github.com/milvus-io/milvus/internal/distributed/datanode.(*Server).SyncSegments(0xf?, {0x3e81d98?, 0xc006133710?}, 0xf?)
	/go/src/github.com/milvus-io/milvus/internal/distributed/datanode/service.go:386 +0x2e
github.com/milvus-io/milvus/internal/proto/datapb._DataNode_SyncSegments_Handler.func1({0x3e81d98, 0xc006133710}, {0x3983aa0?, 0xc00755a770})
	/go/src/github.com/milvus-io/milvus/internal/proto/datapb/data_coord.pb.go:6474 +0x78
github.com/milvus-io/milvus/internal/util/logutil.UnaryTraceLoggerInterceptor({0x3e81d98?, 0xc006133680?}, {0x3983aa0, 0xc00755a770}, 0x3e6e980?, 0xc0123f47e0)
	/go/src/github.com/milvus-io/milvus/internal/util/logutil/grpc_interceptor.go:22 +0x49
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x3e81d98?, 0xc006133680?}, {0x3983aa0?, 0xc00755a770?})
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a
github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1({0x3e81d98, 0xc0061335f0}, {0x3983aa0, 0xc00755a770}, 0xc006c3e460?, 0xc006c3e480)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38 +0x16a
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x3e81d98?, 0xc0061335f0?}, {0x3983aa0?, 0xc00755a770?})
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1({0x3e81d98, 0xc0061335f0}, {0x3983aa0, 0xc00755a770}, 0xc00973daf0?, 0x374b3e0?)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34 +0xbf
github.com/milvus-io/milvus/internal/proto/datapb._DataNode_SyncSegments_Handler({0x39e3440?, 0xc000c92960}, {0x3e81d98, 0xc0061335f0}, 0xc006377140, 0xc001916690)
	/go/src/github.com/milvus-io/milvus/internal/proto/datapb/data_coord.pb.go:6476 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0016408c0, {0x3e90f00, 0xc0014256c0}, 0xc00a8aaa20, 0xc001916810, 0x529df20, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1283 +0xcfd
google.golang.org/grpc.(*Server).handleStream(0xc0016408c0, {0x3e90f00, 0xc0014256c0}, 0xc00a8aaa20, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1620 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:920 +0x28a

```

### Expected Behavior

all test cases passed

### Milvus Log

failed job: 
https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/1946/pipeline

log:
[artifacts-standalone-pod-kill-1946-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9738291/artifacts-standalone-pod-kill-1946-server-logs.tar.gz)

[artifacts-standalone-pod-kill-1946-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9738292/artifacts-standalone-pod-kill-1946-pytest-logs.tar.gz)

**Comment by soothing-rain** [comment]
/assign @XuanYang-cn 
/unassign @yanliang567 

https://github.com/milvus-io/milvus/blob/master/internal/datanode/segment_replica.go#L779-L782

Guess we need a safer check?

**Comment by zhuwenxing** [comment]
It looks same as https://github.com/milvus-io/milvus/issues/19478

**Comment by xiaofan-luan** [comment]
close duplicate issue
