### ISSUE TITLE
[Bug]: Load collection timeout after many pod kill and  pod failure chaos test when Kafka is as MQ for Milvus

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#19633]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20221006-e1124765
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2022-10-07T20:24:57.877Z] [2022-10-07 20:23:32 - INFO - ci_test]: assert index entities: 23020 (test_all_collections_after_chaos.py:70)

[2022-10-07T20:24:57.877Z] [2022-10-07 20:23:32 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['float_vector', {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}], kwargs: {'name': 'test_nLBGhh88', 'timeout': 40, 'index_name': '_default_idx'} (api_request.py:56)

[2022-10-07T20:24:57.877Z] [2022-10-07 20:23:34 - DEBUG - ci_test]: (api_response) : Status(code=0, message='')  (api_request.py:31)

[2022-10-07T20:24:57.877Z] [2022-10-07 20:23:34 - INFO - ci_test]: [test][2022-10-07T20:23:32Z] [1.99804586s] Checker__vQjDwsCg create_index -> Status(code=0, message='') (wrapper.py:30)

[2022-10-07T20:24:57.877Z] [2022-10-07 20:23:34 - INFO - ci_test]: assert index: 1.9982595443725586 (test_all_collections_after_chaos.py:77)

[2022-10-07T20:24:57.877Z] [2022-10-07 20:23:34 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 20], kwargs: {} (api_request.py:56)

[2022-10-07T20:24:57.877Z] [2022-10-07 20:24:08 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=-1, message=wait for loading collection timeout)>, <Time:{'RPC start': '2022-10-07 20:23:34.767031', 'RPC error': '2022-10-07 20:24:08.817218'}> (decorators.py:112)

[2022-10-07T20:24:57.877Z] [2022-10-07 20:24:08 - WARNING - pymilvus.decorators]: Retry timeout: 20s (decorators.py:80)

[2022-10-07T20:24:57.877Z] [2022-10-07 20:24:08 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=-1, message=Retry timeout: 20s, message=wait for loading collection timeout)>, <Time:{'RPC start': '2022-10-07 20:23:34.723081', 'RPC error': '2022-10-07 20:24:08.817612'}> (decorators.py:112)

[2022-10-07T20:24:57.877Z] [2022-10-07 20:24:08 - ERROR - ci_test]: Traceback (most recent call last):

[2022-10-07T20:24:57.877Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 51, in handler

[2022-10-07T20:24:57.877Z]     return func(self, *args, **kwargs)

[2022-10-07T20:24:57.877Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 656, in load_collection

[2022-10-07T20:24:57.877Z]     self.wait_for_loading_collection(collection_name, timeout)

[2022-10-07T20:24:57.877Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 113, in handler

[2022-10-07T20:24:57.877Z]     raise e

[2022-10-07T20:24:57.877Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 109, in handler

[2022-10-07T20:24:57.877Z]     return func(*args, **kwargs)

[2022-10-07T20:24:57.877Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 139, in handler

[2022-10-07T20:24:57.877Z]     ret = func(self, *args, **kwargs)

[2022-10-07T20:24:57.877Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 89, in handler

[2022-10-07T20:24:57.877Z]     raise e

[2022-10-07T20:24:57.877Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 51, in handler

[2022-10-07T20:24:57.877Z]     return func(self, *args, **kwargs)

[2022-10-07T20:24:57.877Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 665, in wait_for_loading_collection

[2022-10-07T20:24:57.877Z]     return self._wait_for_loading_collection(collection_name, timeout)

[2022-10-07T20:24:57.877Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 699, in _wait_for_loading_collection

[2022-10-07T20:24:57.877Z]     raise MilvusException(-1, "wait for loading collection timeout")

[2022-10-07T20:24:57.877Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=-1, message=wait for loading collection timeout)>

[2022-10-07T20:24:57.877Z] 

[2022-10-07T20:24:57.877Z] During handling of the above exception, another exception occurred:

[2022-10-07T20:24:57.877Z] 

[2022-10-07T20:24:57.877Z] Traceback (most recent call last):

[2022-10-07T20:24:57.877Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2022-10-07T20:24:57.877Z]     res = func(*args, **_kwargs)

[2022-10-07T20:24:57.877Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2022-10-07T20:24:57.877Z]     return func(*arg, **kwargs)

[2022-10-07T20:24:57.877Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 474, in load

[2022-10-07T20:24:57.877Z]     conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)

[2022-10-07T20:24:57.877Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 113, in handler

[2022-10-07T20:24:57.877Z]     raise e

[2022-10-07T20:24:57.877Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 109, in handler

[2022-10-07T20:24:57.877Z]     return func(*args, **kwargs)

[2022-10-07T20:24:57.877Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 139, in handler

[2022-10-07T20:24:57.877Z]     ret = func(self, *args, **kwargs)

[2022-10-07T20:24:57.877Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 81, in handler

[2022-10-07T20:24:57.877Z]     raise MilvusException(e.code, f"{timeout_msg}, message={e.message}")

[2022-10-07T20:24:57.877Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=-1, message=Retry timeout: 20s, message=wait for loading collection timeout)>

[2022-10-07T20:24:57.877Z]  (api_request.py:39)

[2022-10-07T20:24:57.877Z] [2022-10-07 20:24:08 - ERROR - ci_test]: (api_response) : <MilvusException: (code=-1, message=Retry timeout: 20s, message=wait for loading collection timeout)> (api_request.py:40)
```

### Expected Behavior

all test cases passed

### Milvus Log

failed job:  https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka/detail/chaos-test-kafka/1780/pipeline
log:
[artifacts-querynode-pod-failure-1780-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9738826/artifacts-querynode-pod-failure-1780-server-logs.tar.gz)

[artifacts-querynode-pod-failure-1780-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9738827/artifacts-querynode-pod-failure-1780-pytest-logs.tar.gz)

### Anything else?

![image](https://user-images.githubusercontent.com/12268675/194699644-fc2d3a9b-099c-4554-9ffc-9330dd40a11f.png)

**Comment by zhuwenxing** [comment]
The log is not completed, so for the full log, please go to Loki

**Comment by zhuwenxing** [comment]
For now, It works well for proxy pod kill chaos test, but others still have this issue.

**Comment by zhuwenxing** [comment]
![image](https://user-images.githubusercontent.com/12268675/195482615-ec7ed940-027f-4709-925f-b72e58fe6fe8.png)

**Comment by zhuwenxing** [comment]
When the timeout is set to 360s, some cases still fail.

chaos type: pod-failure image tag: master-20221029-a8e2a69a target pod: querycoord
failed job:https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka/detail/chaos-test-kafka/2377/pipeline
log:
[artifacts-querycoord-pod-failure-2377-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9897841/artifacts-querycoord-pod-failure-2377-server-logs.tar.gz)

[artifacts-querycoord-pod-failure-2377-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9897842/artifacts-querycoord-pod-failure-2377-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
It all failed at the loading step for the cluster Kafka version
![image](https://user-images.githubusercontent.com/12268675/199916251-b1484180-6560-4b3b-a926-a46945097884.png)
 
And this blocked other issue verification such as search issues.
