### ISSUE TITLE
[Bug]: [Stability] Milvus crashes if running tests with query, insert and delete requests

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#19644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220930-08ade66c
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.0-dev33
```

### Current Behavior

Milvus crashes during stability test with search, query, insert and delete concurrently
client config: client-random-locust-insert-delete-search-filter
```
{
	"config.yaml": "locust_random_performance:
		  collections:
		    -
		      collection_name: sift_10w_128_l2
		      ni_per: 50000
		      other_fields: float1
		      build_index: true
		      index_type: hnsw
		      index_param:
		        M: 8
		        efConstruction: 200
		      task:
		        types:
		          -
		            type: query
		            weight: 10
		            params:
		              top_k: 10
		              nq: 10
		              search_param:
		                ef: 16
		              filters:
		                -
		                  range: \"{'range': {'float1': {'GT': collection_size * 0.5, 'LT': collection_size * 1}}}\"
		          -
		            type: load
		            weight: 2
		          -
		            type: get
		            weight: 5
		            params:
		              ids_length: 10
		          -
		            type: insert
		            weight: 1
		            params:
		              ni_per: 1
		          -
		            type: delete
		            weight: 1
		            params:
		              ni_per: 1
		        connection_num: 1
		        clients_num: 20
		        spawn_rate: 2
		        # during_time: 84h
		        during_time: 72h
		"
}
```

### Expected Behavior

no crash and all requests return successfully

### Steps To Reproduce

```markdown
https://argo-workflows.zilliz.cc/workflows/qa/fouram-g864x?tab=workflow&nodeId=fouram-g864x-3353266211&nodePanelView=inputs-outputs
```

### Milvus Log

go to loki for full logs
```
Common labels: {"cluster":"4am","component":"standalone","job":"qa-milvus/milvus","namespace":"qa-milvus","node_name":"4am-node12","pod":"fouram-g864x-1-milvus-standalone-6449cccbfd-cflbs","app":"milvus","container":"standalone"}
Line limit: 1000
Total bytes processed: "668  kB"


2022-10-03T00:41:40+08:00		/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:920 +0x28a
2022-10-03T00:41:40+08:00	created by google.golang.org/grpc.(*Server).serveStreams.func1
2022-10-03T00:41:40+08:00		/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:922 +0x98
2022-10-03T00:41:40+08:00	google.golang.org/grpc.(*Server).serveStreams.func1.2()
2022-10-03T00:41:40+08:00		/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1620 +0xa1b
2022-10-03T00:41:40+08:00	google.golang.org/grpc.(*Server).handleStream(0xc0007d96c0, {0x3e64820, 0xc001ffbba0}, 0xc006e9eb40, 0x0)
2022-10-03T00:41:40+08:00		/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1283 +0xcfd
2022-10-03T00:41:40+08:00	google.golang.org/grpc.(*Server).processUnaryRPC(0xc0007d96c0, {0x3e64820, 0xc001ffbba0}, 0xc006e9eb40, 0xc003825cb0, 0x525b080, 0x0)
2022-10-03T00:41:40+08:00		/go/src/github.com/milvus-io/milvus/internal/proto/datapb/data_coord.pb.go:6476 +0x138
2022-10-03T00:41:40+08:00	github.com/milvus-io/milvus/internal/proto/datapb._DataNode_SyncSegments_Handler({0x39bc320?, 0xc000d25220}, {0x3e55720, 0xc006e95620}, 0xc00f696c60, 0xc003825b30)
2022-10-03T00:41:40+08:00		/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34 +0xbf
2022-10-03T00:41:40+08:00	github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1({0x3e55720, 0xc006e95620}, {0x395cc20, 0xc000c7c0e0}, 0xc000624af0?, 0x37283e0?)
2022-10-03T00:41:40+08:00		/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a
2022-10-03T00:41:40+08:00	github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x3e55720?, 0xc006e95620?}, {0x395cc20?, 0xc000c7c0e0?})
2022-10-03T00:41:40+08:00		/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38 +0x16a
2022-10-03T00:41:40+08:00	github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1({0x3e55720, 0xc006e95620}, {0x395cc20, 0xc000c7c0e0}, 0xc006be2f20?, 0xc006be2f40)
2022-10-03T00:41:40+08:00		/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a
2022-10-03T00:41:40+08:00	github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x3e55720?, 0xc006e956b0?}, {0x395cc20?, 0xc000c7c0e0?})
2022-10-03T00:41:40+08:00		/go/src/github.com/milvus-io/milvus/internal/util/logutil/grpc_interceptor.go:22 +0x49
2022-10-03T00:41:40+08:00	github.com/milvus-io/milvus/internal/util/logutil.UnaryTraceLoggerInterceptor({0x3e55720?, 0xc006e956b0?}, {0x395cc20, 0xc000c7c0e0}, 0x3e42480?, 0xc0074fd0e0)
2022-10-03T00:41:40+08:00		/go/src/github.com/milvus-io/milvus/internal/proto/datapb/data_coord.pb.go:6474 +0x78
2022-10-03T00:41:40+08:00	github.com/milvus-io/milvus/internal/proto/datapb._DataNode_SyncSegments_Handler.func1({0x3e55720, 0xc006e95740}, {0x395cc20?, 0xc000c7c0e0})
2022-10-03T00:41:40+08:00		/go/src/github.com/milvus-io/milvus/internal/distributed/datanode/service.go:386 +0x2e
2022-10-03T00:41:40+08:00	github.com/milvus-io/milvus/internal/distributed/datanode.(*Server).SyncSegments(0xf?, {0x3e55720?, 0xc006e95740?}, 0x10?)
2022-10-03T00:41:40+08:00		/go/src/github.com/milvus-io/milvus/internal/datanode/data_node.go:933 +0x9b6
2022-10-03T00:41:40+08:00	github.com/milvus-io/milvus/internal/datanode.(*DataNode).SyncSegments(0xc0007a6d00, {0x3e55720, 0xc006e95740}, 0xc000c7c0e0)
2022-10-03T00:41:40+08:00		/go/src/github.com/milvus-io/milvus/internal/datanode/segment_replica.go:782 +0x9ce
2022-10-03T00:41:40+08:00	github.com/milvus-io/milvus/internal/datanode.(*SegmentReplica).mergeFlushedSegments(0xc002114180, 0xc006b99a00, 0x60e63d6160101af, {0xc002a17040?, 0x2, 0x1?})
2022-10-03T00:41:40+08:00	goroutine 73423623 [running]:
2022-10-03T00:41:40+08:00	
2022-10-03T00:41:40+08:00	[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x269eece]
2022-10-03T00:41:40+08:00	panic: runtime error: invalid memory address or nil pointer dereference
2022-10-03T00:41:40+08:00	[2022/10/02 16:41:40.963 +00:00] [DEBUG] [proxy/impl.go:676] ["DescribeCollection done"] [traceID=7507708cb906c586] [role=proxy] [MsgID=436395985044768838] [BeginTS=436398693011161091] [EndTS=436398693011161091] [db=] [collection=sift_10w_128_l2]
2022-10-03T00:41:40+08:00	[2022/10/02 16:41:40.963 +00:00] [INFO] [datanode/segment_replica.go:777] ["merge flushed segments"] ["segment ID"=436395985044832688] ["collection ID"=436348556669553987] ["partition ID"=436348556669553988] ["compacted from"="[436348556857559969,436395509919679665]"] [planID=436395985044832687] ["channel name"=by-dev-rootcoord-dml_0_436348556669553987v0]
```

**Comment by yanliang567** [comment]
resubmit a task fouram-hdtgq for verification

**Comment by yanliang567** [comment]
The task is still running after 2.5 days, I will check it again in 2 more days

**Comment by yanliang567** [comment]
not reproduced
