### ISSUE TITLE
[Bug]: [Nightly] Query failed with message 'fail to search on all shard leaders, err=fail to Query, QueryNode ID = 10, reason=historical query failed on nodeID 20, reason = query shard(channel)  by-dev-rootcoord-dml_..  does not exist'

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#19654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:706b8e9
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.1.3.dev1
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Query failed with message 'fail to search on all shard leaders, err=fail to Query, QueryNode ID = 10, reason=historical query failed on nodeID 20, reason = query shard(channel)  by-dev-rootcoord-dml_..  does not exist'
```
[2022-10-08T21:09:10.320Z] [2022-10-08 20:28:20 - ERROR - pymilvus.decorators]: RPC error: [query], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Query, QueryNode ID = 10, reason=historical query failed on nodeID 20, reason = query shard(channel)  by-dev-rootcoord-dml_61_436538146946023425v0  does not exist
[2022-10-08T21:09:10.320Z] , err = %!w(<nil>))>, <Time:{'RPC start': '2022-10-08 20:28:19.819678', 'RPC error': '2022-10-08 20:28:20.186033'}> (decorators.py:95)
[2022-10-08T21:09:10.320Z] [2022-10-08 20:28:20 - ERROR - ci_test]: Traceback (most recent call last):
[2022-10-08T21:09:10.320Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
[2022-10-08T21:09:10.320Z]     res = func(*args, **kwargs)
[2022-10-08T21:09:10.320Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 56, in api_request
[2022-10-08T21:09:10.320Z]     return func(*arg, **kwargs)
[2022-10-08T21:09:10.320Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 796, in query
[2022-10-08T21:09:10.320Z]     res = conn.query(self._name, expr, output_fields, partition_names, timeout=timeout, schema=schema_dict, **kwargs)
[2022-10-08T21:09:10.320Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 96, in handler
[2022-10-08T21:09:10.320Z]     raise e
[2022-10-08T21:09:10.320Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 92, in handler
[2022-10-08T21:09:10.320Z]     return func(*args, **kwargs)
[2022-10-08T21:09:10.320Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 74, in handler
[2022-10-08T21:09:10.320Z]     raise e
[2022-10-08T21:09:10.320Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 48, in handler
[2022-10-08T21:09:10.320Z]     return func(self, *args, **kwargs)
[2022-10-08T21:09:10.320Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 974, in query
[2022-10-08T21:09:10.320Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2022-10-08T21:09:10.320Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Query, QueryNode ID = 10, reason=historical query failed on nodeID 20, reason = query shard(channel)  by-dev-rootcoord-dml_61_436538146946023425v0  does not exist
[2022-10-08T21:09:10.320Z] , err = %!w(<nil>))>
[2022-10-08T21:09:10.320Z]  (api_request.py:35)
[2022-10-08T21:09:10.320Z] [2022-10-08 20:28:20 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Query, QueryNode ID = 10, reason=historical query failed on nodeID 20, reason = query shard(channel)  by-dev-rootcoord-dml_61_436538146946023425v0  does not exist
[2022-10-08T21:09:10.320Z] , err = %!w(<nil>))> (api_request.py:36)
```

### Expected Behavior

PASSED

### Steps To Reproduce

```markdown
See nightly: https://jenkins.milvus.io:18080/blue/organizations/jenkins/qa%2Fmilvus-release-nightly/detail/milvus-release-nightly/149/pipeline/196/
```

### Milvus Log

1. collection name: query_1yFvBgJk
2. failed timeline: [2022-10-08T20:28:21.334Z] [gw5] [ 39%] FAILED testcases/test_query.py::TestQueryParams::test_query_output_binary_vec_field
3. milvus log: [milvus-distributed-pulsar-149-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/qa/job/milvus-release-nightly/149/artifact/milvus-distributed-pulsar-149-pymilvus-e2e-logs.tar.gz)

**Comment by congqixia** [comment]
Hi @NicoYuan1986 , does this problem still persist?

**Comment by NicoYuan1986** [comment]
> Hi @NicoYuan1986 , does this problem still persist?

It doesn't exist these days.
