### ISSUE TITLE
[Bug]: Create index timeout when the concurrency is 4 for standalone Milvus 

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#19718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20221010-2c92ce0c
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2022-10-10T06:50:58.080Z] =========================== short test summary info ============================
[2022-10-10T06:50:58.080Z] FAILED testcases/test_action_first_deployment.py::TestActionFirstDeployment::test_task_all[HNSW-all-is_vector_indexed-is_string_indexed-is_deleted-is_compacted-0]
[2022-10-10T06:50:58.080Z] FAILED testcases/test_action_first_deployment.py::TestActionFirstDeployment::test_task_all[BIN_IVF_FLAT-all-is_vector_indexed-is_string_indexed-is_deleted-not_compacted-0]
[2022-10-10T06:50:58.080Z] ============= 2 failed, 32 passed, 64 skipped in 374.88s (0:06:14) =============
```

```
[2022-10-10T06:50:58.079Z] <name>: deploy_test_index_type_BIN_IVF_FLAT_is_compacted_not_compacted_segment_status_all_is_vector_indexed_is_vector_indexed_is_string_indexed_is_string_indexed_replica_number_0_is_deleted_is_deleted_data_size_3000
[2022-10-10T06:50:58.079Z] <partitions>: [{"name": "_default", "collection_name": "......  (api_request.py:31)
[2022-10-10T06:50:58.079Z] [2022-10-10 06:48:23 - INFO - ci_test]: inserted 3000 data into collection deploy_test_index_type_BIN_IVF_FLAT_is_compacted_not_compacted_segment_status_all_is_vector_indexed_is_vector_indexed_is_string_indexed_is_string_indexed_replica_number_0_is_deleted_is_deleted_data_size_3000 (common_func.py:684)
[2022-10-10T06:50:58.079Z] [2022-10-10 06:48:23 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [      int64   float varchar                                      binary_vector
[2022-10-10T06:50:58.079Z] 0         0     0.0       0       b'\xc4oHI\x7fj\x8e$\xe7\xdb\x9eX\r{\xcb\x92'
[2022-10-10T06:50:58.079Z] 1         1     1.0       1  b'\xe7$\x978\xf1\x9d\x8b\x92C\x8f\xfd\xa9o\xcc...
[2022-10-10T06:50:58.079Z] 2         2     2.0       2  b'\xe8\xca\xf1T\xb9*d\xa63\xd3\xd......, kwargs: {'timeout': 20} (api_request.py:56)
[2022-10-10T06:50:58.079Z] [2022-10-10 06:48:24 - DEBUG - ci_test]: (api_response) : (insert count: 3000, delete count: 0, upsert count: 0, timestamp: 436570555410022401, success count: 3000, err count: 0)  (api_request.py:31)
[2022-10-10T06:50:58.079Z] [2022-10-10 06:48:24 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 20} (api_request.py:56)
[2022-10-10T06:50:58.079Z] [2022-10-10 06:48:26 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)
[2022-10-10T06:50:58.079Z] [2022-10-10 06:48:26 - DEBUG - ci_test]: (api_request)  : [Collection.delete] args: ['int64 in [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]', None, 20], kwargs: {} (api_request.py:56)
[2022-10-10T06:50:58.079Z] [2022-10-10 06:48:26 - DEBUG - ci_test]: (api_response) : (insert count: 0, delete count: 10, upsert count: 0, timestamp: 436570556144025603, success count: 0, err count: 0)  (api_request.py:31)
[2022-10-10T06:50:58.079Z] [2022-10-10 06:48:26 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['binary_vector', {'index_type': 'BIN_IVF_FLAT', 'params': {'nlist': 128}, 'metric_type': 'HAMMING'}], kwargs: {'timeout': 40, 'index_name': '_default_idx'} (api_request.py:56)
[2022-10-10T06:50:58.079Z] [2022-10-10 06:49:07 - WARNING - pymilvus.decorators]: [93mRetry timeout: 40s[0m (decorators.py:80)
[2022-10-10T06:50:58.079Z] [2022-10-10 06:49:07 - ERROR - pymilvus.decorators]: RPC error: [wait_for_creating_index], <MilvusException: (code=1, message=Retry timeout: 40s, message=CreateIndex Timeout)>, <Time:{'RPC start': '2022-10-10 06:48:26.958858', 'RPC error': '2022-10-10 06:49:07.048606'}> (decorators.py:112)
[2022-10-10T06:50:58.079Z] [2022-10-10 06:49:07 - WARNING - pymilvus.decorators]: [93mRetry timeout: 40s[0m (decorators.py:80)
[2022-10-10T06:50:58.079Z] [2022-10-10 06:49:07 - ERROR - pymilvus.decorators]: RPC error: [create_index], <MilvusException: (code=1, message=Retry timeout: 40s, message=Retry timeout: 40s, message=CreateIndex Timeout)>, <Time:{'RPC start': '2022-10-10 06:48:26.792258', 'RPC error': '2022-10-10 06:49:07.048710'}> (decorators.py:112)
[2022-10-10T06:50:58.079Z] [2022-10-10 06:49:07 - ERROR - ci_test]: Traceback (most recent call last):
[2022-10-10T06:50:58.080Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 51, in handler
[2022-10-10T06:50:58.080Z]     return func(self, *args, **kwargs)
[2022-10-10T06:50:58.080Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 645, in wait_for_creating_index
[2022-10-10T06:50:58.080Z]     raise MilvusException(1, "CreateIndex Timeout")
[2022-10-10T06:50:58.080Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=CreateIndex Timeout)>
[2022-10-10T06:50:58.080Z] 
[2022-10-10T06:50:58.080Z] During handling of the above exception, another exception occurred:
[2022-10-10T06:50:58.080Z] 
[2022-10-10T06:50:58.080Z] Traceback (most recent call last):
[2022-10-10T06:50:58.080Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 51, in handler
[2022-10-10T06:50:58.080Z]     return func(self, *args, **kwargs)
[2022-10-10T06:50:58.080Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 574, in create_index
[2022-10-10T06:50:58.080Z]     timeout=timeout)
[2022-10-10T06:50:58.080Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 113, in handler
[2022-10-10T06:50:58.080Z]     raise e
[2022-10-10T06:50:58.080Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 109, in handler
[2022-10-10T06:50:58.080Z]     return func(*args, **kwargs)
[2022-10-10T06:50:58.080Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 139, in handler
[2022-10-10T06:50:58.080Z]     ret = func(self, *args, **kwargs)
[2022-10-10T06:50:58.080Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 81, in handler
[2022-10-10T06:50:58.080Z]     raise MilvusException(e.code, f"{timeout_msg}, message={e.message}")
[2022-10-10T06:50:58.080Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 40s, message=CreateIndex Timeout)>
[2022-10-10T06:50:58.080Z] 
[2022-10-10T06:50:58.080Z] During handling of the above exception, another exception occurred:
[2022-10-10T06:50:58.080Z] 
[2022-10-10T06:50:58.080Z] Traceback (most recent call last):
[2022-10-10T06:50:58.080Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2022-10-10T06:50:58.080Z]     res = func(*args, **_kwargs)
[2022-10-10T06:50:58.080Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2022-10-10T06:50:58.080Z]     return func(*arg, **kwargs)
[2022-10-10T06:50:58.080Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 1089, in create_index
[2022-10-10T06:50:58.080Z]     timeout=timeout, **kwargs)
[2022-10-10T06:50:58.080Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 113, in handler
[2022-10-10T06:50:58.080Z]     raise e
[2022-10-10T06:50:58.080Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 109, in handler
[2022-10-10T06:50:58.080Z]     return func(*args, **kwargs)
[2022-10-10T06:50:58.080Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 139, in handler
[2022-10-10T06:50:58.080Z]     ret = func(self, *args, **kwargs)
[2022-10-10T06:50:58.080Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 81, in handler
[2022-10-10T06:50:58.080Z]     raise MilvusException(e.code, f"{timeout_msg}, message={e.message}")
[2022-10-10T06:50:58.080Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 40s, message=Retry timeout: 40s, message=CreateIndex Timeout)>
[2022-10-10T06:50:58.080Z]  (api_request.py:39)
[2022-10-10T06:50:58.080Z] [2022-10-10 06:49:07 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 40s, message=Retry timeout: 40s, message=CreateIndex Timeout)> (api_request.py:40)
```

### Expected Behavior

all test cases passed

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test/detail/deploy_test/364/pipeline/128/

log:
[artifacts-standalone-reinstall-364-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9761080/artifacts-standalone-reinstall-364-server-logs.tar.gz)
[artifacts-standalone-reinstall-364-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9761081/artifacts-standalone-reinstall-364-pytest-logs.tar.gz)

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test/detail/deploy_test/371/pipeline/68
log:
[artifacts-standalone-upgrade-371-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9761161/artifacts-standalone-upgrade-371-server-logs.tar.gz)
[artifacts-standalone-upgrade-371-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9761162/artifacts-standalone-upgrade-371-pytest-logs.tar.gz)

### Anything else?

It seems that the performance of creating index is lower than v2.1.4, since those testcases can pass in v2.1.4. And another point can verify this conclusion, because after upgrading, there will be creating index timeout in some testcases.

![image](https://user-images.githubusercontent.com/12268675/195239627-b070d79b-04e8-4749-823b-b047a783d564.png)

![image](https://user-images.githubusercontent.com/12268675/195239770-65f98062-7977-4d37-932a-e2a16c8599d0.png)

This issue only happened in the standalone scenario, the reason may be the resource is less than the cluster.

**Comment by xiaocai2333** [comment]
reason:
1. compaction occurred when building indexes.
2. the order building index is sorted by buildID.
3. Concurrency testing

the buildID of the segment from compaction is large other segment, so even if the indexing task comes first, after the compaction occurs, it has to wait for the segments of other collections to complete the indexing. 
very easy to cause timeout.

**Comment by xiaocai2333** [comment]
> reason:
> 
> 1. compaction occurred when building indexes.
> 2. the order building index is sorted by buildID.
> 3. Concurrency testing
> 
> the buildID of the segment from compaction is large other segment, so even if the indexing task comes first, after the compaction occurs, it has to wait for the segments of other collections to complete the indexing. very easy to cause timeout.

sorry, maybe this is not the real reason.

**Comment by xiaocai2333** [comment]
/unassign
/assign @zhuwenxing 
please verify it

**Comment by zhuwenxing** [comment]
For the vector field, this issue is not reproduced again, but it happened when the field is varchar, see https://github.com/milvus-io/milvus/issues/19959.
