### ISSUE TITLE
[Bug]: [Nightly]Load collection failed for timeout

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#19736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:ae373d4
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0.dev40
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Load collection failed for timeout.
```
[2022-10-12T20:11:56.067Z] [2022-10-12 15:57:08 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=-1, message=wait for loading collection timeout)>, <Time:{'RPC start': '2022-10-12 15:56:48.079230', 'RPC error': '2022-10-12 15:57:08.097555'}> (decorators.py:112)
[2022-10-12T20:11:56.067Z] [2022-10-12 15:57:08 - WARNING - pymilvus.decorators]: [93mRetry timeout: 20s[0m (decorators.py:80)
[2022-10-12T20:11:56.067Z] [2022-10-12 15:57:08 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=-1, message=Retry timeout: 20s, message=wait for loading collection timeout)>, <Time:{'RPC start': '2022-10-12 15:56:47.250350', 'RPC error': '2022-10-12 15:57:08.097903'}> (decorators.py:112)
[2022-10-12T20:11:56.067Z] [2022-10-12 15:57:08 - ERROR - ci_test]: Traceback (most recent call last):
[2022-10-12T20:11:56.067Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 51, in handler
[2022-10-12T20:11:56.067Z]     return func(self, *args, **kwargs)
[2022-10-12T20:11:56.067Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 657, in load_collection
[2022-10-12T20:11:56.067Z]     self.wait_for_loading_collection(collection_name, timeout)
[2022-10-12T20:11:56.067Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 113, in handler
[2022-10-12T20:11:56.067Z]     raise e
[2022-10-12T20:11:56.067Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2022-10-12T20:11:56.067Z]     return func(*args, **kwargs)
[2022-10-12T20:11:56.067Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 139, in handler
[2022-10-12T20:11:56.067Z]     ret = func(self, *args, **kwargs)
[2022-10-12T20:11:56.067Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 89, in handler
[2022-10-12T20:11:56.067Z]     raise e
[2022-10-12T20:11:56.067Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 51, in handler
[2022-10-12T20:11:56.067Z]     return func(self, *args, **kwargs)
[2022-10-12T20:11:56.067Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 666, in wait_for_loading_collection
[2022-10-12T20:11:56.067Z]     return self._wait_for_loading_collection(collection_name, timeout)
[2022-10-12T20:11:56.067Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 700, in _wait_for_loading_collection
[2022-10-12T20:11:56.067Z]     raise MilvusException(-1, "wait for loading collection timeout")
[2022-10-12T20:11:56.067Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=-1, message=wait for loading collection timeout)>
[2022-10-12T20:11:56.067Z] 
[2022-10-12T20:11:56.067Z] During handling of the above exception, another exception occurred:
[2022-10-12T20:11:56.067Z] 
[2022-10-12T20:11:56.067Z] Traceback (most recent call last):
[2022-10-12T20:11:56.067Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2022-10-12T20:11:56.067Z]     res = func(*args, **_kwargs)
[2022-10-12T20:11:56.067Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2022-10-12T20:11:56.067Z]     return func(*arg, **kwargs)
[2022-10-12T20:11:56.067Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 473, in load
[2022-10-12T20:11:56.067Z]     conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
[2022-10-12T20:11:56.067Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 113, in handler
[2022-10-12T20:11:56.067Z]     raise e
[2022-10-12T20:11:56.067Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2022-10-12T20:11:56.067Z]     return func(*args, **kwargs)
[2022-10-12T20:11:56.067Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 139, in handler
[2022-10-12T20:11:56.067Z]     ret = func(self, *args, **kwargs)
[2022-10-12T20:11:56.067Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 81, in handler
[2022-10-12T20:11:56.067Z]     raise MilvusException(e.code, f"{timeout_msg}, message={e.message}")
[2022-10-12T20:11:56.067Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=-1, message=Retry timeout: 20s, message=wait for loading collection timeout)>
[2022-10-12T20:11:56.067Z]  (api_request.py:39)
[2022-10-12T20:11:56.067Z] [2022-10-12 15:57:08 - ERROR - ci_test]: (api_response) : <MilvusException: (code=-1, message=Retry timeout: 20s, message=wait for loading collection timeout)> (api_request.py:40)
```

### Expected Behavior

PASSED

### Steps To Reproduce

```markdown
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/155/pipeline/187
```

### Milvus Log

1. log: [artifacts-milvus-distributed-pulsar-nightly-155-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/155/artifact/artifacts-milvus-distributed-pulsar-nightly-155-pymilvus-e2e-logs.tar.gz)
2. collection name: search_collection_ITkh81Er
3. failed timeline: [2022-10-12T15:57:10.344Z] [gw5] [ 45%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_binary_jaccard_flat_index[2-8-False-True-False-BIN_FLAT]

**Comment by weiliu1031** [comment]
just because loadSegmentTask generate a bit late， so loadCollection finish later than proxy timeout. actually, the collection has been load successfully.

**Comment by weiliu1031** [comment]
> just because loadSegmentTask generate a bit late， so loadCollection finish later than proxy timeout. actually, the collection has been load successfully.

more details: 

1. loadSegmentTask generate for a bit late due to watchDmChannel cost 20s before loadSegmentTask can generate

2. watchDmChannel cost 20s just because query node process task in serial and a loadCollection with 256 channels is processing before it.

**Comment by NicoYuan1986** [comment]
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/168/pipeline/155/
failed case: test_search_pagination_after_different_index
collection name: search_collection_oM31DyQc
log: [artifacts-milvus-distributed-kafka-nightly-168-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/168/artifact/artifacts-milvus-distributed-kafka-nightly-168-pymilvus-e2e-logs.tar.gz)

**Comment by NicoYuan1986** [comment]
The issue is same with #20247. So close this one.
