### ISSUE TITLE
[Bug]: [bulk load]Bulk load tasks created after dataoord pod chaos were all pending  because 2 tasks created during chaos keep in started state

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#19730]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20221012-a561614d
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.2.0.dev38
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2022-10-12T03:59:25.059Z] [2022-10-12 03:59:21 - INFO - ci_test]: ******3rd assert after chaos deleted:  (test_chaos_bulk_load.py:201)
[2022-10-12T03:59:25.059Z] [2022-10-12 03:59:21 - INFO - ci_test]: Expect Succ: Op.bulk_load succ rate 0.0, total: 4, average time: 0.0000 (test_chaos_bulk_load.py:40)
```
The following logs are more clear.

before the chaos, the tasks can all success.
during the chaos, some tasks failed, some tasks are staying at the started state and some tasks are the pending state.
after the chaos is deleted, there are always 2 tasks in the started state, and more and more tasks are in the pending state.

It means 2 tasks created during chaos were always in the started state, and can not turn into completed or failed state, and this makes the task created after chaos can only be in the pending queue, and not be started.
```
[2022-10-12 03:45:44,221 - INFO - ci_test]: ################################################################################ (conftest.py:189)
[2022-10-12 03:45:44,221 - INFO - ci_test]: [initialize_milvus] Log cleaned up, start testing... (conftest.py:190)
[2022-10-12 03:45:44,676 - INFO - ci_test]: init health checkers (test_chaos_bulk_load.py:85)
[2022-10-12 03:45:47,700 - INFO - ci_test]: bulk_load checker is in  health checkers, prepare data firstly (test_chaos_bulk_load.py:99)
[2022-10-12 03:45:47,777 - INFO - ci_test]: generate bulk load file (test_chaos_bulk_load.py:122)
[2022-10-12 03:45:47,929 - INFO - ci_test]: upload file to minio (test_chaos_bulk_load.py:125)
[2022-10-12 03:45:47,990 - INFO - ci_test]: prepare data for bulk load done (test_chaos_bulk_load.py:129)
[2022-10-12 03:45:47,992 - INFO - ci_test]: *********************Chaos Test Start********************** (test_chaos_bulk_load.py:144)
[2022-10-12 03:45:47,993 - INFO - ci_test]: {'address': '10.101.209.246:19530', 'user': ''} (test_chaos_bulk_load.py:145)
[2022-10-12 03:45:47,996 - INFO - ci_test]: chaos_config: {'kind': 'Schedule', 'apiVersion': 'chaos-mesh.org/v1alpha1', 'metadata': {'name': 'test-datacoord-pod-kill-1665546347', 'namespace': 'chaos-testing'}, 'spec': {'schedule': '*/5 * * * * *', 'startingDeadlineSeconds': 60, 'concurrencyPolicy': 'Forbid', 'historyLimit': 1, 'type': 'PodChaos', 'podChaos': {'selector': {'namespaces': ['chaos-testing'], 'labelSelectors': {'app.kubernetes.io/instance': 'bulk-load-test-15', 'app.kubernetes.io/name': 'milvus', 'component': 'datacoord'}}, 'mode': 'fixed', 'value': '1', 'action': 'pod-kill', 'gracePeriod': 0}}} (test_chaos_bulk_load.py:156)
[2022-10-12 03:45:48,028 - INFO - ci_test]: before bulk load, there are 0 working tasks (utility_wrapper.py:24)
[2022-10-12 03:45:49,037 - INFO - ci_test]: after bulk load, there are 0 working tasks (utility_wrapper.py:32)
[2022-10-12 03:45:49,037 - INFO - ci_test]: wait bulk load timeout is 60 (utility_wrapper.py:108)
[2022-10-12 03:45:49,039 - INFO - ci_test]: before waiting, there are 0 pending tasks (utility_wrapper.py:110)
[2022-10-12 03:45:55,051 - INFO - ci_test]: after waiting, there are 0 pending tasks (utility_wrapper.py:143)
[2022-10-12 03:45:55,051 - INFO - ci_test]: task state distribution: {'success': {436612960032066906}, 'failed': set(), 'in_progress': set()} (utility_wrapper.py:144)
[2022-10-12 03:45:55,051 - INFO - ci_test]: wait for bulk load tasks completed successfully, cost time: 6.0118725299835205 (utility_wrapper.py:147)
[2022-10-12 03:45:56,085 - INFO - ci_test]: before bulk load, there are 0 working tasks (utility_wrapper.py:24)
[2022-10-12 03:45:57,094 - INFO - ci_test]: after bulk load, there are 0 working tasks (utility_wrapper.py:32)
[2022-10-12 03:45:57,094 - INFO - ci_test]: wait bulk load timeout is 60 (utility_wrapper.py:108)
[2022-10-12 03:45:57,096 - INFO - ci_test]: before waiting, there are 0 pending tasks (utility_wrapper.py:110)
[2022-10-12 03:46:11,137 - INFO - ci_test]: after waiting, there are 0 pending tasks (utility_wrapper.py:143)
[2022-10-12 03:46:11,137 - INFO - ci_test]: task state distribution: {'success': {436612960032066926}, 'failed': set(), 'in_progress': set()} (utility_wrapper.py:144)
[2022-10-12 03:46:11,137 - INFO - ci_test]: wait for bulk load tasks completed successfully, cost time: 14.041176319122314 (utility_wrapper.py:147)
[2022-10-12 03:46:12,165 - INFO - ci_test]: before bulk load, there are 0 working tasks (utility_wrapper.py:24)
[2022-10-12 03:46:13,173 - INFO - ci_test]: after bulk load, there are 0 working tasks (utility_wrapper.py:32)
[2022-10-12 03:46:13,173 - INFO - ci_test]: wait bulk load timeout is 60 (utility_wrapper.py:108)
[2022-10-12 03:46:13,176 - INFO - ci_test]: before waiting, there are 0 pending tasks (utility_wrapper.py:110)
[2022-10-12 03:46:25,199 - INFO - ci_test]: after waiting, there are 0 pending tasks (utility_wrapper.py:143)
[2022-10-12 03:46:25,199 - INFO - ci_test]: task state distribution: {'success': {436612960032066946}, 'failed': set(), 'in_progress': set()} (utility_wrapper.py:144)
[2022-10-12 03:46:25,200 - INFO - ci_test]: wait for bulk load tasks completed successfully, cost time: 12.023027896881104 (utility_wrapper.py:147)
[2022-10-12 03:46:26,239 - INFO - ci_test]: before bulk load, there are 0 working tasks (utility_wrapper.py:24)
[2022-10-12 03:46:27,255 - INFO - ci_test]: after bulk load, there are 0 working tasks (utility_wrapper.py:32)
[2022-10-12 03:46:27,256 - INFO - ci_test]: wait bulk load timeout is 60 (utility_wrapper.py:108)
[2022-10-12 03:46:27,258 - INFO - ci_test]: before waiting, there are 0 pending tasks (utility_wrapper.py:110)
[2022-10-12 03:46:41,287 - INFO - ci_test]: after waiting, there are 0 pending tasks (utility_wrapper.py:143)
[2022-10-12 03:46:41,287 - INFO - ci_test]: task state distribution: {'success': {436612960032066966}, 'failed': set(), 'in_progress': set()} (utility_wrapper.py:144)
[2022-10-12 03:46:41,288 - INFO - ci_test]: wait for bulk load tasks completed successfully, cost time: 14.029809951782227 (utility_wrapper.py:147)
[2022-10-12 03:46:42,320 - INFO - ci_test]: before bulk load, there are 0 working tasks (utility_wrapper.py:24)
[2022-10-12 03:46:43,328 - INFO - ci_test]: after bulk load, there are 0 working tasks (utility_wrapper.py:32)
[2022-10-12 03:46:43,328 - INFO - ci_test]: wait bulk load timeout is 60 (utility_wrapper.py:108)
[2022-10-12 03:46:43,330 - INFO - ci_test]: before waiting, there are 0 pending tasks (utility_wrapper.py:110)
[2022-10-12 03:46:55,354 - INFO - ci_test]: after waiting, there are 0 pending tasks (utility_wrapper.py:143)
[2022-10-12 03:46:55,355 - INFO - ci_test]: task state distribution: {'success': {436612960032066987}, 'failed': set(), 'in_progress': set()} (utility_wrapper.py:144)
[2022-10-12 03:46:55,355 - INFO - ci_test]: wait for bulk load tasks completed successfully, cost time: 12.023986577987671 (utility_wrapper.py:147)
[2022-10-12 03:46:56,399 - INFO - ci_test]: before bulk load, there are 0 working tasks (utility_wrapper.py:24)
[2022-10-12 03:46:57,407 - INFO - ci_test]: after bulk load, there are 0 working tasks (utility_wrapper.py:32)
[2022-10-12 03:46:57,407 - INFO - ci_test]: wait bulk load timeout is 60 (utility_wrapper.py:108)
[2022-10-12 03:46:57,409 - INFO - ci_test]: before waiting, there are 0 pending tasks (utility_wrapper.py:110)
[2022-10-12 03:47:11,434 - INFO - ci_test]: after waiting, there are 0 pending tasks (utility_wrapper.py:143)
[2022-10-12 03:47:11,434 - INFO - ci_test]: task state distribution: {'success': {436612960032067007}, 'failed': set(), 'in_progress': set()} (utility_wrapper.py:144)
[2022-10-12 03:47:11,434 - INFO - ci_test]: wait for bulk load tasks completed successfully, cost time: 14.02506947517395 (utility_wrapper.py:147)
[2022-10-12 03:47:12,464 - INFO - ci_test]: before bulk load, there are 0 working tasks (utility_wrapper.py:24)
[2022-10-12 03:47:13,473 - INFO - ci_test]: after bulk load, there are 0 working tasks (utility_wrapper.py:32)
[2022-10-12 03:47:13,473 - INFO - ci_test]: wait bulk load timeout is 60 (utility_wrapper.py:108)
[2022-10-12 03:47:13,475 - INFO - ci_test]: before waiting, there are 0 pending tasks (utility_wrapper.py:110)
[2022-10-12 03:47:25,499 - INFO - ci_test]: after waiting, there are 0 pending tasks (utility_wrapper.py:143)
[2022-10-12 03:47:25,499 - INFO - ci_test]: task state distribution: {'success': {436612960032067027}, 'failed': set(), 'in_progress': set()} (utility_wrapper.py:144)
[2022-10-12 03:47:25,500 - INFO - ci_test]: wait for bulk load tasks completed successfully, cost time: 12.023810863494873 (utility_wrapper.py:147)
[2022-10-12 03:47:26,536 - INFO - ci_test]: before bulk load, there are 0 working tasks (utility_wrapper.py:24)
[2022-10-12 03:47:27,544 - INFO - ci_test]: after bulk load, there are 0 working tasks (utility_wrapper.py:32)
[2022-10-12 03:47:27,544 - INFO - ci_test]: wait bulk load timeout is 60 (utility_wrapper.py:108)
[2022-10-12 03:47:27,546 - INFO - ci_test]: before waiting, there are 0 pending tasks (utility_wrapper.py:110)
[2022-10-12 03:47:41,593 - INFO - ci_test]: after waiting, there are 0 pending tasks (utility_wrapper.py:143)
[2022-10-12 03:47:41,593 - INFO - ci_test]: task state distribution: {'success': {436612960032067047}, 'failed': set(), 'in_progress': set()} (utility_wrapper.py:144)
[2022-10-12 03:47:41,593 - INFO - ci_test]: wait for bulk load tasks completed successfully, cost time: 14.046059370040894 (utility_wrapper.py:147)
[2022-10-12 03:47:42,625 - INFO - ci_test]: before bulk load, there are 0 working tasks (utility_wrapper.py:24)
[2022-10-12 03:47:43,634 - INFO - ci_test]: after bulk load, there are 0 working tasks (utility_wrapper.py:32)
[2022-10-12 03:47:43,634 - INFO - ci_test]: wait bulk load timeout is 60 (utility_wrapper.py:108)
[2022-10-12 03:47:43,636 - INFO - ci_test]: before waiting, there are 0 pending tasks (utility_wrapper.py:110)
[2022-10-12 03:47:48,095 - INFO - ci_test]: ******1st assert before chaos:  (test_chaos_bulk_load.py:160)
[2022-10-12 03:47:48,096 - INFO - ci_test]: Expect Succ: Op.bulk_load succ rate 1.0, total: 8, average time: 13.2919 (test_chaos_bulk_load.py:40)
[2022-10-12 03:47:48,236 - INFO - ci_test]: chaos injected (test_chaos_bulk_load.py:168)
[2022-10-12 03:47:55,672 - INFO - ci_test]: after waiting, there are 0 pending tasks (utility_wrapper.py:143)
[2022-10-12 03:47:55,672 - INFO - ci_test]: task state distribution: {'success': {436612960032067068}, 'failed': set(), 'in_progress': set()} (utility_wrapper.py:144)
[2022-10-12 03:47:55,673 - INFO - ci_test]: wait for bulk load tasks completed successfully, cost time: 12.036173343658447 (utility_wrapper.py:147)
[2022-10-12 03:47:59,886 - INFO - ci_test]: before bulk load, there are 0 working tasks (utility_wrapper.py:24)
[2022-10-12 03:48:00,897 - INFO - ci_test]: after bulk load, there are 1 working tasks (utility_wrapper.py:32)
[2022-10-12 03:48:00,897 - INFO - ci_test]: wait bulk load timeout is 60 (utility_wrapper.py:108)
[2022-10-12 03:48:00,899 - INFO - ci_test]: before waiting, there are 0 pending tasks (utility_wrapper.py:110)
[2022-10-12 03:49:01,025 - INFO - ci_test]: after waiting, there are 0 pending tasks (utility_wrapper.py:143)
[2022-10-12 03:49:01,025 - INFO - ci_test]: task state distribution: {'success': set(), 'failed': set(), 'in_progress': {436612960032067088}} (utility_wrapper.py:144)
[2022-10-12 03:49:01,025 - INFO - ci_test]: wait for bulk load tasks completed failed, cost time: 60.12511086463928 (utility_wrapper.py:150)
[2022-10-12 03:49:05,167 - ERROR - ci_test]: Traceback (most recent call last):
  File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 140, in __init__
    consistency_level=consistency_level)
  File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 112, in handler
    raise e
  File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 108, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 139, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 88, in handler
    raise e
  File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 208, in create_collection
    raise MilvusException(status.error_code, status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=err: find no available datacoord, check datacoord state
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:301 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall
/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:483 github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).WatchChannels
/go/src/github.com/milvus-io/milvus/internal/rootcoord/broker.go:105 github.com/milvus-io/milvus/internal/rootcoord.(*ServerBroker).WatchChannels
/go/src/github.com/milvus-io/milvus/internal/rootcoord/step.go:100 github.com/milvus-io/milvus/internal/rootcoord.(*watchChannelsStep).Execute
/go/src/github.com/milvus-io/milvus/internal/rootcoord/undo.go:37 github.com/milvus-io/milvus/internal/rootcoord.(*baseUndoTask).Execute
/go/src/github.com/milvus-io/milvus/internal/rootcoord/create_collection_task.go:307 github.com/milvus-io/milvus/internal/rootcoord.(*createCollectionTask).Execute
/go/src/github.com/milvus-io/milvus/internal/rootcoord/scheduler.go:70 github.com/milvus-io/milvus/internal/rootcoord.(*scheduler).execute
/go/src/github.com/milvus-io/milvus/internal/rootcoord/scheduler.go:85 github.com/milvus-io/milvus/internal/rootcoord.(*scheduler).taskLoop
/usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit
)>
 (api_request.py:39)
[2022-10-12 03:49:05,168 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=err: find no available datacoord, check datacoord state
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:301...... (api_request.py:40)
[2022-10-12 03:49:05,168 - ERROR - ci_test]:  (checker.py:78)
[2022-10-12 03:49:06,197 - ERROR - ci_test]: Traceback (most recent call last):
  File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 140, in __init__
    consistency_level=consistency_level)
  File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 112, in handler
    raise e
  File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 108, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 139, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 88, in handler
    raise e
  File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 208, in create_collection
    raise MilvusException(status.error_code, status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=err: find no available datacoord, check datacoord state
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:301 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall
/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:483 github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).WatchChannels
/go/src/github.com/milvus-io/milvus/internal/rootcoord/broker.go:105 github.com/milvus-io/milvus/internal/rootcoord.(*ServerBroker).WatchChannels
/go/src/github.com/milvus-io/milvus/internal/rootcoord/step.go:100 github.com/milvus-io/milvus/internal/rootcoord.(*watchChannelsStep).Execute
/go/src/github.com/milvus-io/milvus/internal/rootcoord/undo.go:37 github.com/milvus-io/milvus/internal/rootcoord.(*baseUndoTask).Execute
/go/src/github.com/milvus-io/milvus/internal/rootcoord/create_collection_task.go:307 github.com/milvus-io/milvus/internal/rootcoord.(*createCollectionTask).Execute
/go/src/github.com/milvus-io/milvus/internal/rootcoord/scheduler.go:70 github.com/milvus-io/milvus/internal/rootcoord.(*scheduler).execute
/go/src/github.com/milvus-io/milvus/internal/rootcoord/scheduler.go:85 github.com/milvus-io/milvus/internal/rootcoord.(*scheduler).taskLoop
/usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit
)>
 (api_request.py:39)
[2022-10-12 03:49:06,197 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=err: find no available datacoord, check datacoord state
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:301...... (api_request.py:40)
[2022-10-12 03:49:06,197 - ERROR - ci_test]:  (checker.py:78)
[2022-10-12 03:49:07,241 - INFO - ci_test]: before bulk load, there are 1 working tasks (utility_wrapper.py:24)
[2022-10-12 03:49:08,250 - INFO - ci_test]: after bulk load, there are 2 working tasks (utility_wrapper.py:32)
[2022-10-12 03:49:08,250 - INFO - ci_test]: wait bulk load timeout is 60 (utility_wrapper.py:108)
[2022-10-12 03:49:08,252 - INFO - ci_test]: before waiting, there are 0 pending tasks (utility_wrapper.py:110)
[2022-10-12 03:50:08,368 - INFO - ci_test]: after waiting, there are 0 pending tasks (utility_wrapper.py:143)
[2022-10-12 03:50:08,368 - INFO - ci_test]: task state distribution: {'success': set(), 'failed': set(), 'in_progress': {436612960032067105}} (utility_wrapper.py:144)
[2022-10-12 03:50:08,369 - INFO - ci_test]: wait for bulk load tasks completed failed, cost time: 60.11599564552307 (utility_wrapper.py:150)
[2022-10-12 03:50:12,505 - INFO - ci_test]: before bulk load, there are 2 working tasks (utility_wrapper.py:24)
[2022-10-12 03:50:13,513 - INFO - ci_test]: after bulk load, there are 2 working tasks (utility_wrapper.py:32)
[2022-10-12 03:50:13,514 - INFO - ci_test]: wait bulk load timeout is 60 (utility_wrapper.py:108)
[2022-10-12 03:50:13,516 - INFO - ci_test]: before waiting, there are 1 pending tasks (utility_wrapper.py:110)
[2022-10-12 03:51:14,067 - INFO - ci_test]: after waiting, there are 1 pending tasks (utility_wrapper.py:143)
[2022-10-12 03:51:14,067 - INFO - ci_test]: task state distribution: {'success': set(), 'failed': set(), 'in_progress': {436612960032067109}} (utility_wrapper.py:144)
[2022-10-12 03:51:14,068 - INFO - ci_test]: wait for bulk load tasks completed failed, cost time: 60.55144715309143 (utility_wrapper.py:150)
[2022-10-12 03:51:18,169 - INFO - ci_test]: before bulk load, there are 2 working tasks (utility_wrapper.py:24)
[2022-10-12 03:51:19,181 - INFO - ci_test]: after bulk load, there are 2 working tasks (utility_wrapper.py:32)
[2022-10-12 03:51:19,181 - INFO - ci_test]: wait bulk load timeout is 60 (utility_wrapper.py:108)
[2022-10-12 03:51:19,184 - INFO - ci_test]: before waiting, there are 2 pending tasks (utility_wrapper.py:110)
[2022-10-12 03:52:20,039 - INFO - ci_test]: after waiting, there are 2 pending tasks (utility_wrapper.py:143)
[2022-10-12 03:52:20,040 - INFO - ci_test]: task state distribution: {'success': set(), 'failed': set(), 'in_progress': {436612960032067113}} (utility_wrapper.py:144)
[2022-10-12 03:52:20,040 - INFO - ci_test]: wait for bulk load tasks completed failed, cost time: 60.85559678077698 (utility_wrapper.py:150)
[2022-10-12 03:52:24,152 - INFO - ci_test]: before bulk load, there are 2 working tasks (utility_wrapper.py:24)
[2022-10-12 03:52:25,160 - INFO - ci_test]: after bulk load, there are 2 working tasks (utility_wrapper.py:32)
[2022-10-12 03:52:25,160 - INFO - ci_test]: wait bulk load timeout is 60 (utility_wrapper.py:108)
[2022-10-12 03:52:25,162 - INFO - ci_test]: before waiting, there are 3 pending tasks (utility_wrapper.py:110)
[2022-10-12 03:53:27,954 - INFO - ci_test]: after waiting, there are 3 pending tasks (utility_wrapper.py:143)
[2022-10-12 03:53:27,954 - INFO - ci_test]: task state distribution: {'success': set(), 'failed': set(), 'in_progress': {436612960032067117}} (utility_wrapper.py:144)
[2022-10-12 03:53:27,954 - INFO - ci_test]: wait for bulk load tasks completed failed, cost time: 62.79169964790344 (utility_wrapper.py:150)
[2022-10-12 03:53:28,436 - INFO - ci_test]: Alive threads: [<_MainThread(MainThread, started 140030506510144)>, <Thread(Op.bulk_load, started daemon 140027986306816)>] (test_chaos_bulk_load.py:174)
[2022-10-12 03:53:28,437 - INFO - ci_test]: ******2nd assert after chaos injected:  (test_chaos_bulk_load.py:176)
[2022-10-12 03:53:28,437 - INFO - ci_test]: Expect Fail: Op.bulk_load succ rate 0.0, total: 4, average time: 0.0000 (test_chaos_bulk_load.py:35)
[2022-10-12 03:53:28,475 - INFO - ci_test]: chaos deleted (test_chaos_bulk_load.py:183)
[2022-10-12 03:53:28,996 - INFO - ci_test]: before bulk load, there are 2 working tasks (utility_wrapper.py:24)
[2022-10-12 03:53:30,003 - INFO - ci_test]: after bulk load, there are 2 working tasks (utility_wrapper.py:32)
[2022-10-12 03:53:30,004 - INFO - ci_test]: wait bulk load timeout is 60 (utility_wrapper.py:108)
[2022-10-12 03:53:30,006 - INFO - ci_test]: before waiting, there are 4 pending tasks (utility_wrapper.py:110)
[2022-10-12 03:53:30,477 - INFO - ci_test]: wait for pods in namespace chaos-testing with label app.kubernetes.io/instance=bulk-load-test-15 (test_chaos_bulk_load.py:186)
[2022-10-12 03:54:30,114 - INFO - ci_test]: after waiting, there are 4 pending tasks (utility_wrapper.py:143)
[2022-10-12 03:54:30,114 - INFO - ci_test]: task state distribution: {'success': set(), 'failed': set(), 'in_progress': {436612960032067121}} (utility_wrapper.py:144)
[2022-10-12 03:54:30,114 - INFO - ci_test]: wait for bulk load tasks completed failed, cost time: 60.107569456100464 (utility_wrapper.py:150)
[2022-10-12 03:54:31,156 - INFO - ci_test]: before bulk load, there are 2 working tasks (utility_wrapper.py:24)
[2022-10-12 03:54:32,163 - INFO - ci_test]: after bulk load, there are 2 working tasks (utility_wrapper.py:32)
[2022-10-12 03:54:32,164 - INFO - ci_test]: wait bulk load timeout is 60 (utility_wrapper.py:108)
[2022-10-12 03:54:32,165 - INFO - ci_test]: before waiting, there are 5 pending tasks (utility_wrapper.py:110)
[2022-10-12 03:55:00,828 - INFO - ci_test]: all pods in namespace chaos-testing with label app.kubernetes.io/instance=bulk-load-test-15 are ready (util_k8s.py:79)
[2022-10-12 03:55:00,831 - INFO - ci_test]: wait for pods in namespace chaos-testing with label release=bulk-load-test-15 (test_chaos_bulk_load.py:188)
[2022-10-12 03:55:00,923 - INFO - ci_test]: all pods in namespace chaos-testing with label release=bulk-load-test-15 are ready (util_k8s.py:79)
[2022-10-12 03:55:00,925 - INFO - ci_test]: all pods are ready (test_chaos_bulk_load.py:190)
[2022-10-12 03:55:32,267 - INFO - ci_test]: after waiting, there are 5 pending tasks (utility_wrapper.py:143)
[2022-10-12 03:55:32,267 - INFO - ci_test]: task state distribution: {'success': set(), 'failed': set(), 'in_progress': {436612960032067126}} (utility_wrapper.py:144)
[2022-10-12 03:55:32,267 - INFO - ci_test]: wait for bulk load tasks completed failed, cost time: 60.101367235183716 (utility_wrapper.py:150)
[2022-10-12 03:55:33,274 - INFO - ci_test]: before bulk load, there are 2 working tasks (utility_wrapper.py:24)
[2022-10-12 03:55:34,282 - INFO - ci_test]: after bulk load, there are 2 working tasks (utility_wrapper.py:32)
[2022-10-12 03:55:34,282 - INFO - ci_test]: wait bulk load timeout is 60 (utility_wrapper.py:108)
[2022-10-12 03:55:34,285 - INFO - ci_test]: before waiting, there are 6 pending tasks (utility_wrapper.py:110)
[2022-10-12 03:56:34,402 - INFO - ci_test]: after waiting, there are 6 pending tasks (utility_wrapper.py:143)
[2022-10-12 03:56:34,402 - INFO - ci_test]: task state distribution: {'success': set(), 'failed': set(), 'in_progress': {436612960032067128}} (utility_wrapper.py:144)
[2022-10-12 03:56:34,403 - INFO - ci_test]: wait for bulk load tasks completed failed, cost time: 60.11708641052246 (utility_wrapper.py:150)
[2022-10-12 03:56:35,410 - INFO - ci_test]: before bulk load, there are 2 working tasks (utility_wrapper.py:24)
[2022-10-12 03:56:36,418 - INFO - ci_test]: after bulk load, there are 2 working tasks (utility_wrapper.py:32)
[2022-10-12 03:56:36,419 - INFO - ci_test]: wait bulk load timeout is 60 (utility_wrapper.py:108)
[2022-10-12 03:56:36,421 - INFO - ci_test]: before waiting, there are 7 pending tasks (utility_wrapper.py:110)
[2022-10-12 03:57:36,533 - INFO - ci_test]: after waiting, there are 7 pending tasks (utility_wrapper.py:143)
[2022-10-12 03:57:36,534 - INFO - ci_test]: task state distribution: {'success': set(), 'failed': set(), 'in_progress': {436612960032067130}} (utility_wrapper.py:144)
[2022-10-12 03:57:36,534 - INFO - ci_test]: wait for bulk load tasks completed failed, cost time: 60.11253023147583 (utility_wrapper.py:150)
[2022-10-12 03:57:37,541 - INFO - ci_test]: before bulk load, there are 2 working tasks (utility_wrapper.py:24)
[2022-10-12 03:57:38,549 - INFO - ci_test]: after bulk load, there are 2 working tasks (utility_wrapper.py:32)
[2022-10-12 03:57:38,549 - INFO - ci_test]: wait bulk load timeout is 60 (utility_wrapper.py:108)
[2022-10-12 03:57:38,552 - INFO - ci_test]: before waiting, there are 8 pending tasks (utility_wrapper.py:110)
[2022-10-12 03:58:38,667 - INFO - ci_test]: after waiting, there are 8 pending tasks (utility_wrapper.py:143)
[2022-10-12 03:58:38,667 - INFO - ci_test]: task state distribution: {'success': set(), 'failed': set(), 'in_progress': {436612960032067132}} (utility_wrapper.py:144)
[2022-10-12 03:58:38,668 - INFO - ci_test]: wait for bulk load tasks completed failed, cost time: 60.11581039428711 (utility_wrapper.py:150)
[2022-10-12 03:58:39,676 - INFO - ci_test]: before bulk load, there are 2 working tasks (utility_wrapper.py:24)
[2022-10-12 03:58:40,683 - INFO - ci_test]: after bulk load, there are 2 working tasks (utility_wrapper.py:32)
[2022-10-12 03:58:40,683 - INFO - ci_test]: wait bulk load timeout is 60 (utility_wrapper.py:108)
[2022-10-12 03:58:40,686 - INFO - ci_test]: before waiting, there are 9 pending tasks (utility_wrapper.py:110)
[2022-10-12 03:59:21,046 - INFO - ci_test]: ******3rd assert after chaos deleted:  (test_chaos_bulk_load.py:201)
[2022-10-12 03:59:21,047 - INFO - ci_test]: Expect Succ: Op.bulk_load succ rate 0.0, total: 4, average time: 0.0000 (test_chaos_bulk_load.py:40)
[2022-10-12 03:59:23,089 - INFO - ci_test]: Alive threads: [<_MainThread(MainThread, started 140030506510144)>, <Thread(Op.bulk_load, started daemon 140027986306816)>] (test_chaos_bulk_load.py:139)

```

### Expected Behavior

After chaos, bulk load task can be started and then be completed.

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/bulk_load_chaos_test/detail/bulk_load_chaos_test/15/pipeline

log:
[artifacts-bulk-load-test-15-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/9764302/artifacts-bulk-load-test-15-server-logs.1.tar.gz)

[artifacts-bulk-load-test-15-pytest-logs (2).tar.gz](https://github.com/milvus-io/milvus/files/9764303/artifacts-bulk-load-test-15-pytest-logs.2.tar.gz)

**Comment by soothing-rain** [comment]
/unassign
/assign @zhuwenxing 

Please verify

**Comment by zhuwenxing** [comment]
Verified and passed
