### ISSUE TITLE
[Bug]: Indexcoord crash after datacoord pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#19741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20221012-ae373d45
- Deployment mode(standalone or cluster): cluster 
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.2.0.dev40
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2022/10/12 20:54:36.228 +00:00] [INFO] [indexcoord/index_coord.go:1095] ["create index for flushed segment"] [collID=436628911476903330] [segID=436628911476906301] [numRows=78]
[2022/10/12 20:54:36.228 +00:00] [DEBUG] [indexcoord/index_coord.go:1105] ["IndexCoord has same index"] [buildID=436628911476906560] [segmentID=436628911476906301]
[2022/10/12 20:54:36.228 +00:00] [INFO] [indexcoord/handoff.go:96] ["segment need to write handoff"] [segID=436628911476906301]
[2022/10/12 20:54:36.228 +00:00] [DEBUG] [indexcoord/flush_segment_watcher.go:291] ["flushedSegmentWatcher construct task success"] [segID=436628911476906301] ["tasks num"=1]
[2022/10/12 20:54:36.228 +00:00] [DEBUG] [indexcoord/flush_segment_watcher.go:186] ["flushedSegmentWatcher updateInternalTaskState"] [segID=436628911476906301] [state=InProgress]
[2022/10/12 20:54:36.228 +00:00] [DEBUG] [indexcoord/flush_segment_watcher.go:262] ["segment no need to build index"] [segmentID=436628911476906382] ["num of rows"=12] ["collection indexes num"=0]
[2022/10/12 20:54:36.228 +00:00] [DEBUG] [indexcoord/flush_segment_watcher.go:186] ["flushedSegmentWatcher updateInternalTaskState"] [segID=436628911476906382] [state=InProgress]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x2730a10]

goroutine 302 [running]:
github.com/milvus-io/milvus/internal/indexcoord.(*flushedSegmentWatcher).constructTask(0xc0002385a0, 0xc001dd4160)
	/go/src/github.com/milvus-io/milvus/internal/indexcoord/flush_segment_watcher.go:275 +0x370
github.com/milvus-io/milvus/internal/indexcoord.(*flushedSegmentWatcher).internalProcess(0xc0002385a0, 0x60f37ae7f3f198f)
	/go/src/github.com/milvus-io/milvus/internal/indexcoord/flush_segment_watcher.go:234 +0x2b7
github.com/milvus-io/milvus/internal/indexcoord.(*flushedSegmentWatcher).internalRun(0xc0002385a0)
	/go/src/github.com/milvus-io/milvus/internal/indexcoord/flush_segment_watcher.go:165 +0x23e
github.com/milvus-io/milvus/internal/indexcoord.(*flushedSegmentWatcher).internalScheduler(0xc0002385a0)
	/go/src/github.com/milvus-io/milvus/internal/indexcoord/flush_segment_watcher.go:146 +0x172
created by github.com/milvus-io/milvus/internal/indexcoord.(*flushedSegmentWatcher).Start
	/go/src/github.com/milvus-io/milvus/internal/indexcoord/flush_segment_watcher.go:111 +0x6a
```

```
[2022-10-12T20:55:45.218Z] + kubectl get pods -o wide

[2022-10-12T20:55:45.219Z] + grep datacoord-pod-kill-2107

[2022-10-12T20:55:45.473Z] datacoord-pod-kill-2107-etcd-0                                    1/1     Running            0               19m     10.102.10.181   devops-node20   <none>           <none>

[2022-10-12T20:55:45.473Z] datacoord-pod-kill-2107-etcd-1                                    1/1     Running            0               19m     10.102.6.9      devops-node10   <none>           <none>

[2022-10-12T20:55:45.473Z] datacoord-pod-kill-2107-etcd-2                                    1/1     Running            0               19m     10.102.7.36     devops-node11   <none>           <none>

[2022-10-12T20:55:45.473Z] datacoord-pod-kill-2107-milvus-datacoord-6cfff969cc-2756f         1/1     Running            0               11m     10.102.7.92     devops-node11   <none>           <none>

[2022-10-12T20:55:45.473Z] datacoord-pod-kill-2107-milvus-datanode-db75bc799-8bvmc           1/1     Running            0               19m     10.102.10.158   devops-node20   <none>           <none>

[2022-10-12T20:55:45.473Z] datacoord-pod-kill-2107-milvus-datanode-db75bc799-mdfs8           1/1     Running            0               19m     10.102.5.47     devops-node21   <none>           <none>

[2022-10-12T20:55:45.473Z] datacoord-pod-kill-2107-milvus-indexcoord-78d57f8565-hfmpp        0/1     CrashLoopBackOff   7 (69s ago)     19m     10.102.10.162   devops-node20   <none>           <none>

[2022-10-12T20:55:45.473Z] datacoord-pod-kill-2107-milvus-indexnode-868fbfb8c8-9gpzv         1/1     Running            0               19m     10.102.5.42     devops-node21   <none>           <none>

[2022-10-12T20:55:45.473Z] datacoord-pod-kill-2107-milvus-proxy-6c77b58889-rxzbm             1/1     Running            0               19m     10.102.5.43     devops-node21   <none>           <none>

[2022-10-12T20:55:45.473Z] datacoord-pod-kill-2107-milvus-querycoord-6bb4b6bbcd-lb62r        1/1     Running            0               19m     10.102.10.159   devops-node20   <none>           <none>

[2022-10-12T20:55:45.473Z] datacoord-pod-kill-2107-milvus-querynode-686c6dcd6d-4dcl7         1/1     Running            0               19m     10.102.10.160   devops-node20   <none>           <none>

[2022-10-12T20:55:45.473Z] datacoord-pod-kill-2107-milvus-querynode-686c6dcd6d-gz6rp         1/1     Running            0               19m     10.102.7.30     devops-node11   <none>           <none>

[2022-10-12T20:55:45.473Z] datacoord-pod-kill-2107-milvus-querynode-686c6dcd6d-qd2xp         1/1     Running            0               19m     10.102.6.252    devops-node10   <none>           <none>

[2022-10-12T20:55:45.473Z] datacoord-pod-kill-2107-milvus-rootcoord-68999cb8bd-2zdtv         1/1     Running            0               19m     10.102.5.40     devops-node21   <none>           <none>

[2022-10-12T20:55:45.473Z] datacoord-pod-kill-2107-minio-0                                   1/1     Running            0               19m     10.102.6.8      devops-node10   <none>           <none>

[2022-10-12T20:55:45.473Z] datacoord-pod-kill-2107-minio-1                                   1/1     Running            0               19m     10.102.10.189   devops-node20   <none>           <none>

[2022-10-12T20:55:45.473Z] datacoord-pod-kill-2107-minio-2                                   1/1     Running            0               19m     10.102.7.35     devops-node11   <none>           <none>

[2022-10-12T20:55:45.473Z] datacoord-pod-kill-2107-minio-3                                   1/1     Running            0               19m     10.102.8.17     devops-node12   <none>           <none>

[2022-10-12T20:55:45.473Z] datacoord-pod-kill-2107-pulsar-bookie-0                           1/1     Running            0               19m     10.102.10.183   devops-node20   <none>           <none>

[2022-10-12T20:55:45.473Z] datacoord-pod-kill-2107-pulsar-bookie-1                           1/1     Running            0               19m     10.102.6.11     devops-node10   <none>           <none>

[2022-10-12T20:55:45.473Z] datacoord-pod-kill-2107-pulsar-bookie-init-cp78f                  0/1     Completed          0               19m     10.102.5.45     devops-node21   <none>           <none>

[2022-10-12T20:55:45.473Z] datacoord-pod-kill-2107-pulsar-broker-0                           1/1     Running            0               19m     10.102.6.251    devops-node10   <none>           <none>

[2022-10-12T20:55:45.473Z] datacoord-pod-kill-2107-pulsar-proxy-0                            1/1     Running            0               19m     10.102.10.157   devops-node20   <none>           <none>

[2022-10-12T20:55:45.473Z] datacoord-pod-kill-2107-pulsar-pulsar-init-2c2zg                  0/1     Completed          0               19m     10.102.5.44     devops-node21   <none>           <none>

[2022-10-12T20:55:45.473Z] datacoord-pod-kill-2107-pulsar-recovery-0                         1/1     Running            0               19m     10.102.5.46     devops-node21   <none>           <none>

[2022-10-12T20:55:45.473Z] datacoord-pod-kill-2107-pulsar-zookeeper-0                        1/1     Running            0               19m     10.102.10.165   devops-node20   <none>           <none>
```

### Expected Behavior

all pods can be ready after chaos, and all test cases can pass

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/2107/pipeline/

log:
[artifacts-datacoord-pod-kill-2107-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/9769992/artifacts-datacoord-pod-kill-2107-server-logs.1.tar.gz)

[artifacts-datacoord-pod-kill-2107-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9769993/artifacts-datacoord-pod-kill-2107-pytest-logs.tar.gz)

**Comment by xiaocai2333** [comment]
same reason as #19526 
the start position of segment info is nil.
@congqixia PTAL
/assign @congqixia

**Comment by soothing-rain** [comment]
the start position of segment info is nil because DataNode crashed between
https://github.com/milvus-io/milvus/blob/master/internal/datanode/flush_manager.go#L773

and

https://github.com/milvus-io/milvus/blob/master/internal/datanode/flush_manager.go#L805

Normal case:
1. The first `listNewSegmentsStartPositions` fetches start positions of `newSegments` and then turn them into `normalSegment`.
2. The first `SaveBinlogPaths` flushes the segment with the correct start positions of `newSegments`.
3. The second `listNewSegmentsStartPositions` fetches start positions of `newSegments` and gets startPosition==null because the segment has already turned `normalSegment`. 
4. The second `SaveBinlogPaths` flushes the segment with startPosition=null. (there's no problem because start position is set in the first `SaveBinlogPaths` call)

Bad case:
1. The first `listNewSegmentsStartPositions` fetches start positions of `newSegments` and then turn them into `normalSegment`.
2. DataNode crashes.
3. The second `listNewSegmentsStartPositions` fetches start positions of `newSegments` and gets startPosition==null because the segment has already turned `normalSegment`. 
4. The second `SaveBinlogPaths` flushes the segment with startPosition=null. (this is problematic because the start position of this segment will then never be set).

I'd suggest that `SaveBinlogPaths` always called with a non-empty start position of the current segment.

**Comment by congqixia** [comment]
> the start position of segment info is nil because DataNode crashed between https://github.com/milvus-io/milvus/blob/master/internal/datanode/flush_manager.go#L773
> 
> and
> 
> https://github.com/milvus-io/milvus/blob/master/internal/datanode/flush_manager.go#L805
> 
> Normal case:
> 
>     1. The first `listNewSegmentsStartPositions` fetches start positions of `newSegments` and then turn them into `normalSegment`.
> 
>     2. The first `SaveBinlogPaths` flushes the segment with the correct start positions of `newSegments`.
> 
>     3. The second `listNewSegmentsStartPositions` fetches start positions of `newSegments` and gets startPosition==null because the segment has already turned `normalSegment`.
> 
>     4. The second `SaveBinlogPaths` flushes the segment with startPosition=null. (there's no problem because start position is set in the first `SaveBinlogPaths` call)
> 
> 
> Bad case:
> 
>     1. The first `listNewSegmentsStartPositions` fetches start positions of `newSegments` and then turn them into `normalSegment`.
> 
>     2. DataNode crashes.
> 
>     3. The second `listNewSegmentsStartPositions` fetches start positions of `newSegments` and gets startPosition==null because the segment has already turned `normalSegment`.
> 
>     4. The second `SaveBinlogPaths` flushes the segment with startPosition=null. (this is problematic because the start position of this segment will then never be set).
> 
> 
> I'd suggest that `SaveBinlogPaths` always called with a non-empty start position of the current segment.

If datanode crashed, the recovered position shall make sure the segment is a new segment without start position or a normal segment with the start position. Do we have and case to violate this constraint? @XuanYang-cn @soothing-rain

**Comment by congqixia** [comment]
/assign @zhuwenxing 
/unassign @sunby @congqixia 
Hi @zhuwenxing , could you please verify after Fix pr merged?

**Comment by zhuwenxing** [comment]
Verified and passed
