### ISSUE TITLE
[Bug]: [Nightly] Create collection failed reporting 'failed to watch channels, code: UnexpectedError, reason: DataCoord 0 is not ready'

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#19780]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:5e12a64
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0.dev44
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Create collection failed reporting 'failed to watch channels, code: UnexpectedError, reason: DataCoord 0 is not ready'. 
Detailed error message:
```
[2022-10-13T18:29:58.245Z] [2022-10-13 15:11:35 - ERROR - pymilvus.decorators]: RPC error: [create_collection], <MilvusException: (code=1, message=failed to watch channels, code: UnexpectedError, reason: DataCoord 0 is not ready)>, <Time:{'RPC start': '2022-10-13 15:11:34.658073', 'RPC error': '2022-10-13 15:11:35.301039'}> (decorators.py:112)
[2022-10-13T18:29:58.245Z] [2022-10-13 15:11:35 - ERROR - ci_test]: Traceback (most recent call last):
[2022-10-13T18:29:58.245Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2022-10-13T18:29:58.245Z]     res = func(*args, **_kwargs)
[2022-10-13T18:29:58.245Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2022-10-13T18:29:58.245Z]     return func(*arg, **kwargs)
[2022-10-13T18:29:58.245Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 139, in __init__
[2022-10-13T18:29:58.245Z]     conn.create_collection(self._name, fields=schema, shards_num=self._shards_num, **kwargs)
[2022-10-13T18:29:58.245Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 113, in handler
[2022-10-13T18:29:58.245Z]     raise e
[2022-10-13T18:29:58.245Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2022-10-13T18:29:58.245Z]     return func(*args, **kwargs)
[2022-10-13T18:29:58.245Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 139, in handler
[2022-10-13T18:29:58.245Z]     ret = func(self, *args, **kwargs)
[2022-10-13T18:29:58.245Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 89, in handler
[2022-10-13T18:29:58.245Z]     raise e
[2022-10-13T18:29:58.245Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 51, in handler
[2022-10-13T18:29:58.245Z]     return func(self, *args, **kwargs)
[2022-10-13T18:29:58.245Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 211, in create_collection
[2022-10-13T18:29:58.245Z]     raise MilvusException(status.error_code, status.reason)
[2022-10-13T18:29:58.245Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=failed to watch channels, code: UnexpectedError, reason: DataCoord 0 is not ready)>
[2022-10-13T18:29:58.245Z]  (api_request.py:39)
[2022-10-13T18:29:58.245Z] [2022-10-13 15:11:35 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=failed to watch channels, code: UnexpectedError, reason: DataCoord 0 is not ready)> (api_request.py:40)
```

### Expected Behavior

PASSED

### Steps To Reproduce

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/157/pipeline/187/

### Milvus Log

1. log: [artifacts-milvus-distributed-pulsar-nightly-157-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/157/artifact/artifacts-milvus-distributed-pulsar-nightly-157-pymilvus-e2e-logs.tar.gz)
2. collection name: index_otsAinH6
3. FAILED time: [2022-10-13T15:11:36.793Z] [gw3] [ 19%] FAILED testcases/test_index.py::TestIndexParams::test_index_field_name_not_existed

**Comment by NicoYuan1986** [comment]
Update: 
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/163/pipeline/155/

milvus: 1587878
pymilvus:  2.2.0.dev44

1. milvus log: [artifacts-milvus-distributed-kafka-nightly-163-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/163/artifact/artifacts-milvus-distributed-kafka-nightly-163-pymilvus-e2e-logs.tar.gz)
2. collection name: insert_7t3IydvZ
3. FAILED timeline: [2022-10-16T18:11:49.943Z] [gw4] [ 19%] FAILED testcases/test_insert.py::TestInsertParams::test_insert_single

**Comment by soothing-rain** [comment]
DataCoord panicked during compaction.

/assign @wayblink 
/unassign

**Comment by NicoYuan1986** [comment]
Fixed!
