### ISSUE TITLE
[Bug]: [Nightly]Load balance failed reporting 'failed to balance segments, err=context deadline exceeded'

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#19813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 89c9cb3
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0.dev44
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Load balance failed reporting 'failed to balance segments, err=context deadline exceeded'.
```
[2022-10-15T21:35:47.097Z] [2022-10-15 21:13:52 - ERROR - pymilvus.decorators]: RPC error: [load_balance], <MilvusException: (code=1, message=failed to balance segments, err=context deadline exceeded)>, <Time:{'RPC start': '2022-10-15 21:13:45.741900', 'RPC error': '2022-10-15 21:13:52.823347'}> (decorators.py:112)
[2022-10-15T21:35:47.097Z] [2022-10-15 21:13:52 - ERROR - ci_test]: Traceback (most recent call last):
[2022-10-15T21:35:47.097Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2022-10-15T21:35:47.097Z]     res = func(*args, **_kwargs)
[2022-10-15T21:35:47.097Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2022-10-15T21:35:47.097Z]     return func(*arg, **kwargs)
[2022-10-15T21:35:47.097Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/utility.py", line 546, in load_balance
[2022-10-15T21:35:47.097Z]     return _get_connection(using).load_balance(collection_name, src_node_id, dst_node_ids, sealed_segment_ids, timeout=timeout)
[2022-10-15T21:35:47.097Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 113, in handler
[2022-10-15T21:35:47.097Z]     raise e
[2022-10-15T21:35:47.097Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2022-10-15T21:35:47.097Z]     return func(*args, **kwargs)
[2022-10-15T21:35:47.097Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 139, in handler
[2022-10-15T21:35:47.097Z]     ret = func(self, *args, **kwargs)
[2022-10-15T21:35:47.097Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 89, in handler
[2022-10-15T21:35:47.097Z]     raise e
[2022-10-15T21:35:47.097Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 51, in handler
[2022-10-15T21:35:47.097Z]     return func(self, *args, **kwargs)
[2022-10-15T21:35:47.097Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 964, in load_balance
[2022-10-15T21:35:47.097Z]     raise MilvusException(status.error_code, status.reason)
[2022-10-15T21:35:47.097Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=failed to balance segments, err=context deadline exceeded)>
[2022-10-15T21:35:47.097Z]  (api_request.py:39)
[2022-10-15T21:35:47.098Z] [2022-10-15 21:13:52 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=failed to balance segments, err=context deadline exceeded)> (api_request.py:40)
```

### Expected Behavior

PASSED

### Steps To Reproduce

```markdown
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/162/pipeline/187
```

### Milvus Log

1. milvus log: [artifacts-milvus-distributed-pulsar-nightly-162-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/162/artifact/artifacts-milvus-distributed-pulsar-nightly-162-pymilvus-e2e-logs.tar.gz)
2. collection name: utility_45ZXJbAa
3. FAILED timeline: [2022-10-15T21:13:54.960Z] [gw1] [ 99%] FAILED testcases/test_utility.py::TestUtilityAdvanced::test_load_balance_normal

**Comment by sunby** [comment]
This issue is caused by ShowPartitions timeout(5s) and ShowPartiton actually spent 7s. We should find the reason why it spent so long time. @longjiquan
