### ISSUE TITLE
[Bug]: [benchmark][standalone] Milvus load failed, rasie an error"collection has not been loaded to memory or load failed"

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#19827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20221014-bdaddd7b
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0dev40
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

release_name_prefix
fouramf-pf4mt
deploy_config
empty-file
case_params
empty-file
other_params
 --milvus_tag_prefix=master -k test_search_time -s 

```
fouramf-pf4mt-71-2626-etcd-0                                 1/1     Running     0             3m52s   10.104.4.68    4am-node11   <none>           <none>
fouramf-pf4mt-71-2626-milvus-standalone-67987d8585-7xfbg     1/1     Running     0             3m52s   10.104.9.231   4am-node14   <none>           <none>
fouramf-pf4mt-71-2626-minio-968fcf766-l7q54                  1/1     Running     0             3m52s   10.104.1.245   4am-node10   <none>           <none> (cli_client.py:123)"
```

client log:
```

[2022-10-14 10:07:04 - DEBUG - fouram]: (api_response) : <pymilvus.orm.index.Index object at 0x7f6a5ef7ea90>  (api_request.py:24)"
[2022-10-14 10:07:04 -  INFO - fouram]: [Time] Index run in 0.0151s (api_request.py:29)"
[2022-10-14 10:07:04 -  INFO - fouram]: [CommonCases] RT of build index IVF_FLAT: 0.0151s (common_cases.py:80)"
[2022-10-14 10:07:04 - DEBUG - fouram]: (api_request)  : [Collection.has_index] args: [], kwargs: {} (api_request.py:53)"
[2022-10-14 10:07:04 - DEBUG - fouram]: (api_response) : True  (api_request.py:24)"
[2022-10-14 10:07:04 - DEBUG - fouram]: [Time] Collection.has_index run in 0.0136s (api_request.py:31)"
[2022-10-14 10:07:04 - DEBUG - fouram]: (api_request)  : [Collection.index] args: [], kwargs: {} (api_request.py:53)"
[2022-10-14 10:07:04 - DEBUG - fouram]: (api_response) : <pymilvus.orm.index.Index object at 0x7f6a5ef7eb20>  (api_request.py:24)"
[2022-10-14 10:07:04 - DEBUG - fouram]: [Time] Collection.index run in 0.0119s (api_request.py:31)"
[2022-10-14 10:07:04 -  INFO - fouram]: [Base] Params of index: {'index_type': 'IVF_FLAT', 'metric_type': 'L2', 'params': {'nlist': 2048}} (base.py:221)"
[2022-10-14 10:07:04 -  INFO - fouram]: [CommonCases] Prepare index IVF_FLAT done. (common_cases.py:83)"
[2022-10-14 10:07:04 -  INFO - fouram]: [Base] Start load collection fouram_cmBmFF2V, replica_number:1 (base.py:95)"
[2022-10-14 10:07:04 - DEBUG - fouram]: (api_request)  : [Collection.load] args: [None, 1, None], kwargs: {} (api_request.py:53)"
[2022-10-14 10:27:53 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=collection fouram_cmBmFF2V has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-10-14 10:07:04.630716', 'RPC error': '2022-10-14 10:27:53.263322'}> (decorators.py:112)"
[2022-10-14 10:27:53 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=collection fouram_cmBmFF2V has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-10-14 10:07:04.590437', 'RPC error': '2022-10-14 10:27:53.263774'}> (decorators.py:112)"
[2022-10-14 10:27:53 - ERROR - fouram]: Traceback (most recent call last):
  File "/src/fouram/client/util/api_request.py", line 21, in inner_wrapper
    res = func(*args, **kwargs)
  File "/src/fouram/client/util/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 473, in load
    conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 113, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 139, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 89, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 657, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 113, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 139, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 89, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 666, in wait_for_loading_collection
    return self._wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 695, in _wait_for_loading_collection
    progress = self.get_collection_loading_progress(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 674, in get_collection_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection fouram_cmBmFF2V has not been loaded to memory or load failed)>
 (api_request.py:35)"
[2022-10-14 10:27:53 - ERROR - fouram]: (api_response) : <MilvusException: (code=1, message=collection fouram_cmBmFF2V has not been loaded to memory or load failed)> (api_request.py:36)"
[2022-10-14 10:27:53 - ERROR - fouram]: [CheckFunc] load request check failed, response:<MilvusException: (code=1, message=collection fouram_cmBmFF2V has not been loaded to memory or load failed)>
```

### Steps To Reproduce

```markdown
1.create an collection
2.build an  ivf falt index
3. insert 50m data
4.create index again
5.load failed
```

**Comment by weiliu1031** [comment]
same problem with #19837

**Comment by jingkl** [comment]
same with issue #20002，close issue
