### ISSUE TITLE
[Bug]: [benchmark][standalone][scalar filtering] Load collection raise error: collection fouram_0MKXExg9 has not been loaded to memory or load failed

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#19837]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20221016-15878781
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.0.dev40
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task: fouramf-cron-n4tfx
test case: test_search_filter_time

client log:
[test_search_filter_time_1.zip](https://github.com/milvus-io/milvus/files/9799348/test_search_filter_time_1.zip)

```
[2022-10-17 05:58:13,945 -  INFO - fouram]: [Base] Start inserting, ids: 49900000 - 49949999, data size: 50,000,000 (base.py:114)
[2022-10-17 05:58:15,514 -  INFO - fouram]: [Time] Collection.insert run in 1.5682s (api_request.py:29)
[2022-10-17 05:58:15,572 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_0MKXExg9): 49900000 (base.py:237)
[2022-10-17 05:58:15,785 -  INFO - fouram]: [Base] Start inserting, ids: 49950000 - 49999999, data size: 50,000,000 (base.py:114)
[2022-10-17 05:58:17,599 -  INFO - fouram]: [Time] Collection.insert run in 1.813s (api_request.py:29)
[2022-10-17 05:58:17,683 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_0MKXExg9): 49900000 (base.py:237)
[2022-10-17 05:58:17,742 -  INFO - fouram]: [Base] Total time of insert: 1429.8502s, average number of vector bars inserted per second: 34968.6981, average time to insert 50000 vectors per time: 1.4299s (base.py:172)
[2022-10-17 05:58:17,743 -  INFO - fouram]: [Base] Start flush collection fouram_0MKXExg9 (base.py:91)
[2022-10-17 05:58:19,982 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_0MKXExg9): 50000000 (base.py:237)
[2022-10-17 05:58:20,030 -  INFO - fouram]: [Base] Params of index: {'index_type': 'IVF_FLAT', 'metric_type': 'L2', 'params': {'nlist': 2048}} (base.py:221)
[2022-10-17 05:58:20,030 -  INFO - fouram]: [Base] Start build index of IVF_FLAT, params:{'index_type': 'IVF_FLAT', 'metric_type': 'L2', 'params': {'nlist': 2048}} (base.py:215)
[2022-10-17 05:58:20,055 -  INFO - fouram]: [Time] Index run in 0.025s (api_request.py:29)
[2022-10-17 05:58:20,055 -  INFO - fouram]: [CommonCases] RT of build index IVF_FLAT: 0.025s (common_cases.py:80)
[2022-10-17 05:58:20,104 -  INFO - fouram]: [Base] Params of index: {'index_type': 'IVF_FLAT', 'metric_type': 'L2', 'params': {'nlist': 2048}} (base.py:221)
[2022-10-17 05:58:20,104 -  INFO - fouram]: [CommonCases] Prepare index IVF_FLAT done. (common_cases.py:83)
[2022-10-17 05:58:20,105 -  INFO - fouram]: [Base] Start load collection fouram_0MKXExg9, replica_number:1 (base.py:95)
[2022-10-17 06:22:28,491 - ERROR - fouram]: Traceback (most recent call last):
  File "/src/fouram/client/util/api_request.py", line 21, in inner_wrapper
    res = func(*args, **kwargs)
  File "/src/fouram/client/util/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 473, in load
    conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 113, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 139, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 89, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 657, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 113, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 139, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 89, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 666, in wait_for_loading_collection
    return self._wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 695, in _wait_for_loading_collection
    progress = self.get_collection_loading_progress(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 674, in get_collection_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection fouram_0MKXExg9 has not been loaded to memory or load failed)>
 (api_request.py:35)
[2022-10-17 06:22:28,492 - ERROR - fouram]: (api_response) : <MilvusException: (code=1, message=collection fouram_0MKXExg9 has not been loaded to memory or load failed)> (api_request.py:36)
[2022-10-17 06:22:28,492 - ERROR - fouram]: [CheckFunc] load request check failed, response:<MilvusException: (code=1, message=collection fouram_0MKXExg9 has not been loaded to memory or load failed)> (func_check.py:40)
```

server:
```
[2022-10-17 06:22:28,652 -  INFO - fouram]: [Base] Deploy initial state: 
I1017 05:22:50.995982     312 request.go:665] Waited for 1.171986766s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.local/apis/networking.k8s.io/v1?timeout=32s
NAME                                                             READY   STATUS      RESTARTS        AGE     IP             NODE         NOMINATED NODE   READINESS GATES
fouramf-cron-n4tfx-49-4993-etcd-0                                1/1     Running     0               112s    10.104.6.192   4am-node13   <none>           <none>
fouramf-cron-n4tfx-49-4993-milvus-standalone-67fb8698d8-l5fbt    1/1     Running     0               112s    10.104.4.170   4am-node11   <none>           <none>
fouramf-cron-n4tfx-49-4993-minio-7cb4b4d998-fzxvp                1/1     Running     0               112s    10.104.4.171   4am-node11   <none>           <none> (base.py:126)
[2022-10-17 06:22:28,653 -  INFO - fouram]: [Cmd Exe]  kubectl get pods  -n qa-milvus  -o wide | grep -E 'STATUS|fouramf-cron-n4tfx-49-4993'  (util_cmd.py:14)
[2022-10-17 06:22:34,582 -  INFO - fouram]: [CliClient] pod details of release(fouramf-cron-n4tfx-49-4993): 
 I1017 06:22:29.932892    4962 request.go:665] Waited for 1.149479577s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.local/apis/acme.cert-manager.io/v1?timeout=32s
NAME                                                             READY   STATUS      RESTARTS        AGE     IP             NODE         NOMINATED NODE   READINESS GATES
fouramf-cron-n4tfx-49-4993-etcd-0                                1/1     Running     0               61m     10.104.6.192   4am-node13   <none>           <none>
fouramf-cron-n4tfx-49-4993-milvus-standalone-67fb8698d8-l5fbt    1/1     Running     0               61m     10.104.4.170   4am-node11   <none>           <none>
fouramf-cron-n4tfx-49-4993-minio-7cb4b4d998-fzxvp                1/1     Running     0               61m     10.104.4.171   4am-node11   <none>           <none> (cli_client.py:123)
[2022-10-17 06:22:34,582 -  INFO - fouram]: [Base] Start deleting services: fouramf-cron-n4tfx-49-4993 (base.py:129)
[2022-10-17 06:22:34,582 -  INFO - fouram]: [Cmd Exe]  kubectl get pvc  -n qa-milvus  | grep -E 'STATUS|fouramf-cron-n4tfx-49-4993'  (util_cmd.py:14)
[2022-10-17 06:22:40,481 -  INFO - fouram]: [CliClient] pvc storage class of release(fouramf-cron-n4tfx-49-4993): 
 I1017 06:22:35.853495    5001 request.go:665] Waited for 1.168368798s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.local/apis/scheduling.k8s.io/v1?timeout=32s
NAME                                                                                               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-fouramf-cron-n4tfx-49-4993-etcd-0                                                             Bound    pvc-f7694178-a290-48b4-9087-acd246177ca5   10Gi       RWO            local-path     61m
fouramf-cron-n4tfx-49-4993-milvus                                                                  Bound    pvc-91e08730-c9c6-4712-88c2-2f06eedcae47   50Gi       RWO            local-path     61m
fouramf-cron-n4tfx-49-4993-minio                                                                   Bound    pvc-eade4e15-0382-453a-b322-bf406603bf6e   500Gi      RWO            local-path     61m (cli_client.py:131)
```

### Steps To Reproduce

```markdown
1、create collection
2、build index of ivf_flat
3、insert 50m vectors
4、flush collection
5、build index with the same params
6、load collection 《- raise error
```

### Anything else?

client params:
```
{
     "dataset_params": {
          "dim": 128,
          "dataset_name": "sift",
          "dataset_size": 50000000,
          "ni_per": 50000,
          "metric_type": "L2",
          "req_run_counts": 10
     },
     "collection_params": {
          "other_fields": [
               "int64_1",
               "int64_2",
               "float_1",
               "double_1",
               "varchar_1"
          ]
     },
     "load_params": {},
     "search_params": {
          "expr": [
               {
                    "float_1": {
                         "GT": -1,
                         "LT": 5000000
                    }
               },
               {
                    "float_1": {
                         "GT": -1,
                         "LT": 25000000
                    }
               },
               {
                    "float_1": {
                         "GT": -1,
                         "LT": 45000000
                    }
               }
          ],
          "top_k": [
               1,
               10,
               100,
               1000
          ],
          "nq": [
               1,
               10,
               100,
               200,
               500,
               1000,
               1200
          ],
          "search_param": {
               "nprobe": [
                    8,
                    32
               ]
          }
     },
     "index_params": {
          "index_type": "IVF_FLAT",
          "index_param": {
               "nlist": 2048
          }
     }
}
```

**Comment by xige-16** [comment]
> /assign @xige-16 pls help on this one

OK

**Comment by xige-16** [comment]
During the process of inserting data, the memory keeps rising (no load). I turn off autocomaction locally, but I can still see  that the memory keeps rising.

<img width="1293" alt="截屏2022-10-18 11 53 39" src="https://user-images.githubusercontent.com/20124155/196331749-716119bd-2fb7-41c1-94e0-07f07bd80673.png">

**Comment by xige-16** [comment]
Compared with 2.1, the memory consumption of the insert and build index stages is basically the same, but the number of segments in the 2.1 version is 1/3 less than that of the master branch. And the autocomaction of the master branch does not take effect.

**Comment by congqixia** [comment]
@xige-16 @wayblink  FYI, a similar test scene could load with same record number. The key difference I suspect is that the successful one DOES NOT has scalar field. 
One possible direction to inspect is the memory consumption of string field.

**Comment by xige-16** [comment]
> @xige-16 @wayblink FYI, a similar test scene could load with same record number. The key difference I suspect is that the successful one DOES NOT has scalar field. One possible direction to inspect is the memory consumption of string field.

@wangting0128 Did you run with varchar field before?

**Comment by wayblink** [comment]
AutoCompaction is not hitted because the segment size changed.

Small compaction policy:
collect small segments greedly to reach a max_row_num(654720), put these segments into bucket
rule 1: len(bucket) >= minSegmentMerge(4) ||
rule 2: sum(segment_row_num in bucket) > max_row_num(654720) * smallPortion(0.9)
if rule 1 || rule 2 {
	compact()
}

In test:
2.1: each segment ~ 25000 rows, will hit rule 1
master: each segment ~ 17W+ rows, is an awkward value, both rule missed.
According to calculation, 17W+ rows/each segment is a reasonable value.
If I set minSegmentMerge=3, compaction will take effect.

So I think it is a tune issue instead of a bug. 
And we can enhance compaction policy, make it more adaptive, be aware of cluster load. 
@xige-16 @wangting0128 @congqixia @soothing-rain

**Comment by wayblink** [comment]
AutoCompaction is not hitted because the segment size changed.

Small compaction policy:
collect small segments greedly to reach a max_row_num(654720), put these segments into bucket
rule 1: len(bucket) >= minSegmentMerge(4) ||
rule 2: sum(segment_row_num in bucket) > max_row_num(654720) * smallPortion(0.9)
if rule 1 || rule 2 {
	compact()
}

2.1: each segment ~ 25000 rows, will hit rule 1
master: each segment ~ 17W+ rows, is an awkward value, both rule missed.
According to calculation, 17W+ rows/each segment is a reasonable value.
If set minSegmentMerge=3, compaction will take effect.

I think it is a tune issue instead of a bug. 
And we can enhance compaction policy, make it more adaptive, aware of cluster load. 
@xige-16 @wangting0128 @congqixia @soothing-rain

**Comment by jingkl** [comment]
fouramf-cron-1666454400
case_name
test_search_filter
server
```
fouramf-cron-1666454400-2-58-1268-etcd-0                          1/1     Running                  0               3m42s   10.104.9.166   4am-node14   <none>           <none>
fouramf-cron-1666454400-2-58-1268-milvus-standalone-84787bchhqp   1/1     Running                  0               3m42s   10.104.6.221   4am-node13   <none>           <none>
fouramf-cron-1666454400-2-58-1268-minio-b8d58c5d7-chp9d           1/1     Running                  0               3m42s   10.104.9.157   4am-node14   <none>           <none> (cli_client.py:123)"
```
client log：
```
2022-10-22 16:39:47 -  INFO - fouram]: [CommonCases] No scalars need to be indexed. (common_cases.py:91)"
[2022-10-22 16:39:47 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_fa0oKlht): 50000000 (base.py:244)"
[2022-10-22 16:39:47 -  INFO - fouram]: [Base] Start load collection fouram_fa0oKlht, replica_number:1 (base.py:97)"
[2022-10-22 16:39:47 - DEBUG - fouram]: (api_request)  : [Collection.load] args: [None, 1, None], kwargs: {} (api_request.py:53)"
[2022-10-22 17:02:29 - ERROR - pymilvus.decorators]: RPC error: [get_loading_progress], <MilvusException: (code=1, message=collection 436851082682433538 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-10-22 17:02:29.198301', 'RPC error': '2022-10-22 17:02:29.199751'}> (decorators.py:112)"
[2022-10-22 17:02:29 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=collection 436851082682433538 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-10-22 16:39:47.225221', 'RPC error': '2022-10-22 17:02:29.200226'}> (decorators.py:112)"
[2022-10-22 17:02:29 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=collection 436851082682433538 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-10-22 16:39:47.109721', 'RPC error': '2022-10-22 17:02:29.200311'}> (decorators.py:112)"
[2022-10-22 17:02:29 - ERROR - fouram]: Traceback (most recent call last):
  File "/src/fouram/client/util/api_request.py", line 21, in inner_wrapper
    res = func(*args, **kwargs)
  File "/src/fouram/client/util/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 473, in load
    conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 113, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 139, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 89, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 665, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 113, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 139, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 89, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 683, in wait_for_loading_collection
    progress = self.get_loading_progress(collection_name, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 113, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 139, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 89, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 744, in get_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection 436851082682433538 has not been loaded to memory or load failed)>
 (api_request.py:35)"
```

**Comment by wayblink** [comment]
Memory consume in load become larger in 2.2. Shown in the following graph, the red block only exists in 2.2's.
![image](https://user-images.githubusercontent.com/18096561/199194107-c8b38ddf-22aa-4dd4-b737-a01b28dd734b.png)
Discussed with @xige-16 . It is related to the following logic, the raw_data from multi files is loaded into memory and assemble to a large one. We changed some logic and order which leads to the raw_data copied twice. We can optimize this.
https://github.com/milvus-io/milvus/blob/master/internal/core/src/index/VectorMemIndex.cpp#L67-L77

**Comment by wangting0128** [comment]
verify: 2.2.0-20221105-16c8642b
close issue
