### ISSUE TITLE
[Bug]: [Nightly]Search failed reporting 'fail to search on all shard leaders, err=fail to Search, QueryNode ID=12, reason=Search 1 failed, reason query shard(channel)  by-dev-rootcoord-dml_160_436739632224134850v1  does not exist'

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#19850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:0a83cdf
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0.dev45
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Search failed reporting 'fail to search on all shard leaders, err=fail to Search, QueryNode ID=12, reason=Search 1 failed, reason query shard(channel)  by-dev-rootcoord-dml_160_436739632224134850v1  does not exist'.
```
[2022-10-17T21:44:54.458Z] [2022-10-17 18:35:10 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=12, reason=Search 1 failed, reason query shard(channel)  by-dev-rootcoord-dml_160_436739632224134850v1  does not exist
[2022-10-17T21:44:54.458Z]  err %!w(<nil>))>, <Time:{'RPC start': '2022-10-17 18:35:09.088707', 'RPC error': '2022-10-17 18:35:10.096655'}> (decorators.py:112)
[2022-10-17T21:44:54.458Z] [2022-10-17 18:35:10 - ERROR - ci_test]: Traceback (most recent call last):
[2022-10-17T21:44:54.458Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2022-10-17T21:44:54.458Z]     res = func(*args, **_kwargs)
[2022-10-17T21:44:54.458Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2022-10-17T21:44:54.458Z]     return func(*arg, **kwargs)
[2022-10-17T21:44:54.458Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 716, in search
[2022-10-17T21:44:54.458Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,
[2022-10-17T21:44:54.458Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 113, in handler
[2022-10-17T21:44:54.458Z]     raise e
[2022-10-17T21:44:54.458Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2022-10-17T21:44:54.458Z]     return func(*args, **kwargs)
[2022-10-17T21:44:54.458Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 139, in handler
[2022-10-17T21:44:54.458Z]     ret = func(self, *args, **kwargs)
[2022-10-17T21:44:54.458Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 89, in handler
[2022-10-17T21:44:54.458Z]     raise e
[2022-10-17T21:44:54.458Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 51, in handler
[2022-10-17T21:44:54.458Z]     return func(self, *args, **kwargs)
[2022-10-17T21:44:54.458Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 471, in search
[2022-10-17T21:44:54.458Z]     return self._execute_search_requests(requests, timeout, **_kwargs)
[2022-10-17T21:44:54.458Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 435, in _execute_search_requests
[2022-10-17T21:44:54.458Z]     raise pre_err
[2022-10-17T21:44:54.458Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 426, in _execute_search_requests
[2022-10-17T21:44:54.458Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2022-10-17T21:44:54.458Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=12, reason=Search 1 failed, reason query shard(channel)  by-dev-rootcoord-dml_160_436739632224134850v1  does not exist
[2022-10-17T21:44:54.458Z]  err %!w(<nil>))>
[2022-10-17T21:44:54.458Z]  (api_request.py:39)
[2022-10-17T21:44:54.458Z] [2022-10-17 18:35:10 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=12, reason=Search 1 failed, reason query shard(channel)  by-dev-rootcoord-dml_160_436739632224134850v1  does not exist
[2022-10-17T21:44:54.458Z]  err %!w(<nil>))> (api_request.py:40)

```

### Expected Behavior

PASSED

### Steps To Reproduce

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/164/pipeline/155/

### Milvus Log

1. milvus log: [artifacts-milvus-distributed-kafka-nightly-164-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/164/artifact/artifacts-milvus-distributed-kafka-nightly-164-pymilvus-e2e-logs.tar.gz)
2. collection name: search_collection_3a1AU8Aq
3. failed time: [2022-10-17T18:35:11.417Z] [gw5] [ 40%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_collection_multiple_times[5000-500-8-False-False]

**Comment by sunby** [comment]
QueryNode unsubscribe dmchannel by releaseCollectionTask which is dangerous. And it lead to unavailable search service, we will fix it.

**Comment by NicoYuan1986** [comment]
Latest: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/193/pipeline/155

milvus: 2390095
pymilvus: 2.2.0.dev72

1. log: [artifacts-milvus-distributed-pulsar-nightly-193-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/193/artifact/artifacts-milvus-distributed-pulsar-nightly-193-pymilvus-e2e-logs.tar.gz)
2. collection name: query_5O6cVQ4J
3. FAILED time: [2022-11-17T18:11:24.603Z] [gw1] [ 31%] FAILED testcases/test_query.py::TestQueryParams::test_query_pagination_with_expression[100-int64 > 0]

**Comment by NicoYuan1986** [comment]
Latest: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/9/pipeline/155

milvus: efa1cf7
pymilvus: 2.2.0.dev71

1. log: [artifacts-milvus-distributed-kafka-nightly-9-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/9/artifact/artifacts-milvus-distributed-kafka-nightly-9-pymilvus-e2e-logs.tar.gz)
2. collection name: query_KtJdwxcD
3. FAILED time: [2022-11-21T20:11:00.982Z] [gw1] [ 28%] FAILED testcases/test_query.py::TestQueryParams::test_query_pagination_with_expression[100-float in [+3**6, 2**10/2]]

**Comment by NicoYuan1986** [comment]
The error hasn't occurred for some time, so close it now.
