### ISSUE TITLE
[Bug]: [benchmark][standalone] Milvus load failed, raise an error"fail to show collections from the querycoord, no data"

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#19881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20221018-a752682d
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0.dev45
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server-instance
fouram-concurrent-1666108800-1
server-configmap
server-single-4c16m-diskann
client-configmap
client-locust-search-sift10m-diskann
Milvus:
```
fouram-concurrent-1666108800-1-etcd-0                             1/1     Running             0             118s   10.104.6.6     4a
m-node13   <none>           <none>
fouram-concurrent-1666108800-1-milvus-standalone-86496c89cbfd2v   1/1     Running             0             118s   10.104.9.27    4a
m-node14   <none>           <none>
fouram-concurrent-1666108800-1-minio-7fc8584c55-5qpfj             1/1     Running             0             118s   10.104.6.240   4a
m-node13   <none>           <none>
```

```
[2022-10-18 17:09:43,105] [    INFO] - Start load collection (milvus_benchmark.runners.locust:459)
[2022-10-18 17:09:49,855] [ WARNING] - [93m[get_loading_progress] retry:4, cost: 0.27s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:72)
[2022-10-18 17:09:50,126] [ WARNING] - [93m[get_loading_progress] retry:5, cost: 0.81s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:72)
[2022-10-18 17:09:50,937] [ WARNING] - [93m[get_loading_progress] retry:6, cost: 2.43s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:72)
[2022-10-18 17:09:53,369] [ WARNING] - [93m[get_loading_progress] retry:7, cost: 7.290000000000001s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:72)
[2022-10-18 17:10:00,660] [ WARNING] - [93m[get_loading_progress] retry:8, cost: 21.870000000000005s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:72)
[2022-10-18 17:10:22,531] [ WARNING] - [93m[get_loading_progress] retry:9, cost: 60s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:72)
[2022-10-18 17:11:22,533] [ WARNING] - [93m[get_loading_progress] retry:10, cost: 60s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:72)
[2022-10-18 17:12:22,536] [ WARNING] - [93mRetry run out of 10 retry times[0m (pymilvus.decorators:80)
[2022-10-18 17:12:22,536] [   ERROR] - RPC error: [get_loading_progress], <MilvusException: (code=1, message=Retry run out of 10 retry times, message=fail to show collections from the querycoord, no data)>, <Time:{'RPC start': '2022-10-18 17:09:49.722041', 'RPC error': '2022-10-18 17:12:22.536650'}> (pymilvus.decorators:112)
[2022-10-18 17:12:22,536] [   ERROR] - RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=Retry run out of 10 retry times, message=fail to show collections from the querycoord, no data)>, <Time:{'RPC start': '2022-10-18 17:09:43.113171', 'RPC error': '2022-10-18 17:12:22.536746'}> (pymilvus.decorators:112)
[2022-10-18 17:12:22,536] [   ERROR] - RPC error: [load_collection], <MilvusException: (code=1, message=Retry run out of 10 retry times, message=fail to show collections from the querycoord, no data)>, <Time:{'RPC start': '2022-10-18 17:09:43.105152', 'RPC error': '2022-10-18 17:12:22.536796'}> (pymilvus.decorators:112)
[2022-10-18 17:12:22,536] [   ERROR] - <MilvusException: (code=1, message=Retry run out of 10 retry times, message=fail to show collections from the querycoord, no data)> (milvus_benchmark.main:118)
[2022-10-18 17:12:22,538] [   ERROR] - Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 744, in get_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to show collections from the querycoord, no data)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 87, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/locust.py", line 461, in prepare
    self.milvus.load_collection(replica_number=replica_number)
  File "/src/milvus_benchmark/client.py", line 53, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 592, in load_collection
    return self._milvus.load_collection(collection_name, **params)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/stub.py", line 195, in load_collection
    return handler.load_collection(collection_name=collection_name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 113, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 139, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 89, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 665, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 113, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 139, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 89, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 683, in wait_for_loading_collection
    progress = self.get_loading_progress(collection_name, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 113, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 139, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 81, in handler
    raise MilvusException(e.code, f"{timeout_msg}, message={e.message}")
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry run out of 10 retry times, message=fail to show collections from the querycoord, no data)>
 (milvus_benchmark.main:119)
```

### Expected Behavior

```
data:
  config.yaml: |
    locust_random_performance:
      collections:
        -
          collection_name: sift_10m_128_l2
          ni_per: 50000
          build_index: true
          index_type: diskann
          index_param: {}
          task:
            types:
              -
                type: query
                weight: 10
                params:
                  top_k: 10
                  nq: 10
                  search_param:
                    search_list: 30
              -
                type: load
                weight: 1
              -
                type: get
                weight: 2
                params:
                  ids_length: 10  
            connection_num: 1
            clients_num: 20
            spawn_rate: 2
            during_time: 1h
```

**Comment by xiaofan-luan** [comment]
/assign @weiliu1031 
pls help on this one

**Comment by weiliu1031** [comment]
![image](https://user-images.githubusercontent.com/108661493/196613810-b8ff5b6d-42bb-41e4-b0c4-ff00b7839784.png)
milvus standalone service crash here during load collection

**Comment by weiliu1031** [comment]
> ![image](https://user-images.githubusercontent.com/108661493/196613810-b8ff5b6d-42bb-41e4-b0c4-ff00b7839784.png) milvus standalone service crash here during load collection
more details: service crush at creating index 
![image](https://user-images.githubusercontent.com/108661493/196647629-c89d7c1b-ef6b-425b-b52c-a7967e0a0dbd.png)

**Comment by xige-16** [comment]
milvus panic after load disk index failed
```
  | 2022-10-19 01:09:48 | io_setup() failed; returned -11, errno=11:Resource temporarily unavailable
  | 2022-10-19 01:09:48 | bad thread access; returning -1 as io_context_t
  | 2022-10-19 01:09:48 | Assert "ok" at /go/src/github.com/milvus-io/milvus/internal/core/src/index/VectorDiskIndex.cpp:56
  | 2022-10-19 01:09:48 | => load disk index failed
  | 2022-10-19 01:09:48 | [2022/10/18 17:09:48.815 +00:00] [WARN] [querynode/cgo_helper.go:56] ["AppendIndex failed, C Runtime Exception: [UnexpectedError] Assert \"ok\" at /go/src/github.com/milvus-io/milvus/internal/core/src/index/VectorDiskIndex.cpp:56\n => load disk index failed\n"]

```
