### ISSUE TITLE
[Bug]: Milvus create diskann index timeout ，dataCoord panic cause milvus server crash

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#19899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:02871ea4b
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus==2.2.0.dev49
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

indexcase：

[gw4] linux -- Python 3.6.8 /usr/local/bin/python3

```
[2022-10-19T08:22:47.562Z] [gw4] linux -- Python 3.6.8 /usr/local/bin/python3[gw4] linux -- Python 3.6.8 /usr/local/bin/python3

[2022-10-19T08:22:47.562Z] 

[2022-10-19T08:22:47.562Z] self = <test_index.TestIndexDiskann object at 0x7fc185647978>

[2022-10-19T08:22:47.562Z] 

[2022-10-19T08:22:47.562Z]     @pytest.mark.tags(CaseLabel.L1)

[2022-10-19T08:22:47.562Z]     def test_create_index_with_diskann_normal(self):

[2022-10-19T08:22:47.562Z]         """

[2022-10-19T08:22:47.562Z]         target: test create index with diskann

[2022-10-19T08:22:47.562Z]         method: 1.create collection and insert data

[2022-10-19T08:22:47.562Z]                 2.create diskann index , then load data

[2022-10-19T08:22:47.562Z]                 3.search successfully

[2022-10-19T08:22:47.562Z]         expected: create index successfully

[2022-10-19T08:22:47.562Z]         """

[2022-10-19T08:22:47.562Z]         c_name = cf.gen_unique_str(prefix)

[2022-10-19T08:22:47.562Z]         collection_w = self.init_collection_wrap(name=c_name)

[2022-10-19T08:22:47.562Z]         data = cf.gen_default_list_data()

[2022-10-19T08:22:47.562Z]         collection_w.insert(data=data)

[2022-10-19T08:22:47.562Z] >       index, _ = self.index_wrap.init_index(collection_w.collection, default_float_vec_field_name, ct.default_diskann_index)
```

client log：
```
[2022-10-19T08:22:47.563Z] [2022-10-19 08:22:36 - WARNING - pymilvus.decorators]: Retry timeout: 40s (decorators.py:80)

[2022-10-19T08:22:47.563Z] [2022-10-19 08:22:36 - ERROR - pymilvus.decorators]: RPC error: [wait_for_creating_index], <MilvusException: (code=1, message=Retry timeout: 40s, message=CreateIndex Timeout)>, <Time:{'RPC start': '2022-10-19 08:21:56.008952', 'RPC error': '2022-10-19 08:22:36.355579'}> (decorators.py:112)

[2022-10-19T08:22:47.563Z] [2022-10-19 08:22:36 - WARNING - pymilvus.decorators]: Retry timeout: 40s (decorators.py:80)

[2022-10-19T08:22:47.563Z] [2022-10-19 08:22:36 - ERROR - pymilvus.decorators]: RPC error: [create_index], <MilvusException: (code=1, message=Retry timeout: 40s, message=Retry timeout: 40s, message=CreateIndex Timeout)>, <Time:{'RPC start': '2022-10-19 08:21:53.491496', 'RPC error': '2022-10-19 08:22:36.355944'}> (decorators.py:112)

[2022-10-19T08:22:47.563Z] [2022-10-19 08:22:36 - ERROR - ci_test]: Traceback (most recent call last):

[2022-10-19T08:22:47.563Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 51, in handler

[2022-10-19T08:22:47.563Z]     return func(self, *args, **kwargs)

[2022-10-19T08:22:47.563Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 662, in wait_for_creating_index

[2022-10-19T08:22:47.563Z]     raise MilvusException(1, "CreateIndex Timeout")

[2022-10-19T08:22:47.563Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=CreateIndex Timeout)>

[2022-10-19T08:22:47.563Z] 

[2022-10-19T08:22:47.563Z] During handling of the above exception, another exception occurred:

[2022-10-19T08:22:47.563Z] 

[2022-10-19T08:22:47.563Z] Traceback (most recent call last):

[2022-10-19T08:22:47.563Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 51, in handler

[2022-10-19T08:22:47.563Z]     return func(self, *args, **kwargs)

[2022-10-19T08:22:47.563Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 589, in create_index

[2022-10-19T08:22:47.563Z]     timeout=timeout)

[2022-10-19T08:22:47.563Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 113, in handler

[2022-10-19T08:22:47.563Z]     raise e

[2022-10-19T08:22:47.563Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 109, in handler

[2022-10-19T08:22:47.563Z]     return func(*args, **kwargs)

[2022-10-19T08:22:47.563Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 139, in handler

[2022-10-19T08:22:47.563Z]     ret = func(self, *args, **kwargs)

[2022-10-19T08:22:47.563Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 81, in handler

[2022-10-19T08:22:47.563Z]     raise MilvusException(e.code, f"{timeout_msg}, message={e.message}")

[2022-10-19T08:22:47.563Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 40s, message=CreateIndex Timeout)>

[2022-10-19T08:22:47.563Z] 

[2022-10-19T08:22:47.563Z] During handling of the above exception, another exception occurred:

[2022-10-19T08:22:47.563Z] 

[2022-10-19T08:22:47.563Z] Traceback (most recent call last):

[2022-10-19T08:22:47.563Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2022-10-19T08:22:47.563Z]     res = func(*args, **_kwargs)

[2022-10-19T08:22:47.563Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2022-10-19T08:22:47.563Z]     return func(*arg, **kwargs)

[2022-10-19T08:22:47.563Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/index.py", line 85, in __init__

[2022-10-19T08:22:47.563Z]     conn.create_index(self._collection.name, self._field_name, self._index_params, **kwargs)

[2022-10-19T08:22:47.563Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 113, in handler

[2022-10-19T08:22:47.563Z]     raise e

[2022-10-19T08:22:47.563Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 109, in handler

[2022-10-19T08:22:47.563Z]     return func(*args, **kwargs)

[2022-10-19T08:22:47.563Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 139, in handler

[2022-10-19T08:22:47.563Z]     ret = func(self, *args, **kwargs)

[2022-10-19T08:22:47.563Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 81, in handler

[2022-10-19T08:22:47.563Z]     raise MilvusException(e.code, f"{timeout_msg}, message={e.message}")

[2022-10-19T08:22:47.563Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 40s, message=Retry timeout: 40s, message=CreateIndex Timeout)>

[2022-10-19T08:22:47.564Z]  (api_request.py:39)

[2022-10-19T08:22:47.564Z] [2022-10-19 08:22:36 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 40s, message=Retry timeout: 40s, message=CreateIndex Timeout)> (api_request.py:40)
```

jerkins：https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-19893/1/pipeline/

server

```
2022-10-19T16:22:38.086450315+08:00 stdout F [2022/10/19 08:22:38.086 +00:00] [INFO] [datacoord/compaction.go:280] ["handleCompactionResult: success to handle merge compaction result"] [planID=436775768024699475]
2022-10-19T16:22:38.086467238+08:00 stdout F [2022/10/19 08:22:38.086 +00:00] [DEBUG] [datacoord/compaction.go:362] ["try to release queue"] [nodeID=4]
2022-10-19T16:22:38.086478541+08:00 stdout F [2022/10/19 08:22:38.086 +00:00] [INFO] [datacoord/compaction.go:313] ["compaction completed"] [planID=436775768024699477] [nodeID=4]
2022-10-19T16:22:38.086489594+08:00 stdout F [2022/10/19 08:22:38.086 +00:00] [INFO] [datacoord/meta.go:864] ["meta update: get complete compaction meta"]
2022-10-19T16:22:38.087223656+08:00 stdout F [2022/10/19 08:22:38.087 +00:00] [DEBUG] [datacoord/meta.go:934] ["meta update: get complete compaction meta - complete"] [segmentID=436775768024699478] [collectionID=436775768024497617] [partitionID=436775768024497618] [NumOfRows=49937] [compactionFrom="[436775768024699053,436775768024498275,436775768024698703,436775768024698619,436775768024698961,436775768024498191,436775768024498016,436775768024698453,436775768024497801,436775768024699252,436775768024698515,436775768024698352,436775768024497870,436775768024497622,436775768024498112,436775768024698775,436775768024497945,436775768024699126,436775768024497711,436775768024698845]"]
2022-10-19T16:22:38.087250429+08:00 stdout F [2022/10/19 08:22:38.087 +00:00] [DEBUG] [datacoord/compaction.go:257] ["handleCompactionResult: altering metastore after compaction"] [planID=436775768024699477]
2022-10-19T16:22:38.089486051+08:00 stderr F panic: segment not found: 436775768024698774
2022-10-19T16:22:38.089506391+08:00 stderr F
2022-10-19T16:22:38.089514066+08:00 stderr F goroutine 155817 [running]:
2022-10-19T16:22:38.089526329+08:00 stderr F [github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Operate](http://github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Operate)(0xc0053905a0, {0xc009bfbab0?, 0x1?, 0x1?})
2022-10-19T16:22:38.089537762+08:00 stderr F    /go/src/[github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:408](http://github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:408) +0x3459
2022-10-19T16:22:38.089544057+08:00 stderr F [github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work(0xc018f47290)](http://github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work(0xc018f47290))
2022-10-19T16:22:38.089548083+08:00 stderr F    /go/src/[github.com/milvus-io/milvus/internal/util/flowgraph/node.go:112](http://github.com/milvus-io/milvus/internal/util/flowgraph/node.go:112) +0x232
2022-10-19T16:22:38.089552189+08:00 stderr F created by [github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start](http://github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start)
2022-10-19T16:22:38.089558971+08:00 stderr F    /go/src/[github.com/milvus-io/milvus/internal/util/flowgraph/node.go:68](http://github.com/milvus-io/milvus/internal/util/flowgraph/node.go:68) +0x79
```

**Comment by xiaocai2333** [comment]
DataCoord panic, PTAL @sunby 
/assign @sunby 
/unassign

**Comment by jingkl** [comment]
Already fixed, close the issue
