### ISSUE TITLE
[Bug]: Create varchar index timeout when concurrency is 4

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#19959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20221021-3d3289ce
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2022-10-21 02:44:44 - INFO - ci_test]: inserted 3000 data into collection deploy_test_index_type_BIN_IVF_FLAT_is_compacted_is_compacted_segment_status_all_is_string_indexed_is_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000 (common_func.py:684)
[2022-10-21 02:44:45 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [      int64   float varchar                                      binary_vector
0         0     0.0       0   b'\xf4\x1a\rY!.\x9c\x0b\n\xd1v\xa3\xa4.\x97\x9c'
1         1     1.0       1  b'\xe8q\x04\x84P\xc6\xc8\x0e\xdd\x85x\xeb\nn\x...
2         2     2.0       2  b'0\xc5+\xf8+\x03\xc5\xc7\x83\x80......, kwargs: {'timeout': 20} (api_request.py:56)
[2022-10-21 02:44:45 - DEBUG - ci_test]: (api_response) : (insert count: 3000, delete count: 0, upsert count: 0, timestamp: {self._timestamp}, success count: {self.succ_count}, err count: {self.err_count})  (api_request.py:31)
[2022-10-21 02:44:45 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 20} (api_request.py:56)
[2022-10-21 02:44:48 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)
[2022-10-21 02:44:48 - DEBUG - ci_test]: (api_request)  : [Collection.delete] args: ['int64 in [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]', None, 20], kwargs: {} (api_request.py:56)
[2022-10-21 02:44:48 - DEBUG - ci_test]: (api_response) : (insert count: 0, delete count: 10, upsert count: 0, timestamp: {self._timestamp}, success count: {self.succ_count}, err count: {self.err_count})  (api_request.py:31)
[2022-10-21 02:44:48 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['varchar', {}], kwargs: {'timeout': 40, 'index_name': '_default_string_idx'} (api_request.py:56)
[2022-10-21 02:45:28 - WARNING - pymilvus.decorators]: Retry timeout: 40s (decorators.py:79)
[2022-10-21 02:45:28 - ERROR - pymilvus.decorators]: RPC error: [wait_for_creating_index], <MilvusException: (code=1, message=Retry timeout: 40s, message=collection deploy_test_index_type_BIN_IVF_FLAT_is_compacted_is_compacted_segment_status_all_is_string_indexed_is_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000 create index _default_string_idx timeout in 40s)>, <Time:{'RPC start': '2022-10-21 02:44:48.462519', 'RPC error': '2022-10-21 02:45:28.929165'}> (decorators.py:108)
[2022-10-21 02:45:28 - WARNING - pymilvus.decorators]: Retry timeout: 40s (decorators.py:79)
[2022-10-21 02:45:28 - ERROR - pymilvus.decorators]: RPC error: [create_index], <MilvusException: (code=1, message=Retry timeout: 40s, message=Retry timeout: 40s, message=collection deploy_test_index_type_BIN_IVF_FLAT_is_compacted_is_compacted_segment_status_all_is_string_indexed_is_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000 create index _default_string_idx timeout in 40s)>, <Time:{'RPC start': '2022-10-21 02:44:48.432620', 'RPC error': '2022-10-21 02:45:28.929300'}> (decorators.py:108)
[2022-10-21 02:45:28 - ERROR - ci_test]: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 638, in wait_for_creating_index
    raise MilvusException(message=f"collection {collection_name} create index {index_name} timeout in {timeout}s")
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection deploy_test_index_type_BIN_IVF_FLAT_is_compacted_is_compacted_segment_status_all_is_string_indexed_is_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000 create index _default_string_idx timeout in 40s)>
```

### Expected Behavior

all test cases passed

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test/detail/deploy_test/440/pipeline
log:
[artifacts-standalone-reinstall-440-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9835483/artifacts-standalone-reinstall-440-server-logs.tar.gz)

[artifacts-standalone-reinstall-440-pytest-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/9835485/artifacts-standalone-reinstall-440-pytest-logs.1.tar.gz)

**Comment by xiaocai2333** [comment]
[pr19820]( https://github.com/milvus-io/milvus/pull/19820)  although ignore the index progress of the segment (A) which is compaction  from. But the index of `varchar` field will start after the index of segment (A) is done .

**Comment by zhuwenxing** [comment]
It reproduced stable, so set it as critical

**Comment by zhuwenxing** [comment]
It also blocked the reinstall test, because the test would be failed at the first deployment, so we can not check the behavior after reinstall

**Comment by zhuwenxing** [comment]
After reducing concurrency, this issue was not reproduced again
