### ISSUE TITLE
[Bug]: Release timeout after etcd pod kill chaos test for pulsar version

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#19951]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20221020-e8ca754d
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.2.0.dev57
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```


[2022-10-20T23:49:06.835Z] [2022-10-20 23:49:06 - INFO - ci_test]: assert index entities: 6000 (test_e2e.py:63)

[2022-10-20T23:49:10.985Z] [2022-10-20 23:49:10 - INFO - ci_test]: [test][2022-10-20T23:49:06Z] [3.79553098s] e2e__F9iDSO0C create_index -> Status(code=0, message=) (wrapper.py:30)

[2022-10-20T23:49:10.985Z] [2022-10-20 23:49:10 - INFO - ci_test]: assert index: 3.7957406044006348 (test_e2e.py:70)

[2022-10-20T23:49:32.842Z] [2022-10-20 23:49:30 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=wait for loading collection timeout, collection: e2e__F9iDSO0C)>, <Time:{'RPC start': '2022-10-20 23:49:10.135894', 'RPC error': '2022-10-20 23:49:30.294303'}> (decorators.py:108)

[2022-10-20T23:49:32.842Z] [2022-10-20 23:49:30 - WARNING - pymilvus.decorators]: Retry timeout: 20s (decorators.py:79)

[2022-10-20T23:49:32.842Z] [2022-10-20 23:49:30 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry timeout: 20s, message=wait for loading collection timeout, collection: e2e__F9iDSO0C)>, <Time:{'RPC start': '2022-10-20 23:49:10.119445', 'RPC error': '2022-10-20 23:49:30.294710'}> (decorators.py:108)

[2022-10-20T23:49:32.842Z] [2022-10-20 23:49:30 - ERROR - ci_test]: Traceback (most recent call last):

[2022-10-20T23:49:32.842Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 50, in handler

[2022-10-20T23:49:32.842Z]     return func(self, *args, **kwargs)

[2022-10-20T23:49:32.842Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 650, in load_collection

[2022-10-20T23:49:32.842Z]     self.wait_for_loading_collection(collection_name, timeout)

[2022-10-20T23:49:32.842Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 109, in handler

[2022-10-20T23:49:32.842Z]     raise e

[2022-10-20T23:49:32.842Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 105, in handler

[2022-10-20T23:49:32.842Z]     return func(*args, **kwargs)

[2022-10-20T23:49:32.842Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 136, in handler

[2022-10-20T23:49:32.842Z]     ret = func(self, *args, **kwargs)

[2022-10-20T23:49:32.842Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 85, in handler

[2022-10-20T23:49:32.842Z]     raise e

[2022-10-20T23:49:32.842Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 50, in handler

[2022-10-20T23:49:32.842Z]     return func(self, *args, **kwargs)

[2022-10-20T23:49:32.842Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 672, in wait_for_loading_collection

[2022-10-20T23:49:32.842Z]     raise MilvusException(message=f"wait for loading collection timeout, collection: {collection_name}")

[2022-10-20T23:49:32.842Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=wait for loading collection timeout, collection: e2e__F9iDSO0C)>

[2022-10-20T23:49:32.842Z] 

[2022-10-20T23:49:32.842Z] The above exception was the direct cause of the following exception:

[2022-10-20T23:49:32.842Z] 

[2022-10-20T23:49:32.842Z] Traceback (most recent call last):

[2022-10-20T23:49:32.842Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2022-10-20T23:49:32.842Z]     res = func(*args, **_kwargs)

[2022-10-20T23:49:32.842Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2022-10-20T23:49:32.842Z]     return func(*arg, **kwargs)

[2022-10-20T23:49:32.842Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 476, in load

[2022-10-20T23:49:32.842Z]     conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)

[2022-10-20T23:49:32.842Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 109, in handler

[2022-10-20T23:49:32.842Z]     raise e

[2022-10-20T23:49:32.842Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 105, in handler

[2022-10-20T23:49:32.842Z]     return func(*args, **kwargs)

[2022-10-20T23:49:32.842Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 136, in handler

[2022-10-20T23:49:32.842Z]     ret = func(self, *args, **kwargs)

[2022-10-20T23:49:32.842Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 80, in handler

[2022-10-20T23:49:32.842Z]     raise MilvusException(e.code, f"{timeout_msg}, message={e.message}") from e

[2022-10-20T23:49:32.842Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 20s, message=wait for loading collection timeout, collection: e2e__F9iDSO0C)>
```

### Expected Behavior

all test cases passed

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/2346/pipeline

log:
[artifacts-rootcoord-pod-failure-2346-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9835290/artifacts-rootcoord-pod-failure-2346-server-logs.tar.gz)

[artifacts-rootcoord-pod-failure-2346-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9835292/artifacts-rootcoord-pod-failure-2346-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
The following pod failure chaos tests all have this issue

minio: 
    failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/2348/pipeline
    log:
      [artifacts-s3-pod-failure-2348-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9836617/artifacts-s3-pod-failure-2348-server-logs.tar.gz)
     [artifacts-s3-pod-failure-2348-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9836621/artifacts-s3-pod-failure-2348-pytest-logs.tar.gz)

etcd:
    failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/2347/pipeline
    log: 
       [artifacts-etcd-pod-failure-2347-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9836632/artifacts-etcd-pod-failure-2347-server-logs.tar.gz)
      [artifacts-etcd-pod-failure-2347-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9836633/artifacts-etcd-pod-failure-2347-pytest-logs.tar.gz)


querynode
    failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/2345/pipeline
    log: 
        [artifacts-querynode-pod-failure-2345-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9836658/artifacts-querynode-pod-failure-2345-server-logs.tar.gz)
       [artifacts-querynode-pod-failure-2345-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9836659/artifacts-querynode-pod-failure-2345-pytest-logs.tar.gz)

**Comment by yah01** [comment]
looks like it's just the load is not fast enough

**Comment by yah01** [comment]
/assign @zhuwenxing 
plz help re-check this, as #19976 fixes a bug of IndexCoord, and makes the QueryCoord not load the growing segments, should be helpful

**Comment by zhuwenxing** [comment]
chaos type: pod-failure image tag: master-20221028-977947e2 target pod: querynode
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/2564/pipeline
log:
[artifacts-querynode-pod-failure-2564-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9893369/artifacts-querynode-pod-failure-2564-server-logs.tar.gz)
[artifacts-querynode-pod-failure-2564-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9893370/artifacts-querynode-pod-failure-2564-pytest-logs.tar.gz)

and so on
chaos type: pod-failure image tag: master-20221028-977947e2 target pod: minio
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/2567/pipeline

chaos type: pod-failure image tag: master-20221028-977947e2 target pod: etcd
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/2566/pipeline/242

**Comment by zhuwenxing** [comment]
## release timeout 

chaos type: pod-failure image tag: master-20221028-977947e2 target pod: querycoord
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/2563/pipeline/243
log:
[artifacts-querycoord-pod-failure-2563-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9893382/artifacts-querycoord-pod-failure-2563-server-logs.tar.gz)

[artifacts-querycoord-pod-failure-2563-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9893383/artifacts-querycoord-pod-failure-2563-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
Same for the Kafka version

chaos type: pod-kill image tag: master-20221028-977947e2 target pod: etcd
release failed step https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka/detail/chaos-test-kafka/2303/pipeline/244 (collection name: Hello_Milvus ) 
load failed step: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka/detail/chaos-test-kafka/2303/pipeline/243 (collection name: e2e__0K4f8wNK)
log:
[artifacts-etcd-pod-kill-2303-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9893413/artifacts-etcd-pod-kill-2303-server-logs.tar.gz)
[artifacts-etcd-pod-kill-2303-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9893414/artifacts-etcd-pod-kill-2303-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
/assign @yah01 
PTAL

**Comment by zhuwenxing** [comment]
For the pulsar version, this issue was not reproduced. But for the Kafka version, this issue can reproduced for all kinds of pod kill or failure chaos tests.

for some examples

* chaos type: pod-failure image tag: master-latest target pod: querynode
    failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka/detail/chaos-test-kafka/2343/pipeline
    log:
        [artifacts-querynode-pod-failure-2343-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9894993/artifacts-querynode-pod-failure-2343-pytest-logs.tar.gz)
       [artifacts-querynode-pod-failure-2343-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9894995/artifacts-querynode-pod-failure-2343-server-logs.tar.gz)

**Comment by zhuwenxing** [comment]
chaos type: pod-kill image tag: master-latest target pod: etcd
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka/detail/chaos-test-kafka/2342/pipeline
log:
[artifacts-etcd-pod-kill-2342-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9894996/artifacts-etcd-pod-kill-2342-server-logs.tar.gz)

[artifacts-etcd-pod-kill-2342-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9894997/artifacts-etcd-pod-kill-2342-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
For now, this issue is only reproduced in minio pod kill chaos test.

failed job:https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/2623/pipeline
log:
[artifacts-s3-pod-kill-2623-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9897918/artifacts-s3-pod-kill-2623-server-logs.tar.gz)

[artifacts-s3-pod-kill-2623-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9897920/artifacts-s3-pod-kill-2623-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
chaos type: pod-failure image tag: master-20221101-29f2ed67 target pod: querynode
failed job：https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka/detail/chaos-test-kafka/2428/pipeline/245
```
[2022-11-01T22:22:50.653Z] testcases/test_data_persistence.py::TestDataPersistence::test_milvus_default 

[2022-11-01T22:22:50.653Z] -------------------------------- live log setup --------------------------------

[2022-11-01T22:22:50.653Z] [2022-11-01 22:22:50 - INFO - ci_test]: ################################################################################ (conftest.py:189)

[2022-11-01T22:22:50.653Z] [2022-11-01 22:22:50 - INFO - ci_test]: [initialize_milvus] Log cleaned up, start testing... (conftest.py:190)

[2022-11-01T22:22:50.653Z] [2022-11-01 22:22:50 - INFO - ci_test]: [setup_class] Start setup class... (client_base.py:30)

[2022-11-01T22:22:50.653Z] [2022-11-01 22:22:50 - INFO - ci_test]: *********************************** setup *********************************** (client_base.py:36)

[2022-11-01T22:22:50.653Z] [2022-11-01 22:22:50 - INFO - ci_test]: [setup_method] Start setup test case test_milvus_default. (client_base.py:37)

[2022-11-01T22:22:50.908Z] -------------------------------- live log call ---------------------------------

[2022-11-01T22:22:50.908Z] [2022-11-01 22:22:50 - INFO - ci_test]: [test][2022-11-01T22:22:50Z] [0.03207996s] Hello_Milvus flush -> None (wrapper.py:30)

[2022-11-01T22:22:50.908Z] [2022-11-01 22:22:50 - INFO - ci_test]: assert create collection: 0.019901514053344727, init_entities: 6000 (test_data_persistence.py:28)

[2022-11-01T22:22:51.466Z] [2022-11-01 22:22:51 - INFO - ci_test]: [test][2022-11-01T22:22:50Z] [0.37808054s] Hello_Milvus insert -> (insert count: 3000, delete count: 0, upsert count: 0, timestamp: {self._timestamp}, success count: {self.succ_count}, err count: {self.err_count}) (wrapper.py:30)

[2022-11-01T22:22:51.466Z] [2022-11-01 22:22:51 - INFO - ci_test]: assert insert: 0.3783137798309326 (test_data_persistence.py:35)

[2022-11-01T22:22:54.719Z] [2022-11-01 22:22:54 - INFO - ci_test]: [test][2022-11-01T22:22:51Z] [3.05592818s] Hello_Milvus flush -> None (wrapper.py:30)

[2022-11-01T22:22:54.719Z] [2022-11-01 22:22:54 - INFO - ci_test]: [test][2022-11-01T22:22:54Z] [0.00744674s] Hello_Milvus flush -> None (wrapper.py:30)

[2022-11-01T22:22:54.719Z] [2022-11-01 22:22:54 - INFO - ci_test]: [test][2022-11-01T22:22:54Z] [0.00422952s] Hello_Milvus flush -> None (wrapper.py:30)

[2022-11-01T22:22:54.719Z] [2022-11-01 22:22:54 - INFO - ci_test]: assert flush: 3.0658071041107178, entities: 9000 (test_data_persistence.py:45)

[2022-11-01T22:22:54.719Z] [2022-11-01 22:22:54 - INFO - ci_test]: index info: [{'collection': 'Hello_Milvus', 'field': 'float_vector', 'index_name': 'test_5NXnGGuU', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}, {'collection': 'Hello_Milvus', 'field': 'varchar', 'index_name': 'test_ZnNawkrn', 'index_param': {'index_type': 'Trie'}}] (test_data_persistence.py:64)

[2022-11-01T22:22:54.719Z] [2022-11-01 22:22:54 - INFO - ci_test]: [test][2022-11-01T22:22:54Z] [0.00820948s] Hello_Milvus load -> None (wrapper.py:30)

[2022-11-01T22:22:54.719Z] [2022-11-01 22:22:54 - INFO - ci_test]: [test][2022-11-01T22:22:54Z] [0.30309668s] Hello_Milvus search -> <pymilvus.orm.search.SearchResult object at 0x7f4d0bf13040> (wrapper.py:30)

[2022-11-01T22:22:54.719Z] [2022-11-01 22:22:54 - INFO - ci_test]: assert search: 0.30329036712646484 (test_data_persistence.py:76)

[2022-11-01T22:29:01.124Z] [2022-11-01 22:28:54 - ERROR - pymilvus.decorators]: RPC error: [release_collection], <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 360s)>, <Time:{'RPC start': '2022-11-01 22:22:54.662105', 'RPC error': '2022-11-01 22:28:54.663888'}> (decorators.py:108)

[2022-11-01T22:29:01.124Z] [2022-11-01 22:28:54 - ERROR - ci_test]: Traceback (most recent call last):

[2022-11-01T22:29:01.124Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2022-11-01T22:29:01.124Z]     return func(self, *args, **kwargs)

[2022-11-01T22:29:01.124Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 680, in release_collection

[2022-11-01T22:29:01.124Z]     response = rf.result()

[2022-11-01T22:29:01.124Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 744, in result

[2022-11-01T22:29:01.124Z]     raise self

[2022-11-01T22:29:01.124Z] grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:

[2022-11-01T22:29:01.124Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2022-11-01T22:29:01.124Z] 	details = "Deadline Exceeded"

[2022-11-01T22:29:01.124Z] 	debug_error_string = "{"created":"@1667341734.663216226","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":81,"grpc_status":4}"

[2022-11-01T22:29:01.124Z] >

[2022-11-01T22:29:01.124Z] 

[2022-11-01T22:29:01.124Z] The above exception was the direct cause of the following exception:

[2022-11-01T22:29:01.124Z] 

[2022-11-01T22:29:01.124Z] Traceback (most recent call last):

[2022-11-01T22:29:01.124Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2022-11-01T22:29:01.124Z]     res = func(*args, **_kwargs)

[2022-11-01T22:29:01.124Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2022-11-01T22:29:01.124Z]     return func(*arg, **kwargs)

[2022-11-01T22:29:01.124Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 503, in release

[2022-11-01T22:29:01.124Z]     conn.release_collection(self._name, timeout=timeout, **kwargs)

[2022-11-01T22:29:01.124Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2022-11-01T22:29:01.124Z]     raise e

[2022-11-01T22:29:01.124Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2022-11-01T22:29:01.124Z]     return func(*args, **kwargs)

[2022-11-01T22:29:01.124Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2022-11-01T22:29:01.124Z]     ret = func(self, *args, **kwargs)

[2022-11-01T22:29:01.125Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 64, in handler

[2022-11-01T22:29:01.125Z]     raise MilvusException(message=f"rpc deadline exceeded: {timeout_msg}") from e

[2022-11-01T22:29:01.125Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 360s)>

[2022-11-01T22:29:01.125Z]  (api_request.py:39)

[2022-11-01T22:29:01.125Z] [2022-11-01 22:28:54 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 360s)> (api_request.py:40)
```

**Comment by zhuwenxing** [comment]
For now, this issue is not reproduced in the Pulsar version, but it is still reproduced in the Kafka version

**Comment by zhuwenxing** [comment]
chaos type: pod-failure image tag: master-20221102-3ac87fe0 target pod: minio

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka/detail/chaos-test-kafka/2455/pipeline
log:
[artifacts-minio-pod-failure-2455-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9925414/artifacts-minio-pod-failure-2455-pytest-logs.tar.gz)
[artifacts-minio-pod-failure-2455-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9925413/artifacts-minio-pod-failure-2455-server-logs.tar.gz)

**Comment by zhuwenxing** [comment]
For pulsar version, this issue is reproduced when doing datacoord pod failure chaos test

chaos type: pod-failure image tag: master-20221103-f557af11 target pod: datacoord
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/2745/pipeline
log:

[artifacts-datacoord-pod-failure-2745-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9934520/artifacts-datacoord-pod-failure-2745-server-logs.tar.gz)
[artifacts-datacoord-pod-failure-2745-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9934521/artifacts-datacoord-pod-failure-2745-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
chaos type: pod-failure image tag: master-20221103-f557af11 target pod: indexnode
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/2748/pipeline
log:

[artifacts-indexnode-pod-failure-2748-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9934537/artifacts-indexnode-pod-failure-2748-server-logs.tar.gz)
[artifacts-indexnode-pod-failure-2748-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9934538/artifacts-indexnode-pod-failure-2748-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
chaos type: pod-kill image tag: master-20221103-f557af11 target pod: indexcoord
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/2735/pipeline
log:

[artifacts-indexcoord-pod-kill-2735-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9934549/artifacts-indexcoord-pod-kill-2735-server-logs.tar.gz)

[artifacts-indexcoord-pod-kill-2735-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9934551/artifacts-indexcoord-pod-kill-2735-pytest-logs.tar.gz)

**Comment by yah01** [comment]
> chaos type: pod-kill image tag: master-20221103-f557af11 target pod: indexcoord failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/2735/pipeline log:
> 
> [artifacts-indexcoord-pod-kill-2735-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9934549/artifacts-indexcoord-pod-kill-2735-server-logs.tar.gz)
> 
> [artifacts-indexcoord-pod-kill-2735-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9934551/artifacts-indexcoord-pod-kill-2735-pytest-logs.tar.gz)

This load succeeded in 43s, but the timeout is 40s...

**Comment by yah01** [comment]
#20330 waits for #20306

**Comment by zhuwenxing** [comment]
chaos type: pod-kill image tag: master-20221105-4a66965d target pod: etcd
failed job:
https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/2815/pipeline
log:
[artifacts-etcd-pod-kill-2815-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9949116/artifacts-etcd-pod-kill-2815-server-logs.tar.gz)
[artifacts-etcd-pod-kill-2815-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9949117/artifacts-etcd-pod-kill-2815-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
chaos type: pod-kill image tag: 2.2.0-20221109-13dbc090 target pod: datanode
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-for-release/detail/chaos-test-for-release/1702/pipeline/244

log:
[artifacts-datanode-pod-kill-1702-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9978596/artifacts-datanode-pod-kill-1702-server-logs.tar.gz)

[artifacts-datanode-pod-kill-1702-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9978597/artifacts-datanode-pod-kill-1702-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
![image](https://user-images.githubusercontent.com/12268675/201617882-88019283-36fd-4152-84fc-e355e03136d4.png)

chaos type: pod-kill image tag: 2.2.0-20221113-056aebf9 target pod: querycoord
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-for-release/detail/chaos-test-kafka-for-release/1639/pipeline

log:
[artifacts-querycoord-pod-kill-1639-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10001326/artifacts-querycoord-pod-kill-1639-server-logs.tar.gz)
[artifacts-querycoord-pod-kill-1639-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10001328/artifacts-querycoord-pod-kill-1639-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
> ![image](https://user-images.githubusercontent.com/12268675/201617882-88019283-36fd-4152-84fc-e355e03136d4.png)
> 
> chaos type: pod-kill image tag: 2.2.0-20221113-056aebf9 target pod: querycoord failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-for-release/detail/chaos-test-kafka-for-release/1639/pipeline
> 
> log: [artifacts-querycoord-pod-kill-1639-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10001326/artifacts-querycoord-pod-kill-1639-server-logs.tar.gz) [artifacts-querycoord-pod-kill-1639-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10001328/artifacts-querycoord-pod-kill-1639-pytest-logs.tar.gz)

@yah01 
PTAL

**Comment by yah01** [comment]
Many LoadSegment tasks were enqueued, and the release task stucked in the queue for 2min+, which is over the timeout

**Comment by yah01** [comment]
I'm trying to make release unblocking, or we have to wait for QueryNodeV2 solution

**Comment by yah01** [comment]
As [discussion](https://github.com/milvus-io/milvus/pull/20602#issuecomment-1315019338) here, we can't make release unblocking, this issue will be solved at v2.3, with QueryNodeV2

**Comment by zhuwenxing** [comment]
@yanliang567 
What's your opinion?  If it is ok for you, I would like to move to the milestone 2.3

**Comment by yanliang567** [comment]
> @yanliang567 What's your opinion? If it is ok for you, I would like to move to the milestone 2.3

ok

**Comment by zhuwenxing** [comment]
chaos type: pod-kill image tag: 2.2.0-20221118-e7429f88 target pod: datanode
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-for-release/detail/chaos-test-for-release/1988/pipeline
![image](https://user-images.githubusercontent.com/12268675/202950269-079d3f52-c1d2-4d7d-8566-b4c803333e6f.png)
In this step, release timeout.
log:
[artifacts-datanode-pod-kill-1988-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10052110/artifacts-datanode-pod-kill-1988-server-logs.tar.gz)

[artifacts-datanode-pod-kill-1988-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10052126/artifacts-datanode-pod-kill-1988-pytest-logs.tar.gz)

**Comment by yah01** [comment]
/assign @zhuwenxing 
As QueryNodeV2 merged, please help verify this

**Comment by zhuwenxing** [comment]
not reproduced in master-20230417-4a32b842
