### ISSUE TITLE
[Bug]: Create vector field index timeout after minio pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#19952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20221020-e8ca754d
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.2.0.dev57
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2022-10-20T22:46:00.129Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[Checker__a7AmNb8B]

[2022-10-20T22:46:00.129Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[Checker__X4EGMfSi]

[2022-10-20T22:46:00.129Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[Checker__vMPz3J9v]

[2022-10-20T22:46:00.129Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[IndexChecker__2edMgyxQ]

[2022-10-20T22:46:00.129Z] =================== 4 failed, 9 passed in 135.77s (0:02:15) ====================
```

```
2022-10-20T22:46:00.123Z] [2022-10-20 22:43:54 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 20} (api_request.py:56)

[2022-10-20T22:46:00.123Z] [2022-10-20 22:43:54 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)

[2022-10-20T22:46:00.123Z] [2022-10-20 22:43:54 - INFO - ci_test]: [test][2022-10-20T22:43:54Z] [0.00456020s] Checker__a7AmNb8B flush -> None (wrapper.py:30)

[2022-10-20T22:46:00.123Z] [2022-10-20 22:43:54 - INFO - ci_test]: assert flush: 3.5636420249938965, entities: 19800 (test_all_collections_after_chaos.py:52)

[2022-10-20T22:46:00.123Z] [2022-10-20 22:43:54 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['float_vector', {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}], kwargs: {'name': 'test_zlL9a9oY', 'timeout': 40, 'index_name': '_default_idx'} (api_request.py:56)

[2022-10-20T22:46:00.123Z] [2022-10-20 22:44:34 - WARNING - pymilvus.decorators]: Retry timeout: 40s (decorators.py:79)

[2022-10-20T22:46:00.123Z] [2022-10-20 22:44:34 - ERROR - pymilvus.decorators]: RPC error: [wait_for_creating_index], <MilvusException: (code=1, message=Retry timeout: 40s, message=collection Checker__a7AmNb8B create index _default_idx timeout in 40s)>, <Time:{'RPC start': '2022-10-20 22:43:54.171262', 'RPC error': '2022-10-20 22:44:34.421326'}> (decorators.py:108)

[2022-10-20T22:46:00.123Z] [2022-10-20 22:44:34 - WARNING - pymilvus.decorators]: Retry timeout: 40s (decorators.py:79)

[2022-10-20T22:46:00.123Z] [2022-10-20 22:44:34 - ERROR - pymilvus.decorators]: RPC error: [create_index], <MilvusException: (code=1, message=Retry timeout: 40s, message=Retry timeout: 40s, message=collection Checker__a7AmNb8B create index _default_idx timeout in 40s)>, <Time:{'RPC start': '2022-10-20 22:43:54.157333', 'RPC error': '2022-10-20 22:44:34.421509'}> (decorators.py:108)

[2022-10-20T22:46:00.123Z] [2022-10-20 22:44:34 - ERROR - ci_test]: Traceback (most recent call last):

[2022-10-20T22:46:00.123Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 50, in handler

[2022-10-20T22:46:00.123Z]     return func(self, *args, **kwargs)

[2022-10-20T22:46:00.123Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 638, in wait_for_creating_index

[2022-10-20T22:46:00.123Z]     raise MilvusException(message=f"collection {collection_name} create index {index_name} timeout in {timeout}s")

[2022-10-20T22:46:00.123Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection Checker__a7AmNb8B create index _default_idx timeout in 40s)>

[2022-10-20T22:46:00.123Z] 

[2022-10-20T22:46:00.123Z] The above exception was the direct cause of the following exception:

[2022-10-20T22:46:00.123Z] 

[2022-10-20T22:46:00.123Z] Traceback (most recent call last):

[2022-10-20T22:46:00.123Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 50, in handler

[2022-10-20T22:46:00.123Z]     return func(self, *args, **kwargs)

[2022-10-20T22:46:00.123Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 566, in create_index

[2022-10-20T22:46:00.123Z]     timeout=timeout)

[2022-10-20T22:46:00.123Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 109, in handler

[2022-10-20T22:46:00.123Z]     raise e

[2022-10-20T22:46:00.123Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 105, in handler

[2022-10-20T22:46:00.123Z]     return func(*args, **kwargs)

[2022-10-20T22:46:00.123Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 136, in handler

[2022-10-20T22:46:00.123Z]     ret = func(self, *args, **kwargs)

[2022-10-20T22:46:00.123Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 80, in handler

[2022-10-20T22:46:00.123Z]     raise MilvusException(e.code, f"{timeout_msg}, message={e.message}") from e

[2022-10-20T22:46:00.123Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 40s, message=collection Checker__a7AmNb8B create index _default_idx timeout in 40s)>
```

### Expected Behavior

all test cases passed

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/2336/pipeline

log:
[artifacts-s3-pod-kill-2336-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9835334/artifacts-s3-pod-kill-2336-pytest-logs.tar.gz)

[artifacts-s3-pod-kill-2336-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9835335/artifacts-s3-pod-kill-2336-server-logs.tar.gz)

**Comment by xiaocai2333** [comment]
fixed, please verify it.
/assign @zhuwenxing

**Comment by zhuwenxing** [comment]
Not reproduced, close it!
