### ISSUE TITLE
[Bug]: Load or release timeout after querynode pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#19953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20221020-e8ca754d
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.2.0.dev57
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

load timeout 
```
[2022-10-20T22:30:46.957Z] [2022-10-20 22:28:25 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 20} (api_request.py:56)

[2022-10-20T22:30:46.957Z] [2022-10-20 22:28:25 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)

[2022-10-20T22:30:46.957Z] [2022-10-20 22:28:25 - INFO - ci_test]: [test][2022-10-20T22:28:25Z] [0.00463671s] FlushChecker__jrPYAq7a flush -> None (wrapper.py:30)

[2022-10-20T22:30:46.957Z] [2022-10-20 22:28:25 - INFO - ci_test]: assert flush: 3.55131196975708, entities: 7770 (test_all_collections_after_chaos.py:52)

[2022-10-20T22:30:46.957Z] [2022-10-20 22:28:25 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['float_vector', {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}], kwargs: {'name': 'test_HH2XhDMa', 'timeout': 40, 'index_name': '_default_idx'} (api_request.py:56)

[2022-10-20T22:30:46.957Z] [2022-10-20 22:28:34 - DEBUG - ci_test]: (api_response) : Status(code=0, message=)  (api_request.py:31)

[2022-10-20T22:30:46.957Z] [2022-10-20 22:28:34 - INFO - ci_test]: [test][2022-10-20T22:28:25Z] [9.28648382s] FlushChecker__jrPYAq7a create_index -> Status(code=0, message=) (wrapper.py:30)

[2022-10-20T22:30:46.957Z] [2022-10-20 22:28:34 - INFO - ci_test]: assert index: 9.286714315414429 (test_all_collections_after_chaos.py:61)

[2022-10-20T22:30:46.957Z] [2022-10-20 22:28:34 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 20], kwargs: {} (api_request.py:56)

[2022-10-20T22:30:46.957Z] [2022-10-20 22:28:55 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=wait for loading collection timeout, collection: FlushChecker__jrPYAq7a)>, <Time:{'RPC start': '2022-10-20 22:28:35.044841', 'RPC error': '2022-10-20 22:28:55.210013'}> (decorators.py:108)

[2022-10-20T22:30:46.957Z] [2022-10-20 22:28:55 - WARNING - pymilvus.decorators]: Retry timeout: 20s (decorators.py:79)

[2022-10-20T22:30:46.957Z] [2022-10-20 22:28:55 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry timeout: 20s, message=wait for loading collection timeout, collection: FlushChecker__jrPYAq7a)>, <Time:{'RPC start': '2022-10-20 22:28:34.805577', 'RPC error': '2022-10-20 22:28:55.210438'}> (decorators.py:108)

[2022-10-20T22:30:46.957Z] [2022-10-20 22:28:55 - ERROR - ci_test]: Traceback (most recent call last):

[2022-10-20T22:30:46.957Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 50, in handler

[2022-10-20T22:30:46.957Z]     return func(self, *args, **kwargs)

[2022-10-20T22:30:46.957Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 650, in load_collection

[2022-10-20T22:30:46.957Z]     self.wait_for_loading_collection(collection_name, timeout)

[2022-10-20T22:30:46.957Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 109, in handler

[2022-10-20T22:30:46.957Z]     raise e

[2022-10-20T22:30:46.957Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 105, in handler

[2022-10-20T22:30:46.957Z]     return func(*args, **kwargs)

[2022-10-20T22:30:46.957Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 136, in handler

[2022-10-20T22:30:46.957Z]     ret = func(self, *args, **kwargs)

[2022-10-20T22:30:46.957Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 85, in handler

[2022-10-20T22:30:46.957Z]     raise e

[2022-10-20T22:30:46.957Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 50, in handler

[2022-10-20T22:30:46.957Z]     return func(self, *args, **kwargs)

[2022-10-20T22:30:46.957Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 672, in wait_for_loading_collection

[2022-10-20T22:30:46.957Z]     raise MilvusException(message=f"wait for loading collection timeout, collection: {collection_name}")

[2022-10-20T22:30:46.957Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=wait for loading collection timeout, collection: FlushChecker__jrPYAq7a)>

[2022-10-20T22:30:46.957Z] 

[2022-10-20T22:30:46.957Z] The above exception was the direct cause of the following exception:

[2022-10-20T22:30:46.957Z] 

[2022-10-20T22:30:46.957Z] Traceback (most recent call last):

[2022-10-20T22:30:46.957Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2022-10-20T22:30:46.957Z]     res = func(*args, **_kwargs)

[2022-10-20T22:30:46.957Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2022-10-20T22:30:46.957Z]     return func(*arg, **kwargs)

[2022-10-20T22:30:46.957Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 476, in load

[2022-10-20T22:30:46.957Z]     conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)

[2022-10-20T22:30:46.957Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 109, in handler

[2022-10-20T22:30:46.957Z]     raise e

[2022-10-20T22:30:46.957Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 105, in handler

[2022-10-20T22:30:46.957Z]     return func(*args, **kwargs)

[2022-10-20T22:30:46.957Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 136, in handler

[2022-10-20T22:30:46.957Z]     ret = func(self, *args, **kwargs)

[2022-10-20T22:30:46.957Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 80, in handler

[2022-10-20T22:30:46.957Z]     raise MilvusException(e.code, f"{timeout_msg}, message={e.message}") from e

[2022-10-20T22:30:46.957Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 20s, message=wait for loading collection timeout, collection: FlushChecker__jrPYAq7a)>

[2022-10-20T22:30:46.957Z]  (api_request.py:39)

[2022-10-20T22:30:46.957Z] [2022-10-20 22:28:55 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 20s, message=wait for loading collection timeout, collection: FlushChecker__jrPYAq7a)> (api_request.py:40)
```

release timeout
```
[2022-10-20T22:30:46.959Z] [2022-10-20 22:28:33 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 20], kwargs: {} (api_request.py:56)

[2022-10-20T22:30:46.959Z] [2022-10-20 22:28:37 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)

[2022-10-20T22:30:46.959Z] [2022-10-20 22:28:37 - INFO - ci_test]: [test][2022-10-20T22:28:33Z] [4.26465630s] CreateChecker__MZ19lXH7 load -> None (wrapper.py:30)

[2022-10-20T22:30:46.959Z] [2022-10-20 22:28:37 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.124856444438301, 0.11186685256711554, 0.07078054123302893, 0.09398171871893292, 0.15126377690638118, 0.10732389401581163, 0.012911777151489303, 0.09819781341469262, 0.10060194558334722, 0.06466272327561635, 0.06082546562638558, 0.08913108905896831, 0.12769877799519283, 0.13798521507922806, 0.05......, kwargs: {} (api_request.py:56)

[2022-10-20T22:30:46.959Z] [2022-10-20 22:28:38 - DEBUG - ci_test]: (api_response) : ["['(distance: 0.2931663990020752, id: 324)']"]  (api_request.py:31)

[2022-10-20T22:30:46.959Z] [2022-10-20 22:28:38 - INFO - ci_test]: [test][2022-10-20T22:28:37Z] [0.49273321s] CreateChecker__MZ19lXH7 search -> <pymilvus.orm.search.SearchResult object at 0x7f5e458fe630> (wrapper.py:30)

[2022-10-20T22:30:46.959Z] [2022-10-20 22:28:38 - INFO - ci_test]: assert search: 0.49294567108154297 (test_all_collections_after_chaos.py:70)

[2022-10-20T22:30:46.959Z] [2022-10-20 22:28:38 - DEBUG - ci_test]: (api_request)  : [Collection.release] args: [], kwargs: {'timeout': 20} (api_request.py:56)

[2022-10-20T22:30:46.959Z] [2022-10-20 22:28:58 - ERROR - pymilvus.decorators]: RPC error: [release_collection], <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)>, <Time:{'RPC start': '2022-10-20 22:28:38.004640', 'RPC error': '2022-10-20 22:28:58.005180'}> (decorators.py:108)

[2022-10-20T22:30:46.959Z] [2022-10-20 22:28:58 - ERROR - ci_test]: Traceback (most recent call last):

[2022-10-20T22:30:46.959Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 50, in handler

[2022-10-20T22:30:46.959Z]     return func(self, *args, **kwargs)

[2022-10-20T22:30:46.959Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 679, in release_collection

[2022-10-20T22:30:46.959Z]     response = rf.result()

[2022-10-20T22:30:46.959Z]   File "/usr/local/lib/python3.7/dist-packages/grpc/_channel.py", line 744, in result

[2022-10-20T22:30:46.959Z]     raise self

[2022-10-20T22:30:46.959Z] grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:

[2022-10-20T22:30:46.959Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2022-10-20T22:30:46.959Z] 	details = "Deadline Exceeded"

[2022-10-20T22:30:46.959Z] 	debug_error_string = "{"created":"@1666304938.004857857","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":81,"grpc_status":4}"

[2022-10-20T22:30:46.959Z] >

[2022-10-20T22:30:46.959Z] 

[2022-10-20T22:30:46.959Z] The above exception was the direct cause of the following exception:

[2022-10-20T22:30:46.959Z] 

[2022-10-20T22:30:46.959Z] Traceback (most recent call last):

[2022-10-20T22:30:46.959Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2022-10-20T22:30:46.959Z]     res = func(*args, **_kwargs)

[2022-10-20T22:30:46.959Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2022-10-20T22:30:46.959Z]     return func(*arg, **kwargs)

[2022-10-20T22:30:46.959Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 503, in release

[2022-10-20T22:30:46.959Z]     conn.release_collection(self._name, timeout=timeout, **kwargs)

[2022-10-20T22:30:46.959Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 109, in handler

[2022-10-20T22:30:46.959Z]     raise e

[2022-10-20T22:30:46.959Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 105, in handler

[2022-10-20T22:30:46.959Z]     return func(*args, **kwargs)

[2022-10-20T22:30:46.959Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 136, in handler

[2022-10-20T22:30:46.959Z]     ret = func(self, *args, **kwargs)

[2022-10-20T22:30:46.959Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 64, in handler

[2022-10-20T22:30:46.959Z]     raise MilvusException(message=f"rpc deadline exceeded: {timeout_msg}") from e

[2022-10-20T22:30:46.959Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)>

[2022-10-20T22:30:46.959Z]  (api_request.py:39)

[2022-10-20T22:30:46.959Z] [2022-10-20 22:28:58 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)> (api_request.py:40)
```

### Expected Behavior

all test case passed

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/2333/pipeline

log:

[artifacts-querynode-pod-kill-2333-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9835362/artifacts-querynode-pod-kill-2333-server-logs.tar.gz)

[artifacts-querynode-pod-kill-2333-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9835363/artifacts-querynode-pod-kill-2333-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
When the timeout is 120s, this issue still happens.
failed job:https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/2570/pipeline
log:

[artifacts-querynode-pod-failure-2570-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9893535/artifacts-querynode-pod-failure-2570-server-logs.tar.gz)
[artifacts-querynode-pod-failure-2570-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9893537/artifacts-querynode-pod-failure-2570-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
Not reproduced, so remove critical label
