### ISSUE TITLE
[Bug]: [benchmark][cluster]Milvus load fails after several retries,raise an error"collection  has not been loaded to memory or load failed"

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#20002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20221023-08cfc140
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0.dev45
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server-instance
fouram-concurrent-1666540800-1
server-configmap
server-single-4c16m-diskann
client-configmap
client-locust-search-sift10m-diskann

```
fouram-concurrent-1666540800-1-etcd-0                             1/1     Running                  0               23m     10.104.4.42    4am-node11   <none>           <none>
fouram-concurrent-1666540800-1-milvus-standalone-78bd44d55qzcj8   1/1     Running                  0               23m     10.104.9.119   4am-node14   <none>           <none>
fouram-concurrent-1666540800-1-minio-79fff7ddd9-fxrcs             1/1     Running                  0               23m     10.104.9.95    4am-node14   <none>           <none>
```

```
[2022-10-23 17:31:06,394] [    INFO] - Start load collection (milvus_benchmark.runners.locust:459)
[2022-10-23 17:31:09,067] [ WARNING] - [93m[get_loading_progress] retry:4, cost: 0.27s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:72)
[2022-10-23 17:31:09,338] [ WARNING] - [93m[get_loading_progress] retry:5, cost: 0.81s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:72)
[2022-10-23 17:31:10,150] [ WARNING] - [93m[get_loading_progress] retry:6, cost: 2.43s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:72)
[2022-10-23 17:31:12,581] [ WARNING] - [93m[get_loading_progress] retry:7, cost: 7.290000000000001s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:72)
[2022-10-23 17:31:19,872] [ WARNING] - [93m[get_loading_progress] retry:8, cost: 21.870000000000005s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:72)
[2022-10-23 17:31:41,744] [ WARNING] - [93m[get_loading_progress] retry:9, cost: 60s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:72)
[2022-10-23 17:32:41,745] [ WARNING] - [93m[get_loading_progress] retry:10, cost: 60s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:72)
[2022-10-23 17:33:41,762] [ WARNING] - [93mRetry run out of 10 retry times[0m (pymilvus.decorators:80)
[2022-10-23 17:33:41,762] [   ERROR] - RPC error: [get_loading_progress], <MilvusException: (code=1, message=Retry run out of 10 retry times, message=collection 436874020902404101 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-10-23 17:31:08.934316', 'RPC error': '2022-10-23 17:33:41.762644'}> (pymilvus.decorators:112)
[2022-10-23 17:33:41,762] [   ERROR] - RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=Retry run out of 10 retry times, message=collection 436874020902404101 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-10-23 17:31:06.402600', 'RPC error': '2022-10-23 17:33:41.762768'}> (pymilvus.decorators:112)
[2022-10-23 17:33:41,762] [   ERROR] - RPC error: [load_collection], <MilvusException: (code=1, message=Retry run out of 10 retry times, message=collection 436874020902404101 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-10-23 17:31:06.394902', 'RPC error': '2022-10-23 17:33:41.762844'}> (pymilvus.decorators:112)
[2022-10-23 17:33:41,762] [   ERROR] - <MilvusException: (code=1, message=Retry run out of 10 retry times, message=collection 436874020902404101 has not been loaded to memory or load failed)> (milvus_benchmark.main:118)
[2022-10-23 17:33:41,764] [   ERROR] - Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 744, in get_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection 436874020902404101 has not been loaded to memory or load failed)>
```

### Steps To Reproduce

```markdown
1.create an collection\
2.build diskann index
3.insert 10m data
4. build index again
5. load failed
```

### Anything else?

```
data:
  config.yaml: |
    locust_random_performance:
      collections:
        -
          collection_name: sift_10m_128_l2
          ni_per: 50000
          build_index: true
          index_type: diskann
          index_param: {}
          task:
            types:
              -
                type: query
                weight: 10
                params:
                  top_k: 10
                  nq: 10
                  search_param:
                    search_list: 30
              -
                type: load
                weight: 1
              -
                type: get
                weight: 2
                params:
                  ids_length: 10  
            connection_num: 1
            clients_num: 20
            spawn_rate: 2
            during_time: 1h
```

**Comment by bigsheeper** [comment]
/assign
working on it

**Comment by bigsheeper** [comment]
https://grafana-4am.zilliz.cc/explore?orgId=1&left=%5B%221666546230000%22,%221666546350000%22,%22Loki%22,%7B%22refId%22:%22A%22,%22expr%22:%22%7Bpod%3D%5C%22fouram-concurrent-1666540800-1-milvus-standalone-78bd44d55qzcj8%5C%22%7D%20%7C%3D%20%5C%22github.com%2Fmilvus-io%2Fmilvus%2Finternal%5C%22%22%7D%5D

**Comment by jingkl** [comment]
server-instance
fouram-stable-1666803600-1
server-configmap
server-single-4c16m-diskann
client-configmap
client-locust-search-sift10m-diskann

master-20221026-b213297d

server:
```
NOMINATED NODE   READINESS GATES
fouram-stable-1666803600-1-etcd-0                                 1/1     Running     0               114s    10.104.4.39    4am-nod
e11   <none>           <none>
fouram-stable-1666803600-1-milvus-standalone-6f6f4746df-p4zvg     1/1     Running     0               115s    10.104.9.178   4am-nod
e14   <none>           <none>
fouram-stable-1666803600-1-minio-864dc5446d-2k59m                 1/1     Running     0               115s    10.104.4.30    4am-nod
e11   <none>           <none>
```
client log:

```
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 669, in wait_for_loading_collection
    progress = self.get_loading_progress(collection_name, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 80, in handler
    raise MilvusException(e.code, f"{timeout_msg}, message={e.message}") from e
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry run out of 10 retry times, message=collection 43694259
7473435652 has not been loaded to memory or load failed)>
```

**Comment by bigsheeper** [comment]
crash at `ws::Config::GetCachedConfigValue`：

![image](https://user-images.githubusercontent.com/42060877/198955597-c2ca6b5f-8cfe-45ba-bf3a-bbd78b36580d.png)

`GetCachedConfigValue` before `Aws::InitAPI`
#20200 would fix it.

**Comment by bigsheeper** [comment]
/assign @jingkl 
/unassign
please help to verify, thanks

**Comment by jingkl** [comment]
server-instance
fouram-stable-1667322000-1
server-configmap
server-single-4c16m-diskann
client-configmap
client-locust-search-sift10m-diskann

master-20221101-29f2ed67
2.2.0.dev70
This issue does not currently occur
