### ISSUE TITLE
[Bug]: Load raise error ` pymilvus.exceptions.MilvusException: <MilvusException: (code=5, message=failed to load collection, err=collection with different index map[103:436885001246019009] existed, release this collection first before changing its index[LoadParameterMismatched])>` 

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#20026]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20221024-eaae3aa4
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
2022-10-24 12:13:06 - INFO - ci_test]: *********************************** setup *********************************** (client_base.py:36)
[2022-10-24 12:13:06 - INFO - ci_test]: [setup_method] Start setup test case test_check. (client_base.py:37)
---------------------------------------------------------------------- Captured log call ----------------------------------------------------------------------
[2022-10-24 12:13:06 - DEBUG - ci_test]: (api_request)  : [Connections.connect] args: ['default'], kwargs: {'host': '10.101.162.138', 'port': 19530} (api_request.py:56)
[2022-10-24 12:13:06 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)
[2022-10-24 12:13:06 - DEBUG - ci_test]: (api_request)  : [Collection] args: ['deploy_test_index_type_HNSW_is_compacted_not_compacted_segment_status_only_growing_is_string_indexed_is_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000', None, 'default', 2], kwargs: {'consistency_level': 'Strong'} (api_request.py:56)
[2022-10-24 12:13:06 - DEBUG - ci_test]: (api_response) : <Collection>:
-------------
<name>: deploy_test_index_type_HNSW_is_compacted_not_compacted_segment_status_only_growing_is_string_indexed_is_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000
<partitions>: [{"name": "_default", "collection_name": "deploy_test_index_type_HNSW_is_comp......  (api_request.py:31)
[2022-10-24 12:13:06 - INFO - ci_test]: get replicas failed (test_action_second_deployment.py:96)
[2022-10-24 12:13:06 - INFO - ci_test]: [{'collection': 'deploy_test_index_type_HNSW_is_compacted_not_compacted_segment_status_only_growing_is_string_indexed_is_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000', 'field': 'float_vector', 'index_name': '_default_idx', 'index_param': {'index_type': 'HNSW', 'params': {'M': 48, 'efConstruction': 500}, 'metric_type': 'L2'}}] (test_action_second_deployment.py:47)
[2022-10-24 12:13:06 - INFO - ci_test]: current index param is {'index_type': 'HNSW', 'params': {'M': 48, 'efConstruction': 500}, 'metric_type': 'L2'}, passed in param is {'index_type': 'HNSW', 'params': {'M': 48, 'efConstruction': 500}, 'metric_type': 'L2'} (test_action_second_deployment.py:50)
[2022-10-24 12:13:06 - INFO - ci_test]: current index name is _default_idx, passed in param is _default_idx (test_action_second_deployment.py:52)
[2022-10-24 12:13:08 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=5, message=failed to load collection, err=collection with different index map[103:436885001246019009] existed, release this collection first before changing its index[LoadParameterMismatched])>, <Time:{'RPC start': '2022-10-24 12:13:08.972775', 'RPC error': '2022-10-24 12:13:08.994021'}> (decorators.py:111)

```

### Expected Behavior

all test cases passed

### Steps To Reproduce

```markdown
1. deploy cluster Milvus with image `master-20221024-eaae3aa4`
2. run the script https://github.com/zhuwenxing/milvus/blob/master-dev/tests/python_client/deploy/testcases/test_action_first_deployment.py
3. run the script https://github.com/zhuwenxing/milvus/blob/master-dev/tests/python_client/deploy/testcases/test_get_all_collections.py
4. run the script https://github.com/zhuwenxing/milvus/blob/master-dev/tests/python_client/deploy/testcases/test_action_second_deployment.py

This issue happened in step 4
```

### Milvus Log

[test-reinstall-test-10-24-15-49.zip](https://github.com/milvus-io/milvus/files/9849779/test-reinstall-test-10-24-15-49.zip)

### Anything else?

```
Results (368.48s):
      55 passed
      13 failed
         - deploy/testcases/test_action_second_deployment.py:59 TestActionSecondDeployment.test_check[deploy_test_index_type_HNSW_is_compacted_not_compacted_segment_status_only_growing_is_string_indexed_not_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000]
         - deploy/testcases/test_action_second_deployment.py:59 TestActionSecondDeployment.test_check[deploy_test_index_type_HNSW_is_compacted_is_compacted_segment_status_only_growing_is_string_indexed_is_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000]
         - deploy/testcases/test_action_second_deployment.py:59 TestActionSecondDeployment.test_check[deploy_test_index_type_BIN_IVF_FLAT_is_compacted_is_compacted_segment_status_only_growing_is_string_indexed_is_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000]
         - deploy/testcases/test_action_second_deployment.py:59 TestActionSecondDeployment.test_check[deploy_test_index_type_BIN_IVF_FLAT_is_compacted_is_compacted_segment_status_only_growing_is_string_indexed_not_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000]
         - deploy/testcases/test_action_second_deployment.py:59 TestActionSecondDeployment.test_check[deploy_test_index_type_BIN_IVF_FLAT_is_compacted_not_compacted_segment_status_only_growing_is_string_indexed_not_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000]
         - deploy/testcases/test_action_second_deployment.py:59 TestActionSecondDeployment.test_check[deploy_test_index_type_HNSW_is_compacted_is_compacted_segment_status_only_growing_is_string_indexed_not_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000]
         - deploy/testcases/test_action_second_deployment.py:59 TestActionSecondDeployment.test_check[deploy_test_index_type_HNSW_empty]
         - deploy/testcases/test_action_second_deployment.py:59 TestActionSecondDeployment.test_check[deploy_test_index_type_HNSW_is_compacted_not_compacted_segment_status_only_growing_is_string_indexed_is_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000]
         - deploy/testcases/test_action_second_deployment.py:59 TestActionSecondDeployment.test_check[deploy_test_index_type_BIN_IVF_FLAT_is_compacted_not_compacted_segment_status_all_is_string_indexed_not_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000]
         - deploy/testcases/test_action_second_deployment.py:59 TestActionSecondDeployment.test_check[deploy_test_index_type_HNSW_is_compacted_is_compacted_segment_status_all_is_string_indexed_not_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000]
         - deploy/testcases/test_action_second_deployment.py:59 TestActionSecondDeployment.test_check[deploy_test_index_type_BIN_IVF_FLAT_is_compacted_not_compacted_segment_status_only_growing_is_string_indexed_is_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000]
         - deploy/testcases/test_action_second_deployment.py:59 TestActionSecondDeployment.test_check[deploy_test_index_type_BIN_IVF_FLAT_is_compacted_is_compacted_segment_status_all_is_string_indexed_not_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000]
         - deploy/testcases/test_action_second_deployment.py:59 TestActionSecondDeployment.test_check[deploy_test_index_type_HNSW_is_compacted_not_compacted_segment_status_all_is_string_indexed_not_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000]
```

all test cases failed with this issue

**Comment by zhuwenxing** [comment]
some related issues and I found that the error message below is `different index map[]`, but in my case is `index map[103:436885001246019009`. 
* https://github.com/milvus-io/milvus/issues/19960
* https://github.com/milvus-io/milvus/issues/19962

**Comment by yah01** [comment]
> /assign @yah01 maybe #19986 fix it?

look related, plz retry with #19986
/assign @zhuwenxing

**Comment by zhuwenxing** [comment]
This issue still reproduced when upgrading from 2.1.4 to master-20221025-290b902a

failed job:
https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test/detail/deploy_test/489/pipeline
log:
[artifacts-standalone-upgrade-489-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9858420/artifacts-standalone-upgrade-489-server-logs.tar.gz)

[artifacts-standalone-upgrade-489-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9858423/artifacts-standalone-upgrade-489-pytest-logs.tar.gz)


```

[2022-10-25T07:04:08.841Z] collection name: task_1_IVF_SQ8

[2022-10-25T07:04:08.841Z] load collection

[2022-10-25T07:04:08.841Z] Traceback (most recent call last):

[2022-10-25T07:04:08.841Z]   File "scripts/action_after_upgrade.py", line 100, in <module>

[2022-10-25T07:04:08.841Z]     task_1(data_size, host)

[2022-10-25T07:04:08.841Z]   File "scripts/action_after_upgrade.py", line 20, in task_1

[2022-10-25T07:04:08.841Z]     load_and_search(prefix)

[2022-10-25T07:04:08.841Z]   File "/home/jenkins/agent/workspace/tests/python_client/deploy/scripts/utils.py", line 148, in load_and_search

[2022-10-25T07:04:08.841Z]     c.load()

[2022-10-25T07:04:08.841Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 476, in load

[2022-10-25T07:04:08.841Z]     conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)

[2022-10-25T07:04:08.841Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 109, in handler

[2022-10-25T07:04:08.841Z]     raise e

[2022-10-25T07:04:08.841Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 105, in handler

[2022-10-25T07:04:08.841Z]     return func(*args, **kwargs)

[2022-10-25T07:04:08.841Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 136, in handler

[2022-10-25T07:04:08.841Z]     ret = func(self, *args, **kwargs)

[2022-10-25T07:04:08.841Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 85, in handler

[2022-10-25T07:04:08.841Z]     raise e

[2022-10-25T07:04:08.841Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 50, in handler

[2022-10-25T07:04:08.841Z]     return func(self, *args, **kwargs)

[2022-10-25T07:04:08.841Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 648, in load_collection

[2022-10-25T07:04:08.841Z]     raise MilvusException(response.error_code, response.reason)

[2022-10-25T07:04:08.841Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=5, message=failed to load collection, err=collection with different index map[] existed, release this collection first before changing its index[LoadParameterMismatched])>
```

**Comment by yah01** [comment]
/assign @zhuwenxing 
plz retry with #20064 , a corner case handled within the migration tool

**Comment by zhuwenxing** [comment]
It still reproduced 
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test/detail/deploy_test/503/pipeline
log:
[artifacts-standalone-upgrade-503-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9866366/artifacts-standalone-upgrade-503-server-logs.tar.gz)
[artifacts-standalone-upgrade-503-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9866368/artifacts-standalone-upgrade-503-pytest-logs.tar.gz)

**Comment by yah01** [comment]
/assign @xiaocai2333 
it looks like an issue of IndexCoord, the flat index is not migrated properly, please help check

**Comment by xiaocai2333** [comment]
working on it~

**Comment by xiaocai2333** [comment]
@zhuwenxing 
please verify 
/assign @zhuwenxing

**Comment by zhuwenxing** [comment]
Not reproduced

**Comment by Nwe2310** [comment]
have to release first at the milvis UI (attu). 
<img width="833" alt="image" src="https://github.com/milvus-io/milvus/assets/153502895/cfaf250c-00de-46b3-ad7c-8077dce5b767">
