### ISSUE TITLE
[Bug]: [Nightly]Query failed reporting 'fail to search on all shard leaders, err=fail to Query, QueryNode ID = 2, reason=Query 2 failed, reason failed to get service timestamp, taskID = 436898317007323137, collectionID = 436898227082374911, err=cannot found tSafer, vChannel = by-dev-rootcoord-delta_77_436898227082374911v0 err %!w(<nil>))'

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#20040]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2f19e65
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.0.0.dev63
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Query failed reporting 'fail to search on all shard leaders, err=fail to Query, QueryNode ID = 2, reason=Query 2 failed, reason failed to get service timestamp, taskID = 436898317007323137, collectionID = 436898227082374911, err=cannot found tSafer, vChannel = by-dev-rootcoord-delta_77_436898227082374911v0 err %!w(<nil>))'
```
[2022-10-24T19:54:22.899Z] [2022-10-24 18:06:55 - ERROR - pymilvus.decorators]: RPC error: [query], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Query, QueryNode ID = 2, reason=Query 2 failed, reason failed to get service timestamp, taskID = 436898317007323137, collectionID = 436898227082374911, err=cannot found tSafer, vChannel = by-dev-rootcoord-delta_77_436898227082374911v0 err %!w(<nil>))>, <Time:{'RPC start': '2022-10-24 18:06:55.262215', 'RPC error': '2022-10-24 18:06:55.635072'}> (decorators.py:108)
[2022-10-24T19:54:22.899Z] [2022-10-24 18:06:55 - ERROR - ci_test]: Traceback (most recent call last):
[2022-10-24T19:54:22.899Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2022-10-24T19:54:22.899Z]     res = func(*args, **_kwargs)
[2022-10-24T19:54:22.899Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2022-10-24T19:54:22.899Z]     return func(*arg, **kwargs)
[2022-10-24T19:54:22.899Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 807, in query
[2022-10-24T19:54:22.899Z]     res = conn.query(self._name, expr, output_fields, partition_names, timeout=timeout, schema=schema, **kwargs)
[2022-10-24T19:54:22.899Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2022-10-24T19:54:22.899Z]     raise e
[2022-10-24T19:54:22.899Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2022-10-24T19:54:22.899Z]     return func(*args, **kwargs)
[2022-10-24T19:54:22.899Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2022-10-24T19:54:22.899Z]     ret = func(self, *args, **kwargs)
[2022-10-24T19:54:22.899Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
[2022-10-24T19:54:22.899Z]     raise e
[2022-10-24T19:54:22.899Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2022-10-24T19:54:22.899Z]     return func(self, *args, **kwargs)
[2022-10-24T19:54:22.900Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 876, in query
[2022-10-24T19:54:22.900Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2022-10-24T19:54:22.900Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Query, QueryNode ID = 2, reason=Query 2 failed, reason failed to get service timestamp, taskID = 436898317007323137, collectionID = 436898227082374911, err=cannot found tSafer, vChannel = by-dev-rootcoord-delta_77_436898227082374911v0 err %!w(<nil>))>
[2022-10-24T19:54:22.900Z]  (api_request.py:39)
[2022-10-24T19:54:22.900Z] [2022-10-24 18:06:55 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Query, QueryNode ID = 2, reason=Query 2 failed, reason failed to get service timestamp, taskID = 436898317007323137, collectionID = 436898227082374911, err=cannot found tSafer, vChannel = by-dev-rootcoord-delta_77_43...... (api_request.py:40)
```

### Expected Behavior

PASSED

### Steps To Reproduce

```markdown
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/172/pipeline/187
```

### Milvus Log

1. log: [artifacts-milvus-distributed-pulsar-nightly-172-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/172/artifact/artifacts-milvus-distributed-pulsar-nightly-172-pymilvus-e2e-logs.tar.gz)
2. collection name: collection_stcKrDtg
3. failed time: [2022-10-24T18:06:56.310Z] [gw1] [ 10%] FAILED testcases/test_collection.py::TestLoadCollection::test_load_replica_partitions

**Comment by NicoYuan1986** [comment]
The issue has disappeared for some time. Close it first. milvus:f557af1
