### ISSUE TITLE
[Bug]: Collection is not loaded after upgrade when the collection has been loaded before upgrade

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#20047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.1.4 --> master-20221024-2f19e659
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus==2.1.3 --> pymilvus==2.2.0.dev63
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
+ python3 scripts/second_recall_test.py --host 10.101.179.4
 RPC error: [search], <MilvusException: (code=1, message=checkIfLoaded failed when search, collection:sift_128_euclidean, partitions:[], err = GetCollectionInfo failed, collection = sift_128_euclidean, err = collection 436905762688073729 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-10-25 02:11:51.403721', 'RPC error': '2022-10-25 02:11:51.561368'}>
 
 Search...
 Traceback (most recent call last):
   File "scripts/second_recall_test.py", line 64, in <module>
     search_test(host)
   File "scripts/second_recall_test.py", line 34, in search_test
     test[:nq], "float_vector", search_params, topK, output_fields=["int64"], timeout=TIMEOUT
   File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 720, in search
     partition_names, output_fields, round_decimal, timeout=timeout, schema=schema_dict, **kwargs)
   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 109, in handler
     raise e
   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 105, in handler
     return func(*args, **kwargs)
   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 136, in handler
     ret = func(self, *args, **kwargs)
   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 85, in handler
     raise e
   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 50, in handler
     return func(self, *args, **kwargs)
   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 476, in search
     return self._execute_search_requests(requests, timeout, **_kwargs)
   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 440, in _execute_search_requests
     raise pre_err
   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 431, in _execute_search_requests
     raise MilvusException(response.status.error_code, response.status.reason)
 pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=checkIfLoaded failed when search, collection:sift_128_euclidean, partitions:[], err = GetCollectionInfo failed, collection = sift_128_euclidean, err = collection 436905762688073729 has not been loaded to memory or load failed)>
```

### Expected Behavior

The collection should be at loaded status, and can be searched directly

### Steps To Reproduce

```markdown
1. deploy 2.1.4
2. create collection, insert data, create index, load, and search
3. update to the master
4. search
```

### Milvus Log
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test/detail/deploy_test/484/pipeline

[artifacts-standalone-upgrade-484-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9856855/artifacts-standalone-upgrade-484-server-logs.tar.gz)

**Comment by longjiquan** [comment]
Sorry, but we should upgrade the meta migration tool. @zhuwenxing

**Comment by zhuwenxing** [comment]
after using meta migration version `20221025-7a13b1c32`, it works well
