### ISSUE TITLE
[Bug]: [Bug]: [benchmark][standalone] Load collection raise error: collection 436896709038047235 has not been loaded to memory or load failed

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#20057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20221024-2f19e659
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0.dev45
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task: fouramf-cron-1666627200
test case: test_search_standalone

client log:

[test_search_standalone_1.zip](https://github.com/milvus-io/milvus/files/9857691/test_search_standalone_1.zip)

```
[2022-10-24 17:02:11,588 -  INFO - fouram]: [Base] Start inserting, ids: 49900000 - 49949999, data size: 50,000,000 (base.py:116)
[2022-10-24 17:02:12,880 -  INFO - fouram]: [Time] Collection.insert run in 1.2918s (api_request.py:29)
[2022-10-24 17:02:12,882 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_dXkcIRdI): 49900000 (base.py:244)
[2022-10-24 17:02:13,095 -  INFO - fouram]: [Base] Start inserting, ids: 49950000 - 49999999, data size: 50,000,000 (base.py:116)
[2022-10-24 17:02:14,595 -  INFO - fouram]: [Time] Collection.insert run in 1.499s (api_request.py:29)
[2022-10-24 17:02:14,597 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_dXkcIRdI): 49900000 (base.py:244)
[2022-10-24 17:02:14,662 -  INFO - fouram]: [Base] Total time of insert: 1376.2218s, average number of vector bars inserted per second: 36331.353, average time to insert 50000 vectors per time: 1.3762s (base.py:175)
[2022-10-24 17:02:14,663 -  INFO - fouram]: [Base] Start flush collection fouram_dXkcIRdI (base.py:93)
[2022-10-24 17:02:17,216 -  INFO - fouram]: [Base] Params of index: {'index_type': 'IVF_FLAT', 'metric_type': 'L2', 'params': {'nlist': 2048}} (base.py:228)
[2022-10-24 17:02:17,216 -  INFO - fouram]: [Base] Start build index of IVF_FLAT, params:{'index_type': 'IVF_FLAT', 'metric_type': 'L2', 'params': {'nlist': 2048}} (base.py:218)
[2022-10-24 17:02:17,244 -  INFO - fouram]: [Time] Index run in 0.0278s (api_request.py:29)
[2022-10-24 17:02:17,244 -  INFO - fouram]: [CommonCases] RT of build index IVF_FLAT: 0.0278s (common_cases.py:83)
[2022-10-24 17:02:17,282 -  INFO - fouram]: [Base] Params of index: {'index_type': 'IVF_FLAT', 'metric_type': 'L2', 'params': {'nlist': 2048}} (base.py:228)
[2022-10-24 17:02:17,282 -  INFO - fouram]: [CommonCases] Prepare index IVF_FLAT done. (common_cases.py:86)
[2022-10-24 17:02:17,282 -  INFO - fouram]: [CommonCases] No scalars need to be indexed. (common_cases.py:91)
[2022-10-24 17:02:17,284 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_dXkcIRdI): 50000000 (base.py:244)
[2022-10-24 17:02:17,284 -  INFO - fouram]: [Base] Start load collection fouram_dXkcIRdI, replica_number:1 (base.py:97)
[2022-10-24 17:19:12,705 - ERROR - fouram]: Traceback (most recent call last):
  File "/src/fouram/client/util/api_request.py", line 21, in inner_wrapper
    res = func(*args, **kwargs)
  File "/src/fouram/client/util/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 473, in load
    conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 113, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 139, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 89, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 665, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 113, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 139, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 89, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 683, in wait_for_loading_collection
    progress = self.get_loading_progress(collection_name, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 113, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 139, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 89, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 744, in get_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection 436896709038047235 has not been loaded to memory or load failed)>
 (api_request.py:35)
[2022-10-24 17:19:12,705 - ERROR - fouram]: (api_response) : <MilvusException: (code=1, message=collection 436896709038047235 has not been loaded to memory or load failed)> (api_request.py:36)
[2022-10-24 17:19:12,705 - ERROR - fouram]: [CheckFunc] load request check failed, response:<MilvusException: (code=1, message=collection 436896709038047235 has not been loaded to memory or load failed)> (func_check.py:40)
```

server:
```
[2022-10-24 17:19:12,858 -  INFO - fouram]: [Base] Deploy initial state: 
I1024 16:26:18.495344     361 request.go:665] Waited for 1.154320553s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.local/apis/monitoring.coreos.com/v1alpha1?timeout=32s
NAME                                                              READY   STATUS      RESTARTS         AGE     IP             NODE         NOMINATED NODE   READINESS GATES
fouramf-cron-1666627200-3-71-6260-etcd-0                          1/1     Running     0                25m     10.104.9.169   4am-node14   <none>           <none>
fouramf-cron-1666627200-3-71-6260-milvus-standalone-7cf7bcgr8sz   1/1     Running     0                25m     10.104.4.211   4am-node11   <none>           <none>
fouramf-cron-1666627200-3-71-6260-minio-7f85fd669d-sdks6          1/1     Running     0                25m     10.104.9.172   4am-node14   <none>           <none> (base.py:126)
[2022-10-24 17:19:12,858 -  INFO - fouram]: [Cmd Exe]  kubectl get pods  -n qa-milvus  -o wide | grep -E 'STATUS|fouramf-cron-1666627200-3-71-6260'  (util_cmd.py:14)
[2022-10-24 17:19:18,968 -  INFO - fouram]: [CliClient] pod details of release(fouramf-cron-1666627200-3-71-6260): 
 I1024 17:19:14.122249    4427 request.go:665] Waited for 1.163681896s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.local/apis/autoscaling/v2?timeout=32s
NAME                                                              READY   STATUS      RESTARTS         AGE     IP             NODE         NOMINATED NODE   READINESS GATES
fouramf-cron-1666627200-3-71-6260-etcd-0                          1/1     Running     0                78m     10.104.9.169   4am-node14   <none>           <none>
fouramf-cron-1666627200-3-71-6260-milvus-standalone-7cf7bcgr8sz   1/1     Running     0                78m     10.104.4.211   4am-node11   <none>           <none>
fouramf-cron-1666627200-3-71-6260-minio-7f85fd669d-sdks6          1/1     Running     0                78m     10.104.9.172   4am-node14   <none>           <none> (cli_client.py:123)
[2022-10-24 17:19:18,969 -  INFO - fouram]: [Base] Start deleting services: fouramf-cron-1666627200-3-71-6260 (base.py:129)
[2022-10-24 17:19:18,969 -  INFO - fouram]: [Cmd Exe]  kubectl get pvc  -n qa-milvus  | grep -E 'STATUS|fouramf-cron-1666627200-3-71-6260'  (util_cmd.py:14)
[2022-10-24 17:19:24,889 -  INFO - fouram]: [CliClient] pvc storage class of release(fouramf-cron-1666627200-3-71-6260): 
 I1024 17:19:20.232249    4482 request.go:665] Waited for 1.10460722s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.local/apis/cert-manager.io/v1?timeout=32s
NAME                                                                                                           STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
data-fouramf-cron-1666627200-3-71-6260-etcd-0                                                                  Bound    pvc-fbe9f921-0b1b-4d3e-9052-5c89571f2450   10Gi       RWO            local-path        78m
fouramf-cron-1666627200-3-71-6260-milvus                                                                       Bound    pvc-833e1b1d-7331-4b82-9bec-20e7c617ac59   50Gi       RWO            local-path        78m
fouramf-cron-1666627200-3-71-6260-minio                                                                        Bound    pvc-5effef2a-0433-4a60-8ae3-402eb0f4fe6b   500Gi      RWO            local-path        78m (cli_client.py:131)
```

### Steps To Reproduce

```markdown
1、create collection
2、build index of ivf_flat
3、insert 50m vectors
4、flush collection
5、build index with the same params
6、load collection 《- raise error
```

### Anything else?

client params:
```
{
     "dataset_params": {
          "dim": 128,
          "dataset_name": "sift",
          "dataset_size": 50000000,
          "ni_per": 50000,
          "metric_type": "L2",
          "req_run_counts": 30
     },
     "collection_params": {
          "other_fields": []
     },
     "load_params": {},
     "search_params": {
          "top_k": [
               1,
               10,
               100,
               1000
          ],
          "nq": [
               1,
               10,
               100,
               200,
               500,
               1000,
               1200
          ],
          "search_param": {
               "nprobe": [
                    8,
                    32
               ]
          }
     },
     "index_params": {
          "index_type": "IVF_FLAT",
          "index_param": {
               "nlist": 2048
          }
     }
}
```

**Comment by czs007** [comment]
load failed.
Load is not guaranteed to succeed now. When it is found that the memory is not enough during the loading process, the load operation is rolled back, and the collection is not considered to be loaded.
Therefore, when the sdk asks whether the loading is complete, it will encounter the exception that the collection is not loaded.



2022-10-25 01:19:12 | [2022/10/24 17:19:12.503 +00:00] [INFO] [observers/collection_observer.go:98] ["load collection timeout, cancel it"] [collectionID=436896709038047235] [loadTime=16m55.186850539s]
-- | --

**Comment by wangting0128** [comment]
verify: 2.2.0-20221105-16c8642b
close issue
