### ISSUE TITLE
[Bug]: [benchmark][standalone][FLAT] Milvus load 50million vectors failed: collection 436910864330391554 has not been loaded to memory or load failed

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#20074]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20221025-290b902a
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0.dev45
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task:fouramf-cron-1666627200
test case: test_query_by_ids_local_standalone

server:
```
[2022-10-25 09:48:33,862 -  INFO - fouram]: [Base] Deploy initial state: 
I1025 07:25:06.719147   43756 request.go:665] Waited for 1.159581417s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.local/apis/cert-manager.io/v1?timeout=32s
NAME                                                              READY   STATUS      RESTARTS        AGE     IP             NODE         NOMINATED NODE   READINESS GATES
fouramf-cron-1666627200-1-50-6606-etcd-0                          1/1     Running     0               118s    10.104.9.232   4am-node14   <none>           <none>
fouramf-cron-1666627200-1-50-6606-milvus-standalone-7db9c8xcqgp   1/1     Running     0               118s    10.104.6.59    4am-node13   <none>           <none>
fouramf-cron-1666627200-1-50-6606-minio-68cdcfdf57-spbfs          1/1     Running     0               118s    10.104.6.58    4am-node13   <none>           <none> (base.py:126)
[2022-10-25 09:48:33,863 -  INFO - fouram]: [Cmd Exe]  kubectl get pods  -n qa-milvus  -o wide | grep -E 'STATUS|fouramf-cron-1666627200-1-50-6606'  (util_cmd.py:14)
[2022-10-25 09:48:39,856 -  INFO - fouram]: [CliClient] pod details of release(fouramf-cron-1666627200-1-50-6606): 
 I1025 09:48:35.161597   48945 request.go:665] Waited for 1.169669848s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.local/apis/node.k8s.io/v1?timeout=32s
NAME                                                              READY   STATUS      RESTARTS        AGE     IP             NODE         NOMINATED NODE   READINESS GATES
fouramf-cron-1666627200-1-50-6606-etcd-0                          1/1     Running     0               145m    10.104.9.232   4am-node14   <none>           <none>
fouramf-cron-1666627200-1-50-6606-milvus-standalone-7db9c8xcqgp   1/1     Running     0               145m    10.104.6.59    4am-node13   <none>           <none>
fouramf-cron-1666627200-1-50-6606-minio-68cdcfdf57-spbfs          1/1     Running     0               145m    10.104.6.58    4am-node13   <none>           <none> (cli_client.py:123)
[2022-10-25 09:48:39,856 -  INFO - fouram]: [Base] Start deleting services: fouramf-cron-1666627200-1-50-6606 (base.py:129)
[2022-10-25 09:48:39,856 -  INFO - fouram]: [Cmd Exe]  kubectl get pvc  -n qa-milvus  | grep -E 'STATUS|fouramf-cron-1666627200-1-50-6606'  (util_cmd.py:14)
[2022-10-25 09:48:45,777 -  INFO - fouram]: [CliClient] pvc storage class of release(fouramf-cron-1666627200-1-50-6606): 
 I1025 09:48:41.143463   49000 request.go:665] Waited for 1.15884053s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.local/apis/events.k8s.io/v1?timeout=32s
NAME                                                                                                 STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
data-fouramf-cron-1666627200-1-50-6606-etcd-0                                                        Bound    pvc-d856dba3-5de8-43ad-a4d6-b171acc1108c   10Gi       RWO            local-path        145m
fouramf-cron-1666627200-1-50-6606-milvus                                                             Bound    pvc-07a859c3-fc25-4f5c-a166-4263650eb539   50Gi       RWO            local-path        145m
fouramf-cron-1666627200-1-50-6606-minio                                                              Bound    pvc-4d396aa6-60ee-4a9a-94cc-9f7a31c6829d   500Gi      RWO            local-path        145m (cli_client.py:131)
```
<img width="1433" alt="截屏2022-10-25 21 28 32" src="https://user-images.githubusercontent.com/26307815/197786125-f37214e2-d0df-49b0-9c21-5d08f37eb128.png">

client logs:
[test_query_by_ids_local_standalone_1.zip](https://github.com/milvus-io/milvus/files/9860669/test_query_by_ids_local_standalone_1.zip)

```
2022-10-25 09:22:00,978 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_QtNxhK6R): 49750000 (base.py:244)
[2022-10-25 09:22:05,082 -  INFO - fouram]: [Base] Start inserting, ids: 49800000 - 49849999, data size: 50,000,000 (base.py:116)
[2022-10-25 09:22:08,402 -  INFO - fouram]: [Time] Collection.insert run in 3.3201s (api_request.py:29)
[2022-10-25 09:22:08,404 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_QtNxhK6R): 49800000 (base.py:244)
[2022-10-25 09:22:11,846 -  INFO - fouram]: [Base] Start inserting, ids: 49850000 - 49899999, data size: 50,000,000 (base.py:116)
[2022-10-25 09:22:15,196 -  INFO - fouram]: [Time] Collection.insert run in 3.3497s (api_request.py:29)
[2022-10-25 09:22:15,198 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_QtNxhK6R): 49850000 (base.py:244)
[2022-10-25 09:22:19,224 -  INFO - fouram]: [Base] Start inserting, ids: 49900000 - 49949999, data size: 50,000,000 (base.py:116)
[2022-10-25 09:22:22,607 -  INFO - fouram]: [Time] Collection.insert run in 3.383s (api_request.py:29)
[2022-10-25 09:22:22,609 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_QtNxhK6R): 49900000 (base.py:244)
[2022-10-25 09:22:26,207 -  INFO - fouram]: [Base] Start inserting, ids: 49950000 - 49999999, data size: 50,000,000 (base.py:116)
[2022-10-25 09:22:29,474 -  INFO - fouram]: [Time] Collection.insert run in 3.2663s (api_request.py:29)
[2022-10-25 09:22:29,476 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_QtNxhK6R): 49950000 (base.py:244)
[2022-10-25 09:22:29,828 -  INFO - fouram]: [Base] Total time of insert: 3299.6152s, average number of vector bars inserted per second: 15153.2821, average time to insert 50000 vectors per time: 3.2996s (base.py:175)
[2022-10-25 09:22:29,830 -  INFO - fouram]: [Base] Start flush collection fouram_QtNxhK6R (base.py:93)
[2022-10-25 09:22:31,846 -  INFO - fouram]: [Base] Collection:fouram_QtNxhK6R is not building index (base.py:230)
[2022-10-25 09:22:31,846 -  INFO - fouram]: [Base] Start build index of FLAT, params:{'index_type': 'FLAT', 'metric_type': 'L2', 'params': {}} (base.py:218)
[2022-10-25 09:22:33,394 -  INFO - fouram]: [Time] Index run in 1.5482s (api_request.py:29)
[2022-10-25 09:22:33,395 -  INFO - fouram]: [CommonCases] RT of build index FLAT: 1.5482s (common_cases.py:83)
[2022-10-25 09:22:33,450 -  INFO - fouram]: [Base] Params of index: {'index_type': 'FLAT', 'metric_type': 'L2', 'params': {}} (base.py:228)
[2022-10-25 09:22:33,450 -  INFO - fouram]: [CommonCases] Prepare index FLAT done. (common_cases.py:86)
[2022-10-25 09:22:33,450 -  INFO - fouram]: [CommonCases] No scalars need to be indexed. (common_cases.py:91)
[2022-10-25 09:22:33,452 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_QtNxhK6R): 50000000 (base.py:244)
[2022-10-25 09:22:33,452 -  INFO - fouram]: [Base] Start load collection fouram_QtNxhK6R, replica_number:1 (base.py:97)
[2022-10-25 09:48:33,818 - ERROR - fouram]: Traceback (most recent call last):
  File "/src/fouram/client/util/api_request.py", line 21, in inner_wrapper
    res = func(*args, **kwargs)
  File "/src/fouram/client/util/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 473, in load
    conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 113, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 139, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 89, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 665, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 113, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 139, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 89, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 683, in wait_for_loading_collection
    progress = self.get_loading_progress(collection_name, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 113, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 139, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 89, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 744, in get_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection 436910864330391554 has not been loaded to memory or load failed)>
 (api_request.py:35)
[2022-10-25 09:48:33,818 - ERROR - fouram]: (api_response) : <MilvusException: (code=1, message=collection 436910864330391554 has not been loaded to memory or load failed)> (api_request.py:36)
[2022-10-25 09:48:33,819 - ERROR - fouram]: [CheckFunc] load request check failed, response:<MilvusException: (code=1, message=collection 436910864330391554 has not been loaded to memory or load failed)> (func_check.py:40)
```

### Steps To Reproduce

```markdown
1、create collection
2、build index of flat
3、insert 50m vectors
4、flush
5、build index with the same params
6、load 《- raise error
```

### Milvus Log

server deploy cmd:
`helm  -n qa-milvus  upgrade --install  --set standalone.resources.limits.cpu=32.0,standalone.resources.limits.memory=128Gi,standalone.resources.requests.cpu=17.0,standalone.resources.requests.memory=65Gi,standalone.persistence.persistentVolumeClaim.storageClass=local-path,cluster.enabled=False,etcd.replicaCount=1,etcd.global.storageClass=local-path,etcd.metrics.enabled=True,etcd.metrics.podMonitor.enabled=True,minio.mode=standalone,minio.persistence.storageClass=local-path,minio.metrics.serviceMonitor.enabled=False,pulsar.enabled=False,metrics.serviceMonitor.enabled=True,image.all.repository=harbor.milvus.io/dockerhub/milvusdb/milvus,image.all.tag=master-20221025-290b902a   --wait --timeout 30m   fouramf-cron-1666627200-1-50-6606 /home/helm/charts/milvus/ `

### Anything else?

case param:
```
{
     "dataset_params": {
          "dim": 512,
          "dataset_name": "local",
          "dataset_size": "50m",
          "ni_per": 50000,
          "metric_type": "L2",
          "req_run_counts": 10
     },
     "collection_params": {},
     "load_params": {},
     "search_params": {},
     "index_params": {
          "index_type": "FLAT",
          "index_param": {}
     },
     "query_params": {
          "ids": [
               1,
               100,
               10000
          ]
     }
}
```

**Comment by czs007** [comment]
follower 2 failed to load segment, reason load segment failed, OOM if load, collectionID = 436910864330391554, maxSegmentSize = 1 MB, concurrency = 1, usedMemAfterLoad = 118837 MB, totalMem = 131072 MB, thresholdFactor = 0.900000"]

**Comment by czs007** [comment]
relate: https://github.com/milvus-io/milvus/pull/20108

**Comment by wangting0128** [comment]
argo task：fouramf-cron-1667664000
test case：test_query_by_ids_local_standalone

server：
```
[2022-11-06 09:44:12,527 -  INFO - fouram]: [Base] Deploy initial state: 
I1106 07:32:46.352663   44243 request.go:665] Waited for 1.160106871s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.local/apis/admissionregistration.k8s.io/v1?timeout=32s
NAME                                                              READY   STATUS      RESTARTS       AGE    IP             NODE         NOMINATED NODE   READINESS GATES
fouramf-cron-1667664000-1-58-8529-etcd-0                          1/1     Running     0              108s   10.104.6.3     4am-node13   <none>           <none>
fouramf-cron-1667664000-1-58-8529-milvus-standalone-6d5f87vc295   1/1     Running     0              108s   10.104.5.86    4am-node12   <none>           <none>
fouramf-cron-1667664000-1-58-8529-minio-b85b5cc6d-gqtlb           1/1     Running     0              108s   10.104.6.254   4am-node13   <none>           <none> (base.py:126)
[2022-11-06 09:44:12,527 -  INFO - fouram]: [Cmd Exe]  kubectl get pods  -n qa-milvus  -o wide | grep -E 'STATUS|fouramf-cron-1667664000-1-58-8529'  (util_cmd.py:14)
[2022-11-06 09:44:18,489 -  INFO - fouram]: [CliClient] pod details of release(fouramf-cron-1667664000-1-58-8529): 
 I1106 09:44:13.822975   49180 request.go:665] Waited for 1.173539868s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.local/apis/policy/v1beta1?timeout=32s
NAME                                                              READY   STATUS      RESTARTS         AGE    IP             NODE         NOMINATED NODE   READINESS GATES
fouramf-cron-1667664000-1-58-8529-etcd-0                          1/1     Running     0                133m   10.104.6.3     4am-node13   <none>           <none>
fouramf-cron-1667664000-1-58-8529-milvus-standalone-6d5f87vc295   1/1     Running     0                133m   10.104.5.86    4am-node12   <none>           <none>
fouramf-cron-1667664000-1-58-8529-minio-b85b5cc6d-gqtlb           1/1     Running     0                133m   10.104.6.254   4am-node13   <none>           <none> (cli_client.py:123)
[2022-11-06 09:44:18,490 -  INFO - fouram]: [Base] Start deleting services: fouramf-cron-1667664000-1-58-8529 (base.py:129)
[2022-11-06 09:44:18,490 -  INFO - fouram]: [Cmd Exe]  kubectl get pvc  -n qa-milvus  | grep -E 'STATUS|fouramf-cron-1667664000-1-58-8529'  (util_cmd.py:14)
[2022-11-06 09:44:24,424 -  INFO - fouram]: [CliClient] pvc storage class of release(fouramf-cron-1667664000-1-58-8529): 
 I1106 09:44:19.795043   49235 request.go:665] Waited for 1.157207632s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.local/apis/node.k8s.io/v1?timeout=32s
NAME                                                                                               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
data-fouramf-cron-1667664000-1-58-8529-etcd-0                                                      Bound    pvc-2051a3c6-d158-4f5e-957a-8556a71f7ccd   10Gi       RWO            local-path        133m
fouramf-cron-1667664000-1-58-8529-milvus                                                           Bound    pvc-e51e8cc0-e27c-4b99-b88b-495b4bc3c19e   50Gi       RWO            local-path        133m
fouramf-cron-1667664000-1-58-8529-minio                                                            Bound    pvc-024ffb7d-78dd-4618-b623-e741265f8385   500Gi      RWO            local-path        133m (cli_client.py:131)
```

client log:
```
[2022-11-06 09:19:40,993 -  INFO - fouram]: [Time] Collection.insert run in 3.3299s (api_request.py:29)
[2022-11-06 09:19:40,996 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_U2ZmFSxF): 49750000 (base.py:244)
[2022-11-06 09:19:44,335 -  INFO - fouram]: [Base] Start inserting, ids: 49800000 - 49849999, data size: 50,000,000 (base.py:116)
[2022-11-06 09:19:47,385 -  INFO - fouram]: [Time] Collection.insert run in 3.0501s (api_request.py:29)
[2022-11-06 09:19:47,387 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_U2ZmFSxF): 49800000 (base.py:244)
[2022-11-06 09:19:50,572 -  INFO - fouram]: [Base] Start inserting, ids: 49850000 - 49899999, data size: 50,000,000 (base.py:116)
[2022-11-06 09:19:53,664 -  INFO - fouram]: [Time] Collection.insert run in 3.0918s (api_request.py:29)
[2022-11-06 09:19:53,666 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_U2ZmFSxF): 49850000 (base.py:244)
[2022-11-06 09:19:56,959 -  INFO - fouram]: [Base] Start inserting, ids: 49900000 - 49949999, data size: 50,000,000 (base.py:116)
[2022-11-06 09:20:00,103 -  INFO - fouram]: [Time] Collection.insert run in 3.1439s (api_request.py:29)
[2022-11-06 09:20:00,105 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_U2ZmFSxF): 49900000 (base.py:244)
[2022-11-06 09:20:03,013 -  INFO - fouram]: [Base] Start inserting, ids: 49950000 - 49999999, data size: 50,000,000 (base.py:116)
[2022-11-06 09:20:06,150 -  INFO - fouram]: [Time] Collection.insert run in 3.1367s (api_request.py:29)
[2022-11-06 09:20:06,153 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_U2ZmFSxF): 49950000 (base.py:244)
[2022-11-06 09:20:06,410 -  INFO - fouram]: [Base] Total time of insert: 3076.2457s, average number of vector bars inserted per second: 16253.5782, average time to insert 50000 vectors per time: 3.0762s (base.py:175)
[2022-11-06 09:20:06,412 -  INFO - fouram]: [Base] Start flush collection fouram_U2ZmFSxF (base.py:93)
[2022-11-06 09:20:08,426 -  INFO - fouram]: [Base] Collection:fouram_U2ZmFSxF is not building index (base.py:230)
[2022-11-06 09:20:08,426 -  INFO - fouram]: [Base] Start build index of FLAT, params:{'index_type': 'FLAT', 'metric_type': 'L2', 'params': {}} (base.py:218)
[2022-11-06 09:20:10,180 -  INFO - fouram]: [Time] Index run in 1.7537s (api_request.py:29)
[2022-11-06 09:20:10,180 -  INFO - fouram]: [CommonCases] RT of build index FLAT: 1.7537s (common_cases.py:83)
[2022-11-06 09:20:10,234 -  INFO - fouram]: [Base] Params of index: {'index_type': 'FLAT', 'metric_type': 'L2', 'params': {}} (base.py:228)
[2022-11-06 09:20:10,234 -  INFO - fouram]: [CommonCases] Prepare index FLAT done. (common_cases.py:86)
[2022-11-06 09:20:10,234 -  INFO - fouram]: [CommonCases] No scalars need to be indexed. (common_cases.py:91)
[2022-11-06 09:20:10,235 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_U2ZmFSxF): 50000000 (base.py:244)
[2022-11-06 09:20:10,236 -  INFO - fouram]: [Base] Start load collection fouram_U2ZmFSxF, replica_number:1 (base.py:97)
[2022-11-06 09:44:12,402 - ERROR - fouram]: Traceback (most recent call last):
  File "/src/fouram/client/util/api_request.py", line 21, in inner_wrapper
    res = func(*args, **kwargs)
  File "/src/fouram/client/util/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 476, in load
    conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 668, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 686, in wait_for_loading_collection
    progress = self.get_loading_progress(collection_name, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 747, in get_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection 437182779903442948 has not been loaded to memory or load failed)>
 (api_request.py:35)
```

**Comment by wangting0128** [comment]
argo task:fouramf-cron-1667836800
test case：test_query_by_ids_local_standalone

server:
```
[2022-11-08 09:11:34,855 -  INFO - fouram]: [Base] Deploy initial state: 
I1108 07:07:39.081913   43713 request.go:665] Waited for 1.162477878s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.local/apis/chaos-mesh.org/v1alpha1?timeout=32s
NAME                                                              READY   STATUS      RESTARTS      AGE     IP             NODE         NOMINATED NODE   READINESS GATES
fouramf-cron-1667836800-1-24-3380-etcd-0                          1/1     Running     0             5m16s   10.104.4.176   4am-node11   <none>           <none>
fouramf-cron-1667836800-1-24-3380-milvus-standalone-bc57b5vcdhd   1/1     Running     0             5m16s   10.104.1.157   4am-node10   <none>           <none>
fouramf-cron-1667836800-1-24-3380-minio-6f878694c5-6mzqd          1/1     Running     0             5m16s   10.104.1.156   4am-node10   <none>           <none> (base.py:126)
[2022-11-08 09:11:34,855 -  INFO - fouram]: [Cmd Exe]  kubectl get pods  -n qa-milvus  -o wide | grep -E 'STATUS|fouramf-cron-1667836800-1-24-3380'  (util_cmd.py:14)
[2022-11-08 09:11:40,783 -  INFO - fouram]: [CliClient] pod details of release(fouramf-cron-1667836800-1-24-3380): 
 I1108 09:11:36.113617   48491 request.go:665] Waited for 1.171603149s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.local/apis/discovery.k8s.io/v1beta1?timeout=32s
NAME                                                              READY   STATUS      RESTARTS      AGE     IP             NODE         NOMINATED NODE   READINESS GATES
fouramf-cron-1667836800-1-24-3380-etcd-0                          1/1     Running     0             129m    10.104.4.176   4am-node11   <none>           <none>
fouramf-cron-1667836800-1-24-3380-milvus-standalone-bc57b5vcdhd   1/1     Running     0             129m    10.104.1.157   4am-node10   <none>           <none>
fouramf-cron-1667836800-1-24-3380-minio-6f878694c5-6mzqd          1/1     Running     0             129m    10.104.1.156   4am-node10   <none>           <none> (cli_client.py:123)
[2022-11-08 09:11:40,784 -  INFO - fouram]: [Base] Start deleting services: fouramf-cron-1667836800-1-24-3380 (base.py:129)
[2022-11-08 09:11:40,784 -  INFO - fouram]: [Cmd Exe]  kubectl get pvc  -n qa-milvus  | grep -E 'STATUS|fouramf-cron-1667836800-1-24-3380'  (util_cmd.py:14)
[2022-11-08 09:11:46,684 -  INFO - fouram]: [CliClient] pvc storage class of release(fouramf-cron-1667836800-1-24-3380): 
 I1108 09:11:42.050870   48546 request.go:665] Waited for 1.163559742s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.local/apis/events.k8s.io/v1?timeout=32s
NAME                                                                                               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
data-fouramf-cron-1667836800-1-24-3380-etcd-0                                                      Bound    pvc-6d8ccb7c-932e-4ba8-8ace-1f8587a8aff3   10Gi       RWO            local-path        129m
fouramf-cron-1667836800-1-24-3380-milvus                                                           Bound    pvc-446c01e6-ed2c-47e9-8188-96886b1af5fd   50Gi       RWO            local-path        129m
fouramf-cron-1667836800-1-24-3380-minio                                                            Bound    pvc-1431a84f-297e-43ab-bea0-3bb0a52ea102   500Gi      RWO            local-path        129m (cli_client.py:131)
```

client log:
```
[2022-11-08 08:48:51,028 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_2biQ9A1T): 49950000 (base.py:244)
[2022-11-08 08:48:51,263 -  INFO - fouram]: [Base] Total time of insert: 2892.6578s, average number of vector bars inserted per second: 17285.1417, average time to insert 50000 vectors per time: 2.8927s (base.py:175)
[2022-11-08 08:48:51,265 -  INFO - fouram]: [Base] Start flush collection fouram_2biQ9A1T (base.py:93)
[2022-11-08 08:48:53,276 -  INFO - fouram]: [Base] Collection:fouram_2biQ9A1T is not building index (base.py:230)
[2022-11-08 08:48:53,277 -  INFO - fouram]: [Base] Start build index of FLAT, params:{'index_type': 'FLAT', 'metric_type': 'L2', 'params': {}} (base.py:218)
[2022-11-08 08:48:54,819 -  INFO - fouram]: [Time] Index run in 1.5419s (api_request.py:29)
[2022-11-08 08:48:54,819 -  INFO - fouram]: [CommonCases] RT of build index FLAT: 1.5419s (common_cases.py:83)
[2022-11-08 08:48:54,872 -  INFO - fouram]: [Base] Params of index: {'index_type': 'FLAT', 'metric_type': 'L2', 'params': {}} (base.py:228)
[2022-11-08 08:48:54,872 -  INFO - fouram]: [CommonCases] Prepare index FLAT done. (common_cases.py:86)
[2022-11-08 08:48:54,872 -  INFO - fouram]: [CommonCases] No scalars need to be indexed. (common_cases.py:91)
[2022-11-08 08:48:54,874 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_2biQ9A1T): 50000000 (base.py:244)
[2022-11-08 08:48:54,874 -  INFO - fouram]: [Base] Start load collection fouram_2biQ9A1T, replica_number:1 (base.py:97)
[2022-11-08 09:11:34,818 - ERROR - fouram]: Traceback (most recent call last):
  File "/src/fouram/client/util/api_request.py", line 21, in inner_wrapper
    res = func(*args, **kwargs)
  File "/src/fouram/client/util/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 476, in load
    conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 668, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 686, in wait_for_loading_collection
    progress = self.get_loading_progress(collection_name, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 747, in get_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection 437227660601458693 has not been loaded to memory or load failed)>
 (api_request.py:35)
[2022-11-08 09:11:34,818 - ERROR - fouram]: (api_response) : <MilvusException: (code=1, message=collection 437227660601458693 has not been loaded to memory or load failed)> (api_request.py:36)
[2022-11-08 09:11:34,818 - ERROR - fouram]: [CheckFunc] load request check failed, response:<MilvusException: (code=1, message=collection 437227660601458693 has not been loaded to memory or load failed)> (func_check.py:40)
```

**Comment by yanliang567** [comment]
@sunby any updates?

**Comment by sunby** [comment]
Maybe related issue #21972

**Comment by yanliang567** [comment]
remove critical urgent for no updates for long time.

**Comment by elstic** [comment]
This case has been changed in the timed task and the issue of the new case has been recorded and will be closed here
