### ISSUE TITLE
[Bug]: Milvus standalone panicked with "move consume position backward" 

### ISSUE THREAD

**Issue by soothing-rain** [milvus-io/milvus#20079]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
2022-10-26 00:03:50 | starting application, this might take some time...
-- | --
  |   |   | 2022-10-26 00:03:50 | /milvus/tools/heaptrack/lib/heaptrack/libheaptrack_preload.so
  |   |   | 2022-10-26 00:03:50 | heaptrack output will be written to "/milvus/heaptrack.milvus.7.gz"
  |   |   | 2022-10-26 00:03:48 | heaptrack --analyze "/milvus/heaptrack.milvus.7.gz"
  |   |   | 2022-10-26 00:03:48 |  
  |   |   | 2022-10-26 00:03:48 | Heaptrack finished! Now run the following to investigate the data:
  |   |   | 2022-10-26 00:03:48 | temporary allocations:	177658611
  |   |   | 2022-10-26 00:03:48 | leaked allocations:   	1232659306
  |   |   | 2022-10-26 00:03:48 | allocations:          	4017061120
  |   |   | 2022-10-26 00:03:48 | heaptrack stats:
  |   |   | 2022-10-26 00:03:47 | /go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x8d
  |   |   | 2022-10-26 00:03:47 | created by golang.org/x/sync/errgroup.(*Group).Go
  |   |   | 2022-10-26 00:03:47 | /go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
  |   |   | 2022-10-26 00:03:47 | golang.org/x/sync/errgroup.(*Group).Go.func1()
  |   |   | 2022-10-26 00:03:47 | /go/src/github.com/milvus-io/milvus/internal/querynode/task.go:586 +0x39
  |   |   | 2022-10-26 00:03:47 | github.com/milvus-io/milvus/internal/querynode.(*loadSegmentsTask).Execute.func2()
  |   |   | 2022-10-26 00:03:47 | /go/src/github.com/milvus-io/milvus/internal/querynode/segment_loader.go:738 +0x626
  |   |   | 2022-10-26 00:03:47 | github.com/milvus-io/milvus/internal/querynode.(*segmentLoader).FromDmlCPLoadDelete(0xc001d466c0, {0x409ba50, 0xc01c8e3280?}, 0x61037af1d1c019d, 0xc045dff3e0)
  |   |   | 2022-10-26 00:03:47 | /go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_msgstream.go:549 +0x31b
  |   |   | 2022-10-26 00:03:47 | github.com/milvus-io/milvus/internal/mq/msgstream.(*mqMsgStream).Seek(0xc0b928e6c0, {0xc0d09a74d8, 0x1, 0x2?})
  |   |   | 2022-10-26 00:03:47 | /go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/rmq/rmq_consumer.go:83 +0x47
  |   |   | 2022-10-26 00:03:47 | github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/rmq.(*Consumer).Seek(0x3c9a2b4?, {0x409cee0?, 0xc0c83de770?}, 0x48?)
  |   |   | 2022-10-26 00:03:47 | /go/src/github.com/milvus-io/milvus/internal/mq/mqimpl/rocksmq/client/consumer_impl.go:121 +0x47
  |   |   | 2022-10-26 00:03:47 | github.com/milvus-io/milvus/internal/mq/mqimpl/rocksmq/client.(*consumer).Seek(0xc00df62c80, 0x3ba2d00?)
  |   |   | 2022-10-26 00:03:47 | /go/src/github.com/milvus-io/milvus/internal/mq/mqimpl/rocksmq/server/rocksmq_impl.go:819 +0x165
  |   |   | 2022-10-26 00:03:47 | github.com/milvus-io/milvus/internal/mq/mqimpl/rocksmq/server.(*rocksmq).Seek(0xc000eec240, {0xc00063a570, 0x16}, {0xc2b6219b20, 0x1e}, 0x61037af1a879aa7)
  |   |   | 2022-10-26 00:03:47 | /go/src/github.com/milvus-io/milvus/internal/mq/mqimpl/rocksmq/server/rocksmq_impl.go:773 +0x2e9
  |   |   | 2022-10-26 00:03:47 | github.com/milvus-io/milvus/internal/mq/mqimpl/rocksmq/server.(*rocksmq).seek(0xc000eec240, {0xc00063a570, 0x16}, {0xc2b6219b20, 0x1e}, 0x61037af1a879aa7)
  |   |   | 2022-10-26 00:03:47 | /go/src/github.com/milvus-io/milvus/internal/mq/mqimpl/rocksmq/server/rocksmq_impl.go:787 +0x691
  |   |   | 2022-10-26 00:03:47 | github.com/milvus-io/milvus/internal/mq/mqimpl/rocksmq/server.(*rocksmq).moveConsumePos(0xc000eec240, {0xc00063a570, 0x16}, {0xc2b6219b20, 0x1e}, 0x61037af1a879aa7)
  |   |   | 2022-10-26 00:03:47 | goroutine 93023332 [running]:
  |   |   | 2022-10-26 00:03:47 |  
  |   |   | 2022-10-26 00:03:47 | panic: move consume position backward
  |   |   | 2022-10-26 00:03:47 | [2022/10/25 16:03:47.890 +00:00] [INFO] [querynode/task.go:599] ["LoadSegmentTask Execute done"] [collectionID=436910389102117277] [replicaID=436910389206974465] [msgID=17782]
  |   |   | 2022-10-26 00:03:47 | [2022/10/25 16:03:47.890 +00:00] [WARN] [server/rocksmq_impl.go:785] ["RocksMQ: trying to move Consume position backward"] [key=querynode-2-436910389102117277/by-dev-rootcoord-dml_1] [oldPos=436910389058868442] [newPos=436910389058837159]
  |   |   | 2022-10-26 00:03:47 | [2022/10/25 16:03:47.890 +00:00] [INFO] [msgstream/mq_msgstream.go:548] ["MsgStream seek begin"] [channel=by-dev-rootcoord-dml_1] [MessageID="p5qHGq83EAY="]
  |   |   | 2022-10-26 00:03:47 | [2022/10/25 16:03:47.890 +00:00] [INFO] [msgstream/mq_msgstream.go:170] ["Successfully create consumer"] [channel=by-dev-rootcoord-dml_1] [subname=querynode-2-436910389102117277]
  |   |   | 2022-10-26 00:03:47 | [2022/10/25 16:03:47.889 +00:00] [DEBUG] [client/client_impl.go:82] ["ConsumerGroup already existed"] [topic=by-dev-rootcoord-dml_1] [SubscriptionName=querynode-2-436910389102117277]
  |   |   | 2022-10-26 00:03:47 | [2022/10/25 16:03:47.889 +00:00] [INFO] [querynode/segment_loader.go:706] ["from dml check point load delete"] [position="channel_name:\"by-dev-rootcoord-dml_1_436910389102117277v1\" msgID:\"\\247\\232\\207\\032\\2577\\020\\006\" msgGroup:\"by-dev-dataNode-6-by-dev-rootcoord-dml_1_436910389102117277v1\" timestamp:436918768493133826 "]
  |   |   | 2022-10-26 00:03:47 | [2022/10/25 16:03:47.889 +00:00] [INFO] [querynode/task.go:511] ["WatchDeltaChannels done"] [collectionID=436910389102117277] [ChannelIDs="[by-dev-rootcoord-delta_1_436910389102117277v1]\n"]
  |   |   | 2022-10-26 00:03:47 | [2022/10/25 16:03:47.889 +00:00] [INFO] [querynode/tsafe_replica.go:136] ["add tSafe done"] [channel=by-dev-rootcoord-delta_1_436910389102117277v1]
  |   |   | 2022-10-26 00:03:47 | [2022/10/25 16:03:47.889 +00:00] [INFO] [querynode/collection.go:196] ["pChannel has been existed in collection's pChannels"] [collectionID=436910389102117277] [pChannel=by-dev-rootcoord-delta_1]
  |   |   | 2022-10-26 00:03:47 | [2022/10/25 16:03:47.889 +00:00] [INFO] [querynode/collection.go:236] ["vDeltaChannel has been existed in collection's vDeltaChannels"] [collectionID=436910389102117277] [vChannel=by-dev-rootcoord-delta_1_436910389102117277v1]
  |   |   | 2022-10-26 00:03:47 | [2022/10/25 16:03:47.889 +00:00] [INFO] [querynode/task.go:481] ["watchDeltaChannel, add flowGraph for deltaChannel success"] [collectionID=436910389102117277] [vDeltaChannels="[by-dev-rootcoord-delta_1_436910389102117277v1]"]
  |   |   | 2022-10-26 00:03:47 | [2022/10/25 16:03:47.889 +00:00] [WARN] [querynode/data_sync_service.go:127] ["delta flow graph has been existed"] [collectionID=436910389102117277] [channel=by-dev-rootcoord-delta_1_436910389102117277v1]
```

**Comment by jaime0815** [comment]
it causes by #19592

**Comment by jaime0815** [comment]
It is possible that happens the msgID is less than the latest msgID within the topic when processes seek operation, so it should be a normal case.
```
func (rmq *rocksmq) moveConsumePos(topicName string, groupName string, msgID UniqueID) error {
	key := constructCurrentID(topicName, groupName)
	oldPos, ok := rmq.consumersID.Load(key)
	if !ok {
		return errors.New("move unknown consumer")
	}

	if msgID < oldPos.(UniqueID) {
		log.Warn("RocksMQ: trying to move Consume position backward",
			zap.String("key", key), zap.Int64("oldPos", oldPos.(UniqueID)), zap.Int64("newPos", msgID))
		panic("move consume position backward")
	}

```

**Comment by jaime0815** [comment]
load segment task 17780 was canceled when starting read delta msg from seek position, then load segment task 17782 try to consume mq with the same topic and groupid fail, that reason is  the rocksmq was not closed after task 17780 canceled.

```
[2022/10/25 16:03:47.890 +00:00] [INFO] [querynode/task.go:599] ["LoadSegmentTask Execute done"] [collectionID=436910389102117277] [replicaID=436910389206974465] [msgID=17782]
[2022/10/25 16:03:47.890 +00:00] [WARN] [server/rocksmq_impl.go:785] ["RocksMQ: trying to move Consume position backward"] [key=querynode-2-436910389102117277/by-dev-rootcoord-dml_1] [oldPos=436910389058868442] [newPos=436910389058837159]
[2022/10/25 16:03:47.890 +00:00] [INFO] [msgstream/mq_msgstream.go:170] ["Successfully create consumer"] [channel=by-dev-rootcoord-dml_1] [subname=querynode-2-436910389102117277]
[2022/10/25 16:03:47.889 +00:00] [DEBUG] [client/client_impl.go:82] ["ConsumerGroup already existed"] [topic=by-dev-rootcoord-dml_1] [SubscriptionName=querynode-2-436910389102117277]
[2022/10/25 16:03:47.889 +00:00] [INFO] [querynode/segment_loader.go:706] ["from dml check point load delete"] [position="channel_name:\"by-dev-rootcoord-dml_1_436910389102117277v1\" msgID:\"\\247\\232\\207\\032\\2577\\020\\006\" msgGroup:\"by-dev-dataNode-6-by-dev-rootcoord-dml_1_436910389102117277v1\" timestamp:436918768493133826 "]
[2022/10/25 16:03:47.542 +00:00] [INFO] [querynode/task.go:548] ["LoadSegmentTask Execute start"] [msgID=17782]

[2022/10/25 16:03:46.801 +00:00] [WARN] [querynode/impl.go:461] ["context canceled"]
[2022/10/25 16:03:46.801 +00:00] [WARN] [querynode/task_scheduler.go:111] ["context canceled"]
[2022/10/25 16:03:46.801 +00:00] [WARN] [querynode/task.go:594] ["failed to load delete data while load segment"] [collectionID=436910389102117277] [replicaID=436910389206974465] [error="context canceled"]
[2022/10/25 16:03:46.801 +00:00] [INFO] [querynode/segment.go:252] ["delete segment from memory"] [collectionID=436910389102117277] [partitionID=436910389102117278] [segmentID=436910389102578589] [segmentType=Sealed]
[2022/10/25 16:03:46.801 +00:00] [INFO] [querynode/partition.go:100] ["remove a segment from replica"] [collectionID=436910389102117277] [partitionID=436910389102117278] [segmentID=436910389102578589] [segmentType=Sealed]
[2022/10/25 16:03:46.800 +00:00] [INFO] [indexcoord/handoff.go:223] ["mark segment as write handoff success, remove task"] [segID=436910389102578590]
[2022/10/25 16:03:46.799 +00:00] [INFO] [querynode/segment_loader.go:750] ["start read delta msg from seek position to last position"] ["Collection ID"=436910389102117277] [channel=by-dev-rootcoord-dml_1] ["seek pos"="channel_name:\"by-dev-rootcoord-dml_1\" msgID:\"\\332\\024\\210\\032\\2577\\020\\006\" msgGroup:\"by-dev-dataNode-6-by-dev-rootcoord-dml_1_436910389102117277v1\" timestamp:436919028710375425 "] ["last msg"={}]
[2022/10/25 16:03:46.799 +00:00] [DEBUG] [server/rocksmq_impl.go:823] ["successfully seek"] [topic=by-dev-rootcoord-dml_1] [group=querynode-2-436910389102117277] [msgId=436910389058868442]
[2022/10/25 16:03:46.798 +00:00] [INFO] [msgstream/mq_msgstream.go:170] ["Successfully create consumer"] [channel=by-dev-rootcoord-dml_1] [subname=querynode-2-436910389102117277]
[2022/10/25 16:03:46.798 +00:00] [DEBUG] [server/rocksmq_impl.go:449] ["Rocksmq create consumer group successfully "] [topic=by-dev-rootcoord-dml_1] [group=querynode-2-436910389102117277] [elapsed=0]
[2022/10/25 16:03:46.798 +00:00] [INFO] [querynode/segment_loader.go:706] ["from dml check point load delete"] [position="channel_name:\"by-dev-rootcoord-dml_1_436910389102117277v1\" msgID:\"\\332\\024\\210\\032\\2577\\020\\006\" msgGroup:\"by-dev-dataNode-6-by-dev-rootcoord-dml_1_436910389102117277v1\" timestamp:436919028710375425 "]
[2022/10/25 16:03:46.542 +00:00] [INFO] [querynode/task.go:548] ["LoadSegmentTask Execute start"] [msgID=17780]
```
