### ISSUE TITLE
[Bug]: [benchmark] Glove dataset and build IVF_FLAT index, search with nprobe=512 that raise error:Deadline Exceeded

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#20075]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20221025-85ef7331
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0.dev45
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task:fouramf-cron-1666627200
test case:test_recall_glove_ivf_flat_cluster

server:
```
NAME                                                              READY   STATUS      RESTARTS        AGE     IP             NODE         NOMINATED NODE   READINESS GATES
fouramf-cron-1666627200-1-81-6086-etcd-0                          1/1     Running     0               82m     10.104.6.235   4am-node13   <none>           <none>
fouramf-cron-1666627200-1-81-6086-etcd-1                          1/1     Running     0               82m     10.104.9.192   4am-node14   <none>           <none>
fouramf-cron-1666627200-1-81-6086-etcd-2                          1/1     Running     0               82m     10.104.4.109   4am-node11   <none>           <none>
fouramf-cron-1666627200-1-81-6086-milvus-datacoord-5d665fcszlpx   1/1     Running     0               82m     10.104.6.229   4am-node13   <none>           <none>
fouramf-cron-1666627200-1-81-6086-milvus-datanode-767d8bb4s9smj   1/1     Running     0               82m     10.104.6.231   4am-node13   <none>           <none>
fouramf-cron-1666627200-1-81-6086-milvus-indexcoord-54bb6bvhcdr   1/1     Running     0               82m     10.104.6.220   4am-node13   <none>           <none>
fouramf-cron-1666627200-1-81-6086-milvus-indexnode-758769dvmmzl   1/1     Running     0               82m     10.104.9.188   4am-node14   <none>           <none>
fouramf-cron-1666627200-1-81-6086-milvus-proxy-f588868bd-mgxhp    1/1     Running     0               82m     10.104.6.224   4am-node13   <none>           <none>
fouramf-cron-1666627200-1-81-6086-milvus-querycoord-69b878w2mlw   1/1     Running     0               82m     10.104.6.219   4am-node13   <none>           <none>
fouramf-cron-1666627200-1-81-6086-milvus-querynode-59d7b95vmlj9   1/1     Running     0               82m     10.104.6.222   4am-node13   <none>           <none>
fouramf-cron-1666627200-1-81-6086-milvus-rootcoord-5564444kr5j6   1/1     Running     0               82m     10.104.6.225   4am-node13   <none>           <none>
fouramf-cron-1666627200-1-81-6086-minio-0                         1/1     Running     0               82m     10.104.6.236   4am-node13   <none>           <none>
fouramf-cron-1666627200-1-81-6086-minio-1                         1/1     Running     0               82m     10.104.9.190   4am-node14   <none>           <none>
fouramf-cron-1666627200-1-81-6086-minio-2                         1/1     Running     0               82m     10.104.4.108   4am-node11   <none>           <none>
fouramf-cron-1666627200-1-81-6086-minio-3                         1/1     Running     0               82m     10.104.5.120   4am-node12   <none>           <none>
fouramf-cron-1666627200-1-81-6086-pulsar-bookie-0                 1/1     Running     0               82m     10.104.9.195   4am-node14   <none>           <none>
fouramf-cron-1666627200-1-81-6086-pulsar-bookie-1                 1/1     Running     0               82m     10.104.6.239   4am-node13   <none>           <none>
fouramf-cron-1666627200-1-81-6086-pulsar-bookie-2                 1/1     Running     0               82m     10.104.4.112   4am-node11   <none>           <none>
fouramf-cron-1666627200-1-81-6086-pulsar-bookie-init-xn5bn        0/1     Completed   0               82m     10.104.6.226   4am-node13   <none>           <none>
fouramf-cron-1666627200-1-81-6086-pulsar-broker-0                 1/1     Running     0               82m     10.104.6.228   4am-node13   <none>           <none>
fouramf-cron-1666627200-1-81-6086-pulsar-proxy-0                  1/1     Running     0               82m     10.104.6.221   4am-node13   <none>           <none>
fouramf-cron-1666627200-1-81-6086-pulsar-pulsar-init-5flp6        0/1     Completed   0               82m     10.104.6.227   4am-node13   <none>           <none>
fouramf-cron-1666627200-1-81-6086-pulsar-recovery-0               1/1     Running     0               82m     10.104.6.223   4am-node13   <none>           <none>
fouramf-cron-1666627200-1-81-6086-pulsar-zookeeper-0              1/1     Running     0               82m     10.104.6.234   4am-node13   <none>           <none>
fouramf-cron-1666627200-1-81-6086-pulsar-zookeeper-1              1/1     Running     0               81m     10.104.9.197   4am-node14   <none>           <none>
fouramf-cron-1666627200-1-81-6086-pulsar-zookeeper-2              1/1     Running     0               81m     10.104.5.122   4am-node12   <none>           <none> 
```

client logs:
[test_recall_glove_ivf_flat_cluster_1.zip](https://github.com/milvus-io/milvus/files/9860773/test_recall_glove_ivf_flat_cluster_1.zip)

```
[2022-10-25 06:37:51,362 -  INFO - fouram]: [PerfTemplate] Actual parameters used: {'dataset_params': {'dim': 200, 'dataset_name': 'glove-200-angular', 'ni_per': 10000}, 'collection_params': {'other_fields': []}, 'load_params': {'replica_number': 1}, 'search_params': {'top_k': 10, 'nq': 10000, 'search_param': {'nprobe': 512}}, 'index_params': {'index_type': 'IVF_FLAT', 'index_param': {'nlist': 1024}}} (performance_template.py:59)
[2022-10-25 06:37:51,368 -  INFO - fouram]: [AccCases] Params of search: {'data': array([[-0.02773983,  0.0795716 , -0.07341436, ...,  0.0432257 ,
        -0.09719583, -0.08906623],
       [-0.00701086, -0.03715183,  0.0632261 , ..., -0.0334666 ,
        -0.09059103,  0.05058862],
       [ 0.04278408, -0.0195656 , -0.0546626 , ...,  0.0624952 ,
        -0.13264737, -0.01105194],
       ...,
       [ 0.03442654,  0.13952227,  0.02177458, ...,  0.04648568,
        -0.05786795, -0.06752396],
       [ 0.04487952, -0.03255282,  0.07743784, ...,  0.08966012,
        -0.01795752,  0.07155532],
       [-0.0895235 , -0.12985045,  0.11885931, ...,  0.0558663 ,
         0.07499653, -0.15403427]], dtype=float32), 'anns_field': 'float_vector', 'param': {'metric_type': 'IP', 'params': {'nprobe': 512}}, 'limit': 10} (accuracy_cases.py:145)
[2022-10-25 06:37:51,368 -  INFO - fouram]: [Base] Params of search: nq:10000, anns_field:float_vector, param:{'metric_type': 'IP', 'params': {'nprobe': 512}}, limit:10, expr:"None" (base.py:268)
[2022-10-25 06:42:51,627 - ERROR - fouram]: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 471, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 435, in _execute_search_requests
    raise pre_err
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 423, in _execute_search_requests
    response = ft.result()
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1666680171.625480254","description":"Error received from peer ipv4:10.255.219.41:19530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/src/fouram/client/util/api_request.py", line 21, in inner_wrapper
    res = func(*args, **kwargs)
  File "/src/fouram/client/util/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 716, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 113, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 139, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 59, in handler
    raise MilvusException(Status.UNEXPECTED_ERROR, str(e))
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1666680171.625480254","description":"Error received from peer ipv4:10.255.219.41:19530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>)>
 (api_request.py:35)
[2022-10-25 06:42:51,628 - ERROR - fouram]: (api_response) : <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1666680171.625480254","description":"Error received from peer ipv4:10.255.219.41:19530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>)> (api_request.py:36)
[2022-10-25 06:42:51,628 - ERROR - fouram]: [CheckFunc] search request check failed, response:<MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1666680171.625480254","description":"Error received from peer ipv4:10.255.219.41:19530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>)> (func_check.py:40)
[2022-10-25 06:42:51,628 - ERROR - fouram]: [AccCases] Search raise error:  (accuracy_cases.py:173)
```

### Steps To Reproduce

```markdown
1、create collection
2、insert 1183514 vectors
3、flush 
4、build index of IVF_FLAT
5、load
6、serial search and calculation of RT and recall 《- nprobe=512 raise error
```

### Anything else?

case param：
```
{
     "dataset_params": {
          "dim": 200,
          "dataset_name": "glove-200-angular",
          "ni_per": 10000
     },
     "collection_params": {
          "other_fields": []
     },
     "load_params": {
          "replica_number": 1
     },
     "search_params": {
          "top_k": [
               10
          ],
          "nq": [
               10000
          ],
          "search_param": {
               "nprobe": [
                    1,
                    2,
                    4,
                    8,
                    16,
                    32,
                    64,
                    128,
                    256,
                    512
               ]
          }
     },
     "index_params": {
          "index_type": "IVF_FLAT",
          "index_param": {
               "nlist": 1024
          }
     }
}
```

**Comment by czs007** [comment]
![image](https://user-images.githubusercontent.com/59249785/199143289-0e4d7c9a-2c17-4449-ac3e-653c7d8fa0d8.png)
As nprobe grows, segcore does take more time.

**Comment by aoiasd** [comment]
Test on my Mac(4 Core), row count 1024*1024, data size 512MB
Search with nprobe 512, nlist 1024, nq=10000: 
At 2.2.0 will use 220s. 
At 2.1 will be more slow, use near 260s(Search after compaction complete, if not will use near 330s)

Search with nprobe 8, nlist 16, nq=10000
nprobe 8, nlist 16 same with  nprobe 512, nlist 1024, will search half of all data(256MB).
At 2.2.0 use 190s, and it can be sure that most time used in CSearch.

So most of time used by search in the bucket of IVF_FLAT, near 19ms per nq.

**Comment by yanliang567** [comment]
downgrade the priority
@jingkl any chance to rerun on 2.2.1

**Comment by elstic** [comment]
Environment
```
- Milvus version: 2.2.0-20221216-1aa7a9a8
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.1.dev4
```
argo task : fouramf-cron-1671292800
case name: test_recall_glove_ivf_flat_cluster

server
```
fouramf-cron-1671292800-1-3-8818-etcd-0                           1/1     Running     0          80m     10.104.1.88    4am-node10   <none>           <none>
fouramf-cron-1671292800-1-3-8818-etcd-1                           1/1     Running     0          80m     10.104.4.214   4am-node11   <none>           <none>
fouramf-cron-1671292800-1-3-8818-etcd-2                           1/1     Running     0          80m     10.104.5.94    4am-node12   <none>           <none>
fouramf-cron-1671292800-1-3-8818-milvus-datacoord-c7587c6chk45m   1/1     Running     0          80m     10.104.5.85    4am-node12   <none>           <none>
fouramf-cron-1671292800-1-3-8818-milvus-datanode-69b9dd5d4xwrhl   1/1     Running     0          80m     10.104.5.84    4am-node12   <none>           <none>
fouramf-cron-1671292800-1-3-8818-milvus-indexcoord-75dccb6rdhnv   1/1     Running     0          80m     10.104.5.87    4am-node12   <none>           <none>
fouramf-cron-1671292800-1-3-8818-milvus-indexnode-6cb867f86slkq   1/1     Running     0          80m     10.104.5.83    4am-node12   <none>           <none>
fouramf-cron-1671292800-1-3-8818-milvus-proxy-747889bbb4-kxn64    1/1     Running     0          80m     10.104.4.207   4am-node11   <none>           <none>
fouramf-cron-1671292800-1-3-8818-milvus-querycoord-85f5b442llgp   1/1     Running     0          80m     10.104.5.86    4am-node12   <none>           <none>
fouramf-cron-1671292800-1-3-8818-milvus-querynode-59f68cd95ws7q   1/1     Running     0          80m     10.104.4.210   4am-node11   <none>           <none>
fouramf-cron-1671292800-1-3-8818-milvus-rootcoord-7447cb98wp2rv   1/1     Running     0          80m     10.104.4.209   4am-node11   <none>           <none>
fouramf-cron-1671292800-1-3-8818-minio-0                          1/1     Running     0          80m     10.104.1.91    4am-node10   <none>           <none>
fouramf-cron-1671292800-1-3-8818-minio-1                          1/1     Running     0          80m     10.104.4.217   4am-node11   <none>           <none>
fouramf-cron-1671292800-1-3-8818-minio-2                          1/1     Running     0          80m     10.104.5.97    4am-node12   <none>           <none>
fouramf-cron-1671292800-1-3-8818-minio-3                          1/1     Running     0          80m     10.104.6.148   4am-node13   <none>           <none>
fouramf-cron-1671292800-1-3-8818-pulsar-bookie-0                  1/1     Running     0          80m     10.104.1.89    4am-node10   <none>           <none>
fouramf-cron-1671292800-1-3-8818-pulsar-bookie-1                  1/1     Running     0          80m     10.104.4.215   4am-node11   <none>           <none>
fouramf-cron-1671292800-1-3-8818-pulsar-bookie-2                  1/1     Running     0          80m     10.104.5.96    4am-node12   <none>           <none>
fouramf-cron-1671292800-1-3-8818-pulsar-bookie-init-rr9wv         0/1     Completed   0          80m     10.104.1.83    4am-node10   <none>           <none>
fouramf-cron-1671292800-1-3-8818-pulsar-broker-0                  1/1     Running     0          80m     10.104.1.82    4am-node10   <none>           <none>
fouramf-cron-1671292800-1-3-8818-pulsar-proxy-0                   1/1     Running     0          80m     10.104.1.84    4am-node10   <none>           <none>
fouramf-cron-1671292800-1-3-8818-pulsar-pulsar-init-lnxp4         0/1     Completed   0          80m     10.104.5.88    4am-node12   <none>           <none>
fouramf-cron-1671292800-1-3-8818-pulsar-recovery-0                1/1     Running     0          80m     10.104.4.208   4am-node11   <none>           <none>
fouramf-cron-1671292800-1-3-8818-pulsar-zookeeper-0               1/1     Running     0          80m     10.104.5.90    4am-node12   <none>           <none>
fouramf-cron-1671292800-1-3-8818-pulsar-zookeeper-1               1/1     Running     0          80m     10.104.1.93    4am-node10   <none>           <none>
fouramf-cron-1671292800-1-3-8818-pulsar-zookeeper-2               1/1     Running     0          79m     10.104.4.219   4am-node11   <none>           <none> (cli_client.py:115)
```


client log
![image](https://user-images.githubusercontent.com/48523564/208573836-4b141904-0e59-40c0-a848-9c257f6d6e50.png)

**Comment by yanliang567** [comment]
keep it active

**Comment by elstic** [comment]
This issue does not appear in recent versions.
