### ISSUE TITLE
[Bug]: [CI]Failed to delete index, collection.indexes means indexes still exist

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#20096]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 87e7651af
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus==2.2.0.dev63
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

testcase：

```
[gw5] [ 26%] FAILED testcases/test_index.py::TestIndexOperation::test_index_drop_index 

[2022-10-26T07:37:33.689Z] 

[2022-10-26T07:37:33.689Z] =================================== FAILURES ===================================

[2022-10-26T07:37:33.689Z] ___________________ TestIndexOperation.test_index_drop_index ___________________

[2022-10-26T07:37:33.689Z] [gw5] linux -- Python 3.8.13 /usr/local/bin/python3

[2022-10-26T07:37:33.689Z] [gw5] linux -- Python 3.8.13 /usr/local/bin/python3[gw5] linux -- Python 3.8.13 /usr/local/bin/python3

[2022-10-26T07:37:33.689Z] 

[2022-10-26T07:37:33.689Z] self = <test_index.TestIndexOperation object at 0x7f2e7b5b47f0>

[2022-10-26T07:37:33.689Z] 

[2022-10-26T07:37:33.689Z]     @pytest.mark.tags(CaseLabel.L1)

[2022-10-26T07:37:33.689Z]     def test_index_drop_index(self):

[2022-10-26T07:37:33.689Z]         """

[2022-10-26T07:37:33.689Z]         target: test index.drop

[2022-10-26T07:37:33.689Z]         method: create index by `index`, and then drop it

[2022-10-26T07:37:33.689Z]         expected: no exception raised

[2022-10-26T07:37:33.689Z]         """

[2022-10-26T07:37:33.689Z]         c_name = cf.gen_unique_str(prefix)

[2022-10-26T07:37:33.689Z]         collection_w = self.init_collection_wrap(name=c_name)

[2022-10-26T07:37:33.689Z]         index, _ = self.index_wrap.init_index(collection_w.collection, default_field_name, default_index_params)

[2022-10-26T07:37:33.689Z]         cf.assert_equal_index(index, collection_w.collection.indexes[0])

[2022-10-26T07:37:33.689Z]         self.index_wrap.drop()

[2022-10-26T07:37:33.689Z] >       assert len(collection_w.collection.indexes) == 0

[2022-10-26T07:37:33.689Z] E       assert 1 == 0

[2022-10-26T07:37:33.689Z] E        +  where 1 = len([<pymilvus.orm.index.Index object at 0x7f2e4f585400>])
```

jenkins log ：https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-20063/7/artifacts

log：
```
[2022-10-26T07:37:33.690Z] [2022-10-26 07:37:20 - DEBUG - ci_test]: (api_response) : <Collection>:

[2022-10-26T07:37:33.690Z] -------------

[2022-10-26T07:37:33.690Z] <name>: index_CJHImofJ

[2022-10-26T07:37:33.690Z] <partitions>: [{"name": "_default", "collection_name": "index_CJHImofJ", "description": ""}]

[2022-10-26T07:37:33.690Z] <description>: 

[2022-10-26T07:37:33.690Z] <schema>: {

[2022-10-26T07:37:33.690Z]   auto_id: False

[2022-10-26T07:37:33.690Z]   description: 

[2022-10-26T07:37:33.690Z]   fields: [{

[2022-10-26T07:37:33.690Z]     name: int64

[2022-10-26T07:37:33.690Z]     description: 

[2022-10-26T07:37:33.690Z]     type: 5

[2022-10-26T07:37:33.690Z]     is_primary: True

[2022-10-26T07:37:33.690Z]     auto_id: Fa......  (api_request.py:31)

[2022-10-26T07:37:33.690Z] [2022-10-26 07:37:20 - DEBUG - ci_test]: (api_request)  : [Index] args: [<Collection>:

[2022-10-26T07:37:33.690Z] -------------

[2022-10-26T07:37:33.690Z] <name>: index_CJHImofJ

[2022-10-26T07:37:33.690Z] <partitions>: [{"name": "_default", "collection_name": "index_CJHImofJ", "description": ""}]

[2022-10-26T07:37:33.690Z] <description>: 

[2022-10-26T07:37:33.690Z] <schema>: {

[2022-10-26T07:37:33.690Z]   auto_id: False

[2022-10-26T07:37:33.690Z]   description: 

[2022-10-26T07:37:33.690Z]   fields: [{

[2022-10-26T07:37:33.690Z]     name: int64

[2022-10-26T07:37:33.690Z]     description: 

[2022-10-26T07:37:33.690Z]     type: 5

[2022-10-26T07:37:33.690Z]     is_primary: True

[2022-10-26T07:37:33.690Z]     auto_id: F......, kwargs: {'timeout': 200, 'index_name': ''} (api_request.py:56)

[2022-10-26T07:37:33.690Z] [2022-10-26 07:37:21 - DEBUG - ci_test]: (api_response) : <pymilvus.orm.index.Index object at 0x7f2e4ebfba30>  (api_request.py:31)

[2022-10-26T07:37:33.690Z] [2022-10-26 07:37:21 - DEBUG - ci_test]: (api_request)  : [Index.drop] args: [], kwargs: {'timeout': 20, 'index_name': ''} (api_request.py:56)

[2022-10-26T07:37:33.690Z] [2022-10-26 07:37:21 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)
```

log file
[artifacts-milvus-standalone-PR-20063-7-pymilvus-e2e-logs.tar.gz](https://github.com/milvus-io/milvus/files/9867658/artifacts-milvus-standalone-PR-20063-7-pymilvus-e2e-logs.tar.gz)

### Steps To Reproduce

```markdown
1. create an collction
2. build index
3. drop index 
4. result not delete index
```

**Comment by xiaocai2333** [comment]
fixed.
/assign @jingkl 
/unassign

**Comment by jingkl** [comment]
testcase:

```
[gw1] linux -- Python 3.8.13 /usr/local/bin/python3

[2022-10-28T03:21:00.056Z] [gw1] linux -- Python 3.8.13 /usr/local/bin/python3[gw1] linux -- Python 3.8.13 /usr/local/bin/python3

[2022-10-28T03:21:00.056Z] 

[2022-10-28T03:21:00.056Z] self = <test_index.TestIndexOperation object at 0x7f1feea7dee0>

[2022-10-28T03:21:00.056Z] 

[2022-10-28T03:21:00.056Z]     @pytest.mark.tags(CaseLabel.L1)

[2022-10-28T03:21:00.056Z]     # TODO #7372

[2022-10-28T03:21:00.056Z]     def test_index_drop_repeatedly(self):

[2022-10-28T03:21:00.056Z]         """

[2022-10-28T03:21:00.056Z]         target: test index.drop

[2022-10-28T03:21:00.056Z]         method: create index by `index`, and then drop it twice

[2022-10-28T03:21:00.056Z]         expected: exception raised

[2022-10-28T03:21:00.056Z]         """

[2022-10-28T03:21:00.056Z]         c_name = cf.gen_unique_str(prefix)

[2022-10-28T03:21:00.056Z]         collection_w = self.init_collection_wrap(name=c_name)

[2022-10-28T03:21:00.056Z]         _, _ = self.index_wrap.init_index(collection_w.collection, default_field_name, default_index_params)

[2022-10-28T03:21:00.056Z] >       self.index_wrap.drop()

[2022-10-28T03:21:00.056Z] 

[2022-10-28T03:21:00.056Z] testcases/test_index.py:389: 

[2022-10-28T03:21:00.056Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

[2022-10-28T03:21:00.056Z] base/index_wrapper.py:40: in drop

[2022-10-28T03:21:00.056Z]     check_result = ResponseChecker(res, func_name, check_task, check_items, is_succ, **kwargs).run()

[2022-10-28T03:21:00.056Z] check/func_check.py:34: in run

[2022-10-28T03:21:00.056Z]     result = self.assert_succ(self.succ, True)

[2022-10-28T03:21:00.056Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

[2022-10-28T03:21:00.056Z] 

[2022-10-28T03:21:00.056Z] actual = False, expect = True

[2022-10-28T03:21:00.056Z] 

[2022-10-28T03:21:00.056Z]     @staticmethod

[2022-10-28T03:21:00.056Z]     def assert_succ(actual, expect):

[2022-10-28T03:21:00.056Z] >       assert actual is expect

[2022-10-28T03:21:00.056Z] E       AssertionError
```

client log:

```
[2022-10-28T04:28:48.229Z] [2022-10-28 04:28:35 - DEBUG - ci_test]: (api_response) : <pymilvus.orm.index.Index object at 0x7efc916aed30>  (api_request.py:31)

[2022-10-28T04:28:48.229Z] [2022-10-28 04:28:35 - DEBUG - ci_test]: (api_request)  : [Index.drop] args: [], kwargs: {'timeout': 20, 'index_name': ''} (api_request.py:56)

[2022-10-28T04:28:48.229Z] [2022-10-28 04:28:35 - ERROR - pymilvus.decorators]: RPC error: [drop_index], <MilvusException: (code=1, message=IndexName is not specified)>, <Time:{'RPC start': '2022-10-28 04:28:35.864855', 'RPC error': '2022-10-28 04:28:35.865623'}> (decorators.py:108)

[2022-10-28T04:28:48.229Z] [2022-10-28 04:28:35 - ERROR - ci_test]: Traceback (most recent call last):

[2022-10-28T04:28:48.229Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2022-10-28T04:28:48.229Z]     res = func(*args, **_kwargs)

[2022-10-28T04:28:48.229Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2022-10-28T04:28:48.229Z]     return func(*arg, **kwargs)

[2022-10-28T04:28:48.229Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/index.py", line 163, in drop

[2022-10-28T04:28:48.229Z]     conn.drop_index(self._collection.name, self.field_name, index_name, timeout=timeout, **copy_kwargs)

[2022-10-28T04:28:48.229Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler

[2022-10-28T04:28:48.229Z]     raise e

[2022-10-28T04:28:48.229Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler

[2022-10-28T04:28:48.229Z]     return func(*args, **kwargs)

[2022-10-28T04:28:48.229Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler

[2022-10-28T04:28:48.229Z]     ret = func(self, *args, **kwargs)

[2022-10-28T04:28:48.229Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler

[2022-10-28T04:28:48.229Z]     raise e

[2022-10-28T04:28:48.229Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler

[2022-10-28T04:28:48.229Z]     return func(self, *args, **kwargs)

[2022-10-28T04:28:48.229Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 851, in drop_index

[2022-10-28T04:28:48.229Z]     raise MilvusException(response.error_code, response.reason)

[2022-10-28T04:28:48.229Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=IndexName is not specified)>

[2022-10-28T04:28:48.229Z]  (api_request.py:39)

[2022-10-28T04:28:48.229Z] [2022-10-28 04:28:35 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=IndexName is not specified)> (api_request.py:40)
```

jenkins:https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-20063/14/pipeline/


milvus tag:6c9db52e4

**Comment by xiaocai2333** [comment]
fixed, please verify
/assign @jingkl

**Comment by jingkl** [comment]
This problem has been fixed, close issue
