### ISSUE TITLE
[Bug]: Create index raise error `CreateIndex failed: creating multiple indexes on same field is not supported` after upgrading

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#20103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.1.4 --> master-20221026-d525cacb
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.1.3 --> pymilvus==2.2.0.dev63
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2022-10-26T09:49:50.033Z] Create index...

[2022-10-26T09:49:50.033Z] IVF_SQ8

[2022-10-26T09:49:50.033Z] <Collection>:

[2022-10-26T09:49:50.033Z] -------------

[2022-10-26T09:49:50.033Z] <name>: task_2_IVF_SQ8

[2022-10-26T09:49:50.033Z] <partitions>: [{"name": "_default", "collection_name": "task_2_IVF_SQ8", "description": ""}]

[2022-10-26T09:49:50.033Z] <description>: test collection

[2022-10-26T09:49:50.033Z] <schema>: {

[2022-10-26T09:49:50.033Z]   auto_id: False

[2022-10-26T09:49:50.033Z]   description: test collection

[2022-10-26T09:49:50.033Z]   fields: [{

[2022-10-26T09:49:50.033Z]     name: count

[2022-10-26T09:49:50.033Z]     description: 

[2022-10-26T09:49:50.033Z]     type: 5

[2022-10-26T09:49:50.033Z]     is_primary: True

[2022-10-26T09:49:50.033Z]     auto_id: False

[2022-10-26T09:49:50.033Z]   }, {

[2022-10-26T09:49:50.033Z]     name: random_value

[2022-10-26T09:49:50.033Z]     description: 

[2022-10-26T09:49:50.033Z]     type: 11

[2022-10-26T09:49:50.033Z]   }, {

[2022-10-26T09:49:50.033Z]     name: float_vector

[2022-10-26T09:49:50.033Z]     description: 

[2022-10-26T09:49:50.033Z]     type: 101

[2022-10-26T09:49:50.033Z]     params: {'dim': 128}

[2022-10-26T09:49:50.033Z]   }]

[2022-10-26T09:49:50.033Z] }

[2022-10-26T09:49:50.034Z] 

[2022-10-26T09:49:50.034Z] Traceback (most recent call last):

[2022-10-26T09:49:50.034Z]   File "scripts/action_after_upgrade.py", line 105, in <module>

[2022-10-26T09:49:50.034Z]     task_2(data_size, host)

[2022-10-26T09:49:50.034Z]   File "scripts/action_after_upgrade.py", line 38, in task_2

[2022-10-26T09:49:50.034Z]     create_index(prefix)

[2022-10-26T09:49:50.034Z]   File "/home/jenkins/agent/workspace/tests/python_client/deploy/scripts/utils.py", line 151, in create_index

[2022-10-26T09:49:50.034Z]     c.create_index(field_name="float_vector", index_params=index)

[2022-10-26T09:49:50.034Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 1093, in create_index

[2022-10-26T09:49:50.034Z]     timeout=timeout, **kwargs)

[2022-10-26T09:49:50.034Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 109, in handler

[2022-10-26T09:49:50.034Z]     raise e

[2022-10-26T09:49:50.034Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 105, in handler

[2022-10-26T09:49:50.034Z]     return func(*args, **kwargs)

[2022-10-26T09:49:50.034Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 136, in handler

[2022-10-26T09:49:50.034Z]     ret = func(self, *args, **kwargs)

[2022-10-26T09:49:50.034Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 85, in handler

[2022-10-26T09:49:50.034Z]     raise e

[2022-10-26T09:49:50.034Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 50, in handler

[2022-10-26T09:49:50.034Z]     return func(self, *args, **kwargs)

[2022-10-26T09:49:50.034Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 561, in create_index

[2022-10-26T09:49:50.034Z]     raise MilvusException(status.error_code, status.reason)

[2022-10-26T09:49:50.034Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=CreateIndex failed: creating multiple indexes on same field is not supported)>
```

### Expected Behavior

all test cases passed

### Steps To Reproduce

```markdown
before upgrade: create collection, insert data and create index, load and search
after upgrade: get collection, load, search, insert data, create index, load, and search

when creating index before upgrading and after upgrading,  the index name is not passed in, so the value is set by system as default value.
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test/detail/deploy_test/526/pipeline

log:
[artifacts-standalone-upgrade-526-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9868511/artifacts-standalone-upgrade-526-server-logs.tar.gz)

[artifacts-standalone-upgrade-526-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9868512/artifacts-standalone-upgrade-526-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
/assign @xiaocai2333 
PTAL

**Comment by zhuwenxing** [comment]
Verified and not reproduced.
But it becomes to another issue https://github.com/milvus-io/milvus/issues/20179
