### ISSUE TITLE
[Bug]: Loading again after release, it will timeout after 60s when querynode number is 3 or more

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#20151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20221027-d5bc4e25
- Deployment mode(standalone or cluster): both
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus==2.2.0.dev68
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
 [2022-10-28 00:32:59 - INFO - ci_test]: [test][2022-10-28T00:32:59Z] [0.00480840s] e2e__hnIl0JmM flush -> None (wrapper.py:30)
 [2022-10-28 00:32:59 - INFO - ci_test]: assert create collection: 0.06064748764038086, init_entities: 0 (test_e2e.py:24)
 [2022-10-28 00:33:00 - INFO - ci_test]: [test][2022-10-28T00:32:59Z] [0.40605972s] e2e__hnIl0JmM insert -> (insert count: 3000, delete count: 0, upsert count: 0, timestamp: {self._timestamp}, success count: {self.succ_count}, err count: {self.err_count}) (wrapper.py:30)
 [2022-10-28 00:33:00 - INFO - ci_test]: assert insert: 0.40630054473876953 (test_e2e.py:31)
 [2022-10-28 00:33:03 - INFO - ci_test]: [test][2022-10-28T00:33:00Z] [3.01777338s] e2e__hnIl0JmM flush -> None (wrapper.py:30)
 [2022-10-28 00:33:03 - INFO - ci_test]: [test][2022-10-28T00:33:03Z] [0.00588390s] e2e__hnIl0JmM flush -> None (wrapper.py:30)
 [2022-10-28 00:33:03 - INFO - ci_test]: [test][2022-10-28T00:33:03Z] [0.00310394s] e2e__hnIl0JmM flush -> None (wrapper.py:30)
 [2022-10-28 00:33:03 - INFO - ci_test]: assert flush: 3.02542781829834, entities: 3000 (test_e2e.py:41)
 [2022-10-28 00:33:05 - INFO - ci_test]: [test][2022-10-28T00:33:03Z] [2.52804599s] e2e__hnIl0JmM create_index -> Status(code=0, message=) (wrapper.py:30)
 [2022-10-28 00:33:08 - INFO - ci_test]: [test][2022-10-28T00:33:05Z] [3.02416739s] e2e__hnIl0JmM load -> None (wrapper.py:30)
 [2022-10-28 00:33:08 - INFO - ci_test]: [test][2022-10-28T00:33:08Z] [0.25966106s] e2e__hnIl0JmM search -> <pymilvus.orm.search.SearchResult object at 0x7f64db3f3640> (wrapper.py:30)
 [2022-10-28 00:33:08 - INFO - ci_test]: assert search: 0.2599039077758789 (test_e2e.py:56)
 [2022-10-28 00:33:10 - INFO - ci_test]: [test][2022-10-28T00:33:08Z] [1.81002013s] e2e__hnIl0JmM release -> None (wrapper.py:30)
 [2022-10-28 00:33:11 - INFO - ci_test]: [test][2022-10-28T00:33:10Z] [0.34176409s] e2e__hnIl0JmM insert -> (insert count: 3000, delete count: 0, upsert count: 0, timestamp: {self._timestamp}, success count: {self.succ_count}, err count: {self.err_count}) (wrapper.py:30)
 [2022-10-28 00:33:13 - INFO - ci_test]: [test][2022-10-28T00:33:11Z] [2.51506627s] e2e__hnIl0JmM flush -> None (wrapper.py:30)
 [2022-10-28 00:33:13 - INFO - ci_test]: assert index entities: 6000 (test_e2e.py:63)
 [2022-10-28 00:33:15 - INFO - ci_test]: [test][2022-10-28T00:33:13Z] [1.51960054s] e2e__hnIl0JmM create_index -> Status(code=0, message=) (wrapper.py:30)
 [2022-10-28 00:33:15 - INFO - ci_test]: assert index: 1.5198545455932617 (test_e2e.py:70)
 [2022-10-28 00:33:35 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=wait for loading collection timeout, collection: e2e__hnIl0JmM)>, <Time:{'RPC start': '2022-10-28 00:33:15.194608', 'RPC error': '2022-10-28 00:33:35.297940'}> (decorators.py:108)
 [2022-10-28 00:33:35 - WARNING - pymilvus.decorators]: [93mRetry timeout: 20s[0m (decorators.py:79)
 [2022-10-28 00:33:35 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry timeout: 20s, message=wait for loading collection timeout, collection: e2e__hnIl0JmM)>, <Time:{'RPC start': '2022-10-28 00:33:15.185831', 'RPC error': '2022-10-28 00:33:35.298342'}> (decorators.py:108)
 [2022-10-28 00:33:35 - ERROR - ci_test]: Traceback (most recent call last):
   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
     return func(self, *args, **kwargs)
   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 668, in load_collection
     self.wait_for_loading_collection(collection_name, timeout)
   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
     raise e
   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
     return func(*args, **kwargs)
   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
     ret = func(self, *args, **kwargs)
   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
     raise e
   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
     return func(self, *args, **kwargs)
   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 690, in wait_for_loading_collection
     raise MilvusException(message=f"wait for loading collection timeout, collection: {collection_name}")
 pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=wait for loading collection timeout, collection: e2e__hnIl0JmM)>
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
     res = func(*args, **_kwargs)
   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
     return func(*arg, **kwargs)
   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 476, in load
     conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
     raise e
   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
     return func(*args, **kwargs)
   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
     ret = func(self, *args, **kwargs)
   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 80, in handler
     raise MilvusException(e.code, f"{timeout_msg}, message={e.message}") from e
 pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 20s, message=wait for loading collection timeout, collection: e2e__hnIl0JmM)>
  (api_request.py:39)
 [2022-10-28 00:33:35 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 20s, message=wait for loading collection timeout, collection: e2e__hnIl0JmM)> (api_request.py:40)
 FAILED
```

### Expected Behavior

time for second loading is normal

### Steps To Reproduce

```markdown
def test_milvus_default(self):
        # create
        name = cf.gen_unique_str(prefix)
        t0 = time.time()
        collection_w = self.init_collection_wrap(name=name, active_trace=True)
        tt = time.time() - t0
        assert collection_w.name == name
        entities = collection_w.num_entities
        log.info(f"assert create collection: {tt}, init_entities: {entities}")

        # insert
        data = cf.gen_default_list_data()
        t0 = time.time()
        _, res = collection_w.insert(data)
        tt = time.time() - t0
        log.info(f"assert insert: {tt}")
        assert res

        # flush
        t0 = time.time()
        _, check_result = collection_w.flush(timeout=180)
        assert check_result
        assert collection_w.num_entities == len(data[0]) + entities
        tt = time.time() - t0
        entities = collection_w.num_entities
        log.info(f"assert flush: {tt}, entities: {entities}")

        # search
        _index_params = {"index_type": "IVF_SQ8", "params": {"nlist": 64}, "metric_type": "L2"}
        index, _ = collection_w.create_index(field_name=ct.default_float_vec_field_name,
                                             index_params=_index_params,
                                             name=cf.gen_unique_str())
        collection_w.load()
        search_vectors = cf.gen_vectors(1, ct.default_dim)
        search_params = {"metric_type": "L2", "params": {"nprobe": 16}}
        t0 = time.time()
        res_1, _ = collection_w.search(data=search_vectors,
                                       anns_field=ct.default_float_vec_field_name,
                                       param=search_params, limit=1)
        tt = time.time() - t0
        log.info(f"assert search: {tt}")
        assert len(res_1) == 1
        collection_w.release()

        # index
        d = cf.gen_default_list_data()
        collection_w.insert(d)
        log.info(f"assert index entities: {collection_w.num_entities}")
        _index_params = {"index_type": "IVF_SQ8", "params": {"nlist": 64}, "metric_type": "L2"}
        t0 = time.time()
        index, _ = collection_w.create_index(field_name=ct.default_float_vec_field_name,
                                             index_params=_index_params,
                                             name=cf.gen_unique_str())
        tt = time.time() - t0
        log.info(f"assert index: {tt}")
        assert len(collection_w.indexes) == 1

        # search
        t0 = time.time()
        collection_w.load()
        tt = time.time() - t0
        log.info(f"assert load: {tt}")
        search_vectors = cf.gen_vectors(1, ct.default_dim)
        t0 = time.time()
        res_1, _ = collection_w.search(data=search_vectors,
                                       anns_field=ct.default_float_vec_field_name,
                                       param=search_params, limit=1)
        tt = time.time() - t0
        log.info(f"assert search: {tt}")

        # query
        term_expr = f'{ct.default_int64_field_name} in [1001,1201,4999,2999]'
        t0 = time.time()
        res, _ = collection_w.query(term_expr)
        tt = time.time() - t0
        log.info(f"assert query result {len(res)}: {tt}")
```

### Milvus Log

[artifacts-s3-pod-failure-2526-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9884808/artifacts-s3-pod-failure-2526-pytest-logs.tar.gz)

[artifacts-s3-pod-failure-2526-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9884809/artifacts-s3-pod-failure-2526-server-logs.tar.gz)

### Anything else?

It happened before the chaos test, it just happened in a fresh Milvus

**Comment by zhuwenxing** [comment]
/unassign @yanliang567 
/assign @jiaoew1991 
PTAL

**Comment by zhuwenxing** [comment]
when the timeout was set to 40s, it still failed.
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/2535/pipeline
log:
[artifacts-datanode-pod-kill-2535-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9889789/artifacts-datanode-pod-kill-2535-pytest-logs.tar.gz)
[artifacts-datanode-pod-kill-2535-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9889790/artifacts-datanode-pod-kill-2535-server-logs.tar.gz)

**Comment by zhuwenxing** [comment]
when the timeout was set to 60s, it still failed.
failed job https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/2536/pipeline
log:
[artifacts-datanode-pod-kill-2536-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9889912/artifacts-datanode-pod-kill-2536-server-logs.tar.gz)
[artifacts-datanode-pod-kill-2536-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9889913/artifacts-datanode-pod-kill-2536-pytest-logs.tar.gz)

**Comment by jiaoew1991** [comment]
/unassign 
/assign @zhuwenxing 
you can retry with pr #20182

**Comment by zhuwenxing** [comment]
verified and passed
