### ISSUE TITLE
[Bug]: [Nightly]Milvus crashed reporting 'invalid memory address or nil pointer dereference'

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#20158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:d5bc4e2
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0.dev68
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Milvus crashed reporting 'invalid memory address or nil pointer dereference'.
```
2022-10-28T02:01:49.48206295+08:00 stderr F panic: All attempts results:
2022-10-28T02:01:49.482088522+08:00 stderr F attempt #1:err: find no available rootcoord, check rootcoord state
2022-10-28T02:01:49.482095472+08:00 stderr F , /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
2022-10-28T02:01:49.482100049+08:00 stderr F /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:304 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall
2022-10-28T02:01:49.482105838+08:00 stderr F /go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/client/client.go:127 github.com/milvus-io/milvus/internal/distributed/rootcoord/client.(*Client).GetComponentStates
2022-10-28T02:01:49.482116893+08:00 stderr F /go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:65 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates.func1
2022-10-28T02:01:49.482120872+08:00 stderr F /go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:37 github.com/milvus-io/milvus/internal/util/retry.Do
2022-10-28T02:01:49.482125454+08:00 stderr F /go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:89 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates
2022-10-28T02:01:49.482136538+08:00 stderr F /go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:104 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentHealthy
2022-10-28T02:01:49.482141827+08:00 stderr F /go/src/github.com/milvus-io/milvus/internal/distributed/indexcoord/service.go:141 github.com/milvus-io/milvus/internal/distributed/indexcoord.(*Server).init
2022-10-28T02:01:49.482150745+08:00 stderr F /go/src/github.com/milvus-io/milvus/internal/distributed/indexcoord/service.go:81 github.com/milvus-io/milvus/internal/distributed/indexcoord.(*Server).Run
2022-10-28T02:01:49.482154671+08:00 stderr F /go/src/github.com/milvus-io/milvus/cmd/components/index_coord.go:51 github.com/milvus-io/milvus/cmd/components.(*IndexCoord).Run
2022-10-28T02:01:49.482160058+08:00 stderr F
2022-10-28T02:01:49.482164786+08:00 stderr F attempt #2:err: find no available rootcoord, check rootcoord state
```
```
2022-10-28T02:01:50.51279123+08:00 stdout F [2022/10/27 18:01:50.512 +00:00] [DEBUG] [querycoord/service.go:289] ["QueryCoord stop"] [Address=10.105.7.181:19531]
2022-10-28T02:01:50.51281645+08:00 stdout F [2022/10/27 18:01:50.512 +00:00] [INFO] [querycoordv2/server.go:357] ["stop cluster..."]
2022-10-28T02:01:50.516157161+08:00 stderr F panic: runtime error: invalid memory address or nil pointer dereference
2022-10-28T02:01:50.516168894+08:00 stderr F [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x2c347e7]
2022-10-28T02:01:50.516174084+08:00 stderr F
2022-10-28T02:01:50.516178557+08:00 stderr F goroutine 1 [running]:
2022-10-28T02:01:50.516182732+08:00 stderr F github.com/milvus-io/milvus/internal/querycoordv2.(*Server).Stop(0xc00056b080)
2022-10-28T02:01:50.516189748+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/querycoordv2/server.go:358 +0x67
2022-10-28T02:01:50.516197184+08:00 stderr F github.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).Stop(0xc0004fe0a0)
2022-10-28T02:01:50.516215204+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/service.go:298 +0x1e4
2022-10-28T02:01:50.516222313+08:00 stderr F github.com/milvus-io/milvus/cmd/components.(*QueryCoord).Stop(0x5000104?)
2022-10-28T02:01:50.51622627+08:00 stderr F     /go/src/github.com/milvus-io/milvus/cmd/components/query_coord.go:62 +0x1d
2022-10-28T02:01:50.516237537+08:00 stderr F github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run(0xc00063fe50, 0x0, {0x0, 0x0})
2022-10-28T02:01:50.516245085+08:00 stderr F    /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:311 +0xc3c
2022-10-28T02:01:50.516250495+08:00 stderr F github.com/milvus-io/milvus/cmd/milvus.(*run).execute(0xc000c1b140, {0xc00012c060?, 0x3, 0x3}, 0xc00047e3c0)
2022-10-28T02:01:50.516254721+08:00 stderr F    /go/src/github.com/milvus-io/milvus/cmd/milvus/run.go:120 +0x733
2022-10-28T02:01:50.516269878+08:00 stderr F github.com/milvus-io/milvus/cmd/milvus.RunMilvus({0xc00012c060?, 0x3, 0x3})

```

### Expected Behavior

PASS

### Steps To Reproduce

```markdown
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/175/pipeline/187
```

### Milvus Log

[artifacts-milvus-distributed-pulsar-nightly-175-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/175/artifact/artifacts-milvus-distributed-pulsar-nightly-175-pymilvus-e2e-logs.tar.gz)

file:
ci.var.log.containers.mdp-175-n-milvus-indexcoord-75dc544bd9-q8b5d_milvus-ci_indexcoord-e85f699624308f91ddc83e2e021323d73a29cf74ef7e2fa75b63b5f5fcb7ee71.log
ci.var.log.containers.mdp-175-n-milvus-querycoord-85b8b7dc66-5sc6g_milvus-ci_querycoord-ddb4b42e39e9b332f553f9b786ba6cdd0b4d33c173a2ef1d29ab8776cbae2b82.log

**Comment by binbinlv** [comment]
@NicoYuan1986 
please verify this issue.

**Comment by NicoYuan1986** [comment]
Fixed.
