### ISSUE TITLE
[Bug]: [upgrade] Collection is not exist after upgrading milvus from 2.1 to master

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#20199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20221031-8d0cc422
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus dev68
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. Deploy milvus 2.1.0
2. Create index, Insert and flush, create index with pymilvus 2.1
3. Upgrade milvus to `master-20221031-8d0cc422`
4. collection not exist
```
[2022-10-31 04:28:09,560 - INFO - ci_test]: [initialize_milvus] Log cleaned up, start testing... (conftest.py:194)
[2022-10-31 04:28:09,580 - DEBUG - ci_test]: (api_request)  : [Collection] args: ['upgrade_index', None, 'default', 2], kwargs: {'co
nsistency_level': 'Strong'} (api_request.py:56)
[2022-10-31 04:28:09,583 - ERROR - ci_test]: Traceback (most recent call last):
  File "/src/milvus/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/src/milvus/tests/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 137, in __init__
    raise SchemaNotReadyException(message=ExceptionsMessage.CollectionNotExistNoSchema % name)
pymilvus.exceptions.SchemaNotReadyException: <SchemaNotReadyException: (code=1, message=Collection 'upgrade_index' not exist, or you
 can pass in schema to create one.)>
 (api_request.py:39)
```
client pod:
`cluster-upgrade-index-before-x6h2r-2958863942`
Server pod:
```
NAME                                                            READY   STATUS      RESTARTS          AGE     IP              NODE            NOMINATED NODE   READINESS GATES
cluster-upgrade-etcd-0                                          1/1     Running     0                 13m     10.102.5.25     devops-node21   <none>           <none>
cluster-upgrade-etcd-1                                          1/1     Running     0                 13m     10.102.10.132   devops-node20   <none>           <none>
cluster-upgrade-etcd-2                                          1/1     Running     0                 13m     10.102.8.224    devops-node12   <none>           <none>
cluster-upgrade-milvus-datacoord-568b7f7548-kmnd7               1/1     Running     0                 46s     10.102.5.90     devops-node21   <none>           <none>
cluster-upgrade-milvus-datanode-6f8b564557-jqhbx                1/1     Running     0                 46s     10.102.5.91     devops-node21   <none>           <none>
cluster-upgrade-milvus-indexcoord-6f97c88db8-dm5rx              1/1     Running     0                 46s     10.102.5.89     devops-node21   <none>           <none>
cluster-upgrade-milvus-indexnode-65cd98977-k6fdz                1/1     Running     0                 46s     10.102.5.95     devops-node21   <none>           <none>
cluster-upgrade-milvus-proxy-6d74fd8f97-kvjsk                   1/1     Running     0                 46s     10.102.5.88     devops-node21   <none>           <none>
cluster-upgrade-milvus-querycoord-7cb99c4588-zg6dk              1/1     Running     0                 46s     10.102.5.94     devops-node21   <none>           <none>
cluster-upgrade-milvus-querynode-774d4fc697-9jg7p               1/1     Running     0                 46s     10.102.5.93     devops-node21   <none>           <none>
cluster-upgrade-milvus-rootcoord-5c44b7bf7b-lhqgv               1/1     Running     0                 46s     10.102.5.92     devops-node21   <none>           <none>
cluster-upgrade-minio-0                                         1/1     Running     0                 13m     10.102.5.28     devops-node21   <none>           <none>
cluster-upgrade-minio-1                                         1/1     Running     0                 13m     10.102.10.134   devops-node20   <none>           <none>
cluster-upgrade-minio-2                                         1/1     Running     0                 13m     10.102.8.225    devops-node12   <none>           <none>
cluster-upgrade-minio-3                                         1/1     Running     0                 13m     10.102.6.219    devops-node10   <none>           <none>
cluster-upgrade-pulsar-bookie-0                                 1/1     Running     0                 13m     10.102.5.34     devops-node21   <none>           <none>
cluster-upgrade-pulsar-bookie-1                                 1/1     Running     0                 13m     10.102.10.138   devops-node20   <none>           <none>
cluster-upgrade-pulsar-bookie-2                                 1/1     Running     0                 13m     10.102.8.229    devops-node12   <none>           <none>
cluster-upgrade-pulsar-bookie-init-x7xkg                        0/1     Completed   0                 13m     10.102.5.19     devops-node21   <none>           <none>
cluster-upgrade-pulsar-broker-0                                 1/1     Running     0                 13m     10.102.10.129   devops-node20   <none>           <none>
cluster-upgrade-pulsar-proxy-0                                  1/1     Running     0                 13m     10.102.10.130   devops-node20   <none>           <none>
cluster-upgrade-pulsar-pulsar-init-9j9cw                        0/1     Completed   0                 13m     10.102.10.131   devops-node20   <none>           <none>
cluster-upgrade-pulsar-recovery-0                               1/1     Running     0                 13m     10.102.5.21     devops-node21   <none>           <none>
cluster-upgrade-pulsar-zookeeper-0                              1/1     Running     0                 13m     10.102.5.33     devops-node21   <none>           <none>
cluster-upgrade-pulsar-zookeeper-1                              1/1     Running     0                 12m     10.102.10.142   devops-node20   <none>           <none>
cluster-upgrade-pulsar-zookeeper-2                              1/1     Running     0                 12m     10.102.8.233    devops-node12   <none>           <none>
```

**Comment by Maghamrohith** [comment]
Hi @ThreadDao ,
Can we update an existing collection instead or delete and insert?
thanks in advance
