### ISSUE TITLE
[Bug]: Search failed with error `Search 6 failed, reason [UnexpectedError] Assert "Segment 437057689446982774 System Field RowID or Timestamp is not loaded" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:395` after datanode pod kill chaos test for Kafka version

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#20229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20221031-a2d5947f
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
2022-10-31T19:20:45.027Z] [2022-10-31 19:19:06 - INFO - ci_test]: assert insert: 0.4285159111022949 (test_all_collections_after_chaos.py:42)

[2022-10-31T19:20:45.027Z] [2022-10-31 19:19:06 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:56)

[2022-10-31T19:20:45.027Z] [2022-10-31 19:19:09 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)

[2022-10-31T19:20:45.027Z] [2022-10-31 19:19:09 - INFO - ci_test]: [test][2022-10-31T19:19:06Z] [2.52342354s] Checker__fyOfpnKs flush -> None (wrapper.py:30)

[2022-10-31T19:20:45.027Z] [2022-10-31 19:19:09 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 360} (api_request.py:56)

[2022-10-31T19:20:45.027Z] [2022-10-31 19:19:09 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)

[2022-10-31T19:20:45.027Z] [2022-10-31 19:19:09 - INFO - ci_test]: [test][2022-10-31T19:19:09Z] [0.00452510s] Checker__fyOfpnKs flush -> None (wrapper.py:30)

[2022-10-31T19:20:45.027Z] [2022-10-31 19:19:09 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 360} (api_request.py:56)

[2022-10-31T19:20:45.027Z] [2022-10-31 19:19:09 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)

[2022-10-31T19:20:45.027Z] [2022-10-31 19:19:09 - INFO - ci_test]: [test][2022-10-31T19:19:09Z] [0.00593516s] Checker__fyOfpnKs flush -> None (wrapper.py:30)

[2022-10-31T19:20:45.027Z] [2022-10-31 19:19:09 - INFO - ci_test]: assert flush: 2.5305159091949463, entities: 20042 (test_all_collections_after_chaos.py:52)

[2022-10-31T19:20:45.027Z] [2022-10-31 19:19:09 - INFO - ci_test]: index info: [{'collection': 'Checker__fyOfpnKs', 'field': 'float_vector', 'index_name': 'index__AlxUKHZx', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}] (test_all_collections_after_chaos.py:68)

[2022-10-31T19:20:45.027Z] [2022-10-31 19:19:09 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 360], kwargs: {} (api_request.py:56)

[2022-10-31T19:20:45.027Z] [2022-10-31 19:19:09 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)

[2022-10-31T19:20:45.027Z] [2022-10-31 19:19:09 - INFO - ci_test]: [test][2022-10-31T19:19:09Z] [0.00813158s] Checker__fyOfpnKs load -> None (wrapper.py:30)

[2022-10-31T19:20:45.027Z] [2022-10-31 19:19:09 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.06109819315287981, 0.13070283257864643, 0.08535296310349849, 0.08984527451166008, 0.022217335284859818, 0.09821160671553741, 0.07519066359350549, 0.13268365717548164, 0.08918355823012082, 0.1103051125991434, 0.11891477349637086, 0.08977535757719467, 0.10218824398908126, 0.12769355146491465, 0.0......, kwargs: {} (api_request.py:56)

[2022-10-31T19:20:45.027Z] [2022-10-31 19:19:09 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=Channel: by-dev-rootcoord-dml_17_437057689446977087v1 returns err: fail to Search, QueryNode ID=4, reason=Search 6 failed, reason [UnexpectedError] Assert "Segment 437057689446982774 System Field RowID or Timestamp is not loaded" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:395

[2022-10-31T19:20:45.027Z]  err %!w(<nil>))>, <Time:{'RPC start': '2022-10-31 19:19:09.296254', 'RPC error': '2022-10-31 19:19:09.455506'}> (decorators.py:108)

[2022-10-31T19:20:45.027Z] [2022-10-31 19:19:09 - ERROR - ci_test]: Traceback (most recent call last):

[2022-10-31T19:20:45.027Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2022-10-31T19:20:45.027Z]     res = func(*args, **_kwargs)

[2022-10-31T19:20:45.027Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2022-10-31T19:20:45.027Z]     return func(*arg, **kwargs)

[2022-10-31T19:20:45.027Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 719, in search

[2022-10-31T19:20:45.027Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,

[2022-10-31T19:20:45.027Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2022-10-31T19:20:45.027Z]     raise e

[2022-10-31T19:20:45.027Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2022-10-31T19:20:45.027Z]     return func(*args, **kwargs)

[2022-10-31T19:20:45.027Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2022-10-31T19:20:45.027Z]     ret = func(self, *args, **kwargs)

[2022-10-31T19:20:45.027Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2022-10-31T19:20:45.027Z]     raise e

[2022-10-31T19:20:45.027Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2022-10-31T19:20:45.027Z]     return func(self, *args, **kwargs)

[2022-10-31T19:20:45.027Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 476, in search

[2022-10-31T19:20:45.027Z]     return self._execute_search_requests(requests, timeout, **_kwargs)

[2022-10-31T19:20:45.027Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 440, in _execute_search_requests

[2022-10-31T19:20:45.027Z]     raise pre_err

[2022-10-31T19:20:45.027Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 431, in _execute_search_requests

[2022-10-31T19:20:45.027Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2022-10-31T19:20:45.027Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=Channel: by-dev-rootcoord-dml_17_437057689446977087v1 returns err: fail to Search, QueryNode ID=4, reason=Search 6 failed, reason [UnexpectedError] Assert "Segment 437057689446982774 System Field RowID or Timestamp is not loaded" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:395

[2022-10-31T19:20:45.027Z]  err %!w(<nil>))>

[2022-10-31T19:20:45.027Z]  (api_request.py:39)
```

### Expected Behavior

all test cases passed

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka/detail/chaos-test-kafka/2384/pipeline/
log:
[artifacts-datanode-pod-kill-2384-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9906513/artifacts-datanode-pod-kill-2384-server-logs.tar.gz)
[artifacts-datanode-pod-kill-2384-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9906514/artifacts-datanode-pod-kill-2384-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
/assign @soothing-rain 
PTAL
It is same with  https://github.com/milvus-io/milvus/issues/19954

**Comment by soothing-rain** [comment]
DataCoord sealed the segment and start flushing it (# of rows != 0)

At the same time DataNode restarted, started recover the segment (# of rows == 0), and started to flush the segment with 0 rows (which should be forbidden)

**Comment by zhuwenxing** [comment]
Not reproduced
