### ISSUE TITLE
[Bug]: [Upgrade][cluster]milvus 2.1 update master, then shut down and restart milvus, finally release collection, drop index and then create a new index failed

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#20226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1->master-20221031-d0de1028
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. 
server-instance
fouram-tag-no-clean-vhk4f-1
server-configmap
server-cluster-8c64m-kafka
client-configmap
client-random-locust-1m-hnsw-ddl-r8-w2-10m
milvus image: 2.1.0
 
milvus server：

```
fouram-tag-no-clean-vhk4f-1-milvus-datacoord-569f44f96f-rwg7t    1/1     Running     0                109s    10.104.9.31    4am-nod
e14   <none>           <none>
fouram-tag-no-clean-vhk4f-1-milvus-datanode-6bc5c5f4f5-fw6k8     1/1     Running     0                109s    10.104.6.14    4am-nod
e13   <none>           <none>
fouram-tag-no-clean-vhk4f-1-milvus-indexcoord-576dc6c75-46sbq    1/1     Running     0                109s    10.104.6.15    4am-nod
e13   <none>           <none>
fouram-tag-no-clean-vhk4f-1-milvus-indexnode-5dc9dd8656-qd77b    1/1     Running     0                109s    10.104.4.63    4am-nod
e11   <none>           <none>
fouram-tag-no-clean-vhk4f-1-milvus-proxy-64d69d46f7-rl49z        1/1     Running     0                109s    10.104.9.30    4am-nod
e14   <none>           <none>
fouram-tag-no-clean-vhk4f-1-milvus-querycoord-77b484fd68-4mhd7   1/1     Running     0                109s    10.104.6.16    4am-nod
e13   <none>           <none>
fouram-tag-no-clean-vhk4f-1-milvus-querynode-7bbf8f5d8b-cw2qz    1/1     Running     0                109s    10.104.5.11    4am-nod
e12   <none>           <none>
fouram-tag-no-clean-vhk4f-1-milvus-rootcoord-65d7fb7ffb-tblzb    1/1     Running     0                109s    10.104.4.62    4am-nod
e11   <none>           <none>
fouram-tag-no-clean-vhk4f-1-minio-0                              1/1     Running     0                109s    10.104.1.189   4am-nod
e10   <none>           <none>
fouram-tag-no-clean-vhk4f-1-minio-1                              1/1     Running     0                109s    10.104.9.35    4am-nod
e14   <none>           <none>
fouram-tag-no-clean-vhk4f-1-minio-2                              1/1     Running     0                109s    10.104.6.20    4am-nod
e13   <none>           <none>
fouram-tag-no-clean-vhk4f-1-minio-3                              1/1     Running     0                108s    10.104.4.65    4am-nod
e11   <none>           <none>
fouram-tag-no-clean-vhk4f-1-zookeeper-0                          1/1     Running     0                109s    10.104.9.36    4am-nod
e14   <none>           <none>
fouram-tag-no-clean-vhk4f-1-zookeeper-1                          1/1     Running     0                109s    10.104.6.21    4am-nod
e13   <none>           <none>
fouram-tag-no-clean-vhk4f-1-zookeeper-2                          1/1     Running     0                109s    10.104.5.12    4am-nod
e12   <none>           <none>
```

2. update image. with Migration Tools 
update image to 
master-20221031-d0de1028

3. uninstall and reinstall milvus support diskann
milvus server：
```

fouram-tag-no-clean-vhk4f-1-etcd-0                               1/1     Running            0                112s    10.104.6.31    4am-node13   <none>           <none>
fouram-tag-no-clean-vhk4f-1-etcd-1                               1/1     Running            0                112s    10.104.9.58    4am-node14   <none>           <none>
fouram-tag-no-clean-vhk4f-1-etcd-2                               1/1     Running            0                112s    10.104.1.196   4am-node10   <none>           <none>
fouram-tag-no-clean-vhk4f-1-kafka-0                              1/1     Running            2 (80s ago)      112s    10.104.9.59    4am-node14   <none>           <none>
fouram-tag-no-clean-vhk4f-1-kafka-1                              1/1     Running            0                80s     10.104.6.35    4am-node13   <none>           <none>
fouram-tag-no-clean-vhk4f-1-kafka-2                              1/1     Running            0                80s     10.104.5.35    4am-node12   <none>           <none>
fouram-tag-no-clean-vhk4f-1-milvus-datacoord-559dcf8c7f-vct4q    1/1     Running            0                112s    10.104.5.32    4am-node12   <none>           <none>
fouram-tag-no-clean-vhk4f-1-milvus-datanode-9c56c56f6-pzrfv      1/1     Running            0                112s    10.104.9.56    4am-node14   <none>           <none>
fouram-tag-no-clean-vhk4f-1-milvus-indexcoord-66558f785c-85d56   1/1     Running            0                112s    10.104.5.30    4am-node12   <none>           <none>
fouram-tag-no-clean-vhk4f-1-milvus-indexnode-7d4558448d-mdqpr    1/1     Running            0                112s    10.104.5.33    4am-node12   <none>           <none>
fouram-tag-no-clean-vhk4f-1-milvus-proxy-db7c4b8c5-x7rnv         1/1     Running            0                112s    10.104.6.32    4am-node13   <none>           <none>
fouram-tag-no-clean-vhk4f-1-milvus-querycoord-8f8445458-c6nbx    1/1     Running            0                112s    10.104.5.29    4am-node12   <none>           <none>
fouram-tag-no-clean-vhk4f-1-milvus-querynode-c6c9c4c74-rc4zb     1/1     Running            0                112s    10.104.5.31    4am-node12   <none>           <none>
fouram-tag-no-clean-vhk4f-1-milvus-rootcoord-594f5f4d46-2fr7p    1/1     Running            0                112s    10.104.5.28    4am-node12   <none>           <none>
fouram-tag-no-clean-vhk4f-1-minio-0                              1/1     Running            0                112s    10.104.1.195   4am-node10   <none>           <none>
fouram-tag-no-clean-vhk4f-1-minio-1                              1/1     Running            0                112s    10.104.9.57    4am-node14   <none>           <none>
fouram-tag-no-clean-vhk4f-1-minio-2                              1/1     Running            0                112s    10.104.6.33    4am-node13   <none>           <none>
fouram-tag-no-clean-vhk4f-1-minio-3                              1/1     Running            0                112s    10.104.4.73    4am-node11   <none>           <none>
fouram-tag-no-clean-vhk4f-1-zookeeper-0                          1/1     Running            0                112s    10.104.5.34    4am-node12   <none>           <none>
fouram-tag-no-clean-vhk4f-1-zookeeper-1                          1/1     Running            0                112s    10.104.6.34    4am-node13   <none>           <none>
fouram-tag-no-clean-vhk4f-1-zookeeper-2                          1/1     Running            0                112s    10.104.9.60    4am-node14   <none>           <none>
```
5. rebuild diskann index failed:

```
[2022-10-31 15:19:33,736] [ WARNING] - [get_env_variable] GO_PLAY failed to get environment variables : 'GO_PLAY', use default value :  (milvus_benchmark.utils:443)
[2022-10-31 15:19:33,737] [    INFO] - Prepare to run cases (milvus_benchmark.main:86)
[2022-10-31 15:19:33,742] [   DEBUG] - Row count: 1000000 in collection: <sift_1m_128_l2> (milvus_benchmark.client:520)
[2022-10-31 15:19:33,743] [   DEBUG] - 1000000 (milvus_benchmark.runners.locust:850)
[2022-10-31 15:19:33,744] [    INFO] - None (milvus_benchmark.client:313)
[2022-10-31 15:19:33,744] [   DEBUG] - {'index_type': 'flat', 'metric_type': None, 'index_param': None} (milvus_benchmark.runners.locust:851)
[2022-10-31 15:19:33,744] [   DEBUG] - start release collection. (milvus_benchmark.runners.locust:852)
[2022-10-31 15:19:35,154] [   DEBUG] - Milvus release_collection run in 1.4093s (milvus_benchmark.client:57)
[2022-10-31 15:19:35,154] [   DEBUG] - start drop index. (milvus_benchmark.runners.locust:854)
[2022-10-31 15:19:35,154] [    INFO] - Drop index: sift_1m_128_l2 (milvus_benchmark.client:325)
[2022-10-31 15:19:35,156] [   DEBUG] - Start rebuild index. (milvus_benchmark.runners.locust:857)
[2022-10-31 15:19:35,156] [    INFO] - Building index start, collection_name: sift_1m_128_l2, index_type: DISKANN, metric_type: L2 (milvus_benchmark.client:295)
[2022-10-31 15:19:35,156] [   DEBUG] - collection: sift_1m_128_l2 Index params: {'index_type': 'DISKANN', 'metric_type': 'L2', 'params': {}} (milvus_benchmark.client:304)
[2022-10-31 15:19:35,159] [   ERROR] - RPC error: [create_index], <MilvusException: (code=1, message=CreateIndex failed: at most one distinct index is allowed per field)>, <Time:{'RPC start': '2022-10-31 15:19:35.156995', 'RPC error': '2022-10-31 15:19:35.159778'}> (pymilvus.decorators:108)
[2022-10-31 15:19:35,159] [   ERROR] - <MilvusException: (code=1, message=CreateIndex failed: at most one distinct index is allowed per field)> (milvus_benchmark.main:118)
[2022-10-31 15:19:35,160] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 87, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/locust.py", line 859, in prepare
    self.milvus.create_index(index_field_name, case_param["index_type"], case_param["metric_type"], index_param=case_param["index_param"])
  File "/src/milvus_benchmark/client.py", line 53, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 305, in create_index
    res = self._milvus.create_index(tmp_collection_name, field_name, index_params, _async=_async)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/stub.py", line 632, in create_index
    return handler.create_index(collection_name, field_name, params, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 563, in create_index
    raise MilvusException(status.error_code, status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=CreateIndex failed: at most one distinct index is allowed per field)>
```

### Steps To Reproduce

```markdown
1. create an collection
2. build hnsw index
3. insert 1m data
4. build index again
6. load,search,query,scence_test
7. update image with migration tool
8. uninstall and reinstall milvus support diskann
9.release collection,drop index,rebuild index failed
```

### Anything else?

milvus sever:
```
{
	"config.yaml": "server:
		  server_tag: \"8c64m\"
		milvus:
		  deploy_mode: \"cluster\"
		server_resource:
		  pulsar:
		    enabled: false
		  kafka:
		    enabled: true
		"
}
```
milvus reinstall after：

```
{
	"config.yaml": "server:
		  server_tag: \"8c64m\"
		milvus:
		  deploy_mode: \"cluster\"
		server_resource:
		  indexNode:
		    resources:
		      limits:
		        ephemeral-storage: 256Gi
		    disk:
		      enabled: true
		      size:
		        enabled: true
		  queryNode:
		    resources:
		      limits:
		        ephemeral-storage: 256Gi
		    disk:
		      enabled: true
		      size:
		        enabled: true
		  pulsar:
		    enabled: false
		  kafka:
		    enabled: true
		"
}
```

**Comment by xiaocai2333** [comment]
please use pymilvus==2.2.0.dev70
/assign @jingkl

**Comment by jingkl** [comment]
Keep upgrading without problems, turn off issue first
