### ISSUE TITLE
[Bug]: [Nightly]Load balance failed reporting 'failed to balance segments, err=ConflictTaskExisted'

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#20248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:29f2ed6
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0.dev69
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Load balance failed reporting 'failed to balance segments, err=ConflictTaskExisted'.
```
[2022-11-01T19:19:18.592Z] [2022-11-01 18:54:56 - ERROR - pymilvus.decorators]: RPC error: [load_balance], <MilvusException: (code=1, message=failed to balance segments, err=ConflictTaskExisted)>, <Time:{'RPC start': '2022-11-01 18:54:56.610234', 'RPC error': '2022-11-01 18:54:56.611669'}> (decorators.py:108)
[2022-11-01T19:19:18.592Z] [2022-11-01 18:54:56 - ERROR - ci_test]: Traceback (most recent call last):
[2022-11-01T19:19:18.592Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2022-11-01T19:19:18.592Z]     res = func(*args, **_kwargs)
[2022-11-01T19:19:18.592Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2022-11-01T19:19:18.592Z]     return func(*arg, **kwargs)
[2022-11-01T19:19:18.592Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/utility.py", line 470, in load_balance
[2022-11-01T19:19:18.592Z]     return _get_connection(using).\
[2022-11-01T19:19:18.592Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2022-11-01T19:19:18.592Z]     raise e
[2022-11-01T19:19:18.592Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2022-11-01T19:19:18.592Z]     return func(*args, **kwargs)
[2022-11-01T19:19:18.592Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2022-11-01T19:19:18.592Z]     ret = func(self, *args, **kwargs)
[2022-11-01T19:19:18.592Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
[2022-11-01T19:19:18.592Z]     raise e
[2022-11-01T19:19:18.592Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2022-11-01T19:19:18.593Z]     return func(self, *args, **kwargs)
[2022-11-01T19:19:18.593Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 947, in load_balance
[2022-11-01T19:19:18.593Z]     raise MilvusException(status.error_code, status.reason)
[2022-11-01T19:19:18.593Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=failed to balance segments, err=ConflictTaskExisted)>
[2022-11-01T19:19:18.593Z]  (api_request.py:39)
[2022-11-01T19:19:18.593Z] [2022-11-01 18:54:56 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=failed to balance segments, err=ConflictTaskExisted)> (api_request.py:40)
```

### Expected Behavior

PASS

### Steps To Reproduce

nightly: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/180/pipeline/155

### Milvus Log

1. log: [artifacts-milvus-distributed-kafka-nightly-180-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/180/artifact/artifacts-milvus-distributed-kafka-nightly-180-pymilvus-e2e-logs.tar.gz)
2. collection name: utility_gTAufz26
3. failed time: [2022-11-01T18:54:57.220Z] [gw4] [ 97%] FAILED testcases/test_utility.py::TestUtilityAdvanced::test_load_balance_normal

**Comment by NicoYuan1986** [comment]
Latest: https://jenkins.milvus.io:18080/blue/rest/organizations/jenkins/pipelines/Milvus%20Nightly%20CI/branches/master/runs/181/nodes/187/steps/207/log/?start=0

milvus: 3ac87fe
pymilvus: 2.2.0.dev69

1. log: [artifacts-milvus-distributed-pulsar-nightly-181-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/181/artifact/artifacts-milvus-distributed-pulsar-nightly-181-pymilvus-e2e-logs.tar.gz)
2. collection name: utility_SFdNyU6F
3. failed time: [2022-11-02T18:48:53.534Z] [gw5] [ 98%] FAILED testcases/test_utility.py::TestUtilityAdvanced::test_load_balance_normal

**Comment by NicoYuan1986** [comment]
Latest: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/182/pipeline/155

milvus: f557af1
pymilvus: 2.2.0.dev71

1. log: [artifacts-milvus-distributed-kafka-nightly-182-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/182/artifact/artifacts-milvus-distributed-kafka-nightly-182-pymilvus-e2e-logs.tar.gz)
2. collection name: utility_NPEYDwum
3. failed time: [2022-11-03T18:55:05.479Z] [gw4] [ 97%] FAILED testcases/test_utility.py::TestUtilityAdvanced::test_load_balance_normal

**Comment by NicoYuan1986** [comment]
Latest: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/185/pipeline/123

milvus: 4a66965
pymilvus: 2.2.0.dev71

1. log: [artifacts-milvus-distributed-kafka-nightly-185-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/185/artifact/artifacts-milvus-distributed-kafka-nightly-185-pymilvus-e2e-logs.tar.gz)
2. collection name: utility_qqOcscrI
3. failed time: [2022-11-06T18:55:27.027Z] [gw2] [ 97%] FAILED testcases/test_utility.py::TestUtilityAdvanced::test_load_balance_normal

**Comment by xige-16** [comment]
@jiaoew1991  please help/

**Comment by yah01** [comment]
/assign @NicoYuan1986 
plz retry with #20364, #20370 at 2.2.0 as well

**Comment by NicoYuan1986** [comment]
Fixed. milvus: c5cd92d

**Comment by NicoYuan1986** [comment]
Reproduce!
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/217/pipeline/187/

milvus: abc2adb
pymilvus: 2.3.0.dev15

1. log: [artifacts-milvus-distributed-pulsar-nightly-217-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/217/artifact/artifacts-milvus-distributed-pulsar-nightly-217-pymilvus-e2e-logs.tar.gz)
2. collection name: utility_6dkzbW8w
3. failed time: [2022-12-11T18:57:10.939Z] [gw3] [ 98%] FAILED testcases/test_utility.py::TestUtilityAdvanced::test_load_balance_normal

**Comment by yah01** [comment]
https://github.com/milvus-io/milvus/pull/20851 brings this issue back, auto-balance tasks can't be with high priority
/assign @SimFG

**Comment by yah01** [comment]
Task priority should be determined following:
- High for channel related tasks
- High for lacks of segments
- High for manual balance
- Normal for redundancies of segments
- Low for auto-balance segments

**Comment by SimFG** [comment]
@yah01#20851 this pr is merged in the last week. I think the issue isn't related by the pr.

**Comment by SimFG** [comment]
@yah01 If one query node will be offline, the data in the query node will be balanced to other nodes firstly. Otherwise, this query node will stop for a long time.

**Comment by NicoYuan1986** [comment]
Latest: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/38/pipeline/124/

milvus: 2.2.0(1aa7a9a)
pymilvus: 2.2.1.dev5

1. log: [artifacts-milvus-distributed-kafka-nightly-38-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/38/artifact/artifacts-milvus-distributed-kafka-nightly-38-pymilvus-e2e-logs.tar.gz)
2. collection name: utility_wqlLLfRg
3. faile time: [2022-12-18T20:56:21.487Z] [gw2] [ 97%] FAILED testcases/test_utility.py::TestUtilityAdvanced::test_load_balance_normal

**Comment by SimFG** [comment]
@NicoYuan1986 When you are stopping one query node, we can't support to balance the stopping node.

**Comment by yah01** [comment]
> @NicoYuan1986 When you are stopping one query node, we can't support to balance the stopping node.

We need a better error message, like "failed to balance due to the source/destination node is stopping"

**Comment by NicoYuan1986** [comment]
The error message still unchanged.
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/47/pipeline/124/

milvus: 2.2.0(d751044)
pymilvus: 2.2.1.dev5

1. log: [artifacts-milvus-distributed-kafka-nightly-47-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/47/artifact/artifacts-milvus-distributed-kafka-nightly-47-pymilvus-e2e-logs.tar.gz)
2. collection name: utility_yLXGV7OO
3. failed time: [2022-12-28T20:58:09.779Z] [gw1] [ 97%] FAILED testcases/test_utility.py::TestUtilityAdvanced::test_load_balance_normal

**Comment by NicoYuan1986** [comment]
The error reproduced frequently these days.
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/59/pipeline/124

milvus: 2.2.0(7154b53)
pymilvus: 2.2.1.dev5

1. log: [artifacts-milvus-distributed-kafka-nightly-59-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/59/artifact/artifacts-milvus-distributed-kafka-nightly-59-pymilvus-e2e-logs.tar.gz)
2. collection name: utility_6HOvvaNg
3. failed time: [2023-01-09T20:57:32.609Z] [gw4] [ 98%] FAILED testcases/test_utility.py::TestUtilityAdvanced::test_load_balance_normal

**Comment by SimFG** [comment]
I think it's not same from the error message
@NicoYuan1986 
![image](https://user-images.githubusercontent.com/21985684/211524743-60c77a33-08a8-4b81-9c7d-1a7835097d2b.png)

**Comment by NicoYuan1986** [comment]
> I think it's not same from the error message @NicoYuan1986 ![image](https://user-images.githubusercontent.com/21985684/211524743-60c77a33-08a8-4b81-9c7d-1a7835097d2b.png)

Yes! I'll close this issue and report the error in another.

**Comment by NicoYuan1986** [comment]
The issue reproduced in 2.2 branch.

milvus: a8a7186
pymilvus: 2.2.2.dev3

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/89/pipeline/188/
2. log: [artifacts-milvus-distributed-pulsar-nightly-89-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/89/artifact/artifacts-milvus-distributed-pulsar-nightly-89-pymilvus-e2e-logs.tar.gz)
3. collection name: utility_SYitUIx3
4. failed time: [2023-02-07T20:55:05.794Z] [gw2] [ 96%] FAILED testcases/test_utility.py::TestUtilityAdvanced::test_load_balance_normal
5. error message: 
```
[2023-02-07T21:26:27.221Z] [2023-02-07 20:55:04 - ERROR - pymilvus.decorators]: RPC error: [load_balance], <MilvusException: (code=1, message=failed to balance segments, err=ConflictTaskExisted)>, <Time:{'RPC start': '2023-02-07 20:55:04.965800', 'RPC error': '2023-02-07 20:55:04.967024'}> (decorators.py:108)
[2023-02-07T21:26:27.221Z] [2023-02-07 20:55:04 - ERROR - ci_test]: Traceback (most recent call last):
[2023-02-07T21:26:27.221Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2023-02-07T21:26:27.221Z]     res = func(*args, **_kwargs)
[2023-02-07T21:26:27.221Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2023-02-07T21:26:27.221Z]     return func(*arg, **kwargs)
[2023-02-07T21:26:27.221Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/utility.py", line 508, in load_balance
[2023-02-07T21:26:27.221Z]     return _get_connection(using).\
[2023-02-07T21:26:27.221Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2023-02-07T21:26:27.221Z]     raise e
[2023-02-07T21:26:27.221Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2023-02-07T21:26:27.221Z]     return func(*args, **kwargs)
[2023-02-07T21:26:27.221Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2023-02-07T21:26:27.221Z]     ret = func(self, *args, **kwargs)
[2023-02-07T21:26:27.221Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
[2023-02-07T21:26:27.221Z]     raise e
[2023-02-07T21:26:27.221Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2023-02-07T21:26:27.221Z]     return func(self, *args, **kwargs)
[2023-02-07T21:26:27.221Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 950, in load_balance
[2023-02-07T21:26:27.221Z]     raise MilvusException(status.error_code, status.reason)
[2023-02-07T21:26:27.221Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=failed to balance segments, err=ConflictTaskExisted)>
[2023-02-07T21:26:27.221Z]  (api_request.py:39)
[2023-02-07T21:26:27.221Z] [2023-02-07 20:55:04 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=failed to balance segments, err=ConflictTaskExisted)> (api_request.py:40)
```
