### ISSUE TITLE
[Bug]: [Nightly]Load collection failed with error message 'wait for loading collection timeout'

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#20247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:29f2ed6
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0.dev69
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Load collection failed with error message 'wait for loading collection timeout'.
```
[2022-11-01T19:19:18.324Z] [2022-11-01 18:24:02 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=wait for loading collection timeout, collection: search_collection_3HtD3MeA)>, <Time:{'RPC start': '2022-11-01 18:23:42.234751', 'RPC error': '2022-11-01 18:24:02.314642'}> (decorators.py:108)
[2022-11-01T19:19:18.324Z] [2022-11-01 18:24:02 - WARNING - pymilvus.decorators]: [93mRetry timeout: 20s[0m (decorators.py:79)
[2022-11-01T19:19:18.324Z] [2022-11-01 18:24:02 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry timeout: 20s, message=wait for loading collection timeout, collection: search_collection_3HtD3MeA)>, <Time:{'RPC start': '2022-11-01 18:23:42.222611', 'RPC error': '2022-11-01 18:24:02.315429'}> (decorators.py:108)
[2022-11-01T19:19:18.324Z] [2022-11-01 18:24:02 - ERROR - ci_test]: Traceback (most recent call last):
[2022-11-01T19:19:18.324Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2022-11-01T19:19:18.324Z]     return func(self, *args, **kwargs)
[2022-11-01T19:19:18.324Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 668, in load_collection
[2022-11-01T19:19:18.324Z]     self.wait_for_loading_collection(collection_name, timeout)
[2022-11-01T19:19:18.324Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2022-11-01T19:19:18.324Z]     raise e
[2022-11-01T19:19:18.324Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2022-11-01T19:19:18.324Z]     return func(*args, **kwargs)
[2022-11-01T19:19:18.324Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2022-11-01T19:19:18.324Z]     ret = func(self, *args, **kwargs)
[2022-11-01T19:19:18.324Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
[2022-11-01T19:19:18.324Z]     raise e
[2022-11-01T19:19:18.324Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2022-11-01T19:19:18.324Z]     return func(self, *args, **kwargs)
[2022-11-01T19:19:18.324Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 690, in wait_for_loading_collection
[2022-11-01T19:19:18.325Z]     raise MilvusException(message=f"wait for loading collection timeout, collection: {collection_name}")
[2022-11-01T19:19:18.325Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=wait for loading collection timeout, collection: search_collection_3HtD3MeA)>
[2022-11-01T19:19:18.325Z] 
[2022-11-01T19:19:18.325Z] The above exception was the direct cause of the following exception:
[2022-11-01T19:19:18.325Z] 
[2022-11-01T19:19:18.325Z] Traceback (most recent call last):
[2022-11-01T19:19:18.325Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2022-11-01T19:19:18.325Z]     res = func(*args, **_kwargs)
[2022-11-01T19:19:18.325Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2022-11-01T19:19:18.325Z]     return func(*arg, **kwargs)
[2022-11-01T19:19:18.325Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 476, in load
[2022-11-01T19:19:18.325Z]     conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
[2022-11-01T19:19:18.325Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2022-11-01T19:19:18.325Z]     raise e
[2022-11-01T19:19:18.325Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2022-11-01T19:19:18.325Z]     return func(*args, **kwargs)
[2022-11-01T19:19:18.325Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2022-11-01T19:19:18.325Z]     ret = func(self, *args, **kwargs)
[2022-11-01T19:19:18.325Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 80, in handler
[2022-11-01T19:19:18.325Z]     raise MilvusException(e.code, f"{timeout_msg}, message={e.message}") from e
[2022-11-01T19:19:18.325Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 20s, message=wait for loading collection timeout, collection: search_collection_3HtD3MeA)>
[2022-11-01T19:19:18.325Z]  (api_request.py:39)
[2022-11-01T19:19:18.325Z] [2022-11-01 18:24:02 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 20s, message=wait for loading collection timeout, collection: search_collection_3HtD3MeA)> (api_request.py:40)
```

### Expected Behavior

PASS

### Steps To Reproduce

nightly: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/180/pipeline/155

### Milvus Log

1. log: [artifacts-milvus-distributed-kafka-nightly-180-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/180/artifact/artifacts-milvus-distributed-kafka-nightly-180-pymilvus-e2e-logs.tar.gz)
2. collection name: search_collection_3HtD3MeA
3. failed time: [2022-11-01T18:24:02.638Z] [gw4] [ 51%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_collection_after_release_load[5000-2-8-True-False]

**Comment by binbinlv** [comment]
From results of last nightly, this issue only appears in kafka pipeline, so @jaime0815  could you help to have a look first? Thanks.

**Comment by NicoYuan1986** [comment]
The error also occurs in pulsar from the latest nightly report.
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/182/pipeline/187

milvus: f557af1
pymilvus: 2.2.0.dev71

1. log: [artifacts-milvus-distributed-pulsar-nightly-182-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/182/artifact/artifacts-milvus-distributed-pulsar-nightly-182-pymilvus-e2e-logs.tar.gz)
2. collection name: search_collection_Av7o6jLY
3. failed time: [2022-11-03T18:10:03.208Z] [gw2] [ 27%] FAILED testcases/test_search.py::TestCollectionSearchInvalid::test_search_partition_deleted 

Also in kafka: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/182/pipeline/155

**Comment by NicoYuan1986** [comment]
From the latest nightly report: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/185/pipeline/155/

milvus: 4a66965
pymilvus: 2.2.0.dev71

1. log: [artifacts-milvus-standalone-nightly-185-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/185/artifact/artifacts-milvus-standalone-nightly-185-pymilvus-e2e-logs.tar.gz)
2. collection name: search_collection_v363ztlX
3. failed timeline: [2022-11-06T18:08:23.403Z] [gw4] [ 27%] FAILED testcases/test_search.py::TestCollectionSearchInvalid::test_search_partition_deleted

Also in kafka: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/185/pipeline/123

**Comment by NicoYuan1986** [comment]
The latest: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/186/pipeline/155/

milvus: c5cd92d
pymilvus: 2.2.0.dev71

1. log: [artifacts-milvus-distributed-kafka-nightly-186-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/186/artifact/artifacts-milvus-distributed-kafka-nightly-186-pymilvus-e2e-logs.tar.gz)
2. FAILED cases:
TestCollectionSearchInvalid.test_search_different_index_invalid_params[IVF_SQ8-params1]
TestCollectionSearch.test_search_collection_after_release_load[3000-2-128-True-False]
TestCollectionSearchInvalid.test_search_param_invalid_dim
TestCollectionSearch.test_search_after_different_index_with_params[8-True-False-ANNOY-params5]
TestCollectionSearch.test_search_HNSW_index_with_max_ef[False-True-8-4]
TestCollectionSearch.test_search_after_different_index_with_params[128-False-False-IVF_FLAT-params1]
TestCollectionSearch.test_search_after_different_index_with_params[128-False-True-IVF_FLAT-params1]
TestCollectionSearch.test_search_index_partitions_fuzzy[3000-500-128-True-False-partition_names0]
TestCollectionSearch.test_search_after_index_different_metric_type[8-True-True-IVF_SQ8-params2]
TestsearchPagination.test_search_pagination_empty[10-8-False-False]
TestsearchPagination.test_search_pagination_after_different_index[True-10-True-IVF_FLAT-params1]

**Comment by NicoYuan1986** [comment]
Latest: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/187/pipeline/155

milvus: a2bf502
pymilvus: 2.2.0.dev72

1. log: [artifacts-milvus-distributed-kafka-nightly-187-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/187/artifact/artifacts-milvus-distributed-kafka-nightly-187-pymilvus-e2e-logs.tar.gz)
2. collection name: search_collection_K515wZhW
3. failed time: [2022-11-08T18:15:51.580Z] [gw3] [ 40%] FAILED testcases/test_search.py::TestCollectionSearchInvalid::test_search_param_invalid_expr_bool[get_invalid_expr_bool_value0]

**Comment by jaime0815** [comment]
related to  #19633

**Comment by NicoYuan1986** [comment]
The issue has disappeared in master branch for 1 week, but not for 2.2 branch.
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/5/pipeline/155/

milvus: 2.2.0(b4af870)
pymilvus: 2.2.0.dev71

log: [artifacts-milvus-distributed-kafka-nightly-5-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/5/artifact/artifacts-milvus-distributed-kafka-nightly-5-pymilvus-e2e-logs.tar.gz)

**Comment by NicoYuan1986** [comment]
Latest: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/9/pipeline/155

milvus: efa1cf7
pymilvus: 2.2.0.dev71

1. log: [artifacts-milvus-distributed-kafka-nightly-9-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/9/artifact/artifacts-milvus-distributed-kafka-nightly-9-pymilvus-e2e-logs.tar.gz)
2. collection name: index_jnW0sDOC
3. FAILED timeline: [2022-11-21T20:11:17.070Z] [gw4] [ 29%] FAILED testcases/test_index.py::TestIndexDiskann::test_drop_diskann_index_with_partition

**Comment by NicoYuan1986** [comment]
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/10/pipeline/187

milvus: 2.2.0(89bdb34)
pymilvus: 2.2.0.dev71

log: [artifacts-milvus-distributed-pulsar-nightly-10-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/10/artifact/artifacts-milvus-distributed-pulsar-nightly-10-pymilvus-e2e-logs.tar.gz)

**Comment by jaime0815** [comment]
> https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/9/pipeline/155

load collection fail
```
[2022/11/21 20:11:49.267 +00:00] [WARN] [task/executor.go:175] ["failed to load segment"] [taskIDs="[1711]"] [collectionID=437534261946403769] [shard=by-dev-rootcoord-dml_71_437534261946403769v0] [segmentIDs="[437534261946403802]"] [nodeID=2] [source=2] [reason="follower 2 failed to load segment, reason target node id not match target id = 2, node id = 13"]Show context
[2022/11/21 20:11:49.267 +00:00] [WARN] [querynode/impl_utils.go:30] ["shard cluster failed to load segments"] [shard=by-dev-rootcoord-dml_71_437534261946403769v0] [error="follower 2 failed to load segment, reason target node id not match target id = 2, node id = 13"]
[2022/11/21 20:11:49.267 +00:00] [WARN] [querynode/shard_cluster.go:651] ["follower load segment failed"] [collectionID=437534261946403769] [channel=by-dev-rootcoord-dml_71_437534261946403769v0] [replicaID=437534278481871070] [dstNodeID=2] [segmentIDs="[437534261946403802]"] [reason="target node id not match target id = 2, node id = 13"]
[2022/11/21 20:11:49.266 +00:00] [INFO] [task/executor.go:168] ["load segments..."] [taskIDs="[1711]"] [collectionID=437534261946403769] [shard=by-dev-rootcoord-dml_71_437534261946403769v0] [segmentIDs="[437534261946403802]"] [nodeID=2] [source=2]

```

**Comment by NicoYuan1986** [comment]
Latest: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/203/pipeline/187

milvus: f588a73
pymilvus: 2.3.0.dev15

1. log: [artifacts-milvus-distributed-pulsar-nightly-203-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/203/artifact/artifacts-milvus-distributed-pulsar-nightly-203-pymilvus-e2e-logs.tar.gz)
2. collection name: search_collection_FJeAQXCd

**Comment by jaime0815** [comment]
> Latest: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/203/pipeline/187
> 
> milvus: [f588a73](https://github.com/milvus-io/milvus/commit/f588a73719378f532734143b72fcca383eed2eca) pymilvus: 2.3.0.dev15
> 
> 1. log: [artifacts-milvus-distributed-pulsar-nightly-203-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/203/artifact/artifacts-milvus-distributed-pulsar-nightly-203-pymilvus-e2e-logs.tar.gz)
> 2. collection name: search_collection_FJeAQXCd

relate to #20869

**Comment by NicoYuan1986** [comment]
Keep occurring on 2.2 branch.
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/16/pipeline/155
[artifacts-milvus-distributed-kafka-nightly-16-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/16/artifact/artifacts-milvus-distributed-kafka-nightly-16-pymilvus-e2e-logs.tar.gz)

**Comment by jaime0815** [comment]
> > https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/9/pipeline/155
> 
> load collection fail
> 
> ```
> [2022/11/21 20:11:49.267 +00:00] [WARN] [task/executor.go:175] ["failed to load segment"] [taskIDs="[1711]"] [collectionID=437534261946403769] [shard=by-dev-rootcoord-dml_71_437534261946403769v0] [segmentIDs="[437534261946403802]"] [nodeID=2] [source=2] [reason="follower 2 failed to load segment, reason target node id not match target id = 2, node id = 13"]Show context
> [2022/11/21 20:11:49.267 +00:00] [WARN] [querynode/impl_utils.go:30] ["shard cluster failed to load segments"] [shard=by-dev-rootcoord-dml_71_437534261946403769v0] [error="follower 2 failed to load segment, reason target node id not match target id = 2, node id = 13"]
> [2022/11/21 20:11:49.267 +00:00] [WARN] [querynode/shard_cluster.go:651] ["follower load segment failed"] [collectionID=437534261946403769] [channel=by-dev-rootcoord-dml_71_437534261946403769v0] [replicaID=437534278481871070] [dstNodeID=2] [segmentIDs="[437534261946403802]"] [reason="target node id not match target id = 2, node id = 13"]
> [2022/11/21 20:11:49.266 +00:00] [INFO] [task/executor.go:168] ["load segments..."] [taskIDs="[1711]"] [collectionID=437534261946403769] [shard=by-dev-rootcoord-dml_71_437534261946403769v0] [segmentIDs="[437534261946403802]"] [nodeID=2] [source=2]
> ```

querynode process exit with an unexpected signal when starting to search a segment, it seems occurs core dump within segcore or knowhere and there is no more log to troubleshoot this issue.

please help take a look at this diskann issue. @xige-16 

```
2022-11-22T03:59:07.978754402+08:00 stdout F [2022/11/21 19:59:07.978 +00:00] [INFO] [querynode/query_node.go:154] ["QueryNode init session"] [nodeID=2] ["node address"=10.105.1.166:21123]
2022-11-22T04:10:56.316945195+08:00 stdout F [2022/11/21 20:10:56.316 +00:00] [DEBUG] [querynode/validate.go:50] ["read target partitions"] [traceID=585036035f0f0c89] [collectionID=437534261946402248] [partitionIDs="[437534261946402249]"]
2022-11-22T04:10:56.316948491+08:00 stdout F [2022/11/21 20:10:56.316 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=437534446297022473] [segmentID=437534261946402326] [segmentType=3] [loadIndex=false]
2022-11-22T04:10:56.327851042+08:00 stderr F fatal error: unexpected signal during runtime execution
```

**Comment by jaime0815** [comment]
> 
related to #20878

**Comment by jaime0815** [comment]
> https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/16/pipeline/155
> [artifacts-milvus-distributed-kafka-nightly-16-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/16/artifact/artifacts-milvus-distributed-kafka-nightly-16-pymilvus-e2e-logs.tar.gz)

related to #20880

**Comment by jaime0815** [comment]
> Keep occurring on 2.2 branch. https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/16/pipeline/155 [artifacts-milvus-distributed-kafka-nightly-16-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/16/artifact/artifacts-milvus-distributed-kafka-nightly-16-pymilvus-e2e-logs.tar.gz)

relate to https://github.com/milvus-io/milvus/issues/20869

**Comment by NicoYuan1986** [comment]
keep happening
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/205/pipeline/187

**Comment by jaime0815** [comment]
#20869

> keep happening https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/205/pipeline/187

**Comment by NicoYuan1986** [comment]
Not appeared yesterday in both master and 2.2 branch.

**Comment by NicoYuan1986** [comment]
Latest: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/22/pipeline/136/

milvus: 2.2.0(90ca7e1)
pymilvus: 2.2.1.dev3

1. log: [artifacts-milvus-distributed-kafka-nightly-22-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/22/artifact/artifacts-milvus-distributed-kafka-nightly-22-pymilvus-e2e-logs.tar.gz)
2. collection name: search_collection_uTjhHvsl
3. failed time: [2022-12-04T20:30:53.498Z] [gw0] [ 59%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_after_different_index_with_params[32-False-True-DISKANN-params6]

**Comment by yanliang567** [comment]
sounds like an occasional issue, downgrade the priority

**Comment by NicoYuan1986** [comment]
Latest: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/24/pipeline/135

milvus: 2.2(7ea86ed)
pymilvus: 2.2.1.dev3

1. log: [artifacts-milvus-distributed-kafka-nightly-24-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/24/artifact/artifacts-milvus-distributed-kafka-nightly-24-pymilvus-e2e-logs.tar.gz)
2. collection name: search_collection_c55VM0qb
3. failed time: [2022-12-06T20:58:49.970Z] [gw4] [ 90%] FAILED testcases/test_search.py::TestsearchDiskann::test_search_invalid_params_with_diskann_C[128-False-6554-6554]

**Comment by NicoYuan1986** [comment]
Latest: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/214/pipeline/155
case: test_search_after_different_index_with_params[128-False-True-DISKANN-params6]

**Comment by NicoYuan1986** [comment]
Update: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/29/pipeline/187

milvus: 2.2.0(50c7a80)
pymilvus: 2.2.1.dev3

1. log: [artifacts-milvus-distributed-pulsar-nightly-29-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/29/artifact/artifacts-milvus-distributed-pulsar-nightly-29-pymilvus-e2e-logs.tar.gz)
2. collection name: search_collection_26UDxOHa
3. failed time: [2022-12-11T20:22:13.995Z] [gw4] [ 44%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_after_different_index_with_params[128-False-False-DISKANN-params6]

**Comment by yanliang567** [comment]
@NicoYuan1986 is it a valid issue on 2.2 branch?

**Comment by NicoYuan1986** [comment]
> @NicoYuan1986 is it a valid issue on 2.2 branch?

Yes.Not reproduced for these days.

**Comment by yanliang567** [comment]
close as comments above
