### ISSUE TITLE
[Bug]: [Nightly]Fail to search on all shard leaders, err=Channel: by-dev-rootcoord-dml_29_437079421052139892v1 returns err: fail to Search, QueryNode ID=2, reason=Search 2 failed, reason failed to get service timestamp

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#20251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:29f2ed6
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0.dev69
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Fail to search on all shard leaders, err=Channel: by-dev-rootcoord-dml_29_437079421052139892v1 returns err: fail to Search, QueryNode ID=2, reason=Search 2 failed, reason failed to get service timestamp.
```
[2022-11-01T19:16:32.430Z] [2022-11-01 18:05:24 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=Channel: by-dev-rootcoord-dml_29_437079421052139892v1 returns err: fail to Search, QueryNode ID=2, reason=Search 2 failed, reason failed to get service timestamp, taskID = 437079487092621313, collectionID = 437079421052139892, err=cannot found tSafer, vChannel = by-dev-rootcoord-delta_29_437079421052139892v1 err %!w(<nil>))>, <Time:{'RPC start': '2022-11-01 18:05:24.288254', 'RPC error': '2022-11-01 18:05:24.465950'}> (decorators.py:108)
[2022-11-01T19:16:32.430Z] [2022-11-01 18:05:24 - ERROR - ci_test]: Traceback (most recent call last):
[2022-11-01T19:16:32.430Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2022-11-01T19:16:32.430Z]     res = func(*args, **_kwargs)
[2022-11-01T19:16:32.430Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2022-11-01T19:16:32.430Z]     return func(*arg, **kwargs)
[2022-11-01T19:16:32.430Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 719, in search
[2022-11-01T19:16:32.430Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,
[2022-11-01T19:16:32.430Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2022-11-01T19:16:32.430Z]     raise e
[2022-11-01T19:16:32.430Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2022-11-01T19:16:32.430Z]     return func(*args, **kwargs)
[2022-11-01T19:16:32.430Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2022-11-01T19:16:32.430Z]     ret = func(self, *args, **kwargs)
[2022-11-01T19:16:32.430Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
[2022-11-01T19:16:32.430Z]     raise e
[2022-11-01T19:16:32.430Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2022-11-01T19:16:32.430Z]     return func(self, *args, **kwargs)
[2022-11-01T19:16:32.430Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 478, in search
[2022-11-01T19:16:32.430Z]     return self._execute_search_requests(requests, timeout, **_kwargs)
[2022-11-01T19:16:32.430Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 442, in _execute_search_requests
[2022-11-01T19:16:32.430Z]     raise pre_err
[2022-11-01T19:16:32.430Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 433, in _execute_search_requests
[2022-11-01T19:16:32.430Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2022-11-01T19:16:32.430Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=Channel: by-dev-rootcoord-dml_29_437079421052139892v1 returns err: fail to Search, QueryNode ID=2, reason=Search 2 failed, reason failed to get service timestamp, taskID = 437079487092621313, collectionID = 437079421052139892, err=cannot found tSafer, vChannel = by-dev-rootcoord-delta_29_437079421052139892v1 err %!w(<nil>))>
[2022-11-01T19:16:32.430Z]  (api_request.py:39)
[2022-11-01T19:16:32.430Z] [2022-11-01 18:05:24 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=Channel: by-dev-rootcoord-dml_29_437079421052139892v1 returns err: fail to Search, QueryNode ID=2, reason=Search 2 failed, reason failed to get service timestamp, taskID = 437079487092621313, collectionID = 43707942105213989...... (api_request.py:40)
```

### Expected Behavior

PASS

### Steps To Reproduce

```markdown
nightly: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/180/pipeline/187
```

### Milvus Log

1. log: [artifacts-milvus-distributed-pulsar-nightly-180-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/180/artifact/artifacts-milvus-distributed-pulsar-nightly-180-pymilvus-e2e-logs.tar.gz)
2. collection name: collection_FTf6fG8M
3. failed time: [2022-11-01T18:05:24.959Z] [gw3] [ 10%] FAILED testcases/test_collection.py::TestReleaseAdvanced::test_release_partition_during_searching

**Comment by NicoYuan1986** [comment]
Latest: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/185/pipeline/123/

milvus: 4a66965
pymilvus: 2.2.0.dev71

1. log: [artifacts-milvus-distributed-kafka-nightly-185-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/185/artifact/artifacts-milvus-distributed-kafka-nightly-185-pymilvus-e2e-logs.tar.gz)
2. collection name: collection_i1KPKssz
3. failed time: [2022-11-06T18:04:25.942Z] [gw3] [ 10%] FAILED testcases/test_collection.py::TestLoadCollection::test_load_replica_partitions
