### ISSUE TITLE
[Bug]: Datanode panic with error `:data service save bin log path failed, reason = etcdserver: too many operations in txn request` and can not be recovery after datanode pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#20275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20221102-fc7e7256
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2022/11/02 09:47:32.215 +00:00] [INFO] [datanode/data_node.go:351] ["DataNode received a PUT event with an end State"] [state=WatchSuccess]
[2022/11/02 09:47:32.215 +00:00] [INFO] [datanode/data_node.go:441] ["handle put event success"] [key=channelwatch/41/by-dev-rootcoord-dml_71_437094033995018902v1] [state=WatchSuccess] [vChanName=by-dev-rootcoord-dml_71_437094033995018902v1]
[2022/11/02 09:47:32.316 +00:00] [WARN] [datanode/flush_manager.go:844] ["failed to SaveBinlogPaths"] ["segment ID"=437094033995018761] [error="All attempts results:\nattempt #1:data service save bin log path failed, reason = etcdserver: too many operations in txn request\nattempt #2:data service save bin log path failed, reason = etcdserver: too many operations in txn request\nattempt #3:data service save bin log path failed, reason = etcdserver: too many operations in txn request\nattempt #4:data service save bin log path failed, reason = etcdserver: too many operations in txn request\nattempt #5:data service save bin log path failed, reason = etcdserver: too many operations in txn request\nattempt #6:data service save bin log path failed, reason = etcdserver: too many operations in txn request\nattempt #7:data service save bin log path failed, reason = etcdserver: too many operations in txn request\nattempt #8:data service save bin log path failed, reason = etcdserver: too many operations in txn request\nattempt #9:data service save bin log path failed, reason = etcdserver: too many operations in txn request\nattempt #10:data service save bin log path failed, reason = etcdserver: too many operations in txn request\n"]
panic: All attempts results:
attempt #1:data service save bin log path failed, reason = etcdserver: too many operations in txn request
attempt #2:data service save bin log path failed, reason = etcdserver: too many operations in txn request
attempt #3:data service save bin log path failed, reason = etcdserver: too many operations in txn request
attempt #4:data service save bin log path failed, reason = etcdserver: too many operations in txn request
attempt #5:data service save bin log path failed, reason = etcdserver: too many operations in txn request
attempt #6:data service save bin log path failed, reason = etcdserver: too many operations in txn request
attempt #7:data service save bin log path failed, reason = etcdserver: too many operations in txn request
attempt #8:data service save bin log path failed, reason = etcdserver: too many operations in txn request
attempt #9:data service save bin log path failed, reason = etcdserver: too many operations in txn request
attempt #10:data service save bin log path failed, reason = etcdserver: too many operations in txn request


goroutine 60449 [running]:
github.com/milvus-io/milvus/internal/datanode.flushNotifyFunc.func1(0xc0036a4af0)
	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_manager.go:848 +0x11a8
github.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).waitFinish(0xc001ecd2c0, 0xc0024ac150, 0xc0058f7560)
	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_task.go:201 +0xdb
created by github.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).init.func1
	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_task.go:119 +0xf1

```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/2681/pipeline

log:
[artifacts-datanode-pod-kill-2681-server-logs (2).tar.gz](https://github.com/milvus-io/milvus/files/9919283/artifacts-datanode-pod-kill-2681-server-logs.2.tar.gz)

[artifacts-datanode-pod-kill-2681-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9919284/artifacts-datanode-pod-kill-2681-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
Not reproduced yet!
