### ISSUE TITLE
[Bug]: [benchmark][diskann]Milvus  create diskann index with 768d 5m data, report an error"SyncTimestamp Failed:context canceled"

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#20337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20221103-f557af11
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0.dev70
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server-instance
fouram-qh47g-1
server-configmap
server-single-2c9m-diskann
client-configmap
client-diskann-locust-search-local5m
Milvus server:
```
NAME                                                     READY   STATUS    RESTARTS      AGE     IP             NODE         NOMINATED NODE   READINESS GATES
fouram-qh47g-1-etcd-0                                    1/1     Running   0             103s    10.104.1.139   4am-node10   <none>           <none>
fouram-qh47g-1-milvus-standalone-5c749b9cbf-vf4hc        1/1     Running   0             103s    10.104.5.209   4am-node12   <none>           <none>
fouram-qh47g-1-minio-56d64c975-79f5c                     1/1     Running   0             103s    10.104.1.137   4am-node10   <none>           <none>
```
Milvus client log:
```
[2022-11-04 04:18:51,817] [    INFO] - Building index start, collection_name: local_5m_768_l2, index_type: DISKANN, metric_type: L2 (milvus_benchmark.client:295)
[2022-11-04 04:18:51,817] [   DEBUG] - collection: local_5m_768_l2 Index params: {'index_type': 'DISKANN', 'metric_type': 'L2', 'params': {}} (milvus_benchmark.client:304)
[2022-11-04 08:24:16,353] [   ERROR] - RPC error: [get_index_state], <MilvusException: (code=1, message=syncTimestamp Failed:context canceled)>, <Time:{'RPC start': '2022-11-04 08:24:16.352458', 'RPC error': '2022-11-04 08:24:16.353679'}> (pymilvus.decorators:108)
[2022-11-04 08:24:16,354] [   ERROR] - RPC error: [wait_for_creating_index], <MilvusException: (code=1, message=syncTimestamp Failed:context canceled)>, <Time:{'RPC start': '2022-11-04 04:18:51.828105', 'RPC error': '2022-11-04 08:24:16.354354'}> (pymilvus.decorators:108)
[2022-11-04 08:24:16,354] [   ERROR] - RPC error: [create_index], <MilvusException: (code=1, message=syncTimestamp Failed:context canceled)>, <Time:{'RPC start': '2022-11-04 04:18:51.817971', 'RPC error': '2022-11-04 08:24:16.354563'}> (pymilvus.decorators:108)
[2022-11-04 08:24:16,354] [   ERROR] - <MilvusException: (code=1, message=syncTimestamp Failed:context canceled)> (milvus_benchmark.main:118)
[2022-11-04 08:24:16,355] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 87, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/locust.py", line 316, in prepare
    self.milvus.create_index(index_field_name, case_param["index_type"], case_param["metric_type"], index_param=case_param["index_param"])
  File "/src/milvus_benchmark/client.py", line 53, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 305, in create_index
    res = self._milvus.create_index(tmp_collection_name, field_name, index_params, _async=_async)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/stub.py", line 632, in create_index
    return handler.create_index(collection_name, field_name, params, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 566, in create_index
    index_success, fail_reason = self.wait_for_creating_index(collection_name=collection_name,
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 649, in wait_for_creating_index
    state, fail_reason = self.get_index_state(collection_name, index_name, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 630, in get_index_state
    raise MilvusException(status.error_code, status.reason)
```

### Steps To Reproduce

```markdown
1.create an collection
2. build diskann index
3. insert 5m 768d data
9. build index failed
```

**Comment by jingkl** [comment]
server-instance
fouram-67nnt-1
server-configmap
server-single-2c9m-diskann
client-configmap
client-autoindex-locust-search-sift25m
sever
```
NAME                                                     READY   STATUS    RESTARTS      AGE     IP             NODE         NOMINATED NODE   READINESS GATES
fouram-67nnt-1-etcd-0                                    1/1     Running   0             105s    10.104.9.50    4am-node14   <none>           <none>
fouram-67nnt-1-milvus-standalone-597f778bc7-fvk59        1/1     Running   0             105s    10.104.1.141   4am-node10   <none>           <none>
fouram-67nnt-1-minio-7df6ff76bb-jpfht                    1/1     Running   0             105s    10.104.9.45    4am-node14   <none>           <none>
```
log：
```
[2022-11-04 04:13:34,756] [   DEBUG] - collection: sift_25m_128_l2 Index params: {'index_type': 'DISKANN', 'metric_type': 'L2', 'params': {}} (milvus_benchmark.client:304)
[2022-11-04 08:23:17,077] [   ERROR] - RPC error: [get_index_state], <MilvusException: (code=1, message=syncTimestamp Failed:context canceled)>, <Time:{'RPC start': '2022-11-04 08:23:17.075698', 'RPC error': '2022-11-04 08:23:17.077143'}> (pymilvus.decorators:108)
[2022-11-04 08:23:17,077] [   ERROR] - RPC error: [wait_for_creating_index], <MilvusException: (code=1, message=syncTimestamp Failed:context canceled)>, <Time:{'RPC start': '2022-11-04 04:13:34.769796', 'RPC error': '2022-11-04 08:23:17.077807'}> (pymilvus.decorators:108)
[2022-11-04 08:23:17,078] [   ERROR] - RPC error: [create_index], <MilvusException: (code=1, message=syncTimestamp Failed:context canceled)>, <Time:{'RPC start': '2022-11-04 04:13:34.756944', 'RPC error': '2022-11-04 08:23:17.078023'}> (pymilvus.decorators:108)
[2022-11-04 08:23:17,078] [   ERROR] - <MilvusException: (code=1, message=syncTimestamp Failed:context canceled)> (milvus_benchmark.main:118)
[2022-11-04 08:23:17,089] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 87, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/locust.py", line 455, in prepare
    self.milvus.create_index(index_field_name, case_param["index_type"], case_param["metric_type"], index_param=case_param["index_param"])
  File "/src/milvus_benchmark/client.py", line 53, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 305, in create_index
    res = self._milvus.create_index(tmp_collection_name, field_name, index_params, _async=_async)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/stub.py", line 632, in create_index
    return handler.create_index(collection_name, field_name, params, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 566, in create_index
    index_success, fail_reason = self.wait_for_creating_index(collection_name=collection_name,
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 649, in wait_for_creating_index
    state, fail_reason = self.get_index_state(collection_name, index_name, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 630, in get_index_state
    raise MilvusException(status.error_code, status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=syncTimestamp Failed:context canceled)>
 (milvus_benchmark.main:119)
```

**Comment by jingkl** [comment]
The same index creation failure error occurs for sift 128d 2500w data

**Comment by xige-16** [comment]
syncTimestamp failed may be related to high cpu utilization

![fkVsOwX1om](https://user-images.githubusercontent.com/20124155/199940336-53cac24d-8a51-4a53-aca4-ee0add4b356d.png)

**Comment by xige-16** [comment]
This pr should alleviate the problem
 https://github.com/milvus-io/milvus/pull/20328/files

**Comment by jingkl** [comment]
server-instance
fouram-r8jbl-1
server-configmap
server-single-2c9m
client-configmap
client-diskann-locust-search-local5m
2.2.0-20221109-13dbc090
pymilvus 2.2.0.dev70
The issue of creating an index did not arise
