### ISSUE TITLE
[Bug]: querycoord crashed

### ISSUE THREAD

**Issue by haochun** [milvus-io/milvus#20340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.4
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS):  centos 7
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

querycoord crashed,the log:
```
[2022/11/04 09:06:09.489 +00:00] [WARN] [grpcclient/client.go:251] ["datacoord ClientBase ReCall grpc first call get error "] [error="err: rpc error: code = DeadlineExceeded desc = context deadline exceeded\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:250 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall\n/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:545 github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).ReleaseSegmentLock\n/go/src/github.com/milvus-io/milvus/internal/querycoord/global_meta_broker.go:533 github.com/milvus-io/milvus/internal/querycoord.(*globalMetaBroker).releaseSegmentReferLock.func1\n/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:37 github.com/milvus-io/milvus/internal/util/retry.Do\n/go/src/github.com/milvus-io/milvus/internal/querycoord/global_meta_broker.go:532 github.com/milvus-io/milvus/internal/querycoord.(*globalMetaBroker).releaseSegmentReferLock\n/go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:1401 github.com/milvus-io/milvus/internal/querycoord.(*loadSegmentTask).postExecute\n/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:565 github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processTask.func2\n/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:579 github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processTask\n/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:931 github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processActivateTaskLoop.func1\n"]
[2022/11/04 09:06:09.489 +00:00] [ERROR] [querycoord/global_meta_broker.go:535] ["QueryCoord release reference lock on segments failed"] [segmentIDs="[437122948269867009,437126742083371009,437129163441963009,437122711226155009,437130441433284609,437132226869854209,437123016453521409,437121243390148609]"] [error="context deadline exceeded"] [stack="github.com/milvus-io/milvus/internal/querycoord.(*globalMetaBroker).releaseSegmentReferLock.func1\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/global_meta_broker.go:535\ngithub.com/milvus-io/milvus/internal/util/retry.Do\n\t/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:37\ngithub.com/milvus-io/milvus/internal/querycoord.(*globalMetaBroker).releaseSegmentReferLock\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/global_meta_broker.go:532\ngithub.com/milvus-io/milvus/internal/querycoord.(*loadSegmentTask).postExecute\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:1401\ngithub.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processTask.func2\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:565\ngithub.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processTask\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:579\ngithub.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processActivateTaskLoop.func1\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:931"]
[2022/11/04 09:06:09.489 +00:00] [DEBUG] [retry/retry.go:39] ["retry func failed"] ["retry time"=0] [error="context deadline exceeded"]
[2022/11/04 09:06:09.489 +00:00] [WARN] [grpcclient/client.go:251] ["datacoord ClientBase ReCall grpc first call get error "] [error="err: rpc error: code = DeadlineExceeded desc = context deadline exceeded\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:250 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall\n/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:545 github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).ReleaseSegmentLock\n/go/src/github.com/milvus-io/milvus/internal/querycoord/global_meta_broker.go:533 github.com/milvus-io/milvus/internal/querycoord.(*globalMetaBroker).releaseSegmentReferLock.func1\n/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:37 github.com/milvus-io/milvus/internal/util/retry.Do\n/go/src/github.com/milvus-io/milvus/internal/querycoord/global_meta_broker.go:532 github.com/milvus-io/milvus/internal/querycoord.(*globalMetaBroker).releaseSegmentReferLock\n/go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:1401 github.com/milvus-io/milvus/internal/querycoord.(*loadSegmentTask).postExecute\n/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:565 github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processTask.func2\n/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:579 github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processTask\n/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:931 github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processActivateTaskLoop.func1\n"]
panic: All attempts results:
attempt #1:context deadline exceeded
attempt #2:context deadline exceeded


goroutine 455 [running]:
github.com/milvus-io/milvus/internal/querycoord.(*loadSegmentTask).postExecute(0xc0034db0e0, 0x43b7d10, 0xc003f15400, 0x1, 0x4007150)
        /go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:1402 +0x37c
github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processTask.func2(0x43dc120, 0xc010ceb200, 0x43f0740, 0xc0034db0e0, 0xc003d83b40)
        /go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:565 +0x126
github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processTask(0xc00077bd80, 0x43f0740, 0xc0034db0e0, 0x437ac20, 0xc00547e660)
        /go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:579 +0x8f8
github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processActivateTaskLoop.func1(0xc00077bd80, 0x43f0740, 0xc0034db0e0)
        /go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:931 +0x3f
created by github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processActivateTaskLoop
        /go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:930 +0x151
```

### Milvus Log

[2022/11/04 09:06:09.489 +00:00] [WARN] [grpcclient/client.go:251] ["datacoord ClientBase ReCall grpc first call get error "] [error="err: rpc error: code = DeadlineExceeded desc = context deadline exceeded\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:250 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall\n/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:545 github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).ReleaseSegmentLock\n/go/src/github.com/milvus-io/milvus/internal/querycoord/global_meta_broker.go:533 github.com/milvus-io/milvus/internal/querycoord.(*globalMetaBroker).releaseSegmentReferLock.func1\n/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:37 github.com/milvus-io/milvus/internal/util/retry.Do\n/go/src/github.com/milvus-io/milvus/internal/querycoord/global_meta_broker.go:532 github.com/milvus-io/milvus/internal/querycoord.(*globalMetaBroker).releaseSegmentReferLock\n/go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:1401 github.com/milvus-io/milvus/internal/querycoord.(*loadSegmentTask).postExecute\n/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:565 github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processTask.func2\n/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:579 github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processTask\n/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:931 github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processActivateTaskLoop.func1\n"]
[2022/11/04 09:06:09.489 +00:00] [ERROR] [querycoord/global_meta_broker.go:535] ["QueryCoord release reference lock on segments failed"] [segmentIDs="[437122948269867009,437126742083371009,437129163441963009,437122711226155009,437130441433284609,437132226869854209,437123016453521409,437121243390148609]"] [error="context deadline exceeded"] [stack="github.com/milvus-io/milvus/internal/querycoord.(*globalMetaBroker).releaseSegmentReferLock.func1\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/global_meta_broker.go:535\ngithub.com/milvus-io/milvus/internal/util/retry.Do\n\t/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:37\ngithub.com/milvus-io/milvus/internal/querycoord.(*globalMetaBroker).releaseSegmentReferLock\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/global_meta_broker.go:532\ngithub.com/milvus-io/milvus/internal/querycoord.(*loadSegmentTask).postExecute\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:1401\ngithub.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processTask.func2\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:565\ngithub.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processTask\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:579\ngithub.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processActivateTaskLoop.func1\n\t/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:931"]
[2022/11/04 09:06:09.489 +00:00] [DEBUG] [retry/retry.go:39] ["retry func failed"] ["retry time"=0] [error="context deadline exceeded"]
[2022/11/04 09:06:09.489 +00:00] [WARN] [grpcclient/client.go:251] ["datacoord ClientBase ReCall grpc first call get error "] [error="err: rpc error: code = DeadlineExceeded desc = context deadline exceeded\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:250 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall\n/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:545 github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).ReleaseSegmentLock\n/go/src/github.com/milvus-io/milvus/internal/querycoord/global_meta_broker.go:533 github.com/milvus-io/milvus/internal/querycoord.(*globalMetaBroker).releaseSegmentReferLock.func1\n/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:37 github.com/milvus-io/milvus/internal/util/retry.Do\n/go/src/github.com/milvus-io/milvus/internal/querycoord/global_meta_broker.go:532 github.com/milvus-io/milvus/internal/querycoord.(*globalMetaBroker).releaseSegmentReferLock\n/go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:1401 github.com/milvus-io/milvus/internal/querycoord.(*loadSegmentTask).postExecute\n/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:565 github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processTask.func2\n/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:579 github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processTask\n/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:931 github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processActivateTaskLoop.func1\n"]
panic: All attempts results:
attempt #1:context deadline exceeded
attempt #2:context deadline exceeded

goroutine 455 [running]:
github.com/milvus-io/milvus/internal/querycoord.(*loadSegmentTask).postExecute(0xc0034db0e0, 0x43b7d10, 0xc003f15400, 0x1, 0x4007150)
        /go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:1402 +0x37c
github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processTask.func2(0x43dc120, 0xc010ceb200, 0x43f0740, 0xc0034db0e0, 0xc003d83b40)
        /go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:565 +0x126
github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processTask(0xc00077bd80, 0x43f0740, 0xc0034db0e0, 0x437ac20, 0xc00547e660)
        /go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:579 +0x8f8
github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processActivateTaskLoop.func1(0xc00077bd80, 0x43f0740, 0xc0034db0e0)
        /go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:931 +0x3f
created by github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processActivateTaskLoop
        /go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:930 +0x151

**Comment by yanliang567** [comment]
@haochun Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
/assign @haochun

**Comment by haorenfsa** [comment]
looks like `releaseSegmentReferLock` paniced. I'll try to dig it out.

**Comment by haorenfsa** [comment]
@haochun If you plz, providing the log of datacoord will be good help

**Comment by xiaofan-luan** [comment]
close because of not active
