### ISSUE TITLE
[Bug]: [benchmark][diskann]Milvus create diskann index ,load raise an error"Retry run out of 10 retry times, message=collection 437191740442542084 has not been loaded to memory or load failed"

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#20359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20221105-16c8642b
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0dev70
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server-instance
fouram-stable-1667754000-1
server-configmap
server-single-4c16m-diskann
client-configmap
client-locust-search-sift10m-diskann

```
NAME                                                              READY   STATUS      RESTARTS        AGE     IP             NODE         NOMINATED NODE   READINESS GATES
fouram-stable-1667754000-1-etcd-0                                 1/1     Running     0               2m12s   10.104.6.82    4am-node13   <none>           <none>
fouram-stable-1667754000-1-milvus-standalone-fcd7484f8-st7q5      1/1     Running     0               2m12s   10.104.5.190   4am-node12   <none>           <none>
fouram-stable-1667754000-1-minio-7ccddd9459-54qnn                 1/1     Running     0               2m12s   10.104.6.69    4am-node13   <none>           <none>
```

```
[2022-11-06 19:01:59,996] [   DEBUG] - Milvus create_index run in 6768.5157s (milvus_benchmark.client:57)
[2022-11-06 19:01:59,996] [   DEBUG] - {'flush_time': 2.5175, 'build_time': 6768.5158} (milvus_benchmark.runners.locust:457)
[2022-11-06 19:01:59,997] [   DEBUG] - Row count: 10000000 in collection: <sift_10m_128_l2> (milvus_benchmark.client:520)
[2022-11-06 19:01:59,998] [    INFO] - 10000000 (milvus_benchmark.runners.locust:458)
[2022-11-06 19:01:59,998] [    INFO] - Start load collection (milvus_benchmark.runners.locust:459)
[2022-11-06 19:02:37,117] [ WARNING] - [93m[get_loading_progress] retry:4, cost: 0.27s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:71)
[2022-11-06 19:02:37,389] [ WARNING] - [93m[get_loading_progress] retry:5, cost: 0.81s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:71)
[2022-11-06 19:02:38,200] [ WARNING] - [93m[get_loading_progress] retry:6, cost: 2.43s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:71)
[2022-11-06 19:02:40,632] [ WARNING] - [93m[get_loading_progress] retry:7, cost: 7.29s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:71)
[2022-11-06 19:02:47,924] [ WARNING] - [93m[get_loading_progress] retry:8, cost: 21.87s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:71)
[2022-11-06 19:03:09,796] [ WARNING] - [93m[get_loading_progress] retry:9, cost: 60.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:71)
[2022-11-06 19:04:09,797] [ WARNING] - [93m[get_loading_progress] retry:10, cost: 60.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:71)
[2022-11-06 19:05:09,802] [ WARNING] - [93mRetry run out of 10 retry times[0m (pymilvus.decorators:79)
[2022-11-06 19:05:09,803] [   ERROR] - RPC error: [get_loading_progress], <MilvusException: (code=1, message=Retry run out of 10 retry times, message=collection 437191740442542084 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-11-06 19:02:36.939779', 'RPC error': '2022-11-06 19:05:09.803200'}> (pymilvus.decorators:108)
[2022-11-06 19:05:09,803] [   ERROR] - RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=Retry run out of 10 retry times, message=collection 437191740442542084 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-11-06 19:02:00.025298', 'RPC error': '2022-11-06 19:05:09.803375'}> (pymilvus.decorators:108)
[2022-11-06 19:05:09,803] [   ERROR] - RPC error: [load_collection], <MilvusException: (code=1, message=Retry run out of 10 retry times, message=collection 437191740442542084 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-11-06 19:01:59.998503', 'RPC error': '2022-11-06 19:05:09.803474'}> (pymilvus.decorators:108)
[2022-11-06 19:05:09,803] [   ERROR] - <MilvusException: (code=1, message=Retry run out of 10 retry times, message=collection 437191740442542084 has not been loaded to memory or load failed)> (milvus_benchmark.main:118)
[2022-11-06 19:05:09,806] [   ERROR] - Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 747, in get_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection 437191740442542084 has not been loaded to memory or load failed)>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 87, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/locust.py", line 461, in prepare
    self.milvus.load_collection(replica_number=replica_number)
  File "/src/milvus_benchmark/client.py", line 53, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 592, in load_collection
    return self._milvus.load_collection(collection_name, **params)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/stub.py", line 193, in load_collection
    return handler.load_collection(collection_name, replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 668, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 686, in wait_for_loading_collection
    progress = self.get_loading_progress(collection_name, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 80, in handler
    raise MilvusException(e.code, f"{timeout_msg}, message={e.message}") from e
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry run out of 10 retry times, message=collection 437191740442542084 has not been loaded to memory or load failed)>
 (milvus_benchmark.main:119)
```

### Steps To Reproduce

```markdown
1.create a collection
2. build diskann index
3. insert 10m data
4. build same index again
5. load raise an error
```

**Comment by xige-16** [comment]
querynode restart 

![fZKD94kqmj](https://user-images.githubusercontent.com/20124155/200241607-9797e8f1-fc2e-4392-8739-143e6a1b2bb1.png)

**Comment by xige-16** [comment]
first panic at 19:02, there is still a lot of free memory, so it is not a restart caused by insufficient memory

![WmrV2IIeAY](https://user-images.githubusercontent.com/20124155/200242271-a960722a-ca42-4f14-a0a6-9a524ffcb6db.png)

**Comment by jingkl** [comment]
server-instance
fouram-stable-1667840400-1
server-configmap
server-single-4c16m-diskann
client-configmap
client-locust-search-sift10m-diskann

```
NAME                                                              READY   STATUS      RESTARTS       AGE     IP             NODE         NOMINATED NODE   READINESS GATES
fouram-stable-1667840400-1-etcd-0                                 1/1     Running     0              108s    10.104.4.198   4am-node11   <none>           <none>
fouram-stable-1667840400-1-milvus-standalone-84cc66f5c4-qp5hl     1/1     Running     0              108s    10.104.9.20    4am-node14   <none>           <none>
fouram-stable-1667840400-1-minio-779d5647c7-7nr7h                 1/1     Running     0              108s    10.104.4.194   4am-node11   <none>           <none>
```
```
[2022-11-07 19:09:04,268] [    INFO] - Start load collection (milvus_benchmark.runners.locust:459)
[2022-11-07 19:11:02,624] [ WARNING] - [93m[get_loading_progress] retry:4, cost: 0.27s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:71)
[2022-11-07 19:11:02,895] [ WARNING] - [93m[get_loading_progress] retry:5, cost: 0.81s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:71)
[2022-11-07 19:11:03,707] [ WARNING] - [93m[get_loading_progress] retry:6, cost: 2.43s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:71)
[2022-11-07 19:11:06,138] [ WARNING] - [93m[get_loading_progress] retry:7, cost: 7.29s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:71)
[2022-11-07 19:11:13,429] [ WARNING] - [93m[get_loading_progress] retry:8, cost: 21.87s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:71)
[2022-11-07 19:11:35,301] [ WARNING] - [93m[get_loading_progress] retry:9, cost: 60.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:71)
[2022-11-07 19:12:35,302] [ WARNING] - [93m[get_loading_progress] retry:10, cost: 60.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:71)
[2022-11-07 19:13:35,306] [ WARNING] - [93mRetry run out of 10 retry times[0m (pymilvus.decorators:79)
[2022-11-07 19:13:35,306] [   ERROR] - RPC error: [get_loading_progress], <MilvusException: (code=1, message=Retry run out of 10 retry times, message=collection 437214385965105157 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-11-07 19:11:02.342355', 'RPC error': '2022-11-07 19:13:35.306265'}> (pymilvus.decorators:108)
[2022-11-07 19:13:35,306] [   ERROR] - RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=Retry run out of 10 retry times, message=collection 437214385965105157 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-11-07 19:09:04.277667', 'RPC error': '2022-11-07 19:13:35.306407'}> (pymilvus.decorators:108)
[2022-11-07 19:13:35,306] [   ERROR] - RPC error: [load_collection], <MilvusException: (code=1, message=Retry run out of 10 retry times, message=collection 437214385965105157 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-11-07 19:09:04.268150', 'RPC error': '2022-11-07 19:13:35.306481'}> (pymilvus.decorators:108)
[2022-11-07 19:13:35,306] [   ERROR] - <MilvusException: (code=1, message=Retry run out of 10 retry times, message=collection 437214385965105157 has not been loaded to memory or load failed)> (milvus_benchmark.main:118)
[2022-11-07 19:13:35,307] [   ERROR] - Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 747, in get_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection 437214385965105157 has not been loaded to memory or load failed)>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 87, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/locust.py", line 461, in prepare
    self.milvus.load_collection(replica_number=replica_number)
  File "/src/milvus_benchmark/client.py", line 53, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 592, in load_collection
    return self._milvus.load_collection(collection_name, **params)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/stub.py", line 193, in load_collection
    return handler.load_collection(collection_name, replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 668, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 686, in wait_for_loading_collection
    progress = self.get_loading_progress(collection_name, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 80, in handler
    raise MilvusException(e.code, f"{timeout_msg}, message={e.message}") from e
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry run out of 10 retry times, message=collection 437214385965105157 has not been loaded to memory or load failed)>
 (milvus_benchmark.main:119)
```

**Comment by xige-16** [comment]
The reason is that the data pointed by the index_payload->raw_data may have been destructed, and the raw_data is still used outside the function after the data is destructed.

https://github.com/milvus-io/milvus/blob/a2bf5022cb283ed599f38a0e0941dbc991a4dc1a/internal/core/src/storage/DiskFileManagerImpl.cpp#L191-L202

**Comment by xige-16** [comment]
@jingkl  please verifty 2.2.0

**Comment by elstic** [comment]
```
server-instance
fouram-stable-1668099600-1
server-configmap
server-single-4c16m-diskann
client-configmap
client-locust-search-sift10m-diskann

```
tag: 2.2.0-20221110-b565145a
pymilvus-2.2.0.dev70

```
NOMINATED NODE   READINESS GATES
fouram-stable-1668099600-1-etcd-0                                 1/1     Running     0              106s    10.104.9.118   4am-node14
<none>           <none>
fouram-stable-1668099600-1-milvus-standalone-6654bb4c8c-qshbq     1/1     Running     0              106s    10.104.5.234   4am-node12
<none>           <none>
fouram-stable-1668099600-1-minio-7b76b9586-7kptw                  1/1     Running     0              106s    10.104.6.181   4am-node13
<none>           <none>
```

```
[2022-11-10 19:59:07,975] [    INFO] - Start load collection (milvus_benchmark.runners.locust:459)
[2022-11-10 20:16:04,254] [   ERROR] - RPC error: [get_loading_progress], <MilvusException: (code=1, message=collection 437282332939911173 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-11-10 20:16:04.252305', 'RPC error': '2022-11-10 20:16:04.254010'}> (pymilvus.decorators:108)
[2022-11-10 20:16:04,254] [   ERROR] - RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=collection 437282332939911173 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-11-10 19:59:07.993964', 'RPC error': '2022-11-10 20:16:04.254333'}> (pymilvus.decorators:108)
[2022-11-10 20:16:04,254] [   ERROR] - RPC error: [load_collection], <MilvusException: (code=1, message=collection 437282332939911173 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-11-10 19:59:07.975106', 'RPC error': '2022-11-10 20:16:04.254405'}> (pymilvus.decorators:108)
[2022-11-10 20:16:04,254] [   ERROR] - <MilvusException: (code=1, message=collection 437282332939911173 has not been loaded to memory or load failed)> (milvus_benchmark.main:118)
[2022-11-10 20:16:04,256] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 87, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/locust.py", line 461, in prepare
    self.milvus.load_collection(replica_number=replica_number)
  File "/src/milvus_benchmark/client.py", line 53, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 592, in load_collection
    return self._milvus.load_collection(collection_name, **params)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/stub.py", line 193, in load_collection
    return handler.load_collection(collection_name, replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 668, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 686, in wait_for_loading_collection
    progress = self.get_loading_progress(collection_name, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 747, in get_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection 437282332939911173 has not been loaded to memory or load failed)>
 (milvus_benchmark.main:119)



```
@xige-16

**Comment by elstic** [comment]
server-instance
fouram-stable-1668358800-1
server-configmap
server-single-4c16m-diskann
client-configmap
client-locust-search-sift10m-diskann

pymilvus-2.2.0.dev70
tag: 2.2.0-20221113-056aebf9


```
fouram-stable-1668358800-1-etcd-0                                 1/1     Running     0              116s    10.104.5.28    4am-node12   <none>           <none>
fouram-stable-1668358800-1-milvus-standalone-85cd4f59c8-7t47z     1/1     Running     0              116s    10.104.6.249   4am-node13   <none>           <none>
fouram-stable-1668358800-1-minio-68d87b566c-qnhtk                 1/1     Running     0              116s    10.104.6.244   4am-node13   <none>           <none>
```

```
[2022-11-13 19:35:22,509] [   ERROR] - RPC error: [get_loading_progress], <MilvusException: (code=1, message=collection 437350283317870597 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-11-13 19:35:22.507994', 'RPC error': '2022-11-13 19:35:22.509424'}> (pymilvus.decorators:108)
[2022-11-13 19:35:22,509] [   ERROR] - RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=collection 437350283317870597 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-11-13 19:17:39.018854', 'RPC error': '2022-11-13 19:35:22.509791'}> (pymilvus.decorators:108)
[2022-11-13 19:35:22,509] [   ERROR] - RPC error: [load_collection], <MilvusException: (code=1, message=collection 437350283317870597 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-11-13 19:17:38.998123', 'RPC error': '2022-11-13 19:35:22.509866'}> (pymilvus.decorators:108)
[2022-11-13 19:35:22,509] [   ERROR] - <MilvusException: (code=1, message=collection 437350283317870597 has not been loaded to memory or load failed)> (milvus_benchmark.main:118)
[2022-11-13 19:35:22,511] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 87, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/locust.py", line 461, in prepare
    self.milvus.load_collection(replica_number=replica_number)
  File "/src/milvus_benchmark/client.py", line 53, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 592, in load_collection
    return self._milvus.load_collection(collection_name, **params)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/stub.py", line 193, in load_collection
    return handler.load_collection(collection_name, replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 668, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 686, in wait_for_loading_collection
    progress = self.get_loading_progress(collection_name, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 747, in get_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection 437350283317870597 has not been loaded to memory or load failed)>
 (milvus_benchmark.main:119)
[2022-11-13 19:35:22,511] [   DEBUG] - {'_version': '0.1', '_type': 'metric', 'run_id': 1668366183, 'mode': 'local', 'server': <milvus_benchmark.metrics.models.server.Server object at 0x7f3a63725970>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware object at 0x7f3baf1b80d0>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7f3a62174220>, 'status': 'RUN_FAILED', 'err_message': '', 'collection': {'dimension': 128, 'metric_type': 'l2', 'dataset_name': 'sift_10m_128_l2', 'collection_size': 10000000, 'other_fields': None, 'ni_per': 50000, 'shards_num': None}, 'index': {'index_type': 'diskann', 'index_param': {}}, 'search': None, 'run_params': {'task': {'types': [{'type': 'query', 'weight': 10, 'params': {'top_k': 10, 'nq': 10, 'search_param': {'search_list': 30}}}, {'type': 'load', 'weight': 1}, {'type': 'get', 'weight': 2, 'params': {'ids_length': 10}}], 'connection_num': 1, 'clients_num': 20, 'spawn_rate': 2, 'during_time': '1h'}, 'connection_type': 'single'}, 'metrics': {'type': 'locust_random_performance', 'value': {}}, 'datetime': '2022-11-13 17:04:14.244361', 'type': 'metric'} (milvus_benchmark.metric.api:30)
```

@xige-16

**Comment by elstic** [comment]
Last 7 days no show 

image ：2.2.0-20221211-50c7a80b
