### ISSUE TITLE
[Feature]: Modify the collection schema once collection is created and is not empty

### ISSUE THREAD

**Issue by jeet129** [milvus-io/milvus#20405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Many a times, when we start with an ANN collection definition we don't know the exhaustive list of fields which should be available for the use case and we create the collection with few known fields in the collection schema and as the application evolves there is a need to add/modify the schema defined earlier to accommodate more attributes.

Without this, the only way is to recreate a collection and do a fresh ingestion of data, which might not be an easy choice  considering the longer data ingestion pipeline for huge collections.

### Describe the solution you'd like.

We need a way to add new fields(non-mandatory/fields with default values)/drop existing(non-primary) fields from collection.
This way the same collection can be used to serve the different scenarios pertaining to a use case without a need to create a new collection and hydrating it with the data.

Also there should be an option to update the values for such attributes for existing entities.

**Comment by zyy20191** [comment]
The ability to add field to an already created collection is really convenient, and I hope you can consider this requirement

**Comment by xiaofan-luan** [comment]
Let's keep it.
Agree this is very useful feature.
But this require a lot effort so I think if anyone has time pls take it. Otherwise we will wait for performance/stability issue solved and we start to work on it

**Comment by sskserk** [comment]
Hey Milvus Developers and Community,

Would it be feasible to implement a feature that includes basic routines for renaming, adding, or dropping columns? Even a simple set of these functions could significantly enhance our capabilities.

The use case is straightforward but has a substantial impact:
We have a large collection containing many thousands of records.
* A considerable amount of time has been invested in calculating the stored embeddings.
**A new release of the functional logic now necessitates the inclusion of an additional field.
*A major challenge we face is determining how to properly migrate the data. 

Currently, we are compelled to recreate the entire collection from scratch whenever an additional or modified field is needed. Given the vast amounts of data involved, this process is exceedingly challenging.

Providing a command-line tool that could handle these modifications would offer significant relief and improve our efficiency.

P/S: Would be happy to cooperate with somebody or assist with a corresponding MR.

**Comment by xiaofan-luan** [comment]
this is for sure already on our roadmap.

@tedxu  and @smellthemoon  is actually working on it so hopefully that would help..

@smellthemoon could you please followup with @sskserk and see how it can work with our latest modify schema feature

**Comment by sskserk** [comment]
@xiaofan-luan , @tedxu , @smellthemoon,

I am eager to test the new feature and am looking forward to receiving it. I'm ready to test a prerelease of this  feature, just need to know when.

The implementation of this feature will undoubtedly mark a significant milestone. I anticipate that, as a result, a new Milvus-related product similar to "Flyway" might emerge in the future.

Your solution is already widely adopted by major companies, and this enhancement will further solidify its enterprise-grade capabilities.

Thank you for the positive update!

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan , @tedxu , @smellthemoon,
> 
> I am eager to test the new feature and am looking forward to receiving it. I'm ready to test a prerelease of this feature, just need to know when.
> 
> The implementation of this feature will undoubtedly mark a significant milestone. I anticipate that, as a result, a new Milvus-related product similar to "Flyway" might emerge in the future.
> 
> Your solution is already widely adopted by major companies, and this enhancement will further solidify its enterprise-grade capabilities.
> 
> Thank you for the positive update!

could, let's ship it

**Comment by smellthemoon** [comment]
In fact, the add field feature has been included in our development plan. Users can add a new column through add field operation. The values in this new column are all null values. After the add field operation is completed, the field data in insert/upsert request needs to has the data of the new column. I will keep you updated if there is any progress.

**Comment by xiaofan-luan** [comment]
On 2.0 we support null/default value.
The target for 3.0 is to support schema change.

**Comment by iamkhalidbashir** [comment]
is there any null value for embeddings field? 
js lib if we pass null for an embedding field, we get this error
```sh
Error processing PDF: TypeError: Cannot read properties of null (reading 'length')
    at Function.concat (node:buffer:589:19)
    at /app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/grpc/Data.js:241:47
    at Array.map (<anonymous>)
    at MilvusClient.<anonymous> (/app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/grpc/Data.js:218:64)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/grpc/Data.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by xiaofan-luan** [comment]
> is there any null value for embeddings field? js lib if we pass null for an embedding field, we get this error
> 
> ```shell
> Error processing PDF: TypeError: Cannot read properties of null (reading 'length')
>     at Function.concat (node:buffer:589:19)
>     at /app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/grpc/Data.js:241:47
>     at Array.map (<anonymous>)
>     at MilvusClient.<anonymous> (/app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/grpc/Data.js:218:64)
>     at Generator.next (<anonymous>)
>     at fulfilled (/app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/grpc/Data.js:5:58)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> ```

embeddings can not be null.

for data field, it can be null only if nullable enabled after milvus 2.5

@smellthemoon
Do we support alter a non-nullable field to nullable?

**Comment by michaeltinsley** [comment]
Is there any update on this? The [docs still say it is planned for a future release](https://milvus.io/docs/product_faq.md#What-are-the-limitations-of-using-dynamic-fields-For-example-are-there-size-limits-modification-methods-or-indexing-restrictions:~:text=in%20future%20releases.-,Does%20Milvus%20support%20schema%20changes%3F,for%20future%20releases%2C%20enhancing%20the%20flexibility%20of%20schema%20management%20within%20Milvus.,-Does%20modifying%20max_length) in the 2.6 docs

**Comment by xiaofan-luan** [comment]
2.6 already supported add field https://milvus.io/docs/add-fields-to-an-existing-collection.md

this will be beta on Zilliz cloud since october
