### ISSUE TITLE
[Bug]: Create index timeout (200s) after minio pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#20418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20221108-a2bf5022
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
2022-11-08T22:21:06.305Z] [2022-11-08 22:16:23 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)

[2022-11-08T22:21:06.305Z] [2022-11-08 22:16:23 - INFO - ci_test]: [test][2022-11-08T22:16:23Z] [0.00652410s] e2e__Xp5zbO9M flush -> None (wrapper.py:30)

[2022-11-08T22:21:06.305Z] [2022-11-08 22:16:23 - INFO - ci_test]: assert flush: 2.5275509357452393, entities: 3000 (test_e2e.py:41)

[2022-11-08T22:21:06.305Z] [2022-11-08 22:16:23 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['float_vector', {'index_type': 'IVF_SQ8', 'params': {'nlist': 64}, 'metric_type': 'L2'}], kwargs: {'timeout': 200, 'index_name': 'test_mGiU8aMG'} (api_request.py:56)

[2022-11-08T22:21:06.305Z] [2022-11-08 22:17:33 - DEBUG - ci_test]: (api_response) : Status(code=0, message=)  (api_request.py:31)

[2022-11-08T22:21:06.305Z] [2022-11-08 22:17:33 - INFO - ci_test]: [test][2022-11-08T22:16:23Z] [70.34883540s] e2e__Xp5zbO9M create_index -> Status(code=0, message=) (wrapper.py:30)

[2022-11-08T22:21:06.305Z] [2022-11-08 22:17:33 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['varchar', {}], kwargs: {'timeout': 200, 'index_name': 'test_oYi4msE5'} (api_request.py:56)

[2022-11-08T22:21:06.305Z] [2022-11-08 22:20:54 - WARNING - pymilvus.decorators]: Retry timeout: 200s (decorators.py:79)

[2022-11-08T22:21:06.305Z] [2022-11-08 22:20:54 - ERROR - pymilvus.decorators]: RPC error: [wait_for_creating_index], <MilvusException: (code=1, message=Retry timeout: 200s, message=collection e2e__Xp5zbO9M create index test_oYi4msE5 timeout in 200s)>, <Time:{'RPC start': '2022-11-08 22:17:33.926250', 'RPC error': '2022-11-08 22:20:54.242344'}> (decorators.py:108)

[2022-11-08T22:21:06.305Z] [2022-11-08 22:20:54 - WARNING - pymilvus.decorators]: Retry timeout: 200s (decorators.py:79)

[2022-11-08T22:21:06.305Z] [2022-11-08 22:20:54 - ERROR - pymilvus.decorators]: RPC error: [create_index], <MilvusException: (code=1, message=Retry timeout: 200s, message=Retry timeout: 200s, message=collection e2e__Xp5zbO9M create index test_oYi4msE5 timeout in 200s)>, <Time:{'RPC start': '2022-11-08 22:17:33.913001', 'RPC error': '2022-11-08 22:20:54.242601'}> (decorators.py:108)

[2022-11-08T22:21:06.305Z] [2022-11-08 22:20:54 - ERROR - ci_test]: Traceback (most recent call last):

[2022-11-08T22:21:06.305Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2022-11-08T22:21:06.305Z]     return func(self, *args, **kwargs)

[2022-11-08T22:21:06.305Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 566, in create_index

[2022-11-08T22:21:06.305Z]     index_success, fail_reason = self.wait_for_creating_index(collection_name=collection_name,

[2022-11-08T22:21:06.305Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2022-11-08T22:21:06.305Z]     raise e

[2022-11-08T22:21:06.305Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2022-11-08T22:21:06.305Z]     return func(*args, **kwargs)

[2022-11-08T22:21:06.305Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2022-11-08T22:21:06.305Z]     ret = func(self, *args, **kwargs)

[2022-11-08T22:21:06.305Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 80, in handler

[2022-11-08T22:21:06.305Z]     raise MilvusException(e.code, f"{timeout_msg}, message={e.message}") from e

[2022-11-08T22:21:06.305Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 200s, message=collection e2e__Xp5zbO9M create index test_oYi4msE5 timeout in 200s)>

[2022-11-08T22:21:06.305Z] 

[2022-11-08T22:21:06.305Z] The above exception was the direct cause of the following exception:

[2022-11-08T22:21:06.305Z] 

[2022-11-08T22:21:06.305Z] Traceback (most recent call last):

[2022-11-08T22:21:06.305Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2022-11-08T22:21:06.305Z]     res = func(*args, **_kwargs)

[2022-11-08T22:21:06.305Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2022-11-08T22:21:06.305Z]     return func(*arg, **kwargs)

[2022-11-08T22:21:06.305Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 1092, in create_index

[2022-11-08T22:21:06.305Z]     return conn.create_index(self._name, field_name, index_params,

[2022-11-08T22:21:06.305Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2022-11-08T22:21:06.305Z]     raise e

[2022-11-08T22:21:06.305Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2022-11-08T22:21:06.305Z]     return func(*args, **kwargs)

[2022-11-08T22:21:06.305Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2022-11-08T22:21:06.305Z]     ret = func(self, *args, **kwargs)

[2022-11-08T22:21:06.305Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 80, in handler

[2022-11-08T22:21:06.305Z]     raise MilvusException(e.code, f"{timeout_msg}, message={e.message}") from e

[2022-11-08T22:21:06.305Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 200s, message=Retry timeout: 200s, message=collection e2e__Xp5zbO9M create index test_oYi4msE5 timeout in 200s)>

[2022-11-08T22:21:06.305Z]  (api_request.py:39)
```

### Expected Behavior

all test cases passed

### Milvus Log

chaos type: pod-kill image tag: master-20221108-a2bf5022 target pod: minio
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/2909/pipeline
log:
[artifacts-s3-pod-kill-2909-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9966662/artifacts-s3-pod-kill-2909-server-logs.tar.gz)

[artifacts-s3-pod-kill-2909-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9966663/artifacts-s3-pod-kill-2909-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
Not only vchar index but also vector index would be failed

**Comment by xiaocai2333** [comment]
fixed on master, please verify @zhuwenxing 
/assign @zhuwenxing

**Comment by zhuwenxing** [comment]
Not reproduced in master and 2.2.0 branch
