### ISSUE TITLE
[Bug]: [UT] proxy failed with error bind: address already in use

### ISSUE THREAD

**Issue by jennyli-z** [milvus-io/milvus#20421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
Action Runner 
https://github.com/milvus-io/milvus/actions/runs/3420487743/jobs/5695371172
```

### Current Behavior

Failed with following error message

```
Error: 1/08 15:24:31.763 +00:00] [ERROR] [rootcoord/service.go:231] ["GrpcServer:failed to listen"] [error="listen tcp :53100: bind: address already in use"] [stack="github.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).startGrpcLoop\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:231"]
panic: listen tcp :53100: bind: address already in use

goroutine 305 [running]:
github.com/milvus-io/milvus/internal/proxy.runRootCoord.func1()
	/go/src/github.com/milvus-io/milvus/internal/proxy/proxy_test.go:117 +0x1bc
created by github.com/milvus-io/milvus/internal/proxy.runRootCoord
	/go/src/github.com/milvus-io/milvus/internal/proxy/proxy_test.go:102 +0x1a5
FAIL	github.com/milvus-io/milvus/internal/proxy	3.519s
FAIL
make: *** [Makefile:233: codecov-go] Error 1
```

### Expected Behavior

should pass

### Milvus Log

[https://github.com/milvus-io/milvus/actions/runs/3420487743/jobs/5695371172](https://github.com/milvus-io/milvus/actions/runs/3420487743/jobs/5695371172)

**Comment by yanliang567** [comment]
@jiaoew1991 was this ut fixed?

**Comment by jiaoew1991** [comment]
> @jiaoew1991 was this ut fixed?

not yet，it's trigger condition is difficult
