### ISSUE TITLE
[Bug]: "StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet"

### ISSUE THREAD

**Issue by SamrudhiRRao** [milvus-io/milvus#20433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.1.4
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.1.3
- OS(Ubuntu or CentOS): Ubuntu 22.04LTS
- CPU/Memory: 32GB RAM
- GPU: 
- Others:
```

### Current Behavior

Milvus was working fine for a while and I wanted to insert data. When I released the collection, milvus crashed with the error "**StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet**". I recreated the docker image several times and even tried to reinstall docker but the error persists . 

The docker compose file has been taken from: https://github.com/milvus-io/milvus/releases/download/v2.1.4/milvus-standalone-docker-compose.yml

[has_collection] retry:4, cost: 0.27s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>
[has_collection] retry:5, cost: 0.81s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>
[has_collection] retry:6, cost: 2.43s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>
[has_collection] retry:7, cost: 7.290000000000001s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>
[has_collection] retry:8, cost: 21.870000000000005s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>
[has_collection] retry:9, cost: 60s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>
[has_collection] retry:10, cost: 60s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>

### Milvus Log

[2022/11/09 06:38:38.870 +00:00] [DEBUG] [sessionutil/session_util.go:142] ["Session try to connect to etcd"]
[2022/11/09 06:38:38.960 +00:00] [DEBUG] [sessionutil/session_util.go:142] ["Session try to connect to etcd"]
[2022/11/09 06:38:38.961 +00:00] [DEBUG] [sessionutil/session_util.go:142] ["Session try to connect to etcd"]
[2022/11/09 06:38:38.968 +00:00] [DEBUG] [sessionutil/session_util.go:142] ["Session try to connect to etcd"]
[2022/11/09 06:38:38.995 +00:00] [DEBUG] [sessionutil/session_util.go:142] ["Session try to connect to etcd"]
[2022/11/09 06:38:38.996 +00:00] [DEBUG] [sessionutil/session_util.go:142] ["Session try to connect to etcd"]
[2022/11/09 06:38:38.996 +00:00] [DEBUG] [sessionutil/session_util.go:142] ["Session try to connect to etcd"]
[2022/11/09 06:38:38.998 +00:00] [DEBUG] [sessionutil/session_util.go:142] ["Session try to connect to etcd"]
[2022/11/09 06:38:39.670 +00:00] [WARN] [grpclog/grpclog.go:46] ["[core][Channel #23 SubChannel #24] grpc: addrConn.createTransport failed to connect to {\n  \"Addr\": \"etcd:2379\",\n  \"ServerName\": \"etcd\",\n  \"Attributes\": null,\n  \"BalancerAttributes\": null,\n  \"Type\": 0,\n  \"Metadata\": null\n}. Err: connection error: desc = \"transport: Error while dialing dial tcp 172.21.0.3:2379: i/o timeout\""]
{"level":"warn","ts":"2022-11-09T06:38:43.871Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000437340/#initially=[etcd:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 172.21.0.3:2379: i/o timeout\""}
{"level":"warn","ts":"2022-11-09T06:38:43.961Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000a5c8c0/#initially=[etcd:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 172.21.0.3:2379: i/o timeout\""}
{"level":"warn","ts":"2022-11-09T06:38:43.963Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000a5ce00/#initially=[etcd:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 172.21.0.3:2379: i/o timeout\""}
{"level":"warn","ts":"2022-11-09T06:38:43.969Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0004e0fc0/#initially=[etcd:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 172.21.0.3:2379: i/o timeout\""}
{"level":"warn","ts":"2022-11-09T06:38:43.996Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000eea000/#initially=[etcd:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 172.21.0.3:2379: i/o timeout\""}
{"level":"warn","ts":"2022-11-09T06:38:43.996Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0010a6380/#initially=[etcd:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 172.21.0.3:2379: i/o timeout\""}
{"level":"warn","ts":"2022-11-09T06:38:43.996Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000a5c540/#initially=[etcd:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 172.21.0.3:2379: i/o timeout\""}
{"level":"warn","ts":"2022-11-09T06:38:43.999Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0010a6700/#initially=[etcd:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 172.21.0.3:2379: i/o timeout\""}
[2022/11/09 06:38:45.174 +00:00] [WARN] [grpclog/grpclog.go:46] ["[core][Channel #33 SubChannel #34] grpc: addrConn.createTransport failed to connect to {\n  \"Addr\": \"etcd:2379\",\n  \"ServerName\": \"etcd\",\n  \"Attributes\": null,\n  \"BalancerAttributes\": null,\n  \"Type\": 0,\n  \"Metadata\": null\n}. Err: connection error: desc = \"transport: Error while dialing dial tcp 172.21.0.3:2379: i/o timeout\""]
[2022/11/09 06:38:46.872 +00:00] [DEBUG] [sessionutil/session_util.go:142] ["Session try to connect to etcd"]
[2022/11/09 06:38:46.962 +00:00] [DEBUG] [sessionutil/session_util.go:142] ["Session try to connect to etcd"]
[2022/11/09 06:38:46.963 +00:00] [DEBUG] [sessionutil/session_util.go:142] ["Session try to connect to etcd"]
[2022/11/09 06:38:46.970 +00:00] [DEBUG] [sessionutil/session_util.go:142] ["Session try to connect to etcd"]
[2022/11/09 06:38:46.997 +00:00] [DEBUG] [sessionutil/session_util.go:142] ["Session try to connect to etcd"]
[2022/11/09 06:38:46.997 +00:00] [DEBUG] [sessionutil/session_util.go:142] ["Session try to connect to etcd"]
[2022/11/09 06:38:46.997 +00:00] [DEBUG] [sessionutil/session_util.go:142] ["Session try to connect to etcd"]
[2022/11/09 06:38:46.999 +00:00] [DEBUG] [sessionutil/session_util.go:142] ["Session try to connect to etcd"]
{"level":"warn","ts":"2022-11-09T06:38:51.872Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000437340/#initially=[etcd:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 172.21.0.3:2379: i/o timeout\""}
{"level":"warn","ts":"2022-11-09T06:38:51.963Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000a5c8c0/#initially=[etcd:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 172.21.0.3:2379: i/o timeout\""}
{"level":"warn","ts":"2022-11-09T06:38:51.964Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000a5ce00/#initially=[etcd:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 172.21.0.3:2379: i/o timeout\""}
{"level":"warn","ts":"2022-11-09T06:38:51.971Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0004e0fc0/#initially=[etcd:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 172.21.0.3:2379: i/o timeout\""}
{"level":"warn","ts":"2022-11-09T06:38:51.998Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0010a6380/#initially=[etcd:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 172.21.0.3:2379: i/o timeout\""}
{"level":"warn","ts":"2022-11-09T06:38:51.998Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000a5c540/#initially=[etcd:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 172.21.0.3:2379: i/o timeout\""}
{"level":"warn","ts":"2022-11-09T06:38:51.998Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000eea000/#initially=[etcd:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 172.21.0.3:2379: i/o timeout\""}
{"level":"warn","ts":"2022-11-09T06:38:51.999Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0010a6700/#initially=[etcd:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 172.21.0.3:2379: i/o timeout\""}
[2022/11/09 06:38:54.873 +00:00] [WARN] [sessionutil/session_util.go:153] ["failed to initialize session"] [error="All attempts results:\nattempt #1:context deadline exceeded\nattempt #2:context deadline exceeded\nattempt #3:context deadline exceeded\nattempt #4:context deadline exceeded\nattempt #5:context deadline exceeded\nattempt #6:context deadline exceeded\nattempt #7:context deadline exceeded\nattempt #8:context deadline exceeded\nattempt #9:context deadline exceeded\nattempt #10:context deadline exceeded\nattempt #11:context deadline exceeded\n"]
[2022/11/09 06:38:54.873 +00:00] [DEBUG] [client/client.go:59] ["QueryCoordClient NewClient failed"] [error="new session error, maybe can not connect to etcd"]
[2022/11/09 06:38:54.873 +00:00] [WARN] [proxy/service.go:360] ["failed to create RootCoord client for Proxy"] [error="new session error, maybe can not connect to etcd"]
[2022/11/09 06:38:54.873 +00:00] [WARN] [proxy/service.go:289] ["init Proxy server failed"] [error="new session error, maybe can not connect to etcd"]
[2022/11/09 06:38:54.873 +00:00] [WARN] [components/proxy.go:51] ["failed to start Proxy"] [error="new session error, maybe can not connect to etcd"]
[2022/11/09 06:38:54.964 +00:00] [WARN] [sessionutil/session_util.go:153] ["failed to initialize session"] [error="All attempts results:\nattempt #1:context deadline exceeded\nattempt #2:context deadline exceeded\nattempt #3:context deadline exceeded\nattempt #4:context deadline exceeded\nattempt #5:context deadline exceeded\nattempt #6:context deadline exceeded\nattempt #7:context deadline exceeded\nattempt #8:context deadline exceeded\nattempt #9:context deadline exceeded\nattempt #10:context deadline exceeded\nattempt #11:context deadline exceeded\n"]
[2022/11/09 06:38:54.964 +00:00] [DEBUG] [client/client.go:55] ["DataCoordClient NewClient failed"] [error="new session error, maybe can not connect to etcd"]
panic: new session error, maybe can not connect to etcd

goroutine 156 [running]:
github.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).setClient.func1(0xc00013f3d0, 0xb, 0xc000a5c8c0, 0x0, 0x0)
        /go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:119 +0xa5
github.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).init(0xc000a4e790, 0x8bdf3e, 0xc000b42fc8)
        /go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:199 +0x879
github.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).Run(0xc000a4e790, 0xc000a4e700, 0x0)
        /go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:141 +0x2f
github.com/milvus-io/milvus/cmd/components.(*RootCoord).Run(0xc000a47200, 0xffffffffffffffff, 0x43ca108)
        /go/src/github.com/milvus-io/milvus/cmd/components/root_coord.go:55 +0x33
github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runRootCoord.func1(0x1, 0x43b7d10, 0xc000ac6000, 0xc000a60110, 0xc000a704c0, 0xc000b42fc0)
        /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:123 +0x125
created by github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runRootCoord
        /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:106 +0xba

**Comment by yanliang567** [comment]
seems like the etcd service was down. could you please double check the etcd status? @SamrudhiRRao

**Comment by SamrudhiRRao** [comment]
ETCD is up and running.

CONTAINER ID   IMAGE                                      COMMAND                  CREATED       STATUS                 PORTS                                           NAMES
29b44e1663d4   quay.io/coreos/etcd:v3.5.0                 "etcd -advertise-cli…"   2 hours ago   Up 2 hours             2379-2380/tcp                                   milvus-etcd

**Comment by SamrudhiRRao** [comment]
@yanliang567 I have attached milvus-standalone and milvus-etcd log files.

[milvus-etcd.log](https://github.com/milvus-io/milvus/files/9969546/milvus-etcd.log)
[milvus-standalone.log](https://github.com/milvus-io/milvus/files/9969549/milvus-standalone.log)

**Comment by jiaoew1991** [comment]
Milvus cannot connect to Etcd, could you confirm that Etcd and Milvus images are linked correctly?

<img width="1870" alt="image" src="https://user-images.githubusercontent.com/2297455/200988762-2c5c3919-c571-4673-b7a8-6e89d5a336d0.png">

**Comment by SamrudhiRRao** [comment]
I have replaced the docker compose file with the below attached docker compose file and it is working. Not sure whether docker compose file makes a difference. In future if the problem occurs I will consider the solution provided by @jiaoew1991 
[dockercompose.txt](https://github.com/milvus-io/milvus/files/9978366/dockercompose.txt)

**Comment by haikuoxin** [comment]
have any update about this problem?
