### ISSUE TITLE
[Bug]: Search failed with error `message=<_MultiThreadedRendezvous of RPC that terminated with:status = StatusCode.DEADLINE_EXCEEDED` after upgrading from 2.1.4 to 2.2.0

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#20445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.4 --> 2.2.0-20221109-b007daa2
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2022-11-09T07:05:10.117Z] + python3 scripts/second_recall_test.py --host 10.101.142.198

[2022-11-09T07:08:46.506Z] RPC error: [search], <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:

[2022-11-09T07:08:46.506Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2022-11-09T07:08:46.506Z] 	details = "Deadline Exceeded"

[2022-11-09T07:08:46.506Z] 	debug_error_string = "{"created":"@1667977712.016076497","description":"Error received from peer ipv4:10.101.142.198:19530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"Deadline Exceeded","grpc_status":4}"

[2022-11-09T07:08:46.506Z] >)>, <Time:{'RPC start': '2022-11-09 07:05:11.830060', 'RPC error': '2022-11-09 07:08:32.018305'}>

[2022-11-09T07:08:46.506Z] 

[2022-11-09T07:08:46.506Z] Search...

[2022-11-09T07:08:46.506Z] Traceback (most recent call last):

[2022-11-09T07:08:46.506Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2022-11-09T07:08:46.506Z]     return func(self, *args, **kwargs)

[2022-11-09T07:08:46.506Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 478, in search

[2022-11-09T07:08:46.506Z]     return self._execute_search_requests(requests, timeout, **_kwargs)

[2022-11-09T07:08:46.506Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 442, in _execute_search_requests

[2022-11-09T07:08:46.506Z]     raise pre_err

[2022-11-09T07:08:46.506Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 430, in _execute_search_requests

[2022-11-09T07:08:46.506Z]     response = ft.result()

[2022-11-09T07:08:46.506Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 744, in result

[2022-11-09T07:08:46.506Z]     raise self

[2022-11-09T07:08:46.506Z] grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:

[2022-11-09T07:08:46.506Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2022-11-09T07:08:46.506Z] 	details = "Deadline Exceeded"

[2022-11-09T07:08:46.506Z] 	debug_error_string = "{"created":"@1667977712.016076497","description":"Error received from peer ipv4:10.101.142.198:19530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"Deadline Exceeded","grpc_status":4}"

[2022-11-09T07:08:46.506Z] >

[2022-11-09T07:08:46.506Z] 

[2022-11-09T07:08:46.506Z] The above exception was the direct cause of the following exception:

[2022-11-09T07:08:46.506Z] 

[2022-11-09T07:08:46.506Z] Traceback (most recent call last):

[2022-11-09T07:08:46.507Z]   File "scripts/second_recall_test.py", line 64, in <module>

[2022-11-09T07:08:46.507Z]     search_test(host)

[2022-11-09T07:08:46.507Z]   File "scripts/second_recall_test.py", line 33, in search_test

[2022-11-09T07:08:46.507Z]     res = collection.search(

[2022-11-09T07:08:46.507Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 658, in search

[2022-11-09T07:08:46.507Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,

[2022-11-09T07:08:46.507Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2022-11-09T07:08:46.507Z]     raise e

[2022-11-09T07:08:46.507Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2022-11-09T07:08:46.507Z]     return func(*args, **kwargs)

[2022-11-09T07:08:46.507Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2022-11-09T07:08:46.507Z]     ret = func(self, *args, **kwargs)

[2022-11-09T07:08:46.507Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 58, in handler

[2022-11-09T07:08:46.507Z]     raise MilvusException(message=str(e)) from e

[2022-11-09T07:08:46.507Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:

[2022-11-09T07:08:46.507Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2022-11-09T07:08:46.507Z] 	details = "Deadline Exceeded"

[2022-11-09T07:08:46.507Z] 	debug_error_string = "{"created":"@1667977712.016076497","description":"Error received from peer ipv4:10.101.142.198:19530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"Deadline Exceeded","grpc_status":4}"

[2022-11-09T07:08:46.507Z] >)>

script returned exit code 1
```

### Milvus Log

milvus mode: cluster deploy task: upgrade old image tag: v2.1.4 new image tag: 2.2.0-latest
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_kafka_for_release/detail/deploy_test_kafka_for_release/344/pipeline/320
![image](https://user-images.githubusercontent.com/12268675/200817325-0aded36d-3899-4546-8c80-1ea3d109e65f.png)

log:
[artifacts-kafka-cluster-upgrade-344-pytest-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/9970485/artifacts-kafka-cluster-upgrade-344-pytest-logs.1.tar.gz)
[artifacts-kafka-cluster-upgrade-344-server-first-deployment-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/9970489/artifacts-kafka-cluster-upgrade-344-server-first-deployment-logs.1.tar.gz)
[artifacts-kafka-cluster-upgrade-344-server-second-deployment-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/9970491/artifacts-kafka-cluster-upgrade-344-server-second-deployment-logs.1.tar.gz)

**Comment by zhuwenxing** [comment]
milvus mode: cluster deploy task: upgrade old image tag: v2.1.4 new image tag: 2.2.0-latest
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_kafka_for_release/detail/deploy_test_kafka_for_release/354/pipeline
log:

[artifacts-kafka-cluster-upgrade-354-server-second-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/9979513/artifacts-kafka-cluster-upgrade-354-server-second-deployment-logs.tar.gz)
[artifacts-kafka-cluster-upgrade-354-server-first-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/9979514/artifacts-kafka-cluster-upgrade-354-server-first-deployment-logs.tar.gz)
[artifacts-kafka-cluster-upgrade-354-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9979515/artifacts-kafka-cluster-upgrade-354-pytest-logs.tar.gz)

**Comment by jaime0815** [comment]
the reason still is time tick received slowly

**Comment by jaime0815** [comment]
verify this case after #20542 #20597 check in 2.2.0 branch

**Comment by zhuwenxing** [comment]
milvus mode: cluster deploy task: upgrade old image tag: v2.1.4 new image tag: 2.2.0-20221115-31ee7098
This issue is still reproduced.
![image](https://user-images.githubusercontent.com/12268675/202079164-a53002f7-0c6d-4073-bb1d-b4add1657528.png)

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_kafka_for_release/detail/deploy_test_kafka_for_release/394/pipeline
log:
[artifacts-kafka-cluster-upgrade-394-server-first-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/10017981/artifacts-kafka-cluster-upgrade-394-server-first-deployment-logs.tar.gz)
[artifacts-kafka-cluster-upgrade-394-server-second-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/10017982/artifacts-kafka-cluster-upgrade-394-server-second-deployment-logs.tar.gz)
[artifacts-kafka-cluster-upgrade-394-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10017984/artifacts-kafka-cluster-upgrade-394-pytest-logs.tar.gz)

**Comment by jaime0815** [comment]
2.2 reinstall all passed for cluster and standalone mode.

due to the checkpoint at the farther point, the upgrading test still fails

the two tests have passed after upgrading with standalone deployment 
![image](https://user-images.githubusercontent.com/4024711/202093434-9848e4b4-d1eb-4f53-b150-e97a598dc7f2.png)

standalone model produces time tick latency:
![image](https://user-images.githubusercontent.com/4024711/202092413-d1b21e1a-30bb-4a88-88f8-27ef7ddc2745.png)
cluster mode produces time tick latency:
![image](https://user-images.githubusercontent.com/4024711/202092586-a4742111-516b-4888-b7c8-61839c9a7790.png)
it is obvious that the latency has nearly doubled for the standalone model than the cluster model.
