### ISSUE TITLE
[Bug]: Search failed with error `Invalid shard leader` after upgrading from 2.1.4 to 2.2.0

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#20444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.4 --> 2.2.0-20221109-b007daa2
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2022-11-09T07:13:39.366Z] collection name: task_1_ANNOY

[2022-11-09T07:13:39.366Z] load collection

[2022-11-09T07:13:39.366Z] load time: 424.7682

[2022-11-09T07:13:39.366Z] {'metric_type': 'L2', 'params': {'search_k': 1000}}

[2022-11-09T07:13:39.366Z] 

[2022-11-09T07:13:39.366Z] Search...

[2022-11-09T07:13:39.366Z] Traceback (most recent call last):

[2022-11-09T07:13:39.366Z]   File "scripts/action_after_upgrade.py", line 107, in <module>

[2022-11-09T07:13:39.366Z]     task_1(data_size, host)

[2022-11-09T07:13:39.366Z]   File "scripts/action_after_upgrade.py", line 20, in task_1

[2022-11-09T07:13:39.366Z]     load_and_search(prefix)

[2022-11-09T07:13:39.366Z]   File "/home/jenkins/agent/workspace/tests/python_client/deploy/scripts/utils.py", line 194, in load_and_search

[2022-11-09T07:13:39.366Z]     res = c.search(

[2022-11-09T07:13:39.366Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 658, in search

[2022-11-09T07:13:39.366Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,

[2022-11-09T07:13:39.366Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2022-11-09T07:13:39.366Z]     raise e

[2022-11-09T07:13:39.366Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2022-11-09T07:13:39.366Z]     return func(*args, **kwargs)

[2022-11-09T07:13:39.366Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2022-11-09T07:13:39.366Z]     ret = func(self, *args, **kwargs)

[2022-11-09T07:13:39.366Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2022-11-09T07:13:39.366Z]     raise e

[2022-11-09T07:13:39.366Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2022-11-09T07:13:39.366Z]     return func(self, *args, **kwargs)

[2022-11-09T07:13:39.366Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 478, in search

[2022-11-09T07:13:39.366Z]     return self._execute_search_requests(requests, timeout, **_kwargs)

[2022-11-09T07:13:39.366Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 442, in _execute_search_requests

[2022-11-09T07:13:39.366Z]     raise pre_err

[2022-11-09T07:13:39.366Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 433, in _execute_search_requests

[2022-11-09T07:13:39.366Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2022-11-09T07:13:39.366Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Invalid shard leader)>
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_kafka_for_release/detail/deploy_test_kafka_for_release/344/pipeline

![image](https://user-images.githubusercontent.com/12268675/200815052-adac6a84-5f86-43f4-b674-752f3483657e.png)

log:
[artifacts-kafka-cluster-upgrade-344-server-second-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/9970369/artifacts-kafka-cluster-upgrade-344-server-second-deployment-logs.tar.gz)

[artifacts-kafka-cluster-upgrade-344-server-first-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/9970371/artifacts-kafka-cluster-upgrade-344-server-first-deployment-logs.tar.gz)

[artifacts-kafka-cluster-upgrade-344-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9970377/artifacts-kafka-cluster-upgrade-344-pytest-logs.tar.gz)

**Comment by yah01** [comment]
/assign @zhuwenxing 
plz check with #20456, and #20487 for v2.2.0

**Comment by zhuwenxing** [comment]
Not reproduced
