### ISSUE TITLE
[Bug]: Collection is not loaded after reinstallation when collection has been loaded for 2.2.0 branch

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#20443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-20221109-b007daa2
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2022-11-09T04:29:25.733Z] + python3 scripts/second_recall_test.py --host 10.101.82.62

[2022-11-09T04:29:27.612Z] RPC error: [search], <MilvusException: (code=1, message=collection:sift_128_euclidean or partition:[] not loaded into memory when search)>, <Time:{'RPC start': '2022-11-09 04:29:26.887182', 'RPC error': '2022-11-09 04:29:27.144092'}>

[2022-11-09T04:29:27.612Z] 

[2022-11-09T04:29:27.612Z] Search...

[2022-11-09T04:29:27.612Z] Traceback (most recent call last):

[2022-11-09T04:29:27.612Z]   File "scripts/second_recall_test.py", line 64, in <module>

[2022-11-09T04:29:27.612Z]     search_test(host)

[2022-11-09T04:29:27.612Z]   File "scripts/second_recall_test.py", line 33, in search_test

[2022-11-09T04:29:27.612Z]     res = collection.search(

[2022-11-09T04:29:27.612Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 658, in search

[2022-11-09T04:29:27.612Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,

[2022-11-09T04:29:27.612Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2022-11-09T04:29:27.612Z]     raise e

[2022-11-09T04:29:27.612Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2022-11-09T04:29:27.612Z]     return func(*args, **kwargs)

[2022-11-09T04:29:27.612Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2022-11-09T04:29:27.612Z]     ret = func(self, *args, **kwargs)

[2022-11-09T04:29:27.612Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2022-11-09T04:29:27.612Z]     raise e

[2022-11-09T04:29:27.612Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2022-11-09T04:29:27.612Z]     return func(self, *args, **kwargs)

[2022-11-09T04:29:27.612Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 478, in search

[2022-11-09T04:29:27.612Z]     return self._execute_search_requests(requests, timeout, **_kwargs)

[2022-11-09T04:29:27.612Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 442, in _execute_search_requests

[2022-11-09T04:29:27.612Z]     raise pre_err

[2022-11-09T04:29:27.612Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 433, in _execute_search_requests

[2022-11-09T04:29:27.612Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2022-11-09T04:29:27.612Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection:sift_128_euclidean or partition:[] not loaded into memory when search)>

script returned exit code 1
```

### Expected Behavior

all test cases passed

### Milvus Log

milvus mode: cluster deploy task: reinstall old image tag: v2.1.4 new image tag: 2.2.0-latest
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_kafka_for_release/detail/deploy_test_kafka_for_release/342/pipeline/320

log:

[artifacts-kafka-cluster-reinstall-342-server-second-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/9970260/artifacts-kafka-cluster-reinstall-342-server-second-deployment-logs.tar.gz)
[artifacts-kafka-cluster-reinstall-342-server-first-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/9970264/artifacts-kafka-cluster-reinstall-342-server-first-deployment-logs.tar.gz)
[artifacts-kafka-cluster-reinstall-342-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9970267/artifacts-kafka-cluster-reinstall-342-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
/assign @jiaoew1991 
PTAL

**Comment by jiaoew1991** [comment]
The collection loaded finished at 04:29:28, but the search request start at 04:29:27, the error seems reasonable @zhuwenxing 

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/2297455/201015308-9f0bfb8d-c96f-4ee8-af32-df8eb4fbf8ed.png">

**Comment by zhuwenxing** [comment]
This issue has not happened before, so it means the performance of loading degraded form this aspect
I will add some wait time before searching, and then recheck this issue!
