### ISSUE TITLE
[Bug]: Datanode panic after datacoord pod failure chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#20501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20221110-cd19d99a
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/12268675/201250133-23d2fe8f-5bc6-4e81-99a5-7e91fdf9274e.png)

```
[2022/11/10 19:55:41.045 +00:00] [INFO] [datanode/flow_graph_insert_buffer_node.go:401] ["insertBufferNode syncing BufferData"] [segmentID=437284811168487916] [flushed=false] [dropped=false] [auto=false] [position="channel_name:\"by-dev-rootcoord-dml_12_437284811168484922v0\" msgID:\"f\\r\\000\\000\\000\\000\\000\\000\" msgGroup:\"by-dev-dataNode-17-by-dev-rootcoord-dml_12_437284811168484922v0\" timestamp:437285064764293121 "] [channel=by-dev-rootcoord-dml_12_437284811168484922v0]
[2022/11/10 19:55:41.046 +00:00] [INFO] [datanode/flow_graph_delete_node.go:126] ["should flush segments, "] [seg_count=0]
[2022/11/10 19:55:41.047 +00:00] [INFO] [datanode/flow_graph_delete_node.go:126] ["should flush segments, "] [seg_count=0]
[2022/11/10 19:55:41.048 +00:00] [INFO] [datanode/flush_manager.go:288] ["handling insert task"] ["segment ID"=437284811168487916] [flushed=false] [dropped=false] [position="channel_name:\"by-dev-rootcoord-dml_12_437284811168484922v0\" msgID:\"f\\r\\000\\000\\000\\000\\000\\000\" msgGroup:\"by-dev-dataNode-17-by-dev-rootcoord-dml_12_437284811168484922v0\" timestamp:437285064764293121 "]
[2022/11/10 19:55:41.048 +00:00] [INFO] [datanode/flow_graph_delete_node.go:126] ["should flush segments, "] [seg_count=0]
[2022/11/10 19:55:41.048 +00:00] [INFO] [datanode/flush_manager.go:140] ["new flush task runner created and initialized"] ["segment ID"=437284811168487916] ["pos message ID"="f\r\u0000\u0000\u0000\u0000\u0000\u0000"]
[2022/11/10 19:55:41.048 +00:00] [INFO] [datanode/flush_task.go:134] ["running flush insert task"] ["segment ID"=437284811168487916] [flushed=false] [dropped=false] [position="channel_name:\"by-dev-rootcoord-dml_12_437284811168484922v0\" msgID:\"f\\r\\000\\000\\000\\000\\000\\000\" msgGroup:\"by-dev-dataNode-17-by-dev-rootcoord-dml_12_437284811168484922v0\" timestamp:437285064764293121 "] [PosTime=2022/11/10 19:55:40.855 +00:00]
[2022/11/10 19:55:41.048 +00:00] [INFO] [datanode/channel_meta.go:358] ["roll pk stats"] ["segment id"=437284811168487916]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x28558d4]

goroutine 6210 [running]:
github.com/milvus-io/milvus/internal/datanode.(*DelDataBuf).mergeDelDataBuf(0xc004c99f00, 0xc008ba6500)
	/go/src/github.com/milvus-io/milvus/internal/datanode/buffer.go:307 +0x54
github.com/milvus-io/milvus/internal/datanode.(*DelBufferManager).CompactSegBuf(0xc003f48340, 0x0?, {0xc0011cc800, 0x7, 0x3cdacad?})
	/go/src/github.com/milvus-io/milvus/internal/datanode/buffer.go:147 +0x136
github.com/milvus-io/milvus/internal/datanode.(*deleteNode).updateCompactedSegments(0xc004f14070)
	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_delete_node.go:193 +0x125
github.com/milvus-io/milvus/internal/datanode.(*deleteNode).Operate(0xc004f14070, {0xc000c78580, 0x1, 0x1})
	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_delete_node.go:97 +0x4be
github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work(0xc003f29450)
	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:127 +0x2b8
created by github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start
	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:70 +0x79
```

### Milvus Log

chaos type: pod-failure image tag: master-20221110-cd19d99a target pod: datacoord
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka/detail/chaos-test-kafka/2651/pipeline
log:
[artifacts-datacoord-pod-failure-2651-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/9986052/artifacts-datacoord-pod-failure-2651-server-logs.1.tar.gz)

[artifacts-datacoord-pod-failure-2651-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9986054/artifacts-datacoord-pod-failure-2651-pytest-logs.tar.gz)

**Comment by xiaofan-luan** [comment]
/assign @MrPresent-Han 
pls help on it

**Comment by xiaocai2333** [comment]
there is another problem here.  @MrPresent-Han 

![image](https://user-images.githubusercontent.com/46207236/201855914-195ec157-4643-4543-b815-f987f028931f.png)
![image](https://user-images.githubusercontent.com/46207236/201856044-7e495569-7d35-4a26-a3b9-b5eadc5ece57.png)
![image](https://user-images.githubusercontent.com/46207236/201857211-b932f47d-34c5-4d6b-a012-981cd183a615.png)


in step 6, panic... because the `buf.endPos` is nil. Should we fill `startPos` and `endPos` in step 2? like:
![image](https://user-images.githubusercontent.com/46207236/201856789-334575f0-474f-4fdc-9b52-f434d5a228d6.png)

```
[2022/11/15 15:48:16.122 +08:00] [INFO] [datanode/segment.go:137] ["evictHistoryInsertBuffer done"] [segmentID=437386672262500719] [ts=2022/11/15 15:48:15.944 +08:00] [channel=by-dev-rootcoord-dml_0_437386672261300227v0]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x286a091]

goroutine 6183 [running]:
github.com/milvus-io/milvus/internal/datanode.(*Segment).evictHistoryDeleteBuffer(0xc002b1e270, 0xc00136af00)
	/home/zc/work/milvus/internal/datanode/segment.go:154 +0x91
github.com/milvus-io/milvus/internal/datanode.(*ChannelMeta).evictHistoryDeleteBuffer(0xc0003b9290, 0x611e8dc6db2516f, 0xc0012cdaa8?)
	/home/zc/work/milvus/internal/datanode/channel_meta.go:773 +0x1a5
github.com/milvus-io/milvus/internal/datanode.flushNotifyFunc.func1(0xc0004caa50)
	/home/zc/work/milvus/internal/datanode/flush_manager.go:854 +0xfc6
github.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).waitFinish(0xc000eaa9c0, 0xc000e4c7e0, 0xc001298bb0)
	/home/zc/work/milvus/internal/datanode/flush_task.go:204 +0xdb
created by github.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).init.func1
	/home/zc/work/milvus/internal/datanode/flush_task.go:121 +0xf1

```

**Comment by zhuwenxing** [comment]
> there is another problem here. @MrPresent-Han
> 
> ![image](https://user-images.githubusercontent.com/46207236/201855914-195ec157-4643-4543-b815-f987f028931f.png) ![image](https://user-images.githubusercontent.com/46207236/201856044-7e495569-7d35-4a26-a3b9-b5eadc5ece57.png) ![image](https://user-images.githubusercontent.com/46207236/201857211-b932f47d-34c5-4d6b-a012-981cd183a615.png)
> 
> in step 6, panic... because the `buf.endPos` is nil. Should we fill `startPos` and `endPos` in step 2? like: ![image](https://user-images.githubusercontent.com/46207236/201856789-334575f0-474f-4fdc-9b52-f434d5a228d6.png)
> 
> ```
> [2022/11/15 15:48:16.122 +08:00] [INFO] [datanode/segment.go:137] ["evictHistoryInsertBuffer done"] [segmentID=437386672262500719] [ts=2022/11/15 15:48:15.944 +08:00] [channel=by-dev-rootcoord-dml_0_437386672261300227v0]
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x286a091]
> 
> goroutine 6183 [running]:
> github.com/milvus-io/milvus/internal/datanode.(*Segment).evictHistoryDeleteBuffer(0xc002b1e270, 0xc00136af00)
> 	/home/zc/work/milvus/internal/datanode/segment.go:154 +0x91
> github.com/milvus-io/milvus/internal/datanode.(*ChannelMeta).evictHistoryDeleteBuffer(0xc0003b9290, 0x611e8dc6db2516f, 0xc0012cdaa8?)
> 	/home/zc/work/milvus/internal/datanode/channel_meta.go:773 +0x1a5
> github.com/milvus-io/milvus/internal/datanode.flushNotifyFunc.func1(0xc0004caa50)
> 	/home/zc/work/milvus/internal/datanode/flush_manager.go:854 +0xfc6
> github.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).waitFinish(0xc000eaa9c0, 0xc000e4c7e0, 0xc001298bb0)
> 	/home/zc/work/milvus/internal/datanode/flush_task.go:204 +0xdb
> created by github.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).init.func1
> 	/home/zc/work/milvus/internal/datanode/flush_task.go:121 +0xf1
> ```

Yes， I have come up with the same problem

```
[2022/11/15 07:08:15.945 +00:00] [DEBUG] [querynode/validate.go:50] ["read target partitions"] [traceID=4a7ed9f5da8431d6] [collectionID=437386182968938034] [partitionIDs="[437386182968938035]"]
[2022/11/15 07:08:15.945 +00:00] [DEBUG] [querynode/segment.go:399] ["do retrieve on segment"] [msgID=437386240491520003] [segmentID=437386182968938058] [segmentType=3]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x2855294]

goroutine 8148 [running]:
github.com/milvus-io/milvus/internal/datanode.(*DelDataBuf).mergeDelDataBuf(0xc00906bf80, 0xc00b505780)
	/go/src/github.com/milvus-io/milvus/internal/datanode/buffer.go:306 +0x54
github.com/milvus-io/milvus/internal/datanode.(*DelBufferManager).CompactSegBuf(0xc00b650180, 0x40d25e0?, {0xc001e5c180, 0x9, 0x4?})
	/go/src/github.com/milvus-io/milvus/internal/datanode/buffer.go:146 +0x136
github.com/milvus-io/milvus/internal/datanode.(*deleteNode).updateCompactedSegments(0xc006776310)
	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_delete_node.go:193 +0x125
github.com/milvus-io/milvus/internal/datanode.(*deleteNode).Operate(0xc006776310, {0xc012bba1f0, 0x1, 0x1})
	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_delete_node.go:97 +0x4be
github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work(0xc00b65e5a0)
	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:127 +0x2b8
created by github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start
	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:70 +0x79
```


```
[2022-11-15T07:09:36.852Z] + kubectl get pods -o wide

[2022-11-15T07:09:36.852Z] + grep standalone-pod-kill-1854

[2022-11-15T07:09:37.410Z] standalone-pod-kill-1854-etcd-0                                   1/1     Running     0              6m32s   10.102.6.253    devops-node10   <none>           <none>

[2022-11-15T07:09:37.410Z] standalone-pod-kill-1854-milvus-standalone-687b7f5b4d-fzsnw       0/1     Running     2 (80s ago)    6m32s   10.102.6.252    devops-node10   <none>           <none>

[2022-11-15T07:09:37.410Z] standalone-pod-kill-1854-minio-585565c98f-cnwcp                   1/1     Running     0              6m32s   10.102.6.250    devops-node10   <none>           <none>
```


failed job:
https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-for-release/detail/chaos-test-for-release/1854/pipeline
log:
[artifacts-standalone-pod-kill-1854-server-logs (3).tar.gz](https://github.com/milvus-io/milvus/files/10010660/artifacts-standalone-pod-kill-1854-server-logs.3.tar.gz)
[artifacts-standalone-pod-kill-1854-pytest-logs (2).tar.gz](https://github.com/milvus-io/milvus/files/10010662/artifacts-standalone-pod-kill-1854-pytest-logs.2.tar.gz)

**Comment by zhuwenxing** [comment]
image: master-20221115-c848896b
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/3129/pipeline
log:
[artifacts-standalone-pod-kill-3129-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10010688/artifacts-standalone-pod-kill-3129-pytest-logs.tar.gz)

[artifacts-standalone-pod-kill-3129-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/10010690/artifacts-standalone-pod-kill-3129-server-logs.1.tar.gz)

```
[2022/11/15 07:40:22.941 +00:00] [INFO] [datanode/segment.go:137] ["evictHistoryInsertBuffer done"] [segmentID=437386708916049131] [ts=2022/11/15 07:40:22.730 +00:00] [channel=by-dev-rootcoord-dml_12_437386657830997549v0]
[2022/11/15 07:40:22.941 +00:00] [INFO] [datanode/segment.go:160] ["evictHistoryDeleteBuffer done"] [segmentID=437386708916049131] [ts=2022/11/15 07:40:22.730 +00:00] [channel=by-dev-rootcoord-dml_12_437386657830997549v0]
[2022/11/15 07:40:22.945 +00:00] [INFO] [datacoord/meta.go:526] ["meta update: update flush segments info - update flush segments info successfully"] ["segment ID"=437386708916049133]
[2022/11/15 07:40:22.945 +00:00] [INFO] [datacoord/services.go:446] ["flush segment with meta"] ["segment id"=437386708916049133] [meta=null]
[2022/11/15 07:40:22.945 +00:00] [INFO] [datanode/segment.go:137] ["evictHistoryInsertBuffer done"] [segmentID=437386708916049133] [ts=2022/11/15 07:40:22.730 +00:00] [channel=by-dev-rootcoord-dml_13_437386657830997549v1]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x289fe71]

goroutine 80795 [running]:
github.com/milvus-io/milvus/internal/datanode.(*Segment).evictHistoryDeleteBuffer(0xc00d6844e0, 0xc00d242240)
	/go/src/github.com/milvus-io/milvus/internal/datanode/segment.go:154 +0x91
github.com/milvus-io/milvus/internal/datanode.(*ChannelMeta).evictHistoryDeleteBuffer(0xc005b106c0, 0x611e8e4f66b14ed, 0xc00ccd1aa8?)
	/go/src/github.com/milvus-io/milvus/internal/datanode/channel_meta.go:773 +0x1a5
github.com/milvus-io/milvus/internal/datanode.flushNotifyFunc.func1(0xc00dc26910)
	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_manager.go:854 +0xfc6
github.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).waitFinish(0xc00b48f800, 0xc005b4a240, 0xc00d22a730)
	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_task.go:204 +0xdb
created by github.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).init.func1
	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_task.go:121 +0xf1

```

```
[2022-11-15T07:42:09.281Z] + kubectl get pods -o wide

[2022-11-15T07:42:09.281Z] + grep standalone-pod-kill-3129

[2022-11-15T07:42:09.841Z] standalone-pod-kill-3129-etcd-0                                 1/1     Running     0              12m     10.102.8.185    devops-node12   <none>           <none>

[2022-11-15T07:42:09.842Z] standalone-pod-kill-3129-milvus-standalone-656b6f74b7-9fz5j     0/1     Running     2 (106s ago)   12m     10.102.8.184    devops-node12   <none>           <none>

[2022-11-15T07:42:09.842Z] standalone-pod-kill-3129-minio-647fbc5f5-947l9                  1/1     Running     0              12m     10.102.8.183    devops-node12   <none>           <none>

collecte logs

```

**Comment by MrPresent-Han** [comment]
This is not a bug introduced by PR #20563 but another original defect due to commit cd19d99a which is merged on 2022-11-10, as well as the bug fixed in PR#20563

**Comment by MrPresent-Han** [comment]
/assign @bigsheeper 
please have a look at this bug related to start-end position init inside delDataBuf

**Comment by bigsheeper** [comment]
should be fixed, please help to verify @zhuwenxing

**Comment by zhuwenxing** [comment]
Not reproduced
