### ISSUE TITLE
[Bug]: Datanode panic during first deploy test without upgrading and reinstallation

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#20571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20221114-a7ba416b
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.2.0.dev72
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/12268675/201642191-f6f3c959-500a-4aed-95ef-f3cd2315d3ce.png)

```
[2022/11/14 10:09:18.161 +00:00] [INFO] [datanode/flush_manager.go:288] ["handling insert task"] ["segment ID"=437366331509866311] [flushed=false] [dropped=false] [position="channel_name:\"by-dev-rootcoord-dml_71_437366331509865851v1\" msgID:\"\\010I\\020\\270\\002\\030\\000 \\000\" msgGroup:\"by-dev-dataNode-18-by-dev-rootcoord-dml_71_437366331509865851v1\" timestamp:437366438731186181 "]
[2022/11/14 10:09:18.161 +00:00] [INFO] [datanode/flush_manager.go:140] ["new flush task runner created and initialized"] ["segment ID"=437366331509866311] ["pos message ID"="\u0008I\u0010\ufffd\u0002\u0018\u0000 \u0000"]
[2022/11/14 10:09:18.161 +00:00] [INFO] [datanode/flush_task.go:134] ["running flush insert task"] ["segment ID"=437366331509866311] [flushed=false] [dropped=false] [position="channel_name:\"by-dev-rootcoord-dml_71_437366331509865851v1\" msgID:\"\\010I\\020\\270\\002\\030\\000 \\000\" msgGroup:\"by-dev-dataNode-18-by-dev-rootcoord-dml_71_437366331509865851v1\" timestamp:437366438731186181 "] [PosTime=2022/11/14 10:09:17.904 +00:00]
[2022/11/14 10:09:18.161 +00:00] [INFO] [datanode/channel_meta.go:358] ["roll pk stats"] ["segment id"=437366331509866311]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x2857ab4]

goroutine 391 [running]:
github.com/milvus-io/milvus/internal/datanode.(*DelDataBuf).mergeDelDataBuf(0xc004f14500, 0xc00302ef80)
	/go/src/github.com/milvus-io/milvus/internal/datanode/buffer.go:307 +0x54
github.com/milvus-io/milvus/internal/datanode.(*DelBufferManager).CompactSegBuf(0xc0005550c0, 0x0?, {0xc000628be0, 0x4, 0x3cb3c38?})
	/go/src/github.com/milvus-io/milvus/internal/datanode/buffer.go:147 +0x136
github.com/milvus-io/milvus/internal/datanode.(*deleteNode).updateCompactedSegments(0xc00036cf50)
	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_delete_node.go:193 +0x125
github.com/milvus-io/milvus/internal/datanode.(*deleteNode).Operate(0xc00036cf50, {0xc0018b0750, 0x1, 0x1})
	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_delete_node.go:97 +0x4be
github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work(0xc000197540)
	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:127 +0x2b8
created by github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start
	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:70 +0x79
```

```
[2022-11-14T10:16:03.698Z] [2022-11-14 10:13:47 - INFO - ci_test]: [setup_method] Start setup test case test_task_all. (client_base.py:37)
[2022-11-14T10:16:03.698Z] ------------------------------ Captured log call -------------------------------
[2022-11-14T10:16:03.698Z] [get_env_variable] failed to get environment variables : 'CI_LOG_PATH', use default path : /tmp/ci_logs
[2022-11-14T10:16:03.698Z] [create_path] folder(/tmp/ci_logs) is not exist.
[2022-11-14T10:16:03.698Z] [create_path] create path now...
[2022-11-14T10:16:03.698Z] [2022-11-14 10:13:47 - INFO - ci_test]: collection name: deploy_test_index_type_BIN_IVF_FLAT_is_compacted_not_compacted_segment_status_all_is_string_indexed_not_string_indexed_replica_number_2_is_deleted_is_deleted_data_size_3000 (test_action_first_deployment.py:81)
[2022-11-14T10:16:03.698Z] [2022-11-14 10:13:47 - DEBUG - ci_test]: (api_request)  : [Connections.connect] args: ['default'], kwargs: {'host': '10.101.230.253', 'port': 19530} (api_request.py:56)
[2022-11-14T10:16:03.698Z] [2022-11-14 10:13:50 - ERROR - ci_test]: Traceback (most recent call last):
[2022-11-14T10:16:03.698Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 111, in _wait_for_channel_ready
[2022-11-14T10:16:03.698Z]     grpc.channel_ready_future(self._channel).result(timeout=timeout)
[2022-11-14T10:16:03.698Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_utilities.py", line 139, in result
[2022-11-14T10:16:03.698Z]     self._block(timeout)
[2022-11-14T10:16:03.698Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_utilities.py", line 85, in _block
[2022-11-14T10:16:03.698Z]     raise grpc.FutureTimeoutError()
[2022-11-14T10:16:03.698Z] grpc.FutureTimeoutError
[2022-11-14T10:16:03.698Z] 
[2022-11-14T10:16:03.698Z] The above exception was the direct cause of the following exception:
[2022-11-14T10:16:03.698Z] 
[2022-11-14T10:16:03.698Z] Traceback (most recent call last):
[2022-11-14T10:16:03.698Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2022-11-14T10:16:03.698Z]     res = func(*args, **_kwargs)
[2022-11-14T10:16:03.698Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2022-11-14T10:16:03.698Z]     return func(*arg, **kwargs)
[2022-11-14T10:16:03.698Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/connections.py", line 303, in connect
[2022-11-14T10:16:03.698Z]     connect_milvus(**kwargs, user=user, password=password)
[2022-11-14T10:16:03.698Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/connections.py", line 274, in connect_milvus
[2022-11-14T10:16:03.698Z]     gh._wait_for_channel_ready(timeout=timeout)
[2022-11-14T10:16:03.698Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 114, in _wait_for_channel_ready
[2022-11-14T10:16:03.698Z]     raise MilvusException(Status.CONNECT_FAILED,
[2022-11-14T10:16:03.698Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on 10.101.230.253:19530. Timeout)>
[2022-11-14T10:16:03.698Z]  (api_request.py:39)
[2022-11-14T10:16:03.698Z] [2022-11-14 10:13:50 - ERROR - ci_test]: (api_response) : <MilvusException: (code=2, message=Fail connecting to server on 10.101.230.253:19530. Timeout)> (api_request.py:40)
[2022-11-14T10:16:03.698Z] ------------- generated html file: file:///tmp/ci_logs/report.html -------------
[2022-11-14T10:16:03.698Z] =========================== short test summary info ============================
[2022-11-14T10:16:03.698Z] FAILED testcases/test_action_first_deployment.py::TestActionFirstDeployment::test_task_all[BIN_IVF_FLAT-all-is_string_indexed-is_deleted-is_compacted-0] - AssertionError
[2022-11-14T10:16:03.698Z] FAILED testcases/test_action_first_deployment.py::TestActionFirstDeployment::test_task_all[BIN_IVF_FLAT-all-is_string_indexed-is_deleted-is_compacted-1] - AssertionError
[2022-11-14T10:16:03.698Z] FAILED testcases/test_action_first_deployment.py::TestActionFirstDeployment::test_task_all[BIN_IVF_FLAT-all-is_string_indexed-is_deleted-is_compacted-2] - AssertionError
[2022-11-14T10:16:03.698Z] FAILED testcases/test_action_first_deployment.py::TestActionFirstDeployment::test_task_all[BIN_IVF_FLAT-all-is_string_indexed-is_deleted-not_compacted-2] - AssertionError
[2022-11-14T10:16:03.698Z] FAILED testcases/test_action_first_deployment.py::TestActionFirstDeployment::test_task_all[BIN_IVF_FLAT-all-not_string_indexed-is_deleted-is_compacted-0] - AssertionError
[2022-11-14T10:16:03.698Z] FAILED testcases/test_action_first_deployment.py::TestActionFirstDeployment::test_task_all[BIN_IVF_FLAT-all-not_string_indexed-is_deleted-is_compacted-1] - AssertionError
[2022-11-14T10:16:03.698Z] FAILED testcases/test_action_first_deployment.py::TestActionFirstDeployment::test_task_all[BIN_IVF_FLAT-all-not_string_indexed-is_deleted-is_compacted-2] - AssertionError
[2022-11-14T10:16:03.698Z] FAILED testcases/test_action_first_deployment.py::TestActionFirstDeployment::test_task_all[BIN_IVF_FLAT-all-not_string_indexed-is_deleted-not_compacted-0] - AssertionError
[2022-11-14T10:16:03.698Z] FAILED testcases/test_action_first_deployment.py::TestActionFirstDeployment::test_task_all[BIN_IVF_FLAT-all-not_string_indexed-is_deleted-not_compacted-1] - AssertionError
[2022-11-14T10:16:03.698Z] FAILED testcases/test_action_first_deployment.py::TestActionFirstDeployment::test_task_all[BIN_IVF_FLAT-all-not_string_indexed-is_deleted-not_compacted-2] - AssertionError
[2022-11-14T10:16:03.698Z] ============ 10 failed, 16 passed, 24 skipped in 695.56s (0:11:35) =============
```

### Expected Behavior

all test cases passed

### Steps To Reproduce

```markdown
1. install Milvus
2. run test case in test/python_client/deploy

pytest testcases/test_action_first_deployment.py -n 2 
```
```


### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test/detail/deploy_test/646/pipeline
log:

[artifacts-pulsar-cluster-reinstall-646-server-logs (2).tar.gz](https://github.com/milvus-io/milvus/files/10002284/artifacts-pulsar-cluster-reinstall-646-server-logs.2.tar.gz)

[artifacts-pulsar-cluster-reinstall-646-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10002288/artifacts-pulsar-cluster-reinstall-646-pytest-logs.tar.gz)


### Anything else?

_No response_

**Comment by zhuwenxing** [comment]
same for standalone
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/3104/pipeline
log:
[artifacts-standalone-pod-kill-3104-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/10002461/artifacts-standalone-pod-kill-3104-server-logs.1.tar.gz)
[artifacts-standalone-pod-kill-3104-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10002462/artifacts-standalone-pod-kill-3104-pytest-logs.tar.gz)

**Comment by soothing-rain** [comment]
Should be fixed in #20563

**Comment by zhuwenxing** [comment]
It is also reproduced in the 2.2 branch. Seems like the same reason.
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-for-release/detail/chaos-test-for-release/1854/pipeline

log:

[artifacts-standalone-pod-kill-1854-server-logs (2).tar.gz](https://github.com/milvus-io/milvus/files/10010180/artifacts-standalone-pod-kill-1854-server-logs.2.tar.gz)

[artifacts-standalone-pod-kill-1854-pytest-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/10010181/artifacts-standalone-pod-kill-1854-pytest-logs.1.tar.gz)




```
[2022/11/15 07:08:15.945 +00:00] [DEBUG] [querynode/validate.go:50] ["read target partitions"] [traceID=4a7ed9f5da8431d6] [collectionID=437386182968938034] [partitionIDs="[437386182968938035]"]
[2022/11/15 07:08:15.945 +00:00] [DEBUG] [querynode/segment.go:399] ["do retrieve on segment"] [msgID=437386240491520003] [segmentID=437386182968938058] [segmentType=3]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x2855294]

goroutine 8148 [running]:
github.com/milvus-io/milvus/internal/datanode.(*DelDataBuf).mergeDelDataBuf(0xc00906bf80, 0xc00b505780)
	/go/src/github.com/milvus-io/milvus/internal/datanode/buffer.go:306 +0x54
github.com/milvus-io/milvus/internal/datanode.(*DelBufferManager).CompactSegBuf(0xc00b650180, 0x40d25e0?, {0xc001e5c180, 0x9, 0x4?})
	/go/src/github.com/milvus-io/milvus/internal/datanode/buffer.go:146 +0x136
github.com/milvus-io/milvus/internal/datanode.(*deleteNode).updateCompactedSegments(0xc006776310)
	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_delete_node.go:193 +0x125
github.com/milvus-io/milvus/internal/datanode.(*deleteNode).Operate(0xc006776310, {0xc012bba1f0, 0x1, 0x1})
	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_delete_node.go:97 +0x4be
github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work(0xc00b65e5a0)
	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:127 +0x2b8
created by github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start
	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:70 +0x79
```

**Comment by zhuwenxing** [comment]
image: master-20221115-c848896b
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/3129/pipeline
log:
[artifacts-standalone-pod-kill-3129-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10010688/artifacts-standalone-pod-kill-3129-pytest-logs.tar.gz)

[artifacts-standalone-pod-kill-3129-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/10010690/artifacts-standalone-pod-kill-3129-server-logs.1.tar.gz)

```
[2022/11/15 07:40:22.941 +00:00] [INFO] [datanode/segment.go:137] ["evictHistoryInsertBuffer done"] [segmentID=437386708916049131] [ts=2022/11/15 07:40:22.730 +00:00] [channel=by-dev-rootcoord-dml_12_437386657830997549v0]
[2022/11/15 07:40:22.941 +00:00] [INFO] [datanode/segment.go:160] ["evictHistoryDeleteBuffer done"] [segmentID=437386708916049131] [ts=2022/11/15 07:40:22.730 +00:00] [channel=by-dev-rootcoord-dml_12_437386657830997549v0]
[2022/11/15 07:40:22.945 +00:00] [INFO] [datacoord/meta.go:526] ["meta update: update flush segments info - update flush segments info successfully"] ["segment ID"=437386708916049133]
[2022/11/15 07:40:22.945 +00:00] [INFO] [datacoord/services.go:446] ["flush segment with meta"] ["segment id"=437386708916049133] [meta=null]
[2022/11/15 07:40:22.945 +00:00] [INFO] [datanode/segment.go:137] ["evictHistoryInsertBuffer done"] [segmentID=437386708916049133] [ts=2022/11/15 07:40:22.730 +00:00] [channel=by-dev-rootcoord-dml_13_437386657830997549v1]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x289fe71]

goroutine 80795 [running]:
github.com/milvus-io/milvus/internal/datanode.(*Segment).evictHistoryDeleteBuffer(0xc00d6844e0, 0xc00d242240)
	/go/src/github.com/milvus-io/milvus/internal/datanode/segment.go:154 +0x91
github.com/milvus-io/milvus/internal/datanode.(*ChannelMeta).evictHistoryDeleteBuffer(0xc005b106c0, 0x611e8e4f66b14ed, 0xc00ccd1aa8?)
	/go/src/github.com/milvus-io/milvus/internal/datanode/channel_meta.go:773 +0x1a5
github.com/milvus-io/milvus/internal/datanode.flushNotifyFunc.func1(0xc00dc26910)
	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_manager.go:854 +0xfc6
github.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).waitFinish(0xc00b48f800, 0xc005b4a240, 0xc00d22a730)
	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_task.go:204 +0xdb
created by github.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).init.func1
	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_task.go:121 +0xf1

```

```
[2022-11-15T07:42:09.281Z] + kubectl get pods -o wide

[2022-11-15T07:42:09.281Z] + grep standalone-pod-kill-3129

[2022-11-15T07:42:09.841Z] standalone-pod-kill-3129-etcd-0                                 1/1     Running     0              12m     10.102.8.185    devops-node12   <none>           <none>

[2022-11-15T07:42:09.842Z] standalone-pod-kill-3129-milvus-standalone-656b6f74b7-9fz5j     0/1     Running     2 (106s ago)   12m     10.102.8.184    devops-node12   <none>           <none>

[2022-11-15T07:42:09.842Z] standalone-pod-kill-3129-minio-647fbc5f5-947l9                  1/1     Running     0              12m     10.102.8.183    devops-node12   <none>           <none>

collecte logs

```

**Comment by MrPresent-Han** [comment]
An existing question which is the same as  https://github.com/milvus-io/milvus/pull/20615, which will be fixed by @bigsheeper

**Comment by zhuwenxing** [comment]
Not reproduced
