### ISSUE TITLE
[Bug]: [Nightly]Query failed with message `fail to search on all shard leaders, err=fail to Query, QueryNode ID = 5, reason=Query 5 failed, reason context canceled err %!w(<nil>)`

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#20580]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: bec1d4c
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.0.dev72
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Query failed with message `fail to search on all shard leaders, err=fail to Query, QueryNode ID = 5, reason=Query 5 failed, reason context canceled err %!w(<nil>)`.
```
[2022-11-14T19:13:00.183Z] [2022-11-14 18:16:43 - ERROR - pymilvus.decorators]: RPC error: [query], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Query, QueryNode ID = 5, reason=Query 5 failed, reason context canceled err %!w(<nil>))>, <Time:{'RPC start': '2022-11-14 18:16:43.627530', 'RPC error': '2022-11-14 18:16:43.878021'}> (decorators.py:108)
[2022-11-14T19:13:00.183Z] [2022-11-14 18:16:43 - ERROR - ci_test]: Traceback (most recent call last):
[2022-11-14T19:13:00.183Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2022-11-14T19:13:00.183Z]     res = func(*args, **_kwargs)
[2022-11-14T19:13:00.183Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2022-11-14T19:13:00.183Z]     return func(*arg, **kwargs)
[2022-11-14T19:13:00.183Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 746, in query
[2022-11-14T19:13:00.183Z]     res = conn.query(self._name, expr, output_fields, partition_names, timeout=timeout, schema=schema, **kwargs)
[2022-11-14T19:13:00.183Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2022-11-14T19:13:00.183Z]     raise e
[2022-11-14T19:13:00.183Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2022-11-14T19:13:00.183Z]     return func(*args, **kwargs)
[2022-11-14T19:13:00.184Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2022-11-14T19:13:00.184Z]     ret = func(self, *args, **kwargs)
[2022-11-14T19:13:00.184Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
[2022-11-14T19:13:00.184Z]     raise e
[2022-11-14T19:13:00.184Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2022-11-14T19:13:00.184Z]     return func(self, *args, **kwargs)
[2022-11-14T19:13:00.184Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 893, in query
[2022-11-14T19:13:00.184Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2022-11-14T19:13:00.184Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Query, QueryNode ID = 5, reason=Query 5 failed, reason context canceled err %!w(<nil>))>
[2022-11-14T19:13:00.184Z]  (api_request.py:39)
[2022-11-14T19:13:00.184Z] [2022-11-14 18:16:43 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Query, QueryNode ID = 5, reason=Query 5 failed, reason context canceled err %!w(<nil>))> (api_request.py:40)
```

### Expected Behavior

PASS

### Steps To Reproduce

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/190/pipeline/155

### Milvus Log

1. log: [artifacts-milvus-distributed-kafka-nightly-190-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/190/artifact/artifacts-milvus-distributed-kafka-nightly-190-pymilvus-e2e-logs.tar.gz)
2. collection name: query_fh3a9h6p
3. failed time: [2022-11-14T18:16:44.824Z] [gw2] [ 43%] FAILED testcases/test_query.py::TestqueryString::test_query_string_is_primary["0" <= varchar <= "100"]

**Comment by weiliu1031** [comment]
/assign @NicoYuan1986 
please verify on this.

**Comment by NicoYuan1986** [comment]
> /assign @NicoYuan1986 please verify on this.

Thanks for your help!🌻 I will verify on it tonight.

**Comment by NicoYuan1986** [comment]
Fixed.
