### ISSUE TITLE
[Bug]: [benchmark][standalone] Glove dataset and build HNSW index, search with ef=10 that search timeout

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#20588]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-20221114-221d044c
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.0.dev70
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task: fouramf-cron-1668441600
test case: test_recall_glove_hnsw_standalone

server:
```
[2022-11-15 02:17:25,968 -  INFO - fouram]: [Base] Deploy initial state: 
I1115 00:53:34.973971   16943 request.go:665] Waited for 1.16596946s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.local/apis/flowcontrol.apiserver.k8s.io/v1beta2?timeout=32s
NAME                                                              READY   STATUS      RESTARTS      AGE     IP             NODE         NOMINATED NODE   READINESS GATES
fouramf-cron-1668441600-1-59-8608-etcd-0                          1/1     Running     0             114s    10.104.6.112   4am-node13   <none>           <none>
fouramf-cron-1668441600-1-59-8608-milvus-standalone-6f89446dn62   1/1     Running     0             114s    10.104.5.69    4am-node12   <none>           <none>
fouramf-cron-1668441600-1-59-8608-minio-5c8c79df74-ml4zl          1/1     Running     0             114s    10.104.6.111   4am-node13   <none>           <none> (base.py:126)
[2022-11-15 02:17:25,968 -  INFO - fouram]: [Cmd Exe]  kubectl get pods  -n qa-milvus  -o wide | grep -E 'STATUS|fouramf-cron-1668441600-1-59-8608'  (util_cmd.py:14)
[2022-11-15 02:17:31,886 -  INFO - fouram]: [CliClient] pod details of release(fouramf-cron-1668441600-1-59-8608): 
 I1115 02:17:27.223665   19170 request.go:665] Waited for 1.165468674s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.local/apis/cert-manager.io/v1?timeout=32s
NAME                                                              READY   STATUS      RESTARTS      AGE     IP             NODE         NOMINATED NODE   READINESS GATES
fouramf-cron-1668441600-1-59-8608-etcd-0                          1/1     Running     0             85m     10.104.6.112   4am-node13   <none>           <none>
fouramf-cron-1668441600-1-59-8608-milvus-standalone-6f89446dn62   1/1     Running     0             85m     10.104.5.69    4am-node12   <none>           <none>
fouramf-cron-1668441600-1-59-8608-minio-5c8c79df74-ml4zl          1/1     Running     0             85m     10.104.6.111   4am-node13   <none>           <none> (cli_client.py:123)
[2022-11-15 02:17:31,886 -  INFO - fouram]: [Base] Start deleting services: fouramf-cron-1668441600-1-59-8608 (base.py:129)
[2022-11-15 02:17:31,886 -  INFO - fouram]: [Cmd Exe]  kubectl get pvc  -n qa-milvus  | grep -E 'STATUS|fouramf-cron-1668441600-1-59-8608'  (util_cmd.py:14)
[2022-11-15 02:17:37,754 -  INFO - fouram]: [CliClient] pvc storage class of release(fouramf-cron-1668441600-1-59-8608): 
 I1115 02:17:33.132983   19221 request.go:665] Waited for 1.170910672s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.local/apis/authorization.k8s.io/v1?timeout=32s
NAME                                                                                               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
data-fouramf-cron-1668441600-1-59-8608-etcd-0                                                      Bound    pvc-db5b60d6-8ffa-4106-b9b8-066611e91b88   10Gi       RWO            local-path        85m
fouramf-cron-1668441600-1-59-8608-milvus                                                           Bound    pvc-0ae756a1-4a26-48a2-bcf5-0a23e277bee0   50Gi       RWO            local-path        85m
fouramf-cron-1668441600-1-59-8608-minio                                                            Bound    pvc-2f9fdc56-c4a2-4baf-bee7-faa969cf5675   500Gi      RWO            local-path        85m (cli_client.py:131)
```

client log:
[test_recall_glove_hnsw_standalone_1.zip](https://github.com/milvus-io/milvus/files/10009145/test_recall_glove_hnsw_standalone_1.zip)
```
[2022-11-15 00:54:27,436 -  INFO - fouram]: [Base] Total time of ann insert: 29.1063s (base.py:206)
[2022-11-15 00:54:27,437 -  INFO - fouram]: [Base] Start flush collection fouram_zbRxwt5v (base.py:93)
[2022-11-15 00:54:30,456 -  INFO - fouram]: [Base] Clean all index done. (base.py:239)
[2022-11-15 00:54:30,456 -  INFO - fouram]: [Base] Start build index of HNSW, params:{'index_type': 'HNSW', 'metric_type': 'IP', 'params': {'M': 36, 'efConstruction': 500}} (base.py:218)
[2022-11-15 01:10:17,992 -  INFO - fouram]: [Time] Index run in 947.5357s (api_request.py:29)
[2022-11-15 01:10:17,998 -  INFO - fouram]: [Base] Params of index: {'index_type': 'HNSW', 'metric_type': 'IP', 'params': {'M': 36, 'efConstruction': 500}} (base.py:228)
[2022-11-15 01:10:17,998 -  INFO - fouram]: [Base] Start load collection fouram_zbRxwt5v, replica_number:1 (base.py:97)
[2022-11-15 01:10:46,219 -  INFO - fouram]: [Time] Collection.load run in 28.2205s (api_request.py:29)
[2022-11-15 01:10:46,222 -  INFO - fouram]: [AccCases] Number of vectors in the collection(fouram_zbRxwt5v): 1183514 (accuracy_cases.py:117)
[2022-11-15 01:10:46,222 -  INFO - fouram]: [PerfTemplate] Actual parameters used: {'dataset_params': {'dim': 200, 'dataset_name': 'glove-200-angular', 'ni_per': 10000}, 'collection_params': {'other_fields': []}, 'load_params': {'replica_number': 1}, 'search_params': {'top_k': 10, 'nq': 10000, 'search_param': {'ef': 10}}, 'index_params': {'index_type': 'HNSW', 'index_param': {'M': 36, 'efConstruction': 500}}} (performance_template.py:59)
[2022-11-15 01:10:46,227 -  INFO - fouram]: [AccCases] Params of search: {'data': array([[-0.02773983,  0.0795716 , -0.07341436, ...,  0.0432257 ,
        -0.09719583, -0.08906623],
       [-0.00701086, -0.03715183,  0.0632261 , ..., -0.0334666 ,
        -0.09059103,  0.05058862],
       [ 0.04278408, -0.0195656 , -0.0546626 , ...,  0.0624952 ,
        -0.13264737, -0.01105194],
       ...,
       [ 0.03442654,  0.13952227,  0.02177458, ...,  0.04648568,
        -0.05786795, -0.06752396],
       [ 0.04487952, -0.03255282,  0.07743784, ...,  0.08966012,
        -0.01795752,  0.07155532],
       [-0.0895235 , -0.12985045,  0.11885931, ...,  0.0558663 ,
         0.07499653, -0.15403427]], dtype=float32), 'anns_field': 'float_vector', 'param': {'metric_type': 'IP', 'params': {'ef': 10}}, 'limit': 10} (accuracy_cases.py:145)
[2022-11-15 01:10:46,227 -  INFO - fouram]: [Base] Params of search: nq:10000, anns_field:float_vector, param:{'metric_type': 'IP', 'params': {'ef': 10}}, limit:10, expr:"None" (base.py:268)
[2022-11-15 01:14:33,213 -  INFO - fouram]: [Time] Collection.search run in 226.9845s (api_request.py:29)
[2022-11-15 01:14:33,213 -  INFO - fouram]: [Base] Params of search: nq:10000, anns_field:float_vector, param:{'metric_type': 'IP', 'params': {'ef': 10}}, limit:10, expr:"None" (base.py:268)
[2022-11-15 01:19:30,802 -  INFO - fouram]: [Time] Collection.search run in 297.5873s (api_request.py:29)
[2022-11-15 01:19:30,810 -  INFO - fouram]: [Base] Params of search: nq:10000, anns_field:float_vector, param:{'metric_type': 'IP', 'params': {'ef': 10}}, limit:10, expr:"None" (base.py:268)
[2022-11-15 01:24:31,046 - ERROR - fouram]: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 478, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 442, in _execute_search_requests
    raise pre_err
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 430, in _execute_search_requests
    response = ft.result()
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1668475471.044411074","description":"Error received from peer ipv4:10.255.105.204:19530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/src/fouram/client/util/api_request.py", line 21, in inner_wrapper
    res = func(*args, **kwargs)
  File "/src/fouram/client/util/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 719, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 58, in handler
    raise MilvusException(message=str(e)) from e
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1668475471.044411074","description":"Error received from peer ipv4:10.255.105.204:19530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>)>
 (api_request.py:35)
[2022-11-15 01:24:31,047 - ERROR - fouram]: (api_response) : <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1668475471.044411074","description":"Error received from peer ipv4:10.255.105.204:19530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>)> (api_request.py:36)
[2022-11-15 01:24:31,047 - ERROR - fouram]: [CheckFunc] search request check failed, response:<MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1668475471.044411074","description":"Error received from peer ipv4:10.255.105.204:19530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>)> (func_check.py:40)
[2022-11-15 01:24:31,047 - ERROR - fouram]: [AccCases] Search raise error:  (accuracy_cases.py:173)
```

### Steps To Reproduce

```markdown
1. create a collection or use an existing collection
        2. insert training dataset
        3. flush collection
        4. clean index and build new index HNSW
        5. load collection
        6. search with different parameters
        7. clean all collections or not
```

### Milvus Log

milvus deploy:
```
helm  -n qa-milvus  upgrade --install  --set standalone.resources.limits.cpu=8.0,standalone.resources.limits.memory=16Gi,standalone.resources.requests.cpu=5.0,standalone.resources.requests.memory=9Gi,standalone.persistence.persistentVolumeClaim.storageClass=local-path,cluster.enabled=False,etcd.replicaCount=1,etcd.global.storageClass=local-path,etcd.metrics.enabled=True,etcd.metrics.podMonitor.enabled=True,minio.mode=standalone,minio.persistence.storageClass=local-path,minio.metrics.serviceMonitor.enabled=False,pulsar.enabled=False,metrics.serviceMonitor.enabled=True,image.all.repository=harbor.milvus.io/dockerhub/milvusdb/milvus,image.all.tag=2.2.0-20221114-221d044c   --wait --timeout 30m   fouramf-cron-1668441600-1-59-8608 /home/helm/charts/milvus/
```

### Anything else?

case params:
```
{
     "dataset_params": {
          "dim": 200,
          "dataset_name": "glove-200-angular",
          "ni_per": 10000
     },
     "collection_params": {
          "other_fields": []
     },
     "load_params": {
          "replica_number": 1
     },
     "search_params": {
          "top_k": [
               10
          ],
          "nq": [
               10000
          ],
          "search_param": {
               "ef": [
                    10,
                    16,
                    32,
                    64,
                    128,
                    256,
                    512
               ]
          }
     },
     "index_params": {
          "index_type": "HNSW",
          "index_param": {
               "M": 36,
               "efConstruction": 500
          }
     }
}
```

**Comment by czs007** [comment]
2022-11-15 01:29:07 | [2022/11/15 01:29:07.416 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=437380906250141697] [segmentID=437380342014107123] [segmentType=3] [loadIndex=true]
-- | --

**Comment by czs007** [comment]
[2022-11-15 01:24:31,055 -  INFO - fouram]: [Base] Params of search: nq:10000, anns_field:float_vector, param:{'metric_type': 'IP', 'params': {'ef': 16}}, limit:10, expr:"None" (base.py:268)
[2022-11-15 01:26:32,256 -  INFO - fouram]: [Time] Collection.search run in 121.2002s (api_request.py:29)
[2022-11-15 01:26:32,257 -  INFO - fouram]: [Base] Params of search: nq:10000, anns_field:float_vector, param:{'metric_type': 'IP', 'params': {'ef': 16}}, limit:10, expr:"None" (base.py:268)
[2022-11-15 01:27:04,258 -  INFO - fouram]: [Time] Collection.search run in 32.0s (api_request.py:29)
[2022-11-15 01:27:04,265 -  INFO - fouram]: [Base] Params of search: nq:10000, anns_field:float_vector, param:{'metric_type': 'IP', 'params': {'ef': 16}}, limit:10, expr:"None" (base.py:268)
[2022-11-15 01:29:06,507 -  INFO - fouram]: [Time] Collection.search run in 122.2416s (api_request.py:29)

**Comment by wangting0128** [comment]
### search RT increases with the increase of search parameter ef

argo task: fouramf-cron-1668528000
test case: test_recall_glove_hnsw_standalone

client log:
[2022_11_15_test_recall_glove_hnsw_standalone_1.log](https://github.com/milvus-io/milvus/files/10018611/2022_11_15_test_recall_glove_hnsw_standalone_1.log)
<img width="1919" alt="截屏2022-11-16 14 12 00" src="https://user-images.githubusercontent.com/26307815/202098469-161a8448-58ec-4efa-90ff-f433721f43a3.png">


[2022_11_12_test_recall_glove_hnsw_standalone_1.log](https://github.com/milvus-io/milvus/files/10018613/2022_11_12_test_recall_glove_hnsw_standalone_1.log)
<img width="1920" alt="截屏2022-11-16 14 12 22" src="https://user-images.githubusercontent.com/26307815/202098525-d624904a-a01f-4f57-b0b8-669fabb5df9d.png">

**Comment by jaime0815** [comment]
related to #20445

**Comment by yanliang567** [comment]
/assign @czs007 
any updates?

**Comment by czs007** [comment]
Still investigating, but it's not currently my top priority.

The current main direction of investigation is to see if there is any difference in segment compaction during the two tests.
After all, the larger the segment size, the better the query performance.

**Comment by czs007** [comment]
## Test1 
[2022_11_12_test_recall_glove_hnsw_standalone_1.log](https://github.com/milvus-io/milvus/files/10018613/2022_11_12_test_recall_glove_hnsw_standalone_1.log)
### Milvus Server
After 01:19:47, the query is performed on 8 segments
```
[2022/11/13 02:01:40.740 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=437336119884644353] [segmentID=437335030685437263] [segmentType=3] [loadIndex=true]
[2022/11/13 02:01:40.740 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=437336119884644353] [segmentID=437335030685637325] [segmentType=3] [loadIndex=true]
[2022/11/13 02:01:40.740 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=437336119884644353] [segmentID=437335030686037399] [segmentType=3] [loadIndex=true]
[2022/11/13 02:01:40.740 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=437336119884644353] [segmentID=437335030686437472] [segmentType=3] [loadIndex=true]
[2022/11/13 02:02:32.701 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=437336119884644353] [segmentID=437335030685637324] [segmentType=3] [loadIndex=true]
[2022/11/13 02:02:32.701 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=437336119884644353] [segmentID=437335030686037398] [segmentType=3] [loadIndex=true]
[2022/11/13 02:02:32.702 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=437336119884644353] [segmentID=437335030685437262] [segmentType=3] [loadIndex=true]
[2022/11/13 02:02:32.701 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=437336119884644353] [segmentID=437335030686437473] [segmentType=3] [loadIndex=true]
```
After 02:03:53, the query is performed on 5 segments

```
[2022/11/13 02:03:53.728 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=437336145116004355] [segmentID=437335030686637559] [segmentType=3] [loadIndex=true]
[2022/11/13 02:04:06.658 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=437336158131453954] [segmentID=437335030685437263] [segmentType=3] [loadIndex=true]
[2022/11/13 02:04:06.658 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=437336158131453954] [segmentID=437335030685637325] [segmentType=3] [loadIndex=true]
[2022/11/13 02:04:06.658 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=437336158131453954] [segmentID=437335030686037399] [segmentType=3] [loadIndex=true]
[2022/11/13 02:04:06.658 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=437336158131453954] [segmentID=437335030686437472] [segmentType=3] [loadIndex=true]
```

The number of segments is reduced to 5 because of compaction:
segment(437335030685637324, 437335030686037398, 437335030685437262, 437335030686437473) =>  segment(437335030686637559).

The segment(437335030686637559) load log is as follows:
```
[2022/11/13 02:02:31.577 +00:00] [INFO] [querynode/segment.go:873] ["load field done"] [fieldID=0] ["row count"=591710] [segmentID =437335030686637559]
```
### Test Client

```
[2022-11-13 01:59:15,671 -  INFO - fouram]: [Base] Params of search: nq:10000, anns_field:float_vector, param:{'metric_type': 'IP', 'params': {'ef': 128}}, limit:10, expr:"None" (base.py:268)
[2022-11-13 02:00:08,183 -  INFO - fouram]: [Time] Collection.search run in 52.5105s (api_request.py:29)
[2022-11-13 02:00:08,284 -  INFO - fouram]: [Base] Params of search: nq:10000, anns_field:float_vector, param:{'metric_type': 'IP', 'params': {'ef': 256}}, limit:10, expr:"None" (base.py:268)
[2022-11-13 02:01:40,478 -  INFO - fouram]: [Time] Collection.search run in 92.1927s (api_request.py:29)
[2022-11-13 02:01:40,479 -  INFO - fouram]: [Base] Params of search: nq:10000, anns_field:float_vector, param:{'metric_type': 'IP', 'params': {'ef': 256}}, limit:10, expr:"None" (base.py:268)
[2022-11-13 02:03:16,715 -  INFO - fouram]: [Time] Collection.search run in 96.2348s (api_request.py:29)
[2022-11-13 02:03:16,723 -  INFO - fouram]: [Base] Params of search: nq:10000, anns_field:float_vector, param:{'metric_type': 'IP', 'params': {'ef': 256}}, limit:10, expr:"None" (base.py:268)
[2022-11-13 02:04:06,394 -  INFO - fouram]: [Time] Collection.search run in 49.669s (api_request.py:29)
...

 [2022-11-13 02:10:03,183 -  INFO - fouram]: [Base] Params of search: nq:10000, anns_field:float_vector, param:{'metric_type': 'IP', 'params': {'ef': 512}}, limit:10, expr:"None" (base.py:268)
[2022-11-13 02:11:43,229 -  INFO - fouram]: [Time] Collection.search run in 100.0446s (api_request.py:29)
[2022-11-13 02:11:43,229 -  INFO - fouram]: [Base] Params of search: nq:10000, anns_field:float_vector, param:{'metric_type': 'IP', 'params': {'ef': 512}}, limit:10, expr:"None" (base.py:268)
[2022-11-13 02:13:30,061 -  INFO - fouram]: [Time] Collection.search run in 106.8308s (api_request.py:29)
```

For searches on 8 segments:
    latency of search(ef:128) is about 50 seconds
    latency of search(ef:256) is about 90 seconds


After compaction, for searches on 5 segments:
    latency of search(ef:256) is about 50 seconds
    latency of search(ef:512) is about  100 seconds

Note:When starting to do  search(ef:512) , compaction has already occurred.

## Test2 
[2022_11_15_test_recall_glove_hnsw_standalone_1.log](https://github.com/milvus-io/milvus/files/10018611/2022_11_15_test_recall_glove_hnsw_standalone_1.log)

### Milvus Server
From 01:13 - 02:08, searches are performed on 8 segments

```
从 01:13 - 02:08 都是在  8个segment上做查询
[2022/11/16 01:13:45.649 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=437403313919492098] [segmentID=437402798474934185] [segmentType=3] [loadIndex=true]
[2022/11/16 01:13:45.649 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=437403313919492098] [segmentID=437402798474333518] [segmentType=3] [loadIndex=true]
[2022/11/16 01:13:45.649 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=437403313919492098] [segmentID=437402798475334529] [segmentType=3] [loadIndex=true]
[2022/11/16 01:13:45.649 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=437403313919492098] [segmentID=437402798474533850] [segmentType=3] [loadIndex=true]
[2022/11/16 01:13:50.052 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=437403313919492098] [segmentID=437402798474934186] [segmentType=3] [loadIndex=true]
[2022/11/16 01:13:50.052 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=437403313919492098] [segmentID=437402798474533851] [segmentType=3] [loadIndex=true]
[2022/11/16 01:13:50.052 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=437403313919492098] [segmentID=437402798474333519] [segmentType=3] [loadIndex=true]
[2022/11/16 01:13:50.052 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=437403313919492098] [segmentID=437402798475334530] [segmentType=3] [loadIndex=true]
...
[2022/11/16 02:09:31.633 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=437404171090788353] [segmentID=437402798474333518] [segmentType=3] [loadIndex=true]
[2022/11/16 02:09:31.633 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=437404171090788353] [segmentID=437402798475334529] [segmentType=3] [loadIndex=true]
[2022/11/16 02:09:31.633 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=437404171090788353] [segmentID=437402798474934185] [segmentType=3] [loadIndex=true]
[2022/11/16 02:09:31.633 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=437404171090788353] [segmentID=437402798474533850] [segmentType=3] [loadIndex=true]
[2022/11/16 02:08:15.480 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=437404171090788353] [segmentID=437402798475334530] [segmentType=3] [loadIndex=true]
[2022/11/16 02:08:15.480 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=437404171090788353] [segmentID=437402798474333519] [segmentType=3] [loadIndex=true]
[2022/11/16 02:08:15.480 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=437404171090788353] [segmentID=437402798474533851] [segmentType=3] [loadIndex=true]
[2022/11/16 02:08:15.480 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=437404171090788353] [segmentID=437402798474934186] [segmentType=3] [loadIndex=true]
```
No compaction ever occurred.

### Test Client

```
[2022-11-16 01:46:19,499 -  INFO - fouram]: [Time] Collection.search run in 45.1918s (api_request.py:29)
[2022-11-16 01:46:19,507 -  INFO - fouram]: [Base] Params of search: nq:10000, anns_field:float_vector, param:{'metric_type': 'IP', 'params': {'ef': 128}}, limit:10, expr:"None" (base.py:268)
[2022-11-16 01:47:05,044 -  INFO - fouram]: [Time] Collection.search run in 45.5356s (api_request.py:29)
...
[2022-11-16 01:52:46,341 -  INFO - fouram]: [Time] Collection.search run in 86.0639s (api_request.py:29)
[2022-11-16 01:52:46,350 -  INFO - fouram]: [Base] Params of search: nq:10000, anns_field:float_vector, param:{'metric_type': 'IP', 'params': {'ef': 256}}, limit:10, expr:"None" (base.py:268)
[2022-11-16 01:54:15,352 -  INFO - fouram]: [Time] Collection.search run in 89.0002s (api_request.py:29)
[2022-11-16 01:54:15,359 -  INFO - fouram]: [Base] Params of search: nq:10000, anns_field:float_vector, param:{'metric_type': 'IP', 'params': {'ef': 256}}, limit:10, expr:"None" (base.py:268)
[2022-11-16 01:55:46,393 -  INFO - fouram]: [Time] Collection.search run in 91.0332s (api_request.py:29)
[2022-11-16 01:55:46,401 -  INFO - fouram]: [Base] Params of search: nq:10000, anns_field:float_vector, param:{'metric_type': 'IP', 'params': {'ef': 256}}, limit:10, expr:"None" (base.py:268)
[2022-11-16 01:57:18,593 -  INFO - fouram]: [Time] Collection.search run in 92.1903s (api_request.py:29)
[2022-11-16 01:57:18,663 -  INFO - fouram]: [AccCases] Search result:{'Recall': 0.973, 'RT': 87.629, 'LastRT': 92.1903} (accuracy_cases.py:169)
[2022-11-16 01:57:18,687 -  INFO - fouram]: [Base] Params of search: nq:10000, anns_field:float_vector, param:{'metric_type': 'IP', 'params': {'ef': 512}}, limit:10, expr:"None" (base.py:268)
[2022-11-16 01:59:59,991 -  INFO - fouram]: [Time] Collection.search run in 161.3031s (api_request.py:29)
[2022-11-16 01:59:59,991 -  INFO - fouram]: [Base] Params of search: nq:10000, anns_field:float_vector, param:{'metric_type': 'IP', 'params': {'ef': 512}}, limit:10, expr:"None" (base.py:268)
[2022-11-16 02:02:42,178 -  INFO - fouram]: [Time] Collection.search run in 162.1862s (api_request.py:29)
[2022-11-16 02:02:42,186 -  INFO - fouram]: [Base] Params of search: nq:10000, anns_field:float_vector, param:{'metric_type': 'IP', 'params': {'ef': 512}}, limit:10, expr:"None" (base.py:268)
[2022-11-16 02:05:27,065 -  INFO - fouram]: [Time] Collection.search run in 164.8774s (api_request.py:29)
```
For queries on 8 segments:
    latency of search(ef:128) is about 50 seconds
    latency of search(ef:256) is about 90 seconds
    latency of search(ef:512) is about 160 seconds



## Conculsion
There was no change in performance between the two tests.
For searches on 8 segments, the latency obtained by the two tests are consistent:
    latency of search(ef:128) is about 50 seconds
    latency of search(ef:256) is about 90 seconds

**Comment by yanliang567** [comment]
@jingkl please help to rerun the test.
/assign @jingkl 
/unassign

**Comment by jingkl** [comment]
This question is the same as this one：#21302

**Comment by yanliang567** [comment]
close for dup to https://github.com/milvus-io/milvus/issues/21302
