### ISSUE TITLE
[Bug]: Search failed with many reason after querynode pod kill chaos test 

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#20584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20221114-221d044c
- Deployment mode(standalone or cluster):cluster with Kafka as MQ
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2022-11-15T01:11:14.374Z] [2022-11-15 01:10:18 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:56)

[2022-11-15T01:11:14.374Z] [2022-11-15 01:10:18 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)

[2022-11-15T01:11:14.374Z] [2022-11-15 01:10:18 - INFO - ci_test]: [test][2022-11-15T01:10:18Z] [0.00513178s] Checker__QqfP8A4d load -> None (wrapper.py:30)

[2022-11-15T01:11:14.374Z] [2022-11-15 01:10:18 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.12434408259021447, 0.05219811512668729, 0.13107317601713434, 0.12361155007286936, 0.14059393991062347, 0.09534419511429101, 0.070196057989174, 0.0173821262086775, 0.01898353715434437, 0.046736665381351766, 0.005599004984749921, 0.054265626878106904, 0.04008960390597267, 0.13752221940041803, 0.1......, kwargs: {} (api_request.py:56)

[2022-11-15T01:11:14.374Z] [2022-11-15 01:10:23 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=32, reason=ShardNotAvailable(replica=437380312558993416, shard=by-dev-rootcoord-dml_17_437380305050078765v1))>, <Time:{'RPC start': '2022-11-15 01:10:18.329602', 'RPC error': '2022-11-15 01:10:23.331930'}> (decorators.py:108)

[2022-11-15T01:11:14.374Z] [2022-11-15 01:10:23 - ERROR - ci_test]: Traceback (most recent call last):

[2022-11-15T01:11:14.374Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2022-11-15T01:11:14.374Z]     res = func(*args, **_kwargs)

[2022-11-15T01:11:14.374Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2022-11-15T01:11:14.374Z]     return func(*arg, **kwargs)

[2022-11-15T01:11:14.374Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 658, in search

[2022-11-15T01:11:14.374Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,

[2022-11-15T01:11:14.374Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2022-11-15T01:11:14.374Z]     raise e

[2022-11-15T01:11:14.374Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2022-11-15T01:11:14.374Z]     return func(*args, **kwargs)

[2022-11-15T01:11:14.374Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2022-11-15T01:11:14.374Z]     ret = func(self, *args, **kwargs)

[2022-11-15T01:11:14.374Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2022-11-15T01:11:14.374Z]     raise e

[2022-11-15T01:11:14.374Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2022-11-15T01:11:14.374Z]     return func(self, *args, **kwargs)

[2022-11-15T01:11:14.374Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 478, in search

[2022-11-15T01:11:14.374Z]     return self._execute_search_requests(requests, timeout, **_kwargs)

[2022-11-15T01:11:14.374Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 442, in _execute_search_requests

[2022-11-15T01:11:14.374Z]     raise pre_err

[2022-11-15T01:11:14.374Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 433, in _execute_search_requests

[2022-11-15T01:11:14.374Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2022-11-15T01:11:14.374Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=32, reason=ShardNotAvailable(replica=437380312558993416, shard=by-dev-rootcoord-dml_17_437380305050078765v1))>

[2022-11-15T01:11:14.374Z]  (api_request.py:39)

[2022-11-15T01:11:14.374Z] [2022-11-15 01:10:23 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=32, reason=ShardNotAvailable(replica=437380312558993416, shard=by-dev-rootcoord-dml_17_437380305050078765v1))> (api_request.py:40)
```

```
2022-11-15T01:11:14.374Z] [2022-11-15 01:10:18 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:56)

[2022-11-15T01:11:14.374Z] [2022-11-15 01:10:18 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)

[2022-11-15T01:11:14.374Z] [2022-11-15 01:10:18 - INFO - ci_test]: [test][2022-11-15T01:10:18Z] [0.00513178s] Checker__QqfP8A4d load -> None (wrapper.py:30)

[2022-11-15T01:11:14.374Z] [2022-11-15 01:10:18 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.12434408259021447, 0.05219811512668729, 0.13107317601713434, 0.12361155007286936, 0.14059393991062347, 0.09534419511429101, 0.070196057989174, 0.0173821262086775, 0.01898353715434437, 0.046736665381351766, 0.005599004984749921, 0.054265626878106904, 0.04008960390597267, 0.13752221940041803, 0.1......, kwargs: {} (api_request.py:56)

[2022-11-15T01:11:14.374Z] [2022-11-15 01:10:23 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=32, reason=ShardNotAvailable(replica=437380312558993416, shard=by-dev-rootcoord-dml_17_437380305050078765v1))>, <Time:{'RPC start': '2022-11-15 01:10:18.329602', 'RPC error': '2022-11-15 01:10:23.331930'}> (decorators.py:108)

[2022-11-15T01:11:14.374Z] [2022-11-15 01:10:23 - ERROR - ci_test]: Traceback (most recent call last):

[2022-11-15T01:11:14.374Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2022-11-15T01:11:14.374Z]     res = func(*args, **_kwargs)

[2022-11-15T01:11:14.374Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2022-11-15T01:11:14.374Z]     return func(*arg, **kwargs)

[2022-11-15T01:11:14.374Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 658, in search

[2022-11-15T01:11:14.374Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,

[2022-11-15T01:11:14.374Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2022-11-15T01:11:14.374Z]     raise e

[2022-11-15T01:11:14.374Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2022-11-15T01:11:14.374Z]     return func(*args, **kwargs)

[2022-11-15T01:11:14.374Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2022-11-15T01:11:14.374Z]     ret = func(self, *args, **kwargs)

[2022-11-15T01:11:14.374Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2022-11-15T01:11:14.374Z]     raise e

[2022-11-15T01:11:14.374Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2022-11-15T01:11:14.374Z]     return func(self, *args, **kwargs)

[2022-11-15T01:11:14.374Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 478, in search

[2022-11-15T01:11:14.374Z]     return self._execute_search_requests(requests, timeout, **_kwargs)

[2022-11-15T01:11:14.374Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 442, in _execute_search_requests

[2022-11-15T01:11:14.374Z]     raise pre_err

[2022-11-15T01:11:14.374Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 433, in _execute_search_requests

[2022-11-15T01:11:14.374Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2022-11-15T01:11:14.374Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=32, reason=ShardNotAvailable(replica=437380312558993416, shard=by-dev-rootcoord-dml_17_437380305050078765v1))>

[2022-11-15T01:11:14.374Z]  (api_request.py:39)
```

```
[2022-11-15T01:11:14.376Z] [2022-11-15 01:10:18 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:56)

[2022-11-15T01:11:14.376Z] [2022-11-15 01:10:18 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)

[2022-11-15T01:11:14.376Z] [2022-11-15 01:10:18 - INFO - ci_test]: [test][2022-11-15T01:10:18Z] [0.00532319s] Checker__xt9VybGl load -> None (wrapper.py:30)

[2022-11-15T01:11:14.376Z] [2022-11-15 01:10:18 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.03300009734466444, 0.14536467458460536, 0.10196405796495031, 0.09191352717899691, 0.020215957982048186, 0.013560723341016202, 0.10491321537248693, 0.07697564759988161, 0.10924537775965922, 0.06405463796623413, 0.01715353106006519, 0.12294983605232208, 0.007777334603186985, 0.04498505365941788, ......, kwargs: {} (api_request.py:56)

[2022-11-15T01:11:14.376Z] [2022-11-15 01:10:38 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=All attempts results:

[2022-11-15T01:11:14.376Z] attempt #1:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_9_437380305050078738v1 is not available in any replica

[2022-11-15T01:11:14.376Z] attempt #2:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_9_437380305050078738v1 is not available in any replica

[2022-11-15T01:11:14.376Z] attempt #3:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_9_437380305050078738v1 is not available in any replica

[2022-11-15T01:11:14.376Z] attempt #4:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_9_437380305050078738v1 is not available in any replica

[2022-11-15T01:11:14.376Z] attempt #5:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_9_437380305050078738v1 is not available in any replica

[2022-11-15T01:11:14.376Z] attempt #6:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_9_437380305050078738v1 is not available in any replica

[2022-11-15T01:11:14.376Z] attempt #7:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_9_437380305050078738v1 is not available in any replica

[2022-11-15T01:11:14.376Z] attempt #8:context deadline exceeded

[2022-11-15T01:11:14.376Z] )>, <Time:{'RPC start': '2022-11-15 01:10:18.373673', 'RPC error': '2022-11-15 01:10:38.332590'}> (decorators.py:108)

[2022-11-15T01:11:14.376Z] [2022-11-15 01:10:38 - ERROR - ci_test]: Traceback (most recent call last):

[2022-11-15T01:11:14.376Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2022-11-15T01:11:14.376Z]     res = func(*args, **_kwargs)

[2022-11-15T01:11:14.376Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2022-11-15T01:11:14.376Z]     return func(*arg, **kwargs)

[2022-11-15T01:11:14.376Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 658, in search

[2022-11-15T01:11:14.376Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,

[2022-11-15T01:11:14.376Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2022-11-15T01:11:14.376Z]     raise e

[2022-11-15T01:11:14.376Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2022-11-15T01:11:14.376Z]     return func(*args, **kwargs)

[2022-11-15T01:11:14.376Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2022-11-15T01:11:14.376Z]     ret = func(self, *args, **kwargs)

[2022-11-15T01:11:14.376Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2022-11-15T01:11:14.376Z]     raise e

[2022-11-15T01:11:14.376Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2022-11-15T01:11:14.376Z]     return func(self, *args, **kwargs)

[2022-11-15T01:11:14.376Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 478, in search

[2022-11-15T01:11:14.376Z]     return self._execute_search_requests(requests, timeout, **_kwargs)

[2022-11-15T01:11:14.376Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 442, in _execute_search_requests

[2022-11-15T01:11:14.376Z]     raise pre_err

[2022-11-15T01:11:14.376Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 433, in _execute_search_requests

[2022-11-15T01:11:14.376Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2022-11-15T01:11:14.376Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=All attempts results:

[2022-11-15T01:11:14.376Z] attempt #1:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_9_437380305050078738v1 is not available in any replica

[2022-11-15T01:11:14.376Z] attempt #2:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_9_437380305050078738v1 is not available in any replica

[2022-11-15T01:11:14.376Z] attempt #3:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_9_437380305050078738v1 is not available in any replica

[2022-11-15T01:11:14.376Z] attempt #4:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_9_437380305050078738v1 is not available in any replica

[2022-11-15T01:11:14.376Z] attempt #5:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_9_437380305050078738v1 is not available in any replica

[2022-11-15T01:11:14.376Z] attempt #6:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_9_437380305050078738v1 is not available in any replica

[2022-11-15T01:11:14.376Z] attempt #7:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_9_437380305050078738v1 is not available in any replica

[2022-11-15T01:11:14.376Z] attempt #8:context deadline exceeded

[2022-11-15T01:11:14.376Z] )>

[2022-11-15T01:11:14.376Z]  (api_request.py:39)
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-for-release/detail/chaos-test-kafka-for-release/1664/pipeline

log:
[artifacts-querynode-pod-kill-1664-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10008847/artifacts-querynode-pod-kill-1664-server-logs.tar.gz)

[artifacts-querynode-pod-kill-1664-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10008848/artifacts-querynode-pod-kill-1664-pytest-logs.tar.gz)

**Comment by jiaoew1991** [comment]
the collection `437380305050078738` is not start to load 
<img width="1211" alt="image" src="https://user-images.githubusercontent.com/2297455/202145605-1d38a8b4-c1b1-43f8-9896-da3c133b8be3.png">

**Comment by jiaoew1991** [comment]
should fixed by this pr https://github.com/milvus-io/milvus/pull/20620

**Comment by jiaoew1991** [comment]
After chaos, IndexCoord cannot provide the right index path 
<img width="1991" alt="image" src="https://user-images.githubusercontent.com/2297455/202352281-3fff3351-8e2e-467a-8f6e-64c11c1caa84.png">
