### ISSUE TITLE
[Bug]: [benchmark][standalone] Milvus  build ivf flat index after load failed, raise an error"collection 437394638847606788 has not been loaded to memory or load failed"

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#20630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20221115-0ea2ff78
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0dev70
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

case_name:
test_ivf_flat_search_standalone 

```

NAME                                                              READY   STATUS      RESTARTS        AGE     IP             NODE         NOMINATED NODE   READINESS GATES
fouramf-cron-1668528000-3-99-1235-etcd-0                          1/1     Running     0               84m     10.104.4.133   4am-node11   <none>           <none>
fouramf-cron-1668528000-3-99-1235-milvus-standalone-765b6d8n57h   1/1     Running     0               84m     10.104.9.221   4am-node14   <none>           <none>
fouramf-cron-1668528000-3-99-1235-minio-5cdc5b4f67-rvgzf          1/1     Running     0               84m     10.104.4.131   4am-node11   <none>           <none> (cli_client.py:123)
"
```
grafana:
<img width="1391" alt="截屏2022-11-16 11 35 30" src="https://user-images.githubusercontent.com/34296482/202077444-a8d2eaeb-bf02-4b9e-a57d-7f1aa2edab1e.png">

client log:

```
[2022-11-15 17:03:26 - DEBUG - fouram]: (api_response) : <pymilvus.orm.index.Index object at 0x7fc73bdfd160>  (api_request.py:24)"
[2022-11-15 17:03:26 -  INFO - fouram]: [Time] Index run in 1534.0034s (api_request.py:29)"
[2022-11-15 17:03:26 -  INFO - fouram]: [CommonCases] RT of build index IVF_FLAT: 1534.0034s (common_cases.py:83)"
[2022-11-15 17:03:26 - DEBUG - fouram]: (api_request)  : [Collection.has_index] args: [], kwargs: {} (api_request.py:53)"
[2022-11-15 17:03:27 - DEBUG - fouram]: (api_response) : True  (api_request.py:24)"
[2022-11-15 17:03:27 - DEBUG - fouram]: [Time] Collection.has_index run in 0.0216s (api_request.py:31)"
[2022-11-15 17:03:27 - DEBUG - fouram]: (api_request)  : [Collection.index] args: [], kwargs: {} (api_request.py:53)"
[2022-11-15 17:03:27 - DEBUG - fouram]: (api_response) : <pymilvus.orm.index.Index object at 0x7fc736f6cf40>  (api_request.py:24)"
[2022-11-15 17:03:27 - DEBUG - fouram]: [Time] Collection.index run in 0.0249s (api_request.py:31)"
[2022-11-15 17:03:27 -  INFO - fouram]: [Base] Params of index: {'index_type': 'IVF_FLAT', 'metric_type': 'L2', 'params': {'nlist': 2048}} (base.py:228)"
[2022-11-15 17:03:27 -  INFO - fouram]: [CommonCases] Prepare index IVF_FLAT done. (common_cases.py:86)"
[2022-11-15 17:03:27 -  INFO - fouram]: [CommonCases] No scalars need to be indexed. (common_cases.py:91)"
[2022-11-15 17:03:27 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_DJ3XSwt2): 50000000 (base.py:244)"
[2022-11-15 17:03:27 -  INFO - fouram]: [Base] Start load collection fouram_DJ3XSwt2, replica_number:1 (base.py:97)"
[2022-11-15 17:03:27 - DEBUG - fouram]: (api_request)  : [Collection.load] args: [None, 1, None], kwargs: {} (api_request.py:53)"
[2022-11-15 17:24:31 - ERROR - pymilvus.decorators]: RPC error: [get_loading_progress], <MilvusException: (code=1, message=collection 437394638847606788 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-11-15 17:24:31.087408', 'RPC error': '2022-11-15 17:24:31.088932'}> (decorators.py:108)"
[2022-11-15 17:24:31 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=collection 437394638847606788 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-11-15 17:03:27.099818', 'RPC error': '2022-11-15 17:24:31.089409'}> (decorators.py:108)"
[2022-11-15 17:24:31 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=collection 437394638847606788 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-11-15 17:03:27.048626', 'RPC error': '2022-11-15 17:24:31.089481'}> (decorators.py:108)"
[2022-11-15 17:24:31 - ERROR - fouram]: Traceback (most recent call last):
  File "/src/fouram/client/util/api_request.py", line 21, in inner_wrapper
    res = func(*args, **kwargs)
  File "/src/fouram/client/util/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 476, in load
    conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 668, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 686, in wait_for_loading_collection
    progress = self.get_loading_progress(collection_name, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 747, in get_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection 437394638847606788 has not been loaded to memory or load failed)>
```

### Steps To Reproduce

```markdown
1. create a collection or use an existing collection
        2. build index on vector column
        3. insert a certain number of vectors
        4. flush collection
        5. build index on vector column with the same parameters
        6. build index on on scalars column or not
        7. count the total number of rows
        8. load collection -> raise error
```

### Milvus Log

[fouram_log.log](https://github.com/milvus-io/milvus/files/10017961/fouram_log.log)

### Anything else?

`{'dataset_params': {'dim': 128, 'dataset_name': 'sift', 'dataset_size': 50000000, 'ni_per': 50000, 'metric_type': 'L2', 'req_run_counts': 30}, 'collection_params': {'other_fields': []}, 'load_params': {}, 'search_params': {'top_k': [1, 10, 100, 1000], 'nq': [1, 10, 100, 200, 500, 1000, 1200], 'search_param': {'nprobe': [8, 32]}}, 'index_params': {'index_type': 'IVF_FLAT', 'index_param': {'nlist': 2048}}} (params_check.py:31)`

**Comment by congqixia** [comment]
```
[2022/11/15 17:19:31.022 +00:00] [WARN] [querynode/impl.go:498] ["load segment failed, OOM if load, collectionID = 437394638847606788, maxSegmentSize = 144 MB, concurrency = 1, usedMemAfterLoad = 60823 MB, totalMem = 65536 MB, thresholdFactor = 0.900000"]
```
From the log, looks like the there was not enough memory to load collection

**Comment by jingkl** [comment]
case_name
test_ivf_flat_search_standalone 
image:2.2.0
pymilvus:2.2.0dev70



```
NAME                                                              READY   STATUS            RESTARTS       AGE     IP             NODE         NOMINATED NODE   READINESS GATES
fouramf-cron-1668960000-3-46-1334-etcd-0                          1/1     Running           0              2m38s   10.104.4.107   4am-node11   <none>           <none>
fouramf-cron-1668960000-3-46-1334-milvus-standalone-588995sntgv   1/1     Running           0              2m38s   10.104.9.112   4am-node14   <none>           <none>
fouramf-cron-1668960000-3-46-1334-minio-769f9fbffd-bkcvd          1/1     Running           0              2m38s   10.104.4.105   4am-node11   <none>           <none> (cli_client.py:123)"
```
client log:


```
[2022-11-20 17:00:55 - DEBUG - root]: (api_request)  : [Collection.load] args: [None, 1, None], kwargs: {} (api_request.py:55)"
[2022-11-20 17:16:33 - ERROR - pymilvus.decorators]: RPC error: [get_loading_progress], <MilvusException: (code=1, message=collection 437507897052364804 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-11-20 17:16:33.050643', 'RPC error': '2022-11-20 17:16:33.051719'}> (decorators.py:108)"
[2022-11-20 17:16:33 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=collection 437507897052364804 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-11-20 17:00:55.911488', 'RPC error': '2022-11-20 17:16:33.052301'}> (decorators.py:108)"
[2022-11-20 17:16:33 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=collection 437507897052364804 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-11-20 17:00:55.875343', 'RPC error': '2022-11-20 17:16:33.052423'}> (decorators.py:108)"
[2022-11-20 17:16:33 - ERROR - root]: Traceback (most recent call last):
  File "/src/fouram/client/util/api_request.py", line 22, in inner_wrapper
    res = func(*args, **kwargs)
  File "/src/fouram/client/util/api_request.py", line 59, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 424, in load
    conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 668, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 686, in wait_for_loading_collection
    progress = self.get_loading_progress(collection_name, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 747, in get_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection 437507897052364804 has not been loaded to memory or load failed)>
 (api_request.py:37)"
```

**Comment by jingkl** [comment]
test case：test_ivf_flat_search_filter_standalone
milvus：2.2.0-20221211-50c7a80b
pymilvus：2.2.1dev4

server：

```
I1211 16:05:47.668262     303 request.go:665] Waited for 1.170711352s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.local/apis/authorization.k8s.io/v1?timeout=32s
NAME                                                              READY   STATUS      RESTARTS         AGE     IP             NODE         NOMINATED NODE   READINESS GATES
fouramf-cron-1670774400-2-95-3164-etcd-0                          1/1     Running     0                5m18s   10.104.9.142   4am-node14   <none>           <none>
fouramf-cron-1670774400-2-95-3164-milvus-standalone-689899sfg4m   1/1     Running     0                5m18s   10.104.1.10    4am-node10   <none>           <none>
fouramf-cron-1670774400-2-95-3164-minio-6f89b45b64-qp2g9          1/1     Running     0                5m18s   10.104.1.9     4am-node10   <none>           <none> (base.py:126)
[2022-12-11 18:20:37,113 -  INFO - fouram]: [Cmd Exe]  kubectl get pods  -n qa-milvus  -o wide | grep -E 'STATUS|fouramf-cron-1670774400-2-95-3164'  (util_cmd.py:14)
[2022-12-11 18:20:43,095 -  INFO - fouram]: [CliClient] pod details of release(fouramf-cron-1670774400-2-95-3164): 
 I1211 18:20:38.363364   12417 request.go:665] Waited for 1.166234655s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.local/apis/events.k8s.io/v1beta1?timeout=32s
NAME                                                              READY   STATUS      RESTARTS         AGE     IP             NODE         NOMINATED NODE   READINESS GATES
fouramf-cron-1670774400-2-95-3164-etcd-0                          1/1     Running     0                140m    10.104.9.142   4am-node14   <none>           <none>
fouramf-cron-1670774400-2-95-3164-milvus-standalone-689899sfg4m   1/1     Running     0                140m    10.104.1.10    4am-node10   <none>           <none>
fouramf-cron-1670774400-2-95-3164-minio-6f89b45b64-qp2g9          1/1     Running     0                140m    10.104.1.9     4am-node10   <none>           <none> (cli_client.py:115)
[2022-12-11 18:20:43,095 -  INFO - fouram]: [Base] Start deleting services: fouramf-cron-1670774400-2-95-3164 (base.py:129)
```

client log：

```
[2022-12-11 17:40:48,748 -  INFO - fouram]: [CommonCases] Prepare index IVF_FLAT done. (common_cases.py:84)
[2022-12-11 17:40:48,748 -  INFO - fouram]: [CommonCases] No scalars need to be indexed. (common_cases.py:89)
[2022-12-11 17:40:48,750 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_oAjGa1Hk): 50000000 (base.py:276)
[2022-12-11 17:40:48,751 -  INFO - fouram]: [Base] Start load collection fouram_oAjGa1Hk, replica_number:1 (base.py:108)
[2022-12-11 18:20:36,953 - ERROR - fouram]: RPC error: [get_loading_progress], <MilvusException: (code=1, message=collection 437983549439082501 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-12-11 18:20:36.950249', 'RPC error': '2022-12-11 18:20:36.953331'}> (decorators.py:108)
[2022-12-11 18:20:36,953 - ERROR - fouram]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=collection 437983549439082501 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-12-11 17:40:48.863099', 'RPC error': '2022-12-11 18:20:36.953927'}> (decorators.py:108)
[2022-12-11 18:20:36,954 - ERROR - fouram]: RPC error: [load_collection], <MilvusException: (code=1, message=collection 437983549439082501 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-12-11 17:40:48.751129', 'RPC error': '2022-12-11 18:20:36.954078'}> (decorators.py:108)
[2022-12-11 18:20:36,962 - ERROR - fouram]: Traceback (most recent call last):
  File "/src/fouram/client/util/api_request.py", line 33, in inner_wrapper
    res = func(*args, **kwargs)
  File "/src/fouram/client/util/api_request.py", line 70, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 361, in load
    conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 659, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 677, in wait_for_loading_collection
    progress = self.get_loading_progress(collection_name, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 738, in get_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection 437983549439082501 has not been loaded to memory or load failed)>
 (api_request.py:48)
```

**Comment by xige-16** [comment]
> fouramf-cron-1670774400-2-95-3164-milvus-standalone-689899sfg4m

![XNsLKfjt2T](https://user-images.githubusercontent.com/20124155/206954957-732287d4-c42a-44a0-b7ad-5da95e6bd06f.png)

Many handoffs occurred during loading

**Comment by jingkl** [comment]
case_name：
 test_ivf_flat_search_standalone

image： 2.2.0-20221216-1aa7a9a8
pymilvus：2.2.1dev4
This problem does not appear
