### ISSUE TITLE
[Bug]: Compact failed with timeout(120s) after kafka pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#20660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-20221116-279cf6f5
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2022-11-17T00:42:24.632Z] <name>: InsertChecker__xtQCmaWc

[2022-11-17T00:42:24.632Z] <partitions>: [{"name": "_default", "collection_name": "InsertChecker__xtQCmaWc", "description": ""}]

[2022-11-17T00:42:24.632Z] <description>: 

[2022-11-17T00:42:24.632Z] <schema>: {

[2022-11-17T00:42:24.632Z]   auto_id: False

[2022-11-17T00:42:24.632Z]   description: 

[2022-11-17T00:42:24.632Z]   fields: [{

[2022-11-17T00:42:24.632Z]     name: int64

[2022-11-17T00:42:24.632Z]     description: 

[2022-11-17T00:42:24.632Z]     type: 5

[2022-11-17T00:42:24.632Z]     is_primary: Tr......  (api_request.py:31)

[2022-11-17T00:42:24.632Z] [2022-11-17 00:40:19 - DEBUG - ci_test]: (api_request)  : [Collection.compact] args: [120], kwargs: {} (api_request.py:56)

[2022-11-17T00:42:24.632Z] [2022-11-17 00:42:19 - ERROR - pymilvus.decorators]: RPC error: [compact], <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 120s)>, <Time:{'RPC start': '2022-11-17 00:40:19.798015', 'RPC error': '2022-11-17 00:42:19.800216'}> (decorators.py:108)

[2022-11-17T00:42:24.632Z] [2022-11-17 00:42:19 - ERROR - ci_test]: Traceback (most recent call last):

[2022-11-17T00:42:24.632Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2022-11-17T00:42:24.632Z]     return func(self, *args, **kwargs)

[2022-11-17T00:42:24.632Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 959, in compact

[2022-11-17T00:42:24.632Z]     response = future.result()

[2022-11-17T00:42:24.632Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 744, in result

[2022-11-17T00:42:24.632Z]     raise self

[2022-11-17T00:42:24.632Z] grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:

[2022-11-17T00:42:24.632Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2022-11-17T00:42:24.632Z] 	details = "Deadline Exceeded"

[2022-11-17T00:42:24.632Z] 	debug_error_string = "{"created":"@1668645739.799815261","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":81,"grpc_status":4}"

[2022-11-17T00:42:24.632Z] >

[2022-11-17T00:42:24.632Z] 

[2022-11-17T00:42:24.632Z] The above exception was the direct cause of the following exception:

[2022-11-17T00:42:24.632Z] 

[2022-11-17T00:42:24.632Z] Traceback (most recent call last):

[2022-11-17T00:42:24.632Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2022-11-17T00:42:24.632Z]     res = func(*args, **_kwargs)

[2022-11-17T00:42:24.632Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2022-11-17T00:42:24.632Z]     return func(*arg, **kwargs)

[2022-11-17T00:42:24.632Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 1129, in compact

[2022-11-17T00:42:24.632Z]     self.compaction_id = conn.compact(self._name, timeout=timeout, **kwargs)

[2022-11-17T00:42:24.632Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2022-11-17T00:42:24.632Z]     raise e

[2022-11-17T00:42:24.632Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2022-11-17T00:42:24.632Z]     return func(*args, **kwargs)

[2022-11-17T00:42:24.632Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2022-11-17T00:42:24.632Z]     ret = func(self, *args, **kwargs)

[2022-11-17T00:42:24.632Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 64, in handler

[2022-11-17T00:42:24.632Z]     raise MilvusException(message=f"rpc deadline exceeded: {timeout_msg}") from e

[2022-11-17T00:42:24.632Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 120s)>

[2022-11-17T00:42:24.632Z]  (api_request.py:39)

[2022-11-17T00:42:24.632Z] [2022-11-17 00:42:19 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 120s)> (api_request.py:40)
```

### Milvus Log

chaos type: pod-kill image tag: 2.2.0-20221116-279cf6f5 target pod: kafka
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-for-release/detail/chaos-test-kafka-for-release/1712/pipeline

log:

[artifacts-kafka-pod-kill-1712-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10027268/artifacts-kafka-pod-kill-1712-server-logs.tar.gz)
[artifacts-kafka-pod-kill-1712-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10027271/artifacts-kafka-pod-kill-1712-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-for-release-cron/detail/chaos-test-kafka-for-release-cron/159/pipeline
log:
[artifacts-kafka-pod-kill-159-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10109497/artifacts-kafka-pod-kill-159-server-logs.tar.gz)

[artifacts-kafka-pod-kill-159-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10109498/artifacts-kafka-pod-kill-159-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
It reproduced stably

**Comment by zhuwenxing** [comment]
Not reproduced in `2.2.0-20221212-184d3c35`
