### ISSUE TITLE
[Bug]: Load timeout （120s）after etcd pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#20661]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20221116-279cf6f5
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
2022-11-16T23:17:41.709Z] [2022-11-16 23:15:00 - INFO - ci_test]: assert flush: 3.0609169006347656, entities: 18590 (test_all_collections_after_chaos.py:56)

[2022-11-16T23:17:41.709Z] [2022-11-16 23:15:00 - INFO - ci_test]: index info: [{'collection': 'Checker__W8hL0Tzl', 'field': 'float_vector', 'index_name': 'index__3yiQYDNH', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}] (test_all_collections_after_chaos.py:72)

[2022-11-16T23:17:41.709Z] [2022-11-16 23:15:00 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:56)

[2022-11-16T23:17:41.709Z] [2022-11-16 23:17:00 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=wait for loading collection timeout, collection: Checker__W8hL0Tzl)>, <Time:{'RPC start': '2022-11-16 23:15:00.664488', 'RPC error': '2022-11-16 23:17:00.932002'}> (decorators.py:108)

[2022-11-16T23:17:41.709Z] [2022-11-16 23:17:00 - WARNING - pymilvus.decorators]: Retry timeout: 120s (decorators.py:79)

[2022-11-16T23:17:41.709Z] [2022-11-16 23:17:00 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: Checker__W8hL0Tzl)>, <Time:{'RPC start': '2022-11-16 23:15:00.660940', 'RPC error': '2022-11-16 23:17:00.933125'}> (decorators.py:108)

[2022-11-16T23:17:41.709Z] [2022-11-16 23:17:00 - ERROR - ci_test]: Traceback (most recent call last):

[2022-11-16T23:17:41.709Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2022-11-16T23:17:41.709Z]     return func(self, *args, **kwargs)

[2022-11-16T23:17:41.709Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 668, in load_collection

[2022-11-16T23:17:41.709Z]     self.wait_for_loading_collection(collection_name, timeout)

[2022-11-16T23:17:41.709Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2022-11-16T23:17:41.709Z]     raise e

[2022-11-16T23:17:41.709Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2022-11-16T23:17:41.709Z]     return func(*args, **kwargs)

[2022-11-16T23:17:41.709Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2022-11-16T23:17:41.709Z]     ret = func(self, *args, **kwargs)

[2022-11-16T23:17:41.709Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2022-11-16T23:17:41.709Z]     raise e

[2022-11-16T23:17:41.709Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2022-11-16T23:17:41.709Z]     return func(self, *args, **kwargs)

[2022-11-16T23:17:41.709Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 690, in wait_for_loading_collection

[2022-11-16T23:17:41.709Z]     raise MilvusException(message=f"wait for loading collection timeout, collection: {collection_name}")

[2022-11-16T23:17:41.709Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=wait for loading collection timeout, collection: Checker__W8hL0Tzl)>

[2022-11-16T23:17:41.709Z] 

[2022-11-16T23:17:41.709Z] The above exception was the direct cause of the following exception:

[2022-11-16T23:17:41.709Z] 

[2022-11-16T23:17:41.709Z] Traceback (most recent call last):

[2022-11-16T23:17:41.709Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2022-11-16T23:17:41.709Z]     res = func(*args, **_kwargs)

[2022-11-16T23:17:41.709Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2022-11-16T23:17:41.709Z]     return func(*arg, **kwargs)

[2022-11-16T23:17:41.709Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 424, in load

[2022-11-16T23:17:41.709Z]     conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)

[2022-11-16T23:17:41.709Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2022-11-16T23:17:41.709Z]     raise e

[2022-11-16T23:17:41.709Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2022-11-16T23:17:41.709Z]     return func(*args, **kwargs)

[2022-11-16T23:17:41.709Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2022-11-16T23:17:41.709Z]     ret = func(self, *args, **kwargs)

[2022-11-16T23:17:41.709Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 80, in handler

[2022-11-16T23:17:41.709Z]     raise MilvusException(e.code, f"{timeout_msg}, message={e.message}") from e

[2022-11-16T23:17:41.709Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: Checker__W8hL0Tzl)>

[2022-11-16T23:17:41.709Z]  (api_request.py:39)

[2022-11-16T23:17:41.709Z] [2022-11-16 23:17:00 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: Checker__W8hL0Tzl)> (api_request.py:40)

[2022-11-16T23:17:41.709Z] ------------- generated html file: file:///tmp/ci_logs/report.html -------------

[2022-11-16T23:17:41.709Z] =========================== short test summary info ============================

[2022-11-16T23:17:41.709Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[Checker__W8hL0Tzl] - AssertionError

[2022-11-16T23:17:41.709Z] =================== 1 failed, 10 passed in 184.27s (0:03:04) ===================

script returned exit code 1
```

### Milvus Log

chaos type: pod-kill image tag: 2.2.0-20221116-279cf6f5 target pod: etcd
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-for-release/detail/chaos-test-for-release/1889/pipeline
log:
[artifacts-etcd-pod-kill-1889-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10027387/artifacts-etcd-pod-kill-1889-server-logs.tar.gz)

[artifacts-etcd-pod-kill-1889-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10027389/artifacts-etcd-pod-kill-1889-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
chaos type: pod-kill image tag: 2.2.0-20221118-e7429f88 target pod: datanode
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-for-release/detail/chaos-test-for-release/1988/pipeline
![image](https://user-images.githubusercontent.com/12268675/202950852-2b986708-0e22-4ba8-ad14-739776200f54.png)
log:
[artifacts-datanode-pod-kill-1988-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/10052480/artifacts-datanode-pod-kill-1988-server-logs.1.tar.gz)
[artifacts-datanode-pod-kill-1988-pytest-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/10052481/artifacts-datanode-pod-kill-1988-pytest-logs.1.tar.gz)

**Comment by soothing-rain** [comment]
@zhuwenxing Can you double check that Etcd pod kill issue in the main thread?

Should be fixed by https://github.com/milvus-io/milvus/pull/20655 and https://github.com/milvus-io/milvus/pull/20695 (cherry-pick)

**Comment by zhuwenxing** [comment]
Verified and passed in `2.2.0-20221130-c5f215da`
