### ISSUE TITLE
[Bug]: [Nightly]Create index 'DISKANN' failed with message `invalid index params: map[beamwidth_ratio:4.000000 dim:8 index_type:DISKANN max_degree:56 metric_type:L2 num_build_thread_ratio:1.000000 num_load_thread_ratio:8.000000 pq_code_budget_gb_ratio:0.125000 search_cache_budget_gb_ratio:0.100000 search_list_size:100]`

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#20701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0(b4af870)
- Deployment mode(standalone or cluster): standalone && cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.0.dev71
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Create index 'DISKANN' failed.
```
[2022-11-17T21:24:54.835Z] [2022-11-17 21:17:58 - ERROR - pymilvus.decorators]: RPC error: [create_index], <MilvusException: (code=1, message=invalid index params: map[beamwidth_ratio:4.000000 dim:8 index_type:DISKANN max_degree:56 metric_type:L2 num_build_thread_ratio:1.000000 num_load_thread_ratio:8.000000 pq_code_budget_gb_ratio:0.125000 search_cache_budget_gb_ratio:0.100000 search_list_size:100])>, <Time:{'RPC start': '2022-11-17 21:17:58.307235', 'RPC error': '2022-11-17 21:17:58.309726'}> (decorators.py:108)
[2022-11-17T21:24:54.836Z] [2022-11-17 21:17:58 - ERROR - ci_test]: Traceback (most recent call last):
[2022-11-17T21:24:54.836Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2022-11-17T21:24:54.836Z]     res = func(*args, **_kwargs)
[2022-11-17T21:24:54.836Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2022-11-17T21:24:54.836Z]     return func(*arg, **kwargs)
[2022-11-17T21:24:54.836Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 1092, in create_index
[2022-11-17T21:24:54.836Z]     return conn.create_index(self._name, field_name, index_params,
[2022-11-17T21:24:54.836Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2022-11-17T21:24:54.836Z]     raise e
[2022-11-17T21:24:54.836Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2022-11-17T21:24:54.836Z]     return func(*args, **kwargs)
[2022-11-17T21:24:54.836Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2022-11-17T21:24:54.836Z]     ret = func(self, *args, **kwargs)
[2022-11-17T21:24:54.836Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
[2022-11-17T21:24:54.836Z]     raise e
[2022-11-17T21:24:54.836Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2022-11-17T21:24:54.836Z]     return func(self, *args, **kwargs)
[2022-11-17T21:24:54.836Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 563, in create_index
[2022-11-17T21:24:54.836Z]     raise MilvusException(status.error_code, status.reason)
[2022-11-17T21:24:54.836Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=invalid index params: map[beamwidth_ratio:4.000000 dim:8 index_type:DISKANN max_degree:56 metric_type:L2 num_build_thread_ratio:1.000000 num_load_thread_ratio:8.000000 pq_code_budget_gb_ratio:0.125000 search_cache_budget_gb_ratio:0.100000 search_list_size:100])>
[2022-11-17T21:24:54.836Z]  (api_request.py:39)
[2022-11-17T21:24:54.836Z] [2022-11-17 21:17:58 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=invalid index params: map[beamwidth_ratio:4.000000 dim:8 index_type:DISKANN max_degree:56 metric_type:L2 num_build_thread_ratio:1.000000 num_load_thread_ratio:8.000000 pq_code_budget_gb_ratio:0.125000 search_cache_budget_gb_ratio:0.100000 search_list_size:100])> (api_request.py:40)
```

### Expected Behavior

PASS

### Steps To Reproduce

```markdown
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/5/pipeline/123
```

### Milvus Log

1. log: [artifacts-milvus-standalone-nightly-5-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/5/artifact/artifacts-milvus-standalone-nightly-5-pymilvus-e2e-logs.tar.gz)
2. failed cases:
```
[2022-11-17T21:24:54.836Z] FAILED testcases/test_search.py::TestCollectionSearch::test_search_after_different_index_with_params[8-True-True-DISKANN-params6] - AssertionError
[2022-11-17T21:24:54.836Z] FAILED testcases/test_search.py::TestCollectionSearch::test_search_after_different_index_with_params[8-False-False-DISKANN-params6] - AssertionError
[2022-11-17T21:24:54.836Z] FAILED testcases/test_search.py::TestCollectionSearch::test_search_after_different_index_with_min_dim[False-False-DISKANN-params6] - AssertionError
[2022-11-17T21:24:54.836Z] FAILED testcases/test_search.py::TestCollectionSearch::test_search_after_different_index_with_params[8-False-True-DISKANN-params6] - AssertionError
[2022-11-17T21:24:54.836Z] FAILED testcases/test_search.py::TestCollectionSearch::test_search_after_different_index_with_min_dim[False-True-DISKANN-params6] - AssertionError
[2022-11-17T21:24:54.836Z] FAILED testcases/test_search.py::TestCollectionSearch::test_search_after_different_index_with_params[8-True-False-DISKANN-params6] - AssertionError
[2022-11-17T21:24:54.836Z] FAILED testcases/test_search.py::TestCollectionSearch::test_search_after_different_index_with_min_dim[True-False-DISKANN-params6] - AssertionError
[2022-11-17T21:24:54.836Z] FAILED testcases/test_search.py::TestCollectionSearch::test_search_after_different_index_with_min_dim[True-True-DISKANN-params6] - AssertionError
[2022-11-17T21:24:54.836Z] FAILED testcases/test_search.py::TestCollectionSearch::test_search_after_index_different_metric_type[8-False-False-DISKANN-params6] - AssertionError
[2022-11-17T21:24:54.836Z] FAILED testcases/test_search.py::TestCollectionSearch::test_search_after_index_different_metric_type[8-False-True-DISKANN-params6] - AssertionError
[2022-11-17T21:24:54.836Z] FAILED testcases/test_search.py::TestCollectionSearch::test_search_after_index_different_metric_type[8-True-False-DISKANN-params6] - AssertionError
[2022-11-17T21:24:54.836Z] FAILED testcases/test_search.py::TestCollectionSearch::test_search_after_index_different_metric_type[8-True-True-DISKANN-params6] - AssertionError
[2022-11-17T21:24:54.836Z] FAILED testcases/test_search.py::TestsearchPagination::test_search_pagination_after_different_index[False-10-False-DISKANN-params6] - AssertionError
[2022-11-17T21:24:54.836Z] FAILED testcases/test_search.py::TestsearchPagination::test_search_pagination_after_different_index[False-0-False-DISKANN-params6] - AssertionError
[2022-11-17T21:24:54.836Z] FAILED testcases/test_search.py::TestsearchPagination::test_search_pagination_after_different_index[False-10-True-DISKANN-params6] - AssertionError
[2022-11-17T21:24:54.836Z] FAILED testcases/test_search.py::TestsearchPagination::test_search_pagination_after_different_index[False-0-True-DISKANN-params6] - AssertionError
[2022-11-17T21:24:54.836Z] FAILED testcases/test_search.py::TestsearchPagination::test_search_pagination_after_different_index[True-10-True-DISKANN-params6] - AssertionError
[2022-11-17T21:24:54.836Z] FAILED testcases/test_search.py::TestsearchPagination::test_search_pagination_after_different_index[True-0-False-DISKANN-params6] - AssertionError
[2022-11-17T21:24:54.836Z] FAILED testcases/test_search.py::TestsearchDiskann::test_search_with_diskann_index[8-False-False] - AssertionError
[2022-11-17T21:24:54.836Z] FAILED testcases/test_search.py::TestsearchDiskann::test_search_with_diskann_index[8-False-True] - AssertionError
[2022-11-17T21:24:54.836Z] FAILED testcases/test_search.py::TestsearchDiskann::test_search_with_diskann_index[8-True-False] - AssertionError
[2022-11-17T21:24:54.836Z] FAILED testcases/test_search.py::TestsearchDiskann::test_search_with_diskann_index[8-True-True] - AssertionError
[2022-11-17T21:24:54.836Z] FAILED testcases/test_search.py::TestsearchPagination::test_search_pagination_after_different_index[True-0-True-DISKANN-params6] - AssertionError
[2022-11-17T21:24:54.836Z] FAILED testcases/test_search.py::TestsearchDiskann::test_search_invalid_params_with_diskann_C[8-False-6554-6554] - AssertionError
[2022-11-17T21:24:54.836Z] FAILED testcases/test_search.py::TestsearchDiskann::test_search_invalid_params_with_diskann_C[8-False-65536-6554] - AssertionError
[2022-11-17T21:24:54.836Z] FAILED testcases/test_search.py::TestsearchDiskann::test_search_invalid_params_with_diskann_C[8-True-6554-6554] - AssertionError
[2022-11-17T21:24:54.836Z] FAILED testcases/test_search.py::TestsearchDiskann::test_search_invalid_params_with_diskann_C[8-True-65536-6554] - AssertionError
[2022-11-17T21:24:54.836Z] FAILED testcases/test_search.py::TestsearchDiskann::test_search_invalid_params_with_diskann_A[8-False-10-20] - AssertionError
[2022-11-17T21:24:54.836Z] FAILED testcases/test_search.py::TestsearchDiskann::test_search_invalid_params_with_diskann_A[8-False-201-20] - AssertionError
[2022-11-17T21:24:54.836Z] FAILED testcases/test_search.py::TestsearchDiskann::test_search_invalid_params_with_diskann_A[8-True-10-20] - AssertionError
[2022-11-17T21:24:54.836Z] FAILED testcases/test_search.py::TestsearchDiskann::test_search_invalid_params_with_diskann_A[8-True-201-20] - AssertionError
[2022-11-17T21:24:54.836Z] FAILED testcases/test_search.py::TestsearchPagination::test_search_pagination_after_different_index[True-10-False-DISKANN-params6] - AssertionError
[2022-11-17T21:24:54.836Z] FAILED testcases/test_search.py::TestsearchDiskann::test_search_with_diskann_with_string_pk[8] - AssertionError
[2022-11-17T21:24:54.837Z] FAILED testcases/test_search.py::TestsearchDiskann::test_search_invalid_params_with_diskann_B[8-False-6553-6553] - AssertionError
[2022-11-17T21:24:54.837Z] FAILED testcases/test_search.py::TestsearchDiskann::test_search_invalid_params_with_diskann_B[8-False-65531-6553] - AssertionError
[2022-11-17T21:24:54.837Z] FAILED testcases/test_search.py::TestsearchDiskann::test_search_invalid_params_with_diskann_B[8-True-6553-6553] - AssertionError
[2022-11-17T21:24:54.837Z] FAILED testcases/test_search.py::TestsearchDiskann::test_search_invalid_params_with_diskann_B[8-True-65531-6553] - AssertionError
[2022-11-17T21:24:54.837Z] FAILED testcases/test_search.py::TestsearchDiskann::test_search_with_delete_data[8-False-False] - AssertionError
[2022-11-17T21:24:54.837Z] FAILED testcases/test_search.py::TestsearchDiskann::test_search_with_delete_data[8-False-True] - AssertionError
[2022-11-17T21:24:54.837Z] FAILED testcases/test_search.py::TestsearchDiskann::test_search_with_delete_data[8-True-False] - AssertionError
[2022-11-17T21:24:54.837Z] FAILED testcases/test_search.py::TestsearchDiskann::test_search_with_delete_data[8-True-True] - AssertionError
[2022-11-17T21:24:54.837Z] FAILED testcases/test_search.py::TestsearchDiskann::test_search_with_diskann_and_more_index[8-False-False] - AssertionError
[2022-11-17T21:24:54.837Z] FAILED testcases/test_search.py::TestsearchDiskann::test_search_with_diskann_and_more_index[8-False-True] - AssertionError
[2022-11-17T21:24:54.837Z] FAILED testcases/test_search.py::TestsearchDiskann::test_search_with_diskann_and_more_index[8-True-False] - AssertionError
[2022-11-17T21:24:54.837Z] FAILED testcases/test_search.py::TestsearchDiskann::test_search_with_diskann_and_more_index[8-True-True] - AssertionError
```

**Comment by binbinlv** [comment]
@xige-16 
could you please improve the log to show what is the error is?
As far as I know, here is dim should >=32 for diskANN, but we could not know this through the error message. 

Thanks.

**Comment by binbinlv** [comment]
@jingkl 
And the test case should modified here to support this limit (dim >=32 for diskANN).

Thanks.

**Comment by jingkl** [comment]
pr：#20702

**Comment by jingkl** [comment]
This will fix the problem

**Comment by NicoYuan1986** [comment]
Fixed.
