### ISSUE TITLE
[Bug]: Datanode crashes after manually calling flush

### ISSUE THREAD

**Issue by deer-code** [milvus-io/milvus#20797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.3
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):v2.0.0rc2
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 两台 32C64G
- GPU: 
- Others:
```

### Current Behavior

手动flush 导致datanode重启

### Milvus Log

[2022/11/20 05:00:42.500 +00:00] [INFO] [datanode/compaction_executor.go:94] ["end to execute compaction"] [planID=437497480244363266]
[2022/11/20 05:00:42.605 +00:00] [INFO] [datanode/flow_graph_insert_buffer_node.go:368] ["(Manual Flush) receiving flush message"] [segmentID=437495639469457409] [collectionID=437428833814315009] [flushed=false] ["v-channel name"=by-dev-rootcoord-dml_10_437428833814315009v0]
[2022/11/20 05:00:42.605 +00:00] [ERROR] [datanode/flow_graph_insert_buffer_node.go:408] ["failed to get segment stats log"] [segmentID=437495639469457409] [error="segment not found: 437495639469457409"] [stack="[github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Operate\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:408\ngithub.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work\n\t/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:102](http://github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Operate/n/t/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:408/ngithub.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work/n/t/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:102)"]
panic: segment not found: 437495639469457409
goroutine 15086922 [running]:
[github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Operate](http://github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Operate)(0xc0146e13b0, 0xc008ae4990, 0x1, 0x1, 0x4376ba0, 0xc0055d44d0, 0x0)
/go/src/[github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:409](http://github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:409) +0x4525
[github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work(0xc00bc44680)](http://github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work(0xc00bc44680))
/go/src/[github.com/milvus-io/milvus/internal/util/flowgraph/node.go:102](http://github.com/milvus-io/milvus/internal/util/flowgraph/node.go:102) +0x23b
created by [github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start](http://github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start)
/go/src/[github.com/milvus-io/milvus/internal/util/flowgraph/node.go:70](http://github.com/milvus-io/milvus/internal/util/flowgraph/node.go:70) +0x70

**Comment by yanliang567** [comment]
@deer-code Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
Also could you please retry on Milvus 2.2.0, which was just released

/assign

**Comment by xiaofan-luan** [comment]
Hi @deer-code,
is this fixed in your cluster? If you still need help pls let me know
