### ISSUE TITLE
[Bug]: [Nightly]Create index timeout(1200s) with diskann

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#20805]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:b834cce
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0.dev72
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Create index timeout(1200s) with diskann.
```
[2022-11-23T21:58:53.628Z] [2022-11-23 20:24:49 - WARNING - pymilvus.decorators]: [93mRetry timeout: 1200s[0m (decorators.py:79)
[2022-11-23T21:58:53.628Z] [2022-11-23 20:24:49 - ERROR - pymilvus.decorators]: RPC error: [wait_for_creating_index], <MilvusException: (code=1, message=Retry timeout: 1200s, message=collection search_collection_5WeWDL14 create index  timeout in 1200s)>, <Time:{'RPC start': '2022-11-23 20:04:49.611293', 'RPC error': '2022-11-23 20:24:49.950894'}> (decorators.py:108)
[2022-11-23T21:58:53.628Z] [2022-11-23 20:24:49 - WARNING - pymilvus.decorators]: [93mRetry timeout: 1200s[0m (decorators.py:79)
[2022-11-23T21:58:53.628Z] [2022-11-23 20:24:49 - ERROR - pymilvus.decorators]: RPC error: [create_index], <MilvusException: (code=1, message=Retry timeout: 1200s, message=Retry timeout: 1200s, message=collection search_collection_5WeWDL14 create index  timeout in 1200s)>, <Time:{'RPC start': '2022-11-23 20:04:49.601155', 'RPC error': '2022-11-23 20:24:49.951153'}> (decorators.py:108)
[2022-11-23T21:58:53.628Z] [2022-11-23 20:24:49 - ERROR - ci_test]: Traceback (most recent call last):
[2022-11-23T21:58:53.628Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2022-11-23T21:58:53.628Z]     return func(self, *args, **kwargs)
[2022-11-23T21:58:53.628Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 566, in create_index
[2022-11-23T21:58:53.628Z]     index_success, fail_reason = self.wait_for_creating_index(collection_name=collection_name,
[2022-11-23T21:58:53.628Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2022-11-23T21:58:53.628Z]     raise e
[2022-11-23T21:58:53.628Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2022-11-23T21:58:53.628Z]     return func(*args, **kwargs)
[2022-11-23T21:58:53.628Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2022-11-23T21:58:53.628Z]     ret = func(self, *args, **kwargs)
[2022-11-23T21:58:53.628Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 80, in handler
[2022-11-23T21:58:53.628Z]     raise MilvusException(e.code, f"{timeout_msg}, message={e.message}") from e
[2022-11-23T21:58:53.628Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 1200s, message=collection search_collection_5WeWDL14 create index  timeout in 1200s)>
[2022-11-23T21:58:53.628Z] 
[2022-11-23T21:58:53.628Z] The above exception was the direct cause of the following exception:
[2022-11-23T21:58:53.628Z] 
[2022-11-23T21:58:53.628Z] Traceback (most recent call last):
[2022-11-23T21:58:53.628Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2022-11-23T21:58:53.628Z]     res = func(*args, **_kwargs)
[2022-11-23T21:58:53.628Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2022-11-23T21:58:53.628Z]     return func(*arg, **kwargs)
[2022-11-23T21:58:53.628Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 1031, in create_index
[2022-11-23T21:58:53.628Z]     return conn.create_index(self._name, field_name, index_params,
[2022-11-23T21:58:53.628Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2022-11-23T21:58:53.628Z]     raise e
[2022-11-23T21:58:53.628Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2022-11-23T21:58:53.628Z]     return func(*args, **kwargs)
[2022-11-23T21:58:53.628Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2022-11-23T21:58:53.628Z]     ret = func(self, *args, **kwargs)
[2022-11-23T21:58:53.628Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 80, in handler
[2022-11-23T21:58:53.628Z]     raise MilvusException(e.code, f"{timeout_msg}, message={e.message}") from e
[2022-11-23T21:58:53.628Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 1200s, message=Retry timeout: 1200s, message=collection search_collection_5WeWDL14 create index  timeout in 1200s)>
[2022-11-23T21:58:53.628Z]  (api_request.py:39)
[2022-11-23T21:58:53.628Z] [2022-11-23 20:24:49 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 1200s, message=Retry timeout: 1200s, message=collection search_collection_5WeWDL14 create index  timeout in 1200s)> (api_request.py:40)
```

### Expected Behavior

pass

### Steps To Reproduce

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/199/pipeline/187/

### Milvus Log

log: [artifacts-milvus-distributed-pulsar-nightly-199-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/199/artifact/artifacts-milvus-distributed-pulsar-nightly-199-pymilvus-e2e-logs.tar.gz)

**Comment by NicoYuan1986** [comment]
Latest: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/204/pipeline/155

milvus: b5f178f
pymilvus: 2.3.0.dev15

1. log: [artifacts-milvus-distributed-kafka-nightly-204-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/204/artifact/artifacts-milvus-distributed-kafka-nightly-204-pymilvus-e2e-logs.tar.gz)
2. collection name: search_collection_88fmNeyB

**Comment by xige-16** [comment]
error info
```
2022-11-29T02:17:01.555947584+08:00 stdout F 2022-11-28 18:17:01,555 | INFO | default | [KNOWHERE][Prepare][milvus] Loading PQ from disk.
2022-11-29T02:17:01.555989451+08:00 stdout F 2022-11-28 18:17:01,555 | INFO | default | L2: Using AVX2 distance computation DistanceL2Float
2022-11-29T02:17:01.556008597+08:00 stdout F 2022-11-28 18:17:01,555 | INFO | default | L2: Using AVX2 distance computation DistanceL2Float
2022-11-29T02:17:01.556091773+08:00 stdout F 2022-11-28 18:17:01,556 | INFO | default | PQ Pivots: #ctrs: 256, #dims: 128, #chunks: 64
2022-11-29T02:17:01.556280249+08:00 stdout F 2022-11-28 18:17:01,556 | INFO | default | Loaded PQ centroids and in-memory compressed vectors. #points: 1503 #dim: 128 #aligned_dim: 128 #chunks: 64
2022-11-29T02:17:01.556325181+08:00 stdout F 2022-11-28 18:17:01,556 | INFO | default | Disk-Index File Meta-data: # nodes per sector: 5, max node len (bytes): 740, max node degree: 56
2022-11-29T02:17:01.556337842+08:00 stdout F 2022-11-28 18:17:01,556 | INFO | default | Setting up thread-specific contexts for nthreads: 64
2022-11-29T02:17:01.569941388+08:00 stdout F 2022-11-28 18:17:01,569 | INFO | default | Loading centroid data from medoids vector data of 1 medoid(s)
2022-11-29T02:17:01.575162472+08:00 stdout F 2022-11-28 18:17:01,575 | INFO | default | [KNOWHERE][Prepare][milvus] Caching 87 sample nodes around medoid(s).
2022-11-29T02:17:01.6126701+08:00 stderr F terminate called after throwing an instance of 'diskann::ANNException'
2022-11-29T02:17:01.612691555+08:00 stderr F   what():   [FUNC: void {anonymous}::execute_io(io_context_t, uint64_t, int, const std::vector<AlignedRead>&, uint64_t)][FILE: /go/src/github.com/milvus-io/milvus/cmake_build/3rdparty_download/knowhere-subbuild/src/knowhere_ep/thirdparty/DiskANN/src/linux_aligned_file_reader.cpp][LINE: 76]io_getevents() failed; returned 5, expected=6, ernno=0=Unknown error -5, try #1
```

**Comment by xige-16** [comment]
> error info
> 
> ```
> 2022-11-29T02:17:01.555947584+08:00 stdout F 2022-11-28 18:17:01,555 | INFO | default | [KNOWHERE][Prepare][milvus] Loading PQ from disk.
> 2022-11-29T02:17:01.555989451+08:00 stdout F 2022-11-28 18:17:01,555 | INFO | default | L2: Using AVX2 distance computation DistanceL2Float
> 2022-11-29T02:17:01.556008597+08:00 stdout F 2022-11-28 18:17:01,555 | INFO | default | L2: Using AVX2 distance computation DistanceL2Float
> 2022-11-29T02:17:01.556091773+08:00 stdout F 2022-11-28 18:17:01,556 | INFO | default | PQ Pivots: #ctrs: 256, #dims: 128, #chunks: 64
> 2022-11-29T02:17:01.556280249+08:00 stdout F 2022-11-28 18:17:01,556 | INFO | default | Loaded PQ centroids and in-memory compressed vectors. #points: 1503 #dim: 128 #aligned_dim: 128 #chunks: 64
> 2022-11-29T02:17:01.556325181+08:00 stdout F 2022-11-28 18:17:01,556 | INFO | default | Disk-Index File Meta-data: # nodes per sector: 5, max node len (bytes): 740, max node degree: 56
> 2022-11-29T02:17:01.556337842+08:00 stdout F 2022-11-28 18:17:01,556 | INFO | default | Setting up thread-specific contexts for nthreads: 64
> 2022-11-29T02:17:01.569941388+08:00 stdout F 2022-11-28 18:17:01,569 | INFO | default | Loading centroid data from medoids vector data of 1 medoid(s)
> 2022-11-29T02:17:01.575162472+08:00 stdout F 2022-11-28 18:17:01,575 | INFO | default | [KNOWHERE][Prepare][milvus] Caching 87 sample nodes around medoid(s).
> 2022-11-29T02:17:01.6126701+08:00 stderr F terminate called after throwing an instance of 'diskann::ANNException'
> 2022-11-29T02:17:01.612691555+08:00 stderr F   what():   [FUNC: void {anonymous}::execute_io(io_context_t, uint64_t, int, const std::vector<AlignedRead>&, uint64_t)][FILE: /go/src/github.com/milvus-io/milvus/cmake_build/3rdparty_download/knowhere-subbuild/src/knowhere_ep/thirdparty/DiskANN/src/linux_aligned_file_reader.cpp][LINE: 76]io_getevents() failed; returned 5, expected=6, ernno=0=Unknown error -5, try #1
> ```

@cqy123456  please help

**Comment by xige-16** [comment]
same with #20869

**Comment by NicoYuan1986** [comment]
Latest: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/205/pipeline/187

milvus: c6fc151
pymilvus: 2.3.0.dev15

1. log: [artifacts-milvus-distributed-pulsar-nightly-205-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/205/artifact/artifacts-milvus-distributed-pulsar-nightly-205-pymilvus-e2e-logs.tar.gz)
2. collection name: search_collection_XIxqln7i

**Comment by NicoYuan1986** [comment]
Not appeared yesterday.

**Comment by yanliang567** [comment]
downgrade the priority for now

**Comment by NicoYuan1986** [comment]
behave well these days

**Comment by xiaofan-luan** [comment]
close since is no longer a issue
