### ISSUE TITLE
[Bug]: [Nightly]Search failed with an unexpected error about DIAKANN

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#20803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:b834cce
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.0.dev72
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Search with DISKANN failed.
```
[2022-11-23T21:09:49.285Z] [2022-11-23 18:10:23 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=7, reason=Search 3 failed, reason [UnexpectedError] Error in T knowhere::{anonymous}::TryDiskANNCallAndThrow(std::function<T()>&&) [with T = void] at IndexDiskANN.cpp:147: DiskANN Exception: [FUNC: void {anonymous}::execute_io(io_context_t, uint64_t, int, const std::vector<AlignedRead>&, uint64_t)][FILE: /go/src/github.com/milvus-io/milvus/cmake_build/3rdparty_download/knowhere-subbuild/src/knowhere_ep/thirdparty/DiskANN/src/linux_aligned_file_reader.cpp][LINE: 76]io_getevents() failed; returned 9, expected=11, ernno=0=Unknown error -9, try #1 err %!w(<nil>))>, <Time:{'RPC start': '2022-11-23 18:10:23.017251', 'RPC error': '2022-11-23 18:10:23.323173'}> (decorators.py:108)
[2022-11-23T21:09:49.285Z] [2022-11-23 18:10:23 - ERROR - ci_test]: Traceback (most recent call last):
[2022-11-23T21:09:49.285Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2022-11-23T21:09:49.285Z]     res = func(*args, **_kwargs)
[2022-11-23T21:09:49.285Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2022-11-23T21:09:49.285Z]     return func(*arg, **kwargs)
[2022-11-23T21:09:49.285Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 658, in search
[2022-11-23T21:09:49.285Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,
[2022-11-23T21:09:49.285Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2022-11-23T21:09:49.285Z]     raise e
[2022-11-23T21:09:49.285Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2022-11-23T21:09:49.285Z]     return func(*args, **kwargs)
[2022-11-23T21:09:49.285Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2022-11-23T21:09:49.285Z]     ret = func(self, *args, **kwargs)
[2022-11-23T21:09:49.285Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
[2022-11-23T21:09:49.285Z]     raise e
[2022-11-23T21:09:49.285Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2022-11-23T21:09:49.285Z]     return func(self, *args, **kwargs)
[2022-11-23T21:09:49.285Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 478, in search
[2022-11-23T21:09:49.285Z]     return self._execute_search_requests(requests, timeout, **_kwargs)
[2022-11-23T21:09:49.285Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 442, in _execute_search_requests
[2022-11-23T21:09:49.285Z]     raise pre_err
[2022-11-23T21:09:49.285Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 433, in _execute_search_requests
[2022-11-23T21:09:49.285Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2022-11-23T21:09:49.285Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=7, reason=Search 3 failed, reason [UnexpectedError] Error in T knowhere::{anonymous}::TryDiskANNCallAndThrow(std::function<T()>&&) [with T = void] at IndexDiskANN.cpp:147: DiskANN Exception: [FUNC: void {anonymous}::execute_io(io_context_t, uint64_t, int, const std::vector<AlignedRead>&, uint64_t)][FILE: /go/src/github.com/milvus-io/milvus/cmake_build/3rdparty_download/knowhere-subbuild/src/knowhere_ep/thirdparty/DiskANN/src/linux_aligned_file_reader.cpp][LINE: 76]io_getevents() failed; returned 9, expected=11, ernno=0=Unknown error -9, try #1 err %!w(<nil>))>
[2022-11-23T21:09:49.285Z]  (api_request.py:39)
[2022-11-23T21:09:49.285Z] [2022-11-23 18:10:23 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=7, reason=Search 3 failed, reason [UnexpectedError] Error in T knowhere::{anonymous}::TryDiskANNCallAndThrow(std::function<T()>&&) [with T = void] at IndexDiskANN.cpp:147: DiskANN Exception: [FUN...... (api_request.py:40)
```

### Expected Behavior

PASS

### Steps To Reproduce

```markdown
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/199/pipeline/135
```

### Milvus Log

1. log: [artifacts-milvus-distributed-kafka-nightly-199-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/199/artifact/artifacts-milvus-distributed-kafka-nightly-199-pymilvus-e2e-logs.tar.gz)
2. collection name: index_sAkGFWAa
3. failed timeline: [2022-11-23T18:10:23.663Z] [gw5] [ 24%] FAILED testcases/test_index.py::TestIndexDiskann::test_create_index_with_diskann_callback[True]

**Comment by xiaofan-luan** [comment]
/assign @liliu-z 
seems to be a aio issue

**Comment by hhy3** [comment]
It seems to be a bug or something in libaio and non-reproducible. This will be fixed later and libaio will later be replaced with iouring.

**Comment by NicoYuan1986** [comment]
Latest: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/204/pipeline/155

milvus: b5f178f
pymilvus: 2.3.0.dev15

1. log: [artifacts-milvus-distributed-kafka-nightly-204-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/204/artifact/artifacts-milvus-distributed-kafka-nightly-204-pymilvus-e2e-logs.tar.gz)
2. collection name: search_collection_I4McDQH6
3. [2022-11-28T21:55:20.268Z] [gw2] [ 99%] FAILED testcases/test_search.py::TestsearchDiskann::test_search_with_delete_data[128-False-False]

**Comment by NicoYuan1986** [comment]
Latest: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/205/pipeline/187

milvus: c6fc151
pymilvus: 2.3.0.dev15

1. log: [artifacts-milvus-distributed-pulsar-nightly-205-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/205/artifact/artifacts-milvus-distributed-pulsar-nightly-205-pymilvus-e2e-logs.tar.gz)
2. collection name: search_collection_iz8IQV1S
3. [2022-11-29T21:53:11.716Z] _ TestCollectionSearch.test_search_after_different_index_with_params[32-True-True-DISKANN-params6] _

**Comment by NicoYuan1986** [comment]
Not appeared yesterday. I'll close it if it behaves well in the later days.

**Comment by NicoYuan1986** [comment]
Not appeared.
