### ISSUE TITLE
[Bug]: Collection load failed after upgrading from 2.1.4 to master

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#20849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.1.4 --> master-20221126-f588a737
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2022-11-27T09:54:24.577Z] List collections...

[2022-11-27T09:54:24.577Z] collections_nums: 6

[2022-11-27T09:54:24.577Z] task_1_HNSW: 3000

[2022-11-27T09:54:24.577Z] task_1_IVF_FLAT: 3000

[2022-11-27T09:54:24.577Z] task_1_FLAT: 3000

[2022-11-27T09:54:24.577Z] task_1_IVF_PQ: 3000

[2022-11-27T09:54:24.577Z] task_1_ANNOY: 3000

[2022-11-27T09:54:24.577Z] task_1_IVF_SQ8: 3000

[2022-11-27T09:54:24.577Z] collection name: task_1_HNSW

[2022-11-27T09:54:24.577Z] load collection

[2022-11-27T09:54:24.577Z] Traceback (most recent call last):

[2022-11-27T09:54:24.577Z]   File "scripts/action_after_upgrade.py", line 107, in <module>

[2022-11-27T09:54:24.577Z]     task_1(data_size, host)

[2022-11-27T09:54:24.577Z]   File "scripts/action_after_upgrade.py", line 20, in task_1

[2022-11-27T09:54:24.577Z]     load_and_search(prefix)

[2022-11-27T09:54:24.577Z]   File "/home/jenkins/agent/workspace/tests/python_client/deploy/scripts/utils.py", line 173, in load_and_search

[2022-11-27T09:54:24.577Z]     c.load()

[2022-11-27T09:54:24.577Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 361, in load

[2022-11-27T09:54:24.577Z]     conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)

[2022-11-27T09:54:24.577Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2022-11-27T09:54:24.577Z]     raise e

[2022-11-27T09:54:24.577Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2022-11-27T09:54:24.577Z]     return func(*args, **kwargs)

[2022-11-27T09:54:24.577Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2022-11-27T09:54:24.577Z]     ret = func(self, *args, **kwargs)

[2022-11-27T09:54:24.577Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2022-11-27T09:54:24.577Z]     raise e

[2022-11-27T09:54:24.577Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2022-11-27T09:54:24.577Z]     return func(self, *args, **kwargs)

[2022-11-27T09:54:24.577Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 659, in load_collection

[2022-11-27T09:54:24.577Z]     self.wait_for_loading_collection(collection_name, timeout)

[2022-11-27T09:54:24.577Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2022-11-27T09:54:24.577Z]     raise e

[2022-11-27T09:54:24.577Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2022-11-27T09:54:24.577Z]     return func(*args, **kwargs)

[2022-11-27T09:54:24.577Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2022-11-27T09:54:24.577Z]     ret = func(self, *args, **kwargs)

[2022-11-27T09:54:24.577Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2022-11-27T09:54:24.577Z]     raise e

[2022-11-27T09:54:24.577Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2022-11-27T09:54:24.577Z]     return func(self, *args, **kwargs)

[2022-11-27T09:54:24.577Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 677, in wait_for_loading_collection

[2022-11-27T09:54:24.577Z]     progress = self.get_loading_progress(collection_name, timeout=timeout)

[2022-11-27T09:54:24.577Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2022-11-27T09:54:24.577Z]     raise e

[2022-11-27T09:54:24.577Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2022-11-27T09:54:24.577Z]     return func(*args, **kwargs)

[2022-11-27T09:54:24.577Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2022-11-27T09:54:24.577Z]     ret = func(self, *args, **kwargs)

[2022-11-27T09:54:24.577Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2022-11-27T09:54:24.577Z]     raise e

[2022-11-27T09:54:24.577Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2022-11-27T09:54:24.577Z]     return func(self, *args, **kwargs)

[2022-11-27T09:54:24.577Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 738, in get_loading_progress

[2022-11-27T09:54:24.577Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2022-11-27T09:54:24.577Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection 437660215062036481 has not been loaded to memory or load failed)>
```

### Expected Behavior

all test cases passed

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_cron/detail/deploy_test_cron/27/pipeline
log:
[artifacts-pulsar-standalone-upgrade-27-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10100007/artifacts-pulsar-standalone-upgrade-27-server-logs.tar.gz)

[artifacts-pulsar-standalone-upgrade-27-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10100008/artifacts-pulsar-standalone-upgrade-27-pytest-logs.tar.gz)

### Anything else?

```
+ kubectl get pods -o wide
 + grep pulsar-standalone-upgrade-27
 pulsar-standalone-upgrade-27-etcd-0                               1/1     Running            0               69m     10.102.6.15     devops-node10   <none>           <none>
 pulsar-standalone-upgrade-27-milvus-standalone-596d8db6d8-44q72   1/1     Running            0               60m     10.102.6.40     devops-node10   <none>           <none>
 pulsar-standalone-upgrade-27-minio-9f645bfd9-5kfdh                1/1     Running            0               69m     10.102.5.76     devops-node21   <none>           <none>
```

**Comment by weiliu1031** [comment]
![image](https://user-images.githubusercontent.com/108661493/204261544-59361fc0-d011-40f4-aa48-0e7c92ad492d.png)
collection has been release due to no index during upgrade. please check test case

**Comment by zhuwenxing** [comment]
You can check the code https://github.com/milvus-io/milvus/blob/938c09679c8a414defcd667fb55ca7dc47c2c4cc/tests/python_client/deploy/scripts/action_after_upgrade.py#L9-L24

The things we did is creating the index, then load and search.

![image](https://user-images.githubusercontent.com/12268675/204454213-e7d5ff20-be61-474d-a247-3ec792ecbb1c.png)

**Comment by zhuwenxing** [comment]
![image](https://user-images.githubusercontent.com/12268675/204456149-c9726395-08bd-4292-98b2-d31899415264.png)

This step also failed, so it is not about index

**Comment by weiliu1031** [comment]
something wrong when consume from rocksmq
![image](https://user-images.githubusercontent.com/108661493/204463271-0fc4d58c-b4fe-4c8a-bcf6-d7e1513bd36e.png)

**Comment by zhuwenxing** [comment]
It still reproduced, please help to take a look! @smellthemoon 

deploy task: upgrade milvus mode：standalone old image tag: v2.1.4 new image tag: master-20221129-8153b84f
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_cron/detail/deploy_test_cron/35/pipeline
log:

[artifacts-pulsar-standalone-upgrade-35-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10128678/artifacts-pulsar-standalone-upgrade-35-server-logs.tar.gz)

[artifacts-pulsar-standalone-upgrade-35-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10128679/artifacts-pulsar-standalone-upgrade-35-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
verified and passed in `master-20221130-4c5ffc83`
