### ISSUE TITLE
[Bug]: [Nightly]Load collection failed because there is no enough nodes to create replicas

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#20848]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:f588a73
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.0.dev15
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Load collection failed because there is no enough nodes to create replicas.
```
[2022-11-27T19:48:35.383Z] [2022-11-27 19:45:30 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=failed to load collection, err=no enough nodes to create replicas[NoEnoughNode])>, <Time:{'RPC start': '2022-11-27 19:45:30.341011', 'RPC error': '2022-11-27 19:45:30.347172'}> (decorators.py:108)
[2022-11-27T19:48:35.383Z] [2022-11-27 19:45:30 - ERROR - ci_test]: Traceback (most recent call last):
[2022-11-27T19:48:35.383Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2022-11-27T19:48:35.383Z]     res = func(*args, **_kwargs)
[2022-11-27T19:48:35.384Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2022-11-27T19:48:35.384Z]     return func(*arg, **kwargs)
[2022-11-27T19:48:35.384Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 361, in load
[2022-11-27T19:48:35.384Z]     conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
[2022-11-27T19:48:35.384Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2022-11-27T19:48:35.384Z]     raise e
[2022-11-27T19:48:35.384Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2022-11-27T19:48:35.384Z]     return func(*args, **kwargs)
[2022-11-27T19:48:35.384Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2022-11-27T19:48:35.384Z]     ret = func(self, *args, **kwargs)
[2022-11-27T19:48:35.384Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
[2022-11-27T19:48:35.384Z]     raise e
[2022-11-27T19:48:35.384Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2022-11-27T19:48:35.384Z]     return func(self, *args, **kwargs)
[2022-11-27T19:48:35.384Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 656, in load_collection
[2022-11-27T19:48:35.384Z]     raise MilvusException(response.error_code, response.reason)
[2022-11-27T19:48:35.384Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=failed to load collection, err=no enough nodes to create replicas[NoEnoughNode])>
[2022-11-27T19:48:35.384Z]  (api_request.py:39)
[2022-11-27T19:48:35.384Z] [2022-11-27 19:45:30 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=failed to load collection, err=no enough nodes to create replicas[NoEnoughNode])> (api_request.py:40)
```

### Expected Behavior

PASS

### Steps To Reproduce

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/203/pipeline/187

### Milvus Log

1. log: [artifacts-milvus-distributed-pulsar-nightly-203-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/203/artifact/artifacts-milvus-distributed-pulsar-nightly-203-pymilvus-e2e-logs.tar.gz)
2. collection name: search_collection_abu2KV4R

**Comment by NicoYuan1986** [comment]
The error also occurs many times in 2.2 branch.
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/15/pipeline/155

**Comment by yanliang567** [comment]
@NicoYuan1986 how many replicas did you set in the testcase, and how many querynode did you configure in the deployment?

**Comment by NicoYuan1986** [comment]
> @NicoYuan1986 how many replicas did you set in the testcase, and how many querynode did you configure in the deployment?

querynode: 2 
replicas:
proxy.replicas=2
queryNode.replicas=2
indexNode.replicas=2
dataNode.replicas=2

**Comment by weiliu1031** [comment]
seems that diskANN cause query node panic
![image](https://user-images.githubusercontent.com/108661493/204255876-abe6ac6f-7a9e-403c-8a53-832097cd0302.png)

**Comment by weiliu1031** [comment]
same as https://github.com/milvus-io/milvus/issues/20869

**Comment by NicoYuan1986** [comment]
The error occurred many times yesterday.
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/204/pipeline/187
[artifacts-milvus-distributed-pulsar-nightly-204-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/204/artifact/artifacts-milvus-distributed-pulsar-nightly-204-pymilvus-e2e-logs.tar.gz)
maintain attention.

**Comment by xiaofan-luan** [comment]
this is an urgent issue. put it to 2.2.1 because we hit many times

**Comment by NicoYuan1986** [comment]
The error occurred many times yesterday.
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/205/pipeline/155
[artifacts-milvus-distributed-kafka-nightly-205-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/205/artifact/artifacts-milvus-distributed-kafka-nightly-205-pymilvus-e2e-logs.tar.gz)
error message:
```
<MilvusException: (code=1, message=failed to load collection, err=no enough nodes to create replicas[NoEnoughNode])>
```

**Comment by NicoYuan1986** [comment]
Not appeared yesterday.

**Comment by yanliang567** [comment]
@NicoYuan1986 shall we close it as it not reproduced

**Comment by NicoYuan1986** [comment]
not reproduced for a week, close it first.
