### ISSUE TITLE
[Bug]: Datanode panic after running some test cases when mq is Kafka

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#20846]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20221126-f588a737
- Deployment mode(standalone or cluster): cluster and standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.3.0.dev15
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2022/11/26 10:36:37.050 +00:00] [INFO] [datanode/flow_graph_insert_buffer_node.go:616] ["datanode AsProducer"] [TimeTickChannelName=by-dev-datacoord-timetick-channel]
[2022/11/26 10:36:37.050 +00:00] [INFO] [kafka/kafka_client.go:42] ["init kafka Config "] [commonConfig="+map[api.version.request:true bootstrap.servers:kafka-cluster-reinstall-22:9092 reconnect.backoff.max.ms:5000 reconnect.backoff.ms:20]"] [extraConsumerConfig="+map[]"] [extraProducerConfig="+map[]"]
[2022/11/26 10:36:37.050 +00:00] [INFO] [kafka/kafka_client.go:42] ["init kafka Config "] [commonConfig="+map[api.version.request:true bootstrap.servers:kafka-cluster-reinstall-22:9092 reconnect.backoff.max.ms:5000 reconnect.backoff.ms:20]"] [extraConsumerConfig="+map[]"] [extraProducerConfig="+map[]"]
[2022/11/26 10:36:37.050 +00:00] [INFO] [datanode/flow_graph_dmstream_input_node.go:68] ["datanode seek successfully"] ["seek msgID"="\"\u0003\u0000\u0000\u0000\u0000\u0000\u0000"] [pchannel=by-dev-rootcoord-dml_7] [vchannel=by-dev-rootcoord-dml_7_437638217426099634v1] [position=1970/01/01 00:00:00.000 +00:00] [tsLag=463738h36m37.050370781s] ["collection ID"=437638217426099634] [elapse=240.592553ms]
[2022/11/26 10:36:37.050 +00:00] [INFO] [datanode/flow_graph_insert_buffer_node.go:616] ["datanode AsProducer"] [TimeTickChannelName=by-dev-datacoord-timetick-channel]
[2022/11/26 10:36:37.050 +00:00] [INFO] [datanode/flow_graph_dmstream_input_node.go:80] ["datanode AsConsumer"] ["physical channel"=by-dev-rootcoord-dml_7] [subName=by-dev-dataNode-56-by-dev-rootcoord-dml_7_437638217426099634v1] ["collection ID"=437638217426099634]
[2022/11/26 10:36:37.050 +00:00] [INFO] [kafka/kafka_client.go:42] ["init kafka Config "] [commonConfig="+map[api.version.request:true bootstrap.servers:kafka-cluster-reinstall-22:9092 reconnect.backoff.max.ms:5000 reconnect.backoff.ms:20]"] [extraConsumerConfig="+map[]"] [extraProducerConfig="+map[]"]
panic: assignment to entry in nil map

goroutine 590 [running]:
github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/kafka.(*kafkaMessage).Properties(0xc001fb4150)
	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/kafka/kafka_message.go:26 +0x125
github.com/milvus-io/milvus/internal/mq/msgstream.(*MqTtMsgStream).consumeToTtMsg(0xc001b2c200, {0x38440e0, 0xc001b1a180})
	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_msgstream.go:813 +0x37b
created by github.com/milvus-io/milvus/internal/mq/msgstream.(*MqTtMsgStream).bufMsgPackToChannel
	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_msgstream.go:694 +0x4ca
```

```
[2022-11-26T10:40:00.362Z] + kubectl get pods -o wide

[2022-11-26T10:40:00.362Z] + grep kafka-cluster-reinstall-22

[2022-11-26T10:40:00.362Z] kafka-cluster-reinstall-22-0                                     2/2     Running            2 (32m ago)      32m    10.102.7.161    devops-node11   <none>           <none>

[2022-11-26T10:40:00.362Z] kafka-cluster-reinstall-22-1                                     2/2     Running            0                32m    10.102.6.138    devops-node10   <none>           <none>

[2022-11-26T10:40:00.362Z] kafka-cluster-reinstall-22-2                                     2/2     Running            0                32m    10.102.5.116    devops-node21   <none>           <none>

[2022-11-26T10:40:00.362Z] kafka-cluster-reinstall-22-etcd-0                                1/1     Running            0                32m    10.102.6.134    devops-node10   <none>           <none>

[2022-11-26T10:40:00.362Z] kafka-cluster-reinstall-22-etcd-1                                1/1     Running            0                32m    10.102.10.188   devops-node20   <none>           <none>

[2022-11-26T10:40:00.362Z] kafka-cluster-reinstall-22-etcd-2                                1/1     Running            0                32m    10.102.7.166    devops-node11   <none>           <none>

[2022-11-26T10:40:00.362Z] kafka-cluster-reinstall-22-exporter-84d959f98d-gx9b7             1/1     Running            4 (32m ago)      32m    10.102.7.157    devops-node11   <none>           <none>

[2022-11-26T10:40:00.362Z] kafka-cluster-reinstall-22-milvus-datacoord-548dc5f65-d7bwh      1/1     Running            0                32m    10.102.6.122    devops-node10   <none>           <none>

[2022-11-26T10:40:00.362Z] kafka-cluster-reinstall-22-milvus-datanode-9d56bb597-k22v4       0/1     CrashLoopBackOff   10 (3m23s ago)   32m    10.102.10.185   devops-node20   <none>           <none>

[2022-11-26T10:40:00.362Z] kafka-cluster-reinstall-22-milvus-datanode-9d56bb597-vdgjz       0/1     CrashLoopBackOff   10 (2m19s ago)   32m    10.102.6.123    devops-node10   <none>           <none>

[2022-11-26T10:40:00.362Z] kafka-cluster-reinstall-22-milvus-indexcoord-b5b5c59d5-x55tj     1/1     Running            0                32m    10.102.6.124    devops-node10   <none>           <none>

[2022-11-26T10:40:00.362Z] kafka-cluster-reinstall-22-milvus-indexnode-559dbcc865-47fxk     1/1     Running            0                32m    10.102.6.126    devops-node10   <none>           <none>

[2022-11-26T10:40:00.362Z] kafka-cluster-reinstall-22-milvus-indexnode-559dbcc865-tdbdn     1/1     Running            0                32m    10.102.7.156    devops-node11   <none>           <none>

[2022-11-26T10:40:00.362Z] kafka-cluster-reinstall-22-milvus-indexnode-559dbcc865-v9w55     1/1     Running            0                32m    10.102.6.130    devops-node10   <none>           <none>

[2022-11-26T10:40:00.362Z] kafka-cluster-reinstall-22-milvus-proxy-6f4c8b5689-kl8pt         1/1     Running            0                32m    10.102.6.128    devops-node10   <none>           <none>

[2022-11-26T10:40:00.362Z] kafka-cluster-reinstall-22-milvus-querycoord-5f9bd44654-8sbbs    1/1     Running            0                32m    10.102.6.125    devops-node10   <none>           <none>

[2022-11-26T10:40:00.362Z] kafka-cluster-reinstall-22-milvus-querynode-786b4cc96d-8mgzb     1/1     Running            8 (18m ago)      32m    10.102.6.127    devops-node10   <none>           <none>

[2022-11-26T10:40:00.362Z] kafka-cluster-reinstall-22-milvus-querynode-786b4cc96d-b8k5l     1/1     Running            8 (16m ago)      32m    10.102.7.158    devops-node11   <none>           <none>

[2022-11-26T10:40:00.362Z] kafka-cluster-reinstall-22-milvus-querynode-786b4cc96d-p7fmf     1/1     Running            8 (18m ago)      32m    10.102.10.186   devops-node20   <none>           <none>

[2022-11-26T10:40:00.363Z] kafka-cluster-reinstall-22-milvus-rootcoord-55565b6cd-vdmvd      1/1     Running            0                32m    10.102.7.155    devops-node11   <none>           <none>

[2022-11-26T10:40:00.363Z] kafka-cluster-reinstall-22-minio-0                               1/1     Running            0                32m    10.102.6.133    devops-node10   <none>           <none>

[2022-11-26T10:40:00.363Z] kafka-cluster-reinstall-22-minio-1                               1/1     Running            0                32m    10.102.7.164    devops-node11   <none>           <none>

[2022-11-26T10:40:00.363Z] kafka-cluster-reinstall-22-minio-2                               1/1     Running            0                32m    10.102.10.190   devops-node20   <none>           <none>

[2022-11-26T10:40:00.363Z] kafka-cluster-reinstall-22-minio-3                               1/1     Running            0                32m    10.102.8.232    devops-node12   <none>           <none>

[2022-11-26T10:40:00.363Z] kafka-cluster-reinstall-22-zookeeper-0                           1/1     Running            0                32m    10.102.6.135    devops-node10   <none>           <none>

[2022-11-26T10:40:00.363Z] kafka-cluster-reinstall-22-zookeeper-1                           1/1     Running            0                32m    10.102.7.163    devops-node11   <none>           <none>

[2022-11-26T10:40:00.363Z] kafka-cluster-reinstall-22-zookeeper-2                           1/1     Running            0                32m    10.102.10.192   devops-node20   <none>           <none>
```

### Expected Behavior

all test cases passed

### Steps To Reproduce

```markdown
1. deploy Milvus with Kafka as mq
2. run test cases `test/python_client/deploy/testcases/test_action_first_deployment.py`
```

### Milvus Log

release name: kafka-standalone-reinstall-21

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_kafka_cron/detail/deploy_test_kafka_cron/21/pipeline
log:

[artifacts-kafka-standalone-reinstall-21-server-second-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/10099971/artifacts-kafka-standalone-reinstall-21-server-second-deployment-logs.tar.gz)

**Comment by jaime0815** [comment]
Kafka message may has not header information, so https://github.com/milvus-io/milvus/blob/dd7e309a295941647c4fa2c9e2a602f29b22388a/internal/mq/msgstream/mqwrapper/kafka/kafka_message.go#L26 potentially occurs panic because nil value

**Comment by zhuwenxing** [comment]
Verified with image `master-20221128-b5f178f2`
