### ISSUE TITLE
[Bug]: [Nightly]Kafka runs much slowly than ever and will be killed over 6 hours

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#20850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:f588a73
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.0.dev15
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Kafka runs much slowly than ever and will be killed over 6 hours.
```
script returned exit code 124
```

### Expected Behavior

normal running

### Steps To Reproduce

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/203/pipeline/136

### Milvus Log

[artifacts-milvus-distributed-kafka-nightly-203-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/203/artifact/artifacts-milvus-distributed-kafka-nightly-203-pymilvus-e2e-logs.tar.gz)

**Comment by jaime0815** [comment]
```
2022-11-28T02:21:29.429382539+08:00 stderr F panic: assignment to entry in nil map
2022-11-28T02:21:29.429418247+08:00 stderr F 
2022-11-28T02:21:29.429429495+08:00 stderr F goroutine 8431 [running]:
2022-11-28T02:21:29.429442734+08:00 stderr F github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/kafka.(*kafkaMessage).Properties(0xc0031e2138)
2022-11-28T02:21:29.429448698+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/kafka/kafka_message.go:26 +0x125
2022-11-28T02:21:29.429454487+08:00 stderr F github.com/milvus-io/milvus/internal/mq/msgstream.(*MqTtMsgStream).consumeToTtMsg(0xc000542a00, {0x38440e0, 0xc0016191a0})
2022-11-28T02:21:29.429459471+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_msgstream.go:813 +0x37b
2022-11-28T02:21:29.429464672+08:00 stderr F created by github.com/milvus-io/milvus/internal/mq/msgstream.(*MqTtMsgStream).bufMsgPackToChannel
2022-11-28T02:21:29.429470082+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_msgstream.go:694 +0x4ca
```

**Comment by jaime0815** [comment]
related to #20846

**Comment by yanliang567** [comment]
@NicoYuan1986 please help to verify it

**Comment by NicoYuan1986** [comment]
Kafka won't be killed for timeout(6h) now.
