### ISSUE TITLE
[Bug]: Standalone install failed due to panic of standalone pod when Mq is Kafka

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#20873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20221128-6824188b
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
 + kubectl get pods -o wide
 + grep kafka-standalone-reinstall-29
 kafka-standalone-reinstall-29-0                                   2/2     Running            1 (4m13s ago)   4m33s   10.102.7.205    devops-node11   <none>           <none>
 kafka-standalone-reinstall-29-1                                   2/2     Running            0               4m33s   10.102.6.120    devops-node10   <none>           <none>
 kafka-standalone-reinstall-29-2                                   2/2     Running            0               4m33s   10.102.10.38    devops-node20   <none>           <none>
 kafka-standalone-reinstall-29-etcd-0                              1/1     Running            0               4m33s   10.102.7.206    devops-node11   <none>           <none>
 kafka-standalone-reinstall-29-exporter-7cd55566f4-fsfs9           1/1     Running            3 (4m12s ago)   4m33s   10.102.7.198    devops-node11   <none>           <none>
 kafka-standalone-reinstall-29-milvus-standalone-75bfdc55f8f9pqc   0/1     Running            3 (39s ago)     4m33s   10.102.7.204    devops-node11   <none>           <none>
 kafka-standalone-reinstall-29-minio-7d8bdfd6d9-nqx7p              1/1     Running            0               4m33s   10.102.10.33    devops-node20   <none>           <none>
 kafka-standalone-reinstall-29-zookeeper-0                         1/1     Running            0               4m33s   10.102.7.208    devops-node11   <none>           <none>
 kafka-standalone-reinstall-29-zookeeper-1                         1/1     Running            0               4m33s   10.102.10.37    devops-node20   <none>           <none>
 kafka-standalone-reinstall-29-zookeeper-2                         1/1     Running            0               4m33s   10.102.8.235    devops-node12   <none>           <none>
```

```
[2022/11/28 10:10:02.838 +00:00] [INFO] [datanode/data_node.go:411] ["handle put event: new data sync service success"] [vChanName=by-dev-rootcoord-dml_1_437683501703888900v1]
[2022/11/28 10:10:02.838 +00:00] [INFO] [datanode/data_sync_service.go:130] ["dataSyncService starting flow graph"] [collectionID=437683501703888900] [vChanName=by-dev-rootcoord-dml_0_437683501703888900v0]
[2022/11/28 10:10:02.838 +00:00] [INFO] [datanode/data_node.go:411] ["handle put event: new data sync service success"] [vChanName=by-dev-rootcoord-dml_0_437683501703888900v0]
[2022/11/28 10:10:02.839 +00:00] [INFO] [datacoord/channel_manager.go:627] ["datanode successfully watched channel"] [nodeID=3] ["channel name"=by-dev-rootcoord-dml_1_437683501703888900v1]
[2022/11/28 10:10:02.839 +00:00] [INFO] [datacoord/channel_manager.go:627] ["datanode successfully watched channel"] [nodeID=3] ["channel name"=by-dev-rootcoord-dml_0_437683501703888900v0]
[2022/11/28 10:10:02.839 +00:00] [INFO] [datacoord/channel_checker.go:112] ["stop timer before timeout"] ["watch state"=ToWatch] [nodeID=3] ["channel name"=by-dev-rootcoord-dml_0_437683501703888900v0] ["timeout time"=2022/11/28 10:10:22.815 +00:00]
[2022/11/28 10:10:02.839 +00:00] [INFO] [datacoord/channel_checker.go:112] ["stop timer before timeout"] ["watch state"=ToWatch] [nodeID=3] ["channel name"=by-dev-rootcoord-dml_1_437683501703888900v1] ["timeout time"=2022/11/28 10:10:22.815 +00:00]
panic: assignment to entry in nil map

goroutine 1274 [running]:
github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/kafka.(*kafkaMessage).Properties(0xc00228edb0)
	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/kafka/kafka_message.go:26 +0x125
github.com/milvus-io/milvus/internal/mq/msgstream.(*MqTtMsgStream).consumeToTtMsg(0xc004050600, {0x38458e0, 0xc007fa2fc0})
	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_msgstream.go:813 +0x37b
created by github.com/milvus-io/milvus/internal/mq/msgstream.(*MqTtMsgStream).bufMsgPackToChannel
	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_msgstream.go:694 +0x4ca
```

### Expected Behavior

Install success

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_kafka_cron/detail/deploy_test_kafka_cron/29/pipeline

log:
[artifacts-kafka-standalone-reinstall-29-server-second-deployment-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/10109282/artifacts-kafka-standalone-reinstall-29-server-second-deployment-logs.1.tar.gz)

### Anything else?

crash pod name: kafka-standalone-reinstall-29-milvus-standalone-75bfdc55f8f9pqc

**Comment by zhuwenxing** [comment]
dup with https://github.com/milvus-io/milvus/issues/20846
