### ISSUE TITLE
[Bug]: system panic when trying to create DISKANN index if disk_index is not enabled when compiling

### ISSUE THREAD

**Issue by czs007** [milvus-io/milvus#20871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

system panic when trying to create DISKANN index if disk_index is not enabled when compiling.

[2022/11/29 10:25:18.145 +08:00] [INFO] [indexnode/task.go:359] ["disk index params are ready"] [buildID=437698859115092634] ["index params"="{\"beamwidth_ratio\":\"4.000000\",\"build_dram_budget_gb\":\"22.393871\",\"collection_id\":\"437698859114692612\",\"dim\":\"128\",\"field_id\":\"102\",\"index_build_id\":\"437698859115092634\",\"index_id\":\"0\",\"index_type\":\"DISKANN\",\"index_version\":\"1\",\"max_degree\":\"56\",\"metric_type\":\"L2\",\"num_build_thread\":\"12\",\"num_build_thread_ratio\":\"1.000000\",\"num_load_thread_ratio\":\"8.000000\",\"partition_id\":\"437698859114692613\",\"pq_code_budget_gb\":\"0.011921\",\"pq_code_budget_gb_ratio\":\"0.125000\",\"search_cache_budget_gb_ratio\":\"0.100000\",\"search_list_size\":\"100\",\"segment_id\":\"437698859114892620\"}"]
[2022/11/29 10:25:18.146 +08:00] [WARN] [indexcgowrapper/helper.go:76] ["failed to create index, C Runtime Exception: [UnexpectedError] Error in knowhere::VecIndexPtr knowhere::VecIndexFactory::CreateVecIndex(const IndexType&, knowhere::IndexMode) at VecIndexFactory.cpp:61: Invalid index type DISKANN\n"]
[2022/11/29 10:25:18.146 +08:00] [ERROR] [indexnode/task.go:366] ["failed to create index"] [error="[UnexpectedError] Error in knowhere::VecIndexPtr knowhere::VecIndexFactory::CreateVecIndex(const IndexType&, knowhere::IndexMode) at VecIndexFactory.cpp:61: Invalid index type DISKANN"] [stack="github.com/milvus-io/milvus/internal/indexnode.(*indexBuildTask).BuildDiskAnnIndex.func1\n\t/home/czs/milvus/internal/indexnode/task.go:366\ngithub.com/milvus-io/milvus/internal/util/concurrency.(*Pool).Submit.func1\n\t/home/czs/milvus/internal/util/concurrency/pool.go:46\ngithub.com/panjf2000/ants/v2.(*goWorker).run.func1\n\t/home/czs/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.8/worker.go:70"]
[2022/11/29 10:25:18.148 +08:00] [INFO] [gc/gc_tuner.go:81] ["GC Tune done"] ["previous GOGC"=200] ["heapuse "=69] ["total memory"=8984] ["next GC"=170] ["new GOGC"=200]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x28de094]

goroutine 3154 [running]:
github.com/milvus-io/milvus/internal/util/indexcgowrapper.(*CgoIndex).CleanLocalData.func1(0xc004409358?)
	/home/czs/milvus/internal/util/indexcgowrapper/index.go:339 +0x14
github.com/milvus-io/milvus/internal/util/indexcgowrapper.(*CgoIndex).CleanLocalData(0xc0017a1248?)
	/home/czs/milvus/internal/util/indexcgowrapper/index.go:339 +0x19
github.com/milvus-io/milvus/internal/indexnode.(*indexBuildTask).BuildDiskAnnIndex(0xc00447dce0, {0x40864d0?, 0xc0045d3500})
	/home/czs/milvus/internal/indexnode/task.go:377 +0xdc8
github.com/milvus-io/milvus/internal/indexnode.(*indexBuildTask).BuildIndex(0xc00447dce0, {0x40864d0, 0xc0045d3500})
	/home/czs/milvus/internal/indexnode/task.go:241 +0xa5
github.com/milvus-io/milvus/internal/indexnode.(*TaskScheduler).processTask.func1(0xc004409e00)
	/home/czs/milvus/internal/indexnode/task_scheduler.go:205 +0x82
github.com/milvus-io/milvus/internal/indexnode.(*TaskScheduler).processTask(0xc0006fc580, {0x4098168, 0xc00447dce0}, {0xc001458d00?, 0xc004694240?})
	/home/czs/milvus/internal/indexnode/task_scheduler.go:218 +0x409
github.com/milvus-io/milvus/internal/indexnode.(*TaskScheduler).indexBuildLoop.func1(0x18c5780?, {0x4098168?, 0xc00447dce0?})
	/home/czs/milvus/internal/indexnode/task_scheduler.go:247 +0x6c
created by github.com/milvus-io/milvus/internal/indexnode.(*TaskScheduler).indexBuildLoop
	/home/czs/milvus/internal/indexnode/task_scheduler.go:245 +0x29

**Comment by yah01** [comment]
#20861 fixes this

**Comment by xige-16** [comment]
verify pass
