### ISSUE TITLE
[Bug]: [Nightly]Search failed because of invalid shard leader

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#20946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: b46601f
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.1.dev3
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Search failed because of invalid shard leader.
The error occurred both in master and 2.2 branch in several cases. Take one for example.
```
[2022-12-01T21:34:43.050Z] [2022-12-01 20:38:35 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=Invalid shard leader)>, <Time:{'RPC start': '2022-12-01 20:38:29.946417', 'RPC error': '2022-12-01 20:38:35.641837'}> (decorators.py:108)
[2022-12-01T21:34:43.050Z] [2022-12-01 20:38:35 - ERROR - ci_test]: Traceback (most recent call last):
[2022-12-01T21:34:43.050Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2022-12-01T21:34:43.050Z]     res = func(*args, **_kwargs)
[2022-12-01T21:34:43.050Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2022-12-01T21:34:43.050Z]     return func(*arg, **kwargs)
[2022-12-01T21:34:43.050Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 610, in search
[2022-12-01T21:34:43.050Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,
[2022-12-01T21:34:43.050Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2022-12-01T21:34:43.050Z]     raise e
[2022-12-01T21:34:43.050Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2022-12-01T21:34:43.050Z]     return func(*args, **kwargs)
[2022-12-01T21:34:43.050Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2022-12-01T21:34:43.050Z]     ret = func(self, *args, **kwargs)
[2022-12-01T21:34:43.050Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
[2022-12-01T21:34:43.050Z]     raise e
[2022-12-01T21:34:43.050Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2022-12-01T21:34:43.050Z]     return func(self, *args, **kwargs)
[2022-12-01T21:34:43.050Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 469, in search
[2022-12-01T21:34:43.050Z]     return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)
[2022-12-01T21:34:43.050Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 438, in _execute_search_requests
[2022-12-01T21:34:43.050Z]     raise pre_err
[2022-12-01T21:34:43.050Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 429, in _execute_search_requests
[2022-12-01T21:34:43.050Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2022-12-01T21:34:43.051Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Invalid shard leader)>
[2022-12-01T21:34:43.051Z]  (api_request.py:39)
[2022-12-01T21:34:43.051Z] [2022-12-01 20:38:35 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Invalid shard leader)> (api_request.py:40)
```

### Expected Behavior

PASS

### Steps To Reproduce

```markdown
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/19/pipeline/187
```

### Milvus Log

1. log: [artifacts-milvus-distributed-pulsar-nightly-19-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/19/artifact/artifacts-milvus-distributed-pulsar-nightly-19-pymilvus-e2e-logs.tar.gz)
2. collection name: search_collection_Sl0dwlXd
3. failed timeline: [2022-12-01T20:38:36.338Z] [gw2] [ 64%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_index_partitions_fuzzy[5000-500-128-True-False-partition_names0]

**Comment by sunby** [comment]
Same as https://github.com/milvus-io/milvus/issues/21000

**Comment by xiaofan-luan** [comment]
assign @yanliang567  can you help on verifying it?

**Comment by yanliang567** [comment]
@NicoYuan1986 any updates from recent nightly runs?

**Comment by NicoYuan1986** [comment]
> @NicoYuan1986 any updates from recent nightly runs?

The issue hasn't occurred since my last comment.

**Comment by yanliang567** [comment]
close it for now as commented above
