### ISSUE TITLE
[Bug]: Failed to load collection, after in-disk index built

### ISSUE THREAD

**Issue by siwenyang** [milvus-io/milvus#20956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.x
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.2.0
- OS(Ubuntu or CentOS): Ubuntu 20.04
- CPU/Memory: 467G available
- GPU: 
- Others: disk 247G available
```

### Current Behavior

When collection.load(), error like below:

RPC error: [load_collection], <MilvusException: (code=1, message=failed to load collection, err=no enough nodes to create replicas[NoEnoughNode])>, <Time:{'RPC start': '2022-12-01 23:02:34.870841', 'RPC error': '2022-12-01 23:02:34.883944'}>
Traceback (most recent call last):
  File "gecoding_build_diskann_index_milvus.py", line 41, in <module>
    collection.load(replica_number=1)
  File "/home/siwen/.conda/envs/aencoder2/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 424, in load
    conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/home/siwen/.conda/envs/aencoder2/lib/python3.6/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/home/siwen/.conda/envs/aencoder2/lib/python3.6/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/home/siwen/.conda/envs/aencoder2/lib/python3.6/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/home/siwen/.conda/envs/aencoder2/lib/python3.6/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/home/siwen/.conda/envs/aencoder2/lib/python3.6/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/home/siwen/.conda/envs/aencoder2/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 665, in load_collection
    raise MilvusException(response.error_code, response.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=failed to load collection, err=no enough nodes to create replicas[NoEnoughNode])>

### Expected Behavior

When collection.load(), should be loaded.

### Steps To Reproduce

```markdown
1. insert 7.5 million data with dim 256
2. build index with "DISKANN"
3. load collection
```

### Anything else?

milvus log sent to chenlong, thank you for help

**Comment by yanliang567** [comment]
@siwenyang how do you deploy milvus? Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @siwenyang

**Comment by xiaofan-luan** [comment]
seems to be "no enough nodes to create replicas"
pls check how many replica and and how many nodes you own.
Also if would be really helpful to offer logs
