### ISSUE TITLE
[Bug]: querynode panic  with “invalid memory address or nil pointer dereference”

### ISSUE THREAD

**Issue by bingbb47** [milvus-io/milvus#21005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.4
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.1
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

after writing data，when load the collection, querynode panic and restart;
 and the state is not restored after restart;
do you have any idea about the reason of the panic and how to avoid?

### Milvus Log

[2022/12/05 22:56:19.142 +00:00] [INFO] [querynode/task.go:243] ["successfully load growing segments done in WatchDmChannels"] [collectionID=437766828564938753] [unFlushedSegmentIDs="[]"]
[2022/12/05 22:56:19.142 +00:00] [INFO] [querynode/task.go:275] ["watchDMChannel, group channels done"] [collectionID=437766828564938753]
[2022/12/05 22:56:19.142 +00:00] [INFO] [querynode/task.go:290] ["watchDMChannel, add check points info for unflushed segments done"] [collectionID=437766828564938753] [unflushedSegmentIDs="[]"]
[2022/12/05 22:56:19.143 +00:00] [INFO] [querynode/task.go:315] ["watchDMChannel, add check points info for flushed segments done"] [collectionID=437766828564938753] [flushedSegmentIDs="[437766828669796354,437766828866404354,437766832811409410,437766837294333953,437766838971793409,437766840400478209,437766841160957953,437766841252708354,437766841344196610,437766841409994753,437766841449316353,437766841475268609,437766841567281153,437766841724567554,437766841763889153,437766841790103553,437766841802948610,437766841829425154,437766841934282753,437766842799095810,437766842930167809,437766842982858753,437766843021918209,437766843048394753,437766843100823554,437766843126775809,437766843205419010,437766843310538753,437766844516401153,437766845394321409,437766845591191554,437766845669572609,437766845761323009,437766845892657153,437766846036574209,437766846154801153,437766846233444354,437766846325194754,437766846404624386,437766846547755009,437766846679089154,437766846783946753,437766847137579009,437766847334449153,437766847413092353,437766847517949954,437766847675236353,437766847832522753,437766847898058753,437766847989809153,437766848042237954,437766848094404609,437766848133726209,437766848251953154,437766849208778754,437766849877245953,437766850073591809,437766850218033154,437766850663677953,437766851135275009,437773063201226753,437773063463108609,437773063738621954,437773064184266753,437773064511946753,437773065442557953,437773065612951554,437773065769975809,437773065993060353,437773066254942209,437773066491133954,437773066726801410,437773066936778754,437773067015421953,437773067107110209,437773067225137153,437773069060145153,437773069387825154,437773069518897154,437773069663076353,437773069754564610,437773069846315009,437773069964541953,437773070121566209,437773070305329154,437773070410186753,437773071747121153,437773073346199553,437773073830903810,437773074132631554,437773074787729409,437773075600375809,437773076072235009,437773076413284353,437773077003108353,437773077330788353,437773077566717954,437773077789278209,437773078182756353,437773078444900354,437773078615031810,437773078720151554,437773078995402753,437773079349297153,437773079414833153,437773079480107010,437773079519428609,437773079572119553,437773079611441153,437773079650762753,437773079703191554,437773079729405954,437773079781572609,437773079808049154,437773079834001410,437773079860477954,437773079886692353,437773079912906754,437773079939121154,437773079952228354,437781566798692353,437781566811537410,437781566838013954,437781566877073409,437781566892802049,437781567008407553,437781567047467010,437781567087050753,437781567113003010,437781567152324609,437781567178801153,437781567205015553,437781567322718210,437781567467159553,437781567480004610,437781567519326209,437781567545540609,437781567558647810,437781567585124353,437781567624183809,437781567716196353,437781568188055553,437781568253591553,437781568345341953,437781568397770753,437781568437092353,437781568528580609,437781568607223809,437781568712281410,437781568790724609,437781568830308353,437781568856522753,437781568908951553,437781568948273153,437781569039761410,437781569459191809,437781569524989954,437781569577156610,437781569616740353,437781569721597954,437781571084684609,437781571333521410,437781571687677954,437781571923607553,437781572094001154,437781572316823554,437781572644241410,437781572880433154,437781573365399554,437781573627543554,437781573811044353,437781573915901953,437781574112247809,437781574374653954,437781574531940353,437781574715441154,437781574767869953,437781574872727554,437781576799485953,437781578136420353,437793529831620609,437793532296036354,437793533134635010,437793533632970753,437793534025924609,437793534694391809,437793535087869954,437793535402180610,437793536411435009,437793536791805953,437793537080164353,437793539098411009,437793539347709953,437793539452567553,437793539609591809,437793539754033154,437793539989962754,437793540107927553,437793540343857153,437793540632215553,437793540790026242,437793540881190209,437793540986109953,437793541077860353,437793541116919810,437793541169610753,437793541195563009,437793541287313410,437793544406827009,437793544918469954,437793545717547009,437793547106910210,437793547696734209,437793548247236610,437793549374455809,437793549571063810,437793550672330753,437793550882045954,437793551013642241,437793552664625153,437793552913661954,437793553398366210,437793553529700354,437793553726308353,437793553936023553,437793554119524353,437793554486525953,437793554670026753,437793554892849153,437793555037028353,437793555181207553,437793555312479554,437793555521732610,437793555613745154,437793555718602754,437793556740964353,437793558051684353,437793558261137409,437793558536650753,437793559467261953,437809706764075009,437809706908516353,437809707013373953,437809707118231554,437809708114116609,437809708389629953,437809708651773954,437809708822167553,437809709031882754,437809709228228610,437809709608337409,437809709739671553,437809709818314753,437809709896957953,437809709988446209,437809711823454210,437809712020324353,437809712295575554,437809712597041153,437809712793649153,437809713016471553,437809713173757953,437809713304829953,437809713449009153,437809713645617153,437809713737367553,437809713868177409,437809713973035010,437809714077892609,437809714942967809,437809715270909953,437809715362660353,437809715480625153,437809715585682753,437809715716292609,437809715834519554,437809715965591553,437809716083556353,437809718704996353,437809718796746753,437809718927818753,437809719255498754,437809719517380610,437809719648914753,437809719779786754,437809719858429953,437809719963287554,437809720146526209,437809720395825154,437809720500682753,437809720684183553,437809720946327554,437809721156042754,437809721273745409,437809721709428737,437809721758973954,437809721876938753,437809721915998209,437809722165297153,437809725678026753]"]
[2022/12/05 22:56:19.143 +00:00] [INFO] [querynode/impl.go:132] ["watchDmChannelsTask WaitToFinish done"] [collectionID=437766828564938753] [nodeID=126]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x2266f54]
goroutine 244 [running]:
github.com/milvus-io/milvus/internal/querynode.(*watchDmChannelsTask).Execute(0xc00113eb80, 0x43b7d10, 0xc000c6f780, 0x0, 0x0)
/go/src/github.com/milvus-io/milvus/internal/querynode/task.go:328 +0x2794
github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).processTask(0xc0006d2a00, 0x43ce320, 0xc00113eb80, 0x43ce218, 0xc00017a780)
/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:110 +0x173
github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).taskLoop(0xc0006d2a00)
/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:127 +0x15a
created by github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).Start

**Comment by xiaofan-luan** [comment]
hi @bingbb47, this might be a fixed issue in 2.2, and we will release 2.2.1 this week.
Could you pls upgrade to 2.2.1 and retry?

**Comment by inkinworld** [comment]
> hi @bingbb47, this might be a fixed issue in 2.2, and we will release 2.2.1 this week. Could you pls upgrade to 2.2.1 and retry?

after trace same part code, found this commit in 2.2.0 branch: https://github.com/milvus-io/milvus/commit/a3f84f2ea33bdcb17f473940cc29451f36e2d346

it sems mean user use 2.1.0 may crash cause by nil ref of  field  about `dropped segment info`. in this issue, we infer `droppedSegment.DmlPositio` is nil.

cherry pick this commit to 2.1.0 may be a good choice.

**Comment by yanliang567** [comment]
there are no plans to release on 2.1 branch, so we suggest that upgrade to 2.2.0

/assign @inkinworld

**Comment by inkinworld** [comment]
@yanliang567 Thanks for your reply.
We planned to upgrade, but patched first due to business migration costs.
Looking forward to the data backup feature and smooth upgrade capability of version 2.2.x， this will make upgrading very flexible.
