### ISSUE TITLE
[Bug]: ut fail: channel_checker_test TestChannelStateTimer

### ISSUE THREAD

**Issue by SimFG** [milvus-io/milvus#21039]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

link: https://github.com/milvus-io/milvus/actions/runs/3635641315/jobs/6134917657
```
=== RUN   TestChannelStateTimer
coverage: 3.0% of statements in ./...
panic: test timed out after 10m0s

goroutine 160 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:2029 +0xbb
created by time.goFunc
	/usr/local/go/src/time/sleep.go:176 +0x48

goroutine 1 [chan receive, 10 minutes]:
testing.(*T).Run(0xc0000969c0, {0x30c5481, 0x15}, 0x315a010)
	/usr/local/go/src/testing/testing.go:1487 +0x750
testing.runTests.func1(0x0?)
	/usr/local/go/src/testing/testing.go:1839 +0x9a
testing.tRunner(0xc0000969c0, 0xc0004ddac8)
	/usr/local/go/src/testing/testing.go:1439 +0x214
testing.runTests(0xc0004145a0?, {0x4491c60, 0x85, 0x85}, {0xc0000b8188?, 0x1c?, 0x45d1500?})
	/usr/local/go/src/testing/testing.go:1837 +0x7e5
testing.(*M).Run(0xc0004145a0)
	/usr/local/go/src/testing/testing.go:1719 +0xa72
github.com/milvus-io/milvus/internal/datacoord.TestMain(0x44ccf60?)
	/go/src/github.com/milvus-io/milvus/internal/datacoord/server_test.go:64 +0xd7
main.main()
	_testmain.go:1123 +0x410

goroutine 123 [select, 2 minutes]:
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc000558c00)
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/balancer_conn_wrappers.go:112 +0x150
created by google.golang.org/grpc.newCCBalancerWrapper
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/balancer_conn_wrappers.go:73 +0x4b7

goroutine 122 [select, 2 minutes]:
google.golang.org/grpc.(*pickerWrapper).pick(0xc00059a750, {0x35533b8, 0xc00059b230}, 0x0, {{0x30c6d54?, 0x0?}, {0x35533b8?, 0xc00059b230?}})
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/picker_wrapper.go:103 +0x1f0
google.golang.org/grpc.(*ClientConn).getTransport(0xc0000b9500, {0x35533b8, 0xc00059b230}, 0xd0?, {0x30c6d54, 0x16})
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/clientconn.go:910 +0x9b
google.golang.org/grpc.(*clientStream).newAttemptLocked(0xc0005afe60, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/stream.go:416 +0xf3b
google.golang.org/grpc.newClientStreamWithParams({0x35533b8, 0xc00059b170}, 0x45cf2a0, 0xc0000b9500, {0x30c6d54, 0x16}, {0x0, 0x0, 0x0, 0x0, ...}, ...)
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/stream.go:306 +0x1191
google.golang.org/grpc.newClientStream.func2({0x35533b8, 0xc00059b170}, 0xc00059b170?)
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/stream.go:192 +0x19a
google.golang.org/grpc.newClientStream({0x35533b8, 0xc00059b170}, 0x45cf2a0, 0xc0000b9500, {0x30c6d54, 0x16}, {0xc000558f00, 0x3, 0x4})
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/stream.go:220 +0x734
google.golang.org/grpc.invoke({0x35533b8, 0xc00059b170}, {0x30c6d54, 0x16}, {0x305abc0, 0xc0002939e0}, {0x302cb80, 0xc0001583c0}, 0x0?, {0xc000558f00, ...})
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/call.go:66 +0xd3
go.etcd.io/etcd/client/v3.(*Client).unaryClientInterceptor.func1({0x3553348, 0xc0000c8008}, {0x30c6d54, 0x16}, {0x305abc0, 0xc0002939e0}, {0x302cb80, 0xc0001583c0}, 0xc0000b9500, 0x315b548, ...)
	/go/pkg/mod/go.etcd.io/etcd/client/v3@v3.5.0/retry_interceptor.go:58 +0x51c
google.golang.org/grpc.(*ClientConn).Invoke(0xc0000b9500, {0x3553348, 0xc0000c8008}, {0x30c6d54, 0x16}, {0x305abc0, 0xc0002939e0}, {0x302cb80, 0xc0001583c0}, {0xc000156c00, ...})
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/call.go:35 +0x26c
go.etcd.io/etcd/api/v3/etcdserverpb.(*kVClient).Range(0xc000011c70, {0x3553348, 0xc0000c8008}, 0x90?, {0xc000156c00, 0x4, 0x6})
	/go/pkg/mod/go.etcd.io/etcd/api/v3@v3.5.0/etcdserverpb/rpc.pb.go:6460 +0xf5
go.etcd.io/etcd/client/v3.(*retryKVClient).Range(0xc0005bed50, {0x3553348, 0xc0000c8008}, 0x24c0450?, {0x45cff00?, 0x3, 0x3})
	/go/pkg/mod/go.etcd.io/etcd/client/v3@v3.5.0/retry.go:105 +0x1ca
go.etcd.io/etcd/client/v3.(*kv).Do(0xc00059afc0, {_, _}, {0x1, {0xc00055b7e8, 0x12, 0x18}, {0xc00055b800, 0x12, 0x12}, ...})
	/go/pkg/mod/go.etcd.io/etcd/client/v3@v3.5.0/kv.go:149 +0x4fe
go.etcd.io/etcd/client/v3.(*kv).Get(0x203000?, {0x3553348, 0xc0000c8008}, {0xc00055b7d0, 0x12}, {0xc000011c98, 0x1, 0x1})
	/go/pkg/mod/go.etcd.io/etcd/client/v3@v3.5.0/kv.go:119 +0x11c
github.com/milvus-io/milvus/internal/config.(*EtcdSource).refreshConfigurations(0xc000585800)
	/go/src/github.com/milvus-io/milvus/internal/config/etcd_source.go:123 +0x18e
github.com/milvus-io/milvus/internal/config.(*EtcdSource).GetConfigurations(0xc000585800)
	/go/src/github.com/milvus-io/milvus/internal/config/etcd_source.go:88 +0x65
github.com/milvus-io/milvus/internal/config.(*Manager).pullSourceConfigs(0xc00039fc50, {0x30b214b, 0xa})
	/go/src/github.com/milvus-io/milvus/internal/config/manager.go:166 +0x103
github.com/milvus-io/milvus/internal/config.(*Manager).AddSource(0xc00039fc50, {0x3554ae0?, 0xc000585800})
	/go/src/github.com/milvus-io/milvus/internal/config/manager.go:150 +0x27f
github.com/milvus-io/milvus/internal/config.Init({0xc000433b50, 0x3, 0xd?})
	/go/src/github.com/milvus-io/milvus/internal/config/config.go:48 +0x4b6
github.com/milvus-io/milvus/internal/util/paramtable.(*BaseTable).initConfigsFromRemote(0x45d6520, 0x6b6afb?)
	/go/src/github.com/milvus-io/milvus/internal/util/paramtable/base_table.go:170 +0x57d
github.com/milvus-io/milvus/internal/util/paramtable.(*BaseTable).Init(0x45d6520)
	/go/src/github.com/milvus-io/milvus/internal/util/paramtable/base_table.go:120 +0x11d
github.com/milvus-io/milvus/internal/util/paramtable.(*ServiceParam).Init(0x45d6520)
	/go/src/github.com/milvus-io/milvus/internal/util/paramtable/service_param.go:57 +0x45
github.com/milvus-io/milvus/internal/util/paramtable.(*ComponentParam).Init(0x45d6520)
	/go/src/github.com/milvus-io/milvus/internal/util/paramtable/component_param.go:80 +0x45
github.com/milvus-io/milvus/internal/datacoord.getMetaKv(0xc000097ba0)
	/go/src/github.com/milvus-io/milvus/internal/datacoord/cluster_test.go:36 +0x33
github.com/milvus-io/milvus/internal/datacoord.TestChannelStateTimer(0x0?)
	/go/src/github.com/milvus-io/milvus/internal/datacoord/channel_checker_test.go:32 +0x48
testing.tRunner(0xc000097ba0, 0x315a010)
	/usr/local/go/src/testing/testing.go:1439 +0x214
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1486 +0x725

goroutine 176 [select, 2 minutes]:
google.golang.org/grpc.(*addrConn).resetTransport(0xc000394580)
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/clientconn.go:1146 +0x3bb
google.golang.org/grpc.(*addrConn).connect(0xc000394580)
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/clientconn.go:800 +0xbc
created by google.golang.org/grpc.(*acBalancerWrapper).Connect
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/balancer_conn_wrappers.go:409 +0x117
FAIL	github.com/milvus-io/milvus/internal/datacoord	600.336s
FAIL
make: *** [Makefile:233: codecov-go] Error 1
2
Error: Process completed with exit code 2.
```

**Comment by yanliang567** [comment]
@SimFG any updates?

**Comment by SimFG** [comment]
@yanliang567 I didn't encounter this problem again
