### ISSUE TITLE
[Bug]: DataNode panic when flush

### ISSUE THREAD

**Issue by bigsheeper** [milvus-io/milvus#21057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 039e9ce4
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/42060877/206337314-ff7dd74a-2251-414f-af8d-89c9259af768.png)
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7f021f4705c6]

runtime stack:
runtime.throw({0x35b6288?, 0x7f0221f92dca?})
	/home/sheep/sdk/go1.18.1/src/runtime/panic.go:992 +0x71
runtime.sigpanic()
	/home/sheep/sdk/go1.18.1/src/runtime/signal_unix.go:802 +0x3a9

goroutine 419 [syscall]:
runtime.cgocall(0x2c887e1, 0xc001038f68)
	/home/sheep/sdk/go1.18.1/src/runtime/cgocall.go:157 +0x5c fp=0xc001038f40 sp=0xc001038f08 pc=0x1189edc
github.com/milvus-io/milvus/internal/storage._Cfunc_ReleasePayloadWriter(0x7f01f43e5000)
	_cgo_gotypes.go:542 +0x45 fp=0xc001038f68 sp=0xc001038f40 pc=0x2443b05
github.com/milvus-io/milvus/internal/storage.(*PayloadWriter).ReleasePayloadWriter.func1(0x4fb9b48?)
	/home/sheep/workspace/milvus/internal/storage/payload.go:356 +0x3a fp=0xc001038fa0 sp=0xc001038f68 pc=0x24457da
github.com/milvus-io/milvus/internal/storage.(*PayloadWriter).ReleasePayloadWriter(0x3213ca0?)
	/home/sheep/workspace/milvus/internal/storage/payload.go:356 +0x19 fp=0xc001038fb8 sp=0xc001038fa0 pc=0x2445779
github.com/milvus-io/milvus/internal/storage.(*baseEventWriter).Close(...)
	/home/sheep/workspace/milvus/internal/storage/event_writer.go:162

### Steps To Reproduce

```markdown
Run hello_milvus.py
```

**Comment by longjiquan** [comment]
![image](https://user-images.githubusercontent.com/31589260/206405489-712e6102-da62-4638-8a36-9f64f63ca06a.png)

**Comment by XuanYang-cn** [comment]
repro locally today
```
156 [2022/12/09 14:58:10.615 +08:00] [INFO] [datanode/flow_graph_insert_buffer_node.go:351] ["merging sync task, updating flushed flag"] [segmentID=437929628050328911] [flushed=false] [dropped=false]
 157 [2022/12/09 14:58:10.615 +08:00] [INFO] [datanode/flow_graph_insert_buffer_node.go:397] ["insertBufferNode syncing BufferData"] [segmentID=437929628050328912] [flushed=false] [dropped=false] [auto=false] [position="channel_name:\"by-dev-rootcoord-dml_0_437929     628050128902v0\" msgID:\"\\010\\312\\004\\020\\321\\001\\030\\000 \\000\" msgGroup:\"by-dev-dataNode-72-by-dev-rootcoord-dml_0_437929628050128902v0\" timestamp:437929663652691969 "] [channel=by-dev-rootcoord-dml_0_437929628050128902v0]
 158 [2022/12/09 14:58:10.615 +08:00] [INFO] [datanode/flow_graph_insert_buffer_node.go:397] ["insertBufferNode syncing BufferData"] [segmentID=437929628050328911] [flushed=false] [dropped=false] [auto=false] [position="channel_name:\"by-dev-rootcoord-dml_1_437929     628050128902v1\" msgID:\"\\010\\311\\004\\020\\321\\001\\030\\000 \\000\" msgGroup:\"by-dev-dataNode-72-by-dev-rootcoord-dml_1_437929628050128902v1\" timestamp:437929663652691969 "] [channel=by-dev-rootcoord-dml_1_437929628050128902v1]
 159 fatal error: unexpected signal during runtime execution                                                                 
 160 [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7faacc0be9c9]                                            
 161                                                                                                                         
 162 runtime stack:                                                                                                          
 163 runtime.throw({0x3751ac9?, 0x7faacda984ee?})                                                                            
 164     /snap/go/current/src/runtime/panic.go:1047 +0x5d fp=0x7faa39bea3e0 sp=0x7faa39bea3b0 pc=0x12316dd                   
 165 runtime.sigpanic()                                                                                                      
 166     /snap/go/current/src/runtime/signal_unix.go:819 +0x369 fp=0x7faa39bea430 sp=0x7faa39bea3e0 pc=0x12488c9             
 167                                                                                                                         
 168 goroutine 494 [syscall]:                                                                                                
 169 runtime.cgocall(0x2d21c80, 0xc0012b6f68)                                                                                
 170     /snap/go/current/src/runtime/cgocall.go:158 +0x5c fp=0xc0012b6f40 sp=0xc0012b6f08 pc=0x11fb1bc                      
 171 github.com/milvus-io/milvus/internal/storage._Cfunc_ReleasePayloadWriter(0x7faa38e36000)                                
 172     _cgo_gotypes.go:558 +0x45 fp=0xc0012b6f68 sp=0xc0012b6f40 pc=0x24a55e5                                              
 173 github.com/milvus-io/milvus/internal/storage.(*PayloadWriter).ReleasePayloadWriter.func1(0x503a070?)                    
 174     /home/yangxuan/Github/milvus/internal/storage/payload.go:356 +0x3a fp=0xc0012b6fa0 sp=0xc0012b6f68 pc=0x24a72ba     
 175 github.com/milvus-io/milvus/internal/storage.(*PayloadWriter).ReleasePayloadWriter(0x33aca40?)                          
 176     /home/yangxuan/Github/milvus/internal/storage/payload.go:356 +0x19 fp=0xc0012b6fb8 sp=0xc0012b6fa0 pc=0x24a7259     
 177 github.com/milvus-io/milvus/internal/storage.(*baseEventWriter).Close(...)                                              
 178     /home/yangxuan/Github/milvus/internal/storage/event_writer.go:162                                                   
 179 github.com/milvus-io/milvus/internal/storage.(*InsertCodec).Serialize(0xc0011da2d8, 0xc0012b7448?, 0x64?, 0xc001784ec0) 
 180     /home/yangxuan/Github/milvus/internal/storage/data_codec.go:429 +0x1270 fp=0xc0012b71e0 sp=0xc0012b6fb8 pc=0x2482270
 181 github.com/milvus-io/milvus/internal/datanode.(*rendezvousFlushManager).flushBufferData(0xc000b2e0b0, 0xc0017a3000, 0x613d6ad2c8f0d50, 0x20?, 0x4f?, 0xc0012b7868?)
 182     /home/yangxuan/Github/milvus/internal/datanode/flush_manager.go:367 +0x2dc fp=0xc0012b7688 sp=0xc0012b71e0 pc=0x273373c
 183 github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Sync.func1()                                          
 184     /home/yangxuan/Github/milvus/internal/datanode/flow_graph_insert_buffer_node.go:408 +0x63 fp=0xc0012b7760 sp=0xc0012b7688 pc=0x272c203
 185 github.com/milvus-io/milvus/internal/util/retry.Do({0x3b10b70, 0xc0019cee40}, 0xc0012b79d8, {0xc0012b7980, 0x1, 0x0?})  
 186     /home/yangxuan/Github/milvus/internal/util/retry/retry.go:37 +0x102 fp=0xc0012b78f8 sp=0xc0012b7760 pc=0x1e205a2    
 187 github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Sync(0xc00041c7e0, 0xc001b0a0e8?, {0xc001b0a0e8?, 0xc001b10c60?, 0xc001b10c00?}, 0xc001b10c60)
 188     /home/yangxuan/Github/milvus/internal/datanode/flow_graph_insert_buffer_node.go:407 +0x729 fp=0xc0012b7c30 sp=0xc0012b78f8 pc=0x272b949
 189 github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Operate(0xc00041c7e0, {0xc001b084c0?, 0x43?, 0x37c8d98?})
 190     /home/yangxuan/Github/milvus/internal/datanode/flow_graph_insert_buffer_node.go:170 +0x6e5 fp=0xc0012b7e90 sp=0xc0012b7c30 pc=0x2728b85
 191 github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work(0xc000af9400)                                       
 192     /home/yangxuan/Github/milvus/internal/util/flowgraph/node.go:127 +0x2b8 fp=0xc0012b7fc8 sp=0xc0012b7e90 pc=0x26ef0d8
 193 github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start.func1()                                            
 194     /home/yangxuan/Github/milvus/internal/util/flowgraph/node.go:70 +0x26 fp=0xc0012b7fe0 sp=0xc0012b7fc8 pc=0x26eeb06  
 195 runtime.goexit()                                                                                                        
 196     /snap/go/current/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0012b7fe8 sp=0xc0012b7fe0 pc=0x12676c1                     
 197 created by github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start                                         
 198     /home/yangxuan/Github/milvus/internal/util/flowgraph/node.go:70 +0x79                                               

```

**Comment by yah01** [comment]
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-21185/13/pipeline/107/
After adding logs:
![image](https://user-images.githubusercontent.com/12216890/207523589-0d6b99c7-7f7a-4bf3-b1c8-8b5746a3f346.png)
No double close and this address is actually correct.
Thanks to @longjiquan, I found this panic is not caused by `delete p`, but `arrow::default_memory_pool()->ReleaseUnused();`

![image](https://user-images.githubusercontent.com/12216890/207523867-061a1389-4a96-46ab-958f-34e2c69e6684.png)
Then I found that every time this panic occurs, there are always multiple goroutine call `ReleasePayloadWriter` (different segments), It should be a problem that `arrow::default_memory_pool()->ReleaseUnused()` is not thread safe

**Comment by longjiquan** [comment]
The root cause is that we mix-use the glibc and jemalloc, already fixed. Feel free to reopen this if the issue is reproduced again.

/close
