### ISSUE TITLE
[Bug]: standalone panic index out of range when searching with expr `float in [1.0]`

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#21118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20221208-6709ccf6
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): go 2.2.0
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. Create collection and insert data
2. Create hnsw index and load collection
3. Search with expr `float in [1.0]`
standalone pod panic crash
```
Defaulted container "standalone" out of: standalone, config (init)
[2022/12/10 10:47:18.294 +00:00] [DEBUG] [querynode/segment.go:335] ["start do search on segment"] [msgID=437955916757204995] [segmentID=437955886529056100] [segmentType=3] [loadIndex=true]
[2022/12/10 10:47:18.294 +00:00] [DEBUG] [querynode/segment.go:348] ["do search on segment done"] [msgID=437955916757204995] [segmentID=437955886529056101] [segmentType=3] [loadIndex=true]
[2022/12/10 10:47:18.294 +00:00] [DEBUG] [querynode/validate.go:115] ["read target partitions"] [traceID=77dbad73173b8c58] [collectionID=437955886528856088] [partitionIDs="[437955886528856089]"]
[2022/12/10 10:47:18.294 +00:00] [DEBUG] [querynode/validate.go:131] ["validateOnStreamReplica getSegmentIDsByVChannel"] [traceID=77dbad73173b8c58] [collectionID=437955886528856088] [vChannel=by-dev-rootcoord-dml_1_437955886528856088v1] [partitionIDs="[437955886528856089]"] [segmentIDs="[]"] []
[2022/12/10 10:47:18.294 +00:00] [DEBUG] [querynode/impl.go:864] ["timerecorder : record elapsed duration"] [traceID=77dbad73173b8c58] [msg="do search done, msgID = 437955916757204995, fromSharedLeader = true, vChannel = by-dev-rootcoord-dml_1_437955886528856088v1, segmentIDs = [437955886529056101]"] [duration=149.038507ms]
[2022/12/10 10:47:18.294 +00:00] [DEBUG] [querynode/result.go:86] ["shard leader get valid search results"] [traceID=77dbad73173b8c58] [numbers=1]
[2022/12/10 10:47:18.294 +00:00] [DEBUG] [querynode/result.go:89] [reduceSearchResultData] [traceID=77dbad73173b8c58] ["result No."=0] [nq=5] [topk=10]
[2022/12/10 10:47:18.294 +00:00] [DEBUG] [querynode/result.go:181] ["skip duplicated search result"] [traceID=77dbad73173b8c58] [count=0]
[2022/12/10 10:47:18.294 +00:00] [DEBUG] [querynode/impl.go:924] ["timerecorder : record elapsed duration"] [traceID=77dbad73173b8c58] [msg="start reduce search result, msgID = 437955916757204995, fromSharedLeader = false, vChannel = by-dev-rootcoord-dml_1_437955886528856088v1, segmentIDs = []"] [duration=149.285997ms]
[2022/12/10 10:47:18.294 +00:00] [DEBUG] [querynode/segment.go:348] ["do search on segment done"] [msgID=437955916757204995] [segmentID=437955886529056100] [segmentType=3] [loadIndex=true]
[2022/12/10 10:47:18.294 +00:00] [DEBUG] [querynode/result.go:86] ["shard leader get valid search results"] [traceID=77dbad73173b8c58] [numbers=0]
[2022/12/10 10:47:18.295 +00:00] [DEBUG] [querynode/impl.go:934] ["timerecorder : record elapsed duration"] [traceID=77dbad73173b8c58] [msg="do search done, msgID = 437955916757204995, fromSharedLeader = false, vChannel = by-dev-rootcoord-dml_1_437955886528856088v1, segmentIDs = []"] [duration=149.376481ms]
[2022/12/10 10:47:18.295 +00:00] [DEBUG] [querynode/impl.go:864] ["timerecorder : record elapsed duration"] [traceID=77dbad73173b8c58] [msg="do search done, msgID = 437955916757204995, fromSharedLeader = true, vChannel = by-dev-rootcoord-dml_0_437955886528856088v0, segmentIDs = [437955886529056100]"] [duration=149.21849ms]
[2022/12/10 10:47:18.295 +00:00] [DEBUG] [querynode/result.go:86] ["shard leader get valid search results"] [traceID=77dbad73173b8c58] [numbers=1]
[2022/12/10 10:47:18.295 +00:00] [DEBUG] [querynode/result.go:89] [reduceSearchResultData] [traceID=77dbad73173b8c58] ["result No."=0] [nq=5] [topk=10]
panic: runtime error: index out of range [-1]

goroutine 6357 [running]:
github.com/milvus-io/milvus/internal/querynode.selectSearchResultData({0xc0034ceff8, 0x1, 0x13e2d9c?}, {0xc001c65f80, 0x1, 0xc003381b00?}, {0xc003670d78, 0x1, 0x0?}, 0x0)
	/go/src/github.com/milvus-io/milvus/internal/querynode/result.go:205 +0x2bf
github.com/milvus-io/milvus/internal/querynode.reduceSearchResultData({0x39f3510, 0xc001a8a400}, {0xc0034ceff8?, 0x1, 0x1}, 0x5, 0xa)
	/go/src/github.com/milvus-io/milvus/internal/querynode/result.go:152 +0x6f0
github.com/milvus-io/milvus/internal/querynode.reduceSearchResults({0x39f3510, 0xc001a8a400}, {0xc0034cefd0?, 0xc0004aaa00?, 0x4?}, 0x4?, 0xc003e4b100?, {0xc00045bc28, 0x2})
	/go/src/github.com/milvus-io/milvus/internal/querynode/result.go:95 +0x5ef
github.com/milvus-io/milvus/internal/querynode.(*QueryNode).Search(0xc00054a0f0, {0x39f3510, 0xc001a8a400}, 0xc002442ae0)
	/go/src/github.com/milvus-io/milvus/internal/querynode/impl.go:780 +0x850
github.com/milvus-io/milvus/internal/querynode.(*ShardCluster).Search.func2()
	/go/src/github.com/milvus-io/milvus/internal/querynode/shard_cluster.go:976 +0xbd
created by github.com/milvus-io/milvus/internal/querynode.(*ShardCluster).Search
	/go/src/github.com/milvus-io/milvus/internal/querynode/shard_cluster.go:974 +0x1016
```

### Steps To Reproduce

```markdown
func TestSearchInvalidExpr(t *testing.T)  {
	ctx := createContext(t, time.Second*common.DefaultTimeout*2)
	// connect
	mc := createMilvusClient(ctx, t)

	// create collection with data
	collName, _ := createCollectionWithDataIndex(ctx, t, mc, false, true)

	// load collection
	errLoad := mc.LoadCollection(ctx, collName, false)
	common.CheckErr(t, errLoad, true)

	sp, _ := entity.NewIndexHNSWSearchParam(74)
	
	_, errSearchEmpty := mc.Search (
		ctx, collName,
		[]string{},
		"float in [1.0]",
		[]string{common.DefaultIntFieldName},
		common.GenSearchVectors(common.DefaultNq, common.DefaultDim, entity.FieldTypeFloatVector),
		common.DefaultFloatVecFieldName,
		entity.L2,
		common.DefaultTopK,
		sp,
	)
	common.CheckErr(t, errSearchEmpty, false, "ignore")
}
```
```


### Milvus Log

_No response_

### Anything else?

_No response_

**Comment by yanliang567** [comment]
@congqixia any updates?

**Comment by congqixia** [comment]
@yanliang567 I think knowhere has fixed this bug in 1.3.6. Could you please double check? @liliu-z

**Comment by liliu-z** [comment]
Similar to https://github.com/milvus-io/milvus/issues/21138 which is get fixed.

/unassign

**Comment by ThreadDao** [comment]
Fixed!
Verified on `master-20230208-137e620a`
