### ISSUE TITLE
[Bug]: [benchmark][cluster] The client throws an error: "collection 438004644173578244 has not been loaded to memory or load failed"

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#21172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20221212-df8c67fe
- Deployment mode(standalone or cluster):cluster 
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.1.dev4
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server-instance
fouram-tag-no-clean-sfv94-1
server-configmap
server-cluster-8c64m-querynode2-kafka
client-configmap
client-random-locust-search-filter-hnsw-100m-ddl-replica2-36h-wh

argo task: fouram-tag-no-clean-sfv94

server
```
fouram-tag-no-clean-sfv94-1-etcd-0                                1/1     Running     0              111s    10.104.6.151   4am-node13   <none>           <none>
fouram-tag-no-clean-sfv94-1-etcd-1                                1/1     Running     0              111s    10.104.1.187   4am-node10   <none>           <none>
fouram-tag-no-clean-sfv94-1-etcd-2                                1/1     Running     0              111s    10.104.9.54    4am-node14   <none>           <none>
fouram-tag-no-clean-sfv94-1-kafka-0                               2/2     Running     0              111s    10.104.6.152   4am-node13   <none>           <none>
fouram-tag-no-clean-sfv94-1-kafka-1                               2/2     Running     0              111s    10.104.1.190   4am-node10   <none>           <none>
fouram-tag-no-clean-sfv94-1-kafka-2                               2/2     Running     0              111s    10.104.9.57    4am-node14   <none>           <none>
fouram-tag-no-clean-sfv94-1-kafka-exporter-6f9f566bc6-xjvlr       1/1     Running     4 (64s ago)    111s    10.104.6.147   4am-node13   <none>           <none>
fouram-tag-no-clean-sfv94-1-milvus-datacoord-9f6c46c74-64hjj      1/1     Running     0              111s    10.104.5.115   4am-node12   <none>           <none>
fouram-tag-no-clean-sfv94-1-milvus-datanode-844b4689cc-v7w5k      1/1     Running     0              111s    10.104.5.117   4am-node12   <none>           <none>
fouram-tag-no-clean-sfv94-1-milvus-indexcoord-5c9f787bb9-jm8hg    1/1     Running     0              111s    10.104.9.51    4am-node14   <none>           <none>
fouram-tag-no-clean-sfv94-1-milvus-indexnode-65ccfc5bfd-qgdg6     1/1     Running     0              111s    10.104.1.184   4am-node10   <none>           <none>
fouram-tag-no-clean-sfv94-1-milvus-proxy-75bc4f4fd7-hxd7z         1/1     Running     0              111s    10.104.5.114   4am-node12   <none>           <none>
fouram-tag-no-clean-sfv94-1-milvus-querycoord-6687f55d78-lxb8d    1/1     Running     0              111s    10.104.1.183   4am-node10   <none>           <none>
fouram-tag-no-clean-sfv94-1-milvus-querynode-7cb45cc8c6-jbxd8     1/1     Running     0              111s    10.104.5.116   4am-node12   <none>           <none>
fouram-tag-no-clean-sfv94-1-milvus-querynode-7cb45cc8c6-x6swg     1/1     Running     0              111s    10.104.6.146   4am-node13   <none>           <none>
fouram-tag-no-clean-sfv94-1-milvus-rootcoord-85bc6cff74-fmdtr     1/1     Running     0              111s    10.104.5.113   4am-node12   <none>           <none>
fouram-tag-no-clean-sfv94-1-minio-0                               1/1     Running     0              111s    10.104.6.150   4am-node13   <none>           <none>
fouram-tag-no-clean-sfv94-1-minio-1                               1/1     Running     0              111s    10.104.1.188   4am-node10   <none>           <none>
fouram-tag-no-clean-sfv94-1-minio-2                               1/1     Running     0              111s    10.104.9.55    4am-node14   <none>           <none>
fouram-tag-no-clean-sfv94-1-minio-3                               1/1     Running     0              111s    10.104.4.222   4am-node11   <none>           <none>
fouram-tag-no-clean-sfv94-1-zookeeper-0                           1/1     Running     0              111s    10.104.1.189   4am-node10   <none>           <none>
fouram-tag-no-clean-sfv94-1-zookeeper-1                           1/1     Running     0              111s    10.104.9.56    4am-node14   <none>           <none>
fouram-tag-no-clean-sfv94-1-zookeeper-2                           1/1     Running     0              111s    10.104.4.223   4am-node11   <none>           <none>
```

client log:
```
[2022-12-12 17:44:32,180] [   DEBUG] - Row count: 100000000 in collection: <sift_100m_128_l2> (milvus_benchmark.client:520)
[2022-12-12 17:44:32,180] [    INFO] - 100000000 (milvus_benchmark.runners.locust:458)
[2022-12-12 17:44:32,180] [    INFO] - Start load collection (milvus_benchmark.runners.locust:459)
[2022-12-12 17:44:32,180] [   DEBUG] - params of load collection: {'replica_number': 2} (milvus_benchmark.client:591)
[2022-12-12 17:57:02,541] [   ERROR] - RPC error: [get_loading_progress], <MilvusException: (code=1, message=collection 438004644173578244 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-12-12 17:57:02.538543', 'RPC error': '2022-12-12 17:57:02.541539'}> (pymilvus.decorators:108)
[2022-12-12 17:57:02,542] [   ERROR] - RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=collection 438004644173578244 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-12-12 17:44:32.272682', 'RPC error': '2022-12-12 17:57:02.542185'}> (pymilvus.decorators:108)
[2022-12-12 17:57:02,542] [   ERROR] - RPC error: [load_collection], <MilvusException: (code=1, message=collection 438004644173578244 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-12-12 17:44:32.180997', 'RPC error': '2022-12-12 17:57:02.542338'}> (pymilvus.decorators:108)
[2022-12-12 17:57:02,542] [   ERROR] - <MilvusException: (code=1, message=collection 438004644173578244 has not been loaded to memory or load failed)> (milvus_benchmark.main:118)
[2022-12-12 17:57:02,547] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 87, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/locust.py", line 461, in prepare
    self.milvus.load_collection(replica_number=replica_number)
  File "/src/milvus_benchmark/client.py", line 53, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 592, in load_collection
    return self._milvus.load_collection(collection_name, **params)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/stub.py", line 193, in load_collection
    return handler.load_collection(collection_name, replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 659, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 677, in wait_for_loading_collection
    progress = self.get_loading_progress(collection_name, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 738, in get_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection 438004644173578244 has not been loaded to memory or load failed)>
 (milvus_benchmark.main:119)
```

### Steps To Reproduce

```markdown
1.create a collection
2.build index of hnsw
3.insert 100m data
4.load collection   ===>  load failed
```

### Anything else?

client-random-locust-search-filter-hnsw-100m-ddl-replica2-36h-wh
```
    locust_random_performance:
      collections:
        -
          collection_name: sift_100m_128_l2
          other_fields: float1
          ni_per: 50000
          build_index: true
          index_type: hnsw
          index_param:
            M: 8
            efConstruction: 200
          load_param:
            replica_number: 2
          task:
            types:
              -
                type: query
                weight: 20
                params:
                  top_k: 10
                  nq: 10
                  search_param:
                    nprobe: 16
                  filters:
                    -
                      range: "{'range': {'float1': {'GT': -1.0, 'LT': collection_size * 0.5}}}"
              -
                type: load
                weight: 1
                params:
                  replica_number: 2
              -
                type: get
                weight: 10
                params:
                  ids_length: 10
              -
                type: scene_test
                weight: 2
            connection_num: 1
            clients_num: 20
            spawn_rate: 2
            during_time: 36h
```

**Comment by yah01** [comment]
![image](https://user-images.githubusercontent.com/12216890/207219067-5f0e1267-f737-411a-a68a-83592a998c5a.png)
![image](https://user-images.githubusercontent.com/12216890/207219103-a41eb124-9f8d-49d6-a27c-2f60fd879753.png)

QueryNode reports no enough memory to load

**Comment by yah01** [comment]
![image](https://user-images.githubusercontent.com/12216890/207219713-013bf465-fd9a-4bb6-ba2b-07314af111b1.png)
![image](https://user-images.githubusercontent.com/12216890/207219815-6a3c57c6-9bc2-4d64-80d3-ffef242dfb9b.png)
The dataset need 107GB memory to load, the cluster has total 64*2=128GB memory, but tried to load with 2 replicas, which requires 214GB memory

**Comment by elstic** [comment]
Sorry, this is a config item error
