### ISSUE TITLE
[Bug]: ReleasePayloadWriter panic

### ISSUE THREAD

**Issue by jaime0815** [milvus-io/milvus#21177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
ev-rootcoord-dml_9_438017262516437025v1]
2022-12-13T11:48:43.739609233+08:00 stdout F [2022/12/13 03:48:43.739 +00:00] [INFO] [datanode/flow_graph_insert_buffer_node.go:272] ["segment buffer status"] [no.=0] [segmentID=438017262516637365] [channel=by-dev-rootcoord-dml_8_438017262516437025v0] [size=1503] [limit=21077]
2022-12-13T11:48:43.739619257+08:00 stdout F [2022/12/13 03:48:43.739 +00:00] [DEBUG] [datanode/flow_graph_insert_buffer_node.go:342] ["sync segments"] [vChannel=by-dev-rootcoord-dml_8_438017262516437025v0] [segIDs="[438017262516637365]"]
2022-12-13T11:48:43.739626381+08:00 stdout F [2022/12/13 03:48:43.739 +00:00] [INFO] [datanode/flow_graph_insert_buffer_node.go:351] ["merging sync task, updating flushed flag"] [segmentID=438017262516637365] [flushed=false] [dropped=false]
2022-12-13T11:48:43.739644447+08:00 stdout F [2022/12/13 03:48:43.739 +00:00] [INFO] [datanode/flow_graph_insert_buffer_node.go:397] ["insertBufferNode syncing BufferData"] [segmentID=438017262516637365] [flushed=false] [dropped=false] [auto=false] [position="channel_name:\"by-dev-rootcoord-dml_8_438017262516437025v0\" msgID:\"\\237\\000\\240'a&\\024\\006\" msgGroup:\"by-dev-dataNode-1-by-dev-rootcoord-dml_8_438017262516437025v0\" timestamp:438017280859701271 "] [channel=by-dev-rootcoord-dml_8_438017262516437025v0]
2022-12-13T11:48:43.740866549+08:00 stderr F fatal error: unexpected signal during runtime execution
2022-12-13T11:48:43.743040041+08:00 stderr F [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7f6225089f89]
2022-12-13T11:48:43.743052501+08:00 stderr F 
2022-12-13T11:48:43.743055623+08:00 stderr F runtime stack:
2022-12-13T11:48:43.74305896+08:00 stderr F runtime.throw({0x364d646?, 0x7f62251dabe0?})
2022-12-13T11:48:43.74306182+08:00 stderr F 	/usr/local/go/src/runtime/panic.go:992 +0x71
2022-12-13T11:48:43.743065058+08:00 stderr F runtime.sigpanic()
2022-12-13T11:48:43.743068877+08:00 stderr F 	/usr/local/go/src/runtime/signal_unix.go:802 +0x3a9
2022-12-13T11:48:43.743071448+08:00 stderr F 
2022-12-13T11:48:43.74307476+08:00 stderr F goroutine 5846 [syscall]:
2022-12-13T11:48:43.743077972+08:00 stderr F runtime.cgocall(0x2cb07a0, 0xc009910f68)
2022-12-13T11:48:43.743081321+08:00 stderr F 	/usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc009910f40 sp=0xc009910f08 pc=0x11a3b7c
2022-12-13T11:48:43.743084724+08:00 stderr F github.com/milvus-io/milvus/internal/storage._Cfunc_ReleasePayloadWriter(0x7f5fd7c1e000)
2022-12-13T11:48:43.74308755+08:00 stderr F 	_cgo_gotypes.go:542 +0x45 fp=0xc009910f68 sp=0xc009910f40 pc=0x2432c05
2022-12-13T11:48:43.743091138+08:00 stderr F github.com/milvus-io/milvus/internal/storage.(*PayloadWriter).ReleasePayloadWriter.func1(0x4eb6388?)
2022-12-13T11:48:43.743098933+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/storage/payload.go:356 +0x3a fp=0xc009910fa0 sp=0xc009910f68 pc=0x24348da
2022-12-13T11:48:43.743101922+08:00 stderr F github.com/milvus-io/milvus/internal/storage.(*PayloadWriter).ReleasePayloadWriter(0x32aa560?)
2022-12-13T11:48:43.743105622+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/storage/payload.go:356 +0x19 fp=0xc009910fb8 sp=0xc009910fa0 pc=0x2434879
2022-12-13T11:48:43.743114056+08:00 stderr F github.com/milvus-io/milvus/internal/storage.(*baseEventWriter).Close(...)
2022-12-13T11:48:43.7431215+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/storage/event_writer.go:162
2022-12-13T11:48:43.743124279+08:00 stderr F github.com/milvus-io/milvus/internal/storage.(*InsertCodec).Serialize(0xc005108250, 0xc009911448?, 0x1?, 0xc007f2a640)
2022-12-13T11:48:43.743127002+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/storage/data_codec.go:429 +0x1271 fp=0xc0099111e0 sp=0xc009910fb8 pc=0x240fb51
2022-12-13T11:48:43.743130002+08:00 stderr F github.com/milvus-io/milvus/internal/datanode.(*rendezvousFlushManager).flushBufferData(0xc0086a6210, 0xc008d76e80, 0x614266129cb0eb5, 0xe0?, 0x9d?, 0xc009911868?)
2022-12-13T11:48:43.743133626+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_manager.go:367 +0x2dc fp=0xc009911688 sp=0xc0099111e0 pc=0x26b5ddc
2022-12-13T11:48:43.74313634+08:00 stderr F github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Sync.func1()
2022-12-13T11:48:43.743139397+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:408 +0x63 fp=0xc009911760 sp=0xc009911688 pc=0x26ae943
2022-12-13T11:48:43.743144644+08:00 stderr F github.com/milvus-io/milvus/internal/util/retry.Do({0x3a025f0, 0xc007bf9d40}, 0xc0099119d8, {0xc009911980, 0x1, 0x0?})
2022-12-13T11:48:43.743151737+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:37 +0x103 fp=0xc0099118f8 sp=0xc009911760 pc=0x1dadee3
2022-12-13T11:48:43.743163458+08:00 stderr F github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Sync(0xc00018efc0, 0xc004881058?, {0xc004881058?, 0xc008fae0c0?, 0xc008fae060?}, 0xc008fae0c0)
2022-12-13T11:48:43.743180584+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:407 +0x729 fp=0xc009911c30 sp=0xc0099118f8 pc=0x26ae0a9
2022-12-13T11:48:43.743187345+08:00 stderr F github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Operate(0xc00018efc0, {0xc0095bd950?, 0x43?, 0x36c41a0?})
2022-12-13T11:48:43.74319225+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:170 +0x6b7 fp=0xc009911e90 sp=0xc009911c30 pc=0x26ab2f7
2022-12-13T11:48:43.743199005+08:00 stderr F github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work(0xc0016a3950)
2022-12-13T11:48:43.743207109+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:127 +0x2b8 fp=0xc009911fc8 sp=0xc009911e90 pc=0x24f0578
2022-12-13T11:48:43.743213951+08:00 stderr F github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start.func1()
2022-12-13T11:48:43.743221789+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:70 +0x26 fp=0xc009911fe0 sp=0xc009911fc8 pc=0x24effa6
2022-12-13T11:48:43.743230741+08:00 stderr F runtime.goexit()
2022-12-13T11:48:43.743242546+08:00 stderr F 	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc009911fe8 sp=0xc009911fe0 pc=0x120ce61
2022-12-13T11:48:43.743247814+08:00 stderr F created by github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start
2022-12-13T11:48:43.743252471+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:70 +0x79
2022-12-13T11:48:43.743255218+08:00 stderr F 
```

[ci.var.log.containers.ms-21006-12-pr-milvus-standalone-6b79d5fd67-74rmq_milvus-ci_standalone-bd47cf0e56b5e0f53f43dccf9ee5574017e5bc278d097f7712190888420e6139.log](https://github.com/milvus-io/milvus/files/10215043/ci.var.log.containers.ms-21006-12-pr-milvus-standalone-6b79d5fd67-74rmq_milvus-ci_standalone-bd47cf0e56b5e0f53f43dccf9ee5574017e5bc278d097f7712190888420e6139.log)

**Comment by jaime0815** [comment]
related to #21057
