### ISSUE TITLE
[Bug]: Create collection failed with error `message=InvalidateCollectionMetaCache failed` after proxy pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#21181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20221213-d553b510
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.3.0.dev21
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2022-12-13 06:49:36 - ERROR - pymilvus.decorators]: RPC error: [create_collection], <MilvusException: (code=1, message=InvalidateCollectionMetaCache failed, proxyID = 17, err = err: failed to connect 10.244.0.47:19529, reason: context deadline exceeded
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:304 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall
/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/client/client.go:1[35](https://github.com/zhuwenxing/milvus/actions/runs/3682859911/jobs/6230875006#step:15:36) github.com/milvus-io/milvus/internal/distributed/proxy/client.(*Client).InvalidateCollectionMetaCache
/go/src/github.com/milvus-io/milvus/internal/rootcoord/proxy_client_manager.go:139 github.com/milvus-io/milvus/internal/rootcoord.(*proxyClientManager).InvalidateCollectionMetaCache.func1
/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 golang.org/x/sync/errgroup.(*Group).Go.func1
/usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit
)>, <Time:{'RPC start': '2022-12-13 06:49:17.683246', 'RPC error': '2022-12-13 06:49:36.584684'}> (decorators.py:108)
[2022-12-13 06:49:36 - ERROR - ci_test]: Traceback (most recent call last):
  File "/home/runner/work/milvus/milvus/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/home/runner/work/milvus/milvus/tests/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 120, in __init__
    conn.create_collection(self._name, schema, shards_num=self._shards_num, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 210, in create_collection
    raise MilvusException(status.error_code, status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=InvalidateCollectionMetaCache failed, proxyID = 17, err = err: failed to connect 10.244.0.47:19529, reason: context deadline exceeded
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:304 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall
/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/client/client.go:135 github.com/milvus-io/milvus/internal/distributed/proxy/client.(*Client).InvalidateCollectionMetaCache
/go/src/github.com/milvus-io/milvus/internal/rootcoord/proxy_client_manager.go:139 github.com/milvus-io/milvus/internal/rootcoord.(*proxyClientManager).InvalidateCollectionMetaCache.func1
/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-0[36](https://github.com/zhuwenxing/milvus/actions/runs/3682859911/jobs/6230875006#step:15:37)812b2e83c/errgroup/errgroup.go:57 golang.org/x/sync/errgroup.(*Group).Go.func1
/usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit
)>
 (api_request.py:[39](https://github.com/zhuwenxing/milvus/actions/runs/3682859911/jobs/6230875006#step:15:40))
[2022-12-13 06:49:36 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=InvalidateCollectionMetaCache failed, proxyID = 17, err = err: failed to connect 10.244.0.47:19529, reason: context deadline exceeded
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTr...... (api_request.py:[40](https://github.com/zhuwenxing/milvus/actions/runs/3682859911/jobs/6230875006#step:15:41))
FAILED
```

### Steps To Reproduce

```markdown
see https://github.com/zhuwenxing/milvus/actions/runs/3682859911/jobs/6230875006
```

### Milvus Log

failed job: https://github.com/zhuwenxing/milvus/actions/runs/3682859911/jobs/6230875006
log:
[logs-proxy (7).zip](https://github.com/milvus-io/milvus/files/10215426/logs-proxy.7.zip)

### Anything else?

It is strange that the connection error is not reported at the time of connection but at the time of creation of the collection

**Comment by zhuwenxing** [comment]
It also reproduced in Jenkins

chaos type: pod-kill image tag: 2.2.0-20221213-437e4430 target pod: proxy
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-for-release-cron/detail/chaos-test-for-release-cron/414/pipeline
log:

[artifacts-proxy-pod-kill-414-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10225501/artifacts-proxy-pod-kill-414-server-logs.tar.gz)

[artifacts-proxy-pod-kill-414-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10225502/artifacts-proxy-pod-kill-414-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
chaos type: pod-kill image tag: master-20221222-98088e3b target pod: proxy
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/721/pipeline
log:

[artifacts-proxy-pod-kill-721-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10291689/artifacts-proxy-pod-kill-721-server-logs.tar.gz)
[artifacts-proxy-pod-kill-721-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10291690/artifacts-proxy-pod-kill-721-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
@jiaoew1991 
any progress? It was reproduced stably!

**Comment by zhuwenxing** [comment]
chaos type: pod-kill image tag: master-20230129-66027790 target pod: proxy
failed job:https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/1640/pipeline
log:
[artifacts-proxy-pod-kill-1640-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10541990/artifacts-proxy-pod-kill-1640-server-logs.tar.gz)
[artifacts-proxy-pod-kill-1640-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10541992/artifacts-proxy-pod-kill-1640-pytest-logs.tar.gz)


```

[2023-01-29T20:48:23.003Z] [2023-01-29 20:48:20 - ERROR - pymilvus.decorators]: RPC error: [create_collection], <MilvusException: (code=1, message=InvalidateCollectionMetaCache failed, proxyID = 13, err = err: failed to connect 10.102.10.127:19529, reason: context deadline exceeded

[2023-01-29T20:48:23.003Z] , /go/src/github.com/milvus-io/milvus/internal/tracer/stack_trace.go:51 github.com/milvus-io/milvus/internal/tracer.StackTrace

[2023-01-29T20:48:23.003Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:310 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall

[2023-01-29T20:48:23.003Z] /go/src/github.com/milvus-io/milvus/internal/distributed/proxy/client/client.go:135 github.com/milvus-io/milvus/internal/distributed/proxy/client.(*Client).InvalidateCollectionMetaCache

[2023-01-29T20:48:23.003Z] /go/src/github.com/milvus-io/milvus/internal/rootcoord/proxy_client_manager.go:154 github.com/milvus-io/milvus/internal/rootcoord.(*proxyClientManager).InvalidateCollectionMetaCache.func1

[2023-01-29T20:48:23.003Z] /go/pkg/mod/golang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4/errgroup/errgroup.go:75 golang.org/x/sync/errgroup.(*Group).Go.func1

[2023-01-29T20:48:23.003Z] /usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit

[2023-01-29T20:48:23.003Z] )>, <Time:{'RPC start': '2023-01-29 20:47:56.053838', 'RPC error': '2023-01-29 20:48:20.629500'}> (decorators.py:108)

[2023-01-29T20:48:23.003Z] [2023-01-29 20:48:20 - ERROR - ci_test]: Traceback (most recent call last):

[2023-01-29T20:48:23.003Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2023-01-29T20:48:23.003Z]     res = func(*args, **_kwargs)

[2023-01-29T20:48:23.003Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2023-01-29T20:48:23.003Z]     return func(*arg, **kwargs)

[2023-01-29T20:48:23.003Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 120, in __init__

[2023-01-29T20:48:23.003Z]     conn.create_collection(self._name, schema, shards_num=self._shards_num, **kwargs)

[2023-01-29T20:48:23.003Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-01-29T20:48:23.003Z]     raise e

[2023-01-29T20:48:23.003Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-01-29T20:48:23.003Z]     return func(*args, **kwargs)

[2023-01-29T20:48:23.003Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-01-29T20:48:23.003Z]     ret = func(self, *args, **kwargs)

[2023-01-29T20:48:23.003Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-01-29T20:48:23.003Z]     raise e

[2023-01-29T20:48:23.003Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-01-29T20:48:23.003Z]     return func(self, *args, **kwargs)

[2023-01-29T20:48:23.003Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 211, in create_collection

[2023-01-29T20:48:23.003Z]     raise MilvusException(status.error_code, status.reason)

[2023-01-29T20:48:23.003Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=InvalidateCollectionMetaCache failed, proxyID = 13, err = err: failed to connect 10.102.10.127:19529, reason: context deadline exceeded

[2023-01-29T20:48:23.003Z] , /go/src/github.com/milvus-io/milvus/internal/tracer/stack_trace.go:51 github.com/milvus-io/milvus/internal/tracer.StackTrace

[2023-01-29T20:48:23.003Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:310 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall

[2023-01-29T20:48:23.003Z] /go/src/github.com/milvus-io/milvus/internal/distributed/proxy/client/client.go:135 github.com/milvus-io/milvus/internal/distributed/proxy/client.(*Client).InvalidateCollectionMetaCache

[2023-01-29T20:48:23.003Z] /go/src/github.com/milvus-io/milvus/internal/rootcoord/proxy_client_manager.go:154 github.com/milvus-io/milvus/internal/rootcoord.(*proxyClientManager).InvalidateCollectionMetaCache.func1

[2023-01-29T20:48:23.003Z] /go/pkg/mod/golang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4/errgroup/errgroup.go:75 golang.org/x/sync/errgroup.(*Group).Go.func1

[2023-01-29T20:48:23.003Z] /usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit

[2023-01-29T20:48:23.003Z] )>

[2023-01-29T20:48:23.003Z]  (api_request.py:39)

[2023-01-29T20:48:23.003Z] [2023-01-29 20:48:20 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=InvalidateCollectionMetaCache failed, proxyID = 13, err = err: failed to connect 10.102.10.127:19529, reason: context deadline exceeded

[2023-01-29T20:48:23.003Z] , /go/src/github.com/milvus-io/milvus/internal/tracer/stack_trace.go:51 github.com/milvus-io/milvus/internal/tracer.StackTrace

[2023-01-29T20:48:23.003Z] /g...... (api_request.py:40)
```

**Comment by sunby** [comment]
please check it.
/assign @zhuwenxing 
/unassign

**Comment by zhuwenxing** [comment]
Verified and passed with `master-20230201-5d5a04d3`

**Comment by zhuwenxing** [comment]
It also happened in the 2.2.0 branch. Please check whether we need to cherry-pick the PR to the 2.2.0 branch!
@sunby 
chaos type: pod-kill image tag: 2.2.0-20230203-68156b3d target pod: proxy
failed job:https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-for-release-cron/detail/chaos-test-for-release-cron/1723/pipeline
log:
[artifacts-proxy-pod-kill-1723-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10637062/artifacts-proxy-pod-kill-1723-server-logs.tar.gz)
[artifacts-proxy-pod-kill-1723-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10637063/artifacts-proxy-pod-kill-1723-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
verified and passed with `2.2.0-20230206-1f0214d4`

**Comment by otteryan** [comment]
i  have met this proble using   milvus version:2.2.3 ,java sdk :2.2.3。Then i tried   with 2.2.0-20230206-1f0214d4,  this proble still occured。

**Comment by Phobia-Cosmos** [comment]
I am learning from the [Run Milvus using Python](https://milvus.io/docs/example_code.md) using the Milvus lite on my mac directly, and when I first run the code, it encounter the error below and then leave a collection in my DB.However, the second time I run it just few seconds after, everything went right but the collection it made in the first try remains.I don't know why it will the error occurs and I don't know why it returns normal.
```
=== start connecting to Milvus     ===

Does collection hello_milvus exist in Milvus: False

=== Create collection `hello_milvus` ===

RPC error: [create_collection], <MilvusException: (code=65535, message=InvalidateCollectionMetaCache failed, proxyID = 2, err = stack trace: /Users/jibin/Working/milvus-lite/milvus_binary/milvus/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace
/Users/jibin/Working/milvus-lite/milvus_binary/milvus/internal/util/grpcclient/client.go:515 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call
/Users/jibin/Working/milvus-lite/milvus_binary/milvus/internal/util/grpcclient/client.go:529 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall
/Users/jibin/Working/milvus-lite/milvus_binary/milvus/internal/distributed/proxy/client/client.go:76 github.com/milvus-io/milvus/internal/distributed/proxy/client.wrapGrpcCall[...]
/Users/jibin/Working/milvus-lite/milvus_binary/milvus/internal/distributed/proxy/client/client.go:109 github.com/milvus-io/milvus/internal/distributed/proxy/client.(*Client).InvalidateCollectionMetaCache
/Users/jibin/Working/milvus-lite/milvus_binary/milvus/internal/rootcoord/proxy_client_manager.go:157 github.com/milvus-io/milvus/internal/rootcoord.(*proxyClientManager).InvalidateCollectionMetaCache.func1
/Users/jibin/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 golang.org/x/sync/errgroup.(*Group).Go.func1
/opt/homebrew/Cellar/go/1.21.4/libexec/src/runtime/asm_arm64.s:1197 runtime.goexit: attempt #0: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match: attempt #1: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match: attempt #2: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match: attempt #3: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match: attempt #4: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match: attempt #5: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match: attempt #6: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match: attempt #7: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match: attempt #8: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match: attempt #9: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match)>, <Time:{'RPC start': '2024-01-16 19:27:20.388750', 'RPC error': '2024-01-16 19:28:33.203917'}>
Traceback (most recent call last):
  File "/Users/liuzihao/Desktop/Draft/milvus/hello_Milvus/hello_milvus.py", line 59, in <module>
    hello_milvus = Collection("hello_milvus", schema, consistency_level="Strong")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liuzihao/Desktop/Draft/milvus/milvus/lib/python3.11/site-packages/pymilvus/orm/collection.py", line 147, in __init__
    conn.create_collection(self._name, schema, **kwargs)
  File "/Users/liuzihao/Desktop/Draft/milvus/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 129, in handler
    raise e from e
  File "/Users/liuzihao/Desktop/Draft/milvus/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 125, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liuzihao/Desktop/Draft/milvus/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 164, in handler
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liuzihao/Desktop/Draft/milvus/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 104, in handler
    raise e from e
  File "/Users/liuzihao/Desktop/Draft/milvus/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 68, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liuzihao/Desktop/Draft/milvus/milvus/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 293, in create_collection
    check_status(status)
  File "/Users/liuzihao/Desktop/Draft/milvus/milvus/lib/python3.11/site-packages/pymilvus/client/utils.py", line 54, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=InvalidateCollectionMetaCache failed, proxyID = 2, err = stack trace: /Users/jibin/Working/milvus-lite/milvus_binary/milvus/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace
/Users/jibin/Working/milvus-lite/milvus_binary/milvus/internal/util/grpcclient/client.go:515 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call
/Users/jibin/Working/milvus-lite/milvus_binary/milvus/internal/util/grpcclient/client.go:529 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall
/Users/jibin/Working/milvus-lite/milvus_binary/milvus/internal/distributed/proxy/client/client.go:76 github.com/milvus-io/milvus/internal/distributed/proxy/client.wrapGrpcCall[...]
/Users/jibin/Working/milvus-lite/milvus_binary/milvus/internal/distributed/proxy/client/client.go:109 github.com/milvus-io/milvus/internal/distributed/proxy/client.(*Client).InvalidateCollectionMetaCache
/Users/jibin/Working/milvus-lite/milvus_binary/milvus/internal/rootcoord/proxy_client_manager.go:157 github.com/milvus-io/milvus/internal/rootcoord.(*proxyClientManager).InvalidateCollectionMetaCache.func1
/Users/jibin/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 golang.org/x/sync/errgroup.(*Group).Go.func1
/opt/homebrew/Cellar/go/1.21.4/libexec/src/runtime/asm_arm64.s:1197 runtime.goexit: attempt #0: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match: attempt #1: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match: attempt #2: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match: attempt #3: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match: attempt #4: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match: attempt #5: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match: attempt #6: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match: attempt #7: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match: attempt #8: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match: attempt #9: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match)>
```

**Comment by yanliang567** [comment]
we are trying to refactor the milvus lite, so it guess it is not up to date. could you please try to run the code against a milvus deployment, such as standalone. @Phobia-Cosmos feel free to file a new issue if you meet any issues.

**Comment by Phobia-Cosmos** [comment]
I don't know whether it's due to the CLI doc or something else, when i use milvus_cli to show database, below error occurs:
```
milvus_cli > show collection
RPC error: [has_collection], <ParamError: (code=1, message=`collection_name` value None is illegal)>, <Time:{'RPC start': '2024-01-17 10:19:57.434343', 'RPC error': '2024-01-17 10:19:57.434416'}>
Get collection detail error!Get collection error!<ParamError: (code=1, message=`collection_name` value None is illegal)>
```

And I wonder if there is any way like mysql or things alike, enabling me to use CLI tools directly check databases and data?
