### ISSUE TITLE
[Bug]: Proxy panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tiratano** [milvus-io/milvus#21201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.0
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: Intel(R) Xeon(R) Silver 4314 CPU @ 2.40GHz / 256GB
- GPU: None
- Others:
```

### Current Behavior

When I insert records with 300 threads simultaneously, the proxy server crashed and I see the error message attached below.

### Expected Behavior

No crash occurs

### Steps To Reproduce

```markdown
1. I have 5 physical servers and configured a helm override_values.yml file with dataNode.replicas=4, indexNode.replicas=4, queryNode.replicas=4
2. Create a collection with 4 shards, 2 replicas
3. Insert one record with 300 threads simultaneously
4. The milvus proxy pod crashed
```

### Milvus Log

[2022/12/12 00:01:50.396 +00:00] [ERROR] [proxy/channels_mgr.go:104] ["failed to describe collection"] [error_code=UnexpectedError] [reason="code: CollectionNotExists, reason: can't find collection: 0"] [stack="github.com/milvus-io/milvus/internal/proxy.getDmlChannelsFunc.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/channels_mgr.go:104\ngithub.com/milvus-io/milvus/internal/proxy.(*singleTypeChannelsMgr).getPChans\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/channels_mgr.go:145\ngithub.com/milvus-io/milvus/internal/proxy.(*singleTypeChannelsMgr).getChannels\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/channels_mgr.go:165\ngithub.com/milvus-io/milvus/internal/proxy.(*channelsMgrImpl).getChannels\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/channels_mgr.go:330\ngithub.com/milvus-io/milvus/internal/proxy.(*insertTask).getChannels\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_insert.go:99\ngithub.com/milvus-io/milvus/internal/proxy.(*insertTask).getPChanStats\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_insert.go:77\ngithub.com/milvus-io/milvus/internal/proxy.(*dmTaskQueue).addPChanStats\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:262\ngithub.com/milvus-io/milvus/internal/proxy.(*dmTaskQueue).Enqueue\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:235\ngithub.com/milvus-io/milvus/internal/proxy.(*Proxy).Insert\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/impl.go:2539\ngithub.com/milvus-io/milvus/internal/distributed/proxy.(*Server).Insert\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:670\ngithub.com/milvus-io/milvus-proto/go-api/milvuspb._MilvusService_Insert_Handler.func1\n\t/go/pkg/mod/github.com/milvus-io/milvus-proto/go-api@v0.0.0-20221019080323-84e9fa2f9e45/milvuspb/milvus.pb.go:9360\ngithub.com/milvus-io/milvus/internal/proxy.RateLimitInterceptor.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/rate_limit_interceptor.go:52\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/milvus-io/milvus/internal/util/logutil.UnaryTraceLoggerInterceptor\n\t/go/src/github.com/milvus-io/milvus/internal/util/logutil/grpc_interceptor.go:22\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/milvus-io/milvus/internal/proxy.UnaryServerInterceptor.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/privilege_interceptor.go:70\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/milvus-io/milvus/internal/proxy.UnaryServerHookInterceptor.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/hook_interceptor.go:91\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/grpc-ecosystem/go-grpc-middleware/auth.UnaryServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/auth/auth.go:47\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34\ngithub.com/milvus-io/milvus-proto/go-api/milvuspb._MilvusService_Insert_Handler\n\t/go/pkg/mod/github.com/milvus-io/milvus-proto/go-api@v0.0.0-20221019080323-84e9fa2f9e45/milvuspb/milvus.pb.go:9362\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1283\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1620\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:922"]
[2022/12/12 00:01:50.396 +00:00] [WARN] [proxy/task_scheduler.go:264] ["Proxy dmTaskQueue addPChanStats"] [tID=437991062989701141] [stats={}] [error="code: CollectionNotExists, reason: can't find collection: 0"]
[2022/12/12 00:01:50.396 +00:00] [WARN] [proxy/impl.go:2540] ["Failed to enqueue insert task: code: CollectionNotExists, reason: can't find collection: 0"]
[2022/12/12 00:01:50.398 +00:00] [ERROR] [proxy/channels_mgr.go:104] ["failed to describe collection"] [error_code=UnexpectedError] [reason="code: CollectionNotExists, reason: can't find collection: 0"] [stack="github.com/milvus-io/milvus/internal/proxy.getDmlChannelsFunc.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/channels_mgr.go:104\ngithub.com/milvus-io/milvus/internal/proxy.(*singleTypeChannelsMgr).getPChans\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/channels_mgr.go:145\ngithub.com/milvus-io/milvus/internal/proxy.(*singleTypeChannelsMgr).getChannels\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/channels_mgr.go:165\ngithub.com/milvus-io/milvus/internal/proxy.(*channelsMgrImpl).getChannels\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/channels_mgr.go:330\ngithub.com/milvus-io/milvus/internal/proxy.(*insertTask).getChannels\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_insert.go:99\ngithub.com/milvus-io/milvus/internal/proxy.(*dmTaskQueue).popPChanStats\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:296\ngithub.com/milvus-io/milvus/internal/proxy.(*dmTaskQueue).PopActiveTask\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:253\ngithub.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:442\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:838\nruntime.panicmem\n\t/usr/local/go/src/runtime/panic.go:220\nruntime.sigpanic\n\t/usr/local/go/src/runtime/signal_unix.go:818\ngithub.com/milvus-io/milvus/internal/proxy.(*insertTask).checkLengthOfFieldsData\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_insert.go:108\ngithub.com/milvus-io/milvus/internal/proxy.(*insertTask).checkPrimaryFieldData\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_insert.go:128\ngithub.com/milvus-io/milvus/internal/proxy.(*insertTask).PreExecute\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_insert.go:233\ngithub.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:446"]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x2bbe09f]

goroutine 4800058 [running]:
github.com/milvus-io/milvus/internal/proxy.(*insertTask).checkLengthOfFieldsData(0x3?)
        /go/src/github.com/milvus-io/milvus/internal/proxy/task_insert.go:108 +0x1f
github.com/milvus-io/milvus/internal/proxy.(*insertTask).checkPrimaryFieldData(0xc002a53e00)
        /go/src/github.com/milvus-io/milvus/internal/proxy/task_insert.go:128 +0x69
github.com/milvus-io/milvus/internal/proxy.(*insertTask).PreExecute(0xc002a53e00, {0xc0034bf780?, 0x1?})
        /go/src/github.com/milvus-io/milvus/internal/proxy/task_insert.go:233 +0xd96
github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask(0xc000ec7860?, {0x41073e8, 0xc002a53e00}, {0x4104fd0, 0xc001d0da70})
        /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:446 +0x51b
created by github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).manipulationLoop
        /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:503 +0x1c5
/received request to invalidate collection meta cache

**Comment by yanliang567** [comment]
@tiratano Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the full Milvus logs, etcd and pulsar logs for investigation? 
Generally, insert with multiple threads would require much much more resource on pulsar and etcd, so could you please also offer the configurations of pulsar and etcd? In case you are using default config, we suggest you insert with less than 10 threads and 15MB per second as a max throughput. 

/assign @tiratano

**Comment by xiaofan-luan** [comment]
@tiratano 
Is it 100% reproducible? Could your share your code to reproduce the issue?

**Comment by tiratano** [comment]
@yanliang567 Thanks for your explanation. I'll export the full logs and attach them with config files soon. If I want to increase thread numbers and throughput, which configs should I modify?

@xiaofan-luan It occurred during the testing period, Milvus is one of the codes. so it is hard to reproduce the exact same case. However, I guess too many threads were the main reason for the crash. I'll try to reproduce the case and share the code if it's successful.

**Comment by czs007** [comment]
@tiratano Could please share the code for the step of creating collection ?
Did you specify the property  `collection.ttl.seconds` by accident?

**Comment by tiratano** [comment]
@czs007 My code consists of many parts and one of them is the Milvus code so I need to clean up the other parts. Anyway, the core part should be something like `collection.insert(data, partition_name=_partition_name)` Furthermore, there may be other variables since it has some codes causing time differences. I'll try to make a reproducing code and share them.

For the last question, no I did not specify the property since I didn't know that option.

**Comment by yanliang567** [comment]
@tiratano quick question, how many collections were you inserting with multi-threads at the same time?

@czs007 please help to look into this issue.

**Comment by czs007** [comment]
@tiratano thanks for the log.
I am investing. @yanliang567

**Comment by czs007** [comment]
@tiratano could you please provid previous log for rootcoord. especially logs in day 2022/12/12.

**Comment by czs007** [comment]
@tiratano  @yanliang567 @xiaofan-luan 
The bug has been located and I'm trying to fix it.  this patch will be shipped in 2.2.1

**Comment by tiratano** [comment]
@czs007 Thanks! Can I by any chance know the release date for the v2.2.1?

By the way, for the previous question, I cannot find logs for the rootcood in 2022/12/12. 
The log starts from 2022/12/15 and no previous logs. Is there any log size or period limitation?
Regarding log configurations, I just used a default setting. If it's not normal, please tell me how to export previous logs.

```
NAME                                            READY   STATUS      RESTARTS        AGE
my-release-milvus-rootcoord-b84785844-jvh4d     1/1     Running     0               5d3h

$ kubectl logs my-release-milvus-rootcoord-b84785844-jvh4d --previous
Error from server (BadRequest): previous terminated container "rootcoord" in pod "my-release-milvus-rootcoord-b84785844-jvh4d" not found

kubectl logs my-release-milvus-rootcoord-b84785844-jvh4d | head
[2022/12/15 21:13:51.348 +00:00] [INFO] [rootcoord/root_coord.go:956] ["received request to describe collection"] [traceID=68525e8a73ebb4b4] ["collection name"=] [id=437962553766107741] [msgID=0] [ts=18446744073709551615]
[2022/12/15 21:13:51.349 +00:00] [INFO] [rootcoord/root_coord.go:985] ["done to describe collection"] [traceID=68525e8a73ebb4b4] ["collection name"=] [id=437962553766107741] [msgID=0] [ts=18446744073709551615] [collection_id=437962553766107741]
[2022/12/15 21:13:51.349 +00:00] [INFO] [rootcoord/root_coord.go:1249] ["received request to show partitions"] [traceID=14b8127bfbd6c4b8] [collection=] [msgID=0]
[2022/12/15 21:13:51.350 +00:00] [INFO] [rootcoord/root_coord.go:1276] ["done to show partitions"] [traceID=14b8127bfbd6c4b8] [collection=] [msgID=0] [partitions="[_default,1943_xxx, ..., 1352_,1354_]"]
```

**Comment by yanliang567** [comment]
@tiratano you can check the logs retention configuration in k8s. 
What's more, this issue was fixed in 2.2.1, could you please help to verify it?

**Comment by tiratano** [comment]
@yanliang567 I upgraded Milvus to 2.2.1 and now it's solved! Thanks.

**Comment by yanliang567** [comment]
> @yanliang567 I upgraded Milvus to 2.2.1 and now it's solved! Thanks.

great to hear that, i will close this issue for now. Please feel free to file a new issue if any problems
