### ISSUE TITLE
[Bug]: Release collection timeout(120s) after datacoord pod failure chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#21229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-20221213-437e4430
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.3.0.dev21
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2022-12-13T22:16:35.797Z] [2022-12-13 22:14:28 - INFO - ci_test]: assert flush: 2.522702217102051, entities: 9000 (test_data_persistence.py:45)

[2022-12-13T22:16:35.797Z] [2022-12-13 22:14:28 - INFO - ci_test]: index info: [{'collection': 'Hello_Milvus', 'field': 'float_vector', 'index_name': 'test_EimABaRf', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}, {'collection': 'Hello_Milvus', 'field': 'varchar', 'index_name': 'test_UxcmNzD3', 'index_param': {'index_type': 'Trie'}}] (test_data_persistence.py:64)

[2022-12-13T22:16:35.797Z] [2022-12-13 22:14:28 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:56)

[2022-12-13T22:16:35.797Z] [2022-12-13 22:14:28 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)

[2022-12-13T22:16:35.797Z] [2022-12-13 22:14:28 - INFO - ci_test]: [test][2022-12-13T22:14:28Z] [0.00488615s] Hello_Milvus load -> None (wrapper.py:30)

[2022-12-13T22:16:35.797Z] [2022-12-13 22:14:28 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.14951110531989925, 0.0042006107116955614, 0.03019967013429185, 0.13963021614888704, 0.023427741150505905, 0.05204653384800491, 0.005952359764187688, 0.05351390580985805, 0.11692606709353275, 0.022705026632890736, 0.009148047689023338, 0.033622396844635014, 0.07769632401762165, 0.061120616657271......, kwargs: {} (api_request.py:56)

[2022-12-13T22:16:35.797Z] [2022-12-13 22:14:29 - DEBUG - ci_test]: (api_response) : ["['(distance: 0.3493305444717407, id: 2092)']"]  (api_request.py:31)

[2022-12-13T22:16:35.797Z] [2022-12-13 22:14:29 - INFO - ci_test]: [test][2022-12-13T22:14:28Z] [0.41317743s] Hello_Milvus search -> <pymilvus.orm.search.SearchResult object at 0x7fdf7e06abb0> (wrapper.py:30)

[2022-12-13T22:16:35.797Z] [2022-12-13 22:14:29 - INFO - ci_test]: assert search: 0.41338491439819336 (test_data_persistence.py:76)

[2022-12-13T22:16:35.797Z] [2022-12-13 22:14:29 - DEBUG - ci_test]: (api_request)  : [Collection.release] args: [], kwargs: {'timeout': 120} (api_request.py:56)

[2022-12-13T22:16:35.797Z] [2022-12-13 22:16:29 - ERROR - pymilvus.decorators]: RPC error: [release_collection], <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 120s)>, <Time:{'RPC start': '2022-12-13 22:14:29.109611', 'RPC error': '2022-12-13 22:16:29.110269'}> (decorators.py:108)

[2022-12-13T22:16:35.797Z] [2022-12-13 22:16:29 - ERROR - ci_test]: Traceback (most recent call last):

[2022-12-13T22:16:35.797Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2022-12-13T22:16:35.797Z]     return func(self, *args, **kwargs)

[2022-12-13T22:16:35.797Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 689, in release_collection

[2022-12-13T22:16:35.797Z]     response = rf.result()

[2022-12-13T22:16:35.797Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 744, in result

[2022-12-13T22:16:35.797Z]     raise self

[2022-12-13T22:16:35.797Z] grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:

[2022-12-13T22:16:35.797Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2022-12-13T22:16:35.797Z] 	details = "Deadline Exceeded"

[2022-12-13T22:16:35.797Z] 	debug_error_string = "{"created":"@1670969789.109883127","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":81,"grpc_status":4}"

[2022-12-13T22:16:35.797Z] >

[2022-12-13T22:16:35.797Z] 

[2022-12-13T22:16:35.797Z] The above exception was the direct cause of the following exception:

[2022-12-13T22:16:35.797Z] 

[2022-12-13T22:16:35.797Z] Traceback (most recent call last):

[2022-12-13T22:16:35.797Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2022-12-13T22:16:35.797Z]     res = func(*args, **_kwargs)

[2022-12-13T22:16:35.797Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2022-12-13T22:16:35.797Z]     return func(*arg, **kwargs)

[2022-12-13T22:16:35.797Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 384, in release

[2022-12-13T22:16:35.797Z]     conn.release_collection(self._name, timeout=timeout, **kwargs)

[2022-12-13T22:16:35.797Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2022-12-13T22:16:35.797Z]     raise e

[2022-12-13T22:16:35.797Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2022-12-13T22:16:35.797Z]     return func(*args, **kwargs)

[2022-12-13T22:16:35.797Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2022-12-13T22:16:35.797Z]     ret = func(self, *args, **kwargs)

[2022-12-13T22:16:35.797Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 64, in handler

[2022-12-13T22:16:35.797Z]     raise MilvusException(message=f"rpc deadline exceeded: {timeout_msg}") from e

[2022-12-13T22:16:35.797Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 120s)>

[2022-12-13T22:16:35.797Z]  (api_request.py:39)

[2022-12-13T22:16:35.797Z] [2022-12-13 22:16:29 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 120s)> (api_request.py:40)

[2022-12-13T22:16:35.797Z] ------------- generated html file: file:///tmp/ci_logs/report.html -------------

[2022-12-13T22:16:35.797Z] =========================== short test summary info ============================

[2022-12-13T22:16:35.797Z] FAILED testcases/test_data_persistence.py::TestDataPersistence::test_milvus_default - AssertionError

[2022-12-13T22:16:35.797Z] ======================== 1 failed in 123.81s (0:02:03) =========================

script returned exit code 1
```

### Milvus Log

chaos type: pod-failure image tag: 2.2.0-20221213-437e4430 target pod: datacoord
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-for-release-cron/detail/chaos-test-for-release-cron/422/pipeline

log:
[artifacts-datacoord-pod-failure-422-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10225609/artifacts-datacoord-pod-failure-422-server-logs.tar.gz)
[artifacts-datacoord-pod-failure-422-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10225612/artifacts-datacoord-pod-failure-422-pytest-logs.tar.gz)

**Comment by jiaoew1991** [comment]
/assign @yah01
/unassign

root cause may be the same as #21230

**Comment by zhuwenxing** [comment]
It was not reproduced again recently with image `2.2.2-20221222-0fdc1a04`
