### ISSUE TITLE
[Bug]: when query offset equal to num_entities or  greater than num_entities milvus-standalone exited with code 2

### ISSUE THREAD

**Issue by luokuncool** [milvus-io/milvus#21223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvusdb/milvus:v2.2.0
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.2.0
- OS(Ubuntu or CentOS): MacOS docker
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

when i call collection query offset equal to num_entities or  greater than num_entities milvus-standalone exited with code 2

- my code：

```python
logger.info("total：{}", tmimg_feature.num_entities)
res = tmimg_feature.query(expr="cls > 0", output_fields=[], offset=0, limit=5)
print(res)

res = tmimg_feature.query(expr="cls > 0", output_fields=[], offset=5, limit=5)
print(res)

res = tmimg_feature.query(expr="cls > 0", output_fields=[], offset=11, limit=5)
print(res)
```

- output:

```
2022-12-14 15:17:54.975 | INFO     | __main__:<module>:5 - total：11
[{'pk': '1000003443'}, {'pk': '1000003529'}, {'pk': '1000003603'}, {'pk': '1000003705'}, {'pk': '1000003831'}]
[{'pk': '1000003941'}, {'pk': '1000004007'}, {'pk': '100000409'}, {'pk': '1000004124'}, {'pk': '1000004207'}]
[query] retry:4, cost: 0.27s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>
[query] retry:5, cost: 0.81s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>
[query] retry:6, cost: 2.43s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>
[query] retry:7, cost: 7.29s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>
[query] retry:8, cost: 21.87s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>
[query] retry:9, cost: 60.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>
```

- container log:

```
milvus-standalone  | [2022/12/14 07:09:00.184 +00:00] [DEBUG] [timerecord/time_recorder.go:91] ["Query: wait query result (191ms)"] [traceID=4f5326b8595ff751]
milvus-standalone  | panic: runtime error: invalid memory address or nil pointer dereference
milvus-standalone  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x2bcb3b1]
milvus-standalone  |
milvus-standalone  | goroutine 3382 [running]:
milvus-standalone  | github.com/milvus-io/milvus/internal/proxy.(*queryTask).PostExecute(0xc004734460, {0x40f0158, 0xc0047dd410})
milvus-standalone  | 	/go/src/github.com/milvus-io/milvus/internal/proxy/task_query.go:378 +0xfb1
milvus-standalone  | github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask(0x0?, {0x4107580, 0xc004734460}, {0x4105048, 0xc003702f30})
milvus-standalone  | 	/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:468 +0xbe8
milvus-standalone  | created by github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).queryLoop
milvus-standalone  | 	/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:519 +0x1e5
milvus-standalone exited with code 2
```

### Expected Behavior

expect an empty list returned

**Comment by xiaofan-luan** [comment]
/assign @XuanYang-cn 
pls take a look into it.

**Comment by yanliang567** [comment]
/assign @NicoYuan1986 
please help to check whether we need a new testcase for this scenario.

/unassign

**Comment by XuanYang-cn** [comment]
looking into it now

**Comment by XuanYang-cn** [comment]
@smellthemoon Please help to cherry-pick to  2.2.0 branch

**Comment by NicoYuan1986** [comment]
Fixed.
