### ISSUE TITLE
[Bug]: milvus crush after some search

### ISSUE THREAD

**Issue by shanghaikid** [milvus-io/milvus#21234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): node sdk v2.2.0
- OS(Ubuntu or CentOS): Mac os
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2022/12/14 07:24:41.861 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=438043326955126787] [segmentID=437841179729350090] [segmentType=3] [loadIndex=false]
[2022/12/14 07:24:41.861 +00:00] [DEBUG] [timerecord/time_recorder.go:91] ["searchTask: enqueueEnd (285ms)"]
[2022/12/14 07:24:41.862 +00:00] [DEBUG] [querynode/validate.go:50] ["read target partitions"] [traceID=66ee5682c1dced4a] [collectionID=437841179729349594] [partitionIDs="[437841179729349595]"]
[2022/12/14 07:24:41.863 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=438043326955126787] [segmentID=437841179729349615] [segmentType=3] [loadIndex=false]
[2022/12/14 07:24:41.859 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=438043326955126787] [segmentID=437841179729351863] [segmentType=3] [loadIndex=false]
[2022/12/14 07:24:41.868 +00:00] [DEBUG] [querynode/segment.go:375] ["do search on segment done"] [msgID=438043326955126787] [segmentID=437841179729349615] [segmentType=3] [loadIndex=false]
[2022/12/14 07:24:41.869 +00:00] [DEBUG] [querynode/segment.go:375] ["do search on segment done"] [msgID=438043326955126787] [segmentID=437841179729350042] [segmentType=3] [loadIndex=false]
[2022/12/14 07:24:41.869 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=438043326955126787] [segmentID=437841179729350041] [segmentType=3] [loadIndex=false]
[2022/12/14 07:24:41.869 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=438043326955126787] [segmentID=437841179729351995] [segmentType=3] [loadIndex=false]
[2022/12/14 07:24:41.872 +00:00] [DEBUG] [querynode/segment.go:375] ["do search on segment done"] [msgID=438043326955126787] [segmentID=437841179729350041] [segmentType=3] [loadIndex=false]
[2022/12/14 07:24:41.872 +00:00] [DEBUG] [querynode/segment.go:375] ["do search on segment done"] [msgID=438043326955126787] [segmentID=437841179729350090] [segmentType=3] [loadIndex=false]
[2022/12/14 07:24:41.872 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=438043326955126787] [segmentID=437841179729350091] [segmentType=3] [loadIndex=false]
[2022/12/14 07:24:41.873 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=438043326955126787] [segmentID=437841179729349616] [segmentType=3] [loadIndex=false]
[2022/12/14 07:24:41.874 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=438043326955126787] [segmentID=437841179729351864] [segmentType=3] [loadIndex=false]
[2022/12/14 07:24:41.874 +00:00] [DEBUG] [querynode/segment.go:358] ["start do search on segment"] [msgID=438043326955126787] [segmentID=437841179729351994] [segmentType=3] [loadIndex=false]
[2022/12/14 07:24:41.876 +00:00] [DEBUG] [querynode/segment.go:375] ["do search on segment done"] [msgID=438043326955126787] [segmentID=437841179729351864] [segmentType=3] [loadIndex=false]
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x2 addr=0x4070313000 pc=0x40035db6c4]

runtime stack:
runtime.throw({0x3d32270?, 0x0?})
/usr/local/go/src/runtime/panic.go:992 +0x71fatal error: unexpected signal during runtime execution

runtime.sigpanic()
/usr/local/go/src/runtime/signal_unix.go:802 +0x3a9

goroutine 609 [syscall, locked to thread]:
runtime.cgocall(0x2e80f50, 0xc002c57e58)
/usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc002c57e30 sp=0xc002c57df8 pc=0x135937c
github.com/milvus-io/milvus/internal/querynode._Cfunc_Search(0x405c46d000, 0x40756b5100, 0x4078e152a0, 0xffffffffffffffff, 0xc00971cb70)
_cgo_gotypes.go:805 +0x55 fp=0xc002c57e58 sp=0xc002c57e30 pc=0x2ce4bb5
github.com/milvus-io/milvus/internal/querynode.(*Segment).search.func1.1(0x3ccb27c?, 0x9?, 0xc00971cb70)
/go/src/github.com/milvus-io/milvus/internal/querynode/segment.go:368 +0xdb fp=0xc002c57ec0 sp=0xc002c57e58 pc=0x2cfd35b
github.com/milvus-io/milvus/internal/querynode.(*Segment).search.func1()
/go/src/github.com/milvus-io/milvus/internal/querynode/segment.go:368 +0x74 fp=0xc002c57f50 sp=0xc002c57ec0 pc=0x2cfd0d4
github.com/milvus-io/milvus/internal/util/concurrency.(*Pool).Submit.func1()
/go/src/github.com/milvus-io/milvus/internal/util/concurrency/pool.go:46 +0x64 fp=0xc002c57f88 sp=0xc002c57f50 pc=0x2852a84
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.8/worker.go:70 +0x97 fp=0xc002c57fe0 sp=0xc002c57f88 pc=0x2851117
runtime.goexit()
/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc002c57fe8 sp=0xc002c57fe0 pc=0x13c2661
created by github.com/panjf2000/ants/v2.(*goWorker).run
/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.8/worker.go:48 +0x65

goroutine 1 [chan receive, 9357 minutes]:
github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run(0xc0018f5e50, 0x1, {0x0, 0x0})
/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:306 +0xb32
github.com/milvus-io/milvus/cmd/milvus.(*run).execute(0xc000b22660, {0xc00004e0c0?, 0x3, 0x3}, 0xc00063e4e0)
/go/src/github.com/milvus-io/milvus/cmd/milvus/run.go:120 +0x733
github.com/milvus-io/milvus/cmd/milvus.RunMilvus({0xc00004e0c0?, 0x3, 0x3})
/go/src/github.com/milvus-io/milvus/cmd/milvus/milvus.go:60 +0x21e
main.main()
/go/src/github.com/milvus-io/milvus/cmd/main.go:26 +0x2e

goroutine 165 [IO wait]:
internal/poll.runtime_pollWait(0x4058f0a6e8, 0x72)
/usr/local/go/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc000517080?, 0xc000118000?, 0x0)
/usr/local/go/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
/usr/local/go/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc000517080, {0xc000118000, 0x8000, 0x8000})
/usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc000517080, {0xc000118000?, 0x3b85dc0?, 0x13d0401?})
/usr/local/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc0002fc1c0, {0xc000118000?, 0x0?, 0x805010601?})
/usr/local/go/src/net/net.go:183 +0x45
bufio.(*Reader).Read(0xc000114900, {0xc0004e6660, 0x9, 0x18?})
/usr/local/go/src/bufio/bufio.go:236 +0x1b4
io.ReadAtLeast({0x40d4f80, 0xc000114900}, {0xc0004e6660, 0x9, 0x9}, 0x9)
/usr/local/go/src/io/io.go:331 +0x9a
io.ReadFull(...)
/usr/local/go/src/io/io.go:350
golang.org/x/net/http2.readFrameHeader({0xc0004e6660?, 0x9?, 0x1fea2deb4103d?}, {0x40d4f80?, 0xc000114900?})
/go/pkg/mod/golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd/http2/frame.go:237 +0x6e
golang.org/x/net/http2.(*Framer).ReadFrame(0xc0004e6620)
/go/pkg/mod/golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd/http2/frame.go:498 +0x95
google.golang.org/grpc/internal/transport.(*http2Client).reader(0xc0000003c0)
/go/pkg/mod/google.golang.org/grpc@v1.46.0/internal/transport/http2_client.go:1498 +0x414
created by google.golang.org/grpc/internal/transport.newHTTP2Client
/go/pkg/mod/google.golang.org/grpc@v1.46.0/internal/transport/http2_client.go:365 +0x193f

goroutine 233 [select, 9357 minutes]:
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc000f2f940)
/go/pkg/mod/google.golang.org/grpc@v1.46.0/balancer_conn_wrappers.go:112 +0x73
created by google.golang.org/grpc.newCCBalancerWrapper
/go/pkg/mod/google.golang.org/grpc@v1.46.0/balancer_conn_wrappers.go:73 +0x22a

goroutine 106 [chan receive]:
github.com/panjf2000/ants/v2.(*Pool).purgePeriodically(0xc0002b6380)
/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.8/pool.go:69 +0x8b
created by github.com/panjf2000/ants/v2.NewPool
/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.8/pool.go:137 +0x34a

goroutine 110 [select, 9357 minutes]:
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc000594600)
/go/pkg/mod/google.golang.org/grpc@v1.46.0/balancer_conn_wrappers.go:112 +0x73
created by google.golang.org/grpc.newCCBalancerWrapper
/go/pkg/mod/google.golang.org/grpc@v1.46.0/balancer_conn_wrappers.go:73 +0x22a

goroutine 167 [select]:
github.com/milvus-io/milvus/internal/config.(*EtcdSource).refreshConfigurationsPeriodically(0xc000516e00)
/go/src/github.com/milvus-io/milvus/internal/config/etcd_source.go:135 +0x9f
created by github.com/milvus-io/milvus/internal/config.(*EtcdSource).GetConfigurations.func1
/go/src/github.com/milvus-io/milvus/internal/config/etcd_source.go:88 +0x5a

goroutine 195 [IO wait]:
internal/poll.runtime_pollWait(0x4058f0a328, 0x72)
/usr/local/go/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc000c46f00?, 0xc000bc6000?, 0x0)
/usr/local/go/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
/usr/local/go/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc000c46f00, {0xc000bc6000, 0x8000, 0x8000})
/usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc000c46f00, {0xc000bc6000?, 0x3b85dc0?, 0x1?})
/usr/local/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc000620750, {0xc000bc6000?, 0x13a5800?, 0x807010601?})
/usr/local/go/src/net/net.go:183 +0x45
bufio.(*Reader).Read(0xc00063ea80, {0xc0004e63c0, 0x9, 0x18?})
/usr/local/go/src/bufio/bufio.go:236 +0x1b4
io.ReadAtLeast({0x40d4f80, 0xc00063ea80}, {0xc0004e63c0, 0x9, 0x9}, 0x9)
/usr/local/go/src/io/io.go:331 +0x9a
io.ReadFull(...)
/usr/local/go/src/io/io.go:350
golang.org/x/net/http2.readFrameHeader({0xc0004e63c0?, 0x9?, 0x1fea2f74a4382?}, {0x40d4f80?, 0xc00063ea80?})
/go/pkg/mod/golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd/http2/frame.go:237 +0x6e
golang.org/x/net/http2.(*Framer).ReadFrame(0xc0004e6380)
/go/pkg/mod/golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd/http2/frame.go:498 +0x95
google.golang.org/grpc/internal/transport.(*http2Client).reader(0xc000045680)
/go/pkg/mod/google.golang.org/grpc@v1.46.0/internal/transport/http2_client.go:1498 +0x414
created by google.golang.org/grpc/internal/transport.newHTTP2Client
/go/pkg/mod/google.golang.org/grpc@v1.46.0/internal/transport/http2_client.go:365 +0x193f

goroutine 166 [select]:
google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc000b08370, 0x1)
/go/pkg/mod/google.golang.org/grpc@v1.46.0/internal/transport/controlbuf.go:407 +0x115
google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc000114960)
/go/pkg/mod/google.golang.org/grpc@v1.46.0/internal/transport/controlbuf.go:534 +0x85
google.golang.org/grpc/internal/transport.newHTTP2Client.func3()
/go/pkg/mod/google.golang.org/grpc@v1.46.0/internal/transport/http2_client.go:415 +0x65
created by google.golang.org/grpc/internal/transport.newHTTP2Client
/go/pkg/mod/google.golang.org/grpc@v1.46.0/internal/transport/http2_client.go:413 +0x1f91

```

### Steps To Reproduce

```markdown
I did some binary vector search on attu, then milvus crushed. After restarting, everything back.
```

### Milvus Log

[milvus.log.zip](https://github.com/milvus-io/milvus/files/10226012/milvus.log.zip)

**Comment by yanliang567** [comment]
/assign @jiaoew1991 
looks like cgo crashed, could you please take a look first? @jiaoew1991 

/unassign

**Comment by xiaofan-luan** [comment]
@shanghaikid is there a way we can quickly reproduce the issue?

**Comment by shanghaikid** [comment]
> @shanghaikid is there a way we can quickly reproduce the issue?

I can reproduce this issue anymore.  : (

**Comment by jiaoew1991** [comment]
The information in the log is insufficient, and the bug needs to be reproduced 😅
