### ISSUE TITLE
[Bug]: [benchmark][varchar]Milvus failed to load after inserting varchar field with max length 10000 

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#21251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20221213-1c309a74 
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.1dev4
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

deploy_config：
fouramf-server-cluster-8c64m-test
case_params：
fouramf-client-varchar-search-maxlen10000
other_params：
 --milvus_tag=2.2.0-20221213-1c309a74 -k test_search_custom_parameters -s --case_skip_clean_collection --deploy_mode=cluster --sync_report 

server：
```
fouramf-q57mr-54-5964-etcd-0                                      1/1     Running     0                83m     10.104.1.50    4am-node10   <none>           <none>
fouramf-q57mr-54-5964-etcd-1                                      1/1     Running     0                83m     10.104.9.71    4am-node14   <none>           <none>
fouramf-q57mr-54-5964-etcd-2                                      1/1     Running     0                83m     10.104.4.81    4am-node11   <none>           <none>
fouramf-q57mr-54-5964-milvus-datacoord-84cc97b479-6c7nz           1/1     Running     0                83m     10.104.1.34    4am-node10   <none>           <none>
fouramf-q57mr-54-5964-milvus-datanode-5bf7dd6984-k5zdw            1/1     Running     0                83m     10.104.9.69    4am-node14   <none>           <none>
fouramf-q57mr-54-5964-milvus-indexcoord-9cf68c746-hw6hc           1/1     Running     0                83m     10.104.1.37    4am-node10   <none>           <none>
fouramf-q57mr-54-5964-milvus-indexnode-d76686fb7-w7xbj            1/1     Running     0                83m     10.104.4.76    4am-node11   <none>           <none>
fouramf-q57mr-54-5964-milvus-proxy-6c6f85ddc6-s7kxg               1/1     Running     0                83m     10.104.4.74    4am-node11   <none>           <none>
fouramf-q57mr-54-5964-milvus-querycoord-69497b9c97-qtj9t          1/1     Running     0                83m     10.104.4.71    4am-node11   <none>           <none>
fouramf-q57mr-54-5964-milvus-querynode-676688bb77-4p55t           1/1     Running     0                83m     10.104.5.177   4am-node12   <none>           <none>
fouramf-q57mr-54-5964-milvus-rootcoord-67c5c6885f-qpcw6           1/1     Running     0                83m     10.104.1.27    4am-node10   <none>           <none>
fouramf-q57mr-54-5964-minio-0                                     1/1     Running     0                83m     10.104.1.53    4am-node10   <none>           <none>
fouramf-q57mr-54-5964-minio-1                                     1/1     Running     0                83m     10.104.4.83    4am-node11   <none>           <none>
fouramf-q57mr-54-5964-minio-2                                     1/1     Running     0                83m     10.104.5.185   4am-node12   <none>           <none>
fouramf-q57mr-54-5964-minio-3                                     1/1     Running     0                83m     10.104.9.73    4am-node14   <none>           <none>
fouramf-q57mr-54-5964-pulsar-bookie-0                             1/1     Running     0                83m     10.104.1.52    4am-node10   <none>           <none>
fouramf-q57mr-54-5964-pulsar-bookie-1                             1/1     Running     0                83m     10.104.5.183   4am-node12   <none>           <none>
fouramf-q57mr-54-5964-pulsar-bookie-2                             1/1     Running     0                83m     10.104.4.84    4am-node11   <none>           <none>
fouramf-q57mr-54-5964-pulsar-bookie-init-wd9gl                    0/1     Completed   0                83m     10.104.4.77    4am-node11   <none>           <none>
fouramf-q57mr-54-5964-pulsar-broker-0                             1/1     Running     0                83m     10.104.1.36    4am-node10   <none>           <none>
fouramf-q57mr-54-5964-pulsar-proxy-0                              1/1     Running     0                83m     10.104.4.73    4am-node11   <none>           <none>
fouramf-q57mr-54-5964-pulsar-pulsar-init-t2qlh                    0/1     Completed   0                83m     10.104.4.75    4am-node11   <none>           <none>
fouramf-q57mr-54-5964-pulsar-recovery-0                           1/1     Running     0                83m     10.104.1.32    4am-node10   <none>           <none>
fouramf-q57mr-54-5964-pulsar-zookeeper-0                          1/1     Running     0                83m     10.104.1.51    4am-node10   <none>           <none>
fouramf-q57mr-54-5964-pulsar-zookeeper-1                          1/1     Running     0                82m     10.104.5.187   4am-node12   <none>           <none>
fouramf-q57mr-54-5964-pulsar-zookeeper-2                          1/1     Running     0                82m     10.104.4.86    4am-node11   <none>           <none>
```
client log：

```
[2022-12-15 05:12:18,051 -  INFO - fouram]: [CommonCases] RT of build index HNSW: 23.7247s (common_cases.py:81)
[2022-12-15 05:12:18,056 -  INFO - fouram]: [Base] Params of index: {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 8, 'efConstruction': 200}} (base.py:259)
[2022-12-15 05:12:18,056 -  INFO - fouram]: [CommonCases] Prepare index HNSW done. (common_cases.py:84)
[2022-12-15 05:12:18,060 -  INFO - fouram]: [Base] Params of index: {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 8, 'efConstruction': 200}} (base.py:259)
[2022-12-15 05:12:18,060 -  INFO - fouram]: [Base] Start build scalar index of varchar_1 (base.py:253)
[2022-12-15 05:15:17,970 -  INFO - fouram]: [Time] Index run in 179.9097s (api_request.py:41)
[2022-12-15 05:15:17,970 -  INFO - fouram]: [CommonCases] RT of build scalar index varchar_1: 179.9097s (common_cases.py:105)
[2022-12-15 05:15:17,972 -  INFO - fouram]: [Base] Collection:fouram_PqipgTwT indexes (base.py:266)
[2022-12-15 05:15:17,972 -  INFO - fouram]: [CommonCases] Prepare scalars ['varchar_1'] index done. (common_cases.py:107)
[2022-12-15 05:15:17,974 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_PqipgTwT): 1000000 (base.py:281)
[2022-12-15 05:15:17,974 -  INFO - fouram]: [Base] Start load collection fouram_PqipgTwT, replica_number:1 (base.py:108)
[2022-12-15 05:26:10,914 - ERROR - fouram]: RPC error: [get_loading_progress], <MilvusException: (code=1, message=collection 438062822354845700 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-12-15 05:26:10.912857', 'RPC error': '2022-12-15 05:26:10.914159'}> (decorators.py:108)
[2022-12-15 05:26:10,914 - ERROR - fouram]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=collection 438062822354845700 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-12-15 05:15:17.992659', 'RPC error': '2022-12-15 05:26:10.914575'}> (decorators.py:108)
[2022-12-15 05:26:10,914 - ERROR - fouram]: RPC error: [load_collection], <MilvusException: (code=1, message=collection 438062822354845700 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-12-15 05:15:17.974578', 'RPC error': '2022-12-15 05:26:10.914678'}> (decorators.py:108)
[2022-12-15 05:26:10,915 - ERROR - fouram]: Traceback (most recent call last):
  File "/src/fouram/client/util/api_request.py", line 33, in inner_wrapper
    res = func(*args, **kwargs)
  File "/src/fouram/client/util/api_request.py", line 70, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 361, in load
    conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 659, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 677, in wait_for_loading_collection
    progress = self.get_loading_progress(collection_name, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 738, in get_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection 438062822354845700 has not been loaded to memory or load failed)>
 (api_request.py:48)
[2022-12-15 05:26:10,915 - ERROR - fouram]: (api_response) : <MilvusException: (code=1, message=collection 438062822354845700 has not been loaded to memory or load failed)> (api_request.py:49)
```

grafana:

querynode memory;
<img width="1346" alt="截屏2022-12-15 14 26 04" src="https://user-images.githubusercontent.com/34296482/207788241-c0ce373d-d3bf-45b6-a7cb-8045624ded12.png">

### Steps To Reproduce

```markdown
1. create a collection 
        2. build index on vector column
        3. insert a 1m number of vectors
        4. flush collection
        5. build hnsw  index on vector column with the same parameters
        6. build index on on scalars column 
        7. count the total number of rows
        8. load collection
        9. search collection
```

### Anything else?

scene_search required params: {'dataset_params': {'dim': 128, 'max_length': 10000, 'varchar_filled': True, 'scalars_index': ['varchar_1'], 'dataset_name': 'sift', 'dataset_size': '1m', 'ni_per': 100, 'metric_type': 'L2', 'req_run_counts': 100000}, 'collection_params': {'other_fields': ['varchar_1']}, 'load_params': {}, 'search_params': {'top_k': [1], 'nq': [1], 'search_param': {'ef': [64], 'output_fields': ['varchar_1']}}, 'index_params': {'index_type': 'HNSW', 'index_param': {'M': 8, 'efConstruction': 200}}} (params_check.py:31)

**Comment by xige-16** [comment]
[querynode/cgo_helper.go:56] ["LoadFieldData failed, C Runtime Exception: [UnexpectedError] Assert \"suc\" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/segment_c.cpp:208\n => unmarshal field data string failed\n"]
https://github.com/milvus-io/milvus/blob/99975ec7f9d109f8c4598c9b4dfcb16d72627d27/internal/core/src/segcore/segment_c.cpp#L201-L216

**Comment by xige-16** [comment]
The varChar scalar filed  is indexed, so the LoadFieldData interface should not be called, and UpdateSealedSegmentIndex func should be called
https://github.com/milvus-io/milvus/blob/99975ec7f9d109f8c4598c9b4dfcb16d72627d27/internal/core/src/segcore/segment_c.cpp#L236-L247

**Comment by xige-16** [comment]
> The varChar scalar filed is indexed, so the LoadFieldData interface should not be called, and UpdateSealedSegmentIndex func should be called
> 
> https://github.com/milvus-io/milvus/blob/99975ec7f9d109f8c4598c9b4dfcb16d72627d27/internal/core/src/segcore/segment_c.cpp#L236-L247

My mistask. Building scalar index failed, so it is reasonable for querynode to load raw data
```
  | 2022-12-15 13:15:33 | [2022/12/15 05:15:33.645 +00:00] [WARN] [indexcgowrapper/helper.go:76] ["failed to build scalar index, C Runtime Exception: [UnexpectedError] basic_string::append\n"]
```

**Comment by xige-16** [comment]
The semgent of buildindex and load failed has 338983 rows, and the data of varchar field is about 3G. There is a problem when the raw data is transferred from go to c++ through proto

https://github.com/milvus-io/milvus/blob/8c353bf099ba702a22934413cc96fa73134b7fb1/internal/core/src/index/ScalarIndex-inl.h#L67-L75

**Comment by xiaofan-luan** [comment]
I'm working on fix the issue by adding another serialization if data size is large than 2G

**Comment by xige-16** [comment]
releated pr https://github.com/milvus-io/milvus/pull/22382

**Comment by xige-16** [comment]
@jingkl  the bug should has been fixed

**Comment by jingkl** [comment]
block issue： #21266

**Comment by yanliang567** [comment]
/assign @yongpengli-z 
please help to verify the fix

**Comment by elstic** [comment]
> /assign @elstic please help to verify the fix

#### Milvus index creation hangs after inserting a varchar field with a maximum length of 10000 

server:
```
fouramf-kxtbc-72-3397-etcd-0                                      1/1     Running            0               179m    10.104.16.166   4am-node21   <none>           <none>
fouramf-kxtbc-72-3397-etcd-1                                      1/1     Running            0               179m    10.104.21.156   4am-node24   <none>           <none>
fouramf-kxtbc-72-3397-etcd-2                                      1/1     Running            0               179m    10.104.18.146   4am-node25   <none>           <none>
fouramf-kxtbc-72-3397-milvus-datacoord-7c49dbbd65-qwlrv           1/1     Running            0               179m    10.104.9.45     4am-node14   <none>           <none>
fouramf-kxtbc-72-3397-milvus-datanode-bc756674b-xb5kc             1/1     Running            1 (100m ago)    179m    10.104.1.159    4am-node10   <none>           <none>
fouramf-kxtbc-72-3397-milvus-indexcoord-b49cbcc88-2b2gt           1/1     Running            0               179m    10.104.1.160    4am-node10   <none>           <none>
fouramf-kxtbc-72-3397-milvus-indexnode-84f67ffff9-b22vx           1/1     Running            0               179m    10.104.5.20     4am-node12   <none>           <none>
fouramf-kxtbc-72-3397-milvus-proxy-b764bc866-znck4                1/1     Running            0               179m    10.104.12.57    4am-node17   <none>           <none>
fouramf-kxtbc-72-3397-milvus-querycoord-7c84897767-vc27b          1/1     Running            0               179m    10.104.12.58    4am-node17   <none>           <none>
fouramf-kxtbc-72-3397-milvus-querynode-5b98d7b565-kvfdk           1/1     Running            0               179m    10.104.4.176    4am-node11   <none>           <none>
fouramf-kxtbc-72-3397-milvus-rootcoord-55969f845-4lp4j            1/1     Running            0               179m    10.104.1.161    4am-node10   <none>           <none>
fouramf-kxtbc-72-3397-minio-0                                     1/1     Running            0               179m    10.104.23.246   4am-node27   <none>           <none>
fouramf-kxtbc-72-3397-minio-1                                     1/1     Running            0               179m    10.104.25.36    4am-node30   <none>           <none>
fouramf-kxtbc-72-3397-minio-2                                     1/1     Running            0               179m    10.104.31.205   4am-node34   <none>           <none>
fouramf-kxtbc-72-3397-minio-3                                     1/1     Running            0               179m    10.104.34.136   4am-node37   <none>           <none>
fouramf-kxtbc-72-3397-pulsar-bookie-0                             1/1     Running            0               179m    10.104.30.210   4am-node38   <none>           <none>
fouramf-kxtbc-72-3397-pulsar-bookie-1                             1/1     Running            0               179m    10.104.29.67    4am-node35   <none>           <none>
fouramf-kxtbc-72-3397-pulsar-bookie-2                             1/1     Running            0               179m    10.104.19.32    4am-node28   <none>           <none>
fouramf-kxtbc-72-3397-pulsar-bookie-init-qrjdl                    0/1     Completed          0               179m    10.104.4.175    4am-node11   <none>           <none>
fouramf-kxtbc-72-3397-pulsar-broker-0                             1/1     Running            0               179m    10.104.9.46     4am-node14   <none>           <none>
fouramf-kxtbc-72-3397-pulsar-proxy-0                              1/1     Running            0               179m    10.104.12.59    4am-node17   <none>           <none>
fouramf-kxtbc-72-3397-pulsar-pulsar-init-4tn6h                    0/1     Completed          0               179m    10.104.1.162    4am-node10   <none>           <none>
fouramf-kxtbc-72-3397-pulsar-recovery-0                           1/1     Running            0               179m    10.104.1.163    4am-node10   <none>           <none>
fouramf-kxtbc-72-3397-pulsar-zookeeper-0                          1/1     Running            0               179m    10.104.34.134   4am-node37   <none>           <none>
fouramf-kxtbc-72-3397-pulsar-zookeeper-1                          1/1     Running            0               178m    10.104.23.249   4am-node27   <none>           <none>
fouramf-kxtbc-72-3397-pulsar-zookeeper-2                          1/1     Running            0               178m    10.104.21.158   4am-node24   <none>           <none>
```

create index hangs near 2h 
![image](https://github.com/milvus-io/milvus/assets/48523564/3f660abe-7542-42f1-98fd-76eb18882c05)


  @yanliang567 @xige-16

**Comment by czs007** [comment]
may be related to https://github.com/milvus-io/milvus/issues/21266
