### ISSUE TITLE
[Bug]: [Nightly][kafka] Drop nonexistent alias occasionally failed reporting 'get collection_id by alias not found'

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#21268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: ee7fddb
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus2.3.0.dev21
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Drop nonexistent alias failed reporting 'get collection_id by alias not found'.
```
[2022-12-15T19:25:38.893Z] [2022-12-15 18:00:46 - ERROR - pymilvus.decorators]: RPC error: [drop_alias], <MilvusException: (code=1, message=get collection_id by alias not found, alias=alias_zbJ22h6W, ts=438075980959186957)>, <Time:{'RPC start': '2022-12-15 18:00:46.738953', 'RPC error': '2022-12-15 18:00:46.741371'}> (decorators.py:108)
[2022-12-15T19:25:38.893Z] [2022-12-15 18:00:46 - ERROR - ci_test]: Traceback (most recent call last):
[2022-12-15T19:25:38.893Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2022-12-15T19:25:38.893Z]     res = func(*args, **_kwargs)
[2022-12-15T19:25:38.893Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2022-12-15T19:25:38.893Z]     return func(*arg, **kwargs)
[2022-12-15T19:25:38.893Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/utility.py", line 572, in drop_alias
[2022-12-15T19:25:38.893Z]     return _get_connection(using).drop_alias(alias, timeout=timeout)
[2022-12-15T19:25:38.893Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2022-12-15T19:25:38.893Z]     raise e
[2022-12-15T19:25:38.893Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2022-12-15T19:25:38.893Z]     return func(*args, **kwargs)
[2022-12-15T19:25:38.893Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2022-12-15T19:25:38.893Z]     ret = func(self, *args, **kwargs)
[2022-12-15T19:25:38.893Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
[2022-12-15T19:25:38.893Z]     raise e
[2022-12-15T19:25:38.893Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2022-12-15T19:25:38.893Z]     return func(self, *args, **kwargs)
[2022-12-15T19:25:38.893Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 497, in drop_alias
[2022-12-15T19:25:38.893Z]     raise MilvusException(response.error_code, response.reason)
[2022-12-15T19:25:38.893Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=get collection_id by alias not found, alias=alias_zbJ22h6W, ts=438075980959186957)>
[2022-12-15T19:25:38.893Z]  (api_request.py:39)
[2022-12-15T19:25:38.893Z] [2022-12-15 18:00:46 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=get collection_id by alias not found, alias=alias_zbJ22h6W, ts=438075980959186957)> (api_request.py:40)
```

### Expected Behavior

pass

### Steps To Reproduce

```markdown
[2022-12-15T19:25:38.892Z] __________ TestAliasOperationInvalid.test_alias_drop_not_exist_alias ___________
[2022-12-15T19:25:38.892Z] [gw5] linux -- Python 3.8.16 /usr/local/bin/python3
[2022-12-15T19:25:38.892Z] 
[2022-12-15T19:25:38.892Z] self = <test_alias.TestAliasOperationInvalid object at 0x7fb118fcd700>
[2022-12-15T19:25:38.892Z] 
[2022-12-15T19:25:38.892Z]     @pytest.mark.tags(CaseLabel.L1)
[2022-12-15T19:25:38.892Z]     def test_alias_drop_not_exist_alias(self):
[2022-12-15T19:25:38.892Z]         """
[2022-12-15T19:25:38.892Z]         target: test collection dropping alias which is not exist
[2022-12-15T19:25:38.892Z]         method:
[2022-12-15T19:25:38.892Z]                 1.create a collection with alias
[2022-12-15T19:25:38.892Z]                 2.collection drop alias which is not exist
[2022-12-15T19:25:38.892Z]         expected: drop alias failed
[2022-12-15T19:25:38.892Z]         """
[2022-12-15T19:25:38.892Z]         self._connect()
[2022-12-15T19:25:38.892Z]         c_name = cf.gen_unique_str("collection")
[2022-12-15T19:25:38.892Z]         collection_w = self.init_collection_wrap(name=c_name, schema=default_schema,
[2022-12-15T19:25:38.892Z]                                                  check_task=CheckTasks.check_collection_property,
[2022-12-15T19:25:38.892Z]                                                  check_items={exp_name: c_name, exp_schema: default_schema})
[2022-12-15T19:25:38.892Z]         alias_name = cf.gen_unique_str(prefix)
[2022-12-15T19:25:38.892Z]         self.utility_wrap.create_alias(collection_w.name, alias_name)
[2022-12-15T19:25:38.892Z]         # collection_w.create_alias(alias_name)
[2022-12-15T19:25:38.892Z]     
[2022-12-15T19:25:38.892Z]         alias_not_exist_name = cf.gen_unique_str(prefix)
[2022-12-15T19:25:38.892Z]         error = {ct.err_code: 1, ct.err_msg: "Drop alias failed: alias does not exist"}
[2022-12-15T19:25:38.892Z]         # self.utility_wrap.drop_alias(alias_not_exist_name,
[2022-12-15T19:25:38.892Z]         #                              check_task=CheckTasks.err_res,
[2022-12-15T19:25:38.892Z]         #                              check_items=error)
[2022-12-15T19:25:38.892Z]         # @longjiquan: dropping alias should be idempotent.
[2022-12-15T19:25:38.892Z] >       self.utility_wrap.drop_alias(alias_not_exist_name)
[2022-12-15T19:25:38.892Z] 
[2022-12-15T19:25:38.892Z] testcases/test_alias.py:474: 
[2022-12-15T19:25:38.893Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[2022-12-15T19:25:38.893Z] base/utility_wrapper.py:302: in drop_alias
[2022-12-15T19:25:38.893Z]     check_result = ResponseChecker(res, func_name, check_task, check_items, is_succ,
[2022-12-15T19:25:38.893Z] check/func_check.py:34: in run
[2022-12-15T19:25:38.893Z]     result = self.assert_succ(self.succ, True)
[2022-12-15T19:25:38.893Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[2022-12-15T19:25:38.893Z] 
[2022-12-15T19:25:38.893Z] actual = False, expect = True
[2022-12-15T19:25:38.893Z] 
[2022-12-15T19:25:38.893Z]     @staticmethod
[2022-12-15T19:25:38.893Z]     def assert_succ(actual, expect):
[2022-12-15T19:25:38.893Z] >       assert actual is expect
[2022-12-15T19:25:38.893Z] E       AssertionError
[2022-12-15T19:25:38.893Z] 
[2022-12-15T19:25:38.893Z] check/func_check.py:93: AssertionError
```

### Milvus Log

1. report: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/222/pipeline/175/
2. log: [artifacts-milvus-distributed-kafka-nightly-222-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/222/artifact/artifacts-milvus-distributed-kafka-nightly-222-pymilvus-e2e-logs.tar.gz)
3. collection name: collection_DDQKKgMh
4. failed time: [2022-12-15T18:00:47.778Z] [gw5] [  1%] FAILED testcases/test_alias.py::TestAliasOperationInvalid::test_alias_drop_not_exist_alias

**Comment by NicoYuan1986** [comment]
@longjiquan  Could you please have a look? I noticed that you deleted the error check.

**Comment by longjiquan** [comment]
The mysql backend didn't keep the idempotency like etcd. Please help to solve this. @jaime0815 
/unassign
/assign @jaime0815

**Comment by longjiquan** [comment]
https://github.com/milvus-io/milvus/blob/396a85c92614a537958c921ec00aac24fbb20ced/internal/metastore/db/dao/collection_alias.go#L38-L40

**Comment by jaime0815** [comment]
Mysql metastore isn't enabled in this case @longjiquan

**Comment by NicoYuan1986** [comment]
Not supported with mysql. I will disable it soon.
/assign @NicoYuan1986
