### ISSUE TITLE
[Bug]: node is not ready

### ISSUE THREAD

**Issue by smallcai03** [milvus-io/milvus#21324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

when I search milvus_entity,the bug sometimes happens,sometimes is ok, sometimes is error (two error bug)
eg:

RPC error: [search], <MilvusException: (code=1, message=err: failed to connect 10.233.109.24:21123, reason: context deadline exceeded
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:277 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call
/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:254 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Search
/go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:484 github.com/milvus-io/milvus/internal/proxy.(*searchTask).searchShard
/go/src/github.com/milvus-io/milvus/internal/proxy/task_policies.go:128 github.com/milvus-io/milvus/internal/proxy.mergeRoundRobinPolicy.func1
/usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit
)>, <Time:{'RPC start': '2022-12-20 17:02:59.591708', 'RPC error': '2022-12-20 17:03:06.112487'}>
Traceback (most recent call last):
  File "dealMilvus.py", line 184, in <module>
    search()
  File "dealMilvus.py", line 178, in search
    cmi.search(s, search_params)
  File "dealMilvus.py", line 88, in search
    result = self.hello_milvus.search(q, "embeddings", search_params, limit=3)
  File "/root/anaconda3/envs/torchreid/lib/python3.7/site-packages/pymilvus/orm/collection.py", line 611, in search
    schema=self._schema_dict, **kwargs)
  File "/root/anaconda3/envs/torchreid/lib/python3.7/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/root/anaconda3/envs/torchreid/lib/python3.7/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/torchreid/lib/python3.7/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/root/anaconda3/envs/torchreid/lib/python3.7/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/root/anaconda3/envs/torchreid/lib/python3.7/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/root/anaconda3/envs/torchreid/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 470, in search
    return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)
  File "/root/anaconda3/envs/torchreid/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 439, in _execute_search_requests
    raise pre_err
  File "/root/anaconda3/envs/torchreid/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 430, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=err: failed to connect 10.233.109.24:21123, reason: context deadline exceeded
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:277 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call
/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:254 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Search
/go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:484 github.com/milvus-io/milvus/internal/proxy.(*searchTask).searchShard
/go/src/github.com/milvus-io/milvus/internal/proxy/task_policies.go:128 github.com/milvus-io/milvus/internal/proxy.mergeRoundRobinPolicy.func1
/usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit

sometimes:
RPC error: [search], <MilvusException: (code=1, message=Invalid shard leader)>, <Time:{'RPC start': '2022-12-20 14:46:46.224928', 'RPC error': '2022-12-20 14:46:46.229172'}>
Traceback (most recent call last):
  File "dealMilvus2.py", line 196, in <module>
    result = hello_milvus.search(vectors_to_search, "embeddings", search_params, limit=3, output_fields=["random"])
  File "/root/anaconda3/envs/torchreid/lib/python3.7/site-packages/pymilvus/orm/collection.py", line 611, in search
    schema=self._schema_dict, **kwargs)
  File "/root/anaconda3/envs/torchreid/lib/python3.7/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/root/anaconda3/envs/torchreid/lib/python3.7/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/torchreid/lib/python3.7/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/root/anaconda3/envs/torchreid/lib/python3.7/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/root/anaconda3/envs/torchreid/lib/python3.7/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/root/anaconda3/envs/torchreid/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 470, in search
    return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)
  File "/root/anaconda3/envs/torchreid/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 439, in _execute_search_requests
    raise pre_err
  File "/root/anaconda3/envs/torchreid/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 430, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Invalid shard leader)>

### Expected Behavior

when i search or insert  , the result should be ok everytime.

### Steps To Reproduce

```markdown
1.create colletion
2.insert data
3. search data
```

### Milvus Log

[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/10267056/milvus-log.tar.gz)

### Anything else?

no

**Comment by xiaofan-luan** [comment]
@smallcai03 
for the error log
[2022/12/19 07:37:33.639 +00:00] [WARN] [grpclog/grpclog.go:46] ["[core][Channel #928 SubChannel #929] grpc: addrConn.createTransport failed to connect to {\n  \"Addr\": \"10.233.109.24:21123\",\n  \"ServerName\": \"10.233.109.24:21123\",\n  \"Attributes\": null,\n  \"BalancerAttributes\": null,\n  \"Type\": 0,\n  \"Metadata\": null\n}. Err: connection error: desc = \"transport: Error while dialing dial tcp 10.233.109.24:21123: connect: connection refused\""]

**Comment by xiaofan-luan** [comment]
milvus-b1pyjs-querynode-6f7f65b7bf-72tj8-pre  is 10.233.109.24:21123。
Before 09:07 it is not connectable, you see similar log in querycoord logs.
On 09:07 it's ready, but proxy log end at 09:06 so I'm not sure what happened later on.
If you restart proxy it should work

**Comment by yanliang567** [comment]
@smallcai03 also please double check the etcd and pulsar services are working well.

/assign @smallcai03 
/unassign

**Comment by smallcai03** [comment]
Nothing is done, just normal tests to create indexes, enter data, and query.

Moreover, the time when I made the error was around 16:00 in the afternoon, and I did not operate it from 9:00 to 11:00 in the morning

**Comment by smallcai03** [comment]
How can I check if etcd pulsar is working fine.
I installed milvus2.2.0 through kubesphere, a foolish installation, and nothing else can be operated.

**Comment by smallcai03** [comment]
> Nothing is done, just normal tests to create indexes, enter data, and query.
> 
> Moreover, the time when I made the error was around 16:00 in the afternoon, and I did not operate it from 9:00 to 11:00 in the morning

**Comment by smallcai03** [comment]
> How can I check if etcd pulsar is working fine.
> I installed milvus2.2.0 through kubesphere, a foolish installation, and nothing else can be operated.

**Comment by smallcai03** [comment]
The crash reappeared and occurred around 13:40 PM

md5: 9bc3709b5e9d9d7c992744a6c20f5bf1
Number of entities in Milvus: 26120
RPC error: [search], <MilvusException: (code=1, message=Invalid shard leader)>, <Time:{'RPC start': '2022-12-21 13:55:12.744359', 'RPC error': '2022-12-21 13:55:12.752829'}>
Traceback (most recent call last):
  File "dealMilvus.py", line 198, in <module>
    search()
  File "dealMilvus.py", line 192, in search
    cmi.search(s, search_params)
  File "dealMilvus.py", line 89, in search
    result = self.hello_milvus.search(q, "embeddings", search_params, limit=3)
  File "/root/anaconda3/envs/torchreid/lib/python3.7/site-packages/pymilvus/orm/collection.py", line 611, in search
    schema=self._schema_dict, **kwargs)
  File "/root/anaconda3/envs/torchreid/lib/python3.7/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/root/anaconda3/envs/torchreid/lib/python3.7/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/torchreid/lib/python3.7/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/root/anaconda3/envs/torchreid/lib/python3.7/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/root/anaconda3/envs/torchreid/lib/python3.7/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/root/anaconda3/envs/torchreid/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 470, in search
    return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)
  File "/root/anaconda3/envs/torchreid/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 439, in _execute_search_requests
    raise pre_err
  File "/root/anaconda3/envs/torchreid/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 430, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Invalid shard leader)>



another time：
md5: 9bc3709b5e9d9d7c992744a6c20f5bf1
Number of entities in Milvus: 26120
RPC error: [search], <MilvusException: (code=1, message=err: failed to connect 10.233.109.24:21123, reason: context deadline exceeded
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:277 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call
/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:254 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Search
/go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:484 github.com/milvus-io/milvus/internal/proxy.(*searchTask).searchShard
/go/src/github.com/milvus-io/milvus/internal/proxy/task_policies.go:128 github.com/milvus-io/milvus/internal/proxy.mergeRoundRobinPolicy.func1
/usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit
)>, <Time:{'RPC start': '2022-12-21 13:54:13.914161', 'RPC error': '2022-12-21 13:54:19.971503'}>
Traceback (most recent call last):
  File "dealMilvus.py", line 198, in <module>
    search()
  File "dealMilvus.py", line 192, in search
    cmi.search(s, search_params)
  File "dealMilvus.py", line 89, in search
    result = self.hello_milvus.search(q, "embeddings", search_params, limit=3)
  File "/root/anaconda3/envs/torchreid/lib/python3.7/site-packages/pymilvus/orm/collection.py", line 611, in search
    schema=self._schema_dict, **kwargs)
  File "/root/anaconda3/envs/torchreid/lib/python3.7/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/root/anaconda3/envs/torchreid/lib/python3.7/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/torchreid/lib/python3.7/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/root/anaconda3/envs/torchreid/lib/python3.7/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/root/anaconda3/envs/torchreid/lib/python3.7/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/root/anaconda3/envs/torchreid/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 470, in search
    return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)
  File "/root/anaconda3/envs/torchreid/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 439, in _execute_search_requests
    raise pre_err
  File "/root/anaconda3/envs/torchreid/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 430, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=err: failed to connect 10.233.109.24:21123, reason: context deadline exceeded
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:277 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call
/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:254 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Search
/go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:484 github.com/milvus-io/milvus/internal/proxy.(*searchTask).searchShard
/go/src/github.com/milvus-io/milvus/internal/proxy/task_policies.go:128 github.com/milvus-io/milvus/internal/proxy.mergeRoundRobinPolicy.func1
[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/10274911/milvus-log.tar.gz)

**Comment by smallcai03** [comment]
milvus-pro                     milvus-b1pyjs-querynode-6f7f65b7bf-72tj8           0/1     Running     28         5d

milvus-pro                     milvus-b1pyjs-querynode-6f7f65b7bf-72tj8           0/1     CrashLoopBackOff   27         5d

milvus-pro                     milvus-b1pyjs-querynode-6f7f65b7bf-72tj8           1/1     Running     27         5d

**Comment by smallcai03** [comment]
Paralyzed focus milvus-pro milvus-b1pyjs-querynode-6f7f65b7bf-72tj8 。The log time needs to be subtracted by 8 hours。
Also my environment is：
kubesphere 3.2.1
k8s 1.21.5
milvus 3.3.2 [2.2.0]  (kubesphere show)
pymivlsu 2.2.1
docker 20.10.8

**Comment by smallcai03** [comment]
the log from kubectl logs milvus-b1pyjs-querynode-5746865f4-j285j -n milvus-pro:

libgomp:
libgomp:
libgomp: Thread creation failed: Resource temporarily unavailable
Thread creation failed: Resource temporarily unavailable
Thread creation failed: Resource temporarily unavailableThread creation failed: Resource temporarily unavailable

**Comment by smallcai03** [comment]
the log from kubectl logs milvus-b1pyjs-querynode-5746865f4-j285j -n milvus-pro:

[2022/12/22 02:38:21.718 +00:00] [WARN] [querynode/impl.go:799] ["Search failed, failed to get query shard"] [traceID=117634bb05c876ec] [msgID=438220016731291653] ["dml channel"=by-dev-rootcoord-dml_33_438087684253496381v1] [error="query shard(channel)  by-dev-rootcoord-dml_33_438087684253496381v1  does not exist\n"]
[2022/12/22 02:38:21.718 +00:00] [WARN] [querynode/impl.go:799] ["Search failed, failed to get query shard"] [traceID=117634bb05c876ec] [msgID=438220016731291653] ["dml channel"=by-dev-rootcoord-dml_32_438087684253496381v0] [error="query shard(channel)  by-dev-rootcoord-dml_32_438087684253496381v0  does not exist\n"]
[2022/12/22 02:38:22.961 +00:00] [INFO] [gc/gc_tuner.go:81] ["GC Tune done"] ["previous GOGC"=100] ["heapuse "=20] ["total memory"=33] ["next GC"=29] ["new GOGC"=200]

**Comment by xiaofan-luan** [comment]
libgomp: Thread creation failed 
That seemed to be the problem. libomp is trying to create too many thread and over the system limit.
on 2.2.1 we fixed some of the thread issue.  Try 2.2.2(we'll release later today)

**Comment by smallcai03** [comment]
Paralysis explains:
2.2.2 Is it pymilvus or something else

**Comment by JackLCL** [comment]
2.2.2 is a newer milvus version.
