### ISSUE TITLE
[Bug]:  QueryCoord panic during query node down

### ISSUE THREAD

**Issue by jaime0815** [milvus-io/milvus#21345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2022/12/21 10:20:22.757 +00:00] [INFO] [querycoordv2/server.go:573] ["a node down, remove it"] [nodeID=3]
[2022/12/21 10:20:22.757 +00:00] [INFO] [task/merger.go:81] ["Merger stopped"]
[2022/12/21 10:20:22.757 +00:00] [INFO] [task/scheduler.go:233] ["remove executor of offline QueryNode"] [nodeID=3]
[2022/12/21 10:20:23.003 +00:00] [WARN] [task/scheduler.go:583] ["no executor for QueryNode"] [taskID=38] [type=1] [collectionID=438204574270164371] [replicaID=438204574377181188] [source=2] [step=0] [nodeID=3]
[2022/12/21 10:20:23.003 +00:00] [WARN] [task/scheduler.go:583] ["no executor for QueryNode"] [taskID=52] [type=1] [collectionID=438204574270164983] [replicaID=438204574377181194] [source=2] [step=0] [nodeID=3]
[2022/12/21 10:20:23.003 +00:00] [WARN] [task/scheduler.go:583] ["no executor for QueryNode"] [taskID=63] [type=1] [collectionID=438204574270164498] [replicaID=438204574377181190] [source=2] [step=0] [nodeID=3]
[2022/12/21 10:20:23.003 +00:00] [WARN] [task/scheduler.go:583] ["no executor for QueryNode"] [taskID=57] [type=1] [collectionID=438204574270164505] [replicaID=438204574377181193] [source=2] [step=0] [nodeID=3]
[2022/12/21 10:20:23.003 +00:00] [WARN] [task/scheduler.go:583] ["no executor for QueryNode"] [taskID=55] [type=1] [collectionID=438204574270164505] [replicaID=438204574377181193] [source=2] [step=0] [nodeID=3]
[2022/12/21 10:20:23.003 +00:00] [WARN] [task/scheduler.go:583] ["no executor for QueryNode"] [taskID=40] [type=1] [collectionID=438204574270164508] [replicaID=438204574377181189] [source=2] [step=0] [nodeID=3]
[2022/12/21 10:20:23.003 +00:00] [WARN] [task/scheduler.go:583] ["no executor for QueryNode"] [taskID=62] [type=1] [collectionID=438204574270164505] [replicaID=438204574377181193] [source=2] [step=0] [nodeID=3]
[2022/12/21 10:20:23.003 +00:00] [WARN] [task/scheduler.go:583] ["no executor for QueryNode"] [taskID=28] [type=1] [collectionID=438204574270164501] [replicaID=438204574377181192] [source=2] [step=0] [nodeID=3]
[2022/12/21 10:20:23.003 +00:00] [WARN] [task/scheduler.go:583] ["no executor for QueryNode"] [taskID=60] [type=1] [collectionID=438204574270164505] [replicaID=438204574377181193] [source=2] [step=0] [nodeID=3]
[2022/12/21 10:20:23.003 +00:00] [WARN] [task/scheduler.go:583] ["no executor for QueryNode"] [taskID=53] [type=1] [collectionID=438204574270165614] [replicaID=438204574377181195] [source=2] [step=0] [nodeID=3]
[2022/12/21 10:20:23.003 +00:00] [WARN] [task/scheduler.go:583] ["no executor for QueryNode"] [taskID=59] [type=1] [collectionID=438204574270164505] [replicaID=438204574377181193] [source=2] [step=0] [nodeID=3]
[2022/12/21 10:20:23.003 +00:00] [WARN] [task/scheduler.go:583] ["no executor for QueryNode"] [taskID=37] [type=1] [collectionID=438204574270166217] [replicaID=438204574377181196] [source=2] [step=0] [nodeID=3]
[2022/12/21 10:20:23.003 +00:00] [WARN] [task/scheduler.go:583] ["no executor for QueryNode"] [taskID=61] [type=1] [collectionID=438204574270164505] [replicaID=438204574377181193] [source=2] [step=0] [nodeID=3]
[2022/12/21 10:20:23.003 +00:00] [WARN] [task/scheduler.go:583] ["no executor for QueryNode"] [taskID=19] [type=1] [collectionID=438204574270164511] [replicaID=438204574377181191] [source=2] [step=0] [nodeID=3]
[2022/12/21 10:20:23.003 +00:00] [INFO] [task/scheduler.go:512] ["processed tasks"] [nodeID=4] [toProcessNum=0] [failCount=0] [toRemoveNum=0]
[2022/12/21 10:20:23.086 +00:00] [INFO] [observers/collection_observer.go:164] ["collection targets"] [collectionID=438204574270164505] [segmentTargetNum=18] [channelTargetNum=2] [totalTargetNum=20] [replicaNum=1]
[2022/12/21 10:20:23.086 +00:00] [INFO] [observers/collection_observer.go:191] ["collection load progress"] [collectionID=438204574270164505] [subChannelCount=1] [loadSegmentCount=3]
[2022/12/21 10:20:23.086 +00:00] [INFO] [observers/collection_observer.go:164] ["collection targets"] [collectionID=438204574270164508] [segmentTargetNum=24] [channelTargetNum=2] [totalTargetNum=26] [replicaNum=1]
[2022/12/21 10:20:23.087 +00:00] [INFO] [observers/collection_observer.go:191] ["collection load progress"] [collectionID=438204574270164508] [subChannelCount=1] [loadSegmentCount=11]
[2022/12/21 10:20:23.087 +00:00] [INFO] [observers/collection_observer.go:164] ["collection targets"] [collectionID=438204574270164983] [segmentTargetNum=2] [channelTargetNum=2] [totalTargetNum=4] [replicaNum=1]
[2022/12/21 10:20:23.087 +00:00] [INFO] [observers/collection_observer.go:191] ["collection load progress"] [collectionID=438204574270164983] [subChannelCount=1] [loadSegmentCount=0]
[2022/12/21 10:20:23.087 +00:00] [INFO] [observers/collection_observer.go:164] ["collection targets"] [collectionID=438204574270165614] [segmentTargetNum=2] [channelTargetNum=2] [totalTargetNum=4] [replicaNum=1]
[2022/12/21 10:20:23.087 +00:00] [INFO] [observers/collection_observer.go:191] ["collection load progress"] [collectionID=438204574270165614] [subChannelCount=1] [loadSegmentCount=0]
[2022/12/21 10:20:23.087 +00:00] [INFO] [observers/collection_observer.go:164] ["collection targets"] [collectionID=438204574270166217] [segmentTargetNum=2] [channelTargetNum=2] [totalTargetNum=4] [replicaNum=1]
[2022/12/21 10:20:23.087 +00:00] [INFO] [observers/collection_observer.go:191] ["collection load progress"] [collectionID=438204574270166217] [subChannelCount=1] [loadSegmentCount=0]
[2022/12/21 10:20:23.087 +00:00] [INFO] [observers/collection_observer.go:164] ["collection targets"] [collectionID=438204574270164371] [segmentTargetNum=4] [channelTargetNum=2] [totalTargetNum=6] [replicaNum=1]
[2022/12/21 10:20:23.087 +00:00] [INFO] [observers/collection_observer.go:191] ["collection load progress"] [collectionID=438204574270164371] [subChannelCount=1] [loadSegmentCount=1]
[2022/12/21 10:20:23.087 +00:00] [INFO] [observers/collection_observer.go:164] ["collection targets"] [collectionID=438204574270164498] [segmentTargetNum=22] [channelTargetNum=2] [totalTargetNum=24] [replicaNum=1]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x2a5e4f3]

goroutine 12120 [running]:
github.com/milvus-io/milvus/internal/querycoordv2/session.(*NodeInfo).IsStoppingState(0x3272e80?)
	/go/src/github.com/milvus-io/milvus/internal/querycoordv2/session/node_manager.go:129 +0x33
github.com/milvus-io/milvus/internal/querycoordv2/balance.(*RowCountBasedBalancer).balanceReplica(0xc000e7f320, 0xc002333920)
	/go/src/github.com/milvus-io/milvus/internal/querycoordv2/balance/rowcount_based_balancer.go:126 +0x3f3
github.com/milvus-io/milvus/internal/querycoordv2/balance.(*RowCountBasedBalancer).Balance(0xc000e7f320)
	/go/src/github.com/milvus-io/milvus/internal/querycoordv2/balance/rowcount_based_balancer.go:96 +0x26d
github.com/milvus-io/milvus/internal/querycoordv2/checkers.(*BalanceChecker).Check(0xc00316d1a0, {0x3a0f150, 0xc0010b0240})
	/go/src/github.com/milvus-io/milvus/internal/querycoordv2/checkers/balance_checker.go:46 +0x70
github.com/milvus-io/milvus/internal/querycoordv2/checkers.(*CheckerController).check(0xc001dd2d80, {0x3a0f150, 0xc0010b0240})
	/go/src/github.com/milvus-io/milvus/internal/querycoordv2/checkers/controller.go:121 +0x162
github.com/milvus-io/milvus/internal/querycoordv2/checkers.(*CheckerController).Start.func1()
	/go/src/github.com/milvus-io/milvus/internal/querycoordv2/checkers/controller.go:96 +0x145
created by github.com/milvus-io/milvus/internal/querycoordv2/checkers.(*CheckerController).Start
	/go/src/github.com/milvus-io/milvus/internal/querycoordv2/checkers/controller.go:82 +0x8a

```

**Comment by jaime0815** [comment]
It is a concurrent issue. Node 3 will be removed after printing the log "a node down, remove it",  meanwhile balancer also tries to get the node state, which might occur a nil pointer issue during checking the node state.
