### ISSUE TITLE
[Bug]: [benchmark][standalone]Milvus repeated load failures are reported as"Retry run out of 10 retry times, message=collection 438231170498953220 has not been loaded to memory or load failed"

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#21357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20221222-46a7236b
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.1dev4
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server-instance
fouram-test-no-clean-7btvl-1
server-configmap
server-single-8c16m
client-configmap
client-insert-load-search-sift10m-release

server:
```
fouram-test-no-clean-7btvl-1-etcd-0                               1/1     Running     0             11h     10.104.4.76    4am-node11   <none>           <none>
fouram-test-no-clean-7btvl-1-milvus-standalone-74c8f46b8-5r462    1/1     Running     1 (11h ago)   11h     10.104.9.168   4am-node14   <none>           <none>
fouram-test-no-clean-7btvl-1-minio-85c466d8b9-rkkhj               1/1     Running     0             11h     10.104.4.75    4am-node11   <none>           <none>
```

client log:

```
[2022-12-22 14:53:51,133] [    INFO] - Start load collection (milvus_benchmark.runners.search:714)
[2022-12-22 14:53:52,568] [ WARNING] - [93m[get_loading_progress] retry:4, cost: 0.27s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:71)
[2022-12-22 14:53:52,839] [ WARNING] - [93m[get_loading_progress] retry:5, cost: 0.81s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:71)
[2022-12-22 14:53:53,651] [ WARNING] - [93m[get_loading_progress] retry:6, cost: 2.43s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:71)
[2022-12-22 14:53:56,083] [ WARNING] - [93m[get_loading_progress] retry:7, cost: 7.29s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:71)
[2022-12-22 14:54:03,375] [ WARNING] - [93m[get_loading_progress] retry:8, cost: 21.87s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:71)
[2022-12-22 14:54:25,247] [ WARNING] - [93m[get_loading_progress] retry:9, cost: 60.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:71)
[2022-12-22 14:55:25,249] [ WARNING] - [93m[get_loading_progress] retry:10, cost: 60.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (pymilvus.decorators:71)
[2022-12-22 14:56:25,334] [ WARNING] - [93mRetry run out of 10 retry times[0m (pymilvus.decorators:79)
[2022-12-22 14:56:25,335] [   ERROR] - RPC error: [get_loading_progress], <MilvusException: (code=1, message=Retry run out of 10 retry times, message=collection 438231170498953220 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-12-22 14:53:52.435344', 'RPC error': '2022-12-22 14:56:25.335746'}> (pymilvus.decorators:108)
[2022-12-22 14:56:25,336] [   ERROR] - RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=Retry run out of 10 retry times, message=collection 438231170498953220 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-12-22 14:53:51.932896', 'RPC error': '2022-12-22 14:56:25.336077'}> (pymilvus.decorators:108)
[2022-12-22 14:56:25,336] [   ERROR] - RPC error: [load_collection], <MilvusException: (code=1, message=Retry run out of 10 retry times, message=collection 438231170498953220 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-12-22 14:53:51.133483', 'RPC error': '2022-12-22 14:56:25.336151'}> (pymilvus.decorators:108)
[2022-12-22 14:56:25,338] [   ERROR] - Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 738, in get_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection 438231170498953220 has not been loaded to memory or load failed)>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 95, in run_suite
    result = runner.run_case(case_metric, **case)
  File "/src/milvus_benchmark/runners/search.py", line 716, in run_case
    self.milvus.load_collection(replica_number=replica_number, timeout=1200)
  File "/src/milvus_benchmark/client.py", line 53, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 592, in load_collection
    return self._milvus.load_collection(collection_name, **params)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/stub.py", line 193, in load_collection
    return handler.load_collection(collection_name, replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 659, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 677, in wait_for_loading_collection
    progress = self.get_loading_progress(collection_name, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 80, in handler
    raise MilvusException(e.code, f"{timeout_msg}, message={e.message}") from e
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry run out of 10 retry times, message=collection 438231170498953220 has not been loaded to memory or load failed)>
 (milvus_benchmark.main:98
```

### Steps To Reproduce

```markdown
1. create an collection
2. build ivfsq8 index
3. insert 10m data
4. build index again
5. Serial repetitive execution of load search release with load failure
```

**Comment by jingkl** [comment]
standalone memory
<img width="1382" alt="截屏2022-12-23 10 55 16" src="https://user-images.githubusercontent.com/34296482/209261690-8ad3708a-b2b7-4c44-a7f3-6b4a6086e419.png">

**Comment by sunby** [comment]
@jingkl Milvus restarted during loading collection and this collection is release automatically because it is not loaded successfully before crash. It is a expected behavior by design.

**Comment by yanliang567** [comment]
so, we need know why Milvus crashed during loading, also i think Milvus shall load the collection successfully after restarted. @sunby

**Comment by xiaofan-luan** [comment]
> @jingkl Milvus restarted during loading collection and this collection was released automatically because it was not loaded successfully before crash. It is a expected behavior by design.

Why did it crash? We've seen many crash cases in 2.2.X but I didn't find the failed reason

**Comment by sunby** [comment]
> > @jingkl Milvus restarted during loading collection and this collection was released automatically because it was not loaded successfully before crash. It is a expected behavior by design.
> 
> Why did it crash? We've seen many crash cases in 2.2.X but I didn't find the failed reason

Still investigating it.

**Comment by sunby** [comment]
QueryNode executes unsubscribe dmchannel task via creating a release collection. If we have two vchannel v0 and v1, when we call release collection, QueryCoord will generate two tasks that will release v0 and v1 separately. But QueryNode will release the collection when it received the release v0 request. And now QueryCoord will return release collection success. And the client then send a load request and QueryCoord will generate a watch dmchannel task. In QueryNode, the watch task and release v1 task is executed concurrently and the panic happened.
Try to fix it in https://github.com/milvus-io/milvus/pull/21513

**Comment by jingkl** [comment]
fouram-test-no-clean-fmk5x-1
server-configmap
server-single-8c16m
client-configmap
client-insert-load-search-sift10m-release
image:2.2.0-20230208-b83bbc04
pymilvus:2.2.2dev4
