### ISSUE TITLE
[Bug]: querycoord recovery panic 

### ISSUE THREAD

**Issue by jaime0815** [milvus-io/milvus#21409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.2
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

{"log":"[2022/12/15 11:20:28.766 +00:00] [INFO] [utils/meta.go:157] [\"get recovery info...\"] [collectionID=438061793391982518] [partitionID=438061793391982519]\n","stream":"stdout","time":"2022-12-15T11:20:28.766389593Z"}
{"log":"[2022/12/15 11:20:28.766 +00:00] [ERROR] [querycoordv2/server.go:526] [\"failed to get partitions from RootCoord\"] [error=\"ShowPartitions failed: code: CollectionNotExists, reason: can't find collection: 438061793391981922\"] [stack=\"github.com/milvus-io/milvus/internal/querycoordv2.(*Server).recoverCollectionTargets\\n\\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/server.go:526\\ngithub.com/milvus-io/milvus/internal/querycoordv2.(*Server).recover.func1\\n\\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/server.go:503\\ngolang.org/x/sync/errgroup.(*Group).Go.func1\\n\\t/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57\"]\n","stream":"stdout","time":"2022-12-15T11:20:28.766391341Z"}
{"log":"[2022/12/15 11:20:28.766 +00:00] [ERROR] [meta/coordinator_broker.go:128] [\"get recovery info failed\"] [collectionID=438061793391982518] [partitionID=438061793391982519] [error=\"context canceled\"] [stack=\"github.com/milvus-io/milvus/internal/querycoordv2/meta.(*CoordinatorBroker).GetRecoveryInfo\\n\\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/meta/coordinator_broker.go:128\\ngithub.com/milvus-io/milvus/internal/querycoordv2/utils.FetchTargets\\n\\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/utils/meta.go:160\\ngithub.com/milvus-io/milvus/internal/querycoordv2/utils.RegisterTargets\\n\\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/utils/meta.go:137\\ngithub.com/milvus-io/milvus/internal/querycoordv2.(*Server).recoverCollectionTargets\\n\\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/server.go:536\\ngithub.com/milvus-io/milvus/internal/querycoordv2.(*Server).recover.func1\\n\\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/server.go:503\\ngolang.org/x/sync/errgroup.(*Group).Go.func1\\n\\t/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57\"]\n","stream":"stdout","time":"2022-12-15T11:20:28.766458205Z"}
{"log":"panic: failed to get partitions from RootCoord[ShowPartitions failed: code: CollectionNotExists, reason: can't find collection: 438061793391982468]\n","stream":"stderr","time":"2022-12-15T11:20:28.768591201Z"}
{"log":"\n","stream":"stderr","time":"2022-12-15T11:20:28.768594067Z"}
{"log":"goroutine 257 [running]:\n","stream":"stderr","time":"2022-12-15T11:20:28.768595438Z"}
{"log":"panic({0x3990a60, 0xc006871300})\n","stream":"stderr","time":"2022-12-15T11:20:28.768596746Z"}
{"log":"\u0009/usr/local/go/src/runtime/panic.go:941 +0x397 fp=0xc001c61f20 sp=0xc001c61e60 pc=0x138d4f7\n","stream":"stderr","time":"2022-12-15T11:20:28.768597998Z"}
{"log":"github.com/milvus-io/milvus/cmd/components.(*QueryCoord).Run(0x56a11a0?)\n","stream":"stderr","time":"2022-12-15T11:20:28.768599545Z"}
{"log":"\u0009/go/src/github.com/milvus-io/milvus/cmd/components/query_coord.go:54 +0x56 fp=0xc001c61f58 sp=0xc001c61f20 pc=0x2e75f16\n","stream":"stderr","time":"2022-12-15T11:20:28.768601003Z"}
{"log":"github.com/milvus-io/milvus/cmd/roles.runComponent[...].func1()\n","stream":"stderr","time":"2022-12-15T11:20:28.768602486Z"}
{"log":"\u0009/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:102 +0x18e fp=0xc001c61fe0 sp=0xc001c61f58 pc=0x2e7850e\n","stream":"stderr","time":"2022-12-15T11:20:28.768603748Z"}
{"log":"runtime.goexit()\n","stream":"stderr","time":"2022-12-15T11:20:28.768605066Z"}
{"log":"\u0009/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc001c61fe8 sp=0xc001c61fe0 pc=0x13c2661\n","stream":"stderr","time":"2022-12-15T11:20:28.768607945Z"}

**Comment by xiaofan-luan** [comment]
@jaime0815 seems that the collection does not exist. How did we reproduce this issue? did we have detailed logs

**Comment by jaime0815** [comment]
it can be produced in VDC environment, [log link](https://grafana-vdc-dev.zilliz.cc/explore?orgId=1&left=%5B%221671062400000%22,%221671148799000%22,%22Loki-vdc%22,%7B%22refId%22:%22B%22,%22expr%22:%22%7Bcluster%3D%5C%22uat-test%5C%22,pod%3D%5C%22in01-2fba969278cea97-milvus-standalone-6c966fcf67-lnmqp%5C%22%7D%22,%22hide%22:false%7D%5D)

**Comment by yanliang567** [comment]
@longjiquan @jaime0815 any updates
