### ISSUE TITLE
[Bug]:[Nightly]Milvus crashed by reporting error 'Fail connecting to server ..'

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#21529]
## Environment
- Milvus version: 9a571c5
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.1.dev5
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others: 

## Current Behavior:
Milvus crashed by reporting error 'Fail connecting to server ..'
```
[2023-01-04T21:23:58.991Z] [2023-01-04 20:11:30 - ERROR - ci_test]: Traceback (most recent call last):
[2023-01-04T21:23:58.991Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 112, in _wait_for_channel_ready
[2023-01-04T21:23:58.991Z]     grpc.channel_ready_future(self._channel).result(timeout=timeout)
[2023-01-04T21:23:58.991Z]   File "/usr/local/lib/python3.8/site-packages/grpc/_utilities.py", line 139, in result
[2023-01-04T21:23:58.991Z]     self._block(timeout)
[2023-01-04T21:23:58.991Z]   File "/usr/local/lib/python3.8/site-packages/grpc/_utilities.py", line 85, in _block
[2023-01-04T21:23:58.991Z]     raise grpc.FutureTimeoutError()
[2023-01-04T21:23:58.991Z] grpc.FutureTimeoutError
[2023-01-04T21:23:58.991Z] 
[2023-01-04T21:23:58.991Z] The above exception was the direct cause of the following exception:
[2023-01-04T21:23:58.991Z] 
[2023-01-04T21:23:58.991Z] Traceback (most recent call last):
[2023-01-04T21:23:58.991Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2023-01-04T21:23:58.991Z]     res = func(*args, **_kwargs)
[2023-01-04T21:23:58.991Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2023-01-04T21:23:58.991Z]     return func(*arg, **kwargs)
[2023-01-04T21:23:58.991Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 303, in connect
[2023-01-04T21:23:58.991Z]     connect_milvus(**kwargs, user=user, password=password)
[2023-01-04T21:23:58.991Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 274, in connect_milvus
[2023-01-04T21:23:58.991Z]     gh._wait_for_channel_ready(timeout=timeout)
[2023-01-04T21:23:58.991Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 115, in _wait_for_channel_ready
[2023-01-04T21:23:58.991Z]     raise MilvusException(Status.CONNECT_FAILED,
[2023-01-04T21:23:58.991Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on mdp-54-n-milvus.milvus-ci:19530. Timeout)>
[2023-01-04T21:23:58.991Z]  (api_request.py:39)
[2023-01-04T21:23:58.991Z] [2023-01-04 20:11:30 - ERROR - ci_test]: (api_response) : <MilvusException: (code=2, message=Fail connecting to server on mdp-54-n-milvus.milvus-ci:19530. Timeout)> (api_request.py:40)
```

## Expected Behavior:
PASS

## Log:
artifacts-milvus-distributed-pulsar-nightly-54-pymilvus-e2e-logs.tar.gz

**Comment by NicoYuan1986** [comment]
log: [artifacts-milvus-distributed-pulsar-nightly-54-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/54/artifact/artifacts-milvus-distributed-pulsar-nightly-54-pymilvus-e2e-logs.tar.gz)

**Comment by binbinlv** [comment]
Running Links:
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/54/pipeline/188

**Comment by NicoYuan1986** [comment]
Latest: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/65/pipeline/124

milvus: 2.2.0(d475de4)
pymilvus: 2.2.1.dev5

1. log: [artifacts-milvus-standalone-nightly-65-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/65/artifact/artifacts-milvus-standalone-nightly-65-pymilvus-e2e-logs.tar.gz)
2. failed time: [2023-01-15T20:57:00.182Z] [gw2] [ 91%] FAILED testcases/test_utility.py::TestUtilityParams::test_has_partition_collection_name_invalid[get_invalid_collection_name0]

**Comment by NicoYuan1986** [comment]
Latest: https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/79/

milvus: 2.2.0(a4a20ee)
pymilvus: 2.2.2.dev3

1. log: [artifacts-milvus-distributed-pulsar-nightly-79-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/79/artifact/artifacts-milvus-distributed-pulsar-nightly-79-pymilvus-e2e-logs.tar.gz)
2. failed time: [2023-01-29T20:03:47.740Z] [gw0] [  5%] FAILED testcases/test_collection.py::TestCollectionParams::test_collection_shards_num_with_error_type

**Comment by NicoYuan1986** [comment]
Not reproduced recently.
