### ISSUE TITLE
[Bug]: Release collection timeout after kafka pod failure chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#21582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.2-20230105-b1c0b22a
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): kafka   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2023-01-08T23:38:48.098Z] [2023-01-08 23:36:41 - INFO - ci_test]: [test][2023-01-08T23:36:41Z] [0.27831502s] Hello_Milvus search -> <pymilvus.orm.search.SearchResult object at 0x7f7635bd1b80> (wrapper.py:30)

[2023-01-08T23:38:48.098Z] [2023-01-08 23:36:41 - INFO - ci_test]: assert search: 0.27851295471191406 (test_data_persistence.py:76)

[2023-01-08T23:38:48.098Z] [2023-01-08 23:36:41 - DEBUG - ci_test]: (api_request)  : [Collection.release] args: [], kwargs: {'timeout': 120} (api_request.py:56)

[2023-01-08T23:38:48.099Z] [2023-01-08 23:38:41 - ERROR - pymilvus.decorators]: RPC error: [release_collection], <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 120s)>, <Time:{'RPC start': '2023-01-08 23:36:41.463077', 'RPC error': '2023-01-08 23:38:41.463587'}> (decorators.py:108)

[2023-01-08T23:38:48.099Z] [2023-01-08 23:38:41 - ERROR - ci_test]: Traceback (most recent call last):

[2023-01-08T23:38:48.099Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-01-08T23:38:48.099Z]     return func(self, *args, **kwargs)

[2023-01-08T23:38:48.099Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 689, in release_collection

[2023-01-08T23:38:48.099Z]     response = rf.result()

[2023-01-08T23:38:48.099Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 744, in result

[2023-01-08T23:38:48.099Z]     raise self

[2023-01-08T23:38:48.099Z] grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:

[2023-01-08T23:38:48.099Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2023-01-08T23:38:48.099Z] 	details = "Deadline Exceeded"

[2023-01-08T23:38:48.099Z] 	debug_error_string = "{"created":"@1673221121.463177300","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":81,"grpc_status":4}"

[2023-01-08T23:38:48.099Z] >

[2023-01-08T23:38:48.099Z] 

[2023-01-08T23:38:48.099Z] The above exception was the direct cause of the following exception:

[2023-01-08T23:38:48.099Z] 

[2023-01-08T23:38:48.099Z] Traceback (most recent call last):

[2023-01-08T23:38:48.099Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2023-01-08T23:38:48.099Z]     res = func(*args, **_kwargs)

[2023-01-08T23:38:48.099Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2023-01-08T23:38:48.099Z]     return func(*arg, **kwargs)

[2023-01-08T23:38:48.099Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 384, in release

[2023-01-08T23:38:48.099Z]     conn.release_collection(self._name, timeout=timeout, **kwargs)

[2023-01-08T23:38:48.099Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-01-08T23:38:48.099Z]     raise e

[2023-01-08T23:38:48.099Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-01-08T23:38:48.099Z]     return func(*args, **kwargs)

[2023-01-08T23:38:48.099Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-01-08T23:38:48.099Z]     ret = func(self, *args, **kwargs)

[2023-01-08T23:38:48.099Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 64, in handler

[2023-01-08T23:38:48.099Z]     raise MilvusException(message=f"rpc deadline exceeded: {timeout_msg}") from e

[2023-01-08T23:38:48.099Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 120s)>

[2023-01-08T23:38:48.099Z]  (api_request.py:39)

[2023-01-08T23:38:48.099Z] [2023-01-08 23:38:41 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 120s)> (api_request.py:40)

[2023-01-08T23:38:48.099Z] ------------- generated html file: file:///tmp/ci_logs/report.html -------------

[2023-01-08T23:38:48.099Z] =========================== short test summary info ============================

[2023-01-08T23:38:48.099Z] FAILED testcases/test_data_persistence.py::TestDataPersistence::test_milvus_default - AssertionError

[2023-01-08T23:38:48.099Z] ======================== 1 failed in 124.71s (0:02:04) =========================
```

### Expected Behavior

all test cases passed

### Milvus Log

chaos type: pod-failure image tag: 2.2.2-20230105-b1c0b22a target pod: kafka
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-for-release-cron/detail/chaos-test-kafka-for-release-cron/1094/pipeline

log:
[artifacts-kafka-pod-failure-1094-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10370070/artifacts-kafka-pod-failure-1094-server-logs.tar.gz)
[artifacts-kafka-pod-failure-1094-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10370072/artifacts-kafka-pod-failure-1094-pytest-logs.tar.gz)

**Comment by smellthemoon** [comment]
> /assign @smellthemoon could you take a look into it

Ok, I will fix it.

**Comment by smellthemoon** [comment]
<img width="1109" alt="1" src="https://user-images.githubusercontent.com/64083300/212300751-f54f7524-630f-40c4-9e3e-b656f410bef0.png">
The release collection request at 07:36:46.
<img width="1151" alt="2" src="https://user-images.githubusercontent.com/64083300/212301186-554c38d2-101a-4af9-936a-f59e083e9aca.png">
But execute release collection task at 07:40:04.
Many LoadSegment tasks were enqueued, and the release task stucked in the queue , which is the reason of the timeout.

**Comment by smellthemoon** [comment]
see also #19951

**Comment by smellthemoon** [comment]
assign @zhuwenxing

**Comment by zhuwenxing** [comment]
close this issue due to duplicates with https://github.com/milvus-io/milvus/issues/19951
