### ISSUE TITLE
[Bug]: Datacoord crash after pulsar pod failure 

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#21581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230106-e1f72204
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2023/01/08 21:30:26.845 +00:00] [INFO] [management/server.go:68] ["management listen"] [addr=:9091]
[2023/01/08 21:30:26.951 +00:00] [INFO] [storage/minio_chunk_manager.go:134] ["minio chunk manager init success."] [bucketname=milvus-bucket] [root=file]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x24e6990]

goroutine 107 [running]:
panic({0x32e3500, 0x4da5030})
	/usr/local/go/src/runtime/panic.go:941 +0x397 fp=0xc0003ed580 sp=0xc0003ed4c0 pc=0x11d2cf7
runtime.panicmem(...)
	/usr/local/go/src/runtime/panic.go:220
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:818 +0x336 fp=0xc0003ed5d0 sp=0xc0003ed580 pc=0x11e9cd6
github.com/milvus-io/milvus/internal/datacoord.(*SegmentsInfo).SetSegmentIndex(...)
	/go/src/github.com/milvus-io/milvus/internal/datacoord/segment_info.go:102
github.com/milvus-io/milvus/internal/datacoord.(*meta).updateSegmentIndex(...)
	/go/src/github.com/milvus-io/milvus/internal/datacoord/index_meta.go:45
github.com/milvus-io/milvus/internal/datacoord.(*meta).reloadFromKV(0xc0007f6690)
	/go/src/github.com/milvus-io/milvus/internal/datacoord/meta.go:147 +0x970 fp=0xc0003ed840 sp=0xc0003ed5d0 pc=0x24e6990
github.com/milvus-io/milvus/internal/datacoord.newMeta({0x3a52910?, 0xc0007b5480}, {0x3a774d0?, 0xc00081ba40}, {0x3a71170?, 0xc00081b680})
	/go/src/github.com/milvus-io/milvus/internal/datacoord/meta.go:92 +0x1dd fp=0xc0003ed8b0 sp=0xc0003ed840 pc=0x24e5f9d
github.com/milvus-io/milvus/internal/datacoord.(*Server).initMeta.func1()
	/go/src/github.com/milvus-io/milvus/internal/datacoord/server.go:465 +0x127 fp=0xc0003ed930 sp=0xc0003ed8b0 pc=0x2506a27
github.com/milvus-io/milvus/internal/util/retry.Do({0x3a52910, 0xc0007b5480}, 0xc0003edb28, {0xc0003edb20, 0x1, 0x3a52910?})
	/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:37 +0x103 fp=0xc0003edac8 sp=0xc0003ed930 pc=0x1da8ae3
github.com/milvus-io/milvus/internal/datacoord.(*Server).initMeta(0xc000622c40, {0x3a71170, 0xc00081b680})
	/go/src/github.com/milvus-io/milvus/internal/datacoord/server.go:471 +0x176 fp=0xc0003edb60 sp=0xc0003edac8 pc=0x2506896
github.com/milvus-io/milvus/internal/datacoord.(*Server).Init(0xc000622c40)
	/go/src/github.com/milvus-io/milvus/internal/datacoord/server.go:272 +0xbf fp=0xc0003edc70 sp=0xc0003edb60 pc=0x25043ff
github.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).init(0xc000f4a120)
	/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:107 +0x502 fp=0xc0003edee8 sp=0xc0003edc70 pc=0x252b142
github.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).Run(0xb?)
	/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:215 +0x25 fp=0xc0003edf28 sp=0xc0003edee8 pc=0x252c805
github.com/milvus-io/milvus/cmd/components.(*DataCoord).Run(0xc0003fa500?)
	/go/src/github.com/milvus-io/milvus/cmd/components/data_coord.go:49 +0x1d fp=0xc0003edf60 sp=0xc0003edf28 pc=0x2ca621d
github.com/milvus-io/milvus/cmd/roles.runComponent[...].func1()
	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:89 +0x150 fp=0xc0003edfe0 sp=0xc0003edf60 pc=0x2ca9410
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0003edfe8 sp=0xc0003edfe0 pc=0x1207fa1
created by github.com/milvus-io/milvus/cmd/roles.runComponent[...]
	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:76 +0x12f

```

```
[2023-01-08T21:31:47.109Z] + kubectl get pods -o wide

[2023-01-08T21:31:47.109Z] + grep pulsar-pod-failure-1145

[2023-01-08T21:31:47.363Z] pulsar-pod-failure-1145-bookie-0                                  1/1     Running            0               14m     10.102.7.106    devops-node11   <none>           <none>

[2023-01-08T21:31:47.363Z] pulsar-pod-failure-1145-bookie-1                                  1/1     Running            0               14m     10.102.9.54     devops-node13   <none>           <none>

[2023-01-08T21:31:47.363Z] pulsar-pod-failure-1145-bookie-init-xnwzf                         0/1     Completed          0               14m     10.102.7.57     devops-node11   <none>           <none>

[2023-01-08T21:31:47.363Z] pulsar-pod-failure-1145-broker-0                                  1/1     Running            4 (5m20s ago)   14m     10.102.7.60     devops-node11   <none>           <none>

[2023-01-08T21:31:47.363Z] pulsar-pod-failure-1145-etcd-0                                    1/1     Running            0               14m     10.102.7.110    devops-node11   <none>           <none>

[2023-01-08T21:31:47.363Z] pulsar-pod-failure-1145-etcd-1                                    1/1     Running            0               14m     10.102.9.55     devops-node13   <none>           <none>

[2023-01-08T21:31:47.363Z] pulsar-pod-failure-1145-etcd-2                                    1/1     Running            0               14m     10.102.6.152    devops-node10   <none>           <none>

[2023-01-08T21:31:47.363Z] pulsar-pod-failure-1145-milvus-datacoord-8598b47949-nwk78         0/1     CrashLoopBackOff   6 (77s ago)     14m     10.102.7.54     devops-node11   <none>           <none>

[2023-01-08T21:31:47.363Z] pulsar-pod-failure-1145-milvus-datanode-8c5cc6d5d-5lz8x           0/1     Running            2 (71s ago)     14m     10.102.9.39     devops-node13   <none>           <none>

[2023-01-08T21:31:47.363Z] pulsar-pod-failure-1145-milvus-datanode-8c5cc6d5d-mpb6x           0/1     Running            2 (64s ago)     14m     10.102.7.47     devops-node11   <none>           <none>

[2023-01-08T21:31:47.364Z] pulsar-pod-failure-1145-milvus-indexcoord-869cd9f484-kj8ml        1/1     Running            0               14m     10.102.7.48     devops-node11   <none>           <none>

[2023-01-08T21:31:47.364Z] pulsar-pod-failure-1145-milvus-indexnode-79bbdbfbf9-v5mpg         1/1     Running            0               14m     10.102.7.52     devops-node11   <none>           <none>

[2023-01-08T21:31:47.364Z] pulsar-pod-failure-1145-milvus-proxy-86767cf9d6-tqlzr             1/1     Running            1 (10m ago)     14m     10.102.7.46     devops-node11   <none>           <none>

[2023-01-08T21:31:47.364Z] pulsar-pod-failure-1145-milvus-querycoord-6957b9cb55-zkdfb        1/1     Running            1 (9m57s ago)   14m     10.102.7.49     devops-node11   <none>           <none>

[2023-01-08T21:31:47.364Z] pulsar-pod-failure-1145-milvus-querynode-76dfccc59c-h6ch4         1/1     Running            1 (4m37s ago)   14m     10.102.9.41     devops-node13   <none>           <none>

[2023-01-08T21:31:47.364Z] pulsar-pod-failure-1145-milvus-querynode-76dfccc59c-j84n6         1/1     Running            0               14m     10.102.5.123    devops-node21   <none>           <none>

[2023-01-08T21:31:47.364Z] pulsar-pod-failure-1145-milvus-querynode-76dfccc59c-z2btq         1/1     Running            1 (4m35s ago)   14m     10.102.7.55     devops-node11   <none>           <none>

[2023-01-08T21:31:47.364Z] pulsar-pod-failure-1145-milvus-rootcoord-7666d6c68f-hr42r         1/1     Running            1 (9m42s ago)   14m     10.102.7.56     devops-node11   <none>           <none>

[2023-01-08T21:31:47.364Z] pulsar-pod-failure-1145-minio-0                                   1/1     Running            0               14m     10.102.7.101    devops-node11   <none>           <none>

[2023-01-08T21:31:47.364Z] pulsar-pod-failure-1145-minio-1                                   1/1     Running            0               14m     10.102.9.43     devops-node13   <none>           <none>

[2023-01-08T21:31:47.364Z] pulsar-pod-failure-1145-minio-2                                   1/1     Running            0               14m     10.102.6.144    devops-node10   <none>           <none>

[2023-01-08T21:31:47.364Z] pulsar-pod-failure-1145-minio-3                                   1/1     Running            0               14m     10.102.10.190   devops-node20   <none>           <none>

[2023-01-08T21:31:47.364Z] pulsar-pod-failure-1145-proxy-0                                   1/1     Running            0               14m     10.102.7.58     devops-node11   <none>           <none>

[2023-01-08T21:31:47.364Z] pulsar-pod-failure-1145-pulsar-init-6476r                         0/1     Completed          0               14m     10.102.7.50     devops-node11   <none>           <none>

[2023-01-08T21:31:47.364Z] pulsar-pod-failure-1145-recovery-0                                1/1     Running            0               14m     10.102.7.53     devops-node11   <none>           <none>

[2023-01-08T21:31:47.364Z] pulsar-pod-failure-1145-zookeeper-0                               1/1     Running            0               14m     10.102.7.103    devops-node11   <none>           <none>
```

### Expected Behavior

all pods are ready and healthy

### Milvus Log

chaos type: pod-failure image tag: master-20230106-e1f72204 target pod: pulsar

[artifacts-pulsar-pod-failure-1145-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/10370033/artifacts-pulsar-pod-failure-1145-server-logs.1.tar.gz)
[artifacts-pulsar-pod-failure-1145-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10370034/artifacts-pulsar-pod-failure-1145-pytest-logs.tar.gz)

**Comment by xiaofan-luan** [comment]
/assign @aoiasd 
pls take a look into it

**Comment by yanliang567** [comment]
@zhuwenxing @aoiasd any updates

**Comment by zhuwenxing** [comment]
This issue still happened, but the panic reason changed
```
datanode.newDmInputNode\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_dmstream_input_node.go:48\ngithub.com/milvus-io/milvus/internal/datanode.(*dataSyncService).initNodes\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/data_sync_service.go:303\ngithub.com/milvus-io/milvus/internal/datanode.newDataSyncService\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/data_sync_service.go:122\ngithub.com/milvus-io/milvus/internal/datanode.(*flowgraphManager).addAndStart\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_manager.go:50\ngithub.com/milvus-io/milvus/internal/datanode.(*DataNode).handlePutEvent\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/data_node.go:424\ngithub.com/milvus-io/milvus/internal/datanode.(*channelEventManager).Run.func1\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:72"]
[2023/02/28 21:34:48.341 +00:00] [INFO] [datanode/flow_graph_dd_node.go:394] ["datanode AsProducer"] [DeltaChannelName=by-dev-rootcoord-delta_26]
panic: Failed to create consumer by-dev-rootcoord-dml_27, error = All attempts results:
attempt #1:server error: ConsumerBusy: Exclusive consumer is already connected


goroutine 33848 [running]:
panic({0x335f240, 0xc000191f80})
	/usr/local/go/src/runtime/panic.go:941 +0x397 fp=0xc002c88148 sp=0xc002c88088 pc=0x124ccf7
github.com/milvus-io/milvus/internal/mq/msgstream.(*MqTtMsgStream).AsConsumer(0xc00608cd00, {0xc0024d8b80?, 0x1, 0x0?}, {0xc00023e380, 0x3e}, 0x2)
	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_msgstream.go:533 +0x285 fp=0xc002c88238 sp=0xc002c88148 pc=0x254f965
github.com/milvus-io/milvus/internal/mq/msgdispatcher.NewDispatcher({0x7fdef67692e0, 0xc000f94ae0}, 0x0, {0xc00169cc30, 0x17}, 0xc003ab3a40, {0xc00023e380, 0x3e}, 0x203001?, 0xc002e62180, ...)
	/go/src/github.com/milvus-io/milvus/internal/mq/msgdispatcher/dispatcher.go:97 +0x404 fp=0xc002c88500 sp=0xc002c88238 pc=0x26a11c4
github.com/milvus-io/milvus/internal/mq/msgdispatcher.(*dispatcherManager).Add(0xc001696090, {0xc0016f8270, 0x2c}, 0xc003ab3a40, 0x0?)
	/go/src/github.com/milvus-io/milvus/internal/mq/msgdispatcher/manager.go:95 +0x47f fp=0xc002c886e0 sp=0xc002c88500 pc=0x26a3bdf
github.com/milvus-io/milvus/internal/mq/msgdispatcher.(*client).Register(0xc000fc7a80, {0xc0016f8270, 0x2c}, 0x335f4c0?, 0xc000143a01?)
	/go/src/github.com/milvus-io/milvus/internal/mq/msgdispatcher/client.go:73 +0x4d0 fp=0xc002c88908 sp=0xc002c886e0 pc=0x26a04d0
github.com/milvus-io/milvus/internal/datanode.newDmInputNode({0x3c39658, 0xc000fc7a80}, 0xc003ab3a40, 0xc0036778c0)
	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_dmstream_input_node.go:48 +0x2e6 fp=0xc002c88b90 sp=0xc002c88908 pc=0x286a6c6
github.com/milvus-io/milvus/internal/datanode.(*dataSyncService).initNodes(0xc00218a600, 0xc00218a500, 0xc003ab3b60)
	/go/src/github.com/milvus-io/milvus/internal/datanode/data_sync_service.go:303 +0x1a98 fp=0xc002c89798 sp=0xc002c88b90 pc=0x285f758
github.com/milvus-io/milvus/internal/datanode.newDataSyncService({0x3c4c150?, 0xc000fc6340?}, 0xc001502000, 0xc003ab3bc0, {0x3c7a4e0, 0xc00225e630}, {0x3c42600?, 0xc003c38a80}, {0x3c39658, 0xc000fc7a80}, ...)
	/go/src/github.com/milvus-io/milvus/internal/datanode/data_sync_service.go:122 +0x419 fp=0xc002c89808 sp=0xc002c89798 pc=0x285d339
github.com/milvus-io/milvus/internal/datanode.(*flowgraphManager).addAndStart(0xc000f94ba0, 0xc00030d7c0, 0xc00218a500, 0x1?, 0x1?)
	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_manager.go:50 +0x413 fp=0xc002c89a88 sp=0xc002c89808 pc=0x2872813
github.com/milvus-io/milvus/internal/datanode.(*DataNode).handlePutEvent(0xc00030d7c0, 0xc0035ead20, 0x1)
	/go/src/github.com/milvus-io/milvus/internal/datanode/data_node.go:424 +0x338 fp=0xc002c89ef8 sp=0xc002c89a88 pc=0x285abf8
github.com/milvus-io/milvus/internal/datanode.(*DataNode).handlePutEvent-fm(0xc000574760?, 0xc000574750?)
	<autogenerated>:1 +0x2f fp=0xc002c89f20 sp=0xc002c89ef8 pc=0x288f3ef
github.com/milvus-io/milvus/internal/datanode.(*channelEventManager).Run.func1()
	/go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:72 +0x128 fp=0xc002c89fe0 sp=0xc002c89f20 pc=0x2862348
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc002c89fe8 sp=0xc002c89fe0 pc=0x12820c1
created by github.com/milvus-io/milvus/internal/datanode.(*channelEventManager).Run
	/go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:66 +0x56
```

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/2389/pipeline
log:
[artifacts-pulsar-pod-failure-2389-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/10856806/artifacts-pulsar-pod-failure-2389-server-logs.1.tar.gz)

[artifacts-pulsar-pod-failure-2389-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10856807/artifacts-pulsar-pod-failure-2389-pytest-logs.tar.gz)
