### ISSUE TITLE
[Bug]: Load timeout when running `test_e2e.py` when standby mode is on

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#21593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:wayblink-mep-30-debug-2.2-ce6092e-20230106
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka): pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus==2.3.0.dev21
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2023-01-09T10:12:22.046Z] [2023-01-09 10:10:15 - INFO - ci_test]: [test][2023-01-09T10:10:12Z] [3.23144492s] e2e__8NtZY6IA create_index -> Status(code=0, message=) (wrapper.py:30)

[2023-01-09T10:12:22.046Z] [2023-01-09 10:10:15 - INFO - ci_test]: assert index: 5.260945558547974 (test_e2e.py:53)

[2023-01-09T10:12:22.046Z] [2023-01-09 10:10:15 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:56)

[2023-01-09T10:12:22.046Z] [2023-01-09 10:12:16 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=wait for loading collection timeout, collection: e2e__8NtZY6IA)>, <Time:{'RPC start': '2023-01-09 10:10:16.197175', 'RPC error': '2023-01-09 10:12:16.522771'}> (decorators.py:108)

[2023-01-09T10:12:22.046Z] [2023-01-09 10:12:16 - WARNING - pymilvus.decorators]: Retry timeout: 120s (decorators.py:79)

[2023-01-09T10:12:22.046Z] [2023-01-09 10:12:16 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: e2e__8NtZY6IA)>, <Time:{'RPC start': '2023-01-09 10:10:15.313433', 'RPC error': '2023-01-09 10:12:16.523750'}> (decorators.py:108)

[2023-01-09T10:12:22.046Z] [2023-01-09 10:12:16 - ERROR - ci_test]: Traceback (most recent call last):

[2023-01-09T10:12:22.046Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-01-09T10:12:22.046Z]     return func(self, *args, **kwargs)

[2023-01-09T10:12:22.046Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 660, in load_collection

[2023-01-09T10:12:22.046Z]     self.wait_for_loading_collection(collection_name, timeout)

[2023-01-09T10:12:22.046Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-01-09T10:12:22.046Z]     raise e

[2023-01-09T10:12:22.046Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-01-09T10:12:22.046Z]     return func(*args, **kwargs)

[2023-01-09T10:12:22.046Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-01-09T10:12:22.046Z]     ret = func(self, *args, **kwargs)

[2023-01-09T10:12:22.046Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-01-09T10:12:22.046Z]     raise e

[2023-01-09T10:12:22.046Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-01-09T10:12:22.046Z]     return func(self, *args, **kwargs)

[2023-01-09T10:12:22.046Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 682, in wait_for_loading_collection

[2023-01-09T10:12:22.046Z]     raise MilvusException(message=f"wait for loading collection timeout, collection: {collection_name}")

[2023-01-09T10:12:22.046Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=wait for loading collection timeout, collection: e2e__8NtZY6IA)>

[2023-01-09T10:12:22.046Z] 

[2023-01-09T10:12:22.046Z] The above exception was the direct cause of the following exception:

[2023-01-09T10:12:22.046Z] 

[2023-01-09T10:12:22.046Z] Traceback (most recent call last):

[2023-01-09T10:12:22.046Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2023-01-09T10:12:22.046Z]     res = func(*args, **_kwargs)

[2023-01-09T10:12:22.046Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2023-01-09T10:12:22.046Z]     return func(*arg, **kwargs)

[2023-01-09T10:12:22.046Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 361, in load

[2023-01-09T10:12:22.046Z]     conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)

[2023-01-09T10:12:22.046Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-01-09T10:12:22.046Z]     raise e

[2023-01-09T10:12:22.046Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-01-09T10:12:22.046Z]     return func(*args, **kwargs)

[2023-01-09T10:12:22.046Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-01-09T10:12:22.046Z]     ret = func(self, *args, **kwargs)

[2023-01-09T10:12:22.046Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 80, in handler

[2023-01-09T10:12:22.046Z]     raise MilvusException(e.code, f"{timeout_msg}, message={e.message}") from e

[2023-01-09T10:12:22.046Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: e2e__8NtZY6IA)>

[2023-01-09T10:12:22.046Z]  (api_request.py:39)

[2023-01-09T10:12:22.046Z] [2023-01-09 10:12:16 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: e2e__8NtZY6IA)> (api_request.py:40)

[2023-01-09T10:12:22.046Z] ------------- generated html file: file:///tmp/ci_logs/report.html -------------

[2023-01-09T10:12:22.046Z] =========================== short test summary info ============================

[2023-01-09T10:12:22.046Z] FAILED ../testcases/test_e2e.py::TestE2e::test_milvus_default - AssertionError

[2023-01-09T10:12:22.046Z] ======================== 1 failed in 130.28s (0:02:10) =========================
```

### Expected Behavior

test case passed

### Milvus Log

chaos type: pod-failure image tag: wayblink-mep-30-debug-2.2-ce6092e-20230106 target pod: rootcoord
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/standby_test/detail/standby_test/4/pipeline

log:
[artifacts-rootcoord-pod-failure-4-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10372592/artifacts-rootcoord-pod-failure-4-server-logs.tar.gz)
[artifacts-rootcoord-pod-failure-4-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10372593/artifacts-rootcoord-pod-failure-4-pytest-logs.tar.gz)

**Comment by yanliang567** [comment]
/assign @jiaoew1991 
unassign

**Comment by wayblink** [comment]
@zhuwenxing hi, please help check whether this issue still exist

**Comment by zhuwenxing** [comment]
verified and passed with `2.2.0-20230207-e3501f7a`
