### ISSUE TITLE
[Bug]: Search failed with error `err=LackSegment(segmentID=438635988139838921)` when standby mode is on

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#21607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230109-7b12865c
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka): pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus==2.3.0.dev21
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2023-01-09T11:27:47.205Z] [2023-01-09 11:27:24 - INFO - ci_test]: [test][2023-01-09T11:27:20Z] [3.52814004s] Hello_Milvus load -> None (wrapper.py:30)

[2023-01-09T11:27:47.205Z] [2023-01-09 11:27:24 - INFO - ci_test]: assert load: 3.5283122062683105 (test_data_persistence.py:89)

[2023-01-09T11:27:47.205Z] [2023-01-09 11:27:24 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.04224458910813775, 0.12182133081705956, 0.1448920846555463, 0.025928506063524197, 0.02434470743558359, 0.013112335812097049, 0.08888766320653563, 0.06905261837051943, 0.1306925723238217, 0.047793243612755776, 0.043331834939028244, 0.10021279428000637, 0.04925405229443544, 0.042754203095455856, ......, kwargs: {} (api_request.py:56)

[2023-01-09T11:27:47.205Z] [2023-01-09 11:27:44 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:

[2023-01-09T11:27:47.205Z] attempt #1:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_2_438635988139838870v0 is not available in any replica, err=LackSegment(segmentID=438635988139838921)

[2023-01-09T11:27:47.205Z] attempt #2:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_2_438635988139838870v0 is not available in any replica, err=LackSegment(segmentID=438635988139838921)

[2023-01-09T11:27:47.205Z] attempt #3:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_2_438635988139838870v0 is not available in any replica, err=LackSegment(segmentID=438635988139838921)

[2023-01-09T11:27:47.205Z] attempt #4:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_2_438635988139838870v0 is not available in any replica, err=LackSegment(segmentID=438635988139838921)

[2023-01-09T11:27:47.205Z] attempt #5:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_3_438635988139838870v1 is not available in any replica, err=LackSegment(segmentID=438635988139838922)

[2023-01-09T11:27:47.205Z] attempt #6:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_2_438635988139838870v0 is not available in any replica, err=LackSegment(segmentID=438635988139838921)

[2023-01-09T11:27:47.205Z] attempt #7:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_2_438635988139838870v0 is not available in any replica, err=LackSegment(segmentID=438635988139838921)

[2023-01-09T11:27:47.205Z] attempt #8:context deadline exceeded

[2023-01-09T11:27:47.205Z] )>, <Time:{'RPC start': '2023-01-09 11:27:24.495910', 'RPC error': '2023-01-09 11:27:44.499612'}> (decorators.py:108)

[2023-01-09T11:27:47.205Z] [2023-01-09 11:27:44 - ERROR - ci_test]: Traceback (most recent call last):

[2023-01-09T11:27:47.205Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2023-01-09T11:27:47.205Z]     res = func(*args, **_kwargs)

[2023-01-09T11:27:47.205Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2023-01-09T11:27:47.205Z]     return func(*arg, **kwargs)

[2023-01-09T11:27:47.205Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 609, in search

[2023-01-09T11:27:47.205Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,

[2023-01-09T11:27:47.205Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-01-09T11:27:47.205Z]     raise e

[2023-01-09T11:27:47.205Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-01-09T11:27:47.205Z]     return func(*args, **kwargs)

[2023-01-09T11:27:47.205Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-01-09T11:27:47.205Z]     ret = func(self, *args, **kwargs)

[2023-01-09T11:27:47.205Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-01-09T11:27:47.205Z]     raise e

[2023-01-09T11:27:47.205Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-01-09T11:27:47.205Z]     return func(self, *args, **kwargs)

[2023-01-09T11:27:47.205Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 470, in search

[2023-01-09T11:27:47.205Z]     return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)

[2023-01-09T11:27:47.205Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 439, in _execute_search_requests

[2023-01-09T11:27:47.205Z]     raise pre_err

[2023-01-09T11:27:47.205Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 430, in _execute_search_requests

[2023-01-09T11:27:47.205Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2023-01-09T11:27:47.205Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:

[2023-01-09T11:27:47.205Z] attempt #1:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_2_438635988139838870v0 is not available in any replica, err=LackSegment(segmentID=438635988139838921)

[2023-01-09T11:27:47.205Z] attempt #2:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_2_438635988139838870v0 is not available in any replica, err=LackSegment(segmentID=438635988139838921)

[2023-01-09T11:27:47.205Z] attempt #3:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_2_438635988139838870v0 is not available in any replica, err=LackSegment(segmentID=438635988139838921)

[2023-01-09T11:27:47.205Z] attempt #4:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_2_438635988139838870v0 is not available in any replica, err=LackSegment(segmentID=438635988139838921)

[2023-01-09T11:27:47.205Z] attempt #5:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_3_438635988139838870v1 is not available in any replica, err=LackSegment(segmentID=438635988139838922)

[2023-01-09T11:27:47.205Z] attempt #6:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_2_438635988139838870v0 is not available in any replica, err=LackSegment(segmentID=438635988139838921)

[2023-01-09T11:27:47.205Z] attempt #7:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_2_438635988139838870v0 is not available in any replica, err=LackSegment(segmentID=438635988139838921)

[2023-01-09T11:27:47.206Z] attempt #8:context deadline exceeded

[2023-01-09T11:27:47.206Z] )>

[2023-01-09T11:27:47.206Z]  (api_request.py:39)

[2023-01-09T11:27:47.206Z] [2023-01-09 11:27:44 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:

[2023-01-09T11:27:47.206Z] attempt #1:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_2_438635988139838870v0 is not available in any replica, err=LackSegment(segmentID=438635988139838921)

[2023-01-09T11:27:47.206Z] attempt #2:fail t...... (api_request.py:40)

[2023-01-09T11:27:47.206Z] ------------- generated html file: file:///tmp/ci_logs/report.html -------------

[2023-01-09T11:27:47.206Z] =========================== short test summary info ============================

[2023-01-09T11:27:47.206Z] FAILED testcases/test_data_persistence.py::TestDataPersistence::test_milvus_default - AssertionError

[2023-01-09T11:27:47.206Z] ============================== 1 failed in 39.43s ==============================
```

### Expected Behavior

all test cases passed

### Milvus Log

chaos type: pod-failure image tag: 2.2.0-20230109-7b12865c target pod: rootcoord

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/standby_test/detail/standby_test/7/pipeline
log:
the log is not exported, please go to Loki

release name: rootcoord-pod-failure-7

**Comment by zhuwenxing** [comment]
It is not a stable issue! For now, only happened once.

**Comment by zhuwenxing** [comment]
Not reproduced recently
Verified and passed in version `2.2.0-20230117-f081c3c6`
