### ISSUE TITLE
[Bug]: [Nightly]Load collection with wrong replica_number type raised unexcepted error

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#21618]
## Environment
- Milvus version: 23ceb9c
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): kafka
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.0.dev21
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others: 

## Current Behavior:
Load collection with wrong replica_number type raised unexcepted error.
```
[2023-01-09T19:20:09.988Z] [2023-01-09 18:02:14 - ERROR - pymilvus.decorators]: Unexcepted error: [load_collection], [1, '2', 3] has type list, but expected one of: int, <Time: {'RPC start': '2023-01-09 18:02:14.072980', 'Exception': '2023-01-09 18:02:14.073041'}> (decorators.py:120)
[2023-01-09T19:20:09.988Z] [2023-01-09 18:02:14 - ERROR - ci_test]: Traceback (most recent call last):
[2023-01-09T19:20:09.988Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2023-01-09T19:20:09.988Z]     res = func(*args, **_kwargs)
[2023-01-09T19:20:09.988Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2023-01-09T19:20:09.988Z]     return func(*arg, **kwargs)
[2023-01-09T19:20:09.988Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 361, in load
[2023-01-09T19:20:09.988Z]     conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
[2023-01-09T19:20:09.988Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 121, in handler
[2023-01-09T19:20:09.988Z]     raise e
[2023-01-09T19:20:09.988Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2023-01-09T19:20:09.988Z]     return func(*args, **kwargs)
[2023-01-09T19:20:09.988Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2023-01-09T19:20:09.988Z]     ret = func(self, *args, **kwargs)
[2023-01-09T19:20:09.988Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 87, in handler
[2023-01-09T19:20:09.988Z]     raise e
[2023-01-09T19:20:09.988Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2023-01-09T19:20:09.988Z]     return func(self, *args, **kwargs)
[2023-01-09T19:20:09.988Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 653, in load_collection
[2023-01-09T19:20:09.988Z]     request = Prepare.load_collection("", collection_name, replica_number)
[2023-01-09T19:20:09.988Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/prepare.py", line 547, in load_collection
[2023-01-09T19:20:09.988Z]     return milvus_types.LoadCollectionRequest(db_name=db_name, collection_name=collection_name,
[2023-01-09T19:20:09.988Z] TypeError: [1, '2', 3] has type list, but expected one of: int
[2023-01-09T19:20:09.988Z]  (api_request.py:39)
[2023-01-09T19:20:09.988Z] [2023-01-09 18:02:14 - ERROR - ci_test]: (api_response) : [1, '2', 3] has type list, but expected one of: int (api_request.py:40)
```

## Expected Behavior:
raise MilvusException as expected: err_code: 0, expected one of: int, long

## Test Report:
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/247/pipeline/171/

**Comment by NicoYuan1986** [comment]
Failed cases:
test_load_partition_replica_non_number
test_load_replica_non_number
Take one for example: test_load_replica_non_number[get_non_number_replicas2]
1. log: [artifacts-milvus-distributed-kafka-nightly-247-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/247/artifact/artifacts-milvus-distributed-kafka-nightly-247-pymilvus-e2e-logs.tar.gz)
2. collection name: collection_LPtZZJI4
3. failed time: [2023-01-09T18:02:14.852Z] [gw2] [  8%] FAILED testcases/test_collection.py::TestLoadCollection::test_load_replica_non_number[get_non_number_replicas2]

**Comment by yanliang567** [comment]
sounds like a pymilvus issue? 
/assign @XuanYang-cn 
/unassign

**Comment by XuanYang-cn** [comment]
![image](https://user-images.githubusercontent.com/51370125/212592579-a7063c74-b7f4-42ad-8ae5-5eecc971b54f.png)

**Comment by XuanYang-cn** [comment]
pymilvus-2.3.0.dev24

/unassign
/assign @NicoYuan1986 @binbinlv

**Comment by binbinlv** [comment]
@NicoYuan1986 

could you please verify if it is fixed, thanks.

**Comment by NicoYuan1986** [comment]
I tried to update pymilvus to 2.3.0.dev24. But it disappeared another error. 
```
[2023-01-18 17:10:01 - ERROR - pymilvus.decorators]: Unexpected error: [load_partitions], Cannot set milvus.proto.milvus.LoadPartitionsRequest.replica_number to []: [] has type <class 'list'>, but expected one of: (<class 'int'>,) for field LoadPartitionsRequest.replica_number, <Time: {'RPC start': '2023-01-18 17:10:01.562969', 'Exception': '2023-01-18 17:10:01.563130'}> (decorators.py:120)
[2023-01-18 17:10:01 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/google/protobuf/internal/python_message.py", line 702, in field_setter
    new_value = type_checker.CheckValue(new_value)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/google/protobuf/internal/type_checkers.py", line 167, in CheckValue
    raise TypeError(message)
TypeError: [] has type <class 'list'>, but expected one of: (<class 'int'>,)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/google/protobuf/internal/python_message.py", line 558, in init
    setattr(self, field_name, field_value)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/google/protobuf/internal/python_message.py", line 704, in field_setter
    raise TypeError(
TypeError: Cannot set milvus.proto.milvus.LoadPartitionsRequest.replica_number to []: [] has type <class 'list'>, but expected one of: (<class 'int'>,)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 87, in handler
    raise e
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 697, in load_partitions
    request = Prepare.load_partitions("", collection_name, partition_names, replica_number)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/client/prepare.py", line 564, in load_partitions
    return milvus_types.LoadPartitionsRequest(db_name=db_name, collection_name=collection_name,
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/google/protobuf/internal/python_message.py", line 560, in init
    _ReraiseTypeErrorWithFieldName(message_descriptor.name, field_name)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/google/protobuf/internal/python_message.py", line 477, in _ReraiseTypeErrorWithFieldName
    raise exc.with_traceback(sys.exc_info()[2])
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/google/protobuf/internal/python_message.py", line 558, in init
    setattr(self, field_name, field_value)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/google/protobuf/internal/python_message.py", line 704, in field_setter
    raise TypeError(
TypeError: Cannot set milvus.proto.milvus.LoadPartitionsRequest.replica_number to []: [] has type <class 'list'>, but expected one of: (<class 'int'>,) for field LoadPartitionsRequest.replica_number

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zilliz/nico/milvus/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/Users/zilliz/nico/milvus/tests/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/orm/partition.py", line 222, in load
    return conn.load_partitions(self._collection.name, [self._name], replica_number, timeout=timeout, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 121, in handler
    raise MilvusException(message=f"Unexpected error, message=<{e.message}>") from e
AttributeError: 'TypeError' object has no attribute 'message'
 (api_request.py:39)
[2023-01-18 17:10:01 - ERROR - ci_test]: (api_response) : 'TypeError' object has no attribute 'message' (api_request.py:40)
```
It seems like a protobuf error.

**Comment by binbinlv** [comment]
@XuanYang-cn 
could you please have a look again, thank.

**Comment by NicoYuan1986** [comment]
Verified fixed.
milvus: master-20230129-66027790
Load with replica number none will raise exception now.
Load with replica number -1, 0 will succeed as replica number=1
