### ISSUE TITLE
[Bug]: Search, query and create index can not recovery after querycoord pod failure is injected into activated querycoord, and it seems that standby querycoord is not changed to activated

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#21610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230109-7b12865c
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka): pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.3.0.dev21
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

before pod failure chaos
```
[2023-01-10T02:28:32.307Z] [2023-01-10 02:27:19 - INFO - root]: activated pod list: ['querycoord-pod-failure-12-milvus-querycoord-598cd8cff4-cdw25'], standby pod list: ['querycoord-pod-failure-12-milvus-querycoord-598cd8cff4-7sgsh'] (test_chaos_apply_to_coord.py:64)
```
after pod failure chaos
```
[2023-01-10T02:28:32.312Z] [2023-01-10 02:28:30 - INFO - root]: activated pod list: ['querycoord-pod-failure-12-milvus-querycoord-598cd8cff4-cdw25'], standby pod list: ['querycoord-pod-failure-12-milvus-querycoord-598cd8cff4-7sgsh'] (test_chaos_apply_to_coord.py:131)
```

![image](https://user-images.githubusercontent.com/12268675/211452023-821adea3-3093-4a98-85c7-e37bb8147ee1.png)

```
[2023-01-10T02:31:17.376Z] [2023-01-10 02:31:17 - INFO - ci_test]: QueryChecker, succ_rate: 0.75, total: 136, average_time: 0.2132, max_time: 0.3998, min_time: 0.1830 (checker.py:127)
```

```
[2023-01-10T02:31:17.376Z] [2023-01-10 02:31:17 - INFO - ci_test]: SearchChecker, succ_rate: 0.73, total: 139, average_time: 0.2135, max_time: 0.4019, min_time: 0.1844 (checker.py:127)
```

```
[2023-01-10T02:31:17.375Z] [2023-01-10 02:31:17 - INFO - ci_test]: IndexChecker, succ_rate: 0.50, total: 113, average_time: 4.3180, max_time: 7.2462, min_time: 0.5150 (checker.py:127)
```

### Milvus Log

chaos type: pod-failure image tag: 2.2.0-20230109-7b12865c target pod: querycoord

failed job:https://qa-jenkins.milvus.io/blue/organizations/jenkins/standby_test/detail/standby_test/12/pipeline
log:
[artifacts-querycoord-pod-failure-12-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10378600/artifacts-querycoord-pod-failure-12-pytest-logs.tar.gz)

[artifacts-querycoord-pod-failure-12-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10378602/artifacts-querycoord-pod-failure-12-server-logs.tar.gz)

**Comment by zhuwenxing** [comment]
In another run, standby querycoord is changed to activated after chaos, but query and search still do not work.
And after chaos, some test cases failed with error 
```
[2023-01-10T03:08:35.553Z] [2023-01-10 03:06:28 - INFO - ci_test]: assert flush: 3.030381202697754, entities: 9000 (test_data_persistence.py:45)

[2023-01-10T03:08:35.553Z] [2023-01-10 03:06:28 - INFO - ci_test]: index info: [{'collection': 'Hello_Milvus', 'field': 'float_vector', 'index_name': 'test_7cvNz9XI', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}, {'collection': 'Hello_Milvus', 'field': 'varchar', 'index_name': 'test_jLhS1WiO', 'index_param': {'index_type': 'Trie'}}] (test_data_persistence.py:64)

[2023-01-10T03:08:35.553Z] [2023-01-10 03:06:28 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:56)

[2023-01-10T03:08:35.553Z] [2023-01-10 03:08:29 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=wait for loading collection timeout, collection: Hello_Milvus)>, <Time:{'RPC start': '2023-01-10 03:06:28.914848', 'RPC error': '2023-01-10 03:08:29.153174'}> (decorators.py:108)

[2023-01-10T03:08:35.553Z] [2023-01-10 03:08:29 - WARNING - pymilvus.decorators]: Retry timeout: 120s (decorators.py:79)

[2023-01-10T03:08:35.553Z] [2023-01-10 03:08:29 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: Hello_Milvus)>, <Time:{'RPC start': '2023-01-10 03:06:28.895655', 'RPC error': '2023-01-10 03:08:29.153868'}> (decorators.py:108)

[2023-01-10T03:08:35.553Z] [2023-01-10 03:08:29 - ERROR - ci_test]: Traceback (most recent call last):

[2023-01-10T03:08:35.553Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-01-10T03:08:35.553Z]     return func(self, *args, **kwargs)

[2023-01-10T03:08:35.553Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 660, in load_collection

[2023-01-10T03:08:35.553Z]     self.wait_for_loading_collection(collection_name, timeout)

[2023-01-10T03:08:35.553Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-01-10T03:08:35.553Z]     raise e

[2023-01-10T03:08:35.553Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-01-10T03:08:35.553Z]     return func(*args, **kwargs)

[2023-01-10T03:08:35.553Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-01-10T03:08:35.553Z]     ret = func(self, *args, **kwargs)

[2023-01-10T03:08:35.553Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-01-10T03:08:35.553Z]     raise e

[2023-01-10T03:08:35.553Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-01-10T03:08:35.553Z]     return func(self, *args, **kwargs)

[2023-01-10T03:08:35.553Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 682, in wait_for_loading_collection

[2023-01-10T03:08:35.553Z]     raise MilvusException(message=f"wait for loading collection timeout, collection: {collection_name}")

[2023-01-10T03:08:35.553Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=wait for loading collection timeout, collection: Hello_Milvus)>

[2023-01-10T03:08:35.553Z] 

[2023-01-10T03:08:35.553Z] The above exception was the direct cause of the following exception:

[2023-01-10T03:08:35.553Z] 

[2023-01-10T03:08:35.553Z] Traceback (most recent call last):

[2023-01-10T03:08:35.553Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2023-01-10T03:08:35.553Z]     res = func(*args, **_kwargs)

[2023-01-10T03:08:35.553Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2023-01-10T03:08:35.553Z]     return func(*arg, **kwargs)

[2023-01-10T03:08:35.553Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 361, in load

[2023-01-10T03:08:35.554Z]     conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)

[2023-01-10T03:08:35.554Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-01-10T03:08:35.554Z]     raise e

[2023-01-10T03:08:35.554Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-01-10T03:08:35.554Z]     return func(*args, **kwargs)

[2023-01-10T03:08:35.554Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-01-10T03:08:35.554Z]     ret = func(self, *args, **kwargs)

[2023-01-10T03:08:35.554Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 80, in handler

[2023-01-10T03:08:35.554Z]     raise MilvusException(e.code, f"{timeout_msg}, message={e.message}") from e

[2023-01-10T03:08:35.554Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: Hello_Milvus)>

[2023-01-10T03:08:35.554Z]  (api_request.py:39)

[2023-01-10T03:08:35.554Z] [2023-01-10 03:08:29 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: Hello_Milvus)> (api_request.py:40)
```

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/standby_test/detail/standby_test/13/pipeline
log:


[artifacts-querycoord-pod-failure-13-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10378667/artifacts-querycoord-pod-failure-13-pytest-logs.tar.gz)

[artifacts-querycoord-pod-failure-13-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10378668/artifacts-querycoord-pod-failure-13-server-logs.tar.gz)

**Comment by zhuwenxing** [comment]
Verified and passed in version `2.2.0-20230117-f081c3c6`
