### ISSUE TITLE
[Bug]: Failed to insert data into default partition after refreshing `common.defaultPartitionName`

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#21648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230110-aab20a40
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):  pulsar  
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.3.0.dev21; go github.com/milvus-io/milvus-sdk-go/v2
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. deploy milvus cluster
2. refresh config `common.defaultPartitionName` by put etcd kv
```
config-cluster/config/common/defaultPartitionName
wa
```
3. run case insert with default `partition_name=None`:
```
    def test_insert_limit(self):
        c_name = cf.gen_unique_str(prefix)
        collection_w = self.init_collection_wrap(name=c_name)

        for i in range(5):
            df = cf.gen_default_dataframe_data(ct.default_nb, start=i*ct.default_nb)
            mutation_res, _ = collection_w.insert(data=df)
            assert mutation_res.insert_count == ct.default_nb
        assert collection_w.num_entities == ct.default_nb * 5
```

client gets error:
```
[2023-01-11 16:25:17 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [      int64   float varchar                                       float_vector
0         0     0.0       0  [0.06447506556075396, 0.027316360080054367, 0....
1         1     1.0       1  [0.06454942780672786, 0.056474182167839476, 0....
2         2     2.0       2  [0.0996025785772503, 0.1497233726......, kwargs: {'timeout': 120} (api_request.py:56)
[2023-01-11 16:25:18 - ERROR - pymilvus.decorators]: RPC error: [batch_insert], <MilvusException: (code=1, message=partition is not exist: _default)>, <Time:{'RPC start': '2023-01-11 16:25:17.072313', 'RPC error': '2023-01-11 16:25:18.710743'}> (decorators.py:108)
[2023-01-11 16:25:18 - ERROR - ci_test]: Traceback (most recent call last):
  File "/home/zong/zong/projects/milvus/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/home/zong/zong/projects/milvus/tests/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 425, in insert
    res = conn.batch_insert(self._name, entities, partition_name,
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 386, in batch_insert
    raise err
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 382, in batch_insert
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=partition is not exist: _default)>
 (api_request.py:39)
[2023-01-11 16:25:18 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=partition is not exist: _default)> (api_request.py:40)
```

### Expected Behavior

Insert data into refreshed default partition name when insert with `partition_name=None`

**Comment by yanliang567** [comment]
@ThreadDao please check what happens if changing `common.defaultPartitionName` after some data in '_default' partition.

**Comment by ThreadDao** [comment]
> @ThreadDao please check what happens if changing `common.defaultPartitionName` after some data in '_default' partition.

2. create a collection with `_default` partition
3. refresh config `common.defaultPartitionName` to `test_partition`
4. the collection only have the `_default` partition, you need to create `test_partition` partition manually, and `_default` partition is an non-default partition, you can drop while you can't drop new default `test_partition` partition

After refreshing, you can successfully query search data from `_default` partition.

**Comment by ThreadDao** [comment]
Maybe we can change the error message `partition is not exist: _default` to `partition is not exist: $new_default_partition, please create it manually`.
1. `_default` partition actually exists
2. the error message can prompt the user to manually create new default partition
3. we don't need to explain this config separately in the document

**Comment by jiaoew1991** [comment]
> Maybe we can change the error message `partition is not exist: _default` to `partition is not exist: $new_default_partition, please create it manually`.
> 
> 1. `_default` partition actually exists
> 2. the error message can prompt the user to manually create new default partition
> 3. we don't need to explain this config separately in the document

It is better

**Comment by yanliang567** [comment]
keep it active

**Comment by jiaoew1991** [comment]
try it with #22047 
/unassign 
/assign @ThreadDao

**Comment by ThreadDao** [comment]
verified on `master-20230302-bdd6bc76`

- Birdwatcher config not change
- Actual config not change
- Etcd put succ
