### ISSUE TITLE
[Bug]: Search failed with error `reason=Search 8 failed, reason Timestamp lag too large lag(464827h27m31.835s) max(24h0m0s) err %!w(<nil>)` after proxy pod failure chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#21644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230110-cc5ecaba
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):Kafka    
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus==2.3.0.dev21
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/12268675/211747307-b8a0e5e2-44b0-46d4-8fb2-5576fb9a1063.png)

```
[2023-01-10T19:27:46.538Z] [2023-01-10 19:27:23 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['float_vector', {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}], kwargs: {'timeout': 1200, 'index_name': 'test_0vDwYB8s'} (api_request.py:56)

[2023-01-10T19:27:46.538Z] [2023-01-10 19:27:28 - DEBUG - ci_test]: (api_response) : Status(code=0, message=)  (api_request.py:31)

[2023-01-10T19:27:46.538Z] [2023-01-10 19:27:28 - INFO - ci_test]: [test][2023-01-10T19:27:23Z] [5.02931311s] InsertChecker__QNWQDaqH create_index -> Status(code=0, message=) (wrapper.py:30)

[2023-01-10T19:27:46.538Z] [2023-01-10 19:27:28 - INFO - ci_test]: assert index: 5.029588460922241 (test_all_collections_after_chaos.py:68)

[2023-01-10T19:27:46.538Z] [2023-01-10 19:27:28 - INFO - ci_test]: index info: [{'collection': 'InsertChecker__QNWQDaqH', 'field': 'float_vector', 'index_name': 'test_0vDwYB8s', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}] (test_all_collections_after_chaos.py:72)

[2023-01-10T19:27:46.538Z] [2023-01-10 19:27:28 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:56)

[2023-01-10T19:27:46.538Z] [2023-01-10 19:27:31 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)

[2023-01-10T19:27:46.538Z] [2023-01-10 19:27:31 - INFO - ci_test]: [test][2023-01-10T19:27:28Z] [3.52180509s] InsertChecker__QNWQDaqH load -> None (wrapper.py:30)

[2023-01-10T19:27:46.539Z] [2023-01-10 19:27:31 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.08013436919075217, 0.09971480337795628, 0.1277414790624765, 0.13829921792051356, 0.07241622754266692, 0.044825821476905364, 0.07287652498334955, 0.03259113938235253, 0.008500225697527414, 0.04313598979139376, 0.06188144764852698, 0.11702822299831012, 0.08427297491628935, 0.10088581201588119, 0......., kwargs: {} (api_request.py:56)

[2023-01-10T19:27:46.539Z] [2023-01-10 19:27:32 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=7, reason=Search 8 failed, reason Timestamp lag too large lag(464827h27m31.835s) max(24h0m0s) err %!w(<nil>))>, <Time:{'RPC start': '2023-01-10 19:27:31.846409', 'RPC error': '2023-01-10 19:27:32.310324'}> (decorators.py:108)

[2023-01-10T19:27:46.539Z] [2023-01-10 19:27:32 - ERROR - ci_test]: Traceback (most recent call last):

[2023-01-10T19:27:46.539Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2023-01-10T19:27:46.539Z]     res = func(*args, **_kwargs)

[2023-01-10T19:27:46.539Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2023-01-10T19:27:46.539Z]     return func(*arg, **kwargs)

[2023-01-10T19:27:46.539Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 609, in search

[2023-01-10T19:27:46.539Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,

[2023-01-10T19:27:46.539Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-01-10T19:27:46.539Z]     raise e

[2023-01-10T19:27:46.539Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-01-10T19:27:46.539Z]     return func(*args, **kwargs)

[2023-01-10T19:27:46.539Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-01-10T19:27:46.539Z]     ret = func(self, *args, **kwargs)

[2023-01-10T19:27:46.539Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-01-10T19:27:46.539Z]     raise e

[2023-01-10T19:27:46.539Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-01-10T19:27:46.539Z]     return func(self, *args, **kwargs)

[2023-01-10T19:27:46.539Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 470, in search

[2023-01-10T19:27:46.539Z]     return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)

[2023-01-10T19:27:46.539Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 439, in _execute_search_requests

[2023-01-10T19:27:46.539Z]     raise pre_err

[2023-01-10T19:27:46.539Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 430, in _execute_search_requests

[2023-01-10T19:27:46.539Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2023-01-10T19:27:46.539Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=7, reason=Search 8 failed, reason Timestamp lag too large lag(464827h27m31.835s) max(24h0m0s) err %!w(<nil>))>

[2023-01-10T19:27:46.539Z]  (api_request.py:39)

[2023-01-10T19:27:46.539Z] [2023-01-10 19:27:32 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=7, reason=Search 8 failed, reason Timestamp lag too large lag(464827h27m31.835s) max(24h0m0s) err %!w(<nil>))> (api_request.py:40)

[2023-01-10T19:27:46.539Z] ------------- generated html file: file:///tmp/ci_logs/report.html -------------

[2023-01-10T19:27:46.539Z] =========================== short test summary info ============================

[2023-01-10T19:27:46.539Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[InsertChecker__QNWQDaqH] - AssertionError
```

### Milvus Log

chaos type: pod-failure image tag: master-20230110-cc5ecaba target pod: proxy
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-cron/detail/chaos-test-kafka-cron/1100/pipeline

log:
[artifacts-proxy-pod-failure-1100-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10389877/artifacts-proxy-pod-failure-1100-server-logs.tar.gz)

[artifacts-proxy-pod-failure-1100-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10389878/artifacts-proxy-pod-failure-1100-pytest-logs.tar.gz)

**Comment by yanliang567** [comment]
looks like a dup to #21634

**Comment by zhuwenxing** [comment]
chaos type: pod-kill image tag: master-20230110-cc5ecaba target pod: etcd
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/1187/pipeline
log:

[artifacts-etcd-pod-kill-1187-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10390186/artifacts-etcd-pod-kill-1187-server-logs.tar.gz)
[artifacts-etcd-pod-kill-1187-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10390188/artifacts-etcd-pod-kill-1187-pytest-logs.tar.gz)

**Comment by yah01** [comment]
/assign
Also the QueryNode doesn't initialize the timestamp correctly

**Comment by yah01** [comment]
fixed with #21737 
/assign @zhuwenxing

**Comment by zhuwenxing** [comment]
This issue also happened when upgrading from v2.2.2 to 2.2.0-20230131-3b4e5ac2. But it is not a stable issue.
milvus mode: cluster deploy task: upgrade old image tag: v2.2.2 new image tag: 2.2.0-20230131-3b4e5ac2
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_kafka_for_release_cron/detail/deploy_test_kafka_for_release_cron/286/pipeline
log:
[artifacts-kafka-cluster-upgrade-286-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10552620/artifacts-kafka-cluster-upgrade-286-pytest-logs.tar.gz)
[artifacts-kafka-cluster-upgrade-286-server-first-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/10552621/artifacts-kafka-cluster-upgrade-286-server-first-deployment-logs.tar.gz)
[artifacts-kafka-cluster-upgrade-286-server-second-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/10552622/artifacts-kafka-cluster-upgrade-286-server-second-deployment-logs.tar.gz)

**Comment by yah01** [comment]
/assign @zhuwenxing 
fixed with #21899

**Comment by zhuwenxing** [comment]
Verified and passed in `master-20230201-5d5a04d3` and `2.2.0-20230201-d108d916`
