### ISSUE TITLE
[Bug]: [Nightly]Load balance failed reporting 'failed to balance segments, err=TaskStale'

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#21661]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0(04e595d)
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka): kafka
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.1.dev5
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Load balance failed reporting 'failed to balance segments, err=TaskStale'.
```
[2023-01-11T21:26:49.221Z] [2023-01-11 20:58:52 - ERROR - pymilvus.decorators]: RPC error: [load_balance], <MilvusException: (code=1, message=failed to balance segments, err=TaskStale)>, <Time:{'RPC start': '2023-01-11 20:58:51.785992', 'RPC error': '2023-01-11 20:58:52.077284'}> (decorators.py:108)
[2023-01-11T21:26:49.221Z] [2023-01-11 20:58:52 - ERROR - ci_test]: Traceback (most recent call last):
[2023-01-11T21:26:49.221Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2023-01-11T21:26:49.221Z]     res = func(*args, **_kwargs)
[2023-01-11T21:26:49.221Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2023-01-11T21:26:49.221Z]     return func(*arg, **kwargs)
[2023-01-11T21:26:49.221Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/utility.py", line 471, in load_balance
[2023-01-11T21:26:49.221Z]     return _get_connection(using).\
[2023-01-11T21:26:49.221Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2023-01-11T21:26:49.221Z]     raise e
[2023-01-11T21:26:49.221Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2023-01-11T21:26:49.221Z]     return func(*args, **kwargs)
[2023-01-11T21:26:49.221Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2023-01-11T21:26:49.221Z]     ret = func(self, *args, **kwargs)
[2023-01-11T21:26:49.221Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
[2023-01-11T21:26:49.221Z]     raise e
[2023-01-11T21:26:49.221Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2023-01-11T21:26:49.221Z]     return func(self, *args, **kwargs)
[2023-01-11T21:26:49.221Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 939, in load_balance
[2023-01-11T21:26:49.221Z]     raise MilvusException(status.error_code, status.reason)
[2023-01-11T21:26:49.221Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=failed to balance segments, err=TaskStale)>
[2023-01-11T21:26:49.221Z]  (api_request.py:39)
[2023-01-11T21:26:49.221Z] [2023-01-11 20:58:52 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=failed to balance segments, err=TaskStale)> (api_request.py:40)
```

### Expected Behavior

succeed

### Steps To Reproduce

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/61/pipeline/140/

### Milvus Log

1. log: [artifacts-milvus-distributed-kafka-nightly-61-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/61/artifact/artifacts-milvus-distributed-kafka-nightly-61-pymilvus-e2e-logs.tar.gz)
2. collection name: utility_2WAWdyxf
3. failed time: [2023-01-11T20:58:52.522Z] [gw0] [ 98%] FAILED testcases/test_utility.py::TestUtilityAdvanced::test_load_balance_normal

**Comment by binbinlv** [comment]
@sunby 

could you please have a look first? Thanks.

**Comment by NicoYuan1986** [comment]
Latest: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/65/pipeline/148

milvus: 2.2.0(d475de4)
pymilvus: 2.2.1.dev5

1. log: [artifacts-milvus-distributed-kafka-nightly-65-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/65/artifact/artifacts-milvus-distributed-kafka-nightly-65-pymilvus-e2e-logs.tar.gz)
2. collection name: utility_qMdOgGSN
3. failed time: [2023-01-15T20:58:35.571Z] [gw0] [ 98%] FAILED testcases/test_utility.py::TestUtilityAdvanced::test_load_balance_normal

**Comment by NicoYuan1986** [comment]
The issue has not reproduced for some days. Close it first.
