### ISSUE TITLE
[Bug]: Proxy pod panic with error `runtime error: invalid memory address or nil pointer dereference` after etcd pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#21665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230111-04e595d6
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):Kafka    
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus==2.3.0.dev21
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2023-01-11T23:15:19.143Z] + kubectl get pods -o wide

[2023-01-11T23:15:19.143Z] + grep etcd-pod-kill-1161

[2023-01-11T23:15:19.399Z] etcd-pod-kill-1161-0                                             1/1     Running             0               5m19s   10.102.7.23     devops-node11   <none>           <none>

[2023-01-11T23:15:19.399Z] etcd-pod-kill-1161-1                                             1/1     Running             0               5m49s   10.102.6.185    devops-node10   <none>           <none>

[2023-01-11T23:15:19.399Z] etcd-pod-kill-1161-2                                             1/1     Running             0               5m29s   10.102.9.254    devops-node13   <none>           <none>

[2023-01-11T23:15:19.399Z] etcd-pod-kill-1161-kafka-0                                       2/2     Running             2 (12m ago)     12m     10.102.6.150    devops-node10   <none>           <none>

[2023-01-11T23:15:19.399Z] etcd-pod-kill-1161-kafka-1                                       2/2     Running             0               12m     10.102.7.214    devops-node11   <none>           <none>

[2023-01-11T23:15:19.399Z] etcd-pod-kill-1161-kafka-2                                       2/2     Running             1 (11m ago)     12m     10.102.9.217    devops-node13   <none>           <none>

[2023-01-11T23:15:19.399Z] etcd-pod-kill-1161-kafka-exporter-5fdf95b4fb-bz9hr               1/1     Running             4 (11m ago)     12m     10.102.6.145    devops-node10   <none>           <none>

[2023-01-11T23:15:19.399Z] etcd-pod-kill-1161-milvus-datacoord-79c9f8bbcd-cxqxq             1/1     Running             1 (4m30s ago)   12m     10.102.7.169    devops-node11   <none>           <none>

[2023-01-11T23:15:19.399Z] etcd-pod-kill-1161-milvus-datanode-d7b9c8f6d-jghvq               1/1     Running             1 (4m45s ago)   12m     10.102.7.171    devops-node11   <none>           <none>

[2023-01-11T23:15:19.399Z] etcd-pod-kill-1161-milvus-datanode-d7b9c8f6d-k44z5               1/1     Running             1 (4m43s ago)   12m     10.102.9.205    devops-node13   <none>           <none>

[2023-01-11T23:15:19.399Z] etcd-pod-kill-1161-milvus-indexcoord-7dd8c6f8c6-dqp4h            1/1     Running             1 (4m30s ago)   12m     10.102.7.167    devops-node11   <none>           <none>

[2023-01-11T23:15:19.399Z] etcd-pod-kill-1161-milvus-indexnode-774ccf68c5-4fb44             1/1     Running             1 (4m28s ago)   12m     10.102.9.208    devops-node13   <none>           <none>

[2023-01-11T23:15:19.399Z] etcd-pod-kill-1161-milvus-proxy-854c7f4d64-7gvxv                 0/1     Running             4 (2m18s ago)   12m     10.102.7.175    devops-node11   <none>           <none>

[2023-01-11T23:15:19.399Z] etcd-pod-kill-1161-milvus-querycoord-698cfbf5-j5ht9              1/1     Running             1 (4m41s ago)   12m     10.102.7.170    devops-node11   <none>           <none>

[2023-01-11T23:15:19.399Z] etcd-pod-kill-1161-milvus-querynode-6988b4fc69-5s7l9             1/1     Running             1 (2m3s ago)    12m     10.102.7.174    devops-node11   <none>           <none>

[2023-01-11T23:15:19.399Z] etcd-pod-kill-1161-milvus-querynode-6988b4fc69-bh2dz             1/1     Running             1 (2m3s ago)    12m     10.102.5.148    devops-node21   <none>           <none>

[2023-01-11T23:15:19.399Z] etcd-pod-kill-1161-milvus-querynode-6988b4fc69-krdxj             1/1     Running             1 (2m3s ago)    12m     10.102.9.207    devops-node13   <none>           <none>

[2023-01-11T23:15:19.399Z] etcd-pod-kill-1161-milvus-rootcoord-8d7c54869-pljpk              1/1     Running             1 (2m5s ago)    12m     10.102.7.168    devops-node11   <none>           <none>

[2023-01-11T23:15:19.399Z] etcd-pod-kill-1161-minio-0                                       1/1     Running             0               12m     10.102.7.205    devops-node11   <none>           <none>

[2023-01-11T23:15:19.399Z] etcd-pod-kill-1161-minio-1                                       1/1     Running             0               12m     10.102.9.213    devops-node13   <none>           <none>

[2023-01-11T23:15:19.399Z] etcd-pod-kill-1161-minio-2                                       1/1     Running             0               12m     10.102.6.159    devops-node10   <none>           <none>

[2023-01-11T23:15:19.399Z] etcd-pod-kill-1161-minio-3                                       1/1     Running             0               12m     10.102.6.161    devops-node10   <none>           <none>

[2023-01-11T23:15:19.399Z] etcd-pod-kill-1161-zookeeper-0                                   1/1     Running             0               12m     10.102.7.212    devops-node11   <none>           <none>

[2023-01-11T23:15:19.399Z] etcd-pod-kill-1161-zookeeper-1                                   1/1     Running             0               12m     10.102.6.156    devops-node10   <none>           <none>

[2023-01-11T23:15:19.399Z] etcd-pod-kill-1161-zookeeper-2                                   1/1     Running             0               12m     10.102.9.216    devops-node13   <none>           <none>
```

```
[2023/01/11 23:13:00.906 +00:00] [WARN] [retry/retry.go:39] ["retry func failed"] ["retry time"=0] [error="err: find no available rootcoord, check rootcoord state\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:304 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/client/client.go:127 github.com/milvus-io/milvus/internal/distributed/rootcoord/client.(*Client).GetComponentStates\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:65 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates.func1\n/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:37 github.com/milvus-io/milvus/internal/util/retry.Do\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:89 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:104 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentHealthy\n/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:384 github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).init\n/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:292 github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).Run\n/go/src/github.com/milvus-io/milvus/cmd/components/proxy.go:53 github.com/milvus-io/milvus/cmd/components.(*Proxy).Run\n"]
[2023/01/11 23:13:01.107 +00:00] [WARN] [client/client.go:103] ["RootCoordClient mess key not exist"] [key=rootcoord]
[2023/01/11 23:13:01.107 +00:00] [ERROR] [grpcclient/client.go:149] ["failed to get client address"] [error="find no available rootcoord, check rootcoord state"] [stack="github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).connect\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:149\ngithub.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).GetGrpcClient\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:122\ngithub.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).callOnce\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:247\ngithub.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:290\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord/client.(*Client).GetComponentStates\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/client/client.go:127\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates.func1\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:65\ngithub.com/milvus-io/milvus/internal/util/retry.Do\n\t/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:37\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:89\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentHealthy\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:104\ngithub.com/milvus-io/milvus/internal/distributed/proxy.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:384\ngithub.com/milvus-io/milvus/internal/distributed/proxy.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:292\ngithub.com/milvus-io/milvus/cmd/components.(*Proxy).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/proxy.go:53\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:102"]
[2023/01/11 23:13:01.107 +00:00] [WARN] [grpcclient/client.go:296] ["rootcoord ClientBase ReCall grpc first call get error "] [error="err: find no available rootcoord, check rootcoord state\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:295 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/client/client.go:127 github.com/milvus-io/milvus/internal/distributed/rootcoord/client.(*Client).GetComponentStates\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:65 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates.func1\n/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:37 github.com/milvus-io/milvus/internal/util/retry.Do\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:89 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:104 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentHealthy\n/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:384 github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).init\n/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:292 github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).Run\n/go/src/github.com/milvus-io/milvus/cmd/components/proxy.go:53 github.com/milvus-io/milvus/cmd/components.(*Proxy).Run\n"]
[2023/01/11 23:13:01.107 +00:00] [WARN] [client/client.go:103] ["RootCoordClient mess key not exist"] [key=rootcoord]
[2023/01/11 23:13:01.107 +00:00] [ERROR] [grpcclient/client.go:149] ["failed to get client address"] [error="find no available rootcoord, check rootcoord state"] [stack="github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).connect\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:149\ngithub.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).GetGrpcClient\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:122\ngithub.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).callOnce\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:247\ngithub.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:302\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord/client.(*Client).GetComponentStates\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/client/client.go:127\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates.func1\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:65\ngithub.com/milvus-io/milvus/internal/util/retry.Do\n\t/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:37\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:89\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentHealthy\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:104\ngithub.com/milvus-io/milvus/internal/distributed/proxy.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:384\ngithub.com/milvus-io/milvus/internal/distributed/proxy.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:292\ngithub.com/milvus-io/milvus/cmd/components.(*Proxy).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/proxy.go:53\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:102"]
[2023/01/11 23:13:01.107 +00:00] [ERROR] [grpcclient/client.go:305] ["ClientBase ReCall grpc second call get error"] [role=rootcoord] [error="err: find no available rootcoord, check rootcoord state\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:304 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/client/client.go:127 github.com/milvus-io/milvus/internal/distributed/rootcoord/client.(*Client).GetComponentStates\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:65 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates.func1\n/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:37 github.com/milvus-io/milvus/internal/util/retry.Do\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:89 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:104 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentHealthy\n/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:384 github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).init\n/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:292 github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).Run\n/go/src/github.com/milvus-io/milvus/cmd/components/proxy.go:53 github.com/milvus-io/milvus/cmd/components.(*Proxy).Run\n"] [stack="github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:305\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord/client.(*Client).GetComponentStates\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/client/client.go:127\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates.func1\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:65\ngithub.com/milvus-io/milvus/internal/util/retry.Do\n\t/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:37\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:89\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentHealthy\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:104\ngithub.com/milvus-io/milvus/internal/distributed/proxy.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:384\ngithub.com/milvus-io/milvus/internal/distributed/proxy.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:292\ngithub.com/milvus-io/milvus/cmd/components.(*Proxy).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/proxy.go:53\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:102"]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2c28635]

goroutine 249 [running]:
github.com/milvus-io/milvus/internal/proxy.(*Proxy).GetProxyMetrics(0xc00047dce0, {0x411fbb8?, 0xc000fa58f0?}, 0xc000532780)
	/go/src/github.com/milvus-io/milvus/internal/proxy/impl.go:3801 +0x115
github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).GetProxyMetrics(0xf?, {0x411fbb8?, 0xc000fa58f0?}, 0xf?)
	/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:878 +0x2f
github.com/milvus-io/milvus/internal/proto/proxypb._Proxy_GetProxyMetrics_Handler.func1({0x411fbb8, 0xc000fa58f0}, {0x3ba2cc0?, 0xc000532780})
	/go/src/github.com/milvus-io/milvus/internal/proto/proxypb/proxy.pb.go:671 +0x78
github.com/milvus-io/milvus/internal/util/logutil.UnaryTraceLoggerInterceptor({0x411fbb8?, 0xc000fa5860?}, {0x3ba2cc0, 0xc000532780}, 0x410a740?, 0xc00022ad38)
	/go/src/github.com/milvus-io/milvus/internal/util/logutil/grpc_interceptor.go:22 +0x49
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x411fbb8?, 0xc000fa5860?}, {0x3ba2cc0?, 0xc000532780?})
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a
github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1({0x411fbb8, 0xc001400990}, {0x3ba2cc0, 0xc000532780}, 0xc000af4220?, 0xc000af4240)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38 +0x16a
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x411fbb8?, 0xc001400990?}, {0x3ba2cc0?, 0xc000532780?})
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1({0x411fbb8, 0xc001400990}, {0x3ba2cc0, 0xc000532780}, 0xc000e53af0?, 0x39a4a80?)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34 +0xbf
github.com/milvus-io/milvus/internal/proto/proxypb._Proxy_GetProxyMetrics_Handler({0x3cd1700?, 0xc0004d00b0}, {0x411fbb8, 0xc001400990}, 0xc000b087e0, 0xc000a91290)
	/go/src/github.com/milvus-io/milvus/internal/proto/proxypb/proxy.pb.go:673 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004fee00, {0x412fc38, 0xc000682b60}, 0xc0003cc240, 0xc000a913e0, 0x55b9c08, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1283 +0xcfd
google.golang.org/grpc.(*Server).handleStream(0xc0004fee00, {0x412fc38, 0xc000682b60}, 0xc0003cc240, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1620 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:920 +0x28a

```

### Expected Behavior

all pods can be ready after chaosthe 

### Milvus Log

chaos type: pod-kill image tag: 2.2.0-20230111-04e595d6 target pod: etcd
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-for-release-cron/detail/chaos-test-kafka-for-release-cron/1161/pipeline
log:
[artifacts-etcd-pod-kill-1161-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/10397759/artifacts-etcd-pod-kill-1161-server-logs.1.tar.gz)

[artifacts-etcd-pod-kill-1161-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10397760/artifacts-etcd-pod-kill-1161-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
It was reproduced stably, so set it as critical!

**Comment by bigsheeper** [comment]
/assign @zhuwenxing 
should be fixed, please help to verity

**Comment by zhuwenxing** [comment]
verified and passed in `2.2.0-20230113-a13c375c`
