### ISSUE TITLE
[Bug]: [Nightly]Search failed reporting 'channel xx is not available in any replica, err=LackSegment'

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#21667]
## Environment
- Milvus version:04e595d
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.1.dev5
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others: 

## Current Behavior:
Search failed reporting 'channel xx is not available in any replica, err=LackSegment'.
```
[2023-01-11T21:23:59.403Z] [2023-01-11 20:09:57 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.3075515340498379, 0.5043181252648048, 0.22726466740039653, 0.30972667693707223, 0.2594818093884532, 0.24384080544801257, 0.6972569059363569, 0.15206223592125911, 0.53188441717009, 0.4191003444515854, 0.3723171426058829, 0.2817927118118889, 0.9542171557641594, 0.0620067113971039, 0.7747235244060......, kwargs: {} (api_request.py:56)
[2023-01-11T21:23:59.403Z] [2023-01-11 20:10:17 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:
[2023-01-11T21:23:59.403Z] attempt #1:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_56_438689392754393991v1 is not available in any replica, err=LackSegment(segmentID=438689392754596628)
[2023-01-11T21:23:59.403Z] attempt #2:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_55_438689392754393991v0 is not available in any replica, err=LackSegment(segmentID=438689392754596630)
[2023-01-11T21:23:59.403Z] attempt #3:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_55_438689392754393991v0 is not available in any replica, err=LackSegment(segmentID=438689392754596630)
[2023-01-11T21:23:59.403Z] attempt #4:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_55_438689392754393991v0 is not available in any replica, err=LackSegment(segmentID=438689392754596630)
[2023-01-11T21:23:59.403Z] attempt #5:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_55_438689392754393991v0 is not available in any replica, err=LackSegment(segmentID=438689392754596630)
[2023-01-11T21:23:59.403Z] attempt #6:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_55_438689392754393991v0 is not available in any replica, err=LackSegment(segmentID=438689392754596630)
[2023-01-11T21:23:59.403Z] attempt #7:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_55_438689392754393991v0 is not available in any replica, err=LackSegment(segmentID=438689392754596630)
[2023-01-11T21:23:59.403Z] attempt #8:context deadline exceeded
[2023-01-11T21:23:59.403Z] )>, <Time:{'RPC start': '2023-01-11 20:09:57.273919', 'RPC error': '2023-01-11 20:10:17.277969'}> (decorators.py:108)
[2023-01-11T21:23:59.403Z] [2023-01-11 20:10:17 - ERROR - ci_test]: Traceback (most recent call last):
[2023-01-11T21:23:59.403Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2023-01-11T21:23:59.403Z]     res = func(*args, **_kwargs)
[2023-01-11T21:23:59.403Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2023-01-11T21:23:59.403Z]     return func(*arg, **kwargs)
[2023-01-11T21:23:59.403Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 609, in search
[2023-01-11T21:23:59.403Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,
[2023-01-11T21:23:59.404Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2023-01-11T21:23:59.404Z]     raise e
[2023-01-11T21:23:59.404Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2023-01-11T21:23:59.404Z]     return func(*args, **kwargs)
[2023-01-11T21:23:59.404Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2023-01-11T21:23:59.404Z]     ret = func(self, *args, **kwargs)
[2023-01-11T21:23:59.404Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
[2023-01-11T21:23:59.404Z]     raise e
[2023-01-11T21:23:59.404Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2023-01-11T21:23:59.404Z]     return func(self, *args, **kwargs)
[2023-01-11T21:23:59.404Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 470, in search
[2023-01-11T21:23:59.404Z]     return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)
[2023-01-11T21:23:59.404Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 439, in _execute_search_requests
[2023-01-11T21:23:59.404Z]     raise pre_err
[2023-01-11T21:23:59.404Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 430, in _execute_search_requests
[2023-01-11T21:23:59.404Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2023-01-11T21:23:59.404Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:
[2023-01-11T21:23:59.404Z] attempt #1:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_56_438689392754393991v1 is not available in any replica, err=LackSegment(segmentID=438689392754596628)
[2023-01-11T21:23:59.404Z] attempt #2:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_55_438689392754393991v0 is not available in any replica, err=LackSegment(segmentID=438689392754596630)
[2023-01-11T21:23:59.404Z] attempt #3:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_55_438689392754393991v0 is not available in any replica, err=LackSegment(segmentID=438689392754596630)
[2023-01-11T21:23:59.404Z] attempt #4:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_55_438689392754393991v0 is not available in any replica, err=LackSegment(segmentID=438689392754596630)
[2023-01-11T21:23:59.404Z] attempt #5:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_55_438689392754393991v0 is not available in any replica, err=LackSegment(segmentID=438689392754596630)
[2023-01-11T21:23:59.404Z] attempt #6:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_55_438689392754393991v0 is not available in any replica, err=LackSegment(segmentID=438689392754596630)
[2023-01-11T21:23:59.404Z] attempt #7:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_55_438689392754393991v0 is not available in any replica, err=LackSegment(segmentID=438689392754596630)
[2023-01-11T21:23:59.404Z] attempt #8:context deadline exceeded
[2023-01-11T21:23:59.404Z] )>
[2023-01-11T21:23:59.404Z]  (api_request.py:39)
[2023-01-11T21:23:59.404Z] [2023-01-11 20:10:17 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:
[2023-01-11T21:23:59.404Z] attempt #1:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_56_438689392754393991v1 is not available in any replica, err=LackSegment(segmentID=438689392754596628)
[2023-01-11T21:23:59.404Z] attempt #2:fail ...... (api_request.py:40)
```

## Expected Behavior:
pass 

## Report
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/61/pipeline/124/

**Comment by NicoYuan1986** [comment]
1. log: [artifacts-milvus-standalone-nightly-61-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/61/artifact/artifacts-milvus-standalone-nightly-61-pymilvus-e2e-logs.tar.gz)
2. collection name: index_qpRtboPM
3. failed time: [2023-01-11T20:10:17.593Z] [gw1] [ 24%] FAILED testcases/test_index.py::TestNewIndexBase::test_index_collection_with_after_load

**Comment by yah01** [comment]
fixed with #21742 #21762 
/assign @binbinlv

**Comment by binbinlv** [comment]
@NicoYuan1986 

Whether this issue still exists in the nightly tests last night?

**Comment by NicoYuan1986** [comment]
> @NicoYuan1986
> 
> Whether this issue still exists in the nightly tests last night?

Not reproduced for these days.

**Comment by binbinlv** [comment]
OK, close this issue first, will reopen it if it occurs in the future.
