### ISSUE TITLE
[Bug]: Datanode panic and standby rootcoord does not activate after injecting etcd pod kill then rootcoord pod failure and all chaos deleted

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#21666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:wayblink-mep-30-debug-2.2-c6aed4b-20230110
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):Pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus==2.3.0.dev21
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2023-01-11T12:09:12.510Z] + kubectl get pods -o wide

[2023-01-11T12:09:12.510Z] + grep rootcoord-pod-failure-71

[2023-01-11T12:09:12.510Z] rootcoord-pod-failure-71-etcd-0                               1/1     Running            0               4m52s   10.102.5.97     devops-node21   <none>           <none>

[2023-01-11T12:09:12.510Z] rootcoord-pod-failure-71-etcd-1                               1/1     Running            0               4m32s   10.102.7.83     devops-node11   <none>           <none>

[2023-01-11T12:09:12.510Z] rootcoord-pod-failure-71-etcd-2                               1/1     Running            0               4m42s   10.102.6.150    devops-node10   <none>           <none>

[2023-01-11T12:09:12.510Z] rootcoord-pod-failure-71-milvus-datacoord-b96f9d4b7-cnfgr     1/1     Running            1 (3m39s ago)   11m     10.102.5.83     devops-node21   <none>           <none>

[2023-01-11T12:09:12.510Z] rootcoord-pod-failure-71-milvus-datacoord-b96f9d4b7-mq6g7     1/1     Running            0               11m     10.102.7.75     devops-node11   <none>           <none>

[2023-01-11T12:09:12.510Z] rootcoord-pod-failure-71-milvus-datanode-6d79db956f-ggtn6     0/1     Error              2               11m     10.102.7.59     devops-node11   <none>           <none>

[2023-01-11T12:09:12.510Z] rootcoord-pod-failure-71-milvus-datanode-6d79db956f-vqvwf     0/1     CrashLoopBackOff   1 (16s ago)     11m     10.102.5.73     devops-node21   <none>           <none>

[2023-01-11T12:09:12.511Z] rootcoord-pod-failure-71-milvus-indexcoord-558d8bcd45-h4pdv   1/1     Running            0               11m     10.102.7.70     devops-node11   <none>           <none>

[2023-01-11T12:09:12.511Z] rootcoord-pod-failure-71-milvus-indexcoord-558d8bcd45-jbvgs   1/1     Running            0               11m     10.102.5.70     devops-node21   <none>           <none>

[2023-01-11T12:09:12.511Z] rootcoord-pod-failure-71-milvus-indexnode-5999fdb546-89nmx    1/1     Running            0               11m     10.102.5.78     devops-node21   <none>           <none>

[2023-01-11T12:09:12.511Z] rootcoord-pod-failure-71-milvus-proxy-7b97cffccf-lj672        1/1     Running            0               11m     10.102.5.66     devops-node21   <none>           <none>

[2023-01-11T12:09:12.511Z] rootcoord-pod-failure-71-milvus-querycoord-f654b7b54-dzmfv    1/1     Running            1 (3m38s ago)   11m     10.102.5.82     devops-node21   <none>           <none>

[2023-01-11T12:09:12.511Z] rootcoord-pod-failure-71-milvus-querycoord-f654b7b54-wxnqd    1/1     Running            1 (3m36s ago)   11m     10.102.7.73     devops-node11   <none>           <none>

[2023-01-11T12:09:12.511Z] rootcoord-pod-failure-71-milvus-querynode-76b7974b8d-c85qn    1/1     Running            0               11m     10.102.5.74     devops-node21   <none>           <none>

[2023-01-11T12:09:12.511Z] rootcoord-pod-failure-71-milvus-querynode-76b7974b8d-cmwp8    1/1     Running            0               11m     10.102.10.62    devops-node20   <none>           <none>

[2023-01-11T12:09:12.511Z] rootcoord-pod-failure-71-milvus-querynode-76b7974b8d-jtqlj    1/1     Running            0               11m     10.102.7.58     devops-node11   <none>           <none>

[2023-01-11T12:09:12.511Z] rootcoord-pod-failure-71-milvus-rootcoord-5777ffd976-56g79    1/1     Running            2 (3m58s ago)   11m     10.102.5.69     devops-node21   <none>           <none>

[2023-01-11T12:09:12.511Z] rootcoord-pod-failure-71-milvus-rootcoord-5777ffd976-p682j    1/1     Running            0               11m     10.102.7.60     devops-node11   <none>           <none>

[2023-01-11T12:09:12.511Z] rootcoord-pod-failure-71-minio-0                              1/1     Running            0               11m     10.102.5.87     devops-node21   <none>           <none>

[2023-01-11T12:09:12.511Z] rootcoord-pod-failure-71-minio-1                              1/1     Running            0               11m     10.102.7.77     devops-node11   <none>           <none>

[2023-01-11T12:09:12.511Z] rootcoord-pod-failure-71-minio-2                              1/1     Running            0               11m     10.102.6.144    devops-node10   <none>           <none>

[2023-01-11T12:09:12.511Z] rootcoord-pod-failure-71-minio-3                              1/1     Running            0               11m     10.102.9.32     devops-node13   <none>           <none>

[2023-01-11T12:09:12.511Z] rootcoord-pod-failure-71-pulsar-bookie-0                      1/1     Running            0               11m     10.102.5.93     devops-node21   <none>           <none>

[2023-01-11T12:09:12.511Z] rootcoord-pod-failure-71-pulsar-bookie-1                      1/1     Running            0               11m     10.102.7.82     devops-node11   <none>           <none>

[2023-01-11T12:09:12.511Z] rootcoord-pod-failure-71-pulsar-bookie-init-qjtmf             0/1     Completed          0               11m     10.102.5.67     devops-node21   <none>           <none>

[2023-01-11T12:09:12.511Z] rootcoord-pod-failure-71-pulsar-broker-0                      1/1     Running            0               11m     10.102.5.76     devops-node21   <none>           <none>

[2023-01-11T12:09:12.511Z] rootcoord-pod-failure-71-pulsar-proxy-0                       1/1     Running            0               11m     10.102.5.79     devops-node21   <none>           <none>

[2023-01-11T12:09:12.511Z] rootcoord-pod-failure-71-pulsar-pulsar-init-gpjqz             0/1     Completed          0               11m     10.102.5.68     devops-node21   <none>           <none>

[2023-01-11T12:09:12.511Z] rootcoord-pod-failure-71-pulsar-recovery-0                    1/1     Running            0               11m     10.102.5.80     devops-node21   <none>           <none>

[2023-01-11T12:09:12.511Z] rootcoord-pod-failure-71-pulsar-zookeeper-0                   1/1     Running            0               11m     10.102.5.92     devops-node21   <none>           <none>
```

```
Defaulted container "datanode" out of: datanode, config (init)
2023/01/11 12:09:13 maxprocs: Leaving GOMAXPROCS=32: CPU quota undefined

    __  _________ _   ____  ______    
   /  |/  /  _/ /| | / / / / / __/    
  / /|_/ // // /_| |/ / /_/ /\ \    
 /_/  /_/___/____/___/\____/___/     

Welcome to use Milvus!
Version:   c6aed4b
Built:     Tue Jan 10 09:20:35 UTC 2023
GitCommit: c6aed4b
GoVersion: go version go1.18.3 linux/amd64

open pid file: /run/milvus/datanode.pid
lock pid file: /run/milvus/datanode.pid
[2023/01/11 12:09:13.646 +00:00] [INFO] [roles/roles.go:192] ["starting running Milvus components"]
[2023/01/11 12:09:13.646 +00:00] [INFO] [roles/roles.go:134] ["Enable Jemalloc"] ["Jemalloc Path"=/milvus/lib/libjemalloc.so]
[2023/01/11 12:09:13.671 +00:00] [INFO] [config/etcd_source.go:139] ["start refreshing configurations"]
[2023/01/11 12:09:13.671 +00:00] [INFO] [paramtable/quota_param.go:532] ["init disk quota"] [diskQuota(MB)=+inf]
[2023/01/11 12:09:13.672 +00:00] [INFO] [paramtable/component_param.go:1327] ["init segment max idle time"] [value=10m0s]
[2023/01/11 12:09:13.672 +00:00] [INFO] [paramtable/component_param.go:1332] ["init segment min size from idle to sealed"] [value=16]
[2023/01/11 12:09:13.682 +00:00] [INFO] [paramtable/base_table.go:143] ["cannot find etcd.endpoints"]
[2023/01/11 12:09:13.684 +00:00] [INFO] [management/server.go:68] ["management listen"] [addr=:9091]
[2023/01/11 12:09:13.707 +00:00] [INFO] [config/etcd_source.go:139] ["start refreshing configurations"]
[2023/01/11 12:09:13.707 +00:00] [DEBUG] [paramtable/grpc_param.go:153] [initServerMaxSendSize] [role=datanode] [grpc.serverMaxSendSize=536870912]
[2023/01/11 12:09:13.707 +00:00] [DEBUG] [paramtable/grpc_param.go:175] [initServerMaxRecvSize] [role=datanode] [grpc.serverMaxRecvSize=536870912]
[2023/01/11 12:09:13.708 +00:00] [INFO] [datanode/service.go:252] ["DataNode address"] [address=10.102.5.73:21124]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x288b9d0]

goroutine 154 [running]:
github.com/milvus-io/milvus/internal/datanode.(*DataNode).GetMetrics(0xc00057e120, {0x411a998?, 0xc000cde3f0?}, 0x411a900?)
	/go/src/github.com/milvus-io/milvus/internal/datanode/data_node.go:763 +0xb90
github.com/milvus-io/milvus/internal/distributed/datanode.(*Server).GetMetrics(0xf?, {0x411a998?, 0xc000cde3f0?}, 0xf?)
	/go/src/github.com/milvus-io/milvus/internal/distributed/datanode/service.go:366 +0x2b
github.com/milvus-io/milvus/internal/proto/datapb._DataNode_GetMetrics_Handler.func1({0x411a998, 0xc000cde3f0}, {0x3b9e3e0?, 0xc000616740})
	/go/src/github.com/milvus-io/milvus/internal/proto/datapb/data_coord.pb.go:6828 +0x78
github.com/milvus-io/milvus/internal/util/logutil.UnaryTraceLoggerInterceptor({0x411a998?, 0xc000cde360?}, {0x3b9e3e0, 0xc000616740}, 0x4105500?, 0xc000597740)
	/go/src/github.com/milvus-io/milvus/internal/util/logutil/grpc_interceptor.go:22 +0x49
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x411a998?, 0xc000cde360?}, {0x3b9e3e0?, 0xc000616740?})
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a
github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1({0x411a998, 0xc000d2ea20}, {0x3b9e3e0, 0xc000616740}, 0xc0000e6380?, 0xc0000e63c0)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38 +0x16a
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x411a998?, 0xc000d2ea20?}, {0x3b9e3e0?, 0xc000616740?})
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1({0x411a998, 0xc000d2ea20}, {0x3b9e3e0, 0xc000616740}, 0xc000ebaaf0?, 0x39a0640?)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34 +0xbf
github.com/milvus-io/milvus/internal/proto/datapb._DataNode_GetMetrics_Handler({0x3c48fa0?, 0xc0000361e0}, {0x411a998, 0xc000d2ea20}, 0xc000115020, 0xc000738960)
	/go/src/github.com/milvus-io/milvus/internal/proto/datapb/data_coord.pb.go:6830 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00043dc00, {0x412aa18, 0xc000184680}, 0xc00017a000, 0xc000738ae0, 0x55b4ef8, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1283 +0xcfd
google.golang.org/grpc.(*Server).handleStream(0xc00043dc00, {0x412aa18, 0xc000184680}, 0xc00017a000, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1620 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:920 +0x28a

```

### Milvus Log

chaos type: pod-failure image tag: wayblink-mep-30-debug-2.2-c6aed4b-20230110 target pod: rootcoord
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/standby_test/detail/standby_test/71/pipeline
log:
[artifacts-rootcoord-pod-failure-71-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/10397844/artifacts-rootcoord-pod-failure-71-server-logs.1.tar.gz)

[artifacts-rootcoord-pod-failure-71-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10397845/artifacts-rootcoord-pod-failure-71-pytest-logs.tar.gz)

**Comment by bigsheeper** [comment]
/assign @zhuwenxing 
should be fixed, please help to verity

**Comment by zhuwenxing** [comment]
Verified and passed in `2.2.0-20230117-f081c3c6`
