### ISSUE TITLE
[Bug]: Datanode keeps panic and restart after deployment and inserting data when standby mode is on

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#21681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230112-03ce5c26
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):Pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2023/01/12 08:00:14.306 +00:00] [INFO] [datanode/data_node.go:358] ["DataNode is handling watchInfo PUT event"] [key=by-dev/meta/channelwatch/11/by-dev-rootcoord-dml_1_438700618871209989v1] ["watch state"=ToWatch]
[2023/01/12 08:00:14.306 +00:00] [INFO] [datanode/data_sync_service.go:179] ["begin to init data sync service"] [collection=438700618871209989] [Chan=by-dev-rootcoord-dml_1_438700618871209989v1] [unflushed="[]"] [flushed="[]"]
time="2023-01-12T08:00:14Z" level=error msg="[Failed to create consumer]" consumerID=3 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=neqas subscription=by-dev-dataNode-11-by-dev-rootcoord-dml_1_438700618871209989v1 topic="persistent://public/default/by-dev-rootcoord-dml_1"
time="2023-01-12T08:00:14Z" level=error msg="[Failed to create consumer]" consumerID=3 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=neqas subscription=by-dev-dataNode-11-by-dev-rootcoord-dml_1_438700618871209989v1 topic="persistent://public/default/by-dev-rootcoord-dml_1"
[2023/01/12 08:00:14.309 +00:00] [WARN] [retry/retry.go:39] ["retry func failed"] ["retry time"=0] [error="server error: ConsumerBusy: Exclusive consumer is already connected"]
panic: Failed to create consumer by-dev-rootcoord-dml_1, error = All attempts results:
attempt #1:server error: ConsumerBusy: Exclusive consumer is already connected


goroutine 2232 [running]:
github.com/milvus-io/milvus/internal/mq/msgstream.(*MqTtMsgStream).AsConsumer(0xc00281e200, {0xc0023e0d20?, 0x1, 0x3?}, {0xc00298cd40, 0x3e}, 0x2)
	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_msgstream.go:651 +0x285
github.com/milvus-io/milvus/internal/datanode.newDmInputNode({0x4127690, 0xc002245bc0}, 0xc00223f6e0, 0xc001f367d0)
	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_dmstream_input_node.go:52 +0x2af
github.com/milvus-io/milvus/internal/datanode.(*dataSyncService).initNodes(0xc00224a0e0, 0xc00224d040)
	/go/src/github.com/milvus-io/milvus/internal/datanode/data_sync_service.go:285 +0x1a05
github.com/milvus-io/milvus/internal/datanode.newDataSyncService({0x4127690?, 0xc0001aaf80?}, 0xc002907000, 0xc00223f800, {0x414b168, 0xc002912480}, {0x411dd20?, 0xc0024ce4a0}, {0x7fc00f357f90, 0xc00044ddd0}, ...)
	/go/src/github.com/milvus-io/milvus/internal/datanode/data_sync_service.go:112 +0x3c5
github.com/milvus-io/milvus/internal/datanode.(*flowgraphManager).addAndStart(0xc00044de90, 0xc0002fa6c0, 0xc00224d040, 0x0?)
	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_manager.go:49 +0x3a5
github.com/milvus-io/milvus/internal/datanode.(*DataNode).handlePutEvent(0xc0002fa6c0, 0xc002240460, 0x56c3ac0?)
	/go/src/github.com/milvus-io/milvus/internal/datanode/data_node.go:405 +0xba
github.com/milvus-io/milvus/internal/datanode.(*channelEventManager).retryHandlePutEvent(0xc002245b80, {0x1, {0xc001c84e10, 0x2b}, 0x1, 0xc002240460})
	/go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:88 +0x10f
github.com/milvus-io/milvus/internal/datanode.(*channelEventManager).Run.func1()
	/go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:70 +0x12e
created by github.com/milvus-io/milvus/internal/datanode.(*channelEventManager).Run
	/go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:64 +0x56

```

```
[2023-01-12T08:01:22.601Z] + kubectl get pods -o wide

[2023-01-12T08:01:22.601Z] + grep rootcoord-pod-failure-89

[2023-01-12T08:01:22.856Z] rootcoord-pod-failure-89-etcd-0                               1/1     Running     0               9m19s   10.102.7.254    devops-node11   <none>           <none>

[2023-01-12T08:01:22.856Z] rootcoord-pod-failure-89-etcd-1                               1/1     Running     0               9m19s   10.102.9.174    devops-node13   <none>           <none>

[2023-01-12T08:01:22.856Z] rootcoord-pod-failure-89-etcd-2                               1/1     Running     0               9m19s   10.102.6.208    devops-node10   <none>           <none>

[2023-01-12T08:01:22.856Z] rootcoord-pod-failure-89-milvus-datacoord-5bd77896d8-8frnb    1/1     Running     0               9m19s   10.102.9.163    devops-node13   <none>           <none>

[2023-01-12T08:01:22.856Z] rootcoord-pod-failure-89-milvus-datacoord-5bd77896d8-q5ws7    1/1     Running     0               9m19s   10.102.7.240    devops-node11   <none>           <none>

[2023-01-12T08:01:22.856Z] rootcoord-pod-failure-89-milvus-datanode-68d955cf65-nzxsc     0/1     Running     1 (68s ago)     9m19s   10.102.7.243    devops-node11   <none>           <none>

[2023-01-12T08:01:22.856Z] rootcoord-pod-failure-89-milvus-datanode-68d955cf65-r6jq9     0/1     Running     1 (68s ago)     9m19s   10.102.9.157    devops-node13   <none>           <none>

[2023-01-12T08:01:22.856Z] rootcoord-pod-failure-89-milvus-indexcoord-789f6d94cc-gtcns   1/1     Running     0               9m19s   10.102.7.248    devops-node11   <none>           <none>

[2023-01-12T08:01:22.856Z] rootcoord-pod-failure-89-milvus-indexcoord-789f6d94cc-sjfvk   1/1     Running     0               9m19s   10.102.9.168    devops-node13   <none>           <none>

[2023-01-12T08:01:22.856Z] rootcoord-pod-failure-89-milvus-indexnode-7d65cff586-v6227    1/1     Running     0               9m19s   10.102.9.165    devops-node13   <none>           <none>

[2023-01-12T08:01:22.856Z] rootcoord-pod-failure-89-milvus-proxy-6f8c45c45f-zlqf5        1/1     Running     0               9m19s   10.102.7.238    devops-node11   <none>           <none>

[2023-01-12T08:01:22.856Z] rootcoord-pod-failure-89-milvus-querycoord-68c789cf46-h7btb   1/1     Running     0               9m19s   10.102.7.239    devops-node11   <none>           <none>

[2023-01-12T08:01:22.856Z] rootcoord-pod-failure-89-milvus-querycoord-68c789cf46-xcngf   1/1     Running     0               9m19s   10.102.9.154    devops-node13   <none>           <none>

[2023-01-12T08:01:22.856Z] rootcoord-pod-failure-89-milvus-querynode-654899544d-mq6dj    1/1     Running     0               9m19s   10.102.5.101    devops-node21   <none>           <none>

[2023-01-12T08:01:22.856Z] rootcoord-pod-failure-89-milvus-querynode-654899544d-vwsp5    1/1     Running     0               9m19s   10.102.9.164    devops-node13   <none>           <none>

[2023-01-12T08:01:22.856Z] rootcoord-pod-failure-89-milvus-querynode-654899544d-zhxc7    1/1     Running     0               9m19s   10.102.7.237    devops-node11   <none>           <none>

[2023-01-12T08:01:22.856Z] rootcoord-pod-failure-89-milvus-rootcoord-dff9f478d-2f92n     1/1     Running     0               9m19s   10.102.9.167    devops-node13   <none>           <none>

[2023-01-12T08:01:22.856Z] rootcoord-pod-failure-89-milvus-rootcoord-dff9f478d-9t2vv     1/1     Running     0               9m19s   10.102.7.246    devops-node11   <none>           <none>

[2023-01-12T08:01:22.856Z] rootcoord-pod-failure-89-minio-0                              1/1     Running     0               9m19s   10.102.9.173    devops-node13   <none>           <none>

[2023-01-12T08:01:22.856Z] rootcoord-pod-failure-89-minio-1                              1/1     Running     0               9m19s   10.102.7.7      devops-node11   <none>           <none>

[2023-01-12T08:01:22.856Z] rootcoord-pod-failure-89-minio-2                              1/1     Running     0               9m19s   10.102.5.103    devops-node21   <none>           <none>

[2023-01-12T08:01:22.856Z] rootcoord-pod-failure-89-minio-3                              1/1     Running     0               9m18s   10.102.6.211    devops-node10   <none>           <none>

[2023-01-12T08:01:22.856Z] rootcoord-pod-failure-89-pulsar-bookie-0                      1/1     Running     0               9m19s   10.102.7.8      devops-node11   <none>           <none>

[2023-01-12T08:01:22.856Z] rootcoord-pod-failure-89-pulsar-bookie-1                      1/1     Running     0               9m19s   10.102.9.176    devops-node13   <none>           <none>

[2023-01-12T08:01:22.856Z] rootcoord-pod-failure-89-pulsar-bookie-init-z5r57             0/1     Completed   0               9m19s   10.102.9.156    devops-node13   <none>           <none>

[2023-01-12T08:01:22.856Z] rootcoord-pod-failure-89-pulsar-broker-0                      1/1     Running     0               9m19s   10.102.9.166    devops-node13   <none>           <none>

[2023-01-12T08:01:22.856Z] rootcoord-pod-failure-89-pulsar-proxy-0                       1/1     Running     0               9m19s   10.102.9.159    devops-node13   <none>           <none>

[2023-01-12T08:01:22.856Z] rootcoord-pod-failure-89-pulsar-pulsar-init-jh2nj             0/1     Completed   0               9m19s   10.102.9.158    devops-node13   <none>           <none>

[2023-01-12T08:01:22.856Z] rootcoord-pod-failure-89-pulsar-recovery-0                    1/1     Running     0               9m19s   10.102.9.160    devops-node13   <none>           <none>

[2023-01-12T08:01:22.856Z] rootcoord-pod-failure-89-pulsar-zookeeper-0                   1/1     Running     0               9m19s   10.102.7.2      devops-node11   <none>           <none>
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/standby_test/detail/standby_test/89/pipeline

log:
[artifacts-rootcoord-pod-failure-89-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10399750/artifacts-rootcoord-pod-failure-89-server-logs.tar.gz)
[artifacts-rootcoord-pod-failure-89-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10399751/artifacts-rootcoord-pod-failure-89-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
This issue seems is introduced by PR https://github.com/milvus-io/milvus/pull/21641

**Comment by zhuwenxing** [comment]
And it is reproduced stably, so set it as critical

**Comment by xiaocai2333** [comment]
RootCoord old `activateFunc` overrides new `activateFunc`, I will fix it.

**Comment by xiaocai2333** [comment]
@zhuwenxing please verify.

**Comment by zhuwenxing** [comment]
Verified and passed in `2.2.0-20230117-f081c3c6`
