### ISSUE TITLE
[Bug]: [benchmark][cluster]Milvus release collection then load collection failure"server Unavailable: Retry run out of 10 retry times"

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#21685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.2.2
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.1dev4
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

**insert and build index** 
deploy_config:
fouramf-server-cluster-8c24m-test
case_params:
fouramf-client-test-sift10m
other_params:
 --milvus_tag=v2.2.2 -k test_build_index_hnsw_cluster -s --sync_report --deploy_retain --deploy_mode=cluster --case_skip_clean_collection

**release load case**
fouramf-concurrent-bkzfr

case_params
fouramf-client-test-sift10m-search

case_name
-k test_search_custom_parameters --sync_report --case_skip_prepare  --case_skip_build_index --host=10.104.4.94  --deploy_skip --case_skip_clean_collection 

sever:

```
fouramf-4q9sz-97-6429-etcd-0                                      1/1     Running            0               76m     10.104.9.246   4am-node14   <none>           <none>
fouramf-4q9sz-97-6429-etcd-1                                      1/1     Running            0               76m     10.104.6.102   4am-node13   <none>           <none>
fouramf-4q9sz-97-6429-etcd-2                                      1/1     Running            0               76m     10.104.5.142   4am-node12   <none>           <none>
fouramf-4q9sz-97-6429-milvus-datacoord-5df7b47bc4-67qdc           1/1     Running            0               76m     10.104.9.239   4am-node14   <none>           <none>
fouramf-4q9sz-97-6429-milvus-datanode-84d9564f8-8pnfx             1/1     Running            0               76m     10.104.5.135   4am-node12   <none>           <none>
fouramf-4q9sz-97-6429-milvus-indexcoord-6f55454988-m4dg4          1/1     Running            0               76m     10.104.4.95    4am-node11   <none>           <none>
fouramf-4q9sz-97-6429-milvus-indexnode-769f798d4c-jvjgw           1/1     Running            0               76m     10.104.1.235   4am-node10   <none>           <none>
fouramf-4q9sz-97-6429-milvus-proxy-5b777d877d-rl725               1/1     Running            0               76m     10.104.4.94    4am-node11   <none>           <none>
fouramf-4q9sz-97-6429-milvus-querycoord-9dd79b567-s429x           1/1     Running            0               76m     10.104.9.240   4am-node14   <none>           <none>
fouramf-4q9sz-97-6429-milvus-querynode-69594dc745-2s2dz           1/1     Running            0               76m     10.104.4.93    4am-node11   <none>           <none>
fouramf-4q9sz-97-6429-milvus-rootcoord-659486dc5c-j44dv           1/1     Running            0               76m     10.104.4.92    4am-node11   <none>           <none>
fouramf-4q9sz-97-6429-minio-0                                     1/1     Running            0               76m     10.104.4.100   4am-node11   <none>           <none>
fouramf-4q9sz-97-6429-minio-1                                     1/1     Running            0               76m     10.104.5.137   4am-node12   <none>           <none>
fouramf-4q9sz-97-6429-minio-2                                     1/1     Running            0               76m     10.104.6.99    4am-node13   <none>           <none>
fouramf-4q9sz-97-6429-minio-3                                     1/1     Running            0               76m     10.104.9.248   4am-node14   <none>           <none>
fouramf-4q9sz-97-6429-pulsar-bookie-0                             1/1     Running            0               76m     10.104.5.140   4am-node12   <none>           <none>
fouramf-4q9sz-97-6429-pulsar-bookie-1                             1/1     Running            0               76m     10.104.4.103   4am-node11   <none>           <none>
fouramf-4q9sz-97-6429-pulsar-bookie-2                             1/1     Running            0               76m     10.104.6.104   4am-node13   <none>           <none>
fouramf-4q9sz-97-6429-pulsar-bookie-init-5sl9w                    0/1     Completed          0               76m     10.104.9.242   4am-node14   <none>           <none>
fouramf-4q9sz-97-6429-pulsar-broker-0                             1/1     Running            0               76m     10.104.9.243   4am-node14   <none>           <none>
fouramf-4q9sz-97-6429-pulsar-proxy-0                              1/1     Running            0               76m     10.104.4.96    4am-node11   <none>           <none>
fouramf-4q9sz-97-6429-pulsar-pulsar-init-gzdvm                    0/1     Completed          0               76m     10.104.9.244   4am-node14   <none>           <none>
fouramf-4q9sz-97-6429-pulsar-recovery-0                           1/1     Running            0               76m     10.104.9.241   4am-node14   <none>           <none>
fouramf-4q9sz-97-6429-pulsar-zookeeper-0                          1/1     Running            0               76m     10.104.4.99    4am-node11   <none>           <none>
fouramf-4q9sz-97-6429-pulsar-zookeeper-1                          1/1     Running            0               75m     10.104.9.250   4am-node14   <none>           <none>
fouramf-4q9sz-97-6429-pulsar-zookeeper-2                          1/1     Running            0               74m     10.104.5.144   4am-node12   <none>           <none>
```
client log:

```
[2023-01-12 08:44:09,704 -  INFO - fouram]: [Base] Start load collection fouram_z8QjQe9D, replica_number:1 (base.py:108)
[2023-01-12 09:17:27,088 - WARNING - fouram]: [93m[get_loading_progress] retry:4, cost: 0.27s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (decorators.py:71)
[2023-01-12 09:17:27,359 - WARNING - fouram]: [93m[get_loading_progress] retry:5, cost: 0.81s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (decorators.py:71)
[2023-01-12 09:17:28,171 - WARNING - fouram]: [93m[get_loading_progress] retry:6, cost: 2.43s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (decorators.py:71)
[2023-01-12 09:17:30,604 - WARNING - fouram]: [93m[get_loading_progress] retry:7, cost: 7.29s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (decorators.py:71)
[2023-01-12 09:17:37,896 - WARNING - fouram]: [93m[get_loading_progress] retry:8, cost: 21.87s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (decorators.py:71)
[2023-01-12 09:17:59,789 - WARNING - fouram]: [93m[get_loading_progress] retry:9, cost: 60.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (decorators.py:71)
[2023-01-12 09:18:59,841 - WARNING - fouram]: [93m[get_loading_progress] retry:10, cost: 60.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (decorators.py:71)
[2023-01-12 09:19:59,852 - ERROR - fouram]: RPC error: [get_loading_progress], <MilvusUnavailableException: (code=1, message=server Unavailable: Retry run out of 10 retry times)>, <Time:{'RPC start': '2023-01-12 09:17:26.955314', 'RPC error': '2023-01-12 09:19:59.852270'}> (decorators.py:108)
[2023-01-12 09:19:59,852 - ERROR - fouram]: RPC error: [wait_for_loading_collection], <MilvusUnavailableException: (code=1, message=server Unavailable: Retry run out of 10 retry times)>, <Time:{'RPC start': '2023-01-12 08:44:09.718066', 'RPC error': '2023-01-12 09:19:59.852581'}> (decorators.py:108)
[2023-01-12 09:19:59,852 - ERROR - fouram]: RPC error: [load_collection], <MilvusUnavailableException: (code=1, message=server Unavailable: Retry run out of 10 retry times)>, <Time:{'RPC start': '2023-01-12 08:44:09.704591', 'RPC error': '2023-01-12 09:19:59.852681'}> (decorators.py:108)
[2023-01-12 09:19:59,853 - ERROR - fouram]: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 736, in get_loading_progress
    response = self._stub.GetLoadingProgress.future(request, timeout=timeout).result()
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1673515199.851867744","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3260,"referenced_errors":[{"created":"@1673515199.851866937","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":167,"grpc_status":14}]}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/src/fouram/client/util/api_request.py", line 33, in inner_wrapper
    res = func(*args, **kwargs)
  File "/src/fouram/client/util/api_request.py", line 70, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 361, in load
    conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 659, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 677, in wait_for_loading_collection
    progress = self.get_loading_progress(collection_name, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 66, in handler
    raise MilvusUnavailableException(message=f"server Unavailable: {timeout_msg}") from e
pymilvus.exceptions.MilvusUnavailableException: <MilvusUnavailableException: (code=1, message=server Unavailable: Retry run out of 10 retry times)>
 (api_request.py:48)
```

### Steps To Reproduce

```markdown
1. create a collection 
        2. insert a 10million of vectors
        3. flush collection
        4. count the total number of rows
        5. build index on vector column
        6. connection milvus 
        7. release collection 
        8. load collection
```

**Comment by jiaoew1991** [comment]
Querycoord got singal terminated
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/2297455/213347990-59c7d31e-7628-4338-9647-759d946b429c.png">

**Comment by jingkl** [comment]
The problem does not appear, first close off
