### ISSUE TITLE
[Bug]: [benchmark][standalone] Milvus search with Laion dataset ,search rasie an error"StatusCode.DEADLINE_EXCEEDED"

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#21690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.2.2
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.1dev4
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

deploy_config:
fouramf-server-cluster-8c16m-test
case_params:
fouramf-client-laion-search-locust
other_params:
 --milvus_tag=v2.2.2 -k test_concurrent_locust_custom_parameters -s --case_skip_clean_collection --sync_report --deploy_retain

server:

```
fouramf-ps2wv-25-4809-etcd-0                                      1/1     Running            0               50m     10.104.5.149   4am-node12   <none>           <none>
fouramf-ps2wv-25-4809-milvus-standalone-5c864fc455-q8kgg          1/1     Running            0               50m     10.104.4.107   4am-node11   <none>           <none>
fouramf-ps2wv-25-4809-minio-85f85d645f-wxzvg                      1/1     Running            0               50m     10.104.5.150   4am-node12   <none>           <none>
```
client log:

```
2023-01-12 09:11:58,394 - ERROR - fouram]: RPC error: [search], <MilvusException: (code=1, message=<_InactiveRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1673514718.394355981","description":"Error received from peer ipv4:10.255.85.31:19530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>)>, <Time:{'RPC start': '2023-01-12 09:10:48.541387', 'RPC error': '2023-01-12 09:11:58.394834'}> (decorators.py:108)
[2023-01-12 09:11:58,397 - ERROR - fouram]: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 469, in search
    return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 438, in _execute_search_requests
    raise pre_err
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 426, in _execute_search_requests
    response = self._stub.Search(request, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1673514718.394355981","description":"Error received from peer ipv4:10.255.85.31:19530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/src/fouram/client/util/api_request.py", line 33, in inner_wrapper
    res = func(*args, **kwargs)
  File "/src/fouram/client/util/api_request.py", line 70, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 610, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 58, in handler
    raise MilvusException(message=str(e)) from e
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=<_InactiveRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1673514718.394355981","description":"Error received from peer ipv4:10.255.85.31:19530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>)>
 (api_request.py:48)
[2023-01-12 09:11:58,398 - ERROR - fouram]: (api_response) : <MilvusException: (code=1, message=<_InactiveRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1673514718.394355981","description":"Error received from peer ipv4:10.255.85.31:19530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>)> (api_request.py:49)
[2023-01-12 09:11:58,398 - ERROR - fouram]: [CheckFunc] search request check failed, response:<MilvusException: (code=1, message=<_InactiveRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1673514718.394355981","description":"Error received from peer ipv4:10.255.85.31:19530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>)> (func_check.py:42)
[2023-01-12 09:11:59,193 - ERROR - fouram]: RPC error: [search], <MilvusException: (code=1, message=<_InactiveRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1673514718.431316252","description":"Error received from peer ipv4:10.255.85.31:19530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>)>, <Time:{'RPC start': '2023-01-12 09:10:50.137669', 'RPC error': '2023-01-12 09:11:59.193259'}> (decorators.py:108)
```

### Steps To Reproduce

```markdown
1. create a collection
        2. build hnsw index on vector column
        3. insert a 2m of vectors
        4. flush collection
        5. build index on vector column with the same parameters
        6. count the total number of rows
        7. load collection
        8. perform concurrent operations
```

### Anything else?

 ```
{'dataset_params': {'dim': 768,
                                                    'dataset_name': 'laion',
                                                    'dataset_size': '2m',
                                                    'ni_per': 1000,
                                                    'metric_type': 'L2'},
                                 'load_params': {},
                                 'index_params': {'index_type': 'HNSW',
                                                  'index_param': {'M': 8,
                                                                  'efConstruction': 200}},
                                 'concurrent_params': {'concurrent_number': 20,
                                                       'during_time': '1h',
                                                       'interval': 20,
                                                       'spawn_rate': None},
                                 'concurrent_tasks': [{'type': 'search',
                                                       'weight': 1,
                                                       'params': {'nq': 1000,
                                                                  'top_k': 1,
                                                                  'search_param': {'ef': 16},
                                                                  'random_data': True}}]}
```

**Comment by yanliang567** [comment]
@jingkl any updates for this

**Comment by soothing-rain** [comment]
/unassign
/assign @jiaoew1991 

Please help take a look at this.

**Comment by jingkl** [comment]
deploy_config：
fouramf-server-cluster-8c16m-test
case_params：
fouramf-client-laion-search-locust
other_params：
 --milvus_tag= -k test_concurrent_locust_custom_parameters -s --case_skip_clean_collection --sync_report --deploy_retain
image：master-20230222-7a4dfcc7
pymilvus：2.3.0dev34
The current version is normal
