### ISSUE TITLE
[Bug]: [Nightly][kafka]Many cases failed because of insert error

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#21729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 837e316
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):   kafka 
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.0.dev21
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Many cases failed because of insert error.
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/253/pipeline/135
brief: 
```
<MilvusException: (code=55, message=deny to write, reason: time tick long delay, req: /milvus.proto.milvus.MilvusService/Insert)>
```
details: 
```
[2023-01-15T18:48:46.682Z] [2023-01-15 18:30:19 - ERROR - pymilvus.decorators]: RPC error: [batch_insert], <MilvusException: (code=55, message=deny to write, reason: time tick long delay, req: /milvus.proto.milvus.MilvusService/Insert)>, <Time:{'RPC start': '2023-01-15 18:30:19.686025', 'RPC error': '2023-01-15 18:30:19.730545'}> (decorators.py:108)
[2023-01-15T18:48:46.682Z] [2023-01-15 18:30:19 - ERROR - ci_test]: Traceback (most recent call last):
[2023-01-15T18:48:46.682Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2023-01-15T18:48:46.682Z]     res = func(*args, **_kwargs)
[2023-01-15T18:48:46.682Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2023-01-15T18:48:46.683Z]     return func(*arg, **kwargs)
[2023-01-15T18:48:46.683Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 425, in insert
[2023-01-15T18:48:46.683Z]     res = conn.batch_insert(self._name, entities, partition_name,
[2023-01-15T18:48:46.683Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2023-01-15T18:48:46.683Z]     raise e
[2023-01-15T18:48:46.683Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2023-01-15T18:48:46.683Z]     return func(*args, **kwargs)
[2023-01-15T18:48:46.683Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2023-01-15T18:48:46.683Z]     ret = func(self, *args, **kwargs)
[2023-01-15T18:48:46.683Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
[2023-01-15T18:48:46.683Z]     raise e
[2023-01-15T18:48:46.683Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2023-01-15T18:48:46.683Z]     return func(self, *args, **kwargs)
[2023-01-15T18:48:46.683Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 386, in batch_insert
[2023-01-15T18:48:46.683Z]     raise err
[2023-01-15T18:48:46.683Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 382, in batch_insert
[2023-01-15T18:48:46.683Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2023-01-15T18:48:46.683Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=55, message=deny to write, reason: time tick long delay, req: /milvus.proto.milvus.MilvusService/Insert)>
[2023-01-15T18:48:46.683Z]  (api_request.py:39)
[2023-01-15T18:48:46.683Z] [2023-01-15 18:30:19 - ERROR - ci_test]: (api_response) : <MilvusException: (code=55, message=deny to write, reason: time tick long delay, req: /milvus.proto.milvus.MilvusService/Insert)> (api_request.py:40)
```

### Expected Behavior

insert success

### Milvus Log

[artifacts-milvus-distributed-kafka-nightly-253-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/253/artifact/artifacts-milvus-distributed-kafka-nightly-253-pymilvus-e2e-logs.tar.gz)

**Comment by NicoYuan1986** [comment]
Take one case for example: test_query_partition_without_loading
collection name: query_InejXDrE
FAILED timeline: [2023-01-15T18:17:29.355Z] [gw4] [ 36%] FAILED testcases/test_query.py::TestQueryParams::test_query_partition_without_loading
case:
```
[2023-01-15T18:48:44.167Z] _____________ TestQueryParams.test_query_partition_without_loading _____________
[2023-01-15T18:48:44.167Z] [gw4] linux -- Python 3.8.16 /usr/local/bin/python3
[2023-01-15T18:48:44.167Z] 
[2023-01-15T18:48:44.167Z] self = <test_query.TestQueryParams object at 0x7fa6d7dd5cd0>
[2023-01-15T18:48:44.167Z] 
[2023-01-15T18:48:44.167Z]     @pytest.mark.tags(CaseLabel.L2)
[2023-01-15T18:48:44.167Z]     def test_query_partition_without_loading(self):
[2023-01-15T18:48:44.167Z]         """
[2023-01-15T18:48:44.167Z]         target: test query on partition without loading
[2023-01-15T18:48:44.167Z]         method: query on partition and no loading
[2023-01-15T18:48:44.167Z]         expected: raise exception
[2023-01-15T18:48:44.167Z]         """
[2023-01-15T18:48:44.167Z]         collection_w = self.init_collection_wrap(name=cf.gen_unique_str(prefix))
[2023-01-15T18:48:44.167Z]         partition_w = self.init_partition_wrap(collection_wrap=collection_w)
[2023-01-15T18:48:44.167Z]         df = cf.gen_default_dataframe_data()
[2023-01-15T18:48:44.167Z] >       partition_w.insert(df)
[2023-01-15T18:48:44.167Z] 
[2023-01-15T18:48:44.167Z] testcases/test_query.py:839: 
[2023-01-15T18:48:44.167Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[2023-01-15T18:48:44.167Z] base/partition_wrapper.py:95: in insert
[2023-01-15T18:48:44.167Z]     check_result = ResponseChecker(res, func_name, check_task,
[2023-01-15T18:48:44.167Z] check/func_check.py:34: in run
[2023-01-15T18:48:44.167Z]     result = self.assert_succ(self.succ, True)
[2023-01-15T18:48:44.167Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[2023-01-15T18:48:44.167Z] 
[2023-01-15T18:48:44.167Z] actual = False, expect = True
[2023-01-15T18:48:44.167Z] 
[2023-01-15T18:48:44.167Z]     @staticmethod
[2023-01-15T18:48:44.167Z]     def assert_succ(actual, expect):
[2023-01-15T18:48:44.167Z] >       assert actual is expect
[2023-01-15T18:48:44.167Z] E       AssertionError
[2023-01-15T18:48:44.167Z] 
[2023-01-15T18:48:44.167Z] check/func_check.py:93: AssertionError
```

**Comment by bigsheeper** [comment]
Throughput in datacoord-timetick channel is abnormal:
![image](https://user-images.githubusercontent.com/42060877/212804777-0a2be72d-3fd1-40a6-8659-1f2865fce1a1.png)

A plenty of flowgraphs in DataNode didn't be released as expected:
![image](https://user-images.githubusercontent.com/42060877/212804948-306a3380-ccfb-44ab-baf2-db8fa12cd8a8.png)

This leed to the performance decreasing of kafka, and leed to the long time tick issue eventually.
We need to figure out why flowgraphs in DataNode are not being released.

**Comment by bigsheeper** [comment]
Rootcoord's log shows that it didn't send DropCollection to DMLChannel even though it received DropCollection requests.
AsyncSteps in DropCollection task in RootCoord is blocked at **ReleaseCollection** step:
```
2023-01-16T02:11:10.659807012+08:00 stdout F [2023/01/15 18:11:10.659 +00:00] [INFO] [rootcoord/broker.go:61] ["releasing collection"] [collection=438778054851483433]
```

ReleaseCollection job in QueryCoord is blocked at **ReleaseSegment** task:
```
2023-01-16T02:11:12.128225307+08:00 stdout F [2023/01/15 18:11:12.128 +00:00] [INFO] [task/executor.go:347] ["release segment..."] [taskID=2136] [collectionID=438778054851483433] [replicaID=-1] [segmentID=438778054851483444] [node=7] [source=2]
```

ReleaseSegment task in QueryNode is blocked at removeSegment from metaReplica:
```
2023-01-16T02:11:12.128500002+08:00 stdout F [2023/01/15 18:11:12.128 +00:00] [INFO] [querynode/partition.go:100] ["remove a segment from replica"] [collectionID=438778054851483433] [partitionID=438778054851483434] [segmentID=438778054851483444] [segmentType=Sealed]
```
![image](https://user-images.githubusercontent.com/42060877/212806446-ade0b22e-03f0-4e99-9232-b03420ec1c85.png)

**Comment by NicoYuan1986** [comment]
Not reproduced these days.
