### ISSUE TITLE
[Bug]: [Nighty][kafka]Many cases failed due to load collection timeout

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#21730]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 837e316
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):   kafka 
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.0.dev21
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Many cases failed due to load collection timeout.
error message:
```
<MilvusException: (code=1, message=wait for loading collection timeout, collection: query_ktqr3hwk)>
```
Link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/253/pipeline/135/

### Expected Behavior

load successfully

### Milvus Log

[artifacts-milvus-distributed-kafka-nightly-253-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/253/artifact/artifacts-milvus-distributed-kafka-nightly-253-pymilvus-e2e-logs.tar.gz)

**Comment by NicoYuan1986** [comment]
Take one case for example:
1. case name: test_query_growing_segment_data
2. collection name: query_ktqr3hwk
3. error meaage:
```
[2023-01-15T18:48:45.177Z] [2023-01-15 18:19:33 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=wait for loading collection timeout, collection: query_ktqr3hwk)>, <Time:{'RPC start': '2023-01-15 18:17:33.108628', 'RPC error': '2023-01-15 18:19:33.520913'}> (decorators.py:108)
[2023-01-15T18:48:45.177Z] [2023-01-15 18:19:33 - WARNING - pymilvus.decorators]: [93mRetry timeout: 120s[0m (decorators.py:79)
[2023-01-15T18:48:45.177Z] [2023-01-15 18:19:33 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: query_ktqr3hwk)>, <Time:{'RPC start': '2023-01-15 18:17:33.099300', 'RPC error': '2023-01-15 18:19:33.521441'}> (decorators.py:108)
[2023-01-15T18:48:45.178Z] [2023-01-15 18:19:33 - ERROR - ci_test]: Traceback (most recent call last):
[2023-01-15T18:48:45.178Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2023-01-15T18:48:45.178Z]     return func(self, *args, **kwargs)
[2023-01-15T18:48:45.178Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 660, in load_collection
[2023-01-15T18:48:45.178Z]     self.wait_for_loading_collection(collection_name, timeout)
[2023-01-15T18:48:45.178Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2023-01-15T18:48:45.178Z]     raise e
[2023-01-15T18:48:45.178Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2023-01-15T18:48:45.178Z]     return func(*args, **kwargs)
[2023-01-15T18:48:45.178Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2023-01-15T18:48:45.178Z]     ret = func(self, *args, **kwargs)
[2023-01-15T18:48:45.178Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
[2023-01-15T18:48:45.178Z]     raise e
[2023-01-15T18:48:45.178Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2023-01-15T18:48:45.178Z]     return func(self, *args, **kwargs)
[2023-01-15T18:48:45.178Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 682, in wait_for_loading_collection
[2023-01-15T18:48:45.178Z]     raise MilvusException(message=f"wait for loading collection timeout, collection: {collection_name}")
[2023-01-15T18:48:45.178Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=wait for loading collection timeout, collection: query_ktqr3hwk)>
[2023-01-15T18:48:45.178Z] 
[2023-01-15T18:48:45.178Z] The above exception was the direct cause of the following exception:
[2023-01-15T18:48:45.178Z] 
[2023-01-15T18:48:45.178Z] Traceback (most recent call last):
[2023-01-15T18:48:45.178Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2023-01-15T18:48:45.178Z]     res = func(*args, **_kwargs)
[2023-01-15T18:48:45.178Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2023-01-15T18:48:45.178Z]     return func(*arg, **kwargs)
[2023-01-15T18:48:45.178Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 361, in load
[2023-01-15T18:48:45.178Z]     conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
[2023-01-15T18:48:45.178Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2023-01-15T18:48:45.178Z]     raise e
[2023-01-15T18:48:45.178Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2023-01-15T18:48:45.178Z]     return func(*args, **kwargs)
[2023-01-15T18:48:45.178Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2023-01-15T18:48:45.178Z]     ret = func(self, *args, **kwargs)
[2023-01-15T18:48:45.178Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 80, in handler
[2023-01-15T18:48:45.178Z]     raise MilvusException(e.code, f"{timeout_msg}, message={e.message}") from e
[2023-01-15T18:48:45.178Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: query_ktqr3hwk)>
[2023-01-15T18:48:45.178Z]  (api_request.py:39)
[2023-01-15T18:48:45.178Z] [2023-01-15 18:19:33 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: query_ktqr3hwk)> (api_request.py:40)
```
4. failed time: [2023-01-15T18:19:34.229Z] [gw5] [ 58%] FAILED testcases/test_query.py::TestQueryOperation::test_query_growing_segment_data
5. error statement:
```
[2023-01-15T18:48:45.176Z] ______________ TestQueryOperation.test_query_growing_segment_data ______________
[2023-01-15T18:48:45.176Z] [gw5] linux -- Python 3.8.16 /usr/local/bin/python3
[2023-01-15T18:48:45.176Z] 
[2023-01-15T18:48:45.176Z] self = <test_query.TestQueryOperation object at 0x7fdb36692850>
[2023-01-15T18:48:45.176Z] 
[2023-01-15T18:48:45.176Z]     @pytest.mark.tags(CaseLabel.L1)
[2023-01-15T18:48:45.177Z]     def test_query_growing_segment_data(self):
[2023-01-15T18:48:45.177Z]         """
[2023-01-15T18:48:45.177Z]         target: test query data in the growing segment
[2023-01-15T18:48:45.177Z]         method: 1. create collection
[2023-01-15T18:48:45.177Z]                 2.load collection
[2023-01-15T18:48:45.177Z]                 3.insert without flush
[2023-01-15T18:48:45.177Z]                 4.query
[2023-01-15T18:48:45.177Z]         expected: Data can be queried
[2023-01-15T18:48:45.177Z]         """
[2023-01-15T18:48:45.177Z]         import time
[2023-01-15T18:48:45.177Z]         collection_w = self.init_collection_wrap(name=cf.gen_unique_str(prefix))
[2023-01-15T18:48:45.177Z]         # load collection
[2023-01-15T18:48:45.177Z]         collection_w.create_index(ct.default_float_vec_field_name, index_params=ct.default_flat_index)
[2023-01-15T18:48:45.177Z] >       collection_w.load()
[2023-01-15T18:48:45.177Z] 
```

**Comment by jaime0815** [comment]
there are two load tasks 2179 and 2180,  task 2180 was executed successfully, but task 2179 didn't schedule until timeout that should execute on node 7.  Seems that the middle state is abnormal,  the last heartbeat time from Querycoord to node7 is six minutes ago.
```
stdout F [2023/01/15 18:17:33.101 +00:00] [INFO] [querycoordv2/services.go:201] ["load collection request received"] [collectionID=438778054851686315] [schema="name:\"query_ktqr3hwk\" fields:<fieldID:100 name:\"int64\" is_primary_key:true data_type:Int64 > fields:<fieldID:101 name:\"float\" data_type:Float > fields:<fieldID:102 name:\"varchar\" data_type:VarChar type_params:<key:\"max_length\" value:\"65535\" > > fields:<fieldID:103 name:\"float_vector\" data_type:FloatVector type_params:<key:\"dim\" value:\"128\" > > "] [replicaNumber=1] [fieldIndexes="[438778054851686320]"]

67091:2023-01-16T02:17:33.630601469+08:00 stdout F [2023/01/15 18:17:33.630 +00:00] [INFO] [task/scheduler.go:261] ["task added"] [task="[id=2179] [type=1] [collectionID=438778054851686315] [replicaID=438778069416673584] [priority=1] [actionsCount=1] [actions={[type=1]node=7]}] [channel=by-dev-rootcoord-dml_37_438778054851686315v1]"]
67092:2023-01-16T02:17:33.630625259+08:00 stdout F [2023/01/15 18:17:33.630 +00:00] [INFO] [task/scheduler.go:261] ["task added"] [task="[id=2180] [type=1] [collectionID=438778054851686315] [replicaID=438778069416673584] [priority=1] [actionsCount=1] [actions={[type=1][node=8]}] [channel=by-dev-rootcoord-dml_36_438778054851686315v0]"]

67109:2023-01-16T02:17:34.146021673+08:00 stdout F [2023/01/15 18:17:34.145 +00:00] [INFO] [task/executor.go:440] ["subscribe DmChannel done"] [taskID=2180] [collectionID=438778054851686315] [replicaID=438778069416673584] [channel=by-dev-rootcoord-dml_36_43877805485168
6315v0] [node=8] [source=1] [taskID=2180] ["time taken"=17.761001ms]
67118:2023-01-16T02:17:34.628832836+08:00 stdout F [2023/01/15 18:17:34.628 +00:00] [DEBUG] [task/scheduler.go:701] ["task removed"] [taskID=2180] [collectionID=438778054851686315] [replicaID=438778069416673584] [taskStatus=3] [channel=by-dev-rootcoord-dml_36_438778054
851686315v0]

2023-01-16T02:17:18.705956932+08:00 stdout F [2023/01/15 18:17:18.705 +00:00] [DEBUG] [dist/dist_handler.go:76] ["failed to get node's data distribution"] [nodeID=7] [lastHeartbeat=2023/01/15 18:11:12.127 +00:00]
2023-01-16T02:17:48.712967652+08:00 stdout F [2023/01/15 18:17:48.712 +00:00] [DEBUG] [dist/dist_handler.go:76] ["failed to get node's data distribution"] [nodeID=7] [lastHeartbeat=2023/01/15 18:11:12.127 +00:00]

stdout F [2023/01/15 18:27:34.630 +00:00] [INFO] [observers/collection_observer.go:191] ["collection load progress"] [collectionID=438778054851686315] [subChannelCount=1] [loadSegmentCount=0]
stdout F [2023/01/15 18:27:35.629 +00:00] [INFO] [observers/collection_observer.go:102] ["load collection timeout, cancel it"] [collectionID=438778054851686315] [loadTime=10m2.522892251s]
```

**Comment by NicoYuan1986** [comment]
Not reproduced these days.
