### ISSUE TITLE
[Bug]: Datanode panic after pulsar pod failure chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#21765]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230116-6e66c101
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):Pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2023-01-16T21:37:34.603Z] + + kubectl get pods -o wide

[2023-01-16T21:37:34.603Z] grep pulsar-pod-failure-1341

[2023-01-16T21:37:34.858Z] pulsar-pod-failure-1341-bookie-0                                 1/1     Running     0               11m     10.102.7.159    devops-node11   <none>           <none>

[2023-01-16T21:37:34.858Z] pulsar-pod-failure-1341-bookie-1                                 1/1     Running     5 (5m22s ago)   11m     10.102.9.167    devops-node13   <none>           <none>

[2023-01-16T21:37:34.858Z] pulsar-pod-failure-1341-bookie-init-66fgz                        0/1     Completed   0               11m     10.102.10.54    devops-node20   <none>           <none>

[2023-01-16T21:37:34.858Z] pulsar-pod-failure-1341-broker-0                                 1/1     Running     0               11m     10.102.7.119    devops-node11   <none>           <none>

[2023-01-16T21:37:34.858Z] pulsar-pod-failure-1341-etcd-0                                   1/1     Running     0               11m     10.102.7.163    devops-node11   <none>           <none>

[2023-01-16T21:37:34.858Z] pulsar-pod-failure-1341-etcd-1                                   1/1     Running     0               11m     10.102.5.38     devops-node21   <none>           <none>

[2023-01-16T21:37:34.858Z] pulsar-pod-failure-1341-etcd-2                                   1/1     Running     0               11m     10.102.9.171    devops-node13   <none>           <none>

[2023-01-16T21:37:34.858Z] pulsar-pod-failure-1341-milvus-datacoord-799956d569-q8g65        1/1     Running     0               11m     10.102.7.126    devops-node11   <none>           <none>

[2023-01-16T21:37:34.858Z] pulsar-pod-failure-1341-milvus-datanode-7967f896d8-4j7wb         0/1     Running     1 (4s ago)      11m     10.102.7.148    devops-node11   <none>           <none>

[2023-01-16T21:37:34.858Z] pulsar-pod-failure-1341-milvus-datanode-7967f896d8-6g86t         0/1     Running     1 (10s ago)     11m     10.102.5.34     devops-node21   <none>           <none>

[2023-01-16T21:37:34.858Z] pulsar-pod-failure-1341-milvus-indexcoord-5f67f956bb-mtvdd       1/1     Running     0               11m     10.102.7.120    devops-node11   <none>           <none>

[2023-01-16T21:37:34.858Z] pulsar-pod-failure-1341-milvus-indexnode-9f784ff69-qqmd8         1/1     Running     0               11m     10.102.7.121    devops-node11   <none>           <none>

[2023-01-16T21:37:34.858Z] pulsar-pod-failure-1341-milvus-proxy-6748fd4db8-tw28h            1/1     Running     0               11m     10.102.5.36     devops-node21   <none>           <none>

[2023-01-16T21:37:34.858Z] pulsar-pod-failure-1341-milvus-querycoord-8459db4d9-cj55v        1/1     Running     0               11m     10.102.7.130    devops-node11   <none>           <none>

[2023-01-16T21:37:34.859Z] pulsar-pod-failure-1341-milvus-querynode-569f8556f9-4q45d        1/1     Running     0               11m     10.102.10.53    devops-node20   <none>           <none>

[2023-01-16T21:37:34.859Z] pulsar-pod-failure-1341-milvus-querynode-569f8556f9-dpfwh        1/1     Running     0               11m     10.102.5.35     devops-node21   <none>           <none>

[2023-01-16T21:37:34.859Z] pulsar-pod-failure-1341-milvus-querynode-569f8556f9-qzzzt        1/1     Running     0               11m     10.102.7.132    devops-node11   <none>           <none>

[2023-01-16T21:37:34.859Z] pulsar-pod-failure-1341-milvus-rootcoord-586dc8bbff-jtgqs        1/1     Running     0               11m     10.102.7.117    devops-node11   <none>           <none>

[2023-01-16T21:37:34.859Z] pulsar-pod-failure-1341-minio-0                                  1/1     Running     0               11m     10.102.7.161    devops-node11   <none>           <none>

[2023-01-16T21:37:34.859Z] pulsar-pod-failure-1341-minio-1                                  1/1     Running     0               11m     10.102.10.59    devops-node20   <none>           <none>

[2023-01-16T21:37:34.859Z] pulsar-pod-failure-1341-minio-2                                  1/1     Running     0               11m     10.102.5.40     devops-node21   <none>           <none>

[2023-01-16T21:37:34.859Z] pulsar-pod-failure-1341-minio-3                                  1/1     Running     0               11m     10.102.9.172    devops-node13   <none>           <none>

[2023-01-16T21:37:34.859Z] pulsar-pod-failure-1341-proxy-0                                  1/1     Running     0               11m     10.102.7.129    devops-node11   <none>           <none>

[2023-01-16T21:37:34.859Z] pulsar-pod-failure-1341-pulsar-init-dcknb                        0/1     Completed   0               11m     10.102.7.131    devops-node11   <none>           <none>

[2023-01-16T21:37:34.859Z] pulsar-pod-failure-1341-recovery-0                               1/1     Running     0               11m     10.102.7.150    devops-node11   <none>           <none>

[2023-01-16T21:37:34.859Z] pulsar-pod-failure-1341-zookeeper-0                              1/1     Running     0               11m     10.102.7.160    devops-node11   <none>           <none>
```

```
[2023/01/16 21:41:29.938 +00:00] [INFO] [datanode/channel_meta.go:296] ["begin to init pk bloom filter"] [segmentID=438804014208062764] ["stats bin logs"=0]
[2023/01/16 21:41:29.938 +00:00] [WARN] [datanode/channel_meta.go:325] ["no stats files to load"] [segmentID=438804014208062764]
time="2023-01-16T21:41:29Z" level=error msg="Failed to create consumer" consumerID=71 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=fwvbv subscription=by-dev-dataNode-12-by-dev-rootcoord-dml_66_438804014208063299v0 topic="persistent://public/default/by-dev-rootcoord-dml_66"
time="2023-01-16T21:41:29Z" level=error msg="Failed to create consumer" consumerID=71 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=fwvbv subscription=by-dev-dataNode-12-by-dev-rootcoord-dml_66_438804014208063299v0 topic="persistent://public/default/by-dev-rootcoord-dml_66"
panic: Failed to create consumer by-dev-rootcoord-dml_66, error = All attempts results:
attempt #1:server error: ConsumerBusy: Exclusive consumer is already connected


goroutine 5248 [running]:
panic({0x31eb820, 0xc005026460})
	/usr/local/go/src/runtime/panic.go:941 +0x397 fp=0xc00370c1c8 sp=0xc00370c108 pc=0x11c6cf7
github.com/milvus-io/milvus/internal/mq/msgstream.(*MqTtMsgStream).AsConsumer(0xc00514f200, {0xc00512ebb0?, 0x1, 0x3?}, {0xc0026153c0, 0x3f}, 0x2)
	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_msgstream.go:532 +0x285 fp=0xc00370c2b8 sp=0xc00370c1c8 pc=0x23f2b25
github.com/milvus-io/milvus/internal/datanode.newDmInputNode({0x3a68a90, 0xc003d49040}, 0xc001f23080, 0xc00258a000)
	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_dmstream_input_node.go:53 +0x24c fp=0xc00370c868 sp=0xc00370c2b8 pc=0x27027cc
github.com/milvus-io/milvus/internal/datanode.(*dataSyncService).initNodes(0xc0006adb30, 0xc004ea0400)
	/go/src/github.com/milvus-io/milvus/internal/datanode/data_sync_service.go:290 +0x19fe fp=0xc00370d450 sp=0xc00370c868 pc=0x26f7ffe
github.com/milvus-io/milvus/internal/datanode.newDataSyncService({0x3a68a90?, 0xc000689f40?}, 0xc003fbb000, 0xc001f7f7a0, {0x3a923a8, 0xc005000bd0}, {0x3a5f160?, 0xc0034d8210}, {0x7fbc3a1078a0, 0xc000c8aea0}, ...)
	/go/src/github.com/milvus-io/milvus/internal/datanode/data_sync_service.go:116 +0x3d3 fp=0xc00370d4b8 sp=0xc00370d450 pc=0x26f5cb3
github.com/milvus-io/milvus/internal/datanode.(*flowgraphManager).addAndStart(0xc000c8af60, 0xc000f0e240, 0xc004ea0400, 0xf?)
	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_manager.go:50 +0x3c5 fp=0xc00370d708 sp=0xc00370d4b8 pc=0x270b205
github.com/milvus-io/milvus/internal/datanode.(*DataNode).handlePutEvent(0xc000f0e240, 0xc0034fcdc0, 0x4ed5680?)
	/go/src/github.com/milvus-io/milvus/internal/datanode/data_node.go:411 +0xba fp=0xc00370db58 sp=0xc00370d708 pc=0x26f349a
github.com/milvus-io/milvus/internal/datanode.(*DataNode).handlePutEvent-fm(0x3787b51f?, 0xedb57bbc5?)
	<autogenerated>:1 +0x2f fp=0xc00370db80 sp=0xc00370db58 pc=0x2727a0f
github.com/milvus-io/milvus/internal/datanode.(*channelEventManager).retryHandlePutEvent(0xc003cfa240, {0x1, {0xc0053ade00, 0x2c}, 0x1, 0xc0034fcdc0})
	/go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:88 +0x10f fp=0xc00370df20 sp=0xc00370db80 pc=0x26fa9cf
github.com/milvus-io/milvus/internal/datanode.(*channelEventManager).Run.func1()
	/go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:70 +0x12e fp=0xc00370dfe0 sp=0xc00370df20 pc=0x26fa88e
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00370dfe8 sp=0xc00370dfe0 pc=0x11fc0a1
created by github.com/milvus-io/milvus/internal/datanode.(*channelEventManager).Run
	/go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:64 +0x56

```

### Expected Behavior

All pods can be ready after the chaos

### Milvus Log

chaos type: pod-failure image tag: master-20230116-6e66c101 target pod: pulsar
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/1341/pipeline

log:
[artifacts-pulsar-pod-failure-1341-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/10431884/artifacts-pulsar-pod-failure-1341-server-logs.1.tar.gz)
[artifacts-pulsar-pod-failure-1341-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10431886/artifacts-pulsar-pod-failure-1341-pytest-logs.tar.gz)

**Comment by xiaofan-luan** [comment]
should be recovered in a while?

**Comment by zhuwenxing** [comment]
> should be recovered in a while?

No!  After chaos deleted and then waiting 3 min, the datanodes are still in a not-ready status and have already been restarted once.

**Comment by xiaofan-luan** [comment]
seems that this is due to pulsar consumer issue~
