### ISSUE TITLE
[Bug]: Recall is only 0.384 for first search, which is expected to be 0.97~0.98, but for the late search , the recall can be 0.984

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#21783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230116-836773f1
- Deployment mode(standalone or cluster):cluster and standalone
- MQ type(rocksmq, pulsar or kafka):Kafka and pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2023-01-17T10:11:37.991Z] Search...

[2023-01-17T10:11:37.991Z] search cost  3.9131 seconds

[2023-01-17T10:11:37.991Z] Traceback (most recent call last):

[2023-01-17T10:11:37.991Z]   File "scripts/first_recall_test.py", line 136, in <module>

[2023-01-17T10:11:37.991Z]     milvus_recall_test(host)

[2023-01-17T10:11:37.991Z]   File "scripts/first_recall_test.py", line 117, in milvus_recall_test

[2023-01-17T10:11:37.991Z]     assert recall >= 0.95

[2023-01-17T10:11:37.991Z] AssertionError
```

collection name: sift_128_euclidean

### Expected Behavior

```
[2023-01-15T09:28:45.814Z] Insert 1000000 vectors cost 32.9921 seconds

[2023-01-15T09:28:45.814Z] 

[2023-01-15T09:28:45.814Z] Get collection entities...

[2023-01-15T09:28:45.814Z] 1000000

[2023-01-15T09:28:45.814Z] 

[2023-01-15T09:28:45.814Z] Get collection entities cost 2.5327 seconds

[2023-01-15T09:28:45.814Z] 

[2023-01-15T09:28:45.814Z] Create index...

[2023-01-15T09:28:45.814Z] 

[2023-01-15T09:28:45.814Z] Create index cost 3.5314 seconds

[2023-01-15T09:28:45.814Z] 

[2023-01-15T09:28:45.814Z] load collection...

[2023-01-15T09:28:45.814Z] 

[2023-01-15T09:28:45.814Z] load collection cost 6.5466 seconds

[2023-01-15T09:28:45.814Z] 

[2023-01-15T09:28:45.814Z] Search...

[2023-01-15T09:28:45.814Z] search cost  4.1557 seconds

[2023-01-15T09:28:45.814Z] recall=0.983

[2023-01-15T09:28:45.814Z] {'float': 2.0, 'int64': 2}

[2023-01-15T09:28:45.814Z] {'float': 4.0, 'int64': 4}

[2023-01-15T09:28:45.814Z] {'float': 6.0, 'int64': 6}

[2023-01-15T09:28:45.814Z] {'float': 8.0, 'int64': 8}
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_cron/detail/deploy_test_cron/225/pipeline
log:
[artifacts-pulsar-cluster-reinstall-225-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10441802/artifacts-pulsar-cluster-reinstall-225-server-logs.tar.gz)
[artifacts-pulsar-cluster-reinstall-225-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10441803/artifacts-pulsar-cluster-reinstall-225-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
index params:
```
  default_index = {"index_type": "IVF_SQ8",
                   "metric_type": "L2", "params": {"nlist": 64}}
```

search_params
```
{"metric_type": "L2", "params": {"nprobe": 10}}
```
recall: 0.384

**Comment by zhuwenxing** [comment]
After more tests, find a new thing:
In the first search, the recall is only 0.384, then the recall of the later search can be normal, becoming 0.984.

```
2023-01-18 14:22:04.291 | INFO     | __main__:milvus_recall_test:103 - Search...
2023-01-18 14:22:28.531 | INFO     | __main__:milvus_recall_test:110 - search cost  24.2404 seconds
2023-01-18 14:22:39.540 | INFO     | __main__:milvus_recall_test:121 - Calculate recall...
2023-01-18 14:22:40.136 | INFO     | __main__:milvus_recall_test:128 - recall=0.384
2023-01-18 14:22:59.678 | INFO     | __main__:milvus_recall_test:110 - search cost  55.3871 seconds
2023-01-18 14:23:10.357 | INFO     | __main__:milvus_recall_test:121 - Calculate recall...
2023-01-18 14:23:11.581 | INFO     | __main__:milvus_recall_test:128 - recall=0.984
2023-01-18 14:23:36.496 | INFO     | __main__:milvus_recall_test:110 - search cost  92.2054 seconds
2023-01-18 14:23:51.315 | INFO     | __main__:milvus_recall_test:121 - Calculate recall...
2023-01-18 14:23:53.593 | INFO     | __main__:milvus_recall_test:128 - recall=0.984

```

**Comment by zhuwenxing** [comment]
If we add 20s waiting time before the seach, the recall of the first search is also normal(0.984).

So the issue may be caused by segments were not loaded completely.

**Comment by zhuwenxing** [comment]
This issue was not reproduced in the 2.2.0 branch. it can get a normal recall just after waiting for 10s.

**Comment by zhuwenxing** [comment]
It may still fail when adding a 20s waiting time
image tag: master-20230130-270c5b05
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_cron/detail/deploy_test_cron/280/pipeline
```

[2023-01-30T09:26:10.589Z] 2023-01-30 09:26:08.319 | INFO     | __main__:milvus_recall_test:87 - load collection...

[2023-01-30T09:26:14.743Z] 2023-01-30 09:26:13.857 | INFO     | __main__:milvus_recall_test:91 - load collection cost 5.5375 seconds

[2023-01-30T09:26:14.743Z] 2023-01-30 09:26:13.858 | INFO     | __main__:milvus_recall_test:94 - segments info: [segmentID: 439109724449752562

[2023-01-30T09:26:14.743Z] collectionID: 439109724448951645

[2023-01-30T09:26:14.743Z] partitionID: 439109724448951646

[2023-01-30T09:26:14.743Z] num_rows: 150086

[2023-01-30T09:26:14.743Z] state: Sealed

[2023-01-30T09:26:14.743Z] nodeIds: 1

[2023-01-30T09:26:14.743Z] , segmentID: 439109724449952592

[2023-01-30T09:26:14.743Z] collectionID: 439109724448951645

[2023-01-30T09:26:14.743Z] partitionID: 439109724448951646

[2023-01-30T09:26:14.743Z] num_rows: 350272

[2023-01-30T09:26:14.743Z] state: Sealed

[2023-01-30T09:26:14.743Z] nodeIds: 1

[2023-01-30T09:26:14.743Z] , segmentID: 439109724449752557

[2023-01-30T09:26:14.743Z] collectionID: 439109724448951645

[2023-01-30T09:26:14.743Z] partitionID: 439109724448951646

[2023-01-30T09:26:14.743Z] num_rows: 149914

[2023-01-30T09:26:14.743Z] state: Sealed

[2023-01-30T09:26:14.743Z] nodeIds: 1

[2023-01-30T09:26:14.743Z] , segmentID: 439109724449952591

[2023-01-30T09:26:14.743Z] collectionID: 439109724448951645

[2023-01-30T09:26:14.743Z] partitionID: 439109724448951646

[2023-01-30T09:26:14.743Z] num_rows: 349728

[2023-01-30T09:26:14.743Z] state: Sealed

[2023-01-30T09:26:14.743Z] nodeIds: 1

[2023-01-30T09:26:14.743Z] ]

[2023-01-30T09:26:14.743Z] 2023-01-30 09:26:13.860 | INFO     | __main__:milvus_recall_test:98 - wait for loading complete...

[2023-01-30T09:26:46.735Z] 2023-01-30 09:26:43.889 | INFO     | __main__:milvus_recall_test:101 - segments info: [segmentID: 439109724449952591

[2023-01-30T09:26:46.735Z] collectionID: 439109724448951645

[2023-01-30T09:26:46.735Z] partitionID: 439109724448951646

[2023-01-30T09:26:46.735Z] num_rows: 349728

[2023-01-30T09:26:46.735Z] state: Sealed

[2023-01-30T09:26:46.735Z] nodeIds: 1

[2023-01-30T09:26:46.735Z] , segmentID: 439109724449752557

[2023-01-30T09:26:46.735Z] collectionID: 439109724448951645

[2023-01-30T09:26:46.735Z] partitionID: 439109724448951646

[2023-01-30T09:26:46.735Z] num_rows: 149914

[2023-01-30T09:26:46.735Z] state: Sealed

[2023-01-30T09:26:46.735Z] nodeIds: 1

[2023-01-30T09:26:46.736Z] , segmentID: 439109724449952592

[2023-01-30T09:26:46.736Z] collectionID: 439109724448951645

[2023-01-30T09:26:46.736Z] partitionID: 439109724448951646

[2023-01-30T09:26:46.736Z] num_rows: 350272

[2023-01-30T09:26:46.736Z] state: Sealed

[2023-01-30T09:26:46.736Z] nodeIds: 1

[2023-01-30T09:26:46.736Z] , segmentID: 439109724449752562

[2023-01-30T09:26:46.736Z] collectionID: 439109724448951645

[2023-01-30T09:26:46.736Z] partitionID: 439109724448951646

[2023-01-30T09:26:46.736Z] num_rows: 150086

[2023-01-30T09:26:46.736Z] state: Sealed

[2023-01-30T09:26:46.736Z] nodeIds: 1

[2023-01-30T09:26:46.736Z] ]

[2023-01-30T09:26:46.736Z] 2023-01-30 09:26:43.889 | INFO     | __main__:milvus_recall_test:111 - Search...

[2023-01-30T09:26:49.243Z] 2023-01-30 09:26:48.758 | INFO     | __main__:milvus_recall_test:116 - search cost  4.8688 seconds

[2023-01-30T09:26:59.160Z] 2023-01-30 09:26:58.296 | INFO     | __main__:milvus_recall_test:127 - Calculate recall...

[2023-01-30T09:26:59.160Z] 2023-01-30 09:26:58.965 | INFO     | __main__:milvus_recall_test:134 - recall=0.384

[2023-01-30T09:26:59.160Z] Traceback (most recent call last):

[2023-01-30T09:26:59.160Z]   File "scripts/first_recall_test.py", line 152, in <module>

[2023-01-30T09:26:59.160Z]     milvus_recall_test(host)

[2023-01-30T09:26:59.160Z]   File "scripts/first_recall_test.py", line 135, in milvus_recall_test

[2023-01-30T09:26:59.160Z]     assert 0.95 <= recall < 1.0, f"recall is {recall}, less than 0.95"

[2023-01-30T09:26:59.160Z] AssertionError: recall is 0.384, less than 0.95
```

**Comment by zhuwenxing** [comment]
At first, I thought it was because the segment was not fully loaded, but after looking at the segment info, the total amount of data was a complete 100000

**Comment by zhuwenxing** [comment]
/assign @jiaoew1991 
Please also help to take a look

**Comment by xiaofan-luan** [comment]
is it reproducible? it will be hard to investigate for current info

**Comment by yanliang567** [comment]
> is it reproducible? it will be hard to investigate for current info

yes, it is reproduced on master

**Comment by xiaofan-luan** [comment]
/assign @xige-16 
pls take a look into it

**Comment by yanliang567** [comment]
/assign @zhuwenxing 
please help to verify

**Comment by zhuwenxing** [comment]
Verified and passed with `master-20230210-9b8f04fd`
