### ISSUE TITLE
[Bug]: [Nightly][kafka]Kafka runs much slowly with many failed cases and will be killed over 6 hours

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#21805]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: c82b5d1
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):   kafka 
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.0.dev21
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Kafka runs much slowly with many failed cases and will be killed over 6 hours.
1. nightly link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/256/pipeline/155/
2. pytest log: [milvus-distributed-kafka-pymilvus-pytest-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/256/artifact/milvus-distributed-kafka-pymilvus-pytest-logs.tar.gz)
3. error message: (take one case 'test_search_after_index_different_metric_type' for example)
```
[2023-01-18 22:58:31,629 - ERROR - ci_test]: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 660, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 682, in wait_for_loading_collection
    raise MilvusException(message=f"wait for loading collection timeout, collection: {collection_name}")
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=wait for loading collection timeout, collection: search_collection_20ALqdnt)>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 361, in load
    conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 80, in handler
    raise MilvusException(e.code, f"{timeout_msg}, message={e.message}") from e
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: search_collection_20ALqdnt)>
 (api_request.py:39)
[2023-01-18 22:58:31,630 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: search_collection_20ALqdnt)> (api_request.py:40)
```

### Expected Behavior

pass

### Milvus Log

1. milvus log: [artifacts-milvus-distributed-kafka-nightly-256-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/256/artifact/artifacts-milvus-distributed-kafka-nightly-256-pymilvus-e2e-logs.tar.gz)
2. link files:
ci.var.log.containers.mdk-256-n-milvus-datanode-78575456f4-v4fsh_milvus-ci_datanode-d6fd8510b03ba89378deeee8597e431800e42670bdfbc6177eca12e538a314c3.log
ci.var.log.containers.mdk-256-n-milvus-datanode-78575456f4-v4fsh_milvus-ci_datanode-d6fd8510b03ba89378deeee8597e431800e42670bdfbc6177eca12e538a314c3.log
ci.var.log.containers.mdk-256-n-milvus-datanode-78575456f4-v4fsh_milvus-ci_datanode-d6fd8510b03ba89378deeee8597e431800e42670bdfbc6177eca12e538a314c3.log
ci.var.log.containers.mdk-256-n-milvus-datanode-78575456f4-v4fsh_milvus-ci_datanode-d6fd8510b03ba89378deeee8597e431800e42670bdfbc6177eca12e538a314c3.log
3. error:
```
2023-01-19T07:58:00.486774692+08:00 stdout F [2023/01/18 23:58:00.486 +00:00] [ERROR] [datanode/flow_graph_insert_buffer_node.go:480] ["insertBufferNode flushBufferData failed, err = All attempts results:\nattempt #1:StateCode=Abnormal\nattempt #2:context canceled\n"] [stack="github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Sync\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:480\ngithub.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Operate\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:123\ngithub.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work\n\t/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:127"]
2023-01-19T07:58:00.488884105+08:00 stderr F panic: insertBufferNode flushBufferData failed, err = All attempts results:
2023-01-19T07:58:00.488902321+08:00 stderr F attempt #1:StateCode=Abnormal
2023-01-19T07:58:00.488909135+08:00 stderr F attempt #2:context canceled
2023-01-19T07:58:00.488912919+08:00 stderr F
2023-01-19T07:58:00.488920544+08:00 stderr F
2023-01-19T07:58:00.488923271+08:00 stderr F goroutine 58834764 [running]:
2023-01-19T07:58:00.488931835+08:00 stderr F panic({0x3293ae0, 0xc00673e2c0})
2023-01-19T07:58:00.488934943+08:00 stderr F    /usr/local/go/src/runtime/panic.go:941 +0x397 fp=0xc016be37e0 sp=0xc016be3720 pc=0x11c7cf7
2023-01-19T07:58:00.488937902+08:00 stderr F github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Sync(0xc013b14460, 0x4f29be0?, {0xc02322bb58?, 0x0?, 0x0?}, 0xc0059179e0)

```

**Comment by jaime0815** [comment]
It always fails when querycoord gets distribution  from querynode 1
```
2023-01-19T02:08:41.593546263+08:00 stdout F [2023/01/18 18:08:41.593 +00:00] [WARN] [grpcclient/client.go:284] ["ClientBase Call grpc first call get error"] [role=querynode] [error="err: rpc error: code = DeadlineExceeded desc = context deadline exceeded\n, /go/src/github.com/mil
vus-io/milvus/internal/tracer/stack_trace.go:51 github.com/milvus-io/milvus/internal/tracer.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:283 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call\n/go/src/github.com/milvu
s-io/milvus/internal/distributed/querynode/client/client.go:371 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).GetDataDistribution\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/session/cluster.go:183 github.com/milvus-io/milvus/internal/qu
erycoordv2/session.(*QueryCluster).GetDataDistribution.func1\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/session/cluster.go:246 github.com/milvus-io/milvus/internal/querycoordv2/session.(*QueryCluster).send\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/
session/cluster.go:178 github.com/milvus-io/milvus/internal/querycoordv2/session.(*QueryCluster).GetDataDistribution\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/dist/dist_handler.go:214 github.com/milvus-io/milvus/internal/querycoordv2/dist.(*distHandler).getDistrib
ution\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/dist/dist_handler.go:71 github.com/milvus-io/milvus/internal/querycoordv2/dist.(*distHandler).start\n/usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit\n"]
2023-01-19T02:08:41.593574057+08:00 stdout F [2023/01/18 18:08:41.593 +00:00] [WARN] [dist/dist_handler.go:97] ["failed to get data distribution"] [error="err: rpc error: code = DeadlineExceeded desc = context deadline exceeded\n, /go/src/github.com/milvus-io/milvus/internal/tracer/stack_trace.go:51 github.com/milvus-io/milvus/internal/tracer.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:283 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call\n/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:371 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).GetDataDistribution\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/session/cluster.go:183 github.com/milvus-io/milvus/internal/querycoordv2/session.(*QueryCluster).GetDataDistribution.func1\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/session/cluster.go:246 github.com/milvus-io/milvus/internal/querycoordv2/session.(*QueryCluster).send\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/session/cluster.go:178 github.com/milvus-io/milvus/internal/querycoordv2/session.(*QueryCluster).GetDataDistribution\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/dist/dist_handler.go:214 github.com/milvus-io/milvus/internal/querycoordv2/dist.(*distHandler).getDistribution\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/dist/dist_handler.go:71 github.com/milvus-io/milvus/internal/querycoordv2/dist.(*distHandler).start\n/usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit\n"]
```

**Comment by NicoYuan1986** [comment]
Not reproduced for a long time. milvus: 5d5a04d
