### ISSUE TITLE
[Bug]: etcdserver: request is too large, datanode Startup failed

### ISSUE THREAD

**Issue by stringk245** [milvus-io/milvus#21840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.2
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.2
- OS(Ubuntu or CentOS): Ubuntu 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1.datanode Startup failed;
2. Restart etcd success and Restart datanode still failed

### Expected Behavior

datanode Startup success

### Steps To Reproduce

```markdown
datanode fails after running for a while and fails to restart
```

### Milvus Log

# datacoord

```text
[2023/01/28 03:29:47.325 +00:00] [DEBUG] [datacoord/service.go:162] ["startup success"] [module=DataCoord] 
time="2023-01-28T03:29:47Z" level=info msg="[Connected consumer]" consumerID=1 name=cydoy subscription=milvus-data-dataCoord topic="persistent://public/default/milvus-data-datacoord-timetick-channel" 
time="2023-01-28T03:29:47Z" level=info msg="[Created consumer]" consumerID=1 name=cydoy subscription=milvus-data-dataCoord topic="persistent://public/default/milvus-data-datacoord-timetick-channel" 
{"level":"warn","ts":"2023-01-28T03:39:50.669Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000312380/#initially=[milvus2-etcd:2379]","attempt":0,"error":"rpc error: code = InvalidArgument desc = etcdserver: request is too large"} 
{"level":"warn","ts":"2023-01-28T03:39:50.715Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000312380/#initially=[milvus2-etcd:2379]","attempt":0,"error":"rpc error: code = InvalidArgument desc = etcdserver: request is too large"} 
```

# datanode

```text
time="2023-01-28T03:40:33Z" level=info msg="[Reconnecting to broker in  101.193866ms]" consumerID=2 name=gzjeq subscription=milvus-data-dataNode-895-436163544965709825 topic="persistent://public/default/milvus-data-rootcoord-dml_0" 
time="2023-01-28T03:40:33Z" level=info msg="[Connected consumer]" consumerID=2 name=gzjeq subscription=milvus-data-dataNode-895-436163544965709825 topic="persistent://public/default/milvus-data-rootcoord-dml_0" 
time="2023-01-28T03:40:33Z" level=info msg="[Reconnected consumer to broker]" consumerID=2 name=gzjeq subscription=milvus-data-dataNode-895-436163544965709825 topic="persistent://public/default/milvus-data-rootcoord-dml_0" 
time="2023-01-28T03:40:33Z" level=info msg="[Created producer]" cnx="10.19.58.67:39606 -> 10.19.56.63:6650" producerID=3 producer_name=milvus2-pulsar-0-5386 topic="persistent://public/default/milvus-data-rootcoord-delta_0" 
time="2023-01-28T03:40:33Z" level=info msg="[Created producer]" cnx="10.19.58.67:39606 -> 10.19.56.63:6650" producerID=4 producer_name=milvus2-pulsar-0-5387 topic="persistent://public/default/milvus-data-datacoord-timetick-channel" 
time="2023-01-28T03:40:58Z" level=info msg="[Connected consumer]" consumerID=3 name=vlyvc subscription=milvus-data-dataNode-895-438383471040921601 topic="persistent://public/default/milvus-data-rootcoord-dml_3" 
time="2023-01-28T03:40:58Z" level=info msg="[Created consumer]" consumerID=3 name=vlyvc subscription=milvus-data-dataNode-895-438383471040921601 topic="persistent://public/default/milvus-data-rootcoord-dml_3" 
time="2023-01-28T03:40:58Z" level=info msg="Broker notification of Closed consumer: 3" local_addr="10.19.58.67:39606" remote_addr="pulsar://milvus2-pulsar-proxy:6650" 
time="2023-01-28T03:40:58Z" level=info msg="[Reconnecting to broker in  114.848188ms]" consumerID=3 name=vlyvc subscription=milvus-data-dataNode-895-438383471040921601 topic="persistent://public/default/milvus-data-rootcoord-dml_3" 
time="2023-01-28T03:40:58Z" level=info msg="[Connected consumer]" consumerID=3 name=vlyvc subscription=milvus-data-dataNode-895-438383471040921601 topic="persistent://public/default/milvus-data-rootcoord-dml_3" 
time="2023-01-28T03:40:58Z" level=info msg="[Reconnected consumer to broker]" consumerID=3 name=vlyvc subscription=milvus-data-dataNode-895-438383471040921601 topic="persistent://public/default/milvus-data-rootcoord-dml_3" 
time="2023-01-28T03:40:58Z" level=info msg="[Created producer]" cnx="10.19.58.67:39606 -> 10.19.56.63:6650" producerID=5 producer_name=milvus2-pulsar-0-5388 topic="persistent://public/default/milvus-data-rootcoord-delta_3" 
time="2023-01-28T03:40:58Z" level=info msg="[Created producer]" cnx="10.19.58.67:39606 -> 10.19.56.63:6650" producerID=6 producer_name=milvus2-pulsar-0-5389 topic="persistent://public/default/milvus-data-datacoord-timetick-channel" 
panic: All attempts results: 
attempt #1:data service save bin log path failed, reason = etcdserver: request is too large 
attempt #2:data service save bin log path failed, reason = etcdserver: request is too large 
attempt #3:data service save bin log path failed, reason = etcdserver: request is too large 
attempt #4:data service save bin log path failed, reason = etcdserver: request is too large 
attempt #5:data service save bin log path failed, reason = etcdserver: request is too large 
attempt #6:data service save bin log path failed, reason = etcdserver: request is too large 
attempt #7:data service save bin log path failed, reason = etcdserver: request is too large 
attempt #8:data service save bin log path failed, reason = etcdserver: request is too large 
attempt #9:data service save bin log path failed, reason = etcdserver: request is too large 
attempt #10:data service save bin log path failed, reason = etcdserver: request is too large 
 
 
goroutine 928440 [running]: 
github.com/milvus-io/milvus/internal/datanode.flushNotifyFunc.func1(0xc001e1b220) 
	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_manager.go:827 +0x1688 
github.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).waitFinish(0xc000dde600, 0xc0015a2720, 0xc0017c2730) 
	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_task.go:201 +0xbd 
created by github.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).init.func1 
	/go/src/github.com/milvus-io/milvus/internal/datanode/flush_task.go:119 +0xb0 
```

# etcd 

```text
{"level":"warn","ts":"2023-01-28T06:40:37.477Z","caller":"wal/wal.go:802","msg":"slow fdatasync","took":"1.460378765s","expected-duration":"1s"} 
{"level":"warn","ts":"2023-01-28T06:40:45.835Z","caller":"etcdserver/util.go:166","msg":"apply request took too long","took":"306.70564ms","expected-duration":"100ms","prefix":"","request":"header:<ID:16167507008610748144 > put:<key:\"milvus-data/kv/index_gid/idTimestamp\" value_size:8 >","response":"size:7"} 
{"level":"warn","ts":"2023-01-28T06:41:27.105Z","caller":"etcdserver/util.go:166","msg":"apply request took too long","took":"812.278636ms","expected-duration":"100ms","prefix":"","request":"header:<ID:1627354136644260885 > txn:<compare:<> success:<request_put:<key:\"milvus-data/meta/channelwatch/936/milvus-data-rootcoord-dml_16_436274110148640769v0\" value_size:302 > request_delete_range:<key:\"milvus-data/meta/channelwatch/938/milvus-data-rootcoord-dml_16_436274110148640769v0\" > > failure:<>>","response":"size:31"} 
{"level":"warn","ts":"2023-01-28T06:42:08.322Z","caller":"wal/wal.go:802","msg":"slow fdatasync","took":"2.00367309s","expected-duration":"1s"} 
{"level":"warn","ts":"2023-01-28T06:42:16.765Z","caller":"etcdserver/util.go:166","msg":"apply request took too long","took":"434.384692ms","expected-duration":"100ms","prefix":"","request":"header:<ID:1627354136644260924 > txn:<compare:<> success:<request_put:<key:\"milvus-data/meta/channelwatch/936/milvus-data-rootcoord-dml_17_436274110148640769v1\" value_size:294 > request_delete_range:<key:\"milvus-data/meta/channelwatch/938/milvus-data-rootcoord-dml_17_436274110148640769v1\" > > failure:<>>","response":"size:31"} 
{"level":"warn","ts":"2023-01-28T06:42:19.933Z","caller":"etcdserver/util.go:166","msg":"apply request took too long","took":"511.45607ms","expected-duration":"100ms","prefix":"","request":"header:<ID:16167507008610748264 > put:<key:\"milvus-data/kv/gid/idTimestamp\" value_size:8 >","response":"size:7"} 
{"level":"warn","ts":"2023-01-28T06:42:36.902Z","caller":"etcdserver/util.go:166","msg":"apply request took too long","took":"373.131489ms","expected-duration":"100ms","prefix":"","request":"header:<ID:16167507008610748285 > put:<key:\"milvus-data/kv/index_gid/idTimestamp\" value_size:8 >","response":"size:7"} 
{"level":"warn","ts":"2023-01-28T06:42:38.045Z","caller":"etcdserver/util.go:166","msg":"apply request took too long","took":"625.456785ms","expected-duration":"100ms","prefix":"","request":"header:<ID:16167507008610748286 > put:<key:\"milvus-data/kv/gid/idTimestamp\" value_size:8 >","response":"size:7"} 
{"level":"warn","ts":"2023-01-28T06:43:20.641Z","caller":"wal/wal.go:802","msg":"slow fdatasync","took":"2.57490595s","expected-duration":"1s"} 
{"level":"info","ts":"2023-01-28T06:45:21.413Z","caller":"mvcc/index.go:214","msg":"compact tree index","revision":23838254} 
{"level":"info","ts":"2023-01-28T06:45:21.413Z","caller":"mvcc/kvstore_compaction.go:57","msg":"finished scheduled compaction","compact-revision":23838254,"took":"496.792µs"} 
{"level":"info","ts":"2023-01-28T06:50:21.422Z","caller":"mvcc/index.go:214","msg":"compact tree index","revision":23838675} 
{"level":"info","ts":"2023-01-28T06:50:21.423Z","caller":"mvcc/kvstore_compaction.go:57","msg":"finished scheduled compaction","compact-revision":23838675,"took":"480.89µs"} 
{"level":"info","ts":"2023-01-28T06:50:31.021Z","caller":"traceutil/trace.go:171","msg":"trace[247718525] transaction","detail":"{read_only:false; number_of_response:0; response_revision:23839687; }","duration":"126.446619ms","start":"2023-01-28T06:50:30.895Z","end":"2023-01-28T06:50:31.021Z","steps":["trace[247718525] 'process raft request'  (duration: 126.365681ms)"],"step_count":1} 
{"level":"warn","ts":"2023-01-28T06:53:22.917Z","caller":"etcdserver/util.go:166","msg":"apply request took too long","took":"229.03609ms","expected-duration":"100ms","prefix":"","request":"header:<ID:1627354136644261450 > txn:<compare:<> success:<request_delete_range:<key:\"milvus-data/meta/channelwatch/939/milvus-data-rootcoord-dml_17_436274110148640769v1\" > > failure:<>>","response":"size:22"} 
{"level":"info","ts":"2023-01-28T06:55:21.433Z","caller":"mvcc/index.go:214","msg":"compact tree index","revision":23839095} 
{"level":"info","ts":"2023-01-28T06:55:21.434Z","caller":"mvcc/kvstore_compaction.go:57","msg":"finished scheduled compaction","compact-revision":23839095,"took":"488.93µs"} 
{"level":"info","ts":"2023-01-28T07:00:21.464Z","caller":"mvcc/index.go:214","msg":"compact tree index","revision":23839528} 
{"level":"info","ts":"2023-01-28T07:00:21.465Z","caller":"mvcc/kvstore_compaction.go:57","msg":"finished scheduled compaction","compact-revision":23839528,"took":"489.896µs"} 
{"level":"info","ts":"2023-01-28T07:05:21.521Z","caller":"mvcc/index.go:214","msg":"compact tree index","revision":23839951} 
{"level":"info","ts":"2023-01-28T07:05:21.521Z","caller":"mvcc/kvstore_compaction.go:57","msg":"finished scheduled compaction","compact-revision":23839951,"took":"521.494µs"} 
{"level":"info","ts":"2023-01-28T07:10:21.595Z","caller":"mvcc/index.go:214","msg":"compact tree index","revision":23840381} 
{"level":"info","ts":"2023-01-28T07:10:21.597Z","caller":"mvcc/kvstore_compaction.go:57","msg":"finished scheduled compaction","compact-revision":23840381,"took":"806.931µs"} 
{"level":"info","ts":"2023-01-28T07:15:21.549Z","caller":"mvcc/index.go:214","msg":"compact tree index","revision":23840802} 
{"level":"info","ts":"2023-01-28T07:15:21.550Z","caller":"mvcc/kvstore_compaction.go:57","msg":"finished scheduled compaction","compact-revision":23840802,"took":"777.59µs"} 
{"level":"info","ts":"2023-01-28T07:20:21.579Z","caller":"mvcc/index.go:214","msg":"compact tree index","revision":23841229} 
{"level":"info","ts":"2023-01-28T07:20:21.580Z","caller":"mvcc/kvstore_compaction.go:57","msg":"finished scheduled compaction","compact-revision":23841229,"took":"451.873µs"} 
```

# client pymilvus

```text
<MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:\nattempt #1:fail to get shard leaders from QueryCoord: no replica available\nattempt 
#2:fail to get shard leaders from QueryCoord: no replica available\nattempt 
#3:fail to get shard leaders from QueryCoord: no replica available\nattempt 
#4:fail to get shard leaders from QueryCoord: no replica available\nattempt 
#5:fail to get shard leaders from QueryCoord: no replica available\nattempt 
#6:fail to get shard leaders from QueryCoord: no replica available\nattempt 
#7:fail to get shard leaders from QueryCoord: no replica available\nattempt 
#8:context deadline exceeded\n)>
```

### Anything else?

rootcoord  querycoord querynode indexcoord indexnode  is normal

**Comment by xiaofan-luan** [comment]
upgrade to 2.2 would solve the issue.
this is already fixed #19123

**Comment by stringk245** [comment]
> upgrade to 2.2 would solve the issue. this is already fixed #19123


Is there any workaround without upgrading?

**Comment by xiaofan-luan** [comment]
change ETCD_MAX_REQUEST_BYTES/–max-request-bytes in etcd config to a larger value can help. 
see etcd config https://etcd.io/docs/v3.3/op-guide/configuration/

**Comment by xiaofan-luan** [comment]
but again the request is already as large as 1.5MB. 
this usually means you have many delete or small files(triggered by flush) so I highly recommend you to upgrade sometime in the future

**Comment by stringk245** [comment]
> 

How long does it take to migrate 1 million data?
https://milvus.io/docs/upgrade_milvus_cluster-helm.md

**Comment by xiaofan-luan** [comment]
we just change meta data, so it should be pretty fast. 
and if you can rebuild index, that would be even faster so you don't need to run the ungrade script.
but any way you'd better change etcd config and recover before upgrade

**Comment by stringk245** [comment]
> ou don't need to run the ungrade script.

1. Stop all of the Milvus components？？  Includes etcd、 minio and pulsar  also need stop？？
2.  run or  don't need to run [migration script](https://github.com/milvus-io/milvus/blob/master/deployments/migrate-meta/migrate.sh)??

**Comment by yanliang567** [comment]
/assign @LoveEachDay 
could you please give a hand on this issue about how to upgrade to milvus 2.2.x

**Comment by xiaofan-luan** [comment]
> > ou don't need to run the ungrade script.
> 
> 1. Stop all of the Milvus components？？  Includes etcd、 minio and pulsar  also need stop？？
> 2. run or  don't need to run [migration script](https://github.com/milvus-io/milvus/blob/master/deployments/migrate-meta/migrate.sh)??
>    ![image](https://user-images.githubusercontent.com/11296126/215261048-8e13ad30-56d1-45e4-aa8a-49ab5c5dec6b.png)

based on if you want to rebuild index. if no then you need to migrate metadata
