### ISSUE TITLE
[Bug]: [Nightly]Milvus crashed with message 'send on closed channel'

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#21929]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 5d5a04d
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.0.dev26
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

A case failed reporting 'Fail connecting to server on mdp-270-n-milvus.milvus-ci:19530. Timeout'
1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/270/pipeline/187/
```
[2023-02-01T19:33:18.605Z] [2023-02-01 18:53:15 - ERROR - ci_test]: Traceback (most recent call last):
[2023-02-01T19:33:18.605Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 113, in _wait_for_channel_ready
[2023-02-01T19:33:18.605Z]     grpc.channel_ready_future(self._channel).result(timeout=timeout)
[2023-02-01T19:33:18.605Z]   File "/usr/local/lib/python3.8/site-packages/grpc/_utilities.py", line 139, in result
[2023-02-01T19:33:18.605Z]     self._block(timeout)
[2023-02-01T19:33:18.605Z]   File "/usr/local/lib/python3.8/site-packages/grpc/_utilities.py", line 85, in _block
[2023-02-01T19:33:18.605Z]     raise grpc.FutureTimeoutError()
[2023-02-01T19:33:18.605Z] grpc.FutureTimeoutError
[2023-02-01T19:33:18.605Z] 
[2023-02-01T19:33:18.605Z] The above exception was the direct cause of the following exception:
[2023-02-01T19:33:18.605Z] 
[2023-02-01T19:33:18.605Z] Traceback (most recent call last):
[2023-02-01T19:33:18.605Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2023-02-01T19:33:18.605Z]     res = func(*args, **_kwargs)
[2023-02-01T19:33:18.605Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2023-02-01T19:33:18.605Z]     return func(*arg, **kwargs)
[2023-02-01T19:33:18.605Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 303, in connect
[2023-02-01T19:33:18.605Z]     connect_milvus(**kwargs, user=user, password=password)
[2023-02-01T19:33:18.605Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 274, in connect_milvus
[2023-02-01T19:33:18.605Z]     gh._wait_for_channel_ready(timeout=timeout)
[2023-02-01T19:33:18.605Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 116, in _wait_for_channel_ready
[2023-02-01T19:33:18.605Z]     raise MilvusException(Status.CONNECT_FAILED,
[2023-02-01T19:33:18.605Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on mdp-270-n-milvus.milvus-ci:19530. Timeout)>
[2023-02-01T19:33:18.605Z]  (api_request.py:39)
[2023-02-01T19:33:18.605Z] [2023-02-01 18:53:15 - ERROR - ci_test]: (api_response) : <MilvusException: (code=2, message=Fail connecting to server on mdp-270-n-milvus.milvus-ci:19530. Timeout)> (api_request.py:40)
[2023-02-01T19:33:18.605Z] _ TestsearchPagination.test_searc
```
2. failed time: [2023-02-01T18:53:16.243Z] [gw4] [ 83%] FAILED testcases/test_search.py::TestsearchPagination::test_search_pagination_after_different_index[True-0-False-ANNOY-params5]

### Expected Behavior

pass

### Milvus Log

1. log: [artifacts-milvus-distributed-pulsar-nightly-270-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/270/artifact/artifacts-milvus-distributed-pulsar-nightly-270-pymilvus-e2e-logs.tar.gz)
2. file: ci.var.log.containers.mdp-270-n-minio-6dcc46858d-zv946_milvus-ci_minio-2be3e32aae5d08f591b1a2533167a5d720278a155949283a62be47461f76a2fb.log
3. error:
```
2023-02-02T01:55:37.330065329+08:00 stdout F WARNING: MINIO_ACCESS_KEY and MINIO_SECRET_KEY are deprecated.
2023-02-02T01:55:37.330086692+08:00 stdout F          Please use MINIO_ROOT_USER and MINIO_ROOT_PASSWORD
2023-02-02T01:55:37.362871905+08:00 stdout F WARNING: Detected default credentials 'minioadmin:minioadmin', we recommend that you change these values with 'MINIO_ROOT_USER' and 'MINIO_ROOT_PASSWORD' environment variables
2023-02-02T01:55:37.519179992+08:00 stdout F API: http://10.105.7.254:9000  http://127.0.0.1:9000
2023-02-02T01:55:37.519271808+08:00 stdout F
2023-02-02T01:55:37.519277305+08:00 stdout F Console: http://10.105.7.254:41125 http://127.0.0.1:41125
2023-02-02T01:55:37.519279416+08:00 stdout F
2023-02-02T01:55:37.519281657+08:00 stdout F Documentation: https://docs.min.io
2023-02-02T01:55:37.519283574+08:00 stdout F
2023-02-02T01:55:37.519286117+08:00 stdout F WARNING: Console endpoint is listening on a dynamic port (41125), please use --console-address ":PORT" to choose a static port.
2023-02-02T01:55:38.455158373+08:00 stdout F
2023-02-02T01:55:38.455173273+08:00 stdout F  You are running an older version of MinIO released 10 months ago
2023-02-02T01:55:38.45517672+08:00 stdout F  Update: Run `mc admin update`
2023-02-02T01:55:38.455178737+08:00 stdout F
2023-02-02T01:55:38.455180608+08:00 stdout F
2023-02-02T03:33:33.058391182+08:00 stdout F Exiting on signal: TERMINATED
2023-02-02T03:33:33.061810923+08:00 stderr F panic: send on closed channel
2023-02-02T03:33:33.06183131+08:00 stderr F
2023-02-02T03:33:33.061838775+08:00 stderr F goroutine 469524 [running]:
2023-02-02T03:33:33.061846108+08:00 stderr F github.com/minio/minio/cmd.(*FSObjects).NSScanner.func1()
2023-02-02T03:33:33.061866177+08:00 stderr F    github.com/minio/minio/cmd/fs-v1.go:298 +0x188
2023-02-02T03:33:33.061871955+08:00 stderr F created by github.com/minio/minio/cmd.(*FSObjects).NSScanner
2023-02-02T03:33:33.061876944+08:00 stderr F    github.com/minio/minio/cmd/fs-v1.go:290 +0x8c5

```

**Comment by sunby** [comment]
related issue #21972

**Comment by NicoYuan1986** [comment]
Update: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/86/pipeline/144

milvus: 68156b3
pymilvus: 2.3.0.dev26

1. log: [artifacts-milvus-distributed-kafka-nightly-86-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/86/artifact/artifacts-milvus-distributed-kafka-nightly-86-pymilvus-e2e-logs.tar.gz)
2. failed time: [2023-02-04T20:15:00.896Z] [gw3] [ 35%] FAILED testcases/test_partition.py::TestPartitionParams::test_load_partition_replica_non_number[\u4e2d\u6587]
3. error log file: ci.var.log.containers.mdk-86-n-minio-56b68cd5fd-526x2_milvus-ci_minio-497508de4a7d83df8a47c727d997ab631499c3181386622796ad11ecae7d6f61.log
```
2023-02-05T05:30:02.268788988+08:00 stderr F panic: send on closed channel
2023-02-05T05:30:02.268823704+08:00 stderr F
2023-02-05T05:30:02.268829499+08:00 stderr F goroutine 440777 [running]:
2023-02-05T05:30:02.268833506+08:00 stderr F github.com/minio/minio/cmd.(*FSObjects).NSScanner.func1()
2023-02-05T05:30:02.268837174+08:00 stderr F    github.com/minio/minio/cmd/fs-v1.go:298 +0x188
2023-02-05T05:30:02.268850487+08:00 stderr F created by github.com/minio/minio/cmd.(*FSObjects).NSScanner
2023-02-05T05:30:02.268854698+08:00 stderr F    github.com/minio/minio/cmd/fs-v1.go:290 +0x8c5
```

**Comment by yah01** [comment]
/assign @NicoYuan1986 
plz help verify with #21981

**Comment by NicoYuan1986** [comment]
Fixed. master-20230206-ffdb6529
