### ISSUE TITLE
[Bug]: create index timeout 

### ISSUE THREAD

**Issue by chencoyote** [milvus-io/milvus#21932]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.2.2
- Deployment mode(standalone or cluster):standalone 
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): centOS
- CPU/Memory: 2 core 4G memory
- GPU: 
- Others:
```

### Current Behavior

run bootcamp image  bootcamp/solutions/image/reverse_image_search/quick_deploy/server/src/main.py and upload images

```
2023-02-02 00:33:54,581 - 140465681528640 - main.py-main:125 - INFO: Successfully count the number of images!
2023-02-02 00:33:54,581 ｜ INFO ｜ main.py ｜ count_images ｜ 125 ｜ Successfully count the number of images!
INFO:     10.18.192.250:12343 - "POST /img/count HTTP/1.1" 200 OK
INFO:     10.18.192.250:42694 - "OPTIONS /img/load HTTP/1.1" 200 OK
/root/.conda/envs/ecdb/lib/python3.7/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libc10_cuda.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
2023-02-02 00:34:04,177 - 140465681528640 - helpers.py-helpers:247 - INFO: Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth)
2023-02-02 00:34:04,177 ｜ INFO ｜ helpers.py ｜ load_pretrained ｜ 247 ｜ Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth)
Extracting feature from image No. 1 , 1 images in total
2023-02-02 00:34:04,514 - 140465681528640 - milvus_helpers.py-milvus_helpers:51 - DEBUG: Create Milvus collection: milvus_img_search
2023-02-02 00:34:04,537 - 140465681528640 - decorators.py-decorators:73 - ERROR: RPC error: [load_collection], <BaseException: (code=1, message=index doesn't exist, collectionID 439161214444965414)>, <Time:{'RPC start': '2023-02-02 00:34:04.535328', 'RPC error': '2023-02-02 00:34:04.537397'}>
2023-02-02 00:34:04,537 ｜ ERROR ｜ decorators.py ｜ handler ｜ 73 ｜ RPC error: [load_collection], <BaseException: (code=1, message=index doesn't exist, collectionID 439161214444965414)>, <Time:{'RPC start': '2023-02-02 00:34:04.535328', 'RPC error': '2023-02-02 00:34:04.537397'}>
2023-02-02 00:34:04,537 - 140465681528640 - milvus_helpers.py-milvus_helpers:73 - ERROR: Failed to load data to Milvus: <BaseException: (code=1, message=index doesn't exist, collectionID 439161214444965414)>
2023-02-02 00:34:04,537 ｜ ERROR ｜ milvus_helpers.py ｜ insert ｜ 73 ｜ Failed to load data to Milvus: <BaseException: (code=1, message=index doesn't exist, collectionID 439161214444965414)>
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/work/milvus-install/demo/bootcamp-master/solutions/image/reverse_image_search/quick_deploy/server/src/milvus_helpers.py", line 68, in insert
    self.collection.load()
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/pymilvus/orm/collection.py", line 453, in load
    conn.load_collection(self._name, timeout=timeout, **kwargs)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 666, in load_collection
    raise BaseException(response.error_code, response.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=index doesn't exist, collectionID 439161214444965414)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/fastapi/routing.py", line 215, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/fastapi/routing.py", line 149, in run_endpoint_function
    return await dependant.call(**values)
  File "main.py", line 70, in load_images
    total_num = do_load(item.Table, item.File, MODEL, MILVUS_CLI, MYSQL_CLI)
  File "/root/work/milvus-install/demo/bootcamp-master/solutions/image/reverse_image_search/quick_deploy/server/src/operations/load.py", line 59, in do_load
    ids = milvus_client.insert(table_name, vectors)
  File "/root/work/milvus-install/demo/bootcamp-master/solutions/image/reverse_image_search/quick_deploy/server/src/milvus_helpers.py", line 74, in insert
    sys.exit(1)
SystemExit: 1
2023-02-02 00:34:04,537 - 140465681528640 - h11_impl.py-h11_impl:399 - ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/root/work/milvus-install/demo/bootcamp-master/solutions/image/reverse_image_search/quick_deploy/server/src/milvus_helpers.py", line 68, in insert
    self.collection.load()
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/pymilvus/orm/collection.py", line 453, in load
    conn.load_collection(self._name, timeout=timeout, **kwargs)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 666, in load_collection
    raise BaseException(response.error_code, response.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=index doesn't exist, collectionID 439161214444965414)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/fastapi/routing.py", line 215, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/fastapi/routing.py", line 149, in run_endpoint_function
    return await dependant.call(**values)
  File "main.py", line 70, in load_images
    total_num = do_load(item.Table, item.File, MODEL, MILVUS_CLI, MYSQL_CLI)
  File "/root/work/milvus-install/demo/bootcamp-master/solutions/image/reverse_image_search/quick_deploy/server/src/operations/load.py", line 59, in do_load
    ids = milvus_client.insert(table_name, vectors)
  File "/root/work/milvus-install/demo/bootcamp-master/solutions/image/reverse_image_search/quick_deploy/server/src/milvus_helpers.py", line 74, in insert
    sys.exit(1)
SystemExit: 1
2023-02-02 00:34:04,537 ｜ ERROR ｜ h11_impl.py ｜ run_asgi ｜ 399 ｜ Exception in ASGI application
Traceback (most recent call last):
  File "/root/work/milvus-install/demo/bootcamp-master/solutions/image/reverse_image_search/quick_deploy/server/src/milvus_helpers.py", line 68, in insert
    self.collection.load()
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/pymilvus/orm/collection.py", line 453, in load
    conn.load_collection(self._name, timeout=timeout, **kwargs)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 666, in load_collection
    raise BaseException(response.error_code, response.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=index doesn't exist, collectionID 439161214444965414)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/fastapi/routing.py", line 215, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/fastapi/routing.py", line 149, in run_endpoint_function
    return await dependant.call(**values)
  File "main.py", line 70, in load_images
    total_num = do_load(item.Table, item.File, MODEL, MILVUS_CLI, MYSQL_CLI)
  File "/root/work/milvus-install/demo/bootcamp-master/solutions/image/reverse_image_search/quick_deploy/server/src/operations/load.py", line 59, in do_load
    ids = milvus_client.insert(table_name, vectors)
  File "/root/work/milvus-install/demo/bootcamp-master/solutions/image/reverse_image_search/quick_deploy/server/src/milvus_helpers.py", line 74, in insert
    sys.exit(1)
SystemExit: 1
INFO:     10.18.192.250:42694 - "POST /img/load HTTP/1.1" 500 Internal Server Error
```

### Expected Behavior

make test file  test_milvus.py

```
import os
from pymilvus import connections,utility, Collection

MILVUS_HOST = os.getenv("MILVUS_HOST", "127.0.0.1")
MILVUS_PORT = int(os.getenv("MILVUS_PORT", "19530"))

connections.connect(host=MILVUS_HOST, port=MILVUS_PORT)
utility.has_collection('milvus_img_search')
collect = Collection('milvus_img_search')
default_index = {"index_type": "IVF_SQ8", "metric_type": "L2", "params": {"nlist": 2048}}
collect.create_index(field_name="embedding", index_params=default_index)
print(collect.index)
```

and run `test_milvus.py` wait seconds ctrl + c

output

```
python test_milvus.py
^CTraceback (most recent call last):
  File "test_milvus.py", line 12, in <module>
    collect.create_index(field_name="embedding", index_params=default_index)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/pymilvus/orm/collection.py", line 1033, in create_index
    timeout=timeout, **kwargs)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 596, in create_index
    field_name=field_name, timeout=timeout)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/root/.conda/envs/ecdb/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 647, in wait_for_creating_index
    time.sleep(0.5)
KeyboardInterrupt
```

**Comment by xiaofan-luan** [comment]
index creation takes long time but it should be blocked forever. What do you mean by timeout?

**Comment by chencoyote** [comment]
yes, it should be blocked, maybe i saw the code in&nbsp; grpc_handler.py has a 'timeout' pa
rameter, but i didn't wait to confirm whether it timeout.&nbsp;

---Original---
From: ***@***.***&gt;
Date: Thu, Feb 2, 2023 15:57 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [milvus-io/milvus] [Bug]: create index timeout  (Issue #21932)




 
index creation takes long time but it should be blocked forever. What do you mean by timeout?

**Comment by yanliang567** [comment]
as you were running on 2 core, i think building index could cost a few mins depending on how many vectors did you inserted. could you please retry with more cpu cores or wait for more mins ?

/assign @chencoyote 
/unassign
