### ISSUE TITLE
[Bug]: [ResourceGroup] Milvus proxy crashes when trying to describe a dropped resource group

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#21971]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230202-d41cc0b2
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):  2.3.0.dev29
```

### Current Behavior

Milvus proxy crashes
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2ac3a81]

goroutine 378 [running]:
panic({0x334aec0, 0x4e3fef0})
        /usr/local/go/src/runtime/panic.go:941 +0x397 fp=0xc00136bc08 sp=0xc00136bb48 pc=0x11eacf7
runtime.panicmem(...)
        /usr/local/go/src/runtime/panic.go:220
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:818 +0x336 fp=0xc00136bc58 sp=0xc00136bc08 pc=0x1201d16
github.com/milvus-io/milvus/internal/proxy.(*DescribeResourceGroupTask).Execute(0xc000cbcd40, {0x3ac6ed8, 0xc000d05ce0})
        /go/src/github.com/milvus-io/milvus/internal/proxy/task.go:2120 +0x101 fp=0xc00136bcf8 sp=0xc00136bc58 pc=0x2ac3a81
github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask(0xc000f03a80?, {0x3ae39f8, 0xc000cbcd40}, {0x3ae2218, 0xc00086c5f0})
        /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:453 +0x443 fp=0xc00136bf40 sp=0xc00136bcf8 pc=0x2adf8c3
github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop(0xc0004f9e00)
        /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:480 +0x116 fp=0xc00136bfc8 sp=0xc00136bf40 pc=0x2ae0016
github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).Start.func1()
        /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:521 +0x26 fp=0xc00136bfe0 sp=0xc00136bfc8 pc=0x2ae08e6
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00136bfe8 sp=0xc00136bfe0 pc=0x12200a1
created by github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).Start
        /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:521 +0x76
```

### Expected Behavior

fail with an error msg, no crash

### Steps To Reproduce

```markdown
1. create a rg with name abc
  2. list rgs and describe the rg abc
  3. drop the rg abc
  4. list rgs and describe the rg abc
```

### Milvus Log

[rg.proxy.crash.log](https://github.com/milvus-io/milvus/files/10577869/rg.proxy.crash.log)

logs for pods around 2023/02/03 10:02:02:
```
yanliang-master-rg-milvus-datacoord-9d4c5cf96-s6f4w               1/1     Running            0                24h
yanliang-master-rg-milvus-datanode-5fb8fcc477-5gdjs               1/1     Running            0                24h
yanliang-master-rg-milvus-indexcoord-7f694b8b76-twcz2             1/1     Running            0                24h
yanliang-master-rg-milvus-indexnode-7688cd8575-xgvb6              1/1     Running            0                24h
yanliang-master-rg-milvus-proxy-6568bc4c4f-4mr8k                  1/1     Running            20 (7m43s ago)   24h
yanliang-master-rg-milvus-querycoord-b7cf6dddd-zl6ln              1/1     Running            0                24h
yanliang-master-rg-milvus-querynode-6bdd98c576-bpff8              1/1     Running            0                24h
yanliang-master-rg-milvus-rootcoord-7ddd74dc44-x8zrq              1/1     Running            0                24h
```

**Comment by yanliang567** [comment]
proxy does not crash pymilvus-2.3.0.dev31 with master-20230208-403f85a9, but the error is not meaningful.
`[2023-02-08 15:00:16,489 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Unexpected error, message=<error_code>)> (api_request.py:40)
`

**Comment by yanliang567** [comment]
verified on pymilvus 2.3 dev38
` ct.err_msg: "failed to describe resource group, err=resource group doesn't exist"}`
