### ISSUE TITLE
[Bug]: Load failed with error `err=failed to update next targets for collection[context deadline exceeded]` after datacoord pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#21989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230205-ae305a54
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):Pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2023-02-05T20:45:50.239Z] [2023-02-05 20:45:26 - INFO - ci_test]: [test][2023-02-05T20:45:25Z] [1.01423774s] e2e__k0NEGYXr create_index -> Status(code=0, message=) (wrapper.py:30)

[2023-02-05T20:45:50.239Z] [2023-02-05 20:45:26 - INFO - ci_test]: assert index: 121.54544806480408 (test_e2e.py:53)

[2023-02-05T20:45:50.239Z] [2023-02-05 20:45:26 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:56)

[2023-02-05T20:45:50.239Z] [2023-02-05 20:45:48 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=failed to load collection, err=failed to update next targets for collection[context deadline exceeded])>, <Time:{'RPC start': '2023-02-05 20:45:26.875677', 'RPC error': '2023-02-05 20:45:48.805299'}> (decorators.py:108)

[2023-02-05T20:45:50.239Z] [2023-02-05 20:45:48 - ERROR - ci_test]: Traceback (most recent call last):

[2023-02-05T20:45:50.239Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2023-02-05T20:45:50.239Z]     res = func(*args, **_kwargs)

[2023-02-05T20:45:50.239Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2023-02-05T20:45:50.239Z]     return func(*arg, **kwargs)

[2023-02-05T20:45:50.239Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 364, in load

[2023-02-05T20:45:50.239Z]     conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)

[2023-02-05T20:45:50.239Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-02-05T20:45:50.239Z]     raise e

[2023-02-05T20:45:50.239Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-02-05T20:45:50.239Z]     return func(*args, **kwargs)

[2023-02-05T20:45:50.239Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-02-05T20:45:50.239Z]     ret = func(self, *args, **kwargs)

[2023-02-05T20:45:50.239Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-02-05T20:45:50.239Z]     raise e

[2023-02-05T20:45:50.239Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-02-05T20:45:50.239Z]     return func(self, *args, **kwargs)

[2023-02-05T20:45:50.239Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 659, in load_collection

[2023-02-05T20:45:50.239Z]     raise MilvusException(response.error_code, response.reason)

[2023-02-05T20:45:50.239Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=failed to load collection, err=failed to update next targets for collection[context deadline exceeded])>

[2023-02-05T20:45:50.239Z]  (api_request.py:39)

[2023-02-05T20:45:50.239Z] [2023-02-05 20:45:48 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=failed to load collection, err=failed to update next targets for collection[context deadline exceeded])> (api_request.py:40)

[2023-02-05T20:45:50.239Z] ------------- generated html file: file:///tmp/ci_logs/report.html -------------

[2023-02-05T20:45:50.239Z] =========================== short test summary info ============================

[2023-02-05T20:45:50.239Z] FAILED ../testcases/test_e2e.py::TestE2e::test_milvus_default - AssertionError
```

### Milvus Log

chaos type: pod-kill image tag: master-20230205-ae305a54 target pod: datacoord
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/1811/pipeline
log:
[artifacts-datacoord-pod-kill-1811-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/10637371/artifacts-datacoord-pod-kill-1811-server-logs.1.tar.gz)
[artifacts-datacoord-pod-kill-1811-pytest-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/10637372/artifacts-datacoord-pod-kill-1811-pytest-logs.1.tar.gz)

**Comment by zhuwenxing** [comment]
* load failed after upgrading from v2.2.2 to master-latest:
deploy task: upgrade old image tag: v2.2.2 new image tag: master-20230206-ffdb6529
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_kafka_cron/detail/deploy_test_kafka_cron/319/pipeline
log:
[artifacts-kafka-cluster-upgrade-319-server-second-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/10670906/artifacts-kafka-cluster-upgrade-319-server-second-deployment-logs.tar.gz)
[artifacts-kafka-cluster-upgrade-319-server-first-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/10670907/artifacts-kafka-cluster-upgrade-319-server-first-deployment-logs.tar.gz)
[artifacts-kafka-cluster-upgrade-319-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10670908/artifacts-kafka-cluster-upgrade-319-pytest-logs.tar.gz)

* load failed after indexnode pod kill chaos
chaos type: pod-kill image tag: master-20230206-ffdb6529 target pod: indexnode
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-cron/detail/chaos-test-kafka-cron/1757/pipeline
log:
[artifacts-indexnode-pod-kill-1757-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10670916/artifacts-indexnode-pod-kill-1757-server-logs.tar.gz)
[artifacts-indexnode-pod-kill-1757-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10670917/artifacts-indexnode-pod-kill-1757-pytest-logs.tar.gz)

* load failed after etcd pod kill chaos test
chaos type: pod-kill image tag: master-20230206-ffdb6529 target pod: etcd
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/1845/pipeline
log:
[artifacts-etcd-pod-kill-1845-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10670930/artifacts-etcd-pod-kill-1845-server-logs.tar.gz)
[artifacts-etcd-pod-kill-1845-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10670932/artifacts-etcd-pod-kill-1845-pytest-logs.tar.gz)

**Comment by weiliu1031** [comment]
related to #23924
should be fixed by #24057 
please verify this @zhuwenxing
