### ISSUE TITLE
[Bug]: [Nightly]Load balance failed because segment not found in source node

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#22015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:1f0214d
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus2.2.2.dev3
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Load balance failed because segment not found in source node.
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/88/pipeline/156
```
[2023-02-06T21:25:29.316Z] [2023-02-06 20:54:07 - ERROR - pymilvus.decorators]: RPC error: [load_balance], <MilvusException: (code=1, message=failed to balance segments, err=segment 439278237707787364 not found in source node 4)>, <Time:{'RPC start': '2023-02-06 20:54:07.367122', 'RPC error': '2023-02-06 20:54:07.368627'}> (decorators.py:108)
[2023-02-06T21:25:29.316Z] [2023-02-06 20:54:07 - ERROR - ci_test]: Traceback (most recent call last):
[2023-02-06T21:25:29.316Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2023-02-06T21:25:29.316Z]     res = func(*args, **_kwargs)
[2023-02-06T21:25:29.316Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2023-02-06T21:25:29.316Z]     return func(*arg, **kwargs)
[2023-02-06T21:25:29.316Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/utility.py", line 508, in load_balance
[2023-02-06T21:25:29.316Z]     return _get_connection(using).\
[2023-02-06T21:25:29.316Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2023-02-06T21:25:29.316Z]     raise e
[2023-02-06T21:25:29.316Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2023-02-06T21:25:29.316Z]     return func(*args, **kwargs)
[2023-02-06T21:25:29.316Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2023-02-06T21:25:29.316Z]     ret = func(self, *args, **kwargs)
[2023-02-06T21:25:29.316Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
[2023-02-06T21:25:29.316Z]     raise e
[2023-02-06T21:25:29.316Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2023-02-06T21:25:29.316Z]     return func(self, *args, **kwargs)
[2023-02-06T21:25:29.316Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 950, in load_balance
[2023-02-06T21:25:29.316Z]     raise MilvusException(status.error_code, status.reason)
[2023-02-06T21:25:29.316Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=failed to balance segments, err=segment 439278237707787364 not found in source node 4)>
[2023-02-06T21:25:29.316Z]  (api_request.py:39)
[2023-02-06T21:25:29.316Z] [2023-02-06 20:54:07 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=failed to balance segments, err=segment 439278237707787364 not found in source node 4)> (api_request.py:40)
```

### Expected Behavior

pass

### Milvus Log

1. log: [artifacts-milvus-distributed-kafka-nightly-88-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/88/artifact/artifacts-milvus-distributed-kafka-nightly-88-pymilvus-e2e-logs.tar.gz)
2. collection name: utility_cE8XMiYf
3. failed time: [2023-02-06T20:54:11.616Z] [gw3] [ 96%] FAILED testcases/test_utility.py::TestUtilityAdvanced::test_load_balance_normal

**Comment by NicoYuan1986** [comment]
Not reproduced.
