### ISSUE TITLE
[Bug]: Search and query failed with error `not loaded into memory when query` during rolling update

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#22028]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230207-883a79e4
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):kafka    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/12268675/217184403-10291b86-05be-4245-bdfe-c14f138d7c44.png)

```
[2023-02-07T07:16:16.225Z] [2023-02-07 07:16:14 - DEBUG - ci_test]: (api_request)  : [Collection.query] args: ['int64 in [2428, 623, 737, 330, 411]', None, None, 40], kwargs: {} (api_request.py:56)
[2023-02-07T07:16:16.226Z] [2023-02-07 07:16:14 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=collection:SearchChecker__GVwS8RWD or partition:[] not loaded into memory when search)>, <Time:{'RPC start': '2023-02-07 07:16:14.826107', 'RPC error': '2023-02-07 07:16:14.828139'}> (decorators.py:108)
[2023-02-07T07:16:16.226Z] [2023-02-07 07:16:14 - ERROR - ci_test]: Traceback (most recent call last):
[2023-02-07T07:16:16.226Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2023-02-07T07:16:16.226Z]     res = func(*args, **_kwargs)
[2023-02-07T07:16:16.226Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2023-02-07T07:16:16.226Z]     return func(*arg, **kwargs)
[2023-02-07T07:16:16.226Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 614, in search
[2023-02-07T07:16:16.226Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,
[2023-02-07T07:16:16.226Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
[2023-02-07T07:16:16.226Z]     raise e
[2023-02-07T07:16:16.226Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
[2023-02-07T07:16:16.226Z]     return func(*args, **kwargs)
[2023-02-07T07:16:16.226Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
[2023-02-07T07:16:16.226Z]     ret = func(self, *args, **kwargs)
[2023-02-07T07:16:16.226Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
[2023-02-07T07:16:16.226Z]     raise e
[2023-02-07T07:16:16.226Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
[2023-02-07T07:16:16.226Z]     return func(self, *args, **kwargs)
[2023-02-07T07:16:16.226Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 472, in search
[2023-02-07T07:16:16.226Z]     return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)
[2023-02-07T07:16:16.226Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 441, in _execute_search_requests
[2023-02-07T07:16:16.226Z]     raise pre_err
[2023-02-07T07:16:16.226Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 432, in _execute_search_requests
[2023-02-07T07:16:16.226Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2023-02-07T07:16:16.226Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection:SearchChecker__GVwS8RWD or partition:[] not loaded into memory when search)>
[2023-02-07T07:16:16.226Z]  (api_request.py:39)
[2023-02-07T07:16:16.226Z] [2023-02-07 07:16:14 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=collection:SearchChecker__GVwS8RWD or partition:[] not loaded into memory when search)> (api_request.py:40)
[2023-02-07T07:16:16.226Z] [2023-02-07 07:16:14 - INFO - ci_test]: [chaos-test][start time:2023-02-07T07:16:14Z][time cost:0.00545203s][operation_name:search][collection name:SearchChecker__GVwS8RWD] -> False (checker.py:53)
[2023-02-07T07:16:16.226Z] [2023-02-07 07:16:14 - ERROR - pymilvus.decorators]: RPC error: [query], <MilvusException: (code=1, message=collection:QueryChecker__ScWYjz8H or partition:[] not loaded into memory when query)>, <Time:{'RPC start': '2023-02-07 07:16:14.827264', 'RPC error': '2023-02-07 07:16:14.829731'}> (decorators.py:108)
[2023-02-07T07:16:16.226Z] [2023-02-07 07:16:14 - ERROR - ci_test]: Traceback (most recent call last):
[2023-02-07T07:16:16.226Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2023-02-07T07:16:16.226Z]     res = func(*args, **_kwargs)
[2023-02-07T07:16:16.226Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2023-02-07T07:16:16.226Z]     return func(*arg, **kwargs)
[2023-02-07T07:16:16.226Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 698, in query
[2023-02-07T07:16:16.226Z]     res = conn.query(self._name, expr, output_fields, partition_names,
[2023-02-07T07:16:16.226Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
[2023-02-07T07:16:16.226Z]     raise e
[2023-02-07T07:16:16.226Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
[2023-02-07T07:16:16.226Z]     return func(*args, **kwargs)
[2023-02-07T07:16:16.226Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
[2023-02-07T07:16:16.226Z]     ret = func(self, *args, **kwargs)
[2023-02-07T07:16:16.226Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
[2023-02-07T07:16:16.226Z]     raise e
[2023-02-07T07:16:16.226Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
[2023-02-07T07:16:16.226Z]     return func(self, *args, **kwargs)
[2023-02-07T07:16:16.226Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 903, in query
[2023-02-07T07:16:16.226Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2023-02-07T07:16:16.226Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection:QueryChecker__ScWYjz8H or partition:[] not loaded into memory when query)>
[2023-02-07T07:16:16.226Z]  (api_request.py:39)
[2023-02-07T07:16:16.226Z] [2023-02-07 07:16:14 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=collection:QueryChecker__ScWYjz8H or partition:[] not loaded into memory when query)> (api_request.py:40)
[2023-02-07T07:16:16.226Z] [2023-02-07 07:16:14 - INFO - ci_test]: [chaos-test][start time:2023-02-07T07:16:14Z][time cost:0.00533932s][operation_name:query][collection name:QueryChecker__ScWYjz8H] -> False (checker.py:53)
[2023-02-07T07:16:16.226Z] [2023-02-07 07:16:14 - INFO - ci_test]: Expect Succ: Op.insert succ rate 0.998995983935743, total: 996, average time: 0.1116 (chaos_commons.py:101)
[2023-02-07T07:16:16.226Z] [2023-02-07 07:16:14 - INFO - ci_test]: Expect Succ: Op.flush succ rate 0.9924242424242424, total: 132, average time: 6.9401 (chaos_commons.py:101)
[2023-02-07T07:16:16.226Z] [2023-02-07 07:16:14 - INFO - ci_test]: Expect Succ: Op.index succ rate 0.9949238578680203, total: 197, average time: 4.5464 (chaos_commons.py:101)
[2023-02-07T07:16:16.226Z] [2023-02-07 07:16:14 - INFO - ci_test]: Expect Succ: Op.search succ rate 0.11915367483296214, total: 898, average time: 1.4504 (chaos_commons.py:101)
[2023-02-07T07:16:16.226Z] [2023-02-07 07:16:14 - INFO - ci_test]: Expect Succ: Op.query succ rate 0.11817168338907469, total: 897, average time: 1.4731 (chaos_commons.py:101)
[2023-02-07T07:16:16.227Z] [2023-02-07 07:16:14 - INFO - ci_test]: Expect Succ: Op.delete succ rate 1.0, total: 1004, average time: 0.1016 (chaos_commons.py:101)
[2023-02-07T07:16:16.227Z] ------------- generated html file: file:///tmp/ci_logs/report.html -------------
[2023-02-07T07:16:16.227Z] =========================== short test summary info ============================
[2023-02-07T07:16:16.227Z] FAILED testcases/test_single_request_operation.py::TestOperations::test_operations - AssertionError: [93m
[2023-02-07T07:16:16.227Z] 
[2023-02-07T07:16:16.227Z] assert_expectations() called at[0m
[2023-02-07T07:16:16.227Z] [4m[94m"/home/jenkins/agent/workspace/tests/python_client/chaos/testcases/test_single_request_operation.py:82"[0m[93m in test_operations()
[2023-02-07T07:16:16.227Z] 
[2023-02-07T07:16:16.227Z] [91m[4mFailed Expectations : 2
[2023-02-07T07:16:16.227Z] [0m
[2023-02-07T07:16:16.227Z] 1: [91mFailed at "[0m[94m[4m/home/jenkins/agent/workspace/tests/python_client/chaos/chaos_commons.py:102[0m[91m", in assert_statistic()
[2023-02-07T07:16:16.227Z] 	[1m[4mErrorMessage:[0m[91m	Expect Succ: Op.search succ rate 0.11915367483296214, total: 898, average time: 1.4504[0m
[2023-02-07T07:16:16.227Z]             expect(succ_rate > 0.90 and total > 2,
[2023-02-07T07:16:16.227Z] 
[2023-02-07T07:16:16.227Z] 2: [91mFailed at "[0m[94m[4m/home/jenkins/agent/workspace/tests/python_client/chaos/chaos_commons.py:102[0m[91m", in assert_statistic()
[2023-02-07T07:16:16.227Z] 	[1m[4mErrorMessage:[0m[91m	Expect Succ: Op.query succ rate 0.11817168338907469, total: 897, average time: 1.4731[0m
[2023-02-07T07:16:16.227Z]             expect(succ_rate > 0.90 and total > 2,
[2023-02-07T07:16:16.227Z] ======================== 1 failed in 1257.70s (0:20:57) ========================
script returned exit code 1
```

### Expected Behavior

all operations can be successful during rolling update

### Milvus Log

milvus_mode: standalone mq type：kafka old image tag: v2.2.2 new image tag: 2.2.0-latest

failed job: 
https://qa-jenkins.milvus.io/blue/organizations/jenkins/rolling_update_test/detail/rolling_update_test/13/pipeline

log:
[artifacts-kafka-standalone-rolling-upgrade-13-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10672626/artifacts-kafka-standalone-rolling-upgrade-13-server-logs.tar.gz)
[artifacts-kafka-standalone-rolling-upgrade-13-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10672627/artifacts-kafka-standalone-rolling-upgrade-13-pytest-logs.tar.gz)

### Anything else?

It is not a stable issue, because with the same config, this pipeline https://qa-jenkins.milvus.io/blue/organizations/jenkins/rolling_update_test/detail/rolling_update_test/14/pipeline/330/ is successful

![image](https://user-images.githubusercontent.com/12268675/217184177-bccfda6b-800d-43d3-bced-9f2df3314d2f.png)

**Comment by zhuwenxing** [comment]
* milvus_mode: standalone mq type：pulsar old image tag: v2.2.2 new image tag: 2.2.0-20230207-4456365b
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/rolling_update_test/detail/rolling_update_test/20/pipeline/247
log:
[artifacts-pulsar-standalone-rolling-upgrade-20-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10681172/artifacts-pulsar-standalone-rolling-upgrade-20-server-logs.tar.gz)
[artifacts-pulsar-standalone-rolling-upgrade-20-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10681173/artifacts-pulsar-standalone-rolling-upgrade-20-pytest-logs.tar.gz)

* milvus_mode: standalone mq type：kafka old image tag: v2.2.2 new image tag: 2.2.0-20230207-4456365b
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/rolling_update_test/detail/rolling_update_test/21/pipeline
log:
[artifacts-kafka-standalone-rolling-upgrade-21-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10681175/artifacts-kafka-standalone-rolling-upgrade-21-server-logs.tar.gz)
[artifacts-kafka-standalone-rolling-upgrade-21-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10681176/artifacts-kafka-standalone-rolling-upgrade-21-pytest-logs.tar.gz)

**Comment by jaime0815** [comment]
pipeline https://qa-jenkins.milvus.io/blue/organizations/jenkins/rolling_update_test/detail/rolling_update_test/14/pipeline/330/ i

Before rolling upgrade, collection 439288476488141320 has already finished load operation.
```
[2023/02/07 06:55:51.288 +00:00] [INFO] [observers/collection_observer.go:306] ["collection load status updated"] [collectionID=439288476488141320] [loadPercentage=100] [collectionStatus=2]
```

After rolling upgrade,  Milvus is restarted.  The collection 439288476488141320 should load into memory automatically,  but loading fails due to getting collection schema timeout from RootCoord.
```
2023/02/07 06:58:56 maxprocs: Leaving GOMAXPROCS=64: CPU quota undefined

[2023/02/07 06:58:57.288 +00:00] [INFO] [task/scheduler.go:259] ["task added"] [task="[id=355] [type=3] [collectionID=439288476488141320] [replicaID=439288476539289626] [priority=0] [actionsCount=2] [actions={[type=1][node=12][streaming=false]}, {[type=2][node=2][streaming=false]}] [segmentID=439288476488141329]"]Show context
[2023/02/07 06:58:57.663 +00:00] [INFO] [task/executor.go:275] ["load segment task committed"] [taskID=355] [collectionID=439288476488141320] [segmentID=439288476488141329] [node=12] [source=3] [shardLeader=2]
[2023/02/07 06:58:59.279 +00:00] [INFO] [task/executor.go:328] ["release segment..."] [taskID=355] [collectionID=439288476488141320] [segmentID=439288476488141329] [node=2] [source=3] [shardLeader=2]
[2023/02/07 06:58:59.288 +00:00] [WARN] [task/executor.go:235] ["failed to get schema of collection"] [taskID=355] [collectionID=439288476488141320] [segmentID=439288476488141329] [node=12] [source=3] [error="context canceled"]
[2023/02/07 06:58:59.288 +00:00] [WARN] [task/executor.go:331] ["failed to release segment, it may be a false failure"] [taskID=355] [collectionID=439288476488141320] [segmentID=439288476488141329] [node=2] [source=3] [shardLeader=2] [error="context canceled"]
[2023/02/07 06:58:59.639 +00:00] [INFO] [querynode/impl.go:627] ["start to release segments"] [collectionID=439288476488141320] [segmentIDs="[439288476488141329]"]Show context
[2023/02/07 06:58:59.639 +00:00] [INFO] [querynode/partition.go:100] ["remove a segment from replica"] [collectionID=439288476488141320] [partitionID=439288476488141321] [segmentID=439288476488141329] [segmentType=Sealed]
[2023/02/07 06:58:59.639 +00:00] [INFO] [querynode/segment.go:238] ["delete segment from memory"] [collectionID=439288476488141320] [partitionID=439288476488141321] [segmentID=439288476488141329] [segmentType=Sealed]
[2023/02/07 06:58:59.639 +00:00] [INFO] [querynode/meta_replica.go:721] ["segment removed from collection replica"] ["QueryNode ID"=2] ["collection ID"=439288476488141320] ["partition ID"=439288476488141321] ["segment ID"=439288476488141329] ["segment type"=Sealed] ["row count"=1497] ["segment indexed fields"=1]


[2023/02/07 07:04:13.348 +00:00] [WARN] [proxy/task_scheduler.go:454] ["Failed to pre-execute task: collection:SearchChecker__GVwS8RWD or partition:[] not loaded into memory when search"] [traceID=3f2c66b471609299]
[2023/02/07 07:04:14.353 +00:00] [WARN] [proxy/task_scheduler.go:454] ["Failed to pre-execute task: collection:SearchChecker__GVwS8RWD or partition:[] not loaded into memory when search"] [traceID=5820d4b85a4dc130]
[2023/02/07 07:04:15.360 +00:00] [WARN] [proxy/task_scheduler.go:454] ["Failed to pre-execute task: collection:SearchChecker__GVwS8RWD or partition:[] not loaded into memory when search"] [traceID=4ca056e668cc10e2]

```

**Comment by yah01** [comment]
The QueryCoord failed to start (due to failed to pull target for previous loaded collections), but this activate procedure ignores the error and no retry @wayblink

**Comment by yah01** [comment]
> The QueryCoord failed to start (due to failed to pull target for previous loaded collections), but this activate procedure ignores the error and no retry @wayblink

This failure may be caused by DataCoord not ready, then QueryCoord can't pull information from it
/assign @wayblink

**Comment by yah01** [comment]
/assign @zhuwenxing 
plz check with #22091

**Comment by binbinlv** [comment]
@zhuwenxing 
Is it fixed?

**Comment by zhuwenxing** [comment]
The search and failed are still failed during the standalone rolling update.But the error changed to `message=checkIfLoaded failed when search, collection:SearchChecker__J6gj8J4s, partitions:[], err = GetCollectionInfo failed, collection = SearchChecker__J6gj8J4s, err = failed to show collections, err=NotHealthy`.

So I would like to close this issue, and open a new issue to trace the problem above
