### ISSUE TITLE
[Bug]: Crash querynode when search by batch of vectors

### ISSUE THREAD

**Issue by AlexeyIvanov8** [milvus-io/milvus#22078]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.2
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2): io.milvus:milvus-sdk-java:2.2.2
- OS(Ubuntu or CentOS): 
- CPU/Memory: 8/64Gb * 14 nodes
- GPU: 
- Others: 

Cluster yaml:

milvuscluster:
  components:
    dataCoord:
      replicas: 1
      resources:
        limits:
          cpu: 8
          memory: 16Gi
        requests:
          cpu: 1
          memory: 1Gi
    dataNode:
      replicas: 3
      resources:
        limits:
          cpu: 16
          memory: 64Gi
        requests:
          cpu: 1
          memory: 4Gi
    indexCoord:
      replicas: 1
      resources:
        limits:
          cpu: 8
          memory: 16Gi
        requests:
          cpu: 1
          memory: 1Gi
    indexNode:
      replicas: 4
      resources:
        limits:
          cpu: 32
          memory: 64Gi
        requests:
          cpu: 1
          memory: 4Gi
    queryCoord:
      replicas: 1
      resources:
        limits:
          cpu: 8
          memory: 16Gi
        requests:
          cpu: 1
          memory: 1Gi
    queryNode:
      replicas: 14
      resources:
        limits:
          cpu: 8
          memory: 64Gi
        requests:
          cpu: 1
          memory: 4Gi
    proxy:
      replicas: 1
      resources:
        limits:
          cpu: 8
          memory: 16Gi
        requests:
          cpu: 2
          memory: 8Gi
      serviceType: LoadBalancer
    rootCoord:
      replicas: 1
      resources:
        limits:
          cpu: 8
          memory: 8Gi
        requests:
          cpu: 1
          memory: 1Gi
  config:
    minio:
      bucketName: larva
      rootPath: ""
      useSSL: false
    proxy:
      maxTaskNum: 8192
    queryNode:
      dataSync:
        flowGraph:
          maxQueueLength: 1024 # Maximum length of task queue in flowgraph
          maxParallelism: 1024 # Maximum number of tasks executed in parallel in the flowgraph
    dataCoord:
      segment:
        maxSize: 512
```

### Current Behavior

Create collection of 100_000_000 vectors with dim=512. Collection params:
![image](https://user-images.githubusercontent.com/11261049/217575715-e6576d17-693d-4c85-8851-11a7b962d55e.png)

Then run search in multiple threads - load tests for check max throughput. Every search contains 50 vectors. After some time querynodes starts randomly crash with error:

```
[2023/02/03 07:54:06.166 +00:00] [DEBUG] [querynode/task_read.go:173] ["query msg can do"] [collectionID=439188497826859008] [sm.GuaranteeTimestamp=1970/01/01 00:00:00.000 +00:00] [serviceTime=2023/02/03 07:54:05.792 +00:00] ["delta 
milliseconds"=-1675410845792] [channel=milvuscluster-larva-rootcoord-delta_2_439188497826859008v0] [msgID=439198900851048454]
[2023/02/03 07:54:06.166 +00:00] [DEBUG] [querynode/task_read.go:180] [tr/waitTSafeTimeRecorder] [msg="wait for tsafe done"] [duration=27.161µs]
unexpected fault address 0x7fa7dca6258a
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7fa7dca6258a pc=0x13c4969]

goroutine 120601 [running]:
runtime.throw({0x3ccd4e8?, 0xc0014f59e8?})
	/usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc0014f5968 sp=0xc0014f5938 pc=0x138e951
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:815 +0x125 fp=0xc0014f59b8 sp=0xc0014f5968 pc=0x13a52c5
runtime.memmove()
	/usr/local/go/src/runtime/memmove_amd64.s:399 +0x489 fp=0xc0014f59c0 sp=0xc0014f59b8 pc=0x13c4969
golang.org/x/exp/mmap.(*ReaderAt).ReadAt(0x40ee420?, {0xc010946000?, 0x32660a, 0x5a?}, 0xc0014f5aa8?)
	/go/pkg/mod/golang.org/x/exp@v0.0.0-20220303212507-bbda1eaf7a17/mmap/mmap_unix.go:73 +0xc5 fp=0xc0014f5a10 sp=0xc0014f59c0 pc=0x1ffeda5
github.com/milvus-io/milvus/internal/storage.(*VectorChunkManager).Read(0xc0016e8b40, {0x40fbef0, 0xc002065dc0}, {0xc038f677a0, 0x5a})
	/go/src/github.com/milvus-io/milvus/internal/storage/vector_chunk_manager.go:194 +0x98 fp=0xc0014f5a68 sp=0xc0014f5a10 pc=0x2612278
github.com/milvus-io/milvus/internal/querynode.fillStringFieldData({0x40fbef0?, 0xc002065dc0?}, {0x4114c70?, 0xc0016e8b40?}, {0xc038f677a0?, 0x67?}, 0xc0383b0aa0, 0x0, 0x577d, {0x4107d40, ...})
	/go/src/github.com/milvus-io/milvus/internal/querynode/segment.go:445 +0x64 fp=0xc0014f5ac0 sp=0xc0014f5a68 pc=0x2d09784
github.com/milvus-io/milvus/internal/querynode.fillFieldData({0x40fbef0?, 0xc002065dc0?}, {0x4114c70?, 0xc0016e8b40?}, {0xc038f677a0?, 0x0?}, 0x0?, 0x0?, 0x3ccd7f9?, {0x4107d40, ...})
	/go/src/github.com/milvus-io/milvus/internal/querynode/segment.go:537 +0x254 fp=0xc0014f5b38 sp=0xc0014f5ac0 pc=0x2d0a894
github.com/milvus-io/milvus/internal/querynode.(*Segment).fillIndexedFieldsData(0xc002198d80, {0x40fbef0, 0xc002065dc0}, 0x3cdaa5f?, {0x4114c70, 0xc0016e8b40}, 0xc038a06060)
	/go/src/github.com/milvus-io/milvus/internal/querynode/segment.go:576 +0x245 fp=0xc0014f5be0 sp=0xc0014f5b38 pc=0x2d0ab65
github.com/milvus-io/milvus/internal/querynode.retrieveOnSegments({0x40fbef0, 0xc002065dc0}, {0x4121fe0, 0xc00053f950}, 0xa2684800?, 0x0?, 0x2cdb984?, {0xc000949300, 0xf, 0x10}, ...)
	/go/src/github.com/milvus-io/milvus/internal/querynode/retrieve.go:44 +0x1a8 fp=0xc0014f5c88 sp=0xc0014f5be0 pc=0x2cb49e8
github.com/milvus-io/milvus/internal/querynode.retrieveHistorical({0x40fbef0, 0xc002065dc0}, {0x4121fe0, 0xc00053f950}, 0xc00cb763a0?, 0xc000a42c80?, {0x0?, 0x387b7a0?, 0xc038666560?}, {0xc000949300, ...}, ...)
	/go/src/github.com/milvus-io/milvus/internal/querynode/retrieve.go:63 +0x146 fp=0xc0014f5d38 sp=0xc0014f5c88 pc=0x2cb4ca6
github.com/milvus-io/milvus/internal/querynode.(*queryTask).queryOnHistorical(0xc000e749c0)
	/go/src/github.com/milvus-io/milvus/internal/querynode/task_query.go:127 +0x1d3 fp=0xc0014f5ec0 sp=0xc0014f5d38 pc=0x2cd9bf3
github.com/milvus-io/milvus/internal/querynode.(*queryTask).Execute(0xc000e749c0?, {0x0?, 0x0?})
	/go/src/github.com/milvus-io/milvus/internal/querynode/task_query.go:150 +0x2a fp=0xc0014f5ef8 sp=0xc0014f5ec0 pc=0x2cda1ea
github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).processReadTask(0xc00076ee10, {0x4116bc8, 0xc000e749c0})
	/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:337 +0xf2 fp=0xc0014f5f70 sp=0xc0014f5ef8 pc=0x2cdfd92
github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).executeReadTasks.func1({0x4116bc8, 0xc000e749c0})
	/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:287 +0xbb fp=0xc0014f5fc0 sp=0xc0014f5f70 pc=0x2cdfafb
github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).executeReadTasks.func5()
	/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:315 +0x2e fp=0xc0014f5fe0 sp=0xc0014f5fc0 pc=0x2cdf9ae
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0014f5fe8 sp=0xc0014f5fe0 pc=0x13c3661
created by github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).executeReadTasks
	/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:315 +0x48d

goroutine 1 [chan receive, 1 minutes]:
github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run(0xc0008ebe50, 0x0, {0x0, 0x0})
	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:311 +0xb58
github.com/milvus-io/milvus/cmd/milvus.(*run).execute(0xc00004f770, {0xc0001a8060?, 0x3, 0x3}, 0xc00068e360)
	/go/src/github.com/milvus-io/milvus/cmd/milvus/run.go:120 +0x733
github.com/milvus-io/milvus/cmd/milvus.RunMilvus({0xc0001a8060?, 0x3, 0x3})
	/go/src/github.com/milvus-io/milvus/cmd/milvus/milvus.go:60 +0x21e
main.main()
	/go/src/github.com/milvus-io/milvus/cmd/main.go:26 +0x2e

goroutine 20 [semacquire]:
sync.runtime_Semacquire(0xc002924500?)
	/usr/local/go/src/runtime/sema.go:56 +0x25
sync.(*WaitGroup).Wait(0x1?)
	/usr/local/go/src/sync/waitgroup.go:136 +0x52
github.com/containerd/cgroups.(*cgroup).Stat(0xc007c76940, {0xc000544290, 0x1, 0x1})
	/go/pkg/mod/github.com/containerd/cgroups@v1.0.2/cgroup.go:298 +0x337
github.com/milvus-io/milvus/internal/util/hardware.getContainerMemUsed()
	/go/src/github.com/milvus-io/milvus/internal/util/hardware/container_linux.go:53 +0x79
github.com/milvus-io/milvus/internal/util/hardware.GetUsedMemoryCount()
	/go/src/github.com/milvus-io/milvus/internal/util/hardware/hardware_info.go:118 +0x6a
github.com/milvus-io/milvus/internal/util/gc.optimizeGOGC()
	/go/src/github.com/milvus-io/milvus/internal/util/gc/gc_tuner.go:60 +0x5c
github.com/milvus-io/milvus/internal/util/gc.finalizerHandler(0x0?)
	/go/src/github.com/milvus-io/milvus/internal/util/gc/gc_tuner.go:49 +0x1e

goroutine 226 [chan receive]:
github.com/panjf2000/ants/v2.(*Pool).purgePeriodically(0xc00095dc70)
	/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.8/pool.go:69 +0x8b
created by github.com/panjf2000/ants/v2.NewPool
	/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.8/pool.go:137 +0x34a

goroutine 120224 [select]:
net/http.(*persistConn).writeLoop(0xc000f885a0)
	/usr/local/go/src/net/http/transport.go:2392 +0xf5
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1751 +0x1791

goroutine 228 [select, 1 minutes]:
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc00054c700)
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/balancer_conn_wrappers.go:112 +0x73
created by google.golang.org/grpc.newCCBalancerWrapper
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/balancer_conn_wrappers.go:73 +0x22a

goroutine 358 [select]:
net/http.(*persistConn).writeLoop(0xc000560360)
	/usr/local/go/src/net/http/transport.go:2392 +0xf5
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1751 +0x1791

goroutine 295 [IO wait]:
internal/poll.runtime_pollWait(0x7fab34593dd0, 0x72)
	/usr/local/go/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc000730680?, 0xc000066000?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Accept(0xc000730680)
	/usr/local/go/src/internal/poll/fd_unix.go:614 +0x22c
net.(*netFD).accept(0xc000730680)
	/usr/local/go/src/net/fd_unix.go:172 +0x35
net.(*TCPListener).accept(0xc00000f548)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x28
net.(*TCPListener).Accept(0xc00000f548)
	/usr/local/go/src/net/tcpsock.go:288 +0x3d
net/http.(*Server).Serve(0xc000fb6000, {0x40fa0f0, 0xc00000f548})
	/usr/local/go/src/net/http/server.go:3039 +0x385
net/http.(*Server).ListenAndServe(0xc000fb6000)
	/usr/local/go/src/net/http/server.go:2968 +0x7d
net/http.ListenAndServe(...)
	/usr/local/go/src/net/http/server.go:3222
github.com/milvus-io/milvus/internal/management.ServeHTTP.func1()
	/go/src/github.com/milvus-io/milvus/internal/management/server.go:69 +0x151
created by github.com/milvus-io/milvus/internal/management.ServeHTTP
	/go/src/github.com/milvus-io/milvus/internal/management/server.go:66 +0x25
```

Full log of crashed querynode:
[milvuscluster-milvus-querynode-f675cdfdb-p76w7.log.zip](https://github.com/milvus-io/milvus/files/10687496/milvuscluster-milvus-querynode-f675cdfdb-p76w7.log.zip)

### Expected Behavior

No errors when search.

### Steps To Reproduce

```markdown
1. Create two collections one is 100_000_000 embeddings with dim = 1024(collection_1024) and other is 100_000_000 embeddings with dim = 512(collection_512)
2. Load collection_1024
3. Run intensive search from multiply threads for about ten minutes in collection_1024. Every search call contains 50 vectors
4. Release collection_1024
5. Load collection_512
6. Run intensive search from multiply threads for about ten minutes in collection_512.  Every search call contains 50 vectors. There will be errors

Maybe error can be reproduced with less data and less cluster resources but I not tested it.
```

### Anything else?

Floating error.

**Comment by xiaofan-luan** [comment]
goroutine 120601 [running]:
runtime.throw({0x3ccd4e8?, 0xc0014f59e8?})
	/usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc0014f5968 sp=0xc0014f5938 pc=0x138e951
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:815 +0x125 fp=0xc0014f59b8 sp=0xc0014f5968 pc=0x13a52c5
runtime.memmove()
	/usr/local/go/src/runtime/memmove_amd64.s:399 +0x489 fp=0xc0014f59c0 sp=0xc0014f59b8 pc=0x13c4969
golang.org/x/exp/mmap.(*ReaderAt).ReadAt(0x40ee420?, {0xc010946000?, 0x32660a, 0x5a?}, 0xc0014f5aa8?)
	/go/pkg/mod/golang.org/x/exp@v0.0.0-20220303212507-bbda1eaf7a17/mmap/mmap_unix.go:73 +0xc5 fp=0xc0014f5a10 sp=0xc0014f59c0 pc=0x1ffeda5
github.com/milvus-io/milvus/internal/storage.(*VectorChunkManager).Read(0xc0016e8b40, {0x40fbef0, 0xc002065dc0}, {0xc038f677a0, 0x5a})
	/go/src/github.com/milvus-io/milvus/internal/storage/vector_chunk_manager.go:194 +0x98 fp=0xc0014f5a68 sp=0xc0014f5a10 pc=0x2612278
github.com/milvus-io/milvus/internal/querynode.fillStringFieldData({0x40fbef0?, 0xc002065dc0?}, {0x4114c70?, 0xc0016e8b40?}, {0xc038f677a0?, 0x67?}, 0xc0383b0aa0, 0x0, 0x577d, {0x4107d40, ...})
	/go/src/github.com/milvus-io/milvus/internal/querynode/segment.go:445 +0x64 fp=0xc0014f5ac0 sp=0xc0014f5a68 pc=0x2d09784
github.com/milvus-io/milvus/internal/querynode.fillFieldData({0x40fbef0?, 0xc002065dc0?}, {0x4114c70?, 0xc0016e8b40?}, {0xc038f677a0?, 0x0?}, 0x0?, 0x0?, 0x3ccd7f9?, {0x4107d40, ...})
	/go/src/github.com/milvus-io/milvus/internal/querynode/segment.go:537 +0x254 fp=0xc0014f5b38 sp=0xc0014f5ac0 pc=0x2d0a894
github.com/milvus-io/milvus/internal/querynode.(*Segment).fillIndexedFieldsData(0xc002198d80, {0x40fbef0, 0xc002065dc0}, 0x3cdaa5f?, {0x4114c70, 0xc0016e8b40}, 0xc038a06060)
	/go/src/github.com/milvus-io/milvus/internal/querynode/segment.go:576 +0x245 fp=0xc0014f5be0 sp=0xc0014f5b38 pc=0x2d0ab65
github.com/milvus-io/milvus/internal/querynode.retrieveOnSegments({0x40fbef0, 0xc002065dc0}, {0x4121fe0, 0xc00053f950}, 0xa2684800?, 0x0?, 0x2cdb984?, {0xc000949300, 0xf, 0x10}, ...)
	/go/src/github.com/milvus-io/milvus/internal/querynode/retrieve.go:44 +0x1a8 fp=0xc0014f5c88 sp=0xc0014f5be0 pc=0x2cb49e8
github.com/milvus-io/milvus/internal/querynode.retrieveHistorical({0x40fbef0, 0xc002065dc0}, {0x4121fe0, 0xc00053f950}, 0xc00cb763a0?, 0xc000a42c80?, {0x0?, 0x387b7a0?, 0xc038666560?}, {0xc000949300, ...}, ...)
	/go/src/github.com/milvus-io/milvus/internal/querynode/retrieve.go:63 +0x146 fp=0xc0014f5d38 sp=0xc0014f5c88 pc=0x2cb4ca6
github.com/milvus-io/milvus/internal/querynode.(*queryTask).queryOnHistorical(0xc000e749c0)
	/go/src/github.com/milvus-io/milvus/internal/querynode/task_query.go:127 +0x1d3 fp=0xc0014f5ec0 sp=0xc0014f5d38 pc=0x2cd9bf3
github.com/milvus-io/milvus/internal/querynode.(*queryTask).Execute(0xc000e749c0?, {0x0?, 0x0?})
	/go/src/github.com/milvus-io/milvus/internal/querynode/task_query.go:150 +0x2a fp=0xc0014f5ef8 sp=0xc0014f5ec0 pc=0x2cda1ea
github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).processReadTask(0xc00076ee10, {0x4116bc8, 0xc000e749c0})
	/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:337 +0xf2 fp=0xc0014f5f70 sp=0xc0014f5ef8 pc=0x2cdfd92
github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).executeReadTasks.func1({0x4116bc8, 0xc000e749c0})
	/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:287 +0xbb fp=0xc0014f5fc0 sp=0xc0014f5f70 pc=0x2cdfafb
github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).executeReadTasks.func5()
	/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:315 +0x2e fp=0xc0014f5fe0 sp=0xc0014f5fc0 pc=0x2cdf9ae
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0014f5fe8 sp=0xc0014f5fe0 pc=0x13c3661
created by github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).executeReadTasks
	/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:315 +0x48d

**Comment by xiaofan-luan** [comment]
1. we should not retrieve on vector chunkmanager since  the index should support it.
2. why vector chunk manager crash is another thing need to be figure out

**Comment by xiaofan-luan** [comment]
should be fixed by https://github.com/milvus-io/milvus/pull/21852/

**Comment by jiaoew1991** [comment]
2.2.3 was released, you can try it @AlexeyIvanov8

**Comment by AlexeyIvanov8** [comment]
Checked release 2.2.3, looks fixed. The error is not reproduced

**Comment by xiaofan-luan** [comment]
cheers, close it for now!
