### ISSUE TITLE
[Bug]: [Nightly]Plenty of cases failed for loading collection timeout

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#22135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: bd559b3
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.2.dev8
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Plenty of cases failed for loading collection timeout.
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/94/pipeline/156
```
[2023-02-12T22:09:16.202Z] [2023-02-12 22:09:09 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=wait for loading collection timeout, collection: search_collection_IAA3xBCG)>, <Time:{'RPC start': '2023-02-12 22:07:08.935373', 'RPC error': '2023-02-12 22:09:09.424617'}> (decorators.py:108)
[2023-02-12T22:09:16.202Z] [2023-02-12 22:09:09 - WARNING - pymilvus.decorators]: [93mRetry timeout: 120s[0m (decorators.py:79)
[2023-02-12T22:09:16.202Z] [2023-02-12 22:09:09 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: search_collection_IAA3xBCG)>, <Time:{'RPC start': '2023-02-12 22:07:08.921973', 'RPC error': '2023-02-12 22:09:09.425478'}> (decorators.py:108)
[2023-02-12T22:09:16.202Z] [2023-02-12 22:09:09 - ERROR - ci_test]: Traceback (most recent call last):
[2023-02-12T22:09:16.202Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2023-02-12T22:09:16.202Z]     return func(self, *args, **kwargs)
[2023-02-12T22:09:16.202Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 664, in load_collection
[2023-02-12T22:09:16.202Z]     self.wait_for_loading_collection(collection_name, timeout)
[2023-02-12T22:09:16.202Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2023-02-12T22:09:16.202Z]     raise e
[2023-02-12T22:09:16.202Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2023-02-12T22:09:16.202Z]     return func(*args, **kwargs)
[2023-02-12T22:09:16.202Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2023-02-12T22:09:16.202Z]     ret = func(self, *args, **kwargs)
[2023-02-12T22:09:16.202Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
[2023-02-12T22:09:16.202Z]     raise e
[2023-02-12T22:09:16.202Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2023-02-12T22:09:16.202Z]     return func(self, *args, **kwargs)
[2023-02-12T22:09:16.202Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 686, in wait_for_loading_collection
[2023-02-12T22:09:16.202Z]     raise MilvusException(message=f"wait for loading collection timeout, collection: {collection_name}")
[2023-02-12T22:09:16.202Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=wait for loading collection timeout, collection: search_collection_IAA3xBCG)>
[2023-02-12T22:09:16.202Z] 
[2023-02-12T22:09:16.202Z] The above exception was the direct cause of the following exception:
[2023-02-12T22:09:16.202Z] 
[2023-02-12T22:09:16.202Z] Traceback (most recent call last):
[2023-02-12T22:09:16.202Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2023-02-12T22:09:16.202Z]     res = func(*args, **_kwargs)
[2023-02-12T22:09:16.202Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2023-02-12T22:09:16.202Z]     return func(*arg, **kwargs)
[2023-02-12T22:09:16.202Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 366, in load
[2023-02-12T22:09:16.202Z]     conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
[2023-02-12T22:09:16.202Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2023-02-12T22:09:16.202Z]     raise e
[2023-02-12T22:09:16.202Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2023-02-12T22:09:16.202Z]     return func(*args, **kwargs)
[2023-02-12T22:09:16.202Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2023-02-12T22:09:16.202Z]     ret = func(self, *args, **kwargs)
[2023-02-12T22:09:16.202Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 80, in handler
[2023-02-12T22:09:16.202Z]     raise MilvusException(e.code, f"{timeout_msg}, message={e.message}") from e
[2023-02-12T22:09:16.202Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: search_collection_IAA3xBCG)>
[2023-02-12T22:09:16.202Z]  (api_request.py:39)
[2023-02-12T22:09:16.202Z] [2023-02-12 22:09:09 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: search_collection_IAA3xBCG)> (api_request.py:40)
```

### Expected Behavior

pass

### Milvus Log

[artifacts-milvus-distributed-kafka-nightly-94-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/94/artifact/artifacts-milvus-distributed-kafka-nightly-94-pymilvus-e2e-logs.tar.gz)

**Comment by NicoYuan1986** [comment]
Same situation with the master branch and occur continuously the latest 3 days.
1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/281/pipeline/155
2. milvus log: [artifacts-milvus-distributed-kafka-nightly-281-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/281/artifact/artifacts-milvus-distributed-kafka-nightly-281-pymilvus-e2e-logs.tar.gz)
3. error message:
```
[2023-02-12 22:31:19,955 - ERROR - ci_test]: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 664, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 686, in wait_for_loading_collection
    raise MilvusException(message=f"wait for loading collection timeout, collection: {collection_name}")
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=wait for loading collection timeout, collection: query_6530YQwY)>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 366, in load
    conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 80, in handler
    raise MilvusException(e.code, f"{timeout_msg}, message={e.message}") from e
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: query_6530YQwY)>
 (api_request.py:39)
[2023-02-12 22:31:19,955 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: query_6530YQwY)> (api_request.py:40)

```

**Comment by NicoYuan1986** [comment]
@jiaoew1991 
More details: The situation started last Friday. And it will be killed over 6 hours in master branch.

**Comment by jiaoew1991** [comment]
It is caused by https://github.com/milvus-io/milvus/issues/22123
<img width="2231" alt="image" src="https://user-images.githubusercontent.com/2297455/218365063-53eb1879-e0c7-48ff-b218-dc13c3d6f719.png">

**Comment by NicoYuan1986** [comment]
Update:
From the latest nightly, the pipeline pulsar still timeout(6h) for loading collection error.
link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/282/pipeline/187
log: [artifacts-milvus-distributed-pulsar-nightly-282-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/282/artifact/artifacts-milvus-distributed-pulsar-nightly-282-pymilvus-e2e-logs.tar.gz)

The pipeline kafka has several loading collection error.
link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/282/pipeline/155
log: [artifacts-milvus-distributed-kafka-nightly-282-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/282/artifact/artifacts-milvus-distributed-kafka-nightly-282-pymilvus-e2e-logs.tar.gz)
failed cases: 
[2023-02-13T18:07:18.762Z] [gw4] [ 21%] FAILED testcases/test_index.py::TestIndexDiskann::test_create_index_with_diskann_normal
[2023-02-13T18:07:26.842Z] [gw5] [ 21%] FAILED testcases/test_index.py::TestIndexDiskann::test_drop_diskann_index_with_noraml
[2023-02-13T18:20:10.870Z] [gw2] [ 42%] FAILED testcases/test_query.py::TestQueryParams::test_query_expr_empty_term_array
[2023-02-13T18:20:10.870Z] [gw4] [ 42%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_after_index_different_metric_type[32-False-True-IVF_SQ8-params2]
[2023-02-13T18:20:10.870Z] [gw3] [ 42%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_HNSW_index_with_max_ef[False-True-8-4]
...

**Comment by NicoYuan1986** [comment]
Reproduced continuously.
link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/283/pipeline/135
log: [artifacts-milvus-distributed-kafka-nightly-283-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/283/artifact/artifacts-milvus-distributed-kafka-nightly-283-pymilvus-e2e-logs.tar.gz)

**Comment by sunby** [comment]
![image](https://user-images.githubusercontent.com/9817127/219565409-68a8340f-e84b-487e-a58a-ae62c8675d1a.png)
There are some bugs in knowhere.

**Comment by liliu-z** [comment]
known issue, this get fixed in Knowhere1.x, but looks like forget to cherrypick to 2.0.
/assign @hhy3

**Comment by liliu-z** [comment]
fixed in https://github.com/milvus-io/knowhere/pull/697

**Comment by NicoYuan1986** [comment]
Fixed! master-20230221-c3e8ad36

**Comment by NicoYuan1986** [comment]
Plenty of cases failed for loading collection timeout again in master branch.
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/320/pipeline/187/

milvus: 0e9a447
pymilvus: 2.3.0.dev48
log: [artifacts-milvus-distributed-pulsar-nightly-320-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/320/artifact/artifacts-milvus-distributed-pulsar-nightly-320-pymilvus-e2e-logs.tar.gz)

**Comment by NicoYuan1986** [comment]
@sunby Could you help resolve it?

**Comment by NicoYuan1986** [comment]
latest: 
milvus: 1287ca6
link:https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/327/pipeline/187
log: [artifacts-milvus-distributed-pulsar-nightly-327-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/327/artifact/artifacts-milvus-distributed-pulsar-nightly-327-pymilvus-e2e-logs.tar.gz)
collection name: collection_HQeeZkVR
failed time: [2023-03-30T18:14:37.026Z] [gw3] [  9%] FAILED testcases/test_collection.py::TestLoadCollection::test_load_replica_multi

**Comment by NicoYuan1986** [comment]
latest: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/331/pipeline/143/
Pipeline kafka exit for 6 hours timeout. And plenty of cases failed for loading collection timeout.

milvus: 7da870f
pymilvus: 2.4.0.dev4

1. log: [artifacts-milvus-distributed-kafka-nightly-331-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/331/artifact/artifacts-milvus-distributed-kafka-nightly-331-pymilvus-e2e-logs.tar.gz)
2. The time when the failure begins: [2023-04-03T18:31:22.153Z] [gw0] [ 33%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_HNSW_index_with_max_ef[False-False-8-4]

**Comment by NicoYuan1986** [comment]
This issue has not occurred for a month
