### ISSUE TITLE
[Bug]: [Diskann index] Milvus standalone pod restarts multiple times, load, query, search fail with error "StatusCode.UNAVAILABLE"

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#22140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230210-6313a455
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.2.dev4
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

testcase:test_concurrent_locust_diskann_dql_standalone
sever：
```
fouramf-stable-test-1676239200-2-etcd-0                           1/1     Running     0                132m    10.104.1.170   4am-node10   <none>           <none>
fouramf-stable-test-1676239200-2-milvus-standalone-6586ff7l4ws4   1/1     Running     4 (2m40s ago)    132m    10.104.4.141   4am-node11   <none>           <none>
fouramf-stable-test-1676239200-2-minio-764c584654-pg5js           1/1     Running     0                132m    10.104.1.168   4am-node10   <none>           <none> 
```

client：

```
2023-02-12 23:39:47,073 - ERROR - fouram]: RPC error: [query], <MilvusUnavailableException: (code=1, message=server Unavailable: Retry timeout: 60s)>, <Time:{'RPC start': '2023-02-12 23:38:07.297660', 'RPC error': '2023-02-12 23:39:47.073578'}> (decorators.py:108)
[2023-02-12 23:39:47,080 - ERROR - fouram]: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 880, in query
    response = future.result()
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1676245187.072721583","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3260,"referenced_errors":[{"created":"@1676245187.072721004","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":167,"grpc_status":14}]}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/src/fouram/client/util/api_request.py", line 33, in inner_wrapper
    res = func(*args, **kwargs)
  File "/src/fouram/client/util/api_request.py", line 70, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 696, in query
    res = conn.query(self._name, expr, output_fields, partition_names, timeout=timeout, schema=schema, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 66, in handler
    raise MilvusUnavailableException(message=f"server Unavailable: {timeout_msg}") from e
pymilvus.exceptions.MilvusUnavailableException: <MilvusUnavailableException: (code=1, message=server Unavailable: Retry timeout: 60s)>
 (api_request.py:48)
[2023-02-12 23:39:47,081 - ERROR - fouram]: (api_response) : <MilvusUnavailableException: (code=1, message=server Unavailable: Retry timeout: 60s)> (api_request.py:49)
[2023-02-12 23:39:47,081 - ERROR - fouram]: [CheckFunc] query request check failed, response:<MilvusUnavailableException: (code=1, message=server Unavailable: Retry timeout: 60s)> (func_check.py:42)
[2023-02-12 23:39:47,086 - ERROR - fouram]: RPC error: [query], <MilvusUnavailableException: (code=1, message=server Unavailable: Retry timeout: 60s)>, <Time:{'RPC start': '2023-02-12 23:38:11.211443', 'RPC error': '2023-02-12 23:39:47.086297'}> (decorators.py:108)
[2023-02-12 23:39:47,087 - ERROR - fouram]: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 880, in query
    response = future.result()
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1676245187.073135384","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3260,"referenced_errors":[{"created":"@1676245187.073134917","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":167,"grpc_status":14}]}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/src/fouram/client/util/api_request.py", line 33, in inner_wrapper
    res = func(*args, **kwargs)
  File "/src/fouram/client/util/api_request.py", line 70, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 696, in query
    res = conn.query(self._name, expr, output_fields, partition_names, timeout=timeout, schema=schema, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 66, in handler
    raise MilvusUnavailableException(message=f"server Unavailable: {timeout_msg}") from e
pymilvus.exceptions.MilvusUnavailableException: <MilvusUnavailableException: (code=1, message=server Unavailable: Retry timeout: 60s)>
 (api_request.py:48)
[2023-02-12 23:39:47,087 - ERROR - fouram]: (api_response) : <MilvusUnavailableException: (code=1, message=server Unavailable: Retry timeout: 60s)> (api_request.py:49)
[2023-02-12 23:39:47,087 - ERROR - fouram]: [CheckFunc] query request check failed, response:<MilvusUnavailableException: (code=1, message=server Unavailable: Retry timeout: 60s)> (func_check.py:42)
[2023-02-12 23:39:47,090 - ERROR - fouram]: RPC error: [query], <MilvusUnavailableException: (code=1, message=server Unavailable: Retry timeout: 60s)>, <Time:{'RPC start': '2023-02-12 23:38:11.216069', 'RPC error': '2023-02-12 23:39:47.090852'}> (decorators.py:108)
[2023-02-12 23:39:47,091 - ERROR - fouram]: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 880, in query
    response = future.result()
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1676245187.073253691","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3260,"referenced_errors":[{"created":"@1676245187.073253192","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":167,"grpc_status":14}]}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/src/fouram/client/util/api_request.py", line 33, in inner_wrapper
    res = func(*args, **kwargs)
  File "/src/fouram/client/util/api_request.py", line 70, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 696, in query
    res = conn.query(self._name, expr, output_fields, partition_names, timeout=timeout, schema=schema, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 66, in handler
    raise MilvusUnavailableException(message=f"server Unavailable: {timeout_msg}") from e
pymilvus.exceptions.MilvusUnavailableException: <MilvusUnavailableException: (code=1, message=server Unavailable: Retry timeout: 60s)>
 (api_request.py:48)
[2023-02-12 23:39:47,091 - ERROR - fouram]: (api_response) : <MilvusUnavailableException: (code=1, message=server Unavailable: Retry timeout: 60s)> (api_request.py:49)
```
standalone pod:
<img width="1384" alt="截屏2023-02-13 11 05 33" src="https://user-images.githubusercontent.com/34296482/218361307-d79b0266-14e2-4fa7-9443-a4c1edbd6bb7.png">

### Steps To Reproduce

```markdown
1. create a collection 
        2. build diskann index on vector column
        3. insert a 10m of vectors
        4. flush collection
        5. build index on vector column with the same parameters
        6. count the total number of rows
        7. load collection
        8. perform concurrent operations
        9. clean all collections or not
```

### Anything else?

```
client': {'test_case_type': 'ConcurrentClientBase',
            'test_case_name': 'test_concurrent_locust_diskann_dql_standalone',
            'test_case_params': {'dataset_params': {'dim': 128,
                                                    'dataset_name': 'sift',
                                                    'dataset_size': 10000000,
                                                    'ni_per': 50000,
                                                    'metric_type': 'L2'},
                                 'collection_params': {'other_fields': []},
                                 'load_params': {},
                                 'search_params': {},
                                 'index_params': {'index_type': 'DISKANN',
                                                  'index_param': {}},
                                 'concurrent_params': {'concurrent_number': 20,
                                                       'during_time': '1h',
                                                       'interval': 20,
                                                       'spawn_rate': None},
                                 'concurrent_tasks': [{'type': 'search',
                                                       'weight': 10,
                                                       'params': {'nq': 10,
                                                                  'top_k': 10,
                                                                  'search_param': {'search_list': 30},
                                                                  'expr': None,
                                                                  'guarantee_timestamp': None,
                                                                  'timeout': 60,
                                                                  'random_data': True}},
                                                      {'type': 'query',
                                                       'weight': 2,
                                                       'params': {'ids': [0,
                                                                          1,
                                                                          2,
                                                                          3,
                                                                          4,
                                                                          5,
                                                                          6,
                                                                          7,
                                                                          8,
                                                                          9],
                                                                  'expr': None,
                                                                  'timeout': 60}},
                                                      {'type': 'load',
                                                       'weight': 1,
                                                       'params': {'replica_number': 1,
                                                                  'timeout': 30}}]}
```

**Comment by yanliang567** [comment]
looks like it was OOM

**Comment by xige-16** [comment]
seems with https://github.com/milvus-io/milvus/issues/22127

**Comment by xige-16** [comment]
@jingkl Does this bug still exist?
/assign @jingkl

**Comment by jingkl** [comment]
2.2.0-20230808-506ec414
release_name
fouramf-stable-test-1690581601-2
other_params
 --milvus_tag_prefix=2.2.0  -s --client_version=2.2.0
case_name
test_concurrent_locust_diskann_dql_standalone


already fix ，close issue
