### ISSUE TITLE
[Bug]: [benchmark][diskann]Milvus creates a diskann index and then search, query, load for a while to concurrently insert the vector with an error “SegmentIDAllocator failRemainRequest"

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#22146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230210-6313a455
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.2.dev4
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

InstanceID: fouramf-stable-1676228400-10
testcase:test_concurrent_locust_diskann_compaction_cluster

server:
```
NAME                                                              READY   STATUS        RESTARTS         AGE     IP             NODE         NOMINATED NODE   READINESS GATES
fouramf-stable-1676228400-10-etcd-0                               1/1     Running       0                5h7m    10.104.9.243   4am-node14   <none>           <none>
fouramf-stable-1676228400-10-etcd-1                               1/1     Running       0                5h7m    10.104.6.154   4am-node13   <none>           <none>
fouramf-stable-1676228400-10-etcd-2                               1/1     Running       0                5h7m    10.104.4.87    4am-node11   <none>           <none>
fouramf-stable-1676228400-10-milvus-datacoord-5db5d898d7-tl6lj    1/1     Running       1 (5h3m ago)     5h7m    10.104.9.230   4am-node14   <none>           <none>
fouramf-stable-1676228400-10-milvus-datanode-5b9f9784cf-vzd6v     1/1     Running       1 (5h3m ago)     5h7m    10.104.5.17    4am-node12   <none>           <none>
fouramf-stable-1676228400-10-milvus-indexcoord-c5bc856c5-k9vjv    1/1     Running       1 (5h3m ago)     5h7m    10.104.5.15    4am-node12   <none>           <none>
fouramf-stable-1676228400-10-milvus-indexnode-9c45b4d4-cxqm5      1/1     Running       0                5h7m    10.104.4.66    4am-node11   <none>           <none>
fouramf-stable-1676228400-10-milvus-proxy-5595c759cf-dbvzc        1/1     Running       1 (5h3m ago)     5h7m    10.104.5.16    4am-node12   <none>           <none>
fouramf-stable-1676228400-10-milvus-querycoord-5cf444b96d-hv4dp   1/1     Running       1 (5h3m ago)     5h7m    10.104.6.133   4am-node13   <none>           <none>
fouramf-stable-1676228400-10-milvus-querynode-85cc8dfc58-swwtv    1/1     Running       0                5h7m    10.104.1.86    4am-node10   <none>           <none>
fouramf-stable-1676228400-10-milvus-rootcoord-68d7c6cb8-k455h     1/1     Running       1 (5h3m ago)     5h7m    10.104.9.231   4am-node14   <none>           <none>
fouramf-stable-1676228400-10-minio-0                              1/1     Running       0                5h7m    10.104.9.247   4am-node14   <none>           <none>
fouramf-stable-1676228400-10-minio-1                              1/1     Running       0                5h7m    10.104.6.156   4am-node13   <none>           <none>
fouramf-stable-1676228400-10-minio-2                              1/1     Running       0                5h7m    10.104.4.88    4am-node11   <none>           <none>
fouramf-stable-1676228400-10-minio-3                              1/1     Running       0                5h7m    10.104.1.102   4am-node10   <none>           <none>
fouramf-stable-1676228400-10-pulsar-bookie-0                      1/1     Running       0                5h7m    10.104.5.22    4am-node12   <none>           <none>
fouramf-stable-1676228400-10-pulsar-bookie-1                      1/1     Running       0                5h7m    10.104.6.152   4am-node13   <none>           <none>
fouramf-stable-1676228400-10-pulsar-bookie-2                      1/1     Running       0                5h7m    10.104.1.100   4am-node10   <none>           <none>
fouramf-stable-1676228400-10-pulsar-bookie-init-nvkpx             0/1     Completed     0                5h7m    10.104.4.59    4am-node11   <none>           <none>
fouramf-stable-1676228400-10-pulsar-broker-0                      1/1     Running       0                5h7m    10.104.9.232   4am-node14   <none>           <none>
fouramf-stable-1676228400-10-pulsar-proxy-0                       1/1     Running       0                5h7m    10.104.6.134   4am-node13   <none>           <none>
fouramf-stable-1676228400-10-pulsar-pulsar-init-bc7fc             0/1     Completed     0                5h7m    10.104.4.62    4am-node11   <none>           <none>
fouramf-stable-1676228400-10-pulsar-recovery-0                    1/1     Running       0                5h7m    10.104.6.135   4am-node13   <none>           <none>
fouramf-stable-1676228400-10-pulsar-zookeeper-0                   1/1     Running       0                5h7m    10.104.9.246   4am-node14   <none>           <none>
fouramf-stable-1676228400-10-pulsar-zookeeper-1                   1/1     Running       0                5h5m    10.104.6.158   4am-node13   <none>           <none>
fouramf-stable-1676228400-10-pulsar-zookeeper-2                   1/1     Running       0                5h4m    10.104.1.104   4am-node10   <none>           <none>
```
client log:
Number of requests for INSERT up to the time of the error
```
[2023-02-12 23:47:28,032 -  INFO - fouram]:  Type     Name                                                                                  50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100% # reqs (stats.py:740)
[2023-02-12 23:47:28,032 -  INFO - fouram]: --------|--------------------------------------------------------------------------------|---------|------|------|------|------|------|------|------|------|------|------|------| (stats.py:750)
[2023-02-12 23:47:28,033 -  INFO - fouram]:  grpc     load                                                                                  230    320    370    400    550    710    920   1200   2700   4900   6000  19012 (stats.py:754)
[2023-02-12 23:47:28,033 -  INFO - fouram]:  grpc     query                                                                                 340    390    430    460    590    730   1000   1400   3100   4600   6400 190301 (stats.py:754)
[2023-02-12 23:47:28,034 -  INFO - fouram]:  grpc     scene_insert_delete_flush                                                            3100   3300   3400   3500   3900   4200   4900   5300   7000   8000   8400  18924 (stats.py:754)
[2023-02-12 23:47:28,034 -  INFO - fouram]:  grpc     search                                                                                450    530    600    640    790    970   1300   1800   3500   5400   7500 381207 (stats.py:754)
[2023-02-12 23:47:28,035 -  INFO - fouram]: --------|--------------------------------------------------------------------------------|---------|------|------|------|------|------|------|------|------|------|------|------| (stats.py:755)
[2023-02-12 23:47:28,035 -  INFO - fouram]:  None     Aggregated                                                                            410    500    570    620    810   1200   3000   3400   4700   6200   8400 609444 (stats.py:758)
[2023-02-12 23:47:28,035 -  INFO - fouram]:  (stats.py:759
```

```
[2023-02-12 23:47:28,035 -  INFO - fouram]:  (stats.py:759)
[2023-02-12 23:47:42,826 - ERROR - fouram]: RPC error: [batch_insert], <MilvusException: (code=1, message=getSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error)>, <Time:{'RPC start': '2023-02-12 23:47:30.944614', 'RPC error': '2023-02-12 23:47:42.826631'}> (decorators.py:108)
[2023-02-12 23:47:42,828 - ERROR - fouram]: Traceback (most recent call last):
  File "/src/fouram/client/util/api_request.py", line 33, in inner_wrapper
    res = func(*args, **kwargs)
  File "/src/fouram/client/util/api_request.py", line 70, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 427, in insert
    res = conn.batch_insert(self._name, entities, partition_name, timeout=timeout, schema=schema_dict, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 385, in batch_insert
    raise err
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 381, in batch_insert
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=getSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error)>
 (api_request.py:48)
[2023-02-12 23:47:42,829 - ERROR - fouram]: (api_response) : <MilvusException: (code=1, message=getSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error)> (api_request.py:49)
[2023-02-12 23:47:42,829 - ERROR - fouram]: [CheckFunc] insert request check failed, response:<MilvusException: (code=1, message=getSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error)> (func_check.py:48)
[2023-02-12 23:47:42,829 - ERROR - fouram]: Traceback (most recent call last):
  File "/src/fouram/client/util/api_request.py", line 105, in inner_wrapper
    res = func(*args, **kwargs)
  File "/src/fouram/client/cases/base.py", line 512, in concurrent_scene_insert_delete_flush
    self.collection_wrap.insert(entities)
  File "/src/fouram/client/client_base/collection_wrapper.py", line 99, in insert
    check_result = ResponseChecker(res, func_name, check_task, check_items, check,
  File "/src/fouram/client/check/func_check.py", line 23, in run
    result = self.assert_succ(self.succ, True)
  File "/src/fouram/client/check/func_check.py", line 49, in assert_succ
    assert actual is expect
AssertionError
```

### Steps To Reproduce

```markdown
        1. create a collection 
        2. build DISKANN index on vector column
        3. insert a 100000  of vectors
        4. flush collection
        5. build index on vector column with the same parameters
        6. count the total number of rows
        7. load collection
        8. perform concurrent operations, load, scene_insert_delete_flush->raise error
        10. clean all collections or not
```

### Anything else?

```
 'test_case_params': {'dataset_params': {'dim': 128,
                                                    'dataset_name': 'sift',
                                                    'dataset_size': 100000,
                                                    'ni_per': 50000,
                                                    'metric_type': 'L2'},
                                 'collection_params': {'other_fields': ['float_1']},
                                 'load_params': {},
                                 'search_params': {},
                                 'index_params': {'index_type': 'DISKANN',
                                                  'index_param': {}},
                                 'concurrent_params': {'concurrent_number': 20,
                                                       'during_time': '5h',
                                                       'interval': 20,
                                                       'spawn_rate': None},
                                 'concurrent_tasks': [{'type': 'search',
                                                       'weight': 20,
                                                       'params': {'nq': 10,
                                                                  'top_k': 10,
                                                                  'search_param': {'search_list': 30},
                                                                  'expr': {'float_1': {'GT': -1.0,
                                                                                       'LT': 50000.0}},
                                                                  'guarantee_timestamp': None,
                                                                  'timeout': 60,
                                                                  'random_data': True}},
                                                      {'type': 'query',
                                                       'weight': 10,
                                                       'params': {'ids': [0,
                                                                          1,
                                                                          2,
                                                                          3,
                                                                          4,
                                                                          5,
                                                                          6,
                                                                          7,
                                                                          8,
                                                                          9],
                                                                  'expr': None,
                                                                  'timeout': 60}},
                                                      {'type': 'load',
                                                       'weight': 1,
                                                       'params': {'replica_number': 1,
                                                                  'timeout': 30}},
                                                      {'type': 'scene_insert_delete_flush',
                                                       'weight': 1,
                                                       'params': {'insert_length': 1,
                                                                  'delete_length': 1,
                                                                  'random_id': True,
                                                                  'random_vector': True,
                                                                  'varchar_filled': True}}]}`
```

**Comment by jingkl** [comment]
This problem has not occurred before, close issue
