### ISSUE TITLE
[Bug]: Search failed with error `cannot found tSafer, vChannel = by-dev-rootcoord-delta_12_439428575331552722v0` after upgrading from v2.2.2 to 2.2.0-20230213-4e26d626

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#22158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230213-4e26d626 
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus==2.3.0.dev34
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/12268675/218625966-f5d3b364-4288-41dc-be29-d20f8e60a788.png)

```
[2023-02-13T11:38:46.821Z] + python3 scripts/second_recall_test.py --host 10.101.134.247

[2023-02-13T11:38:49.342Z] 2023-02-13 11:38:48.937 | INFO     | __main__:search_test:33 - 

[2023-02-13T11:38:49.342Z] Search...

[2023-02-13T11:39:56.982Z] RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=14, reason=Search 14 failed, reason failed to get service timestamp, taskID = 439428927743590404, collectionID = 439428575331552722, err=cannot found tSafer, vChannel = by-dev-rootcoord-delta_12_439428575331552722v0 err %!w(<nil>))>, <Time:{'RPC start': '2023-02-13 11:38:48.937447', 'RPC error': '2023-02-13 11:39:49.679031'}>

[2023-02-13T11:39:56.982Z] Traceback (most recent call last):

[2023-02-13T11:39:56.982Z]   File "scripts/second_recall_test.py", line 67, in <module>

[2023-02-13T11:39:56.982Z]     search_test(host)

[2023-02-13T11:39:56.983Z]   File "scripts/second_recall_test.py", line 35, in search_test

[2023-02-13T11:39:56.983Z]     res = collection.search(

[2023-02-13T11:39:56.983Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 614, in search

[2023-02-13T11:39:56.983Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,

[2023-02-13T11:39:56.983Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-02-13T11:39:56.983Z]     raise e

[2023-02-13T11:39:56.983Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-02-13T11:39:56.983Z]     return func(*args, **kwargs)

[2023-02-13T11:39:56.983Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-02-13T11:39:56.983Z]     ret = func(self, *args, **kwargs)

[2023-02-13T11:39:56.983Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-02-13T11:39:56.983Z]     raise e

[2023-02-13T11:39:56.983Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-02-13T11:39:56.983Z]     return func(self, *args, **kwargs)

[2023-02-13T11:39:56.983Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 472, in search

[2023-02-13T11:39:56.983Z]     return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)

[2023-02-13T11:39:56.983Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 441, in _execute_search_requests

[2023-02-13T11:39:56.983Z]     raise pre_err

[2023-02-13T11:39:56.983Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 432, in _execute_search_requests

[2023-02-13T11:39:56.983Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2023-02-13T11:39:56.983Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=14, reason=Search 14 failed, reason failed to get service timestamp, taskID = 439428927743590404, collectionID = 439428575331552722, err=cannot found tSafer, vChannel = by-dev-rootcoord-delta_12_439428575331552722v0 err %!w(<nil>))>

script returned exit code 1
```

### Expected Behavior

all testcases pass

### Milvus Log

milvus mode: cluster deploy task: upgrade old image tag: v2.2.2 new image tag: 2.2.0-20230213-4e26d626
failed job:https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_for_release_cron/detail/deploy_test_for_release_cron/343/pipeline
log:

[artifacts-pulsar-cluster-upgrade-343-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10728230/artifacts-pulsar-cluster-upgrade-343-server-logs.tar.gz)
[artifacts-pulsar-cluster-upgrade-343-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10728231/artifacts-pulsar-cluster-upgrade-343-pytest-logs.tar.gz)

**Comment by xiaofan-luan** [comment]
/assign @congqixia 
pls help on investigating

**Comment by congqixia** [comment]
Found some logs 
```
[2023/02/13 11:30:02.990 +00:00] [INFO] [querynode/load_segment_task.go:218] ["watchDeltaChannel, add flowGraph for deltaChannel success"] [collectionID=439428575331552722] [collectionID=439428575331552722] [vDeltaChannels="[by-dev-rootcoord-delta_13_439428575331552722v1]"]
[2023/02/13 11:26:46.247 +00:00] [INFO] [querynode/load_segment_task.go:156] ["Starting WatchDeltaChannels ..."] [collectionID=439428575331552722] [channels="[by-dev-rootcoord-delta_12]"]
```
It looks like the channel name is not correct for delta channel 12

**Comment by congqixia** [comment]
Patch and compatibility PRs are all merged. Could you please verify?
/assign @zhuwenxing

**Comment by zhuwenxing** [comment]
verified and passed with 2.2.0-20230222-ec20fec1
