### ISSUE TITLE
[Bug]: Upgrade standalone from v2.2.0 to master-20230213-7c495303 failed with standalone pod crash

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#22180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.2.0 --> master-20230213-7c495303
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):rocksmq    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/12268675/218915801-9344c7c0-d5f0-4498-8195-082074aadde1.png)
![image](https://user-images.githubusercontent.com/12268675/218915840-f0e1d14b-3749-49ed-9919-2122a10ea3c2.png)

```
[2023/02/13 09:51:56.515 +00:00] [INFO] [datanode/channel_meta.go:199] ["adding segment"] [type=Normal] [segmentID=439426855970366797] [collectionID=439426855970366432] [partitionID=439426855970366433] [channel=by-dev-rootcoord-dml_55_439426855970366432v1] [startPosition=<nil>] [endPosition="channel_name:\"by-dev-rootcoord-dml_55_439426855970366432v1\" msgID:\"\\330\\303\\360\\263e(\\031\\006\" msgGroup:\"by-dev-dataNode-7-by-dev-rootcoord-dml_55_439426855970366432v1\" timestamp:439426881808760833 "] [recoverTs=439426881546616838] [importing=false]
[2023/02/13 09:51:56.516 +00:00] [INFO] [datanode/channel_meta.go:296] ["begin to init pk bloom filter"] [segmentID=439426855970366797] ["stats bin logs"=1]
[2023/02/13 09:51:56.515 +00:00] [INFO] [msgdispatcher/dispatcher.go:86] ["creating dispatcher..."] [pchannel=by-dev-rootcoord-dml_77] [subName=datanode-17-by-dev-rootcoord-dml_77_439426855970567678v1-true] [isMain=true]
[2023/02/13 09:51:56.516 +00:00] [DEBUG] [server/rocksmq_impl.go:479] ["Rocksmq create consumer group successfully "] [topic=by-dev-rootcoord-dml_77] [group=datanode-17-by-dev-rootcoord-dml_77_439426855970567678v1-true] [elapsed=0]
[2023/02/13 09:51:56.516 +00:00] [DEBUG] [server/rocksmq_impl.go:505] ["Rocksmq register consumer successfully "] [topic=by-dev-rootcoord-dml_77] [elapsed=0]
[2023/02/13 09:51:56.516 +00:00] [INFO] [msgstream/mq_msgstream.go:758] ["MsgStream begin to seek start msg: "] [channel=by-dev-rootcoord-dml_77] [MessageID="zEbxs2UoGQY="]
panic: cannot find token 'by-dev-rootcoord-dml' in ''

goroutine 1432 [running]:
panic({0x32f2fa0, 0xc003a82d00})
	/usr/local/go/src/runtime/panic.go:941 +0x397 fp=0xc00412b308 sp=0xc00412b248 pc=0x11edcf7
github.com/milvus-io/milvus/internal/datanode.(*ddNode).Operate(0xc003691200, {0xc003d07f30?, 0x1?, 0x1?})
	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_dd_node.go:226 +0x2d5f fp=0xc00412be90 sp=0xc00412b308 pc=0x27379df
github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work(0xc003e9bcc0)
	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:127 +0x2ac fp=0xc00412bfc8 sp=0xc00412be90 pc=0x257d9cc
github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start.func1()
	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:71 +0x26 fp=0xc00412bfe0 sp=0xc00412bfc8 pc=0x257d406
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00412bfe8 sp=0xc00412bfe0 pc=0x12230a1
created by github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start
	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:71 +0x79

goroutine 1 [semacquire]:
runtime.gopark(0x1cfd8bd?, 0x4f6e7c0?, 0xe0?, 0xe7?, 0x11c3e25?)
	/usr/local/go/src/runtime/proc.go:361 +0xd6 fp=0xc001135748 sp=0xc001135728 pc=0x11f0f56
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:367
runtime.semacquire1(0xc000026d78, 0x30?, 0x1, 0x0)
	/usr/local/go/src/runtime/sema.go:144 +0x1f3 fp=0xc0011357b0 sp=0xc001135748 pc=0x12020d3
sync.runtime_Semacquire(0x11ec59f?)
	/usr/local/go/src/runtime/sema.go:56 +0x25 fp=0xc0011357e0 sp=0xc0011357b0 pc=0x121ed45
sync.(*WaitGroup).Wait(0xc000d4ccc0?)
	/usr/local/go/src/sync/waitgroup.go:136 +0x52 fp=0xc001135808 sp=0xc0011357e0 pc=0x1231852
github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run(0xc001135e58, 0x1, {0xc000d60a90?, 0xe?})
	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:298 +0x965 fp=0xc001135e08 sp=0xc001135808 pc=0x2d24dc5
github.com/milvus-io/milvus/cmd/milvus.(*run).execute(0xc000d88060, {0xc0001ac060?, 0x3, 0x3}, 0xc0004b75c0)
	/go/src/github.com/milvus-io/milvus/cmd/milvus/run.go:112 +0x66e fp=0xc001135ee0 sp=0xc001135e08 pc=0x2d3152e
github.com/milvus-io/milvus/cmd/milvus.RunMilvus({0xc0001ac060?, 0x3, 0x3})
	/go/src/github.com/milvus-io/milvus/cmd/milvus/milvus.go:60 +0x21e fp=0xc001135f58 sp=0xc001135ee0 pc=0x2d30dbe
main.main()
	/go/src/github.com/milvus-io/milvus/cmd/main.go:26 +0x2e fp=0xc001135f80 sp=0xc001135f58 pc=0x2d3422e
runtime.main()
	/usr/local/go/src/runtime/proc.go:250 +0x212 fp=0xc001135fe0 sp=0xc001135f80 pc=0x11f0b92
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc001135fe8 sp=0xc001135fe0 pc=0x12230a1
```

### Milvus Log

deploy task: upgrade milvus mode：standalone old image tag: v2.2.0 new image tag: master-20230213-7c495303
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_cron/detail/deploy_test_cron/339/pipeline
log:
[artifacts-pulsar-standalone-upgrade-339-server-logs (2).tar.gz](https://github.com/milvus-io/milvus/files/10738869/artifacts-pulsar-standalone-upgrade-339-server-logs.2.tar.gz)
[artifacts-pulsar-standalone-upgrade-339-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10738868/artifacts-pulsar-standalone-upgrade-339-pytest-logs.tar.gz)

### Anything else?

It works well with image master-20230210-9b8f04fd

**Comment by zhuwenxing** [comment]
It can reproduced stable after master-20230213-7c495303

**Comment by zhuwenxing** [comment]
@congqixia 
Is this issue related to the https://github.com/milvus-io/milvus/issues/22181?

**Comment by congqixia** [comment]
@zhuwenxing might be related. Actually issue 22181 is root cause for 22158. Milvus did not crash in these cases.  Could have some other problem in master branch

**Comment by zhuwenxing** [comment]
This issue is also reproduced in cluster mode.
The datanode crashed with the same error.
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_cron/detail/deploy_test_cron/350/pipeline/278
error log:
```
[2023/02/15 10:00:02.890 +00:00] [INFO] [datanode/data_sync_service.go:152] ["dataSyncService starting flow graph"] [collectionID=439472205761842500] [vChanName=by-dev-rootcoord-dml_115_439472205761842500v1]
[2023/02/15 10:00:02.890 +00:00] [INFO] [datanode/data_node.go:427] ["handle put event: new data sync service success"] [vChanName=by-dev-rootcoord-dml_115_439472205761842500v1]
[2023/02/15 10:00:02.890 +00:00] [ERROR] [datanode/flow_graph_dd_node.go:225] ["convert dmlVChannel to deltaVChannel failed"] [vchannel=by-dev-rootcoord-dml_115_439472205761842500v1] [error="cannot find token 'by-dev-rootcoord-dml' in ''"] [stack="github.com/milvus-io/milvus/internal/datanode.(*ddNode).Operate\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_dd_node.go:225\ngithub.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work\n\t/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:127"]
panic: cannot find token 'by-dev-rootcoord-dml' in ''

goroutine 4196 [running]:
panic({0x32f51a0, 0xc0018f3d10})
	/usr/local/go/src/runtime/panic.go:941 +0x397 fp=0xc001727308 sp=0xc001727248 pc=0x11eecf7
github.com/milvus-io/milvus/internal/datanode.(*ddNode).Operate(0xc000e16580, {0xc001bab310?, 0x1?, 0x1?})
	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_dd_node.go:226 +0x2d5f fp=0xc001727e90 sp=0xc001727308 pc=0x2739a1f
github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work(0xc0018a8280)
	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:127 +0x2ac fp=0xc001727fc8 sp=0xc001727e90 pc=0x257f28c
github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start.func1()
	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:71 +0x26 fp=0xc001727fe0 sp=0xc001727fc8 pc=0x257ecc6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc001727fe8 sp=0xc001727fe0 pc=0x12240a1
created by github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start
	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:71 +0x79

```
logs:

[artifacts-pulsar-cluster-upgrade-350-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/10751455/artifacts-pulsar-cluster-upgrade-350-server-logs.1.tar.gz)
[artifacts-pulsar-cluster-upgrade-350-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10751457/artifacts-pulsar-cluster-upgrade-350-pytest-logs.tar.gz)

**Comment by bigsheeper** [comment]
Proxy didn't set the `ShardName` field when produce delete message to msgstream in v2.2.0, so after upgraded, DataNode converts shardName/vchannel to deltaVchannel failed before forwarding delete messages.
https://github.com/milvus-io/milvus/blob/8ec5ba13dc326140d2d887ba5564c34aa2570e74/internal/datanode/flow_graph_dd_node.go#L223-L228

Both these two solutions can solve this:
1. Fix up v2.2.0, set the `ShardName` field.
2. Ignore this since QueryNodeV2 doesn't need delta channel, forwarding delete logic would be removed soon.

**Comment by xiaofan-luan** [comment]
fix on 2.2 may not help this issue.
we need to fix on 2.3 I guess. Because it's not for sure user will upgrade to the version in 2.2

**Comment by bigsheeper** [comment]
> fix on 2.2 may not help this issue. we need to fix on 2.3 I guess. Because it's not for sure user will upgrade to the version in 2.2

@xiaofan-luan You're right, thanks for reminding.  So **For 2.2.x**, how about solution3:

3. Do not panic when convert channel, just assign an empty ShardName in message, and the delete message would dispatcher to the all vchannels, seems to be no effect on correctness.

As for 2.3, let's wait for solution2.

**Comment by zhuwenxing** [comment]
@bigsheeper 
Any progress?  It is still a stable reproduced issue.

**Comment by bigsheeper** [comment]
> @bigsheeper Any progress? It is still a stable reproduced issue.

QueryNodeV2 could solve this.

**Comment by bigsheeper** [comment]
@zhuwenxing should be fixed by QueryNodeV2, please help to make verify

**Comment by zhuwenxing** [comment]
Not reproduced in master-20230423-b7cb34b9
