### ISSUE TITLE
[Bug]: [benchmark][standalone] Milvus search with gist1m data，search concurrent number is one, and an error is reported"server Unavailable"

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#22214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230215-cad39ebf
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.2dev4
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Instance ID: fouramf-concurrent-search-7c7wv
release_name_prefix:
fouramf-concurrent-search-7c7wv
deploy_config:
fouramf-server-standalone-8c16m
case_params:
fouramf-client-gist1m-concurrent-diskann

server: 

```
fouramf-concurrent-search-7c7wv-3-21-5795-etcd-0                  1/1     Running     0               127m    10.104.9.22    4am-node14   <none>           <none>
fouramf-concurrent-search-7c7wv-3-21-5795-milvus-standalon8h2l8   1/1     Running     8 (9m31s ago)   127m    10.104.1.166   4am-node10   <none>           <none>
fouramf-concurrent-search-7c7wv-3-21-5795-minio-5687bf5db-5gcj7   1/1     Running     0               127m    10.104.9.20    4am-node14   <none>           <none> 
```

client:

```

[2023-02-16 02:45:54,483 -  INFO - fouram]:  Type     Name                                                                                  50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100% # reqs (stats.py:740)
[2023-02-16 02:45:54,483 -  INFO - fouram]: --------|--------------------------------------------------------------------------------|---------|------|------|------|------|------|------|------|------|------|------|------| (stats.py:750)
[2023-02-16 02:45:54,483 -  INFO - fouram]:  grpc     search                                                                                110    120    120    160    170    170    180    240    530   2400   2400   7964 (stats.py:754)
[2023-02-16 02:45:54,483 -  INFO - fouram]: --------|--------------------------------------------------------------------------------|---------|------|------|------|------|------|------|------|------|------|------|------| (stats.py:755)
[2023-02-16 02:45:54,484 -  INFO - fouram]:  None     Aggregated                                                                            110    120    120    160    170    170    180    240    530   2400   2400   7964 (stats.py:758)
[2023-02-16 02:45:54,484 -  INFO - fouram]:  (stats.py:759)
[2023-02-16 02:45:56,047 - ERROR - fouram]: RPC error: [search], <MilvusUnavailableException: (code=1, message=server Unavailable: Retry timeout: 60s)>, <Time:{'RPC start': '2023-02-16 02:44:22.685346', 'RPC error': '2023-02-16 02:45:56.047299'}> (decorators.py:108)
[2023-02-16 02:45:56,050 - ERROR - fouram]: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 472, in search
    return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 441, in _execute_search_requests
    raise pre_err
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 429, in _execute_search_requests
    response = self._stub.Search(request, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1676515556.046870502","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3260,"referenced_errors":[{"created":"@1676515556.046869428","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":167,"grpc_status":14}]}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/src/fouram/client/util/api_request.py", line 33, in inner_wrapper
    res = func(*args, **kwargs)
  File "/src/fouram/client/util/api_request.py", line 70, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 614, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 66, in handler
    raise MilvusUnavailableException(message=f"server Unavailable: {timeout_msg}") from e
pymilvus.exceptions.MilvusUnavailableException: <MilvusUnavailableException: (code=1, message=server Unavailable: Retry timeout: 60s)>
 (api_request.py:48)
[2023-02-16 02:45:56,050 - ERROR - fouram]: (api_response) : <MilvusUnavailableException: (code=1, message=server Unavailable: Retry timeout: 60s)> (api_request.py:49)
[2023-02-16 02:45:56,051 - ERROR - fouram]: [CheckFunc] search request check failed, response:<MilvusUnavailableException: (code=1, message=server Unavailable: Retry timeout: 60s)> (func_check.py:42)
[2023-02-16 02:45:56,185 - WARNING - fouram]: [93m[search] retry:4, cost: 0.27s, reason: <_InactiveRpcError: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (decorators.py:71)
[2023-02-16 02:45:56,457 - WARNING - fouram]: [93m[search] retry:5, cost: 0.81s, reason: <_InactiveRpcError: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (decorators.py:71)
[2023-02-16 02:45:57,270 - WARNING - fouram]: [93m[search] retry:6, cost: 2.43s, reason: <_InactiveRpcError: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (decorators.py:71)
[2023-02-16 02:45:59,702 - WARNING - fouram]: [93m[search] retry:7, cost: 7.29s, reason: <_InactiveRpcError: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (decorators.py:71)
[2023-02-16 02:46:06,996 - WARNING - fouram]: [93m[search] retry:8, cost: 21.87s, reason: <_InactiveRpcError: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (decorators.py:71)
```
server log：
<img width="1299" alt="截屏2023-02-16 15 04 07" src="https://user-images.githubusercontent.com/34296482/219292309-91f53c9e-af4b-4e49-a9f2-db6dde44d907.png">

grafana with standalone：
<img width="1358" alt="截屏2023-02-16 15 05 23" src="https://user-images.githubusercontent.com/34296482/219292529-21ba319f-6f23-49e7-960f-4ee6bd7d6f3c.png">

### Steps To Reproduce

```markdown
1. create a collection 
        2. build diskann index 
        3. insert a 1m of vectors
        4. flush collection
        5. build index on vector column with the same parameters
        6. count the total number of rows
        7. load collection
        8. perform concurrent operations-> search raise error
```

### Anything else?

```
'client': {'test_case_type': 'ConcurrentClientBase',
            'test_case_name': 'test_concurrent_locust_custom_parameters',
            'test_case_params': {'dataset_params': {'dim': 768,
                                                    'dataset_name': 'gist',
                                                    'dataset_size': 1000000,
                                                    'ni_per': 1000,
                                                    'metric_type': 'L2'},
                                 'collection_params': {'other_fields': []},
                                 'load_params': {},
                                 'search_params': {},
                                 'index_params': {'index_type': 'DISKANN',
                                                  'index_param': {}},
                                 'concurrent_params': {'concurrent_number': 1,
                                                       'during_time': 3600,
                                                       'interval': 20,
                                                       'spawn_rate': None},
                                 'concurrent_tasks': [{'type': 'search',
                                                       'weight': 1,
                                                       'params': {'nq': 1,
                                                                  'top_k': 1,
                                                                  'search_param': {'search_list': 30},
                                                                  'random_data': True}}]},
            'run_id': 20230216,
            'datetime': '2023-02-16 02:20:34.317227',
            'client_version': '2.2'},
 'result': {'test_result': {'Aggregated': {'Requests': 29257,
                                           'Fails': 3,
                                           'RPS': 8.34,
                                           'fail_s': 0.0,
                                           'RT_max': 93741.09,
                                           'RT_avg': 118.98,
                                           'TP50': 100.0,
                                           'TP99': 230.0},
                            'search': {'Requests': 29257,
                                       'Fails': 3,
                                       'RPS': 8.34,
                                       'fail_s': 0.0,
                                       'RT_max': 93741.09,
                                       'RT_avg': 118.98,
                                       'TP50': 100.0,
                                       'TP99': 230.0}}}} (performance_template.py:127)
```

**Comment by yanliang567** [comment]
it looks like milvus crashed.
/assign @xige-16 
/unassign

**Comment by xiaocai2333** [comment]
same as: #22127

**Comment by elstic** [comment]
@xiaocai2333 This issue still exists.
deploy_config:fouramf-server-standalone-8c16m
case_params :fouramf-client-gist1m-concurrent-diskann
case_name:test_concurrent_locust_custom_parameters

server:
```
fouramf-concurrent-search-1677817800-3-14-9465-etcd-0             1/1     Running           0               138m    10.104.5.168    4am-node12   <none>           <none>
fouramf-concurrent-search-1677817800-3-14-9465-milvus-stankpvpg   1/1     Running           7 (8m44s ago)   138m    10.104.9.231    4am-node14   <none>           <none>
fouramf-concurrent-search-1677817800-3-14-9465-minio-79dd92nfb4   1/1     Running           0               138m    10.104.5.167    4am-node12   <none>           <none> 
```
client error log : 
![image](https://user-images.githubusercontent.com/48523564/222680160-5c45d8e5-6f74-47b3-abc3-e9097a76261b.png)

grafana:
![image](https://user-images.githubusercontent.com/48523564/222680806-e9cd91e1-1f2a-4e63-b3bc-acf438c58b88.png)

**Comment by xiaocai2333** [comment]
@elstic  Has the instance been deleted? I can’t find the corresponding log.

**Comment by elstic** [comment]
@xiaocai2333 This problem has not appeared recently and I will close it.
