### ISSUE TITLE
[Bug]: [ResourceGroup]Querycoord crashes if transfer num_node is -1

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#22224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230216-8ec5ba13
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):  pymilvus-2.3.0.dev38
```

### Current Behavior

querycoord crashes

```
yanliang-master-rg-milvus-datacoord-5fd5994946-bqgpq              1/1     Running            0                3h36m
yanliang-master-rg-milvus-datanode-5b7d9b67d8-pplml               1/1     Running            0                3h37m
yanliang-master-rg-milvus-indexcoord-8677f66cb6-h9c6k             1/1     Running            0                3h36m
yanliang-master-rg-milvus-indexnode-c98f8b679-4zbnf               1/1     Running            0                3h37m
yanliang-master-rg-milvus-proxy-84584d7578-rz4fv                  1/1     Running            0                3h37m
yanliang-master-rg-milvus-querycoord-5b584cc486-6gfsq             0/1     Running            3 (4s ago)       3h36m
yanliang-master-rg-milvus-querynode-86898c45d4-nklrl              1/1     Running            0                3h34m
yanliang-master-rg-milvus-rootcoord-6f644f9fd8-qbffq              1/1     Running            0                3h36m

```

### Expected Behavior

transfer_node(source=ct.default_resource_group_name,
                                        target=rg_name,
                                        num_node=-1)

### Steps To Reproduce

```markdown
testcase: test_transfer_node_with_wrong_num_node
```

### Milvus Log

```
[2023/02/16 08:48:48.243 +00:00] [INFO] [querycoordv2/services.go:975] ["create resource group request received"] [traceID=80b2fdc8b1c5d8d7415ff7990415cb81] [rgName=rg_yC7TggN4]
[2023/02/16 08:48:48.244 +00:00] [INFO] [meta/resource_manager.go:157] ["add resource group"] [rgName=rg_yC7TggN4]
[2023/02/16 08:48:48.263 +00:00] [INFO] [querycoordv2/services.go:1015] ["transfer node between resource group request received"] [traceID=b444b036591205ce2599dd56628da4b1] [source=__default_resource_group] [target=rg_yC7TggN4] [numNode=-1]
panic: runtime error: makeslice: cap out of range

goroutine 10589 [running]:
panic({0x335ede0, 0x3ac1180})
        /usr/local/go/src/runtime/panic.go:941 +0x397 fp=0xc001360f80 sp=0xc001360ec0 pc=0x11eecf7
runtime.panicmakeslicecap(...)
        /usr/local/go/src/runtime/slice.go:33
runtime.makeslice(0xc0013610f0?, 0xc0007a5560?, 0xc0013610f0?)
        /usr/local/go/src/runtime/slice.go:100 +0xa5 fp=0xc001360fa8 sp=0xc001360f80 pc=0x1207165
github.com/milvus-io/milvus/internal/querycoordv2/meta.(*ResourceManager).transferNodeInStore(0xc00041de80, {0xc001d692a8, 0x18}, {0xc001ed4e30, 0xb}, 0xffffffffffffffff)
        /go/src/github.com/milvus-io/milvus/internal/querycoordv2/meta/resource_manager.go:532 +0x1cf fp=0xc001361160 sp=0xc001360fa8 pc=0x2b5340f
github.com/milvus-io/milvus/internal/querycoordv2/meta.(*ResourceManager).TransferNode(0xc00041de80, {0xc001d692a8, 0x18}, {0xc001ed4e30, 0xb}, 0xffffffffffffffff)
        /go/src/github.com/milvus-io/milvus/internal/querycoordv2/meta/resource_manager.go:495 +0x1eb fp=0xc001361260 sp=0xc001361160 pc=0x2b52c2b
```

[quercoord.crash.log](https://github.com/milvus-io/milvus/files/10753972/quercoord.crash.log)

**Comment by yanliang567** [comment]
the same if transfer_replica in 
```
    @pytest.mark.parametrize("num_replica", [0, 99, -1, 0.5, True, "str"])
    def test_transfer_replica_with_wrong_num_replica(self, num_replica):
```

**Comment by yanliang567** [comment]
@weiliu1031 all works as expected with error, except num_node=True.
when num_node=True, I expected failure, but it did not.
I think it is caused by python language, but can we improve here?

**Comment by weiliu1031** [comment]
please verify this

**Comment by yanliang567** [comment]
verified on 2.2.0-20230228-91d251ab

**Comment by weiliu1031** [comment]
after discuss, we will accept bool param
