### ISSUE TITLE
[Bug]: [benchmark][standalone]Milvus inserts data in numbers that do not match what the num entities interface prints

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#22262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230216-b25b3ef4
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus==2.3.0.dev34
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server：

```
NAME                                                                STATUS      RESTARTS     AGE     IP              NODE           
fouramf-cron-master-1676563200-1-op-20-3274-milvus-standalm4ff4     Running     0            7m      10.104.6.17     4am-node13     
fouramf-cron-master-1676563200-1-op-20-3274-etcd-0                  Running     0            9m      10.104.6.14     4am-node13     
fouramf-cron-master-1676563200-1-op-20-3274-minio-57688fc97f6b9     Running     0            9m      10.104.6.16     4am-node13
```

client log：
`The inserted data is 100w data, the actual collection data is only 932,500`

```
[2023-02-17 01:30:36,579 -  INFO - fouram]: [Time] Collection.insert run in 0.0226s (api_request.py:41)
[2023-02-17 01:30:36,580 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_1Jhqn2MO): 932500 (base.py:291)
[2023-02-17 01:30:36,582 -  INFO - fouram]: [Base] Start inserting, ids: 996500 - 996999, data size: 1,000,000 (base.py:143)
[2023-02-17 01:30:36,606 -  INFO - fouram]: [Time] Collection.insert run in 0.0241s (api_request.py:41)
[2023-02-17 01:30:36,608 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_1Jhqn2MO): 932500 (base.py:291)
[2023-02-17 01:30:36,610 -  INFO - fouram]: [Base] Start inserting, ids: 997000 - 997499, data size: 1,000,000 (base.py:143)
[2023-02-17 01:30:36,633 -  INFO - fouram]: [Time] Collection.insert run in 0.0227s (api_request.py:41)
[2023-02-17 01:30:36,634 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_1Jhqn2MO): 932500 (base.py:291)
[2023-02-17 01:30:36,636 -  INFO - fouram]: [Base] Start inserting, ids: 997500 - 997999, data size: 1,000,000 (base.py:143)
[2023-02-17 01:30:36,659 -  INFO - fouram]: [Time] Collection.insert run in 0.0223s (api_request.py:41)
[2023-02-17 01:30:36,660 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_1Jhqn2MO): 932500 (base.py:291)
[2023-02-17 01:30:36,662 -  INFO - fouram]: [Base] Start inserting, ids: 998000 - 998499, data size: 1,000,000 (base.py:143)
[2023-02-17 01:30:36,684 -  INFO - fouram]: [Time] Collection.insert run in 0.022s (api_request.py:41)
[2023-02-17 01:30:36,685 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_1Jhqn2MO): 932500 (base.py:291)
[2023-02-17 01:30:36,687 -  INFO - fouram]: [Base] Start inserting, ids: 998500 - 998999, data size: 1,000,000 (base.py:143)
[2023-02-17 01:30:36,711 -  INFO - fouram]: [Time] Collection.insert run in 0.0239s (api_request.py:41)
[2023-02-17 01:30:36,712 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_1Jhqn2MO): 932500 (base.py:291)
[2023-02-17 01:30:36,714 -  INFO - fouram]: [Base] Start inserting, ids: 999000 - 999499, data size: 1,000,000 (base.py:143)
[2023-02-17 01:30:36,748 -  INFO - fouram]: [Time] Collection.insert run in 0.0333s (api_request.py:41)
[2023-02-17 01:30:36,750 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_1Jhqn2MO): 932500 (base.py:291)
[2023-02-17 01:30:36,752 -  INFO - fouram]: [Base] Start inserting, ids: 999500 - 999999, data size: 1,000,000 (base.py:143)
[2023-02-17 01:30:36,781 -  INFO - fouram]: [Time] Collection.insert run in 0.0288s (api_request.py:41)
[2023-02-17 01:30:36,782 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_1Jhqn2MO): 932500 (base.py:291)
[2023-02-17 01:30:36,788 -  INFO - fouram]: [Base] Total time of insert: 53.0426s, average number of vector bars inserted per second: 18852.7712, average time to insert 500 vectors per time: 0.0265s (base.py:210)
[2023-02-17 01:30:36,789 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_1Jhqn2MO): 932500 (base.py:291)
```
`The following error log was reported when inserting 1m again`
```
[2023-02-17 01:34:56,030 -  INFO - fouram]: [Base] Start inserting 1000000 vectors to collection fouram_1Jhqn2MO (base.py:161)
[2023-02-17 01:34:57,009 -  INFO - fouram]: [Base] Start inserting, ids: 0 - 99999, data size: 1,000,000 (base.py:143)
[2023-02-17 01:34:58,516 -  INFO - fouram]: [Time] Collection.insert run in 1.506s (api_request.py:41)
[2023-02-17 01:34:58,517 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_lR6ILphz): 0 (base.py:291)
[2023-02-17 01:34:59,601 -  INFO - fouram]: [Base] Start inserting, ids: 100000 - 199999, data size: 1,000,000 (base.py:143)
[2023-02-17 01:35:01,132 -  INFO - fouram]: [Time] Collection.insert run in 1.5301s (api_request.py:41)
[2023-02-17 01:35:01,134 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_lR6ILphz): 90391 (base.py:291)
[2023-02-17 01:35:02,234 -  INFO - fouram]: [Base] Start inserting, ids: 200000 - 299999, data size: 1,000,000 (base.py:143)
[2023-02-17 01:35:03,793 - ERROR - fouram]: RPC error: [batch_insert], <MilvusException: (code=1, message=IO error: No space left on device: While appending to file: /var/lib/milvus/rdb_data/000437.log: No space left on device)>, <Time:{'RPC start': '2023-02-17 01:35:02.261818', 'RPC error': '2023-02-17 01:35:03.793458'}> (decorators.py:108)
[2023-02-17 01:35:03,797 - ERROR - fouram]: Traceback (most recent call last):
  File "/src/fouram/client/util/api_request.py", line 33, in inner_wrapper
    res = func(*args, **kwargs)
  File "/src/fouram/client/util/api_request.py", line 70, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 430, in insert
    res = conn.batch_insert(self._name, entities, partition_name,
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 388, in batch_insert
    raise err
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 384, in batch_insert
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=IO error: No space left on device: While appending to file: /var/lib/milvus/rdb_data/000437.log: No space left on device)>
 (api_request.py:48)
[2023-02-17 01:35:03,797 - ERROR - fouram]: (api_response) : <MilvusException: (code=1, message=IO error: No space left on device: While appending to file: /var/lib/milvus/rdb_data/000437.log: No space left on device)> (api_request.py:49)
[2023-02-17 01:35:03,797 - ERROR - fouram]: [CheckFunc] insert request check failed, response:<MilvusException: (code=1, message=IO error: No space left on device: While appending to file: /var/lib/milvus/rdb_data/000437.log: No space left on device)> (func_check.py:48)
[2023-02-17 01:35:03,797 - ERROR - fouram]: [InsertBatch] Insert batch raise error:  (common_cases.py:246)
[2023-02-17 01:35:03,798 -  INFO - fouram]: [PerfTemplate] Actual parameters used: {'dataset_params': {'dim': 128, 'dataset_name': 'sift', 'dataset_size': '1m', 'ni_per': 125000}, 'collection_params': {}, 'load_params': {}, 'search_params': {}} (performance_template.py:57)
[2023-02-17 01:35:03,798 -  INFO - fouram]: [Base] Disconnect alias: default (base.py:67)
[2023-02-17 01:35:03,798 -  INFO - fouram]: [Base] Connection params: {'alias': 'default', 'host': 'fouramf-cron-master-1676563200-1-op-20-3274-milvus.qa-milvus', 'port': 19530} (base.py:61)
[2023-02-17 01:35:03,804 -  INFO - fouram]: [Base] Start clean all collections ['fouram_lR6ILphz'] (base.py:97)
[2023-02-17 01:35:03,807 -  INFO - fouram]: [Base] Create collection fouram_MbLgVpIj (base.py:81)
[2023-02-17 01:35:03,809 - ERROR - fouram]: RPC error: [create_collection], <MilvusException: (code=1, message=IO error: No space left on device: While appending to file: /var/lib/milvus/rdb_data/000437.log: No space left on device)>, <Time:{'RPC start': '2023-02-17 01:35:03.808210', 'RPC error': '2023-02-17 01:35:03.809196'}> (decorators.py:108)
[2023-02-17 01:35:03,809 - ERROR - fouram]: Traceback (most recent call last):
  File "/src/fouram/client/util/api_request.py", line 33, in inner_wrapper
    res = func(*args, **kwargs)
  File "/src/fouram/client/util/api_request.py", line 70, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 120, in __init__
    conn.create_collection(self._name, schema, shards_num=self._shards_num, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 212, in create_collection
    raise MilvusException(status.error_code, status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=IO error: No space left on device: While appending to file: /var/lib/milvus/rdb_data/000437.log: No space left on device)>
 (api_request.py:48)
[2023-02-17 01:35:03,809 - ERROR - fouram]: (api_response) : <MilvusException: (code=1, message=IO error: No space left on device: While appending to file: /var/lib/milvus/rdb_data/000437.log: No space left on device)> (api_request.py:49)
[2023-02-17 01:35:03,809 - ERROR - fouram]: [CheckFunc] init_collection request check failed, response:<MilvusException: (code=1, message=IO error: No space left on device: While appending to file: /var/lib/milvus/rdb_data/000437.log: No space left on device)> (func_check.py:48)
[2023-02-17 01:35:03,809 - ERROR - fouram]: [InsertBatch] Insert batch raise error:  (common_cases.py:246)
```

### Steps To Reproduce

```markdown
1. create a collection 
        2. insert a 1m of data in batches
        3. count the total number of rows
        4. clean all collections
```

### Anything else?

```
 'client': {'test_case_type': 'InsertBatch',
            'test_case_name': 'test_batch_insert_standalone',
            'test_case_params': {'dataset_params': {'dim': 128,
                                                    'dataset_name': 'sift',
                                                    'dataset_size': '1m',
                                                    'ni_per': 500},
                                 'collection_params': {},
                                 'load_params': {},
                                 'search_params': {}},
            'run_id': 20230216,
            'datetime': '2023-02-17 01:25:54.187719',
            'client_version': '2.2'},
 'result': {'test_result': {'insert': {'total_time': 53.0426,
                                       'VPS': 18852.7712,
                                       'batch_time': 0.0265,
                                       'batch': 500}}}} 
```

**Comment by xiaofan-luan** [comment]
@jingkl  @yanliang567 
it seems the insert fail with error  No space left on device

**Comment by jingkl** [comment]
It is estimated that the machine disk resources are not enough，first close issue

**Comment by jingkl** [comment]
Is the inconsistent insertion of the previous data also caused by the disk? @xiaofan-luan

**Comment by jingkl** [comment]
argo：fouramf-cron-master-1676908800-3

params：

```
{'server': {'deploy_tool': 'helm',
            'deploy_mode': 'standalone',
            'config_name': 'standalone_8c16m',
            'config': {'standalone': {'resources': {'limits': {'cpu': '8.0',
                                                               'memory': '16Gi'},
                                                    'requests': {'cpu': '5.0',
                                                                 'memory': '9Gi'}},
                                      'persistence': {'persistentVolumeClaim': {'storageClass': 'local-path'}}},
                       'cluster': {'enabled': False},
                       'etcd': {'replicaCount': 1,
                                'global': {'storageClass': 'local-path'},
                                'metrics': {'enabled': True,
                                            'podMonitor': {'enabled': True}}},
                       'minio': {'mode': 'standalone',
                                 'persistence': {'storageClass': 'local-path'},
                                 'metrics': {'serviceMonitor': {'enabled': False}}},
                       'pulsar': {'enabled': False},
                       'metrics': {'serviceMonitor': {'enabled': True}},
                       'image': {'all': {'repository': 'harbor.milvus.io/dockerhub/milvusdb/milvus',
                                         'tag': '2.2.0-20230221-c2c8ddd4'}}},
            'host': 'fouramf-cron-master-1676908800-1-milvus.qa-milvus.svc.cluster.local'},
 'client': {'test_case_type': 'InsertBatch',
            'test_case_name': 'test_batch_insert_standalone',
            'test_case_params': {'dataset_params': {'dim': 128,
                                                    'dataset_name': 'sift',
                                                    'dataset_size': '1m',
                                                    'ni_per': 500},
                                 'collection_params': {},
                                 'load_params': {},
                                 'search_params': {}},
            'run_id': 20230220,
            'datetime': '2023-02-21 09:38:34.871152',
            'client_version': '2.2.3'},
 'result': {'test_result': {'insert': {'total_time': 54.3799,
                                       'VPS': 18389.1475,
                                       'batch_time': 0.0272,
                                       'batch': 500}}}} 
```

server：
```
NAME                                                              READY   STATUS      RESTARTS         AGE     IP              NODE         NOMINATED NODE   READINESS GATES
fouramf-cron-master-1676908800-1-etcd-0                           1/1     Running     0                2m29s   10.104.1.85     4am-node10   <none>           <none>
fouramf-cron-master-1676908800-1-milvus-standalone-587b78f2ljjp   1/1     Running     0                2m29s   10.104.12.125   4am-node17   <none>           <none>
fouramf-cron-master-1676908800-1-minio-74cf54956b-jf87d           1/1     Running     0                2m29s   10.104.1.82     4am-node10   <none>           <none> (cli_client.py:130)
```

Recently, master's tag has a problem of inconsistency between inserted data and actual data.
```


client log start：


[2023-02-21 09:41:05,533 -  INFO - fouram]: [Base] Start clean all collections [] (base.py:98)
[2023-02-21 09:41:05,534 -  INFO - fouram]: [Base] Create collection fouram_1bj3Vp4K (base.py:82)
[2023-02-21 09:41:05,566 -  INFO - fouram]: [Base] Collection schema: {'auto_id': False, 'description': '', 'fields': [{'name': 'id', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float_vector', 'description': '', 'type': <DataType.FLOAT_VECTOR: 101>, 'params': {'dim': 128}}]} (base.py:129)
[2023-02-21 09:41:05,566 -  INFO - fouram]: [CommonCases] Prepare collection fouram_1bj3Vp4K done. (common_cases.py:52)
[2023-02-21 09:41:05,566 -  INFO - fouram]: [Base] Start inserting 1000000 vectors to collection fouram_1bj3Vp4K (base.py:162)
[2023-02-21 09:41:06,484 -  INFO - fouram]: [Base] Start inserting, ids: 0 - 499, data size: 1,000,000 (base.py:144)
[2023-02-21 09:41:06,514 -  INFO - fouram]: [Time] Collection.insert run in 0.0295s (api_request.py:41)
[2023-02-21 09:41:06,515 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_1bj3Vp4K): 0 (base.py:292)
[2023-02-21 09:41:06,519 -  INFO - fouram]: [Base] Start inserting, ids: 500 - 999, data size: 1,000,000 (base.py:144)
[2023-02-21 09:41:06,543 -  INFO - fouram]: [Time] Collection.insert run in 0.0235s (api_request.py:41)
[2023-02-21 09:41:06,544 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_1bj3Vp4K): 0 (base.py:292)
[2023-02-21 09:41:06,547 -  INFO - fouram]: [Base] Start inserting, ids: 1000 - 1499, data size: 1,000,000 (base.py:144)
[2023-02-21 09:41:06,571 -  INFO - fouram]: [Time] Collection.insert run in 0.0238s (api_request.py:41)
[2023-02-21 09:41:06,572 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_1bj3Vp4K): 0 (base.py:292)
[2023-02-21 09:41:06,576 -  INFO - fouram]: [Base] Start inserting, ids: 1500 - 1999, data size: 1,000,000 (base.py:144)
[2023-02-21 09:41:06,606 -  INFO - fouram]: [Time] Collection.insert run in 0.0298s (api_request.py:41)
[2023-02-21 09:41:06,607 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_1bj3Vp4K): 0 (base.py:292)
[2023-02-21 09:41:06,612 -  INFO - fouram]: [Base] Start inserting, ids: 2000 - 2499, data size: 1,000,000 (base.py:144)
[2023-02-21 09:41:06,636 -  INFO - fouram]: [Time] Collection.insert run in 0.0242s (api_request.py:41)
[2023-02-21 09:41:06,637 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_1bj3Vp4K): 0 (base.py:292)
[2023-02-21 09:41:06,641 -  INFO - fouram]: [Base] Start inserting, ids: 2500 - 2999, data size: 1,000,000 (base.py:144)
[2023-02-21 09:41:06,664 -  INFO - fouram]: [Time] Collection.insert run in 0.0231s (api_request.py:41)
[2023-02-21 09:41:06,665 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_1bj3Vp4K): 0 (base.py:292)
[2023-02-21 09:41:06,668 -  INFO - fouram]: [Base] Start inserting, ids: 3000 - 3499, data size: 1,000,000 (base.py:144)
[2023-02-21 09:41:06,693 -  INFO - fouram]: [Time] Collection.insert run in 0.0247s (api_request.py:41)
[2023-02-21 09:41:06,694 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_1bj3Vp4K): 0 (base.py:292)
[2023-02-21 09:41:06,698 -  INFO - fouram]: [Base] Start inserting, ids: 3500 - 3999, data size: 1,000,000 (base.py:144)
[2023-02-21 09:41:06,722 -  INFO - fouram]: [Time] Collection.insert run in 0.0237s (api_request.py:41)
[2023-02-21 09:41:06,723 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_1bj3Vp4K): 0 (base.py:292)
[2023-02-21 09:41:06,726 -  INFO - fouram]: [Base] Start inserting, ids: 4000 - 4499, data size: 1,000,000 (base.py:144)
[2023-02-21 09:41:06,749 -  INFO - fouram]: [Time] Collection.insert run in 0.023s (api_request.py:41)
[2023-02-21 09:41:06,751 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_1bj3Vp4K): 0 (base.py:292)
[2023-02-21 09:41:06,754 -  INFO - fouram]: [Base] Start inserting, ids: 4500 - 4999, data size: 1,000,000 (base.py:144)
[2023-02-21 09:41:06,778 -  INFO - fouram]: [Time] Collection.insert run in 0.0238s (api_request.py:41)
[2023-02-21 09:41:06,779 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_1bj3Vp4K): 0 (base.py:292)
[2023-02-21 09:41:06,783 -  INFO - fouram]: [Base] Start inserting, ids: 5000 - 5499, data size: 1,000,000 (base.py:144)
[2023-02-21 09:41:06,807 -  INFO - fouram]: [Time] Collection.insert run in 0.0232s (api_request.py:41)
[2023-02-21 09:41:06,807 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_1bj3Vp4K): 0 (base.py:292)
[2023-02-21 09:41:06,811 -  INFO - fouram]: [Base] Start inserting, ids: 5500 - 5999, data size: 1,000,000 (base.py:144)
[2023-02-21 09:41:06,833 -  INFO - fouram]: [Time] Collection.insert run in 0.0222s (api_request.py:41)
[2023-02-21 09:41:06,834 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_1bj3Vp4K): 0 (base.py:292)



client log end：


```
[2023-02-21 09:42:16,938 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_1bj3Vp4K): 934529 (base.py:292)
[2023-02-21 09:42:16,941 -  INFO - fouram]: [Base] Start inserting, ids: 997500 - 997999, data size: 1,000,000 (base.py:144)
[2023-02-21 09:42:16,990 -  INFO - fouram]: [Time] Collection.insert run in 0.0484s (api_request.py:41)
[2023-02-21 09:42:16,991 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_1bj3Vp4K): 934529 (base.py:292)
[2023-02-21 09:42:16,993 -  INFO - fouram]: [Base] Start inserting, ids: 998000 - 998499, data size: 1,000,000 (base.py:144)
[2023-02-21 09:42:17,018 -  INFO - fouram]: [Time] Collection.insert run in 0.0244s (api_request.py:41)
[2023-02-21 09:42:17,019 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_1bj3Vp4K): 967475 (base.py:292)
[2023-02-21 09:42:17,021 -  INFO - fouram]: [Base] Start inserting, ids: 998500 - 998999, data size: 1,000,000 (base.py:144)
[2023-02-21 09:42:17,080 -  INFO - fouram]: [Time] Collection.insert run in 0.058s (api_request.py:41)
[2023-02-21 09:42:17,081 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_1bj3Vp4K): 967475 (base.py:292)
[2023-02-21 09:42:17,083 -  INFO - fouram]: [Base] Start inserting, ids: 999000 - 999499, data size: 1,000,000 (base.py:144)
[2023-02-21 09:42:17,107 -  INFO - fouram]: [Time] Collection.insert run in 0.0237s (api_request.py:41)
[2023-02-21 09:42:17,108 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_1bj3Vp4K): 967475 (base.py:292)
[2023-02-21 09:42:17,110 -  INFO - fouram]: [Base] Start inserting, ids: 999500 - 999999, data size: 1,000,000 (base.py:144)
[2023-02-21 09:42:17,135 -  INFO - fouram]: [Time] Collection.insert run in 0.0239s (api_request.py:41)
[2023-02-21 09:42:17,135 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_1bj3Vp4K): 967475 (base.py:292)
[2023-02-21 09:42:17,142 -  INFO - fouram]: [Base] Total time of insert: 54.3799s, average number of vector bars inserted per second: 18389.1475, average time to insert 500 vectors per time: 0.0272s (base.py:211)
[2023-02-21 09:42:17,143 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_1bj3Vp4K): 967475 
```
