### ISSUE TITLE
[Bug]: [benchmark] Failed to create index after inserting 10 million data 

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#22304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230216-8ec5ba13
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.0.dev34
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

deploy_config
fouramf-server-cluster-8c32m-querynode3
case_params
fouramf-client-sift-rg3-replica3
other_params
 --milvus_tag=master-20230216-8ec5ba13 -k test_concurrent_locust_custom_parameters -s --deploy_mode=cluster --client_test_skip  --deploy_retain

server: 
argo task:fouramf-qd9qq
```
fouramf-qd9qq-5-3701-etcd-0                                       1/1     Running            0              5m41s   10.104.5.51    4am-node12   <none>           <none>
fouramf-qd9qq-5-3701-etcd-1                                       1/1     Running            0              5m41s   10.104.6.95    4am-node13   <none>           <none>
fouramf-qd9qq-5-3701-etcd-2                                       1/1     Running            0              5m40s   10.104.1.14    4am-node10   <none>           <none>
fouramf-qd9qq-5-3701-milvus-datacoord-c5f8cc8fd-grdnc             1/1     Running            0              5m41s   10.104.5.40    4am-node12   <none>           <none>
fouramf-qd9qq-5-3701-milvus-datanode-59cf6484fb-84jj9             1/1     Running            0              5m41s   10.104.6.88    4am-node13   <none>           <none>
fouramf-qd9qq-5-3701-milvus-indexcoord-6f8449dc6b-h7fg9           1/1     Running            0              5m41s   10.104.6.90    4am-node13   <none>           <none>
fouramf-qd9qq-5-3701-milvus-indexnode-9ccdbf677-qpxhh             1/1     Running            0              5m41s   10.104.6.89    4am-node13   <none>           <none>
fouramf-qd9qq-5-3701-milvus-proxy-5fbcff5d58-rflpq                1/1     Running            1 (100s ago)   5m41s   10.104.6.86    4am-node13   <none>           <none>
fouramf-qd9qq-5-3701-milvus-querycoord-6fb9bffbfc-f2rhw           1/1     Running            0              5m41s   10.104.5.38    4am-node12   <none>           <none>
fouramf-qd9qq-5-3701-milvus-querynode-668c97f5cf-5r5bc            1/1     Running            0              5m41s   10.104.9.98    4am-node14   <none>           <none>
fouramf-qd9qq-5-3701-milvus-querynode-668c97f5cf-7znp6            1/1     Running            0              5m41s   10.104.6.87    4am-node13   <none>           <none>
fouramf-qd9qq-5-3701-milvus-querynode-668c97f5cf-f7x7s            1/1     Running            0              5m41s   10.104.5.41    4am-node12   <none>           <none>
fouramf-qd9qq-5-3701-milvus-rootcoord-b85ccd7ff-kvfxp             1/1     Running            0              5m41s   10.104.6.84    4am-node13   <none>           <none>
fouramf-qd9qq-5-3701-minio-0                                      1/1     Running            0              5m41s   10.104.5.53    4am-node12   <none>           <none>
fouramf-qd9qq-5-3701-minio-1                                      1/1     Running            0              5m40s   10.104.6.96    4am-node13   <none>           <none>
fouramf-qd9qq-5-3701-minio-2                                      1/1     Running            0              5m40s   10.104.1.16    4am-node10   <none>           <none>
fouramf-qd9qq-5-3701-minio-3                                      1/1     Running            0              5m40s   10.104.9.101   4am-node14   <none>           <none>
fouramf-qd9qq-5-3701-pulsar-bookie-0                              1/1     Running            0              5m41s   10.104.5.50    4am-node12   <none>           <none>
fouramf-qd9qq-5-3701-pulsar-bookie-1                              1/1     Running            0              5m41s   10.104.6.97    4am-node13   <none>           <none>
fouramf-qd9qq-5-3701-pulsar-bookie-2                              1/1     Running            0              5m40s   10.104.1.15    4am-node10   <none>           <none>
fouramf-qd9qq-5-3701-pulsar-bookie-init-59nzw                     0/1     Completed          0              5m41s   10.104.5.43    4am-node12   <none>           <none>
fouramf-qd9qq-5-3701-pulsar-broker-0                              1/1     Running            0              5m41s   10.104.5.39    4am-node12   <none>           <none>
fouramf-qd9qq-5-3701-pulsar-proxy-0                               1/1     Running            0              5m41s   10.104.6.85    4am-node13   <none>           <none>
fouramf-qd9qq-5-3701-pulsar-pulsar-init-lp7w7                     0/1     Completed          0              5m41s   10.104.5.42    4am-node12   <none>           <none>
fouramf-qd9qq-5-3701-pulsar-recovery-0                            1/1     Running            0              5m41s   10.104.5.44    4am-node12   <none>           <none>
fouramf-qd9qq-5-3701-pulsar-zookeeper-0                           1/1     Running            0              5m41s   10.104.5.52    4am-node12   <none>           <none>
fouramf-qd9qq-5-3701-pulsar-zookeeper-1                           1/1     Running            0              4m52s   10.104.6.100   4am-node13   <none>           <none>
fouramf-qd9qq-5-3701-pulsar-zookeeper-2                           1/1     Running            0              4m17s   10.104.1.18    4am-node10   <none>           <none>
```

client :
fouramf-xgbk4

client 
```
[2023-02-20 11:10:29,109 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_IIqap6kV): 9900000 (base.py:292)
[2023-02-20 11:10:29,292 -  INFO - fouram]: [Base] Start inserting, ids: 9950000 - 9999999, data size: 10,000,000 (base.py:144)
[2023-02-20 11:10:31,139 -  INFO - fouram]: [Time] Collection.insert run in 1.8465s (api_request.py:41)
[2023-02-20 11:10:31,142 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_IIqap6kV): 9924919 (base.py:292)
[2023-02-20 11:10:31,216 -  INFO - fouram]: [Base] Total time of insert: 223.9903s, average number of vector bars inserted per second: 44644.7904, average time to insert 50000 vectors per time: 1.12s (base.py:211)
[2023-02-20 11:10:31,217 -  INFO - fouram]: [Base] Start flush collection fouram_IIqap6kV (base.py:114)
[2023-02-20 11:10:33,736 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_IIqap6kV): 10000000 (base.py:292)
[2023-02-20 11:10:33,740 -  INFO - fouram]: [Base] Params of index: {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 8, 'efConstruction': 200}} (base.py:270)
[2023-02-20 11:10:33,741 -  INFO - fouram]: [Base] Start build index of HNSW for collection fouram_IIqap6kV, params:{'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 8, 'efConstruction': 200}} (base.py:257)
[2023-02-20 11:19:35,444 - ERROR - fouram]: RPC error: [get_index_state], <MilvusException: (code=1, message=syncTimeStamp Failed:StateCode=Abnormal)>, <Time:{'RPC start': '2023-02-20 11:19:35.442544', 'RPC error': '2023-02-20 11:19:35.444275'}> (decorators.py:108)
[2023-02-20 11:19:35,445 - ERROR - fouram]: RPC error: [wait_for_creating_index], <MilvusException: (code=1, message=syncTimeStamp Failed:StateCode=Abnormal)>, <Time:{'RPC start': '2023-02-20 11:10:33.746676', 'RPC error': '2023-02-20 11:19:35.445169'}> (decorators.py:108)
[2023-02-20 11:19:35,445 - ERROR - fouram]: RPC error: [create_index], <MilvusException: (code=1, message=syncTimeStamp Failed:StateCode=Abnormal)>, <Time:{'RPC start': '2023-02-20 11:10:33.742956', 'RPC error': '2023-02-20 11:19:35.445425'}> (decorators.py:108)
[2023-02-20 11:19:35,447 - ERROR - fouram]: Traceback (most recent call last):
  File "/src/fouram/client/util/api_request.py", line 33, in inner_wrapper
    res = func(*args, **kwargs)
  File "/src/fouram/client/util/api_request.py", line 70, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/index.py", line 74, in __init__
    conn.create_index(self._collection.name, self._field_name, self._index_params, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
```

### Steps To Reproduce

```markdown
1. create a collection or use an existing collection
        2. build index on vector column
        3. insert a certain number of vectors
        4. flush collection
        5. build index on vector column with the same parameters
        6. build index on on scalars column or not
        7. count the total number of rows
        8. load collection
        9. perform concurrent operations
        10. clean all collections or not
```

### Milvus Log

test_concurrent_locust_custom_parameters
```
    def test_concurrent_locust_custom_parameters(self, input_params: InputParamsBase):
        """
        :test steps:
            1. concurrent test and calculation of RT and QPS
        """
        # concurrent_tasks = [ConcurrentParams.params_search(), ConcurrentParams.params_query(ids=[1, 10, 100, 1000]),
        #                     ConcurrentParams.params_scene_insert_delete_flush(random_id=True, random_vector=True)]
        self.concurrency_template(input_params=input_params, cpu=dp.default_cpu, mem=dp.default_mem,
                                  old_version_format=False, sync_report=True,
                                  case_callable_obj=ConcurrentClientBase().scene_concurrent_locust)
                                  
 
     @check_params(ParamsFormat.common_concurrent)
    def scene_concurrent_locust(self, **kwargs):
        """
        :param kwargs:
            params: dict
            prepare: bool
            prepare_clean: bool
            clean_collection: bool
        :return:
        """
        from gevent import monkey
        monkey.patch_all()
        # from requests.packages.urllib3.util.ssl_ import create_urllib3_context; create_urllib3_context()
        import grpc.experimental.gevent as grpc_gevent
        grpc_gevent.init_gevent()
        from client.concurrent.locust_runner import LocustRunner

        # params prepare
        params = kwargs.get("params", None)
        prepare = kwargs.get("prepare", True)
        prepare_clean = kwargs.get("prepare_clean", True)
        clean_collection = kwargs.get("clean_collection", True)
        log.info("[ConcurrentClientBase] The detailed test steps are as follows: {}".format(self))

        # params parsing
        self.parsing_params(params)
        vector_type = get_vector_type(self.params_obj.dataset_params[pn.dataset_name])
        vector_default_field_name = get_default_field_name(vector_type,
                                                           self.params_obj.dataset_params.get(pn.vector_field_name, ""))

        obj_params = self.parser_concurrent_tasks(self.params_obj.concurrent_tasks, vector_default_field_name,
                                                  self.params_obj.dataset_params[pn.metric_type])

        # prepare data
        self.prepare_collection(vector_default_field_name, prepare, prepare_clean)
        if prepare is True:
            self.prepare_index(vector_field_name=vector_default_field_name,
                               metric_type=self.params_obj.dataset_params[pn.metric_type],
                               clean_index_before=True)
            self.prepare_insert(data_type=self.params_obj.dataset_params[pn.dataset_name],
                                dim=self.params_obj.dataset_params[pn.dim],
                                size=self.params_obj.dataset_params[pn.dataset_size],
                                ni=self.params_obj.dataset_params[pn.ni_per])
            self.prepare_flush()
            self.count_entities()
            self.prepare_index(vector_field_name=vector_default_field_name,
                               metric_type=self.params_obj.dataset_params[pn.metric_type])
            self.prepare_scalars_index()
        # else:
        #     self.release_collection()

        # load collection
        self.prepare_load(**self.params_obj.load_params)

        # set output log
        info_logout.reset_output()

        # concurrent test
        c_params = self.parser_concurrent_params()
        params_list = []
        for c_p in c_params:
            spawn_rate = c_p[pn.spawn_rate] if pn.spawn_rate in c_p else None
            con_client = LocustRunner(obj=self, obj_params=obj_params,
                                      interval=c_p[pn.interval], during_time=parser_time(c_p[pn.during_time]),
                                      concurrent_number=c_p[pn.concurrent_number], spawn_rate=spawn_rate)

            actual_params_used = copy.deepcopy(params)
            actual_params_used[pn.concurrent_params] = {
                pn.concurrent_number: c_p[pn.concurrent_number],
                pn.during_time: c_p[pn.during_time],
                pn.interval: c_p[pn.interval],
                pn.spawn_rate: spawn_rate
            }
            p = CaseIterParams(callable_object=con_client.start_runner,
                               actual_params_used=actual_params_used, case_type=self.__class__.__name__)
            params_list.append(p)
        yield params_list

        # clear env
        self.clear_collections(clean_collection=clean_collection)
        yield True
```

**Comment by xiaocai2333** [comment]
Looks like it can't connect to pulsar.
![pwflx0J5pf](https://user-images.githubusercontent.com/46207236/220105933-509631fe-c6bb-4e21-b37b-5790f31b82fa.png)

**Comment by yanliang567** [comment]
@xiaocai2333 any hints for why it failed to connect to pulsar?
/assign @xiaocai2333 
/unassign

**Comment by xiaocai2333** [comment]
@elstic  Are you sure the release server is what you tested? From the logs, I only see that the server is still in the startup phase, even I don't see any insert requests. Please verify.

**Comment by xiaocai2333** [comment]
> @elstic Are you sure the release server is what you tested? From the logs, I only see that the server is still in the startup phase, even I don't see any insert requests. Please verify.

And the server start failed, looks like the milvus service was started without waiting for the third-party component to start successfully.
