### ISSUE TITLE
[Bug]: Create collection failed with error `Broker: Invalid replication factor` when mq is kafka

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#22310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230220-ac6e8798
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):kafka    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2023-02-20T10:08:39.013Z] + python3 scripts/first_recall_test.py --host 10.101.99.125

[2023-02-20T10:08:40.373Z] 2023-02-20 10:08:40.286 | INFO     | __main__:milvus_recall_test:43 - Create collection sift_128_euclidean

[2023-02-20T10:08:40.628Z] RPC error: [create_collection], <MilvusException: (code=1, message=Broker: Invalid replication factor)>, <Time:{'RPC start': '2023-02-20 10:08:40.378025', 'RPC error': '2023-02-20 10:08:40.381999'}>

[2023-02-20T10:08:40.628Z] Traceback (most recent call last):

[2023-02-20T10:08:40.628Z]   File "scripts/first_recall_test.py", line 152, in <module>

[2023-02-20T10:08:40.628Z]     milvus_recall_test(host)

[2023-02-20T10:08:40.628Z]   File "scripts/first_recall_test.py", line 44, in milvus_recall_test

[2023-02-20T10:08:40.628Z]     collection = Collection(name=name, schema=default_schema)

[2023-02-20T10:08:40.628Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 120, in __init__

[2023-02-20T10:08:40.628Z]     conn.create_collection(self._name, schema, shards_num=self._shards_num, **kwargs)

[2023-02-20T10:08:40.628Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-02-20T10:08:40.628Z]     raise e

[2023-02-20T10:08:40.628Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-02-20T10:08:40.628Z]     return func(*args, **kwargs)

[2023-02-20T10:08:40.628Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-02-20T10:08:40.628Z]     ret = func(self, *args, **kwargs)

[2023-02-20T10:08:40.628Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-02-20T10:08:40.628Z]     raise e

[2023-02-20T10:08:40.628Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-02-20T10:08:40.628Z]     return func(self, *args, **kwargs)

[2023-02-20T10:08:40.628Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 212, in create_collection

[2023-02-20T10:08:40.628Z]     raise MilvusException(status.error_code, status.reason)

[2023-02-20T10:08:40.628Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Broker: Invalid replication factor)>

script returned exit code 1
```

### Expected Behavior

all test cases pass

### Milvus Log

image tag: master-20230220-ac6e8798
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_kafka_cron/detail/deploy_test_kafka_cron/385/pipeline/

log:
[artifacts-kafka-standalone-reinstall-385-server-second-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/10789000/artifacts-kafka-standalone-reinstall-385-server-second-deployment-logs.tar.gz)
[artifacts-kafka-standalone-reinstall-385-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10789001/artifacts-kafka-standalone-reinstall-385-pytest-logs.tar.gz)

helm values
```
[2023-02-20T10:06:35.972Z] + cat standalone-values.yaml

[2023-02-20T10:06:35.972Z] cluster:

[2023-02-20T10:06:35.972Z]   enabled: false

[2023-02-20T10:06:35.972Z] log:

[2023-02-20T10:06:35.972Z]   level: debug

[2023-02-20T10:06:35.972Z] image:

[2023-02-20T10:06:35.972Z]   all:

[2023-02-20T10:06:35.972Z]     repository: milvusdb/milvus

[2023-02-20T10:06:35.972Z]     tag: master-latest

[2023-02-20T10:06:35.972Z]     pullPolicy: IfNotPresent

[2023-02-20T10:06:35.972Z] kafka:

[2023-02-20T10:06:35.972Z]   enabled: true

[2023-02-20T10:06:35.972Z]   name: kafka

[2023-02-20T10:06:35.972Z]   replicaCount: 3

[2023-02-20T10:06:35.972Z]   defaultReplicationFactor: 2

[2023-02-20T10:06:35.972Z]   metrics:

[2023-02-20T10:06:35.972Z]     kafka:

[2023-02-20T10:06:35.972Z]       enabled: true

[2023-02-20T10:06:35.972Z]     jmx:

[2023-02-20T10:06:35.972Z]       enabled: true

[2023-02-20T10:06:35.972Z]     serviceMonitor:

[2023-02-20T10:06:35.972Z]       enabled: true

[2023-02-20T10:06:35.972Z] etcd:

[2023-02-20T10:06:35.972Z]   replicaCount: 1

[2023-02-20T10:06:35.972Z]   image:

[2023-02-20T10:06:35.972Z]     repository: milvusdb/etcd

[2023-02-20T10:06:35.972Z]     tag: 3.5.5-r2

[2023-02-20T10:06:35.972Z] minio:

[2023-02-20T10:06:35.972Z]   mode: standalone

[2023-02-20T10:06:35.972Z] pulsar:

[2023-02-20T10:06:35.972Z]   enabled: false

[2023-02-20T10:06:35.972Z] standalone:

[2023-02-20T10:06:35.972Z]   messageQueue: kafka
```

**Comment by zhuwenxing** [comment]
/assign @LoveEachDay 
please take a look

**Comment by LoveEachDay** [comment]
@zhuwenxing From the kafka broker controller (id=1) log:
```
[2023-02-20 10:08:41,774] WARN [RequestSendThread controllerId=1] Controller 1's connection to broker kafka-standalone-reinstall-385-2.kafka-standalone-reinstall-385-headless.chaos-testing.svc.cluster.local:9093 (id: 2 rack: null) was unsuccessful (kafka.controller.RequestSendThread)
java.io.IOException: Connection to kafka-standalone-reinstall-385-2.kafka-standalone-reinstall-385-headless.chaos-testing.svc.cluster.local:9093 (id: 2 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:70)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:291)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:245)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2023-02-20 10:08:41,774] INFO [Controller id=1, targetBrokerId=2] Client requested connection close from node 2 (org.apache.kafka.clients.NetworkClient)
[2023-02-20 10:08:41,876] INFO [RequestSendThread controllerId=1] Controller 1 connected to kafka-standalone-reinstall-385-2.kafka-standalone-reinstall-385-headless.chaos-testing.svc.cluster.local:9093 (id: 2 rack: null) for sending state change requests (kafka.controller.RequestSendThread)
[2023-02-20 10:08:42,377] INFO [Controller id=1] New topics: [Set(by-dev-datacoord-timetick-channel)], deleted topics: [Set()], new partition replica assignment [Set(TopicIdReplicaAssignment(by-dev-datacoord-timetick-channel,Some(YHufZ9aTTWurjXqRcMNzeQ),Map(by-dev-datacoord-timetick-channel-0 -> ReplicaAssignment(replicas=1,2, addingReplicas=, removingReplicas=))))] (kafka.controller.KafkaController)
```
The kafka cluster became to ready at 10:08:41, while the tests ran at 10:08:40. And the default health probe only checks whether the port is ready. We'd better make sure that the kafka cluster is ready before we run any tests.

/unassign
/assign @zhuwenxing

**Comment by zhuwenxing** [comment]
Need to add a script to make sure the Kafka cluster is really ready, then run test case.
