### ISSUE TITLE
[Bug]: [benchmark][cluster]Hnsw index concurrent insert report: "getSegmentID failed: SegmentIDAllocator failRemainRequest" 

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#22332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230221-c2c8ddd4
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka): pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.0.dev34
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task: fouramf-stable-1677006000  , id :8 

other_params:
 --milvus_tag_prefix=2.2.0 -s --client_version=2.2.3
case_name
test_concurrent_locust_hnsw_compaction_cluster

server
```
fouramf-stable-1677006000-8-etcd-0                                1/1     Running     0               5m50s   10.104.6.32     4am-node13   <none>           <none>
fouramf-stable-1677006000-8-etcd-1                                1/1     Running     0               5m49s   10.104.1.145    4am-node10   <none>           <none>
fouramf-stable-1677006000-8-etcd-2                                1/1     Running     0               5m49s   10.104.4.95     4am-node11   <none>           <none>
fouramf-stable-1677006000-8-milvus-datacoord-5dd49f7cfb-gpjjd     1/1     Running     1 (110s ago)    5m52s   10.104.9.142    4am-node14   <none>           <none>
fouramf-stable-1677006000-8-milvus-datanode-75b7cf575b-mtcft      1/1     Running     1 (111s ago)    5m52s   10.104.4.74     4am-node11   <none>           <none>
fouramf-stable-1677006000-8-milvus-indexcoord-cccf8b8cd-ksvnt     1/1     Running     1 (110s ago)    5m51s   10.104.1.131    4am-node10   <none>           <none>
fouramf-stable-1677006000-8-milvus-indexnode-6d476b4c5-8xgf5      1/1     Running     0               5m51s   10.104.5.8      4am-node12   <none>           <none>
fouramf-stable-1677006000-8-milvus-proxy-76bfd75b68-9rmv2         1/1     Running     1 (111s ago)    5m52s   10.104.4.73     4am-node11   <none>           <none>
fouramf-stable-1677006000-8-milvus-querycoord-5754c6d77c-cggzk    1/1     Running     1 (110s ago)    5m52s   10.104.4.76     4am-node11   <none>           <none>
fouramf-stable-1677006000-8-milvus-querynode-5b77d47c57-vpltm     1/1     Running     0               5m52s   10.104.9.143    4am-node14   <none>           <none>
fouramf-stable-1677006000-8-milvus-rootcoord-6c78ddf655-2cf4l     1/1     Running     1 (110s ago)    5m51s   10.104.6.251    4am-node13   <none>           <none>
fouramf-stable-1677006000-8-minio-0                               1/1     Running     0               5m51s   10.104.1.140    4am-node10   <none>           <none>
fouramf-stable-1677006000-8-minio-1                               1/1     Running     0               5m50s   10.104.6.30     4am-node13   <none>           <none>
fouramf-stable-1677006000-8-minio-2                               1/1     Running     0               5m50s   10.104.9.170    4am-node14   <none>           <none>
fouramf-stable-1677006000-8-minio-3                               1/1     Running     0               5m49s   10.104.4.93     4am-node11   <none>           <none>
fouramf-stable-1677006000-8-pulsar-bookie-0                       1/1     Running     0               5m51s   10.104.6.31     4am-node13   <none>           <none>
fouramf-stable-1677006000-8-pulsar-bookie-1                       1/1     Running     0               5m50s   10.104.1.144    4am-node10   <none>           <none>
fouramf-stable-1677006000-8-pulsar-bookie-2                       1/1     Running     0               5m49s   10.104.9.173    4am-node14   <none>           <none>
fouramf-stable-1677006000-8-pulsar-bookie-init-bq5xz              0/1     Completed   0               5m52s   10.104.1.128    4am-node10   <none>           <none>
fouramf-stable-1677006000-8-pulsar-broker-0                       1/1     Running     0               5m51s   10.104.1.130    4am-node10   <none>           <none>
fouramf-stable-1677006000-8-pulsar-proxy-0                        1/1     Running     0               5m51s   10.104.6.250    4am-node13   <none>           <none>
fouramf-stable-1677006000-8-pulsar-pulsar-init-hmp8s              0/1     Completed   0               5m52s   10.104.1.129    4am-node10   <none>           <none>
fouramf-stable-1677006000-8-pulsar-recovery-0                     1/1     Running     0               5m50s   10.104.1.132    4am-node10   <none>           <none>
fouramf-stable-1677006000-8-pulsar-zookeeper-0                    1/1     Running     0               5m51s   10.104.6.28     4am-node13   <none>           <none>
fouramf-stable-1677006000-8-pulsar-zookeeper-1                    1/1     Running     0               4m19s   10.104.9.187    4am-node14   <none>           <none>
fouramf-stable-1677006000-8-pulsar-zookeeper-2                    1/1     Running     0               3m7s    10.104.1.156    4am-node10   <none>           <none> (cli_client.py:130)
```

client error log:
![image](https://user-images.githubusercontent.com/48523564/220518648-9b38f951-ce9a-432f-83e6-2d41ce16550b.png)

grafana:
![image](https://user-images.githubusercontent.com/48523564/220518730-cd599fb5-9f3d-4522-a917-a9f6be5d5b27.png)

### Steps To Reproduce

```markdown
1. create a collection or use an existing collection
        2. build index on vector column
        3. insert a certain number of vectors
        4. flush collection
        5. build index on vector column with the same parameters
        6. build index on on scalars column or not
        7. count the total number of rows
        8. load collection
        9. perform concurrent operations
        10. clean all collections or not
```

### Anything else?

   test_concurrent_locust_hnsw_compaction_cluster:
 ```
    @pytest.mark.locust
    @pytest.mark.parametrize("deploy_mode", [CLUSTER])
    def test_concurrent_locust_hnsw_compaction_cluster(self, input_params: InputParamsBase, deploy_mode):
        """
        :test steps:
            1. concurrent test and calculation of RT and QPS
        """
        concurrent_tasks = [ConcurrentParams.params_search(weight=20, nq=10, top_k=10, search_param={"ef": 16},
                                                           expr=eval("{'float_1': {'GT': -1.0, 'LT': 100000 * 0.5}}")),
                            ConcurrentParams.params_query(weight=10, ids=[i for i in range(10)]),
                            ConcurrentParams.params_load(weight=1),
                            ConcurrentParams.params_scene_insert_delete_flush(weight=1, insert_length=1,
                                                                              delete_length=1, random_id=True,
                                                                              random_vector=True, varchar_filled=True)]
        default_case_params = ConcurrentParams().params_scene_concurrent(concurrent_tasks, concurrent_number=[20],
                                                                         during_time="5h", interval=20,
                                                                         dataset_size="10w", other_fields=["float_1"],
                                                                         **cdp.DefaultIndexParams.HNSW)
        self.concurrency_template(input_params=input_params, cpu=dp.default_cpu, mem=dp.default_mem,
                                  deploy_mode=deploy_mode, old_version_format=False, sync_report=True,
                                  case_callable_obj=ConcurrentClientBase().scene_concurrent_locust,
                                  default_case_params=default_case_params)

```

**Comment by xiaofan-luan** [comment]
/assign @czs007 
could you pls help on it?

**Comment by ThreadDao** [comment]
I had the same issue on the master branch `master-20230221-c3e8ad36`. If you need related case and logs, see the following:

test steps:
1. deploy cluster with the operator config
```
({'spec': {'components': {'queryNode': {'resources': {'limits': {'cpu': 1, 'memory': '2560Mi'}, 'requests': {'cpu': '1.0', 'memory': '2Gi'}}, 'replicas': 4}, 'indexNode': {'resources': {'limits': {'cpu': 2, 'memory': '4Gi'}, 'requests': {'cpu': '100m', 'memory': '128Mi'}}}, 'dataNode': {'resources': {'limits': {'cpu': '1.0', 'memory': '2Gi'}, 'requests': {'cpu': '1.0', 'memory': '2Gi'}}}, 'image': 'harbor.milvus.io/milvus/milvus:master-20230221-c3e8ad36'}, 'mode': 'cluster', 'dependencies': {'etcd': {'inCluster': {'deletionPolicy': 'Delete', 'pvcDeletion': True, 'values': {'global': {'storageClass': 'local-path'}, 'metrics': {'enabled': True, 'podMonitor': {'enabled': True}}}}}, 'pulsar': {'inCluster': {'deletionPolicy': 'Delete', 'pvcDeletion': True, 'values': {'bookkeeper': {'volumes': {'journal': {'storageClassName': 'local-path'}, 'ledgers': {'storageClassName': 'local-path'}}}, 'zookeeper': {'volumes': {'data': {'storageClassName': 'local-path'}}}}}}, 'storage': {'inCluster': {'deletionPolicy': 'Delete', 'pvcDeletion': True, 'values': {'persistence': {'storageClass': 'local-path'}, 'metrics': {'serviceMonitor': {'enabled': False}}}}}, 'kafka': {'inCluster': {'values': {'persistence': {'storageClass': 'local-path'}}}}}}, 'apiVersion': 'milvus.io/v1beta1', 'kind': 'Milvus', 'metadata': {'name': 'fouram-op-60-1637'}}, 'cluster_1c2m', {'spec': {'components': {'queryNode': {'resources': {'limits': {'cpu': 1, 'memory': '2560Mi'}, 'requests': {'cpu': '1.0', 'memory': '2Gi'}}, 'replicas': 4}, 'indexNode': {'resources': {'limits': {'cpu': 2, 'memory': '4Gi'}, 'requests': {'cpu': '100m', 'memory': '128Mi'}}}, 'dataNode': {'resources': {'limits': {'cpu': '1.0', 'memory': '2Gi'}, 'requests': {'cpu': '1.0', 'memory': '2Gi'}}}, 'image': 'harbor.milvus.io/milvus/milvus:master-20230221-c3e8ad36'}, 'mode': 'cluster', 'dependencies': {'etcd': {'inCluster': {'deletionPolicy': 'Delete', 'pvcDeletion': True, 'values': {'global': {'storageClass': 'local-path'}, 'metrics': {'enabled': True, 'podMonitor': {'enabled': True}}}}}, 'pulsar': {'inCluster': {'deletionPolicy': 'Delete', 'pvcDeletion': True, 'values': {'bookkeeper': {'volumes': {'journal': {'storageClassName': 'local-path'}, 'ledgers': {'storageClassName': 'local-path'}}}, 'zookeeper': {'volumes': {'data': {'storageClassName': 'local-path'}}}}}}, 'storage': {'inCluster': {'deletionPolicy': 'Delete', 'pvcDeletion': True, 'values': {'persistence': {'storageClass': 'local-path'}, 'metrics': {'serviceMonitor': {'enabled': False}}}}}, 'kafka': {'inCluster': {'values': {'persistence': {'storageClass': 'local-path'}}}}}}, 'apiVersion': 'milvus.io/v1beta1', 'kind': 'Milvus', 'metadata': {'name': 'fouram-op-60-1637'}}) (base.py:106)
```
2. Create rg `RG_0` and transfer 2 nodes from default_rg, create rg `RG_1` and transfer 2 nodes from default_rg
3. Create a collection with schema
```
{'auto_id': False, 'description': '', 'fields': [{'name': 'id', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float_vector', 'description': '', 'type': <DataType.FLOAT_VECTOR: 101>, 'params': {'dim': 128}}, {'name': 'int64_1', 'description': '', 'type': <DataType.INT64: 5>}, {'name': 'int64_2', 'description': '', 'type': <DataType.INT64: 5>}, {'name': 'float_1', 'description': '', 'type': <DataType.FLOAT: 10>}, {'name': 'double_1', 'description': '', 'type': <DataType.DOUBLE: 11>}, {'name': 'varchar_1', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}]} (base.py:125)
```
4. Create index
```
params:{'index_type': 'IVF_FLAT', 'metric_type': 'L2', 'params': {'nlist': 512}}
```
5. Start to insert 2m-128d entities, and error returned
```
[2023-02-22 07:00:25,671 -  INFO - fouram]: [Base] Start inserting, ids: 1900000 - 1949999, data size: 2,000,000 (base.py:140)
[2023-02-22 07:00:36,458 - ERROR - fouram]: RPC error: [batch_insert], <MilvusException: (code=1, message=getSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error)>, <Time:{'RPC start': '2023-02-22 07:00:25.712536', 'RPC error': '2023-02-22 07:00:36.458520'}> (decorators.py:108)
[2023-02-22 07:00:36,460 - ERROR - fouram]: Traceback (most recent call last):
  File "/src/fouram/client/util/api_request.py", line 33, in inner_wrapper
    res = func(*args, **kwargs)
  File "/src/fouram/client/util/api_request.py", line 70, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 430, in insert
    res = conn.batch_insert(self._name, entities, partition_name,
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 399, in batch_insert
    raise err
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 395, in batch_insert
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=getSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error)>
 (api_request.py:48)
[2023-02-22 07:00:36,460 - ERROR - fouram]: (api_response) : <MilvusException: (code=1, message=getSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error)> (api_request.py:49)
```

**pod logs:** 
devops cluster, chaos-testing namespace, argo workflow `fouram-scale-6cktv`
```
fouram-scale-6cktv-op-77-7063-milvus-datacoord-7cf8d5d48d-lj8hx     Running     0            2m      10.102.5.193     devops-node21     
fouram-scale-6cktv-op-77-7063-milvus-datanode-79bbfd754f-2xxhm      Running     0            2m      10.102.10.89     devops-node20     
fouram-scale-6cktv-op-77-7063-milvus-indexcoord-f96bf6444-52dpb     Running     0            2m      10.102.5.190     devops-node21     
fouram-scale-6cktv-op-77-7063-milvus-indexnode-7579797777-bbjks     Running     0            2m      10.102.5.195     devops-node21     
fouram-scale-6cktv-op-77-7063-milvus-proxy-754b89fbc5-jbmp7         Running     0            2m      10.102.5.191     devops-node21     
fouram-scale-6cktv-op-77-7063-milvus-querycoord-5c88796988v4cqs     Running     0            2m      10.102.9.107     devops-node13     
fouram-scale-6cktv-op-77-7063-milvus-querynode-5f9cdf9b79-7mn6f     Running     0            2m      10.102.7.169     devops-node11     
fouram-scale-6cktv-op-77-7063-milvus-querynode-5f9cdf9b79-82rj5     Running     0            2m      10.102.5.194     devops-node21     
fouram-scale-6cktv-op-77-7063-milvus-querynode-5f9cdf9b79-f5dcn     Running     0            2m      10.102.9.106     devops-node13     
fouram-scale-6cktv-op-77-7063-milvus-querynode-5f9cdf9b79-hvfjt     Running     0            2m      10.102.6.54      devops-node10     
fouram-scale-6cktv-op-77-7063-milvus-rootcoord-9bd4d5bd4-4q59z      Running     0            2m      10.102.5.192     devops-node21    
```

**Comment by elstic** [comment]
@czs007 Please pay attention to this issue, which still exists.
case_name:test_concurrent_locust_hnsw_dml_dql_filter_cluster
server:
```
fouramf-stable-test-1677535200-4-etcd-0                           1/1     Running             0                  25m     10.104.6.214    4am-node13   <none>           <none>
fouramf-stable-test-1677535200-4-etcd-1                           1/1     Running             0                  25m     10.104.5.51     4am-node12   <none>           <none>
fouramf-stable-test-1677535200-4-etcd-2                           1/1     Running             0                  25m     10.104.4.159    4am-node11   <none>           <none>
fouramf-stable-test-1677535200-4-milvus-datacoord-7bc7d588q58px   1/1     Running             1 (21m ago)        25m     10.104.4.151    4am-node11   <none>           <none>
fouramf-stable-test-1677535200-4-milvus-datanode-5ccb65dc5gnfmb   1/1     Running             1 (21m ago)        25m     10.104.9.104    4am-node14   <none>           <none>
fouramf-stable-test-1677535200-4-milvus-indexcoord-685f8f6qvz5g   1/1     Running             1 (21m ago)        25m     10.104.6.189    4am-node13   <none>           <none>
fouramf-stable-test-1677535200-4-milvus-indexnode-5b887887wcmpc   1/1     Running             0                  25m     10.104.1.186    4am-node10   <none>           <none>
fouramf-stable-test-1677535200-4-milvus-proxy-b85b46f74-966n4     1/1     Running             1 (21m ago)        25m     10.104.4.154    4am-node11   <none>           <none>
fouramf-stable-test-1677535200-4-milvus-querycoord-7546f9cjh988   1/1     Running             1 (21m ago)        25m     10.104.6.188    4am-node13   <none>           <none>
fouramf-stable-test-1677535200-4-milvus-querynode-778448b7f22cm   1/1     Running             0                  25m     10.104.1.171    4am-node10   <none>           <none>
fouramf-stable-test-1677535200-4-milvus-rootcoord-8595dbc8mxtsc   1/1     Running             1 (21m ago)        25m     10.104.1.169    4am-node10   <none>           <none>
fouramf-stable-test-1677535200-4-minio-0                          1/1     Running             0                  25m     10.104.6.212    4am-node13   <none>           <none>
fouramf-stable-test-1677535200-4-minio-1                          1/1     Running             0                  25m     10.104.1.183    4am-node10   <none>           <none>
fouramf-stable-test-1677535200-4-minio-2                          1/1     Running             0                  25m     10.104.4.162    4am-node11   <none>           <none>
fouramf-stable-test-1677535200-4-minio-3                          1/1     Running             0                  25m     10.104.9.116    4am-node14   <none>           <none>
fouramf-stable-test-1677535200-4-pulsar-bookie-0                  1/1     Running             0                  25m     10.104.5.54     4am-node12   <none>           <none>
fouramf-stable-test-1677535200-4-pulsar-bookie-1                  1/1     Running             0                  25m     10.104.6.220    4am-node13   <none>           <none>
fouramf-stable-test-1677535200-4-pulsar-bookie-2                  1/1     Running             0                  25m     10.104.4.164    4am-node11   <none>           <none>
fouramf-stable-test-1677535200-4-pulsar-bookie-init-z7xhr         0/1     Completed           0                  25m     10.104.4.149    4am-node11   <none>           <none>
fouramf-stable-test-1677535200-4-pulsar-broker-0                  1/1     Running             0                  25m     10.104.4.152    4am-node11   <none>           <none>
fouramf-stable-test-1677535200-4-pulsar-proxy-0                   1/1     Running             0                  25m     10.104.4.153    4am-node11   <none>           <none>
fouramf-stable-test-1677535200-4-pulsar-pulsar-init-w25j6         0/1     Completed           0                  25m     10.104.4.150    4am-node11   <none>           <none>
fouramf-stable-test-1677535200-4-pulsar-recovery-0                1/1     Running             0                  25m     10.104.5.49     4am-node12   <none>           <none>
fouramf-stable-test-1677535200-4-pulsar-zookeeper-0               1/1     Running             0                  25m     10.104.6.213    4am-node13   <none>           <none>
fouramf-stable-test-1677535200-4-pulsar-zookeeper-1               1/1     Running             0                  24m     10.104.1.185    4am-node10   <none>           <none>
fouramf-stable-test-1677535200-4-pulsar-zookeeper-2               1/1     Running             0                  23m     10.104.5.59     4am-node12   <none>           <none> 
```
client log:
![image](https://user-images.githubusercontent.com/48523564/221752814-87fffa31-faaf-49bf-b12c-66abaf3277ae.png)
grafana:
![image](https://user-images.githubusercontent.com/48523564/221752901-f1d89a06-aedf-4563-9a4e-2b89ceebca31.png)

**Comment by elstic** [comment]
After verification, this issue did not occur
