### ISSUE TITLE
 [Bug]: [benchmark][standalone]Milvus create hsnw index after，then search with gist 1million 768d raise an error

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#22343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230220-faf62cfa
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.0.dev34
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

test_concurrent_locust_custom_parameters：

deploy_config：
fouramf-server-standalone-8c16m
case_params：
fouramf-client-gist1m-concurrent-hnsw

server：
```
NAME                                                              READY   STATUS             RESTARTS        AGE     IP             NODE         NOMINATED NODE   READINESS GATES
fouramf-concurrent-search-md224-2-4-7515-etcd-0                   1/1     Running            0               4h15m   10.104.5.82    4am-node12   <none>           <none>
fouramf-concurrent-search-md224-2-4-7515-milvus-standalonemwkqb   1/1     Running            1 (3h59m ago)   4h15m   10.104.4.111   4am-node11   <none>           <none>
fouramf-concurrent-search-md224-2-4-7515-minio-58c57f96fc-d4lvj   1/1     Running            0               4h15m   10.104.5.79    4am-node12   <none>           <none> (cli_client.py:130
```

client log：

```
[2023-02-20 11:39:22,091 -  INFO - fouram]:  Type     Name                                                                                  50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100% # reqs (stats.py:740)
[2023-02-20 11:39:22,091 -  INFO - fouram]: --------|--------------------------------------------------------------------------------|---------|------|------|------|------|------|------|------|------|------|------|------| (stats.py:750)
[2023-02-20 11:39:22,091 -  INFO - fouram]:  grpc     search                                                                                 21     21     22     22     23    210    600   1200   1800   1800   1800    801 (stats.py:754)
[2023-02-20 11:39:22,091 -  INFO - fouram]: --------|--------------------------------------------------------------------------------|---------|------|------|------|------|------|------|------|------|------|------|------| (stats.py:755)
[2023-02-20 11:39:22,091 -  INFO - fouram]:  None     Aggregated                                                                             21     21     22     22     23    210    600   1200   1800   1800   1800    801 (stats.py:758)
[2023-02-20 11:39:22,092 -  INFO - fouram]:  (stats.py:759)
[2023-02-20 11:39:22,851 - ERROR - fouram]: RPC error: [search], <MilvusUnavailableException: (code=1, message=server Unavailable: Retry timeout: 60s)>, <Time:{'RPC start': '2023-02-20 11:37:49.079975', 'RPC error': '2023-02-20 11:39:22.851142'}> (decorators.py:108)
[2023-02-20 11:39:22,852 - ERROR - fouram]: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 472, in search
    return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 441, in _execute_search_requests
    raise pre_err
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 429, in _execute_search_requests
    response = self._stub.Search(request, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1676893162.850818922","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3260,"referenced_errors":[{"created":"@1676893162.850817859","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":167,"grpc_status":14}]}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/src/fouram/client/util/api_request.py", line 33, in inner_wrapper
    res = func(*args, **kwargs)
  File "/src/fouram/client/util/api_request.py", line 70, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 614, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 66, in handler
    raise MilvusUnavailableException(message=f"server Unavailable: {timeout_msg}") from e
pymilvus.exceptions.MilvusUnavailableException: <MilvusUnavailableException: (code=1, message=server Unavailable: Retry timeout: 60s)>
 (api_request.py:48)
[2023-02-20 11:39:22,853 - ERROR - fouram]: (api_response) : <MilvusUnavailableException: (code=1, message=server Unavailable: Retry timeout: 60s)> (api_request.py:49)
[2023-02-20 11:39:22,853 - ERROR - fouram]: [CheckFunc] search request check failed, response:<MilvusUnavailableException: (code=1, message=server Unavailable: Retry timeout: 60s)> (func_check.py:42)
[2023-02-20 11:39:22,986 - WARNING - fouram]: [93m[search] retry:4, cost: 0.27s, reason: <_InactiveRpcError: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (decorators.py:71)
[2023-02-20 11:39:23,258 - WARNING - fouram]: [93m[search] retry:5, cost: 0.81s, reason: <_InactiveRpcError: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (decorators.py:71)
[2023-02-20 11:39:24,070 - WARNING - fouram]: [93m[search] retry:6, cost: 2.43s, reason: <_InactiveRpcError: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (decorators.py:71)
[2023-02-20 11:39:26,503 - WARNING - fouram]: [93m[search] retry:7, cost: 7.29s, reason: <_InactiveRpcError: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (decorators.py:71)
[2023-02-20 11:39:33,797 - WARNING - fouram]: [93m[search] retry:8, cost: 21.87s, reason: <_InactiveRpcError: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (decorators.py:71)
```

### Steps To Reproduce

```markdown
1. create a collection 
        2. build hnsw index on vector column
        3. insert a 1m of vectors
        4. flush collection
        5. build index on vector column with the same parameters
        6. count the total number of rows
        7. load collection
        8. perform concurrent operations
        9. clean all collections or not
```

### Anything else?

```
'client': {'test_case_type': 'ConcurrentClientBase',
            'test_case_name': 'test_concurrent_locust_custom_parameters',
            'test_case_params': {'dataset_params': {'dim': 768,
                                                    'dataset_name': 'gist',
                                                    'dataset_size': '1m',
                                                    'ni_per': 1000,
                                                    'metric_type': 'L2'},
                                 'collection_params': {'other_fields': []},
                                 'load_params': {},
                                 'search_params': {},
                                 'index_params': {'index_type': 'HNSW',
                                                  'index_param': {'M': 8,
                                                                  'efConstruction': 200}},
                                 'concurrent_params': {'concurrent_number': 100,
                                                       'during_time': 3600,
                                                       'interval': 20,
                                                       'spawn_rate': None},
                                 'concurrent_tasks': [{'type': 'search',
                                                       'weight': 1,
                                                       'params': {'nq': 1,
                                                                  'top_k': 1,
                                                                  'search_param': {'ef': 16},
                                                                  'random_data': True}}]},
```

**Comment by yanliang567** [comment]
@jingkl it looks like an occasional timeout, which occurs only once.

**Comment by yanliang567** [comment]
please keep an eye on it, lets see what happens recently

**Comment by yanliang567** [comment]
@jingkl does it reproduce recenlty?

**Comment by elstic** [comment]
> @jingkl does it reproduce recenlty?

After verification, this issue did not occur

**Comment by elstic** [comment]
> > @jingkl does it reproduce recenlty?
> 
> @yanliang567 After verification, this issue did not occur
