### ISSUE TITLE
[Bug]: [benchmark][standalone] Milvus recall test with search error in glove  200dim dataset

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#22345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230221-99bf1727
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.0dev34
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

testcase:test_recall_glove_hnsw_standalone
server:

```
NAME                                                              READY   STATUS      RESTARTS         AGE     IP              NODE         NOMINATED NODE   READINESS GATES
fouramf-cron-1676908800-1-67-9552-etcd-0                          1/1     Running     0                48m     10.104.9.179    4am-node14   <none>           <none>
fouramf-cron-1676908800-1-67-9552-milvus-standalone-6d6cffhwz68   1/1     Running     0                48m     10.104.4.99     4am-node11   <none>           <none>
fouramf-cron-1676908800-1-67-9552-minio-75784464f8-l9mtv          1/1     Running     0                48m     10.104.4.100    4am-node11   <none>           <none>
```

client log:

```
2023-02-21 04:37:52,793 -  INFO - fouram]: [Base] Params of search: nq:10000, anns_field:float_vector, param:{'metric_type': 'IP', 'params': {'ef': 10}}, limit:10, expr:"None", kwargs:{} (base.py:317)
[2023-02-21 04:42:53,061 - ERROR - fouram]: RPC error: [search], <MilvusException: (code=1, message=<_InactiveRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1676954573.060420354","description":"Error received from peer ipv4:10.255.66.22:19530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>)>, <Time:{'RPC start': '2023-02-21 04:37:52.794737', 'RPC error': '2023-02-21 04:42:53.061128'}> (decorators.py:108)
[2023-02-21 04:42:53,062 - ERROR - fouram]: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 472, in search
    return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 441, in _execute_search_requests
    raise pre_err
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 429, in _execute_search_requests
    response = self._stub.Search(request, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1676954573.060420354","description":"Error received from peer ipv4:10.255.66.22:19530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/src/fouram/client/util/api_request.py", line 33, in inner_wrapper
    res = func(*args, **kwargs)
  File "/src/fouram/client/util/api_request.py", line 70, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 614, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 58, in handler
    raise MilvusException(message=str(e)) from e
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=<_InactiveRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1676954573.060420354","description":"Error received from peer ipv4:10.255.66.22:19530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>)>
 (api_request.py:48)
[2023-02-21 04:42:53,063 - ERROR - fouram]: (api_response) : <MilvusException: (code=1, message=<_InactiveRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1676954573.060420354","description":"Error received from peer ipv4:10.255.66.22:19530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>)> (api_request.py:49)
[2023-02-21 04:42:53,063 - ERROR - fouram]: [CheckFunc] search request check failed, response:<MilvusException: (code=1, message=<_InactiveRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1676954573.060420354","description":"Error received from peer ipv4:10.255.66.22:19530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>)> (func_check.py:48)
[2023-02-21 04:42:53,063 - ERROR - fouram]: [AccCases] Search raise error:  (accuracy_cases.py:192)
```

### Steps To Reproduce

```markdown
1. create a collection 
        2. insert glove-200 dataset
        3. flush collection
        4. clean index and build new index
        5. load collection
        6. search with different parameters
        7. clean all collections or not
```

### Anything else?

```
{'server': {'deploy_tool': 'helm',
            'deploy_mode': 'standalone',
            'config_name': 'standalone_8c16m',
            'config': {'standalone': {'resources': {'limits': {'cpu': '8.0',
                                                               'memory': '16Gi'},
                                                    'requests': {'cpu': '5.0',
                                                                 'memory': '9Gi'}},
                                      'persistence': {'persistentVolumeClaim': {'storageClass': 'local-path'}}},
                       'cluster': {'enabled': False},
                       'etcd': {'replicaCount': 1,
                                'global': {'storageClass': 'local-path'},
                                'metrics': {'enabled': True,
                                            'podMonitor': {'enabled': True}}},
                       'minio': {'mode': 'standalone',
                                 'persistence': {'storageClass': 'local-path'},
                                 'metrics': {'serviceMonitor': {'enabled': False}}},
                       'pulsar': {'enabled': False},
                       'metrics': {'serviceMonitor': {'enabled': True}},
                       'image': {'all': {'repository': 'harbor.milvus.io/dockerhub/milvusdb/milvus',
                                         'tag': '2.2.0-20230221-99bf1727'}}},
            'host': 'fouramf-cron-1676908800-1-67-9552-milvus.qa-milvus.svc.cluster.local'},
 'client': {'test_case_type': 'AccCases',
            'test_case_name': 'test_recall_glove_hnsw_standalone',
            'test_case_params': {'dataset_params': {'dim': 200,
                                                    'dataset_name': 'glove-200-angular',
                                                    'ni_per': 10000},
                                 'collection_params': {'other_fields': []},
                                 'load_params': {'replica_number': 1},
                                 'search_params': {'top_k': 10,
                                                   'nq': 10000,
                                                   'search_param': {'ef': 256},
                                                   'expr': None},
                                 'index_params': {'index_type': 'HNSW',
                                                  'index_param': {'M': 36,
                                                                  'efConstruction': 500}}},
            'run_id': 20230220,
            'datetime': '2023-02-21 04:31:56.120773',
            'client_version': '2.2.3'}
```

**Comment by congqixia** [comment]
![image](https://user-images.githubusercontent.com/84113973/220607839-f90c97e7-2278-4d41-95d2-a6f0f0698145.png)
In brief, search failed due to brute force search on growing segments (nq = 10000)
BTW, what's the timeout setting for this search case? @jingkl

**Comment by xiaofan-luan** [comment]
@congqixia this might be related to performance regression of Knowhere 2.0
@liliu-z is working on this

**Comment by congqixia** [comment]
> @congqixia this might be related to performance regression of Knowhere 2.0
> @liliu-z is working on this

Ok. 
Any metrics to confirm? @liliu-z

**Comment by congqixia** [comment]
@xiaofan-luan 
Quick update: after offline conversation with @liliu-z , the known issue of performance is related to IVFSQ index. This case builds HNSW index and the timeout failure happened during the period in which querynode loads growing segments.
It might be caused by regression of brute force segment or "handoff" (implemented by target updates) happened too slowly. Will check on that.

**Comment by congqixia** [comment]
@ThreadDao could you please check whether patch fixes this issue?
/assign @ThreadDao

**Comment by jingkl** [comment]
image：2.2.0-20230327-ec19edfb
pymilvus；2.3.0dev48
This problem is no longer present, close issue
