### ISSUE TITLE
[Bug]: Loading collection timeout after pulsar pod failure chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#22360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230222-7e19a924
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus==2.3.0.dev38
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2023-02-22T21:47:08.317Z] [2023-02-22 21:44:54 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:56)

[2023-02-22T21:47:08.317Z] [2023-02-22 21:46:54 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=wait for loading collection timeout, collection: DeleteChecker__hp9wYVrI)>, <Time:{'RPC start': '2023-02-22 21:44:54.209882', 'RPC error': '2023-02-22 21:46:54.554081'}> (decorators.py:108)

[2023-02-22T21:47:08.317Z] [2023-02-22 21:46:54 - WARNING - pymilvus.decorators]: Retry timeout: 120s (decorators.py:79)

[2023-02-22T21:47:08.317Z] [2023-02-22 21:46:54 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: DeleteChecker__hp9wYVrI)>, <Time:{'RPC start': '2023-02-22 21:44:54.204905', 'RPC error': '2023-02-22 21:46:54.554920'}> (decorators.py:108)

[2023-02-22T21:47:08.317Z] [2023-02-22 21:46:54 - ERROR - ci_test]: Traceback (most recent call last):

[2023-02-22T21:47:08.317Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-02-22T21:47:08.317Z]     return func(self, *args, **kwargs)

[2023-02-22T21:47:08.317Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 675, in load_collection

[2023-02-22T21:47:08.317Z]     self.wait_for_loading_collection(collection_name, timeout)

[2023-02-22T21:47:08.317Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-02-22T21:47:08.317Z]     raise e

[2023-02-22T21:47:08.317Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-02-22T21:47:08.317Z]     return func(*args, **kwargs)

[2023-02-22T21:47:08.317Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-02-22T21:47:08.317Z]     ret = func(self, *args, **kwargs)

[2023-02-22T21:47:08.317Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-02-22T21:47:08.317Z]     raise e

[2023-02-22T21:47:08.317Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-02-22T21:47:08.317Z]     return func(self, *args, **kwargs)

[2023-02-22T21:47:08.317Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 697, in wait_for_loading_collection

[2023-02-22T21:47:08.317Z]     raise MilvusException(message=f"wait for loading collection timeout, collection: {collection_name}")

[2023-02-22T21:47:08.317Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=wait for loading collection timeout, collection: DeleteChecker__hp9wYVrI)>

[2023-02-22T21:47:08.317Z] 

[2023-02-22T21:47:08.317Z] The above exception was the direct cause of the following exception:

[2023-02-22T21:47:08.317Z] 

[2023-02-22T21:47:08.317Z] Traceback (most recent call last):

[2023-02-22T21:47:08.317Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2023-02-22T21:47:08.317Z]     res = func(*args, **_kwargs)

[2023-02-22T21:47:08.317Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2023-02-22T21:47:08.317Z]     return func(*arg, **kwargs)

[2023-02-22T21:47:08.317Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 366, in load

[2023-02-22T21:47:08.317Z]     conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)

[2023-02-22T21:47:08.317Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-02-22T21:47:08.317Z]     raise e

[2023-02-22T21:47:08.317Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-02-22T21:47:08.317Z]     return func(*args, **kwargs)

[2023-02-22T21:47:08.317Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-02-22T21:47:08.317Z]     ret = func(self, *args, **kwargs)

[2023-02-22T21:47:08.317Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 80, in handler

[2023-02-22T21:47:08.317Z]     raise MilvusException(e.code, f"{timeout_msg}, message={e.message}") from e

[2023-02-22T21:47:08.317Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: DeleteChecker__hp9wYVrI)>

[2023-02-22T21:47:08.317Z]  (api_request.py:39)

[2023-02-22T21:47:08.317Z] [2023-02-22 21:46:54 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: DeleteChecker__hp9wYVrI)> (api_request.py:40)

[2023-02-22T21:47:08.317Z] ------------- generated html file: file:///tmp/ci_logs/report.html -------------

[2023-02-22T21:47:08.317Z] =========================== short test summary info ============================

[2023-02-22T21:47:08.317Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[DeleteChecker__hp9wYVrI] - AssertionError

[2023-02-22T21:47:08.317Z] =================== 1 failed, 11 passed in 203.64s (0:03:23) ===================
```

### Milvus Log

chaos type: pod-failure image tag: master-20230222-7e19a924 target pod: pulsar
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/2235/pipeline/288
log:
[artifacts-pulsar-pod-failure-2235-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/10810787/artifacts-pulsar-pod-failure-2235-server-logs.1.tar.gz)

[artifacts-pulsar-pod-failure-2235-pytest-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/10810788/artifacts-pulsar-pod-failure-2235-pytest-logs.1.tar.gz)

**Comment by yah01** [comment]
/assign @zhuwenxing 
plz help check with #22429

**Comment by yah01** [comment]
/assign @zhuwenxing 
plz check with #22584

**Comment by zhuwenxing** [comment]
verified and passed with 2.2.0-20230310-b2ece6a5
