### ISSUE TITLE
[Bug]: Load and create index failed with error `find no available querycoord, check querycoord state` after etcd pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#22387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230223-7808bb51
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):kafka    
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus==2.3.0.dev38
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

load failed 
```
[2023-02-23T23:21:16.775Z] [2023-02-23 23:21:16 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)

[2023-02-23T23:21:16.775Z] [2023-02-23 23:21:16 - INFO - ci_test]: [test][2023-02-23T23:21:16Z] [0.00220190s] Hello_Milvus flush -> None (wrapper.py:30)

[2023-02-23T23:21:16.775Z] [2023-02-23 23:21:16 - INFO - ci_test]: assert flush: 3.018524169921875, entities: 9000 (test_data_persistence.py:46)

[2023-02-23T23:21:16.775Z] [2023-02-23 23:21:16 - INFO - ci_test]: index info: [{'collection': 'Hello_Milvus', 'field': 'float_vector', 'index_name': 'test_BreMAxUS', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}, {'collection': 'Hello_Milvus', 'field': 'varchar', 'index_name': 'test_anlWOT5d', 'index_param': {'index_type': 'Trie'}}] (test_data_persistence.py:65)

[2023-02-23T23:21:16.775Z] [2023-02-23 23:21:16 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:56)

[2023-02-23T23:21:16.775Z] [2023-02-23 23:21:16 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=call query coordinator LoadCollection: err: find no available querycoord, check querycoord state

[2023-02-23T23:21:16.775Z] , /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace

[2023-02-23T23:21:16.775Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:304 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall

[2023-02-23T23:21:16.775Z] /go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/client/client.go:187 github.com/milvus-io/milvus/internal/distributed/querycoord/client.(*Client).LoadCollection

[2023-02-23T23:21:16.775Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task.go:1373 github.com/milvus-io/milvus/internal/proxy.(*loadCollectionTask).Execute

[2023-02-23T23:21:16.775Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:460 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask

[2023-02-23T23:21:16.775Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:489 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop

[2023-02-23T23:21:16.775Z] /usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit

[2023-02-23T23:21:16.775Z] )>, <Time:{'RPC start': '2023-02-23 23:21:16.371454', 'RPC error': '2023-02-23 23:21:16.375059'}> (decorators.py:108)

[2023-02-23T23:21:16.775Z] [2023-02-23 23:21:16 - ERROR - ci_test]: Traceback (most recent call last):

[2023-02-23T23:21:16.775Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2023-02-23T23:21:16.775Z]     res = func(*args, **_kwargs)

[2023-02-23T23:21:16.775Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2023-02-23T23:21:16.775Z]     return func(*arg, **kwargs)

[2023-02-23T23:21:16.775Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 366, in load

[2023-02-23T23:21:16.775Z]     conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)

[2023-02-23T23:21:16.775Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-02-23T23:21:16.775Z]     raise e

[2023-02-23T23:21:16.775Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-02-23T23:21:16.775Z]     return func(*args, **kwargs)

[2023-02-23T23:21:16.775Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-02-23T23:21:16.775Z]     ret = func(self, *args, **kwargs)

[2023-02-23T23:21:16.775Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-02-23T23:21:16.775Z]     raise e

[2023-02-23T23:21:16.775Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-02-23T23:21:16.775Z]     return func(self, *args, **kwargs)

[2023-02-23T23:21:16.775Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 672, in load_collection

[2023-02-23T23:21:16.775Z]     raise MilvusException(response.error_code, response.reason)

[2023-02-23T23:21:16.775Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=call query coordinator LoadCollection: err: find no available querycoord, check querycoord state

[2023-02-23T23:21:16.775Z] , /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace

[2023-02-23T23:21:16.775Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:304 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall

[2023-02-23T23:21:16.775Z] /go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/client/client.go:187 github.com/milvus-io/milvus/internal/distributed/querycoord/client.(*Client).LoadCollection

[2023-02-23T23:21:16.775Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task.go:1373 github.com/milvus-io/milvus/internal/proxy.(*loadCollectionTask).Execute

[2023-02-23T23:21:16.775Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:460 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask

[2023-02-23T23:21:16.775Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:489 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop

[2023-02-23T23:21:16.775Z] /usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit

[2023-02-23T23:21:16.775Z] )>

[2023-02-23T23:21:16.775Z]  (api_request.py:39)

[2023-02-23T23:21:16.775Z] [2023-02-23 23:21:16 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=call query coordinator LoadCollection: err: find no available querycoord, check querycoord state

[2023-02-23T23:21:16.775Z] , /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace

[2023-02-23T23:21:16.775Z] /go/src/github.com/milvus-io/milv...... (api_request.py:40)

[2023-02-23T23:21:16.775Z] ------------- generated html file: file:///tmp/ci_logs/report.html -------------

[2023-02-23T23:21:16.775Z] =========================== short test summary info ============================

[2023-02-23T23:21:16.775Z] FAILED testcases/test_data_persistence.py::TestDataPersistence::test_milvus_default - AssertionError

[2023-02-23T23:21:16.775Z] ============================== 1 failed in 4.34s ===============================
```

create index failed
```

[2023-02-23T23:21:16.798Z] [2023-02-23 23:21:16 - INFO - ci_test]: [test][2023-02-23T23:21:16Z] [0.00295235s] e2e__gTeyWogJ flush -> None (wrapper.py:30)

[2023-02-23T23:21:16.798Z] [2023-02-23 23:21:16 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 120} (api_request.py:56)

[2023-02-23T23:21:16.798Z] [2023-02-23 23:21:16 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)

[2023-02-23T23:21:16.798Z] [2023-02-23 23:21:16 - INFO - ci_test]: [test][2023-02-23T23:21:16Z] [0.00240048s] e2e__gTeyWogJ flush -> None (wrapper.py:30)

[2023-02-23T23:21:16.798Z] [2023-02-23 23:21:16 - INFO - ci_test]: assert flush: 3.020550489425659, entities: 3000 (test_e2e.py:41)

[2023-02-23T23:21:16.798Z] [2023-02-23 23:21:16 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['float_vector', {'index_type': 'IVF_SQ8', 'params': {'nlist': 64}, 'metric_type': 'L2'}], kwargs: {'timeout': 1200, 'index_name': 'test_ELWgyCvi'} (api_request.py:56)

[2023-02-23T23:21:16.798Z] [2023-02-23 23:21:16 - ERROR - pymilvus.decorators]: RPC error: [create_index], <MilvusException: (code=1, message=err: find no available querycoord, check querycoord state

[2023-02-23T23:21:16.798Z] , /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace

[2023-02-23T23:21:16.798Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:304 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall

[2023-02-23T23:21:16.798Z] /go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/client/client.go:168 github.com/milvus-io/milvus/internal/distributed/querycoord/client.(*Client).ShowCollections

[2023-02-23T23:21:16.798Z] /go/src/github.com/milvus-io/milvus/internal/proxy/util.go:863 github.com/milvus-io/milvus/internal/proxy.isCollectionLoaded

[2023-02-23T23:21:16.798Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_index.go:297 github.com/milvus-io/milvus/internal/proxy.(*createIndexTask).PreExecute

[2023-02-23T23:21:16.798Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:447 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask

[2023-02-23T23:21:16.798Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:489 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop

[2023-02-23T23:21:16.798Z] /usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit

[2023-02-23T23:21:16.798Z] )>, <Time:{'RPC start': '2023-02-23 23:21:16.357800', 'RPC error': '2023-02-23 23:21:16.361984'}> (decorators.py:108)

[2023-02-23T23:21:16.798Z] [2023-02-23 23:21:16 - ERROR - ci_test]: Traceback (most recent call last):

[2023-02-23T23:21:16.798Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2023-02-23T23:21:16.798Z]     res = func(*args, **_kwargs)

[2023-02-23T23:21:16.798Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2023-02-23T23:21:16.798Z]     return func(*arg, **kwargs)

[2023-02-23T23:21:16.798Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 953, in create_index

[2023-02-23T23:21:16.798Z]     return conn.create_index(self._name, field_name, index_params, timeout=timeout, **kwargs)

[2023-02-23T23:21:16.798Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-02-23T23:21:16.798Z]     raise e

[2023-02-23T23:21:16.798Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-02-23T23:21:16.798Z]     return func(*args, **kwargs)

[2023-02-23T23:21:16.798Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-02-23T23:21:16.798Z]     ret = func(self, *args, **kwargs)

[2023-02-23T23:21:16.798Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-02-23T23:21:16.798Z]     raise e

[2023-02-23T23:21:16.798Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-02-23T23:21:16.798Z]     return func(self, *args, **kwargs)

[2023-02-23T23:21:16.798Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 568, in create_index

[2023-02-23T23:21:16.798Z]     raise MilvusException(status.error_code, status.reason)

[2023-02-23T23:21:16.798Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=err: find no available querycoord, check querycoord state

[2023-02-23T23:21:16.798Z] , /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace

[2023-02-23T23:21:16.798Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:304 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall

[2023-02-23T23:21:16.798Z] /go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/client/client.go:168 github.com/milvus-io/milvus/internal/distributed/querycoord/client.(*Client).ShowCollections

[2023-02-23T23:21:16.798Z] /go/src/github.com/milvus-io/milvus/internal/proxy/util.go:863 github.com/milvus-io/milvus/internal/proxy.isCollectionLoaded

[2023-02-23T23:21:16.798Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_index.go:297 github.com/milvus-io/milvus/internal/proxy.(*createIndexTask).PreExecute

[2023-02-23T23:21:16.798Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:447 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask

[2023-02-23T23:21:16.798Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:489 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop

[2023-02-23T23:21:16.798Z] /usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit

[2023-02-23T23:21:16.798Z] )>

[2023-02-23T23:21:16.798Z]  (api_request.py:39)

[2023-02-23T23:21:16.798Z] [2023-02-23 23:21:16 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=err: find no available querycoord, check querycoord state

[2023-02-23T23:21:16.798Z] , /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace

[2023-02-23T23:21:16.798Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:3...... (api_request.py:40)

[2023-02-23T23:21:16.798Z] ------------- generated html file: file:///tmp/ci_logs/report.html -------------

[2023-02-23T23:21:16.798Z] =========================== short test summary info ============================

[2023-02-23T23:21:16.798Z] FAILED ../testcases/test_e2e.py::TestE2e::test_milvus_default - AssertionError

[2023-02-23T23:21:16.798Z] ============================== 1 failed in 4.63s ===============================
```

### Milvus Log

chaos type: pod-kill image tag: 2.2.0-20230223-7808bb51 target pod: etcd

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-for-release-cron/detail/chaos-test-kafka-for-release-cron/2198/pipeline
log:

[artifacts-etcd-pod-kill-2198-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10820120/artifacts-etcd-pod-kill-2198-server-logs.tar.gz)

[artifacts-etcd-pod-kill-2198-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10820121/artifacts-etcd-pod-kill-2198-pytest-logs.tar.gz)

**Comment by smellthemoon** [comment]
Querycoord didn't start up because it couldn't connect to etcd, the etcd has an error: lease not found.
![1](https://user-images.githubusercontent.com/64083300/221550395-9fe5d53d-2e9b-4881-9812-4a3cb16cd867.png)
Is this a stable recurrence? If it is, consider upgrading or choose a more stable etcd version.
@zhuwenxing

**Comment by smellthemoon** [comment]
Did it reappear these days? @zhuwenxing

**Comment by zhuwenxing** [comment]
Not reproduced in 2.2.0-20230310-b2ece6a5
