### ISSUE TITLE
[Bug]: Segment info is not complete for collection which index is IVF_SQ8

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#22388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230223-98cde49a
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):rocksmq    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2023-02-23T11:21:20.170Z] 2023-02-23 11:21:20.173 | INFO     | __main__:milvus_recall_test:74 - recall test for index type IVF_SQ8

[2023-02-23T11:21:20.728Z] 2023-02-23 11:21:20.583 | INFO     | __main__:milvus_recall_test:88 - Create collection sift_128_euclidean_IVF_SQ8

[2023-02-23T11:21:20.728Z] 2023-02-23 11:21:20.597 | INFO     | __main__:milvus_recall_test:95 - epoch: 0

[2023-02-23T11:21:22.086Z] 2023-02-23 11:21:21.805 | INFO     | __main__:milvus_recall_test:95 - epoch: 1

[2023-02-23T11:21:23.442Z] 2023-02-23 11:21:23.148 | INFO     | __main__:milvus_recall_test:95 - epoch: 2

[2023-02-23T11:21:24.801Z] 2023-02-23 11:21:24.397 | INFO     | __main__:milvus_recall_test:95 - epoch: 3

[2023-02-23T11:21:26.168Z] 2023-02-23 11:21:25.941 | INFO     | __main__:milvus_recall_test:95 - epoch: 4

[2023-02-23T11:21:27.526Z] 2023-02-23 11:21:27.213 | INFO     | __main__:milvus_recall_test:95 - epoch: 5

[2023-02-23T11:21:28.885Z] 2023-02-23 11:21:28.716 | INFO     | __main__:milvus_recall_test:95 - epoch: 6

[2023-02-23T11:21:30.243Z] 2023-02-23 11:21:30.216 | INFO     | __main__:milvus_recall_test:95 - epoch: 7

[2023-02-23T11:21:32.127Z] 2023-02-23 11:21:31.631 | INFO     | __main__:milvus_recall_test:95 - epoch: 8

[2023-02-23T11:21:33.048Z] 2023-02-23 11:21:32.971 | INFO     | __main__:milvus_recall_test:95 - epoch: 9

[2023-02-23T11:21:34.408Z] 2023-02-23 11:21:34.242 | INFO     | __main__:milvus_recall_test:95 - epoch: 10

[2023-02-23T11:21:35.769Z] 2023-02-23 11:21:35.501 | INFO     | __main__:milvus_recall_test:95 - epoch: 11

[2023-02-23T11:21:37.126Z] 2023-02-23 11:21:36.849 | INFO     | __main__:milvus_recall_test:95 - epoch: 12

[2023-02-23T11:21:38.497Z] 2023-02-23 11:21:38.289 | INFO     | __main__:milvus_recall_test:95 - epoch: 13

[2023-02-23T11:21:39.890Z] 2023-02-23 11:21:39.844 | INFO     | __main__:milvus_recall_test:95 - epoch: 14

[2023-02-23T11:21:41.251Z] 2023-02-23 11:21:41.225 | INFO     | __main__:milvus_recall_test:95 - epoch: 15

[2023-02-23T11:21:42.610Z] 2023-02-23 11:21:42.501 | INFO     | __main__:milvus_recall_test:95 - epoch: 16

[2023-02-23T11:21:43.970Z] 2023-02-23 11:21:43.924 | INFO     | __main__:milvus_recall_test:95 - epoch: 17

[2023-02-23T11:21:45.852Z] 2023-02-23 11:21:45.359 | INFO     | __main__:milvus_recall_test:95 - epoch: 18

[2023-02-23T11:21:46.774Z] 2023-02-23 11:21:46.746 | INFO     | __main__:milvus_recall_test:95 - epoch: 19

[2023-02-23T11:21:48.655Z] 2023-02-23 11:21:48.330 | INFO     | __main__:milvus_recall_test:108 - Insert 1000000 vectors cost 27.7331 seconds

[2023-02-23T11:21:48.655Z] 2023-02-23 11:21:48.330 | INFO     | __main__:milvus_recall_test:111 - Get collection entities...

[2023-02-23T11:21:51.165Z] 2023-02-23 11:21:50.882 | INFO     | __main__:milvus_recall_test:116 - 1000000

[2023-02-23T11:21:51.165Z] 2023-02-23 11:21:50.882 | INFO     | __main__:milvus_recall_test:118 - Get collection entities cost 2.5523 seconds

[2023-02-23T11:21:51.165Z] 2023-02-23 11:21:50.882 | INFO     | __main__:milvus_recall_test:122 - Create index...

[2023-02-23T11:22:37.797Z] 2023-02-23 11:22:36.181 | INFO     | __main__:milvus_recall_test:127 - Create index cost 45.2981 seconds

[2023-02-23T11:22:37.797Z] 2023-02-23 11:22:36.181 | INFO     | __main__:milvus_recall_test:131 - load collection...

[2023-02-23T11:22:43.038Z] 2023-02-23 11:22:42.235 | INFO     | __main__:milvus_recall_test:135 - load collection cost 6.0542 seconds

[2023-02-23T11:22:43.038Z] 2023-02-23 11:22:42.237 | INFO     | __main__:milvus_recall_test:138 - segments info: [segmentID: 439655075302311506

[2023-02-23T11:22:43.038Z] collectionID: 439655075302111492

[2023-02-23T11:22:43.038Z] partitionID: 439655075302111493

[2023-02-23T11:22:43.038Z] num_rows: 174374

[2023-02-23T11:22:43.038Z] state: Sealed

[2023-02-23T11:22:43.038Z] nodeIds: 2

[2023-02-23T11:22:43.038Z] ]

[2023-02-23T11:22:43.038Z] Traceback (most recent call last):

[2023-02-23T11:22:43.038Z]   File "scripts/first_recall_test.py", line 201, in <module>

[2023-02-23T11:22:43.038Z]     milvus_recall_test(host, index_type)

[2023-02-23T11:22:43.038Z]   File "scripts/first_recall_test.py", line 141, in milvus_recall_test

[2023-02-23T11:22:43.038Z]     assert cnt == collection.num_entities

[2023-02-23T11:22:43.038Z] AssertionError
```

The code:
```
    # load collection
    replica_number = 1
    logger.info(f"load collection...")
    t0 = time.time()
    collection.load(replica_number=replica_number)
    t1 = time.time()
    logger.info(f"load collection cost {t1 - t0:.4f} seconds")
    res = utility.get_query_segment_info(name)
    cnt = 0
    logger.info(f"segments info: {res}")
    for segment in res:
        cnt += segment.num_rows
    assert cnt == collection.num_entities
```

### Milvus Log

2.2.0-20230223-98cde49a

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_for_release_cron/detail/deploy_test_for_release_cron/400/pipeline
log:

[artifacts-pulsar-standalone-reinstall-400-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10820276/artifacts-pulsar-standalone-reinstall-400-server-logs.tar.gz)

[artifacts-pulsar-standalone-reinstall-400-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10820277/artifacts-pulsar-standalone-reinstall-400-pytest-logs.tar.gz)

**Comment by yanliang567** [comment]
sounds like it is not completely loaded, although after calling load()

/assign @jiaoew1991 
/unassign

**Comment by zhuwenxing** [comment]
It reproduced stably.
milvus mode: standalone deploy task: reinstall , image tag: 2.2.0-20230227-b01b467b
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_for_release_cron/detail/deploy_test_for_release_cron/430/pipeline
log:
[artifacts-pulsar-standalone-reinstall-430-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10846006/artifacts-pulsar-standalone-reinstall-430-server-logs.tar.gz)
[artifacts-pulsar-standalone-reinstall-430-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10846007/artifacts-pulsar-standalone-reinstall-430-pytest-logs.tar.gz)

**Comment by aoiasd** [comment]
Load task completed, but load task just load a part of segments  all, query coord only fetch a part of all segments at loading,  I will try to find what lead to this. And could see that the only loaded segment has been compact to a new segment in DataCoord.

**Comment by zhuwenxing** [comment]
milvus mode: cluster deploy task: reinstall old image tag: v2.2.2 new image tag: 2.2.0-20230228-bd5b263c

```
[2023-02-28T12:43:52.613Z] 2023-02-28 12:43:52.570 | INFO     | __main__:milvus_recall_test:88 - Create collection sift_128_euclidean_ANNOY

[2023-02-28T12:43:53.969Z] 2023-02-28 12:43:53.921 | INFO     | __main__:milvus_recall_test:95 - epoch: 0

[2023-02-28T12:43:56.557Z] 2023-02-28 12:43:56.082 | INFO     | __main__:milvus_recall_test:95 - epoch: 1

[2023-02-28T12:43:59.086Z] 2023-02-28 12:43:58.476 | INFO     | __main__:milvus_recall_test:95 - epoch: 2

[2023-02-28T12:44:00.445Z] 2023-02-28 12:44:00.207 | INFO     | __main__:milvus_recall_test:95 - epoch: 3

[2023-02-28T12:44:03.032Z] 2023-02-28 12:44:02.385 | INFO     | __main__:milvus_recall_test:95 - epoch: 4

[2023-02-28T12:44:04.969Z] 2023-02-28 12:44:04.584 | INFO     | __main__:milvus_recall_test:95 - epoch: 5

[2023-02-28T12:44:06.882Z] 2023-02-28 12:44:06.371 | INFO     | __main__:milvus_recall_test:95 - epoch: 6

[2023-02-28T12:44:08.246Z] 2023-02-28 12:44:08.014 | INFO     | __main__:milvus_recall_test:95 - epoch: 7

[2023-02-28T12:44:10.182Z] 2023-02-28 12:44:09.800 | INFO     | __main__:milvus_recall_test:95 - epoch: 8

[2023-02-28T12:44:11.569Z] 2023-02-28 12:44:11.497 | INFO     | __main__:milvus_recall_test:95 - epoch: 9

[2023-02-28T12:44:13.466Z] 2023-02-28 12:44:13.207 | INFO     | __main__:milvus_recall_test:95 - epoch: 10

[2023-02-28T12:44:15.372Z] 2023-02-28 12:44:14.935 | INFO     | __main__:milvus_recall_test:95 - epoch: 11

[2023-02-28T12:44:16.752Z] 2023-02-28 12:44:16.567 | INFO     | __main__:milvus_recall_test:95 - epoch: 12

[2023-02-28T12:44:18.649Z] 2023-02-28 12:44:18.166 | INFO     | __main__:milvus_recall_test:95 - epoch: 13

[2023-02-28T12:44:20.007Z] 2023-02-28 12:44:19.778 | INFO     | __main__:milvus_recall_test:95 - epoch: 14

[2023-02-28T12:44:21.885Z] 2023-02-28 12:44:21.498 | INFO     | __main__:milvus_recall_test:95 - epoch: 15

[2023-02-28T12:44:23.244Z] 2023-02-28 12:44:23.135 | INFO     | __main__:milvus_recall_test:95 - epoch: 16

[2023-02-28T12:44:25.126Z] 2023-02-28 12:44:24.927 | INFO     | __main__:milvus_recall_test:95 - epoch: 17

[2023-02-28T12:44:27.007Z] 2023-02-28 12:44:26.941 | INFO     | __main__:milvus_recall_test:95 - epoch: 18

[2023-02-28T12:44:28.885Z] 2023-02-28 12:44:28.735 | INFO     | __main__:milvus_recall_test:95 - epoch: 19

[2023-02-28T12:44:30.775Z] 2023-02-28 12:44:30.528 | INFO     | __main__:milvus_recall_test:108 - Insert 1000000 vectors cost 36.6073 seconds

[2023-02-28T12:44:30.775Z] 2023-02-28 12:44:30.529 | INFO     | __main__:milvus_recall_test:111 - Get collection entities...

[2023-02-28T12:44:36.048Z] 2023-02-28 12:44:35.587 | INFO     | __main__:milvus_recall_test:116 - 1000000

[2023-02-28T12:44:36.048Z] 2023-02-28 12:44:35.588 | INFO     | __main__:milvus_recall_test:118 - Get collection entities cost 5.0591 seconds

[2023-02-28T12:44:36.048Z] 2023-02-28 12:44:35.588 | INFO     | __main__:milvus_recall_test:122 - Create index...

[2023-02-28T12:45:08.073Z] 2023-02-28 12:45:03.074 | INFO     | __main__:milvus_recall_test:127 - Create index cost 27.4863 seconds

[2023-02-28T12:45:08.073Z] 2023-02-28 12:45:03.075 | INFO     | __main__:milvus_recall_test:131 - load collection...

[2023-02-28T12:45:09.952Z] 2023-02-28 12:45:09.664 | INFO     | __main__:milvus_recall_test:135 - load collection cost 6.5897 seconds

[2023-02-28T12:45:09.952Z] 2023-02-28 12:45:09.668 | INFO     | __main__:milvus_recall_test:138 - segments info: [segmentID: 439769510231080191

[2023-02-28T12:45:09.952Z] collectionID: 439769510230079885

[2023-02-28T12:45:09.952Z] partitionID: 439769510230079886

[2023-02-28T12:45:09.952Z] num_rows: 150086

[2023-02-28T12:45:09.952Z] state: Sealed

[2023-02-28T12:45:09.952Z] nodeIds: 7

[2023-02-28T12:45:09.952Z] , segmentID: 439769510230479994

[2023-02-28T12:45:09.952Z] collectionID: 439769510230079885

[2023-02-28T12:45:09.952Z] partitionID: 439769510230079886

[2023-02-28T12:45:09.952Z] num_rows: 175354

[2023-02-28T12:45:09.952Z] state: Sealed

[2023-02-28T12:45:09.952Z] nodeIds: 7

[2023-02-28T12:45:09.952Z] , segmentID: 439769510231080192

[2023-02-28T12:45:09.952Z] collectionID: 439769510230079885

[2023-02-28T12:45:09.952Z] partitionID: 439769510230079886

[2023-02-28T12:45:09.952Z] num_rows: 149914

[2023-02-28T12:45:09.952Z] state: Sealed

[2023-02-28T12:45:09.952Z] nodeIds: 7

[2023-02-28T12:45:09.952Z] ]

[2023-02-28T12:45:09.952Z] Traceback (most recent call last):

[2023-02-28T12:45:09.952Z]   File "scripts/first_recall_test.py", line 201, in <module>

[2023-02-28T12:45:09.952Z]     milvus_recall_test(host, index_type)

[2023-02-28T12:45:09.952Z]   File "scripts/first_recall_test.py", line 141, in milvus_recall_test

[2023-02-28T12:45:09.952Z]     assert cnt == collection.num_entities

[2023-02-28T12:45:09.952Z] AssertionError
```

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_kafka_for_release_cron/detail/deploy_test_kafka_for_release_cron/435/pipeline

log:
[artifacts-kafka-cluster-reinstall-435-server-second-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/10856933/artifacts-kafka-cluster-reinstall-435-server-second-deployment-logs.tar.gz)

[artifacts-kafka-cluster-reinstall-435-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10856934/artifacts-kafka-cluster-reinstall-435-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
This issue blocked the reinstall deploy test, please set it as high priority

**Comment by aoiasd** [comment]
related https://github.com/milvus-io/milvus/issues/22374, Create Index still return early, I will fix it

**Comment by aoiasd** [comment]
related https://github.com/milvus-io/milvus/issues/22374,create index end early, if segment dropped because compact

**Comment by aoiasd** [comment]
Still has problem, https://github.com/milvus-io/milvus/pull/22509 could prevent create index end early，but now will block create index.
We need to confirm semantics of create index. if the client create index should wait for a new flushed segment at runtime. If not will cause that getSegmentInfo could not get current row num（this issue），but wait will cause that create index may delay many times.
Or ban compaction at creating index.

**Comment by aoiasd** [comment]
Fixed.

**Comment by jiaoew1991** [comment]
/unassign @aoiasd 
/assign @zhuwenxing 
pls verify it
