### ISSUE TITLE
[Bug]: [Nightly] Load failed for timeout with error "Retry timeout: 120s, message=wait for loading collection timeout" 

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#22392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-latest (8dc5114)
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):   pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus2.3.0.dev38
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Load failed for timeout with error "Retry timeout: 120s, message=wait for loading collection timeout" 
```
[2023-02-23 19:35:52,141 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:56)
[2023-02-23 19:35:53,139 - ERROR - ci_test]: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 675, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 697, in wait_for_loading_collection
    raise MilvusException(message=f"wait for loading collection timeout, collection: {collection_name}")
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=wait for loading collection timeout, collection: query_AMaboAdi)>
```

### Expected Behavior

Load successfully without any errors

### Steps To Reproduce

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/292/pipeline/187

A lot of cases failed for load time:
```markdown
...
[2023-02-23T21:49:23.987Z] [gw1] [ 43%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_normal[2-128-True-False] 

[2023-02-23T21:59:00.571Z] testcases/test_search.py::TestCollectionSearch::test_search_normal[2-128-True-True] 

[2023-02-23T21:59:00.571Z] [gw5] [ 43%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_after_index_different_metric_type[32-False-True-DISKANN-params6] 

[2023-02-23T22:06:52.118Z] testcases/test_search.py::TestCollectionSearch::test_search_after_index_different_metric_type[32-True-False-FLAT-params0] 

[2023-02-23T22:06:52.118Z] [gw4] [ 43%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_after_different_index_with_params[32-True-True-HNSW-params4] 

[2023-02-23T22:39:29.531Z] testcases/test_search.py::TestCollectionSearch::test_search_after_different_index_with_params[32-True-True-ANNOY-params5] 

[2023-02-23T22:39:29.531Z] [gw2] [ 43%] XFAIL testcases/test_search.py::TestCollectionSearch::test_search_before_after_delete[500-32-True-False] 

[2023-02-23T22:45:21.027Z] testcases/test_search.py::TestCollectionSearch::test_search_before_after_delete[500-32-True-True] 

[2023-02-23T22:45:21.027Z] [gw3] [ 43%] FAILED testcases/test_query.py::TestQueryParams::test_query_pagination_with_expression[0-int64 > 0] 

[2023-02-23T22:49:12.437Z] testcases/test_query.py::TestQueryParams::test_query_pagination_with_expression[0-(int64 > 0 && int64 < 400) or (int64 > 500 && int64 < 1000)] 

[2023-02-23T22:49:12.437Z] [gw0] [ 43%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_HNSW_index_with_max_ef[False-False-512-4] 

[2023-02-23T23:18:19.403Z] testcases/test_search.py::TestCollectionSearch::test_search_HNSW_index_with_max_ef[False-False-512-64] 

[2023-02-23T23:18:19.403Z] [gw1] [ 43%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_normal[2-128-True-True] 

[2023-02-23T23:20:25.778Z] testcases/test_search.py::TestCollectionSearch::test_search_normal[500-32-False-False] 

[2023-02-23T23:20:25.778Z] [gw1] [ 43%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_normal[500-32-False-False] 

[2023-02-23T23:37:02.585Z] testcases/test_search.py::TestCollectionSearch::test_search_normal[500-32-False-True] 

[2023-02-23T23:37:02.585Z] [gw5] [ 43%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_after_index_different_metric_type[32-True-False-FLAT-params0] 

[2023-02-23T23:51:39.252Z] testcases/test_search.py::TestCollectionSearch::test_search_after_index_different_metric_type[32-True-False-IVF_FLAT-params1] 

[2023-02-23T23:51:39.252Z] [gw4] [ 43%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_after_different_index_with_params[32-True-True-ANNOY-params5] 

[2023-02-24T00:00:45.792Z] testcases/test_search.py::TestCollectionSearch::test_search_after_different_index_with_params[32-True-True-DISKANN-params6] 
```

### Milvus Log

[artifacts-milvus-distributed-pulsar-nightly-292-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/292/artifact/artifacts-milvus-distributed-pulsar-nightly-292-pymilvus-e2e-logs.tar.gz)

### Anything else?

Take one case as an example:
1. case name: testcases/test_search.py::TestCollectionSearch::test_search_after_different_index_with_params[
2. collection name: search_collection_iC6Yx0cn
3. failed time: 
[2023-02-23T20:21:07.726Z] testcases/test_search.py::TestCollectionSearch::test_search_after_different_index_with_params[32-True-False-DISKANN-params6] 
4. error
[2023-02-23 19:35:52,141 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:56)
[2023-02-23 19:35:53,139 - ERROR - ci_test]: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 675, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 697, in wait_for_loading_collection
    raise MilvusException(message=f"wait for loading collection timeout, collection: {collection_name}")
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=wait for loading collection timeout, collection: query_AMaboAdi)>

**Comment by binbinlv** [comment]
Large numbers of cases failed for this reason in nightly (cluster, pulsar), so set it as urgent.

**Comment by jiaoew1991** [comment]
Let's keep the log level to Debug when running nightly tests.

**Comment by NicoYuan1986** [comment]
reproduced again.
link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/299/pipeline/187
log: [artifacts-milvus-distributed-pulsar-nightly-299-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/299/artifact/artifacts-milvus-distributed-pulsar-nightly-299-pymilvus-e2e-logs.tar.gz)
failed cases: 
```
[2023-03-02T18:18:03.687Z] testcases/test_search.py::TestCollectionSearch::test_search_with_dup_primary_key[32-True-False-2] 
[2023-03-02T18:18:03.693Z] [gw5] [ 40%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_after_different_index_with_min_dim[False-True-HNSW-params4] 
[2023-03-02T18:18:03.693Z] testcases/test_search.py::TestCollectionSearch::test_search_after_different_index_with_min_dim[False-True-ANNOY-params5] 
[2023-03-02T18:18:03.693Z] [gw3] [ 40%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_HNSW_index_with_min_ef[False-False-3000-8-4] 
[2023-03-02T18:18:03.693Z] testcases/test_search.py::TestCollectionSearch::test_search_HNSW_index_with_min_ef[False-False-3000-8-64] 
[2023-03-02T18:18:03.693Z] testcases/test_search.py::TestCollectionSearchInvalid::test_search_param_invalid_metric_type[1] 
[2023-03-02T18:18:03.693Z] [gw2] [ 40%] FAILED testcases/test_query.py::TestQueryParams::test_query_output_fields_simple_wildcard 
[2023-03-02T18:18:03.693Z] testcases/test_query.py::TestQueryParams::test_query_output_fields_part_scale_wildcard 
[2023-03-02T18:18:03.693Z] [gw0] [ 40%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_collection_after_release_load[5000-2-128-True-True] 
[2023-03-02T18:19:25.067Z] testcases/test_search.py::TestCollectionSearch::test_search_collection_after_release_load[5000-500-32-False-False] 
[2023-03-02T18:19:25.068Z] [gw1] [ 40%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_with_dup_primary_key[32-True-False-2] 
[2023-03-02T18:20:11.681Z] testcases/test_search.py::TestCollectionSearch::test_search_with_dup_primary_key[32-True-False-3] 
[2023-03-02T18:20:11.681Z] [gw3] [ 40%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_HNSW_index_with_min_ef[False-False-3000-8-64] 
[2023-03-02T18:20:11.681Z] testcases/test_search.py::TestCollectionSearch::test_search_HNSW_index_with_min_ef[False-False-3000-512-4] 
[2023-03-02T18:20:11.681Z] [gw5] [ 40%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_after_different_index_with_min_dim[False-True-ANNOY-params5] 
[2023-03-02T18:20:11.681Z] testcases/test_search.py::TestCollectionSearch::test_search_after_different_index_with_min_dim[True-False-FLAT-params0] 
[2023-03-02T18:20:11.681Z] [gw4] [ 40%] FAILED testcases/test_search.py::TestCollectionSearchInvalid::test_search_param_invalid_metric_type[1] 
[2023-03-02T18:20:11.681Z] testcases/test_search.py::TestCollectionSearchInvalid::test_search_param_invalid_metric_type[get_invalid_metric_type2] 
[2023-03-02T18:20:11.681Z] [gw2] [ 40%] FAILED testcases/test_query.py::TestQueryParams::test_query_output_fields_part_scale_wildcard 
[2023-03-02T18:20:11.681Z] testcases/test_query.py::TestQueryParams::test_query_output_fields_part_vector_wildcard 
[2023-03-02T18:20:11.681Z] [gw0] [ 40%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_collection_after_release_load[5000-500-32-False-False] 
[2023-03-02T18:21:33.038Z] testcases/test_search.py::TestCollectionSearch::test_search_collection_after_release_load[5000-500-32-False-True] 
[2023-03-02T18:21:33.040Z] [gw1] [ 41%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_with_dup_primary_key[32-True-False-3] 
[2023-03-02T18:21:33.040Z] testcases/test_search.py::TestCollectionSearch::test_search_with_dup_primary_key[32-True-True-1] 
```

**Comment by jiaoew1991** [comment]
**Failed to unsubscribe the consumer caused QueryNode to panic.**

<img width="2483" alt="image" src="https://user-images.githubusercontent.com/2297455/223336707-4f19c456-d7d9-4cb6-93ec-7c552c1cf550.png">

**After the QueryNode restarted, the target node id had changed**

<img width="2511" alt="image" src="https://user-images.githubusercontent.com/2297455/223337217-c2289e39-08d6-4cc2-ae5a-b68812950712.png">

**Comment by jiaoew1991** [comment]
/unassign 
/assign @NicoYuan1986 
please verify it with #22607

**Comment by NicoYuan1986** [comment]
Not fixed.
https://jenkins.milvus.io:18080/blue/rest/organizations/jenkins/pipelines/Milvus%20Nightly%20CI/branches/master/runs/306/nodes/197/steps/217/log/?start=0

failed cases:
```
[2023-03-09T18:13:00.815Z] [gw2] [ 31%] FAILED testcases/test_query.py::TestQueryParams::test_query_non_string_expr 
[2023-03-09T18:13:00.815Z] [gw5] [ 31%] FAILED testcases/test_query.py::TestQueryParams::test_query_pagination_with_expression[100-0 < int64 < 400] 
[2023-03-09T18:13:00.815Z] [gw0] [ 31%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_normal_default_params[32-False-True-search_params2] 
[2023-03-09T18:13:00.815Z] [gw1] [ 31%] FAILED testcases/test_search.py::TestCollectionSearchInvalid::test_search_binary_flat_with_L2 
[2023-03-09T18:13:00.815Z] [gw3] [ 31%] FAILED testcases/test_delete.py::TestDeleteString::test_delete_entity_loop_with_string 
[2023-03-09T18:15:07.207Z] [gw2] [ 31%] FAILED testcases/test_query.py::TestQueryParams::test_query_expr_invalid_string 
[2023-03-09T18:15:07.207Z] [gw5] [ 31%] FAILED testcases/test_query.py::TestQueryParams::test_query_pagination_with_expression[100-500 <= int64 < 1000] 
[2023-03-09T18:15:07.207Z] [gw0] [ 31%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_normal_default_params[32-True-False-search_params0] 
[2023-03-09T18:15:07.207Z] [gw1] [ 31%] FAILED testcases/test_search.py::TestCollectionSearchInvalid::test_search_with_output_fields_not_exist 
[2023-03-09T18:15:07.207Z] [gw3] [ 31%] FAILED testcases/test_delete.py::TestDeleteString::test_delete_merge_ids_channel_and_sealed_string 
[2023-03-09T18:17:13.619Z] [gw2] [ 31%] FAILED testcases/test_query.py::TestQueryParams::test_query_expr_non_primary_fields 
[2023-03-09T18:17:13.619Z] [gw5] [ 31%] FAILED testcases/test_query.py::TestQueryParams::test_query_pagination_with_expression[100-200+300 < int64 <= 500+500] 
[2023-03-09T18:17:13.619Z] [gw0] [ 31%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_normal_default_params[32-True-False-search_params1] 
[2023-03-09T18:17:13.619Z] [gw1] [ 31%] FAILED testcases/test_search.py::TestCollectionSearchInvalid::test_search_output_field_vector[output_fields0] 
[2023-03-09T18:17:13.619Z] [gw3] [ 31%] FAILED testcases/test_delete.py::TestDeleteString::test_delete_insert_same_id_sealed_string[False] 
```

log: [artifacts-milvus-distributed-pulsar-nightly-306-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/306/artifact/artifacts-milvus-distributed-pulsar-nightly-306-pymilvus-e2e-logs.tar.gz)

/assign @jiaoew1991

**Comment by jiaoew1991** [comment]
QueryNode crashed by unknown reason 

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/2297455/225792423-44e29f8d-61dd-4f8a-b810-a4157df34523.png">
