### ISSUE TITLE
[Bug]: Collection is renamed failed reporting "get collection_id by collection_name not found"

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#22391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-latest (8dc5114)
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):  kafka
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus2.3.0.dev38
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Collection is renamed failed reporting "get collection_id by collection_name not found"
```
[2023-02-23T19:21:16.433Z] [2023-02-23 18:58:51 - DEBUG - ci_test]: (api_request)  : [rename_collection] args: ['utility_8L8tlEzV', 'utilitynew_2ivfo3UX', None], kwargs: {} (api_request.py:56)
[2023-02-23T19:21:16.433Z] [2023-02-23 18:58:51 - ERROR - pymilvus.decorators]: RPC error: [rename_collections], <MilvusException: (code=1, message=get collection_id by collection_name not found, collName=utilitynew_2ivfo3UX, ts=439662341490475014)>, <Time:{'RPC start': '2023-02-23 18:58:51.927136', 'RPC error': '2023-02-23 18:58:51.930911'}> (decorators.py:108)
[2023-02-23T19:21:16.433Z] [2023-02-23 18:58:51 - ERROR - ci_test]: Traceback (most recent call last):
[2023-02-23T19:21:16.433Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2023-02-23T19:21:16.433Z]     res = func(*args, **_kwargs)
[2023-02-23T19:21:16.433Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2023-02-23T19:21:16.433Z]     return func(*arg, **kwargs)
[2023-02-23T19:21:16.433Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/utility.py", line 477, in rename_collection
[2023-02-23T19:21:16.433Z]     return _get_connection(using).rename_collections(old_collection_name, new_collection_name, timeout=timeout)
[2023-02-23T19:21:16.433Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2023-02-23T19:21:16.433Z]     raise e
[2023-02-23T19:21:16.433Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2023-02-23T19:21:16.433Z]     return func(*args, **kwargs)
[2023-02-23T19:21:16.433Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2023-02-23T19:21:16.433Z]     ret = func(self, *args, **kwargs)
[2023-02-23T19:21:16.433Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
[2023-02-23T19:21:16.433Z]     raise e
[2023-02-23T19:21:16.433Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2023-02-23T19:21:16.433Z]     return func(self, *args, **kwargs)
[2023-02-23T19:21:16.433Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 282, in rename_collections
[2023-02-23T19:21:16.433Z]     raise MilvusException(response.error_code, response.reason)
[2023-02-23T19:21:16.433Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=get collection_id by collection_name not found, collName=utilitynew_2ivfo3UX, ts=439662341490475014)>
```

### Expected Behavior

Collection is renamed successfully without any errors

### Steps To Reproduce
https://jenkins.milvus.io:18080/blue/rest/organizations/jenkins/pipelines/Milvus%20Nightly%20CI/branches/master/runs/292/nodes/63/steps/175/log/?start=0

```markdown
testcases/test_utility.py::TestUtilityBase::test_rename_collection
```

### Milvus Log

[artifacts-milvus-distributed-kafka-nightly-292-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/292/artifact/artifacts-milvus-distributed-kafka-nightly-292-pymilvus-e2e-logs.tar.gz)

### Anything else?

collection name: utility_8L8tlEzV
Failed time:
[2023-02-23T18:58:52.389Z] [gw1] [ 96%] FAILED testcases/test_utility.py::TestUtilityBase::test_rename_collection

**Comment by xiaofan-luan** [comment]
seems to be an atomicity issue?

**Comment by jaime0815** [comment]
It is an issue with Mysql metastore, which suggests metastore doesn't use Mysql due to this function being stale. Mysql metastore is not aligned with Etcd metastore for a long period of time.
