### ISSUE TITLE
[Bug]: [benchmark][IVF_FLAT] Milvus search failed with error "fail to search on all shard leaders"

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#22418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230224-8f1bcc37
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.0.dev34
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task : fouramf-cron-1677340800 , id 3
index: IVF_FLAT
case: test_ivf_flat_search_standalone

server:
```
fouramf-cron-1677340800-3-84-1230-etcd-0                          1/1     Running            0                 2m13s   10.104.6.92     4am-node13   <none>           <none>
fouramf-cron-1677340800-3-84-1230-milvus-standalone-6cbd99zz9l2   1/1     Running            0                 2m13s   10.104.1.86     4am-node10   <none>           <none>
fouramf-cron-1677340800-3-84-1230-minio-5bb984846d-m89gh          1/1     Running            0                 2m13s   10.104.1.87     4am-node10   <none>           <none> 
```

client log
```
[2023-02-25 16:44:49,903 -  INFO - fouram]: [Base] Params of search: nq:10, anns_field:float_vector, param:{'metric_type': 'L2', 'params': {'nprobe': 32}}, limit:1, expr:"None", kwargs:{} (base.py:317)
[2023-02-25 16:44:50,027 -  INFO - fouram]: [Time] Collection.search run in 0.1244s (api_request.py:41)
[2023-02-25 16:44:50,028 -  INFO - fouram]: [Base] Params of search: nq:10, anns_field:float_vector, param:{'metric_type': 'L2', 'params': {'nprobe': 32}}, limit:1, expr:"None", kwargs:{} (base.py:317)
[2023-02-25 16:44:50,157 -  INFO - fouram]: [Time] Collection.search run in 0.1292s (api_request.py:41)
[2023-02-25 16:44:50,157 -  INFO - fouram]: [Base] Params of search: nq:10, anns_field:float_vector, param:{'metric_type': 'L2', 'params': {'nprobe': 32}}, limit:1, expr:"None", kwargs:{} (base.py:317)
[2023-02-25 16:44:50,285 -  INFO - fouram]: [Time] Collection.search run in 0.1277s (api_request.py:41)
[2023-02-25 16:44:50,286 -  INFO - fouram]: [Base] Params of search: nq:10, anns_field:float_vector, param:{'metric_type': 'L2', 'params': {'nprobe': 32}}, limit:1, expr:"None", kwargs:{} (base.py:317)
[2023-02-25 16:44:50,411 - ERROR - fouram]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:
attempt #1:code: UnexpectedError, error: fail to Search, QueryNode ID=1, reason=stream operation failed: [UnexpectedError] Assert "vec_ptr" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentGrowingImpl.cpp:285
 => Pointer of vec_raw is nullptr
attempt #2:context canceled
)>, <Time:{'RPC start': '2023-02-25 16:44:50.287011', 'RPC error': '2023-02-25 16:44:50.411326'}> (decorators.py:108)
[2023-02-25 16:44:50,413 - ERROR - fouram]: Traceback (most recent call last):
  File "/src/fouram/client/util/api_request.py", line 33, in inner_wrapper
    res = func(*args, **kwargs)
  File "/src/fouram/client/util/api_request.py", line 70, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 614, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
```

grafana:
![image](https://user-images.githubusercontent.com/48523564/221463995-22b54348-3ff1-4207-a134-013f691b7991.png)

### Steps To Reproduce

```markdown
1. create a collection or use an existing collection
        2. build IVF_FLAT  index on vector column
        3. insert 50 million number of vectors
        4. flush collection
        5. build index on vector column with the same parameters
        6. build index on on scalars column or not
        7. count the total number of rows
        8. load collection
        9. search collection with different parameters  ==> fail 
        10. clean all collections or not
```

### Milvus Log

milvus error log:
![image](https://user-images.githubusercontent.com/48523564/221463948-aab875b3-7ffe-4995-8381-26b959705b78.png)

### Anything else?

test_ivf_flat_search_standalone

```
    @pytest.mark.search
    @pytest.mark.parametrize("deploy_mode", [STANDALONE])
    def test_ivf_flat_search_standalone(self, input_params: InputParamsBase, deploy_mode):
        """
        :test steps:
            1. insert and calculation of search time
        """
        self.serial_template(input_params=input_params, cpu=16, mem=64, deploy_mode=deploy_mode,
                             case_callable_obj=Search().scene_search,
                             default_case_params=SearchParams().params_scene_search_ivf_flat(other_fields=[],
                                                                                             search_expr=None,
                                                                                             req_run_counts=30))
    def params_scene_search_ivf_flat(self, dataset_name=pn.DatasetsName.SIFT, dim=128, dataset_size="50m", ni_per=50000,
                                     other_fields=dp.other_fields, metric_type=pn.MetricsTypeName.L2,
                                     index_type=pn.IndexTypeName.IVF_FLAT, index_param={"nlist": 2048},
                                     top_k=[1, 10, 100, 1000], nq=[1, 10, 100, 200, 500, 1000, 1200],
                                     search_param={"nprobe": [8, 32]}, search_expr=dp.search_expr, req_run_counts=10):
        dataset_size = parser_data_size(dataset_size)

        _search_expr = []
        if search_expr is None:
            _search_expr = None
        elif isinstance(search_expr, list):
            for s in search_expr:
                _search_expr.append(eval(s))
        elif isinstance(search_expr, str):
            _search_expr.append(eval(search_expr))
        else:
            raise Exception("[SearchParams] search_expr is not: List[str], check search_expr: {0}".format(search_expr))

        default_params = self.base(dataset_name=dataset_name, dim=dim, dataset_size=dataset_size, ni_per=ni_per,
                                   other_fields=other_fields, metric_type=metric_type, index_type=index_type,
                                   index_param=index_param, top_k=top_k, nq=nq, search_param=search_param,
                                   search_expr=_search_expr, req_run_counts=req_run_counts)
        log.debug("[SearchParams] Default params of params_scene_search_ivf_flat: {0}".format(default_params))
        return default_params
```
client and server message:
```
{'server': {'deploy_tool': 'helm',
            'deploy_mode': 'standalone',
            'config_name': 'standalone_16c64m',
            'config': {'standalone': {'resources': {'limits': {'cpu': '16.0',
                                                               'memory': '64Gi'},
                                                    'requests': {'cpu': '9.0',
                                                                 'memory': '33Gi'}},
                                      'persistence': {'persistentVolumeClaim': {'storageClass': 'local-path'}}},
                       'cluster': {'enabled': False},
                       'etcd': {'replicaCount': 1,
                                'global': {'storageClass': 'local-path'},
                                'metrics': {'enabled': True,
                                            'podMonitor': {'enabled': True}}},
                       'minio': {'mode': 'standalone',
                                 'persistence': {'storageClass': 'local-path'},
                                 'metrics': {'serviceMonitor': {'enabled': False}}},
                       'pulsar': {'enabled': False},
                       'metrics': {'serviceMonitor': {'enabled': True}},
                       'image': {'all': {'repository': 'harbor.milvus.io/dockerhub/milvusdb/milvus',
                                         'tag': '2.2.0-20230224-8f1bcc37'}}},
            'host': 'fouramf-cron-1677340800-3-84-1230-milvus.qa-milvus.svc.cluster.local'},
 'client': {'test_case_type': 'Search',
            'test_case_name': 'test_ivf_flat_search_standalone',
            'test_case_params': {'dataset_params': {'dim': 128,
                                                    'dataset_name': 'sift',
                                                    'dataset_size': 50000000,
                                                    'ni_per': 50000,
                                                    'metric_type': 'L2',
                                                    'req_run_counts': 30},
                                 'collection_params': {'other_fields': []},
                                 'load_params': {},
                                 'search_params': {'nq': 1,
                                                   'param': {'metric_type': 'L2',
                                                             'params': {'nprobe': 8}},
                                                   'top_k': 1,
                                                   'expr': None},
                                 'resource_groups_params': {'reset': False},
                                 'index_params': {'index_type': 'IVF_FLAT',
                                                  'index_param': {'nlist': 2048}}},
            'run_id': 20230225,
            'datetime': '2023-02-25 16:00:46.762724',
            'client_version': '2.2.3'},
```

**Comment by jiaoew1991** [comment]
Probably fixed by https://github.com/milvus-io/milvus/pull/22414

**Comment by elstic** [comment]
After verification, the problem does not appear
