### ISSUE TITLE
[Bug]: [Nightly]Fail to rename an existing collection with its original name

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#22415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:cf999b6
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.0.dev38
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Fail to rename an existing collection with its original name.
```
[2023-02-26T19:21:34.378Z] [2023-02-26 18:03:16 - ERROR - pymilvus.decorators]: RPC error: [rename_collections], <MilvusException: (code=1, message=get collection_id by collection_name not found, collName=deletenew_7ZD2B53k, ts=439729414749814786)>, <Time:{'RPC start': '2023-02-26 18:03:16.085521', 'RPC error': '2023-02-26 18:03:16.088210'}> (decorators.py:108)
[2023-02-26T19:21:34.378Z] [2023-02-26 18:03:16 - ERROR - ci_test]: Traceback (most recent call last):
[2023-02-26T19:21:34.378Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2023-02-26T19:21:34.378Z]     res = func(*args, **_kwargs)
[2023-02-26T19:21:34.378Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2023-02-26T19:21:34.378Z]     return func(*arg, **kwargs)
[2023-02-26T19:21:34.378Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/utility.py", line 477, in rename_collection
[2023-02-26T19:21:34.378Z]     return _get_connection(using).rename_collections(old_collection_name, new_collection_name, timeout=timeout)
[2023-02-26T19:21:34.378Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2023-02-26T19:21:34.378Z]     raise e
[2023-02-26T19:21:34.378Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2023-02-26T19:21:34.378Z]     return func(*args, **kwargs)
[2023-02-26T19:21:34.378Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2023-02-26T19:21:34.378Z]     ret = func(self, *args, **kwargs)
[2023-02-26T19:21:34.378Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
[2023-02-26T19:21:34.378Z]     raise e
[2023-02-26T19:21:34.378Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2023-02-26T19:21:34.378Z]     return func(self, *args, **kwargs)
[2023-02-26T19:21:34.378Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 282, in rename_collections
[2023-02-26T19:21:34.378Z]     raise MilvusException(response.error_code, response.reason)
[2023-02-26T19:21:34.378Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=get collection_id by collection_name not found, collName=deletenew_7ZD2B53k, ts=439729414749814786)>
[2023-02-26T19:21:34.378Z]  (api_request.py:39)
[2023-02-26T19:21:34.378Z] [2023-02-26 18:03:16 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=get collection_id by collection_name not found, collName=deletenew_7ZD2B53k, ts=439729414749814786)> (api_request.py:40)
```

### Expected Behavior

succeed

### Steps To Reproduce

```markdown
1. create a collection
2. rename the collection -> raise error
```

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/293/pipeline/155
2. log: [artifacts-milvus-distributed-kafka-nightly-293-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/293/artifact/artifacts-milvus-distributed-kafka-nightly-293-pymilvus-e2e-logs.tar.gz)
3. collection name: delete_2mlCLkMa

**Comment by NicoYuan1986** [comment]
Something wrong with 'rename_collections'. 50+ cases which related to it failed.

**Comment by NicoYuan1986** [comment]
relate to #22391
