### ISSUE TITLE
[Bug]: [benchmark][HNSW] Milvus search failed, report  "fail to search on all shard leaders, err=All attempts results:"

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#22421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-20230224-8f1bcc37
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.0.dev34
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task : fouramf-cron-1677340800 , id 1
index: HNSW
case: test_recall_sift_hnsw_standalone
params:
```
check_params] scene_recall input params: {'dataset_params': {'dataset_name': 'sift-128-euclidean', 'ni_per': 10000, 'dim': 128}, 'collection_params': {'other_fields': []}, 'load_params': {'replica_number': 1}, 'index_params': {'index_type': 'HNSW', 'index_param': {'M': 16, 'efConstruction': 500}}, 'search_params': {'top_k': [10], 'nq': [10000], 'search_param': {'ef': [16, 32, 64, 128, 256, 512]}}} (params_check.py:13)
[2023-02-25 16:03:10,447 -  INFO - fouram]: [check_params] scene_recall required params: {'dataset_params': {'dim': 128, 'dataset_name': 'sift-128-euclidean', 'ni_per': 10000}, 'collection_params': {'other_fields': []}, 'load_params': {'replica_number': 1}, 'search_params': {'top_k': [10], 'nq': [10000], 'search_param': {'ef': [16, 32, 64, 128, 256, 512]}}, 'index_params': {'index_type': 'HNSW', 'index_param': {'M': 16, 'efConstruction': 500}}} (params_check.py:31)
```

server
```
fouramf-cron-1677340800-1-30-5215-etcd-0                          1/1     Running            0                 2m4s    10.104.1.85     4am-node10   <none>           <none>
fouramf-cron-1677340800-1-30-5215-milvus-standalone-7bb5b4k7th7   1/1     Running            0                 2m4s    10.104.9.182    4am-node14   <none>           <none>
fouramf-cron-1677340800-1-30-5215-minio-65676b97d9-rf76l          1/1     Running            0                 2m4s    10.104.9.183    4am-node14   <none>           <none>
```

client log
```
[2023-02-25 16:05:42,049 -  INFO - fouram]: [AccCases] Number of vectors in the collection(fouram_GQVQdauM): 1000000 (accuracy_cases.py:121)
[2023-02-25 16:05:42,138 -  INFO - fouram]: [Base] Describe resource group:__default_resource_group, ResourceGroupInfo:<name:__default_resource_group>,<capacity:1000000>,<num_available_node:1>,<num_loaded_replica:{'fouram_GQVQdauM':1}>,<num_outgoing_node:{}>,<num_incoming_node:{}> (base.py:435)
[2023-02-25 16:05:42,147 -  INFO - fouram]: [Base] Collection fouram_GQVQdauM replicas info - Replica groups:
- Group: <group_id:439704870335283201>, <group_nodes:(1,)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_0_439704869532598276v0>, <shard_leader:1>, <shard_nodes:[1, 1]>, Shard: <channel_name:by-dev-rootcoord-dml_1_439704869532598276v1>, <shard_leader:1>, <shard_nodes:[1, 1]>]> (base.py:439)
[2023-02-25 16:05:42,237 -  INFO - fouram]: [Base] Parser segment info: 
{'count_segment': 1,
 'max_segment': 239384,
 'min_segment': 239384,
 'avg_segment': 239384.0,
 'std_segment': 0.0,
 'shards_num': 2,
 'truncated_avg_segment': nan,
 'truncated_std_segment': nan,
 'top_percentile': [{'TP_10': 239384.0},
                    {'TP_20': 239384.0},
                    {'TP_30': 239384.0},
                    {'TP_40': 239384.0},
                    {'TP_50': 239384.0},
                    {'TP_60': 239384.0},
                    {'TP_70': 239384.0},
                    {'TP_80': 239384.0},
                    {'TP_90': 239384.0}]} (base.py:446)
[2023-02-25 16:05:42,237 -  INFO - fouram]: [PerfTemplate] Actual parameters used: {'dataset_params': {'dim': 128, 'dataset_name': 'sift-128-euclidean', 'ni_per': 10000}, 'collection_params': {'other_fields': []}, 'load_params': {'replica_number': 1}, 'search_params': {'top_k': 10, 'nq': 10000, 'search_param': {'ef': 16}, 'expr': None}, 'index_params': {'index_type': 'HNSW', 'index_param': {'M': 16, 'efConstruction': 500}}} (performance_template.py:57)
[2023-02-25 16:05:42,240 -  INFO - fouram]: [AccCases] Params of search: {'expr': None, 'data': array([[  1.,   3.,  11., ...,  42.,  48.,  11.],
       [ 40.,  25.,  11., ...,   3.,  19.,  13.],
       [ 28.,   4.,   3., ...,   2.,  54.,  47.],
       ...,
       [  0.,  15.,  64., ...,   3.,  62., 118.],
       [131.,   2.,   0., ...,   7.,   0.,   0.],
       [ 23.,   0.,   0., ...,  79.,  16.,   4.]], dtype=float32), 'anns_field': 'float_vector', 'param': {'metric_type': 'L2', 'params': {'ef': 16}}, 'limit': 10} (accuracy_cases.py:161)
[2023-02-25 16:05:42,241 -  INFO - fouram]: [Base] Params of search: nq:10000, anns_field:float_vector, param:{'metric_type': 'L2', 'params': {'ef': 16}}, limit:10, expr:"None", kwargs:{} (base.py:317)
[2023-02-25 16:10:42,390 - ERROR - fouram]: RPC error: [search], <MilvusException: (code=1, message=<_InactiveRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1677341442.389430284","description":"Error received from peer ipv4:10.255.197.197:19530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>)>, <Time:{'RPC start': '2023-02-25 16:05:42.241618', 'RPC error': '2023-02-25 16:10:42.389932'}> (decorators.py:108)
[2023-02-25 16:10:42,392 - ERROR - fouram]: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 472, in search
    return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)
    
    
  ……
  
  [2023-02-25 16:11:07,064 -  INFO - fouram]: [Base] Params of search: nq:10000, anns_field:float_vector, param:{'metric_type': 'L2', 'params': {'ef': 32}}, limit:10, expr:"None", kwargs:{} (base.py:317)
[2023-02-25 16:11:23,068 - ERROR - fouram]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:
attempt #1:code: UnexpectedError, error: fail to Search, QueryNode ID=1, reason=stream operation failed: [UnexpectedError] Assert "fields_data_.find(field_id) != fields_data_.end()" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/InsertRecord.h:264
 => Cannot find field_data with field_id: 100
attempt #2:context canceled
)>, <Time:{'RPC start': '2023-02-25 16:11:07.065956', 'RPC error': '2023-02-25 16:11:23.068831'}> (decorators.py:108)
[2023-02-25 16:11:23,069 - ERROR - fouram]: Traceback (most recent call last):
  File "/src/fouram/client/util/api_request.py", line 33, in inner_wrapper
    res = func(*args, **kwargs)
  File "/src/fouram/client/util/api_request.py", line 70, in api_request
  
  ……
  
  [2023-02-25 16:11:23,069 - ERROR - fouram]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:
attempt #1:code: UnexpectedError, error: fail to Search, QueryNode ID=1, reason=stream operation failed: [UnexpectedError] Assert "fields_data_.find(field_id) != fields_data_.end()" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/InsertRecord.h:264
 => Cannot find field_data with field_id: 100
attempt #2:context canceled
)> (api_request.py:49)
[2023-02-25 16:11:23,069 - ERROR - fouram]: [CheckFunc] search request check failed, response:<MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:
attempt #1:code: UnexpectedError, error: fail to Search, QueryNode ID=1, reason=stream operation failed: [UnexpectedError] Assert "fields_data_.find(field_id) != fields_data_.end()" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/InsertRecord.h:264
 => Cannot find field_data with field_id: 100
attempt #2:context canceled
)> (func_check.py:48)
[2023-02-25 16:11:23,069 - ERROR - fouram]: [AccCases] Search raise error:  (accuracy_cases.py:192)
[2023-02-25 16:11:23,070 -  INFO - fouram]: [PerfTemplate] Actual parameters used: {'dataset_params': {'dim': 128, 'dataset_name': 'sift-128-euclidean', 'ni_per': 10000}, 'collection_params': {'other_fields': []}, 'load_params': {'replica_number': 1}, 'search_params': {'top_k': 10, 'nq': 10000, 'search_param': {'ef': 64}, 'expr': None}, 'index_params': {'index_type': 'HNSW', 'index_param': {'M': 16, 'efConstruction': 500}}} (performance_template.py:57)
[2023-02-25 16:11:23,072 -  INFO - fouram]: [AccCases] Params of search: {'expr': None, 'data': array([[  1.,   3.,  11., ...,  42.,  48.,  11.],
  
```

### Steps To Reproduce

```markdown
1. create a collection or use an existing collection
        2. insert training dataset
        3. flush collection
        4. clean index and build hnsw index
        5. load collection
        6. search with different parameters  ==> raise error 
        7. clean all collections or not
```

### Anything else?

test_recall_sift_hnsw_standalone
```
    @pytest.mark.recall
    @pytest.mark.parametrize("deploy_mode", [STANDALONE])
    def test_recall_sift_hnsw_standalone(self, input_params: InputParamsBase, deploy_mode):
        """
        :test steps:
            1. serial search and calculation of RT and recall
        """
        self.serial_template(input_params=input_params, cpu=dp.default_cpu, mem=dp.default_mem, deploy_mode=deploy_mode,
                             case_callable_obj=AccCases().scene_recall,
                             default_case_params=AccParams().sift_128_euclidean_hnsw())
    def sift_128_euclidean_hnsw(self, dataset_name=pn.AccDatasetsName.sift_128_euclidean,
                                index_type=pn.IndexTypeName.HNSW, m=16, ef_construction=500, ef=None):
        index_param = {"M": m,
                       "efConstruction": ef_construction}

        ef = [16, 32, 64, 128, 256, 512] if ef is None else ef
        search_param = {"ef": ef}

        default_params = self.base(dataset_name=dataset_name, index_type=index_type, index_param=index_param,
                                   search_param=search_param)
        log.debug("[AccParams] Default params of sift_128_euclidean_hnsw: {0}".format(default_params))
        return default_params
```

**Comment by yanliang567** [comment]
looks like a timeout, but the error msg is odd and different.

/assign @jiaoew1991 
/unassign

**Comment by yah01** [comment]
Looks like https://github.com/milvus-io/milvus/pull/22429 would fix this

**Comment by yah01** [comment]
plz help check with #22429

**Comment by elstic** [comment]
After verification, this issue has been fixed

**Comment by elstic** [comment]
Please take a look at this similar question: https://github.com/milvus-io/milvus/issues/22538

**Comment by elstic** [comment]
Please take a look at this similar question: https://github.com/milvus-io/milvus/issues/22345#issuecomment-1451704543
