### ISSUE TITLE
[Bug]: [benchmark]Milvus restarted 2 times and load failed

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#22457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230227-8dd1add3
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):-2.3.0.dev34
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task: fouramf-stable-1677524400, id : 7
case_name: test_concurrent_locust_hnsw_compaction_standalone

server
```
NAME                                                              READY   STATUS              RESTARTS           AGE     IP              NODE         NOMINATED NODE   READINESS GATES
fouramf-stable-1677524400-7-etcd-0                                1/1     Running             0                  5h2m    10.104.1.251    4am-node10   <none>           <none>
fouramf-stable-1677524400-7-milvus-standalone-6b748b7f4c-f6pm5    1/1     Running             2 (4h36m ago)      5h2m    10.104.4.237    4am-node11   <none>           <none>
fouramf-stable-1677524400-7-minio-59d9c596c-42msj                 1/1     Running             0                  5h2m    10.104.1.250    4am-node10   <none>           <none> (cli_client.py:130)
```

client 
```
[2023-02-27 19:27:30,006 - WARNING - fouram]: [93m[get_flush_state] retry:8, cost: 21.87s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (decorators.py:71)
[2023-02-27 19:27:30,006 - WARNING - fouram]: [93m[get_flush_state] retry:8, cost: 21.87s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (decorators.py:71)
[2023-02-27 19:27:30,006 - WARNING - fouram]: [93m[get_flush_state] retry:8, cost: 21.87s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses>[0m (decorators.py:71)
[2023-02-27 19:27:35,472 -  INFO - fouram]:  Name                                                                              # reqs      # fails  |     Avg     Min     Max  Median  |   req/s failures/s (stats.py:724)
[2023-02-27 19:27:35,473 -  INFO - fouram]: ---------------------------------------------------------------------------------------------------------------------------------------------------------------- (stats.py:728)
[2023-02-27 19:27:35,473 -  INFO - fouram]:  grpc load                                                                           5261     0(0.00%)  |     533       2   19350     220  |    4.00    0.00 (stats.py:731)
[2023-02-27 19:27:35,473 -  INFO - fouram]:  grpc query                                                                         52355     0(0.00%)  |      35       1    1402      29  |   37.90    0.00 (stats.py:731)
[2023-02-27 19:27:35,473 -  INFO - fouram]:  grpc scene_insert_delete_flush                                                      5204     0(0.00%)  |    4118    2322  297130    2800  |    2.80    0.00 (stats.py:731)
[2023-02-27 19:27:35,473 -  INFO - fouram]:  grpc search                                                                       104473     0(0.00%)  |      27       3    1494      21  |   79.50    0.00 (stats.py:731)
[2023-02-27 19:27:35,473 -  INFO - fouram]: ---------------------------------------------------------------------------------------------------------------------------------------------------------------- (stats.py:732)
[2023-02-27 19:27:35,473 -  INFO - fouram]:  Aggregated                                                                        167293     0(0.00%)  |     173       1  297130      25  |  124.20    0.00 (stats.py:733)
[2023-02-27 19:27:35,473 -  INFO - fouram]:  (stats.py:734)
[2023-02-27 19:27:35,473 -  INFO - fouram]: Response time percentiles (approximated) (stats.py:738)
[2023-02-27 19:27:35,474 -  INFO - fouram]:  Type     Name                                                                                  50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100% # reqs (stats.py:740)
[2023-02-27 19:27:35,474 -  INFO - fouram]: --------|--------------------------------------------------------------------------------|---------|------|------|------|------|------|------|------|------|------|------|------| (stats.py:750)
[2023-02-27 19:27:35,474 -  INFO - fouram]:  grpc     load                                                                                  220    420    670    880   1500   1900   2300   2800  14000  19000  19000   5261 (stats.py:754)
[2023-02-27 19:27:35,474 -  INFO - fouram]:  grpc     query                                                                                  29     38     45     50     66     85    110    140    400   1200   1400  52355 (stats.py:754)
[2023-02-27 19:27:35,474 -  INFO - fouram]:  grpc     scene_insert_delete_flush                                                            2800   3000   3100   3300   3800   4200   4700   5400 293000 297000 297000   5204 (stats.py:754)
[2023-02-27 19:27:35,475 -  INFO - fouram]:  grpc     search                                                                                 21     28     33     37     50     66     90    110    300    910   1500 104473 (stats.py:754)
[2023-02-27 19:27:35,475 -  INFO - fouram]: --------|--------------------------------------------------------------------------------|---------|------|------|------|------|------|------|------|------|------|------|------| (stats.py:755)
[2023-02-27 19:27:35,475 -  INFO - fouram]:  None     Aggregated                                                                             25     34     41     47     75    200   2600   3100   4600 281000 297000 167293 (stats.py:758)
[2023-02-27 19:27:35,475 -  INFO - fouram]:  (stats.py:759)
[2023-02-27 19:27:51,725 - ERROR - fouram]: RPC error: [load_collection], <MilvusUnavailableException: (code=1, message=server Unavailable: Retry timeout: 30s)>, <Time:{'RPC start': '2023-02-27 19:27:18.148931', 'RPC error': '2023-02-27 19:27:51.725633'}> (decorators.py:108)
[2023-02-27 19:27:51,727 - ERROR - fouram]: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 659, in load_collection
    response = rf.result()
```

grafana:
![image](https://user-images.githubusercontent.com/48523564/221743380-9afca6fd-ce8d-4ee6-8e55-3332ee6b46df.png)

### Steps To Reproduce

```markdown
1. create a collection or use an existing collection
        2. build hnsw index on vector column
        3. insert a certain  number of vectors
        4. flush collection
        5. build index on vector column with the same parameters
        6. build index on on scalars column or not
        7. count the total number of rows
        8. load collection
        9. perform concurrent operations
        10. clean all collections or not
```

### Anything else?

server and config:
```
 {'server': {'deploy_tool': 'helm',
            'deploy_mode': 'standalone',
            'config_name': 'standalone_8c16m',
            'config': {'standalone': {'resources': {'limits': {'cpu': '8.0',
                                                               'memory': '16Gi'},
                                                    'requests': {'cpu': '5.0',
                                                                 'memory': '9Gi'}},
                                      'persistence': {'persistentVolumeClaim': {'storageClass': 'local-path'}}},
                       'cluster': {'enabled': False},
                       'etcd': {'replicaCount': 1,
                                'global': {'storageClass': 'local-path'},
                                'metrics': {'enabled': True,
                                            'podMonitor': {'enabled': True}}},
                       'minio': {'mode': 'standalone',
                                 'persistence': {'storageClass': 'local-path'},
                                 'metrics': {'serviceMonitor': {'enabled': False}}},
                       'pulsar': {'enabled': False},
                       'metrics': {'serviceMonitor': {'enabled': True}},
                       'image': {'all': {'repository': 'harbor.milvus.io/dockerhub/milvusdb/milvus',
                                         'tag': '2.2.0-20230227-8dd1add3'}}},
            'host': 'fouramf-stable-1677524400-7-milvus.qa-milvus.svc.cluster.local'},
 'client': {'test_case_type': 'ConcurrentClientBase',
            'test_case_name': 'test_concurrent_locust_hnsw_compaction_standalone',
            'test_case_params': {'dataset_params': {'dim': 128,
                                                    'dataset_name': 'sift',
                                                    'dataset_size': 100000,
                                                    'ni_per': 50000,
                                                    'metric_type': 'L2'},
                                 'collection_params': {'other_fields': ['float_1']},
                                 'load_params': {},
                                 'search_params': {},
                                 'resource_groups_params': {'reset': False},
                                 'index_params': {'index_type': 'HNSW',
                                                  'index_param': {'M': 8,
                                                                  'efConstruction': 200}},
                                 'concurrent_params': {'concurrent_number': 20,
                                                       'during_time': '5h',
                                                       'interval': 20,
                                                       'spawn_rate': None},
                                 'concurrent_tasks': [{'type': 'search',
                                                       'weight': 20,
                                                       'params': {'nq': 10,
                                                                  'top_k': 10,
                                                                  'search_param': {'ef': 16},
                                                                  'expr': {'float_1': {'GT': -1.0,
                                                                                       'LT': 50000.0}},
                                                                  'guarantee_timestamp': None,
                                                                  'timeout': 60,
                                                                  'random_data': True}},
                                                      {'type': 'query',
                                                       'weight': 10,
                                                       'params': {'ids': [0,
                                                                          1,
                                                                          2,
                                                                          3,
                                                                          4,
                                                                          5,
                                                                          6,
                                                                          7,
                                                                          8,
                                                                          9],
                                                                  'expr': None,
                                                                  'timeout': 60}},
                                                      {'type': 'load',
                                                       'weight': 1,
                                                       'params': {'replica_number': 1,
                                                                  'timeout': 30}},
                                                      {'type': 'scene_insert_delete_flush',
                                                       'weight': 1,
                                                       'params': {'insert_length': 1,
                                                                  'delete_length': 1,
                                                                  'random_id': True,
                                                                  'random_vector': True,
                                                                  'varchar_filled': True}}]},
            'run_id': 2023022744392732,
            'datetime': '2023-02-27 19:00:39.860222',
            'client_version': '2.2.3'},
```
test_concurrent_locust_hnsw_compaction_standalone
```
    @pytest.mark.locust
    @pytest.mark.parametrize("deploy_mode", [STANDALONE])
    def test_concurrent_locust_hnsw_compaction_standalone(self, input_params: InputParamsBase, deploy_mode):
        """
        :test steps:
            1. concurrent test and calculation of RT and QPS
        """
        concurrent_tasks = [ConcurrentParams.params_search(weight=20, nq=10, top_k=10, search_param={"ef": 16},
                                                           expr=eval("{'float_1': {'GT': -1.0, 'LT': 100000 * 0.5}}")),
                            ConcurrentParams.params_query(weight=10, ids=[i for i in range(10)]),
                            ConcurrentParams.params_load(weight=1),
                            ConcurrentParams.params_scene_insert_delete_flush(weight=1, insert_length=1,
                                                                              delete_length=1, random_id=True,
                                                                              random_vector=True, varchar_filled=True)]
        default_case_params = ConcurrentParams().params_scene_concurrent(concurrent_tasks, concurrent_number=[20],
                                                                         during_time="5h", interval=20,
                                                                         dataset_size="10w", other_fields=["float_1"],
                                                                         **cdp.DefaultIndexParams.HNSW)
        self.concurrency_template(input_params=input_params, cpu=dp.default_cpu, mem=dp.default_mem,
                                  deploy_mode=deploy_mode, old_version_format=False, sync_report=True,
                                  case_callable_obj=ConcurrentClientBase().scene_concurrent_locust,
                                  default_case_params=default_case_params)
```

**Comment by wayblink** [comment]
[2023/02/27 19:27:18.578 +00:00] [WARN] [datanode/flush_manager.go:853] ["failed to SaveBinlogPaths"] ["segment ID"=439753155847352862] [error="All attempts results:\nattempt #1:segment 439753155847352862 not found\nattempt #2:segment 439753155847352862 not found\nattempt #3:segment 439753155847352862 not found\nattempt #4:segment 439753155847352862 not found\nattempt #5:segment 439753155847352862 not found\nattempt #6:segment 439753155847352862 not found\nattempt #7:segment 439753155847352862 not found\nattempt #8:segment 439753155847352862 not found\nattempt #9:segment 439753155847352862 not found\nattempt #10:segment 439753155847352862 not found\nattempt #11:segment 439753155847352862 not found\n"]

**Comment by aoiasd** [comment]
> /assign @aoiasd
> 
> Please help verify if it is related to former issues #22142

No, compaction which merge to this segment update result success, 
```
[2023/02/27 19:24:59.422 +00:00] [INFO] [datacoord/compaction.go:294] ["handleCompactionResult: success to handle merge compaction result"] [planID=439753155847335234]
```

it may related to https://github.com/milvus-io/milvus/issues/22502, @yah01

**Comment by soothing-rain** [comment]
/assign @yah01 

WDYT?

**Comment by yah01** [comment]
> /assign @yah01
> 
> WDYT?

It's the same as #22502, as the compaction produces an empty segment then the DataNode failed to sync the binlogs to DataCoord (segment not found), and then DataNode panics

**Comment by yah01** [comment]
/assign @elstic 
plz check with #22551
