### ISSUE TITLE
[Bug]: Search failed with error `_InactiveRpcError of RPC that terminated with` after reinstallation and upgrade

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#22469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.2.2 --> 2.2.0-20230227-8dd1add3
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

collection name:sift_128_euclidean_IVF_FLAT
![image](https://user-images.githubusercontent.com/12268675/221775513-bdeec00a-a5c0-42d9-b0fb-996997d9e6b4.png)

```
[2023-02-27T13:07:17.881Z] + python3 scripts/second_recall_test.py --host 10.101.56.111

[2023-02-27T13:07:18.804Z] 2023-02-27 13:07:18.774 | INFO     | __main__:search_test:53 - recall test for index type IVF_FLAT

[2023-02-27T13:07:19.363Z] 2023-02-27 13:07:19.194 | INFO     | __main__:search_test:63 - 

[2023-02-27T13:07:19.363Z] Search...

[2023-02-27T13:10:40.739Z] RPC error: [search], <MilvusException: (code=1, message=<_InactiveRpcError of RPC that terminated with:

[2023-02-27T13:10:40.739Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2023-02-27T13:10:40.739Z] 	details = "Deadline Exceeded"

[2023-02-27T13:10:40.739Z] 	debug_error_string = "{"created":"@1677503439.401022831","description":"Error received from peer ipv4:10.101.56.111:19530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"Deadline Exceeded","grpc_status":4}"

[2023-02-27T13:10:40.739Z] >)>, <Time:{'RPC start': '2023-02-27 13:07:19.194812', 'RPC error': '2023-02-27 13:10:39.402336'}>

[2023-02-27T13:10:40.739Z] Traceback (most recent call last):

[2023-02-27T13:10:40.739Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-02-27T13:10:40.739Z]     return func(self, *args, **kwargs)

[2023-02-27T13:10:40.739Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 483, in search

[2023-02-27T13:10:40.739Z]     return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)

[2023-02-27T13:10:40.739Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 452, in _execute_search_requests

[2023-02-27T13:10:40.739Z]     raise pre_err

[2023-02-27T13:10:40.739Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 440, in _execute_search_requests

[2023-02-27T13:10:40.739Z]     response = self._stub.Search(request, timeout=timeout)

[2023-02-27T13:10:40.739Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 946, in __call__

[2023-02-27T13:10:40.739Z]     return _end_unary_response_blocking(state, call, False, None)

[2023-02-27T13:10:40.739Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking

[2023-02-27T13:10:40.739Z]     raise _InactiveRpcError(state)

[2023-02-27T13:10:40.739Z] grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:

[2023-02-27T13:10:40.739Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2023-02-27T13:10:40.739Z] 	details = "Deadline Exceeded"

[2023-02-27T13:10:40.739Z] 	debug_error_string = "{"created":"@1677503439.401022831","description":"Error received from peer ipv4:10.101.56.111:19530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"Deadline Exceeded","grpc_status":4}"

[2023-02-27T13:10:40.739Z] >

[2023-02-27T13:10:40.739Z] 

[2023-02-27T13:10:40.739Z] The above exception was the direct cause of the following exception:

[2023-02-27T13:10:40.739Z] 

[2023-02-27T13:10:40.739Z] Traceback (most recent call last):

[2023-02-27T13:10:40.739Z]   File "scripts/second_recall_test.py", line 103, in <module>

[2023-02-27T13:10:40.739Z]     search_test(host, index_type)

[2023-02-27T13:10:40.739Z]   File "scripts/second_recall_test.py", line 65, in search_test

[2023-02-27T13:10:40.739Z]     res = collection.search(

[2023-02-27T13:10:40.739Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 614, in search

[2023-02-27T13:10:40.739Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,

[2023-02-27T13:10:40.739Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-02-27T13:10:40.739Z]     raise e

[2023-02-27T13:10:40.739Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-02-27T13:10:40.739Z]     return func(*args, **kwargs)

[2023-02-27T13:10:40.739Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-02-27T13:10:40.739Z]     ret = func(self, *args, **kwargs)

[2023-02-27T13:10:40.739Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 58, in handler

[2023-02-27T13:10:40.739Z]     raise MilvusException(message=str(e)) from e

[2023-02-27T13:10:40.739Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=<_InactiveRpcError of RPC that terminated with:

[2023-02-27T13:10:40.739Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2023-02-27T13:10:40.739Z] 	details = "Deadline Exceeded"

[2023-02-27T13:10:40.739Z] 	debug_error_string = "{"created":"@1677503439.401022831","description":"Error received from peer ipv4:10.101.56.111:19530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"Deadline Exceeded","grpc_status":4}"

[2023-02-27T13:10:40.739Z] >)>

script returned exit code 1
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_kafka_for_release_cron/detail/deploy_test_kafka_for_release_cron/428/pipeline
log:

[artifacts-kafka-cluster-upgrade-428-pytest-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/10847293/artifacts-kafka-cluster-upgrade-428-pytest-logs.1.tar.gz)
[artifacts-kafka-cluster-upgrade-428-server-first-deployment-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/10847294/artifacts-kafka-cluster-upgrade-428-server-first-deployment-logs.1.tar.gz)
[artifacts-kafka-cluster-upgrade-428-server-second-deployment-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/10847296/artifacts-kafka-cluster-upgrade-428-server-second-deployment-logs.1.tar.gz)

**Comment by zhuwenxing** [comment]
It reproduced stably,so set it as critical.

**Comment by zhuwenxing** [comment]
duplicate with #22605
