### ISSUE TITLE
[Bug]: Load collection failed after reinstallation with error `collection xxx has not been loaded to memory or load failed`

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#22466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230227-8dd1add3
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):kafka    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2023-02-27T14:05:12.582Z] =========================== short test summary info ============================

[2023-02-27T14:05:12.582Z] FAILED testcases/test_action_second_deployment.py::TestActionSecondDeployment::test_check[deploy_test_index_type_BIN_IVF_FLAT_is_compacted_not_compacted_segment_status_only_growing_is_string_indexed_is_string_indexed_replica_number_0_is_deleted_is_deleted_data_size_3000] - pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection 439746878438281519 has not been loaded to memory or load failed)>

[2023-02-27T14:05:12.582Z] [get_env_variable] failed to get environment variables : 'CI_LOG_PATH', use default path : /tmp/ci_logs

[2023-02-27T14:05:12.582Z] FAILED testcases/test_action_second_deployment.py::TestActionSecondDeployment::test_check[deploy_test_index_type_BIN_IVF_FLAT_is_compacted_is_compacted_segment_status_all_is_string_indexed_is_string_indexed_replica_number_0_is_deleted_is_deleted_data_size_3000] - pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection 439746878438281523 has not been loaded to memory or load failed)>

[2023-02-27T14:05:12.582Z] ================== 2 failed, 32 passed in 3459.86s (0:57:39) ===================

script returned exit code 1
```

```
[2023-02-27T14:05:12.582Z] [2023-02-27 13:07:38 - DEBUG - ci_test]: (api_request)  : [Connections.connect] args: ['default'], kwargs: {'host': '10.101.88.159', 'port': 19530} (api_request.py:56)

[2023-02-27T14:05:12.582Z] [2023-02-27 13:07:38 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)

[2023-02-27T14:05:12.582Z] [2023-02-27 13:12:37 - DEBUG - ci_test]: (api_request)  : [Collection] args: ['deploy_test_index_type_BIN_IVF_FLAT_is_compacted_is_compacted_segment_status_all_is_string_indexed_is_string_indexed_replica_number_0_is_deleted_is_deleted_data_size_3000', None, 'default', 2], kwargs: {'consistency_level': 'Strong'} (api_request.py:56)

[2023-02-27T14:05:12.582Z] [2023-02-27 13:12:37 - DEBUG - ci_test]: (api_response) : <Collection>:

[2023-02-27T14:05:12.582Z] -------------

[2023-02-27T14:05:12.582Z] <name>: deploy_test_index_type_BIN_IVF_FLAT_is_compacted_is_compacted_segment_status_all_is_string_indexed_is_string_indexed_replica_number_0_is_deleted_is_deleted_data_size_3000

[2023-02-27T14:05:12.582Z] <partitions>: [{"name": "_default", "collection_name": "deploy_test_index_type_BIN_IVF_FLAT_i......  (api_request.py:31)

[2023-02-27T14:05:12.582Z] [2023-02-27 13:12:37 - DEBUG - ci_test]: (api_request)  : [wait_for_loading_complete] args: ['deploy_test_index_type_BIN_IVF_FLAT_is_compacted_is_compacted_segment_status_all_is_string_indexed_is_string_indexed_replica_number_0_is_deleted_is_deleted_data_size_3000', None, 20, 'default'], kwargs: {} (api_request.py:56)

[2023-02-27T14:05:12.582Z] [2023-02-27 13:12:37 - ERROR - pymilvus.decorators]: RPC error: [get_loading_progress], <MilvusException: (code=1, message=collection 439746878438281523 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2023-02-27 13:12:37.979499', 'RPC error': '2023-02-27 13:12:37.980447'}> (decorators.py:108)

[2023-02-27T14:05:12.582Z] [2023-02-27 13:12:37 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=collection 439746878438281523 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2023-02-27 13:12:37.979483', 'RPC error': '2023-02-27 13:12:37.980621'}> (decorators.py:108)

[2023-02-27T14:05:12.582Z] [2023-02-27 13:12:37 - ERROR - ci_test]: Traceback (most recent call last):

[2023-02-27T14:05:12.582Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2023-02-27T14:05:12.582Z]     res = func(*args, **_kwargs)

[2023-02-27T14:05:12.582Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2023-02-27T14:05:12.582Z]     return func(*arg, **kwargs)

[2023-02-27T14:05:12.582Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/utility.py", line 277, in wait_for_loading_complete

[2023-02-27T14:05:12.582Z]     return _get_connection(using).wait_for_loading_collection(collection_name, timeout=timeout)

[2023-02-27T14:05:12.582Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-02-27T14:05:12.582Z]     raise e

[2023-02-27T14:05:12.582Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-02-27T14:05:12.582Z]     return func(*args, **kwargs)

[2023-02-27T14:05:12.582Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-02-27T14:05:12.582Z]     ret = func(self, *args, **kwargs)

[2023-02-27T14:05:12.582Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-02-27T14:05:12.582Z]     raise e

[2023-02-27T14:05:12.582Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-02-27T14:05:12.582Z]     return func(self, *args, **kwargs)

[2023-02-27T14:05:12.582Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 693, in wait_for_loading_collection

[2023-02-27T14:05:12.582Z]     progress = self.get_loading_progress(collection_name, timeout=timeout)

[2023-02-27T14:05:12.582Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-02-27T14:05:12.582Z]     raise e

[2023-02-27T14:05:12.582Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-02-27T14:05:12.582Z]     return func(*args, **kwargs)

[2023-02-27T14:05:12.582Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-02-27T14:05:12.582Z]     ret = func(self, *args, **kwargs)

[2023-02-27T14:05:12.582Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-02-27T14:05:12.582Z]     raise e

[2023-02-27T14:05:12.582Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-02-27T14:05:12.582Z]     return func(self, *args, **kwargs)

[2023-02-27T14:05:12.582Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 760, in get_loading_progress

[2023-02-27T14:05:12.582Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2023-02-27T14:05:12.582Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection 439746878438281523 has not been loaded to memory or load failed)>

[2023-02-27T14:05:12.582Z]  (api_request.py:39)

[2023-02-27T14:05:12.582Z] [2023-02-27 13:12:37 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=collection 439746878438281523 has not been loaded to memory or load failed)> (api_request.py:40)

[2023-02-27T14:05:12.582Z] [2023-02-27 13:12:37 - ERROR - ci_test]:  (test_action_second_deployment.py:108)

[2023-02-27T14:05:12.582Z] [2023-02-27 13:12:37 - ERROR - pymilvus.decorators]: RPC error: [get_replicas], <MilvusException: (code=15, message=failed to get replicas, collection not loaded)>, <Time:{'RPC start': '2023-02-27 13:12:37.982614', 'RPC error': '2023-02-27 13:12:37.984568'}> (decorators.py:108)

[2023-02-27T14:05:12.582Z] [2023-02-27 13:12:37 - ERROR - ci_test]: <MilvusException: (code=15, message=failed to get replicas, collection not loaded)> (test_action_second_deployment.py:114)

[2023-02-27T14:05:12.582Z] [2023-02-27 13:12:37 - INFO - ci_test]: collection deploy_test_index_type_BIN_IVF_FLAT_is_compacted_is_compacted_segment_status_all_is_string_indexed_is_string_indexed_replica_number_0_is_deleted_is_deleted_data_size_3000 has 0 replicas (test_action_second_deployment.py:117)

[2023-02-27T14:05:12.582Z] [2023-02-27 13:12:38 - INFO - ci_test]: index info: [{'collection': 'deploy_test_index_type_BIN_IVF_FLAT_is_compacted_is_compacted_segment_status_all_is_string_indexed_is_string_indexed_replica_number_0_is_deleted_is_deleted_data_size_3000', 'field': 'binary_vector', 'index_name': '_default_idx_103', 'index_param': {'index_type': 'BIN_IVF_FLAT', 'params': {'nlist': 128}, 'metric_type': 'HAMMING'}}, {'collection': 'deploy_test_index_type_BIN_IVF_FLAT_is_compacted_is_compacted_segment_status_all_is_string_indexed_is_string_indexed_replica_number_0_is_deleted_is_deleted_data_size_3000', 'field': 'varchar', 'index_name': '_default_string_idx', 'index_param': {'index_type': 'Trie'}}] (test_action_second_deployment.py:58)

[2023-02-27T14:05:12.582Z] [2023-02-27 13:12:38 - INFO - ci_test]: current index param is {'index_type': 'BIN_IVF_FLAT', 'params': {'nlist': 128}, 'metric_type': 'HAMMING'}, passed in param is {'index_type': 'BIN_IVF_FLAT', 'params': {'nlist': 128}, 'metric_type': 'HAMMING'} (test_action_second_deployment.py:61)

[2023-02-27T14:05:12.582Z] [2023-02-27 13:12:38 - INFO - ci_test]: current index name is _default_idx_103, passed in param is _default_idx_103 (test_action_second_deployment.py:63)

[2023-02-27T14:05:12.582Z] [2023-02-27 13:22:40 - ERROR - pymilvus.decorators]: RPC error: [get_loading_progress], <MilvusException: (code=1, message=collection 439746878438281523 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2023-02-27 13:22:40.449776', 'RPC error': '2023-02-27 13:22:40.451140'}> (decorators.py:108)

[2023-02-27T14:05:12.582Z] [2023-02-27 13:22:40 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=collection 439746878438281523 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2023-02-27 13:12:39.589759', 'RPC error': '2023-02-27 13:22:40.451534'}> (decorators.py:108)

[2023-02-27T14:05:12.582Z] [2023-02-27 13:22:40 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=collection 439746878438281523 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2023-02-27 13:12:39.575980', 'RPC error': '2023-02-27 13:22:40.451599'}> (decorators.py:108)
```

### Milvus Log

image tag: 2.2.0-20230227-8dd1add3
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_kafka_for_release_cron/detail/deploy_test_kafka_for_release_cron/425/pipeline
log:

[artifacts-kafka-standalone-reinstall-425-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10847151/artifacts-kafka-standalone-reinstall-425-pytest-logs.tar.gz)

[artifacts-kafka-standalone-reinstall-425-server-first-deployment-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/10847153/artifacts-kafka-standalone-reinstall-425-server-first-deployment-logs.1.tar.gz)

[artifacts-kafka-standalone-reinstall-425-server-second-deployment-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/10847154/artifacts-kafka-standalone-reinstall-425-server-second-deployment-logs.1.tar.gz)

**Comment by smellthemoon** [comment]
has received a flush request in datacoord, but it failed because kafka consume msg failed and timed out. 
<img width="1123" alt="10" src="https://user-images.githubusercontent.com/64083300/221804336-32d8e284-55aa-4c6d-9609-2aa0a45a176b.png">
In rootcoord, create channel task did not succeed.
![11](https://user-images.githubusercontent.com/64083300/221805825-46447ef9-658e-4416-9575-83f9fe0f3bef.png)

**Comment by smellthemoon** [comment]
may related to #22469

**Comment by zhuwenxing** [comment]
It also reproduced in querynode pod kill chaos test
![image](https://user-images.githubusercontent.com/12268675/222038904-5333ecdc-82cd-4f0d-9e3b-183d846cca63.png)

```

[2023-03-01T02:38:13.771Z] [2023-03-01 02:38:13 - INFO - ci_test]: [test][2023-03-01T02:38:13Z] [0.00661443s] e2e__nSKgoQ87 flush -> None (wrapper.py:30)

[2023-03-01T02:38:13.771Z] [2023-03-01 02:38:13 - INFO - ci_test]: assert create collection: 0.05898022651672363, init_entities: 0 (test_e2e.py:24)

[2023-03-01T02:38:14.697Z] [2023-03-01 02:38:14 - INFO - ci_test]: [test][2023-03-01T02:38:13Z] [0.49530299s] e2e__nSKgoQ87 insert -> (insert count: 3000, delete count: 0, upsert count: 0, timestamp: 439782813029629956, success count: 3000, err count: 0) (wrapper.py:30)

[2023-03-01T02:38:14.697Z] [2023-03-01 02:38:14 - INFO - ci_test]: assert insert: 0.49558091163635254 (test_e2e.py:31)

[2023-03-01T02:38:17.963Z] [2023-03-01 02:38:17 - INFO - ci_test]: [test][2023-03-01T02:38:14Z] [3.03124267s] e2e__nSKgoQ87 flush -> None (wrapper.py:30)

[2023-03-01T02:38:17.963Z] [2023-03-01 02:38:17 - INFO - ci_test]: [test][2023-03-01T02:38:17Z] [0.00512770s] e2e__nSKgoQ87 flush -> None (wrapper.py:30)

[2023-03-01T02:38:17.963Z] [2023-03-01 02:38:17 - INFO - ci_test]: [test][2023-03-01T02:38:17Z] [0.00409941s] e2e__nSKgoQ87 flush -> None (wrapper.py:30)

[2023-03-01T02:38:17.963Z] [2023-03-01 02:38:17 - INFO - ci_test]: assert flush: 3.0395522117614746, entities: 3000 (test_e2e.py:41)

[2023-03-01T02:38:18.219Z] [2023-03-01 02:38:17 - INFO - ci_test]: [test][2023-03-01T02:38:17Z] [0.52348445s] e2e__nSKgoQ87 create_index -> Status(code=0, message=) (wrapper.py:30)

[2023-03-01T02:38:22.384Z] [2023-03-01 02:38:22 - INFO - ci_test]: [test][2023-03-01T02:38:17Z] [4.06952832s] e2e__nSKgoQ87 create_index -> Status(code=0, message=) (wrapper.py:30)

[2023-03-01T02:38:22.384Z] [2023-03-01 02:38:22 - INFO - ci_test]: assert index: 4.593698740005493 (test_e2e.py:53)

[2023-03-01T02:40:28.763Z] [2023-03-01 02:40:22 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=wait for loading collection timeout, collection: e2e__nSKgoQ87)>, <Time:{'RPC start': '2023-03-01 02:38:22.081250', 'RPC error': '2023-03-01 02:40:22.494028'}> (decorators.py:108)

[2023-03-01T02:40:28.763Z] [2023-03-01 02:40:22 - WARNING - pymilvus.decorators]: Retry timeout: 120s (decorators.py:79)

[2023-03-01T02:40:28.763Z] [2023-03-01 02:40:22 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: e2e__nSKgoQ87)>, <Time:{'RPC start': '2023-03-01 02:38:22.059392', 'RPC error': '2023-03-01 02:40:22.494855'}> (decorators.py:108)

[2023-03-01T02:40:28.763Z] [2023-03-01 02:40:22 - ERROR - ci_test]: Traceback (most recent call last):

[2023-03-01T02:40:28.763Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-03-01T02:40:28.763Z]     return func(self, *args, **kwargs)

[2023-03-01T02:40:28.763Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 675, in load_collection

[2023-03-01T02:40:28.763Z]     self.wait_for_loading_collection(collection_name, timeout)

[2023-03-01T02:40:28.763Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-03-01T02:40:28.763Z]     raise e

[2023-03-01T02:40:28.763Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-03-01T02:40:28.763Z]     return func(*args, **kwargs)

[2023-03-01T02:40:28.763Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-03-01T02:40:28.764Z]     ret = func(self, *args, **kwargs)

[2023-03-01T02:40:28.764Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-03-01T02:40:28.764Z]     raise e

[2023-03-01T02:40:28.764Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-03-01T02:40:28.764Z]     return func(self, *args, **kwargs)

[2023-03-01T02:40:28.764Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 697, in wait_for_loading_collection

[2023-03-01T02:40:28.764Z]     raise MilvusException(message=f"wait for loading collection timeout, collection: {collection_name}")

[2023-03-01T02:40:28.764Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=wait for loading collection timeout, collection: e2e__nSKgoQ87)>

[2023-03-01T02:40:28.764Z] 

[2023-03-01T02:40:28.764Z] The above exception was the direct cause of the following exception:

[2023-03-01T02:40:28.764Z] 

[2023-03-01T02:40:28.764Z] Traceback (most recent call last):

[2023-03-01T02:40:28.764Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2023-03-01T02:40:28.764Z]     res = func(*args, **_kwargs)

[2023-03-01T02:40:28.764Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2023-03-01T02:40:28.764Z]     return func(*arg, **kwargs)

[2023-03-01T02:40:28.764Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 366, in load

[2023-03-01T02:40:28.764Z]     conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)

[2023-03-01T02:40:28.764Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-03-01T02:40:28.764Z]     raise e

[2023-03-01T02:40:28.764Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-03-01T02:40:28.764Z]     return func(*args, **kwargs)

[2023-03-01T02:40:28.764Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-03-01T02:40:28.764Z]     ret = func(self, *args, **kwargs)

[2023-03-01T02:40:28.764Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 80, in handler

[2023-03-01T02:40:28.764Z]     raise MilvusException(e.code, f"{timeout_msg}, message={e.message}") from e

[2023-03-01T02:40:28.764Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: e2e__nSKgoQ87)>

[2023-03-01T02:40:28.764Z]  (api_request.py:39)

[2023-03-01T02:40:28.764Z] [2023-03-01 02:40:22 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: e2e__nSKgoQ87)> (api_request.py:40)

[2023-03-01T02:40:28.764Z] FAILED
```

log:

[artifacts-querynode-pod-kill-2304-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10856905/artifacts-querynode-pod-kill-2304-server-logs.tar.gz)
[artifacts-querynode-pod-kill-2304-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10856906/artifacts-querynode-pod-kill-2304-pytest-logs.tar.gz)

**Comment by smellthemoon** [comment]
help check it @zhuwenxing , related pr has merged.

**Comment by zhuwenxing** [comment]
It was blocked by https://github.com/milvus-io/milvus/issues/22566

**Comment by zhuwenxing** [comment]
Not reproduced in 2.2.0-20230310-1642f7b7
