### ISSUE TITLE
[Bug]: [benchmark][RG][replicas][pod-failure] queryCoord panics after queryNode injection pod failure

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#22467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-20230227-63c57db2
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.0.dev38
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

**panic: runtime error: integer divide by zero**

server:
```
[2023-02-27 15:05:20,854 -  INFO - fouram]: [Base] Deploy initial state: 
I0227 08:17:07.656204     295 request.go:665] Waited for 1.173783553s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.local/api/v1?timeout=32s
NAME                                                              READY   STATUS             RESTARTS          AGE     IP              NODE         NOMINATED NODE   READINESS GATES
fouramf-xspmg-64-5064-etcd-0                                      1/1     Running            0                 5m58s   10.104.1.70     4am-node10   <none>           <none>
fouramf-xspmg-64-5064-etcd-1                                      1/1     Running            0                 5m58s   10.104.4.52     4am-node11   <none>           <none>
fouramf-xspmg-64-5064-etcd-2                                      1/1     Running            0                 5m57s   10.104.6.94     4am-node13   <none>           <none>
fouramf-xspmg-64-5064-milvus-datacoord-54f6c8cf87-85r5p           1/1     Running            1 (117s ago)      5m58s   10.104.4.23     4am-node11   <none>           <none>
fouramf-xspmg-64-5064-milvus-datanode-87dd6ccd7-k4bm7             1/1     Running            1 (116s ago)      5m58s   10.104.1.53     4am-node10   <none>           <none>
fouramf-xspmg-64-5064-milvus-indexcoord-659b6cd789-x22cp          1/1     Running            1 (116s ago)      5m58s   10.104.1.54     4am-node10   <none>           <none>
fouramf-xspmg-64-5064-milvus-indexnode-7cbd754c84-rjs5r           1/1     Running            0                 5m58s   10.104.1.50     4am-node10   <none>           <none>
fouramf-xspmg-64-5064-milvus-proxy-9576fb8c5-9ftcq                1/1     Running            1 (116s ago)      5m58s   10.104.1.55     4am-node10   <none>           <none>
fouramf-xspmg-64-5064-milvus-querycoord-54dfb9c58-8vqfj           1/1     Running            1 (116s ago)      5m58s   10.104.1.56     4am-node10   <none>           <none>
fouramf-xspmg-64-5064-milvus-querynode-6b56b9f5c8-bqwjz           1/1     Running            0                 5m58s   10.104.1.51     4am-node10   <none>           <none>
fouramf-xspmg-64-5064-milvus-querynode-6b56b9f5c8-bsm48           1/1     Running            0                 5m58s   10.104.6.75     4am-node13   <none>           <none>
fouramf-xspmg-64-5064-milvus-querynode-6b56b9f5c8-tbjhg           1/1     Running            0                 5m58s   10.104.4.22     4am-node11   <none>           <none>
fouramf-xspmg-64-5064-milvus-rootcoord-79fd94d8d6-h5rdz           1/1     Running            1 (117s ago)      5m58s   10.104.1.49     4am-node10   <none>           <none>
fouramf-xspmg-64-5064-minio-0                                     1/1     Running            0                 5m58s   10.104.4.39     4am-node11   <none>           <none>
fouramf-xspmg-64-5064-minio-1                                     1/1     Running            0                 5m58s   10.104.1.67     4am-node10   <none>           <none>
fouramf-xspmg-64-5064-minio-2                                     1/1     Running            0                 5m58s   10.104.6.89     4am-node13   <none>           <none>
fouramf-xspmg-64-5064-minio-3                                     1/1     Running            0                 5m58s   10.104.5.123    4am-node12   <none>           <none>
fouramf-xspmg-64-5064-pulsar-bookie-0                             1/1     Running            0                 5m58s   10.104.4.40     4am-node11   <none>           <none>
fouramf-xspmg-64-5064-pulsar-bookie-1                             1/1     Running            0                 5m58s   10.104.1.73     4am-node10   <none>           <none>
fouramf-xspmg-64-5064-pulsar-bookie-2                             1/1     Running            0                 5m57s   10.104.6.95     4am-node13   <none>           <none>
fouramf-xspmg-64-5064-pulsar-bookie-init-684lb                    0/1     Completed          0                 5m58s   10.104.4.21     4am-node11   <none>           <none>
fouramf-xspmg-64-5064-pulsar-broker-0                             1/1     Running            0                 5m58s   10.104.1.57     4am-node10   <none>           <none>
fouramf-xspmg-64-5064-pulsar-proxy-0                              1/1     Running            0                 5m58s   10.104.4.24     4am-node11   <none>           <none>
fouramf-xspmg-64-5064-pulsar-pulsar-init-x9zmq                    0/1     Completed          0                 5m58s   10.104.4.19     4am-node11   <none>           <none>
fouramf-xspmg-64-5064-pulsar-recovery-0                           1/1     Running            0                 5m58s   10.104.1.58     4am-node10   <none>           <none>
fouramf-xspmg-64-5064-pulsar-zookeeper-0                          1/1     Running            0                 5m58s   10.104.1.69     4am-node10   <none>           <none>
fouramf-xspmg-64-5064-pulsar-zookeeper-1                          1/1     Running            0                 5m1s    10.104.6.103    4am-node13   <none>           <none>
fouramf-xspmg-64-5064-pulsar-zookeeper-2                          1/1     Running            0                 4m7s    10.104.9.42     4am-node14   <none>           <none> (base.py:171)
[2023-02-27 15:05:20,854 -  INFO - fouram]: [Cmd Exe]  kubectl get pods  -n qa-milvus  -o wide | grep -E 'STATUS|fouramf-xspmg-64-5064'  (util_cmd.py:14)
[2023-02-27 15:05:28,055 -  INFO - fouram]: [CliClient] pod details of release(fouramf-xspmg-64-5064): 
 I0227 15:05:22.131442     400 request.go:665] Waited for 1.154096356s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.local/apis/networking.k8s.io/v1?timeout=32s
NAME                                                              READY   STATUS              RESTARTS           AGE     IP             NODE         NOMINATED NODE   READINESS GATES
fouramf-xspmg-64-5064-etcd-0                                      1/1     Running             0                  6h54m   10.104.1.70    4am-node10   <none>           <none>
fouramf-xspmg-64-5064-etcd-1                                      1/1     Running             0                  6h54m   10.104.4.52    4am-node11   <none>           <none>
fouramf-xspmg-64-5064-etcd-2                                      1/1     Running             0                  6h54m   10.104.6.94    4am-node13   <none>           <none>
fouramf-xspmg-64-5064-milvus-datacoord-54f6c8cf87-85r5p           1/1     Running             1 (6h50m ago)      6h54m   10.104.4.23    4am-node11   <none>           <none>
fouramf-xspmg-64-5064-milvus-datanode-87dd6ccd7-k4bm7             1/1     Running             1 (6h50m ago)      6h54m   10.104.1.53    4am-node10   <none>           <none>
fouramf-xspmg-64-5064-milvus-indexcoord-659b6cd789-x22cp          1/1     Running             1 (6h50m ago)      6h54m   10.104.1.54    4am-node10   <none>           <none>
fouramf-xspmg-64-5064-milvus-indexnode-7cbd754c84-rjs5r           1/1     Running             0                  6h54m   10.104.1.50    4am-node10   <none>           <none>
fouramf-xspmg-64-5064-milvus-proxy-9576fb8c5-9ftcq                1/1     Running             1 (6h50m ago)      6h54m   10.104.1.55    4am-node10   <none>           <none>
fouramf-xspmg-64-5064-milvus-querycoord-54dfb9c58-8vqfj           1/1     Running             2 (4h50m ago)      6h54m   10.104.1.56    4am-node10   <none>           <none>
fouramf-xspmg-64-5064-milvus-querynode-6b56b9f5c8-bqwjz           1/1     Running             0                  6h54m   10.104.1.51    4am-node10   <none>           <none>
fouramf-xspmg-64-5064-milvus-querynode-6b56b9f5c8-bsm48           1/1     Running             0                  6h54m   10.104.6.75    4am-node13   <none>           <none>
fouramf-xspmg-64-5064-milvus-querynode-6b56b9f5c8-tbjhg           1/1     Running             13 (3h51m ago)     6h54m   10.104.4.22    4am-node11   <none>           <none>
fouramf-xspmg-64-5064-milvus-rootcoord-79fd94d8d6-h5rdz           1/1     Running             1 (6h50m ago)      6h54m   10.104.1.49    4am-node10   <none>           <none>
fouramf-xspmg-64-5064-minio-0                                     1/1     Running             0                  6h54m   10.104.4.39    4am-node11   <none>           <none>
fouramf-xspmg-64-5064-minio-1                                     1/1     Running             0                  6h54m   10.104.1.67    4am-node10   <none>           <none>
fouramf-xspmg-64-5064-minio-2                                     1/1     Running             0                  6h54m   10.104.6.89    4am-node13   <none>           <none>
fouramf-xspmg-64-5064-minio-3                                     1/1     Running             0                  6h54m   10.104.5.123   4am-node12   <none>           <none>
fouramf-xspmg-64-5064-pulsar-bookie-0                             1/1     Running             0                  6h54m   10.104.4.40    4am-node11   <none>           <none>
fouramf-xspmg-64-5064-pulsar-bookie-1                             1/1     Running             0                  6h54m   10.104.1.73    4am-node10   <none>           <none>
fouramf-xspmg-64-5064-pulsar-bookie-2                             1/1     Running             0                  6h54m   10.104.6.95    4am-node13   <none>           <none>
fouramf-xspmg-64-5064-pulsar-bookie-init-684lb                    0/1     Completed           0                  6h54m   10.104.4.21    4am-node11   <none>           <none>
fouramf-xspmg-64-5064-pulsar-broker-0                             1/1     Running             0                  6h54m   10.104.1.57    4am-node10   <none>           <none>
fouramf-xspmg-64-5064-pulsar-proxy-0                              1/1     Running             0                  6h54m   10.104.4.24    4am-node11   <none>           <none>
fouramf-xspmg-64-5064-pulsar-pulsar-init-x9zmq                    0/1     Completed           0                  6h54m   10.104.4.19    4am-node11   <none>           <none>
fouramf-xspmg-64-5064-pulsar-recovery-0                           1/1     Running             0                  6h54m   10.104.1.58    4am-node10   <none>           <none>
fouramf-xspmg-64-5064-pulsar-zookeeper-0                          1/1     Running             0                  6h54m   10.104.1.69    4am-node10   <none>           <none>
fouramf-xspmg-64-5064-pulsar-zookeeper-1                          1/1     Running             0                  6h53m   10.104.6.103   4am-node13   <none>           <none>
fouramf-xspmg-64-5064-pulsar-zookeeper-2                          1/1     Running             0                  6h52m   10.104.9.42    4am-node14   <none>           <none> (cli_client.py:130)
[2023-02-27 15:05:28,055 -  INFO - fouram]: [Base] Start deleting services: fouramf-xspmg-64-5064 (base.py:174)
[2023-02-27 15:05:28,055 -  INFO - fouram]: [Cmd Exe]  kubectl get pvc  -n qa-milvus  | grep -E 'STATUS|fouramf-xspmg-64-5064'  (util_cmd.py:14)
[2023-02-27 15:05:35,145 -  INFO - fouram]: [CliClient] pvc storage class of release(fouramf-xspmg-64-5064): 
 I0227 15:05:29.301651     458 request.go:665] Waited for 1.143027079s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.local/apis/certificates.k8s.io/v1?timeout=32s
NAME                                                                                                         STATUS        VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
data-fouramf-xspmg-64-5064-etcd-0                                                                            Bound         pvc-0aecd56d-7023-497a-8b45-78dc9e939252   10Gi       RWO            local-path        6h54m
data-fouramf-xspmg-64-5064-etcd-1                                                                            Bound         pvc-98a9d705-d302-4cd5-a04d-ef433b8703bc   10Gi       RWO            local-path        6h54m
data-fouramf-xspmg-64-5064-etcd-2                                                                            Bound         pvc-381c73ef-10f9-4d88-bea7-9911e03cc55d   10Gi       RWO            local-path        6h54m
export-fouramf-xspmg-64-5064-minio-0                                                                         Bound         pvc-45ce312a-0b0c-47bc-bf23-46585a15fc03   500Gi      RWO            local-path        6h54m
export-fouramf-xspmg-64-5064-minio-1                                                                         Bound         pvc-e865730b-df49-4fa7-a416-2f4c470b66ff   500Gi      RWO            local-path        6h54m
export-fouramf-xspmg-64-5064-minio-2                                                                         Bound         pvc-d652a76f-6fdc-4ca7-b8fc-a7bdb383b209   500Gi      RWO            local-path        6h54m
export-fouramf-xspmg-64-5064-minio-3                                                                         Bound         pvc-a66d52c4-a3a2-498d-84ba-ce8e118d1723   500Gi      RWO            local-path        6h54m
fouramf-xspmg-64-5064-pulsar-bookie-journal-fouramf-xspmg-64-5064-pulsar-bookie-0                            Bound         pvc-7ef39d82-ea25-40d0-967f-2c1c0ebcdd65   100Gi      RWO            local-path        6h54m
fouramf-xspmg-64-5064-pulsar-bookie-journal-fouramf-xspmg-64-5064-pulsar-bookie-1                            Bound         pvc-35b158c1-2934-4fb9-9c4b-1397234d066e   100Gi      RWO            local-path        6h54m
fouramf-xspmg-64-5064-pulsar-bookie-journal-fouramf-xspmg-64-5064-pulsar-bookie-2                            Bound         pvc-a36760e3-f527-4d76-9bdb-f0504770234c   100Gi      RWO            local-path        6h54m
fouramf-xspmg-64-5064-pulsar-bookie-ledgers-fouramf-xspmg-64-5064-pulsar-bookie-0                            Bound         pvc-c3003573-7587-4969-ae73-9e1c7d85168f   200Gi      RWO            local-path        6h54m
fouramf-xspmg-64-5064-pulsar-bookie-ledgers-fouramf-xspmg-64-5064-pulsar-bookie-1                            Bound         pvc-bc664e04-eca0-48d5-af25-e84db6289425   200Gi      RWO            local-path        6h54m
fouramf-xspmg-64-5064-pulsar-bookie-ledgers-fouramf-xspmg-64-5064-pulsar-bookie-2                            Bound         pvc-31193c9c-7a79-4442-8dc2-dd0998ca805d   200Gi      RWO            local-path        6h54m
fouramf-xspmg-64-5064-pulsar-zookeeper-data-fouramf-xspmg-64-5064-pulsar-zookeeper-0                         Bound         pvc-3267344c-6ceb-4238-abcb-0792a5f7880d   20Gi       RWO            local-path        6h54m
fouramf-xspmg-64-5064-pulsar-zookeeper-data-fouramf-xspmg-64-5064-pulsar-zookeeper-1                         Bound         pvc-f0a07919-6955-4141-9b8e-c8e1d628ff55   20Gi       RWO            local-path        6h53m
fouramf-xspmg-64-5064-pulsar-zookeeper-data-fouramf-xspmg-64-5064-pulsar-zookeeper-2                         Bound         pvc-a4a0d728-a57b-4ef9-b9cb-c840b2061bcd   20Gi       RWO            local-path        6h52m (cli_client.py:137)
```

queryCoord logs:
```
2023/02/27 10:15:11 maxprocs: Leaving GOMAXPROCS=64: CPU quota undefined
	/go/src/github.com/milvus-io/milvus/internal/querycoordv2/checkers/controller.go:82 +0x8a
created by github.com/milvus-io/milvus/internal/querycoordv2/checkers.(*CheckerController).Start
	/go/src/github.com/milvus-io/milvus/internal/querycoordv2/checkers/controller.go:96 +0x132
github.com/milvus-io/milvus/internal/querycoordv2/checkers.(*CheckerController).Start.func1()
	/go/src/github.com/milvus-io/milvus/internal/querycoordv2/checkers/controller.go:121 +0x162
github.com/milvus-io/milvus/internal/querycoordv2/checkers.(*CheckerController).check(0xc0002ff280, {0x41fb250, 0xc0008e2180})
	/go/src/github.com/milvus-io/milvus/internal/querycoordv2/checkers/balance_checker.go:48 +0x7a
github.com/milvus-io/milvus/internal/querycoordv2/checkers.(*BalanceChecker).Check(0xc0006e0900, {0x41fb250, 0xc0008e2180})
	/go/src/github.com/milvus-io/milvus/internal/querycoordv2/balance/rowcount_based_balancer.go:98 +0x26d
github.com/milvus-io/milvus/internal/querycoordv2/balance.(*RowCountBasedBalancer).Balance(0xc000a34800)
	/go/src/github.com/milvus-io/milvus/internal/querycoordv2/balance/rowcount_based_balancer.go:156 +0x1752
github.com/milvus-io/milvus/internal/querycoordv2/balance.(*RowCountBasedBalancer).balanceReplica(0xc000a34800, 0xc002ddd530)
goroutine 399 [running]:
panic: runtime error: integer divide by zero
```
<img width="1752" alt="截屏2023-02-28 14 32 03" src="https://user-images.githubusercontent.com/26307815/221772753-13ceabf3-d9af-4536-ab5b-a362e2a04038.png">

client result:
```
{'server': {'deploy_tool': 'helm',
            'deploy_mode': 'cluster',
            'config_name': 'cluster_2c16m_queryNode3',
            'config': {'queryNode': {'resources': {'limits': {'cpu': '2.0',
                                                              'memory': '16Gi'},
                                                   'requests': {'cpu': '2.0',
                                                                'memory': '9Gi'}},
                                     'replicas': 3},
                       'indexNode': {'resources': {'limits': {'cpu': '2.0',
                                                              'memory': '16Gi'},
                                                   'requests': {'cpu': '2.0',
                                                                'memory': '9Gi'}}},
                       'dataNode': {'resources': {'limits': {'cpu': '2.0',
                                                             'memory': '16Gi'},
                                                  'requests': {'cpu': '2.0',
                                                               'memory': '9Gi'}}},
                       'cluster': {'enabled': True},
                       'pulsar': {'bookkeeper': {'volumes': {'journal': {'storageClassName': 'local-path'},
                                                             'ledgers': {'storageClassName': 'local-path'}}},
                                  'zookeeper': {'volumes': {'data': {'storageClassName': 'local-path'}}}},
                       'kafka': {'persistence': {'storageClass': 'local-path'}},
                       'minio': {'persistence': {'storageClass': 'local-path'},
                                 'metrics': {'serviceMonitor': {'enabled': False}}},
                       'etcd': {'global': {'storageClass': 'local-path'},
                                'metrics': {'enabled': True,
                                            'podMonitor': {'enabled': True}}},
                       'metrics': {'serviceMonitor': {'enabled': True}},
                       'image': {'all': {'repository': 'harbor.milvus.io/milvus/milvus',
                                         'tag': '2.2.0-20230227-63c57db2'}}},
            'host': 'fouramf-xspmg-64-5064-milvus.qa-milvus.svc.cluster.local'},
 'client': {'test_case_type': 'ConcurrentClientBase',
            'test_case_name': 'test_concurrent_locust_resource_groups_cluster',
            'test_case_params': {'dataset_params': {'dim': 128,
                                                    'dataset_name': 'sift',
                                                    'dataset_size': 10000000,
                                                    'ni_per': 50000,
                                                    'metric_type': 'L2'},
                                 'collection_params': {'other_fields': []},
                                 'load_params': {'replica_number': 3,
                                                 '_resource_groups': 3},
                                 'search_params': {},
                                 'resource_groups_params': {'groups': [1, 1, 1],
                                                            'reset': True},
                                 'index_params': {'index_type': 'HNSW',
                                                  'index_param': {'M': 8,
                                                                  'efConstruction': 200}},
                                 'concurrent_params': {'concurrent_number': 50,
                                                       'during_time': '6h',
                                                       'interval': 20,
                                                       'spawn_rate': None},
                                 'concurrent_tasks': [{'type': 'search',
                                                       'weight': 1,
                                                       'params': {'nq': 100,
                                                                  'top_k': 1,
                                                                  'search_param': {'ef': 64},
                                                                  'expr': None,
                                                                  'guarantee_timestamp': None,
                                                                  'timeout': 60,
                                                                  'random_data': True}}]},
            'run_id': 2023022754731382,
            'datetime': '2023-02-27 08:11:13.305596',
            'client_version': '2.2'},
 'result': {'test_result': {'Aggregated': {'Requests': 312744,
                                           'Fails': 86752,
                                           'RPS': 14.48,
                                           'fail_s': 0.28,
                                           'RT_max': 60041.48,
                                           'RT_avg': 3395.44,
                                           'TP50': 750.0,
                                           'TP99': 10000.0},
                            'search': {'Requests': 312744,
                                       'Fails': 86752,
                                       'RPS': 14.48,
                                       'fail_s': 0.28,
                                       'RT_max': 60041.48,
                                       'RT_avg': 3395.44,
                                       'TP50': 750.0,
                                       'TP99': 10000.0}}}}
```

client search first error:
<img width="1754" alt="截屏2023-02-28 14 33 22" src="https://user-images.githubusercontent.com/26307815/221772976-26a5a507-3b8c-467d-9930-2171fc121851.png">

queryNode pod failure:

<img width="1493" alt="截屏2023-02-28 14 33 48" src="https://user-images.githubusercontent.com/26307815/221773070-76a8e988-4b35-4510-ac83-348a54d96bf6.png">

### Expected Behavior

**server run normally, and queryCoord not panic**

### Steps To Reproduce

```markdown
1、deploy Milvus Cluster
2、 client：
   1. insert 10m vectors
   2. flush
   3. build HNSW index
   4. load
   5. locust search <- queryNode pod failure after search 1h
```

**Comment by weiliu1031** [comment]
please verify this
