### ISSUE TITLE
[Bug]: Search failed with error `desc = "transport: Error while dialing dial tcp 10.102.9.120:21123: connect: no route to host` after querynode pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#22484]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-20230228-bd5b263c 
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka): Pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/12268675/222030771-84eb9bfc-1880-4574-a283-75af024295c2.png)
```
[2023-02-28T21:49:12.604Z] [2023-02-28 21:49:12 - INFO - ci_test]: assert insert: 1.669058084487915 (test_data_persistence.py:36)

[2023-02-28T21:49:16.755Z] [2023-02-28 21:49:15 - INFO - ci_test]: [test][2023-02-28T21:49:12Z] [3.32449958s] Hello_Milvus flush -> None (wrapper.py:30)

[2023-02-28T21:49:16.755Z] [2023-02-28 21:49:15 - INFO - ci_test]: [test][2023-02-28T21:49:15Z] [0.00871308s] Hello_Milvus flush -> None (wrapper.py:30)

[2023-02-28T21:49:16.755Z] [2023-02-28 21:49:15 - INFO - ci_test]: [test][2023-02-28T21:49:15Z] [0.00778607s] Hello_Milvus flush -> None (wrapper.py:30)

[2023-02-28T21:49:16.755Z] [2023-02-28 21:49:15 - INFO - ci_test]: assert flush: 3.3376576900482178, entities: 9000 (test_data_persistence.py:46)

[2023-02-28T21:49:16.755Z] [2023-02-28 21:49:16 - INFO - ci_test]: index info: [{'collection': 'Hello_Milvus', 'field': 'float_vector', 'index_name': 'test_gSDG7WJe', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}, {'collection': 'Hello_Milvus', 'field': 'varchar', 'index_name': 'test_N1ySpfc6', 'index_param': {'index_type': 'Trie'}}] (test_data_persistence.py:65)

[2023-02-28T21:49:16.755Z] [2023-02-28 21:49:16 - INFO - ci_test]: [test][2023-02-28T21:49:16Z] [0.02802615s] Hello_Milvus load -> None (wrapper.py:30)

[2023-02-28T21:49:21.982Z] [2023-02-28 21:49:21 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:

[2023-02-28T21:49:21.982Z] attempt #1:err: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.102.9.120:21123: connect: no route to host"

[2023-02-28T21:49:21.982Z] , /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace

[2023-02-28T21:49:21.982Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:285 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call

[2023-02-28T21:49:21.982Z] /go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:254 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Search

[2023-02-28T21:49:21.982Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:513 github.com/milvus-io/milvus/internal/proxy.(*searchTask).searchShard

[2023-02-28T21:49:21.982Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_policies.go:131 github.com/milvus-io/milvus/internal/proxy.mergeRoundRobinPolicy.func1

[2023-02-28T21:49:21.982Z] /usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit

[2023-02-28T21:49:21.982Z] 

[2023-02-28T21:49:21.982Z] attempt #2:context canceled

[2023-02-28T21:49:21.982Z] )>, <Time:{'RPC start': '2023-02-28 21:49:16.173630', 'RPC error': '2023-02-28 21:49:21.182205'}> (decorators.py:108)

[2023-02-28T21:49:21.982Z] [2023-02-28 21:49:21 - ERROR - ci_test]: Traceback (most recent call last):

[2023-02-28T21:49:21.982Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2023-02-28T21:49:21.982Z]     res = func(*args, **_kwargs)

[2023-02-28T21:49:21.982Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2023-02-28T21:49:21.982Z]     return func(*arg, **kwargs)

[2023-02-28T21:49:21.982Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 614, in search

[2023-02-28T21:49:21.982Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,

[2023-02-28T21:49:21.982Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-02-28T21:49:21.982Z]     raise e

[2023-02-28T21:49:21.982Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-02-28T21:49:21.982Z]     return func(*args, **kwargs)

[2023-02-28T21:49:21.982Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-02-28T21:49:21.982Z]     ret = func(self, *args, **kwargs)

[2023-02-28T21:49:21.982Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-02-28T21:49:21.982Z]     raise e

[2023-02-28T21:49:21.982Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-02-28T21:49:21.982Z]     return func(self, *args, **kwargs)

[2023-02-28T21:49:21.982Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 483, in search

[2023-02-28T21:49:21.983Z]     return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)

[2023-02-28T21:49:21.983Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 452, in _execute_search_requests

[2023-02-28T21:49:21.983Z]     raise pre_err

[2023-02-28T21:49:21.983Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 443, in _execute_search_requests

[2023-02-28T21:49:21.983Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2023-02-28T21:49:21.983Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:

[2023-02-28T21:49:21.983Z] attempt #1:err: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.102.9.120:21123: connect: no route to host"

[2023-02-28T21:49:21.983Z] , /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace

[2023-02-28T21:49:21.983Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:285 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call

[2023-02-28T21:49:21.983Z] /go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:254 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Search

[2023-02-28T21:49:21.983Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:513 github.com/milvus-io/milvus/internal/proxy.(*searchTask).searchShard

[2023-02-28T21:49:21.983Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_policies.go:131 github.com/milvus-io/milvus/internal/proxy.mergeRoundRobinPolicy.func1

[2023-02-28T21:49:21.983Z] /usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit

[2023-02-28T21:49:21.983Z] 

[2023-02-28T21:49:21.983Z] attempt #2:context canceled

[2023-02-28T21:49:21.983Z] )>

[2023-02-28T21:49:21.983Z]  (api_request.py:39)

[2023-02-28T21:49:21.983Z] [2023-02-28 21:49:21 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:

[2023-02-28T21:49:21.983Z] attempt #1:err: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.102.9.120:21123: connect: no route to host"

[2023-02-28T21:49:21.983Z] , /go/src/github.com/milvus-io/milvu...... (api_request.py:40)

[2023-02-28T21:49:21.983Z] FAILED
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-for-release-cron/detail/chaos-test-for-release-cron/2287/pipeline
log：

[artifacts-querynode-pod-kill-2287-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10856599/artifacts-querynode-pod-kill-2287-server-logs.tar.gz)

[artifacts-querynode-pod-kill-2287-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10856600/artifacts-querynode-pod-kill-2287-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-for-release-cron/detail/chaos-test-kafka-for-release-cron/2330/pipeline
```
[2023-02-28T23:10:18.517Z] [2023-02-28 23:10:18 - INFO - ci_test]: [test][2023-02-28T23:10:15Z] [2.51314658s] Hello_Milvus flush -> None (wrapper.py:30)

[2023-02-28T23:10:18.517Z] [2023-02-28 23:10:18 - INFO - ci_test]: [test][2023-02-28T23:10:18Z] [0.00311854s] Hello_Milvus flush -> None (wrapper.py:30)

[2023-02-28T23:10:18.517Z] [2023-02-28 23:10:18 - INFO - ci_test]: [test][2023-02-28T23:10:18Z] [0.00258218s] Hello_Milvus flush -> None (wrapper.py:30)

[2023-02-28T23:10:18.517Z] [2023-02-28 23:10:18 - INFO - ci_test]: assert flush: 2.5179288387298584, entities: 9000 (test_data_persistence.py:46)

[2023-02-28T23:10:18.517Z] [2023-02-28 23:10:18 - INFO - ci_test]: index info: [{'collection': 'Hello_Milvus', 'field': 'float_vector', 'index_name': 'test_3m34KDdl', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}, {'collection': 'Hello_Milvus', 'field': 'varchar', 'index_name': 'test_cq6aIacb', 'index_param': {'index_type': 'Trie'}}] (test_data_persistence.py:65)

[2023-02-28T23:10:18.517Z] [2023-02-28 23:10:18 - INFO - ci_test]: [test][2023-02-28T23:10:18Z] [0.00573422s] Hello_Milvus load -> None (wrapper.py:30)

[2023-02-28T23:10:23.750Z] [2023-02-28 23:10:23 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:

[2023-02-28T23:10:23.750Z] attempt #1:err: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.102.5.167:21123: i/o timeout"

[2023-02-28T23:10:23.750Z] , /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace

[2023-02-28T23:10:23.750Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:285 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call

[2023-02-28T23:10:23.750Z] /go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:254 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Search

[2023-02-28T23:10:23.750Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:513 github.com/milvus-io/milvus/internal/proxy.(*searchTask).searchShard

[2023-02-28T23:10:23.750Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_policies.go:131 github.com/milvus-io/milvus/internal/proxy.mergeRoundRobinPolicy.func1

[2023-02-28T23:10:23.750Z] /usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit

[2023-02-28T23:10:23.750Z] 

[2023-02-28T23:10:23.750Z] attempt #2:context canceled

[2023-02-28T23:10:23.750Z] )>, <Time:{'RPC start': '2023-02-28 23:10:18.429956', 'RPC error': '2023-02-28 23:10:23.432695'}> (decorators.py:108)

[2023-02-28T23:10:23.750Z] [2023-02-28 23:10:23 - ERROR - ci_test]: Traceback (most recent call last):

[2023-02-28T23:10:23.750Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2023-02-28T23:10:23.750Z]     res = func(*args, **_kwargs)

[2023-02-28T23:10:23.750Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2023-02-28T23:10:23.750Z]     return func(*arg, **kwargs)

[2023-02-28T23:10:23.750Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 614, in search

[2023-02-28T23:10:23.750Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,

[2023-02-28T23:10:23.750Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-02-28T23:10:23.750Z]     raise e

[2023-02-28T23:10:23.750Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-02-28T23:10:23.750Z]     return func(*args, **kwargs)

[2023-02-28T23:10:23.750Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-02-28T23:10:23.750Z]     ret = func(self, *args, **kwargs)

[2023-02-28T23:10:23.750Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-02-28T23:10:23.750Z]     raise e

[2023-02-28T23:10:23.750Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-02-28T23:10:23.750Z]     return func(self, *args, **kwargs)

[2023-02-28T23:10:23.750Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 483, in search

[2023-02-28T23:10:23.750Z]     return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)

[2023-02-28T23:10:23.750Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 452, in _execute_search_requests

[2023-02-28T23:10:23.750Z]     raise pre_err

[2023-02-28T23:10:23.750Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 443, in _execute_search_requests

[2023-02-28T23:10:23.750Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2023-02-28T23:10:23.750Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:

[2023-02-28T23:10:23.750Z] attempt #1:err: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.102.5.167:21123: i/o timeout"

[2023-02-28T23:10:23.750Z] , /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace

[2023-02-28T23:10:23.750Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:285 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call

[2023-02-28T23:10:23.750Z] /go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:254 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Search

[2023-02-28T23:10:23.750Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:513 github.com/milvus-io/milvus/internal/proxy.(*searchTask).searchShard

[2023-02-28T23:10:23.750Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_policies.go:131 github.com/milvus-io/milvus/internal/proxy.mergeRoundRobinPolicy.func1

[2023-02-28T23:10:23.750Z] /usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit

[2023-02-28T23:10:23.750Z] 

[2023-02-28T23:10:23.750Z] attempt #2:context canceled

[2023-02-28T23:10:23.750Z] )>

[2023-02-28T23:10:23.750Z]  (api_request.py:39)

[2023-02-28T23:10:23.750Z] [2023-02-28 23:10:23 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:

[2023-02-28T23:10:23.750Z] attempt #1:err: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.102.5.167:21123: i/o timeout"

[2023-02-28T23:10:23.750Z] , /go/src/github.com/milvus-io/milvus/internal/uti...... (api_request.py:40)

[2023-02-28T23:10:23.750Z] FAILED
```

log:
[artifacts-querynode-pod-kill-2330-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10856633/artifacts-querynode-pod-kill-2330-server-logs.tar.gz)

[artifacts-querynode-pod-kill-2330-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10856634/artifacts-querynode-pod-kill-2330-pytest-logs.tar.gz)

**Comment by jiaoew1991** [comment]
same as https://github.com/milvus-io/milvus/issues/22435

please verify it with https://github.com/milvus-io/milvus/pull/22470

**Comment by zhuwenxing** [comment]
It still reproduced in 2.2.0-20230301-820ec0fc
```
[2023-03-02T02:38:10.178Z] [2023-03-02 02:38:04 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 120} (api_request.py:56)

[2023-03-02T02:38:10.178Z] [2023-03-02 02:38:04 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)

[2023-03-02T02:38:10.178Z] [2023-03-02 02:38:04 - INFO - ci_test]: [test][2023-03-02T02:38:04Z] [0.00246552s] Hello_Milvus flush -> None (wrapper.py:30)

[2023-03-02T02:38:10.178Z] [2023-03-02 02:38:04 - INFO - ci_test]: assert flush: 3.055392026901245, entities: 9000 (test_data_persistence.py:46)

[2023-03-02T02:38:10.178Z] [2023-03-02 02:38:04 - INFO - ci_test]: index info: [{'collection': 'Hello_Milvus', 'field': 'varchar', 'index_name': 'test_XlGqVkBl', 'index_param': {'index_type': 'Trie'}}, {'collection': 'Hello_Milvus', 'field': 'float_vector', 'index_name': 'test_whRqv0UE', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}] (test_data_persistence.py:65)

[2023-03-02T02:38:10.178Z] [2023-03-02 02:38:04 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:56)

[2023-03-02T02:38:10.178Z] [2023-03-02 02:38:04 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)

[2023-03-02T02:38:10.178Z] [2023-03-02 02:38:04 - INFO - ci_test]: [test][2023-03-02T02:38:04Z] [0.00624950s] Hello_Milvus load -> None (wrapper.py:30)

[2023-03-02T02:38:10.178Z] [2023-03-02 02:38:04 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.09783137532675289, 0.05552785013422252, 0.07666118942544421, 0.13921618085824589, 0.07924449221910969, 0.13441921914559674, 0.05177044410905317, 0.13572740048761406, 0.05192943936081108, 0.021593735135629597, 0.04858019923924311, 0.13879090987659515, 0.12759310306003047, 0.0842080032061474, 0.0......, kwargs: {} (api_request.py:56)

[2023-03-02T02:38:10.178Z] [2023-03-02 02:38:09 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:

[2023-03-02T02:38:10.178Z] attempt #1:err: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.102.7.28:21123: i/o timeout"

[2023-03-02T02:38:10.178Z] , /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace

[2023-03-02T02:38:10.178Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:296 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call

[2023-03-02T02:38:10.178Z] /go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:254 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Search

[2023-03-02T02:38:10.178Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:513 github.com/milvus-io/milvus/internal/proxy.(*searchTask).searchShard

[2023-03-02T02:38:10.178Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_policies.go:131 github.com/milvus-io/milvus/internal/proxy.mergeRoundRobinPolicy.func1

[2023-03-02T02:38:10.178Z] /usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit

[2023-03-02T02:38:10.178Z] 

[2023-03-02T02:38:10.178Z] attempt #2:context canceled

[2023-03-02T02:38:10.178Z] )>, <Time:{'RPC start': '2023-03-02 02:38:04.550441', 'RPC error': '2023-03-02 02:38:09.553143'}> (decorators.py:108)

[2023-03-02T02:38:10.178Z] [2023-03-02 02:38:09 - ERROR - ci_test]: Traceback (most recent call last):

[2023-03-02T02:38:10.178Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2023-03-02T02:38:10.178Z]     res = func(*args, **_kwargs)

[2023-03-02T02:38:10.178Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2023-03-02T02:38:10.178Z]     return func(*arg, **kwargs)

[2023-03-02T02:38:10.178Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 614, in search

[2023-03-02T02:38:10.178Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,

[2023-03-02T02:38:10.178Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-03-02T02:38:10.178Z]     raise e

[2023-03-02T02:38:10.178Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-03-02T02:38:10.178Z]     return func(*args, **kwargs)

[2023-03-02T02:38:10.178Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-03-02T02:38:10.178Z]     ret = func(self, *args, **kwargs)

[2023-03-02T02:38:10.178Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-03-02T02:38:10.178Z]     raise e

[2023-03-02T02:38:10.178Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-03-02T02:38:10.178Z]     return func(self, *args, **kwargs)

[2023-03-02T02:38:10.178Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 483, in search

[2023-03-02T02:38:10.178Z]     return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)

[2023-03-02T02:38:10.178Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 452, in _execute_search_requests

[2023-03-02T02:38:10.178Z]     raise pre_err

[2023-03-02T02:38:10.178Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 443, in _execute_search_requests

[2023-03-02T02:38:10.178Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2023-03-02T02:38:10.178Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:

[2023-03-02T02:38:10.178Z] attempt #1:err: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.102.7.28:21123: i/o timeout"

[2023-03-02T02:38:10.178Z] , /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace

[2023-03-02T02:38:10.178Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:296 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call

[2023-03-02T02:38:10.178Z] /go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:254 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Search

[2023-03-02T02:38:10.178Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:513 github.com/milvus-io/milvus/internal/proxy.(*searchTask).searchShard

[2023-03-02T02:38:10.178Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_policies.go:131 github.com/milvus-io/milvus/internal/proxy.mergeRoundRobinPolicy.func1

[2023-03-02T02:38:10.178Z] /usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit

[2023-03-02T02:38:10.178Z] 

[2023-03-02T02:38:10.178Z] attempt #2:context canceled

[2023-03-02T02:38:10.178Z] )>

[2023-03-02T02:38:10.178Z]  (api_request.py:39)

[2023-03-02T02:38:10.178Z] [2023-03-02 02:38:09 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:

[2023-03-02T02:38:10.178Z] attempt #1:err: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.102.7.28:21123: i/o timeout"

[2023-03-02T02:38:10.178Z] , /go/src/github.com/milvus-io/milvus/internal/util...... (api_request.py:40)

[2023-03-02T02:38:10.178Z] ------------- generated html file: file:///tmp/ci_logs/report.html -------------

[2023-03-02T02:38:10.178Z] =========================== short test summary info ============================

[2023-03-02T02:38:10.178Z] FAILED testcases/test_data_persistence.py::TestDataPersistence::test_milvus_default - AssertionError

[2023-03-02T02:38:10.178Z] ============================== 1 failed in 9.20s ===============================
```
failed job： https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-for-release-cron/detail/chaos-test-for-release-cron/2333/pipeline
log：
[artifacts-querynode-pod-kill-2333-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/10867310/artifacts-querynode-pod-kill-2333-server-logs.1.tar.gz)

[artifacts-querynode-pod-kill-2333-pytest-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/10867311/artifacts-querynode-pod-kill-2333-pytest-logs.1.tar.gz)

**Comment by jiaoew1991** [comment]
plz verify with https://github.com/milvus-io/milvus/pull/22529
I have verified it with this job https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_kafka_for_release_cron/detail/deploy_test_kafka_for_release_cron/445/pipeline/337, it seems ok 

/unassign
/assign @zhuwenxing

**Comment by zhuwenxing** [comment]
verified and passed with 2.2.0-20230310-b2ece6a5
