### ISSUE TITLE
[Bug]: [range_search] Failed to range search for multiple times after flush reporting "type conflict in json"

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#22492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvus latest
- Deployment mode(standalone or cluster):both
- MQ type(rocksmq, pulsar or kafka):    all
- SDK version(e.g. pymilvus v2.0.0rc2):  pymilvus 2.3.0.dev44
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Failed to range search for multiple times after flush reporting "type conflict in json"
The first range search is ok, but reports error after the second time

```
>>> res1 = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=Search 1 failed, reason [UnexpectedError] Assert "failed to range search, err: type conflict in json" at /go/src/github.com/milvus-io/milvus/internal/core/src/index/VectorMemIndex.cpp:94
 err %!w(<nil>))>, <Time:{'RPC start': '2023-03-01 06:35:18.328803', 'RPC error': '2023-03-01 06:35:18.336850'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/binbin/towhee-test-env-3.8-0.8.1/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 660, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/binbin/towhee-test-env-3.8-0.8.1/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/binbin/towhee-test-env-3.8-0.8.1/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/binbin/towhee-test-env-3.8-0.8.1/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/binbin/towhee-test-env-3.8-0.8.1/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/binbin/towhee-test-env-3.8-0.8.1/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/binbin/towhee-test-env-3.8-0.8.1/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 518, in search
    return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)
  File "/binbin/towhee-test-env-3.8-0.8.1/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 487, in _execute_search_requests
    raise pre_err
  File "/binbin/towhee-test-env-3.8-0.8.1/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 478, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=Search 1 failed, reason [UnexpectedError] Assert "failed to range search, err: type conflict in json" at /go/src/github.com/milvus-io/milvus/internal/core/src/index/VectorMemIndex.cpp:94
 err %!w(<nil>))>
```

### Expected Behavior

Range search successfully after flush

### Steps To Reproduce

```python
from pymilvus import CollectionSchema, FieldSchema
from pymilvus import Collection
from pymilvus import connections
from pymilvus import DataType
from pymilvus import Partition
from pymilvus import utility

connections.connect()
dim = 128
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
bool_field = FieldSchema(name="bool", dtype=DataType.BOOL)
string_field = FieldSchema(name="string", dtype=DataType.VARCHAR, max_length=65535)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
schema = CollectionSchema(fields=[int64_field, float_field, bool_field, float_vector])

collection = Collection("test_range_search_tmp_0", schema=schema)
nb=3000
import random
import numpy as np
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], [np.bool_(i) for i in range(nb)], vectors])
index_param = {"index_type": "IVF_FLAT", "metric_type": "L2", "params": {"nlist": 100}}
collection.create_index("float_vector", index_param, index_name="index_name_1")

collection.load()
collection.flush()
default_search_params = {"metric_type": "L2", "params": {"nprobe": 10, "radius": 1, "range_filter": 0}}
nq = 2
limit = 10
res1 = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
res1 = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
```

### Milvus Log

[22492.log](https://github.com/milvus-io/milvus/files/10857815/22492.log)

### Anything else?

collection name: test_range_search_tmp_0

**Comment by smellthemoon** [comment]
From the log, knowhere has received radius and filter.
![1](https://user-images.githubusercontent.com/64083300/222109782-dc077cea-afb9-47c4-9852-7f8e0edc7a87.png)
![2](https://user-images.githubusercontent.com/64083300/222110850-5441c87b-b710-4883-bd51-42f4f34ffd97.png)
But knowhere still return type conflict error, in this case milvus should receive status==success
<img width="749" alt="3" src="https://user-images.githubusercontent.com/64083300/222111073-5bb6d8f6-03ca-4866-ba7c-0757b9ce72d9.png">

**Comment by cydrain** [comment]
without flush, brute force range search is called, in SearchBruteForce.cpp, we update "radius" and "range_filter" to make their types to float
```
config[RADIUS] = conf[RADIUS].get<float>();
```

after flush, index range search is called, there are not above type conversion for "radius" and "range_filter" in file VectorMemIndex.cpp and VectorDiskIndex.cpp, so "type conflict in json" is called.

Please update VectorMemIndex.cpp and VectorDiskIndex.cpp in the same way.

/assign @smellthemoon

**Comment by cydrain** [comment]
Update knowhere to accept both int and float as float type
https://github.com/milvus-io/knowhere/pull/714

**Comment by binbinlv** [comment]
it is fixed in master latest dev version.
```
>>> collection.load()
>>> collection.flush()
>>> default_search_params = {"metric_type": "L2", "params": {"nprobe": 10, "radius": 1, "range_filter": 0}}
>>> nq = 2
>>> limit = 10
>>> res1 = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>> res1 = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>> res1 = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>> res1 = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>> res1 = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>> res1 = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>> res1 = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>> res1 = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>> res1 = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
>>> res1 = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
```
