### ISSUE TITLE
[Bug]: Datanode panic server error: ConsumerBusy: Exclusive consumer is already connected

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#22555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230302-bdd6bc76
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):   pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Datanode panic
```
3721 [2023/03/03 06:37:51.333 +00:00] [INFO] [datanode/data_node.go:374] ["DataNode is handling watchInfo PUT event"] [key=oh-config/meta/channelwatch/174/by-dev-rootcoord-dml_65_439811416347851479v1] ["watch state"=ToRelease]
 3722 [2023/03/03 06:37:59.885 +00:00] [DEBUG] [datanode/services.go:67] ["DataNode current state"] [State=Healthy]
 3723 [2023/03/03 06:37:59.886 +00:00] [DEBUG] [datanode/services.go:67] ["DataNode current state"] [State=Healthy]
 3724 [2023/03/03 06:38:00.132 +00:00] [ERROR] [msgdispatcher/dispatcher.go:100] ["seek failed"] [pchannel=by-dev-rootcoord-dml_4] [subName=datanode-174-by-dev-rootcoord-dml_4_439811416347840021v0-false] [isMain=false] [error="failed to seek, error All attempts results:\natt      empt #1:please subcribe the channel, channel name =by-dev-rootcoord-dml\nattempt #2:please subcribe the channel, channel name =by-dev-rootcoord-dml\nattempt #3:please subcribe the channel, channel name =by-dev-rootcoord-dml\nattempt #4:please subcribe the channel, chan      nel name =by-dev-rootcoord-dml\nattempt #5:please subcribe the channel, channel name =by-dev-rootcoord-dml\nattempt #6:please subcribe the channel, channel name =by-dev-rootcoord-dml\nattempt #7:please subcribe the channel, channel name =by-dev-rootcoord-dml\nattempt #      8:please subcribe the channel, channel name =by-dev-rootcoord-dml\nattempt #9:please subcribe the channel, channel name =by-dev-rootcoord-dml\nattempt #10:please subcribe the channel, channel name =by-dev-rootcoord-dml\nattempt #11:please subcribe the channel, channel       name =by-dev-rootcoord-dml\n"] [stack="github.com/milvus-io/milvus/internal/mq/msgdispatcher.NewDispatcher\n\t/go/src/github.com/milvus-io/milvus/internal/mq/msgdispatcher/dispatcher.go:100\ngithub.com/milvus-io/milvus/internal/mq/msgdispatcher.(*dispatcherManager).spl      it.func1\n\t/go/src/github.com/milvus-io/milvus/internal/mq/msgdispatcher/manager.go:239\ngithub.com/milvus-io/milvus/internal/util/retry.Do\n\t/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:37\ngithub.com/milvus-io/milvus/internal/mq/msgdispatcher.(*      dispatcherManager).split\n\t/go/src/github.com/milvus-io/milvus/internal/mq/msgdispatcher/manager.go:237\ngithub.com/milvus-io/milvus/internal/mq/msgdispatcher.(*dispatcherManager).Run.func1\n\t/go/src/github.com/milvus-io/milvus/internal/mq/msgdispatcher/manager.go:17      4\nsync.(*Map).Range\n\t/usr/local/go/src/sync/map.go:347\ngithub.com/milvus-io/milvus/internal/mq/msgdispatcher.(*dispatcherManager).Run\n\t/go/src/github.com/milvus-io/milvus/internal/mq/msgdispatcher/manager.go:173"]
 3725 [2023/03/03 06:38:00.132 +00:00] [ERROR] [retry/retry.go:39] ["retry func failed"] ["retry time"=0] [error="failed to seek, error All attempts results:\nattempt #1:please subcribe the channel, channel name =by-dev-rootcoord-dml\nattempt #2:please subcribe the channel,       channel name =by-dev-rootcoord-dml\nattempt #3:please subcribe the channel, channel name =by-dev-rootcoord-dml\nattempt #4:please subcribe the channel, channel name =by-dev-rootcoord-dml\nattempt #5:please subcribe the channel, channel name =by-dev-rootcoord-dml\nattem      pt #6:please subcribe the channel, channel name =by-dev-rootcoord-dml\nattempt #7:please subcribe the channel, channel name =by-dev-rootcoord-dml\nattempt #8:please subcribe the channel, channel name =by-dev-rootcoord-dml\nattempt #9:please subcribe the channel, channe      l name =by-dev-rootcoord-dml\nattempt #10:please subcribe the channel, channel name =by-dev-rootcoord-dml\nattempt #11:please subcribe the channel, channel name =by-dev-rootcoord-dml\n"] [stack="github.com/milvus-io/milvus/internal/util/retry.Do\n\t/go/src/github.com/m      ilvus-io/milvus/internal/util/retry/retry.go:39\ngithub.com/milvus-io/milvus/internal/mq/msgdispatcher.(*dispatcherManager).split\n\t/go/src/github.com/milvus-io/milvus/internal/mq/msgdispatcher/manager.go:237\ngithub.com/milvus-io/milvus/internal/mq/msgdispatcher.(*di      spatcherManager).Run.func1\n\t/go/src/github.com/milvus-io/milvus/internal/mq/msgdispatcher/manager.go:174\nsync.(*Map).Range\n\t/usr/local/go/src/sync/map.go:347\ngithub.com/milvus-io/milvus/internal/mq/msgdispatcher.(*dispatcherManager).Run\n\t/go/src/github.com/milv      us-io/milvus/internal/mq/msgdispatcher/manager.go:173"]
 3726 [2023/03/03 06:38:00.332 +00:00] [INFO] [msgdispatcher/dispatcher.go:90] ["creating dispatcher..."] [pchannel=by-dev-rootcoord-dml_4] [subName=datanode-174-by-dev-rootcoord-dml_4_439811416347840021v0-false] [isMain=false]
 3727 time="2023-03-03T06:38:00Z" level=error msg="Failed to create consumer" consumerID=157 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=myneb subscription=datanode-174-by-dev-rootcoord-dml_4_439811416347840021v0-false topic="persistent:/      /public/default/by-dev-rootcoord-dml_4"
 3728 time="2023-03-03T06:38:00Z" level=error msg="Failed to create consumer" consumerID=157 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=myneb subscription=datanode-174-by-dev-rootcoord-dml_4_439811416347840021v0-false topic="persistent:/      /public/default/by-dev-rootcoord-dml_4"
 3729 [2023/03/03 06:38:00.393 +00:00] [ERROR] [retry/retry.go:39] ["retry func failed"] ["retry time"=0] [error="server error: ConsumerBusy: Exclusive consumer is already connected"] [stack="github.com/milvus-io/milvus/internal/util/retry.Do\n\t/go/src/github.com/milvus-io/      milvus/internal/util/retry/retry.go:39\ngithub.com/milvus-io/milvus/internal/mq/msgstream.(*MqTtMsgStream).AsConsumer\n\t/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_msgstream.go:530\ngithub.com/milvus-io/milvus/internal/mq/msgdispatcher.NewDispatcher\n      \t/go/src/github.com/milvus-io/milvus/internal/mq/msgdispatcher/dispatcher.go:97\ngithub.com/milvus-io/milvus/internal/mq/msgdispatcher.(*dispatcherManager).split.func1\n\t/go/src/github.com/milvus-io/milvus/internal/mq/msgdispatcher/manager.go:239\ngithub.com/milvus-i      o/milvus/internal/util/retry.Do\n\t/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:37\ngithub.com/milvus-io/milvus/internal/mq/msgdispatcher.(*dispatcherManager).split\n\t/go/src/github.com/milvus-io/milvus/internal/mq/msgdispatcher/manager.go:237\ngit      hub.com/milvus-io/milvus/internal/mq/msgdispatcher.(*dispatcherManager).Run.func1\n\t/go/src/github.com/milvus-io/milvus/internal/mq/msgdispatcher/manager.go:174\nsync.(*Map).Range\n\t/usr/local/go/src/sync/map.go:347\ngithub.com/milvus-io/milvus/internal/mq/msgdispatc      her.(*dispatcherManager).Run\n\t/go/src/github.com/milvus-io/milvus/internal/mq/msgdispatcher/manager.go:173"]
 3730 panic: Failed to create consumer by-dev-rootcoord-dml_4, error = All attempts results:
 3731 attempt #1:server error: ConsumerBusy: Exclusive consumer is already connected
 3732 
 3733 
 3734 goroutine 412 [running]:
 3735 panic({0x3360320, 0xc0057e7e60})
 3736     /usr/local/go/src/runtime/panic.go:941 +0x397 fp=0xc0015b5500 sp=0xc0015b5440 pc=0x124ccf7
 3737 github.com/milvus-io/milvus/internal/mq/msgstream.(*MqTtMsgStream).AsConsumer(0xc001e6af00, {0xc0065afac0?, 0x1, 0x0?}, {0xc001d9c200, 0x3e}, 0x2)
 3738     /go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_msgstream.go:533 +0x285 fp=0xc0015b55f0 sp=0xc0015b5500 pc=0x254fa25
 3739 github.com/milvus-io/milvus/internal/mq/msgdispatcher.NewDispatcher({0x7f7c95961380, 0xc0011de180}, 0x0, {0xc000e4e330, 0x16}, 0xc001a4c8a0, {0xc001d9c200, 0x3e}, 0xc0015b5a40?, 0xc0011c0fc0, ...)
 3740     /go/src/github.com/milvus-io/milvus/internal/mq/msgdispatcher/dispatcher.go:97 +0x404 fp=0xc0015b58b8 sp=0xc0015b55f0 pc=0x26a1a44
 3741 github.com/milvus-io/milvus/internal/mq/msgdispatcher.(*dispatcherManager).split.func1()
 3742     /go/src/github.com/milvus-io/milvus/internal/mq/msgdispatcher/manager.go:239 +0x17d fp=0xc0015b5988 sp=0xc0015b58b8 pc=0x26a663d
 3743 github.com/milvus-io/milvus/internal/util/retry.Do({0x3c4d7c8, 0xc0001ba060}, 0xc0015b5b98, {0xc00016bb90, 0x1, 0x0?})
 3744     /go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:37 +0x103 fp=0xc0015b5b20 sp=0xc0015b5988 pc=0x1efa663
 3745 github.com/milvus-io/milvus/internal/mq/msgdispatcher.(*dispatcherManager).split(0xc000eeae10, 0xc0019b6c40)
 3746     /go/src/github.com/milvus-io/milvus/internal/mq/msgdispatcher/manager.go:237 +0x3ed fp=0xc0015b5d08 sp=0xc0015b5b20 pc=0x26a628d
 3747 github.com/milvus-io/milvus/internal/mq/msgdispatcher.(*dispatcherManager).Run.func1({0x3360320, 0xc0052fc1c0}, {0x3485840?, 0xc0019b6c40?})
 3748     /go/src/github.com/milvus-io/milvus/internal/mq/msgdispatcher/manager.go:174 +0x56 fp=0xc0015b5d38 sp=0xc0015b5d08 pc=0x26a5476
 3749 sync.(*Map).Range(0xc0011bb1d0?, 0xc0015b5e98)
 3750     /usr/local/go/src/sync/map.go:347 +0x2aa fp=0xc0015b5e08 sp=0xc0015b5d38 pc=0x128e80a
 3751 github.com/milvus-io/milvus/internal/mq/msgdispatcher.(*dispatcherManager).Run(0xc000eeae10)
 3752     /go/src/github.com/milvus-io/milvus/internal/mq/msgdispatcher/manager.go:173 +0x446 fp=0xc0015b5fc8 sp=0xc0015b5e08 pc=0x26a5386
 3753 github.com/milvus-io/milvus/internal/mq/msgdispatcher.(*client).Register.func2()
 3754     /go/src/github.com/milvus-io/milvus/internal/mq/msgdispatcher/client.go:71 +0x2b fp=0xc0015b5fe0 sp=0xc0015b5fc8 pc=0x26a108b
```

before panic, I refreshed some config by etcd put:
```
./etcdctl --endpoints 10.101.35.214:2379 get --prefix oh-config/config/
oh-config/config/common.chanNamePrefix.cluster
by-test
oh-config/config/common.defaultPartitionName
_test
oh-config/config/common.retentionDuration
86400
oh-config/config/rootCoord.dmlChannelNum
32
```

### Milvus Log

datanode previous log:
[datanode.log](https://github.com/milvus-io/milvus/files/10879059/datanode.log)

all pods in devops cluster, chaos-testing namespace
```
oh-config-etcd-0                                                  1/1     Running             0                22h
oh-config-etcd-1                                                  1/1     Running             0                22h
oh-config-etcd-2                                                  1/1     Running             3 (3h47m ago)    22h
oh-config-milvus-datacoord-6b47d6db67-qfg45                       1/1     Running             0                22h
oh-config-milvus-datanode-7f8fff5f78-sztgd                        0/1     CrashLoopBackOff    170 (94s ago)    22h
oh-config-milvus-indexcoord-84cf9b7869-btwlt                      1/1     Running             0                22h
oh-config-milvus-indexnode-f95df6d6b-r25qx                        1/1     Running             0                22h
oh-config-milvus-proxy-8586d684cd-wbrs7                           1/1     Running             0                22h
oh-config-milvus-querycoord-7b4fb8684f-q5hcg                      1/1     Running             0                22h
oh-config-milvus-querynode-6dc967494c-sptrn                       1/1     Running             0                22h
oh-config-milvus-rootcoord-697684fc6c-754bk                       1/1     Running             0                22h
oh-config-minio-0                                                 1/1     Running             0                22h
oh-config-minio-1                                                 1/1     Running             0                22h
oh-config-minio-2                                                 1/1     Running             0                22h
oh-config-minio-3                                                 1/1     Running             0                22h
oh-config-pulsar-bookie-0                                         1/1     Running             0                22h
oh-config-pulsar-bookie-1                                         1/1     Running             0                22h
oh-config-pulsar-bookie-2                                         1/1     Running             0                22h
oh-config-pulsar-bookie-init-pcbc8                                0/1     Completed           0                22h
oh-config-pulsar-broker-0                                         1/1     Running             0                22h
oh-config-pulsar-proxy-0                                          1/1     Running             0                22h
oh-config-pulsar-pulsar-init-kkwvh                                0/1     Completed           0                22h
oh-config-pulsar-recovery-0                                       1/1     Running             0                22h
oh-config-pulsar-zookeeper-0                                      1/1     Running             0                22h
oh-config-pulsar-zookeeper-1                                      1/1     Running             0                22h
oh-config-pulsar-zookeeper-2                                      1/1     Running             0                22h
```

**Comment by eliassama** [comment]
i have the same question.I didn't do anything extra, it just came up automatically.

![image](https://user-images.githubusercontent.com/79587688/225793686-eecb8ca6-251d-4059-bff8-bbff61b069d6.png)

**Comment by eliassama** [comment]
I think I should have found a solution. If I use docker to deploy on each node separately, there will be channel competition between multiple Datanodes, and sometimes there will be a problem of preempting one at the same time. This problem does not exist if I use a highly configured single dataNode node.

**Comment by inkinworld** [comment]
same issue in 2.2.3, we deploy 3 data-node, all of them accidental panic casue by `Exclusive consumer is already connected` and keep restart, after change replicas  to 1,  data-node work well. It seems multi-data-node compete  with each others. 

```
ime=\"2023-04-05T07:32:52Z\" level=error msg=\"[Failed to create consumer]\" consumerID=33 error=\"server error: ConsumerBusy: Exclusive consumer is already connected\" name=bmxvq subscription=biz-name-mask-dataNode-231-biz-name-mask-rootcoord-dml_98_439996603710995897v0 topic=\"persistent://public/default/biz-name-mask-rootcoord-dml_98\"
time=\"2023-04-05T07:32:52Z\" level=error msg=\"[Failed to create consumer]\" consumerID=33 error=\"server error: ConsumerBusy: Exclusive consumer is already connected\" name=bmxvq subscription=biz-name-mask-dataNode-231-biz-name-mask-rootcoord-dml_98_439996603710995897v0 topic=\"persistent://public/default/biz-name-mask-rootcoord-dml_98\"
[2023/04/05 07:32:52.412 +00:00] [WARN] [retry/retry.go:39] [\"retry func failed\"] [\"retry time\"=0] [error=\"server error: ConsumerBusy: Exclusive consumer is already connected\"]
panic: Failed to create consumer biz-name-mask-rootcoord-dml_98, error = All attempts results:
attempt #1:server error: ConsumerBusy: Exclusive consumer is already connected


goroutine 21316 [running]:
github.com/milvus-io/milvus/internal/mq/msgstream.(*MqTtMsgStream).AsConsumer(0xc0b707da00, {0xc198ffc750?, 0x1, 0x3?}, {0xc000da8e40, 0x5a}, 0x2)
\t/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_msgstream.go:651 +0x285
github.com/milvus-io/milvus/internal/datanode.newDmInputNode({0x41dd270, 0xc4eba3d240}, 0xc411aff740, 0xc513bfb2c0)
\t/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_dmstream_input_node.go:52 +0x2af
github.com/milvus-io/milvus/internal/datanode.(*dataSyncService).initNodes(0xc3bc4d21c0, 0xc022dec270)
\t/go/src/github.com/milvus-io/milvus/internal/datanode/data_sync_service.go:285 +0x1a05
github.com/milvus-io/milvus/internal/datanode.newDataSyncService({0x41dd270?, 0xc000e78780?}, 0xc3037b3000, 0xc411aff8c0, {0x4201648, 0xc00053cfc0}, {0x41d3730?, 0xc0012c4bb0}, {0x7f075a979198, 0xc00102d860}, ...)
\t/go/src/github.com/milvus-io/milvus/internal/datanode/data_sync_service.go:112 +0x3c5
github.com/milvus-io/milvus/internal/datanode.(*flowgraphManager).addAndStart(0xc00102d920, 0xc00102a6c0, 0xc022dec270, 0xc0d6b8a3d0?)
\t/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_manager.go:49 +0x3a5
github.com/milvus-io/milvus/internal/datanode.(*DataNode).handlePutEvent(0xc00102a6c0, 0xc4ebbfdb30, 0x57b1900?)
\t/go/src/github.com/milvus-io/milvus/internal/datanode/data_node.go:401 +0xba
github.com/milvus-io/milvus/internal/datanode.(*channelEventManager).retryHandlePutEvent(0xc4eba3d100, {0x1, {0xc4691fd380, 0x39}, 0x1, 0xc4ebbfdb30})
\t/go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:88 +0x10f
github.com/milvus-io/milvus/internal/datanode.(*channelEventManager).Run.func1()
\t/go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:70 +0x12e
created by github.com/milvus-io/milvus/internal/datanode.(*channelEventManager).Run
\t/go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:64 +0x56
"
```

**Comment by ThreadDao** [comment]
reproduce
- image: `master-20230708-3112dad3`
- argo workflow name in 4am: `fouramf-concurrent-rbac-issue1`
- test steps: 10 collections insert 5m-128dim data in parallel, and datanode panic with error
```
[2023/07/10 08:30:37.714 +00:00] [INFO] [msgdispatcher/dispatcher.go:92] ["creating dispatcher..."] [pchannel=fouramf-concurrent-rbac-issue1-rootcoord-dml_2] [subName=datanode-6-fouramf-concurrent-rbac-issue1-rootcoord-dml_2_442755107303195197v0-false] [isMain=false]
time="2023-07-10T08:30:37Z" level=error msg="Failed to create consumer" consumerID=23 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=pikft subscription=datanode-6-fouramf-concurrent-rbac-issue1-rootcoord-dml_2_442755107303195197v0-false topic="persistent://public/default/fouramf-concurrent-rbac-issue1-rootcoord-dml_2"
time="2023-07-10T08:30:37Z" level=error msg="Failed to create consumer" consumerID=23 error="server error: ConsumerBusy: Exclusive consumer is already connected" name=pikft subscription=datanode-6-fouramf-concurrent-rbac-issue1-rootcoord-dml_2_442755107303195197v0-false topic="persistent://public/default/fouramf-concurrent-rbac-issue1-rootcoord-dml_2"
[2023/07/10 08:30:37.720 +00:00] [ERROR] [retry/retry.go:42] ["retry func failed"] ["retry time"=0] [error="server error: ConsumerBusy: Exclusive consumer is already connected: unrecoverable error"] [stack="github.com/milvus-io/milvus/pkg/util/retry.Do\n\t/go/src/github.com/milvus-io/milvus/pkg/util/retry/retry.go:42\ngithub.com/milvus-io/milvus/pkg/mq/msgstream.(*MqTtMsgStream).AsConsumer\n\t/go/src/github.com/milvus-io/milvus/pkg/mq/msgstream/mq_msgstream.go:531\ngithub.com/milvus-io/milvus/pkg/mq/msgdispatcher.NewDispatcher\n\t/go/src/github.com/milvus-io/milvus/pkg/mq/msgdispatcher/dispatcher.go:99\ngithub.com/milvus-io/milvus/pkg/mq/msgdispatcher.(*dispatcherManager).split.func1\n\t/go/src/github.com/milvus-io/milvus/pkg/mq/msgdispatcher/manager.go:239\ngithub.com/milvus-io/milvus/pkg/util/retry.Do\n\t/go/src/github.com/milvus-io/milvus/pkg/util/retry/retry.go:40\ngithub.com/milvus-io/milvus/pkg/mq/msgdispatcher.(*dispatcherManager).split\n\t/go/src/github.com/milvus-io/milvus/pkg/mq/msgdispatcher/manager.go:237\ngithub.com/milvus-io/milvus/pkg/mq/msgdispatcher.(*dispatcherManager).Run.func1\n\t/go/src/github.com/milvus-io/milvus/pkg/mq/msgdispatcher/manager.go:174\nsync.(*Map).Range\n\t/usr/local/go/src/sync/map.go:347\ngithub.com/milvus-io/milvus/pkg/mq/msgdispatcher.(*dispatcherManager).Run\n\t/go/src/github.com/milvus-io/milvus/pkg/mq/msgdispatcher/manager.go:173"]
panic: Failed to create consumer fouramf-concurrent-rbac-issue1-rootcoord-dml_2, error = attempt #0: server error: ConsumerBusy: Exclusive consumer is already connected: unrecoverable error

goroutine 1476 [running]:
panic({0x39baae0, 0xc0062e3b30})
    /usr/local/go/src/runtime/panic.go:941 +0x397 fp=0xc001df34a0 sp=0xc001df33e0 pc=0x14e94f7
github.com/milvus-io/milvus/pkg/mq/msgstream.(*MqTtMsgStream).AsConsumer(0xc00631a1e0, {0xc0062e3690?, 0x1, 0x0?}, {0xc0062d45a0, 0x54}, 0x2)
    /go/src/github.com/milvus-io/milvus/pkg/mq/msgstream/mq_msgstream.go:534 +0x285 fp=0xc001df3590 sp=0xc001df34a0 pc=0x2b9ae25
github.com/milvus-io/milvus/pkg/mq/msgdispatcher.NewDispatcher({0x7f9788aebf10, 0xc00150c3f0}, 0x0, {0xc0006496d0, 0x2e}, 0xc0730bc480, {0xc0062d45a0, 0x54}, 0xc001df3a40?, 0xc0017bf8c0, ...)
    /go/src/github.com/milvus-io/milvus/pkg/mq/msgdispatcher/dispatcher.go:99 +0x40c fp=0xc001df3890 sp=0xc001df3590 pc=0x2dab44c
github.com/milvus-io/milvus/pkg/mq/msgdispatcher.(*dispatcherManager).split.func1() 
    /go/src/github.com/milvus-io/milvus/pkg/mq/msgdispatcher/manager.go:239 +0x17d fp=0xc001df3960 sp=0xc001df3890 pc=0x2db027d
github.com/milvus-io/milvus/pkg/util/retry.Do({0x447d9c8, 0xc00006c1a0}, 0xc001df3b98, {0xc0011f9b90, 0x1, 0x0?})
    /go/src/github.com/milvus-io/milvus/pkg/util/retry/retry.go:40 +0x108 fp=0xc001df3b20 sp=0xc001df3960 pc=0x2302348
github.com/milvus-io/milvus/pkg/mq/msgdispatcher.(*dispatcherManager).split(0xc0016b1dd0, 0xc001a410c0)
    /go/src/github.com/milvus-io/milvus/pkg/mq/msgdispatcher/manager.go:237 +0x3ed fp=0xc001df3d08 sp=0xc001df3b20 pc=0x2dafecd
github.com/milvus-io/milvus/pkg/mq/msgdispatcher.(*dispatcherManager).Run.func1({0x39baae0, 0xc00d6489e0}, {0x3b1c240?, 0xc001a410c0?})
    /go/src/github.com/milvus-io/milvus/pkg/mq/msgdispatcher/manager.go:174 +0x56 fp=0xc001df3d38 sp=0xc001df3d08 pc=0x2daf0b6
sync.(*Map).Range(0xc001931a70?, 0xc001df3e98)
    /usr/local/go/src/sync/map.go:347 +0x2aa fp=0xc001df3e08 sp=0xc001df3d38 pc=0x152b6ea
github.com/milvus-io/milvus/pkg/mq/msgdispatcher.(*dispatcherManager).Run(0xc0016b1dd0)
    /go/src/github.com/milvus-io/milvus/pkg/mq/msgdispatcher/manager.go:173 +0x446 fp=0xc001df3fc8 sp=0xc001df3e08 pc=0x2daefc6
github.com/milvus-io/milvus/pkg/mq/msgdispatcher.(*client).Register.func2()
    /go/src/github.com/milvus-io/milvus/pkg/mq/msgdispatcher/client.go:72 +0x2b fp=0xc001df3fe0 sp=0xc001df3fc8 pc=0x2daa5cb
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc001df3fe8 sp=0xc001df3fe0 pc=0x151eb61
created by github.com/milvus-io/milvus/pkg/mq/msgdispatcher.(*client).Register
    /go/src/github.com/milvus-io/milvus/pkg/mq/msgdispatcher/client.go:72 +0x492
```

datanode panic log: 
[dn.log](https://github.com/milvus-io/milvus/files/12010164/dn.log)

other pods in 4am cluster:
```
fouramf-concurrent-rbac-issue1-etcd-0                             1/1     Running     0               18h     10.104.23.167   4am-node27   <none>           <none>
fouramf-concurrent-rbac-issue1-etcd-1                             1/1     Running     0               18h     10.104.1.71     4am-node10   <none>           <none>
fouramf-concurrent-rbac-issue1-etcd-2                             1/1     Running     0               18h     10.104.9.193    4am-node14   <none>           <none>
fouramf-concurrent-rbac-issue1-milvus-datacoord-54f54cd5ddp7lcq   1/1     Running     0               18h     10.104.23.183   4am-node27   <none>           <none>
fouramf-concurrent-rbac-issue1-milvus-datanode-dbbb4b74d-mskkg    1/1     Running     1 (18h ago)     18h     10.104.1.80     4am-node10   <none>           <none>
fouramf-concurrent-rbac-issue1-milvus-indexcoord-7dd994c5cq9kj2   1/1     Running     0               18h     10.104.23.179   4am-node27   <none>           <none>
fouramf-concurrent-rbac-issue1-milvus-indexnode-6d5fb776fdcvb6b   1/1     Running     0               18h     10.104.23.177   4am-node27   <none>           <none>
fouramf-concurrent-rbac-issue1-milvus-proxy-6657ddfddc-dcrp7      1/1     Running     0               18h     10.104.23.175   4am-node27   <none>           <none>
fouramf-concurrent-rbac-issue1-milvus-querycoord-6b578db46h7znn   1/1     Running     0               18h     10.104.23.178   4am-node27   <none>           <none>
fouramf-concurrent-rbac-issue1-milvus-querynode-7496669b44vhrpf   1/1     Running     0               18h     10.104.23.182   4am-node27   <none>           <none>
fouramf-concurrent-rbac-issue1-milvus-rootcoord-958bc5c5b-rmsxl   1/1     Running     0               18h     10.104.23.180   4am-node27   <none>           <none>
fouramf-concurrent-rbac-issue1-minio-0                            1/1     Running     0               18h     10.104.23.168   4am-node27   <none>           <none>
fouramf-concurrent-rbac-issue1-minio-1                            1/1     Running     0               18h     10.104.1.73     4am-node10   <none>           <none>
fouramf-concurrent-rbac-issue1-minio-2                            1/1     Running     0               18h     10.104.9.195    4am-node14   <none>           <none>
fouramf-concurrent-rbac-issue1-minio-3                            1/1     Running     0               18h     10.104.21.235   4am-node24   <none>           <none>
fouramf-concurrent-rbac-issue1-pulsar-bookie-0                    1/1     Running     0               18h     10.104.23.174   4am-node27   <none>           <none>
fouramf-concurrent-rbac-issue1-pulsar-bookie-1                    1/1     Running     0               18h     10.104.1.77     4am-node10   <none>           <none>
fouramf-concurrent-rbac-issue1-pulsar-bookie-2                    1/1     Running     0               18h     10.104.9.198    4am-node14   <none>           <none>
fouramf-concurrent-rbac-issue1-pulsar-bookie-init-fzncx           0/1     Completed   0               18h     10.104.23.162   4am-node27   <none>           <none>
fouramf-concurrent-rbac-issue1-pulsar-broker-0                    1/1     Running     0               18h     10.104.23.164   4am-node27   <none>           <none>
fouramf-concurrent-rbac-issue1-pulsar-proxy-0                     1/1     Running     0               18h     10.104.23.163   4am-node27   <none>           <none>
fouramf-concurrent-rbac-issue1-pulsar-pulsar-init-s8tc8           0/1     Completed   0               18h     10.104.23.161   4am-node27   <none>           <none>
fouramf-concurrent-rbac-issue1-pulsar-recovery-0                  1/1     Running     0               18h     10.104.23.165   4am-node27   <none>           <none>
fouramf-concurrent-rbac-issue1-pulsar-zookeeper-0                 1/1     Running     0               18h     10.104.23.173   4am-node27   <none>           <none>
fouramf-concurrent-rbac-issue1-pulsar-zookeeper-1                 1/1     Running     0               18h     10.104.1.79     4am-node10   <none>           <none>
fouramf-concurrent-rbac-issue1-pulsar-zookeeper-2                 1/1     Running     0               18h     10.104.9.200    4am-node14   <none>           <none>
```

**Comment by wayblink** [comment]
Supposed can be fixed by #25376. @ThreadDao We can verify this.

**Comment by binbinlv** [comment]
@ThreadDao 
any updates? Fixed now?

**Comment by ThreadDao** [comment]
Retest and not reproduce. close it first
image `master-20230814-7d61355a`
argo link:  https://argo-workflows.zilliz.cc/archived-workflows/qa/bd1ca1fb-3f20-4b0d-a35b-88598fe2ab28?nodeId=fouramf-concurrent-rbac-kg594
