### ISSUE TITLE
[Bug]: Standalone panic with error `failed to update next target for collection` when running test cases without any interruptions

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#22566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230303-5666e0a5
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):kafka    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2023/03/03 10:29:31.676 +00:00] [DEBUG] [kafka/kafka_producer.go:73] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=37.619965ms]
[2023/03/03 10:29:31.676 +00:00] [DEBUG] [kafka/kafka_producer.go:73] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=37.093369ms]
[2023/03/03 10:29:31.676 +00:00] [DEBUG] [kafka/kafka_producer.go:73] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=36.904531ms]
[2023/03/03 10:29:31.676 +00:00] [DEBUG] [kafka/kafka_producer.go:73] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=36.423219ms]
[2023/03/03 10:29:31.676 +00:00] [DEBUG] [kafka/kafka_producer.go:73] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=35.027696ms]
[2023/03/03 10:29:31.681 +00:00] [DEBUG] [kafka/kafka_producer.go:73] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=17.617901ms]
[2023/03/03 10:29:31.681 +00:00] [DEBUG] [kafka/kafka_producer.go:73] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=17.114098ms]
[2023/03/03 10:29:31.681 +00:00] [DEBUG] [kafka/kafka_producer.go:73] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=17.827431ms]
[2023/03/03 10:29:31.681 +00:00] [DEBUG] [kafka/kafka_producer.go:73] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=17.061781ms]
[2023/03/03 10:29:31.681 +00:00] [DEBUG] [kafka/kafka_producer.go:73] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=15.405382ms]
[2023/03/03 10:29:31.681 +00:00] [DEBUG] [kafka/kafka_producer.go:73] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=17.962332ms]
[2023/03/03 10:29:31.770 +00:00] [DEBUG] [kafka/kafka_producer.go:73] ["tr/send msg to stream"] [msg="send msg to stream done"] [duration=17.006224ms]
[2023/03/03 10:29:31.770 +00:00] [INFO] [meta/target_manager.go:134] ["finish to update next targets for collection"] [collectionID=439835381665842510] [segments="[439835431344738307,439835431344738249,439835431344738169]"] [channels="[by-dev-rootcoord-dml_40_439835381665842510v0,by-dev-rootcoord-dml_41_439835381665842510v1]"]
panic: failed to update next target for collection[context deadline exceeded]

goroutine 303 [running]:
github.com/milvus-io/milvus/cmd/components.(*QueryCoord).Run(0x5845e80?)
	/go/src/github.com/milvus-io/milvus/cmd/components/query_coord.go:54 +0x56
github.com/milvus-io/milvus/cmd/roles.runComponent[...].func1()
	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:102 +0x18e
created by github.com/milvus-io/milvus/cmd/roles.runComponent[...]
	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:85 +0x18a
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_kafka_for_release_cron/detail/deploy_test_kafka_for_release_cron/450/pipeline

log：
[artifacts-kafka-standalone-reinstall-450-server-second-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/10881124/artifacts-kafka-standalone-reinstall-450-server-second-deployment-logs.tar.gz)

[artifacts-kafka-standalone-reinstall-450-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10881125/artifacts-kafka-standalone-reinstall-450-pytest-logs.tar.gz)

**Comment by jiaoew1991** [comment]
Milvus was killed by OOM several times, and the memory quota of the pod is 4G which is small.

**Comment by jiaoew1991** [comment]
/unassign
/assign @zhuwenxing 
Try again after removing the memory limit of 4G please.
