### ISSUE TITLE
[Bug]: Search failed with error `fail to get shard leaders from QueryCoord: channel xxx is not available in any replica, err=NodeOffline(nodeID=13)` after querynode chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#22577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230303-09593ad1
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2023-03-06T02:45:07.227Z] [2023-03-06 02:35:59 - INFO - ci_test]: [test][2023-03-06T02:35:56Z] [3.56974834s] Checker__BbfErRpj flush -> None (wrapper.py:30)
[2023-03-06T02:45:07.227Z] [2023-03-06 02:35:59 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 120} (api_request.py:56)
[2023-03-06T02:45:07.227Z] [2023-03-06 02:35:59 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)
[2023-03-06T02:45:07.227Z] [2023-03-06 02:35:59 - INFO - ci_test]: [test][2023-03-06T02:35:59Z] [0.00719786s] Checker__BbfErRpj flush -> None (wrapper.py:30)
[2023-03-06T02:45:07.227Z] [2023-03-06 02:35:59 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 120} (api_request.py:56)
[2023-03-06T02:45:07.227Z] [2023-03-06 02:35:59 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)
[2023-03-06T02:45:07.227Z] [2023-03-06 02:35:59 - INFO - ci_test]: [test][2023-03-06T02:35:59Z] [0.00759684s] Checker__BbfErRpj flush -> None (wrapper.py:30)
[2023-03-06T02:45:07.227Z] [2023-03-06 02:35:59 - INFO - ci_test]: assert flush: 3.580872058868408, entities: 19245 (test_all_collections_after_chaos.py:58)
[2023-03-06T02:45:07.227Z] [2023-03-06 02:35:59 - INFO - ci_test]: index info: [{'collection': 'Checker__BbfErRpj', 'field': 'float_vector', 'index_name': 'index__3RWGAUzb', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}] (test_all_collections_after_chaos.py:74)
[2023-03-06T02:45:07.227Z] [2023-03-06 02:35:59 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:56)
[2023-03-06T02:45:07.227Z] [2023-03-06 02:35:59 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)
[2023-03-06T02:45:07.227Z] [2023-03-06 02:35:59 - INFO - ci_test]: [test][2023-03-06T02:35:59Z] [0.01231237s] Checker__BbfErRpj load -> None (wrapper.py:30)
[2023-03-06T02:45:07.227Z] [2023-03-06 02:35:59 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.008227887047323234, 0.04825959376607356, 0.11675491804549813, 0.02228923817787668, 0.006138032171651676, 0.14027673103728508, 0.013916972260415265, 0.03775404955773196, 0.026030569970489546, 0.0989720280111058, 0.1530453044415531, 0.07771411924583019, 0.0067090655839241, 0.08217615578353443, 0......., kwargs: {} (api_request.py:56)
[2023-03-06T02:45:07.227Z] [2023-03-06 02:36:09 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:
[2023-03-06T02:45:07.227Z] attempt #1:All attempts results:
[2023-03-06T02:45:07.227Z] attempt #1:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_11_439895810417823270v1 is not available in any replica, err=NodeOffline(nodeID=13)
[2023-03-06T02:45:07.227Z] attempt #2:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_10_439895810417823270v0 is not available in any replica, err=NodeOffline(nodeID=13)
[2023-03-06T02:45:07.227Z] attempt #3:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_10_439895810417823270v0 is not available in any replica, err=NodeOffline(nodeID=13)
[2023-03-06T02:45:07.227Z] attempt #4:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_11_439895810417823270v1 is not available in any replica, err=NodeOffline(nodeID=13)
[2023-03-06T02:45:07.227Z] attempt #5:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_11_439895810417823270v1 is not available in any replica, err=NodeOffline(nodeID=13)
[2023-03-06T02:45:07.227Z] attempt #6:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_11_439895810417823270v1 is not available in any replica, err=NodeOffline(nodeID=13)
[2023-03-06T02:45:07.227Z] attempt #7:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_11_439895810417823270v1 is not available in any replica, err=NodeOffline(nodeID=13)
[2023-03-06T02:45:07.227Z] attempt #8:context deadline exceeded
[2023-03-06T02:45:07.227Z] 
[2023-03-06T02:45:07.227Z] attempt #2:context canceled
[2023-03-06T02:45:07.227Z] )>, <Time:{'RPC start': '2023-03-06 02:35:59.719175', 'RPC error': '2023-03-06 02:36:09.724095'}> (decorators.py:108)
[2023-03-06T02:45:07.227Z] [2023-03-06 02:36:09 - ERROR - ci_test]: Traceback (most recent call last):
[2023-03-06T02:45:07.227Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2023-03-06T02:45:07.227Z]     res = func(*args, **_kwargs)
[2023-03-06T02:45:07.227Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2023-03-06T02:45:07.227Z]     return func(*arg, **kwargs)
[2023-03-06T02:45:07.227Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 660, in search
[2023-03-06T02:45:07.227Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,
[2023-03-06T02:45:07.227Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
[2023-03-06T02:45:07.227Z]     raise e
[2023-03-06T02:45:07.227Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
[2023-03-06T02:45:07.227Z]     return func(*args, **kwargs)
[2023-03-06T02:45:07.227Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
[2023-03-06T02:45:07.227Z]     ret = func(self, *args, **kwargs)
[2023-03-06T02:45:07.227Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
[2023-03-06T02:45:07.227Z]     raise e
[2023-03-06T02:45:07.227Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
[2023-03-06T02:45:07.227Z]     return func(self, *args, **kwargs)
[2023-03-06T02:45:07.227Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 518, in search
[2023-03-06T02:45:07.227Z]     return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)
[2023-03-06T02:45:07.227Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 487, in _execute_search_requests
[2023-03-06T02:45:07.227Z]     raise pre_err
[2023-03-06T02:45:07.227Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 478, in _execute_search_requests
[2023-03-06T02:45:07.227Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2023-03-06T02:45:07.227Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:
[2023-03-06T02:45:07.227Z] attempt #1:All attempts results:
[2023-03-06T02:45:07.227Z] attempt #1:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_11_439895810417823270v1 is not available in any replica, err=NodeOffline(nodeID=13)
[2023-03-06T02:45:07.227Z] attempt #2:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_10_439895810417823270v0 is not available in any replica, err=NodeOffline(nodeID=13)
[2023-03-06T02:45:07.227Z] attempt #3:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_10_439895810417823270v0 is not available in any replica, err=NodeOffline(nodeID=13)
[2023-03-06T02:45:07.227Z] attempt #4:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_11_439895810417823270v1 is not available in any replica, err=NodeOffline(nodeID=13)
[2023-03-06T02:45:07.227Z] attempt #5:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_11_439895810417823270v1 is not available in any replica, err=NodeOffline(nodeID=13)
[2023-03-06T02:45:07.227Z] attempt #6:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_11_439895810417823270v1 is not available in any replica, err=NodeOffline(nodeID=13)
[2023-03-06T02:45:07.227Z] attempt #7:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_11_439895810417823270v1 is not available in any replica, err=NodeOffline(nodeID=13)
[2023-03-06T02:45:07.227Z] attempt #8:context deadline exceeded
[2023-03-06T02:45:07.227Z] 
[2023-03-06T02:45:07.227Z] attempt #2:context canceled
```

### Milvus Log

chaos type: pod-kill image tag: 2.2.0-20230303-09593ad1 target pod: querynode
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-for-release-cron/detail/chaos-test-for-release-cron/2449/pipeline
log:
[artifacts-querynode-pod-kill-2449-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/10894010/artifacts-querynode-pod-kill-2449-server-logs.1.tar.gz)
[artifacts-querynode-pod-kill-2449-pytest-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/10894012/artifacts-querynode-pod-kill-2449-pytest-logs.1.tar.gz)

### Anything else?

I checked the status of the pods, and all pods work well
```
+ kubectl get pods -o wide
 + grep querynode-pod-kill-2449
 querynode-pod-kill-2449-etcd-0                                    1/1     Running            0                 24m     10.102.6.67     devops-node10   <none>           <none>
 querynode-pod-kill-2449-etcd-1                                    1/1     Running            0                 24m     10.102.7.232    devops-node11   <none>           <none>
 querynode-pod-kill-2449-etcd-2                                    1/1     Running            0                 24m     10.102.9.56     devops-node13   <none>           <none>
 querynode-pod-kill-2449-milvus-datacoord-7f8cf7ffcd-dm547         1/1     Running            0                 24m     10.102.5.230    devops-node21   <none>           <none>
 querynode-pod-kill-2449-milvus-datanode-6cd585cd4b-hfb4t          1/1     Running            0                 24m     10.102.5.228    devops-node21   <none>           <none>
 querynode-pod-kill-2449-milvus-datanode-6cd585cd4b-phrh7          1/1     Running            0                 24m     10.102.10.245   devops-node20   <none>           <none>
 querynode-pod-kill-2449-milvus-indexcoord-6454f5655b-d2mnp        1/1     Running            0                 24m     10.102.5.226    devops-node21   <none>           <none>
 querynode-pod-kill-2449-milvus-indexnode-65fdc68599-hqk7q         1/1     Running            0                 24m     10.102.5.227    devops-node21   <none>           <none>
 querynode-pod-kill-2449-milvus-proxy-776d4d6ccb-gdn6x             1/1     Running            0                 24m     10.102.5.234    devops-node21   <none>           <none>
 querynode-pod-kill-2449-milvus-querycoord-5b44ff7bdc-zfqwg        1/1     Running            0                 24m     10.102.5.225    devops-node21   <none>           <none>
 querynode-pod-kill-2449-milvus-querynode-697664b45c-75ws2         1/1     Running            0                 18m     10.102.5.236    devops-node21   <none>           <none>
 querynode-pod-kill-2449-milvus-querynode-697664b45c-hqnfh         1/1     Running            0                 18m     10.102.7.73     devops-node11   <none>           <none>
 querynode-pod-kill-2449-milvus-querynode-697664b45c-w92sh         1/1     Running            0                 17m     10.102.10.25    devops-node20   <none>           <none>
 querynode-pod-kill-2449-milvus-rootcoord-76db4c78c5-j2wsd         1/1     Running            0                 24m     10.102.5.224    devops-node21   <none>           <none>
 querynode-pod-kill-2449-minio-0                                   1/1     Running            0                 24m     10.102.7.226    devops-node11   <none>           <none>
 querynode-pod-kill-2449-minio-1                                   1/1     Running            0                 24m     10.102.6.62     devops-node10   <none>           <none>
 querynode-pod-kill-2449-minio-2                                   1/1     Running            0                 24m     10.102.9.57     devops-node13   <none>           <none>
 querynode-pod-kill-2449-minio-3                                   1/1     Running            0                 24m     10.102.7.243    devops-node11   <none>           <none>
 querynode-pod-kill-2449-pulsar-bookie-0                           1/1     Running            0                 24m     10.102.7.242    devops-node11   <none>           <none>
 querynode-pod-kill-2449-pulsar-bookie-1                           1/1     Running            0                 24m     10.102.6.98     devops-node10   <none>           <none>
 querynode-pod-kill-2449-pulsar-bookie-init-l75jd                  0/1     Completed          0                 24m     10.102.7.204    devops-node11   <none>           <none>
 querynode-pod-kill-2449-pulsar-broker-0                           1/1     Running            0                 24m     10.102.7.200    devops-node11   <none>           <none>
 querynode-pod-kill-2449-pulsar-proxy-0                            1/1     Running            0                 24m     10.102.5.231    devops-node21   <none>           <none>
 querynode-pod-kill-2449-pulsar-pulsar-init-4r9l4                  0/1     Completed          0                 24m     10.102.7.210    devops-node11   <none>           <none>
 querynode-pod-kill-2449-pulsar-recovery-0                         1/1     Running            0                 24m     10.102.5.232    devops-node21   <none>           <none>
 querynode-pod-kill-2449-pulsar-zookeeper-0                        1/1     Running            0                 24m     10.102.6.64     devops-node10   <none>           <none>
```

**Comment by yah01** [comment]
Deadlock problem, fixed with commit 07357e9051d30cbcb6674b9585ba5ee26914a117

**Comment by zhuwenxing** [comment]
verified and passed with 2.2.0-20230310-b2ece6a5

**Comment by HongqiZhao** [comment]
如果在v2.2.5环境，10亿数据量无法重建的情况下，出现了这个问题，该如何解决呢？/assign @zhuwenxing @xiaofan-luan

**Comment by yah01** [comment]
@HongqiZhao Hi Hongqi, the problem may be different even you saw the same error, please create an issue, and post your logs then we can check it

**Comment by xiaofan-luan** [comment]
> 如果在v2.2.5环境，10亿数据量无法重建的情况下，出现了这个问题，该如何解决呢？/assign @zhuwenxing @xiaofan-luan

please contact me or yah01 and we can help you on it
