### ISSUE TITLE
[Bug]: Search failed with error `fail to get shard leaders from QueryCoord: channel xxx is not available in any replica, err=LackSegment(segmentID=439913988493610443` after pulsar chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#22599]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230303-09593ad1
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2023-03-06T21:50:05.002Z] [2023-03-06 21:49:54 - INFO - ci_test]: assert flush: 3.029348373413086, entities: 9000 (test_data_persistence.py:46)

[2023-03-06T21:50:05.002Z] [2023-03-06 21:49:54 - INFO - ci_test]: index info: [{'collection': 'Hello_Milvus', 'field': 'float_vector', 'index_name': 'test_Ye94bk0P', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}, {'collection': 'Hello_Milvus', 'field': 'varchar', 'index_name': 'test_Weg9vrK1', 'index_param': {'index_type': 'Trie'}}] (test_data_persistence.py:65)

[2023-03-06T21:50:05.002Z] [2023-03-06 21:49:54 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:56)

[2023-03-06T21:50:05.002Z] [2023-03-06 21:49:54 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)

[2023-03-06T21:50:05.002Z] [2023-03-06 21:49:54 - INFO - ci_test]: [test][2023-03-06T21:49:54Z] [0.01002558s] Hello_Milvus load -> None (wrapper.py:30)

[2023-03-06T21:50:05.002Z] [2023-03-06 21:49:54 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.08649019761893693, 0.12384169909646293, 0.12794909507168958, 0.061333930939839944, 0.14664251392909233, 0.06492012225944448, 0.131148724466501, 0.011140286592999886, 0.08281228721888599, 0.014389595966911228, 0.14956699688300462, 0.10783526694791112, 0.14853162463712197, 0.09804480846832385, 0......., kwargs: {} (api_request.py:56)

[2023-03-06T21:50:05.002Z] [2023-03-06 21:50:04 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:

[2023-03-06T21:50:05.002Z] attempt #1:code: NodeIDNotMatch, error: fail to Search, QueryNode ID=4, reason=QueryNode 14 can't serve, recovering: target node id not match target id = 4, node id = 14

[2023-03-06T21:50:05.002Z] attempt #2:All attempts results:

[2023-03-06T21:50:05.002Z] attempt #1:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_3_439913988493610389v1 is not available in any replica, err=LackSegment(segmentID=439913988493610443)

[2023-03-06T21:50:05.002Z] attempt #2:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_3_439913988493610389v1 is not available in any replica, err=LackSegment(segmentID=439913988493610443)

[2023-03-06T21:50:05.002Z] attempt #3:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_3_439913988493610389v1 is not available in any replica, err=LackSegment(segmentID=439913988493610443)

[2023-03-06T21:50:05.002Z] attempt #4:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_3_439913988493610389v1 is not available in any replica, err=LackSegment(segmentID=439913988493610443)

[2023-03-06T21:50:05.002Z] attempt #5:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_3_439913988493610389v1 is not available in any replica, err=LackSegment(segmentID=439913988493610443)

[2023-03-06T21:50:05.002Z] attempt #6:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_3_439913988493610389v1 is not available in any replica, err=LackSegment(segmentID=439913988493610443)

[2023-03-06T21:50:05.002Z] attempt #7:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_3_439913988493610389v1 is not available in any replica, err=LackSegment(segmentID=439913988493610443)

[2023-03-06T21:50:05.002Z] attempt #8:context deadline exceeded

[2023-03-06T21:50:05.002Z] 

[2023-03-06T21:50:05.002Z] attempt #3:context canceled

[2023-03-06T21:50:05.002Z] )>, <Time:{'RPC start': '2023-03-06 21:49:54.217204', 'RPC error': '2023-03-06 21:50:04.422220'}> (decorators.py:108)

[2023-03-06T21:50:05.002Z] [2023-03-06 21:50:04 - ERROR - ci_test]: Traceback (most recent call last):

[2023-03-06T21:50:05.002Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2023-03-06T21:50:05.002Z]     res = func(*args, **_kwargs)

[2023-03-06T21:50:05.002Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2023-03-06T21:50:05.002Z]     return func(*arg, **kwargs)

[2023-03-06T21:50:05.002Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 660, in search

[2023-03-06T21:50:05.002Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,

[2023-03-06T21:50:05.002Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-03-06T21:50:05.002Z]     raise e

[2023-03-06T21:50:05.002Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-03-06T21:50:05.002Z]     return func(*args, **kwargs)

[2023-03-06T21:50:05.002Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-03-06T21:50:05.002Z]     ret = func(self, *args, **kwargs)

[2023-03-06T21:50:05.002Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-03-06T21:50:05.002Z]     raise e

[2023-03-06T21:50:05.002Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-03-06T21:50:05.002Z]     return func(self, *args, **kwargs)

[2023-03-06T21:50:05.002Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 518, in search

[2023-03-06T21:50:05.002Z]     return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)

[2023-03-06T21:50:05.002Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 487, in _execute_search_requests

[2023-03-06T21:50:05.002Z]     raise pre_err

[2023-03-06T21:50:05.002Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 478, in _execute_search_requests

[2023-03-06T21:50:05.002Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2023-03-06T21:50:05.002Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:

[2023-03-06T21:50:05.002Z] attempt #1:code: NodeIDNotMatch, error: fail to Search, QueryNode ID=4, reason=QueryNode 14 can't serve, recovering: target node id not match target id = 4, node id = 14

[2023-03-06T21:50:05.002Z] attempt #2:All attempts results:

[2023-03-06T21:50:05.002Z] attempt #1:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_3_439913988493610389v1 is not available in any replica, err=LackSegment(segmentID=439913988493610443)

[2023-03-06T21:50:05.002Z] attempt #2:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_3_439913988493610389v1 is not available in any replica, err=LackSegment(segmentID=439913988493610443)

[2023-03-06T21:50:05.002Z] attempt #3:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_3_439913988493610389v1 is not available in any replica, err=LackSegment(segmentID=439913988493610443)

[2023-03-06T21:50:05.002Z] attempt #4:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_3_439913988493610389v1 is not available in any replica, err=LackSegment(segmentID=439913988493610443)

[2023-03-06T21:50:05.002Z] attempt #5:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_3_439913988493610389v1 is not available in any replica, err=LackSegment(segmentID=439913988493610443)

[2023-03-06T21:50:05.002Z] attempt #6:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_3_439913988493610389v1 is not available in any replica, err=LackSegment(segmentID=439913988493610443)

[2023-03-06T21:50:05.002Z] attempt #7:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_3_439913988493610389v1 is not available in any replica, err=LackSegment(segmentID=439913988493610443)

[2023-03-06T21:50:05.002Z] attempt #8:context deadline exceeded

[2023-03-06T21:50:05.002Z] 

[2023-03-06T21:50:05.002Z] attempt #3:context canceled

[2023-03-06T21:50:05.002Z] )>

[2023-03-06T21:50:05.002Z]  (api_request.py:39)

[2023-03-06T21:50:05.003Z] [2023-03-06 21:50:04 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:

[2023-03-06T21:50:05.003Z] attempt #1:code: NodeIDNotMatch, error: fail to Search, QueryNode ID=4, reason=QueryNode 14 can't serve, recovering: target node id not match target id = 4, node id = 14

[2023-03-06T21:50:05.003Z] attempt #2:All attempts results:...... (api_request.py:40)
```

### Milvus Log

chaos type: pod-kill image tag: 2.2.0-20230303-09593ad1 target pod: pulsar
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-for-release-cron/detail/chaos-test-for-release-cron/2465/pipeline
log:
[artifacts-pulsar-pod-kill-2465-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10905008/artifacts-pulsar-pod-kill-2465-server-logs.tar.gz)
[artifacts-pulsar-pod-kill-2465-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10905009/artifacts-pulsar-pod-kill-2465-pytest-logs.tar.gz)

**Comment by yanliang567** [comment]
close for now, please reopen it if reprodueced with datanode.memory.forceSynceEnable=False
