### ISSUE TITLE
[Bug]: Datacoord panic after datacoord pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#22608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230307-07357e90
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2023/03/07 08:25:53.911 +00:00] [DEBUG] [etcd/etcd_kv.go:794] [tr/putEtcdMeta] [msg="putEtcdMeta done"] [duration=2.431334ms]
[2023/03/07 08:25:53.911 +00:00] [DEBUG] [datacoord/meta.go:1243] ["UpdateChannelCheckpoint done"] [vChannel=by-dev-rootcoord-dml_24_439924015778697771v0] [ts=439924176611180545] [time=2023/03/07 08:25:53.601 +00:00]
[2023/03/07 08:25:58.440 +00:00] [INFO] [datacoord/services.go:746] ["received get flushed segments request"] [collectionID=439924015778697201] [partitionID=-1]
[2023/03/07 08:25:58.442 +00:00] [INFO] [datacoord/services.go:746] ["received get flushed segments request"] [collectionID=439924015778696739] [partitionID=-1]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x276cf7b]

goroutine 1526 [running]:
github.com/milvus-io/milvus/internal/datacoord.(*Server).GetFlushedSegments(0xc00024cd00, {0x3d2cd60?, 0x3d95a60?}, 0xc0028d25f0)
	/go/src/github.com/milvus-io/milvus/internal/datacoord/services.go:775 +0x4bb
github.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).GetFlushedSegments(0xf?, {0x424a8b8?, 0xc0028c1f50?}, 0x10?)
	/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:320 +0x2c
github.com/milvus-io/milvus/internal/proto/datapb._DataCoord_GetFlushedSegments_Handler.func1({0x424a8b8, 0xc0028c1f50}, {0x3cdaa80?, 0xc0028d25f0})
	/go/src/github.com/milvus-io/milvus/internal/proto/datapb/data_coord.pb.go:6157 +0x78
github.com/milvus-io/milvus/internal/util/logutil.UnaryTraceLoggerInterceptor({0x424a8b8?, 0xc0028c1ec0?}, {0x3cdaa80, 0xc0028d25f0}, 0x4234b40?, 0xc0028ce6a8)
	/go/src/github.com/milvus-io/milvus/internal/util/logutil/grpc_interceptor.go:22 +0x49
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x424a8b8?, 0xc0028c1ec0?}, {0x3cdaa80?, 0xc0028d25f0?})
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a
github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1({0x424a8b8, 0xc0028c1e30}, {0x3cdaa80, 0xc0028d25f0}, 0xc0028c8860?, 0xc0028c8880)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38 +0x16a
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x424a8b8?, 0xc0028c1e30?}, {0x3cdaa80?, 0xc0028d25f0?})
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1({0x424a8b8, 0xc0028c1e30}, {0x3cdaa80, 0xc0028d25f0}, 0xc000e36af0?, 0x3a8fbc0?)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34 +0xbf
github.com/milvus-io/milvus/internal/proto/datapb._DataCoord_GetFlushedSegments_Handler({0x3d95a60?, 0xc000049ab0}, {0x424a8b8, 0xc0028c1e30}, 0xc0028ccba0, 0xc00041b9e0)
	/go/src/github.com/milvus-io/milvus/internal/proto/datapb/data_coord.pb.go:6159 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0005bd500, {0x425b070, 0xc00169f6c0}, 0xc0028cb9e0, 0xc00041bce0, 0x572d8f8, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1283 +0xcfd
google.golang.org/grpc.(*Server).handleStream(0xc0005bd500, {0x425b070, 0xc00169f6c0}, 0xc0028cb9e0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1620 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:920 +0x28a
```
```
+ kubectl get pods -o wide
 + grep datacoord-pod-kill-2493
 datacoord-pod-kill-2493-etcd-0                                    1/1     Running            0               12m     10.102.6.42     devops-node10   <none>           <none>
 datacoord-pod-kill-2493-etcd-1                                    1/1     Running            0               12m     10.102.7.103    devops-node11   <none>           <none>
 datacoord-pod-kill-2493-etcd-2                                    1/1     Running            0               12m     10.102.9.168    devops-node13   <none>           <none>
 datacoord-pod-kill-2493-milvus-datacoord-bdf769fff-4qm84          0/1     CrashLoopBackOff   5 (40s ago)     5m28s   10.102.5.115    devops-node21   <none>           <none>
 datacoord-pod-kill-2493-milvus-datanode-848cf444df-252kb          1/1     Running            0               12m     10.102.7.97     devops-node11   <none>           <none>
 datacoord-pod-kill-2493-milvus-datanode-848cf444df-49hrm          1/1     Running            0               12m     10.102.9.144    devops-node13   <none>           <none>
 datacoord-pod-kill-2493-milvus-indexcoord-7cc68965dc-f59t8        1/1     Running            0               12m     10.102.9.147    devops-node13   <none>           <none>
 datacoord-pod-kill-2493-milvus-indexnode-6748f99764-sfnt7         1/1     Running            0               12m     10.102.9.149    devops-node13   <none>           <none>
 datacoord-pod-kill-2493-milvus-proxy-865547c5f-gq79f              1/1     Running            0               12m     10.102.9.148    devops-node13   <none>           <none>
 datacoord-pod-kill-2493-milvus-querycoord-cd4c6c5dd-mb7qd         1/1     Running            0               12m     10.102.7.98     devops-node11   <none>           <none>
 datacoord-pod-kill-2493-milvus-querynode-5555ddb658-lzq85         1/1     Running            0               12m     10.102.7.96     devops-node11   <none>           <none>
 datacoord-pod-kill-2493-milvus-querynode-5555ddb658-qvbb8         1/1     Running            0               12m     10.102.9.146    devops-node13   <none>           <none>
 datacoord-pod-kill-2493-milvus-querynode-5555ddb658-xsr4c         1/1     Running            0               12m     10.102.5.90     devops-node21   <none>           <none>
 datacoord-pod-kill-2493-milvus-rootcoord-787b94bdb6-kp8tc         1/1     Running            0               12m     10.102.9.145    devops-node13   <none>           <none>
 datacoord-pod-kill-2493-minio-0                                   1/1     Running            0               12m     10.102.10.22    devops-node20   <none>           <none>
 datacoord-pod-kill-2493-minio-1                                   1/1     Running            0               12m     10.102.6.20     devops-node10   <none>           <none>
 datacoord-pod-kill-2493-minio-2                                   1/1     Running            0               12m     10.102.9.166    devops-node13   <none>           <none>
 datacoord-pod-kill-2493-minio-3                                   1/1     Running            0               12m     10.102.5.94     devops-node21   <none>           <none>
 datacoord-pod-kill-2493-pulsar-bookie-0                           1/1     Running            0               12m     10.102.6.22     devops-node10   <none>           <none>
 datacoord-pod-kill-2493-pulsar-bookie-1                           1/1     Running            0               12m     10.102.10.29    devops-node20   <none>           <none>
 datacoord-pod-kill-2493-pulsar-bookie-init-mt2bw                  0/1     Completed          0               12m     10.102.6.239    devops-node10   <none>           <none>
 datacoord-pod-kill-2493-pulsar-broker-0                           1/1     Running            0               12m     10.102.6.245    devops-node10   <none>           <none>
 datacoord-pod-kill-2493-pulsar-proxy-0                            1/1     Running            0               12m     10.102.6.242    devops-node10   <none>           <none>
 datacoord-pod-kill-2493-pulsar-pulsar-init-b8k8v                  0/1     Completed          0               12m     10.102.10.5     devops-node20   <none>           <none>
 datacoord-pod-kill-2493-pulsar-recovery-0                         1/1     Running            0               12m     10.102.6.237    devops-node10   <none>           <none>
 datacoord-pod-kill-2493-pulsar-zookeeper-0                        1/1     Running            0               12m     10.102.10.25    devops-node20   <none>           <none>
```

### Milvus Log

chaos type: pod-kill image tag: 2.2.0-20230307-07357e90 target pod: datacoord
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-for-release-cron/detail/chaos-test-for-release-cron/2493/pipeline
log:
[artifacts-datacoord-pod-kill-2493-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/10907803/artifacts-datacoord-pod-kill-2493-server-logs.1.tar.gz)
[artifacts-datacoord-pod-kill-2493-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10907804/artifacts-datacoord-pod-kill-2493-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
It reproduced stably
chaos type: pod-kill image tag: 2.2.0-20230307-07357e90 target pod: datacoord
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-for-release-cron/detail/chaos-test-for-release-cron/2505/pipeline
log:

[artifacts-datacoord-pod-kill-2505-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10908172/artifacts-datacoord-pod-kill-2505-server-logs.tar.gz)

[artifacts-datacoord-pod-kill-2505-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10908174/artifacts-datacoord-pod-kill-2505-pytest-logs.tar.gz)

**Comment by soothing-rain** [comment]
Known issue where segment start position is null:
https://github.com/milvus-io/milvus/blob/2.2.0/internal/datacoord/services.go#L775

/unassign
/assign @yah01

**Comment by yah01** [comment]
/assign @zhuwenxing 
plz check with #22598

**Comment by yah01** [comment]
Checked logs of the passed test, no segment with nil start position, no "segment not found" error, feel free to open another issue if the DataCoord/DataNode goes not normal @zhuwenxing
