### ISSUE TITLE
Re-define result returned by has_collection if collection in delete state

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#2261]
**Describe the bug**
`has_collection` returned status not ok if  collection was in `delete` state, the expected result is status ok, and return boolean value `true` or `false`.
```
18:36:04  error_code: UNEXPECTED_ERROR
18:36:04  reason: "Collection already exists and it is in delete state, please wait a second"
18:36:04  
18:36:04  2020-05-08:10:36:04,846 ERROR    [grpc_handler.py:337] error_code: UNEXPECTED_ERROR
18:36:04  reason: "Collection already exists and it is in delete state, please wait a second"
18:36:04  
18:36:04  2020-05-08:10:36:04,846 ERROR    [client.py:72] Collection already exists and it is in delete state, please wait a second
18:36:04  2020-05-08:10:36:04,846 ERROR    [main.py:69] Status not ok
18:36:04  2020-05-08:10:36:04,847 ERROR    [main.py:70] Traceback (most recent call last):
18:36:04    File "main.py", line 67, in queue_worker
18:36:04      runner.run(run_type, collection)
18:36:04    File "/home/jenkins/agent/workspace/milvus-debug/milvus_benchmark/k8s_runner.py", line 141, in run
18:36:04      milvus_instance.create_collection(collection_name, dimension, index_file_size, metric_type)
18:36:04    File "/home/jenkins/agent/workspace/milvus-debug/milvus_benchmark/client.py", line 104, in create_collection
18:36:04      self.check_status(status)
18:36:04    File "/home/jenkins/agent/workspace/milvus-debug/milvus_benchmark/client.py", line 73, in check_status
18:36:04      raise Exception("Status not ok")
18:36:04  Exception: Status not ok
18:36:04  
18:36:04  2020-05-08:10:36:04,847 DEBUG    [k8s_runner.py:63] benchmark-test-sn8jgvf2
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)

**Screenshots**

**Additional context**

**Comment by del-zhenwu** [comment]
`drop_collection` actually should use sync mode

**Comment by yhmo** [comment]
Fixed by pr2270

**Comment by tinkerlin** [comment]
@del-zhenwu  regression test

**Comment by del-zhenwu** [comment]
fixed
