### ISSUE TITLE
[Bug]: Querynode restarted and caused search failed  after datanode pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#22688]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230309-130ab6da
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):kafka    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/12268675/224247996-a0267f6d-9257-48dc-be7c-061a5eb61b4b.png)

but there is no panic log for the previous pod
```
[2023/03/09 22:51:39.167 +00:00] [INFO] [querynode/segment_loader.go:848] ["from dml check point load done"] [subName=querynode-delta-loader-6-439982896660287796-3907669588712005167] [timeTake=21.444144ms]
[2023/03/09 22:51:39.167 +00:00] [INFO] [msgstream/mq_msgstream.go:182] ["start to close mq msg stream"] ["producer num"=0] ["consumer num"=1]
[2023/03/09 22:51:39.167 +00:00] [INFO] [querynode/load_segment_task.go:130] ["LoadSegmentTask Execute done"] [collectionID=439982896660287796] [replicaID=439982899235913741] [msgID=2175]
[2023/03/09 22:51:39.167 +00:00] [INFO] [querynode/load_segment_task.go:40] ["LoadSegmentTask PreExecute start"] [msgID=2168]
[2023/03/09 22:51:39.167 +00:00] [INFO] [querynode/load_segment_task.go:66] ["LoadSegmentTask PreExecute done"] [msgID=2168]
[2023/03/09 22:51:39.167 +00:00] [INFO] [querynode/load_segment_task.go:71] ["LoadSegmentTask Execute start"] [msgID=2168]
[2023/03/09 22:51:39.167 +00:00] [INFO] [querynode/segment_loader.go:103] ["segmentLoader start loading..."] [collectionID=439982896660296619] [segmentType=Sealed] [segmentNum=1]
[2023/03/09 22:51:39.167 +00:00] [INFO] [querynode/impl.go:523] ["loadSegmentsTask WaitToFinish done"] [collectionID=439982896660287796] [segmentIDs="[439982896660287923,439982896660296637]"] [nodeID=6]
[2023/03/09 22:51:39.168 +00:00] [INFO] [querynode/segment_loader.go:943] ["predict memory and disk usage while loading (in MiB)"] [collectionID=439982896660296619] [concurrency=1] [memUsage=1176] [memUsageAfterLoad=1175] [diskUsageAfterLoad=0]
[2023/03/09 22:51:39.169 +00:00] [INFO] [querynode/segment.go:186] ["create segment"] [collectionID=439982896660296619] [partitionID=439982896660296620] [segmentID=439982896660296643] [segmentType=Sealed] [vchannel=by-dev-rootcoord-dml_122_439982896660296619v0]
[2023/03/09 22:51:39.169 +00:00] [INFO] [querynode/segment_loader.go:191] ["start to load segments in parallel"] [collectionID=439982896660296619] [segmentType=Sealed] [segmentNum=1] [concurrencyLevel=1]
[2023/03/09 22:51:39.169 +00:00] [INFO] [querynode/segment_loader.go:231] ["start loading segment data into memory"] [collectionID=439982896660296619] [partitionID=439982896660296620] [segmentID=439982896660296643] [segmentType=Sealed]
[2023/03/09 22:51:39.169 +00:00] [INFO] [querynode/segment_loader.go:482] ["load index params file"] [segment=439982896660296643] [path=file/index_files/439982896660296725/1/439982896660296620/439982896660296643/indexParams]
[2023/03/09 22:51:39.238 +00:00] [INFO] [querynode/segment_loader.go:522] ["load index file"] [segment=439982896660296643] [path=file/index_files/439982896660296725/1/439982896660296620/439982896660296643/marisa_trie_str_ids]
[2023/03/09 22:51:39.238 +00:00] [INFO] [querynode/segment_loader.go:522] ["load index file"] [segment=439982896660296643] [path=file/index_files/439982896660296725/1/439982896660296620/439982896660296643/marisa_trie_index]
[2023/03/09 22:51:39.268 +00:00] [INFO] [kafka/kafka_consumer.go:123] ["close consumer "] [topic=by-dev-rootcoord-dml_3] [groupID=querynode-delta-loader-6-439982896660287796-3907669588712005167]
milvus: rdkafka_broker.c:5464: void rd_kafka_broker_destroy_final(rd_kafka_broker_t *): Assertion `thrd_is_current(rkb->rkb_thread)' failed.
```

search failed:
```
[2023-03-09T22:52:02.833Z] [2023-03-09 22:51:32 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 120} (api_request.py:56)

[2023-03-09T22:52:02.833Z] [2023-03-09 22:51:35 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)

[2023-03-09T22:52:02.833Z] [2023-03-09 22:51:35 - INFO - ci_test]: [test][2023-03-09T22:51:32Z] [3.02581112s] Hello_Milvus flush -> None (wrapper.py:30)

[2023-03-09T22:52:02.833Z] [2023-03-09 22:51:35 - INFO - ci_test]: assert entities: 12000 (test_data_persistence.py:84)

[2023-03-09T22:52:02.833Z] [2023-03-09 22:51:35 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:56)

[2023-03-09T22:52:02.833Z] [2023-03-09 22:51:39 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)

[2023-03-09T22:52:02.833Z] [2023-03-09 22:51:39 - INFO - ci_test]: [test][2023-03-09T22:51:35Z] [4.60859180s] Hello_Milvus load -> None (wrapper.py:30)

[2023-03-09T22:52:02.833Z] [2023-03-09 22:51:39 - INFO - ci_test]: assert load: 4.608972072601318 (test_data_persistence.py:90)

[2023-03-09T22:52:02.833Z] [2023-03-09 22:51:39 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.027753725967769545, 0.0721018084692931, 0.12432295043575459, 0.12663143212922592, 0.10113174307091599, 0.02558182986003222, 0.025369757129250946, 0.03489291144512027, 0.006362064982524551, 0.12416727378829981, 0.15408132283102813, 0.1421351902438156, 0.1423186732701365, 0.08296488623296794, 0.1......, kwargs: {} (api_request.py:56)

[2023-03-09T22:52:02.833Z] [2023-03-09 22:52:01 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:

[2023-03-09T22:52:02.833Z] attempt #1:code: UnexpectedError, error: fail to Search, QueryNode ID=3, reason=Search 6 failed, reason  err err: rpc error: code = Canceled desc = grpc: the client connection is closing

[2023-03-09T22:52:02.833Z] , /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace

[2023-03-09T22:52:02.833Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:296 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call

[2023-03-09T22:52:02.833Z] /go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:254 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Search

[2023-03-09T22:52:02.833Z] /go/src/github.com/milvus-io/milvus/internal/querynode/shard_cluster.go:779 github.com/milvus-io/milvus/internal/querynode.(*ShardCluster).Search.func2

[2023-03-09T22:52:02.833Z] /usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit

[2023-03-09T22:52:02.833Z] 

[2023-03-09T22:52:02.833Z] attempt #2:context canceled

[2023-03-09T22:52:02.833Z] )>, <Time:{'RPC start': '2023-03-09 22:51:39.812154', 'RPC error': '2023-03-09 22:52:01.247449'}> (decorators.py:108)

[2023-03-09T22:52:02.833Z] [2023-03-09 22:52:01 - ERROR - ci_test]: Traceback (most recent call last):

[2023-03-09T22:52:02.833Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2023-03-09T22:52:02.833Z]     res = func(*args, **_kwargs)

[2023-03-09T22:52:02.833Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2023-03-09T22:52:02.833Z]     return func(*arg, **kwargs)

[2023-03-09T22:52:02.833Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 660, in search

[2023-03-09T22:52:02.833Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,

[2023-03-09T22:52:02.833Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-03-09T22:52:02.833Z]     raise e

[2023-03-09T22:52:02.833Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-03-09T22:52:02.833Z]     return func(*args, **kwargs)

[2023-03-09T22:52:02.833Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-03-09T22:52:02.833Z]     ret = func(self, *args, **kwargs)

[2023-03-09T22:52:02.833Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-03-09T22:52:02.833Z]     raise e

[2023-03-09T22:52:02.833Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-03-09T22:52:02.833Z]     return func(self, *args, **kwargs)

[2023-03-09T22:52:02.833Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 518, in search

[2023-03-09T22:52:02.833Z]     return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)

[2023-03-09T22:52:02.833Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 487, in _execute_search_requests

[2023-03-09T22:52:02.833Z]     raise pre_err

[2023-03-09T22:52:02.833Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 478, in _execute_search_requests

[2023-03-09T22:52:02.833Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2023-03-09T22:52:02.833Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:

[2023-03-09T22:52:02.833Z] attempt #1:code: UnexpectedError, error: fail to Search, QueryNode ID=3, reason=Search 6 failed, reason  err err: rpc error: code = Canceled desc = grpc: the client connection is closing

[2023-03-09T22:52:02.833Z] , /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace

[2023-03-09T22:52:02.833Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:296 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call

[2023-03-09T22:52:02.833Z] /go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:254 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Search

[2023-03-09T22:52:02.833Z] /go/src/github.com/milvus-io/milvus/internal/querynode/shard_cluster.go:779 github.com/milvus-io/milvus/internal/querynode.(*ShardCluster).Search.func2

[2023-03-09T22:52:02.833Z] /usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit

[2023-03-09T22:52:02.833Z] 

[2023-03-09T22:52:02.833Z] attempt #2:context canceled

[2023-03-09T22:52:02.833Z] )>

[2023-03-09T22:52:02.833Z]  (api_request.py:39)

[2023-03-09T22:52:02.833Z] [2023-03-09 22:52:01 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:

[2023-03-09T22:52:02.833Z] attempt #1:code: UnexpectedError, error: fail to Search, QueryNode ID=3, reason=Search 6 failed, reason  err err: rpc error: code = Canceled desc = grpc: the client connection is closing

[2023-03-09T22:52:02.833Z] , /go/src/githu...... (api_request.py:40)

[2023-03-09T22:52:02.833Z] ------------- generated html file: file:///tmp/ci_logs/report.html -------------

[2023-03-09T22:52:02.833Z] =========================== short test summary info ============================

[2023-03-09T22:52:02.833Z] FAILED testcases/test_data_persistence.py::TestDataPersistence::test_milvus_default - AssertionError

[2023-03-09T22:52:02.834Z] ============================== 1 failed in 36.09s ==============================

script returned exit code 1

```

### Milvus Log

chaos type: pod-kill image tag: 2.2.0-20230309-130ab6da target pod: datanode

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-for-release-cron/detail/chaos-test-kafka-for-release-cron/2561/pipeline
log:
[artifacts-datanode-pod-kill-2561-server-logs (2).tar.gz](https://github.com/milvus-io/milvus/files/10939527/artifacts-datanode-pod-kill-2561-server-logs.2.tar.gz)
[artifacts-datanode-pod-kill-2561-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10939526/artifacts-datanode-pod-kill-2561-pytest-logs.tar.gz)

### Anything else?

But this issue is not a stable reproduced issue

**Comment by aoiasd** [comment]
```


2023-03-10 06:51:39 | milvus: rdkafka_broker.c:5464: void rd_kafka_broker_destroy_final(rd_kafka_broker_t *): Assertion `thrd_is_current(rkb->rkb_thread)' failed.
-- | --


```

librdkafka make data node crashed, https://github.com/confluentinc/librdkafka/issues/3608
