### ISSUE TITLE
[Bug]: Search failed after upgrading from v2.2.3 to 2.2.0-20230310-1642f7b7 with error `Search 23 failed, reason query shard(channel) xxx does not exist`

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#22683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.2.3 --> 2.2.0-20230310-1642f7b7
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):Pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/12268675/224217972-3624a641-61c2-41d4-85f3-fb70e055f499.png)

```

[2023-03-10T03:14:44.682Z] 2023-03-10 03:14:44.343 | INFO     | MainThread |utils:load_and_search:195 - collection name: task_2_IVF_PQ

[2023-03-10T03:14:44.682Z] 2023-03-10 03:14:44.343 | INFO     | MainThread |utils:load_and_search:196 - load collection

[2023-03-10T03:14:44.682Z] 2023-03-10 03:14:44.370 | INFO     | MainThread |utils:load_and_search:200 - load time: 0.0267

[2023-03-10T03:14:44.682Z] 2023-03-10 03:14:44.385 | INFO     | MainThread |utils:load_and_search:214 - {'metric_type': 'L2', 'params': {'nprobe': 10}}

[2023-03-10T03:14:44.682Z] 2023-03-10 03:14:44.385 | INFO     | MainThread |utils:load_and_search:217 - 

[2023-03-10T03:14:44.682Z] Search...

[2023-03-10T03:14:44.682Z] RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:

[2023-03-10T03:14:44.682Z] attempt #1:code: UnexpectedError, error: fail to Search, QueryNode ID=14, reason=Search 23 failed, reason query shard(channel)  by-dev-rootcoord-dml_59_439986768060689054v1  does not exist

[2023-03-10T03:14:44.682Z]  err %!w(<nil>)

[2023-03-10T03:14:44.682Z] attempt #2:context canceled

[2023-03-10T03:14:44.682Z] )>, <Time:{'RPC start': '2023-03-10 03:14:44.386028', 'RPC error': '2023-03-10 03:14:44.396735'}>

[2023-03-10T03:14:44.682Z] Traceback (most recent call last):

[2023-03-10T03:14:44.682Z]   File "scripts/action_after_upgrade.py", line 109, in <module>

[2023-03-10T03:14:44.682Z]     task_2(data_size, host)

[2023-03-10T03:14:44.682Z]   File "scripts/action_after_upgrade.py", line 37, in task_2

[2023-03-10T03:14:44.682Z]     load_and_search(prefix)

[2023-03-10T03:14:44.682Z]   File "/home/jenkins/agent/workspace/tests/python_client/deploy/scripts/utils.py", line 220, in load_and_search

[2023-03-10T03:14:44.682Z]     res = c.search(

[2023-03-10T03:14:44.682Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 660, in search

[2023-03-10T03:14:44.682Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,

[2023-03-10T03:14:44.682Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-03-10T03:14:44.682Z]     raise e

[2023-03-10T03:14:44.682Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-03-10T03:14:44.682Z]     return func(*args, **kwargs)

[2023-03-10T03:14:44.682Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-03-10T03:14:44.682Z]     ret = func(self, *args, **kwargs)

[2023-03-10T03:14:44.682Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-03-10T03:14:44.682Z]     raise e

[2023-03-10T03:14:44.682Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-03-10T03:14:44.682Z]     return func(self, *args, **kwargs)

[2023-03-10T03:14:44.682Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 518, in search

[2023-03-10T03:14:44.682Z]     return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)

[2023-03-10T03:14:44.682Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 487, in _execute_search_requests

[2023-03-10T03:14:44.682Z]     raise pre_err

[2023-03-10T03:14:44.682Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 478, in _execute_search_requests

[2023-03-10T03:14:44.682Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2023-03-10T03:14:44.682Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:

[2023-03-10T03:14:44.682Z] attempt #1:code: UnexpectedError, error: fail to Search, QueryNode ID=14, reason=Search 23 failed, reason query shard(channel)  by-dev-rootcoord-dml_59_439986768060689054v1  does not exist

[2023-03-10T03:14:44.682Z]  err %!w(<nil>)

[2023-03-10T03:14:44.682Z] attempt #2:context canceled

[2023-03-10T03:14:44.682Z] )>

script returned exit code 1
```

### Milvus Log

milvus mode: cluster deploy task: upgrade old image tag: v2.2.3 new image tag: 2.2.0-20230310-1642f7b7
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_for_release_cron/detail/deploy_test_for_release_cron/562/pipeline
log:
[artifacts-pulsar-cluster-upgrade-562-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10938263/artifacts-pulsar-cluster-upgrade-562-server-logs.tar.gz)

[artifacts-pulsar-cluster-upgrade-562-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10938265/artifacts-pulsar-cluster-upgrade-562-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
A new error message
```
[2023-03-10T04:46:21.969Z] 2023-03-10 04:46:21.850 | INFO     | MainThread |utils:load_and_search:195 - collection name: task_3_IVF_PQ

[2023-03-10T04:46:21.969Z] 2023-03-10 04:46:21.851 | INFO     | MainThread |utils:load_and_search:196 - load collection

[2023-03-10T04:46:21.969Z] 2023-03-10 04:46:21.859 | INFO     | MainThread |utils:load_and_search:200 - load time: 0.0087

[2023-03-10T04:46:21.969Z] 2023-03-10 04:46:21.877 | INFO     | MainThread |utils:load_and_search:214 - {'metric_type': 'L2', 'params': {'nprobe': 10}}

[2023-03-10T04:46:21.969Z] 2023-03-10 04:46:21.877 | INFO     | MainThread |utils:load_and_search:217 - 

[2023-03-10T04:46:21.969Z] Search...

[2023-03-10T04:46:21.969Z] RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:

[2023-03-10T04:46:21.969Z] attempt #1:code: UnexpectedError, error: fail to Search, QueryNode ID=27, reason=Search 27 failed, reason code: NotFoundTSafer, error: cannot found tSafer, vChannel = by-dev-rootcoord-delta_55_439988123422825785v1 err %!w(<nil>)

[2023-03-10T04:46:21.969Z] attempt #2:context canceled

[2023-03-10T04:46:21.969Z] )>, <Time:{'RPC start': '2023-03-10 04:46:21.877545', 'RPC error': '2023-03-10 04:46:21.894413'}>

[2023-03-10T04:46:21.969Z] Traceback (most recent call last):

[2023-03-10T04:46:21.969Z]   File "scripts/action_after_upgrade.py", line 111, in <module>

[2023-03-10T04:46:21.969Z]     task_3(data_size, host)

[2023-03-10T04:46:21.969Z]   File "scripts/action_after_upgrade.py", line 54, in task_3

[2023-03-10T04:46:21.969Z]     load_and_search(prefix)

[2023-03-10T04:46:21.969Z]   File "/home/jenkins/agent/workspace/tests/python_client/deploy/scripts/utils.py", line 220, in load_and_search

[2023-03-10T04:46:21.969Z]     res = c.search(

[2023-03-10T04:46:21.969Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 660, in search

[2023-03-10T04:46:21.969Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,

[2023-03-10T04:46:21.969Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-03-10T04:46:21.969Z]     raise e

[2023-03-10T04:46:21.969Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-03-10T04:46:21.969Z]     return func(*args, **kwargs)

[2023-03-10T04:46:21.969Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-03-10T04:46:21.969Z]     ret = func(self, *args, **kwargs)

[2023-03-10T04:46:21.969Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-03-10T04:46:21.969Z]     raise e

[2023-03-10T04:46:21.970Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-03-10T04:46:21.970Z]     return func(self, *args, **kwargs)

[2023-03-10T04:46:21.970Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 518, in search

[2023-03-10T04:46:21.970Z]     return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)

[2023-03-10T04:46:21.970Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 487, in _execute_search_requests

[2023-03-10T04:46:21.970Z]     raise pre_err

[2023-03-10T04:46:21.970Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 478, in _execute_search_requests

[2023-03-10T04:46:21.970Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2023-03-10T04:46:21.970Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:

[2023-03-10T04:46:21.970Z] attempt #1:code: UnexpectedError, error: fail to Search, QueryNode ID=27, reason=Search 27 failed, reason code: NotFoundTSafer, error: cannot found tSafer, vChannel = by-dev-rootcoord-delta_55_439988123422825785v1 err %!w(<nil>)

[2023-03-10T04:46:21.970Z] attempt #2:context canceled

[2023-03-10T04:46:21.970Z] )>
```

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_for_release_cron/detail/deploy_test_for_release_cron/563/pipeline/331
log:

[artifacts-pulsar-cluster-upgrade-563-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10938834/artifacts-pulsar-cluster-upgrade-563-server-logs.tar.gz)

[artifacts-pulsar-cluster-upgrade-563-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10938835/artifacts-pulsar-cluster-upgrade-563-pytest-logs.tar.gz)

**Comment by congqixia** [comment]
For querynode 23, the queryshard name was PChannel name, which caused this problem. Looking into root cause
```
[2023/03/10 02:59:54.297 +00:00] [INFO] [querynode/query_shard_service.go:98] ["Successfully add query shard"] [collection=439986768060689054] [replica=439986799288778774] [channel=by-dev-rootcoord-dml_59]
```

**Comment by zhuwenxing** [comment]
It was not reproduced in 2.2.0-20230426-5aad58d3
