### ISSUE TITLE
[Bug]: Load and release timeout after querynode pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#22744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230313-99af846b
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/12268675/224882954-62e9e86b-a96c-4ffd-bff5-cb8996d60dda.png)
```
[2023-03-13T21:52:01.574Z] [2023-03-13 21:49:54 - INFO - ci_test]: [test][2023-03-13T21:49:54Z] [0.02102536s] Hello_Milvus load -> None (wrapper.py:30)

[2023-03-13T21:52:01.574Z] [2023-03-13 21:49:54 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.005118963857400897, 0.12508805351362404, 0.01308309120758105, 0.052040587451242376, 0.11280043519188183, 0.0676674662554761, 0.09459943808325436, 0.04848105958240868, 0.08063741055996641, 0.02910647518777011, 0.03952945814689933, 0.08097066514390187, 0.1066915789610202, 0.047448972478482246, 0......., kwargs: {} (api_request.py:56)

[2023-03-13T21:52:01.574Z] [2023-03-13 21:49:54 - DEBUG - ci_test]: (api_response) : ["['(distance: 0.3105737268924713, id: 1166)']"]  (api_request.py:31)

[2023-03-13T21:52:01.574Z] [2023-03-13 21:49:54 - INFO - ci_test]: [test][2023-03-13T21:49:54Z] [0.13322844s] Hello_Milvus search -> <pymilvus.orm.search.SearchResult object at 0x7f4d2c60be20> (wrapper.py:30)

[2023-03-13T21:52:01.574Z] [2023-03-13 21:49:54 - INFO - ci_test]: assert search: 0.13358759880065918 (test_data_persistence.py:77)

[2023-03-13T21:52:01.574Z] [2023-03-13 21:49:54 - DEBUG - ci_test]: (api_request)  : [Collection.release] args: [], kwargs: {'timeout': 120} (api_request.py:56)

[2023-03-13T21:52:01.574Z] [2023-03-13 21:51:54 - ERROR - pymilvus.decorators]: RPC error: [release_collection], <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 120s)>, <Time:{'RPC start': '2023-03-13 21:49:54.955997', 'RPC error': '2023-03-13 21:51:54.957782'}> (decorators.py:108)

[2023-03-13T21:52:01.574Z] [2023-03-13 21:51:54 - ERROR - ci_test]: Traceback (most recent call last):

[2023-03-13T21:52:01.574Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-03-13T21:52:01.574Z]     return func(self, *args, **kwargs)

[2023-03-13T21:52:01.574Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 739, in release_collection

[2023-03-13T21:52:01.574Z]     response = rf.result()

[2023-03-13T21:52:01.574Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 744, in result

[2023-03-13T21:52:01.574Z]     raise self

[2023-03-13T21:52:01.574Z] grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:

[2023-03-13T21:52:01.574Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2023-03-13T21:52:01.574Z] 	details = "Deadline Exceeded"

[2023-03-13T21:52:01.574Z] 	debug_error_string = "{"created":"@1678744314.956764242","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":81,"grpc_status":4}"

[2023-03-13T21:52:01.574Z] >

[2023-03-13T21:52:01.574Z] 

[2023-03-13T21:52:01.574Z] The above exception was the direct cause of the following exception:

[2023-03-13T21:52:01.574Z] 

[2023-03-13T21:52:01.574Z] Traceback (most recent call last):

[2023-03-13T21:52:01.574Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2023-03-13T21:52:01.574Z]     res = func(*args, **_kwargs)

[2023-03-13T21:52:01.574Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2023-03-13T21:52:01.574Z]     return func(*arg, **kwargs)

[2023-03-13T21:52:01.574Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 389, in release

[2023-03-13T21:52:01.574Z]     conn.release_collection(self._name, timeout=timeout, **kwargs)

[2023-03-13T21:52:01.574Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-03-13T21:52:01.574Z]     raise e

[2023-03-13T21:52:01.574Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-03-13T21:52:01.574Z]     return func(*args, **kwargs)

[2023-03-13T21:52:01.574Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-03-13T21:52:01.574Z]     ret = func(self, *args, **kwargs)

[2023-03-13T21:52:01.574Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 64, in handler

[2023-03-13T21:52:01.574Z]     raise MilvusException(message=f"rpc deadline exceeded: {timeout_msg}") from e

[2023-03-13T21:52:01.574Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 120s)>

[2023-03-13T21:52:01.574Z]  (api_request.py:39)

[2023-03-13T21:52:01.574Z] [2023-03-13 21:51:54 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 120s)> (api_request.py:40)

[2023-03-13T21:52:01.574Z] ------------- generated html file: file:///tmp/ci_logs/report.html -------------

[2023-03-13T21:52:01.574Z] =========================== short test summary info ============================

[2023-03-13T21:52:01.574Z] FAILED testcases/test_data_persistence.py::TestDataPersistence::test_milvus_default - AssertionError

[2023-03-13T21:52:01.574Z] ======================== 1 failed in 123.73s (0:02:03) =========================

script returned exit code 1
```

```
2023-03-13T21:54:18.587Z] [2023-03-13 21:51:57 - DEBUG - ci_test]: (api_response) : Status(code=0, message=)  (api_request.py:31)

[2023-03-13T21:54:18.587Z] [2023-03-13 21:51:57 - INFO - ci_test]: [test][2023-03-13T21:51:55Z] [2.04323154s] e2e__x1OqpOOo create_index -> Status(code=0, message=) (wrapper.py:30)

[2023-03-13T21:54:18.587Z] [2023-03-13 21:51:57 - INFO - ci_test]: assert index: 2.581912040710449 (test_e2e.py:53)

[2023-03-13T21:54:18.587Z] [2023-03-13 21:51:57 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:56)

[2023-03-13T21:54:18.587Z] [2023-03-13 21:53:57 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=wait for loading collection timeout, collection: e2e__x1OqpOOo)>, <Time:{'RPC start': '2023-03-13 21:51:57.602199', 'RPC error': '2023-03-13 21:53:57.602975'}> (decorators.py:108)

[2023-03-13T21:54:18.587Z] [2023-03-13 21:53:57 - WARNING - pymilvus.decorators]: Retry timeout: 120s (decorators.py:79)

[2023-03-13T21:54:18.587Z] [2023-03-13 21:53:57 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: e2e__x1OqpOOo)>, <Time:{'RPC start': '2023-03-13 21:51:57.585053', 'RPC error': '2023-03-13 21:53:57.603920'}> (decorators.py:108)

[2023-03-13T21:54:18.587Z] [2023-03-13 21:53:57 - ERROR - ci_test]: Traceback (most recent call last):

[2023-03-13T21:54:18.587Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-03-13T21:54:18.587Z]     return func(self, *args, **kwargs)

[2023-03-13T21:54:18.587Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 710, in load_collection

[2023-03-13T21:54:18.587Z]     self.wait_for_loading_collection(collection_name, timeout)

[2023-03-13T21:54:18.587Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-03-13T21:54:18.587Z]     raise e

[2023-03-13T21:54:18.587Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-03-13T21:54:18.587Z]     return func(*args, **kwargs)

[2023-03-13T21:54:18.587Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-03-13T21:54:18.587Z]     ret = func(self, *args, **kwargs)

[2023-03-13T21:54:18.587Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-03-13T21:54:18.587Z]     raise e

[2023-03-13T21:54:18.587Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-03-13T21:54:18.587Z]     return func(self, *args, **kwargs)

[2023-03-13T21:54:18.587Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 732, in wait_for_loading_collection

[2023-03-13T21:54:18.587Z]     raise MilvusException(message=f"wait for loading collection timeout, collection: {collection_name}")

[2023-03-13T21:54:18.587Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=wait for loading collection timeout, collection: e2e__x1OqpOOo)>

[2023-03-13T21:54:18.587Z] 

[2023-03-13T21:54:18.587Z] The above exception was the direct cause of the following exception:

[2023-03-13T21:54:18.587Z] 

[2023-03-13T21:54:18.587Z] Traceback (most recent call last):

[2023-03-13T21:54:18.587Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2023-03-13T21:54:18.587Z]     res = func(*args, **_kwargs)

[2023-03-13T21:54:18.587Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2023-03-13T21:54:18.587Z]     return func(*arg, **kwargs)

[2023-03-13T21:54:18.587Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 366, in load

[2023-03-13T21:54:18.587Z]     conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)

[2023-03-13T21:54:18.587Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-03-13T21:54:18.587Z]     raise e

[2023-03-13T21:54:18.587Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-03-13T21:54:18.587Z]     return func(*args, **kwargs)

[2023-03-13T21:54:18.587Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-03-13T21:54:18.587Z]     ret = func(self, *args, **kwargs)

[2023-03-13T21:54:18.587Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 80, in handler

[2023-03-13T21:54:18.587Z]     raise MilvusException(e.code, f"{timeout_msg}, message={e.message}") from e

[2023-03-13T21:54:18.587Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: e2e__x1OqpOOo)>

[2023-03-13T21:54:18.587Z]  (api_request.py:39)

[2023-03-13T21:54:18.587Z] [2023-03-13 21:53:57 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: e2e__x1OqpOOo)> (api_request.py:40)

[2023-03-13T21:54:18.587Z] ------------- generated html file: file:///tmp/ci_logs/report.html -------------

[2023-03-13T21:54:18.587Z] =========================== short test summary info ============================

[2023-03-13T21:54:18.587Z] FAILED ../testcases/test_e2e.py::TestE2e::test_milvus_default - AssertionError

[2023-03-13T21:54:18.587Z] ======================== 1 failed in 266.68s (0:04:26) =========================

script returned exit code 1
```

### Milvus Log

chaos type: pod-kill image tag: 2.2.0-20230313-99af846b target pod: querynode
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-for-release-cron/detail/chaos-test-for-release-cron/2676/pipeline
log:
[artifacts-querynode-pod-kill-2676-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10963778/artifacts-querynode-pod-kill-2676-server-logs.tar.gz)
[artifacts-querynode-pod-kill-2676-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10963779/artifacts-querynode-pod-kill-2676-pytest-logs.tar.gz)

### Anything else?

It is not a stable issue. After rerun, the failed job can succeed.
![image](https://user-images.githubusercontent.com/12268675/224887873-2853bf67-72c3-40b1-b54e-fc642395fce1.png)

**Comment by yanliang567** [comment]
/assign @yah01 
is this the same root cause as you just fixed one for memory leak of querycoord?

/unassign

**Comment by yah01** [comment]
May be related, but there is still a known issue that the all load/release request will be in a queue of QueryNode, and wait for a long time with chaos, will be fixed with QueryNodeV2

**Comment by yah01** [comment]
/assign @zhuwenxing 
plz check this as QueryNodeV2 merged

**Comment by zhuwenxing** [comment]
Not reproduced in 2.2.0-20230427-a7c44b29
