### ISSUE TITLE
[Bug]: [Nightly]Search failed reporting channel xxx is not available in any replica

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#22774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:ab3cbdf
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.0.dev47
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Search failed reporting channel xxx is not available in any replica.
```
[2023-03-14T19:27:16.623Z] [2023-03-14 18:48:04 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=attempt #0: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_17_440091707095691147v1 is not available in any replica, err=leader not available: NodeHeartbeatOutdated(nodeID=2, lastHeartbeat=2023-03-14 18:47:40.337250711 +0000 UTC): attempt #1: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_17_440091707095691147v1 is not available in any replica, err=leader not available: NodeHeartbeatOutdated(nodeID=2, lastHeartbeat=2023-03-14 18:47:40.337250711 +0000 UTC): attempt #2: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_17_440091707095691147v1 is not available in any replica, err=leader not available: NodeHeartbeatOutdated(nodeID=2, lastHeartbeat=2023-03-14 18:47:40.337250711 +0000 UTC): attempt #3: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_17_440091707095691147v1 is not available in any replica, err=leader not available: NodeHeartbeatOutdated(nodeID=2, lastHeartbeat=2023-03-14 18:47:40.337250711 +0000 UTC): attempt #4: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_17_440091707095691147v1 is not available in any replica, err=leader not available: NodeHeartbeatOutdated(nodeID=2, lastHeartbeat=2023-03-14 18:47:40.337250711 +0000 UTC): attempt #5: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_17_440091707095691147v1 is not available in any replica, err=leader not available: NodeOffline(nodeID=2): attempt #6: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_17_440091707095691147v1 is not available in any replica, err=<nil>: context done during sleep after run#6: context deadline exceeded)>, <Time:{'RPC start': '2023-03-14 18:47:41.037081', 'RPC error': '2023-03-14 18:48:04.824537'}> (decorators.py:108)
[2023-03-14T19:27:16.623Z] [2023-03-14 18:48:04 - ERROR - ci_test]: Traceback (most recent call last):
[2023-03-14T19:27:16.623Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2023-03-14T19:27:16.623Z]     res = func(*args, **_kwargs)
[2023-03-14T19:27:16.623Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2023-03-14T19:27:16.623Z]     return func(*arg, **kwargs)
[2023-03-14T19:27:16.623Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 660, in search
[2023-03-14T19:27:16.623Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,
[2023-03-14T19:27:16.623Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2023-03-14T19:27:16.623Z]     raise e
[2023-03-14T19:27:16.623Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2023-03-14T19:27:16.623Z]     return func(*args, **kwargs)
[2023-03-14T19:27:16.623Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2023-03-14T19:27:16.623Z]     ret = func(self, *args, **kwargs)
[2023-03-14T19:27:16.623Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
[2023-03-14T19:27:16.623Z]     raise e
[2023-03-14T19:27:16.623Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2023-03-14T19:27:16.623Z]     return func(self, *args, **kwargs)
[2023-03-14T19:27:16.623Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 518, in search
[2023-03-14T19:27:16.623Z]     return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)
[2023-03-14T19:27:16.623Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 487, in _execute_search_requests
[2023-03-14T19:27:16.623Z]     raise pre_err
[2023-03-14T19:27:16.623Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 478, in _execute_search_requests
[2023-03-14T19:27:16.623Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2023-03-14T19:27:16.623Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=attempt #0: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_17_440091707095691147v1 is not available in any replica, err=leader not available: NodeHeartbeatOutdated(nodeID=2, lastHeartbeat=2023-03-14 18:47:40.337250711 +0000 UTC): attempt #1: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_17_440091707095691147v1 is not available in any replica, err=leader not available: NodeHeartbeatOutdated(nodeID=2, lastHeartbeat=2023-03-14 18:47:40.337250711 +0000 UTC): attempt #2: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_17_440091707095691147v1 is not available in any replica, err=leader not available: NodeHeartbeatOutdated(nodeID=2, lastHeartbeat=2023-03-14 18:47:40.337250711 +0000 UTC): attempt #3: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_17_440091707095691147v1 is not available in any replica, err=leader not available: NodeHeartbeatOutdated(nodeID=2, lastHeartbeat=2023-03-14 18:47:40.337250711 +0000 UTC): attempt #4: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_17_440091707095691147v1 is not available in any replica, err=leader not available: NodeHeartbeatOutdated(nodeID=2, lastHeartbeat=2023-03-14 18:47:40.337250711 +0000 UTC): attempt #5: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_17_440091707095691147v1 is not available in any replica, err=leader not available: NodeOffline(nodeID=2): attempt #6: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_17_440091707095691147v1 is not available in any replica, err=<nil>: context done during sleep after run#6: context deadline exceeded)>
[2023-03-14T19:27:16.623Z]  (api_request.py:39)
[2023-03-14T19:27:16.623Z] [2023-03-14 18:48:04 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=attempt #0: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_17_440091707095691147v1 is not available in any replica, err=leader not available: NodeHeartbeatOutdated(nodeID=2, lastHeartbeat=2023-03-14 ...... (api_request.py:40)
```

### Expected Behavior

search successfully

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/311/pipeline/143/
2. log: [artifacts-milvus-distributed-kafka-nightly-311-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/311/artifact/artifacts-milvus-distributed-kafka-nightly-311-pymilvus-e2e-logs.tar.gz)
3. failed time: [2023-03-14T18:48:10.152Z] [gw4] [ 74%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_index_partitions_fuzzy[5000-500-128-True-False-partition_names1]

**Comment by weiliu1031** [comment]
![image](https://user-images.githubusercontent.com/108661493/227831626-3ddf0100-6cba-414a-a93c-9933ef939e84.png)
 known issue: #22688 ,  assert in kafka consumer exit which cause query node panic

**Comment by NicoYuan1986** [comment]
reproduced again.
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/325/pipeline/155
wait for a solution.
