### ISSUE TITLE
[Bug]: [Nightly]Range search failed with an UnexpectedError 'type conflict'

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#22786]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:80c6adb
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.0.dev47
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Range search failed with an UnexpectedError 'type conflict'.
```
[2023-03-15T19:26:03.861Z] [2023-03-15 18:57:18 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=11, reason=Search 5 failed, reason [UnexpectedError] Assert "failed to range search, err: type conflict in json" at /go/src/github.com/milvus-io/milvus/internal/core/src/index/VectorMemIndex.cpp:106
[2023-03-15T19:26:03.861Z]  err %!w(<nil>))>, <Time:{'RPC start': '2023-03-15 18:57:18.595249', 'RPC error': '2023-03-15 18:57:18.936440'}> (decorators.py:108)
[2023-03-15T19:26:03.861Z] [2023-03-15 18:57:18 - ERROR - ci_test]: Traceback (most recent call last):
[2023-03-15T19:26:03.861Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2023-03-15T19:26:03.861Z]     res = func(*args, **_kwargs)
[2023-03-15T19:26:03.861Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2023-03-15T19:26:03.861Z]     return func(*arg, **kwargs)
[2023-03-15T19:26:03.861Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 660, in search
[2023-03-15T19:26:03.861Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,
[2023-03-15T19:26:03.861Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2023-03-15T19:26:03.861Z]     raise e
[2023-03-15T19:26:03.861Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2023-03-15T19:26:03.861Z]     return func(*args, **kwargs)
[2023-03-15T19:26:03.861Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2023-03-15T19:26:03.861Z]     ret = func(self, *args, **kwargs)
[2023-03-15T19:26:03.861Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
[2023-03-15T19:26:03.861Z]     raise e
[2023-03-15T19:26:03.862Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2023-03-15T19:26:03.862Z]     return func(self, *args, **kwargs)
[2023-03-15T19:26:03.862Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 518, in search
[2023-03-15T19:26:03.862Z]     return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)
[2023-03-15T19:26:03.862Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 487, in _execute_search_requests
[2023-03-15T19:26:03.862Z]     raise pre_err
[2023-03-15T19:26:03.862Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 478, in _execute_search_requests
[2023-03-15T19:26:03.862Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2023-03-15T19:26:03.862Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=11, reason=Search 5 failed, reason [UnexpectedError] Assert "failed to range search, err: type conflict in json" at /go/src/github.com/milvus-io/milvus/internal/core/src/index/VectorMemIndex.cpp:106
[2023-03-15T19:26:03.862Z]  err %!w(<nil>))>
[2023-03-15T19:26:03.862Z]  (api_request.py:39)
[2023-03-15T19:26:03.862Z] [2023-03-15 18:57:18 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=11, reason=Search 5 failed, reason [UnexpectedError] Assert "failed to range search, err: type conflict in json" at /go/src/github.com/milvus-io/milvus/internal/core/src/index/VectorMemIndex.cpp:...... (api_request.py:40)
```

### Expected Behavior

search successfully

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/312/pipeline/155
2. log: [artifacts-milvus-distributed-kafka-nightly-312-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/312/artifact/artifacts-milvus-distributed-kafka-nightly-312-pymilvus-e2e-logs.tar.gz)

**Comment by smellthemoon** [comment]
According to the log, the type is correct, but knowhere assert "type_conflict".
2023-03-16 07:51:09,884 | INFO | default | [KNOWHERE][RangeSearch][milvus] {"k":10,"metric_type":"L2","nprobe":10,"radius":1000,"range_filter":0}
Assert "failed to range search, err: type conflict in json" at /go/src/[github.com/milvus-io/milvus/internal/core/src/index/VectorMemIndex.cpp:106](http://github.com/milvus-io/milvus/internal/core/src/index/VectorMemIndex.cpp:106)
It seems to be related to the amount of data, because the test above 3000 is successful, and the test above 3000 fails.
<img width="956" alt="1" src="https://user-images.githubusercontent.com/64083300/225564204-11696217-e89c-4001-9ed8-c331ff57854c.png">
/assign @cydrain, plz help with it.

**Comment by cydrain** [comment]
fixed by PR https://github.com/milvus-io/knowhere/pull/714
with knowhere upgraded to v2.1.0 (#22790), this issue has been fixed

**Comment by binbinlv** [comment]
@NicoYuan1986 
please verify, thanks.

**Comment by NicoYuan1986** [comment]
Fixed.
