### ISSUE TITLE
[Bug]: The error check of invalid param ignore_growing is not consistent in master and 2.2 branch

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#22898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230321-4c603cd0
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.0.dev48
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The error check of invalid param ignore_growing is not consistent in master and 2.2 branch.
When query  with an invalid param ignore_growing in 2.2 branch, it will raise no exception and work as ignore_growing=False
However, when query with an invalid param ignore_growing in master branch, it will raise excpetion:
```
[2023-03-21 16:51:43 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=parse search growing failed)>, <Time:{'RPC start': '2023-03-21 16:51:43.706678', 'RPC error': '2023-03-21 16:51:43.719718'}> (decorators.py:108)
[2023-03-21 16:51:43 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/zilliz/nico/milvus/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/Users/zilliz/nico/milvus/tests/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/orm/collection.py", line 660, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 518, in search
    return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 487, in _execute_search_requests
    raise pre_err
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 478, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=parse search growing failed)>
 (api_request.py:39)
[2023-03-21 16:51:43 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=parse search growing failed)> (api_request.py:40)
```

### Expected Behavior

Keep consistent

**Comment by NicoYuan1986** [comment]
Testing framework error,
