### ISSUE TITLE
[Bug]: Upgrade failed from v2.2.2 to master-20230321-68b9cabb with datanode panic

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#22911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.2.2 --> master-20230321-68b9cabb
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/12268675/226785565-d30da00f-5ff0-432e-88e2-8c3613eb4c18.png)

```
time="2023-03-21T09:58:56Z" level=info msg="Created producer" cnx="10.102.7.77:44364 -> 10.101.250.29:6650" producerID=2 producer_name=pulsar-cluster-upgrade-538-0-1033 topic="persistent://public/default/by-dev-datacoord-timetick-channel"
[2023/03/21 09:58:56.369 +00:00] [INFO] [datanode/flow_graph_insert_buffer_node.go:672] ["datanode AsProducer"] [TimeTickChannelName=by-dev-datacoord-timetick-channel]
[2023/03/21 09:58:56.369 +00:00] [INFO] [datanode/data_sync_service.go:151] ["dataSyncService starting flow graph"] [collectionID=440242264421123581] [vChanName=by-dev-rootcoord-dml_45_440242264421123581v1]
[2023/03/21 09:58:56.369 +00:00] [INFO] [datanode/data_node.go:428] ["handle put event: new data sync service success"] [vChanName=by-dev-rootcoord-dml_45_440242264421123581v1]
[2023/03/21 09:58:56.369 +00:00] [DEBUG] [datanode/flow_graph_dd_node.go:216] ["DDNode receive delete messages"] [numRows=4] [vChannelName=by-dev-rootcoord-dml_45_440242264421123581v1]
[2023/03/21 09:58:56.369 +00:00] [ERROR] [datanode/flow_graph_dd_node.go:224] ["convert dmlVChannel to deltaVChannel failed"] [vchannel=by-dev-rootcoord-dml_45_440242264421123581v1] [error="cannot find token 'by-dev-rootcoord-dml' in ''"] [stack="github.com/milvus-io/milvus/internal/datanode.(*ddNode).Operate\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_dd_node.go:224\ngithub.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work\n\t/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:127"]
panic: cannot find token 'by-dev-rootcoord-dml' in ''

goroutine 526 [running]:
panic({0x34f7c80, 0xc000397520})
	/usr/local/go/src/runtime/panic.go:941 +0x397 fp=0xc0012c3308 sp=0xc0012c3248 pc=0x127acf7
github.com/milvus-io/milvus/internal/datanode.(*ddNode).Operate(0xc0016a8500, {0xc0016e01c0?, 0x1?, 0x1?})
	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_dd_node.go:225 +0x2d5f fp=0xc0012c3e90 sp=0xc0012c3308 pc=0x28b39ff
github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work(0xc000196280)
	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:127 +0x2ac fp=0xc0012c3fc8 sp=0xc0012c3e90 pc=0x26f814c
github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start.func1()
	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:71 +0x26 fp=0xc0012c3fe0 sp=0xc0012c3fc8 pc=0x26f7b86
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0012c3fe8 sp=0xc0012c3fe0 pc=0x12b00c1
created by github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start
	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:71 +0x79

goroutine 1 [chan receive]:
runtime.gopark(0xc000621728?, 0xc000621780?, 0xd3?, 0x8b?, 0xc000621780?)
	/usr/local/go/src/runtime/proc.go:361 +0xd6 fp=0xc001247750 sp=0xc001247730 pc=0x127df56
runtime.chanrecv(0xc00155a120, 0xc000621be8, 0x1)
	/usr/local/go/src/runtime/chan.go:577 +0x56c fp=0xc0012477e0 sp=0xc001247750 pc=0x1249d2c
runtime.chanrecv1(0xc00155a120?, 0xc000621db8?)
	/usr/local/go/src/runtime/chan.go:440 +0x18 fp=0xc001247808 sp=0xc0012477e0 pc=0x1249758
github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run(0xc000621e58, 0x0, {0xc0001ba070?, 0xc?})
	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:325 +0xa6c fp=0xc001247e08 sp=0xc001247808 pc=0x2e82e2c
github.com/milvus-io/milvus/cmd/milvus.(*run).execute(0xc0001b6270, {0xc000220060?, 0x3, 0x3}, 0xc000888720)
	/go/src/github.com/milvus-io/milvus/cmd/milvus/run.go:112 +0x66e fp=0xc001247ee0 sp=0xc001247e08 pc=0x2e8f4ae
github.com/milvus-io/milvus/cmd/milvus.RunMilvus({0xc000220060?, 0x3, 0x3})
	/go/src/github.com/milvus-io/milvus/cmd/milvus/milvus.go:60 +0x21e fp=0xc001247f58 sp=0xc001247ee0 pc=0x2e8ed3e
main.main()
	/go/src/github.com/milvus-io/milvus/cmd/main.go:26 +0x2e fp=0xc001247f80 sp=0xc001247f58 pc=0x2e91b8e
runtime.main()
	/usr/local/go/src/runtime/proc.go:250 +0x212 fp=0xc001247fe0 sp=0xc001247f80 pc=0x127db92
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc001247fe8 sp=0xc001247fe0 pc=0x12b00c1


```

### Expected Behavior

upgrading can be success

### Milvus Log

deploy task: upgrade milvus mode：cluster old image tag: v2.2.0 new image tag: master-20230321-68b9cabb
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_cron/detail/deploy_test_cron/538/pipeline
log:
[artifacts-pulsar-cluster-upgrade-538-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/11035623/artifacts-pulsar-cluster-upgrade-538-server-logs.1.tar.gz)

[artifacts-pulsar-cluster-upgrade-538-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/11035624/artifacts-pulsar-cluster-upgrade-538-pytest-logs.tar.gz)

**Comment by smellthemoon** [comment]
Related to #22180. In summary, the panic here is the expected behavior, because after upgrading from 2.2.x, the shardname of some msgs is not filled in, so the vchannelname and shardname are inconsistent at this time, so a panic occurs here. The solution is the access of QueryNodeV2.

**Comment by zhuwenxing** [comment]
wait for PR https://github.com/milvus-io/milvus/pull/21625

**Comment by zhuwenxing** [comment]
Not reproduced in master-20230427-45fbe1d1
