### ISSUE TITLE
[Bug]: Search failed with error `reason [UnexpectedError] Assert "(get_bit(field_data_ready_bitset_, field_id))" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:625` after datanode pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#22915]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230321-f2ffb5db
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka): pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/12268675/226789221-9abb05f5-efa2-4d52-a80e-12e18f170ddf.png)

```
[2023-03-21T20:50:21.933Z] [2023-03-21 20:49:33 - INFO - ci_test]: [test][2023-03-21T20:49:33Z] [0.35170790s] Checker__AqYH9y7c insert -> (insert count: 3000, delete count: 0, upsert count: 0, timestamp: 440252962831335429, success count: 3000, err count: 0) (wrapper.py:30)

[2023-03-21T20:50:21.933Z] [2023-03-21 20:49:33 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:56)

[2023-03-21T20:50:21.933Z] [2023-03-21 20:49:40 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)

[2023-03-21T20:50:21.933Z] [2023-03-21 20:49:40 - INFO - ci_test]: [test][2023-03-21T20:49:33Z] [6.63328135s] Checker__AqYH9y7c load -> None (wrapper.py:30)

[2023-03-21T20:50:21.933Z] [2023-03-21 20:49:40 - INFO - ci_test]: assert load: 6.633500099182129 (test_all_collections_after_chaos.py:99)

[2023-03-21T20:50:21.933Z] [2023-03-21 20:49:40 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.009661210434435573, 0.10143043971322527, 0.10030246794738719, 0.1470729329415726, 0.0016743863377042681, 0.1411540180361037, 0.11622615337303, 0.10265429435455685, 0.15284603959475576, 0.03282884996520535, 0.06147398403200198, 0.05146866814129061, 0.1504407284400548, 0.08318162559711922, 0.0826......, kwargs: {} (api_request.py:56)

[2023-03-21T20:50:21.934Z] [2023-03-21 20:49:40 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=Search 1 failed, reason [UnexpectedError] Assert "(get_bit(field_data_ready_bitset_, field_id))" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:625

[2023-03-21T20:50:21.934Z]  err %!w(<nil>))>, <Time:{'RPC start': '2023-03-21 20:49:40.211084', 'RPC error': '2023-03-21 20:49:40.512497'}> (decorators.py:108)

[2023-03-21T20:50:21.934Z] [2023-03-21 20:49:40 - ERROR - ci_test]: Traceback (most recent call last):

[2023-03-21T20:50:21.934Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2023-03-21T20:50:21.934Z]     res = func(*args, **_kwargs)

[2023-03-21T20:50:21.934Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2023-03-21T20:50:21.934Z]     return func(*arg, **kwargs)

[2023-03-21T20:50:21.934Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 660, in search

[2023-03-21T20:50:21.934Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,

[2023-03-21T20:50:21.934Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-03-21T20:50:21.934Z]     raise e

[2023-03-21T20:50:21.934Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-03-21T20:50:21.934Z]     return func(*args, **kwargs)

[2023-03-21T20:50:21.934Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-03-21T20:50:21.934Z]     ret = func(self, *args, **kwargs)

[2023-03-21T20:50:21.934Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-03-21T20:50:21.934Z]     raise e

[2023-03-21T20:50:21.934Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-03-21T20:50:21.934Z]     return func(self, *args, **kwargs)

[2023-03-21T20:50:21.934Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 518, in search

[2023-03-21T20:50:21.934Z]     return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)

[2023-03-21T20:50:21.934Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 487, in _execute_search_requests

[2023-03-21T20:50:21.934Z]     raise pre_err

[2023-03-21T20:50:21.934Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 478, in _execute_search_requests

[2023-03-21T20:50:21.934Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2023-03-21T20:50:21.934Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=Search 1 failed, reason [UnexpectedError] Assert "(get_bit(field_data_ready_bitset_, field_id))" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:625

[2023-03-21T20:50:21.934Z]  err %!w(<nil>))>

[2023-03-21T20:50:21.934Z]  (api_request.py:39)

[2023-03-21T20:50:21.934Z] [2023-03-21 20:49:40 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=Search 1 failed, reason [UnexpectedError] Assert "(get_bit(field_data_ready_bitset_, field_id))" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:6...... (api_request.py:40)

[2023-03-21T20:50:21.934Z] ------------- generated html file: file:///tmp/ci_logs/report.html -------------

[2023-03-21T20:50:21.934Z] =========================== short test summary info ============================

[2023-03-21T20:50:21.934Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[Checker__AqYH9y7c] - AssertionError

[2023-03-21T20:50:21.934Z] =================== 1 failed, 11 passed in 328.47s (0:05:28) ===================
```

### Expected Behavior

all test cases passed

### Milvus Log

chaos type: pod-kill image tag: master-20230321-f2ffb5db target pod: datanode
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/2923/pipeline
log:
[artifacts-datanode-pod-kill-2923-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/11035741/artifacts-datanode-pod-kill-2923-server-logs.tar.gz)
[artifacts-datanode-pod-kill-2923-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/11035742/artifacts-datanode-pod-kill-2923-pytest-logs.tar.gz)

**Comment by smellthemoon** [comment]
@zhuwenxing plz check it

**Comment by zhuwenxing** [comment]
not reproduced in master-20230417-4a32b842
