### ISSUE TITLE
[Bug]: [Nightly]Search failed on all shard leaders reporting 'query shard(channel)  xxx  does not exist'

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#22964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 0e9a447
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):   pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.0.dev48
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Search failed on all shard leaders reporting 'query shard(channel)  xxx  does not exist'.
```
[2023-03-23T19:45:22.235Z] [2023-03-23 18:09:41 - ERROR - pymilvus.decorators]: RPC error: [query], <MilvusException: (code=1, message=fail to query on all shard leaders, err=fail to Query, QueryNode ID = 2, reason=Query 1 failed, reason query shard(channel)  by-dev-rootcoord-dml_63_440295563771433844v0  does not exist
[2023-03-23T19:45:22.235Z]  err %!w(<nil>))>, <Time:{'RPC start': '2023-03-23 18:09:41.655268', 'RPC error': '2023-03-23 18:09:41.920332'}> (decorators.py:108)
[2023-03-23T19:45:22.235Z] [2023-03-23 18:09:41 - ERROR - ci_test]: Traceback (most recent call last):
[2023-03-23T19:45:22.235Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2023-03-23T19:45:22.235Z]     res = func(*args, **_kwargs)
[2023-03-23T19:45:22.235Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2023-03-23T19:45:22.235Z]     return func(*arg, **kwargs)
[2023-03-23T19:45:22.235Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 744, in query
[2023-03-23T19:45:22.235Z]     res = conn.query(self._name, expr, output_fields, partition_names,
[2023-03-23T19:45:22.235Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2023-03-23T19:45:22.235Z]     raise e
[2023-03-23T19:45:22.235Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2023-03-23T19:45:22.235Z]     return func(*args, **kwargs)
[2023-03-23T19:45:22.235Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2023-03-23T19:45:22.235Z]     ret = func(self, *args, **kwargs)
[2023-03-23T19:45:22.235Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
[2023-03-23T19:45:22.235Z]     raise e
[2023-03-23T19:45:22.235Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2023-03-23T19:45:22.235Z]     return func(self, *args, **kwargs)
[2023-03-23T19:45:22.235Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 949, in query
[2023-03-23T19:45:22.235Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2023-03-23T19:45:22.235Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to query on all shard leaders, err=fail to Query, QueryNode ID = 2, reason=Query 1 failed, reason query shard(channel)  by-dev-rootcoord-dml_63_440295563771433844v0  does not exist
[2023-03-23T19:45:22.235Z]  err %!w(<nil>))>
[2023-03-23T19:45:22.235Z]  (api_request.py:39)
[2023-03-23T19:45:22.235Z] [2023-03-23 18:09:41 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to query on all shard leaders, err=fail to Query, QueryNode ID = 2, reason=Query 1 failed, reason query shard(channel)  by-dev-rootcoord-dml_63_440295563771433844v0  does not exist
[2023-03-23T19:45:22.235Z]  err %!w(<nil>))> (api_request.py:40)
```

### Expected Behavior

pass

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/320/pipeline/187/
2. log: [artifacts-milvus-distributed-pulsar-nightly-320-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/320/artifact/artifacts-milvus-distributed-pulsar-nightly-320-pymilvus-e2e-logs.tar.gz)
3. collection name: delete_sOUBJdav
4. failed time: [2023-03-23T18:09:42.053Z] [gw3] [ 22%] FAILED testcases/test_delete.py::TestDeleteOperation::test_delete_merge_ids_channel_and_sealed
5. other failed cases: 
```
[2023-03-23T18:09:42.308Z] [gw1] [ 22%] FAILED testcases/test_query.py::TestQueryParams::test_query_with_dup_primary_key[8-1]
[2023-03-23T18:12:15.160Z] [gw0] [ 26%] FAILED testcases/test_query.py::TestQueryParams::test_query_output_one_field
[2023-03-23T18:12:51.508Z] [gw1] [ 27%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_with_dup_primary_key[128-True-True-2] 
[2023-03-23T18:56:47.031Z] [gw1] [ 57%] FAILED testcases/test_search.py::TestSearchBase::test_search_ip_brute_force[10-768] 
[2023-03-23T19:18:55.412Z] [gw3] [ 75%] FAILED testcases/test_search.py::TestSearchPagination::test_search_pagination_with_index_partition[100-True-False-11] 
[2023-03-23T19:22:34.609Z] [gw4] [ 78%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_multi_collections[5000-2-128-False-True]
```

**Comment by smellthemoon** [comment]
![1](https://user-images.githubusercontent.com/64083300/227448448-107bd0f4-92ae-454a-922e-13b9c9cab648.png)
![2](https://user-images.githubusercontent.com/64083300/227448537-ba9fa3ce-7c27-4a39-9767-047b0ceae4ce.png)

unsub channel alway removes queryshard

**Comment by smellthemoon** [comment]
related bugs in 2.2.x has merged #22961 
related bugs in master will fixed after qnv2 pr merged.
/unassign @yanliang567 
/assign @NicoYuan1986

**Comment by smellthemoon** [comment]
related #22960

**Comment by NicoYuan1986** [comment]
Not reproduced
