### ISSUE TITLE
[Bug]: Milvus is restarted after running GPU index cases

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#22971]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvus master latest
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.3.0.dev48
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Milvus is restarted after running GPU index cases "test_search_after_different_index_with_min_dim_gpu":
```
milvus-gpu-e2e-test-etcd-0                             1/1     Running     0               22h
milvus-gpu-e2e-test-minio-ddf88fcc5-kxhkb              1/1     Running     0               22h
milvus-gpu-e2e-test-standalone-5fc64458bf-rt4wt        0/1     Running     6 (23s ago)     22h
```

test log:
```
[2023-03-24 14:15:06 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.41274281034157334], [0.3539373608455363]], 'float_vector', {'metric_type': 'L2', 'params': {'nprobe': 64}}, 10, 'int64 >= 0', None, None, 120, -1], kwargs: {'_async': False, 'travel_timestamp': 0} (api_request.py:56)
[2023-03-24 14:15:11 - WARNING - pymilvus.decorators]: [search] retry:4, cost: 0.27s, reason: <_InactiveRpcError: StatusCode.UNAVAILABLE, failed to connect to all addresses> (decorators.py:71)
[2023-03-24 14:15:11 - WARNING - pymilvus.decorators]: [search] retry:5, cost: 0.81s, reason: <_InactiveRpcError: StatusCode.UNAVAILABLE, failed to connect to all addresses> (decorators.py:71)
[2023-03-24 14:15:12 - WARNING - pymilvus.decorators]: [search] retry:6, cost: 2.43s, reason: <_InactiveRpcError: StatusCode.UNAVAILABLE, failed to connect to all addresses> (decorators.py:71)
[2023-03-24 14:15:14 - WARNING - pymilvus.decorators]: [search] retry:7, cost: 7.29s, reason: <_InactiveRpcError: StatusCode.UNAVAILABLE, failed to connect to all addresses> (decorators.py:71)
[2023-03-24 14:15:21 - WARNING - pymilvus.decorators]: [search] retry:8, cost: 21.87s, reason: <_InactiveRpcError: StatusCode.UNAVAILABLE, failed to connect to all addresses> (decorators.py:71)
[2023-03-24 14:15:43 - WARNING - pymilvus.decorators]: [search] retry:9, cost: 60.00s, reason: <_InactiveRpcError: StatusCode.UNAVAILABLE, failed to connect to all addresses> (decorators.py:71)
[2023-03-24 14:16:43 - WARNING - pymilvus.decorators]: [search] retry:10, cost: 60.00s, reason: <_InactiveRpcError: StatusCode.UNAVAILABLE, failed to connect to all addresses> (decorators.py:71)
[2023-03-24 14:17:49 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusUnavailableException: (code=1, message=server Unavailable: Retry timeout: 120s)>, <Time:{'RPC start': '2023-03-24 14:15:06.134909', 'RPC error': '2023-03-24 14:17:49.955278'}> (decorators.py:108)
[2023-03-24 14:17:49 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 518, in search
    return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 487, in _execute_search_requests
    raise pre_err
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 475, in _execute_search_requests
    response = self._stub.Search(request, timeout=timeout)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1679638669.954713000","description":"Error received from peer ipv4:10.100.35.152:19530","file":"src/core/lib/surface/call.cc","file_line":967,"grpc_message":"Socket closed","grpc_status":14}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/binbin/zillizProjects/milvus/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/Users/binbin/zillizProjects/milvus/tests/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 660, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 66, in handler
    raise MilvusUnavailableException(message=f"server Unavailable: {timeout_msg}") from e
pymilvus.exceptions.MilvusUnavailableException: <MilvusUnavailableException: (code=1, message=server Unavailable: Retry timeout: 120s)>
 (api_request.py:39)
[2023-03-24 14:17:49 - ERROR - ci_test]: (api_response) : <MilvusUnavailableException: (code=1, message=server Unavailable: Retry timeout: 120s)> (api_request.py:40)
[2023-03-24 14:17:49 - INFO - ci_test]: search_results_check: checking the searching results (func_check.py:234)
```

### Expected Behavior

No crash

### Steps To Reproduce

```python
def test_search_after_different_index_with_min_dim_gpu(self, index, params, auto_id, _async):
        """
        target: test search after different index with min dim
        method: test search after different index and corresponding search params with dim = 1
        expected: search successfully with limit(topK)
        """
        # 1. initialize with data
        collection_w, _, _, insert_ids, time_stamp = self.init_collection_general(prefix, True, 5000,
                                                                                  partition_num=1,
                                                                                  auto_id=auto_id,
                                                                                  dim=min_dim, is_index=False)[0:5]
        # 2. create index and load
        if params.get("m"):
            params["m"] = min_dim
        if params.get("PQM"):
            params["PQM"] = min_dim
        default_index = {"index_type": index, "params": params, "metric_type": "L2"}
        collection_w.create_index("float_vector", default_index)
        collection_w.load()
        # 3. search
        search_params = cf.gen_search_param(index)
        vectors = [[random.random() for _ in range(min_dim)] for _ in range(default_nq)]
        for search_param in search_params:
            log.info("Searching with search params: {}".format(search_param))
            collection_w.search(vectors[:default_nq], default_search_field,
                                search_param, default_limit,
                                default_search_exp, _async=_async,
                                travel_timestamp=0,
                                check_task=CheckTasks.check_search_results,
                                check_items={"nq": default_nq,
                                             "ids": insert_ids,
                                             "limit": default_limit,
                                             "_async": _async})
```

### Milvus Log

[22971.log](https://github.com/milvus-io/milvus/files/11059005/22971.log)

### Anything else?

collection name: search_collection_hELSeXbf

**Comment by binbinlv** [comment]
I think dim=1 may be the reason caused the issue, other cases are good.

**Comment by binbinlv** [comment]
@Presburger 
Same case with that in #22940,  could you please have a look too?

Thanks.

**Comment by yanliang567** [comment]
@Presburger any updates?

**Comment by binbinlv** [comment]
https://jenkins.milvus.io:18080/blue/organizations/jenkins/milvus-gpu-ci/detail/PR-23642/8/pipeline
standalone:
There is panic:
.//[ci.var.log.containers.ms](http://ci.var.log.containers.ms/)-23642-8-pr-gpu-milvus-standalone-6fc6b955b8-8pdxl_milvus-ci_standalone-76131386499d10289c4b12137d8408a383d972d7570290e45a0b64cb019e4f6a.log:2023-04-28T18:08:06.13651614+08:00 stderr F 	/usr/local/go/src/runtime/panic.go:992 +0x71 fp=0x7f926c8a8310 sp=0x7f926c8a82e0 pc=0x1266531
.//[ci.var.log.containers.ms](http://ci.var.log.containers.ms/)-23642-8-pr-gpu-milvus-standalone-6fc6b955b8-8pdxl_milvus-ci_standalone-76131386499d10289c4b12137d8408a383d972d7570290e45a0b64cb019e4f6a.log:2023-04-28T18:08:06.136522179+08:00 stderr F runtime.sigpanic()
.//[ci.var.log.containers.ms](http://ci.var.log.containers.ms/)-23642-8-pr-gpu-milvus-standalone-6fc6b955b8-8pdxl_milvus-ci_standalone-6fc1ceb2a1a2a5bd64d852d5b2424d19641f7fd71b955db4adc98a9e0a19a266.log:2023-04-28T18:10:46.439880184+08:00 stderr F 	/usr/local/go/src/runtime/panic.go:992 +0x71 fp=0x7f50d55a8310 sp=0x7f50d55a82e0 pc=0x1266531
.//[ci.var.log.containers.ms](http://ci.var.log.containers.ms/)-23642-8-pr-gpu-milvus-standalone-6fc6b955b8-8pdxl_milvus-ci_standalone-6fc1ceb2a1a2a5bd64d852d5b2424d19641f7fd71b955db4adc98a9e0a19a266.log:2023-04-28T18:10:46.439885292+08:00 stderr F runtime.sigpanic()

**Comment by binbinlv** [comment]
Fixed and closed.
