### ISSUE TITLE
[Bug]: using external kafka dependency, add "maxMessageBytes: 524288" to limit message size, not working

### ISSUE THREAD

**Issue by SendTextLi** [milvus-io/milvus#22985]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka): kafka   
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus2.1.3
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 6 * 128G
- GPU: -
- Others: -
```

### Current Behavior

when I use externalKafka config parameter, like:
externalKafka:
  enabled: True
  brokerList: xxx:9092
  securityProtocol: SASL_SSL
  sasl:
    mechanisms: PLAIN
    username: "xxx"
    password: "xxx"
  maxMessageBytes: 524288
then "helm upgrade milvus-even milvus -f ./milvus/values.yaml" to upgrade milvus cluster, and use pymilvus api collection.insert() to insert npy file, which contain 1million embedding vector. this colection contains 23 partitions. Because my external kafka cluster limits message size under 1M, so I config  maxMessageBytes as 524288, which is 0.5M. But I gain result like below:
RPC error: [bulk_insert], <MilvusException: (code=1, message=Broker: Message size too large)>, <Time:{'RPC start': '2023-03-24 17:44:59.265524', 'RPC error': '2023-03-24 17:45:03.011617'}>
Traceback (most recent call last):
  File "main.py", line 89, in <module>
    main(file_path, collection_name)
  File "main.py", line 42, in main
    sub_milvus_insert(path, collection)
  File "/home/vector_search/code-milvus/git_code/code_0316/milvus-tools/src/multi_tools/milvus_command.py", line 57, in sub_milvus_insert
    ret = milvus_insert.milvus_insert_file(collection, data_file)
  File "/home/vector_search/code-milvus/git_code/code_0316/milvus-tools/src/multi_tools/insert_data.py", line 95, in milvus_insert_file
    insert_result = collections.insert(data=value, partition_name=key)
  File "/root/miniconda3/envs/milvus/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 550, in insert
    res = conn.bulk_insert(self._name, entities, partition_name, ids=None, timeout=timeout, schema=schema_dict, **kwargs)
  File "/root/miniconda3/envs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 96, in handler
    raise e
  File "/root/miniconda3/envs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 92, in handler
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/root/miniconda3/envs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 48, in handler
    return func(self, *args, **kwargs)
  File "/root/miniconda3/envs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 359, in bulk_insert
    raise err
  File "/root/miniconda3/envs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 355, in bulk_insert
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Broker: Message size too large)>

### Expected Behavior

insert data success.

### Steps To Reproduce

```markdown
externalKafka:
  enabled: True
  brokerList: xxx:9092
  securityProtocol: SASL_SSL
  sasl:
    mechanisms: PLAIN
    username: "xxx"
    password: "xxx"
  maxMessageBytes: 524288
```

### Milvus Log

RPC error: [bulk_insert], <MilvusException: (code=1, message=Broker: Message size too large)>, <Time:{'RPC start': '2023-03-24 17:44:59.265524', 'RPC error': '2023-03-24 17:45:03.011617'}>
Traceback (most recent call last):
  File "main.py", line 89, in <module>
    main(file_path, collection_name)
  File "main.py", line 42, in main
    sub_milvus_insert(path, collection)
  File "/home/vector_search/code-milvus/git_code/code_0316/milvus-tools/src/multi_tools/milvus_command.py", line 57, in sub_milvus_insert
    ret = milvus_insert.milvus_insert_file(collection, data_file)
  File "/home/vector_search/code-milvus/git_code/code_0316/milvus-tools/src/multi_tools/insert_data.py", line 95, in milvus_insert_file
    insert_result = collections.insert(data=value, partition_name=key)
  File "/root/miniconda3/envs/milvus/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 550, in insert
    res = conn.bulk_insert(self._name, entities, partition_name, ids=None, timeout=timeout, schema=schema_dict, **kwargs)
  File "/root/miniconda3/envs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 96, in handler
    raise e
  File "/root/miniconda3/envs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 92, in handler
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/root/miniconda3/envs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 48, in handler
    return func(self, *args, **kwargs)
  File "/root/miniconda3/envs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 359, in bulk_insert
    raise err
  File "/root/miniconda3/envs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 355, in bulk_insert
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Broker: Message size too large)>

### Anything else?

if community can give me the mothod how to config externalKafka config parameter map will be perfect.

**Comment by xiaofan-luan** [comment]
Hi @SendTextLi,
you will have to tune your kafka message size.
or your can reduce your batch size while insertion.
Both will help

**Comment by SendTextLi** [comment]
Are there no other parameters that can control the size of the message size in values.yaml? If not, what a shame for that !!! @xiaofan-luan Thanks for your responsing.

**Comment by xiaofan-luan** [comment]
change pulsar.maxMessageSize to value smaller than 524288  may help.
ignore pulsar, kafka and pulsar share same config

**Comment by xiaofan-luan** [comment]
is there a config on milvus side we can control the output size to message queue?
@jiaoew1991

**Comment by jiaoew1991** [comment]
`kafka.producer. *` can be followed by any parameters supported by kafka client.
 https://github.com/confluentinc/librdkafka/blob/master/CONFIGURATION.md
