### ISSUE TITLE
[Bug]: Standalone panic with `panic: insertBufferNode flushBufferData failed` during first test for reinstall deploy test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#23004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230324-a59dc9cb
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):rocksmq    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/12268675/227830318-4fd57d78-1b93-4fe2-b435-00a30da5df0a.png)

```
[2023/03/26 11:20:04.453 +00:00] [INFO] [indexcoord/index_coord.go:847] ["IndexCoord DescribeIndex"] [collectionID=440357144269885300] [indexName=]
[2023/03/26 11:20:04.453 +00:00] [WARN] [indexcoord/index_coord.go:849] ["IndexCoord 5 is not ready"]
[2023/03/26 11:20:04.453 +00:00] [WARN] [datacoord/services.go:896] ["DataCoord.GetMetrics failed"] [traceID=176bc3308cb1f248] [nodeID=3] [req="{\"metric_type\":\"system_info\"}"] [error="DataCoord 3 is not ready"]
[2023/03/26 11:20:04.464 +00:00] [WARN] [retry/retry.go:44] ["retry func failed"] ["retry time"=0] [error="role rootcoord[nodeID: 0] is not serving, reason: sate code: Abnormal"]
[2023/03/26 11:20:04.464 +00:00] [ERROR] [datanode/flow_graph_insert_buffer_node.go:503] ["insertBufferNode flushBufferData failed, err = All attempts results:\nattempt #1:role rootcoord[nodeID: 0] is not serving, reason: sate code: Abnormal\nattempt #2:context canceled\n"] [stack="github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Sync\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:503\ngithub.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Operate\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:139\ngithub.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work\n\t/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:127"]
panic: insertBufferNode flushBufferData failed, err = All attempts results:
attempt #1:role rootcoord[nodeID: 0] is not serving, reason: sate code: Abnormal
attempt #2:context canceled


goroutine 83645 [running]:
github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Sync(0xc00ec82f70, 0xc00ba69020?, {0xc008d0bb58?, 0x0?, 0x0?}, 0xc00e7aec00)
	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:504 +0x1285
github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Operate(0xc00ec82f70, {0xc00589f510, 0x1, 0x1})
	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:139 +0x485
github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work(0xc013e140a0)
	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:127 +0x2ac
created by github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start
	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:71 +0x79
```

### Expected Behavior

all test cases passed

### Milvus Log

```
[2023/03/26 11:20:04.464 +00:00] [ERROR] [datanode/flow_graph_insert_buffer_node.go:503] ["insertBufferNode flushBufferData failed, err = All attempts results:\nattempt #1:role rootcoord[nodeID: 0] is not serving, reason: sate code: Abnormal\nattempt #2:context canceled\n"] [stack="github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Sync\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:503\ngithub.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Operate\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:139\ngithub.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work\n\t/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:127"]
panic: insertBufferNode flushBufferData failed, err = All attempts results:
attempt #1:role rootcoord[nodeID: 0] is not serving, reason: sate code: Abnormal
attempt #2:context canceled


goroutine 83645 [running]:
github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Sync(0xc00ec82f70, 0xc00ba69020?, {0xc008d0bb58?, 0x0?, 0x0?}, 0xc00e7aec00)
	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:504 +0x1285
github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Operate(0xc00ec82f70, {0xc00589f510, 0x1, 0x1})
	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:139 +0x485
github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work(0xc013e140a0)
	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:127 +0x2ac
created by github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start
	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:71 +0x79
```
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_for_release_cron/detail/deploy_test_for_release_cron/65/pipeline
log: 

[artifacts-rocksmq-standalone-reinstall-65-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/11074231/artifacts-rocksmq-standalone-reinstall-65-server-logs.1.tar.gz)
[artifacts-rocksmq-standalone-reinstall-65-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/11074232/artifacts-rocksmq-standalone-reinstall-65-pytest-logs.tar.gz)

### Anything else?

It was not reproduced in cluster reinstall mode

**Comment by smellthemoon** [comment]
The log is very similar with #22624 , considered it to be a network problem between milvus and etcd.

**Comment by yanliang567** [comment]
@zhuwenxing lets see if it reproduces tonight.

**Comment by yanliang567** [comment]
/assign @zhuwenxing 
any updates

**Comment by zhuwenxing** [comment]
not reproduced in 2.2.0-20230411-f1c78610
