### ISSUE TITLE
[Bug]: [Nightly]Release a partition of a loaded collection will cause rpc deadline exceeded

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#23048]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:d55c860
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.0.dev48
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Release a partition of a loaded collection will cause rpc deadline exceeded.
```
[2023-03-27T19:36:32.735Z] [2023-03-27 19:21:10 - ERROR - pymilvus.decorators]: RPC error: [release_partitions], <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)>, <Time:{'RPC start': '2023-03-27 19:20:50.877366', 'RPC error': '2023-03-27 19:21:10.878449'}> (decorators.py:108)
[2023-03-27T19:36:32.735Z] [2023-03-27 19:21:10 - ERROR - ci_test]: Traceback (most recent call last):
[2023-03-27T19:36:32.735Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2023-03-27T19:36:32.735Z]     return func(self, *args, **kwargs)
[2023-03-27T19:36:32.735Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 819, in release_partitions
[2023-03-27T19:36:32.735Z]     response = rf.result()
[2023-03-27T19:36:32.735Z]   File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 744, in result
[2023-03-27T19:36:32.735Z]     raise self
[2023-03-27T19:36:32.735Z] grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
[2023-03-27T19:36:32.735Z] 	status = StatusCode.DEADLINE_EXCEEDED
[2023-03-27T19:36:32.735Z] 	details = "Deadline Exceeded"
[2023-03-27T19:36:32.735Z] 	debug_error_string = "{"created":"@1679944870.877819443","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":81,"grpc_status":4}"
[2023-03-27T19:36:32.735Z] >
[2023-03-27T19:36:32.735Z] 
[2023-03-27T19:36:32.735Z] The above exception was the direct cause of the following exception:
[2023-03-27T19:36:32.735Z] 
[2023-03-27T19:36:32.735Z] Traceback (most recent call last):
[2023-03-27T19:36:32.735Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2023-03-27T19:36:32.735Z]     res = func(*args, **_kwargs)
[2023-03-27T19:36:32.735Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2023-03-27T19:36:32.735Z]     return func(*arg, **kwargs)
[2023-03-27T19:36:32.735Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/partition.py", line 250, in release
[2023-03-27T19:36:32.735Z]     return conn.release_partitions(self._collection.name, [self._name], timeout=timeout, **kwargs)
[2023-03-27T19:36:32.735Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2023-03-27T19:36:32.735Z]     raise e
[2023-03-27T19:36:32.735Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2023-03-27T19:36:32.735Z]     return func(*args, **kwargs)
[2023-03-27T19:36:32.735Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2023-03-27T19:36:32.735Z]     ret = func(self, *args, **kwargs)
[2023-03-27T19:36:32.735Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 64, in handler
[2023-03-27T19:36:32.735Z]     raise MilvusException(message=f"rpc deadline exceeded: {timeout_msg}") from e
[2023-03-27T19:36:32.735Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)>
[2023-03-27T19:36:32.735Z]  (api_request.py:39)
[2023-03-27T19:36:32.735Z] [2023-03-27 19:21:10 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)> (api_request.py:40)
```

### Expected Behavior

pass

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/324/pipeline/187
2. log: [artifacts-milvus-distributed-pulsar-nightly-324-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/324/artifact/artifacts-milvus-distributed-pulsar-nightly-324-pymilvus-e2e-logs.tar.gz)
3. collection name: query_SFBe8nbn
4. failed time: [2023-03-27T19:21:14.730Z] [gw5] [ 98%] FAILED testcases/test_utility.py::TestUtilityBase::test_loading_progress_with_release_partition

**Comment by NicoYuan1986** [comment]
Same error:
```
 <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)>
```
Steps:
```
1. create a collection and 2 partitions
2. load partition1
3. drop partition1
4. release partition2 -> raise error
```
case:
```python
@pytest.mark.tags(CaseLabel.L2)
def test_release_load_partition_after_load_drop_partition(self):
    """
    target: test release load partition after load and drop partition
    method: 1. load partition
            2. drop the loaded partition
            3. release another partition
            4. load the partition
    expected: no exception
    """
    collection_w = self.init_collection_general(prefix)[0]
    partition_w1 = self.init_partition_wrap(collection_w, partition1)
    partition_w2 = self.init_partition_wrap(collection_w, partition2)
    partition_w1.load()
    partition_w1.drop()
    partition_w2.release()
    partition_w2.load()
```

**Comment by NicoYuan1986** [comment]
Keep reproducing.
Latest: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/335/pipeline/133/
[artifacts-milvus-standalone-nightly-335-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/335/artifact/artifacts-milvus-standalone-nightly-335-pymilvus-e2e-logs.tar.gz)

**Comment by NicoYuan1986** [comment]
Since the issue reproduces frequently, add the urgent label.

**Comment by NicoYuan1986** [comment]
Update: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/345/pipeline/123

milvus: 3ad9ff7
pymilvus: 2.4.0.dev7

1. log； [artifacts-milvus-standalone-nightly-345-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/345/artifact/artifacts-milvus-standalone-nightly-345-pymilvus-e2e-logs.tar.gz)
2. collection name: collection_QodOdEXR
3. failed time: [2023-04-17T17:58:58.699Z] [gw3] [  6%] FAILED testcases/test_collection.py::TestLoadCollection::test_load_partitions_after_release_partition

**Comment by bigsheeper** [comment]
> Same error:
> 
> ```
>  <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)>
> ```
> 
> Steps:
> 
> ```
> 1. create a collection and 2 partitions
> 2. load partition1
> 3. drop partition1
> 4. release partition2 -> raise error
> ```
> 
> case:
> 
> ```python
> @pytest.mark.tags(CaseLabel.L2)
> def test_release_load_partition_after_load_drop_partition(self):
>     """
>     target: test release load partition after load and drop partition
>     method: 1. load partition
>             2. drop the loaded partition
>             3. release another partition
>             4. load the partition
>     expected: no exception
>     """
>     collection_w = self.init_collection_general(prefix)[0]
>     partition_w1 = self.init_partition_wrap(collection_w, partition1)
>     partition_w2 = self.init_partition_wrap(collection_w, partition2)
>     partition_w1.load()
>     partition_w1.drop()
>     partition_w2.release()
>     partition_w2.load()
> ```

Fixed by https://github.com/milvus-io/milvus/pull/23732
@NicoYuan1986 Please modify the test case, release partition before dropping.
And please help to make a verify.

**Comment by bigsheeper** [comment]
> Update: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/345/pipeline/123
> 
> milvus: 3ad9ff7 pymilvus: 2.4.0.dev7
> 
> 1. log； [artifacts-milvus-standalone-nightly-345-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/345/artifact/artifacts-milvus-standalone-nightly-345-pymilvus-e2e-logs.tar.gz)
> 2. collection name: collection_QodOdEXR
> 3. failed time: [2023-04-17T17:58:58.699Z] [gw3] [  6%] FAILED testcases/test_collection.py::TestLoadCollection::test_load_partitions_after_release_partition

This would be fixed by https://github.com/milvus-io/milvus/pull/23872
@NicoYuan1986

**Comment by NicoYuan1986** [comment]
The error 'rpc deadline exceeded' has been fixed.
