### ISSUE TITLE
[Bug]: Querynode can not recover after querynode pod failure chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#23089]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230328-dc6d4b91
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/12268675/228412962-d882478d-825a-4470-8a9c-d82c21e977ed.png)

### Milvus Log

```
[2023/03/28 19:21:55.933 +00:00] [DEBUG] [pipeline/pipeline.go:45] ["pipeline add exclude info"] [segmentID=440409943215779618] [tss=440410011402502145]
[2023/03/28 19:21:55.933 +00:00] [INFO] [segments/segment_loader.go:110] ["no segment to load"] [traceID=cb86892f927a99df361a4528d5b4afbe] [collectionID=440409943215779594] [segmentType=Growing]
[2023/03/28 19:21:55.933 +00:00] [INFO] [delegator/delegator_data.go:277] ["add growing segments to delegator"] [collectionID=440409943215779594] [channel=by-dev-rootcoord-dml_25_440409943215779594v1] [replicaID=440409943891771403] [segmentIDs="[]"]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x2d863ff]

goroutine 90 [running]:
panic({0x35f8920, 0x5285170})
	/usr/local/go/src/runtime/panic.go:941 +0x397 fp=0xc001ae6c78 sp=0xc001ae6bb8 pc=0x12accf7
runtime.panicmem(...)
	/usr/local/go/src/runtime/panic.go:220
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:818 +0x336 fp=0xc001ae6cc8 sp=0xc001ae6c78 pc=0x12c3d16
github.com/milvus-io/milvus/internal/querynodev2/pipeline.(*pipeline).ExcludedSegments(0xc000dc0ca0, {0xc000fc09a0, 0xd, 0x2b?})
	/go/src/github.com/milvus-io/milvus/internal/querynodev2/pipeline/pipeline.go:47 +0xff fp=0xc001ae6d98 sp=0xc001ae6cc8 pc=0x2d863ff
github.com/milvus-io/milvus/internal/querynodev2.(*QueryNode).WatchDmChannels(0xc00030e360, {0x3dfc038, 0xc001413350}, 0xc00142e420)
	/go/src/github.com/milvus-io/milvus/internal/querynodev2/services.go:254 +0x13a5 fp=0xc001ae74e8 sp=0xc001ae6d98 pc=0x2d92d85
github.com/milvus-io/milvus/internal/distributed/querynode.(*Server).WatchDmChannels(0x40f862cc121fdeba?, {0x3dfc038?, 0xc001413350?}, 0x0?)
	/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/service.go:260 +0x2e fp=0xc001ae7518 sp=0xc001ae74e8 pc=0x2da4fae
github.com/milvus-io/milvus/internal/proto/querypb._QueryNode_WatchDmChannels_Handler.func1({0x3dfc038, 0xc001413350}, {0x38c2400?, 0xc00142e420})
	/go/src/github.com/milvus-io/milvus/internal/proto/querypb/query_coord.pb.go:6007 +0x7b fp=0xc001ae7558 sp=0xc001ae7518 pc=0x2632c3b
github.com/milvus-io/milvus/internal/util/logutil.UnaryTraceLoggerInterceptor({0x3dfc038?, 0xc0014132c0?}, {0x38c2400, 0xc00142e420}, 0xc001ae75b8?, 0xc0003d23a8)
	/go/src/github.com/milvus-io/milvus/internal/util/logutil/grpc_interceptor.go:22 +0x49 fp=0xc001ae7588 sp=0xc001ae7558 pc=0x2617249
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x3dfc038?, 0xc0014132c0?}, {0x38c2400?, 0xc00142e420?})
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a fp=0xc001ae75c8 sp=0xc001ae7588 pc=0x1df007a
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryServerInterceptor.func1({0x3dfc038, 0xc0014131a0}, {0x38c2400, 0xc00142e420}, 0xc00142c660, 0xc00142c680)
	/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.38.0/interceptor.go:342 +0x528 fp=0xc001ae7938 sp=0xc001ae75c8 pc=0x1b0e028
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x3dfc038?, 0xc0014131a0?}, {0x38c2400?, 0xc00142e420?})
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a fp=0xc001ae7978 sp=0xc001ae7938 pc=0x1df007a
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1({0x3dfc038, 0xc0014131a0}, {0x38c2400, 0xc00142e420}, 0xc0001daa18?, 0x35f7480?)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34 +0xbf fp=0xc001ae79d0 sp=0xc001ae7978 pc=0x1deff1f
github.com/milvus-io/milvus/internal/proto/querypb._QueryNode_WatchDmChannels_Handler({0x38e6bc0?, 0xc0001a0ff0}, {0x3dfc038, 0xc0014131a0}, 0xc000d86070, 0xc0005e8990)
	/go/src/github.com/milvus-io/milvus/internal/proto/querypb/que
```

chaos type: pod-failure image tag: master-20230328-dc6d4b91 target pod: querynode
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-cron/detail/chaos-test-kafka-cron/3027/pipeline
log:

[artifacts-querynode-pod-failure-3027-server-logs (2).tar.gz](https://github.com/milvus-io/milvus/files/11095959/artifacts-querynode-pod-failure-3027-server-logs.2.tar.gz)

[artifacts-querynode-pod-failure-3027-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/11095960/artifacts-querynode-pod-failure-3027-pytest-logs.tar.gz)

**Comment by xiaofan-luan** [comment]
seems to be related to querycoordV2

**Comment by yanliang567** [comment]
closed for now as comments above
