### ISSUE TITLE
[Bug]: [perf][standalone] Milvus concurrently search with an error and restart, the error message is"failed to connect to all addresses"

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#23113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230327-d6bfe8fb
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):  rocksmq  
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.0.dev48
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

release_name_prefix：
perf-standalone-master-1-zfttc
deploy_config：
fouramf-server-standalone-8c16m
other_params ：
 --milvus_tag_prefix=master -s 
case_name：
test_concurrent_locust_glove_ivf_flat_search_standalone
standalone：

<img width="1385" alt="截屏2023-03-29 16 07 42" src="https://user-images.githubusercontent.com/34296482/228468503-5d318a0c-03ae-4054-b218-8794f4999b04.png">
server：

```
NAME                                                              READY   STATUS        RESTARTS      AGE     IP              NODE         NOMINATED NODE   READINESS GATES
perf-standalonezfttc-2-20-8630-etcd-0                             1/1     Running       0             37m     10.104.6.96     4am-node13   <none>           <none>
perf-standalonezfttc-2-20-8630-milvus-standalone-dd986cdf5rbbbq   1/1     Running       1 (28m ago)   37m     10.104.13.162   4am-node16   <none>           <none>
perf-standalonezfttc-2-20-8630-minio-6fd88b6875-kk2t7             1/1     Running       0             37m     10.104.6.95     4am-node13   <none>           <none> (cli_client.py:129)
```
client：
```

[2023-03-28 10:16:24,596 - ERROR - fouram]: RPC error: [search], <MilvusUnavailableException: (code=1, message=server Unavailable: Retry timeout: 60s)>, <Time:{'RPC start': '2023-03-28 10:14:51.484136', 'RPC error': '2023-03-28 10:16:24.596019'}> (decorators.py:108)
[2023-03-28 10:16:24,597 - ERROR - fouram]: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 518, in search
    return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 487, in _execute_search_requests
    raise pre_err
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 475, in _execute_search_requests
    response = self._stub.Search(request, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1679998584.595714005","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3260,"referenced_errors":[{"created":"@1679998584.595713448","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":167,"grpc_status":14}]}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/src/fouram/client/util/api_request.py", line 33, in inner_wrapper
    res = func(*args, **kwargs)
  File "/src/fouram/client/util/api_request.py", line 70, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 660, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 66, in handler
    raise MilvusUnavailableException(message=f"server Unavailable: {timeout_msg}") from e
pymilvus.exceptions.MilvusUnavailableException: <MilvusUnavailableException: (code=1, message=server Unavailable: Retry timeout: 60s)>
```

### Steps To Reproduce

```markdown
1. create a collection 
        2. build index on vector column
        3. insert glove 200dim 1m vectors
        4. flush collection
        5. build index on vector column with the same parameters
        6. count the total number of rows
        7. load collection
        8. concurrent search with 1 ,raise an error
        9. clean all collections
```

### Anything else?

```
'client': {'test_case_type': 'ConcurrentClientBase',
            'test_case_name': 'test_concurrent_locust_glove_ivf_flat_search_standalone',
            'test_case_params': {'dataset_params': {'dim': 200,
                                                    'dataset_name': 'glove-200-angular',
                                                    'dataset_size': 1000000,
                                                    'ni_per': 50000,
                                                    'metric_type': 'IP'},
                                 'collection_params': {'other_fields': []},
                                 'load_params': {},
                                 'search_params': {},
                                 'resource_groups_params': {'reset': False},
                                 'index_params': {'index_type': 'IVF_FLAT',
                                                  'index_param': {'nlist': 1024}},
                                 'concurrent_params': {'concurrent_number': 1,
                                                       'during_time': '600',
                                                       'interval': 20,
                                                       'spawn_rate': None},
                                 'concurrent_tasks': [{'type': 'search',
                                                       'weight': 1,
                                                       'params': {'nq': 1,
                                                                  'top_k': 1,
                                                                  'search_param': {'nprobe': 16},
                                                                  'expr': None,
                                                                  'guarantee_timestamp': None,
                                                                  'timeout': 60,
                                                                  'random_data': True}}]},
```

**Comment by smellthemoon** [comment]
<img width="1152" alt="1" src="https://user-images.githubusercontent.com/64083300/228719559-e3baa750-ba31-42ac-98dc-7c2eb092fca7.png">
It seems like the req don't fill in collection id.

**Comment by smellthemoon** [comment]
@jingkl pr has merged, plz check it.

**Comment by smellthemoon** [comment]
related to #23136

**Comment by jingkl** [comment]
This problem still exists

release_name_prefix
perf-standalone-master-1-1680786000
deploy_config
fouramf-server-standalone-8c16m
case_params
empty-file
other_params
 --milvus_tag_prefix=master -s 
case_name
test_concurrent_locust_glove_ivf_flat_search_standalone


server：

```
NAME                                                              READY   STATUS             RESTARTS         AGE    IP              NODE         NOMINATED NODE   READINESS GATES
perf-standalone86000-2-88-6229-etcd-0                             1/1     Running            0                100m   10.104.9.155    4am-node14   <none>           <none>
perf-standalone86000-2-88-6229-milvus-standalone-d96d96d9-zdhw6   0/1     CrashLoopBackOff   16 (2m16s ago)   100m   10.104.12.191   4am-node17   <none>           <none>
perf-standalone86000-2-88-6229-minio-59cc7896ff-cxtdw             1/1     Running            0                100m   10.104.5.205    4am-node12   <none>           <none> 
```


client log：


```
[2023-04-06 13:12:10,229 - ERROR - fouram]: RPC error: [search], <MilvusUnavailableException: (code=1, message=server Unavailable: Retry timeout: 60s)>, <Time:{'RPC start': '2023-04-06 13:10:37.210153', 'RPC error': '2023-04-06 13:12:10.229338'}> (decorators.py:108)
[2023-04-06 13:12:10,231 - ERROR - fouram]: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 518, in search
    return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 487, in _execute_search_requests
    raise pre_err
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 475, in _execute_search_requests
    response = self._stub.Search(request, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1680786730.228960347","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3260,"referenced_errors":[{"created":"@1680786730.228959373","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":167,"grpc_status":14}]}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/src/fouram/client/util/api_request.py", line 33, in inner_wrapper
    res = func(*args, **kwargs)
  File "/src/fouram/client/util/api_request.py", line 70, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 660, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 66, in handler
    raise MilvusUnavailableException(message=f"server Unavailable: {timeout_msg}") from e
pymilvus.exceptions.MilvusUnavailableException: <MilvusUnavailableException: (code=1, message=server Unavailable: Retry timeout: 60s)>
```

**Comment by smellthemoon** [comment]
the same with #23197 
plz help check it. @jingkl
