### ISSUE TITLE
[Bug]: [perf][cluster]Milvus concurrent search errors, querynode crashes multiple times

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#23198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230401-3b9716bb
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.0dev45
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

release_name_prefix:
perf-cluster-master-1680393600
deploy_config:
fouramf-server-cluster-8c16m
case_params:
fouramf-client-gist1m-concurrent-hnsw
other_params:
 --milvus_tag_prefix=master -s --deploy_mode=cluster

server：

```
perf-cluster-ma93600-2-66-2332-etcd-0                             1/1     Running            0                 4h26m   10.104.6.223    4am-node13   <none>           <none>
perf-cluster-ma93600-2-66-2332-etcd-1                             1/1     Running            0                 4h26m   10.104.5.87     4am-node12   <none>           <none>
perf-cluster-ma93600-2-66-2332-etcd-2                             1/1     Running            0                 4h26m   10.104.1.34     4am-node10   <none>           <none>
perf-cluster-ma93600-2-66-2332-milvus-datacoord-cdd577ffb-t7z56   1/1     Running            2 (4h18m ago)     4h26m   10.104.14.167   4am-node18   <none>           <none>
perf-cluster-ma93600-2-66-2332-milvus-datanode-578d9f5f9-n8np5    1/1     Running            2 (4h18m ago)     4h26m   10.104.13.204   4am-node16   <none>           <none>
perf-cluster-ma93600-2-66-2332-milvus-indexcoord-59d7b9f49cr4mz   1/1     Running            0                 4h26m   10.104.12.218   4am-node17   <none>           <none>
perf-cluster-ma93600-2-66-2332-milvus-indexnode-c9c7c69b8-4gbh6   1/1     Running            0                 4h26m   10.104.14.168   4am-node18   <none>           <none>
perf-cluster-ma93600-2-66-2332-milvus-proxy-b88c4b68f-xxsgf       1/1     Running            2 (4h18m ago)     4h26m   10.104.13.205   4am-node16   <none>           <none>
perf-cluster-ma93600-2-66-2332-milvus-querycoord-7468945b6j926f   1/1     Running            2 (4h18m ago)     4h26m   10.104.13.203   4am-node16   <none>           <none>
perf-cluster-ma93600-2-66-2332-milvus-querynode-77fd74684b4g25f   0/1     CrashLoopBackOff   35 (2m8s ago)     4h26m   10.104.12.221   4am-node17   <none>           <none>
perf-cluster-ma93600-2-66-2332-milvus-rootcoord-6dc66d4c4-cvpwv   1/1     Running            2 (4h18m ago)     4h26m   10.104.12.215   4am-node17   <none>           <none>
perf-cluster-ma93600-2-66-2332-minio-0                            1/1     Running            0                 4h26m   10.104.6.225    4am-node13   <none>           <none>
perf-cluster-ma93600-2-66-2332-minio-1                            1/1     Running            0                 4h26m   10.104.4.96     4am-node11   <none>           <none>
perf-cluster-ma93600-2-66-2332-minio-2                            1/1     Running            0                 4h26m   10.104.9.50     4am-node14   <none>           <none>
perf-cluster-ma93600-2-66-2332-minio-3                            1/1     Running            0                 4h26m   10.104.5.90     4am-node12   <none>           <none>
perf-cluster-ma93600-2-66-2332-pulsar-bookie-0                    1/1     Running            0                 4h26m   10.104.9.45     4am-node14   <none>           <none>
perf-cluster-ma93600-2-66-2332-pulsar-bookie-1                    1/1     Running            0                 4h26m   10.104.6.230    4am-node13   <none>           <none>
perf-cluster-ma93600-2-66-2332-pulsar-bookie-2                    1/1     Running            0                 4h26m   10.104.1.40     4am-node10   <none>           <none>
perf-cluster-ma93600-2-66-2332-pulsar-bookie-init-hc745           0/1     Completed          0                 4h26m   10.104.9.31     4am-node14   <none>           <none>
perf-cluster-ma93600-2-66-2332-pulsar-broker-0                    1/1     Running            0                 4h26m   10.104.5.74     4am-node12   <none>           <none>
perf-cluster-ma93600-2-66-2332-pulsar-proxy-0                     1/1     Running            0                 4h26m   10.104.1.26     4am-node10   <none>           <none>
perf-cluster-ma93600-2-66-2332-pulsar-pulsar-init-7fmx6           0/1     Completed          0                 4h26m   10.104.9.30     4am-node14   <none>           <none>
perf-cluster-ma93600-2-66-2332-pulsar-recovery-0                  1/1     Running            0                 4h26m   10.104.9.32     4am-node14   <none>           <none>
perf-cluster-ma93600-2-66-2332-pulsar-zookeeper-0                 1/1     Running            0                 4h26m   10.104.5.85     4am-node12   <none>           <none>
perf-cluster-ma93600-2-66-2332-pulsar-zookeeper-1                 1/1     Running            0                 4h25m   10.104.9.63     4am-node14   <none>           <none>
perf-cluster-ma93600-2-66-2332-pulsar-zookeeper-2                 1/1     Running            0                 4h22m   10.104.6.253    4am-node13   <none>           <none>
```

client log；

```
[2023-04-02 03:42:05,916 - ERROR - fouram]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=attempt #0: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_1_440505234477547661v1 is not available in any replica, err=<nil>: attempt #1: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_1_440505234477547661v1 is not available in any replica, err=<nil>: attempt #2: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_0_440505234477547661v0 is not available in any replica, err=<nil>: attempt #3: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_1_440505234477547661v1 is not available in any replica, err=<nil>: attempt #4: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_1_440505234477547661v1 is not available in any replica, err=<nil>: attempt #5: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_1_440505234477547661v1 is not available in any replica, err=<nil>: attempt #6: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_1_440505234477547661v1 is not available in any replica, err=<nil>: context done during sleep after run#6: context deadline exceeded)> (api_request.py:49)
[2023-04-02 03:42:05,916 - ERROR - fouram]: [CheckFunc] search request check failed, response:<MilvusException: (code=1, message=fail to search on all shard leaders, err=attempt #0: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_1_440505234477547661v1 is not available in any replica, err=<nil>: attempt #1: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_1_440505234477547661v1 is not available in any replica, err=<nil>: attempt #2: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_0_440505234477547661v0 is not available in any replica, err=<nil>: attempt #3: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_1_440505234477547661v1 is not available in any replica, err=<nil>: attempt #4: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_1_440505234477547661v1 is not available in any replica, err=<nil>: attempt #5: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_1_440505234477547661v1 is not available in any replica, err=<nil>: attempt #6: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_1_440505234477547661v1 is not available in any replica, err=<nil>: context done during sleep after run#6: context deadline exceeded)> (func_check.py:43)
[2023-04-02 03:42:05,935 - ERROR - fouram]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=attempt #0: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_0_440505234477547661v0 is not available in any replica, err=<nil>: attempt #1: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_1_440505234477547661v1 is not available in any replica, err=<nil>: attempt #2: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_1_440505234477547661v1 is not available in any replica, err=<nil>: attempt #3: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_1_440505234477547661v1 is not available in any replica, err=<nil>: attempt #4: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_1_440505234477547661v1 is not available in any replica, err=<nil>: attempt #5: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_1_440505234477547661v1 is not available in any replica, err=<nil>: attempt #6: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_1_440505234477547661v1 is not available in any replica, err=<nil>: context done during sleep after run#6: context deadline exceeded)>, <Time:{'RPC start': '2023-04-02 03:41:45.913155', 'RPC error': '2023-04-02 03:42:05.935821'}> (decorators.py:108)
[2023-04-02 03:42:05,936 - ERROR - fouram]: Traceback (most recent call last):
  File "/src/fouram/client/util/api_request.py", line 33, in inner_wrapper
    res = func(*args, **kwargs)
  File "/src/fouram/client/util/api_request.py", line 70, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 660, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 518, in search
    return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 487, in _execute_search_requests
    raise pre_err
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 478, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=attempt #0: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_0_440505234477547661v0 is not available in any replica, err=<nil>: attempt #1: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_1_440505234477547661v1 is not available in any replica, err=<nil>: attempt #2: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_1_440505234477547661v1 is not available in any replica, err=<nil>: attempt #3: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_1_440505234477547661v1 is not available in any replica, err=<nil>: attempt #4: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_1_440505234477547661v1 is not available in any replica, err=<nil>: attempt #5: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_1_440505234477547661v1 is not available in any replica, err=<nil>: attempt #6: fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_1_440505234477547661v1 is not available in any replica, err=<nil>: context done during sleep after run#6: context deadline exceeded)>
 (api_request.py:48)
```

### Steps To Reproduce

```markdown
1. create a collection 
        2. build index on vector column
        3. insert 1m gist768d of vectors
        4. flush collection
        5. build index on vector column with the same parameters
        6. count the total number of rows
        7. load collection
        8. perform concurrent operations
        9. clean all collections or not
```

### Anything else?

```
'client': {'test_case_type': 'ConcurrentClientBase',
            'test_case_name': 'test_concurrent_locust_custom_parameters',
            'test_case_params': {'dataset_params': {'dim': 768,
                                                    'dataset_name': 'gist',
                                                    'dataset_size': '1m',
                                                    'ni_per': 1000,
                                                    'metric_type': 'L2'},
                                 'collection_params': {'other_fields': []},
                                 'load_params': {},
                                 'search_params': {},
                                 'index_params': {'index_type': 'HNSW',
                                                  'index_param': {'M': 8,
                                                                  'efConstruction': 200}},
                                 'concurrent_params': {'concurrent_number': 100,
                                                       'during_time': 3600,
                                                       'interval': 20,
                                                       'spawn_rate': None},
                                 'concurrent_tasks': [{'type': 'search',
                                                       'weight': 1,
                                                       'params': {'nq': 1,
                                                                  'top_k': 1,
                                                                  'search_param': {'ef': 16},
                                                                  'random_data': True}}]},
```

**Comment by XuanYang-cn** [comment]
![image](https://user-images.githubusercontent.com/51370125/230557864-9842bc4d-4485-4775-a2c8-cf679d2bab0b.png)

seems the same as #23110

**Comment by XuanYang-cn** [comment]
dup to #23110
