### ISSUE TITLE
[Bug]: Create milvus cluster use external MinIO, cluster can't be created successfully, because query node logs error:too many colons in address

### ISSUE THREAD

**Issue by smallersoup** [milvus-io/milvus#23202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.4
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):     pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): 
- OS(Ubuntu or CentOS): Centos K8s
- CPU/Memory: 88c/512G
- GPU: 
- Others:
```

### Current Behavior

milvus cluster can't be created successfully

```yaml
# k get milvus -n openai milvus-t   -o yaml
---
  conditions:
  - lastTransitionTime: "2023-04-02T13:46:06Z"
    message: Etcd endpoints is healthy
    reason: EtcdReady
    status: "True"
    type: EtcdReady
  - lastTransitionTime: "2023-04-02T13:44:07Z"
    reason: StorageReady
    status: "True"
    type: StorageReady
  - lastTransitionTime: "2023-04-02T13:47:03Z"
    message: MsgStream is ready
    reason: MsgStreamReady
    status: "True"
    type: MsgStreamReady
  - lastTransitionTime: "2023-04-03T08:37:32Z"
    message: '[datacoord querycoord indexcoord datanode querynode proxy] not ready,
      detail: component[datacoord]: pod[milvus-t-milvus-datacoord-64494cb7b9-k9k2b]:
      container[datacoord]: restartCount[183] lastState[terminated] reason[Completed]'
    reason: MilvusComponentNotHealthy
    status: "False"
    type: MilvusReady
  - lastTransitionTime: "2023-04-02T13:47:32Z"
    message: Milvus components[datacoord,querycoord,indexcoord,datanode,querynode,proxy]
      are updating
    reason: MilvusComponentsUpdating
    status: "False"
    type: MilvusUpdated
  endpoint: milvus-t-milvus.openai:19530
  ingress:
    loadBalancer: {}
  observedGeneration: 1
  replicas:
    indexNode: 1
    rootCoord: 1
  status: Pending
---
```

querynode pod starts failed, Logs show that connecting MinIO address illegal: address 172.24.149.129: TCP: / / 172.24.149.129:80: too many colons in the address.  as follows

```yaml
# k get pod -n openai -o wide | grep milvus-t-milvus-querynode
milvus-t-milvus-querynode-74cb6887bb-j9qcx        0/1     CrashLoopBackOff   225        18h     172.24.152.119   172.24.248.6    <none>           <none>

# k logs -f  -n openai milvus-t-milvus-querynode-74cb6887bb-j9qcx
2023/04/03 08:33:50 maxprocs: Leaving GOMAXPROCS=104: CPU quota undefined

    __  _________ _   ____  ______    
   /  |/  /  _/ /| | / / / / / __/    
  / /|_/ // // /_| |/ / /_/ /\ \    
 /_/  /_/___/____/___/\____/___/     

Welcome to use Milvus!
Version:   v2.2.4
Built:     Fri Mar 17 09:52:44 UTC 2023
GitCommit: bbc21fe8
GoVersion: go version go1.18.3 linux/amd64

open pid file: /run/milvus/querynode.pid
lock pid file: /run/milvus/querynode.pid
[2023/04/03 08:33:50.255 +00:00] [INFO] [roles/roles.go:192] ["starting running Milvus components"]
[2023/04/03 08:33:50.255 +00:00] [INFO] [roles/roles.go:134] ["Enable Jemalloc"] ["Jemalloc Path"=/milvus/lib/libjemalloc.so]
[2023/04/03 08:33:50.255 +00:00] [INFO] [management/server.go:68] ["management listen"] [addr=:9091]
[2023/04/03 08:33:50.267 +00:00] [INFO] [config/etcd_source.go:145] ["start refreshing configurations"]
[2023/04/03 08:33:50.267 +00:00] [INFO] [paramtable/quota_param.go:532] ["init disk quota"] [diskQuota(MB)=+inf]
[2023/04/03 08:33:50.267 +00:00] [INFO] [paramtable/component_param.go:1400] ["init segment max idle time"] [value=10m0s]
[2023/04/03 08:33:50.267 +00:00] [INFO] [paramtable/component_param.go:1405] ["init segment min size from idle to sealed"] [value=16]
[2023/04/03 08:33:50.267 +00:00] [INFO] [paramtable/component_param.go:1410] ["init segment max binlog file to sealed"] [value=32]
[2023/04/03 08:33:50.269 +00:00] [INFO] [paramtable/base_table.go:142] ["cannot find etcd.endpoints"]
[2023/04/03 08:33:50.269 +00:00] [INFO] [paramtable/hook_config.go:19] ["hook config"] [hook={}]
[2023/04/03 08:33:50.281 +00:00] [INFO] [config/etcd_source.go:145] ["start refreshing configurations"]
[2023/04/03 08:33:50.282 +00:00] [DEBUG] [paramtable/grpc_param.go:153] [initServerMaxSendSize] [role=querynode] [grpc.serverMaxSendSize=536870912]
[2023/04/03 08:33:50.282 +00:00] [DEBUG] [paramtable/grpc_param.go:175] [initServerMaxRecvSize] [role=querynode] [grpc.serverMaxRecvSize=536870912]
[2023/04/03 08:33:50.282 +00:00] [INFO] [querynode/service.go:106] [QueryNode] [port=21123]
[2023/04/03 08:33:50.282 +00:00] [INFO] [querynode/service.go:122] ["QueryNode connect to etcd successfully"]
[2023/04/03 08:33:50.383 +00:00] [INFO] [querynode/service.go:132] [QueryNode] [State=Initializing]
[2023/04/03 08:33:50.383 +00:00] [INFO] [querynode/query_node.go:251] ["QueryNode session info"] [metaPath=milvus-t/meta]
[2023/04/03 08:33:50.383 +00:00] [INFO] [sessionutil/session_util.go:197] ["Session try to connect to etcd"]
[2023/04/03 08:33:50.384 +00:00] [INFO] [sessionutil/session_util.go:212] ["Session connect to etcd success"]
[2023/04/03 08:33:50.393 +00:00] [INFO] [sessionutil/session_util.go:295] ["Session get serverID success"] [key=id] [ServerId=596]
[2023/04/03 08:33:50.403 +00:00] [INFO] [config/etcd_source.go:145] ["start refreshing configurations"]
[2023/04/03 08:33:50.403 +00:00] [INFO] [paramtable/quota_param.go:532] ["init disk quota"] [diskQuota(MB)=+inf]
[2023/04/03 08:33:50.403 +00:00] [INFO] [paramtable/component_param.go:1400] ["init segment max idle time"] [value=10m0s]
[2023/04/03 08:33:50.403 +00:00] [INFO] [paramtable/component_param.go:1405] ["init segment min size from idle to sealed"] [value=16]
[2023/04/03 08:33:50.403 +00:00] [INFO] [paramtable/component_param.go:1410] ["init segment max binlog file to sealed"] [value=32]
[2023/04/03 08:33:50.404 +00:00] [INFO] [paramtable/base_table.go:142] ["cannot find etcd.endpoints"]
[2023/04/03 08:33:50.405 +00:00] [INFO] [paramtable/hook_config.go:19] ["hook config"] [hook={}]
[2023/04/03 08:33:50.405 +00:00] [INFO] [logutil/logutil.go:165] ["Log directory"] [configDir=]
[2023/04/03 08:33:50.405 +00:00] [INFO] [logutil/logutil.go:166] ["Set log file to "] [path=]
[2023/04/03 08:33:50.405 +00:00] [INFO] [querynode/query_node.go:163] ["QueryNode init session"] [nodeID=596] ["node address"=172.24.152.119:21123]
[2023/04/03 08:33:50.405 +00:00] [INFO] [querynode/query_node.go:267] ["QueryNode init rateCollector done"] [nodeID=596]
[2023/04/03 08:33:50.405 +00:00] [ERROR] [querynode/query_node.go:271] ["QueryNode init vector storage failed"] [error="address 172.24.149.129:tcp://172.24.149.129:80: too many colons in address"] [stack="github.com/milvus-io/milvus/internal/querynode.(*QueryNode).Init.func1\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/query_node.go:271\nsync.(*Once).doSlow\n\t/usr/local/go/src/sync/once.go:68\nsync.(*Once).Do\n\t/usr/local/go/src/sync/once.go:59\ngithub.com/milvus-io/milvus/internal/querynode.(*QueryNode).Init\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/query_node.go:249\ngithub.com/milvus-io/milvus/internal/distributed/querynode.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/service.go:133\ngithub.com/milvus-io/milvus/internal/distributed/querynode.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/service.go:213\ngithub.com/milvus-io/milvus/cmd/components.(*QueryNode).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/query_node.go:54\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:102"]
[2023/04/03 08:33:50.405 +00:00] [ERROR] [querynode/service.go:134] ["QueryNode init error: "] [error="address 172.24.149.129:tcp://172.24.149.129:80: too many colons in address"] [stack="github.com/milvus-io/milvus/internal/distributed/querynode.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/service.go:134\ngithub.com/milvus-io/milvus/internal/distributed/querynode.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/service.go:213\ngithub.com/milvus-io/milvus/cmd/components.(*QueryNode).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/query_node.go:54\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:102"]
panic: address 172.24.149.129:tcp://172.24.149.129:80: too many colons in address

goroutine 275 [running]:
github.com/milvus-io/milvus/cmd/components.(*QueryNode).Run(0x5859fc0?)
        /go/src/github.com/milvus-io/milvus/cmd/components/query_node.go:55 +0x56
github.com/milvus-io/milvus/cmd/roles.runComponent[...].func1()
        /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:102 +0x18e
created by github.com/milvus-io/milvus/cmd/roles.runComponent[...]
        /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:85 +0x18a
```

### Expected Behavior

milvus-t-milvus-querynode-74cb6887bb-j9qcx Pod starts status to Running.
milvus cluster can be created successfully

### Steps To Reproduce

```markdown
1. Kubernetes cluster version:v1.18.14
2. Create the following yaml：

# cat milvus_cluster_default.yaml
# This is a sample to deploy a milvus cluster in milvus-operator's default configurations.
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: milvus-t
  namespace: openai
  labels:
    app: milvus
spec:
  mode: cluster
  dependencies:
    storage:
      external: true
      endpoint: 172.24.149.129:80
      secretRef: minio-creds-secret
  components: {}
  config: {}


3. kubectl apply -f milvus_cluster_default.yaml

4. kubectl get pod -n openai 
```shell
# k get pod -n openai 
NAME                                              READY   STATUS             RESTARTS   AGE
milvus-t-etcd-0                                   1/1     Running            0          20h
milvus-t-etcd-1                                   1/1     Running            0          20h
milvus-t-etcd-2                                   1/1     Running            0          20h
milvus-t-milvus-datacoord-64494cb7b9-k9k2b        0/1     Running            194        20h
milvus-t-milvus-datanode-5b6bbb4488-c62pm         0/1     CrashLoopBackOff   195        20h
milvus-t-milvus-indexcoord-7988c688df-rz4ht       0/1     CrashLoopBackOff   196        20h
milvus-t-milvus-indexnode-85cf4fc9bb-m5fgn        1/1     Running            0          20h
milvus-t-milvus-proxy-6c8c487768-r5x7f            0/1     Running            193        20h
milvus-t-milvus-querycoord-55c8b66477-zlq5q       0/1     Running            192        20h
milvus-t-milvus-querynode-74cb6887bb-j9qcx        0/1     CrashLoopBackOff   240        20h
milvus-t-milvus-rootcoord-74c87cc49-swm69         1/1     Running            0          20h
milvus-t-pulsar-bookie-0                          1/1     Running            0          20h
milvus-t-pulsar-bookie-1                          1/1     Running            0          20h
milvus-t-pulsar-bookie-2                          1/1     Running            0          20h
milvus-t-pulsar-bookie-init-bm2hb                 0/1     Completed          0          20h
milvus-t-pulsar-broker-0                          1/1     Running            0          20h
milvus-t-pulsar-proxy-0                           1/1     Running            0          20h
milvus-t-pulsar-pulsar-init-f6l2x                 0/1     Completed          0          20h
milvus-t-pulsar-recovery-0                        1/1     Running            0          20h
milvus-t-pulsar-zookeeper-0                       1/1     Running            0          20h
milvus-t-pulsar-zookeeper-1                       1/1     Running            0          20h
milvus-t-pulsar-zookeeper-2                       1/1     Running            0          20h
minio-log-0                                       1/1     Running            0          3d1h
minio-log-search-api-69544f69dd-2p5rh             1/1     Running            3          3d1h
minio-prometheus-0                                2/2     Running            0          3d1h
minio-ss-0-0                                      1/1     Running            0          3d1h
minio-ss-0-1                                      1/1     Running            0          3d1h
minio-ss-0-2                                      1/1     Running            0          3d1h
```
```


### Milvus Log

Pod ：milvus-t-milvus-querynode's logs：
```shell
# k logs -f -n openai milvus-t-milvus-querynode-74cb6887bb-j9qcx
2023/04/03 09:50:48 maxprocs: Leaving GOMAXPROCS=104: CPU quota undefined

    __  _________ _   ____  ______    
   /  |/  /  _/ /| | / / / / / __/    
  / /|_/ // // /_| |/ / /_/ /\ \    
 /_/  /_/___/____/___/\____/___/     

Welcome to use Milvus!
Version:   v2.2.4
Built:     Fri Mar 17 09:52:44 UTC 2023
GitCommit: bbc21fe8
GoVersion: go version go1.18.3 linux/amd64

open pid file: /run/milvus/querynode.pid
lock pid file: /run/milvus/querynode.pid
[2023/04/03 09:50:48.247 +00:00] [INFO] [roles/roles.go:192] ["starting running Milvus components"]
[2023/04/03 09:50:48.247 +00:00] [INFO] [roles/roles.go:134] ["Enable Jemalloc"] ["Jemalloc Path"=/milvus/lib/libjemalloc.so]
[2023/04/03 09:50:48.248 +00:00] [INFO] [management/server.go:68] ["management listen"] [addr=:9091]
[2023/04/03 09:50:48.260 +00:00] [INFO] [config/etcd_source.go:145] ["start refreshing configurations"]
[2023/04/03 09:50:48.260 +00:00] [INFO] [paramtable/quota_param.go:532] ["init disk quota"] [diskQuota(MB)=+inf]
[2023/04/03 09:50:48.260 +00:00] [INFO] [paramtable/component_param.go:1400] ["init segment max idle time"] [value=10m0s]
[2023/04/03 09:50:48.260 +00:00] [INFO] [paramtable/component_param.go:1405] ["init segment min size from idle to sealed"] [value=16]
[2023/04/03 09:50:48.260 +00:00] [INFO] [paramtable/component_param.go:1410] ["init segment max binlog file to sealed"] [value=32]
[2023/04/03 09:50:48.263 +00:00] [INFO] [paramtable/base_table.go:142] ["cannot find etcd.endpoints"]
[2023/04/03 09:50:48.263 +00:00] [INFO] [paramtable/hook_config.go:19] ["hook config"] [hook={}]
[2023/04/03 09:50:48.275 +00:00] [INFO] [config/etcd_source.go:145] ["start refreshing configurations"]
[2023/04/03 09:50:48.275 +00:00] [DEBUG] [paramtable/grpc_param.go:153] [initServerMaxSendSize] [role=querynode] [grpc.serverMaxSendSize=536870912]
[2023/04/03 09:50:48.275 +00:00] [DEBUG] [paramtable/grpc_param.go:175] [initServerMaxRecvSize] [role=querynode] [grpc.serverMaxRecvSize=536870912]
[2023/04/03 09:50:48.275 +00:00] [INFO] [querynode/service.go:106] [QueryNode] [port=21123]
[2023/04/03 09:50:48.276 +00:00] [INFO] [querynode/service.go:122] ["QueryNode connect to etcd successfully"]
[2023/04/03 09:50:48.376 +00:00] [INFO] [querynode/service.go:132] [QueryNode] [State=Initializing]
[2023/04/03 09:50:48.376 +00:00] [INFO] [querynode/query_node.go:251] ["QueryNode session info"] [metaPath=milvus-t/meta]
[2023/04/03 09:50:48.376 +00:00] [INFO] [sessionutil/session_util.go:197] ["Session try to connect to etcd"]
[2023/04/03 09:50:48.379 +00:00] [INFO] [sessionutil/session_util.go:212] ["Session connect to etcd success"]
[2023/04/03 09:50:48.384 +00:00] [INFO] [sessionutil/session_util.go:295] ["Session get serverID success"] [key=id] [ServerId=635]
[2023/04/03 09:50:48.396 +00:00] [INFO] [config/etcd_source.go:145] ["start refreshing configurations"]
[2023/04/03 09:50:48.397 +00:00] [INFO] [paramtable/quota_param.go:532] ["init disk quota"] [diskQuota(MB)=+inf]
[2023/04/03 09:50:48.397 +00:00] [INFO] [paramtable/component_param.go:1400] ["init segment max idle time"] [value=10m0s]
[2023/04/03 09:50:48.397 +00:00] [INFO] [paramtable/component_param.go:1405] ["init segment min size from idle to sealed"] [value=16]
[2023/04/03 09:50:48.397 +00:00] [INFO] [paramtable/component_param.go:1410] ["init segment max binlog file to sealed"] [value=32]
[2023/04/03 09:50:48.398 +00:00] [INFO] [paramtable/base_table.go:142] ["cannot find etcd.endpoints"]
[2023/04/03 09:50:48.398 +00:00] [INFO] [paramtable/hook_config.go:19] ["hook config"] [hook={}]
[2023/04/03 09:50:48.398 +00:00] [INFO] [logutil/logutil.go:165] ["Log directory"] [configDir=]
[2023/04/03 09:50:48.398 +00:00] [INFO] [logutil/logutil.go:166] ["Set log file to "] [path=]
[2023/04/03 09:50:48.398 +00:00] [INFO] [querynode/query_node.go:163] ["QueryNode init session"] [nodeID=635] ["node address"=172.24.152.119:21123]
[2023/04/03 09:50:48.398 +00:00] [INFO] [querynode/query_node.go:267] ["QueryNode init rateCollector done"] [nodeID=635]
[2023/04/03 09:50:48.398 +00:00] [ERROR] [querynode/query_node.go:271] ["QueryNode init vector storage failed"] [error="address 172.24.149.129:tcp://172.24.149.129:80: too many colons in address"] [stack="github.com/milvus-io/milvus/internal/querynode.(*QueryNode).Init.func1\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/query_node.go:271\nsync.(*Once).doSlow\n\t/usr/local/go/src/sync/once.go:68\nsync.(*Once).Do\n\t/usr/local/go/src/sync/once.go:59\ngithub.com/milvus-io/milvus/internal/querynode.(*QueryNode).Init\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/query_node.go:249\ngithub.com/milvus-io/milvus/internal/distributed/querynode.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/service.go:133\ngithub.com/milvus-io/milvus/internal/distributed/querynode.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/service.go:213\ngithub.com/milvus-io/milvus/cmd/components.(*QueryNode).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/query_node.go:54\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:102"]
[2023/04/03 09:50:48.398 +00:00] [ERROR] [querynode/service.go:134] ["QueryNode init error: "] [error="address 172.24.149.129:tcp://172.24.149.129:80: too many colons in address"] [stack="github.com/milvus-io/milvus/internal/distributed/querynode.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/service.go:134\ngithub.com/milvus-io/milvus/internal/distributed/querynode.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/service.go:213\ngithub.com/milvus-io/milvus/cmd/components.(*QueryNode).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/query_node.go:54\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:102"]
panic: address 172.24.149.129:tcp://172.24.149.129:80: too many colons in address

goroutine 135 [running]:
github.com/milvus-io/milvus/cmd/components.(*QueryNode).Run(0x5859fc0?)
        /go/src/github.com/milvus-io/milvus/cmd/components/query_node.go:55 +0x56
github.com/milvus-io/milvus/cmd/roles.runComponent[...].func1()
        /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:102 +0x18e
created by github.com/milvus-io/milvus/cmd/roles.runComponent[...]
        /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:85 +0x18a
```

Pod ：milvus-t-milvus-proxy's logs：
```shell 
$ k logs -f -n openai milvus-t-milvus-proxy-6c8c487768-r5x7f   

[2023/04/03 09:51:40.723 +00:00] [WARN] [client/client.go:98] ["DataCoordClient, not existed in msess "] [key=datacoord] ["len of msess"=0]
[2023/04/03 09:51:40.723 +00:00] [ERROR] [grpcclient/client.go:158] ["failed to get client address"] [error="find no available datacoord, check datacoord state"] [stack="github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).connect\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:158\ngithub.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).GetGrpcClient\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:131\ngithub.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).callOnce\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:256\ngithub.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:327\ngithub.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).GetComponentStates\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:126\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates.func1\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:65\ngithub.com/milvus-io/milvus/internal/util/retry.Do\n\t/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:42\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:89\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentHealthy\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:104\ngithub.com/milvus-io/milvus/internal/distributed/proxy.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:410\ngithub.com/milvus-io/milvus/internal/distributed/proxy.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:292\ngithub.com/milvus-io/milvus/cmd/components.(*Proxy).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/proxy.go:53\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:102"]
[2023/04/03 09:51:40.723 +00:00] [ERROR] [grpcclient/client.go:330] ["ClientBase ReCall grpc second call get error"] [role=datacoord] [error="err: find no available datacoord, check datacoord state\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:329 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:126 github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).GetComponentStates\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:65 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates.func1\n/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:42 github.com/milvus-io/milvus/internal/util/retry.Do\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:89 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:104 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentHealthy\n/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:410 github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).init\n/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:292 github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).Run\n/go/src/github.com/milvus-io/milvus/cmd/components/proxy.go:53 github.com/milvus-io/milvus/cmd/components.(*Proxy).Run\n"] [stack="github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:330\ngithub.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).GetComponentStates\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:126\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates.func1\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:65\ngithub.com/milvus-io/milvus/internal/util/retry.Do\n\t/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:42\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:89\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentHealthy\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:104\ngithub.com/milvus-io/milvus/internal/distributed/proxy.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:410\ngithub.com/milvus-io/milvus/internal/distributed/proxy.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:292\ngithub.com/milvus-io/milvus/cmd/components.(*Proxy).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/proxy.go:53\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:102"]
[2023/04/03 09:51:42.017 +00:00] [ERROR] [roles/roles.go:318] ["Get signal to exit\n"] [signal=terminated] [stack="github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:318\ngithub.com/milvus-io/milvus/cmd/milvus.(*run).execute\n\t/go/src/github.com/milvus-io/milvus/cmd/milvus/run.go:112\ngithub.com/milvus-io/milvus/cmd/milvus.RunMilvus\n\t/go/src/github.com/milvus-io/milvus/cmd/milvus/milvus.go:60\nmain.main\n\t/go/src/github.com/milvus-io/milvus/cmd/main.go:26\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"]
[2023/04/03 09:51:42.018 +00:00] [INFO] [proxy/service.go:504] ["Proxy stop"] ["internal address"=172.24.152.75:19529] ["external address"=172.24.152.75:19529]
[2023/04/03 09:51:42.018 +00:00] [INFO] [proxy/service.go:522] ["Graceful stop grpc internal server..."]
[2023/04/03 09:51:42.018 +00:00] [INFO] [proxy/service.go:526] ["Graceful stop grpc external server..."]
```

CR：milvus
```shell
# k get milvus -n openai 
NAME       MODE      STATUS    UPDATED   AGE
milvus-t   cluster   Pending   False     20h
```

### Anything else?

```yaml
# k get cm -n openai milvus-t    -o yaml
apiVersion: v1
data:
  user.yaml: |
    etcd:
      endpoints:
      - milvus-t-etcd.openai:2379
      rootPath: milvus-t
    messageQueue: pulsar
    minio:
      accessKeyID: xxxx
      address: 172.24.149.129
      bucketName: milvus-t
      port: 80
      secretAccessKey: xxxx
    msgChannel:
      chanNamePrefix:
        cluster: milvus-t
    pulsar:
      address: milvus-t-pulsar-proxy.openai
      port: 6650
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: milvus-t
    app.kubernetes.io/managed-by: milvus-operator
    app.kubernetes.io/name: milvus
  name: milvus-t
  namespace: openai
  ownerReferences:
  - apiVersion: milvus.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: Milvus
    name: milvus-t
    uid: 28a6d04d-087f-446c-b032-4e2c367f9162
```

**Comment by yanliang567** [comment]
/assign @locustbaby 
could you please help on this?

/unassign

**Comment by locustbaby** [comment]
https://github.com/milvus-io/milvus-helm/issues/400

**Comment by yanliang567** [comment]
@locustbaby any updates here?
