### ISSUE TITLE
[Bug]: proxy panic panic: dyh popPChanStats failed, err=code: UnexpectedError, reason: code: CollectionNotExists, reason: can't find collection

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#23302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: bigsheeper-2304-memory-sync-aed2c6c-20230407
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. concurrent insert case
```
@pytest.mark.locust
    def test_concurrent_locust_insert_partitions(self, input_params: InputParamsBase):
        """
        :test steps:
            1. concurrent test and calculation of RT and QPS
        """
        from parameters.input_params import param_info
        data_size = "5k"
        param_info.deploy_skip = True

        # concurrent tasks
        concurrent_tasks = [
            ConcurrentParams.params_scene_insert_partition(weight=1, data_size='1w', ni=5, timeout=30)]

        # concurrent params
        default_case_params = ConcurrentParams().params_scene_concurrent(
            concurrent_tasks, concurrent_number=[5], during_time="3m", interval=10, dim=128, dataset_size=data_size, ni_per=5000)

        self.concurrency_template(input_params=input_params, cpu=dp.min_cpu, mem=dp.min_mem, deploy_mode=CLUSTER, old_version_format=False,
                                  case_callable_obj=ConcurrentClientBase().scene_concurrent_locust_ddl,
                                  default_case_params=default_case_params)
```

2. client StatusCode.UNAVAILABLE
```
[2023-04-07 20:34:53,496 -  INFO - fouram]: [Base] Start clear collections (base.py:121)
[2023-04-07 20:34:53,509 -  INFO - fouram]: [Base] Release collections done (base.py:123)
[2023-04-07 20:34:53,521 -  INFO - fouram]: [Base] Start clean all collections ['fouram_8CLbQXRs'] (base.py:107)
[2023-04-07 20:34:53,790 - WARNING - fouram]: [drop_collection] retry:4, cost: 0.27s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses> (decorators.py:71)
[2023-04-07 20:34:54,061 - WARNING - fouram]: [drop_collection] retry:5, cost: 0.81s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses> (decorators.py:71)
[2023-04-07 20:34:54,873 - WARNING - fouram]: [drop_collection] retry:6, cost: 2.43s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses> (decorators.py:71)
[2023-04-07 20:34:57,307 - WARNING - fouram]: [drop_collection] retry:7, cost: 7.29s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses> (decorators.py:71)
[2023-04-07 20:35:04,607 - WARNING - fouram]: [drop_collection] retry:8, cost: 21.87s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses> (decorators.py:71)
[2023-04-07 20:35:26,502 - WARNING - fouram]: [drop_collection] retry:9, cost: 60.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses> (decorators.py:71)
[2023-04-07 20:36:26,564 -  INFO - fouram]: [Base] Clear collections Done! (base.py:125)
```
3. server proxy panic
```
35759 [2023/04/07 12:34:53.298 +00:00] [DEBUG] [proxy/task_scheduler.go:261] ["Proxy dmTaskQueue popPChanStats"] [taskID=440630219214159888]
35760 [2023/04/07 12:34:53.539 +00:00] [INFO] [proxy/impl.go:539] ["ReleaseCollection received"] [traceID=78173821a4f4e312] [role=proxy] [db=] [collection=fouram_8CLbQXRs]
35761 [2023/04/07 12:34:53.539 +00:00] [INFO] [proxy/impl.go:563] ["ReleaseCollection enqueued"] [traceID=78173821a4f4e312] [role=proxy] [MsgID=440630219515625473] [BeginTS=440630219515625473] [      EndTS=440630219515625473] [db=] [collection=fouram_8CLbQXRs]
35762 [2023/04/07 12:34:53.540 +00:00] [INFO] [proxy/meta_cache.go:767] ["clearing shard cache for collection"] [collectionName=fouram_8CLbQXRs]
35763 [2023/04/07 12:34:53.540 +00:00] [INFO] [proxy/impl.go:593] ["ReleaseCollection done"] [traceID=78173821a4f4e312] [role=proxy] [MsgID=440630219515625473] [BeginTS=440630219515625473] [EndT      S=440630219515625473] [db=] [collection=fouram_8CLbQXRs]
35764 [2023/04/07 12:34:53.550 +00:00] [INFO] [proxy/impl.go:925] ["ShowCollections received"] [role=proxy] [DbName=] [TimeStamp=0] [ShowType=All] [CollectionNames="[]"]
35765 [2023/04/07 12:34:53.551 +00:00] [INFO] [proxy/impl.go:953] ["ShowCollections enqueued"] [role=proxy] [MsgID=440630219515625474] [DbName=] [TimeStamp=0] [ShowType=All] [CollectionNames="[]      "]
35766 [2023/04/07 12:34:53.551 +00:00] [INFO] [proxy/impl.go:984] ["ShowCollections Done"] [role=proxy] [MsgID=440630219515625474] [DbName=] [TimeStamp=0] [ShowType=All] [len(CollectionNames)=0]       [num_collections=1]
35767 [2023/04/07 12:34:53.562 +00:00] [INFO] [proxy/impl.go:278] ["DropCollection received"] [traceID=7da448ac5bdb5ba3] [role=proxy] [db=] [collection=fouram_8CLbQXRs]
35768 [2023/04/07 12:34:53.563 +00:00] [INFO] [proxy/impl.go:299] ["DropCollection enqueued"] [traceID=7da448ac5bdb5ba3] [role=proxy] [MsgID=440630219515625476] [BeginTs=440630219515625476] [End      Ts=440630219515625476] [db=] [collection=fouram_8CLbQXRs]
35769 [2023/04/07 12:34:53.564 +00:00] [INFO] [proxy/impl.go:109] ["received request to invalidate collection meta cache"] [traceID=7da448ac5bdb5ba3] [module=Proxy] [role=proxy] [db=] [collectio      nName=] [collectionID=440627696106023321]
35770 [2023/04/07 12:34:53.564 +00:00] [INFO] [msgstream/mq_msgstream.go:182] ["start to close mq msg stream"] ["producer num"=2] ["consumer num"=0]
35771 time="2023-04-07T12:34:53Z" level=info msg="[Closing producer]" producerID=15 producer_name=sync-bigsheeper-pulsar-0-554 topic="persistent://public/default/sync-bigsheeper-rootcoord-dml_14      "
35772 time="2023-04-07T12:34:53Z" level=info msg="[Closed producer]" producerID=15 producer_name=sync-bigsheeper-pulsar-0-554 topic="persistent://public/default/sync-bigsheeper-rootcoord-dml_14"
35773 time="2023-04-07T12:34:53Z" level=info msg="[Closing producer]" producerID=16 producer_name=sync-bigsheeper-pulsar-0-555 topic="persistent://public/default/sync-bigsheeper-rootcoord-dml_15      "
35774 [2023/04/07 12:34:53.658 +00:00] [WARN] [proxy/task_scheduler.go:497] ["Failed to execute task: "] [error="producer already been closed: ProducerClosed"] [traceID=728481a4213269d5]
35775 [2023/04/07 12:34:53.658 +00:00] [DEBUG] [proxy/task_scheduler.go:261] ["Proxy dmTaskQueue popPChanStats"] [taskID=440630219227267077]
35776 [2023/04/07 12:34:53.658 +00:00] [WARN] [proxy/task_scheduler.go:497] ["Failed to execute task: "] [error="producer already been closed: ProducerClosed"] [traceID=b40976ad9ddc019]
35777 [2023/04/07 12:34:53.658 +00:00] [WARN] [proxy/task_scheduler.go:497] ["Failed to execute task: "] [error="producer already been closed: ProducerClosed"] [traceID=2f0f06dd09e9a323]
35778 [2023/04/07 12:34:53.658 +00:00] [WARN] [proxy/task_scheduler.go:497] ["Failed to execute task: "] [error="producer already been closed: ProducerClosed"] [traceID=2ef47afb0502184b]
35779 time="2023-04-07T12:34:53Z" level=info msg="[Closed producer]" producerID=16 producer_name=sync-bigsheeper-pulsar-0-555 topic="persistent://public/default/sync-bigsheeper-rootcoord-dml_15"
35780 [2023/04/07 12:34:53.658 +00:00] [INFO] [proxy/channels_mgr.go:291] ["dml stream removed"] [collection_id=440627696106023321]
35781 [2023/04/07 12:34:53.658 +00:00] [INFO] [proxy/impl.go:136] ["complete to invalidate collection meta cache"] [traceID=7da448ac5bdb5ba3] [module=Proxy] [role=proxy] [db=] [collection=] [col      lectionID=440627696106023321]
35782 [2023/04/07 12:34:53.662 +00:00] [WARN] [retry/retry.go:44] ["retry func failed"] ["retry time"=0] [error="code: CollectionNotExists, reason: can't find collection: 440627696106023321"]
35783 [2023/04/07 12:34:53.662 +00:00] [DEBUG] [proxy/task_scheduler.go:261] ["Proxy dmTaskQueue popPChanStats"] [taskID=440630219227267074]
35784 panic: dyh popPChanStats failed, err=code: UnexpectedError, reason: code: CollectionNotExists, reason: can't find collection: 440627696106023321
35785 
35786 goroutine 274183 [running]:
35787 github.com/milvus-io/milvus/internal/proxy.(*dmTaskQueue).PopActiveTask(0xc000f602d0, 0xc001ff6200?)
35788     /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:273 +0x473
35789 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask.func1()
35790     /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:477 +0x13a
35791 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask(0xc0013389c0?, {0x427edf8, 0xc002106000}, {0x427c240, 0xc000f602d0})
35792     /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:499 +0xaac
35793 created by github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).manipulationLoop
35794     /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:538 +0x1c5
```

### Steps To Reproduce

```markdown
contact me, my personal `fouram` repo and `partition` branch
```

### Milvus Log

`devops` cluster, `chaos-testing` namespace
```
sync-bigsheeper-etcd-0                                            1/1     Running       0                3h7m
sync-bigsheeper-etcd-1                                            1/1     Running       0                3h7m
sync-bigsheeper-etcd-2                                            1/1     Running       0                3h7m
sync-bigsheeper-milvus-datacoord-5b9cfcc84b-22wqp                 1/1     Running       0                3h
sync-bigsheeper-milvus-datanode-84bbcd686-ltnmd                   1/1     Running       0                3h
sync-bigsheeper-milvus-indexcoord-7c85c4fd96-pqjg5                1/1     Running       0                3h
sync-bigsheeper-milvus-indexnode-97df4ddfd-8sb88                  1/1     Running       0                3h
sync-bigsheeper-milvus-proxy-6c9f6c7f77-lb4x5                     1/1     Running       1 (2m25s ago)    3h
sync-bigsheeper-milvus-querycoord-5f8b46d568-974h6                1/1     Running       0                3h
sync-bigsheeper-milvus-querynode-697d85bfcf-kbrhp                 1/1     Running       0                3h
sync-bigsheeper-milvus-rootcoord-74f7fc4694-cjfs6                 1/1     Running       1 (162m ago)     3h
sync-bigsheeper-minio-0                                           1/1     Running       0                3h7m
sync-bigsheeper-minio-1                                           1/1     Running       0                3h7m
sync-bigsheeper-minio-2                                           1/1     Running       0                3h7m
sync-bigsheeper-minio-3                                           1/1     Running       0                3h7m
sync-bigsheeper-pulsar-bookie-0                                   1/1     Running       0                3h7m
sync-bigsheeper-pulsar-bookie-1                                   1/1     Running       0                3h7m
sync-bigsheeper-pulsar-bookie-2                                   1/1     Running       0                3h7m
sync-bigsheeper-pulsar-bookie-init-mgbfm                          0/1     Completed     0                3h7m
sync-bigsheeper-pulsar-broker-0                                   1/1     Running       0                3h7m
sync-bigsheeper-pulsar-proxy-0                                    1/1     Running       0                3h7m
sync-bigsheeper-pulsar-pulsar-init-qzpp4                          0/1     Completed     0                3h7m
sync-bigsheeper-pulsar-recovery-0                                 1/1     Running       0                3h7m
sync-bigsheeper-pulsar-zookeeper-0                                1/1     Running       0                3h7m
sync-bigsheeper-pulsar-zookeeper-1                                1/1     Running       0                3h5m
sync-bigsheeper-pulsar-zookeeper-2                                1/1     Running       0                3h5m
```

**Comment by bigsheeper** [comment]
Should be resolved. Please help to retry with this image:
harbor.milvus.io/milvus/milvus:bigsheeper-2304-memory-sync-53814d8-20230410
https://jenkins.milvus.io:18080/blue/organizations/jenkins/milvus-images%2Fbuild-dev-image/detail/build-dev-image/519/pipeline/

**Comment by ThreadDao** [comment]
> @ThreadDao Should be resolved. Please help to retry with this image:
> 
> `harbor.milvus.io/milvus/milvus:bigsheeper-2304-memory-sync-53814d8-20230410`
> 
> https://jenkins.milvus.io:18080/blue/organizations/jenkins/milvus-images%2Fbuild-dev-image/detail/build-dev-image/519/pipeline/

oh~ not fixed yet
```
[2023/04/10 04:14:49.088 +00:00] [DEBUG] [proxy/task_insert.go:440] ["send insert request to virtual channels"] [traceID=2d06c7ea701f2e28] [collection=fouram_LHClSAJ6] [partition=p_NbTECSxJ] [collection_id=440690240703693050] [partition_id=440690240703896210] [virtual_channels="[fouramf-6s79w-op-73-7527-rootcoord-dml_0_440690240703693050v0,fouramf-6s79w-op-73-7527-rootcoord-dml_1_440690240703693050v1]"] [task_id=440690301743136770] ["get cache duration"=5.2µs] ["get msgStream duration"=711ns]
[2023/04/10 04:14:49.088 +00:00] [DEBUG] [proxy/segment.go:227] ["Proxy segIDAssigner pickCanDoFunc"] [records="{\"440690240703693050\":{\"440690240703896210\":{\"fouramf-6s79w-op-73-7527-rootcoord-dml_1_440690240703693050v1\":5}}}"] [len(newTodoReqs)=1] [len(CanDoReqs)=0]
[2023/04/10 04:14:49.088 +00:00] [DEBUG] [proxy/segment.go:267] ["Proxy segIDAssigner reduceSegReqs"] [len(segReqs)=1]
[2023/04/10 04:14:49.088 +00:00] [DEBUG] [proxy/segment.go:297] ["Proxy segIDAssigner reduceSegReqs after reduce"] [len(segReqs)=1] [BeforeCnt=5] [AfterCnt=5]
[2023/04/10 04:14:49.098 +00:00] [DEBUG] [proxy/segment.go:227] ["Proxy segIDAssigner pickCanDoFunc"] [records="{\"440690240703693050\":{\"440690240703896210\":{\"fouramf-6s79w-op-73-7527-rootcoord-dml_1_440690240703693050v1\":5}}}"] [len(newTodoReqs)=0] [len(CanDoReqs)=1]
[2023/04/10 04:14:49.098 +00:00] [DEBUG] [proxy/task_insert.go:459] ["assign segmentID for insert data success"] [msgID=440690301743136770] [collectionID=440690240703693050] ["collection name"=fouram_LHClSAJ6] ["assign segmentID duration"=10.86139ms]
[2023/04/10 04:14:49.594 +00:00] [WARN] [proxy/impl.go:2631] ["Failed to execute insert task in task scheduler: proxy TaskCondition context Done"] [traceID=414788767cda3cf5]
[2023/04/10 04:14:49.594 +00:00] [DEBUG] [proxy/impl.go:2634] ["Finish processing insert request in Proxy"] [traceID=414788767cda3cf5]
panic: dyh 5555

goroutine 11987 [running]:
github.com/milvus-io/milvus/internal/proxy.(*Proxy).Insert.func1()
    /go/src/github.com/milvus-io/milvus/internal/proxy/impl.go:2528 +0x47 
github.com/milvus-io/milvus/internal/proxy.(*Proxy).Insert(0xc000981760, {0x4274558, 0xc002a590b0}, 0xc008216900)
    /go/src/github.com/milvus-io/milvus/internal/proxy/impl.go:2634 +0x1e2c
github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).Insert(0xc00752f2b8?, {0x4274558?, 0xc002a59080?}, 0x1?) 
    /go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:672 +0x2f 
github.com/milvus-io/milvus-proto/go-api/milvuspb._MilvusService_Insert_Handler.func1({0x4274558, 0xc002a59080}, {0x3d22360?, 0xc008216900})
    /go/pkg/mod/github.com/milvus-io/milvus-proto/go-api@v0.0.0-20230324025554-5bbe6698c2b0/milvuspb/milvus.pb.go:10524 +0x7b 
github.com/milvus-io/milvus/internal/proxy.RateLimitInterceptor.func1({0x4274558, 0xc002a59080}, {0x3d22360, 0xc008216900}, 0xc005175820, 0xc0024a29d8)
    /go/src/github.com/milvus-io/milvus/internal/proxy/rate_limit_interceptor.go:47 +0xba 
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x4274558?, 0xc002a59080?}, {0x3d22360?, 0xc008216900?})
    /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a 
github.com/milvus-io/milvus/internal/util/logutil.UnaryTraceLoggerInterceptor({0x4274558?, 0xc002a58fc0?}, {0x3d22360, 0xc008216900}, 0x0?, 0xc005175840)
    /go/src/github.com/milvus-io/milvus/internal/util/logutil/grpc_interceptor.go:22 +0x49 
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x4274558?, 0xc002a58fc0?}, {0x3d22360?, 0xc008216900?})
    /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a 
github.com/milvus-io/milvus/internal/proxy.UnaryServerInterceptor.func1({0x4274558?, 0xc002a58fc0?}, {0x3d22360, 0xc008216900}, 0x0?, 0xc005175860)
    /go/src/github.com/milvus-io/milvus/internal/proxy/privilege_interceptor.go:60 +0x5d 
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x4274558?, 0xc002a58fc0?}, {0x3d22360?, 0xc008216900?})
    /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a 
github.com/milvus-io/milvus/internal/proxy.UnaryServerHookInterceptor.func1({0x4274558, 0xc002a58fc0}, {0x3d22360, 0xc008216900}, 0xc003708b01?, 0xc0051758c0)
    /go/src/github.com/milvus-io/milvus/internal/proxy/hook_interceptor.go:97 +0x942
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x4274558?, 0xc002a58fc0?}, {0x3d22360?, 0xc008216900?})
    /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a 
github.com/grpc-ecosystem/go-grpc-middleware/auth.UnaryServerInterceptor.func1({0x4274558, 0xc002a58fc0}, {0x3d22360, 0xc008216900}, 0xc005175820, 0xc0051758e0)
    /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/auth/auth.go:47 +0xba 
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x4274558?, 0xc002a58fc0?}, {0x3d22360?, 0xc008216900?})
    /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a 
github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1({0x4274558, 0xc002a58f00}, {0x3d22360, 0xc008216900}, 0xc005175820?, 0xc005175900)
    /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38 +0x16a
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x4274558?, 0xc002a58f00?}, {0x3d22360?, 0xc008216900?})
    /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a 
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1({0x4274558, 0xc002a58f00}, {0x3d22360, 0xc008216900}, 0xc0012d2af0?, 0x3ab2660?)
    /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34 +0xbf 
github.com/milvus-io/milvus-proto/go-api/milvuspb._MilvusService_Insert_Handler({0x3dedf80?, 0xc0007a8000}, {0x4274558, 0xc002a58f00}, 0xc003b6e3c0, 0xc001cadc20)
    /go/pkg/mod/github.com/milvus-io/milvus-proto/go-api@v0.0.0-20230324025554-5bbe6698c2b0/milvuspb/milvus.pb.go:10526 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000860a80, {0x4284d90, 0xc0018c9380}, 0xc003708900, 0xc001cade00, 0x5768d90, 0x0)
    /go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1283 +0xcfd
google.golang.org/grpc.(*Server).handleStream(0xc000860a80, {0x4284d90, 0xc0018c9380}, 0xc003708900, 0x0)
    /go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1620 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
    /go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:922 +0x98 
created by google.golang.org/grpc.(*Server).serveStreams.func1
    /go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:920 +0x28a
```

**Comment by xiaofan-luan** [comment]
we need to think about this.
why the task queue need to rely on some meta?

**Comment by bigsheeper** [comment]
> we need to think about this.
> why the task queue need to rely on some meta?

This test is based on a test branch and hasn’t picked up the channel cache fix. With channel cache, task dequeueing doesn’t rely on meta or RPC again. However, task enqueueing still relies on it because it needs to get channels info from RootCoord. I think initializing channels info in imp.go before calling enqueue is a better choice. @xiaofan-luan

**Comment by xiaofan-luan** [comment]
> > we need to think about this.
> > why the task queue need to rely on some meta?
> 
> This test is based on a test branch and hasn’t picked up the channel cache fix. With channel cache, task dequeueing doesn’t rely on meta or RPC again. However, task enqueueing still relies on it because it needs to get channels info from RootCoord. Maybe initializing channels info in impl.go before calling enqueue is a better choice? @xiaofan-luan

yep, totally agreed

**Comment by yanliang567** [comment]
@bigsheeper any updates

**Comment by ThreadDao** [comment]
fixed
