### ISSUE TITLE
[Bug]: [Nightly]Plenty of cases failed for `find no available querycoord` when creating index

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#23314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:7e0f3e9
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.4.dev3
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Plenty of cases failed for `find no available querycoord` when creating index.
error message:
```
[2023-04-09T21:58:17.386Z] [2023-04-09 21:57:32 - ERROR - pymilvus.decorators]: RPC error: [create_index], <MilvusException: (code=1, message=err: find no available querycoord, check querycoord state
[2023-04-09T21:58:17.386Z] , /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
[2023-04-09T21:58:17.386Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:329 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall
[2023-04-09T21:58:17.386Z] /go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/client/client.go:168 github.com/milvus-io/milvus/internal/distributed/querycoord/client.(*Client).ShowCollections
[2023-04-09T21:58:17.386Z] /go/src/github.com/milvus-io/milvus/internal/proxy/util.go:863 github.com/milvus-io/milvus/internal/proxy.isCollectionLoaded
[2023-04-09T21:58:17.386Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_index.go:305 github.com/milvus-io/milvus/internal/proxy.(*createIndexTask).PreExecute
[2023-04-09T21:58:17.386Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:469 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask
[2023-04-09T21:58:17.386Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:511 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop
[2023-04-09T21:58:17.386Z] /usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit
[2023-04-09T21:58:17.386Z] )>, <Time:{'RPC start': '2023-04-09 21:57:32.325240', 'RPC error': '2023-04-09 21:57:32.330031'}> (decorators.py:108)
[2023-04-09T21:58:17.386Z] [2023-04-09 21:57:32 - ERROR - ci_test]: Traceback (most recent call last):
[2023-04-09T21:58:17.386Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2023-04-09T21:58:17.386Z]     res = func(*args, **_kwargs)
[2023-04-09T21:58:17.386Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2023-04-09T21:58:17.386Z]     return func(*arg, **kwargs)
[2023-04-09T21:58:17.386Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 953, in create_index
[2023-04-09T21:58:17.386Z]     return conn.create_index(self._name, field_name, index_params, timeout=timeout, **kwargs)
[2023-04-09T21:58:17.387Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2023-04-09T21:58:17.387Z]     raise e
[2023-04-09T21:58:17.387Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2023-04-09T21:58:17.387Z]     return func(*args, **kwargs)
[2023-04-09T21:58:17.387Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2023-04-09T21:58:17.387Z]     ret = func(self, *args, **kwargs)
[2023-04-09T21:58:17.387Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
[2023-04-09T21:58:17.387Z]     raise e
[2023-04-09T21:58:17.387Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2023-04-09T21:58:17.387Z]     return func(self, *args, **kwargs)
[2023-04-09T21:58:17.387Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 568, in create_index
[2023-04-09T21:58:17.387Z]     raise MilvusException(status.error_code, status.reason)
[2023-04-09T21:58:17.387Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=err: find no available querycoord, check querycoord state
[2023-04-09T21:58:17.387Z] , /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
[2023-04-09T21:58:17.387Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:329 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall
[2023-04-09T21:58:17.387Z] /go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/client/client.go:168 github.com/milvus-io/milvus/internal/distributed/querycoord/client.(*Client).ShowCollections
[2023-04-09T21:58:17.387Z] /go/src/github.com/milvus-io/milvus/internal/proxy/util.go:863 github.com/milvus-io/milvus/internal/proxy.isCollectionLoaded
[2023-04-09T21:58:17.387Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_index.go:305 github.com/milvus-io/milvus/internal/proxy.(*createIndexTask).PreExecute
[2023-04-09T21:58:17.387Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:469 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask
[2023-04-09T21:58:17.387Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:511 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop
[2023-04-09T21:58:17.387Z] /usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit
[2023-04-09T21:58:17.387Z] )>
[2023-04-09T21:58:17.387Z]  (api_request.py:39)
[2023-04-09T21:58:17.387Z] [2023-04-09 21:57:32 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=err: find no available querycoord, check querycoord state
[2023-04-09T21:58:17.387Z] , /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
[2023-04-09T21:58:17.387Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:3...... (api_request.py:40)
```

### Expected Behavior

pass

### Milvus Log

1. nightly link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/155/pipeline/144/
2. milvus log: [artifacts-milvus-distributed-kafka-nightly-155-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/155/artifact/artifacts-milvus-distributed-kafka-nightly-155-pymilvus-e2e-logs.tar.gz)
3. This persistent failure started at about '[2023-04-09T21:49:53.199Z] [gw1] [ 71%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_with_output_fields[3000-2-32-False-True]'

**Comment by smellthemoon** [comment]
<img width="968" alt="1" src="https://user-images.githubusercontent.com/64083300/231413899-3e152c4c-5415-4505-bccf-e5701541dc08.png">
related with #23313, pr has merged. plz check it @NicoYuan1986

**Comment by NicoYuan1986** [comment]
Fixed.

**Comment by 123qwe1234512** [comment]
Could you share it with us? :)

**Comment by smellthemoon** [comment]
> Could you share it with us? :)
hello, could you share more details, what help do you need?
