### ISSUE TITLE
[Bug]: [perf]Milvus on load search release scenario, search is reporting errors

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#23345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230411-12ed2420
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.0.dev45
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

server：
```
fouramf-xbcf5-20-4009-etcd-0                                      1/1     Running     0               64m     10.104.6.79     4am-node13   <none>           <none>
fouramf-xbcf5-20-4009-milvus-standalone-866896b654-tc6f8          1/1     Running     0               64m     10.104.5.20     4am-node12   <none>           <none>
fouramf-xbcf5-20-4009-minio-66bff599b6-sfxm4                      1/1     Running     0               64m     10.104.9.187    4am-node14   <none>           <none>
```

client log：

```
[2023-04-11 05:02:02,622 - DEBUG - fouram]: (api_response) : None  (api_request.py:36)
[2023-04-11 05:02:02,622 - DEBUG - fouram]: [Time] Collection.load run in 23.1208s (api_request.py:43)
[2023-04-11 05:02:02,622 - DEBUG - fouram]: (api_request)  : [Collection.search] args: [[[0.06081683708514396, 0.5641075815459666, 0.8586190928026466, 0.48352007779148487, 0.7688498618299365, 0.9797434644051063, 0.839572729998055, 0.9339194475926144, 0.7922915764838282, 0.5206664335693774, 0.44027935623541425, 0.09908368842524806, 0.9723322490418603, 0.8721626488656454, 0.7258564700365308, 0.7510849096047943, 0.09028539230806143, 0.5005895415894559, 0.149542990370219, 0.038499163693417215, 0.2233547475897103, 0.38029888243466303, 0.04653934784965208, 0.9728567102186682, 0.32321632374715625, 0.855840827332292, 0.8825080074427119, 0.5934103532714314, 0.8652197782688675, 0.2337532947423634, 0.590743967664173, 0.5563733580705496, 0.7111877974425159, 0.8046191748344218, 0.2927193457166334, 0.2709059302504383, 0.6496250016719478, 0.7063495888013083, 0.02686436914657464, 0.7455405154897935, 0.268116858499135, 0.4369532171740639, 0.3476994836190458, 0.5534606220157215, 0.48341368609692714, 0.23203296201246637, 0.42031427021442913, 0.005455575655570755, 0.059269139263781745, 0.08874065550283117, 0.2019467235101694, 0.24743304365486973, 0.8243993778063965, 0.3641669754919684, 0.48539961696123735, 0.3041009220806261, 0.6631877474638946, 0.8790864373987965, 0.725646420893156, 0.37214241657974056, 0.8948207599836586, 0.8116386562802154, 0.4109543621926154, 0.6699712675983197, 0.9687682001461828, 0.7458265921570884, 0.06201932289594492, 0.4843221840426044, 0.6249970145447767, 0.8232123514933777, 0.29434525804515244, 0.8105130587997791, 0.7283160097327018, 0.6475202794395077, 0.40765844939680873, 0.2599656159748671, 0.7182967994019601, 0.9720889876098351, 0.925275986177241, 0.03825420614452424, 0.2114730859310716, 0.9492337074952127, 0.40107371240466827, 0.14393229939161123, 0.6836852005966265, 0.8889722442280944, 0.43609465389805346, 0.4535993503109135, 0.824129355283864, 0.8610203261759644, 0.37286034243485444, 0.05477476390494185, 0.22758197662381696, 0.7714212359609848, 0.10695580209634947, 0.20710373253423175, 0.9561675863935716, 0.7884485648622056, 0.7049576645724273, 0.40397819610879426, 0.8329428398218168, 0.9327181831398415, 0.9281426083866162, 0.3373029324082787, 0.02605390881395131, 0.14554210116491584, 0.9670239848201804, 0.20433881740624338, 0.9229207642403887, 0.32953755139141705, 0.17582659853504168, 0.7328873983031307, 0.49678918157305263, 0.1815096860018074, 0.35738016644675474, 0.5424237879991641, 0.3112923778323651, 0.0033190035520891392, 0.5550379236135731, 0.5242026956881258, 0.10745102099529469, 0.49295574810438714, 0.4774686641611404, 0.4474862886434201, 0.42446457304844865, 0.28960622911658696, 0.3158723274196734, 0.7477937086090434]], 'float_vector', {'metric_type': 'L2', 'params': {'ef': [16]}}, 1, None, None, None, 60, -1], kwargs: {} (api_request.py:66)
[2023-04-11 05:02:02,625 - ERROR - fouram]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:
attempt #1:code: UnexpectedError, error: fail to Search, QueryNode ID=4, reason=Search 4 failed, reason [UnexpectedError] [json.exception.type_error.302] type must be number, but is array err %!w(<nil>)
attempt #2:context canceled
)>, <Time:{'RPC start': '2023-04-11 05:02:02.622595', 'RPC error': '2023-04-11 05:02:02.625389'}> (decorators.py:108)
[2023-04-11 05:02:02,625 - ERROR - fouram]: Traceback (most recent call last):
  File "/src/fouram/client/util/api_request.py", line 33, in inner_wrapper
    res = func(*args, **kwargs)
  File "/src/fouram/client/util/api_request.py", line 70, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 660, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 518, in search
    return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 487, in _execute_search_requests
    raise pre_err
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 478, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:
attempt #1:code: UnexpectedError, error: fail to Search, QueryNode ID=4, reason=Search 4 failed, reason [UnexpectedError] [json.exception.type_error.302] type must be number, but is array err %!w(<nil>)
attempt #2:context canceled
)>
 (api_request.py:48)
[2023-04-11 05:02:02,625 - ERROR - fouram]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:
attempt #1:code: UnexpectedError, error: fail to Search, QueryNode ID=4, reason=Search 4 failed, reason [UnexpectedError] [json.exception.type_error.302] type must be number, but is array err %!w(<nil>)
attempt #2:context canceled
)> (api_request.py:49)
[2023-04-11 05:02:02,626 - ERROR - fouram]: [CheckFunc] search request check failed, response:<MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:
attempt #1:code: UnexpectedError, error: fail to Search, QueryNode ID=4, reason=Search 4 failed, reason [UnexpectedError] [json.exception.type_error.302] type must be number, but is array err %!w(<nil>)
attempt #2:context canceled
)> (func_check.py:46)
[2023-04-11 05:02:02,626 - DEBUG - fouram]: (api_request)  : [Collection.release] args: [], kwargs: {'timeout': 60} (api_request.py:66)
```

### Steps To Reproduce

```markdown
1. create a collection 
        2. build index on vector column
        3. insert 1m 128d of vectors
        4. flush collection
        5. build index on vector column with the same parameters
        6. count the total number of rows
        7. load collection
        8. perform concurrent operations——> load- search raise error-> release
        9. clean all collections or not
```

### Anything else?

```
'client': {'test_case_type': 'ConcurrentClientBase',
            'test_case_name': 'test_concurrent_locust_custom_parameters',
            'test_case_params': {'dataset_params': {'dim': 128,
                                                    'dataset_name': 'sift',
                                                    'dataset_size': '1m',
                                                    'ni_per': 50000,
                                                    'metric_type': 'L2'},
                                 'collection_params': {'other_fields': []},
                                 'load_params': {},
                                 'query_params': {},
                                 'search_params': {},
                                 'index_params': {'index_type': 'HNSW',
                                                  'index_param': {'M': 8,
                                                                  'efConstruction': 200}},
                                 'concurrent_params': {'concurrent_number': 1,
                                                       'during_time': 3600,
                                                       'interval': 20,
                                                       'spawn_rate': None},
                                 'concurrent_tasks': [{'type': 'load_search_release',
                                                       'weight': 1,
                                                       'params': {'top_k': 1,
                                                                  'nq': 1,
                                                                  'search_param': {'ef': [16]},
                                                                  'replica_number': 1,
                                                                  'random_data': True}}]}
```

**Comment by xiaofan-luan** [comment]
[json.exception.type_error.302] type must be number, but is array err

**Comment by jingkl** [comment]
Thanks for the help it has been verified that there is no problem
