### ISSUE TITLE
[Bug]: [Nightly]The error message is not clear when creating a collection with invalid shards number

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#23372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:f1c7861
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):  rocksmq  
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.5.dev2
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The error message is not clear when creating a collection with invalid shards number.
```
[2023-04-11T23:18:50.535Z] [2023-04-11 20:07:38 - ERROR - pymilvus.decorators]: Unexpected error: [create_collection], 'str' object cannot be interpreted as an integer, <Time: {'RPC start': '2023-04-11 20:07:38.341779', 'Exception': '2023-04-11 20:07:38.341878'}> (decorators.py:120)
[2023-04-11T23:18:50.535Z] [2023-04-11 20:07:38 - ERROR - ci_test]: Traceback (most recent call last):
[2023-04-11T23:18:50.535Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2023-04-11T23:18:50.535Z]     return func(*args, **kwargs)
[2023-04-11T23:18:50.535Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2023-04-11T23:18:50.535Z]     ret = func(self, *args, **kwargs)
[2023-04-11T23:18:50.535Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 87, in handler
[2023-04-11T23:18:50.535Z]     raise e
[2023-04-11T23:18:50.535Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2023-04-11T23:18:50.535Z]     return func(self, *args, **kwargs)
[2023-04-11T23:18:50.535Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 205, in create_collection
[2023-04-11T23:18:50.535Z]     request = Prepare.create_collection_request(collection_name, fields, shards_num=shards_num, **kwargs)
[2023-04-11T23:18:50.535Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/prepare.py", line 44, in create_collection_request
[2023-04-11T23:18:50.535Z]     req = milvus_types.CreateCollectionRequest(collection_name=collection_name,
[2023-04-11T23:18:50.535Z] TypeError: 'str' object cannot be interpreted as an integer
[2023-04-11T23:18:50.535Z] 
[2023-04-11T23:18:50.535Z] The above exception was the direct cause of the following exception:
[2023-04-11T23:18:50.535Z] 
[2023-04-11T23:18:50.535Z] Traceback (most recent call last):
[2023-04-11T23:18:50.536Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2023-04-11T23:18:50.536Z]     res = func(*args, **_kwargs)
[2023-04-11T23:18:50.536Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2023-04-11T23:18:50.536Z]     return func(*arg, **kwargs)
[2023-04-11T23:18:50.536Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 120, in __init__
[2023-04-11T23:18:50.536Z]     conn.create_collection(self._name, schema, shards_num=self._shards_num, **kwargs)
[2023-04-11T23:18:50.536Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 121, in handler
[2023-04-11T23:18:50.536Z]     raise MilvusException(message=f"Unexpected error, message=<{str(e)}>") from e
[2023-04-11T23:18:50.536Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Unexpected error, message=<'str' object cannot be interpreted as an integer>)>
[2023-04-11T23:18:50.536Z]  (api_request.py:39)
[2023-04-11T23:18:50.536Z] [2023-04-11 20:07:38 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Unexpected error, message=<'str' object cannot be interpreted as an integer>)> (api_request.py:40)
```

### Expected Behavior

It's not an unexpected  error.
error message should be clear. before: 
```
...expected one of: int, long
```

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/157/pipeline/124/
2. log: [artifacts-milvus-standalone-nightly-157-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/157/artifact/artifacts-milvus-standalone-nightly-157-pymilvus-e2e-logs.tar.gz)
3. collection name: collection_urIkzXOk
4. failed time: [2023-04-11T20:07:38.747Z] [gw2] [  5%] FAILED testcases/test_collection.py::TestCollectionParams::test_collection_shards_num_with_error_type

**Comment by yanliang567** [comment]
/assign @XuanYang-cn 
is it a mismatch of pymilvus update?

/unassign

**Comment by NicoYuan1986** [comment]
Fixed.
