### ISSUE TITLE
[Bug]: replica num = 0 makes it impossible to load successfully

### ISSUE THREAD

**Issue by Cheung7788** [milvus-io/milvus#23430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.5
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The cluster has been trying to load but failed

### Milvus Log

2023/04/11 11:20:12 maxprocs: Leaving GOMAXPROCS=16: CPU quota undefined

    __  _________ _   ____  ______    
   /  |/  /  _/ /| | / / / / / __/    
  / /|_/ // // /_| |/ / /_/ /\ \    
 /_/  /_/___/____/___/\____/___/     

Welcome to use Milvus!
Version:   v2.2.5
Built:     Wed Mar 29 11:32:15 UTC 2023
GitCommit: 47e28fbe
GoVersion: go version go1.18.3 linux/amd64

open pid file: /run/milvus/querycoord.pid
lock pid file: /run/milvus/querycoord.pid
[2023/04/11 11:20:12.398 +00:00] [INFO] [roles/roles.go:192] ["starting running Milvus components"]
[2023/04/11 11:20:12.398 +00:00] [INFO] [roles/roles.go:134] ["Enable Jemalloc"] ["Jemalloc Path"=/milvus/lib/libjemalloc.so]
[2023/04/11 11:20:12.398 +00:00] [INFO] [management/server.go:68] ["management listen"] [addr=:9091]
[2023/04/11 11:20:12.408 +00:00] [INFO] [config/etcd_source.go:145] ["start refreshing configurations"]
[2023/04/11 11:20:12.408 +00:00] [INFO] [paramtable/quota_param.go:532] ["init disk quota"] [diskQuota(MB)=+inf]
[2023/04/11 11:20:12.408 +00:00] [INFO] [paramtable/component_param.go:1402] ["init segment max idle time"] [value=10m0s]
[2023/04/11 11:20:12.408 +00:00] [INFO] [paramtable/component_param.go:1407] ["init segment min size from idle to sealed"] [value=16]
[2023/04/11 11:20:12.408 +00:00] [INFO] [paramtable/component_param.go:1412] ["init segment max binlog file to sealed"] [value=32]
[2023/04/11 11:20:12.409 +00:00] [INFO] [paramtable/base_table.go:142] ["cannot find etcd.endpoints"]
[2023/04/11 11:20:12.409 +00:00] [INFO] [paramtable/hook_config.go:19] ["hook config"] [hook={}]
[2023/04/11 11:20:12.416 +00:00] [INFO] [config/etcd_source.go:145] ["start refreshing configurations"]
[2023/04/11 11:20:12.417 +00:00] [DEBUG] [paramtable/grpc_param.go:153] [initServerMaxSendSize] [role=querycoord] [grpc.serverMaxSendSize=536870912]
[2023/04/11 11:20:12.417 +00:00] [DEBUG] [paramtable/grpc_param.go:175] [initServerMaxRecvSize] [role=querycoord] [grpc.serverMaxRecvSize=536870912]
[2023/04/11 11:20:12.417 +00:00] [INFO] [querycoord/service.go:251] [network] [port=19531]
[2023/04/11 11:20:12.517 +00:00] [INFO] [sessionutil/session_util.go:197] ["Session try to connect to etcd"]
[2023/04/11 11:20:12.519 +00:00] [INFO] [sessionutil/session_util.go:212] ["Session connect to etcd success"]
[2023/04/11 11:20:12.526 +00:00] [INFO] [config/etcd_source.go:145] ["start refreshing configurations"]
[2023/04/11 11:20:12.526 +00:00] [DEBUG] [paramtable/grpc_param.go:238] ["Init client max send size"] [role=rootcoord] [grpc.clientMaxSendSize=104857600]
[2023/04/11 11:20:12.526 +00:00] [DEBUG] [paramtable/grpc_param.go:238] ["Init client max recv size"] [role=rootcoord] [grpc.clientMaxRecvSize=104857600]
[2023/04/11 11:20:12.526 +00:00] [DEBUG] [paramtable/grpc_param.go:238] ["Init dial timeout"] [role=rootcoord] [grpc.client.dialTimeout=104857600]
[2023/04/11 11:20:12.526 +00:00] [DEBUG] [paramtable/grpc_param.go:238] ["Init keep alive timeout"] [role=rootcoord] [grpc.client.keepAliveTimeout=104857600]
[2023/04/11 11:20:12.526 +00:00] [DEBUG] [paramtable/grpc_param.go:238] ["Init keep alive time"] [role=rootcoord] [grpc.client.keepAliveTime=104857600]
[2023/04/11 11:20:12.526 +00:00] [DEBUG] [paramtable/grpc_param.go:238] ["Init max attempts"] [role=rootcoord] [grpc.client.maxMaxAttempts=104857600]
[2023/04/11 11:20:12.526 +00:00] [DEBUG] [paramtable/grpc_param.go:238] ["Init initial back off"] [role=rootcoord] [grpc.client.initialBackOff=104857600]
[2023/04/11 11:20:12.526 +00:00] [DEBUG] [paramtable/grpc_param.go:238] ["Init max back off"] [role=rootcoord] [grpc.client.maxBackoff=104857600]
[2023/04/11 11:20:12.526 +00:00] [DEBUG] [paramtable/grpc_param.go:238] ["Init back off multiplier"] [role=rootcoord] [grpc.client.backoffMultiplier=104857600]
[2023/04/11 11:20:12.526 +00:00] [INFO] [querycoord/service.go:163] ["QueryCoord try to wait for RootCoord ready"]
[2023/04/11 11:20:12.527 +00:00] [INFO] [sessionutil/session_util.go:453] ["SessionUtil GetSessions "] [prefix=rootcoord] [key=rootcoord] [address=10.23.129.30:53100]
[2023/04/11 11:20:12.527 +00:00] [INFO] [client/client.go:108] ["RootCoordClient GetSessions success"] [address=10.23.129.30:53100]
[2023/04/11 11:20:12.529 +00:00] [INFO] [querycoord/service.go:173] ["QueryCoord report RootCoord ready"]
[2023/04/11 11:20:12.529 +00:00] [INFO] [sessionutil/session_util.go:197] ["Session try to connect to etcd"]
[2023/04/11 11:20:12.530 +00:00] [INFO] [sessionutil/session_util.go:212] ["Session connect to etcd success"]
[2023/04/11 11:20:12.539 +00:00] [INFO] [config/etcd_source.go:145] ["start refreshing configurations"]
[2023/04/11 11:20:12.539 +00:00] [DEBUG] [paramtable/grpc_param.go:238] ["Init client max send size"] [role=datacoord] [grpc.clientMaxSendSize=104857600]
[2023/04/11 11:20:12.539 +00:00] [DEBUG] [paramtable/grpc_param.go:238] ["Init client max recv size"] [role=datacoord] [grpc.clientMaxRecvSize=104857600]
[2023/04/11 11:20:12.539 +00:00] [DEBUG] [paramtable/grpc_param.go:238] ["Init dial timeout"] [role=datacoord] [grpc.client.dialTimeout=104857600]
[2023/04/11 11:20:12.539 +00:00] [DEBUG] [paramtable/grpc_param.go:238] ["Init keep alive timeout"] [role=datacoord] [grpc.client.keepAliveTimeout=104857600]
[2023/04/11 11:20:12.539 +00:00] [DEBUG] [paramtable/grpc_param.go:238] ["Init keep alive time"] [role=datacoord] [grpc.client.keepAliveTime=104857600]
[2023/04/11 11:20:12.539 +00:00] [DEBUG] [paramtable/grpc_param.go:238] ["Init max attempts"] [role=datacoord] [grpc.client.maxMaxAttempts=104857600]
[2023/04/11 11:20:12.539 +00:00] [DEBUG] [paramtable/grpc_param.go:238] ["Init initial back off"] [role=datacoord] [grpc.client.initialBackOff=104857600]
[2023/04/11 11:20:12.539 +00:00] [DEBUG] [paramtable/grpc_param.go:238] ["Init max back off"] [role=datacoord] [grpc.client.maxBackoff=104857600]
[2023/04/11 11:20:12.539 +00:00] [DEBUG] [paramtable/grpc_param.go:238] ["Init back off multiplier"] [role=datacoord] [grpc.client.backoffMultiplier=104857600]
[2023/04/11 11:20:12.539 +00:00] [INFO] [querycoord/service.go:192] ["QueryCoord try to wait for DataCoord ready"]
[2023/04/11 11:20:12.540 +00:00] [INFO] [sessionutil/session_util.go:453] ["SessionUtil GetSessions "] [prefix=datacoord] [key=datacoord] [address=10.23.128.198:13333]
[2023/04/11 11:20:12.542 +00:00] [INFO] [querycoord/service.go:201] ["QueryCoord report DataCoord ready"]
[2023/04/11 11:20:12.542 +00:00] [INFO] [sessionutil/session_util.go:197] ["Session try to connect to etcd"]
[2023/04/11 11:20:12.543 +00:00] [INFO] [sessionutil/session_util.go:212] ["Session connect to etcd success"]
[2023/04/11 11:20:12.550 +00:00] [INFO] [config/etcd_source.go:145] ["start refreshing configurations"]
[2023/04/11 11:20:12.550 +00:00] [DEBUG] [paramtable/grpc_param.go:238] ["Init client max send size"] [role=indexcoord] [grpc.clientMaxSendSize=104857600]
[2023/04/11 11:20:12.550 +00:00] [DEBUG] [paramtable/grpc_param.go:238] ["Init client max recv size"] [role=indexcoord] [grpc.clientMaxRecvSize=104857600]
[2023/04/11 11:20:12.550 +00:00] [DEBUG] [paramtable/grpc_param.go:238] ["Init dial timeout"] [role=indexcoord] [grpc.client.dialTimeout=104857600]
[2023/04/11 11:20:12.550 +00:00] [DEBUG] [paramtable/grpc_param.go:238] ["Init keep alive timeout"] [role=indexcoord] [grpc.client.keepAliveTimeout=104857600]
[2023/04/11 11:20:12.550 +00:00] [DEBUG] [paramtable/grpc_param.go:238] ["Init keep alive time"] [role=indexcoord] [grpc.client.keepAliveTime=104857600]
[2023/04/11 11:20:12.550 +00:00] [DEBUG] [paramtable/grpc_param.go:238] ["Init max attempts"] [role=indexcoord] [grpc.client.maxMaxAttempts=104857600]
[2023/04/11 11:20:12.550 +00:00] [DEBUG] [paramtable/grpc_param.go:238] ["Init initial back off"] [role=indexcoord] [grpc.client.initialBackOff=104857600]
[2023/04/11 11:20:12.550 +00:00] [DEBUG] [paramtable/grpc_param.go:238] ["Init max back off"] [role=indexcoord] [grpc.client.maxBackoff=104857600]
[2023/04/11 11:20:12.550 +00:00] [DEBUG] [paramtable/grpc_param.go:238] ["Init back off multiplier"] [role=indexcoord] [grpc.client.backoffMultiplier=104857600]
[2023/04/11 11:20:12.550 +00:00] [INFO] [querycoord/service.go:222] ["QueryCoord try to wait for IndexCoord ready"]
[2023/04/11 11:20:12.551 +00:00] [INFO] [sessionutil/session_util.go:453] ["SessionUtil GetSessions "] [prefix=indexcoord] [key=indexcoord] [address=10.23.128.236:31000]
[2023/04/11 11:20:12.551 +00:00] [INFO] [client/client.go:108] ["IndexCoordClient GetSessions success"] [key=indexcoord] [msess="{\"indexcoord\":{\"ServerID\":69,\"ServerName\":\"indexcoord\",\"Address\":\"10.23.128.236:31000\",\"Exclusive\":true,\"TriggerKill\":true,\"Version\":\"2.2.5-pre+dev\"}}"]
[2023/04/11 11:20:12.552 +00:00] [INFO] [querycoord/service.go:228] ["QueryCoord report IndexCoord is ready"]
[2023/04/11 11:20:12.552 +00:00] [INFO] [querycoordv2/server.go:167] ["QueryCoord start init"] [meta-root-path=by-dev/meta] [address=10.23.128.124:19531]
[2023/04/11 11:20:12.552 +00:00] [INFO] [sessionutil/session_util.go:197] ["Session try to connect to etcd"]
[2023/04/11 11:20:12.553 +00:00] [INFO] [sessionutil/session_util.go:212] ["Session connect to etcd success"]
[2023/04/11 11:20:12.560 +00:00] [INFO] [sessionutil/session_util.go:295] ["Session get serverID success"] [key=id] [ServerId=124]
[2023/04/11 11:20:12.567 +00:00] [INFO] [config/etcd_source.go:145] ["start refreshing configurations"]
[2023/04/11 11:20:12.567 +00:00] [INFO] [paramtable/quota_param.go:532] ["init disk quota"] [diskQuota(MB)=+inf]
[2023/04/11 11:20:12.567 +00:00] [INFO] [paramtable/component_param.go:1402] ["init segment max idle time"] [value=10m0s]
[2023/04/11 11:20:12.568 +00:00] [INFO] [paramtable/component_param.go:1407] ["init segment min size from idle to sealed"] [value=16]
[2023/04/11 11:20:12.568 +00:00] [INFO] [paramtable/component_param.go:1412] ["init segment max binlog file to sealed"] [value=32]
[2023/04/11 11:20:12.569 +00:00] [INFO] [paramtable/base_table.go:142] ["cannot find etcd.endpoints"]
[2023/04/11 11:20:12.569 +00:00] [INFO] [paramtable/hook_config.go:19] ["hook config"] [hook={}]
[2023/04/11 11:20:12.569 +00:00] [INFO] [logutil/logutil.go:165] ["Log directory"] [configDir=]
[2023/04/11 11:20:12.569 +00:00] [INFO] [logutil/logutil.go:166] ["Set log file to "] [path=]
[2023/04/11 11:20:12.569 +00:00] [INFO] [querycoordv2/server.go:200] [QueryCoord] [State=Initializing]
[2023/04/11 11:20:12.569 +00:00] [INFO] [querycoordv2/server.go:204] ["query coordinator try to connect etcd success"]
[2023/04/11 11:20:12.572 +00:00] [INFO] [tso/tso.go:121] ["sync and save timestamp"] [last=2023/04/11 11:15:00.582 +00:00] [save=2023/04/11 11:20:15.570 +00:00] [next=2023/04/11 11:20:12.570 +00:00]
[2023/04/11 11:20:12.572 +00:00] [INFO] [querycoordv2/server.go:285] ["init meta"]
[2023/04/11 11:20:12.572 +00:00] [INFO] [querycoordv2/server.go:289] ["recover meta..."]
[2023/04/11 11:20:12.577 +00:00] [INFO] [meta/replica_manager.go:130] ["recover replica"] [collectionID=440261796313992330] [replicaID=440261800319778817] [nodes="[115]"]
[2023/04/11 11:20:12.577 +00:00] [INFO] [meta/replica_manager.go:130] ["recover replica"] [collectionID=440261796314489607] [replicaID=440261800319778818] [nodes="[115]"]
[2023/04/11 11:20:12.578 +00:00] [INFO] [meta/resource_manager.go:672] ["Recover resource group"] [rgName=__default_resource_group] [nodes="[115]"] [capacity=1000000]
[2023/04/11 11:20:12.578 +00:00] [INFO] [querycoordv2/server.go:228] ["init session"]
[2023/04/11 11:20:12.578 +00:00] [INFO] [querycoordv2/server.go:232] ["init schedulers"]
[2023/04/11 11:20:12.578 +00:00] [INFO] [querycoordv2/server.go:245] ["init dist controller"]
[2023/04/11 11:20:12.578 +00:00] [INFO] [querycoordv2/server.go:255] ["init balancer"]
[2023/04/11 11:20:12.578 +00:00] [INFO] [querycoordv2/server.go:265] ["init checker controller"]
[2023/04/11 11:20:12.578 +00:00] [INFO] [querycoordv2/server.go:325] ["init observers"]
[2023/04/11 11:20:12.578 +00:00] [INFO] [querycoordv2/server.go:280] ["QueryCoord init success"]
[2023/04/11 11:20:12.578 +00:00] [INFO] [querycoord/service.go:101] ["QueryCoord init done ..."]
[2023/04/11 11:20:12.578 +00:00] [INFO] [sessionutil/session_util.go:345] ["service begin to register to etcd"] [serverName=querycoord] [ServerID=124]
[2023/04/11 11:20:12.583 +00:00] [INFO] [sessionutil/session_util.go:382] ["put session key into etcd"] [key=by-dev/meta/session/querycoord] [value="{\"ServerID\":124,\"ServerName\":\"querycoord\",\"Address\":\"10.23.128.124:19531\",\"Exclusive\":true,\"TriggerKill\":true,\"Version\":\"2.2.5-pre+dev\"}"]
[2023/04/11 11:20:12.583 +00:00] [INFO] [sessionutil/session_util.go:393] ["Service registered successfully"] [ServerName=querycoord] [serverID=124]
[2023/04/11 11:20:12.584 +00:00] [INFO] [querycoordv2/server.go:135] ["QueryCoord Register Finished"]
[2023/04/11 11:20:12.584 +00:00] [INFO] [querycoordv2/server.go:367] ["start watcher..."]
[2023/04/11 11:20:12.585 +00:00] [INFO] [sessionutil/session_util.go:453] ["SessionUtil GetSessions "] [prefix=querynode] [key=querynode-115] [address=10.23.128.95:21123]
[2023/04/11 11:20:12.585 +00:00] [INFO] [task/scheduler.go:223] ["add executor for new QueryNode"] [nodeID=115]
[2023/04/11 11:20:12.585 +00:00] [INFO] [meta/resource_manager.go:444] ["HandleNodeUp: node already assign to resource group"] [rgName=__default_resource_group] [node=115]
[2023/04/11 11:20:12.585 +00:00] [INFO] [querycoordv2/server.go:647] ["HandleNodeUp: assign node to resource group"] [nodeID=115] [resourceGroup=__default_resource_group]
[2023/04/11 11:20:12.585 +00:00] [INFO] [querycoordv2/server.go:383] ["start recovering dist and target"]
[2023/04/11 11:20:12.585 +00:00] [INFO] [dist/dist_handler.go:59] ["start dist handler"] [nodeID=115]
[2023/04/11 11:20:12.586 +00:00] [INFO] [meta/target_manager.go:124] ["start to update next targets for collection"] [collectionID=440261796314489607]
[2023/04/11 11:20:12.586 +00:00] [INFO] [meta/target_manager.go:142] ["start to pull next targets for partition"] [collectionID=440261796314489607] [partitionIDs="[440261796314489608,440261796314789806,440261796314831819]"]
[2023/04/11 11:20:12.595 +00:00] [INFO] [meta/target_manager.go:134] ["finish to update next targets for collection"] [collectionID=440261796314489607] [segments="[440261796314797296,440261796314794382,440261796314794383,440261796314797297]"] [channels="[by-dev-rootcoord-dml_6_440261796314489607v0,by-dev-rootcoord-dml_7_440261796314489607v1]"]
[2023/04/11 11:20:12.595 +00:00] [INFO] [meta/target_manager.go:124] ["start to update next targets for collection"] [collectionID=440261796313992330]
[2023/04/11 11:20:12.595 +00:00] [INFO] [meta/target_manager.go:142] ["start to pull next targets for partition"] [collectionID=440261796313992330] [partitionIDs="[440261796313992331,440261796313993599]"]
[2023/04/11 11:20:12.599 +00:00] [INFO] [meta/target_manager.go:134] ["finish to update next targets for collection"] [collectionID=440261796313992330] [segments="[440261796314471217,440261796313997295,440261796314471218,440261796313997296]"] [channels="[by-dev-rootcoord-dml_2_440261796313992330v0,by-dev-rootcoord-dml_3_440261796313992330v1]"]
[2023/04/11 11:20:12.607 +00:00] [INFO] [config/etcd_source.go:145] ["start refreshing configurations"]
[2023/04/11 11:20:12.608 +00:00] [INFO] [querycoordv2/server.go:395] ["start cluster..."]
[2023/04/11 11:20:12.608 +00:00] [INFO] [querycoordv2/server.go:398] ["start job scheduler..."]
[2023/04/11 11:20:12.608 +00:00] [INFO] [querycoordv2/server.go:401] ["start task scheduler..."]
[2023/04/11 11:20:12.608 +00:00] [INFO] [querycoordv2/server.go:404] ["start checker controller..."]
[2023/04/11 11:20:12.608 +00:00] [INFO] [querycoordv2/server.go:407] ["start observers..."]
[2023/04/11 11:20:12.608 +00:00] [INFO] [querycoordv2/server.go:361] ["QueryCoord started"]
[2023/04/11 11:20:12.608 +00:00] [INFO] [querycoord/service.go:106] ["QueryCoord start done ..."]
[2023/04/11 11:20:12.608 +00:00] [INFO] [observers/resource_observer.go:61] ["Start check resource group loop"]
[2023/04/11 11:20:12.608 +00:00] [INFO] [observers/target_observer.go:89] ["Start update next target loop"]
[2023/04/11 11:20:12.608 +00:00] [INFO] [observers/replica_observer.go:64] ["Start check replica loop"]
[2023/04/11 11:20:12.616 +00:00] [INFO] [sessionutil/session_util.go:734] ["register session success"] [role=querycoord] [key=by-dev/meta/session/querycoord]
[2023/04/11 11:20:13.609 +00:00] [INFO] [balance/utils.go:84] ["Create Channel task"] [collection=440261796314489607] [replica=440261800319778818] [channel=by-dev-rootcoord-dml_6_440261796314489607v0] [From=-1] [To=115]
[2023/04/11 11:20:13.609 +00:00] [INFO] [balance/utils.go:84] ["Create Channel task"] [collection=440261796314489607] [replica=440261800319778818] [channel=by-dev-rootcoord-dml_7_440261796314489607v1] [From=-1] [To=115]
[2023/04/11 11:20:13.609 +00:00] [INFO] [balance/utils.go:84] ["Create Channel task"] [collection=440261796313992330] [replica=440261800319778817] [channel=by-dev-rootcoord-dml_3_440261796313992330v1] [From=-1] [To=115]
[2023/04/11 11:20:13.609 +00:00] [INFO] [balance/utils.go:84] ["Create Channel task"] [collection=440261796313992330] [replica=440261800319778817] [channel=by-dev-rootcoord-dml_2_440261796313992330v0] [From=-1] [To=115]
[2023/04/11 11:20:13.609 +00:00] [INFO] [balance/rowcount_based_balancer.go:116] ["nodes info"] [collection=440261796313992330] [replica=440261800319778817] [nodes="[115]"]
[2023/04/11 11:20:13.609 +00:00] [INFO] [balance/rowcount_based_balancer.go:116] ["nodes info"] [collection=440261796314489607] [replica=440261800319778818] [nodes="[115]"]
[2023/04/11 11:20:13.609 +00:00] [INFO] [observers/collection_observer.go:115] ["observes partitions timeout"] [partitionNum=2]
[2023/04/11 11:20:13.609 +00:00] [INFO] [task/scheduler.go:262] ["task added"] [task="[id=1] [type=1] [collectionID=440261796314489607] [replicaID=440261800319778818] [priority=1] [actionsCount=1] [actions={[type=1][node=115]}] [channel=by-dev-rootcoord-dml_6_440261796314489607v0]"]
[2023/04/11 11:20:13.609 +00:00] [INFO] [observers/collection_observer.go:166] ["collection targets"] [collectionID=440261796313992330] [segmentTargetNum=4] [channelTargetNum=2] [totalTargetNum=6] [replicaNum=1]
[2023/04/11 11:20:13.609 +00:00] [INFO] [task/scheduler.go:262] ["task added"] [task="[id=2] [type=1] [collectionID=440261796314489607] [replicaID=440261800319778818] [priority=1] [actionsCount=1] [actions={[type=1][node=115]}] [channel=by-dev-rootcoord-dml_7_440261796314489607v1]"]
[2023/04/11 11:20:13.609 +00:00] [INFO] [task/scheduler.go:262] ["task added"] [task="[id=3] [type=1] [collectionID=440261796313992330] [replicaID=440261800319778817] [priority=1] [actionsCount=1] [actions={[type=1][node=115]}] [channel=by-dev-rootcoord-dml_3_440261796313992330v1]"]
[2023/04/11 11:20:13.609 +00:00] [INFO] [observers/collection_observer.go:166] ["collection targets"] [collectionID=440261796314489607] [segmentTargetNum=4] [channelTargetNum=2] [totalTargetNum=6] [replicaNum=1]
[2023/04/11 11:20:13.609 +00:00] [INFO] [task/scheduler.go:262] ["task added"] [task="[id=4] [type=1] [collectionID=440261796313992330] [replicaID=440261800319778817] [priority=1] [actionsCount=1] [actions={[type=1][node=115]}] [channel=by-dev-rootcoord-dml_2_440261796313992330v0]"]
[2023/04/11 11:20:13.609 +00:00] [INFO] [observers/collection_observer.go:150] ["observe partitions status"] [partitionNum=5]
[2023/04/11 11:20:13.609 +00:00] [INFO] [observers/collection_observer.go:233] ["partition targets"] [collectionID=440261796314489607] [partitionID=440261796314789806] [segmentTargetNum=4] [channelTargetNum=2] [totalTargetNum=6] [replicaNum=0]
panic: runtime error: integer divide by zero

goroutine 363 [running]:
github.com/milvus-io/milvus/internal/querycoordv2/observers.(*CollectionObserver).observePartitionLoadStatus(0xc0006a7770, 0xc00187b600)
	/go/src/github.com/milvus-io/milvus/internal/querycoordv2/observers/collection_observer.go:264 +0xf2a
github.com/milvus-io/milvus/internal/querycoordv2/observers.(*CollectionObserver).observeLoadStatus(0xc0006a7770)
	/go/src/github.com/milvus-io/milvus/internal/querycoordv2/observers/collection_observer.go:156 +0x191
github.com/milvus-io/milvus/internal/querycoordv2/observers.(*CollectionObserver).Observe(0xc00062b798?)
	/go/src/github.com/milvus-io/milvus/internal/querycoordv2/observers/collection_observer.go:93 +0x28
github.com/milvus-io/milvus/internal/querycoordv2/observers.(*CollectionObserver).Start.func1()
	/go/src/github.com/milvus-io/milvus/internal/querycoordv2/observers/collection_observer.go:79 +0x99
created by github.com/milvus-io/milvus/internal/querycoordv2/observers.(*CollectionObserver).Start
	/go/src/github.com/milvus-io/milvus/internal/querycoordv2/observers/collection_observer.go:65 +0x8a

### Anything else?

Restoring service in one step：
1. birdwatcher force release
2. load collection 

[bw_etcd_ALL.230411-191929.bak.gz](https://github.com/milvus-io/milvus/files/11229775/bw_etcd_ALL.230411-191929.bak.gz)
[querycode.txt](https://github.com/milvus-io/milvus/files/11229779/querycode.txt)

**Comment by congqixia** [comment]
Root cause was #23411 shall be fixed by #23412 
@yah01  please cherry pick this patch to 2.2.0 branch
@yanliang567  could we add some test case for this scenario?
/unassign
/assign @yah01 @yanliang567

**Comment by yanliang567** [comment]
@congqixia any tips for reproduce steps?

**Comment by congqixia** [comment]
migrate from 2.1.x to 2.2.0 then upgrade to 2.2.3 or later

**Comment by elonzh** [comment]
我真是忍不住了, 测试了几天到处都是 bug 😂, SDK 也是 patch 版本随便改依赖没测一下就发上去了。
