### ISSUE TITLE
[Bug]: Search the released partition did not report "not loaded" error when collection is ever loaded

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#23498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master latest
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):    all
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.2.7
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Search the released partition did not report "not loaded" error when collection is ever loaded

```
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0", [par[1].name])
>>> res[0].ids
[0, 1259, 1977, 1976, 1965, 219, 4192, 2701, 672, 4051]
>>>
>>> par[1].release()
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0", [par[1].name])
>>> res[0].ids
[]
```

### Expected Behavior

Report  partition not loaded error

### Steps To Reproduce

1. create collection with two partitions
2. insert both partitions
3. flush
4. create index
5. collection load
6. search one partition
7. release one partition
8. search the released partition

```python
from pymilvus import CollectionSchema, FieldSchema
from pymilvus import Collection
from pymilvus import connections
from pymilvus import DataType
from pymilvus import Partition
from pymilvus import utility

connections.connect()

dim = 128
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
bool_field = FieldSchema(name="bool", dtype=DataType.BOOL)
string_field = FieldSchema(name="string", dtype=DataType.VARCHAR, max_length=65535)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
schema = CollectionSchema(fields=[int64_field, float_field, bool_field, float_vector])

collection = Collection("test_search_collection_binbin_tmp_3", schema=schema)


collection.create_partition(partition_name="search_partition_1", description="search partition")
par = collection.partitions
import numpy as np
nb=5000
import random
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], [np.bool_(i) for i in range(nb)], vectors])
res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], [np.bool_(i) for i in range(nb)], vectors], par[1].name)
collection.flush()

index_param = {"index_type": "HNSW", "metric_type": "L2", "params": {"M": 48, "efConstruction": 500}}
collection.create_index("float_vector", index_param, index_name="index_name_1")

collection.load()
par[1].name
limit = 10
nq = 1
default_search_params = {"metric_type": "L2", "params": {"ef": 500}}
res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0", [par[1].name])
print(res[0].ids)

par[1].release()
res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0", [par[1].name])
print(res[0].ids)
collection.drop()
```

**Comment by binbinlv** [comment]
if has not called collection.load() before, only call partition.load(), and release loaded partition, search the released partition, it will report not loaded error.

**Comment by binbinlv** [comment]
Milvus: master-20230509-f6d3b4f7
Fixed.
```
>>> par[1].release()
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0", [par[1].name])
RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=partition=[441346631963474606]: partition not loaded)>, <Time:{'RPC start': '2023-05-09 16:38:18.398187', 'RPC error': '2023-05-09 16:38:18.490883'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/milvus-test-env-3.8/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 666, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/Users/binbin/milvus-test-env-3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/Users/binbin/milvus-test-env-3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus-test-env-3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/Users/binbin/milvus-test-env-3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/Users/binbin/milvus-test-env-3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/milvus-test-env-3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 522, in search
    return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)
  File "/Users/binbin/milvus-test-env-3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 491, in _execute_search_requests
    raise pre_err
  File "/Users/binbin/milvus-test-env-3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 482, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=partition=[441346631963474606]: partition not loaded)>
```
