### ISSUE TITLE
[Bug]: Milvus pulsar pods cannot start

### ISSUE THREAD

**Issue by linggong2023** [milvus-io/milvus#23529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.6
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

milvus-pulsar-bookie-0               0/1     Init:0/1   0          6m40s
milvus-pulsar-bookie-1               0/1     Init:0/1   0          8m48s
milvus-pulsar-bookie-2               0/1     Init:0/1   0          17m
milvus-pulsar-broker-0               0/1     Init:0/2   0          13m
milvus-pulsar-broker-1               0/1     Init:0/2   0          17m
milvus-pulsar-proxy-0                0/1     Init:0/2   0          6m43s
milvus-pulsar-recovery-0             0/1     Init:0/1   0          6m50s

log error：
07:10:16.353 [main] INFO  org.apache.zookeeper.ZooKeeper - Session: 0x300051d2cf9013b closed
Exception in thread "main" com.google.common.util.concurrent.UncheckedExecutionException: org.apache.bookkeeper.bookie.BookieException$MetadataStoreException: Failed to get cluster instance id
	at org.apache.bookkeeper.tools.cli.commands.bookies.InstanceIdCommand.apply(InstanceIdCommand.java:61)
	at org.apache.bookkeeper.bookie.BookieShell$WhatIsInstanceId.runCmd(BookieShell.java:1492)
	at org.apache.bookkeeper.bookie.BookieShell$MyCommand.runCmd(BookieShell.java:238)
	at org.apache.bookkeeper.bookie.BookieShell.run(BookieShell.java:2275)
	at org.apache.bookkeeper.bookie.BookieShell.main(BookieShell.java:2366)
Caused by: java.util.concurrent.ExecutionException: org.apache.bookkeeper.bookie.BookieException$MetadataStoreException: Failed to get cluster instance id
	at org.apache.bookkeeper.meta.MetadataDrivers.runFunctionWithMetadataBookieDriver(MetadataDrivers.java:352)
	at org.apache.bookkeeper.meta.MetadataDrivers.runFunctionWithRegistrationManager(MetadataDrivers.java:372)
	at org.apache.bookkeeper.tools.cli.commands.bookies.InstanceIdCommand.apply(InstanceIdCommand.java:49)
	... 4 more
Caused by: org.apache.bookkeeper.bookie.BookieException$MetadataStoreException: Failed to get cluster instance id
	at org.apache.bookkeeper.discover.ZKRegistrationManager.getClusterInstanceId(ZKRegistrationManager.java:429)
	at org.apache.bookkeeper.tools.cli.commands.bookies.InstanceIdCommand.lambda$apply$0(InstanceIdCommand.java:52)
	at org.apache.bookkeeper.meta.MetadataDrivers.lambda$runFunctionWithRegistrationManager$1(MetadataDrivers.java:372)
	at org.apache.bookkeeper.meta.MetadataDrivers.runFunctionWithMetadataBookieDriver(MetadataDrivers.java:347)
	... 6 more
Caused by: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for BookKeeper metadata
	at org.apache.bookkeeper.discover.ZKRegistrationManager.getClusterInstanceId(ZKRegistrationManager.java:419)
	... 9 more

**Comment by Cheung7788** [comment]
![img_v2_ba1bbbc6-9bde-4092-8aa5-f47780f834eg](https://user-images.githubusercontent.com/28556111/233000245-56a6f11d-8d52-4b9e-b862-240d71e588cc.jpg)

**Comment by locustbaby** [comment]
Could you please share me with the results of `describe` the failed pulsar pod?
Run `k describe pod {pulsar-pod-name}`

**Comment by linggong2023** [comment]
I got below log:
09:02:59.592 [main-SendThread(milvus-shihuo-clothes-pulsar-zookeeper:2181)] INFO  org.apache.zookeeper.ClientCnxn - Session establishment complete on server milvus-shihuo-clothes-pulsar-zookeeper/10.238.49.101:2181, session id = 0x200057d55c601fc, negotiated timeout = 30000

WATCHER::

WatchedEvent state:SyncConnected type:None path:null
Node does not exist: /admin/clusters/milvus-shihuo-clothes-pulsar
09:02:59.597 [main] ERROR org.apache.zookeeper.util.ServiceUtils - Exiting JVM with code 1

**Comment by locustbaby** [comment]
@linggong2023 Is it still stuck?
How do you install the milvus cluster? by helm?
The pulsar we use is open-source version?
If it's still stuck, please describe the pod and check the reason

**Comment by xiaofan-luan** [comment]
Hi team, I thought it should be due the wrong configuration of pulsar zk path

see https://github.com/apache/pulsar/issues/7488

**Comment by xiaofan-luan** [comment]
could you make sure the pulsar config didn't change while you did all operations?
