### ISSUE TITLE
[Bug]: Fail to query on a partition after loading and dropping another

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#23536]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230417-3e33954f
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):2.4.0.dev11
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Fail to query on a partition after loading and dropping another.
```python
@pytest.mark.tags(CaseLabel.L2)
    def test_load_partition_after_load_drop_partition(self):
        """
        target: test load partition after load and drop partition
        method: 1. load partition
                2. drop the loaded partition
                3. load the left partition
        expected: no exception
        """
        collection_w = self.init_collection_general(prefix)[0]
        partition_w1 = self.init_partition_wrap(collection_w, partition1)
        partition_w2 = self.init_partition_wrap(collection_w, partition2)
        partition_w1.load()
        partition_w1.drop()
        partition_w2.load()
        collection_w.query(default_term_expr, partition_names=[partition2])
```

### Expected Behavior

pass

### Steps To Reproduce

```markdown
1. load partition
2. drop the loaded partition
3. load the left partition
4. query on the partition ❌
```

### Milvus Log

```
[2023-04-19 17:47:46 - ERROR - pymilvus.decorators]: RPC error: [query], <MilvusException: (code=1, message=fail to query on all shard leaders, err=fail to Query, QueryNode ID = 1, reason=failed to query channel, err=partition=[440847356268734212]: partition not loaded)>, <Time:{'RPC start': '2023-04-19 17:47:46.140151', 'RPC error': '2023-04-19 17:47:46.159125'}> (decorators.py:108)
[2023-04-19 17:47:46 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/zilliz/nico/milvus/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/Users/zilliz/nico/milvus/tests/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/orm/collection.py", line 744, in query
    res = conn.query(self._name, expr, output_fields, partition_names,
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 949, in query
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to query on all shard leaders, err=fail to Query, QueryNode ID = 1, reason=failed to query channel, err=partition=[440847356268734212]: partition not loaded)>
 (api_request.py:39)
[2023-04-19 17:47:46 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to query on all shard leaders, err=fail to Query, QueryNode ID = 1, reason=failed to query channel, err=partition=[440847356268734212]: partition not loaded)> (api_request.py:40)
```

**Comment by NicoYuan1986** [comment]
Verify fixed.
