### ISSUE TITLE
[Bug]: Search failed reporting partition not loaded after loading collection

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#23534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230417-3e33954f
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):2.4.0.dev11
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Search failed reporting partition not loaded after loading collection.
```python
    @pytest.mark.tags(CaseLabel.L2)
    def test_load_collection_after_load_release_partition(self):
        """
        target: test load collection after load and release partition
        method: 1. load partition
                2. release partition
                3. load collection
                4. search on the collection
        expected: no exception
        """
        collection_w = self.init_collection_general(prefix)[0]
        partition_w1 = self.init_partition_wrap(collection_w, partition1)
        partition_w2 = self.init_partition_wrap(collection_w, partition2)
        partition_w1.load()
        partition_w1.release()
        collection_w.load()
        collection_w.search(vectors, default_search_field, default_search_params,
                            default_limit, partition_names=[partition1, partition2])
```

### Expected Behavior

pass

### Steps To Reproduce

```markdown
1. load partition
2. release partition
3. load collection
4. search on the collection ❌
```

### Milvus Log

```
[2023-04-19 17:16:26 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=partition=[440847356268723528 440847356268723533]: partition not loaded)>, <Time:{'RPC start': '2023-04-19 17:16:26.123929', 'RPC error': '2023-04-19 17:16:26.153197'}> (decorators.py:108)
[2023-04-19 17:16:26 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/zilliz/nico/milvus/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/Users/zilliz/nico/milvus/tests/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/orm/collection.py", line 660, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 518, in search
    return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 487, in _execute_search_requests
    raise pre_err
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 478, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=partition=[440847356268723528 440847356268723533]: partition not loaded)>
 (api_request.py:39)
[2023-04-19 17:16:26 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=partition=[440847356268723528 440847356268723533]: partition not loaded)> (api_request.py:40)

```

**Comment by NicoYuan1986** [comment]
Verify fixed.
