### ISSUE TITLE
[Bug]: [Nightly]Release a loaded partition will occasionally fail because of rpc deadline exceeded 

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#23554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:4fe363c
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):2.4.0.dev11
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Release a loaded partition will occasionally fail because of rpc deadline exceeded.
```
[2023-04-19T21:40:44.907Z] [2023-04-19 18:03:47 - ERROR - pymilvus.decorators]: RPC error: [release_partitions], <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)>, <Time:{'RPC start': '2023-04-19 18:03:27.771365', 'RPC error': '2023-04-19 18:03:47.772585'}> (decorators.py:108)
[2023-04-19T21:40:44.907Z] [2023-04-19 18:03:47 - ERROR - ci_test]: Traceback (most recent call last):
[2023-04-19T21:40:44.907Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2023-04-19T21:40:44.907Z]     return func(self, *args, **kwargs)
[2023-04-19T21:40:44.907Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 819, in release_partitions
[2023-04-19T21:40:44.907Z]     response = rf.result()
[2023-04-19T21:40:44.907Z]   File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 797, in result
[2023-04-19T21:40:44.907Z]     raise self
[2023-04-19T21:40:44.907Z] grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
[2023-04-19T21:40:44.907Z] 	status = StatusCode.DEADLINE_EXCEEDED
[2023-04-19T21:40:44.907Z] 	details = "Deadline Exceeded"
[2023-04-19T21:40:44.907Z] 	debug_error_string = "UNKNOWN:Deadline Exceeded {created_time:"2023-04-19T18:03:47.772201235+00:00", grpc_status:4}"
[2023-04-19T21:40:44.907Z] >
[2023-04-19T21:40:44.907Z] 
[2023-04-19T21:40:44.907Z] The above exception was the direct cause of the following exception:
[2023-04-19T21:40:44.907Z] 
[2023-04-19T21:40:44.907Z] Traceback (most recent call last):
[2023-04-19T21:40:44.907Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2023-04-19T21:40:44.907Z]     res = func(*args, **_kwargs)
[2023-04-19T21:40:44.907Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2023-04-19T21:40:44.907Z]     return func(*arg, **kwargs)
[2023-04-19T21:40:44.907Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/partition.py", line 250, in release
[2023-04-19T21:40:44.907Z]     return conn.release_partitions(self._collection.name, [self._name], timeout=timeout, **kwargs)
[2023-04-19T21:40:44.907Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2023-04-19T21:40:44.907Z]     raise e
[2023-04-19T21:40:44.907Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2023-04-19T21:40:44.907Z]     return func(*args, **kwargs)
[2023-04-19T21:40:44.907Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2023-04-19T21:40:44.907Z]     ret = func(self, *args, **kwargs)
[2023-04-19T21:40:44.907Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 64, in handler
[2023-04-19T21:40:44.907Z]     raise MilvusException(message=f"rpc deadline exceeded: {timeout_msg}") from e
[2023-04-19T21:40:44.907Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)>
[2023-04-19T21:40:44.907Z]  (api_request.py:39)
[2023-04-19T21:40:44.907Z] [2023-04-19 18:03:47 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=rpc deadline exceeded: Retry timeout: 20s)> (api_request.py:40)
```

### Expected Behavior

pass

### Steps To Reproduce

```markdown
1. create a collection and 2 partitions
2. load a partition
3. release the partition -> raise error
```

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/347/pipeline/155
2. log: [artifacts-milvus-distributed-kafka-nightly-347-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/347/artifact/artifacts-milvus-distributed-kafka-nightly-347-pymilvus-e2e-logs.tar.gz)
3. collection name: collection_mJY2yDK4
4. failed time: [2023-04-19T18:03:49.286Z] [gw0] [  8%] FAILED testcases/test_collection.py::TestLoadPartition::test_load_partitions_after_load_partition_release_partitions

**Comment by NicoYuan1986** [comment]
Similar situation: 
1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/347/pipeline/155
2. log: [artifacts-milvus-distributed-kafka-nightly-347-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/347/artifact/artifacts-milvus-distributed-kafka-nightly-347-pymilvus-e2e-logs.tar.gz)
3. collection name: collection_b353D0Ln
4. failed time: [2023-04-19T18:03:49.286Z] [gw2] [  8%] FAILED testcases/test_collection.py::TestLoadPartition::test_load_partitions_release_collection
5. steps: 
```
1. create a collection and 2 partitions
2. load a partition
3. release the partition
4. load the partition again ❌
```

**Comment by bigsheeper** [comment]
@NicoYuan1986 Cannot reproduce, please help to make a verify
assign @NicoYuan1986

**Comment by NicoYuan1986** [comment]
I can't either.
