### ISSUE TITLE
[Bug]: Insert failed with error `memory quota exhausted, please allocate more resources` with setting `quotaAndLimits.enabled=false` after upgrade from v2.2.5 to master-20230420-a2ab94ec to 

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#23592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.2.5 --> master-20230420-a2ab94ec
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):kafka    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://user-images.githubusercontent.com/12268675/233531737-519be7ea-834f-477b-b567-1face460df6a.png)

```
[2023-04-20T10:57:47.556Z] <name>: deploy_test_index_type_BIN_IVF_FLAT_is_compacted_not_compacted_segment_status_all_is_string_indexed_not_string_indexed_replica_number_0_is_deleted_is_deleted_data_size_3000

[2023-04-20T10:57:47.556Z] <partitions>: [{"name": "_default", "collection_name": "deploy_test_index_type_BIN_IVF_FLAT......  (api_request.py:31)

[2023-04-20T10:57:47.556Z] [2023-04-20 10:57:44 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 120} (api_request.py:56)

[2023-04-20T10:57:47.556Z] [2023-04-20 10:57:44 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)

[2023-04-20T10:57:47.557Z] [2023-04-20 10:57:44 - INFO - ci_test]: inserted 3000 data into collection deploy_test_index_type_BIN_IVF_FLAT_is_compacted_not_compacted_segment_status_all_is_string_indexed_not_string_indexed_replica_number_0_is_deleted_is_deleted_data_size_3000 (common_func.py:780)

[2023-04-20T10:57:47.557Z] [2023-04-20 10:57:44 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [      int64   float varchar                                      binary_vector

[2023-04-20T10:57:47.557Z] 0         0     0.0       0        b'tqD7\x94\xa3\x9e\x15M\xad=C\xec\xa9\xeaO'

[2023-04-20T10:57:47.557Z] 1         1     1.0       1  b'\xc2\xc4\xa4&\xc1\xf5\x1c\xa5\xe9\xdf\xf2x:9...

[2023-04-20T10:57:47.557Z] 2         2     2.0       2  b'\xb5\xa5\x0f\xe1)\xd4~\xafe\x9e......, kwargs: {'timeout': 120} (api_request.py:56)

[2023-04-20T10:57:47.557Z] [2023-04-20 10:57:44 - ERROR - pymilvus.decorators]: RPC error: [batch_insert], <MilvusException: (code=53, message=deny to write, reason: memory quota exhausted, please allocate more resources, req: /milvus.proto.milvus.MilvusService/Insert)>, <Time:{'RPC start': '2023-04-20 10:57:44.832348', 'RPC error': '2023-04-20 10:57:44.836087'}> (decorators.py:108)

[2023-04-20T10:57:47.557Z] [2023-04-20 10:57:44 - ERROR - ci_test]: Traceback (most recent call last):

[2023-04-20T10:57:47.557Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2023-04-20T10:57:47.557Z]     res = func(*args, **_kwargs)

[2023-04-20T10:57:47.557Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2023-04-20T10:57:47.557Z]     return func(*arg, **kwargs)

[2023-04-20T10:57:47.557Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 430, in insert

[2023-04-20T10:57:47.557Z]     res = conn.batch_insert(self._name, entities, partition_name,

[2023-04-20T10:57:47.557Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-04-20T10:57:47.557Z]     raise e

[2023-04-20T10:57:47.557Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-04-20T10:57:47.557Z]     return func(*args, **kwargs)

[2023-04-20T10:57:47.557Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-04-20T10:57:47.557Z]     ret = func(self, *args, **kwargs)

[2023-04-20T10:57:47.557Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-04-20T10:57:47.557Z]     raise e

[2023-04-20T10:57:47.557Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-04-20T10:57:47.557Z]     return func(self, *args, **kwargs)

[2023-04-20T10:57:47.557Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 406, in batch_insert

[2023-04-20T10:57:47.557Z]     raise err

[2023-04-20T10:57:47.557Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 402, in batch_insert

[2023-04-20T10:57:47.557Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2023-04-20T10:57:47.557Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=53, message=deny to write, reason: memory quota exhausted, please allocate more resources, req: /milvus.proto.milvus.MilvusService/Insert)>
```

### Expected Behavior

all test cases work well

### Milvus Log

failed job: deploy_test_kafka_cron/665
log:
[artifacts-kafka-standalone-upgrade-665-server-first-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/11291938/artifacts-kafka-standalone-upgrade-665-server-first-deployment-logs.tar.gz)

[artifacts-kafka-standalone-upgrade-665-server-second-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/11291937/artifacts-kafka-standalone-upgrade-665-server-second-deployment-logs.tar.gz)

### Anything else?

Some test cases also failed with the error 
```
[2023-04-20T10:57:47.545Z] <name>: deploy_test_index_type_HNSW_replica_number_0_empty

[2023-04-20T10:57:47.545Z] <partitions>: [{"name": "_default", "collection_name": "deploy_test_index_type_HNSW_replica_number_0_empty", "description": ""}]

[2023-04-20T10:57:47.545Z] <description>: 

[2023-04-20T10:57:47.545Z] <schema>: {

[2023-04-20T10:57:47.545Z]   auto_id: False

[2023-04-20T10:57:47.545Z]   description: 

[2023-04-20T10:57:47.545Z]   fields: [{

[2023-04-20T10:57:47.545Z]     name: ......  (api_request.py:31)

[2023-04-20T10:57:47.545Z] [2023-04-20 10:56:52 - DEBUG - ci_test]: (api_request)  : [wait_for_loading_complete] args: ['deploy_test_index_type_HNSW_replica_number_0_empty', None, 20, 'default'], kwargs: {} (api_request.py:56)

[2023-04-20T10:57:47.545Z] [2023-04-20 10:56:52 - ERROR - pymilvus.decorators]: RPC error: [get_loading_progress], <MilvusException: (code=1, message=collection 440922410268430617 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2023-04-20 10:56:52.941459', 'RPC error': '2023-04-20 10:56:52.942437'}> (decorators.py:108)

[2023-04-20T10:57:47.545Z] [2023-04-20 10:56:52 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=collection 440922410268430617 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2023-04-20 10:56:52.941443', 'RPC error': '2023-04-20 10:56:52.942552'}> (decorators.py:108)

[2023-04-20T10:57:47.545Z] [2023-04-20 10:56:52 - ERROR - ci_test]: Traceback (most recent call last):

[2023-04-20T10:57:47.545Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2023-04-20T10:57:47.545Z]     res = func(*args, **_kwargs)

[2023-04-20T10:57:47.545Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2023-04-20T10:57:47.545Z]     return func(*arg, **kwargs)

[2023-04-20T10:57:47.545Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/utility.py", line 277, in wait_for_loading_complete

[2023-04-20T10:57:47.545Z]     return _get_connection(using).wait_for_loading_collection(collection_name, timeout=timeout)

[2023-04-20T10:57:47.545Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-04-20T10:57:47.545Z]     raise e

[2023-04-20T10:57:47.545Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-04-20T10:57:47.545Z]     return func(*args, **kwargs)

[2023-04-20T10:57:47.545Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-04-20T10:57:47.545Z]     ret = func(self, *args, **kwargs)

[2023-04-20T10:57:47.545Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-04-20T10:57:47.545Z]     raise e

[2023-04-20T10:57:47.545Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-04-20T10:57:47.545Z]     return func(self, *args, **kwargs)

[2023-04-20T10:57:47.545Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 728, in wait_for_loading_collection

[2023-04-20T10:57:47.545Z]     progress = self.get_loading_progress(collection_name, timeout=timeout)

[2023-04-20T10:57:47.545Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-04-20T10:57:47.545Z]     raise e

[2023-04-20T10:57:47.545Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-04-20T10:57:47.545Z]     return func(*args, **kwargs)

[2023-04-20T10:57:47.546Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-04-20T10:57:47.546Z]     ret = func(self, *args, **kwargs)

[2023-04-20T10:57:47.546Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-04-20T10:57:47.546Z]     raise e

[2023-04-20T10:57:47.546Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-04-20T10:57:47.546Z]     return func(self, *args, **kwargs)

[2023-04-20T10:57:47.546Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 795, in get_loading_progress

[2023-04-20T10:57:47.546Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2023-04-20T10:57:47.546Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection 440922410268430617 has not been loaded to memory or load failed)>

[2023-04-20T10:57:47.546Z]  (api_request.py:39)
```

**Comment by zhuwenxing** [comment]
![image](https://user-images.githubusercontent.com/12268675/233532630-bf40ee87-b6df-4b27-b17d-247cd150a594.png)

it indeed reaches the limit.

**Comment by zhuwenxing** [comment]
in the 2.2.0 release， the memory usage is much lower.
![image](https://user-images.githubusercontent.com/12268675/233534939-90b380d0-6122-47a4-a7ca-6543ea01298d.png)

**Comment by aoiasd** [comment]
May cause by we use compact policy not based on index and compact will be more radical,  and this change will revert when https://github.com/milvus-io/milvus/pull/25470 merged. We need test after this pr.

**Comment by zhuwenxing** [comment]
master-20230713-65cb52d0
![image](https://github.com/milvus-io/milvus/assets/12268675/bc49d4d0-c8e1-4c49-acaa-e9ba0fb7a6bf)

memory usage reduced to a normal level
