### ISSUE TITLE
[Bug]: Search failed when outputting binary vectors

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#23661]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230423-b7cb34b9
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0.dev12
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Search failed when outputting binary vectors.
```
>>> res = collection.search(binary_vectors[:nq], "binary_vector", search_params, 10, "int64 >= 0",
...                         output_fields=['binary_vector'])
Unexpected error: [search], 'bytes' object has no attribute 'data', <Time: {'RPC start': '2023-04-24 17:02:53.115727', 'Exception': '2023-04-24 17:02:53.149099'}>
Traceback (most recent call last):
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 87, in handler
    raise e
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 518, in search
    return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 487, in _execute_search_requests
    raise pre_err
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 482, in _execute_search_requests
    return ChunkedQueryResult(raws, auto_id, round_decimal)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/client/abstract.py", line 471, in __init__
    self._pack(self._raw_list)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/client/abstract.py", line 519, in _pack
    field.vectors.binary_vector.data.extend(field_data.vectors.binary_vector.data[
AttributeError: 'bytes' object has no attribute 'data'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/orm/collection.py", line 660, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 121, in handler
    raise MilvusException(message=f"Unexpected error, message=<{str(e)}>") from e
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Unexpected error, message=<'bytes' object has no attribute 'data'>)>
```

### Expected Behavior

return binary vectors

### Steps To Reproduce

```python
from pymilvus import CollectionSchema, FieldSchema, Collection, connections, DataType, Partition, utility
import numpy as np
import random

dim = 128
nb = 3000
nq = 2
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True, auto_id=False)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
binary_vector = FieldSchema(name="binary_vector", dtype=DataType.BINARY_VECTOR, dim=dim)
schema = CollectionSchema(fields=[int64_field, float_field, binary_vector])

connections.connect()
# utility.drop_collection("test_binary")
collection = Collection("test_binary", schema=schema)

raw_vectors = []
binary_vectors = []
for _ in range(nb):
    raw_vector = [random.randint(0, 1) for _ in range(dim)]
    raw_vectors.append(raw_vector)
    # packs a binary-valued array into bits in a unit8 array, and bytes array_of_ints
    binary_vectors.append(bytes(np.packbits(raw_vector, axis=-1).tolist()))
collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], binary_vectors])

index = {"index_type": "BIN_FLAT", "params": {"nlist": 128}, "metric_type": "JACCARD"}
collection.create_index("binary_vector", index)

collection.load()
search_params = {"metric_type": "JACCARD", "params": {"nprobe": 10}}
res = collection.search(binary_vectors[:nq], "binary_vector", search_params, 10, "int64 >= 0",
                        output_fields=['binary_vector'])
```

**Comment by NicoYuan1986** [comment]
@XuanYang-cn Is this a pymilvus bug?

**Comment by XuanYang-cn** [comment]
This error is raised from Milvus server, not a pymilvus bug

**Comment by yanliang567** [comment]
/assign @cydrain 
is it a bug in getVectorById ?

**Comment by cydrain** [comment]
"AttributeError: 'bytes' object has no attribute 'data'"
above error is coming from pymilvus/client/abstract.py::519
![Screenshot from 2023-05-10 11-48-14](https://github.com/milvus-io/milvus/assets/3992404/8cd3da07-be96-4ac4-ad00-d5141be0642e)

@XuanYang-cn please help to check

**Comment by binbinlv** [comment]
@XuanYang-cn 
any updates？

**Comment by yanliang567** [comment]
any updates?

**Comment by NicoYuan1986** [comment]
Update: 2.4.0.dev90, still not fix. please help ~ @XuanYang-cn

**Comment by XuanYang-cn** [comment]
pymilvus-2.2.14.dev10
pymilvus-2.4.0.dev100
/assign @NicoYuan1986 
/unassign

**Comment by NicoYuan1986** [comment]
master fixed. pymilvus==2.4.0.dev101

2.2 still reports error , pymilvus==2.2.14.dev12
```
>>> res = collection.search(binary_vectors[:nq], "binary_vector", search_params, 10, "int64 >= 0",
...                         output_fields=['binary_vector'])
Unexpected error: [search], 'bytes' object has no attribute 'data', <Time: {'RPC start': '2023-07-18 18:58:11.794183', 'Exception': '2023-07-18 18:58:11.834152'}>
Traceback (most recent call last):
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.10/site-packages/pymilvus/decorators.py", line 122, in handler
    return func(*args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.10/site-packages/pymilvus/decorators.py", line 161, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.10/site-packages/pymilvus/decorators.py", line 103, in handler
    raise e from e
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.10/site-packages/pymilvus/decorators.py", line 68, in handler
    return func(*args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 660, in search
    return self._execute_search_requests(
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 620, in _execute_search_requests
    raise pre_err from pre_err
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 615, in _execute_search_requests
    return ChunkedQueryResult(raws, round_decimal)
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.10/site-packages/pymilvus/client/abstract.py", line 508, in __init__
    self._pack(self._raw_list)
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.10/site-packages/pymilvus/client/abstract.py", line 574, in _pack
    field.vectors.binary_vector.data.extend(
AttributeError: 'bytes' object has no attribute 'data'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.10/site-packages/pymilvus/orm/collection.py", line 706, in search
    res = conn.search(
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.10/site-packages/pymilvus/decorators.py", line 144, in handler
    raise MilvusException(message=f"Unexpected error, message=<{e!s}>") from e
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Unexpected error, message=<'bytes' object has no attribute 'data'>)>

```

**Comment by XuanYang-cn** [comment]
/assign @NicoYuan1986 
/unassign
pymilvus-2.2.14.dev16 Please try this version

**Comment by NicoYuan1986** [comment]
Verify fixed.
