### ISSUE TITLE
[Bug]: RootCoord failed to started: [ERROR] [rootcoord/kv_catalog.go:635] ["fail to save the role"] 

### ISSUE THREAD

**Issue by chunyuforka** [milvus-io/milvus#23861]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.6
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2): 
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 32C64G * 3
- GPU:  null
- Others:
```

### Current Behavior

The cluster cannot be started after being restarted, The rootCoord program reported an error

### Expected Behavior

start server

### Milvus Log

```
[2023/05/04 08:51:03.987 +00:00] [ERROR] [rootcoord/kv_catalog.go:635] ["fail to save the role"] [key=root-coord/credential/roles/admin] [error="the key[root-coord/credential/roles/admin] is existed"] [stack="[github.com/milvus-io/milvus/internal/metastore/kv/rootcoord.(*Catalog).CreateRole\n\t/go/src/github.com/milvus-io/milvus/internal/metastore/kv/rootcoord/kv_catalog.go:635\ngithub.com/milvus-io/milvus/internal/rootcoord.(*MetaTable).CreateRole\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/meta_table.go:911\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).initRbac\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:539\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).initInternal\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:476\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).Init.func2\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:518\nsync.(*Once).doSlow\n\t/usr/local/go/src/sync/once.go:68\nsync.(*Once).Do\n\t/usr/local/go/src/sync/once.go:59\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).Init\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:517\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:212\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:142\ngithub.com/milvus-io/milvus/cmd/components.(*RootCoord).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/root_coord.go:57\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:102](http://github.com/milvus-io/milvus/internal/metastore/kv/rootcoord.(*Catalog).CreateRole/n/t/go/src/github.com/milvus-io/milvus/internal/metastore/kv/rootcoord/kv_catalog.go:635/ngithub.com/milvus-io/milvus/internal/rootcoord.(*MetaTable).CreateRole/n/t/go/src/github.com/milvus-io/milvus/internal/rootcoord/meta_table.go:911/ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).initRbac/n/t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:539/ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).initInternal/n/t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:476/ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).Init.func2/n/t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:518/nsync.(*Once).doSlow/n/t/usr/local/go/src/sync/once.go:68/nsync.(*Once).Do/n/t/usr/local/go/src/sync/once.go:59/ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).Init/n/t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:517/ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).init/n/t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:212/ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).Run/n/t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:142/ngithub.com/milvus-io/milvus/cmd/components.(*RootCoord).Run/n/t/go/src/github.com/milvus-io/milvus/cmd/components/root_coord.go:57/ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1/n/t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:102)"]
[2023/05/04 08:51:03.988 +00:00] [ERROR] [rootcoord/kv_catalog.go:635] ["fail to save the role"] [key=root-coord/credential/roles/public] [error="the key[root-coord/credential/roles/public] is existed"] [stack="[github.com/milvus-io/milvus/internal/metastore/kv/rootcoord.(*Catalog).CreateRole\n\t/go/src/github.com/milvus-io/milvus/internal/metastore/kv/rootcoord/kv_catalog.go:635\ngithub.com/milvus-io/milvus/internal/rootcoord.(*MetaTable).CreateRole\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/meta_table.go:911\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).initRbac\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:539\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).initInternal\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:476\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).Init.func2\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:518\nsync.(*Once).doSlow\n\t/usr/local/go/src/sync/once.go:68\nsync.(*Once).Do\n\t/usr/local/go/src/sync/once.go:59\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).Init\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:517\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:212\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:142\ngithub.com/milvus-io/milvus/cmd/components.(*RootCoord).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/root_coord.go:57\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:102](http://github.com/milvus-io/milvus/internal/metastore/kv/rootcoord.(*Catalog).CreateRole/n/t/go/src/github.com/milvus-io/milvus/internal/metastore/kv/rootcoord/kv_catalog.go:635/ngithub.com/milvus-io/milvus/internal/rootcoord.(*MetaTable).CreateRole/n/t/go/src/github.com/milvus-io/milvus/internal/rootcoord/meta_table.go:911/ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).initRbac/n/t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:539/ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).initInternal/n/t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:476/ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).Init.func2/n/t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:518/nsync.(*Once).doSlow/n/t/usr/local/go/src/sync/once.go:68/nsync.(*Once).Do/n/t/usr/local/go/src/sync/once.go:59/ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).Init/n/t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:517/ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).init/n/t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:212/ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).Run/n/t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:142/ngithub.com/milvus-io/milvus/cmd/components.(*RootCoord).Run/n/t/go/src/github.com/milvus-io/milvus/cmd/components/root_coord.go:57/ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1/n/t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:102)"]
[2023/05/04 08:52:39.493 +00:00] [ERROR] [roles/roles.go:318] ["Get signal to exit\n"] [signal=terminated] [stack="[github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:318\ngithub.com/milvus-io/milvus/cmd/milvus.(*run).execute\n\t/go/src/github.com/milvus-io/milvus/cmd/milvus/run.go:112\ngithub.com/milvus-io/milvus/cmd/milvus.RunMilvus\n\t/go/src/github.com/milvus-io/milvus/cmd/milvus/milvus.go:60\nmain.main\n\t/go/src/github.com/milvus-io/milvus/cmd/main.go:26\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250](http://github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run/n/t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:318/ngithub.com/milvus-io/milvus/cmd/milvus.(*run).execute/n/t/go/src/github.com/milvus-io/milvus/cmd/milvus/run.go:112/ngithub.com/milvus-io/milvus/cmd/milvus.RunMilvus/n/t/go/src/github.com/milvus-io/milvus/cmd/milvus/milvus.go:60/nmain.main/n/t/go/src/github.com/milvus-io/milvus/cmd/main.go:26/nruntime.main/n/t/usr/local/go/src/runtime/proc.go:250)"]
[2023/05/04 08:52:39.493 +00:00] [WARN] [sessionutil/session_util.go:412] ["keep alive"] [error="context done"]
[2023/05/04 08:52:39.493 +00:00] [WARN] [rootcoord/proxy_manager.go:110] ["stop watching etcd loop"]
{"level":"warn","ts":"2023-05-04T08:52:39.496Z","logger":"etcd-client","caller":"v3@v3.5.5/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00022d6c0/milvus-saas-1-etcd:2379","attempt":0,"error":"rpc error: code = Canceled desc = grpc: the client connection is closing"}
```

**Comment by yanliang567** [comment]
@chunyuforka what requests did you do before restarting milvus? also could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @chunyuforka

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Environment
> ```gfm
> - Milvus version: v2.2.6
> - Deployment mode(standalone or cluster): cluster
> - MQ type(rocksmq, pulsar or kafka):    kafka
> - SDK version(e.g. pymilvus v2.0.0rc2): 
> - OS(Ubuntu or CentOS): CentOS
> - CPU/Memory: 32C64G * 3
> - GPU:  null
> - Others:
> ```
> 
> ### Current Behavior
> The cluster cannot be started after being restarted, The rootCoord program reported an error
> 
> ### Expected Behavior
> start server
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Milvus Log
> ```
> [2023/05/04 08:51:03.987 +00:00] [ERROR] [rootcoord/kv_catalog.go:635] ["fail to save the role"] [key=root-coord/credential/roles/admin] [error="the key[root-coord/credential/roles/admin] is existed"] [stack="[github.com/milvus-io/milvus/internal/metastore/kv/rootcoord.(*Catalog).CreateRole\n\t/go/src/github.com/milvus-io/milvus/internal/metastore/kv/rootcoord/kv_catalog.go:635\ngithub.com/milvus-io/milvus/internal/rootcoord.(*MetaTable).CreateRole\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/meta_table.go:911\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).initRbac\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:539\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).initInternal\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:476\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).Init.func2\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:518\nsync.(*Once).doSlow\n\t/usr/local/go/src/sync/once.go:68\nsync.(*Once).Do\n\t/usr/local/go/src/sync/once.go:59\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).Init\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:517\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:212\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:142\ngithub.com/milvus-io/milvus/cmd/components.(*RootCoord).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/root_coord.go:57\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:102](http://github.com/milvus-io/milvus/internal/metastore/kv/rootcoord.(*Catalog).CreateRole/n/t/go/src/github.com/milvus-io/milvus/internal/metastore/kv/rootcoord/kv_catalog.go:635/ngithub.com/milvus-io/milvus/internal/rootcoord.(*MetaTable).CreateRole/n/t/go/src/github.com/milvus-io/milvus/internal/rootcoord/meta_table.go:911/ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).initRbac/n/t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:539/ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).initInternal/n/t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:476/ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).Init.func2/n/t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:518/nsync.(*Once).doSlow/n/t/usr/local/go/src/sync/once.go:68/nsync.(*Once).Do/n/t/usr/local/go/src/sync/once.go:59/ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).Init/n/t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:517/ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).init/n/t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:212/ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).Run/n/t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:142/ngithub.com/milvus-io/milvus/cmd/components.(*RootCoord).Run/n/t/go/src/github.com/milvus-io/milvus/cmd/components/root_coord.go:57/ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1/n/t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:102)"]
> [2023/05/04 08:51:03.988 +00:00] [ERROR] [rootcoord/kv_catalog.go:635] ["fail to save the role"] [key=root-coord/credential/roles/public] [error="the key[root-coord/credential/roles/public] is existed"] [stack="[github.com/milvus-io/milvus/internal/metastore/kv/rootcoord.(*Catalog).CreateRole\n\t/go/src/github.com/milvus-io/milvus/internal/metastore/kv/rootcoord/kv_catalog.go:635\ngithub.com/milvus-io/milvus/internal/rootcoord.(*MetaTable).CreateRole\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/meta_table.go:911\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).initRbac\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:539\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).initInternal\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:476\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).Init.func2\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:518\nsync.(*Once).doSlow\n\t/usr/local/go/src/sync/once.go:68\nsync.(*Once).Do\n\t/usr/local/go/src/sync/once.go:59\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).Init\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:517\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:212\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:142\ngithub.com/milvus-io/milvus/cmd/components.(*RootCoord).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/root_coord.go:57\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:102](http://github.com/milvus-io/milvus/internal/metastore/kv/rootcoord.(*Catalog).CreateRole/n/t/go/src/github.com/milvus-io/milvus/internal/metastore/kv/rootcoord/kv_catalog.go:635/ngithub.com/milvus-io/milvus/internal/rootcoord.(*MetaTable).CreateRole/n/t/go/src/github.com/milvus-io/milvus/internal/rootcoord/meta_table.go:911/ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).initRbac/n/t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:539/ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).initInternal/n/t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:476/ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).Init.func2/n/t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:518/nsync.(*Once).doSlow/n/t/usr/local/go/src/sync/once.go:68/nsync.(*Once).Do/n/t/usr/local/go/src/sync/once.go:59/ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).Init/n/t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:517/ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).init/n/t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:212/ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).Run/n/t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:142/ngithub.com/milvus-io/milvus/cmd/components.(*RootCoord).Run/n/t/go/src/github.com/milvus-io/milvus/cmd/components/root_coord.go:57/ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1/n/t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:102)"]
> [2023/05/04 08:52:39.493 +00:00] [ERROR] [roles/roles.go:318] ["Get signal to exit\n"] [signal=terminated] [stack="[github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:318\ngithub.com/milvus-io/milvus/cmd/milvus.(*run).execute\n\t/go/src/github.com/milvus-io/milvus/cmd/milvus/run.go:112\ngithub.com/milvus-io/milvus/cmd/milvus.RunMilvus\n\t/go/src/github.com/milvus-io/milvus/cmd/milvus/milvus.go:60\nmain.main\n\t/go/src/github.com/milvus-io/milvus/cmd/main.go:26\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250](http://github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run/n/t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:318/ngithub.com/milvus-io/milvus/cmd/milvus.(*run).execute/n/t/go/src/github.com/milvus-io/milvus/cmd/milvus/run.go:112/ngithub.com/milvus-io/milvus/cmd/milvus.RunMilvus/n/t/go/src/github.com/milvus-io/milvus/cmd/milvus/milvus.go:60/nmain.main/n/t/go/src/github.com/milvus-io/milvus/cmd/main.go:26/nruntime.main/n/t/usr/local/go/src/runtime/proc.go:250)"]
> [2023/05/04 08:52:39.493 +00:00] [WARN] [sessionutil/session_util.go:412] ["keep alive"] [error="context done"]
> [2023/05/04 08:52:39.493 +00:00] [WARN] [rootcoord/proxy_manager.go:110] ["stop watching etcd loop"]
> {"level":"warn","ts":"2023-05-04T08:52:39.496Z","logger":"etcd-client","caller":"v3@v3.5.5/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00022d6c0/milvus-saas-1-etcd:2379","attempt":0,"error":"rpc error: code = Canceled desc = grpc: the client connection is closing"}
> ```
> 
> ### Anything else?
> _No response_

The actual problem is rootcoord got killed. if root coord  reboot can it recover?

**Comment by chunyuforka** [comment]
The rootCoord service has been rebooting repeatedly，the logs are identical。
Rootcoord was killed by kubelet，because run 'kubectl describes pod' getting the following log:
```
Events:
  Type     Reason     Age                     From     Message
  ----     ------     ----                    ----     -------
  Warning  Unhealthy  4m20s (x435 over 154m)  kubelet  Readiness probe failed: HTTP probe failed with statuscode: 500
  Warning  BackOff    40s (x255 over 127m)    kubelet  Back-off restarting failed container

```

**Comment by xiaofan-luan** [comment]
> The rootCoord service has been rebooting repeatedly，the logs are identical。 Rootcoord was killed by kubelet，because run 'kubectl describes pod' getting the following log:
> 
> ```
> Events:
>   Type     Reason     Age                     From     Message
>   ----     ------     ----                    ----     -------
>   Warning  Unhealthy  4m20s (x435 over 154m)  kubelet  Readiness probe failed: HTTP probe failed with statuscode: 500
>   Warning  BackOff    40s (x255 over 127m)    kubelet  Back-off restarting failed container
> ```
 
could you offer more logs about why rootcoord is crashing? we need at least logs from etcd and better to have logs with other node

**Comment by chunyuforka** [comment]
[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/11410837/milvus-log.tar.gz)

**Comment by chunyuforka** [comment]
> [milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/11410837/milvus-log.tar.gz)

@xiaofan-luan That is  log-file

**Comment by Vatsalparsaniya** [comment]
Team facing related issue
```python
[2023/06/01 13:57:44.716 +00:00] [ERROR] [rootcoord/kv_catalog.go:635] ["fail to save the role"] [key=root-coord/credential/roles/admin] [error="the key[root-coord/credential/roles/admin] is existed"] [stack="github.com/milvus-io/milvus/internal/metastore/kv/rootcoord.(*Catalog).CreateRole\n\t/go/src/github.com/milvus-io/milvus/internal/metastore/kv/rootcoord/kv_catalog.go:635\ngithub.com/milvus-io/milvus/internal/rootcoord.(*MetaTable).CreateRole\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/meta_table.go:906\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).initRbac\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:539\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).initInternal\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:476\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).Init.func2\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:518\nsync.(*Once).doSlow\n\t/usr/local/go/src/sync/once.go:68\nsync.(*Once).Do\n\t/usr/local/go/src/sync/once.go:59\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).Init\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:517\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:212\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:142\ngithub.com/milvus-io/milvus/cmd/components.(*RootCoord).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/root_coord.go:57\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:102"]
[2023/06/01 13:57:44.717 +00:00] [ERROR] [rootcoord/kv_catalog.go:635] ["fail to save the role"] [key=root-coord/credential/roles/public] [error="the key[root-coord/credential/roles/public] is existed"] [stack="github.com/milvus-io/milvus/internal/metastore/kv/rootcoord.(*Catalog).CreateRole\n\t/go/src/github.com/milvus-io/milvus/internal/metastore/kv/rootcoord/kv_catalog.go:635\ngithub.com/milvus-io/milvus/internal/rootcoord.(*MetaTable).CreateRole\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/meta_table.go:906\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).initRbac\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:539\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).initInternal\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:476\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).Init.func2\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:518\nsync.(*Once).doSlow\n\t/usr/local/go/src/sync/once.go:68\nsync.(*Once).Do\n\t/usr/local/go/src/sync/once.go:59\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).Init\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:517\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:212\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:142\ngithub.com/milvus-io/milvus/cmd/components.(*RootCoord).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/root_coord.go:57\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:102"]
[2023/06/01 13:57:44.724 +00:00] [WARN] [retry/retry.go:44] ["retry func failed"] ["retry time"=0] [error="function CompareAndSwap error for compare is false for key: rootcoord"]
```


Logs: [milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/11648726/milvus-log.tar.gz)
Related slack thread: https://milvusio.slack.com/archives/CMNHUC371/p1685643325382409

**Comment by xiaofan-luan** [comment]
this is not the error. But it does happen a restart during that time.
you have to figure out why the node crash.

and your cluster seems to has a clock skew(30s), please check it

**Comment by Vatsalparsaniya** [comment]
Thanks, @xiaofan-luan : root cord is restarting because of bellow error
```python
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x2ef8ded]

goroutine 616 [running]:
github.com/milvus-io/milvus/internal/rootcoord.(*MetaTable).CreateAlias(0xc000f4f810, {0x420afb8, 0xc002630660}, {0xc0014fa750, 0x2b}, {0xc001099d00, 0x3b}, 0x6222c2148000003)
    /go/src/github.com/milvus-io/milvus/internal/rootcoord/meta_table.go:610 +0x22d
github.com/milvus-io/milvus/internal/rootcoord.(*createAliasTask).Execute(0xc0026349b0, {0x420afb8, 0xc002630660})
    /go/src/github.com/milvus-io/milvus/internal/rootcoord/create_alias_task.go:46 +0x14f
github.com/milvus-io/milvus/internal/rootcoord.(*scheduler).execute(0xc000f1f200, {0x421df28, 0xc0026349b0})
    /go/src/github.com/milvus-io/milvus/internal/rootcoord/scheduler.go:88 +0x107
github.com/milvus-io/milvus/internal/rootcoord.(*scheduler).taskLoop(0xc000f1f200)
    /go/src/github.com/milvus-io/milvus/internal/rootcoord/scheduler.go:99 +0x8a
created by github.com/milvus-io/milvus/internal/rootcoord.(*scheduler).Start
    /go/src/github.com/milvus-io/milvus/internal/rootcoord/scheduler.go:71 +0x76
```

**Comment by xiaofan-luan** [comment]
> ```python
> meta_table
> ```

Which Milvus release is it?
