### ISSUE TITLE
[Bug]: pymilvus.exceptions.MilvusException: <MilvusException: (code=55, message=deny to write, reason: time tick long delay, req: /milvus.proto.milvus.MilvusService/Insert)>

### ISSUE THREAD

**Issue by GaoJianwei-CTW** [milvus-io/milvus#23920]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 
v2.1.0
- Deployment mode(standalone or cluster):
cluster
- SDK version
pymilvus v2.2.5
```

### Current Behavior

When I try to build a new vector database, it will raise the error as follow. I restart the cluster, but It did not work.

```python
ERROR:pymilvus.decorators:RPC error: [batch_insert], <MilvusException: (code=55, message=deny to write, reason: time tick long delay, req: /milvus.proto.milvus.MilvusService/Insert)>, <Time:{'RPC start': '2023-05-08 10:58:56.921444', 'RPC error': '2023-05-08 10:58:57.661675'}>
ERROR:root:init vectorstore failed, <MilvusException: (code=55, message=deny to write, reason: time tick long delay, req: /milvus.proto.milvus.MilvusService/Insert)>
Traceback (most recent call last):
  File "/Users/gjwei/Desktop/work/doraemon-branch/chatbot/app/init_vectorstore.py", line 136, in <module>
    vectorstore = init_vectorstore()
  File "/Users/gjwei/Desktop/work/doraemon-branch/chatbot/app/init_vectorstore.py", line 104, in init_vectorstore
    raise e
  File "/Users/gjwei/Desktop/work/doraemon-branch/chatbot/app/init_vectorstore.py", line 92, in init_vectorstore
    docsearch = Milvus.from_documents(
  File "/opt/homebrew/anaconda3/envs/py310/lib/python3.10/site-packages/langchain/vectorstores/base.py", line 272, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
  File "/Users/gjwei/Desktop/work/doraemon-branch/chatbot/app/database/vectorstores/milvus.py", line 447, in from_texts
    milvus.add_texts(texts, metadatas)
  File "/Users/gjwei/Desktop/work/doraemon-branch/chatbot/app/database/vectorstores/milvus.py", line 153, in add_texts
    res = self.col.insert(
  File "/opt/homebrew/anaconda3/envs/py310/lib/python3.10/site-packages/pymilvus/orm/collection.py", line 430, in insert
    res = conn.batch_insert(self._name, entities, partition_name,
  File "/opt/homebrew/anaconda3/envs/py310/lib/python3.10/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/opt/homebrew/anaconda3/envs/py310/lib/python3.10/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/opt/homebrew/anaconda3/envs/py310/lib/python3.10/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/opt/homebrew/anaconda3/envs/py310/lib/python3.10/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/opt/homebrew/anaconda3/envs/py310/lib/python3.10/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/opt/homebrew/anaconda3/envs/py310/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 399, in batch_insert
    raise err
  File "/opt/homebrew/anaconda3/envs/py310/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 395, in batch_insert
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=55, message=deny to write, reason: time tick long delay, req: /milvus.proto.milvus.MilvusService/Insert)>
```

**Comment by yanliang567** [comment]
@GaoJianwei-CTW deny to write when tt long delay is kind of protect from system crash.  we need to investigate why the tt become long. Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @GaoJianwei-CTW

**Comment by GaoJianwei-CTW** [comment]
> @GaoJianwei-CTW deny to write when tt long delay is kind of protect from system crash. we need to investigate why the tt become long. Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
> 
> /assign @GaoJianwei-CTW

Thanks for you reply, here is the log file
[logs.tar.gz](https://github.com/milvus-io/milvus/files/11417353/logs.tar.gz)
