### ISSUE TITLE
[Bug]: Create collection failed with error `failed to watch channels, code: UnexpectedError, reason: context deadline exceeded`

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#23933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230506-ad75afdc
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2023-05-07T09:41:38.258Z] ------------------------------ Captured log setup ------------------------------

[2023-05-07T09:41:38.258Z] [2023-05-07 09:35:38 - INFO - ci_test]: *********************************** setup *********************************** (client_base.py:39)

[2023-05-07T09:41:38.258Z] [2023-05-07 09:35:38 - INFO - ci_test]: [setup_method] Start setup test case test_task_all. (client_base.py:40)

[2023-05-07T09:41:38.258Z] ------------------------------ Captured log call -------------------------------

[2023-05-07T09:41:38.258Z] [get_env_variable] failed to get environment variables : 'CI_LOG_PATH', use default path : /tmp/ci_logs

[2023-05-07T09:41:38.258Z] [2023-05-07 09:35:38 - INFO - ci_test]: collection name: deploy_test_index_type_HNSW_is_compacted_not_compacted_segment_status_all_is_string_indexed_is_string_indexed_replica_number_2_is_deleted_is_deleted_data_size_3000 (test_action_first_deployment.py:81)

[2023-05-07T09:41:38.258Z] [2023-05-07 09:35:38 - DEBUG - ci_test]: (api_request)  : [Connections.connect] args: ['default'], kwargs: {'host': '10.101.91.157', 'port': 19530} (api_request.py:56)

[2023-05-07T09:41:38.258Z] [2023-05-07 09:35:38 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)

[2023-05-07T09:41:38.258Z] [2023-05-07 09:35:39 - INFO - ci_test]: collection name: deploy_test_index_type_HNSW_is_compacted_not_compacted_segment_status_all_is_string_indexed_is_string_indexed_replica_number_2_is_deleted_is_deleted_data_size_3000, replica_number: 2, is_compacted: not_compacted,is_deleted: is_deleted, is_string_indexed: is_string_indexed,segment_status: all, index_type: HNSW (test_action_first_deployment.py:89)

[2023-05-07T09:41:38.258Z] [2023-05-07 09:35:39 - INFO - ci_test]: Test case of search interface: initialize before test case (client_base.py:197)

[2023-05-07T09:41:38.258Z] [2023-05-07 09:35:39 - DEBUG - ci_test]: (api_request)  : [Connections.connect] args: ['default'], kwargs: {'host': '10.101.91.157', 'port': 19530} (api_request.py:56)

[2023-05-07T09:41:38.258Z] [2023-05-07 09:35:39 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)

[2023-05-07T09:41:38.258Z] [2023-05-07 09:35:39 - DEBUG - ci_test]: (api_request)  : [FieldSchema] args: ['int64', <DataType.INT64: 5>, ''], kwargs: {'is_primary': False} (api_request.py:56)

[2023-05-07T09:41:38.258Z] [2023-05-07 09:35:39 - DEBUG - ci_test]: (api_response) : {

[2023-05-07T09:41:38.258Z]     name: int64

[2023-05-07T09:41:38.258Z]     description: 

[2023-05-07T09:41:38.258Z]     type: 5

[2023-05-07T09:41:38.258Z]   }  (api_request.py:31)

[2023-05-07T09:41:38.258Z] [2023-05-07 09:35:39 - DEBUG - ci_test]: (api_request)  : [FieldSchema] args: ['float', <DataType.FLOAT: 10>, ''], kwargs: {'is_primary': False} (api_request.py:56)

[2023-05-07T09:41:38.258Z] [2023-05-07 09:35:39 - DEBUG - ci_test]: (api_response) : {

[2023-05-07T09:41:38.258Z]     name: float

[2023-05-07T09:41:38.258Z]     description: 

[2023-05-07T09:41:38.258Z]     type: 10

[2023-05-07T09:41:38.258Z]   }  (api_request.py:31)

[2023-05-07T09:41:38.258Z] [2023-05-07 09:35:39 - DEBUG - ci_test]: (api_request)  : [FieldSchema] args: ['varchar', <DataType.VARCHAR: 21>, ''], kwargs: {'max_length': 65535, 'is_primary': False} (api_request.py:56)

[2023-05-07T09:41:38.258Z] [2023-05-07 09:35:39 - DEBUG - ci_test]: (api_response) : {

[2023-05-07T09:41:38.258Z]     name: varchar

[2023-05-07T09:41:38.258Z]     description: 

[2023-05-07T09:41:38.258Z]     type: 21

[2023-05-07T09:41:38.258Z]     params: {'max_length': 65535}

[2023-05-07T09:41:38.258Z]   }  (api_request.py:31)

[2023-05-07T09:41:38.258Z] [2023-05-07 09:35:39 - DEBUG - ci_test]: (api_request)  : [FieldSchema] args: ['float_vector', <DataType.FLOAT_VECTOR: 101>, ''], kwargs: {'dim': 128, 'is_primary': False} (api_request.py:56)

[2023-05-07T09:41:38.258Z] [2023-05-07 09:35:39 - DEBUG - ci_test]: (api_response) : {

[2023-05-07T09:41:38.258Z]     name: float_vector

[2023-05-07T09:41:38.258Z]     description: 

[2023-05-07T09:41:38.258Z]     type: 101

[2023-05-07T09:41:38.258Z]     params: {'dim': 128}

[2023-05-07T09:41:38.258Z]   }  (api_request.py:31)

[2023-05-07T09:41:38.258Z] [2023-05-07 09:35:39 - DEBUG - ci_test]: (api_request)  : [CollectionSchema] args: [[{

[2023-05-07T09:41:38.258Z]     name: int64

[2023-05-07T09:41:38.258Z]     description: 

[2023-05-07T09:41:38.258Z]     type: 5

[2023-05-07T09:41:38.258Z]   }, {

[2023-05-07T09:41:38.258Z]     name: float

[2023-05-07T09:41:38.258Z]     description: 

[2023-05-07T09:41:38.258Z]     type: 10

[2023-05-07T09:41:38.258Z]   }, {

[2023-05-07T09:41:38.258Z]     name: varchar

[2023-05-07T09:41:38.258Z]     description: 

[2023-05-07T09:41:38.258Z]     type: 21

[2023-05-07T09:41:38.258Z]     params: {'max_length': 65535}

[2023-05-07T09:41:38.258Z]   }, {

[2023-05-07T09:41:38.258Z]     name: float_vector

[2023-05-07T09:41:38.258Z]     description: 

[2023-05-07T09:41:38.258Z]     type: 101

[2023-05-07T09:41:38.258Z]     params: {'dim': 128}

[2023-05-07T09:41:38.258Z]   }], ''], kwargs: {'primary_field': 'int64', 'auto_id': False} (api_request.py:56)

[2023-05-07T09:41:38.258Z] [2023-05-07 09:35:39 - DEBUG - ci_test]: (api_response) : {

[2023-05-07T09:41:38.258Z]   auto_id: False

[2023-05-07T09:41:38.258Z]   description: 

[2023-05-07T09:41:38.258Z]   fields: [{

[2023-05-07T09:41:38.258Z]     name: int64

[2023-05-07T09:41:38.258Z]     description: 

[2023-05-07T09:41:38.258Z]     type: 5

[2023-05-07T09:41:38.258Z]     is_primary: True

[2023-05-07T09:41:38.259Z]     auto_id: False

[2023-05-07T09:41:38.259Z]   }, {

[2023-05-07T09:41:38.259Z]     name: float

[2023-05-07T09:41:38.259Z]     description: 

[2023-05-07T09:41:38.259Z]     type: 10

[2023-05-07T09:41:38.259Z]   }, {

[2023-05-07T09:41:38.259Z]     name: varchar

[2023-05-07T09:41:38.259Z]     description: 

[2023-05-07T09:41:38.259Z]     type: 21

[2023-05-07T09:41:38.259Z]     params: {'max_length': 65535}

[2023-05-07T09:41:38.259Z]   }, {

[2023-05-07T09:41:38.259Z]     name: float......  (api_request.py:31)

[2023-05-07T09:41:38.259Z] [2023-05-07 09:35:39 - INFO - ci_test]: init_collection_general: collection creation (client_base.py:214)

[2023-05-07T09:41:38.259Z] [2023-05-07 09:35:39 - DEBUG - ci_test]: (api_request)  : [Connections.has_connection] args: ['default'], kwargs: {} (api_request.py:56)

[2023-05-07T09:41:38.259Z] [2023-05-07 09:35:39 - DEBUG - ci_test]: (api_response) : True  (api_request.py:31)

[2023-05-07T09:41:38.259Z] [2023-05-07 09:35:39 - DEBUG - ci_test]: (api_request)  : [Collection] args: ['deploy_test_index_type_HNSW_is_compacted_not_compacted_segment_status_all_is_string_indexed_is_string_indexed_replica_number_2_is_deleted_is_deleted_data_size_3000', {

[2023-05-07T09:41:38.259Z]   auto_id: False

[2023-05-07T09:41:38.259Z]   description: 

[2023-05-07T09:41:38.259Z]   fields: [{

[2023-05-07T09:41:38.259Z]     name: int64

[2023-05-07T09:41:38.259Z]     description: 

[2023-05-07T09:41:38.259Z]     type: 5

[2023-05-07T09:41:38.259Z]     is_primary: True

[2023-05-07T09:41:38.259Z]     auto_id: Fals......, kwargs: {'shards_num': 2, 'consistency_level': 'Strong'} (api_request.py:56)

[2023-05-07T09:41:38.259Z] [2023-05-07 09:35:49 - ERROR - pymilvus.decorators]: RPC error: [create_collection], <MilvusException: (code=1, message=failed to watch channels, code: UnexpectedError, reason: context deadline exceeded)>, <Time:{'RPC start': '2023-05-07 09:35:39.131424', 'RPC error': '2023-05-07 09:35:49.207701'}> (decorators.py:108)

[2023-05-07T09:41:38.259Z] [2023-05-07 09:35:49 - ERROR - ci_test]: Traceback (most recent call last):

[2023-05-07T09:41:38.259Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2023-05-07T09:41:38.259Z]     res = func(*args, **_kwargs)

[2023-05-07T09:41:38.259Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2023-05-07T09:41:38.259Z]     return func(*arg, **kwargs)

[2023-05-07T09:41:38.259Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 120, in __init__

[2023-05-07T09:41:38.259Z]     conn.create_collection(self._name, schema, **kwargs)

[2023-05-07T09:41:38.259Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-05-07T09:41:38.259Z]     raise e

[2023-05-07T09:41:38.259Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-05-07T09:41:38.259Z]     return func(*args, **kwargs)

[2023-05-07T09:41:38.259Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-05-07T09:41:38.259Z]     ret = func(self, *args, **kwargs)

[2023-05-07T09:41:38.259Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-05-07T09:41:38.259Z]     raise e

[2023-05-07T09:41:38.259Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-05-07T09:41:38.259Z]     return func(self, *args, **kwargs)

[2023-05-07T09:41:38.259Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 216, in create_collection

[2023-05-07T09:41:38.259Z]     raise MilvusException(status.error_code, status.reason)

[2023-05-07T09:41:38.259Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=failed to watch channels, code: UnexpectedError, reason: context deadline exceeded)>

[2023-05-07T09:41:38.259Z]  (api_request.py:39)

[2023-05-07T09:41:38.259Z] [2023-05-07 09:35:49 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=failed to watch channels, code: UnexpectedError, reason: context deadline exceeded)> (api_request.py:40)
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_cron/detail/deploy_test_cron/737/pipeline
log:
[artifacts-pulsar-cluster-reinstall-737-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/11417421/artifacts-pulsar-cluster-reinstall-737-server-logs.1.tar.gz)

[artifacts-pulsar-cluster-reinstall-737-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/11417422/artifacts-pulsar-cluster-reinstall-737-pytest-logs.tar.gz)

### Anything else?

It failed at the first stage
![image](https://user-images.githubusercontent.com/12268675/236727298-cdb5d1ed-c756-4ef7-b2e3-2da230dbbbae.png)

**Comment by sunby** [comment]
Saving to etcd spent most time and leads to timeout. It may be caused by network lag or etcd cluster issue.

**Comment by sunby** [comment]
I can only find the apply time from log, and maybe we should enable tracing for milvus and etcd to get more detailed information.
BTW, I test the etcd tracing and it only can be enabled from 3.6.0-alpha0. I think we can use it after the stable 3.6 version is released.
