### ISSUE TITLE
[Bug]: [Nightly]Load collection occasionally failed for 'service not ready'

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#23934]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:dcf55e7
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):2.4.0.dev23
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Load collection occasionally failed for 'service not ready'.
```
[2023-05-07T19:24:04.774Z] [2023-05-07 18:44:53 - ERROR - pymilvus.decorators]: RPC error: [get_loading_progress], <MilvusException: (code=56, message=stage=Initializing: service not ready)>, <Time:{'RPC start': '2023-05-07 18:44:47.700748', 'RPC error': '2023-05-07 18:44:53.604482'}> (decorators.py:108)
[2023-05-07T19:24:04.774Z] [2023-05-07 18:44:53 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=56, message=stage=Initializing: service not ready)>, <Time:{'RPC start': '2023-05-07 18:44:43.684870', 'RPC error': '2023-05-07 18:44:53.604698'}> (decorators.py:108)
[2023-05-07T19:24:04.774Z] [2023-05-07 18:44:53 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=56, message=stage=Initializing: service not ready)>, <Time:{'RPC start': '2023-05-07 18:44:43.673576', 'RPC error': '2023-05-07 18:44:53.604799'}> (decorators.py:108)
[2023-05-07T19:24:04.774Z] [2023-05-07 18:44:53 - ERROR - ci_test]: Traceback (most recent call last):
[2023-05-07T19:24:04.774Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2023-05-07T19:24:04.774Z]     res = func(*args, **_kwargs)
[2023-05-07T19:24:04.774Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2023-05-07T19:24:04.774Z]     return func(*arg, **kwargs)
[2023-05-07T19:24:04.774Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 372, in load
[2023-05-07T19:24:04.774Z]     conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
[2023-05-07T19:24:04.774Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2023-05-07T19:24:04.774Z]     raise e
[2023-05-07T19:24:04.774Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2023-05-07T19:24:04.774Z]     return func(*args, **kwargs)
[2023-05-07T19:24:04.774Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2023-05-07T19:24:04.774Z]     ret = func(self, *args, **kwargs)
[2023-05-07T19:24:04.774Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
[2023-05-07T19:24:04.774Z]     raise e
[2023-05-07T19:24:04.774Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2023-05-07T19:24:04.775Z]     return func(self, *args, **kwargs)
[2023-05-07T19:24:04.775Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 714, in load_collection
[2023-05-07T19:24:04.775Z]     self.wait_for_loading_collection(collection_name, timeout)
[2023-05-07T19:24:04.775Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2023-05-07T19:24:04.775Z]     raise e
[2023-05-07T19:24:04.775Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2023-05-07T19:24:04.775Z]     return func(*args, **kwargs)
[2023-05-07T19:24:04.775Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2023-05-07T19:24:04.775Z]     ret = func(self, *args, **kwargs)
[2023-05-07T19:24:04.775Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
[2023-05-07T19:24:04.775Z]     raise e
[2023-05-07T19:24:04.775Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2023-05-07T19:24:04.775Z]     return func(self, *args, **kwargs)
[2023-05-07T19:24:04.775Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 732, in wait_for_loading_collection
[2023-05-07T19:24:04.775Z]     progress = self.get_loading_progress(collection_name, timeout=timeout)
[2023-05-07T19:24:04.775Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2023-05-07T19:24:04.775Z]     raise e
[2023-05-07T19:24:04.775Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2023-05-07T19:24:04.775Z]     return func(*args, **kwargs)
[2023-05-07T19:24:04.775Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2023-05-07T19:24:04.775Z]     ret = func(self, *args, **kwargs)
[2023-05-07T19:24:04.775Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
[2023-05-07T19:24:04.775Z]     raise e
[2023-05-07T19:24:04.775Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2023-05-07T19:24:04.775Z]     return func(self, *args, **kwargs)
[2023-05-07T19:24:04.775Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 799, in get_loading_progress
[2023-05-07T19:24:04.775Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2023-05-07T19:24:04.775Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=56, message=stage=Initializing: service not ready)>
[2023-05-07T19:24:04.775Z]  (api_request.py:39)
[2023-05-07T19:24:04.775Z] [2023-05-07 18:44:53 - ERROR - ci_test]: (api_response) : <MilvusException: (code=56, message=stage=Initializing: service not ready)> (api_request.py:40)
```

### Expected Behavior

pass

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/365/pipeline/187
2. log: [artifacts-milvus-distributed-pulsar-nightly-365-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/365/artifact/artifacts-milvus-distributed-pulsar-nightly-365-pymilvus-e2e-logs.tar.gz)
3. collection name: search_collection_I69jLTdT
4. failed timeline: [2023-05-07T18:44:55.428Z] [gw2] [ 60%] FAILED testcases/test_search.py::TestSearchBase::test_search_ip_flat[10]

**Comment by NicoYuan1986** [comment]
Start time:
```
[2023-05-07T18:44:55.428Z] [gw2] [ 60%] FAILED testcases/test_search.py::TestSearchBase::test_search_ip_flat[10] 
[2023-05-07T18:44:55.428Z] testcases/test_search.py::TestSearchBase::test_search_ip_after_index[FLAT-params0] 
[2023-05-07T18:44:55.428Z] [gw4] [ 60%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_expression_all_data_type[5000-2-32-True-True] 
[2023-05-07T18:44:55.428Z] testcases/test_search.py::TestCollectionSearch::test_search_expression_all_data_type[5000-2-128-False-False] 
[2023-05-07T18:44:55.428Z] [gw1] [ 60%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_index_partitions[5000-500-128-True-False] 
[2023-05-07T18:44:55.684Z] testcases/test_search.py::TestCollectionSearch::test_search_index_partitions[5000-500-128-True-True] 
[2023-05-07T18:44:55.686Z] [gw0] [ 60%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_with_consistency_strong[500-128-False-False] 
[2023-05-07T18:44:55.686Z] [gw1] [ 60%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_index_partitions[5000-500-128-True-True] 
[2023-05-07T18:44:55.686Z] testcases/test_search.py::TestCollectionSearch::test_search_with_consistency_strong[500-128-False-True] 
[2023-05-07T18:44:55.942Z] testcases/test_search.py::TestCollectionSearch::test_search_index_partitions_fuzzy[3000-2-32-False-False-partition_names0] 
[2023-05-07T18:44:55.942Z] [gw5] [ 60%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_multi_collections[3000-2-32-True-True] 
[2023-05-07T18:44:56.197Z] testcases/test_search.py::TestCollectionSearch::test_search_multi_collections[3000-2-128-False-False] 
[2023-05-07T18:44:56.197Z] [gw1] [ 60%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_index_partitions_fuzzy[3000-2-32-False-False-partition_names0] 
[2023-05-07T18:44:56.452Z] testcases/test_search.py::TestCollectionSearch::test_search_index_partitions_fuzzy[3000-2-32-False-False-partition_names1] 
[2023-05-07T18:44:56.453Z] [gw1] [ 60%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_index_partitions_fuzzy[3000-2-32-False-False-partition_names1] 
[2023-05-07T18:44:57.013Z] testcases/test_search.py::TestCollectionSearch::test_search_index_partitions_fuzzy[3000-2-32-False-True-partition_names0] 
[2023-05-07T18:44:57.013Z] [gw1] [ 60%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_index_partitions_fuzzy[3000-2-32-False-True-partition_names0] 
[2023-05-07T18:44:57.268Z] testcases/test_search.py::TestCollectionSearch::test_search_index_partitions_fuzzy[3000-2-32-False-True-partition_names1] 
[2023-05-07T18:44:57.524Z] [gw1] [ 60%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_index_partitions_fuzzy[3000-2-32-False-True-partition_names1] 
[2023-05-07T18:44:57.524Z] testcases/test_search.py::TestCollectionSearch::test_search_index_partitions_fuzzy[3000-2-32-True-False-partition_names0] 
[2023-05-07T18:44:57.524Z] [gw1] [ 60%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_index_partitions_fuzzy[3000-2-32-True-False-partition_names0] 
[2023-05-07T18:44:58.084Z] testcases/test_search.py::TestCollectionSearch::test_search_index_partitions_fuzzy[3000-2-32-True-False-partition_names1] 
[2023-05-07T18:44:58.084Z] [gw1] [ 60%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_index_partitions_fuzzy[3000-2-32-True-False-partition_names1] 
[2023-05-07T18:44:58.340Z] testcases/test_search.py::TestCollectionSearch::test_search_index_partitions_fuzzy[3000-2-32-True-True-partition_names0] 
[2023-05-07T18:44:58.341Z] [gw1] [ 60%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_index_partitions_fuzzy[3000-2-32-True-True-partition_names0] 
[2023-05-07T18:44:58.341Z] [gw2] [ 60%] FAILED testcases/test_search.py::TestSearchBase::test_search_ip_after_index[FLAT-params0] 
```

milvus log:
```
2023-05-08T03:12:11.549908804+08:00 stderr F panic: runtime error: invalid memory address or nil pointer dereference
2023-05-08T03:12:11.5499419+08:00 stderr F [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2cc5d73]
2023-05-08T03:12:11.549946895+08:00 stderr F
2023-05-08T03:12:11.549952332+08:00 stderr F goroutine 782 [running]:
2023-05-08T03:12:11.549956445+08:00 stderr F panic({0x33a5b40, 0x4f88020})
2023-05-08T03:12:11.549970535+08:00 stderr F    /usr/local/go/src/runtime/panic.go:941 +0x397 fp=0xc0010cfa68 sp=0xc0010cf9a8 pc=0x12873f7
2023-05-08T03:12:11.549974255+08:00 stderr F runtime.panicmem(...)
2023-05-08T03:12:11.549977933+08:00 stderr F    /usr/local/go/src/runtime/panic.go:220
2023-05-08T03:12:11.549981591+08:00 stderr F runtime.sigpanic()
2023-05-08T03:12:11.54999434+08:00 stderr F     /usr/local/go/src/runtime/signal_unix.go:818 +0x336 fp=0xc0010cfab8 sp=0xc0010cfa68 pc=0x129e416
2023-05-08T03:12:11.550000225+08:00 stderr F github.com/milvus-io/milvus/internal/querycoordv2/checkers.(*BalanceChecker).replicasToBalance.func1(0x0?, 0x0?)
2023-05-08T03:12:11.550004094+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/querycoordv2/checkers/balance_checker.go:67 +0x53 fp=0xc0010cfae8 sp=0xc0010cfab8 pc=0x2cc5d73
2023-05-08T03:12:11.550012743+08:00 stderr F github.com/samber/lo.Filter[...]({0xc0020fdda0?, 0xc, 0x8}, 0xc0010cfcc8?)
2023-05-08T03:12:11.550016757+08:00 stderr F    /go/pkg/mod/github.com/samber/lo@v1.27.0/slice.go:14 +0x9f fp=0xc0010cfb60 sp=0xc0010cfae8 pc=0x270c75f
2023-05-08T03:12:11.550020894+08:00 stderr F github.com/milvus-io/milvus/internal/querycoordv2/checkers.(*BalanceChecker).replicasToBalance(0xc000d0cf00)
2023-05-08T03:12:11.550032287+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/querycoordv2/checkers/balance_checker.go:65 +0x8a fp=0xc0010cfda8 sp=0xc0010cfb60 pc=0x2cc542a
2023-05-08T03:12:11.550058487+08:00 stderr F github.com/milvus-io/milvus/internal/querycoordv2/checkers.(*BalanceChecker).Check(0xc000d0cf00, {0x3bb2e50, 0xc00012ab40})
2023-05-08T03:12:11.550092496+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/querycoordv2/checkers/balance_checker.go:143 +0x65 fp=0xc0010cfe78 sp=0xc0010cfda8 pc=0x2cc61e5
2023-05-08T03:12:11.550102911+08:00 stderr F github.com/milvus-io/milvus/internal/querycoordv2/checkers.(*CheckerController).check(0xc000d08c80, {0x3bb2e50, 0xc00012ab40})
2023-05-08T03:12:11.550110558+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/querycoordv2/checkers/controller.go:122 +0x166 fp=0xc0010cff10 sp=0xc0010cfe78 pc=0x2cc8da6
```

**Comment by yanliang567** [comment]
sounds like a crash during test running.
/assign @jiaoew1991 
/unassign

**Comment by NicoYuan1986** [comment]
Fixed.
