### ISSUE TITLE
[Bug]: Query failed after release collection then delete data 

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#23989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230508-ed81eaa9
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0.dev23
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Query failed after release collection then delete data.
```
[2023-05-09 18:01:10 - ERROR - pymilvus.decorators]: RPC error: [query], <MilvusException: (code=1, message=fail to query on all shard leaders, err=fail to Query, QueryNode ID = 3, reason=failed to query channel, err=worker(3) query failed: failed to query channel, err=segment 441352323451727459 belongs to partition 441352323451727437, which is not in [441352323451727431])>, <Time:{'RPC start': '2023-05-09 18:01:10.325422', 'RPC error': '2023-05-09 18:01:10.485544'}> (decorators.py:108)
[2023-05-09 18:01:10 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/zilliz/nico/milvus/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/Users/zilliz/nico/milvus/tests/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/orm/collection.py", line 750, in query
    res = conn.query(self._name, expr, output_fields, partition_names,
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 953, in query
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to query on all shard leaders, err=fail to Query, QueryNode ID = 3, reason=failed to query channel, err=worker(3) query failed: failed to query channel, err=segment 441352323451727459 belongs to partition 441352323451727437, which is not in [441352323451727431])>
 (api_request.py:39)
[2023-05-09 18:01:10 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to query on all shard leaders, err=fail to Query, QueryNode ID = 3, reason=failed to query channel, err=worker(3) query failed: failed to query channel, err=segment 441352323451727459 belongs to partition 441352323451727437, which is not in [441352323451727431...... (api_request.py:40)
```

### Expected Behavior

return data

### Steps To Reproduce

```markdown
1. create a collection and 2 partitions
2. insert data
3. load one partition
4. release the collection
5. delete half data in each partition
6. query on the collection -> len(res)==100 -> ❌
```

### Milvus Log

```python
@pytest.mark.tags(CaseLabel.L2)
def test_load_partition_release_collection_delete(self):
    """
    target: test delete load collection release partition
    method: 1. create a collection and 2 partitions
            2. insert data
            3. load one partition
            4. release the collection
            5. delete half data in each partition
            6. query on the collection -> len(res)==100
    expected: No exception
    """
    # insert data
    collection_w = self.init_collection_general(prefix, partition_num=1)[0]
    partition_w1, partition_w2 = collection_w.partitions
    df = cf.gen_default_dataframe_data(200)
    partition_w1.insert(df[:100])
    partition_w2.insert(df[100:])
    # load && release
    partition_w1.load()
    collection_w.release()
    # delete data
    delete_ids = [i for i in range(50, 150)]
    collection_w.delete(f"int64 in {delete_ids}")
    collection_w.load()
    res = collection_w.query(default_search_exp)[0]
    assert len(res) == 100
```

**Comment by NicoYuan1986** [comment]
Same:
```python
@pytest.mark.tags(CaseLabel.L2)
def test_load_partition_drop_partition_delete(self):
    """
    target: test delete load collection release partition
    method: 1. create a collection and 2 partitions
            2. insert data
            3. load one partition
            4. release and drop the partition
            5. delete half data in each partition
            6. query on the collection -> len(res)==50
    expected: No exception
    """
    # insert data
    collection_w = self.init_collection_general(prefix, partition_num=1)[0]
    partition_w1, partition_w2 = collection_w.partitions
    df = cf.gen_default_dataframe_data(200)
    partition_w1.insert(df[:100])
    partition_w2.insert(df[100:])
    # load && release
    partition_w2.load()
    partition_w2.release()
    partition_w2.drop()
    # delete data
    delete_ids = [i for i in range(50, 150)]
    collection_w.delete(f"int64 in {delete_ids}")
    # query
    collection_w.load()
    res = collection_w.query(default_search_exp)[0]
    assert len(res) == 50
```
error message:
```
[2023-05-09 18:43:40 - ERROR - pymilvus.decorators]: RPC error: [query], <MilvusException: (code=1, message=fail to query on all shard leaders, err=fail to Query, QueryNode ID = 3, reason=failed to query channel, err=worker(3) query failed: failed to query channel, err=segment 441352323451740960 belongs to partition 441352323451740923, which is not in [441352323451740939])>, <Time:{'RPC start': '2023-05-09 18:43:40.347090', 'RPC error': '2023-05-09 18:43:40.613073'}> (decorators.py:108)
[2023-05-09 18:43:40 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/zilliz/nico/milvus/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/Users/zilliz/nico/milvus/tests/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/orm/collection.py", line 750, in query
    res = conn.query(self._name, expr, output_fields, partition_names,
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 953, in query
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to query on all shard leaders, err=fail to Query, QueryNode ID = 3, reason=failed to query channel, err=worker(3) query failed: failed to query channel, err=segment 441352323451740960 belongs to partition 441352323451740923, which is not in [441352323451740939])>
 (api_request.py:39)
[2023-05-09 18:43:40 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to query on all shard leaders, err=fail to Query, QueryNode ID = 3, reason=failed to query channel, err=worker(3) query failed: failed to query channel, err=segment 441352323451740960 belongs to partition 441352323451740923, which is not in [441352323451740939...... (api_request.py:40)
```

**Comment by xiaofan-luan** [comment]
interesting test case

**Comment by NicoYuan1986** [comment]
Verify fixed.
