### ISSUE TITLE
[Bug]: [Nightly]load collection or partition failed with error `collection not loaded`

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#23998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:893e31d
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):2.4.0.dev24
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

load collection or partition failed with error `collection not loaded`.

Take one case for example:
```
[2023-05-09T19:26:59.784Z] [2023-05-09 17:59:32 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=failed to load collection, err=QueryNode failed to loadPartition, nodeID=4, err=failed to load partitions: collection=441360048330131918: collection not loaded)>, <Time:{'RPC start': '2023-05-09 17:59:32.570458', 'RPC error': '2023-05-09 17:59:32.574407'}> (decorators.py:108)
[2023-05-09T19:26:59.784Z] [2023-05-09 17:59:32 - ERROR - ci_test]: Traceback (most recent call last):
[2023-05-09T19:26:59.784Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2023-05-09T19:26:59.784Z]     res = func(*args, **_kwargs)
[2023-05-09T19:26:59.784Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2023-05-09T19:26:59.784Z]     return func(*arg, **kwargs)
[2023-05-09T19:26:59.784Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 372, in load
[2023-05-09T19:26:59.784Z]     conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
[2023-05-09T19:26:59.784Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2023-05-09T19:26:59.784Z]     raise e
[2023-05-09T19:26:59.784Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2023-05-09T19:26:59.784Z]     return func(*args, **kwargs)
[2023-05-09T19:26:59.784Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2023-05-09T19:26:59.784Z]     ret = func(self, *args, **kwargs)
[2023-05-09T19:26:59.784Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
[2023-05-09T19:26:59.784Z]     raise e
[2023-05-09T19:26:59.784Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2023-05-09T19:26:59.784Z]     return func(self, *args, **kwargs)
[2023-05-09T19:26:59.784Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 708, in load_collection
[2023-05-09T19:26:59.784Z]     raise MilvusException(response.error_code, response.reason)
[2023-05-09T19:26:59.784Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=failed to load collection, err=QueryNode failed to loadPartition, nodeID=4, err=failed to load partitions: collection=441360048330131918: collection not loaded)>
[2023-05-09T19:26:59.784Z]  (api_request.py:39)
[2023-05-09T19:26:59.784Z] [2023-05-09 17:59:32 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=failed to load collection, err=QueryNode failed to loadPartition, nodeID=4, err=failed to load partitions: collection=441360048330131918: collection not loaded)> (api_request.py:40)
```

### Expected Behavior

load successfully

### Steps To Reproduce

```markdown
[2023-05-09T19:26:59.783Z] _______ TestLoadCollection.test_load_collection_after_drop_one_partition _______
[2023-05-09T19:26:59.783Z] [gw4] linux -- Python 3.8.16 /usr/local/bin/python3
[2023-05-09T19:26:59.783Z] 
[2023-05-09T19:26:59.783Z] self = <test_collection.TestLoadCollection object at 0x7f10de8eacd0>
[2023-05-09T19:26:59.783Z] 
[2023-05-09T19:26:59.783Z]     @pytest.mark.tags(CaseLabel.L2)
[2023-05-09T19:26:59.783Z]     def test_load_collection_after_drop_one_partition(self):
[2023-05-09T19:26:59.783Z]         """
[2023-05-09T19:26:59.783Z]         target: test load collection after drop a partition
[2023-05-09T19:26:59.783Z]         method: 1. load collection
[2023-05-09T19:26:59.783Z]                 2. drop a partition
[2023-05-09T19:26:59.783Z]                 3. load collection
[2023-05-09T19:26:59.783Z]                 4. query on the partition
[2023-05-09T19:26:59.783Z]         expected: No exception
[2023-05-09T19:26:59.783Z]         """
[2023-05-09T19:26:59.783Z]         collection_w = self.init_collection_general(prefix)[0]
[2023-05-09T19:26:59.783Z]         partition_w1 = self.init_partition_wrap(collection_w, partition1)
[2023-05-09T19:26:59.783Z]         partition_w2 = self.init_partition_wrap(collection_w, partition2)
[2023-05-09T19:26:59.783Z]         collection_w.load()
[2023-05-09T19:26:59.783Z]         partition_w1.release()
[2023-05-09T19:26:59.783Z]         partition_w1.drop()
[2023-05-09T19:26:59.783Z] >       collection_w.load()
```

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/367/pipeline/136
2. log: [artifacts-milvus-distributed-kafka-nightly-367-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/367/artifact/artifacts-milvus-distributed-kafka-nightly-367-pymilvus-e2e-logs.tar.gz)
3. collection name: collection_j3PfSMfZ
4. failed time: [2023-05-09T17:59:32.999Z] [gw4] [  6%] FAILED testcases/test_collection.py::TestLoadCollection::test_load_collection_after_drop_one_partition 
5. all failed cases:
```
test_load_collection_after_drop_one_partition 
test_load_partitions_after_release_collection_partition 
test_load_partitions_after_release_partitions 
test_load_partitions_after_release_partition 
test_load_collection_after_release_partitions 
test_load_partition_after_drop_partition_and_release_another 
test_load_collection_after_load_one_partition  
test_load_collection_after_load_loaded_partition  
test_load_collection_after_load_unloaded_partition  
test_load_partitions_after_load_release_partition  
test_load_partitions_after_load_partition_release_partitions  
test_load_partitions_release_collection  
test_load_partiton_respectively
```

**Comment by NicoYuan1986** [comment]
Verify fixed.
