### ISSUE TITLE
[Bug]: Returns `not found the user` exception when role removes an already deleted user

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#24019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: PR-23742-20230505-3a859f674
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.2.9.dev3
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. connect with root user, pwd
2. create a user
3. create a role and bind the user
4. delete the user
5. role.get_users also return the deleted user
6. role.revoke_user return exception
```
[2023-05-10 18:38:51,599 - ERROR - ci_test]: (api_response) : <MilvusException: (code=37, message=not found the user, maybe the user isn't existed or internal system error)> (api_request.py:40)
```

### Expected Behavior

Deleted users do not appear in the get_users and list_roles bound by role
or be able to revoke successfully

### Steps To Reproduce

```markdown
def test_revoke_user_after_delete_user(self, host, port):
        """
        target: test revoke user with deleted user
        method: 1. create user -> create a role -> role add user
                2. delete user
                3. revoke the deleted user
        expected: revoke successfully
        """
        # root connect
        self.connection_wrap.connect(host=host, port=port, user=ct.default_user,
                                     password=ct.default_password, check_task=ct.CheckTasks.ccr)

        # create user
        user_name = cf.gen_unique_str("user")
        u, _ = self.utility_wrap.create_user(user=user_name, password=ct.default_password)

        # create a role and bind user
        role_name = cf.gen_unique_str("role")
        self.utility_wrap.init_role(role_name)
        self.utility_wrap.create_role()
        self.utility_wrap.role_add_user(user_name)

        # delete user
        self.utility_wrap.delete_user(user_name)

        # remove user successfully
        self.utility_wrap.role_remove_user(user_name)

        # get role users and verify user removed
        role_users, _ = self.utility_wrap.role_get_users()
        assert user_name not in role_users
```
```


### Milvus Log

```
[2023-05-10 18:38:51,461 - INFO - ci_test]: [setup_method] Start setup test case test_revoke_user_after_delete_user. (client_base.py:43)
[2023-05-10 18:38:51,461 - DEBUG - ci_test]: (api_request)  : [Connections.connect] args: ['default', 'root', 'Milvus', ''], kwargs: {'host': '10.101.55.211', 'port': 19530} (api_request.py:56)
[2023-05-10 18:38:51,497 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)
[2023-05-10 18:38:51,498 - DEBUG - ci_test]: (api_request)  : [create_user] args: ['user_CpPfZTqN', 'Milvus', 'default'], kwargs: {} (api_request.py:56)
[2023-05-10 18:38:51,518 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)
[2023-05-10 18:38:51,518 - DEBUG - ci_test]: (api_request)  : [Role] args: ['role_K2UXS5I0', 'default'], kwargs: {} (api_request.py:56)
[2023-05-10 18:38:51,518 - DEBUG - ci_test]: (api_response) : <pymilvus.orm.role.Role object at 0x7fde61212fa0>  (api_request.py:31)
[2023-05-10 18:38:51,519 - DEBUG - ci_test]: (api_request)  : [Role.create] args: [], kwargs: {} (api_request.py:56)
[2023-05-10 18:38:51,535 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)
[2023-05-10 18:38:51,535 - DEBUG - ci_test]: (api_request)  : [Role.add_user] args: ['user_CpPfZTqN'], kwargs: {} (api_request.py:56)
[2023-05-10 18:38:51,560 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)
[2023-05-10 18:38:51,560 - DEBUG - ci_test]: (api_request)  : [delete_user] args: ['user_CpPfZTqN', 'default'], kwargs: {} (api_request.py:56)
[2023-05-10 18:38:51,575 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)
[2023-05-10 18:38:51,575 - DEBUG - ci_test]: (api_request)  : [Role.remove_user] args: ['user_CpPfZTqN'], kwargs: {} (api_request.py:56)
[2023-05-10 18:38:51,598 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/nausicca/projects/milvus/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/Users/nausicca/projects/milvus/tests/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/orm/role.py", line 95, in remove_user
    return self._get_connection().remove_user_from_role(username, self._name)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 1179, in remove_user_from_role
    raise MilvusException(resp.error_code, resp.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=37, message=not found the user, maybe the user isn't existed or internal system error)>
 (api_request.py:39)
[2023-05-10 18:38:51,599 - ERROR - ci_test]: (api_response) : <MilvusException: (code=37, message=not found the user, maybe the user isn't existed or internal system error)> (api_request.py:40)
FAILED
```

### Anything else?

_No response_

**Comment by ThreadDao** [comment]
fixed
