### ISSUE TITLE
[Bug]: The error message is not appropriate when query on a partly loaded collection 

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#24039]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230511-5819e98e
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0.dev25
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The error message is not appropriate when query on a partly loaded collection.
```
>>> res = collection.query('int64 >= 0')
RPC error: [query], <MilvusException: (code=1, message=fail to query on all shard leaders, err=fail to Query, QueryNode ID = 1, reason=failed to query channel, err=worker(1) query failed: failed to query channel, err=segment 441391558909956508 belongs to partition 441391558909956500, which is not in [441391558909956489])>, <Time:{'RPC start': '2023-05-11 14:44:34.317264', 'RPC error': '2023-05-11 14:44:34.374538'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/orm/collection.py", line 750, in query
    res = conn.query(self._name, expr, output_fields, partition_names,
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 950, in query
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to query on all shard leaders, err=fail to Query, QueryNode ID = 1, reason=failed to query channel, err=worker(1) query failed: failed to query channel, err=segment 441391558909956508 belongs to partition 441391558909956500, which is not in [441391558909956489])>
```

### Expected Behavior

return a clear error message like 'partition xxx is not loaded'.

### Steps To Reproduce

```python
from pymilvus import CollectionSchema, FieldSchema, Collection, connections, DataType, Partition, utility
import numpy as np
import random
connections.connect()

# create collection
dim = 128
fields = [
    FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True, description='pk'),
    FieldSchema(name="float", dtype=DataType.FLOAT),
    FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
]
schema = CollectionSchema(fields=fields)

collection = Collection("test_load", schema=schema)
index = {"index_type": "IVF_FLAT", "params": {"nlist": 128}, "metric_type": "L2"}
collection.create_index("float_vector", index)
partition1 = collection.partitions[0]
partition2 = collection.create_partition('_default2')
# 2 partitions: _default, _default2

# insert data
nb = 100
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors], "_default")
collection.insert([[(i+1000) for i in range(nb)], [np.float32(i+1000) for i in range(nb)], vectors], "_default2")

partition1.load()
res = collection.query('int64 >= 0')
```

**Comment by NicoYuan1986** [comment]
It's valid to query/search on a partly loaded collection, so close the issue.

**Comment by NicoYuan1986** [comment]
It's valid to query/search on a partly loaded collection, so close the issue.
