### ISSUE TITLE
[Bug]: Fail to query on a collection after load one partition and drop another

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#24048]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230511-5819e98e
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0.dev25
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Fail to query on a collection after load one partition and drop another.
```
>>> res = collection.query('int64 >= 0')
RPC error: [query], <MilvusException: (code=1, message=fail to query on all shard leaders, err=fail to Query, QueryNode ID = 1, reason=failed to query channel, err=worker(1) query failed: failed to query channel, err=segment 441391558910017034 belongs to partition 441391558910017025, which is not in [441391558910017014])>, <Time:{'RPC start': '2023-05-11 17:55:24.213807', 'RPC error': '2023-05-11 17:55:24.244752'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/orm/collection.py", line 750, in query
    res = conn.query(self._name, expr, output_fields, partition_names,
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 950, in query
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to query on all shard leaders, err=fail to Query, QueryNode ID = 1, reason=failed to query channel, err=worker(1) query failed: failed to query channel, err=segment 441391558910017034 belongs to partition 441391558910017025, which is not in [441391558910017014])>

```

### Expected Behavior

search successfully

### Steps To Reproduce

```markdown
1. create a collection and 2 partitions
2. insert data
3. load one partition
4. flush
5. drop the non-loaded partition
6. search on the collection -> len(res)==100 ❌
7. search on the dropped partition -> raise error
```

### Milvus Log

```python
from pymilvus import CollectionSchema, FieldSchema, Collection, connections, DataType, Partition, utility
import numpy as np
import random
connections.connect()

# create collection
dim = 128
fields = [
    FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True, description='pk'),
    FieldSchema(name="float", dtype=DataType.FLOAT),
    FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
]
schema = CollectionSchema(fields=fields)

collection = Collection("test_load", schema=schema)
index = {"index_type": "IVF_FLAT", "params": {"nlist": 128}, "metric_type": "L2"}
collection.create_index("float_vector", index)
partition1 = collection.partitions[0]
partition2 = collection.create_partition('_default2')
# 2 partitions: _default, _default2

# insert data
nb = 100
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors], "_default")
collection.insert([[(i+1000) for i in range(nb)], [np.float32(i+1000) for i in range(nb)], vectors], "_default2")


partition1.load()
collection.flush()
partition2.drop()

# check
res = collection.query('int64 >= 0')
print(len(res))
res1 = collection.query('int64 >= 0', partition_names=[partition1.name])
res2 = collection.query('int64 >= 0', partition_names=[partition2.name])
res0 = collection.query('int64 >= 0', partition_names=[partition1.name, partition2.name])

collection.drop()

```

**Comment by NicoYuan1986** [comment]
fixed.
