### ISSUE TITLE
[Bug]: Standalone panic: implement me whne multi users connect 

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#24115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: PR-23718-20230515-5d492bc5f
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):  rocksmq 
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.2.9.dev3 
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. deploy standalone with qtp task: `1684137906204`
```
{
extraConfigFiles:{
user.yaml:"queryNode:
scheduler:
readSchedulePolicy: "user-task-polling"
"
}
standalone:{
resources:{
requests:{
memory:"6Gi"
cpu:"3"
}
limits:{
memory:"12Gi"
cpu:"3"
}
}
}
}
```
2. Start 10 clients
    each client connects with root user, then create a user and bind the user to the admin role

3. standalone panic
```
[2023/05/15 09:13:47.946 +00:00] [DEBUG] [etcd/etcd_kv.go:769] [tr/getEtcdMeta] [msg="getEtcdMeta done"] [duration=204.05µs]
[2023/05/15 09:13:47.946 +00:00] [DEBUG] [etcd/etcd_kv.go:794] [tr/putEtcdMeta] [msg="putEtcdMeta done"] [duration=305.432µs]
[2023/05/15 09:13:47.946 +00:00] [INFO] [proxy/impl.go:4755] [RefreshPrivilegeInfoCache] [req="opType:1 opKey:\"user_1_5/admin\" "]
[2023/05/15 09:13:47.946 +00:00] [INFO] [proxy/impl.go:4773] ["RefreshPrivilegeInfoCache success"]
[2023/05/15 09:13:47.946 +00:00] [DEBUG] [rootcoord/service.go:474] ["OperateUserRole-AddUserToRole success"] [role=rootcoord]
panic: implement me

goroutine 5683 [running]:
github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).ListDatabases(0x4450c58?, {0xc00ee21620?, 0x3df1f40?}, 0xc00ee21620?)
    /go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:945 +0x27
github.com/milvus-io/milvus-proto/go-api/milvuspb._MilvusService_ListDatabases_Handler.func1({0x4450c58, 0xc00ee218f0}, {0x3df1f40?, 0xc00ee21620})
    /go/pkg/mod/github.com/milvus-io/milvus-proto/go-api@v0.0.0-20230509062636-f6c495229ceb/milvuspb/milvus.pb.go:11607 +0x7b
github.com/milvus-io/milvus/internal/proxy.RateLimitInterceptor.func1({0x4450c58, 0xc00ee218f0}, {0x3df1f40, 0xc00ee21620}, 0xc005a2a5c0, 0xc005a1f2a8)
    /go/src/github.com/milvus-io/milvus/internal/proxy/rate_limit_interceptor.go:38 +0xf3
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x4450c58?, 0xc00ee218f0?}, {0x3df1f40?, 0xc00ee21620?})
    /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a
github.com/milvus-io/milvus/internal/util/logutil.UnaryTraceLoggerInterceptor({0x4450c58?, 0xc00ee21830?}, {0x3df1f40, 0xc00ee21620}, 0x4474c90?, 0xc005a2a5e0)
    /go/src/github.com/milvus-io/milvus/internal/util/logutil/grpc_interceptor.go:22 +0x49
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x4450c58?, 0xc00ee21830?}, {0x3df1f40?, 0xc00ee21620?})
    /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a
github.com/milvus-io/milvus/internal/proxy.UnaryServerInterceptor.func1({0x4450c58?, 0xc00ee21830?}, {0x3df1f40, 0xc00ee21620}, 0x0?, 0xc005a2a600)
    /go/src/github.com/milvus-io/milvus/internal/proxy/privilege_interceptor.go:60 +0x5d
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x4450c58?, 0xc00ee21830?}, {0x3df1f40?, 0xc00ee21620?})
    /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a
github.com/milvus-io/milvus/internal/proxy.UnaryServerHookInterceptor.func1({0x4450c58, 0xc00ee21830}, {0x3df1f40, 0xc00ee21620}, 0xc005a32501?, 0xc005a2a620)
    /go/src/github.com/milvus-io/milvus/internal/proxy/hook_interceptor.go:101 +0x962
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x4450c58?, 0xc00ee21830?}, {0x3df1f40?, 0xc00ee21620?})
``` 

### Expected Behavior

The reason is I forgot to config ??
```
  security:
    authorizationEnabled: false
```

### Milvus Log

[users-standalone.log](https://github.com/milvus-io/milvus/files/11476370/users-standalone.log)

pod in fouram cluster and qa-milvus namespace:
```
zong-users-aidmz-etcd-0                                           1/1     Running            0                 90m     10.104.17.42    4am-node23   <none>           <none>
zong-users-aidmz-milvus-standalone-98f57659b-7prdn                1/1     Running            11 (15m ago)      90m     10.104.21.208   4am-node24   <none>           <none>
zong-users-aidmz-minio-8586879bbf-qwbvs                           1/1     Running            0                 90m     10.104.17.43    4am-node23   <none>           <none>
```

test argo name: fouramf-concurrent-rbac-vwlhf

**Comment by ThreadDao** [comment]
It doesn't seem to be because the configuration is not enabled `security.authorizationEnabled`

Deploy and enabled rbac:
```
dao-users-zbliv-etcd-0                                            1/1     Running            0                  26m     10.104.5.123    4am-node12   <none>           <none>
dao-users-zbliv-milvus-standalone-57b7558497-d6wtn                0/1     CrashLoopBackOff   7 (2m16s ago)      26m     10.104.5.121    4am-node12   <none>           <none>
dao-users-zbliv-minio-84697974cb-dhtvm                            1/1     Running            0                  26m     10.104.5.122    4am-node12   <none>
```
standalone also panic:
```
[2023/05/15 10:03:48.419 +00:00] [INFO] [proxy/impl.go:4755] [RefreshPrivilegeInfoCache] [req="opType:1 opKey:\"user_1_6/admin\" "]
[2023/05/15 10:03:48.419 +00:00] [INFO] [proxy/impl.go:4773] ["RefreshPrivilegeInfoCache success"]
[2023/05/15 10:03:48.419 +00:00] [DEBUG] [rootcoord/service.go:474] ["OperateUserRole-AddUserToRole success"] [role=rootcoord]
[2023/05/15 10:03:48.420 +00:00] [DEBUG] [proxy/privilege_interceptor.go:68] [PrivilegeInterceptor] [type=*milvuspb.ListDatabasesRequest]
[2023/05/15 10:03:48.420 +00:00] [DEBUG] [funcutil/policy.go:47] ["GetPrivilegeExtObj success"] [resource_type=Global] [resource_privilege=PrivilegeListDatabases]
panic: implement me

goroutine 1482 [running]:
github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).ListDatabases(0x4450c58?, {0xc0013ab6b0?, 0x3df1f40?}, 0xc0013ab6b0?)
    /go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:945 +0x27
github.com/milvus-io/milvus-proto/go-api/milvuspb._MilvusService_ListDatabases_Handler.func1({0x4450c58, 0xc0013ab9b0}, {0x3df1f40?, 0xc0013ab6b0})
    /go/pkg/mod/github.com/milvus-io/milvus-proto/go-api@v0.0.0-20230509062636-f6c495229ceb/milvuspb/milvus.pb.go:11607 +0x7b
github.com/milvus-io/milvus/internal/proxy.RateLimitInterceptor.func1({0x4450c58, 0xc0013ab9b0}, {0x3df1f40, 0xc0013ab6b0}, 0xc000a0f9e0, 0xc0080de8e8)
    /go/src/github.com/milvus-io/milvus/internal/proxy/rate_limit_interceptor.go:38 +0xf3
```

[dao_standalone.log](https://github.com/milvus-io/milvus/files/11476672/dao_standalone.log)

argo workflow name in fouram cluster: `fouramf-concurrent-rbac-2`

**Comment by chyezh** [comment]
Expected error.
Database feature is not merged in HEAD in 2.2 branch.

**Comment by yanliang567** [comment]
@ThreadDao does it reproduce on 2.2 latest build?

**Comment by ThreadDao** [comment]
Nope closed

> @ThreadDao does it reproduce on 2.2 latest build?
