### ISSUE TITLE
[Bug]: [JSON] Insert could not support numpy.bool_ when inserting JSON data (bool key)

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#24153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230515-30415e1b
- Deployment mode(standalone or cluster):both
- MQ type(rocksmq, pulsar or kafka):    all
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.4.0.dev27
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

 Insert could not support numpy.bool_ when inserting JSON data (bool key)
```
>>> res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], [np.bool_(i) for i in range(nb)], [{"number": i, "string": "milvus", "bool": np.bool_(i), "list": [j for j in range(0, i)]} for i in range(0, nb)], vectors])
RPC error: [batch_insert], <DataNotMatchException: (code=1, message=The data in the same column must be of the same type.)>, <Time:{'RPC start': '2023-05-16 16:02:35.806906', 'RPC error': '2023-05-16 16:02:35.810998'}>
Traceback (most recent call last):
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/client/prepare.py", line 290, in batch_insert_or_upsert_param
    field_data = entity_helper.entity_to_field_data(entity, fields_info[location[entity.get("name")]])
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/client/entity_helper.py", line 83, in entity_to_field_data
    field_data.scalars.json_data.data.extend(entity_to_json_arr(entity))
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/client/entity_helper.py", line 47, in entity_to_json_arr
    arr.append(ujson.dumps(obj).encode(Config.EncodeProtocol))
TypeError: False is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 436, in insert
    res = conn.batch_insert(self._name, entities, partition_name,
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 409, in batch_insert
    raise err
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 390, in batch_insert
    request = self._prepare_batch_insert_or_upsert_request(
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 380, in _prepare_batch_insert_or_upsert_request
    else Prepare.batch_insert_or_upsert_param(collection_name, entities, partition_name, fields_info, isInsert)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/client/prepare.py", line 293, in batch_insert_or_upsert_param
    raise DataNotMatchException(message=ExceptionsMessage.DataTypeInconsistent) from e
pymilvus.exceptions.DataNotMatchException: <DataNotMatchException: (code=1, message=The data in the same column must be of the same type.)>
```

### Expected Behavior

Insert without errors

### Steps To Reproduce

```python
from pymilvus import CollectionSchema, FieldSchema
from pymilvus import Collection
from pymilvus import connections
from pymilvus import DataType
from pymilvus import Partition
from pymilvus import utility

connections.connect()
dim = 128
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
bool_field = FieldSchema(name="bool", dtype=DataType.BOOL)
string_field = FieldSchema(name="string", dtype=DataType.VARCHAR, max_length=65535)
json_field = FieldSchema(name="json_field", dtype=DataType.JSON)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
schema = CollectionSchema(fields=[int64_field, float_field, bool_field, json_field, float_vector])
collection = Collection("test_search_collection_binbin_tmp", schema=schema)
import random
nb=3000
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
import numpy as np
res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], [np.bool_(i) for i in range(nb)], [{"number": i, "string": "milvus", "bool": np.bool_(i), "list": [j for j in range(0, i)]} for i in range(0, nb)], vectors])
```

**Comment by binbinlv** [comment]
It is good if switch the type: bool(np.bool_(0)).
Milvus support np.bool_(i) in bool field, the behavior is better to keep the same.

```
>>> res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], [np.bool_(i) for i in range(nb)], [{"number": i, "string": "milvus", "bool": bool(np.bool_(0)), "list": [j for j in range(0, i)]} for i in range(0, nb)], vectors])
```

**Comment by yah01** [comment]
/assign @binbinlv 
After discussion, we are not going to support this for now

**Comment by binbinlv** [comment]
> /assign @binbinlv After discussion, we are not going to support this for now

OK, It is better to be mentioned on user doc.
