### ISSUE TITLE
[Bug]: [JSON] Querynode crashed after search/ query with json expression

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#24219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230518-0217e967
- Deployment mode(standalone or cluster):both
- MQ type(rocksmq, pulsar or kafka):    all
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.9.dev11
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Querynode crashed after search/ query with json expression:
```
RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:
attempt #1:code: NotReadyServe, error: err: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.102.6.134:21123: connect: connection refused"
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:296 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call
/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:254 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Search
/go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:500 github.com/milvus-io/milvus/internal/proxy.(*searchTask).searchShard
/go/src/github.com/milvus-io/milvus/internal/proxy/task_policies.go:132 github.com/milvus-io/milvus/internal/proxy.mergeRoundRobinPolicy.func1
/usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit

attempt #2:code: NotReadyServe, error: err: failed to connect 10.102.6.134:21123, reason: context deadline exceeded
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:296 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call
/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:254 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Search
/go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:500 github.com/milvus-io/milvus/internal/proxy.(*searchTask).searchShard
/go/src/github.com/milvus-io/milvus/internal/proxy/task_policies.go:132 github.com/milvus-io/milvus/internal/proxy.mergeRoundRobinPolicy.func1
/usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit

attempt #3:code: NotReadyServe, error: err: failed to connect 10.102.6.134:21123, reason: context deadline exceeded
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:296 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call
/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:254 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Search
/go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:500 github.com/milvus-io/milvus/internal/proxy.(*searchTask).searchShard
/go/src/github.com/milvus-io/milvus/internal/proxy/task_policies.go:132 github.com/milvus-io/milvus/internal/proxy.mergeRoundRobinPolicy.func1
/usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit

attempt #4:code: NotReadyServe, error: err: failed to connect 10.102.6.134:21123, reason: context deadline exceeded
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:296 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call
/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:254 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Search
/go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:500 github.com/milvus-io/milvus/internal/proxy.(*searchTask).searchShard
/go/src/github.com/milvus-io/milvus/internal/proxy/task_policies.go:132 github.com/milvus-io/milvus/internal/proxy.mergeRoundRobinPolicy.func1
/usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit

attempt #5:All attempts results:
attempt #1:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_0_441553362842552689v0 is not available in any replica, err=<nil>
attempt #2:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_0_441553362842552689v0 is not available in any replica, err=<nil>
attempt #3:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_0_441553362842552689v0 is not available in any replica, err=<nil>
attempt #4:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_0_441553362842552689v0 is not available in any replica, err=<nil>
attempt #5:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_0_441553362842552689v0 is not available in any replica, err=<nil>
attempt #6:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_0_441553362842552689v0 is not available in any replica, err=<nil>
attempt #7:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_0_441553362842552689v0 is not available in any replica, err=<nil>
attempt #8:context deadline exceeded
```

### Expected Behavior

Search successfully

### Steps To Reproduce

```python
from pymilvus import CollectionSchema, FieldSchema
from pymilvus import Collection
from pymilvus import connections
from pymilvus import DataType
from pymilvus import Partition
from pymilvus import utility

connections.connect()
dim = 128
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
bool_field = FieldSchema(name="bool", dtype=DataType.BOOL)
string_field = FieldSchema(name="string", dtype=DataType.VARCHAR, max_length=65535)
json_field = FieldSchema(name="json_field", dtype=DataType.JSON)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
schema = CollectionSchema(fields=[int64_field, float_field, bool_field, json_field, float_vector])
collection = Collection("test_search_collection_binbin_tmp", schema=schema)
import random
nb=3000
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
import numpy as np
res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], [np.bool_(i) for i in range(nb)], [{"number": i, "string": "milvus", "bool": True, "list": [j for j in range(0, i)]} for i in range(0, nb)], vectors])
index_param = {"index_type": "IVF_SQ8", "metric_type": "L2", "params": {"nlist": 8192}}
collection.create_index("float_vector", index_param, index_name="index_name_1")
collection.load()
default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
limit = 10
nq =1
res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "json_field[\"number\"] >= 0")
res = collection.query("json_field[\"number\"] >= 0")

```

### Milvus Log

[24219.zip](https://github.com/milvus-io/milvus/files/11505347/24219.zip)

**Comment by binbinlv** [comment]
This issue is for 2.2. branch

**Comment by binbinlv** [comment]
And same issue when specifying JSON in output_fields (query/search):
```
>>> res = collection.query("json_field[\"number\"] >= 0", output_fields=["json_field"])
RPC error: [query], <MilvusException: (code=1, message=fail to query on all shard leaders, err=All attempts results:
attempt #1:code: NotReadyServe, error: err: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.102.6.78:21123: connect: connection refused"
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:296 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call
/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:268 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Query
/go/src/github.com/milvus-io/milvus/internal/proxy/task_query.go:484 github.com/milvus-io/milvus/internal/proxy.(*queryTask).queryShard
/go/src/github.com/milvus-io/milvus/internal/proxy/task_policies.go:132 github.com/milvus-io/milvus/internal/proxy.mergeRoundRobinPolicy.func1
/usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit

attempt #2:code: NodeIDNotMatch, error: fail to Query, QueryNode ID = 14, reason=QueryNode 15 can't serve, recovering: target node id not match target id = 14, node id = 15
attempt #3:code: NodeIDNotMatch, error: fail to Query, QueryNode ID = 14, reason=QueryNode 15 can't serve, recovering: target node id not match target id = 14, node id = 15
attempt #4:code: NodeIDNotMatch, error: fail to Query, QueryNode ID = 14, reason=QueryNode 15 can't serve, recovering: target node id not match target id = 14, node id = 15
attempt #5:code: NodeIDNotMatch, error: fail to Query, QueryNode ID = 14, reason=QueryNode 15 can't serve, recovering: target node id not match target id = 14, node id = 15
)>, <Time:{'RPC start': '2023-05-19 15:35:10.688640', 'RPC error': '2023-05-19 15:35:18.115395'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 704, in query
    res = conn.query(self._name, expr, output_fields, partition_names,
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 950, in query
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to query on all shard leaders, err=All attempts results:
attempt #1:code: NotReadyServe, error: err: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.102.6.78:21123: connect: connection refused"
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:296 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call
/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:268 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Query
/go/src/github.com/milvus-io/milvus/internal/proxy/task_query.go:484 github.com/milvus-io/milvus/internal/proxy.(*queryTask).queryShard
/go/src/github.com/milvus-io/milvus/internal/proxy/task_policies.go:132 github.com/milvus-io/milvus/internal/proxy.mergeRoundRobinPolicy.func1
/usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit

attempt #2:code: NodeIDNotMatch, error: fail to Query, QueryNode ID = 14, reason=QueryNode 15 can't serve, recovering: target node id not match target id = 14, node id = 15
attempt #3:code: NodeIDNotMatch, error: fail to Query, QueryNode ID = 14, reason=QueryNode 15 can't serve, recovering: target node id not match target id = 14, node id = 15
attempt #4:code: NodeIDNotMatch, error: fail to Query, QueryNode ID = 14, reason=QueryNode 15 can't serve, recovering: target node id not match target id = 14, node id = 15
attempt #5:code: NodeIDNotMatch, error: fail to Query, QueryNode ID = 14, reason=QueryNode 15 can't serve, recovering: target node id not match target id = 14, node id = 15
```

**Comment by binbinlv** [comment]
Verified and fixed:
milvus: [2.2.0-20230520-1eb804fc](https://hub.docker.com/layers/milvusdb/milvus/2.2.0-20230520-1eb804fc/images/sha256-f1fce0b4ba76324119d89cebe860886197da341061e6688f0ef9da34719ef485?context=explore)
pymilvus: 2.2.9.dev12


```
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "json_field[\"number\"] >= 0")
>>> res[0].ids
[0, 59, 891, 157, 189, 2192, 966, 844, 1368, 568]
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "json_field[\"number\"] >= 0", output_fields=["json_field"])
>>> res[0][0]
id: 0, distance: 0.0, entity: {'json_field': b'{"number":0,"string":"milvus","bool":true,"list":[]}'}
>>> res = collection.query("json_field[\"number\"] >= 0", output_fields=["json_field"])
>>> res[0]
{'json_field': b'{"number":0,"string":"milvus","bool":true,"list":[]}', 'int64': 0}
```
