### ISSUE TITLE
[Bug]: Pod panic when disk quota is exceeded when bulk inserting, and bulk insert can still success after pod restart

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#24301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230522-edea7e55
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):rocksmq    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2023/05/22 09:23:55.737 +00:00] [INFO] [datanode/channel_meta.go:435] ["Successfully load pk stats"] [segmentID=441646066309730790] [time=5.434825ms] [size=16509]
[2023/05/22 09:23:55.742 +00:00] [WARN] [rootcoord/quota_center.go:733] ["collection disk quota exceeded"] [collection=441646066309530348] ["coll disk usage"=759227392] ["coll disk quota"=268435456]
panic: assignment to entry in nil map

goroutine 925 [running]:
github.com/milvus-io/milvus/internal/rootcoord.(*QuotaCenter).forceDenyWriting(0xc0020f2780, 0x36, {0xc0022b82c8?, 0xc005424898?, 0x14e024a?})
        /go/src/github.com/milvus-io/milvus/internal/rootcoord/quota_center.go:279 +0xb0
github.com/milvus-io/milvus/internal/rootcoord.(*QuotaCenter).checkDiskQuota(0xc0020f2780)
        /go/src/github.com/milvus-io/milvus/internal/rootcoord/quota_center.go:741 +0x7a5
github.com/milvus-io/milvus/internal/rootcoord.(*QuotaCenter).calculateWriteRates(0xc0020f2780)
        /go/src/github.com/milvus-io/milvus/internal/rootcoord/quota_center.go:420 +0x88
github.com/milvus-io/milvus/internal/rootcoord.(*QuotaCenter).calculateRates(0xc0020f2780?)
        /go/src/github.com/milvus-io/milvus/internal/rootcoord/quota_center.go:667 +0x28
github.com/milvus-io/milvus/internal/rootcoord.(*QuotaCenter).run(0xc0020f2780)
        /go/src/github.com/milvus-io/milvus/internal/rootcoord/quota_center.go:146 +0x31b
created by github.com/milvus-io/milvus/internal/rootcoord.(*Core).startInternal
        /go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:660 +0x105

```

### Expected Behavior

when the disk quota is exceeded, there will be writing deny.

### Milvus Log

Milvus setting
```
cluster:
  enabled: false

log:
  level: debug

image:
  all:
    repository: milvusdb/milvus
    tag: 2.2.0-20230522-edea7e55
    pullPolicy: IfNotPresent
standalone:
  resources:
    limits:
      cpu: 2
      memory: 6Gi
    requests:
      cpu: 2
      memory: 6Gi

kafka:
  enabled: false
  name: kafka
  replicaCount: 3
  defaultReplicationFactor: 2

etcd:
  replicaCount: 3
  image:
    debug: true
    repository: milvusdb/etcd
    tag: 3.5.5-r2  
minio:
  mode: standalone
pulsar:
  enabled: false

extraConfigFiles:
  user.yaml: |+
    quotaAndLimits:
      enabled: true
      memory:
        forceSyncEnable: false
      limitWriting:
        diskProtection:
          enabled: true
          diskQuota: 1024
          diskQuotaPerCollection: 256

```

before restart
[standalone.log](https://github.com/milvus-io/milvus/files/11529557/standalone.log)
after restart
[standalone_v2.log](https://github.com/milvus-io/milvus/files/11529579/standalone_v2.log)

[test_client.log](https://github.com/milvus-io/milvus/files/11529593/test_client.log)

**Comment by zhuwenxing** [comment]
First bulk insert success
```
[2023-05-22 17:20:00 - INFO - ci_test]: {441646066309735384: <Bulk insert state:
    - taskID          : 441646066309735384,
    - state           : Completed,
    - row_count       : 100000,
    - infos           : {'files': 'int64.npy,float.npy,varchar.npy,float_vector.npy', 'collection': 'Checker__G48GkNys', 'partition': '_default', 'failed_reason': '', 'progress_percent': '100', 'persist_cost': '19.30'},
    - id_ranges       : [],
    - create_ts       : 2023-05-22 17:19:39
>} (utility_wrapper.py:151)

```

second time failed 
```
[2023-05-22 17:27:06 - INFO - ci_test]: {441646066309935798: <Bulk insert state:
    - taskID          : 441646066309935798,
    - state           : Failed,
    - row_count       : 0,
    - infos           : {'files': 'int64.npy,float.npy,varchar.npy,float_vector.npy', 'collection': 'Checker__G48GkNys', 'partition': '_default', 'failed_reason': 'task marked failed as service restarted', 'progress_percent': '26'},
    - id_ranges       : [],
    - create_ts       : 2023-05-22 17:20:16
>} (utility_wrapper.py:151)

```


Third-time success
```
[2023-05-22 17:37:21 - INFO - ci_test]: {441646437034099670: <Bulk insert state:
    - taskID          : 441646437034099670,
    - state           : Completed,
    - row_count       : 100000,
    - infos           : {'files': 'int64.npy,float.npy,varchar.npy,float_vector.npy', 'collection': 'Checker__G48GkNys', 'partition': '_default', 'failed_reason': '', 'progress_percent': '100', 'persist_cost': '584.30'},
    - id_ranges       : [],
    - create_ts       : 2023-05-22 17:27:27
>} (utility_wrapper.py:151)

```

**Comment by zhuwenxing** [comment]
/assign @bigsheeper 
/assign @yhmo 

Please take a look!

**Comment by zhuwenxing** [comment]
the pod will not panic with image `2.2.0-20230525-ef1a671d`.

But it still can do bulk insert when disk usage reached the limit.

![image](https://github.com/milvus-io/milvus/assets/12268675/ec5c5c3f-9405-4dc3-b14a-ab6777d0b2c5)

```
extraConfigFiles:
  user.yaml: |+
    quotaAndLimits:
      enabled: true
      memory:
        forceSyncEnable: false
      limitWriting:
        diskProtection:
          enabled: true
          diskQuota: 1024
          diskQuotaPerCollection: 512
```
[standalone.log](https://github.com/milvus-io/milvus/files/11561864/standalone.log)

**Comment by zhuwenxing** [comment]
![image](https://github.com/milvus-io/milvus/assets/12268675/692f0fae-376a-4412-af0a-00fdbd0ede4d)

In the log, it shows that the server knows the total disk quota is exceeded, but the bulk insert task can still succeed.

**Comment by zhuwenxing** [comment]
Another problem: I set the quota to the collection, but there is no log showing that the collection quota was exceeded.

**Comment by bigsheeper** [comment]
hello @zhuwenxing , how many collection do you have? and did you inserted into thses collection concurrently?

**Comment by zhuwenxing** [comment]
> hello @zhuwenxing , how many collection do you have? and did you inserted into thses collection concurrently?

Not sure how many collections are in Milvus. But when doing bulk insert, the collections are same, and it is one by one.

**Comment by bigsheeper** [comment]
/assign @zhuwenxing 
please help to make a verify, thanks

**Comment by zhuwenxing** [comment]
deploy config
```
cluster:
  enabled: false

log:
  level: debug

image:
  all:
    repository: milvusdb/milvus
    tag: 2.2.0-20230529-c314d546
    pullPolicy: IfNotPresent
standalone:
  resources:
    limits:
      cpu: 2
      memory: 6Gi
    requests:
      cpu: 2
      memory: 6Gi

kafka:
  enabled: false
  name: kafka
  replicaCount: 3
  defaultReplicationFactor: 2

etcd:
  replicaCount: 3
  image:
    debug: true
    repository: milvusdb/etcd
    tag: 3.5.5-r2  
minio:
  mode: standalone
pulsar:
  enabled: false

extraConfigFiles:
  user.yaml: |+
    quotaAndLimits:
      enabled: true
      memory:
        forceSyncEnable: false
      limitWriting:
        diskProtection:
          enabled: true
          diskQuota: 1024
          diskQuotaPerCollection: 512

```
When total usage reached the limit, the bulk insert can still success.

```
[2023-05-29 17:14:09 - INFO - ci_test]: total disk usage: 2433.3874168395996 MB, rate limit: 10240 MB (test_bulk_insert_rate_limit.py:172)
[2023-05-29 17:14:18 - INFO - ci_test]: after waiting, there are 0 pending tasks (utility_wrapper.py:149)
[2023-05-29 17:14:18 - INFO - ci_test]: task state distribution: {'success': {441802188028044970}, 'failed': set(), 'in_progress': set()} (utility_wrapper.py:150)
[2023-05-29 17:14:18 - INFO - ci_test]: {441802188028044970: <Bulk insert state:
    - taskID          : 441802188028044970,
    - state           : Completed,
    - row_count       : 5000,
    - infos           : {'files': 'bulk_insert_data_source_dim_1024_nb_5000.json', 'collection': 'Checker__MEIsRABU', 'partition': '_default', 'failed_reason': '', 'progress_percent': '100', 'persist_cost': '149.41'},
    - id_ranges       : [],
    - create_ts       : 2023-05-29 17:11:43
>} (utility_wrapper.py:151)
[2023-05-29 17:14:18 - INFO 
```

**Comment by zhuwenxing** [comment]
It seems the rate limit takes effect
```
[2023/05/29 11:14:54.752 +00:00] [DEBUG] [querynode/impl.go:90] ["Get QueryNode component state done"] [stateCode=Healthy]
[2023/05/29 11:14:55.650 +00:00] [INFO] [indexcoord/index_builder.go:173] ["index builder task schedule"] ["task num"=12]
[2023/05/29 11:14:55.651 +00:00] [DEBUG] [indexnode/indexnode_service.go:155] ["querying index build task"] [traceID=344aa563b289d043] [ClusterID=by-dev] [IndexBuildID=441805045270015965] [state=InProgress] ["fail reason"=]
[2023/05/29 11:14:55.651 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=350ed7f52f9950c8] [Unissued=0] [Active=1] [Slot=0]
[2023/05/29 11:14:55.651 +00:00] [INFO] [indexcoord/index_builder.go:178] ["there is no IndexNode available or etcd is not serviceable, wait a minute..."]
[2023/05/29 11:14:56.549 +00:00] [INFO] [indexcoord/index_builder.go:173] ["index builder task schedule"] ["task num"=12]
[2023/05/29 11:14:56.550 +00:00] [DEBUG] [indexnode/indexnode_service.go:155] ["querying index build task"] [traceID=7f26fdbac9573354] [ClusterID=by-dev] [IndexBuildID=441805045270015965] [state=InProgress] ["fail reason"=]
[2023/05/29 11:14:56.550 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=4bfbdfc82a2a07c1] [Unissued=0] [Active=1] [Slot=0]
[2023/05/29 11:14:56.649 +00:00] [INFO] [indexcoord/index_builder.go:178] ["there is no IndexNode available or etcd is not serviceable, wait a minute..."]
[2023/05/29 11:14:57.549 +00:00] [INFO] [indexcoord/index_builder.go:173] ["index builder task schedule"] ["task num"=12]
[2023/05/29 11:14:57.654 +00:00] [DEBUG] [proxy/impl.go:4129] [Proxy.GetProxyMetrics] [traceID=2fa79cee3fb96c49] [nodeID=8] [req="{\"metric_type\":\"system_info\"}"] [metricType=system_info]
[2023/05/29 11:14:57.655 +00:00] [DEBUG] [indexnode/indexnode_service.go:155] ["querying index build task"] [traceID=2e9c6c793dc2fa5] [ClusterID=by-dev] [IndexBuildID=441805045270015965] [state=InProgress] ["fail reason"=]
[2023/05/29 11:14:57.655 +00:00] [DEBUG] [querynode/impl.go:90] ["Get QueryNode component state done"] [stateCode=Healthy]
[2023/05/29 11:14:57.753 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=6a64e2bf56aa213e] [Unissued=0] [Active=1] [Slot=0]
[2023/05/29 11:14:57.755 +00:00] [INFO] [log/mlogger.go:72] ["index builder peek client error, there is no available"]
[2023/05/29 11:14:57.755 +00:00] [INFO] [indexcoord/index_builder.go:178] ["there is no IndexNode available or etcd is not serviceable, wait a minute..."]
[2023/05/29 11:14:57.756 +00:00] [WARN] [rootcoord/quota_center.go:741] ["collection disk quota exceeded"] [collection=441805045269791928] ["coll disk usage"=274706726] ["coll disk quota"=268435456]
[2023/05/29 11:14:57.849 +00:00] [WARN] [rootcoord/quota_center.go:288] ["QuotaCenter force to deny writing"] [collectionIDs="[441805045269791928]"] [reason=DiskQuotaExhausted]
[2023/05/29 11:14:57.849 +00:00] [INFO] [rootcoord/quota_center.go:410] ["QueryNodeMetrics when cool-off"] [metrics="{\"1\":{\"Hms\":{\"ip\":\"10.102.6.52:21123\",\"cpu_core_count\":2,\"cpu_core_usage\":18.60279444009825,\"memory\":6442450944,\"memory_usage\":4410847232,\"disk\":104857600,\"disk_usage\":2097152},\"Rms\":[{\"Label\":\"NQPerSecond\",\"Rate\":0},{\"Label\":\"SearchThroughput\",\"Rate\":0},{\"Label\":\"InsertConsumeThroughput\",\"Rate\":0},{\"Label\":\"DeleteConsumeThroughput\",\"Rate\":0}],\"Fgm\":{\"MinFlowGraphChannel\":\"by-dev-rootcoord-delta_0_441805045269791928v0\",\"MinFlowGraphTt\":441806722708013058,\"NumFlowGraph\":4},\"SearchQueue\":{\"UnsolvedQueue\":0,\"ReadyQueue\":0,\"ReceiveChan\":0,\"ExecuteChan\":0,\"AvgQueueDuration\":0},\"QueryQueue\":{\"UnsolvedQueue\":0,\"ReadyQueue\":0,\"ReceiveChan\":0,\"ExecuteChan\":0,\"AvgQueueDuration\":0},\"GrowingSegmentsSize\":0,\"Effect\":{\"NodeID\":1,\"CollectionIDs\":[441805045269791928]}}}"]
[2023/05/29 11:14:58.550 +00:00] [INFO] [indexcoord/index_builder.go:173] ["index builder task schedule"] ["task num"=12]
[2023/05/29 11:14:58.552 +00:00] [DEBUG] [indexnode/indexnode_service.go:155] ["querying index build task"] [traceID=220059863bf371fe] [ClusterID=by-dev] [IndexBuildID=441805045270015965] [state=InProgress] ["fail reason"=]
[2023/05/29 11:14:58.553 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=61a7f9ef7285ee3e] [Unissued=0] [Active=1] [Slot=0]
[2023/05/29 11:14:58.553 +00:00] [INFO] [indexcoord/index_builder.go:178] ["there is no IndexNode available or etcd is not serviceable, wait a minute..."]
[2023/05/29 11:14:59.549 +00:00] [INFO] [indexcoord/index_builder.go:173] ["index builder task schedule"] ["task num"=12]
[2023/05/29 11:14:59.550 +00:00] [DEBUG] [indexnode/indexnode_service.go:155] ["querying index build task"] [traceID=5d13443c0ce493c0] [ClusterID=by-dev] [IndexBuildID=441805045270015965] [state=InProgress] ["fail reason"=]
[2023/05/29 11:14:59.551 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=4c0a2e05d2e639d] [Unissued=0] [Active=1] [Slot=0]
[2023/05/29 11:14:59.650 +00:00] [INFO] [indexcoord/index_builder.go:178] ["there is no IndexNode available or etcd is not serviceable, wait a minute..."]
[2023/05/29 11:14:59.650 +00:00] [DEBUG] [checkers/balance_checker.go:105] ["ScoreBasedBalancer has balanced collection, skip balancing in this round"] [collectionID=441805045269791928]
[2023/05/29 11:14:59.650 +00:00] [DEBUG] [checkers/balance_checker.go:119] ["ScoreBasedBalancer has balanced all collections in one round, clear collectionIDs for this round"]
[2023/05/29 11:15:00.554 +00:00] [INFO] [indexcoord/index_builder.go:173] ["index builder task schedule"] ["task num"=12]
[2023/05/29 11:15:00.655 +00:00] [DEBUG] [indexnode/indexnode_service.go:155] ["querying index build task"] [traceID=7e4d4855ac106686] [ClusterID=by-dev] [IndexBuildID=441805045270015965] [state=InProgress] ["fail reason"=]
(milvus) 
```

**Comment by xiaofan-luan** [comment]
why there is no IndexNode available or etcd is not serviceable, wait a minute?

**Comment by xiaofan-luan** [comment]
seems that the cluster is not in good states
