### ISSUE TITLE
[Bug]: Create index, load or search failed with error `failed to get channels, collection not loaded: collection=xxx: collection not found` after upgrade

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#24315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.2.5--> master-20230522-6da88537
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):kafka    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

After the upgrade, all test cases failed with error `failed to get channels, err=collection=xxx: collection not found`

```

[2023-05-22T10:52:23.724Z] Search...

[2023-05-22T10:52:23.725Z] RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=attempt #0: fail to get shard leaders from QueryCoord: failed to get channels, err=collection=441647242385124511: collection not found: unrecoverable error)>, <Time:{'RPC start': '2023-05-22 10:52:23.552902', 'RPC error': '2023-05-22 10:52:23.641666'}>

[2023-05-22T10:52:23.725Z] Traceback (most recent call last):

[2023-05-22T10:52:23.725Z]   File "scripts/action_after_upgrade.py", line 108, in <module>

[2023-05-22T10:52:23.725Z]     task_1(data_size, host)

[2023-05-22T10:52:23.725Z]   File "scripts/action_after_upgrade.py", line 20, in task_1

[2023-05-22T10:52:23.725Z]     load_and_search(prefix)

[2023-05-22T10:52:23.725Z]   File "/home/jenkins/agent/workspace/tests/python_client/deploy/scripts/utils.py", line 226, in load_and_search

[2023-05-22T10:52:23.725Z]     res = c.search(

[2023-05-22T10:52:23.725Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 666, in search

[2023-05-22T10:52:23.725Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,

[2023-05-22T10:52:23.725Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-05-22T10:52:23.725Z]     raise e

[2023-05-22T10:52:23.725Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-05-22T10:52:23.725Z]     return func(*args, **kwargs)

[2023-05-22T10:52:23.725Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-05-22T10:52:23.725Z]     ret = func(self, *args, **kwargs)

[2023-05-22T10:52:23.725Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-05-22T10:52:23.725Z]     raise e

[2023-05-22T10:52:23.725Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-05-22T10:52:23.725Z]     return func(self, *args, **kwargs)

[2023-05-22T10:52:23.725Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 521, in search

[2023-05-22T10:52:23.725Z]     return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)

[2023-05-22T10:52:23.725Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 490, in _execute_search_requests

[2023-05-22T10:52:23.725Z]     raise pre_err

[2023-05-22T10:52:23.725Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 481, in _execute_search_requests

[2023-05-22T10:52:23.725Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2023-05-22T10:52:23.725Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=attempt #0: fail to get shard leaders from QueryCoord: failed to get channels, err=collection=441647242385124511: collection not found: unrecoverable error)>

script returned exit code 
```

```

[2023-05-22T10:56:59.351Z] [2023-05-22 10:56:13 - ERROR - pymilvus.decorators]: RPC error: [get_replicas], <MilvusException: (code=15, message=failed to get replica info, err=failed to get channels, collection not loaded: collection=441647242384923701: collection not found)>, <Time:{'RPC start': '2023-05-22 10:56:13.743960', 'RPC error': '2023-05-22 10:56:13.746498'}> (decorators.py:108)

[2023-05-22T10:56:59.351Z] [2023-05-22 10:56:13 - ERROR - ci_test]: <MilvusException: (code=15, message=failed to get replica info, err=failed to get channels, collection not loaded: collection=441647242384923701: collection not found)> (test_action_second_deployment.py:114)
```

```

[2023-05-22T10:52:20.778Z] Create index...

[2023-05-22T10:52:20.778Z] RPC error: [get_replicas], <MilvusException: (code=15, message=failed to get replica info, err=failed to get channels, collection not loaded: collection=441647242385124511: collection not found)>, <Time:{'RPC start': '2023-05-22 10:52:20.525048', 'RPC error': '2023-05-22 10:52:20.526866'}>

[2023-05-22T10:52:20.778Z] 2023-05-22 10:52:20.526 | INFO     | MainThread |utils:create_index:172 - <MilvusException: (code=15, message=failed to get replica info, err=failed to get channels, collection not loaded: collection=441647242385124511: collection not found)>
```

### Expected Behavior

all test cases passed

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_kafka_cron/detail/deploy_test_kafka_cron/799/pipeline

log:

[artifacts-kafka-standalone-upgrade-799-server-second-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/11538685/artifacts-kafka-standalone-upgrade-799-server-second-deployment-logs.tar.gz)

[artifacts-kafka-standalone-upgrade-799-server-first-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/11538686/artifacts-kafka-standalone-upgrade-799-server-first-deployment-logs.tar.gz)

[artifacts-kafka-standalone-upgrade-799-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/11538687/artifacts-kafka-standalone-upgrade-799-pytest-logs.tar.gz)

**Comment by yah01** [comment]
This has been fixed with #24300 and #24335, please retry with the latest master
/assign @zhuwenxing
