### ISSUE TITLE
Cache is full during preloading

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#2433]
**Describe the bug**
```
[2020-05-26 11:39:49,358][ERROR][SERVER][TakeToExecute][reqsched_thread] Request failed with code: Error code(30111): Cache is full

```
```
11:23:16  2020-05-26:03:23:15,913 INFO     [k8s_runner.py:311] {'index_type': 'ivf_sq8h', 'index_param': {'nlist': 16384}}
11:23:38  2020-05-26:03:23:38,413 ERROR    [client.py:72] Cache is full
11:23:38  2020-05-26:03:23:38,413 ERROR    [main.py:71] Status not ok
11:23:38  2020-05-26:03:23:38,414 ERROR    [main.py:72] Traceback (most recent call last):
11:23:38    File "main.py", line 69, in queue_worker
11:23:38      runner.run(run_type, collection)
11:23:38    File "/home/jenkins/agent/workspace/milvus-benchmark-0.9.1/milvus_benchmark/k8s_runner.py", line 312, in run
11:23:38      milvus_instance.preload_collection()
11:23:38    File "/home/jenkins/agent/workspace/milvus-benchmark-0.9.1/milvus_benchmark/client.py", line 33, in wrapper
11:23:38      result = func(*args, **kwargs)
11:23:38    File "/home/jenkins/agent/workspace/milvus-benchmark-0.9.1/milvus_benchmark/client.py", line 196, in preload_collection
11:23:38      self.check_status(status)
11:23:38    File "/home/jenkins/agent/workspace/milvus-benchmark-0.9.1/milvus_benchmark/client.py", line 73, in check_status
11:23:38      raise Exception("Status not ok")
11:23:38  Exception: Status not ok
```

**Steps/Code to reproduce behavior**
dataset: `sift-1b`, `sift-50m`

**Expected behavior**

**Environment details**
0.9.1-gpu
0.9.1-cpu
```
11:37:46  2020-05-26:03:37:39,173 INFO     [client.py:222] Server command: get_config *, result: {
"cache_config":
{"cache_insert_data":"false","cpu_cache_capacity":"4","cpu_cache_threshold":"0.7","insert_buffer_size":"1"},
"db_config":
{"archive_days_threshold":"0","archive_disk_threshold":"0","auto_flush_interval":"1","backend_url":"sqlite://:@:/","preload_collection":""},
"engine_config":
{"omp_thread_num":"0","simd_type":"auto","use_blas_threshold":"0"},
"logs":
{"debug.enable":"true","error.enable":"true","fatal.enable":"true","info.enable":"true","log_rotate_num":"0","max_log_file_size":"1024","path":"/var/lib/milvus/logs","trace.enable":"true","warning.enable":"true"},
"metric_config":
{"address":"192.168.1.237","enable_monitor":"true","port":"9091"},
"server_config":
{"address":"0.0.0.0","deploy_mode":"single","port":"19530","time_zone":"UTC+8","web_enable":"true","web_port":"19121"},
"storage_config":
{"file_cleanup_timeout":"10","primary_path":"/test/milvus/db_data_8/sift_50m_2048_128_l2_ivf","secondary_path":""},
"tracing_config":
{"json_config_path":""},
"wal_config":
{"buffer_size":"256","enable":"true","recovery_error_ignore":"true","wal_path":"/test/milvus/db_data_8/sift_50m_2048_128_l2_ivf/wal"}}
```
**Screenshots**

**Additional context**

**Comment by del-zhenwu** [comment]
Cache value should be set big enough before preloading db data currently.

**Comment by yhmo** [comment]
I will make a fix

**Comment by yhmo** [comment]
fixed by pr2438

**Comment by del-zhenwu** [comment]
fixed and close
