### ISSUE TITLE
[Bug]: Standalone pod panic with error `insertBufferNode flushBufferData failed, role rootcoord[nodeID: 0] is not serving, reason: sate code: Abnormal`

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#24348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230523-8c1f9118
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):rocksmq    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2023-05-23T11:23:14.750Z] RPC error: [get_index_state], <MilvusException: (code=56, message=role indexcoord[nodeID: 3] is not serving, reason: sate code: Abnormal)>, <Time:{'RPC start': '2023-05-23 11:22:12.260653', 'RPC error': '2023-05-23 11:22:59.862867'}>

[2023-05-23T11:23:14.750Z] RPC error: [wait_for_creating_index], <MilvusException: (code=56, message=role indexcoord[nodeID: 3] is not serving, reason: sate code: Abnormal)>, <Time:{'RPC start': '2023-05-23 11:21:26.735002', 'RPC error': '2023-05-23 11:22:59.863045'}>

[2023-05-23T11:23:14.750Z] RPC error: [create_index], <MilvusException: (code=56, message=role indexcoord[nodeID: 3] is not serving, reason: sate code: Abnormal)>, <Time:{'RPC start': '2023-05-23 11:21:26.711341', 'RPC error': '2023-05-23 11:22:59.863083'}>

[2023-05-23T11:23:14.750Z] Traceback (most recent call last):

[2023-05-23T11:23:14.750Z]   File "scripts/action_before_reinstall.py", line 47, in <module>

[2023-05-23T11:23:14.750Z]     task_1(data_size, host)

[2023-05-23T11:23:14.750Z]   File "scripts/action_before_reinstall.py", line 15, in task_1

[2023-05-23T11:23:14.750Z]     create_index(prefix)

[2023-05-23T11:23:14.750Z]   File "/home/jenkins/agent/workspace/tests/python_client/deploy/scripts/utils.py", line 184, in create_index

[2023-05-23T11:23:14.750Z]     c.create_index(field_name="float_vector", index_params=index)

[2023-05-23T11:23:14.750Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 1005, in create_index

[2023-05-23T11:23:14.750Z]     return conn.create_index(self._name, field_name, index_params, timeout=timeout, **kwargs)

[2023-05-23T11:23:14.750Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-05-23T11:23:14.750Z]     raise e

[2023-05-23T11:23:14.750Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-05-23T11:23:14.750Z]     return func(*args, **kwargs)

[2023-05-23T11:23:14.750Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-05-23T11:23:14.750Z]     ret = func(self, *args, **kwargs)

[2023-05-23T11:23:14.750Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-05-23T11:23:14.750Z]     raise e

[2023-05-23T11:23:14.750Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-05-23T11:23:14.750Z]     return func(self, *args, **kwargs)

[2023-05-23T11:23:14.750Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 607, in create_index

[2023-05-23T11:23:14.750Z]     index_success, fail_reason = self.wait_for_creating_index(collection_name=collection_name,

[2023-05-23T11:23:14.751Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-05-23T11:23:14.751Z]     raise e

[2023-05-23T11:23:14.751Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-05-23T11:23:14.751Z]     return func(*args, **kwargs)

[2023-05-23T11:23:14.751Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-05-23T11:23:14.751Z]     ret = func(self, *args, **kwargs)

[2023-05-23T11:23:14.751Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-05-23T11:23:14.751Z]     raise e

[2023-05-23T11:23:14.751Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-05-23T11:23:14.751Z]     return func(self, *args, **kwargs)

[2023-05-23T11:23:14.751Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 690, in wait_for_creating_index

[2023-05-23T11:23:14.751Z]     state, fail_reason = self.get_index_state(collection_name, index_name, timeout=timeout, **kwargs)

[2023-05-23T11:23:14.751Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-05-23T11:23:14.751Z]     raise e

[2023-05-23T11:23:14.751Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-05-23T11:23:14.751Z]     return func(*args, **kwargs)

[2023-05-23T11:23:14.751Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-05-23T11:23:14.751Z]     ret = func(self, *args, **kwargs)

[2023-05-23T11:23:14.751Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-05-23T11:23:14.751Z]     raise e

[2023-05-23T11:23:14.751Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-05-23T11:23:14.751Z]     return func(self, *args, **kwargs)

[2023-05-23T11:23:14.751Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 671, in get_index_state

[2023-05-23T11:23:14.751Z]     raise MilvusException(status.error_code, status.reason)

[2023-05-23T11:23:14.751Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=56, message=role indexcoord[nodeID: 3] is not serving, reason: sate code: Abnormal)>

script returned exit code 1
```

```
[2023-05-23T11:23:39.811Z] + kubectl get pods -o wide

[2023-05-23T11:23:39.811Z] + grep rocksmq-standalone-reinstall-419

[2023-05-23T11:23:39.811Z] rocksmq-standalone-reinstall-419-etcd-0                           1/1     Running                0                  13m     10.104.9.48     4am-node14   <none>           <none>

[2023-05-23T11:23:39.811Z] rocksmq-standalone-reinstall-419-etcd-1                           1/1     Running                0                  13m     10.104.4.25     4am-node11   <none>           <none>

[2023-05-23T11:23:39.811Z] rocksmq-standalone-reinstall-419-etcd-2                           1/1     Running                0                  13m     10.104.23.160   4am-node27   <none>           <none>

[2023-05-23T11:23:39.811Z] rocksmq-standalone-reinstall-419-milvus-standalone-595bf99ssnh2   0/1     Running                1 (32s ago)        13m     10.104.18.50    4am-node25   <none>           <none>

[2023-05-23T11:23:39.811Z] rocksmq-standalone-reinstall-419-minio-66945f69d8-sppbl           1/1     Running                0                  13m     10.104.18.51    4am-node25   <none>           <none>
```

panic log:

```
[2023/05/23 11:23:07.162 +00:00] [ERROR] [datanode/flow_graph_insert_buffer_node.go:504] ["insertBufferNode flushBufferData failed, err = All attempts results:\nattempt #1:role rootcoord[nodeID: 0] is not serving, reason: sate code: Abnormal\nattempt #2:context canceled\n"] [stack="github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Sync\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:504\ngithub.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Operate\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:140\ngithub.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work\n\t/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:127"]
panic: insertBufferNode flushBufferData failed, err = All attempts results:
attempt #1:role rootcoord[nodeID: 0] is not serving, reason: sate code: Abnormal
attempt #2:context canceled


goroutine 8842 [running]:
github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Sync(0xc004e70f70, 0xc00c0d5740?, {0xc021a9fb68?, 0x0?, 0x0?}, 0xc01336dd40)
	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:505 +0x1285
github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Operate(0xc004e70f70, {0xc00371a430, 0x1, 0x1})
	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:140 +0x485
github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work(0xc006578410)
	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:127 +0x2ac
created by github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start
	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:71 +0x79
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_for_release_cron/detail/deploy_test_for_release_cron/419/pipeline

log:
[artifacts-rocksmq-standalone-reinstall-419-server-logs (2).tar.gz](https://github.com/milvus-io/milvus/files/11549876/artifacts-rocksmq-standalone-reinstall-419-server-logs.2.tar.gz)

[artifacts-rocksmq-standalone-reinstall-419-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/11549877/artifacts-rocksmq-standalone-reinstall-419-pytest-logs.tar.gz)

**Comment by xiaofan-luan** [comment]
I will simply change the retry to 20 times

**Comment by xiaofan-luan** [comment]
why coordinator is not serving still a issue

**Comment by weiliu1031** [comment]
> why coordinator is not serving still a issue

![image](https://github.com/milvus-io/milvus/assets/108661493/2720f5b1-e3c0-450d-8afd-a39bf37341f1)
the keep alive channel closed suddenly, and the root coord exit.

and the reason for why etcd close the keep alive channel, seems due to leader change

**Comment by zhuwenxing** [comment]
dup with https://github.com/milvus-io/milvus/issues/26124

so close this.
