### ISSUE TITLE
[Bug]: [Nightly]Create collection failed with message `failed to watch channels .. UnexpectedError, reason: DataCoord 13 is not ready` 

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#24379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 014387f
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):2.4.0.dev27
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Create collection failed with message `failed to watch channels .. UnexpectedError, reason: DataCoord 13 is not ready` .
```
[2023-05-24T19:50:44.189Z] [2023-05-24 18:28:42 - ERROR - pymilvus.decorators]: RPC error: [create_collection], <MilvusException: (code=1, message=failed to watch channels, code: UnexpectedError, reason: DataCoord 13 is not ready)>, <Time:{'RPC start': '2023-05-24 18:28:42.159052', 'RPC error': '2023-05-24 18:28:42.175795'}> (decorators.py:108)
[2023-05-24T19:50:44.189Z] [2023-05-24 18:28:42 - ERROR - ci_test]: Traceback (most recent call last):
[2023-05-24T19:50:44.189Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2023-05-24T19:50:44.189Z]     res = func(*args, **_kwargs)
[2023-05-24T19:50:44.189Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2023-05-24T19:50:44.189Z]     return func(*arg, **kwargs)
[2023-05-24T19:50:44.189Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 120, in __init__
[2023-05-24T19:50:44.189Z]     conn.create_collection(self._name, schema, **kwargs)
[2023-05-24T19:50:44.189Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2023-05-24T19:50:44.189Z]     raise e
[2023-05-24T19:50:44.189Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2023-05-24T19:50:44.189Z]     return func(*args, **kwargs)
[2023-05-24T19:50:44.189Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2023-05-24T19:50:44.189Z]     ret = func(self, *args, **kwargs)
[2023-05-24T19:50:44.189Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
[2023-05-24T19:50:44.189Z]     raise e
[2023-05-24T19:50:44.189Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2023-05-24T19:50:44.189Z]     return func(self, *args, **kwargs)
[2023-05-24T19:50:44.189Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 215, in create_collection
[2023-05-24T19:50:44.189Z]     raise MilvusException(status.error_code, status.reason)
[2023-05-24T19:50:44.189Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=failed to watch channels, code: UnexpectedError, reason: DataCoord 13 is not ready)>
[2023-05-24T19:50:44.189Z]  (api_request.py:39)
[2023-05-24T19:50:44.189Z] [2023-05-24 18:28:42 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=failed to watch channels, code: UnexpectedError, reason: DataCoord 13 is not ready)> (api_request.py:40)
```

### Expected Behavior

pass

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/382/pipeline/139/
2. log: [artifacts-milvus-distributed-kafka-nightly-382-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/382/artifact/artifacts-milvus-distributed-kafka-nightly-382-pymilvus-e2e-logs.tar.gz)
3. failed time: [2023-05-24T18:28:50.394Z] [gw2] [  6%] FAILED testcases/test_collection.py::TestLoadCollection::test_load_partitions_after_release_partitions
4. collection name: collection_o7UD4Tt1
5. all failed cases:
```
[2023-05-24T19:50:44.912Z] FAILED testcases/test_collection.py::TestLoadCollection::test_load_partitions_after_release_partitions - AssertionError
[2023-05-24T19:50:44.912Z] FAILED testcases/test_collection.py::TestLoadCollection::test_load_collection_after_release_partitions - AssertionError
[2023-05-24T19:50:44.912Z] FAILED testcases/test_collection.py::TestCollectionMultiCollections::test_collection_count_multi_collections_mix - AssertionError
[2023-05-24T19:50:44.912Z] FAILED testcases/test_collection.py::TestLoadCollection::test_release_collection_after_drop - AssertionError
[2023-05-24T19:50:44.912Z] FAILED testcases/test_collection.py::TestCollectionMultiCollections::test_collection_count_multi_collections_l2[2001] - AssertionError
[2023-05-24T19:50:44.912Z] FAILED testcases/test_collection.py::TestLoadCollection::test_load_release_collection - AssertionError
[2023-05-24T19:50:44.912Z] FAILED testcases/test_collection.py::TestLoadCollection::test_load_replica_number_none[None] - AssertionError
[2023-05-24T19:50:44.912Z] FAILED testcases/test_collection.py::TestLoadCollection::test_load_collection_without_creating_index - AssertionError
[2023-05-24T19:50:44.912Z] FAILED testcases/test_collection.py::TestLoadCollection::test_load_replica_invalid_number[0] - AssertionError
[2023-05-24T19:50:44.912Z] FAILED testcases/test_collection.py::TestLoadCollection::test_get_collection_replicas_not_loaded - AssertionError
[2023-05-24T19:50:44.912Z] FAILED testcases/test_collection.py::TestHasCollection::test_has_collection_without_connection - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadPartition::test_load_partition_after_index_binary[JACCARD-binary_index0] - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadPartition::test_load_partition_after_index_binary[JACCARD-binary_index1] - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestCollectionMultiCollections::test_collection_count_multi_collections_binary[1] - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadPartition::test_load_partition_after_index_binary[SUBSTRUCTURE-binary_index1] - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestDropCollection::test_create_drop_collection_multithread - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadPartition::test_load_partition_after_index_binary[SUBSTRUCTURE-binary_index0] - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadCollection::test_release_collection_dis_connect - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadPartition::test_load_partition_not_existed - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestDropCollection::test_drop_collection_A - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadPartition::test_release_partition_not_load - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadCollection::test_load_partitions_after_load_collection - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadPartition::test_load_collection_after_load_one_partition - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadPartition::test_load_collection_after_load_unloaded_partition - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadCollection::test_load_collection_after_release_partition_collection - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestHasCollection::test_has_collection_not_existed - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadPartition::test_release_load_partition_after_load_partition_drop_another - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadPartition::test_load_partitions_after_load_partition_release_partitions - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_compaction.py::TestCompactionParams::test_compact_only_growing_segment - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadCollection::test_load_empty_collection - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestListCollections::test_list_collections_multithread - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadCollection::test_load_another_partition_after_drop_one_partition - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadPartition::test_load_another_partition_after_load_drop_partition - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadCollection::test_load_collection_after_load_release - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_compaction.py::TestCompactionParams::test_compact_max_time_interval - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadCollection::test_load_partition_names_empty - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadCollection::test_load_collection_not_existed - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadCollection::test_load_partitions_after_load_release_collection - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_compaction.py::TestCompactionOperation::test_compact_merge_multi_segments - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadCollection::test_load_collection_after_drop_one_partition - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_compaction.py::TestCompactionOperation::test_compact_and_delete - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_compaction.py::TestCompactionOperation::test_compact_merge_inside_time_travel - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadCollection::test_load_replica_multi - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_compaction.py::TestCompactionOperation::test_compact_cross_shards - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadCollection::test_load_replica_greater_than_querynodes - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestReleaseAdvanced::test_release_partition_during_searching - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestCollectionMultiCollections::test_collection_count_multi_collections_l2[1000] - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestDescribeCollection::test_collection_describe - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadPartition::test_load_partition_after_index_binary[TANIMOTO-binary_index0] - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadCollection::test_load_replica_invalid_number[-1] - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadPartition::test_load_partition_dis_connect - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadPartition::test_load_partition_after_index_binary[HAMMING-binary_index0] - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadCollection::test_load_replica_partitions - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadPartition::test_load_release_after_collection_drop - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadPartition::test_load_partition_after_index_binary[SUPERSTRUCTURE-binary_index0] - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadPartition::test_load_partitions_after_load_release_partition - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadPartition::test_load_release_after_drop - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestReleaseAdvanced::test_release_indexed_collection_during_searching - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestCollectionString::test_collection_string_field_is_primary - Exception: The result to check isn't collection type object
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadPartition::test_load_partitions_release_collection - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_compaction.py::TestCompactionParams::test_compact_without_connection - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadPartition::test_load_partition_after_index_binary[TANIMOTO-binary_index1] - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadPartition::test_release_load_collection_after_load_partition_drop_another - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadPartition::test_release_partition_dis_connect - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_compaction.py::TestCompactionParams::test_compact_delete_ratio - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadPartition::test_load_collection_after_load_loaded_partition - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestCreateCollection::test_create_collection_multithread - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_compaction.py::TestCompactionOperation::test_compact_after_index - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_compaction.py::TestCompactionParams::test_compact_empty_collection - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_compaction.py::TestCompactionOperation::test_compact_search_after_delete_channel - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadPartition::test_release_load_collection_after_load_drop_partition - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_compaction.py::TestCompactionOperation::test_compact_no_merge - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_compaction.py::TestCompactionOperation::test_compact_during_index - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestCollectionString::test_collection_with_muti_string_fields - Exception: The result to check isn't collection type object
[2023-05-24T19:50:44.913Z] FAILED testcases/test_compaction.py::TestCompactionOperation::test_compact_threshold_auto_merge - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_compaction.py::TestCompactionOperation::test_compact_cross_partition - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_compaction.py::TestCompactionParams::test_compact_delete_less_ratio - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestListCollections::test_list_collections_multi_collections - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_compaction.py::TestCompactionOperation::test_compact_after_binary_index - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_collection.py::TestLoadCollection::test_load_collection_dis_connect - AssertionError
[2023-05-24T19:50:44.913Z] FAILED testcases/test_compaction.py::TestCompactionOperation::test_compact_and_insert - AssertionError
[2023-05-24T19:50:44.914Z] FAILED testcases/test_collection.py::TestLoadCollection::test_load_collection_repeatedly - AssertionError
[2023-05-24T19:50:44.914Z] FAILED testcases/test_compaction.py::TestCompactionOperation::test_compact_during_search - AssertionError
[2023-05-24T19:50:44.914Z] FAILED testcases/test_collection.py::TestLoadCollection::test_load_partitions_after_release_partition - AssertionError
[2023-05-24T19:50:44.914Z] FAILED testcases/test_collection.py::TestLoadCollection::test_load_partition_after_drop_partition_and_release_another - AssertionError
[2023-05-24T19:50:44.914Z] FAILED testcases/test_collection.py::TestLoadCollection::test_load_replica_change - AssertionError
[2023-05-24T19:50:44.914Z] FAILED testcases/test_collection.py::TestReleaseAdvanced::test_release_collection_during_searching - AssertionError
[2023-05-24T19:50:44.914Z] FAILED testcases/test_collection.py::TestLoadPartition::test_load_partition_after_index_binary[HAMMING-binary_index1] - AssertionError
[2023-05-24T19:50:44.914Z] FAILED testcases/test_collection.py::TestLoadPartition::test_load_partition_after_index_binary[SUPERSTRUCTURE-binary_index1] - AssertionError
[2023-05-24T19:50:44.914Z] FAILED testcases/test_collection.py::TestLoadPartition::test_release_partition_after_drop - AssertionError
[2023-05-24T19:50:44.914Z] FAILED testcases/test_collection.py::TestLoadPartition::test_load_collection_release_collection - AssertionError
[2023-05-24T19:50:44.914Z] FAILED testcases/test_compaction.py::TestCompactionParams::test_compact_after_delete - AssertionError
[2023-05-24T19:50:44.914Z] FAILED testcases/test_compaction.py::TestCompactionOperation::test_compact_merge_multi_shards - AssertionError
[2023-05-24T19:50:44.914Z] FAILED testcases/test_compaction.py::TestCompactionOperation::test_compact_merge_two_segments - AssertionError
[2023-05-24T19:50:44.914Z] FAILED testcases/test_compaction.py::TestCompactionOperation::test_compact_less_threshold_no_merge - AssertionError
[2023-05-24T19:50:44.914Z] FAILED testcases/test_compaction.py::TestCompactionOperation::test_compact_during_insert - AssertionError
```

**Comment by NicoYuan1986** [comment]
Reproduced.

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/401/pipeline/241/
2. log: [artifacts-milvus-distributed-kafka-nightly-401-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/401/artifact/artifacts-milvus-distributed-kafka-nightly-401-pymilvus-e2e-logs.tar.gz)
3. the failure started at about [2023-06-12T18:29:59.490Z] [gw4] [  6%] FAILED testcases/test_collection.py::TestLoadPartition::test_load_collection_after_load_loaded_partition 
4. end at about [2023-06-12T18:30:00.264Z] [gw3] [  7%] FAILED testcases/test_collection.py::TestReleaseAdvanced::test_release_partition_during_searching

**Comment by NicoYuan1986** [comment]
Reproduced.

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/409/pipeline/205
2. log: [artifacts-milvus-distributed-kafka-nightly-409-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/409/artifact/artifacts-milvus-distributed-kafka-nightly-409-pymilvus-e2e-logs.tar.gz)

**Comment by NicoYuan1986** [comment]
@sunby Could you help resolve it?

**Comment by sunby** [comment]
@NicoYuan1986 I find that datanode restarts many times because of kafka channel double close. It's already fixed and please rerun tests.

**Comment by NicoYuan1986** [comment]
Fixed.
