### ISSUE TITLE
[Bug]: [Nightly]Load collection sometimes failed for timeout

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#24380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 014387f
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):2.4.0.dev27
```

### Current Behavior

Load collection sometimes failed for timeout.
```
[2023-05-24T19:50:44.186Z] [2023-05-24 18:00:37 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=wait for loading collection timeout, collection: collection_wOZVqJcR)>, <Time:{'RPC start': '2023-05-24 17:58:36.754327', 'RPC error': '2023-05-24 18:00:37.252259'}> (decorators.py:108)
[2023-05-24T19:50:44.186Z] [2023-05-24 18:00:37 - WARNING - pymilvus.decorators]: [93mRetry timeout: 120s[0m (decorators.py:79)
[2023-05-24T19:50:44.186Z] [2023-05-24 18:00:37 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: collection_wOZVqJcR)>, <Time:{'RPC start': '2023-05-24 17:58:36.736653', 'RPC error': '2023-05-24 18:00:37.252822'}> (decorators.py:108)
[2023-05-24T19:50:44.186Z] [2023-05-24 18:00:37 - ERROR - ci_test]: Traceback (most recent call last):
[2023-05-24T19:50:44.186Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2023-05-24T19:50:44.186Z]     return func(self, *args, **kwargs)
[2023-05-24T19:50:44.186Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 711, in load_collection
[2023-05-24T19:50:44.186Z]     self.wait_for_loading_collection(collection_name, timeout)
[2023-05-24T19:50:44.186Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2023-05-24T19:50:44.186Z]     raise e
[2023-05-24T19:50:44.186Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2023-05-24T19:50:44.186Z]     return func(*args, **kwargs)
[2023-05-24T19:50:44.186Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2023-05-24T19:50:44.186Z]     ret = func(self, *args, **kwargs)
[2023-05-24T19:50:44.186Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
[2023-05-24T19:50:44.186Z]     raise e
[2023-05-24T19:50:44.186Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2023-05-24T19:50:44.186Z]     return func(self, *args, **kwargs)
[2023-05-24T19:50:44.186Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 733, in wait_for_loading_collection
[2023-05-24T19:50:44.186Z]     raise MilvusException(message=f"wait for loading collection timeout, collection: {collection_name}")
[2023-05-24T19:50:44.186Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=wait for loading collection timeout, collection: collection_wOZVqJcR)>
[2023-05-24T19:50:44.186Z] 
[2023-05-24T19:50:44.186Z] The above exception was the direct cause of the following exception:
[2023-05-24T19:50:44.186Z] 
[2023-05-24T19:50:44.186Z] Traceback (most recent call last):
[2023-05-24T19:50:44.186Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2023-05-24T19:50:44.186Z]     res = func(*args, **_kwargs)
[2023-05-24T19:50:44.186Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2023-05-24T19:50:44.186Z]     return func(*arg, **kwargs)
[2023-05-24T19:50:44.186Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 372, in load
[2023-05-24T19:50:44.186Z]     conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
[2023-05-24T19:50:44.186Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2023-05-24T19:50:44.186Z]     raise e
[2023-05-24T19:50:44.186Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2023-05-24T19:50:44.186Z]     return func(*args, **kwargs)
[2023-05-24T19:50:44.186Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2023-05-24T19:50:44.186Z]     ret = func(self, *args, **kwargs)
[2023-05-24T19:50:44.186Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 80, in handler
[2023-05-24T19:50:44.186Z]     raise MilvusException(e.code, f"{timeout_msg}, message={e.message}") from e
[2023-05-24T19:50:44.186Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: collection_wOZVqJcR)>
[2023-05-24T19:50:44.186Z]  (api_request.py:39)
[2023-05-24T19:50:44.186Z] [2023-05-24 18:00:37 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: collection_wOZVqJcR)> (api_request.py:40)
```

### Expected Behavior

succeed

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/382/pipeline/139/
2. log: [artifacts-milvus-distributed-kafka-nightly-382-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/382/artifact/artifacts-milvus-distributed-kafka-nightly-382-pymilvus-e2e-logs.tar.gz)
3. failed time: [2023-05-24T18:00:42.727Z] [gw0] [  6%] FAILED testcases/test_collection.py::TestLoadCollection::test_load_collection_after_release_collection_partition 
4. collection name: collection_wOZVqJcR

**Comment by NicoYuan1986** [comment]
Update: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/387/pipeline/258/

1. log: [artifacts-milvus-distributed-pulsar-nightly-387-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/387/artifact/artifacts-milvus-distributed-pulsar-nightly-387-pymilvus-e2e-logs.tar.gz)
2. collection name: search_collection_aHgXby0E
3. failed time: [2023-05-29T18:21:59.543Z] [gw2] [ 37%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_after_different_index_with_params[32-True-False-FLAT-params0]

**Comment by NicoYuan1986** [comment]
not reproduced for a long time.
