### ISSUE TITLE
[Bug]: [Dynamic] Insert failed reporting "The fields don't match with schema fields"

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#24448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-20230526-a521e364
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):    all
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-2.2.9.dev17
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Insert failed reporting "The fields don't match with schema fields"

```
>>> collection = Collection("test_search_collection_binbin_tmp_11111", schema=schema)
>>>
>>> collection.describe()
{'collection_name': 'test_search_collection_binbin_tmp_11111', 'auto_id': False, 'num_shards': 1, 'description': '', 'fields': [{'field_id': 100, 'name': 'int64', 'description': '', 'type': 5, 'params': {}, 'is_primary': True, 'auto_id': False, 'is_partition_key': False, 'is_dynamic': False}, {'field_id': 101, 'name': 'float_vector', 'description': '', 'type': 101, 'params': {'dim': 128}, 'is_primary': False, 'auto_id': False, 'is_partition_key': False, 'is_dynamic': False}], 'aliases': [], 'collection_id': 441734086790730512, 'consistency_level': 2, 'properties': [], 'num_partitions': 1, 'enable_dynamic_field': True}

>>> import numpy as np
>>> res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], [np.bool_(i) for i in range(nb)], vectors])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 440, in insert
    check_insert_data_schema(self._schema, data)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/orm/schema.py", line 405, in check_insert_data_schema
    check_infer_fields_valid(infer_fields, tmp_fields, isinstance(data, pandas.DataFrame))
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/orm/schema.py", line 468, in check_infer_fields_valid
    raise DataNotMatchException(
pymilvus.exceptions.DataNotMatchException: <DataNotMatchException: (code=1, message=The fields don't match with schema fields, expected: ['int64', 'float_vector'], got ['', '', '', ''])>
```

### Expected Behavior

Insert successfully

### Steps To Reproduce

```python
from pymilvus import CollectionSchema, FieldSchema
from pymilvus import Collection
from pymilvus import connections
from pymilvus import DataType
from pymilvus import Partition
from pymilvus import utility
connections.connect()

int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
dim = 128
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
schema = CollectionSchema(fields=[int64_field, float_vector], enable_dynamic_field=True)
collection = Collection("test_search_collection_binbin_tmp_11111", schema=schema)
collection.describe()
nb=3000
import random
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
import numpy as np
res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], [np.bool_(i) for i in range(nb)], vectors])
```

**Comment by binbinlv** [comment]
As discussed with @czs007, dynamic field does not support Columnar insertion, so close this issue.

the supported insert could refer this example:
https://github.com/milvus-io/pymilvus/commit/72761edad7904ad206280223bdda02aed2c7a8a2#diff-5dad536ae32bae114e72f36fdcb041e1cf73a3b148cecaf05df57bd78ef945d4
