### ISSUE TITLE
[Bug]: Latest pymilvus is not compatible with old version milvus

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#24444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 3ae4e00
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):    all
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.9.dev17
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Latest pymilvus is not compatible with old version milvus

```
>>> connections.connect()
RPC error: [__internal_register], <MilvusException: (code=1, message=<_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "unknown method Connect for service milvus.proto.milvus.MilvusService"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:10.15.22.142:19530 {grpc_message:"unknown method Connect for service milvus.proto.milvus.MilvusService", grpc_status:12, created_time:"2023-05-26T15:11:23.708754+08:00"}"
>)>, <Time:{'RPC start': '2023-05-26 15:11:23.505637', 'RPC error': '2023-05-26 15:11:23.709263'}>
Traceback (most recent call last):
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 1398, in __internal_register
    response = self._stub.Connect(request=req)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/grpc/_interceptor.py", line 247, in __call__
    response, ignored_call = self._with_call(request,
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/grpc/_interceptor.py", line 290, in _with_call
    return call.result(), call
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/grpc/_channel.py", line 379, in result
    raise self
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/grpc/_interceptor.py", line 274, in continuation
    response, call = self._thunk(new_method).with_call(
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/grpc/_interceptor.py", line 301, in with_call
    return self._with_call(request,
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/grpc/_interceptor.py", line 290, in _with_call
    return call.result(), call
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/grpc/_channel.py", line 379, in result
    raise self
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/grpc/_interceptor.py", line 274, in continuation
    response, call = self._thunk(new_method).with_call(
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/grpc/_channel.py", line 1043, in with_call
    return _end_unary_response_blocking(state, call, True, None)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/grpc/_channel.py", line 910, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "unknown method Connect for service milvus.proto.milvus.MilvusService"
	debug_error_string = "UNKNOWN:Error received from peer ipv {grpc_message:"unknown method Connect for service milvus.proto.milvus.MilvusService", grpc_status:12, created_time:"2023-05-26T15:11:23.708754+08:00"}"

```

### Expected Behavior

Latest pymilvus is compatible with old version milvus

### Steps To Reproduce

```markdown
Use latest pymilvus(2.2.9.dev17) to operate old version milvus(3ae4e00)
```

### Milvus Log

NA

### Anything else?

NA

**Comment by binbinlv** [comment]
@czs007 

Do we support this compatibility?

**Comment by xiaofan-luan** [comment]
this is as expected.
We only support backward compatibility

**Comment by yanliang567** [comment]
@xiaofan-luan can we have a sdk support list to reject any unsupported connection?

**Comment by xiaofan-luan** [comment]
/assign @longjiquan 
We can probably simply ignore the error

**Comment by xiaofan-luan** [comment]
That will help for new SDK to connect the old cluster

**Comment by longjiquan** [comment]
fixed by the https://github.com/milvus-io/pymilvus/pull/1481 and https://github.com/milvus-io/pymilvus/pull/1482

**Comment by binbinlv** [comment]
Verified and fixed.

Now the behavior for newest pymilvus to connect old version milvus is not supported and report errors.

pymilvus: 2.2.9.dev30 and 
Results:
```
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=this version of sdk is incompatible with server, please downgrade your sdk or upgrade your server )>
```
pymilvus: 2.4.0.dev60
Results:
```
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=this version of sdk is incompatible with server, please downgrade your sdk or upgrade your server )>
```
