### ISSUE TITLE
[Bug]: Fail to create partition after load collection

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#24446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230526-fe18109a
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):2.4.0.dev46
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Fail to create partition after load collection.
```
RPC error: [create_partition], <MilvusException: (code=1, message=sync new partition failed, reason: failed to sync new created partition, err=context deadline exceeded)>, <Time:{'RPC start': '2023-05-26 16:31:33.019446', 'RPC error': '2023-05-26 16:31:43.135379'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/orm/collection.py", line 866, in create_partition
    return Partition(self, partition_name, description=description, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/orm/partition.py", line 43, in __init__
    conn.create_partition(self._collection.name, self.name, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 320, in create_partition
    raise MilvusException(response.error_code, response.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=sync new partition failed, reason: failed to sync new created partition, err=context deadline exceeded)>
```

### Expected Behavior

pass

### Steps To Reproduce

```markdown
1. create a collection with 2 partitions
2. load collection
3. create a partition -> ❌
```

### Milvus Log

```python
from pymilvus import CollectionSchema, FieldSchema, Collection, connections, DataType, Partition, utility
import numpy as np
import pandas as pd
import random
connections.connect()

# create collection
dim = 128
nb = 300
fields = [
    FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True, description='pk'),
    FieldSchema(name="float", dtype=DataType.FLOAT),
    FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
]
schema = CollectionSchema(fields=fields)

collection = Collection("test_load", schema=schema)
index = {"index_type": "IVF_FLAT", "params": {"nlist": 128}, "metric_type": "L2"}
collection.create_index("float_vector", index)
partition1 = collection.partitions[0]
partition2 = collection.create_partition('_default2')
# 2 partitions: _default, _default2

# insert data
data = pd.DataFrame({
    'int64': [i for i in range(nb)],
    'float': [np.float32(i) for i in range(nb)],
    'float_vector': [[random.random() for _ in range(dim)] for _ in range(nb)]
})
collection.insert(data[:100], partition1.name)
collection.insert(data[100:200], partition2.name)

# load + release
collection.load()

partition3 = collection.create_partition('_default3')
collection.insert(data[200:], partition3.name)
partition3.load()

# check
res = collection.query('int64 >= 0')
print(len(res))

```

**Comment by bigsheeper** [comment]
/assign @NicoYuan1986 

should be fixed, please help to verify

**Comment by NicoYuan1986** [comment]
Fixed.
