### ISSUE TITLE
[Bug]: [Dynamic] Insert failed reporting "can not assign primary field data when auto id enabled int64" while did not insert data for primary key field

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#24471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-latest(2.2.0-20230529-7e7ca5f9)
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):    all
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Insert failed reporting "can not assign primary field data when auto id enabled int64" while did not insert data for primary key field
```
>>> hello_milvus.insert(rows)
RPC error: [insert_rows], <MilvusException: (code=1, message=can not assign primary field data when auto id enabled int64)>, <Time:{'RPC start': '2023-05-29 10:41:11.399641', 'RPC error': '2023-05-29 10:41:11.597090'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 447, in insert
    res = conn.insert_rows(self._name, data, partition_name,
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 443, in insert_rows
    raise err
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 441, in insert_rows
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=can not assign primary field data when auto id enabled int64)>
```

### Expected Behavior

Insert successfully

### Steps To Reproduce

```markdown
import time
import numpy as np
from pymilvus import (
     connections,
     utility,
     FieldSchema, CollectionSchema, DataType,
     Collection,
 )

connections.connect()
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
dim = 128
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
schema = CollectionSchema(fields=[int64_field, float_field, float_vector], auto_id=True)
hello_milvus = Collection("hello_milvus", schema)

rng = np.random.default_rng(seed=19530)
rows = [
         {"float": 1.0, "float_vector": rng.random((1, dim))[0], "a": 1},
         {"float": 1.0, "float_vector": rng.random((1, dim))[0], "b": 1},
         {"float": 1.0, "float_vector": rng.random((1, dim))[0], "c": 1},
         {"float": 1.0, "float_vector": rng.random((1, dim))[0], "d": 1},
         {"float": 1.0, "float_vector": rng.random((1, dim))[0], "e": 1},
         {"float": 1.0, "float_vector": rng.random((1, dim))[0], "f": 1},
         ]

hello_milvus.insert(rows)
```

**Comment by binbinlv** [comment]
In master:

```
>>> import time
>>> import numpy as np
>>> from pymilvus import (
...      connections,
...      utility,
...      FieldSchema, CollectionSchema, DataType,
...      Collection,
...  )
>>> connections.connect(host="10.101.235.6")
>>> int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
>>> float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
>>> dim = 128
>>> float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
>>> schema = CollectionSchema(fields=[int64_field, float_field, float_vector], auto_id=True, enable_dynamic_field=True)
>>> hello_milvus = Collection("hello_milvus", schema)
>>>
>>> rng = np.random.default_rng(seed=19530)
>>> rows = [
...          {"float": 1.0, "float_vector": rng.random((1, dim))[0], "a": 1},
...          {"float": 1.0, "float_vector": rng.random((1, dim))[0], "b": 1},
...          {"float": 1.0, "float_vector": rng.random((1, dim))[0], "c": 1},
...          {"float": 1.0, "float_vector": rng.random((1, dim))[0], "d": 1},
...          {"float": 1.0, "float_vector": rng.random((1, dim))[0], "e": 1},
...          {"float": 1.0, "float_vector": rng.random((1, dim))[0], "f": 1},
...          ]
>>> hello_milvus.insert(rows)
RPC error: [insert_rows], <MilvusException: (code=1, message=the length of passed fields is equal to needed: expected=3, actual=4: invalid parameter)>, <Time:{'RPC start': '2023-05-29 16:09:36.639391', 'RPC error': '2023-05-29 16:09:36.752838'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 447, in insert
    res = conn.insert_rows(self._name, data, partition_name,
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 443, in insert_rows
    raise err
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 441, in insert_rows
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=the length of passed fields is equal to needed: expected=3, actual=4: invalid parameter)>
```

**Comment by xiaocai2333** [comment]
fixed, please verify. @binbinlv 
/assign @binbinlv

**Comment by binbinlv** [comment]
Verified and fixed:
in 2.2 branch: pymilvus 2.2.9.dev18
```
Type "help", "copyright", "credits" or "license" for more information.
>>> import time
>>> import numpy as np
>>> from pymilvus import (
...      connections,
...      utility,
...      FieldSchema, CollectionSchema, DataType,
...      Collection,
...  )

>>>
>>> connections.connect(host="10.102.9.228")
>>> connections.connect()
>>> int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
>>> float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
>>> dim = 128
>>> float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
>>> schema = CollectionSchema(fields=[int64_field, float_field, float_vector], auto_id=True, enable_dynamic_field=True)
>>> hello_milvus = Collection("hello_milvus", schema)
>>> rng = np.random.default_rng(seed=19530)
>>> rows = [
...          {"float": 1.0, "float_vector": rng.random((1, dim))[0], "a": 1},
...          {"float": 1.0, "float_vector": rng.random((1, dim))[0], "b": 1},
...          {"float": 1.0, "float_vector": rng.random((1, dim))[0], "c": 1},
...          {"float": 1.0, "float_vector": rng.random((1, dim))[0], "d": 1},
...          {"float": 1.0, "float_vector": rng.random((1, dim))[0], "e": 1},
...          {"float": 1.0, "float_vector": rng.random((1, dim))[0], "f": 1},
...          ]
>>> hello_milvus.insert(rows)
(insert count: 6, delete count: 0, upsert count: 0, timestamp: 441805108597489667, success count: 6, err count: 0)
```
