### ISSUE TITLE
[Bug]: Fail to insert data when using default value

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#24497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230529-63752365
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):2.4.0.dev48
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Fail to insert data when using default value.
1. empty
```
>>> data = [
...     [i for i in range(nb)],
...     [[random.random() for _ in range(dim)] for _ in range(nb)],
... ]
>>> collection.insert(data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/orm/collection.py", line 440, in insert
    check_insert_or_upsert_data_schema(self._schema, data)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/orm/schema.py", line 421, in check_insert_or_upsert_data_schema
    check_infer_fields_valid(infer_fields, tmp_fields, is_data_frame)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/orm/schema.py", line 544, in check_infer_fields_valid
    raise DataNotMatchException(
pymilvus.exceptions.DataNotMatchException: <DataNotMatchException: (code=1, message=The data type of field varchar doesn't match, expected: VARCHAR, got FLOAT_VECTOR)>
```
2. None
```
>>> data = [
...     [i for i in range(nb)],
...     None,
...     [[random.random() for _ in range(dim)] for _ in range(nb)],
... ]
>>> collection.insert(data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/orm/collection.py", line 440, in insert
    check_insert_or_upsert_data_schema(self._schema, data)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/orm/schema.py", line 419, in check_insert_or_upsert_data_schema
    infer_fields, tmp_fields, is_data_frame = parse_fields_from_data(
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/orm/schema.py", line 442, in parse_fields_from_data
    raise DataTypeNotSupportException(
pymilvus.exceptions.DataTypeNotSupportException: <DataTypeNotSupportException: (code=1, message=data should be a list of list)>
```

### Expected Behavior

pass

### Milvus Log

```python
from pymilvus import CollectionSchema, FieldSchema, Collection, connections, DataType, Partition, utility
import numpy as np
import pandas as pd
import random
connections.connect()

# create collection
dim = 128
nb = 300
fields = [
    FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True, description='pk'),
    FieldSchema(name="varchar", dtype=DataType.VARCHAR, max_length=512, default_value="abc"),
    FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim),
]
schema = CollectionSchema(fields=fields)
collection = Collection("test_default_value", schema=schema)

data = [
    [i for i in range(nb)],
    None,
    [[random.random() for _ in range(dim)] for _ in range(nb)],
]
collection.insert(data)

```

**Comment by smellthemoon** [comment]
related with https://github.com/milvus-io/pymilvus/pull/1473
