### ISSUE TITLE
[Bug]: Fail to insert with empty data using multiple default value fields

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#24521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230530-b09e7aea
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0.dev56
```

### Current Behavior

Fail to insert with empty data using multiple default value fields.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/orm/collection.py", line 441, in insert
    entities = Prepare.prepare_insert_or_upsert_data(data, self._schema)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/orm/prepare.py", line 64, in prepare_insert_or_upsert_data
    if data[i] is None:
IndexError: list index out of range

```

### Expected Behavior

pass

### Steps To Reproduce

```markdown
# create collection
dim = 128
nb = 300
fields = [
    FieldSchema(name="pk", dtype=DataType.INT64, is_primary=True, description='pk'),
    FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim),
    FieldSchema(name="int8", dtype=DataType.INT8, default_value=np.int8(8)),
    FieldSchema(name="int16", dtype=DataType.INT16, default_value=np.int16(16)),
    FieldSchema(name="int32", dtype=DataType.INT32, default_value=np.int32(32)),
    FieldSchema(name="int64", dtype=DataType.INT64, default_value=np.int64(64)),
    FieldSchema(name="float", dtype=DataType.FLOAT, default_value=np.float32(3.1415)),
    FieldSchema(name="bool", dtype=DataType.BOOL, default_value=False),
    FieldSchema(name="double", dtype=DataType.DOUBLE, default_value=np.double(6.7891)),
    FieldSchema(name="varchar", dtype=DataType.VARCHAR, max_length=512, default_value="abc"),
]
schema = CollectionSchema(fields=fields)

if utility.has_collection("test_default_value"):
    utility.drop_collection("test_default_value")

collection = Collection("test_default_value", schema=schema)

# insert data
data = [
    [i for i in range(nb)],
    [[random.random() for _ in range(dim)] for _ in range(nb)]
]
collection.insert(data)
```

**Comment by smellthemoon** [comment]
related with https://github.com/milvus-io/pymilvus/pull/1488

**Comment by NicoYuan1986** [comment]
fixed.
