### ISSUE TITLE
[Bug]: Load timeout after datacoord pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#24614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230601-93ea9c49
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2023-06-01T20:51:47.416Z] [2023-06-01 20:49:40 - INFO - ci_test]: assert entities: 12000 (test_data_persistence.py:84)

[2023-06-01T20:51:47.416Z] [2023-06-01 20:49:40 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:56)

[2023-06-01T20:51:47.416Z] [2023-06-01 20:51:41 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=wait for loading collection timeout, collection: Hello_Milvus)>, <Time:{'RPC start': '2023-06-01 20:49:40.943420', 'RPC error': '2023-06-01 20:51:41.160027'}> (decorators.py:108)

[2023-06-01T20:51:47.416Z] [2023-06-01 20:51:41 - WARNING - pymilvus.decorators]: Retry timeout: 120s (decorators.py:79)

[2023-06-01T20:51:47.416Z] [2023-06-01 20:51:41 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: Hello_Milvus)>, <Time:{'RPC start': '2023-06-01 20:49:40.740209', 'RPC error': '2023-06-01 20:51:41.160557'}> (decorators.py:108)

[2023-06-01T20:51:47.416Z] [2023-06-01 20:51:41 - ERROR - ci_test]: Traceback (most recent call last):

[2023-06-01T20:51:47.416Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-06-01T20:51:47.416Z]     return func(self, *args, **kwargs)

[2023-06-01T20:51:47.416Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 790, in load_collection

[2023-06-01T20:51:47.416Z]     self.wait_for_loading_collection(collection_name, timeout)

[2023-06-01T20:51:47.416Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-06-01T20:51:47.416Z]     raise e

[2023-06-01T20:51:47.416Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-06-01T20:51:47.416Z]     return func(*args, **kwargs)

[2023-06-01T20:51:47.416Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-06-01T20:51:47.416Z]     ret = func(self, *args, **kwargs)

[2023-06-01T20:51:47.416Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-06-01T20:51:47.416Z]     raise e

[2023-06-01T20:51:47.416Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-06-01T20:51:47.416Z]     return func(self, *args, **kwargs)

[2023-06-01T20:51:47.416Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 812, in wait_for_loading_collection

[2023-06-01T20:51:47.416Z]     raise MilvusException(message=f"wait for loading collection timeout, collection: {collection_name}")

[2023-06-01T20:51:47.416Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=wait for loading collection timeout, collection: Hello_Milvus)>

[2023-06-01T20:51:47.416Z] 

[2023-06-01T20:51:47.416Z] The above exception was the direct cause of the following exception:

[2023-06-01T20:51:47.416Z] 

[2023-06-01T20:51:47.416Z] Traceback (most recent call last):

[2023-06-01T20:51:47.416Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2023-06-01T20:51:47.416Z]     res = func(*args, **_kwargs)

[2023-06-01T20:51:47.416Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2023-06-01T20:51:47.416Z]     return func(*arg, **kwargs)

[2023-06-01T20:51:47.416Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 375, in load

[2023-06-01T20:51:47.416Z]     conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)

[2023-06-01T20:51:47.416Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-06-01T20:51:47.416Z]     raise e

[2023-06-01T20:51:47.416Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-06-01T20:51:47.416Z]     return func(*args, **kwargs)

[2023-06-01T20:51:47.416Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-06-01T20:51:47.416Z]     ret = func(self, *args, **kwargs)

[2023-06-01T20:51:47.416Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 80, in handler

[2023-06-01T20:51:47.416Z]     raise MilvusException(e.code, f"{timeout_msg}, message={e.message}") from e

[2023-06-01T20:51:47.416Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: Hello_Milvus)>

[2023-06-01T20:51:47.416Z]  (api_request.py:39)

[2023-06-01T20:51:47.416Z] [2023-06-01 20:51:41 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: Hello_Milvus)> (api_request.py:40)

[2023-06-01T20:51:47.416Z] ------------- generated html file: file:///tmp/ci_logs/report.html -------------

[2023-06-01T20:51:47.416Z] =========================== short test summary info ============================

[2023-06-01T20:51:47.416Z] FAILED testcases/test_data_persistence.py::TestDataPersistence::test_milvus_default - AssertionError

[2023-06-01T20:51:47.416Z] ======================== 1 failed in 135.45s (0:02:15) =========================

script returned exit code 1
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/4625/pipeline

log:
[artifacts-datacoord-pod-kill-4625-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/11631650/artifacts-datacoord-pod-kill-4625-server-logs.tar.gz)

[artifacts-datacoord-pod-kill-4625-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/11631651/artifacts-datacoord-pod-kill-4625-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
This issue reproduced Stabley.

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/4709/pipeline
log:

[artifacts-datacoord-pod-failure-4709-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/11648258/artifacts-datacoord-pod-failure-4709-server-logs.tar.gz)

[artifacts-datacoord-pod-failure-4709-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/11648261/artifacts-datacoord-pod-failure-4709-pytest-logs.tar.gz)

**Comment by sunby** [comment]
endless chaos bug 😂

**Comment by sunby** [comment]
maybe caused by https://github.com/milvus-io/milvus/pull/23570/, stats log is parsed between string and int64 but the special stats log's path suffix is "01" which is parsed to 1(int64).

**Comment by sunby** [comment]
@aoiasd will fix it.
