### ISSUE TITLE
[Bug]: fail to load a collection with diskann index

### ISSUE THREAD

**Issue by baijinge0310** [milvus-io/milvus#24621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvusdb/milvus:v2.2.8
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): kafka
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.2.8
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 56/314.6GiB
- GPU: None
- Others:
```

### Current Behavior

I created a collection indexed by `DISKANN`, then inserted 100w rows of 512-dimensional data, got stuck in load, waited about half an hour, and then prompted for an error and failed to load.
As follows, it is my table-building statement.
```
fields = [
    FieldSchema(name='id', dtype=DataType.INT64, descrition='ids', is_primary=True, auto_id=False),
    FieldSchema(name='embedding', dtype=DataType.FLOAT_VECTOR, descrition='embedding vectors', dim=dim)
]
schema = CollectionSchema(fields=fields, description='reverse image search')
collection = Collection(name=table_name, schema=schema)
index_params = {
    'metric_type': 'L2',
    'index_type': "DISKANN",
    'params': {}
}
code = collection.create_index(field_name="embedding", index_params=index_params)
```
Here is my load script
```
connections.connect(host="172.38.40.153", port="19530")
table_name = "disk_test"
logger.info("开始load了")
collection = Collection(name=table_name)
collection.load()
logger.info("load完成")
```
Here is the error log.
```
2023-06-02 14:09:56,473 - my_milvus - line:252 - INFO - 开始load了
2023-06-02 14:40:08,151 - decorators - line:108 - ERROR - RPC error: [get_loading_progress], <MilvusException: (code=1, message=collection 441233733579602972 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2023-06-02 14:40:08.140782', 'RPC error': '2023-06-02 14:40:08.151140'}>
2023-06-02 14:40:08,151 - decorators - line:108 - ERROR - RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=collection 441233733579602972 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2023-06-02 14:09:56.514860', 'RPC error': '2023-06-02 14:40:08.151562'}>
2023-06-02 14:40:08,151 - decorators - line:108 - ERROR - RPC error: [load_collection], <MilvusException: (code=1, message=collection 441233733579602972 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2023-06-02 14:09:56.503955', 'RPC error': '2023-06-02 14:40:08.151742'}>
Traceback (most recent call last):
  File "/Users/bai/Desktop/milvus_tool/utils/my_milvus.py", line 254, in <module>
    collection.load()
  File "/Users/bai/anaconda3/envs/milvus_tool/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 364, in load
    conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
  File "/Users/bai/anaconda3/envs/milvus_tool/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/Users/bai/anaconda3/envs/milvus_tool/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/Users/bai/anaconda3/envs/milvus_tool/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/Users/bai/anaconda3/envs/milvus_tool/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/Users/bai/anaconda3/envs/milvus_tool/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/Users/bai/anaconda3/envs/milvus_tool/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 687, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/Users/bai/anaconda3/envs/milvus_tool/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/Users/bai/anaconda3/envs/milvus_tool/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/Users/bai/anaconda3/envs/milvus_tool/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/Users/bai/anaconda3/envs/milvus_tool/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/Users/bai/anaconda3/envs/milvus_tool/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/Users/bai/anaconda3/envs/milvus_tool/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 705, in wait_for_loading_collection
    progress = self.get_loading_progress(collection_name, timeout=timeout)
  File "/Users/bai/anaconda3/envs/milvus_tool/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/Users/bai/anaconda3/envs/milvus_tool/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/Users/bai/anaconda3/envs/milvus_tool/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/Users/bai/anaconda3/envs/milvus_tool/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/Users/bai/anaconda3/envs/milvus_tool/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/Users/bai/anaconda3/envs/milvus_tool/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 772, in get_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection 441233733579602972 has not been loaded to memory or load failed)>
```
Can someone help me troubleshoot this problem? I've tried that other types of indexes are ok.I guess is it because of the fluctuation of the network io of the host where the milvus service is located?

**Comment by yanliang567** [comment]
@baijinge0310 Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @baijinge0310

**Comment by xiaofan-luan** [comment]
To enable diskANN on your production environment, you will need to setup a nvme temp dir for caching.

We will need to have Querycoord/Querynode log to investigate why you load failed, but disk performance is usually one of the major concerns.

**Comment by baijinge0310** [comment]
This is a single-node service started by docker-compose. Since the log size exceeds the github limit, I have sent the standalone log to Mr. Xiaolong of “Milvus用户交流群102”.

**Comment by baijinge0310** [comment]
> @baijinge0310 Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
> 
> /assign @baijinge0310

https://pan.baidu.com/s/1FPTaYYs6Zm9Aw7Hdql3LQg?pwd=qvqr 
I uploaded the log to Baidu online disk.I started it with docker-compose and intercepted the log of the “standalone” service, one just after load and the other after the error was reported.

**Comment by xige-16** [comment]
@baijinge0310 Sorry for the late reply. There doesn't seem to be any abnormality from the logs. If you still have problems, you can try upgrading to the latest version of Milvus.

**Comment by yanliang567** [comment]
close as no feedbacks for creator for long time
