### ISSUE TITLE
[Bug]: [ci] Float vector search with flat index gets error Assert "is_float_data_type == is_float_metric_type"

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#24689]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.4.0.dev67
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

jenkins link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-24682/1/pipeline/

failed case:
```


[2023-06-06T08:47:38.472Z]     def test_partition_release(self):

[2023-06-06T08:47:38.472Z]         """

[2023-06-06T08:47:38.472Z]         target: verify release partition

[2023-06-06T08:47:38.472Z]         method: 1. create a collection and two partitions

[2023-06-06T08:47:38.472Z]                 2. insert data into each partition

[2023-06-06T08:47:38.472Z]                 3. flush and load the partition1

[2023-06-06T08:47:38.472Z]                 4. release partition1

[2023-06-06T08:47:38.472Z]                 5. release partition2

[2023-06-06T08:47:38.472Z]         expected: 1. the 1st partition is released

[2023-06-06T08:47:38.472Z]                   2. the 2nd partition is released

[2023-06-06T08:47:38.472Z]         """

[2023-06-06T08:47:38.473Z]         # create collection

[2023-06-06T08:47:38.473Z]     

[2023-06-06T08:47:38.473Z]         collection_w = self.init_collection_wrap()

[2023-06-06T08:47:38.473Z]         collection_w.create_index(ct.default_float_vec_field_name, index_params=ct.default_flat_index)

[2023-06-06T08:47:38.473Z]     

[2023-06-06T08:47:38.473Z]         # create two partitions

[2023-06-06T08:47:38.473Z]         partition_w1 = self.init_partition_wrap(collection_w)

[2023-06-06T08:47:38.473Z]         partition_w2 = self.init_partition_wrap(collection_w)

[2023-06-06T08:47:38.473Z]     

[2023-06-06T08:47:38.473Z]         # insert data to two partition

[2023-06-06T08:47:38.473Z]         partition_w1.insert(cf.gen_default_list_data())

[2023-06-06T08:47:38.473Z]         partition_w2.insert(cf.gen_default_list_data())

[2023-06-06T08:47:38.473Z]     

[2023-06-06T08:47:38.473Z]         # load two partitions

[2023-06-06T08:47:38.473Z]         partition_w1.load()

[2023-06-06T08:47:38.473Z]     

[2023-06-06T08:47:38.473Z]         # search  partition1

[2023-06-06T08:47:38.473Z]         search_vectors = cf.gen_vectors(1, ct.default_dim)

[2023-06-06T08:47:38.473Z] >       res1, _ = partition_w1.search(data=search_vectors,

[2023-06-06T08:47:38.473Z]                                       anns_field=ct.default_float_vec_field_name,

[2023-06-06T08:47:38.473Z]                                       params={"nprobe": 32}, limit=1)
```

Case logs:
```
[2023-06-06T08:47:38.474Z] [2023-06-06 08:47:27 - DEBUG - ci_test]: (api_request)  : [Partition.search] args: [[[0.13370258626922998, 0.027305671097499266, 0.0056039893727706305, 0.08984188006961258, 0.05979996652758897, 0.05459569630456104, 0.0682462688913339, 0.10207865293921013, 0.1470685601342297, 0.03193095697265624, 0.10910294657923192, 0.01764960291230022, 0.016166165477839306, 0.003056571812437048, ......, kwargs: {'timeout': 20} (api_request.py:56)

[2023-06-06T08:47:38.474Z] [2023-06-06 08:47:28 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=[UnexpectedError] Assert "is_float_data_type == is_float_metric_type" at /go/src/github.com/milvus-io/milvus/internal/core/src/query/SearchBruteForce.cpp:34

[2023-06-06T08:47:38.474Z]  => [BruteForceSearch] Data type and metric type miss-match)>, <Time:{'RPC start': '2023-06-06 08:47:27.998854', 'RPC error': '2023-06-06 08:47:28.331727'}> (decorators.py:108)

[2023-06-06T08:47:38.474Z] [2023-06-06 08:47:28 - ERROR - ci_test]: Traceback (most recent call last):

[2023-06-06T08:47:38.474Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2023-06-06T08:47:38.474Z]     res = func(*args, **_kwargs)

[2023-06-06T08:47:38.474Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2023-06-06T08:47:38.474Z]     return func(*arg, **kwargs)

[2023-06-06T08:47:38.474Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/partition.py", line 452, in search

[2023-06-06T08:47:38.474Z]     return self._collection.search(

[2023-06-06T08:47:38.474Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 681, in search

[2023-06-06T08:47:38.474Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,

[2023-06-06T08:47:38.474Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler

[2023-06-06T08:47:38.474Z]     raise e

[2023-06-06T08:47:38.474Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler

[2023-06-06T08:47:38.474Z]     return func(*args, **kwargs)

[2023-06-06T08:47:38.474Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler

[2023-06-06T08:47:38.474Z]     ret = func(self, *args, **kwargs)

[2023-06-06T08:47:38.474Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler

[2023-06-06T08:47:38.474Z]     raise e

[2023-06-06T08:47:38.474Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler

[2023-06-06T08:47:38.474Z]     return func(self, *args, **kwargs)

[2023-06-06T08:47:38.474Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 599, in search

[2023-06-06T08:47:38.474Z]     return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, **kwargs)

[2023-06-06T08:47:38.474Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 579, in _execute_search_requests

[2023-06-06T08:47:38.474Z]     raise pre_err

[2023-06-06T08:47:38.474Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 570, in _execute_search_requests

[2023-06-06T08:47:38.474Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2023-06-06T08:47:38.474Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=[UnexpectedError] Assert "is_float_data_type == is_float_metric_type" at /go/src/github.com/milvus-io/milvus/internal/core/src/query/SearchBruteForce.cpp:34

[2023-06-06T08:47:38.474Z]  => [BruteForceSearch] Data type and metric type miss-match)>

[2023-06-06T08:47:38.474Z]  (api_request.py:39)
```

**Comment by yah01** [comment]
fixed by @bigsheeper 
/assign @ThreadDao
