### ISSUE TITLE
[Bug]: [High level] Creating collections with same collection name and  different dim does not report errors

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#24718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-20230607-02e3b06b
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):    all
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-2.2.10.dev1
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Create collections with same collection name and  different dim is successful
```
>>> dim = 256
>>> collection_name = "binbin_milvus"
>>> milvus_client.create_collection(collection_name, dim)
>>> milvus_client.describe_collection("binbin_milvus")
{'auto_id': False, 'description': '', 'fields': [{'name': 'id', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'vector', 'description': '', 'type': <DataType.FLOAT_VECTOR: 101>, 'params': {'dim': 256}}], 'enable_dynamic_field': True}
>>> dim = 128
>>> milvus_client.create_collection(collection_name, dim)
>>> milvus_client.describe_collection("binbin_milvus")
{'auto_id': False, 'description': '', 'fields': [{'name': 'id', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'vector', 'description': '', 'type': <DataType.FLOAT_VECTOR: 101>, 'params': {'dim': 256}}], 'enable_dynamic_field': True}
```

### Expected Behavior

Report errors:
```
(code=1, message=create duplicate collection with different parameters, collection: ***)>
```

### Steps To Reproduce

```python
from pymilvus import MilvusClient
milvus_client = MilvusClient()
dim = 256
collection_name = "binbin_milvus"
milvus_client.create_collection(collection_name, dim)
milvus_client.describe_collection("binbin_milvus")
dim = 128
milvus_client.create_collection(collection_name, dim)
milvus_client.describe_collection("binbin_milvus")
```

**Comment by binbinlv** [comment]
Low level will report errors:
```
>>> from pymilvus import CollectionSchema, FieldSchema
>>> from pymilvus import Collection
>>> from pymilvus import connections
>>> from pymilvus import DataType
>>> from pymilvus import Partition
>>> from pymilvus import utility
>>> connections.connect()
>>> dim = 128
>>> int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
>>> float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
>>> bool_field = FieldSchema(name="bool", dtype=DataType.BOOL)
>>> string_field = FieldSchema(name="string", dtype=DataType.VARCHAR, max_length=65535)
>>> json_field = FieldSchema(name="json_field", dtype=DataType.JSON)
>>> float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
>>> schema = CollectionSchema(fields=[int64_field, float_field, bool_field, json_field, float_vector])
>>> collection = Collection("test_search_collection_binbin_tmp_binbin_0", schema=schema)
>>> dim = 256
>>> float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
>>> schema = CollectionSchema(fields=[int64_field, float_field, bool_field, json_field, float_vector])
>>> collection = Collection("test_search_collection_binbin_tmp_binbin_0", schema=schema)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 113, in __init__
    raise SchemaNotReadyException(message=ExceptionsMessage.SchemaInconsistent)
pymilvus.exceptions.SchemaNotReadyException: <SchemaNotReadyException: (code=1, message=The collection already exist, but the schema is not the same as the schema passed in.)>
```

**Comment by binbinlv** [comment]
Verified, and fixed.

milvus: 2.2.0-20230608-b5714b0c
pymilvus: 2.2.10.dev1

```
>>> dim = 256
>>> collection_name = "binbin_milvus"
>>> milvus_client.create_collection(collection_name, dim)
>>> milvus_client.describe_collection("binbin_milvus")
{'auto_id': False, 'description': '', 'fields': [{'name': 'id', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'vector', 'description': '', 'type': <DataType.FLOAT_VECTOR: 101>, 'params': {'dim': 256}}], 'enable_dynamic_field': True}
>>> dim = 128
>>> milvus_client.create_collection(collection_name, dim)
RPC error: [create_collection], <MilvusException: (code=1, message=create duplicate collection with different parameters, collection: binbin_milvus)>, <Time:{'RPC start': '2023-06-08 06:58:46.956446', 'RPC error': '2023-06-08 06:58:46.958944'}>
Failed to create collection: binbin_milvus
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/milvus_client/milvus_client.py", line 101, in create_collection
    raise ex
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/milvus_client/milvus_client.py", line 97, in create_collection
    conn.create_collection(collection_name, schema, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 251, in create_collection
    raise MilvusException(status.error_code, status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=create duplicate collection with different parameters, collection: binbin_milvus)>
```

**Comment by binbinlv** [comment]
Verified in master branch, fixed.

milvus:master-20230608-d531b177
pymilvus:2.4.0.dev69

results:
```
>>> dim = 256
>>> collection_name = "binbin_milvus"
>>> milvus_client.create_collection(collection_name, dim)

>>> milvus_client.describe_collection("binbin_milvus")
{'auto_id': False, 'description': '', 'fields': [{'name': 'id', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'vector', 'description': '', 'type': <DataType.FLOAT_VECTOR: 101>, 'params': {'dim': 256}}], 'enable_dynamic_field': True}
>>>
>>> dim = 128
>>> milvus_client.create_collection(collection_name, dim)
RPC error: [create_collection], <MilvusException: (code=1, message=create duplicate collection with different parameters, collection: binbin_milvus)>, <Time:{'RPC start': '2023-06-08 10:02:37.213119', 'RPC error': '2023-06-08 10:02:37.215908'}>
Failed to create collection: binbin_milvus
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/milvus_client/milvus_client.py", line 101, in create_collection
    raise ex
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/milvus_client/milvus_client.py", line 97, in create_collection
    conn.create_collection(collection_name, schema, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 252, in create_collection
    raise MilvusException(status.error_code, status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=create duplicate collection with different parameters, collection: binbin_milvus)>
```
