### ISSUE TITLE
[Bug]: CPU usage of the datanode spikes every 150 seconds

### ISSUE THREAD

**Issue by bedivere2018** [milvus-io/milvus#24744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.9
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus
- OS(Ubuntu or CentOS): CentOS7.9
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

We found that data writes into milvus have become slow. Then we checked the monitoring and noticed that the CPU usage of the datanode spikes every 150 seconds. 
![image](https://github.com/milvus-io/milvus/assets/41724669/1d74f7d5-4fc3-422a-a93e-74f418d69613)

However, there are no error logs. What could be the reason for this?

Here is the config file for milvus.
[milvus.txt](https://github.com/milvus-io/milvus/files/11684631/milvus.txt)

**Comment by xiaofan-luan** [comment]
1. is there growing data in,  if the insertion rate is very stable, My guess is flush/compaction is happening at the backend.
2. is there chance you can generate a pprof while the cpu is high? it would be great to have the profiling details to figure out what happens
3. how many CPUs and Memories is each datanode? Did you see datanode memory increase at meantime? i don't see any chron interval configs of 150s or 150 * 1000 ms on milvus side.

Thanks for the observation! it's very useful

**Comment by xiaofan-luan** [comment]
@bedivere2018 
If you want to know how to do profiling, see here https://github.com/milvus-io/milvus/issues/13978 or contact me at xiaofan.luan@zilliz.com directly

**Comment by bedivere2018** [comment]
> 1. is there growing data in,  if the insertion rate is very stable, My guess is flush/compaction is happening at the backend.
> 2. is there chance you can generate a pprof while the cpu is high? it would be great to have the profiling details to figure out what happens
> 3. how many CPUs and Memories is each datanode? Did you see datanode memory increase at meantime? i don't see any chron interval configs of 150s or 150 * 1000 ms on milvus side.
> 
> Thanks for the observation! it's very useful

@xiaofan-luan Thanks for your reply.

1. When the problem occurred, we had already stopped writing data, but the CPU was still jumping regularly and had not come down.
2. Okay, let me study pprof first.
3. We use 5 physical machines deployed the Milvus cluster on Kubernetes, each with the same configuration of 96 CPU cores and 1T of memory.

currently our milvus contains 30 million entities stored in 17 different collections, and each collection has a 1500-dimension vector and 10 scalars.

**Comment by yanliang567** [comment]
@bedivere2018  According to the milvus.txt you attached, it says that you changed the segment max size to 2048. This could be the reason that even after you stopped insertion, datanode is still working to compact small segments to bigger ones. 
Also could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @bedivere2018

**Comment by bedivere2018** [comment]
> @bedivere2018 According to the milvus.txt you attached, it says that you changed the segment max size to 2048. This could be the reason that even after you stopped insertion, datanode is still working to compact small segments to bigger ones. Also could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
> 
> /assign @bedivere2018

@yanliang567  Here is the whole milvus logs.
[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/11685494/milvus-log.tar.gz)

If datanodes keep working to compact segments, how can I get the compact process and status? What should I do now?

**Comment by bedivere2018** [comment]
> @bedivere2018 If you want to know how to do profiling, see here #13978 or contact me at [xiaofan.luan@zilliz.com](mailto:xiaofan.luan@zilliz.com) directly

@xiaofan-luan @yanliang567 
I'm sorry, I have been too busy these days and haven't had time to continue researching the cpu problem of Milvus.
At first, I noticed that the CPU and memory usage of the datanode was very high, so I restarted one of the datanodes, and the memory usage returned to normal, but the CPU usage continued to spike.
Just now, I tried to access http://localhost:9091/debug/pprof/ inside the pod when the datanode's CPU usage was very high, and the content that I obtained is as follows:

/debug/pprof/

Types of profiles available:
Count	Profile
3359	allocs
0	block
0	cmdline
69206721	goroutine
3359	heap
0	mutex
0	profile
104	threadcreate
0	trace
full goroutine stack dump

When I noticed that the goroutine count was very high and tried to export it, the datanode pod may have restarted because of the large amount of data. Surprisingly, the CPU usage returned to normal after the restart.
Then I followed the same steps to export the goroutine in another datanode, and although the export failed, the datanode pod also restarted and the CPU usage returned to normal. The error message from datanode is as follows:

panic: DDNode forward delete msg failed, vChannel = by-dev-rootcoord-dml_3_441987761874201011v1, err = All attempts results:
│attempt #1:message send timeout: TimeoutError
│attempt #2:context canceled
│goroutine 141210847 [running]:
│github.com/milvus-io/milvus/internal/datanode.(*ddNode).Operate(0xdc3832ba80, {0xdd06c93430?, 0x1?, 0x1?})
│    /go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_dd_node.go:249 +0xfd6
│github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work(0xd73044cf50)
│    /go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:127 +0x2ac
│created by github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start
│    /go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:71 +0x79

And then I checked every component of Milvus and found that datacoord had an error as follows. 

[2023/06/09 08:05:04.158 +00:00] [ERROR] [datacoord/server.go:563] ["failed to handle timetick message"] [error="channel by-dev-rootcoord-dml_2_441987761874201011v0 is not watched on node 22"] [stack="github.com/milvus-io/milvus/internal/datacoord.(*Server).handleDataNodeTimetickMsgstream\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/server.go:563"]
[2023/06/09 08:05:04.161 +00:00] [ERROR] [datacoord/server.go:563] ["failed to handle timetick message"] [error="channel by-dev-rootcoord-dml_3_441987761874201011v1 is not watched on node 13"] [stack="github.com/milvus-io/milvus/internal/datacoord.(*Server).handleDataNodeTimetickMsgstream\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/server.go:563"]
[2023/06/09 08:05:05.740 +00:00] [ERROR] [datacoord/server.go:563] ["failed to handle timetick message"] [error="channel by-dev-rootcoord-dml_3_441987761874201011v1 is not watched on node 13"] [stack="github.com/milvus-io/milvus/internal/datacoord.(*Server).handleDataNodeTimetickMsgstream\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/server.go:563"]

I tried to forcefully restart datacoord, and fortunately, the restart was successful, so everything seemed to be back to normal.


It seems like the problem has been temporarily resolved, but I am not sure of the specific root cause. If the same issue arises again in the future, I will export the goroutine and take a closer look.

Thank you so much for your assistance!

**Comment by xiaofan-luan** [comment]
there seems to be many goroutines.
69206721 goroutine
is there any chance you get what those go routines are for?

**Comment by xiaofan-luan** [comment]
@bedivere2018 
Any progress?

**Comment by bedivere2018** [comment]
> @bedivere2018 Any progress?

@xiaofan-luan  I'm sorry, the CPU issue took a long time and when I tried to export pprof, the datanode restarted.By the time I checked it again, there was no data available. It's possible that the accumulation of too much data caused the issue. 
We can only hope that if the issue reoccurs, we will export the data earlier next time.

**Comment by bedivere2018** [comment]
> there seems to be many goroutines. 69206721 goroutine is there any chance you get what those go routines are for?

@xiaofan-luan 
The same issue has occurred again, and this time the pprof data has been exported. Please help me check what the problem is. Thank you.
[datanode2_pprof.zip](https://github.com/milvus-io/milvus/files/11783423/datanode2_pprof.zip)

**Comment by xiaofan-luan** [comment]
> > there seems to be many goroutines. 69206721 goroutine is there any chance you get what those go routines are for?
> 
> @xiaofan-luan The same issue has occurred again, and this time the pprof data has been exported. Please help me check what the problem is. Thank you. [datanode2_pprof.zip](https://github.com/milvus-io/milvus/files/11783423/datanode2_pprof.zip)



> > there seems to be many goroutines. 69206721 goroutine is there any chance you get what those go routines are for?
> 
> @xiaofan-luan The same issue has occurred again, and this time the pprof data has been exported. Please help me check what the problem is. Thank you. [datanode2_pprof.zip](https://github.com/milvus-io/milvus/files/11783423/datanode2_pprof.zip)

It seems that under your scenario, datacoord try to balance the channel but failed..
If you still the message attempt https://github.com/milvus-io/milvus/issues/1:message send timeout: TimeoutError, then I think the issue might be related to your MQ failed to do produce.
The slow operation causing flush happens repeatedly, which on the other side incurs too many goroutines

**Comment by xiaofan-luan** [comment]
Did you see frequent logs like
"sync segment for cp lag behind too much"
or 
"sync segment due to memory usage is too high"

**Comment by bedivere2018** [comment]
> Did you see frequent logs like "sync segment for cp lag behind too much" or "sync segment due to memory usage is too high"

No, I didn't see that.

What can I do to restore it to normal? 
I tried restarting two datanodes in sequence, 
but when I restarted datanode1, datanode1 returned to normal and the CPU issue shifted to datanode2. 
Then, when I restarted datanode2, datanode2 returned to normal and the CPU issue shifted back to datanode1.

I found some error logs in DataCoord.
[milvusdb-datacoord-7cfbcb95-f4984.log](https://github.com/milvus-io/milvus/files/11783906/milvusdb-datacoord-7cfbcb95-f4984.log)

**Comment by bigsheeper** [comment]
@bedivere2018 could you please offer us more detailed goroutine info by `curl http://xxx:9091/debug/pprof/goroutine?debug=2 > "$(date +"%FT%T").out`

**Comment by bedivere2018** [comment]
> @bedivere2018 could you please offer us more detailed goroutine info by `curl http://xxx:9091/debug/pprof/goroutine?debug=2 > "$(date +"%FT%T").out`

Sure, please take a look at the attachment.
[datanode2_pprof_20230619_1217.zip](https://github.com/milvus-io/milvus/files/11784010/datanode2_pprof_20230619_1217.zip)

**Comment by xiaofan-luan** [comment]
Thanks for the detailed info, I think I know what's happening, this will be fixed today and will be released in 2.2.11 this week

1. Coordinator try to release segment from node28, trigger a bunch of flush request.
2. but for some reason, the release timeout
<img width="1127" alt="image" src="https://github.com/milvus-io/milvus/assets/83447078/82eb19e3-78dc-4741-b25d-aed9b404308a">

Then something bad happend
1. Flush will always fail due to the datacoord check [2023/06/19 02:17:33.874 +00:00] [ERROR] [datacoord/server.go:563] ["failed to handle timetick message"] [error="channel by-dev-rootcoord-dml_0_441987761874142489v0 is not watched on node 28"] [stack="github.com/milvus-io/milvus/internal/datacoord.(*Server).handleDataNodeTimetickMsgstream\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/server.go:563"]

2. tryToReleaseFlowgraph

**Comment by xiaofan-luan** [comment]
Fix: 

If we see this special error:
channel by-dev-rootcoord-dml_0_441987761874142489v0 is not watched on node 28

Datanode should ignore flush error and move forward
