### ISSUE TITLE
[Bug]: Search iterator failed reporting `failed to create query plan`

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#24832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230608-41af0a98
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0.dev70
```

### Current Behavior

Search iterator failed reporting `failed to create query plan`.

```
>>> while True:
...     res = search_iterator.next()  # 翻下一页
...     if len(res[0]) == 0:
...         print("search iteration finished, close")
...         search_iterator.close()  # close
...         break
...     for i in range(len(res[0])):
...         print(res[0][i])
... 
id: 202, distance: 0.05072334036231041, entity: {'int64': 202}
id: 229, distance: 0.12542426586151123, entity: {'int64': 229}
id: 337, distance: 0.16815145313739777, entity: {'int64': 337}
id: 20, distance: 0.18820156157016754, entity: {'int64': 20}
id: 579, distance: 0.19118869304656982, entity: {'int64': 579}
RPC error: [search], <MilvusException: (code=1, message=failed to create query plan: cannot parse expression: 5 <= int64 < 995id not in [579, ], error: invalid expression: 5 <= int64 < 995id not in [579, ])>, <Time:{'RPC start': '2023-06-12 17:18:29.820582', 'RPC error': '2023-06-12 17:18:29.861589'}>
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/orm/iterator.py", line 152, in next
    res = self._conn.search(self._iterator_params['collection_name'],
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 599, in search
    return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 579, in _execute_search_requests
    raise pre_err
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 570, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=failed to create query plan: cannot parse expression: 5 <= int64 < 995id not in [579, ], error: invalid expression: 5 <= int64 < 995id not in [579, ])>
```

### Expected Behavior

pass

### Steps To Reproduce

```python
from pymilvus import CollectionSchema, FieldSchema, Collection, connections, DataType, Partition, utility
import random
connections.connect()

dim = 8
fields = [
    FieldSchema(name="pk", dtype=DataType.INT64, is_primary=True, description='pk'),
    FieldSchema(name="int64", dtype=DataType.INT64),
    FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
]
schema = CollectionSchema(fields=fields)
collection = Collection("test_search_iterator", schema=schema)
# utility.drop_collection('test_search_iterator')

nb = 1000
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
data = [
    [i for i in range(nb)],
    [i for i in range(nb)],
    vectors
]
collection.insert(data)

collection.create_index("float_vector", {"metric_type": "L2"})
collection.load()

limit = 5
expression = "5 <= int64 < 995"
search_params = {"metric_type": "L2", "params": {"nprobe": 10, "radius": 1.0}}
search_iterator = collection.search_iterator(vectors[:1], "float_vector", search_params, limit,
                                             output_fields=['int64'], expr=expression)
```

**Comment by shunjiezhao** [comment]
Hello,
this may construct search expr is not add 'and '
![image](https://github.com/milvus-io/milvus/assets/90906581/dfe1a5e3-d4d0-4cce-9577-f81a72d9f4c8)

https://github.com/milvus-io/pymilvus/blob/d3b98ca1052bc3ad31d757828b7abbe23eaea556/pymilvus/orm/iterator.py#LL180C1-L182C38

and in we don't add ',' in last id
https://github.com/milvus-io/pymilvus/blob/d3b98ca1052bc3ad31d757828b7abbe23eaea556/pymilvus/orm/iterator.py#LL174C1-L178C55

**Comment by MrPresent-Han** [comment]
Thanks for debugging, 
this should been fixed by https://github.com/milvus-io/pymilvus/pull/1534

**Comment by NicoYuan1986** [comment]
Thanks for your help! The issue is now fixed.
