### ISSUE TITLE
[Bug]: my-release-milvus-standalone Pod failing to start up

### ISSUE THREAD

**Issue by vishalt-verneek** [milvus-io/milvus#24878]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.9
- Milvus operator: v0.7.13
- Deployment mode(standalone or cluster): Standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I am trying to install Milvus Standalone on GCP K8 & the pod `my-release-milvus-standalone` is crashing.

### Expected Behavior

Not crash, I guess

### Steps To Reproduce

```markdown
I followed the following steps documented [here](https://milvus.io/docs/install_standalone-operator.md):
- `helm install milvus-operator \
  -n milvus-operator --create-namespace \
  --wait --wait-for-jobs \
  https://github.com/milvus-io/milvus-operator/releases/download/v0.7.13/milvus-operator-0.7.13.tgz`
- `kubectl apply -f https://raw.githubusercontent.com/milvus-io/milvus-operator/main/config/samples/milvus_default.yaml`
```

### Milvus Log

```
panic: strconv.Atoi: parsing "tcp://10.108.7.122:8080": invalid syntax goroutine 171 [running]: github.com/milvus-io/milvus/internal/util/paramtable.(*BaseTable).ParseIntWithDefault(0x5b8adc0, {0xc001302410, 0xa}, 0x3ff9db3?) /go/src/github.com/milvus-io/milvus/internal/util/paramtable/base_table.go:363 +0x8d github.com/milvus-io/milvus/internal/util/paramtable.(*grpcConfig).initPort(0x5b8adc0) /go/src/github.com/milvus-io/milvus/internal/util/paramtable/grpc_param.go:93 +0x53 github.com/milvus-io/milvus/internal/util/paramtable.(*grpcConfig).init(0x5b8adc0, {0x3ffe9cb, 0x5}) /go/src/github.com/milvus-io/milvus/internal/util/paramtable/grpc_param.go:78 +0xaa github.com/milvus-io/milvus/internal/util/paramtable.(*GrpcServerConfig).Init(0x5b8adc0, {0x3ffe9cb?, 0xc00123d120?}) /go/src/github.com/milvus-io/milvus/internal/util/paramtable/grpc_param.go:129 +0x25 github.com/milvus-io/milvus/internal/util/paramtable.(*GrpcServerConfig).InitOnce.func1() /go/src/github.com/milvus-io/milvus/internal/util/paramtable/grpc_param.go:124 +0x25 sync.(*Once).doSlow(0xc11a60f2568a76e5?, 0xbd5ebe1?) /usr/local/go/src/sync/once.go:68 +0xc2 sync.(*Once).Do(...) /usr/local/go/src/sync/once.go:59 github.com/milvus-io/milvus/internal/util/paramtable.(*GrpcServerConfig).InitOnce(0x13?, {0x3ffe9cb?, 0xbd5ebe1?}) /go/src/github.com/milvus-io/milvus/internal/util/paramtable/grpc_param.go:123 +0x5c github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).init(0xc000214630) /go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:311 +0x49 github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).Run(0xc00123df08?) /go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:295 +0x50 github.com/milvus-io/milvus/cmd/components.(*Proxy).Run(0x5ba1380?) /go/src/github.com/milvus-io/milvus/cmd/components/proxy.go:53 +0x2e
```

**Comment by haorenfsa** [comment]
I'll check it later, sorry for the delay
