### ISSUE TITLE
Random test failed caused by server socket closed frequently.

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#2487]
**Describe the bug**
more details about the issue:
https://github.com/milvus-io/pymilvus/issues/219

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)

**Screenshots**

**Additional context**

**Comment by BossZou** [comment]
It reproduced after server restart, I will check and find out the solutions.

**Comment by del-zhenwu** [comment]
```
18:19:34  2020-06-08:10:19:33,974 DEBUG    [client.py:245] Row count: 100626 in collection: <collection_95bvjuaw>
18:19:34  2020-06-08:10:19:33,974 INFO     [k8s_runner.py:728] collection_gruisivu
18:19:34  2020-06-08:10:19:33,974 INFO     [k8s_runner.py:729] flush
18:19:34  2020-06-08:10:19:34,8 INFO     [client.py:46] Milvus flush run in 0.03s
18:19:34  2020-06-08:10:19:34,9 INFO     [k8s_runner.py:728] collection_95bvjuaw
18:19:34  2020-06-08:10:19:34,9 INFO     [k8s_runner.py:729] insert_rand
18:19:34  2020-06-08:10:19:34,14 DEBUG    [client.py:241] (Status(code=0, message='Success!'), 100626)
18:19:34  2020-06-08:10:19:34,17 DEBUG    [client.py:245] Row count: 100626 in collection: <collection_95bvjuaw>
18:19:34  2020-06-08:10:19:34,17 INFO     [client.py:124] Insert length: 47
18:19:34  2020-06-08:10:19:34,21 INFO     [client.py:46] Milvus insert run in 0.0s
18:19:34  2020-06-08:10:19:34,46 INFO     [client.py:46] Milvus flush run in 0.02s

18:19:34  count_collection
18:19:34  Rpc error: <_MultiThreadedRendezvous of RPC that terminated with:
18:19:34  	status = StatusCode.UNAVAILABLE
18:19:34  	details = "Socket closed"
18:19:34  	debug_error_string = "{"created":"@1591611574.251892773","description":"Error received from peer ipv4:10.108.180.155:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}"
18:19:34  >
18:19:34  2020-06-08:10:19:34,254 ERROR    [grpc_handler.py:45] count_collection
18:19:34  Rpc error: <_MultiThreadedRendezvous of RPC that terminated with:
18:19:34  	status = StatusCode.UNAVAILABLE
18:19:34  	details = "Socket closed"
18:19:34  	debug_error_string = "{"created":"@1591611574.251892773","description":"Error received from peer ipv4:10.108.180.155:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}"
18:19:34  >
18:19:34  2020-06-08:10:19:34,254 DEBUG    [client.py:241] (Status(code=<StatusCode.UNAVAILABLE: (14, 'unavailable')>, message='Error occurred. Socket closed'), None)

18:19:44  count_collection
18:19:44  Request timeout: 
18:19:44  2020-06-08:10:19:44,256 ERROR    [grpc_handler.py:41] count_collection
18:19:44  Request timeout: 
18:19:44  2020-06-08:10:19:44,256 DEBUG    [client.py:245] Row count: 0 in collection: <collection_95bvjuaw>
18:19:44  2020-06-08:10:19:44,257 ERROR    [main.py:70] 
18:19:44  2020-06-08:10:19:44,259 ERROR    [main.py:71] Traceback (most recent call last):
18:19:44    File "main.py", line 68, in queue_worker
18:19:44      runner.run(run_type, collection)
18:19:44    File "/home/jenkins/agent/workspace/milvus-benchmark-0.10.0/milvus_benchmark/k8s_runner.py", line 732, in run
18:19:44      task_run()
18:19:44    File "/home/jenkins/agent/workspace/milvus-benchmark-0.10.0/milvus_benchmark/client.py", line 137, in insert_rand
18:19:44      assert count_before + insert_xb == self.count()
18:19:44  AssertionError
```

**Comment by del-zhenwu** [comment]
Count request timeout
```
[2020-06-08 18:19:34,033][INFO][WAL][operator()][wal_thread] record flush collection collection_95bvjuaw lsn 12992546664
[2020-06-08 18:19:34,056][INFO][WAL][CollectionFlushed][wal_thread] collection_95bvjuaw is flushed by lsn 12992546664
[2020-06-08 18:19:34,056][INFO][SERVER][Flush][grpcpp_sync_ser] Request [3033] Flush end.
[2020-06-08 18:19:34,057][INFO][SERVER][CountCollection][grpcpp_sync_ser] Request [3034] CountCollection begin.
~                                                                                                                                                                                                                                         
~                                                                                                                            
```

**Comment by del-zhenwu** [comment]
```
15:49:06  2020-06-09:07:49:05,905 DEBUG    [client.py:263] Row count: 1375800 in collection: <random_100m_1024_512_l2>
15:49:06  2020-06-09:07:49:05,905 DEBUG    [k8s_runner.py:157] Row count: 1375800
15:49:06  2020-06-09:07:49:05,940 INFO     [client.py:46] Milvus insert run in 0.03s
15:49:06  2020-06-09:07:49:06,40 DEBUG    [k8s_runner.py:156] 13866
15:49:06  2020-06-09:07:49:06,53 DEBUG    [client.py:259] (Status(code=0, message='Success!'), 1375800)
15:49:06  2020-06-09:07:49:06,67 DEBUG    [client.py:263] Row count: 1375800 in collection: <random_100m_1024_512_l2>
15:49:06  2020-06-09:07:49:06,67 DEBUG    [k8s_runner.py:157] Row count: 1375800
15:49:06  2020-06-09:07:49:06,98 INFO     [client.py:46] Milvus insert run in 0.03s
15:49:06  2020-06-09:07:49:06,198 DEBUG    [k8s_runner.py:156] 13867

15:49:16  count_collection
15:49:16  Request timeout: 
15:49:16  2020-06-09:07:49:16,199 ERROR    [grpc_handler.py:41] count_collection
15:49:16  Request timeout: 
15:49:16  2020-06-09:07:49:16,200 DEBUG    [client.py:259] (Status(code=1, message='Request timeout'), None)

15:49:26  count_collection
15:49:26  Request timeout: 
15:49:26  2020-06-09:07:49:26,202 ERROR    [grpc_handler.py:41] count_collection
15:49:26  Request timeout: 
15:49:26  2020-06-09:07:49:26,202 DEBUG    [client.py:263] Row count: 0 in collection: <random_100m_1024_512_l2>
15:49:26  2020-06-09:07:49:26,203 DEBUG    [k8s_runner.py:157] Row count: 0

15:49:31  insert
15:49:31  Rpc error: <_MultiThreadedRendezvous of RPC that terminated with:
15:49:31  	status = StatusCode.UNAVAILABLE
15:49:31  	details = "Connection reset by peer"
15:49:31  	debug_error_string = "{"created":"@1591688971.680683265","description":"Error received from peer ipv4:10.102.182.231:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Connection reset by peer","grpc_status":14}"
15:49:31  >
15:49:31  2020-06-09:07:49:31,682 ERROR    [grpc_handler.py:45] insert
15:49:31  Rpc error: <_MultiThreadedRendezvous of RPC that terminated with:
15:49:31  	status = StatusCode.UNAVAILABLE
15:49:31  	details = "Connection reset by peer"
15:49:31  	debug_error_string = "{"created":"@1591688971.680683265","description":"Error received from peer ipv4:10.102.182.231:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Connection reset by peer","grpc_status":14}"
15:49:31  >
15:49:31  2020-06-09:07:49:31,682 ERROR    [client.py:99] Error occurred. Connection reset by peer
15:49:31  2020-06-09:07:49:31,682 ERROR    [main.py:70] Status not ok
15:49:31  2020-06-09:07:49:31,685 ERROR    [main.py:71] Traceback (most recent call last):
15:49:31    File "main.py", line 68, in queue_worker
15:49:31      runner.run(run_type, collection)
15:49:31    File "/home/jenkins/agent/workspace/milvus-benchmark-0.10.0/milvus_benchmark/k8s_runner.py", line 158, in run
15:49:31      status, res = milvus_instance.insert(insert_vectors)
15:49:31    File "/home/jenkins/agent/workspace/milvus-benchmark-0.10.0/milvus_benchmark/client.py", line 44, in wrapper
15:49:31      result = func(*args, **kwargs)
15:49:31    File "/home/jenkins/agent/workspace/milvus-benchmark-0.10.0/milvus_benchmark/client.py", line 125, in insert
15:49:31      self.check_status(status)
15:49:31    File "/home/jenkins/agent/workspace/milvus-benchmark-0.10.0/milvus_benchmark/client.py", line 100, in check_status
15:49:31      raise Exception("Status not ok")
15:49:31  Exception: Status not ok
15:49:31  
15:49:31  2020-06-09:07:49:31,685 DEBUG    [k8s_runner.py:68] Start clean up: milvus-benchmark-test-d5bald2p
15:49:31  2020-06-09:07:49:31,685 DEBUG    [utils.py:334] helm uninstall -n milvus milvus-benchmark-test-d5bald2p
```

**Comment by BossZou** [comment]
Here is an article about grpc timeout:
https://grpc.io/blog/deadlines/

**Comment by del-zhenwu** [comment]
```
14:16:34  2020-06-12:06:16:34,59 ERROR    [utils.py:389] 1591942594.0590744
14:16:34  2020-06-12:06:16:34,75 ERROR    [utils.py:392] Running
14:16:34  2020-06-12:06:16:34,76 DEBUG    [client.py:60] milvus-benchmark-test-sbtnsidc.milvus.svc.cluster.local
14:16:34  2020-06-12:06:16:34,76 DEBUG    [client.py:61] 19530
14:16:34  2020-06-12:06:16:34,94 DEBUG    [client.py:72] Try connect times: 0, 0.02
14:16:34  2020-06-12:06:16:34,111 DEBUG    [client.py:60] milvus-benchmark-test-sbtnsidc.milvus.svc.cluster.local
14:16:34  2020-06-12:06:16:34,112 DEBUG    [client.py:61] 19530
14:16:34  2020-06-12:06:16:34,124 DEBUG    [client.py:72] Try connect times: 0, 0.01
14:16:34  2020-06-12:06:16:34,138 INFO     [k8s_runner.py:775] Loop time: 2
14:16:34  2020-06-12:06:16:34,138 INFO     [k8s_runner.py:782] collection_vmca7szl
14:16:34  2020-06-12:06:16:34,138 INFO     [k8s_runner.py:783] query_rand
14:16:41  [95m[2020-06-12 06:16:39,858-ERROR-milvus.client.grpc_handler]: 
14:16:41  get_vectors_by_ids
14:16:41  Rpc error: <_MultiThreadedRendezvous of RPC that terminated with:
14:16:41  	status = StatusCode.UNAVAILABLE
14:16:41  	details = "Socket closed"
14:16:41  	debug_error_string = "{"created":"@1591942599.855843229","description":"Error received from peer ipv4:10.99.243.17:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}"
14:16:41  >
14:16:41  	{'API start': '2020-06-12 06:16:34.555871', 'RPC start': '2020-06-12 06:16:34.555898', 'RPC error': '2020-06-12 06:16:39.857936'} (grpc_handler.py:49)[0m
14:16:41  2020-06-12:06:16:39,858 ERROR    [grpc_handler.py:49] 
14:16:41  get_vectors_by_ids
14:16:41  Rpc error: <_MultiThreadedRendezvous of RPC that terminated with:
14:16:41  	status = StatusCode.UNAVAILABLE
14:16:41  	details = "Socket closed"
14:16:41  	debug_error_string = "{"created":"@1591942599.855843229","description":"Error received from peer ipv4:10.99.243.17:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}"
14:16:41  >
14:16:41  	{'API start': '2020-06-12 06:16:34.555871', 'RPC start': '2020-06-12 06:16:34.555898', 'RPC error': '2020-06-12 06:16:39.857936'}
14:16:41  2020-06-12:06:16:39,858 ERROR    [client.py:99] Error occurred. Socket closed
14:16:41  2020-06-12:06:16:39,858 ERROR    [main.py:70] Status not ok
14:16:41  2020-06-12:06:16:39,860 ERROR    [main.py:71] Traceback (most recent call last):
14:16:41    File "main.py", line 68, in queue_worker
14:16:41      runner.run(run_type, collection)
14:16:41    File "/home/jenkins/agent/workspace/milvus-benchmark-0.10.0/milvus_benchmark/k8s_runner.py", line 786, in run
14:16:41      task_run()
14:16:41    File "/home/jenkins/agent/workspace/milvus-benchmark-0.10.0/milvus_benchmark/client.py", line 243, in query_rand
14:16:41      ids, X = self.get_rand_entities(nq)
14:16:41    File "/home/jenkins/agent/workspace/milvus-benchmark-0.10.0/milvus_benchmark/client.py", line 172, in get_rand_entities
14:16:41      self.check_status(status)
14:16:41    File "/home/jenkins/agent/workspace/milvus-benchmark-0.10.0/milvus_benchmark/client.py", line 100, in check_status
14:16:41      raise Exception("Status not ok")
14:16:41  Exception: Status not ok
```
```
[2020-06-12 14:16:34,569][DEBUG][SERVER][OnPostRecvInitialMetaData][grpcpp_sync_ser] milvus generate request_id: 69
[2020-06-12 14:16:34,570][DEBUG][ENGINE][MarkOngoingFileNoLock][reqsched_thread] Mark ongoing file:1591942162602201000 refcount:1
[2020-06-12 14:16:34,570][DEBUG][ENGINE][FilesByTypeEx][reqsched_thread] Get collection files by type. raw files:0 to_index files:0 backup files:0
[2020-06-12 14:16:34,570][DEBUG][SERVER][print][reqsched_thread] [CACHE CPU] [item count]: 0, [usage] 0MB, [capacity] 4096MB
[2020-06-12 14:16:34,570][DEBUG][ENGINE][GetVectorsByIdHelper][reqsched_thread] Getting vector by id in 1 files, id count = 89
[2020-06-12 14:16:35,255][DEBUG][ENGINE][PrintInfo][metric_thread] File reference information:
[2020-06-12 14:16:35,255][DEBUG][ENGINE][PrintInfo][metric_thread]      collection_vmca7szl: 1 files in use
[2020-06-12 14:16:36,361][DEBUG][ENGINE][PrintInfo][metric_thread] File reference information:
[2020-06-12 14:16:36,361][DEBUG][ENGINE][PrintInfo][metric_thread]      collection_vmca7szl: 1 files in use
[2020-06-12 14:16:37,510][DEBUG][ENGINE][PrintInfo][metric_thread] File reference information:
[2020-06-12 14:16:37,510][DEBUG][ENGINE][PrintInfo][metric_thread]      collection_vmca7szl: 1 files in use
[2020-06-12 14:16:38,614][DEBUG][ENGINE][PrintInfo][metric_thread] File reference information:
[2020-06-12 14:16:38,614][DEBUG][ENGINE][PrintInfo][metric_thread]      collection_vmca7szl: 1 files in use
[2020-06-12 14:16:39,720][DEBUG][ENGINE][PrintInfo][metric_thread] File reference information:
[2020-06-12 14:16:39,720][DEBUG][ENGINE][PrintInfo][metric_thread]      collection_vmca7szl: 1 files in use
```
```
[2020-06-12 14:16:34,151][INFO][SERVER][ShowCollectionInfo][grpcpp_sync_ser] Request [67] ShowCollectionInfo begin.
[2020-06-12 14:16:34,175][INFO][SERVER][ShowCollectionInfo][grpcpp_sync_ser] Request [67] ShowCollectionInfo end.
[2020-06-12 14:16:34,180][INFO][SERVER][GetVectorIDs][grpcpp_sync_ser] Request [68] GetVectorIDs begin.
[2020-06-12 14:16:34,307][INFO][SERVER][GetVectorIDs][grpcpp_sync_ser] Request [68] GetVectorIDs end.
[2020-06-12 14:16:34,569][INFO][SERVER][GetVectorsByID][grpcpp_sync_ser] Request [69] GetVectorsByID begin.
[2020-06-12 14:16:34,707][INFO][WAL][CollectionFlushed][wal_thread]  is flushed by lsn 0
[2020-06-12 14:16:35,707][INFO][WAL][CollectionFlushed][wal_thread]  is flushed by lsn 0
[2020-06-12 14:16:36,707][INFO][WAL][CollectionFlushed][wal_thread]  is flushed by lsn 0
[2020-06-12 14:16:37,708][INFO][WAL][CollectionFlushed][wal_thread]  is flushed by lsn 0
[2020-06-12 14:16:38,708][INFO][WAL][CollectionFlushed][wal_thread]  is flushed by lsn 0
[2020-06-12 14:16:39,708][INFO][WAL][CollectionFlushed][wal_thread]  is flushed by lsn 0
```

**Comment by BossZou** [comment]
> Server has received request.
> 
> ```
> 14:16:34  2020-06-12:06:16:34,59 ERROR    [utils.py:389] 1591942594.0590744
> 14:16:34  2020-06-12:06:16:34,75 ERROR    [utils.py:392] Running
> 14:16:34  2020-06-12:06:16:34,76 DEBUG    [client.py:60] milvus-benchmark-test-sbtnsidc.milvus.svc.cluster.local
> 14:16:34  2020-06-12:06:16:34,76 DEBUG    [client.py:61] 19530
> 14:16:34  2020-06-12:06:16:34,94 DEBUG    [client.py:72] Try connect times: 0, 0.02
> 14:16:34  2020-06-12:06:16:34,111 DEBUG    [client.py:60] milvus-benchmark-test-sbtnsidc.milvus.svc.cluster.local
> 14:16:34  2020-06-12:06:16:34,112 DEBUG    [client.py:61] 19530
> 14:16:34  2020-06-12:06:16:34,124 DEBUG    [client.py:72] Try connect times: 0, 0.01
> 14:16:34  2020-06-12:06:16:34,138 INFO     [k8s_runner.py:775] Loop time: 2
> 14:16:34  2020-06-12:06:16:34,138 INFO     [k8s_runner.py:782] collection_vmca7szl
> 14:16:34  2020-06-12:06:16:34,138 INFO     [k8s_runner.py:783] query_rand
> 14:16:41  �[95m[2020-06-12 06:16:39,858-ERROR-milvus.client.grpc_handler]: 
> 14:16:41  get_vectors_by_ids
> 14:16:41  Rpc error: <_MultiThreadedRendezvous of RPC that terminated with:
> 14:16:41  	status = StatusCode.UNAVAILABLE
> 14:16:41  	details = "Socket closed"
> 14:16:41  	debug_error_string = "{"created":"@1591942599.855843229","description":"Error received from peer ipv4:10.99.243.17:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}"
> 14:16:41  >
> 14:16:41  	{'API start': '2020-06-12 06:16:34.555871', 'RPC start': '2020-06-12 06:16:34.555898', 'RPC error': '2020-06-12 06:16:39.857936'} (grpc_handler.py:49)�[0m
> 14:16:41  2020-06-12:06:16:39,858 ERROR    [grpc_handler.py:49] 
> 14:16:41  get_vectors_by_ids
> 14:16:41  Rpc error: <_MultiThreadedRendezvous of RPC that terminated with:
> 14:16:41  	status = StatusCode.UNAVAILABLE
> 14:16:41  	details = "Socket closed"
> 14:16:41  	debug_error_string = "{"created":"@1591942599.855843229","description":"Error received from peer ipv4:10.99.243.17:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}"
> 14:16:41  >
> 14:16:41  	{'API start': '2020-06-12 06:16:34.555871', 'RPC start': '2020-06-12 06:16:34.555898', 'RPC error': '2020-06-12 06:16:39.857936'}
> 14:16:41  2020-06-12:06:16:39,858 ERROR    [client.py:99] Error occurred. Socket closed
> 14:16:41  2020-06-12:06:16:39,858 ERROR    [main.py:70] Status not ok
> 14:16:41  2020-06-12:06:16:39,860 ERROR    [main.py:71] Traceback (most recent call last):
> 14:16:41    File "main.py", line 68, in queue_worker
> 14:16:41      runner.run(run_type, collection)
> 14:16:41    File "/home/jenkins/agent/workspace/milvus-benchmark-0.10.0/milvus_benchmark/k8s_runner.py", line 786, in run
> 14:16:41      task_run()
> 14:16:41    File "/home/jenkins/agent/workspace/milvus-benchmark-0.10.0/milvus_benchmark/client.py", line 243, in query_rand
> 14:16:41      ids, X = self.get_rand_entities(nq)
> 14:16:41    File "/home/jenkins/agent/workspace/milvus-benchmark-0.10.0/milvus_benchmark/client.py", line 172, in get_rand_entities
> 14:16:41      self.check_status(status)
> 14:16:41    File "/home/jenkins/agent/workspace/milvus-benchmark-0.10.0/milvus_benchmark/client.py", line 100, in check_status
> 14:16:41      raise Exception("Status not ok")
> 14:16:41  Exception: Status not ok
> ```
> 
> ```
> [2020-06-12 14:16:34,569][DEBUG][SERVER][OnPostRecvInitialMetaData][grpcpp_sync_ser] milvus generate request_id: 69
> [2020-06-12 14:16:34,570][DEBUG][ENGINE][MarkOngoingFileNoLock][reqsched_thread] Mark ongoing file:1591942162602201000 refcount:1
> [2020-06-12 14:16:34,570][DEBUG][ENGINE][FilesByTypeEx][reqsched_thread] Get collection files by type. raw files:0 to_index files:0 backup files:0
> [2020-06-12 14:16:34,570][DEBUG][SERVER][print][reqsched_thread] [CACHE CPU] [item count]: 0, [usage] 0MB, [capacity] 4096MB
> [2020-06-12 14:16:34,570][DEBUG][ENGINE][GetVectorsByIdHelper][reqsched_thread] Getting vector by id in 1 files, id count = 89
> [2020-06-12 14:16:35,255][DEBUG][ENGINE][PrintInfo][metric_thread] File reference information:
> [2020-06-12 14:16:35,255][DEBUG][ENGINE][PrintInfo][metric_thread]      collection_vmca7szl: 1 files in use
> [2020-06-12 14:16:36,361][DEBUG][ENGINE][PrintInfo][metric_thread] File reference information:
> [2020-06-12 14:16:36,361][DEBUG][ENGINE][PrintInfo][metric_thread]      collection_vmca7szl: 1 files in use
> [2020-06-12 14:16:37,510][DEBUG][ENGINE][PrintInfo][metric_thread] File reference information:
> [2020-06-12 14:16:37,510][DEBUG][ENGINE][PrintInfo][metric_thread]      collection_vmca7szl: 1 files in use
> [2020-06-12 14:16:38,614][DEBUG][ENGINE][PrintInfo][metric_thread] File reference information:
> [2020-06-12 14:16:38,614][DEBUG][ENGINE][PrintInfo][metric_thread]      collection_vmca7szl: 1 files in use
> [2020-06-12 14:16:39,720][DEBUG][ENGINE][PrintInfo][metric_thread] File reference information:
> [2020-06-12 14:16:39,720][DEBUG][ENGINE][PrintInfo][metric_thread]      collection_vmca7szl: 1 files in use
> ```
> 
> ```
> [2020-06-12 14:16:34,151][INFO][SERVER][ShowCollectionInfo][grpcpp_sync_ser] Request [67] ShowCollectionInfo begin.
> [2020-06-12 14:16:34,175][INFO][SERVER][ShowCollectionInfo][grpcpp_sync_ser] Request [67] ShowCollectionInfo end.
> [2020-06-12 14:16:34,180][INFO][SERVER][GetVectorIDs][grpcpp_sync_ser] Request [68] GetVectorIDs begin.
> [2020-06-12 14:16:34,307][INFO][SERVER][GetVectorIDs][grpcpp_sync_ser] Request [68] GetVectorIDs end.
> [2020-06-12 14:16:34,569][INFO][SERVER][GetVectorsByID][grpcpp_sync_ser] Request [69] GetVectorsByID begin.
> [2020-06-12 14:16:34,707][INFO][WAL][CollectionFlushed][wal_thread]  is flushed by lsn 0
> [2020-06-12 14:16:35,707][INFO][WAL][CollectionFlushed][wal_thread]  is flushed by lsn 0
> [2020-06-12 14:16:36,707][INFO][WAL][CollectionFlushed][wal_thread]  is flushed by lsn 0
> [2020-06-12 14:16:37,708][INFO][WAL][CollectionFlushed][wal_thread]  is flushed by lsn 0
> [2020-06-12 14:16:38,708][INFO][WAL][CollectionFlushed][wal_thread]  is flushed by lsn 0
> [2020-06-12 14:16:39,708][INFO][WAL][CollectionFlushed][wal_thread]  is flushed by lsn 0
> ```

It seem like another issue occurred in server or network.

**Comment by BossZou** [comment]
https://zhuanlan.zhihu.com/p/88356559

**Comment by BossZou** [comment]
I performed a experiment that kill client procedure when server is handling a RPC request. I add some comments in `Search` request:
```
::grpc::Status
GrpcRequestHandler::Search(::grpc::ServerContext* context, const ::milvus::grpc::SearchParam* request,
                           ::milvus::grpc::TopKQueryResult* response) {
    std::cout << "Search start ..." << std::endl;
    sleep(20);

.....................
    std::cout << "Search end " << std::endl;

    return ::grpc::Status::OK;
```

**Comment by tinkerlin** [comment]
keep on tracking
@del-zhenwu

**Comment by del-zhenwu** [comment]
```
14:50:21  2020-06-17:06:50:20,891 INFO     [k8s_runner.py:786] delete_rand
14:50:21  2020-06-17:06:50:20,893 DEBUG    [client.py:261] (Status(code=0, message='Success!'), 100873)
14:50:21  2020-06-17:06:50:20,895 DEBUG    [client.py:265] Row count: 100873 in collection: <collection_q7wvlcxc>
14:50:21  2020-06-17:06:50:20,895 INFO     [client.py:189] collection_q7wvlcxc: length to delete: 17
14:50:21  2020-06-17:06:50:21,20 INFO     [client.py:46] Milvus delete run in 0.0s
14:50:21  
14:50:21  Addr [milvus-benchmark-test-o3vg0asw.milvus.svc.cluster.local:19530] flush
14:50:21  Rpc error: <_MultiThreadedRendezvous of RPC that terminated with:
14:50:21  	status = StatusCode.UNAVAILABLE
14:50:21  	details = "Socket closed"
14:50:21  	debug_error_string = "{"created":"@1592376621.504319288","description":"Error received from peer ipv4:10.106.21.124:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}"
14:50:21  >
14:50:21  	{'API start': '2020-06-17 06:50:21.020472', 'RPC start': '2020-06-17 06:50:21.020476', 'RPC error': '2020-06-17 06:50:21.505903'}
14:50:21  2020-06-17:06:50:21,506 ERROR    [grpc_handler.py:50] 
14:50:21  Addr [milvus-benchmark-test-o3vg0asw.milvus.svc.cluster.local:19530] flush
14:50:21  Rpc error: <_MultiThreadedRendezvous of RPC that terminated with:
14:50:21  	status = StatusCode.UNAVAILABLE
14:50:21  	details = "Socket closed"
14:50:21  	debug_error_string = "{"created":"@1592376621.504319288","description":"Error received from peer ipv4:10.106.21.124:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}"
14:50:21  >
14:50:21  	{'API start': '2020-06-17 06:50:21.020472', 'RPC start': '2020-06-17 06:50:21.020476', 'RPC error': '2020-06-17 06:50:21.505903'}
14:50:21  2020-06-17:06:50:21,506 ERROR    [client.py:99] Error occurred. Socket closed
14:50:21  2020-06-17:06:50:21,506 ERROR    [main.py:70] Status not ok
14:50:21  2020-06-17:06:50:21,508 ERROR    [main.py:71] Traceback (most recent call last):
14:50:21    File "main.py", line 68, in queue_worker
14:50:21      runner.run(run_type, collection)
14:50:21    File "/home/jenkins/agent/workspace/milvus-benchmark/milvus_benchmark/k8s_runner.py", line 789, in run
14:50:21      task_run()
14:50:21    File "/home/jenkins/agent/workspace/milvus-benchmark/milvus_benchmark/client.py", line 192, in delete_rand
14:50:21      self.flush()
14:50:21    File "/home/jenkins/agent/workspace/milvus-benchmark/milvus_benchmark/client.py", line 44, in wrapper
14:50:21      result = func(*args, **kwargs)
14:50:21    File "/home/jenkins/agent/workspace/milvus-benchmark/milvus_benchmark/client.py", line 203, in flush
14:50:21      self.check_status(status)
14:50:21    File "/home/jenkins/agent/workspace/milvus-benchmark/milvus_benchmark/client.py", line 100, in check_status
14:50:21      raise Exception("Status not ok")
14:50:21  Exception: Status not ok
```
```
/test/milvus/db_data_8/loop_stability/logs
milvus-20-06-17-14:47-debug.log
```

**Comment by yhmo** [comment]
May relate to #2692 which is already fixed by pr2715 in 0.10.1

**Comment by yhmo** [comment]
link to #2715 #2692

**Comment by del-zhenwu** [comment]
Restart pod failed sometimes.
```
➜  milvus_benchmark git:(0.10.1) kubectl logs -f milvus-benchmark-test-qg6behtq-writable-85968c84ff-mcl9s -n milvus -c milvus

    __  _________ _   ____  ______
   /  |/  /  _/ /| | / / / / / __/
  / /|_/ // // /_| |/ / /_/ /\ \
 /_/  /_/___/____/___/\____/___/

Welcome to use Milvus!
Milvus Release version: v0.10.1, built at 2020-07-10 08:56.39, with OpenBLAS library.
You are using Milvus CPU edition
Last commit id: d7c47a79058ee9cffe2e6aeec9a4b9b6c4dac9c5

Loading configuration from: /var/lib/milvus/conf/server_config.yaml
WARNNING: You are using SQLite as the meta data management, which can't be used in production. Please change it to MySQL!
Can't lock file: /test/milvus/db_data_11/loop_stability_1594391377/lock, due to permission denied.
Milvus server exit...
single instance lock db path failed.Can't lock file: /test/milvus/db_data_11/loop_stability_1594391377/lock, due to permission denied.
```

**Comment by XuanYang-cn** [comment]
### I've done three experiments:

Given a file **me.txt**
1. A **greedy process** locks me.txt for 30s and exit, a **pitty process** keeps trying to get the lock of me.txt. After greedy exit, pitty get the lock successfully.

2. A **greedy process** locks me.txt, and
 - kill greedy with ctrll-c;
 - kill greedy with kill -9;
 - kill greedy with kill -15;
A pitty process keeps trying to get the lock of me.txt. After greedy exit, pitty gets the lock successfully.

3. A **greedy process** locks me.txt, and
 - Let greedy be orphan process OR
 - Let greedy be zombie process
A **pitty** process keeps trying to get the lock of me.txt. When orphan-p or zombie-p finally exit, 
**pitty** process gets the lock successfully.

### conclusion
When **greedy** process doesn't exit, whether is orphan, zombie or normal process, **pitty** won't have the permission to get the file lock.

**Comment by del-zhenwu** [comment]
not reproduced recently
