### ISSUE TITLE
[Bug]: Nil reference panic while running test cases in rocksdb-based mq stream folder

### ISSUE THREAD

**Issue by caesarjuly** [milvus-io/milvus#24877]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):   rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Please refer to https://github.com/milvus-io/milvus/pull/24238#issuecomment-1586476952

### Expected Behavior

No error in test cases

### Steps To Reproduce

```markdown
Run the test cases in docker

source scripts/setenv.sh && go test -v ./internal/mq/msgstream/mqwrapper/rmq/ -count 1
```

### Milvus Log

```
=== RUN   TestRmqClient_CreateProducer
--- FAIL: TestRmqClient_CreateProducer (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10e19cf]

goroutine 445 [running]:
testing.tRunner.func1.2({0x1429ec0, 0x21290d0})
        /usr/local/go/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
        /usr/local/go/src/testing/testing.go:1529 +0x39f
panic({0x1429ec0, 0x21290d0})
        /usr/local/go/src/runtime/panic.go:884 +0x213
github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/rmq.TestRmqClient_CreateProducer(0xc00060d380?)
        /go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/rmq/rmq_client_test.go:68 +0xef
testing.tRunner(0xc00060d520, 0x167cd48)
        /usr/local/go/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1629 +0x3ea
FAIL    github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/rmq 2.582s
FAIL
```

**Comment by xiaofan-luan** [comment]
Good job and welcome to the community!
