### ISSUE TITLE
[Bug]: Insert as a tuple will raise error using default value

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#24890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230613-5c3b744b
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0.dev70
```

### Current Behavior

Insert as a tuple will raise error using default value.

```
[2023-06-14 16:17:40 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/zilliz/nico/milvus/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/Users/zilliz/nico/milvus/tests/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/orm/collection.py", line 438, in insert
    row_based = check_insert_or_upsert_is_row_based(data)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/orm/schema.py", line 385, in check_insert_or_upsert_is_row_based
    raise DataTypeNotSupportException(
pymilvus.exceptions.DataTypeNotSupportException: <DataTypeNotSupportException: (code=1, message=The type of data should be list or pandas.DataFrame or dict)>
 (api_request.py:39)
[2023-06-14 16:17:40 - ERROR - ci_test]: (api_response) : <DataTypeNotSupportException: (code=1, message=The type of data should be list or pandas.DataFrame or dict)> (api_request.py:40)
```

### Expected Behavior

support tuple

### Steps To Reproduce

```markdown
@pytest.mark.tags(CaseLabel.L2)
    @pytest.mark.parametrize("default_value", [[], None])
    def test_insert_tuple_using_default_value(self, default_value):
        """
        target: test insert with tuple
        method: insert with invalid tuple
        expected: insert successfully
        """
        fields = [cf.gen_int64_field(is_primary=True), cf.gen_float_vec_field(),
                  cf.gen_string_field(), cf.gen_float_field(default_value=np.float32(3.14))]
        schema = cf.gen_collection_schema(fields)
        collection_w = self.init_collection_wrap(schema=schema)
        vectors = cf.gen_vectors(ct.default_nb, ct.default_dim)
        int_values = [i for i in range(0, ct.default_nb)]
        string_values = ["abc" for i in range(ct.default_nb)]
        data = (int_values, vectors, string_values, default_value)
        collection_w.insert(data)
        assert collection_w.num_entities == ct.default_nb
        data = (int_values, vectors, string_values)
        collection_w.insert(data)
        assert collection_w.num_entities == ct.default_nb * 2
```

**Comment by NicoYuan1986** [comment]
Now tuple is not allowed. so close the issue.
