### ISSUE TITLE
[Bug]: Search failed with error `metric type not match: expected=, actual=L2: invalid parameter: channel=xxx: fail to access shard delegator: fail to search on all shard leaders` after querynode pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#24905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230614-56380ea7
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):kafka    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2023-06-14T19:17:38.621Z] [2023-06-14 19:16:46 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:56)

[2023-06-14T19:17:38.621Z] [2023-06-14 19:16:50 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)

[2023-06-14T19:17:38.621Z] [2023-06-14 19:16:50 - INFO - ci_test]: assert load: 4.031520843505859 (test_all_collections_after_chaos.py:113)

[2023-06-14T19:17:38.621Z] [2023-06-14 19:16:50 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.12244859134611578, 0.06579158525826927, 0.13097596373823822, 0.017804772100960344, 0.006299194743936003, 0.13567370747756205, 0.15311268045901044, 0.033681646912894006, 0.0997287114096215, 0.018451548019214885, 0.047613408063506314, 0.01878352523703067, 0.05357705764339764, 0.008088898583371135......, kwargs: {} (api_request.py:56)

[2023-06-14T19:17:38.622Z] [2023-06-14 19:16:50 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=attempt #0: fail to Search, QueryNode ID=15, reason=collection:442176469283512108, metric type not match: expected=, actual=L2: invalid parameter: channel=by-dev-rootcoord-dml_13_442176469283512108v1: fail to access shard delegator: fail to search on all shard leaders)>, <Time:{'RPC start': '2023-06-14 19:16:50.794623', 'RPC error': '2023-06-14 19:16:50.999694'}> (decorators.py:108)

[2023-06-14T19:17:38.622Z] [2023-06-14 19:16:51 - ERROR - ci_test]: Traceback (most recent call last):

[2023-06-14T19:17:38.622Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2023-06-14T19:17:38.622Z]     res = func(*args, **_kwargs)

[2023-06-14T19:17:38.622Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2023-06-14T19:17:38.622Z]     return func(*arg, **kwargs)

[2023-06-14T19:17:38.622Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 681, in search

[2023-06-14T19:17:38.622Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,

[2023-06-14T19:17:38.622Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-06-14T19:17:38.622Z]     raise e

[2023-06-14T19:17:38.622Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-06-14T19:17:38.622Z]     return func(*args, **kwargs)

[2023-06-14T19:17:38.622Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-06-14T19:17:38.622Z]     ret = func(self, *args, **kwargs)

[2023-06-14T19:17:38.622Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-06-14T19:17:38.622Z]     raise e

[2023-06-14T19:17:38.622Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-06-14T19:17:38.622Z]     return func(self, *args, **kwargs)

[2023-06-14T19:17:38.622Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 599, in search

[2023-06-14T19:17:38.622Z]     return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, **kwargs)

[2023-06-14T19:17:38.622Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 579, in _execute_search_requests

[2023-06-14T19:17:38.622Z]     raise pre_err

[2023-06-14T19:17:38.622Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 570, in _execute_search_requests

[2023-06-14T19:17:38.622Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2023-06-14T19:17:38.622Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=attempt #0: fail to Search, QueryNode ID=15, reason=collection:442176469283512108, metric type not match: expected=, actual=L2: invalid parameter: channel=by-dev-rootcoord-dml_13_442176469283512108v1: fail to access shard delegator: fail to search on all shard leaders)>

[2023-06-14T19:17:38.622Z]  (api_request.py:39)

[2023-06-14T19:17:38.622Z] [2023-06-14 19:16:51 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=attempt #0: fail to Search, QueryNode ID=15, reason=collection:442176469283512108, metric type not match: expected=, actual=L2: invalid parameter: channel=by-dev-rootcoord-dml_13_442176469283512108v1: fail to access shard delegator: fail to search on all shard lead...... (api_request.py:40)
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-cron/detail/chaos-test-kafka-cron/4881/pipeline

log:
[artifacts-querynode-pod-kill-4881-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/11752430/artifacts-querynode-pod-kill-4881-server-logs.tar.gz)
[artifacts-querynode-pod-kill-4881-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/11752431/artifacts-querynode-pod-kill-4881-pytest-logs.tar.gz)

**Comment by jiaoew1991** [comment]
<img width="1095" alt="image" src="https://github.com/milvus-io/milvus/assets/2297455/8edce2b0-f2a6-4df6-b709-9c8199dc15ce">

From the error message, it appears that the metric type of the collection is empty, while L2 was used in the query. These two are not equal.
