### ISSUE TITLE
Random test failed for id returned by searching is not expected

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#2494]
**Describe the bug**
Assertion failed in comparing with the result id returned by searching collection created with metric_type: IP. 

```
collection_mdqzjomu
{'index_type': 'flat', 'index_param': {'nlist': 2048}} (Status(code=0, message='Describe collection successfully!'), CollectionSchema(collection_name='collection_mdqzjomu', dimension=128, index_file_size=86, metric_type=<MetricType: L2>)) 100000
collection_9oujsngb
{'index_type': 'flat', 'index_param': {'nlist': 2048}} (Status(code=0, message='Describe collection successfully!'), CollectionSchema(collection_name='collection_9oujsngb', dimension=128, index_file_size=42, metric_type=<MetricType: IP>)) 100000
Loop time: 1
collection_9oujsngb query_rand
collection_9oujsngb, Search nq: 74, top_k: 79, nprobe: 58
Result(id=1591275255917109350, distance=1.0) 1591275255917109350
collection_9oujsngb delete_rand
Delete length: 97
Count after delete: 99903
collection_mdqzjomu compact
collection_mdqzjomu query_rand
collection_mdqzjomu, Search nq: 4, top_k: 27, nprobe: 25
Result(id=1591275254280062007, distance=0.0) 1591275254280062007
collection_9oujsngb insert_rand
collection_mdqzjomu compact
collection_9oujsngb delete_rand
Delete length: 27
Reset length: 26
Count after delete: 99903
collection_9oujsngb insert_rand
collection_mdqzjomu flush
collection_9oujsngb compact
collection_9oujsngb query_rand
collection_9oujsngb, Search nq: 83, top_k: 72, nprobe: 6
Result(id=1591275256327185088, distance=41.37975311279297) 1591275256327185088
collection_9oujsngb flush
collection_mdqzjomu insert_rand
collection_9oujsngb query_rand
Reset length: 90
collection_9oujsngb, Search nq: 94, top_k: 67, nprobe: 93
Result(id=1591275256327185000, distance=45.827205657958984) 1591275256327185000
collection_mdqzjomu delete_rand
Delete length: 99
Reset length: 18
Count after delete: 100000
collection_mdqzjomu query_rand
collection_mdqzjomu, Search nq: 61, top_k: 85, nprobe: 15
Result(id=1591275254280083321, distance=0.0) 1591275254280083321
collection_mdqzjomu flush
collection_9oujsngb insert_rand
collection_9oujsngb compact
collection_9oujsngb insert_rand
collection_mdqzjomu query_rand
collection_mdqzjomu, Search nq: 92, top_k: 56, nprobe: 90
Result(id=1591275254280104451, distance=0.0) 1591275254280104451
collection_mdqzjomu insert_rand
collection_9oujsngb compact
collection_9oujsngb delete_rand
Delete length: 40
Count after delete: 99993
collection_mdqzjomu delete_rand
Delete length: 56
Count after delete: 100025
collection_mdqzjomu compact
collection_9oujsngb compact
collection_9oujsngb flush
collection_mdqzjomu query_rand
collection_mdqzjomu, Search nq: 89, top_k: 7, nprobe: 80
Result(id=1591275254280274496, distance=0.0) 1591275254280274496
collection_mdqzjomu compact
collection_9oujsngb delete_rand
Delete length: 88
Count after delete: 99905
collection_mdqzjomu query_rand
Reset length: 25
collection_mdqzjomu, Search nq: 97, top_k: 25, nprobe: 13
Result(id=1591275256629120002, distance=0.0) 1591275256629120002
collection_9oujsngb flush
collection_9oujsngb compact
collection_mdqzjomu flush
collection_9oujsngb compact
collection_mdqzjomu delete_rand
Delete length: 68
Count after delete: 99957
collection_mdqzjomu query_rand
Reset length: 25
collection_mdqzjomu, Search nq: 99, top_k: 94, nprobe: 80
Result(id=1591275256629120002, distance=0.0) 1591275256629120002
collection_9oujsngb delete_rand
Delete length: 73
Count after delete: 99832
collection_9oujsngb flush
collection_9oujsngb flush
collection_mdqzjomu query_rand
collection_mdqzjomu, Search nq: 18, top_k: 40, nprobe: 39
Result(id=1591275254280108787, distance=0.0) 1591275254280108787
collection_9oujsngb delete_rand
Delete length: 87
Reset length: 2
Count after delete: 99830
collection_mdqzjomu query_rand
collection_mdqzjomu, Search nq: 10, top_k: 77, nprobe: 57
Result(id=1591275254280184883, distance=0.0) 1591275254280184883
collection_9oujsngb delete_rand
Delete length: 5
Count after delete: 99825
collection_mdqzjomu delete_rand
Delete length: 6
Count after delete: 99951
collection_9oujsngb query_rand
collection_9oujsngb, Search nq: 88, top_k: 33, nprobe: 3
Result(id=1591275255917052401, distance=0.9999999403953552) 1591275255917052401
collection_9oujsngb delete_rand
Delete length: 29
Count after delete: 99796
collection_mdqzjomu delete_rand
Delete length: 51
Count after delete: 99900
collection_9oujsngb insert_rand
collection_9oujsngb delete_rand
Delete length: 1
Count after delete: 99867
collection_9oujsngb insert_rand
collection_9oujsngb delete_rand
Delete length: 83
Count after delete: 99813
collection_mdqzjomu compact
collection_9oujsngb delete_rand
Delete length: 98
Count after delete: 99715
collection_9oujsngb flush
collection_9oujsngb flush
collection_9oujsngb flush
collection_9oujsngb query_rand
collection_9oujsngb, Search nq: 99, top_k: 16, nprobe: 52
Result(id=1591275257877997006, distance=5.564087867736816) 1591275255917236734
0
Traceback (most recent call last):
  File "test_loop.py", line 49, in <module>
    func()
  File "/home/zw/work/z/milvus_benchmark/client.py", line 225, in query_rand
    raise Exception("Query failed")
Exception: Query failed

```

**Steps/Code to reproduce behavior**
1. Two collections created with random metric_type, no index created
2. insert 100000 vectors into each collection
3. loop operation: random_insert/search/delete/compact/get entity/...
Assertion failed in comparing with the result id returned by random searching.

test.py
```
import time
import random
import logging
from client import MilvusClient
import utils


if __name__ == "__main__":
    milvus_instance = MilvusClient()
    milvus_instance.clean_db()
    pull_interval_seconds = 1000
    collection_num = 2
    dimension = 128
    insert_xb = 100000
    index_types = ['flat']
    index_param = {"nlist": 2048}
    collection_names = []
    milvus_instances_map = {}
    insert_vectors = [[random.random() for _ in range(dimension)] for _ in range(insert_xb)]
    for i in range(collection_num):
        name = utils.get_unique_name(prefix="collection_")
        print(name)
        collection_names.append(name)
        metric_type = random.choice(["l2", "ip"])
        index_file_size = random.randint(10, 100)
        milvus_instance.create_collection(name, dimension, index_file_size, metric_type)
        milvus_instance = MilvusClient(collection_name=name)
        index_type = random.choice(index_types)
        milvus_instance.create_index(index_type, index_param=index_param)
        insert_vectors = utils.normalize(metric_type, insert_vectors)
        milvus_instance.insert(insert_vectors)
        milvus_instance.flush()
        milvus_instances_map.update({name: milvus_instance})
        print(milvus_instance.describe_index(), milvus_instance.count())

    tasks = ["insert_rand", "delete_rand", "query_rand", "flush", "compact"]
    i = 1
    while True:
        print("Loop time: %d" % i)
        start_time = time.time()
        while time.time() - start_time < pull_interval_seconds:
            # choose collection
            tmp_collection_name = random.choice(collection_names)
            # choose task from task
            task_name = random.choice(tasks)
            print(tmp_collection_name, task_name)
            func = getattr(milvus_instances_map[tmp_collection_name], task_name)
            func()

```
client.py:
```
import sys
import pdb
import random
import logging
import json
import time, datetime
from multiprocessing import Process
from milvus import Milvus, IndexType, MetricType
import utils

logger = logging.getLogger("milvus_benchmark.client")

SERVER_HOST_DEFAULT = "127.0.0.1"
# SERVER_HOST_DEFAULT = "192.168.1.130"
SERVER_PORT_DEFAULT = 19530
INDEX_MAP = {
    "flat": IndexType.FLAT,
    "ivf_flat": IndexType.IVFLAT,
    "ivf_sq8": IndexType.IVF_SQ8,
    "nsg": IndexType.RNSG,
    "ivf_sq8h": IndexType.IVF_SQ8H,
    "ivf_pq": IndexType.IVF_PQ,
    "hnsw": IndexType.HNSW,
    "annoy": IndexType.ANNOY
}

METRIC_MAP = {
    "l2": MetricType.L2,
    "ip": MetricType.IP,
    "jaccard": MetricType.JACCARD,
    "hamming": MetricType.HAMMING,
    "sub": MetricType.SUBSTRUCTURE,
    "super": MetricType.SUPERSTRUCTURE
}

epsilon = 0.1

def time_wrapper(func):
    """
    This decorator prints the execution time for the decorated function.
    """
    def wrapper(*args, **kwargs):
        start = time.time()
        result = func(*args, **kwargs)
        end = time.time()
        logger.info("Milvus {} run in {}s".format(func.__name__, round(end - start, 2)))
        return result
    return wrapper


class MilvusClient(object):
    def __init__(self, collection_name=None, host=None, port=None, timeout=60):
        self._collection_name = collection_name
        try:
            start_time = time.time()
            if not host:
                host = SERVER_HOST_DEFAULT
            if not port:
                port = SERVER_PORT_DEFAULT
            logger.debug(host)
            logger.debug(port)
            # retry connect for remote server
            i = 0
            while time.time() < start_time + timeout:
                try:
                    self._milvus = Milvus(
                        host = host,
                        port = port,
                        try_connect = False,
                        pre_ping = False)
                    if self._milvus.server_status():
                        logger.debug("Try connect times: %d, %s" % (i, round(time.time() - start_time, 2)))
                        break
                except Exception as e:
                    logger.debug("Milvus connect failed: %d times" % i)
                    i = i + 1

            if time.time() > start_time + timeout:
                raise Exception("Server connect timeout")

        except Exception as e:
            raise e
        self._metric_type = None
        if self._collection_name:
            self._metric_type = self.describe()[1].metric_type
            self._dimension = self.describe()[1].dimension

    def __str__(self):
        return 'Milvus collection %s' % self._collection_name

    def check_status(self, status):
        if not status.OK():
            logger.error(status.message)
            raise Exception("Status not ok")

    def check_result_ids(self, result):
        for index, item in enumerate(result):
            if item[0].distance >= epsilon:
                logger.error(index)
                logger.error(item[0].distance)
                raise Exception("Distance wrong")

    def create_collection(self, collection_name, dimension, index_file_size, metric_type):
        if not self._collection_name:
            self._collection_name = collection_name
        if metric_type not in METRIC_MAP.keys():
            raise Exception("Not supported metric_type: %s" % metric_type)
        metric_type = METRIC_MAP[metric_type]
        create_param = {'collection_name': collection_name,
                 'dimension': dimension,
                 'index_file_size': index_file_size,
                 "metric_type": metric_type}
        status = self._milvus.create_collection(create_param)
        self.check_status(status)

    @time_wrapper
    def insert(self, X, ids=None):
        logger.info("Insert length: %d" % len(X))
        status, result = self._milvus.insert(self._collection_name, X, ids)
        self.check_status(status)
        return status, result

    def insert_rand(self):
        insert_xb = random.randint(1, 100)
        X = [[random.random() for _ in range(self._dimension)] for _ in range(insert_xb)]
        X = utils.normalize(self._metric_type, X)
        count_before = self.count()
        status, ids = self.insert(X)
        self.check_status(status)
        self.flush()
        assert count_before + insert_xb == self.count()

    def get_rand_ids(self, length):
        status, stats = self._milvus.get_collection_stats(self._collection_name)
        self.check_status(status)
        segments = stats["partitions"][0]["segments"]
        # random choice one segment
        while True:
            segment = random.choice(segments)
            stauts, segment_ids = self._milvus.list_id_in_segment(self._collection_name, segment["name"])
            self.check_status(status)
            if len(segment_ids):
                break
        if length >= len(segment_ids):
            print("Reset length: %d" % len(segment_ids))
            return segment_ids
        return random.sample(segment_ids, length)

    def get_rand_entities(self, length):
        ids = self.get_rand_ids(length)
        status, get_res = self._milvus.get_entity_by_id(self._collection_name, ids)
        self.check_status(status)
        return ids, get_res

    @time_wrapper
    def delete(self, ids):
        status = self._milvus.delete_entity_by_id(self._collection_name, ids)
        self.check_status(status)

    def delete_rand(self):
        delete_id_length = random.randint(1, 100)
        count_before = self.count()
        print("Delete length: %d" % delete_id_length)
        delete_ids = self.get_rand_ids(delete_id_length)
        self.delete(delete_ids)
        self.flush()
        print("Count after delete: %d" % self.count())
        status, get_res = self._milvus.get_entity_by_id(self._collection_name, delete_ids)
        self.check_status(status)
        for item in get_res:
            assert not item
        assert count_before - len(delete_ids) == self.count()

    @time_wrapper
    def flush(self):
        status = self._milvus.flush([self._collection_name])
        self.check_status(status)

    @time_wrapper
    def compact(self):
        status = self._milvus.compact(self._collection_name)
        self.check_status(status)

    @time_wrapper
    def create_index(self, index_type, index_param=None):
        index_type = INDEX_MAP[index_type]
        logger.info("Building index start, collection_name: %s, index_type: %s" % (self._collection_name, index_type))
        if index_param:
            logger.info(index_param)
        status = self._milvus.create_index(self._collection_name, index_type, index_param)
        self.check_status(status)

    def describe_index(self):
        status, result = self._milvus.get_index_info(self._collection_name)
        self.check_status(status)
        index_type = None
        for k, v in INDEX_MAP.items():
            if result._index_type == v:
                index_type = k
                break
        return {"index_type": index_type, "index_param": result._params}

    def drop_index(self):
        logger.info("Drop index: %s" % self._collection_name)
        return self._milvus.drop_index(self._collection_name)

    def query(self, X, top_k, search_param=None):
        status, result = self._milvus.search(self._collection_name, top_k, query_records=X, params=search_param)
        self.check_status(status)
        return result

    def query_rand(self):
        top_k = random.randint(1, 100)
        nq = random.randint(1, 100)
        nprobe = random.randint(1, 100)
        search_param = {"nprobe": nprobe}
        ids, X = self.get_rand_entities(nq)
        print("Search nq: %d, top_k: %d, nprobe: %d" % (nq, top_k, nprobe))
        status, search_res = self._milvus.search(self._collection_name, top_k, query_records=X, params=search_param)
        self.check_status(status)
        for i, item in enumerate(search_res):
            if item[0].id != ids[i]:
                print(i, item[0], ids[i])
                raise Exception("Query failed")

    # @time_wrapper
    # def query_ids(self, top_k, ids, search_param=None):
    #     status, result = self._milvus.search_by_id(self._collection_name, ids, top_k, params=search_param)
    #     self.check_result_ids(result)
    #     return result

    def count(self):
        row_count = self._milvus.count_entities(self._collection_name)[1]
        logger.debug("Row count: %d" % row_count)
        return row_count

    def drop(self, timeout=120, name=None):
        timeout = int(timeout)
        if name is None:
            name = self._collection_name
        logger.info("Start delete collection: %s" % name)
        status = self._milvus.drop_collection(name)
        self.check_status(status)
        i = 0
        while i < timeout:
            if self.count():
                time.sleep(1)
                i = i + 1
                continue
            else:
                break
        if i >= timeout:
            logger.error("Delete collection timeout")

    def describe(self):
        return self._milvus.get_collection_info(self._collection_name)

    def show_collections(self):
        return self._milvus.list_collections()

    def exists_collection(self, collection_name=None):
        if collection_name is None:
            collection_name = self._collection_name
        status, res = self._milvus.has_collection(collection_name)
        # self.check_status(status)
        return res

    def clean_db(self):
        collection_names = self.show_collections()[1]
        for name in collection_names:
            self.drop(name=name)

    @time_wrapper
    def preload_collection(self):
        status = self._milvus.load_collection(self._collection_name, timeout=3000)
        self.check_status(status)
        return status

    def get_server_version(self):
        status, res = self._milvus.server_version()
        return res

    def get_server_mode(self):
        return self.cmd("mode")

    def get_server_commit(self):
        return self.cmd("build_commit_id")

    def get_server_config(self):
        return json.loads(self.cmd("get_config *"))

    def get_mem_info(self):
        result = json.loads(self.cmd("get_system_info"))
        result_human = {
            # unit: Gb
            "memory_used": round(int(result["memory_used"]) / (1024*1024*1024), 2)
        }
        return result_human

    def cmd(self, command):
        status, res = self._milvus._cmd(command)
        logger.info("Server command: %s, result: %s" % (command, res))
        self.check_status(status)
        return res

```
utils.py
```
# -*- coding: utf-8 -*-
import os
import sys
import pdb
import time
import json
import datetime
import argparse
import threading
import logging
import string
import random
# import multiprocessing
# import numpy
# import psutil
import sklearn.preprocessing
import h5py
# import docker
from yaml import full_load, dump
import yaml
import tableprint as tp
from pprint import pprint


logger = logging.getLogger("milvus_benchmark.utils")

REGISTRY_URL = "registry.zilliz.com/milvus/engine"

class literal_str(str): pass

def change_style(style, representer):
    def new_representer(dumper, data):
        scalar = representer(dumper, data)
        scalar.style = style
        return scalar
    return new_representer

from yaml.representer import SafeRepresenter

# represent_str does handle some corner cases, so use that
# instead of calling represent_scalar directly
represent_literal_str = change_style('|', SafeRepresenter.represent_str)

yaml.add_representer(literal_str, represent_literal_str)


def normalize(metric_type, X):
    if metric_type == "ip":
        logger.info("Set normalize for metric_type: %s" % metric_type)
        X = sklearn.preprocessing.normalize(X, axis=1, norm='l2')
        X = X.tolist()
    elif metric_type in ["jaccard", "hamming", "sub", "super"]:
        tmp = []
        for index, item in enumerate(X):
            new_vector = bytes(np.packbits(item, axis=-1).tolist())
            tmp.append(new_vector)
        X = tmp
    return X

def get_unique_name(prefix=None):
    if prefix is None:
        prefix = "milvus-benchmark-test-"
    return prefix+"".join(random.choice(string.ascii_letters + string.digits) for _ in range(8)).lower()


def get_current_time():

```
**Expected behavior**

**Environment details**
0.10.0-cpu

**Screenshots**

**Additional context**

**Comment by del-zhenwu** [comment]
issue can be re-produced when the metric_type among the collections including IP.

**Comment by del-zhenwu** [comment]
invalid issue.
