### ISSUE TITLE
[Bug]: Search reports "metric type not match" error when using the new index with different metric type after dropping the old index

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#24957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 10.102.9.76
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):    all
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0.dev71
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Search reports "metric type not match" error when drop one index and create another index

```
>>> index_param = {"index_type": "IVF_FLAT", "metric_type": "L2", "params": {"nlist": 100}}
>>> collection.create_index("float_vector", index_param)
Status(code=0, message=)
>>>
>>> collection.load()
>>> import random
>>> res = collection.query(expr="int64 == 0", output_fields=["float_vector"])
>>> vector = res[0]["float_vector"]
>>> default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
>>> nq = 1
>>> limit = 10
>>> res = collection.search([vector], "float_vector", default_search_params, limit)
>>> res[0][0]
id: 0, distance: 0.0, entity: {}
>>> collection.release()
>>> collection.drop_index()
>>> index_param = {"index_type": "IVF_FLAT", "metric_type": "IP", "params": {"nlist": 100}}
>>> collection.create_index("float_vector", index_param)
Status(code=0, message=)
>>> collection.load()
>>> default_search_params = {"metric_type": "IP", "params": {"nprobe": 10}}
>>> res = collection.search([vector], "float_vector", default_search_params, limit)
RPC error: [search], <MilvusException: (code=1, message=attempt #0: fail to Search, QueryNode ID=1, reason=collection:442209745747491485, metric type not match: expected=L2, actual=IP: invalid parameter: channel=by-dev-rootcoord-dml_12_442209745747491485v0: fail to access shard delegator: fail to search on all shard leaders)>, <Time:{'RPC start': '2023-06-16 08:27:49.716886', 'RPC error': '2023-06-16 08:27:49.921733'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 682, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 599, in search
    return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 579, in _execute_search_requests
    raise pre_err
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 570, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=attempt #0: fail to Search, QueryNode ID=1, reason=collection:442209745747491485, metric type not match: expected=L2, actual=IP: invalid parameter: channel=by-dev-rootcoord-dml_12_442209745747491485v0: fail to access shard delegator: fail to search on all shard leaders)>
```

### Expected Behavior

Search successfully using the new index with new metric type

### Steps To Reproduce

```python
from pymilvus import CollectionSchema, FieldSchema
from pymilvus import Collection
from pymilvus import connections
from pymilvus import DataType
from pymilvus import Partition
import numpy as np
connections.connect()
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
dim = 128
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
schema = CollectionSchema(fields=[int64_field, float_vector])
collection = Collection("hello_milvus_binbin10", schema)

nb = 1000
rng = np.random.default_rng(seed=19530)
rows = [{"int64": i, "float_vector": rng.random((1, dim))[0]} for  i in range(0, nb)]
collection.insert(rows)
index_param = {"index_type": "IVF_FLAT", "metric_type": "L2", "params": {"nlist": 100}}
collection.create_index("float_vector", index_param)

collection.load()
import random
res = collection.query(expr="int64 == 0", output_fields=["float_vector"])
vector = res[0]["float_vector"]
default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
nq = 1
limit = 10
res = collection.search([vector], "float_vector", default_search_params, limit)
res[0][0]
collection.release()
collection.drop_index()
index_param = {"index_type": "IVF_FLAT", "metric_type": "IP", "params": {"nlist": 100}}
collection.create_index("float_vector", index_param)
collection.load()
default_search_params = {"metric_type": "IP", "params": {"nprobe": 10}}
res = collection.search([vector], "float_vector", default_search_params, limit)
```

**Comment by binbinlv** [comment]
It is good in 2.2.0: 2.2.0-20230616-307d687e

```
>>> from pymilvus import CollectionSchema, FieldSchema
>>> from pymilvus import Collection
>>> from pymilvus import connections
>>> from pymilvus import DataType
>>> from pymilvus import Partition
>>> import numpy as np
>>> connections.connect()
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
>>> dim = 128
>>> float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
>>> schema = CollectionSchema(fields=[int64_field, float_vector])
>>> collection = Collection("hello_milvus_binbin10", schema)
>>>
>>> nb = 1000
>>> rng = np.random.default_rng(seed=19530)
>>> rows = [{"int64": i, "float_vector": rng.random((1, dim))[0]} for  i in range(0, nb)]
>>> collection.insert(rows)
(insert count: 1000, delete count: 0, upsert count: 0, timestamp: 442212668254453764, success count: 1000, err count: 0)
>>> index_param = {"index_type": "IVF_FLAT", "metric_type": "L2", "params": {"nlist": 100}}
>>> collection.create_index("float_vector", index_param)
Status(code=0, message=)
>>>
>>> collection.load()
>>> import random
>>> res = collection.query(expr="int64 == 0", output_fields=["float_vector"])
>>> vector = res[0]["float_vector"]
>>> default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
>>>
>>>
>>> nq = 1
>>> limit = 10
>>> res = collection.search([vector], "float_vector", default_search_params, limit)
>>> res[0][0]
id: 0, distance: 0.0, entity: {}
>>> collection.release()
>>> collection.drop_index()
>>> index_param = {"index_type": "IVF_FLAT", "metric_type": "IP", "params": {"nlist": 100}}
>>> collection.create_index("float_vector", index_param)
Status(code=0, message=)
>>> collection.load()
>>> default_search_params = {"metric_type": "IP", "params": {"nprobe": 10}}
>>> res = collection.search([vector], "float_vector", default_search_params, limit)
>>>
>>>
>>> res[0].ids
[0, 818, 497, 415, 518, 30, 889, 428, 735, 744]
```
