### ISSUE TITLE
[Bug]: DataCorrd Unable to create broker thread

### ISSUE THREAD

**Issue by xTerry** [milvus-io/milvus#24970]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:V2.2.8
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.2.1 
- OS(Ubuntu or CentOS): Centos7
- CPU/Memory: 192G *3
- GPU: no
- Others:
```

### Current Behavior

When the data volume reached 280 million, there was a problem of insufficient memory during program startup. After deleting 200 million feature volumes (through ATTU and SDK deletion), the datacoord still failed to start. Please refer to the log for details

![error](https://github.com/milvus-io/milvus/assets/2304854/ea4cc6f2-2a0b-4e0a-bb97-e85a9e4220eb)
<img width="797" alt="3c4275336d0af6abecbe525ba06d12d" src="https://github.com/milvus-io/milvus/assets/2304854/09c9996f-aaf2-40a5-87fc-dc673490ff03">
<img width="874" alt="23e9f17683793cb5c35cb65928d89f2" src="https://github.com/milvus-io/milvus/assets/2304854/2eafae36-fb86-415c-9214-4602c661d030">
<img width="887" alt="47ed39823a0fe75abe4d883bfc6a328" src="https://github.com/milvus-io/milvus/assets/2304854/01340381-7220-4ec5-b811-8f925a74d104">

logs:
err: find no available datacoord, check datacoord state , /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:329 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall /go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:284 github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).GetCollectionStatistics /go/src/github.com/milvus-io/milvus/internal/proxy/task_statistic.go:662 github.com/milvus-io/milvus/internal/proxy.(*getCollectionStatisticsTask).Execute /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:470 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:499 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop /usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit

### Milvus Log

[2023/06/18 00:58:54.584 +00:00] [WARN] [datacoord/metrics_info.go:167] ["invalid metrics of DataNode was found"] [error="err: failed to connect 10.38.38.226:21124, reason: context deadline exceeded\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:329 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n/go/src/github.com/milvus-io/milvus/internal/distributed/datanode/client/client.go:205 github.com/milvus-io/milvus/internal/distributed/datanode/client.(*Client).GetMetrics\n/go/src/github.com/milvus-io/milvus/internal/datacoord/metrics_info.go:165 github.com/milvus-io/milvus/internal/datacoord.(*Server).getDataNodeMetrics\n/go/src/github.com/milvus-io/milvus/internal/datacoord/metrics_info.go:80 github.com/milvus-io/milvus/internal/datacoord.(*Server).getSystemInfoMetrics\n/go/src/github.com/milvus-io/milvus/internal/datacoord/services.go:1024 github.com/milvus-io/milvus/internal/datacoord.(*Server).GetMetrics\n/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:340 github.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).GetMetrics\n/go/src/github.com/milvus-io/milvus/internal/proto/datapb/data_coord.pb.go:6539 github.com/milvus-io/milvus/internal/proto/datapb._DataCoord_GetMetrics_Handler.func1\n/go/src/github.com/milvus-io/milvus/internal/util/logutil/grpc_interceptor.go:22 github.com/milvus-io/milvus/internal/util/logutil.UnaryTraceLoggerInterceptor\n/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n"]
[2023/06/18 00:58:58.667 +00:00] [ERROR] [grpcclient/client.go:330] ["ClientBase ReCall grpc second call get error"] [role=datanode] [error="err: failed to connect 10.38.38.226:21124, reason: context deadline exceeded\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:329 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n/go/src/github.com/milvus-io/milvus/internal/distributed/datanode/client/client.go:236 github.com/milvus-io/milvus/internal/distributed/datanode/client.(*Client).GetCompactionState\n/go/src/github.com/milvus-io/milvus/internal/datacoord/session_manager.go:250 github.com/milvus-io/milvus/internal/datacoord.(*SessionManager).GetCompactionState.func1\n/usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit\n"] [stack="github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:330\ngithub.com/milvus-io/milvus/internal/distributed/datanode/client.(*Client).GetCompactionState\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datanode/client/client.go:236\ngithub.com/milvus-io/milvus/internal/datacoord.(*SessionManager).GetCompactionState.func1\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/session_manager.go:250"]
[2023/06/18 00:58:58.667 +00:00] [WARN] [grpclog/grpclog.go:46] ["[core][Channel #40 SubChannel #41] grpc: addrConn.createTransport failed to connect to {\n  \"Addr\": \"10.38.38.226:21124\",\n  \"ServerName\": \"10.38.38.226:21124\",\n  \"Attributes\": null,\n  \"BalancerAttributes\": null,\n  \"Type\": 0,\n  \"Metadata\": null\n}. Err: connection error: desc = \"transport: Error while dialing dial tcp 10.38.38.226:21124: operation was canceled\""]
[2023/06/18 00:59:03.668 +00:00] [WARN] [grpclog/grpclog.go:46] ["[core][Channel #42 SubChannel #43] grpc: addrConn.createTransport failed to connect to {\n  \"Addr\": \"10.38.38.226:21124\",\n  \"ServerName\": \"10.38.38.226:21124\",\n  \"Attributes\": null,\n  \"BalancerAttributes\": null,\n  \"Type\": 0,\n  \"Metadata\": null\n}. Err: connection error: desc = \"transport: Error while dialing dial tcp 10.38.38.226:21124: i/o timeout\""]
[2023/06/18 00:59:03.668 +00:00] [WARN] [grpcclient/client.go:318] ["ClientBase ReCall grpc first call get error"] [role=datanode] [error="err: failed to connect 10.38.38.226:21124, reason: context deadline exceeded\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:317 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n/go/src/github.com/milvus-io/milvus/internal/distributed/datanode/client/client.go:205 github.com/milvus-io/milvus/internal/distributed/datanode/client.(*Client).GetMetrics\n/go/src/github.com/milvus-io/milvus/internal/datacoord/metrics_info.go:165 github.com/milvus-io/milvus/internal/datacoord.(*Server).getDataNodeMetrics\n/go/src/github.com/milvus-io/milvus/internal/datacoord/metrics_info.go:80 github.com/milvus-io/milvus/internal/datacoord.(*Server).getSystemInfoMetrics\n/go/src/github.com/milvus-io/milvus/internal/datacoord/services.go:1024 github.com/milvus-io/milvus/internal/datacoord.(*Server).GetMetrics\n/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:340 github.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).GetMetrics\n/go/src/github.com/milvus-io/milvus/internal/proto/datapb/data_coord.pb.go:6539 github.com/milvus-io/milvus/internal/proto/datapb._DataCoord_GetMetrics_Handler.func1\n/go/src/github.com/milvus-io/milvus/internal/util/logutil/grpc_interceptor.go:22 github.com/milvus-io/milvus/internal/util/logutil.UnaryTraceLoggerInterceptor\n/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n"]
[2023/06/18 00:59:08.668 +00:00] [WARN] [grpclog/grpclog.go:46] ["[core][Channel #47 SubChannel #48] grpc: addrConn.createTransport failed to connect to {\n  \"Addr\": \"10.38.38.226:21124\",\n  \"ServerName\": \"10.38.38.226:21124\",\n  \"Attributes\": null,\n  \"BalancerAttributes\": null,\n  \"Type\": 0,\n  \"Metadata\": null\n}. Err: connection error: desc = \"transport: Error while dialing dial tcp 10.38.38.226:21124: i/o timeout\""]
[2023/06/18 00:59:08.668 +00:00] [WARN] [grpcclient/client.go:318] ["ClientBase ReCall grpc first call get error"] [role=datanode] [error="err: failed to connect 10.38.38.226:21124, reason: context deadline exceeded\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:317 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n/go/src/github.com/milvus-io/milvus/internal/distributed/datanode/client/client.go:236 github.com/milvus-io/milvus/internal/distributed/datanode/client.(*Client).GetCompactionState\n/go/src/github.com/milvus-io/milvus/internal/datacoord/session_manager.go:250 github.com/milvus-io/milvus/internal/datacoord.(*SessionManager).GetCompactionState.func1\n/usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit\n"]
[2023/06/18 00:59:08.668 +00:00] [ERROR] [grpcclient/client.go:330] ["ClientBase ReCall grpc second call get error"] [role=datanode] [error="err: failed to connect 10.38.38.226:21124, reason: context deadline exceeded\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:329 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n/go/src/github.com/milvus-io/milvus/internal/distributed/datanode/client/client.go:205 github.com/milvus-io/milvus/internal/distributed/datanode/client.(*Client).GetMetrics\n/go/src/github.com/milvus-io/milvus/internal/datacoord/metrics_info.go:165 github.com/milvus-io/milvus/internal/datacoord.(*Server).getDataNodeMetrics\n/go/src/github.com/milvus-io/milvus/internal/datacoord/metrics_info.go:80 github.com/milvus-io/milvus/internal/datacoord.(*Server).getSystemInfoMetrics\n/go/src/github.com/milvus-io/milvus/internal/datacoord/services.go:1024 github.com/milvus-io/milvus/internal/datacoord.(*Server).GetMetrics\n/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:340 github.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).GetMetrics\n/go/src/github.com/milvus-io/milvus/internal/proto/datapb/data_coord.pb.go:6539 github.com/milvus-io/milvus/internal/proto/datapb._DataCoord_GetMetrics_Handler.func1\n/go/src/github.com/milvus-io/milvus/internal/util/logutil/grpc_interceptor.go:22 github.com/milvus-io/milvus/internal/util/logutil.UnaryTraceLoggerInterceptor\n/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n"] [stack="github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:330\ngithub.com/milvus-io/milvus/internal/distributed/datanode/client.(*Client).GetMetrics\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datanode/client/client.go:205\ngithub.com/milvus-io/milvus/internal/datacoord.(*Server).getDataNodeMetrics\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/metrics_info.go:165\ngithub.com/milvus-io/milvus/internal/datacoord.(*Server).getSystemInfoMetrics\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/metrics_info.go:80\ngithub.com/milvus-io/milvus/internal/datacoord.(*Server).GetMetrics\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/services.go:1024\ngithub.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).GetMetrics\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:340\ngithub.com/milvus-io/milvus/internal/proto/datapb._DataCoord_GetMetrics_Handler.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proto/datapb/data_coord.pb.go:6539\ngithub.com/milvus-io/milvus/internal/util/logutil.UnaryTraceLoggerInterceptor\n\t/go/src/github.com/milvus-io/milvus/internal/util/logutil/grpc_interceptor.go:22\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34\ngithub.com/milvus-io/milvus/internal/proto/datapb._DataCoord_GetMetrics_Handler\n\t/go/src/github.com/milvus-io/milvus/internal/proto/datapb/data_coord.pb.go:6541\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1283\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1620\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:922"]
[2023/06/18 00:59:08.668 +00:00] [WARN] [datacoord/metrics_info.go:167] ["invalid metrics of DataNode was found"] [error="err: failed to connect 10.38.38.226:21124, reason: context deadline exceeded\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:329 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n/go/src/github.com/milvus-io/milvus/internal/distributed/datanode/client/client.go:205 github.com/milvus-io/milvus/internal/distributed/datanode/client.(*Client).GetMetrics\n/go/src/github.com/milvus-io/milvus/internal/datacoord/metrics_info.go:165 github.com/milvus-io/milvus/internal/datacoord.(*Server).getDataNodeMetrics\n/go/src/github.com/milvus-io/milvus/internal/datacoord/metrics_info.go:80 github.com/milvus-io/milvus/internal/datacoord.(*Server).getSystemInfoMetrics\n/go/src/github.com/milvus-io/milvus/internal/datacoord/services.go:1024 github.com/milvus-io/milvus/internal/datacoord.(*Server).GetMetrics\n/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:340 github.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).GetMetrics\n/go/src/github.com/milvus-io/milvus/internal/proto/datapb/data_coord.pb.go:6539 github.com/milvus-io/milvus/internal/proto/datapb._DataCoord_GetMetrics_Handler.func1\n/go/src/github.com/milvus-io/milvus/internal/util/logutil/grpc_interceptor.go:22 github.com/milvus-io/milvus/internal/util/logutil.UnaryTraceLoggerInterceptor\n/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n"]
[2023/06/18 00:59:08.668 +00:00] [WARN] [datacoord/metrics_info.go:167] ["invalid metrics of DataNode was found"] [error="context deadline exceeded"]
%2|1687049948.780|THREAD|dc1#consumer-2478| [thrd:app]: Unable to create broker thread
%2|1687049948.780|THREAD|dc1#consumer-2478| [thrd:app]: Unable to create broker thread
%2|1687049948.780|THREAD|dc1#consumer-2479| [thrd:app]: Unable to create broker thread
milvus: rdkafka_broker.c:5754: rd_kafka_broker_t *rd_kafka_broker_add_logical(rd_kafka_t *, const char *): Assertion `rkb && *"failed to create broker thread"' failed.
SIGABRT: abort
PC=0x7f142e69100b m=21 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 14136 [syscall]:
runtime.cgocall(0x2f5c2d0, 0xc00f494808)
	/usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc00f4947e0 sp=0xc00f4947a8 pc=0x13c537c
github.com/confluentinc/confluent-kafka-go/kafka._Cfunc_rd_kafka_new(0x1, 0x7ef97990f000, 0x7ef58274a200, 0x100)
	_cgo_gotypes.go:2655 +0x4d fp=0xc00f494808 sp=0xc00f4947e0 pc=0x25e902d
github.com/confluentinc/confluent-kafka-go/kafka.NewConsumer.func3(0x7ef97990f000, 0x7ef58274a200?)
	/go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.9.1/kafka/consumer.go:517 +0x65 fp=0xc00f494848 sp=0xc00f494808 pc=0x25f0e05
github.com/confluentinc/confluent-kafka-go/kafka.NewConsumer(0xc0124d1cd0)
	/go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.9.1/kafka/consumer.go:517 +0x36b fp=0xc00f494af0 sp=0xc00f494848 pc=0x25f06eb
github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/kafka.(*Consumer).createKafkaConsumer(0xc014f79d40)
	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/kafka/kafka_consumer.go:97 +0x3d fp=0xc00f494c00 sp=0xc00f494af0 pc=0x2605d3d
github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/kafka.newKafkaConsumer(0xc0124d1cd0, {0xc00ded2b70, 0x16}, {0xc0151d6ec0, 0x40}, 0x2)
	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/kafka/kafka_consumer.go:39 +0x15a fp=0xc00f4950a8 sp=0xc00f494c00 pc=0x260501a
github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/kafka.(*kafkaClient).Subscribe(0x3c34780?, {{0xc00ded2b70, 0x16}, {0xc0151d6ec0, 0x40}, 0x2, 0xffffffffffffffff})
	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/kafka/kafka_client.go:187 +0x105 fp=0xc00f495118 sp=0xc00f4950a8 pc=0x2604725
github.com/milvus-io/milvus/internal/mq/msgstream.(*mqMsgStream).AsConsumer.func1()
	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_msgstream.go:145 +0xf9 fp=0xc00f4951e8 sp=0xc00f495118 pc=0x2642bf9
github.com/milvus-io/milvus/internal/util/retry.Do({0x420af48, 0xc00005a178}, 0xc00f495438, {0xc00f495420, 0x3, 0x0?})
	/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:42 +0x110 fp=0xc00f495380 sp=0xc00f4951e8 pc=0x1fd35b0
github.com/milvus-io/milvus/internal/mq/msgstream.(*mqMsgStream).AsConsumer(0xc0153e9980, {0xc01540d260?, 0x1, 0x420af10?}, {0xc0151d6ec0, 0x40}, 0x2)
	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_msgstream.go:165 +0x205 fp=0xc00f4954f8 sp=0xc00f495380 pc=0x2642805
github.com/milvus-io/milvus/internal/mq/msgstream.(*KmsFactory).NewMsgStreamDisposer.func1({0xc01540d260, 0x1, 0x1}, {0xc0151d6ec0, 0x40})
	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_factory.go:240 +0x93 fp=0xc00f495550 sp=0xc00f4954f8 pc=0x2641b73
github.com/milvus-io/milvus/internal/mq/msgstream.UnsubscribeChannels({0x420af10, 0xc000702380}, {0x7f13388b5400, 0xc0008e2b40}, {0xc0151d6ec0, 0x40}, {0xc01540d260, 0x1, 0x1})
	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/msgstream_util.go:30 +0x2aa fp=0xc00f495768 sp=0xc00f495550 pc=0x264de4a
github.com/milvus-io/milvus/internal/datacoord.(*ChannelManager).unsubAttempt(0xc0009209c0, 0x47c?)
	/go/src/github.com/milvus-io/milvus/internal/datacoord/channel_manager.go:421 +0xdb fp=0xc00f495840 sp=0xc00f495768 pc=0x26ca19b
github.com/milvus-io/milvus/internal/datacoord.(*ChannelManager).DeleteNode(0xc0009209c0, 0x47c)
	/go/src/github.com/milvus-io/milvus/internal/datacoord/channel_manager.go:371 +0xe5 fp=0xc00f495a70 sp=0xc00f495840 pc=0x26c99a5
github.com/milvus-io/milvus/internal/datacoord.(*Cluster).UnRegister(0xc00e270ae0, 0xc0131ca198)
	/go/src/github.com/milvus-io/milvus/internal/datacoord/cluster.go:73 +0x3f fp=0xc00f495ab0 sp=0xc00f495a70 pc=0x26d38df
github.com/milvus-io/milvus/internal/datacoord.(*Server).handleSessionEvent(0xc00056d860, {0xc0020a5f3c?, 0xc011d3d600?}, 0xc00f2780f0)
	/go/src/github.com/milvus-io/milvus/internal/datacoord/server.go:771 +0x2c6 fp=0xc00f495f08 sp=0xc00f495ab0 pc=0x2710c66
github.com/milvus-io/milvus/internal/datacoord.(*Server).watchService(0xc00056d860, {0x420af10, 0xc011d3d600})
	/go/src/github.com/milvus-io/milvus/internal/datacoord/server.go:719 +0x1a5 fp=0xc00f495fb8 sp=0xc00f495f08 pc=0x2710665
github.com/milvus-io/milvus/internal/datacoord.(*Server).startWatchService.func1()
	/go/src/github.com/milvus-io/milvus/internal/datacoord/server.go:672 +0x2e fp=0xc00f495fe0 sp=0xc00f495fb8 pc=0x270fd4e
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00f495fe8 sp=0xc00f495fe0 pc=0x142e6a1
created by github.com/milvus-io/milvus/internal/datacoord.(*Server).startWatchService
	/go/src/github.com/milvus-io/milvus/internal/datacoord/server.go:672 +0x95

goroutine 1 [chan receive, 1 minutes]:
github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run(0xc000e53e58, 0x0, {0x0, 0x0})
	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:317 +0xb8d
github.com/milvus-io/milvus/cmd/milvus.(*run).execute(0xc0007c28d0, {0xc00004e090?, 0x3, 0x3}, 0xc0009141e0)
	/go/src/github.com/milvus-io/milvus/cmd/milvus/run.go:112 +0x66e
github.com/milvus-io/milvus/cmd/milvus.RunMilvus({0xc00004e090?, 0x3, 0x3})
	/go/src/github.com/milvus-io/milvus/cmd/milvus/milvus.go:60 +0x21e
main.main()
	/go/src/github.com/milvus-io/milvus/cmd/main.go:26 +0x2e

goroutine 34949 [select]:
github.com/milvus-io/milvus/internal/datacoord.(*channelStateTimer).startOne.func1()
	/go/src/github.com/milvus-io/milvus/internal/datacoord/channel_checker.go:117 +0x430
created by github.com/milvus-io/milvus/internal/datacoord.(*channelStateTimer).startOne
	/go/src/github.com/milvus-io/milvus/internal/datacoord/channel_checker.go:109 +0x471

goroutine 102 [chan receive]:
github.com/panjf2000/ants/v2.(*Pool).purgePeriodically(0xc0003544d0)
	/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.8/pool.go:69 +0x8b
created by github.com/panjf2000/ants/v2.NewPool
	/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.8/pool.go:137 +0x34a

goroutine 180 [IO wait, 1 minutes]:
internal/poll.runtime_pollWait(0x7f1341455ec8, 0x72)
	/usr/local/go/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc000562180?, 0x0?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Accept(0xc000562180)
	/usr/local/go/src/internal/poll/fd_unix.go:614 +0x22c
net.(*netFD).accept(0xc000562180)
	/usr/local/go/src/net/fd_unix.go:172 +0x35
net.(*TCPListener).accept(0xc0001348d0)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x28
net.(*TCPListener).Accept(0xc0001348d0)
	/usr/local/go/src/net/tcpsock.go:288 +0x3d
net/http.(*Server).Serve(0xc0004e60e0, {0x4209160, 0xc0001348d0})
	/usr/local/go/src/net/http/server.go:3039 +0x385
net/http.(*Server).ListenAndServe(0xc0004e60e0)
	/usr/local/go/src/net/http/server.go:2968 +0x7d
net/http.ListenAndServe(...)
	/usr/local/go/src/net/http/server.go:3222
github.com/milvus-io/milvus/internal/management.ServeHTTP.func1()
	/go/src/github.com/milvus-io/milvus/internal/management/server.go:69 +0x151
created by github.com/milvus-io/milvus/internal/management.ServeHTTP
	/go/src/github.com/milvus-io/milvus/internal/management/server.go:66 +0x25

goroutine 182 [select, 1 minutes]:
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc000d596c0)
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/balancer_conn_wrappers.go:112 +0x73
created by google.golang.org/grpc.newCCBalancerWrapper
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/balancer_conn_wrappers.go:73 +0x22a

**Comment by xiaofan-luan** [comment]
how many collections is there? Did you get an idea about how many threads is there?

**Comment by jiaoew1991** [comment]
@jaime0815 Any clues on this error message when using Kafka?

**Comment by congqixia** [comment]
@xTerry 
It look like thread explosion in your scenario. How many collections and channels are there in your cluster?

**Comment by jaime0815** [comment]
Hi, @xTerry  Can you be sure how many collections you have?  Kafka Client will not release the thread resource after closing consumers immediately,  it is easy to exhaust thread resources if the number of flowgraphs is large(it relates to the number of collections).

**Comment by xTerry** [comment]
> Hi, @xTerry Can you be sure how many collections you have? Kafka Client will not release the thread resource after closing consumers immediately, it is easy to exhaust thread resources if the number of flowgraphs is large(it relates to the number of collections).

I deleted 200 million data volumes, about 10 collections, and after restarting, some of the loaded data cannot be retrieved. Looking at Kafka, there is over 350GB of space occupied on the disk, is it caused by a large number of consumers piling up?

**Comment by xTerry** [comment]
> > Hi, @xTerry Can you be sure how many collections you have? Kafka Client will not release the thread resource after closing consumers immediately, it is easy to exhaust thread resources if the number of flowgraphs is large(it relates to the number of collections).
> 
> I deleted 200 million data volumes, about 10 collections, and after restarting, some of the loaded data cannot be retrieved. Looking at Kafka, there is over 350GB of space occupied on the disk, is it caused by a large number of consumers piling up?

When deleted 10+ collections , has 1000+ collections , a collection's num about 10000 vectors，Some collections have 10 million+

**Comment by sweet85** [comment]
How can I solve this problem? I've encountered it too.

**Comment by sweet85** [comment]
/reopen
How can I solve this problem? I've encountered it too.

**Comment by sweet85** [comment]
How can I solve this problem? I've encountered it too.
