### ISSUE TITLE
[Bug]: [Nightly]The pipeline cluster-pulsar ended in 3 minutes with error message `find no available rootcoord, check rootcoord state`

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#24984]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: de66c8b
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.12.dev1
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The pipeline cluster-pulsar ended in 3 minutes with error message `find no available rootcoord, check rootcoord state`.
```
[2023-06-18T20:12:18.534Z] [2023-06-18 20:11:35 - ERROR - pymilvus.decorators]: RPC error: [batch_insert], <MilvusException: (code=1, message=err: find no available rootcoord, check rootcoord state
[2023-06-18T20:12:18.534Z] , /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
[2023-06-18T20:12:18.534Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:329 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall
[2023-06-18T20:12:18.534Z] /go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/client/client.go:234 github.com/milvus-io/milvus/internal/distributed/rootcoord/client.(*Client).DescribeCollection
[2023-06-18T20:12:18.534Z] /go/src/github.com/milvus-io/milvus/internal/proxy/meta_cache.go:543 github.com/milvus-io/milvus/internal/proxy.(*MetaCache).describeCollection
[2023-06-18T20:12:18.534Z] /go/src/github.com/milvus-io/milvus/internal/proxy/meta_cache.go:235 github.com/milvus-io/milvus/internal/proxy.(*MetaCache).GetCollectionID
[2023-06-18T20:12:18.534Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_insert.go:86 github.com/milvus-io/milvus/internal/proxy.(*insertTask).getChannels
[2023-06-18T20:12:18.534Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:235 github.com/milvus-io/milvus/internal/proxy.(*dmTaskQueue).Enqueue
[2023-06-18T20:12:18.534Z] /go/src/github.com/milvus-io/milvus/internal/proxy/impl.go:2837 github.com/milvus-io/milvus/internal/proxy.(*Proxy).Insert
[2023-06-18T20:12:18.534Z] /go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:680 github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).Insert
[2023-06-18T20:12:18.534Z] /go/pkg/mod/github.com/milvus-io/milvus-proto/go-api/v2@v2.2.10-dev.3/milvuspb/milvus.pb.go:11178 github.com/milvus-io/milvus-proto/go-api/v2/milvuspb._MilvusService_Insert_Handler.func1
[2023-06-18T20:12:18.534Z] )>, <Time:{'RPC start': '2023-06-18 20:11:35.603269', 'RPC error': '2023-06-18 20:11:35.608067'}> (decorators.py:108)
[2023-06-18T20:12:18.534Z] [2023-06-18 20:11:35 - ERROR - ci_test]: Traceback (most recent call last):
[2023-06-18T20:12:18.534Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2023-06-18T20:12:18.534Z]     res = func(*args, **_kwargs)
[2023-06-18T20:12:18.534Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2023-06-18T20:12:18.534Z]     return func(*arg, **kwargs)
[2023-06-18T20:12:18.534Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 443, in insert
[2023-06-18T20:12:18.534Z]     res = conn.batch_insert(self._name, entities, partition_name,
[2023-06-18T20:12:18.534Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2023-06-18T20:12:18.534Z]     raise e
[2023-06-18T20:12:18.534Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2023-06-18T20:12:18.534Z]     return func(*args, **kwargs)
[2023-06-18T20:12:18.534Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2023-06-18T20:12:18.534Z]     ret = func(self, *args, **kwargs)
[2023-06-18T20:12:18.534Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
[2023-06-18T20:12:18.534Z]     raise e
[2023-06-18T20:12:18.534Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2023-06-18T20:12:18.534Z]     return func(self, *args, **kwargs)
[2023-06-18T20:12:18.534Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 473, in batch_insert
[2023-06-18T20:12:18.534Z]     raise err
[2023-06-18T20:12:18.534Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 469, in batch_insert
[2023-06-18T20:12:18.534Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2023-06-18T20:12:18.534Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=err: find no available rootcoord, check rootcoord state
[2023-06-18T20:12:18.534Z] , /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
[2023-06-18T20:12:18.534Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:329 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall
[2023-06-18T20:12:18.534Z] /go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/client/client.go:234 github.com/milvus-io/milvus/internal/distributed/rootcoord/client.(*Client).DescribeCollection
[2023-06-18T20:12:18.534Z] /go/src/github.com/milvus-io/milvus/internal/proxy/meta_cache.go:543 github.com/milvus-io/milvus/internal/proxy.(*MetaCache).describeCollection
[2023-06-18T20:12:18.534Z] /go/src/github.com/milvus-io/milvus/internal/proxy/meta_cache.go:235 github.com/milvus-io/milvus/internal/proxy.(*MetaCache).GetCollectionID
[2023-06-18T20:12:18.534Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_insert.go:86 github.com/milvus-io/milvus/internal/proxy.(*insertTask).getChannels
[2023-06-18T20:12:18.534Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:235 github.com/milvus-io/milvus/internal/proxy.(*dmTaskQueue).Enqueue
[2023-06-18T20:12:18.534Z] /go/src/github.com/milvus-io/milvus/internal/proxy/impl.go:2837 github.com/milvus-io/milvus/internal/proxy.(*Proxy).Insert
[2023-06-18T20:12:18.534Z] /go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:680 github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).Insert
[2023-06-18T20:12:18.534Z] /go/pkg/mod/github.com/milvus-io/milvus-proto/go-api/v2@v2.2.10-dev.3/milvuspb/milvus.pb.go:11178 github.com/milvus-io/milvus-proto/go-api/v2/milvuspb._MilvusService_Insert_Handler.func1
[2023-06-18T20:12:18.534Z] )>
[2023-06-18T20:12:18.534Z]  (api_request.py:39)
[2023-06-18T20:12:18.534Z] [2023-06-18 20:11:35 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=err: find no available rootcoord, check rootcoord state
[2023-06-18T20:12:18.534Z] , /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
[2023-06-18T20:12:18.534Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:329...... (api_request.py:40)
```

### Expected Behavior

pass

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/226/pipeline/188
2. log: [artifacts-milvus-distributed-pulsar-nightly-226-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/226/artifact/artifacts-milvus-distributed-pulsar-nightly-226-pymilvus-e2e-logs.tar.gz)
3. collection name: collection_3Dc7gLXS
4. failure start time: [2023-06-18T20:11:37.858Z] [gw5] [  5%] FAILED testcases/test_collection.py::TestCollectionMultiCollections::test_collection_count_multi_collections_binary[1]

**Comment by NicoYuan1986** [comment]
same error in kafka: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/226/pipeline/156

**Comment by NicoYuan1986** [comment]
not reproduced for a week.
