### ISSUE TITLE
[Bug]: getSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#25017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230619-a6310050
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.4dev75
```

### Current Behavior

error when inserting
```
06/20/2023 03:57:50 AM - ERROR - RPC error: [batch_insert], <MilvusException: (code=1, message=getSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error)>, <Time:{'RPC start': '2023-06-20 03:57:38.787478', 'RPC error': '2023-06-20
 03:57:50.843354'}>
```

### Expected Behavior

insert successfully

### Steps To Reproduce

```markdown
1. insert 50000-128d vectors for 400 times
2. it failed occasionally
```

### Milvus Log

```
yanliang-cd-hnsw-milvus-datanode-68cb744dc5-mhp6v                 1/1     Running       0               112m    10.102.7.196    devops-node11   <none>           <none>
yanliang-cd-hnsw-milvus-indexnode-5b88747b4f-pzj9v                1/1     Running       1 (57m ago)     112m    10.102.6.209    devops-node10   <none>           <none>
yanliang-cd-hnsw-milvus-mixcoord-94f9c776f-tkb4g                  1/1     Running       2 (42m ago)     112m    10.102.9.159    devops-node13   <none>           <none>
yanliang-cd-hnsw-milvus-proxy-7ccb44d5f-42tlj                     1/1     Running       0               112m    10.102.5.150    devops-node21   <none>           <none>
yanliang-cd-hnsw-milvus-proxy-7ccb44d5f-qzh7r                     1/1     Running       0               112m    10.102.7.198    devops-node11   <none>           <none>
yanliang-cd-hnsw-milvus-querynode-58c584c654-4v2vz                1/1     Running       0               112m    10.102.6.210    devops-node10   <none>           <none>
yanliang-cd-hnsw-milvus-querynode-58c584c654-cvxn8                1/1     Running       1 (57m ago)     112m    10.102.9.158    devops-node13   <none>           <none>
yanliang-cd-hnsw-milvus-querynode-58c584c654-gs4rm                1/1     Running       0               112m    10.102.10.152   devops-node20   <none>           <none>
yanliang-cd-hnsw-milvus-querynode-58c584c654-p4zls 
```

**Comment by yanliang567** [comment]
it reproduced again on 2.2.0-20230621-6d139d97 when insert and delete slowly(one request per second)
`06/25/2023 22:11:38 PM - ERROR - RPC error: [batch_insert], <MilvusException: (code=1, message=getSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error)>, <Time:{'RPC start': '2023-06-25 22:11:28.773656', 'RPC error': '2023-06-25`

pod name:
```
yanliang-20cu-milvus-datanode-6577d4d86c-g2vsx                    1/1     Running       0                4d18h
yanliang-20cu-milvus-indexnode-84bc9cd4bb-2whzk                   0/1     Running       3 (4h46m ago)    15h
yanliang-20cu-milvus-mixcoord-7c57659fb9-td95d                    1/1     Running       1 (4d14h ago)    4d18h
yanliang-20cu-milvus-proxy-8d49fd575-xbpql                        1/1     Running       0                4d18h
yanliang-20cu-milvus-querynode-867cc74dfd-9kbfd                   1/1     Running       0                4d18h
yanliang-20cu-milvus-querynode-867cc74dfd-kjmb9                   1/1     Running       0                4d18h
yanliang-20cu-milvus-querynode-867cc74dfd-nknl8                   1/1     Running       5 (22h ago)      4d18h
yanliang-20cu-milvus-querynode-867cc74dfd-q8h79                   1/1     Running       1 (4d14h ago)    4d18h
```

**Comment by XuanYang-cn** [comment]
Seems to be etcd's problem
```
		2023-06-26 06:11:38	
[2023/06/25 22:11:38.777 +00:00] [WARN] [datacoord/services.go:180] ["failed to alloc segment"] [request="count:100 channel_name:\"yanliang-20cu-rootcoord-dml_0_442323864287453969v0\" collectionID:442323864287453969 partitionID:442323864287453970 "] [error="etcdserver: request timed out"]
2023-06-26 06:11:38	
[2023/06/25 22:11:38.777 +00:00] [ERROR] [datacoord/meta.go:896] ["meta update: add allocation failed"] ["segment ID"=442327211019938562] [error="etcdserver: request timed out"] [stack="github.com/milvus-io/milvus/internal/datacoord.(*meta).AddAllocation\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/meta.go:896\ngithub.com/milvus-io/milvus/internal/datacoord.(*SegmentManager).AllocSegment\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/segment_manager.go:278\ngithub.com/milvus-io/milvus/internal/datacoord.(*Server).AssignSegmentID\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/services.go:177\ngithub.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).AssignSegmentID\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:280\ngithub.com/milvus-io/milvus/internal/proto/datapb._DataCoord_AssignSegmentID_Handler.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proto/datapb/data_coord.pb.go:6269\ngithub.com/milvus-io/milvus/internal/util/logutil.UnaryTraceLoggerInterceptor\n\t/go/src/github.com/milvus-io/milvus/internal/util/logutil/grpc_interceptor.go:22\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tracing/opentracing/server_interceptors.go:38\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34\ngithub.com/milvus-io/milvus/internal/proto/datapb._DataCoord_AssignSegmentID_Handler\n\t/go/src/github.com/milvus-io/milvus/internal/proto/datapb/data_coord.pb.go:6271\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1283\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1620\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:922"]
```

```
2023-06-26 06:11:38	
[2023/06/25 22:11:38.777 +00:00] [WARN] [datacoord/services.go:180] ["failed to alloc segment"] [request="count:100 channel_name:\"yanliang-20cu-rootcoord-dml_0_442323864287453969v0\" collectionID:442323864287453969 partitionID:442323864287453970 "] [error="etcdserver: request timed out"]Show context
2023-06-21 18:46:55	
[2023/06/21 10:46:55.415 +00:00] [WARN] [rootcoord/root_coord.go:250] ["failed to update tso"] [error="etcdserver: request timed out"] [errorVerbose="etcdserver: request timed out\ngithub.com/milvus-io/milvus/internal/tso.(*timestampOracle).saveTimestamp\n\t/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:97\ngithub.com/milvus-io/milvus/internal/tso.(*timestampOracle).UpdateTimestamp\n\t/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:200\ngithub.com/milvus-io/milvus/internal/tso.(*GlobalTSOAllocator).UpdateTSO\n\t/go/src/github.com/milvus-io/milvus/internal/tso/global_allocator.go:100\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).tsLoop\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:249\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571"]
2023-06-21 18:46:42	
[2023/06/21 10:46:42.444 +00:00] [INFO] [rootcoord/root_coord.go:411] ["tso allocator initialized"] [root_path=yanliang-20cu/kv] [sub_path=gid] [key=idTimestamp]
2023-06-21 18:46:42	
[2023/06/21 10:46:42.392 +00:00] [INFO] [rootcoord/root_coord.go:395] ["id allocator initialized"] [root_path=yanliang-20cu/kv] [sub_path=gid] [key=idTimestamp]
2023-06-21 18:46:18	
[2023/06/21 10:46:18.461 +00:00] [WARN] [rootcoord/root_coord.go:250] ["failed to update tso"] [error="etcdserver: request timed out"] [errorVerbose="etcdserver: request timed out\ngithub.com/milvus-io/milvus/internal/tso.(*timestampOracle).saveTimestamp\n\t/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:97\ngithub.com/milvus-io/milvus/internal/tso.(*timestampOracle).UpdateTimestamp\n\t/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:200\ngithub.com/milvus-io/milvus/internal/tso.(*GlobalTSOAllocator).UpdateTSO\n\t/go/src/github.com/milvus-io/milvus/internal/tso/global_allocator.go:100\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).tsLoop\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:249\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571"]
2023-06-21 18:46:08	
[2023/06/21 10:46:08.460 +00:00] [WARN] [rootcoord/root_coord.go:250] ["failed to update tso"] [error="etcdserver: request timed out"] [errorVerbose="etcdserver: request timed out\ngithub.com/milvus-io/milvus/internal/tso.(*timestampOracle).saveTimestamp\n\t/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:97\ngithub.com/milvus-io/milvus/internal/tso.(*timestampOracle).UpdateTimestamp\n\t/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:200\ngithub.com/milvus-io/milvus/internal/tso.(*GlobalTSOAllocator).UpdateTSO\n\t/go/src/github.com/milvus-io/milvus/internal/tso/global_allocator.go:100\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).tsLoop\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:249\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571"]
2023-06-21 18:45:58	
[2023/06/21 10:45:58.456 +00:00] [WARN] [rootcoord/root_coord.go:250] ["failed to update tso"] [error="etcdserver: request timed out"] [errorVerbose="etcdserver: request timed out\ngithub.com/milvus-io/milvus/internal/tso.(*timestampOracle).saveTimestamp\n\t/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:97\ngithub.com/milvus-io/milvus/internal/tso.(*timestampOracle).UpdateTimestamp\n\t/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:200\ngithub.com/milvus-io/milvus/internal/tso.(*GlobalTSOAllocator).UpdateTSO\n\t/go/src/github.com/milvus-io/milvus/internal/tso/global_allocator.go:100\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).tsLoop\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:249\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571"]
2023-06-21 18:40:57	
[2023/06/21 10:40:57.761 +00:00] [WARN] [rootcoord/root_coord.go:250] ["failed to update tso"] [error="etcdserver: request timed out"] [errorVerbose="etcdserver: request timed out\ngithub.com/milvus-io/milvus/internal/tso.(*timestampOracle).saveTimestamp\n\t/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:97\ngithub.com/milvus-io/milvus/internal/tso.(*timestampOracle).UpdateTimestamp\n\t/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:200\ngithub.com/milvus-io/milvus/internal/tso.(*GlobalTSOAllocator).UpdateTSO\n\t/go/src/github.com/milvus-io/milvus/internal/tso/global_allocator.go:100\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).tsLoop\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:249\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571"]
2023-06-21 18:16:06	
[2023/06/21 10:16:06.876 +00:00] [WARN] [rootcoord/root_coord.go:250] ["failed to update tso"] [error="etcdserver: request timed out"] [errorVerbose="etcdserver: request timed out\ngithub.com/milvus-io/milvus/internal/tso.(*timestampOracle).saveTimestamp\n\t/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:97\ngithub.com/milvus-io/milvus/internal/tso.(*timestampOracle).UpdateTimestamp\n\t/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:200\ngithub.com/milvus-io/milvus/internal/tso.(*GlobalTSOAllocator).UpdateTSO\n\t/go/src/github.com/milvus-io/milvus/internal/tso/global_allocator.go:100\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).tsLoop\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:249\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571"]
2023-06-21 18:15:21	
[2023/06/21 10:15:21.750 +00:00] [WARN] [rootcoord/root_coord.go:250] ["failed to update tso"] [error="etcdserver: request timed out"] [errorVerbose="etcdserver: request timed out\ngithub.com/milvus-io/milvus/internal/tso.(*timestampOracle).saveTimestamp\n\t/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:97\ngithub.com/milvus-io/milvus/internal/tso.(*timestampOracle).UpdateTimestamp\n\t/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:200\ngithub.com/milvus-io/milvus/internal/tso.(*GlobalTSOAllocator).UpdateTSO\n\t/go/src/github.com/milvus-io/milvus/internal/tso/global_allocator.go:100\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).tsLoop\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:249\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571"]
2023-06-21 18:14:41	
[2023/06/21 10:14:41.212 +00:00] [WARN] [rootcoord/root_coord.go:250] ["failed to update tso"] [error="etcdserver: request timed out"] [errorVerbose="etcdserver: request timed out\ngithub.com/milvus-io/milvus/internal/tso.(*timestampOracle).saveTimestamp\n\t/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:97\ngithub.com/milvus-io/milvus/internal/tso.(*timestampOracle).UpdateTimestamp\n\t/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:200\ngithub.com/milvus-io/milvus/internal/tso.(*GlobalTSOAllocator).UpdateTSO\n\t/go/src/github.com/milvus-io/milvus/internal/tso/global_allocator.go:100\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).tsLoop\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:249\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571"]
2023-06-21 18:14:31	
[2023/06/21 10:14:31.211 +00:00] [WARN] [rootcoord/root_coord.go:250] ["failed to update tso"] [error="etcdserver: request timed out"] [errorVerbose="etcdserver: request timed out\ngithub.com/milvus-io/milvus/internal/tso.(*timestampOracle).saveTimestamp\n\t/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:97\ngithub.com/milvus-io/milvus/internal/tso.(*timestampOracle).UpdateTimestamp\n\t/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:200\ngithub.com/milvus-io/milvus/internal/tso.(*GlobalTSOAllocator).UpdateTSO\n\t/go/src/github.com/milvus-io/milvus/internal/tso/global_allocator.go:100\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).tsLoop\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:249\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571"]
2023-06-21 17:51:21	
[2023/06/21 09:51:21.412 +00:00] [WARN] [rootcoord/root_coord.go:250] ["failed to update tso"] [error="etcdserver: request timed out"] [errorVerbose="etcdserver: request timed out\ngithub.com/milvus-io/milvus/internal/tso.(*timestampOracle).saveTimestamp\n\t/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:97\ngithub.com/milvus-io/milvus/internal/tso.(*timestampOracle).UpdateTimestamp\n\t/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:200\ngithub.com/milvus-io/milvus/internal/tso.(*GlobalTSOAllocator).UpdateTSO\n\t/go/src/github.com/milvus-io/milvus/internal/tso/global_allocator.go:100\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).tsLoop\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:249\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571"]
2023-06-21 17:36:18	
[2023/06/21 09:36:18.260 +00:00] [WARN] [rootcoord/root_coord.go:250] ["failed to update tso"] [error="etcdserver: request timed out"] [errorVerbose="etcdserver: request timed out\ngithub.com/milvus-io/milvus/internal/tso.(*timestampOracle).saveTimestamp\n\t/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:97\ngithub.com/milvus-io/milvus/internal/tso.(*timestampOracle).UpdateTimestamp\n\t/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:200\ngithub.com/milvus-io/milvus/internal/tso.(*GlobalTSOAllocator).UpdateTSO\n\t/go/src/github.com/milvus-io/milvus/internal/tso/global_allocator.go:100\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).tsLoop\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:249\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571"]
2023-06-21 17:19:17	
[2023/06/21 09:19:17.710 +00:00] [WARN] [rootcoord/root_coord.go:250] ["failed to update tso"] [error="etcdserver: request timed out"] [errorVerbose="etcdserver: request timed out\ngithub.com/milvus-io/milvus/internal/tso.(*timestampOracle).saveTimestamp\n\t/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:97\ngithub.com/milvus-io/milvus/internal/tso.(*timestampOracle).UpdateTimestamp\n\t/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:200\ngithub.com/milvus-io/milvus/internal/tso.(*GlobalTSOAllocator).UpdateTSO\n\t/go/src/github.com/milvus-io/milvus/internal/tso/global_allocator.go:100\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).tsLoop\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:249\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571"]
2023-06-21 17:14:56	
[2023/06/21 09:14:56.412 +00:00] [WARN] [rootcoord/root_coord.go:250] ["failed to update tso"] [error="etcdserver: request timed out"] [errorVerbose="etcdserver: request timed out\ngithub.com/milvus-io/milvus/internal/tso.(*timestampOracle).saveTimestamp\n\t/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:97\ngithub.com/milvus-io/milvus/internal/tso.(*timestampOracle).UpdateTimestamp\n\t/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:200\ngithub.com/milvus-io/milvus/internal/tso.(*GlobalTSOAllocator).UpdateTSO\n\t/go/src/github.com/milvus-io/milvus/internal/tso/global_allocator.go:100\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).tsLoop\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:249\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571"]
2023-06-21 17:14:32	
[2023/06/21 09:14:32.561 +00:00] [WARN] [rootcoord/root_coord.go:250] ["failed to update tso"] [error="etcdserver: request timed out"] [errorVerbose="etcdserver: request timed out\ngithub.com/milvus-io/milvus/internal/tso.(*timestampOracle).saveTimestamp\n\t/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:97\ngithub.com/milvus-io/milvus/internal/tso.(*timestampOracle).UpdateTimestamp\n\t/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:200\ngithub.com/milvus-io/milvus/internal/tso.(*GlobalTSOAllocator).UpdateTSO\n\t/go/src/github.com/milvus-io/milvus/internal/tso/global_allocator.go:100\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).tsLoop\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:249\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571"]
2023-06-21 17:07:52	
[2023/06/21 09:07:52.761 +00:00] [WARN] [rootcoord/root_coord.go:250] ["failed to update tso"] [error="etcdserver: request timed out"] [errorVerbose="etcdserver: request timed out\ngithub.com/milvus-io/milvus/internal/tso.(*timestampOracle).saveTimestamp\n\t/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:97\ngithub.com/milvus-io/milvus/internal/tso.(*timestampOracle).UpdateTimestamp\n\t/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:200\ngithub.com/milvus-io/milvus/internal/tso.(*GlobalTSOAllocator).UpdateTSO\n\t/go/src/github.com/milvus-io/milvus/internal/tso/global_allocator.go:100\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).tsLoop\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:249\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571"]
2023-06-21 16:35:58	
[2023/06/21 08:35:58.311 +00:00] [WARN] [rootcoord/root_coord.go:250] ["failed to update tso"] [error="etcdserver: request timed out"] [errorVerbose="etcdserver: request timed out\ngithub.com/milvus-io/milvus/internal/tso.(*timestampOracle).saveTimestamp\n\t/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:97\ngithub.com/milvus-io/milvus/internal/tso.(*timestampOracle).UpdateTimestamp\n\t/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:200\ngithub.com/milvus-io/milvus/internal/tso.(*GlobalTSOAllocator).UpdateTSO\n\t/go/src/github.com/milvus-io/milvus/internal/tso/global_allocator.go:100\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).tsLoop\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:249\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571"]
2023-06-21 16:29:03	
[2023/06/21 08:29:03.710 +00:00] [WARN] [rootcoord/root_coord.go:250] ["failed to update tso"] [error="etcdserver: request timed out"] [errorVerbose="etcdserver: request timed out\ngithub.com/milvus-io/milvus/internal/tso.(*timestampOracle).saveTimestamp\n\t/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:97\ngithub.com/milvus-io/milvus/internal/tso.(*timestampOracle).UpdateTimestamp\n\t/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:200\ngithub.com/milvus-io/milvus/internal/tso.(*GlobalTSOAllocator).UpdateTSO\n\t/go/src/github.com/milvus-io/milvus/internal/tso/global_allocator.go:100\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).tsLoop\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:249\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571"]
2023-06-21 16:13:16	
[2023/06/21 08:13:16.761 +00:00] [WARN] [rootcoord/root_coord.go:250] ["failed to update tso"] [error="etcdserver: request timed out"] [errorVerbose="etcdserver: request timed out\ngithub.com/milvus-io/milvus/internal/tso.(*timestampOracle).saveTimestamp\n\t/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:97\ngithub.com/milvus-io/milvus/internal/tso.(*timestampOracle).UpdateTimestamp\n\t/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:200\ngithub.com/milvus-io/milvus/internal/tso.(*GlobalTSOAllocator).UpdateTSO\n\t/go/src/github.com/milvus-io/milvus/internal/tso/global_allocator.go:100\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).tsLoop\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:249\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571"]
2023-06-21 15:13:55	
[2023/06/21 07:13:55.634 +00:00] [INFO] [rootcoord/root_coord.go:411] ["tso allocator initialized"] [root_path=yanliang-20cu/kv] [sub_path=gid] [key=idTimestamp]
2023-06-21 15:13:55	
[2023/06/21 07:13:55.620 +00:00] [INFO] [rootcoord/root_coord.go:395] ["id allocator initialized"] [root_path=yanliang-20cu/kv] [sub_path=gid] [key=idTimestamp]
```

**Comment by yanliang567** [comment]
so the question turns to
1. how to configure a qualified etcd service
2. or how to insert within the current etcd configurations

**Comment by XuanYang-cn** [comment]
According to @congqixia , when insert frequency is high, datacoord need to write segmentinfo constently into etcd; and now datacoord will write >10KB *unnecessery* info into etcd everytime when allocate ids for new insertions.

This will put huge pressure on etcd, if etcd's disk isn't that good, it'll shut down.

@jaime0815 is working on it. I'll attach the PR later.

**Comment by XuanYang-cn** [comment]
@sunby is working on it
/assign @sunby 
/unassign

**Comment by XuanYang-cn** [comment]
https://github.com/milvus-io/milvus/pull/25316 some progresses

**Comment by binbinlv** [comment]
Same errors when inserting:
```
RPC error: [insert_rows], <MilvusException: (code=1, message=getSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error)>, <Time:{'RPC start': '2023-07-20 10:30:22.405544', 'RPC error': '2023-07-20 10:30:39.294523'}>
Traceback (most recent call last):
  File "./23406.py", line 34, in <module>
    res = collection.insert(rows)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 508, in insert
    res = conn.insert_rows(
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 126, in handler
    raise e from e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 122, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 161, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 101, in handler
    raise e from e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 68, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 501, in insert_rows
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=getSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error)
```

milvus: master-20230720-7bf39aed
pymilvus:

**Comment by XuanYang-cn** [comment]
@binbinlv 
![TOoss9Buq0](https://github.com/milvus-io/milvus/assets/51370125/b393873b-7ad1-4ecd-8661-b21c83fbbaf3)
6s for etcd put is way way way too much pressure, provide a better disk for etcd is a quicker solution.

BTW you can retry insert or low the insertion rate, this could help ease the pressure a bit.

**Comment by yanliang567** [comment]
any ideas why the etcd is getting slower and slower? I think we already used the local disk as etcd volumes. @XuanYang-cn 

/assign @XuanYang-cn

**Comment by xiaofan-luan** [comment]
> 

I think the devops cluster disk usage is too high. please figure out the environment issue together with the devops team because I don't engineers to spend extra time on investigate this

**Comment by yanliang567** [comment]
close it for now, will file a new one if reproduced on the other test clusters.
