### ISSUE TITLE
Add more info when raising exception in python-sdk

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#2503]
**Describe the bug**
```
11:40:08  2020-06-08:03:40:07,869 INFO     [client.py:247] Start delete collection: collection_p9kudkpv
11:40:08  2020-06-08:03:40:07,873 ERROR    [main.py:70] collection_name is illegal
11:40:08  2020-06-08:03:40:07,874 ERROR    [main.py:71] Traceback (most recent call last):
11:40:08    File "main.py", line 68, in queue_worker
11:40:08      runner.run(run_type, collection)
11:40:08    File "/home/jenkins/agent/workspace/milvus-benchmark-0.10.0/milvus_benchmark/k8s_runner.py", line 689, in run
11:40:08      milvus_instance.clean_db()
11:40:08    File "/home/jenkins/agent/workspace/milvus-benchmark-0.10.0/milvus_benchmark/client.py", line 277, in clean_db
11:40:08      self.drop(name=name)
11:40:08    File "/home/jenkins/agent/workspace/milvus-benchmark-0.10.0/milvus_benchmark/client.py", line 252, in drop
11:40:08      if self.count():
11:40:08    File "/home/jenkins/agent/workspace/milvus-benchmark-0.10.0/milvus_benchmark/client.py", line 239, in count
11:40:08      row_count = self._milvus.count_entities(self._collection_name)[1]
11:40:08    File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 37, in inner
11:40:08      return func(self, *args, **kwargs)
11:40:08    File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 311, in count_entities
11:40:08      check_pass_param(collection_name=collection_name)
11:40:08    File "/usr/local/lib/python3.6/site-packages/milvus/client/check.py", line 237, in check_pass_param
11:40:08      _raise_param_error(key)
11:40:08    File "/usr/local/lib/python3.6/site-packages/milvus/client/check.py", line 227, in _raise_param_error
11:40:08      raise ParamError("{} is illegal".format(param_name))
11:40:08  milvus.client.exceptions.ParamError: collection_name is illegal
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)

**Screenshots**

**Additional context**

**Comment by BossZou** [comment]
@del-zhenwu Please check.

**Comment by BossZou** [comment]
@del-zhenwu , May this issue has been fixed?
