### ISSUE TITLE
[Bug]: [Nightly]Plenty of cases failed for `InvalidateCollectionMetaCache failed, proxyID = 9, err = proxy not healthy`

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#25048]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 4d370ff
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.12.dev1
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Plenty of cases failed for `InvalidateCollectionMetaCache failed, proxyID = 9, err = proxy not healthy`.
It takes about 2 more hours than ever and only runs 7% of all cases.

```
[2023-06-20T23:40:52.089Z] [2023-06-20 20:10:24 - ERROR - pymilvus.decorators]: RPC error: [create_collection], <MilvusException: (code=1, message=InvalidateCollectionMetaCache failed, proxyID = 9, err = proxy not healthy)>, <Time:{'RPC start': '2023-06-20 20:10:24.198929', 'RPC error': '2023-06-20 20:10:24.209494'}> (decorators.py:108)
[2023-06-20T23:40:52.089Z] [2023-06-20 20:10:24 - ERROR - ci_test]: Traceback (most recent call last):
[2023-06-20T23:40:52.089Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2023-06-20T23:40:52.089Z]     res = func(*args, **_kwargs)
[2023-06-20T23:40:52.089Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2023-06-20T23:40:52.089Z]     return func(*arg, **kwargs)
[2023-06-20T23:40:52.089Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 124, in __init__
[2023-06-20T23:40:52.089Z]     conn.create_collection(self._name, schema, **kwargs)
[2023-06-20T23:40:52.089Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2023-06-20T23:40:52.089Z]     raise e
[2023-06-20T23:40:52.089Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2023-06-20T23:40:52.089Z]     return func(*args, **kwargs)
[2023-06-20T23:40:52.089Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2023-06-20T23:40:52.089Z]     ret = func(self, *args, **kwargs)
[2023-06-20T23:40:52.089Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
[2023-06-20T23:40:52.089Z]     raise e
[2023-06-20T23:40:52.089Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2023-06-20T23:40:52.089Z]     return func(self, *args, **kwargs)
[2023-06-20T23:40:52.089Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 251, in create_collection
[2023-06-20T23:40:52.089Z]     raise MilvusException(status.error_code, status.reason)
[2023-06-20T23:40:52.089Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=InvalidateCollectionMetaCache failed, proxyID = 9, err = proxy not healthy)>
[2023-06-20T23:40:52.089Z]  (api_request.py:39)
[2023-06-20T23:40:52.089Z] [2023-06-20 20:10:24 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=InvalidateCollectionMetaCache failed, proxyID = 9, err = proxy not healthy)> (api_request.py:40)
```

### Expected Behavior

pass

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/228/pipeline/156/
2. log: [artifacts-milvus-distributed-kafka-nightly-228-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/228/artifact/artifacts-milvus-distributed-kafka-nightly-228-pymilvus-e2e-logs.tar.gz)
3. failure start time: [2023-06-20T20:10:35.028Z] [gw4] [  4%] FAILED testcases/test_collection.py::TestCollectionCountIP::test_collection_count_after_index_created[1]

**Comment by smellthemoon** [comment]
<img width="939" alt="1" src="https://github.com/milvus-io/milvus/assets/64083300/35c4464b-e1ea-43db-ac64-406dcc3344a7">
close of closed channel panic make proxy panic.

**Comment by jaime0815** [comment]
it has been fixed https://github.com/milvus-io/milvus/pull/25071

**Comment by NicoYuan1986** [comment]
fixed.
