### ISSUE TITLE
[Bug]: Test case is stucked with server error `["Broadcast failed"] [error="Local: Unknown partition"]` 

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#25065]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230621-592e3e2e
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):kafka    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/12268675/4b227048-7ced-488b-b8d6-9773b4865088)

```
[2023/06/21 06:38:12.225 +00:00] [INFO] [job/scheduler.go:151] ["start to post-execute job"] [msgID=0] [collectionID=442323230914511980]
[2023/06/21 06:38:12.225 +00:00] [INFO] [job/scheduler.go:153] ["job finished"] [msgID=0] [collectionID=442323230914511980]
[2023/06/21 06:38:12.225 +00:00] [INFO] [querycoordv2/services.go:312] ["collection released"] [msgID=0] [collectionID=442323230914511980]
[2023/06/21 06:38:12.225 +00:00] [INFO] [meta/failed_load_cache.go:109] ["FailedLoadCache removes cache"] [collectionID=442323230914511980]
[2023/06/21 06:38:12.225 +00:00] [INFO] [rootcoord/broker.go:96] ["done to release collection"] [collection=442323230914511980]
[2023/06/21 06:38:12.225 +00:00] [INFO] [rootcoord/broker.go:225] ["dropping collection index"] [collection=442323230914511980] [partitions="[]"]
[2023/06/21 06:38:12.227 +00:00] [INFO] [sessionutil/session_util.go:486] ["SessionUtil GetSessions "] [prefix=indexcoord] [key=indexcoord] [address=10.104.19.18:31000]
[2023/06/21 06:38:12.227 +00:00] [INFO] [client/client.go:108] ["IndexCoordClient GetSessions success"] [key=indexcoord] [msess="{\"indexcoord\":{\"ServerID\":4,\"ServerName\":\"indexcoord\",\"Address\":\"10.104.19.18:31000\",\"Exclusive\":true,\"TriggerKill\":true,\"Version\":\"2.2.11-pre+dev\"}}"]
[2023/06/21 06:38:12.228 +00:00] [INFO] [indexcoord/index_coord.go:702] ["IndexCoord DropIndex"] [collectionID=442323230914511980] [partitionIDs="[]"] [indexName=]
[2023/06/21 06:38:12.228 +00:00] [INFO] [indexcoord/meta_table.go:744] ["IndexCoord metaTable MarkIndexAsDeleted"] [collID=442323230914511980] [indexIDs="[442323230914712019,442323230914712044]"]
[2023/06/21 06:38:12.229 +00:00] [INFO] [indexcoord/meta_table.go:774] ["IndexCoord metaTable MarkIndexAsDeleted success"] [collID=442323230914511980] [indexIDs="[442323230914712019,442323230914712044]"]
[2023/06/21 06:38:12.229 +00:00] [INFO] [indexcoord/index_coord.go:758] ["IndexCoord DropIndex success"] [collID=442323230914511980] [partitionIDs="[]"] [indexName=] [indexIDs="[442323230914712019,442323230914712044]"]
[2023/06/21 06:38:12.230 +00:00] [INFO] [rootcoord/broker.go:240] ["done to drop collection index"] [collection=442323230914511980] [partitions="[]"]
[2023/06/21 06:38:12.230 +00:00] [ERROR] [rootcoord/dml_channels.go:246] ["Broadcast failed"] [error="Local: Unknown partition"] [chanName=by-dev-rootcoord-dml_0] [stack="github.com/milvus-io/milvus/internal/rootcoord.(*dmlChannels).broadcast\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/dml_channels.go:246\ngithub.com/milvus-io/milvus/internal/rootcoord.(*timetickSync).broadcastDmlChannels\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/timeticksync.go:385\ngithub.com/milvus-io/milvus/internal/rootcoord.(*bgGarbageCollector).notifyCollectionGc\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/garbage_collector.go:169\ngithub.com/milvus-io/milvus/internal/rootcoord.(*bgGarbageCollector).GcCollectionData\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/garbage_collector.go:216\ngithub.com/milvus-io/milvus/internal/rootcoord.(*deleteCollectionDataStep).Execute\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/step.go:189\ngithub.com/milvus-io/milvus/internal/rootcoord.(*stepStack).Execute\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/step_executor.go:58\ngithub.com/milvus-io/milvus/internal/rootcoord.(*bgStepExecutor).process.func1\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/step_executor.go:200"]
[2023/06/21 06:38:12.230 +00:00] [WARN] [rootcoord/step_executor.go:74] ["failed to execute step, wait for reschedule"] [error="Local: Unknown partition"] [step="delete collection data, collection: 442323230914511980"]
[2023/06/21 06:38:12.230 +00:00] [ERROR] [rootcoord/dml_channels.go:246] ["Broadcast failed"] [error="Local: Unknown partition"] [chanName=by-dev-rootcoord-dml_0] [stack="github.com/milvus-io/milvus/internal/rootcoord.(*dmlChannels).broadcast\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/dml_channels.go:246\ngithub.com/milvus-io/milvus/internal/rootcoord.(*timetickSync).broadcastDmlChannels\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/timeticksync.go:385\ngithub.com/milvus-io/milvus/internal/rootcoord.(*bgGarbageCollector).notifyCollectionGc\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/garbage_collector.go:169\ngithub.com/milvus-io/milvus/internal/rootcoord.(*bgGarbageCollector).GcCollectionData\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/garbage_collector.go:216\ngithub.com/milvus-io/milvus/internal/rootcoord.(*deleteCollectionDataStep).Execute\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/step.go:189\ngithub.com/milvus-io/milvus/internal/rootcoord.(*stepStack).Execute\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/step_executor.go:58\ngithub.com/milvus-io/milvus/internal/rootcoord.(*bgStepExecutor).process.func1\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/step_executor.go:200"]
[2023/06/21 06:38:12.230 +00:00] [WARN] [rootcoord/step_executor.go:74] ["failed to execute step, wait for reschedule"] [error="Local: Unknown partition"] [step="delete collection data, collection: 442323230914511980"]
[2023/06/21 06:38:12.570 +00:00] [ERROR] [rootcoord/dml_channels.go:246] ["Broadcast failed"] [error="Local: Unknown partition"] [chanName=by-dev-rootcoord-dml_0] [stack="github.com/milvus-io/milvus/internal/rootcoord.(*dmlChannels).broadcast\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/dml_channels.go:246\ngithub.com/milvus-io/milvus/internal/rootcoord.(*timetickSync).broadcastDmlChannels\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/timeticksync.go:385\ngithub.com/milvus-io/milvus/internal/rootcoord.(*bgGarbageCollector).notifyCollectionGc\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/garbage_collector.go:169\ngithub.com/milvus-io/milvus/internal/rootcoord.(*bgGarbageCollector).GcCollectionData\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/garbage_collector.go:216\ngithub.com/milvus-io/milvus/internal/rootcoord.(*deleteCollectionDataStep).Execute\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/step.go:189\ngithub.com/milvus-io/milvus/internal/rootcoord.(*stepStack).Execute\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/step_executor.go:58\ngithub.com/milvus-io/milvus/internal/rootcoord.(*bgStepExecutor).process.func1\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/step_executor.go:200"]
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-for-release-cron/detail/chaos-test-kafka-for-release-cron/5214/pipeline

log:

[artifacts-standalone-pod-kill-5214-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/11814567/artifacts-standalone-pod-kill-5214-server-logs.1.tar.gz)

[artifacts-standalone-pod-kill-5214-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/11814568/artifacts-standalone-pod-kill-5214-pytest-logs.tar.gz)

**Comment by yanliang567** [comment]
blocking 2.2.11 release
/assign @jiaoew1991 @czs007

**Comment by zhuwenxing** [comment]
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-for-release-cron/detail/chaos-test-kafka-for-release-cron/5216/pipeline
log:
[artifacts-querynode-pod-kill-5216-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/11814776/artifacts-querynode-pod-kill-5216-server-logs.1.tar.gz)

[artifacts-querynode-pod-kill-5216-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/11814777/artifacts-querynode-pod-kill-5216-pytest-logs.tar.gz)


for cluster mode, the datanode will panic

![image](https://github.com/milvus-io/milvus/assets/12268675/df1a0cb6-7de6-4d7e-b8ef-b192ccc3267e)


```
[2023/06/21 07:10:58.371 +00:00] [INFO] [kafka/kafka_consumer.go:126] ["close consumer "] [topic=by-dev-rootcoord-dml_0] [groupID=by-dev-dataNode-8-by-dev-rootcoord-dml_0_442323747856712782v0]
[2023/06/21 07:10:58.372 +00:00] [WARN] [flowgraph/input_node.go:84] ["MsgStream closed"] ["input node"=dmInputNode-data-442323747856712782-by-dev-rootcoord-dml_0_442323747856712782v0]
[2023/06/21 07:10:58.372 +00:00] [INFO] [flowgraph/input_node.go:86] ["trigger force sync"] [collection=442323747856712782] [startPositions="[{\"channel_name\":\"by-dev-rootcoord-dml_0\",\"msgID\":\"XQAAAAAAAAA=\",\"msgGroup\":\"by-dev-dataNode-8-by-dev-rootcoord-dml_0_442323747856712782v0\",\"timestamp\":442323809836990466}]"] [endPositions="[{\"channel_name\":\"by-dev-rootcoord-dml_0\",\"msgID\":\"XwAAAAAAAAA=\",\"msgGroup\":\"by-dev-dataNode-8-by-dev-rootcoord-dml_0_442323747856712782v0\",\"timestamp\":442323809928740865}]"]
[2023/06/21 07:10:58.372 +00:00] [INFO] [flowgraph/node.go:112] ["flow graph node closed"] [nodeName=dmInputNode-data-442323747856712782-by-dev-rootcoord-dml_0_442323747856712782v0]
[2023/06/21 07:10:58.373 +00:00] [WARN] [datanode/flow_graph_dd_node.go:120] ["MsgStream closed"] ["ddNode node"=ddNode-442323747856712782-by-dev-rootcoord-dml_0_442323747856712782v0] [collection=442323747856712782] [channel=by-dev-rootcoord-dml_0_442323747856712782v0]
[2023/06/21 07:10:58.373 +00:00] [INFO] [msgstream/mq_msgstream.go:182] ["start to close mq msg stream"] ["producer num"=1] ["consumer num"=0]
[2023/06/21 07:10:58.383 +00:00] [INFO] [flowgraph/node.go:112] ["flow graph node closed"] [nodeName=ddNode-442323747856712782-by-dev-rootcoord-dml_0_442323747856712782v0]
[2023/06/21 07:10:58.383 +00:00] [INFO] [datanode/flow_graph_insert_buffer_node.go:348] ["Receive close request and syncing all segments"] [segments="[442323747856912794,442323747856912894]"] [channel=by-dev-rootcoord-dml_0_442323747856712782v0]
[2023/06/21 07:10:58.383 +00:00] [INFO] [msgstream/mq_msgstream.go:182] ["start to close mq msg stream"] ["producer num"=1] ["consumer num"=0]
panic: close of closed channel

goroutine 2391 [running]:
github.com/confluentinc/confluent-kafka-go/kafka.(*Producer).Close(0xc002332370)
	/go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.9.1/kafka/producer.go:358 +0x28
github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/kafka.(*kafkaProducer).Close.func1()
	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/kafka/kafka_producer.go:93 +0x27f
sync.(*Once).doSlow(0xc0021c9cc8?, 0x1508f08?)
	/usr/local/go/src/sync/once.go:68 +0xc2
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:59
github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/kafka.(*kafkaProducer).Close(0x41bb12b?)
	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mqwrapper/kafka/kafka_producer.go:81 +0x45
github.com/milvus-io/milvus/internal/mq/msgstream.(*mqMsgStream).Close(0xc000560540)
	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_msgstream.go:193 +0x2c4
github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Close(0xc0021464e0)
	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:102 +0x4b
github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work(0xc001f64190)
	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:133 +0x372
created by github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start
	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:71 +0x79
```

**Comment by zhuwenxing** [comment]
/assign @congqixia 
PTAL

**Comment by jaime0815** [comment]
It is similar with https://github.com/milvus-io/milvus/issues/24767

**Comment by jaime0815** [comment]
The flowgraphs of the collection and stream connections have been closed, but GC tasks still try to handle them.
