### ISSUE TITLE
[Bug]: All test cases load failed after querycoord pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#25080]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230621-277cbbd7
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):kafka    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```

[2023-06-21T09:58:56.184Z] [2023-06-21 09:56:45 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 120} (api_request.py:56)

[2023-06-21T09:58:56.184Z] [2023-06-21 09:56:48 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)

[2023-06-21T09:58:56.184Z] [2023-06-21 09:56:48 - INFO - ci_test]: [test][2023-06-21T09:56:45Z] [3.52191728s] Hello_Milvus flush -> None (wrapper.py:30)

[2023-06-21T09:58:56.184Z] [2023-06-21 09:56:48 - INFO - ci_test]: assert entities: 8000 (test_data_persistence.py:84)

[2023-06-21T09:58:56.184Z] [2023-06-21 09:56:48 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:56)

[2023-06-21T09:58:56.184Z] [2023-06-21 09:58:49 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=wait for loading collection timeout, collection: Hello_Milvus)>, <Time:{'RPC start': '2023-06-21 09:56:48.914266', 'RPC error': '2023-06-21 09:58:49.370345'}> (decorators.py:108)

[2023-06-21T09:58:56.184Z] [2023-06-21 09:58:49 - WARNING - pymilvus.decorators]: Retry timeout: 120s (decorators.py:79)

[2023-06-21T09:58:56.184Z] [2023-06-21 09:58:49 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: Hello_Milvus)>, <Time:{'RPC start': '2023-06-21 09:56:48.902070', 'RPC error': '2023-06-21 09:58:49.370697'}> (decorators.py:108)

[2023-06-21T09:58:56.184Z] [2023-06-21 09:58:49 - ERROR - ci_test]: Traceback (most recent call last):

[2023-06-21T09:58:56.184Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-06-21T09:58:56.184Z]     return func(self, *args, **kwargs)

[2023-06-21T09:58:56.184Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 791, in load_collection

[2023-06-21T09:58:56.184Z]     self.wait_for_loading_collection(collection_name, timeout, isRefresh=_refresh)

[2023-06-21T09:58:56.184Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-06-21T09:58:56.184Z]     raise e

[2023-06-21T09:58:56.184Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-06-21T09:58:56.184Z]     return func(*args, **kwargs)

[2023-06-21T09:58:56.184Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-06-21T09:58:56.184Z]     ret = func(self, *args, **kwargs)

[2023-06-21T09:58:56.184Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-06-21T09:58:56.184Z]     raise e

[2023-06-21T09:58:56.184Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-06-21T09:58:56.184Z]     return func(self, *args, **kwargs)

[2023-06-21T09:58:56.184Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 813, in wait_for_loading_collection

[2023-06-21T09:58:56.184Z]     raise MilvusException(message=f"wait for loading collection timeout, collection: {collection_name}")

[2023-06-21T09:58:56.184Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=wait for loading collection timeout, collection: Hello_Milvus)>

[2023-06-21T09:58:56.184Z] 

[2023-06-21T09:58:56.184Z] The above exception was the direct cause of the following exception:

[2023-06-21T09:58:56.184Z] 

[2023-06-21T09:58:56.184Z] Traceback (most recent call last):

[2023-06-21T09:58:56.184Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2023-06-21T09:58:56.184Z]     res = func(*args, **_kwargs)

[2023-06-21T09:58:56.184Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2023-06-21T09:58:56.184Z]     return func(*arg, **kwargs)

[2023-06-21T09:58:56.184Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 376, in load

[2023-06-21T09:58:56.184Z]     conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)

[2023-06-21T09:58:56.184Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-06-21T09:58:56.184Z]     raise e

[2023-06-21T09:58:56.184Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-06-21T09:58:56.184Z]     return func(*args, **kwargs)

[2023-06-21T09:58:56.184Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-06-21T09:58:56.184Z]     ret = func(self, *args, **kwargs)

[2023-06-21T09:58:56.184Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 80, in handler

[2023-06-21T09:58:56.184Z]     raise MilvusException(e.code, f"{timeout_msg}, message={e.message}") from e

[2023-06-21T09:58:56.184Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: Hello_Milvus)>

[2023-06-21T09:58:56.184Z]  (api_request.py:39)

[2023-06-21T09:58:56.184Z] [2023-06-21 09:58:49 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: Hello_Milvus)> (api_request.py:40
```
![image](https://github.com/milvus-io/milvus/assets/12268675/a3e20628-2f41-4437-94da-47f50d2b7c7b)
![image](https://github.com/milvus-io/milvus/assets/12268675/75270d01-622a-47e3-aef1-c2f8b23c34d0)

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-for-release-cron/detail/chaos-test-kafka-for-release-cron/5225/pipeline

log:

[artifacts-querycoord-pod-kill-5225-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/11816619/artifacts-querycoord-pod-kill-5225-server-logs.tar.gz)

[artifacts-querycoord-pod-kill-5225-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/11816620/artifacts-querycoord-pod-kill-5225-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
It seems not a stable issue, two retry jobs are all successful.

![image](https://github.com/milvus-io/milvus/assets/12268675/3f1c06d4-e25a-4d2f-8304-1913a0ee83d7)

**Comment by jaime0815** [comment]
```
[2023/06/21 09:56:49.851 +00:00] [INFO] [querynode/impl.go:510] ["loadSegmentsTask Enqueue done"] [collectionID=442326257168760870] [segmentIDs="[442326257168760896]"] [nodeID=4]
[2023/06/21 09:58:57.850 +00:00] [WARN] [task/scheduler.go:808] ["task stale due to the segment to load not exists in targets"] [taskID=172] [source=2] [segment=442326257168760896]
[2023/06/21 09:58:57.852 +00:00] [WARN] [meta/failed_load_cache.go:101] ["FailedLoadCache put failed record"] [collectionID=442326257168760870] [errCode=UnexpectedError] [error=TaskStale]
[2023/06/21 09:58:57.853 +00:00] [WARN] [querynode/shard_cluster.go:524] ["failed to dispatch load segment request"] [collectionID=442326257168760870] [channel=by-dev-rootcoord-dml_10_442326257168760870v0] [replicaID=442326343178256385] [dstNodeID=4] [segmentIDs="[442326257168760896]"] [error="context canceled"]
```
two minutes later, loadSegmentsTask pop from the queue, and dispatch fails. It seems scheduler problem.

**Comment by zhuwenxing** [comment]
this is reproduced in the case of the rootcoord pod failure chaos test.
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-for-release-cron/detail/chaos-test-kafka-for-release-cron/5345/pipeline
log:
[artifacts-rootcoord-pod-failure-5345-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/11858600/artifacts-rootcoord-pod-failure-5345-server-logs.tar.gz)

[artifacts-rootcoord-pod-failure-5345-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/11858601/artifacts-rootcoord-pod-failure-5345-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-for-release-cron/detail/chaos-test-kafka-for-release-cron/5303/pipeline
![image](https://github.com/milvus-io/milvus/assets/12268675/8eedf359-a036-48e8-a227-58ebbbb39eb5)

log:
[artifacts-rootcoord-pod-kill-5303-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/11858603/artifacts-rootcoord-pod-kill-5303-server-logs.tar.gz)

[artifacts-rootcoord-pod-kill-5303-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/11858604/artifacts-rootcoord-pod-kill-5303-pytest-logs.tar.gz)

**Comment by weiliu1031** [comment]
when try to close kafka/pulsar consumer by context done, the outside `mq_msgstream` will exit immediately, but the inside `kafka_consumer` will keep writing to `msgChannel` until receive `closeCh` signal, but if `msgChannel` has reached it's limit before receiving the close signal, the close operation will be blocked forever by writing to the `msgChannel`, cause the outside `mq_msgstream` has closed

**Comment by zhuwenxing** [comment]
Not reproduced recently, remove the critical label.
