### ISSUE TITLE
[Bug]: Search or query failed with error `attempt #0: can not find client of node -1: channel=by-dev-rootcoord-dml_10_xxxv0: fail to access shard delegator: fail to search on all shard leaders`

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#25102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230621-72c5e2a4
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):rocksmq    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```

[2023-06-24T09:35:01.549Z] <name>: deploy_test_index_type_BIN_IVF_FLAT_is_compacted_is_compacted_segment_status_all_is_string_indexed_is_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000

[2023-06-24T09:35:01.549Z] <description>: 

[2023-06-24T09:35:01.549Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', ......  (api_request.py:31)

[2023-06-24T09:35:01.549Z] [2023-06-24 09:31:34 - INFO - ci_test]: inserted 3000 data into collection deploy_test_index_type_BIN_IVF_FLAT_is_compacted_is_compacted_segment_status_all_is_string_indexed_is_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000 (common_func.py:944)

[2023-06-24T09:35:01.549Z] [2023-06-24 09:31:34 - DEBUG - ci_test]: Dynamic field is enabled: False (common_func.py:946)

[2023-06-24T09:35:01.549Z] [2023-06-24 09:31:35 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [      int64   float varchar                                      binary_vector

[2023-06-24T09:35:01.549Z] 0         0     0.0       0  b'V\x0b(\xd3\xd8`\xa6\xf8LX\x9f\xb5\xd0\x19\xe0+'

[2023-06-24T09:35:01.549Z] 1         1     1.0       1  b'\xc2\x1f\xe1\xfd\xc1\xf0\xa5\x895\x17}e\xf2B...

[2023-06-24T09:35:01.549Z] 2         2     2.0       2              b'|.\x92iU\xd6\xa2u|\......, kwargs: {'timeout': 120} (api_request.py:56)

[2023-06-24T09:35:01.549Z] [2023-06-24 09:31:37 - DEBUG - ci_test]: (api_response) : (insert count: 3000, delete count: 0, upsert count: 0, timestamp: 442393977423921161, success count: 3000, err count: 0)  (api_request.py:31)

[2023-06-24T09:35:01.549Z] [2023-06-24 09:31:37 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['binary_vector', {'index_type': 'BIN_IVF_FLAT', 'params': {'nlist': 128}, 'metric_type': 'HAMMING'}], kwargs: {'timeout': 1200, 'index_name': ''} (api_request.py:56)

[2023-06-24T09:35:01.549Z] [2023-06-24 09:31:38 - DEBUG - ci_test]: (api_response) : Status(code=0, message=)  (api_request.py:31)

[2023-06-24T09:35:01.549Z] [2023-06-24 09:31:38 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['varchar', {}], kwargs: {'timeout': 1200, 'index_name': '_default_string_idx'} (api_request.py:56)

[2023-06-24T09:35:01.549Z] [2023-06-24 09:31:39 - DEBUG - ci_test]: (api_response) : Status(code=0, message=)  (api_request.py:31)

[2023-06-24T09:35:01.549Z] [2023-06-24 09:31:39 - DEBUG - ci_test]: (api_request)  : [Collection.release] args: [], kwargs: {'timeout': 120} (api_request.py:56)

[2023-06-24T09:35:01.549Z] [2023-06-24 09:31:39 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)

[2023-06-24T09:35:01.549Z] [2023-06-24 09:31:39 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:56)

[2023-06-24T09:35:01.549Z] [2023-06-24 09:31:42 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)

[2023-06-24T09:35:01.549Z] [2023-06-24 09:31:42 - DEBUG - ci_test]: (api_request)  : [wait_for_loading_complete] args: ['deploy_test_index_type_BIN_IVF_FLAT_is_compacted_is_compacted_segment_status_all_is_string_indexed_is_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000', None, 20, 'default'], kwargs: {} (api_request.py:56)

[2023-06-24T09:35:01.549Z] [2023-06-24 09:31:42 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)

[2023-06-24T09:35:01.549Z] [2023-06-24 09:31:42 - DEBUG - ci_test]: (api_request)  : [Collection.delete] args: ['int64 in [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]', None, 120], kwargs: {} (api_request.py:56)

[2023-06-24T09:35:01.549Z] [2023-06-24 09:31:42 - DEBUG - ci_test]: (api_response) : (insert count: 0, delete count: 10, upsert count: 0, timestamp: 442393979104526337, success count: 0, err count: 0)  (api_request.py:31)

[2023-06-24T09:35:01.549Z] [2023-06-24 09:31:42 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[b'\xe7X\xe7w0+\t\xf9vg\xf5Y\xeb\xb5\x03\t', b'\xdf\xd3\xa2\x18R\xd4J>\xb5\xd3\xf7\xb3\xd0_\xe5,'], 'binary_vector', {'metric_type': 'HAMMING', 'params': {'nprobe': 10}}, 10, 'int64 >= 0', None, None, 120, -1], kwargs: {} (api_request.py:56)

[2023-06-24T09:35:01.549Z] [2023-06-24 09:31:42 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=attempt #0: can not find client of node -1: channel=by-dev-rootcoord-dml_10_442393880510040551v0: fail to access shard delegator: fail to search on all shard leaders)>, <Time:{'RPC start': '2023-06-24 09:31:42.436087', 'RPC error': '2023-06-24 09:31:42.727646'}> (decorators.py:108)

[2023-06-24T09:35:01.549Z] [2023-06-24 09:31:42 - ERROR - ci_test]: Traceback (most recent call last):

[2023-06-24T09:35:01.549Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2023-06-24T09:35:01.549Z]     res = func(*args, **_kwargs)

[2023-06-24T09:35:01.549Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2023-06-24T09:35:01.549Z]     return func(*arg, **kwargs)

[2023-06-24T09:35:01.549Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 682, in search

[2023-06-24T09:35:01.549Z]     res = conn.search(self._name, data, anns_field, param, limit, expr,

[2023-06-24T09:35:01.549Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-06-24T09:35:01.549Z]     raise e

[2023-06-24T09:35:01.549Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-06-24T09:35:01.549Z]     return func(*args, **kwargs)

[2023-06-24T09:35:01.549Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-06-24T09:35:01.549Z]     ret = func(self, *args, **kwargs)

[2023-06-24T09:35:01.549Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-06-24T09:35:01.549Z]     raise e

[2023-06-24T09:35:01.549Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-06-24T09:35:01.549Z]     return func(self, *args, **kwargs)

[2023-06-24T09:35:01.549Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 599, in search

[2023-06-24T09:35:01.549Z]     return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, **kwargs)

[2023-06-24T09:35:01.549Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 579, in _execute_search_requests

[2023-06-24T09:35:01.549Z]     raise pre_err

[2023-06-24T09:35:01.549Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 570, in _execute_search_requests

[2023-06-24T09:35:01.549Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2023-06-24T09:35:01.549Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=attempt #0: can not find client of node -1: channel=by-dev-rootcoord-dml_10_442393880510040551v0: fail to access shard delegator: fail to search on all shard leaders)>

[2023-06-24T09:35:01.549Z]  (api_request.py:39)
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_cron/detail/deploy_test_cron/954/pipeline/132

log:
[artifacts-rocksmq-standalone-reinstall-954-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/11858646/artifacts-rocksmq-standalone-reinstall-954-server-logs.tar.gz)

[artifacts-rocksmq-standalone-reinstall-954-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/11858647/artifacts-rocksmq-standalone-reinstall-954-pytest-logs.tar.gz)

**Comment by binbinlv** [comment]
Similar error in CI:
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-25118/2/pipeline

collection name: search_collection_5vzPMgCW

**Comment by smellthemoon** [comment]
qn check health failed, look aside balancer put the node to unreachable nodes list.
<img width="1340" alt="1" src="https://github.com/milvus-io/milvus/assets/64083300/b63ba0ea-2610-4a3d-8f72-952ab42aa713">
But qn is actually health, it can be seen that the  look aside balancer get component fails occasionally.
<img width="1082" alt="2" src="https://github.com/milvus-io/milvus/assets/64083300/3777248a-5b77-4f8c-9660-cb6cb2c8efe6">

**Comment by zhuwenxing** [comment]
query failed with the same error after the etcd pod kill and rootcoord pod kill chaos test.
```

[2023-06-26T19:30:33.077Z] [2023-06-26 19:29:37 - INFO - ci_test]: index info: [{'collection': 'IndexChecker__iVkmOKNO', 'field': 'float_vector', 'index_name': 'index__AI4AAgIB', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}] (test_all_collections_after_chaos.py:81)

[2023-06-26T19:30:33.077Z] [2023-06-26 19:29:37 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:56)

[2023-06-26T19:30:33.077Z] [2023-06-26 19:29:42 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)

[2023-06-26T19:30:33.078Z] [2023-06-26 19:29:42 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.12701659704679183, 0.12021538986785697, 0.07622557456922326, 0.01588132198627707, 0.11457519254425393, 0.051951762942409434, 0.0194720065304285, 0.0018303041829864678, 0.10880331584102208, 0.009326862231300572, 0.0661646784581864, 0.07626513047717888, 0.04725084517766036, 0.03782598381420408, 0......, kwargs: {} (api_request.py:56)

[2023-06-26T19:30:33.078Z] [2023-06-26 19:29:43 - DEBUG - ci_test]: (api_response) : ["['id: 1012, distance: 0.3033236861228943, entity: {}']"]  (api_request.py:31)

[2023-06-26T19:30:33.078Z] [2023-06-26 19:29:43 - INFO - ci_test]: assert search: 0.3734242916107178 (test_all_collections_after_chaos.py:94)

[2023-06-26T19:30:33.078Z] [2023-06-26 19:29:43 - DEBUG - ci_test]: (api_request)  : [Collection.query] args: ['int64 in [-3000, -2999, -2998, -2997, -2996, -2995, -2994, -2993, -2992, -2991, -2990, -2989, -2988, -2987, -2986, -2985, -2984, -2983, -2982, -2981, -2980, -2979, -2978, -2977, -2976, -2975, -2974, -2973, -2972, -2971, -2970, -2969, -2968, -2967, -2966, -2965, -2964, -2963, -2962, -2961, -2960, -......, kwargs: {} (api_request.py:56)

[2023-06-26T19:30:33.078Z] [2023-06-26 19:29:43 - ERROR - pymilvus.decorators]: RPC error: [query], <MilvusException: (code=1, message=attempt #0: can not find client of node -1: channel=by-dev-rootcoord-dml_2_442448455404170639v0: fail to access shard delegator: fail to query on all shard leaders)>, <Time:{'RPC start': '2023-06-26 19:29:43.348125', 'RPC error': '2023-06-26 19:29:43.579805'}> (decorators.py:108)

[2023-06-26T19:30:33.078Z] [2023-06-26 19:29:43 - ERROR - ci_test]: Traceback (most recent call last):

[2023-06-26T19:30:33.078Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2023-06-26T19:30:33.078Z]     res = func(*args, **_kwargs)

[2023-06-26T19:30:33.078Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2023-06-26T19:30:33.078Z]     return func(*arg, **kwargs)

[2023-06-26T19:30:33.078Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 775, in query

[2023-06-26T19:30:33.078Z]     res = conn.query(self._name, expr, output_fields, partition_names,

[2023-06-26T19:30:33.078Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-06-26T19:30:33.078Z]     raise e

[2023-06-26T19:30:33.078Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-06-26T19:30:33.078Z]     return func(*args, **kwargs)

[2023-06-26T19:30:33.078Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-06-26T19:30:33.078Z]     ret = func(self, *args, **kwargs)

[2023-06-26T19:30:33.078Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-06-26T19:30:33.078Z]     raise e

[2023-06-26T19:30:33.078Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-06-26T19:30:33.078Z]     return func(self, *args, **kwargs)

[2023-06-26T19:30:33.078Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 1048, in query

[2023-06-26T19:30:33.078Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2023-06-26T19:30:33.078Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=attempt #0: can not find client of node -1: channel=by-dev-rootcoord-dml_2_442448455404170639v0: fail to access shard delegator: fail to query on all shard leaders)>

[2023-06-26T19:30:33.078Z]  (api_request.py:39)

[2023-06-26T19:30:33.078Z] [2023-06-26 19:29:43 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=attempt #0: can not find client of node -1: channel=by-dev-rootcoord-dml_2_442448455404170639v0: fail to access shard delegator: fail to query on all shard leaders)> (api_request.py:40)
```

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-cron/detail/chaos-test-kafka-cron/5220/pipeline
log:
[artifacts-etcd-pod-kill-5220-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/11878178/artifacts-etcd-pod-kill-5220-server-logs.tar.gz)

[artifacts-etcd-pod-kill-5220-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/11878179/artifacts-etcd-pod-kill-5220-pytest-logs.tar.gz)

**Comment by yanliang567** [comment]
@zhuwenxing @smellthemoon any updates

**Comment by smellthemoon** [comment]
> @zhuwenxing @smellthemoon any updates

pr merged, need verify.
