### ISSUE TITLE
[Bug]: [high level api] Could we set a default value for max_length when setting string as primary key

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#25110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvus latest
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):     all
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus latest
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

No default value for max_length:
if not specifying max_length, it will report error
```
>>> milvus_client.create_collection(collection_name, dim, id_type="string")
RPC error: [create_collection], <MilvusException: (code=1, message=type param(max_length) should be specified for varChar field of collection coll123)>, <Time:{'RPC start': '2023-06-25 15:26:29.526359', 'RPC error': '2023-06-25 15:26:29.632324'}>
Failed to create collection: coll123
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 101, in create_collection
    raise ex
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 97, in create_collection
    conn.create_collection(collection_name, schema, timeout=timeout, **kwargs)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 251, in create_collection
    raise MilvusException(status.error_code, status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=type param(max_length) should be specified for varChar field of collection coll123)>
```

### Expected Behavior

Set default value for max_length

### Steps To Reproduce

```python
from pymilvus import MilvusClient
milvus_client = MilvusClient()
collection_name= "coll123"
dim = 10
milvus_client.create_collection(collection_name, dim, id_type="string")
```

### Anything else?

both in 2.2.* and 2.3.*

**Comment by binbinlv** [comment]
And when input max_length, it report error too.
>>> milvus_client.create_collection(collection_name, dim, id_type="string", max_length=10)
RPC error: [create_collection], <MilvusException: (code=1, message=type param(max_length) should be specified for varChar field of collection coll123)>, <Time:{'RPC start': '2023-06-25 15:27:59.230481', 'RPC error': '2023-06-25 15:27:59.336032'}>
Failed to create collection: coll123
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 101, in create_collection
    raise ex
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 97, in create_collection
    conn.create_collection(collection_name, schema, timeout=timeout, **kwargs)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 251, in create_collection
    raise MilvusException(status.error_code, status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=type param(max_length) should be specified for varChar field of collection coll123)>

**Comment by binbinlv** [comment]
@czs007 
so it is no plan to set default value for max_length?
