### ISSUE TITLE
[Bug]: When standalone pod was killed by force, it needs restart 3 times to recover

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#25182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.2.10
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):rocksmq    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

when the pod starts to recover, the pod will crash with panic error at begin. 
```
[2023/06/27 09:33:26.536 +00:00] [INFO] [server/global_rmq.go:55] ["initializing global rmq"] [path=/var/lib/milvus/rdb_data]
[2023/06/27 09:33:26.536 +00:00] [INFO] [config/etcd_source.go:145] ["start refreshing configurations"]
[2023/06/27 09:33:26.537 +00:00] [INFO] [server/rocksmq_impl.go:154] ["Start rocksmq "] ["max proc"=8] [parallism=1] ["lru cache"=1030792151]
panic: IO error: While lock file: /var/lib/milvus/rdb_data_meta_kv/LOCK: Resource temporarily unavailable

goroutine 1 [running]:
github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run(0xc0005e5e48, 0x1, {0x0, 0x0})
        /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:243 +0xcf5
github.com/milvus-io/milvus/cmd/milvus.(*run).execute(0xc000f00180, {0xc0001ae060?, 0x3, 0x3}, 0xc0003f2900)
        /go/src/github.com/milvus-io/milvus/cmd/milvus/run.go:117 +0x6ae
github.com/milvus-io/milvus/cmd/milvus.RunMilvus({0xc0001ae060?, 0x3, 0x3})
        /go/src/github.com/milvus-io/milvus/cmd/milvus/milvus.go:60 +0x21e
main.main()
        /go/src/github.com/milvus-io/milvus/cmd/main.go:26 +0x2e

```

![image](https://github.com/milvus-io/milvus/assets/12268675/19097e7f-1ff2-428b-afcf-3b7ae9deda13)

### Expected Behavior

the pod can recover as fast as possible

### Milvus Log

```
Defaulted container "standalone" out of: standalone, config (init)
2023/06/27 09:33:26 maxprocs: Updating GOMAXPROCS=8: determined from CPU quota

    __  _________ _   ____  ______    
   /  |/  /  _/ /| | / / / / / __/    
  / /|_/ // // /_| |/ / /_/ /\ \    
 /_/  /_/___/____/___/\____/___/     

Welcome to use Milvus!
Version:   v2.2.10
Built:     Wed Jun 14 04:16:44 UTC 2023
GitCommit: f11b317
GoVersion: go version go1.18.3 linux/amd64

open pid file: /run/milvus/standalone.pid
lock pid file: /run/milvus/standalone.pid
[2023/06/27 09:33:26.464 +00:00] [INFO] [roles/roles.go:226] ["starting running Milvus components"]
[2023/06/27 09:33:26.464 +00:00] [INFO] [roles/roles.go:152] ["Enable Jemalloc"] ["Jemalloc Path"=/milvus/lib/libjemalloc.so]
[2023/06/27 09:33:26.492 +00:00] [INFO] [config/etcd_source.go:145] ["start refreshing configurations"]
[2023/06/27 09:33:26.492 +00:00] [INFO] [paramtable/quota_param.go:769] ["init disk quota"] [diskQuota(MB)=+inf]
[2023/06/27 09:33:26.492 +00:00] [INFO] [paramtable/quota_param.go:784] ["init disk quota per DB"] [diskQuotaPerCollection(MB)=1.7976931348623157e+308]
[2023/06/27 09:33:26.492 +00:00] [INFO] [paramtable/component_param.go:1538] ["init segment max idle time"] [value=10m0s]
[2023/06/27 09:33:26.492 +00:00] [INFO] [paramtable/component_param.go:1543] ["init segment min size from idle to sealed"] [value=16]
[2023/06/27 09:33:26.492 +00:00] [INFO] [paramtable/component_param.go:1553] ["init segment max binlog file to sealed"] [value=32]
[2023/06/27 09:33:26.492 +00:00] [INFO] [paramtable/component_param.go:1548] ["init segment expansion rate"] [value=1.25]
[2023/06/27 09:33:26.500 +00:00] [INFO] [paramtable/base_table.go:142] ["cannot find etcd.endpoints"]
[2023/06/27 09:33:26.500 +00:00] [INFO] [paramtable/hook_config.go:19] ["hook config"] [hook={}]
[2023/06/27 09:33:26.536 +00:00] [INFO] [server/global_rmq.go:55] ["initializing global rmq"] [path=/var/lib/milvus/rdb_data]
[2023/06/27 09:33:26.536 +00:00] [INFO] [config/etcd_source.go:145] ["start refreshing configurations"]
[2023/06/27 09:33:26.537 +00:00] [INFO] [server/rocksmq_impl.go:154] ["Start rocksmq "] ["max proc"=8] [parallism=1] ["lru cache"=1030792151]
panic: IO error: While lock file: /var/lib/milvus/rdb_data_meta_kv/LOCK: Resource temporarily unavailable

goroutine 1 [running]:
github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run(0xc0005e5e48, 0x1, {0x0, 0x0})
        /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:243 +0xcf5
github.com/milvus-io/milvus/cmd/milvus.(*run).execute(0xc000f00180, {0xc0001ae060?, 0x3, 0x3}, 0xc0003f2900)
        /go/src/github.com/milvus-io/milvus/cmd/milvus/run.go:117 +0x6ae
github.com/milvus-io/milvus/cmd/milvus.RunMilvus({0xc0001ae060?, 0x3, 0x3})
        /go/src/github.com/milvus-io/milvus/cmd/milvus/milvus.go:60 +0x21e
main.main()
        /go/src/github.com/milvus-io/milvus/cmd/main.go:26 +0x2e

❯ k get pod|grep insert-tes                                     
insert-test-xgbkw-etcd-0                                          1/1     Running       0               23h
insert-test-xgbkw-milvus-standalone-64bd854886-77qsc              1/1     Running       3 (2m29s ago)   2m56s
insert-test-xgbkw-minio-6c8b8769c6-9jwdk                          1/1     Runni
```

### Anything else?

It will make RTO become large

**Comment by xiaofan-luan** [comment]
@zhuwenxing good catch!

**Comment by aoiasd** [comment]
Seems that force kill milvus but not release file locak of rocksdb. Qusetion was that, if we delelte before start, user will could use multiple milvus with one rockdb folder, and cause data out of order.

**Comment by xiaofan-luan** [comment]
> Seems that force kill milvus but not release file lock of rocksdb. Qusetion was that, if we delelte before start, user will could use multiple milvus with one rockdb folder, and cause data out of order.

The cleanup process might be handled by the daemon script which brings milvus us?
Talk to @LoveEachDay about the details
