### ISSUE TITLE
[Bug]: The metric type was not set properly in shard followers

### ISSUE THREAD

**Issue by bigsheeper** [milvus-io/milvus#25205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0 (f80afb1db)
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. start 2 querynodes:
```shell
echo "Starting querynode..."
nohup ./bin/milvus run querynode --alias querynode:1 > /tmp/querynode1.log 2>&1 &
nohup ./bin/milvus run querynode --alias querynode:2 > /tmp/querynode2.log 2>&1 &
```

2. create collection with 1 shard, and search without metric type:
```python
# hello_milvus.py demonstrates the basic operations of PyMilvus, a Python SDK of Milvus.
# 1. connect to Milvus
# 2. create collection
# 3. insert data
# 4. create index
# 5. search, query, and hybrid search on entities
# 6. delete entities by PK
# 7. drop collection
import time

import numpy as np
from pymilvus import (
    connections,
    utility,
    FieldSchema, CollectionSchema, DataType,
    Collection,
)

fmt = "\n=== {:30} ===\n"
search_latency_fmt = "search latency = {:.4f}s"
num_entities, dim = 3000, 8

#################################################################################
# 1. connect to Milvus
# Add a new connection alias `default` for Milvus server in `localhost:19530`
# Actually the "default" alias is a buildin in PyMilvus.
# If the address of Milvus is the same as `localhost:19530`, you can omit all
# parameters and call the method as: `connections.connect()`.
#
# Note: the `using` parameter of the following methods is default to "default".
print(fmt.format("start connecting to Milvus"))
connections.connect("default", host="localhost", port="19530")

has = utility.has_collection("hello_milvus")
print(f"Does collection hello_milvus exist in Milvus: {has}")

#################################################################################
# 2. create collection
# We're going to create a collection with 3 fields.
# +-+------------+------------+------------------+------------------------------+
# | | field name | field type | other attributes |       field description      |
# +-+------------+------------+------------------+------------------------------+
# |1|    "pk"    |   VarChar  |  is_primary=True |      "primary field"         |
# | |            |            |   auto_id=False  |                              |
# +-+------------+------------+------------------+------------------------------+
# |2|  "random"  |    Double  |                  |      "a double field"        |
# +-+------------+------------+------------------+------------------------------+
# |3|"embeddings"| FloatVector|     dim=8        |  "float vector with dim 8"   |
# +-+------------+------------+------------------+------------------------------+
fields = [
    FieldSchema(name="pk", dtype=DataType.VARCHAR, is_primary=True, auto_id=False, max_length=100),
    FieldSchema(name="random", dtype=DataType.DOUBLE),
    FieldSchema(name="embeddings", dtype=DataType.FLOAT_VECTOR, dim=dim)
]

schema = CollectionSchema(fields, "hello_milvus is the simplest demo to introduce the APIs")

print(fmt.format("Create collection `hello_milvus`"))
hello_milvus = Collection("hello_milvus", schema, consistency_level="Strong", num_shards=1)

################################################################################
# 3. insert data
# We are going to insert 3000 rows of data into `hello_milvus`
# Data to be inserted must be organized in fields.
#
# The insert() method returns:
# - either automatically generated primary keys by Milvus if auto_id=True in the schema;
# - or the existing primary key field from the entities if auto_id=False in the schema.

print(fmt.format("Start inserting entities"))
rng = np.random.default_rng(seed=19530)
entities = [
    # provide the pk field because `auto_id` is set to False
    [str(i) for i in range(num_entities)],
    rng.random(num_entities).tolist(),  # field random, only supports list
    rng.random((num_entities, dim)),    # field embeddings, supports numpy.ndarray and list
]

for _ in range(20):
    insert_result = hello_milvus.insert(entities)
    hello_milvus.flush()
    print(f"Number of entities in Milvus: {hello_milvus.num_entities}")  # check the num_entites

################################################################################
# 4. create index
# We are going to create an IVF_FLAT index for hello_milvus collection.
# create_index() can only be applied to `FloatVector` and `BinaryVector` fields.
print(fmt.format("Start Creating index IVF_FLAT"))
index = {
    "index_type": "IVF_FLAT",
    "metric_type": "L2",
    "params": {"nlist": 128},
}

hello_milvus.create_index("embeddings", index)

################################################################################
# 5. search, query, and hybrid search
# After data were inserted into Milvus and indexed, you can perform:
# - search based on vector similarity
# - query based on scalar filtering(boolean, int, etc.)
# - hybrid search based on vector similarity and scalar filtering.
#

# Before conducting a search or a query, you need to load the data in `hello_milvus` into memory.
print(fmt.format("Start loading"))
hello_milvus.load()

# -----------------------------------------------------------------------------
# search based on vector similarity
print(fmt.format("Start searching based on vector similarity"))
vectors_to_search = entities[-1][-2:]
search_params = {
    "metric_type": "",
    "params": {"nprobe": 10},
}

start_time = time.time()
result = hello_milvus.search(vectors_to_search, "embeddings", search_params, limit=3, output_fields=["random"])
end_time = time.time()

for hits in result:
    for hit in hits:
        print(f"hit: {hit}, random field: {hit.entity.get('random')}")
print(search_latency_fmt.format(end_time - start_time))


###############################################################################
# 7. drop collection
# Finally, drop the hello_milvus collection
print(fmt.format("Drop collection `hello_milvus`"))
utility.drop_collection("hello_milvus")
```

3. result:
```
RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:
attempt #1:code: UnexpectedError, error: fail to Search, QueryNode ID=4, reason=Search 2 failed, reason [UnexpectedError] Assert "field_indexing->metric_type_ == search_info.metric_type_" at /home/sheep/workspace/milvus/internal/core/src/query/SearchOnSealed.cpp:40
 => Metric type of field index isn't the same with search info err %!w(<nil>)
attempt #2:context canceled
)>, <Time:{'RPC start': '2023-06-28 16:08:48.228611', 'RPC error': '2023-06-28 16:08:48.687467'}>
Traceback (most recent call last):
  File "hello_milvus.py", line 119, in <module>
    result = hello_milvus.search(vectors_to_search, "embeddings", search_params, limit=3, output_fields=["random"])
  File "/home/sheep/workspace/pymilvus/pymilvus/orm/collection.py", line 682, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/home/sheep/workspace/pymilvus/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/home/sheep/workspace/pymilvus/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/home/sheep/workspace/pymilvus/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/home/sheep/workspace/pymilvus/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/home/sheep/workspace/pymilvus/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/home/sheep/workspace/pymilvus/pymilvus/client/grpc_handler.py", line 599, in search
    return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, **kwargs)
  File "/home/sheep/workspace/pymilvus/pymilvus/client/grpc_handler.py", line 579, in _execute_search_requests
    raise pre_err
  File "/home/sheep/workspace/pymilvus/pymilvus/client/grpc_handler.py", line 570, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:
attempt #1:code: UnexpectedError, error: fail to Search, QueryNode ID=4, reason=Search 2 failed, reason [UnexpectedError] Assert "field_indexing->metric_type_ == search_info.metric_type_" at /home/sheep/workspace/milvus/internal/core/src/query/SearchOnSealed.cpp:40
 => Metric type of field index isn't the same with search info err %!w(<nil>)
attempt #2:context canceled
)>
```

**Comment by NicoYuan1986** [comment]
I will add the case later.
