### ISSUE TITLE
[Bug]: Some components are not in a health status when run first deployment test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#25202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230628-e09da3b4
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq  
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
2023-06-28T06:12:42.828Z] [2023-06-28 06:12:41 - DEBUG - ci_test]: (api_request)  : [Connections.has_connection] args: ['default'], kwargs: {} (api_request.py:56)

[2023-06-28T06:12:42.828Z] [2023-06-28 06:12:41 - DEBUG - ci_test]: (api_response) : True  (api_request.py:31)

[2023-06-28T06:12:42.828Z] [2023-06-28 06:12:41 - DEBUG - ci_test]: (api_request)  : [Collection] args: ['deploy_test_index_type_BIN_IVF_FLAT_is_compacted_not_compacted_segment_status_all_is_string_indexed_not_string_indexed_replica_number_0_is_deleted_is_deleted_data_size_3000', {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_prim......, kwargs: {'consistency_level': 'Strong'} (api_request.py:56)

[2023-06-28T06:12:42.828Z] [2023-06-28 06:12:41 - ERROR - pymilvus.decorators]: RPC error: [create_collection], <MilvusException: (code=1, message=err: find no available datacoord, check datacoord state

[2023-06-28T06:12:42.828Z] , /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace

[2023-06-28T06:12:42.828Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:352 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall

[2023-06-28T06:12:42.828Z] /go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:583 github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).WatchChannels

[2023-06-28T06:12:42.828Z] /go/src/github.com/milvus-io/milvus/internal/rootcoord/broker.go:126 github.com/milvus-io/milvus/internal/rootcoord.(*ServerBroker).WatchChannels

[2023-06-28T06:12:42.828Z] /go/src/github.com/milvus-io/milvus/internal/rootcoord/step.go:115 github.com/milvus-io/milvus/internal/rootcoord.(*watchChannelsStep).Execute

[2023-06-28T06:12:42.828Z] /go/src/github.com/milvus-io/milvus/internal/rootcoord/undo.go:53 github.com/milvus-io/milvus/internal/rootcoord.(*baseUndoTask).Execute

[2023-06-28T06:12:42.828Z] /go/src/github.com/milvus-io/milvus/internal/rootcoord/create_collection_task.go:442 github.com/milvus-io/milvus/internal/rootcoord.(*createCollectionTask).Execute

[2023-06-28T06:12:42.828Z] /go/src/github.com/milvus-io/milvus/internal/rootcoord/scheduler.go:88 github.com/milvus-io/milvus/internal/rootcoord.(*scheduler).execute

[2023-06-28T06:12:42.828Z] /go/src/github.com/milvus-io/milvus/internal/rootcoord/scheduler.go:99 github.com/milvus-io/milvus/internal/rootcoord.(*scheduler).taskLoop

[2023-06-28T06:12:42.828Z] /usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit

[2023-06-28T06:12:42.828Z] )>, <Time:{'RPC start': '2023-06-28 06:12:41.514057', 'RPC error': '2023-06-28 06:12:41.525870'}> (decorators.py:108)

[2023-06-28T06:12:42.828Z] [2023-06-28 06:12:41 - ERROR - ci_test]: Traceback (most recent call last):

[2023-06-28T06:12:42.828Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2023-06-28T06:12:42.828Z]     res = func(*args, **_kwargs)

[2023-06-28T06:12:42.828Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2023-06-28T06:12:42.828Z]     return func(*arg, **kwargs)

[2023-06-28T06:12:42.828Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 124, in __init__

[2023-06-28T06:12:42.828Z]     conn.create_collection(self._name, schema, **kwargs)

[2023-06-28T06:12:42.828Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-06-28T06:12:42.828Z]     raise e

[2023-06-28T06:12:42.828Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-06-28T06:12:42.828Z]     return func(*args, **kwargs)

[2023-06-28T06:12:42.828Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-06-28T06:12:42.828Z]     ret = func(self, *args, **kwargs)

[2023-06-28T06:12:42.828Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-06-28T06:12:42.828Z]     raise e

[2023-06-28T06:12:42.828Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-06-28T06:12:42.828Z]     return func(self, *args, **kwargs)

[2023-06-28T06:12:42.828Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 252, in create_collection

[2023-06-28T06:12:42.828Z]     raise MilvusException(status.error_code, status.reason)

[2023-06-28T06:12:42.828Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=err: find no available datacoord, check datacoord state

[2023-06-28T06:12:42.828Z] , /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace

[2023-06-28T06:12:42.828Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:352 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall

[2023-06-28T06:12:42.829Z] /go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:583 github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).WatchChannels

[2023-06-28T06:12:42.829Z] /go/src/github.com/milvus-io/milvus/internal/rootcoord/broker.go:126 github.com/milvus-io/milvus/internal/rootcoord.(*ServerBroker).WatchChannels

[2023-06-28T06:12:42.829Z] /go/src/github.com/milvus-io/milvus/internal/rootcoord/step.go:115 github.com/milvus-io/milvus/internal/rootcoord.(*watchChannelsStep).Execute

[2023-06-28T06:12:42.829Z] /go/src/github.com/milvus-io/milvus/internal/rootcoord/undo.go:53 github.com/milvus-io/milvus/internal/rootcoord.(*baseUndoTask).Execute

[2023-06-28T06:12:42.829Z] /go/src/github.com/milvus-io/milvus/internal/rootcoord/create_collection_task.go:442 github.com/milvus-io/milvus/internal/rootcoord.(*createCollectionTask).Execute

[2023-06-28T06:12:42.829Z] /go/src/github.com/milvus-io/milvus/internal/rootcoord/scheduler.go:88 github.com/milvus-io/milvus/internal/rootcoord.(*scheduler).execute

[2023-06-28T06:12:42.829Z] /go/src/github.com/milvus-io/milvus/internal/rootcoord/scheduler.go:99 github.com/milvus-io/milvus/internal/rootcoord.(*scheduler).taskLoop

[2023-06-28T06:12:42.829Z] /usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit

[2023-06-28T06:12:42.829Z] )>

[2023-06-28T06:12:42.829Z]  (api_request.py:39)
```

```
[2023-06-28T06:12:45.198Z] + kubectl get pods -o wide

[2023-06-28T06:12:45.198Z] + grep rocksmq-standalone-reinstall-593

[2023-06-28T06:12:45.465Z] rocksmq-standalone-reinstall-593-etcd-0                           1/1     Running     0                9m29s   10.104.4.221    4am-node11   <none>           <none>

[2023-06-28T06:12:45.465Z] rocksmq-standalone-reinstall-593-etcd-1                           1/1     Running     0                9m29s   10.104.19.156   4am-node28   <none>           <none>

[2023-06-28T06:12:45.465Z] rocksmq-standalone-reinstall-593-etcd-2                           1/1     Running     0                9m29s   10.104.9.13     4am-node14   <none>           <none>

[2023-06-28T06:12:45.465Z] rocksmq-standalone-reinstall-593-milvus-standalone-85596bdnp8gg   0/1     Running     0                9m29s   10.104.19.154   4am-node28   <none>           <none>

[2023-06-28T06:12:45.465Z] rocksmq-standalone-reinstall-593-minio-8d9d6cfc8-pwqk9            1/1     Running     0                9m29s   10.104.19.155   4am-node28   <none>           <none>
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_for_release_cron/detail/deploy_test_for_release_cron/593/pipeline

log:
[artifacts-rocksmq-standalone-reinstall-593-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/11891075/artifacts-rocksmq-standalone-reinstall-593-server-logs.1.tar.gz)

[artifacts-rocksmq-standalone-reinstall-593-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/11891076/artifacts-rocksmq-standalone-reinstall-593-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
image tag: 2.2.0-20230706-e3a3680f

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_for_release_cron/detail/deploy_test_for_release_cron/631/pipeline
log:

[artifacts-rocksmq-standalone-reinstall-631-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/11979636/artifacts-rocksmq-standalone-reinstall-631-server-logs.1.tar.gz)

[artifacts-rocksmq-standalone-reinstall-631-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/11979637/artifacts-rocksmq-standalone-reinstall-631-pytest-logs.tar.gz)


Did not see the error log in the standalone pod, but can get some info from the pod describe.

```
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  14m                    default-scheduler  Successfully assigned chaos-testing/rocksmq-standalone-reinstall-631-milvus-standalone-7d5c4767nxzp to 4am-node22
  Normal   Pulled     14m                    kubelet            Container image "milvusdb/milvus-config-tool:v0.1.1" already present on machine
  Normal   Created    14m                    kubelet            Created container config
  Normal   Started    14m                    kubelet            Started container config
  Warning  Unhealthy  7m30s                  kubelet            Liveness probe failed: Get "http://10.104.20.192:9091/healthz": dial tcp 10.104.20.192:9091: connect: connection refused
  Warning  Unhealthy  7m30s                  kubelet            Readiness probe failed: Get "http://10.104.20.192:9091/healthz": dial tcp 10.104.20.192:9091: connect: connection refused
  Warning  Unhealthy  3m25s (x5 over 11m)    kubelet            Readiness probe failed: Get "http://10.104.20.192:9091/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  3m25s (x2 over 7m55s)  kubelet            Liveness probe failed: Get "http://10.104.20.192:9091/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  2m58s                  kubelet            Liveness probe failed: HTTP probe failed with statuscode: 500
  Warning  Unhealthy  2m50s (x3 over 3m9s)   kubelet            Readiness probe failed: HTTP probe failed with statuscode: 500
  Warning  BackOff    2m40s (x2 over 2m47s)  kubelet            Back-off restarting failed container
  Normal   Created    2m30s (x3 over 14m)    kubelet            Created container standalone
  Normal   Pulled     2m30s (x3 over 14m)    kubelet            Container image "harbor.milvus.io/dockerhub/milvusdb/milvus:2.2.0-20230706-e3a3680f" already present on machine
  Normal   Started    2m29s (x3 over 14m)    kubelet            Started container standalone
```

**Comment by zhuwenxing** [comment]
`9091` used to be the port for restful service, so is there anything gets changed?
