### ISSUE TITLE
[Bug]: Insert was denied when quotaAndLimits.enabled is set to false 

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#25246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230629-4501c426
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):kafka    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

use `--set quotaAndLimits.enabled=false` to disable quota and limit
 
```
[2023-06-29T12:29:08.729Z] + helm install --wait --timeout 1200s kafka-standalone-reinstall-1138 milvus/milvus --set image.all.repository=harbor.milvus.io/dockerhub/milvusdb/milvus --set image.all.tag=2.2.0-20230629-4501c426 --set metrics.serviceMonitor.enabled=true --set etcd.metrics.enabled=true --set etcd.metrics.podMonitor.enabled=true --set etcd.metrics.podMonitor.namespace=chaos-testing --set quotaAndLimits.enabled=false -f standalone-values.yaml
```

```

[2023-06-29T12:45:40.937Z] Create collection...

[2023-06-29T12:45:40.937Z] 2023-06-29 12:45:35.860 | INFO     | MainThread |utils:create_collections_and_insert_data:99 - collection name: task_2_IVF_FLAT

[2023-06-29T12:45:40.937Z] 2023-06-29 12:45:35.860 | INFO     | MainThread |utils:create_collections_and_insert_data:100 - begin insert, count: 3000 nb: 300

[2023-06-29T12:45:40.937Z] 2023-06-29 12:45:35.970 | INFO     | MainThread |utils:create_collections_and_insert_data:114 - [1/10] insert 300 data, time: 0.0641

[2023-06-29T12:45:40.937Z] 2023-06-29 12:45:39.101 | INFO     | MainThread |utils:create_collections_and_insert_data:114 - [2/10] insert 300 data, time: 0.0190

[2023-06-29T12:45:42.299Z] RPC error: [batch_insert], <MilvusException: (code=53, message=deny to write, reason: memory quota exhausted, please allocate more resources, req: /milvus.proto.milvus.MilvusService/Insert)>, <Time:{'RPC start': '2023-06-29 12:45:42.120692', 'RPC error': '2023-06-29 12:45:42.127538'}>

[2023-06-29T12:45:42.299Z] Traceback (most recent call last):

[2023-06-29T12:45:42.299Z]   File "scripts/action_before_reinstall.py", line 48, in <module>

[2023-06-29T12:45:42.299Z]     task_2(data_size, host)

[2023-06-29T12:45:42.299Z]   File "scripts/action_before_reinstall.py", line 32, in task_2

[2023-06-29T12:45:42.299Z]     create_collections_and_insert_data(prefix, count=data_size)

[2023-06-29T12:45:42.299Z]   File "/home/jenkins/agent/workspace/tests/python_client/deploy/scripts/utils.py", line 106, in create_collections_and_insert_data

[2023-06-29T12:45:42.299Z]     collection.insert(

[2023-06-29T12:45:42.299Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 443, in insert

[2023-06-29T12:45:42.299Z]     res = conn.batch_insert(self._name, entities, partition_name,

[2023-06-29T12:45:42.299Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-06-29T12:45:42.299Z]     raise e

[2023-06-29T12:45:42.299Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-06-29T12:45:42.299Z]     return func(*args, **kwargs)

[2023-06-29T12:45:42.299Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-06-29T12:45:42.299Z]     ret = func(self, *args, **kwargs)

[2023-06-29T12:45:42.299Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-06-29T12:45:42.299Z]     raise e

[2023-06-29T12:45:42.299Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-06-29T12:45:42.299Z]     return func(self, *args, **kwargs)

[2023-06-29T12:45:42.299Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 481, in batch_insert

[2023-06-29T12:45:42.299Z]     raise err

[2023-06-29T12:45:42.299Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 477, in batch_insert

[2023-06-29T12:45:42.299Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2023-06-29T12:45:42.299Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=53, message=deny to write, reason: memory quota exhausted, please allocate more resources, req: /milvus.proto.milvus.MilvusService/Insert)>
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_kafka_for_release_cron/detail/deploy_test_kafka_for_release_cron/1138/pipeline

log:
[artifacts-kafka-standalone-reinstall-1138-server-second-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/11912572/artifacts-kafka-standalone-reinstall-1138-server-second-deployment-logs.tar.gz)

[artifacts-kafka-standalone-reinstall-1138-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/11912573/artifacts-kafka-standalone-reinstall-1138-pytest-logs.tar.gz)

**Comment by bigsheeper** [comment]
![image](https://github.com/milvus-io/milvus/assets/42060877/1f1a0bd1-4488-43e2-b15e-79264593f00c)

seems `quotaAndLimits.enabled` param was not set properly.

**Comment by bigsheeper** [comment]
@LoveEachDay seems that this param has been removed from helm-chart? please help to make a verify.

**Comment by LoveEachDay** [comment]
@zhuwenxing @bigsheeper Yes, we have removed the `quotaAndLimits` in the helm charts values.yaml.
@zhuwenxing You should set this at `extraConfigFiles`.
