### ISSUE TITLE
[Bug]: Load failed after querynode pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#25302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230703-b68fa204
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```

[2023-07-03T21:25:39.951Z] [2023-07-03 21:23:32 - INFO - ci_test]: [test][2023-07-03T21:23:31Z] [1.01100957s] e2e__Lzw5JCuu create_index -> Status(code=0, message=) (wrapper.py:30)

[2023-07-03T21:25:39.951Z] [2023-07-03 21:23:32 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['varchar', {}], kwargs: {'timeout': 1200, 'index_name': 'test_qz77SRl0'} (api_request.py:56)

[2023-07-03T21:25:39.951Z] [2023-07-03 21:23:33 - DEBUG - ci_test]: (api_response) : Status(code=0, message=)  (api_request.py:31)

[2023-07-03T21:25:39.951Z] [2023-07-03 21:23:33 - INFO - ci_test]: [test][2023-07-03T21:23:32Z] [1.11934590s] e2e__Lzw5JCuu create_index -> Status(code=0, message=) (wrapper.py:30)

[2023-07-03T21:25:39.951Z] [2023-07-03 21:23:33 - INFO - ci_test]: assert index: 2.1307404041290283 (test_e2e.py:53)

[2023-07-03T21:25:39.951Z] [2023-07-03 21:23:33 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:56)

[2023-07-03T21:25:39.951Z] [2023-07-03 21:25:33 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=wait for loading collection timeout, collection: e2e__Lzw5JCuu)>, <Time:{'RPC start': '2023-07-03 21:23:33.534547', 'RPC error': '2023-07-03 21:25:33.756883'}> (decorators.py:108)

[2023-07-03T21:25:39.951Z] [2023-07-03 21:25:33 - WARNING - pymilvus.decorators]: Retry timeout: 120s (decorators.py:79)

[2023-07-03T21:25:39.951Z] [2023-07-03 21:25:33 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: e2e__Lzw5JCuu)>, <Time:{'RPC start': '2023-07-03 21:23:33.520213', 'RPC error': '2023-07-03 21:25:33.757299'}> (decorators.py:108)

[2023-07-03T21:25:39.951Z] [2023-07-03 21:25:33 - ERROR - ci_test]: Traceback (most recent call last):

[2023-07-03T21:25:39.951Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-07-03T21:25:39.951Z]     return func(self, *args, **kwargs)

[2023-07-03T21:25:39.951Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 791, in load_collection

[2023-07-03T21:25:39.951Z]     self.wait_for_loading_collection(collection_name, timeout, isRefresh=_refresh)

[2023-07-03T21:25:39.951Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-07-03T21:25:39.951Z]     raise e

[2023-07-03T21:25:39.951Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-07-03T21:25:39.951Z]     return func(*args, **kwargs)

[2023-07-03T21:25:39.951Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-07-03T21:25:39.951Z]     ret = func(self, *args, **kwargs)

[2023-07-03T21:25:39.952Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-07-03T21:25:39.952Z]     raise e

[2023-07-03T21:25:39.952Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-07-03T21:25:39.952Z]     return func(self, *args, **kwargs)

[2023-07-03T21:25:39.952Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 813, in wait_for_loading_collection

[2023-07-03T21:25:39.952Z]     raise MilvusException(message=f"wait for loading collection timeout, collection: {collection_name}")

[2023-07-03T21:25:39.952Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=wait for loading collection timeout, collection: e2e__Lzw5JCuu)>

[2023-07-03T21:25:39.952Z] 

[2023-07-03T21:25:39.952Z] The above exception was the direct cause of the following exception:

[2023-07-03T21:25:39.952Z] 

[2023-07-03T21:25:39.952Z] Traceback (most recent call last):

[2023-07-03T21:25:39.952Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2023-07-03T21:25:39.952Z]     res = func(*args, **_kwargs)

[2023-07-03T21:25:39.952Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2023-07-03T21:25:39.952Z]     return func(*arg, **kwargs)

[2023-07-03T21:25:39.952Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 376, in load

[2023-07-03T21:25:39.952Z]     conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)

[2023-07-03T21:25:39.952Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-07-03T21:25:39.952Z]     raise e

[2023-07-03T21:25:39.952Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-07-03T21:25:39.952Z]     return func(*args, **kwargs)

[2023-07-03T21:25:39.952Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-07-03T21:25:39.952Z]     ret = func(self, *args, **kwargs)

[2023-07-03T21:25:39.952Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 80, in handler

[2023-07-03T21:25:39.952Z]     raise MilvusException(e.code, f"{timeout_msg}, message={e.message}") from e

[2023-07-03T21:25:39.952Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: e2e__Lzw5JCuu)>

[2023-07-03T21:25:39.952Z]  (api_request.py:39)

[2023-07-03T21:25:39.952Z] [2023-07-03 21:25:33 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: e2e__Lzw5JCuu)> (api_request.py:40)
```

```

[2023-07-03T21:25:44.663Z] [2023-07-03 21:23:37 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:56)

[2023-07-03T21:25:44.663Z] [2023-07-03 21:25:37 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=wait for loading collection timeout, collection: Hello_Milvus)>, <Time:{'RPC start': '2023-07-03 21:23:37.691234', 'RPC error': '2023-07-03 21:25:37.778099'}> (decorators.py:108)

[2023-07-03T21:25:44.664Z] [2023-07-03 21:25:37 - WARNING - pymilvus.decorators]: Retry timeout: 120s (decorators.py:79)

[2023-07-03T21:25:44.664Z] [2023-07-03 21:25:37 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: Hello_Milvus)>, <Time:{'RPC start': '2023-07-03 21:23:37.678734', 'RPC error': '2023-07-03 21:25:37.778487'}> (decorators.py:108)

[2023-07-03T21:25:44.664Z] [2023-07-03 21:25:37 - ERROR - ci_test]: Traceback (most recent call last):

[2023-07-03T21:25:44.664Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-07-03T21:25:44.664Z]     return func(self, *args, **kwargs)

[2023-07-03T21:25:44.664Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 791, in load_collection

[2023-07-03T21:25:44.664Z]     self.wait_for_loading_collection(collection_name, timeout, isRefresh=_refresh)

[2023-07-03T21:25:44.664Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-07-03T21:25:44.664Z]     raise e

[2023-07-03T21:25:44.664Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-07-03T21:25:44.664Z]     return func(*args, **kwargs)

[2023-07-03T21:25:44.664Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-07-03T21:25:44.664Z]     ret = func(self, *args, **kwargs)

[2023-07-03T21:25:44.664Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-07-03T21:25:44.664Z]     raise e

[2023-07-03T21:25:44.664Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-07-03T21:25:44.664Z]     return func(self, *args, **kwargs)

[2023-07-03T21:25:44.664Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 813, in wait_for_loading_collection

[2023-07-03T21:25:44.664Z]     raise MilvusException(message=f"wait for loading collection timeout, collection: {collection_name}")

[2023-07-03T21:25:44.664Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=wait for loading collection timeout, collection: Hello_Milvus)>

[2023-07-03T21:25:44.664Z] 

[2023-07-03T21:25:44.664Z] The above exception was the direct cause of the following exception:

[2023-07-03T21:25:44.664Z] 

[2023-07-03T21:25:44.664Z] Traceback (most recent call last):

[2023-07-03T21:25:44.664Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2023-07-03T21:25:44.664Z]     res = func(*args, **_kwargs)

[2023-07-03T21:25:44.664Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2023-07-03T21:25:44.664Z]     return func(*arg, **kwargs)

[2023-07-03T21:25:44.664Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 376, in load

[2023-07-03T21:25:44.664Z]     conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)

[2023-07-03T21:25:44.664Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-07-03T21:25:44.664Z]     raise e

[2023-07-03T21:25:44.664Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-07-03T21:25:44.664Z]     return func(*args, **kwargs)

[2023-07-03T21:25:44.664Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-07-03T21:25:44.664Z]     ret = func(self, *args, **kwargs)

[2023-07-03T21:25:44.664Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 80, in handler

[2023-07-03T21:25:44.664Z]     raise MilvusException(e.code, f"{timeout_msg}, message={e.message}") from e

[2023-07-03T21:25:44.664Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: Hello_Milvus)>
```

```

[2023-07-03T21:28:26.807Z] [2023-07-03 21:23:45 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:56)

[2023-07-03T21:28:26.807Z] [2023-07-03 21:25:46 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=wait for loading collection timeout, collection: Checker__4DMXLJDQ)>, <Time:{'RPC start': '2023-07-03 21:23:45.883370', 'RPC error': '2023-07-03 21:25:46.051086'}> (decorators.py:108)

[2023-07-03T21:28:26.807Z] [2023-07-03 21:25:46 - WARNING - pymilvus.decorators]: Retry timeout: 120s (decorators.py:79)

[2023-07-03T21:28:26.807Z] [2023-07-03 21:25:46 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: Checker__4DMXLJDQ)>, <Time:{'RPC start': '2023-07-03 21:23:45.869841', 'RPC error': '2023-07-03 21:25:46.051417'}> (decorators.py:108)

[2023-07-03T21:28:26.807Z] [2023-07-03 21:25:46 - ERROR - ci_test]: Traceback (most recent call last):

[2023-07-03T21:28:26.807Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-07-03T21:28:26.807Z]     return func(self, *args, **kwargs)

[2023-07-03T21:28:26.807Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 791, in load_collection

[2023-07-03T21:28:26.807Z]     self.wait_for_loading_collection(collection_name, timeout, isRefresh=_refresh)

[2023-07-03T21:28:26.807Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-07-03T21:28:26.807Z]     raise e

[2023-07-03T21:28:26.807Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-07-03T21:28:26.807Z]     return func(*args, **kwargs)

[2023-07-03T21:28:26.807Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-07-03T21:28:26.807Z]     ret = func(self, *args, **kwargs)

[2023-07-03T21:28:26.807Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2023-07-03T21:28:26.807Z]     raise e

[2023-07-03T21:28:26.807Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 50, in handler

[2023-07-03T21:28:26.807Z]     return func(self, *args, **kwargs)

[2023-07-03T21:28:26.807Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 813, in wait_for_loading_collection

[2023-07-03T21:28:26.807Z]     raise MilvusException(message=f"wait for loading collection timeout, collection: {collection_name}")

[2023-07-03T21:28:26.807Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=wait for loading collection timeout, collection: Checker__4DMXLJDQ)>

[2023-07-03T21:28:26.807Z] 

[2023-07-03T21:28:26.807Z] The above exception was the direct cause of the following exception:

[2023-07-03T21:28:26.807Z] 

[2023-07-03T21:28:26.807Z] Traceback (most recent call last):

[2023-07-03T21:28:26.807Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2023-07-03T21:28:26.807Z]     res = func(*args, **_kwargs)

[2023-07-03T21:28:26.807Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2023-07-03T21:28:26.807Z]     return func(*arg, **kwargs)

[2023-07-03T21:28:26.807Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 376, in load

[2023-07-03T21:28:26.807Z]     conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)

[2023-07-03T21:28:26.807Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 109, in handler

[2023-07-03T21:28:26.807Z]     raise e

[2023-07-03T21:28:26.807Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 105, in handler

[2023-07-03T21:28:26.807Z]     return func(*args, **kwargs)

[2023-07-03T21:28:26.807Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2023-07-03T21:28:26.807Z]     ret = func(self, *args, **kwargs)

[2023-07-03T21:28:26.807Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 80, in handler

[2023-07-03T21:28:26.807Z]     raise MilvusException(e.code, f"{timeout_msg}, message={e.message}") from e

[2023-07-03T21:28:26.807Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: Checker__4DMXLJDQ)>
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/5481/pipeline

log:

[artifacts-querynode-pod-kill-5481-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/11943762/artifacts-querynode-pod-kill-5481-server-logs.tar.gz)

[artifacts-querynode-pod-kill-5481-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/11943756/artifacts-querynode-pod-kill-5481-pytest-logs.tar.gz)

**Comment by aoiasd** [comment]
Querynode distribution not filter invalid segment out when update target version.So if collection have more than one shard, will get error.
Fixed by: https://github.com/milvus-io/milvus/pull/25337

**Comment by jiaoew1991** [comment]
please verify it 

/assign @zhuwenxing 
/unassign @aoiasd

**Comment by zhuwenxing** [comment]
Verification is blocked by https://github.com/milvus-io/milvus/issues/25362

**Comment by binbinlv** [comment]
@zhuwenxing #25362 is closed, and could you verify this issue? Thanks.

**Comment by zhuwenxing** [comment]
Not reproduced in master-20230809-d267559b
