### ISSUE TITLE
[Bug]: [Nightly]Many test cases failed for creating index and timeout in 1200s

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#25325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:3e055a5
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.13.dev3
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Many test cases failed for creating index and timeout in 1200s.
```
[2023-07-04T22:03:24.650Z] [2023-07-04 20:26:35 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['float_vector', {'index_type': 'DISKANN', 'params': {}, 'metric_type': 'L2'}], kwargs: {'timeout': 1200, 'index_name': ''} (api_request.py:56)
[2023-07-04T22:03:24.650Z] [2023-07-04 20:46:36 - WARNING - pymilvus.decorators]: [93mRetry timeout: 1200s[0m (decorators.py:79)
[2023-07-04T22:03:24.650Z] [2023-07-04 20:46:36 - ERROR - pymilvus.decorators]: RPC error: [wait_for_creating_index], <MilvusException: (code=1, message=Retry timeout: 1200s, message=collection search_collection_1Bo58I6x create index  timeout in 1200s)>, <Time:{'RPC start': '2023-07-04 20:26:35.869400', 'RPC error': '2023-07-04 20:46:36.130865'}> (decorators.py:108)
[2023-07-04T22:03:24.650Z] [2023-07-04 20:46:36 - WARNING - pymilvus.decorators]: [93mRetry timeout: 1200s[0m (decorators.py:79)
[2023-07-04T22:03:24.650Z] [2023-07-04 20:46:36 - ERROR - pymilvus.decorators]: RPC error: [create_index], <MilvusException: (code=1, message=Retry timeout: 1200s, message=Retry timeout: 1200s, message=collection search_collection_1Bo58I6x create index  timeout in 1200s)>, <Time:{'RPC start': '2023-07-04 20:26:35.850210', 'RPC error': '2023-07-04 20:46:36.131033'}> (decorators.py:108)
[2023-07-04T22:03:24.650Z] [2023-07-04 20:46:36 - ERROR - ci_test]: Traceback (most recent call last):
[2023-07-04T22:03:24.650Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2023-07-04T22:03:24.650Z]     return func(self, *args, **kwargs)
[2023-07-04T22:03:24.650Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 721, in wait_for_creating_index
[2023-07-04T22:03:24.650Z]     raise MilvusException(message=f"collection {collection_name} create index {index_name} timeout in {timeout}s")
[2023-07-04T22:03:24.650Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection search_collection_1Bo58I6x create index  timeout in 1200s)>
[2023-07-04T22:03:24.650Z] 
[2023-07-04T22:03:24.650Z] The above exception was the direct cause of the following exception:
[2023-07-04T22:03:24.650Z] 
[2023-07-04T22:03:24.650Z] Traceback (most recent call last):
[2023-07-04T22:03:24.650Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2023-07-04T22:03:24.650Z]     return func(self, *args, **kwargs)
[2023-07-04T22:03:24.650Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 630, in create_index
[2023-07-04T22:03:24.650Z]     index_success, fail_reason = self.wait_for_creating_index(collection_name=collection_name,
[2023-07-04T22:03:24.650Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2023-07-04T22:03:24.650Z]     raise e
[2023-07-04T22:03:24.650Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2023-07-04T22:03:24.650Z]     return func(*args, **kwargs)
[2023-07-04T22:03:24.650Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2023-07-04T22:03:24.650Z]     ret = func(self, *args, **kwargs)
[2023-07-04T22:03:24.650Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 80, in handler
[2023-07-04T22:03:24.650Z]     raise MilvusException(e.code, f"{timeout_msg}, message={e.message}") from e
[2023-07-04T22:03:24.650Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 1200s, message=collection search_collection_1Bo58I6x create index  timeout in 1200s)>
[2023-07-04T22:03:24.650Z] 
[2023-07-04T22:03:24.650Z] The above exception was the direct cause of the following exception:
[2023-07-04T22:03:24.650Z] 
[2023-07-04T22:03:24.650Z] Traceback (most recent call last):
[2023-07-04T22:03:24.650Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2023-07-04T22:03:24.650Z]     res = func(*args, **_kwargs)
[2023-07-04T22:03:24.650Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2023-07-04T22:03:24.650Z]     return func(*arg, **kwargs)
[2023-07-04T22:03:24.650Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 968, in create_index
[2023-07-04T22:03:24.650Z]     return conn.create_index(self._name, field_name, index_params, timeout=timeout, **kwargs)
[2023-07-04T22:03:24.650Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2023-07-04T22:03:24.650Z]     raise e
[2023-07-04T22:03:24.650Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2023-07-04T22:03:24.650Z]     return func(*args, **kwargs)
[2023-07-04T22:03:24.650Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2023-07-04T22:03:24.650Z]     ret = func(self, *args, **kwargs)
[2023-07-04T22:03:24.650Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 80, in handler
[2023-07-04T22:03:24.650Z]     raise MilvusException(e.code, f"{timeout_msg}, message={e.message}") from e
[2023-07-04T22:03:24.650Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 1200s, message=Retry timeout: 1200s, message=collection search_collection_1Bo58I6x create index  timeout in 1200s)>
[2023-07-04T22:03:24.650Z]  (api_request.py:39)
[2023-07-04T22:03:24.650Z] [2023-07-04 20:46:36 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 1200s, message=Retry timeout: 1200s, message=collection search_collection_1Bo58I6x create index  timeout in 1200s)> (api_request.py:40)
```

### Expected Behavior

pass

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/242/pipeline/124/
2. log: [artifacts-milvus-standalone-nightly-242-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/242/artifact/artifacts-milvus-standalone-nightly-242-pymilvus-e2e-logs.tar.gz)
3. failed time: [2023-07-04T20:46:36.677Z] [gw3] [ 47%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_after_different_index_with_params[128-True-False-True-DISKANN-params6]
4. collection name: search_collection_1Bo58I6x

**Comment by NicoYuan1986** [comment]
This issue has not come up recently
