### ISSUE TITLE
[Bug]: Failed to upgrade from 2.2.8 to 2.2.11 and unable to roll back

### ISSUE THREAD

**Issue by darkerin** [milvus-io/milvus#25321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.8 -> 2.2.11
- Deployment mode(standalone or cluster): standalone 
- MQ type(rocksmq, pulsar or kafka): rocksmq   
- SDK version(e.g. pymilvus v2.0.0rc2): /
- OS(Ubuntu or CentOS):  ubuntu
- CPU/Memory: 4C 8G
- GPU: 
- Others:
```

### Current Behavior

I am trying to upgrade from 2.2.8 to 2.2.11. After downloading the latest docker-compose.yml file and starting it, I encountered an error. 
```
milvus-standalone  | [2023/07/04 14:00:36.807 +00:00] [WARN] [client/client.go:98] ["DataCoordClient, not existed in msess "] [key=datacoord] ["len of msess"=0]
milvus-standalone  | [2023/07/04 14:00:36.807 +00:00] [WARN] [storage/minio_chunk_manager.go:118] ["failed to check blob bucket exist"] [bucket=a-bucket] [error="Get \"http://minio:9000/a-bucket/?location=\": dial tcp: lookup minio: Temporary failure in name resolution"]
milvus-standalone  | [2023/07/04 14:00:36.807 +00:00] [ERROR] [grpcclient/client.go:161] ["failed to get client address"] [error="find no available datacoord, check datacoord state"] [stack="github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).connect\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:161\ngithub.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).GetGrpcClient\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:134\ngithub.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).callOnce\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:271\ngithub.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:350\ngithub.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).GetComponentStates\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:126\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates.func1\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:67\ngithub.com/milvus-io/milvus/internal/util/retry.Do\n\t/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:42\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:91\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentInitOrHealthy\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:96\ngithub.com/milvus-io/milvus/internal/distributed/datanode.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datanode/service.go:306\ngithub.com/milvus-io/milvus/internal/distributed/datanode.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datanode/service.go:177\ngithub.com/milvus-io/milvus/cmd/components.(*DataNode).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/data_node.go:52\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:120"]
milvus-standalone  | [2023/07/04 14:00:36.807 +00:00] [ERROR] [grpcclient/client.go:353] ["ClientBase ReCall grpc second call get error"] [role=datacoord] [error="err: find no available datacoord, check datacoord state\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:352 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:126 github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).GetComponentStates\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:67 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates.func1\n/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:42 github.com/milvus-io/milvus/internal/util/retry.Do\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:91 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates\n/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:96 github.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentInitOrHealthy\n/go/src/github.com/milvus-io/milvus/internal/distributed/datanode/service.go:306 github.com/milvus-io/milvus/internal/distributed/datanode.(*Server).init\n/go/src/github.com/milvus-io/milvus/internal/distributed/datanode/service.go:177 github.com/milvus-io/milvus/internal/distributed/datanode.(*Server).Run\n/go/src/github.com/milvus-io/milvus/cmd/components/data_node.go:52 github.com/milvus-io/milvus/cmd/components.(*DataNode).Run\n"] [stack="github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:353\ngithub.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).GetComponentStates\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:126\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates.func1\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:67\ngithub.com/milvus-io/milvus/internal/util/retry.Do\n\t/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:42\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:91\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentInitOrHealthy\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:96\ngithub.com/milvus-io/milvus/internal/distributed/datanode.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datanode/service.go:306\ngithub.com/milvus-io/milvus/internal/distributed/datanode.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datanode/service.go:177\ngithub.com/milvus-io/milvus/cmd/components.(*DataNode).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/data_node.go:52\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:120"]
milvus-standalone  | [2023/07/04 14:00:36.815 +00:00] [WARN] [storage/minio_chunk_manager.go:118] ["failed to check blob bucket exist"] [bucket=a-bucket] [error="Get \"http://minio:9000/a-bucket/?location=\": dial tcp: lookup minio: Temporary failure in name resolution"]
milvus-standalone  | [2023/07/04 14:00:36.896 +00:00] [WARN] [client/client.go:98] ["DataCoordClient, not existed in msess "] [key=datacoord] ["len of msess"=0]
milvus-standalone  | [2023/07/04 14:00:36.896 +00:00] [ERROR] [grpcclient/client.go:161] ["failed to get client address"] [error="find no available datacoord, check datacoord state"] [stack="github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).connect\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:161\ngithub.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).GetGrpcClient\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:134\ngithub.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).callOnce\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:271\ngithub.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n\t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:335\ngithub.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).GetComponentStates\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:126\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates.func1\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:67\ngithub.com/milvus-io/milvus/internal/util/retry.Do\n\t/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:42\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentStates\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:91\ngithub.com/milvus-io/milvus/internal/util/funcutil.WaitForComponentHealthy\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/func.go:106\ngithub.com/milvus-io/milvus/internal/distributed/proxy.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:416\ngithub.com/milvus-io/milvus/internal/distributed/proxy.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:298\ngithub.com/milvus-io/milvus/cmd/components.(*Proxy).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/proxy.go:51\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:120"]
```

Then, when I switched back to the docker-compose of version 2.2.8, I found that it couldn't start either.

```
milvus-standalone  | panic: Not implemented: Unsupported compression method for this build: ZSTD
milvus-standalone  | 
milvus-standalone  | goroutine 1 [running]:
milvus-standalone  | github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run(0xc000f8fe58, 0x1, {0x0, 0x0})
milvus-standalone  |    /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:214 +0xd95
milvus-standalone  | github.com/milvus-io/milvus/cmd/milvus.(*run).execute(0xc00053ad50, {0xc00004e090?, 0x3, 0x3}, 0xc000115b00)
milvus-standalone  |    /go/src/github.com/milvus-io/milvus/cmd/milvus/run.go:112 +0x66e
milvus-standalone  | github.com/milvus-io/milvus/cmd/milvus.RunMilvus({0xc00004e090?, 0x3, 0x3})
milvus-standalone  |    /go/src/github.com/milvus-io/milvus/cmd/milvus/milvus.go:60 +0x21e
milvus-standalone  | main.main()
milvus-standalone  |    /go/src/github.com/milvus-io/milvus/cmd/main.go:26 +0x2e
```

**Comment by xiaofan-luan** [comment]
milvus-standalone  | [2023/07/04 14:00:36.807 +00:00] [WARN] [storage/minio_chunk_manager.go:118] ["failed to check blob bucket exist"] [bucket=a-bucket] [error="Get \"http://minio:9000/a-bucket/?location=\": dial tcp: lookup minio: Temporary failure in name resolution"

**Comment by darkerin** [comment]
I've noticed an issue. My minio version is from 2022, and the docker-compose.yml file I obtained from the Milvus official website on May 2nd. I don't know if there could be any connection between them?
···
version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2022-03-17T06-34-49Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.2.8
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"

networks:
  default:
    name: milvusubuntu@VM-0-15-ubuntu:/usr/local/milvus$ 
···

**Comment by darkerin** [comment]
> 2.2.11 standalone can not rollback to 2.2.8 because rocksmq change compression method.
> 
> I would suggest you to use 2.2.11, from the log you shared it's simply because you name service is not working . Wait for a while maybe the dns would recover itself. you need to offer full log so we can investigate why this happened.
> 
> meanwhile, if you want to rollback to 2.2.8, the easiest way is to remove rocksdb data directory. you may lost the write in the last few minutes if you do so

After waiting for 20 minutes, I still encountered an error, here are full log:

[milvus.log](https://github.com/milvus-io/milvus/files/11950375/milvus.log)

**Comment by zhuwenxing** [comment]
Can you take a look at minio container? If the minio iamge tag is `minio/minio:RELEASE.2022-03-17T06-34-49Z` for v2.2.8 and the dockerfile for v2.2.11 is the latest docker-compose.yaml,  then the minio image should be `minio/minio:RELEASE.2023-03-20T20-16-18Z`.  There will be incompatibility between the two minio images, so you could choose to keep minio version same.

**Comment by darkerin** [comment]
> Can you take a look at minio container? If the minio image tag is `minio/minio:RELEASE.2022-03-17T06-34-49Z` for v2.2.8 and the dockerfile for v2.2.11 is the latest docker-compose.yaml, then the minio image should be `minio/minio:RELEASE.2023-03-20T20-16-18Z`. There will be incompatibility between the two minio images, so you could choose to keep minio version same.

Yes, version 2.2.8 of Minio is `minio/minio:RELEASE.2022-03-17T06-34-49Z`, but the docker-compose.yml file I obtained from the official website was different from the one on [GitHub release](https://github.com/milvus-io/milvus/releases/tag/v2.2.8). What could be the reason for this? 
If I downgrade the Minio version to `minio/minio:RELEASE.2022-03-17T06-34-49Z`, will it still be compatible with v2.2.11?

**Comment by darkerin** [comment]
> Can you take a look at minio container? If the minio image tag is `minio/minio:RELEASE.2022-03-17T06-34-49Z` for v2.2.8 and the dockerfile for v2.2.11 is the latest docker-compose.yaml, then the minio image should be `minio/minio:RELEASE.2023-03-20T20-16-18Z`. There will be incompatibility between the two minio images, so you could choose to keep minio version same.

Thanks, now it works.

**Comment by zhuwenxing** [comment]
>If I downgrade the Minio version to minio/minio:RELEASE.2022-03-17T06-34-49Z, will it still be compatible with v2.2.11?

Yes, `minio/minio:RELEASE.2022-03-17T06-34-49Z` can work with Milvus v2.2.11. The reason we upgrade the version of minio is because of a security  issue https://github.com/milvus-io/milvus/issues/24646
