### ISSUE TITLE
[Bug]: [Nightly]Many cases using DISKANN index failed for loading collection timeout in cluster mode

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#25327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:3e055a5
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.13.dev3
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Many cases using DISKANN index failed for loading collection timeout.
```
[2023-07-04T21:23:50.216Z] [2023-07-04 20:26:43 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=wait for loading collection timeout, collection: search_collection_EXoj24BB)>, <Time:{'RPC start': '2023-07-04 20:24:43.154923', 'RPC error': '2023-07-04 20:26:43.294113'}> (decorators.py:108)
[2023-07-04T21:23:50.216Z] [2023-07-04 20:26:43 - WARNING - pymilvus.decorators]: [93mRetry timeout: 120s[0m (decorators.py:79)
[2023-07-04T21:23:50.216Z] [2023-07-04 20:26:43 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: search_collection_EXoj24BB)>, <Time:{'RPC start': '2023-07-04 20:24:43.125142', 'RPC error': '2023-07-04 20:26:43.294855'}> (decorators.py:108)
[2023-07-04T21:23:50.216Z] [2023-07-04 20:26:43 - ERROR - ci_test]: Traceback (most recent call last):
[2023-07-04T21:23:50.216Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2023-07-04T21:23:50.216Z]     return func(self, *args, **kwargs)
[2023-07-04T21:23:50.216Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 735, in load_collection
[2023-07-04T21:23:50.216Z]     self.wait_for_loading_collection(collection_name, timeout)
[2023-07-04T21:23:50.216Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2023-07-04T21:23:50.216Z]     raise e
[2023-07-04T21:23:50.216Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2023-07-04T21:23:50.216Z]     return func(*args, **kwargs)
[2023-07-04T21:23:50.216Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2023-07-04T21:23:50.216Z]     ret = func(self, *args, **kwargs)
[2023-07-04T21:23:50.216Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
[2023-07-04T21:23:50.216Z]     raise e
[2023-07-04T21:23:50.216Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
[2023-07-04T21:23:50.216Z]     return func(self, *args, **kwargs)
[2023-07-04T21:23:50.216Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 757, in wait_for_loading_collection
[2023-07-04T21:23:50.216Z]     raise MilvusException(message=f"wait for loading collection timeout, collection: {collection_name}")
[2023-07-04T21:23:50.216Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=wait for loading collection timeout, collection: search_collection_EXoj24BB)>
[2023-07-04T21:23:50.216Z] 
[2023-07-04T21:23:50.216Z] The above exception was the direct cause of the following exception:
[2023-07-04T21:23:50.216Z] 
[2023-07-04T21:23:50.216Z] Traceback (most recent call last):
[2023-07-04T21:23:50.216Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2023-07-04T21:23:50.216Z]     res = func(*args, **_kwargs)
[2023-07-04T21:23:50.216Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2023-07-04T21:23:50.216Z]     return func(*arg, **kwargs)
[2023-07-04T21:23:50.216Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 376, in load
[2023-07-04T21:23:50.216Z]     conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
[2023-07-04T21:23:50.216Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
[2023-07-04T21:23:50.216Z]     raise e
[2023-07-04T21:23:50.216Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
[2023-07-04T21:23:50.216Z]     return func(*args, **kwargs)
[2023-07-04T21:23:50.216Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2023-07-04T21:23:50.216Z]     ret = func(self, *args, **kwargs)
[2023-07-04T21:23:50.216Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 80, in handler
[2023-07-04T21:23:50.217Z]     raise MilvusException(e.code, f"{timeout_msg}, message={e.message}") from e
[2023-07-04T21:23:50.217Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: search_collection_EXoj24BB)>
[2023-07-04T21:23:50.217Z]  (api_request.py:39)
[2023-07-04T21:23:50.217Z] [2023-07-04 20:26:43 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: search_collection_EXoj24BB)> (api_request.py:40)

```

### Expected Behavior

succeed

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/242/pipeline/156
2. log: [artifacts-milvus-distributed-kafka-nightly-242-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/242/artifact/artifacts-milvus-distributed-kafka-nightly-242-pymilvus-e2e-logs.tar.gz)
3. collection name: search_collection_EXoj24BB
4. failed time: [2023-07-04T20:26:43.891Z] [gw0] [ 42%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_after_index_different_metric_type[128-False-False-False-DISKANN-params6]

**Comment by NicoYuan1986** [comment]
similar:
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/423/pipeline/241/

**Comment by NicoYuan1986** [comment]
Update: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/244/pipeline/188/

**Comment by aoiasd** [comment]
![image](https://github.com/milvus-io/milvus/assets/45024769/28b0cd23-d4e3-469f-9e77-f30391283581)
![image](https://github.com/milvus-io/milvus/assets/45024769/aba73069-67f3-4e80-9c1a-22053dbd29db)
Disknn index prepare from config failed.

**Comment by aoiasd** [comment]
same with https://github.com/milvus-io/milvus/issues/25350
 2.2.0 error with io_submit
![image](https://github.com/milvus-io/milvus/assets/45024769/4ec15998-abad-4e14-b7c1-8c0b9fd333fb)

**Comment by NicoYuan1986** [comment]
keep reproducing

**Comment by NicoYuan1986** [comment]
not reproduced.  2.2.0-20230718-f5983722

**Comment by yanliang567** [comment]
not reproduced after updating aio-max-nr  to a bigger value
