### ISSUE TITLE
[Bug]: search failed with error  Param 'ef'(10) is not in range [30, 9223372036854775807] err

### ISSUE THREAD

**Issue by eechenyi** [milvus-io/milvus#25364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:  milvus:v2.2.10 
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.2.13
- OS(Ubuntu or CentOS): docker
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

execute code：
 docs = milvus.similarity_search(querystr, k=30)
collection:
![image](https://github.com/milvus-io/milvus/assets/67175449/f4b1217d-16ae-4718-8f5e-c5bbfe4bd6ce)

RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:
attempt #1:code: UnexpectedError, error: fail to Search, QueryNode ID=18, reason=Search 18 failed, reason [UnexpectedError] Assert "false" at /go/src/github.com/milvus-io/milvus/internal/core/src/index/VectorMemIndex.cpp:169
 => Error in void knowhere::CheckIntegerRange(const Config&, const string&, int64_t, int64_t) at ConfAdapter.cpp:58: Param 'ef'(10) is not in range [30, 9223372036854775807] err %!w(<nil>)
attempt #2:context canceled
)>, <Time:{'RPC start': '2023-07-06 14:22:32.631692', 'RPC error': '2023-07-06 14:22:32.848619'}>
Traceback (most recent call last):
  File "/Users/anker/cy/code/python/gpt-service/app/services/gpt_qa_milvus.py", line 84, in <module>
    result = server.get_gpt_answer(query,"")
  File "/Users/anker/cy/code/python/gpt-service/app/services/gpt_qa_milvus.py", line 44, in get_gpt_answer
    docs = self.get_match_doc(new_query)
  File "/Users/anker/cy/code/python/gpt-service/app/services/gpt_qa_milvus.py", line 67, in get_match_doc
    docs = milvus.similarity_search(querystr, k=30)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/langchain/vectorstores/milvus.py", line 476, in similarity_search
    res = self.similarity_search_with_score(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/langchain/vectorstores/milvus.py", line 548, in similarity_search_with_score
    res = self.similarity_search_with_score_by_vector(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/langchain/vectorstores/milvus.py", line 593, in similarity_search_with_score_by_vector
    res = self.col.search(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymilvus/orm/collection.py", line 629, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymilvus/client/grpc_handler.py", line 544, in search
    return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymilvus/client/grpc_handler.py", line 524, in _execute_search_requests
    raise pre_err
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymilvus/client/grpc_handler.py", line 515, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:
attempt #1:code: UnexpectedError, error: fail to Search, QueryNode ID=18, reason=Search 18 failed, reason [UnexpectedError] Assert "false" at /go/src/github.com/milvus-io/milvus/internal/core/src/index/VectorMemIndex.cpp:169
 => Error in void knowhere::CheckIntegerRange(const Config&, const string&, int64_t, int64_t) at ConfAdapter.cpp:58: Param 'ef'(10) is not in range [30, 9223372036854775807] err %!w(<nil>)
attempt #2:context canceled
)>

**Comment by eechenyi** [comment]
create collection code
![image](https://github.com/milvus-io/milvus/assets/67175449/db2cdb94-fc35-47df-a86b-248a3a92628b)

**Comment by yanliang567** [comment]
@eechenyi thank you for the issue. it seems that you gives a too small ef(10) in search params for a topk=30 searching request. could you please retry with ef=30? Or please share the code of similarity_search() to investigate?

/assign @eechenyi 
/unassign

**Comment by talhaanwarch** [comment]
@yanliang567 i am getting this error to, where can i get the function where `ef` is parameter?

**Comment by yanliang567** [comment]
ef is one of search parameters when you set index type as HNSW. check here for more info: https://milvus.io/docs/search.md#Prepare-search-parameters
