### ISSUE TITLE
[Bug]: Insert data with auto_id=False will raise error using pymilvus==2.2.14.dev2

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#25413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-20230707-56c32d3b
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.14.dev2
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Insert data with auto_id=False will raise error using pymilvus==2.2.14.dev2.

```
pytest test_search.py::TestCollectionSearch::test_search_with_output_field

[2023-07-07 16:31:31 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [      int64  ...                                       float_vector
0         0  ...  [0.13093560290659081, 0.09078615952885524, 0.1...
1         1  ...  [0.14815669857605315, 0.07793621287363173, 0.1...
2         2  ...  [0.011056403849351608, 0.044871117504637494, 0...
3         3  ...  [0.006722......, kwargs: {'timeout': 120} (api_request.py:56)
[2023-07-07 16:31:35 - ERROR - pymilvus.decorators]: RPC error: [batch_insert], <MilvusException: (code=1, message=currently only support DataType Int64 or VarChar as PrimaryField)>, <Time:{'RPC start': '2023-07-07 16:31:31.338969', 'RPC error': '2023-07-07 16:31:35.333566'}> (decorators.py:119)
[2023-07-07 16:31:35 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/zilliz/nico/2.2/milvus/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/Users/zilliz/nico/2.2/milvus/tests/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.10/site-packages/pymilvus/orm/collection.py", line 495, in insert
    res = conn.batch_insert(
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.10/site-packages/pymilvus/decorators.py", line 120, in handler
    raise e from e
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.10/site-packages/pymilvus/decorators.py", line 116, in handler
    return func(*args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.10/site-packages/pymilvus/decorators.py", line 155, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.10/site-packages/pymilvus/decorators.py", line 95, in handler
    raise e from e
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.10/site-packages/pymilvus/decorators.py", line 68, in handler
    return func(*args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 559, in batch_insert
    raise err from err
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 555, in batch_insert
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=currently only support DataType Int64 or VarChar as PrimaryField)>
 (api_request.py:39)
[2023-07-07 16:31:35 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=currently only support DataType Int64 or VarChar as PrimaryField)> (api_request.py:40)

```

### Expected Behavior

pass

### Steps To Reproduce

```markdown
@pytest.mark.tags(CaseLabel.L1)
    def test_search_with_output_field(self, auto_id, _async, enable_dynamic_field):
        """
        target: test search with output fields
        method: search with one output_field
        expected: search success
        """
        # 1. initialize with data
        collection_w, _, _, insert_ids = self.init_collection_general(prefix, True,
                                                                      auto_id=auto_id,
                                                                      enable_dynamic_field=
                                                                      enable_dynamic_field)[0:4]
        # 2. search
        log.info("test_search_with_output_field: Searching collection %s" % collection_w.name)

        collection_w.search(vectors[:default_nq], default_search_field,
                            default_search_params, default_limit,
                            default_search_exp, _async=_async,
                            output_fields=[default_int64_field_name],
                            check_task=CheckTasks.check_search_results,
                            check_items={"nq": default_nq,
                                         "ids": insert_ids,
                                         "limit": default_limit,
                                         "_async": _async,
                                         "output_fields": [default_int64_field_name]})
```

**Comment by XuanYang-cn** [comment]
should be fixed at pymilvus-2.2.14.dev9
/unassign 
/assign @NicoYuan1986

**Comment by XuanYang-cn** [comment]
pymilvus-2.2.14.dev10

**Comment by NicoYuan1986** [comment]
#25646

**Comment by NicoYuan1986** [comment]
fixed. 2.2.14.dev10
