### ISSUE TITLE
[Bug]: It is invalid to set max length of pk varchar field less than 18 when using autoid=true

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#25580]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230713-ed3e4b0b
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0.dev95
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

It is invalid to set max length of pk varchar field less than 18 when using autoid=true.
```
RPC error: [batch_insert], <MilvusException: (code=1, message=the length (18) of 0th string exceeds max length (4): expected=valid length string, actual=string length exceeds max length: invalid parameter)>, <Time:{'RPC start': '2023-07-13 18:49:40.504498', 'RPC error': '2023-07-13 18:49:40.766040'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/orm/collection.py", line 497, in insert
    res = conn.batch_insert(
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 120, in handler
    raise e from e
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 116, in handler
    return func(*args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 155, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 95, in handler
    raise e from e
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 68, in handler
    return func(*args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 562, in batch_insert
    raise err from err
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 558, in batch_insert
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=the length (18) of 0th string exceeds max length (4): expected=valid length string, actual=string length exceeds max length: invalid parameter)>

```

### Expected Behavior

give some limitation or remove error

### Steps To Reproduce

```markdown
1. create a collection, set pk varchar and auto_id=true, set max_length=4
2. insert data -> raise error
```

### Milvus Log

```python
from pymilvus import CollectionSchema, FieldSchema, Collection, connections, DataType, Partition, utility
import numpy as np
import pandas as pd
import random
connections.connect()


dim = 128
fields = [
    FieldSchema(name="string", dtype=DataType.VARCHAR, is_primary=True, max_length=4, auto_id=True),
    FieldSchema(name="int64", dtype=DataType.INT64),
    FieldSchema(name="float", dtype=DataType.FLOAT),
    FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim),
]
schema = CollectionSchema(fields=fields)
collection_name = "test_varchar"
if utility.has_collection(collection_name):
    utility.drop_collection(collection_name)

collection = Collection(collection_name, schema=schema)

nb = 1000
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
data = pd.DataFrame({
    'int64': [i for i in range(nb)],
    'float': [np.float32(i) for i in range(nb)],
    'float_vector': vectors,
})
collection.insert(data)
```

**Comment by NicoYuan1986** [comment]
verify fixed.
The parameter max_length does not take effect when primary key is string and auto id is set true.
But it still need to provide the param. or it will raise exception.
![image](https://github.com/milvus-io/milvus/assets/109071306/342ee814-4d72-42ae-a087-2219d3a6b98f)
