### ISSUE TITLE
[Bug]: unable to login to attu: No connection established

### ISSUE THREAD

**Issue by wales-z** [milvus-io/milvus#25596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.10
- Deployment mode(standalone or cluster): standalone 
- MQ type(rocksmq, pulsar or kafka): default (don't know which one) 
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 
- OS(Ubuntu or CentOS): Ubuntu (Microsoft WSL2 backend)
- CPU/Memory: AMD R7 5800H / 8G 3200 MHz* 2 
- GPU: Nvidia RTX 3060 Laptop
- Others:
```

### Current Behavior

I deployed Milvus Standalone with default docker-compose config, and I can successfully conncect to milvus server using python SDK. 

Following the install tutorail in https://milvus.io/docs/attu_install-docker.md, I run this command to start an Attu instance via docker:
```
docker run -p 8000:3000  -e MILVUS_URL=127.0.0.1:19530 zilliz/attu:v2.2.6
```
> I also tried using localhost instead of 127.0.0.1)

The frontend page (localhost:8000) runs well but when I click the connect button, there's no change in frontend page.
![attu_page](https://github.com/milvus-io/milvus/assets/54798466/e8ad0ccf-bd3a-4398-9160-aaad65403f9a)

### Milvus Log

> below is the error log reported in attu instance
(node:49) UnhandledPromiseRejectionWarning: Error: 14 UNAVAILABLE: No connection established
    at callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
    at /app/node_modules/@grpc/grpc-js/build/src/call-interface.js:78:35
    at Object.onReceiveStatus (/app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/utils/Grpc.js:145:41)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /app/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
    at runNextTicks (internal/process/task_queues.js:64:3)
    at listOnTimeout (internal/timers.js:526:9)
for call at
    at ServiceClientImpl.makeUnaryRequest (/app/node_modules/@grpc/grpc-js/build/src/client.js:160:34)
    at ServiceClientImpl.<anonymous> (/app/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at /app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/utils/Function.js:20:24
    at new Promise (<anonymous>)
    at promisify (/app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/utils/Function.js:17:17)
    at MilvusClient.<anonymous> (/app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/grpc/GrpcClient.js:140:38)
    at Generator.next (<anonymous>)
    at /app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/grpc/GrpcClient.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/grpc/GrpcClient.js:4:12)
(node:49) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
Error: 14 UNAVAILABLE: No connection established
    at callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
    at /app/node_modules/@grpc/grpc-js/build/src/call-interface.js:78:35
    at Object.onReceiveStatus (/app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/utils/Grpc.js:145:41)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /app/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/app/node_modules/@grpc/grpc-js/build/src/client.js:160:34)
    at ServiceClientImpl.<anonymous> (/app/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at /app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/utils/Function.js:20:24
    at new Promise (<anonymous>)
    at promisify (/app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/utils/Function.js:17:17)
    at MilvusClient.<anonymous> (/app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/grpc/GrpcClient.js:192:44)
    at Generator.next (<anonymous>)
    at /app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/grpc/GrpcClient.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/grpc/GrpcClient.js:4:12) {
  code: 14,
  details: 'No connection established',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} },
  expose: true,
  statusCode: 400,
  status: 400
}
POST /api/v1/milvus/connect 400 Error: 14 UNAVAILABLE: No connection established

**Comment by wales-z** [comment]
I'm Chinese by the way, so feel free to answer in Chinese

**Comment by shanghaikid** [comment]
attu有自己的server，在docker中。你输入127.0.0.1对于attu的docker只是docker网络的127.0.0.1. 你需要输入正确的milvus的地址，这个地址能被attu的docker访问。

**Comment by wales-z** [comment]
非常感谢，茅塞顿开！我把attu的container加入到milvus standalone所在的docker network里，然后又把登陆界面的地址相应替换，就成功登上去了。

**Comment by onenerve** [comment]
你好，请问你具体是怎么做的呢？

**Comment by shanghaikid** [comment]
> 你好，请问你具体是怎么做的呢？

这取决于你的docker网络是怎么设置的，当然，你如果是本地单机版docker安装，可以尝试输入本地的ip(wan)地址，比如你的ip是188.188.188.188，那你可以尝试输入188.188.188.188:19530，这个因为是wan地址，本地attu docker理论上是可以访问的。

总之一句话，输入的ip，需要能被attu 的docker访问。

**Comment by onenerve** [comment]
懂了，谢谢

**Comment by wenshu400** [comment]
> 正确的milvus的地址

正确的milvus的地址怎么看大佬

**Comment by shanghaikid** [comment]
> > 正确的milvus的地址
> 
> 正确的milvus的地址怎么看大佬

你怎么装milvus和attu的？ 如果都是本机的话，你在attu界面就输入本机的外网地址。不要输入127.0.0.1后者localhost。

**Comment by wenshu400** [comment]
> > > 正确的milvus的地址
> > 
> > 
> > 正确的milvus的地址怎么看大佬
> 
> 你怎么装milvus和attu的？ 如果都是本机的话，你在attu界面就输入本机的外网地址。不要输入127.0.0.1后者localhost。

好的  懂了
