### ISSUE TITLE
[Bug]: SIGSEGV: segmentation violation when searching

### ISSUE THREAD

**Issue by longjiquan** [milvus-io/milvus#25610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

goroutine 1191 [syscall]:
_ZN6milvus7segcore17SegmentSealedImpl19bulk_subscript_implIlEEvPKvPKllPv
	/home/ljq/work/milvus-distributed/internal/core/src/segcore/SegmentSealedImpl.cpp:735 pc=0x7f50ab31b371
_ZNK6milvus7segcore17SegmentSealedImpl14bulk_subscriptEN6fluent9NamedTypeIlNS_4impl10FieldIdTagEJNS2_10ComparableENS2_8HashableEEEEPKll
	/home/ljq/work/milvus-distributed/internal/core/src/segcore/SegmentSealedImpl.cpp:870 pc=0x7f50ab31b371
_ZNK6milvus7segcore24SegmentInternalInterface15FillPrimaryKeysEPKNS_5query4PlanERNS_12SearchResultE
	/home/ljq/work/milvus-distributed/internal/core/src/segcore/SegmentInterface.cpp:41 pc=0x7f50ab372fa9
_ZN6milvus7segcore12ReduceHelper14FillPrimaryKeyEv
	/home/ljq/work/milvus-distributed/internal/core/src/segcore/Reduce.cpp:121 pc=0x7f50ab365d33
_ZN6milvus7segcore12ReduceHelper6ReduceEv
	/home/ljq/work/milvus-distributed/internal/core/src/segcore/Reduce.cpp:57 pc=0x7f50ab36708c
ReduceSearchResultsAndFillData
	/home/ljq/work/milvus-distributed/internal/core/src/segcore/reduce_c.cpp:42 pc=0x7f50ab36ccfb
_cgo_643f0fd36df8_Cfunc_ReduceSearchResultsAndFillData
	/tmp/go-build/cgo-gcc-prolog:103 pc=0x36ab66b
runtime.cgocall(0x36ab630, 0xc001b5d9a8)
	/usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc001b5d980 sp=0xc001b5d948 pc=0x14a167c
github.com/milvus-io/milvus/internal/querynodev2/segments._Cfunc_ReduceSearchResultsAndFillData(0xc001900038, 0x7f4ff3222000, 0xc001f0a000, 0x18, 0xc001b500a8, 0xc001b500a0, 0x1)
	_cgo_gotypes.go:784 +0x55 fp=0xc001b5d9a8 sp=0xc001b5d980 pc=0x33d2ab5
github.com/milvus-io/milvus/internal/querynodev2/segments.ReduceSearchResultsAndFillData.func1(0x3863e00?, 0xc001f06080?, 0x3a8c540?, 0xc00133a490?, 0x36976119c4b90482?, 0xafc5e277aa2c2f3d?, 0x167950ef313e03c3?)
	/home/ljq/work/milvus-distributed/internal/querynodev2/segments/reduce.go:100 +0xdd fp=0xc001b5da38 sp=0xc001b5d9a8 pc=0x33db81d
github.com/milvus-io/milvus/internal/querynodev2/segments.ReduceSearchResultsAndFillData(0xc0019945d8, {0xc0013320c0, 0x18, 0xc001330d80?}, 0x30?, {0xc001b500a8, 0x1, 0x0?}, {0xc001b500a0, 0x1, ...})
	/home/ljq/work/milvus-distributed/internal/querynodev2/segments/reduce.go:100 +0x2bc fp=0xc001b5dae8 sp=0xc001b5da38 pc=0x33db65c
github.com/milvus-io/milvus/internal/querynodev2/tasks.(*SearchTask).Execute(0xc001169680)
	/home/ljq/work/milvus-distributed/internal/querynodev2/tasks/task.go:177 +0x5b7 fp=0xc001b5dec0 sp=0xc001b5dae8 pc=0x3401bd7
github.com/milvus-io/milvus/internal/querynodev2/tasks.(*scheduler).exec.func1()
	/home/ljq/work/milvus-distributed/internal/querynodev2/tasks/concurrent_safe_scheduler.go:193 +0xec fp=0xc001b5df30 sp=0xc001b5dec0 pc=0x33ff0ac
github.com/milvus-io/milvus/pkg/util/conc.(*Pool[...]).Submit.func1()
	/home/ljq/work/milvus-distributed/pkg/util/conc/pool.go:73 +0x99 fp=0xc001b5df88 sp=0xc001b5df30 pc=0x2f98f99
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
	/home/ljq/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.2/worker.go:67 +0x97 fp=0xc001b5dfe0 sp=0xc001b5df88 pc=0x2d99e77
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc001b5dfe8 sp=0xc001b5dfe0 pc=0x150d941
created by github.com/panjf2000/ants/v2.(*goWorker).run
	/home/ljq/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.2/worker.go:48 +0x65

### Expected Behavior

Searching should be normal.

**Comment by longjiquan** [comment]
commit: `d216f9abd`
number of vectors: 1000, 000
index type: HNSW
segments number: 24
topk: 10000
nq: 1

**Comment by longjiquan** [comment]
fixed by https://github.com/milvus-io/milvus/pull/25707
