### ISSUE TITLE
[Bug]: BulkInsert raises error when upgrading pymilvus to 2.2.14.dev10

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#25667]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: aa4144c
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.14.dev10
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

BulkInsert raises error when upgrading pymilvus to 2.2.14.dev10.
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-25646/4/pipeline/116/
```
[2023-07-17T09:36:08.850Z] ------------------------------ Captured log call -------------------------------
[2023-07-17T09:36:08.850Z] [2023-07-17 09:34:09 - DEBUG - urllib3.connectionpool]: Starting new HTTP connection (1): ms-25646-4-pr-minio.milvus-ci:9000 (connectionpool.py:245)
[2023-07-17T09:36:08.850Z] [2023-07-17 09:34:09 - DEBUG - urllib3.connectionpool]: http://ms-25646-4-pr-minio.milvus-ci:9000 "GET /milvus-bucket?location= HTTP/1.1" 200 128 (connectionpool.py:473)
[2023-07-17T09:36:08.850Z] [2023-07-17 09:34:09 - DEBUG - urllib3.connectionpool]: http://ms-25646-4-pr-minio.milvus-ci:9000 "HEAD /milvus-bucket HTTP/1.1" 200 0 (connectionpool.py:473)
[2023-07-17T09:36:08.850Z] [2023-07-17 09:34:09 - DEBUG - urllib3.connectionpool]: http://ms-25646-4-pr-minio.milvus-ci:9000 "HEAD /milvus-bucket/_row_auto_float_vectors_128d_100_0.json HTTP/1.1" 200 0 (connectionpool.py:473)
[2023-07-17T09:36:08.850Z] [2023-07-17 09:34:09 - DEBUG - urllib3.connectionpool]: http://ms-25646-4-pr-minio.milvus-ci:9000 "PUT /milvus-bucket/_row_auto_float_vectors_128d_100_0.json HTTP/1.1" 200 0 (connectionpool.py:473)
[2023-07-17T09:36:08.850Z] [2023-07-17 09:34:09 - INFO - ci_test]: copied _row_auto_float_vectors_128d_100_0.json to minio (minio_comm.py:26)
[2023-07-17T09:36:08.850Z] [2023-07-17 09:34:09 - DEBUG - ci_test]: (api_request)  : [Connections.connect] args: ['default', '', '', ''], kwargs: {'host': 'ms-25646-4-pr-milvus.milvus-ci', 'port': '19530'} (api_request.py:56)
[2023-07-17T09:36:08.850Z] [2023-07-17 09:34:09 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)
[2023-07-17T09:36:08.850Z] [2023-07-17 09:34:09 - DEBUG - ci_test]: (api_request)  : [create_database] args: ['db_lOy88Jr1', 'default', None], kwargs: {} (api_request.py:56)
[2023-07-17T09:36:08.850Z] [2023-07-17 09:34:09 - ERROR - ci_test]: Traceback (most recent call last):
[2023-07-17T09:36:08.850Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2023-07-17T09:36:08.850Z]     res = func(*args, **_kwargs)
[2023-07-17T09:36:08.850Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2023-07-17T09:36:08.850Z]     return func(*arg, **kwargs)
[2023-07-17T09:36:08.850Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/db.py", line 27, in create_database
[2023-07-17T09:36:08.850Z]     _get_connection(using).create_database(db_name, timeout=timeout)
[2023-07-17T09:36:08.850Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/db.py", line 7, in _get_connection
[2023-07-17T09:36:08.850Z]     return connections._fetch_handler(alias)
[2023-07-17T09:36:08.850Z] AttributeError: module 'pymilvus.orm.connections' has no attribute '_fetch_handler'
[2023-07-17T09:36:08.850Z]  (api_request.py:39)
[2023-07-17T09:36:08.850Z] [2023-07-17 09:34:09 - ERROR - ci_test]: (api_response) : module 'pymilvus.orm.connections' has no attribute '_fetch_handler' (api_request.py:40)
```

### Expected Behavior

pass

### Steps To Reproduce

```markdown
@pytest.mark.tags(CaseLabel.L3)
    @pytest.mark.parametrize("is_row_based", [True])
    @pytest.mark.parametrize("auto_id", [True, False])
    @pytest.mark.parametrize("dim", [128])  # 8, 128
    @pytest.mark.parametrize("entities", [100])  # 100, 1000
    def test_bulk_insert_to_db(self, is_row_based, auto_id, dim, entities):
        """
        collection: auto_id, customized_id
        collection schema: [pk, float_vector]
        Steps:
        1. create collection
        2. import data
        3. verify the data entities equal the import data
        4. load the collection
        5. verify search successfully
        6. verify query successfully
        """
        files = prepare_bulk_insert_json_files(
            minio_endpoint=self.minio_endpoint,
            bucket_name=self.bucket_name,
            is_row_based=is_row_based,
            rows=entities,
            dim=dim,
            auto_id=auto_id,
            data_fields=default_vec_only_fields,
            force=True,
        )
        self._connect()
        c_name = cf.gen_unique_str("bulk_insert")
        for i in range(2):
            db_name = cf.gen_unique_str("db")
            self.database_wrap.create_database(db_name)
            dbs, _ = self.database_wrap.list_database()
            assert db_name in dbs
            self.database_wrap.using_database(db_name)

            fields = [
                cf.gen_int64_field(name=df.pk_field, is_primary=True),
                cf.gen_float_vec_field(name=df.vec_field, dim=dim),
            ]
            schema = cf.gen_collection_schema(fields=fields, auto_id=auto_id)
            log.info(f"create collection: {c_name} in db {db_name}")
            self.collection_wrap.init_collection(c_name, schema=schema)
            # import data
            t0 = time.time()
            task_id, _ = self.utility_wrap.do_bulk_insert(
                collection_name=c_name,
                partition_name=None,
                files=files,
            )
            logging.info(f"bulk insert task id:{task_id}")
            success, _ = self.utility_wrap.wait_for_bulk_insert_tasks_completed(
                task_ids=[task_id], timeout=90
            )
            tt = time.time() - t0
            log.info(f"bulk insert state:{success} in {tt}")
            assert success

            num_entities = self.collection_wrap.num_entities
            log.info(f" collection entities: {num_entities}")
            assert num_entities == entities

            # verify imported data is available for search
            index_params = ct.default_index
            self.collection_wrap.create_index(
                field_name=df.vec_field, index_params=index_params
            )
            time.sleep(2)
            self.utility_wrap.wait_for_index_building_complete(c_name, timeout=120)
            res, _ = self.utility_wrap.index_building_progress(c_name)
            log.info(f"index building progress: {res}")
            self.collection_wrap.load()
            self.collection_wrap.load(_refresh=True)
            log.info(f"wait for load finished and be ready for search")
            time.sleep(2)
            log.info(
                f"query seg info: {self.utility_wrap.get_query_segment_info(c_name)[0]}"
            )
            nq = 2
            topk = 2
            search_data = cf.gen_vectors(nq, dim)
            search_params = ct.default_search_params
            res, _ = self.collection_wrap.search(
                search_data,
                df.vec_field,
                param=search_params,
                limit=topk,
                check_task=CheckTasks.check_search_results,
                check_items={"nq": nq, "limit": topk},
            )
            for hits in res:
                ids = hits.ids
                results, _ = self.collection_wrap.query(expr=f"{df.pk_field} in {ids}")
                assert len(results) == len(ids)
```

**Comment by XuanYang-cn** [comment]
please try 2.2.14.dev11
/unassign
/assign @NicoYuan1986

**Comment by NicoYuan1986** [comment]
Fixed.
