### ISSUE TITLE
[Bug]: Time travel does not work even with the retentionDuration parameter set

### ISSUE THREAD

**Issue by groobyming** [milvus-io/milvus#25699]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.11
- Deployment mode: standalone
- MQ type(rocksmq, pulsar or kafka):   
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.2.4
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Time travel does not work even with the retentionDuration parameter set

milvus.yaml: 
```
common:
  retentionDuration: 7200
```
docker-compose.yml:
```
version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.2.11
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
      - /data/vector_db/milvus/milvus.yaml:/var/lib/milvus/milvus.yaml
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
networks:
  default:
    name: milvus
```

example code: https://milvus.io/docs/timetravel.md
error: 
<img width="1160" alt="image" src="https://github.com/milvus-io/milvus/assets/34335395/ba50a7fe-0500-47c3-820e-4929a2e9ac6c">

**Comment by yanliang567** [comment]
@groobyming thanks for the feedback. could you please share the reproduce code for us to investigate the issue?
/assign @groobyming

**Comment by yanliang567** [comment]
/assign @NicoYuan1986 
could you pease help to reproduce the issue in house

**Comment by NicoYuan1986** [comment]
not reproduced.
v2.2.11
pymilvus v2.2.4

```
>>> from pymilvus import connections, Collection, FieldSchema, CollectionSchema, DataType
>>> connections.connect("default", host='10.102.9.150', port='19530')
>>> collection_name = "test_time_travel"
>>> schema = CollectionSchema([
...   FieldSchema("pk", DataType.INT64, is_primary=True),
...   FieldSchema("example_field", dtype=DataType.FLOAT_VECTOR, dim=2)
... ])
>>> collection = Collection(collection_name, schema)
>>> 
>>> import random
>>> data = [
...   [i for i in range(10)],
...   [[random.random() for _ in range(2)] for _ in range(10)],
... ]
>>> batch1 = collection.insert(data)

>>> 
>>> batch1.timestamp
442939459903422467
>>> data = [
...   [i for i in range(10, 20)],
...   [[random.random() for _ in range(2)] for _ in range(9)],
... ]
>>> data[1].append([1.0,1.0])
>>> batch2 = collection.insert(data)
>>> collection.create_index("example_field", {"index_type": "FLAT", "params": {"nlist": 128}, "metric_type": "L2"})
Status(code=0, message=)
>>> collection.load()

>>> 
>>> search_param = {
...   "data": [[1.0, 1.0]],
...   "anns_field": "example_field",
...   "param": {"metric_type": "L2"},
...   "limit": 10,
...   "travel_timestamp": batch1.timestamp,
... }
>>> 
>>> res = collection.search(**search_param)
>>> 
>>> res[0].ids
[2, 9, 0, 7, 1, 6, 8, 5, 3, 4]
>>> 
>>> batch2.timestamp
442939465565732866
>>> 
>>> search_param = {
...     "data": [[1.0, 1.0]],
...     "anns_field": "example_field",
...     "param": {"metric_type": "L2"},
...     "limit": 10,
...     "travel_timestamp": batch2.timestamp,
... }
>>> 
>>> res = collection.search(**search_param)
>>> res[0].ids
[19, 17, 13, 2, 9, 0, 7, 11, 1, 16]
>>> 
>>> import datetime
>>> datetime = datetime.datetime.now()
>>> from pymilvus import utility
>>> pre_del_timestamp = utility.mkts_from_datetime(datetime)
>>> 
>>> expr = "pk in [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]"
>>> collection.delete(expr)
(insert count: 0, delete count: 10, upsert count: 0, timestamp: 442939502632894467, success count: 0, err count: 0)
>>> 
>>> search_param = {
...     "data": [[1.0, 1.0]],
...     "anns_field": "example_field",
...     "param": {"metric_type": "L2"},
...     "limit": 10,
... }
>>> res = collection.search(**search_param)
>>> res[0].ids
[19, 17, 13, 9, 7, 11, 1, 5, 15, 3]
>>> 
>>> 
>>> search_param = {
...     "data": [[1.0, 1.0]],
...     "anns_field": "example_field",
...     "param": {"metric_type": "L2"},
...     "limit": 10,
...     "travel_timestamp": pre_del_timestamp,
... }
>>> res = collection.search(**search_param)
>>> res[0].ids
[19, 17, 13, 2, 9, 0, 7, 11, 1, 16]
```

**Comment by NicoYuan1986** [comment]
@yanliang567  suggest add a step 'create index' here, or it will report error.
https://milvus.io/docs/timetravel.md
![image](https://github.com/milvus-io/milvus/assets/109071306/8f1e3475-4d49-469b-8a3b-11112d8768d2)

**Comment by NicoYuan1986** [comment]
reproduced by starting milvus using docker-compose.yaml.
```
wget https://github.com/milvus-io/milvus/releases/download/v2.2.11/milvus-standalone-docker-compose.yml -O docker-compose.yml
```

```
>>> search_param = {
...   "data": [[1.0, 1.0]],
...   "anns_field": "example_field",
...   "param": {"metric_type": "L2"},
...   "limit": 10,
...   "travel_timestamp": batch1.timestamp,
... }
>>> res = collection.search(**search_param)
RPC error: [search], <MilvusException: (code=1, message=only support to travel back to 0s so far, but got 28s)>, <Time:{'RPC start': '2023-07-18 19:48:48.453033', 'RPC error': '2023-07-18 19:48:48.472262'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zilliz/virtual-environment/release/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 614, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/Users/zilliz/virtual-environment/release/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/Users/zilliz/virtual-environment/release/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/Users/zilliz/virtual-environment/release/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/Users/zilliz/virtual-environment/release/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/Users/zilliz/virtual-environment/release/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/virtual-environment/release/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 483, in search
    return self._execute_search_requests(requests, timeout, round_decimal=round_decimal, auto_id=auto_id, **kwargs)
  File "/Users/zilliz/virtual-environment/release/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 452, in _execute_search_requests
    raise pre_err
  File "/Users/zilliz/virtual-environment/release/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 443, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=only support to travel back to 0s so far, but got 28s)>
```

**Comment by yanliang567** [comment]
@groobyming it seems that you did not make the retentionDuration parameter updated in docker composer. How did you change the parameter?

/assign @groobyming

**Comment by groobyming** [comment]
@yanliang567  reproduced by starting milvus using docker-compose.yaml as @NicoYuan1986 said, and  how can I change the retentionDuration in docker composer file， Please give me an example

**Comment by yanliang567** [comment]
/assign @locustbaby 
could you please give an example here?

**Comment by locustbaby** [comment]
@groobyming 
Need to mount local `milvus.yaml` into `Milvus container` in `docker-compose.yaml`
```yaml
...
  standalone:
  ...
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
      - ./milvus.yaml:/milvus/configs/milvus.yaml
...
```
So that you can define a custom config locally

**Comment by groobyming** [comment]
> @groobyming Need to mount local `milvus.yaml` into `Milvus container` in `docker-compose.yaml` Add `- ./milvus.yaml:/milvus/configs/milvus.yaml` at volumes as below:
> 
> ```yaml
> ...
>   standalone:
>   ...
>     volumes:
>       - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
>       - ./milvus.yaml:/milvus/configs/milvus.yaml
> ...
> ```
> 
> So that you can define a custom config locally

Thanks

**Comment by groobyming** [comment]
@locustbaby I mount local milvus.yaml into Milvus container, but got an error when restart milvus-standalone
<img width="1071" alt="image" src="https://github.com/milvus-io/milvus/assets/34335395/9ccefdcc-539c-4efc-91e5-e377e4aad036">

directory list：
<img width="867" alt="image" src="https://github.com/milvus-io/milvus/assets/34335395/51c833db-353c-4c9c-998a-b27e1a9383a0">

milvus.yaml
<img width="286" alt="image" src="https://github.com/milvus-io/milvus/assets/34335395/4009be76-d483-4156-bb57-a383b0425542">

docker-compose.yaml
<img width="798" alt="image" src="https://github.com/milvus-io/milvus/assets/34335395/fcca9b59-b53c-4717-8f04-b64ff7f0769d">

**Comment by locustbaby** [comment]
> milvus.yaml

The `milvus.yaml` should be complete, which means contain all parameters, can make a copy and change the parameters as you want.

**Comment by groobyming** [comment]
@locustbaby Thanks,  i will close the issue
