### ISSUE TITLE
[Bug]: [Nightly]Search on a loaded collection whose partitions are all released will raise error

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#25692]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: a8f7305
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0.dev100
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Search on a loaded collection whose partitions are all released will raise error.
reproduced locally
```
[2023-07-17T19:22:03.198Z] [2023-07-17 19:17:33 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=attempt #0: fail to get shard leaders from QueryCoord: collection=442922834043398224: collection not loaded: unrecoverable error: fail to search on all shard leaders)>, <Time:{'RPC start': '2023-07-17 19:17:33.053980', 'RPC error': '2023-07-17 19:17:33.056248'}> (decorators.py:125)
[2023-07-17T19:22:03.198Z] [2023-07-17 19:17:33 - ERROR - ci_test]: Traceback (most recent call last):
[2023-07-17T19:22:03.198Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper
[2023-07-17T19:22:03.198Z]     res = func(*args, **_kwargs)
[2023-07-17T19:22:03.198Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request
[2023-07-17T19:22:03.198Z]     return func(*arg, **kwargs)
[2023-07-17T19:22:03.198Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 780, in search
[2023-07-17T19:22:03.198Z]     res = conn.search(
[2023-07-17T19:22:03.198Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 126, in handler
[2023-07-17T19:22:03.198Z]     raise e from e
[2023-07-17T19:22:03.198Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 122, in handler
[2023-07-17T19:22:03.198Z]     return func(*args, **kwargs)
[2023-07-17T19:22:03.198Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 161, in handler
[2023-07-17T19:22:03.198Z]     return func(self, *args, **kwargs)
[2023-07-17T19:22:03.198Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 101, in handler
[2023-07-17T19:22:03.198Z]     raise e from e
[2023-07-17T19:22:03.198Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 68, in handler
[2023-07-17T19:22:03.198Z]     return func(*args, **kwargs)
[2023-07-17T19:22:03.198Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 765, in search
[2023-07-17T19:22:03.198Z]     return self._execute_search_requests(
[2023-07-17T19:22:03.198Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 725, in _execute_search_requests
[2023-07-17T19:22:03.198Z]     raise pre_err from pre_err
[2023-07-17T19:22:03.198Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 716, in _execute_search_requests
[2023-07-17T19:22:03.198Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2023-07-17T19:22:03.198Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=attempt #0: fail to get shard leaders from QueryCoord: collection=442922834043398224: collection not loaded: unrecoverable error: fail to search on all shard leaders)>
[2023-07-17T19:22:03.198Z]  (api_request.py:45)
[2023-07-17T19:22:03.198Z] [2023-07-17 19:17:33 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=attempt #0: fail to get shard leaders from QueryCoord: collection=442922834043398224: collection not loaded: unrecoverable error: fail to search on all shard leaders)> (api_request.py:46)
```

### Expected Behavior

pass

### Steps To Reproduce

```markdown
@pytest.mark.tags(CaseLabel.L2)
    def test_load_collection_release_all_partitions(self):
        """
        target: test load and release all partitions
        method: 1. create a collection and 2 partitions
                2. load collection and release all partitions
                3. search
        expected: No exception
        """
        # init the collection
        collection_w = self.init_collection_general(prefix, True, 200, partition_num=1, is_index=False)[0]
        partition_w1, partition_w2 = collection_w.partitions
        collection_w.create_index(default_search_field, default_index_params)
        # load and release
        collection_w.load()
        partition_w1.release()
        partition_w2.release()
        # search on collection
        collection_w.search(vectors[:1], field_name, default_search_params, 200,
                            check_task=CheckTasks.check_search_results,
                            check_items={"nq": 1, "limit": 0})
```

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/436/pipeline/161/
2. log: [artifacts-milvus-standalone-nightly-436-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/436/artifact/artifacts-milvus-standalone-nightly-436-pymilvus-e2e-logs.tar.gz)
3. collection name: search_collection_zRr9Xtto
4. failed time: [2023-07-17T19:17:33.256Z] [gw5] [ 90%] FAILED testcases/test_search.py::TestCollectionLoadOperation::test_load_collection_release_all_partitions

**Comment by bigsheeper** [comment]
Now the collection will be released if all partitions are released. Please help to modify the corresponding test case. @NicoYuan1986

**Comment by NicoYuan1986** [comment]
Fixed.
