### ISSUE TITLE
[Bug]: Standalone panic during running test cases for after reinstallation

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#25821]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230720-cfd287f1
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka): kafka   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2023-07-20T13:15:17.283Z] -------------

[2023-07-20T13:15:17.283Z] <name>: deploy_test_index_type_BIN_IVF_FLAT_is_compacted_not_compacted_segment_status_all_is_string_indexed_not_string_indexed_replica_number_0_is_deleted_is_deleted_data_size_3000

[2023-07-20T13:15:17.283Z] <description>: 

[2023-07-20T13:15:17.283Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64'......  (api_request.py:37)

[2023-07-20T13:15:17.283Z] [2023-07-20 13:10:24 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 120} (api_request.py:62)

[2023-07-20T13:15:17.283Z] [2023-07-20 13:10:27 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-07-20T13:15:17.283Z] [2023-07-20 13:10:27 - INFO - ci_test]: inserted 3000 data into collection deploy_test_index_type_BIN_IVF_FLAT_is_compacted_not_compacted_segment_status_all_is_string_indexed_not_string_indexed_replica_number_0_is_deleted_is_deleted_data_size_3000 (common_func.py:948)

[2023-07-20T13:15:17.283Z] [2023-07-20 13:10:27 - DEBUG - ci_test]: Dynamic field is enabled: False (common_func.py:950)

[2023-07-20T13:15:17.283Z] [2023-07-20 13:10:27 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [      int64   float varchar                                      binary_vector

[2023-07-20T13:15:17.283Z] 0         0     0.0       0  b'`#\x81\xfb\x89\xeeZ\x8b\xe0\xd0|\x13\xa7\x80...

[2023-07-20T13:15:17.283Z] 1         1     1.0       1     b'\x9e%O\xaf\x80\x84\xd2c\xde(\xd2[X\x074\xfd'

[2023-07-20T13:15:17.283Z] 2         2     2.0       2  b'\xfb\xedh?B$\x12#\x17\xfc\xa2\x......, kwargs: {'timeout': 120} (api_request.py:62)

[2023-07-20T13:15:17.283Z] [2023-07-20 13:10:28 - DEBUG - ci_test]: (api_response) : (insert count: 3000, delete count: 0, upsert count: 0, timestamp: 442986300167159810, success count: 3000, err count: 0)  (api_request.py:37)

[2023-07-20T13:15:17.283Z] [2023-07-20 13:10:34 - INFO - ci_test]: index info: [{'collection': 'deploy_test_index_type_BIN_IVF_FLAT_is_compacted_not_compacted_segment_status_all_is_string_indexed_not_string_indexed_replica_number_0_is_deleted_is_deleted_data_size_3000', 'field': 'varchar', 'index_name': 'test_WIKU13Mb', 'index_param': {}}] (test_action_second_deployment.py:58)

[2023-07-20T13:15:17.283Z] [2023-07-20 13:10:34 - INFO - ci_test]: current index param is {}, passed in param is {'index_type': 'BIN_IVF_FLAT', 'params': {'nlist': 128}, 'metric_type': 'HAMMING'} (test_action_second_deployment.py:61)

[2023-07-20T13:15:17.283Z] [2023-07-20 13:10:34 - INFO - ci_test]: current index name is test_WIKU13Mb, passed in param is None (test_action_second_deployment.py:63)

[2023-07-20T13:15:17.283Z] [2023-07-20 13:10:56 - WARNING - pymilvus.decorators]: [get_loading_progress] retry:4, cost: 0.27s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.42.24:19530: Failed to connect to remote host: Connection refused> (decorators.py:87)

[2023-07-20T13:15:17.283Z] [2023-07-20 13:10:56 - WARNING - pymilvus.decorators]: [get_loading_progress] retry:5, cost: 0.81s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.42.24:19530: Failed to connect to remote host: Connection refused> (decorators.py:87)

[2023-07-20T13:15:17.283Z] [2023-07-20 13:10:57 - WARNING - pymilvus.decorators]: [get_loading_progress] retry:6, cost: 2.43s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.42.24:19530: Failed to connect to remote host: Connection refused> (decorators.py:87)

[2023-07-20T13:15:17.283Z] [2023-07-20 13:10:59 - WARNING - pymilvus.decorators]: [get_loading_progress] retry:7, cost: 7.29s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.42.24:19530: Failed to connect to remote host: Connection refused> (decorators.py:87)

[2023-07-20T13:15:17.283Z] [2023-07-20 13:11:07 - WARNING - pymilvus.decorators]: [get_loading_progress] retry:8, cost: 21.87s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.42.24:19530: Failed to connect to remote host: Connection refused> (decorators.py:87)

[2023-07-20T13:15:17.283Z] [2023-07-20 13:11:28 - WARNING - pymilvus.decorators]: [get_loading_progress] retry:9, cost: 60.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.42.24:19530: Failed to connect to remote host: Connection refused> (decorators.py:87)

[2023-07-20T13:15:17.284Z] [2023-07-20 13:12:29 - WARNING - pymilvus.decorators]: [get_loading_progress] retry:10, cost: 60.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.42.24:19530: Failed to connect to remote host: Connection refused> (decorators.py:87)

[2023-07-20T13:15:17.284Z] [2023-07-20 13:13:29 - WARNING - pymilvus.decorators]: Retry run out of 10 retry times (decorators.py:93)

[2023-07-20T13:15:17.284Z] [2023-07-20 13:13:29 - ERROR - pymilvus.decorators]: RPC error: [get_loading_progress], <MilvusException: (code=1, message=Retry run out of 10 retry times, message=collection 442985652525175599 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2023-07-20 13:10:55.679989', 'RPC error': '2023-07-20 13:13:29.073676'}> (decorators.py:125)

[2023-07-20T13:15:17.284Z] [2023-07-20 13:13:29 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=Retry run out of 10 retry times, message=collection 442985652525175599 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2023-07-20 13:10:53.673298', 'RPC error': '2023-07-20 13:13:29.073761'}> (decorators.py:125)

[2023-07-20T13:15:17.284Z] [2023-07-20 13:13:29 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry run out of 10 retry times, message=collection 442985652525175599 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2023-07-20 13:10:53.660415', 'RPC error': '2023-07-20 13:13:29.073807'}> (decorators.py:125)[get_env_variable] failed to get environment variables : 'CI_LOG_PATH', use default path : /tmp/ci_logs

[2023-07-20T13:15:17.284Z] 

[2023-07-20T13:15:17.284Z] ------------- generated html file: file:///tmp/ci_logs/report.html -------------

[2023-07-20T13:15:17.284Z] =========================== short test summary info ============================

[2023-07-20T13:15:17.284Z] FAILED testcases/test_action_second_deployment.py::TestActionSecondDeployment::test_check[deploy_test_index_type_BIN_IVF_FLAT_is_compacted_not_compacted_segment_status_all_is_string_indexed_not_string_indexed_replica_number_0_is_deleted_is_deleted_data_size_3000] - pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry run out of 10 retry times, message=collection 442985652525175599 has not been loaded to memory or load failed)>

[2023-07-20T13:15:17.284Z] =================== 1 failed, 33 passed in 550.36s (0:09:10) ===================
```

```
[2023/07/20 13:10:55.388 +00:00] [INFO] [indexcoord/meta_table.go:811] ["IndexCoord get index file path from meta table"] [buildID=442985991836685306]
[2023/07/20 13:10:55.388 +00:00] [INFO] [indexcoord/meta_table.go:822] ["IndexCoord get segment index file path success"] [buildID=442985991836685306] ["index files num"=2]
[2023/07/20 13:10:55.400 +00:00] [DEBUG] [querynode/task_read.go:190] ["query msg can do"] [collectionID=442985652524972334] [sm.GuaranteeTimestamp=2023/07/20 13:10:54.985 +00:00] [serviceTime=2023/07/20 13:10:55.235 +00:00] ["delta milliseconds"=-250] [channel=by-dev-rootcoord-dml_14_442985652524972334v0] [msgID=442986307252387843]
[2023/07/20 13:10:55.400 +00:00] [DEBUG] [querynode/task_read.go:197] [tr/waitTSafeTimeRecorder] [msg="wait for tsafe done"] [duration=397.399139ms]
[2023/07/20 13:10:55.400 +00:00] [DEBUG] [querynode/validate.go:115] ["read target partitions on stream replica"] [traceID=68289fdc97b1248e] [collectionID=442985652524972334] [partitionIDs="[442985652524972335]"]
panic: serviceTimeNode setTSafe timeout, collectionID = 442985652525175599, err = set tSafe failed, err = code: NotFoundTSafer, error: cannot found tSafer, vChannel = by-dev-rootcoord-dml_11_442985652525175599v0

goroutine 1915396 [running]:
github.com/milvus-io/milvus/internal/querynode.(*serviceTimeNode).Operate(0xc01452e8d0, {0xc00a013000, 0x1, 0x1})
	/go/src/github.com/milvus-io/milvus/internal/querynode/flow_graph_service_time_node.go:72 +0x84e
github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work(0xc004381040)
	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:127 +0x2ac
created by github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start
	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:71 +0x79
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_kafka_for_release_cron/detail/deploy_test_kafka_for_release_cron/1218/pipeline

log:
[artifacts-kafka-standalone-reinstall-1218-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/12115914/artifacts-kafka-standalone-reinstall-1218-pytest-logs.tar.gz)

[artifacts-kafka-standalone-reinstall-1218-server-first-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/12115915/artifacts-kafka-standalone-reinstall-1218-server-first-deployment-logs.tar.gz)

[artifacts-kafka-standalone-reinstall-1218-server-second-deployment-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/12115916/artifacts-kafka-standalone-reinstall-1218-server-second-deployment-logs.1.tar.gz)

**Comment by zhuwenxing** [comment]
It passed after a second try.
success job:  https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_kafka_for_release_cron/detail/deploy_test_kafka_for_release_cron/1222/pipeline/
![image](https://github.com/milvus-io/milvus/assets/12268675/f08e6f5e-e8c5-432a-a809-a12494ff77c6)

**Comment by bigsheeper** [comment]
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-26395/3/pipeline/

**Comment by binbinlv** [comment]
Similar random occurred issue in CI:
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-26505/10/pipeline/199

collection name:
logs:
[artifacts-milvus-distributed-PR-26505-10-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20HA%20CI/job/PR-26505/10/artifact/artifacts-milvus-distributed-PR-26505-10-pymilvus-e2e-logs.tar.gz)
panic:
```
2023-08-22T18:02:06.641706641+08:00 stdout F [2023/08/22 10:02:06.640 +00:00] [INFO] [msgdispatcher/dispatcher.go:195] ["begin to work"] [pchannel=by-dev-rootcoord-dml_1] [isMain=true]
2023-08-22T18:02:06.654602339+08:00 stderr F panic: serviceTimeNode setTSafe timeout, collectionID = 443730690657363542, err = set tSafe failed, err = cannot found tSafer, vChannel = by-dev-rootcoord-dml_1_443730690657363542v0
2023-08-22T18:02:06.654634247+08:00 stderr F
2023-08-22T18:02:06.654640399+08:00 stderr F goroutine 3633 [running]:
2023-08-22T18:02:06.654645511+08:00 stderr F panic({0x3ae57a0, 0xc0020669e0})
2023-08-22T18:02:06.654650713+08:00 stderr F    /usr/local/go/src/runtime/panic.go:987 +0x3bb fp=0xc0002cbc90 sp=0xc0002cbbd0 pc=0x153ebdb
2023-08-22T18:02:06.654655961+08:00 stderr F github.com/milvus-io/milvus/internal/querynodev2/pipeline.(*deleteNode).Operate(0xc002c3a730, {0x39819e0?, 0xc001a13440})
2023-08-22T18:02:06.654671052+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/querynodev2/pipeline/delete_node.go:85 +0x345 fp=0xc0002cbe90 sp=0xc0002cbc90 pc=0x359cf45
2023-08-22T18:02:06.654675464+08:00 stderr F github.com/milvus-io/milvus/internal/util/pipeline.(*nodeCtx).work(0xc0031fb680)
2023-08-22T18:02:06.654679512+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/util/pipeline/node.go:77 +0x207 fp=0xc0002cbfc8 sp=0xc0002cbe90 pc=0x359a7e7
2023-08-22T18:02:06.654684764+08:00 stderr F github.com/milvus-io/milvus/internal/util/pipeline.(*nodeCtx).Start.func1()
2023-08-22T18:02:06.654688611+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/util/pipeline/node.go:51 +0x26 fp=0xc0002cbfe0 sp=0xc0002cbfc8 pc=0x359a546
2023-08-22T18:02:06.654692988+08:00 stderr F runtime.goexit()
2023-08-22T18:02:06.654696936+08:00 stderr F    /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0002cbfe8 sp=0xc0002cbfe0 pc=0x1578301
2023-08-22T18:02:06.654701035+08:00 stderr F created by github.com/milvus-io/milvus/internal/util/pipeline.(*nodeCtx).Start
2023-08-22T18:02:06.654712412+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/util/pipeline/node.go:51 +0x7b
2023-08-22T18:02:06.654716585+08:00 stderr F
2023-08-22T18:02:06.654720755+08:00 stderr F goroutine 1 [chan receive, 4 minutes]:
2023-08-22T18:02:06.654728156+08:00 stderr F runtime.gopark(0xc0002cd760?, 0xc0002cd7b8?, 0x93?, 0xa9?, 0xc0002cd7b8?)
2023-08-22T18:02:06.654734698+08:00 stderr F    /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc001993788 sp=0xc001993768 pc=0x1542096
2023-08-22T18:02:06.654739499+08:00 stderr F runtime.chanrecv(0xc0002b1f80, 0xc0002cdc18, 0x1)
2023-08-22T18:02:06.654743593+08:00 stderr F    /usr/local/go/src/runtime/chan.go:583 +0x49d fp=0xc001993818 sp=0xc001993788 pc=0x150a57d
2023-08-22T18:02:06.654757127+08:00 stderr F runtime.chanrecv1(0xc0002b1f80?, 0xc0002cdda8?)
2023-08-22T18:02:06.654759958+08:00 stderr F    /usr/local/go/src/runtime/chan.go:442 +0x18 fp=0xc001993840 sp=0xc001993818 pc=0x150a078
2023-08-22T18:02:06.654763695+08:00 stderr F github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run(0xc0002cde48, 0x0, {0xc000ef5c90?, 0xd?})
2023-08-22T18:02:06.654766668+08:00 stderr F    /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:355 +0xa07 fp=0xc001993df8 sp=0xc001993840 pc=0x3752327
2023-08-22T18:02:06.654769624+08:00 stderr F github.com/milvus-io/milvus/cmd/milvus.(*run).execute(0xc000f27560, {0xc000052090?, 0x3, 0x3}, 0xc0002b0c00)
2023-08-22T18:02:06.654774091+08:00 stderr F    /go/src/github.com/milvus-io/milvus/cmd/milvus/run.go:117 +0x68e fp=0xc001993ee0 sp=0xc001993df8 pc=0x375e70e
```
