### ISSUE TITLE
[Bug]: Fail to rename collection reporting `collection_name` value None is illegal

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#25872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-20230724-1f1ac8f1
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.14.dev18
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Fail to rename collection reporting `collection_name` value None is illegal.
```
[2023-07-24 10:43:36 - DEBUG - ci_test]: (api_request)  : [rename_collection] args: ['utility_rjYmP4lq', 'utilitynew_5FEUUtAo', None], kwargs: {} (api_request.py:56)
[2023-07-24 10:43:36 - ERROR - pymilvus.decorators]: RPC error: [rename_collections], <ParamError: (code=1, message=`collection_name` value None is illegal)>, <Time:{'RPC start': '2023-07-24 10:43:36.286855', 'RPC error': '2023-07-24 10:43:36.286934'}> (decorators.py:126)
[2023-07-24 10:43:36 - ERROR - ci_test]: Traceback (most recent call last):
  File "/root/python_client/utils/api_request.py", line 26, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/root/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/root/milvus/lib/python3.8/site-packages/pymilvus/orm/utility.py", line 525, in rename_collection
    return _get_connection(using).rename_collections(
  File "/root/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 127, in handler
    raise e from e
  File "/root/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 123, in handler
    return func(*args, **kwargs)
  File "/root/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 162, in handler
    return func(self, *args, **kwargs)
  File "/root/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 102, in handler
    raise e from e
  File "/root/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 68, in handler
    return func(*args, **kwargs)
  File "/root/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 362, in rename_collections
    check_pass_param(collection_name=new_db_name)
  File "/root/milvus/lib/python3.8/site-packages/pymilvus/client/check.py", line 356, in check_pass_param
    checker.check(key, value)
  File "/root/milvus/lib/python3.8/site-packages/pymilvus/client/check.py", line 342, in check
    _raise_param_error(key, value)
  File "/root/milvus/lib/python3.8/site-packages/pymilvus/client/check.py", line 237, in _raise_param_error
    raise ParamError(message=f"`{param_name}` value {param_value} is illegal")
pymilvus.exceptions.ParamError: <ParamError: (code=1, message=`collection_name` value None is illegal)>
 (api_request.py:39)
[2023-07-24 10:43:36 - ERROR - ci_test]: (api_response) : <ParamError: (code=1, message=`collection_name` value None is illegal)> (api_request.py:40)
```

### Expected Behavior

pass

**Comment by NicoYuan1986** [comment]
@XuanYang-cn
