### ISSUE TITLE
[Bug]: Failed to connect to milvus cloud

### ISSUE THREAD

**Issue by rahulvramesh** [milvus-io/milvus#25911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2
- Deployment mode(standalone or cluster): Milvus Cloud Service
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

trying to connect to the cluster as per the document but always returns connection error
```
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on in01-9c218e805bbd990.aws-us-west-2.vectordb.zillizcloud.com:19530. Timeout)>
```

### Expected Behavior

Should be connected to the cluster

### Steps To Reproduce

```markdown
1, Create New Cluster On zilliz.com
2, Use python MilvusClient function to create connection with uri and token
```

### Milvus Log

```
Traceback (most recent call last):
  File "/Users/rahulvramesh/workspace/benchmarks/milvus/milvus-bud/importer.py", line 4, in <module>
    client = MilvusClient(uri='https://in01-9c218e805bbd990.aws-us-west-2.vectordb.zillizcloud.com:19530',token='db_admin:Vijaya&Ramesh1')
  File "/Users/rahulvramesh/workspace/benchmarks/milvus/.venv/lib/python3.10/site-packages/pymilvus/milvus_client/milvus_client.py", line 56, in __init__
    self._using = self._create_connection(uri, user, password, db_name, token, **kwargs)
  File "/Users/rahulvramesh/workspace/benchmarks/milvus/.venv/lib/python3.10/site-packages/pymilvus/milvus_client/milvus_client.py", line 527, in _create_connection
    raise ex
  File "/Users/rahulvramesh/workspace/benchmarks/milvus/.venv/lib/python3.10/site-packages/pymilvus/milvus_client/milvus_client.py", line 522, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/Users/rahulvramesh/workspace/benchmarks/milvus/.venv/lib/python3.10/site-packages/pymilvus/orm/connections.py", line 349, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/Users/rahulvramesh/workspace/benchmarks/milvus/.venv/lib/python3.10/site-packages/pymilvus/orm/connections.py", line 282, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/Users/rahulvramesh/workspace/benchmarks/milvus/.venv/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 123, in _wait_for_channel_ready
    raise MilvusException(Status.CONNECT_FAILED,
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on in01-9c218e805bbd990.aws-us-west-2.vectordb.zillizcloud.com:19530. Timeout)>
```

### Anything else?

am using zilliz.com

**Comment by yanliang567** [comment]
@rahulvramesh for your sake of security, i suggest you contact to support@zilliz.com for help.

**Comment by yanliang567** [comment]
close this issue as commented above

**Comment by xiaofan-luan** [comment]
Usuaully there are two reasons:
1. check your pymilvus version, you have to use the version document specified or newer
2. check your ip white list settings.
