### ISSUE TITLE
[Bug]: DataNode graceful stop panic

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#25925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
 322 [2023/07/26 14:54:04.809 +08:00] [WARN] [datanode/flow_graph_dd_node.go:113] ["MsgStream closed"] ["ddNode node"=ddNode-443116240548921605-by-dev-rootcoord-dml_0_443116240548921605v0] [collection=443116240548921605] [channel=by-dev-rootcoord-dml_0_443116240548921605v0]
 323 [2023/07/26 14:54:04.832 +08:00] [ERROR] [retry/retry.go:42] ["retry func failed"] ["retry time"=0] [error="fail to allocate ID, closed allocator"] [errorVerbose="fail to allocate ID, closed allocator\n(1) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus/internal/a     llocator.(*IDAllocator).Alloc\n  | \t/home/yangxuan/Github/milvus/internal/allocator/id_allocator.go:152\n  | github.com/milvus-io/milvus/internal/datanode.(*rendezvousFlushManager).flushBufferData\n  | \t/home/yangxuan/Github/milvus/internal/datanode/flush_manager.go:462\n  | github.com/     milvus-io/milvus/internal/datanode.(*insertBufferNode).Sync.func1\n  | \t/home/yangxuan/Github/milvus/internal/datanode/flow_graph_insert_buffer_node.go:491\n  | github.com/milvus-io/milvus/pkg/util/retry.Do\n  | \t/home/yangxuan/Github/milvus/pkg/util/retry/retry.go:40\n  | github.com/mi     lvus-io/milvus/internal/datanode.(*insertBufferNode).Sync\n  | \t/home/yangxuan/Github/milvus/internal/datanode/flow_graph_insert_buffer_node.go:489\n  | github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Operate\n  | \t/home/yangxuan/Github/milvus/internal/datanode/flow_gr     aph_insert_buffer_node.go:208\n  | github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work\n  | \t/home/yangxuan/Github/milvus/internal/util/flowgraph/node.go:127\n  | runtime.goexit\n  | \t/usr/local/go/src/runtime/asm_amd64.s:1571\nWraps: (2) fail to allocate ID, closed allo     cator\nError types: (1) *withstack.withStack (2) *errutil.leafError"] [stack="github.com/milvus-io/milvus/pkg/util/retry.Do\n\t/home/yangxuan/Github/milvus/pkg/util/retry/retry.go:42\ngithub.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Sync\n\t/home/yangxuan/Github/milvus/in     ternal/datanode/flow_graph_insert_buffer_node.go:489\ngithub.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Operate\n\t/home/yangxuan/Github/milvus/internal/datanode/flow_graph_insert_buffer_node.go:208\ngithub.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work\n\t/h     ome/yangxuan/Github/milvus/internal/util/flowgraph/node.go:127"]
 324 [2023/07/26 14:54:04.832 +08:00] [ERROR] [datanode/flow_graph_insert_buffer_node.go:509] ["insertBufferNode flushBufferData failed, err = attempt #0: fail to allocate ID, closed allocator: context done during sleep after run#0: context canceled"] [segmentID=443116240550122055] [flushed=fa     lse] [dropped=false] [auto=true] [position="channel_name:\"by-dev-rootcoord-dml_0_443116240548921605v0\" msgID:\"\\010\\236\\007\\020\\366\\005\\030\\000 \\000\" msgGroup:\"datanode-6-by-dev-rootcoord-dml_0_443116240548921605v0-true\" timestamp:443116275444482050 "] [channel=by-dev-rootco     ord-dml_0_443116240548921605v0] [stack="github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Sync\n\t/home/yangxuan/Github/milvus/internal/datanode/flow_graph_insert_buffer_node.go:509\ngithub.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Operate\n\t/home/yangxua     n/Github/milvus/internal/datanode/flow_graph_insert_buffer_node.go:208\ngithub.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work\n\t/home/yangxuan/Github/milvus/internal/util/flowgraph/node.go:127"]
 325 panic: insertBufferNode flushBufferData failed, err = attempt #0: fail to allocate ID, closed allocator: context done during sleep after run#0: context canceled
 326                                                                                                                         
 327 goroutine 434 [running]:                                                                                                
 328 panic({0x3961aa0, 0xc00126b700})                                                                                        
 329     /usr/local/go/src/runtime/panic.go:941 +0x397 fp=0xc000c157e8 sp=0xc000c15728 pc=0x14f6297                          
 330 github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Sync(0xc001220e70, 0xc00141b198?, {0xc00141b198?, 0xc001bfc8a0?, 0xc001bfc840?}, 0xc001bfc8a0)
 331     /home/yangxuan/Github/milvus/internal/datanode/flow_graph_insert_buffer_node.go:510 +0xf6b fp=0xc000c15b28 sp=0xc000c157e8 pc=0x2f96beb
 332 github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Operate(0xc001220e70, {0xc001e29690, 0x1, 0x1})       
 333     /home/yangxuan/Github/milvus/internal/datanode/flow_graph_insert_buffer_node.go:208 +0x9e5 fp=0xc000c15e90 sp=0xc000c15b28 pc=0x2f93085
 334 github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work(0xc000f56050)                                       
 335     /home/yangxuan/Github/milvus/internal/util/flowgraph/node.go:127 +0x2ac fp=0xc000c15fc8 sp=0xc000c15e90 pc=0x2dc9bcc
 336 github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start.func1()                                            
 337     /home/yangxuan/Github/milvus/internal/util/flowgraph/node.go:71 +0x26 fp=0xc000c15fe0 sp=0xc000c15fc8 pc=0x2dc9606  
 338 runtime.goexit()                                                                                                        
 339     /usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000c15fe8 sp=0xc000c15fe0 pc=0x152b9e1                        
 340 created by github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start                                         
 341     /home/yangxuan/Github/milvus/internal/util/flowgraph/node.go:71 +0x79                                               
 342                                                                             
```

### Expected Behavior

See also: https://github.com/milvus-io/milvus/issues/21420

**Comment by XuanYang-cn** [comment]
Too many useless logs
![image](https://github.com/milvus-io/milvus/assets/51370125/ffe36629-6122-4383-ae28-26e065f80574)
