### ISSUE TITLE
Milvus python example run failed

### ISSUE THREAD

**Issue by fengchaozheng120** [milvus-io/milvus#2592]
Describe the bug
When i run the python exampler program, i got the problem as follows:
Traceback (most recent call last):
File "/home/lily/anaconda3/lib/python3.6/site-packages/milvus/client/grpc_client.py", line 199, in connect
grpc.channel_ready_future(self._channel).result(timeout=timeout)
File "/home/lily/anaconda3/lib/python3.6/site-packages/grpc/_utilities.py", line 140, in result
self._block(timeout)
File "/home/lily/anaconda3/lib/python3.6/site-packages/grpc/_utilities.py", line 86, in _block
raise grpc.FutureTimeoutError()
grpc.FutureTimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "example.py", line 118, in
main()
File "example.py", line 27, in main
status = milvus.connect(**param)
File "/home/lily/anaconda3/lib/python3.6/site-packages/milvus/client/grpc_client.py", line 203, in connect
raise NotConnectError('Fail connecting to server on {}. Timeout'.format(self._uri))
milvus.client.exceptions.NotConnectError: Fail connecting to server on 127.0.0.1:19530. Timeout

**Comment by tinkerlin** [comment]
Pleasae provide more information about your test environment, milvus configuration, index_type, and more. This helps us reproduce the issue you're having and resolve the issue more quickly.

Environment details

- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in server_config.yaml)

**Comment by BossZou** [comment]
Please check if your server work well? And did you map server port to host machine(docker cmd '-p 19530:19530')?

**Comment by Uncle-Yuanl** [comment]
maybe you didn't install Milvus via docker at all.

**Comment by BossZou** [comment]
Not active. Close it.
