### ISSUE TITLE
[Bug]: Milvus panic at startup when compile in centos7

### ISSUE THREAD

**Issue by xige-16** [milvus-io/milvus#25990]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): centos7
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Compile milvus on centos7, there is no error in the compilation stage, but it panics directly when starting, 

panic log:
goroutine 112 [syscall]:
runtime.cgocall(0x2f303d0, 0xc000c772e0)
        /usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc000c77278 sp=0xc000c77240 pc=0x139d8fc
github.com/milvus-io/milvus/internal/util/initcore._Cfunc_InitRemoteChunkManagerSingleton({0x7feaac003120, 0x7feaac004520, 0x7feaac004610, 0x7feaac002440, 0x7feaac0044d0, 0x7feaac001150, 0x7feaac001100, 0x0, 0x0, {0x0, ...}})
        _cgo_gotypes.go:122 +0x5b fp=0xc000c772e0 sp=0xc000c77278 pc=0x296f5fb
github.com/milvus-io/milvus/internal/util/initcore.InitRemoteChunkManager(0x5983c20)
        /go/src/github.com/milvus-io/milvus/internal/util/initcore/init_storage_config.go:75 +0x2e5 fp=0xc000c77418 sp=0xc000c772e0 pc=0x296fc25
github.com/milvus-io/milvus/internal/querynode.(*QueryNode).InitSegcore(0x41bd730?)

**Comment by xige-16** [comment]
The reason is that the default compilation parameter USE_OPENSSL of aws-sdk-cpp is ON, but the default openssl version of centos7 is too low, resulting in a panic during initialization of the aws s3 client
