### ISSUE TITLE
[Bug]: Create FLAT index type failed with error `context deadline exceeded`

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#26024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230728-1287a750
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):rocksmq    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
2023-07-31T02:23:58.228Z] 2023-07-31 02:23:46.131 | INFO     | MainThread |utils:create_index:179 - FLAT

[2023-07-31T02:23:58.228Z] 2023-07-31 02:23:46.131 | INFO     | MainThread |utils:create_index:180 - <Collection>:

[2023-07-31T02:23:58.228Z] -------------

[2023-07-31T02:23:58.228Z] <name>: task_1_FLAT

[2023-07-31T02:23:58.228Z] <description>: test collection

[2023-07-31T02:23:58.228Z] <schema>: {'auto_id': False, 'description': 'test collection', 'fields': [{'name': 'count', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'random_value', 'description': '', 'type': <DataType.DOUBLE: 11>}, {'name': 'float_vector', 'description': '', 'type': <DataType.FLOAT_VECTOR: 101>, 'params': {'dim': 128}}]}

[2023-07-31T02:23:58.228Z] 

[2023-07-31T02:24:54.403Z] RPC error: [get_index_state], <MilvusException: (code=1, message=context deadline exceeded)>, <Time:{'RPC start': '2023-07-31 02:24:38.867384', 'RPC error': '2023-07-31 02:24:50.255657'}>

[2023-07-31T02:24:54.403Z] RPC error: [wait_for_creating_index], <MilvusException: (code=1, message=context deadline exceeded)>, <Time:{'RPC start': '2023-07-31 02:23:46.148054', 'RPC error': '2023-07-31 02:24:50.255794'}>

[2023-07-31T02:24:54.403Z] RPC error: [create_index], <MilvusException: (code=1, message=context deadline exceeded)>, <Time:{'RPC start': '2023-07-31 02:23:46.131481', 'RPC error': '2023-07-31 02:24:50.255828'}>

[2023-07-31T02:24:54.403Z] Traceback (most recent call last):

[2023-07-31T02:24:54.403Z]   File "scripts/action_before_reinstall.py", line 47, in <module>

[2023-07-31T02:24:54.403Z]     task_1(data_size, host)

[2023-07-31T02:24:54.403Z]   File "scripts/action_before_reinstall.py", line 15, in task_1

[2023-07-31T02:24:54.403Z]     create_index(prefix)

[2023-07-31T02:24:54.403Z]   File "/home/jenkins/agent/workspace/tests/python_client/deploy/scripts/utils.py", line 187, in create_index

[2023-07-31T02:24:54.403Z]     c.create_index(field_name="float_vector", index_params=index)

[2023-07-31T02:24:54.403Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 1207, in create_index

[2023-07-31T02:24:54.403Z]     return conn.create_index(self._name, field_name, index_params, timeout=timeout, **kwargs)

[2023-07-31T02:24:54.403Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 126, in handler

[2023-07-31T02:24:54.403Z]     raise e from e

[2023-07-31T02:24:54.403Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 122, in handler

[2023-07-31T02:24:54.403Z]     return func(*args, **kwargs)

[2023-07-31T02:24:54.403Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 161, in handler

[2023-07-31T02:24:54.403Z]     return func(self, *args, **kwargs)

[2023-07-31T02:24:54.403Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 101, in handler

[2023-07-31T02:24:54.403Z]     raise e from e

[2023-07-31T02:24:54.403Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 68, in handler

[2023-07-31T02:24:54.403Z]     return func(*args, **kwargs)

[2023-07-31T02:24:54.403Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 870, in create_index

[2023-07-31T02:24:54.403Z]     index_success, fail_reason = self.wait_for_creating_index(

[2023-07-31T02:24:54.403Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 126, in handler

[2023-07-31T02:24:54.403Z]     raise e from e

[2023-07-31T02:24:54.403Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 122, in handler

[2023-07-31T02:24:54.403Z]     return func(*args, **kwargs)

[2023-07-31T02:24:54.403Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 161, in handler

[2023-07-31T02:24:54.403Z]     return func(self, *args, **kwargs)

[2023-07-31T02:24:54.403Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 101, in handler

[2023-07-31T02:24:54.403Z]     raise e from e

[2023-07-31T02:24:54.403Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 68, in handler

[2023-07-31T02:24:54.403Z]     return func(*args, **kwargs)

[2023-07-31T02:24:54.403Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 979, in wait_for_creating_index

[2023-07-31T02:24:54.403Z]     state, fail_reason = self.get_index_state(

[2023-07-31T02:24:54.403Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 126, in handler

[2023-07-31T02:24:54.403Z]     raise e from e

[2023-07-31T02:24:54.403Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 122, in handler

[2023-07-31T02:24:54.403Z]     return func(*args, **kwargs)

[2023-07-31T02:24:54.403Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 161, in handler

[2023-07-31T02:24:54.403Z]     return func(self, *args, **kwargs)

[2023-07-31T02:24:54.403Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 101, in handler

[2023-07-31T02:24:54.403Z]     raise e from e

[2023-07-31T02:24:54.403Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 68, in handler

[2023-07-31T02:24:54.403Z]     return func(*args, **kwargs)

[2023-07-31T02:24:54.403Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 957, in get_index_state

[2023-07-31T02:24:54.403Z]     raise MilvusException(status.error_code, status.reason)

[2023-07-31T02:24:54.403Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=context deadline exceeded)>
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_for_release_cron/detail/deploy_test_for_release_cron/731/pipeline

log:

[artifacts-rocksmq-standalone-reinstall-731-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/12212252/artifacts-rocksmq-standalone-reinstall-731-server-logs.tar.gz)
[artifacts-rocksmq-standalone-reinstall-731-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/12212253/artifacts-rocksmq-standalone-reinstall-731-pytest-logs.tar.gz)

**Comment by longjiquan** [comment]
Please assign me when the issue is reproduced. thx.
/assign @zhuwenxing 
/unassign
