### ISSUE TITLE
[Bug]: Search failed with error `fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_5_443234812286237113v0 is not available in any replica, err=<nil>`

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#26047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-20230731-0e5f0a6b
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):kafka    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The search failed during the test

![image](https://github.com/milvus-io/milvus/assets/12268675/bfd4d226-e53c-42e2-aa5e-1d8301900f90)

all pods are healthy

![image](https://github.com/milvus-io/milvus/assets/12268675/2dfe9704-56d7-483f-adb6-bf82a4de4808)

```
[2023-07-31T12:34:40.809Z] <name>: deploy_test_index_type_BIN_IVF_FLAT_is_compacted_not_compacted_segment_status_all_is_string_indexed_is_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000

[2023-07-31T12:34:40.809Z] <description>: 

[2023-07-31T12:34:40.809Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64',......  (api_request.py:37)

[2023-07-31T12:34:40.809Z] [2023-07-31 12:32:58 - INFO - ci_test]: inserted 3000 data into collection deploy_test_index_type_BIN_IVF_FLAT_is_compacted_not_compacted_segment_status_all_is_string_indexed_is_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000 (common_func.py:1194)

[2023-07-31T12:34:40.809Z] [2023-07-31 12:32:58 - DEBUG - ci_test]: Dynamic field is enabled: False (common_func.py:1196)

[2023-07-31T12:34:40.809Z] [2023-07-31 12:32:59 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [      int64   float varchar                                      binary_vector

[2023-07-31T12:34:40.809Z] 0         0     0.0       0     b"}[\xd8h'\x13i\xe3\x97\xd9\xc9\xd3\xcf\xbbD!"

[2023-07-31T12:34:40.809Z] 1         1     1.0       1     b'\xd9l\xda\xa6,\xd44\xbdBG\xe2DH\x1d\xae\xc9'

[2023-07-31T12:34:40.809Z] 2         2     2.0       2           b'\xe9q7\x80\x14{U?\xa3\......, kwargs: {'timeout': 120} (api_request.py:62)

[2023-07-31T12:34:40.809Z] [2023-07-31 12:33:00 - DEBUG - ci_test]: (api_response) : (insert count: 3000, delete count: 0, upsert count: 0, timestamp: 443234852523212811, success count: 3000, err count: 0)  (api_request.py:37)

[2023-07-31T12:34:40.809Z] [2023-07-31 12:33:00 - DEBUG - ci_test]: (api_request)  : [Collection.release] args: [], kwargs: {'timeout': 120} (api_request.py:62)

[2023-07-31T12:34:40.809Z] [2023-07-31 12:33:07 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-07-31T12:34:40.809Z] [2023-07-31 12:33:07 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:62)

[2023-07-31T12:34:40.809Z] [2023-07-31 12:33:09 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-07-31T12:34:40.809Z] [2023-07-31 12:33:09 - DEBUG - ci_test]: (api_request)  : [wait_for_loading_complete] args: ['deploy_test_index_type_BIN_IVF_FLAT_is_compacted_not_compacted_segment_status_all_is_string_indexed_is_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000', None, 20, 'default'], kwargs: {} (api_request.py:62)

[2023-07-31T12:34:40.809Z] [2023-07-31 12:33:09 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-07-31T12:34:40.809Z] [2023-07-31 12:33:09 - INFO - ci_test]: Test case of search interface: initialize before test case (client_base.py:241)

[2023-07-31T12:34:40.809Z] [2023-07-31 12:33:09 - DEBUG - ci_test]: (api_request)  : [Connections.connect] args: ['default', '', '', ''], kwargs: {'host': '10.255.3.167', 'port': 19530} (api_request.py:62)

[2023-07-31T12:34:40.809Z] [2023-07-31 12:33:09 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-07-31T12:34:40.809Z] [2023-07-31 12:33:09 - DEBUG - ci_test]: (api_request)  : [FieldSchema] args: ['int64', <DataType.INT64: 5>, ''], kwargs: {'is_primary': False} (api_request.py:62)

[2023-07-31T12:34:40.809Z] [2023-07-31 12:33:09 - DEBUG - ci_test]: (api_response) : {'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>}  (api_request.py:37)

[2023-07-31T12:34:40.809Z] [2023-07-31 12:33:09 - DEBUG - ci_test]: (api_request)  : [FieldSchema] args: ['float', <DataType.FLOAT: 10>, ''], kwargs: {'is_primary': False} (api_request.py:62)

[2023-07-31T12:34:40.809Z] [2023-07-31 12:33:09 - DEBUG - ci_test]: (api_response) : {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}  (api_request.py:37)

[2023-07-31T12:34:40.809Z] [2023-07-31 12:33:09 - DEBUG - ci_test]: (api_request)  : [FieldSchema] args: ['varchar', <DataType.VARCHAR: 21>, ''], kwargs: {'max_length': 65535, 'is_primary': False} (api_request.py:62)

[2023-07-31T12:34:40.809Z] [2023-07-31 12:33:09 - DEBUG - ci_test]: (api_response) : {'name': 'varchar', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 65535}}  (api_request.py:37)

[2023-07-31T12:34:40.809Z] [2023-07-31 12:33:09 - DEBUG - ci_test]: (api_request)  : [FieldSchema] args: ['json_field', <DataType.JSON: 23>, ''], kwargs: {'is_primary': False} (api_request.py:62)

[2023-07-31T12:34:40.809Z] [2023-07-31 12:33:09 - DEBUG - ci_test]: (api_response) : {'name': 'json_field', 'description': '', 'type': <DataType.JSON: 23>}  (api_request.py:37)

[2023-07-31T12:34:40.809Z] [2023-07-31 12:33:09 - DEBUG - ci_test]: (api_request)  : [FieldSchema] args: ['float_vector', <DataType.FLOAT_VECTOR: 101>, ''], kwargs: {'dim': 128, 'is_primary': False} (api_request.py:62)

[2023-07-31T12:34:40.809Z] [2023-07-31 12:33:09 - DEBUG - ci_test]: (api_response) : {'name': 'float_vector', 'description': '', 'type': <DataType.FLOAT_VECTOR: 101>, 'params': {'dim': 128}}  (api_request.py:37)

[2023-07-31T12:34:40.809Z] [2023-07-31 12:33:09 - DEBUG - ci_test]: (api_request)  : [FieldSchema] args: ['json_field', <DataType.JSON: 23>, ''], kwargs: {'is_primary': False} (api_request.py:62)

[2023-07-31T12:34:40.809Z] [2023-07-31 12:33:09 - DEBUG - ci_test]: (api_response) : {'name': 'json_field', 'description': '', 'type': <DataType.JSON: 23>}  (api_request.py:37)

[2023-07-31T12:34:40.809Z] [2023-07-31 12:33:09 - DEBUG - ci_test]: (api_request)  : [CollectionSchema] args: [[{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}, {'name': 'varchar', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 65535}}, {'name': 'float_vector', 'description': '', 'type': <DataT......, kwargs: {'primary_field': 'int64', 'auto_id': False, 'enable_dynamic_field': False} (api_request.py:62)

[2023-07-31T12:34:40.809Z] [2023-07-31 12:33:09 - DEBUG - ci_test]: (api_response) : {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}, {'name': 'varchar', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params......  (api_request.py:37)

[2023-07-31T12:34:40.809Z] [2023-07-31 12:33:09 - DEBUG - ci_test]: (api_request)  : [FieldSchema] args: ['int64', <DataType.INT64: 5>, ''], kwargs: {'is_primary': False} (api_request.py:62)

[2023-07-31T12:34:40.809Z] [2023-07-31 12:33:09 - DEBUG - ci_test]: (api_response) : {'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>}  (api_request.py:37)

[2023-07-31T12:34:40.809Z] [2023-07-31 12:33:09 - DEBUG - ci_test]: (api_request)  : [FieldSchema] args: ['float', <DataType.FLOAT: 10>, ''], kwargs: {'is_primary': False} (api_request.py:62)

[2023-07-31T12:34:40.809Z] [2023-07-31 12:33:09 - DEBUG - ci_test]: (api_response) : {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}  (api_request.py:37)

[2023-07-31T12:34:40.809Z] [2023-07-31 12:33:09 - DEBUG - ci_test]: (api_request)  : [FieldSchema] args: ['varchar', <DataType.VARCHAR: 21>, ''], kwargs: {'max_length': 65535, 'is_primary': False} (api_request.py:62)

[2023-07-31T12:34:40.809Z] [2023-07-31 12:33:09 - DEBUG - ci_test]: (api_response) : {'name': 'varchar', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 65535}}  (api_request.py:37)

[2023-07-31T12:34:40.809Z] [2023-07-31 12:33:09 - DEBUG - ci_test]: (api_request)  : [FieldSchema] args: ['binary_vector', <DataType.BINARY_VECTOR: 100>, ''], kwargs: {'dim': 128, 'is_primary': False} (api_request.py:62)

[2023-07-31T12:34:40.809Z] [2023-07-31 12:33:09 - DEBUG - ci_test]: (api_response) : {'name': 'binary_vector', 'description': '', 'type': <DataType.BINARY_VECTOR: 100>, 'params': {'dim': 128}}  (api_request.py:37)

[2023-07-31T12:34:40.810Z] [2023-07-31 12:33:09 - DEBUG - ci_test]: (api_request)  : [CollectionSchema] args: [[{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}, {'name': 'varchar', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 65535}}, {'name': 'binary_vector', 'description': '', 'type': <Data......, kwargs: {'primary_field': 'int64', 'auto_id': False} (api_request.py:62)

[2023-07-31T12:34:40.810Z] [2023-07-31 12:33:09 - DEBUG - ci_test]: (api_response) : {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}, {'name': 'varchar', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params......  (api_request.py:37)

[2023-07-31T12:34:40.810Z] [2023-07-31 12:33:09 - INFO - ci_test]: init_collection_general: collection creation (client_base.py:262)

[2023-07-31T12:34:40.810Z] [2023-07-31 12:33:09 - DEBUG - ci_test]: (api_request)  : [Connections.has_connection] args: ['default'], kwargs: {} (api_request.py:62)

[2023-07-31T12:34:40.810Z] [2023-07-31 12:33:09 - DEBUG - ci_test]: (api_response) : True  (api_request.py:37)

[2023-07-31T12:34:40.810Z] [2023-07-31 12:33:09 - DEBUG - ci_test]: (api_request)  : [Collection] args: ['deploy_test_index_type_BIN_IVF_FLAT_is_compacted_not_compacted_segment_status_all_is_string_indexed_is_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000', {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_prima......, kwargs: {'consistency_level': 'Strong'} (api_request.py:62)

[2023-07-31T12:34:40.810Z] [2023-07-31 12:33:09 - DEBUG - ci_test]: (api_response) : <Collection>:

[2023-07-31T12:34:40.810Z] -------------

[2023-07-31T12:34:40.810Z] <name>: deploy_test_index_type_BIN_IVF_FLAT_is_compacted_not_compacted_segment_status_all_is_string_indexed_is_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000

[2023-07-31T12:34:40.810Z] <description>: 

[2023-07-31T12:34:40.810Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64',......  (api_request.py:37)

[2023-07-31T12:34:40.810Z] [2023-07-31 12:33:09 - INFO - ci_test]: inserted 3000 data into collection deploy_test_index_type_BIN_IVF_FLAT_is_compacted_not_compacted_segment_status_all_is_string_indexed_is_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000 (common_func.py:1194)

[2023-07-31T12:34:40.810Z] [2023-07-31 12:33:09 - DEBUG - ci_test]: Dynamic field is enabled: False (common_func.py:1196)

[2023-07-31T12:34:40.810Z] [2023-07-31 12:33:09 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [      int64   float varchar                                      binary_vector

[2023-07-31T12:34:40.810Z] 0         0     0.0       0       b'<s\xddP\xab\xdb\x1bT\n\xa1!\xfb3i\xaa\x0b'

[2023-07-31T12:34:40.810Z] 1         1     1.0       1     b'\xaf\x065\x90\x9ft\xc7}\xd8PON\x85c\xde\xca'

[2023-07-31T12:34:40.810Z] 2         2     2.0       2  b'\xe9e\xa8T\xf7\xd8}\xdb\x89\xdb......, kwargs: {'timeout': 120} (api_request.py:62)

[2023-07-31T12:34:40.810Z] [2023-07-31 12:33:09 - DEBUG - ci_test]: (api_response) : (insert count: 3000, delete count: 0, upsert count: 0, timestamp: 443234854998900737, success count: 3000, err count: 0)  (api_request.py:37)

[2023-07-31T12:34:40.810Z] [2023-07-31 12:33:09 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[b'\xad\x95n\x03\xf4g\x0c\xad\xf9,\xc9C\x02\xcd\xc6\x1f', b'j,,!\xaa\xd0\x8c\xcfR\x8ds\x1a\xb9_\xda\xcf'], 'binary_vector', {'metric_type': 'HAMMING', 'params': {'nprobe': 10}}, 10, 'int64 >= 0', None, None, 120, -1], kwargs: {} (api_request.py:62)

[2023-07-31T12:34:40.810Z] [2023-07-31 12:33:20 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:

[2023-07-31T12:34:40.810Z] attempt #1:code: NotShardLeader, error: Invalid shard leader

[2023-07-31T12:34:40.810Z] attempt #2:code: NotShardLeader, error: Invalid shard leader

[2023-07-31T12:34:40.810Z] attempt #3:All attempts results:

[2023-07-31T12:34:40.810Z] attempt #1:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_5_443234812286237113v0 is not available in any replica, err=<nil>

[2023-07-31T12:34:40.810Z] attempt #2:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_5_443234812286237113v0 is not available in any replica, err=<nil>

[2023-07-31T12:34:40.810Z] attempt #3:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_5_443234812286237113v0 is not available in any replica, err=<nil>

[2023-07-31T12:34:40.810Z] attempt #4:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_5_443234812286237113v0 is not available in any replica, err=<nil>

[2023-07-31T12:34:40.810Z] attempt #5:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_5_443234812286237113v0 is not available in any replica, err=<nil>

[2023-07-31T12:34:40.810Z] attempt #6:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_5_443234812286237113v0 is not available in any replica, err=<nil>

[2023-07-31T12:34:40.810Z] attempt #7:context deadline exceeded

[2023-07-31T12:34:40.810Z] 

[2023-07-31T12:34:40.810Z] attempt #4:context canceled

[2023-07-31T12:34:40.810Z] )>, <Time:{'RPC start': '2023-07-31 12:33:09.442660', 'RPC error': '2023-07-31 12:33:20.259877'}> (decorators.py:126)

[2023-07-31T12:34:40.810Z] [2023-07-31 12:33:20 - ERROR - ci_test]: Traceback (most recent call last):

[2023-07-31T12:34:40.810Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2023-07-31T12:34:40.810Z]     res = func(*args, **_kwargs)

[2023-07-31T12:34:40.810Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2023-07-31T12:34:40.810Z]     return func(*arg, **kwargs)

[2023-07-31T12:34:40.810Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 781, in search

[2023-07-31T12:34:40.810Z]     res = conn.search(

[2023-07-31T12:34:40.810Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 127, in handler

[2023-07-31T12:34:40.810Z]     raise e from e

[2023-07-31T12:34:40.810Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 123, in handler

[2023-07-31T12:34:40.810Z]     return func(*args, **kwargs)

[2023-07-31T12:34:40.810Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 162, in handler

[2023-07-31T12:34:40.810Z]     return func(self, *args, **kwargs)

[2023-07-31T12:34:40.810Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 102, in handler

[2023-07-31T12:34:40.810Z]     raise e from e

[2023-07-31T12:34:40.810Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 68, in handler

[2023-07-31T12:34:40.810Z]     return func(*args, **kwargs)

[2023-07-31T12:34:40.810Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 765, in search

[2023-07-31T12:34:40.810Z]     return self._execute_search_requests(

[2023-07-31T12:34:40.810Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 725, in _execute_search_requests

[2023-07-31T12:34:40.810Z]     raise pre_err from pre_err

[2023-07-31T12:34:40.810Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 716, in _execute_search_requests

[2023-07-31T12:34:40.810Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2023-07-31T12:34:40.810Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:

[2023-07-31T12:34:40.810Z] attempt #1:code: NotShardLeader, error: Invalid shard leader

[2023-07-31T12:34:40.810Z] attempt #2:code: NotShardLeader, error: Invalid shard leader

[2023-07-31T12:34:40.810Z] attempt #3:All attempts results:

[2023-07-31T12:34:40.810Z] attempt #1:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_5_443234812286237113v0 is not available in any replica, err=<nil>

[2023-07-31T12:34:40.810Z] attempt #2:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_5_443234812286237113v0 is not available in any replica, err=<nil>

[2023-07-31T12:34:40.810Z] attempt #3:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_5_443234812286237113v0 is not available in any replica, err=<nil>

[2023-07-31T12:34:40.810Z] attempt #4:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_5_443234812286237113v0 is not available in any replica, err=<nil>

[2023-07-31T12:34:40.810Z] attempt #5:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_5_443234812286237113v0 is not available in any replica, err=<nil>

[2023-07-31T12:34:40.810Z] attempt #6:fail to get shard leaders from QueryCoord: channel by-dev-rootcoord-dml_5_443234812286237113v0 is not available in any replica, err=<nil>

[2023-07-31T12:34:40.810Z] attempt #7:context deadline exceeded

[2023-07-31T12:34:40.810Z] 

[2023-07-31T12:34:40.810Z] attempt #4:context canceled

[2023-07-31T12:34:40.810Z] )>

[2023-07-31T12:34:40.810Z]  (api_request.py:45)

[2023-07-31T12:34:40.810Z] [2023-07-31 12:33:20 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:

[2023-07-31T12:34:40.810Z] attempt #1:code: NotShardLeader, error: Invalid shard leader

[2023-07-31T12:34:40.810Z] attempt #2:code: NotShardLeader, error: Invalid shard leader

[2023-07-31T12:34:40.810Z] attempt #3:All attempts results:

[2023-07-31T12:34:40.810Z] attempt #1:fail to get shard leaders from Query...... (api_request.py:46)
```

### Expected Behavior

all test cases pass

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_kafka_for_release_cron/detail/deploy_test_kafka_for_release_cron/1272/pipeline/

log:
[artifacts-kafka-standalone-reinstall-1272-server-second-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/12224323/artifacts-kafka-standalone-reinstall-1272-server-second-deployment-logs.tar.gz)

[artifacts-kafka-standalone-reinstall-1272-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/12224324/artifacts-kafka-standalone-reinstall-1272-pytest-logs.tar.gz)

**Comment by jiaoew1991** [comment]
It can be seen that querynode unsubscribed and subscribed twice each, triggered by etcd watch and unwatch, occurring after **20:33:00**
<img width="1337" alt="image" src="https://github.com/milvus-io/milvus/assets/2297455/8cd20f1e-3558-4d96-9310-e6dfe3de1fcb">

From the etcd logs, it can be seen that there have been no logs after **20:33:00**. It is suspected that etcd has become stuck.
![image](https://github.com/milvus-io/milvus/assets/2297455/d8cba797-891d-4d13-8f33-89bf67e3f668)
