### ISSUE TITLE
Row count of fields must be equal

### ISSUE THREAD

**Issue by xiaochanghui** [milvus-io/milvus#26052]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

io.milvus.exception.ParamException: Row count of fields must be equal
	at io.milvus.param.dml.InsertParam$Builder.build(InsertParam.java:127)
	at org.springblade.modules.chatgpt.gptUtil.MilvusClientUtil.insertParttonsName(MilvusClientUtil.java:188)
	at org.springblade.modules.chatgpt.service.impl.KnowledgeServiceImpl.textTOmilvus(KnowledgeServiceImpl.java:201)
	at org.springblade.modules.chatgpt.thread.MilvusThread.run(MilvusThread.java:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

### Describe the solution you'd like.

How to solve it

### Describe an alternate solution.

How to solve it

### Anything else? (Additional Context)

How to solve it

**Comment by xiaofan-luan** [comment]
> MilvusThread

Seems like it's your code inserted entity didn't match your schema

**Comment by xiaofan-luan** [comment]
/assign @xiaochanghui
please check your code, if still no reason, paste your code of create collection and insertion

**Comment by xiaochanghui** [comment]
List<InsertParam.Field> fields = new ArrayList<>();
        fields.add(new InsertParam.Field(CONTENT_FIELD, dataSqlEntity.getContent()));
        fields.add(new InsertParam.Field(VECTOR_FIELD, dataSqlEntity.getLl()));

        InsertParam insertParam = InsertParam.newBuilder()
                .withCollectionName(collectionName)
                .withFields(fields)
                .build();

        R<MutationResult> response = milvusClient.insert(insertParam);
        handleResponseStatus(response);
        return response;

**Comment by xiaofan-luan** [comment]
so you only have two field? CONTENT_FIELD and. VECTOR_FIELD?
How did you create the collection
