### ISSUE TITLE
[Bug]: Rootcoord will panic and keep restart after rootcoord pod kill or pod failure chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#26160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230804-13f69bfc
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/12268675/09b481da-c5d9-4078-98fd-83947ec4d7c0)

```
(*proxyClientManager).RefreshPolicyInfoCache.func1\n/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 golang.org/x/sync/errgroup.(*Group).Go.func1\n/usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit\n\n"] [stack="github.com/milvus-io/milvus/internal/rootcoord.(*Core).startInternal\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:682\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).Start.func1\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:704\nsync.(*Once).doSlow\n\t/usr/local/go/src/sync/once.go:68\nsync.(*Once).Do\n\t/usr/local/go/src/sync/once.go:59\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).Start\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:703\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).start\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:289\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:160\ngithub.com/milvus-io/milvus/cmd/components.(*RootCoord).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/root_coord.go:56\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:120"]
panic: fail to refresh policy info cache

goroutine 244 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc004283a40, {0xc0027afb40, 0x1, 0x1})
	/go/pkg/mod/go.uber.org/zap@v1.17.0/zapcore/entry.go:234 +0x49b
go.uber.org/zap.(*Logger).Panic(0xc0027afb40?, {0x42a6e61?, 0x12?}, {0xc0027afb40, 0x1, 0x1})
	/go/pkg/mod/go.uber.org/zap@v1.17.0/logger.go:227 +0x59
github.com/milvus-io/milvus/internal/log.Panic({0x42a6e61?, 0xc0012ba980?}, {0xc0027afb40?, 0xc002187af0?, 0x2?})
	/go/src/github.com/milvus-io/milvus/internal/log/global.go:58 +0x8b
github.com/milvus-io/milvus/internal/rootcoord.(*Core).startInternal(0xc001287080)
	/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:682 +0x39f
github.com/milvus-io/milvus/internal/rootcoord.(*Core).Start.func1()
	/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:704 +0x26
sync.(*Once).doSlow(0xc0002bfe40?, 0x47074d0?)
	/usr/local/go/src/sync/once.go:68 +0xc2
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:59
github.com/milvus-io/milvus/internal/rootcoord.(*Core).Start(0xc001287080?)
	/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:703 +0x67
github.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).start(0xc001298dc0)
	/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:289 +0x1d1
github.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).Run(0xc00088cf08?)
	/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:160 +0x4f
github.com/milvus-io/milvus/cmd/components.(*RootCoord).Run(0x5ef2b80?)
	/go/src/github.com/milvus-io/milvus/cmd/components/root_coord.go:56 +0x2f
github.com/milvus-io/milvus/cmd/roles.runComponent[...].func1()
	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:120 +0x182
created by github.com/milvus-io/milvus/cmd/roles.runComponent[...]
	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:104 +0x18a
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-for-release-cron/detail/chaos-test-kafka-for-release-cron/6542/pipeline

log:
[artifacts-rootcoord-pod-kill-6542-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/12271505/artifacts-rootcoord-pod-kill-6542-server-logs.tar.gz)

[artifacts-rootcoord-pod-kill-6542-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/12271506/artifacts-rootcoord-pod-kill-6542-pytest-logs.tar.gz)

### Anything else?

It can be reproduced stably

**Comment by zhuwenxing** [comment]
/assign @SimFG 
Please take a look. it looks like related to https://github.com/milvus-io/milvus/pull/25988

**Comment by SimFG** [comment]
@zhuwenxing it will be fixed in the https://github.com/milvus-io/milvus/pull/26151 and  https://github.com/milvus-io/milvus/pull/26150

**Comment by yanliang567** [comment]
@SimFG please assign back to wenxing as the PRs merged

**Comment by SimFG** [comment]
@yanliang567 ok, two prs is reviewing

**Comment by SimFG** [comment]
@zhuwenxing please help to check it again

**Comment by zhuwenxing** [comment]
Verified with 2.2.0-20230807-ef31fe23 and passed
