### ISSUE TITLE
[Bug]: Segment is empty after load finished

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#26211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230808-506ec414
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):kafka    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2023-08-08T07:50:01.570Z] + python3 scripts/first_recall_test.py --host 10.255.91.37

[2023-08-08T07:50:02.130Z] 2023-08-08 07:50:01.845 | INFO     | __main__:milvus_recall_test:73 - recall test for index type HNSW

[2023-08-08T07:50:03.061Z] 2023-08-08 07:50:03.027 | INFO     | __main__:milvus_recall_test:87 - Create collection sift_128_euclidean_HNSW

[2023-08-08T07:50:04.948Z] 2023-08-08 07:50:04.927 | INFO     | __main__:milvus_recall_test:94 - epoch: 0

[2023-08-08T07:50:17.114Z] 2023-08-08 07:50:15.516 | INFO     | __main__:milvus_recall_test:94 - epoch: 1

[2023-08-08T07:50:17.675Z] 2023-08-08 07:50:17.458 | INFO     | __main__:milvus_recall_test:94 - epoch: 2

[2023-08-08T07:50:19.560Z] 2023-08-08 07:50:19.431 | INFO     | __main__:milvus_recall_test:94 - epoch: 3

[2023-08-08T07:50:22.078Z] 2023-08-08 07:50:21.505 | INFO     | __main__:milvus_recall_test:94 - epoch: 4

[2023-08-08T07:50:23.964Z] 2023-08-08 07:50:23.567 | INFO     | __main__:milvus_recall_test:94 - epoch: 5

[2023-08-08T07:50:25.850Z] 2023-08-08 07:50:25.556 | INFO     | __main__:milvus_recall_test:94 - epoch: 6

[2023-08-08T07:50:27.739Z] 2023-08-08 07:50:27.707 | INFO     | __main__:milvus_recall_test:94 - epoch: 7

[2023-08-08T07:50:31.001Z] 2023-08-08 07:50:30.474 | INFO     | __main__:milvus_recall_test:94 - epoch: 8

[2023-08-08T07:50:32.889Z] 2023-08-08 07:50:32.781 | INFO     | __main__:milvus_recall_test:94 - epoch: 9

[2023-08-08T07:50:35.406Z] 2023-08-08 07:50:34.960 | INFO     | __main__:milvus_recall_test:94 - epoch: 10

[2023-08-08T07:50:37.293Z] 2023-08-08 07:50:37.200 | INFO     | __main__:milvus_recall_test:94 - epoch: 11

[2023-08-08T07:50:39.805Z] 2023-08-08 07:50:39.413 | INFO     | __main__:milvus_recall_test:94 - epoch: 12

[2023-08-08T07:50:41.692Z] 2023-08-08 07:50:41.425 | INFO     | __main__:milvus_recall_test:94 - epoch: 13

[2023-08-08T07:50:44.204Z] 2023-08-08 07:50:43.832 | INFO     | __main__:milvus_recall_test:94 - epoch: 14

[2023-08-08T07:50:46.091Z] 2023-08-08 07:50:45.808 | INFO     | __main__:milvus_recall_test:94 - epoch: 15

[2023-08-08T07:50:47.979Z] 2023-08-08 07:50:47.787 | INFO     | __main__:milvus_recall_test:94 - epoch: 16

[2023-08-08T07:50:49.867Z] 2023-08-08 07:50:49.847 | INFO     | __main__:milvus_recall_test:94 - epoch: 17

[2023-08-08T07:50:52.376Z] 2023-08-08 07:50:51.925 | INFO     | __main__:milvus_recall_test:94 - epoch: 18

[2023-08-08T07:50:54.262Z] 2023-08-08 07:50:53.944 | INFO     | __main__:milvus_recall_test:94 - epoch: 19

[2023-08-08T07:50:56.775Z] 2023-08-08 07:50:56.693 | INFO     | __main__:milvus_recall_test:107 - Insert 1000000 vectors cost 51.7660 seconds

[2023-08-08T07:50:56.775Z] 2023-08-08 07:50:56.693 | INFO     | __main__:milvus_recall_test:110 - Get collection entities...

[2023-08-08T07:50:59.287Z] 2023-08-08 07:50:59.239 | INFO     | __main__:milvus_recall_test:115 - 1000000

[2023-08-08T07:50:59.289Z] 2023-08-08 07:50:59.239 | INFO     | __main__:milvus_recall_test:117 - Get collection entities cost 2.5457 seconds

[2023-08-08T07:50:59.289Z] 2023-08-08 07:50:59.239 | INFO     | __main__:milvus_recall_test:121 - Create index...

[2023-08-08T07:50:59.851Z] 2023-08-08 07:50:59.765 | INFO     | __main__:milvus_recall_test:126 - Create index cost 0.5261 seconds

[2023-08-08T07:50:59.851Z] 2023-08-08 07:50:59.765 | INFO     | __main__:milvus_recall_test:130 - load collection...

[2023-08-08T07:51:01.735Z] 2023-08-08 07:51:01.309 | INFO     | __main__:milvus_recall_test:134 - load collection cost 1.5436 seconds

[2023-08-08T07:51:01.735Z] 2023-08-08 07:51:01.311 | INFO     | __main__:milvus_recall_test:137 - segments info: []

[2023-08-08T07:51:01.735Z] Traceback (most recent call last):

[2023-08-08T07:51:01.735Z]   File "scripts/first_recall_test.py", line 200, in <module>

[2023-08-08T07:51:01.735Z]     milvus_recall_test(host, index_type)

[2023-08-08T07:51:01.735Z]   File "scripts/first_recall_test.py", line 140, in milvus_recall_test

[2023-08-08T07:51:01.735Z]     assert cnt == collection.num_entities

[2023-08-08T07:51:01.736Z] AssertionError
```

cnt is the sum of num_rows in all segments

in ordinary cases, it looks like
![image](https://github.com/milvus-io/milvus/assets/12268675/e8bcc322-05cb-4836-9a30-82fc9fa814a1)

### Expected Behavior

We can get segments after loaded and sum of num_rows is equal to num_entities

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_kafka_for_release_cron/detail/deploy_test_kafka_for_release_cron/1300/pipeline

log:

[artifacts-kafka-standalone-reinstall-1300-server-second-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/12289372/artifacts-kafka-standalone-reinstall-1300-server-second-deployment-logs.tar.gz)

pod info
```

[2023-08-08T08:05:08.851Z] + kubectl get pods -o wide

[2023-08-08T08:05:08.853Z] + grep kafka-standalone-reinstall-1300

[2023-08-08T08:05:09.112Z] kafka-standalone-reinstall-1300-0                                 2/2     Running       1 (17m ago)      18m     10.104.12.198   4am-node17   <none>           <none>

[2023-08-08T08:05:09.112Z] kafka-standalone-reinstall-1300-1                                 2/2     Running       2 (17m ago)      18m     10.104.18.87    4am-node25   <none>           <none>

[2023-08-08T08:05:09.112Z] kafka-standalone-reinstall-1300-2                                 2/2     Running       2 (17m ago)      18m     10.104.20.135   4am-node22   <none>           <none>

[2023-08-08T08:05:09.112Z] kafka-standalone-reinstall-1300-etcd-0                            1/1     Running       0                18m     10.104.18.84    4am-node25   <none>           <none>

[2023-08-08T08:05:09.112Z] kafka-standalone-reinstall-1300-etcd-1                            1/1     Running       0                18m     10.104.20.133   4am-node22   <none>           <none>

[2023-08-08T08:05:09.112Z] kafka-standalone-reinstall-1300-etcd-2                            1/1     Running       0                18m     10.104.12.199   4am-node17   <none>           <none>

[2023-08-08T08:05:09.112Z] kafka-standalone-reinstall-1300-exporter-584b847b8d-q8bs7         1/1     Running       5 (16m ago)      18m     10.104.18.81    4am-node25   <none>           <none>

[2023-08-08T08:05:09.112Z] kafka-standalone-reinstall-1300-milvus-standalone-68744c96x6ht6   1/1     Running       0                18m     10.104.14.143   4am-node18   <none>           <none>

[2023-08-08T08:05:09.112Z] kafka-standalone-reinstall-1300-minio-f6c957dcf-7m9r9             1/1     Running       0                18m     10.104.17.10    4am-node23   <none>           <none>

[2023-08-08T08:05:09.112Z] kafka-standalone-reinstall-1300-zookeeper-0                       1/1     Running       0                18m     10.104.17.11    4am-node23   <none>           <none>

[2023-08-08T08:05:09.112Z] kafka-standalone-reinstall-1300-zookeeper-1                       1/1     Running       0                18m     10.104.6.143    4am-node13   <none>           <none>

[2023-08-08T08:05:09.112Z] kafka-standalone-reinstall-1300-zookeeper-2                       1/1     Running       0                18m     10.104.20.134   4am-node22   <none>           <none>
```

**Comment by zhuwenxing** [comment]
It works well with the image 2.2.0-20230807-ef31fe23


failed job:
```
[2023-08-08T08:22:03.337Z] 2023-08-08 08:22:02.760 | INFO     | __main__:milvus_recall_test:110 - Get collection entities...

[2023-08-08T08:22:05.847Z] 2023-08-08 08:22:05.278 | INFO     | __main__:milvus_recall_test:115 - 1000000

[2023-08-08T08:22:05.847Z] 2023-08-08 08:22:05.278 | INFO     | __main__:milvus_recall_test:117 - Get collection entities cost 2.5177 seconds

[2023-08-08T08:22:05.847Z] 2023-08-08 08:22:05.278 | INFO     | __main__:milvus_recall_test:121 - Create index...

[2023-08-08T08:22:06.102Z] 2023-08-08 08:22:05.885 | INFO     | __main__:milvus_recall_test:126 - Create index cost 0.6064 seconds

[2023-08-08T08:22:06.102Z] 2023-08-08 08:22:05.885 | INFO     | __main__:milvus_recall_test:130 - load collection...

[2023-08-08T08:22:08.621Z] 2023-08-08 08:22:08.457 | INFO     | __main__:milvus_recall_test:134 - load collection cost 2.5719 seconds
```

success job
```

[2023-08-08T09:13:57.946Z] 2023-08-08 09:13:57.714 | INFO     | __main__:milvus_recall_test:107 - Insert 1000000 vectors cost 52.3866 seconds

[2023-08-08T09:13:57.948Z] 2023-08-08 09:13:57.714 | INFO     | __main__:milvus_recall_test:110 - Get collection entities...

[2023-08-08T09:14:00.462Z] 2023-08-08 09:14:00.230 | INFO     | __main__:milvus_recall_test:115 - 1000000

[2023-08-08T09:14:00.464Z] 2023-08-08 09:14:00.230 | INFO     | __main__:milvus_recall_test:117 - Get collection entities cost 2.5159 seconds

[2023-08-08T09:14:00.464Z] 2023-08-08 09:14:00.230 | INFO     | __main__:milvus_recall_test:121 - Create index...

[2023-08-08T09:17:21.859Z] 2023-08-08 09:17:12.162 | INFO     | __main__:milvus_recall_test:126 - Create index cost 191.9320 seconds

[2023-08-08T09:17:21.859Z] 2023-08-08 09:17:12.162 | INFO     | __main__:milvus_recall_test:130 - load collection...

[2023-08-08T09:17:21.859Z] 2023-08-08 09:17:18.236 | INFO     | __main__:milvus_recall_test:134 - load collection cost 6.0739 seconds
```

In the failed job, creating index costs 0.6064 seconds while it costs 191.9320 seconds in success job.  same for load time, failed job costs less time.

**Comment by xiaocai2333** [comment]
Because the method of judging whether the index is completed has been changed, the previous problem is exposed: `the number of unissued index tasks is wrongly assigned to the number of none`, resulting in that when all tasks are unissued, the task index status is considered finished.

**Comment by xiaocai2333** [comment]
master doesn't have same bug.

**Comment by zhuwenxing** [comment]
verified and passed with image 2.2.0-20230808-4d4e8cd8
