### ISSUE TITLE
[Bug]: [Nightly]Search failed more frequently due to use of closed network connection

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#26223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 21eeb37
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0.dev109
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Search failed more frequently using DISKANN due to use of closed network connection.
```
[2023-08-08T19:31:52.741Z] [2023-08-08 19:14:30 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=attempt #0: fail to Search, QueryNode ID=1, reason=err: rpc error: code = Unavailable desc = error reading from server: read tcp 10.105.1.211:56458->10.105.7.47:21123: use of closed network connection
[2023-08-08T19:31:52.741Z] , /go/src/github.com/milvus-io/milvus/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace
[2023-08-08T19:31:52.741Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:356 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall
[2023-08-08T19:31:52.741Z] /go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:101 github.com/milvus-io/milvus/internal/distributed/querynode/client.wrapGrpcCall[...]
[2023-08-08T19:31:52.741Z] /go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:219 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).SearchSegments
[2023-08-08T19:31:52.741Z] /go/src/github.com/milvus-io/milvus/internal/querynodev2/cluster/worker.go:123 github.com/milvus-io/milvus/internal/querynodev2/cluster.(*remoteWorker).SearchSegments
[2023-08-08T19:31:52.741Z] /go/src/github.com/milvus-io/milvus/internal/querynodev2/delegator/delegator.go:255 github.com/milvus-io/milvus/internal/querynodev2/delegator.(*shardDelegator).Search.func3
[2023-08-08T19:31:52.741Z] /go/src/github.com/milvus-io/milvus/internal/querynodev2/delegator/delegator.go:441 github.com/milvus-io/milvus/internal/querynodev2/delegator.executeSubTasks[...].func1
[2023-08-08T19:31:52.741Z] /usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit: channel=by-dev-rootcoord-dml_10_443421151795579651v0: fail to access shard delegator: attempt #1: no available shard delegator found: service unavailable: fail to search on all shard leaders)>, <Time:{'RPC start': '2023-08-08 19:14:29.543727', 'RPC error': '2023-08-08 19:14:30.912863'}> (decorators.py:126)
[2023-08-08T19:31:52.741Z] [2023-08-08 19:14:30 - ERROR - ci_test]: Traceback (most recent call last):
[2023-08-08T19:31:52.741Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper
[2023-08-08T19:31:52.741Z]     res = func(*args, **_kwargs)
[2023-08-08T19:31:52.741Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request
[2023-08-08T19:31:52.741Z]     return func(*arg, **kwargs)
[2023-08-08T19:31:52.741Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 781, in search
[2023-08-08T19:31:52.741Z]     res = conn.search(
[2023-08-08T19:31:52.741Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 127, in handler
[2023-08-08T19:31:52.741Z]     raise e from e
[2023-08-08T19:31:52.741Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 123, in handler
[2023-08-08T19:31:52.741Z]     return func(*args, **kwargs)
[2023-08-08T19:31:52.741Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 162, in handler
[2023-08-08T19:31:52.741Z]     return func(self, *args, **kwargs)
[2023-08-08T19:31:52.741Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 102, in handler
[2023-08-08T19:31:52.741Z]     raise e from e
[2023-08-08T19:31:52.741Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 68, in handler
[2023-08-08T19:31:52.741Z]     return func(*args, **kwargs)
[2023-08-08T19:31:52.741Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 765, in search
[2023-08-08T19:31:52.741Z]     return self._execute_search_requests(
[2023-08-08T19:31:52.741Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 725, in _execute_search_requests
[2023-08-08T19:31:52.741Z]     raise pre_err from pre_err
[2023-08-08T19:31:52.741Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 716, in _execute_search_requests
[2023-08-08T19:31:52.741Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2023-08-08T19:31:52.741Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=attempt #0: fail to Search, QueryNode ID=1, reason=err: rpc error: code = Unavailable desc = error reading from server: read tcp 10.105.1.211:56458->10.105.7.47:21123: use of closed network connection
[2023-08-08T19:31:52.741Z] , /go/src/github.com/milvus-io/milvus/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace
[2023-08-08T19:31:52.741Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:356 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall
[2023-08-08T19:31:52.741Z] /go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:101 github.com/milvus-io/milvus/internal/distributed/querynode/client.wrapGrpcCall[...]
[2023-08-08T19:31:52.741Z] /go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:219 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).SearchSegments
[2023-08-08T19:31:52.741Z] /go/src/github.com/milvus-io/milvus/internal/querynodev2/cluster/worker.go:123 github.com/milvus-io/milvus/internal/querynodev2/cluster.(*remoteWorker).SearchSegments
[2023-08-08T19:31:52.741Z] /go/src/github.com/milvus-io/milvus/internal/querynodev2/delegator/delegator.go:255 github.com/milvus-io/milvus/internal/querynodev2/delegator.(*shardDelegator).Search.func3
[2023-08-08T19:31:52.741Z] /go/src/github.com/milvus-io/milvus/internal/querynodev2/delegator/delegator.go:441 github.com/milvus-io/milvus/internal/querynodev2/delegator.executeSubTasks[...].func1
[2023-08-08T19:31:52.741Z] /usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit: channel=by-dev-rootcoord-dml_10_443421151795579651v0: fail to access shard delegator: attempt #1: no available shard delegator found: service unavailable: fail to search on all shard leaders)>
[2023-08-08T19:31:52.741Z]  (api_request.py:45)
[2023-08-08T19:31:52.741Z] [2023-08-08 19:14:30 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=attempt #0: fail to Search, QueryNode ID=1, reason=err: rpc error: code = Unavailable desc = error reading from server: read tcp 10.105.1.211:56458->10.105.7.47:21123: use of closed network connection
[2023-08-08T19:31:52.741Z] , /go/src/github.com/milvus-io/milvus/pkg/tracer/stack_trace.go:...... (api_request.py:46)
```

### Expected Behavior

search successfully

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/459/pipeline/273
2. log: [artifacts-milvus-distributed-pulsar-nightly-459-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/459/artifact/artifacts-milvus-distributed-pulsar-nightly-459-pymilvus-e2e-logs.tar.gz)
3. collection name: search_collection_fVXjlOGT
4. failed time: [2023-08-08T19:14:31.908Z] [gw3] [ 79%] FAILED testcases/test_search.py::TestCollectionRangeSearch::test_range_search_after_different_index_with_params[32-True-DISKANN-params5]

**Comment by NicoYuan1986** [comment]
similar one: 

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/458/pipeline/273
2. log: [artifacts-milvus-distributed-pulsar-nightly-458-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/458/artifact/artifacts-milvus-distributed-pulsar-nightly-458-pymilvus-e2e-logs.tar.gz)
3. collection name: search_collection_0oPciA1B
4. failed time: [2023-08-07T19:16:57.672Z] [gw0] [ 82%] FAILED testcases/test_search.py::TestSearchDiskann::test_search_diskann_search_list_equal_to_limit[128-False-True-True-100]

**Comment by yanliang567** [comment]
@NicoYuan1986 did any milvus pods restart?

**Comment by NicoYuan1986** [comment]
```
[2023-08-09T19:36:00.501Z] mdp-460-n-etcd-0                                    1/1     Running       0             100m   10.105.1.145   ci-node10   <none>           <none>
[2023-08-09T19:36:00.501Z] mdp-460-n-etcd-1                                    1/1     Running       0             100m   10.105.5.118   ci-node11   <none>           <none>
[2023-08-09T19:36:00.501Z] mdp-460-n-etcd-2                                    1/1     Running       0             100m   10.105.7.208   ci-node12   <none>           <none>
[2023-08-09T19:36:00.501Z] mdp-460-n-milvus-datacoord-5bf7449c59-lqpfd         1/1     Running       0             100m   10.105.5.112   ci-node11   <none>           <none>
[2023-08-09T19:36:00.502Z] mdp-460-n-milvus-datanode-547b685dbf-5jzwr          1/1     Running       1 (96m ago)   100m   10.105.7.191   ci-node12   <none>           <none>
[2023-08-09T19:36:00.502Z] mdp-460-n-milvus-datanode-547b685dbf-gg6g8          1/1     Running       1 (96m ago)   100m   10.105.5.107   ci-node11   <none>           <none>
[2023-08-09T19:36:00.502Z] mdp-460-n-milvus-indexcoord-6b8bb7c748-6fbnn        1/1     Running       0             100m   10.105.5.106   ci-node11   <none>           <none>
[2023-08-09T19:36:00.502Z] mdp-460-n-milvus-indexnode-5dfc794cfb-hgtjl         1/1     Running       0             100m   10.105.1.110   ci-node10   <none>           <none>
[2023-08-09T19:36:00.502Z] mdp-460-n-milvus-indexnode-5dfc794cfb-slh2p         1/1     Running       0             100m   10.105.7.190   ci-node12   <none>           <none>
[2023-08-09T19:36:00.502Z] mdp-460-n-milvus-proxy-f98b5869-bxvkh               1/1     Running       1 (96m ago)   100m   10.105.5.109   ci-node11   <none>           <none>
[2023-08-09T19:36:00.502Z] mdp-460-n-milvus-proxy-f98b5869-tf46z               1/1     Running       1 (96m ago)   100m   10.105.1.113   ci-node10   <none>           <none>
[2023-08-09T19:36:00.502Z] mdp-460-n-milvus-querycoord-5fd88b6447-kjg92        1/1     Running       1 (96m ago)   100m   10.105.5.110   ci-node11   <none>           <none>
[2023-08-09T19:36:00.502Z] mdp-460-n-milvus-querynode-9c86dbb74-b44bx          1/1     Running       0             100m   10.105.1.116   ci-node10   <none>           <none>
[2023-08-09T19:36:00.502Z] mdp-460-n-milvus-querynode-9c86dbb74-hcfc6          1/1     Running       0             100m   10.105.5.113   ci-node11   <none>           <none>
[2023-08-09T19:36:00.502Z] mdp-460-n-milvus-rootcoord-6dd46b85bd-jj9qj         1/1     Running       1 (96m ago)   100m   10.105.1.109   ci-node10   <none>           <none>
[2023-08-09T19:36:00.502Z] mdp-460-n-minio-89bfdcf8c-lvrmk                     1/1     Running       0             100m   10.105.1.147   ci-node10   <none>           <none>
[2023-08-09T19:36:00.502Z] mdp-460-n-pulsar-bookie-0                           1/1     Running       0             100m   10.105.1.148   ci-node10   <none>           <none>
[2023-08-09T19:36:00.502Z] mdp-460-n-pulsar-bookie-1                           1/1     Running       0             100m   10.105.7.206   ci-node12   <none>           <none>
[2023-08-09T19:36:00.502Z] mdp-460-n-pulsar-bookie-2                           1/1     Running       0             100m   10.105.5.125   ci-node11   <none>           <none>
[2023-08-09T19:36:00.502Z] mdp-460-n-pulsar-bookie-init-v2vxc                  0/1     Completed     0             100m   10.105.1.108   ci-node10   <none>           <none>
[2023-08-09T19:36:00.502Z] mdp-460-n-pulsar-broker-0                           1/1     Running       0             100m   10.105.1.112   ci-node10   <none>           <none>
[2023-08-09T19:36:00.502Z] mdp-460-n-pulsar-broker-1                           1/1     Running       0             100m   10.105.7.192   ci-node12   <none>           <none>
[2023-08-09T19:36:00.502Z] mdp-460-n-pulsar-proxy-0                            1/1     Running       0             100m   10.105.5.108   ci-node11   <none>           <none>
[2023-08-09T19:36:00.502Z] mdp-460-n-pulsar-pulsar-init-lcqss                  0/1     Completed     0             100m   10.105.1.111   ci-node10   <none>           <none>
[2023-08-09T19:36:00.502Z] mdp-460-n-pulsar-recovery-0                         1/1     Running       0             100m   10.105.5.111   ci-node11   <none>           <none>
[2023-08-09T19:36:00.502Z] mdp-460-n-pulsar-zookeeper-0                        1/1     Running       0             100m   10.105.1.154   ci-node10   <none>           <none>
[2023-08-09T19:36:00.502Z] mdp-460-n-pulsar-zookeeper-1                        1/1     Running       0             99m    10.105.5.135   ci-node11   <none>           <none>
[2023-08-09T19:36:00.502Z] mdp-460-n-pulsar-zookeeper-2                        1/1     Running       0             98m    10.105.7.219   ci-node12   <none>           <none>
```
```
[2023-08-09T19:36:00.758Z] mdp-460-n-milvus-datanode-547b685dbf-5jzwr restarts 1, last terminateed reason is "Error"
[2023-08-09T19:36:01.014Z] mdp-460-n-milvus-datanode-547b685dbf-gg6g8 restarts 1, last terminateed reason is "Error"
[2023-08-09T19:36:01.014Z] mdp-460-n-milvus-proxy-f98b5869-bxvkh restarts 1, last terminateed reason is "Error"
[2023-08-09T19:36:01.014Z] mdp-460-n-milvus-proxy-f98b5869-tf46z restarts 1, last terminateed reason is "Error"
[2023-08-09T19:36:01.268Z] mdp-460-n-milvus-querycoord-5fd88b6447-kjg92 restarts 1, last terminateed reason is "Error"
[2023-08-09T19:36:01.268Z] mdp-460-n-milvus-rootcoord-6dd46b85bd-jj9qj restarts 1, last terminateed reason is "Error"
```
These pod resarted.
https://grafana-ci.zilliz.cc/d/uLf5cJ3Gz/milvus2-0?orgId=1&from=1691603277067&to=1691610979392&var-datasource=prometheus&var-app_name=milvus&var-namespace=milvus-ci&var-instance=mdp-460-n&var-collection=search_collection_7ycwNYax&var-pod=mdp-460-n-milvus-datacoord-5bf7449c59-lqpfd&var-component=

**Comment by NicoYuan1986** [comment]
other error message:
```
[2023-08-13T19:34:56.664Z] E                   grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
[2023-08-13T19:34:56.664Z] E                   	status = StatusCode.UNAVAILABLE
[2023-08-13T19:34:56.664Z] E                   	details = "Socket closed"
[2023-08-13T19:34:56.664Z] E                   	debug_error_string = "UNKNOWN:Error received from peer ipv4:10.255.226.146:19530 {grpc_message:"Socket closed", grpc_status:14, created_time:"2023-08-13T18:15:53.451469569+00:00"}"
```

This time the case failed with milvus panic.
```
2023-08-14T02:17:36.98038884+08:00 stderr F panic: runtime error: invalid memory address or nil pointer dereference
2023-08-14T02:17:36.980428634+08:00 stderr F [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x3289a4a]
```
reproducing every day.

**Comment by aoiasd** [comment]
Find some gpc method return milvus err by rpc error(should return milvus error by response status), so rpc connection mark this connection invalid and reset connection, cause some rpc call at the same time run failed.

**Comment by aoiasd** [comment]
Will fix by congqi /assign @congqixia

**Comment by NicoYuan1986** [comment]
not reproduced for a week. 
c5a1b41
