### ISSUE TITLE
[Bug]: Query failed with error `all available nodes are unreachable: service unavailable` during test after first deployment stage with no chaos or reinstall

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#26300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230811-a0198ce8
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2023-08-11T09:54:17.053Z] 2023-08-11 09:54:15.964 | INFO     | MainThread |utils:load_and_search:206 - collection name: task_1_HNSW

[2023-08-11T09:54:17.053Z] 2023-08-11 09:54:15.964 | INFO     | MainThread |utils:load_and_search:207 - load collection

[2023-08-11T09:54:22.286Z] 2023-08-11 09:54:21.796 | INFO     | MainThread |utils:load_and_search:211 - load time: 5.8316

[2023-08-11T09:54:22.286Z] 2023-08-11 09:54:21.808 | INFO     | MainThread |utils:load_and_search:225 - {'metric_type': 'L2', 'params': {'ef': 64}}

[2023-08-11T09:54:22.286Z] 2023-08-11 09:54:21.808 | INFO     | MainThread |utils:load_and_search:228 - 

[2023-08-11T09:54:22.286Z] Search...

[2023-08-11T09:54:23.646Z] 2023-08-11 09:54:23.384 | INFO     | MainThread |utils:load_and_search:239 - hit: id: 849, distance: 31.33049774169922, entity: {'count': 849, 'random_value': -16.0}

[2023-08-11T09:54:23.646Z] 2023-08-11 09:54:23.385 | INFO     | MainThread |utils:load_and_search:239 - hit: id: 747, distance: 32.033451080322266, entity: {'count': 747, 'random_value': -19.0}

[2023-08-11T09:54:23.646Z] 2023-08-11 09:54:23.385 | INFO     | MainThread |utils:load_and_search:239 - hit: id: 1859, distance: 32.16548156738281, entity: {'count': 1859, 'random_value': -13.0}

[2023-08-11T09:54:23.646Z] 2023-08-11 09:54:23.385 | INFO     | MainThread |utils:load_and_search:239 - hit: id: 725, distance: 32.341758728027344, entity: {'count': 725, 'random_value': -20.0}

[2023-08-11T09:54:23.646Z] 2023-08-11 09:54:23.385 | INFO     | MainThread |utils:load_and_search:239 - hit: id: 1015, distance: 32.754817962646484, entity: {'count': 1015, 'random_value': -14.0}

[2023-08-11T09:54:23.646Z] 2023-08-11 09:54:23.385 | INFO     | MainThread |utils:load_and_search:242 - [849, 747, 1859, 725, 1015]

[2023-08-11T09:54:23.646Z] 2023-08-11 09:54:23.385 | INFO     | MainThread |utils:load_and_search:244 - search latency: 1.5767s

[2023-08-11T09:54:24.205Z] RPC error: [query], <MilvusException: (code=1, message=attempt #0: all available nodes are unreachable: service unavailable: attempt #1: all available nodes are unreachable: service unavailable: fail to query on all shard leaders)>, <Time:{'RPC start': '2023-08-11 09:54:23.385629', 'RPC error': '2023-08-11 09:54:24.093299'}>

[2023-08-11T09:54:24.205Z] Traceback (most recent call last):

[2023-08-11T09:54:24.205Z]   File "scripts/action_before_reinstall.py", line 47, in <module>

[2023-08-11T09:54:24.205Z]     task_1(data_size, host)

[2023-08-11T09:54:24.205Z]   File "scripts/action_before_reinstall.py", line 16, in task_1

[2023-08-11T09:54:24.205Z]     load_and_search(prefix)

[2023-08-11T09:54:24.205Z]   File "/home/jenkins/agent/workspace/tests/python_client/deploy/scripts/utils.py", line 251, in load_and_search

[2023-08-11T09:54:24.205Z]     res = c.query(expr, output_fields, timeout=120)

[2023-08-11T09:54:24.205Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 916, in query

[2023-08-11T09:54:24.205Z]     return conn.query(

[2023-08-11T09:54:24.205Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 127, in handler

[2023-08-11T09:54:24.205Z]     raise e from e

[2023-08-11T09:54:24.205Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 123, in handler

[2023-08-11T09:54:24.205Z]     return func(*args, **kwargs)

[2023-08-11T09:54:24.205Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 162, in handler

[2023-08-11T09:54:24.205Z]     return func(self, *args, **kwargs)

[2023-08-11T09:54:24.205Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 102, in handler

[2023-08-11T09:54:24.205Z]     raise e from e

[2023-08-11T09:54:24.205Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 68, in handler

[2023-08-11T09:54:24.205Z]     return func(*args, **kwargs)

[2023-08-11T09:54:24.205Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 1341, in query

[2023-08-11T09:54:24.205Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2023-08-11T09:54:24.205Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=attempt #0: all available nodes are unreachable: service unavailable: attempt #1: all available nodes are unreachable: service unavailable: fail to query on all shard leaders)>

script returned exit code
```

### Expected Behavior

no exception

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_cron/detail/deploy_test_cron/1135/pipeline
log:

[artifacts-rocksmq-standalone-reinstall-1135-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/12320531/artifacts-rocksmq-standalone-reinstall-1135-server-logs.1.tar.gz)
[artifacts-rocksmq-standalone-reinstall-1135-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/12320532/artifacts-rocksmq-standalone-reinstall-1135-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
Verifying whether it is a stable issue

**Comment by zhuwenxing** [comment]
>Verifying whether it is a stable issue

Not a stable reproduced issue
