### ISSUE TITLE
[Bug]: [rolling update]Mixcoord will restart one time after rolling update with error `panic: role rootcoord[nodeID: 0] is not serving, reason: sate code: Abnormal`

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#26333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230814-ae780e03
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/12268675/e3936df5-a5df-42cf-aaa3-8c6b4d98880f)

```
[2023/08/14 07:49:33.313 +00:00] [DEBUG] [sessionutil/session_util.go:240] ["Session connect to etcd success"]
[2023/08/14 07:49:33.313 +00:00] [INFO] [sessionutil/session_util.go:965] ["register ACTIVE querycoord"]
[2023/08/14 07:49:33.313 +00:00] [INFO] [sessionutil/session_util.go:1018] ["serverName: querycoord quit STANDBY mode, this node will become ACTIVE"]
[2023/08/14 07:49:33.313 +00:00] [INFO] [querycoordv2/server.go:184] ["QueryCoord switch from standby to active, activating"]
[2023/08/14 07:49:33.313 +00:00] [INFO] [querycoordv2/server.go:206] [QueryCoord] [State=Initializing]
[2023/08/14 07:49:33.313 +00:00] [INFO] [querycoordv2/server.go:210] ["query coordinator try to connect etcd success"]
[2023/08/14 07:49:33.315 +00:00] [INFO] [tso/tso.go:122] ["sync and save timestamp"] [last=2023/08/14 07:16:20.910 +00:00] [save=2023/08/14 07:49:36.314 +00:00] [next=2023/08/14 07:49:33.314 +00:00]
[2023/08/14 07:49:33.315 +00:00] [INFO] [querycoordv2/server.go:301] ["init meta"]
[2023/08/14 07:49:33.315 +00:00] [INFO] [querycoordv2/server.go:310] ["recover meta..."]
[2023/08/14 07:49:33.317 +00:00] [ERROR] [meta/coordinator_broker.go:89] ["failed to get collection schema"] [collectionID=443546960286450261] [error="role rootcoord[nodeID: 0] is not serving, reason: sate code: Abnormal"] [stack="github.com/milvus-io/milvus/internal/querycoordv2/meta.(*CoordinatorBroker).GetCollectionSchema\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/meta/coordinator_broker.go:89\ngithub.com/milvus-io/milvus/internal/querycoordv2/meta.(*CollectionManager).Recover\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/meta/collection_manager.go:128\ngithub.com/milvus-io/milvus/internal/querycoordv2.(*Server).initMeta\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/server.go:311\ngithub.com/milvus-io/milvus/internal/querycoordv2.(*Server).initQueryCoord\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/server.go:229\ngithub.com/milvus-io/milvus/internal/querycoordv2.(*Server).Init.func1\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/server.go:185\ngithub.com/milvus-io/milvus/internal/util/sessionutil.(*Session).ProcessActiveStandBy\n\t/go/src/github.com/milvus-io/milvus/internal/util/sessionutil/session_util.go:1020\ngithub.com/milvus-io/milvus/internal/querycoordv2.(*Server).Register\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/server.go:139\ngithub.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).start\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/service.go:247\ngithub.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/service.go:97\ngithub.com/milvus-io/milvus/cmd/components.(*QueryCoord).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/query_coord.go:53\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:112"]
[2023/08/14 07:49:33.317 +00:00] [ERROR] [querycoordv2/server.go:313] ["failed to recover collections"] [stack="github.com/milvus-io/milvus/internal/querycoordv2.(*Server).initMeta\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/server.go:313\ngithub.com/milvus-io/milvus/internal/querycoordv2.(*Server).initQueryCoord\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/server.go:229\ngithub.com/milvus-io/milvus/internal/querycoordv2.(*Server).Init.func1\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/server.go:185\ngithub.com/milvus-io/milvus/internal/util/sessionutil.(*Session).ProcessActiveStandBy\n\t/go/src/github.com/milvus-io/milvus/internal/util/sessionutil/session_util.go:1020\ngithub.com/milvus-io/milvus/internal/querycoordv2.(*Server).Register\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/server.go:139\ngithub.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).start\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/service.go:247\ngithub.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/service.go:97\ngithub.com/milvus-io/milvus/cmd/components.(*QueryCoord).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/query_coord.go:53\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:112"]
[2023/08/14 07:49:33.317 +00:00] [ERROR] [querycoordv2/server.go:186] ["QueryCoord init failed"] [error="role rootcoord[nodeID: 0] is not serving, reason: sate code: Abnormal"] [stack="github.com/milvus-io/milvus/internal/querycoordv2.(*Server).Init.func1\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/server.go:186\ngithub.com/milvus-io/milvus/internal/util/sessionutil.(*Session).ProcessActiveStandBy\n\t/go/src/github.com/milvus-io/milvus/internal/util/sessionutil/session_util.go:1020\ngithub.com/milvus-io/milvus/internal/querycoordv2.(*Server).Register\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/server.go:139\ngithub.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).start\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/service.go:247\ngithub.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/service.go:97\ngithub.com/milvus-io/milvus/cmd/components.(*QueryCoord).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/query_coord.go:53\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:112"]
[2023/08/14 07:49:33.317 +00:00] [ERROR] [querycoordv2/server.go:140] ["failed to activate standby server"] [error="role rootcoord[nodeID: 0] is not serving, reason: sate code: Abnormal"] [stack="github.com/milvus-io/milvus/internal/querycoordv2.(*Server).Register\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/server.go:140\ngithub.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).start\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/service.go:247\ngithub.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/service.go:97\ngithub.com/milvus-io/milvus/cmd/components.(*QueryCoord).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/query_coord.go:53\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:112"]
[2023/08/14 07:49:33.317 +00:00] [ERROR] [components/query_coord.go:54] ["QueryCoord starts error"] [error="role rootcoord[nodeID: 0] is not serving, reason: sate code: Abnormal"] [stack="github.com/milvus-io/milvus/cmd/components.(*QueryCoord).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/query_coord.go:54\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:112"]
panic: role rootcoord[nodeID: 0] is not serving, reason: sate code: Abnormal

goroutine 285 [running]:
panic({0x3c3d260, 0xc0012bad98})
	/usr/local/go/src/runtime/panic.go:941 +0x397 fp=0xc0016bdf58 sp=0xc0016bde98 pc=0x153b377
github.com/milvus-io/milvus/cmd/roles.runComponent[...].func1()
	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:113 +0x18c fp=0xc0016bdfe0 sp=0xc0016bdf58 pc=0x366e24c
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0016bdfe8 sp=0xc0016bdfe0 pc=0x15709e1
created by github.com/milvus-io/milvus/cmd/roles.runComponent[...]
	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:99 +0x151

goroutine 1 [semacquire]:
runtime.gopark(0x5c28130?, 0xc001425818?, 0x0?, 0x58?, 0x150eac5?)
	/usr/local/go/src/runtime/proc.go:361 +0xd6 fp=0xc001d87780 sp=0xc001d87760 pc=0x153e5d6
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:367
runtime.semacquire1(0xc00052ad48, 0x30?, 0x1, 0x0)
	/usr/local/go/src/runtime/sema.go:144 +0x1f3 fp=0xc001d877e8 sp=0xc001d87780 pc=0x154f753
sync.runtime_Semacquire(0x1539c1f?)
	/usr/local/go/src/runtime/sema.go:56 +0x25 fp=0xc001d87818 sp=0xc001d877e8 pc=0x156c5e5
sync.(*WaitGroup).Wait(0x3ef5a00?)
	/usr/local/go/src/sync/waitgroup.go:136 +0x52 fp=0xc001d87840 sp=0xc001d87818 pc=0x157f5d2
github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run(0xc001d87e48, 0x0, {0xc000f20b20?, 0xb?})
	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:340 +0x8fa fp=0xc001d87df8 sp=0xc001d87840 pc=0x366da5a
github.com/milvus-io/milvus/cmd/milvus.(*run).execute(0xc000f2ebd0, {0xc00004e070?, 0x7, 0x7}, 0xc0004048a0)
	/go/src/github.com/milvus-io/milvus/cmd/milvus/run.go:117 +0x6ae fp=0xc001d87ee0 sp=0xc001d87df8 pc=0x367a2ae
github.com/milvus-io/milvus/cmd/milvus.RunMilvus({0xc00004e070?, 0x7, 0x7})
	/go/src/github.com/milvus-io/milvus/cmd/milvus/milvus.go:60 +0x21e fp=0xc001d87f58 sp=0xc001d87ee0 pc=0x3679afe
main.main()
	/go/src/github.com/milvus-io/milvus/cmd/main.go:26 +0x2e fp=0xc001d87f80 sp=0xc001d87f58 pc=0x367c98e
runtime.main()
	/usr/local/go/src/runtime/proc.go:250 +0x212 fp=0xc001d87fe0 sp=0xc001d87f80 pc=0x153e212
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc001d87fe8 sp=0xc001d87fe0 pc=0x15709e1
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/rolling_update_for_operator_test/detail/rolling_update_for_operator_test/126/pipeline

log:
[artifacts-kafka-cluster-126-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/12332833/artifacts-kafka-cluster-126-pytest-logs.tar.gz)

[artifacts-kafka-cluster-126-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/12332835/artifacts-kafka-cluster-126-server-logs.1.tar.gz)

**Comment by zhuwenxing** [comment]
This made search, query and insert also has a low succ rate.
```

[2023-08-14T07:54:25.806Z] FAILED testcases/test_single_request_operation_for_rolling_update.py::TestOperations::test_operations - pytest_assume.plugin.FailedAssumption: 

[2023-08-14T07:54:25.806Z] 6 Failed Assumptions:

[2023-08-14T07:54:25.806Z] 

[2023-08-14T07:54:25.806Z] chaos_commons.py:112: AssumptionFailure

[2023-08-14T07:54:25.806Z] >>	pytest.assume(

[2023-08-14T07:54:25.806Z] AssertionError: Expect Succ: Op.insert succ rate 0.9703872437357631, total: 439, average time: 0.3923

[2023-08-14T07:54:25.806Z] assert False

[2023-08-14T07:54:25.806Z] 

[2023-08-14T07:54:25.806Z] chaos_commons.py:112: AssumptionFailure

[2023-08-14T07:54:25.806Z] >>	pytest.assume(

[2023-08-14T07:54:25.806Z] AssertionError: Expect Succ: Op.index succ rate 0.7910447761194029, total: 67, average time: 10.5081

[2023-08-14T07:54:25.806Z] assert False

[2023-08-14T07:54:25.806Z] 

[2023-08-14T07:54:25.806Z] chaos_commons.py:112: AssumptionFailure

[2023-08-14T07:54:25.806Z] >>	pytest.assume(

[2023-08-14T07:54:25.806Z] AssertionError: Expect Succ: Op.search succ rate 0.9256410256410257, total: 390, average time: 0.3787

[2023-08-14T07:54:25.806Z] assert False

[2023-08-14T07:54:25.807Z] 

[2023-08-14T07:54:25.807Z] chaos_commons.py:112: AssumptionFailure

[2023-08-14T07:54:25.807Z] >>	pytest.assume(

[2023-08-14T07:54:25.807Z] AssertionError: Expect Succ: Op.query succ rate 0.9581818181818181, total: 550, average time: 0.0677

[2023-08-14T07:54:25.807Z] assert False

[2023-08-14T07:54:25.807Z] 

[2023-08-14T07:54:25.807Z] testcases/test_single_request_operation_for_rolling_update.py:119: AssumptionFailure

[2023-08-14T07:54:25.807Z] >>	pytest.assume(rto < 30,  f"{k} rto expect 30s but get {rto}s")  # rto should be less than 30s

[2023-08-14T07:54:25.807Z] AssertionError: Op.search rto expect 30s but get 180.53367018699646s

[2023-08-14T07:54:25.807Z] assert False

[2023-08-14T07:54:25.807Z] 

[2023-08-14T07:54:25.807Z] testcases/test_single_request_operation_for_rolling_update.py:119: AssumptionFailure

[2023-08-14T07:54:25.807Z] >>	pytest.assume(rto < 30,  f"{k} rto expect 30s but get {rto}s")  # rto should be less than 30s

[2023-08-14T07:54:25.807Z] AssertionError: Op.query rto expect 30s but get 182.73539519309998s

[2023-08-14T07:54:25.807Z] assert False

[2023-08-14T07:54:25.807Z] =================== 1 failed, 1 warning in 992.43s (0:16:32) ===================
```

**Comment by weiliu1031** [comment]
during rolling upgrade progress, from old rc start to close until revoke it's session, which will cost `1s`, also from new rc start to register to be active and become healthy, which will cost `1s`.
 
which means during rolling upgrade, each coord will. become unavailable for `2s`.  to prevent the cross coord component's RPC failed, we need to add retry on all cross coord component's RPC

**Comment by xiaofan-luan** [comment]
> 

Let me figure this out, current implementation is not as expect

**Comment by xiaofan-luan** [comment]
1. we definitely retry
2. if retry failed, we will need to clean connection
3. we also need check serverID before we conenct to a server

**Comment by weiliu1031** [comment]
> 1. we definitely retry
> 2. if retry failed, we will need to clean connection
> 3. we also need check serverID before we connect to a server

for now, we just retry twice in grpc client, which won't go through the available period. we need a better retry poliy based component's state: if current rootcoord is unhealthy, we should retry until context done, rather than return err in a few ms

**Comment by yanliang567** [comment]
close for now, will file a new one if reproduce
