### ISSUE TITLE
[Bug]: [Nightly]Flush failed for timeout with lots of get_flush_state retries

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#26348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 7d61355
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0.dev115
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Flush failed for timeout with lots of get_flush_state retries.
```
[2023-08-14T19:28:11.165Z] [2023-08-14 18:12:22 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:4, cost: 0.27s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.165Z] [2023-08-14 18:12:23 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:5, cost: 0.81s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.165Z] [2023-08-14 18:12:23 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:6, cost: 2.43s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.165Z] [2023-08-14 18:12:26 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:7, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.165Z] [2023-08-14 18:12:29 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:8, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.165Z] [2023-08-14 18:12:32 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:9, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.165Z] [2023-08-14 18:12:35 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:10, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.165Z] [2023-08-14 18:12:38 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:11, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.165Z] [2023-08-14 18:12:41 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:12, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.165Z] [2023-08-14 18:12:44 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:13, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.165Z] [2023-08-14 18:12:47 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:14, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.165Z] [2023-08-14 18:12:50 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:15, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.165Z] [2023-08-14 18:12:53 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:16, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.165Z] [2023-08-14 18:12:56 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:17, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.165Z] [2023-08-14 18:12:59 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:18, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.165Z] [2023-08-14 18:13:02 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:19, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.165Z] [2023-08-14 18:13:05 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:20, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.165Z] [2023-08-14 18:13:08 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:21, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.165Z] [2023-08-14 18:13:11 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:22, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.165Z] [2023-08-14 18:13:14 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:23, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.165Z] [2023-08-14 18:13:17 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:24, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.165Z] [2023-08-14 18:13:20 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:25, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.165Z] [2023-08-14 18:13:23 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:26, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.166Z] [2023-08-14 18:13:26 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:27, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.166Z] [2023-08-14 18:13:29 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:28, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.166Z] [2023-08-14 18:13:32 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:29, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.166Z] [2023-08-14 18:13:35 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:30, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.166Z] [2023-08-14 18:13:38 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:31, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.166Z] [2023-08-14 18:13:41 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:32, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.166Z] [2023-08-14 18:13:44 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:33, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.166Z] [2023-08-14 18:13:47 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:34, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.166Z] [2023-08-14 18:13:50 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:35, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.166Z] [2023-08-14 18:13:53 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:36, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.166Z] [2023-08-14 18:13:56 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:37, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.166Z] [2023-08-14 18:13:59 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:38, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.166Z] [2023-08-14 18:14:02 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:39, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.166Z] [2023-08-14 18:14:05 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:40, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.166Z] [2023-08-14 18:14:08 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:41, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.166Z] [2023-08-14 18:14:11 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:42, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.166Z] [2023-08-14 18:14:14 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:43, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.166Z] [2023-08-14 18:14:17 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:44, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.166Z] [2023-08-14 18:14:20 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:45, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.166Z] [2023-08-14 18:14:23 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:46, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.166Z] [2023-08-14 18:14:26 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:47, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.166Z] [2023-08-14 18:14:29 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:48, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.166Z] [2023-08-14 18:14:32 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:49, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.166Z] [2023-08-14 18:14:35 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:50, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.166Z] [2023-08-14 18:14:38 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:51, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.166Z] [2023-08-14 18:14:41 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:52, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.166Z] [2023-08-14 18:14:44 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:53, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.166Z] [2023-08-14 18:14:47 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:54, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.166Z] [2023-08-14 18:14:50 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:55, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.167Z] [2023-08-14 18:14:53 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:56, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.167Z] [2023-08-14 18:14:56 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:57, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.167Z] [2023-08-14 18:14:59 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:58, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.167Z] [2023-08-14 18:15:02 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:59, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.167Z] [2023-08-14 18:15:05 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:60, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.167Z] [2023-08-14 18:15:08 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:61, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.167Z] [2023-08-14 18:15:11 - WARNING - pymilvus.decorators]: [93m[get_flush_state] retry:62, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.65.64:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-08-14T19:28:11.167Z] [2023-08-14 18:15:14 - WARNING - pymilvus.decorators]: [93mRetry timeout: 120s[0m (decorators.py:94)
[2023-08-14T19:28:11.167Z] [2023-08-14 18:15:14 - ERROR - pymilvus.decorators]: RPC error: [flush], <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for flush timeout, segment ids: [443557249886330073])>, <Time:{'RPC start': '2023-08-14 18:12:18.416841', 'RPC error': '2023-08-14 18:15:14.596548'}> (decorators.py:126)
[2023-08-14T19:28:11.167Z] [2023-08-14 18:15:14 - ERROR - ci_test]: Traceback (most recent call last):
[2023-08-14T19:28:11.167Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper
[2023-08-14T19:28:11.167Z]     res = func(*args, **_kwargs)
[2023-08-14T19:28:11.167Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request
[2023-08-14T19:28:11.167Z]     return func(*arg, **kwargs)
[2023-08-14T19:28:11.167Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 313, in flush
[2023-08-14T19:28:11.167Z]     conn.flush([self.name], timeout=timeout, **kwargs)
[2023-08-14T19:28:11.167Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 127, in handler
[2023-08-14T19:28:11.167Z]     raise e from e
[2023-08-14T19:28:11.167Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 123, in handler
[2023-08-14T19:28:11.167Z]     return func(*args, **kwargs)
[2023-08-14T19:28:11.167Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 162, in handler
[2023-08-14T19:28:11.167Z]     return func(self, *args, **kwargs)
[2023-08-14T19:28:11.167Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 95, in handler
[2023-08-14T19:28:11.167Z]     raise MilvusException(
[2023-08-14T19:28:11.167Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for flush timeout, segment ids: [443557249886330073])>
[2023-08-14T19:28:11.167Z]  (api_request.py:45)
[2023-08-14T19:28:11.167Z] [2023-08-14 18:15:14 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for flush timeout, segment ids: [443557249886330073])> (api_request.py:46)
```

### Expected Behavior

pass

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/466/pipeline/141
2. log: [artifacts-milvus-standalone-nightly-466-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/466/artifact/artifacts-milvus-standalone-nightly-466-pymilvus-e2e-logs.tar.gz)
3. collection name: query_uRsd0oHv
4. failed time: [2023-08-14T18:15:15.225Z] [gw5] [ 29%] FAILED testcases/test_query.py::TestQueryParams::test_query_pagination_with_insert_data[10]
5. milvus panic log:
```
2023-08-15T02:10:19.24991782+08:00 stderr F panic: runtime error: invalid memory address or nil pointer dereference
2023-08-15T02:10:19.249937908+08:00 stderr F [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x3289b2a]
2023-08-15T02:10:19.249942342+08:00 stderr F
2023-08-15T02:10:19.249946351+08:00 stderr F goroutine 473846 [running]:
2023-08-15T02:10:19.249959596+08:00 stderr F panic({0x3a7c380, 0x5abb2a0})
2023-08-15T02:10:19.249965877+08:00 stderr F    /usr/local/go/src/runtime/panic.go:941 +0x397 fp=0xc007576ab0 sp=0xc0075769f0 pc=0x153b377
2023-08-15T02:10:19.249970739+08:00 stderr F runtime.panicmem(...)
2023-08-15T02:10:19.249975352+08:00 stderr F    /usr/local/go/src/runtime/panic.go:220
2023-08-15T02:10:19.249979876+08:00 stderr F runtime.sigpanic()
```

**Comment by NicoYuan1986** [comment]
@jiaoew1991  Is it related to disk?

**Comment by jiaoew1991** [comment]
It looks like a Milvus panic.

**Comment by NicoYuan1986** [comment]
The flush hang issue has been fixed. not reproduced. master-20230816-95bcf3e9
