### ISSUE TITLE
[Bug]: Standalone panic when search with invalid expr from collection which has json and dynamic fields

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#26408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230816-8b549142
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): go-sdk master branch
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. create collection with json field and enable dynamic
Json field struct
```
	type JSONStruct struct {
		Number int32   `json:"number" milvus:"name:number"`
		String string  `json:"string" milvus:"name:string"`
		Bool   bool    `json:"bool" milvus:"name:bool"`
		List   []int64 `json:"list" milvus:"name:list"`
	}
```
3. insert data
4. index and load
5. search with invalid expr `json['list'] == [1, 2]`
6. standalone panic
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x3286caa]

goroutine 200064 [running]:
panic({0x3a7b120, 0x5ab92a0})
    /usr/local/go/src/runtime/panic.go:941 +0x397 fp=0xc0080caab0 sp=0xc0080ca9f0 pc=0x153a377
runtime.panicmem(...)
    /usr/local/go/src/runtime/panic.go:220
runtime.sigpanic()
```
- panic logs:
[standalone_2.log](https://github.com/milvus-io/milvus/files/12360101/standalone_2.log)

- go case
```
func TestSearchJsonFieldInvalidExpr(t *testing.T) {
	t.Parallel()

	// invalid expr and error message
	type invalidExprStruct struct {
		expr   string
		errMsg string
	}
	ctx := createContext(t, time.Second*common.DefaultTimeout)
	// connect
	mc := createMilvusClient(ctx, t)

	for _, dynamicField := range []bool{true} {
		// create collection
		cp := CollectionParams{
			CollectionFieldsType: Int64FloatVecJSON,
			AutoID:               false,
			EnableDynamicField:   dynamicField,
			ShardsNum:            common.DefaultShards,
			Dim:                  common.DefaultDim,
		}
		collName := createCollection(ctx, t, mc, cp)

		// insert
		dp := DataParams{
			CollectionName:       collName,
			PartitionName:        "",
			CollectionFieldsType: Int64FloatVecJSON,
			start:                0,
			nb:                   common.DefaultNb,
			dim:                  common.DefaultDim,
			EnableDynamicField:   dynamicField,
		}
		_, _ = insertData(ctx, t, mc, dp)

		idx, _ := entity.NewIndexHNSW(entity.L2, 8, 96)
		_ = mc.CreateIndex(ctx, collName, common.DefaultFloatVecFieldName, idx, false)

		// Load collection
		errLoad := mc.LoadCollection(ctx, collName, false)
		common.CheckErr(t, errLoad, true)

		// gen invalid json and dynamic expr
		invalidExpr := []invalidExprStruct{
			{expr: fmt.Sprintf("%s == 1", common.DefaultJSONFieldName), errMsg: "can not comparisons jsonField directly"},                            // json field filter
			{expr: fmt.Sprintf("%s['list'] == [1, 2]", common.DefaultJSONFieldName), errMsg: "failed to create query plan: cannot parse expression"}, // wrong term expr keyword
		}
		if dynamicField {
			invalidExpr = append(invalidExpr,
				invalidExprStruct{expr: fmt.Sprintf("%s == 1", common.DefaultDynamicFieldName), errMsg: "can not comparisons jsonField directly"},
				invalidExprStruct{expr: fmt.Sprintf("%s[\"dynamicList\"] == [2, 3]", common.DefaultDynamicFieldName), errMsg: "failed to create query plan: cannot parse expression"})
		}

		// search with invalid expr
		sp, _ := entity.NewIndexHNSWSearchParam(74)
		for _, exprStruct := range invalidExpr {
			_, errSearchEmpty := mc.Search(
				ctx, collName,
				[]string{},
				exprStruct.expr,
				[]string{common.DefaultIntFieldName},
				common.GenSearchVectors(common.DefaultNq, common.DefaultDim, entity.FieldTypeFloatVector),
				common.DefaultFloatVecFieldName,
				entity.L2,
				common.DefaultTopK,
				sp,
			)
			common.CheckErr(t, errSearchEmpty, false, exprStruct.errMsg)
		}
	}
}
```

### Steps To Reproduce

```markdown
run go case
```

**Comment by yanliang567** [comment]
@NicoYuan1986 does it reproduce if using pymilvus?

**Comment by xiaocai2333** [comment]
We don't support compare whether json_array is equal to an array, but it should not panic.

**Comment by xiaocai2333** [comment]
list is just supported for `json_contains` expr
such as:
`json_contains(json_array, [1,2,3])`
`json_contains_any(json_array, [1,2,3])`
`json_contains_any(json_array, [[1,2,3], [4,5,6]])`
`json_contains_all(json_array, [1,2,3])`
`json_contains_all(json_array, [[1,2,3], [4,5,6]])`

**Comment by xiaocai2333** [comment]
/assign @ThreadDao 
It's fixed. please check it with latest image.

**Comment by NicoYuan1986** [comment]
Forgot to comment. 
It will raise error using pymilvus when meeting the issue. And it does not panic.

**Comment by yanliang567** [comment]
> Forgot to comment. It will raise error using pymilvus when meeting the issue. And it does not panic.

so what is the error msg, does it meaningful and acceptable? @NicoYuan1986

**Comment by NicoYuan1986** [comment]
The error message:

pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=cannot parse expression: json['list'] == [1, 2], error: invalid expression, array is not supported for Equality)>

It is clear and acceptable.

milvus: master-20230906-78a2638f
pymilvus: 2.3.0

**Comment by ThreadDao** [comment]
@NicoYuan1986 @xiaocai2333 
image: master-20231007-5c1abfa2
support json['list'] == [1, 2]

**Comment by yanliang567** [comment]
close as comments above
