### ISSUE TITLE
[Bug]: [Nightly]The error message  is not user-friendly when diskann search failed using a out-of-range search_list

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#26419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230816-95bcf3e9
- Deployment mode(standalone or cluster): cluster && standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0.dev115
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Diskann search failed reporting 'out of range in json'.
```
[2023-08-16T19:39:21.006Z] [2023-08-16 18:29:13 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=attempt #0: fail to Search, QueryNode ID=6, reason=worker(6) query failed: UnexpectedError: Assert "failed to search: out of range in json: " at /go/src/github.com/milvus-io/milvus/internal/core/src/index/VectorDiskIndex.cpp:247: channel=by-dev-rootcoord-dml_14_443602361520731801v0: fail to search/query shard leader: attempt #1: no available shard delegator found: service unavailable: fail to search on all shard leaders)>, <Time:{'RPC start': '2023-08-16 18:29:12.992615', 'RPC error': '2023-08-16 18:29:13.942829'}> (decorators.py:126)
[2023-08-16T19:39:21.006Z] [2023-08-16 18:29:13 - ERROR - ci_test]: Traceback (most recent call last):
[2023-08-16T19:39:21.006Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper
[2023-08-16T19:39:21.006Z]     res = func(*args, **_kwargs)
[2023-08-16T19:39:21.006Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request
[2023-08-16T19:39:21.006Z]     return func(*arg, **kwargs)
[2023-08-16T19:39:21.006Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 778, in search
[2023-08-16T19:39:21.006Z]     res = conn.search(
[2023-08-16T19:39:21.006Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 127, in handler
[2023-08-16T19:39:21.006Z]     raise e from e
[2023-08-16T19:39:21.006Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 123, in handler
[2023-08-16T19:39:21.006Z]     return func(*args, **kwargs)
[2023-08-16T19:39:21.006Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 162, in handler
[2023-08-16T19:39:21.006Z]     return func(self, *args, **kwargs)
[2023-08-16T19:39:21.006Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 102, in handler
[2023-08-16T19:39:21.006Z]     raise e from e
[2023-08-16T19:39:21.006Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 68, in handler
[2023-08-16T19:39:21.006Z]     return func(*args, **kwargs)
[2023-08-16T19:39:21.006Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 766, in search
[2023-08-16T19:39:21.006Z]     return self._execute_search_requests(
[2023-08-16T19:39:21.006Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 727, in _execute_search_requests
[2023-08-16T19:39:21.006Z]     raise pre_err from pre_err
[2023-08-16T19:39:21.006Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 718, in _execute_search_requests
[2023-08-16T19:39:21.006Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2023-08-16T19:39:21.006Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=attempt #0: fail to Search, QueryNode ID=6, reason=worker(6) query failed: UnexpectedError: Assert "failed to search: out of range in json: " at /go/src/github.com/milvus-io/milvus/internal/core/src/index/VectorDiskIndex.cpp:247: channel=by-dev-rootcoord-dml_14_443602361520731801v0: fail to search/query shard leader: attempt #1: no available shard delegator found: service unavailable: fail to search on all shard leaders)>
[2023-08-16T19:39:21.006Z]  (api_request.py:45)
[2023-08-16T19:39:21.006Z] [2023-08-16 18:29:13 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=attempt #0: fail to Search, QueryNode ID=6, reason=worker(6) query failed: UnexpectedError: Assert "failed to search: out of range in json: " at /go/src/github.com/milvus-io/milvus/internal/core/src/index/VectorDiskIndex.cpp:247: channel=by-dev-rootcoord-dml_14_443...... (api_request.py:46)
```

### Expected Behavior

pass

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/468/pipeline/253/
2. log: [artifacts-milvus-distributed-pulsar-nightly-468-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/468/artifact/artifacts-milvus-distributed-pulsar-nightly-468-pymilvus-e2e-logs.tar.gz)
3. collection name: search_collection_4Fw1upB3
4. failed time: [2023-08-16T18:29:14.876Z] [gw3] [ 33%] FAILED testcases/test_search.py::TestCollectionSearch::test_search_after_different_index_with_params[128-True-False-True-DISKANN-params5]

**Comment by jiaoew1991** [comment]
<img width="671" alt="image" src="https://github.com/milvus-io/milvus/assets/2297455/ab267f20-1a8a-4154-be91-6adef75d65dc">

search_list == 1500 exceeds the range of diskann. The range of diskann is [topk, max(200, topk*10)], where topk == 10.

**Comment by yanliang567** [comment]
remove critical urgent.

**Comment by NicoYuan1986** [comment]
This is indeed the reason why case failed. Thanks for your help. @jiaoew1991 
I will modify the case then.

**Comment by NicoYuan1986** [comment]
But the error message is not user friendly. I did not catch the root cause when i first saw it.
advise to modify the error message from 
```
<MilvusException: (code=1, message=attempt #0: fail to Search, QueryNode ID=6, reason=worker(6) query failed: UnexpectedError: Assert "failed to search: out of range in json: " at /go/src/github.com/milvus-io/milvus/internal/core/src/index/VectorDiskIndex.cpp:247: channel=by-dev-rootcoord-dml_14_443...... (api_request.py:46)
```
to 
```
<MilvusException: (code=1, message=failed to search: search_list is out of range ..)
```

**Comment by jiaoew1991** [comment]
> But the error message is not user friendly. I did not catch the root cause when i first saw it. advise to modify the error message from
> 
> ```
> <MilvusException: (code=1, message=attempt #0: fail to Search, QueryNode ID=6, reason=worker(6) query failed: UnexpectedError: Assert "failed to search: out of range in json: " at /go/src/github.com/milvus-io/milvus/internal/core/src/index/VectorDiskIndex.cpp:247: channel=by-dev-rootcoord-dml_14_443...... (api_request.py:46)
> ```
> 
> to
> 
> ```
> <MilvusException: (code=1, message=failed to search: search_list is out of range ..)
> ```

Yes, currently, it is not very user friendly. I will try to find a way to improve it.

**Comment by jiaoew1991** [comment]
@yah01 

Please organize the error messages of segcore and knowhere.

**Comment by yah01** [comment]
/assign @NicoYuan1986 
should fixed by https://github.com/zilliztech/knowhere/pull/20

**Comment by NicoYuan1986** [comment]
error message at present:
```
[2023-09-26 15:40:51 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=65538, message=failed to search: attempt #0: failed to search/query delegator 1 for channel by-dev-rootcoord-dml_0_444520000779816256v0: fail to Search, QueryNode ID=1, reason=worker(1) query failed: UnknownError:  => failed to search: out of range in json: search_list_size should be in range: [topk, max(200, topk * 10)], topk = 10, search_list_size = 300: attempt #1: no available shard delegator found: service unavailable)>, <Time:{'RPC start': '2023-09-26 15:40:50.323883', 'RPC error': '2023-09-26 15:40:51.227544'}> (decorators.py:128)
[2023-09-26 15:40:51 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/zilliz/nico/milvus/tests/python_client/utils/api_request.py", line 32, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/Users/zilliz/nico/milvus/tests/python_client/utils/api_request.py", line 63, in api_request
    return func(*arg, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/orm/collection.py", line 778, in search
    res = conn.search(
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 129, in handler
    raise e from e
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 125, in handler
    return func(*args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 164, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 104, in handler
    raise e from e
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/decorators.py", line 68, in handler
    return func(*args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 788, in search
    return self._execute_search_requests(
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 749, in _execute_search_requests
    raise pre_err from pre_err
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 740, in _execute_search_requests
    raise MilvusException(response.status.code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=65538, message=failed to search: attempt #0: failed to search/query delegator 1 for channel by-dev-rootcoord-dml_0_444520000779816256v0: fail to Search, QueryNode ID=1, reason=worker(1) query failed: UnknownError:  => failed to search: out of range in json: search_list_size should be in range: [topk, max(200, topk * 10)], topk = 10, search_list_size = 300: attempt #1: no available shard delegator found: service unavailable)>
 (api_request.py:45)
[2023-09-26 15:40:51 - ERROR - ci_test]: (api_response) : <MilvusException: (code=65538, message=failed to search: attempt #0: failed to search/query delegator 1 for channel by-dev-rootcoord-dml_0_444520000779816256v0: fail to Search, QueryNode ID=1, reason=worker(1) query failed: UnknownError:  => failed to search: out of range in json: search_list_size s...... (api_request.py:46
```
