### ISSUE TITLE
[Bug]: [Nightly]Partition flush will fail for timeout sometimes

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#26485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: c5a1b41
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): kafka
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0.dev115
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Partition flush will fail for timeout sometimes.
```
[2023-08-19T20:49:08.452Z] [2023-08-19 18:32:37 - DEBUG - ci_test]: (api_request)  : [Partition.flush] args: [], kwargs: {'timeout': 20} (api_request.py:62)
[2023-08-19T20:49:08.452Z] [2023-08-19 18:32:57 - WARNING - pymilvus.decorators]: [93mRetry timeout: 20s[0m (decorators.py:94)
[2023-08-19T20:49:08.452Z] [2023-08-19 18:32:57 - ERROR - pymilvus.decorators]: RPC error: [flush], <MilvusException: (code=1, message=Retry timeout: 20s, message=wait for flush timeout, segment ids: [443670533582223316])>, <Time:{'RPC start': '2023-08-19 18:32:37.664760', 'RPC error': '2023-08-19 18:32:57.787238'}> (decorators.py:126)
[2023-08-19T20:49:08.452Z] [2023-08-19 18:32:57 - ERROR - ci_test]: Traceback (most recent call last):
[2023-08-19T20:49:08.452Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper
[2023-08-19T20:49:08.452Z]     res = func(*args, **_kwargs)
[2023-08-19T20:49:08.452Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request
[2023-08-19T20:49:08.452Z]     return func(*arg, **kwargs)
[2023-08-19T20:49:08.452Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/partition.py", line 155, in flush
[2023-08-19T20:49:08.452Z]     conn.flush([self._collection.name], timeout=timeout, **kwargs)
[2023-08-19T20:49:08.452Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 127, in handler
[2023-08-19T20:49:08.452Z]     raise e from e
[2023-08-19T20:49:08.452Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 123, in handler
[2023-08-19T20:49:08.452Z]     return func(*args, **kwargs)
[2023-08-19T20:49:08.452Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 162, in handler
[2023-08-19T20:49:08.452Z]     return func(self, *args, **kwargs)
[2023-08-19T20:49:08.452Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 95, in handler
[2023-08-19T20:49:08.452Z]     raise MilvusException(
[2023-08-19T20:49:08.452Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 20s, message=wait for flush timeout, segment ids: [443670533582223316])>
[2023-08-19T20:49:08.452Z]  (api_request.py:45)
[2023-08-19T20:49:08.452Z] [2023-08-19 18:32:57 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 20s, message=wait for flush timeout, segment ids: [443670533582223316])> (api_request.py:46)
```

### Expected Behavior

pass

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/470/pipeline/205
2. log: [artifacts-milvus-distributed-kafka-nightly-470-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/470/artifact/artifacts-milvus-distributed-kafka-nightly-470-pymilvus-e2e-logs.tar.gz)
3. collection name: coll__rwRygDuX
4. failed time: [2023-08-19T18:32:59.472Z] [gw0] [ 21%] FAILED testcases/test_partition.py::TestPartitionOperations::test_partition_insert_default_partition

**Comment by NicoYuan1986** [comment]
keep reproducing every day in kafka.

**Comment by NicoYuan1986** [comment]
Update: 

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/494/pipeline/205/
2. log: [artifacts-milvus-distributed-kafka-nightly-494-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/494/artifact/artifacts-milvus-distributed-kafka-nightly-494-pymilvus-e2e-logs.tar.gz)
3. collection name: index_ACJRHfg5
4. failed time: [2023-09-11T18:11:36.556Z] [gw5] [ 10%] FAILED testcases/test_index.py::TestNewIndexBase::test_create_index_no_vectors_insert_ip

**Comment by xiaofan-luan** [comment]
/assign @bigsheeper 
could you please help on it?

**Comment by bigsheeper** [comment]
DataCoord keep restarting for **6** times:
```
2023-09-12T02:14:35.505828926+08:00 stdout F [2023/09/11 18:14:35.505 +00:00] [INFO] [datacoord/indexnode_manager.go:134] ["peek client success"] [nodeID=2]
2023-09-12T02:14:35.505859045+08:00 stdout F [2023/09/11 18:14:35.505 +00:00] [WARN] [grpcclient/client.go:309] ["fail to get grpc client"] [client_role=indexnode] [error="failed to connect 10.105.1.199:21121, reason: context canceled"]
2023-09-12T02:14:35.506032817+08:00 stdout F [2023/09/11 18:14:35.505 +00:00] [INFO] [datacoord/indexnode_manager.go:147] ["peek client success"] [nodeID=2]
2023-09-12T02:14:35.506045507+08:00 stdout F [2023/09/11 18:14:35.506 +00:00] [DEBUG] [datacoord/index_meta.go:505] ["IndexCoord metaTable UpdateVersion receive"] [buildID=444191209635615653] [nodeID=2]
2023-09-12T02:14:35.508038035+08:00 stderr F panic: runtime error: invalid memory address or nil pointer dereference
2023-09-12T02:14:35.508053616+08:00 stderr F [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x33185e9]
2023-09-12T02:14:35.508057907+08:00 stderr F 
2023-09-12T02:14:35.508062127+08:00 stderr F goroutine 504 [running]:
2023-09-12T02:14:35.508073705+08:00 stderr F panic({0x3f73060, 0x6268450})
2023-09-12T02:14:35.508077709+08:00 stderr F 	/usr/local/go/src/runtime/panic.go:987 +0x3bb fp=0xc001b7fd38 sp=0xc001b7fc78 pc=0x169fbdb
2023-09-12T02:14:35.508081157+08:00 stderr F runtime.panicmem(...)
2023-09-12T02:14:35.508084869+08:00 stderr F 	/usr/local/go/src/runtime/panic.go:260
2023-09-12T02:14:35.508088455+08:00 stderr F runtime.sigpanic()
2023-09-12T02:14:35.508094951+08:00 stderr F 	/usr/local/go/src/runtime/signal_unix.go:841 +0x37d fp=0xc001b7fd98 sp=0xc001b7fd38 pc=0x16b7e1d
2023-09-12T02:14:35.508105869+08:00 stderr F github.com/milvus-io/milvus/internal/datacoord.(*IndexNodeManager).PeekClient.func1()
2023-09-12T02:14:35.508124383+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/datacoord/indexnode_manager.go:126 +0x2e9 fp=0xc001b7ffe0 sp=0xc001b7fd98 pc=0x33185e9
2023-09-12T02:14:35.508133961+08:00 stderr F runtime.goexit()
2023-09-12T02:14:35.508143105+08:00 stderr F 	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc001b7ffe8 sp=0xc001b7ffe0 pc=0x16d9921
2023-09-12T02:14:35.508152879+08:00 stderr F created by github.com/milvus-io/milvus/internal/datacoord.(*IndexNodeManager).PeekClient
2023-09-12T02:14:35.5081599+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/datacoord/indexnode_manager.go:119 +0x126
2023-09-12T02:14:35.508163426+08:00 stderr F 
2023-09-12T02:14:35.508171714+08:00 stderr F goroutine 1 [chan receive]:
2023-09-12T02:14:35.508196045+08:00 stderr F runtime.gopark(0xc00110e100?, 0xc001b25aa8?, 0x1e?, 0xf0?, 0x3f3ed40?)
2023-09-12T02:14:35.508212225+08:00 stderr F 	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc001b25a50 sp=0xc001b25a30 pc=0x16a3096
2023-09-12T02:14:35.508228134+08:00 stderr F runtime.chanrecv(0xc000200960, 0x0, 0x1)
2023-09-12T02:14:35.508245202+08:00 stderr F 	/usr/local/go/src/runtime/chan.go:583 +0x49d fp=0xc001b25ae0 sp=0xc001b25a50 pc=0x166b57d
2023-09-12T02:14:35.508259422+08:00 stderr F runtime.chanrecv1(0xc001059570?, 0x494d998?)
2023-09-12T02:14:35.50827261+08:00 stderr F 	/usr/local/go/src/runtime/chan.go:442 +0x18 fp=0xc001b25b08 sp=0xc001b25ae0 pc=0x166b078
2023-09-12T02:14:35.50829788+08:00 stderr F github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run(0xc00068c8a0, {0xc000224010?, 0xc00069a080?})
2023-09-12T02:14:35.508316963+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:380 +0x871 fp=0xc001b25df0 sp=0xc001b25b08 pc=0x3b33f51
2023-09-12T02:14:35.508340063+08:00 stderr F github.com/milvus-io/milvus/cmd/milvus.(*run).execute(0xc00068c0c0, {0xc000220060?, 0x3, 0x3}, 0xc000226600)
2023-09-12T02:14:35.508360177+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/cmd/milvus/run.go:111 +0x674 fp=0xc001b25ee0 sp=0xc001b25df0 pc=0x3b406b4
2023-09-12T02:14:35.508381941+08:00 stderr F github.com/milvus-io/milvus/cmd/milvus.RunMilvus({0xc000220060?, 0x3, 0x3})
2023-09-12T02:14:35.508414841+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/cmd/milvus/milvus.go:60 +0x21e fp=0xc001b25f58 sp=0xc001b25ee0 pc=0x3b3ff3e
2023-09-12T02:14:35.508437355+08:00 stderr F main.main()
2023-09-12T02:14:35.508448625+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/cmd/main.go:26 +0x2e fp=0xc001b25f80 sp=0xc001b25f58 pc=0x3b42f4e
2023-09-12T02:14:35.50845688+08:00 stderr F runtime.main()
2023-09-12T02:14:35.50846451+08:00 stderr F 	/usr/local/go/src/runtime/proc.go:250 +0x207 fp=0xc001b25fe0 sp=0xc001b25f80 pc=0x16a2c67
2023-09-12T02:14:35.508469696+08:00 stderr F runtime.goexit()
2023-09-12T02:14:35.508477861+08:00 stderr F 	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc001b25fe8 sp=0xc001b25fe0 pc=0x16d9921
2023-09-12T02:14:35.508484076+08:00 stderr F 
```

**Comment by bigsheeper** [comment]
Should be fixed by https://github.com/milvus-io/milvus/pull/27013

**Comment by bigsheeper** [comment]
after #27013 fix, still may panic at `resp.TaskSlots`, please help to fix it @xiaocai2333 , and make sure use GetXXX function rather than directly access to members.
![EXFn5UEfPe](https://github.com/milvus-io/milvus/assets/42060877/00e9541f-aaef-4c38-9653-46509078b0ea)

By the way, why resp and err are both nill. @xiaocai2333

**Comment by xiaocai2333** [comment]
It stands to reason that when error is nil, response or status cannot be nil. I noticed that the code of RpcCall has been changed recently. Please check whether there are related possible vulnerabilities. @SimFG 

I will check the code related to index, sort out the direct value and change it to `GetXXX`.

**Comment by NicoYuan1986** [comment]
fixed. 
master-20230921-67a471e0
