### ISSUE TITLE
[Bug]: Search failed with error `fail to get shard leaders from QueryCoord: collection=xxx: collection not loaded: unrecoverable error: fail to search on all shard leaders` after upgrading from v2.2.0 to master-20230818-74fb244b

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#26522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.2.0--> master-20230818-74fb244b
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2023-08-21T10:31:13.055Z] <name>: Checker__IhsMnlYN

[2023-08-21T10:31:13.055Z] <description>: 

[2023-08-21T10:31:13.055Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}......  (api_request.py:37)

[2023-08-21T10:31:13.055Z] [2023-08-21 10:04:35 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2023-08-21T10:31:13.055Z] [2023-08-21 10:04:36 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-08-21T10:31:13.055Z] [2023-08-21 10:04:36 - DEBUG - ci_test]: (api_request)  : [Collection.compact] args: [120], kwargs: {} (api_request.py:62)

[2023-08-21T10:31:13.055Z] [2023-08-21 10:04:36 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-08-21T10:31:13.055Z] [2023-08-21 10:10:44 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 120} (api_request.py:62)

[2023-08-21T10:31:13.055Z] [2023-08-21 10:10:44 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-08-21T10:31:13.055Z] [2023-08-21 10:10:44 - INFO - ci_test]: assert create collection: 0.22375154495239258, init_entities: 15915 (test_all_collections_after_chaos.py:49)

[2023-08-21T10:31:13.055Z] [2023-08-21 10:10:44 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [[[-3000, -2999, -2998, -2997, -2996, -2995, -2994, -2993, -2992, -2991, -2990, -2989, -2988, -2987, -2986, -2985, -2984, -2983, -2982, -2981, -2980, -2979, -2978, -2977, -2976, -2975, -2974, -2973, -2972, -2971, -2970, -2969, -2968, -2967, -2966, -2965, -2964, -2963, -2962, -2961, -2960, -2959, -29......, kwargs: {'timeout': 120} (api_request.py:62)

[2023-08-21T10:31:13.055Z] [2023-08-21 10:10:44 - DEBUG - ci_test]: (api_response) : (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 443708249188597764, success count: 2000, err count: 0)  (api_request.py:37)

[2023-08-21T10:31:13.055Z] [2023-08-21 10:10:44 - INFO - ci_test]: assert insert: 0.19503259658813477 (test_all_collections_after_chaos.py:61)

[2023-08-21T10:31:13.055Z] [2023-08-21 10:10:44 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2023-08-21T10:31:13.055Z] [2023-08-21 10:10:48 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-08-21T10:31:13.055Z] [2023-08-21 10:10:48 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 120} (api_request.py:62)

[2023-08-21T10:31:13.055Z] [2023-08-21 10:10:48 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-08-21T10:31:13.055Z] [2023-08-21 10:10:48 - INFO - ci_test]: assert flush: 3.5506527423858643, entities: 17915 (test_all_collections_after_chaos.py:71)

[2023-08-21T10:31:13.055Z] [2023-08-21 10:10:48 - INFO - ci_test]: index info: [{'collection': 'Checker__IhsMnlYN', 'field': 'float_vector', 'index_name': 'index__t4gCrX7W', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}] (test_all_collections_after_chaos.py:87)

[2023-08-21T10:31:13.055Z] [2023-08-21 10:10:48 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:62)

[2023-08-21T10:31:13.055Z] [2023-08-21 10:10:48 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-08-21T10:31:13.055Z] [2023-08-21 10:10:48 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.07649869616660752, 0.09149957881184916, 0.10660337414180021, 0.12939343634591782, 0.13889182146993986, 0.03351951321567684, 0.03375831432987895, 0.010577123529540614, 0.08533798515694191, 0.11391902531547995, 0.11147166374109792, 0.08193796136074015, 0.023126073032568792, 0.0972852428492824, 0......., kwargs: {} (api_request.py:62)

[2023-08-21T10:31:13.055Z] [2023-08-21 10:10:48 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=attempt #0: fail to get shard leaders from QueryCoord: collection=443707682170015291: collection not loaded: unrecoverable error: fail to search on all shard leaders)>, <Time:{'RPC start': '2023-08-21 10:10:48.498560', 'RPC error': '2023-08-21 10:10:48.501442'}> (decorators.py:126)

[2023-08-21T10:31:13.055Z] [2023-08-21 10:10:48 - ERROR - ci_test]: Traceback (most recent call last):

[2023-08-21T10:31:13.055Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2023-08-21T10:31:13.055Z]     res = func(*args, **_kwargs)

[2023-08-21T10:31:13.055Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2023-08-21T10:31:13.055Z]     return func(*arg, **kwargs)

[2023-08-21T10:31:13.055Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 778, in search

[2023-08-21T10:31:13.055Z]     res = conn.search(

[2023-08-21T10:31:13.055Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 127, in handler

[2023-08-21T10:31:13.055Z]     raise e from e

[2023-08-21T10:31:13.055Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 123, in handler

[2023-08-21T10:31:13.055Z]     return func(*args, **kwargs)

[2023-08-21T10:31:13.055Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 162, in handler

[2023-08-21T10:31:13.055Z]     return func(self, *args, **kwargs)

[2023-08-21T10:31:13.055Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 102, in handler

[2023-08-21T10:31:13.055Z]     raise e from e

[2023-08-21T10:31:13.055Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 68, in handler

[2023-08-21T10:31:13.055Z]     return func(*args, **kwargs)

[2023-08-21T10:31:13.055Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 766, in search

[2023-08-21T10:31:13.055Z]     return self._execute_search_requests(

[2023-08-21T10:31:13.055Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 727, in _execute_search_requests

[2023-08-21T10:31:13.055Z]     raise pre_err from pre_err

[2023-08-21T10:31:13.055Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 718, in _execute_search_requests

[2023-08-21T10:31:13.055Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2023-08-21T10:31:13.055Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=attempt #0: fail to get shard leaders from QueryCoord: collection=443707682170015291: collection not loaded: unrecoverable error: fail to search on all shard leaders)>

[2023-08-21T10:31:13.055Z]  (api_request.py:45)

[2023-08-21T10:31:13.055Z] [2023-08-21 10:10:48 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=attempt #0: fail to get shard leaders from QueryCoord: collection=443707682170015291: collection not loaded: unrecoverable error: fail to search on all shard leaders)> (api_request.py:46)
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_cron/detail/deploy_test_cron/1218/pipeline
log:
[artifacts-rocksmq-standalone-upgrade-1218-pytest-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/12404227/artifacts-rocksmq-standalone-upgrade-1218-pytest-logs.1.tar.gz)
[artifacts-rocksmq-standalone-upgrade-1218-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/12404229/artifacts-rocksmq-standalone-upgrade-1218-server-logs.1.tar.gz)

**Comment by yah01** [comment]
Same as #26519 
#26523 is fixing this

**Comment by yah01** [comment]
/assign @zhuwenxing 
help chech it as #26523 merged

**Comment by zhuwenxing** [comment]
However, it is also important to verify that all versions beyond v2.2.0 can work seamlessly with this updated image.

**Comment by zhuwenxing** [comment]
v2.2.0 --> master-20230822-bed034a4 : pass
v2.2.5 --> master-20230822-bed034a4 : pass
