### ISSUE TITLE
[Bug]: Second load timeout  after minio pod kill chaos test (load->search/query ->release->load)

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#26557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230822-e17cda23-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

load->search/query ->release->load

load failed at the second load

```
2023-08-22T21:49:36.716Z] <name>: SearchChecker__EBDqDere

[2023-08-22T21:49:36.716Z] <description>: 

[2023-08-22T21:49:36.716Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT......  (api_request.py:37)

[2023-08-22T21:49:36.716Z] [2023-08-22 21:46:52 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2023-08-22T21:49:36.716Z] [2023-08-22 21:46:52 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-08-22T21:49:36.716Z] [2023-08-22 21:46:52 - DEBUG - ci_test]: (api_request)  : [Collection.compact] args: [120], kwargs: {} (api_request.py:62)

[2023-08-22T21:49:36.716Z] [2023-08-22 21:46:52 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-08-22T21:49:36.716Z] [2023-08-22 21:47:03 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 120} (api_request.py:62)

[2023-08-22T21:49:36.717Z] [2023-08-22 21:47:03 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-08-22T21:49:36.717Z] [2023-08-22 21:47:03 - INFO - ci_test]: assert create collection: 0.01398777961730957, init_entities: 3000 (test_all_collections_after_chaos.py:49)

[2023-08-22T21:49:36.717Z] [2023-08-22 21:47:03 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [[[-3000, -2999, -2998, -2997, -2996, -2995, -2994, -2993, -2992, -2991, -2990, -2989, -2988, -2987, -2986, -2985, -2984, -2983, -2982, -2981, -2980, -2979, -2978, -2977, -2976, -2975, -2974, -2973, -2972, -2971, -2970, -2969, -2968, -2967, -2966, -2965, -2964, -2963, -2962, -2961, -2960, -2959, -29......, kwargs: {'timeout': 120} (api_request.py:62)

[2023-08-22T21:49:36.717Z] [2023-08-22 21:47:03 - DEBUG - ci_test]: (api_response) : (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 443741850475692033, success count: 2000, err count: 0)  (api_request.py:37)

[2023-08-22T21:49:36.717Z] [2023-08-22 21:47:03 - INFO - ci_test]: assert insert: 0.40020012855529785 (test_all_collections_after_chaos.py:61)

[2023-08-22T21:49:36.717Z] [2023-08-22 21:47:03 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2023-08-22T21:49:36.717Z] [2023-08-22 21:47:07 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-08-22T21:49:36.717Z] [2023-08-22 21:47:07 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 120} (api_request.py:62)

[2023-08-22T21:49:36.717Z] [2023-08-22 21:47:07 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-08-22T21:49:36.717Z] [2023-08-22 21:47:07 - INFO - ci_test]: assert flush: 3.7192797660827637, entities: 5000 (test_all_collections_after_chaos.py:71)

[2023-08-22T21:49:36.717Z] [2023-08-22 21:47:07 - INFO - ci_test]: index info: [{'collection': 'SearchChecker__EBDqDere', 'field': 'float_vector', 'index_name': 'index__znkq9EZg', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}] (test_all_collections_after_chaos.py:87)

[2023-08-22T21:49:36.717Z] [2023-08-22 21:47:07 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:62)

[2023-08-22T21:49:36.717Z] [2023-08-22 21:47:07 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-08-22T21:49:36.717Z] [2023-08-22 21:47:07 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.1343845383306262, 0.06067253497965713, 0.11595633735290434, 0.07997882955612276, 0.13615476900219287, 0.1292113810213237, 0.03077235490197127, 0.06140850784203321, 0.03787259613759504, 0.09720197168492818, 0.15836351337760401, 0.08422662314852229, 0.03440064729367448, 0.10330639499146772, 0.005......, kwargs: {} (api_request.py:62)

[2023-08-22T21:49:36.717Z] [2023-08-22 21:47:07 - DEBUG - ci_test]: (api_response) : ["['id: 2299, distance: 24.493846893310547, entity: {}']"]  (api_request.py:37)

[2023-08-22T21:49:36.717Z] [2023-08-22 21:47:07 - INFO - ci_test]: assert search: 0.2899503707885742 (test_all_collections_after_chaos.py:100)

[2023-08-22T21:49:36.717Z] [2023-08-22 21:47:07 - DEBUG - ci_test]: (api_request)  : [Collection.query] args: ['int64 in [-3000, -2999, -2998, -2997, -2996, -2995, -2994, -2993, -2992, -2991, -2990, -2989, -2988, -2987, -2986, -2985, -2984, -2983, -2982, -2981, -2980, -2979, -2978, -2977, -2976, -2975, -2974, -2973, -2972, -2971, -2970, -2969, -2968, -2967, -2966, -2965, -2964, -2963, -2962, -2961, -2960, -......, kwargs: {} (api_request.py:62)

[2023-08-22T21:49:36.717Z] [2023-08-22 21:47:08 - DEBUG - ci_test]: (api_response) : [{'int64': -3000}, {'int64': -2999}, {'int64': -2998}, {'int64': -2997}, {'int64': -2996}, {'int64': -2995}, {'int64': -2994}, {'int64': -2993}, {'int64': -2992}, {'int64': -2991}, {'int64': -2990}, {'int64': -2989}, {'int64': -2988}, {'int64': -2987}, {'int64': -2986}, {'int64': -2985}, {'int64': -......  (api_request.py:37)

[2023-08-22T21:49:36.717Z] [2023-08-22 21:47:08 - INFO - ci_test]: assert query result 2000: 0.23685097694396973 (test_all_collections_after_chaos.py:107)

[2023-08-22T21:49:36.717Z] [2023-08-22 21:47:08 - DEBUG - ci_test]: (api_request)  : [Collection.release] args: [], kwargs: {'timeout': 120} (api_request.py:62)

[2023-08-22T21:49:36.717Z] [2023-08-22 21:47:09 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-08-22T21:49:36.717Z] [2023-08-22 21:47:09 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [[[-204801864992107404, -6447752610705312361, 3992465783776104158, 1125074889911746569, -130613186597662049, -7548671622351683242, -4963739583001529049, 8216537731608994324, -6891055678246337368, -357652093939765311, 6420257705693299930, 7734857349813974543, -8692967204730001404, -412844896507640849......, kwargs: {'timeout': 120} (api_request.py:62)

[2023-08-22T21:49:36.717Z] [2023-08-22 21:47:09 - DEBUG - ci_test]: (api_response) : (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 443741851999797250, success count: 2000, err count: 0)  (api_request.py:37)

[2023-08-22T21:49:36.717Z] [2023-08-22 21:47:09 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:62)

[2023-08-22T21:49:36.717Z] [2023-08-22 21:49:10 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=wait for loading collection timeout, collection: SearchChecker__EBDqDere)>, <Time:{'RPC start': '2023-08-22 21:47:10.146549', 'RPC error': '2023-08-22 21:49:10.392775'}> (decorators.py:126)

[2023-08-22T21:49:36.717Z] [2023-08-22 21:49:10 - WARNING - pymilvus.decorators]: Retry timeout: 120s (decorators.py:94)

[2023-08-22T21:49:36.717Z] [2023-08-22 21:49:10 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: SearchChecker__EBDqDere)>, <Time:{'RPC start': '2023-08-22 21:47:09.642324', 'RPC error': '2023-08-22 21:49:10.393588'}> (decorators.py:126)

[2023-08-22T21:49:36.717Z] [2023-08-22 21:49:10 - ERROR - ci_test]: Traceback (most recent call last):

[2023-08-22T21:49:36.717Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2023-08-22T21:49:36.717Z]     res = func(*args, **_kwargs)

[2023-08-22T21:49:36.717Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2023-08-22T21:49:36.717Z]     return func(*arg, **kwargs)

[2023-08-22T21:49:36.717Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 418, in load

[2023-08-22T21:49:36.717Z]     conn.load_collection(

[2023-08-22T21:49:36.717Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 127, in handler

[2023-08-22T21:49:36.717Z]     raise e from e

[2023-08-22T21:49:36.717Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 123, in handler

[2023-08-22T21:49:36.717Z]     return func(*args, **kwargs)

[2023-08-22T21:49:36.717Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 162, in handler

[2023-08-22T21:49:36.717Z]     return func(self, *args, **kwargs)

[2023-08-22T21:49:36.717Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 95, in handler

[2023-08-22T21:49:36.717Z]     raise MilvusException(

[2023-08-22T21:49:36.717Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: SearchChecker__EBDqDere)>

[2023-08-22T21:49:36.717Z]  (api_request.py:45)

[2023-08-22T21:49:36.717Z] [2023-08-22 21:49:10 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: SearchChecker__EBDqDere)> (api_request.py:46)

[2023-08-22T21:49:36.717Z] ------------- generated html file: file:///tmp/ci_logs/report.html -------------

[2023-08-22T21:49:36.717Z] =========================== short test summary info ============================

[2023-08-22T21:49:36.717Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[SearchChecker__EBDqDere] - AssertionError


```

### Expected Behavior

all tests pass

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/6784/pipeline

log:
[artifacts-s3-pod-kill-6784-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/12414621/artifacts-s3-pod-kill-6784-server-logs.tar.gz)

[artifacts-s3-pod-kill-6784-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/12414623/artifacts-s3-pod-kill-6784-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
Not a stable issue. It passed after the second try
