### ISSUE TITLE
[Bug]: Milvus2.3, ListIndexedSegment crashes server

### ISSUE THREAD

**Issue by shanghaikid** [milvus-io/milvus#26588]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
```

### Current Behavior

```bash
[2023-08-23T12:59:07.833Z] Milvus-sdk-node debug: [DB:Data:GetFlushState] sending {"segmentIDs":[]}
[2023-08-23T12:59:07.852Z] Milvus-sdk-node debug: [DB:Data:GetFlushState] executed in 18ms, returns {"status":{"error_code":"Success","reason":"","code":0},"flushed":true}
[2023-08-23T12:59:07.853Z] Milvus-sdk-node debug: [DB:Data:ListIndexedSegment] sending {"collection_name":"collection_uz38qmmp","index_name":"collection_index"}
[2023-08-23T12:59:15.111Z] Milvus-sdk-node debug: [DB:Data:ListIndexedSegment] executed failed, status: {"code":14,"details":"Connection dropped","metadata":{}}, timeout set: 15000ms, retry after 60 ms.
[2023-08-23T12:59:15.813Z] Milvus-sdk-node debug: [DB:Data:ListIndexedSegment] executed failed, status: {"code":14,"details":"Connection dropped","metadata":{}}, timeout set: 15000ms, retry after 120 ms.
[2023-08-23T12:59:15.955Z] Milvus-sdk-node debug: [DB:Data:ListIndexedSegment] executed failed, status: {"code":14,"details":"Connection dropped","metadata":{}}, timeout set: 15000ms, retry after 240 ms.
[2023-08-23T12:59:15.956Z] Milvus-sdk-node debug: [DB:Data:ListIndexedSegment] retry run out of 3 times. {"code":14,"details":"No connection established","metadata":{}}
[2023-08-23T12:59:15.971Z] Milvus-sdk-node debug: [DB:Data:Search] sending {"collection_name":"collection_uz38qmmp","output_fields":["age","height","default_value","name","meta"],"nq":1,"dsl":"","dsl_type":1,"placeholder_group":{"type":"Buffer","data":[10,24,10,2,36,48,16,101,26,16,0,0,128,63,0,0,0,64,0,0,64,64,0,0,128,64]},"search_params":[{"key":"anns_field","value":"vector"},{"key":"topk","value":4},{"key":"offset","value":0},{"key":"metric_type","value":""},{"key":"params","value":"{}"},{"key":"ignore_growing","value":false}],"consistency_level":2}
[2023-08-23T12:59:15.975Z] Milvus-sdk-node debug: [DB:Data:Search] executed failed, status: {"code":14,"details":"No connection established","metadata":{}}, timeout set: 15000ms, retry after 60 ms.
[2023-08-23T12:59:16.037Z] Milvus-sdk-node debug: [DB:Data:Search] executed failed, status: {"code":14,"details":"No connection established","metadata":{}}, timeout set: 15000ms, retry after 120 ms.
[2023-08-23T12:59:16.159Z] Milvus-sdk-node debug: [DB:Data:Search] executed failed, status: {"code":14,"details":"No connection established","metadata":{}}, timeout set: 15000ms, retry after 240 ms.
[2023-08-23T12:59:16.161Z] Milvus-sdk-node debug: [DB:Data:Search] retry run out of 3 times. {"code":14,"details":"No connection established","metadata":{}}
```

### Steps To Reproduce

```markdown
1. create a collection
2. insert data
3. create index (IVF_FLAT)
4. load collection
5. flush
6. listIndexedSegment
```

### Milvus Log

```
2023-08-23 20:59:08 | runtime.gcBgMarkWorker()
-- | --
  |   | 2023-08-23 20:59:08 | /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc0005e4f50 sp=0xc0005e4f30 pc=0x1542096
  |   | 2023-08-23 20:59:08 | runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
  |   | 2023-08-23 20:59:08 | goroutine 63 [GC worker (idle), 3 minutes]:Show context
  |   | 2023-08-23 20:59:08 |  
  |   | 2023-08-23 20:59:08 | /usr/local/go/src/runtime/mgc.go:1199 +0x25
  |   | 2023-08-23 20:59:08 | created by runtime.gcBgMarkStartWorkers
  |   | 2023-08-23 20:59:08 | /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0006057e8 sp=0xc0006057e0 pc=0x1578301
  |   | 2023-08-23 20:59:08 | runtime.goexit()
  |   | 2023-08-23 20:59:08 | /usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0006057e0 sp=0xc000605750 pc=0x1521651
  |   | 2023-08-23 20:59:08 | runtime.gcBgMarkWorker()
  |   | 2023-08-23 20:59:08 | /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000605750 sp=0xc000605730 pc=0x1542096
  |   | 2023-08-23 20:59:08 | runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
  |   | 2023-08-23 20:59:08 | goroutine 100 [GC worker (idle), 3 minutes]:
  |   | 2023-08-23 20:59:08 |  
  |   | 2023-08-23 20:59:08 | /usr/local/go/src/runtime/mgc.go:1199 +0x25
  |   | 2023-08-23 20:59:08 | created by runtime.gcBgMarkStartWorkers
  |   | 2023-08-23 20:59:08 | /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000601fe8 sp=0xc000601fe0 pc=0x1578301
  |   | 2023-08-23 20:59:08 | runtime.goexit()
  |   | 2023-08-23 20:59:08 | /usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc000601fe0 sp=0xc000601f50 pc=0x1521651
  |   | 2023-08-23 20:59:08 | runtime.gcBgMarkWorker()
  |   | 2023-08-23 20:59:08 | /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000601f50 sp=0xc000601f30 pc=0x1542096
  |   | 2023-08-23 20:59:08 | runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
  |   | 2023-08-23 20:59:08 | goroutine 78 [GC worker (idle), 3 minutes]:
  |   | 2023-08-23 20:59:08 |  
  |   | 2023-08-23 20:59:08 | /usr/local/go/src/runtime/mgc.go:1199 +0x25

```

More logs here
https://grafana-4am.zilliz.cc/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bpod%3D%5C%22m23-node-sdk-wjoqj-milvus-standalone-6d5998f657-lsqj4%5C%22%7D%22,%22hide%22:true%7D,%7B%22refId%22:%22B%22,%22expr%22:%22%7Bpod%3D%5C%22m23-node-sdk-wjoqj-milvus-standalone-6d5998f657-lsqj4%5C%22%7D%7C~%5C%22%5C%22%22%7D%5D,%22range%22:%7B%22from%22:%221692795488000%22,%22to%22:%221692795549000%22%7D%7D

**Comment by congqixia** [comment]
@shanghaikid `ListIndexedSegment` along with `DescribeSegmentIndexData` is not implemented yet and shall not be invoked

**Comment by shanghaikid** [comment]
ok.
