### ISSUE TITLE
[Bug]: User despite have necessary permissions (grants) is hitting permission deny error

### ISSUE THREAD

**Issue by ganderaj** [milvus-io/milvus#26655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.11
- Deployment mode(standalone or cluster): Cluster on AWS EKS
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.15
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: NA
- GPU: None
- Others: Attu v2.2.8
```

### Current Behavior

Despite allowing grants on the Milvus User, operations exist with Permission Deny error messages. Behavior is consistent when used Attu Dashboard, PyMilvus API and langchain.Milvus.

We have tried purging every impacted user and role and recreating them but to no avail.
![MicrosoftTeams-image (4)](https://github.com/milvus-io/milvus/assets/41026744/f602c135-1722-42cd-b6b3-fe89aab5a185)
![MicrosoftTeams-image (5)](https://github.com/milvus-io/milvus/assets/41026744/8c09728e-2075-45b6-9b4c-43dc32b046b3)

### Expected Behavior

Performing Milvus operations using PyMilvus API or Attu should be in accordance with the grants allowed on the Milvus User who is executing the APIs or performing Operations.

Grants allowed to my impacted Milvus user:

<img width="1333" alt="grants" src="https://github.com/milvus-io/milvus/assets/41026744/74e6b347-3916-4976-a1b6-f077ef91eabd">

### Steps To Reproduce

```markdown
1. Allow any grant say ListDatabases to a Milvus user on a specific database of your choice.
2. Login to Attu or provide your credentials on PyMilvus to perform the same action. 

Expectation is you should be able to perform operation with no fail. But we are not.
```

### Milvus Log

[milvus_logs.tar.gz](https://github.com/milvus-io/milvus/files/12459590/milvus_logs.tar.gz)

### Anything else?

Assuming we have hit any limitation on # of users and roles, we have even purged other users to reduce the count which yielded no result.

**Comment by ganderaj** [comment]
@LoveEachDay / @xiaofan-luan

**Comment by yanliang567** [comment]
@ganderaj  in the screenshot above, we only see the privileges of root, but it seems that you are running with a milvus user named "svc_dataiku_dss". could you please list the role that bound to this user and list all the privileges of this role? we need to make sure that the user you are running do have create collection privilege.  more details please check here: https://milvus.io/docs/rbac.md#3-Grant-a-privilege-to-a-role

/assign @ganderaj 
/unassign

**Comment by ganderaj** [comment]
@yanliang567 

I think you got confused with Grantor name for user. I have used `root` user to grant permissions to the role (thereby to the user). The list of grants outlined in the screenshot corresponds to the role _"dte_ml_role"_ which 

Bottom of the snippet tells you the list of users who are assigned the said role. Obtained via `role.get_users()`.

Code used to get that info.

```
database_name = "dte_ml_platform"
role_name = "dte_ml_role"
role = Role(role_name)

print(f'Access for {role_name} on DB {database_name} \n{role.list_grants(db_name=database_name)}')
print(f'\nUsers who assume the role {role_name}:\n{role.get_users()}\n')
```

**Comment by yanliang567** [comment]
/assign @binbinlv 
could you please help to reproduce it in house? Is there a chance that it not working with milvusClient api?
/unassign

**Comment by binbinlv** [comment]
working on it.

**Comment by binbinlv** [comment]
Reproduced in milvus v2.2.11:
And the problem is only for milvusClient api, pymilvus API is working well.

Create new database "ds1", and grant CreateCollection to roleB (default dababase), and create new user "user2" and add "user2" to "roleB".
```
>>> role.grant("Global", "*", "CreateCollection")
>>> db.create_database("ds1")
>>> role.list_grants()
GrantInfo groups:
- GrantItem: <object:Global>, <object_name:*>, <db_name:default>, <role_name:roleB>, <grantor_name:root>, <privilege:CreateCollection>
>>>
>>> role.list_grants("ds1")
GrantInfo groups:
>>>
>>> utility.create_user(user="user2", password="Milvus")
>>> role.add_user("user2")
>>> utility.list_users(True)
UserInfo groups:
- UserItem: <username:root>, <roles:()>
- UserItem: <username:user2>, <roles:('roleB',)>
>>> role.name
'roleB'
>>> role.list_grants()
GrantInfo groups:
- GrantItem: <object:Global>, <object_name:*>, <db_name:default>, <role_name:roleB>, <grantor_name:root>, <privilege:CreateCollection>
>>> role.list_grants("ds1")
GrantInfo groups:
>>>
```
connect using "user2", and using pymilvus API, it success to create collection using "default" database with the createCollection privilege, and fails to create collection using "ds1" database without the createCollection privilege.
```
>>> connection = connections.connect(host="10.102.7.95", user="user2", password="Milvus")
>>> db.using_database("default")
>>> collection = Collection("test_search_collection_binbin_tmp_211_1", schema=schema)
>>>
>>> db.using_database("ds1")
>>> collection = Collection("test_search_collection_binbin_tmp_211_2", schema=schema)
grpc RpcError: [create_collection], <_MultiThreadedRendezvous: StatusCode.PERMISSION_DENIED, PrivilegeCreateCollection: permission deny>, <Time:{'RPC start': '2023-09-04 17:15:45.395128', 'gRPC error': '2023-09-04 17:15:45.480779'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 144, in __init__
    conn.create_collection(self._name, schema, **kwargs)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 141, in handler
    raise e from e
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 123, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 162, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 79, in handler
    raise e from e
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 68, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 290, in create_collection
    status = rf.result()
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/grpc/_channel.py", line 797, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.PERMISSION_DENIED
	details = "PrivilegeCreateCollection: permission deny"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:10.102.7.95:19530 {created_time:"2023-09-04T17:15:45.480403+08:00", grpc_status:7, grpc_message:"PrivilegeCreateCollection: permission deny"}"
>
>>>
```
using milvusClient api, it fails to create collection using default db with createCollection priviledge.
```
>>> client = MilvusClient(uri="http://10.102.7.95:19530", user="user2", password="Milvus", db_name="default")
>>> db.using_database("default")
>>> client.create_collection(collection_name, dimension=128)
grpc RpcError: [create_index], <_MultiThreadedRendezvous: StatusCode.PERMISSION_DENIED, PrivilegeCreateIndex: permission deny>, <Time:{'RPC start': '2023-09-04 17:18:47.145150', 'gRPC error': '2023-09-04 17:18:47.278190'}>
Failed to create an index on collection: col_211_1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 119, in create_collection
    self._create_index(collection_name, vector_field_name, index_params, timeout=timeout)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 147, in _create_index
    raise ex from ex
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 132, in _create_index
    conn.create_index(
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 141, in handler
    raise e from e
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 123, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 162, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 79, in handler
    raise e from e
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 68, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 769, in create_index
    status = future.result()
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/grpc/_channel.py", line 797, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.PERMISSION_DENIED
	details = "PrivilegeCreateIndex: permission deny"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:10.102.7.95:19530 {created_time:"2023-09-04T17:18:47.277862+08:00", grpc_status:7, grpc_message:"PrivilegeCreateIndex: permission deny"}"
>
```

**Comment by binbinlv** [comment]
Using milvus v2.2.14, the issue still exists:
milvus log:https://grafana-4am.zilliz.cc/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcluster%3D%5C%22devops%5C%22,namespace%3D%5C%22chaos-testing%5C%22,pod%3D~%5C%22role-grant-comof.*%5C%22%7D%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D

```
>>> connection = connections.connect(host="", user="root", password="Milvus")
>>>
>>>
>>> utility.create_user("user3", "Milvus")
>>>
>>> utility.list_users(True)
UserInfo groups:
- UserItem: <username:root>, <roles:()>
- UserItem: <username:user3>, <roles:()>
>>>
>>>
>>> role_name = "roleC"
>>> role = Role(role_name)
>>>
>>> role.create()
>>>
>>> role.grant("Global", "*", "CreateCollection")
>>>
>>> role.list_grants()
GrantInfo groups:
- GrantItem: <object:Global>, <object_name:*>, <db_name:default>, <role_name:roleC>, <grantor_name:root>, <privilege:CreateCollection>
>>>
>>> db.create_database("db3")
>>> role.list_grants("db3")
GrantInfo groups:
>>>
>>>
>>> role.add_user("user3")
>>> utility.list_roles(True)
RoleInfo groups:
- RoleItem: <role_name:admin>, <users:()>
- RoleItem: <role_name:public>, <users:()>
- RoleItem: <role_name:roleC>, <users:('user3',)>
>>>
>>> role.list_grants()
GrantInfo groups:
- GrantItem: <object:Global>, <object_name:*>, <db_name:default>, <role_name:roleC>, <grantor_name:root>, <privilege:CreateCollection>
>>> role.list_grants("db3")
GrantInfo groups:
>>>
>>> role.name
'roleC'
>>>
>>> connections.disconnect("default")
>>> client = MilvusClient(uri="http://:19530", user="user3", password="Milvus", db_name="default")
>>>
>>>
>>> collection_name = "coll2141"
>>> client.create_collection(collection_name, dimension=128)
grpc RpcError: [create_index], <_MultiThreadedRendezvous: StatusCode.PERMISSION_DENIED, PrivilegeCreateIndex: permission deny>, <Time:{'RPC start': '2023-09-04 17:45:41.754899', 'gRPC error': '2023-09-04 17:45:41.859535'}>
Failed to create an index on collection: coll2141
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 119, in create_collection
    self._create_index(collection_name, vector_field_name, index_params, timeout=timeout)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 147, in _create_index
    raise ex from ex
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 132, in _create_index
    conn.create_index(
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 141, in handler
    raise e from e
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 123, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 162, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 79, in handler
    raise e from e
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/decorators.py", line 68, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 769, in create_index
    status = future.result()
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/grpc/_channel.py", line 797, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.PERMISSION_DENIED
	details = "PrivilegeCreateIndex: permission deny"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:10.102.9.151:19530 {grpc_message:"PrivilegeCreateIndex: permission deny", grpc_status:7, created_time:"2023-09-04T17:45:41.858987+08:00"}"
>
```

**Comment by binbinlv** [comment]
And when I add the following privilege, the collection is created successfully, but I think it is not expected. As the doc https://milvus.io/docs/users_and_roles.md, create collection should not has relationship to other privilege class?
```
>>> role.grant("Collection", "*", "*")
```
![image](https://github.com/milvus-io/milvus/assets/83755740/8a34c8c4-2b14-492a-96dc-b2f212f78f66)


Code:

```
>>> connection = connections.connect(host="", user="root", password="Milvus")
>>> utility.list_collections()
['coll2141']
>>>
>>> utility.list_roles(True)
RoleInfo groups:
- RoleItem: <role_name:admin>, <users:()>
- RoleItem: <role_name:public>, <users:()>
- RoleItem: <role_name:roleC>, <users:('user3',)>
>>>
>>> role=Role("roleC")
>>> role.name
'roleC'
>>> role.list_grants()
GrantInfo groups:
- GrantItem: <object:Global>, <object_name:*>, <db_name:default>, <role_name:roleC>, <grantor_name:root>, <privilege:CreateCollection>
>>>
>>> role.list_grants("db3")
GrantInfo groups:
>>>
>>> role.grant("Collection", "*", "*")
>>> role.grant("Collection", "*", "*", "db3")
>>>
>>> role.list_grants()
GrantInfo groups:
- GrantItem: <object:Collection>, <object_name:*>, <db_name:default>, <role_name:roleC>, <grantor_name:root>, <privilege:*>
- GrantItem: <object:Global>, <object_name:*>, <db_name:default>, <role_name:roleC>, <grantor_name:root>, <privilege:CreateCollection>
>>>
>>> role.list_grants("db3")
GrantInfo groups:
- GrantItem: <object:Collection>, <object_name:*>, <db_name:db3>, <role_name:roleC>, <grantor_name:root>, <privilege:*>
>>>
>>>
>>> role.grant("Collection", "*", "Search")
>>> role.grant("Collection", "*", "Search", "db3")
>>> role.list_grants()
GrantInfo groups:
- GrantItem: <object:Collection>, <object_name:*>, <db_name:default>, <role_name:roleC>, <grantor_name:root>, <privilege:*>
- GrantItem: <object:Collection>, <object_name:*>, <db_name:default>, <role_name:roleC>, <grantor_name:root>, <privilege:Search>
- GrantItem: <object:Global>, <object_name:*>, <db_name:default>, <role_name:roleC>, <grantor_name:root>, <privilege:CreateCollection>
>>> role.list_grants("db3")
GrantInfo groups:
- GrantItem: <object:Collection>, <object_name:*>, <db_name:db3>, <role_name:roleC>, <grantor_name:root>, <privilege:*>
- GrantItem: <object:Collection>, <object_name:*>, <db_name:db3>, <role_name:roleC>, <grantor_name:root>, <privilege:Search>
>>>
>>>
>>> client = MilvusClient(uri="http://10.102.9.151:19530", user="user3", password="Milvus", db_name="default")
>>> collection_name = "coll21465"
>>> client.create_collection(collection_name, dimension=128)
```

**Comment by ganderaj** [comment]
Team,

We appear to hit the issue again on a different Milvus environment. 
- `Milvus: v2.2.11`
- `PyMilvus: v2.2.15`

We are hittings the below error message while Listing Databases among others despite having enough permissions granted to the user. Refer to the snippet below for more info on the grants.

`grpc RpcError: [list_database], <_InactiveRpcError: StatusCode.PERMISSION_DENIED, PrivilegeListDatabases: permission deny>, <Time:{'RPC start': '2023-09-14 02:25:32.943359', 'gRPC error': '2023-09-14 02:25:32.961143'}>`

<img width="1310" alt="user_grants" src="https://github.com/milvus-io/milvus/assets/41026744/5c9888fe-3e86-4b9b-a2fa-99c76770a89d">

**Comment by yanliang567** [comment]
@jaime0815 could you please double check whether it is fixed in milvus 2.3
