### ISSUE TITLE
[Bug]: Milvus is restarted when concurrent searching with expression filtering varchar field 

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#26662]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230828-905d4b38
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.3.0
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Milvus is restarted when concurrent searching with expression filtering varchar field 
'expr': "varchar_1 == '1'",

```
[2023-08-29 03:01:27,242] - WARNING: ^[[93m[search] retry:4, cost: 0.27s, reason: <_InactiveRpcError: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.102.7.108:19530: Failed to connect to remote host: Connection refused>^[[0m (decorators.py:88)

 ...

[2023-08-29 03:02:38,832] - ERROR: RPC error: [search], <MilvusException: (code=1, message=attempt #0: fail to get shard leaders from QueryCoord: collection=443864428257466430: collection not loaded: unrecoverable error: fail to search on all shard leaders)>, <Time:{'RPC start': '2023-08-29 03:01:39.769054', 'RPC error': '2023-08-29 03:02:38.831965'}> (decorators.py:126)

...

[2023-08-29 03:04:56,915] - WARNING: ^[[93m[search] retry:10, cost: 3.00s, reason: <_InactiveRpcError: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.102.7.108:19530: Failed to connect to remote host: Connection refused>^[[0m (decorators.py:88)
```
binbin@binbindeMacBook-Pro ~ % kubectl get pods |grep range-search-ptrnw
range-search-ptrnw-etcd-0                                       1/1     Running       0               19h
range-search-ptrnw-milvus-standalone-6d97649466-gr7l6           1/1     Running       9 (22m ago)     19h
range-search-ptrnw-minio-746dbdd6d6-6xrcp                       1/1     Running       0               19h

### Expected Behavior

No restarted and concurrent search successfully

### Steps To Reproduce

```markdown
1. create collection  (dim=768)
2. create index (HNSW)
3. load
4. insert (1M)
5. flush
6. compact
7. concurrent search （expression：varchar == "1") (Concurrency：10)
```

### Milvus Log

log:

https://grafana-4am.zilliz.cc/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcluster%3D%5C%22devops%5C%22,namespace%3D%5C%22chaos-testing%5C%22,pod%3D~%5C%22range-search-ptrnw.*%5C%22%7D%22%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D

granfana:
https://grafana-devops.zilliz.cc/d/uLf5cJ3Gzx/milvus2-0?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=chaos-testing&var-instance=range-search-ptrnw&var-collection=All&var-app_name=milvus&from=now-1h&to=now

### Anything else?

1. collection: fouram_ouDGJHWn
2. dataset: laion 1m-768d
3. search parameter:
{'database_params': {'metric_type': 'L2', 'dim': 768, 'max_length': 256},
 'insert_params': {},
 'connection_params': {'secure': False},
 'collection_params': {'collection_name': 'fouram_ouDGJHWn'},
 'index_params': {},
 'load_params': {},
 'search_params': {},
 'concurrent_params': {'concurrent_number': 10,
                       'during_time': 600,
                       'warm_time': 0,
                       'interval': 20},
 'concurrent_tasks': [{'type': 'search',
                       'weight': 1,
                       'params': {'nq': 1,
                                  'top_k': 10,
                                  'search_param': {'ef': 360},
                                  'expr': "varchar_1 == '1'",
                                  'timeout': 60}}]}

**Comment by binbinlv** [comment]
Do more trials:
1. concurrent search (10) with expr: int == 1: no problem
2. serial search with expr: varchar_1 == '1': no problem

**Comment by jiaoew1991** [comment]
From the logs, it seems that the collection has not been loaded yet. @binbinlv, can you please double-check the test code? Was it loaded before performing the search?

**Comment by binbinlv** [comment]
Yes, it was loaded.

>>> utility.loading_progress("fouram_ouDGJHWn")
{'loading_progress': '100%'}

**Comment by binbinlv** [comment]
Actually, I saw the not load error too, so I ever run load again.
But it was still crashed again when I run the concurrent search using varchar expression.

Just as I pasted in the "Current Behaviour" part, it reported not connected first, and then report collection not loaded, then not connected ...

```
[2023-08-29 03:01:27,242] - WARNING: ^[[93m[search] retry:4, cost: 0.27s, reason: <_InactiveRpcError: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.102.7.108:19530: Failed to connect to remote host: Connection refused>^[[0m (decorators.py:88)

 ...

[2023-08-29 03:02:38,832] - ERROR: RPC error: [search], <MilvusException: (code=1, message=attempt #0: fail to get shard leaders from QueryCoord: collection=443864428257466430: collection not loaded: unrecoverable error: fail to search on all shard leaders)>, <Time:{'RPC start': '2023-08-29 03:01:39.769054', 'RPC error': '2023-08-29 03:02:38.831965'}> (decorators.py:126)

...

[2023-08-29 03:04:56,915] - WARNING: ^[[93m[search] retry:10, cost: 3.00s, reason: <_InactiveRpcError: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.102.7.108:19530: Failed to connect to remote host: Connection refused>^[[0m (decorators.py:88)
```

**Comment by binbinlv** [comment]
And it searched successfully at the very beginning, it should only report "not loaded" when searching if the collection not loaded rather than milvus restarted.

**Comment by jiaoew1991** [comment]
I got it, it panic by an error 
```
panic: runtime error: slice bounds out of range [1:0]
goroutine 17054390 [running]:
panic({0x3dab720, 0xc005cb8cc0})
	/usr/local/go/src/runtime/panic.go:987 +0x3bb fp=0xc005fd6b58 sp=0xc005fd6a98 pc=0x153fb5b
runtime.goPanicSliceB(0x1, 0x0)
	/usr/local/go/src/runtime/panic.go:153 +0x7f fp=0xc005fd6b98 sp=0xc005fd6b58 pc=0x153dc5f
github.com/milvus-io/milvus/internal/parser/planparserv2.(*ParserVisitor).VisitString(0x44f93c0?, 0x44b5010?)
	/go/src/github.com/milvus-io/milvus/internal/parser/planparserv2/parser_visitor.go:135 +0x25f fp=0xc005fd6c20 sp=0xc005fd6b98 pc=0x334ac7f
github.com/milvus-io/milvus/internal/parser/planparserv2/generated.(*StringContext).Accept(0xc001d536e0?, {0x44b5010?, 0xc00283a8b0})
	/go/src/github.com/milvus-io/milvus/internal/parser/planparserv2/generated/plan_parser.go:321 +0x9d fp=0xc005fd6c68 sp=0xc005fd6c20 pc=0x32d8e7d
github.com/milvus-io/milvus/internal/parser/planparserv2.(*ParserVisitor).VisitEquality(0xc00283a8b0?, 0xc001d536e0)
	/go/src/github.com/milvus-io/milvus/internal/parser/planparserv2/parser_visitor.go:326 +0xc2 fp=0xc005fd6d00 sp=0xc005fd6c68 pc=0x334be62
github.com/milvus-io/milvus/internal/parser/planparserv2/generated.(*EqualityContext).Accept(0xc00193b2d8?, {0x44b5010?, 0xc00283a8b0})
	/go/src/github.com/milvus-io/milvus/internal/parser/planparserv2/generated/plan_parser.go:728 +0x9a fp=0xc005fd6d48 sp=0xc005fd6d00 pc=0x32db73a
github.com/milvus-io/milvus/internal/parser/planparserv2.handleExpr(0xc0032efd70, {0xc00514c3f0, 0x10})
	/go/src/github.com/milvus-io/milvus/internal/parser/planparserv2/plan_parser_v2.go:51 +0x4b4 fp=0xc005fd6e28 sp=0xc005fd6d48 pc=0x3352294
github.com/milvus-io/milvus/internal/parser/planparserv2.ParseExpr(0xc0035ed490?, {0xc00514c3f0, 0x10})
	/go/src/github.com/milvus-io/milvus/internal/parser/planparserv2/plan_parser_v2.go:55 +0x3b fp=0xc005fd6eb8 sp=0xc005fd6e28 pc=0x335231b
github.com/milvus-io/milvus/internal/parser/planparserv2.CreateSearchPlan.func1(...)
	/go/src/github.com/milvus-io/milvus/internal/parser/planparserv2/plan_parser_v2.go:121
github.com/milvus-io/milvus/internal/parser/planparserv2.CreateSearchPlan(0xc00313a540?, {0xc00514c3f0, 0x10}, {0xc00514c460, 0xc}, 0xc00300b860)
	/go/src/github.com/milvus-io/milvus/internal/parser/planparserv2/plan_parser_v2.go:124 +0x86 fp=0xc005fd7048 sp=0xc005fd6eb8 pc=0x3352946
github.com/milvus-io/milvus/internal/proxy.(*searchTask).PreExecute(0xc003138240, {0x44b39c0, 0xc0032efc80})
	/go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:300 +0x2148 fp=0xc005fd7d60 sp=0xc005fd7048 pc=0x340baa8
github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask(0xc0019f6340?, {0x44e09b0, 0xc003138240}, {0x44cdc98, 0xc00044dba8})
	/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:445 +0x283 fp=0xc005fd7fa8 sp=0xc005fd7d60 pc=0x3407083
github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).queryLoop.func2()
	/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:515 +0x36 fp=0xc005fd7fe0 sp=0xc005fd7fa8 pc=0x3407f96
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc005fd7fe8 sp=0xc005fd7fe0 pc=0x1578e21
created by github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).queryLoop
	/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:515 +0x1e5

```

**Comment by longjiquan** [comment]
I think #24848 caused this issue. @xiaocai2333 can you help to solve this?
/assign @xiaocai2333

**Comment by binbinlv** [comment]
Verified and fixed:
no panic now.

milvus: master-20230831-82b0e39a
