### ISSUE TITLE
[Bug]: Rootcoord and datacoord will panic when apply pod failure chaos to etcd followers

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#26849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230905-4b58c719-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/12268675/79fc0398-60aa-46da-b691-23f96f3d8a79)

```
[2023/09/05 05:11:12.622 +00:00] [INFO] [datacoord/services.go:760] ["get recovery info request received"] [traceID=13c8e68720817f1b3b95a19c36034ae7] [collectionID=444043193134426912] [partitionIDs="[]"]
[2023/09/05 05:11:12.727 +00:00] [WARN] [datacoord/services.go:1415] ["failed to report dataNode ttMsgs on closed server"] [traceID=49fd19cf8aa075f5a2531c10acaf1a5b]
[2023/09/05 05:11:12.729 +00:00] [WARN] [datacoord/services.go:1415] ["failed to report dataNode ttMsgs on closed server"] [traceID=dfa0e87c6f34b2de171fb8df572edcec]
[2023/09/05 05:11:13.267 +00:00] [WARN] [sessionutil/session_util.go:492] ["fail to retry keepAliveOnce"] [serverName=indexcoord] [leaseID=3023756360760382022] [error="attempt #0: context deadline exceeded: attempt #1: etcdserver: requested lease not found: attempt #2: etcdserver: requested lease not found"]
[2023/09/05 05:11:13.267 +00:00] [WARN] [roles/roles.go:267] ["Get signal to exit"] [signal=interrupt]
[2023/09/05 05:11:13.268 +00:00] [INFO] [components/index_coord.go:45] ["IndexCoord stopping ..."]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x362c354]

goroutine 6952 [running]:
panic({0x3a30c00, 0x59f22d0})
	/usr/local/go/src/runtime/panic.go:987 +0x3bb fp=0xc000e44710 sp=0xc000e44650 pc=0x1505bdb
runtime.panicmem(...)
	/usr/local/go/src/runtime/panic.go:260
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:841 +0x37d fp=0xc000e44770 sp=0xc000e44710 pc=0x151de1d
github.com/milvus-io/milvus/cmd/components.(*RootCoord).Stop(0x3e89c34?)
	/go/src/github.com/milvus-io/milvus/cmd/components/root_coord.go:61 +0x14 fp=0xc000e44788 sp=0xc000e44770 pc=0x362c354
github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run.func1({0x4348208?, 0x0?})
	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:382 +0x66 fp=0xc000e447c0 sp=0xc000e44788 pc=0x3630966
github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run.func3()
	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:383 +0x2e fp=0xc000e447e0 sp=0xc000e447c0 pc=0x36308ce
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000e447e8 sp=0xc000e447e0 pc=0x153f521
created by github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run
	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:380 +0x99f

```

```
[2023/09/05 05:09:54.609 +00:00] [INFO] [rootcoord/root_coord.go:1130] ["done to describe collection"] [traceID=3799c2698f2e080ad8cb191ab7d066b4] [collectionName=] [dbName=] [id=444043193134426912] [ts=18446744073709551615] [allowUnavailable=true] [collection_id=444043193134426912]
[2023/09/05 05:09:54.610 +00:00] [INFO] [rootcoord/root_coord.go:1101] ["received request to describe collection"] [traceID=75989e93aca6db9e45611c61126889c2] [collectionName=] [dbName=] [id=444043193134426912] [ts=18446744073709551615] [allowUnavailable=false]
[2023/09/05 05:09:54.610 +00:00] [INFO] [rootcoord/root_coord.go:1130] ["done to describe collection"] [traceID=75989e93aca6db9e45611c61126889c2] [collectionName=] [dbName=] [id=444043193134426912] [ts=18446744073709551615] [allowUnavailable=false] [collection_id=444043193134426912]
[2023/09/05 05:10:02.034 +00:00] [ERROR] [rootcoord/proxy_manager.go:127] ["re watch proxy fails when etcd has a compaction error"] ["etcd error"="etcdserver: mvcc: required revision has been compacted"] [error="proxy manager failed to watch proxy with error context deadline exceeded"] [stack="github.com/milvus-io/milvus/internal/rootcoord.(*proxyManager).startWatchEtcd\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/proxy_manager.go:127\ngithub.com/milvus-io/milvus/internal/rootcoord.(*proxyManager).WatchProxy.func1\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/proxy_manager.go:104\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75"]
{"level":"warn","ts":"2023-09-05T05:10:02.034Z","logger":"etcd-client","caller":"v3@v3.5.5/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000d268c0/etcd-followers-pod-failure-7180:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
panic: failed to handle etcd request, exit..

goroutine 882 [running]:
panic({0x38e5d20, 0x431c800})
	/usr/local/go/src/runtime/panic.go:987 +0x3bb fp=0xc001239b20 sp=0xc001239a60 pc=0x1505bdb
github.com/milvus-io/milvus/internal/rootcoord.(*proxyManager).startWatchEtcd(0xc0003f6420?, {0x4346bb8, 0xc001aabea0}, 0xc00128e660)
	/go/src/github.com/milvus-io/milvus/internal/rootcoord/proxy_manager.go:129 +0x3e6 fp=0xc001239f48 sp=0xc001239b20 pc=0x35e1b06
github.com/milvus-io/milvus/internal/rootcoord.(*proxyManager).WatchProxy.func1()
	/go/src/github.com/milvus-io/milvus/internal/rootcoord/proxy_manager.go:104 +0x28 fp=0xc001239f78 sp=0xc001239f48 pc=0x35e16e8
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64 fp=0xc001239fe0 sp=0xc001239f78 pc=0x2389184
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc001239fe8 sp=0xc001239fe0 pc=0x153f521
created by golang.org/x/sync/errgroup.(*Group).Go
	/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5

```

### Expected Behavior

When the etcd's leader is up and running, the milvus component should be up and running as well!

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/7180/pipeline

log:
[artifacts-etcd-followers-pod-failure-7180-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/12519778/artifacts-etcd-followers-pod-failure-7180-pytest-logs.tar.gz)

[artifacts-etcd-followers-pod-failure-7180-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/12519784/artifacts-etcd-followers-pod-failure-7180-server-logs.1.tar.gz)

### Anything else?

Error in client:
```

[2023-09-05T05:11:16.297Z] [2023-09-05 05:11:09 - ERROR - pymilvus.decorators]: RPC error: [get_index_state], <MilvusException: (code=1, message=syncTimestamp Failed:context deadline exceeded)>, <Time:{'RPC start': '2023-09-05 05:10:02.585390', 'RPC error': '2023-09-05 05:11:09.620114'}> (decorators.py:126)

[2023-09-05T05:11:16.297Z] [2023-09-05 05:11:09 - ERROR - pymilvus.decorators]: RPC error: [wait_for_creating_index], <MilvusException: (code=1, message=syncTimestamp Failed:context deadline exceeded)>, <Time:{'RPC start': '2023-09-05 05:09:42.707972', 'RPC error': '2023-09-05 05:11:09.620589'}> (decorators.py:126)

[2023-09-05T05:11:16.298Z] [2023-09-05 05:11:09 - ERROR - pymilvus.decorators]: RPC error: [create_index], <MilvusException: (code=1, message=syncTimestamp Failed:context deadline exceeded)>, <Time:{'RPC start': '2023-09-05 05:09:42.699063', 'RPC error': '2023-09-05 05:11:09.620769'}> (decorators.py:126)

[2023-09-05T05:11:16.298Z] [2023-09-05 05:11:09 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=syncTimestamp Failed:err: rpc error: code = Unknown desc = expectedNodeID=5, actualNodeID=0: node not match

[2023-09-05T05:11:16.298Z] , /go/src/github.com/milvus-io/milvus/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace

[2023-09-05T05:11:16.298Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:405 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall

[2023-09-05T05:11:16.298Z] /go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/client/client.go:120 github.com/milvus-io/milvus/internal/distributed/rootcoord/client.wrapGrpcCall[...]

[2023-09-05T05:11:16.298Z] /go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/client/client.go:321 github.com/milvus-io/milvus/internal/distributed/rootcoord/client.(*Client).AllocTimestamp

[2023-09-05T05:11:16.298Z] /go/src/github.com/milvus-io/milvus/internal/proxy/timestamp.go:61 github.com/milvus-io/milvus/internal/proxy.(*timestampAllocator).alloc

[2023-09-05T05:11:16.298Z] /go/src/github.com/milvus-io/milvus/internal/proxy/timestamp.go:83 github.com/milvus-io/milvus/internal/proxy.(*timestampAllocator).AllocOne

[2023-09-05T05:11:16.298Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:170 github.com/milvus-io/milvus/internal/proxy.(*baseTaskQueue).Enqueue

[2023-09-05T05:11:16.298Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:348 github.com/milvus-io/milvus/internal/proxy.(*ddTaskQueue).Enqueue

[2023-09-05T05:11:16.298Z] /go/src/github.com/milvus-io/milvus/internal/proxy/impl.go:509 github.com/milvus-io/milvus/internal/proxy.(*Proxy).LoadCollection

[2023-09-05T05:11:16.298Z] /go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:715 github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).LoadCollection

[2023-09-05T05:11:16.298Z] )>, <Time:{'RPC start': '2023-09-05 05:11:09.621121', 'RPC error': '2023-09-05 05:11:09.626385'}> (decorators.py:126)

[2023-09-05T05:11:16.298Z] [2023-09-05 05:11:09 - ERROR - ci_test]: Traceback (most recent call last):

[2023-09-05T05:11:16.298Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2023-09-05T05:11:16.298Z]     res = func(*args, **_kwargs)

[2023-09-05T05:11:16.298Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2023-09-05T05:11:16.298Z]     return func(*arg, **kwargs)

[2023-09-05T05:11:16.298Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 419, in load

[2023-09-05T05:11:16.298Z]     conn.load_collection(

[2023-09-05T05:11:16.298Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 127, in handler

[2023-09-05T05:11:16.298Z]     raise e from e

[2023-09-05T05:11:16.298Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 123, in handler

[2023-09-05T05:11:16.298Z]     return func(*args, **kwargs)

[2023-09-05T05:11:16.298Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 162, in handler

[2023-09-05T05:11:16.298Z]     return func(self, *args, **kwargs)

[2023-09-05T05:11:16.298Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 102, in handler

[2023-09-05T05:11:16.298Z]     raise e from e

[2023-09-05T05:11:16.298Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 68, in handler

[2023-09-05T05:11:16.298Z]     return func(*args, **kwargs)

[2023-09-05T05:11:16.298Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 1020, in load_collection

[2023-09-05T05:11:16.298Z]     raise MilvusException(response.error_code, response.reason)

[2023-09-05T05:11:16.298Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=syncTimestamp Failed:err: rpc error: code = Unknown desc = expectedNodeID=5, actualNodeID=0: node not match

[2023-09-05T05:11:16.298Z] , /go/src/github.com/milvus-io/milvus/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace

[2023-09-05T05:11:16.298Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:405 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall

[2023-09-05T05:11:16.298Z] /go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/client/client.go:120 github.com/milvus-io/milvus/internal/distributed/rootcoord/client.wrapGrpcCall[...]

[2023-09-05T05:11:16.298Z] /go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/client/client.go:321 github.com/milvus-io/milvus/internal/distributed/rootcoord/client.(*Client).AllocTimestamp

[2023-09-05T05:11:16.298Z] /go/src/github.com/milvus-io/milvus/internal/proxy/timestamp.go:61 github.com/milvus-io/milvus/internal/proxy.(*timestampAllocator).alloc

[2023-09-05T05:11:16.298Z] /go/src/github.com/milvus-io/milvus/internal/proxy/timestamp.go:83 github.com/milvus-io/milvus/internal/proxy.(*timestampAllocator).AllocOne

[2023-09-05T05:11:16.298Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:170 github.com/milvus-io/milvus/internal/proxy.(*baseTaskQueue).Enqueue

[2023-09-05T05:11:16.298Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:348 github.com/milvus-io/milvus/internal/proxy.(*ddTaskQueue).Enqueue

[2023-09-05T05:11:16.298Z] /go/src/github.com/milvus-io/milvus/internal/proxy/impl.go:509 github.com/milvus-io/milvus/internal/proxy.(*Proxy).LoadCollection

[2023-09-05T05:11:16.298Z] /go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:715 github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).LoadCollection

[2023-09-05T05:11:16.298Z] )>

[2023-09-05T05:11:16.298Z]  (api_request.py:45)

[2023-09-05T05:11:16.298Z] [2023-09-05 05:11:09 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=syncTimestamp Failed:err: rpc error: code = Unknown desc = expectedNodeID=5, actualNodeID=0: node not match

[2023-09-05T05:11:16.298Z] , /go/src/github.com/milvus-io/milvus/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace

[2023-09-05T05:11:16.298Z] /go/src/github.com/milvus-io/milvus/inte...... (api_request.py:46)
```

**Comment by weiliu1031** [comment]
except the panic, after we kill the etcd follower, something unexpected happened:
1. etcd operation become much more slower, which cost more than 10s.
2. session keep alive channel is closed.
3. retry session keep alive, but meet context deadline due to slow etcd operation

**Comment by zhuwenxing** [comment]
If we only inject pod failure chaos to one follower, no components will be restarted.
![image](https://github.com/milvus-io/milvus/assets/12268675/330e3e0a-8dfd-412d-994a-6b077906e22c)
