### ISSUE TITLE
[Bug]: "there is no IndexNode available or etcd is not serviceable, wait a minute..."

### ISSUE THREAD

**Issue by kyoungrok0517** [milvus-io/milvus#26860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): ?
- SDK version(e.g. pymilvus v2.0.0rc2): v2.3.0
- OS(Ubuntu or CentOS): Red Hat Enterprise Linux release 8.8 (Ootpa)
- CPU/Memory: 48 / 128GB
- GPU: NA
- Others:
```

### Current Behavior

Trying to run `hello_milvus.py`, but sees the following error

```
❯ python hello_milvus.py

=== start connecting to Milvus     ===

Does collection hello_milvus exist in Milvus: True

=== Create collection `hello_milvus` ===


=== Start inserting entities       ===

Number of entities in Milvus: 9000

=== Start Creating index IVF_FLAT  ===

RPC error: [create_index], <MilvusException: (code=1, message=444052140311908046: canceled;)>, <Time:{'RPC start': '2023-09-05 23:40:57.182725', 'RPC error': '2023-09-05 23:40:57.687686'}>
Traceback (most recent call last):
  File "/home1/irteamsu/workspace/code/milvus/hello_milvus.py", line 95, in <module>
    hello_milvus.create_index("embeddings", index, timeout=300)
  File "/home1/irteamsu/miniforge3/envs/milvus/lib/python3.11/site-packages/pymilvus/orm/collection.py", line 1208, in create_index
    return conn.create_index(self._name, field_name, index_params, timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/irteamsu/miniforge3/envs/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 127, in handler
    raise e from e
  File "/home1/irteamsu/miniforge3/envs/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 123, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home1/irteamsu/miniforge3/envs/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 162, in handler
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/irteamsu/miniforge3/envs/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 102, in handler
    raise e from e
  File "/home1/irteamsu/miniforge3/envs/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 68, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home1/irteamsu/miniforge3/envs/milvus/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 886, in create_index
    raise MilvusException(message=fail_reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=444052140311908046: canceled;)>
```

The docker log shows like this

```
[2023/09/05 14:47:00.578 +00:00] [INFO] [datacoord/index_builder.go:180] ["index builder task schedule"] ["task num"=2]
[2023/09/05 14:47:00.578 +00:00] [INFO] [indexnode/indexnode_service.go:228] ["Get Index Job Stats"] [traceID=3d5ee3ab7961ae985b36a1b7bdacc44b] [Unissued=0] [Active=1] [Slot=0]
[2023/09/05 14:47:00.578 +00:00] [INFO] [datacoord/index_builder.go:188] ["there is no IndexNode available or etcd is not serviceable, wait a minute..."]
[2023/09/05 14:47:01.579 +00:00] [INFO] [datacoord/index_builder.go:180] ["index builder task schedule"] ["task num"=2]
[2023/09/05 14:47:01.579 +00:00] [INFO] [indexnode/indexnode_service.go:228] ["Get Index Job Stats"] [traceID=219a270aa9aea05bdfe480612fa17f0f] [Unissued=0] [Active=1] [Slot=0]
[2023/09/05 14:47:01.579 +00:00] [INFO] [datacoord/index_builder.go:188] ["there is no IndexNode available or etcd is not serviceable, wait a minute..."]
[2023/09/05 14:47:02.579 +00:00] [INFO] [datacoord/index_builder.go:180] ["index builder task schedule"] ["task num"=2]
[2023/09/05 14:47:02.579 +00:00] [INFO] [indexnode/indexnode_service.go:228] ["Get Index Job Stats"] [traceID=2df4bd56944fda71c3eb74382d3b3d57] [Unissued=0] [Active=1] [Slot=0]
[2023/09/05 14:47:02.579 +00:00] [INFO] [datacoord/index_builder.go:188] ["there is no IndexNode available or etcd is not serviceable, wait a minute..."]
[2023/09/05 14:47:03.579 +00:00] [INFO] [datacoord/index_builder.go:180] ["index builder task schedule"] ["task num"=2]
[2023/09/05 14:47:03.579 +00:00] [INFO] [indexnode/indexnode_service.go:228] ["Get Index Job Stats"] [traceID=f3fd470afb7917f31d9e44595bab1dd6] [Unissued=0] [Active=1] [Slot=0]
[2023/09/05 14:47:03.579 +00:00] [INFO] [datacoord/index_builder.go:251] ["index builder peek client error, there is no available"]
[2023/09/05 14:47:03.579 +00:00] [INFO] [datacoord/index_builder.go:188] ["there is no IndexNode available or etcd is not serviceable, wait a minute..."]
[2023/09/05 14:47:04.578 +00:00] [INFO] [datacoord/index_builder.go:180] ["index builder task schedule"] ["task num"=2]
[2023/09/05 14:47:04.578 +00:00] [INFO] [indexnode/indexnode_service.go:228] ["Get Index Job Stats"] [traceID=2b7bc9e14ede4c26847d27169dda57f3] [Unissued=0] [Active=1] [Slot=0]
[2023/09/05 14:47:04.579 +00:00] [INFO] [datacoord/index_builder.go:188] ["there is no IndexNode available or etcd is not serviceable, wait a minute..."]
[2023/09/05 14:47:05.578 +00:00] [INFO] [datacoord/index_builder.go:180] ["index builder task schedule"] ["task num"=2]
[2023/09/05 14:47:05.579 +00:00] [INFO] [indexnode/indexnode_service.go:228] ["Get Index Job Stats"] [traceID=0fe03fb8928fba3520c11005a990e6c0] [Unissued=0] [Active=1] [Slot=0]
[2023/09/05 14:47:05.579 +00:00] [INFO] [datacoord/index_builder.go:188] ["there is no IndexNode available or etcd is not serviceable, wait a minute..."]
[2023/09/05 14:47:05.974 +00:00] [INFO] [proxy/meta_cache.go:904] ["expire all shard leader cache"] [database=default] [collections="[hello_milvus]"]
[2023/09/05 14:47:06.578 +00:00] [INFO] [datacoord/index_builder.go:180] ["index builder task schedule"] ["task num"=2]
[2023/09/05 14:47:06.579 +00:00] [INFO] [indexnode/indexnode_service.go:228] ["Get Index Job Stats"] [traceID=598a315273143a5f5d7268be30f9a61d] [Unissued=0] [Active=1] [Slot=0]
[2023/09/05 14:47:06.579 +00:00] [INFO] [datacoord/index_builder.go:188] ["there is no IndexNode available or etcd is not serviceable, wait a minute..."]
[2023/09/05 14:47:07.578 +00:00] [INFO] [datacoord/index_builder.go:180] ["index builder task schedule"] ["task num"=2]
[2023/09/05 14:47:07.579 +00:00] [INFO] [indexnode/indexnode_service.go:228] ["Get Index Job Stats"] [traceID=f441a90cc2ec7977bd327dff53d3dc2e] [Unissued=0] [Active=1] [Slot=0]
[2023/09/05 14:47:07.579 +00:00] [INFO] [datacoord/index_builder.go:188] ["there is no IndexNode available or etcd is not serviceable, wait a minute..."]
[2023/09/05 14:47:08.579 +00:00] [INFO] [datacoord/index_builder.go:180] ["index builder task schedule"] ["task num"=2]
[2023/09/05 14:47:08.579 +00:00] [INFO] [indexnode/indexnode_service.go:228] ["Get Index Job Stats"] [traceID=6bb99eb872d5d560656db3d9e8f0e2dc] [Unissued=0] [Active=1] [Slot=0]
[2023/09/05 14:47:08.579 +00:00] [INFO] [datacoord/index_builder.go:251] ["index builder peek client error, there is no available"]
[2023/09/05 14:47:08.579 +00:00] [INFO] [datacoord/index_builder.go:188] ["there is no IndexNode available or etcd is not serviceable, wait a minute..."]
[2023/09/05 14:47:08.595 +00:00] [INFO] [indexnode/task.go:322] ["index params are ready"] [buildID=444052215049362502] ["index params"="{\"dim\":\"8\",\"index_type\":\"IVF_FLAT\",\"metric_type\":\"L2\",\"nlist\":\"128\"}"]
[2023/09/05 14:47:09.557 +00:00] [INFO] [rootcoord/quota_center.go:416] ["QueryNodeMetrics when cool-off"] [metrics="{\"2\":{\"Hms\":{\"ip\":\"172.27.0.4:21123\",\"cpu_core_count\":48,\"cpu_core_usage\":0,\"memory\":134533251072,\"memory_usage\":123338752,\"disk\":104857600,\"disk_usage\":2097152},\"Rms\":[{\"Label\":\"NQPerSecond\",\"Rate\":0},{\"Label\":\"Sear
chThroughput\",\"Rate\":0},{\"Label\":\"InsertConsumeThroughput\",\"Rate\":0},{\"Label\":\"DeleteConsumeThroughput\",\"Rate\":0}],\"Fgm\":{\"MinFlowGraphChannel\":\"\",\"MinFlowGraphTt\":18446744073709551615,\"NumFlowGraph\":0},\"SearchQueue\":{\"UnsolvedQueue\":0,\"ReadyQueue\":0,\"ReceiveChan\":0,\"ExecuteChan\":0,\"AvgQueueDuration\":0},\"QueryQueue\":{\"Unso
lvedQueue\":0,\"ReadyQueue\":0,\"ReceiveChan\":0,\"ExecuteChan\":0,\"AvgQueueDuration\":0},\"GrowingSegmentsSize\":0,\"Effect\":{\"NodeID\":2,\"CollectionIDs\":[]}}}"]
[2023/09/05 14:47:09.578 +00:00] [INFO] [datacoord/index_builder.go:180] ["index builder task schedule"] ["task num"=2]
[2023/09/05 14:47:09.579 +00:00] [INFO] [indexnode/indexnode_service.go:228] ["Get Index Job Stats"] [traceID=e19a7be38975892673b5aacad4d35c62] [Unissued=0] [Active=1] [Slot=0]
[2023/09/05 14:47:09.579 +00:00] [INFO] [datacoord/index_builder.go:188] ["there is no IndexNode available or etcd is not serviceable, wait a minute..."]
```

### Expected Behavior

Run the demo successfully.

### Steps To Reproduce

```markdown
1. Follow the guide (https://milvus.io/docs/install_standalone-docker.md) to install standalone v2.3.0
2. python hello_milvus.py
3. Observe the error

--- 

In fact, the original `docker-compose.yml` doesn't work in the first place. `minio` or `etcd` doesn't start properly. So I had to make the modification like below

version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.4.27
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 300s
      retries: 3

  minio:
    container_name: milvus-minio
    image: minio/minio:latest
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 300s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.3.0
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 300s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"

networks:
  default:
    name: milvus
```

### Milvus

```
[2023/09/05 14:47:00.578 +00:00] [INFO] [datacoord/index_builder.go:180] ["index builder task schedule"] ["task num"=2]
[2023/09/05 14:47:00.578 +00:00] [INFO] [indexnode/indexnode_service.go:228] ["Get Index Job Stats"] [traceID=3d5ee3ab7961ae985b36a1b7bdacc44b] [Unissued=0] [Active=1] [Slot=0]
[2023/09/05 14:47:00.578 +00:00] [INFO] [datacoord/index_builder.go:188] ["there is no IndexNode available or etcd is not serviceable, wait a minute..."]
[2023/09/05 14:47:01.579 +00:00] [INFO] [datacoord/index_builder.go:180] ["index builder task schedule"] ["task num"=2]
[2023/09/05 14:47:01.579 +00:00] [INFO] [indexnode/indexnode_service.go:228] ["Get Index Job Stats"] [traceID=219a270aa9aea05bdfe480612fa17f0f] [Unissued=0] [Active=1] [Slot=0]
[2023/09/05 14:47:01.579 +00:00] [INFO] [datacoord/index_builder.go:188] ["there is no IndexNode available or etcd is not serviceable, wait a minute..."]
[2023/09/05 14:47:02.579 +00:00] [INFO] [datacoord/index_builder.go:180] ["index builder task schedule"] ["task num"=2]
[2023/09/05 14:47:02.579 +00:00] [INFO] [indexnode/indexnode_service.go:228] ["Get Index Job Stats"] [traceID=2df4bd56944fda71c3eb74382d3b3d57] [Unissued=0] [Active=1] [Slot=0]
[2023/09/05 14:47:02.579 +00:00] [INFO] [datacoord/index_builder.go:188] ["there is no IndexNode available or etcd is not serviceable, wait a minute..."]
[2023/09/05 14:47:03.579 +00:00] [INFO] [datacoord/index_builder.go:180] ["index builder task schedule"] ["task num"=2]
[2023/09/05 14:47:03.579 +00:00] [INFO] [indexnode/indexnode_service.go:228] ["Get Index Job Stats"] [traceID=f3fd470afb7917f31d9e44595bab1dd6] [Unissued=0] [Active=1] [Slot=0]
[2023/09/05 14:47:03.579 +00:00] [INFO] [datacoord/index_builder.go:251] ["index builder peek client error, there is no available"]
[2023/09/05 14:47:03.579 +00:00] [INFO] [datacoord/index_builder.go:188] ["there is no IndexNode available or etcd is not serviceable, wait a minute..."]
[2023/09/05 14:47:04.578 +00:00] [INFO] [datacoord/index_builder.go:180] ["index builder task schedule"] ["task num"=2]
[2023/09/05 14:47:04.578 +00:00] [INFO] [indexnode/indexnode_service.go:228] ["Get Index Job Stats"] [traceID=2b7bc9e14ede4c26847d27169dda57f3] [Unissued=0] [Active=1] [Slot=0]
[2023/09/05 14:47:04.579 +00:00] [INFO] [datacoord/index_builder.go:188] ["there is no IndexNode available or etcd is not serviceable, wait a minute..."]
[2023/09/05 14:47:05.578 +00:00] [INFO] [datacoord/index_builder.go:180] ["index builder task schedule"] ["task num"=2]
[2023/09/05 14:47:05.579 +00:00] [INFO] [indexnode/indexnode_service.go:228] ["Get Index Job Stats"] [traceID=0fe03fb8928fba3520c11005a990e6c0] [Unissued=0] [Active=1] [Slot=0]
[2023/09/05 14:47:05.579 +00:00] [INFO] [datacoord/index_builder.go:188] ["there is no IndexNode available or etcd is not serviceable, wait a minute..."]
[2023/09/05 14:47:05.974 +00:00] [INFO] [proxy/meta_cache.go:904] ["expire all shard leader cache"] [database=default] [collections="[hello_milvus]"]
[2023/09/05 14:47:06.578 +00:00] [INFO] [datacoord/index_builder.go:180] ["index builder task schedule"] ["task num"=2]
[2023/09/05 14:47:06.579 +00:00] [INFO] [indexnode/indexnode_service.go:228] ["Get Index Job Stats"] [traceID=598a315273143a5f5d7268be30f9a61d] [Unissued=0] [Active=1] [Slot=0]
[2023/09/05 14:47:06.579 +00:00] [INFO] [datacoord/index_builder.go:188] ["there is no IndexNode available or etcd is not serviceable, wait a minute..."]
[2023/09/05 14:47:07.578 +00:00] [INFO] [datacoord/index_builder.go:180] ["index builder task schedule"] ["task num"=2]
[2023/09/05 14:47:07.579 +00:00] [INFO] [indexnode/indexnode_service.go:228] ["Get Index Job Stats"] [traceID=f441a90cc2ec7977bd327dff53d3dc2e] [Unissued=0] [Active=1] [Slot=0]
[2023/09/05 14:47:07.579 +00:00] [INFO] [datacoord/index_builder.go:188] ["there is no IndexNode available or etcd is not serviceable, wait a minute..."]
[2023/09/05 14:47:08.579 +00:00] [INFO] [datacoord/index_builder.go:180] ["index builder task schedule"] ["task num"=2]
[2023/09/05 14:47:08.579 +00:00] [INFO] [indexnode/indexnode_service.go:228] ["Get Index Job Stats"] [traceID=6bb99eb872d5d560656db3d9e8f0e2dc] [Unissued=0] [Active=1] [Slot=0]
[2023/09/05 14:47:08.579 +00:00] [INFO] [datacoord/index_builder.go:251] ["index builder peek client error, there is no available"]
[2023/09/05 14:47:08.579 +00:00] [INFO] [datacoord/index_builder.go:188] ["there is no IndexNode available or etcd is not serviceable, wait a minute..."]
[2023/09/05 14:47:08.595 +00:00] [INFO] [indexnode/task.go:322] ["index params are ready"] [buildID=444052215049362502] ["index params"="{\"dim\":\"8\",\"index_type\":\"IVF_FLAT\",\"metric_type\":\"L2\",\"nlist\":\"128\"}"]
[2023/09/05 14:47:09.557 +00:00] [INFO] [rootcoord/quota_center.go:416] ["QueryNodeMetrics when cool-off"] [metrics="{\"2\":{\"Hms\":{\"ip\":\"172.27.0.4:21123\",\"cpu_core_count\":48,\"cpu_core_usage\":0,\"memory\":134533251072,\"memory_usage\":123338752,\"disk\":104857600,\"disk_usage\":2097152},\"Rms\":[{\"Label\":\"NQPerSecond\",\"Rate\":0},{\"Label\":\"Sear
chThroughput\",\"Rate\":0},{\"Label\":\"InsertConsumeThroughput\",\"Rate\":0},{\"Label\":\"DeleteConsumeThroughput\",\"Rate\":0}],\"Fgm\":{\"MinFlowGraphChannel\":\"\",\"MinFlowGraphTt\":18446744073709551615,\"NumFlowGraph\":0},\"SearchQueue\":{\"UnsolvedQueue\":0,\"ReadyQueue\":0,\"ReceiveChan\":0,\"ExecuteChan\":0,\"AvgQueueDuration\":0},\"QueryQueue\":{\"Unso
lvedQueue\":0,\"ReadyQueue\":0,\"ReceiveChan\":0,\"ExecuteChan\":0,\"AvgQueueDuration\":0},\"GrowingSegmentsSize\":0,\"Effect\":{\"NodeID\":2,\"CollectionIDs\":[]}}}"]
[2023/09/05 14:47:09.578 +00:00] [INFO] [datacoord/index_builder.go:180] ["index builder task schedule"] ["task num"=2]
[2023/09/05 14:47:09.579 +00:00] [INFO] [indexnode/indexnode_service.go:228] ["Get Index Job Stats"] [traceID=e19a7be38975892673b5aacad4d35c62] [Unissued=0] [Active=1] [Slot=0]
[2023/09/05 14:47:09.579 +00:00] [INFO] [datacoord/index_builder.go:188] ["there is no IndexNode available or etcd is not serviceable, wait a minute..."]
```

###

**Comment by yanliang567** [comment]
@kyoungrok0517  it seems that you update the etcd and minio version in docker compose yaml file, this could bring us some compatibility issue. could you please use docker-compose logs > milvus.log to export the full logs for investigation?
/assign @kyoungrok0517

**Comment by kyoungrok0517** [comment]
Here it is. Too long to paste here.

[milvus.log](https://github.com/milvus-io/milvus/files/12530344/milvus.log)

**Comment by jiaoew1991** [comment]
/assign @xiaocai2333 
/unassign 

please take a look at this isuse

**Comment by xiaocai2333** [comment]
looks like the index task was not assigned successful at the first time, but it was recorded on indexnode. then datacoord drop the task and reassigned. The status of the old task overwrites the status of the new task.
And it should retry instead of fail when task is canceled.
I will fix it.

**Comment by kyoungrok0517** [comment]
Can there be a workaround before the next release? Which part should I look into??

**Comment by xiaocai2333** [comment]
> Can there be a workaround before the next release? Which part should I look into??

Check your network, it looks like the network has been down for a while.
 This should be a difficult case to reproduce.

**Comment by kyoungrok0517** [comment]
Network?? Don't the containers communicate each other using local connection? Do the containers require remote access? More clarification would be appreciated. Thanks.

**Comment by xiaocai2333** [comment]
> Network?? Don't the containers communicate with each other using local connection? Do the containers require remote access? More clarification would be appreciated. Thanks.

We can't get more precise information from the logs. This is a bug caused by rpc call timeout. Not sure why the rpc call times out, and  can you reproduce it reliably?

**Comment by kyoungrok0517** [comment]
I can't avoid having this issue. Maybe compatibility issue with RHEL Enterprise? I'm not sure what's the root cause of RPC timeout.

**Comment by xiaocai2333** [comment]
During indexnode rpc timeout, there is an error also reporting connection etcd timeout. But no more information.
```
milvus-standalone  | [2023/09/06 01:39:28.184 +00:00] [WARN] [grpclog/grpclog.go:46] ["[core][Channel #1 SubChannel #2] grpc: addrConn.createTransport failed to connect to {\n  \"Addr\": \"etcd:2379\",\n  \"ServerName\": \"etcd\",\n  \"Attributes\": null,\n  \"BalancerAttributes\": null,\n  \"Type\": 0,\n  \"Metadata\": null\n}. Err: connection error: desc = \"transport: Error while dialing: dial tcp: lookup etcd: i/o timeout\""]
```

**Comment by xiaocai2333** [comment]
> 

It looks like your etcd is unhealthy, can you export its logs to have a look?

**Comment by kyoungrok0517** [comment]
@xiaocai2333 I think that's because the health check is broken. The method in #26733 solves the problem, but I ran the script as-is so my logs show broken health.
