### ISSUE TITLE
[Bug]: Collection load timeout after standalone pod failure chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#26898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230906-8b5b1372-amd64
- Deployment mode(standalone or cluster):standalone 
- MQ type(rocksmq, pulsar or kafka): rocksmq   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```

[2023-09-06T22:07:33.823Z] [2023-09-06 22:05:02 - INFO - ci_test]: [test][2023-09-06T22:04:58Z] [3.79787124s] Hello_Milvus flush -> None (wrapper.py:30)

[2023-09-06T22:07:33.823Z] [2023-09-06 22:05:02 - INFO - ci_test]: assert entities: 8000 (test_data_persistence.py:93)

[2023-09-06T22:07:33.823Z] [2023-09-06 22:05:02 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:62)

[2023-09-06T22:07:33.823Z] [2023-09-06 22:07:05 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=wait for loading collection timeout, collection: Hello_Milvus)>, <Time:{'RPC start': '2023-09-06 22:05:02.737054', 'RPC error': '2023-09-06 22:07:05.137528'}> (decorators.py:126)

[2023-09-06T22:07:33.824Z] [2023-09-06 22:07:05 - WARNING - pymilvus.decorators]: Retry timeout: 120s (decorators.py:94)

[2023-09-06T22:07:33.824Z] [2023-09-06 22:07:05 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: Hello_Milvus)>, <Time:{'RPC start': '2023-09-06 22:05:02.340854', 'RPC error': '2023-09-06 22:07:05.138253'}> (decorators.py:126)

[2023-09-06T22:07:33.824Z] [2023-09-06 22:07:05 - ERROR - ci_test]: Traceback (most recent call last):

[2023-09-06T22:07:33.824Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2023-09-06T22:07:33.824Z]     res = func(*args, **_kwargs)

[2023-09-06T22:07:33.824Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2023-09-06T22:07:33.824Z]     return func(*arg, **kwargs)

[2023-09-06T22:07:33.824Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 419, in load

[2023-09-06T22:07:33.824Z]     conn.load_collection(

[2023-09-06T22:07:33.824Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 127, in handler

[2023-09-06T22:07:33.824Z]     raise e from e

[2023-09-06T22:07:33.824Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 123, in handler

[2023-09-06T22:07:33.824Z]     return func(*args, **kwargs)

[2023-09-06T22:07:33.824Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 162, in handler

[2023-09-06T22:07:33.824Z]     return func(self, *args, **kwargs)

[2023-09-06T22:07:33.824Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 95, in handler

[2023-09-06T22:07:33.824Z]     raise MilvusException(

[2023-09-06T22:07:33.824Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: Hello_Milvus)>

[2023-09-06T22:07:33.824Z]  (api_request.py:45)

[2023-09-06T22:07:33.824Z] [2023-09-06 22:07:05 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: Hello_Milvus)> (api_request.py:46)
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/7231/pipeline
log:
[artifacts-standalone-pod-failure-7231-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/12544145/artifacts-standalone-pod-failure-7231-pytest-logs.tar.gz)
[artifacts-standalone-pod-failure-7231-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/12544146/artifacts-standalone-pod-failure-7231-server-logs.tar.gz)

**Comment by weiliu1031** [comment]
after new retry policy, load segment request always been canceled by `resetconnection`, which make the load segment operation failed again and again.

should be fixed by #27014.

please verify this with latest image @zhuwenxing
