### ISSUE TITLE
[Bug]: Search failed with error `segment not found: segment=xxx` in many chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#26908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.0-20230907-ec0074b6
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2023-09-07T05:58:31.828Z] [2023-09-07 05:57:58 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:62)

[2023-09-07T05:58:31.828Z] [2023-09-07 05:58:07 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-09-07T05:58:31.828Z] [2023-09-07 05:58:07 - INFO - ci_test]: [test][2023-09-07T05:57:58Z] [8.89724498s] Hello_Milvus load -> None (wrapper.py:30)

[2023-09-07T05:58:31.828Z] [2023-09-07 05:58:07 - INFO - ci_test]: assert load: 8.89761734008789 (test_data_persistence.py:99)

[2023-09-07T05:58:31.828Z] [2023-09-07 05:58:07 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.0028447861078360753, 0.04561295375388627, 0.02793718145684516, 0.00031935703086005495, 0.0248690431219347, 0.1258072999270596, 0.016944780597999184, 0.08454142258206096, 0.09931228912570805, 0.06593713301138239, 0.005456077773997688, 0.12258407140697336, 0.14392023061559123, 0.10915868738164751......, kwargs: {} (api_request.py:62)

[2023-09-07T05:58:31.828Z] [2023-09-07 05:58:09 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=failed to search: attempt #0: failed to search/query delegator 6 for channel by-dev-rootcoord-dml_1_444089005327392476v0: fail to Search, QueryNode ID=6, reason=worker(6) query failed: segment not found: segment=444089174695171531: segment not loaded: attempt #1: no available shard delegator found: service unavailable)>, <Time:{'RPC start': '2023-09-07 05:58:07.112118', 'RPC error': '2023-09-07 05:58:09.329331'}> (decorators.py:126)

[2023-09-07T05:58:31.828Z] [2023-09-07 05:58:09 - ERROR - ci_test]: Traceback (most recent call last):

[2023-09-07T05:58:31.828Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2023-09-07T05:58:31.828Z]     res = func(*args, **_kwargs)

[2023-09-07T05:58:31.828Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2023-09-07T05:58:31.828Z]     return func(*arg, **kwargs)

[2023-09-07T05:58:31.828Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 778, in search

[2023-09-07T05:58:31.828Z]     res = conn.search(

[2023-09-07T05:58:31.829Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 127, in handler

[2023-09-07T05:58:31.829Z]     raise e from e

[2023-09-07T05:58:31.829Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 123, in handler

[2023-09-07T05:58:31.829Z]     return func(*args, **kwargs)

[2023-09-07T05:58:31.829Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 162, in handler

[2023-09-07T05:58:31.829Z]     return func(self, *args, **kwargs)

[2023-09-07T05:58:31.829Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 102, in handler

[2023-09-07T05:58:31.829Z]     raise e from e

[2023-09-07T05:58:31.829Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 68, in handler

[2023-09-07T05:58:31.829Z]     return func(*args, **kwargs)

[2023-09-07T05:58:31.829Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 774, in search

[2023-09-07T05:58:31.829Z]     return self._execute_search_requests(

[2023-09-07T05:58:31.829Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 735, in _execute_search_requests

[2023-09-07T05:58:31.829Z]     raise pre_err from pre_err

[2023-09-07T05:58:31.829Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 726, in _execute_search_requests

[2023-09-07T05:58:31.829Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2023-09-07T05:58:31.829Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=failed to search: attempt #0: failed to search/query delegator 6 for channel by-dev-rootcoord-dml_1_444089005327392476v0: fail to Search, QueryNode ID=6, reason=worker(6) query failed: segment not found: segment=444089174695171531: segment not loaded: attempt #1: no available shard delegator found: service unavailable)>

[2023-09-07T05:58:31.829Z]  (api_request.py:45)

[2023-09-07T05:58:31.829Z] [2023-09-07 05:58:09 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=failed to search: attempt #0: failed to search/query delegator 6 for channel by-dev-rootcoord-dml_1_444089005327392476v0: fail to Search, QueryNode ID=6, reason=worker(6) query failed: segment not found: segment=444089174695171531: segment not loaded: attempt #1: n...... (api_request.py:46)
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-cron/detail/chaos-test-kafka-cron/7104/pipeline
log:
[artifacts-standalone-pod-kill-7104-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/12545730/artifacts-standalone-pod-kill-7104-pytest-logs.tar.gz)

[artifacts-standalone-pod-kill-7104-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/12545731/artifacts-standalone-pod-kill-7104-server-logs.tar.gz)

some other failed jobs:

* https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-cron/detail/chaos-test-kafka-cron/7108/pipeline
* https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-cron/detail/chaos-test-kafka-cron/7109/pipeline
* https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-cron/detail/chaos-test-kafka-cron/7110/pipeline

**Comment by zhuwenxing** [comment]
It also failed in the reinstallation test
```

[2023-09-07T09:10:56.817Z] [2023-09-07 09:08:07 - INFO - ci_test]: index info: [{'collection': 'FlushChecker__5vfGtPAG', 'field': 'float_vector', 'index_name': 'test_0QqqMZcH', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}] (test_all_collections_after_chaos.py:87)

[2023-09-07T09:10:56.817Z] [2023-09-07 09:08:07 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:62)

[2023-09-07T09:10:56.817Z] [2023-09-07 09:08:32 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-09-07T09:10:56.817Z] [2023-09-07 09:08:32 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.010159163345690796, 0.11273734538330085, 0.05392494125478032, 0.14198358055822066, 0.0940086680944635, 0.005237327022958855, 0.030228039484186366, 0.07636592410787049, 0.017153678885960196, 0.05261390873657478, 0.05043780715640719, 0.004831370137810686, 0.06485966733529486, 0.004612114254804619......, kwargs: {} (api_request.py:62)

[2023-09-07T09:10:56.817Z] [2023-09-07 09:08:33 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=failed to search: attempt #0: failed to search/query delegator 2 for channel by-dev-rootcoord-dml_11_444091445116156098v1: fail to Search, QueryNode ID=2, reason=worker(2) query failed: segment not found: segment=444091445118789260: segment not loaded: attempt #1: no available shard delegator found: service unavailable)>, <Time:{'RPC start': '2023-09-07 09:08:32.238084', 'RPC error': '2023-09-07 09:08:33.016679'}> (decorators.py:126)

[2023-09-07T09:10:56.817Z] [2023-09-07 09:08:33 - ERROR - ci_test]: Traceback (most recent call last):

[2023-09-07T09:10:56.817Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2023-09-07T09:10:56.817Z]     res = func(*args, **_kwargs)

[2023-09-07T09:10:56.817Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2023-09-07T09:10:56.817Z]     return func(*arg, **kwargs)

[2023-09-07T09:10:56.817Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 778, in search

[2023-09-07T09:10:56.817Z]     res = conn.search(

[2023-09-07T09:10:56.817Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 127, in handler

[2023-09-07T09:10:56.817Z]     raise e from e

[2023-09-07T09:10:56.817Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 123, in handler

[2023-09-07T09:10:56.817Z]     return func(*args, **kwargs)

[2023-09-07T09:10:56.817Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 162, in handler

[2023-09-07T09:10:56.817Z]     return func(self, *args, **kwargs)

[2023-09-07T09:10:56.817Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 102, in handler

[2023-09-07T09:10:56.817Z]     raise e from e

[2023-09-07T09:10:56.817Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 68, in handler

[2023-09-07T09:10:56.817Z]     return func(*args, **kwargs)

[2023-09-07T09:10:56.817Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 774, in search

[2023-09-07T09:10:56.817Z]     return self._execute_search_requests(

[2023-09-07T09:10:56.817Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 735, in _execute_search_requests

[2023-09-07T09:10:56.817Z]     raise pre_err from pre_err

[2023-09-07T09:10:56.817Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 726, in _execute_search_requests

[2023-09-07T09:10:56.817Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2023-09-07T09:10:56.817Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=failed to search: attempt #0: failed to search/query delegator 2 for channel by-dev-rootcoord-dml_11_444091445116156098v1: fail to Search, QueryNode ID=2, reason=worker(2) query failed: segment not found: segment=444091445118789260: segment not loaded: attempt #1: no available shard delegator found: service unavailable)>

[2023-09-07T09:10:56.817Z]  (api_request.py:45)

[2023-09-07T09:10:56.817Z] [2023-09-07 09:08:33 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=failed to search: attempt #0: failed to search/query delegator 2 for channel by-dev-rootcoord-dml_11_444091445116156098v1: fail to Search, QueryNode ID=2, reason=worker(2) query failed: segment not found: segment=444091445118789260: segment not loaded: attempt #1: ...... (api_request.py:46)
```

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_kafka_cron/detail/deploy_test_kafka_cron/1240/pipeline

log:
[artifacts-kafka-standalone-reinstall-1240-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/12547429/artifacts-kafka-standalone-reinstall-1240-pytest-logs.tar.gz)
[artifacts-kafka-standalone-reinstall-1240-server-first-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/12547430/artifacts-kafka-standalone-reinstall-1240-server-first-deployment-logs.tar.gz)
[artifacts-kafka-standalone-reinstall-1240-server-second-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/12547431/artifacts-kafka-standalone-reinstall-1240-server-second-deployment-logs.tar.gz)

**Comment by jiaoew1991** [comment]
/assign @weiliu1031 
please help on this issue

**Comment by zhuwenxing** [comment]
Still reproduced in 2.3.0-20230908-5c53b435
```
[2023-09-08T10:37:04.245Z] [2023-09-08 10:27:36 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=failed to search: attempt #0: failed to search/query delegator 6 for channel by-dev-rootcoord-dml_11_444115875026837373v0: fail to Search, QueryNode ID=6, reason=worker(6) query failed: segment not found: segment=444116004819961197: segment not loaded: attempt #1: ...... (api_request.py:46)
[2023-09-08T10:37:04.245Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[Checker__KtZox4aw] - AssertionError
```

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/7275/pipeline
log:
[artifacts-standalone-pod-kill-7275-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/12558707/artifacts-standalone-pod-kill-7275-pytest-logs.tar.gz)
[artifacts-standalone-pod-kill-7275-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/12558708/artifacts-standalone-pod-kill-7275-server-logs.tar.gz)

**Comment by zhuwenxing** [comment]
It is still reproduced in version `2.3.0-20230911-57bed4a0` with rootcoord pod kill chaos test
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-for-release-cron/detail/chaos-test-kafka-for-release-cron/7215/pipeline
log:
[artifacts-rootcoord-pod-kill-7215-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/12573104/artifacts-rootcoord-pod-kill-7215-pytest-logs.tar.gz)
[artifacts-rootcoord-pod-kill-7215-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/12573105/artifacts-rootcoord-pod-kill-7215-server-logs.tar.gz)

**Comment by zhuwenxing** [comment]
Not reproduced in with 2.3.0-20230912-608ba462.

**Comment by yanliang567** [comment]
close  as comments above
