### ISSUE TITLE
[Bug]: The sum of num rows of segments is less than the num_entities

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#26925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230907-e2528030-amd64
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka): kafka   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

collection: sift_128_euclidean_HNSW
1M entities have been inserted, but only got 400K in segments info.

```
[2023-09-07T10:16:30.180Z] 2023-09-07 10:16:30.100 | INFO     | __main__:milvus_recall_test:107 - Insert 1000000 vectors cost 59.6915 seconds

[2023-09-07T10:16:30.185Z] 2023-09-07 10:16:30.100 | INFO     | __main__:milvus_recall_test:110 - Get collection entities...

[2023-09-07T10:16:33.457Z] 2023-09-07 10:16:32.769 | INFO     | __main__:milvus_recall_test:115 - 1000000

[2023-09-07T10:16:33.458Z] 2023-09-07 10:16:32.769 | INFO     | __main__:milvus_recall_test:117 - Get collection entities cost 2.6691 seconds

[2023-09-07T10:16:33.458Z] 2023-09-07 10:16:32.770 | INFO     | __main__:milvus_recall_test:121 - Create index...

[2023-09-07T10:18:09.864Z] 2023-09-07 10:18:02.602 | INFO     | __main__:milvus_recall_test:126 - Create index cost 89.8325 seconds

[2023-09-07T10:18:09.866Z] 2023-09-07 10:18:02.603 | INFO     | __main__:milvus_recall_test:130 - load collection...

[2023-09-07T10:18:09.866Z] 2023-09-07 10:18:07.136 | INFO     | __main__:milvus_recall_test:134 - load collection cost 4.5333 seconds

[2023-09-07T10:18:09.866Z] 2023-09-07 10:18:07.138 | INFO     | __main__:milvus_recall_test:137 - segments info: [segmentID: 444093333682735035

[2023-09-07T10:18:09.866Z] collectionID: 444093333681734141

[2023-09-07T10:18:09.866Z] partitionID: 444093333681734142

[2023-09-07T10:18:09.866Z] num_rows: 200000

[2023-09-07T10:18:09.866Z] state: Sealed

[2023-09-07T10:18:09.866Z] nodeIds: 1

[2023-09-07T10:18:09.866Z] , segmentID: 444093333683335840

[2023-09-07T10:18:09.866Z] collectionID: 444093333681734141

[2023-09-07T10:18:09.866Z] partitionID: 444093333681734142

[2023-09-07T10:18:09.866Z] num_rows: 200000

[2023-09-07T10:18:09.866Z] state: Sealed

[2023-09-07T10:18:09.866Z] nodeIds: 1

[2023-09-07T10:18:09.866Z] ]

[2023-09-07T10:18:09.866Z] Traceback (most recent call last):

[2023-09-07T10:18:09.866Z]   File "scripts/first_recall_test.py", line 200, in <module>

[2023-09-07T10:18:09.866Z]     milvus_recall_test(host, index_type)

[2023-09-07T10:18:09.866Z]   File "scripts/first_recall_test.py", line 140, in milvus_recall_test

[2023-09-07T10:18:09.866Z]     assert cnt == collection.num_entities

[2023-09-07T10:18:09.866Z] AssertionError
```

### Expected Behavior

The sum of num rows of segments is equal to the num_entities

### Steps To Reproduce

```markdown
create collection
insert data
create index
load collection
get segment info
compare num_rows and num_entities
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_kafka_cron/detail/deploy_test_kafka_cron/1245/pipeline

log:
[artifacts-kafka-standalone-reinstall-1245-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/12554888/artifacts-kafka-standalone-reinstall-1245-pytest-logs.tar.gz)
[artifacts-kafka-standalone-reinstall-1245-server-second-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/12554889/artifacts-kafka-standalone-reinstall-1245-server-second-deployment-logs.tar.gz)

**Comment by zhuwenxing** [comment]
It has not been reproduced recently. image tag: 2.3.0-20230915-a42bc90c

![image](https://github.com/milvus-io/milvus/assets/12268675/a4b3c69b-1326-494f-baae-b77e3f2d7eb0)
