### ISSUE TITLE
[Bug]: `TestSessionProcessActiveStandBy` is not stable

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#26964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2101f2d & 2.3.0
- Deployment mode(standalone or cluster): 
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

TestSessionProcessActiveStandBy test case may block 10min and timeout

### Expected Behavior

Test cases shall pass stably

### Milvus Log

```
2023-09-10T00:38:51.6198675Z panic: test timed out after 10m0s
2023-09-10T00:38:51.6199288Z running tests:
2023-09-10T00:38:51.6199851Z 	TestSessionProcessActiveStandBy (9m53s)
2023-09-10T00:38:51.6200243Z 
2023-09-10T00:38:51.6200549Z goroutine 552 [running]:
2023-09-10T00:38:51.6201068Z testing.(*M).startAlarm.func1()
2023-09-10T00:38:51.6201624Z 	/usr/local/go/src/testing/testing.go:2241 +0x219
2023-09-10T00:38:51.6216919Z created by time.goFunc
2023-09-10T00:38:51.6217451Z 	/usr/local/go/src/time/sleep.go:176 +0x48
2023-09-10T00:38:51.6217804Z 
2023-09-10T00:38:51.6218142Z goroutine 1 [chan receive, 9 minutes]:
2023-09-10T00:38:51.6218562Z testing.(*T).Run(0xc0004d3520, {0x1b90566, 0x1f}, 0x1becb78)
2023-09-10T00:38:51.6219093Z 	/usr/local/go/src/testing/testing.go:1630 +0x82e
2023-09-10T00:38:51.6219597Z testing.runTests.func1(0x0?)
2023-09-10T00:38:51.6220160Z 	/usr/local/go/src/testing/testing.go:2036 +0x8e
2023-09-10T00:38:51.6220710Z testing.tRunner(0xc0004d3520, 0xc00039fb40)
2023-09-10T00:38:51.6221263Z 	/usr/local/go/src/testing/testing.go:1576 +0x217
2023-09-10T00:38:51.6221898Z testing.runTests(0xc0001720a0?, {0x27cb040, 0xf, 0xf}, {0xc00039fba8?, 0x453f91?, 0x27e43e0?})
2023-09-10T00:38:51.6222521Z 	/usr/local/go/src/testing/testing.go:2034 +0x87d
2023-09-10T00:38:51.6223056Z testing.(*M).Run(0xc0001720a0)
2023-09-10T00:38:51.6223594Z 	/usr/local/go/src/testing/testing.go:1906 +0xb45
2023-09-10T00:38:51.6224026Z main.main()
2023-09-10T00:38:51.6224487Z 	_testmain.go:106 +0x2fd
```

### Anything else?

See also 
https://github.com/milvus-io/milvus/actions/runs/6133766499/job/16645979764
https://github.com/milvus-io/milvus/actions/runs/6134499940/job/16647516566

**Comment by SimFG** [comment]
log
```
2023-09-19T18:33:51.6420314Z === RUN   TestSessionProcessActiveStandBy
2023-09-19T18:33:51.6469746Z [2023/09/19 18:33:51.646 +00:00] [DEBUG] [sessionutil/session_util.go:229] ["Session try to connect to etcd"]
2023-09-19T18:33:51.6477939Z [2023/09/19 18:33:51.647 +00:00] [DEBUG] [sessionutil/session_util.go:244] ["Session connect to etcd success"]
2023-09-19T18:33:51.6493360Z [2023/09/19 18:33:51.648 +00:00] [DEBUG] [sessionutil/session_util.go:287] [getServerID] [reuse=false]
2023-09-19T18:33:51.6514377Z [2023/09/19 18:33:51.650 +00:00] [DEBUG] [sessionutil/session_util.go:345] ["Session get serverID success"] [key=id] [ServerId=1]
2023-09-19T18:33:51.6517728Z [2023/09/19 18:33:51.651 +00:00] [INFO] [sessionutil/session_util.go:261] ["start server"] [name=inittest] [address=testAddr] [id=1]
2023-09-19T18:33:51.6551478Z [2023/09/19 18:33:51.651 +00:00] [DEBUG] [sessionutil/session_util.go:408] ["service begin to register to etcd"] [serverName=inittest] [ServerID=1]
2023-09-19T18:33:51.6635489Z [2023/09/19 18:33:51.661 +00:00] [INFO] [sessionutil/session_util.go:438] ["put session key into etcd"] [key=2368463258322938615/session/1/session/inittest-1] [value="{\"ServerID\":1,\"ServerName\":\"inittest\",\"Address\":\"testAddr\",\"Exclusive\":true,\"TriggerKill\":true,\"Version\":\"2.3.0\",\"LeaseID\":7587873429713483235}"]
2023-09-19T18:33:51.6636637Z [2023/09/19 18:33:51.661 +00:00] [INFO] [sessionutil/session_util.go:448] ["Service registered successfully"] [ServerName=inittest] [serverID=1]
2023-09-19T18:33:51.6637172Z [2023/09/19 18:33:51.662 +00:00] [INFO] [sessionutil/session_util.go:978] ["serverName: inittest enter STANDBY mode"]
2023-09-19T18:33:51.6637658Z [2023/09/19 18:33:51.662 +00:00] [INFO] [sessionutil/session_util.go:952] ["try to register as ACTIVE inittest service..."]
2023-09-19T18:33:51.6638143Z [2023/09/19 18:33:51.662 +00:00] [DEBUG] [sessionutil/session_util.go:981] ["serverName: inittest is in STANDBY ..."]
2023-09-19T18:33:51.6656147Z [2023/09/19 18:33:51.664 +00:00] [INFO] [sessionutil/session_util.go:970] ["register ACTIVE inittest"]
2023-09-19T18:33:51.6656687Z [2023/09/19 18:33:51.664 +00:00] [INFO] [sessionutil/session_util.go:1023] ["serverName: inittest quit STANDBY mode, this node will become ACTIVE"]
2023-09-19T18:33:51.6657192Z [2023/09/19 18:33:51.665 +00:00] [DEBUG] [sessionutil/session_util_test.go:617] ["Session 1 become active"]
2023-09-19T18:33:51.6664707Z [2023/09/19 18:33:51.666 +00:00] [WARN] [sessionutil/session_util.go:377] ["fail to get the session key from the etcd"] []
2023-09-19T18:33:51.6675230Z [2023/09/19 18:33:51.667 +00:00] [DEBUG] [sessionutil/session_util.go:229] ["Session try to connect to etcd"]
2023-09-19T18:33:51.6684625Z [2023/09/19 18:33:51.668 +00:00] [DEBUG] [sessionutil/session_util.go:244] ["Session connect to etcd success"]
2023-09-19T18:33:51.6697492Z [2023/09/19 18:33:51.669 +00:00] [DEBUG] [sessionutil/session_util.go:287] [getServerID] [reuse=false]
2023-09-19T18:33:51.6718822Z [2023/09/19 18:33:51.671 +00:00] [INFO] [sessionutil/session_util.go:846] ["register session success"] [role=inittest] [key=2368463258322938615/session/1/session/inittest]
2023-09-19T18:33:51.6722581Z [2023/09/19 18:33:51.671 +00:00] [DEBUG] [sessionutil/session_util.go:345] ["Session get serverID success"] [key=id] [ServerId=2]
2023-09-19T18:33:51.6725831Z [2023/09/19 18:33:51.672 +00:00] [INFO] [sessionutil/session_util.go:261] ["start server"] [name=inittest] [address=testAddr] [id=2]
2023-09-19T18:33:51.6729113Z [2023/09/19 18:33:51.672 +00:00] [DEBUG] [sessionutil/session_util.go:408] ["service begin to register to etcd"] [serverName=inittest] [ServerID=2]
2023-09-19T18:33:51.6754280Z [2023/09/19 18:33:51.674 +00:00] [INFO] [sessionutil/session_util.go:438] ["put session key into etcd"] [key=2368463258322938615/session/1/session/inittest-2] [value="{\"ServerID\":2,\"ServerName\":\"inittest\",\"Address\":\"testAddr\",\"Exclusive\":true,\"TriggerKill\":true,\"Version\":\"2.3.0\",\"LeaseID\":7587873429713483244}"]
2023-09-19T18:33:51.6755708Z [2023/09/19 18:33:51.674 +00:00] [INFO] [sessionutil/session_util.go:448] ["Service registered successfully"] [ServerName=inittest] [serverID=2]
2023-09-19T18:33:51.6758385Z [2023/09/19 18:33:51.675 +00:00] [INFO] [sessionutil/session_util.go:978] ["serverName: inittest enter STANDBY mode"]
2023-09-19T18:33:51.6761775Z [2023/09/19 18:33:51.675 +00:00] [INFO] [sessionutil/session_util.go:952] ["try to register as ACTIVE inittest service..."]
2023-09-19T18:33:51.6766352Z [2023/09/19 18:33:51.676 +00:00] [DEBUG] [sessionutil/session_util.go:981] ["serverName: inittest is in STANDBY ..."]
2023-09-19T18:33:51.6771021Z [2023/09/19 18:33:51.675 +00:00] [DEBUG] [sessionutil/session_util_test.go:645] ["Stop session 1, session 2 will take over primary service"]
2023-09-19T18:33:51.6779429Z [2023/09/19 18:33:51.677 +00:00] [INFO] [sessionutil/session_util.go:972] ["ACTIVE inittest has already been registered"]
2023-09-19T18:33:51.6780532Z [2023/09/19 18:33:51.677 +00:00] [INFO] [sessionutil/session_util.go:995] ["inittest start to watch ACTIVE key 2368463258322938615/session/1/session/inittest"]
2023-09-19T18:33:51.6793952Z [2023/09/19 18:33:51.678 +00:00] [WARN] [sessionutil/session_util.go:472] ["session keepalive channel closed"]
2023-09-19T18:33:51.6799016Z [2023/09/19 18:33:51.678 +00:00] [INFO] [sessionutil/session_util.go:848] ["session key is deleted, exit..."] [role=inittest] [key=2368463258322938615/session/1/session/inittest]
2023-09-19T18:33:51.6803690Z [2023/09/19 18:33:51.679 +00:00] [WARN] [sessionutil/session_util.go:823] ["watch session key channel closed"]
2023-09-19T18:33:51.7726165Z [2023/09/19 18:33:51.771 +00:00] [DEBUG] [sessionutil/session_util.go:1013] ["watch the ACTIVE key"] [DELETE="key:\"2368463258322938615/session/1/session/inittest\" mod_revision:1524 "]
2023-09-19T18:33:51.7731733Z [2023/09/19 18:33:51.772 +00:00] [INFO] [sessionutil/session_util.go:1019] ["stop watching ACTIVE key 2368463258322938615/session/1/session/inittest"]
2023-09-19T18:33:51.7734898Z [2023/09/19 18:33:51.772 +00:00] [INFO] [sessionutil/session_util.go:952] ["try to register as ACTIVE inittest service..."]
2023-09-19T18:33:51.7748859Z [2023/09/19 18:33:51.774 +00:00] [INFO] [sessionutil/session_util.go:970] ["register ACTIVE inittest"]
2023-09-19T18:33:51.7752929Z [2023/09/19 18:33:51.774 +00:00] [INFO] [sessionutil/session_util.go:1023] ["serverName: inittest quit STANDBY mode, this node will become ACTIVE"]
2023-09-19T18:33:51.7756726Z [2023/09/19 18:33:51.775 +00:00] [DEBUG] [sessionutil/session_util_test.go:637] ["Session 2 become active"]
2023-09-19T18:33:52.9694776Z [2023/09/19 18:33:52.966 +00:00] [WARN] [sessionutil/session_util.go:496] ["fail to retry keepAliveOnce"] [serverName=sessionComp] [leaseID=7587873430210733321] [error="attempt #0: etcdserver: requested lease not found: attempt #1: etcdserver: requested lease not found: attempt #2: etcdserver: requested lease not found"]
2023-09-19T18:33:52.9696311Z [2023/09/19 18:33:52.966 +00:00] [WARN] [sessionutil/session_util.go:496] ["fail to retry keepAliveOnce"] [serverName=sessionComp] [leaseID=7587873430210733335] [error="attempt #0: etcdserver: requested lease not found: attempt #1: etcdserver: requested lease not found: attempt #2: etcdserver: requested lease not found"]
2023-09-19T18:33:52.9697660Z [2023/09/19 18:33:52.967 +00:00] [WARN] [sessionutil/session_util.go:496] ["fail to retry keepAliveOnce"] [serverName=sessionComp] [leaseID=7587873430210733328] [error="attempt #0: etcdserver: requested lease not found: attempt #1: etcdserver: requested lease not found: attempt #2: etcdserver: server stopped"]
2023-09-19T18:33:53.0432510Z [2023/09/19 18:33:53.041 +00:00] [WARN] [sessionutil/session_util.go:496] ["fail to retry keepAliveOnce"] [serverName=sessionComp] [leaseID=7587873430210733360] [error="attempt #0: etcdserver: requested lease not found: attempt #1: etcdserver: server stopped: attempt #2: etcdserver: requested lease not found"]
2023-09-19T18:33:53.0433963Z [2023/09/19 18:33:53.041 +00:00] [WARN] [sessionutil/session_util.go:496] ["fail to retry keepAliveOnce"] [serverName=sessionComp] [leaseID=7587873430210733367] [error="attempt #0: etcdserver: requested lease not found: attempt #1: etcdserver: server stopped: attempt #2: etcdserver: requested lease not found"]
2023-09-19T18:33:53.0437784Z [2023/09/19 18:33:53.042 +00:00] [WARN] [sessionutil/session_util.go:496] ["fail to retry keepAliveOnce"] [serverName=sessionComp] [leaseID=7587873430210733353] [error="attempt #0: etcdserver: server stopped: attempt #1: etcdserver: server stopped: attempt #2: etcdserver: requested lease not found"]
```
