### ISSUE TITLE
[Bug]: Standalone pod panic when running e2e test cases in ci

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#26989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):rocksmq 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
2023-09-11T15:32:26.603599222+08:00 stdout F [2023/09/11 07:32:26.603 +00:00] [DEBUG] [proxy/task_scheduler.go:263] ["Proxy dmTaskQueue popPChanStats"] [taskID=444181393331978243]
2023-09-11T15:32:26.610676005+08:00 stdout F [2023/09/11 07:32:26.610 +00:00] [DEBUG] [proxy/impl.go:2491] ["Search received"] [traceID=85ff186086c96b4af3410c9027285e1c] [role=proxy] [db=default] [collection=search_collection_cA7IMSBp] [partitions="[]"] [dsl="int64 >= 0"] [len(PlaceholderGroup)=26210] [OutputFields="[]"] [search_params="[{\"key\":\"topk\",\"value\":\"1000\"},{\"key\":\"params\",\"value\":\"{\\\"nprobe\\\":10}\"},{\"key\":\"round_decimal\",\"value\":\"-1\"},{\"key\":\"ignore_growing\",\"value\":\"False\"},{\"key\":\"metric_type\",\"value\":\"COSINE\"},{\"key\":\"anns_field\",\"value\":\"float_vector\"}]"] [guarantee_timestamp=2]
2023-09-11T15:32:26.613029345+08:00 stderr F panic: runtime error: invalid memory address or nil pointer dereference
2023-09-11T15:32:26.613048885+08:00 stderr F [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x38dddbc]
2023-09-11T15:32:26.613051979+08:00 stderr F 
2023-09-11T15:32:26.613056258+08:00 stderr F goroutine 478457 [running]:
2023-09-11T15:32:26.613058669+08:00 stderr F panic({0x3f70ec0, 0x6265450})
2023-09-11T15:32:26.613061565+08:00 stderr F 	/usr/local/go/src/runtime/panic.go:987 +0x3bb fp=0xc001582438 sp=0xc001582378 pc=0x169ebdb
2023-09-11T15:32:26.613064693+08:00 stderr F runtime.panicmem(...)
2023-09-11T15:32:26.61306736+08:00 stderr F 	/usr/local/go/src/runtime/panic.go:260
2023-09-11T15:32:26.613069828+08:00 stderr F runtime.sigpanic()
```

### Milvus Log

failed job: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-26986/1/pipeline

**Comment by xiaofan-luan** [comment]
/assign @sunby

could you help on fixing this?

**Comment by bigsheeper** [comment]
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-26142/34/pipeline/

**Comment by bigsheeper** [comment]
```
2023-09-11T15:32:26.603131724+08:00 stdout F [2023/09/11 07:32:26.603 +00:00] [DEBUG] [proxy/task_insert.go:264] ["assign segmentID for insert data success"] [traceID=76f521b9970a599acbf0b543bc349441] ["assign segmentID duration"=1.952682ms]
2023-09-11T15:32:26.603592426+08:00 stdout F [2023/09/11 07:32:26.603 +00:00] [DEBUG] [proxy/task_insert.go:276] ["Proxy Insert Execute done"] [traceID=76f521b9970a599acbf0b543bc349441] [collectionName=search_collection_cA7IMSBp] ["send message duration"=452.525µs] ["execute duration"=2.410776ms]
2023-09-11T15:32:26.603599222+08:00 stdout F [2023/09/11 07:32:26.603 +00:00] [DEBUG] [proxy/task_scheduler.go:263] ["Proxy dmTaskQueue popPChanStats"] [taskID=444181393331978243]
2023-09-11T15:32:26.610676005+08:00 stdout F [2023/09/11 07:32:26.610 +00:00] [DEBUG] [proxy/impl.go:2491] ["Search received"] [traceID=85ff186086c96b4af3410c9027285e1c] [role=proxy] [db=default] [collection=search_collection_cA7IMSBp] [partitions="[]"] [dsl="int64 >= 0"] [len(PlaceholderGroup)=26210] [OutputFields="[]"] [search_params="[{\"key\":\"topk\",\"value\":\"1000\"},{\"key\":\"params\",\"value\":\"{\\\"nprobe\\\":10}\"},{\"key\":\"round_decimal\",\"value\":\"-1\"},{\"key\":\"ignore_growing\",\"value\":\"False\"},{\"key\":\"metric_type\",\"value\":\"COSINE\"},{\"key\":\"anns_field\",\"value\":\"float_vector\"}]"] [guarantee_timestamp=2]
2023-09-11T15:32:26.613029345+08:00 stderr F panic: runtime error: invalid memory address or nil pointer dereference
2023-09-11T15:32:26.613048885+08:00 stderr F [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x38dddbc]
2023-09-11T15:32:26.613051979+08:00 stderr F 
2023-09-11T15:32:26.613056258+08:00 stderr F goroutine 478457 [running]:
2023-09-11T15:32:26.613058669+08:00 stderr F panic({0x3f70ec0, 0x6265450})
2023-09-11T15:32:26.613061565+08:00 stderr F 	/usr/local/go/src/runtime/panic.go:987 +0x3bb fp=0xc001582438 sp=0xc001582378 pc=0x169ebdb
2023-09-11T15:32:26.613064693+08:00 stderr F runtime.panicmem(...)
2023-09-11T15:32:26.61306736+08:00 stderr F 	/usr/local/go/src/runtime/panic.go:260
2023-09-11T15:32:26.613069828+08:00 stderr F runtime.sigpanic()
2023-09-11T15:32:26.61307251+08:00 stderr F 	/usr/local/go/src/runtime/signal_unix.go:841 +0x37d fp=0xc001582498 sp=0xc001582438 pc=0x16b6e1d
2023-09-11T15:32:26.613074779+08:00 stderr F github.com/milvus-io/milvus/internal/proxy.(*timestampAllocator).alloc(0xc001f28c00, {0x494b660, 0xc00fc25e90}, 0x1)
2023-09-11T15:32:26.613077227+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/proxy/timestamp.go:69 +0x21c fp=0xc0015825a0 sp=0xc001582498 pc=0x38dddbc
2023-09-11T15:32:26.613085125+08:00 stderr F github.com/milvus-io/milvus/internal/proxy.(*timestampAllocator).AllocOne(0xc0011292c0?, {0x494b660?, 0xc00fc25e90?})
2023-09-11T15:32:26.613091147+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/proxy/timestamp.go:83 +0x28 fp=0xc0015825d0 sp=0xc0015825a0 pc=0x38de228
2023-09-11T15:32:26.613093412+08:00 stderr F github.com/milvus-io/milvus/internal/proxy.(*baseTaskQueue).Enqueue(0xc001193900, {0x497b058, 0xc0011292c0})
2023-09-11T15:32:26.613095646+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:170 +0x6b fp=0xc001582600 sp=0xc0015825d0 pc=0x38c4d6b
2023-09-11T15:32:26.613097928+08:00 stderr F github.com/milvus-io/milvus/internal/proxy.(*Proxy).Search(0xc000230c60, {0x494b660, 0xc00fc25cb0}, 0xc000658e10)
2023-09-11T15:32:26.613100172+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/proxy/impl.go:2493 +0x120f fp=0xc001582d28 sp=0xc001582600 pc=0x384fc6f
2023-09-11T15:32:26.61310241+08:00 stderr F github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).Search(0x16aa651?, {0x494b660?, 0xc00fc25cb0?}, 0xc005669f98?)
2023-09-11T15:32:26.613105045+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:829 +0x2f fp=0xc001582d58 sp=0xc001582d28 pc=0x396e0ef
```

**Comment by bigsheeper** [comment]
/assign @zhuwenxing 
should be fixed
