### ISSUE TITLE
[Bug]: Load collection timeout(120s) after standalone pod failure chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#27022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.0-20230911-30003e83
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):kafka    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```

[2023-09-12T00:32:46.000Z] [2023-09-12 00:23:02 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:62)

[2023-09-12T00:32:46.000Z] [2023-09-12 00:23:08 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-09-12T00:32:46.000Z] [2023-09-12 00:23:08 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.1501809320692548, 0.14923115874309034, 0.04220812471926565, 0.1105196016404261, 0.1037405041179099, 0.0281476100535233, 0.1009208350277697, 0.08347036190262218, 0.08493371205748264, 0.14594228420133698, 0.043383237411900984, 0.020676534505550327, 0.07984333246808506, 0.08252060397899662, 0.1059......, kwargs: {} (api_request.py:62)

[2023-09-12T00:32:46.000Z] [2023-09-12 00:23:08 - DEBUG - ci_test]: (api_response) : ["['id: 6444356531428708634, distance: 22.258731842041016, entity: {}']"]  (api_request.py:37)

[2023-09-12T00:32:46.000Z] [2023-09-12 00:23:08 - INFO - ci_test]: assert search: 0.24899077415466309 (test_all_collections_after_chaos.py:100)

[2023-09-12T00:32:46.000Z] [2023-09-12 00:23:08 - DEBUG - ci_test]: (api_request)  : [Collection.query] args: ['int64 in [-3000, -2999, -2998, -2997, -2996, -2995, -2994, -2993, -2992, -2991, -2990, -2989, -2988, -2987, -2986, -2985, -2984, -2983, -2982, -2981, -2980, -2979, -2978, -2977, -2976, -2975, -2974, -2973, -2972, -2971, -2970, -2969, -2968, -2967, -2966, -2965, -2964, -2963, -2962, -2961, -2960, -......, kwargs: {} (api_request.py:62)

[2023-09-12T00:32:46.000Z] [2023-09-12 00:23:08 - DEBUG - ci_test]: (api_response) : [{'int64': -3000}, {'int64': -2999}, {'int64': -2998}, {'int64': -2997}, {'int64': -2996}, {'int64': -2995}, {'int64': -2994}, {'int64': -2993}, {'int64': -2992}, {'int64': -2991}, {'int64': -2990}, {'int64': -2989}, {'int64': -2988}, {'int64': -2987}, {'int64': -2986}, {'int64': -2985}, {'int64': -......  (api_request.py:37)

[2023-09-12T00:32:46.000Z] [2023-09-12 00:23:08 - INFO - ci_test]: assert query result 2000: 0.21684885025024414 (test_all_collections_after_chaos.py:107)

[2023-09-12T00:32:46.000Z] [2023-09-12 00:23:08 - DEBUG - ci_test]: (api_request)  : [Collection.release] args: [], kwargs: {'timeout': 120} (api_request.py:62)

[2023-09-12T00:32:46.000Z] [2023-09-12 00:23:09 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-09-12T00:32:46.000Z] [2023-09-12 00:23:09 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [[[-3352756197227430028, 5374744164665471692, -6436140593765004002, 7836320918818127988, -3611518647533042630, 1120783546119423959, -1986956211776013872, 1463704107477310787, -8860576302515583520, -1181175328709993185, 5844800658504623170, -7608574379271347645, -4641344049907364302, 6418439999184170......, kwargs: {'timeout': 120} (api_request.py:62)

[2023-09-12T00:32:46.000Z] [2023-09-12 00:23:09 - DEBUG - ci_test]: (api_response) : (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 444197290605019138, success count: 2000, err count: 0)  (api_request.py:37)

[2023-09-12T00:32:46.000Z] [2023-09-12 00:23:09 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:62)

[2023-09-12T00:32:46.000Z] [2023-09-12 00:25:11 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=wait for loading collection timeout, collection: FlushChecker__rBTPAKdD)>, <Time:{'RPC start': '2023-09-12 00:23:10.044484', 'RPC error': '2023-09-12 00:25:11.654521'}> (decorators.py:126)

[2023-09-12T00:32:46.000Z] [2023-09-12 00:25:11 - WARNING - pymilvus.decorators]: Retry timeout: 120s (decorators.py:94)

[2023-09-12T00:32:46.000Z] [2023-09-12 00:25:11 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: FlushChecker__rBTPAKdD)>, <Time:{'RPC start': '2023-09-12 00:23:09.943559', 'RPC error': '2023-09-12 00:25:11.655217'}> (decorators.py:126)

[2023-09-12T00:32:46.000Z] [2023-09-12 00:25:11 - ERROR - ci_test]: Traceback (most recent call last):

[2023-09-12T00:32:46.000Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2023-09-12T00:32:46.000Z]     res = func(*args, **_kwargs)

[2023-09-12T00:32:46.000Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2023-09-12T00:32:46.000Z]     return func(*arg, **kwargs)

[2023-09-12T00:32:46.000Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 419, in load

[2023-09-12T00:32:46.000Z]     conn.load_collection(

[2023-09-12T00:32:46.000Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 127, in handler

[2023-09-12T00:32:46.000Z]     raise e from e

[2023-09-12T00:32:46.000Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 123, in handler

[2023-09-12T00:32:46.000Z]     return func(*args, **kwargs)

[2023-09-12T00:32:46.000Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 162, in handler

[2023-09-12T00:32:46.000Z]     return func(self, *args, **kwargs)

[2023-09-12T00:32:46.000Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 95, in handler

[2023-09-12T00:32:46.000Z]     raise MilvusException(

[2023-09-12T00:32:46.000Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: FlushChecker__rBTPAKdD)>

[2023-09-12T00:32:46.000Z]  (api_request.py:45)

[2023-09-12T00:32:46.000Z] [2023-09-12 00:25:11 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: FlushChecker__rBTPAKdD)> (api_request.py:46)
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-for-release-cron/detail/chaos-test-kafka-for-release-cron/7239/pipeline

log:
[artifacts-standalone-pod-failure-7239-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/12583611/artifacts-standalone-pod-failure-7239-pytest-logs.tar.gz)

[artifacts-standalone-pod-failure-7239-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/12583613/artifacts-standalone-pod-failure-7239-server-logs.tar.gz)

**Comment by yah01** [comment]
![image](https://github.com/milvus-io/milvus/assets/12216890/b9d57945-67d0-47fe-8158-8132203adad5)
@zhuwenxing how long it the timeout of client? I saw the load succeeded 2023/09/12 00:25:48.548, and the load started at 2023/09/12 00:23:09.945 +00:00. it takes 2.5 minutes to load, reasonable for me

**Comment by congqixia** [comment]
Also found lots of connection reset log, shall be related to #27014

**Comment by zhuwenxing** [comment]
> how long it the timeout of client? I saw the load succeeded 2023/09/12 00:25:48.548, and the load started at 2023/09/12 00:23:09.945 +00:00. it takes 2.5 minutes to load, reasonable for me

120s. But why is it reasonable to load a small collection in 2.5 minutes? It used to be only several seconds.

**Comment by zhuwenxing** [comment]
It reproduced again with 2.3.0-20230912-608ba462

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-for-release-cron/detail/chaos-test-kafka-for-release-cron/7266/pipeline
log:
[artifacts-standalone-pod-kill-7266-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/12593524/artifacts-standalone-pod-kill-7266-pytest-logs.tar.gz)
[artifacts-standalone-pod-kill-7266-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/12593526/artifacts-standalone-pod-kill-7266-server-logs.tar.gz)

**Comment by congqixia** [comment]
@zhuwenxing 
patch #27048 has been merged, could you please check whether this problem still persist?
