### ISSUE TITLE
[Bug]: [Nightly]Kafka run 3 times slower than pulsar with many cases failed

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#27080]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230913-2ed13ba6
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):   kafka 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Kafka run 3 times slower than pulsar with many cases failed.

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/496/pipeline/205/

error message:
```
[2023-09-13T22:48:55.516Z] [2023-09-13 18:00:22 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 120} (api_request.py:62)
[2023-09-13T22:48:55.516Z] [2023-09-13 18:00:43 - ERROR - pymilvus.decorators]: RPC error: [flush], <MilvusException: (code=1, message=attempt #0: channel=by-dev-rootcoord-dml_5_444236513286569848v0: channel not found: attempt #1: channel=by-dev-rootcoord-dml_5_444236513286569848v0: channel not found: attempt #2: channel=by-dev-rootcoord-dml_5_444236513286569848v0: channel not found: attempt #3: channel=by-dev-rootcoord-dml_5_444236513286569848v0: channel not found: attempt #4: channel=by-dev-rootcoord-dml_5_444236513286569848v0: channel not found: attempt #5: channel=by-dev-rootcoord-dml_5_444236513286569848v0: channel not found: attempt #6: channel=by-dev-rootcoord-dml_5_444236513286569848v0: channel not found: attempt #7: channel=by-dev-rootcoord-dml_5_444236513286569848v0: channel not found: attempt #8: channel=by-dev-rootcoord-dml_5_444236513286569848v0: channel not found: attempt #9: channel=by-dev-rootcoord-dml_5_444236513286569848v0: channel not found)>, <Time:{'RPC start': '2023-09-13 18:00:22.170881', 'RPC error': '2023-09-13 18:00:43.196294'}> (decorators.py:126)
[2023-09-13T22:48:55.516Z] [2023-09-13 18:00:43 - ERROR - ci_test]: Traceback (most recent call last):
[2023-09-13T22:48:55.516Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper
[2023-09-13T22:48:55.516Z]     res = func(*args, **_kwargs)
[2023-09-13T22:48:55.516Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request
[2023-09-13T22:48:55.516Z]     return func(*arg, **kwargs)
[2023-09-13T22:48:55.516Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 314, in flush
[2023-09-13T22:48:55.516Z]     conn.flush([self.name], timeout=timeout, **kwargs)
[2023-09-13T22:48:55.516Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 127, in handler
[2023-09-13T22:48:55.516Z]     raise e from e
[2023-09-13T22:48:55.516Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 123, in handler
[2023-09-13T22:48:55.516Z]     return func(*args, **kwargs)
[2023-09-13T22:48:55.516Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 162, in handler
[2023-09-13T22:48:55.516Z]     return func(self, *args, **kwargs)
[2023-09-13T22:48:55.516Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 102, in handler
[2023-09-13T22:48:55.516Z]     raise e from e
[2023-09-13T22:48:55.516Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 68, in handler
[2023-09-13T22:48:55.516Z]     return func(*args, **kwargs)
[2023-09-13T22:48:55.516Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 1283, in flush
[2023-09-13T22:48:55.516Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2023-09-13T22:48:55.516Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=attempt #0: channel=by-dev-rootcoord-dml_5_444236513286569848v0: channel not found: attempt #1: channel=by-dev-rootcoord-dml_5_444236513286569848v0: channel not found: attempt #2: channel=by-dev-rootcoord-dml_5_444236513286569848v0: channel not found: attempt #3: channel=by-dev-rootcoord-dml_5_444236513286569848v0: channel not found: attempt #4: channel=by-dev-rootcoord-dml_5_444236513286569848v0: channel not found: attempt #5: channel=by-dev-rootcoord-dml_5_444236513286569848v0: channel not found: attempt #6: channel=by-dev-rootcoord-dml_5_444236513286569848v0: channel not found: attempt #7: channel=by-dev-rootcoord-dml_5_444236513286569848v0: channel not found: attempt #8: channel=by-dev-rootcoord-dml_5_444236513286569848v0: channel not found: attempt #9: channel=by-dev-rootcoord-dml_5_444236513286569848v0: channel not found)>
[2023-09-13T22:48:55.516Z]  (api_request.py:45)
[2023-09-13T22:48:55.516Z] [2023-09-13 18:00:43 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=attempt #0: channel=by-dev-rootcoord-dml_5_444236513286569848v0: channel not found: attempt #1: channel=by-dev-rootcoord-dml_5_444236513286569848v0: channel not found: attempt #2: channel=by-dev-rootcoord-dml_5_444236513286569848v0: channel not found: attempt #3: c...... (api_request.py:46)
```

milvus panic log:
[artifacts-milvus-distributed-kafka-nightly-496-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/496/artifact/artifacts-milvus-distributed-kafka-nightly-496-pymilvus-e2e-logs.tar.gz)
```
2023-09-14T04:41:52.046145999+08:00 stderr F panic: runtime error: invalid memory address or nil pointer dereference
2023-09-14T04:41:52.046168135+08:00 stderr F
2023-09-14T04:41:52.046172458+08:00 stderr F runtime/debug.Stack()
2023-09-14T04:41:52.046175148+08:00 stderr F    /usr/local/go/src/runtime/debug/stack.go:24 +0x65
2023-09-14T04:41:52.046177587+08:00 stderr F golang.org/x/sync/singleflight.newPanicError({0x3f99ba0?, 0x6292450})
2023-09-14T04:41:52.04618007+08:00 stderr F     /go/pkg/mod/golang.org/x/sync@v0.1.0/singleflight/singleflight.go:35 +0x2c
2023-09-14T04:41:52.046185221+08:00 stderr F golang.org/x/sync/singleflight.(*Group).doCall.func2.1()
2023-09-14T04:41:52.046187619+08:00 stderr F    /go/pkg/mod/golang.org/x/sync@v0.1.0/singleflight/singleflight.go:184 +0x3b
2023-09-14T04:41:52.046191152+08:00 stderr F panic({0x3f99ba0, 0x6292450})
2023-09-14T04:41:52.046194022+08:00 stderr F    /usr/local/go/src/runtime/panic.go:884 +0x213
2023-09-14T04:41:52.046196723+08:00 stderr F github.com/milvus-io/milvus/internal/querynodev2/cluster.(*remoteWorker).LoadSegments(0xc001e76ba0, {0x4976000, 0xc002a65a70}, 0xc00245c2c0)
2023-09-14T04:41:52.046199755+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/querynodev2/cluster/worker.go:75 +0x2e1

```

### Expected Behavior

pass

**Comment by smellthemoon** [comment]
<img width="1026" alt="1" src="https://github.com/milvus-io/milvus/assets/64083300/212bb26d-0c1e-46f8-a744-5d646ada3d32">
panic because can't handle nil status.
related with #27040

**Comment by NicoYuan1986** [comment]
fixed. 
master-20230921-67a471e0
