### ISSUE TITLE
[Bug]: Flush an empty collection failed with error `attempt #0: channel=by-dev-rootcoord-dml_1_444265622409191135v0: channel not found` without any disruptions

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#27112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.0-20230914-bfe1afae
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):kafka    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2023-09-15T00:51:09.576Z] [2023-09-15 00:51:09 - INFO - ci_test]: all database: ['default'] (test_data_persistence.py:26)

[2023-09-15T00:51:31.449Z] [2023-09-15 00:51:31 - ERROR - pymilvus.decorators]: RPC error: [flush], <MilvusException: (code=1, message=attempt #0: channel=by-dev-rootcoord-dml_1_444265622409191135v0: channel not found: attempt #1: channel=by-dev-rootcoord-dml_1_444265622409191135v0: channel not found: attempt #2: channel=by-dev-rootcoord-dml_1_444265622409191135v0: channel not found: attempt #3: channel=by-dev-rootcoord-dml_1_444265622409191135v0: channel not found: attempt #4: channel=by-dev-rootcoord-dml_1_444265622409191135v0: channel not found: attempt #5: channel=by-dev-rootcoord-dml_1_444265622409191135v0: channel not found: attempt #6: channel=by-dev-rootcoord-dml_1_444265622409191135v0: channel not found: attempt #7: channel=by-dev-rootcoord-dml_1_444265622409191135v0: channel not found: attempt #8: channel=by-dev-rootcoord-dml_1_444265622409191135v0: channel not found: attempt #9: channel=by-dev-rootcoord-dml_1_444265622409191135v0: channel not found)>, <Time:{'RPC start': '2023-09-15 00:51:10.085754', 'RPC error': '2023-09-15 00:51:31.105128'}> (decorators.py:126)

[2023-09-15T00:51:31.449Z] [2023-09-15 00:51:31 - ERROR - ci_test]: Traceback (most recent call last):

[2023-09-15T00:51:31.449Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2023-09-15T00:51:31.449Z]     res = func(*args, **_kwargs)

[2023-09-15T00:51:31.449Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2023-09-15T00:51:31.449Z]     return func(*arg, **kwargs)

[2023-09-15T00:51:31.449Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 314, in flush

[2023-09-15T00:51:31.449Z]     conn.flush([self.name], timeout=timeout, **kwargs)

[2023-09-15T00:51:31.449Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 127, in handler

[2023-09-15T00:51:31.449Z]     raise e from e

[2023-09-15T00:51:31.449Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 123, in handler

[2023-09-15T00:51:31.449Z]     return func(*args, **kwargs)

[2023-09-15T00:51:31.449Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 162, in handler

[2023-09-15T00:51:31.449Z]     return func(self, *args, **kwargs)

[2023-09-15T00:51:31.449Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 102, in handler

[2023-09-15T00:51:31.449Z]     raise e from e

[2023-09-15T00:51:31.449Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 68, in handler

[2023-09-15T00:51:31.449Z]     return func(*args, **kwargs)

[2023-09-15T00:51:31.449Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 1283, in flush

[2023-09-15T00:51:31.449Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2023-09-15T00:51:31.449Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=attempt #0: channel=by-dev-rootcoord-dml_1_444265622409191135v0: channel not found: attempt #1: channel=by-dev-rootcoord-dml_1_444265622409191135v0: channel not found: attempt #2: channel=by-dev-rootcoord-dml_1_444265622409191135v0: channel not found: attempt #3: channel=by-dev-rootcoord-dml_1_444265622409191135v0: channel not found: attempt #4: channel=by-dev-rootcoord-dml_1_444265622409191135v0: channel not found: attempt #5: channel=by-dev-rootcoord-dml_1_444265622409191135v0: channel not found: attempt #6: channel=by-dev-rootcoord-dml_1_444265622409191135v0: channel not found: attempt #7: channel=by-dev-rootcoord-dml_1_444265622409191135v0: channel not found: attempt #8: channel=by-dev-rootcoord-dml_1_444265622409191135v0: channel not found: attempt #9: channel=by-dev-rootcoord-dml_1_444265622409191135v0: channel not found)>

[2023-09-15T00:51:31.450Z]  (api_request.py:45)
```

### Expected Behavior

Although it doesn't make much sense to flush an empty collection, it shouldn't report errors

### Steps To Reproduce

```markdown
create collection(no data insert)
flush
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-for-release-cron/detail/chaos-test-kafka-for-release-cron/7382/pipeline

log:
[artifacts-etcd-leader-pod-failure-7382-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/12614966/artifacts-etcd-leader-pod-failure-7382-server-logs.tar.gz)
[artifacts-etcd-leader-pod-failure-7382-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/12614967/artifacts-etcd-leader-pod-failure-7382-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
It works well with the previous image master-20230905-548c82ec

when flushing an empty collection, almost no time cost
```
[2023-09-15T02:27:46.498Z] [2023-09-15 02:27:46 - INFO - ci_test]: [test][2023-09-15T02:27:46Z] [0.00517917s] Hello_Milvus flush -> None (wrapper.py:30)
[2023-09-15T02:27:46.498Z] [2023-09-15 02:27:46 - INFO - ci_test]: assert create collection: 0.5141146183013916, init_entities: 0 (test_data_persistence.py:38)
```


```

[2023-09-15T02:27:45.939Z] [2023-09-15 02:27:45 - INFO - ci_test]: all database: ['default'] (test_data_persistence.py:26)

[2023-09-15T02:27:46.498Z] [2023-09-15 02:27:46 - INFO - ci_test]: [test][2023-09-15T02:27:46Z] [0.00517917s] Hello_Milvus flush -> None (wrapper.py:30)

[2023-09-15T02:27:46.498Z] [2023-09-15 02:27:46 - INFO - ci_test]: assert create collection: 0.5141146183013916, init_entities: 0 (test_data_persistence.py:38)

[2023-09-15T02:27:47.058Z] [2023-09-15 02:27:46 - INFO - ci_test]: [test][2023-09-15T02:27:46Z] [0.54262393s] Hello_Milvus insert -> (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 444267198361632771, success count: 2000, err count: 0) (wrapper.py:30)

[2023-09-15T02:27:47.058Z] [2023-09-15 02:27:46 - INFO - ci_test]: assert insert: 0.5428431034088135 (test_data_persistence.py:45)

[2023-09-15T02:27:51.220Z] [2023-09-15 02:27:50 - INFO - ci_test]: [test][2023-09-15T02:27:46Z] [3.53125652s] Hello_Milvus flush -> None (wrapper.py:30)

[2023-09-15T02:27:51.220Z] [2023-09-15 02:27:50 - INFO - ci_test]: [test][2023-09-15T02:27:50Z] [0.00437965s] Hello_Milvus flush -> None (wrapper.py:30)

[2023-09-15T02:27:51.220Z] [2023-09-15 02:27:50 - INFO - ci_test]: [test][2023-09-15T02:27:50Z] [0.00409660s] Hello_Milvus flush -> None (wrapper.py:30)

[2023-09-15T02:27:51.220Z] [2023-09-15 02:27:50 - INFO - ci_test]: assert flush: 3.5382614135742188, entities: 2000 (test_data_persistence.py:55)

[2023-09-15T02:27:51.220Z] [2023-09-15 02:27:50 - INFO - ci_test]: collection {name} does not have index, create index for it (test_data_persistence.py:61)

[2023-09-15T02:27:53.732Z] [2023-09-15 02:27:53 - INFO - ci_test]: [test][2023-09-15T02:27:50Z] [3.03210886s] Hello_Milvus create_index -> Status(code=0, message=) (wrapper.py:30)

[2023-09-15T02:27:54.296Z] [2023-09-15 02:27:54 - INFO - ci_test]: [test][2023-09-15T02:27:53Z] [0.51309370s] Hello_Milvus create_index -> Status(code=0, message=) (wrapper.py:30)

[2023-09-15T02:27:54.296Z] [2023-09-15 02:27:54 - INFO - ci_test]: assert index: 3.545618772506714 (test_data_persistence.py:70)

[2023-09-15T02:27:54.296Z] [2023-09-15 02:27:54 - INFO - ci_test]: index info: [{'collection': 'Hello_Milvus', 'field': 'varchar', 'index_name': 'test_F9b7yYx4', 'index_param': {}}, {'collection': 'Hello_Milvus', 'field': 'float_vector', 'index_name': 'test_EMoBY0Ui', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}] (test_data_persistence.py:74)

[2023-09-15T02:27:58.457Z] [2023-09-15 02:27:58 - INFO - ci_test]: [test][2023-09-15T02:27:54Z] [4.04666294s] Hello_Milvus load -> None (wrapper.py:30)

[2023-09-15T02:27:58.457Z] [2023-09-15 02:27:58 - INFO - ci_test]: [test][2023-09-15T02:27:58Z] [0.39865014s] Hello_Milvus search -> <pymilvus.orm.search.SearchResult object at 0x7efdf07ebd90> (wrapper.py:30)

[2023-09-15T02:27:58.457Z] [2023-09-15 02:27:58 - INFO - ci_test]: assert search: 0.398831844329834 (test_data_persistence.py:86)

[2023-09-15T02:27:59.821Z] [2023-09-15 02:27:59 - INFO - ci_test]: [test][2023-09-15T02:27:58Z] [1.01389616s] Hello_Milvus release -> None (wrapper.py:30)

[2023-09-15T02:28:00.380Z] [2023-09-15 02:28:00 - INFO - ci_test]: [test][2023-09-15T02:27:59Z] [0.48815827s] Hello_Milvus insert -> (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 444267201821933570, success count: 2000, err count: 0) (wrapper.py:30)

[2023-09-15T02:28:03.642Z] [2023-09-15 02:28:03 - INFO - ci_test]: [test][2023-09-15T02:28:00Z] [3.52670136s] Hello_Milvus flush -> None (wrapper.py:30)

[2023-09-15T02:28:03.642Z] [2023-09-15 02:28:03 - INFO - ci_test]: assert entities: 4000 (test_data_persistence.py:93)

[2023-09-15T02:28:08.882Z] [2023-09-15 02:28:08 - INFO - ci_test]: [test][2023-09-15T02:28:03Z] [4.56954063s] Hello_Milvus load -> None (wrapper.py:30)

[2023-09-15T02:28:08.882Z] [2023-09-15 02:28:08 - INFO - ci_test]: assert load: 4.56969690322876 (test_data_persistence.py:99)

[2023-09-15T02:28:08.883Z] [2023-09-15 02:28:08 - INFO - ci_test]: [test][2023-09-15T02:28:08Z] [0.26350259s] Hello_Milvus search -> <pymilvus.orm.search.SearchResult object at 0x7efdf07c3df0> (wrapper.py:30)

[2023-09-15T02:28:08.883Z] [2023-09-15 02:28:08 - INFO - ci_test]: assert search: 0.2636845111846924 (test_data_persistence.py:106)

[2023-09-15T02:28:08.883Z] [2023-09-15 02:28:08 - INFO - ci_test]: [test][2023-09-15T02:28:08Z] [0.39928809s] Hello_Milvus query -> [{'int64': 1001}, {'int64': 1201}] (wrapper.py:30)

[2023-09-15T02:28:08.883Z] [2023-09-15 02:28:08 - INFO - ci_test]: assert query result 2: 0.3994441032409668 (test_data_persistence.py:113)

[2023-09-15T02:28:09.138Z] PASSED
```

**Comment by zhuwenxing** [comment]
/assign @bigsheeper 
PTAL

**Comment by zhuwenxing** [comment]
This happened only in Kafka mq

**Comment by bigsheeper** [comment]
[2023/09/15 00:51:31.987 +00:00] [WARN] [kafka/kafka_consumer.go:146] ["consume msg failed"] [topic=by-dev-rootcoord-dml_0] [groupID=datanode-12-by-dev-rootcoord-dml_0_444265622408790929v0-true] [error="Local: Timed out"]

**Comment by NicoYuan1986** [comment]
reproduced on pulsar.
```
[2023-09-15 03:17:24 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 120} (api_request.py:62)
[2023-09-15 03:17:45 - ERROR - pymilvus.decorators]: RPC error: [flush], <MilvusException: (code=1, message=attempt #0: channel=by-dev-rootcoord-dml_15_444267196653005902v0: channel not found: attempt #1: channel=by-dev-rootcoord-dml_15_444267196653005902v0: channel not found: attempt #2: channel=by-dev-rootcoord-dml_15_444267196653005902v0: channel not found: attempt #3: channel=by-dev-rootcoord-dml_15_444267196653005902v0: channel not found: attempt #4: channel=by-dev-rootcoord-dml_15_444267196653005902v0: channel not found: attempt #5: channel=by-dev-rootcoord-dml_15_444267196653005902v0: channel not found: attempt #6: channel=by-dev-rootcoord-dml_15_444267196653005902v0: channel not found: attempt #7: channel=by-dev-rootcoord-dml_15_444267196653005902v0: channel not found: attempt #8: channel=by-dev-rootcoord-dml_15_444267196653005902v0: channel not found: attempt #9: channel=by-dev-rootcoord-dml_15_444267196653005902v0: channel not found)>, <Time:{'RPC start': '2023-09-15 03:17:24.614328', 'RPC error': '2023-09-15 03:17:45.640136'}> (decorators.py:126)
[2023-09-15 03:17:45 - ERROR - ci_test]: Traceback (most recent call last):
  File "/root/python_client/utils/api_request.py", line 32, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/root/python_client/utils/api_request.py", line 63, in api_request
    return func(*arg, **kwargs)
  File "/root/nico/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 314, in flush
    conn.flush([self.name], timeout=timeout, **kwargs)
  File "/root/nico/lib/python3.8/site-packages/pymilvus/decorators.py", line 127, in handler
    raise e from e
  File "/root/nico/lib/python3.8/site-packages/pymilvus/decorators.py", line 123, in handler
    return func(*args, **kwargs)
  File "/root/nico/lib/python3.8/site-packages/pymilvus/decorators.py", line 162, in handler
    return func(self, *args, **kwargs)
  File "/root/nico/lib/python3.8/site-packages/pymilvus/decorators.py", line 102, in handler
    raise e from e
  File "/root/nico/lib/python3.8/site-packages/pymilvus/decorators.py", line 68, in handler
    return func(*args, **kwargs)
  File "/root/nico/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 1283, in flush
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=attempt #0: channel=by-dev-rootcoord-dml_15_444267196653005902v0: channel not found: attempt #1: channel=by-dev-rootcoord-dml_15_444267196653005902v0: channel not found: attempt #2: channel=by-dev-rootcoord-dml_15_444267196653005902v0: channel not found: attempt #3: channel=by-dev-rootcoord-dml_15_444267196653005902v0: channel not found: attempt #4: channel=by-dev-rootcoord-dml_15_444267196653005902v0: channel not found: attempt #5: channel=by-dev-rootcoord-dml_15_444267196653005902v0: channel not found: attempt #6: channel=by-dev-rootcoord-dml_15_444267196653005902v0: channel not found: attempt #7: channel=by-dev-rootcoord-dml_15_444267196653005902v0: channel not found: attempt #8: channel=by-dev-rootcoord-dml_15_444267196653005902v0: channel not found: attempt #9: channel=by-dev-rootcoord-dml_15_444267196653005902v0: channel not found)>
 (api_request.py:45)
[2023-09-15 03:17:45 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=attempt #0: channel=by-dev-rootcoord-dml_15_444267196653005902v0: channel not found: attempt #1: channel=by-dev-rootcoord-dml_15_444267196653005902v0: channel not found: attempt #2: channel=by-dev-rootcoord-dml_15_444267196653005902v0: channel not found: attempt #3...... (api_request.py:46)
```

log:
https://grafana-devops.zilliz.cc/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bpod%3D%5C%22verify-231-dfeid-milvus-querynode-5c6f485f58-hrm7p%5C%22%7D%22%7D%5D,%22range%22:%7B%22from%22:%221694745253000%22,%22to%22:%221694749974000%22%7D%7D

**Comment by bigsheeper** [comment]
> by-dev-rootcoord-dml_15_444267196653005902v0

seems pulsar is not stable
![image](https://github.com/milvus-io/milvus/assets/42060877/19e9dc97-b697-4d70-961b-65b59144bfc2)

**Comment by NicoYuan1986** [comment]
reproduce on 2.3.0-20230915-3f550cee

```
[2023-09-15 09:04:18 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [      int64   float varchar                         json_field                                       float_vector
0         0     0.0       0        {'number': 0, 'float': 0.0}  [0.08947461893871372, 0.06943331348244054, 0.0...
1         1     1.0       1        {'number': 1, 'float': 1.0}  [0.0423......, kwargs: {'timeout': 120} (api_request.py:62)
[2023-09-15 09:04:18 - DEBUG - ci_test]: (api_response) : (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 444273435160608775, success count: 2000, err count: 0)  (api_request.py:37)
[2023-09-15 09:04:18 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 120} (api_request.py:62)
[2023-09-15 09:04:39 - ERROR - pymilvus.decorators]: RPC error: [flush], <MilvusException: (code=1, message=attempt #0: channel=by-dev-rootcoord-dml_8_444273134549160614v0: channel not found: attempt #1: channel=by-dev-rootcoord-dml_8_444273134549160614v0: channel not found: attempt #2: channel=by-dev-rootcoord-dml_8_444273134549160614v0: channel not found: attempt #3: channel=by-dev-rootcoord-dml_8_444273134549160614v0: channel not found: attempt #4: channel=by-dev-rootcoord-dml_8_444273134549160614v0: channel not found: attempt #5: channel=by-dev-rootcoord-dml_8_444273134549160614v0: channel not found: attempt #6: channel=by-dev-rootcoord-dml_8_444273134549160614v0: channel not found: attempt #7: channel=by-dev-rootcoord-dml_8_444273134549160614v0: channel not found: attempt #8: channel=by-dev-rootcoord-dml_8_444273134549160614v0: channel not found: attempt #9: channel=by-dev-rootcoord-dml_8_444273134549160614v0: channel not found)>, <Time:{'RPC start': '2023-09-15 09:04:18.693364', 'RPC error': '2023-09-15 09:04:39.718915'}> (decorators.py:126)
[2023-09-15 09:04:39 - ERROR - ci_test]: Traceback (most recent call last):
  File "/root/python_client/utils/api_request.py", line 32, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/root/python_client/utils/api_request.py", line 63, in api_request
    return func(*arg, **kwargs)
  File "/root/nico/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 314, in flush
    conn.flush([self.name], timeout=timeout, **kwargs)
  File "/root/nico/lib/python3.8/site-packages/pymilvus/decorators.py", line 127, in handler
    raise e from e
  File "/root/nico/lib/python3.8/site-packages/pymilvus/decorators.py", line 123, in handler
    return func(*args, **kwargs)
  File "/root/nico/lib/python3.8/site-packages/pymilvus/decorators.py", line 162, in handler
    return func(self, *args, **kwargs)
  File "/root/nico/lib/python3.8/site-packages/pymilvus/decorators.py", line 102, in handler
    raise e from e
  File "/root/nico/lib/python3.8/site-packages/pymilvus/decorators.py", line 68, in handler
    return func(*args, **kwargs)
  File "/root/nico/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 1283, in flush
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=attempt #0: channel=by-dev-rootcoord-dml_8_444273134549160614v0: channel not found: attempt #1: channel=by-dev-rootcoord-dml_8_444273134549160614v0: channel not found: attempt #2: channel=by-dev-rootcoord-dml_8_444273134549160614v0: channel not found: attempt #3: channel=by-dev-rootcoord-dml_8_444273134549160614v0: channel not found: attempt #4: channel=by-dev-rootcoord-dml_8_444273134549160614v0: channel not found: attempt #5: channel=by-dev-rootcoord-dml_8_444273134549160614v0: channel not found: attempt #6: channel=by-dev-rootcoord-dml_8_444273134549160614v0: channel not found: attempt #7: channel=by-dev-rootcoord-dml_8_444273134549160614v0: channel not found: attempt #8: channel=by-dev-rootcoord-dml_8_444273134549160614v0: channel not found: attempt #9: channel=by-dev-rootcoord-dml_8_444273134549160614v0: channel not found)>
 (api_request.py:45)
[2023-09-15 09:04:39 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=attempt #0: channel=by-dev-rootcoord-dml_8_444273134549160614v0: channel not found: attempt #1: channel=by-dev-rootcoord-dml_8_444273134549160614v0: channel not found: attempt #2: channel=by-dev-rootcoord-dml_8_444273134549160614v0: channel not found: attempt #3: c...... (api_request.py:46)
```

https://grafana-devops.zilliz.cc/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bpod%3D%5C%22verify-231p-rnwwb-milvus-querynode-65554b868b-s6kx2%5C%22%7D%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D

**Comment by bigsheeper** [comment]
![5YQsDfDqD1](https://github.com/milvus-io/milvus/assets/42060877/f488cc50-c1fe-4900-bbd9-a2d7e556b6c2)
close slowly

**Comment by NicoYuan1986** [comment]
Reproduce many times.
1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/500/pipeline/205/
2. log: [artifacts-milvus-distributed-kafka-nightly-500-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/500/artifact/artifacts-milvus-distributed-kafka-nightly-500-pymilvus-e2e-logs.tar.gz)

**Comment by bigsheeper** [comment]
working on it

**Comment by bigsheeper** [comment]
> Reproduce many times on nightly every day.
> 
> 1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/500/pipeline/205/
> 2. log: [artifacts-milvus-distributed-kafka-nightly-500-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/500/artifact/artifacts-milvus-distributed-kafka-nightly-500-pymilvus-e2e-logs.tar.gz)

same reason, nightly ci has many collections, so timeout(120s) cannot cover it:
```
 [WARN] [kafka/kafka_consumer.go:146] ["consume msg failed"] [topic=by-dev-rootcoord-dml_3] [groupID=datanode-6-by-dev-rootcoord-dml_3_444327108859178078v0-true] [error="Local: Timed out"]
```

**Comment by NicoYuan1986** [comment]
not reproduced.
