### ISSUE TITLE
[Bug]: milvus-backup  restore failed

### ISSUE THREAD

**Issue by suchenghui** [milvus-io/milvus#27132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.0
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

[root@tc-bj-yw-dba-manager milvus_backup]# ./milvus-backup restore -n backup_table_one -s _recover
[2023/09/15 17:22:29.516 +08:00] [INFO] [logutil/logutil.go:165] ["Log directory"] [configDir=]
[2023/09/15 17:22:29.516 +08:00] [INFO] [logutil/logutil.go:166] ["Set log file to "] [path=logs/backup.log]
[2023/09/15 17:22:29.516 +08:00] [INFO] [cmd/restore.go:39] ["restore cmd input args"] [args="[]"]
[2023/09/15 17:22:29.516 +08:00] [INFO] [core/backup_impl_restore_backup.go:25] ["receive RestoreBackupRequest"] [requestId=6477050a-53a9-11ee-8aee-5254000770cb] [backupName=backup_table_one] [collections="[]"] [CollectionSuffix=_recover] [CollectionRenames={}] [async=false] [bucketName=] [path=] [databaseCollections=]
[2023/09/15 17:22:29.516 +08:00] [INFO] [core/backup_context.go:183] ["receive GetBackupRequest"] [requestId=64770ad1-53a9-11ee-8aee-5254000770cb] [backupName=backup_table_one] [backupId=] [bucketName=] [path=]
[2023/09/15 17:22:29.581 +08:00] [INFO] [storage/minio_chunk_manager.go:124] ["minio chunk manager init success."] [bucketname=cos-prod-tc-ops-milvus-1302248489] [root=milvus_data]
[2023/09/15 17:22:29.809 +08:00] [INFO] [core/backup_context.go:248] ["finish GetBackupRequest"] [requestId=64770ad1-53a9-11ee-8aee-5254000770cb] [backupName=backup_table_one] [backupId=] [bucketName=] [path=] [resp="requestId:\"64770ad1-53a9-11ee-8aee-5254000770cb\" msg:\"success\" data:<id:\"abf5995b-530a-11ee-a925-5254003a3f90\" state_code:BACKUP_SUCCESS start_time:1694701579668 end_time:1694701581100 name:\"backup_table_one\" backup_timestamp:1694701579668 collection_backups:<collection_id:443867104103340970 db_name:\"kg_test_01\" collection_name:\"spark_doc_kb_knowledge_base\" schema:<name:\"spark_doc_kb_knowledge_base\" fields:<fieldID:100 name:\"id\" is_primary_key:true description:\"Unique ID\" data_type:VarChar type_params:<key:\"max_length\" value:\"65535\" > > fields:<fieldID:101 name:\"doc_id\" description:\"Source document ID\" data_type:VarChar type_params:<key:\"max_length\" value:\"65535\" > > fields:<fieldID:102 name:\"text\" description:\"The embedding vector\" data_type:VarChar type_params:<key:\"max_length\" value:\"65535\" > > fields:<fieldID:103 name:\"embedding\" description:\"The embedding vector\" data_type:FloatVector type_params:<key:\"dim\" value:\"1536\" > > fields:<fieldID:104 name:\"node\" description:\"The node content\" data_type:VarChar type_params:<key:\"max_length\" value:\"65535\" > > > shards_num:1 partition_backups:<partition_id:443867104103340971 partition_name:\"_default\" collection_id:443867104103340970 segment_backups:<segment_id:443867104103341003 collection_id:443867104103340970 partition_id:443867104103340971 num_of_rows:157 binlogs:<binlogs:<log_path:\"milvus_data/insert_log/443867104103340970/443867104103340971/443867104103341003/0/443867104103344237\" log_size:724 > binlogs:<log_path:\"milvus_data/insert_log/443867104103340970/443867104103340971/443867104103341003/0/443867104103347445\" log_size:544 > > binlogs:<fieldID:1 binlogs:<log_path:\"milvus_data/insert_log/443867104103340970/443867104103340971/443867104103341003/1/443867104103344238\" log_size:510 > binlogs:<log_path:\"milvus_data/insert_log/443867104103340970/443867104103340971/443867104103341003/1/443867104103347446\" log_size:471 > > binlogs:<fieldID:100 binlogs:<log_path:\"milvus_data/insert_log/443867104103340970/443867104103340971/443867104103341003/100/443867104103344232\" log_size:3056 > binlogs:<log_path:\"milvus_data/insert_log/443867104103340970/443867104103340971/443867104103341003/100/443867104103347440\" log_size:1986 > > binlogs:<fieldID:101 binlogs:<log_path:\"milvus_data/insert_log/443867104103340970/443867104103340971/443867104103341003/101/443867104103344233\" log_size:816 > binlogs:<log_path:\"milvus_data/insert_log/443867104103340970/443867104103340971/443867104103341003/101/443867104103347441\" log_size:640 > > binlogs:<fieldID:102 binlogs:<log_path:\"milvus_data/insert_log/443867104103340970/443867104103340971/443867104103341003/102/443867104103344234\" log_size:114742 > binlogs:<log_path:\"milvus_data/insert_log/443867104103340970/443867104103340971/443867104103341003/102/443867104103347442\" log_size:44052 > > binlogs:<fieldID:103 binlogs:<log_path:\"milvus_data/insert_log/443867104103340970/443867104103340971/443867104103341003/103/443867104103344235\" log_size:743931 > binlogs:<log_path:\"milvus_data/insert_log/443867104103340970/443867104103340971/443867104103341003/103/443867104103347443\" log_size:221590 > > binlogs:<fieldID:104 binlogs:<log_path:\"milvus_data/insert_log/443867104103340970/443867104103340971/443867104103341003/104/443867104103344236\" log_size:13571 > binlogs:<log_path:\"milvus_data/insert_log/443867104103340970/443867104103340971/443867104103341003/104/443867104103347444\" log_size:7191 > > deltalogs:<> size:1153824 > size:1153824 load_state:\"Loaded\" > backup_timestamp:444255850987520 size:1153824 has_index:true index_infos:<field_name:\"embedding\" index_name:\"_default_idx_103\" index_type:\"HNSW\" params:<key:\"index_type\" value:\"HNSW\" > params:<key:\"metric_type\" value:\"IP\" > params:<key:\"params\" value:\"{\\\"M\\\":8,\\\"efConstruction\\\":64}\" > > load_state:\"Loaded\" backup_physical_timestamp:1694701580 > size:1153824 milvus_version:\"v2.3.0-dev\" > "]
[2023/09/15 17:22:29.810 +08:00] [INFO] [core/backup_impl_restore_backup.go:164] ["Collections to restore"] [collection_num=1]
[2023/09/15 17:22:29.851 +08:00] [ERROR] [core/backup_context.go:74] ["failed to connect to milvus"] [error="this version of sdk is incompatible with server, please downgrade your sdk or upgrade your server"] [errorVerbose="this version of sdk is incompatible with server, please downgrade your sdk or upgrade your server\n(1) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus-sdk-go/v2/client.(*GrpcClient).connectInternal\n  | \t/home/runner/go/pkg/mod/github.com/wayblink/milvus-sdk-go/v2@v2.2.20/client/collection.go:84\n  | github.com/milvus-io/milvus-sdk-go/v2/client.(*GrpcClient).connect\n  | \t/home/runner/go/pkg/mod/github.com/wayblink/milvus-sdk-go/v2@v2.2.20/client/collection.go:54\n  | github.com/milvus-io/milvus-sdk-go/v2/client.NewClient\n  | \t/home/runner/go/pkg/mod/github.com/wayblink/milvus-sdk-go/v2@v2.2.20/client/client.go:249\n  | github.com/milvus-io/milvus-sdk-go/v2/client.NewDefaultGrpcClientWithAuth\n  | \t/home/runner/go/pkg/mod/github.com/wayblink/milvus-sdk-go/v2@v2.2.20/client/client.go:304\n  | github.com/zilliztech/milvus-backup/core.CreateMilvusClient\n  | \t/home/runner/work/milvus-backup/milvus-backup/core/backup_context.go:63\n  | github.com/zilliztech/milvus-backup/core.(*BackupContext).getMilvusClient\n  | \t/home/runner/work/milvus-backup/milvus-backup/core/backup_context.go:157\n  | github.com/zilliztech/milvus-backup/core.(*BackupContext).RestoreBackup\n  | \t/home/runner/work/milvus-backup/milvus-backup/core/backup_impl_restore_backup.go:207\n  | github.com/zilliztech/milvus-backup/cmd.glob..func5\n  | \t/home/runner/work/milvus-backup/milvus-backup/cmd/restore.go:70\n  | github.com/spf13/cobra.(*Command).execute\n  | \t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876\n  | github.com/spf13/cobra.(*Command).ExecuteC\n  | \t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990\n  | github.com/spf13/cobra.(*Command).Execute\n  | \t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918\n  | github.com/zilliztech/milvus-backup/cmd.Execute\n  | \t/home/runner/work/milvus-backup/milvus-backup/cmd/root.go:24\n  | main.main\n  | \t/home/runner/work/milvus-backup/milvus-backup/main.go:17\n  | runtime.main\n  | \t/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/proc.go:250\n  | runtime.goexit\n  | \t/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/asm_amd64.s:1571\nWraps: (2) this version of sdk is incompatible with server, please downgrade your sdk or upgrade your server\nError types: (1) *withstack.withStack (2) *errutil.leafError"] [stack="github.com/zilliztech/milvus-backup/core.CreateMilvusClient\n\t/home/runner/work/milvus-backup/milvus-backup/core/backup_context.go:74\ngithub.com/zilliztech/milvus-backup/core.(*BackupContext).getMilvusClient\n\t/home/runner/work/milvus-backup/milvus-backup/core/backup_context.go:157\ngithub.com/zilliztech/milvus-backup/core.(*BackupContext).RestoreBackup\n\t/home/runner/work/milvus-backup/milvus-backup/core/backup_impl_restore_backup.go:207\ngithub.com/zilliztech/milvus-backup/cmd.glob..func5\n\t/home/runner/work/milvus-backup/milvus-backup/cmd/restore.go:70\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918\ngithub.com/zilliztech/milvus-backup/cmd.Execute\n\t/home/runner/work/milvus-backup/milvus-backup/cmd/root.go:24\nmain.main\n\t/home/runner/work/milvus-backup/milvus-backup/main.go:17\nruntime.main\n\t/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/proc.go:250"]
[2023/09/15 17:22:29.851 +08:00] [ERROR] [core/backup_context.go:159] ["failed to initial milvus client"] [error="this version of sdk is incompatible with server, please downgrade your sdk or upgrade your server"] [errorVerbose="this version of sdk is incompatible with server, please downgrade your sdk or upgrade your server\n(1) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus-sdk-go/v2/client.(*GrpcClient).connectInternal\n  | \t/home/runner/go/pkg/mod/github.com/wayblink/milvus-sdk-go/v2@v2.2.20/client/collection.go:84\n  | github.com/milvus-io/milvus-sdk-go/v2/client.(*GrpcClient).connect\n  | \t/home/runner/go/pkg/mod/github.com/wayblink/milvus-sdk-go/v2@v2.2.20/client/collection.go:54\n  | github.com/milvus-io/milvus-sdk-go/v2/client.NewClient\n  | \t/home/runner/go/pkg/mod/github.com/wayblink/milvus-sdk-go/v2@v2.2.20/client/client.go:249\n  | github.com/milvus-io/milvus-sdk-go/v2/client.NewDefaultGrpcClientWithAuth\n  | \t/home/runner/go/pkg/mod/github.com/wayblink/milvus-sdk-go/v2@v2.2.20/client/client.go:304\n  | github.com/zilliztech/milvus-backup/core.CreateMilvusClient\n  | \t/home/runner/work/milvus-backup/milvus-backup/core/backup_context.go:63\n  | github.com/zilliztech/milvus-backup/core.(*BackupContext).getMilvusClient\n  | \t/home/runner/work/milvus-backup/milvus-backup/core/backup_context.go:157\n  | github.com/zilliztech/milvus-backup/core.(*BackupContext).RestoreBackup\n  | \t/home/runner/work/milvus-backup/milvus-backup/core/backup_impl_restore_backup.go:207\n  | github.com/zilliztech/milvus-backup/cmd.glob..func5\n  | \t/home/runner/work/milvus-backup/milvus-backup/cmd/restore.go:70\n  | github.com/spf13/cobra.(*Command).execute\n  | \t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876\n  | github.com/spf13/cobra.(*Command).ExecuteC\n  | \t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990\n  | github.com/spf13/cobra.(*Command).Execute\n  | \t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918\n  | github.com/zilliztech/milvus-backup/cmd.Execute\n  | \t/home/runner/work/milvus-backup/milvus-backup/cmd/root.go:24\n  | main.main\n  | \t/home/runner/work/milvus-backup/milvus-backup/main.go:17\n  | runtime.main\n  | \t/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/proc.go:250\n  | runtime.goexit\n  | \t/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/asm_amd64.s:1571\nWraps: (2) this version of sdk is incompatible with server, please downgrade your sdk or upgrade your server\nError types: (1) *withstack.withStack (2) *errutil.leafError"] [stack="github.com/zilliztech/milvus-backup/core.(*BackupContext).getMilvusClient\n\t/home/runner/work/milvus-backup/milvus-backup/core/backup_context.go:159\ngithub.com/zilliztech/milvus-backup/core.(*BackupContext).RestoreBackup\n\t/home/runner/work/milvus-backup/milvus-backup/core/backup_impl_restore_backup.go:207\ngithub.com/zilliztech/milvus-backup/cmd.glob..func5\n\t/home/runner/work/milvus-backup/milvus-backup/cmd/restore.go:70\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918\ngithub.com/zilliztech/milvus-backup/cmd.Execute\n\t/home/runner/work/milvus-backup/milvus-backup/cmd/root.go:24\nmain.main\n\t/home/runner/work/milvus-backup/milvus-backup/main.go:17\nruntime.main\n\t/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/proc.go:250"]
panic: this version of sdk is incompatible with server, please downgrade your sdk or upgrade your server

goroutine 1 [running]:
github.com/zilliztech/milvus-backup/core.(*BackupContext).getMilvusClient(0xc00016d8c0)
        /home/runner/work/milvus-backup/milvus-backup/core/backup_context.go:160 +0x27a
github.com/zilliztech/milvus-backup/core.(*BackupContext).RestoreBackup(0xc00016d8c0, {0x129f968?, 0xc000128000}, 0xc0005b3ad8)
        /home/runner/work/milvus-backup/milvus-backup/core/backup_impl_restore_backup.go:207 +0x20f0
github.com/zilliztech/milvus-backup/cmd.glob..func5(0x220d1a0?, {0xc000519240, 0x0, 0x4})
        /home/runner/work/milvus-backup/milvus-backup/cmd/restore.go:70 +0x60f
github.com/spf13/cobra.(*Command).execute(0x220d1a0, {0xc000519200, 0x4, 0x4})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0x220d420)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/zilliztech/milvus-backup/cmd.Execute()
        /home/runner/work/milvus-backup/milvus-backup/cmd/root.go:24 +0x71
main.main()
        /home/runner/work/milvus-backup/milvus-backup/main.go:17 +0x17
[root@tc-bj-yw-dba-manager milvus_backup]# 

### Steps To Reproduce

```markdown
wget https://github.com/zilliztech/milvus-backup/releases/download/v0.3.3/milvus-backup_Linux_x86_64.tar.gz
[root@tc-bj-yw-dba-manager milvus_backup]# ./milvus-backup version                                
Version: 1.0-beta

./milvus-backup restore -n backup_table_one -s _recover
```

### Milvus Log

[root@tc-bj-yw-dba-manager milvus_backup]# ./milvus-backup restore -n backup_table_one -s _recover
[2023/09/15 17:22:29.516 +08:00] [INFO] [logutil/logutil.go:165] ["Log directory"] [configDir=]
[2023/09/15 17:22:29.516 +08:00] [INFO] [logutil/logutil.go:166] ["Set log file to "] [path=logs/backup.log]
[2023/09/15 17:22:29.516 +08:00] [INFO] [cmd/restore.go:39] ["restore cmd input args"] [args="[]"]
[2023/09/15 17:22:29.516 +08:00] [INFO] [core/backup_impl_restore_backup.go:25] ["receive RestoreBackupRequest"] [requestId=6477050a-53a9-11ee-8aee-5254000770cb] [backupName=backup_table_one] [collections="[]"] [CollectionSuffix=_recover] [CollectionRenames={}] [async=false] [bucketName=] [path=] [databaseCollections=]
[2023/09/15 17:22:29.516 +08:00] [INFO] [core/backup_context.go:183] ["receive GetBackupRequest"] [requestId=64770ad1-53a9-11ee-8aee-5254000770cb] [backupName=backup_table_one] [backupId=] [bucketName=] [path=]
[2023/09/15 17:22:29.581 +08:00] [INFO] [storage/minio_chunk_manager.go:124] ["minio chunk manager init success."] [bucketname=cos-prod-tc-ops-milvus-1302248489] [root=milvus_data]
[2023/09/15 17:22:29.809 +08:00] [INFO] [core/backup_context.go:248] ["finish GetBackupRequest"] [requestId=64770ad1-53a9-11ee-8aee-5254000770cb] [backupName=backup_table_one] [backupId=] [bucketName=] [path=] [resp="requestId:\"64770ad1-53a9-11ee-8aee-5254000770cb\" msg:\"success\" data:<id:\"abf5995b-530a-11ee-a925-5254003a3f90\" state_code:BACKUP_SUCCESS start_time:1694701579668 end_time:1694701581100 name:\"backup_table_one\" backup_timestamp:1694701579668 collection_backups:<collection_id:443867104103340970 db_name:\"kg_test_01\" collection_name:\"spark_doc_kb_knowledge_base\" schema:<name:\"spark_doc_kb_knowledge_base\" fields:<fieldID:100 name:\"id\" is_primary_key:true description:\"Unique ID\" data_type:VarChar type_params:<key:\"max_length\" value:\"65535\" > > fields:<fieldID:101 name:\"doc_id\" description:\"Source document ID\" data_type:VarChar type_params:<key:\"max_length\" value:\"65535\" > > fields:<fieldID:102 name:\"text\" description:\"The embedding vector\" data_type:VarChar type_params:<key:\"max_length\" value:\"65535\" > > fields:<fieldID:103 name:\"embedding\" description:\"The embedding vector\" data_type:FloatVector type_params:<key:\"dim\" value:\"1536\" > > fields:<fieldID:104 name:\"node\" description:\"The node content\" data_type:VarChar type_params:<key:\"max_length\" value:\"65535\" > > > shards_num:1 partition_backups:<partition_id:443867104103340971 partition_name:\"_default\" collection_id:443867104103340970 segment_backups:<segment_id:443867104103341003 collection_id:443867104103340970 partition_id:443867104103340971 num_of_rows:157 binlogs:<binlogs:<log_path:\"milvus_data/insert_log/443867104103340970/443867104103340971/443867104103341003/0/443867104103344237\" log_size:724 > binlogs:<log_path:\"milvus_data/insert_log/443867104103340970/443867104103340971/443867104103341003/0/443867104103347445\" log_size:544 > > binlogs:<fieldID:1 binlogs:<log_path:\"milvus_data/insert_log/443867104103340970/443867104103340971/443867104103341003/1/443867104103344238\" log_size:510 > binlogs:<log_path:\"milvus_data/insert_log/443867104103340970/443867104103340971/443867104103341003/1/443867104103347446\" log_size:471 > > binlogs:<fieldID:100 binlogs:<log_path:\"milvus_data/insert_log/443867104103340970/443867104103340971/443867104103341003/100/443867104103344232\" log_size:3056 > binlogs:<log_path:\"milvus_data/insert_log/443867104103340970/443867104103340971/443867104103341003/100/443867104103347440\" log_size:1986 > > binlogs:<fieldID:101 binlogs:<log_path:\"milvus_data/insert_log/443867104103340970/443867104103340971/443867104103341003/101/443867104103344233\" log_size:816 > binlogs:<log_path:\"milvus_data/insert_log/443867104103340970/443867104103340971/443867104103341003/101/443867104103347441\" log_size:640 > > binlogs:<fieldID:102 binlogs:<log_path:\"milvus_data/insert_log/443867104103340970/443867104103340971/443867104103341003/102/443867104103344234\" log_size:114742 > binlogs:<log_path:\"milvus_data/insert_log/443867104103340970/443867104103340971/443867104103341003/102/443867104103347442\" log_size:44052 > > binlogs:<fieldID:103 binlogs:<log_path:\"milvus_data/insert_log/443867104103340970/443867104103340971/443867104103341003/103/443867104103344235\" log_size:743931 > binlogs:<log_path:\"milvus_data/insert_log/443867104103340970/443867104103340971/443867104103341003/103/443867104103347443\" log_size:221590 > > binlogs:<fieldID:104 binlogs:<log_path:\"milvus_data/insert_log/443867104103340970/443867104103340971/443867104103341003/104/443867104103344236\" log_size:13571 > binlogs:<log_path:\"milvus_data/insert_log/443867104103340970/443867104103340971/443867104103341003/104/443867104103347444\" log_size:7191 > > deltalogs:<> size:1153824 > size:1153824 load_state:\"Loaded\" > backup_timestamp:444255850987520 size:1153824 has_index:true index_infos:<field_name:\"embedding\" index_name:\"_default_idx_103\" index_type:\"HNSW\" params:<key:\"index_type\" value:\"HNSW\" > params:<key:\"metric_type\" value:\"IP\" > params:<key:\"params\" value:\"{\\\"M\\\":8,\\\"efConstruction\\\":64}\" > > load_state:\"Loaded\" backup_physical_timestamp:1694701580 > size:1153824 milvus_version:\"v2.3.0-dev\" > "]
[2023/09/15 17:22:29.810 +08:00] [INFO] [core/backup_impl_restore_backup.go:164] ["Collections to restore"] [collection_num=1]
[2023/09/15 17:22:29.851 +08:00] [ERROR] [core/backup_context.go:74] ["failed to connect to milvus"] [error="this version of sdk is incompatible with server, please downgrade your sdk or upgrade your server"] [errorVerbose="this version of sdk is incompatible with server, please downgrade your sdk or upgrade your server\n(1) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus-sdk-go/v2/client.(*GrpcClient).connectInternal\n  | \t/home/runner/go/pkg/mod/github.com/wayblink/milvus-sdk-go/v2@v2.2.20/client/collection.go:84\n  | github.com/milvus-io/milvus-sdk-go/v2/client.(*GrpcClient).connect\n  | \t/home/runner/go/pkg/mod/github.com/wayblink/milvus-sdk-go/v2@v2.2.20/client/collection.go:54\n  | github.com/milvus-io/milvus-sdk-go/v2/client.NewClient\n  | \t/home/runner/go/pkg/mod/github.com/wayblink/milvus-sdk-go/v2@v2.2.20/client/client.go:249\n  | github.com/milvus-io/milvus-sdk-go/v2/client.NewDefaultGrpcClientWithAuth\n  | \t/home/runner/go/pkg/mod/github.com/wayblink/milvus-sdk-go/v2@v2.2.20/client/client.go:304\n  | github.com/zilliztech/milvus-backup/core.CreateMilvusClient\n  | \t/home/runner/work/milvus-backup/milvus-backup/core/backup_context.go:63\n  | github.com/zilliztech/milvus-backup/core.(*BackupContext).getMilvusClient\n  | \t/home/runner/work/milvus-backup/milvus-backup/core/backup_context.go:157\n  | github.com/zilliztech/milvus-backup/core.(*BackupContext).RestoreBackup\n  | \t/home/runner/work/milvus-backup/milvus-backup/core/backup_impl_restore_backup.go:207\n  | github.com/zilliztech/milvus-backup/cmd.glob..func5\n  | \t/home/runner/work/milvus-backup/milvus-backup/cmd/restore.go:70\n  | github.com/spf13/cobra.(*Command).execute\n  | \t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876\n  | github.com/spf13/cobra.(*Command).ExecuteC\n  | \t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990\n  | github.com/spf13/cobra.(*Command).Execute\n  | \t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918\n  | github.com/zilliztech/milvus-backup/cmd.Execute\n  | \t/home/runner/work/milvus-backup/milvus-backup/cmd/root.go:24\n  | main.main\n  | \t/home/runner/work/milvus-backup/milvus-backup/main.go:17\n  | runtime.main\n  | \t/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/proc.go:250\n  | runtime.goexit\n  | \t/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/asm_amd64.s:1571\nWraps: (2) this version of sdk is incompatible with server, please downgrade your sdk or upgrade your server\nError types: (1) *withstack.withStack (2) *errutil.leafError"] [stack="github.com/zilliztech/milvus-backup/core.CreateMilvusClient\n\t/home/runner/work/milvus-backup/milvus-backup/core/backup_context.go:74\ngithub.com/zilliztech/milvus-backup/core.(*BackupContext).getMilvusClient\n\t/home/runner/work/milvus-backup/milvus-backup/core/backup_context.go:157\ngithub.com/zilliztech/milvus-backup/core.(*BackupContext).RestoreBackup\n\t/home/runner/work/milvus-backup/milvus-backup/core/backup_impl_restore_backup.go:207\ngithub.com/zilliztech/milvus-backup/cmd.glob..func5\n\t/home/runner/work/milvus-backup/milvus-backup/cmd/restore.go:70\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918\ngithub.com/zilliztech/milvus-backup/cmd.Execute\n\t/home/runner/work/milvus-backup/milvus-backup/cmd/root.go:24\nmain.main\n\t/home/runner/work/milvus-backup/milvus-backup/main.go:17\nruntime.main\n\t/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/proc.go:250"]
[2023/09/15 17:22:29.851 +08:00] [ERROR] [core/backup_context.go:159] ["failed to initial milvus client"] [error="this version of sdk is incompatible with server, please downgrade your sdk or upgrade your server"] [errorVerbose="this version of sdk is incompatible with server, please downgrade your sdk or upgrade your server\n(1) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus-sdk-go/v2/client.(*GrpcClient).connectInternal\n  | \t/home/runner/go/pkg/mod/github.com/wayblink/milvus-sdk-go/v2@v2.2.20/client/collection.go:84\n  | github.com/milvus-io/milvus-sdk-go/v2/client.(*GrpcClient).connect\n  | \t/home/runner/go/pkg/mod/github.com/wayblink/milvus-sdk-go/v2@v2.2.20/client/collection.go:54\n  | github.com/milvus-io/milvus-sdk-go/v2/client.NewClient\n  | \t/home/runner/go/pkg/mod/github.com/wayblink/milvus-sdk-go/v2@v2.2.20/client/client.go:249\n  | github.com/milvus-io/milvus-sdk-go/v2/client.NewDefaultGrpcClientWithAuth\n  | \t/home/runner/go/pkg/mod/github.com/wayblink/milvus-sdk-go/v2@v2.2.20/client/client.go:304\n  | github.com/zilliztech/milvus-backup/core.CreateMilvusClient\n  | \t/home/runner/work/milvus-backup/milvus-backup/core/backup_context.go:63\n  | github.com/zilliztech/milvus-backup/core.(*BackupContext).getMilvusClient\n  | \t/home/runner/work/milvus-backup/milvus-backup/core/backup_context.go:157\n  | github.com/zilliztech/milvus-backup/core.(*BackupContext).RestoreBackup\n  | \t/home/runner/work/milvus-backup/milvus-backup/core/backup_impl_restore_backup.go:207\n  | github.com/zilliztech/milvus-backup/cmd.glob..func5\n  | \t/home/runner/work/milvus-backup/milvus-backup/cmd/restore.go:70\n  | github.com/spf13/cobra.(*Command).execute\n  | \t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876\n  | github.com/spf13/cobra.(*Command).ExecuteC\n  | \t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990\n  | github.com/spf13/cobra.(*Command).Execute\n  | \t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918\n  | github.com/zilliztech/milvus-backup/cmd.Execute\n  | \t/home/runner/work/milvus-backup/milvus-backup/cmd/root.go:24\n  | main.main\n  | \t/home/runner/work/milvus-backup/milvus-backup/main.go:17\n  | runtime.main\n  | \t/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/proc.go:250\n  | runtime.goexit\n  | \t/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/asm_amd64.s:1571\nWraps: (2) this version of sdk is incompatible with server, please downgrade your sdk or upgrade your server\nError types: (1) *withstack.withStack (2) *errutil.leafError"] [stack="github.com/zilliztech/milvus-backup/core.(*BackupContext).getMilvusClient\n\t/home/runner/work/milvus-backup/milvus-backup/core/backup_context.go:159\ngithub.com/zilliztech/milvus-backup/core.(*BackupContext).RestoreBackup\n\t/home/runner/work/milvus-backup/milvus-backup/core/backup_impl_restore_backup.go:207\ngithub.com/zilliztech/milvus-backup/cmd.glob..func5\n\t/home/runner/work/milvus-backup/milvus-backup/cmd/restore.go:70\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918\ngithub.com/zilliztech/milvus-backup/cmd.Execute\n\t/home/runner/work/milvus-backup/milvus-backup/cmd/root.go:24\nmain.main\n\t/home/runner/work/milvus-backup/milvus-backup/main.go:17\nruntime.main\n\t/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/proc.go:250"]
panic: this version of sdk is incompatible with server, please downgrade your sdk or upgrade your server

goroutine 1 [running]:
github.com/zilliztech/milvus-backup/core.(*BackupContext).getMilvusClient(0xc00016d8c0)
        /home/runner/work/milvus-backup/milvus-backup/core/backup_context.go:160 +0x27a
github.com/zilliztech/milvus-backup/core.(*BackupContext).RestoreBackup(0xc00016d8c0, {0x129f968?, 0xc000128000}, 0xc0005b3ad8)
        /home/runner/work/milvus-backup/milvus-backup/core/backup_impl_restore_backup.go:207 +0x20f0
github.com/zilliztech/milvus-backup/cmd.glob..func5(0x220d1a0?, {0xc000519240, 0x0, 0x4})
        /home/runner/work/milvus-backup/milvus-backup/cmd/restore.go:70 +0x60f
github.com/spf13/cobra.(*Command).execute(0x220d1a0, {0xc000519200, 0x4, 0x4})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0x220d420)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/zilliztech/milvus-backup/cmd.Execute()
        /home/runner/work/milvus-backup/milvus-backup/cmd/root.go:24 +0x71
main.main()
        /home/runner/work/milvus-backup/milvus-backup/main.go:17 +0x17
[root@tc-bj-yw-dba-manager milvus_backup]#

**Comment by zhuwenxing** [comment]
/assign @wayblink 

Please take a look. Milvus backup v0.3.3 should be compatible with Milvus v2.3.0.

**Comment by suchenghui** [comment]
K8S版本的问题。目前K8S 1.22和之前的版本不支持备份
