### ISSUE TITLE
[Bug]: Create index timeout(1200s) after standalone reinstallation

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#27195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.0-20230918-dde27711-amd64
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):kafka    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2023-09-18T13:37:43.040Z] <name>: DropChecker__80lpuRUp

[2023-09-18T13:37:43.040Z] <description>: 

[2023-09-18T13:37:43.040Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: ......  (api_request.py:37)

[2023-09-18T13:37:43.040Z] [2023-09-18 13:14:27 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2023-09-18T13:37:43.040Z] [2023-09-18 13:14:28 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-09-18T13:37:43.040Z] [2023-09-18 13:14:28 - DEBUG - ci_test]: (api_request)  : [Collection.compact] args: [120], kwargs: {} (api_request.py:62)

[2023-09-18T13:37:43.040Z] [2023-09-18 13:14:28 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-09-18T13:37:43.040Z] [2023-09-18 13:17:04 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 120} (api_request.py:62)

[2023-09-18T13:37:43.040Z] [2023-09-18 13:17:08 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-09-18T13:37:43.040Z] [2023-09-18 13:17:09 - INFO - ci_test]: assert create collection: 0.1956174373626709, init_entities: 3000 (test_all_collections_after_chaos.py:49)

[2023-09-18T13:37:43.040Z] [2023-09-18 13:17:09 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [[[-3000, -2999, -2998, -2997, -2996, -2995, -2994, -2993, -2992, -2991, -2990, -2989, -2988, -2987, -2986, -2985, -2984, -2983, -2982, -2981, -2980, -2979, -2978, -2977, -2976, -2975, -2974, -2973, -2972, -2971, -2970, -2969, -2968, -2967, -2966, -2965, -2964, -2963, -2962, -2961, -2960, -2959, -29......, kwargs: {'timeout': 120} (api_request.py:62)

[2023-09-18T13:37:43.040Z] [2023-09-18 13:17:12 - DEBUG - ci_test]: (api_response) : (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 444345360085155846, success count: 2000, err count: 0)  (api_request.py:37)

[2023-09-18T13:37:43.040Z] [2023-09-18 13:17:12 - INFO - ci_test]: assert insert: 3.4751462936401367 (test_all_collections_after_chaos.py:61)

[2023-09-18T13:37:43.040Z] [2023-09-18 13:17:12 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2023-09-18T13:37:43.040Z] [2023-09-18 13:17:32 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-09-18T13:37:43.040Z] [2023-09-18 13:17:32 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 120} (api_request.py:62)

[2023-09-18T13:37:43.040Z] [2023-09-18 13:17:36 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-09-18T13:37:43.040Z] [2023-09-18 13:17:38 - INFO - ci_test]: assert flush: 20.09927535057068, entities: 5000 (test_all_collections_after_chaos.py:71)

[2023-09-18T13:37:43.040Z] [2023-09-18 13:17:38 - INFO - ci_test]: collection DropChecker__80lpuRUp does not have index, create index for it (test_all_collections_after_chaos.py:77)

[2023-09-18T13:37:43.040Z] [2023-09-18 13:17:38 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['float_vector', {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}], kwargs: {'timeout': 1200, 'index_name': 'test_6GhEsFQ2'} (api_request.py:62)

[2023-09-18T13:37:43.040Z] [2023-09-18 13:37:39 - WARNING - pymilvus.decorators]: Retry timeout: 1200s (decorators.py:94)

[2023-09-18T13:37:43.040Z] [2023-09-18 13:37:39 - ERROR - pymilvus.decorators]: RPC error: [wait_for_creating_index], <MilvusException: (code=1, message=Retry timeout: 1200s, message=collection DropChecker__80lpuRUp create index test_6GhEsFQ2 timeout in 1200s)>, <Time:{'RPC start': '2023-09-18 13:17:38.814933', 'RPC error': '2023-09-18 13:37:39.236612'}> (decorators.py:126)

[2023-09-18T13:37:43.040Z] [2023-09-18 13:37:39 - WARNING - pymilvus.decorators]: Retry timeout: 1200s (decorators.py:94)

[2023-09-18T13:37:43.040Z] [2023-09-18 13:37:39 - ERROR - pymilvus.decorators]: RPC error: [create_index], <MilvusException: (code=1, message=Retry timeout: 1200s, message=Retry timeout: 1200s, message=collection DropChecker__80lpuRUp create index test_6GhEsFQ2 timeout in 1200s)>, <Time:{'RPC start': '2023-09-18 13:17:38.626683', 'RPC error': '2023-09-18 13:37:39.236882'}> (decorators.py:126)

[2023-09-18T13:37:43.040Z] [2023-09-18 13:37:39 - ERROR - ci_test]: Traceback (most recent call last):

[2023-09-18T13:37:43.040Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2023-09-18T13:37:43.040Z]     res = func(*args, **_kwargs)

[2023-09-18T13:37:43.040Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2023-09-18T13:37:43.040Z]     return func(*arg, **kwargs)

[2023-09-18T13:37:43.040Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 1208, in create_index

[2023-09-18T13:37:43.040Z]     return conn.create_index(self._name, field_name, index_params, timeout=timeout, **kwargs)

[2023-09-18T13:37:43.040Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 127, in handler

[2023-09-18T13:37:43.040Z]     raise e from e

[2023-09-18T13:37:43.040Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 123, in handler

[2023-09-18T13:37:43.040Z]     return func(*args, **kwargs)

[2023-09-18T13:37:43.040Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 162, in handler

[2023-09-18T13:37:43.040Z]     return func(self, *args, **kwargs)

[2023-09-18T13:37:43.040Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 95, in handler

[2023-09-18T13:37:43.040Z]     raise MilvusException(

[2023-09-18T13:37:43.040Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 1200s, message=Retry timeout: 1200s, message=collection DropChecker__80lpuRUp create index test_6GhEsFQ2 timeout in 1200s)>

[2023-09-18T13:37:43.040Z]  (api_request.py:45)

[2023-09-18T13:37:43.041Z] [2023-09-18 13:37:39 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 1200s, message=Retry timeout: 1200s, message=collection DropChecker__80lpuRUp create index test_6GhEsFQ2 timeout in 1200s)> (api_request.py:46)
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_kafka_for_release_cron/detail/deploy_test_kafka_for_release_cron/1446/pipeline

log:
[artifacts-kafka-standalone-reinstall-1446-server-first-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/12655319/artifacts-kafka-standalone-reinstall-1446-server-first-deployment-logs.tar.gz)
[artifacts-kafka-standalone-reinstall-1446-server-second-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/12655321/artifacts-kafka-standalone-reinstall-1446-server-second-deployment-logs.tar.gz)
[artifacts-kafka-standalone-reinstall-1446-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/12655322/artifacts-kafka-standalone-reinstall-1446-pytest-logs.tar.gz)

### Anything else?

Not a stable issue

**Comment by xiaocai2333** [comment]
It is blocked by indexing tasks from other collections.
And these indexing tasks are basically generated by the segment after compaction.
![image](https://github.com/milvus-io/milvus/assets/46207236/73b0d873-ee2a-44b5-9c70-e9374e965c53)

**Comment by xiaocai2333** [comment]
It is recommended to perform `wait_for_index_building_complete` on other tables before checking the new table to build the index.

**Comment by zhuwenxing** [comment]
> It is recommended to perform wait_for_index_building_complete on other tables before checking the new table to build the index.

This approach is very unfriendly to users!!
If I want to do a CRUD on a new collection, I need to check if the indexes of all the collections in the system have been built completely.

**Comment by xiaofan-luan** [comment]
I think it make sense if user can get stats about current index status.

There is no guarantee that index will be finished in time.

**Comment by xiaofan-luan** [comment]
however, we can improve this by compaction trigger policy.

**Comment by xiaofan-luan** [comment]
compaction can be only triggered if indextask has slot?
