### ISSUE TITLE
[Bug]: [Nightly] Kafka cases frequently failed for DEADLINE_EXCEEDED

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#27196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230918-fd732135
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.0.post1.dev12
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Kafka cases frequently failed for DEADLINE_EXCEEDED.
```
[2023-09-18T21:51:17.176Z] [2023-09-18 18:23:46 - ERROR - pymilvus.decorators]: grpc RpcError: [flush], <_MultiThreadedRendezvous: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded>, <Time:{'RPC start': '2023-09-18 18:23:26.994954', 'gRPC error': '2023-09-18 18:23:46.995670'}> (decorators.py:137)
[2023-09-18T21:51:17.176Z] [2023-09-18 18:23:46 - ERROR - ci_test]: Traceback (most recent call last):
[2023-09-18T21:51:17.176Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper
[2023-09-18T21:51:17.176Z]     res = func(*args, **_kwargs)
[2023-09-18T21:51:17.176Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request
[2023-09-18T21:51:17.176Z]     return func(*arg, **kwargs)
[2023-09-18T21:51:17.176Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/partition.py", line 155, in flush
[2023-09-18T21:51:17.176Z]     conn.flush([self._collection.name], timeout=timeout, **kwargs)
[2023-09-18T21:51:17.176Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 141, in handler
[2023-09-18T21:51:17.176Z]     raise e from e
[2023-09-18T21:51:17.176Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 123, in handler
[2023-09-18T21:51:17.176Z]     return func(*args, **kwargs)
[2023-09-18T21:51:17.176Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 162, in handler
[2023-09-18T21:51:17.176Z]     return func(self, *args, **kwargs)
[2023-09-18T21:51:17.176Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 79, in handler
[2023-09-18T21:51:17.176Z]     raise e from e
[2023-09-18T21:51:17.176Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 68, in handler
[2023-09-18T21:51:17.176Z]     return func(*args, **kwargs)
[2023-09-18T21:51:17.176Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 1281, in flush
[2023-09-18T21:51:17.176Z]     response = future.result()
[2023-09-18T21:51:17.176Z]   File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 797, in result
[2023-09-18T21:51:17.176Z]     raise self
[2023-09-18T21:51:17.176Z] grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
[2023-09-18T21:51:17.176Z] 	status = StatusCode.DEADLINE_EXCEEDED
[2023-09-18T21:51:17.176Z] 	details = "Deadline Exceeded"
[2023-09-18T21:51:17.176Z] 	debug_error_string = "UNKNOWN:Deadline Exceeded {created_time:"2023-09-18T18:23:46.995232663+00:00", grpc_status:4}"
[2023-09-18T21:51:17.176Z] >
[2023-09-18T21:51:17.176Z]  (api_request.py:45)
[2023-09-18T21:51:17.176Z] [2023-09-18 18:23:46 - ERROR - ci_test]: (api_response) : <_MultiThreadedRendezvous of RPC that terminated with:
[2023-09-18T21:51:17.176Z] 	status = StatusCode.DEADLINE_EXCEEDED
[2023-09-18T21:51:17.176Z] 	details = "Deadline Exceeded"
[2023-09-18T21:51:17.176Z] 	debug_error_string = "UNKNOWN:Deadline Exceeded {created_time:"2023-09-18T18:23:46.995232663+00:00", grpc_status:4}"
[2023-09-18T21:51:17.176Z] > (api_request.py:46)
```

### Expected Behavior

pass

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/501/pipeline/193
2. log: -
[artifacts-milvus-distributed-kafka-nightly-501-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/501/artifact/artifacts-milvus-distributed-kafka-nightly-501-pymilvus-e2e-logs.tar.gz)
3. reason:
![img_v2_1151558c-6c05-46b7-97ea-a2bb1c7ebd2g](https://github.com/milvus-io/milvus/assets/109071306/30379633-cfa3-49e7-9b65-fa358d96cd47)

**Comment by NicoYuan1986** [comment]
@czs007  @longjiquan  Could you help to fix ? thx.

**Comment by NicoYuan1986** [comment]
Is it the same reason as #26485?

**Comment by longjiquan** [comment]
Please increase the timeout of the flush case. @NicoYuan1986 
/assign @NicoYuan1986 
/unassign

**Comment by NicoYuan1986** [comment]
Fixed by modifying flush timeout to 180s.
master-20230919-d77984c2-amd64

**Comment by mewc** [comment]
Having this issue on zilliz cloud clusters atm. Is it not available there yet?

**Comment by yanliang567** [comment]
> Having this issue on zilliz cloud clusters atm. Is it not available there yet?

please submit a request in support.zilliz.com: https://support.zilliz.com/hc/en-us/requests/new. If possible, please sign up/sign in with the same email with zilliz.com, which helps us prioritize the requests. @mewc
