### ISSUE TITLE
[Bug]: Flush failed with error `context deadline exceeded` after standalone reinstallation

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#27193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.0-20230918-dde27711-amd64
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):kafka    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```

[2023-09-18T16:39:37.315Z] 2023-09-18 16:39:37.114 | INFO     | MainThread |utils:create_collections_and_insert_data:99 - collection name: task_1_FLAT

[2023-09-18T16:39:37.315Z] 2023-09-18 16:39:37.114 | INFO     | MainThread |utils:create_collections_and_insert_data:100 - begin insert, count: 3000 nb: 300

[2023-09-18T16:39:37.571Z] 2023-09-18 16:39:37.329 | INFO     | MainThread |utils:create_collections_and_insert_data:114 - [1/10] insert 300 data, time: 0.1778

[2023-09-18T16:39:40.833Z] 2023-09-18 16:39:40.626 | INFO     | MainThread |utils:create_collections_and_insert_data:114 - [2/10] insert 300 data, time: 0.1061

[2023-09-18T16:39:44.994Z] 2023-09-18 16:39:44.117 | INFO     | MainThread |utils:create_collections_and_insert_data:114 - [3/10] insert 300 data, time: 0.3009

[2023-09-18T16:39:47.504Z] 2023-09-18 16:39:46.932 | INFO     | MainThread |utils:create_collections_and_insert_data:114 - [4/10] insert 300 data, time: 0.1163

[2023-09-18T16:39:50.769Z] 2023-09-18 16:39:50.336 | INFO     | MainThread |utils:create_collections_and_insert_data:114 - [5/10] insert 300 data, time: 0.2072

[2023-09-18T16:39:53.279Z] 2023-09-18 16:39:53.141 | INFO     | MainThread |utils:create_collections_and_insert_data:114 - [6/10] insert 300 data, time: 0.1066

[2023-09-18T16:39:57.440Z] 2023-09-18 16:39:56.734 | INFO     | MainThread |utils:create_collections_and_insert_data:114 - [7/10] insert 300 data, time: 0.1103

[2023-09-18T16:40:03.966Z] 2023-09-18 16:40:03.939 | INFO     | MainThread |utils:create_collections_and_insert_data:114 - [8/10] insert 300 data, time: 0.2136

[2023-09-18T16:40:08.125Z] 2023-09-18 16:40:07.624 | INFO     | MainThread |utils:create_collections_and_insert_data:114 - [9/10] insert 300 data, time: 0.5940

[2023-09-18T16:40:08.379Z] 2023-09-18 16:40:08.229 | INFO     | MainThread |utils:create_collections_and_insert_data:114 - [10/10] insert 300 data, time: 0.6045

[2023-09-18T16:40:08.379Z] 2023-09-18 16:40:08.229 | INFO     | MainThread |utils:create_collections_and_insert_data:123 - end insert, time: 2.5373

[2023-09-18T16:40:08.379Z] 2023-09-18 16:40:08.229 | INFO     | MainThread |utils:create_collections_and_insert_data:125 - Get collection entities

[2023-09-18T16:40:20.535Z] RPC error: [flush], <MilvusException: (code=1, message=failed to flush 444347971142681026, context deadline exceeded)>, <Time:{'RPC start': '2023-09-18 16:40:08.229469', 'RPC error': '2023-09-18 16:40:18.521405'}>

[2023-09-18T16:40:20.535Z] Traceback (most recent call last):

[2023-09-18T16:40:20.535Z]   File "scripts/action_after_reinstall.py", line 46, in <module>

[2023-09-18T16:40:20.535Z]     task_1(data_size, host)

[2023-09-18T16:40:20.535Z]   File "scripts/action_after_reinstall.py", line 16, in task_1

[2023-09-18T16:40:20.535Z]     create_collections_and_insert_data(prefix,count=data_size)

[2023-09-18T16:40:20.535Z]   File "/home/jenkins/agent/workspace/tests/python_client/deploy/scripts/utils.py", line 128, in create_collections_and_insert_data

[2023-09-18T16:40:20.535Z]     collection.flush()

[2023-09-18T16:40:20.535Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 314, in flush

[2023-09-18T16:40:20.535Z]     conn.flush([self.name], timeout=timeout, **kwargs)

[2023-09-18T16:40:20.535Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 127, in handler

[2023-09-18T16:40:20.535Z]     raise e from e

[2023-09-18T16:40:20.535Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 123, in handler

[2023-09-18T16:40:20.535Z]     return func(*args, **kwargs)

[2023-09-18T16:40:20.535Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 162, in handler

[2023-09-18T16:40:20.535Z]     return func(self, *args, **kwargs)

[2023-09-18T16:40:20.535Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 102, in handler

[2023-09-18T16:40:20.535Z]     raise e from e

[2023-09-18T16:40:20.535Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 68, in handler

[2023-09-18T16:40:20.535Z]     return func(*args, **kwargs)

[2023-09-18T16:40:20.535Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 1283, in flush

[2023-09-18T16:40:20.536Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2023-09-18T16:40:20.536Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=failed to flush 444347971142681026, context deadline exceeded)>

script returned exit code 1
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_kafka_for_release_cron/detail/deploy_test_kafka_for_release_cron/1450/pipeline

log:
[artifacts-kafka-standalone-reinstall-1450-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/12654899/artifacts-kafka-standalone-reinstall-1450-pytest-logs.tar.gz)
[artifacts-kafka-standalone-reinstall-1450-server-first-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/12654900/artifacts-kafka-standalone-reinstall-1450-server-first-deployment-logs.tar.gz)
[artifacts-kafka-standalone-reinstall-1450-server-second-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/12654901/artifacts-kafka-standalone-reinstall-1450-server-second-deployment-logs.tar.gz)

**Comment by bigsheeper** [comment]
/assign
working on it

**Comment by bigsheeper** [comment]
The Flush has a timeout of only 10 seconds.
![xXwlFlbRrH](https://github.com/milvus-io/milvus/assets/42060877/a035ad8e-147a-4dd9-802a-c3ad7b0a4360)

But the Datanode spent 7 seconds to initiate and reach healthy state.
![dsd1Jk8t7D](https://github.com/milvus-io/milvus/assets/42060877/61239be1-8a51-47cb-bc1a-8c0d8b92d4ff)

We should increase Flush timeout for a greater tolerance period during initialization/reinstallation. @zhuwenxing

**Comment by zhuwenxing** [comment]
@bigsheeper 
I did not set a timeout for flush. From the description, it will keep running until raises an error. 
![image](https://github.com/milvus-io/milvus/assets/12268675/ed41b8ef-518a-4ea2-b3c5-08e1ced7d7b5)

**Comment by bigsheeper** [comment]
alter segment state timeout when flush:
![F6Yav78sYC](https://github.com/milvus-io/milvus/assets/42060877/f8eddf5b-40f4-47ce-a2e5-8afe1dd4edb3)
https://grafana-4am.zilliz.cc/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22B%22,%22expr%22:%22%7Bpod%3D%5C%22kafka-standalone-reinstall-1450-milvus-standalone-755d8b8fx4xbq%5C%22%7D%20%7C~%20%5C%22datacoord%2F%7Cdatanode%2F%5C%22%20!~%20%5C%22loadSegment%7CGetIndexSegment%5C%22%22%7D%5D,%22range%22:%7B%22from%22:%221695055204656%22,%22to%22:%221695055222641%22%7D%7D

**Comment by bigsheeper** [comment]
etcd is not stable:
![OdeIbZipW8](https://github.com/milvus-io/milvus/assets/42060877/347b7584-4030-41fa-9869-9d57c0f2cc41)

Could you please try this test agian?  This occurrence should not be a frequent phenomenon. @zhuwenxing

**Comment by zhuwenxing** [comment]
@bigsheeper 
Yes, it is not a stable issue.

**Comment by czs007** [comment]
![image](https://github.com/milvus-io/milvus/assets/59249785/160a4356-85cd-4494-9ad7-16cacdc279cb)
![image](https://github.com/milvus-io/milvus/assets/59249785/58c965e2-0d8f-4288-aaf7-f4f671b7e9e1)

During this period, the CPU utilization has been quite high due to index construction.

**Comment by bigsheeper** [comment]
![image](https://github.com/milvus-io/milvus/assets/42060877/116b5271-4260-4907-8a8b-83e06a5514ef)
![image](https://github.com/milvus-io/milvus/assets/42060877/71b4c579-53ea-4f44-8daa-31c2144db96f)

https://grafana-4am.zilliz.cc/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22B%22,%22expr%22:%22%7Bpod%3D%5C%22kafka-standalone-reinstall-1452-milvus-standalone-7758dd5b94829%5C%22%7D%20%7C~%20%5C%22Slow%20etcd%7CEtcd%7CGC%20Tune%20done,%20and%20the%20gc%20is%20slow%5C%22%22,%22hide%22:true%7D,%7B%22refId%22:%22A%22,%22expr%22:%22%7Bpod%3D%5C%22kafka-standalone-reinstall-1450-milvus-standalone-755d8b8fx4xbq%5C%22%7D%20%7C~%20%5C%22Slow%20etcd%7CEtcd%7CGC%20Tune%20done,%20and%20the%20gc%20is%20slow%5C%22%22,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%221694921268316%22,%22to%22:%221695180246967%22%7D%7D


![image](https://github.com/milvus-io/milvus/assets/42060877/7c19b959-23ac-4232-b935-b3742fad4341)
![image](https://github.com/milvus-io/milvus/assets/42060877/d898d104-20e5-4928-8c8f-764529c6c9c4)

https://grafana-4am.zilliz.cc/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22B%22,%22expr%22:%22%7Bpod%3D%5C%22kafka-standalone-reinstall-1452-milvus-standalone-7758dd5b94829%5C%22%7D%20%7C~%20%5C%22Slow%20etcd%7CEtcd%7CGC%20Tune%20done,%20and%20the%20gc%20is%20slow%5C%22%22,%22hide%22:false%7D,%7B%22refId%22:%22A%22,%22expr%22:%22%7Bpod%3D%5C%22kafka-standalone-reinstall-1450-milvus-standalone-755d8b8fx4xbq%5C%22%7D%20%7C~%20%5C%22Slow%20etcd%7CEtcd%7CGC%20Tune%20done,%20and%20the%20gc%20is%20slow%5C%22%22,%22hide%22:true%7D%5D,%22range%22:%7B%22from%22:%221694921268316%22,%22to%22:%221695180246967%22%7D%7D

It seems that the ETCD save operation is influenced by the GC STW.
