### ISSUE TITLE
Create index failed using shards

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#2724]
**Describe the bug**
```
15:08:32  2020-07-03:07:08:22,683 INFO     [client.py:334] Server command: mode, result: CPU
15:08:32  2020-07-03:07:08:22,688 INFO     [client.py:334] Server command: build_commit_id, result: f7c1d0ad0dfafc573162632d99af99393a8ac448
15:08:32  2020-07-03:07:08:22,697 DEBUG    [k8s_runner.py:658] Building index with param: {"nlist": 16384}
15:08:32  2020-07-03:07:08:22,697 INFO     [client.py:213] Building index start, collection_name: sift_128_euclidean, index_type: IVF_SQ8
15:08:32  2020-07-03:07:08:22,697 INFO     [client.py:215] {'nlist': 16384}
16:08:54  
16:08:54  Addr [milvus-benchmark-test-2jchlp1c.milvus.svc.cluster.local:19530] create_index
16:08:54  Rpc error: <_MultiThreadedRendezvous of RPC that terminated with:
16:08:54  	status = StatusCode.UNAVAILABLE
16:08:54  	details = "Socket closed"
16:08:54  	debug_error_string = "{"created":"@1593763722.583495113","description":"Error received from peer ipv4:10.102.39.119:19530","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Socket closed","grpc_status":14}"
16:08:54  >
16:08:54  	{'API start': '2020-07-03 07:08:22.697377', 'RPC start': '2020-07-03 07:08:22.697381', 'RPC error': '2020-07-03 08:08:42.585013'}
16:08:54  2020-07-03:08:08:42,585 ERROR    [grpc_handler.py:50] 
16:08:54  Addr [milvus-benchmark-test-2jchlp1c.milvus.svc.cluster.local:19530] create_index
16:08:54  Rpc error: <_MultiThreadedRendezvous of RPC that terminated with:
16:08:54  	status = StatusCode.UNAVAILABLE
16:08:54  	details = "Socket closed"
16:08:54  	debug_error_string = "{"created":"@1593763722.583495113","description":"Error received from peer ipv4:10.102.39.119:19530","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Socket closed","grpc_status":14}"
16:08:54  >
16:08:54  	{'API start': '2020-07-03 07:08:22.697377', 'RPC start': '2020-07-03 07:08:22.697381', 'RPC error': '2020-07-03 08:08:42.585013'}
16:08:54  2020-07-03:08:08:42,585 ERROR    [client.py:99] Error occurred. Socket closed
16:08:54  2020-07-03:08:08:42,585 ERROR    [main.py:70] Status not ok
16:08:54  2020-07-03:08:08:42,588 ERROR    [main.py:71] Traceback (most recent call last):
16:08:54    File "main.py", line 68, in queue_worker
16:08:54      runner.run(run_type, collection)
16:08:54    File "/home/jenkins/agent/workspace/milvus-benchmark-0.10.1/milvus_benchmark/k8s_runner.py", line 659, in run
16:08:54      milvus_instance.create_index(index_type, index_param=index_param)
16:08:54    File "/home/jenkins/agent/workspace/milvus-benchmark-0.10.1/milvus_benchmark/client.py", line 44, in wrapper
16:08:54      result = func(*args, **kwargs)
16:08:54    File "/home/jenkins/agent/workspace/milvus-benchmark-0.10.1/milvus_benchmark/client.py", line 217, in create_index
16:08:54      self.check_status(status)
16:08:54    File "/home/jenkins/agent/workspace/milvus-benchmark-0.10.1/milvus_benchmark/client.py", line 100, in check_status
16:08:54      raise Exception("Status not ok")
16:08:54  Exception: Status not ok
```

**Steps/Code to reproduce behavior**

**Expected behavior**

**Environment details**
based on milvus-0.10.1-cpu
dataset: sift-1m
index_type: ivf_sq8

**Screenshots**

**Additional context**

**Comment by del-zhenwu** [comment]
```
[2020-07-03 14:28:29,046][INFO][WAL][GetNextRecord][wal_thread] record type 2 collection sift_1m_128_128_l2 lsn 360877739484
[2020-07-03 14:28:29,126][INFO][WAL][operator()][wal_thread] record flush collection sift_1m_128_128_l2 lsn 360877739484
[2020-07-03 14:28:36,629][INFO][WAL][CollectionFlushed][wal_thread] sift_1m_128_128_l2 is flushed by lsn 360877739484
[2020-07-03 14:28:36,630][INFO][SERVER][Flush][grpcpp_sync_ser] Request [315] Flush end.
[2020-07-03 14:28:36,637][INFO][SERVER][CountCollection][grpcpp_sync_ser] Request [316] CountCollection begin.
[2020-07-03 14:28:36,644][INFO][SERVER][CountCollection][grpcpp_sync_ser] Request [316] CountCollection end.
[2020-07-03 14:28:36,652][INFO][SERVER][CountCollection][grpcpp_sync_ser] Request [317] CountCollection begin.
[2020-07-03 14:28:36,658][INFO][SERVER][CountCollection][grpcpp_sync_ser] Request [317] CountCollection end.
[2020-07-03 14:28:36,665][INFO][SERVER][Cmd][grpcpp_sync_ser] Request [318] Cmd begin.
[2020-07-03 14:28:36,666][INFO][SERVER][Cmd][grpcpp_sync_ser] Request [318] Cmd end.
[2020-07-03 14:28:36,674][INFO][SERVER][Cmd][grpcpp_sync_ser] Request [319] Cmd begin.
[2020-07-03 14:28:36,674][INFO][SERVER][Cmd][grpcpp_sync_ser] Request [319] Cmd end.
[2020-07-03 14:28:36,682][INFO][SERVER][Cmd][grpcpp_sync_ser] Request [320] Cmd begin.
[2020-07-03 14:28:36,682][INFO][SERVER][Cmd][grpcpp_sync_ser] Request [320] Cmd end.
[2020-07-03 14:29:37,407][INFO][SERVER][HandleSignal][milvus_server] Server received critical signal: 15
[2020-07-03 14:29:37,407][INFO][SERVER][PrintStacktrace][milvus_server] Call stack:
[2020-07-03 14:29:37,407][INFO][SERVER][PrintStacktrace][milvus_server] /var/lib/milvus/bin/milvus_server() [0x6b1b96]
[2020-07-03 14:29:37,407][INFO][SERVER][PrintStacktrace][milvus_server] /var/lib/milvus/bin/milvus_server() [0x6b2700]
[2020-07-03 14:29:37,407][INFO][SERVER][PrintStacktrace][milvus_server] /lib64/libc.so.6(+0x36400) [0x7fefc2ff1400]
[2020-07-03 14:29:37,407][INFO][SERVER][PrintStacktrace][milvus_server] /lib64/libpthread.so.0(pause+0x2d) [0x7fefc3dccf5d]
[2020-07-03 14:29:37,407][INFO][SERVER][PrintStacktrace][milvus_server] /var/lib/milvus/bin/milvus_server() [0x434e1a]
[2020-07-03 14:29:37,407][INFO][SERVER][PrintStacktrace][milvus_server] /lib64/libc.so.6(__libc_start_main+0xf5) [0x7fefc2fdd555]
[2020-07-03 14:29:37,408][INFO][SERVER][PrintStacktrace][milvus_server] /var/lib/milvus/bin/milvus_server() [0x442c47]
[2020-07-03 14:29:37,549][INFO][SERVER][Stop][milvus_server] Scheduler gonna stop...
[2020-07-03 14:29:37,549][INFO][SERVER][Stop][milvus_server] Scheduler stopped

```
[root@milvus-benchmark-test-vr81phxo-writable-74b559b56-vnvqp logs]# tail -f milvus-20-07-03-14:21-debug.log
[2020-07-03 14:29:34,143][DEBUG][ENGINE][Size][metric_thread] Size: SELECT IFNULL(SUM(file_size),0) AS sum FROM TableFiles WHERE file_type <> 4;
[2020-07-03 14:29:35,252][DEBUG][ENGINE][Size][metric_thread] Size: SELECT IFNULL(SUM(file_size),0) AS sum FROM TableFiles WHERE file_type <> 4;
[2020-07-03 14:29:36,361][DEBUG][ENGINE][Size][metric_thread] Size: SELECT IFNULL(SUM(file_size),0) AS sum FROM TableFiles WHERE file_type <> 4;
[2020-07-03 14:29:37,438][DEBUG][ENGINE][BackgroundWalThread][wal_thread] WAL background thread exit
[2020-07-03 14:29:37,439][DEBUG][ENGINE][BackgroundIndexThread][index_thread] DB background thread exit
[2020-07-03 14:29:37,440][DEBUG][ENGINE][CleanUpShadowFiles][milvus_server] CleanUp: SELECT table_name FROM information_schema.tables WHERE table_schema = 'db' AND table_name = 'TableFiles';
[2020-07-03 14:29:37,442][DEBUG][ENGINE][CleanUpShadowFiles][milvus_server] Remove collection file type as NEW
[2020-07-03 14:29:37,442][DEBUG][ENGINE][CleanUpShadowFiles][milvus_server] CleanUp: DELETE FROM TableFiles WHERE file_type IN (0,5,6);
[2020-07-03 14:29:37,443][DEBUG][ENGINE][CleanUpShadowFiles][milvus_server] Clean 1 files
[2020-07-03 14:29:37,548][DEBUG][ENGINE][BackgroundMetricThread][metric_thread] DB background metric thread exit

```

**Comment by tinkerlin** [comment]
#2487

**Comment by del-zhenwu** [comment]
no reproduced
