### ISSUE TITLE
[Bug]: Grpc error `StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded` in flush or list collection after datanode pod failure chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#27257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230918-fd732135-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):     
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```

[2023-09-19T20:25:39.813Z] <name>: Hello_Milvus

[2023-09-19T20:25:39.813Z] <description>: 

[2023-09-19T20:25:39.813Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}, {'n......  (api_request.py:37)

[2023-09-19T20:25:39.813Z] [2023-09-19 20:22:24 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2023-09-19T20:25:39.813Z] [2023-09-19 20:25:24 - ERROR - pymilvus.decorators]: grpc RpcError: [flush], <_MultiThreadedRendezvous: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded>, <Time:{'RPC start': '2023-09-19 20:22:24.481925', 'gRPC error': '2023-09-19 20:25:24.483317'}> (decorators.py:137)

[2023-09-19T20:25:39.813Z] [2023-09-19 20:25:24 - ERROR - ci_test]: Traceback (most recent call last):

[2023-09-19T20:25:39.813Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2023-09-19T20:25:39.813Z]     res = func(*args, **_kwargs)

[2023-09-19T20:25:39.813Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2023-09-19T20:25:39.813Z]     return func(*arg, **kwargs)

[2023-09-19T20:25:39.813Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 314, in flush

[2023-09-19T20:25:39.813Z]     conn.flush([self.name], timeout=timeout, **kwargs)

[2023-09-19T20:25:39.813Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 141, in handler

[2023-09-19T20:25:39.813Z]     raise e from e

[2023-09-19T20:25:39.813Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 123, in handler

[2023-09-19T20:25:39.813Z]     return func(*args, **kwargs)

[2023-09-19T20:25:39.813Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 162, in handler

[2023-09-19T20:25:39.813Z]     return func(self, *args, **kwargs)

[2023-09-19T20:25:39.813Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 79, in handler

[2023-09-19T20:25:39.813Z]     raise e from e

[2023-09-19T20:25:39.813Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 68, in handler

[2023-09-19T20:25:39.813Z]     return func(*args, **kwargs)

[2023-09-19T20:25:39.813Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 1281, in flush

[2023-09-19T20:25:39.813Z]     response = future.result()

[2023-09-19T20:25:39.813Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 881, in result

[2023-09-19T20:25:39.813Z]     raise self

[2023-09-19T20:25:39.813Z] grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:

[2023-09-19T20:25:39.813Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2023-09-19T20:25:39.813Z] 	details = "Deadline Exceeded"

[2023-09-19T20:25:39.813Z] 	debug_error_string = "UNKNOWN:Deadline Exceeded {grpc_status:4, created_time:"2023-09-19T20:25:24.482731586+00:00"}"

[2023-09-19T20:25:39.813Z] >

[2023-09-19T20:25:39.813Z]  (api_request.py:45)

[2023-09-19T20:25:39.813Z] [2023-09-19 20:25:24 - ERROR - ci_test]: (api_response) : <_MultiThreadedRendezvous of RPC that terminated with:

[2023-09-19T20:25:39.813Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2023-09-19T20:25:39.813Z] 	details = "Deadline Exceeded"

[2023-09-19T20:25:39.813Z] 	debug_error_string = "UNKNOWN:Deadline Exceeded {grpc_status:4, created_time:"2023-09-19T20:25:24.482731586+00:00"}"

[2023-09-19T20:25:39.813Z] > (api_request.py:46)
```

```
[2023-09-19T20:23:05.299Z] [2023-09-19 20:22:24 - DEBUG - ci_test]: (api_request)  : [Connections.connect] args: ['default', '', '', ''], kwargs: {'host': '10.255.236.24', 'port': 19530} (api_request.py:62)

[2023-09-19T20:23:05.299Z] [2023-09-19 20:22:24 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-09-19T20:23:05.299Z] [2023-09-19 20:22:24 - DEBUG - ci_test]: (api_request)  : [list_collections] args: [20, 'default'], kwargs: {} (api_request.py:62)

[2023-09-19T20:23:05.299Z] [2023-09-19 20:22:44 - ERROR - pymilvus.decorators]: grpc RpcError: [list_collections], <_MultiThreadedRendezvous: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded>, <Time:{'RPC start': '2023-09-19 20:22:24.823849', 'gRPC error': '2023-09-19 20:22:44.825256'}> (decorators.py:137)

[2023-09-19T20:23:05.299Z] [2023-09-19 20:22:44 - ERROR - ci_test]: Traceback (most recent call last):

[2023-09-19T20:23:05.299Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2023-09-19T20:23:05.299Z]     res = func(*args, **_kwargs)

[2023-09-19T20:23:05.299Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2023-09-19T20:23:05.299Z]     return func(*arg, **kwargs)

[2023-09-19T20:23:05.299Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/utility.py", line 556, in list_collections

[2023-09-19T20:23:05.299Z]     return _get_connection(using).list_collections(timeout=timeout)

[2023-09-19T20:23:05.299Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 141, in handler

[2023-09-19T20:23:05.299Z]     raise e from e

[2023-09-19T20:23:05.299Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 123, in handler

[2023-09-19T20:23:05.299Z]     return func(*args, **kwargs)

[2023-09-19T20:23:05.299Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 162, in handler

[2023-09-19T20:23:05.299Z]     return func(self, *args, **kwargs)

[2023-09-19T20:23:05.299Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 79, in handler

[2023-09-19T20:23:05.299Z]     raise e from e

[2023-09-19T20:23:05.299Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 68, in handler

[2023-09-19T20:23:05.299Z]     return func(*args, **kwargs)

[2023-09-19T20:23:05.299Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 352, in list_collections

[2023-09-19T20:23:05.299Z]     response = rf.result()

[2023-09-19T20:23:05.299Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 881, in result

[2023-09-19T20:23:05.299Z]     raise self

[2023-09-19T20:23:05.299Z] grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:

[2023-09-19T20:23:05.299Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2023-09-19T20:23:05.299Z] 	details = "Deadline Exceeded"

[2023-09-19T20:23:05.299Z] 	debug_error_string = "UNKNOWN:Deadline Exceeded {created_time:"2023-09-19T20:22:44.82469156+00:00", grpc_status:4}"

[2023-09-19T20:23:05.299Z] >

[2023-09-19T20:23:05.299Z]  (api_request.py:45)

[2023-09-19T20:23:05.299Z] [2023-09-19 20:22:44 - ERROR - ci_test]: (api_response) : <_MultiThreadedRendezvous of RPC that terminated with:

[2023-09-19T20:23:05.299Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2023-09-19T20:23:05.299Z] 	details = "Deadline Exceeded"

[2023-09-19T20:23:05.299Z] 	debug_error_string = "UNKNOWN:Deadline Exceeded {created_time:"2023-09-19T20:22:44.82469156+00:00", grpc_status:4}"

[2023-09-19T20:23:05.299Z] > (api_request.py:46)
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-cron/detail/chaos-test-kafka-cron/7508/pipeline

log:
[artifacts-datanode-pod-failure-7508-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/12669299/artifacts-datanode-pod-failure-7508-pytest-logs.tar.gz)
[artifacts-datanode-pod-failure-7508-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/12669301/artifacts-datanode-pod-failure-7508-server-logs.tar.gz)

### Anything else?

cluster:4am,
ns: chaos-testing
release name: datanode-pod-failure-7508

**Comment by bigsheeper** [comment]
**use of closed network connection**:
![image](https://github.com/milvus-io/milvus/assets/42060877/88416efd-9d2e-418e-abc1-d505b6a42c7d)
https://grafana-devops.zilliz.cc/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bpod%3D~%5C%22datanode-pod-failure-7508-milvus-proxy-7dc546d4c6-wgxgd%5C%22%7D%20%7C~%20%5C%22receive%7Cdone%7Cfail%5C%22%20%7C~%20%5C%22flush%5C%22%22,%22hide%22:true%7D,%7B%22refId%22:%22B%22,%22expr%22:%22%7Bpod%3D~%5C%22datanode-pod-failure-7508-milvus-.*%5C%22%7D%20%7C~%20%5C%227c6103477e0f87e49f42ada2b7767c8d%5C%22%22%7D,%7B%22refId%22:%22C%22,%22expr%22:%22%7Bpod%3D~%5C%22datanode-pod-failure-7508-milvus-.*%5C%22%7D%20%7C~%20%5C%22datacoord%2F%7Cdatanode%2F%5C%22%20%7C~%20%5C%22444374320637157017%7CSessionManager.FlushChannels%5C%22%20!~%20%5C%22GetQueryVChanPositions%7Crecovery%7CGetRecoveryInfo%7Cchannel%20seek%20position%7CGetMetrics%7CSaveBinlogPath%5C%22%22%7D%5D,%22range%22:%7B%22from%22:%221695154799920%22,%22to%22:%221695155404850%22%7D%7D

**Comment by xiaofan-luan** [comment]
any reason why does it close?

the close policy might need to be refined, but it should be retried?

**Comment by bigsheeper** [comment]
> any reason why does it close?

FlushChannels rpc is closed by GetCompactionState rpc:
![image](https://github.com/milvus-io/milvus/assets/42060877/db3914cc-1df1-4bfc-aadf-b4800234d21a)
[grafana](https://grafana-devops.zilliz.cc/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22B%22,%22expr%22:%22%7Bpod%3D~%5C%22datanode-pod-failure-7508-milvus-.*%5C%22%7D%20%7C~%20%5C%22Datanode%20stop%7Creset%20connection%7Cempty%20grpc%20client%7Cuse%20of%20closed%20network%20connection%7CClientBase%20Call%20grpc%20call%20get%20error%5C%22%20%7C~%20%5C%22datanode-13%5C%22%20%7C~%20%5C%22WARN%7CERROR%5C%22%22%7D,%7B%22refId%22:%22A%22,%22expr%22:%22%7Bpod%3D~%5C%22datanode-pod-failure-7508-milvus-.*%5C%22%7D%20%7C~%20%5C%22Datanode%20stop%7Creset%20connection%7Cempty%20grpc%20client%5C%22%22,%22hide%22:true%7D%5D,%22range%22:%7B%22from%22:%221695154582000%22,%22to%22:%221695156030000%22%7D%7D)

> 
> the close policy might need to be refined, but it should be retried?

Flush rpc timed out before the retry was successful.

**Comment by bigsheeper** [comment]
/assign @zhuwenxing 
https://github.com/milvus-io/milvus/pull/27238 may help, please help to make verify
