### ISSUE TITLE
[Bug]: Search iterator using HNSW failed for `ef(1024) should be larger than k(10000)`

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#27284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.0
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):2.4.0.dev124
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Search iterator using HNSW failed for `ef(1024) should be larger than k(10000)`.
```
>>> batch_size = 1000
>>> search_params = {"metric_type": "COSINE", "params": {"ef": 1024}}
>>> search_iterator = collection.search_iterator(vectors[:1], "float_vector", search_params, batch_size=batch_size)
RPC error: [search], <MilvusException: (code=1, message=attempt #0: fail to Search, QueryNode ID=2, reason=worker(2) query failed: UnexpectedError: Assert "failed to search: out of range in json: ef(1024) should be larger than k(10000)" at /go/src/github.com/milvus-io/milvus/internal/core/src/index/VectorMemIndex.cpp:319: channel=by-dev-rootcoord-dml_0_443752784731590555v0: fail to search/query shard leader: attempt #1: no available shard delegator found: service unavailable: fail to search on all shard leaders)>, <Time:{'RPC start': '2023-08-23 11:11:06.121272', 'RPC error': '2023-08-23 11:11:06.728015'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/nico/lib/python3.10/site-packages/pymilvus/orm/collection.py", line 813, in search_iterator
    return SearchIterator(
  File "/root/nico/lib/python3.10/site-packages/pymilvus/orm/iterator.py", line 308, in __init__
    self.__init_search_iterator()
  File "/root/nico/lib/python3.10/site-packages/pymilvus/orm/iterator.py", line 311, in __init_search_iterator
    init_page = self.__execute_next_search(self._param, self._expr)
  File "/root/nico/lib/python3.10/site-packages/pymilvus/orm/iterator.py", line 469, in __execute_next_search
    res = self._conn.search(
  File "/root/nico/lib/python3.10/site-packages/pymilvus/decorators.py", line 127, in handler
    raise e from e
  File "/root/nico/lib/python3.10/site-packages/pymilvus/decorators.py", line 123, in handler
    return func(*args, **kwargs)
  File "/root/nico/lib/python3.10/site-packages/pymilvus/decorators.py", line 162, in handler
    return func(self, *args, **kwargs)
  File "/root/nico/lib/python3.10/site-packages/pymilvus/decorators.py", line 102, in handler
    raise e from e
  File "/root/nico/lib/python3.10/site-packages/pymilvus/decorators.py", line 68, in handler
    return func(*args, **kwargs)
  File "/root/nico/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 774, in search
    return self._execute_search_requests(
  File "/root/nico/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 735, in _execute_search_requests
    raise pre_err from pre_err
  File "/root/nico/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 726, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=attempt #0: fail to Search, QueryNode ID=2, reason=worker(2) query failed: UnexpectedError: Assert "failed to search: out of range in json: ef(1024) should be larger than k(10000)" at /go/src/github.com/milvus-io/milvus/internal/core/src/index/VectorMemIndex.cpp:319: channel=by-dev-rootcoord-dml_0_443752784731590555v0: fail to search/query shard leader: attempt #1: no available shard delegator found: service unavailable: fail to search on all shard leaders)>
```

### Expected Behavior

search successfully

**Comment by NicoYuan1986** [comment]
Verified fixed.
pymilvus: 2.3.1.post1.dev6
milvus: master-20231015-ff19cb27
