### ISSUE TITLE
[Bug]: [Azure][cluster] Serial execution of L0 level test cases, loading collection timeout

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#27282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230919-19e4deb7-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.0.post1.dev13
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Client pod and milvus are in the same cluster

test cases: https://github.com/milvus-io/milvus/tree/master/tests/python_client/testcases
cmd: `python3.8 -W ignore -m pytest  --tags L0 --timeout 600 -v --host=10.5.68.50`

server:
```
NAME                                                         READY   STATUS      RESTARTS      AGE   IP            NODE                                 NOMINATED NODE   READINESS GATES
in01-shaoyuetest-cluster-etcd-0                              1/1     Running     0             20h   10.5.67.237   aks-milvusdisk-37630825-vmss000000   <none>           <none>
in01-shaoyuetest-cluster-milvus-datanode-6d8b6b6c4b-j8bww    1/1     Running     7 (19h ago)   19h   10.5.68.59    aks-milvus-17178146-vmss000003       <none>           <none>
in01-shaoyuetest-cluster-milvus-indexnode-66fbb46ccb-bgs6s   1/1     Running     0             19h   10.5.68.48    aks-milvus-17178146-vmss000003       <none>           <none>
in01-shaoyuetest-cluster-milvus-mixcoord-5f9955ff54-8swmk    1/1     Running     0             19h   10.5.68.71    aks-milvus-17178146-vmss000003       <none>           <none>
in01-shaoyuetest-cluster-milvus-proxy-7b744ff978-45lxh       1/1     Running     0             19h   10.5.68.50    aks-milvus-17178146-vmss000003       <none>           <none>
in01-shaoyuetest-cluster-milvus-querynode-7cf645d876-rkfwq   1/1     Running     0             19h   10.5.68.70    aks-milvus-17178146-vmss000003       <none>           <none>
in01-shaoyuetest-cluster-pulsar-bookie-0                     1/1     Running     0             20h   10.5.68.53    aks-milvus-17178146-vmss000003       <none>           <none>
in01-shaoyuetest-cluster-pulsar-bookie-1                     1/1     Running     0             20h   10.5.67.179   aks-pulsar-39686421-vmss000001       <none>           <none>
in01-shaoyuetest-cluster-pulsar-bookie-2                     1/1     Running     0             20h   10.5.67.118   aks-pulsar-39686421-vmss000000       <none>           <none>
in01-shaoyuetest-cluster-pulsar-bookie-init-2zmcj            0/1     Completed   0             20h   10.5.67.120   aks-pulsar-39686421-vmss000000       <none>           <none>
in01-shaoyuetest-cluster-pulsar-broker-0                     1/1     Running     0             20h   10.5.68.4     aks-milvus-17178146-vmss000003       <none>           <none>
in01-shaoyuetest-cluster-pulsar-proxy-0                      1/1     Running     0             20h   10.5.67.227   aks-milvusdisk-37630825-vmss000000   <none>           <none>
in01-shaoyuetest-cluster-pulsar-pulsar-init-54cxv            0/1     Completed   0             20h   10.5.67.174   aks-pulsar-39686421-vmss000001       <none>           <none>
in01-shaoyuetest-cluster-pulsar-recovery-0                   1/1     Running     0             20h   10.5.67.238   aks-milvusdisk-37630825-vmss000000   <none>           <none>
in01-shaoyuetest-cluster-pulsar-zookeeper-0                  1/1     Running     0             20h   10.5.67.136   aks-pulsar-39686421-vmss000002       <none>           <none>
in01-shaoyuetest-cluster-pulsar-zookeeper-1                  1/1     Running     0             20h   10.5.68.56    aks-milvus-17178146-vmss000003       <none>           <none>
in01-shaoyuetest-cluster-pulsar-zookeeper-2                  1/1     Running     0             19h   10.5.67.107   aks-pulsar-39686421-vmss000000       <none>           <none>
```

client logs:
[ci_logs.tar.gz](https://github.com/milvus-io/milvus/files/12679803/ci_logs.tar.gz)
[ci_nohup.log](https://github.com/milvus-io/milvus/files/12679804/ci_nohup.log)
```
[2023-09-20 15:25:34 - DEBUG - ci_test]: (api_response) : <Collection>:
-------------
<name>: search_collection_PMQrqBRv
<description>: 
<schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FL......  (api_request.py:37)
[2023-09-20 15:25:34 - INFO - ci_test]: inserted 2000 data into collection search_collection_PMQrqBRv (common_func.py:1219)
[2023-09-20 15:25:34 - DEBUG - ci_test]: Dynamic field is enabled: False (common_func.py:1221)
[2023-09-20 15:25:34 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [      int64   float varchar                         json_field                                       float_vector
0         0     0.0       0        {'number': 0, 'float': 0.0}  [0.11367960501424806, 0.0508464477300253, 0.06...
1         1     1.0       1        {'number': 1, 'float': 1.0}  [0.0244......, kwargs: {'timeout': 180} (api_request.py:62)
[2023-09-20 15:25:34 - DEBUG - ci_test]: (api_response) : (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 444392678123110403, success count: 2000, err count: 0)  (api_request.py:37)
[2023-09-20 15:25:34 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)
[2023-09-20 15:25:36 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)
[2023-09-20 15:25:36 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)
[2023-09-20 15:25:37 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)
[2023-09-20 15:25:37 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['float_vector', {'index_type': 'FLAT', 'params': {}, 'metric_type': 'COSINE'}], kwargs: {'timeout': 1200, 'index_name': ''} (api_request.py:62)
[2023-09-20 15:25:37 - DEBUG - ci_test]: (api_response) : Status(code=0, message=)  (api_request.py:37)
[2023-09-20 15:25:37 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 180], kwargs: {} (api_request.py:62)
[2023-09-20 15:28:38 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=wait for loading collection timeout, collection: search_collection_PMQrqBRv)>, <Time:{'RPC start': '2023-09-20 15:25:37.918967', 'RPC error': '2023-09-20 15:28:38.124572'}> (decorators.py:126)
[2023-09-20 15:28:38 - WARNING - pymilvus.decorators]: Retry timeout: 180s (decorators.py:94)
[2023-09-20 15:28:38 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for loading collection timeout, collection: search_collection_PMQrqBRv)>, <Time:{'RPC start': '2023-09-20 15:25:37.898519', 'RPC error': '2023-09-20 15:28:38.124803'}> (decorators.py:126)
[2023-09-20 15:28:38 - ERROR - ci_test]: Traceback (most recent call last):
  File "/root/work/python_client/utils/api_request.py", line 32, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/root/work/python_client/utils/api_request.py", line 63, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 419, in load
    conn.load_collection(
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 127, in handler
    raise e from e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 123, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 162, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 95, in handler
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for loading collection timeout, collection: search_collection_PMQrqBRv)>
 (api_request.py:45)
[2023-09-20 15:28:38 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for loading collection timeout, collection: search_collection_PMQrqBRv)> (api_request.py:46)
------------- generated html file: file:///tmp/ci_logs/report.html -------------
=========================== short test summary info ============================
FAILED testcases/test_collection.py::TestLoadCollection::test_load_collection_after_index
FAILED testcases/test_collection.py::TestLoadCollection::test_load_collection_after_load_release
FAILED testcases/test_collection.py::TestReleaseAdvanced::test_release_collection_during_searching
FAILED testcases/test_collection.py::TestReleaseAdvanced::test_release_indexed_collection_during_searching
FAILED testcases/test_collection.py::TestLoadPartition::test_load_partition_after_index_binary[JACCARD-binary_index0]
FAILED testcases/test_collection.py::TestLoadPartition::test_load_partition_after_index_binary[JACCARD-binary_index1]
FAILED testcases/test_collection.py::TestLoadPartition::test_load_partition_after_index_binary[HAMMING-binary_index0]
FAILED testcases/test_collection.py::TestLoadPartition::test_load_partition_after_index_binary[HAMMING-binary_index1]
FAILED testcases/test_collection.py::TestLoadPartition::test_load_partition_after_index_binary[SUBSTRUCTURE-binary_index0]
FAILED testcases/test_collection.py::TestLoadPartition::test_load_partition_after_index_binary[SUBSTRUCTURE-binary_index1]
FAILED testcases/test_collection.py::TestLoadPartition::test_load_partition_after_index_binary[SUPERSTRUCTURE-binary_index0]
FAILED testcases/test_collection.py::TestLoadPartition::test_load_partition_after_index_binary[SUPERSTRUCTURE-binary_index1]
FAILED testcases/test_collection.py::TestLoadPartition::test_load_partitions_release_collection
FAILED testcases/test_compaction.py::TestCompactionOperation::test_compact_merge_two_segments
FAILED testcases/test_delete.py::TestDeleteParams::test_delete_entities[False]
FAILED testcases/test_delete.py::TestDeleteParams::test_delete_entities[True]
FAILED testcases/test_delete.py::TestDeleteParams::test_delete_entities_with_range[False]
FAILED testcases/test_delete.py::TestDeleteParams::test_delete_entities_with_range[True]
FAILED testcases/test_delete.py::TestDeleteParams::test_delete_partition - As...
FAILED testcases/test_delete.py::TestDeleteOperation::test_delete_auto_id_collection
FAILED testcases/test_delete.py::TestDeleteString::test_delete_invalid_expr
FAILED testcases/test_index.py::TestNewIndexBinary::test_create_index_search_with_query_vectors
FAILED testcases/test_index.py::TestNewIndexAsync::test_create_index_drop[False]
FAILED testcases/test_index.py::TestNewIndexAsync::test_create_index_drop[True]
FAILED testcases/test_insert.py::TestUpsertValid::test_upsert_data_pk_exist[0]
FAILED testcases/test_insert.py::TestUpsertValid::test_upsert_data_pk_exist[1500]
FAILED testcases/test_insert.py::TestUpsertValid::test_upsert_data_pk_exist[2500]
FAILED testcases/test_insert.py::TestUpsertValid::test_upsert_data_pk_exist[3500]
FAILED testcases/test_partition_key.py::TestPartitionKeyParams::test_partition_key_on_field_schema[int64]
FAILED testcases/test_partition_key.py::TestPartitionKeyParams::test_partition_key_on_field_schema[varchar]
FAILED testcases/test_partition_key.py::TestPartitionKeyParams::test_partition_key_on_collection_schema[True-int64]
FAILED testcases/test_partition_key.py::TestPartitionKeyParams::test_partition_key_on_collection_schema[True-varchar]
FAILED testcases/test_partition_key.py::TestPartitionKeyParams::test_partition_key_on_collection_schema[False-int64]
FAILED testcases/test_partition_key.py::TestPartitionKeyParams::test_partition_key_on_collection_schema[False-varchar]
FAILED testcases/test_query.py::TestQueryParams::test_query[True] - Assertion...
FAILED testcases/test_query.py::TestQueryParams::test_query[False] - Assertio...
FAILED testcases/test_query.py::TestQueryParams::test_query_auto_id_collection
FAILED testcases/test_query.py::TestQueryParams::test_query_expr_empty[True-10]
FAILED testcases/test_query.py::TestQueryParams::test_query_expr_empty[True-100]
FAILED testcases/test_query.py::TestQueryParams::test_query_expr_empty[True-1000]
FAILED testcases/test_query.py::TestQueryParams::test_query_expr_empty[False-10]
FAILED testcases/test_query.py::TestQueryParams::test_query_expr_empty[False-100]
FAILED testcases/test_query.py::TestQueryParams::test_query_expr_empty[False-1000]
FAILED testcases/test_query.py::TestQueryParams::test_query_expr_with_limit_offset_out_of_range
FAILED testcases/test_query.py::TestQueryParams::test_query_output_one_field[True]
FAILED testcases/test_query.py::TestQueryParams::test_query_output_one_field[False]
FAILED testcases/test_query.py::TestQueryParams::test_query_partition - Faile...
FAILED testcases/test_query.py::TestQueryOperation::test_query_after_index - ...
FAILED testcases/test_query.py::TestQueryCount::test_count_with_expr - Assert...
FAILED testcases/test_query.py::TestQueryIterator::test_query_iterator_normal
FAILED testcases/test_query.py::TestQueryIterator::test_query_iterator_empty_expr[True-100]
FAILED testcases/test_query.py::TestQueryIterator::test_query_iterator_empty_expr[True-500]
FAILED testcases/test_query.py::TestQueryIterator::test_query_iterator_empty_expr[False-100]
FAILED testcases/test_query.py::TestQueryIterator::test_query_iterator_empty_expr[False-500]
FAILED testcases/test_search.py::TestCollectionSearch::test_search_normal[200-32-False-False-True]
FAILED testcases/test_search.py::TestCollectionSearch::test_search_normal[200-32-False-False-False]
FAILED testcases/test_search.py::TestCollectionSearch::test_search_normal[200-32-False-True-True]
FAILED testcases/test_search.py::TestCollectionSearch::test_search_normal[200-32-False-True-False]
FAILED testcases/test_search.py::TestCollectionSearch::test_search_normal[200-32-True-False-True]
FAILED testcases/test_search.py::TestCollectionSearch::test_search_normal[200-32-True-False-False]
FAILED testcases/test_search.py::TestCollectionSearch::test_search_normal[200-32-True-True-True]
FAILED testcases/test_search.py::TestCollectionSearch::test_search_normal[200-32-True-True-False]
FAILED testcases/test_search.py::TestCollectionSearch::test_search_normal[200-128-False-False-True]
FAILED testcases/test_search.py::TestCollectionSearch::test_search_normal[200-128-False-False-False]
FAILED testcases/test_search.py::TestCollectionSearch::test_search_normal[200-128-False-True-True]
FAILED testcases/test_search.py::TestCollectionSearch::test_search_normal[200-128-False-True-False]
FAILED testcases/test_search.py::TestCollectionSearch::test_search_normal[200-128-True-False-True]
FAILED testcases/test_search.py::TestCollectionSearch::test_search_normal[200-128-True-False-False]
FAILED testcases/test_search.py::TestCollectionSearch::test_search_normal[200-128-True-True-True]
FAILED testcases/test_search.py::TestCollectionSearch::test_search_normal[200-128-True-True-False]
FAILED testcases/test_search.py::TestCollectionSearch::test_search_normal_without_specify_metric_type
FAILED testcases/test_search.py::TestCollectionSearch::test_search_normal_without_specify_anns_field
FAILED testcases/test_search.py::TestCollectionSearch::test_search_with_hit_vectors[200-32-False-True]
FAILED testcases/test_search.py::TestCollectionSearch::test_search_with_hit_vectors[200-32-False-False]
FAILED testcases/test_search.py::TestCollectionSearch::test_search_with_hit_vectors[200-32-True-True]
FAILED testcases/test_search.py::TestCollectionSearch::test_search_with_hit_vectors[200-32-True-False]
FAILED testcases/test_search.py::TestCollectionSearch::test_search_with_hit_vectors[200-128-False-True]
FAILED testcases/test_search.py::TestCollectionSearch::test_search_with_hit_vectors[200-128-False-False]
FAILED testcases/test_search.py::TestCollectionSearch::test_search_with_hit_vectors[200-128-True-True]
FAILED testcases/test_search.py::TestCollectionSearch::test_search_with_hit_vectors[200-128-True-False]
FAILED testcases/test_search.py::TestSearchDSL::test_query_vector_only - Asse...
= 81 failed, 112 passed, 1 skipped, 6552 deselected, 1 xfailed in 23121.61s (6:25:21) =
```

**Comment by wangting0128** [comment]
image: 2.3.0-20230927-eebabcd-42e225a
**Not reproduce, close it now**
