### ISSUE TITLE
[Bug]: Search failed with error `segment lacks: channel=by-dev-rootcoord-dml_1_xxxv0: channel not available` after etcd pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#27283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.0-20230920-509e7a39-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):kafka    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

db: default
collection name: Hello_Milvus
```
[2023-09-21T00:15:59.392Z] [2023-09-21 00:15:59 - INFO - ci_test]: all database: ['default', 'prod'] (test_data_persistence.py:26)

[2023-09-21T00:15:59.953Z] [2023-09-21 00:15:59 - INFO - ci_test]: [test][2023-09-21T00:15:59Z] [0.50723404s] Hello_Milvus flush -> None (wrapper.py:30)

[2023-09-21T00:15:59.956Z] [2023-09-21 00:15:59 - INFO - ci_test]: assert create collection: 0.004361152648925781, init_entities: 4000 (test_data_persistence.py:38)

[2023-09-21T00:16:00.515Z] [2023-09-21 00:16:00 - INFO - ci_test]: [test][2023-09-21T00:15:59Z] [0.49089945s] Hello_Milvus insert -> (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 444401021159997441, success count: 2000, err count: 0) (wrapper.py:30)

[2023-09-21T00:16:00.516Z] [2023-09-21 00:16:00 - INFO - ci_test]: assert insert: 0.4911682605743408 (test_data_persistence.py:45)

[2023-09-21T00:16:03.795Z] [2023-09-21 00:16:03 - INFO - ci_test]: [test][2023-09-21T00:16:00Z] [3.14044392s] Hello_Milvus flush -> None (wrapper.py:30)

[2023-09-21T00:16:04.051Z] [2023-09-21 00:16:04 - INFO - ci_test]: [test][2023-09-21T00:16:03Z] [0.51781868s] Hello_Milvus flush -> None (wrapper.py:30)

[2023-09-21T00:16:04.613Z] [2023-09-21 00:16:04 - INFO - ci_test]: [test][2023-09-21T00:16:04Z] [0.50783527s] Hello_Milvus flush -> None (wrapper.py:30)

[2023-09-21T00:16:04.613Z] [2023-09-21 00:16:04 - INFO - ci_test]: assert flush: 3.6611857414245605, entities: 6000 (test_data_persistence.py:55)

[2023-09-21T00:16:04.613Z] [2023-09-21 00:16:04 - INFO - ci_test]: index info: [{'collection': 'Hello_Milvus', 'field': 'float_vector', 'index_name': 'test_dOVirOmk', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}, {'collection': 'Hello_Milvus', 'field': 'varchar', 'index_name': 'test_kBSH8S7w', 'index_param': {}}] (test_data_persistence.py:74)

[2023-09-21T00:16:04.613Z] [2023-09-21 00:16:04 - INFO - ci_test]: [test][2023-09-21T00:16:04Z] [0.00442452s] Hello_Milvus load -> None (wrapper.py:30)

[2023-09-21T00:16:14.558Z] [2023-09-21 00:16:14 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=failed to search: attempt #0: fail to get shard leaders from QueryCoord: segment=444400605126336226: segment lacks: channel=by-dev-rootcoord-dml_1_444400605126336099v0: channel not available: attempt #1: fail to get shard leaders from QueryCoord: segment=444400605126336226: segment lacks: channel=by-dev-rootcoord-dml_1_444400605126336099v0: channel not available: attempt #2: fail to get shard leaders from QueryCoord: segment=444400605126336226: segment lacks: channel=by-dev-rootcoord-dml_1_444400605126336099v0: channel not available: attempt #3: fail to get shard leaders from QueryCoord: segment=444400605126336226: segment lacks: channel=by-dev-rootcoord-dml_1_444400605126336099v0: channel not available: attempt #4: fail to get shard leaders from QueryCoord: segment=444400605126336226: segment lacks: channel=by-dev-rootcoord-dml_1_444400605126336099v0: channel not available: attempt #5: fail to get shard leaders from QueryCoord: segment=444400605126336226: segment lacks: channel=by-dev-rootcoord-dml_1_444400605126336099v0: channel not available: attempt #6: fail to get shard leaders from QueryCoord: segment=444400605126336226: segment lacks: channel=by-dev-rootcoord-dml_1_444400605126336099v0: channel not available: context done during sleep after run#6: context deadline exceeded)>, <Time:{'RPC start': '2023-09-21 00:16:04.527210', 'RPC error': '2023-09-21 00:16:14.532989'}> (decorators.py:126)

[2023-09-21T00:16:14.558Z] [2023-09-21 00:16:14 - ERROR - ci_test]: Traceback (most recent call last):

[2023-09-21T00:16:14.558Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2023-09-21T00:16:14.558Z]     res = func(*args, **_kwargs)

[2023-09-21T00:16:14.558Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2023-09-21T00:16:14.558Z]     return func(*arg, **kwargs)

[2023-09-21T00:16:14.558Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 778, in search

[2023-09-21T00:16:14.558Z]     res = conn.search(

[2023-09-21T00:16:14.558Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 127, in handler

[2023-09-21T00:16:14.558Z]     raise e from e

[2023-09-21T00:16:14.558Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 123, in handler

[2023-09-21T00:16:14.558Z]     return func(*args, **kwargs)

[2023-09-21T00:16:14.558Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 162, in handler

[2023-09-21T00:16:14.558Z]     return func(self, *args, **kwargs)

[2023-09-21T00:16:14.558Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 102, in handler

[2023-09-21T00:16:14.558Z]     raise e from e

[2023-09-21T00:16:14.558Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 68, in handler

[2023-09-21T00:16:14.558Z]     return func(*args, **kwargs)

[2023-09-21T00:16:14.558Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 774, in search

[2023-09-21T00:16:14.558Z]     return self._execute_search_requests(

[2023-09-21T00:16:14.558Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 735, in _execute_search_requests

[2023-09-21T00:16:14.558Z]     raise pre_err from pre_err

[2023-09-21T00:16:14.558Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 726, in _execute_search_requests

[2023-09-21T00:16:14.558Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2023-09-21T00:16:14.558Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=failed to search: attempt #0: fail to get shard leaders from QueryCoord: segment=444400605126336226: segment lacks: channel=by-dev-rootcoord-dml_1_444400605126336099v0: channel not available: attempt #1: fail to get shard leaders from QueryCoord: segment=444400605126336226: segment lacks: channel=by-dev-rootcoord-dml_1_444400605126336099v0: channel not available: attempt #2: fail to get shard leaders from QueryCoord: segment=444400605126336226: segment lacks: channel=by-dev-rootcoord-dml_1_444400605126336099v0: channel not available: attempt #3: fail to get shard leaders from QueryCoord: segment=444400605126336226: segment lacks: channel=by-dev-rootcoord-dml_1_444400605126336099v0: channel not available: attempt #4: fail to get shard leaders from QueryCoord: segment=444400605126336226: segment lacks: channel=by-dev-rootcoord-dml_1_444400605126336099v0: channel not available: attempt #5: fail to get shard leaders from QueryCoord: segment=444400605126336226: segment lacks: channel=by-dev-rootcoord-dml_1_444400605126336099v0: channel not available: attempt #6: fail to get shard leaders from QueryCoord: segment=444400605126336226: segment lacks: channel=by-dev-rootcoord-dml_1_444400605126336099v0: channel not available: context done during sleep after run#6: context deadline exceeded)>

[2023-09-21T00:16:14.559Z]  (api_request.py:45)

[2023-09-21T00:16:14.559Z] [2023-09-21 00:16:14 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=failed to search: attempt #0: fail to get shard leaders from QueryCoord: segment=444400605126336226: segment lacks: channel=by-dev-rootcoord-dml_1_444400605126336099v0: channel not available: attempt #1: fail to get shard leaders from QueryCoord: segment=4444006051...... (api_request.py:46)

[2023-09-21T00:16:14.814Z] FAILED
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-for-release-cron/detail/chaos-test-kafka-for-release-cron/7570/pipeline

log:
[artifacts-etcd-pod-kill-7570-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/12679842/artifacts-etcd-pod-kill-7570-pytest-logs.tar.gz)
[artifacts-etcd-pod-kill-7570-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/12679844/artifacts-etcd-pod-kill-7570-server-logs.tar.gz)

### Anything else?

cluster:4am
ns: chaos-testing
release name: etcd-pod-kill-7570

**Comment by zhuwenxing** [comment]
also failed at querynode pod kill chaos test
db: default
collection name: Hello_Milvus

```
[2023-09-22T07:54:09.946Z] [2023-09-22 07:54:09 - INFO - ci_test]: [test][2023-09-22T07:54:09Z] [0.53790731s] Hello_Milvus flush -> None (wrapper.py:30)

[2023-09-22T07:54:09.946Z] [2023-09-22 07:54:09 - INFO - ci_test]: assert create collection: 0.010680675506591797, init_entities: 4000 (test_data_persistence.py:38)

[2023-09-22T07:54:10.913Z] [2023-09-22 07:54:10 - INFO - ci_test]: [test][2023-09-22T07:54:09Z] [0.95480305s] Hello_Milvus insert -> (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 444430876844490755, success count: 2000, err count: 0) (wrapper.py:30)

[2023-09-22T07:54:10.915Z] [2023-09-22 07:54:10 - INFO - ci_test]: assert insert: 0.9552209377288818 (test_data_persistence.py:45)

[2023-09-22T07:54:14.217Z] [2023-09-22 07:54:13 - INFO - ci_test]: [test][2023-09-22T07:54:10Z] [2.58924453s] Hello_Milvus flush -> None (wrapper.py:30)

[2023-09-22T07:54:14.788Z] [2023-09-22 07:54:14 - INFO - ci_test]: [test][2023-09-22T07:54:13Z] [1.01846581s] Hello_Milvus flush -> None (wrapper.py:30)

[2023-09-22T07:54:15.059Z] [2023-09-22 07:54:14 - INFO - ci_test]: [test][2023-09-22T07:54:14Z] [0.50879017s] Hello_Milvus flush -> None (wrapper.py:30)

[2023-09-22T07:54:15.059Z] [2023-09-22 07:54:14 - INFO - ci_test]: assert flush: 3.6110081672668457, entities: 6000 (test_data_persistence.py:55)

[2023-09-22T07:54:15.059Z] [2023-09-22 07:54:14 - INFO - ci_test]: index info: [{'collection': 'Hello_Milvus', 'field': 'float_vector', 'index_name': 'test_KCWSyUwz', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}, {'collection': 'Hello_Milvus', 'field': 'varchar', 'index_name': 'test_0g30kB6d', 'index_param': {}}] (test_data_persistence.py:74)

[2023-09-22T07:54:15.059Z] [2023-09-22 07:54:15 - INFO - ci_test]: [test][2023-09-22T07:54:15Z] [0.03295811s] Hello_Milvus load -> None (wrapper.py:30)

[2023-09-22T07:54:25.081Z] [2023-09-22 07:54:25 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=failed to search: attempt #0: fail to get shard leaders from QueryCoord: segment=444430485821464612: segment lacks: channel=by-dev-rootcoord-dml_1_444430485821464518v0: channel not available: attempt #1: fail to get shard leaders from QueryCoord: segment=444430485821464612: segment lacks: channel=by-dev-rootcoord-dml_1_444430485821464518v0: channel not available: attempt #2: fail to get shard leaders from QueryCoord: segment=444430485821464612: segment lacks: channel=by-dev-rootcoord-dml_1_444430485821464518v0: channel not available: attempt #3: fail to get shard leaders from QueryCoord: segment=444430485821464612: segment lacks: channel=by-dev-rootcoord-dml_1_444430485821464518v0: channel not available: attempt #4: fail to get shard leaders from QueryCoord: segment=444430485821464537: segment lacks: channel=by-dev-rootcoord-dml_1_444430485821464518v0: channel not available: attempt #5: fail to get shard leaders from QueryCoord: segment=444430485821464612: segment lacks: channel=by-dev-rootcoord-dml_1_444430485821464518v0: channel not available: attempt #6: fail to get shard leaders from QueryCoord: segment=444430485821464612: segment lacks: channel=by-dev-rootcoord-dml_1_444430485821464518v0: channel not available: context done during sleep after run#6: context deadline exceeded)>, <Time:{'RPC start': '2023-09-22 07:54:15.034599', 'RPC error': '2023-09-22 07:54:25.040655'}> (decorators.py:126)

[2023-09-22T07:54:25.082Z] [2023-09-22 07:54:25 - ERROR - ci_test]: Traceback (most recent call last):

[2023-09-22T07:54:25.082Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2023-09-22T07:54:25.082Z]     res = func(*args, **_kwargs)

[2023-09-22T07:54:25.082Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2023-09-22T07:54:25.082Z]     return func(*arg, **kwargs)

[2023-09-22T07:54:25.082Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 778, in search

[2023-09-22T07:54:25.082Z]     res = conn.search(

[2023-09-22T07:54:25.082Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 127, in handler

[2023-09-22T07:54:25.082Z]     raise e from e

[2023-09-22T07:54:25.082Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 123, in handler

[2023-09-22T07:54:25.082Z]     return func(*args, **kwargs)

[2023-09-22T07:54:25.082Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 162, in handler

[2023-09-22T07:54:25.082Z]     return func(self, *args, **kwargs)

[2023-09-22T07:54:25.082Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 102, in handler

[2023-09-22T07:54:25.082Z]     raise e from e

[2023-09-22T07:54:25.082Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 68, in handler

[2023-09-22T07:54:25.082Z]     return func(*args, **kwargs)

[2023-09-22T07:54:25.082Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 774, in search

[2023-09-22T07:54:25.082Z]     return self._execute_search_requests(

[2023-09-22T07:54:25.082Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 735, in _execute_search_requests

[2023-09-22T07:54:25.082Z]     raise pre_err from pre_err

[2023-09-22T07:54:25.082Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 726, in _execute_search_requests

[2023-09-22T07:54:25.082Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2023-09-22T07:54:25.082Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=failed to search: attempt #0: fail to get shard leaders from QueryCoord: segment=444430485821464612: segment lacks: channel=by-dev-rootcoord-dml_1_444430485821464518v0: channel not available: attempt #1: fail to get shard leaders from QueryCoord: segment=444430485821464612: segment lacks: channel=by-dev-rootcoord-dml_1_444430485821464518v0: channel not available: attempt #2: fail to get shard leaders from QueryCoord: segment=444430485821464612: segment lacks: channel=by-dev-rootcoord-dml_1_444430485821464518v0: channel not available: attempt #3: fail to get shard leaders from QueryCoord: segment=444430485821464612: segment lacks: channel=by-dev-rootcoord-dml_1_444430485821464518v0: channel not available: attempt #4: fail to get shard leaders from QueryCoord: segment=444430485821464537: segment lacks: channel=by-dev-rootcoord-dml_1_444430485821464518v0: channel not available: attempt #5: fail to get shard leaders from QueryCoord: segment=444430485821464612: segment lacks: channel=by-dev-rootcoord-dml_1_444430485821464518v0: channel not available: attempt #6: fail to get shard leaders from QueryCoord: segment=444430485821464612: segment lacks: channel=by-dev-rootcoord-dml_1_444430485821464518v0: channel not available: context done during sleep after run#6: context deadline exceeded)>

[2023-09-22T07:54:25.082Z]  (api_request.py:45)
```

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-for-release-cron/detail/chaos-test-kafka-for-release-cron/7631/pipeline
log:

[artifacts-querynode-pod-kill-7631-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/12698540/artifacts-querynode-pod-kill-7631-server-logs.tar.gz)

[artifacts-querynode-pod-kill-7631-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/12698541/artifacts-querynode-pod-kill-7631-pytest-logs.tar.gz)

**Comment by yanliang567** [comment]
@zhuwenxing was this fixed?

**Comment by zhuwenxing** [comment]
Not reproduced recently
