### ISSUE TITLE
[Bug]: Load collection failed with error `empty grpc client: find no available querycoord, check querycoord state` after etcd pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#27314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.0-20230921-6ec7506b-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):kafka    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```

[2023-09-22T05:33:08.523Z] [2023-09-22 05:33:04 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=call query coordinator LoadCollection: stack trace: /go/src/github.com/milvus-io/milvus/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace

[2023-09-22T05:33:08.527Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:485 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call

[2023-09-22T05:33:08.527Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:499 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall

[2023-09-22T05:33:08.527Z] /go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/client/client.go:109 github.com/milvus-io/milvus/internal/distributed/querycoord/client.wrapGrpcCall[...]

[2023-09-22T05:33:08.527Z] /go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/client/client.go:161 github.com/milvus-io/milvus/internal/distributed/querycoord/client.(*Client).LoadCollection

[2023-09-22T05:33:08.527Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task.go:1457 github.com/milvus-io/milvus/internal/proxy.(*loadCollectionTask).Execute

[2023-09-22T05:33:08.527Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:457 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask

[2023-09-22T05:33:08.527Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:484 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop

[2023-09-22T05:33:08.527Z] /usr/local/go/src/runtime/asm_amd64.s:1598 runtime.goexit: attempt #0: empty grpc client: find no available querycoord, check querycoord state: attempt #1: empty grpc client: find no available querycoord, check querycoord state: attempt #2: empty grpc client: find no available querycoord, check querycoord state: attempt #3: empty grpc client: find no available querycoord, check querycoord state: attempt #4: empty grpc client: find no available querycoord, check querycoord state: attempt #5: empty grpc client: find no available querycoord, check querycoord state: attempt #6: empty grpc client: find no available querycoord, check querycoord state: attempt #7: empty grpc client: find no available querycoord, check querycoord state: attempt #8: empty grpc client: find no available querycoord, check querycoord state: attempt #9: empty grpc client: find no available querycoord, check querycoord state)>, <Time:{'RPC start': '2023-09-22 05:32:11.885019', 'RPC error': '2023-09-22 05:33:04.523622'}> (decorators.py:126)

[2023-09-22T05:33:08.527Z] [2023-09-22 05:33:04 - ERROR - ci_test]: Traceback (most recent call last):

[2023-09-22T05:33:08.527Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2023-09-22T05:33:08.527Z]     res = func(*args, **_kwargs)

[2023-09-22T05:33:08.527Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2023-09-22T05:33:08.527Z]     return func(*arg, **kwargs)

[2023-09-22T05:33:08.527Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 419, in load

[2023-09-22T05:33:08.527Z]     conn.load_collection(

[2023-09-22T05:33:08.527Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 127, in handler

[2023-09-22T05:33:08.527Z]     raise e from e

[2023-09-22T05:33:08.527Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 123, in handler

[2023-09-22T05:33:08.527Z]     return func(*args, **kwargs)

[2023-09-22T05:33:08.527Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 162, in handler

[2023-09-22T05:33:08.527Z]     return func(self, *args, **kwargs)

[2023-09-22T05:33:08.527Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 102, in handler

[2023-09-22T05:33:08.527Z]     raise e from e

[2023-09-22T05:33:08.527Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 68, in handler

[2023-09-22T05:33:08.527Z]     return func(*args, **kwargs)

[2023-09-22T05:33:08.527Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 1020, in load_collection

[2023-09-22T05:33:08.528Z]     raise MilvusException(response.error_code, response.reason)

[2023-09-22T05:33:08.528Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=call query coordinator LoadCollection: stack trace: /go/src/github.com/milvus-io/milvus/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace

[2023-09-22T05:33:08.528Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:485 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call

[2023-09-22T05:33:08.528Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:499 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall

[2023-09-22T05:33:08.528Z] /go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/client/client.go:109 github.com/milvus-io/milvus/internal/distributed/querycoord/client.wrapGrpcCall[...]

[2023-09-22T05:33:08.528Z] /go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/client/client.go:161 github.com/milvus-io/milvus/internal/distributed/querycoord/client.(*Client).LoadCollection

[2023-09-22T05:33:08.528Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task.go:1457 github.com/milvus-io/milvus/internal/proxy.(*loadCollectionTask).Execute

[2023-09-22T05:33:08.528Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:457 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask

[2023-09-22T05:33:08.528Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:484 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop

[2023-09-22T05:33:08.528Z] /usr/local/go/src/runtime/asm_amd64.s:1598 runtime.goexit: attempt #0: empty grpc client: find no available querycoord, check querycoord state: attempt #1: empty grpc client: find no available querycoord, check querycoord state: attempt #2: empty grpc client: find no available querycoord, check querycoord state: attempt #3: empty grpc client: find no available querycoord, check querycoord state: attempt #4: empty grpc client: find no available querycoord, check querycoord state: attempt #5: empty grpc client: find no available querycoord, check querycoord state: attempt #6: empty grpc client: find no available querycoord, check querycoord state: attempt #7: empty grpc client: find no available querycoord, check querycoord state: attempt #8: empty grpc client: find no available querycoord, check querycoord state: attempt #9: empty grpc client: find no available querycoord, check querycoord state)>

[2023-09-22T05:33:08.528Z]  (api_request.py:45)
```

### Milvus Log

```
[2023-09-22T05:31:06.215Z] + kubectl get pods -o wide

[2023-09-22T05:31:06.217Z] + grep etcd-pod-kill-7627

[2023-09-22T05:31:06.778Z] etcd-pod-kill-7627-0                                              1/1     Running       0                7m6s    10.104.19.153   4am-node28   <none>           <none>

[2023-09-22T05:31:06.778Z] etcd-pod-kill-7627-1                                              1/1     Running       0                7m6s    10.104.18.85    4am-node25   <none>           <none>

[2023-09-22T05:31:06.778Z] etcd-pod-kill-7627-2                                              1/1     Running       0                7m6s    10.104.4.149    4am-node11   <none>           <none>

[2023-09-22T05:31:06.778Z] etcd-pod-kill-7627-kafka-0                                        2/2     Running       2 (24m ago)      27m     10.104.19.138   4am-node28   <none>           <none>

[2023-09-22T05:31:06.778Z] etcd-pod-kill-7627-kafka-1                                        2/2     Running       0                27m     10.104.13.63    4am-node16   <none>           <none>

[2023-09-22T05:31:06.778Z] etcd-pod-kill-7627-kafka-2                                        2/2     Running       0                27m     10.104.4.90     4am-node11   <none>           <none>

[2023-09-22T05:31:06.778Z] etcd-pod-kill-7627-kafka-exporter-56b547fc44-lg6lc                1/1     Running       6 (24m ago)      27m     10.104.19.127   4am-node28   <none>           <none>

[2023-09-22T05:31:06.778Z] etcd-pod-kill-7627-milvus-datacoord-549659bf74-kcpmq              1/1     Running       1 (5m13s ago)    27m     10.104.17.227   4am-node23   <none>           <none>

[2023-09-22T05:31:06.779Z] etcd-pod-kill-7627-milvus-datanode-6565997d67-b4jzz               1/1     Running       2 (7m37s ago)    27m     10.104.1.92     4am-node10   <none>           <none>

[2023-09-22T05:31:06.779Z] etcd-pod-kill-7627-milvus-datanode-6565997d67-r7kcg               1/1     Running       0                27m     10.104.14.245   4am-node18   <none>           <none>

[2023-09-22T05:31:06.779Z] etcd-pod-kill-7627-milvus-indexcoord-c5ffd6645-4vxhr              1/1     Running       0                27m     10.104.18.216   4am-node25   <none>           <none>

[2023-09-22T05:31:06.779Z] etcd-pod-kill-7627-milvus-indexnode-784ff6b64b-2lplt              1/1     Running       2 (7m37s ago)    27m     10.104.23.84    4am-node27   <none>           <none>

[2023-09-22T05:31:06.779Z] etcd-pod-kill-7627-milvus-indexnode-784ff6b64b-4dxfp              1/1     Running       2 (7m51s ago)    27m     10.104.24.234   4am-node29   <none>           <none>

[2023-09-22T05:31:06.779Z] etcd-pod-kill-7627-milvus-indexnode-784ff6b64b-gfd79              1/1     Running       2 (7m41s ago)    27m     10.104.17.229   4am-node23   <none>           <none>

[2023-09-22T05:31:06.779Z] etcd-pod-kill-7627-milvus-proxy-d9f98579c-tpctt                   1/1     Running       1 (22m ago)      27m     10.104.17.228   4am-node23   <none>           <none>

[2023-09-22T05:31:06.779Z] etcd-pod-kill-7627-milvus-querycoord-748c7b76c8-99xzs             1/1     Running       2 (9m43s ago)    27m     10.104.18.215   4am-node25   <none>           <none>

[2023-09-22T05:31:06.779Z] etcd-pod-kill-7627-milvus-querynode-7c4dddd46d-5bm7p              1/1     Running       0                27m     10.104.18.217   4am-node25   <none>           <none>

[2023-09-22T05:31:06.779Z] etcd-pod-kill-7627-milvus-querynode-7c4dddd46d-gd6z5              1/1     Running       0                27m     10.104.19.126   4am-node28   <none>           <none>

[2023-09-22T05:31:06.779Z] etcd-pod-kill-7627-milvus-querynode-7c4dddd46d-qvwqw              1/1     Running       0                27m     10.104.17.230   4am-node23   <none>           <none>

[2023-09-22T05:31:06.779Z] etcd-pod-kill-7627-milvus-rootcoord-57d99df986-6xvqt              1/1     Running       0                27m     10.104.13.48    4am-node16   <none>           <none>

[2023-09-22T05:31:06.779Z] etcd-pod-kill-7627-minio-0                                        1/1     Running       0                27m     10.104.19.139   4am-node28   <none>           <none>

[2023-09-22T05:31:06.779Z] etcd-pod-kill-7627-minio-1                                        1/1     Running       0                27m     10.104.18.244   4am-node25   <none>           <none>

[2023-09-22T05:31:06.779Z] etcd-pod-kill-7627-minio-2                                        1/1     Running       0                27m     10.104.4.89     4am-node11   <none>           <none>

[2023-09-22T05:31:06.779Z] etcd-pod-kill-7627-minio-3                                        1/1     Running       0                27m     10.104.13.61    4am-node16   <none>           <none>

[2023-09-22T05:31:06.779Z] etcd-pod-kill-7627-zookeeper-0                                    1/1     Running       0                27m     10.104.19.137   4am-node28   <none>           <none>

[2023-09-22T05:31:06.779Z] etcd-pod-kill-7627-zookeeper-1                                    1/1     Running       0                27m     10.104.4.79     4am-node11   <none>           <none>

[2023-09-22T05:31:06.779Z] etcd-pod-kill-7627-zookeeper-2                                    1/1     Running       0                27m     10.104.13.59    4am-node16   <none>           <none>
```

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-for-release-cron/detail/chaos-test-kafka-for-release-cron/7627/pipeline
log:
[artifacts-etcd-pod-kill-7627-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/12697782/artifacts-etcd-pod-kill-7627-server-logs.tar.gz)
[artifacts-etcd-pod-kill-7627-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/12697784/artifacts-etcd-pod-kill-7627-pytest-logs.tar.gz)

### Anything else?

All pods are running before test and after test

**Comment by weiliu1031** [comment]
querycoord stop progress stucked at close etcd client
