### ISSUE TITLE
<MonkeyTest>grpc handler error raised caused by search result format failed

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#2738]
**Describe the bug**
```
09:28:51  2020-07-04:01:28:51,428 INFO     [k8s_runner.py:787] query_rand
09:28:58  2020-07-04:01:28:57,806 INFO     [client.py:244] collection_bvtmuw7e, Search nq: 93, top_k: 95, nprobe: 37
09:28:58  
09:28:58  Addr [milvus-benchmark-test-vk2cq0w2.milvus.svc.cluster.local:19530] search
09:28:58  Excepted error: list index out of range
09:28:58  	{'API start': '2020-07-04 01:28:57.807377', 'RPC start': '2020-07-04 01:28:57.807403', 'Exception': '2020-07-04 01:28:57.943570'}
09:28:58  2020-07-04:01:28:57,943 ERROR    [grpc_handler.py:55] 
09:28:58  Addr [milvus-benchmark-test-vk2cq0w2.milvus.svc.cluster.local:19530] search
09:28:58  Excepted error: list index out of range
09:28:58  	{'API start': '2020-07-04 01:28:57.807377', 'RPC start': '2020-07-04 01:28:57.807403', 'Exception': '2020-07-04 01:28:57.943570'}
09:28:58  2020-07-04:01:28:57,944 ERROR    [main.py:70] list index out of range
09:28:58  2020-07-04:01:28:57,948 ERROR    [main.py:71] Traceback (most recent call last):
09:28:58    File "main.py", line 68, in queue_worker
09:28:58      runner.run(run_type, collection)
09:28:58    File "/home/jenkins/agent/workspace/milvus-benchmark-0.10.1/milvus_benchmark/k8s_runner.py", line 790, in run
09:28:58      task_run()
09:28:58    File "/home/jenkins/agent/workspace/milvus-benchmark-0.10.1/milvus_benchmark/client.py", line 245, in query_rand
09:28:58      status, search_res = self._milvus.search(self._collection_name, top_k, query_records=X, params=search_param)
09:28:58    File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 37, in inner
09:28:58      return func(self, *args, **kwargs)
09:28:58    File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 666, in search
09:28:58      return handler.search(collection_name, top_k, query_records, partition_tags, params, timeout, **kwargs)
09:28:58    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 56, in handler
09:28:58      raise e
09:28:58    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 41, in handler
09:28:58      return func(self, *args, **kwargs)
09:28:58    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 763, in search
09:28:58      resutls = self._search_hook.handle_response(response)
09:28:58    File "/usr/local/lib/python3.6/site-packages/milvus/client/client_hooks.py", line 11, in handle_response
09:28:58      return TopKQueryResult(_response)
09:28:58    File "/usr/local/lib/python3.6/site-packages/milvus/client/abstract.py", line 126, in __init__
09:28:58      self._unpack(self._raw)
09:28:58    File "/usr/local/lib/python3.6/site-packages/milvus/client/abstract.py", line 158, in _unpack
09:28:58      if id_list[j] == -1:
09:28:58  IndexError: list index out of range
09:28:58  
09:29:45  Error: timed out waiting for the condition
```
**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment details**
pymilvus-test

**Screenshots**

**Additional context**

**Comment by BossZou** [comment]
I doubt that server return invalid search result, result in client raise exception when handling result. In client point, only when result length (length of ids in TopKQueryResult defined in proto) not equal to  multiply 'nq' by 'topk'. The 'nq' is equal to row_num in TopKQueryResult, and the 'topk' is equal to 'len(ids) // row_num'. So I guess search results of each query vectors is not aligned.

**Comment by BossZou** [comment]
We have add detail log to check search result structure, and need to reproduce this issue and obtain more detail server log on monkey test.

**Comment by BossZou** [comment]
@del-zhenwu , This issue may be fixed. need to regression.
