### ISSUE TITLE
[Bug]: Load the data into memory Hang and Couldn't create index successfully

### ISSUE THREAD

**Issue by Philipzhong1980** [milvus-io/milvus#27420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.10
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.2.9
- OS(Ubuntu or CentOS): Ubuntu 20.04.3 LTS
- CPU/Memory: 4 VCPU, 16G Memory, 160G SSD
- GPU: No
- Others:
```

### Current Behavior

when running "hello_miluvs.py" to create/insert/create an index etc., it can create collection/insert the data successfully, but hang for load the data into memory. below are the Client and DB errors.
**Client error**:
=== Start Creating index IVF_FLAT  ===
alloc_timestamp unimplemented, ignore it
=== Start loading                  ===
RPC error: [get_loading_progress], <MilvusException: (code=1, message=TaskStale)>, <Time:{'RPC start': '2023-09-27 17:33:55.586215', 'RPC error': '2023-09-27 19:06:11.200304'}>
RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=TaskStale)>, <Time:{'RPC start': '2023-09-27 17:16:21.028050', 'RPC error': '2023-09-27 19:06:11.200583'}>
RPC error: [load_collection], <MilvusException: (code=1, message=TaskStale)>, <Time:{'RPC start': '2023-09-27 17:16:20.991268', 'RPC error': '2023-09-27 19:06:11.200728'}>
Traceback (most recent call last):
  File "hello_milvus.py", line 107, in <module>
    hello_milvus.load()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 419, in load
    conn.load_collection(
.....
**Milvus DB brief error:**
[2023/09/27 09:17:39.648 +00:00] [INFO] [observers/collection_observer.go:204] ["collection load progress"] [collectionID=444545379435545196] [subChannelCount=1] [loadSegmentCount=0]
[2023/09/27 09:17:39.648 +00:00] [INFO] [balance/utils.go:55] ["Create Segment task"] [collection=444545379435545196] [replica=444545386577657857] [segmentID=444545379435745205] [channel=by-dev-rootcoord-dml_0_444545379435545196v0] [From=-1] [To=1]

[2023/09/27 09:22:30.134 +00:00] [WARN] [querycoordv2/services.go:854] ["failed to get replica info"] [msgID=0] [collectionID=444545379435545196] [replica=444545386577657857] [error="failed to get channels, collection not loaded[CollectionNotFound]"]
[2023/09/27 09:22:30.135 +00:00] [WARN] [retry/retry.go:44] ["retry func failed"] ["retry time"=0] [error="failed to get replica info, err=failed to get channels, collection not loaded[CollectionNotFound]"]
[2023/09/27 09:22:30.135 +00:00] [DEBUG] [proxy/impl.go:4314] ["received get replicas response"] [resp="status:<error_code:MetaFailed reason:\"failed to get replica info, err=failed to get channels, collection not loaded[CollectionNotFound]\" > "]

[2023/09/27 09:25:48.970 +00:00] [INFO] [proxy/impl.go:2016] ["GetLoadingProgress done"] [traceID=5f8097bff352374e] [request="base:<msg_type:ShowCollections sourceID:8 > collection_name:\"hello_milvus\" db_name:\"default\" "]
[2023/09/27 09:25:49.135 +00:00] [INFO] [task/scheduler.go:527] ["process tasks related to node"] [nodeID=1] [processingTaskNum=1] [waitingTaskNum=0] [segmentTaskNum=1] [channelTaskNum=0]
[2023/09/27 09:25:49.135 +00:00] [DEBUG] [funcutil/parallel.go:51] [process] [total=1] ["time cost"=23.705µs]
[2023/09/27 09:25:49.135 +00:00] [INFO] [task/scheduler.go:562] ["processed tasks"] [nodeID=1] [toProcessNum=1] [failCount=1] [toRemoveNum=0]
[2023/09/27 09:25:49.135 +00:00] [INFO] [task/scheduler.go:568] ["process tasks related to node done"] [nodeID=1] [processingTaskNum=1] [waitingTaskNum=0] [segmentTaskNum=1] [channelTaskNum=0]
[2023/09/27 09:25:49.233 +00:00] [WARN] [querynode/cgo_helper.go:56] ["LoadFieldData failed, C Runtime Exception: [UnexpectedError] Error:GetObjectSize:  curlCode: 28, Timeout was reached\n"]
[2023/09/27 09:25:49.233 +00:00] [WARN] [querynode/cgo_helper.go:56] ["LoadFieldData failed, C Runtime Exception: [UnexpectedError] Error:GetObjectSize:  curlCode: 28, Timeout was reached\n"]
[2023/09/27 09:25:49.234 +00:00] [WARN] [querynode/cgo_helper.go:56] ["LoadFieldData failed, C Runtime Exception: [UnexpectedError] Error:GetObjectSize:  curlCode: 28, Timeout was reached\n"]
[2023/09/27 09:25:49.237 +00:00] [WARN] [querynode/cgo_helper.go:56] ["LoadFieldData failed, C Runtime Exception: [UnexpectedError] Error:GetObjectSize:  curlCode: 28, Timeout was reached\n"]
[2023/09/27 09:25:49.251 +00:00] [WARN] [querynode/cgo_helper.go:56] ["LoadFieldData failed, C Runtime Exception: [UnexpectedError] Error:GetObjectSize:  curlCode: 28, Timeout was reached\n"]
[2023/09/27 09:25:49.261 +00:00] [INFO] [gc/gc_tuner.go:84] ["GC Tune done"] ["previous GOGC"=200] ["heapuse "=110] ["total memory"=133] ["next GC"=139] ["new GOGC"=200] [gc-pause=81.474µs] [gc-pause-end=1695806749260299555]
[2023/09/27 09:25:49.281 +00:00] [ERROR] [querynode/segment_loader.go:205] ["load segment failed when load data into memory"] [collectionID=444545379435545196] [segmentType=Sealed] [partitionID=444545379435545197] [segmentID=444545379435745205] [error="[UnexpectedError] Error:GetObjectSize:  curlCode: 28, Timeout was reached"] [stack="github.com/milvus-io/milvus/internal/querynode.(*segmentLoader).LoadSegment.func3\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/segment_loader.go:205\ngithub.com/milvus-io/milvus/internal/util/funcutil.ProcessFuncParallel.func3\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/parallel.go:83"]
[2023/09/27 09:25:49.281 +00:00] [ERROR] [funcutil/parallel.go:85] [loadSegmentFunc] [error="[UnexpectedError] Error:GetObjectSize:  curlCode: 28, Timeout was reached"] [idx=0] [stack="github.com/milvus-io/milvus/internal/util/funcutil.ProcessFuncParallel.func3\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/parallel.go:85"]
[2023/09/27 09:25:49.281 +00:00] [DEBUG] [funcutil/parallel.go:51] [loadSegmentFunc] [total=1] ["time cost"=1m9.64312045s]
[2023/09/27 09:25:49.281 +00:00] [INFO] [querynode/segment.go:289] ["delete segment from memory"] [collectionID=444545379435545196] [partitionID=444545379435545197] [segmentID=444545379435745205] [segmentType=Sealed]
[2023/09/27 09:25:49.290 +00:00] [INFO] [gc/gc_tuner.go:84] ["GC Tune done"] ["previous GOGC"=200] ["heapuse "=65] ["total memory"=86] ["next GC"=135] ["new GOGC"=200] [gc-pause=159.472µs] [gc-pause-end=1695806749288838143]
[2023/09/27 09:25:49.295 +00:00] [WARN] [querynode/load_segment_task.go:125] ["failed to load segment"] [collectionID=444545379435545196] [replicaID=444545386577657857] [error="[UnexpectedError] Error:GetObjectSize:  curlCode: 28, Timeout was reached"]
[2023/09/27 09:25:49.295 +00:00] [WARN] [querynode/task_scheduler.go:110] ["[UnexpectedError] Error:GetObjectSize:  curlCode: 28, Timeout was reached"]
[2023/09/27 09:25:49.295 +00:00] [WARN] [querynode/impl.go:522] ["[UnexpectedError] Error:GetObjectSize:  curlCode: 28, Timeout was reached"]
[2023/09/27 09:25:49.295 +00:00] [WARN] [querynode/shard_cluster.go:532] ["follower load segment failed"] [collectionID=444545379435545196] [channel=by-dev-rootcoord-dml_0_444545379435545196v0] [replicaID=444545386577657857] [dstNodeID=1] [segmentIDs="[444545379435745205]"] [reason="[UnexpectedError] Error:GetObjectSize:  curlCode: 28, Timeout was reached"]
[2023/09/27 09:25:49.295 +00:00] [WARN] [querynode/impl_utils.go:61] ["shard cluster failed to load segments"] [traceID=53367e735f7f4d6e] [shard=by-dev-rootcoord-dml_0_444545379435545196v0] [segmentIDs="[444545379435745205]"] [error="follower 1 failed to load segment, reason [UnexpectedError] Error:GetObjectSize:  curlCode: 28, Timeout was reached"]
[2023/09/27 09:25:49.295 +00:00] [WARN] [retry/retry.go:44] ["retry func failed"] ["retry time"=0] [error="follower 1 failed to load segment, reason [UnexpectedError] Error:GetObjectSize:  curlCode: 28, Timeout was reached"]
[2023/09/27 09:25:49.295 +00:00] [WARN] [task/executor.go:198] ["failed to load segment"] [taskIDs="[9]"] [collectionID=444545379435545196] [shard=by-dev-rootcoord-dml_0_444545379435545196v0] [segmentIDs="[444545379435745205]"] [nodeID=1] [source=2] [reason="follower 1 failed to load segment, reason [UnexpectedError] Error:GetObjectSize:  curlCode: 28, Timeout was reached"]
[2023/09/27 09:25:49.295 +00:00] [INFO] [task/executor.go:209] ["execute action done, remove it"] [taskID=9] [step=0] [error="failed to load segment: follower 1 failed to load segment, reason [UnexpectedError] Error:GetObjectSize:  curlCode: 28, Timeout was reached"]

### Expected Behavior

should create the index and load the data successfully, but it always hang.

### Steps To Reproduce

```markdown
1. create Milvus DB.
wget https://github.com/milvus-io/milvus/releases/download/v2.2.10/milvus-standalone-docker-compose.yml -O docker-compose.yml

sudo docker-compose up -d

2. Build the attu in milvus DB server.
docker run -p 8000:3000 -e MILVUS_URL=10.224.122.15:19530  zilliz/attu:v2.2.8
3. Build hello_milvus client with pymilvus 2.2.9
 https://milvus.io/docs/v2.2.x/install-pymilvus.md
4. Run hello_milvus.py 
  wget https://raw.githubusercontent.com/milvus-io/pymilvus/master/examples/hello_milvus.py
```

### Milvus Log

[milvus2.2.log.zip](https://github.com/milvus-io/milvus/files/12744587/milvus2.2.log.zip)

### Anything else?

**1. this is docker-compose.yml**
version: '3.5'
services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.2.10
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"

networks:
  default:
    name: milvus
**2. this is etcd endpoint status**
docker exec milvus-etcd etcdctl --write-out=table --endpoints=127.0.0.1:2379 endpoint status
+----------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
|    ENDPOINT    |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+----------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
| 127.0.0.1:2379 | 8e9e05c52164694d |   3.5.5 |  262 kB |      true |      false |         2 |      20846 |              20846 |        |
+----------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+

**Comment by xiaofan-luan** [comment]
@Philipzhong1980 
seems that load failed because of  object storage failed
"GetObjectSize: curlCode: 28, Timeout was reached"

**Comment by Philipzhong1980** [comment]
@xiaofan-luan Thanks and how to fix this problem?

**Comment by xiaofan-luan** [comment]
you can check with minio client and see if minio is working?

**Comment by Philipzhong1980** [comment]
this minio file when I do hello_milvus.py.
root@node1:/var/milvus/volumes/minio/a-bucket/files# ls -ltr
drwxr-xr-x 3 root root 4096 Sep 28 06:22 insert_log
drwxr-xr-x 3 root root 4096 Sep 28 06:22 stats_log
root@node1:/var/milvus/volumes/minio/a-bucket/files# date 
Thu 28 Sep 2023 06:24:21 AM GMT

**Comment by Philipzhong1980** [comment]
this is health check result.
root@node1:/var/milvus# docker exec milvus-minio curl -f http://localhost:9000/minio/health/live
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

**Comment by Philipzhong1980** [comment]
any finding on this?

**Comment by Philipzhong1980** [comment]
Give some background on this.
I built the Linux server with Kubernetes and then installed Milvus with docker, but I couldn't load the data into memory.
meanwhile, I created the Linux server with OpenStack, then installed docker and Milvus, and I got it successfully.
so would u like to find the real root cause of this?

**Comment by Philipzhong1980** [comment]
I got the root cause because we couldn't install Milvus on Kubernetes cluster with Docker, we must install it by helm.

**Comment by yanliang567** [comment]
so does it work to you now when installing milvus by helm?

**Comment by zhagnlu** [comment]
I using "Steps To Reproduce" to try to generate this error, but it always success.  So what's difference about your operations and this reproduce

**Comment by Philipzhong1980** [comment]
I think you can create a Kubernetes cluster and log in to the master server to install Milvus by docker comose.

**Comment by Philipzhong1980** [comment]
> so does it work to you now when installing milvus by helm?

not try the helm yet and now install Milvus standalone by docker-compose on OCP host
