### ISSUE TITLE
[Bug]:  Grpc error while loading collections on a base ubi9 image 

### ISSUE THREAD

**Issue by jobbine-joseph** [milvus-io/milvus#27472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3
- Deployment mode: standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): compiled in ubuntu and copied to ubi9
- CPU/Memory: 
- GPU: NA
- Others:
```

### Current Behavior

I compiled milvus in ubuntu 20.04 and copied the binaries to ubi9 base container and tried to configured amazon s3 bucket and getting following error while loading collections

`error_code: UnexpectedError
reason: "collection 444542118985728226 has not been loaded to memory or load failed"
code: 65535

RPC error: [get_loading_progress], <MilvusException: (code=1, message=collection 444542118985728226 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2023-09-27 01:14:17.082600', 'RPC error': '2023-09-27 01:14:17.089606'}>
RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=collection 444542118985728226 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2023-09-27 01:04:14.068299', 'RPC error': '2023-09-27 01:14:17.091981'}>
RPC error: [load_collection], <MilvusException: (code=1, message=collection 444542118985728226 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2023-09-27 01:04:14.035243', 'RPC error': '2023-09-27 01:14:17.092573'}>
Traceback (most recent call last):
  File "/root/view_collection.py", line 70, in <module>
    Collection.load(book)
  File "/usr/local/lib/python3.11/site-packages/pymilvus/orm/collection.py", line 419, in load
    conn.load_collection(
  File "/usr/local/lib/python3.11/site-packages/pymilvus/decorators.py", line 127, in handler
    raise e from e
  File "/usr/local/lib/python3.11/site-packages/pymilvus/decorators.py", line 123, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymilvus/decorators.py", line 162, in handler
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymilvus/decorators.py", line 102, in handler
    raise e from e
  File "/usr/local/lib/python3.11/site-packages/pymilvus/decorators.py", line 68, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 1023, in load_collection
    self.wait_for_loading_collection(collection_name, timeout, is_refresh=_refresh)
  File "/usr/local/lib/python3.11/site-packages/pymilvus/decorators.py", line 127, in handler
    raise e from e
  File "/usr/local/lib/python3.11/site-packages/pymilvus/decorators.py", line 123, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymilvus/decorators.py", line 162, in handler
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymilvus/decorators.py", line 102, in handler
    raise e from e
  File "/usr/local/lib/python3.11/site-packages/pymilvus/decorators.py", line 68, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 1043, in wait_for_loading_collection
    progress = self.get_loading_progress(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymilvus/decorators.py", line 127, in handler
    raise e from e
  File "/usr/local/lib/python3.11/site-packages/pymilvus/decorators.py", line 123, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymilvus/decorators.py", line 162, in handler
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymilvus/decorators.py", line 102, in handler
    raise e from e
  File "/usr/local/lib/python3.11/site-packages/pymilvus/decorators.py", line 68, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 1146, in get_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection 444542118985728226 has not been loaded to memory or load failed)>`

i was trying with a simple python code which was working with Milvus binaries and compiled ubuntu binaries.

### Steps To Reproduce

```markdown
1 in a dockerfile pull code compie in ubuntu base image, copy to ubi9 base image and try using simple python code , will hit collection load error.
```

### Milvus Log

`[2023/09/27 11:55:02.133 +00:00] [ERROR] [retry/retry.go:42] ["retry func failed"] ["retry time"=0] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [stack="github.com/milvus-io/milvus/pkg/util/retry.Do\n\t/milvus/pkg/util/retry/retry.go:42\ngithub.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).call\n\t/milvus/internal/util/grpcclient/client.go:405\ngithub.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call\n\t/milvus/internal/util/grpcclient/client.go:483\ngithub.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n\t/milvus/internal/util/grpcclient/client.go:499\ngithub.com/milvus-io/milvus/internal/distributed/querynode/client.wrapGrpcCall[...]\n\t/milvus/internal/distributed/querynode/client/client.go:90\ngithub.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).GetDataDistribution\n\t/milvus/internal/distributed/querynode/client/client.go:281\ngithub.com/milvus-io/milvus/internal/querycoordv2/session.(*QueryCluster).GetDataDistribution.func1\n\t/milvus/internal/querycoordv2/session/cluster.go:215\ngithub.com/milvus-io/milvus/internal/querycoordv2/session.(*QueryCluster).send\n\t/milvus/internal/querycoordv2/session/cluster.go:278\ngithub.com/milvus-io/milvus/internal/querycoordv2/session.(*QueryCluster).GetDataDistribution\n\t/milvus/internal/querycoordv2/session/cluster.go:210\ngithub.com/milvus-io/milvus/internal/querycoordv2/dist.(*distHandler).getDistribution\n\t/milvus/internal/querycoordv2/dist/dist_handler.go:230\ngithub.com/milvus-io/milvus/internal/querycoordv2/dist.(*distHandler).start\n\t/milvus/internal/querycoordv2/dist/dist_handler.go:75"]`

### Anything else?

na

**Comment by xiaofan-luan** [comment]
@jobbine-joseph 
could you offer full log using export log script so we can we can invesitigate on it.

So far the only thing we can see is GetDataDistribution timeout due to some reason.
