### ISSUE TITLE
[Bug]: Search failed with error `node=23: node offline: channel=by-dev-rootcoord-dml_14_xxxv1: channel not available` after querynode pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#27496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20231004-6d4492d2-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2023-10-06T22:24:56.242Z] [2023-10-06 22:19:23 - INFO - ci_test]: assert insert: 3.8945224285125732 (test_all_collections_after_chaos.py:61)

[2023-10-06T22:24:56.242Z] [2023-10-06 22:19:23 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2023-10-06T22:24:56.242Z] [2023-10-06 22:19:29 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-10-06T22:24:56.242Z] [2023-10-06 22:19:29 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2023-10-06T22:24:56.242Z] [2023-10-06 22:19:29 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-10-06T22:24:56.242Z] [2023-10-06 22:19:30 - INFO - ci_test]: assert flush: 5.452794075012207, entities: 265485 (test_all_collections_after_chaos.py:71)

[2023-10-06T22:24:56.242Z] [2023-10-06 22:19:30 - INFO - ci_test]: index info: [{'collection': 'Checker__uy2b039v', 'field': 'float_vector', 'index_name': 'index__LtM7r8kT', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}] (test_all_collections_after_chaos.py:87)

[2023-10-06T22:24:56.242Z] [2023-10-06 22:19:30 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 180], kwargs: {} (api_request.py:62)

[2023-10-06T22:24:56.242Z] [2023-10-06 22:19:30 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-10-06T22:24:56.242Z] [2023-10-06 22:19:30 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.10990852671321616, 0.004310694218554666, 0.04059790301692634, 0.11071745660356859, 0.15223103090783732, 0.15587791323751773, 0.01310123385276619, 0.11822009307889293, 0.07366023247133967, 0.09451222302969019, 0.046281264863547805, 0.13960773945370394, 0.13899543925992833, 0.10013205091491084, 0......, kwargs: {} (api_request.py:62)

[2023-10-06T22:24:56.242Z] [2023-10-06 22:19:40 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=failed to search: attempt #0: fail to get shard leaders from QueryCoord: node=23: node offline: channel=by-dev-rootcoord-dml_14_444761123966234186v1: channel not available: attempt #1: fail to get shard leaders from QueryCoord: node=23: node offline: channel=by-dev-rootcoord-dml_13_444761123966234186v0: channel not available: attempt #2: fail to get shard leaders from QueryCoord: node=23: node offline: channel=by-dev-rootcoord-dml_13_444761123966234186v0: channel not available: attempt #3: fail to get shard leaders from QueryCoord: node=23: node offline: channel=by-dev-rootcoord-dml_13_444761123966234186v0: channel not available: attempt #4: fail to get shard leaders from QueryCoord: node=23: node offline: channel=by-dev-rootcoord-dml_13_444761123966234186v0: channel not available: attempt #5: fail to get shard leaders from QueryCoord: node=23: node offline: channel=by-dev-rootcoord-dml_13_444761123966234186v0: channel not available: attempt #6: fail to get shard leaders from QueryCoord: node=23: node offline: channel=by-dev-rootcoord-dml_13_444761123966234186v0: channel not available: context deadline exceeded)>, <Time:{'RPC start': '2023-10-06 22:19:30.027095', 'RPC error': '2023-10-06 22:19:40.032151'}> (decorators.py:126)

[2023-10-06T22:24:56.242Z] [2023-10-06 22:19:40 - ERROR - ci_test]: Traceback (most recent call last):

[2023-10-06T22:24:56.242Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2023-10-06T22:24:56.242Z]     res = func(*args, **_kwargs)

[2023-10-06T22:24:56.242Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2023-10-06T22:24:56.242Z]     return func(*arg, **kwargs)

[2023-10-06T22:24:56.242Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 778, in search

[2023-10-06T22:24:56.242Z]     res = conn.search(

[2023-10-06T22:24:56.242Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 127, in handler

[2023-10-06T22:24:56.242Z]     raise e from e

[2023-10-06T22:24:56.242Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 123, in handler

[2023-10-06T22:24:56.242Z]     return func(*args, **kwargs)

[2023-10-06T22:24:56.242Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 162, in handler

[2023-10-06T22:24:56.242Z]     return func(self, *args, **kwargs)

[2023-10-06T22:24:56.242Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 102, in handler

[2023-10-06T22:24:56.242Z]     raise e from e

[2023-10-06T22:24:56.242Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 68, in handler

[2023-10-06T22:24:56.242Z]     return func(*args, **kwargs)

[2023-10-06T22:24:56.242Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 774, in search

[2023-10-06T22:24:56.242Z]     return self._execute_search_requests(

[2023-10-06T22:24:56.242Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 735, in _execute_search_requests

[2023-10-06T22:24:56.242Z]     raise pre_err from pre_err

[2023-10-06T22:24:56.242Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 726, in _execute_search_requests

[2023-10-06T22:24:56.242Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2023-10-06T22:24:56.242Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=failed to search: attempt #0: fail to get shard leaders from QueryCoord: node=23: node offline: channel=by-dev-rootcoord-dml_14_444761123966234186v1: channel not available: attempt #1: fail to get shard leaders from QueryCoord: node=23: node offline: channel=by-dev-rootcoord-dml_13_444761123966234186v0: channel not available: attempt #2: fail to get shard leaders from QueryCoord: node=23: node offline: channel=by-dev-rootcoord-dml_13_444761123966234186v0: channel not available: attempt #3: fail to get shard leaders from QueryCoord: node=23: node offline: channel=by-dev-rootcoord-dml_13_444761123966234186v0: channel not available: attempt #4: fail to get shard leaders from QueryCoord: node=23: node offline: channel=by-dev-rootcoord-dml_13_444761123966234186v0: channel not available: attempt #5: fail to get shard leaders from QueryCoord: node=23: node offline: channel=by-dev-rootcoord-dml_13_444761123966234186v0: channel not available: attempt #6: fail to get shard leaders from QueryCoord: node=23: node offline: channel=by-dev-rootcoord-dml_13_444761123966234186v0: channel not available: context deadline exceeded)>
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/8070/pipeline
log:
[artifacts-querynode-pod-kill-8070-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/12836704/artifacts-querynode-pod-kill-8070-pytest-logs.tar.gz)
[artifacts-querynode-pod-kill-8070-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/12836705/artifacts-querynode-pod-kill-8070-server-logs.tar.gz)

### Anything else?

collection name: Checker__uy2b039v'
cluster: 4am
namespace: chaos-testing
release name: querynode-pod-kill-8070

**Comment by zhuwenxing** [comment]
Not reproduced recently, remove the critical label.
