### ISSUE TITLE
[Bug]: [CI] Load collection occasionally failed for timeout(180s)

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#27506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230930-7d0dd004-amd64
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Load collection occasionally failed for timeout(180s).
```
[2023-09-30T14:02:10.263Z] [2023-09-30 13:18:11 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 180], kwargs: {} (api_request.py:62)
[2023-09-30T14:02:10.263Z] [2023-09-30 13:21:11 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=wait for loading collection timeout, collection: query_uphRd6fy)>, <Time:{'RPC start': '2023-09-30 13:18:11.523314', 'RPC error': '2023-09-30 13:21:11.996674'}> (decorators.py:126)
[2023-09-30T14:02:10.263Z] [2023-09-30 13:21:11 - WARNING - pymilvus.decorators]: [93mRetry timeout: 180s[0m (decorators.py:94)
[2023-09-30T14:02:10.263Z] [2023-09-30 13:21:11 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for loading collection timeout, collection: query_uphRd6fy)>, <Time:{'RPC start': '2023-09-30 13:18:11.509913', 'RPC error': '2023-09-30 13:21:11.996986'}> (decorators.py:126)
[2023-09-30T14:02:10.263Z] [2023-09-30 13:21:11 - ERROR - ci_test]: Traceback (most recent call last):
[2023-09-30T14:02:10.263Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper
[2023-09-30T14:02:10.263Z]     res = func(*args, **_kwargs)
[2023-09-30T14:02:10.263Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request
[2023-09-30T14:02:10.263Z]     return func(*arg, **kwargs)
[2023-09-30T14:02:10.263Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 419, in load
[2023-09-30T14:02:10.263Z]     conn.load_collection(
[2023-09-30T14:02:10.263Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 127, in handler
[2023-09-30T14:02:10.263Z]     raise e from e
[2023-09-30T14:02:10.263Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 123, in handler
[2023-09-30T14:02:10.263Z]     return func(*args, **kwargs)
[2023-09-30T14:02:10.263Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 162, in handler
[2023-09-30T14:02:10.263Z]     return func(self, *args, **kwargs)
[2023-09-30T14:02:10.263Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 95, in handler
[2023-09-30T14:02:10.263Z]     raise MilvusException(
[2023-09-30T14:02:10.263Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for loading collection timeout, collection: query_uphRd6fy)>
[2023-09-30T14:02:10.263Z]  (api_request.py:45)
[2023-09-30T14:02:10.263Z] [2023-09-30 13:21:11 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for loading collection timeout, collection: query_uphRd6fy)> (api_request.py:46)
```

### Expected Behavior

load successfully

### Milvus Log

1. link: https://qa-jenkins.milvus.io/blue/organizations/jenkins/E2E%20Test/detail/E2E%20Test/159/pipeline/
2. log: [artifacts-e2e-test-159-server-logs.tar.gz](https://qa-jenkins.milvus.io/job/E2E%20Test/159/artifact/artifacts-e2e-test-159-server-logs.tar.gz)
3. failed time: [2023-09-30T13:21:14.543Z] [gw0] [ 29%] FAILED test_query.py::TestQueryParams::test_query_expr_empty_without_limit

**Comment by yanliang567** [comment]
not reproduce now
