### ISSUE TITLE
[Bug]: Insert int8 array failed reporting type not match: expected: ARRAY, got FLOAT_VECTOR

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#27559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20231007-80eb5434
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.1.post1.dev5
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Insert int8 array failed reporting type not match: expected: ARRAY, got FLOAT_VECTOR.
```
>>> collection.insert(data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/orm/collection.py", line 495, in insert
    check_insert_schema(self._schema, data)
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/orm/schema.py", line 416, in check_insert_schema
    check_infer_fields_valid(infer_fields, tmp_fields, is_data_frame)
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/orm/schema.py", line 561, in check_infer_fields_valid
    raise DataNotMatchException(message=msg)
pymilvus.exceptions.DataNotMatchException: <DataNotMatchException: (code=1, message=The data type of field int8_array doesn't match, expected: ARRAY, got FLOAT_VECTOR)>
```

### Expected Behavior

insert successfully

### Steps To Reproduce

```markdown
from pymilvus import CollectionSchema, FieldSchema, Collection, connections, DataType, Partition, utility
import numpy as np
import random
connections.connect()


dim = 128
collection_name = "test_array"
arr_len = 100
nb = 200


if utility.has_collection(collection_name):
    utility.drop_collection(collection_name)

# create collection
pk_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True, description='pk')
vector_field = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)

int8_array = FieldSchema(name="int8_array", dtype=DataType.ARRAY, element_type=DataType.INT8, max_capacity=arr_len)
int16_array = FieldSchema(name="int16_array", dtype=DataType.ARRAY, element_type=DataType.INT16, max_capacity=arr_len)
int32_array = FieldSchema(name="int32_array", dtype=DataType.ARRAY, element_type=DataType.INT32, max_capacity=arr_len)
int64_array = FieldSchema(name="int64_array", dtype=DataType.ARRAY, element_type=DataType.INT64, max_capacity=arr_len)
bool_array = FieldSchema(name="bool_array", dtype=DataType.ARRAY, element_type=DataType.BOOL, max_capacity=arr_len)
float_array = FieldSchema(name="float_array", dtype=DataType.ARRAY, element_type=DataType.FLOAT, max_capacity=arr_len)
double_array = FieldSchema(name="double_array", dtype=DataType.ARRAY, element_type=DataType.DOUBLE, max_capacity=arr_len)
string_array = FieldSchema(name="string_array", dtype=DataType.ARRAY, element_type=DataType.VARCHAR, max_capacity=arr_len,
                           max_length=100)

# fields = [pk_field, vector_field, int8_array, int16_array, int32_array, int64_array,
#           bool_array, float_array, double_array, string_array]

fields = [pk_field, vector_field, int8_array]
schema = CollectionSchema(fields=fields)
collection = Collection(collection_name, schema=schema)


# insert data
pk_value = [i for i in range(nb)]
vector_value = [[random.random() for _ in range(dim)] for i in range(nb)]

int8_value = [[np.int8(j) for j in range(arr_len)] for i in range(nb)]
int16_value = [[np.int16(j) for j in range(arr_len)] for i in range(nb)]
int32_value = [[np.int32(j) for j in range(arr_len)] for i in range(nb)]
int64_value = [[np.int64(j) for j in range(arr_len)] for i in range(nb)]
bool_value = [[np.bool_(j) for j in range(arr_len)] for i in range(nb)]
float_value = [[np.float32(j) for j in range(arr_len)] for i in range(nb)]
double_value = [[np.double(j) for j in range(arr_len)] for i in range(nb)]
string_value = [[str(j) for j in range(arr_len)] for i in range(nb)]

data = [pk_value, vector_value, int8_value]
collection.insert(data)
```

**Comment by OverlordRon** [comment]
Can you please upload the line where you actually conduct the similarity search?  I have had a similar issue and you have to wrap your vector being searched inside an array.  I think what is going on is you have a vector and you are searching directly for that vector when you should wrap it in the search field like so : [vector]

**Comment by xiaofan-luan** [comment]
I thought this might be a pymilvus issue.
please assign to @czs007

**Comment by czs007** [comment]
yes. I am fixing this. @xiaofan-luan

**Comment by NicoYuan1986** [comment]
> Can you please upload the line where you actually conduct the similarity search? I have had a similar issue and you have to wrap your vector being searched inside an array. I think what is going on is you have a vector and you are searching directly for that vector when you should wrap it in the search field like so : [vector]

I have not started to search. It failed at insert. I think it has something to do with the form of insertion.
same data, insert by list-list will fail,
![image](https://github.com/milvus-io/milvus/assets/109071306/31a696fc-56c4-4b48-8ad1-809b8eca08bf)
insert by list-dict will succeed
![image](https://github.com/milvus-io/milvus/assets/109071306/1d27bb60-5673-4557-b36e-ea8e2335bb59)

int8_array is our new feature and still in investigating.

**Comment by NicoYuan1986** [comment]
Verify fixed. master-20231019-020ad9a6
