### ISSUE TITLE
[Bug]: Insert array field in the form of list will report a Field dtype error

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#27566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20231007-80eb5434
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.1.post1.dev5
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Insert array field in the form of list will report a Field dtype error.

my schema:
pk field, float vector, int32 array, float array, string array

insert data:
![image](https://github.com/milvus-io/milvus/assets/109071306/6e6a0002-82f5-440b-8cdd-9bd36cf17550)

error message:
```
[2023-10-09 17:26:39 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/zilliz/nico/milvus/tests/python_client/utils/api_request.py", line 32, in inner_wrapper
    res = func(*args, **_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/nico/milvus/tests/python_client/utils/api_request.py", line 63, in api_request
    return func(*arg, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/orm/collection.py", line 495, in insert
    check_insert_schema(self._schema, data)
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/orm/schema.py", line 415, in check_insert_schema
    infer_fields, tmp_fields, is_data_frame = parse_fields_from_data(schema, data)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/orm/schema.py", line 451, in parse_fields_from_data
    infer_fields.append(FieldSchema("", infer_dtype_bydata(elem)))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/orm/schema.py", line 255, in __init__
    raise DataTypeNotSupportException(message=ExceptionsMessage.FieldDtype)
pymilvus.exceptions.DataTypeNotSupportException: <DataTypeNotSupportException: (code=1, message=Field dtype must be of DataType)>
 (api_request.py:45)
[2023-10-09 17:26:39 - ERROR - ci_test]: (api_response) : <DataTypeNotSupportException: (code=1, message=Field dtype must be of DataType)> (api_request.py:46)

```

### Expected Behavior

insert successfully

**Comment by NicoYuan1986** [comment]
Verify fixed. master-20231019-020ad9a6
