### ISSUE TITLE
[Bug]: Error message is not clear enough when the length of array inserted > max capacity

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#27584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20231007-80eb5434
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.1.post1.dev5
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Error message is not clear enough when the length of array inserted > max capacity.

```python
    @pytest.mark.tags(CaseLabel.L2)
    def test_insert_array_length_invalid(self):
        """
        target: Insert actual array length > max_capacity
        method: Insert actual array length > max_capacity
        expected: raise error
        """
        schema = cf.gen_array_collection_schema()
        collection_w = self.init_collection_wrap(schema=schema)
        arr_len = ct.default_max_capacity + 1
        data = cf.get_row_data_by_schema(schema=schema)
        data[1][ct.default_float_array_field_name] = [np.float32(i) for i in range(arr_len)]
        err_msg = (f"the length (2000) of 1th array exceeds max capacity ({ct.default_max_capacity}): "
                   f"expected=valid length array, actual=array length exceeds max capacity: invalid parameter")
        collection_w.insert(data=data, check_task=CheckTasks.err_res,
                            check_items={ct.err_code: 1100, ct.err_msg: err_msg})
```

Here i insert 2000 entities. max_capacity=100
The second entity is:
```
pk: 1,
float_vector: [.., ...]
int32_array: [1, 2, 3, 4, ..., 101] (total 101)
...
```
So the error message should be `the length (101) of 1th array exceeds max capacity (100): ...`

But now it is `the length (2000) of 1th array exceeds max capacity (100): ...`
2000 is not array length, but num_entities.

### Expected Behavior

update the error message

**Comment by NicoYuan1986** [comment]
same error when searching:

1. array length = 100, max length = 100, search expression = 'array[101] > 0'
2. array length = 50, max length = 100, search expression = 'array[51] > 0'

error message:
```
[2023-10-10 15:37:28 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=65538, message=failed to search: attempt #0: failed to search/query delegator 3 for channel by-dev-rootcoord-dml_3_444818512781240107v0: fail to Search, QueryNode ID=3, reason=worker(3) query failed: UnknownError: Assert "index >= 0 && index < length_" at /go/src/github.com/milvus-io/milvus/internal/core/src/common/Array.h:454
 => index out of range, index=103, length=100: attempt #1: no available shard delegator found: service unavailable)>, <Time:{'RPC start': '2023-10-10 15:37:27.351611', 'RPC error': '2023-10-10 15:37:28.163081'}> (decorators.py:128)
[2023-10-10 15:37:28 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/zilliz/nico/milvus/tests/python_client/utils/api_request.py", line 32, in inner_wrapper
    res = func(*args, **_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/nico/milvus/tests/python_client/utils/api_request.py", line 63, in api_request
    return func(*arg, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/orm/collection.py", line 778, in search
    res = conn.search(
          ^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 129, in handler
    raise e from e
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 125, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 164, in handler
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 104, in handler
    raise e from e
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 68, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 788, in search
    return self._execute_search_requests(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 749, in _execute_search_requests
    raise pre_err from pre_err
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 740, in _execute_search_requests
    raise MilvusException(response.status.code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=65538, message=failed to search: attempt #0: failed to search/query delegator 3 for channel by-dev-rootcoord-dml_3_444818512781240107v0: fail to Search, QueryNode ID=3, reason=worker(3) query failed: UnknownError: Assert "index >= 0 && index < length_" at /go/src/github.com/milvus-io/milvus/internal/core/src/common/Array.h:454
 => index out of range, index=103, length=100: attempt #1: no available shard delegator found: service unavailable)>
 (api_request.py:45)
[2023-10-10 15:37:28 - ERROR - ci_test]: (api_response) : <MilvusException: (code=65538, message=failed to search: attempt #0: failed to search/query delegator 3 for channel by-dev-rootcoord-dml_3_444818512781240107v0: fail to Search, QueryNode ID=3, reason=worker(3) query failed: UnknownError: Assert "index >= 0 && index < length_" at /go/src/github.com/m...... (api_request.py:46)
```


It is not clear. need an improvement.

**Comment by xiaofan-luan** [comment]
good catch!
we need more reasonable error

**Comment by NicoYuan1986** [comment]
Verify fixed. master-20231019-020ad9a6
