### ISSUE TITLE
[Bug]: datanode and index period restart

### ISSUE THREAD

**Issue by gateray** [milvus-io/milvus#27610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.14
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2): go-sdk v
- OS(Ubuntu or CentOS): ubuntu
- CPU/Memory: 32 core 256G
- GPU: no
- Others: k8s version v1.22
```

### Current Behavior

datanode and index period restart, the container restart previous log is below:
* datanode:

**Comment by gateray** [comment]
datanode and index period restart, the container restart previous log is below:
* indexnode:
```
[2023/10/10 09:03:25.659 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=6e5cbbaa750f5696] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:25.666 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=7ee22ba2b575431b] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:25.672 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=48a72ef8af1754ef] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:25.679 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=25ad4a22f93b85a5] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:25.685 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=3cc264fbdd54d9ed] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:25.691 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=1641699c7c80983] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:25.698 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=3bd3880fa5baf0ad] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:25.705 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=d34572d228a3b2b] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:25.712 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=459cde564a5abc6] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:25.719 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=7c4b9918f6defa96] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:25.727 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=6ba696fe0771418a] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:25.735 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=3488350f32e461c5] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:25.742 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=e61a3bf40754cf5] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:25.750 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=7441c5bbef0aad67] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:25.758 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=140c79d9a5390c60] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:25.765 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=5ef41859b1aba39c] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:25.772 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=346f4307f272c948] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:25.778 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=3f67768a2fc906ac] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:25.788 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=8b13ec470123718] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:25.794 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=1caedc7d77780271] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:25.804 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=233c43fe2cf5c0d7] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:25.827 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=4a6ae334f91cd957] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:25.836 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=413cc3217ac32bc4] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:25.843 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=2837e6907c0ccad9] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:25.852 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=7198c0ce4892558f] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:25.858 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=186a3d792ad9e874] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:25.873 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=1d383a942efea2ae] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:25.882 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=4bbdcd7fc924f121] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:27.458 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=7c4af19f56b87652] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:28.457 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=4be72dcf37c6dbd6] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:29.456 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=2b7804ea9ec1c540] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:30.455 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=29e84f1dd31396de] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:31.455 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=3d32cad115c4f9ff] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:32.453 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=2868be331c63f47a] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:33.453 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=72c3b8296ca9660d] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:34.452 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=13a779352632b83d] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:35.451 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=3c68834842a47e93] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:36.404 +00:00] [INFO] [indexnode/task.go:317] ["index params are ready"] [buildID=444819655658556377] ["index params"="{\"dim\":\"768\",\"index_type\":\"IVF_PQ\",\"m\":\"32\",\"metric_type\":\"L2\",\"nbits\":\"8\",\"nlist\":\"1000\"}"]
2023-10-10 09:03:36,404 | INFO | default | [SEGCORE][InitSDKAPI][milvus] init aws with log level:error
[2023/10/10 09:03:36.436 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=12234249f33f2aa8] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:36.503 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=846942a230fa7e0] [Unissued=0] [Active=1] [Slot=0]
2023-10-10 09:03:37,405 | INFO | default | [SEGCORE][ProcessFormattedStatement][milvus] [AWS LOG] [ERROR] 2023-10-10 09:03:37.405 CurlHttpClient [140351467210496] Curl returned error code 28 - Timeout was reached

2023-10-10 09:03:37,406 | INFO | default | [SEGCORE][ProcessFormattedStatement][milvus] [AWS LOG] [ERROR] 2023-10-10 09:03:37.406 EC2MetadataClient [140351467210496] Http request to retrieve credentials failed

[2023/10/10 09:03:37.449 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=395c4e1b33db3e1] [Unissued=0] [Active=1] [Slot=0]
2023-10-10 09:03:38,406 | INFO | default | [SEGCORE][ProcessFormattedStatement][milvus] [AWS LOG] [ERROR] 2023-10-10 09:03:38.406 CurlHttpClient [140351467210496] Curl returned error code 28 - Timeout was reached

2023-10-10 09:03:38,406 | INFO | default | [SEGCORE][ProcessFormattedStatement][milvus] [AWS LOG] [ERROR] 2023-10-10 09:03:38.406 EC2MetadataClient [140351467210496] Http request to retrieve credentials failed

2023-10-10 09:03:38,406 | INFO | default | [SEGCORE][ProcessFormattedStatement][milvus] [AWS LOG] [ERROR] 2023-10-10 09:03:38.406 EC2MetadataClient [140351467210496] Can not retrieve resource from http://169.254.169.254/latest/meta-data/placement/availability-zone

2023-10-10 09:03:38,406 | INFO | default | [SEGCORE][N6milvus7storage17MinioChunkManagerE::MinioChunkManager][milvus] init MinioChunkManager with parameter[endpoint: 'ks3-cn-beijing-internal.ksyuncs.com:443', default_bucket_name:'document-ai-milvus', use_secure:'true']
2023-10-10 09:03:38,406 | WARNING | default | [KNOWHERE][GetGlobalThreadPool][milvus] Global ThreadPool has not been inialized yet, init it now with threads num: 32
Failed to set Thread scheduling: Operation not permitted
Failed to set Thread scheduling: Operation not permitted
Failed to set Thread scheduling: Operation not permitted
Failed to set Thread scheduling: Operation not permitted
Failed to set Thread scheduling: Operation not permitted
Failed to set Thread scheduling: Operation not permitted
Failed to set Thread scheduling: Operation not permitted
Failed to set Thread scheduling: Operation not permitted
Failed to set Thread scheduling: Operation not permitted
Failed to set Thread scheduling: Operation not permitted
Failed to set Thread scheduling: Operation not permitted
Failed to set Thread scheduling: Operation not permitted
Failed to set Thread scheduling: Operation not permitted
Failed to set Thread scheduling: Operation not permitted
Failed to set Thread scheduling: Operation not permitted
Failed to set Thread scheduling: Operation not permitted
Failed to set Thread scheduling: Operation not permitted
Failed to set Thread scheduling: Operation not permitted
Failed to set Thread scheduling: Operation not permitted
Failed to set Thread scheduling: Operation not permitted
Failed to set Thread scheduling: Operation not permitted
Failed to set Thread scheduling: Operation not permitted
Failed to set Thread scheduling: Operation not permitted
Failed to set Thread scheduling: Operation not permitted
Failed to set Thread scheduling: Operation not permitted
Failed to set Thread scheduling: Operation not permitted
Failed to set Thread scheduling: Operation not permitted
Failed to set Thread scheduling: Operation not permitted
Failed to set Thread scheduling: Operation not permitted
Failed to set Thread scheduling: Operation not permitted
Failed to set Thread scheduling: Operation not permitted
Failed to set Thread scheduling: Operation not permitted
2023-10-10 09:03:38,408 | INFO | default | [SEGCORE][N6milvus10ThreadPoolE::ThreadPool][milvus] Thread pool's worker num:80
[2023/10/10 09:03:38.449 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=56d37baf44f1b4e4] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:39.448 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=7079271272dc9d4c] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:40.447 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=6dd1d51eb6dc3939] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:41.447 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=77b72a9048810425] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:42.446 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=608acf17838c7620] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:43.445 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=7e6725c1e9d1f9cc] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:44.443 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=68de112c763cd3d7] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:45.443 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=befa13f39846581] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:46.442 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=e06d0d7adcc7179] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:47.441 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=2b098cf1bd0ce290] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:48.440 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=2d6168baf881191d] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:49.440 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=1962fb7119fb8e7] [Unissued=0] [Active=1] [Slot=0]
[2023/10/10 09:03:50.439 +00:00] [INFO] [indexnode/indexnode_service.go:209] ["Get Index Job Stats"] [traceID=3f9ff228c4039339] [Unissued=0] [Active=1] [Slot=0]
```

* datanode
```
pan1cuntimeindexrange
goroutine 30387 [running]:github.com/milvus-io/milvus/internal/datanode.(*priorityQueue).Swap(0x1000000033bc0?, 0x2?, 0x7ef17e0?).com/milvus-io/milvus/internal/datanode/buffer.go:234 +0xbcgo/src/github .0xco0ldff7e8], oxfffffffffffffffflcontainer/heap .Remove( 10x474b5e0usr/local/go/srcgo72+0x53github.com/milwustaBufferManager)deleteFromHeap(0xc0357c4000?，0xc005281d00?go/src/github/butfer.go:126 +0xacgithub.com/milvusltaBufferManager)Delete(0xc001596270，0xc005281d00?go /s rcgithubdatanode/buffer.go:154 +0x5fgithub.com/miLvusferManager).UpdateCompactedSegments(OxcO0596270)go/src/aithub-1o/milvus/internal /datanode/buffer.go:83 +0x55agithub .*deleteNode).0perate(oxcoof28b200，(0xc088aelea0，0xl，0x1})Com/m1LVuSlo/milwus internal/datanodecom/milvus-io/milvus/internal/datanode/flow graph delete node.go:94 +0x231go/src/aithubnternal/util/flowgraph.(*nodeCtx).work(oxc014dbaooo)1thub.com/mitwusvus-io/milvus/internal/util/flowgraph/node.go:127 +0x2acgo/src /github . ccreatedby github .com/milvusio/milvus/internal/util/flowgraph.(*nodeCtx)startgo/src/aithub ./flowaraph/node .ao:71 +0x79
```

**Comment by xiaofan-luan** [comment]
Failed to set Thread scheduling: Operation not permitted 

is this 2.2.14?
