### ISSUE TITLE
[Bug]: The error message is not clear enough when inserting rows

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#27628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20231007-80eb5434
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.1.post1.dev6
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Array insert failed when enable_dynamic_field = False.
```
>>> collection.insert(data)
RPC error: [insert_rows], <DataNotMatchException: (code=1, message=Attempt to insert an unexpected field to collection without enabling dynamic field)>, <Time:{'RPC start': '2023-10-11 11:12:20.341396', 'RPC error': '2023-10-11 11:12:20.341801'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/orm/collection.py", line 508, in insert
    res = conn.insert_rows(
          ^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 129, in handler
    raise e from e
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 125, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 164, in handler
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 104, in handler
    raise e from e
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 68, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 505, in insert_rows
    request = self._prepare_row_insert_request(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 486, in _prepare_row_insert_request
    return Prepare.row_insert_param(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/client/prepare.py", line 423, in row_insert_param
    return cls._parse_row_request(request, fields_info, enable_dynamic, entities)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/client/prepare.py", line 371, in _parse_row_request
    raise DataNotMatchException(message=ExceptionsMessage.InsertUnexpectedField)
pymilvus.exceptions.DataNotMatchException: <DataNotMatchException: (code=1, message=Attempt to insert an unexpected field to collection without enabling dynamic field)>
```

### Expected Behavior

insert successfully

### Steps To Reproduce

1. download dataset [Cleaned Medium Articles Dataset](https://www.kaggle.com/datasets/shiyu22chen/cleaned-medium-articles-dataset)
2. prepare data
```python
import pandas as pd
df = pd.read_csv('New_Medium_Data.csv', nrows=100)
df['var_array'] = df[['link', 'publication']].values.tolist()
df['int_array'] = df[['reading_time', 'claps', 'responses']].values.tolist()
df = df.drop(columns=['link', 'publication', 'reading_time', 'claps', 'responses'])
data = df.to_dict('records')
```
3. check the data
```
>>> data[0].keys()
dict_keys(['id', 'title', 'title_vector', 'var_array', 'int_array'])
```
4. create a collection
```python
from pymilvus import connections, Collection, FieldSchema, CollectionSchema, DataType
connections.connect()

fields = [
    FieldSchema(name='id', dtype=DataType.INT64, is_primary=True, auto_id=True, max_length=100),
    FieldSchema(name='title', dtype=DataType.VARCHAR, max_length=512),
    FieldSchema(name='title_vector', dtype=DataType.FLOAT_VECTOR, dim=768),
    FieldSchema(name='var_array', dtype=DataType.ARRAY, element_type=DataType.VARCHAR, max_capacity=900, max_length=1000),
    FieldSchema(name='int_array', dtype=DataType.ARRAY, element_type=DataType.INT64, max_capacity=900)
]

schema = CollectionSchema(
        fields,
        "The schema for a medium news collection",
        enable_dynamic_field=False
)

collection = Collection("medium_articles_with_array", schema)
```
5. insert data -> ❌

**Comment by NicoYuan1986** [comment]
when inserting rows:
```
>>> # 1. insert data
>>> collection.insert(data)
RPC error: [insert_rows], <DataNotMatchException: (code=1, message=The data in the same column must be of the same type.)>, <Time:{'RPC start': '2023-10-20 17:27:00.366133', 'RPC error': '2023-10-20 17:27:00.367069'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/pymilvus/orm/collection.py", line 509, in insert
    res = conn.insert_rows(
          ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pymilvus/decorators.py", line 129, in handler
    raise e from e
  File "/opt/homebrew/lib/python3.11/site-packages/pymilvus/decorators.py", line 125, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pymilvus/decorators.py", line 164, in handler
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pymilvus/decorators.py", line 104, in handler
    raise e from e
  File "/opt/homebrew/lib/python3.11/site-packages/pymilvus/decorators.py", line 68, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 504, in insert_rows
    request = self._prepare_row_insert_request(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 485, in _prepare_row_insert_request
    return Prepare.row_insert_param(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pymilvus/client/prepare.py", line 423, in row_insert_param
    return cls._parse_row_request(request, fields_info, enable_dynamic, entities)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pymilvus/client/prepare.py", line 386, in _parse_row_request
    raise DataNotMatchException(message=ExceptionsMessage.DataTypeInconsistent) from e
pymilvus.exceptions.DataNotMatchException: <DataNotMatchException: (code=1, message=The data in the same column must be of the same type.)>
>>> 
```
We can’t tell what the reason is from this error message.

**Comment by Elijas** [comment]
+1

**Comment by xiaofan-luan** [comment]
> +1

could you give details about which error message you are talking about

**Comment by Elijas** [comment]
> > +1
> 
> could you give details about which error message you are talking about

Of course! Thank you for a quick reply.

Zilliz Cloud + Milvus, collection BOOL field, sending value `null` (instead of true or false) results in:
```
RPC error: [upsert_rows], <DataNotMatchException: (code=1, message=The Input data type is inconsistent with defined schema, please check it.)>, <Time:{'RPC start': '2024-06-27 03:01:01.499781', 'RPC error': '2024-06-27 03:01:01.741953'}>
```
When sending large objects, it's difficult to tell what is causing the error, at least naming the problematic field would be highly helpful

**Comment by xiaofan-luan** [comment]
@xiaocai2333 

please help on refineing the log, adding which field has problem

**Comment by xiaocai2333** [comment]
It looks like an error message from pymilvus. I will optimize it.
keep it close, and open a new issue on pymilvus. https://github.com/milvus-io/pymilvus/issues/2154
