### ISSUE TITLE
[Bug]: [CI]Collection.has_index() is not accurate when upgrading pymilvus to 2.3.1.post1.dev6

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#27624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20231007-80eb5434
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.1.post1.dev6
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Collection.has_index() is not accurate when upgrading pymilvus to 2.3.1.post1.dev6.
```
[2023-10-10T10:04:53.660Z] [2023-10-10 09:40:25 - DEBUG - ci_test]: (api_request)  : [Collection.has_index] args: [], kwargs: {'index_name': 'binary_vector'} (api_request.py:62)
[2023-10-10T10:04:53.660Z] [2023-10-10 09:40:25 - ERROR - pymilvus.decorators]: RPC error: [describe_index], <AmbiguousIndexName: (code=1, message=There are multiple indexes, please specify the index_name.)>, <Time:{'RPC start': '2023-10-10 09:40:25.455505', 'RPC error': '2023-10-10 09:40:25.457861'}> (decorators.py:128)
[2023-10-10T10:04:53.660Z] [2023-10-10 09:40:25 - ERROR - ci_test]: Traceback (most recent call last):
[2023-10-10T10:04:53.660Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper
[2023-10-10T10:04:53.660Z]     res = func(*args, **_kwargs)
[2023-10-10T10:04:53.660Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request
[2023-10-10T10:04:53.660Z]     return func(*arg, **kwargs)
[2023-10-10T10:04:53.660Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 1240, in has_index
[2023-10-10T10:04:53.660Z]     if conn.describe_index(self._name, index_name, timeout=timeout, **copy_kwargs) is None:
[2023-10-10T10:04:53.660Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 129, in handler
[2023-10-10T10:04:53.660Z]     raise e from e
[2023-10-10T10:04:53.660Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 125, in handler
[2023-10-10T10:04:53.660Z]     return func(*args, **kwargs)
[2023-10-10T10:04:53.660Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 164, in handler
[2023-10-10T10:04:53.660Z]     return func(self, *args, **kwargs)
[2023-10-10T10:04:53.660Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 104, in handler
[2023-10-10T10:04:53.660Z]     raise e from e
[2023-10-10T10:04:53.660Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 68, in handler
[2023-10-10T10:04:53.660Z]     return func(*args, **kwargs)
[2023-10-10T10:04:53.660Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 945, in describe_index
[2023-10-10T10:04:53.660Z]     raise AmbiguousIndexName(message=ExceptionsMessage.AmbiguousIndexName)
[2023-10-10T10:04:53.660Z] pymilvus.exceptions.AmbiguousIndexName: <AmbiguousIndexName: (code=1, message=There are multiple indexes, please specify the index_name.)>
[2023-10-10T10:04:53.660Z]  (api_request.py:45)
[2023-10-10T10:04:53.660Z] [2023-10-10 09:40:25 - ERROR - ci_test]: (api_response) : <AmbiguousIndexName: (code=1, message=There are multiple indexes, please specify the index_name.)> (api_request.py:46)
```

### Expected Behavior

pass

### Steps To Reproduce

```markdown
1. create collection and a partition
2. insert data
3. create an index on vector field
4. collection.has_index() return True
5. drop the index
6. collection.has_index() return False. -> ❌
```

### Milvus Log

link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-27609/1/pipeline/129/

**Comment by NicoYuan1986** [comment]
one more:
collection.drop_index()
test_drop_index_repeatedly
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-27609/3/pipeline/129/

**Comment by xiaofan-luan** [comment]
seems that you have multiple index? @NicoYuan1986 
"There are multiple indexes, please specify the index_name"
if you have multiple index, you have to specify indexname

**Comment by NicoYuan1986** [comment]
> seems that you have multiple index? @NicoYuan1986 "There are multiple indexes, please specify the index_name" if you have multiple index, you have to specify indexname

No. Only one index.
![image](https://github.com/milvus-io/milvus/assets/109071306/d65eb717-0f7b-4a8f-b43f-38a5562eb5d9)

**Comment by NicoYuan1986** [comment]
![image](https://github.com/milvus-io/milvus/assets/109071306/f6da17a0-ac59-4d42-ae04-659d8aa33c19)

**Comment by NicoYuan1986** [comment]
seems not a pymilvus issue. it is milvus error code.

**Comment by NicoYuan1986** [comment]
Now the error changes to 
```
RPC error: [list_indexes], <MilvusException: (code=700, message=collection=index_ce49e6A0: index not found)>, <Time:{'RPC start': '2023-10-13 08:31:09.006086', 'RPC error': '2023-10-13 08:31:09.007693'}>
```

**Comment by zhuwenxing** [comment]
Because the error message has changed in the server, but pymilvus has not been updated to it. 
It used to be `INDEX_NOT_EXIST` but now it is `INDEX_NOT_FOUND`
![image](https://github.com/milvus-io/milvus/assets/12268675/2793cd11-6b8f-4dfe-ab17-56e1df02039f)

Milvus-backup also has this issue, which has been fixed by adding one more error message.
https://github.com/zilliztech/milvus-backup/pull/214/files

**Comment by NicoYuan1986** [comment]
@czs007  Could you help judge it is a milvus issue or pymilvus issue?

When using collection.has_index(), it should return False if index not exists.  
But now, it report error `index not found` or `There are multiple indexes`.

**Comment by XuanYang-cn** [comment]
will be fixed soon

**Comment by XuanYang-cn** [comment]
@NicoYuan1986 Please try pymilvus-2.3.1.post1.dev7

**Comment by NicoYuan1986** [comment]
verify fixed.
pymilvus: 2.3.1.post1.dev7
