### ISSUE TITLE
[Bug]: Check failed: IsGoogleLoggingIni tialized() You called ShutdownGoogleLogging() without calling InitGoogleLogging() 

### ISSUE THREAD

**Issue by chyezh** [milvus-io/milvus#27679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-cb71a3e2359215ada0372439d3f91547f88873b3
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus
- OS(Ubuntu or CentOS): MacOS
- CPU/Memory: M1 4G
- GPU: none
- Others:
```

### Current Behavior

- At starting of Milvus, Report a warning log.

```
WARNING: Logging before InitGoogleLogging() is written to STDERR
```

- Crash when shutdown.

```
F20231012 19:33:29.797937 264552052 utilities.cc:379] Check failed: IsGoogleLoggingIni
tialized() You called ShutdownGoogleLogging() without calling InitGoogleLogging() firs
t!
*** Check failure stack trace: ***
    @        0x108aa0340  google::LogMessageFatal::~LogMessageFatal()
    @        0x108a9c93c  google::LogMessageFatal::~LogMessageFatal()
    @        0x108aa6994  google::glog_internal_namespace_::ShutdownGoogleLoggingUtili
ties()
    @        0x108aa0754  google::ShutdownGoogleLogging()
SIGABRT: abort
PC=0x19608c724 m=3582 sigcode=0
signal arrived during cgo execution
```

### Expected Behavior

shutdown milvus without crash.

### Steps To Reproduce

```markdown
1. Start Milvus.
2. Run L0 L1 e2e tests.
3. Stop Milvus.
```

### Milvus Log

```
Welcome to use Milvus!
Version:   v2.2-testing-20230824-310-gcb71a3e23-dev
Built:     Thu Oct 12 04:01:00 UTC 2023
GitCommit: cb71a3e23
GoVersion: go version go1.21.1 darwin/arm64

open pid file: /tmp/milvus/standalone.pid
lock pid file: /tmp/milvus/standalone.pid
WARNING: Logging before InitGoogleLogging() is written to STDERR

....

F20231012 19:33:29.797937 264552052 utilities.cc:379] Check failed: IsGoogleLoggingIni
tialized() You called ShutdownGoogleLogging() without calling InitGoogleLogging() firs
t!
*** Check failure stack trace: ***
    @        0x108aa0340  google::LogMessageFatal::~LogMessageFatal()
    @        0x108a9c93c  google::LogMessageFatal::~LogMessageFatal()
    @        0x108aa6994  google::glog_internal_namespace_::ShutdownGoogleLoggingUtili
ties()
    @        0x108aa0754  google::ShutdownGoogleLogging()
SIGABRT: abort
PC=0x19608c724 m=3582 sigcode=0
signal arrived during cgo execution

goroutine 1312856 [syscall]:
runtime.cgocall(0x104db3910, 0x1400a427b08)
        /opt/homebrew/Cellar/go/1.21.1/libexec/src/runtime/cgocall.go:157 +0x44 fp=0x1
400a427ad0 sp=0x1400a427a90 pc=0x102dd29e4
github.com/milvus-io/milvus/internal/util/initcore._Cfunc_SegcoreCloseGlog()
        _cgo_gotypes.go:191 +0x30 fp=0x1400a427b00 sp=0x1400a427ad0 pc=0x1048b7270
github.com/milvus-io/milvus/internal/util/initcore.CleanGlogManager(...)
        /Users/zilliz/repo/github/chyezh/milvus/internal/util/initcore/init_core.go:11
3
github.com/milvus-io/milvus/internal/querynodev2.(*QueryNode).CloseSegcore(0x140013f46
c0?)
        /Users/zilliz/repo/github/chyezh/milvus/internal/querynodev2/server.go:259 +0x
28 fp=0x1400a427b10 sp=0x1400a427b00 pc=0x104d0c118
github.com/milvus-io/milvus/internal/querynodev2.(*QueryNode).Stop.func1()
        /Users/zilliz/repo/github/chyezh/milvus/internal/querynodev2/server.go:473 +0x
234 fp=0x1400a427df0 sp=0x1400a427b10 pc=0x104d0def4
sync.(*Once).doSlow(0x1?, 0x1?)
        /opt/homebrew/Cellar/go/1.21.1/libexec/src/sync/once.go:74 +0x100 fp=0x1400a42
7e50 sp=0x1400a427df0 pc=0x102e53500
sync.(*Once).Do(...)
        /opt/homebrew/Cellar/go/1.21.1/libexec/src/sync/once.go:65
github.com/milvus-io/milvus/internal/querynodev2.(*QueryNode).Stop(0x104dd3243?)
        /Users/zilliz/repo/github/chyezh/milvus/internal/querynodev2/server.go:412 +0x
48 fp=0x1400a427e80 sp=0x1400a427e50 pc=0x104d0dc98
github.com/milvus-io/milvus/internal/distributed/querynode.(*Server).Stop(0x1400123c60
0)
        /Users/zilliz/repo/github/chyezh/milvus/internal/distributed/querynode/service
.go:238 +0x124 fp=0x1400a427f50 sp=0x1400a427e80 pc=0x104d11d54
github.com/milvus-io/milvus/cmd/components.(*QueryNode).Stop(0x0?)
        /Users/zilliz/repo/github/chyezh/milvus/cmd/components/query_node.go:63 +0x20
fp=0x1400a427f70 sp=0x1400a427f50 pc=0x104d9b380
github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run.func2({0x105b07978?, 0x14000b
4a390?})
        /Users/zilliz/repo/github/chyezh/milvus/cmd/roles/roles.go:412 +0x5c fp=0x1400
a427fb0 sp=0x1400a427f70 pc=0x104d9f55c
github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run.func5()
        /Users/zilliz/repo/github/chyezh/milvus/cmd/roles/roles.go:413 +0x38 fp=0x1400
a427fd0 sp=0x1400a427fb0 pc=0x104d9f4c8
runtime.goexit()
        /opt/homebrew/Cellar/go/1.21.1/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x
1400a427fd0 sp=0x1400a427fd0 pc=0x102e435f4
created by github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run in goroutine 1
        /Users/zilliz/repo/github/chyezh/milvus/cmd/roles/roles.go:410 +0xbd8
```

**Comment by zhagnlu** [comment]
how you stop it , I can not reproduce it as your steps

**Comment by zhagnlu** [comment]
thread safe problem. glog init is not thread-safe, and for standalone mode, may catch multi init and close for indexnode and querynode.

**Comment by xiaohezi205** [comment]
加我1079361253微信 2.2.12版本arm64镜像免费送
