### ISSUE TITLE
[Bug]: Docker Started Exited on Standalone

### ISSUE THREAD

**Issue by kenneth-bro** [milvus-io/milvus#27690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.0
- Deployment mode(standalone or cluster):
standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
pymilvus 2.3.1
- OS(Ubuntu or CentOS): 
MacOS
- CPU/Memory: 
M1/32GB
- GPU: 
Apple
- Others:
```

### Current Behavior

connect on python

### Milvus Log

2023-10-13 11:22:24 goroutine 270 [running]:
2023-10-13 11:22:24 panic({0x391a860, 0x4001860f60})
2023-10-13 11:22:24     /usr/local/go/src/runtime/panic.go:987 +0x3ac fp=0x40019fff40 sp=0x40019ffe80 pc=0x15a89bc
2023-10-13 11:22:24 github.com/milvus-io/milvus/cmd/roles.runComponent[...].func1()
2023-10-13 11:22:24     /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:113 +0x19c fp=0x40019fffd0 sp=0x40019fff40 pc=0x33c426c
2023-10-13 11:22:24 runtime.goexit()
2023-10-13 11:22:24     /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x40019fffd0 sp=0x40019fffd0 pc=0x15e0894
2023-10-13 11:22:24 created by github.com/milvus-io/milvus/cmd/roles.runComponent[...]
2023-10-13 11:22:24     /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:99 +0x128
2023-10-13 11:22:24 
2023-10-13 11:22:24 goroutine 1 [semacquire]:
2023-10-13 11:22:24 runtime.gopark(0x5913ac0?, 0x1f?, 0x40?, 0xba?, 0x40fd728?)
2023-10-13 11:22:24     /usr/local/go/src/runtime/proc.go:381 +0xe0 fp=0x40018a9750 sp=0x40018a9730 pc=0x15aba60
2023-10-13 11:22:24 runtime.goparkunlock(...)
2023-10-13 11:22:24     /usr/local/go/src/runtime/proc.go:387
2023-10-13 11:22:24 runtime.semacquire1(0x40010149b8, 0x70?, 0x1, 0x0, 0xb0?)
2023-10-13 11:22:24     /usr/local/go/src/runtime/sema.go:160 +0x20c fp=0x40018a97b0 sp=0x40018a9750 pc=0x15bd9bc
2023-10-13 11:22:24 sync.runtime_Semacquire(0x3c28f08?)
2023-10-13 11:22:24     /usr/local/go/src/runtime/sema.go:62 +0x2c fp=0x40018a97f0 sp=0x40018a97b0 pc=0x15dc11c
2023-10-13 11:22:24 sync.(*WaitGroup).Wait(0x40010149b0)
2023-10-13 11:22:24     /usr/local/go/src/sync/waitgroup.go:116 +0x74 fp=0x40018a9810 sp=0x40018a97f0 pc=0x15f0974
2023-10-13 11:22:24 github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run(0x40018a9e30, 0x1, {0x400026c090?, 0xe?})
2023-10-13 11:22:24     /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:340 +0x714 fp=0x40018a9dd0 sp=0x40018a9810 pc=0x33c3b24
2023-10-13 11:22:24 github.com/milvus-io/milvus/cmd/milvus.(*run).execute(0x4000276000, {0x400011c060?, 0x3, 0x3}, 0x400024e480)
2023-10-13 11:22:24     /go/src/github.com/milvus-io/milvus/cmd/milvus/run.go:117 +0x680 fp=0x40018a9ec0 sp=0x40018a9dd0 pc=0x33ce1d0
2023-10-13 11:22:24 github.com/milvus-io/milvus/cmd/milvus.RunMilvus({0x400011c060?, 0x3, 0x3})
2023-10-13 11:22:24     /go/src/github.com/milvus-io/milvus/cmd/milvus/milvus.go:60 +0x244 fp=0x40018a9f40 sp=0x40018a9ec0 pc=0x33cda54
2023-10-13 11:22:24 main.main()
2023-10-13 11:22:24     /go/src/github.com/milvus-io/milvus/cmd/main.go:26 +0x34 fp=0x40018a9f70 sp=0x40018a9f40 pc=0x33d0524
2023-10-13 11:22:24 runtime.main()
2023-10-13 11:22:24     /usr/local/go/src/runtime/proc.go:250 +0x200 fp=0x40018a9fd0 sp=0x40018a9f70 pc=0x15ab650
2023-10-13 11:22:24 runtime.goexit()
2023-10-13 11:22:24     /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x40018a9fd0 sp=0x40018a9fd0 pc=0x15e0894
2023-10-13 11:22:24 
2023-10-13 11:22:24 goroutine 2 [force gc (idle)]:
2023-10-13 11:22:24 runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
2023-10-13 11:22:24     /usr/local/go/src/runtime/proc.go:381 +0xe0 fp=0x400007cfa0 sp=0x400007cf80 pc=0x15aba60
2023-10-13 11:22:24 runtime.goparkunlock(...)
2023-10-13 11:22:24     /usr/local/go/src/runtime/proc.go:387
2023-10-13 11:22:24 runtime.forcegchelper()
2023-10-13 11:22:24     /usr/local/go/src/runtime/proc.go:305 +0xb0 fp=0x400007cfd0 sp=0x400007cfa0 pc=0x15ab8b0
2023-10-13 11:22:24 runtime.goexit()
2023-10-13 11:22:24     /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x400007cfd0 sp=0x400007cfd0 pc=0x15e0894
2023-10-13 11:22:24 created by runtime.init.6
2023-10-13 11:22:24     /usr/local/go/src/runtime/proc.go:293 +0x24
2023-10-13 11:22:24 
2023-10-13 11:22:24 goroutine 3 [GC sweep wait]:
2023-10-13 11:22:24 runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
2023-10-13 11:22:24     /usr/local/go/src/runtime/proc.go:381 +0xe0 fp=0x400007d760 sp=0x400007d740 pc=0x15aba60
2023-10-13 11:22:24 runtime.goparkunlock(...)
2023-10-13 11:22:24     /usr/local/go/src/runtime/proc.go:387
2023-10-13 11:22:24 runtime.bgsweep(0x0?)
2023-10-13 11:22:24     /usr/local/go/src/runtime/mgcsweep.go:319 +0x100 fp=0x400007d7b0 sp=0x400007d760 pc=0x1594a70
2023-10-13 11:22:24 runtime.gcenable.func1()
2023-10-13 11:22:24     /usr/local/go/src/runtime/mgc.go:178 +0x28 fp=0x400007d7d0 sp=0x400007d7b0 pc=0x15898f8
2023-10-13 11:22:24 runtime.goexit()
2023-10-13 11:22:24     /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x400007d7d0 sp=0x400007d7d0 pc=0x15e0894
2023-10-13 11:22:24 created by runtime.gcenable
2023-10-13 11:22:24     /usr/local/go/src/runtime/mgc.go:178 +0x6c
2023-10-13 11:22:24 
2023-10-13 11:22:24 goroutine 4 [GC scavenge wait]:
2023-10-13 11:22:24 runtime.gopark(0x40000a6000?, 0x40c5c40?, 0x0?, 0x0?, 0x0?)
2023-10-13 11:22:24     /usr/local/go/src/runtime/proc.go:381 +0xe0 fp=0x400007df50 sp=0x400007df30 pc=0x15aba60
2023-10-13 11:22:24 runtime.goparkunlock(...)
2023-10-13 11:22:24     /usr/local/go/src/runtime/proc.go:387
2023-10-13 11:22:24 runtime.(*scavengerState).park(0x5907360)
2023-10-13 11:22:24     /usr/local/go/src/runtime/mgcscavenge.go:400 +0x5c fp=0x400007df80 sp=0x400007df50 pc=0x15928cc
2023-10-13 11:22:24 runtime.bgscavenge(0x0?)
2023-10-13 11:22:24     /usr/local/go/src/runtime/mgcscavenge.go:633 +0xa8 fp=0x400007dfb0 sp=0x400007df80 pc=0x1592e88
2023-10-13 11:22:24 runtime.gcenable.func2()
2023-10-13 11:22:24     /usr/local/go/src/runtime/mgc.go:179 +0x28 fp=0x400007dfd0 sp=0x400007dfb0 pc=0x1589898
2023-10-13 11:22:24 runtime.goexit()
2023-10-13 11:22:24     /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x400007dfd0 sp=0x400007dfd0 pc=0x15e0894
2023-10-13 11:22:24 created by runtime.gcenable
2023-10-13 11:22:24     /usr/local/go/src/runtime/mgc.go:179 +0xac
2023-10-13 11:22:24 
2023-10-13 11:22:24 goroutine 18 [finalizer wait]:
2023-10-13 11:22:24 runtime.gopark(0x0?, 0x3d4f380?, 0x0?, 0x20?, 0x1000000010?)
2023-10-13 11:22:24     /usr/local/go/src/runtime/proc.go:381 +0xe0 fp=0x400007c580 sp=0x400007c560 pc=0x15aba60
2023-10-13 11:22:24 runtime.runfinq()
2023-10-13 11:22:24     /usr/local/go/src/runtime/mfinal.go:193 +0x100 fp=0x400007c7d0 sp=0x400007c580 pc=0x15889c0
2023-10-13 11:22:24 runtime.goexit()
2023-10-13 11:22:24     /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x400007c7d0 sp=0x400007c7d0 pc=0x15e0894
2023-10-13 11:22:24 created by runtime.createfing
2023-10-13 11:22:24     /usr/local/go/src/runtime/mfinal.go:163 +0x80
2023-10-13 11:22:24 
2023-10-13 11:22:24 goroutine 19 [GC worker (idle)]:
2023-10-13 11:22:24 runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
2023-10-13 11:22:24     /usr/local/go/src/runtime/proc.go:381 +0xe0 fp=0x4000078740 sp=0x4000078720 pc=0x15aba60
2023-10-13 11:22:24 runtime.gcBgMarkWorker()
2023-10-13 11:22:24     /usr/local/go/src/runtime/mgc.go:1275 +0xe4 fp=0x40000787d0 sp=0x4000078740 pc=0x158b6d4
2023-10-13 11:22:24 runtime.goexit()
2023-10-13 11:22:24     /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x40000787d0 sp=0x40000787d0 pc=0x15e0894
2023-10-13 11:22:24 created by runtime.gcBgMarkStartWorkers
2023-10-13 11:22:24     /usr/local/go/src/runtime/mgc.go:1199 +0x28
2023-10-13 11:22:24 
2023-10-13 11:22:24 goroutine 20 [GC worker (idle)]:
2023-10-13 11:22:24 runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
2023-10-13 11:22:24     /usr/local/go/src/runtime/proc.go:381 +0xe0 fp=0x4000078f40 sp=0x4000078f20 pc=0x15aba60
2023-10-13 11:22:24 runtime.gcBgMarkWorker()
2023-10-13 11:22:24     /usr/local/go/src/runtime/mgc.go:1275 +0xe4 fp=0x4000078fd0 sp=0x4000078f40 pc=0x158b6d4
2023-10-13 11:22:24 runtime.goexit()
2023-10-13 11:22:24     /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x4000078fd0 sp=0x4000078fd0 pc=0x15e0894
2023-10-13 11:22:24 created by runtime.gcBgMarkStartWorkers
2023-10-13 11:22:24     /usr/local/go/src/runtime/mgc.go:1199 +0x28
2023-10-13 11:22:24 
2023-10-13 11:22:24 goroutine 21 [GC worker (idle)]:
2023-10-13 11:22:24 runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
2023-10-13 11:22:24     /usr/local/go/src/runtime/proc.go:381 +0xe0 fp=0x4000079740 sp=0x4000079720 pc=0x15aba60
2023-10-13 11:22:24 runtime.gcBgMarkWorker()
2023-10-13 11:22:24     /usr/local/go/src/runtime/mgc.go:1275 +0xe4 fp=0x40000797d0 sp=0x4000079740 pc=0x158b6d4
2023-10-13 11:22:24 runtime.goexit()
2023-10-13 11:22:24     /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x40000797d0 sp=0x40000797d0 pc=0x15e0894
2023-10-13 11:22:24 created by runtime.gcBgMarkStartWorkers
2023-10-13 11:22:24     /usr/local/go/src/runtime/mgc.go:1199 +0x28
2023-10-13 11:22:24 
2023-10-13 11:22:24 goroutine 22 [GC worker (idle)]:
2023-10-13 11:22:24 runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
2023-10-13 11:22:24     /usr/local/go/src/runtime/proc.go:381 +0xe0 fp=0x4000079f40 sp=0x4000079f20 pc=0x15aba60
2023-10-13 11:22:24 runtime.gcBgMarkWorker()
2023-10-13 11:22:24     /usr/local/go/src/runtime/mgc.go:1275 +0xe4 fp=0x4000079fd0 sp=0x4000079f40 pc=0x158b6d4
2023-10-13 11:22:24 runtime.goexit()
2023-10-13 11:22:24     /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x4000079fd0 sp=0x4000079fd0 pc=0x15e0894
2023-10-13 11:22:24 created by runtime.gcBgMarkStartWorkers
2023-10-13 11:22:24     /usr/local/go/src/runtime/mgc.go:1199 +0x28
2023-10-13 11:22:24 
2023-10-13 11:22:24 goroutine 23 [GC worker (idle)]:
2023-10-13 11:22:24 runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
2023-10-13 11:22:24     /usr/local/go/src/runtime/proc.go:381 +0xe0 fp=0x400007a740 sp=0x400007a720 pc=0x15aba60
2023-10-13 11:22:24 runtime.gcBgMarkWorker()
2023-10-13 11:22:24     /usr/local/go/src/runtime/mgc.go:1275 +0xe4 fp=0x400007a7d0 sp=0x400007a740 pc=0x158b6d4
2023-10-13 11:22:24 runtime.goexit()
2023-10-13 11:22:24     /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x400007a7d0 sp=0x400007a7d0 pc=0x15e0894
2023-10-13 11:22:24 created by runtime.gcBgMarkStartWorkers
2023-10-13 11:22:24     /usr/local/go/src/runtime/mgc.go:1199 +0x28
2023-10-13 11:22:24 
2023-10-13 11:22:24 goroutine 24 [GC worker (idle)]:
2023-10-13 11:22:24 runtime.gopark(0x3ecf10a109d5?, 0x3?, 0xb5?, 0x32?, 0x0?)
2023-10-13 11:22:24     /usr/local/go/src/runtime/proc.go:381 +0xe0 fp=0x400007af40 sp=0x400007af20 pc=0x15aba60
2023-10-13 11:22:24 runtime.gcBgMarkWorker()
2023-10-13 11:22:24     /usr/local/go/src/runtime/mgc.go:1275 +0xe4 fp=0x400007afd0 sp=0x400007af40 pc=0x158b6d4
2023-10-13 11:22:24 runtime.goexit()
2023-10-13 11:22:24     /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x400007afd0 sp=0x400007afd0 pc=0x15e0894
2023-10-13 11:22:24 created by runtime.gcBgMarkStartWorkers
2023-10-13 11:22:24     /usr/local/go/src/runtime/mgc.go:1199 +0x28

**Comment by yanliang567** [comment]
@kenneth-bro quick question
1. does Milvus exit when initializing or when trying to connect it by pymilvus?
2. if former, please share more details about how you deploy milvus and your configurations
3. if latter, please share the full milvus logs. For Milvus installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs.

/assign @kenneth-bro 
/unassign

**Comment by kenneth-bro** [comment]
> @kenneth-bro quick question 快速提问
> 
> 1. does Milvus exit when initializing or when trying to connect it by pymilvus?Milvus 在初始化或尝试通过 pymilvus 连接时退出吗？
> 2. if former, please share more details about how you deploy milvus and your configurations如果是前者，请分享有关如何部署 milvus 和配置的更多详细信息
> 3. if latter, please share the full milvus logs. For Milvus installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs.如果是后者，请分享完整的 milvus 日志。对于使用 docker-compose 安装的 Milvus，可以使用 docker-compose logs > milvus.log 导出日志。
> 
> /assign  /分配@kenneth-bro /unassign  /取消分配

i have Solve it.
