### ISSUE TITLE
[Bug]: Flush timeout after datacoord pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#27847]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20231021-d2dbbbc1
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka): pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```

[2023-10-22T21:44:47.105Z] [2023-10-22 21:23:18 - DEBUG - ci_test]: (api_request)  : [Connections.connect] args: ['default', '', '', ''], kwargs: {'host': '10.255.146.172', 'port': 19530} (api_request.py:62)

[2023-10-22T21:44:47.105Z] [2023-10-22 21:23:18 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-10-22T21:44:47.105Z] [2023-10-22 21:23:18 - DEBUG - ci_test]: (api_request)  : [Connections.has_connection] args: ['default'], kwargs: {} (api_request.py:62)

[2023-10-22T21:44:47.105Z] [2023-10-22 21:23:18 - DEBUG - ci_test]: (api_response) : True  (api_request.py:37)

[2023-10-22T21:44:47.105Z] [2023-10-22 21:23:18 - DEBUG - ci_test]: (api_request)  : [Collection] args: ['Checker__VohwzxtG', {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}, {'name': 'varchar', 'description': '', 'type': <DataType......, kwargs: {'consistency_level': 'Strong'} (api_request.py:62)

[2023-10-22T21:44:47.105Z] [2023-10-22 21:23:18 - DEBUG - ci_test]: (api_response) : <Collection>:

[2023-10-22T21:44:47.105Z] -------------

[2023-10-22T21:44:47.105Z] <name>: Checker__VohwzxtG

[2023-10-22T21:44:47.105Z] <description>: 

[2023-10-22T21:44:47.105Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}......  (api_request.py:37)

[2023-10-22T21:44:47.105Z] [2023-10-22 21:23:18 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2023-10-22T21:44:47.105Z] [2023-10-22 21:26:19 - WARNING - pymilvus.decorators]: Retry timeout: 180s (decorators.py:94)

[2023-10-22T21:44:47.105Z] [2023-10-22 21:26:19 - ERROR - pymilvus.decorators]: RPC error: [flush], <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for flush timeout, collection: Checker__VohwzxtG)>, <Time:{'RPC start': '2023-10-22 21:23:18.953073', 'RPC error': '2023-10-22 21:26:19.413758'}> (decorators.py:128)

[2023-10-22T21:44:47.105Z] [2023-10-22 21:26:19 - ERROR - ci_test]: Traceback (most recent call last):

[2023-10-22T21:44:47.105Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2023-10-22T21:44:47.105Z]     res = func(*args, **_kwargs)

[2023-10-22T21:44:47.105Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2023-10-22T21:44:47.105Z]     return func(*arg, **kwargs)

[2023-10-22T21:44:47.105Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 314, in flush

[2023-10-22T21:44:47.105Z]     conn.flush([self.name], timeout=timeout, **kwargs)

[2023-10-22T21:44:47.105Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 129, in handler

[2023-10-22T21:44:47.105Z]     raise e from e

[2023-10-22T21:44:47.105Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 125, in handler

[2023-10-22T21:44:47.105Z]     return func(*args, **kwargs)

[2023-10-22T21:44:47.105Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 164, in handler

[2023-10-22T21:44:47.105Z]     return func(self, *args, **kwargs)

[2023-10-22T21:44:47.105Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 95, in handler

[2023-10-22T21:44:47.105Z]     raise MilvusException(

[2023-10-22T21:44:47.105Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for flush timeout, collection: Checker__VohwzxtG)>

[2023-10-22T21:44:47.105Z]  (api_request.py:45)

[2023-10-22T21:44:47.106Z] [2023-10-22 21:26:19 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for flush timeout, collection: Checker__VohwzxtG)> (api_request.py:46)
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/8538/pipeline

log:
[artifacts-datacoord-pod-kill-8538-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/13065736/artifacts-datacoord-pod-kill-8538-pytest-logs.tar.gz)
[artifacts-datacoord-pod-kill-8538-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/13065737/artifacts-datacoord-pod-kill-8538-server-logs.tar.gz)

**Comment by bigsheeper** [comment]
[2023/10/22 21:26:15.899 +00:00] [INFO] [datacoord/services.go:1248] ["GetFlushState failed, channel unflushed"] [traceID=b68f09c222225b1551d11472c0228341] [collection=445122607478287008] [flushTs=2023/10/22 21:23:18.933 +00:00] [channel=by-dev-rootcoord-dml_12_445122607478287008v1] [CP=2023/10/22 21:05:53.183 +00:00] [lag=**17m25.75s**]

![image](https://github.com/milvus-io/milvus/assets/42060877/29b4215f-6fac-49f6-92f2-b0f9187f9a17)
