### ISSUE TITLE
[Bug]: Error message needs to be optimized to make it more user-friendly

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#27886]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2ea7579
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.1.post1.dev18
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Error message needs to be optimized to make it more user-friendly.

load collection error:
```
[2023-10-23T20:14:51.978Z] [2023-10-23 18:35:44 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=10001, message=failed to load collection: stack trace: /go/src/github.com/milvus-io/milvus/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace
[2023-10-23T20:14:51.978Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:491 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call
[2023-10-23T20:14:51.978Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:505 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall
[2023-10-23T20:14:51.978Z] /go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:102 github.com/milvus-io/milvus/internal/distributed/datacoord/client.wrapGrpcCall[...]
[2023-10-23T20:14:51.978Z] /go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:588 github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).DescribeIndex
[2023-10-23T20:14:51.978Z] /go/src/github.com/milvus-io/milvus/internal/querycoordv2/meta/coordinator_broker.go:240 github.com/milvus-io/milvus/internal/querycoordv2/meta.(*CoordinatorBroker).DescribeIndex
[2023-10-23T20:14:51.978Z] /go/src/github.com/milvus-io/milvus/internal/querycoordv2/job/utils.go:81 github.com/milvus-io/milvus/internal/querycoordv2/job.loadPartitions
[2023-10-23T20:14:51.978Z] /go/src/github.com/milvus-io/milvus/internal/querycoordv2/job/job_load.go:164 github.com/milvus-io/milvus/internal/querycoordv2/job.(*LoadCollectionJob).Execute
[2023-10-23T20:14:51.978Z] /go/src/github.com/milvus-io/milvus/internal/querycoordv2/job/scheduler.go:159 github.com/milvus-io/milvus/internal/querycoordv2/job.(*Scheduler).process
[2023-10-23T20:14:51.978Z] /go/src/github.com/milvus-io/milvus/internal/querycoordv2/job/scheduler.go:135 github.com/milvus-io/milvus/internal/querycoordv2/job.(*Scheduler).processQueue: attempt #0: rpc error: code = DeadlineExceeded desc = context deadline exceeded: context deadline exceeded)>, <Time:{'RPC start': '2023-10-23 18:35:35.481323', 'RPC error': '2023-10-23 18:35:44.567273'}> (decorators.py:128)
[2023-10-23T20:14:51.978Z] [2023-10-23 18:35:44 - ERROR - ci_test]: Traceback (most recent call last):
[2023-10-23T20:14:51.978Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper
[2023-10-23T20:14:51.978Z]     res = func(*args, **_kwargs)
[2023-10-23T20:14:51.978Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request
[2023-10-23T20:14:51.978Z]     return func(*arg, **kwargs)
[2023-10-23T20:14:51.978Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 419, in load
[2023-10-23T20:14:51.978Z]     conn.load_collection(
[2023-10-23T20:14:51.978Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 129, in handler
[2023-10-23T20:14:51.978Z]     raise e from e
[2023-10-23T20:14:51.978Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 125, in handler
[2023-10-23T20:14:51.978Z]     return func(*args, **kwargs)
[2023-10-23T20:14:51.978Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 164, in handler
[2023-10-23T20:14:51.978Z]     return func(self, *args, **kwargs)
[2023-10-23T20:14:51.978Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 104, in handler
[2023-10-23T20:14:51.978Z]     raise e from e
[2023-10-23T20:14:51.978Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 68, in handler
[2023-10-23T20:14:51.978Z]     return func(*args, **kwargs)
[2023-10-23T20:14:51.978Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 1033, in load_collection
[2023-10-23T20:14:51.978Z]     raise MilvusException(response.code, response.reason, response.error_code)
[2023-10-23T20:14:51.978Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=10001, message=failed to load collection: stack trace: /go/src/github.com/milvus-io/milvus/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace
[2023-10-23T20:14:51.978Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:491 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call
[2023-10-23T20:14:51.978Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:505 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall
[2023-10-23T20:14:51.978Z] /go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:102 github.com/milvus-io/milvus/internal/distributed/datacoord/client.wrapGrpcCall[...]
[2023-10-23T20:14:51.978Z] /go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:588 github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).DescribeIndex
[2023-10-23T20:14:51.978Z] /go/src/github.com/milvus-io/milvus/internal/querycoordv2/meta/coordinator_broker.go:240 github.com/milvus-io/milvus/internal/querycoordv2/meta.(*CoordinatorBroker).DescribeIndex
[2023-10-23T20:14:51.978Z] /go/src/github.com/milvus-io/milvus/internal/querycoordv2/job/utils.go:81 github.com/milvus-io/milvus/internal/querycoordv2/job.loadPartitions
[2023-10-23T20:14:51.978Z] /go/src/github.com/milvus-io/milvus/internal/querycoordv2/job/job_load.go:164 github.com/milvus-io/milvus/internal/querycoordv2/job.(*LoadCollectionJob).Execute
[2023-10-23T20:14:51.978Z] /go/src/github.com/milvus-io/milvus/internal/querycoordv2/job/scheduler.go:159 github.com/milvus-io/milvus/internal/querycoordv2/job.(*Scheduler).process
[2023-10-23T20:14:51.978Z] /go/src/github.com/milvus-io/milvus/internal/querycoordv2/job/scheduler.go:135 github.com/milvus-io/milvus/internal/querycoordv2/job.(*Scheduler).processQueue: attempt #0: rpc error: code = DeadlineExceeded desc = context deadline exceeded: context deadline exceeded)>
[2023-10-23T20:14:51.978Z]  (api_request.py:45)
[2023-10-23T20:14:51.978Z] [2023-10-23 18:35:44 - ERROR - ci_test]: (api_response) : <MilvusException: (code=10001, message=failed to load collection: stack trace: /go/src/github.com/milvus-io/milvus/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace
[2023-10-23T20:14:51.978Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:491 github.com/milvus-io/milvus/int...... (api_request.py:46)
```

I can't figure out from the above why the load failed.

### Expected Behavior

Improve error messages and causes

### Milvus Log

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/537/pipeline/193/

**Comment by NicoYuan1986** [comment]
invalid dim:
before:
The dimension of query entities is different from schema
now:
message=failed to search/query delegator 2 for channel in01-67dc87b439bb8fc-rootcoord-dml_1_446405174423421363v0: fail to Search, QueryNode ID=2, reason=worker(2) query failed: UnknownError: Assert "field_meta.get_sizeof() == element.line_sizeof_" at /go/src/github.com/milvus-io/milvus/internal/core/src/query/Plan.cpp:52
 => vector dimension mismatch)>

**Comment by NicoYuan1986** [comment]
update: 
reproduce on master and 2.3 branch
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.3/51/pipeline/201/
```
[2023-12-27T22:56:31.190Z] [2023-12-27 21:58:33 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 180], kwargs: {} (api_request.py:62)
[2023-12-27T22:56:31.190Z] [2023-12-27 21:58:38 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=65535, message=stack trace: /go/src/github.com/milvus-io/milvus/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace
[2023-12-27T22:56:31.190Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:550 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call
[2023-12-27T22:56:31.190Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:564 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall
[2023-12-27T22:56:31.190Z] /go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/client/client.go:106 github.com/milvus-io/milvus/internal/distributed/rootcoord/client.wrapGrpcCall[...]
[2023-12-27T22:56:31.190Z] /go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/client/client.go:274 github.com/milvus-io/milvus/internal/distributed/rootcoord/client.(*Client).ShowPartitions
[2023-12-27T22:56:31.190Z] /go/src/github.com/milvus-io/milvus/internal/querycoordv2/meta/coordinator_broker.go:95 github.com/milvus-io/milvus/internal/querycoordv2/meta.(*CoordinatorBroker).GetPartitions
[2023-12-27T22:56:31.190Z] /go/src/github.com/milvus-io/milvus/internal/querycoordv2/job/job_load.go:116 github.com/milvus-io/milvus/internal/querycoordv2/job.(*LoadCollectionJob).Execute
[2023-12-27T22:56:31.190Z] /go/src/github.com/milvus-io/milvus/internal/querycoordv2/job/scheduler.go:159 github.com/milvus-io/milvus/internal/querycoordv2/job.(*Scheduler).process
[2023-12-27T22:56:31.190Z] /go/src/github.com/milvus-io/milvus/internal/querycoordv2/job/scheduler.go:135 github.com/milvus-io/milvus/internal/querycoordv2/job.(*Scheduler).processQueue
[2023-12-27T22:56:31.190Z] /usr/local/go/src/runtime/asm_amd64.s:1598 runtime.goexit: attempt #0: rpc error: code = DeadlineExceeded desc = context deadline exceeded)>, <Time:{'RPC start': '2023-12-27 21:58:33.846485', 'RPC error': '2023-12-27 21:58:38.857479'}> (decorators.py:128)
[2023-12-27T22:56:31.190Z] [2023-12-27 21:58:38 - ERROR - ci_test]: Traceback (most recent call last):
[2023-12-27T22:56:31.190Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper
[2023-12-27T22:56:31.190Z]     res = func(*args, **_kwargs)
[2023-12-27T22:56:31.190Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request
[2023-12-27T22:56:31.190Z]     return func(*arg, **kwargs)
[2023-12-27T22:56:31.190Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 419, in load
[2023-12-27T22:56:31.190Z]     conn.load_collection(
[2023-12-27T22:56:31.190Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 129, in handler
[2023-12-27T22:56:31.190Z]     raise e from e
[2023-12-27T22:56:31.190Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 125, in handler
[2023-12-27T22:56:31.190Z]     return func(*args, **kwargs)
[2023-12-27T22:56:31.190Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 164, in handler
[2023-12-27T22:56:31.190Z]     return func(self, *args, **kwargs)
[2023-12-27T22:56:31.190Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 104, in handler
[2023-12-27T22:56:31.190Z]     raise e from e
[2023-12-27T22:56:31.190Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 68, in handler
[2023-12-27T22:56:31.190Z]     return func(*args, **kwargs)
[2023-12-27T22:56:31.190Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 982, in load_collection
[2023-12-27T22:56:31.190Z]     check_status(response)
[2023-12-27T22:56:31.190Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/utils.py", line 54, in check_status
[2023-12-27T22:56:31.190Z]     raise MilvusException(status.code, status.reason, status.error_code)
[2023-12-27T22:56:31.190Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=stack trace: /go/src/github.com/milvus-io/milvus/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace
[2023-12-27T22:56:31.190Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:550 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call
[2023-12-27T22:56:31.190Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:564 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall
[2023-12-27T22:56:31.190Z] /go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/client/client.go:106 github.com/milvus-io/milvus/internal/distributed/rootcoord/client.wrapGrpcCall[...]
[2023-12-27T22:56:31.190Z] /go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/client/client.go:274 github.com/milvus-io/milvus/internal/distributed/rootcoord/client.(*Client).ShowPartitions
[2023-12-27T22:56:31.190Z] /go/src/github.com/milvus-io/milvus/internal/querycoordv2/meta/coordinator_broker.go:95 github.com/milvus-io/milvus/internal/querycoordv2/meta.(*CoordinatorBroker).GetPartitions
[2023-12-27T22:56:31.190Z] /go/src/github.com/milvus-io/milvus/internal/querycoordv2/job/job_load.go:116 github.com/milvus-io/milvus/internal/querycoordv2/job.(*LoadCollectionJob).Execute
[2023-12-27T22:56:31.190Z] /go/src/github.com/milvus-io/milvus/internal/querycoordv2/job/scheduler.go:159 github.com/milvus-io/milvus/internal/querycoordv2/job.(*Scheduler).process
[2023-12-27T22:56:31.191Z] /go/src/github.com/milvus-io/milvus/internal/querycoordv2/job/scheduler.go:135 github.com/milvus-io/milvus/internal/querycoordv2/job.(*Scheduler).processQueue
[2023-12-27T22:56:31.191Z] /usr/local/go/src/runtime/asm_amd64.s:1598 runtime.goexit: attempt #0: rpc error: code = DeadlineExceeded desc = context deadline exceeded)>
[2023-12-27T22:56:31.191Z]  (api_request.py:45)
[2023-12-27T22:56:31.191Z] [2023-12-27 21:58:38 - ERROR - ci_test]: (api_response) : <MilvusException: (code=65535, message=stack trace: /go/src/github.com/milvus-io/milvus/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace
[2023-12-27T22:56:31.191Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:550 github.com/milvus-io/milvus/internal/util/grpcclient.(*Cli...... (api_request.py:46)
```

**Comment by NicoYuan1986** [comment]
latest: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.3/62/pipeline/237

@yah01  please help.

**Comment by yah01** [comment]
This is introduced by SDK changes, as Milvus doesn't contain the error message "The dimension of query entities is different from schema", or the "10001" error code. I will optimize this but it can't be the same as before

**Comment by yah01** [comment]
#30316 has fixed the dimension error message
