### ISSUE TITLE
Create index failed with index type: IVF_PQ

### ISSUE THREAD

**Issue by Bennu-Li** [milvus-io/milvus#2792]
**Please state you issue using the following template and, most importantly, in English.**

**Describe the bug**
index: ivf_pq   m=64
An error occurred while building the index.
![image](https://user-images.githubusercontent.com/53458891/87025782-6995a680-c20d-11ea-969d-a511e3208e3c.png)

**Environment details**
- GeForce RTX 2080 Ti *4
- GPU MEM: 12G
- Milvus version (v0.10.0  gpu)

**Comment by del-zhenwu** [comment]
```
11:21:58  2020-07-10:03:21:57,868 INFO     [client.py:215] Building index start, collection_name: sift_10m_1024_128_l2, index_type: IVF_PQ
11:21:58  2020-07-10:03:21:57,868 INFO     [client.py:217] {'nlist': 10000, 'm': 64}

11:22:54  2020-07-10:03:22:48,269 ERROR    [client.py:99] Error in void faiss::gpu::GpuIndexIVFPQ::verifySettings_() const at gpu/GpuIndexIVFPQ.cu:444: Error: 'requiredSmemSize <= getMaxSharedMemPerBlock(device_)' failed: Device 0 has 49152 bytes of shared memory, while 8 bits per code and 64 sub-quantizers requires 65536 bytes. Consider useFloat16LookupTables and/or reduce parameters
11:22:54  2020-07-10:03:22:48,271 ERROR    [client.py:100] (Status(code=0, message='Success!'), 'OK')
11:22:54  2020-07-10:03:22:48,274 DEBUG    [client.py:263] (Status(code=0, message='Success!'), 10000000)
11:22:54  2020-07-10:03:22:48,277 DEBUG    [client.py:267] Row count: 10000000 in collection: <sift_10m_1024_128_l2>
11:22:54  2020-07-10:03:22:48,277 ERROR    [client.py:101] 10000000
11:22:54  2020-07-10:03:22:48,277 ERROR    [main.py:70] Status not ok
11:22:54  2020-07-10:03:22:48,279 ERROR    [main.py:71] Traceback (most recent call last):
11:22:54    File "main.py", line 68, in queue_worker
11:22:54      runner.run(run_type, collection)
11:22:54    File "/home/jenkins/agent/workspace/milvus-benchmark-0.10.1/milvus_benchmark/k8s_runner.py", line 258, in run
11:22:54      milvus_instance.create_index(index_type, index_param)
11:22:54    File "/home/jenkins/agent/workspace/milvus-benchmark-0.10.1/milvus_benchmark/client.py", line 44, in wrapper
11:22:54      result = func(*args, **kwargs)
11:22:54    File "/home/jenkins/agent/workspace/milvus-benchmark-0.10.1/milvus_benchmark/client.py", line 219, in create_index
11:22:54      self.check_status(status)
11:22:54    File "/home/jenkins/agent/workspace/milvus-benchmark-0.10.1/milvus_benchmark/client.py", line 102, in check_status
11:22:54      raise Exception("Status not ok")
11:22:54  Exception: Status not ok
```

**Comment by shengjun1985** [comment]
It is a limitation of the GPU algorithm.
When creating IVF_PQ on GPU, the max 'M' is 48.
We will add it in the DOC.
