### ISSUE TITLE
[Bug]:  querynode SIGSEGV panic 

### ISSUE THREAD

**Issue by jaime0815** [milvus-io/milvus#28022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7f877eb9ed74]
runtime stack:
runtime.throw({0x4745629?, 0x2?})
        /usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7f83bfbcd578 sp=0x7f83bfbcd548 pc=0x178505d
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:825 +0x3e9 fp=0x7f83bfbcd5d8 sp=0x7f83bfbcd578 pc=0x179cec9
goroutine 7070 [syscall]:
_ZNK6milvus19CollectionIndexMeta19GetIndexMaxRowCountEv
        /go/src/[github.com/milvus-io/milvus/internal/core/src/common/IndexMeta.cpp:61](http://github.com/milvus-io/milvus/internal/core/src/common/IndexMeta.cpp:61) pc=0x7f877eb9ed74
_ZN6milvus7segcore14IndexingRecord10InitializeEv
        /go/src/[github.com/milvus-io/milvus/internal/core/src/segcore/FieldIndexing.h:252](http://github.com/milvus-io/milvus/internal/core/src/segcore/FieldIndexing.h:252) pc=0x7f877fba8e11
_ZN6milvus7segcore14IndexingRecordC4ERKNS_6SchemaERKSt10shared_ptrINS_19CollectionIndexMetaEERKNS0_13SegcoreConfigE
        /go/src/[github.com/milvus-io/milvus/internal/core/src/segcore/FieldIndexing.h:237](http://github.com/milvus-io/milvus/internal/core/src/segcore/FieldIndexing.h:237) pc=0x7f877fb9c1ab
_ZN6milvus7segcore18SegmentGrowingImplC4ESt10shared_ptrINS_6SchemaEES2_INS_19CollectionIndexMetaEERKNS0_13SegcoreConfigEl
        /go/src/[github.com/milvus-io/milvus/internal/core/src/segcore/SegmentGrowingImpl.h:202](http://github.com/milvus-io/milvus/internal/core/src/segcore/SegmentGrowingImpl.h:202) pc=0x7f877fb9c1ab
_ZSt11make_uniqueIN6milvus7segcore18SegmentGrowingImplEJRSt10shared_ptrINS0_6SchemaEERS3_INS0_19CollectionIndexMetaEERKNS1_13SegcoreConfigERlEENSt9_MakeUniqIT_E15__single_objectEDpOT0_
        /usr/include/c++/9/bits/unique_ptr.h:857 pc=0x7f877fb9c1ab
_ZN6milvus7segcore20CreateGrowingSegmentESt10shared_ptrINS_6SchemaEES1_INS_19CollectionIndexMetaEElRKNS0_13SegcoreConfigE
        /go/src/[github.com/milvus-io/milvus/internal/core/src/segcore/SegmentGrowingImpl.h:302](http://github.com/milvus-io/milvus/internal/core/src/segcore/SegmentGrowingImpl.h:302) pc=0x7f877fb9c1ab
NewSegment
        /go/src/[github.com/milvus-io/milvus/internal/core/src/segcore/segment_c.cpp:38](http://github.com/milvus-io/milvus/internal/core/src/segcore/segment_c.cpp:38) pc=0x7f877fb9c1ab
_cgo_ca1ef8f75683_Cfunc_NewSegment
        /tmp/go-build/cgo-gcc-prolog:227 pc=0x3e3e3a1
runtime.asmcgocall
        /usr/local/go/src/runtime/asm_amd64.s:848 pc=0x17be663
runtime.cgocall(0x3e3e380, 0xc0040b5c68)
        /usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc0040b5c40 sp=0xc0040b5c08 pc=0x174d77c
[github.com/milvus-io/milvus/internal/querynodev2/segments._Cfunc_NewSegment(0x7f8507e03000,](http://github.com/milvus-io/milvus/internal/querynodev2/segments._Cfunc_NewSegment(0x7f8507e03000,) 0x1, 0x62e01fc814f1015)
        _cgo_gotypes.go:735 +0x4d fp=0xc0040b5c68 sp=0xc0040b5c40 pc=0x3c2694d
[github.com/milvus-io/milvus/internal/querynodev2/segments.NewSegment.func2(0x0?,](http://github.com/milvus-io/milvus/internal/querynodev2/segments.NewSegment.func2(0x0?,) 0x0?)
        /go/src/[github.com/milvus-io/milvus/internal/querynodev2/segments/segment.go:175](http://github.com/milvus-io/milvus/internal/querynodev2/segments/segment.go:175) +0x55 fp=0xc0040b5ca8 sp=0xc0040b5c68 pc=0x3c32d15
[github.com/milvus-io/milvus/internal/querynodev2/segments.NewSegment(0x4bfd960?,](http://github.com/milvus-io/milvus/internal/querynodev2/segments.NewSegment(0x4bfd960?,) 0x62e01fc814f1015, 0x62e01fc814c02a1, 0x62e01fc814c02a0, {0xc007d108c0, 0x39}, 0x2, 0x1792e3322f076cdf, 0x0, 0x0)
        /go/src/[github.com/milvus-io/milvus/internal/querynodev2/segments/segment.go:175](http://github.com/milvus-io/milvus/internal/querynodev2/segments/segment.go:175) +0x10c fp=0xc0040b5e90 sp=0xc0040b5ca8 pc=0x3c326ac
```
https://grafana-4am.zilliz.cc/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22chaos-testing%5C%22,%20pod%3D~%5C%22kafka-standalone-222-milvus.*%5C%22%7D%20%7C~%5C%22coord%20stop%7Cnode%20stop%7Cquit%20STANDBY%7CCoord%20stop%7Cpanic%7CGitCommit%7Cstartup%7CGraceful%20stop%20grpc%20server%7Cclean%20sessions%5C%22%20!%3D%5C%22failed%20to%20get%20client%20address%5C%22%20!%3D%5C%22unknown%20method%20DropIndex%20%5C%22%22,%22queryType%22:%22range%22,%22hide%22:false%7D,%7B%22refId%22:%22B%22,%22expr%22:%22%7Bnamespace%3D%5C%22chaos-testing%5C%22,%20pod%3D~%5C%22kafka-standalone-222-milvus-.*%5C%22%7D%20%20%7C~%5C%22failed%20to%20WaitToFinish%7Cpanic%7Cetcd%5C%22%20!%3D%5C%22there%20is%20no%20IndexNode%20available%5C%22%22,%22queryType%22:%22range%22,%22hide%22:true%7D,%7B%22refId%22:%22C%22,%22expr%22:%22%7Bnamespace%3D%5C%22chaos-testing%5C%22,%20pod%3D~%5C%22kafka-standalone-222-milvus-.*%5C%22%7D%20%7C~%5C%22319e413cb4409948%7C3474b3e4be9b513b%7C445200996915794804%7C445200996915794803%5C%22%22,%22hide%22:true%7D%5D,%22range%22:%7B%22from%22:%221698669241823%22,%22to%22:%221698670135863%22%7D%7D

**Comment by xiaofan-luan** [comment]
looks like growing segment rowcount has a rac?

**Comment by yah01** [comment]
The growing index requires `IndexInfoList` in `WatchChannel` and `LoadSegments` requests, this field is introduced from v2.3, the old QueryCoord can't provide this field, so the new QueryNode crashes while trying to create growing index
