### ISSUE TITLE
[Bug]: pymilvus raise MilvusException when using concurrent.futures.ThreadPoolExecutor() and output_fields at same time

### ISSUE THREAD

**Issue by auwc** [milvus-io/milvus#28043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.0
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

This error only occur at this situation: 
1. use concurrent.futures.ThreadPoolExecutor() to execute multiple searches
2. use all fields as output_fields params to search
3. where output_fields = [x.name for x in my_collection.schema.fields]

If I skip the output_fields, only use concurrent.futures.ThreadPoolExecutor() todo multiple search, it works well.
If I don't use  concurrent.futures.ThreadPoolExecutor(), search each collections one by one, then output_fields param will not cause trouble. 

### Steps To Reproduce

```markdown
In pyMilvus 2.3.0, milvus-standalone 2.3.0

#%%
import concurrent.futures

from pymilvus import (
    connections,
    db,
    utility,
    FieldSchema, CollectionSchema, DataType,
    Collection,
)

from service.embedding import embedding_m3e


def query0(collection):
    vectors_to_search = [embedding_m3e("test search string")]
    connections.connect(host="{ip}", port=19530, db_name={database})
    my_collection = Collection(collection)
    output_fields = [x.name for x in my_collection.schema.fields]
    search_params = {
        "metric_type": "IP"
    }
    result = my_collection.search(vectors_to_search, "embedding", search_params, expr="", limit=999, 
        output_fields=output_fields)
    return result

try:
    collection_list = [{collection1}, {collection2}, {collection3}]
    with concurrent.futures.ThreadPoolExecutor() as executor:
        results = list(executor.map(lambda element: query0(element), collection_list))
except:
    import traceback
    traceback.print_exc()
```

### Milvus Log

2023-10-31 16:49:09,013 - decorators.py - line:126 - ERROR - RPC error: [search], <MilvusException: (code=1, message=legacy error code:1, reason: cannot parse expression: {id_fields} in [ {all_ids} ], error: line 1:25 mismatched input '"362602467025866752"' expecting {'(', '[', EXISTS, '+', '-', '~', NOT, JSONContains, JSONContainsAll, JSONContainsAny, BooleanConstant, IntegerConstant, FloatingConstant, Identifier, StringLiteral, JSONIdentifier})>, <Time:{'RPC start': '2023-10-31 16:49:08.753781', 'RPC error': '2023-10-31 16:49:09.013950'}> -23096
2023-10-31 16:49:09,805 - decorators.py - line:126 - ERROR - RPC error: [search], <MilvusException: (code=1, message=legacy error code:1, reason: cannot parse expression: {id_fields} in [ {all_ids} ], error: line 1:25 mismatched input '"344551092824166400"' expecting {'(', '[', EXISTS, '+', '-', '~', NOT, JSONContains, JSONContainsAll, JSONContainsAny, BooleanConstant, IntegerConstant, FloatingConstant, Identifier, StringLiteral, JSONIdentifier})>, <Time:{'RPC start': '2023-10-31 16:49:09.231543', 'RPC error': '2023-10-31 16:49:09.805408'}> -23096
2023-10-31 16:49:10,005 - decorators.py - line:126 - ERROR - RPC error: [search], <MilvusException: (code=1, message=legacy error code:1, reason: cannot parse expression: {id_fields} in [ {all_ids} ], error: line 1:25 mismatched input '"366964231351947264"' expecting {'(', '[', EXISTS, '+', '-', '~', NOT, JSONContains, JSONContainsAll, JSONContainsAny, BooleanConstant, IntegerConstant, FloatingConstant, Identifier, StringLiteral, JSONIdentifier})>, <Time:{'RPC start': '2023-10-31 16:49:09.720826', 'RPC error': '2023-10-31 16:49:10.005222'}> -23096
Traceback (most recent call last):
  File "<ipython-input-2-a03b783e2e7f>", line 36, in <cell line: 33>
    results = list(executor.map(lambda element: query0(element), collection_list))
  File "c:\Users\wangyy02\Anaconda3\envs\dac\lib\concurrent\futures\_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "c:\Users\wangyy02\Anaconda3\envs\dac\lib\concurrent\futures\_base.py", line 446, in result
    return self.__get_result()
  File "c:\Users\wangyy02\Anaconda3\envs\dac\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "c:\Users\wangyy02\Anaconda3\envs\dac\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "<ipython-input-2-a03b783e2e7f>", line 36, in <lambda>
    results = list(executor.map(lambda element: query0(element), collection_list))
  File "<ipython-input-2-a03b783e2e7f>", line 27, in query0
    result = my_collection.search(vectors_to_search, "embedding", search_params, expr="", limit=999,
  File "c:\Users\wangyy02\Anaconda3\envs\dac\lib\site-packages\pymilvus\orm\collection.py", line 778, in search
    res = conn.search(
  File "c:\Users\wangyy02\Anaconda3\envs\dac\lib\site-packages\pymilvus\decorators.py", line 127, in handler
    raise e from e
  File "c:\Users\wangyy02\Anaconda3\envs\dac\lib\site-packages\pymilvus\decorators.py", line 123, in handler
    return func(*args, **kwargs)
  File "c:\Users\wangyy02\Anaconda3\envs\dac\lib\site-packages\pymilvus\decorators.py", line 162, in handler
    return func(self, *args, **kwargs)
  File "c:\Users\wangyy02\Anaconda3\envs\dac\lib\site-packages\pymilvus\decorators.py", line 102, in handler
    raise e from e
  File "c:\Users\wangyy02\Anaconda3\envs\dac\lib\site-packages\pymilvus\decorators.py", line 68, in handler
    return func(*args, **kwargs)
  File "c:\Users\wangyy02\Anaconda3\envs\dac\lib\site-packages\pymilvus\client\grpc_handler.py", line 774, in search
    return self._execute_search_requests(
  File "c:\Users\wangyy02\Anaconda3\envs\dac\lib\site-packages\pymilvus\client\grpc_handler.py", line 735, in _execute_search_requests
    raise pre_err from pre_err
  File "c:\Users\wangyy02\Anaconda3\envs\dac\lib\site-packages\pymilvus\client\grpc_handler.py", line 726, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=legacy error code:1, reason: cannot parse expression: {id_fields} in [ {all_ids} ], error: line 1:25 mismatched input '"362602467025866752"' expecting {'(', '[', EXISTS, '+', '-', '~', NOT, JSONContains, JSONContainsAll, JSONContainsAny, BooleanConstant, IntegerConstant, FloatingConstant, Identifier, StringLiteral, JSONIdentifier})>

**Comment by xiaocai2333** [comment]
@auwc this is a known bug on v2.3.0. If you need concurrent search, it is recommended to use version 2.3.1 or later.
pr #26721 fixed it.
/assign @auwc 
/unassign

**Comment by auwc** [comment]
> @auwc this is a known bug on v2.3.0. If you need concurrent search, it is recommended to use version 2.3.1 or later. pr #26721 fixed it. /assign @auwc /unassign

I see. Thank you!
