### ISSUE TITLE
[Bug]: SIGSEGV when run standalone 

### ISSUE THREAD

**Issue by KumaJie** [milvus-io/milvus#28065]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master v2.2-testing-20230824-491-g8ae9c947a-dev
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I want to run Milvus standalone. step like:
```bash
cd deployments/docker/dev
docker-compose up -d
cd ../../../
./scripts/start_standalone.sh 
```

### Milvus Log

```
SIGSEGV: segmentation violation
PC=0x7f039e31934a m=7 sigcode=1
signal arrived during cgo execution

goroutine 1622 [syscall]:
_ZN8knowhere12IvfIndexNodeIN5faiss12IndexIVFFlatEE11DeserializeERKNS_9BinarySetERKNS_6ConfigE
	/home/kuma/t/milvus/cmake_build/thirdparty/knowhere/knowhere-src/src/index/ivf/ivf.cc:756 pc=0x7f039e31934a
_ZN8knowhere5IndexINS_9IndexNodeEE11DeserializeERKNS_9BinarySetERKN8nlohmann16json_abi_v3_11_210basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS7_14adl_serializerESA_IhSaIhEEEE
	/home/kuma/t/milvus/cmake_build/thirdparty/knowhere/knowhere-src/src/common/index.cc:200 pc=0x7f039e2c9ace
_ZN6milvus5index14VectorMemIndex19LoadWithoutAssembleERKN8knowhere9BinarySetERKN8nlohmann16json_abi_v3_11_210basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS7_14adl_serializerESA_IhSaIhEEEE
	/home/kuma/t/milvus/internal/core/src/index/VectorMemIndex.cpp:97 pc=0x7f039ec6580f
_ZN6milvus5index14VectorMemIndex4LoadERKN8nlohmann16json_abi_v3_11_210basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS3_14adl_serializerES6_IhSaIhEEEE
	/home/kuma/t/milvus/internal/core/src/index/VectorMemIndex.cpp:217 pc=0x7f039ec6f0c7
runtime.cgocall(0x3d079c0, 0xc000fbceb0)
	/home/kuma/go/src/runtime/cgocall.go:157 +0x4b fp=0xc000fbce88 sp=0xc000fbce50 pc=0x178416b
github.com/milvus-io/milvus/internal/querynodev2/segments._Cfunc_AppendIndexV2(0x7f034be033c0)
	_cgo_gotypes.go:227 +0x50 fp=0xc000fbceb0 sp=0xc000fbce88 pc=0x3afead0
github.com/milvus-io/milvus/internal/querynodev2/segments.(*LoadIndexInfo).appendIndexData.func1(0x0?)
	/home/kuma/t/milvus/internal/querynodev2/segments/load_index_info.go:157 +0x34 fp=0xc000fbcee8 sp=0xc000fbceb0 pc=0x3b04674
github.com/milvus-io/milvus/internal/querynodev2/segments.(*LoadIndexInfo).appendIndexData(0xc000fbd020?, {0xc0020de970?, 0x1, 0xc002013063?})
	/home/kuma/t/milvus/internal/querynodev2/segments/load_index_info.go:157 +0x70 fp=0xc000fbcf38 sp=0xc000fbcee8 pc=0x3b045d0
github.com/milvus-io/milvus/internal/querynodev2/segments.(*LoadIndexInfo).appendLoadIndexInfo(0xc000fbd258?, 0xc0023a2280, 0x43?, 0x24e?, 0x54fe5d0?, 0x135?)
	/home/kuma/t/milvus/internal/querynodev2/segments/load_index_info.go:99 +0x538 fp=0xc000fbd1a0 sp=0xc000fbcf38 pc=0x3b03ab8
github.com/milvus-io/milvus/internal/querynodev2/segments.(*LocalSegment).LoadIndex(0xc0020da240, 0xc0023a2280, 0x65?)
	/home/kuma/t/milvus/internal/querynodev2/segments/segment.go:844 +0xa7 fp=0xc000fbd2f8 sp=0xc000fbd1a0 pc=0x3b127c7
github.com/milvus-io/milvus/internal/querynodev2/segments.(*segmentLoader).loadFieldIndex(0xc000c92e00?, {0x24e?, 0x54fe5d0?}, 0xc0020da240, 0xc0023a2280)
	/home/kuma/t/milvus/internal/querynodev2/segments/segment_loader.go:727 +0x20d fp=0xc000fbd380 sp=0xc000fbd2f8 pc=0x3b1c22d
github.com/milvus-io/milvus/internal/querynodev2/segments.(*segmentLoader).loadFieldsIndex(0xc0020aaa80?, {0x4acbec8, 0xc0021d8450}, 0xc001cd1140?, 0xc0020da240, 0x1?, 0xc0020de3c0?)
	/home/kuma/t/milvus/internal/querynodev2/segments/segment_loader.go:680 +0xea fp=0xc000fbd5d0 sp=0xc000fbd380 pc=0x3b1bb0a
github.com/milvus-io/milvus/internal/querynodev2/segments.(*segmentLoader).loadSegment(0xc0010820c0, {0x4acbec8, 0xc0021d8450}, 0xc0020da240, 0xc000119600)
	/home/kuma/t/milvus/internal/querynodev2/segments/segment_loader.go:593 +0xfb7 fp=0xc000fbdb90 sp=0xc000fbd5d0 pc=0x3b1af17
github.com/milvus-io/milvus/internal/querynodev2/segments.(*segmentLoader).Load.func4(0x4ab6660?)
	/home/kuma/t/milvus/internal/querynodev2/segments/segment_loader.go:247 +0xed fp=0xc000fbddc0 sp=0xc000fbdb90 pc=0x3b1598d
github.com/milvus-io/milvus/pkg/util/funcutil.ProcessFuncParallel.func3(0x0)
	/home/kuma/t/milvus/pkg/util/funcutil/parallel.go:86 +0x151 fp=0xc000fbdfc8 sp=0xc000fbddc0 pc=0x2436d31
github.com/milvus-io/milvus/pkg/util/funcutil.ProcessFuncParallel.func4()
	/home/kuma/t/milvus/pkg/util/funcutil/parallel.go:104 +0x27 fp=0xc000fbdfe0 sp=0xc000fbdfc8 pc=0x2436ba7
runtime.goexit()
	/home/kuma/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000fbdfe8 sp=0xc000fbdfe0 pc=0x17f3ba1
created by github.com/milvus-io/milvus/pkg/util/funcutil.ProcessFuncParallel in goroutine 1502
	/home/kuma/t/milvus/pkg/util/funcutil/parallel.go:73 +0x1b4

goroutine 1 [chan receive]:
runtime.gopark(0x4002f20?, 0xc0011a21b0?, 0x60?, 0xc9?, 0x11?)
	/home/kuma/go/src/runtime/proc.go:398 +0xce fp=0xc002597690 sp=0xc002597670 pc=0x17be4ce
runtime.chanrecv(0xc000df6840, 0x0, 0x1)
	/home/kuma/go/src/runtime/chan.go:583 +0x3cd fp=0xc002597708 sp=0xc002597690 pc=0x17865cd
runtime.chanrecv1(0xc000f7eef0?, 0x4acbf00?)
	/home/kuma/go/src/runtime/chan.go:442 +0x12 fp=0xc002597730 sp=0xc002597708 pc=0x17861d2
github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run(0xc0001e4a40)
	/home/kuma/t/milvus/cmd/roles/roles.go:389 +0x98c fp=0xc002597bb0 sp=0xc002597730 pc=0x3c1548c
github.com/milvus-io/milvus/cmd/milvus.(*run).execute(0x68cc580?, {0xc0000527e0?, 0x3, 0x3}, 0xc00105dc70)
	/home/kuma/t/milvus/cmd/milvus/run.go:44 +0x289 fp=0xc002597c80 sp=0xc002597bb0 pc=0x3c20169
github.com/milvus-io/milvus/cmd/milvus.RunMilvus({0xc0000527e0?, 0x3, 0x3})
	/home/kuma/t/milvus/cmd/milvus/milvus.go:60 +0x204 fp=0xc002597cf8 sp=0xc002597c80 pc=0x3c1fe44
main.main()
	/home/kuma/t/milvus/cmd/main.go:95 +0x405 fp=0xc002597f40 sp=0xc002597cf8 pc=0x3c24845
runtime.main()
	/home/kuma/go/src/runtime/proc.go:267 +0x2bb fp=0xc002597fe0 sp=0xc002597f40 pc=0x17be05b
runtime.goexit()
	/home/kuma/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc002597fe8 sp=0xc002597fe0 pc=0x17f3ba1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/home/kuma/go/src/runtime/proc.go:398 +0xce fp=0xc000086fa8 sp=0xc000086f88 pc=0x17be4ce
runtime.goparkunlock(...)
	/home/kuma/go/src/runtime/proc.go:404
runtime.forcegchelper()
	/home/kuma/go/src/runtime/proc.go:322 +0xb3 fp=0xc000086fe0 sp=0xc000086fa8 pc=0x17be333
runtime.goexit()
	/home/kuma/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000086fe8 sp=0xc000086fe0 pc=0x17f3ba1
created by runtime.init.6 in goroutine 1
	/home/kuma/go/src/runtime/proc.go:310 +0x1a
```

**Comment by xiaofan-luan** [comment]
seems to be very similar as https://github.com/milvus-io/milvus/pull/28034

**Comment by xiaofan-luan** [comment]
is this during upgrade? 
wes should be able to fix it on 2.3.3

**Comment by yanliang567** [comment]
@KumaJie sounds like you are running on a test build? could you please retry with milvus v2.3.2?
/assign @KumaJie 
/unassign

**Comment by KumaJie** [comment]
I used master branch code to build.
I will try milvus v2.3.2, thanks.

**Comment by xiaofan-luan** [comment]
> I used master branch code to build. I will try milvus v2.3.2, thanks.

I think 2.3.2 could mostly have the same issue. it this reproduce forever?

**Comment by KumaJie** [comment]
> > I used master branch code to build. I will try milvus v2.3.2, thanks.
> 
> I think 2.3.2 could mostly have the same issue. it this reproduce forever?

yes, I meet same problem in the 2.3.2. 
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7fd9548119ed]

runtime stack:
runtime.throw({0x467e8a0?, 0x7fd8e95e0248?})
	/usr/local/go/src/runtime/panic.go:992 +0x71 fp=0x7fd8e95dfdd0 sp=0x7fd8e95dfda0 pc=0x179f7b1
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:802 +0x389 fp=0x7fd8e95dfe20 sp=0x7fd8e95dfdd0 pc=0x17b65a9

goroutine 1580 [syscall]:
_ZN8knowhere12IvfIndexNodeIN5faiss12IndexIVFFlatEE11DeserializeERKNS_9BinarySetERKNS_6ConfigE
	/home/kuma/milvus/cmake_build/thirdparty/knowhere/knowhere-src/src/index/ivf/ivf.cc:756 pc=0x7fd9548119ed
_ZN8knowhere5IndexINS_9IndexNodeEE11DeserializeERKNS_9BinarySetERKN8nlohmann16json_abi_v3_11_210basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS7_14adl_serializerESA_IhSaIhEEEE
	/home/kuma/milvus/cmake_build/thirdparty/knowhere/knowhere-src/src/common/index.cc:200 pc=0x7fd9547ca63e
_ZN6milvus5index14VectorMemIndex19LoadWithoutAssembleERKN8knowhere9BinarySetERKN8nlohmann16json_abi_v3_11_210basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS7_14adl_serializerESA_IhSaIhEEEE
	/home/kuma/milvus/internal/core/src/index/VectorMemIndex.cpp:97 pc=0x7fd955162e9f
_ZN6milvus5index14VectorMemIndex4LoadERKN8nlohmann16json_abi_v3_11_210basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS3_14adl_serializerES6_IhSaIhEEEE
	/home/kuma/milvus/internal/core/src/index/VectorMemIndex.cpp:217 pc=0x7fd95516912c
runtime.cgocall(0x3d7bd60, 0xc0026a2ea8)
	/usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc0026a2e80 sp=0xc0026a2e48 pc=0x176873c
github.com/milvus-io/milvus/internal/querynodev2/segments._Cfunc_AppendIndexV2(0x7fd8e42ccd40)
	_cgo_gotypes.go:229 +0x51 fp=0xc0026a2ea8 sp=0xc0026a2e80 pc=0x3b659d1
github.com/milvus-io/milvus/internal/querynodev2/segments.(*LoadIndexInfo).appendIndexData.func1(0x0?)
	/home/kuma/milvus/internal/querynodev2/segments/load_index_info.go:157 +0x3a fp=0xc0026a2ee0 sp=0xc0026a2ea8 pc=0x3b6be1a
github.com/milvus-io/milvus/internal/querynodev2/segments.(*LoadIndexInfo).appendIndexData(0xc0026a3018?, {0xc0026d0200?, 0x1?, 0xc0026b23f3?})
	/home/kuma/milvus/internal/querynodev2/segments/load_index_info.go:157 +0x38 fp=0xc0026a2f30 sp=0xc0026a2ee0 pc=0x3b6bd18
github.com/milvus-io/milvus/internal/querynodev2/segments.(*LoadIndexInfo).appendLoadIndexInfo(0x2?, 0xc001801cc0, 0x203000?, 0x203000?, 0xc001b401a0?, 0x203000?)
	/home/kuma/milvus/internal/querynodev2/segments/load_index_info.go:99 +0x554 fp=0xc0026a3198 sp=0xc0026a2f30 pc=0x3b6aff4
github.com/milvus-io/milvus/internal/querynodev2/segments.(*LocalSegment).LoadIndex(0xc0026bd3b0, 0xc001801cc0, 0x65?)
	/home/kuma/milvus/internal/querynodev2/segments/segment.go:822 +0xb8 fp=0xc0026a32f0 sp=0xc0026a3198 pc=0x3b7ad78
github.com/milvus-io/milvus/internal/querynodev2/segments.(*segmentLoader).loadFieldIndex(0xc000ecf960?, {0x24b?, 0x5360dce?}, 0xc0026bd3b0, 0xc001801cc0)
	/home/kuma/milvus/internal/querynodev2/segments/segment_loader.go:724 +0xf2 fp=0xc0026a3380 sp=0xc0026a32f0 pc=0x3b84552
github.com/milvus-io/milvus/internal/querynodev2/segments.(*segmentLoader).loadFieldsIndex(0xc0026b2e68?, {0x4b94358, 0xc0026c6360}, 0xc0026afdc0?, 0xc0026bd3b0, 0x1?, 0x203000?)
	/home/kuma/milvus/internal/querynodev2/segments/segment_loader.go:677 +0xf4 fp=0xc0026a35d0 sp=0xc0026a3380 pc=0x3b83f14
github.com/milvus-io/milvus/internal/querynodev2/segments.(*segmentLoader).loadSegment(0xc00051bb00, {0x4b94358, 0xc0026c6360}, 0xc0026bd3b0, 0xc00117ee00)
	/home/kuma/milvus/internal/querynodev2/segments/segment_loader.go:590 +0x101f fp=0xc0026a3b90 sp=0xc0026a35d0 pc=0x3b8329f
github.com/milvus-io/milvus/internal/querynodev2/segments.(*segmentLoader).Load.func4(0xc0026a81d0?)
	/home/kuma/milvus/internal/querynodev2/segments/segment_loader.go:247 +0xf1 fp=0xc0026a3dc0 sp=0xc0026a3b90 pc=0x3b7e0b1
github.com/milvus-io/milvus/pkg/util/funcutil.ProcessFuncParallel.func3(0x0)
	/home/kuma/milvus/pkg/util/funcutil/parallel.go:86 +0x16d fp=0xc0026a3fc8 sp=0xc0026a3dc0 pc=0x24688cd
github.com/milvus-io/milvus/pkg/util/funcutil.ProcessFuncParallel.func4()
	/home/kuma/milvus/pkg/util/funcutil/parallel.go:104 +0x2a fp=0xc0026a3fe0 sp=0xc0026a3fc8 pc=0x246872a
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0026a3fe8 sp=0xc0026a3fe0 pc=0x17d50c1
created by github.com/milvus-io/milvus/pkg/util/funcutil.ProcessFuncParallel
	/home/kuma/milvus/pkg/util/funcutil/parallel.go:73 +0x1aa
```

**Comment by xiaofan-luan** [comment]
@KumaJie 
what is the verison of your existing data?

**Comment by xiaofan-luan** [comment]
I'm seeing you are loading IVFFLAT index and failed. what is the current version before you upgrade?

**Comment by xiaofan-luan** [comment]
if would be helpful if you can offer your index files @KumaJie

**Comment by liliu-z** [comment]
Yes index files, raw data + reproducing instruction, either one can help. Thanks!

**Comment by KumaJie** [comment]
Hi. I don't save any data in the milvus. I rebuild source code in a new wsl2 machine and it still wrong. 
But it work when I clean the docker volume dir and restart deployments environment, everything(2.3.2 or master) is ok.
So, I think this situation not a milvus bug😂.

**Comment by KumaJie** [comment]
I test some new feature about insert data recently and frequent change version.  I guess it may be cause some conflict. Thanks😊.

**Comment by liliu-z** [comment]
Hi @KumaJie Good to know that this get solved!
Appreciate it if you can help provide an instruction to reproduce this, so we can check if there is any risky points.
