### ISSUE TITLE
[Bug]: Standalone panic: fail to init rocksmq when upgrade milvus image from v2.3.2 to master-latest

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#28067]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.3.2 -> master-20231101-1d7a2035
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. deploy milvus standalone with image v2.3.2 with config by milvus-operator
```
    standalone:
      paused: false
      replicas: 1
      resources:
        limits:
          cpu: "2" 
          memory: 6Gi 
        requests:
          cpu: 100m
          memory: 128Mi
      serviceType: ClusterIP
  config:
    log:
      level: debug
```

2. Edit milvus and upgrade image to master-20231101-1d7a2035. The standalone pod crashes with log:
[standalone_pre.log](https://github.com/milvus-io/milvus/files/13224419/standalone_pre.log)

```
[2023/11/01 07:12:39.883 +00:00] [DEBUG] [indexnode/task_scheduler.go:242] ["IndexNode TaskScheduler start build loop ..."]
[2023/11/01 07:12:39.884 +00:00] [INFO] [sessionutil/session_util.go:450] ["put session key into etcd"] [key=standalone-memory/meta/session/indexnode-10] [value="{\"ServerID\":10,\"ServerName\":\"indexnode\",\"Address\":\"10.102.10.108:21121\",\"TriggerKill\":true,\"Version\":\"2.3.2\",\"IndexEngineVersion\":{},\"LeaseID\":2832636114115150581,\"HostName\":\"standalone-memory-milvus-standalone-588669b767-rmflr\",\"EnableDisk\":true}"]
[2023/11/01 07:12:39.884 +00:00] [INFO] [sessionutil/session_util.go:460] ["Service registered successfully"] [ServerName=indexnode] [serverID=10]
[2023/11/01 07:12:39.886 +00:00] [DEBUG] [indexnode/service.go:206] ["IndexNode Register etcd success"]
[2023/11/01 07:12:39.886 +00:00] [DEBUG] [indexnode/service.go:78] ["IndexNode start done ..."]
[2023/11/01 07:12:39.886 +00:00] [DEBUG] [components/index_node.go:55] ["IndexNode successfully started"]
[2023/11/01 07:12:39.893 +00:00] [FATAL] [msgstream/mq_factory.go:16] ["fail to init rocksmq"] [error="Invalid argument: Column families not opened: properties"] [stack="github.com/milvus-io/milvus/internal/mq/msgstream.NewRocksmqFactory\n\t/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_factory.go:16\ngithub.com/milvus-io/milvus/internal/util/dependency.(*DefaultFactory).initMQ\n\t/go/src/github.com/milvus-io/milvus/internal/util/dependency/factory.go:90\ngithub.com/milvus-io/milvus/internal/util/dependency.(*DefaultFactory).Init\n\t/go/src/github.com/milvus-io/milvus/internal/util/dependency/factory.go:77\ngithub.com/milvus-io/milvus/internal/datacoord.(*Server).Init\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/server.go:303\ngithub.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:126\ngithub.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:249\ngithub.com/milvus-io/milvus/cmd/components.(*DataCoord).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/data_coord.go:50\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:114"]
panic: fail to init rocksmq

goroutine 340 [running]:
panic({0x403d080, 0xc0010eb790})
    /usr/local/go/src/runtime/panic.go:987 +0x3bb fp=0xc000443690 sp=0xc0004435d0 pc=0x1785c1b
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0011443c0, {0xc0005b3e40, 0x1, 0x1})
    /go/pkg/mod/go.uber.org/zap@v1.20.0/zapcore/entry.go:232 +0x44c fp=0xc000443838 sp=0xc000443690 pc=0x198102c
go.uber.org/zap.(*Logger).Fatal(0xc0000ce800?, {0x46e55ca?, 0x0?}, {0xc0005b3e40, 0x1, 0x1})
    /go/pkg/mod/go.uber.org/zap@v1.20.0/logger.go:241 +0x59 fp=0xc000443868 sp=0xc000443838 pc=0x1bd1f39
github.com/milvus-io/milvus/pkg/log.Fatal({0x46e55ca?, 0x2498ed7?}, {0xc0005b3e40?, 0xc0000632e0?, 0xb?})
    /go/src/github.com/milvus-io/milvus/pkg/log/global.go:65 +0x8b fp=0xc0004438b8 sp=0xc000443868 pc=0x1d669ab
github.com/milvus-io/milvus/internal/mq/msgstream.NewRocksmqFactory({0xc00126c2b8, 0x18}, 0x673f0a0)
    /go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_factory.go:16 +0x14b fp=0xc0004439d0 sp=0xc0004438b8 pc=0x34d2feb
github.com/milvus-io/milvus/internal/util/dependency.(*DefaultFactory).initMQ(0xc00044c7b0, 0x1, 0x673f0a0)
    /go/src/github.com/milvus-io/milvus/internal/util/dependency/factory.go:90 +0x3f9 fp=0xc000443ad0 sp=0xc0004439d0 pc=0x34d3639
github.com/milvus-io/milvus/internal/util/dependency.(*DefaultFactory).Init(0xc00044c7b0, 0x4bc9388?)
    /go/src/github.com/milvus-io/milvus/internal/util/dependency/factory.go:77 +0x7c fp=0xc000443b00 sp=0xc000443ad0 pc=0x34d31fc
github.com/milvus-io/milvus/internal/datacoord.(*Server).Init(0xc000400c00)
    /go/src/github.com/milvus-io/milvus/internal/datacoord/server.go:303 +0x3b fp=0xc000443b38 sp=0xc000443b00 pc=0x353e67b
github.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).init(0xc00046c4e0)
    /go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:126 +0x6c2 fp=0xc000443e48 sp=0xc000443b38 pc=0x356d7e2
github.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).Run(0xc000252550?)
    /go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:249 +0x25 fp=0xc000443e88 sp=0xc000443e48 pc=0x356efc5
github.com/milvus-io/milvus/cmd/components.(*DataCoord).Run(0xc00005f140?)
    /go/src/github.com/milvus-io/milvus/cmd/components/data_coord.go:50 +0x2f fp=0xc000443f58 sp=0xc000443e88 pc=0x3d4512f
github.com/milvus-io/milvus/cmd/roles.runComponent[...].func1()
    /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:114 +0x15a fp=0xc000443fe0 sp=0xc000443f58 pc=0x3d4ba3a
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000443fe8 sp=0xc000443fe0 pc=0x17bf9a1
created by github.com/milvus-io/milvus/cmd/roles.runComponent[...]
    /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:101 +0x158
```

**Comment by xiaofan-luan** [comment]
I'll handle it

**Comment by xiaofan-luan** [comment]
revert #28000

**Comment by xiaofan-luan** [comment]
/assign @ThreadDao 
please verify latest master

**Comment by ThreadDao** [comment]
@xiaofan-luan Nice! Upgraded to master-20231102-d39ffba5-amd64 successfully
