### ISSUE TITLE
[Bug]: [Nightly]Delete failed when expression containing array field

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#28180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: bf2f62c
- Deployment mode(standalone or cluster): cluster && standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Delete failed when expression containing array field.
```
[2023-11-05T20:20:37.063Z] [2023-11-05 18:12:16 - ERROR - pymilvus.decorators]: RPC error: [delete], <MilvusException: (code=65538, message=attempt #0: failed to search/query delegator 3 for channel by-dev-rootcoord-dml_11_445437003227889890v0: UnknownError: Assert "index >= 0 && index < length_" at /go/src/github.com/milvus-io/milvus/internal/core/src/common/Array.h:444
[2023-11-05T20:20:37.063Z]  => index out of range, index=1, length=0: attempt #1: no available shard delegator found: service unavailable)>, <Time:{'RPC start': '2023-11-05 18:12:15.672535', 'RPC error': '2023-11-05 18:12:16.281866'}> (decorators.py:128)
[2023-11-05T20:20:37.063Z] [2023-11-05 18:12:16 - ERROR - ci_test]: Traceback (most recent call last):
[2023-11-05T20:20:37.063Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper
[2023-11-05T20:20:37.063Z]     res = func(*args, **_kwargs)
[2023-11-05T20:20:37.063Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request
[2023-11-05T20:20:37.063Z]     return func(*arg, **kwargs)
[2023-11-05T20:20:37.063Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 564, in delete
[2023-11-05T20:20:37.063Z]     res = conn.delete(self._name, expr, partition_name, timeout=timeout, **kwargs)
[2023-11-05T20:20:37.063Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 129, in handler
[2023-11-05T20:20:37.063Z]     raise e from e
[2023-11-05T20:20:37.063Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 125, in handler
[2023-11-05T20:20:37.063Z]     return func(*args, **kwargs)
[2023-11-05T20:20:37.063Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 164, in handler
[2023-11-05T20:20:37.063Z]     return func(self, *args, **kwargs)
[2023-11-05T20:20:37.063Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 104, in handler
[2023-11-05T20:20:37.063Z]     raise e from e
[2023-11-05T20:20:37.063Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 68, in handler
[2023-11-05T20:20:37.063Z]     return func(*args, **kwargs)
[2023-11-05T20:20:37.063Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 612, in delete
[2023-11-05T20:20:37.063Z]     raise err from err
[2023-11-05T20:20:37.063Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 606, in delete
[2023-11-05T20:20:37.063Z]     raise MilvusException(
[2023-11-05T20:20:37.063Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=65538, message=attempt #0: failed to search/query delegator 3 for channel by-dev-rootcoord-dml_11_445437003227889890v0: UnknownError: Assert "index >= 0 && index < length_" at /go/src/github.com/milvus-io/milvus/internal/core/src/common/Array.h:444
[2023-11-05T20:20:37.063Z]  => index out of range, index=1, length=0: attempt #1: no available shard delegator found: service unavailable)>
[2023-11-05T20:20:37.063Z]  (api_request.py:45)
[2023-11-05T20:20:37.063Z] [2023-11-05 18:12:16 - ERROR - ci_test]: (api_response) : <MilvusException: (code=65538, message=attempt #0: failed to search/query delegator 3 for channel by-dev-rootcoord-dml_11_445437003227889890v0: UnknownError: Assert "index >= 0 && index < length_" at /go/src/github.com/milvus-io/milvus/internal/core/src/common/Array.h:444
[2023-11-05T20:20:37.063Z]  => index out of range, ind...... (api_request.py:46)
```

### Expected Behavior

delete successfully

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/550/pipeline/205/
2. log: [artifacts-milvus-distributed-kafka-nightly-550-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/550/artifact/artifacts-milvus-distributed-kafka-nightly-550-pymilvus-e2e-logs.tar.gz)
3. collection name: coll__GfyRjD9O
4. failed time: [2023-11-05T18:12:16.621Z] [gw0] [ 10%] FAILED testcases/test_delete.py::TestDeleteComplexExpr::test_delete_array_expressions[False-int32_array[1] not in [1, 2, 3]] 
5. all failed cases: 
```
[2023-11-05T20:20:37.547Z] FAILED testcases/test_delete.py::TestDeleteComplexExpr::test_delete_array_expressions[False-int32_array[1] not in [1, 2, 3]] - AssertionError
[2023-11-05T20:20:37.547Z] FAILED testcases/test_delete.py::TestDeleteComplexExpr::test_delete_array_expressions[True-int32_array[0] > 0] - AssertionError
[2023-11-05T20:20:37.547Z] FAILED testcases/test_delete.py::TestDeleteComplexExpr::test_delete_array_expressions[True-int32_array[1] % 100 == 0 && string_array[1] in ['1', '2']] - AssertionError
[2023-11-05T20:20:37.547Z] FAILED testcases/test_delete.py::TestDeleteComplexExpr::test_delete_array_expressions[True-int32_array[1] in [1, 2, 3] and string_array[1] != '2'] - AssertionError
[2023-11-05T20:20:37.547Z] FAILED testcases/test_delete.py::TestDeleteComplexExpr::test_delete_array_expressions[False-0 <= int32_array[0] < 400 or 1000 > float_array[1] >= 500] - AssertionError
[2023-11-05T20:20:37.547Z] FAILED testcases/test_delete.py::TestDeleteComplexExpr::test_delete_array_expressions[False-int32_array[1] in [300/2, -10*30+800, (200-100)*2] or (float_array[1] <= -4**5/2 || 100 <= int32_array[1] < 200)] - AssertionError
[2023-11-05T20:20:37.547Z] FAILED testcases/test_delete.py::TestDeleteComplexExpr::test_delete_array_expressions[True-int32_array[1] not in [1, 2, 3]] - AssertionError
[2023-11-05T20:20:37.547Z] FAILED testcases/test_delete.py::TestDeleteComplexExpr::test_delete_array_expressions[False-int32_array[0] > 0] - AssertionError
[2023-11-05T20:20:37.547Z] FAILED testcases/test_delete.py::TestDeleteComplexExpr::test_delete_array_expressions[False-int32_array[1] % 100 == 0 && string_array[1] in ['1', '2']] - AssertionError
[2023-11-05T20:20:37.547Z] FAILED testcases/test_delete.py::TestDeleteComplexExpr::test_delete_array_expressions[True-int32_array[1] + 1 == 3 && int32_array[0] - 1 != 1] - AssertionError
[2023-11-05T20:20:37.547Z] FAILED testcases/test_delete.py::TestDeleteComplexExpr::test_delete_array_expressions[False-int32_array[1] in [1, 2, 3] and string_array[1] != '2'] - AssertionError
[2023-11-05T20:20:37.547Z] FAILED testcases/test_delete.py::TestDeleteComplexExpr::test_delete_array_expressions[True-0 <= int32_array[0] < 400 or 1000 > float_array[1] >= 500] - AssertionError
[2023-11-05T20:20:37.547Z] FAILED testcases/test_delete.py::TestDeleteComplexExpr::test_delete_array_expressions[True-int32_array[1] in [300/2, -10*30+800, (200-100)*2] or (float_array[1] <= -4**5/2 || 100 <= int32_array[1] < 200)] - AssertionError
[2023-11-05T20:20:37.547Z] FAILED testcases/test_delete.py::TestDeleteComplexExpr::test_delete_array_expressions[False-int32_array[1] + 1 == 3 && int32_array[0] - 1 != 1] - AssertionError
```

**Comment by xiaocai2333** [comment]
fixed, please verify it.
/assign @NicoYuan1986

**Comment by NicoYuan1986** [comment]
fixed. master-20231108-7dda2e88
