### ISSUE TITLE
[Bug]: Flush timeout after standalone reinstallation

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#28269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3-20231108-cc3dd6ed
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):kafka    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```

[2023-11-08T04:02:38.987Z] [2023-11-08 04:02:37 - ERROR - pymilvus.decorators]: RPC error: [flush], <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for flush timeout, collection: IndexChecker__vuFlSm4b)>, <Time:{'RPC start': '2023-11-08 03:59:37.054698', 'RPC error': '2023-11-08 04:02:37.386239'}> (decorators.py:128)

[2023-11-08T04:02:38.987Z] [2023-11-08 04:02:37 - ERROR - ci_test]: Traceback (most recent call last):

[2023-11-08T04:02:38.987Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2023-11-08T04:02:38.987Z]     res = func(*args, **_kwargs)

[2023-11-08T04:02:38.987Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2023-11-08T04:02:38.987Z]     return func(*arg, **kwargs)

[2023-11-08T04:02:38.987Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 315, in flush

[2023-11-08T04:02:38.987Z]     conn.flush([self.name], timeout=timeout, **kwargs)

[2023-11-08T04:02:38.987Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 129, in handler

[2023-11-08T04:02:38.987Z]     raise e from e

[2023-11-08T04:02:38.987Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 125, in handler

[2023-11-08T04:02:38.987Z]     return func(*args, **kwargs)

[2023-11-08T04:02:38.987Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 164, in handler

[2023-11-08T04:02:38.987Z]     return func(self, *args, **kwargs)

[2023-11-08T04:02:38.987Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 95, in handler

[2023-11-08T04:02:38.987Z]     raise MilvusException(

[2023-11-08T04:02:38.987Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for flush timeout, collection: IndexChecker__vuFlSm4b)>

[2023-11-08T04:02:38.987Z]  (api_request.py:45)

[2023-11-08T04:02:38.987Z] [2023-11-08 04:02:37 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for flush timeout, collection: IndexChecker__vuFlSm4b)> (api_request.py:46)

[2023-11-08T04:02:38.987Z] ------------- generated html file: file:///tmp/ci_logs/report.html -------------

[2023-11-08T04:02:38.987Z] =========================== short test summary info ============================

[2023-11-08T04:02:38.987Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[Checker__Oy5jjhp1] - AssertionError

[2023-11-08T04:02:38.987Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[Checker__7azSXTWU] - AssertionError

[2023-11-08T04:02:38.987Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[Checker__xitBak8U] - AssertionError

[2023-11-08T04:02:38.987Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[Checker__uj1pZOax] - AssertionError

[2023-11-08T04:02:38.987Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[Checker__YtFnjiLt] - AssertionError

[2023-11-08T04:02:38.987Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[InsertChecker__rzweH28Y] - AssertionError

[2023-11-08T04:02:38.987Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[DropChecker__9Qlq2TWF] - AssertionError

[2023-11-08T04:02:38.987Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[SearchChecker__5F7zt2eJ] - AssertionError

[2023-11-08T04:02:38.987Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[CreateChecker__rQEvgPGd] - AssertionError

[2023-11-08T04:02:38.987Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[QueryChecker__6W2EKzgS] - AssertionError

[2023-11-08T04:02:38.987Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[FlushChecker__2MFGA4MY] - AssertionError

[2023-11-08T04:02:38.987Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[IndexChecker__vuFlSm4b] - AssertionError
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_kafka_for_release_cron/detail/deploy_test_kafka_for_release_cron/1526/pipeline

log:
[artifacts-kafka-standalone-reinstall-1526-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/13293008/artifacts-kafka-standalone-reinstall-1526-pytest-logs.tar.gz)
[artifacts-kafka-standalone-reinstall-1526-server-first-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/13293009/artifacts-kafka-standalone-reinstall-1526-server-first-deployment-logs.tar.gz)
[artifacts-kafka-standalone-reinstall-1526-server-second-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/13293011/artifacts-kafka-standalone-reinstall-1526-server-second-deployment-logs.tar.gz)

**Comment by zhuwenxing** [comment]
And it seems stuck at the insert
![image](https://github.com/milvus-io/milvus/assets/12268675/07ca6ac4-1e24-4afc-9db5-ab9eea635a4d)
