### ISSUE TITLE
[Bug]: Flush timeout after etcd pod failure chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#28266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3-20231108-cc3dd6ed-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):kafka    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```

[2023-11-08T05:40:41.169Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[FlushChecker__NVEUZylL] - AssertionError

[2023-11-08T05:40:41.169Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[SearchChecker__lHe4iMEd] - AssertionError

[2023-11-08T05:40:41.169Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[CreateChecker__SoeqRNfJ] - AssertionError

[2023-11-08T05:40:41.169Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[DropChecker__jXWjcN0Q] - AssertionError

[2023-11-08T05:40:41.169Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[Checker__zMxs95GH] - AssertionError

[2023-11-08T05:40:41.169Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[Checker__jWhu2VLs] - AssertionError

[2023-11-08T05:40:41.169Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[Checker__lY6vrHku] - AssertionError

[2023-11-08T05:40:41.169Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[Checker__dy0S3N6A] - AssertionError

[2023-11-08T05:40:41.169Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[Checker__lZEKiuMy] - AssertionError

[2023-11-08T05:40:41.169Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[InsertChecker__KRwd82RG] - AssertionError

[2023-11-08T05:40:41.169Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[DeleteChecker__6X4csttN] - AssertionError

[2023-11-08T05:40:41.169Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[QueryChecker__0tzZ2bhl] - AssertionError

[2023-11-08T05:40:41.169Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[IndexChecker__x4o87fYq] - AssertionError
```

```

[2023-11-08T05:40:41.160Z] <name>: FlushChecker__NVEUZylL

[2023-11-08T05:40:41.160Z] <description>: 

[2023-11-08T05:40:41.160Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT:......  (api_request.py:37)

[2023-11-08T05:40:41.160Z] [2023-11-08 05:28:29 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2023-11-08T05:40:41.160Z] [2023-11-08 05:31:30 - WARNING - pymilvus.decorators]: Retry timeout: 180s (decorators.py:94)

[2023-11-08T05:40:41.160Z] [2023-11-08 05:31:30 - ERROR - pymilvus.decorators]: RPC error: [flush], <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for flush timeout, collection: FlushChecker__NVEUZylL)>, <Time:{'RPC start': '2023-11-08 05:28:29.890164', 'RPC error': '2023-11-08 05:31:30.192498'}> (decorators.py:128)

[2023-11-08T05:40:41.160Z] [2023-11-08 05:31:30 - ERROR - ci_test]: Traceback (most recent call last):

[2023-11-08T05:40:41.160Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2023-11-08T05:40:41.160Z]     res = func(*args, **_kwargs)

[2023-11-08T05:40:41.160Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2023-11-08T05:40:41.160Z]     return func(*arg, **kwargs)

[2023-11-08T05:40:41.160Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 315, in flush

[2023-11-08T05:40:41.160Z]     conn.flush([self.name], timeout=timeout, **kwargs)

[2023-11-08T05:40:41.160Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 129, in handler

[2023-11-08T05:40:41.160Z]     raise e from e

[2023-11-08T05:40:41.160Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 125, in handler

[2023-11-08T05:40:41.160Z]     return func(*args, **kwargs)

[2023-11-08T05:40:41.160Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 164, in handler

[2023-11-08T05:40:41.160Z]     return func(self, *args, **kwargs)

[2023-11-08T05:40:41.160Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 95, in handler

[2023-11-08T05:40:41.160Z]     raise MilvusException(

[2023-11-08T05:40:41.160Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for flush timeout, collection: FlushChecker__NVEUZylL)>

[2023-11-08T05:40:41.160Z]  (api_request.py:45)

[2023-11-08T05:40:41.160Z] [2023-11-08 05:31:30 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for flush timeout, collection: FlushChecker__NVEUZylL)> (api_request.py:46)
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-for-release-cron/detail/chaos-test-kafka-for-release-cron/8083/pipeline

log:
[artifacts-etcd-pod-failure-8083-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/13292835/artifacts-etcd-pod-failure-8083-pytest-logs.tar.gz)
[artifacts-etcd-pod-failure-8083-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/13292836/artifacts-etcd-pod-failure-8083-server-logs.tar.gz)

**Comment by weiliu1031** [comment]
please verify this with latest image
