### ISSUE TITLE
[Bug]: COSINE metric_type index create error

### ISSUE THREAD

**Issue by v4if** [milvus-io/milvus#28340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.13
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

COSINE metric_type index create error

### Steps To Reproduce

```markdown
from pymilvus import (
    connections,
    FieldSchema,
    CollectionSchema,
    DataType,
    Collection,
    utility,
    Index,
)

connections.connect()
field1 = FieldSchema("int64", DataType.INT64, is_primary=True)
field2 = FieldSchema("fvec", DataType.FLOAT_VECTOR, is_primary=False, dim=128)
schema = CollectionSchema(fields=[field1, field2])
collection = Collection(name='test', schema=schema)

index_params = {"index_type": "IVF_SQ8", "metric_type": "COSINE", "params": {"nlist": 64}}
index = Index(collection, "fvec", index_params)
```

### Milvus Log

```
RPC error: [get_index_state], <AmbiguousIndexName: (code=1, message=There are multiple indexes, please specify the index_name.)>, <Time:{'RPC start': '2023-11-10 15:30:03.470582', 'RPC error': '2023-11-10 15:30:03.472554'}>
RPC error: [wait_for_creating_index], <AmbiguousIndexName: (code=1, message=There are multiple indexes, please specify the index_name.)>, <Time:{'RPC start': '2023-11-10 15:30:02.969229', 'RPC error': '2023-11-10 15:30:03.472734'}>
RPC error: [create_index], <AmbiguousIndexName: (code=1, message=There are multiple indexes, please specify the index_name.)>, <Time:{'RPC start': '2023-11-10 15:30:02.966344', 'RPC error': '2023-11-10 15:30:03.472801'}>
Traceback (most recent call last):
  File "/home/ray/test.py", line 19, in <module>
    index = Index(collection, "fvec", index_params)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/pymilvus/orm/index.py", line 83, in __init__
    conn.create_index(self._collection.name, self._field_name, self._index_params, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/pymilvus/decorators.py", line 129, in handler
    raise e from e
  File "/home/ray/anaconda3/lib/python3.9/site-packages/pymilvus/decorators.py", line 125, in handler
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/pymilvus/decorators.py", line 164, in handler
    return func(self, *args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/pymilvus/decorators.py", line 104, in handler
    raise e from e
  File "/home/ray/anaconda3/lib/python3.9/site-packages/pymilvus/decorators.py", line 68, in handler
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/pymilvus/client/grpc_handler.py", line 884, in create_index
    index_success, fail_reason = self.wait_for_creating_index(
  File "/home/ray/anaconda3/lib/python3.9/site-packages/pymilvus/decorators.py", line 129, in handler
    raise e from e
  File "/home/ray/anaconda3/lib/python3.9/site-packages/pymilvus/decorators.py", line 125, in handler
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/pymilvus/decorators.py", line 164, in handler
    return func(self, *args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/pymilvus/decorators.py", line 104, in handler
    raise e from e
  File "/home/ray/anaconda3/lib/python3.9/site-packages/pymilvus/decorators.py", line 68, in handler
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/pymilvus/client/grpc_handler.py", line 993, in wait_for_creating_index
    state, fail_reason = self.get_index_state(
  File "/home/ray/anaconda3/lib/python3.9/site-packages/pymilvus/decorators.py", line 129, in handler
    raise e from e
  File "/home/ray/anaconda3/lib/python3.9/site-packages/pymilvus/decorators.py", line 125, in handler
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/pymilvus/decorators.py", line 164, in handler
    return func(self, *args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/pymilvus/decorators.py", line 104, in handler
    raise e from e
  File "/home/ray/anaconda3/lib/python3.9/site-packages/pymilvus/decorators.py", line 68, in handler
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/pymilvus/client/grpc_handler.py", line 983, in get_index_state
    raise AmbiguousIndexName(message=ExceptionsMessage.AmbiguousIndexName)
pymilvus.exceptions.AmbiguousIndexName: <AmbiguousIndexName: (code=1, message=There are multiple indexes, please specify the index_name.)>
```

**Comment by yanliang567** [comment]
@v4if Milvus v2.2.13 does not support cosine, please retry on milvus 2.3.0 or later.(also remember to upgrade the pymilvus)

/assign @v4if 
/unassign
