### ISSUE TITLE
[Bug]: Load collection failed for timeout(120s) with milvus panic `fatal error: concurrent map writes`

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#28397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-20231113-49eadcd5
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):     rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.16.post1.dev6
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Load collection failed for timeout(120s) with milvus panic `fatal error: concurrent map writes`.
```
[2023-11-13T10:18:44.993Z] [2023-11-13 10:01:21 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:56)
[2023-11-13T10:18:44.993Z] [2023-11-13 10:01:25 - WARNING - pymilvus.decorators]: [93m[get_loading_progress] retry:4, cost: 0.27s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.83.58:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-11-13T10:18:44.993Z] [2023-11-13 10:01:25 - WARNING - pymilvus.decorators]: [93m[get_loading_progress] retry:5, cost: 0.81s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.83.58:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-11-13T10:18:44.993Z] [2023-11-13 10:01:26 - WARNING - pymilvus.decorators]: [93m[get_loading_progress] retry:6, cost: 2.43s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.83.58:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-11-13T10:18:44.993Z] [2023-11-13 10:01:28 - WARNING - pymilvus.decorators]: [93m[get_loading_progress] retry:7, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.83.58:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-11-13T10:18:44.993Z] [2023-11-13 10:01:31 - WARNING - pymilvus.decorators]: [93m[get_loading_progress] retry:8, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.83.58:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-11-13T10:18:44.993Z] [2023-11-13 10:01:34 - WARNING - pymilvus.decorators]: [93m[get_loading_progress] retry:9, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.83.58:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-11-13T10:18:44.993Z] [2023-11-13 10:01:37 - WARNING - pymilvus.decorators]: [93m[get_loading_progress] retry:10, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.83.58:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-11-13T10:18:44.993Z] [2023-11-13 10:01:40 - WARNING - pymilvus.decorators]: [93m[get_loading_progress] retry:11, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.83.58:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-11-13T10:18:44.993Z] [2023-11-13 10:01:43 - WARNING - pymilvus.decorators]: [93m[get_loading_progress] retry:12, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.83.58:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-11-13T10:18:44.993Z] [2023-11-13 10:01:46 - WARNING - pymilvus.decorators]: [93m[get_loading_progress] retry:13, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.83.58:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-11-13T10:18:44.993Z] [2023-11-13 10:01:49 - WARNING - pymilvus.decorators]: [93m[get_loading_progress] retry:14, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.83.58:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-11-13T10:18:44.993Z] [2023-11-13 10:01:57 - WARNING - pymilvus.decorators]: [93m[get_loading_progress] retry:15, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.83.58:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-11-13T10:18:44.993Z] [2023-11-13 10:02:00 - WARNING - pymilvus.decorators]: [93m[get_loading_progress] retry:16, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.83.58:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-11-13T10:18:44.993Z] [2023-11-13 10:02:03 - WARNING - pymilvus.decorators]: [93m[get_loading_progress] retry:17, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.83.58:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-11-13T10:18:44.993Z] [2023-11-13 10:02:06 - WARNING - pymilvus.decorators]: [93m[get_loading_progress] retry:18, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.83.58:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-11-13T10:18:44.993Z] [2023-11-13 10:02:09 - WARNING - pymilvus.decorators]: [93m[get_loading_progress] retry:19, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.83.58:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-11-13T10:18:44.994Z] [2023-11-13 10:02:12 - WARNING - pymilvus.decorators]: [93m[get_loading_progress] retry:20, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.83.58:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-11-13T10:18:44.994Z] [2023-11-13 10:02:15 - WARNING - pymilvus.decorators]: [93m[get_loading_progress] retry:21, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.83.58:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-11-13T10:18:44.994Z] [2023-11-13 10:02:18 - WARNING - pymilvus.decorators]: [93m[get_loading_progress] retry:22, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.83.58:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-11-13T10:18:44.994Z] [2023-11-13 10:02:21 - WARNING - pymilvus.decorators]: [93m[get_loading_progress] retry:23, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.83.58:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-11-13T10:18:44.994Z] [2023-11-13 10:02:24 - WARNING - pymilvus.decorators]: [93m[get_loading_progress] retry:24, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.83.58:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-11-13T10:18:44.994Z] [2023-11-13 10:02:27 - WARNING - pymilvus.decorators]: [93m[get_loading_progress] retry:25, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.83.58:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-11-13T10:18:44.994Z] [2023-11-13 10:02:30 - WARNING - pymilvus.decorators]: [93m[get_loading_progress] retry:26, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.83.58:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-11-13T10:18:44.994Z] [2023-11-13 10:02:33 - WARNING - pymilvus.decorators]: [93m[get_loading_progress] retry:27, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.83.58:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-11-13T10:18:44.994Z] [2023-11-13 10:02:36 - WARNING - pymilvus.decorators]: [93m[get_loading_progress] retry:28, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.83.58:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-11-13T10:18:44.994Z] [2023-11-13 10:02:39 - WARNING - pymilvus.decorators]: [93m[get_loading_progress] retry:29, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.83.58:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-11-13T10:18:44.994Z] [2023-11-13 10:02:42 - WARNING - pymilvus.decorators]: [93m[get_loading_progress] retry:30, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.83.58:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-11-13T10:18:44.994Z] [2023-11-13 10:02:45 - WARNING - pymilvus.decorators]: [93m[get_loading_progress] retry:31, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.83.58:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-11-13T10:18:44.994Z] [2023-11-13 10:02:48 - WARNING - pymilvus.decorators]: [93m[get_loading_progress] retry:32, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.83.58:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-11-13T10:18:44.994Z] [2023-11-13 10:02:51 - WARNING - pymilvus.decorators]: [93m[get_loading_progress] retry:33, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.83.58:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-11-13T10:18:44.994Z] [2023-11-13 10:02:54 - WARNING - pymilvus.decorators]: [93m[get_loading_progress] retry:34, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.83.58:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-11-13T10:18:44.994Z] [2023-11-13 10:02:57 - WARNING - pymilvus.decorators]: [93m[get_loading_progress] retry:35, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.83.58:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-11-13T10:18:44.994Z] [2023-11-13 10:03:00 - WARNING - pymilvus.decorators]: [93m[get_loading_progress] retry:36, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.83.58:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-11-13T10:18:44.994Z] [2023-11-13 10:03:03 - WARNING - pymilvus.decorators]: [93m[get_loading_progress] retry:37, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.83.58:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-11-13T10:18:44.994Z] [2023-11-13 10:03:06 - WARNING - pymilvus.decorators]: [93m[get_loading_progress] retry:38, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.255.83.58:19530: Failed to connect to remote host: Connection refused>[0m (decorators.py:88)
[2023-11-13T10:18:44.994Z] [2023-11-13 10:03:09 - ERROR - pymilvus.decorators]: RPC error: [get_loading_progress], <MilvusException: (code=1, message=collection 445609694443625229 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2023-11-13 10:01:25.075495', 'RPC error': '2023-11-13 10:03:09.347033'}> (decorators.py:126)
[2023-11-13T10:18:44.994Z] [2023-11-13 10:03:09 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=collection 445609694443625229 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2023-11-13 10:01:22.056801', 'RPC error': '2023-11-13 10:03:09.347268'}> (decorators.py:126)
[2023-11-13T10:18:44.995Z] [2023-11-13 10:03:09 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=collection 445609694443625229 has not been loaded to memory or load failed)>, <Time:{'RPC start': '2023-11-13 10:01:21.667712', 'RPC error': '2023-11-13 10:03:09.347365'}> (decorators.py:126)
[2023-11-13T10:18:44.995Z] [2023-11-13 10:03:09 - ERROR - ci_test]: Traceback (most recent call last):
[2023-11-13T10:18:44.995Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2023-11-13T10:18:44.995Z]     res = func(*args, **_kwargs)
[2023-11-13T10:18:44.995Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2023-11-13T10:18:44.995Z]     return func(*arg, **kwargs)
[2023-11-13T10:18:44.995Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 416, in load
[2023-11-13T10:18:44.995Z]     conn.load_collection(
[2023-11-13T10:18:44.995Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 127, in handler
[2023-11-13T10:18:44.995Z]     raise e from e
[2023-11-13T10:18:44.995Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 123, in handler
[2023-11-13T10:18:44.995Z]     return func(*args, **kwargs)
[2023-11-13T10:18:44.995Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 162, in handler
[2023-11-13T10:18:44.995Z]     return func(self, *args, **kwargs)
[2023-11-13T10:18:44.995Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 102, in handler
[2023-11-13T10:18:44.995Z]     raise e from e
[2023-11-13T10:18:44.995Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 68, in handler
[2023-11-13T10:18:44.995Z]     return func(*args, **kwargs)
[2023-11-13T10:18:44.995Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 919, in load_collection
[2023-11-13T10:18:44.995Z]     self.wait_for_loading_collection(collection_name, timeout)
[2023-11-13T10:18:44.995Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 127, in handler
[2023-11-13T10:18:44.995Z]     raise e from e
[2023-11-13T10:18:44.995Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 123, in handler
[2023-11-13T10:18:44.995Z]     return func(*args, **kwargs)
[2023-11-13T10:18:44.995Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 162, in handler
[2023-11-13T10:18:44.995Z]     return func(self, *args, **kwargs)
[2023-11-13T10:18:44.995Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 102, in handler
[2023-11-13T10:18:44.995Z]     raise e from e
[2023-11-13T10:18:44.995Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 68, in handler
[2023-11-13T10:18:44.995Z]     return func(*args, **kwargs)
[2023-11-13T10:18:44.995Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 937, in wait_for_loading_collection
[2023-11-13T10:18:44.995Z]     progress = self.get_loading_progress(collection_name, timeout=timeout)
[2023-11-13T10:18:44.995Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 127, in handler
[2023-11-13T10:18:44.995Z]     raise e from e
[2023-11-13T10:18:44.995Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 123, in handler
[2023-11-13T10:18:44.995Z]     return func(*args, **kwargs)
[2023-11-13T10:18:44.995Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 162, in handler
[2023-11-13T10:18:44.995Z]     return func(self, *args, **kwargs)
[2023-11-13T10:18:44.995Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 102, in handler
[2023-11-13T10:18:44.995Z]     raise e from e
[2023-11-13T10:18:44.995Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 68, in handler
[2023-11-13T10:18:44.995Z]     return func(*args, **kwargs)
[2023-11-13T10:18:44.995Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 1030, in get_loading_progress
[2023-11-13T10:18:44.995Z]     raise MilvusException(response.status.error_code, response.status.reason)
[2023-11-13T10:18:44.995Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection 445609694443625229 has not been loaded to memory or load failed)>
[2023-11-13T10:18:44.995Z]  (api_request.py:39)
[2023-11-13T10:18:44.995Z] [2023-11-13 10:03:09 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=collection 445609694443625229 has not been loaded to memory or load failed)> (api_request.py:40)
```

### Expected Behavior

pass

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.2.0/12/pipeline/124/
2. log: [artifacts-milvus-standalone-nightly-12-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.2.0/12/artifact/artifacts-milvus-standalone-nightly-12-pymilvus-e2e-logs.tar.gz)
3. failed time: [2023-11-13T10:03:14.334Z] [gw5] [ 77%] FAILED testcases/test_search.py::TestSearchPagination::test_search_pagination_with_expression[0-False-True-int64 in [300/2, 900%40, -10*30+800, 2048/2%200, (100+200)*2]] 

```
2023-11-13T18:01:24.674821774+08:00 stderr F fatal error: concurrent map writes
2023-11-13T18:01:24.678001867+08:00 stderr F
2023-11-13T18:01:24.678020469+08:00 stderr F goroutine 2567952 [running]:
2023-11-13T18:01:24.678025659+08:00 stderr F runtime.throw({0x415244d?, 0x0?})
2023-11-13T18:01:24.678038795+08:00 stderr F    /usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc00adc9e30 sp=0xc00adc9e00 pc=0x1566f11
2023-11-13T18:01:24.678055808+08:00 stderr F runtime.mapassign_fast64(0x45e24b8?, 0xc00249dc68?, 0x62f1fa7f96a43f5)
2023-11-13T18:01:24.678066391+08:00 stderr F    /usr/local/go/src/runtime/map_fast64.go:102 +0x2c5 fp=0xc00adc9e68 sp=0xc00adc9e30 pc=0x1541685
2023-11-13T18:01:24.678071102+08:00 stderr F github.com/milvus-io/milvus/internal/datacoord.FilterInIndexedSegments.func1()
2023-11-13T18:01:24.678077942+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/datacoord/util.go:158 +0x35f fp=0xc00adc9f78 sp=0xc00adc9e68 pc=0x2a4913f
2023-11-13T18:01:24.678082132+08:00 stderr F golang.org/x/sync/errgroup.(*Group).Go.func1()
2023-11-13T18:01:24.67808674+08:00 stderr F     /go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64 fp=0xc00adc9fe0 sp=0xc00adc9f78 pc=0x2301a64
2023-11-13T18:01:24.67809048+08:00 stderr F runtime.goexit()
2023-11-13T18:01:24.678114583+08:00 stderr F    /usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00adc9fe8 sp=0xc00adc9fe0 pc=0x159c061

```

**Comment by NicoYuan1986** [comment]
Fixed. 2.2.0-20231113-9654d323
