### ISSUE TITLE
[Bug]: Load timeout(120s) for 2 replicas

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#28392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20231113-49eadcd5
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):kafka    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```

[2023-11-13T09:00:48.228Z] <name>: deploy_test_index_type_BIN_IVF_FLAT_is_compacted_not_compacted_segment_status_all_is_string_indexed_is_string_indexed_replica_number_2_is_deleted_is_deleted_data_size_3000

[2023-11-13T09:00:48.228Z] <description>: 

[2023-11-13T09:00:48.228Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64',......  (api_request.py:37)

[2023-11-13T09:00:48.228Z] [2023-11-13 08:58:07 - INFO - ci_test]: inserted 3000 data into collection deploy_test_index_type_BIN_IVF_FLAT_is_compacted_not_compacted_segment_status_all_is_string_indexed_is_string_indexed_replica_number_2_is_deleted_is_deleted_data_size_3000 (common_func.py:1382)

[2023-11-13T09:00:48.228Z] [2023-11-13 08:58:07 - DEBUG - ci_test]: Dynamic field is enabled: False (common_func.py:1384)

[2023-11-13T09:00:48.228Z] [2023-11-13 08:58:08 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [      int64   float varchar                                      binary_vector

[2023-11-13T09:00:48.228Z] 0         0     0.0       0       b'\xf26=o\xdcO\x1f5\x82\t\x00T|\x7f\x81\x8f'

[2023-11-13T09:00:48.228Z] 1         1     1.0       1  b'\x92\x81\xfb\xb3%\x8c\x92\xa2U\xc7\x8e\x92\x...

[2023-11-13T09:00:48.228Z] 2         2     2.0       2          b'\xfeaR\xe78^\xa2(\xa2\\......, kwargs: {'timeout': 180} (api_request.py:62)

[2023-11-13T09:00:48.228Z] [2023-11-13 08:58:08 - DEBUG - ci_test]: (api_response) : (insert count: 3000, delete count: 0, upsert count: 0, timestamp: 445609643352260610, success count: 3000, err count: 0)  (api_request.py:37)

[2023-11-13T09:00:48.228Z] [2023-11-13 08:58:08 - DEBUG - ci_test]: (api_request)  : [Collection.release] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2023-11-13T09:00:48.228Z] [2023-11-13 08:58:10 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-11-13T09:00:48.228Z] [2023-11-13 08:58:10 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 2, 120], kwargs: {} (api_request.py:62)

[2023-11-13T09:00:48.228Z] [2023-11-13 09:00:11 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=wait for loading collection timeout, collection: deploy_test_index_type_BIN_IVF_FLAT_is_compacted_not_compacted_segment_status_all_is_string_indexed_is_string_indexed_replica_number_2_is_deleted_is_deleted_data_size_3000)>, <Time:{'RPC start': '2023-11-13 08:58:11.182493', 'RPC error': '2023-11-13 09:00:11.348525'}> (decorators.py:128)

[2023-11-13T09:00:48.228Z] [2023-11-13 09:00:11 - WARNING - pymilvus.decorators]: Retry timeout: 120s (decorators.py:94)

[2023-11-13T09:00:48.228Z] [2023-11-13 09:00:11 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: deploy_test_index_type_BIN_IVF_FLAT_is_compacted_not_compacted_segment_status_all_is_string_indexed_is_string_indexed_replica_number_2_is_deleted_is_deleted_data_size_3000)>, <Time:{'RPC start': '2023-11-13 08:58:10.125793', 'RPC error': '2023-11-13 09:00:11.348902'}> (decorators.py:128)

[2023-11-13T09:00:48.228Z] [2023-11-13 09:00:11 - ERROR - ci_test]: Traceback (most recent call last):

[2023-11-13T09:00:48.228Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2023-11-13T09:00:48.228Z]     res = func(*args, **_kwargs)

[2023-11-13T09:00:48.228Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2023-11-13T09:00:48.228Z]     return func(*arg, **kwargs)

[2023-11-13T09:00:48.228Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 420, in load

[2023-11-13T09:00:48.228Z]     conn.load_collection(

[2023-11-13T09:00:48.228Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 129, in handler

[2023-11-13T09:00:48.228Z]     raise e from e

[2023-11-13T09:00:48.228Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 125, in handler

[2023-11-13T09:00:48.228Z]     return func(*args, **kwargs)

[2023-11-13T09:00:48.228Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 164, in handler

[2023-11-13T09:00:48.228Z]     return func(self, *args, **kwargs)

[2023-11-13T09:00:48.228Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 95, in handler

[2023-11-13T09:00:48.228Z]     raise MilvusException(

[2023-11-13T09:00:48.228Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: deploy_test_index_type_BIN_IVF_FLAT_is_compacted_not_compacted_segment_status_all_is_string_indexed_is_string_indexed_replica_number_2_is_deleted_is_deleted_data_size_3000)>

[2023-11-13T09:00:48.228Z]  (api_request.py:45)

[2023-11-13T09:00:48.228Z] [2023-11-13 09:00:11 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: deploy_test_index_type_BIN_IVF_FLAT_is_compacted_not_compacted_segment_status_all_is_string_indexed_is_string_indexed_replica_number_2_is_deleted_is_deleted_data_size_3000)> (api_request.py:46)
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_kafka_for_release_cron/detail/deploy_test_kafka_for_release_cron/1564/pipeline

log:
[artifacts-kafka-cluster-reinstall-1564-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/13333766/artifacts-kafka-cluster-reinstall-1564-pytest-logs.tar.gz)
[artifacts-kafka-cluster-reinstall-1564-server-second-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/13333767/artifacts-kafka-cluster-reinstall-1564-server-second-deployment-logs.tar.gz)

**Comment by zhuwenxing** [comment]
/assign @bigsheeper 
PTAL

It reproduced after https://github.com/milvus-io/milvus/pull/28118 merged

**Comment by zhuwenxing** [comment]
Not a stable reproduced issue

**Comment by bigsheeper** [comment]
> It reproduced after https://github.com/milvus-io/milvus/pull/28118 merged

https://github.com/milvus-io/milvus/pull/28118 affects only the datanode, not the load logic. @zhuwenxing

**Comment by bigsheeper** [comment]
Failed to connect to QueryNode: 
```
[2023/11/13 08:55:52.055 +00:00] [WARN] [grpcclient/client.go:281] ["fail to get grpc client in the retry state"] [traceID=656aa969042afea6] [client_role=querynode] [error="failed to connect 10.104.1.163:21123, reason: context canceled"]
```
