### ISSUE TITLE
[Bug]: Flush failed with error `message=attempt #0: channel=by-dev-rootcoord-dml_1_xxv0: channel not found` or failed with timeout after etcd pod kill chaos test 

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#28479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20231115-bed7467f-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka): kafka   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```

[2023-11-15T20:29:42.073Z] <name>: Hello_Milvus

[2023-11-15T20:29:42.073Z] <description>: 

[2023-11-15T20:29:42.073Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}, {'n......  (api_request.py:37)

[2023-11-15T20:29:42.073Z] [2023-11-15 20:26:35 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2023-11-15T20:29:42.074Z] [2023-11-15 20:29:34 - ERROR - pymilvus.decorators]: RPC error: [flush], <MilvusException: (code=500, message=attempt #0: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #1: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #2: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #3: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #4: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #5: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #6: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #7: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #8: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #9: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #10: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #11: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #12: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #13: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #14: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #15: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #16: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #17: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #18: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #19: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #20: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #21: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #22: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #23: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #24: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #25: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #26: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #27: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #28: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #29: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #30: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #31: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #32: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #33: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #34: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #35: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #36: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #37: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #38: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #39: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #40: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #41: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #42: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #43: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #44: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #45: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #46: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #47: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #48: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #49: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #50: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #51: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #52: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found)>, <Time:{'RPC start': '2023-11-15 20:26:35.208984', 'RPC error': '2023-11-15 20:29:34.603320'}> (decorators.py:128)

[2023-11-15T20:29:42.074Z] [2023-11-15 20:29:34 - ERROR - ci_test]: Traceback (most recent call last):

[2023-11-15T20:29:42.074Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2023-11-15T20:29:42.074Z]     res = func(*args, **_kwargs)

[2023-11-15T20:29:42.074Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2023-11-15T20:29:42.074Z]     return func(*arg, **kwargs)

[2023-11-15T20:29:42.074Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 315, in flush

[2023-11-15T20:29:42.074Z]     conn.flush([self.name], timeout=timeout, **kwargs)

[2023-11-15T20:29:42.074Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 129, in handler

[2023-11-15T20:29:42.074Z]     raise e from e

[2023-11-15T20:29:42.074Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 125, in handler

[2023-11-15T20:29:42.074Z]     return func(*args, **kwargs)

[2023-11-15T20:29:42.074Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 164, in handler

[2023-11-15T20:29:42.074Z]     return func(self, *args, **kwargs)

[2023-11-15T20:29:42.074Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 104, in handler

[2023-11-15T20:29:42.074Z]     raise e from e

[2023-11-15T20:29:42.074Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 68, in handler

[2023-11-15T20:29:42.074Z]     return func(*args, **kwargs)

[2023-11-15T20:29:42.074Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 1294, in flush

[2023-11-15T20:29:42.074Z]     raise MilvusException(

[2023-11-15T20:29:42.074Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=500, message=attempt #0: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #1: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #2: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #3: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #4: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #5: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #6: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #7: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #8: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #9: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #10: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #11: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #12: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #13: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #14: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #15: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #16: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #17: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #18: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #19: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #20: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #21: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #22: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #23: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #24: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #25: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #26: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #27: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #28: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #29: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #30: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #31: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #32: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #33: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #34: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #35: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #36: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #37: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #38: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #39: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #40: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #41: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #42: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #43: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #44: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #45: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #46: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #47: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #48: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #49: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #50: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #51: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found: attempt #52: channel=by-dev-rootcoord-dml_2_445665089091412032v0: channel not found)>

[2023-11-15T20:29:42.075Z]  (api_request.py:45)
```

```
[2023-11-15T20:36:04.089Z] [2023-11-15 20:30:07 - DEBUG - ci_test]: (api_request)  : [Connections.connect] args: ['default', '', '', ''], kwargs: {'host': '10.255.137.95', 'port': 19530} (api_request.py:62)

[2023-11-15T20:36:04.089Z] [2023-11-15 20:30:07 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-11-15T20:36:04.089Z] [2023-11-15 20:30:07 - DEBUG - ci_test]: (api_request)  : [Connections.has_connection] args: ['default'], kwargs: {} (api_request.py:62)

[2023-11-15T20:36:04.089Z] [2023-11-15 20:30:07 - DEBUG - ci_test]: (api_response) : True  (api_request.py:37)

[2023-11-15T20:36:04.089Z] [2023-11-15 20:30:07 - DEBUG - ci_test]: (api_request)  : [Collection] args: ['CreateChecker__11RYPMz8', {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}, {'name': 'varchar', 'description': '', 'type': <Da......, kwargs: {'consistency_level': 'Strong'} (api_request.py:62)

[2023-11-15T20:36:04.089Z] [2023-11-15 20:30:07 - DEBUG - ci_test]: (api_response) : <Collection>:

[2023-11-15T20:36:04.089Z] -------------

[2023-11-15T20:36:04.089Z] <name>: CreateChecker__11RYPMz8

[2023-11-15T20:36:04.089Z] <description>: 

[2023-11-15T20:36:04.089Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT......  (api_request.py:37)

[2023-11-15T20:36:04.089Z] [2023-11-15 20:30:07 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2023-11-15T20:36:04.089Z] [2023-11-15 20:33:07 - ERROR - pymilvus.decorators]: grpc RpcError: [flush], <_MultiThreadedRendezvous: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded>, <Time:{'RPC start': '2023-11-15 20:30:07.739891', 'gRPC error': '2023-11-15 20:33:07.740877'}> (decorators.py:139)

[2023-11-15T20:36:04.089Z] [2023-11-15 20:33:07 - ERROR - ci_test]: Traceback (most recent call last):

[2023-11-15T20:36:04.089Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2023-11-15T20:36:04.089Z]     res = func(*args, **_kwargs)

[2023-11-15T20:36:04.089Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2023-11-15T20:36:04.089Z]     return func(*arg, **kwargs)

[2023-11-15T20:36:04.089Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 315, in flush

[2023-11-15T20:36:04.089Z]     conn.flush([self.name], timeout=timeout, **kwargs)

[2023-11-15T20:36:04.089Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 143, in handler

[2023-11-15T20:36:04.089Z]     raise e from e

[2023-11-15T20:36:04.089Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 125, in handler

[2023-11-15T20:36:04.089Z]     return func(*args, **kwargs)

[2023-11-15T20:36:04.089Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 164, in handler

[2023-11-15T20:36:04.089Z]     return func(self, *args, **kwargs)

[2023-11-15T20:36:04.089Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 79, in handler

[2023-11-15T20:36:04.089Z]     raise e from e

[2023-11-15T20:36:04.089Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 68, in handler

[2023-11-15T20:36:04.089Z]     return func(*args, **kwargs)

[2023-11-15T20:36:04.089Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 1292, in flush

[2023-11-15T20:36:04.089Z]     response = future.result()

[2023-11-15T20:36:04.089Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 881, in result

[2023-11-15T20:36:04.089Z]     raise self

[2023-11-15T20:36:04.089Z] grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:

[2023-11-15T20:36:04.089Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2023-11-15T20:36:04.089Z] 	details = "Deadline Exceeded"

[2023-11-15T20:36:04.089Z] 	debug_error_string = "UNKNOWN:Deadline Exceeded {created_time:"2023-11-15T20:33:07.740464545+00:00", grpc_status:4}"

[2023-11-15T20:36:04.089Z] >

[2023-11-15T20:36:04.089Z]  (api_request.py:45)

[2023-11-15T20:36:04.089Z] [2023-11-15 20:33:07 - ERROR - ci_test]: (api_response) : <_MultiThreadedRendezvous of RPC that terminated with:

[2023-11-15T20:36:04.089Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2023-11-15T20:36:04.089Z] 	details = "Deadline Exceeded"

[2023-11-15T20:36:04.089Z] 	debug_error_string = "UNKNOWN:Deadline Exceeded {created_time:"2023-11-15T20:33:07.740464545+00:00", grpc_status:4}"

[2023-11-15T20:36:04.089Z] > (api_request.py:46)
```

### Milvus Log

failed job:https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-cron/detail/chaos-test-kafka-cron/9116/pipeline

log:
[artifacts-etcd-pod-kill-9116-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/13371653/artifacts-etcd-pod-kill-9116-pytest-logs.tar.gz)
[artifacts-etcd-pod-kill-9116-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/13371654/artifacts-etcd-pod-kill-9116-server-logs.tar.gz)

**Comment by zhuwenxing** [comment]
This issue also happened in other components chaos test, not only the etcd chaos test.

**Comment by jaime0815** [comment]
The assigning channel failed on the DataNode because the stats log doesn't exist.
the issue is related to #28320

```
[2023/11/15 20:33:07.721 +00:00] [WARN] [storage/minio_chunk_manager.go:181] ["failed to read object"] [path=file/stats_log/445665089091613301/445665089091613302/445665089091613337/100/1] [error="The specified key does not exist.: key=file/stats_log/445665089091613301/445665089091613302/445665089091613337/100/1: key not found"] [errorVerbose="The specified key does not exist.: key=file/stats_log/445665089091613301/445665089091613302/445665089091613337/100/1: key not found\n(1) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus/pkg/util/merr.WrapErrIoKeyNotFound\n  | \t/go/src/github.com/milvus-io/milvus/pkg/util/merr/utils.go:654\n  | [...repeated from below...]\nWraps: (2) The specified key does not exist.\nWraps: (3) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus/pkg/util/merr.WrapErrIoKeyNotFound\n  | \t/go/src/github.com/milvus-io/milvus/pkg/util/merr/utils.go:652\n  | github.com/milvus-io/milvus/internal/storage.checkObjectStorageError\n  | \t/go/src/github.com/milvus-io/milvus/internal/storage/remote_chunk_manager.go:410\n  | github.com/milvus-io/milvus/internal/storage.(*MinioChunkManager).Read\n  | \t/go/src/github.com/milvus-io/milvus/internal/storage/minio_chunk_manager.go:179\n  | github.com/milvus-io/milvus/internal/storage.(*MinioChunkManager).MultiRead\n  | \t/go/src/github.com/milvus-io/milvus/internal/storage/minio_chunk_manager.go:206\n  | github.com/milvus-io/milvus/internal/datanode.loadStats\n  | \t/go/src/github.com/milvus-io/milvus/internal/datanode/data_sync_service.go:236\n  | github.com/milvus-io/milvus/internal/datanode.initMetaCache.func1.1\n  | \t/go/src/github.com/milvus-io/milvus/internal/datanode/data_sync_service.go:157\n  | github.com/milvus-io/milvus/pkg/util/conc.(*Pool[...]).Submit.func1\n  | \t/go/src/github.com/milvus-io/milvus/pkg/util/conc/pool.go:79\n  | github.com/panjf2000/ants/v2.(*goWorker).run.func1\n  | \t/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.2/worker.go:67\n  | runtime.goexit\n  | \t/usr/local/go/src/runtime/asm_amd64.s:1598\nWraps: (4) key=file/stats_log/445665089091613301/445665089091613302/445665089091613337/100/1\nWraps: (5) key not found\nError types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) merr.milvusError"]
[2023/11/15 20:33:07.721 +00:00] [WARN] [datanode/data_sync_service.go:238] ["failed to load bloom filter files"] [segmentID=445665089091613337] [error="The specified key does not exist.: key=file/stats_log/445665089091613301/445665089091613302/445665089091613337/100/1: key not found"]
[2023/11/15 20:33:07.721 +00:00] [WARN] [datanode/flow_graph_manager.go:136] ["fail to create new DataSyncService"] [channel=by-dev-rootcoord-dml_7_445665089091613301v0] [error="The specified key does not exist.: key=file/stats_log/445665089091613301/445665089091613302/445665089091613337/100/1: key not found"]
```

**Comment by jaime0815** [comment]
the newest stats log key from the merged stats log and it is generated after flush. Now we need to confirm what will happen if the segment doesn't flush.

**Comment by jaime0815** [comment]
The segment  has been flushed and synced, which means the statslog should persist, but it missed on minio while loading statlogs on datanode
```
2023-11-16 03:49:58	
[2023/11/15 19:49:58.152 +00:00] [INFO] [datacoord/services.go:426] ["receive SaveBinlogPaths request"] [traceID=9088a267e5e825f7f478dc41040aadbe] [nodeID=10] [collectionID=0] [segmentID=445665089091613337] [isFlush=true] [isDropped=false] [startPositions=null] [checkpoints="[{\"segmentID\":445665089091613337,\"position\":{\"channel_name\":\"by-dev-rootcoord-dml_7_445665089091613301v0\",\"msgID\":\"zwAAAAAAAAA=\",\"msgGroup\":\"datanode-10-by-dev-rootcoord-dml_7_445665089091613301v0-true\",\"timestamp\":445665194141286409},\"num_of_rows\":1503}]"]
2023-11-16 03:49:58	
[2023/11/15 19:49:58.155 +00:00] [INFO] [datacoord/server.go:954] ["flush successfully"] [segmentID=445665089091613337]
2023-11-16 03:49:58	
[2023/11/15 19:49:58.156 +00:00] [INFO] [datacoord/services.go:426] ["receive SaveBinlogPaths request"] [traceID=18d8d44a8cec26b520845a35255b8130] [nodeID=10] [collectionID=0] [segmentID=445665089091613337] [isFlush=true] [isDropped=false] [startPositions=null] [checkpoints="[{\"segmentID\":445665089091613337,\"position\":{\"channel_name\":\"by-dev-rootcoord-dml_7_445665089091613301v0\",\"msgID\":\"0AAAAAAAAAA=\",\"msgGroup\":\"datanode-10-by-dev-rootcoord-dml_7_445665089091613301v0-true\",\"timestamp\":445665194206822402},\"num_of_rows\":1503}]"]
2023-11-16 03:49:58	
[2023/11/15 19:49:58.158 +00:00] [INFO] [datacoord/server.go:954] ["flush successfully"] [segmentID=445665089091613337]
2023-11-16 03:49:58	
[2023/11/15 19:49:58.157 +00:00] [WARN] [syncmgr/task.go:139] ["task done"] [collectionID=0] [partitionID=445665089091613302] [segmentID=445665089091613337] [channel=by-dev-rootcoord-dml_7_445665089091613301v0]Show context
2023-11-16 03:49:58	
[2023/11/15 19:49:58.160 +00:00] [WARN] [syncmgr/task.go:139] ["task done"] [collectionID=0] [partitionID=445665089091613302] [segmentID=445665089091613337] [channel=by-dev-rootcoord-dml_7_445665089091613301v0]

2023-11-16 04:03:17	
[2023/11/15 20:03:17.118 +00:00] [INFO] [datacoord/channel_manager.go:383] ["deregister node"] [nodeID=8] [updates="[\"{type=Delete,nodeID=8,channels=\\\"[by-dev-rootcoord-dml_7_445665089091613301v0
2023-11-16 04:05:23	
[2023/11/15 20:05:23.084 +00:00] [INFO] [datanode/data_sync_service.go:148] ["recover segments from checkpoints"] [vChannelName=by-dev-rootcoord-dml_7_445665089091613301v0] [segmentID=445665089091613337] [numRows=1503] [segmentType=sealed]Show context
2023-11-16 04:05:23	
[2023/11/15 20:05:23.092 +00:00] [WARN] [datanode/flow_graph_manager.go:136] ["fail to create new DataSyncService"] [channel=by-dev-rootcoord-dml_7_445665089091613301v0] [error="The specified key does not exist.: key=file/stats_log/445665089091613301/445665089091613302/445665089091613337/100/1: key not found"]
2023-11-16 04:05:23	
```

**Comment by zhuwenxing** [comment]
This issue almost happened in all chaos tests, so set it as critical.

**Comment by xiaofan-luan** [comment]
this is only only happned on master but not 2.3 right?
could be related to L0 Delete

**Comment by zhuwenxing** [comment]
> this is only only happned on master but not 2.3 right? could be related to L0 Delete

Yes, it works well in 2.3 (2.3-20231115-21d995b1)

**Comment by xiaofan-luan** [comment]
this could related by L0 delete

**Comment by congqixia** [comment]
@zhuwenxing this problem shall be fixed after https://github.com/milvus-io/milvus/pull/28494
could you please verify?
/assign @zhuwenxing
