### ISSUE TITLE
[Bug]: Load collection timeout(180s) after datacoord pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#28481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20231115-bed7467f-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2023-11-15T19:13:44.108Z] [2023-11-15 19:13:37 - INFO - ci_test]: all database: ['default', 'prod'] (test_data_persistence.py:26)

[2023-11-15T19:13:44.108Z] [2023-11-15 19:13:37 - INFO - ci_test]: [test][2023-11-15T19:13:37Z] [0.51789255s] Hello_Milvus flush -> None (wrapper.py:30)

[2023-11-15T19:13:44.108Z] [2023-11-15 19:13:37 - INFO - ci_test]: assert create collection: 0.008752822875976562, init_entities: 4000 (test_data_persistence.py:38)

[2023-11-15T19:13:44.108Z] [2023-11-15 19:13:39 - INFO - ci_test]: [test][2023-11-15T19:13:38Z] [0.76322037s] Hello_Milvus insert -> (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 445664623054553090, success count: 2000, err count: 0) (wrapper.py:30)

[2023-11-15T19:13:44.108Z] [2023-11-15 19:13:39 - INFO - ci_test]: assert insert: 0.7638733386993408 (test_data_persistence.py:45)

[2023-11-15T19:13:44.108Z] [2023-11-15 19:13:43 - INFO - ci_test]: [test][2023-11-15T19:13:39Z] [4.04844348s] Hello_Milvus flush -> None (wrapper.py:30)

[2023-11-15T19:13:44.108Z] [2023-11-15 19:13:43 - INFO - ci_test]: [test][2023-11-15T19:13:43Z] [0.51551346s] Hello_Milvus flush -> None (wrapper.py:30)

[2023-11-15T19:13:44.108Z] [2023-11-15 19:13:44 - INFO - ci_test]: [test][2023-11-15T19:13:43Z] [0.51747511s] Hello_Milvus flush -> None (wrapper.py:30)

[2023-11-15T19:13:44.366Z] [2023-11-15 19:13:44 - INFO - ci_test]: assert flush: 4.568305015563965, entities: 6000 (test_data_persistence.py:55)

[2023-11-15T19:13:44.366Z] [2023-11-15 19:13:44 - INFO - ci_test]: index info: [{'collection': 'Hello_Milvus', 'field': 'float_vector', 'index_name': 'test_tRlQeJbH', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}, {'collection': 'Hello_Milvus', 'field': 'varchar', 'index_name': 'test_LjTC8Gho', 'index_param': {}}] (test_data_persistence.py:74)

[2023-11-15T19:13:44.366Z] [2023-11-15 19:13:44 - INFO - ci_test]: [test][2023-11-15T19:13:44Z] [0.01442112s] Hello_Milvus load -> None (wrapper.py:30)

[2023-11-15T19:13:44.366Z] [2023-11-15 19:13:44 - INFO - ci_test]: [test][2023-11-15T19:13:44Z] [0.13644316s] Hello_Milvus search -> ["['id: 640, distance: 0.3274531662464142, entity: {}']"] (wrapper.py:30)

[2023-11-15T19:13:44.366Z] [2023-11-15 19:13:44 - INFO - ci_test]: assert search: 0.13696694374084473 (test_data_persistence.py:86)

[2023-11-15T19:13:45.318Z] [2023-11-15 19:13:45 - INFO - ci_test]: [test][2023-11-15T19:13:44Z] [1.01486721s] Hello_Milvus release -> None (wrapper.py:30)

[2023-11-15T19:13:46.733Z] [2023-11-15 19:13:46 - INFO - ci_test]: [test][2023-11-15T19:13:45Z] [0.75044517s] Hello_Milvus insert -> (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 445664624981311490, success count: 2000, err count: 0) (wrapper.py:30)

[2023-11-15T19:13:50.096Z] [2023-11-15 19:13:49 - INFO - ci_test]: [test][2023-11-15T19:13:46Z] [3.55392427s] Hello_Milvus flush -> None (wrapper.py:30)

[2023-11-15T19:13:50.096Z] [2023-11-15 19:13:49 - INFO - ci_test]: assert entities: 8000 (test_data_persistence.py:93)

[2023-11-15T19:16:56.692Z] [2023-11-15 19:16:50 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=wait for loading collection timeout, collection: Hello_Milvus)>, <Time:{'RPC start': '2023-11-15 19:13:49.956398', 'RPC error': '2023-11-15 19:16:50.134420'}> (decorators.py:128)

[2023-11-15T19:16:56.692Z] [2023-11-15 19:16:50 - WARNING - pymilvus.decorators]: Retry timeout: 180s (decorators.py:94)

[2023-11-15T19:16:56.692Z] [2023-11-15 19:16:50 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for loading collection timeout, collection: Hello_Milvus)>, <Time:{'RPC start': '2023-11-15 19:13:49.937355', 'RPC error': '2023-11-15 19:16:50.135413'}> (decorators.py:128)

[2023-11-15T19:16:56.692Z] [2023-11-15 19:16:50 - ERROR - ci_test]: Traceback (most recent call last):

[2023-11-15T19:16:56.692Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2023-11-15T19:16:56.692Z]     res = func(*args, **_kwargs)

[2023-11-15T19:16:56.692Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2023-11-15T19:16:56.692Z]     return func(*arg, **kwargs)

[2023-11-15T19:16:56.692Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 420, in load

[2023-11-15T19:16:56.692Z]     conn.load_collection(

[2023-11-15T19:16:56.692Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 129, in handler

[2023-11-15T19:16:56.692Z]     raise e from e

[2023-11-15T19:16:56.692Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 125, in handler

[2023-11-15T19:16:56.692Z]     return func(*args, **kwargs)

[2023-11-15T19:16:56.692Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 164, in handler

[2023-11-15T19:16:56.692Z]     return func(self, *args, **kwargs)

[2023-11-15T19:16:56.692Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 95, in handler

[2023-11-15T19:16:56.692Z]     raise MilvusException(

[2023-11-15T19:16:56.692Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for loading collection timeout, collection: Hello_Milvus)>

[2023-11-15T19:16:56.692Z]  (api_request.py:45)

[2023-11-15T19:16:56.692Z] [2023-11-15 19:16:50 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for loading collection timeout, collection: Hello_Milvus)> (api_request.py:46)

[2023-11-15T19:16:56.692Z] FAILED
```

c_name: Hello_Milvus

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-cron/detail/chaos-test-kafka-cron/9107/pipeline

log:
[artifacts-datacoord-pod-kill-9107-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/13371731/artifacts-datacoord-pod-kill-9107-pytest-logs.tar.gz)
[artifacts-datacoord-pod-kill-9107-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/13371732/artifacts-datacoord-pod-kill-9107-server-logs.tar.gz)

cluster:4am
namespace: chaos-testing
release name: datacoord-pod-kill-9107

```
[2023-11-15T19:09:02.562Z] + kubectl get pods -o wide

[2023-11-15T19:09:02.564Z] + grep datacoord-pod-kill-9107

[2023-11-15T19:09:03.123Z] datacoord-pod-kill-9107-etcd-0                                    1/1     Running     0                41m     10.104.21.35    4am-node24   <none>           <none>

[2023-11-15T19:09:03.123Z] datacoord-pod-kill-9107-etcd-1                                    1/1     Running     0                41m     10.104.23.100   4am-node27   <none>           <none>

[2023-11-15T19:09:03.123Z] datacoord-pod-kill-9107-etcd-2                                    1/1     Running     0                41m     10.104.19.136   4am-node28   <none>           <none>

[2023-11-15T19:09:03.123Z] datacoord-pod-kill-9107-kafka-0                                   2/2     Running     1 (40m ago)      41m     10.104.21.36    4am-node24   <none>           <none>

[2023-11-15T19:09:03.123Z] datacoord-pod-kill-9107-kafka-1                                   2/2     Running     1 (40m ago)      41m     10.104.24.128   4am-node29   <none>           <none>

[2023-11-15T19:09:03.123Z] datacoord-pod-kill-9107-kafka-2                                   2/2     Running     1 (40m ago)      41m     10.104.19.138   4am-node28   <none>           <none>

[2023-11-15T19:09:03.123Z] datacoord-pod-kill-9107-kafka-exporter-7dd988884d-gkqh7           1/1     Running     4 (40m ago)      41m     10.104.6.211    4am-node13   <none>           <none>

[2023-11-15T19:09:03.123Z] datacoord-pod-kill-9107-milvus-datacoord-76d9dd876b-759kp         1/1     Running     0                13m     10.104.4.222    4am-node11   <none>           <none>

[2023-11-15T19:09:03.123Z] datacoord-pod-kill-9107-milvus-datanode-547c7f7ddc-9cq4g          1/1     Running     0                41m     10.104.12.56    4am-node17   <none>           <none>

[2023-11-15T19:09:03.123Z] datacoord-pod-kill-9107-milvus-datanode-547c7f7ddc-cz99p          1/1     Running     0                41m     10.104.6.203    4am-node13   <none>           <none>

[2023-11-15T19:09:03.123Z] datacoord-pod-kill-9107-milvus-indexcoord-6984b9f5bf-lxcq5        1/1     Running     0                41m     10.104.6.208    4am-node13   <none>           <none>

[2023-11-15T19:09:03.123Z] datacoord-pod-kill-9107-milvus-indexnode-5f99b9998-gfm64          1/1     Running     0                41m     10.104.9.192    4am-node14   <none>           <none>

[2023-11-15T19:09:03.123Z] datacoord-pod-kill-9107-milvus-indexnode-5f99b9998-q2gvr          1/1     Running     0                41m     10.104.6.206    4am-node13   <none>           <none>

[2023-11-15T19:09:03.124Z] datacoord-pod-kill-9107-milvus-indexnode-5f99b9998-xrvmj          1/1     Running     0                41m     10.104.4.208    4am-node11   <none>           <none>

[2023-11-15T19:09:03.124Z] datacoord-pod-kill-9107-milvus-proxy-6b4b57cfc9-xsvtz             1/1     Running     0                41m     10.104.6.205    4am-node13   <none>           <none>

[2023-11-15T19:09:03.124Z] datacoord-pod-kill-9107-milvus-querycoord-587968c98b-5ctnd        1/1     Running     0                41m     10.104.6.210    4am-node13   <none>           <none>

[2023-11-15T19:09:03.124Z] datacoord-pod-kill-9107-milvus-querynode-7bb867bfd-57jpx          1/1     Running     0                41m     10.104.5.210    4am-node12   <none>           <none>

[2023-11-15T19:09:03.124Z] datacoord-pod-kill-9107-milvus-querynode-7bb867bfd-nsfln          1/1     Running     0                41m     10.104.12.57    4am-node17   <none>           <none>

[2023-11-15T19:09:03.124Z] datacoord-pod-kill-9107-milvus-querynode-7bb867bfd-r8bnl          1/1     Running     0                41m     10.104.6.209    4am-node13   <none>           <none>

[2023-11-15T19:09:03.124Z] datacoord-pod-kill-9107-milvus-rootcoord-649664b8f8-lgw67         1/1     Running     0                41m     10.104.6.207    4am-node13   <none>           <none>

[2023-11-15T19:09:03.124Z] datacoord-pod-kill-9107-minio-0                                   1/1     Running     0                41m     10.104.23.101   4am-node27   <none>           <none>

[2023-11-15T19:09:03.124Z] datacoord-pod-kill-9107-minio-1                                   1/1     Running     0                41m     10.104.24.127   4am-node29   <none>           <none>

[2023-11-15T19:09:03.124Z] datacoord-pod-kill-9107-minio-2                                   1/1     Running     0                41m     10.104.21.43    4am-node24   <none>           <none>

[2023-11-15T19:09:03.124Z] datacoord-pod-kill-9107-minio-3                                   1/1     Running     0                41m     10.104.20.214   4am-node22   <none>           <none>

[2023-11-15T19:09:03.124Z] datacoord-pod-kill-9107-zookeeper-0                               1/1     Running     0                41m     10.104.19.132   4am-node28   <none>           <none>

[2023-11-15T19:09:03.124Z] datacoord-pod-kill-9107-zookeeper-1                               1/1     Running     0                41m     10.104.20.209   4am-node22   <none>           <none>

[2023-11-15T19:09:03.124Z] datacoord-pod-kill-9107-zookeeper-2                               1/1     Running     0                41m     10.104.21.38    4am-node24   <none>           <none>
```

**Comment by zhuwenxing** [comment]
Load timeout(180s) after recovering from query node pod failure chaos

failed job:https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-for-release-cron/detail/chaos-test-for-release-cron/8218/pipeline
log:
[artifacts-querynode-pod-failure-8218-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/13405664/artifacts-querynode-pod-failure-8218-pytest-logs.tar.gz)

[artifacts-querynode-pod-failure-8218-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/13405665/artifacts-querynode-pod-failure-8218-server-logs.tar.gz)


* already loaded
* search and query
* release
* load (failed at this step)


chaos start and end time
```

[2023-11-19T22:28:39.642Z] [2023-11-19 22:28:38 - INFO - ci_test]: chaos injected (test_chaos_apply.py:102)

[2023-11-19T22:28:39.642Z] [2023-11-19 22:28:38 - INFO - ci_test]: chaos inject result: PodChaos, test-querynode-pod-failure-1700432918 (test_chaos_apply.py:107)

[2023-11-19T22:35:46.145Z] test-querynode-pod-failure-1700432918

[2023-11-19T22:35:46.146Z] [2023-11-19 22:35:38 - INFO - ci_test]: delete custom resource response: {'apiVersion': 'chaos-mesh.org/v1alpha1', 'kind': 'PodChaos', 'metadata': {'creationTimestamp': '2023-11-19T22:28:38Z', 'deletionGracePeriodSeconds': 0, 'deletionTimestamp': '2023-11-19T22:35:38Z', 'finalizers': ['chaos-mesh/records'], 'generation': 9, 'managedFields': [{'apiVersion': 'chaos-mesh.org/v1alpha1', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:spec': {'.': {}, 'f:action': {}, 'f:duration': {}, 'f:gracePeriod': {}, 'f:mode': {}, 'f:selector': {'.': {}, 'f:labelSelectors': {'.': {}, 'f:app.kubernetes.io/instance': {}, 'f:component': {}}, 'f:namespaces': {}}, 'f:value': {}}}, 'manager': 'OpenAPI-Generator', 'operation': 'Update', 'time': '2023-11-19T22:28:38Z'}, {'apiVersion': 'chaos-mesh.org/v1alpha1', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:finalizers': {'.': {}, 'v:"chaos-mesh/records"': {}}}, 'f:status': {'f:conditions': {}, 'f:experiment': {'f:containerRecords': {}, 'f:desiredPhase': {}}}}, 'manager': 'chaos-controller-manager', 'operation': 'Update', 'time': '2023-11-19T22:28:38Z'}], 'name': 'test-querynode-pod-failure-1700432918', 'namespace': 'chaos-testing', 'resourceVersion': '491700797', 'uid': '2d1bbadf-8971-4da7-81a3-a5dfcbc94889'}, 'spec': {'action': 'pod-failure', 'duration': '7m', 'mode': 'all', 'selector': {'labelSelectors': {'app.kubernetes.io/instance': 'querynode-pod-failure-8218', 'component': 'querynode'}, 'namespaces': ['chaos-testing']}, 'value': '1'}, 'status': {'conditions': [{'status': 'True', 'type': 'Selected'}, {'status': 'False', 'type': 'AllInjected'}, {'status': 'True', 'type': 'AllRecovered'}, {'status': 'False', 'type': 'Paused'}], 'experiment': {'containerRecords': [{'events': [{'operation': 'Apply', 'timestamp': '2023-11-19T22:28:38Z', 'type': 'Succeeded'}, {'operation': 'Recover', 'timestamp': '2023-11-19T22:35:38Z', 'type': 'Succeeded'}], 'id': 'chaos-testing/querynode-pod-failure-8218-milvus-querynode-74656d6bdf-zffmt', 'injectedCount': 1, 'phase': 'Not Injected', 'recoveredCount': 1, 'selectorKey': '.'}, {'events': [{'operation': 'Apply', 'timestamp': '2023-11-19T22:28:38Z', 'type': 'Succeeded'}, {'operation': 'Recover', 'timestamp': '2023-11-19T22:35:38Z', 'type': 'Succeeded'}], 'id': 'chaos-testing/querynode-pod-failure-8218-milvus-querynode-74656d6bdf-bp8xv', 'injectedCount': 1, 'phase': 'Not Injected', 'recoveredCount': 1, 'selectorKey': '.'}, {'events': [{'operation': 'Apply', 'timestamp': '2023-11-19T22:28:38Z', 'type': 'Succeeded'}, {'operation': 'Recover', 'timestamp': '2023-11-19T22:35:38Z', 'type': 'Succeeded'}], 'id': 'chaos-testing/querynode-pod-failure-8218-milvus-querynode-74656d6bdf-dk9vt', 'injectedCount': 1, 'phase': 'Not Injected', 'recoveredCount': 1, 'selectorKey': '.'}], 'desiredPhase': 'Stop'}}} (cus_resource_opts.py:54)

[2023-11-19T22:35:46.146Z] [2023-11-19 22:35:38 - INFO - ci_test]: chaos deleted (test_chaos_apply.py:112)
```

failure case log:
```

[2023-11-19T22:53:52.899Z] [2023-11-19 22:50:30 - INFO - ci_test]: assert query result 2000: 0.21397113800048828 (test_all_collections_after_chaos.py:107)

[2023-11-19T22:53:52.899Z] [2023-11-19 22:50:30 - DEBUG - ci_test]: (api_request)  : [Collection.release] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2023-11-19T22:53:52.899Z] [2023-11-19 22:50:31 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-11-19T22:53:52.899Z] [2023-11-19 22:50:31 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [[[5783997871128805535, 4602818704526444014, 5666913931247030845, 5566111534939049790, -5732107636228355404, 1205732209374947417, -259597121713893618, -3929206951976904381, -2052344825799577717, 8405608286197133498, 8032708864132841287, -5784876041778419629, 7888480311506033811, -6563175959379675314......, kwargs: {'timeout': 180} (api_request.py:62)

[2023-11-19T22:53:52.899Z] [2023-11-19 22:50:31 - DEBUG - ci_test]: (api_response) : (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 445758631187841026, success count: 2000, err count: 0)  (api_request.py:37)

[2023-11-19T22:53:52.899Z] [2023-11-19 22:50:31 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 180], kwargs: {} (api_request.py:62)

[2023-11-19T22:53:52.899Z] [2023-11-19 22:53:33 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=wait for loading collection timeout, collection: QueryChecker__6VGo6FlW)>, <Time:{'RPC start': '2023-11-19 22:50:32.971219', 'RPC error': '2023-11-19 22:53:33.077526'}> (decorators.py:128)

[2023-11-19T22:53:52.899Z] [2023-11-19 22:53:33 - WARNING - pymilvus.decorators]: Retry timeout: 180s (decorators.py:94)

[2023-11-19T22:53:52.899Z] [2023-11-19 22:53:33 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for loading collection timeout, collection: QueryChecker__6VGo6FlW)>, <Time:{'RPC start': '2023-11-19 22:50:31.580756', 'RPC error': '2023-11-19 22:53:33.077955'}> (decorators.py:128)

[2023-11-19T22:53:52.899Z] [2023-11-19 22:53:33 - ERROR - ci_test]: Traceback (most recent call last):

[2023-11-19T22:53:52.899Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2023-11-19T22:53:52.899Z]     res = func(*args, **_kwargs)

[2023-11-19T22:53:52.899Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2023-11-19T22:53:52.899Z]     return func(*arg, **kwargs)

[2023-11-19T22:53:52.899Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 420, in load

[2023-11-19T22:53:52.899Z]     conn.load_collection(

[2023-11-19T22:53:52.899Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 129, in handler

[2023-11-19T22:53:52.899Z]     raise e from e

[2023-11-19T22:53:52.899Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 125, in handler

[2023-11-19T22:53:52.899Z]     return func(*args, **kwargs)

[2023-11-19T22:53:52.899Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 164, in handler

[2023-11-19T22:53:52.900Z]     return func(self, *args, **kwargs)

[2023-11-19T22:53:52.900Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 95, in handler

[2023-11-19T22:53:52.900Z]     raise MilvusException(

[2023-11-19T22:53:52.900Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for loading collection timeout, collection: QueryChecker__6VGo6FlW)>

[2023-11-19T22:53:52.900Z]  (api_request.py:45)

[2023-11-19T22:53:52.900Z] [2023-11-19 22:53:33 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for loading collection timeout, collection: QueryChecker__6VGo6FlW)> (api_request.py:46)
```

**Comment by congqixia** [comment]
Same like #28857, could you please verify?
/assign @zhuwenxing
