### ISSUE TITLE
[Bug]: Qerynode terminated: pure virtual method called terminate called without an active exception SIGABRT: abort

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#28542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.15
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.2.15
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. create collection `fouram_XepQhvAI` with the schema:
```
{'auto_id': False, 'description': '', 'fields': [{'name': 'id', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float_vector', 'description': '', 'type': <DataType.FLOAT_VECTOR: 101>, 'params': {'dim': 768}}, {'name': 'int64_pk_5b', 'description': '', 'type': <DataType.INT64: 5>, 'is_partition_key': True}, {'name': 'varchar_md5', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 256}}, {'name': 'double_similarity', 'description': '', 'type': <DataType.DOUBLE: 11>}], 'enable_dynamic_field': True}
```
3.  create diskann index -> load collection
4. insert 50 million 768dim data -> flush
5. concurrent search and query with client params
```
    concurrent_params:
      concurrent_number: 100 
      during_time: '24h'
      interval: 120 
    concurrent_tasks:
      -   
        type: query
        weight: 1
        params:
          expr: '1000 <= int64_pk_5b and id < 5000'
      -   
        type: search
        weight: 9
        params:
          nq: 100 
          top_k: 100 
          expr: 'int64_pk_5b > 1000'
          random_data: true
          output_fields: ['int64_pk_5b']
          search_param:
            search_list: 200 
          timeout: null
```
6. At 07:44, scale-out add a new querynode
7. At 08:31, first search error:
```
[2023-11-17 08:31:03,376 - ERROR - fouram]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=All attempts results:
attempt #1:code: UnexpectedError, error: fail to Search, QueryNode ID=31, reason=Search 20 failed, reason  err stack trace: /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:369 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call
/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:254 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Search
/go/src/github.com/milvus-io/milvus/internal/querynode/shard_cluster.go:784 github.com/milvus-io/milvus/internal/querynode.(*ShardCluster).Search.func2
/usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit: rpc error: code = Canceled desc = grpc: the client connection is closing
attempt #2:fail to get shard leaders from QueryCoord: channel yanliang-est-128cu-rootcoord-dml_5_445677391618779117v1 is not available in any replica, err=NodeOffline(nodeID=20)
attempt #3:fail to get shard leaders from QueryCoord: channel yanliang-est-128cu-rootcoord-dml_4_445677391618779117v0 is not available in any replica, err=NodeOffline(nodeID=20)
attempt #4:fail to get shard leaders from QueryCoord: channel yanliang-est-128cu-rootcoord-dml_4_445677391618779117v0 is not available in any replica, err=NodeOffline(nodeID=20)
attempt #5:fail to get shard leaders from QueryCoord: channel yanliang-est-128cu-rootcoord-dml_4_445677391618779117v0 is not available in any replica, err=NodeOffline(nodeID=20)
)>, <Time:{'RPC start': '2023-11-17 08:22:47.555955', 'RPC error': '2023-11-17 08:31:03.376422'}> (decorators.py:126)
```

8. terminated querynode previous error
[querynode_pre.log](https://github.com/milvus-io/milvus/files/13390555/querynode_pre.log)

```
[2023/11/17 08:26:27.709 +00:00] [DEBUG] [querynode/flow_graph_delete_node.go:129] ["delete in historical replica"] [vchannel=yanliang-est-128cu-rootcoord-delta_5_445677391618779117v1] [collectionID=445677391618779117] [collectionName=] [numPKs=0] [numTS=0] [timestampBegin=445699742101929987] [timestampEnd=445699742101929987] [segmentNum=16] [traceID=5cff4c47fb899904]
[2023/11/17 08:26:27.709 +00:00] [DEBUG] [querynode/flow_graph_delete_node.go:129] ["delete in historical replica"] [vchannel=yanliang-est-128cu-rootcoord-delta_4_445677391618779117v0] [collectionID=445677391618779117] [collectionName=] [numPKs=0] [numTS=0] [timestampBegin=445699742101929987] [timestampEnd=445699742101929987] [segmentNum=16] [traceID=6c276e9d0b24fe33]
[2023/11/17 08:26:27.774 +00:00] [DEBUG] [querynode/segment.go:447] ["do search on segment done"] [traceID=5161345d91b9eaa5] [msgID=445699684417142785] [segmentID=445677391661053691] [segmentType=3] [loadIndex=true]
pure virtual method called
terminate called without an active exception
SIGABRT: abort 
PC=0x7f6cba56d00b m=375 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 725782 [syscall]:
runtime.cgocall(0x327b890, 0xc002b23930)
    /usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc002b23908 sp=0xc002b238d0 pc=0x153357c
github.com/milvus-io/milvus/internal/querynode._Cfunc_ReduceSearchResultsAndFillData(0xc0015302e8, 0x7f681f717300, 0xc003a34000, 0x11, 0xc004f4a980, 0xc004f4a9c0, 0x6)
    _cgo_gotypes.go:834 +0x55 fp=0xc002b23930 sp=0xc002b23908 pc=0x2f93e15
github.com/milvus-io/milvus/internal/querynode.reduceSearchResultsAndFillData.func1(0x3c7ee20?, 0xc00299f780?, 0xc002b23a60?, 0x2fac129?, 0x1ffffffffff?, 0xc0029e6a40?, 0x0?) 
    /go/src/github.com/milvus-io/milvus/internal/querynode/reduce.go:100 +0xdd fp=0xc002b239c0 sp=0xc002b23930 pc=0x2fac85d
github.com/milvus-io/milvus/internal/querynode.reduceSearchResultsAndFillData(0xc001923f38, {0xc003010d80, 0x11, 0x258?}, 0x90?, {0xc004f4a980, 0x6, 0x0?}, {0xc004f4a9c0, 0x6, ...}) 
    /go/src/github.com/milvus-io/milvus/internal/querynode/reduce.go:100 +0x2bc fp=0xc002b23a70 sp=0xc002b239c0 pc=0x2fac69c
github.com/milvus-io/milvus/internal/querynode.(*searchTask).reduceResults(0xc002e53b80, {0x45c9330, 0xc00332e780}, 0xc00448e750, {0xc003010d80, 0x11, 0x11})
    /go/src/github.com/milvus-io/milvus/internal/querynode/task_search.go:228 +0x15c fp=0xc002b23d18 sp=0xc002b23a70 pc=0x2f869fc
github.com/milvus-io/milvus/internal/querynode.(*searchTask).searchOnHistorical(0xc002e53b80)
    /go/src/github.com/milvus-io/milvus/internal/querynode/task_search.go:159 +0x28a fp=0xc002b23ec0 sp=0xc002b23d18 pc=0x2f85bca
github.com/milvus-io/milvus/internal/querynode.(*searchTask).Execute(0xc002e53b80?, {0x13?, 0x413e97b?})
    /go/src/github.com/milvus-io/milvus/internal/querynode/task_search.go:166 +0x2a fp=0xc002b23ef8 sp=0xc002b23ec0 pc=0x2f8604a
github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).processReadTask(0x45daa38?, {0x45e74b8, 0xc002e53b80})
    /go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:351 +0x102 fp=0xc002b23f70 sp=0xc002b23ef8 pc=0x2f84402
github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).executeReadTasks.func1({0x45e74b8, 0xc002e53b80})
    /go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:301 +0xbb fp=0xc002b23fc0 sp=0xc002b23f70 pc=0x2f8415b
github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).executeReadTasks.func4()
    /go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:323 +0x2e fp=0xc002b23fe0 sp=0xc002b23fc0 pc=0x2f8406e
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc002b23fe8 sp=0xc002b23fe0 pc=0x159d061
created by github.com/milvus-io/milvus/internal/querynode.(*taskScheduler).executeReadTasks
    /go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:323 +0x29a
```

### Steps To Reproduce

```markdown
- 4am argo link: https://argo-workflows.zilliz.cc/archived-workflows/qa/78c32bdd-c83c-4f2d-a921-c67d5920b97a?nodeId=yanliang-est-128cu-retest-2

- grafana link: https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=qa-milvus&var-instance=yanliang-est-128cu&var-collection=All&var-app_name=milvus&from=1700204264581&to=1700216906327
```

### Milvus Log

pods:
```
yanliang-est-128cu-etcd-0                                      1/1     Running     0               4d      10.104.23.121   4am-node27   <none>           <none>
yanliang-est-128cu-etcd-1                                      1/1     Running     0               4d      10.104.24.133   4am-node29   <none>           <none>
yanliang-est-128cu-etcd-2                                      1/1     Running     0               4d      10.104.17.30    4am-node23   <none>           <none>
yanliang-est-128cu-milvus-datanode-5574bd55bf-d49gt            1/1     Running     0               25h     10.104.16.12    4am-node21   <none>           <none>
yanliang-est-128cu-milvus-datanode-5574bd55bf-tkvx4            1/1     Running     0               25h     10.104.24.49    4am-node29   <none>           <none>
yanliang-est-128cu-milvus-indexnode-dfb9bf99c-rndft            1/1     Running     0               25h     10.104.9.214    4am-node14   <none>           <none>
yanliang-est-128cu-milvus-mixcoord-6dc8645df9-t2jfj            1/1     Running     0               25h     10.104.13.222   4am-node16   <none>           <none>
yanliang-est-128cu-milvus-proxy-794dd75685-8d8bl               1/1     Running     0               25h     10.104.15.58    4am-node20   <none>           <none>
yanliang-est-128cu-milvus-proxy-794dd75685-d7xkp               1/1     Running     0               25h     10.104.19.44    4am-node28   <none>           <none>
yanliang-est-128cu-milvus-querynode-ccbcf8ff6-7c29x            1/1     Running     0               25h     10.104.19.46    4am-node28   <none>           <none>
yanliang-est-128cu-milvus-querynode-ccbcf8ff6-gmq9k            1/1     Running     0               25h     10.104.12.46    4am-node17   <none>           <none>
yanliang-est-128cu-milvus-querynode-ccbcf8ff6-kqw9k            1/1     Running     1 (127m ago)    25h     10.104.6.124    4am-node13   <none>           <none>
yanliang-est-128cu-milvus-querynode-ccbcf8ff6-pv6gl            1/1     Running     0               169m    10.104.23.103   4am-node27   <none>           <none>
yanliang-est-128cu-milvus-querynode-ccbcf8ff6-wgjwb            1/1     Running     0               25h     10.104.13.226   4am-node16   <none>           <none>
yanliang-est-128cu-minio-0                                     1/1     Running     0               4d      10.104.23.156   4am-node27   <none>           <none>
yanliang-est-128cu-minio-1                                     1/1     Running     0               4d      10.104.20.154   4am-node22   <none>           <none>
yanliang-est-128cu-minio-2                                     1/1     Running     0               4d      10.104.17.31    4am-node23   <none>           <none>
yanliang-est-128cu-minio-3                                     1/1     Running     0               4d      10.104.24.136   4am-node29   <none>           <none>
yanliang-est-128cu-pulsar-bookie-0                             1/1     Running     0               4d      10.104.24.137   4am-node29   <none>           <none>
yanliang-est-128cu-pulsar-bookie-1                             1/1     Running     0               4d      10.104.19.222   4am-node28   <none>           <none>
yanliang-est-128cu-pulsar-bookie-2                             1/1     Running     0               4d      10.104.20.159   4am-node22   <none>           <none>
yanliang-est-128cu-pulsar-broker-0                             1/1     Running     0               4d      10.104.6.146    4am-node13   <none>           <none>
yanliang-est-128cu-pulsar-proxy-0                              1/1     Running     0               4d      10.104.24.125   4am-node29   <none>           <none>
yanliang-est-128cu-pulsar-recovery-0                           1/1     Running     0               4d      10.104.20.151   4am-node22   <none>           <none>
yanliang-est-128cu-pulsar-zookeeper-0                          1/1     Running     0               4d      10.104.19.214   4am-node28   <none>           <none>
yanliang-est-128cu-pulsar-zookeeper-1                          1/1     Running     0               4d      10.104.23.124   4am-node27   <none>           <none>
yanliang-est-128cu-pulsar-zookeeper-2                          1/1     Running     0               4d      10.104.15.194   4am-node20   <none>           <none>
```

**Comment by weiliu1031** [comment]
know issue, already fixed by @yah01 in branch 2.3,  see also #26322

**Comment by yah01** [comment]
I will try to fix this in 2.2, but the way to fix may be diff with 2.3 as the QueryNode had been re-implemented.

**Comment by ThreadDao** [comment]
@yah01 So far I have encountered this three times on the v2.2.15 version, please fix it as soon as possible

**Comment by yah01** [comment]
this bug happens with a small probability and under a special condition, the system could recover and the fix is not simple, which may introduce new problems due to the complexity of old QueryNode, I recommend to not fix this
