### ISSUE TITLE
Milvus standalone crashed

### ISSUE THREAD

**Issue by Shreyash-Chede** [milvus-io/milvus#28583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2-testing-20230824-615-gf1fc19e8a
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): RocksMQ (Default)   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu 22.04.3 LTS
- CPU/Memory: 19.5 GiB
- GPU: llvmpipe (LLVM 15.0.7, 256 bits)
- Others:
```

### Current Behavior

I've setup milvus standalone using git repo and when I execute the `./milvus run standalone` command in 'milvus/bin' directory, I get the error

 "../milvus run standalone
2023/11/20 08:37:21 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
Set runtime dir at /run/milvus failed, set it to /tmp/milvus directory

    __  _________ _   ____  ______    
   /  |/  /  _/ /| | / / / / / __/    
  / /|_/ // // /_| |/ / /_/ /\ \    
 /_/  /_/___/____/___/\____/___/     

Welcome to use Milvus!
Version:   v2.2-testing-20230824-615-gf1fc19e8a
Built:     Sat Nov 18 09:50:38 PM UTC 2023
GitCommit: f1fc19e8a
GoVersion: go version go1.18.1 linux/amd64

open pid file: /tmp/milvus/standalone.pid
lock pid file: /tmp/milvus/standalone.pid
[2023/11/20 08:37:21.864 -06:00] [INFO] [roles/roles.go:305] ["starting running Milvus components"]
[2023/11/20 08:37:21.868 -06:00] [DEBUG] [config/refresher.go:66] ["start refreshing configurations"] [source=FileSource]
[2023/11/20 08:37:21.868 -06:00] [DEBUG] [config/etcd_source.go:49] ["init etcd source"] [etcdInfo="{\"UseEmbed\":false,\"UseSSL\":false,\"Endpoints\":[\"localhost:2379\"],\"KeyPrefix\":\"by-dev\",\"CertFile\":\"/path/to/etcd-client.pem\",\"KeyFile\":\"/path/to/etcd-client-key.pem\",\"CaCertFile\":\"/path/to/ca.pem\",\"MinVersion\":\"1.3\",\"RefreshInterval\":5000000000}"]
[2023/11/20 08:37:21.868 -06:00] [INFO] [etcd/etcd_util.go:47] ["create etcd client"] [useEmbedEtcd=false] [useSSL=false] [endpoints="[localhost:2379]"] [minVersion=1.3]
[2023/11/20 08:37:21.868 -06:00] [DEBUG] [config/etcd_source.go:141] ["etcd refreshConfigurations"] [prefix=by-dev/config] [endpoints="[localhost:2379]"]
{"level":"warn","ts":"2023-11-20T08:37:24.869-0600","logger":"etcd-client","caller":"v3@v3.5.5/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000cc7c00/localhost:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:2379: connect: connection refused\""}
[2023/11/20 08:37:24.870 -06:00] [INFO] [config/manager.go:250] ["Get configuration by items failed"] [error="context deadline exceeded"]
.
.
.
.
goroutine 387 [select]:
runtime.gopark(0xc00150bf38?, 0x3?, 0x0?, 0x30?, 0xc00150befa?)
	/usr/lib/go-1.18/src/runtime/proc.go:361 +0xd6 fp=0xc00150bd40 sp=0xc00150bd20 pc=0x19ea636
runtime.selectgo(0xc00150bf38, 0xc00150bef4, 0x534dbe0?, 0x0, 0xc0005fab70?, 0x1)
	/usr/lib/go-1.18/src/runtime/select.go:328 +0x772 fp=0xc00150be80 sp=0xc00150bd40 pc=0x19fa532
google.golang.org/grpc.(*addrConn).resetTransport(0xc0001b5b80)
	/home/team-wang/go/pkg/mod/google.golang.org/grpc@v1.54.0/clientconn.go:1184 +0x3be fp=0xc00150bf78 sp=0xc00150be80 pc=0x20bb97e
google.golang.org/grpc.(*addrConn).connect(0xc0001b5b80)
	/home/team-wang/go/pkg/mod/google.golang.org/grpc@v1.54.0/clientconn.go:819 +0x187 fp=0xc00150bfc8 sp=0xc00150bf78 pc=0x20b98a7
google.golang.org/grpc.(*acBalancerWrapper).Connect.func2()
	/home/team-wang/go/pkg/mod/google.golang.org/grpc@v1.54.0/balancer_conn_wrappers.go:413 +0x26 fp=0xc00150bfe0 sp=0xc00150bfc8 pc=0x20b3cc6
runtime.goexit()
	/usr/lib/go-1.18/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00150bfe8 sp=0xc00150bfe0 pc=0x1a1d001
created by google.golang.org/grpc.(*acBalancerWrapper).Connect
	/home/team-wang/go/pkg/mod/google.golang.org/grpc@v1.54.0/balancer_conn_wrappers.go:413 +0xbc
Aborted (core dumped)
"

### Steps To Reproduce

```markdown
1. Git clone - https://github.com/milvus-io/milvus
2. Follow the developers guide and build milvus - https://github.com/milvus-io/milvus/blob/master/DEVELOPMENT.md
3. Change dir to `/milvus/bin`
4. Execute `./milvus run standalone`
```

**Comment by jiaoew1991** [comment]
@Shreyash-Chede  It seems that your etcd cannot be connected. Milvus is trying to connect to etcd at localhost:2379, but it fails.

**Comment by Shreyash-Chede** [comment]
> @Shreyash-Chede It seems that your etcd cannot be connected. Milvus is trying to connect to etcd at localhost:2379, but it fails.

Is the expected behavior - the etcd gets connected on execution of the milvus command? or is there any prerequisite that i should follow.

**Comment by Shreyash-Chede** [comment]
Update - I was successfully able to establish connection with etcd. Also i figured that i need to run the `./milvus run standalone` with root privilege so that i do not face - `Set runtime dir at /run/milvus failed, set it to /tmp/milvus directory`

Currently facing the below issue -

$ sudo ./milvus run standalone
2023/11/21 11:54:47 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined

    __  _________ _   ____  ______    
   /  |/  /  _/ /| | / / / / / __/    
  / /|_/ // // /_| |/ / /_/ /\ \    
 /_/  /_/___/____/___/\____/___/     

Welcome to use Milvus!
Version:   v2.2-testing-20230824-615-gf1fc19e8a
Built:     Sat Nov 18 09:50:38 PM UTC 2023
GitCommit: f1fc19e8a
GoVersion: go version go1.18.1 linux/amd64

open pid file: /run/milvus/standalone.pid
lock pid file: /run/milvus/standalone.pid
[2023/11/21 11:54:47.422 -06:00] [INFO] [roles/roles.go:305] ["starting running Milvus components"]
[2023/11/21 11:54:47.426 -06:00] [DEBUG] [config/refresher.go:66] ["start refreshing configurations"] [source=FileSource]
[2023/11/21 11:54:47.427 -06:00] [DEBUG] [config/etcd_source.go:49] ["init etcd source"] [etcdInfo="{\"UseEmbed\":false,\"UseSSL\":false,\"Endpoints\":[\"localhost:2379\"],\"KeyPrefix\":\"by-dev\",\"CertFile\":\"/path/to/etcd-client.pem\",\"KeyFile\":\"/path/to/etcd-client-key.pem\",\"CaCertFile\":\"/path/to/ca.pem\",\"MinVersion\":\"1.3\",\"RefreshInterval\":5000000000}"]
[2023/11/21 11:54:47.427 -06:00] [INFO] [etcd/etcd_util.go:47] ["create etcd client"] [useEmbedEtcd=false] [useSSL=false] [endpoints="[localhost:2379]"] [minVersion=1.3]
[2023/11/21 11:54:47.428 -06:00] [DEBUG] [config/etcd_source.go:141] ["etcd refreshConfigurations"] [prefix=by-dev/config] [endpoints="[localhost:2379]"]
[2023/11/21 11:54:47.430 -06:00] [DEBUG] [config/refresher.go:66] ["start refreshing configurations"] [source=EtcdSource]
[2023/11/21 11:54:47.435 -06:00] [INFO] [paramtable/hook_config.go:21] ["hook config"] [hook={}]
[2023/11/21 11:54:47.435 -06:00] [INFO] [roles/roles.go:254] [setupPrometheusHTTPServer]
[2023/11/21 11:54:47.435 -06:00] [DEBUG] [config/refresher.go:66] ["start refreshing configurations"] [source=FileSource]
[2023/11/21 11:54:47.435 -06:00] [INFO] [http/server.go:77] ["management listen"] [addr=:9091]
[2023/11/21 11:54:47.435 -06:00] [INFO] [rootcoord/root_coord.go:155] ["update rootcoord state"] [state=Abnormal]
[2023/11/21 11:54:47.435 -06:00] [DEBUG] [rootcoord/service.go:166] ["init params done.."]
[2023/11/21 11:54:47.435 -06:00] [INFO] [etcd/etcd_util.go:47] ["create etcd client"] [useEmbedEtcd=false] [useSSL=false] [endpoints="[localhost:2379]"] [minVersion=1.3]
[2023/11/21 11:54:47.436 -06:00] [INFO] [etcd/etcd_util.go:47] ["create etcd client"] [useEmbedEtcd=false] [useSSL=false] [endpoints="[localhost:2379]"] [minVersion=1.3]
[2023/11/21 11:54:47.436 -06:00] [INFO] [components/index_coord.go:38] ["IndexCoord running ..."]
[2023/11/21 11:54:47.436 -06:00] [DEBUG] [rootcoord/service.go:183] ["etcd connect done ..."]
[2023/11/21 11:54:47.436 -06:00] [DEBUG] [rootcoord/service.go:243] ["start grpc "] [port=53100]
[2023/11/21 11:54:47.436 -06:00] [INFO] [etcd/etcd_util.go:47] ["create etcd client"] [useEmbedEtcd=false] [useSSL=false] [endpoints="[localhost:2379]"] [minVersion=1.3]
[2023/11/21 11:54:47.437 -06:00] [DEBUG] [querynode/service.go:100] [QueryNode] [port=21123]
[2023/11/21 11:54:47.437 -06:00] [INFO] [etcd/etcd_util.go:47] ["create etcd client"] [useEmbedEtcd=false] [useSSL=false] [endpoints="[localhost:2379]"] [minVersion=1.3]
[2023/11/21 11:54:47.437 -06:00] [DEBUG] [querynode/service.go:117] ["QueryNode connect to etcd successfully"]
[2023/11/21 11:54:47.438 -06:00] [INFO] [etcd/etcd_util.go:47] ["create etcd client"] [useEmbedEtcd=false] [useSSL=false] [endpoints="[localhost:2379]"] [minVersion=1.3]
[2023/11/21 11:54:47.438 -06:00] [INFO] [datanode/service.go:246] ["DataNode address"] [address=10.0.2.15:21124]
[2023/11/21 11:54:47.438 -06:00] [DEBUG] [indexnode/indexnode.go:115] ["New IndexNode ..."]
[2023/11/21 11:54:47.438 -06:00] [DEBUG] [indexnode/service.go:87] [IndexNode] ["network address"=10.0.2.15:21121] ["network port: "=21121]
[2023/11/21 11:54:47.439 -06:00] [INFO] [proxy/lb_policy.go:78] ["use look_aside policy on replica selection"]
[2023/11/21 11:54:47.439 -06:00] [DEBUG] [proxy/multi_rate_limiter.go:188] ["RateLimiter register for rateType"] [rateType=DMLInsert] [rateLimit=+inf] [burst=1.7976931348623157e+308]
[2023/11/21 11:54:47.439 -06:00] [DEBUG] [proxy/multi_rate_limiter.go:188] ["RateLimiter register for rateType"] [rateType=DMLBulkLoad] [rateLimit=+inf] [burst=1.7976931348623157e+308]
[2023/11/21 11:54:47.439 -06:00] [DEBUG] [proxy/service.go:114] ["create a new Proxy instance"] [state=2]
[2023/11/21 11:54:47.439 -06:00] [DEBUG] [proxy/service.go:375] ["init Proxy server"]
[2023/11/21 11:54:47.439 -06:00] [DEBUG] [proxy/service.go:406] ["Proxy init service's parameter table done"]
[2023/11/21 11:54:47.439 -06:00] [DEBUG] [proxy/service.go:408] ["Proxy init http server's parameter table done"]
[2023/11/21 11:54:47.439 -06:00] [DEBUG] [proxy/service.go:415] ["init Proxy's parameter table done"] ["internal address"=10.0.2.15:19529] ["external address"=10.0.2.15:19530]
[2023/11/21 11:54:47.439 -06:00] [DEBUG] [proxy/service.go:418] ["init Proxy's tracer done"] ["service name"="Proxy ip: 10.0.2.15, port: 19530"]
[2023/11/21 11:54:47.439 -06:00] [INFO] [etcd/etcd_util.go:47] ["create etcd client"] [useEmbedEtcd=false] [useSSL=false] [endpoints="[localhost:2379]"] [minVersion=1.3]
[2023/11/21 11:54:47.439 -06:00] [DEBUG] [proxy/service.go:322] ["Proxy internal server listen on tcp"] [port=19529]
[2023/11/21 11:54:47.439 -06:00] [DEBUG] [proxy/service.go:329] ["Proxy internal server already listen on tcp"] [port=19529]
[2023/11/21 11:54:47.439 -06:00] [DEBUG] [proxy/service.go:361] ["create Proxy internal grpc server"] ["enforcement policy"="{\"MinTime\":5000000000,\"PermitWithoutStream\":true}"] ["server parameters"="{\"MaxConnectionIdle\":0,\"MaxConnectionAge\":0,\"MaxConnectionAgeGrace\":0,\"Time\":60000000000,\"Timeout\":10000000000}"]
[2023/11/21 11:54:47.439 -06:00] [INFO] [proxy/service.go:445] ["Proxy server listen on tcp"] [port=19530]
[2023/11/21 11:54:47.439 -06:00] [INFO] [proxy/service.go:449] ["Proxy server already listen on tcp"] [port=19530]
[2023/11/21 11:54:47.439 -06:00] [DEBUG] [proxy/service.go:232] ["Get proxy rate limiter done"] [port=19530]
[2023/11/21 11:54:47.439 -06:00] [DEBUG] [proxy/service.go:297] ["create Proxy grpc server"] ["enforcement policy"="{\"MinTime\":5000000000,\"PermitWithoutStream\":true}"] ["server parameters"="{\"MaxConnectionIdle\":0,\"MaxConnectionAge\":0,\"MaxConnectionAgeGrace\":0,\"Time\":60000000000,\"Timeout\":10000000000}"]
[2023/11/21 11:54:47.439 -06:00] [INFO] [proxy/service.go:527] ["register Proxy http server"]
[2023/11/21 11:54:47.436 -06:00] [DEBUG] [datacoord/service.go:147] ["network port"] [port=13333]
[2023/11/21 11:54:47.440 -06:00] [INFO] [runtime/asm_amd64.s:1571] ["Start check query node health loop"]
[2023/11/21 11:54:47.440 -06:00] [DEBUG] [proxy/service.go:534] ["create RootCoord client for Proxy"]
[2023/11/21 11:54:47.441 -06:00] [INFO] [etcd/etcd_util.go:47] ["create etcd client"] [useEmbedEtcd=false] [useSSL=false] [endpoints="[localhost:2379]"] [minVersion=1.3]
[2023/11/21 11:54:47.441 -06:00] [DEBUG] [sessionutil/session_util.go:254] ["Session try to connect to etcd"]
[2023/11/21 11:54:47.442 -06:00] [DEBUG] [sessionutil/session_util.go:269] ["Session connect to etcd success"]
[2023/11/21 11:54:47.442 -06:00] [DEBUG] [proxy/service.go:540] ["create RootCoord client for Proxy done"]
[2023/11/21 11:54:47.442 -06:00] [DEBUG] [proxy/service.go:543] ["Proxy wait for RootCoord to be healthy"]
[2023/11/21 11:54:47.442 -06:00] [WARN] [client/client.go:89] ["RootCoordClient mess key not exist"] [key=rootcoord]
[2023/11/21 11:54:47.442 -06:00] [WARN] [grpcclient/client.go:179] ["failed to get client address"] [error="find no available rootcoord, check rootcoord state"]
[2023/11/21 11:54:47.442 -06:00] [WARN] [grpcclient/client.go:513] ["fail to get grpc client"] [client_role=rootcoord] [error="find no available rootcoord, check rootcoord state"]
[2023/11/21 11:54:47.443 -06:00] [WARN] [retry/retry.go:44] ["grpc client is nil, maybe fail to get client in the retry state"] [client_role=rootcoord] [error="empty grpc client: find no available rootcoord, check rootcoord state"]
[2023/11/21 11:54:47.443 -06:00] [WARN] [client/client.go:89] ["RootCoordClient mess key not exist"] [key=rootcoord]
[2023/11/21 11:54:47.443 -06:00] [WARN] [grpcclient/client.go:179] ["failed to get client address"] [error="find no available rootcoord, check rootcoord state"]
[2023/11/21 11:54:47.443 -06:00] [WARN] [grpcclient/client.go:438] ["fail to get grpc client in the retry state"] [client_role=rootcoord] [error="find no available rootcoord, check rootcoord state"]
[2023/11/21 11:54:47.443 -06:00] [ERROR] [grpcclient/client.go:429] ["retry func failed"] ["retry time"=0] [error="empty grpc client: find no available rootcoord, check rootcoord state"] [stack="github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).call\n\t/home/team-wang/milvus/internal/util/grpcclient/client.go:429\ngithub.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call\n\t/home/team-wang/milvus/internal/util/grpcclient/client.go:513\ngithub.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n\t/home/team-wang/milvus/internal/util/grpcclient/client.go:529\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord/client.wrapGrpcCall[...]\n\t/home/team-wang/milvus/internal/distributed/rootcoord/client/client.go:106\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord/client.(*Client).GetComponentStates\n\t/home/team-wang/milvus/internal/distributed/rootcoord/client/client.go:120\ngithub.com/milvus-io/milvus/internal/util/componentutil.WaitForComponentStates[...].func1\n\t/home/team-wang/milvus/internal/util/componentutil/componentutil.go:37\ngithub.com/milvus-io/milvus/pkg/util/retry.Do\n\t/home/team-wang/milvus/pkg/util/retry/retry.go:44\ngithub.com/milvus-io/milvus/internal/util/componentutil.WaitForComponentStates[...]\n\t/home/team-wang/milvus/internal/util/componentutil/componentutil.go:61\ngithub.com/milvus-io/milvus/internal/util/componentutil.WaitForComponentHealthy[...]\n\t/home/team-wang/milvus/internal/util/componentutil/componentutil.go:82\ngithub.com/milvus-io/milvus/internal/distributed/proxy.(*Server).init\n\t/home/team-wang/milvus/internal/distributed/proxy/service.go:544\ngithub.com/milvus-io/milvus/internal/distributed/proxy.(*Server).Run\n\t/home/team-wang/milvus/internal/distributed/proxy/service.go:376\ngithub.com/milvus-io/milvus/cmd/components.(*Proxy).Run\n\t/home/team-wang/milvus/cmd/components/proxy.go:52\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/home/team-wang/milvus/cmd/roles/roles.go:114"]

**Comment by Shreyash-Chede** [comment]
> This is due to the dependency between other coord and rootcoord.
> 
> If rootcoord can not start in a period then the standalone may panic.
> 
> You cluster could be recovered after restart a couple of times.
> 
> try to use 2.2.15 because we fix some issues on restart. Or you can compile with latest 2.2.0 branch

Hi thanks, i have git checkout with 2.2.0 and compiled milvus again, I'm facing this error 

`./milvus: symbol lookup error: /home/team-wang/milvus/internal/core/output/lib/libmilvus_segcore.so: undefined symbol: _ZN8knowhere16prometheusClientE
`

Any idea how should i resolve it?

**Comment by jiaoew1991** [comment]
> > This is due to the dependency between other coord and rootcoord.
> > If rootcoord can not start in a period then the standalone may panic.
> > You cluster could be recovered after restart a couple of times.
> > try to use 2.2.15 because we fix some issues on restart. Or you can compile with latest 2.2.0 branch
> 
> Hi thanks, i have git checkout with 2.2.0 and compiled milvus again, I'm facing this error
> 
> `./milvus: symbol lookup error: /home/team-wang/milvus/internal/core/output/lib/libmilvus_segcore.so: undefined symbol: _ZN8knowhere16prometheusClientE `
> 
> Any idea how should i resolve it?

did you try `make clean`?

**Comment by Shreyash-Chede** [comment]
> > > This is due to the dependency between other coord and rootcoord.
> > > If rootcoord can not start in a period then the standalone may panic.
> > > You cluster could be recovered after restart a couple of times.
> > > try to use 2.2.15 because we fix some issues on restart. Or you can compile with latest 2.2.0 branch
> > 
> > 
> > Hi thanks, i have git checkout with 2.2.0 and compiled milvus again, I'm facing this error
> > `./milvus: symbol lookup error: /home/team-wang/milvus/internal/core/output/lib/libmilvus_segcore.so: undefined symbol: _ZN8knowhere16prometheusClientE `
> > Any idea how should i resolve it?
> 
> did you try `make clean`?

Hi, thanks after 'make clean', its showing the port is already in used, even after killing the process using `sudo kill <PID> `
I get the same error - 

sudo kill 15906
team-wang@VDB-database:~/milvus/bin$ sudo ./milvus run standalone
2023/11/29 12:20:09 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined

    __  _________ _   ____  ______    
   /  |/  /  _/ /| | / / / / / __/    
  / /|_/ // // /_| |/ / /_/ /\ \    
 /_/  /_/___/____/___/\____/___/     

Welcome to use Milvus!
Version:   v2.2-testing-20230824-687-g9c46788d8
Built:     Wed Nov 29 05:32:12 PM UTC 2023
GitCommit: 9c46788d8
GoVersion: go version go1.21.4 linux/amd64

open pid file: /run/milvus/standalone.pid
lock pid file: /run/milvus/standalone.pid
[2023/11/29 12:20:09.682 -06:00] [INFO] [roles/roles.go:305] ["starting running Milvus components"]
[2023/11/29 12:20:09.686 -06:00] [DEBUG] [config/refresher.go:66] ["start refreshing configurations"] [source=FileSource]
[2023/11/29 12:20:09.686 -06:00] [DEBUG] [config/etcd_source.go:49] ["init etcd source"] [etcdInfo="{\"UseEmbed\":false,\"UseSSL\":false,\"Endpoints\":[\"localhost:2379\"],\"KeyPrefix\":\"by-dev\",\"CertFile\":\"/path/to/etcd-client.pem\",\"KeyFile\":\"/path/to/etcd-client-key.pem\",\"CaCertFile\":\"/path/to/ca.pem\",\"MinVersion\":\"1.3\",\"RefreshInterval\":5000000000}"]
[2023/11/29 12:20:09.686 -06:00] [INFO] [etcd/etcd_util.go:47] ["create etcd client"] [useEmbedEtcd=false] [useSSL=false] [endpoints="[localhost:2379]"] [minVersion=1.3]
[2023/11/29 12:20:09.687 -06:00] [DEBUG] [config/etcd_source.go:141] ["etcd refreshConfigurations"] [prefix=by-dev/config] [endpoints="[localhost:2379]"]
[2023/11/29 12:20:09.690 -06:00] [DEBUG] [config/refresher.go:66] ["start refreshing configurations"] [source=EtcdSource]
[2023/11/29 12:20:09.691 -06:00] [INFO] [paramtable/hook_config.go:21] ["hook config"] [hook={}]
[2023/11/29 12:20:09.691 -06:00] [DEBUG] [config/refresher.go:66] ["start refreshing configurations"] [source=FileSource]
[2023/11/29 12:20:09.691 -06:00] [INFO] [roles/roles.go:254] [setupPrometheusHTTPServer]
[2023/11/29 12:20:09.691 -06:00] [INFO] [rootcoord/root_coord.go:155] ["update rootcoord state"] [state=Abnormal]
[2023/11/29 12:20:09.691 -06:00] [DEBUG] [rootcoord/service.go:166] ["init params done.."]
[2023/11/29 12:20:09.691 -06:00] [INFO] [etcd/etcd_util.go:47] ["create etcd client"] [useEmbedEtcd=false] [useSSL=false] [endpoints="[localhost:2379]"] [minVersion=1.3]
[2023/11/29 12:20:09.691 -06:00] [INFO] [http/server.go:88] ["management listen"] [addr=:9091]
[2023/11/29 12:20:09.692 -06:00] [DEBUG] [rootcoord/service.go:183] ["etcd connect done ..."]
[2023/11/29 12:20:09.692 -06:00] [DEBUG] [rootcoord/service.go:243] ["start grpc "] [port=53100]
[2023/11/29 12:20:09.692 -06:00] [ERROR] [http/server.go:91] ["handle metrics failed"] [error="listen tcp :9091: bind: address already in use"] [stack="github.com/milvus-io/milvus/internal/http.ServeHTTP.func1\n\t/home/team-wang/milvus/internal/http/server.go:91"]
[2023/11/29 12:20:09.692 -06:00] [ERROR] [rootcoord/service.go:246] ["GrpcServer:failed to listen"] [error="listen tcp :53100: bind: address already in use"] [stack="github.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).startGrpcLoop\n\t/home/team-wang/milvus/internal/distributed/rootcoord/service.go:246"]
[2023/11/29 12:20:09.692 -06:00] [INFO] [components/index_coord.go:38] ["IndexCoord running ..."]
[2023/11/29 12:20:09.692 -06:00] [ERROR] [components/root_coord.go:53] ["RootCoord starts error"] [error="listen tcp :53100: bind: address already in use"] [stack="github.com/milvus-io/milvus/cmd/components.(*RootCoord).Run\n\t/home/team-wang/milvus/cmd/components/root_coord.go:53\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/home/team-wang/milvus/cmd/roles/roles.go:114"]
[2023/11/29 12:20:09.692 -06:00] [INFO] [etcd/etcd_util.go:47] ["create etcd client"] [useEmbedEtcd=false] [useSSL=false] [endpoints="[localhost:2379]"] [minVersion=1.3]
panic: listen tcp :53100: bind: address already in use

goroutine 166 [running]:
panic({0x4d21820?, 0xc00148b0e0?})
	/usr/local/go/src/runtime/panic.go:1017 +0x3ac fp=0xc0014b3f58 sp=0xc0014b3ea8 pc=0x1b8054c
github.com/milvus-io/milvus/cmd/roles.runComponent[...].func1()
	/home/team-wang/milvus/cmd/roles/roles.go:115 +0x188 fp=0xc0014b3fe0 sp=0xc0014b3f58 pc=0x475c1e8
runtime.goexit()

**Comment by xiaofan-luan** [comment]
panic: listen tcp :53100: bind: address already in use

port is already used 
you need to check which process use the pod.
I guess you try to deploy multiple milvus cluster on same machine

**Comment by 18660598544** [comment]
how to fix that coundn't connect etcd

**Comment by xiaofan-luan** [comment]
> how to fix that coundn't connect etcd

please open another issue with detailed description and  your logs
