### ISSUE TITLE
[Bug]: [Nightly]Search failed reporting `The binlog params is not generate` with milvus panic

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#28591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20231120-e88bbaac-amd64
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Search failed reporting `The binlog params is not generate` with milvus panic.

```
[2023-11-20T20:04:40.570Z] [2023-11-20 19:38:41 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=65538, message=failed to search: attempt #0: failed to search/query delegator 4 for channel by-dev-rootcoord-dml_13_445776780404978059v0: fail to Search, QueryNode ID=4, reason=worker(6) query failed: UnknownError: Assert "vec_binlog_config_.find(field_id) != vec_binlog_config_.end()" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:642
[2023-11-20T20:04:40.570Z]  => The binlog params is not generate.: attempt #1: no available shard delegator found: service unavailable)>, <Time:{'RPC start': '2023-11-20 19:38:40.703649', 'RPC error': '2023-11-20 19:38:41.734307'}> (decorators.py:128)
[2023-11-20T20:04:40.570Z] [2023-11-20 19:38:41 - ERROR - ci_test]: Traceback (most recent call last):
[2023-11-20T20:04:40.570Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper
[2023-11-20T20:04:40.570Z]     res = func(*args, **_kwargs)
[2023-11-20T20:04:40.570Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request
[2023-11-20T20:04:40.570Z]     return func(*arg, **kwargs)
[2023-11-20T20:04:40.570Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 783, in search
[2023-11-20T20:04:40.570Z]     resp = conn.search(
[2023-11-20T20:04:40.570Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 129, in handler
[2023-11-20T20:04:40.570Z]     raise e from e
[2023-11-20T20:04:40.570Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 125, in handler
[2023-11-20T20:04:40.570Z]     return func(*args, **kwargs)
[2023-11-20T20:04:40.570Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 164, in handler
[2023-11-20T20:04:40.570Z]     return func(self, *args, **kwargs)
[2023-11-20T20:04:40.570Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 104, in handler
[2023-11-20T20:04:40.570Z]     raise e from e
[2023-11-20T20:04:40.570Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 68, in handler
[2023-11-20T20:04:40.570Z]     return func(*args, **kwargs)
[2023-11-20T20:04:40.570Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 781, in search
[2023-11-20T20:04:40.570Z]     return self._execute_search(request, timeout, round_decimal=round_decimal, **kwargs)
[2023-11-20T20:04:40.570Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 742, in _execute_search
[2023-11-20T20:04:40.570Z]     raise e from e
[2023-11-20T20:04:40.570Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 734, in _execute_search
[2023-11-20T20:04:40.570Z]     raise MilvusException(response.status.code, response.status.reason)
[2023-11-20T20:04:40.570Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=65538, message=failed to search: attempt #0: failed to search/query delegator 4 for channel by-dev-rootcoord-dml_13_445776780404978059v0: fail to Search, QueryNode ID=4, reason=worker(6) query failed: UnknownError: Assert "vec_binlog_config_.find(field_id) != vec_binlog_config_.end()" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:642
[2023-11-20T20:04:40.570Z]  => The binlog params is not generate.: attempt #1: no available shard delegator found: service unavailable)>
[2023-11-20T20:04:40.570Z]  (api_request.py:45)
[2023-11-20T20:04:40.570Z] [2023-11-20 19:38:41 - ERROR - ci_test]: (api_response) : <MilvusException: (code=65538, message=failed to search: attempt #0: failed to search/query delegator 4 for channel by-dev-rootcoord-dml_13_445776780404978059v0: fail to Search, QueryNode ID=4, reason=worker(6) query failed: UnknownError: Assert "vec_binlog_config_.find(field_id) != vec_binlog_confi...... (api_request.py:46)
```

### Expected Behavior

pass

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/565/pipeline/237/
2. log: [artifacts-milvus-distributed-pulsar-nightly-565-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/565/artifact/artifacts-milvus-distributed-pulsar-nightly-565-pymilvus-e2e-logs.tar.gz)
3. failed time: [2023-11-20T19:38:42.030Z] [gw5] [ 77%] FAILED testcases/test_search.py::TestSearchPagination::test_search_pagination_with_expression[0-False-False-int64 not in [1, 2, 3]] 
4. collection name: search_collection_Os4cb8RX
5. error pod: [2023-11-20T20:04:57.037Z] mdp-565-n-milvus-querynode-6fcbd946df-wz4mw      1/1     Running       1 (20m ago)    125m   10.105.7.247   ci-node12   <none>           <none>
6. panic log:
```
2023-11-21T03:43:56.155146556+08:00 stdout F [2023/11/20 19:43:56.155 +00:00] [INFO] [querynodev2/services.go:592] ["start to release segments"] [traceID=b579fd210731f6a4a58ab4e7a417a1a9] [collectionID=445776780405584949] [shard=by-dev-rootcoord-dml_7_445776780405584949v0] [segmentIDs="[445776780405585003]"] [currentNodeID=6]
2023-11-21T03:43:56.155342555+08:00 stderr F fatal error: unexpected signal during runtime execution
2023-11-21T03:43:56.157525638+08:00 stderr F [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7ff3269dbc1e]
2023-11-21T03:43:56.157535677+08:00 stderr F
2023-11-21T03:43:56.157539547+08:00 stderr F runtime stack:
2023-11-21T03:43:56.157543596+08:00 stderr F runtime.throw({0x4ea6333?, 0x0?})
2023-11-21T03:43:56.157552455+08:00 stderr F    /usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7fe8ec800370 sp=0x7fe8ec800340 pc=0x19ad09d
2023-11-21T03:43:56.157556962+08:00 stderr F runtime.sigpanic()
2023-11-21T03:43:56.157565852+08:00 stderr F    /usr/local/go/src/runtime/signal_unix.go:825 +0x3e9 fp=0x7fe8ec8003d0 sp=0x7fe8ec800370 pc=0x19c4f09
2023-11-21T03:43:56.157569509+08:00 stderr F
2023-11-21T03:43:56.157576988+08:00 stderr F goroutine 314863 [syscall]:
2023-11-21T03:43:56.157590848+08:00 stderr F atomic_load_p
2023-11-21T03:43:56.157608629+08:00 stderr F    include/jemalloc/internal/atomic.h:62 pc=0x7ff3269dbc1e
2023-11-21T03:43:56.157620418+08:00 stderr F extent_arena_get
2023-11-21T03:43:56.157636081+08:00 stderr F    include/jemalloc/internal/extent_inlines.h:51 pc=0x7ff3269dbc1e
2023-11-21T03:43:56.157641359+08:00 stderr F je_large_dalloc
2023-11-21T03:43:56.157648336+08:00 stderr F    src/large.c:361 pc=0x7ff3269dbc1e
2023-11-21T03:43:56.157657005+08:00 stderr F arena_dalloc_large
2023-11-21T03:43:56.157661442+08:00 stderr F    include/jemalloc/internal/arena_inlines_b.h:281 pc=0x7ff3269939fc
2023-11-21T03:43:56.157664781+08:00 stderr F arena_dalloc
2023-11-21T03:43:56.157671867+08:00 stderr F    include/jemalloc/internal/arena_inlines_b.h:323 pc=0x7ff3269939fc
2023-11-21T03:43:56.15767584+08:00 stderr F idalloctm
2023-11-21T03:43:56.15768202+08:00 stderr F     include/jemalloc/internal/jemalloc_internal_inlines_c.h:118 pc=0x7ff3269939fc
2023-11-21T03:43:56.157686104+08:00 stderr F ifree
2023-11-21T03:43:56.157692765+08:00 stderr F    src/jemalloc.c:2589 pc=0x7ff3269939fc
2023-11-21T03:43:56.157697014+08:00 stderr F je_free_default
```

**Comment by NicoYuan1986** [comment]
not reproduced for a month. 95ada1b
