### ISSUE TITLE
[Bug]: Load timeout after recovered from indexnode pod failure chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#28637]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3-20231121-558e3012-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka): kafka   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2023-11-22T01:26:28.884Z] [2023-11-22 01:22:59 - DEBUG - ci_test]: (api_request)  : [Connections.connect] args: ['default', '', '', ''], kwargs: {'host': '10.255.212.74', 'port': 19530} (api_request.py:62)

[2023-11-22T01:26:28.884Z] [2023-11-22 01:22:59 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-11-22T01:26:28.884Z] [2023-11-22 01:22:59 - DEBUG - ci_test]: (api_request)  : [Connections.has_connection] args: ['default'], kwargs: {} (api_request.py:62)

[2023-11-22T01:26:28.884Z] [2023-11-22 01:22:59 - DEBUG - ci_test]: (api_response) : True  (api_request.py:37)

[2023-11-22T01:26:28.884Z] [2023-11-22 01:22:59 - DEBUG - ci_test]: (api_request)  : [Collection] args: ['Checker__unz7DFMW', {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}, {'name': 'varchar', 'description': '', 'type': <DataType......, kwargs: {'consistency_level': 'Strong'} (api_request.py:62)

[2023-11-22T01:26:28.884Z] [2023-11-22 01:22:59 - DEBUG - ci_test]: (api_response) : <Collection>:

[2023-11-22T01:26:28.884Z] -------------

[2023-11-22T01:26:28.884Z] <name>: Checker__unz7DFMW

[2023-11-22T01:26:28.884Z] <description>: 

[2023-11-22T01:26:28.884Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}......  (api_request.py:37)

[2023-11-22T01:26:28.884Z] [2023-11-22 01:22:59 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2023-11-22T01:26:28.884Z] [2023-11-22 01:23:00 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-11-22T01:26:28.884Z] [2023-11-22 01:23:00 - DEBUG - ci_test]: (api_request)  : [Collection.compact] args: [180], kwargs: {} (api_request.py:62)

[2023-11-22T01:26:28.884Z] [2023-11-22 01:23:00 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-11-22T01:26:28.884Z] [2023-11-22 01:23:06 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2023-11-22T01:26:28.884Z] [2023-11-22 01:23:07 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-11-22T01:26:28.884Z] [2023-11-22 01:23:08 - INFO - ci_test]: assert create collection: 0.007910013198852539, init_entities: 9000 (test_all_collections_after_chaos.py:49)

[2023-11-22T01:26:28.884Z] [2023-11-22 01:23:08 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [[[-3000, -2999, -2998, -2997, -2996, -2995, -2994, -2993, -2992, -2991, -2990, -2989, -2988, -2987, -2986, -2985, -2984, -2983, -2982, -2981, -2980, -2979, -2978, -2977, -2976, -2975, -2974, -2973, -2972, -2971, -2970, -2969, -2968, -2967, -2966, -2965, -2964, -2963, -2962, -2961, -2960, -2959, -29......, kwargs: {'timeout': 180} (api_request.py:62)

[2023-11-22T01:26:28.885Z] [2023-11-22 01:23:08 - DEBUG - ci_test]: (api_response) : (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 445806330185252865, success count: 2000, err count: 0)  (api_request.py:37)

[2023-11-22T01:26:28.885Z] [2023-11-22 01:23:08 - INFO - ci_test]: assert insert: 0.2055189609527588 (test_all_collections_after_chaos.py:61)

[2023-11-22T01:26:28.885Z] [2023-11-22 01:23:08 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2023-11-22T01:26:28.885Z] [2023-11-22 01:23:11 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-11-22T01:26:28.885Z] [2023-11-22 01:23:11 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2023-11-22T01:26:28.885Z] [2023-11-22 01:23:11 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-11-22T01:26:28.885Z] [2023-11-22 01:23:11 - INFO - ci_test]: assert flush: 2.5469563007354736, entities: 11000 (test_all_collections_after_chaos.py:71)

[2023-11-22T01:26:28.885Z] [2023-11-22 01:23:11 - INFO - ci_test]: index info: [{'collection': 'Checker__unz7DFMW', 'field': 'float_vector', 'index_name': 'index__1palaGzr', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}] (test_all_collections_after_chaos.py:87)

[2023-11-22T01:26:28.885Z] [2023-11-22 01:23:11 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 180], kwargs: {} (api_request.py:62)

[2023-11-22T01:26:28.885Z] [2023-11-22 01:26:11 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=wait for loading collection timeout, collection: Checker__unz7DFMW)>, <Time:{'RPC start': '2023-11-22 01:23:11.904668', 'RPC error': '2023-11-22 01:26:11.934360'}> (decorators.py:128)

[2023-11-22T01:26:28.885Z] [2023-11-22 01:26:11 - WARNING - pymilvus.decorators]: Retry timeout: 180s (decorators.py:94)

[2023-11-22T01:26:28.885Z] [2023-11-22 01:26:11 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for loading collection timeout, collection: Checker__unz7DFMW)>, <Time:{'RPC start': '2023-11-22 01:23:11.889860', 'RPC error': '2023-11-22 01:26:11.935048'}> (decorators.py:128)

[2023-11-22T01:26:28.885Z] [2023-11-22 01:26:11 - ERROR - ci_test]: Traceback (most recent call last):

[2023-11-22T01:26:28.885Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2023-11-22T01:26:28.885Z]     res = func(*args, **_kwargs)

[2023-11-22T01:26:28.885Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2023-11-22T01:26:28.885Z]     return func(*arg, **kwargs)

[2023-11-22T01:26:28.885Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 420, in load

[2023-11-22T01:26:28.885Z]     conn.load_collection(

[2023-11-22T01:26:28.885Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 129, in handler

[2023-11-22T01:26:28.885Z]     raise e from e

[2023-11-22T01:26:28.885Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 125, in handler

[2023-11-22T01:26:28.885Z]     return func(*args, **kwargs)

[2023-11-22T01:26:28.885Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 164, in handler

[2023-11-22T01:26:28.885Z]     return func(self, *args, **kwargs)

[2023-11-22T01:26:28.885Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 95, in handler

[2023-11-22T01:26:28.885Z]     raise MilvusException(

[2023-11-22T01:26:28.885Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for loading collection timeout, collection: Checker__unz7DFMW)>

[2023-11-22T01:26:28.885Z]  (api_request.py:45)

[2023-11-22T01:26:28.885Z] [2023-11-22 01:26:11 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for loading collection timeout, collection: Checker__unz7DFMW)> (api_request.py:46)
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-for-release-cron/detail/chaos-test-kafka-for-release-cron/8496/pipeline

log:
[artifacts-indexnode-pod-failure-8496-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/13432938/artifacts-indexnode-pod-failure-8496-pytest-logs.tar.gz)
[artifacts-indexnode-pod-failure-8496-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/13432939/artifacts-indexnode-pod-failure-8496-server-logs.tar.gz)

**Comment by zhuwenxing** [comment]
image tag: 2.3-20231126-3b06db1d-amd64

It also happened in the datanode pod failure chaos test.
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-for-release-cron/detail/chaos-test-for-release-cron/8394/pipeline

log:
[artifacts-datanode-pod-kill-8394-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/13469913/artifacts-datanode-pod-kill-8394-pytest-logs.tar.gz)
[artifacts-datanode-pod-kill-8394-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/13469914/artifacts-datanode-pod-kill-8394-server-logs.tar.gz)

**Comment by yah01** [comment]
@aoiasd #28652 won't fix this, but I believe this has been fixed by #28719 @zhuwenxing

**Comment by zhuwenxing** [comment]
not reproduced in 2.3-20231205-3d7bcb5e-amd64
