### ISSUE TITLE
[Bug]: Deploy milvus cluster but mixcoord panic: Failed to create producer xxx-dml_0

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#28675]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20231122-af18aa70
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. deploy milvus release `delete-partition-key` with milvus-operator manifests:
```
  components:
    dataNode:
      paused: false
      replicas: 2
      resources: ...
    disableMetric: false
    image: harbor.milvus.io/milvus/milvus:master-20231122-af18aa70
    imageUpdateMode: rollingUpgrade
    indexNode:
      paused: false
      replicas: 1
      resources: ...
    metricInterval: ""
    mixCoord:
      paused: false
      replicas: 1
      resources: ...
    paused: false
    proxy:
      paused: false
      resources: ...
      serviceType: ClusterIP
    queryNode:
      paused: false
      replicas: 2
      resources: ...
  config:
    log:
      level: debug
```
2. mixcoord panic
[mixcoord_pre.log](https://github.com/milvus-io/milvus/files/13445709/mixcoord_pre.log)

```
[2023/11/23 02:50:46.264 +00:00] [WARN] [grpcclient/client.go:179] ["failed to get client address"] [error="find no available rootcoord, check rootcoord state"]
[2023/11/23 02:50:46.264 +00:00] [WARN] [grpcclient/client.go:438] ["fail to get grpc client in the retry state"] [client_role=rootcoord] [error="find no available rootcoord, check rootcoord state"]
panic: Failed to create producer delete-partition-key-rootcoord-dml_0, error = attempt #0: strconv.Atoi: parsing "dml_0": invalid syntax: attempt #1: strconv.Atoi: parsing "dml_0": invalid syntax: attempt #2: strconv.Atoi: parsing "dml_0": invalid syntax: attempt #3: strconv.Atoi: parsing "dml_0": invalid syntax: attempt #4: strconv.Atoi: parsing "dml_0": invalid syntax: attempt #5: strconv.Atoi: parsing "dml_0": invalid syntax: attempt #6: strconv.Atoi: parsing "dml_0": invalid syntax: attempt #7: strconv.Atoi: parsing "dml_0": invalid syntax: attempt #8: strconv.Atoi: parsing "dml_0": invalid syntax: attempt #9: strconv.Atoi: parsing "dml_0": invalid syntax: attempt #10: strconv.Atoi: parsing "dml_0": invalid syntax: attempt #11: strconv.Atoi: parsing "dml_0": invalid syntax: attempt #12: strconv.Atoi: parsing "dml_0": invalid syntax: attempt #13: strconv.Atoi: parsing "dml_0": invalid syntax: attempt #14: strconv.Atoi: parsing "dml_0": invalid syntax: attempt #15: strconv.Atoi: parsing "dml_0": invalid syntax: attempt #16: strconv.Atoi: parsing "dml_0": invalid syntax: attempt #17: strconv.Atoi: parsing "dml_0": invalid syntax: attempt #18: strconv.Atoi: parsing "dml_0": invalid syntax: attempt #19: strconv.Atoi: parsing "dml_0": invalid syntax

goroutine 269 [running]:
panic({0x46f4ca0, 0xc002193290})
    /usr/local/go/src/runtime/panic.go:987 +0x3bb fp=0xc00070d488 sp=0xc00070d3c8 pc=0x19adc5b
github.com/milvus-io/milvus/pkg/mq/msgstream.(*mqMsgStream).AsProducer(0xc001276d00, {0xc0011cdfc0?, 0x1, 0xc00070d5a0?})
    /go/src/github.com/milvus-io/milvus/pkg/mq/msgstream/mq_msgstream.go:141 +0x219 fp=0xc00070d560 sp=0xc00070d488 pc=0x36ab7f9
github.com/milvus-io/milvus/internal/rootcoord.newDmlChannels({0x53bd6b8?, 0xc0007fbae0}, {0x7fce4db25108, 0xc000869b00}, {0xc0012b4840, 0x22}, 0x10)
    /go/src/github.com/milvus-io/milvus/internal/rootcoord/dml_channels.go:201 +0x472 fp=0xc00070d880 sp=0xc00070d560 pc=0x435e992
github.com/milvus-io/milvus/internal/rootcoord.newTimeTickSync({0x53bd6b8?, 0xc0007fbae0}, 0x80, {0x7fce4db25108, 0xc000869b00}, 0xc001116980?)
    /go/src/github.com/milvus-io/milvus/internal/rootcoord/timeticksync.go:121 +0xd5 fp=0xc00070da50 sp=0xc00070d880 pc=0x43c4355
github.com/milvus-io/milvus/internal/rootcoord.(*Core).initInternal(0xc000785200)
    /go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:471 +0x1a5 fp=0xc00070db88 sp=0xc00070da50 pc=0x4398ca5
github.com/milvus-io/milvus/internal/rootcoord.(*Core).Init.func2()
    /go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:541 +0x26 fp=0xc00070dba8 sp=0xc00070db88 pc=0x43997a6
sync.(*Once).doSlow(0xc000785200?, 0x1f9586b?)
    /usr/local/go/src/sync/once.go:74 +0xc2 fp=0xc00070dc08 sp=0xc00070dba8 pc=0x1a08ac2
sync.(*Once).Do(...)
```

### Steps To Reproduce

```markdown
- 4am argo: https://argo-workflows.zilliz.cc/archived-workflows/qa/753d2268-e4bd-49d0-8f24-e6f5aecdfe40?nodeId=test-delete-stable-partition-key-1
```

### Milvus Log

4am pods:
```
delete-partition-key-etcd-0                                       1/1     Running                  0                 9h
delete-partition-key-etcd-1                                       1/1     Running                  0                 9h
delete-partition-key-etcd-2                                       1/1     Running                  0                 9h
delete-partition-key-milvus-datanode-6fc5cc8655-rwhtr             0/1     Running                  72 (3m47s ago)    9h
delete-partition-key-milvus-datanode-6fc5cc8655-vnbxh             0/1     Running                  72 (2m47s ago)    9h
delete-partition-key-milvus-indexnode-75cd49dc45-89ntd            1/1     Running                  0                 9h
delete-partition-key-milvus-mixcoord-695bcb5788-hm2kv             0/1     CrashLoopBackOff         126 (2m48s ago)   9h
delete-partition-key-milvus-proxy-8498d9c848-z9zgx                0/1     Running                  72 (3m37s ago)    9h
delete-partition-key-milvus-querynode-6996d98b85-7l9jq            1/1     Running                  0                 9h
delete-partition-key-milvus-querynode-6996d98b85-f624n            1/1     Running                  0                 9h
delete-partition-key-minio-0                                      1/1     Running                  0                 9h
delete-partition-key-minio-1                                      1/1     Running                  0                 9h
delete-partition-key-minio-2                                      1/1     Running                  0                 9h
delete-partition-key-minio-3                                      1/1     Running                  0                 9h
delete-partition-key-pulsar-bookie-0                              1/1     Running                  0                 9h
delete-partition-key-pulsar-bookie-1                              1/1     Running                  0                 9h
delete-partition-key-pulsar-bookie-2                              1/1     Running                  0                 9h
delete-partition-key-pulsar-bookie-init-9b5vn                     0/1     Completed                0                 9h
delete-partition-key-pulsar-broker-0                              1/1     Running                  0                 9h
delete-partition-key-pulsar-proxy-0                               1/1     Running                  0                 9h
delete-partition-key-pulsar-pulsar-init-fwfds                     0/1     Completed                0                 9h
delete-partition-key-pulsar-recovery-0                            1/1     Running                  0                 9h
delete-partition-key-pulsar-zookeeper-0                           1/1     Running                  0                 9h
delete-partition-key-pulsar-zookeeper-1                           1/1     Running                  0                 9h
delete-partition-key-pulsar-zookeeper-2                           1/1     Running                  0                 9h
```

**Comment by sunby** [comment]
Congrats! You found a corner case about parsing pulsar topic name.
Our topic name is delete-partition-key-rootcoord-dml_0. But pulsar go client check the '-partition-' string and parse strings after it as int and it panic. https://github.com/milvus-io/pulsar-client-go/blob/f5676b940f6029cf0a34a612b1f843bf5bdac076/pulsar/internal/topic_name.go#L120

So dont use '-partition' or '-partition-' as part of our topic name.

**Comment by ThreadDao** [comment]
After fixed: mixcoord panic with the following logs
```
[2023/11/24 04:03:06.756 +00:00] [DEBUG] [datacoord/service.go:252] ["DataCoord init done ..."]
[2023/11/24 04:03:06.756 +00:00] [DEBUG] [sessionutil/session_util.go:433] ["service begin to register to etcd"] [serverName=indexcoord] [ServerID=16]
[2023/11/24 04:03:06.758 +00:00] [INFO] [rootcoord/meta_table.go:204] ["RootCoord meta table reload done"] [duration=14.981972ms]
panic: channel name can not contains '-partition-'

goroutine 241 [running]:
panic({0x479a3a0, 0x5446230})
    /usr/local/go/src/runtime/panic.go:987 +0x3bb fp=0xc0015b5798 sp=0xc0015b56d8 pc=0x19ebc5b
github.com/milvus-io/milvus/pkg/util/paramtable.(*commonConfig).init.func1({0xc00133d090, 0xd})
    /go/src/github.com/milvus-io/milvus/pkg/util/paramtable/component_param.go:245 +0xd5 fp=0xc0015b5810 sp=0xc0015b5798 pc=0x279c3b5
github.com/milvus-io/milvus/pkg/util/paramtable.(*ParamItem).get(0x72fc548)
```
