### ISSUE TITLE
[Bug]: [Nightly] Load collection failed for timeout after upsert 10 times

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#28707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20231123-53646032
- Deployment mode(standalone or cluster): cluster & standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.3
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Load collection failed for timeout after upsert 10 times.
```
[2023-11-23T19:59:36.992Z] [2023-11-23 18:19:44 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 180], kwargs: {} (api_request.py:62)
[2023-11-23T19:59:36.992Z] [2023-11-23 18:22:45 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=wait for loading collection timeout, collection: upsert_XYcukym2)>, <Time:{'RPC start': '2023-11-23 18:19:44.708164', 'RPC error': '2023-11-23 18:22:45.171210'}> (decorators.py:128)
[2023-11-23T19:59:36.992Z] [2023-11-23 18:22:45 - WARNING - pymilvus.decorators]: [93mRetry timeout: 180s[0m (decorators.py:94)
[2023-11-23T19:59:36.992Z] [2023-11-23 18:22:45 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for loading collection timeout, collection: upsert_XYcukym2)>, <Time:{'RPC start': '2023-11-23 18:19:44.602554', 'RPC error': '2023-11-23 18:22:45.171648'}> (decorators.py:128)
[2023-11-23T19:59:36.992Z] [2023-11-23 18:22:45 - ERROR - ci_test]: Traceback (most recent call last):
[2023-11-23T19:59:36.992Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper
[2023-11-23T19:59:36.992Z]     res = func(*args, **_kwargs)
[2023-11-23T19:59:36.992Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request
[2023-11-23T19:59:36.992Z]     return func(*arg, **kwargs)
[2023-11-23T19:59:36.992Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 420, in load
[2023-11-23T19:59:36.992Z]     conn.load_collection(
[2023-11-23T19:59:36.992Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 129, in handler
[2023-11-23T19:59:36.992Z]     raise e from e
[2023-11-23T19:59:36.992Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 125, in handler
[2023-11-23T19:59:36.993Z]     return func(*args, **kwargs)
[2023-11-23T19:59:36.993Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 164, in handler
[2023-11-23T19:59:36.993Z]     return func(self, *args, **kwargs)
[2023-11-23T19:59:36.993Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 95, in handler
[2023-11-23T19:59:36.993Z]     raise MilvusException(
[2023-11-23T19:59:36.993Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for loading collection timeout, collection: upsert_XYcukym2)>
[2023-11-23T19:59:36.993Z]  (api_request.py:45)
[2023-11-23T19:59:36.993Z] [2023-11-23 18:22:45 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for loading collection timeout, collection: upsert_XYcukym2)> (api_request.py:46)
```

### Expected Behavior

pass

### Steps To Reproduce

```markdown
1. create a collection (pk is string type)
2. insert 2000 data
3. upsert 10 times (every time 1000 data)
4. load -> fail
```

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/568/pipeline/205
2. log: [artifacts-milvus-distributed-kafka-nightly-568-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/568/artifact/artifacts-milvus-distributed-kafka-nightly-568-pymilvus-e2e-logs.tar.gz)
3. collection name: upsert_XYcukym2
4. failed time: [2023-11-23T18:22:46.228Z] [gw2] [ 23%] FAILED testcases/test_insert.py::TestUpsertValid::test_upsert_pk_string_multiple_times

**Comment by NicoYuan1986** [comment]
@congqixia Can you help see if this is a serious issue?

**Comment by yanliang567** [comment]
please help to check if it was related to L0 deletion changes.

**Comment by congqixia** [comment]
Growing segment load fix PR has been merged, could you please verify? 
/assign @NicoYuan1986

**Comment by NicoYuan1986** [comment]
verify fixed. master-20231213-fe1eeae2
