### ISSUE TITLE
[Bug]: Standalone panic: segment not found[segment=xxx] [recovered] and search error Timestamp lag too large

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#28736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20231124-39be3580
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.3.2.post1.dev9
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. deploy standalone  with image `master-20231122-af18aa70`
2. create collection -> index -> load -> insert 10m-128d data  -> flush
3. concurrent upsert and search -> flush timeout
4. upgrade image to `master-20231124-39be3580`
5. concurrent search and upsert -> error:
```
[2023-11-24 08:53:09,751 - ERROR - fouram]: (api_response) : <MilvusException: (code=65535, message=failed to search/query delegator 4 for channel test-delete-3-rootcoord-dml_0_445812718413807844v0: fail to Search, QueryNode ID=4, reason=Timestamp lag too large)> (api_request.py:54)
```

6. standalone panic
[standalone.log](https://github.com/milvus-io/milvus/files/13461108/standalone.log)

```
[2023/11/24 13:05:28.916 +00:00] [ERROR] [conc/options.go:54] ["Conc pool panicked"] [panic="segment not found[segment=445860769366746104]"] [stack="github.com/milvus-io/milvus/pkg/util/conc.(*poolOption).antsOptions.func1\n\t/go/src/github.com/milvus-io/milvus/pkg/util/conc/options.go:54\ngithub.com/panjf2000/ants/v2.(*goWorker).run.func1.1\n\t/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.2/worker.go:54\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:884\ngithub.com/milvus-io/milvus/pkg/util/conc.(*Pool[...]).Submit.func1.1\n\t/go/src/github.com/milvus-io/milvus/pkg/util/conc/pool.go:72\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:884\ngithub.com/milvus-io/milvus/internal/datanode/writebuffer.(*writeBufferBase).getSyncTask.func2\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/writebuffer/write_buffer.go:394\ngithub.com/milvus-io/milvus/internal/datanode/syncmgr.(*SyncTask).handleError\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/syncmgr/task.go:77\ngithub.com/milvus-io/milvus/internal/datanode/syncmgr.(*SyncTask).Run\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/syncmgr/task.go:129\ngithub.com/milvus-io/milvus/internal/datanode/syncmgr.(*keyLockDispatcher[...]).Submit.func1\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/syncmgr/key_lock_dispatcher.go:34\ngithub.com/milvus-io/milvus/pkg/util/conc.(*Pool[...]).Submit.func1\n\t/go/src/github.com/milvus-io/milvus/pkg/util/conc/pool.go:79\ngithub.com/panjf2000/ants/v2.(*goWorker).run.func1\n\t/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.2/worker.go:67"]
panic: segment not found[segment=445860769366746104] [recovered]
    panic: segment not found[segment=445860769366746104] [recovered]
    panic: segment not found[segment=445860769366746104]

goroutine 3068928 [running]:
panic({0x4c8f540, 0xc0051e8090})
    /usr/local/go/src/runtime/panic.go:987 +0x3bb fp=0xc001565788 sp=0xc0015656c8 pc=0x19ebc5b
github.com/milvus-io/milvus/pkg/util/conc.(*poolOption).antsOptions.func1({0x4c8f540, 0xc0051e8090})
    /go/src/github.com/milvus-io/milvus/pkg/util/conc/options.go:56 +0x15b fp=0xc001565850 sp=0xc001565788 pc=0x3365f3b
github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
    /go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.2/worker.go:54 +0x75 fp=0xc0015658c8 sp=0xc001565850 pc=0x3363035
runtime.deferCallSave(0xc001565998, 0xc001565fb8?)
    /usr/local/go/src/runtime/panic.go:796 +0x88 fp=0xc0015658d8 sp=0xc0015658c8 pc=0x19eb848
runtime.runOpenDeferFrame(0xc0027a3c70)
```

### Steps To Reproduce

```markdown
4am argo: https://argo-workflows.zilliz.cc/archived-workflows/qa/06c4dfb1-17a8-452a-ba3f-b13f5092aebb
```

### Milvus Log

4am pods:
```
test-delete-3-etcd-0                                              1/1     Running            0                 2d8h    10.104.18.64    4am-node25   <none>           <none>
test-delete-3-milvus-standalone-5479bb74dc-v7ggj                  1/1     Running            3 (3h36m ago)     7h56m   10.104.18.134   4am-node25   <none>           <none>
test-delete-3-minio-64dfccc775-248fq                              1/1     Running            0                 2d8h    10.104.18.63    4am-node25   <none>           <none>
```

**Comment by congqixia** [comment]
/assign @ThreadDao
please verify after pr #28755 merged

**Comment by ThreadDao** [comment]
Fixed panic `master-20231128-4bd426db-amd64`
https://argo-workflows.zilliz.cc/archived-workflows/qa/abf88751-195e-4bc1-b5e4-330e3afe4121
Flush timeout will track on another issue
