### ISSUE TITLE
[Bug]: After recovering from a data coordinator node kill chaos test, numerous collections in Milvus experienced a flush timeout of 180 seconds

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#28848]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20231129-3f9da2b8-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):kafka    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```

[2023-11-29T19:28:03.802Z] [2023-11-29 19:12:53 - DEBUG - ci_test]: (api_request)  : [Connections.connect] args: ['default', '', '', ''], kwargs: {'host': '10.255.204.137', 'port': 19530} (api_request.py:62)

[2023-11-29T19:28:03.802Z] [2023-11-29 19:12:53 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-11-29T19:28:03.802Z] [2023-11-29 19:12:54 - DEBUG - ci_test]: (api_request)  : [Connections.has_connection] args: ['default'], kwargs: {} (api_request.py:62)

[2023-11-29T19:28:03.802Z] [2023-11-29 19:12:54 - DEBUG - ci_test]: (api_response) : True  (api_request.py:37)

[2023-11-29T19:28:03.802Z] [2023-11-29 19:12:54 - DEBUG - ci_test]: (api_request)  : [Collection] args: ['Checker__oRWcFJMq', {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}, {'name': 'varchar', 'description': '', 'type': <DataType......, kwargs: {'consistency_level': 'Strong'} (api_request.py:62)

[2023-11-29T19:28:03.802Z] [2023-11-29 19:12:54 - DEBUG - ci_test]: (api_response) : <Collection>:

[2023-11-29T19:28:03.802Z] -------------

[2023-11-29T19:28:03.802Z] <name>: Checker__oRWcFJMq

[2023-11-29T19:28:03.802Z] <description>: 

[2023-11-29T19:28:03.802Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}......  (api_request.py:37)

[2023-11-29T19:28:03.802Z] [2023-11-29 19:12:54 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2023-11-29T19:28:03.802Z] [2023-11-29 19:15:54 - WARNING - pymilvus.decorators]: Retry timeout: 180s (decorators.py:94)

[2023-11-29T19:28:03.802Z] [2023-11-29 19:15:54 - ERROR - pymilvus.decorators]: RPC error: [flush], <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for flush timeout, collection: Checker__oRWcFJMq)>, <Time:{'RPC start': '2023-11-29 19:12:54.003792', 'RPC error': '2023-11-29 19:15:54.340882'}> (decorators.py:128)

[2023-11-29T19:28:03.802Z] [2023-11-29 19:15:54 - ERROR - ci_test]: Traceback (most recent call last):

[2023-11-29T19:28:03.802Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2023-11-29T19:28:03.802Z]     res = func(*args, **_kwargs)

[2023-11-29T19:28:03.802Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2023-11-29T19:28:03.802Z]     return func(*arg, **kwargs)

[2023-11-29T19:28:03.802Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 314, in flush

[2023-11-29T19:28:03.802Z]     conn.flush([self.name], timeout=timeout, **kwargs)

[2023-11-29T19:28:03.802Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 129, in handler

[2023-11-29T19:28:03.802Z]     raise e from e

[2023-11-29T19:28:03.802Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 125, in handler

[2023-11-29T19:28:03.802Z]     return func(*args, **kwargs)

[2023-11-29T19:28:03.802Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 164, in handler

[2023-11-29T19:28:03.802Z]     return func(self, *args, **kwargs)

[2023-11-29T19:28:03.802Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 95, in handler

[2023-11-29T19:28:03.802Z]     raise MilvusException(

[2023-11-29T19:28:03.802Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for flush timeout, collection: Checker__oRWcFJMq)>

[2023-11-29T19:28:03.802Z]  (api_request.py:45)
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-cron/detail/chaos-test-kafka-cron/9499/pipeline

log:

[artifacts-datacoord-pod-kill-9499-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/13507783/artifacts-datacoord-pod-kill-9499-server-logs.tar.gz)

[artifacts-datacoord-pod-kill-9499-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/13507785/artifacts-datacoord-pod-kill-9499-pytest-logs.tar.gz)

### Anything else?

There are also some collections that have problem with compact
```
[2023-11-29T19:28:03.799Z] self = <test_all_collections_after_chaos.TestAllCollection object at 0x7fbed12a3370>

[2023-11-29T19:28:03.799Z] collection_name = 'CreateChecker__J70aewRf'

[2023-11-29T19:28:03.799Z] 

[2023-11-29T19:28:03.799Z]     @pytest.mark.tags(CaseLabel.L1)

[2023-11-29T19:28:03.799Z]     def test_milvus_default(self, collection_name):

[2023-11-29T19:28:03.799Z]         self._connect()

[2023-11-29T19:28:03.799Z]         # create

[2023-11-29T19:28:03.799Z]         name = collection_name if collection_name else cf.gen_unique_str("Checker_")

[2023-11-29T19:28:03.799Z]         t0 = time.time()

[2023-11-29T19:28:03.799Z]         schema = Collection(name=name).schema

[2023-11-29T19:28:03.799Z]         collection_w = self.init_collection_wrap(name=name, schema=schema)

[2023-11-29T19:28:03.799Z]         tt = time.time() - t0

[2023-11-29T19:28:03.799Z]         assert collection_w.name == name

[2023-11-29T19:28:03.799Z]         # get collection info

[2023-11-29T19:28:03.799Z]         schema = collection_w.schema

[2023-11-29T19:28:03.799Z]         dim = cf.get_dim_by_schema(schema=schema)

[2023-11-29T19:28:03.799Z]         int64_field_name = cf.get_int64_field_name(schema=schema)

[2023-11-29T19:28:03.799Z]         float_vector_field_name = cf.get_float_vec_field_name(schema=schema)

[2023-11-29T19:28:03.799Z]     

[2023-11-29T19:28:03.799Z]         # compact collection before getting num_entities

[2023-11-29T19:28:03.799Z]         collection_w.flush(timeout=180)

[2023-11-29T19:28:03.799Z]         collection_w.compact()

[2023-11-29T19:28:03.799Z] >       collection_w.wait_for_compaction_completed(timeout=720)

[2023-11-29T19:28:03.799Z] 

[2023-11-29T19:28:03.799Z] testcases/test_all_collections_after_chaos.py:46: 

[2023-11-29T19:28:03.799Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

[2023-11-29T19:28:03.799Z] ../base/collection_wrapper.py:380: in wait_for_compaction_completed

[2023-11-29T19:28:03.799Z]     res = self.collection.wait_for_compaction_completed(timeout, **kwargs)

[2023-11-29T19:28:03.799Z] /usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py:1331: in wait_for_compaction_completed

[2023-11-29T19:28:03.799Z]     return conn.wait_for_compaction_completed(self.compaction_id, timeout=timeout, **kwargs)

[2023-11-29T19:28:03.799Z] /usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py:129: in handler

[2023-11-29T19:28:03.799Z]     raise e from e

[2023-11-29T19:28:03.799Z] /usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py:125: in handler

[2023-11-29T19:28:03.799Z]     return func(*args, **kwargs)

[2023-11-29T19:28:03.799Z] /usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py:164: in handler

[2023-11-29T19:28:03.799Z]     return func(self, *args, **kwargs)

[2023-11-29T19:28:03.799Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

[2023-11-29T19:28:03.799Z] 

[2023-11-29T19:28:03.799Z] args = (<pymilvus.client.grpc_handler.GrpcHandler object at 0x7fbed00fe190>, 445980999246128292)

[2023-11-29T19:28:03.799Z] kwargs = {'timeout': 720}, _timeout = 720, _retry_on_rate_limit = True

[2023-11-29T19:28:03.799Z] back_off = 0.01, start_time = 1701284634.0438457

[2023-11-29T19:28:03.799Z] timeout = <function retry_on_rpc_failure.<locals>.wrapper.<locals>.handler.<locals>.timeout at 0x7fbed127b8b0>

[2023-11-29T19:28:03.799Z] to_msg = 'Retry timeout: 720s'

[2023-11-29T19:28:03.799Z] 

[2023-11-29T19:28:03.799Z]     @functools.wraps(func)

[2023-11-29T19:28:03.799Z]     @error_handler(func_name=func.__name__)

[2023-11-29T19:28:03.799Z]     @tracing_request()

[2023-11-29T19:28:03.799Z]     def handler(*args, **kwargs):

[2023-11-29T19:28:03.799Z]         # This has to make sure every timeout parameter is passing

[2023-11-29T19:28:03.799Z]         # throught kwargs form as `timeout=10`

[2023-11-29T19:28:03.799Z]         _timeout = kwargs.get("timeout", None)

[2023-11-29T19:28:03.799Z]         _retry_on_rate_limit = kwargs.get("retry_on_rate_limit", True)

[2023-11-29T19:28:03.799Z]     

[2023-11-29T19:28:03.799Z]         retry_timeout = _timeout if _timeout is not None and isinstance(_timeout, int) else None

[2023-11-29T19:28:03.799Z]         counter = 1

[2023-11-29T19:28:03.799Z]         back_off = initial_back_off

[2023-11-29T19:28:03.799Z]         start_time = time.time()

[2023-11-29T19:28:03.799Z]     

[2023-11-29T19:28:03.799Z]         def timeout(start_time: Optional[float] = None) -> bool:

[2023-11-29T19:28:03.799Z]             """If timeout is valid, use timeout as the retry limits,

[2023-11-29T19:28:03.799Z]             If timeout is None, use retry_times as the retry limits.

[2023-11-29T19:28:03.799Z]             """

[2023-11-29T19:28:03.799Z]             if retry_timeout is not None:

[2023-11-29T19:28:03.799Z]                 return time.time() - start_time >= retry_timeout

[2023-11-29T19:28:03.799Z]             return counter > retry_times

[2023-11-29T19:28:03.799Z]     

[2023-11-29T19:28:03.799Z]         to_msg = (

[2023-11-29T19:28:03.799Z]             f"Retry timeout: {retry_timeout}s"

[2023-11-29T19:28:03.799Z]             if retry_timeout is not None

[2023-11-29T19:28:03.799Z]             else f"Retry run out of {retry_times} retry times"

[2023-11-29T19:28:03.799Z]         )

[2023-11-29T19:28:03.799Z]     

[2023-11-29T19:28:03.799Z]         while True:

[2023-11-29T19:28:03.799Z]             try:

[2023-11-29T19:28:03.799Z]                 return func(*args, **kwargs)

[2023-11-29T19:28:03.799Z]             except grpc.RpcError as e:

[2023-11-29T19:28:03.799Z]                 # Reference: https://grpc.github.io/grpc/python/grpc.html#grpc-status-code

[2023-11-29T19:28:03.799Z]                 if e.code() in (

[2023-11-29T19:28:03.799Z]                     grpc.StatusCode.DEADLINE_EXCEEDED,

[2023-11-29T19:28:03.799Z]                     grpc.StatusCode.PERMISSION_DENIED,

[2023-11-29T19:28:03.799Z]                     grpc.StatusCode.UNAUTHENTICATED,

[2023-11-29T19:28:03.799Z]                     grpc.StatusCode.INVALID_ARGUMENT,

[2023-11-29T19:28:03.799Z]                     grpc.StatusCode.ALREADY_EXISTS,

[2023-11-29T19:28:03.799Z]                     grpc.StatusCode.RESOURCE_EXHAUSTED,

[2023-11-29T19:28:03.799Z]                 ):

[2023-11-29T19:28:03.799Z]                     raise e from e

[2023-11-29T19:28:03.799Z]                 if timeout(start_time):

[2023-11-29T19:28:03.799Z]                     raise MilvusException(e.code, f"{to_msg}, message={e.details()}") from e

[2023-11-29T19:28:03.799Z]     

[2023-11-29T19:28:03.799Z]                 if counter > 3:

[2023-11-29T19:28:03.799Z]                     retry_msg = (

[2023-11-29T19:28:03.799Z]                         f"[{func.__name__}] retry:{counter}, cost: {back_off:.2f}s, "

[2023-11-29T19:28:03.799Z]                         f"reason: <{e.__class__.__name__}: {e.code()}, {e.details()}>"

[2023-11-29T19:28:03.799Z]                     )

[2023-11-29T19:28:03.799Z]                     LOGGER.warning(WARNING_COLOR.format(retry_msg))

[2023-11-29T19:28:03.799Z]     

[2023-11-29T19:28:03.799Z]                 time.sleep(back_off)

[2023-11-29T19:28:03.799Z]                 back_off = min(back_off * back_off_multiplier, max_back_off)

[2023-11-29T19:28:03.799Z]             except MilvusException as e:

[2023-11-29T19:28:03.799Z]                 if timeout(start_time):

[2023-11-29T19:28:03.799Z]                     LOGGER.warning(WARNING_COLOR.format(to_msg))

[2023-11-29T19:28:03.799Z] >                   raise MilvusException(

[2023-11-29T19:28:03.799Z]                         code=e.code, message=f"{to_msg}, message={e.message}"

[2023-11-29T19:28:03.799Z]                     ) from e

[2023-11-29T19:28:03.799Z] E                   pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 720s, message=get compaction state timeout, compaction id: 445980999246128292)>

[2023-11-29T19:28:03.799Z]
```

4am chaos-testing

```
[2023-11-29T19:00:30.886Z] + kubectl get pods -o wide

[2023-11-29T19:00:30.887Z] + grep datacoord-pod-kill-9499

[2023-11-29T19:00:31.449Z] datacoord-pod-kill-9499-etcd-0                                    1/1     Running             0               33m     10.104.16.136   4am-node21   <none>           <none>

[2023-11-29T19:00:31.449Z] datacoord-pod-kill-9499-etcd-1                                    1/1     Running             0               33m     10.104.21.198   4am-node24   <none>           <none>

[2023-11-29T19:00:31.449Z] datacoord-pod-kill-9499-etcd-2                                    1/1     Running             0               33m     10.104.24.152   4am-node29   <none>           <none>

[2023-11-29T19:00:31.449Z] datacoord-pod-kill-9499-kafka-0                                   2/2     Running             2 (33m ago)     33m     10.104.20.59    4am-node22   <none>           <none>

[2023-11-29T19:00:31.449Z] datacoord-pod-kill-9499-kafka-1                                   2/2     Running             2 (32m ago)     33m     10.104.18.149   4am-node25   <none>           <none>

[2023-11-29T19:00:31.449Z] datacoord-pod-kill-9499-kafka-2                                   2/2     Running             2 (32m ago)     33m     10.104.17.93    4am-node23   <none>           <none>

[2023-11-29T19:00:31.449Z] datacoord-pod-kill-9499-kafka-exporter-5d9dbb7f6d-zthhw           1/1     Running             5 (32m ago)     33m     10.104.6.198    4am-node13   <none>           <none>

[2023-11-29T19:00:31.449Z] datacoord-pod-kill-9499-milvus-datacoord-77bbdff87d-kns6p         1/1     Running             0               12m     10.104.1.169    4am-node10   <none>           <none>

[2023-11-29T19:00:31.449Z] datacoord-pod-kill-9499-milvus-datanode-75c45c8bb9-gwn65          1/1     Running             0               33m     10.104.12.251   4am-node17   <none>           <none>

[2023-11-29T19:00:31.449Z] datacoord-pod-kill-9499-milvus-datanode-75c45c8bb9-h29sw          1/1     Running             0               33m     10.104.6.204    4am-node13   <none>           <none>

[2023-11-29T19:00:31.449Z] datacoord-pod-kill-9499-milvus-indexcoord-749759d8c9-sz8rt        1/1     Running             0               33m     10.104.6.199    4am-node13   <none>           <none>

[2023-11-29T19:00:31.449Z] datacoord-pod-kill-9499-milvus-indexnode-54dccf8b8b-hc2jq         1/1     Running             0               33m     10.104.6.203    4am-node13   <none>           <none>

[2023-11-29T19:00:31.449Z] datacoord-pod-kill-9499-milvus-indexnode-54dccf8b8b-pf64r         1/1     Running             0               33m     10.104.12.246   4am-node17   <none>           <none>

[2023-11-29T19:00:31.449Z] datacoord-pod-kill-9499-milvus-indexnode-54dccf8b8b-qfv2c         1/1     Running             0               33m     10.104.16.134   4am-node21   <none>           <none>

[2023-11-29T19:00:31.449Z] datacoord-pod-kill-9499-milvus-proxy-788ccfb67f-kf6mg             1/1     Running             0               33m     10.104.6.201    4am-node13   <none>           <none>

[2023-11-29T19:00:31.449Z] datacoord-pod-kill-9499-milvus-querycoord-868fd5f44-6xlbs         1/1     Running             0               33m     10.104.6.205    4am-node13   <none>           <none>

[2023-11-29T19:00:31.449Z] datacoord-pod-kill-9499-milvus-querynode-64ffb96794-dw9ws         1/1     Running             0               33m     10.104.6.202    4am-node13   <none>           <none>

[2023-11-29T19:00:31.449Z] datacoord-pod-kill-9499-milvus-querynode-64ffb96794-krjzd         1/1     Running             0               33m     10.104.12.250   4am-node17   <none>           <none>

[2023-11-29T19:00:31.449Z] datacoord-pod-kill-9499-milvus-querynode-64ffb96794-l4gbk         1/1     Running             0               33m     10.104.13.151   4am-node16   <none>           <none>

[2023-11-29T19:00:31.449Z] datacoord-pod-kill-9499-milvus-rootcoord-5756b56c4-dptfp          1/1     Running             0               33m     10.104.12.247   4am-node17   <none>           <none>

[2023-11-29T19:00:31.449Z] datacoord-pod-kill-9499-minio-0                                   1/1     Running             0               33m     10.104.19.41    4am-node28   <none>           <none>

[2023-11-29T19:00:31.449Z] datacoord-pod-kill-9499-minio-1                                   1/1     Running             0               33m     10.104.24.151   4am-node29   <none>           <none>

[2023-11-29T19:00:31.449Z] datacoord-pod-kill-9499-minio-2                                   1/1     Running             0               33m     10.104.18.151   4am-node25   <none>           <none>

[2023-11-29T19:00:31.449Z] datacoord-pod-kill-9499-minio-3                                   1/1     Running             0               33m     10.104.16.142   4am-node21   <none>           <none>

[2023-11-29T19:00:31.449Z] datacoord-pod-kill-9499-zookeeper-0                               1/1     Running             0               33m     10.104.15.116   4am-node20   <none>           <none>

[2023-11-29T19:00:31.449Z] datacoord-pod-kill-9499-zookeeper-1                               1/1     Running             0               33m     10.104.18.148   4am-node25   <none>           <none>

[2023-11-29T19:00:31.449Z] datacoord-pod-kill-9499-zookeeper-2                               1/1     Running             0               33m     10.104.21.199   4am-node24   <none>           <none>
```

**Comment by XuanYang-cn** [comment]
might be refectory related
/assign

**Comment by zhuwenxing** [comment]
it still reproduced in master-20231219-bfca0a79
```

[2023-12-19T19:25:26.643Z] <name>: DropChecker__OzbJMdeQ

[2023-12-19T19:25:26.643Z] <description>: 

[2023-12-19T19:25:26.644Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: ......  (api_request.py:37)

[2023-12-19T19:25:26.644Z] [2023-12-19 19:21:35 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2023-12-19T19:25:26.644Z] [2023-12-19 19:21:36 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-12-19T19:25:26.644Z] [2023-12-19 19:21:36 - DEBUG - ci_test]: (api_request)  : [Collection.compact] args: [180], kwargs: {} (api_request.py:62)

[2023-12-19T19:25:26.644Z] [2023-12-19 19:21:36 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-12-19T19:25:26.644Z] [2023-12-19 19:22:24 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2023-12-19T19:25:26.644Z] [2023-12-19 19:22:25 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-12-19T19:25:26.644Z] [2023-12-19 19:22:25 - INFO - ci_test]: assert create collection: 0.007077693939208984, init_entities: 3000 (test_all_collections_after_chaos.py:49)

[2023-12-19T19:25:26.644Z] [2023-12-19 19:22:25 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [[[-3000, -2999, -2998, -2997, -2996, -2995, -2994, -2993, -2992, -2991, -2990, -2989, -2988, -2987, -2986, -2985, -2984, -2983, -2982, -2981, -2980, -2979, -2978, -2977, -2976, -2975, -2974, -2973, -2972, -2971, -2970, -2969, -2968, -2967, -2966, -2965, -2964, -2963, -2962, -2961, -2960, -2959, -29......, kwargs: {'timeout': 180} (api_request.py:62)

[2023-12-19T19:25:26.644Z] [2023-12-19 19:22:25 - DEBUG - ci_test]: (api_response) : (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 446434835302973443, success count: 2000, err count: 0)  (api_request.py:37)

[2023-12-19T19:25:26.644Z] [2023-12-19 19:22:25 - INFO - ci_test]: assert insert: 0.1816246509552002 (test_all_collections_after_chaos.py:61)

[2023-12-19T19:25:26.644Z] [2023-12-19 19:22:25 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2023-12-19T19:25:26.644Z] [2023-12-19 19:25:25 - WARNING - pymilvus.decorators]: Retry timeout: 180s (decorators.py:94)

[2023-12-19T19:25:26.644Z] [2023-12-19 19:25:25 - ERROR - pymilvus.decorators]: RPC error: [flush], <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for flush timeout, collection: DropChecker__OzbJMdeQ)>, <Time:{'RPC start': '2023-12-19 19:22:25.588662', 'RPC error': '2023-12-19 19:25:25.877992'}> (decorators.py:128)

[2023-12-19T19:25:26.644Z] [2023-12-19 19:25:25 - ERROR - ci_test]: Traceback (most recent call last):

[2023-12-19T19:25:26.644Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2023-12-19T19:25:26.644Z]     res = func(*args, **_kwargs)

[2023-12-19T19:25:26.644Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2023-12-19T19:25:26.644Z]     return func(*arg, **kwargs)

[2023-12-19T19:25:26.644Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 314, in flush

[2023-12-19T19:25:26.644Z]     conn.flush([self.name], timeout=timeout, **kwargs)

[2023-12-19T19:25:26.644Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 129, in handler

[2023-12-19T19:25:26.644Z]     raise e from e

[2023-12-19T19:25:26.644Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 125, in handler

[2023-12-19T19:25:26.644Z]     return func(*args, **kwargs)

[2023-12-19T19:25:26.644Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 164, in handler

[2023-12-19T19:25:26.644Z]     return func(self, *args, **kwargs)

[2023-12-19T19:25:26.644Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 95, in handler

[2023-12-19T19:25:26.644Z]     raise MilvusException(

[2023-12-19T19:25:26.644Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for flush timeout, collection: DropChecker__OzbJMdeQ)>

[2023-12-19T19:25:26.644Z]  (api_request.py:45)
```
failed job: 
https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/10101/pipeline
log:
[artifacts-etcd-pod-failure-10101-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/13725493/artifacts-etcd-pod-failure-10101-pytest-logs.tar.gz)
[artifacts-etcd-pod-failure-10101-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/13725494/artifacts-etcd-pod-failure-10101-server-logs.tar.gz)

**Comment by xiaofan-luan** [comment]
/assign @yiwangdr 
please help on this

**Comment by zhuwenxing** [comment]
duplicated with https://github.com/milvus-io/milvus/issues/30137

so use https://github.com/milvus-io/milvus/issues/30137 to trace
