### ISSUE TITLE
[Bug]: Search failed with error `code=503, message=failed to search: channel lacks[channel=channel not subscribed]: channel not available[channel=by-dev-rootcoord-dml_xxxv1]` after recover from querynode pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#28845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3-20231129-a78ea4fe
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2023-11-29T23:51:39.231Z] <name>: Checker__QIAz3SFw

[2023-11-29T23:51:39.231Z] <description>: 

[2023-11-29T23:51:39.231Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}......  (api_request.py:37)

[2023-11-29T23:51:39.231Z] [2023-11-29 23:49:58 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2023-11-29T23:51:39.231Z] [2023-11-29 23:50:10 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-11-29T23:51:39.231Z] [2023-11-29 23:50:10 - DEBUG - ci_test]: (api_request)  : [Collection.compact] args: [180], kwargs: {} (api_request.py:62)

[2023-11-29T23:51:39.231Z] [2023-11-29 23:50:10 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-11-29T23:51:39.231Z] [2023-11-29 23:50:30 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2023-11-29T23:51:39.231Z] [2023-11-29 23:50:30 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-11-29T23:51:39.231Z] [2023-11-29 23:50:30 - INFO - ci_test]: assert create collection: 0.5872786045074463, init_entities: 81035 (test_all_collections_after_chaos.py:49)

[2023-11-29T23:51:39.231Z] [2023-11-29 23:50:30 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [[[-3000, -2999, -2998, -2997, -2996, -2995, -2994, -2993, -2992, -2991, -2990, -2989, -2988, -2987, -2986, -2985, -2984, -2983, -2982, -2981, -2980, -2979, -2978, -2977, -2976, -2975, -2974, -2973, -2972, -2971, -2970, -2969, -2968, -2967, -2966, -2965, -2964, -2963, -2962, -2961, -2960, -2959, -29......, kwargs: {'timeout': 180} (api_request.py:62)

[2023-11-29T23:51:39.231Z] [2023-11-29 23:50:30 - DEBUG - ci_test]: (api_response) : (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 445986067133759489, success count: 2000, err count: 0)  (api_request.py:37)

[2023-11-29T23:51:39.231Z] [2023-11-29 23:50:30 - INFO - ci_test]: assert insert: 0.20329785346984863 (test_all_collections_after_chaos.py:61)

[2023-11-29T23:51:39.231Z] [2023-11-29 23:50:30 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2023-11-29T23:51:39.231Z] [2023-11-29 23:50:33 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-11-29T23:51:39.231Z] [2023-11-29 23:50:33 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2023-11-29T23:51:39.231Z] [2023-11-29 23:50:34 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-11-29T23:51:39.231Z] [2023-11-29 23:50:34 - INFO - ci_test]: assert flush: 3.0261595249176025, entities: 83035 (test_all_collections_after_chaos.py:71)

[2023-11-29T23:51:39.231Z] [2023-11-29 23:50:34 - INFO - ci_test]: index info: [{'collection': 'Checker__QIAz3SFw', 'field': 'float_vector', 'index_name': 'index__jHw1bQY9', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}] (test_all_collections_after_chaos.py:87)

[2023-11-29T23:51:39.231Z] [2023-11-29 23:50:34 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 180], kwargs: {} (api_request.py:62)

[2023-11-29T23:51:39.232Z] [2023-11-29 23:50:34 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2023-11-29T23:51:39.232Z] [2023-11-29 23:50:34 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.10986396473426743, 0.0627303084116503, 0.028784849204608384, 0.15220708585374843, 0.035258115926872016, 0.09419091292425068, 0.07960466921076756, 0.08883008221656409, 0.12136023477072097, 0.1494548594476696, 0.0612820247610543, 0.09656783717065143, 0.09650270888647003, 0.08401760622212011, 0.03......, kwargs: {} (api_request.py:62)

[2023-11-29T23:51:39.232Z] [2023-11-29 23:50:34 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=503, message=failed to search: channel lacks[channel=channel not subscribed]: channel not available[channel=by-dev-rootcoord-dml_14_445985560087047692v1])>, <Time:{'RPC start': '2023-11-29 23:50:34.402592', 'RPC error': '2023-11-29 23:50:34.405388'}> (decorators.py:128)

[2023-11-29T23:51:39.232Z] [2023-11-29 23:50:34 - ERROR - ci_test]: Traceback (most recent call last):

[2023-11-29T23:51:39.232Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2023-11-29T23:51:39.232Z]     res = func(*args, **_kwargs)

[2023-11-29T23:51:39.232Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2023-11-29T23:51:39.232Z]     return func(*arg, **kwargs)

[2023-11-29T23:51:39.232Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 782, in search

[2023-11-29T23:51:39.232Z]     resp = conn.search(

[2023-11-29T23:51:39.232Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 129, in handler

[2023-11-29T23:51:39.232Z]     raise e from e

[2023-11-29T23:51:39.232Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 125, in handler

[2023-11-29T23:51:39.232Z]     return func(*args, **kwargs)

[2023-11-29T23:51:39.232Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 164, in handler

[2023-11-29T23:51:39.232Z]     return func(self, *args, **kwargs)

[2023-11-29T23:51:39.232Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 104, in handler

[2023-11-29T23:51:39.232Z]     raise e from e

[2023-11-29T23:51:39.232Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 68, in handler

[2023-11-29T23:51:39.232Z]     return func(*args, **kwargs)

[2023-11-29T23:51:39.232Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 781, in search

[2023-11-29T23:51:39.232Z]     return self._execute_search(request, timeout, round_decimal=round_decimal, **kwargs)

[2023-11-29T23:51:39.232Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 742, in _execute_search

[2023-11-29T23:51:39.232Z]     raise e from e

[2023-11-29T23:51:39.232Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 734, in _execute_search

[2023-11-29T23:51:39.232Z]     raise MilvusException(response.status.code, response.status.reason)

[2023-11-29T23:51:39.232Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=503, message=failed to search: channel lacks[channel=channel not subscribed]: channel not available[channel=by-dev-rootcoord-dml_14_445985560087047692v1])>

[2023-11-29T23:51:39.232Z]  (api_request.py:45)
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-for-release-cron/detail/chaos-test-kafka-for-release-cron/8709/pipeline

log:
[artifacts-querynode-pod-kill-8709-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/13507731/artifacts-querynode-pod-kill-8709-pytest-logs.tar.gz)
[artifacts-querynode-pod-kill-8709-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/13507732/artifacts-querynode-pod-kill-8709-server-logs.tar.gz)

### Anything else?

4am chaos-testing
```
[2023-11-29T23:49:36.802Z] + kubectl get pods -o wide

[2023-11-29T23:49:36.803Z] + grep querynode-pod-kill-8709

[2023-11-29T23:49:37.060Z] querynode-pod-kill-8709-etcd-0                                   1/1     Running            0               32m     10.104.24.171   4am-node29   <none>           <none>

[2023-11-29T23:49:37.060Z] querynode-pod-kill-8709-etcd-1                                   1/1     Running            0               32m     10.104.16.136   4am-node21   <none>           <none>

[2023-11-29T23:49:37.060Z] querynode-pod-kill-8709-etcd-2                                   1/1     Running            0               32m     10.104.17.242   4am-node23   <none>           <none>

[2023-11-29T23:49:37.060Z] querynode-pod-kill-8709-kafka-0                                  2/2     Running            2 (32m ago)     32m     10.104.24.168   4am-node29   <none>           <none>

[2023-11-29T23:49:37.060Z] querynode-pod-kill-8709-kafka-1                                  2/2     Running            2 (31m ago)     32m     10.104.17.241   4am-node23   <none>           <none>

[2023-11-29T23:49:37.060Z] querynode-pod-kill-8709-kafka-2                                  2/2     Running            1 (31m ago)     32m     10.104.16.142   4am-node21   <none>           <none>

[2023-11-29T23:49:37.060Z] querynode-pod-kill-8709-kafka-exporter-7df45c5bdd-kfc9s          1/1     Running            4 (31m ago)     32m     10.104.6.243    4am-node13   <none>           <none>

[2023-11-29T23:49:37.060Z] querynode-pod-kill-8709-milvus-datacoord-8684644c49-xmj2l        1/1     Running            0               32m     10.104.6.241    4am-node13   <none>           <none>

[2023-11-29T23:49:37.060Z] querynode-pod-kill-8709-milvus-datanode-5d8bffdd68-8jx8f         1/1     Running            0               32m     10.104.18.163   4am-node25   <none>           <none>

[2023-11-29T23:49:37.060Z] querynode-pod-kill-8709-milvus-datanode-5d8bffdd68-lx7vh         1/1     Running            0               32m     10.104.23.134   4am-node27   <none>           <none>

[2023-11-29T23:49:37.060Z] querynode-pod-kill-8709-milvus-indexcoord-7f85c79dbb-945mj       1/1     Running            0               32m     10.104.18.162   4am-node25   <none>           <none>

[2023-11-29T23:49:37.060Z] querynode-pod-kill-8709-milvus-indexnode-5785d6b5c7-8jcs2        1/1     Running            0               32m     10.104.1.72     4am-node10   <none>           <none>

[2023-11-29T23:49:37.060Z] querynode-pod-kill-8709-milvus-indexnode-5785d6b5c7-s9wp8        1/1     Running            0               32m     10.104.14.84    4am-node18   <none>           <none>

[2023-11-29T23:49:37.060Z] querynode-pod-kill-8709-milvus-indexnode-5785d6b5c7-zg9hl        1/1     Running            0               32m     10.104.6.242    4am-node13   <none>           <none>

[2023-11-29T23:49:37.060Z] querynode-pod-kill-8709-milvus-proxy-65599c69d-7lc5v             1/1     Running            0               32m     10.104.23.135   4am-node27   <none>           <none>

[2023-11-29T23:49:37.060Z] querynode-pod-kill-8709-milvus-querycoord-776d8d67d5-snqc5       1/1     Running            0               32m     10.104.6.244    4am-node13   <none>           <none>

[2023-11-29T23:49:37.060Z] querynode-pod-kill-8709-milvus-querynode-6994f896fc-4dvr9        1/1     Running            0               11m     10.104.18.180   4am-node25   <none>           <none>

[2023-11-29T23:49:37.060Z] querynode-pod-kill-8709-milvus-querynode-6994f896fc-8lg8d        1/1     Running            0               11m     10.104.19.149   4am-node28   <none>           <none>

[2023-11-29T23:49:37.060Z] querynode-pod-kill-8709-milvus-querynode-6994f896fc-bnr59        1/1     Running            0               11m     10.104.16.158   4am-node21   <none>           <none>

[2023-11-29T23:49:37.060Z] querynode-pod-kill-8709-milvus-rootcoord-58bbfd78fc-4ssdf        1/1     Running            0               32m     10.104.19.143   4am-node28   <none>           <none>

[2023-11-29T23:49:37.060Z] querynode-pod-kill-8709-minio-0                                  1/1     Running            0               32m     10.104.24.166   4am-node29   <none>           <none>

[2023-11-29T23:49:37.060Z] querynode-pod-kill-8709-minio-1                                  1/1     Running            0               32m     10.104.16.141   4am-node21   <none>           <none>

[2023-11-29T23:49:37.060Z] querynode-pod-kill-8709-minio-2                                  1/1     Running            0               32m     10.104.17.244   4am-node23   <none>           <none>

[2023-11-29T23:49:37.060Z] querynode-pod-kill-8709-minio-3                                  1/1     Running            0               32m     10.104.21.47    4am-node24   <none>           <none>

[2023-11-29T23:49:37.060Z] querynode-pod-kill-8709-zookeeper-0                              1/1     Running            0               32m     10.104.15.120   4am-node20   <none>           <none>

[2023-11-29T23:49:37.060Z] querynode-pod-kill-8709-zookeeper-1                              1/1     Running            0               32m     10.104.16.134   4am-node21   <none>           <none>

[2023-11-29T23:49:37.060Z] querynode-pod-kill-8709-zookeeper-2                              1/1     Running            0               32m     10.104.17.245   4am-node23   <none>           <none>
```

**Comment by congqixia** [comment]
Shall be same as #28857 could you please verify? 
/assign @zhuwenxing
