### ISSUE TITLE
[Bug]: Standalone panic: fail to init rocksmq when upgrade milvus image from v2.3.3 to master-xxx

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#28867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20231206-4a067a4c-amd64
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):  rocksmq  
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Standalone panic: fail to init rocksmq when upgrade milvus image from v2.3.3 to master-20231206-4a067a4c-amd64
same  with #28067 ??
[stand_pre.log](https://github.com/milvus-io/milvus/files/13576712/stand_pre.log)

```
[2023/12/06 05:34:53.704 +00:00] [DEBUG] [server/rocksmq_impl.go:177] ["Start rocksmq "] ["max proc"=8] [parallism=1] ["lru cache"=1030792151]
[2023/12/06 05:34:53.706 +00:00] [FATAL] [msgstream/mq_factory.go:16] ["fail to init rocksmq"] [error="IO error: While lock file: /var/lib/milvus/rdb_data_meta_kv/LOCK: Resource temporarily unavailable"] [stack="github.com/milvus-io/milvus/internal/mq/msgstream.NewRocksmqFactory\n\t/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_factory.go:16\ngithub.com/milvus-io/milvus/internal/util/dependency.(*DefaultFactory).initMQ\n\t/go/src/github.com/milvus-io/milvus/internal/util/dependency/factory.go:90\ngithub.com/milvus-io/milvus/internal/util/dependency.(*DefaultFactory).Init\n\t/go/src/github.com/milvus-io/milvus/internal/util/dependency/factory.go:77\ngithub.com/milvus-io/milvus/internal/proxy.(*Proxy).Init\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/proxy.go:219\ngithub.com/milvus-io/milvus/internal/distributed/proxy.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:626\ngithub.com/milvus-io/milvus/internal/distributed/proxy.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:400\ngithub.com/milvus-io/milvus/cmd/components.(*Proxy).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/proxy.go:52\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:114"]
panic: fail to init rocksmq

goroutine 410 [running]:
panic({0x47eacc0, 0xc001c7b0f0})
    /usr/local/go/src/runtime/panic.go:987 +0x3bb fp=0xc001ab7eb0 sp=0xc001ab7df0 pc=0x1a16c5b
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x1?, 0x1?, {0x0?, 0x0?, 0xc0013b2d60?})
    /go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x65 fp=0xc001ab7ed0 sp=0xc001ab7eb0 pc=0x1c143a5
go.uber.org/zap/zapcore.(*CheckWriteAction).OnWrite(0x0?, 0x0?, {0xc001c79c80?, 0x0?, 0x0?})
    <autogenerated>:1 +0x2f fp=0xc001ab7f08 sp=0xc001ab7ed0 pc=0x1c25def
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc001c1c270, {0xc001c79c80, 0x1, 0x1})
    /go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x3ec fp=0xc001ab8098 sp=0xc001ab7f08 pc=0x1c1490c
go.uber.org/zap.(*Logger).Fatal(0xc000180000?, {0x4f5cc46?, 0x0?}, {0xc001c79c80, 0x1, 0x1})
    /go/pkg/mod/go.uber.org/zap@v1.24.0/logger.go:269 +0x59 fp=0xc001ab80c8 sp=0xc001ab8098 pc=0x1e65f99
github.com/milvus-io/milvus/pkg/log.Fatal({0x4f5cc46?, 0x2734d77?}, {0xc001c79c80?, 0xc00139c4c0?, 0xb?})
    /go/src/github.com/milvus-io/milvus/pkg/log/global.go:65 +0x8b fp=0xc001ab8118 sp=0xc001ab80c8 pc=0x2001c4b
github.com/milvus-io/milvus/internal/mq/msgstream.NewRocksmqFactory({0xc000577128, 0x18}, 0x7374f40)
```

### Steps To Reproduce

```markdown
argo: https://argo-workflows.zilliz.cc/archived-workflows/qa/34025d13-95b7-4d07-9791-0902ad11f8a4?nodeId=fouramf-upgrade-2333-1
```

### Milvus Log
```
delta-upgrade-standalone-v2-etcd-0                                1/1     Running                           0                 105m
delta-upgrade-standalone-v2-milvus-standalone-797b75fd86-9wccw    0/1     CrashLoopBackOff                  10 (4m54s ago)    31m
delta-upgrade-standalone-v2-milvus-standalone-79f4c989dc-rgvt5    1/1     Running                           0                 102m
delta-upgrade-standalone-v2-minio-6446ddf567-kprb8                1/1     Running                           0                 105m
```

_No response_

**Comment by xiaofan-luan** [comment]
> /var/lib/milvus/rdb_data_meta_kv/LOCK: Resource temporarily unavailable

/var/lib/milvus/rdb_data_meta_kv/LOCK: Resource temporarily unavailable

you will need to remove /var/lib/milvus/rdb_data_meta_kv/LOCK manually I guess. For some reason this is not cleaned up by rocksdb itself
