### ISSUE TITLE
[Bug]: Querynode panic: interface conversion: segments.Segment is *segments.L0Segment, not *segments.LocalSegment

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#29017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20231206-4a067a4c-amd64
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.3.3.post1.dev8
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. deploy cluster and enable LevelZero segment
```
      config:
        rootCoord:
          enableActiveStandby: true
        dataCoord:
          segment:
            enableLevelZero: true
          enableActiveStandby: true
        queryCoord:
          enableActiveStandby: true
        indexCoord:
          enableActiveStandby: true
        mixCoord:
          enableActiveStandby: true
        log:
          level: debug
```
2. create collection -> index -> load -> insert 5m flush ->  index -> load

3. concurrent search and querynode panic
[qn_pre.log](https://github.com/milvus-io/milvus/files/13576601/qn_pre.log)

```
[2023/12/06 04:42:35.287 +00:00] [DEBUG] [segments/collection.go:178] ["collection ref increment"] [collectionID=446125755620131322] [refCount=174]
[2023/12/06 04:42:35.287 +00:00] [DEBUG] [segments/collection.go:187] ["collection ref decrement"] [collectionID=446125755620131322] [refCount=173]
panic: interface conversion: segments.Segment is *segments.L0Segment, not *segments.LocalSegment

goroutine 4958 [running]:
panic({0x49c2c40, 0xc003932780})
    /usr/local/go/src/runtime/panic.go:987 +0x3bb fp=0xc004e92e80 sp=0xc004e92dc0 pc=0x1a16c5b
runtime.panicdottypeE(...)
    /usr/local/go/src/runtime/iface.go:262
runtime.panicdottypeI(0xc0014d22a0?, 0x4e7cce0, 0x4d71d40)
    /usr/local/go/src/runtime/iface.go:272 +0x7c fp=0xc004e92ea8 sp=0xc004e92e80 pc=0x19e72dc
github.com/milvus-io/milvus/internal/querynodev2.(*QueryNode).loadDeltaLogs(0xc0001d7e00, {0x54e6220, 0xc003932690}, 0xc00088e6e0)
    /go/src/github.com/milvus-io/milvus/internal/querynodev2/handlers.go:126 +0x445 fp=0xc004e93018 sp=0xc004e92ea8 pc=0x43face5
github.com/milvus-io/milvus/internal/querynodev2.(*QueryNode).LoadSegments(0xc0001d7e00, {0x54e6220, 0xc003932690}, 0xc00088e6e0)
    /go/src/github.com/milvus-io/milvus/internal/querynodev2/services.go:480 +0xf3f fp=0xc004e933f8 sp=0xc004e93018 pc=0x440a1df
```

### Steps To Reproduce

```markdown
4am argo workflow name: level-zero-stable-insert-2
```

### Milvus Log

pods:
```
level0-insert-1-milvus-datanode-67654ffdf4-gkmkm                  1/1     Running                           0                 98m     10.104.6.194    4am-node13   <none>           <none>
level0-insert-1-milvus-datanode-67654ffdf4-jprtk                  1/1     Running                           0                 98m     10.104.30.168   4am-node38   <none>           <none>
level0-insert-1-milvus-indexnode-57c85c4898-k8tsh                 1/1     Running                           0                 98m     10.104.34.104   4am-node37   <none>           <none>
level0-insert-1-milvus-mixcoord-567c54fc49-dfjjv                  1/1     Running                           0                 98m     10.104.25.175   4am-node30   <none>           <none>
level0-insert-1-milvus-proxy-58d5cb959-4dbxp                      1/1     Running                           0                 98m     10.104.32.189   4am-node39   <none>           <none>
level0-insert-1-milvus-querynode-6c8c689866-hjxkl                 1/1     Running                           3 (47m ago)       98m     10.104.33.158   4am-node36   <none>           <none>
level0-insert-1-milvus-querynode-6c8c689866-xcxmp                 1/1     Running                           0                 98m     10.104.27.27    4am-node31   <none>           <none>
```

**Comment by ThreadDao** [comment]
Fixed `master-20231211-3c32ba24-amd64`
