### ISSUE TITLE
[Bug]: Miss error detection when search_list exceeds limit

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#29020]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20231206-4a067a4c-amd64 
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):     rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.4
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Miss error detection when search_list exceeds limit. 
param: {'search_list': 9999999999}

This causes milvus to restart every time search with invalid search_list.

```
[2023-12-06 14:50:36 - INFO - ci_test]: search_params: {'metric_type': 'L2', 'params': {'search_list': 9999999999}} (test_search.py:343)
[2023-12-06 14:50:36 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.023880591921634053, 0.06612565847230101, 0.8779193744307221, 0.7031879175939921, 0.868487825605817, 0.9922488326996011, 0.027607642180522585, 0.23450095629938705, 0.37591316072416037, 0.4120059024796978, 0.48991023575797576, 0.6393231017397432, 0.5329467363250286, 0.7917255008138984, 0.50343828......, kwargs: {} (api_request.py:62)
[2023-12-06 14:50:40 - WARNING - pymilvus.decorators]: [search] retry:4, cost: 0.27s, reason: <_InactiveRpcError: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.102.9.58:19530: Failed to connect to remote host: Connection refused> (decorators.py:88)
[2023-12-06 14:50:40 - WARNING - pymilvus.decorators]: [search] retry:5, cost: 0.81s, reason: <_InactiveRpcError: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.102.9.58:19530: Failed to connect to remote host: Connection refused> (decorators.py:88)
[2023-12-06 14:50:41 - WARNING - pymilvus.decorators]: [search] retry:6, cost: 2.43s, reason: <_InactiveRpcError: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.102.9.58:19530: Failed to connect to remote host: Connection refused> (decorators.py:88)
[2023-12-06 14:50:43 - WARNING - pymilvus.decorators]: [search] retry:7, cost: 3.00s, reason: <_InactiveRpcError: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.102.9.58:19530: Failed to connect to remote host: Connection refused> (decorators.py:88)
[2023-12-06 14:50:46 - WARNING - pymilvus.decorators]: [search] retry:8, cost: 3.00s, reason: <_InactiveRpcError: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.102.9.58:19530: Failed to connect to remote host: Connection refused> (decorators.py:88)
[2023-12-06 14:50:49 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=101, message=failed to search: collection not loaded[collection=446128323338579452])>, <Time:{'RPC start': '2023-12-06 14:50:36.943360', 'RPC error': '2023-12-06 14:50:49.731442'}> (decorators.py:128)
[2023-12-06 14:50:49 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/zilliz/nico/milvus/tests/python_client/utils/api_request.py", line 32, in inner_wrapper
    res = func(*args, **_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/nico/milvus/tests/python_client/utils/api_request.py", line 63, in api_request
    return func(*arg, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/orm/collection.py", line 782, in search
    resp = conn.search(
           ^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 129, in handler
    raise e from e
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 125, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 164, in handler
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 104, in handler
    raise e from e
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 68, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 748, in search
    return self._execute_search(request, timeout, round_decimal=round_decimal, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 709, in _execute_search
    raise e from e
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 702, in _execute_search
    check_status(response.status)
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/client/utils.py", line 54, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=101, message=failed to search: collection not loaded[collection=446128323338579452])>
 (api_request.py:45)
[2023-12-06 14:50:49 - ERROR - ci_test]: (api_response) : <MilvusException: (code=101, message=failed to search: collection not loaded[collection=446128323338579452])> (api_request.py:46)
```

### Expected Behavior

report error

### Steps To Reproduce

```markdown
@pytest.mark.tags(CaseLabel.L2)
    @pytest.mark.parametrize("index, params",
                             zip(ct.all_index_types[:7],
                                 ct.default_index_params[:7]))
    def test_search_invalid_params_type(self, index, params):
        """
        target: test search with invalid search params
        method: test search with invalid params type
        expected: raise exception and report the error
        """
        if index == "FLAT":
            pytest.skip("skip in FLAT index")
        # 1. initialize with data
        collection_w, _, _, insert_ids = self.init_collection_general(prefix, True, 5000,
                                                                      is_index=False)[0:4]
        # 2. create index and load
        default_index = {"index_type": index, "params": params, "metric_type": "L2"}
        collection_w.create_index("float_vector", default_index)
        collection_w.load()
        # 3. search
        invalid_search_params = cf.gen_invalid_search_params_type()
        for invalid_search_param in invalid_search_params:
            if index == invalid_search_param["index_type"]:
                search_params = {"metric_type": "L2",
                                 "params": invalid_search_param["search_params"]}
                log.info("search_params: {}".format(search_params))
                collection_w.search(vectors[:default_nq], default_search_field,
                                    search_params, default_limit,
                                    default_search_exp,
                                    check_task=CheckTasks.err_res,
                                    check_items={"err_code": 65535,
                                                 "err_msg": "failed to search: invalid param in json:"
                                                            " invalid json key invalid_key"})
```

### Milvus Log

[master-pod.log](https://github.com/milvus-io/milvus/files/13577615/master-pod.log)

pod: 
```
kubectl get pods|grep master-latest-lzgsl
master-latest-lzgsl-etcd-0                                     1/1     Running            0                 3h45m
master-latest-lzgsl-milvus-standalone-7fd9c54469-qhkrm         0/1     Running            7 (71s ago)       3h45m
master-latest-lzgsl-minio-78558bc79b-pnbrj                     1/1     Running            0                 3h45m

```

state:
```
    State:          Running
      Started:      Wed, 06 Dec 2023 14:50:40 +0800
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Wed, 06 Dec 2023 14:34:54 +0800
      Finished:     Wed, 06 Dec 2023 14:50:39 +0800
    Ready:          True
    Restart Count:  7

Events:
  Type     Reason   Age                   From     Message
  ----     ------   ----                  ----     -------
  Warning  BackOff  23m (x15 over 34m)    kubelet  Back-off restarting failed container
  Normal   Created  7m4s (x8 over 3h51m)  kubelet  Created container standalone
  Normal   Started  7m4s (x8 over 3h51m)  kubelet  Started container standalone
  Normal   Pulled   7m4s (x7 over 3h26m)  kubelet  Container image "harbor.milvus.io/milvus/milvus:master-20231206-4a067a4c-amd64" already present on machine


```

**Comment by xiaofan-luan** [comment]
good catch! 
this is should be an issue of knowhere

**Comment by liliu-z** [comment]
Checking

**Comment by liliu-z** [comment]
Looks this is caused by int overflow from Segcore. @Presburger can you help take a further check?

/assign @Presburger

**Comment by userdsr** [comment]
I'm struggling with this problem, could some one help me solve it? thaks very much.

**Comment by Presburger** [comment]
@NicoYuan1986  have you load the collection?

**Comment by NicoYuan1986** [comment]
> @NicoYuan1986 have you load the collection?

![image](https://github.com/milvus-io/milvus/assets/109071306/b627c152-6d50-4a63-91c6-901102622db8)
The collection has been loaded before search.

**Comment by cqy123456** [comment]
https://github.com/milvus-io/milvus-docs/pull/2411

**Comment by yanliang567** [comment]
@cqy123456 @Presburger  if it is ready for verification, please assign back to @NicoYuan1986
