### ISSUE TITLE
[Bug]: Error occurred after version upgrade

### ISSUE THREAD

**Issue by QAQwaitme** [milvus-io/milvus#29139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.13
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.11
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

This error occurred when I upgraded Springboot version to 3.1.6，But using version 3.1.5 does not have this issue, while the Java SDK version is 2.2.11
2023-12-12T14:28:46.728+08:00 ERROR 99832 --- [           main] i.m.client.AbstractMilvusGrpcClient      : HasPartitionRequest RPC failed!

io.grpc.StatusRuntimeException: UNKNOWN
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271) ~[grpc-stub-1.46.0.jar:1.46.0]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252) ~[grpc-stub-1.46.0.jar:1.46.0]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165) ~[grpc-stub-1.46.0.jar:1.46.0]
	at io.milvus.grpc.MilvusServiceGrpc$MilvusServiceBlockingStub.hasPartition(MilvusServiceGrpc.java:4516) ~[milvus-sdk-java-2.3.3.jar:na]
	at io.milvus.client.AbstractMilvusGrpcClient.hasPartition(AbstractMilvusGrpcClient.java:973) ~[milvus-sdk-java-2.3.3.jar:na]
	at io.milvus.client.MilvusServiceClient.lambda$hasPartition$18(MilvusServiceClient.java:390) ~[milvus-sdk-java-2.3.3.jar:na]
Caused by: java.lang.UnsupportedOperationException: null
	at io.grpc.netty.AbstractHttp2Headers.isEmpty(AbstractHttp2Headers.java:40) ~[grpc-netty-1.46.0.jar:1.46.0]
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:419) ~[netty-codec-http2-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:352) ~[netty-codec-http2-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onHeadersRead(Http2InboundFrameLogger.java:56) ~[netty-codec-http2-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader$2.processFragment(DefaultHttp2FrameReader.java:476) ~[netty-codec-http2-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readHeadersFrame(DefaultHttp2FrameReader.java:484) ~[netty-codec-http2-4.1.101.Final.jar:4.1.101.Final]

**Comment by yanliang567** [comment]
/assign @yhmo 
could you please help on this?
/unassign

**Comment by yhmo** [comment]
There is a workaround in this thread:
https://github.com/milvus-io/milvus-sdk-java/issues/706

**Comment by yhmo** [comment]
The error is caused by a compatible issue of grpc-java package: https://github.com/grpc/grpc-java/issues/10665
The grpc-java 1.59.1 contains a fix for this ussue: https://github.com/grpc/grpc-java/releases/tag/v1.59.1

We need to upgrade this package from 1.46 to 1.59.1 for Java SDK. I will do some local testing by using grpc-java 1.59.1, hopefully upgrade to 1.59.1 in the next Java SDK minor version.
