### ISSUE TITLE
[Bug]: Querynode terminated due to segcore crash during concurrent search and upsert

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#29132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20231211-3c32ba24-amd64
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.3.3.post1.dev8
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. deploy milvus enable level zero segment
```
  config:
    dataCoord:
      enableActiveStandby: true
      segment:
        enableLevelZero: true
    indexCoord:
      enableActiveStandby: true
    log:
      level: debug
    mixCoord:
      enableActiveStandby: true
    queryCoord:
      enableActiveStandby: true
    rootCoord:
      enableActiveStandby: true
```

2. create collection `fouram_zpWoelF3` with 2 shards and a **partition-key field**
3. index -> insert 10m -> flush -> index again -> load
4. concurrent search + upsert + flush, some search failed and one querynode terminated with segcore error

[qn_xkbg4_pre.log](https://github.com/milvus-io/milvus/files/13643430/qn_xkbg4_pre.log)

```
_ZN6milvus9SkipIndexD4Ev
    /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SkipIndex.h:36 pc=0x7f700dbe70df
_ZN6milvus7segcore24SegmentInternalInterfaceD4Ev
    /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentInterface.h:118 pc=0x7f700dbe70df
_ZN6milvus7segcore13SegmentSealedD4Ev
    /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealed.h:26 pc=0x7f700dbe70df
_ZN6milvus7segcore17SegmentSealedImplD2Ev
    /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:945 pc=0x7f700dbe70df
_ZN6milvus7segcore17SegmentSealedImplD0Ev
    /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:956 pc=0x7f700dbe73fc
runtime.asmcgocall
```

### Steps To Reproduce

```markdown
- argo workflow: https://argo-workflows.zilliz.cc/archived-workflows/qa/bdf4a654-a85f-48ec-8156-44a094d6717f?nodeId=test-delete-stable-partition-key-10

- grafana: https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=qa-milvus&var-instance=delta-par-key3&var-collection=All&var-app_name=milvus&from=1702296403000&to=1702335640000
```

### Milvus Log

4am pods:
```
delta-par-key3-milvus-datanode-569589c884-p9hhh                   1/1     Running                           0                  15h     10.104.4.18     4am-node11   <none>           <none>
delta-par-key3-milvus-datanode-569589c884-wvt66                   1/1     Running                           0                  15h     10.104.31.10    4am-node34   <none>           <none>
delta-par-key3-milvus-indexnode-5cd55c48bb-8vddx                  1/1     Running                           0                  15h     10.104.12.183   4am-node17   <none>           <none>
delta-par-key3-milvus-mixcoord-6bd5956697-hgm45                   1/1     Running                           0                  15h     10.104.1.109    4am-node10   <none>           <none>
delta-par-key3-milvus-proxy-6fc76b4bb7-vpphp                      1/1     Running                           0                  15h     10.104.30.62    4am-node38   <none>           <none>
delta-par-key3-milvus-querynode-b9f5576-5b4gl                     1/1     Running                           1 (12h ago)        15h     10.104.6.98     4am-node13   <none>           <none>
delta-par-key3-milvus-querynode-b9f5576-xkbg4                     1/1     Running                           1 (15h ago)        15h     10.104.19.178   4am-node28   <none>           <none>
```

**Comment by yah01** [comment]
/assign @MrPresent-Han 
could you help on this?

**Comment by ThreadDao** [comment]
After pod re-running:
1. release-load collection
2. concurrent search + upsert + flush -> querynode terminated
```
W20231212 04:40:16.929692 26910 ivf.cc:211] [KNOWHERE][MatchNlist][milvus] Row num 1 match nlist 1
WARNING clustering 1 points to 1 centroids: please provide at least 39 training points
I20231212 04:40:16.929766 26910 time_recorder.cc:49] [KNOWHERE][PrintTimeRecord][milvus] Build index: done (0.078739 ms)
I20231212 04:40:16.929833 26910 SegmentSealedImpl.cpp:220] [SEGCORE][LoadFieldData][milvus] finish loading segment field, segmentID:446246848225864728, fieldID:101
[signal SIGSEGV: segmentation violation code=0x1 addr=0x9 pc=0x7fb9cf950c0f]

runtime stack:
runtime.throw({0x503af34?, 0x7fb600000002?})
    /usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7fab3d95a610 sp=0x7fab3d95a5e0 pc=0x1a4e09d
runtime.sigpanic()
    /usr/local/go/src/runtime/signal_unix.go:825 +0x3e9 fp=0x7fab3d95a670 sp=0x7fab3d95a610 pc=0x1a65f09

goroutine 10107407 [syscall, locked to thread]:
I20231212 04:40:16.935693 26946 SegmentSealedImpl.cpp:220] [SEGCORE][LoadFieldData][milvus] finish loading segment field, segmentID:446246848225864728, fieldID:1
_ZNKSt10_HashtableIN6fluent9NamedTypeIlN6milvus4impl10FieldIdTagEJNS0_10ComparableENS0_8HashableEEEESt4pairIKS7_St13unordered_mapIlNS2_17FieldChunkMetricsESt4hashIlESt8equal_toIlESaIS8_IKlSB_EEEESaISK_ENSt8__detail10_Select1stESE_IS7_ESC_IS7_ENSM_18_Mod_range_hashingENSM_20_Default_ranged_hashENSM_20_Prime_rehash_policyENSM_17_Hashtable_traitsILb0ELb0ELb1EEEE19_M_find_before_nodeEmRS9_m
    /usr/include/c++/9/bits/hashtable.h:1577 pc=0x7fb9cf950c0f
_ZNKSt10_HashtableIN6fluent9NamedTypeIlN6milvus4impl10FieldIdTagEJNS0_10ComparableENS0_8HashableEEEESt4pairIKS7_St13unordered_mapIlNS2_17FieldChunkMetricsESt4hashIlESt8equal_toIlESaIS8_IKlSB_EEEESaISK_ENSt8__detail10_Select1stESE_IS7_ESC_IS7_ENSM_18_Mod_range_hashingENSM_20_Default_ranged_hashENSM_20_Prime_rehash_policyENSM_17_Hashtable_traitsILb0ELb0ELb1EEEE12_M_find_nodeEmRS9_m
    /usr/include/c++/9/bits/hashtable.h:687 pc=0x7fb9cf950c0f
_ZNSt8__detail9_Map_baseIN6fluent9NamedTypeIlN6milvus4impl10FieldIdTagEJNS1_10ComparableENS1_8HashableEEEESt4pairIKS8_St13unordered_mapIlNS3_17FieldChunkMetricsESt4hashIlESt8equal_toIlESaIS9_IKlSC_EEEESaISL_ENS_10_Select1stESF_IS8_ESD_IS8_ENS_18_Mod_range_hashingENS_20_Default_ranged_hashENS_20_Prime_rehash_policyENS_17_Hashtable_traitsILb0ELb0ELb1EEELb1EEixERSA_
    /usr/include/c++/9/bits/hashtable_policy.h:697 pc=0x7fb9cf950c0f
```
[qn_xkbg4_pre2.log](https://github.com/milvus-io/milvus/files/13644003/qn_xkbg4_pre2.log)

**Comment by ThreadDao** [comment]
https://argo-workflows.zilliz.cc/archived-workflows/qa/17219c77-153d-4c1c-bc5d-e60bd560861d
reproduce image: master-20231213-fe1eeae2
concurrent insert + delete + flush + search:
```
[2023/12/13 08:24:30.416 +00:00] [INFO] [querynodev2/services.go:601] ["start to release segments"] [traceID=8583e01f846aa8e885ddb44a1edde390] [collectionID=446287135098798417] [shard=delta-par-key4-rootcoord-dml_1_446287135098798417v1] [segmentIDs="[446287135113183107]"] [currentNodeID=7]
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x7f437ac24ad3]

runtime stack:
runtime.throw({0x504b79a?, 0x7f4032c2c960?})
    /usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7f3c1917fa80 sp=0x7f3c1917fa50 pc=0x1a5309d
runtime.sigpanic()
    /usr/local/go/src/runtime/signal_unix.go:825 +0x3e9 fp=0x7f3c1917fae0 sp=0x7f3c1917fa80 pc=0x1a6af09

goroutine 5518980 [syscall]:
_ZNSt8__detail16_Hashtable_allocISaINS_10_Hash_nodeISt4pairIKlN6milvus17FieldChunkMetricsEELb0EEEEE19_M_deallocate_nodesEPS7_
    /usr/include/c++/9/bits/hashtable_policy.h:2123 pc=0x7f437ac24ad3
_ZNSt10_HashtableIlSt4pairIKlN6milvus17FieldChunkMetricsEESaIS4_ENSt8__detail10_Select1stESt8equal_toIlESt4hashIlENS6_18_Mod_range_hashingENS6_20_Default_ranged_hashENS6_20_Prime_rehash_policyENS6_17_Hashtable_traitsILb0ELb0ELb1EEEE5clearEv
    /usr/include/c++/9/bits/hashtable.h:2063 pc=0x7f437ac24ad3
```
[qn_jm_pre.log](https://github.com/milvus-io/milvus/files/13658693/qn_jm_pre.log)

**Comment by ThreadDao** [comment]
fixed
