### ISSUE TITLE
[Bug]: [Nightly] Flush will fail for timeout when existing multi collections 

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#29156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 76757e5
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):     kafka & pulsar 
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.3.post1.dev8
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Flush will fail for timeout when existing multi collections.
```
[2023-12-12T22:59:43.374Z] [2023-12-12 21:06:52 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)
[2023-12-12T22:59:43.374Z] [2023-12-12 21:10:13 - WARNING - pymilvus.decorators]: [93mRetry timeout: 180s[0m (decorators.py:94)
[2023-12-12T22:59:43.374Z] [2023-12-12 21:10:13 - ERROR - pymilvus.decorators]: RPC error: [flush], <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for flush timeout, collection: collection_PtsjSt0D)>, <Time:{'RPC start': '2023-12-12 21:06:52.782723', 'RPC error': '2023-12-12 21:10:13.586996'}> (decorators.py:128)
[2023-12-12T22:59:43.374Z] [2023-12-12 21:10:13 - ERROR - ci_test]: Traceback (most recent call last):
[2023-12-12T22:59:43.374Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper
[2023-12-12T22:59:43.374Z]     res = func(*args, **_kwargs)
[2023-12-12T22:59:43.374Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request
[2023-12-12T22:59:43.374Z]     return func(*arg, **kwargs)
[2023-12-12T22:59:43.374Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 314, in flush
[2023-12-12T22:59:43.374Z]     conn.flush([self.name], timeout=timeout, **kwargs)
[2023-12-12T22:59:43.374Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 129, in handler
[2023-12-12T22:59:43.374Z]     raise e from e
[2023-12-12T22:59:43.374Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 125, in handler
[2023-12-12T22:59:43.374Z]     return func(*args, **kwargs)
[2023-12-12T22:59:43.374Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 164, in handler
[2023-12-12T22:59:43.374Z]     return func(self, *args, **kwargs)
[2023-12-12T22:59:43.374Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 95, in handler
[2023-12-12T22:59:43.374Z]     raise MilvusException(
[2023-12-12T22:59:43.374Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for flush timeout, collection: collection_PtsjSt0D)>
[2023-12-12T22:59:43.374Z]  (api_request.py:45)
[2023-12-12T22:59:43.374Z] [2023-12-12 21:10:13 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for flush timeout, collection: collection_PtsjSt0D)> (api_request.py:46)
```

### Expected Behavior

pass

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.3/36/pipeline/237
2. log: [artifacts-milvus-distributed-pulsar-nightly-36-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.3/36/artifact/artifacts-milvus-distributed-pulsar-nightly-36-pymilvus-e2e-logs.tar.gz)
3. failed cases:
```
FAILED testcases/test_collection.py::TestCollectionMultiCollections::test_collection_count_multi_collections_l2[2001] - AssertionError
FAILED testcases/test_collection.py::TestCollectionMultiCollections::test_collection_count_multi_collections_l2[1000] - AssertionError
FAILED testcases/test_collection.py::TestCollectionMultiCollections::test_collection_count_multi_collections_binary[2001] - AssertionError
FAILED testcases/test_collection.py::TestCollectionMultiCollections::test_collection_count_multi_collections_binary[1] - AssertionError
FAILED testcases/test_collection.py::TestCollectionMultiCollections::test_collection_count_multi_collections_binary[1000] - AssertionError
```

**Comment by NicoYuan1986** [comment]
reproduce:
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.3/37/pipeline/237/

**Comment by NicoYuan1986** [comment]
keep reproducing.

**Comment by xiaofan-luan** [comment]
hit similar issue on ut
test_delete_entities

**Comment by xiaofan-luan** [comment]
link https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-28625/24/pipeline/

**Comment by NicoYuan1986** [comment]
not reproduced since the pr merged. master-20231218-438f39e2
