### ISSUE TITLE
[Bug]: index not exist at vectordb test

### ISSUE THREAD

**Issue by shmuelDash** [milvus-io/milvus#29165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvus-2.0.2
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.2.5
- OS(Ubuntu or CentOS): RHEL 8.7
- CPU/Memory: intel Xeon 48 CPUs, 256GB RAM
- GPU: none
- Others:
```
vectorDB is on main branch

### Current Behavior

when I'm running the first tests on vectorDB benchmark I'm getting the following error:
pymilvus.exceptions.MilvusException: <MilvusException: (code=25, message=index not exist)>

full printout is:

2023-12-11 16:46:03,437 | WARNING: [1/1] case {'label': <CaseLabel.Performance: 2>, 'dataset': {'data': {'name': 'OpenAI', 'size': 500000, 'dim': 1536, 'metric_type': <MetricType.COSINE: 'COSINE'>, 'use_shuffled': True, '_size_label': {50000: 'SMALL', 500000: 'MEDIUM', 5000000: 'LARGE'}}}, 'db': 'Milvus-test4'} failed to run, reason=<MilvusException: (code=25, message=index not exist)> (interface.py:163) (2184461)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/vectordb_bench/interface.py", line 144, in _async_task_v2
    case_res.metrics = runner.run(drop_old)
                       ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vectordb_bench/backend/task_runner.py", line 98, in run
    return self._run_perf_case(drop_old)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vectordb_bench/backend/task_runner.py", line 145, in _run_perf_case
    raise e from None
  File "/usr/local/lib/python3.11/site-packages/vectordb_bench/backend/task_runner.py", line 130, in _run_perf_case
    _, load_dur = self._load_train_data()
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vectordb_bench/backend/utils.py", line 41, in inner
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vectordb_bench/backend/task_runner.py", line 157, in _load_train_data
    raise e from None
  File "/usr/local/lib/python3.11/site-packages/vectordb_bench/backend/task_runner.py", line 155, in _load_train_data
    runner.run()
  File "/usr/local/lib/python3.11/site-packages/vectordb_bench/backend/runner/serial_runner.py", line 149, in run
    count, dur = self._insert_all_batches()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vectordb_bench/backend/utils.py", line 41, in inner
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vectordb_bench/backend/runner/serial_runner.py", line 118, in _insert_all_batches
    raise e from e
  File "/usr/local/lib/python3.11/site-packages/vectordb_bench/backend/runner/serial_runner.py", line 109, in _insert_all_batches
    count = future.result(timeout=self.timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
pymilvus.exceptions.MilvusException: <MilvusException: (code=25, message=index not exist)>
2023-12-11 16:46:03,439 | INFO |Task summery: run_id=039e7, task_label=2023121116 (models.py:231)
2023-12-11 16:46:03,439 | INFO |DB     | db_label case                 label      | load_dur    qps        latency(p99)    recall        max_load_count | label (models.py:231)
2023-12-11 16:46:03,439 | INFO |------ | -------- -------------------- ---------- | ----------- ---------- --------------- ------------- -------------- | ----- (models.py:231)
2023-12-11 16:46:03,439 | INFO |Milvus | test4    Performance1536D500K 2023121116 | 0.0         0.0        0.0             0.0           0              | x     (models.py:231)
2023-12-11 16:46:03,439 | INFO: write results to disk /usr/local/lib/python3.11/site-packages/vectordb_bench/results/Milvus/result_20231211_2023121116_milvus.json (models.py:129) (2184461)
2023-12-11 16:46:03,440 | INFO: Succes to finish task: label=2023121116, run_id=039e7fed93a141f68e1c706465278c30 (interface.py:183) (2184461)
^C  Stopping...
2023-12-13 11:51:26,109 | INFO: exit streamlit... (__main__.py:33) (2761986)

**Comment by yanliang567** [comment]
/assign @XuanYang-cn 
please help to take a look
/unassign
