### ISSUE TITLE
[Bug]: Flush timeout after upgrade from v2.2.14 to 2.3-20231212-af6714ef in standalone mode

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#29185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.2.14 to 2.3-20231212-af6714ef
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```

[2023-12-12T09:04:11.555Z] -------------

[2023-12-12T09:04:11.555Z] <name>: deploy_test_index_type_HNSW_is_compacted_is_compacted_segment_status_all_is_string_indexed_is_string_indexed_replica_number_0_is_deleted_is_deleted_data_size_3000

[2023-12-12T09:04:11.555Z] <description>: 

[2023-12-12T09:04:11.555Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'descrip......  (api_request.py:37)

[2023-12-12T09:04:11.555Z] [2023-12-12 08:55:17 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2023-12-12T09:04:11.555Z] [2023-12-12 08:58:19 - WARNING - pymilvus.decorators]: Retry timeout: 180s (decorators.py:94)

[2023-12-12T09:04:11.555Z] [2023-12-12 08:58:19 - ERROR - pymilvus.decorators]: RPC error: [flush], <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for flush timeout, collection: deploy_test_index_type_HNSW_is_compacted_is_compacted_segment_status_all_is_string_indexed_is_string_indexed_replica_number_0_is_deleted_is_deleted_data_size_3000)>, <Time:{'RPC start': '2023-12-12 08:55:17.051183', 'RPC error': '2023-12-12 08:58:19.906295'}> (decorators.py:128)

[2023-12-12T09:04:11.555Z] [2023-12-12 08:58:19 - ERROR - ci_test]: Traceback (most recent call last):

[2023-12-12T09:04:11.555Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2023-12-12T09:04:11.555Z]     res = func(*args, **_kwargs)

[2023-12-12T09:04:11.555Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2023-12-12T09:04:11.555Z]     return func(*arg, **kwargs)

[2023-12-12T09:04:11.555Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 314, in flush

[2023-12-12T09:04:11.555Z]     conn.flush([self.name], timeout=timeout, **kwargs)

[2023-12-12T09:04:11.555Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 129, in handler

[2023-12-12T09:04:11.555Z]     raise e from e

[2023-12-12T09:04:11.555Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 125, in handler

[2023-12-12T09:04:11.555Z]     return func(*args, **kwargs)

[2023-12-12T09:04:11.555Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 164, in handler

[2023-12-12T09:04:11.555Z]     return func(self, *args, **kwargs)

[2023-12-12T09:04:11.555Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 95, in handler

[2023-12-12T09:04:11.555Z]     raise MilvusException(

[2023-12-12T09:04:11.555Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for flush timeout, collection: deploy_test_index_type_HNSW_is_compacted_is_compacted_segment_status_all_is_string_indexed_is_string_indexed_replica_number_0_is_deleted_is_deleted_data_size_3000)>

[2023-12-12T09:04:11.555Z]  (api_request.py:45)

[2023-12-12T09:04:11.555Z] [2023-12-12 08:58:19 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for flush timeout, collection: deploy_test_index_type_HNSW_is_compacted_is_compacted_segment_status_all_is_string_indexed_is_string_indexed_replica_number_0_is_deleted_is_deleted_data_size_3000)> (api_request.py:46)
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_for_release_cron/detail/deploy_test_for_release_cron/1145/pipeline

log:
[artifacts-rocksmq-standalone-upgrade-1145-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/13667615/artifacts-rocksmq-standalone-upgrade-1145-server-logs.1.tar.gz)
[artifacts-rocksmq-standalone-upgrade-1145-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/13667619/artifacts-rocksmq-standalone-upgrade-1145-pytest-logs.tar.gz)

### Anything else?

cluster: 4am
namespace: chaos-testing
release name: rocksmq-standalone-upgrade-1145

**Comment by weiliu1031** [comment]
should be fixed by https://github.com/milvus-io/milvus/pull/29244, please verify this with latest image.
