### ISSUE TITLE
[Bug]: grpc.FutureTimeoutError when connect to milvus remotely

### ISSUE THREAD

**Issue by dove-young** [milvus-io/milvus#29208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.3
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): none 
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.3.4
- OS(Ubuntu or CentOS): RHEL
- CPU/Memory: 4/32GB
- GPU: 
- Others:
```

### Current Behavior

When I try python code like this

```
from pymilvus import (
    connections,
    utility,
)

connections.connect(
  alias="default",
  user='username',
  password='password',
  host='<my ip addr>',
  port='19530'
)

collection_list = utility.list_collections()
for c in collection_list:
    vlogger.info(f'collection = {c}')

```

I got errors like this

```
Traceback (most recent call last):
  File "/root/jupyter/virtualenv/slack-dev-3.10/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 133, in _wait_for_channel_ready
    grpc.channel_ready_future(self._channel).result(timeout=timeout)
  File "/root/jupyter/virtualenv/slack-dev-3.10/lib/python3.10/site-packages/grpc/_utilities.py", line 162, in result
    self._block(timeout)
  File "/root/jupyter/virtualenv/slack-dev-3.10/lib/python3.10/site-packages/grpc/_utilities.py", line 106, in _block
    raise grpc.FutureTimeoutError()
grpc.FutureTimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/jupyter/instana-slack-app-dev/replace-index.py", line 46, in <module>
    connections.connect(
  File "/root/jupyter/virtualenv/slack-dev-3.10/lib/python3.10/site-packages/pymilvus/orm/connections.py", line 356, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/root/jupyter/virtualenv/slack-dev-3.10/lib/python3.10/site-packages/pymilvus/orm/connections.py", line 302, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/root/jupyter/virtualenv/slack-dev-3.10/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 136, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on <my ip addr>:19530. Timeout)>
```

I can run the same code on the VM where milvus is running.  But it does not run in another VM.  And this is not always the case.  Sometime it works. 

I can verify the network connection is good by running `tcpdump -i any port 19530` on the VM on which milvus is running. 

Milvus rans as docker container, like this 

```
NAME                IMAGE                                      COMMAND                                                                                                        SERVICE      CREATED        STATUS                  PORTS
milvus-etcd         quay.io/coreos/etcd:v3.5.5                 "etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd"   etcd         19 hours ago   Up 19 hours             2379-2380/tcp
milvus-minio        minio/minio:RELEASE.2023-03-20T20-16-18Z   "/usr/bin/docker-entrypoint.sh minio server /minio_data"                                                       minio        19 hours ago   Up 19 hours (healthy)   9000/tcp
milvus-standalone   milvusdb/milvus:v2.3.3                     "/tini -- milvus run standalone"                                                                               standalone   19 hours ago   Up 19 hours             0.0.0.0:9091->9091/tcp, 0.0.0.0:19530->19530/tcp
```

**Comment by dove-young** [comment]
Restart milvus sometimes recover this problem

**Comment by yanliang567** [comment]
@dove-young could you please attach the full milvus logs? please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
If installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs.

/assign @dove-young 
/unassign

**Comment by dove-young** [comment]
I refactored by application to use a queue and to query milvus db from a single connect. And I still reproduced this problem. 

Here is the milvus container log.  I don't use those script since it works only on K8S. This is a docker compose installation. 

[milvus.log.zip](https://github.com/milvus-io/milvus/files/13699009/milvus.log.zip)

**Comment by dove-young** [comment]
Here is my installation status
```
CONTAINER ID   IMAGE                                      COMMAND                  CREATED      STATUS                        PORTS           NAMES
7c678965363d   milvusdb/milvus:v2.3.3                     "/tini -- milvus run…"   3 days ago   Exited (0) 2 days ago                         milvus-standalone
6884f8f9922c   minio/minio:RELEASE.2023-03-20T20-16-18Z   "/usr/bin/docker-ent…"   3 days ago   Up 3 days (healthy)           9000/tcp        milvus-minio
d95034fe417c   quay.io/coreos/etcd:v3.5.5                 "etcd -advertise-
cli…"   3 days ago   Up 3 days                     2379-2380/tcp   milvus-etcd
```

Here is the etcd log

[etcd.log.zip](https://github.com/milvus-io/milvus/files/13699030/etcd.log.zip)

for minio, I don't get much log msgs. all logs here

```
 docker logs 6884f8f9922c
WARNING: MINIO_ACCESS_KEY and MINIO_SECRET_KEY are deprecated.
         Please use MINIO_ROOT_USER and MINIO_ROOT_PASSWORD
WARNING: Detected default credentials 'minioadmin:minioadmin', we recommend that you change these values with 'MINIO_ROOT_USER' and 'MINIO_ROOT_PASSWORD' environment variables
MinIO Object Storage Server
Copyright: 2015-2023 MinIO, Inc.
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Version: RELEASE.2023-03-20T20-16-18Z (go1.19.7 linux/amd64)

Status:         1 Online, 0 Offline.
API: http://172.22.0.3:9000  http://127.0.0.1:9000
Console: http://172.22.0.3:38705 http://127.0.0.1:38705

Documentation: https://min.io/docs/minio/linux/index.html
Warning: The standard parity is set to 0. This can lead to data loss.

 You are running an older version of MinIO released 8 months ago
 Update: Run `mc admin update`
```

**Comment by gadregayatri** [comment]
I am facing the same problem. How did you solve it?

**Comment by yanliang567** [comment]
@LoveEachDay any comments
