### ISSUE TITLE
[Bug]: Create index failed with error `CreateIndex failed: creating multiple indexes on same field is not supported` after upgrade from v2.2.14 to 2.3-20231215-97d71c25

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#29269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.2.14 -->2.3-20231215-97d71c25
- Deployment mode(standalone or cluster):standalone and cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2023-12-17T08:53:23.764Z] + python3 scripts/action_after_upgrade.py --host 10.255.155.70 --data_size 3000

[2023-12-17T08:53:24.325Z] 2023-12-17 08:53:24.089 | INFO     | MainThread |__main__:<module>:101 - data size: 3000

[2023-12-17T08:53:24.325Z] 2023-12-17 08:53:24.117 | INFO     | MainThread |__main__:<module>:105 - create index for flat start

[2023-12-17T08:53:24.580Z] 2023-12-17 08:53:24.329 | INFO     | MainThread |utils:create_index_flat:146 - 

[2023-12-17T08:53:24.581Z] Create index for FLAT...

[2023-12-17T08:53:24.581Z] 2023-12-17 08:53:24.435 | INFO     | MainThread |utils:create_index_flat:149 - <Collection>:

[2023-12-17T08:53:24.581Z] -------------

[2023-12-17T08:53:24.581Z] <name>: task_4_FLAT

[2023-12-17T08:53:24.581Z] <description>: test collection

[2023-12-17T08:53:24.581Z] <schema>: {'auto_id': False, 'description': 'test collection', 'fields': [{'name': 'count', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'random_value', 'description': '', 'type': <DataType.DOUBLE: 11>}, {'name': 'float_vector', 'description': '', 'type': <DataType.FLOAT_VECTOR: 101>, 'params': {'dim': 128}}]}

[2023-12-17T08:53:24.581Z] 

[2023-12-17T08:53:24.581Z] RPC error: [get_replicas], <MilvusException: (code=400, message=failed to get replicas by collection: replica not found[replica=446379046569441255])>, <Time:{'RPC start': '2023-12-17 08:53:24.436043', 'RPC error': '2023-12-17 08:53:24.438801'}>

[2023-12-17T08:53:24.582Z] 2023-12-17 08:53:24.438 | INFO     | MainThread |utils:create_index_flat:156 - <MilvusException: (code=400, message=failed to get replicas by collection: replica not found[replica=446379046569441255])>

[2023-12-17T08:53:24.582Z] RPC error: [create_index], <MilvusException: (code=65535, message=CreateIndex failed: creating multiple indexes on same field is not supported)>, <Time:{'RPC start': '2023-12-17 08:53:24.439021', 'RPC error': '2023-12-17 08:53:24.451778'}>

[2023-12-17T08:53:24.582Z] Traceback (most recent call last):

[2023-12-17T08:53:24.582Z]   File "scripts/action_after_upgrade.py", line 106, in <module>

[2023-12-17T08:53:24.582Z]     create_index_flat()

[2023-12-17T08:53:24.582Z]   File "/home/jenkins/agent/workspace/tests/python_client/deploy/scripts/utils.py", line 158, in create_index_flat

[2023-12-17T08:53:24.582Z]     c.create_index(field_name="float_vector", index_params=default_flat_index)

[2023-12-17T08:53:24.582Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 1208, in create_index

[2023-12-17T08:53:24.582Z]     return conn.create_index(self._name, field_name, index_params, timeout=timeout, **kwargs)

[2023-12-17T08:53:24.582Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 129, in handler

[2023-12-17T08:53:24.582Z]     raise e from e

[2023-12-17T08:53:24.582Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 125, in handler

[2023-12-17T08:53:24.582Z]     return func(*args, **kwargs)

[2023-12-17T08:53:24.582Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 164, in handler

[2023-12-17T08:53:24.582Z]     return func(self, *args, **kwargs)

[2023-12-17T08:53:24.582Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 104, in handler

[2023-12-17T08:53:24.582Z]     raise e from e

[2023-12-17T08:53:24.582Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 68, in handler

[2023-12-17T08:53:24.582Z]     return func(*args, **kwargs)

[2023-12-17T08:53:24.582Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 842, in create_index

[2023-12-17T08:53:24.582Z]     check_status(status)

[2023-12-17T08:53:24.582Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/utils.py", line 54, in check_status

[2023-12-17T08:53:24.582Z]     raise MilvusException(status.code, status.reason, status.error_code)

[2023-12-17T08:53:24.582Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=CreateIndex failed: creating multiple indexes on same field is not supported)>

script returned exit code 1
```

### Expected Behavior

It runs well with this script when upgrading from v2.2.14 to 2.3-20231214-a108bf7b-amd64

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_for_release_cron/detail/deploy_test_for_release_cron/1166/pipeline

log:
[artifacts-pulsar-cluster-upgrade-1166-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/13699270/artifacts-pulsar-cluster-upgrade-1166-server-logs.tar.gz)
[artifacts-pulsar-cluster-upgrade-1166-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/13699271/artifacts-pulsar-cluster-upgrade-1166-pytest-logs.tar.gz)

**Comment by zhuwenxing** [comment]
verified and passed in 2.3-20231220-3182b9df

**Comment by yanliang567** [comment]
close as comments aove
