### ISSUE TITLE
[Bug]: [Nightly] Load failed reporting node not match

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#29265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 3f7d636
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.3.post1.dev8
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

 Load failed reporting node not match.
```
[2023-12-17T19:55:48.292Z] [2023-12-17 19:34:01 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 180], kwargs: {} (api_request.py:62)
[2023-12-17T19:55:48.292Z] [2023-12-17 19:34:54 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=65535, message=stack trace: /go/src/github.com/milvus-io/milvus/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace
[2023-12-17T19:55:48.292Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:543 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call
[2023-12-17T19:55:48.292Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:557 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall
[2023-12-17T19:55:48.292Z] /go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:87 github.com/milvus-io/milvus/internal/distributed/querynode/client.wrapGrpcCall[...]
[2023-12-17T19:55:48.292Z] /go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:170 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).LoadPartitions
[2023-12-17T19:55:48.293Z] /go/src/github.com/milvus-io/milvus/internal/querycoordv2/session/cluster.go:178 github.com/milvus-io/milvus/internal/querycoordv2/session.(*QueryCluster).LoadPartitions.func1
[2023-12-17T19:55:48.293Z] /go/src/github.com/milvus-io/milvus/internal/querycoordv2/session/cluster.go:271 github.com/milvus-io/milvus/internal/querycoordv2/session.(*QueryCluster).send
[2023-12-17T19:55:48.293Z] /go/src/github.com/milvus-io/milvus/internal/querycoordv2/session/cluster.go:175 github.com/milvus-io/milvus/internal/querycoordv2/session.(*QueryCluster).LoadPartitions
[2023-12-17T19:55:48.293Z] /go/src/github.com/milvus-io/milvus/internal/querycoordv2/job/utils.go:99 github.com/milvus-io/milvus/internal/querycoordv2/job.loadPartitions
[2023-12-17T19:55:48.293Z] /go/src/github.com/milvus-io/milvus/internal/querycoordv2/job/job_load.go:164 github.com/milvus-io/milvus/internal/querycoordv2/job.(*LoadCollectionJob).Execute: rpc error: code = Unknown desc = node not match[expectedNodeID=6][actualNodeID=13])>, <Time:{'RPC start': '2023-12-17 19:34:01.420190', 'RPC error': '2023-12-17 19:34:54.519344'}> (decorators.py:128)
[2023-12-17T19:55:48.293Z] [2023-12-17 19:34:54 - ERROR - ci_test]: Traceback (most recent call last):
[2023-12-17T19:55:48.293Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper
[2023-12-17T19:55:48.293Z]     res = func(*args, **_kwargs)
[2023-12-17T19:55:48.293Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request
[2023-12-17T19:55:48.293Z]     return func(*arg, **kwargs)
[2023-12-17T19:55:48.293Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 419, in load
[2023-12-17T19:55:48.293Z]     conn.load_collection(
[2023-12-17T19:55:48.293Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 129, in handler
[2023-12-17T19:55:48.293Z]     raise e from e
[2023-12-17T19:55:48.293Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 125, in handler
[2023-12-17T19:55:48.293Z]     return func(*args, **kwargs)
[2023-12-17T19:55:48.293Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 164, in handler
[2023-12-17T19:55:48.293Z]     return func(self, *args, **kwargs)
[2023-12-17T19:55:48.293Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 104, in handler
[2023-12-17T19:55:48.293Z]     raise e from e
[2023-12-17T19:55:48.293Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 68, in handler
[2023-12-17T19:55:48.293Z]     return func(*args, **kwargs)
[2023-12-17T19:55:48.293Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 982, in load_collection
[2023-12-17T19:55:48.293Z]     check_status(response)
[2023-12-17T19:55:48.293Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/utils.py", line 54, in check_status
[2023-12-17T19:55:48.293Z]     raise MilvusException(status.code, status.reason, status.error_code)
[2023-12-17T19:55:48.293Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=stack trace: /go/src/github.com/milvus-io/milvus/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace
[2023-12-17T19:55:48.293Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:543 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call
[2023-12-17T19:55:48.293Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:557 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall
[2023-12-17T19:55:48.293Z] /go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:87 github.com/milvus-io/milvus/internal/distributed/querynode/client.wrapGrpcCall[...]
[2023-12-17T19:55:48.293Z] /go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:170 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).LoadPartitions
[2023-12-17T19:55:48.293Z] /go/src/github.com/milvus-io/milvus/internal/querycoordv2/session/cluster.go:178 github.com/milvus-io/milvus/internal/querycoordv2/session.(*QueryCluster).LoadPartitions.func1
[2023-12-17T19:55:48.293Z] /go/src/github.com/milvus-io/milvus/internal/querycoordv2/session/cluster.go:271 github.com/milvus-io/milvus/internal/querycoordv2/session.(*QueryCluster).send
[2023-12-17T19:55:48.293Z] /go/src/github.com/milvus-io/milvus/internal/querycoordv2/session/cluster.go:175 github.com/milvus-io/milvus/internal/querycoordv2/session.(*QueryCluster).LoadPartitions
[2023-12-17T19:55:48.293Z] /go/src/github.com/milvus-io/milvus/internal/querycoordv2/job/utils.go:99 github.com/milvus-io/milvus/internal/querycoordv2/job.loadPartitions
[2023-12-17T19:55:48.293Z] /go/src/github.com/milvus-io/milvus/internal/querycoordv2/job/job_load.go:164 github.com/milvus-io/milvus/internal/querycoordv2/job.(*LoadCollectionJob).Execute: rpc error: code = Unknown desc = node not match[expectedNodeID=6][actualNodeID=13])>
[2023-12-17T19:55:48.293Z]  (api_request.py:45)
[2023-12-17T19:55:48.293Z] [2023-12-17 19:34:54 - ERROR - ci_test]: (api_response) : <MilvusException: (code=65535, message=stack trace: /go/src/github.com/milvus-io/milvus/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace
[2023-12-17T19:55:48.293Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:543 github.com/milvus-io/milvus/internal/util/grpcclient.(*Cli...... (api_request.py:46)
```

### Expected Behavior

load successfully

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/590/pipeline/237/
2. log: [artifacts-milvus-distributed-pulsar-nightly-590-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/590/artifact/artifacts-milvus-distributed-pulsar-nightly-590-pymilvus-e2e-logs.tar.gz)
3. collection name: search_collection_sbGMqFpy
4. failed time: [2023-12-17T19:34:56.108Z] [gw4] [ 80%] FAILED testcases/test_search.py::TestSearchDiskann::test_search_with_delete_data[32-False-False-False]

**Comment by NicoYuan1986** [comment]
grafana link: https://grafana-ci.zilliz.cc/explore?orgId=1&left=%5B%221702833904317%22,%221702844648358%22,%22prometheus%22,%7B%22refId%22:%22A%22,%22instant%22:true,%22range%22:true,%22exemplar%22:true,%22expr%22:%22%7Bcreated_by_name%3D%5C%22mdp-590-n-milvus-querynode-84ddf46848%5C%22%7D%22%7D%5D

query node restart:
```
mdp-590-n-milvus-querynode-84ddf46848-9v4tf      1/1     Running       1 (22m ago)    119m   10.105.1.122   ci-node10   <none>           <none>
```

panic log: 
```
2023-12-18T03:33:58.956814076+08:00 stdout F I20231217 19:33:58.956746 11871 SegmentSealedImpl.cpp:220] [SEGCORE][LoadFieldData][milvus] finish loading segment field, segmentID:446388259697661015, fieldID:102
2023-12-18T03:33:58.958453771+08:00 stderr F [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7fbbbcad8c0f]
2023-12-18T03:33:58.958467063+08:00 stderr F
2023-12-18T03:33:58.958470557+08:00 stderr F runtime stack:
2023-12-18T03:33:58.958478489+08:00 stderr F runtime.throw({0x50644a5?, 0x7fb800000002?})
2023-12-18T03:33:58.958505465+08:00 stderr F    /usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7fb31c426610 sp=0x7fb31c4265e0 pc=0x1a5e0dd
2023-12-18T03:33:58.95852542+08:00 stderr F runtime.sigpanic()
2023-12-18T03:33:58.958545474+08:00 stderr F    /usr/local/go/src/runtime/signal_unix.go:825 +0x3e9 fp=0x7fb31c426670 sp=0x7fb31c426610 pc=0x1a75f49
2023-12-18T03:33:58.958567817+08:00 stderr F
2023-12-18T03:33:58.958583253+08:00 stderr F goroutine 242375 [syscall, locked to thread]:
2023-12-18T03:33:58.958607667+08:00 stderr F _ZNKSt10_HashtableIN6fluent9NamedTypeIlN6milvus4impl10FieldIdTagEJNS0_10ComparableENS0_8HashableEEEESt4pairIKS7_St13unordered_mapIlNS2_17FieldChunkMetricsESt4hashIlESt8equal_toIlESaIS8_IKlSB_EEEESaISK_ENSt8__detail10_Select1stESE_IS7_ESC_IS7_ENSM_18_Mod_range_hashingENSM_20_Default_ranged_hashENSM_20_Prime_rehash_policyENSM_17_Hashtable_traitsILb0ELb0ELb1EEEE19_M_find_before_nodeEmRS9_m
2023-12-18T03:33:58.95861492+08:00 stderr F     /usr/include/c++/9/bits/hashtable.h:1577 pc=0x7fbbbcad8c0f
2023-12-18T03:33:58.958618202+08:00 stderr F _ZNKSt10_HashtableIN6fluent9NamedTypeIlN6milvus4impl10FieldIdTagEJNS0_10ComparableENS0_8HashableEEEESt4pairIKS7_St13unordered_mapIlNS2_17FieldChunkMetricsESt4hashIlESt8equal_toIlESaIS8_IKlSB_EEEESaISK_ENSt8__detail10_Select1stESE_IS7_ESC_IS7_ENSM_18_Mod_range_hashingENSM_20_Default_ranged_hashENSM_20_Prime_rehash_policyENSM_17_Hashtable_traitsILb0ELb0ELb1EEEE12_M_find_nodeEmRS9_m
2023-12-18T03:33:58.958633771+08:00 stderr F    /usr/include/c++/9/bits/hashtable.h:687 pc=0x7fbbbcad8c0f
2023-12-18T03:33:58.95864452+08:00 stderr F _ZNSt8__detail9_Map_baseIN6fluent9NamedTypeIlN6milvus4impl10FieldIdTagEJNS1_10ComparableENS1_8HashableEEEESt4pairIKS8_St13unordered_mapIlNS3_17FieldChunkMetricsESt4hashIlESt8equal_toIlESaIS9_IKlSC_EEEESaISL_ENS_10_Select1stESF_IS8_ESD_IS8_ENS_18_Mod_range_hashingENS_20_Default_ranged_hashENS_20_Prime_rehash_policyENS_17_Hashtable_traitsILb0ELb0ELb1EEELb1EEixERSA_

```

**Comment by NicoYuan1986** [comment]
not reproduced for 1 week. master-20231228-a8b76293
