### ISSUE TITLE
[Bug]: The mixcoord cpu is fully loaded and the memory continues to grow until it oomkilled

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#29296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20231215-26409d80-amd64
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.3.3.post1.dev3
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. milvus disable L0 segment
- mixcoord resources
```
    Limits:
      cpu:     1
      memory:  4Gi
    Requests:
      cpu:      1
      memory:   4Gi
```
3. create collection `fouram_rHOPRfRv` with a partition_key field, and num_partition 128
4. insert 10m-128d data -> index -> flush -> index again -> load
5. concurrent upsert + flush + search
```
    concurrent_params:
      concurrent_number: 100 
      during_time: '6h'
      interval: 60
    concurrent_tasks:
      -   
        type: search
        weight: 2
        params:
          nq: 100 
          top_k: 100 
          search_param:
            ef: 128 
          timeout: 600 
      -   
        type: flush
        weight: 1
        params:
          timeout: 600 
      -   
        type: upsert
        weight: 4
        params:
          nb: 300 
          timeout: 600 
          start_id: 10000000
          random_id: true
          random_vector: true
```
6. mixcoord oom, it's resource usage:
![image](https://github.com/milvus-io/milvus/assets/27288593/cc40571b-09da-4928-b3eb-6012baf647ab)
![image](https://github.com/milvus-io/milvus/assets/27288593/653b1bd3-8a7a-4c4d-b0f3-0cb90cdc711c)

7. querynode terminated, maybe related with issue #29132
```
[2023/12/15 11:44:42.219 +00:00] [DEBUG] [segments/collection.go:187] ["collection ref decrement"] [collectionID=446333455662580195] [refCount=4968]
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x7fb1e4f10ad3]

runtime stack:
runtime.throw({0x5063376?, 0x7fafc0000000?})
    /usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7f4ac21d5a80 sp=0x7f4ac21d5a50 pc=0x1a5e0dd
runtime.sigpanic()
    /usr/local/go/src/runtime/signal_unix.go:825 +0x3e9 fp=0x7f4ac21d5ae0 sp=0x7f4ac21d5a80 pc=0x1a75f49

goroutine 14828844 [syscall]:
_ZNSt8__detail16_Hashtable_allocISaINS_10_Hash_nodeISt4pairIKlN6milvus17FieldChunkMetricsEELb0EEEEE19_M_deallocate_nodesEPS7_
    /usr/include/c++/9/bits/hashtable_policy.h:2123 pc=0x7fb1e4f10ad3
_ZNSt10_HashtableIlSt4pairIKlN6milvus17FieldChunkMetricsEESaIS4_ENSt8__detail10_Select1stESt8equal_toIlESt4hashIlENS6_18_Mod_range_hashingENS6_20_Default_ranged_hashENS6_20_Prime_rehash_policyENS6_17_Hashtable_traitsILb0ELb0ELb1EEEE5clearEv
    /usr/include/c++/9/bits/hashtable.h:2063 pc=0x7fb1e4f10ad3
_ZNSt10_HashtableIlSt4pairIKlN6milvus17FieldChunkMetricsEESaIS4_ENSt8__detail10_Select1stESt8equal_toIlESt4hashIlENS6_18_Mod_range_hashingENS6_20_Default_ranged_hashENS6_20_Prime_rehash_policyENS6_17_Hashtable_traitsILb0ELb0ELb1EEEED4Ev
    /usr/include/c++/9/bits/hashtable.h:1387 pc=0x7fb1e4f10ad3
_ZNSt13unordered_mapIlN6milvus17FieldChunkMetricsESt4hashIlESt8equal_toIlESaISt4pairIKlS1_EEED4Ev
    /usr/include/c++/9/bits/unordered_map.h:102 pc=0x7fb1e4f10ad3
_ZNSt4pairIKN6fluent9NamedTypeIlN6milvus4impl10FieldIdTagEJNS0_10ComparableENS0_8HashableEEEESt13unordered_mapIlNS2_17FieldChunkMetricsESt4hashIlESt8equal_toIlESaIS_IKlSA_EEEED4Ev
    /usr/include/c++/9/bits/stl_pair.h:208 pc=0x7fb1e4f10ad3
_ZN9__gnu_cxx13new_allocatorINSt8__detail10_Hash_nodeISt4pairIKN6fluent9NamedTypeIlN6milvus4impl10FieldIdTagEJNS4_10ComparableENS4_8HashableEEEESt13unordered_mapIlNS6_17FieldChunkMetricsESt4hashIlESt8equal_toIlESaIS3_IKlSE_EEEELb0EEEE7destroyISN_EEvPT_
    /usr/include/c++/9/ext/new_allocator.h:152 pc=0x7fb1e4f10ad3
_ZNSt16allocator_traitsISaINSt8__detail10_Hash_nodeISt4pairIKN6fluent9NamedTypeIlN6milvus4impl10FieldIdTagEJNS3_10ComparableENS3_8HashableEEEESt13unordered_mapIlNS5_17FieldChunkMetricsESt4hashIlESt8equal_toIlESaIS2_IKlSD_EEEELb0EEEEE7destroyISM_EEvRSO_PT_
    /usr/include/c++/9/bits/alloc_traits.h:496 pc=0x7fb1e4f10ad3
_ZNSt8__detail16_Hashtable_allocISaINS_10_Hash_nodeISt4pairIKN6fluent9NamedTypeIlN6milvus4impl10FieldIdTagEJNS3_10ComparableENS3_8HashableEEEESt13unordered_mapIlNS5_17FieldChunkMetricsESt4hashIlESt8equal_toIlESaIS2_IKlSD_EEEELb0EEEEE18_M_deallocate_nodeEPSN_
    /usr/include/c++/9/bits/hashtable_policy.h:2102 pc=0x7fb1e4f10ad3
_ZNSt8__detail16_Hashtable_allocISaINS_10_Hash_nodeISt4pairIKN6fluent9NamedTypeIlN6milvus4impl10FieldIdTagEJNS3_10ComparableENS3_8HashableEEEESt13unordered_mapIlNS5_17FieldChunkMetricsESt4hashIlESt8equal_toIlESaIS2_IKlSD_EEEELb0EEEEE19_M_deallocate_nodesEPSN_
    /usr/include/c++/9/bits/hashtable_policy.h:2124 pc=0x7fb1e4f10ad3
_ZNSt10_HashtableIN6fluent9NamedTypeIlN6milvus4impl10FieldIdTagEJNS0_10ComparableENS0_8HashableEEEESt4pairIKS7_St13unordered_mapIlNS2_17FieldChunkMetricsESt4hashIlESt8equal_toIlESaIS8_IKlSB_EEEESaISK_ENSt8__detail10_Select1stESE_IS7_ESC_IS7_ENSM_18_Mod_range_hashingENSM_20_Default_ranged_hashENSM_20_Prime_rehash_policyENSM_17_Hashtable_traitsILb0ELb0ELb1EEEE5clearEv
    /usr/include/c++/9/bits/hashtable.h:2063 pc=0x7fb1e4f10ad3
_ZNSt10_HashtableIN6fluent9NamedTypeIlN6milvus4impl10FieldIdTagEJNS0_10ComparableENS0_8HashableEEEESt4pairIKS7_St13unordered_mapIlNS2_17FieldChunkMetricsESt4hashIlESt8equal_toIlESaIS8_IKlSB_EEEESaISK_ENSt8__detail10_Select1stESE_IS7_ESC_IS7_ENSM_18_Mod_range_hashingENSM_20_Default_ranged_hashENSM_20_Prime_rehash_policyENSM_17_Hashtable_traitsILb0ELb0ELb1EEEED2Ev
    /usr/include/c++/9/bits/hashtable.h:1387 pc=0x7fb1e4f10ad3
_ZNSt13unordered_mapIN6fluent9NamedTypeIlN6milvus4impl10FieldIdTagEJNS0_10ComparableENS0_8HashableEEEES_IlNS2_17FieldChunkMetricsESt4hashIlESt8equal_toIlESaISt4pairIKlS8_EEES9_IS7_ESB_IS7_ESaISD_IKS7_SH_EEED4Ev
    /usr/include/c++/9/bits/unordered_map.h:102 pc=0x7fb1e4f540df
_ZN6milvus9SkipIndexD4Ev
```
[qn_r4tvm_pre.log](https://github.com/milvus-io/milvus/files/13703295/qn_r4tvm_pre.log)

### Steps To Reproduce

```markdown
- 4am argo workflow: https://argo-workflows.zilliz.cc/archived-workflows/qa/a3b260a7-114e-4518-9dad-98c7008b7927?nodeId=test-delete-stable-par-key-1

- grafana metrics: https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=qa-milvus&var-instance=delta-par-key6&var-collection=All&var-app_name=milvus&from=1702626600000&to=1702657800000
```

### Milvus Log

pods:
```
delta-par-key6-milvus-datanode-5cf95c9bcf-d2jnq                   1/1     Running            0                3d3h    10.104.26.191   4am-node32   <none>           <none>
delta-par-key6-milvus-datanode-5cf95c9bcf-vpc9j                   1/1     Running            0                3d3h    10.104.34.18    4am-node37   <none>           <none>
delta-par-key6-milvus-indexnode-755f86c56c-llcsv                  1/1     Running            0                3d3h    10.104.6.124    4am-node13   <none>           <none>
delta-par-key6-milvus-mixcoord-84757bf8f4-s2nc5                   1/1     Running            4 (2d6h ago)     3d3h    10.104.6.116    4am-node13   <none>           <none>
delta-par-key6-milvus-proxy-78978d5bf4-zxbwz                      1/1     Running            0                3d3h    10.104.19.50    4am-node28   <none>           <none>
delta-par-key6-milvus-querynode-77c8cdc579-8sjnl                  1/1     Running            0                3d3h    10.104.34.17    4am-node37   <none>           <none>
delta-par-key6-milvus-querynode-77c8cdc579-r4tvm                  1/1     Running            1 (3d ago)       3d3h    10.104.27.136   4am-node31   <none>           <none>
```

**Comment by ThreadDao** [comment]
I will try the case with more cou and memory

**Comment by yanliang567** [comment]
/assign @czs007 
is this something related the issue about mixcoord you are investigating?
/unassign

**Comment by ThreadDao** [comment]
I tried this case with mixcoord cpu.limit=4 and memory.limit=8G, the mixcoord resource usage is:
![image](https://github.com/milvus-io/milvus/assets/27288593/ef1b0dae-1ca8-40e7-b7eb-bddba9a4c881)

- metrics: https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=qa-milvus&var-instance=level-zero-par-key-1&var-collection=All&var-app_name=milvus&from=1702911813000&to=1702957773000

pods:
```
level-zero-par-key-1-milvus-datanode-78bc4bcc6f-fpxwj             1/1     Running            0                10h     10.104.12.137   4am-node17   <none>           <none>
level-zero-par-key-1-milvus-datanode-78bc4bcc6f-jjtz6             1/1     Running            0                10h     10.104.14.226   4am-node18   <none>           <none>
level-zero-par-key-1-milvus-indexnode-59579cc9c7-84l6b            1/1     Running            0                10h     10.104.34.104   4am-node37   <none>           <none>
level-zero-par-key-1-milvus-mixcoord-8654746bcb-nhczw             1/1     Running            0                10h     10.104.12.136   4am-node17   <none>           <none>
level-zero-par-key-1-milvus-proxy-568bbb6fc6-2jt7v                1/1     Running            0                10h     10.104.34.103   4am-node37   <none>           <none>
level-zero-par-key-1-milvus-querynode-6855dcdc6f-7mxbv            1/1     Running            0                10h     10.104.1.220    4am-node10   <none>           <none>
level-zero-par-key-1-milvus-querynode-6855dcdc6f-9lvw5            1/1     Running            1 (4h43m ago)    10h     10.104.14.227   4am-node18   <none>           <none>
```

**Comment by xiaofan-luan** [comment]
this is under high priority

**Comment by ThreadDao** [comment]
before fixing:
![image](https://github.com/milvus-io/milvus/assets/27288593/b49096bf-921d-4a07-86e1-cafddf38bb57)

after fixing:
![image](https://github.com/milvus-io/milvus/assets/27288593/f32f696b-7919-433a-8c9e-9a7f99e8c041)

**Comment by ThreadDao** [comment]
@SimFG This problem occurred again in another test
- image: cardinal-milvus-io-2.3-b69543c-20231222
- Based on the collection of 50+ million data, do search + query + insert_delete_flush concurrently, the mixcoord being oomkilled multiple times
![image](https://github.com/milvus-io/milvus/assets/27288593/ca0545e0-d949-4418-b364-73dfe3f4c76b)

- grafana: - [grafana link](https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=qa-milvus&var-instance=laion1b-test-2&var-collection=All&var-app_name=milvus&from=1703329200000&to=1703395620000)

**Comment by xiaofan-luan** [comment]
We cleanup the map asyncly in a day.
Maybe we should change to 3 hours?

**Comment by xiaofan-luan** [comment]
but if we purge segment info it should increase that fast

**Comment by SimFG** [comment]
@ThreadDao Through the grafana panel, we can see that the dropped segments are increasing rapidly, which should be the core reason for this result.
![image](https://github.com/milvus-io/milvus/assets/21985684/0e5e9150-c352-4faa-865c-0f9f1e563a79)

**Comment by xiaofan-luan** [comment]
> @ThreadDao Through the grafana panel, we can see that the dropped segments are increasing rapidly, which should be the core reason for this result. ![image](https://private-user-images.githubusercontent.com/21985684/292698848-0e5e9150-c352-4faa-865c-0f9f1e563a79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0Nzg2NDMsIm5iZiI6MTcwMzQ3ODM0MywicGF0aCI6Ii8yMTk4NTY4NC8yOTI2OTg4NDgtMGU1ZTkxNTAtYzM1Mi00ZmFhLTg2NWMtMGY5ZjFlNTYzYTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDA0MjU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxOGQzM2ZkZTVmMGRjY2U3NTU0YjUyZDE2NmM2MWE2OGIxMmQ0ZjJhNzFlOTk0MGZhYTJmYzBkNWYwNWJlMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zL6yQQP33eLIagS8cqqMWt1-HltzeaRv7ZojPe4h-ek)

When do we cleanup dropped segment?

**Comment by SimFG** [comment]
@xiaofan-luan This part is controlled by the `gc collector in datacoord`. The current setting should be three hours, but the current situation is a bit strange.
![image](https://github.com/milvus-io/milvus/assets/21985684/2d293a45-d6fb-4955-a654-6b1362ae0055)

**Comment by xiaofan-luan** [comment]
before we gc, we can cleanup the path?

**Comment by xiaofan-luan** [comment]
There are two guess why the gc is not happening:
1. index build can not catch up
2. flush can not catch up so gc is blocked

**Comment by ThreadDao** [comment]
mixcoord memory usage:
image: master-20240109-a903ae64-amd64
![image](https://github.com/milvus-io/milvus/assets/27288593/24503143-90cd-4736-aa84-ea6d4f52b8bb)
