### ISSUE TITLE
[Bug]: Standalone panic with error `Assertion pos < m_num_bits' failed.`

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#29405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: SimFG-leak-compaction-plan-2.3-147a94b-20231220
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2023/12/21 11:14:40.300 +00:00] [DEBUG] [delegator/delegator.go:370] ["query segments..."] [traceID=5e1ca0a61c2796c8a498da3e6552ffaa] [collectionID=446471474987665086] [channel=cdc-test-upstream-83-rootcoord-dml_3_446471474987665086v1] [replicaID=446471475146260482] [sealedNum=5] [growingNum=1]
[2023/12/21 11:14:40.300 +00:00] [DEBUG] [querynodev2/services.go:876] ["start do query segments"] [traceID=5e1ca0a61c2796c8a498da3e6552ffaa] [msgID=446472461976076290] [collectionID=446471474987665086] [channel=cdc-test-upstream-83-rootcoord-dml_3_446471474987665086v1] [scope=Streaming] [fromShardLeader=true] [segmentIDs="[446472335240678907]"]
[2023/12/21 11:14:40.300 +00:00] [DEBUG] [segments/validate.go:50] ["read target partitions"] [traceID=5e1ca0a61c2796c8a498da3e6552ffaa] [collectionID=446471474987665086] [partitionIDs="[446471474987665087]"]
[2023/12/21 11:14:40.300 +00:00] [DEBUG] [delegator/delegator_data.go:126] ["insert into growing segment"] [collectionID=446471474987665086] [channel=cdc-test-upstream-83-rootcoord-dml_2_446471474987665086v0] [replicaID=446471475146260482] [collectionID=446471474987665086] [segmentID=446472335240678906] [rowCount=1520] [maxTimestamp=446472461989183489]
[2023/12/21 11:14:40.300 +00:00] [DEBUG] [delegator/delegator.go:370] ["query segments..."] [traceID=5e1ca0a61c2796c8a498da3e6552ffaa] [collectionID=446471474987665086] [channel=cdc-test-upstream-83-rootcoord-dml_2_446471474987665086v0] [replicaID=446471475146260482] [sealedNum=5] [growingNum=1]
[2023/12/21 11:14:40.300 +00:00] [DEBUG] [querynodev2/services.go:876] ["start do query segments"] [traceID=5e1ca0a61c2796c8a498da3e6552ffaa] [msgID=446472461976076290] [collectionID=446471474987665086] [channel=cdc-test-upstream-83-rootcoord-dml_2_446471474987665086v0] [scope=Streaming] [fromShardLeader=true] [segmentIDs="[446472335240678906]"]
[2023/12/21 11:14:40.301 +00:00] [DEBUG] [segments/validate.go:50] ["read target partitions"] [traceID=5e1ca0a61c2796c8a498da3e6552ffaa] [collectionID=446471474987665086] [partitionIDs="[446471474987665087]"]
milvus: /home/milvus/.conan/data/boost/1.82.0/_/_/package/ca891ed5c8e67ebb3e46639c100abdbca6d8b11e/include/boost/dynamic_bitset/dynamic_bitset.hpp:1141: bool boost::dynamic_bitset<Block, Allocator>::test(boost::dynamic_bitset<Block, Allocator>::size_type) const [with Block = long unsigned int; Allocator = std::allocator<long unsigned int>; boost::dynamic_bitset<Block, Allocator>::size_type = long unsigned int]: Assertion `pos < m_num_bits' failed.
milvus: /home/milvus/.conan/data/boost/1.82.0/_/_/package/ca891ed5c8e67ebb3e46639c100abdbca6d8b11e/include/boost/dynamic_bitset/dynamic_bitset.hpp:1141: bool boost::dynamic_bitset<Block, Allocator>::test(boost::dynamic_bitset<Block, Allocator>::size_type) const [with Block = long unsigned int; Allocator = std::allocator<long unsigned int>; boost::dynamic_bitset<Block, Allocator>::size_type = long unsigned int]: Assertion `pos < m_num_bits' failed.
SIGABRT: abort
PC=0x7fe6802f903b m=188 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 22677 [syscall, locked to thread]:
I20231221 11:14:40.913969  1776 hnsw.cc:93] [KNOWHERE][operator()][Knowhere_Build8] HNSW build progress: 80%
I20231221 11:14:42.139459  1791 hnsw.cc:93] [KNOWHERE][operator()][Knowhere_Build9] HNSW build progress: 90%
I20231221 11:14:43.519284  1772 hnsw.cc:93] [KNOWHERE][operator()][Knowhere_Build7] HNSW build progress: 100%
I20231221 11:14:43.524678  2289 hnsw.cc:101] [KNOWHERE][Add][milvus] HNSW built with #points num:36538 #M:48 #max level:2 #ef_construction:500 #dim:128
I20231221 11:14:43.529356  2289 time_recorder.cc:49] [KNOWHERE][PrintTimeRecord][milvus] Build index: done (10444.300713 ms)
[2023/12/21 11:14:43.532 +00:00] [INFO] [indexnode/task.go:363] ["Successfully build index"] [buildID=446472335240478412] [Collection=446471474987665086] [SegmentID=446472335240477894] [currentIndexVersion=1]
non-Go function
	pc=0x7fe6802f903b
non-Go function
	pc=0x7fe6802d8858
non-Go function
	pc=0x7fe6802d8728
non-Go function
	pc=0x7fe6802ea005
_ZNK5boost14dynamic_bitsetImSaImEE4testEm
	/home/milvus/.conan/data/boost/1.82.0/_/_/package/ca891ed5c8e67ebb3e46639c100abdbca6d8b11e/include/boost/dynamic_bitset/dynamic_bitset.hpp:1141 pc=0x7fe685d0f24c
_ZNK5boost14dynamic_bitsetImSaImEEixEm
	/home/milvus/.conan/data/boost/1.82.0/_/_/package/ca891ed5c8e67ebb3e46639c100abdbca6d8b11e/include/boost/dynamic_bitset/dynamic_bitset.hpp:310 pc=0x7fe685d0a588
non-Go function
	pc=0x7fe685d03950
non-Go function
	pc=0x7fe685cfcdf3
_ZNK6milvus7segcore18SegmentGrowingImpl10find_firstElRKN5boost14dynamic_bitsetImSaImEEEb
	/go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentGrowingImpl.h:260 pc=0x7fe685d2578d
runtime.cgocall(0x4593280, 0xc006579d90)
	/usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc006579d68 sp=0xc006579d30 pc=0x19cf7bc
github.com/milvus-io/milvus/internal/querynodev2/segments._Cfunc_Retrieve(0x7fe43c400700, 0x7fe4350074e0, {0xc00920c240, 0xc00920c228, 0x0, {0x0, 0x0, 0x0, 0x0, 0x0, ...}}, ...)
	_cgo_gotypes.go:813 +0x55 fp=0xc006579d90 sp=0xc006579d68 pc=0x4379335
github.com/milvus-io/milvus/internal/querynodev2/segments.(*LocalSegment).Retrieve.func1.1(0x3?, 0xc03c9a7380?, {0xc00920c240, 0xc00920c228, 0x0, {0x0, 0x0, 0x0, 0x0, 0x0, ...}}, ...)
	/go/src/github.com/milvus-io/milvus/internal/querynodev2/segments/segment.go:404 +0xfa fp=0xc006579e28 sp=0xc006579d90 pc=0x438819a
github.com/milvus-io/milvus/internal/querynodev2/segments.(*LocalSegment).Retrieve.func1()
	/go/src/github.com/milvus-io/milvus/internal/querynodev2/segments/segment.go:404 +0xc5 fp=0xc006579f28 sp=0xc006579e28 pc=0x4387e65
github.com/milvus-io/milvus/pkg/util/conc.(*Pool[...]).Submit.func1()
	/go/src/github.com/milvus-io/milvus/pkg/util/conc/pool.go:81 +0xbc fp=0xc006579f88 sp=0xc006579f28 pc=0x3ed045c
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
	/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.2/worker.go:67 +0x97 fp=0xc006579fe0 sp=0xc006579f88 pc=0x33761f7
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc006579fe8 sp=0xc006579fe0 pc=0x1a409e1
created by github.com/panjf2000/ants/v2.(*goWorker).run
	/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.2/worker.go:48 +0x65
```

### Milvus Log

cluster: 4am
namespace: chaos-testing
release name: cdc-test-upstream-83

**Comment by longjiquan** [comment]
Concurrently read-write will cause this error easily.

**Comment by longjiquan** [comment]
should be fixed, please check this again
/assign @zhuwenxing
