### ISSUE TITLE
[Bug]: 当数据量到两百万条左右时，querynode 频繁重启，导致服务不稳定

### ISSUE THREAD

**Issue by obailiumingo** [milvus-io/milvus#29414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.14
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):   kafka
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 
- OS(Ubuntu or CentOS): redhat
- CPU/Memory: 16c,64G
- GPU: 
- Others:
```

### Current Behavior

随着数据量上升，当前数据量为200万条，大小16G左右(对象存储中的数据量)，最近出现了不稳定现象，querynode 频繁重启。
节点cpu 和 内存 使用率不足40%

1. 当出现以下日志后，立马重启
```
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7f91e576a00b m=2 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f91e576a00b
stack: frame={sp:0x7f91387d5e00, fp:0x0} stack=[0x7f9137fd68b8,0x7f91387d64b8)
0x00007f91387d5d00:  0x0000000000000000  0x00007f91e7a80b37
0x00007f91387d5d10:  0x00000000015c9ba5 <runtime.mstart+0x0000000000000005>  0xf28a1149d17eab00
0x00007f91387d5d20:  0x00000000015a4e46 <runtime.retake+0x00000000000001e6>  0x0000000000000011
0x00007f91387d5d30:  0x00000000000002a8  0x00007f910b408e90
0x00007f91387d5d40:  0x00007f910b4008c0  0x00007f910b408f08
0x00007f91387d5d50:  0x0000000000000011  0x00007f91e7a802ec
0x00007f91387d5d60:  0x0000000000000000  0x0000000000001000
0x00007f91387d5d70:  0x0000000000000001  0x0000000000000011
0x00007f91387d5d80:  0x00007f91387d5e3c  0x00007f91387d5e3d
0x00007f91387d5d90:  0x0000000000000000  0x0000002800017134
0x00007f91387d5da0:  0x0000000000000000  0x00007f91e7a41a1a
0x00007f91387d5db0:  0x000020000044701b  0x0000000001592c9c <runtime.netpoll+0x00000000000000dc>
0x00007f91387d5dc0:  0x00007f9100000005  0x00007f91387d5e10
0x00007f91387d5dd0:  0x0000000000000080  0x00007f9100000000
0x00007f91387d5de0:  0x0000000000000000  0x00007f9100000000
0x00007f91387d5df0:  0x0000000000000000  0x0000000000000000
0x00007f91387d5e00: <0x0000000000000000  0x00007f91387d5e40
0x00007f91387d5e10:  0x0000000000000000  0x0000000000000000
0x00007f91387d5e20:  0x0000000000000000  0x0000000000000000
0x00007f91387d5e20:  0x0000000000000000  0x0000000000000000
0x00007f91387d5e30:  0x0000000000000000  0x0000000000000000
0x00007f91387d5e40:  0x0000000000000000  0x0000000000000000
0x00007f91387d5e50:  0x0000000000000000  0x0000000000000000
0x00007f91387d5e60:  0x0000000000000000  0x0000000000000000
0x00007f91387d5e70:  0x0000000000000000  0x0000000000000000
0x00007f91387d5e80:  0xfffffffe7fffffff  0xffffffffffffffff
0x00007f91387d5e90:  0xffffffffffffffff  0xffffffffffffffff
0x00007f91387d5ea0:  0xffffffffffffffff  0xffffffffffffffff
0x00007f91387d5eb0:  0xffffffffffffffff  0xffffffffffffffff
0x00007f91387d5ec0:  0xffffffffffffffff  0xffffffffffffffff
0x00007f91387d5ed0:  0xffffffffffffffff  0xffffffffffffffff
0x00007f91387d5ee0:  0xffffffffffffffff  0xffffffffffffffff
0x00007f91387d5ef0:  0xffffffffffffffff  0xffffffffffffffff
runtime: unknown pc 0x7f91e576a00b
stack: frame={sp:0x7f91387d5e00, fp:0x0} stack=[0x7f9137fd68b8,0x7f91387d64b8)
0x00007f91387d5d00:  0x0000000000000000  0x00007f91e7a80b37
0x00007f91387d5d10:  0x00000000015c9ba5 <runtime.mstart+0x0000000000000005>  0xf28a1149d17eab00
0x00007f91387d5d20:  0x00000000015a4e46 <runtime.retake+0x00000000000001e6>  0x0000000000000011
0x00007f91387d5d30:  0x00000000000002a8  0x00007f910b408e90
0x00007f91387d5d40:  0x00007f910b4008c0  0x00007f910b408f08
0x00007f91387d5d50:  0x0000000000000011  0x00007f91e7a802ec
0x00007f91387d5d60:  0x0000000000000000  0x0000
```

2. 报错前有大量的不太正常的info日志,不确定是否有影响

```
[WARN] [flowgraph/node.go:204] ["Invalid operate message input"] ["input length"=0]
```

3.下面是和GC有关的日志
```
[2023/12/22 01:55:33.192 +00:00] [INFO] [gc/gc_tuner.go:84] ["GC Tune done"] ["previous GOGC"=200] ["heapuse "=353] ["total memory"=5670] ["next GC"=355] ["new GOGC"=200] [gc-pause=301.421µs] [gc-pause-end=1703210133190485410]
[2023/12/22 01:55:47.323 +00:00] [INFO] [gc/gc_tuner.go:84] ["GC Tune done"] ["previous GOGC"=200] ["heapuse "=349] ["total memory"=5670] ["next GC"=355] ["new GOGC"=200] [gc-pause=3.172713ms] [gc-pause-end=1703210147321132640]
```

**Comment by yanliang567** [comment]
@obailiumingo could you please provide the full milvus logs? please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation
/assign @obailiumingo 
/unassign

**Comment by xiaofan-luan** [comment]
seems that the thread creation is not expected.

What index type are you using?

This is an omp issue. Upgrade to 2.3.4 or 2.2.16 could solve the problem
