### ISSUE TITLE
[Bug]: [laion1b-test] querynode terminated with signal SIGSEGV: segmentation violation when searching on sealed

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#29828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: cardinal-milvus-io-2.3-66c8465-20240103
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. The collection laion_coll_4 has a partition-key field and 128 num_partitions. Collection has 50m-768dim data, DISKANN index

2. concurrent insert + delete + flush + search + query
![image](https://github.com/milvus-io/milvus/assets/27288593/1efaf3df-e6f4-4e74-ade3-90eaee5353eb)

4. The four querynodes terminated. One of two querynodes exit with code 134 and panic logs:
pod `laion1b-test-2-milvus-querynode-7b584b775c-q97vk` panic at 2023-01-05 17:48 (UTC)
pod `laion1b-test-2-milvus-querynode-7b584b775c-r8lzx` panic at 2023-01-05 19:17 (UTC)
```
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x7ff527609e04]
runtime stack:
runtime.throw({0x503dd26?, 0x7ff2a3c08790?})
	/usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7ff27f9dfdc0 sp=0x7ff27f9dfd90 pc=0x1a2709d
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:825 +0x3e9 fp=0x7ff27f9dfe20 sp=0x7ff27f9dfdc0 pc=0x1a3ef09
goroutine 159892 [syscall, locked to thread]:
non-Go function
	pc=0x7ff527609e04
operator()
	/go/src/github.com/milvus-io/milvus/internal/core/src/query/SearchOnSealed.cpp:48 pc=0x7ff52c28c9b3
_ZN6milvus5query19SearchOnSealedIndexERKNS_6SchemaERKNS_7segcore20SealedIndexingRecordERKNS_10SearchInfoEPKvlRKNS_10BitsetViewERNS_12SearchResultE
	/go/src/github.com/milvus-io/milvus/internal/core/src/query/SearchOnSealed.cpp:51 pc=0x7ff52c28c9b3
_ZNK6milvus7segcore17SegmentSealedImpl13vector_searchERNS_10SearchInfoEPKvlmRKNS_10BitsetViewERNS_12SearchResultE
	/go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:647 pc=0x7ff52c093fbb
_ZN6milvus5query19ExecPlanNodeVisitor17VectorVisitorImplINS_11FloatVectorEEEvRNS0_14VectorPlanNodeE
	/go/src/github.com/milvus-io/milvus/internal/core/src/query/visitors/ExecPlanNodeVisitor.cpp:120 pc=0x7ff52c11d580
runtime.cgocall(0x4618900, 0xc0007b7e10)
	/usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc0007b7de8 sp=0xc0007b7db0 pc=0x19ef7bc
github.com/milvus-io/milvus/internal/querynodev2/segments._Cfunc_Search(0x7ff060c61500, 0x7ff2ad40d300, 0x7ff2a5ffe280, {0xc00a034140, 0xc00a034150, 0x0, {0x0, 0x0, 0x0, 0x0, ...}}, ...)
	_cgo_gotypes.go:832 +0x55 fp=0xc0007b7e10 sp=0xc0007b7de8 pc=0x43fb955
github.com/milvus-io/milvus/internal/querynodev2/segments.(*LocalSegment).Search.func1.1(0x1a2a200?, 0xc00008f400?, {0xc00a034140, 0xc00a034150, 0x0, {0x0, 0x0, 0x0, 0x0, 0x0, ...}}, ...)
	/go/src/github.com/milvus-io/milvus/internal/querynodev2/segments/segment.go:362 +0xf9 fp=0xc0007b7e98 sp=0xc0007b7e10 pc=0x4409f39
github.com/milvus-io/milvus/internal/querynodev2/segments.(*LocalSegment).Search.func1()
	/go/src/github.com/milvus-io/milvus/internal/querynodev2/segments/segment.go:362 +0x94 fp=0xc0007b7f28 sp=0xc0007b7e98 pc=0x4409cf4
github.com/milvus-io/milvus/pkg/util/conc.(*Pool[...]).Submit.func1()
```

5. coredump file:
4am-node10
```
-rw-------  1 root root 41160433664 Jan  5 13:55 core-laion1b-test-2-milvus-querynode-7b584b775c-r8lzx-cardinal_search-8-1704484492
-rw-------  1 root root 58943950848 Jan  5 13:17 core-laion1b-test-2-milvus-querynode-7b584b775c-r8lzx-milvus-8-1704482271
```
4am-node21:
```
-rw------- 1 root root  37805674496 Jan  6 02:26 core-laion1b-test-2-milvus-querynode-7b584b775c-q97vk-cardinal_search-8-1704479163
-rw------- 1 root root 201357197312 Jan  6 01:48 core-laion1b-test-2-milvus-querynode-7b584b775c-q97vk-milvus-8-1704476911
```

### Steps To Reproduce

```markdown
argo: https://argo-workflows.zilliz.cc/archived-workflows/qa/4405fb98-0a37-477d-8858-0e0a301061b8?nodeId=laion1b-test-cron-1704456000
```

### Milvus Log

pods:
```
laion1b-test-2-milvus-querynode-7b584b775c-2mcxd                  1/1     Running            1 (3d15h ago)   4d22h   10.104.31.61    4am-node34   <none>           <none>
laion1b-test-2-milvus-querynode-7b584b775c-5pddf                  1/1     Running            1 (3d15h ago)   4d22h   10.104.20.188   4am-node22   <none>           <none>
laion1b-test-2-milvus-querynode-7b584b775c-84469                  1/1     Running            0               39h     10.104.13.57    4am-node16   <none>           <none>
laion1b-test-2-milvus-querynode-7b584b775c-8fxsr                  0/1     Error              0               4d22h   10.104.18.151   4am-node25   <none>           <none>
laion1b-test-2-milvus-querynode-7b584b775c-n5sls                  1/1     Running            0               4d22h   10.104.6.34     4am-node13   <none>           <none>
laion1b-test-2-milvus-querynode-7b584b775c-njkbb                  1/1     Running            0               4d22h   10.104.24.253   4am-node29   <none>           <none>
laion1b-test-2-milvus-querynode-7b584b775c-pldpl                  1/1     Running            0               4d22h   10.104.33.24    4am-node36   <none>           <none>
laion1b-test-2-milvus-querynode-7b584b775c-q97vk                  1/1     Running            2 (3d14h ago)   4d22h   10.104.16.44    4am-node21   <none>           <none>
laion1b-test-2-milvus-querynode-7b584b775c-r8lzx                  1/1     Running            2 (3d12h ago)   4d22h   10.104.1.211    4am-node10   <none>           <none>
laion1b-test-2-milvus-querynode-7b584b775c-xcz9w                  1/1     Running            0               4d22h   10.104.12.200   4am-node17   <none>           <none>
laion1b-test-2-milvus-querynode-7b584b775c-zpcf5                  1/1     Running            0               4d22h   10.104.13.199   4am-node16   <none>           <none>
```

### Anything else?

[Pod terminated reason and exitcode](https://grafana-4am.zilliz.cc/explore?orgId=1&left=%7B%22datasource%22:%22prometheus%22,%22queries%22:%5B%7B%22refId%22:%22B%22,%22expr%22:%22kube_pod_container_status_last_terminated_reason%7Bpod%3D~%5C%22laion1b-test-2-milvus-mixcoord-576578dcbd-ctwrl%5C%22,%20container%3D%5C%22mixcoord%5C%22%7D%22,%22range%22:true,%22hide%22:true%7D,%7B%22refId%22:%22A%22,%22expr%22:%22kube_pod_container_status_last_terminated_reason%7Bpod%3D~%5C%22laion1b-test-2-milvus-querynode-7b584b775c-.*%5C%22,%20container%3D%5C%22querynode%5C%22%7D%22,%22range%22:true,%22hide%22:true%7D,%7B%22refId%22:%22C%22,%22expr%22:%22kube_pod_container_status_last_terminated_exitcode%7Bpod%3D~%5C%22laion1b-test-2-milvus-querynode-7b584b775c-.*%5C%22,%20container%3D%5C%22querynode%5C%22%7D%22,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%221704456000000%22,%22to%22:%221704492060000%22%7D%7D)

**Comment by ThreadDao** [comment]
Fixed 2.3.6
