### ISSUE TITLE
[Bug]: [hybrid_search] Milvus crashed when run hybrid_search with invalid parameters to WeightedRanker

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#29840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 3d07b668
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0rc15
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Milvus crashed when hybrid_search with large number(1024) of reqs 

master-0109-imhkq-etcd-0                                        1/1     Running            0                  28h
master-0109-imhkq-milvus-standalone-594c8594bc-g7428            0/1     Error              1 (78s ago)        28h
master-0109-imhkq-minio-54db7b5f6d-xldkm                        1/1     Running            0                  28h

master-0109-imhkq-etcd-0                                        1/1     Running            0                  28h
master-0109-imhkq-milvus-standalone-594c8594bc-g7428            0/1     Error              2 (80s ago)        28h
master-0109-imhkq-minio-54db7b5f6d-xldkm                        1/1     Running            0                  28h

client error:
```
[2024-01-10 15:24:13 - DEBUG - ci_test]: (api_request)  : [Collection.hybrid_search] args: [[<pymilvus.client.abstract.AnnSearchRequest object at 0x138a24430>, <pymilvus.client.abstract.AnnSearchRequest object at 0x138a243a0>, <pymilvus.client.abstract.AnnSearchRequest object at 0x138a0bbb0>, <pymilvus.client.abstract.AnnSearchRequest object at 0x138a0baf0>, <pymilvus.client.abstract.AnnS......, kwargs: {} (api_request.py:62)
[2024-01-10 15:24:29 - WARNING - pymilvus.decorators]: [hybrid_search] retry:4, cost: 0.27s, reason: <_InactiveRpcError: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.102.9.123:19530: Failed to connect to remote host: Connection refused> (decorators.py:94)
[2024-01-10 15:24:29 - WARNING - pymilvus.decorators]: [hybrid_search] retry:5, cost: 0.81s, reason: <_InactiveRpcError: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.102.9.123:19530: Failed to connect to remote host: Connection refused> (decorators.py:94)
[2024-01-10 15:24:30 - WARNING - pymilvus.decorators]: [hybrid_search] retry:6, cost: 2.43s, reason: <_InactiveRpcError: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.102.9.123:19530: Failed to connect to remote host: Connection refused> (decorators.py:94)
[2024-01-10 15:24:33 - WARNING - pymilvus.decorators]: [hybrid_search] retry:7, cost: 3.00s, reason: <_InactiveRpcError: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.102.9.123:19530: Failed to connect to remote host: Connection refused> (decorators.py:94)
[2024-01-10 15:24:36 - WARNING - pymilvus.decorators]: [hybrid_search] retry:8, cost: 3.00s, reason: <_InactiveRpcError: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.102.9.123:19530: Failed to connect to remote host: Connection refused> (decorators.py:94)
[2024-01-10 15:24:39 - WARNING - pymilvus.decorators]: [hybrid_search] retry:9, cost: 3.00s, reason: <_InactiveRpcError: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.102.9.123:19530: Failed to connect to remote host: Connection refused> (decorators.py:94)
[2024-01-10 15:24:42 - WARNING - pymilvus.decorators]: [hybrid_search] retry:10, cost: 3.00s, reason: <_InactiveRpcError: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNKNOWN: ipv4:10.102.9.123:19530: Failed to connect to remote host: Connection refused> (decorators.py:94)
```

### Expected Behavior

hybrid search successfully

### Steps To Reproduce

```python
    @pytest.mark.tags(CaseLabel.L2)
    def test_hybrid_search_max_reqs_num(self, dim, enable_dynamic_field):
        """
        target: test hybrid search with maximum reqs number
        method: create connection, collection, insert and search
        expected: hybrid search successfully with limit(topK)
        """
        # 1. initialize collection with data
        multiple_dim_array = [dim, dim]
        collection_w, _, _, insert_ids, time_stamp = \
            self.init_collection_general(prefix, True, dim=dim, is_index=False,
                                         enable_dynamic_field=False, multiple_dim_array=multiple_dim_array)[0:5]
        # 2. extract vector field name
        vector_name_list = cf.extract_vector_field_name_list(collection_w)
        flat_index = {"index_type": "FLAT", "params": {}, "metric_type": "COSINE"}
        for vector_name in vector_name_list:
            collection_w.create_index(vector_name, flat_index)
        collection_w.create_index(ct.default_float_vec_field_name, flat_index)
        collection_w.load()
        reqs_max_num = 1024
        # 3. prepare search params
        req_list = []
        for i in range(reqs_max_num):
            search_param = {
                "data": [[random.random() for _ in range(dim)] for _ in range(1)],
                "anns_field": default_search_field,
                "param": {"metric_type": "COSINE"},
                "limit": default_limit,
                "expr": "int64 > 0"}
            req = AnnSearchRequest(**search_param)
            req_list.append(req)
        weights= [[random.random() for _ in range(1)] for _ in range(len(req_list))]
        # 4. hybrid search
        collection_w.hybrid_search(req_list, WeightedRanker(weights), default_limit,
                                   check_task=CheckTasks.check_search_results,
                                   check_items={"nq": 1,
                                                "ids": insert_ids,
                                                "limit": default_limit})
```

### Milvus Log

[max_reqs.log](https://github.com/milvus-io/milvus/files/13884399/max_reqs.log)

**Comment by binbinlv** [comment]
It is crashed when reqs number is 100 too.
```
[2024/01/10 07:41:41.065 +00:00] [DEBUG] [proxy/impl.go:2823] [tr/HybridSearch] [traceID=d99965cbc3f6e9c109d9653ec488f9a7] [msg="wait hybrid search result"] [duration=217.563831ms]
[2024/01/10 07:41:41.065 +00:00] [ERROR] [conc/options.go:54] ["Conc pool panicked"] [panic="interface conversion: interface {} is []interface {}, not float64"] [stack="github.com/milvus-io/milvus/pkg/util/conc.(*poolOption).antsOptions.func1\n\t/go/src/github.com/milvus-io/milvus/pkg/util/conc/options.go:54\ngithub.com/panjf2000/ants/v2.(*goWorker).run.func1.1\n\t/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.2/worker.go:54\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:884\ngithub.com/milvus-io/milvus/pkg/util/conc.(*Pool[...]).Submit.func1.1\n\t/go/src/github.com/milvus-io/milvus/pkg/util/conc/pool.go:74\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:884\nruntime.panicdottypeE\n\t/usr/local/go/src/runtime/iface.go:262\ngithub.com/milvus-io/milvus/internal/proxy.NewReScorer\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/reScorer.go:134\ngithub.com/milvus-io/milvus/internal/proxy.(*hybridSearchTask).Execute\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_hybrid_search.go:151\ngithub.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:455\ngithub.com/milvus-io/milvus/internal/proxy.(*taskScheduler).queryLoop.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:532\ngithub.com/milvus-io/milvus/pkg/util/conc.(*Pool[...]).Submit.func1\n\t/go/src/github.com/milvus-io/milvus/pkg/util/conc/pool.go:81\ngithub.com/panjf2000/ants/v2.(*goWorker).run.func1\n\t/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.2/worker.go:67"]
panic: interface conversion: interface {} is []interface {}, not float64 [recovered]
        panic: interface conversion: interface {} is []interface {}, not float64 [recovered]
        panic: interface conversion: interface {} is []interface {}, not float64

goroutine 7670 [running]:
panic({0x4ae35e0, 0xc001f7f110})
        /usr/local/go/src/runtime/panic.go:987 +0x3bb fp=0xc002b072d0 sp=0xc002b07210 pc=0x1a90c9b
github.com/milvus-io/milvus/pkg/util/conc.(*poolOption).antsOptions.func1({0x4ae35e0, 0xc001f7f110})
        /go/src/github.com/milvus-io/milvus/pkg/util/conc/options.go:56 +0x15b fp=0xc002b07398 sp=0xc002b072d0 pc=0x341bc9b
github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
        /go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.2/worker.go:54 +0x75 fp=0xc002b07410 sp=0xc002b07398 pc=0x3418e15
runtime.deferCallSave(0xc002b074e0, 0xc002983fb8?)
        /usr/local/go/src/runtime/panic.go:796 +0x88 fp=0xc002b07420 sp=0xc002b07410 pc=0x1a90888
runtime.runOpenDeferFrame(0xc0006ab400)
        /usr/local/go/src/runtime/panic.go:769 +0x1b4 fp=0xc002b07468 sp=0xc002b07420 pc=0x1a906b4
panic({0x4ae35e0, 0xc001f7f110})
        /usr/local/go/src/runtime/panic.go:884 +0x213 fp=0xc002b07528 sp=0xc002b07468 pc=0x1a90af3
github.com/milvus-io/milvus/pkg/util/conc.(*Pool[...]).Submit.func1.1()
        /go/src/github.com/milvus-io/milvus/pkg/util/conc/pool.go:74 +0x97 fp=0xc002b07588 sp=0xc002b07528 pc=0x45d8a57
runtime.deferCallSave(0xc002b07658, 0xc002983f50?)
        /usr/local/go/src/runtime/panic.go:796 +0x88 fp=0xc002b07598 sp=0xc002b07588 pc=0x1a90888
runtime.runOpenDeferFrame(0xc002f2db80)
        /usr/local/go/src/runtime/panic.go:769 +0x1b4 fp=0xc002b075e0 sp=0xc002b07598 pc=0x1a906b4
panic({0x4ae35e0, 0xc001f7f110})
        /usr/local/go/src/runtime/panic.go:884 +0x213 fp=0xc002b076a0 sp=0xc002b075e0 pc=0x1a90af3
runtime.panicdottypeE(0x48acc60, 0x48cb2a0, 0x49f3020)
        /usr/local/go/src/runtime/iface.go:262 +0x6a fp=0xc002b076c0 sp=0xc002b076a0 pc=0x1a6122a
github.com/milvus-io/milvus/internal/proxy.NewReScorer({0xc004c93000?, 0x64, 0x64?}, {0xc0055afd40, 0x4, 0x0?})
        /go/src/github.com/milvus-io/milvus/internal/proxy/reScorer.go:134 +0xc7c fp=0xc002b07908 sp=0xc002b076c0 pc=0x433543c
github.com/milvus-io/milvus/internal/proxy.(*hybridSearchTask).Execute(0xc0022cc240, {0x5657d00, 0xc0022079b0})
        /go/src/github.com/milvus-io/milvus/internal/proxy/task_hybrid_search.go:151 +0x5db fp=0xc002b07ca8 sp=0xc002b07908 pc=0x434d77b
github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask(0x0?, {0x56980a8, 0xc0022cc240}, {0x567f920, 0xc000620560})
```

[extra_crash.log](https://github.com/milvus-io/milvus/files/13884537/extra_crash.log)

**Comment by binbinlv** [comment]
After analysis, I found the crash cause should be input a list (invalid data structure) to WeightedRanker.

good:
collection_w.hybrid_search(req_list, WeightedRanker(0.9, 0.1), default_limit,
                                   check_task=CheckTasks.check_search_results,
                                   check_items={"nq": 1,
                                                "ids": insert_ids,
                                                "limit": default_limit})

crash:
collection_w.hybrid_search(req_list, WeightedRanker([0.9, 0.1]), default_limit,
                                   check_task=CheckTasks.check_search_results,
                                   check_items={"nq": 1,
                                                "ids": insert_ids,
                                                "limit": default_limit})

So modify the title.

**Comment by binbinlv** [comment]
Verified and fixed.

Now it reports error instead of crash when input a list to WeightedRanker:

```
pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=The type of rank param weight should be float)>
```
