### ISSUE TITLE
[Bug]: mixcoord panic: close of closed channel when concurrent reading and writing to a partition-key field collection

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#29935]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20240111-930735c4
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):  pulsar  
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.4.0rc15
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. create milvus and enable L0 segment
2. create a collection with a partition-key field, 64 num_partitions
3. create index -> insert 10m 128d data -> flush -> index again -> load
4. concurrent query + search + upsert + flush
```
                                 'concurrent_params': {'concurrent_number': 20,
                                                       'during_time': '10h',
                                                       'interval': 120,
                                                       'spawn_rate': None},
                                 'concurrent_tasks': [{'type': 'query',
                                                       'weight': 2,
                                                       'params': {'expr': '5000 '
                                                                          '< '
                                                                          'id '
                                                                          '< '
                                                                          '10000',
                                                                  'timeout': 600}},
                                                      {'type': 'search',
                                                       'weight': 2,
                                                       'params': {'nq': 100,
                                                                  'top_k': 100,
                                                                  'search_param': {'ef': 128},
                                                                  'timeout': 600}},
                                                      {'type': 'flush',
                                                       'weight': 2,
                                                       'params': {'timeout': 600}},
                                                      {'type': 'upsert',
                                                       'weight': 4,
                                                       'params': {'nb': 200,
                                                                  'timeout': 600,
                                                                  'start_id': 0,
                                                                  'random_id': True,
                                                                  'random_vector': True}}]},
```
5. Many search/query failed because of known issue. This issue is mainly about the restart of multiple nodes. The first one is mixcoord panic.
[mc_dpgg7.log](https://github.com/milvus-io/milvus/files/13915889/mc_dpgg7.log)

```
[2024/01/12 00:04:44.900 +00:00] [INFO] [rootcoord/root_coord.go:763] ["stop rootcoord executor"]
[2024/01/12 00:04:44.900 +00:00] [INFO] [rootcoord/root_coord.go:770] ["stop rootcoord scheduler"]
[2024/01/12 00:04:44.900 +00:00] [INFO] [roles/roles.go:282] ["All cleanup done, handleSignals goroutine quit"]panic: close of closed channel

goroutine 1 [running]:
panic({0x4ad8900, 0x5646dc0})
    /usr/local/go/src/runtime/panic.go:987 +0x3bb fp=0xc04c8c3508 sp=0xc04c8c3448 pc=0x1a9fcdb
runtime.closechan(0xc000225260)
    /usr/local/go/src/runtime/chan.go:365 +0x3fc fp=0xc04c8c3548 sp=0xc04c8c3508 pc=0x1a6b11c
github.com/milvus-io/milvus/internal/util/proxyutil.(*ProxyWatcher).Stop(...)
    /go/src/github.com/milvus-io/milvus/internal/util/proxyutil/proxy_watcher.go:221
github.com/milvus-io/milvus/internal/rootcoord.(*Core).Stop(0xc0014de780)
    /go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:795 +0x5e fp=0xc04c8c3570 sp=0xc04c8c3548 pc=0x45be2be
github.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).Stop(0xc0014f8990)
    /go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:342 +0x4dd fp=0xc04c8c37e0 sp=0xc04c8c3570 pc=0x45f3d3d
github.com/milvus-io/milvus/cmd/components.(*RootCoord).Stop(0x50c12bb?)
    /go/src/github.com/milvus-io/milvus/cmd/components/root_coord.go:63 +0x25 fp=0xc04c8c37f8 sp=0xc04c8c37e0 pc=0x45f6fa5
```
 6. pods:
```
level-zero-par-key-8-etcd-0                                       1/1     Running     0               13h     10.104.25.74    4am-node30   <none>           <none>
level-zero-par-key-8-etcd-1                                       1/1     Running     0               13h     10.104.17.169   4am-node23   <none>           <none>
level-zero-par-key-8-etcd-2                                       1/1     Running     0               13h     10.104.27.127   4am-node31   <none>           <none>
level-zero-par-key-8-milvus-datanode-685758cd6c-h8jt9             1/1     Running     0               13h     10.104.16.59    4am-node21   <none>           <none>
level-zero-par-key-8-milvus-datanode-685758cd6c-psspq             1/1     Running     1 (6h21m ago)   13h     10.104.30.146   4am-node38   <none>           <none>
level-zero-par-key-8-milvus-indexnode-55589c99f8-ml988            1/1     Running     0               13h     10.104.5.183    4am-node12   <none>           <none>
level-zero-par-key-8-milvus-indexnode-55589c99f8-wsrkk            1/1     Running     1 (6h21m ago)   13h     10.104.26.134   4am-node32   <none>           <none>
level-zero-par-key-8-milvus-mixcoord-644f75489d-dpgg7             1/1     Running     1 (6h21m ago)   13h     10.104.18.92    4am-node25   <none>           <none>
level-zero-par-key-8-milvus-proxy-fb75996db-kjklc                 1/1     Running     1 (6h15m ago)   13h     10.104.26.131   4am-node32   <none>           <none>
level-zero-par-key-8-milvus-querynode-d69449fc9-fhxxb             1/1     Running     1 (6h15m ago)   13h     10.104.1.107    4am-node10   <none>           <none>
level-zero-par-key-8-milvus-querynode-d69449fc9-nbsnv             1/1     Running     1 (5h47m ago)   13h     10.104.17.186   4am-node23   <none>           <none>
level-zero-par-key-8-milvus-querynode-d69449fc9-pf9sl             1/1     Running     1 (6h15m ago)   13h     10.104.27.147   4am-node31   <none>           <none>
level-zero-par-key-8-minio-0                                      1/1     Running     0               13h     10.104.25.72    4am-node30   <none>           <none>
level-zero-par-key-8-minio-1                                      1/1     Running     0               13h     10.104.17.171   4am-node23   <none>           <none>
level-zero-par-key-8-minio-2                                      1/1     Running     0               13h     10.104.23.94    4am-node27   <none>           <none>
level-zero-par-key-8-minio-3                                      1/1     Running     0               13h     10.104.28.81    4am-node33   <none>           <none>
level-zero-par-key-8-pulsar-bookie-0                              1/1     Running     0               13h     10.104.25.83    4am-node30   <none>           <none>
level-zero-par-key-8-pulsar-bookie-1                              1/1     Running     0               13h     10.104.17.173   4am-node23   <none>           <none>
level-zero-par-key-8-pulsar-bookie-2                              1/1     Running     0               13h     10.104.27.135   4am-node31   <none>           <none>
level-zero-par-key-8-pulsar-bookie-init-t5vk4                     0/1     Completed   0               13h     10.104.25.52    4am-node30   <none>           <none>
level-zero-par-key-8-pulsar-broker-0                              1/1     Running     0               13h     10.104.25.53    4am-node30   <none>           <none>
level-zero-par-key-8-pulsar-proxy-0                               1/1     Running     0               13h     10.104.25.56    4am-node30   <none>           <none>
level-zero-par-key-8-pulsar-pulsar-init-khpkg                     0/1     Completed   0               13h     10.104.1.70     4am-node10   <none>           <none>
level-zero-par-key-8-pulsar-recovery-0                            1/1     Running     0               13h     10.104.25.54    4am-node30   <none>           <none>
level-zero-par-key-8-pulsar-zookeeper-0                           1/1     Running     0               13h     10.104.25.78    4am-node30   <none>           <none>
level-zero-par-key-8-pulsar-zookeeper-1                           1/1     Running     0               13h     10.104.28.92    4am-node33   <none>           <none>
level-zero-par-key-8-pulsar-zookeeper-2                           1/1     Running     0               13h     10.104.32.106   4am-node39   <none>           <none>
```

### Anything else?

- argo: [level-zero-stable-8b-2699689799](https://argo-workflows.zilliz.cc/archived-workflows/qa/3a0381d0-fa2b-4cb0-9655-b45749058746?nodeId=level-zero-stable-8b-2699689799)
- [prometheus pod terminated reason](https://grafana-4am.zilliz.cc/explore?orgId=1&left=%7B%22datasource%22:%22prometheus%22,%22queries%22:%5B%7B%22refId%22:%22B%22,%22expr%22:%22kube_pod_container_status_last_terminated_reason%7Bpod%3D~%5C%22level-zero-par-key-8-milvus-.*%5C%22%7D%22,%22range%22:true,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%221704992529000%22,%22to%22:%221705042800000%22%7D%7D)

**Comment by ThreadDao** [comment]
Maybe fixed `master-20240119-e3b8c3f6-amd64`
