### ISSUE TITLE
[Bug]: v2.3.4 crash suddenly 

### ISSUE THREAD

**Issue by shanghaikid** [milvus-io/milvus#29944]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.3.4 standalone
```

### Current Behavior

![image](https://github.com/milvus-io/milvus/assets/185051/74f2ef84-3848-43a8-ba1a-cb35a9e68ff0)

```bash

/usr/local/go/src/runtime/mgc.go:1199 +0x25
--
  |   | 2024-01-12 17:16:27 | created by runtime.gcBgMarkStartWorkers
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0004d07e8 sp=0xc0004d07e0 pc=0x1a609e1
  |   | 2024-01-12 17:16:27 | runtime.goexit()
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0004d07e0 sp=0xc0004d0750 pc=0x1a096d1
  |   | 2024-01-12 17:16:27 | runtime.gcBgMarkWorker()
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc0004d0750 sp=0xc0004d0730 pc=0x1a2a116
  |   | 2024-01-12 17:16:27 | runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
  |   | 2024-01-12 17:16:27 | goroutine 39 [GC worker (idle)]:
  |   | 2024-01-12 17:16:27 |  
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/mgc.go:1199 +0x25
  |   | 2024-01-12 17:16:27 | created by runtime.gcBgMarkStartWorkers
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0004cffe8 sp=0xc0004cffe0 pc=0x1a609e1
  |   | 2024-01-12 17:16:27 | runtime.goexit()
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0004cffe0 sp=0xc0004cff50 pc=0x1a096d1
  |   | 2024-01-12 17:16:27 | runtime.gcBgMarkWorker()
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc0004cff50 sp=0xc0004cff30 pc=0x1a2a116
  |   | 2024-01-12 17:16:27 | runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
  |   | 2024-01-12 17:16:27 | goroutine 38 [GC worker (idle)]:
  |   | 2024-01-12 17:16:27 |  
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/mgc.go:1199 +0x25
  |   | 2024-01-12 17:16:27 | created by runtime.gcBgMarkStartWorkers
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0004cf7e8 sp=0xc0004cf7e0 pc=0x1a609e1
  |   | 2024-01-12 17:16:27 | runtime.goexit()
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0004cf7e0 sp=0xc0004cf750 pc=0x1a096d1
  |   | 2024-01-12 17:16:27 | runtime.gcBgMarkWorker()
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc0004cf750 sp=0xc0004cf730 pc=0x1a2a116
  |   | 2024-01-12 17:16:27 | runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
  |   | 2024-01-12 17:16:27 | goroutine 37 [GC worker (idle)]:
  |   | 2024-01-12 17:16:27 |  
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/mgc.go:1199 +0x25
  |   | 2024-01-12 17:16:27 | created by runtime.gcBgMarkStartWorkers
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0004cefe8 sp=0xc0004cefe0 pc=0x1a609e1
  |   | 2024-01-12 17:16:27 | runtime.goexit()
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0004cefe0 sp=0xc0004cef50 pc=0x1a096d1
  |   | 2024-01-12 17:16:27 | runtime.gcBgMarkWorker()
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc0004cef50 sp=0xc0004cef30 pc=0x1a2a116
  |   | 2024-01-12 17:16:27 | runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
  |   | 2024-01-12 17:16:27 | goroutine 36 [GC worker (idle)]:
  |   | 2024-01-12 17:16:27 |  
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/mgc.go:1199 +0x25
  |   | 2024-01-12 17:16:27 | created by runtime.gcBgMarkStartWorkers
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0004ce7e8 sp=0xc0004ce7e0 pc=0x1a609e1
  |   | 2024-01-12 17:16:27 | runtime.goexit()
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0004ce7e0 sp=0xc0004ce750 pc=0x1a096d1
  |   | 2024-01-12 17:16:27 | runtime.gcBgMarkWorker()
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc0004ce750 sp=0xc0004ce730 pc=0x1a2a116
  |   | 2024-01-12 17:16:27 | runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
  |   | 2024-01-12 17:16:27 | goroutine 35 [GC worker (idle)]:
  |   | 2024-01-12 17:16:27 |  
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/mfinal.go:163 +0x45
  |   | 2024-01-12 17:16:27 | created by runtime.createfing
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0001267e8 sp=0xc0001267e0 pc=0x1a609e1
  |   | 2024-01-12 17:16:27 | runtime.goexit()
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/mfinal.go:193 +0x107 fp=0xc0001267e0 sp=0xc000126628 pc=0x1a069a7
  |   | 2024-01-12 17:16:27 | runtime.runfinq()
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000126628 sp=0xc000126608 pc=0x1a2a116
  |   | 2024-01-12 17:16:27 | runtime.gopark(0x0?, 0x51012f8?, 0xa0?, 0xa8?, 0x2000000020?)
  |   | 2024-01-12 17:16:27 | goroutine 34 [finalizer wait]:
  |   | 2024-01-12 17:16:27 |  
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/mgc.go:179 +0xaa
  |   | 2024-01-12 17:16:27 | created by runtime.gcenable
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000122fe8 sp=0xc000122fe0 pc=0x1a609e1
  |   | 2024-01-12 17:16:27 | runtime.goexit()
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/mgc.go:179 +0x26 fp=0xc000122fe0 sp=0xc000122fc8 pc=0x1a07906
  |   | 2024-01-12 17:16:27 | runtime.gcenable.func2()
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/mgcscavenge.go:633 +0x65 fp=0xc000122fc8 sp=0xc000122fa0 pc=0x1a10ce5
  |   | 2024-01-12 17:16:27 | runtime.bgscavenge(0x0?)
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/mgcscavenge.go:400 +0x53 fp=0xc000122fa0 sp=0xc000122f70 pc=0x1a106d3
  |   | 2024-01-12 17:16:27 | runtime.(*scavengerState).park(0x73cf040)
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/proc.go:387
  |   | 2024-01-12 17:16:27 | runtime.goparkunlock(...)
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000122f70 sp=0xc000122f50 pc=0x1a2a116
  |   | 2024-01-12 17:16:27 | runtime.gopark(0xc00018e000?, 0x5512e90?, 0x0?, 0x0?, 0x0?)
  |   | 2024-01-12 17:16:27 | goroutine 19 [GC scavenge wait]:
  |   | 2024-01-12 17:16:27 |  
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/mgc.go:178 +0x6b
  |   | 2024-01-12 17:16:27 | created by runtime.gcenable
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0001227e8 sp=0xc0001227e0 pc=0x1a609e1
  |   | 2024-01-12 17:16:27 | runtime.goexit()
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/mgc.go:178 +0x26 fp=0xc0001227e0 sp=0xc0001227c8 pc=0x1a07966
  |   | 2024-01-12 17:16:27 | runtime.gcenable.func1()
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/mgcsweep.go:319 +0xde fp=0xc0001227c8 sp=0xc000122780 pc=0x1a1289e
  |   | 2024-01-12 17:16:27 | runtime.bgsweep(0x0?)
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/proc.go:387
  |   | 2024-01-12 17:16:27 | runtime.goparkunlock(...)
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000122780 sp=0xc000122760 pc=0x1a2a116
  |   | 2024-01-12 17:16:27 | runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
  |   | 2024-01-12 17:16:27 | goroutine 18 [GC sweep wait]:
  |   | 2024-01-12 17:16:27 |  
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/proc.go:293 +0x25
  |   | 2024-01-12 17:16:27 | created by runtime.init.6
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000126fe8 sp=0xc000126fe0 pc=0x1a609e1
  |   | 2024-01-12 17:16:27 | runtime.goexit()
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/proc.go:305 +0xb0 fp=0xc000126fe0 sp=0xc000126fb0 pc=0x1a29f50
  |   | 2024-01-12 17:16:27 | runtime.forcegchelper()
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/proc.go:387
  |   | 2024-01-12 17:16:27 | runtime.goparkunlock(...)
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000126fb0 sp=0xc000126f90 pc=0x1a2a116
  |   | 2024-01-12 17:16:27 | runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
  |   | 2024-01-12 17:16:27 | goroutine 2 [force gc (idle)]:
  | Log labelsappmilvusclusterdevopscomponentstandalonecontainerstandalonejobchaos-testing/milvusnamespacechaos-testingnode_namedevops-node10podnode234-acldp-milvus-standalone-7f857b4fcb-w2c9kstreamstderrDetected fieldsts2024-01-12T09:16:27.079ZtsNs1705050987079984777 | Log labels |   |   |   | app | milvus |   |   |   | cluster | devops |   |   |   | component | standalone |   |   |   | container | standalone |   |   |   | job | chaos-testing/milvus |   |   |   | namespace | chaos-testing |   |   |   | node_name | devops-node10 |   |   |   | pod | node234-acldp-milvus-standalone-7f857b4fcb-w2c9k |   |   |   | stream | stderr | Detected fields |   |   | ts | 2024-01-12T09:16:27.079Z |   |   | tsNs | 1705050987079984777
Log labels
  |   |   | app | milvus
  |   |   | cluster | devops
  |   |   | component | standalone
  |   |   | container | standalone
  |   |   | job | chaos-testing/milvus
  |   |   | namespace | chaos-testing
  |   |   | node_name | devops-node10
  |   |   | pod | node234-acldp-milvus-standalone-7f857b4fcb-w2c9k
  |   |   | stream | stderr
Detected fields
  |   | ts | 2024-01-12T09:16:27.079Z
  |   | tsNs | 1705050987079984777
  |   | 2024-01-12 17:16:27 |  
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc001907fe8 sp=0xc001907fe0 pc=0x1a609e1
  |   | 2024-01-12 17:16:27 | runtime.goexit()
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/proc.go:250 +0x207 fp=0xc001907fe0 sp=0xc001907f80 pc=0x1a29ce7
  |   | 2024-01-12 17:16:27 | runtime.main()
  |   | 2024-01-12 17:16:27 | /go/src/github.com/milvus-io/milvus/cmd/main.go:95 +0x3e5 fp=0xc001907f80 sp=0xc001907db8 pc=0x452be05
  |   | 2024-01-12 17:16:27 | main.main()
  |   | 2024-01-12 17:16:27 | /go/src/github.com/milvus-io/milvus/cmd/milvus/milvus.go:60 +0x20e fp=0xc001907db8 sp=0xc001907d40 pc=0x452732e
  |   | 2024-01-12 17:16:27 | github.com/milvus-io/milvus/cmd/milvus.RunMilvus({0xc000212150?, 0x3, 0x3})
  |   | 2024-01-12 17:16:27 | /go/src/github.com/milvus-io/milvus/cmd/milvus/run.go:44 +0x2ab fp=0xc001907d40 sp=0xc001907c70 pc=0x452766b
  |   | 2024-01-12 17:16:27 | github.com/milvus-io/milvus/cmd/milvus.(*run).execute(0x7f2d38e41048?, {0xc000212150?, 0x3, 0x3}, 0xc00050e2a0)
  |   | 2024-01-12 17:16:27 | /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:384 +0x9b1 fp=0xc001907c70 sp=0xc0019077f0 pc=0x451c7f1
  |   | 2024-01-12 17:16:27 | github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run(0xc00134e440)
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/sync/waitgroup.go:116 +0x4b fp=0xc0019077f0 sp=0xc0019077c8 pc=0x1a8326b
  |   | 2024-01-12 17:16:27 | sync.(*WaitGroup).Wait(0xc0005ba5e0?)
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/sema.go:62 +0x27 fp=0xc0019077c8 sp=0xc001907790 pc=0x1a5bf67
  |   | 2024-01-12 17:16:27 | sync.runtime_Semacquire(0x50fe020?)
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/sema.go:160 +0x20f fp=0xc001907790 sp=0xc001907728 pc=0x1a3beef
  |   | 2024-01-12 17:16:27 | runtime.semacquire1(0xc0013d90a8, 0x40?, 0x1, 0x0, 0x1?)
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/proc.go:387
  |   | 2024-01-12 17:16:27 | runtime.goparkunlock(...)
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc001907728 sp=0xc001907708 pc=0x1a2a116
  |   | 2024-01-12 17:16:27 | runtime.gopark(0x552c2c0?, 0xc0006a20c8?, 0x0?, 0x0?, 0xc000ff3fa0?)
  |   | 2024-01-12 17:16:27 | goroutine 1 [semacquire]:
  |   | 2024-01-12 17:16:27 |  
  |   | 2024-01-12 17:16:27 | /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:102 +0x158
  |   | 2024-01-12 17:16:27 | created by github.com/milvus-io/milvus/cmd/roles.runComponent[...]
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00190bfe8 sp=0xc00190bfe0 pc=0x1a609e1
  |   | 2024-01-12 17:16:27 | runtime.goexit()
  |   | 2024-01-12 17:16:27 | /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:115 +0x15a fp=0xc00190bfe0 sp=0xc00190bf58 pc=0x451d41a
  |   | 2024-01-12 17:16:27 | github.com/milvus-io/milvus/cmd/roles.runComponent[...].func1()
  |   | 2024-01-12 17:16:27 | /go/src/github.com/milvus-io/milvus/cmd/components/query_node.go:53 +0x2f fp=0xc00190bf58 sp=0xc00190be88 pc=0x4517d8f
  |   | 2024-01-12 17:16:27 | github.com/milvus-io/milvus/cmd/components.(*QueryNode).Run(0xc000002060?)
  |   | 2024-01-12 17:16:27 | /go/src/github.com/milvus-io/milvus/internal/distributed/querynode/service.go:223 +0x25 fp=0xc00190be88 sp=0xc00190be48 pc=0x4475265
  |   | 2024-01-12 17:16:27 | github.com/milvus-io/milvus/internal/distributed/querynode.(*Server).Run(0xc001330110?)
  |   | 2024-01-12 17:16:27 | /go/src/github.com/milvus-io/milvus/internal/distributed/querynode/service.go:128 +0x862 fp=0xc00190be48 sp=0xc00190bb20 pc=0x4473d82
  |   | 2024-01-12 17:16:27 | github.com/milvus-io/milvus/internal/distributed/querynode.(*Server).init(0xc00002e300)
  |   | 2024-01-12 17:16:27 | /go/src/github.com/milvus-io/milvus/internal/querynodev2/server.go:265 +0x5b fp=0xc00190bb20 sp=0xc00190bad8 pc=0x446f0db
  |   | 2024-01-12 17:16:27 | github.com/milvus-io/milvus/internal/querynodev2.(*QueryNode).Init(0x4fae69c?)
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/sync/once.go:65
  |   | 2024-01-12 17:16:27 | sync.(*Once).Do(...)
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/sync/once.go:74 +0xc2 fp=0xc00190bad8 sp=0xc00190ba78 pc=0x1a81ac2
  |   | 2024-01-12 17:16:27 | sync.(*Once).doSlow(0x4fae69c?, 0x0?)
  |   | 2024-01-12 17:16:27 | /go/src/github.com/milvus-io/milvus/internal/querynodev2/server.go:268 +0x13a fp=0xc00190ba78 sp=0xc00190b3d8 pc=0x446f25a
  |   | 2024-01-12 17:16:27 | github.com/milvus-io/milvus/internal/querynodev2.(*QueryNode).Init.func1()
  |   | 2024-01-12 17:16:27 | /go/src/github.com/milvus-io/milvus/internal/querynodev2/server.go:157 +0x105 fp=0xc00190b3d8 sp=0xc00190b2f8 pc=0x446e245
  |   | 2024-01-12 17:16:27 | github.com/milvus-io/milvus/internal/querynodev2.(*QueryNode).initSession(0xc001204000)
  |   | 2024-01-12 17:16:27 | /go/src/github.com/milvus-io/milvus/internal/util/sessionutil/session_util.go:282 +0x32a fp=0xc00190b2f8 sp=0xc00190b1f8 pc=0x3b4a10a
  |   | 2024-01-12 17:16:27 | github.com/milvus-io/milvus/internal/util/sessionutil.(*Session).Init(0xc001412d00, {0x4fafa28, 0x9}, {0xc000036138, 0x11}, 0xb?, 0x1?)
  |   | 2024-01-12 17:16:27 | /usr/local/go/src/runtime/panic.go:987 +0x3bb fp=0xc00190b1f8 sp=0xc00190b138 pc=0x1a26c5b
  |   | 2024-01-12 17:16:27 | panic({0x4bf90a0, 0xc00151c000})
  |   | 2024-01-12 17:16:27 | goroutine 139 [running]:



```

### Milvus Log

https://grafana-4am.zilliz.cc/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bpod%3D%5C%22node234-acldp-milvus-standalone-7f857b4fcb-w2c9k%5C%22%7D%22,%22hide%22:true%7D,%7B%22refId%22:%22B%22,%22expr%22:%22%7Bpod%3D%5C%22node234-acldp-milvus-standalone-7f857b4fcb-w2c9k%5C%22%7D%7C~%5C%22%5C%22%22%7D%5D,%22range%22:%7B%22from%22:%22now-3h%22,%22to%22:%22now%22%7D%7D

**Comment by aoiasd** [comment]
![image](https://github.com/milvus-io/milvus/assets/45024769/482ba20d-2720-498b-8a7a-76a4a893ccda)
Seems etcd connect has some problem, cash reason was that milvus can't connect etcd or connect time out cause init failed.

**Comment by shanghaikid** [comment]
can we just show user that etcd has connection problem, other than crashing the server.

**Comment by aoiasd** [comment]
> can we just show user that etcd has connection problem, other than crashing the server.

Bacause etcd connect failed when we initialize milvus. We now agree that all initialized error should panic. May need a discussion if we want to break this agreement or need more options.
