### ISSUE TITLE
[Bug]: querynode terminated with [signal SIGSEGV: segmentation violation xx]

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#29955]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: cardinal-foxspy-fix_binlog_index_concurrency-b46e085-20240110
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):  pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.3.5rc5
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. Collection `laion_coll_7 ` has a partition_key field and 8 num_partitions
```
{'auto_id': False, 'description': '', 'fields': [{'name': 'id', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float_vector', 'description': '', 'type': <DataType.FLOAT_VECTOR: 101>, 'params': {'dim': 768}}, {'name': 'int64_pk_5b', 'description': '', 'type': <DataType.INT64: 5>, 'is_partition_key': True}, {'name': 'varchar_caption', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 8192}}, {'name': 'varchar_NSFW', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 8192}}, {'name': 'float64_similarity', 'description': '', 'type': <DataType.FLOAT: 10>}, {'name': 'int64_width', 'description': '', 'type': <DataType.INT64: 5>}, {'name': 'int64_height', 'description': '', 'type': <DataType.INT64: 5>}, {'name': 'int64_original_width', 'description': '', 'type': <DataType.INT64: 5>}, {'name': 'int64_original_height', 'description': '', 'type': <DataType.INT64: 5>}, {'name': 'varchar_md5', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 8192}}], 'enable_dynamic_field': True}
```
2. Collection has 20m+ data diskann index
3. concurrent insert + delete + flush + search + query, and one querynode terminated with 134 error
[qn_qfrq2.log](https://github.com/milvus-io/milvus/files/13920891/qn_qfrq2.log)

```
14614 [2024/01/12 14:37:02.030 +00:00] [DEBUG] [segments/collection.go:197] ["collection ref decrement"] [collectionID=446943798268169      315] [refCount=97]
14615 [signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x7f18eb8e2b73]
14616
14617 runtime stack:
14618 runtime.throw({0x503f806?, 0x7f18eb8de1c4?})
14619     /usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7f128f189700 sp=0x7f128f1896d0 pc=0x1a2805d
14620 runtime.sigpanic()
14621     /usr/local/go/src/runtime/signal_unix.go:825 +0x3e9 fp=0x7f128f189760 sp=0x7f128f189700 pc=0x1a3fec9
14622
14623 goroutine 710333 [syscall]:
14624 _ZNKSt14default_deleteIN6milvus7segcore10VectorBaseEEclEPS2_
14625     /usr/include/c++/9/bits/unique_ptr.h:81 pc=0x7f18eb8e2b73
14626 _ZNSt10unique_ptrIN6milvus7segcore10VectorBaseESt14default_deleteIS2_EED4Ev
14627     /usr/include/c++/9/bits/unique_ptr.h:292 pc=0x7f18eb8e2b73
14628 _ZNSt4pairIKN6fluent9NamedTypeIlN6milvus4impl10FieldIdTagEJNS0_10ComparableENS0_8HashableEEEESt10unique_ptrINS2_7segcore10Vector      BaseESt14default_deleteISB_EEED4Ev
14629     /usr/include/c++/9/bits/stl_pair.h:208 pc=0x7f18eb8e2b73
14630 _ZN9__gnu_cxx13new_allocatorINSt8__detail10_Hash_nodeISt4pairIKN6fluent9NamedTypeIlN6milvus4impl10FieldIdTagEJNS4_10ComparableEN      S4_8HashableEEEESt10unique_ptrINS6_7segcore10VectorBaseESt14default_deleteISF_EEELb0EEEE7destroyISJ_EEvPT_
14631     /usr/include/c++/9/ext/new_allocator.h:152 pc=0x7f18eb8e2b73
14632 _ZNSt16allocator_traitsISaINSt8__detail10_Hash_nodeISt4pairIKN6fluent9NamedTypeIlN6milvus4impl10FieldIdTagEJNS3_10ComparableENS3      _8HashableEEEESt10unique_ptrINS5_7segcore10VectorBaseESt14default_deleteISE_EEELb0EEEEE7destroyISI_EEvRSK_PT_
14633     /usr/include/c++/9/bits/alloc_traits.h:496 pc=0x7f18eb8e2b73
14634 _ZNSt8__detail16_Hashtable_allocISaINS_10_Hash_nodeISt4pairIKN6fluent9NamedTypeIlN6milvus4impl10FieldIdTagEJNS3_10ComparableENS3      _8HashableEEEESt10unique_ptrINS5_7segcore10VectorBaseESt14default_deleteISE_EEELb0EEEEE18_M_deallocate_nodeEPSJ_
14635     /usr/include/c++/9/bits/hashtable_policy.h:2102 pc=0x7f18eb8e2b73
14636 _ZNSt8__detail16_Hashtable_allocISaINS_10_Hash_nodeISt4pairIKN6fluent9NamedTypeIlN6milvus4impl10FieldIdTagEJNS3_10ComparableENS3      _8HashableEEEESt10unique_ptrINS5_7segcore10VectorBaseESt14default_deleteISE_EEELb0EEEEE19_M_deallocate_nodesEPSJ_
14637     /usr/include/c++/9/bits/hashtable_policy.h:2124 pc=0x7f18eb8e2b73
14638 _ZNSt10_HashtableIN6fluent9NamedTypeIlN6milvus4impl10FieldIdTagEJNS0_10ComparableENS0_8HashableEEEESt4pairIKS7_St10unique_ptrINS      2_7segcore10VectorBaseESt14default_deleteISC_EEESaISG_ENSt8__detail10_Select1stESt8equal_toIS7_ESt4hashIS7_ENSI_18_Mod_range_has      hingENSI_20_Default_ranged_hashENSI_20_Prime_rehash_policyENSI_17_Hashtable_traitsILb0ELb0ELb1EEEE5clearEv
14639     /usr/include/c++/9/bits/hashtable.h:2063 pc=0x7f18eb8e2b73
14640 _ZNSt10_HashtableIN6fluent9NamedTypeIlN6milvus4impl10FieldIdTagEJNS0_10ComparableENS0_8HashableEEEESt4pairIKS7_St10unique_ptrINS      2_7segcore10VectorBaseESt14default_deleteISC_EEESaISG_ENSt8__detail10_Select1stESt8equal_toIS7_ESt4hashIS7_ENSI_18_Mod_range_has      hingENSI_20_Default_ranged_hashENSI_20_Prime_rehash_policyENSI_17_Hashtable_traitsILb0ELb0ELb1EEEED4Ev
14641     /usr/include/c++/9/bits/hashtable.h:1387 pc=0x7f18eb8e2b73
14642 _ZNSt13unordered_mapIN6fluent9NamedTypeIlN6milvus4impl10FieldIdTagEJNS0_10ComparableENS0_8HashableEEEESt10unique_ptrINS2_7segcor      e10VectorBaseESt14default_deleteISA_EESt4hashIS7_ESt8equal_toIS7_ESaISt4pairIKS7_SD_EEED4Ev
14643     /usr/include/c++/9/bits/unordered_map.h:102 pc=0x7f18eb8e2b73
14644 _ZN6milvus7segcore12InsertRecordILb1EED2Ev
14645     /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/InsertRecord.h:277 pc=0x7f18eb8e2b73
14646 _ZN6milvus7segcore17SegmentSealedImplD2Ev
14647     /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:892 pc=0x7f18eb8ca8b1
14648 _ZN6milvus7segcore17SegmentSealedImplD0Ev
14649     /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:903 pc=0x7f18eb8cac6c
```

### Milvus Log

4am pods:
( coredump file see the /tmp/cores of 4am-node31
```
laion1b-test-knowhere-milvus-datanode-56cbd68b85-8rgtx            1/1     Running     0               9h      10.104.5.102    4am-node12   <none>           <none>
laion1b-test-knowhere-milvus-datanode-56cbd68b85-ns5sc            1/1     Running     0               9h      10.104.1.149    4am-node10   <none>           <none>
laion1b-test-knowhere-milvus-indexnode-665ccb8f84-7ckvk           1/1     Running     0               9h      10.104.26.133   4am-node32   <none>           <none>
laion1b-test-knowhere-milvus-indexnode-665ccb8f84-8cjf4           1/1     Running     0               9h      10.104.4.177    4am-node11   <none>           <none>
laion1b-test-knowhere-milvus-indexnode-665ccb8f84-9g4vd           1/1     Running     0               9h      10.104.16.104   4am-node21   <none>           <none>
laion1b-test-knowhere-milvus-indexnode-665ccb8f84-cmhnq           1/1     Running     0               9h      10.104.20.228   4am-node22   <none>           <none>
laion1b-test-knowhere-milvus-indexnode-665ccb8f84-gjrks           1/1     Running     0               9h      10.104.6.56     4am-node13   <none>           <none>
laion1b-test-knowhere-milvus-mixcoord-759876bc6d-rq257            1/1     Running     0               9h      10.104.5.103    4am-node12   <none>           <none>
laion1b-test-knowhere-milvus-proxy-5599d6cbd7-29287               1/1     Running     0               9h      10.104.4.173    4am-node11   <none>           <none>
laion1b-test-knowhere-milvus-querynode-78c47b599b-5xzdr           1/1     Running     0               9h      10.104.17.230   4am-node23   <none>           <none>
laion1b-test-knowhere-milvus-querynode-78c47b599b-csk4z           1/1     Running     0               9h      10.104.28.229   4am-node33   <none>           <none>
laion1b-test-knowhere-milvus-querynode-78c47b599b-drl7t           1/1     Running     0               9h      10.104.21.129   4am-node24   <none>           <none>
laion1b-test-knowhere-milvus-querynode-78c47b599b-kbqs6           1/1     Running     0               9h      10.104.13.201   4am-node16   <none>           <none>
laion1b-test-knowhere-milvus-querynode-78c47b599b-ld6n7           1/1     Running     0               9h      10.104.29.179   4am-node35   <none>           <none>
laion1b-test-knowhere-milvus-querynode-78c47b599b-pvf2f           1/1     Running     0               9h      10.104.33.168   4am-node36   <none>           <none>
laion1b-test-knowhere-milvus-querynode-78c47b599b-qfrq2           1/1     Running     1 (56m ago)     9h      10.104.27.74    4am-node31   <none>           <none>
laion1b-test-knowhere-milvus-querynode-78c47b599b-vdncb           1/1     Running     0               9h      10.104.30.32    4am-node38   <none>           <none>
laion1b-test-knowhere-milvus-querynode-78c47b599b-wpzj4           1/1     Running     0               9h      10.104.9.63     4am-node14   <none>           <none>
laion1b-test-knowhere-milvus-querynode-78c47b599b-wvd7n           1/1     Running     0               9h      10.104.24.84    4am-node29   <none>           <none>
```

### Anything else?

1. argo link: [laion1b-test-knowhere-reindex-4](https://argo-workflows.zilliz.cc/archived-workflows/qa/ec64ae22-0e1d-4676-8920-99da824b2abe?nodeId=laion1b-test-knowhere-reindex-4)

**Comment by ThreadDao** [comment]
No reproduce in image `cardinal-foxspy-fix_binlog_index_concurrency-1367e8e-20240114`. I guess it is fixed
