### ISSUE TITLE
[Bug]: When Milvus recovers from a chaos, executing load, the load will fail.

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#29973]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20240114-8febbc79-amd64
- Deployment mode(standalone or cluster):all
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2024-01-14T20:07:50.771Z] [2024-01-14 20:00:48 - DEBUG - ci_test]: (api_request)  : [Collection.query] args: ['int64 in [-3000, -2999, -2998, -2997, -2996, -2995, -2994, -2993, -2992, -2991, -2990, -2989, -2988, -2987, -2986, -2985, -2984, -2983, -2982, -2981, -2980, -2979, -2978, -2977, -2976, -2975, -2974, -2973, -2972, -2971, -2970, -2969, -2968, -2967, -2966, -2965, -2964, -2963, -2962, -2961, -2960, -......, kwargs: {} (api_request.py:62)

[2024-01-14T20:07:50.772Z] [2024-01-14 20:00:49 - DEBUG - ci_test]: (api_response) : [{'int64': -3000}, {'int64': -2999}, {'int64': -2998}, {'int64': -2997}, {'int64': -2996}, {'int64': -2995}, {'int64': -2994}, {'int64': -2993}, {'int64': -2992}, {'int64': -2991}, {'int64': -2990}, {'int64': -2989}, {'int64': -2988}, {'int64': -2987}, {'int64': -2986}, {'int64': -2985}, {'int64': -......  (api_request.py:37)

[2024-01-14T20:07:50.772Z] [2024-01-14 20:00:49 - INFO - ci_test]: assert query result 2000: 0.4554431438446045 (test_all_collections_after_chaos.py:107)

[2024-01-14T20:07:50.772Z] [2024-01-14 20:00:49 - DEBUG - ci_test]: (api_request)  : [Collection.release] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-01-14T20:07:50.772Z] [2024-01-14 20:00:51 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-01-14T20:07:50.772Z] [2024-01-14 20:00:51 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [[[5102774969856027445, 491151061401911130, 6906195123916532545, -7360625628324990395, 3698985280648487612, -5371530191423717501, 5374445578596680537, -4628916758856011492, 944208338482724096, 1887975418000341221, 5319238354377786129, -6943896274216453104, 5320488601054311821, -3066324330876782222, ......, kwargs: {'timeout': 180} (api_request.py:62)

[2024-01-14T20:07:50.772Z] [2024-01-14 20:00:51 - DEBUG - ci_test]: (api_response) : (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 447024320089686017, success count: 2000, err count: 0)  (api_request.py:37)

[2024-01-14T20:07:50.772Z] [2024-01-14 20:00:51 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 180], kwargs: {} (api_request.py:62)

[2024-01-14T20:07:50.772Z] [2024-01-14 20:03:53 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=wait for loading collection timeout, collection: Checker__uxALheFV)>, <Time:{'RPC start': '2024-01-14 20:00:53.353209', 'RPC error': '2024-01-14 20:03:53.800110'}> (decorators.py:134)

[2024-01-14T20:07:50.772Z] [2024-01-14 20:03:53 - WARNING - pymilvus.decorators]: Retry timeout: 180s (decorators.py:100)

[2024-01-14T20:07:50.772Z] [2024-01-14 20:03:53 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for loading collection timeout, collection: Checker__uxALheFV)>, <Time:{'RPC start': '2024-01-14 20:00:51.575214', 'RPC error': '2024-01-14 20:03:53.800509'}> (decorators.py:134)

[2024-01-14T20:07:50.772Z] [2024-01-14 20:03:53 - ERROR - ci_test]: Traceback (most recent call last):

[2024-01-14T20:07:50.772Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2024-01-14T20:07:50.772Z]     res = func(*args, **_kwargs)

[2024-01-14T20:07:50.772Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2024-01-14T20:07:50.772Z]     return func(*arg, **kwargs)

[2024-01-14T20:07:50.772Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 419, in load

[2024-01-14T20:07:50.772Z]     conn.load_collection(

[2024-01-14T20:07:50.772Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 135, in handler

[2024-01-14T20:07:50.772Z]     raise e from e

[2024-01-14T20:07:50.772Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 131, in handler

[2024-01-14T20:07:50.772Z]     return func(*args, **kwargs)

[2024-01-14T20:07:50.772Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 170, in handler

[2024-01-14T20:07:50.772Z]     return func(self, *args, **kwargs)

[2024-01-14T20:07:50.772Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 101, in handler

[2024-01-14T20:07:50.772Z]     raise MilvusException(

[2024-01-14T20:07:50.772Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for loading collection timeout, collection: Checker__uxALheFV)>
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/10663/pipeline

log:
[artifacts-etcd-leader-pod-failure-10663-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/13934176/artifacts-etcd-leader-pod-failure-10663-server-logs.tar.gz)

### Anything else?

This issue happened in almost all chaos tests

**Comment by zhuwenxing** [comment]
verified and passed in master-20240116-2a0eb1d2
