### ISSUE TITLE
[Bug]: Search result length is less than limit in search params when using ivfsq8 index

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#30086]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20240117-9a383721
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```

[2024-01-17T10:05:59.756Z] 2024-01-17 10:05:59.647 | INFO     | MainThread |utils:load_and_search:214 - collection name: task_2_IVF_SQ8

[2024-01-17T10:05:59.756Z] 2024-01-17 10:05:59.647 | INFO     | MainThread |utils:load_and_search:215 - load collection

[2024-01-17T10:05:59.756Z] 2024-01-17 10:05:59.650 | INFO     | MainThread |utils:load_and_search:219 - load time: 0.0032

[2024-01-17T10:05:59.756Z] 2024-01-17 10:05:59.661 | INFO     | MainThread |utils:load_and_search:233 - {'metric_type': 'L2', 'params': {'nprobe': 10}}

[2024-01-17T10:05:59.756Z] 2024-01-17 10:05:59.661 | INFO     | MainThread |utils:load_and_search:236 - 

[2024-01-17T10:05:59.756Z] Search...

[2024-01-17T10:05:59.756Z] 2024-01-17 10:05:59.665 | INFO     | MainThread |utils:load_and_search:247 - hit: id: 2166, distance: 31.494504928588867, entity: {'count': 2166, 'random_value': -18.0}

[2024-01-17T10:05:59.756Z] 2024-01-17 10:05:59.666 | INFO     | MainThread |utils:load_and_search:247 - hit: id: 854, distance: 32.32667541503906, entity: {'count': 854, 'random_value': -12.0}

[2024-01-17T10:05:59.756Z] 2024-01-17 10:05:59.666 | INFO     | MainThread |utils:load_and_search:247 - hit: id: 2543, distance: 32.46454620361328, entity: {'count': 2543, 'random_value': -15.0}

[2024-01-17T10:05:59.756Z] 2024-01-17 10:05:59.666 | INFO     | MainThread |utils:load_and_search:247 - hit: id: 1164, distance: 32.48982238769531, entity: {'count': 1164, 'random_value': -14.0}

[2024-01-17T10:05:59.756Z] Traceback (most recent call last):

[2024-01-17T10:05:59.756Z]   File "scripts/action_after_reinstall.py", line 47, in <module>

[2024-01-17T10:05:59.756Z]     task_2(data_size, host)

[2024-01-17T10:05:59.756Z]   File "scripts/action_after_reinstall.py", line 29, in task_2

[2024-01-17T10:05:59.756Z]     load_and_search(prefix)

[2024-01-17T10:05:59.756Z]   File "/home/jenkins/agent/workspace/tests/python_client/deploy/scripts/utils.py", line 249, in load_and_search

[2024-01-17T10:05:59.756Z]     assert len(ids) == topK, f"get {len(ids)} results, but topK is {topK}"

[2024-01-17T10:05:59.756Z] AssertionError: get 4 results, but topK is 5
```

### Expected Behavior

search result length is equal to limit value

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_cron/detail/deploy_test_cron/1814/pipeline
log:
[artifacts-rocksmq-standalone-reinstall-1814-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/13971459/artifacts-rocksmq-standalone-reinstall-1814-server-logs.tar.gz)

[artifacts-rocksmq-standalone-reinstall-1814-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/13971461/artifacts-rocksmq-standalone-reinstall-1814-pytest-logs.tar.gz)

**Comment by xiaofan-luan** [comment]
@zhuwenxing 
this might be as expectd?
how many data is there in your test case, what is the nlist and nprobe?

**Comment by yanliang567** [comment]
keep it

**Comment by xiaofan-luan** [comment]
this could be the same as MVCC issue, i think we are fixing it with retry

**Comment by congqixia** [comment]
@zhuwenxing does this problem persist after retry？
/assign @zhuwenxing

**Comment by zhuwenxing** [comment]
> does this problem persist after retry？

not reproduced in my case yet
