### ISSUE TITLE
Server down during preloading nsg index files

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#3009]
**Please state you issue using the following template and, most importantly, in English.**

**Describe the bug**
dataset : `sift_10m_1024_128_l2_nsg`
index created with using server-version: 0.8
server down when preloading db files
```
[2020-07-25 11:28:51,812][DEBUG][ENGINE][FilesToSearch][reqsched_thread] Collect 5 to-search files in collection sift_10m_1024_128_l2
[2020-07-25 11:28:51,812][DEBUG][ENGINE][FilesToSearchEx][reqsched_thread] No file to search for collection: sift_10m_1024_128_l2
[2020-07-25 11:28:51,812][DEBUG][ENGINE][PreloadCollection][reqsched_thread] Begin pre-load collection:sift_10m_1024_128_l2, totally 5 files need to be pre-loaded
[2020-07-25 11:28:51,812][DEBUG][ENGINE][Build][reqsched_thread] EngineFactory index type: 4
[2020-07-25 11:28:51,812][DEBUG][ENGINE][ExecutionEngineImpl][reqsched_thread] Index params: {"candidate_pool_size":100,"dim":128,"gpu_id":0,"knng":50,"metric_type":"L2","out_degree":40,"search_length":50}
[2020-07-25 11:28:51,813][DEBUG][SERVER][PrintTimeRecord][reqsched_thread] read_index: Start (0.000005 second [0.005454 ms])
[2020-07-25 11:28:51,849][DEBUG][ENGINE][read_internal][reqsched_thread] Start to read_index(/test/milvus/db_data_8/sift_10m_1024_128_l2_nsg/db/tables/sift_10m_1024_128_l2/1587216155817005000/1587295345012492000) length: 2150400071 bytes
[2020-07-25 11:28:52,561][DEBUG][ENGINE][PrintInfo][metric_thread] File reference information:
[2020-07-25 11:28:52,561][DEBUG][ENGINE][PrintInfo][metric_thread]      sift_10m_1024_128_l2: 5 files in use
[2020-07-25 11:28:53,731][DEBUG][ENGINE][PrintInfo][metric_thread] File reference information:
[2020-07-25 11:28:53,731][DEBUG][ENGINE][PrintInfo][metric_thread]      sift_10m_1024_128_l2: 5 files in use
[2020-07-25 11:28:54,843][DEBUG][ENGINE][PrintInfo][metric_thread] File reference information:
[2020-07-25 11:28:54,843][DEBUG][ENGINE][PrintInfo][metric_thread]      sift_10m_1024_128_l2: 5 files in use
[2020-07-25 11:28:55,953][DEBUG][ENGINE][PrintInfo][metric_thread] File reference information:
[2020-07-25 11:28:55,953][DEBUG][ENGINE][PrintInfo][metric_thread]      sift_10m_1024_128_l2: 5 files in use
[2020-07-25 11:28:57,064][DEBUG][ENGINE][PrintInfo][metric_thread] File reference information:
[2020-07-25 11:28:57,064][DEBUG][ENGINE][PrintInfo][metric_thread]      sift_10m_1024_128_l2: 5 files in use
[2020-07-25 11:28:58,188][DEBUG][ENGINE][PrintInfo][metric_thread] File reference information:
[2020-07-25 11:28:58,188][DEBUG][ENGINE][PrintInfo][metric_thread]      sift_10m_1024_128_l2: 5 files in use
[2020-07-25 11:28:59,328][DEBUG][ENGINE][PrintInfo][metric_thread] File reference information:
[2020-07-25 11:28:59,328][DEBUG][ENGINE][PrintInfo][metric_thread]      sift_10m_1024_128_l2: 5 files in use
[2020-07-25 11:29:00,441][DEBUG][ENGINE][PrintInfo][metric_thread] File reference information:
[2020-07-25 11:29:00,441][DEBUG][ENGINE][PrintInfo][metric_thread]      sift_10m_1024_128_l2: 5 files in use
[2020-07-25 11:29:01,551][DEBUG][ENGINE][PrintInfo][metric_thread] File reference information:
[2020-07-25 11:29:01,551][DEBUG][ENGINE][PrintInfo][metric_thread]      sift_10m_1024_128_l2: 5 files in use
[2020-07-25 11:29:02,663][DEBUG][ENGINE][PrintInfo][metric_thread] File reference information:
[2020-07-25 11:29:02,663][DEBUG][ENGINE][PrintInfo][metric_thread]      sift_10m_1024_128_l2: 5 files in use
[2020-07-25 11:29:02,800][DEBUG][SERVER][PrintTimeRecord][reqsched_thread] read_index: End (10.986771 seconds [10986.770763 ms])
[2020-07-25 11:29:02,800][DEBUG][ENGINE][read_internal][reqsched_thread] read_index(/test/milvus/db_data_8/sift_10m_1024_128_l2_nsg/db/tables/sift_10m_1024_128_l2/1587216155817005000/1587295345012492000) rate 186.659MB/s

```
and then k8s pod restarts
**Steps/Code to reproduce behavior**
```

11:28:52  2020-07-25:03:28:51,808 INFO     [client.py:350] Server command: mode, result: CPU
11:28:52  2020-07-25:03:28:51,813 DEBUG    [client.py:277] (Status(code=0, message='Success!'), 10000000)
11:28:52  2020-07-25:03:28:51,815 DEBUG    [client.py:281] Row count: 10000000 in collection: <sift_10m_1024_128_l2>
11:28:52  2020-07-25:03:28:51,815 INFO     [k8s_runner.py:377] 10000000
11:28:52  2020-07-25:03:28:51,817 INFO     [k8s_runner.py:379] {'index_type': 'nsg', 'index_param': {'candidate_pool_size': 100, 'knng': 50, 'out_degree': 40, 'search_length': 50}}
11:30:01  [95m[2020-07-25 03:29:58,219-ERROR-milvus.client.grpc_handler]: 
11:30:01  preload_collection
11:30:01  Rpc error: <_MultiThreadedRendezvous of RPC that terminated with:
11:30:01  	status = StatusCode.UNAVAILABLE
11:30:01  	details = "Connection reset by peer"
11:30:01  	debug_error_string = "{"created":"@1595647798.217596565","description":"Error received from peer ipv4:10.109.76.37:19530","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Connection reset by peer","grpc_status":14}"
11:30:01  >
11:30:01  	{'API start': '2020-07-25 03:28:51.817630', 'RPC start': '2020-07-25 03:28:51.817635', 'RPC error': '2020-07-25 03:29:58.219058'} (grpc_handler.py:49)[0m
11:30:01  2020-07-25:03:29:58,219 ERROR    [grpc_handler.py:49] 
11:30:01  preload_collection
11:30:01  Rpc error: <_MultiThreadedRendezvous of RPC that terminated with:
11:30:01  	status = StatusCode.UNAVAILABLE
11:30:01  	details = "Connection reset by peer"
11:30:01  	debug_error_string = "{"created":"@1595647798.217596565","description":"Error received from peer ipv4:10.109.76.37:19530","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Connection reset by peer","grpc_status":14}"
11:30:01  >
11:30:01  	{'API start': '2020-07-25 03:28:51.817630', 'RPC start': '2020-07-25 03:28:51.817635', 'RPC error': '2020-07-25 03:29:58.219058'}
11:30:01  2020-07-25:03:29:58,219 ERROR    [client.py:102] sift_10m_1024_128_l2
11:30:01  2020-07-25:03:29:58,220 ERROR    [client.py:103] Error occurred. Connection reset by peer
11:30:20  2020-07-25:03:30:19,239 ERROR    [client.py:104] (Status(code=0, message='Success!'), 'OK')
11:30:20  2020-07-25:03:30:19,251 DEBUG    [client.py:277] (Status(code=0, message='Success!'), 10000000)
11:30:20  2020-07-25:03:30:19,262 DEBUG    [client.py:281] Row count: 10000000 in collection: <sift_10m_1024_128_l2>
11:30:20  2020-07-25:03:30:19,262 ERROR    [client.py:105] 10000000
11:30:20  2020-07-25:03:30:19,263 ERROR    [main.py:70] Status not ok
11:30:20  2020-07-25:03:30:19,265 ERROR    [main.py:71] Traceback (most recent call last):
11:30:20    File "main.py", line 68, in queue_worker
11:30:20      runner.run(run_type, collection)
11:30:20    File "/home/jenkins/agent/workspace/milvus-benchmark-0.10.2/milvus_benchmark/k8s_runner.py", line 380, in run
11:30:20      milvus_instance.preload_collection()
11:30:20    File "/home/jenkins/agent/workspace/milvus-benchmark-0.10.2/milvus_benchmark/client.py", line 44, in wrapper
11:30:20      result = func(*args, **kwargs)
11:30:20    File "/home/jenkins/agent/workspace/milvus-benchmark-0.10.2/milvus_benchmark/client.py", line 324, in preload_collection
11:30:20      self.check_status(status)
11:30:20    File "/home/jenkins/agent/workspace/milvus-benchmark-0.10.2/milvus_benchmark/client.py", line 106, in check_status
11:30:20      raise Exception("Status not ok")
11:30:20  Exception: Status not ok
11:30:20  
11:30:30  2020-07-25:03:30:29,275 DEBUG    [k8s_runner.py:70] Start clean up: milvus-benchmark-test-erbkzcvb
```

**Expected behavior**

**Environment details**
logs:
`/test/milvus/db_data_8/sift_10m_1024_128_l2_nsg/logs`

branch:
`0.10.2`

config:
```
11:28:52  2020-07-25:03:28:51,807 INFO     [client.py:350] Server command: get_config *, result: {"cache":{"cache_insert_data":"false","cache_size":"32GB","cpu_cache_threshold":"0.7","insert_buffer_size":"1GB","preload_collection":""},"cluster":{"enable":"false","role":"rw"},"db_config":{"archive_days_threshold":"0","archive_disk_threshold":"0"},"engine_config":{"omp_thread_num":"0","search_combine_nq":"64","simd_type":"auto","use_blas_threshold":"1100"},"general":{"meta_uri":"sqlite://:@:/","timezone":"UTC+8"},"logs":{"level":"debug","log_rotate_num":"0","max_log_file_size":"1024MB","path":"/test/milvus/db_data_8/sift_10m_1024_128_l2_nsg/logs","trace.enable":"true"},"metric":{"address":"192.168.1.237","enable":"true","port":"9091"},"network":{"bind.address":"0.0.0.0","bind.port":"19530","http.enable":"true","http.port":"19121"},"storage":{"auto_flush_interval":"1","file_cleanup_timeout":"10","path":"/test/milvus/db_data_8/sift_10m_1024_128_l2_nsg"},"tracing_config":{"json_config_path":""},"wal":{"buffer_size":"256MB","enable":"true","path":"/test/milvus/db_data_8/sift_10m_1024_128_l2_nsg/wal","recovery_error_ignore":"true"}}
```
**Screenshots**

**Additional context**

**Comment by JinHai-CN** [comment]
Can it be reproduced ?

**Comment by del-zhenwu** [comment]
> Can it be reproduced ?

yes

**Comment by tinkerlin** [comment]
We changed the serialization part of the nsg code.
Refer to PR #2827.

**Comment by del-zhenwu** [comment]
nsg index files can not be used after upgraded to 0.10.1/2 version.
