### ISSUE TITLE
[Bug]: Flush or compact timeout after milvus recover from datanode/datacoord/querynode pod kill/pod failure chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#30137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20240118-ddccccbc
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```

[2024-01-18T19:48:36.785Z] <name>: Checker__Dw9ftQCV

[2024-01-18T19:48:36.785Z] <description>: 

[2024-01-18T19:48:36.785Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}......  (api_request.py:37)

[2024-01-18T19:48:36.785Z] [2024-01-18 19:45:30 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-01-18T19:48:36.785Z] [2024-01-18 19:48:31 - WARNING - pymilvus.decorators]: Retry timeout: 180s (decorators.py:100)

[2024-01-18T19:48:36.785Z] [2024-01-18 19:48:31 - ERROR - pymilvus.decorators]: RPC error: [flush], <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for flush timeout, collection: Checker__Dw9ftQCV)>, <Time:{'RPC start': '2024-01-18 19:45:30.613274', 'RPC error': '2024-01-18 19:48:31.023956'}> (decorators.py:134)

[2024-01-18T19:48:36.785Z] [2024-01-18 19:48:31 - ERROR - ci_test]: Traceback (most recent call last):

[2024-01-18T19:48:36.785Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2024-01-18T19:48:36.785Z]     res = func(*args, **_kwargs)

[2024-01-18T19:48:36.785Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2024-01-18T19:48:36.785Z]     return func(*arg, **kwargs)

[2024-01-18T19:48:36.785Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 314, in flush

[2024-01-18T19:48:36.785Z]     conn.flush([self.name], timeout=timeout, **kwargs)

[2024-01-18T19:48:36.785Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 135, in handler

[2024-01-18T19:48:36.785Z]     raise e from e

[2024-01-18T19:48:36.785Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 131, in handler

[2024-01-18T19:48:36.785Z]     return func(*args, **kwargs)

[2024-01-18T19:48:36.785Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 170, in handler

[2024-01-18T19:48:36.785Z]     return func(self, *args, **kwargs)

[2024-01-18T19:48:36.785Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 101, in handler

[2024-01-18T19:48:36.785Z]     raise MilvusException(

[2024-01-18T19:48:36.785Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for flush timeout, collection: Checker__Dw9ftQCV)>

[2024-01-18T19:48:36.785Z]  (api_request.py:45)
```

```
[2024-01-18T20:45:24.050Z] <name>: Checker__UWvuDf31

[2024-01-18T20:45:24.050Z] <description>: 

[2024-01-18T20:45:24.050Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}......  (api_request.py:37)

[2024-01-18T20:45:24.050Z] [2024-01-18 20:23:38 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-01-18T20:45:24.050Z] [2024-01-18 20:24:04 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-01-18T20:45:24.050Z] [2024-01-18 20:24:04 - DEBUG - ci_test]: (api_request)  : [Collection.compact] args: [180], kwargs: {} (api_request.py:62)

[2024-01-18T20:45:24.050Z] [2024-01-18 20:27:04 - ERROR - pymilvus.decorators]: grpc RpcError: [compact], <_MultiThreadedRendezvous: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded>, <Time:{'RPC start': '2024-01-18 20:24:04.540662', 'gRPC error': '2024-01-18 20:27:04.543365'}> (decorators.py:145)

[2024-01-18T20:45:24.050Z] [2024-01-18 20:27:04 - ERROR - ci_test]: Traceback (most recent call last):

[2024-01-18T20:45:24.050Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2024-01-18T20:45:24.050Z]     res = func(*args, **_kwargs)

[2024-01-18T20:45:24.050Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2024-01-18T20:45:24.050Z]     return func(*arg, **kwargs)

[2024-01-18T20:45:24.050Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 1493, in compact

[2024-01-18T20:45:24.050Z]     self.compaction_id = conn.compact(self._name, timeout=timeout, **kwargs)

[2024-01-18T20:45:24.050Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 149, in handler

[2024-01-18T20:45:24.050Z]     raise e from e

[2024-01-18T20:45:24.050Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 131, in handler

[2024-01-18T20:45:24.050Z]     return func(*args, **kwargs)

[2024-01-18T20:45:24.050Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 170, in handler

[2024-01-18T20:45:24.050Z]     return func(self, *args, **kwargs)

[2024-01-18T20:45:24.050Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 85, in handler

[2024-01-18T20:45:24.050Z]     raise e from e

[2024-01-18T20:45:24.050Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 74, in handler

[2024-01-18T20:45:24.050Z]     return func(*args, **kwargs)

[2024-01-18T20:45:24.050Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 1468, in compact

[2024-01-18T20:45:24.050Z]     response = future.result()

[2024-01-18T20:45:24.050Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 881, in result

[2024-01-18T20:45:24.051Z]     raise self

[2024-01-18T20:45:24.051Z] grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:

[2024-01-18T20:45:24.051Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2024-01-18T20:45:24.051Z] 	details = "Deadline Exceeded"

[2024-01-18T20:45:24.051Z] 	debug_error_string = "UNKNOWN:Deadline Exceeded {grpc_status:4, created_time:"2024-01-18T20:27:04.542839932+00:00"}"

[2024-01-18T20:45:24.051Z] >

[2024-01-18T20:45:24.051Z]  (api_request.py:45)

[2024-01-18T20:45:24.051Z] [2024-01-18 20:27:04 - ERROR - ci_test]: (api_response) : <_MultiThreadedRendezvous of RPC that terminated with:

[2024-01-18T20:45:24.051Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2024-01-18T20:45:24.051Z] 	details = "Deadline Exceeded"

[2024-01-18T20:45:24.051Z] 	debug_error_string = "UNKNOWN:Deadline Exceeded {grpc_status:4, created_time:"2024-01-18T20:27:04.542839932+00:00"}"

[2024-01-18T20:45:24.051Z] > (api_request.py:46)
```

### Milvus Log

compact timeout:
* datanode pod-failure: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-cron/detail/chaos-test-kafka-cron/10690/pipeline

flush timeout:
* datacoord pod-failure: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/10766/pipeline
* querynode pod-kill:https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-cron/detail/chaos-test-kafka-cron/10682/pipeline
 
log:
[artifacts-querynode-pod-kill-10682-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/13986620/artifacts-querynode-pod-kill-10682-server-logs.tar.gz)

[artifacts-datanode-pod-failure-10690-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/13986626/artifacts-datanode-pod-failure-10690-server-logs.tar.gz)

[artifacts-datacoord-pod-failure-10766-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/13986630/artifacts-datacoord-pod-failure-10766-server-logs.tar.gz)

**Comment by ThreadDao** [comment]
@XuanYang-cn 
Stable recurrence. Flush `Unrecoverable error` or `Deadline Exceeded` after remove chaos(pod-kill or pod-failure) from datacoord and minio
- datacoord: https://qa-jenkins.milvus.io/job/chaos-test-kafka-cron/11168/
- minio: https://qa-jenkins.milvus.io/job/chaos-test-kafka-cron/11150/

**Comment by XuanYang-cn** [comment]
> @XuanYang-cn Stable recurrence. Flush `Unrecoverable error` or `Deadline Exceeded` after remove chaos(pod-kill or pod-failure) from datacoord and minio
> 
> * datacoord: https://qa-jenkins.milvus.io/job/chaos-test-kafka-cron/11168/
> * minio: https://qa-jenkins.milvus.io/job/chaos-test-kafka-cron/11150/

Flush stucked here at DataNode `FlushChannels`
![image](https://github.com/milvus-io/milvus/assets/51370125/0fdac082-6780-4523-8b2e-5788834b98ac)

**Comment by xiaofan-luan** [comment]
this could a important issue also for 2.3

**Comment by XuanYang-cn** [comment]
Not deadlocked, looks like network issue
![image](https://github.com/milvus-io/milvus/assets/51370125/4885e18f-3c39-4c00-a97d-3f7f801311a0)
Proxy receive Flush at `20:32:54`
DataCoord receive Flush at `20:35:54`, already timeout and failed for `flush timeout=180s`

**Comment by xiaofan-luan** [comment]
could this be some queue in the system internally?

**Comment by zhuwenxing** [comment]
Now, this issue mainly and stably happened in the datacoord pod kill chaos test

failed job: 
* https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-cron/detail/chaos-test-kafka-cron/11632/pipeline
* https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/11738/pipeline

image tag: master-20240220-e5a16050

**Comment by xiaofan-luan** [comment]
> Not deadlocked, looks like network issue ![image](https://private-user-images.githubusercontent.com/51370125/302498911-4885e18f-3c39-4c00-a97d-3f7f801311a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0ODYyNjYsIm5iZiI6MTcwODQ4NTk2NiwicGF0aCI6Ii81MTM3MDEyNS8zMDI0OTg5MTEtNDg4NWUxOGYtM2MzOS00YzAwLWE5N2QtM2Y3ZjgwMTMxMWEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDAzMjYwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3NTM0ZmE2MzAzNDIyN2VlNjIwN2FhZDdjZGYzMGZjNDQwMDMzMWI3MDkxYmYyZjk3NDM5MDQ0MTY5ODcyZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hwb8CmElWZD_Qx1jIaPV3MvjuymkST71gwGpxOEpClg) Proxy receive Flush at `20:32:54` DataCoord receive Flush at `20:35:54`, already timeout and failed for `flush timeout=180s`

add some more logs about how the flush is queued so we know where is the reqeust is blocked or queued?

**Comment by xiaofan-luan** [comment]
We need a debug mode to reproduce these features:
1. all logs are enabled to debug level
2. GRPC_GO_LOG_VERBOSITY_LEVEL=99 GRPC_GO_LOG_SEVERITY_LEVEL=info to enable more detailed grpc log
3. periodically run pprof including
    1. Goroutine pprofile
    2. Block pprofile
    3. CPU profile
    4. Heap profile 
    5. Trace for last 10s

**Comment by xiaofan-luan** [comment]
The recoverable error could be throwed  from grpc client when node session is lilled

**Comment by XuanYang-cn** [comment]
Compaction timeout & some flush timeout reason:

1. Unfinished compaction will block thoes segments flush and compaction
2. Restart of DC will clear previous compaction tasks from DC, making tasks generated before restart never going to be finished
3. DN will block at flush & compaction of those segments

- #30850 would fix the problem in master

**Comment by XuanYang-cn** [comment]
2.3 has the same problem, but never tested out, bacause

1. compaction is unable to block those segments once the flush happened after compaction inject done(which need to be fixed)
2. The regenerated compaction task after DC restarted is unable to be blocked by previous compaction(which is fine)

**Comment by XuanYang-cn** [comment]
@zhuwenxing Please help veirify the master branch

**Comment by zhuwenxing** [comment]
not happen in the datacoord chaos test but in the etcd chaos test

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/12138/pipeline

log:
[artifacts-etcd-pod-kill-12138-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/14489627/artifacts-etcd-pod-kill-12138-server-logs.tar.gz)

**Comment by zhuwenxing** [comment]
It also happened after reinstallation or upgrading

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_cron/detail/deploy_test_cron/2001/pipeline
log:
[artifacts-pulsar-cluster-reinstall-2001-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/14489689/artifacts-pulsar-cluster-reinstall-2001-server-logs.tar.gz)

**Comment by zhuwenxing** [comment]
@XuanYang-cn 
It still reproduced in `master-20240312-de2c95d0` which should have already enabled L0 compact.
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/12370/pipeline
log:

[artifacts-datanode-pod-kill-12370-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/14581182/artifacts-datanode-pod-kill-12370-server-logs.tar.gz)

**Comment by aoiasd** [comment]
> @XuanYang-cn It still reproduced in `master-20240312-de2c95d0` which should have already enabled L0 compact. failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/12370/pipeline log:
> 
> [artifacts-datanode-pod-kill-12370-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/14581182/artifacts-datanode-pod-kill-12370-server-logs.tar.gz)

![image](https://github.com/milvus-io/milvus/assets/45024769/d90a3314-02e2-48b3-aa6e-a48256c36cd2)
Find segment loss in datanode matacache cause insert buffer failed and data loss.
Will fix by @congqixia

**Comment by XuanYang-cn** [comment]
/assign @zhuwenxing
Please help verify
/unassign

**Comment by zhuwenxing** [comment]
still reproduced in image tag`master-20240321-09281a07-amd64`

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/12681/pipeline
log:
[artifacts-s3-pod-failure-12681-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/14716304/artifacts-s3-pod-failure-12681-server-logs.tar.gz)
```

[2024-03-21T21:32:53.426Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[Checker__xuA9G03s] - AssertionError: Response of API flush expect True, but got False

[2024-03-21T21:32:53.426Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[Checker__vXi9oJPB] - AssertionError: Response of API flush expect True, but got False

[2024-03-21T21:32:53.426Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[Checker__sj8FMQcA] - AssertionError: Response of API flush expect True, but got False

[2024-03-21T21:32:53.426Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[Checker__U7kjLPDQ] - AssertionError: Response of API flush expect True, but got False

[2024-03-21T21:32:53.426Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[InsertChecker__lYgFQuGk] - AssertionError: Response of API flush expect True, but got False

[2024-03-21T21:32:53.426Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[DropChecker__hs2q8puA] - AssertionError: Response of API flush expect True, but got False

[2024-03-21T21:32:53.426Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[IndexChecker__v54pvpgb] - AssertionError: Response of API flush expect True, but got False

[2024-03-21T21:32:53.426Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[CreateChecker__2QIjSMIY] - AssertionError: Response of API flush expect True, but got False

[2024-03-21T21:32:53.426Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[DeleteChecker__x9QA0oRx] - AssertionError: Response of API flush expect True, but got False

[2024-03-21T21:32:53.426Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[FlushChecker__xlx7s4Xu] - AssertionError: Response of API flush expect True, but got False

[2024-03-21T21:32:53.426Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[Checker__dB4Zakqq] - AssertionError: Response of API flush expect True, but got False

[2024-03-21T21:32:53.426Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[HybridSearchChecker__6Yjmdgm0] - AssertionError: Response of API flush expect True, but got False

[2024-03-21T21:32:53.426Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[SearchChecker__uBtpdNwI] - AssertionError: Response of API flush expect True, but got False

[2024-03-21T21:32:53.426Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[UpsertChecker__s82T1rNu] - AssertionError: Response of API flush expect True, but got False

[2024-03-21T21:32:53.426Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[QueryChecker__JGHbptZU] - AssertionError: Response of API flush expect True, but got False

[2024-03-21T21:32:53.426Z] ======================== 15 failed in 888.90s (0:14:48) ========================
```


cluster: 4am
namespace: chaos-testing
pod info
```
[2024-03-21T21:17:35.045Z] + kubectl get pods -o wide

[2024-03-21T21:17:35.047Z] + grep s3-pod-failure-12681

[2024-03-21T21:17:35.302Z] s3-pod-failure-12681-etcd-0                                       1/1     Running       0               38m     10.104.24.144   4am-node29   <none>           <none>

[2024-03-21T21:17:35.302Z] s3-pod-failure-12681-etcd-1                                       1/1     Running       0               38m     10.104.32.104   4am-node39   <none>           <none>

[2024-03-21T21:17:35.302Z] s3-pod-failure-12681-etcd-2                                       1/1     Running       0               38m     10.104.20.199   4am-node22   <none>           <none>

[2024-03-21T21:17:35.302Z] s3-pod-failure-12681-milvus-datacoord-6d4858cf6c-fshml            1/1     Running       0               38m     10.104.25.62    4am-node30   <none>           <none>

[2024-03-21T21:17:35.302Z] s3-pod-failure-12681-milvus-datanode-84655fbfc4-ktlkk             1/1     Running       0               38m     10.104.14.79    4am-node18   <none>           <none>

[2024-03-21T21:17:35.302Z] s3-pod-failure-12681-milvus-datanode-84655fbfc4-kvws8             1/1     Running       4 (6m46s ago)   38m     10.104.25.67    4am-node30   <none>           <none>

[2024-03-21T21:17:35.302Z] s3-pod-failure-12681-milvus-indexcoord-66cdcc9fd6-t2sqq           1/1     Running       0               38m     10.104.25.61    4am-node30   <none>           <none>

[2024-03-21T21:17:35.302Z] s3-pod-failure-12681-milvus-indexnode-554988c759-4p4qr            1/1     Running       0               38m     10.104.29.102   4am-node35   <none>           <none>

[2024-03-21T21:17:35.302Z] s3-pod-failure-12681-milvus-indexnode-554988c759-c4flk            1/1     Running       0               38m     10.104.1.248    4am-node10   <none>           <none>

[2024-03-21T21:17:35.303Z] s3-pod-failure-12681-milvus-indexnode-554988c759-cc77g            1/1     Running       0               38m     10.104.33.38    4am-node36   <none>           <none>

[2024-03-21T21:17:35.303Z] s3-pod-failure-12681-milvus-proxy-5889f7d6f4-kcww5                1/1     Running       0               38m     10.104.25.63    4am-node30   <none>           <none>

[2024-03-21T21:17:35.303Z] s3-pod-failure-12681-milvus-querycoord-7bf9466ddf-xqz2g           1/1     Running       0               38m     10.104.25.66    4am-node30   <none>           <none>

[2024-03-21T21:17:35.303Z] s3-pod-failure-12681-milvus-querynode-567cd6cc75-6vw9z            1/1     Running       0               38m     10.104.25.60    4am-node30   <none>           <none>

[2024-03-21T21:17:35.303Z] s3-pod-failure-12681-milvus-querynode-567cd6cc75-f6wlr            1/1     Running       0               38m     10.104.19.69    4am-node28   <none>           <none>

[2024-03-21T21:17:35.303Z] s3-pod-failure-12681-milvus-querynode-567cd6cc75-p7mcm            1/1     Running       0               38m     10.104.33.37    4am-node36   <none>           <none>

[2024-03-21T21:17:35.303Z] s3-pod-failure-12681-milvus-rootcoord-78497f6b47-55db9            1/1     Running       0               38m     10.104.25.59    4am-node30   <none>           <none>

[2024-03-21T21:17:35.303Z] s3-pod-failure-12681-minio-0                                      1/1     Running       8 (14m ago)     38m     10.104.17.127   4am-node23   <none>           <none>

[2024-03-21T21:17:35.303Z] s3-pod-failure-12681-minio-1                                      1/1     Running       8 (15m ago)     38m     10.104.20.196   4am-node22   <none>           <none>

[2024-03-21T21:17:35.303Z] s3-pod-failure-12681-minio-2                                      1/1     Running       8 (14m ago)     38m     10.104.24.146   4am-node29   <none>           <none>

[2024-03-21T21:17:35.303Z] s3-pod-failure-12681-minio-3                                      1/1     Running       8 (14m ago)     38m     10.104.32.107   4am-node39   <none>           <none>

[2024-03-21T21:17:35.303Z] s3-pod-failure-12681-pulsar-bookie-0                              1/1     Running       0               38m     10.104.32.102   4am-node39   <none>           <none>

[2024-03-21T21:17:35.303Z] s3-pod-failure-12681-pulsar-bookie-1                              1/1     Running       0               38m     10.104.20.198   4am-node22   <none>           <none>

[2024-03-21T21:17:35.303Z] s3-pod-failure-12681-pulsar-bookie-init-5kfh6                     0/1     Completed     0               38m     10.104.5.170    4am-node12   <none>           <none>

[2024-03-21T21:17:35.303Z] s3-pod-failure-12681-pulsar-broker-0                              1/1     Running       0               38m     10.104.9.171    4am-node14   <none>           <none>

[2024-03-21T21:17:35.303Z] s3-pod-failure-12681-pulsar-proxy-0                               1/1     Running       0               38m     10.104.5.171    4am-node12   <none>           <none>

[2024-03-21T21:17:35.303Z] s3-pod-failure-12681-pulsar-pulsar-init-k6dzw                     0/1     Completed     0               38m     10.104.5.169    4am-node12   <none>           <none>

[2024-03-21T21:17:35.303Z] s3-pod-failure-12681-pulsar-recovery-0                            1/1     Running       0               38m     10.104.5.172    4am-node12   <none>           <none>

[2024-03-21T21:17:35.303Z] s3-pod-failure-12681-pulsar-zookeeper-0                           1/1     Running       0               38m     10.104.17.125   4am-node23   <none>           <none>
```

**Comment by XuanYang-cn** [comment]
One of the DataNode restarted twice after 12:17:35, making flush during 12:17-12:30 timeout.

![image](https://github.com/milvus-io/milvus/assets/51370125/393af4ab-1b4c-464f-82ce-e87362a17bfa)

**Comment by XuanYang-cn** [comment]
Comsumer busy cased by nodeID=0 for dispatcher: #31516 
![image](https://github.com/milvus-io/milvus/assets/51370125/28d94071-7969-47ce-a97e-bbeb1cde973f)
![image](https://github.com/milvus-io/milvus/assets/51370125/773e7533-932a-43ee-a702-4bfa4c216f22)

**Comment by XuanYang-cn** [comment]
Releated: #31518 
/assign @zhuwenxing 
Please help verify in master

**Comment by zhuwenxing** [comment]
still reproduced in `2.4-20240405-841f9e4f-amd64`

```

[2024-04-06T22:02:44.885Z] <name>: Checker__gDhcHH2H

[2024-04-06T22:02:44.885Z] <description>: 

[2024-04-06T22:02:44.885Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}......  (api_request.py:37)

[2024-04-06T22:02:44.885Z] [2024-04-06 21:47:57 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-04-06T22:02:44.885Z] [2024-04-06 21:50:57 - ERROR - pymilvus.decorators]: grpc RpcError: [flush], <_MultiThreadedRendezvous: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded>, <Time:{'RPC start': '2024-04-06 21:47:57.006781', 'gRPC error': '2024-04-06 21:50:57.008366'}> (decorators.py:157)

[2024-04-06T22:02:44.885Z] [2024-04-06 21:50:57 - ERROR - ci_test]: Traceback (most recent call last):

[2024-04-06T22:02:44.885Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2024-04-06T22:02:44.885Z]     res = func(*args, **_kwargs)

[2024-04-06T22:02:44.885Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2024-04-06T22:02:44.885Z]     return func(*arg, **kwargs)

[2024-04-06T22:02:44.885Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 317, in flush

[2024-04-06T22:02:44.885Z]     conn.flush([self.name], timeout=timeout, **kwargs)

[2024-04-06T22:02:44.885Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 161, in handler

[2024-04-06T22:02:44.885Z]     raise e from e

[2024-04-06T22:02:44.885Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 143, in handler

[2024-04-06T22:02:44.885Z]     return func(*args, **kwargs)

[2024-04-06T22:02:44.885Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 182, in handler

[2024-04-06T22:02:44.885Z]     return func(self, *args, **kwargs)

[2024-04-06T22:02:44.885Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 91, in handler

[2024-04-06T22:02:44.885Z]     raise e from e

[2024-04-06T22:02:44.885Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 87, in handler

[2024-04-06T22:02:44.885Z]     return func(*args, **kwargs)

[2024-04-06T22:02:44.885Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 1396, in flush

[2024-04-06T22:02:44.885Z]     response = future.result()

[2024-04-06T22:02:44.885Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 881, in result

[2024-04-06T22:02:44.885Z]     raise self

[2024-04-06T22:02:44.885Z] grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:

[2024-04-06T22:02:44.885Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2024-04-06T22:02:44.885Z] 	details = "Deadline Exceeded"

[2024-04-06T22:02:44.885Z] 	debug_error_string = "UNKNOWN:Deadline Exceeded {grpc_status:4, created_time:"2024-04-06T21:50:57.007850385+00:00"}"

[2024-04-06T22:02:44.885Z] >

[2024-04-06T22:02:44.885Z]  (api_request.py:45)

[2024-04-06T22:02:44.885Z] [2024-04-06 21:50:57 - ERROR - ci_test]: (api_response) : <_MultiThreadedRendezvous of RPC that terminated with:

[2024-04-06T22:02:44.885Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2024-04-06T22:02:44.885Z] 	details = "Deadline Exceeded"

[2024-04-06T22:02:44.885Z] 	debug_error_string = "UNKNOWN:Deadline Exceeded {grpc_status:4, created_time:"2024-04-06T21:50:57.007850385+00:00"}"

[2024-04-06T22:02:44.885Z] > (api_request.py:46)
```
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-for-release-cron/detail/chaos-test-for-release-cron/11721/pipeline
log: [artifacts-rootcoord-pod-kill-11721-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/14895632/artifacts-rootcoord-pod-kill-11721-server-logs.tar.gz)

**Comment by XuanYang-cn** [comment]
> Not deadlocked, looks like network issue Proxy receive Flush at `20:32:54` DataCoord receive Flush at `20:35:54`, already timeout and failed for `flush timeout=180s`

Back to this problem

![image](https://github.com/milvus-io/milvus/assets/51370125/4496cf18-001f-47e8-8abc-c7813f9ed174)

**Comment by xiaofan-luan** [comment]
> > Not deadlocked, looks like network issue Proxy receive Flush at `20:32:54` DataCoord receive Flush at `20:35:54`, already timeout and failed for `flush timeout=180s`
> 
> Back to this problem
> 
> ![image](https://private-user-images.githubusercontent.com/51370125/320261387-4496cf18-001f-47e8-8abc-c7813f9ed174.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MTQzMTUsIm5iZiI6MTcxMjUxNDAxNSwicGF0aCI6Ii81MTM3MDEyNS8zMjAyNjEzODctNDQ5NmNmMTgtMDAxZi00N2U4LThhYmMtYzc4MTNmOWVkMTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDE4MjAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkMDBlZjY5OTZkYmExODdmY2UxZGU4Mjk5NzhmZmY3NmQ4YzM2YmZkZjFiMTUyNTQ1ODcwZjFhMDI3NWI4NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wctpkUEdKMjcOlVTrc2m2ulA_mF6c2fl-FZ9G0xC4pk)

Did we have any metrics for the queue size? Maybe it's just because of flush can not catch up and queue size accumulate in proxy

**Comment by yanliang567** [comment]
file a new issues for  individual chaos failure, close this one for now
