### ISSUE TITLE
[Bug]: Milvus panic with error `field brain_float_vector row num not match 1500, other column 3000: service internal error: row num not match` and then keep restart

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#30138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20240117-1185e4dc
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2024/01/19 08:59:12.923 +00:00] [INFO] [msgdispatcher/dispatcher.go:205] ["begin to work"] [pchannel=by-dev-rootcoord-dml_14] [isMain=false]
[2024/01/19 08:59:12.923 +00:00] [INFO] [datanode/flow_graph_dmstream_input_node.go:53] ["datanode seek successfully when register to msgDispatcher"] [nodeID=4] [collectionID=447084827054456537] [vchannel=by-dev-rootcoord-dml_14_447084827054456537v0] [msgID="8\u0000\ufffd\ufffdŃ4\u0006"] [tsTime=2024/01/19 08:58:40.502 +00:00] [tsLag=32.421210711s]
[2024/01/19 08:59:12.923 +00:00] [INFO] [msgstream/mq_msgstream.go:853] ["MsgStream begin to seek start msg: "] [channel=by-dev-rootcoord-dml_11] [MessageID="QgDkqsWDNAY="]
[2024/01/19 08:59:12.923 +00:00] [INFO] [datacoord/meta.go:1282] ["UpdateChannelCheckpoint done"] [vChannel=by-dev-rootcoord-dml_6_447084827054408916v0] [ts=447127158929489921] [msgID="(\u0000\ufffd+ȃ4\u0006"] [time=2024/01/19 08:59:10.555 +00:00]
[2024/01/19 08:59:12.923 +00:00] [ERROR] [datanode/flow_graph_write_node.go:76] ["failed to buffer data"] [error="field brain_float_vector row num not match 1500, other column 3000: service internal error: row num not match"] [errorVerbose="field brain_float_vector row num not match 1500, other column 3000: service internal error: row num not match\n(1) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus/pkg/util/merr.WrapErrServiceInternal\n  | \t/go/src/github.com/milvus-io/milvus/pkg/util/merr/utils.go:348\n  | github.com/milvus-io/milvus/internal/storage.ColumnBasedInsertMsgToInsertData\n  | \t/go/src/github.com/milvus-io/milvus/internal/storage/utils.go:648\n  | github.com/milvus-io/milvus/internal/storage.InsertMsgToInsertData\n  | \t/go/src/github.com/milvus-io/milvus/internal/storage/utils.go:664\n  | github.com/milvus-io/milvus/internal/datanode/writebuffer.(*InsertBuffer).Buffer\n  | \t/go/src/github.com/milvus-io/milvus/internal/datanode/writebuffer/insert_buffer.go:125\n  | github.com/milvus-io/milvus/internal/datanode/writebuffer.(*writeBufferBase).bufferInsert\n  | \t/go/src/github.com/milvus-io/milvus/internal/datanode/writebuffer/write_buffer.go:352\n  | github.com/milvus-io/milvus/internal/datanode/writebuffer.(*bfWriteBuffer).BufferData\n  | \t/go/src/github.com/milvus-io/milvus/internal/datanode/writebuffer/bf_write_buffer.go:36\n  | github.com/milvus-io/milvus/internal/datanode/writebuffer.(*bufferManager).BufferData\n  | \t/go/src/github.com/milvus-io/milvus/internal/datanode/writebuffer/manager.go:111\n  | github.com/milvus-io/milvus/internal/datanode.(*writeNode).Operate\n  | \t/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_write_node.go:74\n  | github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtxManager).workNodeStart\n  | \t/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:125\n  | runtime.goexit\n  | \t/usr/local/go/src/runtime/asm_amd64.s:1598\nWraps: (2) field brain_float_vector row num not match 1500, other column 3000\nWraps: (3) service internal error: row num not match\nError types: (1) *withstack.withStack (2) *errutil.withPrefix (3) merr.milvusError"] [stack="github.com/milvus-io/milvus/internal/datanode.(*writeNode).Operate\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_write_node.go:76\ngithub.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtxManager).workNodeStart\n\t/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:125"]
[2024/01/19 08:59:12.923 +00:00] [INFO] [msgstream/mq_msgstream.go:863] ["MsgStream seek finished"] [channel=by-dev-rootcoord-dml_11]
panic: field brain_float_vector row num not match 1500, other column 3000: service internal error: row num not match

goroutine 2368 [running]:
panic({0x4e3a7a0, 0xc00547def0})
	/usr/local/go/src/runtime/panic.go:987 +0x3bb fp=0xc004271b38 sp=0xc004271a78 pc=0x1af1d9b
github.com/milvus-io/milvus/internal/datanode.(*writeNode).Operate(0xc005444a50, {0xc005443980?, 0x57?, 0x1?})
	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_write_node.go:77 +0xc4e fp=0xc004271e90 sp=0xc004271b38 pc=0x40b768e
github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtxManager).workNodeStart(0xc00546a210)
	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:125 +0x3ac fp=0xc004271fc8 sp=0xc004271e90 pc=0x3ed836c
github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtxManager).Start.func1()
	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:78 +0x26 fp=0xc004271fe0 sp=0xc004271fc8 pc=0x3ed7f86
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc004271fe8 sp=0xc004271fe0 pc=0x1b2bbe1
created by github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtxManager).Start
	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:78 +0x6a
```

### Anything else?

The error is row number does not match. But all fields row num is 3000.

Even if it is wrong, the error should be handled and not make Milvus keep restart

test script:
```
import random
import numpy as np
import time
import argparse
from pymilvus import (
    connections,
    FieldSchema, CollectionSchema, DataType,
    Collection,
    AnnSearchRequest, RRFRanker
)
import tensorflow as tf

TIMEOUT = 120


def hello_milvus(host="127.0.0.1"):
    import time
    # create connection
    connections.connect(host=host, port="19530")

    # create collection
    dim = 2
    default_fields = [
        FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True),
        FieldSchema(name="float", dtype=DataType.FLOAT),
        FieldSchema(name="varchar", dtype=DataType.VARCHAR, max_length=65535),
        FieldSchema(name="array_int", dtype=DataType.ARRAY, element_type=DataType.INT64, max_capacity=200),
        FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim),
        FieldSchema(name="brain_float_vector", dtype=DataType.BFLOAT16_VECTOR, dim=dim)
    ]
    default_schema = CollectionSchema(fields=default_fields, description="test collection")

    print(f"\nCreate collection...")
    collection = Collection(name="hello_milvus_1655", schema=default_schema)

    #  insert data
    nb = 3000
    float_query_vectors = [[random.random() for _ in range(dim)] for _ in range(10)]
    bf16_query_vectors = [tf.constant([random.random() for _ in range(dim)], dtype=tf.bfloat16) for _ in range(10)]
    t0 = time.time()
    data = [
            [i for i in range(nb)],
            [np.float32(i) for i in range(nb)],
            [str(i) for i in range(nb)],
            [[1,2] for _ in range(nb)],
            [[random.random() for _ in range(dim)] for _ in range(nb)],
            [tf.constant([random.random() for _ in range(dim)], dtype=tf.bfloat16) for _ in range(nb)],
        ]
    # print(data)
    collection.insert(data)
    t1 = time.time()
    print(f"\nInsert {nb} vectors cost {t1 - t0:.4f} seconds")

    t0 = time.time()
    print(f"\nGet collection entities...")
    collection.flush()
    print(collection.num_entities)
    t1 = time.time()
    print(f"\nGet collection entities cost {t1 - t0:.4f} seconds")

    print("\nGet replicas number")
    try:
        replicas_info = collection.get_replicas()
        replica_number = len(replicas_info.groups)
        print(f"\nReplicas number is {replica_number}")
    except Exception as e:
        print(str(e))
        replica_number = 1

    # create index and load table
    default_index = {"index_type": "IVF_SQ8", "metric_type": "L2", "params": {"nlist": 64}}
    print(f"\nCreate index...")
    t0 = time.time()

    collection.release()

    collection.create_index(field_name="float_vector", index_params=default_index)
    collection.create_index(field_name="image_emb", index_params=default_index)
    t1 = time.time()
    print(f"\nCreate index cost {t1 - t0:.4f} seconds")
    print(f"\nload collection...")
    t0 = time.time()
    collection.load(replica_number=replica_number)
    t1 = time.time()
    print(f"\nload collection cost {t1 - t0:.4f} seconds")

    # load and search
    topK = 5
    search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
    t0 = time.time()
    print(f"\nSearch...")
    # define output_fields of search result
    res = collection.search(
        float_query_vectors[-2:], "float_vector", search_params, topK,
        "int64 > 100", output_fields=["int64", "float"], timeout=TIMEOUT
    )
    t1 = time.time()
    print(f"search cost  {t1 - t0:.4f} seconds")
    # show result
    for hits in res:
        for hit in hits:
            # Get value of the random value field for search result
            print(hit, hit.entity.get("float"))
    t0 = time.time()
    print(f"\nSearch...")
    # define output_fields of search result
    res = collection.search(
        float_query_vectors[-2:], "brain_float_vector", search_params, topK,
        "int64 > 100", output_fields=["int64", "float"], timeout=TIMEOUT
    )
    t1 = time.time()
    print(f"search cost  {t1 - t0:.4f} seconds")
    # show result
    for hits in res:
        for hit in hits:
            # Get value of the random value field for search result
            print(hit, hit.entity.get("float"))

    # query
    expr = "int64 in [2,4,6,8]"
    output_fields = ["int64", "float"]
    res = collection.query(expr, output_fields, timeout=TIMEOUT)
    sorted_res = sorted(res, key=lambda k: k['int64'])
    for r in sorted_res:
        print(r)

    reqs = [
        AnnSearchRequest(**{
            "data":[float_query_vectors[-1]],
            "anns_field":"float_vector",
            "param": {"metric_type": "L2"},
            "limit": 10,
        }),
        AnnSearchRequest(**{
            "data": [bf16_query_vectors[-1]],
            "anns_field": "brain_float_vector",
            "param": {"metric_type": "L2"},
            "limit": 10,
        })
    ]
    # search for each field
    for r in reqs:
        res = collection.search(
            data=r.data,
            anns_field=r.anns_field,
            param=r.param,
            limit=r.limit,
        )
        print(f"search result for {r.anns_field}: {res}")

    # hybrid search
    res = collection.hybrid_search(
        reqs=reqs,
        rerank=RRFRanker(),
        limit=10,
    )
    print(f"hybrid search result: {res}")


parser = argparse.ArgumentParser(description='host ip')
parser.add_argument('--host', type=str, default='127.0.0.1', help='host ip')
args = parser.parse_args()
# add time stamp
print(f"\nStart time: {time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(time.time()))}")
hello_milvus(args.host)

```

**Comment by cqy123456** [comment]
please use latest pymilvus. 
And it will report :
`pymilvus.exceptions.ParamError: <ParamError: (code=1, message=Collection field dim is 2, but entities field dim is 1)>`
Because float16 vector and bfloat16 should be input as bytes, instead of tensor or numpy array. 
The len of tensor and  numpy array is the number of  a vector, instead of the storage size. @zhuwenxing

**Comment by yanliang567** [comment]
@cqy123456 but we shall not crash milvus in any cases or by any versions of pymilvus. please help to improve.

**Comment by xiaofan-luan** [comment]
> please use latest pymilvus. And it will report : `pymilvus.exceptions.ParamError: <ParamError: (code=1, message=Collection field dim is 2, but entities field dim is 1)>` Because float16 vector and bfloat16 should be input as bytes, instead of tensor or numpy array. New error case by: the len of tensor and numpy array is the number of a vector, instead of the storage size. pymilvus use len function to get error vector length. @zhuwenxing

is there a way to add check on server side?

**Comment by cqy123456** [comment]
This is a bug of all vector types. When fielddata dim no match to schema dim,  appendfielddata function of proxy will use fielddata dim instead of schema dim to generate data.  And the insertmsg of proxy and datanode is different. 
float16 and bfloat16 pass some length check on proxy, but get the wrong insertmsg in datanode

**Comment by zhuwenxing** [comment]
pymilvus:2.4.0rc24
milvus: 2.4-20240407-e3b65203-amd64

```
Create collection...
RPC error: [batch_insert], <MilvusException: (code=1100, message=the dim (1) of field data(brain_float_vector) is not equal to schema dim (2): invalid parameter[expected=1][actual=2])>, <Time:{'RPC start': '2024-04-07 11:39:03.677351', 'RPC error': '2024-04-07 11:39:03.792440'}>

```

the error is reported by server
