### ISSUE TITLE
[Bug]: a standalone with rocksmq may need to panic and restart several times before it can run normally after pod killed

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#30355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 74cfba02
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2024/01/30 03:24:23.849 +00:00] [DEBUG] [querycoord/service.go:168] ["QueryCoord try to wait for RootCoord ready"]
[2024/01/30 03:24:23.849 +00:00] [DEBUG] [rootcoord/service.go:225] ["RootCoord start to create QueryCoord client"]
[2024/01/30 03:24:23.849 +00:00] [DEBUG] [sessionutil/session_util.go:254] ["Session try to connect to etcd"]
[2024/01/30 03:24:23.849 +00:00] [DEBUG] [sessionutil/session_util.go:269] ["Session connect to etcd success"]
[2024/01/30 03:24:23.850 +00:00] [FATAL] [msgstream/mq_factory.go:16] ["fail to init rocksmq"] [error="IO error: While lock file: /var/lib/milvus/rdb_data_meta_kv/LOCK: Resource temporarily unavailable"] [stack="github.com/milvus-io/milvus/internal/mq/msgstream.NewRocksmqFactory\n\t/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_factory.go:16\ngithub.com/milvus-io/milvus/internal/util/dependency.(*DefaultFactory).initMQ\n\t/go/src/github.com/milvus-io/milvus/internal/util/dependency/factory.go:92\ngithub.com/milvus-io/milvus/internal/util/dependency.(*DefaultFactory).Init\n\t/go/src/github.com/milvus-io/milvus/internal/util/dependency/factory.go:78\ngithub.com/milvus-io/milvus/internal/datacoord.(*Server).Init\n\t/go/src/github.com/milvus-io/milvus/internal/datacoord/server.go:308\ngithub.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:129\ngithub.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:252\ngithub.com/milvus-io/milvus/cmd/components.(*DataCoord).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/data_coord.go:50\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:110"]
panic: fail to init rocksmq

goroutine 320 [running]:
panic({0x4a84ae0, 0xc001150d70})
	/usr/local/go/src/runtime/panic.go:987 +0x3bb fp=0xc00083d620 sp=0xc00083d560 pc=0x1b13d9b
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x1?, 0x1?, {0x0?, 0x0?, 0xc00092f5e0?})
	/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x65 fp=0xc00083d640 sp=0xc00083d620 pc=0x1d11b25
go.uber.org/zap/zapcore.(*CheckWriteAction).OnWrite(0x0?, 0x0?, {0xc0015524c0?, 0x0?, 0x0?})
	<autogenerated>:1 +0x2f fp=0xc00083d678 sp=0xc00083d640 pc=0x1d2356f
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00069e0d0, {0xc0015524c0, 0x1, 0x1})
	/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x3ec fp=0xc00083d808 sp=0xc00083d678 pc=0x1d1208c
go.uber.org/zap.(*Logger).Fatal(0xc001132000?, {0x526e479?, 0x0?}, {0xc0015524c0, 0x1, 0x1})
	/go/pkg/mod/go.uber.org/zap@v1.24.0/logger.go:269 +0x59 fp=0xc00083d838 sp=0xc00083d808 pc=0x1f63659
github.com/milvus-io/milvus/pkg/log.Fatal({0x526e479?, 0xa?}, {0xc0015524c0?, 0x2838a30?, 0xc001154230?})
	/go/src/github.com/milvus-io/milvus/pkg/log/global.go:65 +0x8b fp=0xc00083d888 sp=0xc00083d838 pc=0x210008b
github.com/milvus-io/milvus/internal/mq/msgstream.NewRocksmqFactory({0xc0008a3578, 0x18}, 0x77c4220)
	/go/src/github.com/milvus-io/milvus/internal/mq/msgstream/mq_factory.go:16 +0x14b fp=0xc00083d9a0 sp=0xc00083d888 pc=0x3dc288b
github.com/milvus-io/milvus/internal/util/dependency.(*DefaultFactory).initMQ(0xc000c28000, 0x1, 0x77c4220)
	/go/src/github.com/milvus-io/milvus/internal/util/dependency/factory.go:92 +0x405 fp=0xc00083daa0 sp=0xc00083d9a0 pc=0x3dc2ee5
github.com/milvus-io/milvus/internal/util/dependency.(*DefaultFactory).Init(0xc000c28000, 0x57da678?)
	/go/src/github.com/milvus-io/milvus/internal/util/dependency/factory.go:78 +0x7c fp=0xc00083dad0 sp=0xc00083daa0 pc=0x3dc2a9c
github.com/milvus-io/milvus/internal/datacoord.(*Server).Init(0xc001a1c000)
	/go/src/github.com/milvus-io/milvus/internal/datacoord/server.go:308 +0x3b fp=0xc00083db08 sp=0xc00083dad0 pc=0x3e9825b
github.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).init(0xc00173ca80)
	/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:129 +0x76f fp=0xc00083de60 sp=0xc00083db08 pc=0x3ece7cf
github.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).Run(0x4d94ec0?)
	/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:252 +0x25 fp=0xc00083dea0 sp=0xc00083de60 pc=0x3ecffa5
github.com/milvus-io/milvus/cmd/components.(*DataCoord).Run(0xc000280360?)
	/go/src/github.com/milvus-io/milvus/cmd/components/data_coord.go:50 +0x2f fp=0xc00083df70 sp=0xc00083dea0 pc=0x474432f
github.com/milvus-io/milvus/cmd/roles.runComponent[...].func1()
	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:110 +0xd9 fp=0xc00083dfe0 sp=0xc00083df70 pc=0x474b019
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00083dfe8 sp=0xc00083dfe0 pc=0x1b4dbe1
created by github.com/milvus-io/milvus/cmd/roles.runComponent[...]
	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:102 +0x158
```

**Comment by zhuwenxing** [comment]
failed job:https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/11098/pipeline
log:
[artifacts-standalone-pod-kill-11098-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/14093486/artifacts-standalone-pod-kill-11098-server-logs.tar.gz)

**Comment by xiaofan-luan** [comment]
@smellthemoon 

you might need to clean the lock when the process is up?

**Comment by zhuwenxing** [comment]
it was still reproduced.
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/12870/pipeline/266
log:
[artifacts-standalone-pod-kill-12870-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/14798696/artifacts-standalone-pod-kill-12870-server-logs.tar.gz)

This issue will be set as critical because it requires three restarts to restore the service, which will significantly impact the disaster recovery time
