### ISSUE TITLE
[Bug]: After milvus recovers from querynode pod kill chaos, search still encounters an error with message unrecoverable error.

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#30366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20240129-74cfba02
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2024-01-30T04:27:28.072Z] [2024-01-30 04:27:22 - DEBUG - ci_test]: (api_response) : (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 447372025464356865, success count: 2000, err count: 0)  (api_request.py:37)

[2024-01-30T04:27:28.072Z] [2024-01-30 04:27:22 - INFO - ci_test]: [test][2024-01-30T04:27:21Z] [0.67870825s] Hello_Milvus insert -> (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 447372025464356865, success count: 2000, err count: 0) (wrapper.py:30)

[2024-01-30T04:27:28.072Z] [2024-01-30 04:27:22 - INFO - ci_test]: assert insert: 0.6788902282714844 (test_data_persistence.py:45)

[2024-01-30T04:27:28.072Z] [2024-01-30 04:27:22 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-01-30T04:27:28.072Z] [2024-01-30 04:27:26 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-01-30T04:27:28.072Z] [2024-01-30 04:27:26 - INFO - ci_test]: [test][2024-01-30T04:27:22Z] [3.52285530s] Hello_Milvus flush -> None (wrapper.py:30)

[2024-01-30T04:27:28.072Z] [2024-01-30 04:27:26 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-01-30T04:27:28.072Z] [2024-01-30 04:27:26 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-01-30T04:27:28.072Z] [2024-01-30 04:27:26 - INFO - ci_test]: [test][2024-01-30T04:27:26Z] [0.50767582s] Hello_Milvus flush -> None (wrapper.py:30)

[2024-01-30T04:27:28.072Z] [2024-01-30 04:27:26 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-01-30T04:27:28.072Z] [2024-01-30 04:27:27 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-01-30T04:27:28.072Z] [2024-01-30 04:27:27 - INFO - ci_test]: [test][2024-01-30T04:27:26Z] [0.50810452s] Hello_Milvus flush -> None (wrapper.py:30)

[2024-01-30T04:27:28.072Z] [2024-01-30 04:27:27 - INFO - ci_test]: assert flush: 4.032254219055176, entities: 6000 (test_data_persistence.py:55)

[2024-01-30T04:27:28.072Z] [2024-01-30 04:27:27 - INFO - ci_test]: index info: [{'collection': 'Hello_Milvus', 'field': 'float_vector', 'index_name': 'test_F8Xg2BnI', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}, {'collection': 'Hello_Milvus', 'field': 'varchar', 'index_name': 'test_IOKtYLJC', 'index_param': {}}] (test_data_persistence.py:74)

[2024-01-30T04:27:28.072Z] [2024-01-30 04:27:27 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 180], kwargs: {} (api_request.py:62)

[2024-01-30T04:27:28.072Z] [2024-01-30 04:27:27 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-01-30T04:27:28.072Z] [2024-01-30 04:27:27 - INFO - ci_test]: [test][2024-01-30T04:27:27Z] [0.03496802s] Hello_Milvus load -> None (wrapper.py:30)

[2024-01-30T04:27:28.073Z] [2024-01-30 04:27:27 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.09758767219845287, 0.04658460580209793, 0.13032465949691033, 0.030826891522197107, 0.06842785940673284, 0.09629688492801983, 0.014563481670307243, 0.031327533221601644, 0.13656172525760654, 0.13539536984331638, 0.0047004835215813424, 0.03525327794951619, 0.02139315642644164, 0.07911311527882116......, kwargs: {} (api_request.py:62)

[2024-01-30T04:27:28.073Z] [2024-01-30 04:27:27 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=65535, message=unrecoverable error)>, <Time:{'RPC start': '2024-01-30 04:27:27.180483', 'RPC error': '2024-01-30 04:27:27.386116'}> (decorators.py:134)

[2024-01-30T04:27:28.073Z] [2024-01-30 04:27:27 - ERROR - ci_test]: Traceback (most recent call last):

[2024-01-30T04:27:28.073Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2024-01-30T04:27:28.073Z]     res = func(*args, **_kwargs)

[2024-01-30T04:27:28.073Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2024-01-30T04:27:28.073Z]     return func(*arg, **kwargs)

[2024-01-30T04:27:28.073Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 792, in search

[2024-01-30T04:27:28.073Z]     resp = conn.search(

[2024-01-30T04:27:28.073Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 135, in handler

[2024-01-30T04:27:28.073Z]     raise e from e

[2024-01-30T04:27:28.073Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 131, in handler

[2024-01-30T04:27:28.073Z]     return func(*args, **kwargs)

[2024-01-30T04:27:28.073Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 170, in handler

[2024-01-30T04:27:28.073Z]     return func(self, *args, **kwargs)

[2024-01-30T04:27:28.073Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 110, in handler

[2024-01-30T04:27:28.073Z]     raise e from e

[2024-01-30T04:27:28.073Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 74, in handler

[2024-01-30T04:27:28.073Z]     return func(*args, **kwargs)

[2024-01-30T04:27:28.073Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 786, in search

[2024-01-30T04:27:28.073Z]     return self._execute_search(request, timeout, round_decimal=round_decimal, **kwargs)

[2024-01-30T04:27:28.073Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 728, in _execute_search

[2024-01-30T04:27:28.073Z]     raise e from e

[2024-01-30T04:27:28.073Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 721, in _execute_search

[2024-01-30T04:27:28.073Z]     check_status(response.status)

[2024-01-30T04:27:28.073Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/utils.py", line 58, in check_status

[2024-01-30T04:27:28.073Z]     raise MilvusException(status.code, status.reason, status.error_code)

[2024-01-30T04:27:28.073Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=unrecoverable error)>

[2024-01-30T04:27:28.073Z]  (api_request.py:45)

[2024-01-30T04:27:28.073Z] [2024-01-30 04:27:27 - ERROR - ci_test]: (api_response) : <MilvusException: (code=65535, message=unrecoverable error)> (api_request.py:46)
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/11099/pipeline
log:
[artifacts-querynode-pod-kill-11099-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/14093907/artifacts-querynode-pod-kill-11099-server-logs.tar.gz)

cluster: 4am
namespace: chaos-testing
release name: querynode-pod-kill-11099

collection name: Hello_Milvus in prod database

**Comment by zhuwenxing** [comment]
It reproduced stably
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/11132/pipeline

**Comment by ThreadDao** [comment]
@aoiasd 
It reproduced stably
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/11143/pipeline
image: master-20240130-fda6f8d0

**Comment by zhuwenxing** [comment]
it keeps reproducing

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/11715/pipeline
image tag: master-20240219-43e8cd53-amd64

**Comment by zhuwenxing** [comment]
also reproduced in querynode pod failure chaos test

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-cron/detail/chaos-test-kafka-cron/11653/pipeline

image tag: master-20240220-e5a16050

**Comment by xiaofan-luan** [comment]
The recoverable error could be throwed from grpc client when node session is removed

**Comment by xiaofan-luan** [comment]
This might be due to the retry mistake.  we should not return unrecoverable error becasue checkNoteSessionExist is recoverable.

We should name a new error -> NoRetryError 
Working on this

<img width="1071" alt="image" src="https://github.com/milvus-io/milvus/assets/83447078/b3650248-1a18-44f9-ad09-46774e6e46d3">
