### ISSUE TITLE
[Bug]: Search failed: node offline[node=17] after Milvus recover from querynode pod kill chaos 

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#30528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20240204-a587450e-amd64
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):  pulsar  
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

search failed:
```
[2024-02-04T18:02:31.101Z] [2024-02-04 18:01:52 - INFO - ci_test]: index info: [{'collection': 'Checker__QfA2uJnJ', 'field': 'float_vector', 'index_name': 'vec_index', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}] (test_all_collections_after_chaos.py:87)

[2024-02-04T18:02:31.101Z] [2024-02-04 18:01:52 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 180], kwargs: {} (api_request.py:62)

[2024-02-04T18:02:31.101Z] [2024-02-04 18:01:52 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-02-04T18:02:31.101Z] [2024-02-04 18:01:52 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.13107314474268575, 0.0610977050344251, 0.11932757755653745, 0.03118279217422002, 0.12074819626319182, 0.0544163316163824, 0.13112102836038958, 0.05166265278614383, 0.08218892961817183, 0.13924638972540815, 0.09658569376047704, 0.044422780484414025, 0.047904514431127386, 0.04397978539859998, 0.0......, kwargs: {} (api_request.py:62)

[2024-02-04T18:02:31.101Z] [2024-02-04 18:01:52 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=503, message=failed to search: node offline[node=17]: channel not available[channel=by-dev-rootcoord-dml_9_447497576520952577v0])>, <Time:{'RPC start': '2024-02-04 18:01:52.175206', 'RPC error': '2024-02-04 18:01:52.179666'}> (decorators.py:134)

[2024-02-04T18:02:31.101Z] [2024-02-04 18:01:52 - ERROR - ci_test]: Traceback (most recent call last):

[2024-02-04T18:02:31.101Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2024-02-04T18:02:31.101Z]     res = func(*args, **_kwargs)

[2024-02-04T18:02:31.101Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2024-02-04T18:02:31.101Z]     return func(*arg, **kwargs)

[2024-02-04T18:02:31.101Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 792, in search

[2024-02-04T18:02:31.101Z]     resp = conn.search(

[2024-02-04T18:02:31.101Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 135, in handler

[2024-02-04T18:02:31.101Z]     raise e from e

[2024-02-04T18:02:31.101Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 131, in handler

[2024-02-04T18:02:31.101Z]     return func(*args, **kwargs)

[2024-02-04T18:02:31.101Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 170, in handler

[2024-02-04T18:02:31.101Z]     return func(self, *args, **kwargs)

[2024-02-04T18:02:31.101Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 110, in handler

[2024-02-04T18:02:31.101Z]     raise e from e

[2024-02-04T18:02:31.101Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 74, in handler

[2024-02-04T18:02:31.101Z]     return func(*args, **kwargs)

[2024-02-04T18:02:31.101Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 786, in search

[2024-02-04T18:02:31.101Z]     return self._execute_search(request, timeout, round_decimal=round_decimal, **kwargs)

[2024-02-04T18:02:31.101Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 728, in _execute_search

[2024-02-04T18:02:31.101Z]     raise e from e

[2024-02-04T18:02:31.101Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 721, in _execute_search

[2024-02-04T18:02:31.101Z]     check_status(response.status)

[2024-02-04T18:02:31.101Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/utils.py", line 58, in check_status

[2024-02-04T18:02:31.101Z]     raise MilvusException(status.code, status.reason, status.error_code)

[2024-02-04T18:02:31.101Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=503, message=failed to search: node offline[node=17]: channel not available[channel=by-dev-rootcoord-dml_9_447497576520952577v0])>

[2024-02-04T18:02:31.101Z]  (api_request.py:45)
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/11263/pipeline/291

log:
[artifacts-querynode-pod-kill-11263-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/14161699/artifacts-querynode-pod-kill-11263-server-logs.tar.gz)

cluster: 4am
namespace: chaos-testing
release name: querynode-pod-kill-11263

pods after chaos:
```
[2024-02-04T18:00:35.891Z] querynode-pod-kill-11263-etcd-0                                  1/1     Running            0                 33m     10.104.17.115   4am-node23   <none>           <none>

[2024-02-04T18:00:35.891Z] querynode-pod-kill-11263-etcd-1                                  1/1     Running            0                 33m     10.104.24.183   4am-node29   <none>           <none>

[2024-02-04T18:00:35.891Z] querynode-pod-kill-11263-etcd-2                                  1/1     Running            0                 33m     10.104.26.218   4am-node32   <none>           <none>

[2024-02-04T18:00:35.891Z] querynode-pod-kill-11263-milvus-datacoord-64cbf86594-28dfc       1/1     Running            0                 33m     10.104.16.16    4am-node21   <none>           <none>

[2024-02-04T18:00:35.891Z] querynode-pod-kill-11263-milvus-datanode-7fc77bd5f7-5d7nj        1/1     Running            0                 33m     10.104.34.124   4am-node37   <none>           <none>

[2024-02-04T18:00:35.891Z] querynode-pod-kill-11263-milvus-datanode-7fc77bd5f7-fnvx4        1/1     Running            0                 33m     10.104.16.17    4am-node21   <none>           <none>

[2024-02-04T18:00:35.891Z] querynode-pod-kill-11263-milvus-indexcoord-5fc744d577-fx9z7      1/1     Running            0                 33m     10.104.34.122   4am-node37   <none>           <none>

[2024-02-04T18:00:35.892Z] querynode-pod-kill-11263-milvus-indexnode-86859bf8b4-9krbl       1/1     Running            0                 33m     10.104.20.159   4am-node22   <none>           <none>

[2024-02-04T18:00:35.892Z] querynode-pod-kill-11263-milvus-indexnode-86859bf8b4-qlnkb       1/1     Running            0                 33m     10.104.28.109   4am-node33   <none>           <none>

[2024-02-04T18:00:35.892Z] querynode-pod-kill-11263-milvus-indexnode-86859bf8b4-znrk6       1/1     Running            0                 33m     10.104.12.149   4am-node17   <none>           <none>

[2024-02-04T18:00:35.892Z] querynode-pod-kill-11263-milvus-proxy-6b6fdbb965-pwnm4           1/1     Running            0                 33m     10.104.34.120   4am-node37   <none>           <none>

[2024-02-04T18:00:35.892Z] querynode-pod-kill-11263-milvus-querycoord-c75445f94-wvkcq       1/1     Running            0                 33m     10.104.34.118   4am-node37   <none>           <none>

[2024-02-04T18:00:35.892Z] querynode-pod-kill-11263-milvus-querynode-6594c4d8d-5xgml        1/1     Running            0                 12m     10.104.25.73    4am-node30   <none>           <none>

[2024-02-04T18:00:35.892Z] querynode-pod-kill-11263-milvus-querynode-6594c4d8d-68dlc        1/1     Running            0                 12m     10.104.21.240   4am-node24   <none>           <none>

[2024-02-04T18:00:35.892Z] querynode-pod-kill-11263-milvus-querynode-6594c4d8d-6v5c9        1/1     Running            0                 12m     10.104.12.171   4am-node17   <none>           <none>

[2024-02-04T18:00:35.892Z] querynode-pod-kill-11263-milvus-rootcoord-7c5b784f8-c2rhj        1/1     Running            0                 33m     10.104.12.150   4am-node17   <none>           <none>

[2024-02-04T18:00:35.892Z] querynode-pod-kill-11263-minio-0                                 1/1     Running            0                 33m     10.104.26.210   4am-node32   <none>           <none>

[2024-02-04T18:00:35.892Z] querynode-pod-kill-11263-minio-1                                 1/1     Running            0                 33m     10.104.24.180   4am-node29   <none>           <none>

[2024-02-04T18:00:35.892Z] querynode-pod-kill-11263-minio-2                                 1/1     Running            0                 33m     10.104.17.116   4am-node23   <none>           <none>

[2024-02-04T18:00:35.892Z] querynode-pod-kill-11263-minio-3                                 1/1     Running            0                 33m     10.104.34.128   4am-node37   <none>           <none>

[2024-02-04T18:00:35.892Z] querynode-pod-kill-11263-pulsar-bookie-0                         1/1     Running            0                 33m     10.104.26.217   4am-node32   <none>           <none>

[2024-02-04T18:00:35.892Z] querynode-pod-kill-11263-pulsar-bookie-1                         1/1     Running            0                 33m     10.104.24.185   4am-node29   <none>           <none>

[2024-02-04T18:00:35.892Z] querynode-pod-kill-11263-pulsar-bookie-init-hjdln                0/1     Completed          0                 33m     10.104.5.158    4am-node12   <none>           <none>

[2024-02-04T18:00:35.892Z] querynode-pod-kill-11263-pulsar-broker-0                         1/1     Running            0                 33m     10.104.5.155    4am-node12   <none>           <none>

[2024-02-04T18:00:35.892Z] querynode-pod-kill-11263-pulsar-proxy-0                          1/1     Running            0                 33m     10.104.6.15     4am-node13   <none>           <none>

[2024-02-04T18:00:35.892Z] querynode-pod-kill-11263-pulsar-pulsar-init-24hkt                0/1     Completed          0                 33m     10.104.5.156    4am-node12   <none>           <none>

[2024-02-04T18:00:35.892Z] querynode-pod-kill-11263-pulsar-recovery-0                       1/1     Running            0                 33m     10.104.5.157    4am-node12   <none>           <none>

[2024-02-04T18:00:35.892Z] querynode-pod-kill-11263-pulsar-zookeeper-0                      1/1     Running            0                 33m     10.104.26.216   4am-node32   <none>           <none>
```

**Comment by ThreadDao** [comment]
I don't know if this is a problem with #30298 or #28815. node offline or segment issue ?

**Comment by congqixia** [comment]
Could be related to patch #31040
Could you please help verify?
/assign @zhuwenxing

**Comment by yanliang567** [comment]
/assign @zhuwenxing 
please help to check if it reproduces recenlty
