### ISSUE TITLE
[Bug]: Search failed: service unavailable: all available nodes are unreachable after reinstall milvus

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#30531]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20240204-da50fbfb
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2024-02-04T10:10:23.990Z] [2024-02-04 10:08:38 - DEBUG - ci_test]: (api_request)  : [Collection] args: ['Checker__EovMaHcM', {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}, {'name': 'varchar', 'description': '', 'type': <DataType......, kwargs: {'consistency_level': 'Strong'} (api_request.py:62)

[2024-02-04T10:10:23.990Z] [2024-02-04 10:08:38 - DEBUG - ci_test]: (api_response) : <Collection>:

[2024-02-04T10:10:23.990Z] -------------

[2024-02-04T10:10:23.990Z] <name>: Checker__EovMaHcM

[2024-02-04T10:10:23.990Z] <description>: 

[2024-02-04T10:10:23.990Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}......  (api_request.py:37)

[2024-02-04T10:10:23.990Z] [2024-02-04 10:08:38 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-02-04T10:10:23.990Z] [2024-02-04 10:08:39 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-02-04T10:10:23.990Z] [2024-02-04 10:08:39 - DEBUG - ci_test]: (api_request)  : [Collection.compact] args: [180], kwargs: {} (api_request.py:62)

[2024-02-04T10:10:23.990Z] [2024-02-04 10:08:40 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-02-04T10:10:23.990Z] [2024-02-04 10:08:56 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-02-04T10:10:23.990Z] [2024-02-04 10:08:56 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-02-04T10:10:23.990Z] [2024-02-04 10:08:56 - INFO - ci_test]: assert create collection: 0.006284475326538086, init_entities: 50523 (test_all_collections_after_chaos.py:49)

[2024-02-04T10:10:23.990Z] [2024-02-04 10:08:56 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [[[-3000, -2999, -2998, -2997, -2996, -2995, -2994, -2993, -2992, -2991, -2990, -2989, -2988, -2987, -2986, -2985, -2984, -2983, -2982, -2981, -2980, -2979, -2978, -2977, -2976, -2975, -2974, -2973, -2972, -2971, -2970, -2969, -2968, -2967, -2966, -2965, -2964, -2963, -2962, -2961, -2960, -2959, -29......, kwargs: {'timeout': 180} (api_request.py:62)

[2024-02-04T10:10:23.990Z] [2024-02-04 10:08:57 - DEBUG - ci_test]: (api_response) : (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 447490644242071555, success count: 2000, err count: 0)  (api_request.py:37)

[2024-02-04T10:10:23.990Z] [2024-02-04 10:08:57 - INFO - ci_test]: assert insert: 0.2538583278656006 (test_all_collections_after_chaos.py:61)

[2024-02-04T10:10:23.990Z] [2024-02-04 10:08:57 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-02-04T10:10:23.990Z] [2024-02-04 10:09:00 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-02-04T10:10:23.990Z] [2024-02-04 10:09:00 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-02-04T10:10:23.990Z] [2024-02-04 10:09:01 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-02-04T10:10:23.990Z] [2024-02-04 10:09:01 - INFO - ci_test]: assert flush: 3.589613199234009, entities: 52523 (test_all_collections_after_chaos.py:71)

[2024-02-04T10:10:23.990Z] [2024-02-04 10:09:01 - INFO - ci_test]: index info: [{'collection': 'Checker__EovMaHcM', 'field': 'float_vector', 'index_name': 'vec_index', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}] (test_all_collections_after_chaos.py:87)

[2024-02-04T10:10:23.990Z] [2024-02-04 10:09:01 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 180], kwargs: {} (api_request.py:62)

[2024-02-04T10:10:23.990Z] [2024-02-04 10:09:01 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-02-04T10:10:23.990Z] [2024-02-04 10:09:01 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.05161609853660582, 0.03331089099216918, 0.010903727218331181, 0.02510984099263361, 0.025275842486359303, 0.10414511960750036, 0.07915405038204157, 0.0697919719084245, 0.048593571305926314, 0.09278224596897199, 0.05003359547491915, 0.0025533890186690525, 0.08889027301655746, 0.15177577745762513,......, kwargs: {} (api_request.py:62)

[2024-02-04T10:10:23.990Z] [2024-02-04 10:09:02 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=2, message=failed to search: service unavailable: all available nodes are unreachable)>, <Time:{'RPC start': '2024-02-04 10:09:01.732288', 'RPC error': '2024-02-04 10:09:02.337679'}> (decorators.py:134)
```
- failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_cron/detail/deploy_test_cron/1887/pipeline/406
- server logs:
[artifacts-pulsar-cluster-reinstall-1887-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/14162240/artifacts-pulsar-cluster-reinstall-1887-server-logs.tar.gz)

### Milvus Log

- pods: 4am chaos-testing namespace
```
[2024-02-04T10:01:21.848Z] pulsar-cluster-reinstall-1887-bookie-0                            1/1     Running            0                  3m32s   10.104.25.34    4am-node30   <none>           <none>

[2024-02-04T10:01:21.848Z] pulsar-cluster-reinstall-1887-bookie-1                            1/1     Running            0                  3m32s   10.104.23.217   4am-node27   <none>           <none>

[2024-02-04T10:01:21.848Z] pulsar-cluster-reinstall-1887-broker-0                            1/1     Running            0                  3m32s   10.104.6.102    4am-node13   <none>           <none>

[2024-02-04T10:01:21.848Z] pulsar-cluster-reinstall-1887-etcd-0                              1/1     Running            0                  3m36s   10.104.23.215   4am-node27   <none>           <none>

[2024-02-04T10:01:21.848Z] pulsar-cluster-reinstall-1887-etcd-1                              1/1     Running            0                  3m36s   10.104.25.33    4am-node30   <none>           <none>

[2024-02-04T10:01:21.848Z] pulsar-cluster-reinstall-1887-etcd-2                              1/1     Running            0                  3m36s   10.104.16.49    4am-node21   <none>           <none>

[2024-02-04T10:01:21.848Z] pulsar-cluster-reinstall-1887-milvus-datacoord-9bf87dd6f-zhgxc    1/1     Running            0                  3m35s   10.104.6.92     4am-node13   <none>           <none>

[2024-02-04T10:01:21.848Z] pulsar-cluster-reinstall-1887-milvus-datanode-b5b994564-fm4l9     1/1     Running            0                  3m35s   10.104.18.42    4am-node25   <none>           <none>

[2024-02-04T10:01:21.848Z] pulsar-cluster-reinstall-1887-milvus-datanode-b5b994564-q5pwd     1/1     Running            0                  3m35s   10.104.6.93     4am-node13   <none>           <none>

[2024-02-04T10:01:21.848Z] pulsar-cluster-reinstall-1887-milvus-indexcoord-86bd9f7c46lxw5h   1/1     Running            0                  3m35s   10.104.6.95     4am-node13   <none>           <none>

[2024-02-04T10:01:21.848Z] pulsar-cluster-reinstall-1887-milvus-indexnode-5bc8cbb87c-4v76c   1/1     Running            0                  3m35s   10.104.23.216   4am-node27   <none>           <none>

[2024-02-04T10:01:21.848Z] pulsar-cluster-reinstall-1887-milvus-indexnode-5bc8cbb87c-q56q8   1/1     Running            0                  3m35s   10.104.18.43    4am-node25   <none>           <none>

[2024-02-04T10:01:21.848Z] pulsar-cluster-reinstall-1887-milvus-indexnode-5bc8cbb87c-rc58s   1/1     Running            0                  3m35s   10.104.6.96     4am-node13   <none>           <none>

[2024-02-04T10:01:21.848Z] pulsar-cluster-reinstall-1887-milvus-proxy-7cd964b558-vz5vj       1/1     Running            0                  3m35s   10.104.6.97     4am-node13   <none>           <none>

[2024-02-04T10:01:21.848Z] pulsar-cluster-reinstall-1887-milvus-querycoord-6dc7cf78c7f2b2p   1/1     Running            0                  3m35s   10.104.6.98     4am-node13   <none>           <none>

[2024-02-04T10:01:21.848Z] pulsar-cluster-reinstall-1887-milvus-querynode-6b9c5d9995-nfn9f   1/1     Running            0                  3m34s   10.104.23.218   4am-node27   <none>           <none>

[2024-02-04T10:01:21.848Z] pulsar-cluster-reinstall-1887-milvus-querynode-6b9c5d9995-tlm5n   1/1     Running            0                  3m34s   10.104.6.101    4am-node13   <none>           <none>

[2024-02-04T10:01:21.848Z] pulsar-cluster-reinstall-1887-milvus-querynode-6b9c5d9995-wv7nf   1/1     Running            0                  3m35s   10.104.18.44    4am-node25   <none>           <none>

[2024-02-04T10:01:21.848Z] pulsar-cluster-reinstall-1887-milvus-rootcoord-78cf5cd76f-rcz5q   1/1     Running            0                  3m34s   10.104.6.99     4am-node13   <none>           <none>

[2024-02-04T10:01:21.848Z] pulsar-cluster-reinstall-1887-minio-0                             1/1     Running            0                  3m32s   10.104.23.219   4am-node27   <none>           <none>

[2024-02-04T10:01:21.848Z] pulsar-cluster-reinstall-1887-minio-1                             1/1     Running            0                  3m32s   10.104.25.35    4am-node30   <none>           <none>

[2024-02-04T10:01:21.848Z] pulsar-cluster-reinstall-1887-minio-2                             1/1     Running            0                  3m32s   10.104.34.179   4am-node37   <none>           <none>

[2024-02-04T10:01:21.848Z] pulsar-cluster-reinstall-1887-minio-3                             1/1     Running            0                  3m32s   10.104.16.50    4am-node21   <none>           <none>

[2024-02-04T10:01:21.848Z] pulsar-cluster-reinstall-1887-proxy-0                             1/1     Running            0                  3m32s   10.104.6.103    4am-node13   <none>           <none>

[2024-02-04T10:01:21.848Z] pulsar-cluster-reinstall-1887-recovery-0                          1/1     Running            0                  3m32s   10.104.6.104    4am-node13   <none>           <none>

[2024-02-04T10:01:21.849Z] pulsar-cluster-reinstall-1887-zookeeper-0                         1/1     Running            0                  3m32s   10.104.25.36    4am-node30   <none>           <none>
```

**Comment by zhuwenxing** [comment]
verification is blocked by https://github.com/milvus-io/milvus/issues/30137
after cluster reinstallation, all test cases failed due to flush timeout. so can not reach to search for verification

**Comment by zhuwenxing** [comment]
it reproduced after upgrading from v2.3.4 to master-20240312-de2c95d0
```

[2024-03-12T10:49:50.588Z] <name>: Checker__ztLofPTm

[2024-03-12T10:49:50.588Z] <description>: 

[2024-03-12T10:49:50.588Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}......  (api_request.py:37)

[2024-03-12T10:49:50.588Z] [2024-03-12 10:47:43 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-03-12T10:49:50.588Z] [2024-03-12 10:47:44 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-03-12T10:49:50.588Z] [2024-03-12 10:47:44 - DEBUG - ci_test]: (api_request)  : [Collection.compact] args: [180], kwargs: {} (api_request.py:62)

[2024-03-12T10:49:50.588Z] [2024-03-12 10:47:44 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-03-12T10:49:50.588Z] [2024-03-12 10:48:02 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-03-12T10:49:50.588Z] [2024-03-12 10:48:03 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-03-12T10:49:50.588Z] [2024-03-12 10:48:03 - INFO - ci_test]: assert create collection: 0.013230085372924805, init_entities: 91107 (test_all_collections_after_chaos.py:49)

[2024-03-12T10:49:50.588Z] [2024-03-12 10:48:03 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [[[-3000, -2999, -2998, -2997, -2996, -2995, -2994, -2993, -2992, -2991, -2990, -2989, -2988, -2987, -2986, -2985, -2984, -2983, -2982, -2981, -2980, -2979, -2978, -2977, -2976, -2975, -2974, -2973, -2972, -2971, -2970, -2969, -2968, -2967, -2966, -2965, -2964, -2963, -2962, -2961, -2960, -2959, -29......, kwargs: {'timeout': 180} (api_request.py:62)

[2024-03-12T10:49:50.588Z] [2024-03-12 10:48:03 - DEBUG - ci_test]: (api_response) : (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 448329281324187652, success count: 2000, err count: 0)  (api_request.py:37)

[2024-03-12T10:49:50.588Z] [2024-03-12 10:48:03 - INFO - ci_test]: assert insert: 0.32892751693725586 (test_all_collections_after_chaos.py:57)

[2024-03-12T10:49:50.588Z] [2024-03-12 10:48:03 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-03-12T10:49:50.588Z] [2024-03-12 10:48:07 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-03-12T10:49:50.588Z] [2024-03-12 10:48:07 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-03-12T10:49:50.588Z] [2024-03-12 10:48:07 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-03-12T10:49:50.588Z] [2024-03-12 10:48:08 - INFO - ci_test]: assert flush: 3.52858829498291, entities: 93107 (test_all_collections_after_chaos.py:67)

[2024-03-12T10:49:50.588Z] [2024-03-12 10:48:08 - INFO - ci_test]: index info: [{'collection': 'Checker__ztLofPTm', 'field': 'float_vector', 'index_name': 'vec_index', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}] (test_all_collections_after_chaos.py:71)

[2024-03-12T10:49:50.588Z] [2024-03-12 10:48:08 - INFO - ci_test]: index info: [{'collection': 'Checker__ztLofPTm', 'field': 'float_vector', 'index_name': 'vec_index', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}] (test_all_collections_after_chaos.py:86)

[2024-03-12T10:49:50.588Z] [2024-03-12 10:48:08 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 180], kwargs: {} (api_request.py:62)

[2024-03-12T10:49:50.588Z] [2024-03-12 10:48:08 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-03-12T10:49:50.588Z] [2024-03-12 10:48:08 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.105781944477592, 0.09065774841054378, 0.1412208854798972, 0.12997166092070284, 0.04127947202689886, 0.0271161156947469, 0.0889605684684922, 0.04121507454084453, 0.06424676127198203, 0.08698077284639062, 0.052265846170549815, 0.09169561393259693, 0.08028247474743777, 0.01107349872941966, 0.01268......, kwargs: {} (api_request.py:62)

[2024-03-12T10:49:50.588Z] [2024-03-12 10:48:09 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=2, message=failed to search: service unavailable: all available nodes are unreachable)>, <Time:{'RPC start': '2024-03-12 10:48:08.402265', 'RPC error': '2024-03-12 10:48:09.008377'}> (decorators.py:134)

[2024-03-12T10:49:50.588Z] [2024-03-12 10:48:09 - ERROR - ci_test]: Traceback (most recent call last):

[2024-03-12T10:49:50.588Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2024-03-12T10:49:50.588Z]     res = func(*args, **_kwargs)

[2024-03-12T10:49:50.588Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2024-03-12T10:49:50.588Z]     return func(*arg, **kwargs)

[2024-03-12T10:49:50.588Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 792, in search

[2024-03-12T10:49:50.588Z]     resp = conn.search(

[2024-03-12T10:49:50.588Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 135, in handler

[2024-03-12T10:49:50.588Z]     raise e from e

[2024-03-12T10:49:50.588Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 131, in handler

[2024-03-12T10:49:50.588Z]     return func(*args, **kwargs)

[2024-03-12T10:49:50.588Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 170, in handler

[2024-03-12T10:49:50.588Z]     return func(self, *args, **kwargs)

[2024-03-12T10:49:50.588Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 110, in handler

[2024-03-12T10:49:50.588Z]     raise e from e

[2024-03-12T10:49:50.588Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 74, in handler

[2024-03-12T10:49:50.588Z]     return func(*args, **kwargs)

[2024-03-12T10:49:50.588Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 794, in search

[2024-03-12T10:49:50.588Z]     return self._execute_search(request, timeout, round_decimal=round_decimal, **kwargs)

[2024-03-12T10:49:50.588Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 735, in _execute_search

[2024-03-12T10:49:50.588Z]     raise e from e

[2024-03-12T10:49:50.588Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 728, in _execute_search

[2024-03-12T10:49:50.588Z]     check_status(response.status)

[2024-03-12T10:49:50.589Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/utils.py", line 60, in check_status

[2024-03-12T10:49:50.589Z]     raise MilvusException(status.code, status.reason, status.error_code)

[2024-03-12T10:49:50.589Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=failed to search: service unavailable: all available nodes are unreachable)>

[2024-03-12T10:49:50.589Z]  (api_request.py:45)
```

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_kafka_cron/detail/deploy_test_kafka_cron/1966/pipeline
log:

[artifacts-kafka-cluster-upgrade-1966-server-second-deployment-logs.tar.gz](https://github.com/milvus-io/milvus/files/14581090/artifacts-kafka-cluster-upgrade-1966-server-second-deployment-logs.tar.gz)

**Comment by weiliu1031** [comment]
please verify this with latest image
