### ISSUE TITLE
[Bug]: [one pod standalone] Flush failed: code=500, message=channel not found when recovered from pod kill

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#30545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20240205-5449e862-amd64
- Deployment mode(standalone or cluster): one-pod standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Client error:
```
[2024-02-05T17:15:00.587Z] [2024-02-05 17:05:59 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-02-05T17:15:00.587Z] [2024-02-05 17:05:59 - DEBUG - ci_test]: (api_request)  : [Connections.has_connection] args: ['default'], kwargs: {} (api_request.py:62)

[2024-02-05T17:15:00.587Z] [2024-02-05 17:05:59 - DEBUG - ci_test]: (api_response) : True  (api_request.py:37)

[2024-02-05T17:15:00.587Z] [2024-02-05 17:05:59 - DEBUG - ci_test]: (api_request)  : [Collection] args: ['DeleteChecker__ueYDbfok', {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}, {'name': 'varchar', 'description': '', 'type': <Da......, kwargs: {'consistency_level': 'Strong'} (api_request.py:62)

[2024-02-05T17:15:00.587Z] [2024-02-05 17:05:59 - DEBUG - ci_test]: (api_response) : <Collection>:

[2024-02-05T17:15:00.587Z] -------------

[2024-02-05T17:15:00.587Z] <name>: DeleteChecker__ueYDbfok

[2024-02-05T17:15:00.587Z] <description>: 

[2024-02-05T17:15:00.587Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT......  (api_request.py:37)

[2024-02-05T17:15:00.588Z] [2024-02-05 17:05:59 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-02-05T17:15:00.588Z] [2024-02-05 17:08:59 - ERROR - pymilvus.decorators]: RPC error: [flush], <MilvusException: (code=500, message=channel not found[channel=by-dev-rootcoord-dml_11_447519320421511456v0])>, <Time:{'RPC start': '2024-02-05 17:05:59.643014', 'RPC error': '2024-02-05 17:08:59.253312'}> (decorators.py:134)
```

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/11284/pipeline/291
server logs:
[artifacts-one-pod-standalone-pod-kill-11284-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/14174095/artifacts-one-pod-standalone-pod-kill-11284-server-logs.tar.gz)

### Milvus Log

- pod before chaos
```
[2024-02-05T16:33:49.541Z] one-pod-standalone-pod-kill-11284-milvus-standalone-7d765d4gj8b   1/1     Running                      0                  109s    10.104.18.158   4am-node25   <none>           <none>
```
- pod after chaos
```
[2024-02-05T17:02:33.804Z] one-pod-standalone-pod-kill-11284-milvus-standalone-7d765dchc7l   1/1     Running                      0                 12m     10.104.18.211   4am-node25   <none>           <none>
```

**Comment by xiaofan-luan** [comment]
@weiliu1031 could you help on investigating this

**Comment by weiliu1031** [comment]
1. before the pod kill operation, datanode generate segment `447519320421309843` and then query node load it successfully
2. after the pod kill operation, query node try to load segment `447519320421309843` but failed, and datanode failed to sub channel during recover segment `447519320421309843`, due to the state_log not found for segment `447519320421309843`
![image](https://github.com/milvus-io/milvus/assets/108661493/38ee07ef-93f8-4960-9cc7-1b3e96e2d38b)

more detail about lost state_log is still investigating

**Comment by yanliang567** [comment]
/assign @zhuwenxing 
does this reproduce recently?

**Comment by zhuwenxing** [comment]
still reproduced in `master-20240327-655097f1-amd64`
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/12836/pipeline
log: [artifacts-one-pod-standalone-pod-kill-12836-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/14783250/artifacts-one-pod-standalone-pod-kill-12836-server-logs.tar.gz)

```
[2024-03-27T12:28:16.259Z] <name>: Hello_Milvus

[2024-03-27T12:28:16.259Z] <description>: 

[2024-03-27T12:28:16.259Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}, {'n......  (api_request.py:37)

[2024-03-27T12:28:16.259Z] [2024-03-27 12:25:24 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-03-27T12:28:16.259Z] [2024-03-27 12:28:15 - ERROR - pymilvus.decorators]: RPC error: [flush], <MilvusException: (code=500, message=channel not found[channel=by-dev-rootcoord-dml_2_448669831914986925v0])>, <Time:{'RPC start': '2024-03-27 12:25:24.653400', 'RPC error': '2024-03-27 12:28:15.969010'}> (decorators.py:146)

[2024-03-27T12:28:16.259Z] [2024-03-27 12:28:15 - ERROR - ci_test]: Traceback (most recent call last):

[2024-03-27T12:28:16.259Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2024-03-27T12:28:16.259Z]     res = func(*args, **_kwargs)

[2024-03-27T12:28:16.259Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2024-03-27T12:28:16.259Z]     return func(*arg, **kwargs)

[2024-03-27T12:28:16.259Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 317, in flush

[2024-03-27T12:28:16.259Z]     conn.flush([self.name], timeout=timeout, **kwargs)

[2024-03-27T12:28:16.259Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 147, in handler

[2024-03-27T12:28:16.259Z]     raise e from e

[2024-03-27T12:28:16.259Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 143, in handler

[2024-03-27T12:28:16.259Z]     return func(*args, **kwargs)

[2024-03-27T12:28:16.259Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 182, in handler

[2024-03-27T12:28:16.259Z]     return func(self, *args, **kwargs)

[2024-03-27T12:28:16.259Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 122, in handler

[2024-03-27T12:28:16.259Z]     raise e from e

[2024-03-27T12:28:16.259Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 87, in handler

[2024-03-27T12:28:16.259Z]     return func(*args, **kwargs)

[2024-03-27T12:28:16.259Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 1397, in flush

[2024-03-27T12:28:16.259Z]     check_status(response.status)

[2024-03-27T12:28:16.259Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/utils.py", line 60, in check_status

[2024-03-27T12:28:16.259Z]     raise MilvusException(status.code, status.reason, status.error_code)

[2024-03-27T12:28:16.259Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=500, message=channel not found[channel=by-dev-rootcoord-dml_2_448669831914986925v0])>

[2024-03-27T12:28:16.259Z]  (api_request.py:45)
```




```
[2024-03-27T12:22:33.013Z] [2024-03-27 12:22:32 - ERROR - pymilvus.decorators]: RPC error: [create_collection], <MilvusException: (code=65535, message=etcdserver: mvcc: database space exceeded)>, <Time:{'RPC start': '2024-03-27 12:22:32.814786', 'RPC error': '2024-03-27 12:22:32.818889'}> (decorators.py:146)

[2024-03-27T12:22:33.013Z] [2024-03-27 12:22:32 - ERROR - ci_test]: Traceback (most recent call last):

[2024-03-27T12:22:33.013Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2024-03-27T12:22:33.013Z]     res = func(*args, **_kwargs)

[2024-03-27T12:22:33.013Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2024-03-27T12:22:33.013Z]     return func(*arg, **kwargs)

[2024-03-27T12:22:33.013Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 149, in __init__

[2024-03-27T12:22:33.013Z]     conn.create_collection(self._name, schema, **kwargs)

[2024-03-27T12:22:33.013Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 147, in handler

[2024-03-27T12:22:33.013Z]     raise e from e

[2024-03-27T12:22:33.013Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 143, in handler

[2024-03-27T12:22:33.013Z]     return func(*args, **kwargs)

[2024-03-27T12:22:33.013Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 182, in handler

[2024-03-27T12:22:33.013Z]     return func(self, *args, **kwargs)

[2024-03-27T12:22:33.013Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 122, in handler

[2024-03-27T12:22:33.013Z]     raise e from e

[2024-03-27T12:22:33.013Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 87, in handler

[2024-03-27T12:22:33.013Z]     return func(*args, **kwargs)

[2024-03-27T12:22:33.013Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 304, in create_collection

[2024-03-27T12:22:33.013Z]     check_status(status)

[2024-03-27T12:22:33.013Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/utils.py", line 60, in check_status

[2024-03-27T12:22:33.013Z]     raise MilvusException(status.code, status.reason, status.error_code)

[2024-03-27T12:22:33.013Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=etcdserver: mvcc: database space exceeded)>

[2024-03-27T12:22:33.013Z]  (api_request.py:45)

[2024-03-27T12:22:33.013Z] [2024-03-27 12:22:32 - ERROR - ci_test]: (api_response) : <MilvusException: (code=65535, message=etcdserver: mvcc: database space exceeded)> (api_request.py:46)
```
@LoveEachDay  
with the config, etcd still failed 
```
[2024-03-27T11:41:13.994Z] cluster:

[2024-03-27T11:41:13.994Z]   enabled: false

[2024-03-27T11:41:13.994Z] etcd:

[2024-03-27T11:41:13.994Z]   enabled: false

[2024-03-27T11:41:13.994Z] extraConfigFiles:

[2024-03-27T11:41:13.994Z]   user.yaml: |

[2024-03-27T11:41:13.994Z]     etcd:

[2024-03-27T11:41:13.994Z]       use:

[2024-03-27T11:41:13.994Z]         embed: true

[2024-03-27T11:41:13.994Z]       data:

[2024-03-27T11:41:13.994Z]         dir: /var/lib/milvus/etcd

[2024-03-27T11:41:13.994Z]     common:

[2024-03-27T11:41:13.994Z]       storageType: local

[2024-03-27T11:41:13.994Z] image:

[2024-03-27T11:41:13.994Z]   all:

[2024-03-27T11:41:13.994Z]     repository: harbor.milvus.io/milvus/milvus

[2024-03-27T11:41:13.994Z]     tag: master-20240327-655097f1-amd64

[2024-03-27T11:41:13.994Z] metrics:

[2024-03-27T11:41:13.994Z]   serviceMonitor:

[2024-03-27T11:41:13.994Z]     enabled: true

[2024-03-27T11:41:13.994Z] minio:

[2024-03-27T11:41:13.994Z]   enabled: false

[2024-03-27T11:41:13.994Z]   tls:

[2024-03-27T11:41:13.994Z]     enabled: false

[2024-03-27T11:41:13.994Z] pulsar:

[2024-03-27T11:41:13.994Z]   enabled: false

[2024-03-27T11:41:13.994Z] quotaAndLimits:

[2024-03-27T11:41:13.994Z]   enabled: false

[2024-03-27T11:41:13.994Z] standalone:

[2024-03-27T11:41:13.994Z]   extraEnv:

[2024-03-27T11:41:13.994Z]   - name: ETCD_CONFIG_PATH

[2024-03-27T11:41:13.994Z]     value: /milvus/configs/advanced/etcd.yaml
```

**Comment by XuanYang-cn** [comment]
Same reason reproduced at one-pod chaos
[2024/05/14 17:24:19.905 +00:00] [WARN] [datanode/data_sync_service.go:299] ["failed to load bloom filter files"] [segmentID=449761595059215752] [error="failed to read /tmp/milvus/data/stats_log/449761595059215658/449761595059215659/449761595059215752/100/1: key not found[key=/tmp/milvus/data/stats_log/449761595059215658/449761595059215659/449761595059215752/100/1]"]

**Comment by zhuwenxing** [comment]
@XuanYang-cn 

It can be stably reproduced, please help with it
failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/16112/pipeline

log:
[artifacts-one-pod-standalone-pod-kill-16112-server-logs.tar.gz](https://github.com/user-attachments/files/16229585/artifacts-one-pod-standalone-pod-kill-16112-server-logs.tar.gz)

**Comment by xiaofan-luan** [comment]
/tmp/milvus/data/

why do we put data on tmp?

this won't work for chaos test I guess @zhuwenxing
