### ISSUE TITLE
[Bug]: milvus crash immediately on startup

### ISSUE THREAD

**Issue by moosmootoo** [milvus-io/milvus#30604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
Version:   v2.2.9
Built:     Fri Jun  2 09:38:35 UTC 2023
GitCommit: 9ffcd53b
GoVersion: go version go1.18.3 linux/amd64
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.3.4
- OS(Ubuntu or CentOS): osx 
- CPU/Memory: 
- GPU: 
- Others: https://github.com/milvus-io/milvus/releases/download/v2.2.9/milvus-standalone-docker-compose.yml
```

### Current Behavior

Milvus crashes immediately on startup

### Expected Behavior

Milvus runs and does not crash

### Steps To Reproduce

```markdown
Would like to delete all dbs and data. Where is it? Noting at /var/lib/milvus/data
```

### Milvus Log

2024-02-12 23:16:25 terminate called after throwing an instance of 'milvus::SegcoreError'
2024-02-12 23:16:25 [2024/02/13 07:16:25.464 +00:00] [INFO] [querynode/query_shard_service.go:107] ["Successfully add new query shard"] [collection=447690501475051737] [replica=447690506050469890] [channel=by-dev-rootcoord-dml_12_447690501475051737v0] [delta=1]
2024-02-12 23:16:25   what():  Assert "unsupported" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/InsertRecord.h:222
2024-02-12 23:16:25 
2024-02-12 23:16:25 [2024/02/13 07:16:25.465 +00:00] [INFO] [querynode/watch_dm_channels_task.go:157] ["WatchDmChannels done"] [collectionID=447690501475051737] [vChannels="[by-dev-rootcoord-dml_12_447690501475051737v0]"] [replicaID=447690506050469890]
2024-02-12 23:16:25 SIGABRT: abort
2024-02-12 23:16:25 PC=0x4002c3100b m=10 sigcode=18446744073709551610
2024-02-12 23:16:25 signal arrived during cgo execution
2024-02-12 23:16:25 
2024-02-12 23:16:25 goroutine 1573 [syscall]:
2024-02-12 23:16:25 runtime.cgocall(0x3146110, 0xc002fb6898)
2024-02-12 23:16:25     /usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc002fb6870 sp=0xc002fb6838 pc=0x147e57c
2024-02-12 23:16:25 github.com/milvus-io/milvus/internal/querynode._Cfunc_NewSegment(0x40718d0000, 0x1, 0x63684239dc02273)
2024-02-12 23:16:25     _cgo_gotypes.go:758 +0x4d fp=0xc002fb6898 sp=0xc002fb6870 pc=0x2dd20ed
2024-02-12 23:16:25 github.com/milvus-io/milvus/internal/querynode.newSegment.func2(0x0?, 0x401d099?)

**Comment by congqixia** [comment]
@moosmootoo 
It looks like you used an old version without some data type support say "Array"
The data file shall be under docker-compose folder by default

**Comment by moosmootoo** [comment]
@congqixia, which version supports array?

**Comment by xiaofan-luan** [comment]
> @moosmootoo It looks like you used an old version without some data type support say "Array" The data file shall be under docker-compose folder by default

We would recommend to use 2.3.8

**Comment by yanliang567** [comment]
/assign @moosmootoo 
as comments above
