### ISSUE TITLE
[Bug]: many collection load timeout(180s) after milvus already recover from standalone pod kill/failure chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#30712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20240220-e5a16050
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq/kafka   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```

[2024-02-20T17:19:08.837Z] <name>: Checker__e2cqqf7F

[2024-02-20T17:19:08.837Z] <description>: 

[2024-02-20T17:19:08.837Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}......  (api_request.py:37)

[2024-02-20T17:19:08.837Z] [2024-02-20 17:14:36 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-02-20T17:19:08.837Z] [2024-02-20 17:14:37 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-02-20T17:19:08.837Z] [2024-02-20 17:14:37 - DEBUG - ci_test]: (api_request)  : [Collection.compact] args: [180], kwargs: {} (api_request.py:62)

[2024-02-20T17:19:08.837Z] [2024-02-20 17:14:37 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-02-20T17:19:08.837Z] [2024-02-20 17:15:38 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-02-20T17:19:08.837Z] [2024-02-20 17:15:39 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-02-20T17:19:08.837Z] [2024-02-20 17:15:39 - INFO - ci_test]: assert create collection: 0.03422975540161133, init_entities: 138747 (test_all_collections_after_chaos.py:49)

[2024-02-20T17:19:08.837Z] [2024-02-20 17:15:39 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [[[-3000, -2999, -2998, -2997, -2996, -2995, -2994, -2993, -2992, -2991, -2990, -2989, -2988, -2987, -2986, -2985, -2984, -2983, -2982, -2981, -2980, -2979, -2978, -2977, -2976, -2975, -2974, -2973, -2972, -2971, -2970, -2969, -2968, -2967, -2966, -2965, -2964, -2963, -2962, -2961, -2960, -2959, -29......, kwargs: {'timeout': 180} (api_request.py:62)

[2024-02-20T17:19:08.837Z] [2024-02-20 17:15:39 - DEBUG - ci_test]: (api_response) : (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 447859743648382978, success count: 2000, err count: 0)  (api_request.py:37)

[2024-02-20T17:19:08.837Z] [2024-02-20 17:15:39 - INFO - ci_test]: assert insert: 0.40061354637145996 (test_all_collections_after_chaos.py:61)

[2024-02-20T17:19:08.838Z] [2024-02-20 17:15:39 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-02-20T17:19:08.838Z] [2024-02-20 17:15:43 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-02-20T17:19:08.838Z] [2024-02-20 17:15:43 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-02-20T17:19:08.838Z] [2024-02-20 17:15:44 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-02-20T17:19:08.838Z] [2024-02-20 17:15:44 - INFO - ci_test]: assert flush: 4.171746492385864, entities: 140747 (test_all_collections_after_chaos.py:71)

[2024-02-20T17:19:08.838Z] [2024-02-20 17:15:44 - INFO - ci_test]: index info: [{'collection': 'Checker__e2cqqf7F', 'field': 'float_vector', 'index_name': 'vec_index', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}] (test_all_collections_after_chaos.py:87)

[2024-02-20T17:19:08.838Z] [2024-02-20 17:15:44 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 180], kwargs: {} (api_request.py:62)

[2024-02-20T17:19:08.838Z] [2024-02-20 17:18:44 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=wait for loading collection timeout, collection: Checker__e2cqqf7F)>, <Time:{'RPC start': '2024-02-20 17:15:44.256372', 'RPC error': '2024-02-20 17:18:44.736080'}> (decorators.py:134)

[2024-02-20T17:19:08.838Z] [2024-02-20 17:18:44 - WARNING - pymilvus.decorators]: Retry timeout: 180s (decorators.py:100)

[2024-02-20T17:19:08.838Z] [2024-02-20 17:18:44 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for loading collection timeout, collection: Checker__e2cqqf7F)>, <Time:{'RPC start': '2024-02-20 17:15:44.253912', 'RPC error': '2024-02-20 17:18:44.736521'}> (decorators.py:134)

[2024-02-20T17:19:08.838Z] [2024-02-20 17:18:44 - ERROR - ci_test]: Traceback (most recent call last):

[2024-02-20T17:19:08.838Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2024-02-20T17:19:08.838Z]     res = func(*args, **_kwargs)

[2024-02-20T17:19:08.838Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2024-02-20T17:19:08.838Z]     return func(*arg, **kwargs)

[2024-02-20T17:19:08.838Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 419, in load

[2024-02-20T17:19:08.838Z]     conn.load_collection(

[2024-02-20T17:19:08.838Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 135, in handler

[2024-02-20T17:19:08.838Z]     raise e from e

[2024-02-20T17:19:08.838Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 131, in handler

[2024-02-20T17:19:08.838Z]     return func(*args, **kwargs)

[2024-02-20T17:19:08.838Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 170, in handler

[2024-02-20T17:19:08.838Z]     return func(self, *args, **kwargs)

[2024-02-20T17:19:08.838Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 101, in handler

[2024-02-20T17:19:08.838Z]     raise MilvusException(

[2024-02-20T17:19:08.838Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for loading collection timeout, collection: Checker__e2cqqf7F)>

[2024-02-20T17:19:08.838Z]  (api_request.py:45)

[2024-02-20T17:19:08.838Z] [2024-02-20 17:18:44 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for loading collection timeout, collection: Checker__e2cqqf7F)> (api_request.py:46)

[2024-02-20T17:19:08.838Z] ------------- generated html file: file:///tmp/ci_logs/report.html -------------

[2024-02-20T17:19:08.838Z] =========================== short test summary info ============================

[2024-02-20T17:19:08.838Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[Checker__79a480dV] - AssertionError: Response of API load expect True, but got False

[2024-02-20T17:19:08.838Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[Checker__xwOrbdY2] - AssertionError: Response of API load expect True, but got False

[2024-02-20T17:19:08.838Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[Checker__ecbLyMuH] - AssertionError: Response of API load expect True, but got False

[2024-02-20T17:19:08.838Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[Checker__NS1mEkN7] - AssertionError: Response of API load expect True, but got False

[2024-02-20T17:19:08.838Z] FAILED testcases/test_all_collections_after_chaos.py::TestAllCollection::test_milvus_default[Checker__e2cqqf7F] - AssertionError: Response of API load expect True, but got False
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/11737/pipeline/291
log:
[artifacts-standalone-pod-kill-11737-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/14353510/artifacts-standalone-pod-kill-11737-server-logs.tar.gz)

### Anything else?

This issue reproduced stably

**Comment by smellthemoon** [comment]
<img width="1345" alt="1" src="https://github.com/milvus-io/milvus/assets/64083300/68d70ec6-290f-45ac-abfd-ee34f3bf1885">
load failed because key not found in minio.
<img width="1143" alt="2" src="https://github.com/milvus-io/milvus/assets/64083300/073b1fb1-06cf-405b-ab9c-554bbc805d00">
segment<447859184773274513> compact to a new segment. Logpath wrong when load segment<447859184773274513>.
related with #30726

**Comment by zhuwenxing** [comment]
This issue did not happen when the deploy mode was standalone, while it appears in some other components' chaos test in cluster mode.
