### ISSUE TITLE
[Bug]: [string_match] Search failed with error "unsupported operator type for unary expr: Match" when using infix and postfix match for dynamic field

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#30714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20240218-99297ab8
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):    all
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4.0rc35
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Search failed with error "unsupported operator type for unary expr: Match" when using infix and postfix match for dynamic field

prefix matching is good:
```
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "varchar like '0%'", output_fields=['varchar'])
>>> res[0]
["id: 0, distance: 21.468961715698242, entity: {'varchar': '0'}"]
```

But infix and postfix match is failed:
```
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "varchar like '%0'", output_fields=['varchar'])
RPC error: [search], <MilvusException: (code=65535, message=fail to search on QueryNode 1: worker(1) query failed: Operator::GetOutput failed for [Operator:FilterBits, plan node id: 0] :  => unsupported operator type for unary expr: Match)>, <Time:{'RPC start': '2024-02-21 11:51:56.931054', 'RPC error': '2024-02-21 11:51:57.610344'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 792, in search
    resp = conn.search(
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 135, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 131, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 170, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 110, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 794, in search
    return self._execute_search(request, timeout, round_decimal=round_decimal, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 735, in _execute_search
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 728, in _execute_search
    check_status(response.status)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/utils.py", line 60, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=fail to search on QueryNode 1: worker(1) query failed: Operator::GetOutput failed for [Operator:FilterBits, plan node id: 0] :  => unsupported operator type for unary expr: Match)>
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "varchar like '%0%'", output_fields=['varchar'])
RPC error: [search], <MilvusException: (code=65535, message=fail to search on QueryNode 1: worker(1) query failed: Operator::GetOutput failed for [Operator:FilterBits, plan node id: 0] :  => unsupported operator type for unary expr: Match)>, <Time:{'RPC start': '2024-02-21 11:53:10.426855', 'RPC error': '2024-02-21 11:53:11.151808'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 792, in search
    resp = conn.search(
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 135, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 131, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 170, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 110, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 794, in search
    return self._execute_search(request, timeout, round_decimal=round_decimal, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 735, in _execute_search
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 728, in _execute_search
    check_status(response.status)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/utils.py", line 60, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=fail to search on QueryNode 1: worker(1) query failed: Operator::GetOutput failed for [Operator:FilterBits, plan node id: 0] :  => unsupported operator type for unary expr: Match)>
```

### Expected Behavior

Search using infix and postfix match successfully for dynamic field

### Steps To Reproduce

```python
from pymilvus import CollectionSchema, FieldSchema
from pymilvus import Collection
from pymilvus import connections
from pymilvus import DataType
from pymilvus import Partition
import numpy as np
connections.connect()

dim = 128
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
schema = CollectionSchema(fields=[int64_field, float_vector], enable_dynamic_field=True)

collection = Collection("hello_milvus_binbin1", schema)
nb = 2000
rng = np.random.default_rng(seed=19530)
rows = [{"int64": i, "float": i*1.0, "varchar": str(i), "json_field": {"number": i, "string": str(i), "bool": bool(i), "list": [j for j in range(0, i)]}, "float_vector": rng.random((1, dim))[0]} for  i in range(0, nb)]
collection.insert(rows)
index_param = {"index_type": "IVF_FLAT", "metric_type": "L2", "params": {"nlist": 100}}
collection.create_index("float_vector", index_param)
collection.load()
nq = 1
import random
vectors = [[random.random() for _ in range(dim)] for _ in range(nq)]

default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
limit = 1000

res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "varchar like '0%'", output_fields=['varchar'])
print(res[0])

res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "varchar like '%0'", output_fields=['varchar'])

res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "varchar like '%0%'", output_fields=['varchar'])
```

**Comment by binbinlv** [comment]
Similar issue for json field:

```
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "json_field['string'] like '0%'")
>>>
>>> res[0]
['id: 0, distance: 21.468961715698242, entity: {}']
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "json_field['string'] like '%0'")
RPC error: [search], <MilvusException: (code=65535, message=fail to search on QueryNode 1: worker(1) query failed: Operator::GetOutput failed for [Operator:FilterBits, plan node id: 0] :  => unsupported operator type for unary expr: Match)>, <Time:{'RPC start': '2024-02-21 14:15:53.901129', 'RPC error': '2024-02-21 14:15:54.589086'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 792, in search
    resp = conn.search(
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 135, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 131, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 170, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 110, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 794, in search
    return self._execute_search(request, timeout, round_decimal=round_decimal, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 735, in _execute_search
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 728, in _execute_search
    check_status(response.status)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/utils.py", line 60, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=fail to search on QueryNode 1: worker(1) query failed: Operator::GetOutput failed for [Operator:FilterBits, plan node id: 0] :  => unsupported operator type for unary expr: Match)>
```

**Comment by longjiquan** [comment]
OK, I'll fix this soon.

**Comment by longjiquan** [comment]
fixed by #30779 
please help to recheck this, thx. /assign @binbinlv

**Comment by binbinlv** [comment]
Verified, this error is fixed, but appears entities become less issue after flush().
milvus: master-20240228-095cdbed-amd64
pymilvus: 2.4.0rc37

```
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "varchar like '%0'", output_fields=['varchar'])

>>>
>>> len(res[0])
200
>>>
>>>
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "varchar like '%0%'", output_fields=['varchar'])
>>> len(res[0])
452
>>>
>>>
>>> collection.flush()
>>> collection.flush()
>>> collection.flush()
>>> collection.flush()
>>> collection.flush()
>>> collection.flush()
>>> collection.flush()
>>> collection.flush()
>>>
>>>
>>>
>>> collection.flush()
>>>
>>>
>>>
>>>
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "varchar like '0%'", output_fields=['varchar'])
>>> len(res[0])
0
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "varchar like '%0'", output_fields=['varchar'])
>>> len(res[0])
56
>>>
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "varchar like '%0%'", output_fields=['varchar'])
len(res[0])>>> len(res[0])
116
```

**Comment by longjiquan** [comment]
Please try using larger `nprobe` to simulate bruteforce search, for example, set nprobe=nlist(10).
/assign @binbinlv

**Comment by binbinlv** [comment]
Yes, when nprobe=nlist, it could be searched with all the results after flush.

And when nprobe < nlist, it will search only nprobe buckets, so it is valid, then close the issue.

**Comment by asgg4321** [comment]
```
collection.query(
    "name like '%0%'",
    output_fields=[field.name for field in collection.schema.fields],
)
```
This error also exists in the query！
