### ISSUE TITLE
[Bug]: load hang if loading a collection has much more entities than milvus's capacity.

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#30736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.3.9
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):
```

### Current Behavior

1. load hang if loading a collection has much more entities than its capacity
2. utility.loading_progress(c.name) return exception when loading process is hang
`RPC error: [get_loading_progress], <MilvusException: (code=65535, message=show collection failed: load segment failed, OOM if load, maxSegmentSize = 281.928391456604 MB, concurrency = 1, memUsage = 8312.82421875 MB, predictMemUsage = 8594.752610206604 MB, totalMem = 9216 MB thresholdFactor = 0.900000)>, <Time:{'RPC start': '2024-02-21 18:42:50.507292', 'RPC error': '2024-02-21 18:42:50.657950'}>
`

### Expected Behavior

1. if loading a collection has much more entities than its capacity, it shall return error very quickly.
2. utility.loading_progress(c.name) shall not return exception in any situations

### Steps To Reproduce

```markdown
1. deploy a 2c8g milvus standalone instance
   with queryCoord.taskExecutionCap:4 (if use default value 256, milvus will OOM after a few seconds after calling load)
2. create a collection and insert 768d, 10 million vectors(much more than the milvus's capacity)
3. build HNSW and load
```

### Milvus Log

it seems that milvus is retrying to load different segments, but I think in this case retry never helps, and we should return error immediately

**Comment by yanliang567** [comment]
![image](https://github.com/milvus-io/milvus/assets/82361606/88dc4fb4-0478-4ca7-ba5f-57bf228fbaa4)

**Comment by yanliang567** [comment]
in the pymilvus load() api, it returns after about 10 min timeout with msgs like
code=65535, message=Retry run out of 75 retry times, message=show collection failed: load segment failed, OOM if load
is it possible to not retry for this potential oom reason?

**Comment by congqixia** [comment]
looks like the pymilvus not stop asking whether collection is loaded even milvus abort to load this collection
@XuanYang-cn could you please help this issue?

**Comment by congqixia** [comment]
@yanliang567 also we need the stacktrace for this load exception

**Comment by congqixia** [comment]
Also, we shall verify this behavior for all sdk

**Comment by yanliang567** [comment]
here is the stack:
```
[get_loading_progress] retry:75, cost: 3.00s, reason: <_MultiThreadedRendezvous: StatusCode.UNAVAILABLE, failed to connect to all addresses; last error: UNAVAILABLE: ipv4:198.18.2.2:19535: FD shutdown>
Retry run out of 75 retry times
RPC error: [get_loading_progress], <MilvusException: (code=65535, message=Retry run out of 75 retry times, message=show collection failed: load segment failed, OOM if load, maxSegmentSize = 273.5058546066284 MB, concurrency = 1, memUsage = 8080.96875 MB, predictMemUsage = 8354.474604606628 MB, totalMem = 9216 MB thresholdFactor = 0.900000)>, <Time:{'RPC start': '2024-02-21 19:39:39.361399', 'RPC error': '2024-02-22 08:37:17.694185'}>
RPC error: [wait_for_loading_collection], <MilvusException: (code=65535, message=Retry run out of 75 retry times, message=show collection failed: load segment failed, OOM if load, maxSegmentSize = 273.5058546066284 MB, concurrency = 1, memUsage = 8080.96875 MB, predictMemUsage = 8354.474604606628 MB, totalMem = 9216 MB thresholdFactor = 0.900000)>, <Time:{'RPC start': '2024-02-21 19:37:19.445632', 'RPC error': '2024-02-22 08:37:17.694680'}>
RPC error: [load_collection], <MilvusException: (code=65535, message=Retry run out of 75 retry times, message=show collection failed: load segment failed, OOM if load, maxSegmentSize = 273.5058546066284 MB, concurrency = 1, memUsage = 8080.96875 MB, predictMemUsage = 8354.474604606628 MB, totalMem = 9216 MB thresholdFactor = 0.900000)>, <Time:{'RPC start': '2024-02-21 19:37:19.184199', 'RPC error': '2024-02-22 08:37:17.695535'}>
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 419, in load
    conn.load_collection(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 135, in handler
    raise e from e
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 131, in handler
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 170, in handler
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 110, in handler
    raise e from e
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 1098, in load_collection
    self.wait_for_loading_collection(collection_name, timeout, is_refresh=_refresh)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 135, in handler
    raise e from e
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 131, in handler
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 170, in handler
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 110, in handler
    raise e from e
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 1118, in wait_for_loading_collection
    progress = self.get_loading_progress(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 135, in handler
    raise e from e
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 131, in handler
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 170, in handler
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/decorators.py", line 101, in handler
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=Retry run out of 75 retry times, message=show collection failed: load segment failed, OOM if load, maxSegmentSize = 273.5058546066284 MB, concurrency = 1, memUsage = 8080.96875 MB, predictMemUsage = 8354.474604606628 MB, totalMem = 9216 MB thresholdFactor = 0.900000)>

```

**Comment by congqixia** [comment]
@yanliang567 I believe it is by design for Milvus trying to load for 10 minutes when querynodes are out-of-memory?
/assign @yanliang567

**Comment by yanliang567** [comment]
close for now
