### ISSUE TITLE
[Bug]: [benchmark][cluster] Collection load failed `collection not loaded` in concurrent DDL & DQL scene

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#30748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20240221-77eb6def
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):2.4.0rc19
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task:multi-vector-scene-mix2-v9b6l
test case name: test_hybrid_search_locust_ddl_dql_search_cluster

server:
```
NAME                                                              READY   STATUS        RESTARTS        AGE     IP              NODE         NOMINATED NODE   READINESS GATES
multi-vector-scene-mix2-v9b6l-1-etcd-0                            1/1     Running       0               12h     10.104.24.242   4am-node29   <none>           <none>
multi-vector-scene-mix2-v9b6l-1-etcd-1                            1/1     Running       0               12h     10.104.20.215   4am-node22   <none>           <none>
multi-vector-scene-mix2-v9b6l-1-etcd-2                            1/1     Running       0               12h     10.104.23.27    4am-node27   <none>           <none>
multi-vector-scene-mix2-v9b6l-1-milvus-datacoord-d68697fb54ws2r   1/1     Running       1 (12h ago)     12h     10.104.6.62     4am-node13   <none>           <none>
multi-vector-scene-mix2-v9b6l-1-milvus-datanode-7665c9d6788pm7r   1/1     Running       1 (12h ago)     12h     10.104.1.178    4am-node10   <none>           <none>
multi-vector-scene-mix2-v9b6l-1-milvus-indexcoord-6448f7f6zxjv8   1/1     Running       0               12h     10.104.1.177    4am-node10   <none>           <none>
multi-vector-scene-mix2-v9b6l-1-milvus-indexnode-65f9fc746552wj   1/1     Running       1 (12h ago)     12h     10.104.5.218    4am-node12   <none>           <none>
multi-vector-scene-mix2-v9b6l-1-milvus-indexnode-65f9fc746b8gsw   1/1     Running       1 (12h ago)     12h     10.104.14.48    4am-node18   <none>           <none>
multi-vector-scene-mix2-v9b6l-1-milvus-indexnode-65f9fc746rx646   1/1     Running       1 (12h ago)     12h     10.104.9.154    4am-node14   <none>           <none>
multi-vector-scene-mix2-v9b6l-1-milvus-indexnode-65f9fc746sbrwm   1/1     Running       1 (12h ago)     12h     10.104.18.175   4am-node25   <none>           <none>
multi-vector-scene-mix2-v9b6l-1-milvus-proxy-7c68cbc454-psfhj     1/1     Running       2 (12h ago)     12h     10.104.20.152   4am-node22   <none>           <none>
multi-vector-scene-mix2-v9b6l-1-milvus-querycoord-576c9567drtlk   1/1     Running       1 (12h ago)     12h     10.104.1.175    4am-node10   <none>           <none>
multi-vector-scene-mix2-v9b6l-1-milvus-querynode-6574485dc4hn88   1/1     Running       0               12h     10.104.23.29    4am-node27   <none>           <none>
multi-vector-scene-mix2-v9b6l-1-milvus-querynode-6574485dc6qpd5   1/1     Running       1 (12h ago)     12h     10.104.19.3     4am-node28   <none>           <none>
multi-vector-scene-mix2-v9b6l-1-milvus-rootcoord-8669667cbnpbpv   1/1     Running       1 (12h ago)     12h     10.104.1.173    4am-node10   <none>           <none>
multi-vector-scene-mix2-v9b6l-1-minio-0                           1/1     Running       0               12h     10.104.23.20    4am-node27   <none>           <none>
multi-vector-scene-mix2-v9b6l-1-minio-1                           1/1     Running       0               12h     10.104.20.214   4am-node22   <none>           <none>
multi-vector-scene-mix2-v9b6l-1-minio-2                           1/1     Running       0               12h     10.104.21.137   4am-node24   <none>           <none>
multi-vector-scene-mix2-v9b6l-1-minio-3                           1/1     Running       0               12h     10.104.33.190   4am-node36   <none>           <none>
multi-vector-scene-mix2-v9b6l-1-pulsar-bookie-0                   1/1     Running       0               12h     10.104.32.84    4am-node39   <none>           <none>
multi-vector-scene-mix2-v9b6l-1-pulsar-bookie-1                   1/1     Running       0               12h     10.104.15.85    4am-node20   <none>           <none>
multi-vector-scene-mix2-v9b6l-1-pulsar-bookie-2                   1/1     Running       0               12h     10.104.20.216   4am-node22   <none>           <none>
multi-vector-scene-mix2-v9b6l-1-pulsar-bookie-init-bmbvh          0/1     Completed     0               12h     10.104.1.176    4am-node10   <none>           <none>
multi-vector-scene-mix2-v9b6l-1-pulsar-broker-0                   1/1     Running       0               12h     10.104.29.108   4am-node35   <none>           <none>
multi-vector-scene-mix2-v9b6l-1-pulsar-proxy-0                    1/1     Running       0               12h     10.104.6.64     4am-node13   <none>           <none>
multi-vector-scene-mix2-v9b6l-1-pulsar-pulsar-init-wf7gf          0/1     Completed     0               12h     10.104.1.174    4am-node10   <none>           <none>
multi-vector-scene-mix2-v9b6l-1-pulsar-recovery-0                 1/1     Running       0               12h     10.104.24.223   4am-node29   <none>           <none>
multi-vector-scene-mix2-v9b6l-1-pulsar-zookeeper-0                1/1     Running       0               12h     10.104.20.209   4am-node22   <none>           <none>
multi-vector-scene-mix2-v9b6l-1-pulsar-zookeeper-1                1/1     Running       0               12h     10.104.23.62    4am-node27   <none>           <none>
multi-vector-scene-mix2-v9b6l-1-pulsar-zookeeper-2                1/1     Running       0               12h     10.104.25.59    4am-node30   <none>           <none>
```

client pod name:multi-vector-scene-mix2-v9b6l-3102596583
client log:

[client.log](https://github.com/milvus-io/milvus/files/14367976/client.log)

<img width="1632" alt="截屏2024-02-22 10 57 10" src="https://github.com/milvus-io/milvus/assets/26307815/77926ee3-4c2f-4ff5-8651-0bc01245a30f">

`{pod=~"multi-vector-scene-mix2-v9b6l-1-milvus-proxy-7c68cbc454-psfhj"} |~ "447873677776920871"`
![image](https://github.com/milvus-io/milvus/assets/26307815/89f0bb72-9866-453b-a6bb-b8e0a7c69fc8)

`{pod=~"multi-vector-scene-mix2-v9b6l-1-milvus-querynode-.*"} |~ "447873677776920871"`
![image](https://github.com/milvus-io/milvus/assets/26307815/d4f115a6-6e15-4de5-9de5-f8a5ffe8d0f0)

```
[2024-02-21 17:38:31,436 - DEBUG - fouram]: [Base] Create collection scene_search_test_8rw9t5v6 (base.py:267)
[2024-02-21 17:38:31,436 - DEBUG - fouram]: (api_request)  : [Collection] args: ['scene_search_test_8rw9t5v6', {'auto_id': False, 'description': '', 'fields': [{'name': 'id', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float_vector', 'description': '', 'type': <DataType.FLOAT_VECTOR: 101>, 'params': {'dim': 128}}]}, 'default'], kwargs: {'shards_num': 2}, [requestId: 07a1e23c-d0e0-11ee-8a80-76c43c2a5863] (api_request.py:76)
<name>: scene_search_test_8rw9t5v6
[2024-02-21 17:38:32,568 - DEBUG - fouram]: [Base] Start inserting 3000 vectors to collection scene_search_test_8rw9t5v6 (base.py:361)
[2024-02-21 17:38:32,792 - DEBUG - fouram]: [Base] Number of vectors in the collection(scene_search_test_8rw9t5v6): 0 (base.py:491)
[2024-02-21 17:38:32,797 - DEBUG - fouram]: [Base] Start flush collection scene_search_test_8rw9t5v6 (base.py:307)
[2024-02-21 17:38:36,400 - DEBUG - fouram]: [Base] Number of vectors in the collection(scene_search_test_8rw9t5v6): 3000 (base.py:491)
[2024-02-21 17:38:36,400 - DEBUG - fouram]: [Base] Start build index of IVF_SQ8 for field:float_vector collection:scene_search_test_8rw9t5v6, params:{'index_type': 'IVF_SQ8', 'metric_type': 'L2', 'params': {'nlist': 2048}} (base.py:445)
<name>: scene_search_test_8rw9t5v6
[2024-02-21 17:38:37,484 - DEBUG - fouram]: [Base] Start load collection scene_search_test_8rw9t5v6,replica_number:1,kwargs:{} (base.py:313)
[2024-02-21 17:48:41,359 - ERROR - fouram]: RPC error: [get_loading_progress], <MilvusException: (code=101, message=collection not loaded[collection=447873677776920871])>, <Time:{'RPC start': '2024-02-21 17:48:41.350450', 'RPC error': '2024-02-21 17:48:41.359350'}> (decorators.py:134)
[2024-02-21 17:48:41,359 - ERROR - fouram]: RPC error: [wait_for_loading_collection], <MilvusException: (code=101, message=collection not loaded[collection=447873677776920871])>, <Time:{'RPC start': '2024-02-21 17:38:37.536216', 'RPC error': '2024-02-21 17:48:41.359688'}> (decorators.py:134)
[2024-02-21 17:48:41,359 - ERROR - fouram]: RPC error: [load_collection], <MilvusException: (code=101, message=collection not loaded[collection=447873677776920871])>, <Time:{'RPC start': '2024-02-21 17:38:37.484926', 'RPC error': '2024-02-21 17:48:41.359841'}> (decorators.py:134)
pymilvus.exceptions.MilvusException: <MilvusException: (code=101, message=collection not loaded[collection=447873677776920871])>
[2024-02-21 17:48:41,360 - ERROR - fouram]: (api_response) : [Collection.load] <MilvusException: (code=101, message=collection not loaded[collection=447873677776920871])>, [requestId: 0b3cc718-d0e0-11ee-8a80-76c43c2a5863] (api_request.py:57)
[2024-02-21 17:48:41,360 - ERROR - fouram]: [CheckFunc] load request check failed, response:<MilvusException: (code=101, message=collection not loaded[collection=447873677776920871])> (func_check.py:54)
```

<img width="1914" alt="截屏2024-02-22 11 40 53" src="https://github.com/milvus-io/milvus/assets/26307815/d643ca04-d34f-43c4-ac9a-2ef06c2a8ec5">

### Steps To Reproduce

```markdown
concurrent test and calculation of RT and QPS

        :purpose:  `DDL & DQL`
            verify DDL & DQL scenario,
            which has 4 vector fields(IVF_FLAT, HNSW, DISKANN, IVF_SQ8) and scalar fields: `int64_1`, `varchar_1`

        :test steps:
            1. create collection with fields:
                'float_vector': 128dim,
                'float_vector_1': 128dim,
                'float_vector_2': 128dim,
                'float_vector_3': 128dim,
                scalar field: int64_1, varchar_1
            2. build indexes:
                IVF_FLAT: 'float_vector'
                HNSW: 'float_vector_1',
                DISKANN: 'float_vector_2'
                IVF_SQ8: 'float_vector_3'
                INVERTED: 'int64_1', 'varchar_1'
                default scalar index: 'id'
            3. insert 1m data
            4. flush collection
            5. build indexes again using the same params
            6. load collection
                replica: 1
            7. concurrent request:
                - scene_search_test
                    (collection: create->insert->flush->index->load->search->drop) <- load raises error
                - search
                - hybrid_search
                - query
```

### Anything else?

test result:
```
{'server': {'deploy_tool': 'helm',
            'deploy_mode': 'cluster',
            'config_name': 'cluster_2c8m',
            'config': {'queryNode': {'resources': {'limits': {'cpu': '32.0',
                                                              'memory': '32Gi'},
                                                   'requests': {'cpu': '17.0',
                                                                'memory': '17Gi'}},
                                     'replicas': 2},
                       'indexNode': {'resources': {'limits': {'cpu': '8.0',
                                                              'memory': '8Gi'},
                                                   'requests': {'cpu': '5.0',
                                                                'memory': '5Gi'}},
                                     'replicas': 4},
                       'dataNode': {'resources': {'limits': {'cpu': '2.0',
                                                             'memory': '8Gi'},
                                                  'requests': {'cpu': '2.0',
                                                               'memory': '5Gi'}}},
                       'cluster': {'enabled': True},
                       'pulsar': {},
                       'kafka': {},
                       'minio': {'metrics': {'podMonitor': {'enabled': True}}},
                       'etcd': {'metrics': {'enabled': True,
                                            'podMonitor': {'enabled': True}}},
                       'metrics': {'serviceMonitor': {'enabled': True}},
                       'log': {'level': 'debug'},
                       'image': {'all': {'repository': 'harbor.milvus.io/milvus/milvus',
                                         'tag': 'master-20240221-77eb6def'}}},
            'host': 'multi-vector-scene-mix2-v9b6l-1-milvus.qa-milvus.svc.cluster.local',
            'port': '19530',
            'uri': ''},
 'client': {'test_case_type': 'ConcurrentClientBase',
            'test_case_name': 'test_hybrid_search_locust_ddl_dql_search_cluster',
            'test_case_params': {'dataset_params': {'metric_type': 'L2',
                                                    'dim': 128,
                                                    'scalars_index': {'id': {},
                                                                      'int64_1': {'index_type': 'INVERTED'},
                                                                      'varchar_1': {'index_type': 'INVERTED'}},
                                                    'vectors_index': {'float_vector_1': {'index_type': 'HNSW',
                                                                                         'index_param': {'M': 8,
                                                                                                         'efConstruction': 200},
                                                                                         'metric_type': 'L2'},
                                                                      'float_vector_2': {'index_type': 'DISKANN',
                                                                                         'index_param': {},
                                                                                         'metric_type': 'IP'},
                                                                      'float_vector_3': {'index_type': 'IVF_SQ8',
                                                                                         'index_param': {'nlist': 2048},
                                                                                         'metric_type': 'L2'}},
                                                    'scalars_params': {'float_vector_1': {'params': {'dim': 128},
                                                                                          'other_params': {'dataset': 'sift',
                                                                                                           'dim': 128}},
                                                                       'float_vector_2': {'params': {'dim': 128},
                                                                                          'other_params': {'dataset': 'sift',
                                                                                                           'dim': 128}},
                                                                       'float_vector_3': {'params': {'dim': 128},
                                                                                          'other_params': {'dataset': 'sift',
                                                                                                           'dim': 128}}},
                                                    'dataset_name': 'sift',
                                                    'dataset_size': 1000000,
                                                    'ni_per': 10000},
                                 'collection_params': {'other_fields': ['float_vector_1',
                                                                        'float_vector_2',
                                                                        'float_vector_3',
                                                                        'int64_1',
                                                                        'varchar_1'],
                                                       'shards_num': 2},
                                 'resource_groups_params': {'reset': False},
                                 'database_user_params': {'reset_rbac': False,
                                                          'reset_db': False},
                                 'index_params': {'index_type': 'IVF_FLAT',
                                                  'index_param': {'nlist': 1024}},
                                 'concurrent_params': {'concurrent_number': 20,
                                                       'during_time': '12h',
                                                       'interval': 20,
                                                       'spawn_rate': None},
                                 'concurrent_tasks': [{'type': 'scene_search_test',
                                                       'weight': 1,
                                                       'params': {'dataset': 'local',
                                                                  'dim': 128,
                                                                  'shards_num': 2,
                                                                  'data_size': 3000,
                                                                  'nb': 3000,
                                                                  'index_type': 'IVF_SQ8',
                                                                  'index_param': {'nlist': 2048},
                                                                  'metric_type': 'L2',
                                                                  'other_fields': [],
                                                                  'replica_number': 1,
                                                                  'nq': 1,
                                                                  'top_k': 10,
                                                                  'search_param': {'nprobe': 16},
                                                                  'search_counts': 1,
                                                                  'scalars_params': {},
                                                                  'scalars_index': {},
                                                                  'vectors_index': {},
                                                                  'prepare_before_insert': False,
                                                                  'new_connect': False,
                                                                  'new_user': False}},
                                                      {'type': 'search',
                                                       'weight': 1,
                                                       'params': {'nq': 1000,
                                                                  'top_k': 1,
                                                                  'search_param': {'nprobe': 1000},
                                                                  'expr': 'int64_1 '
                                                                          '>= '
                                                                          '0',
                                                                  'guarantee_timestamp': None,
                                                                  'partition_names': None,
                                                                  'output_fields': None,
                                                                  'ignore_growing': False,
                                                                  'group_by_field': None,
                                                                  'timeout': 600,
                                                                  'random_data': True}},
                                                      {'type': 'hybrid_search',
                                                       'weight': 1,
                                                       'params': {'nq': 1,
                                                                  'top_k': 100,
                                                                  'reqs': [{'search_param': {'nprobe': 128},
                                                                            'anns_field': 'float_vector',
                                                                            'expr': 'int64_1 '
                                                                                    '> '
                                                                                    '100000',
                                                                            'top_k': 100},
                                                                           {'search_param': {'ef': 64},
                                                                            'anns_field': 'float_vector_1',
                                                                            'expr': 'id '
                                                                                    '< '
                                                                                    '900000',
                                                                            'top_k': 10},
                                                                           {'search_param': {'search_list': 32},
                                                                            'anns_field': 'float_vector_2',
                                                                            'expr': 'varchar_1 '
                                                                                    '> '
                                                                                    '"1"',
                                                                            'top_k': 30},
                                                                           {'search_param': {'nprobe': 16},
                                                                            'anns_field': 'float_vector_3',
                                                                            'top_k': 400}],
                                                                  'rerank': {'WeightedRanker': [0.85,
                                                                                                0.95,
                                                                                                0.51,
                                                                                                0.32]},
                                                                  'output_fields': ['*'],
                                                                  'ignore_growing': False,
                                                                  'guarantee_timestamp': None,
                                                                  'partition_names': None,
                                                                  'timeout': 600,
                                                                  'random_data': True}},
                                                      {'type': 'query',
                                                       'weight': 1,
                                                       'params': {'ids': None,
                                                                  'expr': 'int64_1 '
                                                                          '> '
                                                                          '-1 '
                                                                          '&& ',
                                                                  'output_fields': ['*'],
                                                                  'offset': None,
                                                                  'limit': None,
                                                                  'ignore_growing': False,
                                                                  'partition_names': None,
                                                                  'timeout': 600,
                                                                  'random_data': True,
                                                                  'random_count': 20,
                                                                  'random_range': [0,
                                                                                   100000],
                                                                  'field_name': 'id',
                                                                  'field_type': 'int64'}}]},
            'run_id': 2024022120678608,
            'datetime': '2024-02-21 07:54:27.923979',
            'client_version': '2.4.0'},
 'result': {'test_result': {'index': {'RT': 105.1332,
                                      'float_vector_1': {'RT': 0.5283},
                                      'float_vector_2': {'RT': 165.4945},
                                      'float_vector_3': {'RT': 0.53},
                                      'id': {'RT': 0.5404},
                                      'int64_1': {'RT': 0.5203},
                                      'varchar_1': {'RT': 0.5158}},
                            'insert': {'total_time': 117.4184,
                                       'VPS': 8516.5528,
                                       'batch_time': 1.1742,
                                       'batch': 10000},
                            'flush': {'RT': 3.0386},
                            'load': {'RT': 7.5798},
                            'Locust': {'Aggregated': {'Requests': 38292,
                                                      'Fails': 1236,
                                                      'RPS': 0.89,
                                                      'fail_s': 0.03,
                                                      'RT_max': 653763.75,
                                                      'RT_avg': 22363.75,
                                                      'TP50': 410.0,
                                                      'TP99': 611000.0},
                                       'hybrid_search': {'Requests': 9679,
                                                         'Fails': 0,
                                                         'RPS': 0.22,
                                                         'fail_s': 0.0,
                                                         'RT_max': 1946.27,
                                                         'RT_avg': 234.33,
                                                         'TP50': 190.0,
                                                         'TP99': 750.0},
                                       'query': {'Requests': 9386,
                                                 'Fails': 0,
                                                 'RPS': 0.22,
                                                 'fail_s': 0.0,
                                                 'RT_max': 3395.74,
                                                 'RT_avg': 192.59,
                                                 'TP50': 160.0,
                                                 'TP99': 560.0},
                                       'scene_search_test': {'Requests': 9650,
                                                             'Fails': 1236,
                                                             'RPS': 0.22,
                                                             'fail_s': 0.13,
                                                             'RT_max': 653763.75,
                                                             'RT_avg': 87786.32,
                                                             'TP50': 10000.0,
                                                             'TP99': 614000.0},
                                       'search': {'Requests': 9577,
                                                  'Fails': 0,
                                                  'RPS': 0.22,
                                                  'fail_s': 0.0,
                                                  'RT_max': 8331.26,
                                                  'RT_avg': 536.61,
                                                  'TP50': 480.0,
                                                  'TP99': 1200.0}}}}}
```

**Comment by yanliang567** [comment]
is it a dup to #30746? @chyezh please help to check
/assign @chyezh 
/unassign

**Comment by chyezh** [comment]
- collection loading cannot find index.
- collection loading timeout, collection load process is canceled.
- Then `collection not loaded` reported

```
[2024/02/21 08:23:51.436 +00:00] [INFO] [task/executor.go:463] ["Sync Distribution..."] [taskID=1708502673593] [collectionID=447873677751529314] [replicaID=447873722854408235] [segmentID=447873677751529398] [leader=2] [node=8] [source=leader_checker] 
2024-02-21 16:23:51.442 | (no unique labels) | [2024/02/21 08:23:51.442 +00:00] [WARN] [task/executor.go:467] ["failed to sync distribution"] [taskID=1708502673593] [collectionID=447873677751529314] [replicaID=447873722854408235] [segmentID=447873677751529398] [leader=2] [node=8] [source=leader_checker] [error="index not found[collection=scene_search_test_Nv4xlj4w]"]

....

[2024/02/21 08:23:52.941 +00:00] [INFO] [observers/collection_observer.go:113] ["load collection timeout, cancel it"] [collectionID=447873677751529314] [loadTime=10m4.441252159s]
```

**Comment by chyezh** [comment]
fixed by #30758

**Comment by yanliang567** [comment]
i believe this was fixed, please help to verify @wangting0128 
/assign @wangting0128 
/unassign @chyezh

**Comment by wangting0128** [comment]
### verification passed

image：master-20240304-882b50c5

**Comment by prrs** [comment]
We are facing similar issue with 2.3.22. I see this fix is available in 2.4.x. Currently we can't migrate to 2.4.x as we have some custom implementation on top of 2.3.x. Please help me with below points:

- Kindly refer the logs to confirm it's similar issue
- In case, it's similar issue, how can I mitigate this?
- What will take to migrate the fix to 2.3.x?

[1735755989_61229_CCCA9F77-E5F4-421B-B941-20B872444B83.csv](https://github.com/user-attachments/files/18286283/1735755989_61229_CCCA9F77-E5F4-421B-B941-20B872444B83.csv)


[1735755992_61230_CCCA9F77-E5F4-421B-B941-20B872444B83.csv](https://github.com/user-attachments/files/18286286/1735755992_61230_CCCA9F77-E5F4-421B-B941-20B872444B83.csv)




stack trace

 java.lang.RuntimeException: index not found[collection=a360_prod_36c281b1adbd47c0940854b275e85009d1]
	at com.salesforce.cdp.dpc.service.kubernetes.milvus.MilvusUtils.handleResponseStatus(MilvusUtils.java:81)
	at com.salesforce.cdp.dpc.service.MilvusService.loadCollection(MilvusService.java:529)
	at com.salesforce.cdp.dpc.service.MilvusService.isMilvusClusterHealthy(MilvusService.java:269)
	at com.salesforce.cdp.dpc.jobs.MilvusClusterHealthCheckJob.lambda$execute$0(MilvusClusterHealthCheckJob.java:64)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at com.salesforce.cdp.dpc.jobs.MilvusClusterHealthCheckJob.execute(MilvusClusterHealthCheckJob.java:59)
	at com.salesforce.cdp.dpc.jobs.ScheduledJob.executeTraceableRun(ScheduledJob.java:81)
	at com.salesforce.servicelibs.opencontext.impl.BagContextProvider.lambda$wrap$0(BagContextProvider.java:40)
	at c.s.s.opencontext.impl.MultiContextProvider$ChainableRunnable.run(MultiContextProvider.java:90)
	

cc: @chyezh @xiaofan-luan

**Comment by chyezh** [comment]
@prrs does the collection not have any index?

**Comment by prrs** [comment]
@chyezh 
- Collection has an index
- If you refer the logs, the index creation was quick and done before hitting search.
- Even after that the index was not found during the load

**Comment by chyezh** [comment]
@prrs But I found that the log you provided are two different collection when creating index and load.
```

[2025/01/01   11:15:00.727 +00:00] [INFO] [datacoord/index_meta.go:277] ["meta update:   CreateIndex success"] [collectionID=454573880320700599] [fieldID=101]   [indexID=454573880320700694]   [indexName=a360_prod_36c281b1adbd47c0940854b275e85009d1_userFaceIndex]

[2025/01/01   11:15:02.043 +00:00] [WARN] [datacoord/index_service.go:578]   ["DescribeIndex fail"] [traceID=243b07e2bbf4c1d393106c003f0c3580]   [collectionID=454573880510349204] [indexName=] [error="index not   found[indexName=]"]
[2025/01/01 11:15:02.043 +00:00] [INFO]   [datacoord/index_service.go:564] ["receive DescribeIndex request"]   [traceID=243b07e2bbf4c1d393106c003f0c3580] [collectionID=454573880510349204]   [indexName=] [timestamp=0]
[2025/01/01 11:15:01.977 +00:00] [DEBUG]   [proxy/task.go:1440] ["loadCollectionTask Execute"]   [traceID=243b07e2bbf4c1d393106c003f0c3580] [role=proxy]   [collectionID=454573880510349204]

```
Please confirm the operation sequence of target collection `454573880510349204`.

**Comment by prrs** [comment]
thanks @chyezh, you pointed rightly, I reviewed this, it's a different issue. There was a failure during insertion and we never created the index.
