### ISSUE TITLE
[Bug]: search failed with error `segment lacks` in testcase `test_partition_key_on_multi_numpy_files`

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#30827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2024-02-26T09:02:04.594Z] [2024-02-26 09:01:12 - INFO - ci_test]: wait for bulk load tasks completed successfully, cost time: 10.092106580734253 (utility_wrapper.py:152)

[2024-02-26T09:02:04.594Z] [2024-02-26 09:01:12 - INFO - ci_test]: bulk insert state:True (test_bulk_insert.py:1468)

[2024-02-26T09:02:04.594Z] [2024-02-26 09:01:12 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-02-26T09:02:04.594Z] [2024-02-26 09:01:12 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-02-26T09:02:04.594Z] [2024-02-26 09:01:12 - INFO - ci_test]:  collection entities: 1500 (test_bulk_insert.py:1471)

[2024-02-26T09:02:04.594Z] [2024-02-26 09:01:12 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-02-26T09:02:04.594Z] [2024-02-26 09:01:13 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-02-26T09:02:04.594Z] [2024-02-26 09:01:13 - DEBUG - ci_test]: (api_request)  : [index_building_progress] args: ['bulk_ins_parkey_zs2JYYIq', '', 'default'], kwargs: {} (api_request.py:62)

[2024-02-26T09:02:04.594Z] [2024-02-26 09:01:13 - DEBUG - ci_test]: (api_response) : {'total_rows': 1500, 'indexed_rows': 1500, 'pending_index_rows': 0}  (api_request.py:37)

[2024-02-26T09:02:04.594Z] [2024-02-26 09:01:13 - DEBUG - ci_test]: index states: {'total_rows': 1500, 'indexed_rows': 1500, 'pending_index_rows': 0} (utility_wrapper.py:201)

[2024-02-26T09:02:04.594Z] [2024-02-26 09:01:13 - INFO - ci_test]: index build completed (utility_wrapper.py:203)

[2024-02-26T09:02:04.594Z] [2024-02-26 09:01:13 - INFO - ci_test]: wait for load finished and be ready for search (test_bulk_insert.py:1477)

[2024-02-26T09:02:04.594Z] [2024-02-26 09:01:13 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 180], kwargs: {'_refresh': True} (api_request.py:62)

[2024-02-26T09:02:04.594Z] [2024-02-26 09:01:14 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-02-26T09:02:04.594Z] [2024-02-26 09:01:16 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.31530011915467154, 0.1309029295561243, 0.1087578160943218, 0.3760873391902682, 0.07111540839644698, 0.05518526338641608, 0.3967707468591814, 0.2884078219651768, 0.4030411582630048, 0.28468644143472865, 0.0907767790271274, 0.39343969851960103, 0.2737656507326158]], 'vectors', {'metric_type': 'CO......, kwargs: {} (api_request.py:62)

[2024-02-26T09:02:04.594Z] [2024-02-26 09:01:16 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=503, message=failed to search: segment lacks[segment=447986647577786941]: channel not available[channel=by-dev-rootcoord-dml_15_447986647577785966v0])>, <Time:{'RPC start': '2024-02-26 09:01:16.024580', 'RPC error': '2024-02-26 09:01:16.174017'}> (decorators.py:134)

[2024-02-26T09:02:04.594Z] [2024-02-26 09:01:16 - ERROR - ci_test]: Traceback (most recent call last):

[2024-02-26T09:02:04.594Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2024-02-26T09:02:04.594Z]     res = func(*args, **_kwargs)

[2024-02-26T09:02:04.594Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2024-02-26T09:02:04.594Z]     return func(*arg, **kwargs)

[2024-02-26T09:02:04.594Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 792, in search

[2024-02-26T09:02:04.594Z]     resp = conn.search(

[2024-02-26T09:02:04.594Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 135, in handler

[2024-02-26T09:02:04.594Z]     raise e from e

[2024-02-26T09:02:04.594Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 131, in handler

[2024-02-26T09:02:04.594Z]     return func(*args, **kwargs)

[2024-02-26T09:02:04.594Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 170, in handler

[2024-02-26T09:02:04.594Z]     return func(self, *args, **kwargs)

[2024-02-26T09:02:04.594Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 110, in handler

[2024-02-26T09:02:04.594Z]     raise e from e

[2024-02-26T09:02:04.594Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler

[2024-02-26T09:02:04.594Z]     return func(*args, **kwargs)

[2024-02-26T09:02:04.594Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 794, in search

[2024-02-26T09:02:04.594Z]     return self._execute_search(request, timeout, round_decimal=round_decimal, **kwargs)

[2024-02-26T09:02:04.594Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 735, in _execute_search

[2024-02-26T09:02:04.594Z]     raise e from e

[2024-02-26T09:02:04.594Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 728, in _execute_search

[2024-02-26T09:02:04.594Z]     check_status(response.status)

[2024-02-26T09:02:04.594Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/utils.py", line 60, in check_status

[2024-02-26T09:02:04.594Z]     raise MilvusException(status.code, status.reason, status.error_code)

[2024-02-26T09:02:04.595Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=503, message=failed to search: segment lacks[segment=447986647577786941]: channel not available[channel=by-dev-rootcoord-dml_15_447986647577785966v0])>

[2024-02-26T09:02:04.595Z]  (api_request.py:45)

[2024-02-26T09:02:04.595Z] [2024-02-26 09:01:16 - ERROR - ci_test]: (api_response) : <MilvusException: (code=503, message=failed to search: segment lacks[segment=447986647577786941]: channel not available[channel=by-dev-rootcoord-dml_15_447986647577785966v0])> (api_request.py:46)
```

### Expected Behavior

search works well after bulk insert

### Milvus Log

failed job: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-30780/6/pipeline/149

**Comment by bigsheeper** [comment]
At time T0, the current target (with segment 447986647577786941) has already been updated. However, segment 447986647577786941 begins loading at time T1.
T0:
```
2024-02-26T17:01:13.987623139+08:00 stdout F [2024/02/26 09:01:13.987 +00:00] [DEBUG] [meta/target_manager.go:74] ["start to update current target for collection"] [collectionID=447986647577785966]
2024-02-26T17:01:13.987632919+08:00 stdout F [2024/02/26 09:01:13.987 +00:00] [DEBUG] [meta/target_manager.go:84] ["finish to update current target for collection"] [collectionID=447986647577785966] [segments="[447986647577786373,447986647577786465,447986647577786049,447986647577786330,447986647577786188,447986647577786914,447986647577786494,447986647577786277,447986647577786432,447986647577786462,447986647577786014,447986647577786428,447986647577786466,447986647577786406,447986647577786908,447986647577786470,447986647577786939,447986647577786944,447986647577786469,447986647577786435,447986647577786370,447986647577786407,447986647577786468,447986647577786935,447986647577786772,447986647577786327,447986647577786440,447986647577786909,447986647577786940,447986647577786903,447986647577786495,447986647577786023,447986647577786431,447986647577786369,447986647577786936,447986647577786853,447986647577786395,447986647577786773,447986647577786115,447986647577786913,447986647577786012,447986647577786850,447986647577786883,447986647577786020,447986647577786364,447986647577786911,447986647577786886,447986647577786015,447986647577786473,447986647577786403,447986647577786434,447986647577786777,447986647577786363,447986647577786885,447986647577786442,447986647577786394,447986647577786776,447986647577786475,447986647577786770,447986647577786397,447986647577786945,447986647577786905,447986647577786398,447986647577786366,447986647577786439,447986647577786438,447986647577786402,447986647577786050,447986647577786017,447986647577786329,447986647577786374,447986647577786857,447986647577786904,447986647577786888,447986647577786401,447986647577786535,447986647577786943,447986647577786405,447986647577786361,447986647577786775,447986647577786851,447986647577786463,447986647577786651,447986647577786937,447986647577786018,447986647577786847,447986647577786368,447986647577786472,447986647577786941,447986647577786855,447986647577786010,447986647577786022,447986647577786907,447986647577786946,447986647577786326,447986647577786372,447986647577786019,447986647577786429,447986647577786912,447986647577786047]"] [channels="[by-dev-rootcoord-dml_15_447986647577785966v0]"] [version=1708938073966769996]
```
T1:
```
2024-02-26T17:01:15.504373713+08:00 stdout F [2024/02/26 09:01:15.504 +00:00] [INFO] [querynodev2/services.go:430] ["received load segments request"] [traceID=727c96c7dc917f278d03e9442d6ecc10] [collectionID=447986647577785966] [partitionID=447986647577785969] [shard=by-dev-rootcoord-dml_15_447986647577785966v0] [segmentID=447986647577786941] [currentNodeID=1] [version=1708938075482645694] [needTransfer=true] [loadScope=Full]
2024-02-26T17:01:15.50440469+08:00 stdout F [2024/02/26 09:01:15.504 +00:00] [INFO] [segments/segment_loader.go:877] ["start loading remote..."] [traceID=727c96c7dc917f278d03e9442d6ecc10] [collectionID=447986647577785966] [segmentIDs="[447986647577786941]"] [segmentNum=1]
```



The `shouldUpdateCurrentTarget` passed the check (at that time, the next target did not yet have segment 447986647577786941). Then it attempted to execute `updateCurrentTarget`. However, before execution, the next target was manually updated through refresh load (with segment 447986647577786941), causing the current target to contain the segment that had not yet been loaded.
https://github.com/milvus-io/milvus/blob/57397b13070095666d56cea042cfd5a75d88e456/internal/querycoordv2/observers/target_observer.go#L187-L189

**Comment by yanliang567** [comment]
keep it

**Comment by bigsheeper** [comment]
/assign @zhuwenxing 
should be fixed, please help to verify
