### ISSUE TITLE
[Bug]: Failed to query: segment lacks after querynode recovered from pod-failure

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#30836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20240224-d970a9fc
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):  pulsar  
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. deploy milvus with 3 queryNodes and 2 dataNodes
```
  config:
    dataCoord:
      enableActiveStandby: true
      segment:
        enableLevelZero: true
    indexCoord:
      enableActiveStandby: true
    log:
      level: debug
    queryCoord:
      enableActiveStandby: true
    rootCoord:
      enableActiveStandby: true
    trace:
      exporter: jaeger
      jaeger:
        url: http://tempo-distributor.tempo:14268/api/traces
      sampleFraction: 1
```
2. Create collection -> index -> load -> insert 3m-128d -> flush -> index again -> load
3. concurrent requests (insert + delete + flush + search) for 10 hours starting from 2024-02-25 16:58
```
{'collection_params': {'shards_num': 2}, 'dataset_params': {'dataset_name': 'sift', 'dim': 128, 'dataset_size': '3m', 'ni_per': 50000, 'metric_type': 'L2'}, 'index_params': {'index_type': 'HNSW', 'index_param': {'M': 8, 'efConstruction': 200}}, 'load_params': {}, 'release_params': {'release_of_reload': True}, 'functional_params': {'partition_name': 'p2', 'with_flush': True, 'delete_expr_list': ['0 <= id < 100000', '100000 <= id < 200000', '200000 <= id < 500000', '500000 <= id < 600000', '600000 <= id < 1000000', '1000000 <= id < 1200000', '1200000 <= id < 1500000', '1500000 <= id < 2000000', '2000000 <= id < 2800000', '2800000 <= id < 3000000', '3000000 <= id < 3500000', '3500000 <= id < 3800000', '3800000 <= id < 4000000']}, 'concurrent_params': {'concurrent_number': 50, 'during_time': '10h', 'interval': 120}, 'concurrent_tasks': [{'type': 'search', 'weight': 3, 'params': {'nq': 100, 'random_data': True, 'top_k': 100, 'search_param': {'ef': 128}, 'timeout': 120}}, {'type': 'insert', 'weight': 3, 'params': {'nb': 100, 'start_id': 3000000, 'random_id': True, 'random_vector': True, 'timeout': 60}}, {'type': 'delete', 'weight': 3, 'params': {'delete_length': 50, 'timeout': 60}}, {'type': 'flush', 'weight': 1, 'params': {'timeout': 60}}]}
```
4. apply chaos pod-failure to all datanode and querynode at 2024-02-25 8:52, remove chaos after 10min
5. All pods are back to running, but the query/search keeps failing.
```
print(current_time)
2024-02-26 12:06:25.853213
c.query('id >=0', output_fields=["count(*)"])
RPC error: [query], <MilvusException: (code=503, message=failed to query: segment lacks[segment=447972580183162415]: channel not available[channel=chaos-delta-clu-insert-3-rootcoord-dml_1_447972580182722033v1])>, <Time:{'RPC start': '2024-02-26 20:06:36.464470', 'RPC error': '2024-02-26 20:06:36.821216'}>
Traceback (most recent call last):
  File "/home/zong/Downloads/pycharm-community-2023.2.5/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 915, in query
    return conn.query(
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/decorators.py", line 129, in handler
    raise e from e
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/decorators.py", line 125, in handler
    return func(*args, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/decorators.py", line 164, in handler
    return func(self, *args, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/decorators.py", line 104, in handler
    raise e from e
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/decorators.py", line 68, in handler
    return func(*args, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 1314, in query
    check_status(response.status)
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/client/utils.py", line 54, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=503, message=failed to query: segment lacks[segment=447972580183162415]: channel not available[channel=chaos-delta-clu-insert-3-rootcoord-dml_1_447972580182722033v1])>
```

### Milvus Log

- argo: [fouramf-chaos-delta-clu-insert-3](https://argo-workflows.zilliz.cc/archived-workflows/qa/1e431dcb-f1ee-4279-8c44-50f3ee73200f?nodeId=fouramf-chaos-delta-clu-insert-3)
- pods:
```
chaos-delta-clu-insert-3-etcd-0                                   1/1     Running            0               19h
chaos-delta-clu-insert-3-etcd-1                                   1/1     Running            0               19h
chaos-delta-clu-insert-3-etcd-2                                   1/1     Running            0               19h
chaos-delta-clu-insert-3-milvus-datanode-666c59c9db-fz2dm         1/1     Running            5 (16h ago)     18h
chaos-delta-clu-insert-3-milvus-datanode-666c59c9db-ttpm6         1/1     Running            5 (16h ago)     18h
chaos-delta-clu-insert-3-milvus-indexnode-586577996c-ppn7w        1/1     Running            0               18h
chaos-delta-clu-insert-3-milvus-indexnode-586577996c-wqc8d        1/1     Running            0               18h
chaos-delta-clu-insert-3-milvus-mixcoord-869dcfcd79-vcpbh         1/1     Running            0               18h
chaos-delta-clu-insert-3-milvus-proxy-74cdc4679-84wkb             1/1     Running            0               18h
chaos-delta-clu-insert-3-milvus-querynode-0-7bbc9f84b-7dpkc       1/1     Running            10 (10h ago)    18h
chaos-delta-clu-insert-3-milvus-querynode-0-7bbc9f84b-jfvct       1/1     Running            12 (10h ago)    18h
chaos-delta-clu-insert-3-milvus-querynode-0-7bbc9f84b-snbnd       1/1     Running            3 (14h ago)     18h
chaos-delta-clu-insert-3-minio-0                                  1/1     Running            0               19h
chaos-delta-clu-insert-3-minio-1                                  1/1     Running            0               19h
chaos-delta-clu-insert-3-minio-2                                  1/1     Running            0               19h
chaos-delta-clu-insert-3-minio-3                                  1/1     Running            0               19h
chaos-delta-clu-insert-3-pulsar-bookie-0                          1/1     Running            0               19h
chaos-delta-clu-insert-3-pulsar-bookie-1                          1/1     Running            0               19h
chaos-delta-clu-insert-3-pulsar-bookie-2                          1/1     Running            0               19h
chaos-delta-clu-insert-3-pulsar-bookie-init-spkjt                 0/1     Completed          0               19h
chaos-delta-clu-insert-3-pulsar-broker-0                          1/1     Running            0               19h
chaos-delta-clu-insert-3-pulsar-proxy-0                           1/1     Running            0               19h
chaos-delta-clu-insert-3-pulsar-pulsar-init-8p2rw                 0/1     Completed          0               19h
chaos-delta-clu-insert-3-pulsar-recovery-0                        1/1     Running            0               19h
chaos-delta-clu-insert-3-pulsar-zookeeper-0                       1/1     Running            0               19h
chaos-delta-clu-insert-3-pulsar-zookeeper-1                       1/1     Running            0               19h
chaos-delta-clu-insert-3-pulsar-zookeeper-2                       1/1     Running            0               19h
```

**Comment by weiliu1031** [comment]
please verify this with latest master image

**Comment by ThreadDao** [comment]
This cause of the problem is fixed. Problems with similar behavior but other causes are tracked in other issue
