### ISSUE TITLE
[Bug]: paniced when tencent cloud token expired

### ISSUE THREAD

**Issue by xiaocai2333** [milvus-io/milvus#30846]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master and 2.3
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
Defaulted container "standalone" out of: standalone, envoy, config (init)
panic: interface conversion: common.CredentialIface is nil, not *common.RoleArnCredential
goroutine 270552 [running]:
panic({0x4b5e8c0, 0xc0005271d0})
	/usr/local/go/src/runtime/panic.go:987 +0x3bb fp=0xc0021c4148 sp=0xc0021c4088 pc=0x1a99cdb
runtime.panicdottypeE(...)
	/usr/local/go/src/runtime/iface.go:262
runtime.panicdottypeI(0xc0021c4198?, 0x4d07f80, 0x4c19c80)
	/usr/local/go/src/runtime/iface.go:272 +0x7c fp=0xc0021c4170 sp=0xc0021c4148 pc=0x1a6a2dc
[github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common.(*RoleArnCredential).refresh(0xc001501180)](http://github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common.(*RoleArnCredential).refresh(0xc001501180))
	/go/pkg/mod/[github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common@v1.0.841/role_arn_credential.go:60](http://github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common@v1.0.841/role_arn_credential.go:60) +0xe5 fp=0xc0021c41b8 sp=0xc0021c4170 pc=0x2b799e5
[github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common.(*RoleArnCredential).GetSecretId(0xc001501180)](http://github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common.(*RoleArnCredential).GetSecretId(0xc001501180))
	/go/pkg/mod/[github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common@v1.0.841/role_arn_credential.go:21](http://github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common@v1.0.841/role_arn_credential.go:21) +0x2e fp=0xc0021c41d0 sp=0xc0021c41b8 pc=0x2b796ce
[github.com/milvus-io/milvus/internal/storage/tencent.CredentialProvider.IsExpired(...)](http://github.com/milvus-io/milvus/internal/storage/tencent.CredentialProvider.IsExpired(...))
	/go/src/[github.com/milvus-io/milvus/internal/storage/tencent/tencent.go:83](http://github.com/milvus-io/milvus/internal/storage/tencent/tencent.go:83)
[github.com/milvus-io/milvus/internal/storage/tencent.(*CredentialProvider).IsExpired(0x1000000000000?)](http://github.com/milvus-io/milvus/internal/storage/tencent.(*CredentialProvider).IsExpired(0x1000000000000?))
	<autogenerated>:1 +0x44 fp=0xc0021c4208 sp=0xc0021c41d0 pc=0x2b7b524
[github.com/minio/minio-go/v7/pkg/credentials.(*Credentials).isExpired(...)](http://github.com/minio/minio-go/v7/pkg/credentials.(*Credentials).isExpired(...))
	/go/pkg/mod/[github.com/minio/minio-go/v7@v7.0.56/pkg/credentials/credentials.go:192](http://github.com/minio/minio-go/v7@v7.0.56/pkg/credentials/credentials.go:192)
[github.com/minio/minio-go/v7/pkg/credentials.(*Credentials).Get(0xc001918840)](http://github.com/minio/minio-go/v7/pkg/credentials.(*Credentials).Get(0xc001918840))
	/go/pkg/mod/[github.com/minio/minio-go/v7@v7.0.56/pkg/credentials/credentials.go:154](http://github.com/minio/minio-go/v7@v7.0.56/pkg/credentials/credentials.go:154) +0xdb fp=0xc0021c42d0 sp=0xc0021c4208 pc=0x2adbbfb
[github.com/minio/minio-go/v7.(*Client).newRequest](http://github.com/minio/minio-go/v7.(*Client).newRequest)(0xc0007ffef0, {0x56e8c30, 0xc002483090}, {0x510ad69?, 0x3?}, {0x0, {0xc00060bee0, 0x1a}, {0x0, 0x0}, ...})
	/go/pkg/mod/[github.com/minio/minio-go/v7@v7.0.56/api.go:765](http://github.com/minio/minio-go/v7@v7.0.56/api.go:765) +0x365 fp=0xc0021c4ca8 sp=0xc0021c42d0 pc=0x2b2d9c5
[github.com/minio/minio-go/v7.(*Client).executeMethod](http://github.com/minio/minio-go/v7.(*Client).executeMethod)(0xc0007ffef0, {0x56e8c30, 0xc002483090}, {0x510ad69, 0x3}, {0x0, {0xc00060bee0, 0x1a}, {0x0, 0x0}, ...})
	/go/pkg/mod/[github.com/minio/minio-go/v7@v7.0.56/api.go:619](http://github.com/minio/minio-go/v7@v7.0.56/api.go:619) +0x7ea fp=0xc0021c5398 sp=0xc0021c4ca8 pc=0x2b2ca0a
[github.com/minio/minio-go/v7.(*Client).listObjectsV2Query](http://github.com/minio/minio-go/v7.(*Client).listObjectsV2Query)(_, {_, _}, {_, _}, {_, _}, {_, _}, 0x1, ...)
	/go/pkg/mod/[github.com/minio/minio-go/v7@v7.0.56/api-list.go:221](http://github.com/minio/minio-go/v7@v7.0.56/api-list.go:221) +0x77f fp=0xc0021c5850 sp=0xc0021c5398 pc=0x2afd67f
[github.com/minio/minio-go/v7.(*Client).listObjectsV2.func2(0xc0001edd40)](http://github.com/minio/minio-go/v7.(*Client).listObjectsV2.func2(0xc0001edd40))
	/go/pkg/mod/[github.com/minio/minio-go/v7@v7.0.56/api-list.go:105](http://github.com/minio/minio-go/v7@v7.0.56/api-list.go:105) +0x22c fp=0xc0021c5fc8 sp=0xc0021c5850 pc=0x2afc78c
[github.com/minio/minio-go/v7.(*Client).listObjectsV2.func5()](http://github.com/minio/minio-go/v7.(*Client).listObjectsV2.func5())
	/go/pkg/mod/[github.com/minio/minio-go/v7@v7.0.56/api-list.go:156](http://github.com/minio/minio-go/v7@v7.0.56/api-list.go:156) +0x2a fp=0xc0021c5fe0 sp=0xc0021c5fc8 pc=0x2afc52a
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0021c5fe8 sp=0xc0021c5fe0 pc=0x1ad3b21
created by [github.com/minio/minio-go/v7.(*Client).listObjectsV2](http://github.com/minio/minio-go/v7.(*Client).listObjectsV2)
	/go/pkg/mod/[github.com/minio/minio-go/v7@v7.0.56/api-list.go:99](http://github.com/minio/minio-go/v7@v7.0.56/api-list.go:99) +0x305
```

### Expected Behavior

update tencent cloud token successfully.

**Comment by yanliang567** [comment]
/assign @yongpengli-z 
please help to double check the verification

/unassign @xiaocai2333

**Comment by yongpengli-z** [comment]
Fixed and verified
