### ISSUE TITLE
[Bug]: [Nightly] Create index failed reporting `InvalidateCollectionMetaCache`

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#31018]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: df09222
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Create index failed reporting `InvalidateCollectionMetaCache`.

```
[2024-03-04T23:18:28.775Z] [2024-03-04 21:28:04 - DEBUG - ci_test]: (api_request)  : [Collection] args: ['index_Q1jHPmRk', {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}, {'name': 'varchar', 'description': '', 'type': <DataType.VA......, kwargs: {'consistency_level': 'Strong'} (api_request.py:62)
[2024-03-04T23:18:28.775Z] [2024-03-04 21:28:05 - ERROR - pymilvus.decorators]: RPC error: [create_collection], <MilvusException: (code=65535, message=InvalidateCollectionMetaCache failed, proxyID = 10, err = stack trace: /go/src/github.com/milvus-io/milvus/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace
[2024-03-04T23:18:28.775Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:555 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call
[2024-03-04T23:18:28.775Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:569 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall
[2024-03-04T23:18:28.775Z] /go/src/github.com/milvus-io/milvus/internal/distributed/proxy/client/client.go:89 github.com/milvus-io/milvus/internal/distributed/proxy/client.wrapGrpcCall[...]
[2024-03-04T23:18:28.775Z] /go/src/github.com/milvus-io/milvus/internal/distributed/proxy/client/client.go:122 github.com/milvus-io/milvus/internal/distributed/proxy/client.(*Client).InvalidateCollectionMetaCache
[2024-03-04T23:18:28.775Z] /go/src/github.com/milvus-io/milvus/internal/rootcoord/proxy_client_manager.go:157 github.com/milvus-io/milvus/internal/rootcoord.(*proxyClientManager).InvalidateCollectionMetaCache.func1
[2024-03-04T23:18:28.775Z] /go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 golang.org/x/sync/errgroup.(*Group).Go.func1
[2024-03-04T23:18:28.775Z] /usr/local/go/src/runtime/asm_amd64.s:1598 runtime.goexit: attempt #0: rpc error: code = Unknown desc = node not match[expectedNodeID=10][actualNodeID=12]: attempt #1: rpc error: code = Unknown desc = node not match[expectedNodeID=10][actualNodeID=12]: unrecoverable error)>, <Time:{'RPC start': '2024-03-04 21:28:04.917734', 'RPC error': '2024-03-04 21:28:05.327937'}> (decorators.py:134)
[2024-03-04T23:18:28.776Z] [2024-03-04 21:28:05 - ERROR - ci_test]: Traceback (most recent call last):
[2024-03-04T23:18:28.776Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper
[2024-03-04T23:18:28.776Z]     res = func(*args, **_kwargs)
[2024-03-04T23:18:28.776Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request
[2024-03-04T23:18:28.776Z]     return func(*arg, **kwargs)
[2024-03-04T23:18:28.776Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 147, in __init__
[2024-03-04T23:18:28.776Z]     conn.create_collection(self._name, schema, **kwargs)
[2024-03-04T23:18:28.776Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 135, in handler
[2024-03-04T23:18:28.776Z]     raise e from e
[2024-03-04T23:18:28.776Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 131, in handler
[2024-03-04T23:18:28.776Z]     return func(*args, **kwargs)
[2024-03-04T23:18:28.776Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 170, in handler
[2024-03-04T23:18:28.776Z]     return func(self, *args, **kwargs)
[2024-03-04T23:18:28.776Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 110, in handler
[2024-03-04T23:18:28.776Z]     raise e from e
[2024-03-04T23:18:28.776Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
[2024-03-04T23:18:28.776Z]     return func(*args, **kwargs)
[2024-03-04T23:18:28.776Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 304, in create_collection
[2024-03-04T23:18:28.776Z]     check_status(status)
[2024-03-04T23:18:28.776Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/utils.py", line 54, in check_status
[2024-03-04T23:18:28.776Z]     raise MilvusException(status.code, status.reason, status.error_code)
[2024-03-04T23:18:28.776Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=InvalidateCollectionMetaCache failed, proxyID = 10, err = stack trace: /go/src/github.com/milvus-io/milvus/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace
[2024-03-04T23:18:28.776Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:555 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call
[2024-03-04T23:18:28.776Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:569 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall
[2024-03-04T23:18:28.776Z] /go/src/github.com/milvus-io/milvus/internal/distributed/proxy/client/client.go:89 github.com/milvus-io/milvus/internal/distributed/proxy/client.wrapGrpcCall[...]
[2024-03-04T23:18:28.776Z] /go/src/github.com/milvus-io/milvus/internal/distributed/proxy/client/client.go:122 github.com/milvus-io/milvus/internal/distributed/proxy/client.(*Client).InvalidateCollectionMetaCache
[2024-03-04T23:18:28.776Z] /go/src/github.com/milvus-io/milvus/internal/rootcoord/proxy_client_manager.go:157 github.com/milvus-io/milvus/internal/rootcoord.(*proxyClientManager).InvalidateCollectionMetaCache.func1
[2024-03-04T23:18:28.776Z] /go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 golang.org/x/sync/errgroup.(*Group).Go.func1
[2024-03-04T23:18:28.776Z] /usr/local/go/src/runtime/asm_amd64.s:1598 runtime.goexit: attempt #0: rpc error: code = Unknown desc = node not match[expectedNodeID=10][actualNodeID=12]: attempt #1: rpc error: code = Unknown desc = node not match[expectedNodeID=10][actualNodeID=12]: unrecoverable error)>
[2024-03-04T23:18:28.776Z]  (api_request.py:45)
[2024-03-04T23:18:28.776Z] [2024-03-04 21:28:05 - ERROR - ci_test]: (api_response) : <MilvusException: (code=65535, message=InvalidateCollectionMetaCache failed, proxyID = 10, err = stack trace: /go/src/github.com/milvus-io/milvus/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace
[2024-03-04T23:18:28.776Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:555 ...... (api_request.py:46)
```

### Expected Behavior

create collection successfully

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/2.3/121/pipeline/205/
2. log: [artifacts-milvus-distributed-kafka-nightly-121-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/2.3/121/artifact/artifacts-milvus-distributed-kafka-nightly-121-pymilvus-e2e-logs.tar.gz)
3. failed time: [2024-03-04T21:28:05.751Z] [gw2] [ 16%] FAILED testcases/test_index.py::TestIndexString::test_create_index_with_same_index_name

**Comment by xiaofan-luan** [comment]
node not match[expectedNodeID=10][actualNodeID=12]: unrecoverable error

will fix that soon

**Comment by NicoYuan1986** [comment]
The issue has not reproduced for a long time. So close it first. 
I will reopen it once it occurs. 
latest image: master-20240321-09281a07-amd64
