### ISSUE TITLE
[Bug]: [Nightly] Milvus crashed with error message `Conc pool panicked`

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#31020]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 52540fe
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Milvus crashed with error message `Conc pool panicked`.
```
2024-03-05T02:46:16.375486422+08:00 stdout F [2024/03/04 18:46:16.375 +00:00] [ERROR] [conc/options.go:54] ["Conc pool panicked"] [panic="runtime error: invalid memory address or nil pointer dereference"] [stack="github.com/milvus-io/milvus/pkg/util/conc.(*poolOption).antsOptions.func1\n\t/go/src/github.com/milvus-io/milvus/pkg/util/conc/options.go:54\ngithub.com/panjf2000/ants/v2.(*goWorker).run.func1.1\n\t/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.2/worker.go:54\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:884\ngithub.com/milvus-io/milvus/pkg/util/conc.(*Pool[...]).Submit.func1.1\n\t/go/src/github.com/milvus-io/milvus/pkg/util/conc/pool.go:74\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:884\nruntime.panicmem\n\t/usr/local/go/src/runtime/panic.go:260\nruntime.sigpanic\n\t/usr/local/go/src/runtime/signal_unix.go:841\ngithub.com/milvus-io/milvus/internal/proxy.checkRangeSearchParams\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:953\ngithub.com/milvus-io/milvus/internal/proxy.parseSearchInfo\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:184\ngithub.com/milvus-io/milvus/internal/proxy.initSearchRequest\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/search_util.go:77\ngithub.com/milvus-io/milvus/internal/proxy.(*searchTask).PreExecute\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_search.go:321\ngithub.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:454\ngithub.com/milvus-io/milvus/internal/proxy.(*taskScheduler).queryLoop.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:546\ngithub.com/milvus-io/milvus/pkg/util/conc.(*Pool[...]).Submit.func1\n\t/go/src/github.com/milvus-io/milvus/pkg/util/conc/pool.go:81\ngithub.com/panjf2000/ants/v2.(*goWorker).run.func1\n\t/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.2/worker.go:67"]
2024-03-05T02:46:16.377686356+08:00 stderr F panic: runtime error: invalid memory address or nil pointer dereference [recovered]
2024-03-05T02:46:16.377701845+08:00 stderr F    panic: runtime error: invalid memory address or nil pointer dereference [recovered]
2024-03-05T02:46:16.377706967+08:00 stderr F    panic: runtime error: invalid memory address or nil pointer dereference
2024-03-05T02:46:16.377711276+08:00 stderr F [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4572659]
2024-03-05T02:46:16.377731644+08:00 stderr F
2024-03-05T02:46:16.377737772+08:00 stderr F goroutine 1758 [running]:
2024-03-05T02:46:16.37774727+08:00 stderr F panic({0x4d3be40, 0x77e5920})
2024-03-05T02:46:16.377758357+08:00 stderr F    /usr/local/go/src/runtime/panic.go:987 +0x3bb fp=0xc002640568 sp=0xc0026404a8 pc=0x1b7eddb
2024-03-05T02:46:16.377769432+08:00 stderr F github.com/milvus-io/milvus/pkg/util/conc.(*poolOption).antsOptions.func1({0x4d3be40, 0x77e5920})
2024-03-05T02:46:16.377783188+08:00 stderr F    /go/src/github.com/milvus-io/milvus/pkg/util/conc/options.go:56 +0x15b fp=0xc002640630 sp=0xc002640568 pc=0x35c45bb

```

### Expected Behavior

work normally

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/668/pipeline/287/
2. log: [artifacts-milvus-distributed-pulsar-nightly-668-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/668/artifact/artifacts-milvus-distributed-pulsar-nightly-668-pymilvus-e2e-logs.tar.gz)
3. pod information:
```
[2024-03-05T00:04:58.293Z] mdp-668-n-etcd-0                                 1/1     Running       0               6h8m    10.105.5.65    ci-node11   <none>           <none>
[2024-03-05T00:04:58.293Z] mdp-668-n-etcd-1                                 1/1     Running       0               6h8m    10.105.7.228   ci-node12   <none>           <none>
[2024-03-05T00:04:58.293Z] mdp-668-n-etcd-2                                 1/1     Running       0               6h8m    10.105.1.131   ci-node10   <none>           <none>
[2024-03-05T00:04:58.293Z] mdp-668-n-milvus-datacoord-59cbf97c6b-rgzh7      1/1     Running       0               6h8m    10.105.1.125   ci-node10   <none>           <none>
[2024-03-05T00:04:58.293Z] mdp-668-n-milvus-datanode-697565b686-h9bhb       1/1     Running       0               6h8m    10.105.5.48    ci-node11   <none>           <none>
[2024-03-05T00:04:58.293Z] mdp-668-n-milvus-datanode-697565b686-hkg6p       1/1     Running       1 (6h4m ago)    6h8m    10.105.1.119   ci-node10   <none>           <none>
[2024-03-05T00:04:58.293Z] mdp-668-n-milvus-indexcoord-5464b4b86c-q5whf     1/1     Running       0               6h8m    10.105.1.120   ci-node10   <none>           <none>
[2024-03-05T00:04:58.293Z] mdp-668-n-milvus-indexnode-56d578db97-fljp5      1/1     Running       1 (25m ago)     6h8m    10.105.1.123   ci-node10   <none>           <none>
[2024-03-05T00:04:58.293Z] mdp-668-n-milvus-indexnode-56d578db97-k85rb      1/1     Running       0               6h8m    10.105.7.215   ci-node12   <none>           <none>
[2024-03-05T00:04:58.293Z] mdp-668-n-milvus-proxy-fc7759574-j9wd7           1/1     Running       5 (5h18m ago)   6h8m    10.105.5.51    ci-node11   <none>           <none>
[2024-03-05T00:04:58.293Z] mdp-668-n-milvus-proxy-fc7759574-ssqrm           1/1     Running       4 (5h21m ago)   6h8m    10.105.7.216   ci-node12   <none>           <none>
[2024-03-05T00:04:58.293Z] mdp-668-n-milvus-querycoord-785c75bf6-lt8kp      1/1     Running       0               6h8m    10.105.7.213   ci-node12   <none>           <none>
[2024-03-05T00:04:58.293Z] mdp-668-n-milvus-querynode-8666db86bc-w6vqw      1/1     Running       0               6h8m    10.105.7.211   ci-node12   <none>           <none>
[2024-03-05T00:04:58.293Z] mdp-668-n-milvus-querynode-8666db86bc-z7kph      1/1     Running       0               6h8m    10.105.5.49    ci-node11   <none>           <none>
[2024-03-05T00:04:58.293Z] mdp-668-n-milvus-rootcoord-6864db6655-5jnnq      1/1     Running       0               6h8m    10.105.7.212   ci-node12   <none>           <none>
[2024-03-05T00:04:58.293Z] mdp-668-n-minio-6446cc767-84ljb                  1/1     Running       0               6h8m    10.105.7.227   ci-node12   <none>           <none>
[2024-03-05T00:04:58.293Z] mdp-668-n-pulsar-bookie-0                        1/1     Running       0               6h8m    10.105.5.66    ci-node11   <none>           <none>
[2024-03-05T00:04:58.293Z] mdp-668-n-pulsar-bookie-1                        1/1     Running       0               6h8m    10.105.7.233   ci-node12   <none>           <none>
[2024-03-05T00:04:58.293Z] mdp-668-n-pulsar-bookie-2                        1/1     Running       0               6h8m    10.105.1.144   ci-node10   <none>           <none>
[2024-03-05T00:04:58.293Z] mdp-668-n-pulsar-bookie-init-v7d58               0/1     Completed     0               6h8m    10.105.7.214   ci-node12   <none>           <none>
[2024-03-05T00:04:58.293Z] mdp-668-n-pulsar-broker-0                        1/1     Running       0               6h8m    10.105.7.217   ci-node12   <none>           <none>
[2024-03-05T00:04:58.293Z] mdp-668-n-pulsar-broker-1                        1/1     Running       0               6h8m    10.105.1.122   ci-node10   <none>           <none>
[2024-03-05T00:04:58.293Z] mdp-668-n-pulsar-proxy-0                         1/1     Running       0               6h8m    10.105.1.124   ci-node10   <none>           <none>
[2024-03-05T00:04:58.293Z] mdp-668-n-pulsar-pulsar-init-kncpl               0/1     Completed     0               6h8m    10.105.1.121   ci-node10   <none>           <none>
[2024-03-05T00:04:58.293Z] mdp-668-n-pulsar-recovery-0                      1/1     Running       0               6h8m    10.105.5.50    ci-node11   <none>           <none>
[2024-03-05T00:04:58.293Z] mdp-668-n-pulsar-zookeeper-0                     1/1     Running       0               6h8m    10.105.5.64    ci-node11   <none>           <none>
[2024-03-05T00:04:58.293Z] mdp-668-n-pulsar-zookeeper-1                     1/1     Running       0               6h7m    10.105.1.148   ci-node10   <none>           <none>
[2024-03-05T00:04:58.293Z] mdp-668-n-pulsar-zookeeper-2                     1/1     Running       0               6h6m    10.105.7.241   ci-node12   <none>           <none>
[2024-03-05T00:04:58.549Z] mdp-668-n-milvus-datanode-697565b686-hkg6p restarts 1, last terminateed reason is "Completed"
[2024-03-05T00:04:58.549Z] mdp-668-n-milvus-indexnode-56d578db97-fljp5 restarts 1, last terminateed reason is "Error"
[2024-03-05T00:04:58.549Z] mdp-668-n-milvus-proxy-fc7759574-j9wd7 restarts 5, last terminateed reason is "Error"
[2024-03-05T00:04:58.805Z] mdp-668-n-milvus-proxy-fc7759574-ssqrm restarts 4, last terminateed reason is "Error"
```

**Comment by xiaofan-luan** [comment]
/assign @smellthemoon 
please help on it

**Comment by NicoYuan1986** [comment]
The panic keep reproducing every day. Please help merge.

**Comment by NicoYuan1986** [comment]
The milvus has not crashed since the pr merged. 
latest image: master-20240321-09281a07-amd64
