### ISSUE TITLE
[Bug]: datacoord/standalone may crash when refresh compaction plan contains dropped segment

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#31044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: def7294
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

datacoord/standalone may crash when refresh compaction plan contains dropped segment

### Expected Behavior

datacoord shall drop invalid compaction plan instead of panicking

### Milvus Log

```
2024-03-05T17:14:36.390369974+08:00 stderr F panic: runtime error: invalid memory address or nil pointer dereference
2024-03-05T17:14:36.390393663+08:00 stderr F [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x40351f5]
2024-03-05T17:14:36.390397695+08:00 stderr F 
2024-03-05T17:14:36.390400822+08:00 stderr F goroutine 870 [running]:
2024-03-05T17:14:36.390404786+08:00 stderr F panic({0x4d404c0, 0x77ed920})
2024-03-05T17:14:36.390408322+08:00 stderr F 	/usr/local/go/src/runtime/panic.go:987 +0x3bb fp=0xc0057dbb90 sp=0xc0057dbad0 pc=0x1b80ddb
2024-03-05T17:14:36.390417376+08:00 stderr F runtime.panicmem(...)
2024-03-05T17:14:36.39042042+08:00 stderr F 	/usr/local/go/src/runtime/panic.go:260
2024-03-05T17:14:36.390422966+08:00 stderr F runtime.sigpanic()
2024-03-05T17:14:36.390425741+08:00 stderr F 	/usr/local/go/src/runtime/signal_unix.go:841 +0x37d fp=0xc0057dbbf0 sp=0xc0057dbb90 pc=0x1b990dd
2024-03-05T17:14:36.390428216+08:00 stderr F github.com/milvus-io/milvus/internal/datacoord.(*compactionPlanHandler).RefreshPlan.func1(0xc00f72b680, 0x0?)
2024-03-05T17:14:36.390430747+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/datacoord/compaction.go:310 +0x55 fp=0xc0057dbc10 sp=0xc0057dbbf0 pc=0x40351f5
2024-03-05T17:14:36.390433225+08:00 stderr F github.com/samber/lo.ForEach[...](...)
2024-03-05T17:14:36.390435625+08:00 stderr F 	/go/pkg/mod/github.com/samber/lo@v1.27.0/slice.go:82
2024-03-05T17:14:36.390438014+08:00 stderr F github.com/milvus-io/milvus/internal/datacoord.(*compactionPlanHandler).RefreshPlan(0xc0011d1b80, 0xc00cd77d80)
2024-03-05T17:14:36.390440499+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/datacoord/compaction.go:307 +0x546 fp=0xc0057dbec0 sp=0xc0057dbc10 pc=0x4034be6
2024-03-05T17:14:36.390443114+08:00 stderr F github.com/milvus-io/milvus/internal/datacoord.(*compactionPlanHandler).notifyTasks(0xc0011d1b80, {0xc01325a018, 0x1, 0xc00020f490?})
2024-03-05T17:14:36.390445611+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/datacoord/compaction.go:361 +0x75 fp=0xc0057dbf00 sp=0xc0057dbec0 pc=0x40352f5
2024-03-05T17:14:36.390452411+08:00 stderr F github.com/milvus-io/milvus/internal/datacoord.(*compactionPlanHandler).schedule(0xc0011d1b80)
2024-03-05T17:14:36.390454992+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/datacoord/compaction.go:166 +0x45 fp=0xc0057dbf30 sp=0xc0057dbf00 pc=0x4032ce5
2024-03-05T17:14:36.390457733+08:00 stderr F github.com/milvus-io/milvus/internal/datacoord.(*compactionPlanHandler).start.func2()
2024-03-05T17:14:36.390460801+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/datacoord/compaction.go:206 +0xcc fp=0xc0057dbfe0 sp=0xc0057dbf30 pc=0x40331ac
2024-03-05T17:14:36.39046337+08:00 stderr F runtime.goexit()
2024-03-05T17:14:36.390466359+08:00 stderr F 	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0057dbfe8 sp=0xc0057dbfe0 pc=0x1bbac21
2024-03-05T17:14:36.390470375+08:00 stderr F created by github.com/milvus-io/milvus/internal/datacoord.(*compactionPlanHandler).start
2024-03-05T17:14:36.390480547+08:00 stderr F 	/go/src/github.com/milvus-io/milvus/internal/datacoord/compaction.go:194 +0x10a
2024-03-05T17:14:36.390495664+08:00 stderr F 
2024-03-05T17:14:36.390500575+08:00 stderr F goroutine 1 [chan receive, 9 minutes]:
```

**Comment by XuanYang-cn** [comment]
should be fixed now
