### ISSUE TITLE
[Bug]: proxy panic: Failed to create producer xx-replicate-msg, error = ServiceNotReady

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#31066]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20240305-3c9ffded
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):  pulsar  
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. deploy milvus and pod `level-zero-mult-par-op-76-8762-milvus-proxy-6c68fd8c7b-7dpvs` is scheduled to 4am-node17
2. The k8s cluster remove 4am-node17.
3. k8s schedule a new proxy pod, but it's always panic
[proxy_t7ndc.log](https://github.com/milvus-io/milvus/files/14506681/proxy_t7ndc.log)

```
[2024/03/06 07:38:01.291 +00:00] [DEBUG] [proxy/impl.go:74] ["Proxy current state"] [StateCode=Initializing]
[2024/03/06 07:38:03.578 +00:00] [DEBUG] [config/refresher.go:71] ["etcd refreshConfigurations"] [prefix=level-zero-mult-par-op-76-8762/config] [endpoints="[level-zero-mult-par-op-76-8762-etcd.qa-milvus:2379]"]
panic: Failed to create producer level-zero-mult-par-op-76-8762-replicate-msg, error = ServiceNotReady

goroutine 251 [running]:
panic({0x4b7a520, 0xc001d07fe0})
    /usr/local/go/src/runtime/panic.go:987 +0x3bb fp=0xc001152278 sp=0xc0011521b8 pc=0x1b80ddb
github.com/milvus-io/milvus/pkg/mq/msgstream.(*mqMsgStream).AsProducer(0xc00113cc40, {0xc001509870?, 0x1, 0xc0006ff560?})
    /go/src/github.com/milvus-io/milvus/pkg/mq/msgstream/mq_msgstream.go:147 +0x219 fp=0xc001152350 sp=0xc001152278 pc=0x39818d9
github.com/milvus-io/milvus/internal/proxy.(*Proxy).Init(0xc000250c00)
    /go/src/github.com/milvus-io/milvus/internal/proxy/proxy.go:271 +0x109e fp=0xc001152dc0 sp=0xc001152350 pc=0x452f69e
github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).init(0xc00105a600)
    /go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:660 +0x35ea fp=0xc001153d38 sp=0xc001152dc0 pc=0x462faca
github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).Run(0xc00105a600)
    /go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:424 +0x56 fp=0xc001153ea0 sp=0xc001153d38 pc=0x462be76
github.com/milvus-io/milvus/cmd/components.(*Proxy).Run(0xc000089c20?)
    /go/src/github.com/milvus-io/milvus/cmd/components/proxy.go:54 +0x2e fp=0xc001153f70 sp=0xc001153ea0 pc=0x48331ae
github.com/milvus-io/milvus/cmd/roles.runComponent[...].func1()
    /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:111 +0xd9 fp=0xc001153fe0 sp=0xc001153f70 pc=0x4839bb9
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc001153fe8 sp=0xc001153fe0 pc=0x1bbac21
created by github.com/milvus-io/milvus/cmd/roles.runComponent[...]
    /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:103 +0x158
```

### Milvus Log

- argo: [level-zero-stable-9dkbz-3754421169](https://argo-workflows.zilliz.cc/archived-workflows/qa/6266c692-5bef-4428-a06f-a39f6bd51428?nodeId=level-zero-stable-9dkbz-3754421169)
- pods:
```
level-zero-mult-par-op-76-8762-etcd-0                             1/1     Running            0                 16h     10.104.25.132   4am-node30   <none>           <none>
level-zero-mult-par-op-76-8762-etcd-1                             1/1     Running            0                 16h     10.104.27.96    4am-node31   <none>           <none>
level-zero-mult-par-op-76-8762-etcd-2                             1/1     Running            0                 16h     10.104.19.207   4am-node28   <none>           <none>
level-zero-mult-par-op-76-8762-milvus-datanode-6d8bc5b44f-mdv42   1/1     Running            0                 16h     10.104.13.39    4am-node16   <none>           <none>
level-zero-mult-par-op-76-8762-milvus-datanode-6d8bc5b44f-snxjb   1/1     Running            0                 16h     10.104.23.194   4am-node27   <none>           <none>
level-zero-mult-par-op-76-8762-milvus-indexnode-7f8b9894bb6clz2   1/1     Running            0                 4h47m   10.104.14.153   4am-node18   <none>           <none>
level-zero-mult-par-op-76-8762-milvus-indexnode-7f8b9894bbrhptd   1/1     Terminating        0                 16h     10.104.12.254   4am-node17   <none>           <none>
level-zero-mult-par-op-76-8762-milvus-indexnode-7f8b9894bbz4tx9   1/1     Running            0                 16h     10.104.4.225    4am-node11   <none>           <none>
level-zero-mult-par-op-76-8762-milvus-mixcoord-79646f745d-mvwdk   1/1     Running            0                 16h     10.104.4.224    4am-node11   <none>           <none>
level-zero-mult-par-op-76-8762-milvus-proxy-6c68fd8c7b-7dpvs      1/1     Terminating        0                 16h     10.104.12.2     4am-node17   <none>           <none>
level-zero-mult-par-op-76-8762-milvus-proxy-6c68fd8c7b-t7ndc      0/1     CrashLoopBackOff   63 (2m29s ago)    4h47m   10.104.20.119   4am-node22   <none>           <none>
level-zero-mult-par-op-76-8762-milvus-querynode-0-78d6bb886jngh   1/1     Running            0                 16h     10.104.1.37     4am-node10   <none>           <none>
level-zero-mult-par-op-76-8762-milvus-querynode-0-78d6bb88hb9q2   1/1     Running            0                 16h     10.104.31.235   4am-node34   <none>           <none>
level-zero-mult-par-op-76-8762-milvus-querynode-0-78d6bb88jcj9f   1/1     Running            0                 16h     10.104.34.80    4am-node37   <none>           <none>
level-zero-mult-par-op-76-8762-minio-0                            1/1     Running            0                 16h     10.104.27.99    4am-node31   <none>           <none>
level-zero-mult-par-op-76-8762-minio-1                            1/1     Running            0                 16h     10.104.25.140   4am-node30   <none>           <none>
level-zero-mult-par-op-76-8762-minio-2                            1/1     Running            0                 16h     10.104.19.213   4am-node28   <none>           <none>
level-zero-mult-par-op-76-8762-minio-3                            1/1     Running            0                 16h     10.104.16.115   4am-node21   <none>           <none>
level-zero-mult-par-op-76-8762-pulsar-bookie-0                    1/1     Running            0                 16h     10.104.27.100   4am-node31   <none>           <none>
level-zero-mult-par-op-76-8762-pulsar-bookie-1                    1/1     Running            0                 16h     10.104.19.212   4am-node28   <none>           <none>
level-zero-mult-par-op-76-8762-pulsar-bookie-2                    1/1     Running            0                 16h     10.104.25.143   4am-node30   <none>           <none>
level-zero-mult-par-op-76-8762-pulsar-bookie-init-cj6g9           0/1     Completed          0                 16h     10.104.27.86    4am-node31   <none>           <none>
level-zero-mult-par-op-76-8762-pulsar-broker-0                    1/1     Terminating        0                 16h     10.104.12.233   4am-node17   <none>           <none>
level-zero-mult-par-op-76-8762-pulsar-proxy-0                     1/1     Running            0                 16h     10.104.1.31     4am-node10   <none>           <none>
level-zero-mult-par-op-76-8762-pulsar-pulsar-init-l4qhb           0/1     Completed          0                 16h     10.104.25.127   4am-node30   <none>           <none>
level-zero-mult-par-op-76-8762-pulsar-recovery-0                  1/1     Running            0                 16h     10.104.19.204   4am-node28   <none>           <none>
level-zero-mult-par-op-76-8762-pulsar-zookeeper-0                 1/1     Running            0                 16h     10.104.16.113   4am-node21   <none>           <none>
level-zero-mult-par-op-76-8762-pulsar-zookeeper-1                 1/1     Running            0                 16h     10.104.25.160   4am-node30   <none>           <none>
level-zero-mult-par-op-76-8762-pulsar-zookeeper-2                 1/1     Running            0                 16h     10.104.23.189   4am-node27   <none>           <none>
```

**Comment by xiaofan-luan** [comment]
milvus should not panic if pulsar is not working

**Comment by XuanYang-cn** [comment]
@xiaofan-luan 
1. According to @congqixia ,  in some cases the proxy or querynode or datanode are unable to recover from the broken pulsar client, and the recovery depends on self-panic to clear the states.
2. Retry inside proxy to hide the panic means no difference to the users, they are both unavailable, just a refinement of the error msg.
3. This sort of retry needs a full chain of errors to be throw out, according to @weiliu1031 , who has tried but failed before, is a very large and complicated change. https://github.com/milvus-io/milvus/issues/30544

I think to remove the dependency on pulsar for proxy, rootcoord, querynode, and datanode, we need to:
1. return the specific error when AsConsumer, AsProducer, dispatcher.Client.Register wrong.
2. return the specific error when Pulsar is crashed in the middle of producer and consume.
3. When meets the specific error, **turns the server into Abnormal states, refuse to service, and retry on searching for connections with pulsar instead of panic**, clear out the broken client.

Luckly for Proxy, we only need to edit the produce and producer side.

**Comment by xiaofan-luan** [comment]
1. for all the nodes, things might be easy to do, since we only need to throw errors out and let coordinator handle this.
2. for coordinators, especially root coord, we might only be able to do lazy load. which means if pulsar/kafka is not responsible, we will retry for a piece

**Comment by xiaofan-luan** [comment]
> 1. for all the nodes, things might be easy to do, since we only need to throw errors out and let coordinator handle this.
> 2. for coordinators, especially root coord, we might only be able to do lazy load. which means if pulsar/kafka is not responsible, we will retry until it recovered

**Comment by XuanYang-cn** [comment]
doesn't blocking 2.4.0

**Comment by yanliang567** [comment]
keep it

**Comment by XuanYang-cn** [comment]
keep it

**Comment by yanliang567** [comment]
let's keep it active
