### ISSUE TITLE
[Bug]: Milvus crashed with panic "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#31081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-latest
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):  kafka  
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Milvus crashed with panic "invalid memory address or nil pointer dereference"

```
2024-03-06T18:43:30.57376954+08:00 stdout F [2024/03/06 10:43:30.573 +00:00] [WARN] [proxy/impl.go:1828] ["CreateIndex failed to WaitToFinish"] [traceID=d4fb78ce72a5714a37fc2d4d42e3549f] [role=proxy] [db=default] [collection=index_TK5bYZbr] [field=float_vector] [extra_params="[{\"key\":\"index_type\",\"value\":\"IVF_SQ8\"},{\"key\":\"metric_type\",\"value\":\"COSINE\"},{\"key\":\"params\",\"value\":\"{\\\"nlist\\\":64}\"}]"] [error="proxy TaskCondition context Done: context canceled"] [errorVerbose="proxy TaskCondition context Done: context canceled\n(1) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus/internal/proxy.(*TaskCondition).WaitToFinish\n  | \t/go/src/github.com/milvus-io/milvus/internal/proxy/condition.go:45\n  | github.com/milvus-io/milvus/internal/proxy.(*Proxy).CreateIndex\n  | \t/go/src/github.com/milvus-io/milvus/internal/proxy/impl.go:1827\n  | github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).CreateIndex\n  | \t/go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:859\n  | github.com/milvus-io/milvus-proto/go-api/v2/milvuspb._MilvusService_CreateIndex_Handler.func1\n  | \t/go/pkg/mod/github.com/milvus-io/milvus-proto/go-api/v2@v2.3.4-0.20240228061649-a922b16f2a46/milvuspb/milvus.pb.go:12255\n  | github.com/milvus-io/milvus/internal/proxy/connection.KeepActiveInterceptor\n  | \t/go/src/github.com/milvus-io/milvus/internal/proxy/connection/util.go:60\n  | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n  | \t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\n  | github.com/milvus-io/milvus/internal/proxy.TraceLogInterceptor\n  | \t/go/src/github.com/milvus-io/milvus/internal/proxy/trace_log_interceptor.go:36\n  | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n  | \t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\n  | github.com/milvus-io/milvus/internal/proxy/accesslog.UnaryUpdateAccessInfoInterceptor\n  | \t/go/src/github.com/milvus-io/milvus/internal/proxy/accesslog/util.go:47\n  | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n  | \t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\n  | github.com/milvus-io/milvus/internal/proxy.RateLimitInterceptor.func1\n  | \t/go/src/github.com/milvus-io/milvus/internal/proxy/rate_limit_interceptor.go:55\n  | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n  | \t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\n  | github.com/milvus-io/milvus/pkg/util/logutil.UnaryTraceLoggerInterceptor\n  | \t/go/src/github.com/milvus-io/milvus/pkg/util/logutil/grpc_interceptor.go:23\n  | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n  | \t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\n  | github.com/milvus-io/milvus/internal/proxy.UnaryServerInterceptor.func1\n  | \t/go/src/github.com/milvus-io/milvus/internal/proxy/privilege_interceptor.go:82\n  | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n  | \t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\n  | github.com/milvus-io/milvus/internal/proxy.UnaryServerHookInterceptor.func1\n  | \t/go/src/github.com/milvus-io/milvus/internal/proxy/hook_interceptor.go:118\n  | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n  | \t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\n  | github.com/milvus-io/milvus/internal/proxy.DatabaseInterceptor.func1\n  | \t/go/src/github.com/milvus-io/milvus/internal/proxy/database_interceptor.go:15\n  | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n  | \t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\n  | github.com/grpc-ecosystem/go-grpc-middleware/auth.UnaryServerInterceptor.func1\n  | \t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/auth/auth.go:47\n  | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n  | \t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\n  | go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryServerInterceptor.func1\n  | \t/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.38.0/interceptor.go:342\n  | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n  | \t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\n  | github.com/milvus-io/milvus/internal/proxy/accesslog.UnaryAccessLogInterceptor\n  | \t/go/src/github.com/milvus-io/milvus/internal/proxy/accesslog/util.go:38\n  | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n  | \t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\n  | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1\n  | \t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34\n  | github.com/milvus-io/milvus-proto/go-api/v2/milvuspb._MilvusService_CreateIndex_Handler\n  | \t/go/pkg/mod/github.com/milvus-io/milvus-proto/go-api/v2@v2.3.4-0.20240228061649-a922b16f2a46/milvuspb/milvus.pb.go:12257\n  | google.golang.org/grpc.(*Server).processUnaryRPC\n  | \t/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:1360\n  | google.golang.org/grpc.(*Server).handleStream\n  | \t/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:1737\n  | google.golang.org/grpc.(*Server).serveStreams.func1.1\n  | \t/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:982\n  | runtime.goexit\n  | \t/usr/local/go/src/runtime/asm_amd64.s:1598\nWraps: (2) proxy TaskCondition context Done\nWraps: (3) context canceled\nError types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *errors.errorString"] [BeginTs=448193314300887043] [EndTs=448193314300887043]
2024-03-06T18:43:30.573796261+08:00 stdout F [2024/03/06 10:43:30.573 +00:00] [WARN] [grpcclient/client.go:556] ["ClientBase Call grpc call get error"] [traceID=d4fb78ce72a5714a37fc2d4d42e3549f] [role=datacoord] [address=10.104.24.181:13333] [error="stack trace: /go/src/github.com/milvus-io/milvus/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:555 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:569 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:107 github.com/milvus-io/milvus/internal/distributed/datacoord/client.wrapGrpcCall[...]\n/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:570 github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).CreateIndex.func1\n/go/src/github.com/milvus-io/milvus/pkg/util/retry/retry.go:44 github.com/milvus-io/milvus/pkg/util/retry.Do\n/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:568 github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).CreateIndex\n/go/src/github.com/milvus-io/milvus/internal/proxy/task_index.go:423 github.com/milvus-io/milvus/internal/proxy.(*createIndexTask).Execute\n/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:466 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask\n/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:493 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop: rpc error: code = Canceled desc = context canceled"] [errorVerbose="stack trace: /go/src/github.com/milvus-io/milvus/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace: rpc error: code = Canceled desc = context canceled\n(1) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call\n  | \t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:555\n  | github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n  | \t/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:569\n  | github.com/milvus-io/milvus/internal/distributed/datacoord/client.wrapGrpcCall[...]\n  | \t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:107\n  | github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).CreateIndex.func1\n  | \t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:570\n  | github.com/milvus-io/milvus/pkg/util/retry.Do\n  | \t/go/src/github.com/milvus-io/milvus/pkg/util/retry/retry.go:44\n  | github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).CreateIndex\n  | \t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:568\n  | github.com/milvus-io/milvus/internal/proxy.(*createIndexTask).Execute\n  | \t/go/src/github.com/milvus-io/milvus/internal/proxy/task_index.go:423\n  | github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask\n  | \t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:466\n  | github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop\n  | \t/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:493\n  | runtime.goexit\n  | \t/usr/local/go/src/runtime/asm_amd64.s:1598\nWraps: (2) stack trace: /go/src/github.com/milvus-io/milvus/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace\n  | /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:555 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call\n  | /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:569 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n  | /go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:107 github.com/milvus-io/milvus/internal/distributed/datacoord/client.wrapGrpcCall[...]\n  | /go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:570 github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).CreateIndex.func1\n  | /go/src/github.com/milvus-io/milvus/pkg/util/retry/retry.go:44 github.com/milvus-io/milvus/pkg/util/retry.Do\n  | /go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:568 github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).CreateIndex\n  | /go/src/github.com/milvus-io/milvus/internal/proxy/task_index.go:423 github.com/milvus-io/milvus/internal/proxy.(*createIndexTask).Execute\n  | /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:466 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask\n  | /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:493 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop\nWraps: (3) rpc error: code = Canceled desc = context canceled\nError types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *status.Error"]
2024-03-06T18:43:30.577142984+08:00 stderr F panic: runtime error: invalid memory address or nil pointer dereference
2024-03-06T18:43:30.577163811+08:00 stderr F [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x45602c5]
2024-03-06T18:43:30.577167072+08:00 stderr F
2024-03-06T18:43:30.577170097+08:00 stderr F goroutine 1062 [running]:
2024-03-06T18:43:30.577172597+08:00 stderr F panic({0x4d44580, 0x77f3920})
2024-03-06T18:43:30.577176987+08:00 stderr F    /usr/local/go/src/runtime/panic.go:987 +0x3bb fp=0xc00f4699e0 sp=0xc00f469920 pc=0x1b81ddb
2024-03-06T18:43:30.577181366+08:00 stderr F runtime.panicmem(...)
2024-03-06T18:43:30.577184125+08:00 stderr F    /usr/local/go/src/runtime/panic.go:260
2024-03-06T18:43:30.577187249+08:00 stderr F runtime.sigpanic()
2024-03-06T18:43:30.5771901+08:00 stderr F      /usr/local/go/src/runtime/signal_unix.go:841 +0x37d fp=0xc00f469a40 sp=0xc00f4699e0 pc=0x1b9a0dd
2024-03-06T18:43:30.577193634+08:00 stderr F github.com/milvus-io/milvus/internal/proxy.(*createIndexTask).Execute(0xc004b020c0, {0x5958bb8, 0xc011fadd40})
2024-03-06T18:43:30.577197642+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/proxy/task_index.go:427 +0x805 fp=0xc00f469cf8 sp=0xc00f469a40 pc=0x45602c5
2024-03-06T18:43:30.577201816+08:00 stderr F github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask(0xc001cb4a00?, {0x599d510, 0xc004b020c0}, {0x5981640, 0xc00245bf40})
2024-03-06T18:43:30.577206442+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:466 +0x443 fp=0xc00f469f40 sp=0xc00f469cf8 pc=0x4570de3
2024-03-06T18:43:30.577209901+08:00 stderr F github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).definitionLoop(0xc001c7bce0)
2024-03-06T18:43:30.577216529+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:493 +0x116 fp=0xc00f469fc8 sp=0xc00f469f40 pc=0x4571536
2024-03-06T18:43:30.577221107+08:00 stderr F github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).Start.func1()
2024-03-06T18:43:30.577226458+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:558 +0x26 fp=0xc00f469fe0 sp=0xc00f469fc8 pc=0x45720c6
2024-03-06T18:43:30.577229198+08:00 stderr F runtime.goexit()
2024-03-06T18:43:30.577232751+08:00 stderr F    /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00f469fe8 sp=0xc00f469fe0 pc=0x1bbbc21
2024-03-06T18:43:30.577236422+08:00 stderr F created by github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).Start
2024-03-06T18:43:30.577240196+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:558 +0x76
2024-03-06T18:43:30.577249252+08:00 stderr F
2024-03-06T18:43:30.57725283+08:00 stderr F goroutine 1 [chan receive, 22 minutes]:
2024-03-06T18:43:30.577256645+08:00 stderr F runtime.gopark(0xc001f3cbf0?, 0x4b7e5e0?, 0xe0?, 0xcb?, 0xc000635788?)
2024-03-06T18:43:30.577263061+08:00 stderr F    /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc0028c1730 sp=0xc0028c1710 pc=0x1b85356
2024-03-06T18:43:30.577266707+08:00 stderr F runtime.chanrecv(0xc0003b28a0, 0x0, 0x1)
2024-03-06T18:43:30.577271699+08:00 stderr F    /usr/local/go/src/runtime/chan.go:583 +0x49d fp=0xc0028c17c0 sp=0xc0028c1730 pc=0x1b4d6fd
2024-03-06T18:43:30.577277077+08:00 stderr F runtime.chanrecv1(0xc001403680?, 0x5958b10?)
2024-03-06T18:43:30.577282247+08:00 stderr F    /usr/local/go/src/runtime/chan.go:442 +0x18 fp=0xc0028c17e8 sp=0xc0028c17c0 pc=0x1b4d1f8
2024-03-06T18:43:30.577285454+08:00 stderr F github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run(0xc0013dd810)
2024-03-06T18:43:30.57728938+08:00 stderr F     /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:399 +0xa85 fp=0xc0028c1c78 sp=0xc0028c17e8 pc=0x483cd65
2024-03-06T18:43:30.577304229+08:00 stderr F github.com/milvus-io/milvus/cmd/milvus.(*run).execute(0x0?, {0xc000052180?, 0x3, 0x3}, 0xc0004cde60)
2024-03-06T18:43:30.577310316+08:00 stderr F    /go/src/github.com/milvus-io/milvus/cmd/milvus/run.go:47 +0x2e5 fp=0xc0028c1d48 sp=0xc0028c1c78 pc=0x4847bc5
2024-03-06T18:43:30.577313368+08:00 stderr F github.com/milvus-io/milvus/cmd/milvus.RunMilvus({0xc000052180?, 0x3, 0x3})
2024-03-06T18:43:30.577317445+08:00 stderr F    /go/src/github.com/milvus-io/milvus/cmd/milvus/milvus.go:60 +0x20e fp=0xc0028c1dc0 sp=0xc0028c1d48 pc=0x484784e
2024-03-06T18:43:30.577320171+08:00 stderr F main.main()
2024-03-06T18:43:30.577323002+08:00 stderr F    /go/src/github.com/milvus-io/milvus/cmd/main.go:95 +0x3e5 fp=0xc0028c1f80 sp=0xc0028c1dc0 pc=0x484c585
2024-03-06T18:43:30.577328713+08:00 stderr F runtime.main()
2024-03-06T18:43:30.577334178+08:00 stderr F    /usr/local/go/src/runtime/proc.go:250 +0x207 fp=0xc0028c1fe0 sp=0xc0028c1f80 pc=0x1b84f27
2024-03-06T18:43:30.577336599+08:00 stderr F runtime.goexit()
2024-03-06T18:43:30.577340061+08:00 stderr F    /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0028c1fe8 sp=0xc0028c1fe0 pc=0x1bbbc21
2024-03-06T18:43:30.577343667+08:00 stderr F
2024-03-06T18:43:30.57734806+08:00 stderr F goroutine 2 [force gc (idle), 22 minutes]:
2024-03-06T18:43:30.577351801+08:00 stderr F runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
2024-03-06T18:43:30.577355867+08:00 stderr F    /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000112fb0 sp=0xc000112f90 pc=0x1b85356
2024-03-06T18:43:30.577360683+08:00 stderr F runtime.goparkunlock(...)
2024-03-06T18:43:30.577364653+08:00 stderr F    /usr/local/go/src/runtime/proc.go:387
2024-03-06T18:43:30.577368586+08:00 stderr F runtime.forcegchelper()
2024-03-06T18:43:30.577372831+08:00 stderr F    /usr/local/go/src/runtime/proc.go:305 +0xb0 fp=0xc000112fe0 sp=0xc000112fb0 pc=0x1b85190
2024-03-06T18:43:30.577378401+08:00 stderr F runtime.goexit()
2024-03-06T18:43:30.577381026+08:00 stderr F    /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000112fe8 sp=0xc000112fe0 pc=0x1bbbc21
2024-03-06T18:43:30.577384801+08:00 stderr F created by runtime.init.6
2024-03-06T18:43:30.577390965+08:00 stderr F    /usr/local/go/src/runtime/proc.go:293 +0x25
...
```

### Expected Behavior

No crash

### Steps To Reproduce

Running CI:

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-31079/1/pipeline

### Milvus Log

[artifacts-milvus-standalone-kafka-PR-31079-1-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20HA%20CI/job/PR-31079/1/artifact/artifacts-milvus-standalone-kafka-PR-31079-1-pymilvus-e2e-logs.tar.gz)

**Comment by xiaocai2333** [comment]
Quite strange, it seems that in the event of context canceled, the err is nil.

**Comment by xiaocai2333** [comment]
fixed by #31077 ， please verify it.

**Comment by binbinlv** [comment]
This panic is triggered when I running CI, and it is not reproduced steadily with no obvious failed cases, any conditions that I could trigger it manually? @xiaocai2333 
If not, I will observe the CI for several days, and will close it if no similar panic again. And will reopen it if it occurs again in the future.

**Comment by xiaocai2333** [comment]
@binbinlv There is no reliable method for stable reproduction, but there are ways to improve the probability of reproduction, as follows:

```
collection.create_index("embeddings", index_params, _async=True)
```

This way of writing will cause the request context to be canceled, but it cannot guarantee the execution is in the datacoord's RPC method. If assurance is needed, some special logic needs to be added to the code, such as time.sleep.

**Comment by yanliang567** [comment]
@binbinlv please help to close the issue if not repro recently

**Comment by binbinlv** [comment]
Close this for not repro recently, and will reopen it if it occurs again in the future.
