### ISSUE TITLE
[Bug]: [CI] Fail to search reporting `channel lacks[channel=channel not subscribed]`

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#31099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 7263469
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Fail to search reporting `channel lacks[channel=channel not subscribed]`.
```
[2024-03-07T03:44:25.145Z] [2024-03-07 03:44:11 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[b'\xa89\xf69@73:\x956\xe2:\x95:\xf09S6\xba8\xba0\x0c9\xe1-\x9c;\xbe.R9;:\xf67\\8\xf75m*\x938\xbc,\xb48L9\xd1.];I1\x040\xd56\xfb8\xaa2', b'\xa85\xae2\xd60":\xf17n4T:1:p-v8d4+2\xca"\xc54\xa7;f:\x7f7\x85\x1f\n7"8z5\xa0(!4<;\xe1\x1b\x19;\xae4{9\xd16f:"8\x899', b"\x9f,J6\x1d8w9\xe89s9\xd8:\xdb:Z2\xe34\......, kwargs: {'guarantee_timestamp': 0} (api_request.py:62)
[2024-03-07T03:44:25.145Z] [2024-03-07 03:44:11 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=503, message=failed to search: channel lacks[channel=channel not subscribed]: channel not available[channel=by-dev-rootcoord-dml_7_448209016220535333v0])>, <Time:{'RPC start': '2024-03-07 03:44:11.650072', 'RPC error': '2024-03-07 03:44:11.678092'}> (decorators.py:134)
[2024-03-07T03:44:25.145Z] [2024-03-07 03:44:11 - ERROR - ci_test]: Traceback (most recent call last):
[2024-03-07T03:44:25.145Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper
[2024-03-07T03:44:25.145Z]     res = func(*args, **_kwargs)
[2024-03-07T03:44:25.145Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request
[2024-03-07T03:44:25.145Z]     return func(*arg, **kwargs)
[2024-03-07T03:44:25.145Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 792, in search
[2024-03-07T03:44:25.145Z]     resp = conn.search(
[2024-03-07T03:44:25.145Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 135, in handler
[2024-03-07T03:44:25.145Z]     raise e from e
[2024-03-07T03:44:25.145Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 131, in handler
[2024-03-07T03:44:25.145Z]     return func(*args, **kwargs)
[2024-03-07T03:44:25.145Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 170, in handler
[2024-03-07T03:44:25.145Z]     return func(self, *args, **kwargs)
[2024-03-07T03:44:25.145Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 110, in handler
[2024-03-07T03:44:25.145Z]     raise e from e
[2024-03-07T03:44:25.145Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
[2024-03-07T03:44:25.145Z]     return func(*args, **kwargs)
[2024-03-07T03:44:25.145Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 794, in search
[2024-03-07T03:44:25.145Z]     return self._execute_search(request, timeout, round_decimal=round_decimal, **kwargs)
[2024-03-07T03:44:25.145Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 735, in _execute_search
[2024-03-07T03:44:25.145Z]     raise e from e
[2024-03-07T03:44:25.145Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 728, in _execute_search
[2024-03-07T03:44:25.145Z]     check_status(response.status)
[2024-03-07T03:44:25.145Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/utils.py", line 60, in check_status
[2024-03-07T03:44:25.145Z]     raise MilvusException(status.code, status.reason, status.error_code)
[2024-03-07T03:44:25.145Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=503, message=failed to search: channel lacks[channel=channel not subscribed]: channel not available[channel=by-dev-rootcoord-dml_7_448209016220535333v0])>
[2024-03-07T03:44:25.145Z]  (api_request.py:45)
[2024-03-07T03:44:25.145Z] [2024-03-07 03:44:11 - ERROR - ci_test]: (api_response) : <MilvusException: (code=503, message=failed to search: channel lacks[channel=channel not subscribed]: channel not available[channel=by-dev-rootcoord-dml_7_448209016220535333v0])> (api_request.py:46)
```

### Expected Behavior

search successfully

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-29522/5/pipeline
2. log: [artifacts-milvus-standalone-kafka-PR-29522-5-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20HA%20CI/job/PR-29522/5/artifact/artifacts-milvus-standalone-kafka-PR-29522-5-pymilvus-e2e-logs.tar.gz)

**Comment by congqixia** [comment]
Standalone restarted during e2e cases
```
[2024/03/07 03:44:13.005 +00:00] [ERROR] [querycoordv2/server.go:152] ["QueryCoord disconnected from etcd, process will exit"] [serverID=1] [stack="github.com/milvus-io/milvus/internal/querycoordv2.(*Server).Register.func1\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/server.go:152"]
```
shall merge with disconnect with etcd issue
/assign @NicoYuan1986

**Comment by NicoYuan1986** [comment]
The issue does not occur for a long time.
