### ISSUE TITLE
[Bug]: QN panic at forward streaming delete

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#31125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

It seems when querynode load segments, pk's type is messed up.
```
 670647 2024-03-07T17:58:10.914314523+08:00 stdout F [2024/03/07 09:58:10.914 +00:00] [WARN] [storage/primary_key.go:232] ["type of compared pk is not varChar"]
 670648 2024-03-07T17:58:10.914317775+08:00 stdout F [2024/03/07 09:58:10.914 +00:00] [WARN] [storage/primary_key.go:252] ["type of compared pk is not varChar"]
 670649 2024-03-07T17:58:10.914321122+08:00 stdout F [2024/03/07 09:58:10.914 +00:00] [WARN] [storage/primary_key.go:232] ["type of compared pk is not varChar"]
 670650 2024-03-07T17:58:10.91432467+08:00 stdout F [2024/03/07 09:58:10.914 +00:00] [WARN] [storage/primary_key.go:252] ["type of compared pk is not varChar"]
 670651 2024-03-07T17:58:10.914328504+08:00 stdout F [2024/03/07 09:58:10.914 +00:00] [WARN] [storage/primary_key.go:232] ["type of compared pk is not varChar"]
 670652 2024-03-07T17:58:10.91434278+08:00 stdout F [2024/03/07 09:58:10.914 +00:00] [WARN] [storage/primary_key.go:252] ["type of compared pk is not varChar"]
 670653 2024-03-07T17:58:10.914346014+08:00 stdout F [2024/03/07 09:58:10.914 +00:00] [WARN] [storage/primary_key.go:232] ["type of compared pk is not varChar"]
 670654 2024-03-07T17:58:10.914349782+08:00 stdout F [2024/03/07 09:58:10.914 +00:00] [WARN] [storage/primary_key.go:252] ["type of compared pk is not varChar"]
 670655 2024-03-07T17:58:10.914352789+08:00 stdout F [2024/03/07 09:58:10.914 +00:00] [WARN] [storage/primary_key.go:232] ["type of compared pk is not varChar"]
 670656 2024-03-07T17:58:10.914364703+08:00 stdout F [2024/03/07 09:58:10.914 +00:00] [WARN] [storage/primary_key.go:252] ["type of compared pk is not varChar"]
 670657 2024-03-07T17:58:10.914370515+08:00 stdout F [2024/03/07 09:58:10.914 +00:00] [WARN] [storage/primary_key.go:232] ["type of compared pk is not varChar"]
 670658 2024-03-07T17:58:10.914387499+08:00 stdout F [2024/03/07 09:58:10.914 +00:00] [WARN] [storage/primary_key.go:252] ["type of compared pk is not varChar"]
 670659 2024-03-07T17:58:10.914392266+08:00 stdout F [2024/03/07 09:58:10.914 +00:00] [WARN] [storage/primary_key.go:232] ["type of compared pk is not varChar"]
 670660 2024-03-07T17:58:10.914394542+08:00 stdout F [2024/03/07 09:58:10.914 +00:00] [WARN] [storage/primary_key.go:252] ["type of compared pk is not varChar"]
 670661 2024-03-07T17:58:10.914396834+08:00 stdout F [2024/03/07 09:58:10.914 +00:00] [WARN] [storage/primary_key.go:232] ["type of compared pk is not varChar"]
 670662 2024-03-07T17:58:10.914398814+08:00 stdout F [2024/03/07 09:58:10.914 +00:00] [WARN] [storage/primary_key.go:252] ["type of compared pk is not varChar"]
 670663 2024-03-07T17:58:10.914401252+08:00 stdout F [2024/03/07 09:58:10.914 +00:00] [WARN] [storage/primary_key.go:232] ["type of compared pk is not varChar"]
 670664 2024-03-07T17:58:10.914403288+08:00 stdout F [2024/03/07 09:58:10.914 +00:00] [WARN] [storage/primary_key.go:252] ["type of compared pk is not varChar"]
 670665 2024-03-07T17:58:10.914410316+08:00 stdout F [2024/03/07 09:58:10.914 +00:00] [INFO] [delegator/delegator_data.go:610] ["forward L0 delete to worker..."] [traceID=ca9c24884684a9b26fc26166c2d4dad4] [collectionID=448215043994025136] [channel=by-dev-rootcoord-dml_15_448215043994025136v0] 
 670665 [replicaID=448215044148429394] [segmentID=448215043994025147] [deleteRowNum=2]
 670666 2024-03-07T17:58:10.916514096+08:00 stderr F panic: interface conversion: storage.PrimaryKey is *storage.VarCharPrimaryKey, not *storage.Int64PrimaryKey
 670667 2024-03-07T17:58:10.91652372+08:00 stderr F 
 670668 2024-03-07T17:58:10.916526666+08:00 stderr F goroutine 401367 [running]:
 670669 2024-03-07T17:58:10.916528979+08:00 stderr F panic({0x4d70080, 0xc00d692120})
 670670 2024-03-07T17:58:10.916531582+08:00 stderr F    /usr/local/go/src/runtime/panic.go:987 +0x3bb fp=0xc004f86420 sp=0xc004f86360 pc=0x1b81ddb
 670671 2024-03-07T17:58:10.916534005+08:00 stderr F runtime.panicdottypeE(...)
 670672 2024-03-07T17:58:10.916536312+08:00 stderr F    /usr/local/go/src/runtime/iface.go:262
 670673 2024-03-07T17:58:10.916538307+08:00 stderr F runtime.panicdottypeI(0x79888d0?, 0x50b1840, 0x4fca1c0)
 670674 2024-03-07T17:58:10.916540805+08:00 stderr F    /usr/local/go/src/runtime/iface.go:272 +0x7c fp=0xc004f86448 sp=0xc004f86420 pc=0x1b523dc
 670675 2024-03-07T17:58:10.91654827+08:00 stderr F github.com/milvus-io/milvus/internal/storage.ParsePrimaryKeys2IDs({0xc000517e00, 0x2, 0xc0053033e0?})
 670676 2024-03-07T17:58:10.916551754+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/storage/primary_key.go:390 +0x25b fp=0xc004f86508 sp=0xc004f86448 pc=0x39c7bfb
 670677 2024-03-07T17:58:10.916558354+08:00 stderr F github.com/milvus-io/milvus/internal/querynodev2/delegator.(*shardDelegator).loadStreamDelete(0xc008f779e0, {0x5958cd8, 0xc001c46ed0}, {0xc011b7afd8, 0x1, 0x1}, {0xc011da88f8, 0x1, 0xc0001940c0?}, {0xc011da88c0, ...}, ...)
 670678 2024-03-07T17:58:10.916561594+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/querynodev2/delegator/delegator_data.go:618 +0x525 fp=0xc004f86a98 sp=0xc004f86508 pc=0x4745e85
 670679 2024-03-07T17:58:10.916564095+08:00 stderr F github.com/milvus-io/milvus/internal/querynodev2/delegator.(*shardDelegator).LoadSegments(0xc008f779e0, {0x5958cd8, 0xc001c46ed0}, 0xc007eba300)
 670680 2024-03-07T17:58:10.916576472+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/querynodev2/delegator/delegator_data.go:465 +0xbe7 fp=0xc004f86f40 sp=0xc004f86a98 pc=0x4743e07
 670681 2024-03-07T17:58:10.916585004+08:00 stderr F github.com/milvus-io/milvus/internal/querynodev2.(*QueryNode).LoadSegments(0xc0016143c0, {0x5958cd8, 0xc001c46ed0}, 0xc007eba300)
 670682 2024-03-07T17:58:10.916587737+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/querynodev2/services.go:462 +0x96d fp=0xc004f873f8 sp=0xc004f86f40 pc=0x4776a2d
 670683 2024-03-07T17:58:10.916594184+08:00 stderr F github.com/milvus-io/milvus/internal/distributed/querynode.(*Server).LoadSegments(0xc00561d368?, {0x5958cd8?, 0xc001c46ed0?}, 0xc004c2e5a8?)
 670684 2024-03-07T17:58:10.916596452+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/distributed/querynode/service.go:298 +0x2e fp=0xc004f87428 sp=0xc004f873f8 pc=0x479116e
 670685 2024-03-07T17:58:10.916601791+08:00 stderr F github.com/milvus-io/milvus/internal/proto/querypb._QueryNode_LoadSegments_Handler.func1({0x5958cd8, 0xc001c46ed0}, {0x51eb480?, 0xc007eba300})
 670686 2024-03-07T17:58:10.916604522+08:00 stderr F    /go/src/github.com/milvus-io/milvus/internal/proto/querypb/query_coord.pb.go:6929 +0x78 fp=0xc004f87468 sp=0xc004f87428 pc=0x2a78e98
 670687 2024-03-07T17:58:10.91661076+08:00 stderr F github.com/milvus-io/milvus/pkg/util/interceptor.ServerIDValidationUnaryServerInterceptor.func1({0x5958cd8, 0xc001c46ed0}, {0x51eb480, 0xc007eba300}, 0x7?, 0xc0091e24e0)
 670688 2024-03-07T17:58:10.916617375+08:00 stderr F    /go/src/github.com/milvus-io/milvus/pkg/util/interceptor/server_id_interceptor.go:54 +0x102 fp=0xc004f874b8 sp=0xc004f87468 pc=0x3dbc8e2
 670689 2024-03-07T17:58:10.916624423+08:00 stderr F github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x5958cd8?, 0xc001c46ed0?}, {0x51eb480?, 0xc007eba300?})
 670690 2024-03-07T17:58:10.916630266+08:00 stderr F    /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a fp=0xc004f874f8 sp=0xc004f874b8 pc=0x273a41a
 670691 2024-03-07T17:58:10.916637813+08:00 stderr F github.com/milvus-io/milvus/pkg/util/interceptor.ClusterValidationUnaryServerInterceptor.func1({0x5958cd8, 0xc001c46ed0}, {0x51eb480, 0xc007eba300}, 0x0?, 0xc0049e5a60)
 670692 2024-03-07T17:58:10.916644453+08:00 stderr F    /go/src/github.com/milvus-io/milvus/pkg/util/interceptor/cluster_interceptor.go:48 +0xf3 fp=0xc004f87558 sp=0xc004f874f8 pc=0x3dbd653
 670693 2024-03-07T17:58:10.916653292+08:00 stderr F github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x5958cd8?, 0xc001c46ed0?}, {0x51eb480?, 0xc007eba300?})
 670694 2024-03-07T17:58:10.91666145+08:00 stderr F     /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a fp=0xc004f87598 sp=0xc004f87558 pc=0x273a41a
 670695 2024-03-07T17:58:10.91666908+08:00 stderr F github.com/milvus-io/milvus/pkg/util/logutil.UnaryTraceLoggerInterceptor({0x5958cd8?, 0xc001c46e40?}, {0x51eb480, 0xc007eba300}, 0xc00a12f5f8?, 0xc0049e5a80)
 670696 2024-03-07T17:58:10.916677414+08:00 stderr F    /go/src/github.com/milvus-io/milvus/pkg/util/logutil/grpc_interceptor.go:23 +0x49 fp=0xc004f875c8 sp=0xc004f87598 pc=0x3a0c789
 670697 2024-03-07T17:58:10.91668295+08:00 stderr F github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x5958cd8?, 0xc001c46e40?}, {0x51eb480?, 0xc007eba300?})
 670698 2024-03-07T17:58:10.916691723+08:00 stderr F    /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a fp=0xc004f87608 sp=0xc004f875c8 pc=0x273a41a
 670699 2024-03-07T17:58:10.916702473+08:00 stderr F go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryServerInterceptor.func1({0x5958cd8, 0xc001c46c90}, {0x51eb480, 0xc007eba300}, 0xc0049e5a20, 0xc0049e5aa0)
 670700 2024-03-07T17:58:10.916706258+08:00 stderr F    /go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.38.0/interceptor.go:342 +0x528 fp=0xc004f87978 sp=0xc004f87608 pc=0x2438408
 670701 2024-03-07T17:58:10.916711604+08:00 stderr F github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x5958cd8?, 0xc001c46c90?}, {0x51eb480?, 0xc007eba300?})
 670702 2024-03-07T17:58:10.916720474+08:00 stderr F    /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a fp=0xc004f879b8 sp=0xc004f87978 pc=0x273a41a
 670703 2024-03-07T17:58:10.91672642+08:00 stderr F github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1({0x5958cd8, 0xc001c46c90}, {0x51eb480, 0xc007eba300}, 0xc000ac9a58?, 0x4d43000?)
 670704 2024-03-07T17:58:10.916733343+08:00 stderr F    /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34 +0xbe fp=0xc004f87a10 sp=0xc004f879b8 pc=0x273a2be
 670705 2024-03-07T17:58:10.916740098+08:00 stderr F github.com/milvus-io/milvus/internal/proto/querypb._QueryNode_LoadSegments_Handler({0x523fd60?, 0xc0011e0a80}, {0x5958cd8, 0xc001c46c90}, 0xc00b770230, 0xc0011fb1d0)
 670706 2024-03-07T17:58:10.91674596+08:00 stderr F     /go/src/github.com/milvus-io/milvus/internal/proto/querypb/query_coord.pb.go:6931 +0x138 fp=0xc004f87a68 sp=0xc004f87a10 pc=0x2a78d58
 670707 2024-03-07T17:58:10.91675567+08:00 stderr F google.golang.org/grpc.(*Server).processUnaryRPC(0xc001a5c000, {0x597a040, 0xc0022551e0}, 0xc00a2d0240, 0xc0011fb350, 0x7811738, 0x0)
 670708 2024-03-07T17:58:10.916760652+08:00 stderr F    /go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:1360 +0xe23 fp=0xc004f87e48 sp=0xc004f87a68 pc=0x22b1ec3
 670709 2024-03-07T17:58:10.916768259+08:00 stderr F google.golang.org/grpc.(*Server).handleStream(0xc001a5c000, {0x597a040, 0xc0022551e0}, 0xc00a2d0240, 0x0)
 670710 2024-03-07T17:58:10.91677416+08:00 stderr F     /go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:1737 +0xa36 fp=0xc004f87f68 sp=0xc004f87e48 pc=0x22b7016
 670711 2024-03-07T17:58:10.916778337+08:00 stderr F google.golang.org/grpc.(*Server).serveStreams.func1.1()
 670712 2024-03-07T17:58:10.916782326+08:00 stderr F    /go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:982 +0x98 fp=0xc004f87fe0 sp=0xc004f87f68 pc=0x22af858
 670713 2024-03-07T17:58:10.916786459+08:00 stderr F runtime.goexit()
 670714 2024-03-07T17:58:10.916791058+08:00 stderr F    /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc004f87fe8 sp=0xc004f87fe0 pc=0x1bbbc21
 670715 2024-03-07T17:58:10.916793431+08:00 stderr F created by google.golang.org/grpc.(*Server).serveStreams.func1
 670716 2024-03-07T17:58:10.916799019+08:00 stderr F    /go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:980 +0x18c

```

**Comment by XuanYang-cn** [comment]
See: #30998

**Comment by XuanYang-cn** [comment]
should be fixed
