### ISSUE TITLE
[Bug]: milvus panic with error `string field contains invalid UTF-8 `

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#31263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: PR-31205-20240312-f84cd3dcc--> master-20240314-1fafc720-amd64
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2024/03/14 05:56:51.127 +00:00] [DEBUG] [client/client.go:93] ["RootCoordClient GetSessions success"] [address=10.104.19.207:53100] [serverID=50]
[2024/03/14 05:56:51.128 +00:00] [WARN] [datacoord/segment_manager.go:248] ["failed to get ts from rootCoord for globalLastExpire"] []
[2024/03/14 05:56:51.152 +00:00] [INFO] [datacoord/server.go:373] ["init segment manager done"]
[2024/03/14 05:56:51.152 +00:00] [INFO] [datacoord/garbage_collector.go:80] ["GC with option"] [enabled=true] [interval=1h0m0s] [missingTolerance=1h0m0s] [dropTolerance=3h0m0s]
[2024/03/14 05:56:51.156 +00:00] [ERROR] [datacoord/service.go:130] ["dataCoord init error"] [error="string field contains invalid UTF-8"] [stack="github.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:130\ngithub.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:256\ngithub.com/milvus-io/milvus/cmd/components.(*DataCoord).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/data_coord.go:52\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:111"]
[2024/03/14 05:56:51.156 +00:00] [ERROR] [components/data_coord.go:53] ["DataCoord starts error"] [error="string field contains invalid UTF-8"] [stack="github.com/milvus-io/milvus/cmd/components.(*DataCoord).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/data_coord.go:53\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:111"]
panic: string field contains invalid UTF-8

goroutine 286 [running]:
panic({0x4ede480, 0x79c1dd0})
        /usr/local/go/src/runtime/panic.go:987 +0x3bb fp=0xc00251bf70 sp=0xc00251beb0 pc=0x1b8fddb
github.com/milvus-io/milvus/cmd/roles.runComponent[...].func1()
        /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:112 +0x105 fp=0xc00251bfe0 sp=0xc00251bf70 pc=0x485ea45
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00251bfe8 sp=0xc00251bfe0 pc=0x1bc9c21
created by github.com/milvus-io/milvus/cmd/roles.runComponent[...]
        /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:103 +0x158

```

### Steps To Reproduce

```markdown
just use helm upgrade command to upgrading image tag PR-31205-20240312-f84cd3dcc to master-20240314-1fafc720-amd64, and then the pod keep restart
```

### Milvus Log

[log.log](https://github.com/milvus-io/milvus/files/14597416/log.log)

### Anything else?
cluster: 4am
namespace: chaos-testing
release name: master-restful-3rd-verification

**Comment by bigsheeper** [comment]
Since ImportJob metadata was altered by PR https://github.com/milvus-io/milvus/pull/31192, the restoration of ImportJob metadata failed when upgrading from `PR-31205-20240312-f84cd3dcc` to master. Since no releases were made during these PRs, I believe this issue does not need to be addressed. @zhuwenxing
