### ISSUE TITLE
[Bug]: search result is less than topk value

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#31291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3-20240314-4e48a4de-amd64
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2024-03-15T03:17:17.178Z] 2024-03-15 03:17:16.908 | INFO     | MainThread |utils:load_and_search:214 - collection name: task_5_HNSW

[2024-03-15T03:17:17.178Z] 2024-03-15 03:17:16.908 | INFO     | MainThread |utils:load_and_search:215 - load collection

[2024-03-15T03:17:17.178Z] 2024-03-15 03:17:16.908 | INFO     | MainThread |utils:load_and_search:221 - release collection before load if replicas > 1

[2024-03-15T03:17:19.061Z] 2024-03-15 03:17:18.926 | INFO     | MainThread |utils:load_and_search:224 - release time: 2.0174

[2024-03-15T03:17:23.219Z] 2024-03-15 03:17:22.960 | INFO     | MainThread |utils:load_and_search:227 - load time: 4.0339

[2024-03-15T03:17:23.219Z] 2024-03-15 03:17:22.963 | INFO     | MainThread |utils:load_and_search:228 - Replica groups:

[2024-03-15T03:17:23.219Z] - Group: <group_id:448389761368326372>, <group_nodes:(25, 27)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_13_448389311178539597v0>, <shard_leader:27>, <shard_nodes:{27}>]>, <resource_group: __default_resource_group>, <num_outbound_node: {}>

[2024-03-15T03:17:23.219Z] - Group: <group_id:448389761368326373>, <group_nodes:(30,)>, <shards:[Shard: <channel_name:by-dev-rootcoord-dml_13_448389311178539597v0>, <shard_leader:30>, <shard_nodes:{30}>]>, <resource_group: __default_resource_group>, <num_outbound_node: {}>

[2024-03-15T03:17:23.219Z] 2024-03-15 03:17:22.979 | INFO     | MainThread |utils:load_and_search:233 - {'metric_type': 'L2', 'params': {'ef': 64}}

[2024-03-15T03:17:23.219Z] 2024-03-15 03:17:22.979 | INFO     | MainThread |utils:load_and_search:236 - 

[2024-03-15T03:17:23.219Z] Search...

[2024-03-15T03:17:23.219Z] 2024-03-15 03:17:22.985 | INFO     | MainThread |utils:load_and_search:247 - hit: id: 1950, distance: 30.79615592956543, entity: {'count': 1950, 'random_value': -18.0}

[2024-03-15T03:17:23.219Z] 2024-03-15 03:17:22.985 | INFO     | MainThread |utils:load_and_search:247 - hit: id: 2994, distance: 31.563446044921875, entity: {'count': 2994, 'random_value': -13.0}

[2024-03-15T03:17:23.219Z] 2024-03-15 03:17:22.985 | INFO     | MainThread |utils:load_and_search:247 - hit: id: 2785, distance: 31.966550827026367, entity: {'count': 2785, 'random_value': -11.0}

[2024-03-15T03:17:23.219Z] 2024-03-15 03:17:22.985 | INFO     | MainThread |utils:load_and_search:247 - hit: id: 868, distance: 32.722984313964844, entity: {'count': 868, 'random_value': -13.0}

[2024-03-15T03:17:23.219Z] Traceback (most recent call last):

[2024-03-15T03:17:23.219Z]   File "scripts/action_after_upgrade.py", line 113, in <module>

[2024-03-15T03:17:23.219Z]     task_5(data_size, host)

[2024-03-15T03:17:23.219Z]   File "scripts/action_after_upgrade.py", line 89, in task_5

[2024-03-15T03:17:23.219Z]     load_and_search(prefix, replicas=NUM_REPLICAS)

[2024-03-15T03:17:23.219Z]   File "/home/jenkins/agent/workspace/tests/python_client/deploy/scripts/utils.py", line 249, in load_and_search

[2024-03-15T03:17:23.219Z]     assert len(ids) == topK, f"get {len(ids)} results, but topK is {topK}"

[2024-03-15T03:17:23.219Z] AssertionError: get 4 results, but topK is 5
```

### Expected Behavior

result length equals to topk

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_for_release_cron/detail/deploy_test_for_release_cron/1541/pipeline

log:
[artifacts-pulsar-cluster-upgrade-1541-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/14610360/artifacts-pulsar-cluster-upgrade-1541-server-logs.tar.gz)

**Comment by rsckjgy** [comment]
Are there any answers?

**Comment by yanliang567** [comment]
> Are there any answers?

do you meet the same issue? could you please share your reproduce steps and milvus logs for investigation?
