### ISSUE TITLE
[Bug]: [Nightly] Load collection failed for timeout every time mmap is enabled

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#31346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 17b4938
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Load collection failed for timeout every time mmap is enabled.
```
[2024-03-17T20:49:18.040Z] ______ TestQueryParams.test_mmap_query_string_field_not_primary_is_empty _______
[2024-03-17T20:49:18.040Z] [gw2] linux -- Python 3.8.17 /usr/local/bin/python3
[2024-03-17T20:49:18.040Z] 
[2024-03-17T20:49:18.040Z] self = <test_query.TestQueryParams object at 0x7f283187bee0>
[2024-03-17T20:49:18.040Z] 
[2024-03-17T20:49:18.040Z]     @pytest.mark.tags(CaseLabel.L2)
[2024-03-17T20:49:18.040Z]     def test_mmap_query_string_field_not_primary_is_empty(self):
[2024-03-17T20:49:18.040Z]         """
[2024-03-17T20:49:18.041Z]         target: enable mmap, use string expr to test query, string field is not the main field
[2024-03-17T20:49:18.041Z]         method: create collection , string field is primary
[2024-03-17T20:49:18.041Z]                 enable mmap
[2024-03-17T20:49:18.041Z]                 collection load and insert empty data with string field
[2024-03-17T20:49:18.041Z]                 collection query uses string expr in string field
[2024-03-17T20:49:18.041Z]         expected: query successfully
[2024-03-17T20:49:18.041Z]         """
[2024-03-17T20:49:18.041Z]         # 1.  create a collection
[2024-03-17T20:49:18.041Z]         collection_w, vectors = self.init_collection_general(prefix, insert_data=False, is_index=False)[0:2]
[2024-03-17T20:49:18.041Z]     
[2024-03-17T20:49:18.041Z]         nb = 3000
[2024-03-17T20:49:18.041Z]         df = cf.gen_default_list_data(nb)
[2024-03-17T20:49:18.041Z]         df[2] = ["" for _ in range(nb)]
[2024-03-17T20:49:18.041Z]     
[2024-03-17T20:49:18.041Z]         collection_w.insert(df)
[2024-03-17T20:49:18.041Z]         assert collection_w.num_entities == nb
[2024-03-17T20:49:18.041Z]     
[2024-03-17T20:49:18.041Z]         collection_w.create_index(ct.default_float_vec_field_name, default_index_params, index_name="index_query")
[2024-03-17T20:49:18.041Z]         collection_w.set_properties({'mmap.enabled': True})
[2024-03-17T20:49:18.041Z]         collection_w.alter_index("index_query", {'mmap.enabled': True})
[2024-03-17T20:49:18.041Z]     
[2024-03-17T20:49:18.041Z] >       collection_w.load()

[2024-03-17T20:49:18.042Z] [2024-03-17 18:55:59 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 180], kwargs: {} (api_request.py:62)
[2024-03-17T20:49:18.042Z] [2024-03-17 18:58:59 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=wait for loading collection timeout, collection: query_EViPRYjc)>, <Time:{'RPC start': '2024-03-17 18:55:59.192131', 'RPC error': '2024-03-17 18:58:59.662895'}> (decorators.py:139)
[2024-03-17T20:49:18.042Z] [2024-03-17 18:58:59 - WARNING - pymilvus.decorators]: [93mRetry timeout: 180s[0m (decorators.py:105)
[2024-03-17T20:49:18.042Z] [2024-03-17 18:58:59 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for loading collection timeout, collection: query_EViPRYjc)>, <Time:{'RPC start': '2024-03-17 18:55:59.157353', 'RPC error': '2024-03-17 18:58:59.664137'}> (decorators.py:139)
[2024-03-17T20:49:18.042Z] [2024-03-17 18:58:59 - ERROR - ci_test]: Traceback (most recent call last):
[2024-03-17T20:49:18.042Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper
[2024-03-17T20:49:18.042Z]     res = func(*args, **_kwargs)
[2024-03-17T20:49:18.042Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request
[2024-03-17T20:49:18.042Z]     return func(*arg, **kwargs)
[2024-03-17T20:49:18.042Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 419, in load
[2024-03-17T20:49:18.042Z]     conn.load_collection(
[2024-03-17T20:49:18.042Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 140, in handler
[2024-03-17T20:49:18.042Z]     raise e from e
[2024-03-17T20:49:18.042Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
[2024-03-17T20:49:18.042Z]     return func(*args, **kwargs)
[2024-03-17T20:49:18.042Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 175, in handler
[2024-03-17T20:49:18.042Z]     return func(self, *args, **kwargs)
[2024-03-17T20:49:18.042Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 106, in handler
[2024-03-17T20:49:18.042Z]     raise MilvusException(
[2024-03-17T20:49:18.042Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for loading collection timeout, collection: query_EViPRYjc)>
[2024-03-17T20:49:18.042Z]  (api_request.py:45)
[2024-03-17T20:49:18.042Z] [2024-03-17 18:58:59 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for loading collection timeout, collection: query_EViPRYjc)> (api_request.py:46)
```

### Expected Behavior

load successfully

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI/detail/master/683/pipeline/159/
2. log: [artifacts-milvus-standalone-nightly-683-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI/job/master/683/artifact/artifacts-milvus-standalone-nightly-683-pymilvus-e2e-logs.tar.gz)
3. collection name: query_bX1hFst0
4. failed time: [2024-03-17T18:49:42.367Z] [gw1] [ 39%] FAILED testcases/test_query.py::TestQueryParams::test_mmap_query_string_field_not_primary_is_empty

**Comment by sunby** [comment]
same issue as #31162

**Comment by sunby** [comment]
fixed.
/unassign
/assign @NicoYuan1986

**Comment by yanliang567** [comment]
@NicoYuan1986 please help to verify and close the issue.

**Comment by NicoYuan1986** [comment]
verified on master branch. master-20240322-c27db43b-amd64 
verified on 2.4 branch. 2.4-20240322-95776504-amd64
