### ISSUE TITLE
[Bug]: search failed with error `segment not found: segment not loaded[segment=448524669963469343]` after etcd pod failure chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#31479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4-20240320-a07abba1-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2024-03-21T02:07:15.400Z] [2024-03-21 02:03:15 - DEBUG - ci_test]: (api_response) : <Collection>:

[2024-03-21T02:07:15.400Z] -------------

[2024-03-21T02:07:15.400Z] <name>: Checker__qG9Cdnts

[2024-03-21T02:07:15.400Z] <description>: 

[2024-03-21T02:07:15.401Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}......  (api_request.py:37)

[2024-03-21T02:07:15.401Z] [2024-03-21 02:03:15 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-03-21T02:07:15.401Z] [2024-03-21 02:03:19 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-03-21T02:07:15.401Z] [2024-03-21 02:03:19 - DEBUG - ci_test]: (api_request)  : [Collection.compact] args: [180], kwargs: {} (api_request.py:62)

[2024-03-21T02:07:15.401Z] [2024-03-21 02:03:19 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-03-21T02:07:15.401Z] [2024-03-21 02:04:56 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-03-21T02:07:15.401Z] [2024-03-21 02:04:57 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-03-21T02:07:15.401Z] [2024-03-21 02:04:57 - INFO - ci_test]: assert create collection: 0.1336677074432373, init_entities: 594000 (test_all_collections_after_chaos.py:49)

[2024-03-21T02:07:15.401Z] [2024-03-21 02:04:58 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [[[-3000, -2999, -2998, -2997, -2996, -2995, -2994, -2993, -2992, -2991, -2990, -2989, -2988, -2987, -2986, -2985, -2984, -2983, -2982, -2981, -2980, -2979, -2978, -2977, -2976, -2975, -2974, -2973, -2972, -2971, -2970, -2969, -2968, -2967, -2966, -2965, -2964, -2963, -2962, -2961, -2960, -2959, -29......, kwargs: {'timeout': 180} (api_request.py:62)

[2024-03-21T02:07:15.401Z] [2024-03-21 02:04:58 - DEBUG - ci_test]: (api_response) : (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 448524897021591553, success count: 2000, err count: 0)  (api_request.py:37)

[2024-03-21T02:07:15.401Z] [2024-03-21 02:04:58 - INFO - ci_test]: assert insert: 0.5366189479827881 (test_all_collections_after_chaos.py:61)

[2024-03-21T02:07:15.401Z] [2024-03-21 02:04:58 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-03-21T02:07:15.401Z] [2024-03-21 02:05:02 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-03-21T02:07:15.401Z] [2024-03-21 02:05:02 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-03-21T02:07:15.401Z] [2024-03-21 02:05:03 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-03-21T02:07:15.401Z] [2024-03-21 02:05:03 - INFO - ci_test]: assert flush: 4.137727737426758, entities: 596000 (test_all_collections_after_chaos.py:71)

[2024-03-21T02:07:15.401Z] [2024-03-21 02:05:03 - INFO - ci_test]: index info: [{'collection': 'Checker__qG9Cdnts', 'field': 'float_vector', 'index_name': 'vec_index', 'index_param': {'params': {'M': 48, 'efConstruction': 500}, 'index_type': 'HNSW', 'metric_type': 'L2'}}] (test_all_collections_after_chaos.py:87)

[2024-03-21T02:07:15.401Z] [2024-03-21 02:05:03 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 180], kwargs: {} (api_request.py:62)

[2024-03-21T02:07:15.401Z] [2024-03-21 02:05:03 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-03-21T02:07:15.401Z] [2024-03-21 02:05:03 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.14533679589001003, 0.0806418768306715, 0.09657549268780763, 0.07232672332383736, 0.034078680266963424, 0.03831020469460922, 0.0004073675842913069, 0.06920585546647347, 0.10202570321737513, 0.12576123686192886, 0.0003041327961810083, 0.028567525655743324, 0.03569710269363669, 0.09693069987799541......, kwargs: {} (api_request.py:62)

[2024-03-21T02:07:15.401Z] [2024-03-21 02:05:04 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=65535, message=fail to search on QueryNode 19: worker(19) query failed: segment not found: segment not loaded[segment=448524669963469343])>, <Time:{'RPC start': '2024-03-21 02:05:03.215411', 'RPC error': '2024-03-21 02:05:04.049116'}> (decorators.py:139)

[2024-03-21T02:07:15.401Z] [2024-03-21 02:05:04 - ERROR - ci_test]: Traceback (most recent call last):

[2024-03-21T02:07:15.401Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2024-03-21T02:07:15.401Z]     res = func(*args, **_kwargs)

[2024-03-21T02:07:15.401Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2024-03-21T02:07:15.401Z]     return func(*arg, **kwargs)

[2024-03-21T02:07:15.401Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 792, in search

[2024-03-21T02:07:15.401Z]     resp = conn.search(

[2024-03-21T02:07:15.401Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 140, in handler

[2024-03-21T02:07:15.401Z]     raise e from e

[2024-03-21T02:07:15.401Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2024-03-21T02:07:15.401Z]     return func(*args, **kwargs)

[2024-03-21T02:07:15.401Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 175, in handler

[2024-03-21T02:07:15.401Z]     return func(self, *args, **kwargs)

[2024-03-21T02:07:15.401Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 115, in handler

[2024-03-21T02:07:15.401Z]     raise e from e

[2024-03-21T02:07:15.401Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 86, in handler

[2024-03-21T02:07:15.401Z]     return func(*args, **kwargs)

[2024-03-21T02:07:15.401Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 775, in search

[2024-03-21T02:07:15.401Z]     return self._execute_search(request, timeout, round_decimal=round_decimal, **kwargs)

[2024-03-21T02:07:15.401Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 735, in _execute_search

[2024-03-21T02:07:15.401Z]     raise e from e

[2024-03-21T02:07:15.401Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 728, in _execute_search

[2024-03-21T02:07:15.401Z]     check_status(response.status)

[2024-03-21T02:07:15.401Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/utils.py", line 54, in check_status

[2024-03-21T02:07:15.401Z]     raise MilvusException(status.code, status.reason, status.error_code)

[2024-03-21T02:07:15.401Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=fail to search on QueryNode 19: worker(19) query failed: segment not found: segment not loaded[segment=448524669963469343])>

[2024-03-21T02:07:15.401Z]  (api_request.py:45)
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-for-release-cron/detail/chaos-test-kafka-for-release-cron/11751/pipeline

log: 
[artifacts-etcd-pod-failure-11751-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/14693220/artifacts-etcd-pod-failure-11751-server-logs.tar.gz)

cluster: 4am
namespace: chaos-testing
pod info
```
[2024-03-21T01:59:49.841Z] + kubectl get pods -o wide

[2024-03-21T01:59:49.842Z] + grep etcd-pod-failure-11751

[2024-03-21T01:59:50.540Z] etcd-pod-failure-11751-0                                          1/1     Running       2 (10m ago)     35m     10.104.20.127   4am-node22   <none>           <none>

[2024-03-21T01:59:50.540Z] etcd-pod-failure-11751-1                                          1/1     Running       2 (10m ago)     35m     10.104.19.142   4am-node28   <none>           <none>

[2024-03-21T01:59:50.540Z] etcd-pod-failure-11751-2                                          1/1     Running       2 (10m ago)     35m     10.104.32.167   4am-node39   <none>           <none>

[2024-03-21T01:59:50.540Z] etcd-pod-failure-11751-kafka-0                                    2/2     Running       1 (34m ago)     35m     10.104.19.141   4am-node28   <none>           <none>

[2024-03-21T01:59:50.540Z] etcd-pod-failure-11751-kafka-1                                    2/2     Running       0               35m     10.104.20.130   4am-node22   <none>           <none>

[2024-03-21T01:59:50.540Z] etcd-pod-failure-11751-kafka-2                                    2/2     Running       1 (34m ago)     35m     10.104.23.104   4am-node27   <none>           <none>

[2024-03-21T01:59:50.540Z] etcd-pod-failure-11751-kafka-exporter-9f5b45644-q7sl7             1/1     Running       4 (34m ago)     35m     10.104.1.81     4am-node10   <none>           <none>

[2024-03-21T01:59:50.540Z] etcd-pod-failure-11751-milvus-datacoord-86cf98d46d-s26vp          1/1     Running       2 (12m ago)     35m     10.104.33.76    4am-node36   <none>           <none>

[2024-03-21T01:59:50.540Z] etcd-pod-failure-11751-milvus-datanode-69fdf898c7-h2clk           1/1     Running       2 (12m ago)     35m     10.104.33.75    4am-node36   <none>           <none>

[2024-03-21T01:59:50.540Z] etcd-pod-failure-11751-milvus-datanode-69fdf898c7-nzq6z           1/1     Running       2 (12m ago)     35m     10.104.4.155    4am-node11   <none>           <none>

[2024-03-21T01:59:50.540Z] etcd-pod-failure-11751-milvus-indexcoord-6c7679758f-dmz5p         1/1     Running       0               35m     10.104.4.151    4am-node11   <none>           <none>

[2024-03-21T01:59:50.541Z] etcd-pod-failure-11751-milvus-indexnode-9d78885b4-5vjrl           1/1     Running       3 (8m56s ago)   35m     10.104.33.77    4am-node36   <none>           <none>

[2024-03-21T01:59:50.541Z] etcd-pod-failure-11751-milvus-indexnode-9d78885b4-jh8gq           1/1     Running       2 (12m ago)     35m     10.104.32.160   4am-node39   <none>           <none>

[2024-03-21T01:59:50.541Z] etcd-pod-failure-11751-milvus-indexnode-9d78885b4-qq9p5           1/1     Running       2 (12m ago)     35m     10.104.4.157    4am-node11   <none>           <none>

[2024-03-21T01:59:50.541Z] etcd-pod-failure-11751-milvus-proxy-66fc5f7f99-8dg58              1/1     Running       2 (12m ago)     35m     10.104.4.156    4am-node11   <none>           <none>

[2024-03-21T01:59:50.541Z] etcd-pod-failure-11751-milvus-querycoord-6d4958b978-9kbwt         1/1     Running       2 (12m ago)     35m     10.104.4.152    4am-node11   <none>           <none>

[2024-03-21T01:59:50.541Z] etcd-pod-failure-11751-milvus-querynode-86546d776-cq8k2           1/1     Running       2 (12m ago)     35m     10.104.4.154    4am-node11   <none>           <none>

[2024-03-21T01:59:50.541Z] etcd-pod-failure-11751-milvus-querynode-86546d776-nkmwc           1/1     Running       2 (12m ago)     35m     10.104.32.161   4am-node39   <none>           <none>

[2024-03-21T01:59:50.541Z] etcd-pod-failure-11751-milvus-querynode-86546d776-qwwqp           1/1     Running       2 (12m ago)     35m     10.104.33.74    4am-node36   <none>           <none>

[2024-03-21T01:59:50.541Z] etcd-pod-failure-11751-milvus-rootcoord-59dfcb445b-6pxcz          1/1     Running       3 (12m ago)     35m     10.104.4.153    4am-node11   <none>           <none>

[2024-03-21T01:59:50.541Z] etcd-pod-failure-11751-minio-0                                    1/1     Running       0               35m     10.104.19.140   4am-node28   <none>           <none>

[2024-03-21T01:59:50.541Z] etcd-pod-failure-11751-minio-1                                    1/1     Running       0               35m     10.104.20.128   4am-node22   <none>           <none>

[2024-03-21T01:59:50.541Z] etcd-pod-failure-11751-minio-2                                    1/1     Running       0               35m     10.104.23.105   4am-node27   <none>           <none>

[2024-03-21T01:59:50.541Z] etcd-pod-failure-11751-minio-3                                    1/1     Running       0               35m     10.104.34.39    4am-node37   <none>           <none>

[2024-03-21T01:59:50.541Z] etcd-pod-failure-11751-zookeeper-0                                1/1     Running       0               35m     10.104.20.124   4am-node22   <none>           <none>

[2024-03-21T01:59:50.541Z] etcd-pod-failure-11751-zookeeper-1                                1/1     Running       0               35m     10.104.19.143   4am-node28   <none>           <none>

[2024-03-21T01:59:50.541Z] etcd-pod-failure-11751-zookeeper-2                                1/1     Running       0               35m     10.104.34.38    4am-node37   <none>           <none>
```

**Comment by xiaofan-luan** [comment]
is this recoverable after a well?

**Comment by weiliu1031** [comment]
> is this recoverable after a well?

yes, but this error is unexpected, due to segment release break the search request

**Comment by xiaofan-luan** [comment]
@weiliu1031 
I think we should remove the segment lag behind check.

1. delegator need to know the current state. That happens on load stage. when load is not done, delegator will reject all the reqeust
2. proxy and querycoord should not take care whether the delegator is ready or not. they simply return the latest querynode host this delegator. everything else is host by delegator.

@aoiasd @congqixia any comments?

**Comment by wangting0128** [comment]
### Different scenarios, same error

test scene is: #31797 

After milvus upgraded the image, search and query reported error
<img width="1918" alt="截屏2024-04-01 17 14 27" src="https://github.com/milvus-io/milvus/assets/26307815/9bec0aab-13ee-4f2d-addd-badb0f4a0986">

**Comment by zhuwenxing** [comment]
It was not reproduced in the chaos test, even before the PR merged
