### ISSUE TITLE
[Bug]: search failed with error `channel not found[channel=by-dev-rootcoord-dml_13_448524181932158703v0]` after querynode pod failure chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#31480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4-20240320-a07abba1-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```

[2024-03-21T01:56:25.160Z] <name>: Checker__Oe8bhr9o

[2024-03-21T01:56:25.160Z] <description>: 

[2024-03-21T01:56:25.160Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}......  (api_request.py:37)

[2024-03-21T01:56:25.160Z] [2024-03-21 01:53:36 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-03-21T01:56:25.160Z] [2024-03-21 01:53:38 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-03-21T01:56:25.161Z] [2024-03-21 01:53:38 - DEBUG - ci_test]: (api_request)  : [Collection.compact] args: [180], kwargs: {} (api_request.py:62)

[2024-03-21T01:56:25.161Z] [2024-03-21 01:53:38 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-03-21T01:56:25.161Z] [2024-03-21 01:53:38 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-03-21T01:56:25.161Z] [2024-03-21 01:53:39 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-03-21T01:56:25.161Z] [2024-03-21 01:53:39 - INFO - ci_test]: assert create collection: 0.012607574462890625, init_entities: 732894 (test_all_collections_after_chaos.py:49)

[2024-03-21T01:56:25.161Z] [2024-03-21 01:53:39 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [[[-3000, -2999, -2998, -2997, -2996, -2995, -2994, -2993, -2992, -2991, -2990, -2989, -2988, -2987, -2986, -2985, -2984, -2983, -2982, -2981, -2980, -2979, -2978, -2977, -2976, -2975, -2974, -2973, -2972, -2971, -2970, -2969, -2968, -2967, -2966, -2965, -2964, -2963, -2962, -2961, -2960, -2959, -29......, kwargs: {'timeout': 180} (api_request.py:62)

[2024-03-21T01:56:25.161Z] [2024-03-21 01:53:40 - DEBUG - ci_test]: (api_response) : (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 448524719206694915, success count: 2000, err count: 0)  (api_request.py:37)

[2024-03-21T01:56:25.161Z] [2024-03-21 01:53:40 - INFO - ci_test]: assert insert: 0.5367302894592285 (test_all_collections_after_chaos.py:61)

[2024-03-21T01:56:25.161Z] [2024-03-21 01:53:40 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-03-21T01:56:25.161Z] [2024-03-21 01:53:44 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-03-21T01:56:25.161Z] [2024-03-21 01:53:44 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-03-21T01:56:25.161Z] [2024-03-21 01:53:44 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-03-21T01:56:25.161Z] [2024-03-21 01:53:44 - INFO - ci_test]: assert flush: 4.171762943267822, entities: 734894 (test_all_collections_after_chaos.py:71)

[2024-03-21T01:56:25.161Z] [2024-03-21 01:53:44 - INFO - ci_test]: index info: [{'collection': 'Checker__Oe8bhr9o', 'field': 'float_vector', 'index_name': 'vec_index', 'index_param': {'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}, 'index_type': 'HNSW'}}] (test_all_collections_after_chaos.py:87)

[2024-03-21T01:56:25.161Z] [2024-03-21 01:53:44 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 180], kwargs: {} (api_request.py:62)

[2024-03-21T01:56:25.161Z] [2024-03-21 01:53:45 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-03-21T01:56:25.161Z] [2024-03-21 01:53:45 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.07178789503954779, 0.014785453516577828, 0.1229953722636067, 0.11306272064532973, 0.04208985126782994, 0.06132565316246127, 0.030306882308206624, 0.007861231051362633, 0.14656461013565672, 0.060989741534688266, 0.04008742534738432, 0.1288472275478675, 0.14097863744146613, 0.13574753389415684, 0......, kwargs: {} (api_request.py:62)

[2024-03-21T01:56:25.161Z] [2024-03-21 01:53:45 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=500, message=fail to search on QueryNode 14: channel not found[channel=by-dev-rootcoord-dml_13_448524181932158703v0])>, <Time:{'RPC start': '2024-03-21 01:53:45.037335', 'RPC error': '2024-03-21 01:53:45.647996'}> (decorators.py:139)

[2024-03-21T01:56:25.161Z] [2024-03-21 01:53:45 - ERROR - ci_test]: Traceback (most recent call last):

[2024-03-21T01:56:25.161Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2024-03-21T01:56:25.161Z]     res = func(*args, **_kwargs)

[2024-03-21T01:56:25.161Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2024-03-21T01:56:25.161Z]     return func(*arg, **kwargs)

[2024-03-21T01:56:25.161Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 792, in search

[2024-03-21T01:56:25.161Z]     resp = conn.search(

[2024-03-21T01:56:25.161Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 140, in handler

[2024-03-21T01:56:25.161Z]     raise e from e

[2024-03-21T01:56:25.161Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2024-03-21T01:56:25.161Z]     return func(*args, **kwargs)

[2024-03-21T01:56:25.161Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 175, in handler

[2024-03-21T01:56:25.161Z]     return func(self, *args, **kwargs)

[2024-03-21T01:56:25.161Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 115, in handler

[2024-03-21T01:56:25.161Z]     raise e from e

[2024-03-21T01:56:25.161Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 86, in handler

[2024-03-21T01:56:25.161Z]     return func(*args, **kwargs)

[2024-03-21T01:56:25.161Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 775, in search

[2024-03-21T01:56:25.161Z]     return self._execute_search(request, timeout, round_decimal=round_decimal, **kwargs)

[2024-03-21T01:56:25.161Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 735, in _execute_search

[2024-03-21T01:56:25.161Z]     raise e from e

[2024-03-21T01:56:25.161Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 728, in _execute_search

[2024-03-21T01:56:25.161Z]     check_status(response.status)

[2024-03-21T01:56:25.161Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/utils.py", line 54, in check_status

[2024-03-21T01:56:25.161Z]     raise MilvusException(status.code, status.reason, status.error_code)

[2024-03-21T01:56:25.161Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=500, message=fail to search on QueryNode 14: channel not found[channel=by-dev-rootcoord-dml_13_448524181932158703v0])>

[2024-03-21T01:56:25.161Z]  (api_request.py:45)

[2024-03-21T01:56:25.161Z] [2024-03-21 01:53:45 - ERROR - ci_test]: (api_response) : <MilvusException: (code=500, message=fail to search on QueryNode 14: channel not found[channel=by-dev-rootcoord-dml_13_448524181932158703v0])> (api_request.py:46)
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-for-release-cron/detail/chaos-test-kafka-for-release-cron/11749/pipeline
log: [artifacts-querynode-pod-failure-11749-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/14693376/artifacts-querynode-pod-failure-11749-server-logs.tar.gz)

cluster: 4am
namespace: chaos-testing
pod info
```
[2024-03-21T01:52:35.596Z] + kubectl get pods -o wide

[2024-03-21T01:52:35.597Z] + grep querynode-pod-failure-11749

[2024-03-21T01:52:35.851Z] querynode-pod-failure-11749-etcd-0                                1/1     Running            0               35m     10.104.20.69    4am-node22   <none>           <none>

[2024-03-21T01:52:35.851Z] querynode-pod-failure-11749-etcd-1                                1/1     Running            0               35m     10.104.32.130   4am-node39   <none>           <none>

[2024-03-21T01:52:35.851Z] querynode-pod-failure-11749-etcd-2                                1/1     Running            0               35m     10.104.29.231   4am-node35   <none>           <none>

[2024-03-21T01:52:35.851Z] querynode-pod-failure-11749-kafka-0                               2/2     Running            0               35m     10.104.20.71    4am-node22   <none>           <none>

[2024-03-21T01:52:35.851Z] querynode-pod-failure-11749-kafka-1                               2/2     Running            0               35m     10.104.32.129   4am-node39   <none>           <none>

[2024-03-21T01:52:35.851Z] querynode-pod-failure-11749-kafka-2                               2/2     Running            0               35m     10.104.33.68    4am-node36   <none>           <none>

[2024-03-21T01:52:35.851Z] querynode-pod-failure-11749-kafka-exporter-6ddb54db6d-p5bsm       1/1     Running            3 (34m ago)     35m     10.104.13.204   4am-node16   <none>           <none>

[2024-03-21T01:52:35.851Z] querynode-pod-failure-11749-milvus-datacoord-6db99885d7-hfrg4     1/1     Running            0               35m     10.104.4.134    4am-node11   <none>           <none>

[2024-03-21T01:52:35.851Z] querynode-pod-failure-11749-milvus-datanode-8c9986888-cp9ww       1/1     Running            0               35m     10.104.33.60    4am-node36   <none>           <none>

[2024-03-21T01:52:35.851Z] querynode-pod-failure-11749-milvus-datanode-8c9986888-d7qb4       1/1     Running            0               35m     10.104.4.133    4am-node11   <none>           <none>

[2024-03-21T01:52:35.851Z] querynode-pod-failure-11749-milvus-indexcoord-6f9859ddf8-fjq4z    1/1     Running            0               35m     10.104.5.125    4am-node12   <none>           <none>

[2024-03-21T01:52:35.851Z] querynode-pod-failure-11749-milvus-indexnode-56fbcf4567-4q69k     1/1     Running            0               35m     10.104.33.61    4am-node36   <none>           <none>

[2024-03-21T01:52:35.851Z] querynode-pod-failure-11749-milvus-indexnode-56fbcf4567-6vb9d     1/1     Running            0               35m     10.104.4.128    4am-node11   <none>           <none>

[2024-03-21T01:52:35.851Z] querynode-pod-failure-11749-milvus-indexnode-56fbcf4567-hzxlw     1/1     Running            0               35m     10.104.5.126    4am-node12   <none>           <none>

[2024-03-21T01:52:35.851Z] querynode-pod-failure-11749-milvus-proxy-558754979b-8ttdn         1/1     Running            0               35m     10.104.4.135    4am-node11   <none>           <none>

[2024-03-21T01:52:35.851Z] querynode-pod-failure-11749-milvus-querycoord-757d469965-jks5w    1/1     Running            0               35m     10.104.4.130    4am-node11   <none>           <none>

[2024-03-21T01:52:35.851Z] querynode-pod-failure-11749-milvus-querynode-57488bc887-6xzrr     1/1     Running            3 (10m ago)     35m     10.104.32.123   4am-node39   <none>           <none>

[2024-03-21T01:52:35.851Z] querynode-pod-failure-11749-milvus-querynode-57488bc887-796tw     1/1     Running            3 (10m ago)     35m     10.104.4.129    4am-node11   <none>           <none>

[2024-03-21T01:52:35.851Z] querynode-pod-failure-11749-milvus-querynode-57488bc887-ph898     1/1     Running            3 (10m ago)     35m     10.104.29.226   4am-node35   <none>           <none>

[2024-03-21T01:52:35.851Z] querynode-pod-failure-11749-milvus-rootcoord-bc9cdf5c9-xb2cc      1/1     Running            1 (33m ago)     35m     10.104.4.127    4am-node11   <none>           <none>

[2024-03-21T01:52:35.851Z] querynode-pod-failure-11749-minio-0                               1/1     Running            0               35m     10.104.20.70    4am-node22   <none>           <none>

[2024-03-21T01:52:35.851Z] querynode-pod-failure-11749-minio-1                               1/1     Running            0               35m     10.104.32.128   4am-node39   <none>           <none>

[2024-03-21T01:52:35.851Z] querynode-pod-failure-11749-minio-2                               1/1     Running            0               35m     10.104.33.66    4am-node36   <none>           <none>

[2024-03-21T01:52:35.851Z] querynode-pod-failure-11749-minio-3                               1/1     Running            0               35m     10.104.19.89    4am-node28   <none>           <none>

[2024-03-21T01:52:35.851Z] querynode-pod-failure-11749-zookeeper-0                           1/1     Running            0               35m     10.104.20.68    4am-node22   <none>           <none>

[2024-03-21T01:52:35.851Z] querynode-pod-failure-11749-zookeeper-1                           1/1     Running            0               35m     10.104.19.87    4am-node28   <none>           <none>

[2024-03-21T01:52:35.851Z] querynode-pod-failure-11749-zookeeper-2                           1/1     Running            0               35m     10.104.29.230   4am-node35   <none>           <none>
```

**Comment by yanliang567** [comment]
sounds like similar to #31481 
/assign @weiliu1031 
/unassign

**Comment by weiliu1031** [comment]
> sounds like similar to #31481 /assign @weiliu1031 /unassign

same cause with #31481, WIP
