### ISSUE TITLE
[Bug]: querycoord crash during test after reinstallation

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#31495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4-20240321-a0535edb-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2024/03/21 08:54:32.438 +00:00] [INFO] [task/scheduler.go:588] ["processed tasks"] [nodeID=31] [toProcessNum=0] [committedNum=0] [toRemoveNum=0]
[2024/03/21 08:54:32.438 +00:00] [INFO] [task/scheduler.go:594] ["process tasks related to node done"] [nodeID=31] [processingTaskNum=2] [waitingTaskNum=0] [segmentTaskNum=0] [channelTaskNum=2]
[2024/03/21 08:54:32.438 +00:00] [INFO] [balance/utils.go:114] ["create channel task"] [collection=448530707477303460] [replica=448531158852436018] [channel=by-dev-rootcoord-dml_10_448530707477303460v0] [from=-1] [to=29]
[2024/03/21 08:54:32.439 +00:00] [INFO] [balance/utils.go:114] ["create channel task"] [collection=448530707476902093] [replica=448531158852436017] [channel=by-dev-rootcoord-dml_10_448530707476902093v0] [from=-1] [to=29]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x46ebcef]

goroutine 375 [running]:
panic({0x4d8e7e0, 0x7877930})
	/usr/local/go/src/runtime/panic.go:987 +0x3bb fp=0xc00322fa98 sp=0xc00322f9d8 pc=0x1b97ddb
runtime.panicmem(...)
	/usr/local/go/src/runtime/panic.go:260
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:841 +0x37d fp=0xc00322faf8 sp=0xc00322fa98 pc=0x1bb00dd
github.com/milvus-io/milvus/internal/querycoordv2/checkers.(*SegmentChecker).createSegmentLoadTasks(0xc00189ee40, {0x59bba98, 0xc00280a2d0}, {0xc0018e6560?, 0x2, 0x2}, 0xc0015707e0)
	/go/src/github.com/milvus-io/milvus/internal/querycoordv2/checkers/segment_checker.go:380 +0x38f fp=0xc00322fc50 sp=0xc00322faf8 pc=0x46ebcef
github.com/milvus-io/milvus/internal/querycoordv2/checkers.(*SegmentChecker).checkReplica(0xc00189e6c0?, {0x59bb9f0, 0xc001d89bd0}, 0xc0015707e0)
	/go/src/github.com/milvus-io/milvus/internal/querycoordv2/checkers/segment_checker.go:113 +0x117 fp=0xc00322fd58 sp=0xc00322fc50 pc=0x46e9177
github.com/milvus-io/milvus/internal/querycoordv2/checkers.(*SegmentChecker).Check(0xc00189ee40, {0x59bb9f0, 0xc001d89bd0})
	/go/src/github.com/milvus-io/milvus/internal/querycoordv2/checkers/segment_checker.go:92 +0x40a fp=0xc00322fe58 sp=0xc00322fd58 pc=0x46e8faa
github.com/milvus-io/milvus/internal/querycoordv2/checkers.(*CheckerController).check(0xc001373e00, {0x59bb9f0, 0xc001d89bd0}, 0x0?)
	/go/src/github.com/milvus-io/milvus/internal/querycoordv2/checkers/controller.go:159 +0x53 fp=0xc00322fea8 sp=0xc00322fe58 pc=0x46e4b53
github.com/milvus-io/milvus/internal/querycoordv2/checkers.(*CheckerController).startChecker(0xc001373e00, {0x59bb9f0, 0xc001d89bd0}, 0x0?)
	/go/src/github.com/milvus-io/milvus/internal/querycoordv2/checkers/controller.go:133 +0x1a6 fp=0xc00322ffb0 sp=0xc00322fea8 pc=0x46e47a6
github.com/milvus-io/milvus/internal/querycoordv2/checkers.(*CheckerController).Start.func1()
	/go/src/github.com/milvus-io/milvus/internal/querycoordv2/checkers/controller.go:95 +0x31 fp=0xc00322ffe0 sp=0xc00322ffb0 pc=0x46e4491
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00322ffe8 sp=0xc00322ffe0 pc=0x1bd1c21
created by github.com/milvus-io/milvus/internal/querycoordv2/checkers.(*CheckerController).Start
	/go/src/github.com/milvus-io/milvus/internal/querycoordv2/checkers/controller.go:95 +0xb3

goroutine 1 [chan receive, 11 minutes]:
runtime.gopark(0x7a0d1b0?, 0xc0015a5770?, 0xa?, 0xab?, 0xc001d7b320?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc001787700 sp=0xc0017876e0 pc=0x1b9b356
runtime.chanrecv(0xc0012f89c0, 0x0, 0x1)
	/usr/local/go/src/runtime/chan.go:583 +0x49d fp=0xc001787790 sp=0xc001787700 pc=0x1b636fd
runtime.chanrecv1(0x79f5ea8?, 0x52eef80?)
	/usr/local/go/src/runtime/chan.go:442 +0x18 fp=0xc0017877b8 sp=0xc001787790 pc=0x1b631f8
github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run(0xc001574f50)
	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:399 +0xafa fp=0xc001787c78 sp=0xc0017877b8 pc=0x48837ba
github.com/milvus-io/milvus/cmd/milvus.(*run).execute(0x0?, {0xc000212150?, 0x3, 0x3}, 0xc0012e8960)
	/go/src/github.com/milvus-io/milvus/cmd/milvus/run.go:47 +0x2e5 fp=0xc001787d48 sp=0xc001787c78 pc=0x488e625
github.com/milvus-io/milvus/cmd/milvus.RunMilvus({0xc000212150?, 0x3, 0x3})
	/go/src/github.com/milvus-io/milvus/cmd/milvus/milvus.go:60 +0x20e fp=0xc001787dc0 sp=0xc001787d48 pc=0x488e2ae
main.main()
	/go/src/github.com/milvus-io/milvus/cmd/main.go:95 +0x3e5 fp=0xc001787f80 sp=0xc001787dc0 pc=0x4892fe5
runtime.main()
	/usr/local/go/src/runtime/proc.go:250 +0x207 fp=0xc001787fe0 sp=0xc001787f80 pc=0x1b9af27
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc001787fe8 sp=0xc001787fe0 pc=0x1bd1c21
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_for_release_cron/detail/deploy_test_for_release_cron/1567/pipeline

log:
[artifacts-pulsar-cluster-reinstall-1567-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/14695109/artifacts-pulsar-cluster-reinstall-1567-server-logs.tar.gz)

cluster: 4am
ns:chaos-testing
pod:
```
 + grep pulsar-cluster-reinstall-1567
 pulsar-cluster-reinstall-1567-bookie-0                            1/1     Running       0               19m     10.104.27.94    4am-node31   <none>           <none>
 pulsar-cluster-reinstall-1567-bookie-1                            1/1     Running       0               19m     10.104.16.105   4am-node21   <none>           <none>
 pulsar-cluster-reinstall-1567-broker-0                            1/1     Running       0               19m     10.104.16.106   4am-node21   <none>           <none>
 pulsar-cluster-reinstall-1567-etcd-0                              1/1     Running       0               19m     10.104.27.93    4am-node31   <none>           <none>
 pulsar-cluster-reinstall-1567-etcd-1                              1/1     Running       0               19m     10.104.34.245   4am-node37   <none>           <none>
 pulsar-cluster-reinstall-1567-etcd-2                              1/1     Running       0               19m     10.104.16.104   4am-node21   <none>           <none>
 pulsar-cluster-reinstall-1567-milvus-datacoord-5bd58f8686-7bb8d   1/1     Running       0               19m     10.104.29.196   4am-node35   <none>           <none>
 pulsar-cluster-reinstall-1567-milvus-datanode-556f4f8c9-jzv65     1/1     Running       0               19m     10.104.14.215   4am-node18   <none>           <none>
 pulsar-cluster-reinstall-1567-milvus-datanode-556f4f8c9-tfkh5     1/1     Running       2 (17m ago)     19m     10.104.29.197   4am-node35   <none>           <none>
 pulsar-cluster-reinstall-1567-milvus-indexcoord-55bb9864c76xgph   1/1     Running       0               19m     10.104.29.198   4am-node35   <none>           <none>
 pulsar-cluster-reinstall-1567-milvus-indexnode-84bdc5fcf8-4hqlf   1/1     Running       0               19m     10.104.33.112   4am-node36   <none>           <none>
 pulsar-cluster-reinstall-1567-milvus-indexnode-84bdc5fcf8-n6xn9   1/1     Running       0               19m     10.104.29.199   4am-node35   <none>           <none>
 pulsar-cluster-reinstall-1567-milvus-indexnode-84bdc5fcf8-xrb49   1/1     Running       0               19m     10.104.14.216   4am-node18   <none>           <none>
 pulsar-cluster-reinstall-1567-milvus-proxy-6994454c7f-6rgwr       1/1     Running       0               19m     10.104.14.217   4am-node18   <none>           <none>
 pulsar-cluster-reinstall-1567-milvus-querycoord-5d7b97dcdbclsnc   1/1     Running       2 (6m6s ago)    19m     10.104.29.200   4am-node35   <none>           <none>
 pulsar-cluster-reinstall-1567-milvus-querynode-85b865f75b-n5fpz   1/1     Running       0               19m     10.104.14.218   4am-node18   <none>           <none>
 pulsar-cluster-reinstall-1567-milvus-querynode-85b865f75b-t7bl9   1/1     Running       0               19m     10.104.33.113   4am-node36   <none>           <none>
 pulsar-cluster-reinstall-1567-milvus-querynode-85b865f75b-zfcls   1/1     Running       0               19m     10.104.29.201   4am-node35   <none>           <none>
 pulsar-cluster-reinstall-1567-milvus-rootcoord-76466478fd-2l49n   1/1     Running       0               19m     10.104.29.202   4am-node35   <none>           <none>
 pulsar-cluster-reinstall-1567-minio-0                             1/1     Running       0               19m     10.104.27.95    4am-node31   <none>           <none>
 pulsar-cluster-reinstall-1567-minio-1                             1/1     Running       0               19m     10.104.25.51    4am-node30   <none>           <none>
 pulsar-cluster-reinstall-1567-minio-2                             1/1     Running       0               19m     10.104.23.238   4am-node27   <none>           <none>
 pulsar-cluster-reinstall-1567-minio-3                             1/1     Running       0               19m     10.104.24.26    4am-node29   <none>           <none>
 pulsar-cluster-reinstall-1567-proxy-0                             1/1     Running       0               19m     10.104.24.28    4am-node29   <none>           <none>
 pulsar-cluster-reinstall-1567-recovery-0                          1/1     Running       0               19m     10.104.24.27    4am-node29   <none>           <none>
 pulsar-cluster-reinstall-1567-zookeeper-0                         1/1     Running       0               19m     10.104.27.98    4am-node31   <none>           <none>
```

**Comment by congqixia** [comment]
/unassign
/assign @zhuwenxing 
@zhuwenxing patches are merged, could you please verify?
