### ISSUE TITLE
[Bug]: unexpected result of FLOAT16_VECTOR+HNSW

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#31520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4.0-rc1
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.4.0
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

HNSW index on FLOAT16_VECTOR field, the search result sometimes is unexpected.

Steps:
1. create a collection with a FLOAT16_VECTOR field
2. insert 10000 vectors
3. create HNSW index
4. pick some vector from the 10000 vectors to search

Sometimes the top0 item is not the target vector.

### Steps To Reproduce

```markdown
Use this script to reproduce

import time
import random
import numpy as np
from pymilvus import (
     connections,
     utility,
     FieldSchema, CollectionSchema, DataType,
     Collection,
 )

index_params_ivf={"index_type": "IVF_FLAT", "params": {"nlist": 128}, "metric_type": "L2"}
index_params_hnsw={"index_type": "HNSW", "params": {"M": 16, "efConstruction": 64}, "metric_type": "L2"}

search_param_ivf={"metric_type": "L2", "params": {"nprobe": 32}}
search_param_hnsw={"metric_type": "L2", "params": {"ef": 64}}

def gen_fp16_vectors(num, dim):
    raw_vectors = []
    fp16_vectors = []
    for _ in range(num):
        raw_vector = [random.random() for _ in range(dim)]
        raw_vectors.append(raw_vector)
        fp16_vector = np.array(raw_vector, dtype=np.float16).view(np.uint8).tolist()
        fp16_vectors.append(bytes(fp16_vector))

    return raw_vectors, fp16_vectors

def fp16_vector_search():
    connections.connect()

    dim = 512
    collection_name = "float16_test"

    int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True, auto_id=False)
    vector_field_name = "float16_vector"
    fp16_vector = FieldSchema(name=vector_field_name, dtype=DataType.FLOAT16_VECTOR, dim=dim)
    schema = CollectionSchema(fields=[int64_field, fp16_vector])

    has = utility.has_collection(collection_name)
    if has:
        utility.drop_collection(collection_name)

    collection = Collection(collection_name, schema)

    nb = 10000
    _, vectors = gen_fp16_vectors(nb, dim)
    data = [
        [i for i in range(nb)],
        vectors,
    ]
    collection.insert(data)
    collection.flush()

    collection.create_index(vector_field_name, index_params=index_params_hnsw)
    collection.load()

    for i in range(1000):
        n = random.randint(0, nb)
        target_vector = vectors[n]

        results = collection.search(data=[target_vector],
                          anns_field=vector_field_name,
                          limit=3,
                          param=search_param_hnsw,
                          )
        print(f"The result of No.{i} target vector:")
        for hits in results:
            for hit in hits:
                print(hit.to_dict())
            if hits[0].pk != n:
                raise Exception(f"The top1 ID {hits[0].pk} is not equal to target vector's ID {n}")


    collection.drop()

if __name__ == "__main__":
    fp16_vector_search()
```
```


### Milvus Log

_No response_

### Anything else?

_No response_

**Comment by yhmo** [comment]
Every time I run the script, always encounter unexpected results like this:
```

......
{'id': 9594, 'distance': 69.77268981933594, 'entity': {}}
{'id': 1656, 'distance': 71.5377197265625, 'entity': {}}
The result of No.14 target vector:
{'id': 8028, 'distance': 0.0, 'entity': {}}
{'id': 8969, 'distance': 67.71222686767578, 'entity': {}}
{'id': 4514, 'distance': 68.22660827636719, 'entity': {}}
The result of No.15 target vector:
{'id': 3400, 'distance': 0.0, 'entity': {}}
{'id': 1277, 'distance': 71.5914077758789, 'entity': {}}
{'id': 1392, 'distance': 72.995849609375, 'entity': {}}
The result of No.16 target vector:
{'id': 9759, 'distance': 70.98637390136719, 'entity': {}}
{'id': 8590, 'distance': 71.29367065429688, 'entity': {}}
{'id': 8916, 'distance': 72.65544128417969, 'entity': {}}
Traceback (most recent call last):
  File "/home/yhmo/git-go/pymilvus/examples/float16_example.py", line 77, in <module>
    fp16_vector_search()
  File "/home/yhmo/git-go/pymilvus/examples/float16_example.py", line 71, in fp16_vector_search
    raise Exception(f"The top1 ID {hits[0].pk} is not equal to target vector's ID {n}")
Exception: The top1 ID 9759 is not equal to target vector's ID 442
```

**Comment by yhmo** [comment]
Both float32 and float16 have similar problem:


```
import random
import numpy as np
from pymilvus import (
     connections,
     utility,
     FieldSchema, CollectionSchema, DataType,
     Collection,
 )

index_params_ivf={"index_type": "IVF_FLAT", "params": {"nlist": 128}, "metric_type": "L2"}
index_params_hnsw={"index_type": "HNSW", "params": {"M": 16, "efConstruction": 64}, "metric_type": "L2"}

search_param_ivf={"metric_type": "L2", "params": {"nprobe": 32}}
search_param_hnsw={"metric_type": "L2", "params": {"ef": 64}}

def gen_vectors(num, dim):
    raw_vectors = []
    fp16_vectors = []
    for _ in range(num):
        raw_vector = [random.random() for _ in range(dim)]
        raw_vectors.append(raw_vector)
        fp16_vector = np.array(raw_vector, dtype=np.float16).view(np.uint8).tolist()
        fp16_vectors.append(bytes(fp16_vector))

    return raw_vectors, fp16_vectors

topk = 10
dim = 512
nb = 10000
vectors32, vectors16 = gen_vectors(nb, dim)

connections.connect()

def fp16_vector_search():
    print("=========================fp16_vector_search============================")
    collection_name = "float16_test"

    int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True, auto_id=False)
    vector_field_name = "float16_vector"
    fp16_vector = FieldSchema(name=vector_field_name, dtype=DataType.FLOAT16_VECTOR, dim=dim)
    schema = CollectionSchema(fields=[int64_field, fp16_vector])

    has = utility.has_collection(collection_name)
    if has:
        utility.drop_collection(collection_name)

    collection = Collection(collection_name, schema)

    data = [
        [i for i in range(nb)],
        vectors16,
    ]
    collection.insert(data)
    collection.flush()

    collection.create_index(vector_field_name, index_params=index_params_hnsw)
    collection.load()

    count = 0
    for i in range(1000):
        n = random.randint(0, nb)
        target_vector = vectors16[n]

        results = collection.search(data=[target_vector],
                          anns_field=vector_field_name,
                          limit=topk,
                          param=search_param_hnsw,
                          )

        for hits in results:
            if hits[0].pk != n:
                print(f"------------ The top1 ID {hits[0].pk} of No.{i} target vector is not equal to target vector's ID {n}")
                count = count + 1

    print(f"Unmatched items: {count}")
    collection.drop()


def fp32_vector_search():
    print("=========================fp32_vector_search============================")
    collection_name = "float32_test"

    int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True, auto_id=False)
    vector_field_name = "float32_vector"
    fp32_vector = FieldSchema(name=vector_field_name, dtype=DataType.FLOAT_VECTOR, dim=dim)
    schema = CollectionSchema(fields=[int64_field, fp32_vector])

    has = utility.has_collection(collection_name)
    if has:
        utility.drop_collection(collection_name)

    collection = Collection(collection_name, schema)

    data = [
        [i for i in range(nb)],
        vectors32,
    ]
    collection.insert(data)
    collection.flush()

    collection.create_index(vector_field_name, index_params=index_params_hnsw)
    collection.load()

    count = 0
    for i in range(1000):
        n = random.randint(0, nb)
        target_vector = vectors32[n]

        results = collection.search(data=[target_vector],
                          anns_field=vector_field_name,
                          limit=topk,
                          param=search_param_hnsw,
                          )

        for hits in results:
            if hits[0].pk != n:
                print(f"------------ The top1 ID {hits[0].pk} of No.{i} target vector is not equal to target vector's ID {n}")
                count = count + 1

    print(f"Unmatched items: {count}")
    collection.drop()


if __name__ == "__main__":
    fp16_vector_search()
    fp32_vector_search()
```

**Comment by yhmo** [comment]
```
=========================fp16_vector_search============================
------------ The top1 ID 1424 of No.1 target vector is not equal to target vector's ID 9369
------------ The top1 ID 6810 of No.6 target vector is not equal to target vector's ID 59
------------ The top1 ID 5324 of No.9 target vector is not equal to target vector's ID 5182
------------ The top1 ID 2742 of No.78 target vector is not equal to target vector's ID 9116
------------ The top1 ID 9669 of No.85 target vector is not equal to target vector's ID 9284
------------ The top1 ID 3190 of No.88 target vector is not equal to target vector's ID 8424
------------ The top1 ID 1007 of No.109 target vector is not equal to target vector's ID 8792
------------ The top1 ID 8551 of No.144 target vector is not equal to target vector's ID 9361
------------ The top1 ID 7624 of No.156 target vector is not equal to target vector's ID 1677
------------ The top1 ID 5804 of No.214 target vector is not equal to target vector's ID 9887
------------ The top1 ID 3067 of No.220 target vector is not equal to target vector's ID 9466
------------ The top1 ID 9941 of No.238 target vector is not equal to target vector's ID 8414
------------ The top1 ID 9208 of No.247 target vector is not equal to target vector's ID 118
------------ The top1 ID 5756 of No.272 target vector is not equal to target vector's ID 470
------------ The top1 ID 1494 of No.278 target vector is not equal to target vector's ID 1297
------------ The top1 ID 2544 of No.342 target vector is not equal to target vector's ID 8343
------------ The top1 ID 1257 of No.366 target vector is not equal to target vector's ID 1824
------------ The top1 ID 5476 of No.384 target vector is not equal to target vector's ID 9198
------------ The top1 ID 2517 of No.389 target vector is not equal to target vector's ID 8621
------------ The top1 ID 7028 of No.411 target vector is not equal to target vector's ID 2430
------------ The top1 ID 2707 of No.418 target vector is not equal to target vector's ID 1686
------------ The top1 ID 9809 of No.423 target vector is not equal to target vector's ID 8647
------------ The top1 ID 2524 of No.442 target vector is not equal to target vector's ID 1439
------------ The top1 ID 2642 of No.450 target vector is not equal to target vector's ID 4643
------------ The top1 ID 8867 of No.495 target vector is not equal to target vector's ID 327
------------ The top1 ID 4003 of No.502 target vector is not equal to target vector's ID 2087
------------ The top1 ID 2977 of No.528 target vector is not equal to target vector's ID 1599
------------ The top1 ID 5479 of No.536 target vector is not equal to target vector's ID 8340
------------ The top1 ID 5476 of No.539 target vector is not equal to target vector's ID 9198
------------ The top1 ID 7058 of No.562 target vector is not equal to target vector's ID 9616
------------ The top1 ID 2977 of No.567 target vector is not equal to target vector's ID 8486
------------ The top1 ID 8629 of No.622 target vector is not equal to target vector's ID 8262
------------ The top1 ID 7268 of No.708 target vector is not equal to target vector's ID 3433
------------ The top1 ID 6342 of No.737 target vector is not equal to target vector's ID 575
------------ The top1 ID 2800 of No.780 target vector is not equal to target vector's ID 1871
------------ The top1 ID 5294 of No.783 target vector is not equal to target vector's ID 985
------------ The top1 ID 1556 of No.791 target vector is not equal to target vector's ID 3978
------------ The top1 ID 5577 of No.793 target vector is not equal to target vector's ID 1354
------------ The top1 ID 458 of No.806 target vector is not equal to target vector's ID 9741
------------ The top1 ID 6382 of No.813 target vector is not equal to target vector's ID 1875
------------ The top1 ID 1995 of No.816 target vector is not equal to target vector's ID 3502
------------ The top1 ID 2096 of No.838 target vector is not equal to target vector's ID 990
------------ The top1 ID 8867 of No.861 target vector is not equal to target vector's ID 327
------------ The top1 ID 398 of No.889 target vector is not equal to target vector's ID 9675
------------ The top1 ID 1287 of No.907 target vector is not equal to target vector's ID 2247
------------ The top1 ID 3455 of No.914 target vector is not equal to target vector's ID 9537
------------ The top1 ID 3617 of No.918 target vector is not equal to target vector's ID 9977
------------ The top1 ID 9481 of No.932 target vector is not equal to target vector's ID 347
------------ The top1 ID 8612 of No.948 target vector is not equal to target vector's ID 9565
------------ The top1 ID 4917 of No.973 target vector is not equal to target vector's ID 9566
------------ The top1 ID 4429 of No.979 target vector is not equal to target vector's ID 8959
------------ The top1 ID 288 of No.990 target vector is not equal to target vector's ID 596
Unmatched items: 52
=========================fp32_vector_search============================
------------ The top1 ID 748 of No.12 target vector is not equal to target vector's ID 9640
------------ The top1 ID 765 of No.55 target vector is not equal to target vector's ID 1041
------------ The top1 ID 7727 of No.75 target vector is not equal to target vector's ID 711
------------ The top1 ID 9421 of No.84 target vector is not equal to target vector's ID 1871
------------ The top1 ID 7969 of No.114 target vector is not equal to target vector's ID 9243
------------ The top1 ID 7976 of No.120 target vector is not equal to target vector's ID 1202
------------ The top1 ID 7370 of No.122 target vector is not equal to target vector's ID 1071
------------ The top1 ID 5266 of No.137 target vector is not equal to target vector's ID 9783
------------ The top1 ID 3892 of No.140 target vector is not equal to target vector's ID 8958
------------ The top1 ID 3137 of No.144 target vector is not equal to target vector's ID 1207
------------ The top1 ID 2146 of No.181 target vector is not equal to target vector's ID 8545
------------ The top1 ID 9774 of No.190 target vector is not equal to target vector's ID 277
------------ The top1 ID 9008 of No.223 target vector is not equal to target vector's ID 830
------------ The top1 ID 5675 of No.243 target vector is not equal to target vector's ID 9766
------------ The top1 ID 4431 of No.260 target vector is not equal to target vector's ID 8481
------------ The top1 ID 1193 of No.270 target vector is not equal to target vector's ID 8663
------------ The top1 ID 810 of No.280 target vector is not equal to target vector's ID 2775
------------ The top1 ID 7669 of No.295 target vector is not equal to target vector's ID 2127
------------ The top1 ID 5185 of No.300 target vector is not equal to target vector's ID 54
------------ The top1 ID 8758 of No.337 target vector is not equal to target vector's ID 2991
------------ The top1 ID 1494 of No.446 target vector is not equal to target vector's ID 1134
------------ The top1 ID 3869 of No.517 target vector is not equal to target vector's ID 9371
------------ The top1 ID 7732 of No.578 target vector is not equal to target vector's ID 92
------------ The top1 ID 9849 of No.624 target vector is not equal to target vector's ID 641
------------ The top1 ID 9941 of No.628 target vector is not equal to target vector's ID 8414
------------ The top1 ID 767 of No.655 target vector is not equal to target vector's ID 88
------------ The top1 ID 9330 of No.659 target vector is not equal to target vector's ID 3572
------------ The top1 ID 7935 of No.687 target vector is not equal to target vector's ID 9889
------------ The top1 ID 9328 of No.688 target vector is not equal to target vector's ID 3076
------------ The top1 ID 9834 of No.698 target vector is not equal to target vector's ID 923
------------ The top1 ID 767 of No.717 target vector is not equal to target vector's ID 88
------------ The top1 ID 4186 of No.759 target vector is not equal to target vector's ID 756
------------ The top1 ID 1642 of No.770 target vector is not equal to target vector's ID 9515
------------ The top1 ID 7596 of No.828 target vector is not equal to target vector's ID 9700
------------ The top1 ID 7216 of No.834 target vector is not equal to target vector's ID 1541
------------ The top1 ID 7935 of No.870 target vector is not equal to target vector's ID 9889
------------ The top1 ID 6239 of No.871 target vector is not equal to target vector's ID 3952
------------ The top1 ID 6239 of No.887 target vector is not equal to target vector's ID 3952
------------ The top1 ID 2099 of No.891 target vector is not equal to target vector's ID 314
------------ The top1 ID 9830 of No.895 target vector is not equal to target vector's ID 175
------------ The top1 ID 9303 of No.899 target vector is not equal to target vector's ID 8902
------------ The top1 ID 5120 of No.914 target vector is not equal to target vector's ID 1098
------------ The top1 ID 7624 of No.949 target vector is not equal to target vector's ID 1677
------------ The top1 ID 4172 of No.972 target vector is not equal to target vector's ID 5288
------------ The top1 ID 1846 of No.976 target vector is not equal to target vector's ID 9947
------------ The top1 ID 5681 of No.995 target vector is not equal to target vector's ID 9807
Unmatched items: 46

Process finished with exit code 0

```

**Comment by yhmo** [comment]
The parameters are too small: "M": 16, "efConstruction": 64
Set to "M": 64, "efConstruction": 200, then no such problem.

**Comment by cqy123456** [comment]
When HNSW use random dataset, it will often happen early stop search iteration  and return.
