### ISSUE TITLE
[Bug]:  panic: unsupported data type: Float16Vector

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#31534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20240322-c27db43b-amd64
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): go-sdk
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

standalone or queryNode panic when run case with fp16 vectors:
[stand_qsx48.log](https://github.com/milvus-io/milvus/files/14719674/stand_qsx48.log)
```
[2024/03/22 07:03:35.192 +00:00] [ERROR] [typeutil/schema.go:979] ["Not supported data type"] ["data type"=Float16Vector] [stack="github.com/milvus-io/milvus/pkg/util/typeutil.MergeFieldData\n\t/go/src/github.com/milvus-io/milvus/pkg/util/typeutil/schema.go:979\ngithub.com/milvus-io/milvus/internal/querynodev2/pipeline.(*insertNode).addInsertData\n\t/go/src/github.com/milvus-io/milvus/internal/querynodev2/pipeline/insert_node.go:63\ngithub.com/milvus-io/milvus/internal/querynodev2/pipeline.(*insertNode).Operate\n\t/go/src/github.com/milvus-io/milvus/internal/querynodev2/pipeline/insert_node.go:106\ngithub.com/milvus-io/milvus/internal/util/pipeline.(*nodeCtx).work\n\t/go/src/github.com/milvus-io/milvus/internal/util/pipeline/node.go:78"]
[2024/03/22 07:03:35.192 +00:00] [ERROR] [pipeline/insert_node.go:65] ["failed to merge field data"] [error="unsupported data type: Float16Vector"] [errorVerbose="unsupported data type: Float16Vector\n(1) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus/pkg/util/typeutil.MergeFieldData\n  | \t/go/src/github.com/milvus-io/milvus/pkg/util/typeutil/schema.go:980\n  | github.com/milvus-io/milvus/internal/querynodev2/pipeline.(*insertNode).addInsertData\n  | \t/go/src/github.com/milvus-io/milvus/internal/querynodev2/pipeline/insert_node.go:63\n  | github.com/milvus-io/milvus/internal/querynodev2/pipeline.(*insertNode).Operate\n  | \t/go/src/github.com/milvus-io/milvus/internal/querynodev2/pipeline/insert_node.go:106\n  | github.com/milvus-io/milvus/internal/util/pipeline.(*nodeCtx).work\n  | \t/go/src/github.com/milvus-io/milvus/internal/util/pipeline/node.go:78\n  | runtime.goexit\n  | \t/usr/local/go/src/runtime/asm_amd64.s:1598\nWraps: (2) unsupported data type: Float16Vector\nError types: (1) *withstack.withStack (2) *errutil.leafError"] [stack="github.com/milvus-io/milvus/internal/querynodev2/pipeline.(*insertNode).addInsertData\n\t/go/src/github.com/milvus-io/milvus/internal/querynodev2/pipeline/insert_node.go:65\ngithub.com/milvus-io/milvus/internal/querynodev2/pipeline.(*insertNode).Operate\n\t/go/src/github.com/milvus-io/milvus/internal/querynodev2/pipeline/insert_node.go:106\ngithub.com/milvus-io/milvus/internal/util/pipeline.(*nodeCtx).work\n\t/go/src/github.com/milvus-io/milvus/internal/util/pipeline/node.go:78"]
panic: unsupported data type: Float16Vector

goroutine 31687 [running]:
panic({0x5017f00, 0xc003c06030})
    /usr/local/go/src/runtime/panic.go:987 +0x3bb fp=0xc003f099c0 sp=0xc003f09900 pc=0x1b9dddb
github.com/milvus-io/milvus/internal/querynodev2/pipeline.(*insertNode).addInsertData(0xc0052af180, 0xc003c06000?, 0xc0055f2000, 0x0?)
    /go/src/github.com/milvus-io/milvus/internal/querynodev2/pipeline/insert_node.go:66 +0xb4e fp=0xc003f09d88 sp=0xc003f099c0 pc=0x47b3b0e
github.com/milvus-io/milvus/internal/querynodev2/pipeline.(*insertNode).Operate(0xc0052af180, {0x4ceeb40?, 0xc0053c1200})
    /go/src/github.com/milvus-io/milvus/internal/querynodev2/pipeline/insert_node.go:106 +0x25b fp=0xc003f09e90 sp=0xc003f09d88 pc=0x47b3ffb
github.com/milvus-io/milvus/internal/util/pipeline.(*nodeCtx).work(0xc0052af200)
    /go/src/github.com/milvus-io/milvus/internal/util/pipeline/node.go:78 +0x207 fp=0xc003f09fc8 sp=0xc003f09e90 pc=0x47ae127
github.com/milvus-io/milvus/internal/util/pipeline.(*nodeCtx).Start.func1()
    /go/src/github.com/milvus-io/milvus/internal/util/pipeline/node.go:52 +0x26 fp=0xc003f09fe0 sp=0xc003f09fc8 pc=0x47ade86
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc003f09fe8 sp=0xc003f09fe0 pc=0x1bd7c21
created by github.com/milvus-io/milvus/internal/util/pipeline.(*nodeCtx).Start
    /go/src/github.com/milvus-io/milvus/internal/util/pipeline/node.go:52 +0x7b
```

### Steps To Reproduce

```markdown
https://github.com/milvus-io/milvus-sdk-go/actions/runs/8384679074?pr=685
```

**Comment by xiaofan-luan** [comment]
seems that the float 16 vector is not working at all

**Comment by xiaofan-luan** [comment]
did we release BF16/float vector support? hopefully it's no

**Comment by ThreadDao** [comment]
> did we release BF16/float vector support? hopefully it's no

This issue seems to only exist on the master branch. v2.4.0-rc.1 works
