### ISSUE TITLE
[Bug]: search failed with error `failed to search: node offline[node=-1]: channel not available[channel=by-dev-rootcoord-dml_xxv1]` after minio pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#31714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20240328-6c6764bca-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2024-03-28T20:16:06.243Z] [2024-03-28 20:14:22 - INFO - ci_test]: [setup_method] Start setup test case test_milvus_default. (client_base.py:45)

[2024-03-28T20:16:06.243Z] ------------------------------ Captured log call -------------------------------

[2024-03-28T20:16:06.243Z] [2024-03-28 20:14:22 - DEBUG - ci_test]: (api_request)  : [Connections.connect] args: ['default', '', '', 'default', ''], kwargs: {'host': '10.255.254.250', 'port': 19530} (api_request.py:62)

[2024-03-28T20:16:06.243Z] [2024-03-28 20:14:22 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-03-28T20:16:06.243Z] [2024-03-28 20:14:22 - DEBUG - ci_test]: (api_request)  : [Connections.has_connection] args: ['default'], kwargs: {} (api_request.py:62)

[2024-03-28T20:16:06.243Z] [2024-03-28 20:14:22 - DEBUG - ci_test]: (api_response) : True  (api_request.py:37)

[2024-03-28T20:16:06.243Z] [2024-03-28 20:14:22 - DEBUG - ci_test]: (api_request)  : [Collection] args: ['Checker__8PaEqJ2o', {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}, {'name': 'varchar', 'description': '', 'type': <DataType......, kwargs: {'consistency_level': 'Strong'} (api_request.py:62)

[2024-03-28T20:16:06.243Z] [2024-03-28 20:14:22 - DEBUG - ci_test]: (api_response) : <Collection>:

[2024-03-28T20:16:06.243Z] -------------

[2024-03-28T20:16:06.243Z] <name>: Checker__8PaEqJ2o

[2024-03-28T20:16:06.243Z] <description>: 

[2024-03-28T20:16:06.243Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}......  (api_request.py:37)

[2024-03-28T20:16:06.243Z] [2024-03-28 20:14:22 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-03-28T20:16:06.243Z] [2024-03-28 20:14:23 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-03-28T20:16:06.243Z] [2024-03-28 20:14:23 - DEBUG - ci_test]: (api_request)  : [Collection.compact] args: [180], kwargs: {} (api_request.py:62)

[2024-03-28T20:16:06.243Z] [2024-03-28 20:14:23 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-03-28T20:16:06.243Z] [2024-03-28 20:14:38 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-03-28T20:16:06.243Z] [2024-03-28 20:14:38 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-03-28T20:16:06.243Z] [2024-03-28 20:14:38 - INFO - ci_test]: assert create collection: 0.3132951259613037, init_entities: 136970 (test_all_collections_after_chaos.py:49)

[2024-03-28T20:16:06.243Z] [2024-03-28 20:14:43 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [[[-3000, -2999, -2998, -2997, -2996, -2995, -2994, -2993, -2992, -2991, -2990, -2989, -2988, -2987, -2986, -2985, -2984, -2983, -2982, -2981, -2980, -2979, -2978, -2977, -2976, -2975, -2974, -2973, -2972, -2971, -2970, -2969, -2968, -2967, -2966, -2965, -2964, -2963, -2962, -2961, -2960, -2959, -29......, kwargs: {'timeout': 180} (api_request.py:62)

[2024-03-28T20:16:06.244Z] [2024-03-28 20:14:44 - DEBUG - ci_test]: (api_response) : (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 448700582114099201, success count: 2000, err count: 0)  (api_request.py:37)

[2024-03-28T20:16:06.244Z] [2024-03-28 20:14:44 - INFO - ci_test]: assert insert: 1.904996633529663 (test_all_collections_after_chaos.py:57)

[2024-03-28T20:16:06.244Z] [2024-03-28 20:14:44 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-03-28T20:16:06.244Z] [2024-03-28 20:14:48 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-03-28T20:16:06.244Z] [2024-03-28 20:14:48 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-03-28T20:16:06.244Z] [2024-03-28 20:14:48 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-03-28T20:16:06.244Z] [2024-03-28 20:14:48 - INFO - ci_test]: assert flush: 4.0370917320251465, entities: 138970 (test_all_collections_after_chaos.py:67)

[2024-03-28T20:16:06.244Z] [2024-03-28 20:14:48 - INFO - ci_test]: index info: [{'collection': 'Checker__8PaEqJ2o', 'field': 'voice_emb', 'index_name': 'voice_emb', 'index_param': {'params': {'M': 48, 'efConstruction': 500}, 'index_type': 'HNSW', 'metric_type': 'L2'}}, {'collection': 'Checker__8PaEqJ2o', 'field': 'int64', 'index_name': 'int64', 'index_param': {'index_type': 'INVERTED'}}, {'collection': 'Checker__8PaEqJ2o', 'field': 'float', 'index_name': 'float', 'index_param': {'index_type': 'INVERTED'}}, {'collection': 'Checker__8PaEqJ2o', 'field': 'varchar', 'index_name': 'varchar', 'index_param': {'index_type': 'INVERTED'}}, {'collection': 'Checker__8PaEqJ2o', 'field': 'float_vector', 'index_name': 'float_vector', 'index_param': {'params': {'M': 48, 'efConstruction': 500}, 'index_type': 'HNSW', 'metric_type': 'L2'}}, {'collection': 'Checker__8PaEqJ2o', 'field': 'image_emb', 'index_name': 'image_emb', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}, {'collection': 'Checker__8PaEqJ2o', 'field': 'text_emb', 'index_name': 'text_emb', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}] (test_all_collections_after_chaos.py:71)

[2024-03-28T20:16:06.244Z] [2024-03-28 20:14:48 - INFO - ci_test]: index info: [{'collection': 'Checker__8PaEqJ2o', 'field': 'float', 'index_name': 'float', 'index_param': {'index_type': 'INVERTED'}}, {'collection': 'Checker__8PaEqJ2o', 'field': 'varchar', 'index_name': 'varchar', 'index_param': {'index_type': 'INVERTED'}}, {'collection': 'Checker__8PaEqJ2o', 'field': 'float_vector', 'index_name': 'float_vector', 'index_param': {'params': {'M': 48, 'efConstruction': 500}, 'index_type': 'HNSW', 'metric_type': 'L2'}}, {'collection': 'Checker__8PaEqJ2o', 'field': 'image_emb', 'index_name': 'image_emb', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}, {'collection': 'Checker__8PaEqJ2o', 'field': 'text_emb', 'index_name': 'text_emb', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}, {'collection': 'Checker__8PaEqJ2o', 'field': 'voice_emb', 'index_name': 'voice_emb', 'index_param': {'params': {'M': 48, 'efConstruction': 500}, 'index_type': 'HNSW', 'metric_type': 'L2'}}, {'collection': 'Checker__8PaEqJ2o', 'field': 'int64', 'index_name': 'int64', 'index_param': {'index_type': 'INVERTED'}}] (test_all_collections_after_chaos.py:86)

[2024-03-28T20:16:06.244Z] [2024-03-28 20:14:48 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 180], kwargs: {} (api_request.py:62)

[2024-03-28T20:16:06.244Z] [2024-03-28 20:14:48 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-03-28T20:16:06.244Z] [2024-03-28 20:14:48 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.015080120245242766, 0.02154321477886245, 0.022973933330329648, 0.03066019420113086, 0.0769283413638094, 0.13839518486244615, 0.06899186850250774, 0.023920794877803072, 0.042448970724905895, 0.10576735536737746, 0.09472221994961415, 0.01053230213579698, 0.009535434537086275, 0.03811712222337497,......, kwargs: {} (api_request.py:62)

[2024-03-28T20:16:06.244Z] [2024-03-28 20:14:48 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=503, message=failed to search: node offline[node=-1]: channel not available[channel=by-dev-rootcoord-dml_8_448699972765691773v1])>, <Time:{'RPC start': '2024-03-28 20:14:48.604105', 'RPC error': '2024-03-28 20:14:48.608296'}> (decorators.py:146)

[2024-03-28T20:16:06.244Z] [2024-03-28 20:14:48 - ERROR - ci_test]: Traceback (most recent call last):

[2024-03-28T20:16:06.244Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2024-03-28T20:16:06.244Z]     res = func(*args, **_kwargs)

[2024-03-28T20:16:06.244Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2024-03-28T20:16:06.244Z]     return func(*arg, **kwargs)

[2024-03-28T20:16:06.244Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 792, in search

[2024-03-28T20:16:06.244Z]     resp = conn.search(

[2024-03-28T20:16:06.244Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 147, in handler

[2024-03-28T20:16:06.244Z]     raise e from e

[2024-03-28T20:16:06.244Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 143, in handler

[2024-03-28T20:16:06.244Z]     return func(*args, **kwargs)

[2024-03-28T20:16:06.244Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 182, in handler

[2024-03-28T20:16:06.244Z]     return func(self, *args, **kwargs)

[2024-03-28T20:16:06.244Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 122, in handler

[2024-03-28T20:16:06.244Z]     raise e from e

[2024-03-28T20:16:06.244Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 87, in handler

[2024-03-28T20:16:06.244Z]     return func(*args, **kwargs)

[2024-03-28T20:16:06.244Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 794, in search

[2024-03-28T20:16:06.244Z]     return self._execute_search(request, timeout, round_decimal=round_decimal, **kwargs)

[2024-03-28T20:16:06.244Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 735, in _execute_search

[2024-03-28T20:16:06.244Z]     raise e from e

[2024-03-28T20:16:06.244Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 728, in _execute_search

[2024-03-28T20:16:06.244Z]     check_status(response.status)

[2024-03-28T20:16:06.244Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/utils.py", line 60, in check_status

[2024-03-28T20:16:06.244Z]     raise MilvusException(status.code, status.reason, status.error_code)

[2024-03-28T20:16:06.244Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=503, message=failed to search: node offline[node=-1]: channel not available[channel=by-dev-rootcoord-dml_8_448699972765691773v1])>

[2024-03-28T20:16:06.244Z]  (api_request.py:45)

[2024-03-28T20:16:06.244Z] [2024-03-28 20:14:48 - ERROR - ci_test]: (api_response) : <MilvusException: (code=503, message=failed to search: node offline[node=-1]: channel not available[channel=by-dev-rootcoord-dml_8_448699972765691773v1])> (api_request.py:46)
```
```
2024-03-28T20:13:29.448Z] + kubectl get pods -o wide

[2024-03-28T20:13:29.449Z] + grep s3-pod-kill-12711

[2024-03-28T20:13:29.705Z] s3-pod-kill-12711-etcd-0                                          1/1     Running            0                 40m     10.104.31.154   4am-node34   <none>           <none>

[2024-03-28T20:13:29.705Z] s3-pod-kill-12711-etcd-1                                          1/1     Running            0                 40m     10.104.21.19    4am-node24   <none>           <none>

[2024-03-28T20:13:29.705Z] s3-pod-kill-12711-etcd-2                                          1/1     Running            0                 40m     10.104.27.238   4am-node31   <none>           <none>

[2024-03-28T20:13:29.705Z] s3-pod-kill-12711-kafka-0                                         2/2     Running            1 (38m ago)       40m     10.104.21.13    4am-node24   <none>           <none>

[2024-03-28T20:13:29.705Z] s3-pod-kill-12711-kafka-1                                         2/2     Running            1 (38m ago)       40m     10.104.33.119   4am-node36   <none>           <none>

[2024-03-28T20:13:29.705Z] s3-pod-kill-12711-kafka-2                                         2/2     Running            0                 40m     10.104.31.156   4am-node34   <none>           <none>

[2024-03-28T20:13:29.705Z] s3-pod-kill-12711-kafka-exporter-5c69785764-6qpvf                 1/1     Running            5 (39m ago)       40m     10.104.31.106   4am-node34   <none>           <none>

[2024-03-28T20:13:29.705Z] s3-pod-kill-12711-milvus-datacoord-5595f5b85b-2dxph               1/1     Running            0                 40m     10.104.1.241    4am-node10   <none>           <none>

[2024-03-28T20:13:29.705Z] s3-pod-kill-12711-milvus-datanode-6d49d5bdc9-lrkmp                1/1     Running            0                 40m     10.104.6.56     4am-node13   <none>           <none>

[2024-03-28T20:13:29.705Z] s3-pod-kill-12711-milvus-datanode-6d49d5bdc9-v6pk2                1/1     Running            0                 40m     10.104.1.245    4am-node10   <none>           <none>

[2024-03-28T20:13:29.705Z] s3-pod-kill-12711-milvus-indexcoord-5875544d57-9jp59              1/1     Running            0                 40m     10.104.1.242    4am-node10   <none>           <none>

[2024-03-28T20:13:29.705Z] s3-pod-kill-12711-milvus-indexnode-66754df48b-dhbps               1/1     Running            0                 40m     10.104.31.110   4am-node34   <none>           <none>

[2024-03-28T20:13:29.705Z] s3-pod-kill-12711-milvus-indexnode-66754df48b-qbkpz               1/1     Running            0                 40m     10.104.1.246    4am-node10   <none>           <none>

[2024-03-28T20:13:29.705Z] s3-pod-kill-12711-milvus-indexnode-66754df48b-r4rbr               1/1     Running            1 (15m ago)       40m     10.104.5.68     4am-node12   <none>           <none>

[2024-03-28T20:13:29.705Z] s3-pod-kill-12711-milvus-proxy-78684444c7-t7bfj                   1/1     Running            1 (36m ago)       40m     10.104.31.107   4am-node34   <none>           <none>

[2024-03-28T20:13:29.705Z] s3-pod-kill-12711-milvus-querycoord-dddd5df5d-mtd9l               1/1     Running            0                 40m     10.104.1.244    4am-node10   <none>           <none>

[2024-03-28T20:13:29.705Z] s3-pod-kill-12711-milvus-querynode-698865df54-5kbjq               1/1     Running            0                 40m     10.104.31.108   4am-node34   <none>           <none>

[2024-03-28T20:13:29.705Z] s3-pod-kill-12711-milvus-querynode-698865df54-kqfw6               1/1     Running            0                 40m     10.104.6.55     4am-node13   <none>           <none>

[2024-03-28T20:13:29.705Z] s3-pod-kill-12711-milvus-querynode-698865df54-qvzkg               1/1     Running            1 (10m ago)       40m     10.104.1.243    4am-node10   <none>           <none>

[2024-03-28T20:13:29.705Z] s3-pod-kill-12711-milvus-rootcoord-5ddd96bb56-v2qz5               1/1     Running            0                 40m     10.104.31.105   4am-node34   <none>           <none>

[2024-03-28T20:13:29.705Z] s3-pod-kill-12711-minio-0                                         1/1     Running            0                 11m     10.104.31.195   4am-node34   <none>           <none>

[2024-03-28T20:13:29.705Z] s3-pod-kill-12711-minio-1                                         1/1     Running            0                 11m     10.104.21.81    4am-node24   <none>           <none>

[2024-03-28T20:13:29.705Z] s3-pod-kill-12711-minio-2                                         1/1     Running            0                 11m     10.104.27.17    4am-node31   <none>           <none>

[2024-03-28T20:13:29.705Z] s3-pod-kill-12711-minio-3                                         1/1     Running            0                 11m     10.104.33.184   4am-node36   <none>           <none>

[2024-03-28T20:13:29.705Z] s3-pod-kill-12711-zookeeper-0                                     1/1     Running            0                 40m     10.104.31.153   4am-node34   <none>           <none>

[2024-03-28T20:13:29.705Z] s3-pod-kill-12711-zookeeper-1                                     1/1     Running            0                 40m     10.104.21.18    4am-node24   <none>           <none>

[2024-03-28T20:13:29.705Z] s3-pod-kill-12711-zookeeper-2                                     1/1     Running            0                 40m     10.104.27.237   4am-node31   <none>           <none>
```
indexnode and querynode restart once during minio chaos

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-cron/detail/chaos-test-kafka-cron/12711/pipeline
log:
[artifacts-s3-pod-kill-12711-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/14798592/artifacts-s3-pod-kill-12711-server-logs.tar.gz)

**Comment by zhuwenxing** [comment]
not reproduced for a long time
