### ISSUE TITLE
[Bug]: [Nightly]The dimension of new file is inconsistent as expected

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#31958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 23ba2a5
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The dimension of new file is inconsistent as expected.
case: test_search_with_expression_bool
error message: 
```
[2024-04-07 16:14:21 - ERROR - pymilvus.decorators]: RPC error: [insert_rows], <ParamError: (code=1, message=Collection field dim is 128, but entities field dim is 32)>, <Time:{'RPC start': '2024-04-07 16:14:21.211323', 'RPC error': '2024-04-07 16:14:21.219354'}> (decorators.py:146)
[2024-04-07 16:14:21 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/zilliz/nico/milvus/tests/python_client/utils/api_request.py", line 32, in inner_wrapper
    res = func(*args, **_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/nico/milvus/tests/python_client/utils/api_request.py", line 63, in api_request
    return func(*arg, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/orm/collection.py", line 508, in insert
    return conn.insert_rows(
           ^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 147, in handler
    raise e from e
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 143, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 182, in handler
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 122, in handler
    raise e from e
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 87, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 509, in insert_rows
    request = self._prepare_row_insert_request(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 490, in _prepare_row_insert_request
    return Prepare.row_insert_param(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/client/prepare.py", line 433, in row_insert_param
    return cls._parse_row_request(request, fields_info, enable_dynamic, entities)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/client/prepare.py", line 405, in _parse_row_request
    _, _, auto_id_loc = traverse_rows_info(fields_info, entities)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/client/utils.py", line 258, in traverse_rows_info
    raise ParamError(
pymilvus.exceptions.ParamError: <ParamError: (code=1, message=Collection field dim is 128, but entities field dim is 32)>
 (api_request.py:45)
[2024-04-07 16:14:21 - ERROR - ci_test]: (api_response) : <ParamError: (code=1, message=Collection field dim is 128, but entities field dim is 32)> (api_request.py:46)
```

The error comes from here:
```
    for i in range(num):
        log.debug("Dynamic field is enabled: %s" % enable_dynamic_field)
        if not is_binary:
            if not is_all_data_type:
                if not enable_dynamic_field:
                    default_data = gen_default_dataframe_data(nb // num, dim=dim, start=start, with_json=with_json,
                                                              random_primary_key=random_primary_key,
                                                              multiple_dim_array=multiple_dim_array,
                                                              multiple_vector_field_name=vector_name_list,
                                                              vector_data_type=vector_data_type)
                else:
                    default_data = gen_default_rows_data(nb // num, dim=dim, start=start, with_json=with_json,
                                                         multiple_dim_array=multiple_dim_array,
                                                         multiple_vector_field_name=vector_name_list,
                                                         vector_data_type=vector_data_type)

            else:
                if not enable_dynamic_field:
                    default_data = gen_dataframe_all_data_type(nb // num, dim=dim, start=start, with_json=with_json,
                                                           random_primary_key=random_primary_key,
                                                           multiple_dim_array=multiple_dim_array,
                                                           multiple_vector_field_name=vector_name_list)
                else:
                    if os.path.exists(ct.rows_all_data_type_file_path + f'_{i}' + '.txt'):
                        with open(ct.rows_all_data_type_file_path + f'_{i}' + '.txt', 'rb') as f:
                            default_data = pickle.load(f)
                    else:
                        default_data = gen_default_rows_data_all_data_type(nb // num, dim=dim, start=start,
                                                                           with_json=with_json,
                                                                           multiple_dim_array=multiple_dim_array,
                                                                           multiple_vector_field_name=vector_name_list,
                                                                           partition_id = i)
```

### Expected Behavior

pass

**Comment by binbinlv** [comment]
I think this is for test case error, not milvus bug, @NicoYuan1986  please modify the test case as we discussed, and then verify this issue.
