### ISSUE TITLE
[Bug]: [CI] Failed to search with float32 vector for defined FLOAT_VECTOR field with error message "unsupported data type: float64"

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#31994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):2.5.0rc5
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

pymilvus==2.5.0rc5 or pymilvus==2.4.1rc4

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-31827/1/pipeline/253/

error message:
```
[2024-04-02T09:53:32.832Z] [2024-04-02 09:53:22 - DEBUG - ci_test]: (api_request)  : [MilvusClient.search] args: ['milvus_client_api_collection_rL7xw8Ym', array([[0.88836589, 0.74824547, 0.99065863, 0.53721989, 0.03771318,
[2024-04-02T09:53:32.832Z]         0.71147818, 0.81163864, 0.20759547, 0.04890721, 0.45205939,
[2024-04-02T09:53:32.832Z]         0.7550809 , 0.09795961, 0.34022963, 0.71357128, 0.7813125 ,
[2024-04-02T09:53:32.832Z]         0.14229097, 0.53672895, 0.33001076, 0.93663012......, kwargs: {'timeout': 120} (api_request.py:62)
[2024-04-02T09:53:32.832Z] [2024-04-02 09:53:22 - ERROR - pymilvus.decorators]: RPC error: [search], <ParamError: (code=1, message=unsupported data type: float64)>, <Time:{'RPC start': '2024-04-02 09:53:22.379985', 'RPC error': '2024-04-02 09:53:22.380278'}> (decorators.py:146)
[2024-04-02T09:53:32.832Z] [2024-04-02 09:53:22 - ERROR - pymilvus.milvus_client.milvus_client]: Failed to search collection: milvus_client_api_collection_rL7xw8Ym (milvus_client.py:318)
[2024-04-02T09:53:32.832Z] [2024-04-02 09:53:22 - ERROR - ci_test]: Traceback (most recent call last):
[2024-04-02T09:53:32.832Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper
[2024-04-02T09:53:32.832Z]     res = func(*args, **_kwargs)
[2024-04-02T09:53:32.832Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request
[2024-04-02T09:53:32.832Z]     return func(*arg, **kwargs)
[2024-04-02T09:53:32.832Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 319, in search
[2024-04-02T09:53:32.832Z]     raise ex from ex
[2024-04-02T09:53:32.832Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 305, in search
[2024-04-02T09:53:32.832Z]     res = conn.search(
[2024-04-02T09:53:32.832Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 147, in handler
[2024-04-02T09:53:32.832Z]     raise e from e
[2024-04-02T09:53:32.832Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 143, in handler
[2024-04-02T09:53:32.832Z]     return func(*args, **kwargs)
[2024-04-02T09:53:32.832Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 182, in handler
[2024-04-02T09:53:32.832Z]     return func(self, *args, **kwargs)
[2024-04-02T09:53:32.832Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 122, in handler
[2024-04-02T09:53:32.832Z]     raise e from e
[2024-04-02T09:53:32.832Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 87, in handler
[2024-04-02T09:53:32.832Z]     return func(*args, **kwargs)
[2024-04-02T09:53:32.832Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 782, in search
[2024-04-02T09:53:32.832Z]     request = Prepare.search_requests_with_expr(
[2024-04-02T09:53:32.832Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/prepare.py", line 671, in search_requests_with_expr
[2024-04-02T09:53:32.832Z]     plg_str = cls._prepare_placeholder_str(data)
[2024-04-02T09:53:32.832Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/prepare.py", line 599, in _prepare_placeholder_str
[2024-04-02T09:53:32.832Z]     raise ParamError(message=err_msg)
[2024-04-02T09:53:32.832Z] pymilvus.exceptions.ParamError: <ParamError: (code=1, message=unsupported data type: float64)>
[2024-04-02T09:53:32.832Z]  (api_request.py:45)
[2024-04-02T09:53:32.832Z] [2024-04-02 09:53:22 - ERROR - ci_test]: (api_response) : <ParamError: (code=1, message=unsupported data type: float64)> (api_request.py:46)
[2024-04-02T09:53:32.832Z] [2024-04-02 09:53:22 - INFO - ci_test]: search_results_check: checking the searching results (func_check.py:295)
[2024-04-02T09:53:32.832Z] [2024-04-02 09:53:22 - WARNING - ci_test]: The function name is search rather than search or hybrid_search (func_check.py:297)
```

### Expected Behavior

pass

**Comment by NicoYuan1986** [comment]
failed case: test_milvus_client_search_query_default
```
    @pytest.mark.tags(CaseLabel.L1)
    def test_milvus_client_search_query_default(self):
        """
        target: test search (high level api) normal case
        method: create connection, collection, insert and search
        expected: search/query successfully
        """
        client = self._connect(enable_milvus_client_api=True)
        collection_name = cf.gen_unique_str(prefix)
        client_w.using_database(client, "default")
        # 1. create collection
        client_w.create_collection(client, collection_name, default_dim, consistency_level="Strong")
        collections = client_w.list_collections(client)[0]
        assert collection_name in collections
        client_w.describe_collection(client, collection_name,
                                     check_task=CheckTasks.check_describe_collection_property,
                                     check_items={"collection_name": collection_name,
                                                  "dim": default_dim,
                                                  "consistency_level": 0})
        # 2. insert
        rng = np.random.default_rng(seed=19530)
        rows = [{default_primary_key_field_name: i, default_vector_field_name: list(rng.random((1, default_dim))[0]),
                 default_float_field_name: i * 1.0, default_string_field_name: str(i)} for i in range(default_nb)]
        client_w.insert(client, collection_name, rows)
        # client_w.flush(client, collection_name)
        # assert client_w.num_entities(client, collection_name)[0] == default_nb
        # 3. search
        vectors_to_search = rng.random((1, default_dim))
        insert_ids = [i for i in range(default_nb)]
        client_w.search(client, collection_name, vectors_to_search,
                        check_task=CheckTasks.check_search_results,
                        check_items={"enable_milvus_client_api": True,
                                     "nq": len(vectors_to_search),
                                     "ids": insert_ids,
                                     "limit": default_limit})
```
The vector type is 101(FLOAT_VECTOR)

**Comment by binbinlv** [comment]
@NicoYuan1986 
Please modify the title to show what vector type you defined, and what is the type of your searched vector, then whether it is matched?
