### ISSUE TITLE
[Bug]: failed to load collection, err=failed to spawn replica for collection[nodes not enough]

### ISSUE THREAD

**Issue by MonikaVijayakumar25** [milvus-io/milvus#32014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.13
- Deployment mode(standalone or cluster):Standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):2.4.0
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Getting error while try to load collection in both API, Milvus attu tool. Error: failed to load collection, err=failed to spawn replica for collection[nodes not enough].

Note: For the Past 1 week, I'm facing new issues like created db few of them got deleted. Now the collection has created and data has inserted successfully but unable to load the collection while do search

conn = connections.connect( host=_HOST, port=_PORT, db_name=_DB_NAME)
db.using_database(_DB_NAME)
collection = Collection(collectionName)
...
collection.load()
res = collection.query(
        expr=filterExpr,
        offset=0,
        limit=100,
        output_fields=["id"]
    )
   

### Expected Behavior

Collection should be load successfully without any error

### Steps To Reproduce

```markdown
No Idea on how and why this issue occurs?
```

### Milvus Log

2024-04-08 15:50:59	
[2024/04/08 10:20:59.492 +00:00] [INFO] [proxy/impl.go:662] ["LoadCollection done"] [traceID=67cf8a9e68f3d75b] [role=proxy] [MsgID=448940385096695809] [BeginTS=448940385096695809] [EndTS=448940385096695809] [db=Compass_appdev_icompass_new] [collection=Compass_A1002]
2024-04-08 15:50:59	
[2024/04/08 10:20:59.492 +00:00] [INFO] [proxy/task.go:1463] ["loadCollectionTask PostExecute"] [role=proxy] [msgID=448940385096695809]
2024-04-08 15:50:59	
[2024/04/08 10:20:59.492 +00:00] [WARN] [retry/retry.go:44] ["retry func failed"] ["retry time"=0] [error="failed to load collection, err=failed to spawn replica for collection[nodes not enough]"]
2024-04-08 15:50:59	
[2024/04/08 10:20:59.491 +00:00] [WARN] [querycoordv2/services.go:269] ["failed to load collection"] [msgID=448940385096695809] [collectionID=448800203707788725] [replicaNumber=1] [resourceGroups="[]"] [refreshMode=false] [error="failed to spawn replica for collection[nodes not enough]"]
2024-04-08 15:50:59	
[2024/04/08 10:20:59.491 +00:00] [INFO] [job/scheduler.go:153] ["job finished"] [msgID=448940385096695809] [collectionID=448800203707788725]
2024-04-08 15:50:59	
[2024/04/08 10:20:59.491 +00:00] [INFO] [meta/target_manager.go:262] ["remove collection from targets"] [collectionID=448800203707788725]
2024-04-08 15:50:59	
[2024/04/08 10:20:59.487 +00:00] [INFO] [job/scheduler.go:151] ["start to post-execute job"] [msgID=448940385096695809] [collectionID=448800203707788725]
2024-04-08 15:50:59	
[2024/04/08 10:20:59.487 +00:00] [WARN] [job/scheduler.go:168] ["failed to execute job"] [msgID=448940385096695809] [collectionID=448800203707788725] [error="failed to spawn replica for collection[nodes not enough]"]
2024-04-08 15:50:59	
[2024/04/08 10:20:59.487 +00:00] [ERROR] [job/job.go:197] ["failed to spawn replica for collection"] [traceID=67cf8a9e68f3d75b] [collectionID=448800203707788725] [error="nodes not enough"] [stack="github.com/milvus-io/milvus/internal/querycoordv2/job.(*LoadCollectionJob).Execute\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/job/job.go:197\ngithub.com/milvus-io/milvus/internal/querycoordv2/job.(*Scheduler).process\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/job/scheduler.go:166\ngithub.com/milvus-io/milvus/internal/querycoordv2/job.(*Scheduler).processQueue\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/job/scheduler.go:141"]
2024-04-08 15:50:59	
[2024/04/08 10:20:59.487 +00:00] [ERROR] [utils/meta.go:132] ["nodes not enough"] [collectionID=448800203707788725] [replicas="[448800203853267154]"] [rgName=__default_resource_group] [stack="github.com/milvus-io/milvus/internal/querycoordv2/utils.AssignNodesToReplicas\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/utils/meta.go:132\ngithub.com/milvus-io/milvus/internal/querycoordv2/utils.SpawnAllReplicasInRG\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/utils/meta.go:196\ngithub.com/milvus-io/milvus/internal/querycoordv2/utils.SpawnReplicasWithRG\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/utils/meta.go:217\ngithub.com/milvus-io/milvus/internal/querycoordv2/job.(*LoadCollectionJob).Execute\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/job/job.go:190\ngithub.com/milvus-io/milvus/internal/querycoordv2/job.(*Scheduler).process\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/job/scheduler.go:166\ngithub.com/milvus-io/milvus/internal/querycoordv2/job.(*Scheduler).processQueue\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/job/scheduler.go:141"]
2024-04-08 15:50:59	
[2024/04/08 10:20:59.483 +00:00] [INFO] [meta/failed_load_cache.go:109] ["FailedLoadCache removes cache"] [collectionID=448800203707788725]
2024-04-08 15:50:59	
[2024/04/08 10:20:59.483 +00:00] [INFO] [job/scheduler.go:165] ["start to execute job"] [msgID=448940385096695809] [collectionID=448800203707788725]
2024-04-08 15:50:59	
[2024/04/08 10:20:59.483 +00:00] [INFO] [job/scheduler.go:157] ["start to pre-execute job"] [msgID=448940385096695809] [collectionID=448800203707788725]
2024-04-08 15:50:59	
[2024/04/08 10:20:59.482 +00:00] [INFO] [querycoordv2/services.go:233] ["load collection request received"] [msgID=448940385096695809] [collectionID=448800203707788725] [replicaNumber=1] [resourceGroups="[]"] [refreshMode=false] [schema="name:\"Compass_A1002\" description:\"compass pdf files collection\" fields:<fieldID:100 name:\"id\" is_primary_key:true data_type:Int64 autoID:true > fields:<fieldID:101 name:\"parent_id\" description:\"document/article/guide record id\" data_type:VarChar type_params:<key:\"max_length\" value:\"200\" > > fields:<fieldID:102 name:\"parent_type\" description:\"document/article/guide\" data_type:VarChar type_params:<key:\"max_length\" value:\"200\" > > fields:<fieldID:103 name:\"title\" description:\"title or pdf File name\" data_type:VarChar type_params:<key:\"max_length\" value:\"500\" > > fields:<fieldID:104 name:\"filename\" description:\"title or pdf File name\" data_type:VarChar type_params:<key:\"max_length\" value:\"500\" > > fields:<fieldID:105 name:\"page_no\" description:\"pdf file page no\" data_type:VarChar type_params:<key:\"max_length\" value:\"200\" > > fields:<fieldID:106 name:\"context_part\" description:\"context part by _MAX_CHAR\" data_type:VarChar type_params:<key:\"max_length\" value:\"200\" > > fields:<fieldID:107 name:\"context\" description:\"page wise pdf context or article context\" data_type:VarChar type_params:<key:\"max_length\" value:\"32768\" > > fields:<fieldID:108 name:\"context_embedding\" description:\"Embedding vectors of context\" data_type:FloatVector type_params:<key:\"dim\" value:\"1536\" > > fields:<fieldID:109 name:\"segment_url\" description:\"segment url\" data_type:VarChar type_params:<key:\"max_length\" value:\"2000\" > > fields:<fieldID:110 name:\"$meta\" description:\"dynamic schema\" data_type:JSON is_dynamic:true > enable_dynamic_field:true "] [fieldIndexes="[448800203707788730]"]
2024-04-08 15:50:59	
[2024/04/08 10:20:59.481 +00:00] [INFO] [proxy/task.go:1452] ["send LoadCollectionRequest to query coordinator"] [role=proxy] [msgID=448940385096695809] [collectionID=448800203707788725] [schema="name:\"Compass_A1002\" description:\"compass pdf files collection\" fields:<fieldID:100 name:\"id\" is_primary_key:true data_type:Int64 autoID:true > fields:<fieldID:101 name:\"parent_id\" description:\"document/article/guide record id\" data_type:VarChar type_params:<key:\"max_length\" value:\"200\" > > fields:<fieldID:102 name:\"parent_type\" description:\"document/article/guide\" data_type:VarChar type_params:<key:\"max_length\" value:\"200\" > > fields:<fieldID:103 name:\"title\" description:\"title or pdf File name\" data_type:VarChar type_params:<key:\"max_length\" value:\"500\" > > fields:<fieldID:104 name:\"filename\" description:\"title or pdf File name\" data_type:VarChar type_params:<key:\"max_length\" value:\"500\" > > fields:<fieldID:105 name:\"page_no\" description:\"pdf file page no\" data_type:VarChar type_params:<key:\"max_length\" value:\"200\" > > fields:<fieldID:106 name:\"context_part\" description:\"context part by _MAX_CHAR\" data_type:VarChar type_params:<key:\"max_length\" value:\"200\" > > fields:<fieldID:107 name:\"context\" description:\"page wise pdf context or article context\" data_type:VarChar type_params:<key:\"max_length\" value:\"32768\" > > fields:<fieldID:108 name:\"context_embedding\" description:\"Embedding vectors of context\" data_type:FloatVector type_params:<key:\"dim\" value:\"1536\" > > fields:<fieldID:109 name:\"segment_url\" description:\"segment url\" data_type:VarChar type_params:<key:\"max_length\" value:\"2000\" > > fields:<fieldID:110 name:\"$meta\" description:\"dynamic schema\" data_type:JSON is_dynamic:true > enable_dynamic_field:true "]
2024-04-08 15:50:59	
[2024/04/08 10:20:59.481 +00:00] [INFO] [indexcoord/index_coord.go:959] ["IndexCoord describe index success"] [collectionID=448800203707788725] [indexID=448800203707788730] ["total rows"=1] ["indexed rows"=1] ["pending index rows"=0] ["index state"=Finished] [segments="[]"]
2024-04-08 15:50:59	
[2024/04/08 10:20:59.481 +00:00] [INFO] [indexcoord/index_coord.go:636] ["IndexCoord completeIndexInfo success"] [collID=448800203707788725] [totalRows=1] [indexRows=1] [state=Finished] [failReason=]
2024-04-08 15:50:59	
[2024/04/08 10:20:59.481 +00:00] [INFO] [indexcoord/meta_table.go:659] ["IndexCoord get index states success"] [indexID=448800203707788730] [total=0] [None=0] [Unissued=0] [InProgress=0] [Finished=0] [Failed=0]
2024-04-08 15:50:59	
[2024/04/08 10:20:59.481 +00:00] [INFO] [indexcoord/index_coord.go:611] ["IndexCoord completeIndexInfo"] [collID=448800203707788725] [indexName=_default_idx_108]
2024-04-08 15:50:59	
[2024/04/08 10:20:59.480 +00:00] [INFO] [datacoord/services.go:828] ["datacoord append channelInfo in GetRecoveryInfo"] [collectionID=448800203707788725] [partitionIDs="[]"] [channel=by-dev-rootcoord-dml_5_448800203707788725v0] ["# of unflushed segments"=0] ["# of flushed segments"=1] ["# of dropped segments"=0]
2024-04-08 15:50:59	
[2024/04/08 10:20:59.480 +00:00] [INFO] [datacoord/handler.go:288] ["channel seek position set from channel checkpoint meta"] [channel=by-dev-rootcoord-dml_5_448800203707788725v0] [posTs=448940380430532611] [posTime=2024/04/08 10:20:41.657 +00:00]
2024-04-08 15:50:59	
[2024/04/08 10:20:59.480 +00:00] [INFO] [datacoord/handler.go:119] [GetQueryVChanPositions] [collectionID=448800203707788725] [channel=by-dev-rootcoord-dml_5_448800203707788725v0] [numOfSegments=1]
2024-04-08 15:50:59	
[2024/04/08 10:20:59.479 +00:00] [INFO] [rootcoord/root_coord.go:1198] ["done to describe collection"] [traceID=97d7b806859a6da] ["collection name"=] [dbName=] [id=448800203707788725] [msgID=0] [ts=18446744073709551615] [allowUnavailable=true] [collection_id=448800203707788725]
2024-04-08 15:50:59	
[2024/04/08 10:20:59.479 +00:00] [INFO] [rootcoord/root_coord.go:1165] ["received request to describe collection"] [traceID=97d7b806859a6da] ["collection name"=] [dbName=] [id=448800203707788725] [msgID=0] [ts=18446744073709551615] [allowUnavailable=true]
2024-04-08 15:50:59	
[2024/04/08 10:20:59.478 +00:00] [INFO] [datacoord/services.go:792] ["get recovery info request received"] [collectionID=448800203707788725] [partitionIDs="[]"]
2024-04-08 15:50:59	
[2024/04/08 10:20:59.477 +00:00] [INFO] [datacoord/services.go:897] ["received get flushed segments request"] [collectionID=448800203707788725] [partitionID=-1]
2024-04-08 15:50:59	
[2024/04/08 10:20:59.476 +00:00] [INFO] [indexcoord/index_coord.go:894] ["IndexCoord DescribeIndex"] [collectionID=448800203707788725] [indexName=] [timestamp=0]
2024-04-08 15:50:59	
[2024/04/08 10:20:59.476 +00:00] [INFO] [proxy/task.go:1401] ["loadCollectionTask Execute"] [role=proxy] [msgID=448940385096695809]
2024-04-08 15:50:59	
[2024/04/08 10:20:59.476 +00:00] [INFO] [proxy/task.go:1382] ["loadCollectionTask PreExecute"] [role=proxy] [msgID=448940385096695809]

**Comment by xiaofan-luan** [comment]
if there are some querynodes works, you could release and load with replica=1 and the problem should be solved

**Comment by xiaofan-luan** [comment]
/assign @MonikaVijayakumar25

And we recommended to use 2.2.16 or 2.3.13 if possible

**Comment by yanliang567** [comment]
@MonikaVijayakumar25 I did not reproduce this issue on milvus 2.3.13 with pymilvus 2.3.7 or pymilvus 2.3.6. Please retry with that. if it reproduced to you, please help to offer the full milvus logs for investigations.
Could you please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
For Milvus installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs.

/assign @MonikaVijayakumar25 
/unassign

**Comment by Gy-hy** [comment]
2025-03-11 15:26:18,750 [ERROR][handler]: RPC error: [load_collection], <MilvusException: (code=65535, message=call query coordinator LoadCollection: failed to spawn replica for collection: resource group node not enough[rg=__default_resource_group][currentNodeNum=0][expectedNodeNum=1])>, <Time:{'RPC start': '2025-03-11 15:26:18.716803', 'RPC error': '2025-03-11 15:26:18.750433'}> (decorators.py:140)
Traceback (most recent call last):
  File "F:\aiops24-RAG-demo-glm\Aiops-RAG\tools\杂.py", line 111, in <module>
    collection.load(_resource_group="__default_resource_group")
  File "D:\miniforge3\envs\myenv\lib\site-packages\pymilvus\orm\collection.py", line 427, in load
    conn.load_collection(
  File "D:\miniforge3\envs\myenv\lib\site-packages\pymilvus\decorators.py", line 141, in handler
    raise e from e
  File "D:\miniforge3\envs\myenv\lib\site-packages\pymilvus\decorators.py", line 137, in handler
    return func(*args, **kwargs)
  File "D:\miniforge3\envs\myenv\lib\site-packages\pymilvus\decorators.py", line 176, in handler
    return func(self, *args, **kwargs)
  File "D:\miniforge3\envs\myenv\lib\site-packages\pymilvus\decorators.py", line 116, in handler
    raise e from e
  File "D:\miniforge3\envs\myenv\lib\site-packages\pymilvus\decorators.py", line 86, in handler
    return func(*args, **kwargs)
  File "D:\miniforge3\envs\myenv\lib\site-packages\pymilvus\client\grpc_handler.py", line 1220, in load_collection
    check_status(response)
  File "D:\miniforge3\envs\myenv\lib\site-packages\pymilvus\client\utils.py", line 64, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=call query coordinator LoadCollection: failed to spawn replica for collection: resource group node not enough[rg=__default_resource_group][currentNodeNum=0][expectedNodeNum=1])>

**Comment by xiaofan-luan** [comment]
> currentNodeNum

Seems that there is no alive querynode in your cluster.
Didn't see crashoff loop?

**Comment by nisharyan** [comment]
> 2025-03-11 15:26:18,750 [ERROR][handler]: RPC error: [load_collection], <MilvusException: (code=65535, message=call query coordinator LoadCollection: failed to spawn replica for collection: resource group node not enough[rg=__default_resource_group][currentNodeNum=0][expectedNodeNum=1])>, <Time:{'RPC start': '2025-03-11 15:26:18.716803', 'RPC error': '2025-03-11 15:26:18.750433'}> (decorators.py:140) Traceback (most recent call last): File "F:\aiops24-RAG-demo-glm\Aiops-RAG\tools\杂.py", line 111, in collection.load(_resource_group="__default_resource_group") File "D:\miniforge3\envs\myenv\lib\site-packages\pymilvus\orm\collection.py", line 427, in load conn.load_collection( File "D:\miniforge3\envs\myenv\lib\site-packages\pymilvus\decorators.py", line 141, in handler raise e from e File "D:\miniforge3\envs\myenv\lib\site-packages\pymilvus\decorators.py", line 137, in handler return func(*args, **kwargs) File "D:\miniforge3\envs\myenv\lib\site-packages\pymilvus\decorators.py", line 176, in handler return func(self, *args, **kwargs) File "D:\miniforge3\envs\myenv\lib\site-packages\pymilvus\decorators.py", line 116, in handler raise e from e File "D:\miniforge3\envs\myenv\lib\site-packages\pymilvus\decorators.py", line 86, in handler return func(*args, **kwargs) File "D:\miniforge3\envs\myenv\lib\site-packages\pymilvus\client\grpc_handler.py", line 1220, in load_collection check_status(response) File "D:\miniforge3\envs\myenv\lib\site-packages\pymilvus\client\utils.py", line 64, in check_status raise MilvusException(status.code, status.reason, status.error_code) pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=call query coordinator LoadCollection: failed to spawn replica for collection: resource group node not enough[rg=__default_resource_group][currentNodeNum=0][expectedNodeNum=1])>

Facing similar issue

Also attu says, milvus is not ready yet
Milvus query node and query co-ordinator pods are up

**Comment by yanliang567** [comment]
> > 2025-03-11 15:26:18,750 [ERROR][handler]: RPC error: [load_collection], <MilvusException: (code=65535, message=call query coordinator LoadCollection: failed to spawn replica for collection: resource group node not enough[rg=__default_resource_group][currentNodeNum=0][expectedNodeNum=1])>, <Time:{'RPC start': '2025-03-11 15:26:18.716803', 'RPC error': '2025-03-11 15:26:18.750433'}> (decorators.py:140) Traceback (most recent call last): File "F:\aiops24-RAG-demo-glm\Aiops-RAG\tools\杂.py", line 111, in collection.load(_resource_group="__default_resource_group") File "D:\miniforge3\envs\myenv\lib\site-packages\pymilvus\orm\collection.py", line 427, in load conn.load_collection( File "D:\miniforge3\envs\myenv\lib\site-packages\pymilvus\decorators.py", line 141, in handler raise e from e File "D:\miniforge3\envs\myenv\lib\site-packages\pymilvus\decorators.py", line 137, in handler return func(*args, **kwargs) File "D:\miniforge3\envs\myenv\lib\site-packages\pymilvus\decorators.py", line 176, in handler return func(self, *args, **kwargs) File "D:\miniforge3\envs\myenv\lib\site-packages\pymilvus\decorators.py", line 116, in handler raise e from e File "D:\miniforge3\envs\myenv\lib\site-packages\pymilvus\decorators.py", line 86, in handler return func(*args, **kwargs) File "D:\miniforge3\envs\myenv\lib\site-packages\pymilvus\client\grpc_handler.py", line 1220, in load_collection check_status(response) File "D:\miniforge3\envs\myenv\lib\site-packages\pymilvus\client\utils.py", line 64, in check_status raise MilvusException(status.code, status.reason, status.error_code) pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=call query coordinator LoadCollection: failed to spawn replica for collection: resource group node not enough[rg=__default_resource_group][currentNodeNum=0][expectedNodeNum=1])>
> 
> Facing similar issue
> 
> Also attu says, milvus is not ready yet Milvus query node and query co-ordinator pods are up

i suggest you file a new issue and upload the full milvus logs for investigations. If you install Milvus with k8s, please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs

**Comment by nisharyan** [comment]
Yes it is k8s deployment using helm. I redeployed after cleaning up etcd PV and it started working.
