### ISSUE TITLE
[Bug]: [benchmark][standalone][LRU] Milvus standalone panic when calling get_real_count if enable disk cache, and Milvus OOM

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#32135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:milvus-io-lru-dev-adfed78-20240410
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):2.4.0rc66
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task：lru-fouramf-qbsr9

server：
```
NAME                                                              READY   STATUS                            RESTARTS        AGE     IP              NODE         NOMINATED NODE   READINESS GATES
lru-scene12-not-autoid-high-etcd-0                                1/1     Running                           0               129m    10.104.33.195   4am-node36   <none>           <none>
lru-scene12-not-autoid-high-milvus-standalone-7fff5b4f46-28f99    1/1     Running                           12 (15m ago)    129m    10.104.34.113   4am-node37   <none>           <none>
lru-scene12-not-autoid-high-minio-bfcc87bc8-pj8sx                 1/1     Running                           0               129m    10.104.15.104   4am-node20   <none>           <none>
lru-scene12-not-autoid-high-pulsar-bookie-0                       1/1     Running                           0               129m    10.104.30.248   4am-node38   <none>           <none>
lru-scene12-not-autoid-high-pulsar-bookie-1                       1/1     Running                           0               129m    10.104.15.106   4am-node20   <none>           <none>
lru-scene12-not-autoid-high-pulsar-bookie-2                       1/1     Running                           0               129m    10.104.17.163   4am-node23   <none>           <none>
lru-scene12-not-autoid-high-pulsar-bookie-init-m4pk7              0/1     Completed                         0               129m    10.104.17.153   4am-node23   <none>           <none>
lru-scene12-not-autoid-high-pulsar-broker-0                       1/1     Running                           0               129m    10.104.29.3     4am-node35   <none>           <none>
lru-scene12-not-autoid-high-pulsar-proxy-0                        1/1     Running                           0               129m    10.104.6.65     4am-node13   <none>           <none>
lru-scene12-not-autoid-high-pulsar-pulsar-init-vnc58              0/1     Completed                         0               129m    10.104.18.30    4am-node25   <none>           <none>
lru-scene12-not-autoid-high-pulsar-recovery-0                     1/1     Running                           0               129m    10.104.4.158    4am-node11   <none>           <none>
lru-scene12-not-autoid-high-pulsar-zookeeper-0                    1/1     Running                           0               129m    10.104.20.122   4am-node22   <none>           <none>
lru-scene12-not-autoid-high-pulsar-zookeeper-1                    1/1     Running                           0               128m    10.104.21.199   4am-node24   <none>           <none>
lru-scene12-not-autoid-high-pulsar-zookeeper-2                    1/1     Running                           0               127m    10.104.15.131   4am-node20   <none>           <none>
```
[milvus_panic.log](https://github.com/milvus-io/milvus/files/14932012/milvus_panic.log)

<img width="1407" alt="截屏2024-04-10 20 18 39" src="https://github.com/milvus-io/milvus/assets/26307815/4cc2c36d-7176-4227-8668-0856fe1ecbc9">

**exitcode**
<img width="1424" alt="截屏2024-04-10 20 23 25" src="https://github.com/milvus-io/milvus/assets/26307815/6d669f2e-3020-4f7a-8af1-6cb57e7017f1">

**resource usage**
<img width="1433" alt="截屏2024-04-10 20 24 36" src="https://github.com/milvus-io/milvus/assets/26307815/92236390-6ae7-48cd-8188-501fb6aa5b4b">

client pod name:  lru-fouramf-qbsr9-1644853595

### Steps To Reproduce

```markdown
1. create a collection with 3 fields: id(primaryKey), float_vector(768dim), int64_1(partitionKey=64)
2. build HNSW index
3. prepare 10w data
4. flush collection
5. build index again with the same params
6. load collection
7. concurrent requests:
   - insert: nb=64
   - delete: length=64
   - flush
   - load
   - search
   - query
```

### Anything else?

test config:
```
{
     "dataset_params": {
          "dataset_name": "laion1b_nolang",
          "column_name": "float32_vector",
          "dim": 768,
          "dataset_size": "10w",
          "ni_per": 10000,
          "metric_type": "L2",
          "scalars_params": {
               "int64_1": {
                    "params": {
                         "is_partition_key": true
                    }
               }
          }
     },
     "collection_params": {
          "other_fields": [
               "int64_1"
          ],
          "num_partitions": 64
     },
     "index_params": {
          "index_type": "HNSW",
          "index_param": {
               "M": 30,
               "efConstruction": 360
          }
     },
     "concurrent_tasks": [
          {
               "type": "insert",
               "weight": 1,
               "params": {
                    "nb": 64,
                    "timeout": 3000,
                    "random_vector": true
               }
          },
          {
               "type": "delete",
               "weight": 1,
               "params": {
                    "delete_length": 64,
                    "timeout": 3000
               }
          },
          {
               "type": "flush",
               "weight": 1,
               "params": {
                    "timeout": 3000
               }
          },
          {
               "type": "load",
               "weight": 1,
               "params": {
                    "timeout": 3000
               }
          },
          {
               "type": "search",
               "weight": 1,
               "params": {
                    "top_k": 1,
                    "nq": 10,
                    "search_param": {
                         "ef": 64
                    },
                    "expr": "int64_1 >= 0 && int64_1 <= 4",
                    "timeout": 3000,
                    "random_data": true
               }
          },
          {
               "type": "query",
               "weight": 1,
               "params": {
                    "expr": "int64_1 != 2",
                    "timeout": 3000,
                    "offset": 0,
                    "limit": 10
               }
          }
     ],
     "concurrent_params": {
          "interval": 20,
          "during_time": "12h",
          "concurrent_number": 10
     }
}
```

**Comment by chyezh** [comment]
```
Common labels: {"app":"milvus","cluster":"4am","component":"standalone","container":"standalone","job":"qa-milvus/milvus","namespace":"qa-milvus","node_name":"4am-node37","pod":"lru-scene12-not-autoid-high-milvus-standalone-7fff5b4f46-28f99","stream":"stderr"}
Line limit: "5000 (8 returned)"
Total bytes processed: "94.1  kB"


2024-04-10 19:28:10.132	terminate called after throwing an instance of 'milvus::SegcoreError'
2024-04-10 19:28:10.132	  what():  Assert "is_sealed" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/InsertRecord.h:282
2024-04-10 19:28:10.132	 => OffsetOrderedArray could not search before seal
2024-04-10 19:28:10.135	SIGABRT: abort
2024-04-10 19:28:10.135	PC=0x7f076fec903b m=360 sigcode=18446744073709551610
2024-04-10 19:28:10.135	signal arrived during cgo execution
2024-04-10 19:28:10.135	
2024-04-10 19:28:10.135	goroutine 247705 [syscall, locked to thread]:
```

**Comment by chyezh** [comment]
@wangting0128 please verify with latest `lru-dev` commit.

**Comment by wangting0128** [comment]
### recurrent OOM

argo task：lru-fouramf-5bqnk
test image：milvus-io-lru-dev-fbd02f7-20240418

server：
```
[2024-04-19 00:35:23,897 -  INFO - fouram]: [Base] Deploy initial state: 
I0418 12:31:58.143792     435 request.go:665] Waited for 1.162998842s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.local/apis/events.k8s.io/v1beta1?timeout=32s
NAME                                                              READY   STATUS                            RESTARTS        AGE     IP              NODE         NOMINATED NODE   READINESS GATES
lru-verify-32135-dml-dql-etcd-0                                   1/1     Running                           0               4m19s   10.104.31.127   4am-node34   <none>           <none>
lru-verify-32135-dml-dql-milvus-standalone-85c8c769c9-bx8bs       1/1     Running                           0               4m19s   10.104.29.158   4am-node35   <none>           <none>
lru-verify-32135-dml-dql-minio-f5b9f5559-9ffh5                    1/1     Running                           0               4m19s   10.104.31.121   4am-node34   <none>           <none>
lru-verify-32135-dml-dql-pulsar-bookie-0                          1/1     Running                           0               4m19s   10.104.26.138   4am-node32   <none>           <none>
lru-verify-32135-dml-dql-pulsar-bookie-1                          1/1     Running                           0               4m19s   10.104.27.84    4am-node31   <none>           <none>
lru-verify-32135-dml-dql-pulsar-bookie-2                          1/1     Running                           0               4m19s   10.104.32.144   4am-node39   <none>           <none>
lru-verify-32135-dml-dql-pulsar-bookie-init-fpbf8                 0/1     Completed                         0               4m19s   10.104.4.157    4am-node11   <none>           <none>
lru-verify-32135-dml-dql-pulsar-broker-0                          1/1     Running                           0               4m19s   10.104.13.129   4am-node16   <none>           <none>
lru-verify-32135-dml-dql-pulsar-proxy-0                           1/1     Running                           0               4m19s   10.104.1.21     4am-node10   <none>           <none>
lru-verify-32135-dml-dql-pulsar-pulsar-init-k9hfv                 0/1     Completed                         0               4m19s   10.104.4.155    4am-node11   <none>           <none>
lru-verify-32135-dml-dql-pulsar-recovery-0                        1/1     Running                           0               4m19s   10.104.4.154    4am-node11   <none>           <none>
lru-verify-32135-dml-dql-pulsar-zookeeper-0                       1/1     Running                           0               4m19s   10.104.31.119   4am-node34   <none>           <none>
lru-verify-32135-dml-dql-pulsar-zookeeper-1                       1/1     Running                           0               3m40s   10.104.20.186   4am-node22   <none>           <none>
lru-verify-32135-dml-dql-pulsar-zookeeper-2                       1/1     Running                           0               3m5s    10.104.32.146   4am-node39   <none>           <none> (base.py:257)
[2024-04-19 00:35:23,897 -  INFO - fouram]: [Cmd Exe]  kubectl get pods  -n qa-milvus  -o wide | grep -E 'NAME|lru-verify-32135-dml-dql-milvus|lru-verify-32135-dml-dql-minio|lru-verify-32135-dml-dql-etcd|lru-verify-32135-dml-dql-pulsar|lru-verify-32135-dml-dql-zookeeper|lru-verify-32135-dml-dql-kafka|lru-verify-32135-dml-dql-log|lru-verify-32135-dml-dql-tikv'  (util_cmd.py:14)
[2024-04-19 00:35:33,660 -  INFO - fouram]: [CliClient] pod details of release(lru-verify-32135-dml-dql): 
 I0419 00:35:25.165001     542 request.go:665] Waited for 1.141232489s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.local/api/v1?timeout=32s
NAME                                                              READY   STATUS                            RESTARTS         AGE     IP              NODE         NOMINATED NODE   READINESS GATES
lru-verify-32135-dml-dql-etcd-0                                   1/1     Running                           0                12h     10.104.31.127   4am-node34   <none>           <none>
lru-verify-32135-dml-dql-milvus-standalone-85c8c769c9-bx8bs       1/1     Running                           31 (25m ago)     12h     10.104.29.158   4am-node35   <none>           <none>
lru-verify-32135-dml-dql-minio-f5b9f5559-9ffh5                    1/1     Running                           0                12h     10.104.31.121   4am-node34   <none>           <none>
lru-verify-32135-dml-dql-pulsar-bookie-0                          1/1     Running                           0                12h     10.104.26.138   4am-node32   <none>           <none>
lru-verify-32135-dml-dql-pulsar-bookie-1                          1/1     Running                           0                12h     10.104.27.84    4am-node31   <none>           <none>
lru-verify-32135-dml-dql-pulsar-bookie-2                          1/1     Running                           0                12h     10.104.32.144   4am-node39   <none>           <none>
lru-verify-32135-dml-dql-pulsar-bookie-init-fpbf8                 0/1     Completed                         0                12h     10.104.4.157    4am-node11   <none>           <none>
lru-verify-32135-dml-dql-pulsar-broker-0                          1/1     Running                           0                12h     10.104.13.129   4am-node16   <none>           <none>
lru-verify-32135-dml-dql-pulsar-proxy-0                           1/1     Running                           0                12h     10.104.1.21     4am-node10   <none>           <none>
lru-verify-32135-dml-dql-pulsar-pulsar-init-k9hfv                 0/1     Completed                         0                12h     10.104.4.155    4am-node11   <none>           <none>
lru-verify-32135-dml-dql-pulsar-recovery-0                        1/1     Running                           0                12h     10.104.4.154    4am-node11   <none>           <none>
lru-verify-32135-dml-dql-pulsar-zookeeper-0                       1/1     Running                           0                12h     10.104.31.119   4am-node34   <none>           <none>
lru-verify-32135-dml-dql-pulsar-zookeeper-1                       1/1     Running                           0                12h     10.104.20.186   4am-node22   <none>           <none>
lru-verify-32135-dml-dql-pulsar-zookeeper-2                       1/1     Running                           0                12h     10.104.32.146   4am-node39   <none>           <none>
```
<img width="1439" alt="截屏2024-04-19 11 24 02" src="https://github.com/milvus-io/milvus/assets/26307815/f2a3ad96-4965-474f-9e83-9f1423291265">

client pod name: lru-fouramf-5bqnk-894457795
client log:
<img width="1440" alt="截屏2024-04-19 11 23 35" src="https://github.com/milvus-io/milvus/assets/26307815/4699d26e-a951-4bd2-a504-0a793ee0540e">


test result:
```
[2024-04-19 00:34:07,101 -  INFO - fouram]: Print locust final stats. (locust_runner.py:56)
[2024-04-19 00:34:07,102 -  INFO - fouram]: Type     Name                                                                          # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s (stats.py:789)
[2024-04-19 00:34:07,102 -  INFO - fouram]: --------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|----------- (stats.py:789)
[2024-04-19 00:34:07,102 -  INFO - fouram]: grpc     delete                                                                          3337  730(21.88%) |     30       0    2914      9 |    0.08        0.02 (stats.py:789)
[2024-04-19 00:34:07,102 -  INFO - fouram]: grpc     flush                                                                           3323     0(0.00%) |  21116     507  643408   5600 |    0.08        0.00 (stats.py:789)
[2024-04-19 00:34:07,102 -  INFO - fouram]: grpc     insert                                                                          3359  639(19.02%) |    574      21  197158    160 |    0.08        0.02 (stats.py:789)
[2024-04-19 00:34:07,102 -  INFO - fouram]: grpc     load                                                                            3227     0(0.00%) |  99088       4 2335355    110 |    0.08        0.00 (stats.py:789)
[2024-04-19 00:34:07,102 -  INFO - fouram]: grpc     query                                                                           3345 2675(79.97%) |   4097       1  210574    800 |    0.08        0.06 (stats.py:789)
[2024-04-19 00:34:07,102 -  INFO - fouram]: grpc     search                                                                          3286 2641(80.37%) |   4080       5  210151    820 |    0.08        0.06 (stats.py:789)
[2024-04-19 00:34:07,102 -  INFO - fouram]: --------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|----------- (stats.py:789)
[2024-04-19 00:34:07,102 -  INFO - fouram]:          Aggregated                                                                     19877 6685(33.63%) |  21083       0 2335355    290 |    0.47        0.16 (stats.py:789)
[2024-04-19 00:34:07,102 -  INFO - fouram]:  (stats.py:790)
[2024-04-19 00:34:07,105 -  INFO - fouram]: [PerfTemplate] Report data: 
{'server': {'deploy_tool': 'helm',
            'deploy_mode': 'standalone',
            'config_name': 'standalone_8c16m',
            'config': {'standalone': {'resources': {'limits': {'cpu': '16',
                                                               'memory': '8Gi',
                                                               'ephemeral-storage': '70Gi'},
                                                    'requests': {'cpu': '16',
                                                                 'memory': '8Gi'}},
                                      'messageQueue': 'pulsar',
                                      'extraEnv': [{'name': 'LOCAL_STORAGE_SIZE',
                                                    'value': '70'}],
                                      'disk': {'size': {'enabled': True}}},
                       'cluster': {'enabled': False},
                       'etcd': {'replicaCount': 1,
                                'metrics': {'enabled': True,
                                            'podMonitor': {'enabled': True}}},
                       'minio': {'mode': 'standalone',
                                 'metrics': {'podMonitor': {'enabled': True}},
                                 'persistence': {'size': '320Gi'}},
                       'pulsar': {'enabled': True},
                       'metrics': {'serviceMonitor': {'enabled': True}},
                       'log': {'level': 'debug'},
                       'extraConfigFiles': {'user.yaml': 'queryNode:\n'
                                                         '  '
                                                         'diskCacheCapacityLimit: '
                                                         '51539607552\n'
                                                         '  mmap:\n'
                                                         '    mmapEnabled: '
                                                         'true\n'
                                                         '  lazyloadEnabled: '
                                                         'true\n'
                                                         '  '
                                                         'useStreamComputing: '
                                                         'true\n'
                                                         '  cache:\n'
                                                         '    warmup: sync\n'
                                                         '  '
                                                         'lazyloadWaitTimeout: '
                                                         '300000\n'},
                       'image': {'all': {'repository': 'harbor.milvus.io/milvus/milvus',
                                         'tag': 'milvus-io-lru-dev-fbd02f7-20240418'}}},
            'host': 'lru-verify-32135-dml-dql-milvus.qa-milvus.svc.cluster.local',
            'port': '19530',
            'uri': ''},
 'client': {'test_case_type': 'ConcurrentClientBase',
            'test_case_name': 'test_concurrent_locust_custom_parameters',
            'test_case_params': {'dataset_params': {'metric_type': 'L2',
                                                    'column_name': 'float32_vector',
                                                    'dim': 768,
                                                    'scalars_params': {'int64_1': {'params': {'is_partition_key': True}}},
                                                    'dataset_name': 'laion1b_nolang',
                                                    'dataset_size': '10w',
                                                    'ni_per': 10000},
                                 'collection_params': {'other_fields': ['int64_1'],
                                                       'num_partitions': 64},
                                 'index_params': {'index_type': 'HNSW',
                                                  'index_param': {'M': 30,
                                                                  'efConstruction': 360}},
                                 'concurrent_params': {'concurrent_number': 10,
                                                       'during_time': '12h',
                                                       'interval': 20,
                                                       'spawn_rate': None},
                                 'concurrent_tasks': [{'type': 'insert',
                                                       'weight': 1,
                                                       'params': {'nb': 64,
                                                                  'timeout': 3000,
                                                                  'random_vector': True}},
                                                      {'type': 'delete',
                                                       'weight': 1,
                                                       'params': {'delete_length': 64,
                                                                  'timeout': 3000}},
                                                      {'type': 'flush',
                                                       'weight': 1,
                                                       'params': {'timeout': 3000}},
                                                      {'type': 'load',
                                                       'weight': 1,
                                                       'params': {'timeout': 3000}},
                                                      {'type': 'search',
                                                       'weight': 1,
                                                       'params': {'top_k': 1,
                                                                  'nq': 10,
                                                                  'search_param': {'ef': 64},
                                                                  'expr': 'int64_1 '
                                                                          '>= '
                                                                          '0 '
                                                                          '&& '
                                                                          'int64_1 '
                                                                          '<= '
                                                                          '4',
                                                                  'timeout': 3000,
                                                                  'random_data': True}},
                                                      {'type': 'query',
                                                       'weight': 1,
                                                       'params': {'expr': 'int64_1 '
                                                                          '!= '
                                                                          '2',
                                                                  'timeout': 3000,
                                                                  'offset': 0,
                                                                  'limit': 10}}]},
            'run_id': 2024041832657011,
            'datetime': '2024-04-18 12:27:45.724594',
            'client_version': '2.2'},
 'result': {'test_result': {'index': {'RT': 64.4586},
                            'insert': {'total_time': 27.8511,
                                       'VPS': 3590.5225,
                                       'batch_time': 2.7851,
                                       'batch': 10000},
                            'flush': {'RT': 6.5546},
                            'load': {'RT': 3.5418},
                            'Locust': {'Aggregated': {'Requests': 19877,
                                                      'Fails': 6685,
                                                      'RPS': 0.47,
                                                      'fail_s': 0.34,
                                                      'RT_max': 2335355.1,
                                                      'RT_avg': 21083.32,
                                                      'TP50': 290.0,
                                                      'TP99': 718000.0},
                                       'delete': {'Requests': 3337,
                                                  'Fails': 730,
                                                  'RPS': 0.08,
                                                  'fail_s': 0.22,
                                                  'RT_max': 2914.8,
                                                  'RT_avg': 30.82,
                                                  'TP50': 9,
                                                  'TP99': 380.0},
                                       'flush': {'Requests': 3323,
                                                 'Fails': 0,
                                                 'RPS': 0.08,
                                                 'fail_s': 0.0,
                                                 'RT_max': 643408.99,
                                                 'RT_avg': 21116.52,
                                                 'TP50': 5600.0,
                                                 'TP99': 634000.0},
                                       'insert': {'Requests': 3359,
                                                  'Fails': 639,
                                                  'RPS': 0.08,
                                                  'fail_s': 0.19,
                                                  'RT_max': 197158.25,
                                                  'RT_avg': 574.35,
                                                  'TP50': 160.0,
                                                  'TP99': 11000.0},
                                       'load': {'Requests': 3227,
                                                'Fails': 0,
                                                'RPS': 0.08,
                                                'fail_s': 0.0,
                                                'RT_max': 2335355.1,
                                                'RT_avg': 99088.49,
                                                'TP50': 110.0,
                                                'TP99': 2035000.0},
                                       'query': {'Requests': 3345,
                                                 'Fails': 2675,
                                                 'RPS': 0.08,
                                                 'fail_s': 0.8,
                                                 'RT_max': 210574.29,
                                                 'RT_avg': 4097.14,
                                                 'TP50': 800.0,
                                                 'TP99': 134000.0},
                                       'search': {'Requests': 3286,
                                                  'Fails': 2641,
                                                  'RPS': 0.08,
                                                  'fail_s': 0.8,
                                                  'RT_max': 210151.75,
                                                  'RT_avg': 4080.13,
                                                  'TP50': 820.0,
                                                  'TP99': 134000.0}}}}}
```

**Comment by wangting0128** [comment]
### verification passed

image: master-20240514-f48a7ff8
argo task: lru-fouramf-wx7vx

test result:
```
{'server': {'deploy_tool': 'helm',
            'deploy_mode': 'standalone',
            'config_name': 'standalone_8c16m',
            'config': {'standalone': {'resources': {'limits': {'cpu': '2',
                                                               'memory': '8Gi',
                                                               'ephemeral-storage': '70Gi'},
                                                    'requests': {'cpu': '2',
                                                                 'memory': '8Gi'}},
                                      'messageQueue': 'pulsar',
                                      'extraEnv': [{'name': 'LOCAL_STORAGE_SIZE',
                                                    'value': '70'}],
                                      'disk': {'size': {'enabled': True}}},
                       'cluster': {'enabled': False},
                       'etcd': {'replicaCount': 1,
                                'metrics': {'enabled': True,
                                            'podMonitor': {'enabled': True}}},
                       'minio': {'mode': 'standalone',
                                 'metrics': {'podMonitor': {'enabled': True}},
                                 'persistence': {'size': '320Gi'}},
                       'pulsar': {'enabled': True},
                       'metrics': {'serviceMonitor': {'enabled': True}},
                       'log': {'level': 'debug'},
                       'extraConfigFiles': {'user.yaml': 'queryNode:\n'
                                                         '  '
                                                         'diskCacheCapacityLimit: '
                                                         '51539607552\n'
                                                         '  mmap:\n'
                                                         '    mmapEnabled: '
                                                         'true\n'
                                                         '  lazyload:\n'
                                                         '    enabled: true\n'
                                                         '    waitTimeout: '
                                                         '300000\n'
                                                         '  '
                                                         'useStreamComputing: '
                                                         'true\n'
                                                         '  cache:\n'
                                                         '    warmup: off\n'},
                       'image': {'all': {'repository': 'harbor.milvus.io/milvus/milvus',
                                         'tag': 'master-20240514-f48a7ff8'}}},
            'host': 'lru-32987-dml-dql-milvus.qa-milvus.svc.cluster.local',
            'port': '19530',
            'uri': ''},
 'client': {'test_case_type': 'ConcurrentClientBase',
            'test_case_name': 'test_concurrent_locust_custom_parameters',
            'test_case_params': {'dataset_params': {'metric_type': 'L2',
                                                    'column_name': 'float32_vector',
                                                    'dim': 768,
                                                    'scalars_params': {'int64_1': {'params': {'is_partition_key': True}}},
                                                    'dataset_name': 'laion1b_nolang',
                                                    'dataset_size': '10w',
                                                    'ni_per': 10000},
                                 'collection_params': {'other_fields': ['int64_1'],
                                                       'num_partitions': 64},
                                 'index_params': {'index_type': 'HNSW',
                                                  'index_param': {'M': 30,
                                                                  'efConstruction': 360}},
                                 'concurrent_params': {'concurrent_number': 10,
                                                       'during_time': '12h',
                                                       'interval': 20,
                                                       'spawn_rate': None},
                                 'concurrent_tasks': [{'type': 'insert',
                                                       'weight': 1,
                                                       'params': {'nb': 64,
                                                                  'timeout': 3000,
                                                                  'random_vector': True}},
                                                      {'type': 'delete',
                                                       'weight': 1,
                                                       'params': {'delete_length': 64,
                                                                  'timeout': 3000}},
                                                      {'type': 'flush',
                                                       'weight': 0,
                                                       'params': {'timeout': 3000}},
                                                      {'type': 'load',
                                                       'weight': 1,
                                                       'params': {'timeout': 3000}},
                                                      {'type': 'search',
                                                       'weight': 1,
                                                       'params': {'top_k': 1,
                                                                  'nq': 10,
                                                                  'search_param': {'ef': 64},
                                                                  'expr': 'int64_1 '
                                                                          '>= '
                                                                          '0 '
                                                                          '&& '
                                                                          'int64_1 '
                                                                          '<= '
                                                                          '4',
                                                                  'timeout': 3000,
                                                                  'random_data': True}},
                                                      {'type': 'query',
                                                       'weight': 1,
                                                       'params': {'expr': 'int64_1 '
                                                                          '!= '
                                                                          '2',
                                                                  'timeout': 3000,
                                                                  'offset': 0,
                                                                  'limit': 10}}]},
            'run_id': 2024051412144173,
            'datetime': '2024-05-14 12:53:34.093352',
            'client_version': '2.2'},
 'result': {'test_result': {'index': {'RT': 63.8284},
                            'insert': {'total_time': 27.8717,
                                       'VPS': 3587.8687,
                                       'batch_time': 2.7872,
                                       'batch': 10000},
                            'flush': {'RT': 4.9282},
                            'load': {'RT': 3.5367},
                            'Locust': {'Aggregated': {'Requests': 624242,
                                                      'Fails': 0,
                                                      'RPS': 14.45,
                                                      'fail_s': 0.0,
                                                      'RT_max': 68522.33,
                                                      'RT_avg': 689.36,
                                                      'TP50': 98,
                                                      'TP99': 15000.0},
                                       'delete': {'Requests': 124461,
                                                  'Fails': 0,
                                                  'RPS': 2.88,
                                                  'fail_s': 0.0,
                                                  'RT_max': 20965.18,
                                                  'RT_avg': 48.13,
                                                  'TP50': 34,
                                                  'TP99': 280.0},
                                       'insert': {'Requests': 124810,
                                                  'Fails': 0,
                                                  'RPS': 2.89,
                                                  'fail_s': 0.0,
                                                  'RT_max': 20390.22,
                                                  'RT_avg': 348.05,
                                                  'TP50': 260.0,
                                                  'TP99': 1800.0},
                                       'load': {'Requests': 125020,
                                                'Fails': 0,
                                                'RPS': 2.89,
                                                'fail_s': 0.0,
                                                'RT_max': 20068.64,
                                                'RT_avg': 75.72,
                                                'TP50': 53,
                                                'TP99': 430.0},
                                       'query': {'Requests': 125121,
                                                 'Fails': 0,
                                                 'RPS': 2.9,
                                                 'fail_s': 0.0,
                                                 'RT_max': 68510.11,
                                                 'RT_avg': 1502.58,
                                                 'TP50': 130.0,
                                                 'TP99': 24000.0},
                                       'search': {'Requests': 124830,
                                                  'Fails': 0,
                                                  'RPS': 2.89,
                                                  'fail_s': 0.0,
                                                  'RT_max': 68522.33,
                                                  'RT_avg': 1469.38,
                                                  'TP50': 110.0,
                                                  'TP99': 23000.0}}}}} 
```
