### ISSUE TITLE
[Bug]: Getting started document does not have instructions on pymilvus package installation.

### ISSUE THREAD

**Issue by deepujain** [milvus-io/milvus#32179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 
- Deployment mode(standalone or cluster): Standalone
- MQ type(rocksmq, pulsar or kafka):    Standalone
- SDK version(e.g. pymilvus v2.0.0rc2):Standalone
- OS(Ubuntu or CentOS): MacOS
- CPU/Memory: 24G
- GPU:  2
- Others:
```

### Current Behavior

```
/usr/local/bin/python3 sentiment-analysis/examples/hr/milvus.py
Traceback (most recent call last):
  File "sentiment-analysis/examples/hr/milvus.py", line 1, in <module>
    from pymilvus import MilvusClient, DataType
ModuleNotFoundError: No module named 'pymilvus'
```

### Expected Behavior

The document should have inslationa steps for pymilvus

### Steps To Reproduce

```markdown
Start milvus locally in a vnenv

 bash milvus_standalone_embed.sh start
Password:
Unable to find image 'milvusdb/milvus:v2.4.0-rc.1' locally
v2.4.0-rc.1: Pulling from milvusdb/milvus
f4bb4e8dca02: Pull complete 
19bbfe54d9b5: Pull complete 
aadc999ec938: Pull complete 
797eaaa02da3: Pull complete 
4f4fb700ef54: Pull complete 
0ca735a2405b: Pull complete 
Digest: sha256:a12662ae00f94274968eb1c4607fe2a2d2155b788297259098d585c2e800a862
Status: Downloaded newer image for milvusdb/milvus:v2.4.0-rc.1
Wait for Milvus Starting...
Start successfully.

```

Run the hello milvus code and it fails.
```
from pymilvus import MilvusClient, DataType

# 1. Set up a Milvus client
client = MilvusClient(
    uri="http://localhost:19530"
)```
```

### Milvus Log

```
/usr/local/bin/python3 sentiment-analysis/examples/hr/milvus.py
Traceback (most recent call last):
  File "sentiment-analysis/examples/hr/milvus.py", line 1, in <module>
    from pymilvus import MilvusClient, DataType
ModuleNotFoundError: No module named 'pymilvus'
```

**Comment by deepujain** [comment]
Pip installation of pymilvus shows success but code execution cannot find it

```
(haacklang2) sh-3.2$ pip install pymilvus
(haacklang2) sh-3.2$ pip install pymilvus
Requirement already satisfied: pymilvus in /Users/dejain/nvidia/envs/haacklang2/lib/python3.11/site-packages (2.4.0)
Requirement already satisfied: setuptools>=67 in /Users/dejain/nvidia/envs/haacklang2/lib/python3.11/site-packages (from pymilvus) (69.2.0)
Requirement already satisfied: grpcio<=1.60.0,>=1.49.1 in /Users/dejain/nvidia/envs/haacklang2/lib/python3.11/site-packages (from pymilvus) (1.60.0)
Requirement already satisfied: protobuf>=3.20.0 in /Users/dejain/nvidia/envs/haacklang2/lib/python3.11/site-packages (from pymilvus) (5.26.1)
Requirement already satisfied: environs<=9.5.0 in /Users/dejain/nvidia/envs/haacklang2/lib/python3.11/site-packages (from pymilvus) (9.5.0)
Requirement already satisfied: ujson>=2.0.0 in /Users/dejain/nvidia/envs/haacklang2/lib/python3.11/site-packages (from pymilvus) (5.9.0)
Requirement already satisfied: pandas>=1.2.4 in /Users/dejain/nvidia/envs/haacklang2/lib/python3.11/site-packages (from pymilvus) (2.2.2)
Requirement already satisfied: requests in /Users/dejain/nvidia/envs/haacklang2/lib/python3.11/site-packages (from pymilvus) (2.31.0)
Requirement already satisfied: minio>=7.0.0 in /Users/dejain/nvidia/envs/haacklang2/lib/python3.11/site-packages (from pymilvus) (7.2.5)
Requirement already satisfied: pyarrow>=12.0.0 in /Users/dejain/nvidia/envs/haacklang2/lib/python3.11/site-packages (from pymilvus) (15.0.2)
Requirement already satisfied: azure-storage-blob in /Users/dejain/nvidia/envs/haacklang2/lib/python3.11/site-packages (from pymilvus) (12.19.1)
Requirement already satisfied: scipy in /Users/dejain/nvidia/envs/haacklang2/lib/python3.11/site-packages (from pymilvus) (1.11.3)
Requirement already satisfied: marshmallow>=3.0.0 in /Users/dejain/nvidia/envs/haacklang2/lib/python3.11/site-packages (from environs<=9.5.0->pymilvus) (3.21.1)
Requirement already satisfied: python-dotenv in /Users/dejain/nvidia/envs/haacklang2/lib/python3.11/site-packages (from environs<=9.5.0->pymilvus) (1.0.0)
Requirement already satisfied: certifi in /Users/dejain/nvidia/envs/haacklang2/lib/python3.11/site-packages (from minio>=7.0.0->pymilvus) (2024.2.2)
Requirement already satisfied: urllib3 in /Users/dejain/nvidia/envs/haacklang2/lib/python3.11/site-packages (from minio>=7.0.0->pymilvus) (2.0.7)
Requirement already satisfied: argon2-cffi in /Users/dejain/nvidia/envs/haacklang2/lib/python3.11/site-packages (from minio>=7.0.0->pymilvus) (23.1.0)
Requirement already satisfied: pycryptodome in /Users/dejain/nvidia/envs/haacklang2/lib/python3.11/site-packages (from minio>=7.0.0->pymilvus) (3.20.0)
Requirement already satisfied: typing-extensions in /Users/dejain/nvidia/envs/haacklang2/lib/python3.11/site-packages (from minio>=7.0.0->pymilvus) (4.11.0)
Requirement already satisfied: numpy>=1.23.2 in /Users/dejain/nvidia/envs/haacklang2/lib/python3.11/site-packages (from pandas>=1.2.4->pymilvus) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/dejain/nvidia/envs/haacklang2/lib/python3.11/site-packages (from pandas>=1.2.4->pymilvus) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/dejain/nvidia/envs/haacklang2/lib/python3.11/site-packages (from pandas>=1.2.4->pymilvus) (2023.3)
Requirement already satisfied: tzdata>=2022.7 in /Users/dejain/nvidia/envs/haacklang2/lib/python3.11/site-packages (from pandas>=1.2.4->pymilvus) (2024.1)
Requirement already satisfied: azure-core<2.0.0,>=1.28.0 in /Users/dejain/nvidia/envs/haacklang2/lib/python3.11/site-packages (from azure-storage-blob->pymilvus) (1.30.1)
Requirement already satisfied: cryptography>=2.1.4 in /Users/dejain/nvidia/envs/haacklang2/lib/python3.11/site-packages (from azure-storage-blob->pymilvus) (42.0.5)
Requirement already satisfied: isodate>=0.6.1 in /Users/dejain/nvidia/envs/haacklang2/lib/python3.11/site-packages (from azure-storage-blob->pymilvus) (0.6.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/dejain/nvidia/envs/haacklang2/lib/python3.11/site-packages (from requests->pymilvus) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/dejain/nvidia/envs/haacklang2/lib/python3.11/site-packages (from requests->pymilvus) (3.6)
Requirement already satisfied: six>=1.11.0 in /Users/dejain/nvidia/envs/haacklang2/lib/python3.11/site-packages (from azure-core<2.0.0,>=1.28.0->azure-storage-blob->pymilvus) (1.16.0)
Requirement already satisfied: cffi>=1.12 in /Users/dejain/nvidia/envs/haacklang2/lib/python3.11/site-packages (from cryptography>=2.1.4->azure-storage-blob->pymilvus) (1.16.0)
Requirement already satisfied: packaging>=17.0 in /Users/dejain/nvidia/envs/haacklang2/lib/python3.11/site-packages (from marshmallow>=3.0.0->environs<=9.5.0->pymilvus) (23.2)
Requirement already satisfied: argon2-cffi-bindings in /Users/dejain/nvidia/envs/haacklang2/lib/python3.11/site-packages (from argon2-cffi->minio>=7.0.0->pymilvus) (21.2.0)
Requirement already satisfied: pycparser in /Users/dejain/nvidia/envs/haacklang2/lib/python3.11/site-packages (from cffi>=1.12->cryptography>=2.1.4->azure-storage-blob->pymilvus) (2.22)

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: pip install --upgrade pip

```
```
 pip list | grep pymilvus

pymilvus                      2.4.0

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: pip install --upgrade pip

```

**Comment by deepujain** [comment]
Fix:

```
pip install pymilvus
```
Install python 3.11.X version but not 3.10
```
python --version
Python 3.11.5
(haacklang2) sh-3.2$ 

```
(haacklang2) sh-3.2$python milvus.py 
(haacklang2) sh-3.2$

```

**Comment by yanliang567** [comment]
thanks for sharing the fix info. I'd close this issue for now.
