### ISSUE TITLE
[Bug]: many test cases failed with error `empty grpc client: find no available xxxcoord` after milvus recovered from etcd-follower pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#32190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4-20240411-5b45debb-amd64
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2024-04-11T22:43:18.614Z] [2024-04-11 22:43:08 - ERROR - pymilvus.decorators]: RPC error: [flush], <MilvusException: (code=65535, message=failed to call flush to data coordinator: stack trace: /go/src/github.com/milvus-io/milvus/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace

[2024-04-11T22:43:18.615Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:556 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call

[2024-04-11T22:43:18.615Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:570 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall

[2024-04-11T22:43:18.615Z] /go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:107 github.com/milvus-io/milvus/internal/distributed/datacoord/client.wrapGrpcCall[...]

[2024-04-11T22:43:18.615Z] /go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:147 github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).Flush

[2024-04-11T22:43:18.616Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task.go:1430 github.com/milvus-io/milvus/internal/proxy.(*flushTask).Execute

[2024-04-11T22:43:18.616Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:466 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask

[2024-04-11T22:43:18.616Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:509 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).controlLoop

[2024-04-11T22:43:18.616Z] /usr/local/go/src/runtime/asm_amd64.s:1598 runtime.goexit: empty grpc client: find no available datacoord, check datacoord state)>, <Time:{'RPC start': '2024-04-11 22:42:15.934049', 'RPC error': '2024-04-11 22:43:08.555966'}> (decorators.py:146)

[2024-04-11T22:43:18.616Z] [2024-04-11 22:43:08 - ERROR - ci_test]: Traceback (most recent call last):

[2024-04-11T22:43:18.616Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2024-04-11T22:43:18.616Z]     res = func(*args, **_kwargs)

[2024-04-11T22:43:18.616Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2024-04-11T22:43:18.616Z]     return func(*arg, **kwargs)

[2024-04-11T22:43:18.616Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 317, in flush

[2024-04-11T22:43:18.616Z]     conn.flush([self.name], timeout=timeout, **kwargs)

[2024-04-11T22:43:18.616Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 147, in handler

[2024-04-11T22:43:18.616Z]     raise e from e

[2024-04-11T22:43:18.616Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 143, in handler

[2024-04-11T22:43:18.616Z]     return func(*args, **kwargs)

[2024-04-11T22:43:18.616Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 182, in handler

[2024-04-11T22:43:18.616Z]     return func(self, *args, **kwargs)

[2024-04-11T22:43:18.616Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 122, in handler

[2024-04-11T22:43:18.616Z]     raise e from e

[2024-04-11T22:43:18.616Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 87, in handler

[2024-04-11T22:43:18.616Z]     return func(*args, **kwargs)

[2024-04-11T22:43:18.616Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 1397, in flush

[2024-04-11T22:43:18.616Z]     check_status(response.status)

[2024-04-11T22:43:18.616Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/utils.py", line 60, in check_status

[2024-04-11T22:43:18.616Z]     raise MilvusException(status.code, status.reason, status.error_code)

[2024-04-11T22:43:18.616Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=failed to call flush to data coordinator: stack trace: /go/src/github.com/milvus-io/milvus/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace

[2024-04-11T22:43:18.616Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:556 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call

[2024-04-11T22:43:18.616Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:570 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall

[2024-04-11T22:43:18.616Z] /go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:107 github.com/milvus-io/milvus/internal/distributed/datacoord/client.wrapGrpcCall[...]

[2024-04-11T22:43:18.616Z] /go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:147 github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).Flush

[2024-04-11T22:43:18.616Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task.go:1430 github.com/milvus-io/milvus/internal/proxy.(*flushTask).Execute

[2024-04-11T22:43:18.616Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:466 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask

[2024-04-11T22:43:18.616Z] /go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:509 github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).controlLoop

[2024-04-11T22:43:18.616Z] /usr/local/go/src/runtime/asm_amd64.s:1598 runtime.goexit: empty grpc client: find no available datacoord, check datacoord state)>

[2024-04-11T22:43:18.616Z]  (api_request.py:45)

[2024-04-11T22:43:18.616Z] [2024-04-11 22:43:08 - ERROR - ci_test]: (api_response) : <MilvusException: (code=65535, message=failed to call flush to data coordinator: stack trace: /go/src/github.com/milvus-io/milvus/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace

[2024-04-11T22:43:18.616Z] /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:556 github.com/milvu...... (api_request.py:46)
```

```

[2024-04-11T22:41:26.885Z] [2024-04-11 22:41:23 - ERROR - pymilvus.decorators]: RPC error: [create_collection], <MilvusException: (code=65535, message=empty grpc client: find no available datacoord, check datacoord state)>, <Time:{'RPC start': '2024-04-11 22:40:30.462252', 'RPC error': '2024-04-11 22:41:23.096821'}> (decorators.py:146)

[2024-04-11T22:41:26.885Z] [2024-04-11 22:41:23 - ERROR - ci_test]: Traceback (most recent call last):

[2024-04-11T22:41:26.885Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2024-04-11T22:41:26.885Z]     res = func(*args, **_kwargs)

[2024-04-11T22:41:26.885Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2024-04-11T22:41:26.885Z]     return func(*arg, **kwargs)

[2024-04-11T22:41:26.885Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 149, in __init__

[2024-04-11T22:41:26.885Z]     conn.create_collection(self._name, schema, **kwargs)

[2024-04-11T22:41:26.885Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 147, in handler

[2024-04-11T22:41:26.885Z]     raise e from e

[2024-04-11T22:41:26.885Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 143, in handler

[2024-04-11T22:41:26.885Z]     return func(*args, **kwargs)

[2024-04-11T22:41:26.885Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 182, in handler

[2024-04-11T22:41:26.885Z]     return func(self, *args, **kwargs)

[2024-04-11T22:41:26.885Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 122, in handler

[2024-04-11T22:41:26.885Z]     raise e from e

[2024-04-11T22:41:26.885Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 87, in handler

[2024-04-11T22:41:26.885Z]     return func(*args, **kwargs)

[2024-04-11T22:41:26.885Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 304, in create_collection

[2024-04-11T22:41:26.885Z]     check_status(status)

[2024-04-11T22:41:26.885Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/utils.py", line 60, in check_status

[2024-04-11T22:41:26.885Z]     raise MilvusException(status.code, status.reason, status.error_code)

[2024-04-11T22:41:26.885Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=empty grpc client: find no available datacoord, check datacoord state)>

[2024-04-11T22:41:26.885Z]  (api_request.py:45)

[2024-04-11T22:41:26.885Z] [2024-04-11 22:41:23 - ERROR - ci_test]: (api_response) : <MilvusException: (code=65535, message=empty grpc client: find no available datacoord, check datacoord state)> (api_request.py:46)
```

### Milvus Log

failed job:https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-for-release-cron/detail/chaos-test-for-release-cron/11893/pipeline
log:
[artifacts-etcd-followers-pod-kill-11893-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/14953324/artifacts-etcd-followers-pod-kill-11893-server-logs.tar.gz)

cluster: 4am
namespace: chaos-testing
pod info
```
[2024-04-11T22:40:21.973Z] + kubectl get pods -o wide

[2024-04-11T22:40:21.975Z] + grep etcd-followers-pod-kill-11893

[2024-04-11T22:40:22.535Z] etcd-followers-pod-kill-11893-0                                   1/1     Running            0                34m     10.104.32.127   4am-node39   <none>           <none>

[2024-04-11T22:40:22.535Z] etcd-followers-pod-kill-11893-1                                   1/1     Running            0                18m     10.104.31.54    4am-node34   <none>           <none>

[2024-04-11T22:40:22.535Z] etcd-followers-pod-kill-11893-2                                   1/1     Running            0                34m     10.104.29.142   4am-node35   <none>           <none>

[2024-04-11T22:40:22.535Z] etcd-followers-pod-kill-11893-milvus-datacoord-6d85476958-kjnml   1/1     Running            0                34m     10.104.4.65     4am-node11   <none>           <none>

[2024-04-11T22:40:22.535Z] etcd-followers-pod-kill-11893-milvus-datanode-57ccc78cb5-62jfz    1/1     Running            0                34m     10.104.4.61     4am-node11   <none>           <none>

[2024-04-11T22:40:22.535Z] etcd-followers-pod-kill-11893-milvus-datanode-57ccc78cb5-7rbhg    1/1     Running            0                34m     10.104.13.49    4am-node16   <none>           <none>

[2024-04-11T22:40:22.535Z] etcd-followers-pod-kill-11893-milvus-indexcoord-6689f9cbc9xdjgm   1/1     Running            0                34m     10.104.13.37    4am-node16   <none>           <none>

[2024-04-11T22:40:22.535Z] etcd-followers-pod-kill-11893-milvus-indexnode-864d659bcb-czkww   1/1     Running            0                34m     10.104.13.53    4am-node16   <none>           <none>

[2024-04-11T22:40:22.535Z] etcd-followers-pod-kill-11893-milvus-indexnode-864d659bcb-lsz96   1/1     Running            0                7m43s   10.104.19.165   4am-node28   <none>           <none>

[2024-04-11T22:40:22.535Z] etcd-followers-pod-kill-11893-milvus-indexnode-864d659bcb-vqhfd   1/1     Running            0                34m     10.104.4.62     4am-node11   <none>           <none>

[2024-04-11T22:40:22.535Z] etcd-followers-pod-kill-11893-milvus-proxy-5949d4cd67-6g4lf       1/1     Running            0                34m     10.104.13.44    4am-node16   <none>           <none>

[2024-04-11T22:40:22.535Z] etcd-followers-pod-kill-11893-milvus-querycoord-6cbfdc649692jj2   1/1     Running            0                34m     10.104.4.64     4am-node11   <none>           <none>

[2024-04-11T22:40:22.535Z] etcd-followers-pod-kill-11893-milvus-querynode-79d6cb669b-299k4   1/1     Running            0                7m42s   10.104.27.221   4am-node31   <none>           <none>

[2024-04-11T22:40:22.535Z] etcd-followers-pod-kill-11893-milvus-querynode-79d6cb669b-klhhs   1/1     Running            0                34m     10.104.4.60     4am-node11   <none>           <none>

[2024-04-11T22:40:22.535Z] etcd-followers-pod-kill-11893-milvus-querynode-79d6cb669b-pw4fl   1/1     Running            0                34m     10.104.13.48    4am-node16   <none>           <none>

[2024-04-11T22:40:22.535Z] etcd-followers-pod-kill-11893-milvus-rootcoord-576877cdf4-l9wp6   1/1     Running            0                34m     10.104.13.42    4am-node16   <none>           <none>

[2024-04-11T22:40:22.535Z] etcd-followers-pod-kill-11893-minio-0                             1/1     Running            0                34m     10.104.32.125   4am-node39   <none>           <none>

[2024-04-11T22:40:22.535Z] etcd-followers-pod-kill-11893-minio-1                             1/1     Running            0                34m     10.104.31.17    4am-node34   <none>           <none>

[2024-04-11T22:40:22.536Z] etcd-followers-pod-kill-11893-minio-2                             1/1     Running            0                34m     10.104.29.139   4am-node35   <none>           <none>

[2024-04-11T22:40:22.536Z] etcd-followers-pod-kill-11893-minio-3                             1/1     Running            0                34m     10.104.33.62    4am-node36   <none>           <none>

[2024-04-11T22:40:22.536Z] etcd-followers-pod-kill-11893-pulsar-bookie-0                     1/1     Running            0                34m     10.104.32.133   4am-node39   <none>           <none>

[2024-04-11T22:40:22.536Z] etcd-followers-pod-kill-11893-pulsar-bookie-1                     1/1     Running            0                34m     10.104.31.28    4am-node34   <none>           <none>

[2024-04-11T22:40:22.536Z] etcd-followers-pod-kill-11893-pulsar-bookie-init-hvnj8            0/1     Completed          0                34m     10.104.4.63     4am-node11   <none>           <none>

[2024-04-11T22:40:22.536Z] etcd-followers-pod-kill-11893-pulsar-broker-0                     1/1     Running            0                34m     10.104.13.51    4am-node16   <none>           <none>

[2024-04-11T22:40:22.536Z] etcd-followers-pod-kill-11893-pulsar-proxy-0                      1/1     Running            0                34m     10.104.13.50    4am-node16   <none>           <none>

[2024-04-11T22:40:22.536Z] etcd-followers-pod-kill-11893-pulsar-pulsar-init-hck8q            0/1     Completed          0                34m     10.104.4.66     4am-node11   <none>           <none>

[2024-04-11T22:40:22.536Z] etcd-followers-pod-kill-11893-pulsar-recovery-0                   1/1     Running            0                34m     10.104.13.52    4am-node16   <none>           <none>

[2024-04-11T22:40:22.536Z] etcd-followers-pod-kill-11893-pulsar-zookeeper-0                  1/1     Running            0                34m     10.104.32.129   4am-node39   <none>           <none>
```

### Anything else?

![image](https://github.com/milvus-io/milvus/assets/12268675/0a2baccd-aa93-4231-8938-28c312e8e90c)

I did not perform pod termination on indexnode and querynode, yet two pods were terminated and then re-initialized.

**Comment by zhuwenxing** [comment]
may related to https://github.com/milvus-io/milvus/pull/32069
/assign @congqixia 
PTAL

**Comment by zhuwenxing** [comment]
there may be some test env issues
![image](https://github.com/milvus-io/milvus/assets/12268675/aa444dc7-4ff2-4df8-bb1c-1a52447065d4)

many pods were in terminating status

**Comment by zhuwenxing** [comment]
after rerun, there are no issues. so this should be related to the environmental problems
