### ISSUE TITLE
[Bug]: Data write to collection via Milvus Spark Connector fails with error 'Fail to list databases'

### ISSUE THREAD

**Issue by dgoldenberg-ias** [milvus-io/milvus#32387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.4.0-rc.1
- Deployment mode(standalone or cluster): Standalone
- MQ type(rocksmq, pulsar or kafka): Pulsar (?)
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.4.0
- OS(Ubuntu or CentOS): < will find out >
- CPU/Memory: < will find out >
- GPU: < will find out >
- Others: N / A
```

### Current Behavior

When I attempt to write vector data into a pre-created milvus collection, I get the error `java.lang.Exception: Fail to list databases: R{exception=StatusRuntimeException: INTERNAL: http2 exception, status=-3, data=null}`.

### Expected Behavior

The expected behavior is that data would successfully get written into the specified collection with no errors.

### Steps To Reproduce

```markdown
Code:

from datetime import datetime
from pyspark.sql import SparkSession


from pymilvus import (
   FieldSchema,
   CollectionSchema,
   DataType,
   Collection,
   MilvusClient
)
from pymilvus.milvus_client import IndexParams


columns = ["doc_id", "vector"]
data = [
   (1, [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0]),
   (2, [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0]),
   (3, [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0]),
   (4, [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0])
]


TEST_ID = datetime.today().strftime("%Y%m%d%H%M%S")
COLLECTION_NAME = f"milvus_spark_test_{TEST_ID}"
NUM_DIMENSIONS = 8


CLUSTER_ENDPOINT = "https://milvus-standalone.alpha.k8s.dev.303net.net:50051"
client = MilvusClient(uri=CLUSTER_ENDPOINT)


field1 = FieldSchema(
   name="doc_id", dtype=DataType.VARCHAR, max_length=32, description="The ID field, prim key",
   is_primary=True, auto_id=False)
field2 = FieldSchema(
   name="vector", dtype=DataType.FLOAT_VECTOR, description="The vector field", dim=NUM_DIMENSIONS,
   is_primary=False)
schema = CollectionSchema(fields=[field1, field2], description="Collection for testing")


index_params = IndexParams()
metric_type = "L2"
index_type = "HNSW"
index_name = f"{COLLECTION_NAME}_idx"
params = {"M": 4, "efConstruction": 200}
index_params.add_index(field_name="vector", metric_type=metric_type, index_type=index_type, index_name=index_name, params=params)


client.create_collection(
   collection_name=COLLECTION_NAME,
   dimension=8,
   primary_field_name="doc_id",
   id_type="string",
   vector_field_name="vector",
   metric_type=metric_type,
   auto_id=False,
   timeout=None,
   schema=schema,
   index_params=index_params
)


spark = SparkSession.builder.appName("Milvus-Spark-Connector-Demo").getOrCreate()
sample_df = spark.sparkContext.parallelize(data).toDF(columns)


(
   sample_df.write
       .mode("append")
       .option("milvus.host", "milvus-standalone.alpha.k8s.dev.303net.net")
       .option("milvus.port", "50051")
       .option("milvus.collection.name", COLLECTION_NAME)
       .option("milvus.collection.vectorField", "vector")
       .option("milvus.collection.vectorDim", str(NUM_DIMENSIONS))
       .option("milvus.collection.primaryKeyField", "doc_id")
       .format("milvus")
       .save()
)
client.close()
```

Exception stack trace:
```
java.lang.Exception: Fail to list databases: R{exception=StatusRuntimeException: INTERNAL: http2 exception, status=-3, data=null}

---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
File <command-3658777111610979>, line 69
     56 spark = SparkSession.builder.appName("Milvus-Spark-Connector-Demo").getOrCreate()
     57 sample_df = spark.sparkContext.parallelize(data).toDF(columns)
     59 (
     60     sample_df.write
     61         .mode("append")
     62         .option("milvus.host", "milvus-standalone.alpha.k8s.dev.303net.net")
     63         .option("milvus.port", "50051")
     64         .option("milvus.collection.name", COLLECTION_NAME)
     65         .option("milvus.collection.vectorField", "vector")
     66         .option("milvus.collection.vectorDim", str(NUM_DIMENSIONS))
     67         .option("milvus.collection.primaryKeyField", "doc_id")
     68         .format("milvus")
---> 69         .save()
     70 )
     72 df = spark.read.format("milvus") \
     73     .option("milvus.host", "milvus-standalone.alpha.k8s.dev.303net.net") \
     74     .option("milvus.port", "50051") \
   (...)
     79     .load() \
     80     .select("doc_id", "vector")
     82 df.show(n=20, truncate=False)

File /databricks/spark/python/pyspark/instrumentation_utils.py:48, in _wrap_function.<locals>.wrapper(*args, **kwargs)
     46 start = time.perf_counter()
     47 try:
---> 48     res = func(*args, **kwargs)
     49     logger.log_success(
     50         module_name, class_name, function_name, time.perf_counter() - start, signature
     51     )
     52     return res

File /databricks/spark/python/pyspark/sql/readwriter.py:1461, in DataFrameWriter.save(self, path, format, mode, partitionBy, **options)
   1459     self.format(format)
   1460 if path is None:
-> 1461     self._jwrite.save()
   1462 else:
   1463     self._jwrite.save(path)

File /databricks/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py:1355, in JavaMember.__call__(self, *args)
   1349 command = proto.CALL_COMMAND_NAME +\
   1350     self.command_header +\
   1351     args_command +\
   1352     proto.END_COMMAND_PART
   1354 answer = self.gateway_client.send_command(command)
-> 1355 return_value = get_return_value(
   1356    answer, self.gateway_client, self.target_id, self.name)
   1358 for temp_arg in temp_args:
   1359     if hasattr(temp_arg, "_detach"):

File /databricks/spark/python/pyspark/errors/exceptions/captured.py:188, in capture_sql_exception.<locals>.deco(*a, **kw)
    186 def deco(*a: Any, **kw: Any) -> Any:
    187     try:
--> 188         return f(*a, **kw)
    189     except Py4JJavaError as e:
    190         converted = convert_exception(e.java_exception)

File /databricks/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py:326, in get_return_value(answer, gateway_client, target_id, name)
    324 value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325 if answer[1] == REFERENCE_TYPE:
--> 326     raise Py4JJavaError(
    327         "An error occurred while calling {0}{1}{2}.\n".
    328         format(target_id, ".", name), value)
    329 else:
    330     raise Py4JError(
    331         "An error occurred while calling {0}{1}{2}. Trace:\n{3}\n".
    332         format(target_id, ".", name, value))

Py4JJavaError: An error occurred while calling o625.save.
: java.lang.Exception: Fail to list databases: R{exception=StatusRuntimeException: INTERNAL: http2 exception, status=-3, data=null}
	at zilliztech.spark.milvus.Milvus.getTable(Milvus.scala:29)
	at org.apache.spark.sql.DataFrameWriter.getTable$1(DataFrameWriter.scala:308)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:326)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:258)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:397)
	at py4j.Gateway.invoke(Gateway.java:306)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:199)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:119)
	at java.lang.Thread.run(Thread.java:750)

```
```


### Milvus Log

_No response_

### Anything else?

Might this be an HTTP vs. HTTPS error?

**Comment by yanliang567** [comment]
I believe this is a dup to #32388 for a milvus connection failure. I'd close this one and lets track the issue in that one
