### ISSUE TITLE
[Bug]: [standalone][LRU] Milvus standalone goroutine leak when enable lru cache

### ISSUE THREAD

**Issue by chyezh** [milvus-io/milvus#32435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: lru-dev
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):   pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Goroutine leaks
<img width="556" alt="image" src="https://github.com/milvus-io/milvus/assets/20332315/d4d54ab9-8aaa-4000-abbc-a5e7e0ca616f">

### Expected Behavior

No goroutine leak

**Comment by chyezh** [comment]
Dead lock when enable lru cache.
RWMutex of segmentManager is recursive rlock when enable lru cahe.

```
goroutine 794746 [sync.RWMutex.RLock, 1026 minutes]:
sync.runtime_SemacquireRWMutexR(0x2?, 0x10?, 0x59ce2e0?)
        /usr/local/go/src/runtime/sema.go:82 +0x26
sync.(*RWMutex).RLock(...)
        /usr/local/go/src/sync/rwmutex.go:71
[github.com/milvus-io/milvus/internal/querynodev2/segments.(*segmentManager).GetWithType](http://github.com/milvus-io/milvus/internal/querynodev2/segments.(*segmentManager).GetWithType)(0xc0005b2db0?, 0xc00d900880?, 0x0?)
        /go/src/[github.com/milvus-io/milvus/internal/querynodev2/segments/manager.go:383](http://github.com/milvus-io/milvus/internal/querynodev2/segments/manager.go:383) +0x5d
[github.com/milvus-io/milvus/internal/querynodev2/segments.(*segmentLoader).waitSegmentLoadDone](http://github.com/milvus-io/milvus/internal/querynodev2/segments.(*segmentLoader).waitSegmentLoadDone)(0xc0005feb00, {0x59c6e88, 0xc0001ba000}, 0x7868ea0?, {0xc00335b468?, 0x1, 0x1}
, 0xc0061d1fb0?)
        /go/src/[github.com/milvus-io/milvus/internal/querynodev2/segments/segment_loader.go:842](http://github.com/milvus-io/milvus/internal/querynodev2/segments/segment_loader.go:842) +0x302
[github.com/milvus-io/milvus/internal/querynodev2/segments.(*segmentLoader).LoadIndex](http://github.com/milvus-io/milvus/internal/querynodev2/segments.(*segmentLoader).LoadIndex)(0xc0005feb00, {0x59c6e88, 0xc0001ba000}, 0xc007868ea0, 0xc00b239d40, 0x3?)
        /go/src/[github.com/milvus-io/milvus/internal/querynodev2/segments/segment_loader.go:1618](http://github.com/milvus-io/milvus/internal/querynodev2/segments/segment_loader.go:1618) +0xcd0
[github.com/milvus-io/milvus/internal/querynodev2/segments.NewManager.func4(0x63bafd320289fae)](http://github.com/milvus-io/milvus/internal/querynodev2/segments.NewManager.func4(0x63bafd320289fae))
        /go/src/[github.com/milvus-io/milvus/internal/querynodev2/segments/manager.go:228](http://github.com/milvus-io/milvus/internal/querynodev2/segments/manager.go:228) +0x165
[github.com/milvus-io/milvus/pkg/util/cache](http://github.com/milvus-io/milvus/pkg/util/cache).(*lruCache[...]).peekAndPin(0x5a4a4e0, 0x1c71946)
        /go/src/[github.com/milvus-io/milvus/pkg/util/cache/cache.go:368](http://github.com/milvus-io/milvus/pkg/util/cache/cache.go:368) +0x144
[github.com/milvus-io/milvus/pkg/util/cache](http://github.com/milvus-io/milvus/pkg/util/cache).(*lruCache[...]).getAndPin(0x5a4a4e0, 0x63bafd320289fae)
        /go/src/[github.com/milvus-io/milvus/pkg/util/cache/cache.go:391](http://github.com/milvus-io/milvus/pkg/util/cache/cache.go:391) +0x78
[github.com/milvus-io/milvus/pkg/util/cache](http://github.com/milvus-io/milvus/pkg/util/cache).(*lruCache[...]).DoWait(0x5a4a4e0, 0x63bafd320289fae, 0x66c16bf41c3, 0xc00b7d5810?)
        /go/src/[github.com/milvus-io/milvus/pkg/util/cache/cache.go:296](http://github.com/milvus-io/milvus/pkg/util/cache/cache.go:296) +0xc6
[github.com/milvus-io/milvus/internal/querynodev2/segments.searchSegmentsStreamly.func2](http://github.com/milvus-io/milvus/internal/querynodev2/segments.searchSegmentsStreamly.func2)({0x5a3ae40, 0xc007868ea0}, 0x1)
        /go/src/[github.com/milvus-io/milvus/internal/querynodev2/segments/search.go:190](http://github.com/milvus-io/milvus/internal/querynodev2/segments/search.go:190) +0x417
created by [github.com/milvus-io/milvus/internal/querynodev2/segments.searchSegmentsStreamly](http://github.com/milvus-io/milvus/internal/querynodev2/segments.searchSegmentsStreamly)
        /go/src/[github.com/milvus-io/milvus/internal/querynodev2/segments/search.go:174](http://github.com/milvus-io/milvus/internal/querynodev2/segments/search.go:174) +0x234

```
