### ISSUE TITLE
[Bug]: search failed with error `failed to search: node offline[node=21]: channel not available[channel=by-dev-rootcoord-dml_2_449246555772891180v1]` after milvus recover from datanode pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#32492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4-20240418-238f9a4a-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):kafka    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```

[2024-04-21T23:26:51.492Z] <name>: UpsertChecker__T80kNexE

[2024-04-21T23:26:51.492Z] <description>: 

[2024-04-21T23:26:51.492Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT......  (api_request.py:37)

[2024-04-21T23:26:51.492Z] [2024-04-21 23:23:44 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-04-21T23:26:51.492Z] [2024-04-21 23:23:45 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-04-21T23:26:51.492Z] [2024-04-21 23:23:45 - DEBUG - ci_test]: (api_request)  : [Collection.compact] args: [180], kwargs: {} (api_request.py:62)

[2024-04-21T23:26:51.492Z] [2024-04-21 23:23:45 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-04-21T23:26:51.492Z] [2024-04-21 23:24:51 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-04-21T23:26:51.492Z] [2024-04-21 23:24:51 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-04-21T23:26:51.492Z] [2024-04-21 23:24:51 - INFO - ci_test]: assert create collection: 0.01916027069091797, init_entities: 60000 (test_all_collections_after_chaos.py:49)

[2024-04-21T23:26:51.492Z] [2024-04-21 23:24:54 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [[[-3000, -2999, -2998, -2997, -2996, -2995, -2994, -2993, -2992, -2991, -2990, -2989, -2988, -2987, -2986, -2985, -2984, -2983, -2982, -2981, -2980, -2979, -2978, -2977, -2976, -2975, -2974, -2973, -2972, -2971, -2970, -2969, -2968, -2967, -2966, -2965, -2964, -2963, -2962, -2961, -2960, -2959, -29......, kwargs: {'timeout': 180} (api_request.py:62)

[2024-04-21T23:26:51.493Z] [2024-04-21 23:24:54 - DEBUG - ci_test]: (api_response) : (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 449247155186040833, success count: 2000, err count: 0)  (api_request.py:37)

[2024-04-21T23:26:51.493Z] [2024-04-21 23:24:54 - INFO - ci_test]: assert insert: 1.6006882190704346 (test_all_collections_after_chaos.py:57)

[2024-04-21T23:26:51.493Z] [2024-04-21 23:24:54 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-04-21T23:26:51.493Z] [2024-04-21 23:24:57 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-04-21T23:26:51.493Z] [2024-04-21 23:24:57 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-04-21T23:26:51.493Z] [2024-04-21 23:24:57 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-04-21T23:26:51.493Z] [2024-04-21 23:25:33 - INFO - ci_test]: assert flush: 2.583571434020996, entities: 62000 (test_all_collections_after_chaos.py:67)

[2024-04-21T23:26:51.493Z] [2024-04-21 23:25:33 - INFO - ci_test]: index info: [{'collection': 'UpsertChecker__T80kNexE', 'field': 'int64', 'index_name': 'int64', 'index_param': {'index_type': 'INVERTED'}}, {'collection': 'UpsertChecker__T80kNexE', 'field': 'float', 'index_name': 'float', 'index_param': {'index_type': 'INVERTED'}}, {'collection': 'UpsertChecker__T80kNexE', 'field': 'varchar', 'index_name': 'varchar', 'index_param': {'index_type': 'INVERTED'}}, {'collection': 'UpsertChecker__T80kNexE', 'field': 'float_vector', 'index_name': 'float_vector', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}, {'collection': 'UpsertChecker__T80kNexE', 'field': 'image_emb', 'index_name': 'image_emb', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}, {'collection': 'UpsertChecker__T80kNexE', 'field': 'text_emb', 'index_name': 'text_emb', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}, {'collection': 'UpsertChecker__T80kNexE', 'field': 'voice_emb', 'index_name': 'voice_emb', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}] (test_all_collections_after_chaos.py:71)

[2024-04-21T23:26:51.493Z] [2024-04-21 23:25:33 - INFO - ci_test]: index info: [{'collection': 'UpsertChecker__T80kNexE', 'field': 'text_emb', 'index_name': 'text_emb', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}, {'collection': 'UpsertChecker__T80kNexE', 'field': 'voice_emb', 'index_name': 'voice_emb', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}, {'collection': 'UpsertChecker__T80kNexE', 'field': 'int64', 'index_name': 'int64', 'index_param': {'index_type': 'INVERTED'}}, {'collection': 'UpsertChecker__T80kNexE', 'field': 'float', 'index_name': 'float', 'index_param': {'index_type': 'INVERTED'}}, {'collection': 'UpsertChecker__T80kNexE', 'field': 'varchar', 'index_name': 'varchar', 'index_param': {'index_type': 'INVERTED'}}, {'collection': 'UpsertChecker__T80kNexE', 'field': 'float_vector', 'index_name': 'float_vector', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}, {'collection': 'UpsertChecker__T80kNexE', 'field': 'image_emb', 'index_name': 'image_emb', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}] (test_all_collections_after_chaos.py:86)

[2024-04-21T23:26:51.493Z] [2024-04-21 23:25:33 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 180], kwargs: {} (api_request.py:62)

[2024-04-21T23:26:51.493Z] [2024-04-21 23:25:33 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-04-21T23:26:51.493Z] [2024-04-21 23:25:33 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.0738166041080281, 0.07413720410951401, 0.14494293832322094, 0.11400530240619897, 0.01931037551221909, 0.07119848587506732, 0.07639657760649597, 0.0049205675161853625, 0.03372389118640681, 0.06339479724009546, 0.12828549003853554, 0.12806457898107645, 0.013248534134082519, 0.03050809106276891, 0......, kwargs: {} (api_request.py:62)

[2024-04-21T23:26:51.493Z] [2024-04-21 23:25:33 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=503, message=failed to search: node offline[node=21]: channel not available[channel=by-dev-rootcoord-dml_2_449246555772891180v1])>, <Time:{'RPC start': '2024-04-21 23:25:33.125761', 'RPC error': '2024-04-21 23:25:33.133690'}> (decorators.py:146)

[2024-04-21T23:26:51.493Z] [2024-04-21 23:25:33 - ERROR - ci_test]: Traceback (most recent call last):

[2024-04-21T23:26:51.493Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2024-04-21T23:26:51.493Z]     res = func(*args, **_kwargs)

[2024-04-21T23:26:51.493Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2024-04-21T23:26:51.493Z]     return func(*arg, **kwargs)

[2024-04-21T23:26:51.493Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 799, in search

[2024-04-21T23:26:51.493Z]     resp = conn.search(

[2024-04-21T23:26:51.493Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 147, in handler

[2024-04-21T23:26:51.493Z]     raise e from e

[2024-04-21T23:26:51.493Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 143, in handler

[2024-04-21T23:26:51.493Z]     return func(*args, **kwargs)

[2024-04-21T23:26:51.493Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 182, in handler

[2024-04-21T23:26:51.493Z]     return func(self, *args, **kwargs)

[2024-04-21T23:26:51.493Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 122, in handler

[2024-04-21T23:26:51.493Z]     raise e from e

[2024-04-21T23:26:51.493Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 87, in handler

[2024-04-21T23:26:51.493Z]     return func(*args, **kwargs)

[2024-04-21T23:26:51.493Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 797, in search

[2024-04-21T23:26:51.493Z]     return self._execute_search(request, timeout, round_decimal=round_decimal, **kwargs)

[2024-04-21T23:26:51.493Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 738, in _execute_search

[2024-04-21T23:26:51.493Z]     raise e from e

[2024-04-21T23:26:51.493Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 731, in _execute_search

[2024-04-21T23:26:51.493Z]     check_status(response.status)

[2024-04-21T23:26:51.493Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/utils.py", line 62, in check_status

[2024-04-21T23:26:51.493Z]     raise MilvusException(status.code, status.reason, status.error_code)

[2024-04-21T23:26:51.493Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=503, message=failed to search: node offline[node=21]: channel not available[channel=by-dev-rootcoord-dml_2_449246555772891180v1])>
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-for-release-cron/detail/chaos-test-kafka-for-release-cron/12639/pipeline
log:
[artifacts-datanode-pod-kill-12639-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/15057223/artifacts-datanode-pod-kill-12639-server-logs.tar.gz)

cluster: 4am
namespace: chaos-testing
pod info
```
 + grep datanode-pod-kill-12639
 datanode-pod-kill-12639-etcd-0                                    1/1     Running       0               41m     10.104.29.166   4am-node35   <none>           <none>
 datanode-pod-kill-12639-etcd-1                                    1/1     Running       0               41m     10.104.28.198   4am-node33   <none>           <none>
 datanode-pod-kill-12639-etcd-2                                    1/1     Running       0               41m     10.104.31.187   4am-node34   <none>           <none>
 datanode-pod-kill-12639-kafka-0                                   2/2     Running       2 (40m ago)     41m     10.104.31.177   4am-node34   <none>           <none>
 datanode-pod-kill-12639-kafka-1                                   2/2     Running       2 (40m ago)     41m     10.104.28.195   4am-node33   <none>           <none>
 datanode-pod-kill-12639-kafka-2                                   2/2     Running       2 (40m ago)     41m     10.104.27.166   4am-node31   <none>           <none>
 datanode-pod-kill-12639-kafka-exporter-64585cdb86-l6gqj           1/1     Running       3 (41m ago)     41m     10.104.6.133    4am-node13   <none>           <none>
 datanode-pod-kill-12639-milvus-datacoord-6fbcfdc44d-nl2vq         1/1     Running       0               41m     10.104.14.217   4am-node18   <none>           <none>
 datanode-pod-kill-12639-milvus-datanode-64db7d77cc-7f4xl          1/1     Running       0               16m     10.104.30.64    4am-node38   <none>           <none>
 datanode-pod-kill-12639-milvus-datanode-64db7d77cc-nc4t4          1/1     Running       0               16m     10.104.34.193   4am-node37   <none>           <none>
 datanode-pod-kill-12639-milvus-indexcoord-66977d7bb7-z4hd9        1/1     Running       0               41m     10.104.28.185   4am-node33   <none>           <none>
 datanode-pod-kill-12639-milvus-indexnode-5b9bfff9c4-g592g         1/1     Running       2 (7m27s ago)   41m     10.104.28.188   4am-node33   <none>           <none>
 datanode-pod-kill-12639-milvus-indexnode-5b9bfff9c4-jjqqb         1/1     Running       0               41m     10.104.32.45    4am-node39   <none>           <none>
 datanode-pod-kill-12639-milvus-indexnode-5b9bfff9c4-rhw9v         1/1     Running       0               41m     10.104.17.177   4am-node23   <none>           <none>
 datanode-pod-kill-12639-milvus-proxy-657ff8664f-8k45n             1/1     Running       0               41m     10.104.6.135    4am-node13   <none>           <none>
 datanode-pod-kill-12639-milvus-querycoord-6d48cddccb-c4wvq        1/1     Running       0               41m     10.104.6.134    4am-node13   <none>           <none>
 datanode-pod-kill-12639-milvus-querynode-9f96fd6bb-2pnq2          1/1     Running       1 (12m ago)     41m     10.104.28.186   4am-node33   <none>           <none>
 datanode-pod-kill-12639-milvus-querynode-9f96fd6bb-6mslv          1/1     Running       0               41m     10.104.6.131    4am-node13   <none>           <none>
 datanode-pod-kill-12639-milvus-querynode-9f96fd6bb-mw2wz          1/1     Running       0               41m     10.104.29.163   4am-node35   <none>           <none>
 datanode-pod-kill-12639-milvus-rootcoord-776859c644-nqq48         1/1     Running       0               41m     10.104.28.187   4am-node33   <none>           <none>
 datanode-pod-kill-12639-minio-0                                   1/1     Running       0               41m     10.104.29.167   4am-node35   <none>           <none>
 datanode-pod-kill-12639-minio-1                                   1/1     Running       0               41m     10.104.31.180   4am-node34   <none>           <none>
 datanode-pod-kill-12639-minio-2                                   1/1     Running       0               41m     10.104.34.169   4am-node37   <none>           <none>
 datanode-pod-kill-12639-minio-3                                   1/1     Running       1 (7m27s ago)   41m     10.104.28.203   4am-node33   <none>           <none>
 datanode-pod-kill-12639-zookeeper-0                               1/1     Running       0               41m     10.104.31.178   4am-node34   <none>           <none>
 datanode-pod-kill-12639-zookeeper-1                               1/1     Running       0               41m     10.104.28.199   4am-node33   <none>           <none>
 datanode-pod-kill-12639-zookeeper-2                               1/1     Running       0               41m     10.104.26.163   4am-node32   <none>           <none>
```

### Anything else?

![image](https://github.com/milvus-io/milvus/assets/12268675/3318b59e-afc7-471f-8ee5-bc7730b898aa)

The "indexnode" and "querynode" restarted after the "datanode" pod was killed

**Comment by zhuwenxing** [comment]
not reproduced recently

**Comment by pycui** [comment]
I'm seeing this again with v2.4.10. Any tips for recovering from this?

**Comment by xiaofan-luan** [comment]
@pycui could you upload your log for further investigation?

we don't know what happens until we get a solid logs
