### ISSUE TITLE
[Bug]: insert failed with error `grpc_message:"Deadline Exceeded"` after milvus recovered from minio pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#32521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20240422-ad5a49e6-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2024-04-22T20:32:02.549Z] [2024-04-22 20:04:56 - DEBUG - ci_test]: (api_response) : <Collection>:

[2024-04-22T20:32:02.549Z] -------------

[2024-04-22T20:32:02.549Z] <name>: DeleteChecker__XnOF9Fgo

[2024-04-22T20:32:02.549Z] <description>: 

[2024-04-22T20:32:02.549Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT......  (api_request.py:37)

[2024-04-22T20:32:02.549Z] [2024-04-22 20:04:56 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-04-22T20:32:02.549Z] [2024-04-22 20:05:27 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-04-22T20:32:02.549Z] [2024-04-22 20:05:27 - DEBUG - ci_test]: (api_request)  : [Collection.compact] args: [180], kwargs: {} (api_request.py:62)

[2024-04-22T20:32:02.549Z] [2024-04-22 20:05:27 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-04-22T20:32:02.549Z] [2024-04-22 20:10:35 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-04-22T20:32:02.549Z] [2024-04-22 20:11:22 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-04-22T20:32:02.549Z] [2024-04-22 20:11:22 - INFO - ci_test]: assert create collection: 0.031424522399902344, init_entities: 26000 (test_all_collections_after_chaos.py:49)

[2024-04-22T20:32:02.549Z] [2024-04-22 20:11:24 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [[[-3000, -2999, -2998, -2997, -2996, -2995, -2994, -2993, -2992, -2991, -2990, -2989, -2988, -2987, -2986, -2985, -2984, -2983, -2982, -2981, -2980, -2979, -2978, -2977, -2976, -2975, -2974, -2973, -2972, -2971, -2970, -2969, -2968, -2967, -2966, -2965, -2964, -2963, -2962, -2961, -2960, -2959, -29......, kwargs: {'timeout': 180} (api_request.py:62)

[2024-04-22T20:32:02.549Z] [2024-04-22 20:14:25 - ERROR - pymilvus.decorators]: grpc RpcError: [batch_insert], <_MultiThreadedRendezvous: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded>, <Time:{'RPC start': '2024-04-22 20:11:24.903857', 'gRPC error': '2024-04-22 20:14:25.199346'}> (decorators.py:150)

[2024-04-22T20:32:02.549Z] [2024-04-22 20:14:25 - ERROR - ci_test]: Traceback (most recent call last):

[2024-04-22T20:32:02.549Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2024-04-22T20:32:02.549Z]     res = func(*args, **_kwargs)

[2024-04-22T20:32:02.549Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2024-04-22T20:32:02.549Z]     return func(*arg, **kwargs)

[2024-04-22T20:32:02.549Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 513, in insert

[2024-04-22T20:32:02.549Z]     return conn.batch_insert(

[2024-04-22T20:32:02.549Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 154, in handler

[2024-04-22T20:32:02.549Z]     raise e from e

[2024-04-22T20:32:02.549Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2024-04-22T20:32:02.549Z]     return func(*args, **kwargs)

[2024-04-22T20:32:02.549Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 175, in handler

[2024-04-22T20:32:02.549Z]     return func(self, *args, **kwargs)

[2024-04-22T20:32:02.549Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 90, in handler

[2024-04-22T20:32:02.549Z]     raise e from e

[2024-04-22T20:32:02.549Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 86, in handler

[2024-04-22T20:32:02.549Z]     return func(*args, **kwargs)

[2024-04-22T20:32:02.549Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 579, in batch_insert

[2024-04-22T20:32:02.549Z]     raise err from err

[2024-04-22T20:32:02.549Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 572, in batch_insert

[2024-04-22T20:32:02.549Z]     response = rf.result()

[2024-04-22T20:32:02.549Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 881, in result

[2024-04-22T20:32:02.549Z]     raise self

[2024-04-22T20:32:02.549Z] grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:

[2024-04-22T20:32:02.549Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2024-04-22T20:32:02.549Z] 	details = "Deadline Exceeded"

[2024-04-22T20:32:02.549Z] 	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-04-22T20:14:25.198901526+00:00", grpc_status:4, grpc_message:"Deadline Exceeded"}"

[2024-04-22T20:32:02.549Z] >

[2024-04-22T20:32:02.549Z]  (api_request.py:45)

[2024-04-22T20:32:02.549Z] [2024-04-22 20:14:25 - ERROR - ci_test]: (api_response) : <_MultiThreadedRendezvous of RPC that terminated with:

[2024-04-22T20:32:02.549Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2024-04-22T20:32:02.549Z] 	details = "Deadline Exceeded"

[2024-04-22T20:32:02.549Z] 	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-04-22T20:14:25.198901526+00:00", grpc_status:4, grpc_message:"Deadline Exceeded"}"

[2024-04-22T20:32:02.549Z] > (api_request.py:46)
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-cron/detail/chaos-test-kafka-cron/13411/pipeline/337
log:
[artifacts-s3-pod-kill-13411-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/15070928/artifacts-s3-pod-kill-13411-server-logs.tar.gz)

**Comment by xiaofan-luan** [comment]
/assign @XuanYang-cn 
please help on it

**Comment by smellthemoon** [comment]
<img width="1187" alt="image" src="https://github.com/milvus-io/milvus/assets/64083300/b8e0483d-b928-4e5a-8f3e-26bd8e9ededd">
consume msg failed for timeout. kafka may not very stable.

**Comment by zhuwenxing** [comment]
not reproduced recently
