### ISSUE TITLE
[Bug]: create collection failed with error `failed to watch channels, code: UnexpectedError, reason: context deadline exceeded`

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#32540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):kafka    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2024-04-23T09:46:39.366Z] [2024-04-23 09:46:13 - INFO - ci_test]: Test case of search interface: initialize before test case (client_base.py:244)

[2024-04-23T09:46:39.366Z] [2024-04-23 09:46:13 - DEBUG - ci_test]: (api_request)  : [Connections.connect] args: ['default', '', '', 'default', ''], kwargs: {'host': 'msk-32535-1-pr-milvus.milvus-ci', 'port': '19530'} (api_request.py:62)

[2024-04-23T09:46:39.366Z] [2024-04-23 09:46:15 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-04-23T09:46:39.366Z] [2024-04-23 09:46:15 - DEBUG - ci_test]: (api_request)  : [FieldSchema] args: ['int64', <DataType.INT64: 5>, ''], kwargs: {'is_primary': False} (api_request.py:62)

[2024-04-23T09:46:39.366Z] [2024-04-23 09:46:15 - DEBUG - ci_test]: (api_response) : {'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>}  (api_request.py:37)

[2024-04-23T09:46:39.366Z] [2024-04-23 09:46:15 - DEBUG - ci_test]: (api_request)  : [FieldSchema] args: ['float_vector', <DataType.FLOAT_VECTOR: 101>, ''], kwargs: {'dim': 128, 'is_primary': False} (api_request.py:62)

[2024-04-23T09:46:39.366Z] [2024-04-23 09:46:15 - DEBUG - ci_test]: (api_response) : {'name': 'float_vector', 'description': '', 'type': <DataType.FLOAT_VECTOR: 101>, 'params': {'dim': 128}}  (api_request.py:37)

[2024-04-23T09:46:39.366Z] [2024-04-23 09:46:15 - DEBUG - ci_test]: (api_request)  : [CollectionSchema] args: [[{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>}, {'name': 'float_vector', 'description': '', 'type': <DataType.FLOAT_VECTOR: 101>, 'params': {'dim': 128}}], ''], kwargs: {'primary_field': 'int64', 'auto_id': False, 'enable_dynamic_field': True} (api_request.py:62)

[2024-04-23T09:46:39.366Z] [2024-04-23 09:46:15 - DEBUG - ci_test]: (api_response) : {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float_vector', 'description': '', 'type': <DataType.FLOAT_VECTOR: 101>, 'params': {'dim': 128}}], 'enable_dynamic_field': True}  (api_request.py:37)

[2024-04-23T09:46:39.366Z] [2024-04-23 09:46:15 - DEBUG - ci_test]: (api_request)  : [FieldSchema] args: ['int64', <DataType.INT64: 5>, ''], kwargs: {'is_primary': False} (api_request.py:62)

[2024-04-23T09:46:39.366Z] [2024-04-23 09:46:15 - DEBUG - ci_test]: (api_response) : {'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>}  (api_request.py:37)

[2024-04-23T09:46:39.366Z] [2024-04-23 09:46:15 - DEBUG - ci_test]: (api_request)  : [FieldSchema] args: ['float_vector', <DataType.FLOAT_VECTOR: 101>, ''], kwargs: {'dim': 128, 'is_primary': False} (api_request.py:62)

[2024-04-23T09:46:39.366Z] [2024-04-23 09:46:15 - DEBUG - ci_test]: (api_response) : {'name': 'float_vector', 'description': '', 'type': <DataType.FLOAT_VECTOR: 101>, 'params': {'dim': 128}}  (api_request.py:37)

[2024-04-23T09:46:39.366Z] [2024-04-23 09:46:15 - DEBUG - ci_test]: (api_request)  : [CollectionSchema] args: [[{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>}, {'name': 'float_vector', 'description': '', 'type': <DataType.FLOAT_VECTOR: 101>, 'params': {'dim': 128}}], ''], kwargs: {'primary_field': 'int64', 'auto_id': False, 'enable_dynamic_field': True} (api_request.py:62)

[2024-04-23T09:46:39.366Z] [2024-04-23 09:46:15 - DEBUG - ci_test]: (api_response) : {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float_vector', 'description': '', 'type': <DataType.FLOAT_VECTOR: 101>, 'params': {'dim': 128}}], 'enable_dynamic_field': True}  (api_request.py:37)

[2024-04-23T09:46:39.366Z] [2024-04-23 09:46:15 - INFO - ci_test]: init_collection_general: collection creation (client_base.py:268)

[2024-04-23T09:46:39.366Z] [2024-04-23 09:46:15 - DEBUG - ci_test]: (api_request)  : [Connections.has_connection] args: ['default'], kwargs: {} (api_request.py:62)

[2024-04-23T09:46:39.366Z] [2024-04-23 09:46:15 - DEBUG - ci_test]: (api_response) : True  (api_request.py:37)

[2024-04-23T09:46:39.366Z] [2024-04-23 09:46:15 - DEBUG - ci_test]: (api_request)  : [Collection] args: ['search_collection_3pHydVxE', {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float_vector', 'description': '', 'type': <DataType.FLOAT_VECTOR: 101>, 'params': {'dim': 128}}], 'enable......, kwargs: {'consistency_level': 'Strong'} (api_request.py:62)

[2024-04-23T09:46:39.366Z] [2024-04-23 09:46:27 - ERROR - pymilvus.decorators]: RPC error: [create_collection], <MilvusException: (code=65535, message=failed to watch channels, code: UnexpectedError, reason: context deadline exceeded)>, <Time:{'RPC start': '2024-04-23 09:46:15.466988', 'RPC error': '2024-04-23 09:46:27.078170'}> (decorators.py:146)

[2024-04-23T09:46:39.366Z] [2024-04-23 09:46:27 - ERROR - ci_test]: Traceback (most recent call last):

[2024-04-23T09:46:39.366Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2024-04-23T09:46:39.366Z]     res = func(*args, **_kwargs)

[2024-04-23T09:46:39.366Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2024-04-23T09:46:39.366Z]     return func(*arg, **kwargs)

[2024-04-23T09:46:39.366Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 151, in __init__

[2024-04-23T09:46:39.366Z]     conn.create_collection(self._name, schema, **kwargs)

[2024-04-23T09:46:39.367Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 147, in handler

[2024-04-23T09:46:39.367Z]     raise e from e

[2024-04-23T09:46:39.367Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 143, in handler

[2024-04-23T09:46:39.367Z]     return func(*args, **kwargs)

[2024-04-23T09:46:39.367Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 182, in handler

[2024-04-23T09:46:39.367Z]     return func(self, *args, **kwargs)

[2024-04-23T09:46:39.367Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 122, in handler

[2024-04-23T09:46:39.367Z]     raise e from e

[2024-04-23T09:46:39.367Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 87, in handler

[2024-04-23T09:46:39.367Z]     return func(*args, **kwargs)

[2024-04-23T09:46:39.367Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 304, in create_collection

[2024-04-23T09:46:39.367Z]     check_status(status)

[2024-04-23T09:46:39.367Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/utils.py", line 62, in check_status

[2024-04-23T09:46:39.367Z]     raise MilvusException(status.code, status.reason, status.error_code)

[2024-04-23T09:46:39.367Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=failed to watch channels, code: UnexpectedError, reason: context deadline exceeded)>

[2024-04-23T09:46:39.367Z]  (api_request.py:45)

[2024-04-23T09:46:39.367Z] [2024-04-23 09:46:27 - ERROR - ci_test]: (api_response) : <MilvusException: (code=65535, message=failed to watch channels, code: UnexpectedError, reason: context deadline exceeded)> (api_request.py:46)
```

### Milvus Log

failed job: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-32535/1/pipeline/199

**Comment by zhuwenxing** [comment]
not reproduced recently
