### ISSUE TITLE
[Bug]: No module named 'milvus_model' 

### ISSUE THREAD

**Issue by weiyi88** [milvus-io/milvus#32691]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

when i use this code 
`
from pymilvus import model

openai_ef = model.dense.OpenAIEmbeddingFunction(
    model_name='text-embedding-3-large', # Specify the model name
    api_key='YOUR_API_KEY', # Provide your OpenAI API key
    dimensions=512 # Set the embedding dimensionality
)
`
and have that error

### Expected Behavior

have error , ande i run 
`
pip install pymilvus[model]
`

have another error

`
zsh: no matches found: pymilvus[model]
`

### Steps To Reproduce

```markdown
1,copy code
2,run python
3,reappear
```

### Milvus Log

(llamaindex) (base) bluefocus_work@ringdeMacBook-Air autoGen % python main.py 
Traceback (most recent call last):
  File "/Users/bluefocus_work/miniconda3/envs/llamaindex/lib/python3.10/site-packages/pymilvus/model/__init__.py", line 24, in _load_milvus_model
    import milvus_model
ModuleNotFoundError: No module named 'milvus_model'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bluefocus_work/Desktop/work/program/python/autoGen/main.py", line 7, in <module>
    from app.routers import V1
  File "/Users/bluefocus_work/Desktop/work/program/python/autoGen/app/routers.py", line 5, in <module>
    from app.api.milvus import router as milvus_router
  File "/Users/bluefocus_work/Desktop/work/program/python/autoGen/app/api/milvus.py", line 3, in <module>
    from app.service.milvus_service import MilvusService
  File "/Users/bluefocus_work/Desktop/work/program/python/autoGen/app/service/milvus_service.py", line 9, in <module>
    class MilvusService:
  File "/Users/bluefocus_work/Desktop/work/program/python/autoGen/app/service/milvus_service.py", line 14, in MilvusService
    openai_ef = model.dense.OpenAIEmbeddingFunction(
  File "/Users/bluefocus_work/miniconda3/envs/llamaindex/lib/python3.10/site-packages/pymilvus/model/__init__.py", line 10, in __getattr__
    self._load_milvus_model()
  File "/Users/bluefocus_work/miniconda3/envs/llamaindex/lib/python3.10/site-packages/pymilvus/model/__init__.py", line 33, in _load_milvus_model
    raise ImportError(err_str) from e
ImportError: The 'milvus_model' package is not installed. For installation, use 'pip install pymilvus[model]'. For more information, please visit https://github.com/milvus-io/milvus-model.

**Comment by yanliang567** [comment]
/assign @wxywb 
please help to take a look
/unassign

**Comment by wxywb** [comment]
@weiyi88 for zsh, you need to use 
```bash
pip install "pymilvus[model]"
```

**Comment by weiyi88** [comment]
![image](https://github.com/milvus-io/milvus/assets/32037147/347a4fa0-293d-42ca-8d14-77c215164e36)
focus i have do this way ,and nothing help

**Comment by weiyi88** [comment]
> @weiyi88对于zsh，你需要使用
> 
> ```shell
> pip install“pymilvus[model]“
> ```

unbelieveable it work , But the pip prompt is pip install pymilvus[model]. This does not work. Can you improve the prompt or annotate it in the document

**Comment by cnzackliu** [comment]
请问你这个问题解决了吗？我今天用BGEM3EmbeddingFunction也遇到这个问题
