### ISSUE TITLE
SDK deserialization costs too much time

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#3271]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
when nq set 10000, the response time cost too much (more than 2min) during `end to end` searching.
```
2020-08-15:17:37:07,556 INFO     [client.py:36] Milvus preload_collection run in 0.24s
2020-08-15:17:37:07,875 DEBUG    [local_runner.py:379] Search nq: 10000, top-k: 10, search_param: {"nprobe": 1}, metric_type: l2
2020-08-15:17:39:39,637 INFO     [local_runner.py:389] Query ann_accuracy: 0.418
2020-08-15:17:39:39,673 DEBUG    [local_runner.py:379] Search nq: 10000, top-k: 10, search_param: {"nprobe": 2}, metric_type: l2
^CTraceback (most recent call last):
  File "main.py", line 181, in <module>
    main()
  File "main.py", line 177, in main
    runner.run(run_type, collection)
  File "/home/zw/work/z/milvus_benchmark/local_runner.py", line 387, in run
    result_ids = milvus_instance.get_ids(result)
  File "/home/zw/work/z/milvus_benchmark/client.py", line 243, in get_ids
    for item in result:
  File "/usr/local/lib/python3.6/dist-packages/milvus/client/abstract.py", line 37, in __next__
    return self.__getitem__(self.__index - 1)
  File "/usr/local/lib/python3.6/dist-packages/milvus/client/abstract.py", line 32, in __getitem__
    return self.get__item(item)
  File "/usr/local/lib/python3.6/dist-packages/milvus/client/abstract.py", line 331, in get__item
    slice_entity = self._entities[start: end]
  File "/usr/local/lib/python3.6/dist-packages/milvus/client/abstract.py", line 26, in __getitem__
    elements.append(self.get__item(i))
  File "/usr/local/lib/python3.6/dist-packages/milvus/client/abstract.py", line 196, in get__item
    fatal_item = sum([1 for v in self._valid_raw[:item] if v])
  File "/usr/local/lib/python3.6/dist-packages/milvus/client/abstract.py", line 196, in <listcomp>
    fatal_item = sum([1 for v in self._valid_raw[:item] if v])
KeyboardInterrupt
```
server log:
```
[2020-08-15 17:37:07,340][INFO][SERVER][PreloadCollection][grpcpp_sync_ser] Request [6320] PreloadCollection begin.
[2020-08-15 17:37:07,578][INFO][SERVER][PreloadCollection][grpcpp_sync_ser] Request [6320] PreloadCollection end.
[2020-08-15 17:37:08,476][INFO][SERVER][Search][grpcpp_sync_ser] Request [6321] Search begin.
[2020-08-15 17:37:10,288][INFO][SERVER][Search][grpcpp_sync_ser] Request [6321] Search end.

```
**Steps/Code to reproduce behavior**
dataset: sift-1m

**Expected behavior**

**Environment details**
master-branch

**Screenshots**

**Additional context**

**Comment by BossZou** [comment]
Need to optimize python sdk.

**Comment by BossZou** [comment]
Here is my test scripts:
```
import random
import time

from milvus import *

if __name__ == '__main__':
    client = Milvus()

    dim = 128

    vectors = [[random.random() for _ in range(dim)] for _ in range(10000)]

    ints = [random.randint(0, 127) for _ in range(10000)]

    collection = "test_example_result"

    if client.has_collection(collection):
        client.drop_collection(collection)

    client.create_collection(collection, {"fields": [
                                                     {"name": "Int", "type": DataType.INT32},
                                                     {"name": "Vec", "type": DataType.FLOAT_VECTOR, "params": {"dim": dim}}
                                                    ]
                                         }
                             )

    client.bulk_insert(collection, [{"name": "Vec", "values": vectors}, {"name": "Int", "values": ints}])
    client.flush([collection])

    query_vectors = [[random.random() for _ in range(dim)] for _ in range(1000)]

    dsl = {
        "bool": {
            "must": [
                {
                    "vector": {
                        "Vec": {"topk": 200, "query": query_vectors, "metric_type": "L2"}
                    }
                }
            ]
        }
    }

    results = client.search(collection, dsl)

    t0 = time.time()
    for i, r in enumerate(results):
        for j, rr in enumerate(r):
            print(f'[{i}, {j}] <{time.time() - t0} s> id = {rr.id}, distance = {rr.distance}')

    print(f"Loop results total cost {time.time() - t0}s")

    results2 = client.search(collection, dsl, fields=["Int"])

    client.drop_collection(collection)
```

The output is:
```
   ......
   ......
   ......
   
[999, 199] <1.4351272583007812 s> id = 1608520076307365847, distance = 17.8914794921875
Loop results total cost 1.4351344108581543s

```

**Comment by BossZou** [comment]
@del-zhenwu , Please check and regression using latest pymilvus-test.
