### ISSUE TITLE
[Bug]: load failed with error `code=65535, message=NodeNotFound` in many chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#33207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4-20240520-2f260cd3-amd64 and master
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2024-05-21T00:19:27.259Z] [2024-05-21 00:19:27 - INFO - ci_test]: [test][2024-05-21T00:19:26Z] [0.66574921s] Hello_Milvus flush -> None (wrapper.py:30)

[2024-05-21T00:19:27.260Z] [2024-05-21 00:19:27 - INFO - ci_test]: assert create collection: 0.004933357238769531, init_entities: 4000 (test_data_persistence.py:38)

[2024-05-21T00:19:27.820Z] [2024-05-21 00:19:27 - INFO - ci_test]: [test][2024-05-21T00:19:27Z] [0.50413442s] Hello_Milvus insert -> (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 449904841224880157, success count: 2000, err count: 0, cost: 0) (wrapper.py:30)

[2024-05-21T00:19:27.821Z] [2024-05-21 00:19:27 - INFO - ci_test]: assert insert: 0.5043199062347412 (test_data_persistence.py:45)

[2024-05-21T00:19:31.081Z] [2024-05-21 00:19:30 - INFO - ci_test]: [test][2024-05-21T00:19:27Z] [3.02795080s] Hello_Milvus flush -> None (wrapper.py:30)

[2024-05-21T00:19:31.336Z] [2024-05-21 00:19:31 - INFO - ci_test]: [test][2024-05-21T00:19:30Z] [0.51707758s] Hello_Milvus flush -> None (wrapper.py:30)

[2024-05-21T00:19:31.896Z] [2024-05-21 00:19:31 - INFO - ci_test]: [test][2024-05-21T00:19:31Z] [0.51545707s] Hello_Milvus flush -> None (wrapper.py:30)

[2024-05-21T00:19:31.898Z] [2024-05-21 00:19:31 - INFO - ci_test]: assert flush: 3.548692464828491, entities: 6000 (test_data_persistence.py:55)

[2024-05-21T00:19:31.898Z] [2024-05-21 00:19:31 - INFO - ci_test]: index info: [{'collection': 'Hello_Milvus', 'field': 'float_vector', 'index_name': 'test_qDtD2BVD', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}, {'collection': 'Hello_Milvus', 'field': 'varchar', 'index_name': 'test_56L4Jjxc', 'index_param': {}}] (test_data_persistence.py:74)

[2024-05-21T00:19:31.898Z] [2024-05-21 00:19:31 - INFO - ci_test]: [test][2024-05-21T00:19:31Z] [0.01232332s] Hello_Milvus load -> None (wrapper.py:30)

[2024-05-21T00:19:32.458Z] [2024-05-21 00:19:32 - INFO - ci_test]: [test][2024-05-21T00:19:31Z] [0.54293441s] Hello_Milvus search -> data: ["['id: 1360, distance: 0.36964741349220276, entity: {}']"] , cost: 0 (wrapper.py:30)

[2024-05-21T00:19:32.459Z] [2024-05-21 00:19:32 - INFO - ci_test]: assert search: 0.5431017875671387 (test_data_persistence.py:86)

[2024-05-21T00:19:33.383Z] [2024-05-21 00:19:33 - INFO - ci_test]: [test][2024-05-21T00:19:32Z] [1.01491624s] Hello_Milvus release -> None (wrapper.py:30)

[2024-05-21T00:19:34.306Z] [2024-05-21 00:19:33 - INFO - ci_test]: [test][2024-05-21T00:19:33Z] [0.46974126s] Hello_Milvus insert -> (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 449904842876649474, success count: 2000, err count: 0, cost: 0) (wrapper.py:30)

[2024-05-21T00:19:37.564Z] [2024-05-21 00:19:37 - INFO - ci_test]: [test][2024-05-21T00:19:33Z] [3.04014148s] Hello_Milvus flush -> None (wrapper.py:30)

[2024-05-21T00:19:37.565Z] [2024-05-21 00:19:37 - INFO - ci_test]: assert entities: 8000 (test_data_persistence.py:93)

[2024-05-21T00:19:37.565Z] [2024-05-21 00:19:37 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=65535, message=NodeNotFound)>, <Time:{'RPC start': '2024-05-21 00:19:37.037347', 'RPC error': '2024-05-21 00:19:37.048752'}> (decorators.py:146)

[2024-05-21T00:19:37.565Z] [2024-05-21 00:19:37 - ERROR - ci_test]: Traceback (most recent call last):

[2024-05-21T00:19:37.565Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2024-05-21T00:19:37.565Z]     res = func(*args, **_kwargs)

[2024-05-21T00:19:37.565Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2024-05-21T00:19:37.565Z]     return func(*arg, **kwargs)

[2024-05-21T00:19:37.565Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 424, in load

[2024-05-21T00:19:37.565Z]     conn.load_collection(

[2024-05-21T00:19:37.565Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 147, in handler

[2024-05-21T00:19:37.565Z]     raise e from e

[2024-05-21T00:19:37.565Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 143, in handler

[2024-05-21T00:19:37.565Z]     return func(*args, **kwargs)

[2024-05-21T00:19:37.565Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 182, in handler

[2024-05-21T00:19:37.565Z]     return func(self, *args, **kwargs)

[2024-05-21T00:19:37.565Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 122, in handler

[2024-05-21T00:19:37.565Z]     raise e from e

[2024-05-21T00:19:37.565Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 87, in handler

[2024-05-21T00:19:37.565Z]     return func(*args, **kwargs)

[2024-05-21T00:19:37.565Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 1148, in load_collection

[2024-05-21T00:19:37.565Z]     check_status(response)

[2024-05-21T00:19:37.565Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/utils.py", line 63, in check_status

[2024-05-21T00:19:37.565Z]     raise MilvusException(status.code, status.reason, status.error_code)

[2024-05-21T00:19:37.565Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=NodeNotFound)>

[2024-05-21T00:19:37.565Z]  (api_request.py:45)
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-for-release-cron/detail/chaos-test-kafka-for-release-cron/13489/pipeline

log:

[artifacts-etcd-pod-kill-13489-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/15383480/artifacts-etcd-pod-kill-13489-server-logs.tar.gz)

**Comment by yanliang567** [comment]
could be a dup to #33200 
/assign @weiliu1031 
/unassign

**Comment by weiliu1031** [comment]
please verify this with latest image

**Comment by zhuwenxing** [comment]
not reproduced in master-latest and 2.4-latest
