### ISSUE TITLE
Support for cmd "get_config *"

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#3329]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
>>> from milvus import Milvus
>>> m=Milvus(host="192.168.1.112", port=19530)
>>> m._cmd("get_config *")
Error: <BaseException: (code=1, message=Unknown exception happened on GET command.)>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/milvus/client/stub.py", line 35, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/milvus/client/stub.py", line 170, in _cmd
    return handler._cmd(cmd, timeout)
  File "/usr/local/lib/python3.6/dist-packages/milvus/client/grpc_handler.py", line 50, in handler
    raise e
  File "/usr/local/lib/python3.6/dist-packages/milvus/client/grpc_handler.py", line 42, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/milvus/client/grpc_handler.py", line 248, in _cmd
    raise BaseException(response.status.error_code, response.status.reason)
milvus.client.exceptions.BaseException: <BaseException: (code=1, message=Unknown exception happened on GET command.)>

```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment details**
- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)

**Screenshots**

**Additional context**

**Comment by godchen0212** [comment]
Add a feature in PR #3347 .
please use _cmd("get_milvus_config") and get config json as follows:
{
    "cache.cache_insert_data":"false",
    "cache.cache_size":"4294967296",
    "cache.cpu_cache_threshold":"0.700000",
    "cache.insert_buffer_size":"1073741824",
    "cache.preload_collection":"",
    "cluster.enable":"false",
    "cluster.role":"rw",
    "engine.build_index_threshold":"4096",
    "engine.omp_thread_num":"0",
    "engine.search_combine_nq":"64",
    "engine.simd_type":"auto",
    "engine.use_blas_threshold":"1100",
    "general.meta_uri":"sqlite://:@:/",
    "general.timezone":"UTC+8",
    "gpu.build_index_devices":"gpu0,",
    "gpu.cache_size":"1073741824",
    "gpu.cache_threshold":"0.700000",
    "gpu.enable":"false",
    "gpu.gpu_search_threshold":"1000",
    "gpu.search_devices":"gpu0,",
    "logs.level":"debug",
    "logs.log_rotate_num":"0",
    "logs.max_log_file_size":"1073741824",
    "logs.path":"/tmp/milvus/logs",
    "logs.trace.enable":"true",
    "metric.address":"127.0.0.1",
    "metric.enable":"false",
    "metric.port":"9091",
    "network.bind.address":"0.0.0.0",
    "network.bind.port":"19530",
    "network.http.enable":"true",
    "network.http.port":"19121",
    "storage.auto_flush_interval":"1",
    "storage.path":"/tmp/milvus",
    "tracing.json_config_path":"",
    "version":"0.5",
    "wal.buffer_size":"268435456",
    "wal.enable":"true",
    "wal.path":"/tmp/milvus/wal",
    "wal.recovery_error_ignore":"false"
}
