### ISSUE TITLE
[Bug]: search failed with error `failed to search: invalid args: bitset size should be <= data count, but we get bitset size: 6006, data count: 3003` after rolling upgrade

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#33719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.4.1--> master-20240605-feeb869f-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```

[2024-06-06T17:41:24.958Z] [2024-06-06 17:41:22 - DEBUG - ci_test]: (api_request)  : [Collection.delete] args: ['int64 in [1072]', None, 120], kwargs: {} (api_request.py:62)

[2024-06-06T17:41:24.958Z] [2024-06-06 17:41:22 - DEBUG - ci_test]: (api_response) : (insert count: 0, delete count: 1, upsert count: 0, timestamp: 0, success count: 0, err count: 0)  (api_request.py:37)

[2024-06-06T17:41:24.958Z] [2024-06-06 17:41:22 - DEBUG - ci_test]: insert request record cost 5.27501106262207e-06s (checker.py:236)

[2024-06-06T17:41:24.958Z] [2024-06-06 17:41:22 - DEBUG - ci_test]: [test][start time:2024-06-06 17:41:22.650167][time cost:0.00675005s][operation_name:delete][collection name:Checker__b57oUylj] -> True (checker.py:239)

[2024-06-06T17:41:24.958Z] [2024-06-06 17:41:22 - DEBUG - ci_test]: (api_request)  : [Collection.query] args: ['int64 in [486, 1589, 935, 317, 1758]', None, None, 10], kwargs: {} (api_request.py:62)

[2024-06-06T17:41:24.958Z] [2024-06-06 17:41:22 - DEBUG - ci_test]: insert data: [1717695682876648, 1717695682877718, 1717695682878781, 1717695682879840, 1717695682880905, 1717695682881936, 1717695682883006, 1717695682884079, 1717695682885115, 1717695682886180] (checker.py:555)

[2024-06-06T17:41:24.958Z] [2024-06-06 17:41:22 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [[[1717695682876648, 1717695682877718, 1717695682878781, 1717695682879840, 1717695682880905, 1717695682881936, 1717695682883006, 1717695682884079, 1717695682885115, 1717695682886180], [0.7479522, 0.2405455, 0.7757129, 0.54255927, 0.7353406, 0.08584014, 0.20091842, 0.16425678, 0.809223, 0.991372], ['......, kwargs: {'timeout': 120} (api_request.py:62)

[2024-06-06T17:41:24.958Z] [2024-06-06 17:41:22 - DEBUG - ci_test]: insert request record cost 7.931143045425415e-06s (checker.py:236)

[2024-06-06T17:41:24.958Z] [2024-06-06 17:41:22 - DEBUG - ci_test]: [test][start time:2024-06-06 17:41:22.875153][time cost:0.02618385s][operation_name:insert][collection name:Checker__b57oUylj] -> True (checker.py:239)

[2024-06-06T17:41:24.958Z] [2024-06-06 17:41:23 - DEBUG - ci_test]: (api_response) : [{'int64': 317}, {'int64': 486}, {'int64': 935}]  (api_request.py:37)

[2024-06-06T17:41:24.958Z] [2024-06-06 17:41:23 - DEBUG - ci_test]: insert request record cost 8.402392268180847e-06s (checker.py:236)

[2024-06-06T17:41:24.958Z] [2024-06-06 17:41:23 - DEBUG - ci_test]: [test][start time:2024-06-06 17:41:22.796193][time cost:0.39918341s][operation_name:query][collection name:Checker__b57oUylj] -> True (checker.py:239)

[2024-06-06T17:41:24.958Z] [2024-06-06 17:41:23 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on QueryNode 37: worker(40) query failed:  => failed to search: invalid args: bitset size should be <= data count, but we get bitset size: 6006, data count: 3003)>, <Time:{'RPC start': '2024-06-06 17:41:22.604960', 'RPC error': '2024-06-06 17:41:23.639246'}> (decorators.py:126)

[2024-06-06T17:41:24.958Z] [2024-06-06 17:41:23 - ERROR - ci_test]: Traceback (most recent call last):

[2024-06-06T17:41:24.958Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2024-06-06T17:41:24.958Z]     res = func(*args, **_kwargs)

[2024-06-06T17:41:24.958Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2024-06-06T17:41:24.958Z]     return func(*arg, **kwargs)

[2024-06-06T17:41:24.958Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 778, in search

[2024-06-06T17:41:24.958Z]     res = conn.search(

[2024-06-06T17:41:24.958Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 127, in handler

[2024-06-06T17:41:24.958Z]     raise e from e

[2024-06-06T17:41:24.958Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 123, in handler

[2024-06-06T17:41:24.958Z]     return func(*args, **kwargs)

[2024-06-06T17:41:24.958Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 162, in handler

[2024-06-06T17:41:24.958Z]     return func(self, *args, **kwargs)

[2024-06-06T17:41:24.958Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 102, in handler

[2024-06-06T17:41:24.958Z]     raise e from e

[2024-06-06T17:41:24.958Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 68, in handler

[2024-06-06T17:41:24.958Z]     return func(*args, **kwargs)

[2024-06-06T17:41:24.958Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 774, in search

[2024-06-06T17:41:24.958Z]     return self._execute_search_requests(

[2024-06-06T17:41:24.958Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 735, in _execute_search_requests

[2024-06-06T17:41:24.958Z]     raise pre_err from pre_err

[2024-06-06T17:41:24.959Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 726, in _execute_search_requests

[2024-06-06T17:41:24.959Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2024-06-06T17:41:24.959Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on QueryNode 37: worker(40) query failed:  => failed to search: invalid args: bitset size should be <= data count, but we get bitset size: 6006, data count: 3003)>
```

![image](https://github.com/milvus-io/milvus/assets/12268675/4ff54c54-67ae-41eb-80ee-cb26d69e04df)

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/rolling_update_for_operator_test_simple/detail/rolling_update_for_operator_test_simple/3642/pipeline

log:
[artifacts-kafka-cluster-3642-server-logs.tar.gz](https://github.com/user-attachments/files/15721568/artifacts-kafka-cluster-3642-server-logs.tar.gz)

cluster: 4am
ns: chaos-testing
pod 
```
[2024-06-06T17:42:44.559Z] + kubectl get pods -o wide

[2024-06-06T17:42:44.560Z] + grep kafka-cluster-3642

[2024-06-06T17:42:45.131Z] kafka-cluster-3642-etcd-0                                        1/1     Running            0                  40m     10.104.27.135   4am-node31   <none>           <none>

[2024-06-06T17:42:45.131Z] kafka-cluster-3642-etcd-1                                        1/1     Running            0                  40m     10.104.15.168   4am-node20   <none>           <none>

[2024-06-06T17:42:45.131Z] kafka-cluster-3642-etcd-2                                        1/1     Running            0                  40m     10.104.18.149   4am-node25   <none>           <none>

[2024-06-06T17:42:45.131Z] kafka-cluster-3642-kafka-0                                       2/2     Running            1 (39m ago)        40m     10.104.15.178   4am-node20   <none>           <none>

[2024-06-06T17:42:45.131Z] kafka-cluster-3642-kafka-1                                       2/2     Running            0                  40m     10.104.27.144   4am-node31   <none>           <none>

[2024-06-06T17:42:45.131Z] kafka-cluster-3642-kafka-2                                       2/2     Running            1 (39m ago)        40m     10.104.23.87    4am-node27   <none>           <none>

[2024-06-06T17:42:45.131Z] kafka-cluster-3642-kafka-exporter-7d68b75448-gv6zk               1/1     Running            4 (39m ago)        40m     10.104.9.228    4am-node14   <none>           <none>

[2024-06-06T17:42:45.131Z] kafka-cluster-3642-kafka-zookeeper-0                             1/1     Running            0                  40m     10.104.27.141   4am-node31   <none>           <none>

[2024-06-06T17:42:45.131Z] kafka-cluster-3642-kafka-zookeeper-1                             1/1     Running            0                  40m     10.104.15.183   4am-node20   <none>           <none>

[2024-06-06T17:42:45.131Z] kafka-cluster-3642-kafka-zookeeper-2                             1/1     Running            0                  40m     10.104.21.241   4am-node24   <none>           <none>

[2024-06-06T17:42:45.131Z] kafka-cluster-3642-milvus-datacoord-745954766f-htvh4             1/1     Running            0                  22m     10.104.25.194   4am-node30   <none>           <none>

[2024-06-06T17:42:45.132Z] kafka-cluster-3642-milvus-datanode-7c9f875b48-2l9p8              1/1     Running            0                  15m     10.104.27.250   4am-node31   <none>           <none>

[2024-06-06T17:42:45.132Z] kafka-cluster-3642-milvus-datanode-7c9f875b48-kr95l              1/1     Running            0                  16m     10.104.13.82    4am-node16   <none>           <none>

[2024-06-06T17:42:45.132Z] kafka-cluster-3642-milvus-datanode-7c9f875b48-rxrxh              1/1     Running            0                  14m     10.104.32.42    4am-node39   <none>           <none>

[2024-06-06T17:42:45.132Z] kafka-cluster-3642-milvus-indexcoord-68c59bd965-24s5m            1/1     Running            0                  22m     10.104.25.193   4am-node30   <none>           <none>

[2024-06-06T17:42:45.132Z] kafka-cluster-3642-milvus-indexnode-7f95c99d9d-hpljz             1/1     Running            0                  28m     10.104.13.64    4am-node16   <none>           <none>

[2024-06-06T17:42:45.132Z] kafka-cluster-3642-milvus-indexnode-7f95c99d9d-k85ct             1/1     Running            0                  30m     10.104.25.144   4am-node30   <none>           <none>

[2024-06-06T17:42:45.132Z] kafka-cluster-3642-milvus-indexnode-7f95c99d9d-x2wdl             1/1     Running            0                  29m     10.104.27.191   4am-node31   <none>           <none>

[2024-06-06T17:42:45.132Z] kafka-cluster-3642-milvus-proxy-5856ff5f64-dtndv                 1/1     Running            0                  15m     10.104.27.249   4am-node31   <none>           <none>

[2024-06-06T17:42:45.132Z] kafka-cluster-3642-milvus-querycoord-5c97b6d5bf-wsfzx            1/1     Running            0                  20m     10.104.27.222   4am-node31   <none>           <none>

[2024-06-06T17:42:45.132Z] kafka-cluster-3642-milvus-querynode-1-676b6988f4-ccsl4           1/1     Running            0                  17m     10.104.25.196   4am-node30   <none>           <none>

[2024-06-06T17:42:45.132Z] kafka-cluster-3642-milvus-querynode-1-676b6988f4-mbkkp           1/1     Running            0                  16m     10.104.13.81    4am-node16   <none>           <none>

[2024-06-06T17:42:45.132Z] kafka-cluster-3642-milvus-querynode-1-676b6988f4-p9hl8           1/1     Running            0                  14m     10.104.27.252   4am-node31   <none>           <none>

[2024-06-06T17:42:45.132Z] kafka-cluster-3642-milvus-rootcoord-5c46b67b7c-r7dk7             1/1     Running            0                  24m     10.104.25.191   4am-node30   <none>           <none>

[2024-06-06T17:42:45.132Z] kafka-cluster-3642-minio-0                                       1/1     Running            0                  40m     10.104.27.139   4am-node31   <none>           <none>

[2024-06-06T17:42:45.132Z] kafka-cluster-3642-minio-1                                       1/1     Running            0                  40m     10.104.15.171   4am-node20   <none>           <none>

[2024-06-06T17:42:45.132Z] kafka-cluster-3642-minio-2                                       1/1     Running            0                  40m     10.104.21.240   4am-node24   <none>           <none>

[2024-06-06T17:42:45.132Z] kafka-cluster-3642-minio-3                                       1/1     Running            0                  40m     10.104.18.150   4am-node25   <none>           <none>
```

**Comment by zhuwenxing** [comment]
search starts to fail after QN updated

**Comment by zhuwenxing** [comment]
/assign @weiliu1031 
PTAL

**Comment by chasingegg** [comment]
this validation is inside knowhere, bitset size passed to knowhere larger than data size, something should be wrong in milvus. @weiliu1031 help take a look

**Comment by zhuwenxing** [comment]
Not reproduced
