### ISSUE TITLE
Add binary vectors failed with python-sdk Bug sdk/python

### ISSUE THREAD

**Issue by 0ZhangJc0** [milvus-io/milvus#3374]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
`Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/milvus/client/types.py", line 56, in __ne__
    return self != other
  File "/usr/local/python3/lib/python3.7/site-packages/milvus/client/types.py", line 56, in __ne__
    return self != other
  File "/usr/local/python3/lib/python3.7/site-packages/milvus/client/types.py", line 56, in __ne__
    return self != other
  [Previous line repeated 997 more times]
RecursionError: maximum recursion depth exceeded in comparison
**Steps/Code to reproduce behavior**

`import numpy as np
from milvus import *
import time
import json
import re
import sys
sys.setrecursionlimit(100000) 
file_path = "/home/bost.txt"
COLLECTION_NAME = "hamming_collections"
DIM = 12064
COLLECTION_PARAM = {
    # "collection_name": COLLECTION_NAME,
    "dimension": DIM,
    "index_file_size": 1024,
    # MetricType `HAMMING`, `JACCARD`, `TANIMOTO` are only used for binary vectors
    # "metric_type": MetricType.JACCARD
}
def read_data(file_path):
    f = open(file_path)
    line = f.readline()
    mer = []
    index = 0
    total = 300000
    while line and index < total:
        columns = line.split()
        _dic = json.loads(columns[1])
        _str = _dic['reuslt'][0]['feature']
        _list = re.findall(r'.{2}',_str)
        mer.append(_list)
        line = f.readline()
        index += 1
        print("input data {} , total ratio {}".format(index, index/total))
    f.close()
    data = np.array(mer).astype('uint8')
    return [bytes(vector) for vector in data]
def main(collection_name, metric_type):
    client = Milvus(host="localhost", port="19121", handler="HTTP")
    _, ok = client.has_collection(collection_name)
    if not ok:
        COLLECTION_PARAM["collection_name"] = collection_name
        COLLECTION_PARAM["metric_type"] = metric_type
        status = client.create_collection(COLLECTION_PARAM)
        if not status.OK():
            print("Create collection {} fail: {}".format(collection_name, status))
            sys.exit(1)
    else:
        client.drop_collection(collection_name)
    start = time.time()
    datas = read_data(read_data)
    end = time.time()
    print("read spent {}".format(end - start))
    status, _ = client.insert(collection_name, datas)
    if 0 != status.code:
        print("Insert binary vectors into collection {} failed: {}".format(collection_name, status))
        exit(1)
    client.flush([collection_name])
    index_param = {
        'nlist': 4096
    }
    print("Creating index: {}".format(index_param))
    start = time.time()
    status = client.create_index(collection_name, IndexType.IVF_FLAT, index_param)
    end = time.time()
    print("read spent {}".format(end - start))
    query_vectors = datas[0:9]
    search_param = {
        "nprobe": 20
    }
    start = time.time()
    status, results = client.search(collection_name, top_k=5, query_records=query_vectors, params=search_param)
    if 0 != status.code:
        print("Search failed. reason:{}".format(status.message))
    else:
        for result in results:
            print(result)
    end = time.time()
    print("search spent {}".format(end - start))
    #client.drop_collection(collection_name)
if __name__ == '__main__':
    binary_metric = MetricType.HAMMING
    main(COLLECTION_NAME, binary_metric)
[data.txt](https://github.com/milvus-io/milvus/files/5103254/data.txt)
`
**Expected behavior**

**Environment details**
centos7.6
python 3.7.5

**Additional context**
there are 40w+ row data in my file, the format of data can be found in data.txt

**Comment by shengjun1985** [comment]
@0ZhangJc0 
Excuse me, but can you provide your Milvus version and SDK version?

**Comment by 0ZhangJc0** [comment]
Milvus: milvus_cpu_0.10.1
Python: 3.7.5
pymilvus: 0.2.13

**Comment by 0ZhangJc0** [comment]
> @0ZhangJc0
> Excuse me, but can you provide your Milvus version and SDK version?

Milvus: milvus_cpu_0.10.1
Python: 3.7.5
pymilvus: 0.2.13
