### ISSUE TITLE
[Bug]: [CI] Standalone restarted 3 times and flush gets MilvusException: code=500, message=channel not found

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#33846]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

CI e2e test Jenkins link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-33836/1/pipeline/183

```

[2024-06-13T10:17:09.662Z] [2024-06-13 10:14:02 - INFO - ci_test]: inserted 10 data into collection search_collection_QXKptyeR (common_func.py:1821)

[2024-06-13T10:17:09.662Z] [2024-06-13 10:14:02 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-06-13T10:17:09.662Z] [2024-06-13 10:16:53 - ERROR - pymilvus.decorators]: RPC error: [flush], <MilvusException: (code=500, message=channel not found[channel=by-dev-rootcoord-dml_4_450434626574625551v0])>, <Time:{'RPC start': '2024-06-13 10:14:02.706741', 'RPC error': '2024-06-13 10:16:53.788984'}> (decorators.py:139)

[2024-06-13T10:17:09.662Z] [2024-06-13 10:16:53 - ERROR - ci_test]: Traceback (most recent call last):

[2024-06-13T10:17:09.662Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2024-06-13T10:17:09.662Z]     res = func(*args, **_kwargs)

[2024-06-13T10:17:09.662Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2024-06-13T10:17:09.662Z]     return func(*arg, **kwargs)

[2024-06-13T10:17:09.662Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 319, in flush

[2024-06-13T10:17:09.662Z]     conn.flush([self.name], timeout=timeout, **kwargs)

[2024-06-13T10:17:09.662Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 140, in handler

[2024-06-13T10:17:09.662Z]     raise e from e

[2024-06-13T10:17:09.662Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler

[2024-06-13T10:17:09.662Z]     return func(*args, **kwargs)

[2024-06-13T10:17:09.662Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 175, in handler

[2024-06-13T10:17:09.662Z]     return func(self, *args, **kwargs)

[2024-06-13T10:17:09.662Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 115, in handler

[2024-06-13T10:17:09.662Z]     raise e from e

[2024-06-13T10:17:09.662Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 86, in handler

[2024-06-13T10:17:09.662Z]     return func(*args, **kwargs)

[2024-06-13T10:17:09.662Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 1419, in flush

[2024-06-13T10:17:09.662Z]     check_status(response.status)

[2024-06-13T10:17:09.662Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/utils.py", line 63, in check_status

[2024-06-13T10:17:09.662Z]     raise MilvusException(status.code, status.reason, status.error_code)

[2024-06-13T10:17:09.662Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=500, message=channel not found[channel=by-dev-rootcoord-dml_4_450434626574625551v0])>

[2024-06-13T10:17:09.662Z]  (api_request.py:45)

[2024-06-13T10:17:09.662Z] [2024-06-13 10:16:53 - ERROR - ci_test]: (api_response) : <MilvusException: (code=500, message=channel not found[channel=by-dev-rootcoord-dml_4_450434626574625551v0])> (api_request.py:46)
```

**Comment by xiaofan-luan** [comment]
/assign @aoiasd 
can you help with it?

**Comment by sunby** [comment]
The create collection request of `search_collection_QXKptyeR` is not received by proxy. 
Maybe there's a bug in client codes or this client connected to another cluster.
@ThreadDao Is there any log in client to check this?

**Comment by yanliang567** [comment]
> The create collection request of `search_collection_QXKptyeR` was not received by proxy but it succeed. Maybe there's a bug in test codes or this client connected to another cluster. @ThreadDao Is there any log in client to check this?

please click the link above and download the logs in the artifacts

**Comment by aoiasd** [comment]
![1718626437202.jpg](https://github.com/milvus-io/milvus/assets/45024769/89963d69-2ce2-41ae-8200-46d5ee15b0b7)

grefana lost logs from 18：13：20 to 18：14：11 but collection create at 18：14：02，so we can not get any logs about error collection expect flush channel not found.

May bad network cause collection create success but watch failed and even no retry.

**Comment by sunby** [comment]
> ![1718626437202.jpg](https://private-user-images.githubusercontent.com/45024769/340301312-89963d69-2ce2-41ae-8200-46d5ee15b0b7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2Nzc0NzQsIm5iZiI6MTcxODY3NzE3NCwicGF0aCI6Ii80NTAyNDc2OS8zNDAzMDEzMTItODk5NjNkNjktMmNlMi00MWFlLTgyMDAtNDZkNWVlMTViMGI3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDAyMTkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3NjZiMWIwMzg5OTBjNDNhN2E4MGEzMWJmYWM2NGFhOThjZDI4OTc2M2U0Y2I1MTdkMmQyZjkxMGE1ZjhjNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e7baeW5pMDBKuaCg-bgj55wy6wsThJVRU_vB4rTEvtE)
> 
> grefana lost logs from 18：13：20 to 18：14：11 but collection create at 18：14：02，so we can not get any logs about error collection expect flush channel not found.
> 
> May bad network cause collection create success but watch failed and even no retry.

Datacoord checks channels needed to be watched every 1 second by default. It appears that datacoord never receive this request.
