### ISSUE TITLE
[Bug]: slow search request over 1m

### ISSUE THREAD

**Issue by ChaoXuaan** [milvus-io/milvus#33988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.9
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): 
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

I get a slow search request as below, the cost over 1 minute

```
[2024/06/18 14:22:14.545 +08:00] [DEBUG] [proxy/impl.go:2977] ["Search received"] [traceID=6233d6517bd3caa1] [role=proxy] [db=default] [collection=NL2DAL_RAG] [partitions="[]"] [dsl=] [len(PlaceholderGroup)=3084] [OutputFields="[prompt,answer,id]"] [search_params="[{\"key\":\"anns_field\",\"value\":\"embedding\"},{\"key\":\"topk\",\"value\":\"1\"},{\"key\":\"metric_type\",\"value\":\"L2\"},{\"key\":\"round_decimal\",\"value\":\"-1\"},{\"key\":\"ignore_growing\",\"value\":\"false\"},{\"key\":\"offset\",\"value\":\"0\"},{\"key\":\"params\",\"value\":\"{\\\"nprobe\\\":5}\"}]"] [travel_timestamp=0] [guarantee_timestamp=1718691729544]
[2024/06/18 14:22:14.545 +08:00] [DEBUG] [proxy/impl.go:3015] [tr/Search] [traceID=6233d6517bd3caa1] [msg="search request enqueue"] [duration=823.443µs]
[2024/06/18 14:22:14.545 +08:00] [DEBUG] [proxy/impl.go:3017] ["Search enqueued"] [traceID=6233d6517bd3caa1] [role=proxy] [msgID=450544726049816578] [timestamp=450544726049816578] [db=default] [collection=NL2DAL_RAG] [partitions="[]"] [dsl=] [len(PlaceholderGroup)=3084] [OutputFields="[prompt,answer,id]"] [search_params="[{\"key\":\"anns_field\",\"value\":\"embedding\"},{\"key\":\"topk\",\"value\":\"1\"},{\"key\":\"metric_type\",\"value\":\"L2\"},{\"key\":\"round_decimal\",\"value\":\"-1\"},{\"key\":\"ignore_growing\",\"value\":\"false\"},{\"key\":\"offset\",\"value\":\"0\"},{\"key\":\"params\",\"value\":\"{\\\"nprobe\\\":5}\"}]"] [travel_timestamp=0] [guarantee_timestamp=1718691729544]
[2024/06/18 14:22:14.546 +08:00] [DEBUG] [proxy/task_search.go:257] ["translate output fields"] [traceID=6233d6517bd3caa1] [msgID=450544726049816578] ["output fields"="[prompt,answer,id]"]
[2024/06/18 14:22:14.546 +08:00] [DEBUG] [proxy/task_search.go:300] ["create query plan"] [traceID=6233d6517bd3caa1] [msgID=450544726049816578] [dsl=] ["anns field"=embedding] ["query info"="topk:1 metric_type:\"L2\" search_params:\"{\\\"nprobe\\\":5}\" round_decimal:-1 "]
[2024/06/18 14:22:14.546 +08:00] [DEBUG] [proxy/task_search.go:333] [Proxy::searchTask::PreExecute] [traceID=6233d6517bd3caa1] [msgID=450544726049816578] [plan.OutputFieldIds="[102,103,100]"] [plan="vector_anns:<field_id:101 query_info:<topk:1 metric_type:\"L2\" search_params:\"{\\\"nprobe\\\":5}\" round_decimal:-1 > placeholder_tag:\"$0\" > output_field_ids:102 output_field_ids:103 output_field_ids:100 "]
[2024/06/18 14:22:14.546 +08:00] [DEBUG] [proxy/task_search.go:396] ["search PreExecute done."] [traceID=6233d6517bd3caa1] [msgID=450544726049816578] [travel_ts=18446744073709551615] [guarantee_ts=1718691729544] [use_default_consistency=false] ["consistency level"=Strong] [timeout_ts=0]
[2024/06/18 14:22:14.546 +08:00] [INFO] [proxy/meta_cache.go:751] ["no shard cache for collection, try to get shard leaders from QueryCoord"] [collectionName=NL2DAL_RAG]
544] [use_default_consistency=false] ["consistency level"=Strong] [timeout_ts=0]
[2024/06/18 14:23:22.081 +08:00] [DEBUG] [proxy/task_search.go:449] ["Search Execute done"] [traceID=6233d6517bd3caa1]
[2024/06/18 14:23:22.081 +08:00] [DEBUG] [proxy/task_search.go:450] ["tr/proxy execute search 450544726049816578"] [traceID=6233d6517bd3caa1] [msg=done] [duration=1m7.535455994s]
[2024/06/18 14:23:22.081 +08:00] [DEBUG] [proxy/task_search.go:589] ["all searches are finished or canceled"] [traceID=6233d6517bd3caa1] [msgID=450544726049816578]
[2024/06/18 14:23:22.081 +08:00] [DEBUG] [proxy/task_search.go:593] ["proxy receives one search result"] [traceID=6233d6517bd3caa1] [sourceID=0] [msgID=450544726049816578]
[2024/06/18 14:23:22.081 +08:00] [DEBUG] [proxy/task_search.go:473] ["tr/searchTask PostExecute"] [traceID=6233d6517bd3caa1] [msg=decodeResultStart] [duration=16.623µs]
[2024/06/18 14:23:22.081 +08:00] [DEBUG] [proxy/task_search.go:652] [tr/decodeSearchResults] [traceID=6233d6517bd3caa1] [msg="decodeSearchResults done"] [duration=74.585µs]
[2024/06/18 14:23:22.081 +08:00] [DEBUG] [proxy/task_search.go:489] ["proxy search post execute reduce"] [traceID=6233d6517bd3caa1] [msgID=450544726049816578] ["number of valid search results"=1]
[2024/06/18 14:23:22.081 +08:00] [DEBUG] [proxy/task_search.go:490] ["tr/searchTask PostExecute"] [traceID=6233d6517bd3caa1] [msg=reduceResultStart] [duration=10.502µs]
[2024/06/18 14:23:22.081 +08:00] [DEBUG] [proxy/task_search.go:714] [reduceSearchResultData] [traceID=6233d6517bd3caa1] [len(subSearchResultData)=1] [nq=1] [offset=0] [limit=1] [metricType=L2]
[2024/06/18 14:23:22.081 +08:00] [DEBUG] [proxy/task_search.go:753] [subSearchResultData] [traceID=6233d6517bd3caa1] ["result No."=0] [nq=1] [topk=1] ["length of FieldsData"=3]
[2024/06/18 14:23:22.082 +08:00] [DEBUG] [proxy/task_search.go:837] ["skip duplicated search result"] [traceID=6233d6517bd3caa1] [count=0]
[2024/06/18 14:23:22.082 +08:00] [DEBUG] [proxy/task_search.go:710] [tr/reduceSearchResultData] [traceID=6233d6517bd3caa1] [msg=done] [duration=91.181µs]
[2024/06/18 14:23:22.082 +08:00] [DEBUG] [proxy/task_search.go:506] ["Search post execute done"] [traceID=6233d6517bd3caa1] [msgID=450544726049816578]
[2024/06/18 14:23:22.082 +08:00] [DEBUG] [proxy/task_search.go:459] ["tr/searchTask PostExecute"] [traceID=6233d6517bd3caa1] [msg=done] [duration=312.793µs]
[2024/06/18 14:23:22.082 +08:00] [DEBUG] [proxy/impl.go:3059] [tr/Search] [traceID=6233d6517bd3caa1] [msg="wait search result"] [duration=1m7.536236195s]
[2024/06/18 14:23:22.082 +08:00] [DEBUG] [proxy/impl.go:3062] [tr/Search] [traceID=6233d6517bd3caa1] [msg="wait search result"] [duration=27.851µs]
[2024/06/18 14:23:22.082 +08:00] [DEBUG] [proxy/impl.go:3063] ["Search done"] [traceID=6233d6517bd3caa1] [role=proxy] [msgID=450544726049816578] [db=default] [collection=NL2DAL_RAG] [partitions="[]"] [dsl=] [len(PlaceholderGroup)=3084] [OutputFields="[prompt,answer,id]"] [search_params="[{\"key\":\"anns_field\",\"value\":\"embedding\"},{\"key\":\"topk\",\"value\":\"1\"},{\"key\":\"metric_type\",\"value\":\"L2\"},{\"key\":\"round_decimal\",\"value\":\"-1\"},{\"key\":\"offset\",\"value\":\"0\"},{\"key\":\"params\",\"value\":\"{\\\"nprobe\\\":5}\"}]"] [travel_timestamp=0] [guarantee_timestamp=1718691729544]
[2024/06/18 14:23:22.082 +08:00] [INFO] [proxy/impl.go:2961] ["Search slow"] [traceID=6233d6517bd3caa1] [role=proxy] [db=default] [collection=NL2DAL_RAG] [partitions="[]"] [dsl=] [len(PlaceholderGroup)=3084] [OutputFields="[prompt,answer,id]"] [search_params="[{\"key\":\"anns_field\",\"value\":\"embedding\"},{\"key\":\"topk\",\"value\":\"1\"},{\"key\":\"metric_type\",\"value\":\"L2\"},{\"key\":\"round_decimal\",\"value\":\"-1\"},{\"key\":\"offset\",\"value\":\"0\"},{\"key\":\"params\",\"value\":\"{\\\"nprobe\\\":5}\"}]"] [travel_timestamp=0] [guarantee_timestamp=1718691729544] [duration=1m7.537238718s]
```

And I found the method `GetShards` cost too much, the prometheus picture  illustrate that.
func (m *MetaCache) GetShards(ctx context.Context, withCache bool, database, collectionName string) (map[string][]nodeInfo, error) 

![image](https://github.com/milvus-io/milvus/assets/33273155/444572b9-9b59-4155-ac13-8d398264053e)

At the same time, datanode panic because of segment is not found.
```
panic: All attempts results:
attempt #1:segment 450519468192288996 not found
attempt #2:segment 450519468192288996 not found
attempt #3:segment 450519468192288996 not found
attempt #4:segment 450519468192288996 not found
attempt #5:segment 450519468192288996 not found
attempt #6:segment 450519468192288996 not found
attempt #7:segment 450519468192288996 not found
attempt #8:segment 450519468192288996 not found
attempt #9:segment 450519468192288996 not found
attempt #10:segment 450519468192288996 not found
attempt #11:segment 450519468192288996 not found


goroutine 12776259254 [running]:
github.com/milvus-io/milvus/internal/datanode.flushNotifyFunc.func1(0xc02e0fa640)
        /go/src/github.com/milvus-io/milvus/internal/datanode/flush_manager.go:857 +0x13f6
github.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).waitFinish(0xc025eb7c80, 0xc01882a4e0, 0xc0095a29a0)
        /go/src/github.com/milvus-io/milvus/internal/datanode/flush_task.go:204 +0xdb
created by github.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).init.func1
        /go/src/github.com/milvus-io/milvus/internal/datanode/flush_task.go:121 +0xf1
2024/06/18 16:04:04 maxprocs: Leaving GOMAXPROCS=6: CPU quota undefined
```

 querycoord has error log
```
[2024/06/18 14:21:41.263 +08:00] [WARN] [retry/retry.go:44] ["retry func failed"] ["retry time"=0] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"]
[2024/06/18 14:21:41.263 +08:00] [WARN] [grpcclient/client.go:328] ["ClientBase ReCall grpc first call get error"] [role=datacoord] [error="err: rpc error: code = DeadlineExceeded desc = context deadline exceeded\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:327 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:435 github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).GetRecoveryInfoV2\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/meta/coordinator_broker.go:156 github.com/milvus-io/milvus/internal/querycoordv2/meta.(*CoordinatorBroker).GetRecoveryInfoV2\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/meta/target_manager.go:207 github.com/milvus-io/milvus/internal/querycoordv2/meta.(*TargetManager).PullNextTargetV2.func1\n/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:42 github.com/milvus-io/milvus/internal/util/retry.Do\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/meta/target_manager.go:229 github.com/milvus-io/milvus/internal/querycoordv2/meta.(*TargetManager).PullNextTargetV2\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/meta/target_manager.go:125 github.com/milvus-io/milvus/internal/querycoordv2/meta.(*TargetManager).updateCollectionNextTarget\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/meta/target_manager.go:117 github.com/milvus-io/milvus/internal/querycoordv2/meta.(*TargetManager).UpdateCollectionNextTarget\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/observers/target_observer.go:214 github.com/milvus-io/milvus/internal/querycoordv2/observers.(*TargetObserver).updateNextTarget\n"]
[2024/06/18 14:21:41.263 +08:00] [ERROR] [meta/coordinator_broker.go:158] ["get recovery info failed"] [collectionID=448045620191647741] [partitionIDs="[]"] [error="context deadline exceeded"] [stack="github.com/milvus-io/milvus/internal/querycoordv2/meta.(*CoordinatorBroker).GetRecoveryInfoV2\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/meta/coordinator_broker.go:158\ngithub.com/milvus-io/milvus/internal/querycoordv2/meta.(*TargetManager).PullNextTargetV2.func1\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/meta/target_manager.go:207\ngithub.com/milvus-io/milvus/internal/util/retry.Do\n\t/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:42\ngithub.com/milvus-io/milvus/internal/querycoordv2/meta.(*TargetManager).PullNextTargetV2\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/meta/target_manager.go:229\ngithub.com/milvus-io/milvus/internal/querycoordv2/meta.(*TargetManager).updateCollectionNextTarget\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/meta/target_manager.go:125\ngithub.com/milvus-io/milvus/internal/querycoordv2/meta.(*TargetManager).UpdateCollectionNextTarget\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/meta/target_manager.go:117\ngithub.com/milvus-io/milvus/internal/querycoordv2/observers.(*TargetObserver).updateNextTarget\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/observers/target_observer.go:214\ngithub.com/milvus-io/milvus/internal/querycoordv2/observers.(*TargetObserver).check\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/observers/target_observer.go:143\ngithub.com/milvus-io/milvus/internal/querycoordv2/observers.(*TargetObserver).tryUpdateTarget\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/observers/target_observer.go:175\ngithub.com/milvus-io/milvus/internal/querycoordv2/observers.(*TargetObserver).schedule\n\t/go/src/github.com/milvus-io/milvus/internal/querycoordv2/observers/target_observer.go:103"]
[2024/06/18 14:21:51.664 +08:00] [WARN] [retry/retry.go:44] ["retry func failed"] ["retry time"=0] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"]
[2024/06/18 14:21:51.664 +08:00] [WARN] [grpcclient/client.go:328] ["ClientBase ReCall grpc first call get error"] [role=datacoord] [error="err: rpc error: code = DeadlineExceeded desc = context deadline exceeded\n, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace\n/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:327 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall\n/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/client/client.go:435 github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).GetRecoveryInfoV2\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/meta/coordinator_broker.go:156 github.com/milvus-io/milvus/internal/querycoordv2/meta.(*CoordinatorBroker).GetRecoveryInfoV2\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/meta/target_manager.go:207 github.com/milvus-io/milvus/internal/querycoordv2/meta.(*TargetManager).PullNextTargetV2.func1\n/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:42 github.com/milvus-io/milvus/internal/util/retry.Do\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/meta/target_manager.go:229 github.com/milvus-io/milvus/internal/querycoordv2/meta.(*TargetManager).PullNextTargetV2\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/meta/target_manager.go:125 github.com/milvu
s-io/milvus/internal/querycoordv2/meta.(*TargetManager).updateCollectionNextTarget\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/meta/target_manager.go:117 github.com/milvus-io/milvus/internal/q
uerycoordv2/meta.(*TargetManager).UpdateCollectionNextTarget\n/go/src/github.com/milvus-io/milvus/internal/querycoordv2/observers/target_observer.go:214 github.com/milvus-io/milvus/internal/querycoordv2/obse
rvers.(*TargetObserver).updateNextTarget\n"]
```

datacoord has error log
```
["failed to clean up subscriptions"] ["pulsar web"=http://33.151.8.4:80] [topic=copilot-rootcoord-dml_11] [subname=copilot-dataNode-9-copilot-rootcoord-dml_11_447284938082360498v0] [error="Delete \"http://33.151.8.4:80/admin/v2/persistent/public/default/copilot-rootcoord-dml_11/subscription/copilot-dataNode-9-copilot-rootcoord-dml_11_447284938082360498v0?force=true\": dial tcp 33.151.8.4:80: i/o timeout"]
```

the timeline is
1. datanode panic
2. datacoord log error
3. querycoord log error
4. slow search request 

### Expected Behavior
Why search cost over 1 minute ? 
I assume that a datanode panic will not affect search latency.

**Comment by xiaofan-luan** [comment]
1. please try 2.3.18 see if this is still a problem.

2.2.9 is no longer maintained , segment not found and many other issue should already be fixed by many later versions.

2. the log you offered is limited, you need to offer full log between

[2024/06/18 14:22:14.546 +08:00] [INFO] [proxy/meta_cache.go:751] ["no shard cache for collection, try to get shard leaders from QueryCoord"] [collectionName=NL2DAL_RAG]
544] [use_default_consistency=false] ["consistency level"=Strong] [timeout_ts=0]
[2024/06/18 14:23:22.081 +08:00] [DEBUG] [proxy/task_search.go:449] ["Search Execute done"] [traceID=6233d6517bd3caa1]

My suggestion is to upgrade to latest milvus and many of the problem has been fixed. let us know if there is still a problem for latest,

**Comment by yanliang567** [comment]
/assign @ChaoXuaan 
please try to upgrade to Milvus 2.4.5

**Comment by ChaoXuaan** [comment]
> 1. please try 2.3.18 see if this is still a problem.
> 
> 2.2.9 is no longer maintained , segment not found and many other issue should already be fixed by many later versions.
> 
> 2. the log you offered is limited, you need to offer full log between
> 
> [2024/06/18 14:22:14.546 +08:00] [INFO] [proxy/meta_cache.go:751] ["no shard cache for collection, try to get shard leaders from QueryCoord"] [collectionName=NL2DAL_RAG] 544] [use_default_consistency=false] ["consistency level"=Strong] [timeout_ts=0] [2024/06/18 14:23:22.081 +08:00] [DEBUG] [proxy/task_search.go:449] ["Search Execute done"] [traceID=6233d6517bd3caa1]
> 
> My suggestion is to upgrade to latest milvus and many of the problem has been fixed. let us know if there is still a problem for latest,

thank you for your reply, there are too many logs over dozens of pages, but it seems no more relative log abount this requst, we will consider your suggestion.
