### ISSUE TITLE
[Bug]: All collections load time after Milvus recovered from one pod standalone pod failure chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#34008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20240619-7b9462c0-amd64
- Deployment mode(standalone or cluster):one-pod-standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```

[2024-06-19T19:23:01.285Z] [2024-06-19 19:19:50 - INFO - ci_test]: [test][2024-06-19T19:19:49Z] [0.63040940s] Hello_Milvus insert -> (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 450579605779120129, success count: 2000, err count: 0, cost: 0) (wrapper.py:30)

[2024-06-19T19:23:01.285Z] [2024-06-19 19:19:50 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-06-19T19:23:01.285Z] [2024-06-19 19:19:53 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-06-19T19:23:01.285Z] [2024-06-19 19:19:53 - INFO - ci_test]: [test][2024-06-19T19:19:50Z] [3.58247638s] Hello_Milvus flush -> None (wrapper.py:30)

[2024-06-19T19:23:01.285Z] [2024-06-19 19:19:53 - INFO - ci_test]: assert entities: 8000 (test_data_persistence.py:93)

[2024-06-19T19:23:01.285Z] [2024-06-19 19:19:53 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 180], kwargs: {} (api_request.py:62)

[2024-06-19T19:23:01.285Z] [2024-06-19 19:22:54 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=wait for loading collection timeout, collection: Hello_Milvus)>, <Time:{'RPC start': '2024-06-19 19:19:53.928180', 'RPC error': '2024-06-19 19:22:54.109364'}> (decorators.py:139)

[2024-06-19T19:23:01.285Z] [2024-06-19 19:22:54 - WARNING - pymilvus.decorators]: Retry timeout: 180s (decorators.py:105)

[2024-06-19T19:23:01.286Z] [2024-06-19 19:22:54 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for loading collection timeout, collection: Hello_Milvus)>, <Time:{'RPC start': '2024-06-19 19:19:53.921914', 'RPC error': '2024-06-19 19:22:54.110611'}> (decorators.py:139)

[2024-06-19T19:23:01.286Z] [2024-06-19 19:22:54 - ERROR - ci_test]: Traceback (most recent call last):

[2024-06-19T19:23:01.286Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2024-06-19T19:23:01.286Z]     res = func(*args, **_kwargs)

[2024-06-19T19:23:01.286Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2024-06-19T19:23:01.286Z]     return func(*arg, **kwargs)

[2024-06-19T19:23:01.286Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 424, in load

[2024-06-19T19:23:01.286Z]     conn.load_collection(

[2024-06-19T19:23:01.286Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 140, in handler

[2024-06-19T19:23:01.286Z]     raise e from e

[2024-06-19T19:23:01.286Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler

[2024-06-19T19:23:01.286Z]     return func(*args, **kwargs)

[2024-06-19T19:23:01.286Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 175, in handler

[2024-06-19T19:23:01.286Z]     return func(self, *args, **kwargs)

[2024-06-19T19:23:01.286Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 106, in handler

[2024-06-19T19:23:01.286Z]     raise MilvusException(

[2024-06-19T19:23:01.286Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for loading collection timeout, collection: Hello_Milvus)>

[2024-06-19T19:23:01.286Z]  (api_request.py:45)

[2024-06-19T19:23:01.286Z] [2024-06-19 19:22:54 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for loading collection timeout, collection: Hello_Milvus)> (api_request.py:46)

[2024-06-19T19:23:01.286Z] ------------- generated html file: file:///tmp/ci_logs/report.html -------------

[2024-06-19T19:23:01.286Z] =========================== short test summary info ============================

[2024-06-19T19:23:01.286Z] FAILED testcases/test_data_persistence.py::TestDataPersistence::test_milvus_default[default] - AssertionError: Response of API load expect True, but got False

[2024-06-19T19:23:01.286Z] FAILED testcases/test_data_persistence.py::TestDataPersistence::test_milvus_default[prod] - AssertionError: Response of API load expect True, but got False
```

### Expected Behavior

all tests success

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/15367/pipeline
log: 
[artifacts-one-pod-standalone-pod-failure-15367-server-logs.tar.gz](https://github.com/user-attachments/files/15908093/artifacts-one-pod-standalone-pod-failure-15367-server-logs.tar.gz)

### Anything else?

It used to be failed at flush, but now, flush can success, however, load failed

**Comment by weiliu1031** [comment]
load segment request failed again and again caused by memory  not enough, please increase the memory resource and retry the test 
![image](https://github.com/milvus-io/milvus/assets/108661493/81d30a7f-09b6-470f-8516-81a3a9b715bb)

**Comment by zhuwenxing** [comment]
After explicitly declaring the resources and ensuring their sufficiency, this issue no longer recurs.
