### ISSUE TITLE
[Bug]: Datacoord panic during test when Milvus already becomes healthy after datacoord pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#34013]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20240619-7b9462c0-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2024/06/19 17:27:08.976 +00:00] [DEBUG] [datacoord/index_service.go:892] ["GetIndexInfos successfully"] [traceID=927d48d2f0ac868b6fbaa841aa6c1db1] [collectionID=450577183870365061] [indexName=]
[2024/06/19 17:27:08.980 +00:00] [DEBUG] [datacoord/index_service.go:892] ["GetIndexInfos successfully"] [traceID=f9615ad015f9ab9695b0c6600f6fb1af] [collectionID=450577183870365061] [indexName=]
panic: runtime error: index out of range [0] with length 0

goroutine 378 [running]:
panic({0x5637900?, 0xc002093518?})
	/usr/local/go/src/runtime/panic.go:1017 +0x3ac fp=0xc0022fb0c8 sp=0xc0022fb018 pc=0x1e27b2c
runtime.goPanicIndex(0x0, 0x0)
	/usr/local/go/src/runtime/panic.go:114 +0x7c fp=0xc0022fb108 sp=0xc0022fb0c8 pc=0x1e2591c
github.com/milvus-io/milvus/internal/datacoord.(*meta).CompleteCompactionMutation(0xc00244a780, 0x0, 0xc00295ea80)
	/go/src/github.com/milvus-io/milvus/internal/datacoord/meta.go:1474 +0x1a99 fp=0xc0022fbaa0 sp=0xc0022fb108 pc=0x4576c79
github.com/milvus-io/milvus/internal/datacoord.(*mixCompactionTask).saveSegmentMeta(0xc001355ae0)
	/go/src/github.com/milvus-io/milvus/internal/datacoord/compaction_task_mix.go:116 +0x1c2 fp=0xc0022fbb70 sp=0xc0022fbaa0 pc=0x451a562
github.com/milvus-io/milvus/internal/datacoord.(*mixCompactionTask).processExecuting(0xc001355ae0)
	/go/src/github.com/milvus-io/milvus/internal/datacoord/compaction_task_mix.go:85 +0x33a fp=0xc0022fbcf0 sp=0xc0022fbb70 pc=0x4519e9a
github.com/milvus-io/milvus/internal/datacoord.(*mixCompactionTask).Process(0xc0022fbdb0?)
	/go/src/github.com/milvus-io/milvus/internal/datacoord/compaction_task_mix.go:132 +0x51 fp=0xc0022fbd08 sp=0xc0022fbcf0 pc=0x451a651
github.com/milvus-io/milvus/internal/datacoord.(*compactionPlanHandler).checkCompaction(0xc000dd0540)
	/go/src/github.com/milvus-io/milvus/internal/datacoord/compaction.go:619 +0x303 fp=0xc0022fbe20 sp=0xc0022fbd08 pc=0x45083c3
github.com/milvus-io/milvus/internal/datacoord.(*compactionPlanHandler).loopCheck(0xc000dd0540)
	/go/src/github.com/milvus-io/milvus/internal/datacoord/compaction.go:331 +0x22c fp=0xc0022fbfc8 sp=0xc0022fbe20 pc=0x45044cc
github.com/milvus-io/milvus/internal/datacoord.(*compactionPlanHandler).start.func2()
	/go/src/github.com/milvus-io/milvus/internal/datacoord/compaction.go:268 +0x25 fp=0xc0022fbfe0 sp=0xc0022fbfc8 pc=0x4503ce5
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0022fbfe8 sp=0xc0022fbfe0 pc=0x1e61381
created by github.com/milvus-io/milvus/internal/datacoord.(*compactionPlanHandler).start in goroutine 274
	/go/src/github.com/milvus-io/milvus/internal/datacoord/compaction.go:268 +0xb6
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/15354/pipeline

log:
[artifacts-datacoord-pod-kill-15354-server-logs (2).tar.gz](https://github.com/user-attachments/files/15908333/artifacts-datacoord-pod-kill-15354-server-logs.2.tar.gz)

**Comment by czs007** [comment]
working

**Comment by czs007** [comment]
pr https://github.com/milvus-io/milvus/pull/33982 merged.
please help to verifiy this in master branch. @zhuwenxing

**Comment by zhuwenxing** [comment]
Not reproduced
