### ISSUE TITLE
[Bug]: The load operation timed out under no interference.

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#34509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4-20240708-f2d0517f-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2024-07-08T08:30:06.690Z] [2024-07-08 08:19:43 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 2, 120], kwargs: {} (api_request.py:62)

[2024-07-08T08:30:06.690Z] [2024-07-08 08:21:43 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=wait for loading collection timeout, collection: deploy_test_index_type_IVF_FLAT_is_compacted_is_compacted_segment_status_all_is_string_indexed_is_string_indexed_replica_number_2_is_deleted_is_deleted_data_size_3000)>, <Time:{'RPC start': '2024-07-08 08:19:43.051533', 'RPC error': '2024-07-08 08:21:43.170732'}> (decorators.py:146)

[2024-07-08T08:30:06.690Z] [2024-07-08 08:21:43 - WARNING - pymilvus.decorators]: Retry timeout: 120s (decorators.py:106)

[2024-07-08T08:30:06.691Z] [2024-07-08 08:21:43 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: deploy_test_index_type_IVF_FLAT_is_compacted_is_compacted_segment_status_all_is_string_indexed_is_string_indexed_replica_number_2_is_deleted_is_deleted_data_size_3000)>, <Time:{'RPC start': '2024-07-08 08:19:43.036402', 'RPC error': '2024-07-08 08:21:43.171127'}> (decorators.py:146)

[2024-07-08T08:30:06.691Z] [2024-07-08 08:21:43 - ERROR - ci_test]: Traceback (most recent call last):

[2024-07-08T08:30:06.691Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2024-07-08T08:30:06.691Z]     res = func(*args, **_kwargs)

[2024-07-08T08:30:06.691Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2024-07-08T08:30:06.691Z]     return func(*arg, **kwargs)

[2024-07-08T08:30:06.691Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 424, in load

[2024-07-08T08:30:06.691Z]     conn.load_collection(

[2024-07-08T08:30:06.691Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 147, in handler

[2024-07-08T08:30:06.691Z]     raise e from e

[2024-07-08T08:30:06.691Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 143, in handler

[2024-07-08T08:30:06.691Z]     return func(*args, **kwargs)

[2024-07-08T08:30:06.691Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 182, in handler

[2024-07-08T08:30:06.691Z]     return func(self, *args, **kwargs)

[2024-07-08T08:30:06.691Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 107, in handler

[2024-07-08T08:30:06.691Z]     raise MilvusException(

[2024-07-08T08:30:06.691Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 120s, message=wait for loading collection timeout, collection: deploy_test_index_type_IVF_FLAT_is_compacted_is_compacted_segment_status_all_is_string_indexed_is_string_indexed_replica_number_2_is_deleted_is_deleted_data_size_3000)>

[2024-07-08T08:30:06.691Z]  (api_request.py:45)
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_for_release_cron/detail/deploy_test_for_release_cron/2017/pipeline

log:
[artifacts-pulsar-cluster-reinstall-2017-server-logs.tar.gz](https://github.com/user-attachments/files/16137254/artifacts-pulsar-cluster-reinstall-2017-server-logs.tar.gz)

**Comment by zhuwenxing** [comment]
Not a stable issue

**Comment by yanliang567** [comment]
lets close it for it could be env issue. please free to reopen it as it reproduced
