### ISSUE TITLE
Server crashed during stability test

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#3453]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**

log path:
```
/test/milvus/db_data_11/loop_stability_1598350730/logs
```
No stack message.
debug.log:
```
[2020-08-25 18:20:37,855][INFO][SERVER][Flush][grpcpp_sync_ser] Request [128] Flush begin.
[2020-08-25 18:20:38,183][INFO][SERVER][Flush][grpcpp_sync_ser] Request [128] Flush end.
[2020-08-25 18:20:38,191][INFO][SERVER][CountCollection][grpcpp_sync_ser] Request [129] CountCollection begin.
[2020-08-25 18:20:38,191][INFO][SERVER][CountCollection][grpcpp_sync_ser] Request [129] CountCollection end.
[2020-08-25 18:20:38,198][INFO][SERVER][GetEntityByID][grpcpp_sync_ser] Request [130] GetEntityByID begin.
[2020-08-25 18:20:38,320][INFO][SERVER][GetEntityByID][grpcpp_sync_ser] Request [130] GetEntityByID end.
[2020-08-25 18:20:38,329][INFO][SERVER][CountCollection][grpcpp_sync_ser] Request [131] CountCollection begin.
[2020-08-25 18:20:38,329][INFO][SERVER][CountCollection][grpcpp_sync_ser] Request [131] CountCollection end.
[2020-08-25 18:20:38,339][INFO][SERVER][Compact][grpcpp_sync_ser] Request [132] Compact begin.
[2020-08-25 18:20:38,340][INFO][SERVER][Compact][grpcpp_sync_ser] Request [132] Compact end.
[2020-08-25 18:20:38,349][INFO][SERVER][CountCollection][grpcpp_sync_ser] Request [133] CountCollection begin.
[2020-08-25 18:20:38,349][INFO][SERVER][CountCollection][grpcpp_sync_ser] Request [133] CountCollection end.
[2020-08-25 18:20:38,359][INFO][SERVER][ShowCollectionInfo][grpcpp_sync_ser] Request [134] ShowCollectionInfo begin.
[2020-08-25 18:20:38,360][INFO][SERVER][ShowCollectionInfo][grpcpp_sync_ser] Request [134] ShowCollectionInfo end.
[2020-08-25 18:20:38,368][INFO][SERVER][GetEntityIDs][grpcpp_sync_ser] Request [135] GetEntityIDs begin.
```
```
18:20:34  2020-08-25:10:20:34,830 INFO     [k8s_runner.py:818] collection_1_vxhkhdqe
18:20:34  2020-08-25:10:20:34,830 INFO     [k8s_runner.py:819] delete_rand
18:20:34  2020-08-25:10:20:34,842 DEBUG    [client.py:290] Row count: 100000 in collection: <collection_1_vxhkhdqe>
18:20:34  2020-08-25:10:20:34,842 INFO     [client.py:194] collection_1_vxhkhdqe: length to delete: 2
18:20:35  2020-08-25:10:20:35,52 INFO     [client.py:36] Milvus delete run in 0.01s
18:20:35  2020-08-25:10:20:35,380 INFO     [client.py:36] Milvus flush run in 0.33s
18:20:35  2020-08-25:10:20:35,394 DEBUG    [client.py:290] Row count: 99998 in collection: <collection_1_vxhkhdqe>
18:20:35  2020-08-25:10:20:35,394 INFO     [client.py:198] collection_1_vxhkhdqe: count after delete: 99998
18:20:35  2020-08-25:10:20:35,526 DEBUG    [client.py:290] Row count: 99998 in collection: <collection_1_vxhkhdqe>
18:20:35  2020-08-25:10:20:35,526 INFO     [k8s_runner.py:818] collection_2_bjmbzugj
18:20:35  2020-08-25:10:20:35,526 INFO     [k8s_runner.py:819] compact
18:20:35  2020-08-25:10:20:35,533 INFO     [client.py:36] Milvus compact run in 0.01s
18:20:35  2020-08-25:10:20:35,534 INFO     [k8s_runner.py:818] collection_3_sqal3spw
18:20:35  2020-08-25:10:20:35,534 INFO     [k8s_runner.py:819] query_rand
18:20:35  2020-08-25:10:20:35,536 INFO     [client.py:276] collection_3_sqal3spw, Search nq: 35, top_k: 100, nprobe: 54
18:20:35  2020-08-25:10:20:35,661 INFO     [k8s_runner.py:818] collection_0_9qar276o
18:20:35  2020-08-25:10:20:35,661 INFO     [k8s_runner.py:819] insert_rand
18:20:35  2020-08-25:10:20:35,680 DEBUG    [client.py:290] Row count: 100072 in collection: <collection_0_9qar276o>
18:20:35  2020-08-25:10:20:35,714 INFO     [client.py:36] Milvus insert run in 0.03s
18:20:36  2020-08-25:10:20:35,942 INFO     [client.py:36] Milvus flush run in 0.23s
18:20:36  2020-08-25:10:20:35,953 DEBUG    [client.py:290] Row count: 100129 in collection: <collection_0_9qar276o>
18:20:36  2020-08-25:10:20:35,954 INFO     [k8s_runner.py:818] collection_1_vxhkhdqe
18:20:36  2020-08-25:10:20:35,954 INFO     [k8s_runner.py:819] delete_rand
18:20:36  2020-08-25:10:20:35,963 DEBUG    [client.py:290] Row count: 99998 in collection: <collection_1_vxhkhdqe>
18:20:36  2020-08-25:10:20:35,963 INFO     [client.py:194] collection_1_vxhkhdqe: length to delete: 47
18:20:36  2020-08-25:10:20:36,133 INFO     [client.py:36] Milvus delete run in 0.01s

18:20:36  2020-08-25:10:20:36,659 INFO     [client.py:36] Milvus flush run in 0.53s
18:20:36  2020-08-25:10:20:36,668 DEBUG    [client.py:290] Row count: 99951 in collection: <collection_1_vxhkhdqe>
18:20:36  2020-08-25:10:20:36,668 INFO     [client.py:198] collection_1_vxhkhdqe: count after delete: 99951
18:20:36  2020-08-25:10:20:36,842 DEBUG    [client.py:290] Row count: 99951 in collection: <collection_1_vxhkhdqe>
18:20:36  2020-08-25:10:20:36,843 INFO     [k8s_runner.py:818] collection_2_bjmbzugj
18:20:36  2020-08-25:10:20:36,843 INFO     [k8s_runner.py:819] query_rand
18:20:36  2020-08-25:10:20:36,847 INFO     [client.py:276] collection_2_bjmbzugj, Search nq: 57, top_k: 63, nprobe: 43
18:20:36  2020-08-25:10:20:36,932 INFO     [k8s_runner.py:818] collection_0_9qar276o
18:20:36  2020-08-25:10:20:36,932 INFO     [k8s_runner.py:819] delete_rand
18:20:36  2020-08-25:10:20:36,944 DEBUG    [client.py:290] Row count: 100129 in collection: <collection_0_9qar276o>
18:20:36  2020-08-25:10:20:36,944 INFO     [client.py:194] collection_0_9qar276o: length to delete: 84
18:20:37  2020-08-25:10:20:36,984 INFO     [client.py:36] Milvus delete run in 0.01s
18:20:37  2020-08-25:10:20:37,510 INFO     [client.py:36] Milvus flush run in 0.53s
18:20:37  2020-08-25:10:20:37,520 DEBUG    [client.py:290] Row count: 100044 in collection: <collection_0_9qar276o>
18:20:37  2020-08-25:10:20:37,520 INFO     [client.py:198] collection_0_9qar276o: count after delete: 100044
18:20:37  2020-08-25:10:20:37,724 DEBUG    [client.py:290] Row count: 100044 in collection: <collection_0_9qar276o>
18:20:37  2020-08-25:10:20:37,724 INFO     [k8s_runner.py:818] collection_2_bjmbzugj
18:20:37  2020-08-25:10:20:37,724 INFO     [k8s_runner.py:819] query_rand
18:20:37  2020-08-25:10:20:37,726 INFO     [client.py:276] collection_2_bjmbzugj, Search nq: 37, top_k: 65, nprobe: 77
18:20:37  2020-08-25:10:20:37,773 INFO     [k8s_runner.py:818] collection_3_sqal3spw
18:20:37  2020-08-25:10:20:37,773 INFO     [k8s_runner.py:819] delete_rand
18:20:37  2020-08-25:10:20:37,779 DEBUG    [client.py:290] Row count: 100071 in collection: <collection_3_sqal3spw>
18:20:37  2020-08-25:10:20:37,779 INFO     [client.py:194] collection_3_sqal3spw: length to delete: 51
18:20:38  2020-08-25:10:20:37,850 INFO     [client.py:36] Milvus delete run in 0.01s
18:20:38  2020-08-25:10:20:38,179 INFO     [client.py:36] Milvus flush run in 0.33s
18:20:38  2020-08-25:10:20:38,187 DEBUG    [client.py:290] Row count: 100020 in collection: <collection_3_sqal3spw>
18:20:38  2020-08-25:10:20:38,187 INFO     [client.py:198] collection_3_sqal3spw: count after delete: 100020
18:20:38  2020-08-25:10:20:38,325 DEBUG    [client.py:290] Row count: 100020 in collection: <collection_3_sqal3spw>
18:20:38  2020-08-25:10:20:38,326 INFO     [k8s_runner.py:818] collection_3_sqal3spw
18:20:38  2020-08-25:10:20:38,326 INFO     [k8s_runner.py:819] compact
18:20:38  2020-08-25:10:20:38,339 INFO     [client.py:36] Milvus compact run in 0.01s
18:20:38  2020-08-25:10:20:38,339 INFO     [k8s_runner.py:818] collection_0_9qar276o
18:20:38  2020-08-25:10:20:38,339 INFO     [k8s_runner.py:819] delete_rand
18:20:38  2020-08-25:10:20:38,349 DEBUG    [client.py:290] Row count: 100044 in collection: <collection_0_9qar276o>
18:20:38  2020-08-25:10:20:38,349 INFO     [client.py:194] collection_0_9qar276o: length to delete: 45

18:20:38  RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
18:20:38  	status = StatusCode.UNAVAILABLE
18:20:38  	details = "Socket closed"
18:20:38  	debug_error_string = "{"created":"@1598350838.541901017","description":"Error received from peer ipv4:10.104.18.210:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
18:20:38  >
18:20:38  	{'API start': '2020-08-25 10:20:38.356830', 'RPC start': '2020-08-25 10:20:38.356835', 'RPC error': '2020-08-25 10:20:38.542472'}
18:20:38  2020-08-25:10:20:38,542 ERROR    [grpc_handler.py:58] RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
18:20:38  	status = StatusCode.UNAVAILABLE
18:20:38  	details = "Socket closed"
18:20:38  	debug_error_string = "{"created":"@1598350838.541901017","description":"Error received from peer ipv4:10.104.18.210:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
18:20:38  >
18:20:38  	{'API start': '2020-08-25 10:20:38.356830', 'RPC start': '2020-08-25 10:20:38.356835', 'RPC error': '2020-08-25 10:20:38.542472'}
18:20:38  2020-08-25:10:20:38,542 ERROR    [main.py:70] <_MultiThreadedRendezvous of RPC that terminated with:
18:20:38  	status = StatusCode.UNAVAILABLE
18:20:38  	details = "Socket closed"
18:20:38  	debug_error_string = "{"created":"@1598350838.541901017","description":"Error received from peer ipv4:10.104.18.210:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
18:20:38  >
18:20:38  2020-08-25:10:20:38,543 ERROR    [main.py:71] Traceback (most recent call last):
18:20:38    File "main.py", line 68, in queue_worker
18:20:38      runner.run(run_type, collection)
18:20:38    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/k8s_runner.py", line 821, in run
18:20:38      task_run()
18:20:38    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/client.py", line 195, in delete_rand
18:20:38      delete_ids = self.get_rand_ids(delete_id_length)
18:20:38    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/client.py", line 154, in get_rand_ids
18:20:38      segment_ids = self._milvus.list_id_in_segment(self._collection_name, segment["id"])
18:20:38    File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 35, in inner
18:20:38      return func(self, *args, **kwargs)
18:20:38    File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 419, in list_id_in_segment
18:20:38      return handler.get_vector_ids(collection_name, segment_id, timeout)
18:20:38    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 59, in handler
18:20:38      raise e
18:20:38    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 42, in handler
18:20:38      return func(self, *args, **kwargs)
18:20:38    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 451, in get_vector_ids
18:20:38      response = rf.result()
18:20:38    File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 625, in result
18:20:38      raise self
18:20:38  grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
18:20:38  	status = StatusCode.UNAVAILABLE
18:20:38  	details = "Socket closed"
18:20:38  	debug_error_string = "{"created":"@1598350838.541901017","description":"Error received from peer ipv4:10.104.18.210:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
18:20:38  >
18:20:38  

18:21:47  2020-08-25:10:21:38,602 DEBUG    [k8s_runner.py:72] Start clean up: milvus-benchmark-test-mw3gkt2g
18:21:47  2020-08-25:10:21:38,603 DEBUG    [utils.py:386] helm uninstall -n milvus milvus-benchmark-test-mw3gkt2g
18:21:47  release "milvus-benchmark-test-mw3gkt2g" uninstalled
```

**Steps/Code to reproduce behavior**
```
i = 0
            start_time = time.time()
            while time.time() < start_time + during_time * 60:
                i = i + 1
                q = self.gen_executors(operations)
                for name in q:
                    try:
                        if name == "insert":
                            insert_ids = random.sample(list(range(collection_size)), insert_xb)
                            insert_vectors = [[random.random() for _ in range(dimension)] for _ in range(insert_xb)]
                            entities = milvus_instance.generate_entities(insert_vectors, insert_ids)
                            milvus_instance.insert(entities, ids=insert_ids)
                        elif name == "delete":
                            delete_ids = random.sample(list(range(collection_size)), delete_xb)
                            milvus_instance.delete(delete_ids)
                        elif name == "query":
                            top_k = random.randint(l_top_k, g_top_k)
                            nq = random.randint(l_nq, g_nq)
                            search_param = {}
                            for k, v in search_params.items():
                                search_param[k] = random.randint(int(v.split("-")[0]), int(v.split("-")[1]))
                            logger.debug("Query nq: %d, top-k: %d, param: %s" % (nq, top_k, json.dumps(search_param)))
                            vector_query = {"vector": {vec_field_name: {
                                "topk": top_k, 
                                "query": query_vectors[:nq], 
                                "metric_type": real_metric_type, 
                                "params": search_param}
                            }}
                            result = milvus_instance.query(vector_query)
                        elif name in ["flush", "compact"]:
                            func = getattr(milvus_instance, name)
                            func()
                        logger.debug(milvus_instance.count())
                    except Exception as e:
                        logger.error(name)
                        logger.error(str(e))
                        raise
                logger.debug("Loop time: %d" % i)
```

**Expected behavior**

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
```
[2020-08-25 18:20:39,473][INFO][SERVER][Start][milvus_server] Milvus Release version: v0.11.0, built at 2020-08-25 09:19.37
[2020-08-25 18:20:39,473][INFO][SERVER][Start][milvus_server] CPU edition
```

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by BossZou** [comment]
Cannot reproduced in host machine, need to check again

**Comment by BossZou** [comment]
```
corrupted size vs. prev_size

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

Error log:
```
[2020-08-31 16:23:09,208][ERROR][SERVER][TakeToExecute][reqsched_thread] Req failed with code: Error code(30005): Segment not exist
[2020-08-31 16:23:22,310][ERROR][SERVER][operator()][milvus_server] [GC] Error when removing path /tmp/milvus-dev/db/collections/C_4/P_4/S_626: filesystem error: cannot remove all: Bad file descriptor [/tmp/milvus-dev/db/collections/C_4/P_4/S_626]
[2020-08-31 16:24:41,107][ERROR][SERVER][TakeToExecute][reqsched_thread] Req failed with code: Error code(30005): Segment not exist

```


[log.zip](https://github.com/milvus-io/milvus/files/5149471/log.zip)

**Comment by del-zhenwu** [comment]
Issue still can be reproduced:
```
18:55:48  2020-09-03:10:55:48,492 INFO     [k8s_runner.py:831] compact
18:55:48  2020-09-03:10:55:48,494 INFO     [client.py:36] Milvus compact run in 0.0s
18:55:48  2020-09-03:10:55:48,494 INFO     [k8s_runner.py:830] collection_1_xxdsoo5e
18:55:48  2020-09-03:10:55:48,494 INFO     [k8s_runner.py:831] flush
18:55:48  2020-09-03:10:55:48,495 INFO     [client.py:36] Milvus flush run in 0.0s
18:55:48  2020-09-03:10:55:48,496 INFO     [k8s_runner.py:830] collection_0_miyz3jrb
18:55:48  2020-09-03:10:55:48,496 INFO     [k8s_runner.py:831] query_rand
18:55:48  2020-09-03:10:55:48,496 INFO     [client.py:286] collection_0_miyz3jrb, Search nq: 30, top_k: 96, nprobe: 76
18:55:48  2020-09-03:10:55:48,526 INFO     [k8s_runner.py:830] collection_3_4udsttcp
18:55:48  2020-09-03:10:55:48,526 INFO     [k8s_runner.py:831] compact
18:55:48  2020-09-03:10:55:48,531 INFO     [client.py:36] Milvus compact run in 0.0s
18:55:48  2020-09-03:10:55:48,531 INFO     [k8s_runner.py:830] collection_3_4udsttcp
18:55:48  2020-09-03:10:55:48,531 INFO     [k8s_runner.py:831] insert_rand
18:55:48  2020-09-03:10:55:48,539 DEBUG    [client.py:300] Row count: 100009 in collection: <collection_3_4udsttcp>
18:55:48  2020-09-03:10:55:48,550 INFO     [client.py:36] Milvus insert run in 0.01s

18:55:48  2020-09-03:10:55:48,711 INFO     [client.py:36] Milvus flush run in 0.16s
18:55:48  2020-09-03:10:55:48,714 DEBUG    [client.py:300] Row count: 100062 in collection: <collection_3_4udsttcp>
18:55:48  2020-09-03:10:55:48,714 INFO     [k8s_runner.py:830] collection_3_4udsttcp
18:55:48  2020-09-03:10:55:48,714 INFO     [k8s_runner.py:831] insert_rand
18:55:48  2020-09-03:10:55:48,721 DEBUG    [client.py:300] Row count: 100062 in collection: <collection_3_4udsttcp>
18:55:48  2020-09-03:10:55:48,736 INFO     [client.py:36] Milvus insert run in 0.01s

18:57:25  RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
18:57:25  	status = StatusCode.UNAVAILABLE
18:57:25  	details = "Socket closed"
18:57:25  	debug_error_string = "{"created":"@1599130641.474796630","description":"Error received from peer ipv4:10.106.200.10:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
18:57:25  >
18:57:25  	{'API start': '2020-09-03 10:55:48.736260', 'RPC start': '2020-09-03 10:55:48.736267', 'RPC error': '2020-09-03 10:57:21.475063'}
18:57:25  2020-09-03:10:57:21,475 ERROR    [grpc_handler.py:58] RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
18:57:25  	status = StatusCode.UNAVAILABLE
18:57:25  	details = "Socket closed"
18:57:25  	debug_error_string = "{"created":"@1599130641.474796630","description":"Error received from peer ipv4:10.106.200.10:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
18:57:25  >
18:57:25  	{'API start': '2020-09-03 10:55:48.736260', 'RPC start': '2020-09-03 10:55:48.736267', 'RPC error': '2020-09-03 10:57:21.475063'}
18:57:25  2020-09-03:10:57:21,475 ERROR    [main.py:70] <_MultiThreadedRendezvous of RPC that terminated with:
18:57:25  	status = StatusCode.UNAVAILABLE
18:57:25  	details = "Socket closed"
18:57:25  	debug_error_string = "{"created":"@1599130641.474796630","description":"Error received from peer ipv4:10.106.200.10:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
18:57:25  >
18:57:25  2020-09-03:10:57:21,476 ERROR    [main.py:71] Traceback (most recent call last):
18:57:25    File "main.py", line 68, in queue_worker
18:57:25      runner.run(run_type, collection)
18:57:25    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/k8s_runner.py", line 833, in run
18:57:25      task_run()
18:57:25    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/client.py", line 148, in insert_rand
18:57:25      self.flush()
18:57:25    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/client.py", line 34, in wrapper
18:57:25      result = func(*args, **kwargs)
18:57:25    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/client.py", line 217, in flush
18:57:25      self._milvus.flush([tmp_collection_name])
18:57:25    File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 35, in inner
18:57:25      return func(self, *args, **kwargs)
18:57:25    File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 696, in flush
18:57:25      return handler.flush(collection_name_array, timeout, **kwargs)
18:57:25    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 59, in handler
18:57:25      raise e
18:57:25    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 42, in handler
18:57:25      return func(self, *args, **kwargs)
18:57:25    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 666, in flush
18:57:25      response = future.result()
18:57:25    File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 625, in result
18:57:25      raise self
18:57:25  grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
18:57:25  	status = StatusCode.UNAVAILABLE
18:57:25  	details = "Socket closed"
18:57:25  	debug_error_string = "{"created":"@1599130641.474796630","description":"Error received from peer ipv4:10.106.200.10:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
18:57:25  >
```
log and data path:
```
/test/milvus/db_data_11/loop_stability_1599129883
```

**Comment by BossZou** [comment]
> Issue still can be reproduced:
> 
> ```
> 18:55:48  2020-09-03:10:55:48,492 INFO     [k8s_runner.py:831] compact
> 18:55:48  2020-09-03:10:55:48,494 INFO     [client.py:36] Milvus compact run in 0.0s
> 18:55:48  2020-09-03:10:55:48,494 INFO     [k8s_runner.py:830] collection_1_xxdsoo5e
> 18:55:48  2020-09-03:10:55:48,494 INFO     [k8s_runner.py:831] flush
> 18:55:48  2020-09-03:10:55:48,495 INFO     [client.py:36] Milvus flush run in 0.0s
> 18:55:48  2020-09-03:10:55:48,496 INFO     [k8s_runner.py:830] collection_0_miyz3jrb
> 18:55:48  2020-09-03:10:55:48,496 INFO     [k8s_runner.py:831] query_rand
> 18:55:48  2020-09-03:10:55:48,496 INFO     [client.py:286] collection_0_miyz3jrb, Search nq: 30, top_k: 96, nprobe: 76
> 18:55:48  2020-09-03:10:55:48,526 INFO     [k8s_runner.py:830] collection_3_4udsttcp
> 18:55:48  2020-09-03:10:55:48,526 INFO     [k8s_runner.py:831] compact
> 18:55:48  2020-09-03:10:55:48,531 INFO     [client.py:36] Milvus compact run in 0.0s
> 18:55:48  2020-09-03:10:55:48,531 INFO     [k8s_runner.py:830] collection_3_4udsttcp
> 18:55:48  2020-09-03:10:55:48,531 INFO     [k8s_runner.py:831] insert_rand
> 18:55:48  2020-09-03:10:55:48,539 DEBUG    [client.py:300] Row count: 100009 in collection: <collection_3_4udsttcp>
> 18:55:48  2020-09-03:10:55:48,550 INFO     [client.py:36] Milvus insert run in 0.01s
> 
> 18:55:48  2020-09-03:10:55:48,711 INFO     [client.py:36] Milvus flush run in 0.16s
> 18:55:48  2020-09-03:10:55:48,714 DEBUG    [client.py:300] Row count: 100062 in collection: <collection_3_4udsttcp>
> 18:55:48  2020-09-03:10:55:48,714 INFO     [k8s_runner.py:830] collection_3_4udsttcp
> 18:55:48  2020-09-03:10:55:48,714 INFO     [k8s_runner.py:831] insert_rand
> 18:55:48  2020-09-03:10:55:48,721 DEBUG    [client.py:300] Row count: 100062 in collection: <collection_3_4udsttcp>
> 18:55:48  2020-09-03:10:55:48,736 INFO     [client.py:36] Milvus insert run in 0.01s
> 
> 18:57:25  RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
> 18:57:25  	status = StatusCode.UNAVAILABLE
> 18:57:25  	details = "Socket closed"
> 18:57:25  	debug_error_string = "{"created":"@1599130641.474796630","description":"Error received from peer ipv4:10.106.200.10:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
> 18:57:25  >
> 18:57:25  	{'API start': '2020-09-03 10:55:48.736260', 'RPC start': '2020-09-03 10:55:48.736267', 'RPC error': '2020-09-03 10:57:21.475063'}
> 18:57:25  2020-09-03:10:57:21,475 ERROR    [grpc_handler.py:58] RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
> 18:57:25  	status = StatusCode.UNAVAILABLE
> 18:57:25  	details = "Socket closed"
> 18:57:25  	debug_error_string = "{"created":"@1599130641.474796630","description":"Error received from peer ipv4:10.106.200.10:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
> 18:57:25  >
> 18:57:25  	{'API start': '2020-09-03 10:55:48.736260', 'RPC start': '2020-09-03 10:55:48.736267', 'RPC error': '2020-09-03 10:57:21.475063'}
> 18:57:25  2020-09-03:10:57:21,475 ERROR    [main.py:70] <_MultiThreadedRendezvous of RPC that terminated with:
> 18:57:25  	status = StatusCode.UNAVAILABLE
> 18:57:25  	details = "Socket closed"
> 18:57:25  	debug_error_string = "{"created":"@1599130641.474796630","description":"Error received from peer ipv4:10.106.200.10:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
> 18:57:25  >
> 18:57:25  2020-09-03:10:57:21,476 ERROR    [main.py:71] Traceback (most recent call last):
> 18:57:25    File "main.py", line 68, in queue_worker
> 18:57:25      runner.run(run_type, collection)
> 18:57:25    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/k8s_runner.py", line 833, in run
> 18:57:25      task_run()
> 18:57:25    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/client.py", line 148, in insert_rand
> 18:57:25      self.flush()
> 18:57:25    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/client.py", line 34, in wrapper
> 18:57:25      result = func(*args, **kwargs)
> 18:57:25    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/client.py", line 217, in flush
> 18:57:25      self._milvus.flush([tmp_collection_name])
> 18:57:25    File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 35, in inner
> 18:57:25      return func(self, *args, **kwargs)
> 18:57:25    File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 696, in flush
> 18:57:25      return handler.flush(collection_name_array, timeout, **kwargs)
> 18:57:25    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 59, in handler
> 18:57:25      raise e
> 18:57:25    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 42, in handler
> 18:57:25      return func(self, *args, **kwargs)
> 18:57:25    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 666, in flush
> 18:57:25      response = future.result()
> 18:57:25    File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 625, in result
> 18:57:25      raise self
> 18:57:25  grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
> 18:57:25  	status = StatusCode.UNAVAILABLE
> 18:57:25  	details = "Socket closed"
> 18:57:25  	debug_error_string = "{"created":"@1599130641.474796630","description":"Error received from peer ipv4:10.106.200.10:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
> 18:57:25  >
> ```
> 
> log and data path:
> 
> ```
> /test/milvus/db_data_11/loop_stability_1599129883
> ```

The crash location:
```0000000000a17290 <milvus::codec::IdBloomFilterFormat::Create(std::shared_ptr<milvus::storage::FSHandler> const&, std::string const&, std::shared_ptr<milvus::segment::IdBloomFilter>&)>:
....
 a177cc:       48 8d 7e e8             lea    -0x18(%rsi),%rdi
  a177d0:       48 39 ef                cmp    %rbp,%rdi
  a177d3:       74 05                   je     a177da <milvus::codec::IdBloomFilterFormat::Create(std::shared_ptr<milvus::storage::FSHandler> const&, std::string const&, std::shared_ptr<milvus::segment::IdBloomFilter>&)+0x54a>


```

**Comment by BossZou** [comment]
@del-zhenwu , need to regression
