### ISSUE TITLE
[Bug]: After restarting, the number of search results is one less than the limit value.

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#34590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20240710-ebc68d27-amd64
- Deployment mode(standalone or cluster):both
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```

[2024-07-10T10:06:49.233Z] + python3 scripts/second_recall_test.py --host 10.255.59.192

[2024-07-10T10:06:49.795Z] 2024-07-10 10:06:49.580 | INFO     | __main__:search_test:53 - recall test for index type HNSW

[2024-07-10T10:06:51.153Z] 2024-07-10 10:06:50.940 | INFO     | __main__:search_test:63 - 

[2024-07-10T10:06:51.153Z] Search...

[2024-07-10T10:06:56.385Z] 2024-07-10 10:06:56.127 | INFO     | __main__:search_test:69 - search cost  5.1862 seconds

[2024-07-10T10:06:56.945Z] Traceback (most recent call last):

[2024-07-10T10:06:56.946Z]   File "scripts/second_recall_test.py", line 103, in <module>

[2024-07-10T10:06:56.946Z]     search_test(host, index_type)

[2024-07-10T10:06:56.946Z]   File "scripts/second_recall_test.py", line 82, in search_test

[2024-07-10T10:06:56.946Z]     assert len(item) == len(true_ids[index]), f"get {len(item)} but expect {len(true_ids[index])}"

[2024-07-10T10:06:56.946Z] AssertionError: get 99 but expect 100
```

### Milvus Log

it is a stable reproduced issue. reproduced in (standalone, cluster)*(Kafka, pulsar)

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_cron/detail/deploy_test_cron/2515/pipeline
log:

[artifacts-rocksmq-standalone-reinstall-2515-server-logs.tar.gz](https://github.com/user-attachments/files/16170920/artifacts-rocksmq-standalone-reinstall-2515-server-logs.tar.gz)

**Comment by zhuwenxing** [comment]
Not reproduced in master-20241030-95521905-amd64 for a long time
