### ISSUE TITLE
Server crashed during adding entities

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#3482]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
[2020-08-27 12:17:31,269][INFO][SERVER][Insert][grpcpp_sync_ser] Request [298] Insert begin.
[2020-08-27 12:17:31,317][INFO][SERVER][OnExecute][reqsched_thread] [insert][0] Execute InsertReq.
[2020-08-27 12:17:31,342][INFO][SERVER][Insert][grpcpp_sync_ser] Request [298] Insert end.
[2020-08-27 12:17:31,427][INFO][SERVER][CountCollection][grpcpp_sync_ser] Request [299] CountCollection begin.
[2020-08-27 12:17:31,428][INFO][SERVER][CountCollection][grpcpp_sync_ser] Request [299] CountCollection end.
[2020-08-27 12:17:31,617][INFO][SERVER][DescribeCollection][grpcpp_sync_ser] Request [300] DescribeCollection begin.
[2020-08-27 12:17:31,618][INFO][SERVER][DescribeCollection][grpcpp_sync_ser] Request [300] DescribeCollection end.
[2020-08-27 12:17:36,572][INFO][SERVER][Insert][grpcpp_sync_ser] Request [301] Insert begin.
[2020-08-27 12:17:36,620][INFO][SERVER][OnExecute][reqsched_thread] [insert][0] Execute InsertReq.
[2020-08-27 12:17:36,643][INFO][SERVER][Insert][grpcpp_sync_ser] Request [301] Insert end.
[2020-08-27 12:17:36,727][INFO][SERVER][CountCollection][grpcpp_sync_ser] Request [302] CountCollection begin.
[2020-08-27 12:17:36,728][INFO][SERVER][CountCollection][grpcpp_sync_ser] Request [302] CountCollection end.
[2020-08-27 12:17:37,566][INFO][SERVER][HandleSignal][timing_metric] Server received critical signal: 11
[2020-08-27 12:17:37,566][INFO][SERVER][PrintStacktrace][timing_metric] Call stack:
[2020-08-27 12:17:37,566][INFO][SERVER][PrintStacktrace][timing_metric] /var/lib/milvus/bin/milvus_server() [0xd92d26]
[2020-08-27 12:17:37,566][INFO][SERVER][PrintStacktrace][timing_metric] /var/lib/milvus/bin/milvus_server() [0xd93890]
[2020-08-27 12:17:37,566][INFO][SERVER][PrintStacktrace][timing_metric] /lib64/libc.so.6(+0x36400) [0x7feef7863400]
[2020-08-27 12:17:37,566][INFO][SERVER][PrintStacktrace][timing_metric] /var/lib/milvus/bin/milvus_server() [0xcae967]
[2020-08-27 12:17:37,567][INFO][SERVER][PrintStacktrace][timing_metric] /var/lib/milvus/bin/milvus_server() [0xcb4b39]
[2020-08-27 12:17:37,567][INFO][SERVER][PrintStacktrace][timing_metric] /var/lib/milvus/bin/milvus_server() [0x5b5de5]
[2020-08-27 12:17:37,567][INFO][SERVER][PrintStacktrace][timing_metric] /var/lib/milvus/bin/milvus_server() [0x5b5f07]
[2020-08-27 12:17:37,567][INFO][SERVER][PrintStacktrace][timing_metric] /var/lib/milvus/bin/milvus_server() [0xda0cff]
[2020-08-27 12:17:37,567][INFO][SERVER][PrintStacktrace][timing_metric] /lib64/libpthread.so.0(+0x7ea5) [0x7feef8892ea5]
[2020-08-27 12:17:37,567][INFO][SERVER][PrintStacktrace][timing_metric] /lib64/libc.so.6(clone+0x6d) [0x7feef792b8dd]

```
```
2:19:50  2020-08-27:04:19:49,823 DEBUG    [client.py:290] Row count: 5450000 in collection: <sift_50m_100000_128_l2>
12:19:50  2020-08-27:04:19:49,823 DEBUG    [runner.py:196] 5450000
12:20:02  2020-08-27:04:20:02,21 INFO     [runner.py:189] Start id: 5500000, end id: 5550000
12:20:08  2020-08-27:04:20:08,242 INFO     [client.py:36] Milvus insert run in 6.16s
12:20:08  2020-08-27:04:20:08,253 DEBUG    [client.py:290] Row count: 5500000 in collection: <sift_50m_100000_128_l2>
12:20:08  2020-08-27:04:20:08,253 DEBUG    [runner.py:196] 5500000
12:20:08  2020-08-27:04:20:08,544 INFO     [runner.py:189] Start id: 5550000, end id: 5600000
12:20:15  2020-08-27:04:20:14,275 INFO     [client.py:36] Milvus insert run in 5.68s
12:20:15  2020-08-27:04:20:14,284 DEBUG    [client.py:290] Row count: 5550000 in collection: <sift_50m_100000_128_l2>
12:20:15  2020-08-27:04:20:14,284 DEBUG    [runner.py:196] 5550000
12:20:28  2020-08-27:04:20:26,998 INFO     [runner.py:189] Start id: 5600000, end id: 5650000
12:20:32  2020-08-27:04:20:32,368 INFO     [client.py:36] Milvus insert run in 5.31s
12:20:32  2020-08-27:04:20:32,371 DEBUG    [client.py:290] Row count: 5600000 in collection: <sift_50m_100000_128_l2>
12:20:32  2020-08-27:04:20:32,371 DEBUG    [runner.py:196] 5600000
12:20:32  2020-08-27:04:20:32,660 INFO     [runner.py:189] Start id: 5650000, end id: 5700000
12:20:39  RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
12:20:39  	status = StatusCode.CANCELLED
12:20:39  	details = "Cancelled"
12:20:39  	debug_error_string = "{"created":"@1598502039.393151777","description":"Error received from peer ipv4:10.105.225.186:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Cancelled","grpc_status":1}"
12:20:39  >
12:20:39  	{'API start': '2020-08-27 04:20:32.726090', 'RPC start': '2020-08-27 04:20:32.726101', 'RPC error': '2020-08-27 04:20:39.406298'}
12:20:39  2020-08-27:04:20:39,406 ERROR    [grpc_handler.py:58] RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
12:20:39  	status = StatusCode.CANCELLED
12:20:39  	details = "Cancelled"
12:20:39  	debug_error_string = "{"created":"@1598502039.393151777","description":"Error received from peer ipv4:10.105.225.186:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Cancelled","grpc_status":1}"
12:20:39  >
12:20:39  	{'API start': '2020-08-27 04:20:32.726090', 'RPC start': '2020-08-27 04:20:32.726101', 'RPC error': '2020-08-27 04:20:39.406298'}
12:20:39  2020-08-27:04:20:39,407 ERROR    [main.py:70] <_MultiThreadedRendezvous of RPC that terminated with:
12:20:39  	status = StatusCode.CANCELLED
12:20:39  	details = "Cancelled"
12:20:39  	debug_error_string = "{"created":"@1598502039.393151777","description":"Error received from peer ipv4:10.105.225.186:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Cancelled","grpc_status":1}"
12:20:39  >
12:20:39  2020-08-27:04:20:39,420 ERROR    [main.py:71] Traceback (most recent call last):
12:20:39    File "main.py", line 68, in queue_worker
12:20:39      runner.run(run_type, collection)
12:20:39    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/k8s_runner.py", line 125, in run
12:20:39      res = self.do_insert(milvus_instance, collection_name, data_type, dimension, collection_size, ni_per)
12:20:39    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/runner.py", line 193, in do_insert
12:20:39      res_ids = milvus.insert(entities, ids=ids)
12:20:39    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/client.py", line 34, in wrapper
12:20:39      result = func(*args, **kwargs)
12:20:39    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/client.py", line 132, in insert
12:20:39      insert_ids = self._milvus.insert(self._collection_name, entities, ids=ids)
12:20:39    File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 35, in inner
12:20:39      return func(self, *args, **kwargs)
12:20:39    File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 393, in insert
12:20:39      return handler.insert(collection_name, entities, ids, partition_tag, params, timeout, **kwargs)
12:20:39    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 59, in handler
12:20:39      raise e
12:20:39    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 42, in handler
12:20:39      return func(self, *args, **kwargs)
12:20:39    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 427, in insert
12:20:39      response = rf.result()
12:20:39    File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 625, in result
12:20:39      raise self
12:20:39  grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
12:20:39  	status = StatusCode.CANCELLED
12:20:39  	details = "Cancelled"
12:20:39  	debug_error_string = "{"created":"@1598502039.393151777","description":"Error received from peer ipv4:10.105.225.186:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Cancelled","grpc_status":1}"
12:20:39  >
12:20:39  
12:21:47  2020-08-27:04:21:39,452 DEBUG    [k8s_runner.py:72] Start clean up: milvus-benchmark-test-r4kzcwfb
12:21:47  2020-08-27:04:21:39,452 DEBUG    [utils.py:386] helm uninstall -n milvus milvus-benchmark-test-r4kzcwfb
12:21:47  release "milvus-benchmark-test-r4kzcwfb" uninstalled
```

**Steps/Code to reproduce behavior**
dataset size: sift50m-128d
the length of entities inserted per request: 50000
segment row count: 100000

**Expected behavior**

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by del-zhenwu** [comment]
fixed

**Comment by del-zhenwu** [comment]
```
[2020-09-03 11:17:09,621][INFO][SERVER][Insert][grpcpp_sync_ser] Request [948] Insert end.
[2020-09-03 11:17:09,680][INFO][SERVER][CountCollection][grpcpp_sync_ser] Request [949] CountCollection begin.
[2020-09-03 11:17:09,680][INFO][SERVER][CountCollection][grpcpp_sync_ser] Request [949] CountCollection end.
[2020-09-03 11:17:10,003][INFO][SERVER][DescribeCollection][grpcpp_sync_ser] Request [950] DescribeCollection begin.
[2020-09-03 11:17:10,003][INFO][SERVER][DescribeCollection][grpcpp_sync_ser] Request [950] DescribeCollection end.
[2020-09-03 11:17:10,611][INFO][SERVER][HandleSignal][timing_flush] Server received critical signal: 11
[2020-09-03 11:17:10,612][INFO][SERVER][PrintStacktrace][timing_flush] Call stack:
[2020-09-03 11:17:10,612][INFO][SERVER][PrintStacktrace][timing_flush] /var/lib/milvus/bin/milvus_server() [0xda6406]
[2020-09-03 11:17:10,612][INFO][SERVER][PrintStacktrace][timing_flush] /var/lib/milvus/bin/milvus_server() [0xda6f70]
[2020-09-03 11:17:10,612][INFO][SERVER][PrintStacktrace][timing_flush] /lib64/libc.so.6(+0x36400) [0x7fe0f2d53400]
[2020-09-03 11:17:10,612][INFO][SERVER][PrintStacktrace][timing_flush] /var/lib/milvus/bin/milvus_server() [0x954333]
[2020-09-03 11:17:10,612][INFO][SERVER][PrintStacktrace][timing_flush] /var/lib/milvus/bin/milvus_server() [0x954a82]
[2020-09-03 11:17:10,612][INFO][SERVER][PrintStacktrace][timing_flush] /var/lib/milvus/bin/milvus_server() [0x9633fa]
[2020-09-03 11:17:10,612][INFO][SERVER][PrintStacktrace][timing_flush] /var/lib/milvus/bin/milvus_server() [0x947f8a]
[2020-09-03 11:17:10,612][INFO][SERVER][PrintStacktrace][timing_flush] /var/lib/milvus/bin/milvus_server() [0x71fa2e]
[2020-09-03 11:17:10,612][INFO][SERVER][PrintStacktrace][timing_flush] /var/lib/milvus/bin/milvus_server() [0x720fac]
[2020-09-03 11:17:10,612][INFO][SERVER][PrintStacktrace][timing_flush] /var/lib/milvus/bin/milvus_server() [0x5c5734]
[2020-09-03 11:17:10,612][INFO][SERVER][PrintStacktrace][timing_flush] /var/lib/milvus/bin/milvus_server() [0x5cae9f]
[2020-09-03 11:17:10,612][INFO][SERVER][PrintStacktrace][timing_flush] /var/lib/milvus/bin/milvus_server() [0x71f4c8]
[2020-09-03 11:17:10,612][INFO][SERVER][PrintStacktrace][timing_flush] /var/lib/milvus/bin/milvus_server() [0x721093]
[2020-09-03 11:17:10,612][INFO][SERVER][PrintStacktrace][timing_flush] /var/lib/milvus/bin/milvus_server() [0x60ecb3]
[2020-09-03 11:17:10,612][INFO][SERVER][PrintStacktrace][timing_flush] /var/lib/milvus/bin/milvus_server() [0x60faa4]
[2020-09-03 11:17:10,612][INFO][SERVER][PrintStacktrace][timing_flush] /var/lib/milvus/bin/milvus_server() [0x5becf5]
[2020-09-03 11:17:10,612][INFO][SERVER][PrintStacktrace][timing_flush] /var/lib/milvus/bin/milvus_server() [0x5c2116]
[2020-09-03 11:17:10,612][INFO][SERVER][PrintStacktrace][timing_flush] /var/lib/milvus/bin/milvus_server() [0xdb43df]
[2020-09-03 11:17:10,612][INFO][SERVER][PrintStacktrace][timing_flush] /lib64/libpthread.so.0(+0x7ea5) [0x7fe0f3d82ea5]
[2020-09-03 11:17:10,612][INFO][SERVER][PrintStacktrace][timing_flush] /lib64/libc.so.6(clone+0x6d) [0x7fe0f2e1b8dd]

```

**Comment by del-zhenwu** [comment]
```
/test/milvus/db_data_011/sift_50m_100000_128_l2/logs
```

**Comment by del-zhenwu** [comment]
fixed, close
