### ISSUE TITLE
[Bug]: [benchmark]  test standalone crash because of build index core dump

### ISSUE THREAD

**Issue by zhagnlu** [milvus-io/milvus#34933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:  2.4-c13c48d
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

core dump
(gdb) bt
#0  runtime.raise () at /usr/local/go/src/runtime/sys_linux_amd64.s:154
#1  0x0000000001e68765 in runtime.dieFromSignal (sig=6) at /usr/local/go/src/runtime/signal_unix.go:903
#2  0x0000000001e68e66 in runtime.sigfwdgo (sig=6, info=<optimized out>, ctx=<optimized out>, ~r0=<optimized out>) at /usr/local/go/src/runtime/signal_unix.go:1108
#3  0x0000000001e67465 in runtime.sigtrampgo (sig=0, info=0x0, ctx=0x1e8ace1 <runtime.raise+33>) at /usr/local/go/src/runtime/signal_unix.go:432
#4  0x0000000001e8afe6 in runtime.sigtramp () at /usr/local/go/src/runtime/sys_linux_amd64.s:352
#5  0x0000000004e56985 in x_cgo_callers (sig=8, info=0xc0022d4630, context=0x0, cgoTraceback=<optimized out>, cgoCallers=<optimized out>, sigtramp=0xc0022d43a8) at gcc_traceback.c:45
#6  <signal handler called>
#7  runtime.raise () at /usr/local/go/src/runtime/sys_linux_amd64.s:154
#8  0x0000000001e68765 in runtime.dieFromSignal (sig=6) at /usr/local/go/src/runtime/signal_unix.go:903
#9  0x0000000001e67f05 in runtime.crash () at /usr/local/go/src/runtime/signal_unix.go:985
#10 runtime.sighandler (sig=11, info=<optimized out>, ctxt=<optimized out>, gp=<optimized out>) at /usr/local/go/src/runtime/signal_unix.go:771
#11 0x0000000001e6756e in runtime.sigtrampgo (sig=11, info=0xc0022d54b0, ctx=0xc0022d5380) at /usr/local/go/src/runtime/signal_unix.go:490
#12 0x0000000001e8afe6 in runtime.sigtramp () at /usr/local/go/src/runtime/sys_linux_amd64.s:352
#13 0x0000000004e56985 in x_cgo_callers (sig=8, info=0x5b9fb30, context=0x0, cgoTraceback=<optimized out>, cgoCallers=<optimized out>, sigtramp=0xc0022d51f0) at gcc_traceback.c:45
#14 <signal handler called>
#15 __gnu_cxx::__atomic_add (__val=1, __mem=<optimized out>) at /usr/include/c++/12/ext/atomicity.h:71
#16 __gnu_cxx::__atomic_add_dispatch (__val=1, __mem=<optimized out>) at /usr/include/c++/12/ext/atomicity.h:111
#17 std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_add_ref_copy (this=<optimized out>) at /usr/include/c++/12/bits/shared_ptr_base.h:152
#18 std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count (__r=..., this=0x7f21aa65de48) at /usr/include/c++/12/bits/shared_ptr_base.h:1078
#19 std::__shared_ptr<folly::RequestContext, (__gnu_cxx::_Lock_policy)2>::__shared_ptr (this=0x7f21aa65de40) at /usr/include/c++/12/bits/shared_ptr_base.h:1522
#20 std::shared_ptr<folly::RequestContext>::shared_ptr (this=0x7f21aa65de40) at /usr/include/c++/12/bits/shared_ptr.h:204
#21 folly::RequestContext::saveContext () at /root/.conan/data/folly/2023.10.30.08/milvus/dev/package/71e52ec7e6bdcb39e8f12e598f0e25527e54965c/include/folly/io/async/Request.h:290
#22 folly::futures::detail::FutureBase<folly::Unit>::setCallback_<folly::futures::detail::FutureBase<folly::Unit>::thenImplementation<folly::Future<folly::Unit>::thenTry<knowhere::ThreadPool::push<knowhere::IvfIndexNode<float, faiss::IndexIVFFlatCC>::Add(std::shared_ptr<knowhere::DataSet>, knowhere::Config const&)::{lambda()#1}>(knowhere::IvfIndexNode<float, faiss::IndexIVFFlatCC>::Add(std::shared_ptr<knowhere::DataSet>, knowhere::Config const&)::{lambda()#1}&&)::{lambda(auto:1&&)#1}>(knowhere::IvfIndexNode<float, faiss::IndexIVFFlatCC>::Add(std::shared_ptr<knowhere::DataSet>, knowhere::Config const&)::{lambda()#1}&&) &&::{lambda(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&)#1}, folly::futures::detail::tryExecutorCallableResult<folly::Unit, folly::Future<folly::Unit>::thenTry<knowhere::ThreadPool::push<knowhere::IvfIndexNode<float, faiss::IndexIVFFlatCC>::Add(std::shared_ptr<knowhere::DataSet>, knowhere::Config const&)::{lambda()#1}>(knowhere::IvfIndexNode<float, faiss::IndexIVFFlatCC>::Add(std::shared_ptr<knowhere::DataSet>, knowhere::Config const&)::{lambda()#1}&&)::{lambda(auto:1&&)#1}>(knowhere::IvfIndexNode<float, faiss::IndexIVFFlatCC>::Add(std::shared_ptr<knowhere::DataSet>, knowhere::Config const&)::{lambda()#1}&&) &&::{lambda(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&)#1}, void> >(knowhere::IvfIndexNode<float, faiss::IndexIVFFlatCC>::Add(std::shared_ptr<knowhere::DataSet>, knowhere::Config const&)::{lambda()#1}&&, folly::futures::detail::tryExecutorCallableResult<folly::Unit, folly::Future<folly::Unit>::thenTry<knowhere::ThreadPool::push<knowhere::IvfIndexNode<float, faiss::IndexIVFFlatCC>::Add(std::shared_ptr<knowhere::DataSet>, knowhere::Config const&)::{lambda()#1}>(knowhere::IvfIndexNode<float, faiss::IndexIVFFlatCC>::Add(std::shared_ptr<knowhere::DataSet>, knowhere::Config const&)::{lambda()#1}&&)::{lambda(auto:1&&)#1}>(knowhere::IvfIndexNode<float, faiss::IndexIVFFlatCC>::Add(std::shared_ptr<knowhere::DataSet>, knowhere::Config const--Type

### Steps To Reproduce

```markdown
fouramf-gv6n6-88-5963-milvus-standalone-7b7d6578fb-tp46z 

https://argo-workflows.zilliz.cc/workflows/qa/fouramf-4xjwm?tab=workflow&nodeId=fouramf-4xjwm-1911938006&nodePanelView=inputs-outputs 

https://grafana-4am.zilliz.cc/explore?panes=%7B%22_0r%22:%7B%22datasource%22:%22vhI6Vw67k%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bpod%3D~%5C%22fouramf-4xjwm-1911938006%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22vhI6Vw67k%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

same test as: #34778
different error with different image
```

**Comment by zhagnlu** [comment]
@foxspy help Investigating it
