### ISSUE TITLE
[Bug]: pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=unrecoverable error)>

### ISSUE THREAD

**Issue by jzyKevin** [milvus-io/milvus#35407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.5
- Deployment mode(standalone or cluster): Milvus Lite (standalone?)
- MQ type(rocksmq, pulsar or kafka): rocksmq 
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus, Version: 2.3.7
- OS(Ubuntu or CentOS): Ubuntu 20.04.2 LTS
- CPU/Memory: Intel(R) Xeon(R) Silver 4116 CPU @ 2.10GHz
- GPU: RTX 3090, CUDA Version: 12.1
```

### Current Behavior

I have already stored vectors in a Milvus collection using Milvus lite. Currently, I need to use it for querying, and I am able to query the number of entities in the collection. However, when I try to perform similarity retrieval using vectors, an error occurs while loading the collection into memory, as detailed in the log. Note: I have previously used Milvus standalone for deployment, but switched to Milvus lite due to frequent issues with Docker containers, and I'm not sure if this has any impact.

**Log:**
RPC error: [load_collection], <MilvusException: (code=65535, message=unrecoverable error)>, <Time:{'RPC start': '2024-08-10 12:24:16.208957', 'RPC error': '2024-08-10 12:24:58.848696'}>
Traceback (most recent call last):
  File "milvus_query.py", line 30, in <module>
    collection.load()
  File "/home/jinzhouyang/miniconda/envs/db/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 419, in load
    conn.load_collection(
  File "/home/jinzhouyang/miniconda/envs/db/lib/python3.8/site-packages/pymilvus/decorators.py", line 140, in handler
    raise e from e
  File "/home/jinzhouyang/miniconda/envs/db/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
    return func(*args, **kwargs)
  File "/home/jinzhouyang/miniconda/envs/db/lib/python3.8/site-packages/pymilvus/decorators.py", line 175, in handler
    return func(self, *args, **kwargs)
  File "/home/jinzhouyang/miniconda/envs/db/lib/python3.8/site-packages/pymilvus/decorators.py", line 115, in handler
    raise e from e
  File "/home/jinzhouyang/miniconda/envs/db/lib/python3.8/site-packages/pymilvus/decorators.py", line 86, in handler
    return func(*args, **kwargs)
  File "/home/jinzhouyang/miniconda/envs/db/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 1046, in load_collection
    check_status(response)
  File "/home/jinzhouyang/miniconda/envs/db/lib/python3.8/site-packages/pymilvus/client/utils.py", line 54, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=unrecoverable error)>

**Comment by xiaofan-luan** [comment]
1. please offer full log for investigate.
2. we don't believe milvus lite can be used in production, but for test both should work
3. it would be great if you can share your current log to test

**Comment by yanliang567** [comment]
@jzyKevin Besides, please also share the code snippet to reproduce the issue.  
/assign @jzyKevin 
/unassign
