### ISSUE TITLE
[Bug]: odr-violation is reported when enabling ASAN in milvus

### ISSUE THREAD

**Issue by chyezh** [milvus-io/milvus#35549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-c42976ee6ff4cb28ed42c0837be6e34cc5299151
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
==821477==ERROR: AddressSanitizer: odr-violation (0x76f874049240):
  [1] size=4 'init_knowhere_once_' /home/chyezh/repository/chyezh/milvus/internal/core/src/config/ConfigKnowhere.cpp:28:16
  [2] size=4 'init_knowhere_once_' /home/chyezh/repository/chyezh/milvus/internal/core/src/config/ConfigKnowhere.cpp:28:16
These globals were registered at these points:
  [1]:
    #0 0x76f878261928 in __asan_register_globals ../../../../src/libsanitizer/asan/asan_globals.cpp:341
    #1 0x76f873549a08 in _sub_I_00099_1 (/home/chyezh/repository/chyezh/milvus/internal/core/output/lib/libmilvus_segcore.so+0x2a6ea08)
    #2 0x76f878c2e47d in call_init elf/dl-init.c:70

  [2]:
    #0 0x76f878261928 in __asan_register_globals ../../../../src/libsanitizer/asan/asan_globals.cpp:341
    #1 0x76f86ea1e62a in _sub_I_00099_1 (/home/chyezh/repository/chyezh/milvus/internal/core/output/lib/libmilvus_indexbuilder.so+0x24e62a)
    #2 0x76f878c2e47d in call_init elf/dl-init.c:70

==821477==HINT: if you don't care about these errors you may set ASAN_OPTIONS=detect_odr_violation=0
SUMMARY: AddressSanitizer: odr-violation: global 'init_knowhere_once_' at /home/chyezh/repository/chyezh/milvus/internal/core/src/config/ConfigKnowhere.cpp:28:16
==821477==ABORTING
```

### Expected Behavior

A static variable should not be linked twice.

### Steps To Reproduce

```markdown
1. Enable ASAN in milvus and run it.
```

**Comment by PwzXxm** [comment]
I'm looking into tracing init fails at Ubuntu 20.04 and found several places including this as well. Good catch!

**Comment by chyezh** [comment]
Fixed
