### ISSUE TITLE
[Bug]: `TestWAL` may panic due to channel double close

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#35762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 56b3490
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

`TestWAL` may panic due to channel double close

### Expected Behavior

Double close shall be prevented

### Milvus Log

```
2024-08-28T04:43:56.7777570Z [2024/08/28 04:43:52.854 +00:00] [WARN] [timetick/timetick_interceptor.go:109] ["timeTickAppendInterceptor is closing"]
2024-08-28T04:43:56.7777686Z panic: close of closed channel
2024-08-28T04:43:56.7777693Z 
2024-08-28T04:43:56.7777789Z goroutine 1195 [running]:
2024-08-28T04:43:56.7778469Z github.com/milvus-io/milvus/internal/streamingnode/server/wal/interceptors/txn.(*TxnManager).CleanupTxnUntil(0xc001ffaa50, 0x788d78?)
2024-08-28T04:43:56.7779013Z 	/go/src/github.com/milvus-io/milvus/internal/streamingnode/server/wal/interceptors/txn/txn_manager.go:78 +0x2e5
2024-08-28T04:43:56.7780008Z github.com/milvus-io/milvus/internal/streamingnode/server/wal/interceptors/timetick.(*timeTickAppendInterceptor).DoAppend(0xc001ca6560, {0x3dbe6d0, 0xc001a20330}, {0x3df8468, 0xc00114acc0}, 0x36af6a0?)
2024-08-28T04:43:56.7780725Z 	/go/src/github.com/milvus-io/milvus/internal/streamingnode/server/wal/interceptors/timetick/timetick_interceptor.go:81 +0x73d
2024-08-28T04:43:56.7781802Z github.com/milvus-io/milvus/internal/streamingnode/server/wal/interceptors.NewChainedInterceptor.chainAppendInterceptors.func2({0x3dbe6d0, 0xc001a20330}, {0x3df8468, 0xc00114acc0}, 0xc000df8090?)
2024-08-28T04:43:56.7782350Z 	/go/src/github.com/milvus-io/milvus/internal/streamingnode/server/wal/interceptors/chain_interceptor.go:79 +0xd1
2024-08-28T04:43:56.7783249Z github.com/milvus-io/milvus/internal/streamingnode/server/wal/interceptors.(*chainedInterceptor).DoAppend(0xc0039837d0, {0x3dbe6d0, 0xc001a20330}, {0x3df8468, 0xc00114acc0}, 0xc000bd6f00?)
2024-08-28T04:43:56.7783858Z 	/go/src/github.com/milvus-io/milvus/internal/streamingnode/server/wal/interceptors/chain_interceptor.go:57 +0xc8
2024-08-28T04:43:56.7784623Z github.com/milvus-io/milvus/internal/streamingnode/server/wal/adaptor.(*walAdaptorImpl).Append(0xc0035dde80, {0x3dbe6d0, 0xc001bebda0}, {0x3df8468, 0xc00114acc0})
2024-08-28T04:43:56.7785187Z 	/go/src/github.com/milvus-io/milvus/internal/streamingnode/server/wal/adaptor/wal_adaptor.go:94 +0x507
2024-08-28T04:43:56.7786031Z github.com/milvus-io/milvus/internal/streamingnode/server/wal/interceptors/timetick.(*timeTickSyncOperator).Sync.func1({0x3dbe6d0, 0xc001bebda0}, {0x3df8468, 0xc00114acc0})
2024-08-28T04:43:56.7786670Z 	/go/src/github.com/milvus-io/milvus/internal/streamingnode/server/wal/interceptors/timetick/timetick_sync_operator.go:77 +0x86
2024-08-28T04:43:56.7787631Z github.com/milvus-io/milvus/internal/streamingnode/server/wal/interceptors/timetick.(*timeTickSyncOperator).sendNoPersistentTsMsg(0xc0035dde00, {0x3dbe708, 0xc001575d10}, 0xc00130fbb0?, 0xc00130fc50)
2024-08-28T04:43:56.7788278Z 	/go/src/github.com/milvus-io/milvus/internal/streamingnode/server/wal/interceptors/timetick/timetick_sync_operator.go:249 +0x2a2
2024-08-28T04:43:56.7789070Z github.com/milvus-io/milvus/internal/streamingnode/server/wal/interceptors/timetick.(*timeTickSyncOperator).sendTsMsg(0xc0035dde00, {0x3dbe708, 0xc001575d10}, 0x0?)
2024-08-28T04:43:56.7789714Z 	/go/src/github.com/milvus-io/milvus/internal/streamingnode/server/wal/interceptors/timetick/timetick_sync_operator.go:197 +0x4d0
2024-08-28T04:43:56.7790473Z github.com/milvus-io/milvus/internal/streamingnode/server/wal/interceptors/timetick.(*timeTickSyncOperator).Sync(0xc0035dde00, {0x3dbe708, 0xc001575d10})
2024-08-28T04:43:56.7791110Z 	/go/src/github.com/milvus-io/milvus/internal/streamingnode/server/wal/interceptors/timetick/timetick_sync_operator.go:76 +0x1d1
2024-08-28T04:43:56.7792072Z github.com/milvus-io/milvus/internal/streamingnode/server/wal/interceptors/timetick/inspector.(*timeTickSyncInspectorImpl).background.func1({0x4bc745?, 0xc0014d9338?}, {0x3dad590, 0xc0035dde00})
2024-08-28T04:43:56.7792673Z 	/go/src/github.com/milvus-io/milvus/internal/streamingnode/server/wal/interceptors/timetick/inspector/impls.go:75 +0x84
2024-08-28T04:43:56.7793149Z github.com/milvus-io/milvus/pkg/util/typeutil.(*ConcurrentMap[...]).Range.func1({0x37a7460?, 0xc0035dde00})
2024-08-28T04:43:56.7793442Z 	/go/src/github.com/milvus-io/milvus/pkg/util/typeutil/map.go:54 +0xf5
2024-08-28T04:43:56.7793577Z sync.(*Map).Range(0xc0012d1770, 0xc00130fe48)
2024-08-28T04:43:56.7793694Z 	/usr/local/go/src/sync/map.go:476 +0x1dc
2024-08-28T04:43:56.7794133Z github.com/milvus-io/milvus/pkg/util/typeutil.(*ConcurrentMap[...]).Range(0x3e10fc0, 0xc00130ff50)
2024-08-28T04:43:56.7794412Z 	/go/src/github.com/milvus-io/milvus/pkg/util/typeutil/map.go:51 +0xda
2024-08-28T04:43:56.7795181Z github.com/milvus-io/milvus/internal/streamingnode/server/wal/interceptors/timetick/inspector.(*timeTickSyncInspectorImpl).background(0xc0008f35c0)
2024-08-28T04:43:56.7795779Z 	/go/src/github.com/milvus-io/milvus/internal/streamingnode/server/wal/interceptors/timetick/inspector/impls.go:74 +0x388
2024-08-28T04:43:56.7796537Z created by github.com/milvus-io/milvus/internal/streamingnode/server/wal/interceptors/timetick/inspector.NewTimeTickSyncInspector in goroutine 1193
2024-08-28T04:43:56.7797186Z 	/go/src/github.com/milvus-io/milvus/internal/streamingnode/server/wal/interceptors/timetick/inspector/impls.go:22 +0x3a7
```

**Comment by congqixia** [comment]
https://github.com/milvus-io/milvus/actions/runs/10589466321/job/29344854162
