### ISSUE TITLE
[Bug]: Timeout occurs when create a GPU index after create an index and delete it

### ISSUE THREAD

**Issue by qwevdb** [milvus-io/milvus#35841]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvus v2.4.5-gpu
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.4.5
- OS(Ubuntu or CentOS): Ubuntu 24.04 LTS
- CPU/Memory: Intel Core i7-8700K / 48G
- GPU: NVIDIA GeForce RTX 1080Ti
- Others:
```

### Current Behavior

Timeout  occurs when creating a GPU index in the collection after creating and then deleting an index in the same collection.

### Expected Behavior

Run normally and produce accurate results.

### Steps To Reproduce

1. create an index in the collection
2. search
2. delete this index
3. create a GPU index in the same collection
4. search
5. timeout occurs

```python
from pymilvus import Collection, connections, FieldSchema, CollectionSchema, DataType
import numpy as np

np.random.seed(0)
connections.connect(
    alias="bench",
    host="localhost",
    port="19530"
)
collection_name = "Benchmark"
dim = 2
idx = FieldSchema(
    name="id",
    dtype=DataType.INT64,
    is_primary=True,
)
vector = FieldSchema(
    name="vector",
    dtype=DataType.FLOAT_VECTOR,
    dim=dim,
)
fields = [idx, vector]
schema = CollectionSchema(fields=fields, description="Benchmark")
collection = Collection(
    name=collection_name,
    schema=schema,
    using="bench",
)

datas = []
number = 1024 
limit = 5
for i in range(number):
    data = {'id': i,
            'vector': np.random.rand(dim).tolist()}
    datas.append(data)
collection.insert(datas)
index_params1 = {
    "index_type": "IVF_FLAT",
    "params": {"nlist": 128},
    "metric_type": "L2"
}
index_params2 = {
    "index_type": "GPU_IVF_FLAT",
    "params": {"nlist": 128},
    "metric_type": "L2"
}
collection.create_index("vector", index_params1, timeout=100)
collection.flush()
collection.load()

query_vector = np.random.rand(dim).tolist()
res1 = collection.search(
    data=[query_vector],
    anns_field="vector",
    param={"metric_type": "L2",
           "params": {"nprobe": 10}},
    limit = limit
)
collection.release()
collection.drop_index()
collection.flush()
print(res1)

collection.create_index("vector", index_params2, timeout=100)  
# timeout
collection.flush()
collection.load()

res2 = collection.search(
    data=[query_vector],
    anns_field="vector",
    param={"metric_type": "L2",
           "params": {"nprobe": 10}},
    limit = limit
)
print(res2)
collection.drop()
```
Result：
``` bash
data: ["['id: 275, distance: 0.000675233721267432, entity: {}', 'id: 823, distance: 0.0009240064537152648, entity: {}', 'id: 172, distance: 0.0009869951754808426, entity: {}', 'id: 497, distance: 0.0012439348502084613, entity: {}', 'id: 824, distance: 0.0015659565106034279, entity: {}']"]
Retry timeout: 100s
RPC error: [wait_for_creating_index], <MilvusException: (code=1, message=Retry timeout: 100s, message=collection Benchmark create index  timeout in 100s)>, <Time:{'RPC start': '2024-08-27 21:16:58.125073', 'RPC error': '2024-08-27 21:18:38.600050'}>
Retry timeout: 100s
RPC error: [create_index], <MilvusException: (code=1, message=Retry timeout: 100s, message=Retry timeout: 100s, message=collection Benchmark create index  timeout in 100s)>, <Time:{'RPC start': '2024-08-27 21:16:58.111692', 'RPC error': '2024-08-27 21:18:38.600509'}>
Traceback (most recent call last):
  File "/home/xxx/mlivus/dev3/milvus_test3.py", line 66, in <module>
    collection.create_index("vector", index_params2, timeout=100)
  File "/home/xxx/anaconda3/envs/milvus/lib/python3.10/site-packages/pymilvus/orm/collection.py", line 1373, in create_index
    return conn.create_index(self._name, field_name, index_params, timeout=timeout, **kwargs)
  File "/home/xxx/anaconda3/envs/milvus/lib/python3.10/site-packages/pymilvus/decorators.py", line 148, in handler
    raise e from e
  File "/home/xxx/anaconda3/envs/milvus/lib/python3.10/site-packages/pymilvus/decorators.py", line 144, in handler
    return func(*args, **kwargs)
  File "/home/xxx/anaconda3/envs/milvus/lib/python3.10/site-packages/pymilvus/decorators.py", line 183, in handler
    return func(self, *args, **kwargs)
  File "/home/xxx/anaconda3/envs/milvus/lib/python3.10/site-packages/pymilvus/decorators.py", line 108, in handler
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 100s, message=Retry timeout: 100s, message=collection Benchmark create index  timeout in 100s)>
```

### Anything else?

I encountered the aforementioned issues exclusively on the NVIDIA GeForce RTX 1080Ti GPU, whereas the RTX 4090 GPU yielded results without any errors.

**Comment by yanliang567** [comment]
@qwevdb please offer milvus logs, For Milvus installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs.
/assign @qwevdb 
/unassign

**Comment by yanliang567** [comment]
/assign @Presburger 
please help to take a look

**Comment by Presburger** [comment]
@qwevdb Hi, Thank you for trying the Milvus GPU version, The computational capability of the 1080 Ti graphics card is below 7.0. Currently, the latest version of Milvus GPU supports compute capabilities of 7.0, 7.5, 8.0, 8.6, and 9.0.
