### ISSUE TITLE
[Bug]: Flush timeout after Milvus recovered from minio pod failure chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#35895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20240901-407fc933-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka): pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2024-09-01T10:06:21.943Z] <name>: Checker__8ADsIeDY

[2024-09-01T10:06:21.943Z] <description>: 

[2024-09-01T10:06:21.943Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}......  (api_request.py:37)

[2024-09-01T10:06:21.943Z] [2024-09-01 10:01:49 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-09-01T10:06:21.943Z] [2024-09-01 10:04:49 - WARNING - pymilvus.decorators]: Retry timeout: 180s (decorators.py:106)

[2024-09-01T10:06:21.943Z] [2024-09-01 10:04:49 - ERROR - pymilvus.decorators]: RPC error: [flush], <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for flush timeout, collection: Checker__8ADsIeDY, flusht_ts: 452246872916230147)>, <Time:{'RPC start': '2024-09-01 10:01:49.451424', 'RPC error': '2024-09-01 10:04:49.696887'}> (decorators.py:140)

[2024-09-01T10:06:21.943Z] [2024-09-01 10:04:49 - ERROR - ci_test]: Traceback (most recent call last):

[2024-09-01T10:06:21.943Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2024-09-01T10:06:21.943Z]     res = func(*args, **_kwargs)

[2024-09-01T10:06:21.943Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2024-09-01T10:06:21.943Z]     return func(*arg, **kwargs)

[2024-09-01T10:06:21.943Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 318, in flush

[2024-09-01T10:06:21.943Z]     conn.flush([self.name], timeout=timeout, **kwargs)

[2024-09-01T10:06:21.943Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 141, in handler

[2024-09-01T10:06:21.943Z]     raise e from e

[2024-09-01T10:06:21.943Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 137, in handler

[2024-09-01T10:06:21.943Z]     return func(*args, **kwargs)

[2024-09-01T10:06:21.943Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 176, in handler

[2024-09-01T10:06:21.943Z]     return func(self, *args, **kwargs)

[2024-09-01T10:06:21.943Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 107, in handler

[2024-09-01T10:06:21.943Z]     raise MilvusException(

[2024-09-01T10:06:21.943Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for flush timeout, collection: Checker__8ADsIeDY, flusht_ts: 452246872916230147)>

[2024-09-01T10:06:21.943Z]  (api_request.py:45)

[2024-09-01T10:06:21.943Z] [2024-09-01 10:04:49 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for flush timeout, collection: Checker__8ADsIeDY, flusht_ts: 452246872916230147)> (api_request.py:46)
```

### Milvus Log

failed job:  https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/17624/pipeline

log:
[artifacts-s3-pod-failure-17624-server-logs.tar.gz](https://github.com/user-attachments/files/16831996/artifacts-s3-pod-failure-17624-server-logs.tar.gz)

cluster: 4am
ns: chaos-testing
pod info
```

[2024-09-01T10:01:22.636Z] + kubectl get pods -o wide

[2024-09-01T10:01:22.637Z] + grep s3-pod-failure-17624

[2024-09-01T10:01:22.892Z] s3-pod-failure-17624-etcd-0                                       1/1     Running                  0                  31m     10.104.27.105   4am-node31   <none>           <none>

[2024-09-01T10:01:22.892Z] s3-pod-failure-17624-etcd-1                                       1/1     Running                  0                  31m     10.104.17.34    4am-node23   <none>           <none>

[2024-09-01T10:01:22.892Z] s3-pod-failure-17624-etcd-2                                       1/1     Running                  0                  31m     10.104.24.4     4am-node29   <none>           <none>

[2024-09-01T10:01:22.892Z] s3-pod-failure-17624-milvus-datanode-5495d4c7b4-5w4lq             1/1     Running                  3 (30m ago)        31m     10.104.6.187    4am-node13   <none>           <none>

[2024-09-01T10:01:22.892Z] s3-pod-failure-17624-milvus-datanode-5495d4c7b4-l97j8             1/1     Running                  3 (30m ago)        31m     10.104.5.221    4am-node12   <none>           <none>

[2024-09-01T10:01:22.892Z] s3-pod-failure-17624-milvus-indexnode-78fb5d6bdc-4tttz            1/1     Running                  3 (30m ago)        31m     10.104.16.210   4am-node21   <none>           <none>

[2024-09-01T10:01:22.892Z] s3-pod-failure-17624-milvus-indexnode-78fb5d6bdc-7w8kf            1/1     Running                  3 (30m ago)        31m     10.104.33.121   4am-node36   <none>           <none>

[2024-09-01T10:01:22.892Z] s3-pod-failure-17624-milvus-indexnode-78fb5d6bdc-ntdgg            1/1     Running                  4 (30m ago)        31m     10.104.34.246   4am-node37   <none>           <none>

[2024-09-01T10:01:22.892Z] s3-pod-failure-17624-milvus-mixcoord-97c6cc89c-bfpnr              1/1     Running                  4 (30m ago)        31m     10.104.34.249   4am-node37   <none>           <none>

[2024-09-01T10:01:22.892Z] s3-pod-failure-17624-milvus-proxy-b48659c4f-lsxz6                 1/1     Running                  3 (30m ago)        31m     10.104.34.245   4am-node37   <none>           <none>

[2024-09-01T10:01:22.892Z] s3-pod-failure-17624-milvus-querynode-845fbbdc89-ll8zp            1/1     Running                  3 (30m ago)        31m     10.104.23.99    4am-node27   <none>           <none>

[2024-09-01T10:01:22.892Z] s3-pod-failure-17624-milvus-querynode-845fbbdc89-lzmbn            1/1     Running                  3 (30m ago)        31m     10.104.9.179    4am-node14   <none>           <none>

[2024-09-01T10:01:22.892Z] s3-pod-failure-17624-milvus-querynode-845fbbdc89-sdvmh            1/1     Running                  3 (30m ago)        31m     10.104.32.237   4am-node39   <none>           <none>

[2024-09-01T10:01:22.892Z] s3-pod-failure-17624-minio-0                                      1/1     Running                  8 (9m12s ago)      31m     10.104.21.39    4am-node24   <none>           <none>

[2024-09-01T10:01:22.892Z] s3-pod-failure-17624-minio-1                                      1/1     Running                  8 (9m37s ago)      31m     10.104.24.5     4am-node29   <none>           <none>

[2024-09-01T10:01:22.892Z] s3-pod-failure-17624-minio-2                                      1/1     Running                  8 (9m2s ago)       31m     10.104.27.108   4am-node31   <none>           <none>

[2024-09-01T10:01:22.892Z] s3-pod-failure-17624-minio-3                                      1/1     Running                  8 (9m18s ago)      31m     10.104.17.37    4am-node23   <none>           <none>

[2024-09-01T10:01:22.892Z] s3-pod-failure-17624-pulsar-bookie-0                              1/1     Running                  0                  31m     10.104.27.106   4am-node31   <none>           <none>

[2024-09-01T10:01:22.892Z] s3-pod-failure-17624-pulsar-bookie-1                              1/1     Running                  0                  31m     10.104.17.35    4am-node23   <none>           <none>

[2024-09-01T10:01:22.892Z] s3-pod-failure-17624-pulsar-bookie-init-4h4f9                     0/1     Completed                0                  31m     10.104.24.230   4am-node29   <none>           <none>

[2024-09-01T10:01:22.892Z] s3-pod-failure-17624-pulsar-broker-0                              1/1     Running                  0                  31m     10.104.24.225   4am-node29   <none>           <none>

[2024-09-01T10:01:22.892Z] s3-pod-failure-17624-pulsar-proxy-0                               1/1     Running                  0                  31m     10.104.24.229   4am-node29   <none>           <none>

[2024-09-01T10:01:22.892Z] s3-pod-failure-17624-pulsar-pulsar-init-67j56                     0/1     Completed                0                  31m     10.104.24.227   4am-node29   <none>           <none>

[2024-09-01T10:01:22.892Z] s3-pod-failure-17624-pulsar-recovery-0                            1/1     Running                  0                  31m     10.104.21.28    4am-node24   <none>           <none>

[2024-09-01T10:01:22.892Z] s3-pod-failure-17624-pulsar-zookeeper-0                           1/1     Running                  0                  31m     10.104.17.32    4am-node23   <none>           <none>
```

**Comment by zhuwenxing** [comment]
/assign @XuanYang-cn 
PTAL

**Comment by bigsheeper** [comment]
/assign
Maybe relate to the streaming node. Let me help take a look at this issue together.

**Comment by zhuwenxing** [comment]
> /assign Maybe relate to the streaming node. Let me help take a look at this issue together.

But currently, the streaming node is not enabled in this test.

**Comment by bigsheeper** [comment]
> > /assign Maybe relate to the streaming node. Let me help take a look at this issue together.
> 
> But currently, the streaming node is not enabled in this test.

Ok.

**Comment by bigsheeper** [comment]
Datanode consumed tt lag is quite high:
![image](https://github.com/user-attachments/assets/105410dc-06da-4d2a-99a5-f27f1bbc44b1)

**Comment by bigsheeper** [comment]
Cannot flush segment `452246403116995760` because it cannot be found in the metacache:
![image](https://github.com/user-attachments/assets/5404d65a-0acc-4462-a4d0-62dbeff16043)

**Comment by bigsheeper** [comment]
### Issue Analysis
1. Segment `452246403116995760` was sealed and flushed, but an insert message [1] was still received afterward: This is the core issue that needs further investigation.
2. From Datacoord's perspective, this segment was already flushed and ready for compaction. So, it triggered a compaction and notified Datanode to remove the segment from the metacache after compaction was done [2].
3. The `WriteBuffer` still has an insert buffer for this segment, but the metacache doesn’t have this segment, leading to sync failures [3].
4. Sync failure causes the channel checkpoint to stall at the insert buffer position [4].
5. The stalled channel checkpoint causes flush operation timeout [5].

### Some Speculations
Why did an insert message get received after the seal and flush were completed？
1. Timetick mechanism issue: Datacoord executed the seal and flush without waiting for the Datanode timetick.
2. Segment allocation mechanism issue: Proxy assigned inserts that exceeded the expire time.
3. Message stream issue: Possible message consumption disorder or duplication.
4. The message timestamp may have been abnormally modified.

### Next Steps for Investigation
Currently, the main suspicions are 3 and 4—a message stream issue or timestamp tampering. I'll add more logs in critical paths to further investigate.

### Key Logs
[1]
![image](https://github.com/user-attachments/assets/cf6fbdfe-d5c2-4776-ae34-de01c5dba9f3)
[2]
![image](https://github.com/user-attachments/assets/5471f3e2-691f-4bc8-8704-9deaa55f6ae2)
[3]
![image](https://github.com/user-attachments/assets/787938fb-4b20-41e5-89e8-1ecd3a77b57d)
[4]
![image](https://github.com/user-attachments/assets/ac011a07-8584-4a5f-b180-b664f8a4c43b)
[5]
![image](https://github.com/user-attachments/assets/a7f9d2ae-15c1-4ed5-9274-8f68e21677a6)

**Comment by zhuwenxing** [comment]
also not reproduced in nightly anymore
