### ISSUE TITLE
[Bug]: [null & default] Querynode is crashed when query relatively large amount of entities back with the nullable fields as output_fields

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#36005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20240904-a32f337e
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):    all
- SDK version(e.g. pymilvus v2.0.0rc2): 2.5.0rc74
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Querynode is crashed when query relatively large amount of entities （10000） back with the nullable fields as output_fields

query returns error:
```
RPC error: [query], <MilvusException: (code=901, message=stack trace: /workspace/source/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace
/workspace/source/internal/util/grpcclient/client.go:559 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call
/workspace/source/internal/util/grpcclient/client.go:573 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall
/workspace/source/internal/distributed/querynode/client/client.go:90 github.com/milvus-io/milvus/internal/distributed/querynode/client.wrapGrpcCall[...]
/workspace/source/internal/distributed/querynode/client/client.go:215 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Query
/workspace/source/internal/proxy/task_query.go:553 github.com/milvus-io/milvus/internal/proxy.(*queryTask).queryShard
/workspace/source/internal/proxy/lb_policy.go:180 github.com/milvus-io/milvus/internal/proxy.(*LBPolicyImpl).ExecuteWithRetry.func1
/workspace/source/pkg/util/retry/retry.go:44 github.com/milvus-io/milvus/pkg/util/retry.Do
/workspace/source/internal/proxy/lb_policy.go:154 github.com/milvus-io/milvus/internal/proxy.(*LBPolicyImpl).ExecuteWithRetry
/workspace/source/internal/proxy/lb_policy.go:218 github.com/milvus-io/milvus/internal/proxy.(*LBPolicyImpl).Execute.func2: node not found)>, <Time:{'RPC start': '2024-09-05 16:12:03.501493', 'RPC error': '2024-09-05 16:12:31.651054'}>
Traceback (most recent call last):
  File "./default_new.py", line 53, in <module>
    res = collection.query("int64>=0", output_fields=["nullableFid"])
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 1082, in query
    return conn.query(
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 141, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 137, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 176, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 116, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 86, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 1536, in query
    check_status(response.status)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/utils.py", line 63, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=901, message=stack trace: /workspace/source/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace
/workspace/source/internal/util/grpcclient/client.go:559 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call
/workspace/source/internal/util/grpcclient/client.go:573 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall
/workspace/source/internal/distributed/querynode/client/client.go:90 github.com/milvus-io/milvus/internal/distributed/querynode/client.wrapGrpcCall[...]
/workspace/source/internal/distributed/querynode/client/client.go:215 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Query
/workspace/source/internal/proxy/task_query.go:553 github.com/milvus-io/milvus/internal/proxy.(*queryTask).queryShard
/workspace/source/internal/proxy/lb_policy.go:180 github.com/milvus-io/milvus/internal/proxy.(*LBPolicyImpl).ExecuteWithRetry.func1
/workspace/source/pkg/util/retry/retry.go:44 github.com/milvus-io/milvus/pkg/util/retry.Do
/workspace/source/internal/proxy/lb_policy.go:154 github.com/milvus-io/milvus/internal/proxy.(*LBPolicyImpl).ExecuteWithRetry
/workspace/source/internal/proxy/lb_policy.go:218 github.com/milvus-io/milvus/internal/proxy.(*LBPolicyImpl).Execute.func2: node not found)>
```

And querynode is crashed:
```
default-null-test-edxnm-milvus-querynode-d68cddb57-m6qmv        0/1     Running                           8 (103s ago)     29h
```

### Expected Behavior

No crash and query successfully

### Steps To Reproduce

```python
from pymilvus import CollectionSchema, FieldSchema
from pymilvus import Collection
from pymilvus import connections
from pymilvus import DataType
from pymilvus import Partition
from pymilvus import utility
import json
import random

connections.connect()

dim = 128
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
double_field = FieldSchema(name="nullableFid", dtype=DataType.DOUBLE, nullable=True, is_primary=False, mmap_enabled=False)
int32_field = FieldSchema(name="int32", dtype=DataType.INT64, default_value=10)
string_field = FieldSchema(name="string", dtype=DataType.VARCHAR, max_length=1000, default_value="10")
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim, mmap_enabled=False)
schema = CollectionSchema(fields=[int64_field, double_field, int32_field, string_field, float_vector], enable_dynamic_field=False)
utility.drop_collection("test")
collection = Collection("test", schema=schema)
res = collection.schema
print(res)

#index = {"index_type": "DISKANN", "metric_type": "L2", "params": {}}
index = {"index_type": "IVF_FLAT", "metric_type": "COSINE", "params": {"nlist":100}}

nb = 10000
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]

data = [[i for i in range(nb)], [None for _ in range(nb)],[None for _ in range(nb)], [], vectors]
#data = [[i for i in range(nb)], [i*1.0 for i in range(nb)],[None for _ in range(nb)], [], vectors]
#  equals to data1 = [[1,2], [None,None],[None,None], vectors]
data1 = [[i for i in range(nb)], [],[],[], vectors]

collection.insert(data=data)
#collection.upsert(data=data1)
collection.create_index("float_vector", index, index_name="index_name_1")
collection.load()
collection.flush()
res = collection.num_entities
print(res)
default_search_params = {"metric_type": "COSINE", "params": {"nprobe": 20}}
limit = 10
nq = 1
import time
start = time.time()
res1 = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0", output_fields=["nullableFid", "int32", "string"])
end = time.time() - start
print(res1)
print("search successfully in %f s" % end)
start = time.time()
#res = collection.query("int64>=0", output_fields=["nullableFid","int32", "string"])
res = collection.query("int64>=0", output_fields=["nullableFid"])
end = time.time() - start
print(res)
print("query successfully in %f s" % end)
```

### Milvus Log

https://grafana-4am.zilliz.cc/explore?orgId=1&panes=%7B%22lnY%22:%7B%22datasource%22:%22vhI6Vw67k%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcluster%3D%5C%22devops%5C%22,namespace%3D%5C%22chaos-testing%5C%22,pod%3D~%5C%22default-null-test-edxnm.%2A%5C%22%7D%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22vhI6Vw67k%22%7D%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1

### Anything else?

1. if no nullable fields with "None", no this issue, and query with output_fields returns successfully:
```
10000
data: ['["id: 0, distance: 1.0, entity: {\'nullableFid\': None, \'int32\': 10, \'string\': \'10\'}", "id: 5327, distance: 0.8516730666160583, entity: {\'nullableFid\': None, \'int32\': 10, \'string\': \'10\'}", "id: 4225, distance: 0.848824679851532, entity: {\'nullableFid\': None, \'int32\': 10, \'string\': \'10\'}", "id: 9496, distance: 0.8330777287483215, entity: {\'nullableFid\': None, \'int32\': 10, \'string\': \'10\'}", "id: 668, distance: 0.8307722210884094, entity: {\'nullableFid\': None, \'int32\': 10, \'string\': \'10\'}", "id: 8027, distance: 0.8300902247428894, entity: {\'nullableFid\': None, \'int32\': 10, \'string\': \'10\'}", "id: 5705, distance: 0.8270300626754761, entity: {\'nullableFid\': None, \'int32\': 10, \'string\': \'10\'}", "id: 9772, distance: 0.8257530927658081, entity: {\'nullableFid\': None, \'int32\': 10, \'string\': \'10\'}", "id: 8802, distance: 0.8253604769706726, entity: {\'nullableFid\': None, \'int32\': 10, \'string\': \'10\'}", "id: 4331, distance: 0.8250492215156555, entity: {\'nullableFid\': None, \'int32\': 10, \'string\': \'10\'}"]']
search successfully in 0.049774 s
data: ["{'int64': 0}", "{'int64': 1}", "{'int64': 2}", "{'int64': 3}", "{'int64': 4}", "{'int64': 5}", "{'int64': 6}", "{'int64': 7}", "{'int64': 8}", "{'int64': 9}"] ...
query successfully in 0.143015 s
```

2. if the data number is 1000, no this issue.

**Comment by smellthemoon** [comment]
https://github.com/milvus-io/milvus/pull/36027 merged, could you help to verify? @binbinlv

**Comment by binbinlv** [comment]
Verified and fixed.

pymilvus: 2.5.0rc78
milvus:master-20240908-208c8a23

results:
```
data: ['["id: 0, distance: 1.0, entity: {\'nullableFid\': None, \'int32\': 10, \'string\': \'10\'}", "id: 65609, distance: 0.8427157998085022, entity: {\'nullableFid\': None, \'int32\': 10, \'string\': \'10\'}", "id: 48048, distance: 0.841633677482605, entity: {\'nullableFid\': None, \'int32\': 10, \'string\': \'10\'}", "id: 28469, distance: 0.8404135704040527, entity: {\'nullableFid\': None, \'int32\': 10, \'string\': \'10\'}", "id: 21084, distance: 0.8393059968948364, entity: {\'nullableFid\': None, \'int32\': 10, \'string\': \'10\'}", "id: 75373, distance: 0.8377096652984619, entity: {\'nullableFid\': None, \'int32\': 10, \'string\': \'10\'}", "id: 74805, distance: 0.8375100493431091, entity: {\'nullableFid\': None, \'int32\': 10, \'string\': \'10\'}", "id: 12415, distance: 0.8372661471366882, entity: {\'nullableFid\': None, \'int32\': 10, \'string\': \'10\'}", "id: 68144, distance: 0.8360772728919983, entity: {\'nullableFid\': None, \'int32\': 10, \'string\': \'10\'}", "id: 70222, distance: 0.8335270285606384, entity: {\'nullableFid\': None, \'int32\': 10, \'string\': \'10\'}"]']
search successfully in 0.050025 s
data: ["{'nullableFid': None, 'int32': 10, 'string': '10', 'int64': 0}", "{'nullableFid': None, 'int32': 10, 'string': '10', 'int64': 1}", "{'nullableFid': None, 'int32': 10, 'string': '10', 'int64': 2}", "{'nullableFid': None, 'int32': 10, 'string': '10', 'int64': 3}", "{'nullableFid': None, 'int32': 10, 'string': '10', 'int64': 4}", "{'nullableFid': None, 'int32': 10, 'string': '10', 'int64': 5}", "{'nullableFid': None, 'int32': 10, 'string': '10', 'int64': 6}", "{'nullableFid': None, 'int32': 10, 'string': '10', 'int64': 7}", "{'nullableFid': None, 'int32': 10, 'string': '10', 'int64': 8}", "{'nullableFid': None, 'int32': 10, 'string': '10', 'int64': 9}"] ...
query successfully in 3.180171 s
```
