### ISSUE TITLE
[Bug]: Search and query failed with error `_MultiThreadedRendezvous: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded` when streaming node is enabled

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#36081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20240905-8593c458-amd64
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2024-09-05T08:49:41.924Z] [2024-09-05 08:46:19 - INFO - ci_test]: insert data for collection DeleteChecker__fVdJAAnH cost 5.536271631717682s (checker.py:403)
[2024-09-05T08:49:41.924Z] [2024-09-05 08:46:19 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)
[2024-09-05T08:49:41.924Z] [2024-09-05 08:46:21 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)
[2024-09-05T08:49:41.924Z] [2024-09-05 08:46:21 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['float_vector', {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}, 120], kwargs: {'index_name': ''} (api_request.py:62)
[2024-09-05T08:49:41.924Z] [2024-09-05 08:46:23 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 180], kwargs: {} (api_request.py:62)
[2024-09-05T08:49:41.924Z] [2024-09-05 08:46:23 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)
[2024-09-05T08:49:41.924Z] [2024-09-05 08:46:31 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [[[172552598729123, 172552598729229, 172552598729334, 172552598729440, 172552598729545, 172552598729651, 172552598729756, 172552598729862, 172552598729967, 172552598730073, 172552598730176, 172552598730281, 172552598730387, 172552598730493, 172552598730598, 172552598730704, 172552598730809, 17255259......, kwargs: {'timeout': 120} (api_request.py:62)
[2024-09-05T08:49:41.924Z] [2024-09-05 08:46:32 - DEBUG - ci_test]: (api_request)  : [Collection.query] args: ['int64 > 0', ['int64'], None, 180], kwargs: {'partition_name': '_default'} (api_request.py:62)
[2024-09-05T08:49:41.924Z] [2024-09-05 08:49:32 - ERROR - pymilvus.decorators]: grpc RpcError: [query], <_MultiThreadedRendezvous: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded>, <Time:{'RPC start': '2024-09-05 08:46:32.660011', 'gRPC error': '2024-09-05 08:49:32.661850'}> (decorators.py:151)
[2024-09-05T08:49:41.924Z] [2024-09-05 08:49:32 - ERROR - ci_test]: Traceback (most recent call last):
[2024-09-05T08:49:41.924Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper
[2024-09-05T08:49:41.924Z]     res = func(*args, **_kwargs)
[2024-09-05T08:49:41.924Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request
[2024-09-05T08:49:41.924Z]     return func(*arg, **kwargs)
[2024-09-05T08:49:41.924Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 1082, in query
[2024-09-05T08:49:41.924Z]     return conn.query(
[2024-09-05T08:49:41.924Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 155, in handler
[2024-09-05T08:49:41.924Z]     raise e from e
[2024-09-05T08:49:41.924Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 137, in handler
[2024-09-05T08:49:41.924Z]     return func(*args, **kwargs)
[2024-09-05T08:49:41.924Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 176, in handler
[2024-09-05T08:49:41.924Z]     return func(self, *args, **kwargs)
[2024-09-05T08:49:41.924Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 90, in handler
[2024-09-05T08:49:41.924Z]     raise e from e
[2024-09-05T08:49:41.924Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 86, in handler
[2024-09-05T08:49:41.924Z]     return func(*args, **kwargs)
[2024-09-05T08:49:41.924Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 1533, in query
[2024-09-05T08:49:41.924Z]     response = future.result()
[2024-09-05T08:49:41.924Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 881, in result
[2024-09-05T08:49:41.924Z]     raise self
[2024-09-05T08:49:41.924Z] grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
[2024-09-05T08:49:41.924Z] 	status = StatusCode.DEADLINE_EXCEEDED
[2024-09-05T08:49:41.924Z] 	details = "Deadline Exceeded"
[2024-09-05T08:49:41.924Z] 	debug_error_string = "UNKNOWN:Deadline Exceeded {grpc_status:4, created_time:"2024-09-05T08:49:32.660799001+00:00"}"
[2024-09-05T08:49:41.924Z] >
[2024-09-05T08:49:41.924Z]  (api_request.py:45)
[2024-09-05T08:49:41.924Z] [2024-09-05 08:49:32 - ERROR - ci_test]: (api_response) : <_MultiThreadedRendezvous of RPC that terminated with:
[2024-09-05T08:49:41.924Z] 	status = StatusCode.DEADLINE_EXCEEDED
[2024-09-05T08:49:41.924Z] 	details = "Deadline Exceeded"
[2024-09-05T08:49:41.924Z] 	debug_error_string = "UNKNOWN:Deadline Exceeded {grpc_status:4, created_time:"2024-09-05T08:49:32.660799001+00:00"}"
[2024-09-05T08:49:41.924Z] > (api_request.py:46)
```

```

[2024-09-05T07:46:21.422Z] <name>: Checker__loK8nTpx

[2024-09-05T07:46:21.422Z] <description>: 

[2024-09-05T07:46:21.422Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}......  (api_request.py:37)

[2024-09-05T07:46:21.422Z] [2024-09-05 07:37:36 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-09-05T07:46:21.422Z] [2024-09-05 07:37:39 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-09-05T07:46:21.422Z] [2024-09-05 07:37:39 - DEBUG - ci_test]: (api_request)  : [Collection.compact] args: [False, 180], kwargs: {} (api_request.py:62)

[2024-09-05T07:46:21.422Z] [2024-09-05 07:37:39 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-09-05T07:46:21.422Z] [2024-09-05 07:37:53 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-09-05T07:46:21.422Z] [2024-09-05 07:37:54 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-09-05T07:46:21.422Z] [2024-09-05 07:37:54 - INFO - ci_test]: assert create collection: 0.011192560195922852, init_entities: 33000 (test_all_collections_after_chaos.py:49)

[2024-09-05T07:46:21.422Z] [2024-09-05 07:37:58 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [[[-3000, -2999, -2998, -2997, -2996, -2995, -2994, -2993, -2992, -2991, -2990, -2989, -2988, -2987, -2986, -2985, -2984, -2983, -2982, -2981, -2980, -2979, -2978, -2977, -2976, -2975, -2974, -2973, -2972, -2971, -2970, -2969, -2968, -2967, -2966, -2965, -2964, -2963, -2962, -2961, -2960, -2959, -29......, kwargs: {'timeout': 180} (api_request.py:62)

[2024-09-05T07:46:21.423Z] [2024-09-05 07:37:59 - DEBUG - ci_test]: (api_response) : (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 452335207276875683, success count: 2000, err count: 0  (api_request.py:37)

[2024-09-05T07:46:21.423Z] [2024-09-05 07:37:59 - INFO - ci_test]: assert insert: 2.255796432495117 (test_all_collections_after_chaos.py:57)

[2024-09-05T07:46:21.423Z] [2024-09-05 07:37:59 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-09-05T07:46:21.423Z] [2024-09-05 07:38:11 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-09-05T07:46:21.423Z] [2024-09-05 07:38:11 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-09-05T07:46:21.423Z] [2024-09-05 07:38:19 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-09-05T07:46:21.423Z] [2024-09-05 07:38:19 - INFO - ci_test]: assert flush: 11.114547491073608, entities: 35000 (test_all_collections_after_chaos.py:67)

[2024-09-05T07:46:21.423Z] [2024-09-05 07:38:19 - INFO - ci_test]: index info: [{'collection': 'Checker__loK8nTpx', 'field': 'int64', 'index_name': 'int64', 'index_param': {'index_type': 'INVERTED'}}, {'collection': 'Checker__loK8nTpx', 'field': 'float', 'index_name': 'float', 'index_param': {'index_type': 'INVERTED'}}, {'collection': 'Checker__loK8nTpx', 'field': 'varchar', 'index_name': 'varchar', 'index_param': {'index_type': 'INVERTED'}}, {'collection': 'Checker__loK8nTpx', 'field': 'float_vector', 'index_name': 'float_vector', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}, {'collection': 'Checker__loK8nTpx', 'field': 'image_emb', 'index_name': 'image_emb', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}, {'collection': 'Checker__loK8nTpx', 'field': 'text_emb', 'index_name': 'text_emb', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}, {'collection': 'Checker__loK8nTpx', 'field': 'voice_emb', 'index_name': 'voice_emb', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}] (test_all_collections_after_chaos.py:71)

[2024-09-05T07:46:21.423Z] [2024-09-05 07:38:19 - INFO - ci_test]: index info: [{'collection': 'Checker__loK8nTpx', 'field': 'varchar', 'index_name': 'varchar', 'index_param': {'index_type': 'INVERTED'}}, {'collection': 'Checker__loK8nTpx', 'field': 'float_vector', 'index_name': 'float_vector', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}, {'collection': 'Checker__loK8nTpx', 'field': 'image_emb', 'index_name': 'image_emb', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}, {'collection': 'Checker__loK8nTpx', 'field': 'text_emb', 'index_name': 'text_emb', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}, {'collection': 'Checker__loK8nTpx', 'field': 'voice_emb', 'index_name': 'voice_emb', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}, {'collection': 'Checker__loK8nTpx', 'field': 'int64', 'index_name': 'int64', 'index_param': {'index_type': 'INVERTED'}}, {'collection': 'Checker__loK8nTpx', 'field': 'float', 'index_name': 'float', 'index_param': {'index_type': 'INVERTED'}}] (test_all_collections_after_chaos.py:86)

[2024-09-05T07:46:21.423Z] [2024-09-05 07:38:19 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 180], kwargs: {} (api_request.py:62)

[2024-09-05T07:46:21.423Z] [2024-09-05 07:38:19 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-09-05T07:46:21.423Z] [2024-09-05 07:38:19 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.13894007311468448, 0.07227371539727309, 0.018555914386370633, 0.04899970662119512, 0.0314175602446851, 0.0934565280991293, 0.10561843403686338, 0.07280634025086548, 0.09755699673404505, 0.1201062715926152, 0.092365476190506, 0.09488174922086669, 0.03463220429494024, 0.11211440151992388, 0.12733......, kwargs: {} (api_request.py:62)

[2024-09-05T07:46:21.423Z] [2024-09-05 07:41:19 - ERROR - pymilvus.decorators]: grpc RpcError: [search], <_InactiveRpcError: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded>, <Time:{'RPC start': '2024-09-05 07:38:19.925575', 'gRPC error': '2024-09-05 07:41:19.927683'}> (decorators.py:151)

[2024-09-05T07:46:21.423Z] [2024-09-05 07:41:19 - ERROR - ci_test]: Traceback (most recent call last):

[2024-09-05T07:46:21.423Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2024-09-05T07:46:21.423Z]     res = func(*args, **_kwargs)

[2024-09-05T07:46:21.423Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2024-09-05T07:46:21.423Z]     return func(*arg, **kwargs)

[2024-09-05T07:46:21.423Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 807, in search

[2024-09-05T07:46:21.423Z]     resp = conn.search(

[2024-09-05T07:46:21.423Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 155, in handler

[2024-09-05T07:46:21.423Z]     raise e from e

[2024-09-05T07:46:21.423Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 137, in handler

[2024-09-05T07:46:21.423Z]     return func(*args, **kwargs)

[2024-09-05T07:46:21.423Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 176, in handler

[2024-09-05T07:46:21.423Z]     return func(self, *args, **kwargs)

[2024-09-05T07:46:21.423Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 90, in handler

[2024-09-05T07:46:21.423Z]     raise e from e

[2024-09-05T07:46:21.423Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 86, in handler

[2024-09-05T07:46:21.423Z]     return func(*args, **kwargs)

[2024-09-05T07:46:21.423Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 800, in search

[2024-09-05T07:46:21.423Z]     return self._execute_search(request, timeout, round_decimal=round_decimal, **kwargs)

[2024-09-05T07:46:21.423Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 741, in _execute_search

[2024-09-05T07:46:21.423Z]     raise e from e

[2024-09-05T07:46:21.423Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 733, in _execute_search

[2024-09-05T07:46:21.423Z]     response = self._stub.Search(request, timeout=timeout)

[2024-09-05T07:46:21.423Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_interceptor.py", line 277, in __call__

[2024-09-05T07:46:21.423Z]     response, ignored_call = self._with_call(

[2024-09-05T07:46:21.423Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_interceptor.py", line 332, in _with_call

[2024-09-05T07:46:21.423Z]     return call.result(), call

[2024-09-05T07:46:21.423Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 438, in result

[2024-09-05T07:46:21.423Z]     raise self

[2024-09-05T07:46:21.423Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_interceptor.py", line 315, in continuation

[2024-09-05T07:46:21.423Z]     response, call = self._thunk(new_method).with_call(

[2024-09-05T07:46:21.423Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_interceptor.py", line 343, in with_call

[2024-09-05T07:46:21.423Z]     return self._with_call(

[2024-09-05T07:46:21.423Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_interceptor.py", line 332, in _with_call

[2024-09-05T07:46:21.423Z]     return call.result(), call

[2024-09-05T07:46:21.423Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 438, in result

[2024-09-05T07:46:21.423Z]     raise self

[2024-09-05T07:46:21.423Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_interceptor.py", line 315, in continuation

[2024-09-05T07:46:21.423Z]     response, call = self._thunk(new_method).with_call(

[2024-09-05T07:46:21.423Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 1178, in with_call

[2024-09-05T07:46:21.423Z]     return _end_unary_response_blocking(state, call, True, None)

[2024-09-05T07:46:21.423Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 1004, in _end_unary_response_blocking

[2024-09-05T07:46:21.423Z]     raise _InactiveRpcError(state)  # pytype: disable=not-instantiable

[2024-09-05T07:46:21.423Z] grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:

[2024-09-05T07:46:21.423Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2024-09-05T07:46:21.423Z] 	details = "Deadline Exceeded"

[2024-09-05T07:46:21.423Z] 	debug_error_string = "UNKNOWN:Deadline Exceeded {created_time:"2024-09-05T07:41:19.926771133+00:00", grpc_status:4}"

[2024-09-05T07:46:21.423Z] >

[2024-09-05T07:46:21.423Z]  (api_request.py:45)

[2024-09-05T07:46:21.423Z] [2024-09-05 07:41:19 - ERROR - ci_test]: (api_response) : <_InactiveRpcError of RPC that terminated with:

[2024-09-05T07:46:21.423Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2024-09-05T07:46:21.423Z] 	details = "Deadline Exceeded"

[2024-09-05T07:46:21.423Z] 	debug_error_string = "UNKNOWN:Deadline Exceeded {created_time:"2024-09-05T07:41:19.926771133+00:00", grpc_status:4}"

[2024-09-05T07:46:21.423Z] > (api_request.py:46)
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-straming-node-cron/detail/chaos-test-straming-node-cron/1/pipeline

log:
[artifacts-proxy-pod-kill-1-server-logs.tar.gz](https://github.com/user-attachments/files/16909504/artifacts-proxy-pod-kill-1-server-logs.tar.gz)

**Comment by chyezh** [comment]
Message size too large for grpc stream

**Comment by chyezh** [comment]
@zhuwenxing please verify it.
