### ISSUE TITLE
[Bug]: Querynode is crashed during the rolling upgrade from master to master

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#36198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20240908-208c8a23 to master-20240912-68266cdd
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Querynode is crashed during the rolling upgrade

panic:
```
[2024/09/12 03:15:36.514 +00:00] [INFO] [segments/segment_loader.go:896] ["load field binlogs done for sealed segment"] [traceID=f60bd62851fa780860901d89956fc2f1] [collection=452421311920841263] [segment=452421311920841315] [len(field)=4] [segmentType=Sealed]
[2024/09/12 03:15:36.514 +00:00] [INFO] [segments/segment.go:1187] ["load text index"] [traceID=f60bd62851fa780860901d89956fc2f1] ["field id"=0] ["text logs"=]
thread '<unnamed>' panicked at src/util.rs:7:41:
called `Result::unwrap()` on an `Err` value: DoesNotExist("/var/lib/milvus/data/querynode/text_log/0/0/452421311920841315/0/")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
SIGABRT: abort
PC=0x7f9c726a59fc m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 266 [syscall, locked to thread]:
non-Go function
        pc=0x7f9c726a59fc
non-Go function
        pc=0x7f9c72651475
non-Go function
        pc=0x7f9c726377f2
_ZN3std3sys4unix14abort_internal17hb82186f9b9b64ef6E
        library/std/src/sys/unix/mod.rs:365 pc=0x7f9c75722656
rust_panic
        library/std/src/panicking.rs:758 pc=0x7f9c75716a43
_ZN3std9panicking20rust_panic_with_hook17h57e78470c47c84deE
        library/std/src/panicking.rs:729 pc=0x7f9c757168a1
_ZN3std9panicking19begin_panic_handler28_$u7b$$u7b$closure$u7d$$u7d$17h3dfd2453cf356ecbE
        library/std/src/panicking.rs:599 pc=0x7f9c757165e6
_ZN3std10sys_common9backtrace26__rust_end_short_backtrace17hdb177d43678e4d7eE
        library/std/src/sys_common/backtrace.rs:170 pc=0x7f9c757138d5
rust_begin_unwind
        library/std/src/panicking.rs:595 pc=0x7f9c75716331
_ZN4core9panicking9panic_fmt17hd1e971d8d7c78e0eE
        library/core/src/panicking.rs:67 pc=0x7f9c747ea502
_ZN4core6result13unwrap_failed17hccb456d39e9c31fcE
        library/core/src/result.rs:1652 pc=0x7f9c747ea9f9
runtime.cgocall(0x5ee2690, 0xc00179deb0)
        /usr/local/go/src/runtime/cgocall.go:157 +0x4b fp=0xc00179de88 sp=0xc00179de50 pc=0x213150b
github.com/milvus-io/milvus/internal/querynodev2/segments._Cfunc_LoadTextIndex(0x7f99e4130000, 0xc001abc180, 0x27)
        _cgo_gotypes.go:882 +0x54 fp=0xc00179deb0 sp=0xc00179de88 pc=0x5c625f4
github.com/milvus-io/milvus/internal/querynodev2/segments.(*LocalSegment).LoadTextIndex.func1.1(0xc00081b6c0?, {0xc001abc180, 0x27, 0x4ade965?})
        /workspace/source/internal/querynodev2/segments/segment.go:1211 +0x65 fp=0xc00179def0 sp=0xc00179deb0 pc=0x5c800c5
github.com/milvus-io/milvus/internal/querynodev2/segments.(*LocalSegment).LoadTextIndex.func1()
        /workspace/source/internal/querynodev2/segments/segment.go:1211 +0x2c fp=0xc00179df28 sp=0xc00179def0 pc=0x5c8000c
github.com/milvus-io/milvus/pkg/util/conc.(*Pool[...]).Submit.func1()
        /workspace/source/pkg/util/conc/pool.go:81 +0xb3 fp=0xc00179df88 sp=0xc00179df28 pc=0x4ade7d3
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
        /go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.2/worker.go:67 +0x8d fp=0xc00179dfe0 sp=0xc00179df88 pc=0x3e5064d
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00179dfe8 sp=0xc00179dfe0 pc=0x21a15e1
created by github.com/panjf2000/ants/v2.(*goWorker).run in goroutine 467
        /go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.2/worker.go:48 +0x5c

goroutine 1 [chan receive]:
runtime.gopark(0xfd8a8d6666a5bc?, 0x18?, 0x18?, 0x0?, 0x6937f00?)
        /usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc001eaf558 sp=0xc001eaf538 pc=0x216bdae
runtime.chanrecv(0xc0001a09c0, 0x0, 0x1)
        /usr/local/go/src/runtime/chan.go:583 +0x3cd fp=0xc001eaf5d0 sp=0xc001eaf558 pc=0x2133bad
runtime.chanrecv1(0xa0438c8?, 0x6937f00?)
        /usr/local/go/src/runtime/chan.go:442 +0x12 fp=0xc001eaf5f8 sp=0xc001eaf5d0 pc=0x21337b2
github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run(0xc000e7b400)
        /workspace/source/cmd/roles/roles.go:532 +0x1406 fp=0xc001eafb70 sp=0xc001eaf5f8 pc=0x5dea826
github.com/milvus-io/milvus/cmd/milvus.(*run).execute(0x611a140?, {0xc0001aa810?, 0x3, 0x3}, 0xc0008d1a40)
        /workspace/source/cmd/milvus/run.go:47 +0x2c9 fp=0xc001eafc40 sp=0xc001eafb70 pc=0x5df6ea9
github.com/milvus-io/milvus/cmd/milvus.RunMilvus({0xc0001aa810?, 0x3, 0x3})
        /workspace/source/cmd/milvus/milvus.go:60 +0x204 fp=0xc001eafcb8 sp=0xc001eafc40 pc=0x5df6b44
main.main()
        /workspace/source/cmd/main.go:97 +0x44a fp=0xc001eaff40 sp=0xc001eafcb8 pc=0x5dfb72a
runtime.main()
        /usr/local/go/src/runtime/proc.go:267 +0x2bb fp=0xc001eaffe0 sp=0xc001eaff40 pc=0x216b93b
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc001eaffe8 sp=0xc001eaffe0 pc=0x21a15e1
...
```

node:
```
default-null-test-skmkb-etcd-0                                    1/1     Running                           0                 19m
default-null-test-skmkb-etcd-1                                    1/1     Running                           0                 20m
default-null-test-skmkb-etcd-2                                    1/1     Running                           0                 21m
default-null-test-skmkb-milvus-datacoord-5c546b578d-ztt5d         1/1     Running                           0                 21m
default-null-test-skmkb-milvus-datanode-6686dc779d-7w7vs          1/1     Running                           0                 21m
default-null-test-skmkb-milvus-indexcoord-77c8b6d464-kmlrn        1/1     Running                           0                 21m
default-null-test-skmkb-milvus-indexnode-568c487f55-q9rkw         1/1     Running                           0                 21m
default-null-test-skmkb-milvus-proxy-748856dc48-ttcp2             1/1     Running                           0                 21m
default-null-test-skmkb-milvus-querycoord-5f94756659-7szrz        1/1     Running                           0                 21m
default-null-test-skmkb-milvus-querynode-8467767d6b-z48qr         1/1     Running                           6 (18h ago)       3d
default-null-test-skmkb-milvus-querynode-d799684df-kbbkr          0/1     CrashLoopBackOff                  8 (86s ago)       21m
default-null-test-skmkb-milvus-rootcoord-6c9475554c-mk2fv         1/1     Running                           0                 21m
default-null-test-skmkb-minio-0                                   1/1     Running                           0                 3d
default-null-test-skmkb-minio-1                                   1/1     Running                           0                 3d
default-null-test-skmkb-minio-2                                   1/1     Running                           0                 3d
default-null-test-skmkb-minio-3                                   1/1     Running                           0                 3d
default-null-test-skmkb-pulsar-bookie-0                           1/1     Running                           0                 3d
default-null-test-skmkb-pulsar-bookie-1                           1/1     Running                           0                 3d
default-null-test-skmkb-pulsar-bookie-2                           1/1     Running                           0                 3d
default-null-test-skmkb-pulsar-broker-0                           1/1     Running                           0                 3d
default-null-test-skmkb-pulsar-proxy-0                            1/1     Running                           0                 3d
default-null-test-skmkb-pulsar-recovery-0                         1/1     Running                           0                 3d
default-null-test-skmkb-pulsar-zookeeper-0                        1/1     Running                           0                 3d
default-null-test-skmkb-pulsar-zookeeper-1                        1/1     Running                           0                 3d
default-null-test-skmkb-pulsar-zookeeper-2                        1/1     Running                           0                 3d
```

### Expected Behavior

No crash during rolling upgrade

### Steps To Reproduce

```markdown
Rolling upgrade from master-20240908-208c8a23 to master-20240912-68266cdd
```

### Milvus Log

[crash.log](https://github.com/user-attachments/files/16972915/crash.log)

**Comment by longjiquan** [comment]
There are some bugs in the master branch before the text-match and after the pk reordering feature. You can try this operation from commit before https://github.com/milvus-io/milvus/pull/35054 to current master branch.

**Comment by binbinlv** [comment]
> There are some bugs in the master branch before the text-match and after the pk reordering feature. You can try this operation from commit before #35054 to current master branch.

Yes, checked, the commit "master-20240908-208c8a23" is actually between the last text-match commit and the commit of pk reordering feature.

Try the commit after the last text-match commit "master-20240911-bb96b150" to "master-20240912-68266cdd", it is upgraded successfully, so the bug is fixed.
