### ISSUE TITLE
[Bug]: [null & default] partition key and nullable could be enabled at the same time without any errors

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#36213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20240912-68266cdd
- Deployment mode(standalone or cluster):both
- MQ type(rocksmq, pulsar or kafka):    all
- SDK version(e.g. pymilvus v2.0.0rc2):2.5.0rc78
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

partition key and nullable could be enabled at the same time without any errors

while when bulk insert, it reports:
```
[2024-09-12 17:45:43 - INFO - ci_test]: {452490807988988024: <Bulk insert state:
    - taskID          : 452490807988988024,
    - state           : Failed,
    - row_count       : 0,
    - infos           : {'failed_reason': 'partition key field not support nullable: invalid parameter', 'progress_percent': '0'},
    - id_ranges       : [],
    - create_ts       : 2024-09-12 17:45:36
```

### Expected Behavior

Report error "partition key field not support nullable: invalid parameter" when enable partition key and nullable at the same time

### Steps To Reproduce

```python
from pymilvus import CollectionSchema, FieldSchema
from pymilvus import Collection
from pymilvus import connections
from pymilvus import DataType
from pymilvus import Partition
from pymilvus import utility
import json
import random

connections.connect()

dim = 128
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
double_field = FieldSchema(name="nullableFid", dtype=DataType.VARCHAR, nullable=True, max_length=100, is_partition_key=True)
int32_field = FieldSchema(name="int32", dtype=DataType.INT64, default_value=3)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim, nullable=False)
schema = CollectionSchema(fields=[int64_field, double_field, int32_field,float_vector])
utility.drop_collection("test")
collection = Collection("test", schema=schema)
res = collection.schema
print(res)
varchar_scalar_index = "TRIE"
scalar_index_params = {"index_type": varchar_scalar_index, "params": {}}

collection.create_index("nullableFid", scalar_index_params, index_name="index_name_0")
#index = {"index_type": "DISKANN", "metric_type": "L2", "params": {}}

index = "HNSW"
params = {'ef': 64}
default_index = {"index_type": index, "params": params, "metric_type": "COSINE"}

nb = 5000
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
data = [[i for i in range(nb)], [None for _ in range(nb)],[], vectors]
#  equals to data1 = [[1,2], [None,None],[None,None], vectors]
data1 = [[1,2], [],[], vectors]

collection.insert(data=data)
#collection.upsert(data=data1)
collection.create_index("float_vector", index, index_name="index_name_1")
collection.load()
collection.flush()
res = collection.num_entities
print(res)
default_search_params = {"metric_type": "", "params": {}}
limit = 1000
nq = 2
import time
start = time.time()
res1 = collection.search(vectors[:nq], "float_vector", default_search_params, limit, expr="nullableFid==''", output_fields=["nullableFid", "int32"])
end = time.time() - start
print(res1)
print("search successfully in %f s" % end)
start = time.time()
res = collection.query("int64>=0", output_fields=["nullableFid","int32"])
end = time.time() - start
print(res)
print("query successfully in %f s" % end)
```

**Comment by smellthemoon** [comment]
The operations for the partition key field are == or in. null can only be query by isNull or isNotNull. not need to set nullable and isPartition key both, which may cause performance degradation. So not allowed yet. I will add the err.

**Comment by binbinlv** [comment]
Verified and fixed:
milvus: master-20240914-5ce99e25-amd64
pymilvus: 2.5.0rc78

result:
```
RPC error: [create_collection], <MilvusException: (code=1100, message=partition key field not support nullable: invalid parameter)>, <Time:{'RPC start': '2024-09-14 18:43:31.604774', 'RPC error': '2024-09-14 18:43:31.619229'}>
Traceback (most recent call last):
  File "./default.py", line 19, in <module>
    collection = Collection("test", schema=schema)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 150, in __init__
    conn.create_collection(self._name, schema, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 141, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 137, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 176, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 116, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 86, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 308, in create_collection
    check_status(status)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/utils.py", line 63, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1100, message=partition key field not support nullable: invalid parameter)>
```
