### ISSUE TITLE
[Bug]: Array expression query, invalid parameter error message is not friendly

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#36221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20240909-99817953-amd64
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

client log：
fail to Query on QueryNode 5: worker(5) query failed: Operator::GetOutput failed for [Operator:FilterBits, plan node id: 0] : Assert "(value_proto.val_case() == milvus::proto::plan::GenericValue::kStringVal)

```
[2024-09-12 12:23:17,499 - DEBUG - ci_test]: (api_request)  : [Collection.query] args: ["array_contains_all(ARRAY_VARCHAR, [['a', 'b']])", None, None, 180], kwargs: {'limit': 1} (api_request.py:62)
[2024-09-12 12:23:18,509 - ERROR - ci_test]: Traceback (most recent call last):
  File "/src/milvus/tests/python_client/utils/api_request.py", line 32, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/src/milvus/tests/python_client/utils/api_request.py", line 63, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 1074, in query
    return conn.query(
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 140, in handler
    raise e from e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 136, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 175, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 115, in handler
    raise e from e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 86, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 1503, in query
    check_status(response.status)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/utils.py", line 63, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=fail to Query on QueryNode 5: worker(5) query failed: Operator::GetOutput failed for [Operator:FilterBits, plan node id: 0] : Assert "(value_proto.val_case() == milvus::proto::plan::GenericValue::kStringVal)"  at /workspace/source/internal/core/src/exec/expression/Utils.h:135
)>
 (api_request.py:45)
```

### Expected Behavior

expected raises error massage like `failed to create query plan: cannot parse expression: array_contains(ARRAY_VARCHAR, [['a', 'b']])`

**Comment by xiaocai2333** [comment]
We refined it and are waiting for the PR to be merged.

**Comment by wangting0128** [comment]
verification passed, close it now
