### ISSUE TITLE
Server crashed during search with index pq on dataset: sift-50m

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#3626]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
log and data path:
`
"logs.path":"/test/milvus/db_data_011/sift_50m_100000_128_pq/logs"
`
```
19:41:16  2020-09-05:11:41:15,916 DEBUG    [client.py:309] Row count: 50000000 in collection: <sift_50m_100000_128_l2>
19:41:16  2020-09-05:11:41:15,916 INFO     [k8s_runner.py:357] 50000000
19:41:16  2020-09-05:11:41:15,918 INFO     [k8s_runner.py:359] {'index_type': 'IVF_PQ', 'index_param': {'m': 32, 'nlist': 1024}}

19:42:52  2020-09-05:11:42:49,281 INFO     [client.py:36] Milvus preload_collection run in 93.36s
19:42:52  2020-09-05:11:42:49,281 INFO     [k8s_runner.py:361] Start warm up query
19:42:52  2020-09-05:11:42:49,421 INFO     [runner.py:217] Start query, query params: top-k: 1, nq: 1, actually length of vectors: 1
19:42:52  2020-09-05:11:42:49,421 INFO     [runner.py:219] Start run query, run 1 of 2
19:42:52  2020-09-05:11:42:51,663 INFO     [runner.py:219] Start run query, run 2 of 2
19:42:52  2020-09-05:11:42:52,517 INFO     [runner.py:231] Min query time: 0.85
19:42:52  2020-09-05:11:42:52,530 INFO     [k8s_runner.py:363] End warm up query
19:42:52  2020-09-05:11:42:52,530 INFO     [k8s_runner.py:365] Search param: {"nprobe": 8}
19:42:52  2020-09-05:11:42:52,668 INFO     [runner.py:217] Start query, query params: top-k: 1, nq: 1, actually length of vectors: 1
19:42:52  2020-09-05:11:42:52,668 INFO     [runner.py:219] Start run query, run 1 of 2

19:42:54  2020-09-05:11:42:54,390 INFO     [runner.py:219] Start run query, run 2 of 2

19:42:55  2020-09-05:11:42:55,252 INFO     [runner.py:231] Min query time: 0.86
19:42:55  2020-09-05:11:42:55,252 INFO     [runner.py:217] Start query, query params: top-k: 10, nq: 1, actually length of vectors: 1
19:42:55  2020-09-05:11:42:55,252 INFO     [runner.py:219] Start run query, run 1 of 2

19:42:56  2020-09-05:11:42:56,48 INFO     [runner.py:219] Start run query, run 2 of 2

19:42:57  2020-09-05:11:42:56,826 INFO     [runner.py:231] Min query time: 0.78
19:42:57  2020-09-05:11:42:56,826 INFO     [runner.py:217] Start query, query params: top-k: 100, nq: 1, actually length of vectors: 1
19:42:57  2020-09-05:11:42:56,826 INFO     [runner.py:219] Start run query, run 1 of 2

19:42:58  2020-09-05:11:42:57,746 INFO     [runner.py:219] Start run query, run 2 of 2

19:42:58  2020-09-05:11:42:58,551 INFO     [runner.py:231] Min query time: 0.80
19:42:58  2020-09-05:11:42:58,551 INFO     [runner.py:217] Start query, query params: top-k: 1000, nq: 1, actually length of vectors: 1
19:42:58  2020-09-05:11:42:58,552 INFO     [runner.py:219] Start run query, run 1 of 2
19:42:59  2020-09-05:11:42:59,492 INFO     [runner.py:219] Start run query, run 2 of 2

19:43:00  2020-09-05:11:43:00,351 INFO     [runner.py:231] Min query time: 0.86
19:43:00  2020-09-05:11:43:00,351 INFO     [runner.py:217] Start query, query params: top-k: 1, nq: 10, actually length of vectors: 10
19:43:00  2020-09-05:11:43:00,351 INFO     [runner.py:219] Start run query, run 1 of 2

19:43:02  2020-09-05:11:43:02,203 INFO     [runner.py:219] Start run query, run 2 of 2

19:43:03  2020-09-05:11:43:03,876 INFO     [runner.py:231] Min query time: 1.67
19:43:03  2020-09-05:11:43:03,876 INFO     [runner.py:217] Start query, query params: top-k: 10, nq: 10, actually length of vectors: 10
19:43:03  2020-09-05:11:43:03,876 INFO     [runner.py:219] Start run query, run 1 of 2

19:43:05  2020-09-05:11:43:05,367 INFO     [runner.py:219] Start run query, run 2 of 2

19:43:06  2020-09-05:11:43:06,620 INFO     [runner.py:231] Min query time: 1.25
19:43:06  2020-09-05:11:43:06,620 INFO     [runner.py:217] Start query, query params: top-k: 100, nq: 10, actually length of vectors: 10
19:43:06  2020-09-05:11:43:06,620 INFO     [runner.py:219] Start run query, run 1 of 2

19:43:08  2020-09-05:11:43:08,145 INFO     [runner.py:219] Start run query, run 2 of 2

19:43:10  2020-09-05:11:43:09,764 INFO     [runner.py:231] Min query time: 1.52
19:43:10  2020-09-05:11:43:09,764 INFO     [runner.py:217] Start query, query params: top-k: 1000, nq: 10, actually length of vectors: 10
19:43:10  2020-09-05:11:43:09,764 INFO     [runner.py:219] Start run query, run 1 of 2

19:43:12  2020-09-05:11:43:11,886 INFO     [runner.py:219] Start run query, run 2 of 2

19:43:14  2020-09-05:11:43:13,977 INFO     [runner.py:231] Min query time: 2.09
19:43:14  2020-09-05:11:43:13,977 INFO     [runner.py:217] Start query, query params: top-k: 1, nq: 100, actually length of vectors: 100
19:43:14  2020-09-05:11:43:13,978 INFO     [runner.py:219] Start run query, run 1 of 2

19:45:05  RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
19:45:05  	status = StatusCode.UNAVAILABLE
19:45:05  	details = "Socket closed"
19:45:05  	debug_error_string = "{"created":"@1599306296.592360212","description":"Error received from peer ipv4:10.108.158.243:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
19:45:05  >
19:45:05  	{'API start': '2020-09-05 11:43:13.978379', 'RPC start': '2020-09-05 11:43:13.978403', 'RPC error': '2020-09-05 11:44:56.593181'}
19:45:05  2020-09-05:11:44:56,593 ERROR    [grpc_handler.py:58] RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
19:45:05  	status = StatusCode.UNAVAILABLE
19:45:05  	details = "Socket closed"
19:45:05  	debug_error_string = "{"created":"@1599306296.592360212","description":"Error received from peer ipv4:10.108.158.243:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
19:45:05  >
19:45:05  	{'API start': '2020-09-05 11:43:13.978379', 'RPC start': '2020-09-05 11:43:13.978403', 'RPC error': '2020-09-05 11:44:56.593181'}
19:45:05  2020-09-05:11:44:56,593 ERROR    [main.py:70] <_MultiThreadedRendezvous of RPC that terminated with:
19:45:05  	status = StatusCode.UNAVAILABLE
19:45:05  	details = "Socket closed"
19:45:05  	debug_error_string = "{"created":"@1599306296.592360212","description":"Error received from peer ipv4:10.108.158.243:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
19:45:05  >
19:45:05  2020-09-05:11:44:56,595 ERROR    [main.py:71] Traceback (most recent call last):
19:45:05    File "main.py", line 68, in queue_worker
19:45:05      runner.run(run_type, collection)
19:45:05    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/k8s_runner.py", line 366, in run
19:45:05      res = self.do_query(milvus_instance, collection_name, vec_field_name, top_ks, nqs, run_count, search_param, filter_query=filter_query)
19:45:05    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/runner.py", line 227, in do_query
19:45:05      query_res = milvus.query(vector_query, filter_query=filter_query)
19:45:05    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/client.py", line 278, in query
19:45:05      result = self._milvus.search(tmp_collection_name, query)
19:45:05    File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 35, in inner
19:45:05      return func(self, *args, **kwargs)
19:45:05    File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 614, in search
19:45:05      return handler.search(collection_name, query_entities, partition_tags, fields, timeout=timeout, **kwargs)
19:45:05    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 59, in handler
19:45:05      raise e
19:45:05    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 42, in handler
19:45:05      return func(self, *args, **kwargs)
19:45:05    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 552, in search
19:45:05      response = ft.result()
19:45:05    File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 625, in result
19:45:05      raise self
19:45:05  grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
19:45:05  	status = StatusCode.UNAVAILABLE
19:45:05  	details = "Socket closed"
19:45:05  	debug_error_string = "{"created":"@1599306296.592360212","description":"Error received from peer ipv4:10.108.158.243:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
19:45:05  >
```

**Steps/Code to reproduce behavior**

1. create a collection

2. build index
```
index_type: ivf_pq
index_param:
       nlist: 1024
       m: 32
```

3. search 
```
top_ks: [1, 10, 100, 1000]
nqs: [1, 10, 100, 1000, 1200]
 search_params:
      -
          nprobe: 8
     -
         nprobe: 32
```
**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [x] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
Server command: get_milvus_config, result: {"cache.cache_insert_data":"false","cache.cache_size":"32GB","cache.cpu_cache_threshold":"0.700000","cache.insert_buffer_size":"1GB","cache.preload_collection":"","cluster.enable":"false","cluster.role":"rw","engine.build_index_threshold":"4096","engine.omp_thread_num":"0","engine.search_combine_nq":"64","engine.simd_type":"auto","engine.use_blas_threshold":"1100","general.meta_uri":"sqlite://:@:/","general.timezone":"UTC+8","gpu.build_index_devices":"gpu0,gpu1,","gpu.cache_size":"6GB","gpu.cache_threshold":"0.700000","gpu.enable":"true","gpu.gpu_search_threshold":"100","gpu.search_devices":"gpu0,gpu1,","logs.level":"debug","logs.log_rotate_num":"0","logs.max_log_file_size":"1GB","logs.path":"/test/milvus/db_data_011/sift_50m_100000_128_pq/logs","logs.trace.enable":"true","metric.address":"192.168.1.237","metric.enable":"true","metric.port":"9091","network.bind.address":"0.0.0.0","network.bind.port":"19530","network.http.enable":"true","network.http.port":"19121","storage.auto_flush_interval":"1","storage.path":"/test/milvus/db_data_011/sift_50m_100000_128_pq","system.lock.enable":"true","tracing.json_config_path":"","transcript.enable":"false","transcript.replay":"","version":"0.5","wal.buffer_size":"256MB","wal.enable":"true","wal.path":"/test/milvus/db_data_011/sift_50m_100000_128_pq/wal","wal.recovery_error_ignore":"true"}
```

**Screenshots**

**Additional context**

**Comment by ThreadDao** [comment]
The server also ceashed when search with index ivf_flat
```
19:18:11  2020-09-05:11:18:11,715 DEBUG    [client.py:309] Row count: 50000000 in collection: <sift_50m_100000_128_l2>
19:18:11  2020-09-05:11:18:11,715 INFO     [k8s_runner.py:357] 50000000
19:18:11  2020-09-05:11:18:11,716 INFO     [k8s_runner.py:359] {'index_type': 'IVF_FLAT', 'index_param': {'nlist': 1024}}
```
when nq and topk are 1000:
```
19:24:20  2020-09-05:11:24:19,338 INFO     [runner.py:217] Start query, query params: top-k: 1000, nq: 1000, actually length of vectors: 1000
19:24:20  2020-09-05:11:24:19,338 INFO     [runner.py:219] Start run query, run 1 of 2

19:26:12  RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
19:26:12  	status = StatusCode.UNAVAILABLE
19:26:12  	details = "Socket closed"
19:26:12  	debug_error_string = "{"created":"@1599305164.294863743","description":"Error received from peer ipv4:10.103.13.217:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
19:26:12  >
19:26:12  	{'API start': '2020-09-05 11:24:19.338887', 'RPC start': '2020-09-05 11:24:19.338893', 'RPC error': '2020-09-05 11:26:04.295743'}
19:26:12  2020-09-05:11:26:04,295 ERROR    [grpc_handler.py:58] RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
19:26:12  	status = StatusCode.UNAVAILABLE
19:26:12  	details = "Socket closed"
19:26:12  	debug_error_string = "{"created":"@1599305164.294863743","description":"Error received from peer ipv4:10.103.13.217:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
19:26:12  >
19:26:12  	{'API start': '2020-09-05 11:24:19.338887', 'RPC start': '2020-09-05 11:24:19.338893', 'RPC error': '2020-09-05 11:26:04.295743'}
19:26:12  2020-09-05:11:26:04,296 ERROR    [main.py:70] <_MultiThreadedRendezvous of RPC that terminated with:
19:26:12  	status = StatusCode.UNAVAILABLE
19:26:12  	details = "Socket closed"
19:26:12  	debug_error_string = "{"created":"@1599305164.294863743","description":"Error received from peer ipv4:10.103.13.217:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
19:26:12  >
```

**Comment by XuanYang-cn** [comment]
I've tested on IVF_FLAT, it's ok now

**Comment by del-zhenwu** [comment]
```
11:50:41  2020-09-14 03:50:40,585 - milvus_benchmark.runner - INFO - Start query, query params: top-k: 100, nq: 1000, actually length of vectors: 1000
11:50:41  INFO:milvus_benchmark.runner:Start query, query params: top-k: 100, nq: 1000, actually length of vectors: 1000
11:50:41  2020-09-14 03:50:40,586 - milvus_benchmark.runner - INFO - Start run query, run 1 of 2
11:50:41  INFO:milvus_benchmark.runner:Start run query, run 1 of 2
11:51:20  2020-09-14 03:51:18,695 - milvus_benchmark.runner - INFO - Start run query, run 2 of 2
11:51:20  INFO:milvus_benchmark.runner:Start run query, run 2 of 2
11:53:13  RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
11:53:13  	status = StatusCode.UNAVAILABLE
11:53:13  	details = "Socket closed"
11:53:13  	debug_error_string = "{"created":"@1600055590.032368408","description":"Error received from peer ipv4:10.97.255.102:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
11:53:13  >
11:53:13  	{'API start': '2020-09-14 03:51:18.696169', 'RPC start': '2020-09-14 03:51:18.696175', 'RPC error': '2020-09-14 03:53:10.033146'}
11:53:13  ERROR:milvus.client.grpc_handler:RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
11:53:13  	status = StatusCode.UNAVAILABLE
11:53:13  	details = "Socket closed"
11:53:13  	debug_error_string = "{"created":"@1600055590.032368408","description":"Error received from peer ipv4:10.97.255.102:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
11:53:13  >
11:53:13  	{'API start': '2020-09-14 03:51:18.696169', 'RPC start': '2020-09-14 03:51:18.696175', 'RPC error': '2020-09-14 03:53:10.033146'}
11:53:13  2020-09-14 03:53:10,033 - milvus_benchmark - ERROR - <_MultiThreadedRendezvous of RPC that terminated with:
11:53:13  	status = StatusCode.UNAVAILABLE
11:53:13  	details = "Socket closed"
11:53:13  	debug_error_string = "{"created":"@1600055590.032368408","description":"Error received from peer ipv4:10.97.255.102:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
11:53:13  >
11:53:13  ERROR:milvus_benchmark:<_MultiThreadedRendezvous of RPC that terminated with:
11:53:13  	status = StatusCode.UNAVAILABLE
11:53:13  	details = "Socket closed"
11:53:13  	debug_error_string = "{"created":"@1600055590.032368408","description":"Error received from peer ipv4:10.97.255.102:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
11:53:13  >
11:53:13  2020-09-14 03:53:10,048 - milvus_benchmark - ERROR - Traceback (most recent call last):
11:53:13    File "main.py", line 80, in queue_worker
11:53:13      runner.run(run_type, collection)
11:53:13    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/k8s_runner.py", line 367, in run
11:53:13      res = self.do_query(milvus_instance, collection_name, vec_field_name, top_ks, nqs, run_count, search_param, filter_query=filter_query)
11:53:13    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/runner.py", line 227, in do_query
11:53:13      query_res = milvus.query(vector_query, filter_query=filter_query)
11:53:13    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/client.py", line 279, in query
11:53:13      result = self._milvus.search(tmp_collection_name, query)
11:53:13    File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 35, in inner
11:53:13      return func(self, *args, **kwargs)
11:53:13    File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 614, in search
11:53:13      return handler.search(collection_name, query_entities, partition_tags, fields, timeout=timeout, **kwargs)
11:53:13    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 59, in handler
11:53:13      raise e
11:53:13    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 42, in handler
11:53:13      return func(self, *args, **kwargs)
11:53:13    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 552, in search
11:53:13      response = ft.result()
11:53:13    File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 625, in result
11:53:13      raise self
11:53:13  grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
11:53:13  	status = StatusCode.UNAVAILABLE
11:53:13  	details = "Socket closed"
11:53:13  	debug_error_string = "{"created":"@1600055590.032368408","description":"Error received from peer ipv4:10.97.255.102:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
11:53:13  >
11:53:13  
11:53:13  ERROR:milvus_benchmark:Traceback (most recent call last):
11:53:13    File "main.py", line 80, in queue_worker
11:53:13      runner.run(run_type, collection)
11:53:13    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/k8s_runner.py", line 367, in run
11:53:13      res = self.do_query(milvus_instance, collection_name, vec_field_name, top_ks, nqs, run_count, search_param, filter_query=filter_query)
11:53:13    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/runner.py", line 227, in do_query
11:53:13      query_res = milvus.query(vector_query, filter_query=filter_query)
11:53:13    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/client.py", line 279, in query
11:53:13      result = self._milvus.search(tmp_collection_name, query)
11:53:13    File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 35, in inner
11:53:13      return func(self, *args, **kwargs)
11:53:13    File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 614, in search
11:53:13      return handler.search(collection_name, query_entities, partition_tags, fields, timeout=timeout, **kwargs)
11:53:13    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 59, in handler
11:53:13      raise e
11:53:13    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 42, in handler
11:53:13      return func(self, *args, **kwargs)
11:53:13    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 552, in search
11:53:13      response = ft.result()
11:53:13    File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 625, in result
11:53:13      raise self
11:53:13  grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
11:53:13  	status = StatusCode.UNAVAILABLE
11:53:13  	details = "Socket closed"
11:53:13  	debug_error_string = "{"created":"@1600055590.032368408","description":"Error received from peer ipv4:10.97.255.102:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
11:53:13  >
11:53:13  
11:54:21  2020-09-14 03:54:10,107 - milvus_benchmark.k8s_runner - DEBUG - Start clean up: milvus-benchmark-test-tfhtkgyo
```

**Comment by del-zhenwu** [comment]
```
11:42:10  2020-09-14 03:42:04,676 - milvus_benchmark.client - INFO - Server command: build_commit_id, result: a8943f824cd5a14d5eae4b5b38b47dfb6d303223
11:42:10  INFO:milvus_benchmark.client:Server command: build_commit_id, result: a8943f824cd5a14d5eae4b5b38b47dfb6d303223
11:42:10  2020-09-14 03:42:04,757 - milvus_benchmark.client - INFO - Server command: mode, result: GPU
```

**Comment by del-zhenwu** [comment]
```
[2020-09-14 11:51:18,746][INFO][SERVER][Search][grpcpp_sync_ser] Request [137] Search begin.
[2020-09-14 11:51:25,595][INFO][SERVER][HandleSignal][taskloader_th] Server received critical signal: 11
[2020-09-14 11:51:25,602][INFO][SERVER][PrintStacktrace][taskloader_th] Call stack:
[2020-09-14 11:51:25,602][INFO][SERVER][PrintStacktrace][taskloader_th] /var/lib/milvus/bin/milvus_server(_ZN6milvus15PrintStacktraceEv+0x26) [0xbaaa96]
[2020-09-14 11:51:25,602][INFO][SERVER][PrintStacktrace][taskloader_th] /var/lib/milvus/bin/milvus_server(_ZN6milvus12HandleSignalEi+0x190) [0xbab600]
[2020-09-14 11:51:25,602][INFO][SERVER][PrintStacktrace][taskloader_th] /usr/lib64/libc.so.6(+0x36400) [0x7fa9f1892400]
[2020-09-14 11:51:25,602][INFO][SERVER][PrintStacktrace][taskloader_th] /usr/lib64/libc.so.6(abort+0x297) [0x7fa9f1893bc7]
[2020-09-14 11:51:25,602][INFO][SERVER][PrintStacktrace][taskloader_th] /var/lib/milvus/bin/milvus_server(_ZN5faiss3gpu15freeMemorySpaceENS0_11MemorySpaceEPv+0x90) [0xd9f480]
[2020-09-14 11:51:25,602][INFO][SERVER][PrintStacktrace][taskloader_th] /var/lib/milvus/bin/milvus_server(_ZN5faiss3gpu12DeviceVectorIhE6appendEPKhmP11CUstream_stb+0x158) [0xdeaf28]
[2020-09-14 11:51:25,602][INFO][SERVER][PrintStacktrace][taskloader_th] /var/lib/milvus/bin/milvus_server(_ZN5faiss3gpu7IVFBase18addIndicesFromCpu_EiPKlm+0x236) [0xde8156]
[2020-09-14 11:51:25,602][INFO][SERVER][PrintStacktrace][taskloader_th] /var/lib/milvus/bin/milvus_server(_ZN5faiss3gpu5IVFPQ21addCodeVectorsFromCpuEiPKvPKlm+0x131) [0xdc6231]
[2020-09-14 11:51:25,602][INFO][SERVER][PrintStacktrace][taskloader_th] /var/lib/milvus/bin/milvus_server(_ZN5faiss3gpu13GpuIndexIVFPQ8copyFromEPKNS_10IndexIVFPQE+0x19f) [0xdb116f]
[2020-09-14 11:51:25,602][INFO][SERVER][PrintStacktrace][taskloader_th] /var/lib/milvus/bin/milvus_server(_ZN5faiss3gpu13GpuIndexIVFPQC1EPNS0_12GpuResourcesEPKNS_10IndexIVFPQENS0_19GpuIndexIVFPQConfigE+0x91) [0xdb1581]
[2020-09-14 11:51:25,602][INFO][SERVER][PrintStacktrace][taskloader_th] /var/lib/milvus/bin/milvus_server(_ZN5faiss3gpu11ToGpuCloner11clone_IndexEPKNS_5IndexE+0x3a0) [0xd99370]
[2020-09-14 11:51:25,602][INFO][SERVER][PrintStacktrace][taskloader_th] /var/lib/milvus/bin/milvus_server(_ZN5faiss3gpu16index_cpu_to_gpuEPNS0_12GpuResourcesEiPKNS_5IndexEPKNS0_16GpuClonerOptionsE+0x4b) [0xd99e2b]
[2020-09-14 11:51:25,602][INFO][SERVER][PrintStacktrace][taskloader_th] /var/lib/milvus/bin/milvus_server(_ZN6milvus8knowhere5IVFPQ12CopyCpuToGpuElRKN8nlohmann10basic_jsonISt3mapSt6vectorSsblmdSaNS2_14adl_serializerEEE+0x8a) [0xc38d3a]
[2020-09-14 11:51:25,602][INFO][SERVER][PrintStacktrace][taskloader_th] /var/lib/milvus/bin/milvus_server(_ZN6milvus8knowhere6cloner12CopyCpuToGpuERKSt10shared_ptrINS0_8VecIndexEElRKN8nlohmann10basic_jsonISt3mapSt6vectorSsblmdSaNS7_14adl_serializerEEE+0x5d4) [0xc09f24]
[2020-09-14 11:51:25,602][INFO][SERVER][PrintStacktrace][taskloader_th] /var/lib/milvus/bin/milvus_server(_ZN6milvus6engine19ExecutionEngineImpl9CopyToGpuEm+0x199) [0x97f649]
[2020-09-14 11:51:25,602][INFO][SERVER][PrintStacktrace][taskloader_th] /var/lib/milvus/bin/milvus_server(_ZN6milvus9scheduler10SearchTask6OnLoadENS0_8LoadTypeEh+0x711) [0x7d9f91]
[2020-09-14 11:51:25,602][INFO][SERVER][PrintStacktrace][taskloader_th] /var/lib/milvus/bin/milvus_server(_ZN6milvus9scheduler4Task4LoadENS0_8LoadTypeEh+0x2a) [0x7db67a]
[2020-09-14 11:51:25,602][INFO][SERVER][PrintStacktrace][taskloader_th] /var/lib/milvus/bin/milvus_server(_ZN6milvus9scheduler8Resource15loader_functionEv+0x16c) [0x7cf4ac]
[2020-09-14 11:51:25,602][INFO][SERVER][PrintStacktrace][taskloader_th] /var/lib/milvus/bin/milvus_server() [0x12024bf]
[2020-09-14 11:51:25,602][INFO][SERVER][PrintStacktrace][taskloader_th] /usr/lib64/libpthread.so.0(+0x7ea5) [0x7fa9fad48ea5]
[2020-09-14 11:51:25,602][INFO][SERVER][PrintStacktrace][taskloader_th] /usr/lib64/libc.so.6(clone+0x6d) [0x7fa9f195a8dd]

```

**Comment by del-zhenwu** [comment]
fixed and close
