### ISSUE TITLE
[Bug]: Milvus panic when reducing at delegator

### ISSUE THREAD

**Issue by chyezh** [milvus-io/milvus#36362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.4.11
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Crash with following stack.

```
2024-09-18 15:42:40.755	panic: runtime error: index out of range [-1] [recovered]
2024-09-18 15:42:40.755		panic: runtime error: index out of range [-1] [recovered]
2024-09-18 15:42:40.755		panic: runtime error: index out of range [-1]
2024-09-18 15:42:40.755	
2024-09-18 15:42:40.755	goroutine 3226085 [running]:
2024-09-18 15:42:40.755	panic({0x56e1100?, 0xc003558138?})
2024-09-18 15:42:40.755		/usr/local/go/src/runtime/panic.go:1017 +0x3ac fp=0xc0027071b8 sp=0xc002707108 pc=0x1e57bec
2024-09-18 15:42:40.755	github.com/milvus-io/milvus/pkg/util/conc.(*poolOption).antsOptions.func1({0x56e1100, 0xc003558138})
2024-09-18 15:42:40.755		/root/milvus/pkg/util/conc/options.go:56 +0x146 fp=0xc002707280 sp=0xc0027071b8 pc=0x3af8866
2024-09-18 15:42:40.755	github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
2024-09-18 15:42:40.755		/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.2/worker.go:54 +0x6d fp=0xc0027072f8 sp=0xc002707280 pc=0x3af5ecd
2024-09-18 15:42:40.755	runtime.deferCallSave(0xc0027073b0, 0xc001685fb8?)
2024-09-18 15:42:40.755		/usr/local/go/src/runtime/panic.go:798 +0x84 fp=0xc002707308 sp=0xc0027072f8 pc=0x1e577a4
2024-09-18 15:42:40.755	runtime.runOpenDeferFrame(0xc002293130)
2024-09-18 15:42:40.755		/usr/local/go/src/runtime/panic.go:771 +0x1b8 fp=0xc002707348 sp=0xc002707308 pc=0x1e575d8
2024-09-18 15:42:40.755	panic({0x56e1100?, 0xc003558138?})
2024-09-18 15:42:40.755		/usr/local/go/src/runtime/panic.go:914 +0x21f fp=0xc0027073f8 sp=0xc002707348 pc=0x1e57a5f
2024-09-18 15:42:40.755	github.com/milvus-io/milvus/pkg/util/conc.(*Pool[...]).Submit.func1.1()
2024-09-18 15:42:40.755		/root/milvus/pkg/util/conc/pool.go:74 +0x8d fp=0xc002707458 sp=0xc0027073f8 pc=0x4cfa46d
2024-09-18 15:42:40.755	runtime.deferCallSave(0xc002707510, 0xc001685f50?)
2024-09-18 15:42:40.755		/usr/local/go/src/runtime/panic.go:798 +0x84 fp=0xc002707468 sp=0xc002707458 pc=0x1e577a4
2024-09-18 15:42:40.755	runtime.runOpenDeferFrame(0xc002293180)
2024-09-18 15:42:40.755		/usr/local/go/src/runtime/panic.go:771 +0x1b8 fp=0xc0027074a8 sp=0xc002707468 pc=0x1e575d8
2024-09-18 15:42:40.755	panic({0x56e1100?, 0xc003558138?})
2024-09-18 15:42:40.755		/usr/local/go/src/runtime/panic.go:914 +0x21f fp=0xc002707558 sp=0xc0027074a8 pc=0x1e57a5f
2024-09-18 15:42:40.755	runtime.goPanicIndex(0xffffffffffffffff, 0x0)
2024-09-18 15:42:40.755		/usr/local/go/src/runtime/panic.go:114 +0x7c fp=0xc002707598 sp=0xc002707558 pc=0x1e559dc
2024-09-18 15:42:40.755	github.com/milvus-io/milvus/internal/querynodev2/segments.MergeSegcoreRetrieveResults({0x6044460, 0xc002485080}, {0xc001cd26c0, 0x7, 0xc002482f50?}, 0xc001685c50, {0xc001cb16c0, 0x7, 0x59fc15b?}, 0xc001fdee20, ...)
2024-09-18 15:42:40.755		/root/milvus/internal/querynodev2/segments/result.go:586 +0x1f50 fp=0xc002707b70 sp=0xc002707598 pc=0x4d14f30
2024-09-18 15:42:40.755	github.com/milvus-io/milvus/internal/querynodev2/segments.mergeSegcoreRetrieveResultsAndFillIfEmpty({0x6044460?, 0xc002485080?}, {0xc001cd26c0?, 0x5836fc0?, 0x0?}, 0xc002707c50, {0xc001cb16c0?, 0x70?, 0xc000697400?}, 0xc001fdee20, ...)
2024-09-18 15:42:40.755		/root/milvus/internal/querynodev2/segments/result.go:696 +0x58 fp=0xc002707bf0 sp=0xc002707b70 pc=0x4d15618
2024-09-18 15:42:40.755	github.com/milvus-io/milvus/internal/querynodev2/segments.(*defaultLimitReducerSegcore).Reduce(0xc002485080?, {0x6044460?, 0xc002485080}, {0xc001cd26c0?, 0x800?, 0x64817332e800001?}, {0xc001cb16c0?, 0x1?, 0xc004583bf0?}, 0xc001fdee20)
2024-09-18 15:42:40.755		/root/milvus/internal/querynodev2/segments/default_limit_reducer.go:54 +0x15a fp=0xc002707c90 sp=0xc002707bf0 pc=0x4d0e55a
2024-09-18 15:42:40.755	github.com/milvus-io/milvus/internal/querynodev2/tasks.(*QueryTask).Execute(0xc003821090)
2024-09-18 15:42:40.755		/root/milvus/internal/querynodev2/tasks/query_task.go:132 +0x5c8 fp=0xc002707e88 sp=0xc002707c90 pc=0x4d91188
2024-09-18 15:42:40.755	github.com/milvus-io/milvus/internal/querynodev2/tasks.(*scheduler).exec.func1()
2024-09-18 15:42:40.755		/root/milvus/internal/querynodev2/tasks/concurrent_safe_scheduler.go:237 +0x16f fp=0xc002707f28 sp=0xc002707e88 pc=0x4d8f8ef
2024-09-18 15:42:40.755	github.com/milvus-io/milvus/pkg/util/conc.(*Pool[...]).Submit.func1()
2024-09-18 15:42:40.755		/root/milvus/pkg/util/conc/pool.go:81 +0xb3 fp=0xc002707f88 sp=0xc002707f28 pc=0x4cfa333
2024-09-18 15:42:40.755	github.com/panjf2000/ants/v2.(*goWorker).run.func1()
2024-09-18 15:42:40.755		/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.2/worker.go:67 +0x8d fp=0xc002707fe0 sp=0xc002707f88 pc=0x3af5ded
2024-09-18 15:42:40.755	runtime.goexit()
2024-09-18 15:42:40.755		/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc002707fe8 sp=0xc002707fe0 pc=0x1e91441
2024-09-18 15:42:40.755	created by github.com/panjf2000/ants/v2.(*goWorker).run in goroutine 431
2024-09-18 15:42:40.755		/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.2/worker.go:48 +0x5c
```

**Comment by chyezh** [comment]
fixed by #36274
