### ISSUE TITLE
[Bug]: [Nightly] Insert inconsistent will not raise exception

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#36396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 89397d1
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Insert inconsistent will not raise exception.
```
[pytest : test]     @pytest.mark.tags(CaseLabel.L2)
[pytest : test]     def test_insert_inconsistent_data(self):
[pytest : test]         """
[pytest : test]         target: test insert with inconsistent data
[pytest : test]         method: insert with data that same field has different type data
[pytest : test]         expected: raise exception
[pytest : test]         """
[pytest : test]         c_name = cf.gen_unique_str(prefix)
[pytest : test]         collection_w = self.init_collection_wrap(name=c_name)
[pytest : test]         data = cf.gen_default_list_data(nb=100)
[pytest : test]         data[0][1] = 1.0
[pytest : test]         error = {ct.err_code: 999,
[pytest : test]                  ct.err_msg: "The Input data type is inconsistent with defined schema, {%s} field should be a int64, "
[pytest : test]                              "but got a {<class 'int'>} instead." % ct.default_int64_field_name}
[pytest : test] >       collection_w.insert(data, check_task=CheckTasks.err_res, check_items=error)

[pytest : test] [2024-09-19 19:22:17 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [[0      0
[pytest : test] 1      1
[pytest : test] 2      2
[pytest : test] 3      3
[pytest : test] 4      4
[pytest : test]       ..
[pytest : test] 95    95
[pytest : test] 96    96
[pytest : test] 97    97
[pytest : test] 98    98
[pytest : test] 99    99
[pytest : test] Length: 100, dtype: int64, 0      0.0
[pytest : test] 1      1.0
[pytest : test] 2      2.0
[pytest : test] 3      3.0
[pytest : test] 4      4.0
[pytest : test]       ... 
[pytest : test] 95    95.0
[pytest : test] 96    96.0
[pytest : test] 97    97.0
[pytest : test] 98    98.0
[pytest : test] 99    99.0
[pytest : test] Length: 100, dtype: float32, 0      0
[pytest : test] 1      1
[pytest : test] 2   ......, kwargs: {'timeout': 180} (api_request.py:62)
[pytest : test] [2024-09-19 19:22:17 - DEBUG - ci_test]: (api_response) : (insert count: 100, delete count: 0, upsert count: 0, timestamp: 452663374759067660, success count: 100, err count: 0  (api_request.py:37)
```

### Expected Behavior

report error

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI(new)/detail/master/122/pipeline/163/
2. log: [artifacts-milvus-standalone-ms-master-122-py-n-122-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI(new)/job/master/122/artifact/artifacts-milvus-standalone-ms-master-122-py-n-122-e2e-logs.tar.gz)
3. failed case: [gw2] [ 23%] FAILED testcases/test_insert.py::TestInsertParams::test_insert_inconsistent_data

**Comment by yanliang567** [comment]
@NicoYuan1986  this could be a test framework issue, as I updated the cf.gen_default_list_data() a few days ago. please help to fix it.  Please free to LMK if you need any help.

/assign @NicoYuan1986 
/unassign

**Comment by NicoYuan1986** [comment]
I try to insert `1.0` to int64 field. It succeeds now. the type of `1.0` is considered int64.
It is unexpected. Before, an error would be raised.

Then I try to insert `1.1` to int64 field. It failed now. the type of `1.1` is considered float64.
It is expected. But the error message is not clear.
```
[2024-09-24 10:31:32 - ERROR - pymilvus.decorators]: Unexpected error: [batch_insert], <built-in method item of numpy.ndarray object at 0x17b131ad0> returned a result with an exception set, <Time: {'RPC start': '2024-09-24 10:31:32.321284', 'Exception': '2024-09-24 10:31:32.321675'}> (decorators.py:164)
[2024-09-24 10:31:32 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 143, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 182, in handler
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 124, in handler
    raise e from e
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 87, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 582, in batch_insert
    raise err from err
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 565, in batch_insert
    request = self._prepare_batch_insert_request(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 549, in _prepare_batch_insert_request
    else Prepare.batch_insert_param(collection_name, entities, partition_name, fields_info)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/client/prepare.py", line 537, in batch_insert_param
    return cls._parse_batch_request(request, entities, fields_info, location)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/client/prepare.py", line 513, in _parse_batch_request
    field_data = entity_helper.entity_to_field_data(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/client/entity_helper.py", line 340, in entity_to_field_data
    field_data.scalars.long_data.data.extend(entity.get("values"))
SystemError: <built-in method item of numpy.ndarray object at 0x17b131ad0> returned a result with an exception set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/zilliz/nico/milvus/tests/python_client/utils/api_request.py", line 32, in inner_wrapper
    res = func(*args, **_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/nico/milvus/tests/python_client/utils/api_request.py", line 63, in api_request
    return func(*arg, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/orm/collection.py", line 513, in insert
    return conn.batch_insert(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 165, in handler
    raise MilvusException(message=f"Unexpected error, message=<{e!s}>") from e
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Unexpected error, message=<<built-in method item of numpy.ndarray object at 0x17b131ad0> returned a result with an exception set>)>
 (api_request.py:45)
[2024-09-24 10:31:32 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Unexpected error, message=<<built-in method item of numpy.ndarray object at 0x17b131ad0> returned a result with an exception set>)> (api_request.py:46)
```
pymilvus version:  pymilvus-2.5.0rc80
