### ISSUE TITLE
[Bug]: [null & default] Insert rows failed with error "the length of valid_data of field(flat) is wrong: invalid parameter[expected=1][actual=0]" when insert valid value to default value field

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#36486]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20240920-6e430bd4
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):   all 
- SDK version(e.g. pymilvus v2.0.0rc2): 2.5.0rc80
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Insert rows failed with error "the length of valid_data of field(flat) is wrong: invalid parameter[expected=1][actual=0]" when insert valid value to default value field

```
RPC error: [insert_rows], <MilvusException: (code=1100, message=the length of valid_data of field(flat) is wrong: invalid parameter[expected=1][actual=0])>, <Time:{'RPC start': '2024-09-25 11:25:29.261927', 'RPC error': '2024-09-25 11:25:29.436065'}>
Traceback (most recent call last):
  File "./default_rows.py", line 24, in <module>
    collection.insert(data={"id": 4, "vector": [7,8,9], "flat": 3})
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 507, in insert
    return conn.insert_rows(
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 141, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 137, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 176, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 116, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 86, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 496, in insert_rows
    check_status(resp.status)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/utils.py", line 63, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1100, message=the length of valid_data of field(flat) is wrong: invalid parameter[expected=1][actual=0])>
```

### Expected Behavior

Insert successfully to the default value field

### Steps To Reproduce

```python
from pymilvus import CollectionSchema, FieldSchema
from pymilvus import Collection
from pymilvus import connections
from pymilvus import DataType
from pymilvus import Partition
from pymilvus import utility
import json
import random


connections.connect()

dim = 3
schema = CollectionSchema(fields=[
    FieldSchema(name="id", dtype=DataType.INT64, is_primary=True, auto_id=False),
    FieldSchema(name="vector", dtype=DataType.FLOAT_VECTOR, dim=3),
    FieldSchema(name="flat", dtype=DataType.INT64, default_value=100),
])

collection = Collection("test_binbin_123", schema=schema)

collection.insert(data={"id": 4, "vector": [7,8,9], "flat": 3})
```

**Comment by smellthemoon** [comment]
pr merged, plz check it. @binbinlv

**Comment by binbinlv** [comment]
Verified and fixed:

pymilvus:2.5.0rc88
milvus: master-20241011-3fe0f829-amd64

results:

```
>>> dim = 3
>>> schema = CollectionSchema(fields=[
...     FieldSchema(name="id", dtype=DataType.INT64, is_primary=True, auto_id=False),
...     FieldSchema(name="vector", dtype=DataType.FLOAT_VECTOR, dim=3),
...     FieldSchema(name="flat", dtype=DataType.INT64, default_value=100),
... ])
>>>
>>> collection = Collection("test_binbin_123", schema=schema)
>>>
>>> collection.insert(data={"id": 4, "vector": [7,8,9], "flat": 3})
(insert count: 1, delete count: 0, upsert count: 0, timestamp: 453149451530797060, success count: 1, err count: 0
```
