### ISSUE TITLE
[Bug]: Search failed reporting `channel not subscribed: channel lacks` (open all mmap)

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#36583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20240927-7c2cb8c5-amd64 
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Search failed reporting `channel not subscribed: channel lacks` (open all mmap)
```
[2024-09-27T08:46:26.500Z] [2024-09-27 07:03:56 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=503, message=failed to search: channel not subscribed: channel lacks[channel=by-dev-rootcoord-dml_10_452832168726603420v0]: channel not available[channel=by-dev-rootcoord-dml_10_452832168726603420v0])>, <Time:{'RPC start': '2024-09-27 07:03:56.369301', 'RPC error': '2024-09-27 07:03:56.372899'}> (decorators.py:140)
[2024-09-27T08:46:26.500Z] [2024-09-27 07:03:56 - ERROR - ci_test]: Traceback (most recent call last):
[2024-09-27T08:46:26.500Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper
[2024-09-27T08:46:26.500Z]     res = func(*args, **_kwargs)
[2024-09-27T08:46:26.500Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request
[2024-09-27T08:46:26.500Z]     return func(*arg, **kwargs)
[2024-09-27T08:46:26.500Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 801, in search
[2024-09-27T08:46:26.500Z]     resp = conn.search(
[2024-09-27T08:46:26.500Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 141, in handler
[2024-09-27T08:46:26.500Z]     raise e from e
[2024-09-27T08:46:26.500Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 137, in handler
[2024-09-27T08:46:26.500Z]     return func(*args, **kwargs)
[2024-09-27T08:46:26.500Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 176, in handler
[2024-09-27T08:46:26.500Z]     return func(self, *args, **kwargs)
[2024-09-27T08:46:26.500Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 116, in handler
[2024-09-27T08:46:26.500Z]     raise e from e
[2024-09-27T08:46:26.500Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 86, in handler
[2024-09-27T08:46:26.500Z]     return func(*args, **kwargs)
[2024-09-27T08:46:26.500Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 800, in search
[2024-09-27T08:46:26.500Z]     return self._execute_search(request, timeout, round_decimal=round_decimal, **kwargs)
[2024-09-27T08:46:26.500Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 741, in _execute_search
[2024-09-27T08:46:26.500Z]     raise e from e
[2024-09-27T08:46:26.500Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 734, in _execute_search
[2024-09-27T08:46:26.500Z]     check_status(response.status)
[2024-09-27T08:46:26.500Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/utils.py", line 63, in check_status
[2024-09-27T08:46:26.500Z]     raise MilvusException(status.code, status.reason, status.error_code)
[2024-09-27T08:46:26.500Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=503, message=failed to search: channel not subscribed: channel lacks[channel=by-dev-rootcoord-dml_10_452832168726603420v0]: channel not available[channel=by-dev-rootcoord-dml_10_452832168726603420v0])>
[2024-09-27T08:46:26.500Z]  (api_request.py:45)
[2024-09-27T08:46:26.500Z] [2024-09-27 07:03:56 - ERROR - ci_test]: (api_response) : <MilvusException: (code=503, message=failed to search: channel not subscribed: channel lacks[channel=by-dev-rootcoord-dml_10_452832168726603420v0]: channel not available[channel=by-dev-rootcoord-dml_10_452832168726603420v0])> (api_request.py:46)
```

### Expected Behavior

pass

### Milvus Log

1. link: https://qa-jenkins.milvus.io/blue/organizations/jenkins/existing-milvus/detail/existing-milvus/7/pipeline/
2. failed case: 
```
[2024-09-27T07:04:01.127Z] [gw1] [ 41%] FAILED test_query.py::TestQueryTextMatch::test_query_text_match_with_multi_lang 
[2024-09-27T07:04:01.127Z] [gw2] [ 41%] FAILED test_query.py::TestQueryParams::test_query_pagination_with_expression[100-int64 in [300/2, 900%40, -10*30+800, (100+200)*2] or float in [+3**6, 2**10/2]] 
[2024-09-27T07:04:01.127Z] [gw0] [ 41%] FAILED test_query.py::TestQueryParams::test_query_auto_id_collection 
[2024-09-27T07:04:01.127Z] test_query.py::TestQueryParams::test_query_pagination_with_expression[100-float <= -4**5/2 && float > 500-1 && float != 500/2+260] 
[2024-09-27T07:04:01.127Z] test_query.py::TestQueryParams::test_query_with_dup_primary_key[8-1] 
[2024-09-27T07:04:01.127Z] [gw4] [ 41%] FAILED test_mix_scenes.py::TestGroupSearch::test_search_group_by_supported_scalars[INT8] 
[2024-09-27T07:04:01.127Z] [gw4] [ 41%] FAILED test_mix_scenes.py::TestGroupSearch::test_search_group_by_supported_scalars[INT64] 
[2024-09-27T07:04:01.127Z] [gw4] [ 41%] FAILED test_mix_scenes.py::TestGroupSearch::test_search_group_by_supported_scalars[BOOL] 
[2024-09-27T07:04:01.127Z] [gw4] [ 41%] FAILED test_mix_scenes.py::TestGroupSearch::test_search_group_by_supported_scalars[VARCHAR] 
[2024-09-27T07:04:01.127Z] [gw4] [ 41%] FAILED test_mix_scenes.py::TestGroupSearch::test_search_pagination_group_by 
```

**Comment by NicoYuan1986** [comment]
not reproduced recently
