### ISSUE TITLE
[Bug]: Using GPU_IVF_PQ and IP wtih the same parameters as IVF_PQ brings errors 

### ISSUE THREAD

**Issue by qwevdb** [milvus-io/milvus#36606]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvus v2.4.12-gpu
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq   
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.4.5
- OS(Ubuntu or CentOS): Ubuntu 24.04 LTS
- CPU/Memory: Intel Core i7-11700 / 64G
- GPU: NVIDIA GeForce RTX 4090
- Others:
```

### Current Behavior

Using the IVF_PQ index and IP metric can normally output results, while using the GPU_IVF_PQ index and IP metric with the same parameters produce errors.

### Expected Behavior

Both IVF_PQ and GPU_IVF_PQ index with IP metric and the same parameters can produce the same results.

### Steps To Reproduce

1. run python script as follow 

 ```python
import time
from pymilvus import Collection, connections, FieldSchema, CollectionSchema, DataType, utility
import numpy as np

FLOAT_MAX = 5000
DATA_INT_MAX = 100

numpy_random = np.random.default_rng(0)
alias = "bench"
collection_name = "Benchmark"
client = connections.connect(
    alias=alias,
    host="localhost",
    port="19530"
)
if utility.has_collection(collection_name, using=alias):
    collection = Collection(name=collection_name, using=alias)
    collection.drop()
    time.sleep(2)  
    
dim = 943
id = FieldSchema(name='id', dtype=DataType.INT64, is_primary=True)
vector = FieldSchema(name='vector', dtype=DataType.FLOAT_VECTOR, dim=dim)
field_1 = FieldSchema(name='field_1', dtype=DataType.INT64)
field_2 = FieldSchema(name='field_2', dtype=DataType.INT64)
fields = [id, vector, field_1, field_2]
schema = CollectionSchema(fields=fields, description=alias)
collection = Collection(
    name=collection_name,
    schema=schema,
    using=alias,
)
index_params = {'index_type': 'IVF_PQ', 'params': {'nlist': 50675, 'm': 1, 'max_empty_result_buckets': 148}, 'metric_type': 'IP'}
# index_params = {'index_type': 'GPU_IVF_PQ', 'params': {'nlist': 50675, 'm': 1, 'max_empty_result_buckets': 148}, 'metric_type': 'IP'}
collection.create_index("vector", index_params, timeout=100)

dataset = []
number = 2358
for i in range(0, number + 0):
    vector = numpy_random.random((1, dim))
    data = {
        'id': i,
        'vector': list(vector[0]),
        'field_1': numpy_random.integers(-DATA_INT_MAX, DATA_INT_MAX),
        'field_2': numpy_random.integers(-DATA_INT_MAX, DATA_INT_MAX)
    }
    dataset.append(data)
collection.upsert(dataset)
collection.flush()
collection.load()

dataset = []
number = 1248
for i in range(2358,number + 2358):
    vector = numpy_random.random((1, dim))
    data = {
        'id': i,
        'vector': list(vector[0]),
        'field_1': numpy_random.integers(-DATA_INT_MAX, DATA_INT_MAX),
        'field_2': numpy_random.integers(-DATA_INT_MAX, DATA_INT_MAX)
    }
    dataset.append(data)
collection.insert(dataset)
collection.flush()
collection.load()

vector = numpy_random.random((1, dim))
query_vector = list(vector[0])
iterator = collection.search_iterator(
       data=[query_vector],
       anns_field="vector",
       param={"metric_type": "IP", "params": {'nprobe': 49640}},
       limit=6,
       expr=None,
       batch_size=1453,
       timeout=100
    )
res1 = []
while True:
    result = iterator.next()
    if not result:
        iterator.close()
        break

    res1.extend(result)
collection.release()
collection.drop_index()
collection.flush()
print(res1)
collection.drop()
```
result:
``` bash
[id: 2932, distance: 258.3150634765625, entity: {}, id: 2811, distance: 255.984619140625, entity: {}, id: 2622, distance: 254.09034729003906, entity: {}, id: 2530, distance: 253.17347717285156, entity: {}, id: 2929, distance: 252.6639404296875, entity: {}, id: 3411, distance: 252.10018920898438, entity: {}]
```

2. change 'index_type': 'IVF_PQ' to 'index_type': 'GPU_IVF_PQ' in index_params and run again

result:
``` bash
RPC error: [search], <MilvusException: (code=65535, message=fail to search on QueryNode 1: worker(1) query failed:  => failed to search: out of range in json: Out of range in json: param 'k' (1453) should be in range [1, 1024] at /workspace/source/internal/core/src/index/VectorMemIndex.cpp:625
)>, <Time:{'RPC start': '2024-09-29 22:51:44.791392', 'RPC error': '2024-09-29 22:51:45.395568'}>
Traceback (most recent call last):
  File "/home/xxx/Desktop/vdb/milvus/vdb-test/./log/milvus/test_bug253_B.py", line 68, in <module>
    iterator = collection.search_iterator(
  File "/root/anaconda3/envs/milvus/lib/python3.10/site-packages/pymilvus/orm/collection.py", line 976, in search_iterator
    return SearchIterator(
  File "/root/anaconda3/envs/milvus/lib/python3.10/site-packages/pymilvus/orm/iterator.py", line 334, in __init__
    self.__init_search_iterator()
  File "/root/anaconda3/envs/milvus/lib/python3.10/site-packages/pymilvus/orm/iterator.py", line 337, in __init_search_iterator
    init_page = self.__execute_next_search(self._param, self._expr, False)
  File "/root/anaconda3/envs/milvus/lib/python3.10/site-packages/pymilvus/orm/iterator.py", line 542, in __execute_next_search
    res = self._conn.search(
  File "/root/anaconda3/envs/milvus/lib/python3.10/site-packages/pymilvus/decorators.py", line 148, in handler
    raise e from e
  File "/root/anaconda3/envs/milvus/lib/python3.10/site-packages/pymilvus/decorators.py", line 144, in handler
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/milvus/lib/python3.10/site-packages/pymilvus/decorators.py", line 183, in handler
    return func(self, *args, **kwargs)
  File "/root/anaconda3/envs/milvus/lib/python3.10/site-packages/pymilvus/decorators.py", line 123, in handler
    raise e from e
  File "/root/anaconda3/envs/milvus/lib/python3.10/site-packages/pymilvus/decorators.py", line 87, in handler
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/milvus/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 801, in search
    return self._execute_search(request, timeout, round_decimal=round_decimal, **kwargs)
  File "/root/anaconda3/envs/milvus/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 742, in _execute_search
    raise e from e
  File "/root/anaconda3/envs/milvus/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 735, in _execute_search
    check_status(response.status)
  File "/root/anaconda3/envs/milvus/lib/python3.10/site-packages/pymilvus/client/utils.py", line 63, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=fail to search on QueryNode 1: worker(1) query failed:  => failed to search: out of range in json: Out of range in json: param 'k' (1453) should be in range [1, 1024] at /workspace/source/internal/core/src/index/VectorMemIndex.cpp:625
)>
```

**Comment by xiaofan-luan** [comment]
GPU index has limitation of as larget as 1024 topk

**Comment by yanliang567** [comment]
Let's track the issue in #36608
