### ISSUE TITLE
[Bug]: Hybrid Search Fails with Sparse Vector Assertion Error

### ISSUE THREAD

**Issue by SeeknnDestroy** [milvus-io/milvus#36640]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.4.0
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): 2.7.2
- OS(Ubuntu or CentOS): ubuntu
- CPU/Memory: 16GB
- GPU: 
- Others:
```

### Current Behavior

When I perform a hybrid search using both dense and sparse vectors, I encounter the following error message:

```plaintext
ERROR:pymilvus.decorators:RPC error: [hybrid_search], <MilvusException: (code=65535, message=fail to hybrid search on QueryNode 6: worker(6) query failed: Assert "!datatype_is_sparse_vector(type_)" at /go/src/github.com/milvus-io/milvus/internal/core/src/common/FieldMeta.h:303
 => should not attempt to get_sizeof() of a sparse vector from schema)>, <Time:{'RPC start': '2024-10-03 18:02:48.272892', 'RPC error': '2024-10-03 18:02:49.111750'}>
ERROR:__main__:Hybrid search failed: <MilvusException: (code=65535, message=fail to hybrid search on QueryNode 6: worker(6) query failed: Assert "!datatype_is_sparse_vector(type_)" at /go/src/github.com/milvus-io/milvus/internal/core/src/common/FieldMeta.h:303
 => should not attempt to get_sizeof() of a sparse vector from schema)>
Traceback (most recent call last):
  File "/home/seeknndestroy/jetlink/bitbucket/jetlink-ai-api/hybrid_search.py", line 282, in <module>
    main()
  File "/home/seeknndestroy/jetlink/bitbucket/jetlink-ai-api/hybrid_search.py", line 261, in main
    search_results = hybrid_search_in_milvus(
  File "/home/seeknndestroy/jetlink/bitbucket/jetlink-ai-api/hybrid_search.py", line 209, in hybrid_search_in_milvus
    raise e
  File "/home/seeknndestroy/jetlink/bitbucket/jetlink-ai-api/hybrid_search.py", line 197, in hybrid_search_in_milvus
    results = collection.hybrid_search(
  File "/home/seeknndestroy/miniconda3/envs/jetlink/lib/python3.10/site-packages/pymilvus/orm/collection.py", line 936, in hybrid_search
    resp = conn.hybrid_search(
  File "/home/seeknndestroy/miniconda3/envs/jetlink/lib/python3.10/site-packages/pymilvus/decorators.py", line 147, in handler
    raise e from e
  File "/home/seeknndestroy/miniconda3/envs/jetlink/lib/python3.10/site-packages/pymilvus/decorators.py", line 143, in handler
    return func(*args, **kwargs)
  File "/home/seeknndestroy/miniconda3/envs/jetlink/lib/python3.10/site-packages/pymilvus/decorators.py", line 182, in handler
    return func(self, *args, **kwargs)
  File "/home/seeknndestroy/miniconda3/envs/jetlink/lib/python3.10/site-packages/pymilvus/decorators.py", line 122, in handler
    raise e from e
  File "/home/seeknndestroy/miniconda3/envs/jetlink/lib/python3.10/site-packages/pymilvus/decorators.py", line 87, in handler
    return func(*args, **kwargs)
  File "/home/seeknndestroy/miniconda3/envs/jetlink/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 843, in hybrid_search
    return self._execute_hybrid_search(
  File "/home/seeknndestroy/miniconda3/envs/jetlink/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 754, in _execute_hybrid_search
    raise e from e
  File "/home/seeknndestroy/miniconda3/envs/jetlink/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 747, in _execute_hybrid_search
    check_status(response.status)
  File "/home/seeknndestroy/miniconda3/envs/jetlink/lib/python3.10/site-packages/pymilvus/client/utils.py", line 60, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=fail to hybrid search on QueryNode 6: worker(6) query failed: Assert "!datatype_is_sparse_vector(type_)" at /go/src/github.com/milvus-io/milvus/internal/core/src/common/FieldMeta.h:303
 => should not attempt to get_sizeof() of a sparse vector from schema)>
```

### Expected Behavior

When I perform a hybrid search using both dense and sparse vectors, the search should execute successfully and return relevant results without any assertion errors.

---

### Reproducible Code Example

```python
from typing import List, Dict
from pymilvus import connections, Collection, DataType, FieldSchema, CollectionSchema, utility, AnnSearchRequest, WeightedRanker
from sklearn.feature_extraction.text import TfidfVectorizer
import logging

# ==============================
# Configuration and Initialization
# ==============================

# Initialize logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Initialize TfidfVectorizer and fit it on the corpus
corpus = [
    "The quick brown fox jumps over the lazy dog.",
    "FastAPI is a modern, fast (high-performance) web framework for building APIs.",
    "Milvus is an open-source vector database for scalable similarity search.",
    # Add more documents as needed
]
vectorizer = TfidfVectorizer()
vectorizer.fit(corpus)

# ==============================
# Helper Functions
# ==============================

def generate_dense_embedding(text: str) -> List[float]:
    """
    Generates a dense embedding for the given text using OpenAI's Azure API.
    """
    # Replace with your actual embedding generation logic
    return [0.1, 0.2, 0.3, 0.4]  # Placeholder embedding

def generate_sparse_vector(text: str, vectorizer: TfidfVectorizer) -> Dict[int, float]:
    """
    Generates a sparse vector for the given text using TfidfVectorizer.
    Returns a dictionary {index: value}.
    """
    vector = vectorizer.transform([text])
    coo = vector.tocoo()
    sparse_vector = {int(index): float(value) for index, value in zip(coo.col, coo.data)}
    return sparse_vector

def setup_milvus_collection(
    collection_name: str,
    dense_dim: int,
    metric_dense: str = "L2",
    metric_sparse: str = "IP"
) -> Collection:
    """
    Creates a new Milvus collection with the specified schema and indices.
    If the collection already exists, it will be dropped and recreated.
    """
    # Define fields
    fields = [
        FieldSchema(name="pk", dtype=DataType.VARCHAR, is_primary=True, auto_id=True, max_length=100),
        FieldSchema(name="text", dtype=DataType.VARCHAR, max_length=512),
        FieldSchema(name="sparse_vector", dtype=DataType.SPARSE_FLOAT_VECTOR),
        FieldSchema(name="dense_vector", dtype=DataType.FLOAT_VECTOR, dim=dense_dim),
    ]
    
    schema = CollectionSchema(fields, description="Hybrid search collection with dense and sparse vectors")
    
    # Drop collection if it exists
    if utility.has_collection(collection_name):
        logger.info(f"Collection '{collection_name}' already exists. Dropping it.")
        utility.drop_collection(collection_name)
    
    # Create collection
    collection = Collection(name=collection_name, schema=schema, consistency_level="Strong")
    
    # Create indices
    sparse_index_params = {
        "index_type": "SPARSE_INVERTED_INDEX",
        "metric_type": metric_sparse,
        "params": {"nlist": 128}
    }
    logger.info("Creating index for 'sparse_vector'...")
    collection.create_index(field_name="sparse_vector", index_params=sparse_index_params)
    
    dense_index_params = {
        "index_type": "IVF_FLAT",
        "metric_type": metric_dense,
        "params": {"nlist": 128}
    }
    logger.info("Creating index for 'dense_vector'...")
    collection.create_index(field_name="dense_vector", index_params=dense_index_params)
    
    # Load collection into memory
    collection.load()
    
    logger.info(f"Collection '{collection_name}' is set up with indices.")
    return collection

def insert_data_into_milvus(
    collection: Collection,
    texts: List[str],
    dense_vectors: List[List[float]],
    sparse_vectors: List[Dict[int, float]]
):
    """
    Inserts data into the Milvus collection.
    """
    try:
        entities = [
            texts,
            sparse_vectors,
            dense_vectors
        ]
        collection.insert(entities)
        logger.info(f"Inserted {len(texts)} entities into the collection.")
        collection.flush()
    except Exception as e:
        logger.error(f"Failed to insert data into Milvus: {e}")
        raise e

def hybrid_search_in_milvus(
    collection: Collection,
    dense_vector: List[float],
    sparse_vector: Dict[int, float],
    limit: int,
    output_fields: List[str],
    metric_dense: str = "L2",
    metric_sparse: str = "IP"
) -> List[Dict]:
    """
    Performs hybrid search on the Milvus collection using dense and sparse vectors.
    """
    try:
        # Define search parameters
        search_param_dense = {
            'metric_type': metric_dense,
            'params': {'nprobe': 10}
        }
        search_param_sparse = {
            'metric_type': metric_sparse,
            'params': {'drop_ratio_search': 0.2}
        }

        # Create ANN search requests
        dense_search_request = AnnSearchRequest(
            data=[dense_vector],
            anns_field="dense_vector",
            param=search_param_dense,
            limit=limit
        )
        sparse_search_request = AnnSearchRequest(
            data=[sparse_vector],
            anns_field="sparse_vector",
            param=search_param_sparse,
            limit=limit
        )

        # Combine search requests
        search_requests = [dense_search_request, sparse_search_request]

        # Define ranker weights
        ranker = WeightedRanker(1.0, 0.7)

        # Perform hybrid search
        results = collection.hybrid_search(
            search_requests,
            reranker=ranker,
            limit=limit,
            output_fields=output_fields
        )

        # Extract results
        top_results = []
        for hit in results:
            entity = hit.entity
            result = {field: entity.get(field, None) for field in output_fields}
            top_results.append(result)
        
        return top_results

    except Exception as e:
        logger.error(f"Hybrid search failed: {e}")
        raise e

# ==============================
# Main Function
# ==============================

def main():
    # Connect to Milvus
    connections.connect(
        host="10.10.220.9",  # Replace with your Milvus host
        port="19530",         # Replace with your Milvus port
        timeout=60
    )
    logger.info("Connected to Milvus.")

    # Generate a dense embedding to determine its dimension
    example_dense = generate_dense_embedding(corpus[0])
    dense_dim = len(example_dense)
    logger.info(f"Dense embedding dimension: {dense_dim}")

    # Setup Milvus collection
    collection = setup_milvus_collection(
        collection_name="test",  # Collection name as per user instruction
        dense_dim=dense_dim
    )

    # Prepare data for insertion
    texts = corpus  # Replace with your actual data as needed
    dense_vectors = [generate_dense_embedding(text) for text in texts]
    sparse_vectors = [generate_sparse_vector(text, vectorizer) for text in texts]

    # Insert data into Milvus
    insert_data_into_milvus(
        collection=collection,
        texts=texts,
        dense_vectors=dense_vectors,
        sparse_vectors=sparse_vectors
    )

    # Define search query
    query_text = "What is Milvus known for"  # Example query
    logger.info(f"Query text: {query_text}")

    # Generate embeddings for the query
    query_dense = generate_dense_embedding(query_text)
    query_sparse = generate_sparse_vector(query_text, vectorizer)

    # Perform hybrid search
    output_fields = ["pk", "text"]  # Fields to retrieve
    search_limit = 10  # Number of top results to retrieve
    search_results = hybrid_search_in_milvus(
        collection=collection,
        dense_vector=query_dense,
        sparse_vector=query_sparse,
        limit=search_limit,
        output_fields=output_fields
    )

    # Display the search results
    logger.info("Search Results:")
    for idx, result in enumerate(search_results, start=1):
        print(f"Result {idx}:")
        for field, value in result.items():
            print(f"{field}: {value}")
        print()

    # Disconnect from Milvus
    connections.disconnect()
    logger.info("Disconnected from Milvus.")

if __name__ == "__main__":
    main()
```

### Anything else?

I have followed the documentation from official milvus hybrid search example with sparse and dense embeddings, but only used Azure for dense, and TfidfVectorizer for sparse vectors instead: https://milvus.io/docs/hybrid_search_with_milvus.md

**Comment by SeeknnDestroy** [comment]
After further investigation, I discovered that the issue was caused by generating empty sparse vectors due to a small corpus and out-of-scope query strings. By ensuring that sparse vectors are properly generated, the hybrid search now works as expected. Since this was an implementation bug on my end, I’m closing the issue.

I have also used `MilvusClient.hybrid_search()` instead.
