### ISSUE TITLE
[Bug]: When Milvus recovers from a datanode pod failure, some collections may experience timeouts (180s) during flushing.

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#36709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4-20241008-f1080665-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```

[2024-10-08T20:35:16.197Z] [2024-10-08 20:26:17 - DEBUG - ci_test]: (api_request)  : [Connections.connect] args: ['default', '', '', 'default', ''], kwargs: {'host': '10.255.181.79', 'port': 19530} (api_request.py:62)

[2024-10-08T20:35:16.197Z] [2024-10-08 20:26:17 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-10-08T20:35:16.197Z] [2024-10-08 20:26:17 - DEBUG - ci_test]: (api_request)  : [Connections.has_connection] args: ['default'], kwargs: {} (api_request.py:62)

[2024-10-08T20:35:16.197Z] [2024-10-08 20:26:17 - DEBUG - ci_test]: (api_response) : True  (api_request.py:37)

[2024-10-08T20:35:16.197Z] [2024-10-08 20:26:17 - DEBUG - ci_test]: (api_request)  : [Collection] args: ['Checker__WmE2CbEL', {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}, {'name': 'varchar', 'description': '', 'type': <DataType......, kwargs: {'consistency_level': 'Strong'} (api_request.py:62)

[2024-10-08T20:35:16.197Z] [2024-10-08 20:26:17 - DEBUG - ci_test]: (api_response) : <Collection>:

[2024-10-08T20:35:16.197Z] -------------

[2024-10-08T20:35:16.197Z] <name>: Checker__WmE2CbEL

[2024-10-08T20:35:16.197Z] <description>: 

[2024-10-08T20:35:16.197Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}......  (api_request.py:37)

[2024-10-08T20:35:16.197Z] [2024-10-08 20:26:17 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-10-08T20:35:16.197Z] [2024-10-08 20:29:17 - WARNING - pymilvus.decorators]: Retry timeout: 180s (decorators.py:107)

[2024-10-08T20:35:16.197Z] [2024-10-08 20:29:17 - ERROR - pymilvus.decorators]: RPC error: [flush], <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for flush timeout, collection: Checker__WmE2CbEL, flusht_ts: 453094716909289490)>, <Time:{'RPC start': '2024-10-08 20:26:17.666243', 'RPC error': '2024-10-08 20:29:17.775533'}> (decorators.py:147)

[2024-10-08T20:35:16.197Z] [2024-10-08 20:29:17 - ERROR - ci_test]: Traceback (most recent call last):

[2024-10-08T20:35:16.197Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2024-10-08T20:35:16.197Z]     res = func(*args, **_kwargs)

[2024-10-08T20:35:16.197Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2024-10-08T20:35:16.197Z]     return func(*arg, **kwargs)

[2024-10-08T20:35:16.197Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 318, in flush

[2024-10-08T20:35:16.197Z]     conn.flush([self.name], timeout=timeout, **kwargs)

[2024-10-08T20:35:16.197Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 148, in handler

[2024-10-08T20:35:16.197Z]     raise e from e

[2024-10-08T20:35:16.197Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 144, in handler

[2024-10-08T20:35:16.197Z]     return func(*args, **kwargs)

[2024-10-08T20:35:16.197Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 183, in handler

[2024-10-08T20:35:16.197Z]     return func(self, *args, **kwargs)

[2024-10-08T20:35:16.197Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 108, in handler

[2024-10-08T20:35:16.197Z]     raise MilvusException(

[2024-10-08T20:35:16.197Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for flush timeout, collection: Checker__WmE2CbEL, flusht_ts: 453094716909289490)>
```

![image](https://github.com/user-attachments/assets/265fa2fa-fb05-400d-a351-0445fd640450)

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-for-release-cron/detail/chaos-test-for-release-cron/16724/pipeline

log:
[artifacts-datanode-pod-failure-16724-server-logs.tar.gz](https://github.com/user-attachments/files/17303017/artifacts-datanode-pod-failure-16724-server-logs.tar.gz)

cluster: cluster
ns: chaos-testing
pod:
```
[2024-10-08T20:25:22.385Z] + kubectl get pods -o wide

[2024-10-08T20:25:22.386Z] + grep datanode-pod-failure-16724

[2024-10-08T20:25:22.641Z] datanode-pod-failure-16724-etcd-0                                 1/1     Running            0                31m     10.104.25.210   4am-node30   <none>           <none>

[2024-10-08T20:25:22.641Z] datanode-pod-failure-16724-etcd-1                                 1/1     Running            0                31m     10.104.34.73    4am-node37   <none>           <none>

[2024-10-08T20:25:22.641Z] datanode-pod-failure-16724-etcd-2                                 1/1     Running            0                31m     10.104.18.202   4am-node25   <none>           <none>

[2024-10-08T20:25:22.641Z] datanode-pod-failure-16724-milvus-datanode-7dc97bfc4d-5wdt5       1/1     Running            5 (8m10s ago)    31m     10.104.4.95     4am-node11   <none>           <none>

[2024-10-08T20:25:22.641Z] datanode-pod-failure-16724-milvus-datanode-7dc97bfc4d-xrfhf       1/1     Running            5 (8m10s ago)    31m     10.104.14.130   4am-node18   <none>           <none>

[2024-10-08T20:25:22.641Z] datanode-pod-failure-16724-milvus-indexnode-77d68d98c7-2vbmz      1/1     Running            2 (31m ago)      31m     10.104.34.70    4am-node37   <none>           <none>

[2024-10-08T20:25:22.641Z] datanode-pod-failure-16724-milvus-indexnode-77d68d98c7-mxvv6      1/1     Running            2 (31m ago)      31m     10.104.16.11    4am-node21   <none>           <none>

[2024-10-08T20:25:22.641Z] datanode-pod-failure-16724-milvus-indexnode-77d68d98c7-vdvgz      1/1     Running            2 (31m ago)      31m     10.104.1.126    4am-node10   <none>           <none>

[2024-10-08T20:25:22.641Z] datanode-pod-failure-16724-milvus-mixcoord-8c48db54f-82tt7        1/1     Running            2 (31m ago)      31m     10.104.1.125    4am-node10   <none>           <none>

[2024-10-08T20:25:22.641Z] datanode-pod-failure-16724-milvus-proxy-85bb5c5977-grvqc          1/1     Running            2 (31m ago)      31m     10.104.9.80     4am-node14   <none>           <none>

[2024-10-08T20:25:22.641Z] datanode-pod-failure-16724-milvus-querynode-66b4d445ff-4l849      1/1     Running            2 (31m ago)      31m     10.104.23.81    4am-node27   <none>           <none>

[2024-10-08T20:25:22.641Z] datanode-pod-failure-16724-milvus-querynode-66b4d445ff-hbc7f      1/1     Running            2 (31m ago)      31m     10.104.9.81     4am-node14   <none>           <none>

[2024-10-08T20:25:22.641Z] datanode-pod-failure-16724-milvus-querynode-66b4d445ff-k99hl      1/1     Running            2 (31m ago)      31m     10.104.19.115   4am-node28   <none>           <none>

[2024-10-08T20:25:22.641Z] datanode-pod-failure-16724-minio-0                                1/1     Running            0                31m     10.104.26.83    4am-node32   <none>           <none>

[2024-10-08T20:25:22.641Z] datanode-pod-failure-16724-minio-1                                1/1     Running            0                31m     10.104.17.33    4am-node23   <none>           <none>

[2024-10-08T20:25:22.641Z] datanode-pod-failure-16724-minio-2                                1/1     Running            0                31m     10.104.25.211   4am-node30   <none>           <none>

[2024-10-08T20:25:22.641Z] datanode-pod-failure-16724-minio-3                                1/1     Running            0                31m     10.104.18.196   4am-node25   <none>           <none>

[2024-10-08T20:25:22.641Z] datanode-pod-failure-16724-pulsar-bookie-0                        1/1     Running            0                31m     10.104.24.57    4am-node29   <none>           <none>

[2024-10-08T20:25:22.641Z] datanode-pod-failure-16724-pulsar-bookie-1                        1/1     Running            0                31m     10.104.25.212   4am-node30   <none>           <none>

[2024-10-08T20:25:22.641Z] datanode-pod-failure-16724-pulsar-bookie-init-7gvs9               0/1     Completed          0                31m     10.104.17.29    4am-node23   <none>           <none>

[2024-10-08T20:25:22.641Z] datanode-pod-failure-16724-pulsar-broker-0                        1/1     Running            0                31m     10.104.13.146   4am-node16   <none>           <none>

[2024-10-08T20:25:22.641Z] datanode-pod-failure-16724-pulsar-proxy-0                         1/1     Running            0                31m     10.104.24.52    4am-node29   <none>           <none>

[2024-10-08T20:25:22.641Z] datanode-pod-failure-16724-pulsar-pulsar-init-nd24t               0/1     Completed          0                31m     10.104.17.28    4am-node23   <none>           <none>

[2024-10-08T20:25:22.641Z] datanode-pod-failure-16724-pulsar-recovery-0                      1/1     Running            0                31m     10.104.25.200   4am-node30   <none>           <none>

[2024-10-08T20:25:22.641Z] datanode-pod-failure-16724-pulsar-zookeeper-0                     1/1     Running            0                31m     10.104.26.82    4am-node32   <none>           <none>
```

**Comment by zhuwenxing** [comment]
/assign @XuanYang-cn 
PTAL

**Comment by XuanYang-cn** [comment]
/unassign
/assign @zhuwenxing 
should be fixed, help verify plz

**Comment by zhuwenxing** [comment]
verified and passed in `2.4-20241013-44564f04-amd64`
