### ISSUE TITLE
[Bug]: If the schema is set to text match as true, using the same scheme to initialize the same collection name will result in an error on the second initialization, stating that the scheme is inconsistent.

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#36719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20241008-1fded422-amd64
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```

[2024-10-09 19:57:46 - INFO - ci_test]: [setup_method] Start setup test case test_query_text_match_with_combined_expression_for_multi_field. (client_base.py:47)
-------------------------------- live log call ---------------------------------
[2024-10-09 19:57:46 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/zilliz/workspace/milvus/tests/python_client/utils/api_request.py", line 32, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/Users/zilliz/workspace/milvus/tests/python_client/utils/api_request.py", line 63, in api_request
    return func(*arg, **kwargs)
  File "/Users/zilliz/opt/anaconda3/envs/text_match/lib/python3.10/site-packages/pymilvus/orm/collection.py", line 135, in __init__
    raise SchemaNotReadyException(message=ExceptionsMessage.SchemaInconsistent)
pymilvus.exceptions.SchemaNotReadyException: <SchemaNotReadyException: (code=1, message=The collection already exist, but the schema is not the same as the schema passed in.)>
 (api_request.py:45)
[2024-10-09 19:57:46 - ERROR - ci_test]: (api_response) : <SchemaNotReadyException: (code=1, message=The collection already exist, but the schema is not the same as the schema passed in.)> (api_request.py:46)
FAILED
testcases/test_query.py:4964 (TestQueryTextMatch.test_query_text_match_with_combined_expression_for_multi_field)
self = <test_query.TestQueryTextMatch object at 0x7fb481cf39d0>

    @pytest.mark.tags(CaseLabel.L0)
    def test_query_text_match_with_combined_expression_for_multi_field(self):
        """
        target: test query text match with combined expression for multi field
        method: 1. enable text match, and insert data with varchar
                2. create the combined expression with `and`, `or` and `not` operator for multi field
                3. verify the result
        expected: query successfully and result is correct
        """
        analyzer_params = {
            "tokenizer": "default",
        }
        # 1. initialize with data
        dim = 128
        fields = [
            FieldSchema(name="id", dtype=DataType.INT64, is_primary=True),
            FieldSchema(
                name="word",
                dtype=DataType.VARCHAR,
                max_length=65535,
                enable_match=True,
                analyzer_params=analyzer_params,
            ),
            FieldSchema(
                name="sentence",
                dtype=DataType.VARCHAR,
                max_length=65535,
                enable_match=True,
                analyzer_params=analyzer_params,
            ),
            FieldSchema(
                name="paragraph",
                dtype=DataType.VARCHAR,
                max_length=65535,
                enable_match=True,
                analyzer_params=analyzer_params,
            ),
            FieldSchema(
                name="text",
                dtype=DataType.VARCHAR,
                max_length=65535,
                enable_match=True,
                analyzer_params=analyzer_params,
            ),
            FieldSchema(name="emb", dtype=DataType.FLOAT_VECTOR, dim=dim),
        ]
        schema = CollectionSchema(fields=fields, description="test collection")
        data_size = 5000
        c_name = cf.gen_unique_str(prefix)
        collection_w = self.init_collection_wrap(
            name=c_name, schema=schema
        )
>       collection_w = self.init_collection_wrap(
            name=c_name, schema=schema
        )

test_query.py:5017: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../base/client_base.py:172: in init_collection_wrap
    collection_w.init_collection(name=name, schema=schema, check_task=check_task,
../base/collection_wrapper.py:41: in init_collection
    name=name, schema=schema, using=using, **kwargs).run()
../check/func_check.py:34: in run
    result = self.assert_succ(self.succ, True)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <check.func_check.ResponseChecker object at 0x7fb491ededa0>
actual = False, expect = True

    def assert_succ(self, actual, expect):
>       assert actual is expect, f"Response of API {self.func_name} expect {expect}, but got {actual}"
E       AssertionError: Response of API init_collection expect True, but got False

../check/func_check.py:116: AssertionError
```

**Comment by czs007** [comment]
working on it.

**Comment by zhuwenxing** [comment]
server version: 20750c0-dev
pymilvus version: 2.5.0rc96

with this config, this issue was not reproduced
