### ISSUE TITLE
[Bug]: Creating a collection still succeeds even when using an unsupported tokenizer in the schema and Jieba tokenizer is not working..

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#36751]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:zhengbuqian-doc-in-restful-d174d05-20241010
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```

-------------------------------- live log call ---------------------------------
[2024-10-10 19:28:13 - DEBUG - ci_test]: (api_request)  : [Connections.has_connection] args: ['default'], kwargs: {} (api_request.py:62)
[2024-10-10 19:28:13 - DEBUG - ci_test]: (api_response) : False  (api_request.py:37)
[2024-10-10 19:28:13 - DEBUG - ci_test]: (api_request)  : [Connections.connect] args: ['default', '', '', 'default', ''], kwargs: {'host': '10.104.4.62', 'port': 19530} (api_request.py:62)
[2024-10-10 19:28:13 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)
[2024-10-10 19:28:13 - DEBUG - ci_test]: (api_request)  : [Collection] args: ['full_text_search_collection_smwEFsbH', {'auto_id': False, 'description': 'test collection', 'fields': [{'name': 'id', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'word', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': ......, kwargs: {'consistency_level': 'Strong'} (api_request.py:62)
[2024-10-10 19:28:14 - DEBUG - ci_test]: (api_response) : <Collection>:
-------------
<name>: full_text_search_collection_smwEFsbH
<description>: test collection
<schema>: {'auto_id': False, 'description': 'test collection', 'fields': [{'name': 'id', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'word', 'de......  (api_request.py:37)
[2024-10-10 19:28:14 - DEBUG - ci_test]: (api_request)  : [Collection.describe] args: [180], kwargs: {} (api_request.py:62)
[2024-10-10 19:28:14 - DEBUG - ci_test]: (api_response) : {'collection_name': 'full_text_search_collection_smwEFsbH', 'auto_id': False, 'num_shards': 1, 'description': 'test collection', 'fields': [{'field_id': 100, 'name': 'id', 'description': '', 'type': <DataType.INT64: 5>, 'params': {}, 'is_primary': True}, {'field_id': 101, 'name': 'word', 'descriptio......  (api_request.py:37)
[2024-10-10 19:28:14 - INFO - ci_test]: collection describe {'collection_name': 'full_text_search_collection_smwEFsbH', 'auto_id': False, 'num_shards': 1, 'description': 'test collection', 'fields': [{'field_id': 100, 'name': 'id', 'description': '', 'type': <DataType.INT64: 5>, 'params': {}, 'is_primary': True}, {'field_id': 101, 'name': 'word', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 65535, 'enable_tokenizer': 'true', 'tokenizer_params': '{"tokenizer":"unsupported"}'}, 'is_partition_key': True}, {'field_id': 102, 'name': 'sentence', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 65535, 'enable_tokenizer': 'true', 'tokenizer_params': '{"tokenizer":"unsupported"}'}}, {'field_id': 103, 'name': 'paragraph', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 65535, 'enable_tokenizer': 'true', 'tokenizer_params': '{"tokenizer":"unsupported"}'}}, {'field_id': 104, 'name': 'text', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 65535, 'enable_tokenizer': 'true', 'tokenizer_params': '{"tokenizer":"unsupported"}'}}, {'field_id': 105, 'name': 'emb', 'description': '', 'type': <DataType.FLOAT_VECTOR: 101>, 'params': {'dim': 128}}, {'field_id': 106, 'name': 'text_sparse_emb', 'description': '', 'type': <DataType.SPARSE_FLOAT_VECTOR: 104>, 'params': {}, 'is_function_output': True}, {'field_id': 107, 'name': 'paragraph_sparse_emb', 'description': '', 'type': <DataType.SPARSE_FLOAT_VECTOR: 104>, 'params': {}, 'is_function_output': True}], 'functions': [{'name': 'text_bm25_emb', 'id': 100, 'description': '', 'type': <FunctionType.BM25: 1>, 'params': {}, 'input_field_names': ['text'], 'input_field_ids': [104], 'output_field_names': ['text_sparse_emb'], 'output_field_ids': [106]}, {'name': 'paragraph_bm25_emb', 'id': 101, 'description': '', 'type': <FunctionType.BM25: 1>, 'params': {}, 'input_field_names': ['paragraph'], 'input_field_ids': [103], 'output_field_names': ['paragraph_sparse_emb'], 'output_field_ids': [107]}], 'aliases': [], 'collection_id': 453124184567726198, 'consistency_level': 0, 'properties': {}, 'num_partitions': 16, 'enable_dynamic_field': False} (test_full_text_search.py:158)
FAILED
testcases/test_full_text_search.py:100 (TestCreateCollectionWithFullTextSearchNegative.test_create_collection_for_full_text_search_with_unsupported_tokenizer[unsupported])
self = <test_full_text_search.TestCreateCollectionWithFullTextSearchNegative object at 0x13275c940>
tokenizer = 'unsupported'

    @pytest.mark.tags(CaseLabel.L0)
    @pytest.mark.parametrize("tokenizer", ["unsupported"])
    def test_create_collection_for_full_text_search_with_unsupported_tokenizer(self, tokenizer):
        tokenizer_params = {
            "tokenizer": tokenizer,
        }
        dim = 128
        fields = [
            FieldSchema(name="id", dtype=DataType.INT64, is_primary=True),
            FieldSchema(
                name="word",
                dtype=DataType.VARCHAR,
                max_length=65535,
                enable_tokenizer=True,
                tokenizer_params=tokenizer_params,
                is_partition_key=True,
            ),
            FieldSchema(
                name="sentence",
                dtype=DataType.VARCHAR,
                max_length=65535,
                enable_tokenizer=True,
                tokenizer_params=tokenizer_params,
            ),
            FieldSchema(
                name="paragraph",
                dtype=DataType.VARCHAR,
                max_length=65535,
                enable_tokenizer=True,
                tokenizer_params=tokenizer_params,
            ),
            FieldSchema(
                name="text",
                dtype=DataType.VARCHAR,
                max_length=65535,
                enable_tokenizer=True,
                tokenizer_params=tokenizer_params,
            ),
            FieldSchema(name="emb", dtype=DataType.FLOAT_VECTOR, dim=dim),
            FieldSchema(name="text_sparse_emb", dtype=DataType.SPARSE_FLOAT_VECTOR),
            FieldSchema(name="paragraph_sparse_emb", dtype=DataType.SPARSE_FLOAT_VECTOR),
        ]
        schema = CollectionSchema(fields=fields, description="test collection")
        text_fields = ["text", "paragraph"]
        for field in text_fields:
            bm25_function = Function(
                name=f"{field}_bm25_emb",
                function_type=FunctionType.BM25,
                input_field_names=[field],
                output_field_names=[f"{field}_sparse_emb"],
                params={},
            )
            schema.add_function(bm25_function)
        collection_w = self.init_collection_wrap(
            name=cf.gen_unique_str(prefix), schema=schema
        )
        res, result = collection_w.describe()
        log.info(f"collection describe {res}")
>       assert not result, "create collection with unsupported tokenizer should be failed"
E       AssertionError: create collection with unsupported tokenizer should be failed
E       assert not True
```

### Expected Behavior

create collection with unsupported tokenizer should be failed

**Comment by zhuwenxing** [comment]
this issue is caused by tokenizer params not correctly checked and used.
so set it as critical issue

**Comment by zhuwenxing** [comment]
verified and fixed
```
[2024-11-21 16:58:03 - INFO - ci_test]: [initialize_milvus] Log cleaned up, start testing... (conftest.py:233)
[2024-11-21 16:58:03 - INFO - ci_test]: [setup_class] Start setup class... (client_base.py:41)
[2024-11-21 16:58:03 - INFO - ci_test]: *********************************** setup *********************************** (client_base.py:47)
[2024-11-21 16:58:03 - INFO - ci_test]: pymilvus version: 2.5.0rc126 (client_base.py:48)
[2024-11-21 16:58:03 - INFO - ci_test]: [setup_method] Start setup test case test_create_collection_for_full_text_search_with_unsupported_tokenizer. (client_base.py:49)
-------------------------------- live log call ---------------------------------
[2024-11-21 16:58:03 - DEBUG - ci_test]: (api_request)  : [Connections.has_connection] args: ['default'], kwargs: {} (api_request.py:62)
[2024-11-21 16:58:03 - DEBUG - ci_test]: (api_response) : False  (api_request.py:37)
[2024-11-21 16:58:03 - DEBUG - ci_test]: (api_request)  : [Connections.connect] args: ['default', '', '', 'default', ''], kwargs: {'host': '10.104.23.221', 'port': 19530} (api_request.py:62)
[2024-11-21 16:58:03 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)
[2024-11-21 16:58:03 - INFO - ci_test]: server version: b983ef9 (client_base.py:166)
[2024-11-21 16:58:03 - DEBUG - ci_test]: (api_request)  : [Collection] args: ['full_text_search_collection_0xlIWOsc', {'auto_id': False, 'description': 'test collection', 'fields': [{'name': 'id', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'word', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': ......, kwargs: {'consistency_level': 'Strong'} (api_request.py:62)
[2024-11-21 16:58:04 - ERROR - pymilvus.decorators]: RPC error: [create_collection], <MilvusException: (code=2000, message=failed to validate text schema, C Runtime Exception: invalid tokenizer parameters
: segcore error[segcoreCode=2001])>, <Time:{'RPC start': '2024-11-21 16:58:03.979169', 'RPC error': '2024-11-21 16:58:04.000078'}> (decorators.py:140)
[2024-11-21 16:58:04 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/zilliz/workspace/milvus/tests/python_client/utils/api_request.py", line 32, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/Users/zilliz/workspace/milvus/tests/python_client/utils/api_request.py", line 63, in api_request
    return func(*arg, **kwargs)
  File "/Users/zilliz/opt/anaconda3/envs/full-text-search/lib/python3.10/site-packages/pymilvus/orm/collection.py", line 150, in __init__
    conn.create_collection(self._name, schema, **kwargs)
  File "/Users/zilliz/opt/anaconda3/envs/full-text-search/lib/python3.10/site-packages/pymilvus/decorators.py", line 141, in handler
    raise e from e
  File "/Users/zilliz/opt/anaconda3/envs/full-text-search/lib/python3.10/site-packages/pymilvus/decorators.py", line 137, in handler
    return func(*args, **kwargs)
  File "/Users/zilliz/opt/anaconda3/envs/full-text-search/lib/python3.10/site-packages/pymilvus/decorators.py", line 176, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/opt/anaconda3/envs/full-text-search/lib/python3.10/site-packages/pymilvus/decorators.py", line 116, in handler
    raise e from e
  File "/Users/zilliz/opt/anaconda3/envs/full-text-search/lib/python3.10/site-packages/pymilvus/decorators.py", line 86, in handler
    return func(*args, **kwargs)
  File "/Users/zilliz/opt/anaconda3/envs/full-text-search/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 309, in create_collection
    check_status(status)
  File "/Users/zilliz/opt/anaconda3/envs/full-text-search/lib/python3.10/site-packages/pymilvus/client/utils.py", line 63, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=2000, message=failed to validate text schema, C Runtime Exception: invalid tokenizer parameters
: segcore error[segcoreCode=2001])>
 (api_request.py:45)
[2024-11-21 16:58:04 - ERROR - ci_test]: (api_response) : <MilvusException: (code=2000, message=failed to validate text schema, C Runtime Exception: invalid tokenizer parameters
: segcore error[segcoreCode=2001])> (api_request.py:46)
```

**Comment by yuhp-zts** [comment]
> verified and fixed
> 
> ```
> [2024-11-21 16:58:03 - INFO - ci_test]: [initialize_milvus] Log cleaned up, start testing... (conftest.py:233)
> [2024-11-21 16:58:03 - INFO - ci_test]: [setup_class] Start setup class... (client_base.py:41)
> [2024-11-21 16:58:03 - INFO - ci_test]: *********************************** setup *********************************** (client_base.py:47)
> [2024-11-21 16:58:03 - INFO - ci_test]: pymilvus version: 2.5.0rc126 (client_base.py:48)
> [2024-11-21 16:58:03 - INFO - ci_test]: [setup_method] Start setup test case test_create_collection_for_full_text_search_with_unsupported_tokenizer. (client_base.py:49)
> -------------------------------- live log call ---------------------------------
> [2024-11-21 16:58:03 - DEBUG - ci_test]: (api_request)  : [Connections.has_connection] args: ['default'], kwargs: {} (api_request.py:62)
> [2024-11-21 16:58:03 - DEBUG - ci_test]: (api_response) : False  (api_request.py:37)
> [2024-11-21 16:58:03 - DEBUG - ci_test]: (api_request)  : [Connections.connect] args: ['default', '', '', 'default', ''], kwargs: {'host': '10.104.23.221', 'port': 19530} (api_request.py:62)
> [2024-11-21 16:58:03 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)
> [2024-11-21 16:58:03 - INFO - ci_test]: server version: b983ef9 (client_base.py:166)
> [2024-11-21 16:58:03 - DEBUG - ci_test]: (api_request)  : [Collection] args: ['full_text_search_collection_0xlIWOsc', {'auto_id': False, 'description': 'test collection', 'fields': [{'name': 'id', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'word', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': ......, kwargs: {'consistency_level': 'Strong'} (api_request.py:62)
> [2024-11-21 16:58:04 - ERROR - pymilvus.decorators]: RPC error: [create_collection], <MilvusException: (code=2000, message=failed to validate text schema, C Runtime Exception: invalid tokenizer parameters
> : segcore error[segcoreCode=2001])>, <Time:{'RPC start': '2024-11-21 16:58:03.979169', 'RPC error': '2024-11-21 16:58:04.000078'}> (decorators.py:140)
> [2024-11-21 16:58:04 - ERROR - ci_test]: Traceback (most recent call last):
>   File "/Users/zilliz/workspace/milvus/tests/python_client/utils/api_request.py", line 32, in inner_wrapper
>     res = func(*args, **_kwargs)
>   File "/Users/zilliz/workspace/milvus/tests/python_client/utils/api_request.py", line 63, in api_request
>     return func(*arg, **kwargs)
>   File "/Users/zilliz/opt/anaconda3/envs/full-text-search/lib/python3.10/site-packages/pymilvus/orm/collection.py", line 150, in __init__
>     conn.create_collection(self._name, schema, **kwargs)
>   File "/Users/zilliz/opt/anaconda3/envs/full-text-search/lib/python3.10/site-packages/pymilvus/decorators.py", line 141, in handler
>     raise e from e
>   File "/Users/zilliz/opt/anaconda3/envs/full-text-search/lib/python3.10/site-packages/pymilvus/decorators.py", line 137, in handler
>     return func(*args, **kwargs)
>   File "/Users/zilliz/opt/anaconda3/envs/full-text-search/lib/python3.10/site-packages/pymilvus/decorators.py", line 176, in handler
>     return func(self, *args, **kwargs)
>   File "/Users/zilliz/opt/anaconda3/envs/full-text-search/lib/python3.10/site-packages/pymilvus/decorators.py", line 116, in handler
>     raise e from e
>   File "/Users/zilliz/opt/anaconda3/envs/full-text-search/lib/python3.10/site-packages/pymilvus/decorators.py", line 86, in handler
>     return func(*args, **kwargs)
>   File "/Users/zilliz/opt/anaconda3/envs/full-text-search/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 309, in create_collection
>     check_status(status)
>   File "/Users/zilliz/opt/anaconda3/envs/full-text-search/lib/python3.10/site-packages/pymilvus/client/utils.py", line 63, in check_status
>     raise MilvusException(status.code, status.reason, status.error_code)
> pymilvus.exceptions.MilvusException: <MilvusException: (code=2000, message=failed to validate text schema, C Runtime Exception: invalid tokenizer parameters
> : segcore error[segcoreCode=2001])>
>  (api_request.py:45)
> [2024-11-21 16:58:04 - ERROR - ci_test]: (api_response) : <MilvusException: (code=2000, message=failed to validate text schema, C Runtime Exception: invalid tokenizer parameters
> : segcore error[segcoreCode=2001])> (api_request.py:46)
> ```

I am still encountering the issue where no results are returned when using BM2.5 with Chinese in version 2.5.5, while it works with English. Does it support Chinese now?
