### ISSUE TITLE
[Bug]: After enabling full-text search in the collection, the query node panics when doing inserting or full text searching, with an error reported as "panic: merge failed, BM25 stats not exist".

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#36788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: zhengbuqian-doc-in-restful-d174d05-20241010
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2024/10/11 10:26:39.590 +00:00] [INFO] [msgdispatcher/dispatcher.go:206] ["begin to work"] [pchannel=full-text-search-test-rootcoord-dml_2] [isMain=true]
[2024/10/11 10:26:39.674 +00:00] [INFO] [delegator/exclude_info.go:79] ["remove segment from exclude info"] [segmentID=453124184574005012]
[2024/10/11 10:26:39.754 +00:00] [DEBUG] [gc/gc_tuner.go:90] ["GC Tune done"] ["previous GOGC"=200] ["heapuse "=43] ["total memory"=606] ["next GC"=100] ["new GOGC"=200] [gc-pause=135.696µs] [gc-pause-end=1728642399752365241]
[2024/10/11 10:26:39.786 +00:00] [INFO] [segments/utils.go:158] [test--] [schema="name:\"full_text_search_collection_yVNxFD0U\"  description:\"beir test collection\"  fields:{fieldID:100  name:\"id\"  is_primary_key:true  data_type:VarChar  type_params:{key:\"max_length\"  value:\"10000\"}}  fields:{fieldID:101  name:\"sparse\"  data_type:SparseFloatVector  is_function_output:true}  fields:{fieldID:102  name:\"document\"  data_type:VarChar  type_params:{key:\"max_length\"  value:\"25536\"}  type_params:{key:\"enable_tokenizer\"  value:\"true\"}  type_params:{key:\"tokenizer_params\"  value:\"{\\\"tokenizer\\\":\\\"default\\\"}\"}}  fields:{name:\"RowID\"  description:\"row id\"  data_type:Int64}  fields:{fieldID:1  name:\"Timestamp\"  description:\"time stamp\"  data_type:Int64}  functions:{name:\"text_bm25_emb\"  id:100  type:BM25  input_field_names:\"document\"  input_field_ids:102  output_field_names:\"sparse\"  output_field_ids:101}"]
[2024/10/11 10:26:39.787 +00:00] [DEBUG] [pipeline/embedding_node.go:128] ["pipeline embedding insert msg"] [collectionID=453124184571400995] [segmentID=453124184574005012] [insertRowNum=4147] [timestampMin=453153075612090373] [timestampMax=453153075612090373]
[2024/10/11 10:26:39.805 +00:00] [INFO] [segments/utils.go:158] [test--] [schema="name:\"full_text_search_collection_yVNxFD0U\"  description:\"beir test collection\"  fields:{fieldID:100  name:\"id\"  is_primary_key:true  data_type:VarChar  type_params:{key:\"max_length\"  value:\"10000\"}}  fields:{fieldID:101  name:\"sparse\"  data_type:SparseFloatVector  is_function_output:true}  fields:{fieldID:102  name:\"document\"  data_type:VarChar  type_params:{key:\"max_length\"  value:\"25536\"}  type_params:{key:\"enable_tokenizer\"  value:\"true\"}  type_params:{key:\"tokenizer_params\"  value:\"{\\\"tokenizer\\\":\\\"default\\\"}\"}}  fields:{name:\"RowID\"  description:\"row id\"  data_type:Int64}  fields:{fieldID:1  name:\"Timestamp\"  description:\"time stamp\"  data_type:Int64}  functions:{name:\"text_bm25_emb\"  id:100  type:BM25  input_field_names:\"document\"  input_field_ids:102  output_field_names:\"sparse\"  output_field_ids:101}"]
[2024/10/11 10:26:39.805 +00:00] [DEBUG] [pipeline/embedding_node.go:128] ["pipeline embedding insert msg"] [collectionID=453124184571400995] [segmentID=453124184574005012] [insertRowNum=853] [timestampMin=453153075612090373] [timestampMax=453153075612090373]
[2024/10/11 10:26:39.907 +00:00] [INFO] [segments/utils.go:158] [test--] [schema="name:\"full_text_search_collection_yVNxFD0U\"  description:\"beir test collection\"  fields:{fieldID:100  name:\"id\"  is_primary_key:true  data_type:VarChar  type_params:{key:\"max_length\"  value:\"10000\"}}  fields:{fieldID:101  name:\"sparse\"  data_type:SparseFloatVector  is_function_output:true}  fields:{fieldID:102  name:\"document\"  data_type:VarChar  type_params:{key:\"max_length\"  value:\"25536\"}  type_params:{key:\"enable_tokenizer\"  value:\"true\"}  type_params:{key:\"tokenizer_params\"  value:\"{\\\"tokenizer\\\":\\\"default\\\"}\"}}  fields:{name:\"RowID\"  description:\"row id\"  data_type:Int64}  fields:{fieldID:1  name:\"Timestamp\"  description:\"time stamp\"  data_type:Int64}  functions:{name:\"text_bm25_emb\"  id:100  type:BM25  input_field_names:\"document\"  input_field_ids:102  output_field_names:\"sparse\"  output_field_ids:101}"]
[2024/10/11 10:26:39.907 +00:00] [DEBUG] [pipeline/embedding_node.go:128] ["pipeline embedding insert msg"] [collectionID=453124184571400995] [segmentID=453124184574005012] [insertRowNum=4277] [timestampMin=453153075821805570] [timestampMax=453153075821805570]
[2024/10/11 10:26:39.928 +00:00] [INFO] [segments/utils.go:158] [test--] [schema="name:\"full_text_search_collection_yVNxFD0U\"  description:\"beir test collection\"  fields:{fieldID:100  name:\"id\"  is_primary_key:true  data_type:VarChar  type_params:{key:\"max_length\"  value:\"10000\"}}  fields:{fieldID:101  name:\"sparse\"  data_type:SparseFloatVector  is_function_output:true}  fields:{fieldID:102  name:\"document\"  data_type:VarChar  type_params:{key:\"max_length\"  value:\"25536\"}  type_params:{key:\"enable_tokenizer\"  value:\"true\"}  type_params:{key:\"tokenizer_params\"  value:\"{\\\"tokenizer\\\":\\\"default\\\"}\"}}  fields:{name:\"RowID\"  description:\"row id\"  data_type:Int64}  fields:{fieldID:1  name:\"Timestamp\"  description:\"time stamp\"  data_type:Int64}  functions:{name:\"text_bm25_emb\"  id:100  type:BM25  input_field_names:\"document\"  input_field_ids:102  output_field_names:\"sparse\"  output_field_ids:101}"]
[2024/10/11 10:26:39.928 +00:00] [DEBUG] [pipeline/embedding_node.go:128] ["pipeline embedding insert msg"] [collectionID=453124184571400995] [segmentID=453124184574005012] [insertRowNum=723] [timestampMin=453153075821805570] [timestampMax=453153075821805570]
[2024/10/11 10:26:39.971 +00:00] [INFO] [segments/utils.go:158] [test--] [schema="name:\"full_text_search_collection_yVNxFD0U\"  description:\"beir test collection\"  fields:{fieldID:100  name:\"id\"  is_primary_key:true  data_type:VarChar  type_params:{key:\"max_length\"  value:\"10000\"}}  fields:{fieldID:101  name:\"sparse\"  data_type:SparseFloatVector  is_function_output:true}  fields:{fieldID:102  name:\"document\"  data_type:VarChar  type_params:{key:\"max_length\"  value:\"25536\"}  type_params:{key:\"enable_tokenizer\"  value:\"true\"}  type_params:{key:\"tokenizer_params\"  value:\"{\\\"tokenizer\\\":\\\"default\\\"}\"}}  fields:{name:\"RowID\"  description:\"row id\"  data_type:Int64}  fields:{fieldID:1  name:\"Timestamp\"  description:\"time stamp\"  data_type:Int64}  functions:{name:\"text_bm25_emb\"  id:100  type:BM25  input_field_names:\"document\"  input_field_ids:102  output_field_names:\"sparse\"  output_field_ids:101}"]
[2024/10/11 10:26:39.972 +00:00] [DEBUG] [pipeline/embedding_node.go:128] ["pipeline embedding insert msg"] [collectionID=453124184571400995] [segmentID=453124184574005012] [insertRowNum=1468] [timestampMin=453153075926663170] [timestampMax=453153075926663170]
[2024/10/11 10:26:40.105 +00:00] [PANIC] [delegator/idf_oracle.go:57] ["merge failed, BM25 stats not exist"] [fieldID=101] [stack="github.com/milvus-io/milvus/internal/querynodev2/delegator.(*bm25Stats).Merge\n\t/go/src/github.com/milvus-io/milvus/internal/querynodev2/delegator/idf_oracle.go:57\ngithub.com/milvus-io/milvus/internal/querynodev2/delegator.(*idfOracle).UpdateGrowing\n\t/go/src/github.com/milvus-io/milvus/internal/querynodev2/delegator/idf_oracle.go:154\ngithub.com/milvus-io/milvus/internal/querynodev2/delegator.(*shardDelegator).ProcessInsert\n\t/go/src/github.com/milvus-io/milvus/internal/querynodev2/delegator/delegator_data.go:170\ngithub.com/milvus-io/milvus/internal/querynodev2/pipeline.(*insertNode).Operate\n\t/go/src/github.com/milvus-io/milvus/internal/querynodev2/pipeline/insert_node.go:113\ngithub.com/milvus-io/milvus/internal/util/pipeline.(*pipeline).process\n\t/go/src/github.com/milvus-io/milvus/internal/util/pipeline/pipeline.go:91\ngithub.com/milvus-io/milvus/internal/util/pipeline.(*streamPipeline).work\n\t/go/src/github.com/milvus-io/milvus/internal/util/pipeline/stream_pipeline.go:67"]
panic: merge failed, BM25 stats not exist

goroutine 3333 [running]:
panic({0x61639c0?, 0xc001929440?})
        /usr/local/go/src/runtime/panic.go:1017 +0x3ac fp=0xc004351418 sp=0xc004351368 pc=0x218162c
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x1?, 0x1?, {0x0?, 0x0?, 0xc00250b020?})
        /go/pkg/mod/go.uber.org/zap@v1.27.0/zapcore/entry.go:196 +0x54 fp=0xc004351438 sp=0xc004351418 pc=0x22b18f4
go.uber.org/zap/zapcore.(*CheckWriteAction).OnWrite(0x0?, 0x0?, {0xc0016a4980?, 0x0?, 0x0?})
        <autogenerated>:1 +0x2d fp=0xc004351470 sp=0xc004351438 pc=0x22c374d
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0001f8c30, {0xc0016a4980, 0x1, 0x1})
        /go/pkg/mod/go.uber.org/zap@v1.27.0/zapcore/entry.go:262 +0x3ec fp=0xc004351600 sp=0xc004351470 pc=0x22b1e4c
go.uber.org/zap.(*Logger).Panic(0xc000c39c00?, {0x6afaa87?, 0x0?}, {0xc0016a4980, 0x1, 0x1})
        /go/pkg/mod/go.uber.org/zap@v1.27.0/logger.go:285 +0x51 fp=0xc004351630 sp=0xc004351600 pc=0x24ffe71
github.com/milvus-io/milvus/pkg/log.Panic({0x6afaa87?, 0xa?}, {0xc0016a4980?, 0xc001aeed00?, 0xc001aeecf0?})
        /go/src/github.com/milvus-io/milvus/pkg/log/global.go:56 +0x85 fp=0xc004351680 sp=0xc004351630 pc=0x27a2265
github.com/milvus-io/milvus/internal/querynodev2/delegator.(*bm25Stats).Merge(0xc000012120, 0xc000e56960?)
        /go/src/github.com/milvus-io/milvus/internal/querynodev2/delegator/idf_oracle.go:57 +0x1c5 fp=0xc0043517e0 sp=0xc004351680 pc=0x5cfe8e5
github.com/milvus-io/milvus/internal/querynodev2/delegator.(*idfOracle).UpdateGrowing(0xc00119da40, 0xc0052ec000?, 0xc0032c99e0)
        /go/src/github.com/milvus-io/milvus/internal/querynodev2/delegator/idf_oracle.go:154 +0xa5 fp=0xc004351838 sp=0xc0043517e0 pc=0x5cff165
github.com/milvus-io/milvus/internal/querynodev2/delegator.(*shardDelegator).ProcessInsert(0xc0013e8000, 0xc00521c960?)
        /go/src/github.com/milvus-io/milvus/internal/querynodev2/delegator/delegator_data.go:170 +0x6a2 fp=0xc004351d88 sp=0xc004351838 pc=0x5ceb102
github.com/milvus-io/milvus/internal/querynodev2/pipeline.(*insertNode).Operate(0xc000d4e1c0, {0x63026c0?, 0xc0032d4050})
        /go/src/github.com/milvus-io/milvus/internal/querynodev2/pipeline/insert_node.go:113 +0x28e fp=0xc004351e88 sp=0xc004351d88 pc=0x5d1e0ce
github.com/milvus-io/milvus/internal/util/pipeline.(*pipeline).process(0xc0007eaf50?)
        /go/src/github.com/milvus-io/milvus/internal/util/pipeline/pipeline.go:91 +0x83 fp=0xc004351ed8 sp=0xc004351e88 pc=0x5d16ec3
github.com/milvus-io/milvus/internal/util/pipeline.(*streamPipeline).work(0xc001d23300)
        /go/src/github.com/milvus-io/milvus/internal/util/pipeline/stream_pipeline.go:67 +0xf7 fp=0xc004351fc8 sp=0xc004351ed8 pc=0x5d17037
github.com/milvus-io/milvus/internal/util/pipeline.(*streamPipeline).Start.func1.1()
        /go/src/github.com/milvus-io/milvus/internal/util/pipeline/stream_pipeline.go:129 +0x25 fp=0xc004351fe0 sp=0xc004351fc8 pc=0x5d18245
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc004351fe8 sp=0xc004351fe0 pc=0x21baee1
created by github.com/milvus-io/milvus/internal/util/pipeline.(*streamPipeline).Start.func1 in goroutine 484
        /go/src/github.com/milvus-io/milvus/internal/util/pipeline/stream_pipeline.go:129 +0x96


```

**Comment by zhuwenxing** [comment]
/assign @zhengbuqian 
PTAL

**Comment by zhuwenxing** [comment]
After a panic occurs, running the same case subsequently, the panic is almost guaranteed to recur.

**Comment by aoiasd** [comment]
Seems collection schema in querynode don't have bm25 function, cause IDFOracle init incomplete.

**Comment by aoiasd** [comment]
Will fix in master with compaction pr.

**Comment by zhengbuqian** [comment]
should be fixed in https://github.com/milvus-io/milvus/pull/36072, please verify

@zhuwenxing

**Comment by zhuwenxing** [comment]
not reproduced in `master-346510e-20241021`
