### ISSUE TITLE
[Bug]: Create "IVF_FLAT" index  failed with error "nlist out of range: [1, 65536]" if not specifying "nlist" parameter

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#36906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-latest/ 2.4 latest
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):    all
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-latest(master)/2.4
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Create "IVF_FLAT" index  failed with error "nlist out of range: [1, 65536]" if not specifying "nlist" parameter

errror:
```
creating index
RPC error: [create_index], <MilvusException: (code=1100, message=nlist out of range: [1, 65536]: invalid parameter[expected=valid index params][actual=invalid index params])>, <Time:{'RPC start': '2024-10-16 12:09:19.603930', 'RPC error': '2024-10-16 12:09:19.629960'}>
Traceback (most recent call last):
  File "./HSNW_New_Smoke.py", line 49, in <module>
    collection.create_index("float_vector", index, index_name="index_name_1")
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 1373, in create_index
    return conn.create_index(self._name, field_name, index_params, timeout=timeout, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 148, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 144, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 183, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 123, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 87, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 986, in create_index
    check_status(status)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/utils.py", line 63, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1100, message=nlist out of range: [1, 65536]: invalid parameter[expected=valid index params][actual=invalid index params])>
```

### Expected Behavior

Create index successfully with default value: nlist: 128
![img_v3_02fn_1e4fb3ee-0f78-486a-ad7c-796f8f5fc1ag](https://github.com/user-attachments/assets/e0b0f0b2-54ad-4398-a93a-9d7832e4095a)

### Steps To Reproduce

```python
from pymilvus import CollectionSchema, FieldSchema
from pymilvus import Collection
from pymilvus import connections
from pymilvus import DataType
from pymilvus import Partition
from pymilvus import utility
import json


connections.connect()

dim = 128
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
bool_field = FieldSchema(name="bool", dtype=DataType.BOOL)
string_field = FieldSchema(name="string", dtype=DataType.VARCHAR, max_length=65535)
json_field = FieldSchema(name="json_field", dtype=DataType.JSON)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)

schema = CollectionSchema(fields=[int64_field, float_field, bool_field, float_vector])

collection = Collection("test_search_collection_binbin_tmp_0", schema=schema)

metric = "IP"
import random
default_search_params = {"metric_type": metric, "params": {"nprobe": 10}}

nb=10000

vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]

import numpy as np

res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], [np.bool_(i) for i in range(nb)], vectors])


collection.flush()


print(collection.num_entities)


index = {"index_type": "IVF_FLAT", "metric_type": metric, "params": {}}
print("creating index")

collection.create_index("float_vector", index, index_name="index_name_1")
```

### Milvus Log

https://grafana-4am.zilliz.cc/explore?orgId=1&panes=%7B%22OFt%22:%7B%22datasource%22:%22vhI6Vw67k%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcluster%3D%5C%22devops%5C%22,namespace%3D%5C%22chaos-testing%5C%22,pod%3D~%5C%22test-nlist-exqyt.%2A%5C%22%7D%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22vhI6Vw67k%22%7D%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1

### Anything else?

collection_name: test_search_collection_binbin_tmp_0

**Comment by binbinlv** [comment]
This issue exist in both master and 2.4.13.

**Comment by XuanYang-cn** [comment]
Milvus doesn't set default nlist, knowhere does. Now milvus returns err if nlist is missing.

We should change the docs.

**Comment by binbinlv** [comment]
> Milvus doesn't set default nlist, knowhere does. Now milvus returns err if nlist is missing.
> 
> We should change the docs.

@AnthonyTsu1984

**Comment by binbinlv** [comment]
@yanliang567 

so from @XuanYang-cn  comments, this is as designed, and the doc is wrong, is it acceptable?

**Comment by yanliang567** [comment]
I think @liliu-z 's team is working for default index params for all index types. 
/assign @liliu-z

**Comment by foxspy** [comment]
> I think @liliu-z 's team is working for default index params for all index types. /assign @liliu-z

@yanliang567 This is the current situation. Do we need to adjust this rule in 2.4? We plan to deal with it in 2.5.x and update the documentation together.

**Comment by foxspy** [comment]
> > I think @liliu-z 's team is working for default index params for all index types. /assign @liliu-z
> 
> @yanliang567 This is the current situation. Do we need to adjust this rule in 2.4? We plan to deal with it in 2.5.x and update the documentation together. The newest error msg should be param nlist not exist in json

discussed with product manager, we have set the nlist with default value 128. Please check it

**Comment by yanliang567** [comment]
/assign @binbinlv 
please help to check

**Comment by binbinlv** [comment]
working on the verification.

**Comment by binbinlv** [comment]
Verified  and the default value behavior has been taken effect on master, and 2.4 still keeps the behavior of reporting error, it is as designed?


milvus: master-20241203-3445b8bd-amd64

```
>>> index = {"index_type": "IVF_FLAT", "metric_type": metric, "params": {}}
>>> print("creating index")
creating index
>>>
>>>
>>> collection.create_index("float_vector", index, index_name="index_name_1")
Status(code=0, message=)
```

2.4:
milvus:  2.4-20241208-bd1ffeaf
```
>>> index = {"index_type": "IVF_FLAT", "metric_type": metric, "params": {}}
>>> print("creating index")
creating index
>>>
>>> collection.create_index("float_vector", index, index_name="index_name_1")
2024-12-09 11:14:04,058 [ERROR][handler]: RPC error: [create_index], <MilvusException: (code=1100, message=nlist out of range: [1, 65536]: invalid parameter[expected=valid index params][actual=invalid index params])>, <Time:{'RPC start': '2024-12-09 11:14:04.025486', 'RPC error': '2024-12-09 11:14:04.058354'}> (decorators.py:140)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 1373, in create_index
    return conn.create_index(self._name, field_name, index_params, timeout=timeout, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 141, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 137, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 176, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 116, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 86, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 991, in create_index
    check_status(status)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/utils.py", line 63, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1100, message=nlist out of range: [1, 65536]: invalid parameter[expected=valid index params][actual=invalid index params])>
```

**Comment by binbinlv** [comment]
@foxspy 

The 2.4 latest still reports error like above, it is as design?

**Comment by foxspy** [comment]
> @foxspy
> 
> The 2.4 latest still reports error like above, it is as design?

@binbinlv It is by design for 2.4. For 2.5 nlist has default value 128.

**Comment by binbinlv** [comment]
OK， close this issue.
