### ISSUE TITLE
[Bug]: [new_indexes] Create index hangs when set m in which dim % m != 0 for new HNSW PQ/PRQ indexes

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#36980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20241017-97ff012c-amd64
- Deployment mode(standalone or cluster):both
- MQ type(rocksmq, pulsar or kafka):    all
- SDK version(e.g. pymilvus v2.0.0rc2): 2.5.0rc97
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

[new_indexes] Create index hangs when set m in which dim % m != 0 for new HNSW PQ/PRQ indexes

### Expected Behavior

Report error

### Steps To Reproduce

```python
from pymilvus import Collection
from pymilvus import connections
from pymilvus import DataType
from pymilvus import Partition
from pymilvus import utility
import json
connections.connect()
dim = 128
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
bool_field = FieldSchema(name="bool", dtype=DataType.BOOL)
string_field = FieldSchema(name="string", dtype=DataType.VARCHAR, max_length=65535)
json_field = FieldSchema(name="json_field", dtype=DataType.JSON)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)

schema = CollectionSchema(fields=[int64_field, float_field, bool_field, float_vector])
collection = Collection("test_search_collection_binbin_tmp_0", schema=schema)
metric = "IP"
import random
default_search_params = {"metric_type": metric, "params": {"nprobe": 10}}
nb=10000

vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
import numpy as np

res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], [np.bool_(i) for i in range(nb)], vectors])
collection.flush()
index = {"index_type": "FAISS_HNSW_PQ", "metric_type": metric, "params": {"nlist": 8, "m": 9}}
collection.create_index("float_vector", index, index_name="index_name_1")
```

### Milvus Log

https://grafana-4am.zilliz.cc/explore?orgId=1&panes=%7B%22Zgk%22:%7B%22datasource%22:%22vhI6Vw67k%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcluster%3D%5C%22devops%5C%22,namespace%3D%5C%22chaos-testing%5C%22,pod%3D~%5C%22test-null-new-ktmjp.%2A%5C%22%7D%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22vhI6Vw67k%22%7D%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1

**Comment by binbinlv** [comment]
For IVF_PQ, it will reports error: 

```
>>> index = {"index_type": "IVF_PQ", "metric_type": metric, "params": {"nlist": 64, "m": 9, "nbits": 8}}
>>> collection.create_index("float_vector", index, index_name="index_name_1")
RPC error: [create_index], <MilvusException: (code=1100, message=dimension must be able to be divided by `m`, dimension: 128, m: 9: invalid parameter[expected=valid index params][actual=invalid index params])>, <Time:{'RPC start': '2024-10-18 11:54:48.087199', 'RPC error': '2024-10-18 11:54:48.126784'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 1373, in create_index
    return conn.create_index(self._name, field_name, index_params, timeout=timeout, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 141, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 137, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 176, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 116, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 86, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 991, in create_index
    check_status(status)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/utils.py", line 63, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1100, message=dimension must be able to be divided by `m`, dimension: 128, m: 9: invalid parameter[expected=valid index params][actual=invalid index params])>
```

**Comment by binbinlv** [comment]
/assign @binbinlv 
working on verification.

**Comment by binbinlv** [comment]
Verified and fixed:
pymilvus:  2.5.0rc106
milvus: master-20241101-0ac8b166

```
>>> collection.create_index("float_vector", index, index_name="index_name_1")
RPC error: [create_index], <MilvusException: (code=1100, message=The dimension of the vector (dim) should be a multiple of the number of subquantizers (m). Dimension: 128, m: 9: invalid parameter[expected=valid index params][actual=invalid index params])>, <Time:{'RPC start': '2024-11-01 23:47:09.551413', 'RPC error': '2024-11-01 23:47:09.588509'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 1373, in create_index
    return conn.create_index(self._name, field_name, index_params, timeout=timeout, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 141, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 137, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 176, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 116, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 86, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 992, in create_index
    check_status(status)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/utils.py", line 63, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1100, message=The dimension of the vector (dim) should be a multiple of the number of subquantizers (m). Dimension: 128, m: 9: invalid parameter[expected=valid index params][actual=invalid index params])>
```

**Comment by binbinlv** [comment]
But this issue still exists in 2.5 branch:

milvus :2.5-20241101-116bf501-amd64

**Comment by binbinlv** [comment]
The 2.5 branch is deleted and master branch has been verified, so close this issue.
