### ISSUE TITLE
[Bug]: [null & default] Search with expression "field_name == ''" for varchar field with "nullable=True" failed with error "failed to create query plan: cannot parse expression: nullableFid == '', error: comparisons between Double and VarChar are not supported"

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#37016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20241021-70339820-amd64
- Deployment mode(standalone or cluster):both
- MQ type(rocksmq, pulsar or kafka):    all
- SDK version(e.g. pymilvus v2.0.0rc2):2.5.0rc99
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Search with expression "field_name == ''" for varchar field with "nullable=True" failed with error "failed to create query plan: cannot parse expression: nullableFid == '', error: comparisons between Double and VarChar are not supported"

```
>>> res1 = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "nullableFid == ''", output_fields=["nullableFid", "int32"])
RPC error: [search], <MilvusException: (code=1100, message=failed to create query plan: cannot parse expression: nullableFid == '', error: comparisons between Double and VarChar are not supported: invalid parameter)>, <Time:{'RPC start': '2024-10-21 14:48:39.408687', 'RPC error': '2024-10-21 14:48:39.426478'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 801, in search
    resp = conn.search(
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 141, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 137, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 176, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 116, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 86, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 805, in search
    return self._execute_search(request, timeout, round_decimal=round_decimal, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 746, in _execute_search
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 735, in _execute_search
    check_status(response.status)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/utils.py", line 63, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1100, message=failed to create query plan: cannot parse expression: nullableFid == '', error: comparisons between Double and VarChar are not supported: invalid parameter)>
```

### Expected Behavior

Search successfully

### Steps To Reproduce

```python
from pymilvus import CollectionSchema, FieldSchema
from pymilvus import Collection
from pymilvus import connections
from pymilvus import DataType
from pymilvus import Partition
from pymilvus import utility
import json
import random


connections.connect()

dim = 128
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
varchar_field = FieldSchema(name="nullableFid", dtype=DataType.VARCHAR, nullable=True, max_length=100)
int32_field = FieldSchema(name="int32", dtype=DataType.INT64, default_value=10)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
schema = CollectionSchema(fields=[int64_field, varchar_field, int32_field,float_vector])
utility.drop_collection("test")
collection = Collection("test", schema=schema)
res = collection.schema
print(res)

index = {"index_type": "DISKANN", "metric_type": "L2", "params": {}}

nb = 2
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
data = [[1,2], ['3',None],[4,None], vectors]

collection.insert(data=data)
collection.create_index("float_vector", index, index_name="index_name_1")
collection.load()
collection.flush()
res = collection.num_entities
print(res)
default_search_params = {"metric_type": "L2", "params": {}}
limit = 10
nq = 1
import time
start = time.time()
res1 = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "nullableFid == '3'", output_fields=["nullableFid", "int32"])
end = time.time() - start
print(res1)
start = time.time()
res1 = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "nullableFid == ''", output_fields=["nullableFid", "int32"])
end = time.time() - start
```

**Comment by binbinlv** [comment]
It seems this issue exists when setting double field as nullable field first, then drop the collection, and set the same field name but different type (varchar) as nullable field again. Maybe there is cache problem? Wish could be a help.

**Comment by smellthemoon** [comment]
checked the code, may related with expr cache, could you help to have a look? @tedxu

**Comment by xiaofan-luan** [comment]
@smellthemoon 

We need expr cache for the same collection ID?

**Comment by smellthemoon** [comment]
> @smellthemoon
> 
> We need expr cache for the same collection ID?

cache for the same collection id may be fix it.  but it may cause the cache some no need collection information. The root cause here is that the behavior of dropping a collection is not perceived. As a result, if a collection with the same name is created after the drop, dirty information will be obtained from the cache.

**Comment by xiaofan-luan** [comment]
The cache need to be expired by time and should be evicted if other collection has some hits, right?

**Comment by smellthemoon** [comment]
> The cache need to be expired by time and should be evicted if other collection has some hits, right?

yes.

**Comment by smellthemoon** [comment]
pr merged, could you please help to verify? @binbinlv

**Comment by binbinlv** [comment]
working on verification.

**Comment by binbinlv** [comment]
Verified and fixed:

milvus: master-20241107-994f52fa-amd64
pymilvus: 2.5.0rc107

results: (not exception now in this scenario)
```
data: ['[]']
```
