### ISSUE TITLE
[Bug]: [null & default] Unknown error "Assert '(data_type == static_cast<DataType>(column_info.data_type()))'"when searching with the nullable field using invalid expr (varchar field == 0)

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#37028]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20241021-70339820-amd64
- Deployment mode(standalone or cluster):both
- MQ type(rocksmq, pulsar or kafka):    all
- SDK version(e.g. pymilvus v2.0.0rc2):2.5.0rc99
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Unknown error "Assert '(data_type == static_cast<DataType>(column_info.data_type()))'"when using invalid expr (varchar field == 0) when searching

```
>>> res1 = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "nullableFid == 0", output_fields=["nullableFid", "int32"])
RPC error: [search], <MilvusException: (code=65535, message=fail to search on QueryNode 1: worker(1) query failed: Assert "(data_type == static_cast<DataType>(column_info.data_type()))"  at /workspace/source/internal/core/src/query/PlanProto.cpp:239
)>, <Time:{'RPC start': '2024-10-21 17:14:04.683401', 'RPC error': '2024-10-21 17:14:05.422990'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 801, in search
    resp = conn.search(
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 141, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 137, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 176, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 116, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 86, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 805, in search
    return self._execute_search(request, timeout, round_decimal=round_decimal, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 746, in _execute_search
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 735, in _execute_search
    check_status(response.status)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/utils.py", line 63, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=fail to search on QueryNode 1: worker(1) query failed: Assert "(data_type == static_cast<DataType>(column_info.data_type()))"  at /workspace/source/internal/core/src/query/PlanProto.cpp:239
)>
```

### Expected Behavior

Report error: 
cannot parse expression: nullableFid == 0, error: comparisons between VarChar and Int64 are not supported

### Steps To Reproduce
```python
from pymilvus import CollectionSchema, FieldSchema
from pymilvus import Collection
from pymilvus import connections
from pymilvus import DataType
from pymilvus import Partition
from pymilvus import utility
import json
import random

connections.connect()

if "test" in utility.list_collections():
   utility.drop_collection("test")
dim = 128
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
double_field = FieldSchema(name="nullableFid", dtype=DataType.DOUBLE, nullable=True, max_length=100)
int32_field = FieldSchema(name="int32", dtype=DataType.INT64, default_value=10)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
schema = CollectionSchema(fields=[int64_field, double_field, int32_field,float_vector])
collection = Collection("test", schema=schema)
res = collection.schema
index = {"index_type": "DISKANN", "metric_type": "L2", "params": {}}
nb = 2
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
data = [[1,2], [3,None],[4,None], vectors]
collection.insert(data=data)
collection.create_index("float_vector", index, index_name="index_name_1")
collection.load()
collection.flush()
default_search_params = {"metric_type": "L2", "params": {}}
limit = 10
nq = 1
res1 = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "nullableFid == 0", output_fields=["nullableFid", "int32"])
print(res1)
collection.drop()
double_field = FieldSchema(name="nullableFid", dtype=DataType.VARCHAR, nullable=True, max_length=100)
schema = CollectionSchema(fields=[int64_field, double_field, int32_field,float_vector])
collection = Collection("test", schema=schema)
data = [[1,2], ['3',None],[4,None], vectors]
collection.insert(data=data)
collection.create_index("float_vector", index, index_name="index_name_1")
collection.load()
collection.flush()
default_search_params = {"metric_type": "L2", "params": {}}
limit = 10
nq = 1
res1 = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "nullableFid == 0", output_fields=["nullableFid", "int32"])
```

**Comment by binbinlv** [comment]
This is not a 100% reproduced issue, when run the same code again for the second time, it reports the right error.

```
>>> res1 = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "nullableFid == 0", output_fields=["nullableFid", "int32"])
RPC error: [search], <MilvusException: (code=1100, message=failed to create query plan: cannot parse expression: nullableFid == 0, error: comparisons between VarChar and Int64 are not supported: invalid parameter)>, <Time:{'RPC start': '2024-10-21 17:29:25.665841', 'RPC error': '2024-10-21 17:29:25.683277'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 801, in search
    resp = conn.search(
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 141, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 137, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 176, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 116, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 86, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 805, in search
    return self._execute_search(request, timeout, round_decimal=round_decimal, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 746, in _execute_search
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 735, in _execute_search
    check_status(response.status)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/utils.py", line 63, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1100, message=failed to create query plan: cannot parse expression: nullableFid == 0, error: comparisons between VarChar and Int64 are not supported: invalid parameter)>
```

**Comment by smellthemoon** [comment]
related with #37016

**Comment by xiaofan-luan** [comment]
maybe there is no need to panic? simply return errors

**Comment by smellthemoon** [comment]
> maybe there is no need to panic? simply return errors

this assert should not be triggered normally, and the parse layer should return an error that the type is not supported. However, because the expr cache is dirty, the underlying segcore check fails.

**Comment by xiaofan-luan** [comment]
event if the check failed, should we simply return error instead of crash?

**Comment by smellthemoon** [comment]
pr merged, could you please help to verify? @binbinlv

**Comment by binbinlv** [comment]
working on verification
