### ISSUE TITLE
[Bug]: Create "STL_SORT" index hangs for the nullable field with all "None" data

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#37045]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20241021-70339820-amd64
- Deployment mode(standalone or cluster):both
- MQ type(rocksmq, pulsar or kafka):    all
- SDK version(e.g. pymilvus v2.0.0rc2):2.5.0rc99
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Create "STL_SORT" index hangs for the nullable field with all None data

```
[2024-10-22 11:59:03 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['int32', {'index_type': 'STL_SORT', 'params': {}}, 1200], kwargs: {'index_name': ''} (api_request.py:62)
[2024-10-22 12:19:03 - WARNING - pymilvus.decorators]: Retry timeout: 1200s (decorators.py:106)
[2024-10-22 12:19:03 - ERROR - pymilvus.decorators]: RPC error: [wait_for_creating_index], <MilvusException: (code=1, message=Retry timeout: 1200s, message=collection search_collection_WdlktD88 create index  timeout in 1200s)>, <Time:{'RPC start': '2024-10-22 11:59:03.467647', 'RPC error': '2024-10-22 12:19:03.670794'}> (decorators.py:140)
[2024-10-22 12:19:03 - WARNING - pymilvus.decorators]: Retry timeout: 1200s (decorators.py:106)
[2024-10-22 12:19:03 - ERROR - pymilvus.decorators]: RPC error: [create_index], <MilvusException: (code=1, message=Retry timeout: 1200s, message=Retry timeout: 1200s, message=collection search_collection_WdlktD88 create index  timeout in 1200s)>, <Time:{'RPC start': '2024-10-22 11:59:03.433492', 'RPC error': '2024-10-22 12:19:03.673754'}> (decorators.py:140)
[2024-10-22 12:19:03 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/binbin/zillizProjects/milvus_latest_runnable/tests/python_client/utils/api_request.py", line 32, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/Users/binbin/zillizProjects/milvus_latest_runnable/tests/python_client/utils/api_request.py", line 63, in api_request
    return func(*arg, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 1373, in create_index
    return conn.create_index(self._name, field_name, index_params, timeout=timeout, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 141, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 137, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 176, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 107, in handler
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 1200s, message=Retry timeout: 1200s, message=collection search_collection_WdlktD88 create index  timeout in 1200s)>
 (api_request.py:45)
[2024-10-22 12:19:03 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 1200s, message=Retry timeout: 1200s, message=collection search_collection_WdlktD88 create index  timeout in 1200s)> (api_request.py:46)
```

### Expected Behavior

Create index successfully

### Steps To Reproduce

```markdown
@pytest.mark.tags(CaseLabel.L2)
    def test_search_after_none_data_all_field_datatype(self, varchar_scalar_index, numeric_scalar_index,
                                                       null_data_percent, _async):
        """
        target: test search after different index
        method: test search after different index and corresponding search params
        expected: search successfully with limit(topK)
        """
        # 1. initialize with data
        nullable_fields = {ct.default_int32_field_name: null_data_percent,
                           ct.default_int16_field_name: null_data_percent,
                           ct.default_int8_field_name: null_data_percent,
                           ct.default_bool_field_name: null_data_percent,
                           ct.default_float_field_name: null_data_percent,
                           ct.default_double_field_name: null_data_percent,
                           ct.default_string_field_name: null_data_percent}
        collection_w, _, _, insert_ids = self.init_collection_general(prefix, True, 5000, partition_num=1,
                                                                      is_all_data_type=True, dim=default_dim,
                                                                      is_index=False, nullable_fields=nullable_fields)[0:4]
        # 2. create index on vector field and load
        index = "HNSW"
        params = cf.get_index_params_params(index)
        default_index = {"index_type": index, "params": params, "metric_type": "COSINE"}
        vector_name_list = cf.extract_vector_field_name_list(collection_w)
        vector_name_list.append(ct.default_float_vec_field_name)
        for vector_name in vector_name_list:
            collection_w.create_index(vector_name, default_index)
        # 3. create index on scalar field with None data
        scalar_index_params = {"index_type": varchar_scalar_index, "params": {}}
        collection_w.create_index(ct.default_string_field_name, scalar_index_params)
        # 4. create index on scalar field with default data
        scalar_index_params = {"index_type": numeric_scalar_index, "params": {}}
        collection_w.create_index(ct.default_int64_field_name, scalar_index_params)
        collection_w.create_index(ct.default_int32_field_name, scalar_index_params)
        collection_w.create_index(ct.default_int16_field_name, scalar_index_params)
        collection_w.create_index(ct.default_int8_field_name, scalar_index_params)
        collection_w.create_index(ct.default_float_field_name, scalar_index_params)
        scalar_index_params = {"index_type": "INVERTED", "params": {}}
        collection_w.create_index(ct.default_bool_field_name, scalar_index_params)
        collection_w.load()
        # 5. search
        search_params = cf.gen_search_param(index, "COSINE")
        limit = search_params[0]["params"]["ef"]
        log.info("Searching with search params: {}".format(search_params[0]))
        vectors = [[random.random() for _ in range(default_dim)] for _ in range(default_nq)]
        collection_w.search(vectors[:default_nq], default_search_field,
                            search_param, limit, default_search_exp, _async=_async,
                            output_fields=[ct.default_string_field_name, ct.default_float_field_name],
                            check_task=CheckTasks.check_search_results,
                            check_items={"nq": default_nq,
                                         "ids": insert_ids,
                                         "limit": limit,
                                         "_async": _async,
                                         "output_fields": [ct.default_string_field_name,
                                                           ct.default_float_field_name]})
```

### Milvus Log

https://grafana-4am.zilliz.cc/explore?orgId=1&panes=%7B%22pPo%22:%7B%22datasource%22:%22vhI6Vw67k%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcluster%3D%5C%22devops%5C%22,namespace%3D%5C%22chaos-testing%5C%22,pod%3D~%5C%22test-null-new-2-rlhxs.%2A%5C%22%7D%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22vhI6Vw67k%22%7D%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1

**Comment by binbinlv** [comment]
From the milvus log:
![img_v3_02ft_f4284231-624f-44f6-887a-5b422050cacg](https://github.com/user-attachments/assets/48c2ba56-5a32-4f82-9ab4-b8c187a849c1)

@smellthemoon  for your reference.

**Comment by smellthemoon** [comment]
pr merged, could you help to verify? /assign @binbinlv

**Comment by binbinlv** [comment]
working on verification.
