### ISSUE TITLE
[Bug]: After recovering from querynode pod kill chaos in Milvus, search encounters an error `InactiveRpcError: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded`.

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#37125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20241024-f78f6112-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```

[2024-10-24T08:02:53.329Z] [2024-10-24 07:58:18 - INFO - ci_test]: pymilvus version: 2.5.0rc103 (client_base.py:48)

[2024-10-24T08:02:53.329Z] [2024-10-24 07:58:18 - INFO - ci_test]: [setup_method] Start setup test case test_milvus_default. (client_base.py:49)

[2024-10-24T08:02:53.329Z] ------------------------------ Captured log call -------------------------------

[2024-10-24T08:02:53.329Z] [2024-10-24 07:58:18 - DEBUG - ci_test]: (api_request)  : [Connections.connect] args: ['default', '', '', 'default', ''], kwargs: {'host': '10.255.128.91', 'port': 19530} (api_request.py:62)

[2024-10-24T08:02:53.329Z] [2024-10-24 07:58:18 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-10-24T08:02:53.329Z] [2024-10-24 07:58:18 - INFO - ci_test]: server version: f78f611 (client_base.py:166)

[2024-10-24T08:02:53.329Z] [2024-10-24 07:58:18 - DEBUG - ci_test]: (api_request)  : [Connections.has_connection] args: ['default'], kwargs: {} (api_request.py:62)

[2024-10-24T08:02:53.329Z] [2024-10-24 07:58:18 - DEBUG - ci_test]: (api_response) : True  (api_request.py:37)

[2024-10-24T08:02:53.329Z] [2024-10-24 07:58:18 - DEBUG - ci_test]: (api_request)  : [Collection] args: ['Checker__6Q314lZy', {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}, {'name': 'varchar', 'description': '', 'type': <DataType......, kwargs: {'consistency_level': 'Strong'} (api_request.py:62)

[2024-10-24T08:02:53.329Z] [2024-10-24 07:58:18 - DEBUG - ci_test]: (api_response) : <Collection>:

[2024-10-24T08:02:53.329Z] -------------

[2024-10-24T08:02:53.329Z] <name>: Checker__6Q314lZy

[2024-10-24T08:02:53.329Z] <description>: 

[2024-10-24T08:02:53.329Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}......  (api_request.py:37)

[2024-10-24T08:02:53.329Z] [2024-10-24 07:58:18 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-10-24T08:02:53.329Z] [2024-10-24 07:58:19 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-10-24T08:02:53.329Z] [2024-10-24 07:58:19 - DEBUG - ci_test]: (api_request)  : [Collection.compact] args: [False, 180], kwargs: {} (api_request.py:62)

[2024-10-24T08:02:53.329Z] [2024-10-24 07:58:19 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-10-24T08:02:53.329Z] [2024-10-24 07:58:47 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-10-24T08:02:53.329Z] [2024-10-24 07:58:47 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-10-24T08:02:53.329Z] [2024-10-24 07:58:47 - INFO - ci_test]: assert create collection: 0.015021085739135742, init_entities: 211500 (test_all_collections_after_chaos.py:49)

[2024-10-24T08:02:53.330Z] [2024-10-24 07:58:49 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [[[-3000, -2999, -2998, -2997, -2996, -2995, -2994, -2993, -2992, -2991, -2990, -2989, -2988, -2987, -2986, -2985, -2984, -2983, -2982, -2981, -2980, -2979, -2978, -2977, -2976, -2975, -2974, -2973, -2972, -2971, -2970, -2969, -2968, -2967, -2966, -2965, -2964, -2963, -2962, -2961, -2960, -2959, -29......, kwargs: {'timeout': 180} (api_request.py:62)

[2024-10-24T08:02:53.330Z] [2024-10-24 07:58:50 - DEBUG - ci_test]: (api_response) : (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 453445348246421506, success count: 2000, err count: 0  (api_request.py:37)

[2024-10-24T08:02:53.330Z] [2024-10-24 07:58:50 - INFO - ci_test]: assert insert: 1.5147688388824463 (test_all_collections_after_chaos.py:57)

[2024-10-24T08:02:53.330Z] [2024-10-24 07:58:50 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-10-24T08:02:53.330Z] [2024-10-24 07:58:58 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-10-24T08:02:53.330Z] [2024-10-24 07:58:58 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-10-24T08:02:53.330Z] [2024-10-24 07:59:08 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-10-24T08:02:53.330Z] [2024-10-24 07:59:08 - INFO - ci_test]: assert flush: 7.881498336791992, entities: 213500 (test_all_collections_after_chaos.py:67)

[2024-10-24T08:02:53.330Z] [2024-10-24 07:59:08 - INFO - ci_test]: index info: [{'collection': 'Checker__6Q314lZy', 'field': 'image_emb', 'index_name': 'image_emb', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}, {'collection': 'Checker__6Q314lZy', 'field': 'text_emb', 'index_name': 'text_emb', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}, {'collection': 'Checker__6Q314lZy', 'field': 'voice_emb', 'index_name': 'voice_emb', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}, {'collection': 'Checker__6Q314lZy', 'field': 'int64', 'index_name': 'int64', 'index_param': {'index_type': 'INVERTED'}}, {'collection': 'Checker__6Q314lZy', 'field': 'float', 'index_name': 'float', 'index_param': {'index_type': 'INVERTED'}}, {'collection': 'Checker__6Q314lZy', 'field': 'varchar', 'index_name': 'varchar', 'index_param': {'index_type': 'INVERTED'}}, {'collection': 'Checker__6Q314lZy', 'field': 'text', 'index_name': 'text', 'index_param': {'index_type': 'INVERTED'}}, {'collection': 'Checker__6Q314lZy', 'field': 'float_vector', 'index_name': 'float_vector', 'index_param': {'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}, 'index_type': 'HNSW'}}] (test_all_collections_after_chaos.py:71)

[2024-10-24T08:02:53.330Z] [2024-10-24 07:59:08 - INFO - ci_test]: index info: [{'collection': 'Checker__6Q314lZy', 'field': 'voice_emb', 'index_name': 'voice_emb', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}, {'collection': 'Checker__6Q314lZy', 'field': 'int64', 'index_name': 'int64', 'index_param': {'index_type': 'INVERTED'}}, {'collection': 'Checker__6Q314lZy', 'field': 'float', 'index_name': 'float', 'index_param': {'index_type': 'INVERTED'}}, {'collection': 'Checker__6Q314lZy', 'field': 'varchar', 'index_name': 'varchar', 'index_param': {'index_type': 'INVERTED'}}, {'collection': 'Checker__6Q314lZy', 'field': 'text', 'index_name': 'text', 'index_param': {'index_type': 'INVERTED'}}, {'collection': 'Checker__6Q314lZy', 'field': 'float_vector', 'index_name': 'float_vector', 'index_param': {'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}, 'index_type': 'HNSW'}}, {'collection': 'Checker__6Q314lZy', 'field': 'image_emb', 'index_name': 'image_emb', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}, {'collection': 'Checker__6Q314lZy', 'field': 'text_emb', 'index_name': 'text_emb', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}] (test_all_collections_after_chaos.py:86)

[2024-10-24T08:02:53.330Z] [2024-10-24 07:59:08 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 180], kwargs: {} (api_request.py:62)

[2024-10-24T08:02:53.330Z] [2024-10-24 07:59:08 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-10-24T08:02:53.330Z] [2024-10-24 07:59:08 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.05153493440617953, 0.13709839155898074, 0.04641153258716724, 0.013079163965342746, 0.037114680668707864, 0.08668058101240385, 0.1514196525654127, 0.10875671143641998, 0.14564552167678804, 0.08347896817801508, 0.07389425572731069, 0.043289531225209676, 0.054496015206339496, 0.038197405749948135,......, kwargs: {} (api_request.py:62)

[2024-10-24T08:02:53.330Z] [2024-10-24 08:02:08 - ERROR - pymilvus.decorators]: grpc RpcError: [search], <_InactiveRpcError: StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded>, <Time:{'RPC start': '2024-10-24 07:59:08.580292', 'gRPC error': '2024-10-24 08:02:08.582048'}> (decorators.py:151)

[2024-10-24T08:02:53.330Z] [2024-10-24 08:02:08 - ERROR - ci_test]: Traceback (most recent call last):

[2024-10-24T08:02:53.330Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2024-10-24T08:02:53.330Z]     res = func(*args, **_kwargs)

[2024-10-24T08:02:53.330Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2024-10-24T08:02:53.330Z]     return func(*arg, **kwargs)

[2024-10-24T08:02:53.330Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 801, in search

[2024-10-24T08:02:53.330Z]     resp = conn.search(

[2024-10-24T08:02:53.330Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 155, in handler

[2024-10-24T08:02:53.330Z]     raise e from e

[2024-10-24T08:02:53.330Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 137, in handler

[2024-10-24T08:02:53.330Z]     return func(*args, **kwargs)

[2024-10-24T08:02:53.330Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 176, in handler

[2024-10-24T08:02:53.330Z]     return func(self, *args, **kwargs)

[2024-10-24T08:02:53.330Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 90, in handler

[2024-10-24T08:02:53.330Z]     raise e from e

[2024-10-24T08:02:53.330Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 86, in handler

[2024-10-24T08:02:53.330Z]     return func(*args, **kwargs)

[2024-10-24T08:02:53.330Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 805, in search

[2024-10-24T08:02:53.330Z]     return self._execute_search(request, timeout, round_decimal=round_decimal, **kwargs)

[2024-10-24T08:02:53.330Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 746, in _execute_search

[2024-10-24T08:02:53.330Z]     raise e from e

[2024-10-24T08:02:53.330Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 734, in _execute_search

[2024-10-24T08:02:53.330Z]     response = self._stub.Search(request, timeout=timeout)

[2024-10-24T08:02:53.330Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_interceptor.py", line 277, in __call__

[2024-10-24T08:02:53.330Z]     response, ignored_call = self._with_call(

[2024-10-24T08:02:53.330Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_interceptor.py", line 332, in _with_call

[2024-10-24T08:02:53.330Z]     return call.result(), call

[2024-10-24T08:02:53.330Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 438, in result

[2024-10-24T08:02:53.330Z]     raise self

[2024-10-24T08:02:53.330Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_interceptor.py", line 315, in continuation

[2024-10-24T08:02:53.330Z]     response, call = self._thunk(new_method).with_call(

[2024-10-24T08:02:53.330Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_interceptor.py", line 343, in with_call

[2024-10-24T08:02:53.330Z]     return self._with_call(

[2024-10-24T08:02:53.330Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_interceptor.py", line 332, in _with_call

[2024-10-24T08:02:53.330Z]     return call.result(), call

[2024-10-24T08:02:53.330Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 438, in result

[2024-10-24T08:02:53.330Z]     raise self

[2024-10-24T08:02:53.330Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_interceptor.py", line 315, in continuation

[2024-10-24T08:02:53.330Z]     response, call = self._thunk(new_method).with_call(

[2024-10-24T08:02:53.330Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 1178, in with_call

[2024-10-24T08:02:53.330Z]     return _end_unary_response_blocking(state, call, True, None)

[2024-10-24T08:02:53.330Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 1004, in _end_unary_response_blocking

[2024-10-24T08:02:53.330Z]     raise _InactiveRpcError(state)  # pytype: disable=not-instantiable

[2024-10-24T08:02:53.330Z] grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:

[2024-10-24T08:02:53.330Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2024-10-24T08:02:53.330Z] 	details = "Deadline Exceeded"

[2024-10-24T08:02:53.330Z] 	debug_error_string = "UNKNOWN:Deadline Exceeded {grpc_status:4, created_time:"2024-10-24T08:02:08.581599695+00:00"}"

[2024-10-24T08:02:53.330Z] >

[2024-10-24T08:02:53.330Z]  (api_request.py:45)

[2024-10-24T08:02:53.330Z] [2024-10-24 08:02:08 - ERROR - ci_test]: (api_response) : <_InactiveRpcError of RPC that terminated with:

[2024-10-24T08:02:53.330Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2024-10-24T08:02:53.330Z] 	details = "Deadline Exceeded"

[2024-10-24T08:02:53.330Z] 	debug_error_string = "UNKNOWN:Deadline Exceeded {grpc_status:4, created_time:"2024-10-24T08:02:08.581599695+00:00"}"

[2024-10-24T08:02:53.330Z] > (api_request.py:46)
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-cron/detail/chaos-test-kafka-cron/18276/pipeline

log:
[artifacts-querynode-pod-kill-18276-server-logs.tar.gz](https://github.com/user-attachments/files/17514868/artifacts-querynode-pod-kill-18276-server-logs.tar.gz)

**Comment by xiaocai2333** [comment]
The logs have already been deleted. Have there been any new occurrences recently?
/assign @zhuwenxing

**Comment by zhuwenxing** [comment]
not reproduced recently

**Comment by yanliang567** [comment]
i'd close this issue for comments above, please free to reopen if it reproduced
