### ISSUE TITLE
[Bug]: [benchmark][standalone][multipleChunkedEnable] hybrid_search raises error ` query failed: Operator::GetOutput failed for [Operator:PhyFilterBitsNode, plan node id: 59]` in concurrent DQL & DML scene

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#37147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20241025-ad2df904-amd64
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):rocksmq    
- SDK version(e.g. pymilvus v2.0.0rc2):2.5.0rc97
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task: memory-opt-scenes-mn2cd
test case name: test_bitmap_locust_dql_dml_standalone

server:
```
NAME                                                              READY   STATUS      RESTARTS          AGE     IP              NODE         NOMINATED NODE   READINESS GATES
memory-opt-scenes-mn2cd-2-etcd-0                                  1/1     Running     0                 3h48m   10.104.17.193   4am-node23   <none>           <none>
memory-opt-scenes-mn2cd-2-milvus-standalone-7bcd7987cf-xt7n6      1/1     Running     2 (3h48m ago)     3h48m   10.104.30.88    4am-node38   <none>           <none>
memory-opt-scenes-mn2cd-2-minio-6fd4bf75df-gb5vq                  1/1     Running     0                 3h48m   10.104.17.192   4am-node23   <none>           <none> 
```

client  error log:
```
[2024-10-25 03:27:52,200 - ERROR - fouram]: RPC error: [hybrid_search], <MilvusException: (code=65535, message=fail to search on QueryNode 1: worker(1) query failed: Operator::GetOutput failed for [Operator:PhyFilterBitsNode, plan node id: 59] : Assert "ptr"  => entry mismatch at /workspace/source/internal/core/src/segcore/SegmentInterface.h:212
[2024-10-25 03:27:52,270 - ERROR - fouram]: RPC error: [hybrid_search], <MilvusException: (code=65535, message=fail to search on QueryNode 1: worker(1) query failed: Operator::GetOutput failed for [Operator:PhyFilterBitsNode, plan node id: 65] : Assert "ptr"  => entry mismatch at /workspace/source/internal/core/src/segcore/SegmentInterface.h:212
[2024-10-25 03:27:52,604 - ERROR - fouram]: RPC error: [hybrid_search], <MilvusException: (code=65535, message=fail to search on QueryNode 1: worker(1) query failed: Operator::GetOutput failed for [Operator:PhyFilterBitsNode, plan node id: 113] : Assert "ptr"  => entry mismatch at /workspace/source/internal/core/src/segcore/SegmentInterface.h:212
[2024-10-25 03:27:52,721 - ERROR - fouram]: RPC error: [hybrid_search], <MilvusException: (code=65535, message=fail to search on QueryNode 1: worker(1) query failed: Operator::GetOutput failed for [Operator:PhyFilterBitsNode, plan node id: 107] : Assert "ptr"  => entry mismatch at /workspace/source/internal/core/src/segcore/SegmentInterface.h:212
[2024-10-25 03:27:52,785 - ERROR - fouram]: RPC error: [hybrid_search], <MilvusException: (code=65535, message=fail to search on QueryNode 1: worker(1) query failed: Operator::GetOutput failed for [Operator:PhyFilterBitsNode, plan node id: 125] : Assert "ptr"  => entry mismatch at /workspace/source/internal/core/src/segcore/SegmentInterface.h:212
[2024-10-25 03:27:54,441 - ERROR - fouram]: RPC error: [hybrid_search], <MilvusException: (code=65535, message=fail to search on QueryNode 1: worker(1) query failed: Operator::GetOutput failed for [Operator:PhyFilterBitsNode, plan node id: 283] : Assert "ptr"  => entry mismatch at /workspace/source/internal/core/src/segcore/SegmentInterface.h:212
[2024-10-25 03:27:56,977 - ERROR - fouram]: RPC error: [hybrid_search], <MilvusException: (code=65535, message=fail to search on QueryNode 1: worker(1) query failed: Operator::GetOutput failed for [Operator:PhyFilterBitsNode, plan node id: 392] : Assert "ptr"  => entry mismatch at /workspace/source/internal/core/src/segcore/SegmentInterface.h:212
[2024-10-25 03:27:58,684 - ERROR - fouram]: RPC error: [hybrid_search], <MilvusException: (code=65535, message=fail to search on QueryNode 1: worker(1) query failed: Operator::GetOutput failed for [Operator:PhyFilterBitsNode, plan node id: 495] : Assert "ptr"  => entry mismatch at /workspace/source/internal/core/src/segcore/SegmentInterface.h:212
[2024-10-25 03:28:10,184 - ERROR - fouram]: RPC error: [search], <MilvusException: (code=2200, message=incomplete query result, missing id %!s(int64=453463308527584890), len(searchIDs) = 100, len(queryIDs) = 13, collection=453463308525896323: inconsistent requery result)>, <Time:{'RPC start': '2024-10-25 03:27:48.693335', 'RPC error': '2024-10-25 03:28:10.184001'}> (decorators.py:140)
[2024-10-25 03:28:10,188 - ERROR - fouram]: RPC error: [search], <MilvusException: (code=2200, message=incomplete query result, missing id %!s(int64=453463308525984853), len(searchIDs) = 100, len(queryIDs) = 12, collection=453463308525896323: inconsistent requery result)>, <Time:{'RPC start': '2024-10-25 03:27:48.706424', 'RPC error': '2024-10-25 03:28:10.188507'}> (decorators.py:140)
[2024-10-25 03:28:10,250 - ERROR - fouram]: RPC error: [search], <MilvusException: (code=2200, message=incomplete query result, missing id %!s(int64=453463308527584890), len(searchIDs) = 100, len(queryIDs) = 20, collection=453463308525896323: inconsistent requery result)>, <Time:{'RPC start': '2024-10-25 03:27:49.029308', 'RPC error': '2024-10-25 03:28:10.250593'}> (decorators.py:140)
[2024-10-25 03:28:11,940 - ERROR - fouram]: RPC error: [search], <MilvusException: (code=2200, message=incomplete query result, missing id %!s(int64=453463308527584890), len(searchIDs) = 100, len(queryIDs) = 16, collection=453463308525896323: inconsistent requery result)>, <Time:{'RPC start': '2024-10-25 03:27:50.732770', 'RPC error': '2024-10-25 03:28:11.940129'}> (decorators.py:140)
[2024-10-25 03:28:12,560 - ERROR - fouram]: RPC error: [hybrid_search], <MilvusException: (code=65535, message=fail to search on QueryNode 1: worker(1) query failed: Operator::GetOutput failed for [Operator:PhyFilterBitsNode, plan node id: 914] : Assert "ptr"  => entry mismatch at /workspace/source/internal/core/src/segcore/SegmentInterface.h:212
[2024-10-25 03:28:12,818 - ERROR - fouram]: RPC error: [search], <MilvusException: (code=2200, message=incomplete query result, missing id %!s(int64=453463308527584890), len(searchIDs) = 100, len(queryIDs) = 11, collection=453463308525896323: inconsistent requery result)>, <Time:{'RPC start': '2024-10-25 03:27:51.694807', 'RPC error': '2024-10-25 03:28:12.818634'}> (decorators.py:140)
[2024-10-25 03:28:13,405 - ERROR - fouram]: RPC error: [search], <MilvusException: (code=2200, message=incomplete query result, missing id %!s(int64=453463308527584890), len(searchIDs) = 100, len(queryIDs) = 9, collection=453463308525896323: inconsistent requery result)>, <Time:{'RPC start': '2024-10-25 03:27:52.272400', 'RPC error': '2024-10-25 03:28:13.405480'}> (decorators.py:140)
[2024-10-25 03:28:13,754 - ERROR - fouram]: RPC error: [search], <MilvusException: (code=2200, message=incomplete query result, missing id %!s(int64=453463308527584890), len(searchIDs) = 100, len(queryIDs) = 8, collection=453463308525896323: inconsistent requery result)>, <Time:{'RPC start': '2024-10-25 03:27:52.607858', 'RPC error': '2024-10-25 03:28:13.754053'}> (decorators.py:140)
[2024-10-25 03:28:13,853 - ERROR - fouram]: RPC error: [search], <MilvusException: (code=2200, message=incomplete query result, missing id %!s(int64=453463308527584890), len(searchIDs) = 100, len(queryIDs) = 19, collection=453463308525896323: inconsistent requery result)>, <Time:{'RPC start': '2024-10-25 03:27:52.696048', 'RPC error': '2024-10-25 03:28:13.853192'}> (decorators.py:140)

```

### Steps To Reproduce

```markdown
concurrent test and calculation of RT and QPS

        :purpose:  `primary key: INT64 autoID`
            1. building `BITMAP` index on all supported 12 scalar fields
            2. 2 fields of different vector types
            3. verify DQL & DML requests

        :test steps:
            1. create collection with fields:
                'float_vector': 128dim
                'sparse_float_vector': sparse_range=[1, 100] <- the range of non-zero values of a sparse vector
                'id': primary key type is INT64

                all scalar fields: varchar max_length=100, array max_capacity=13
            2. build indexes:
                IVF_SQ8: 'float_vector'
                SPARSE_WAND: 'sparse_float_vector'
                BITMAP: all scalar fields
            3. insert 2 million data
            4. flush collection
            5. build indexes again using the same params
            6. load collection
            7. concurrent request:
                - search
                - query
                - hybrid_search
                - load
                - insert
                - delete: delete all inserted data
                - flush: ignore RateLimiter
```

### Anything else?

test result:
```
[2024-10-25 06:27:49,697 -  INFO - fouram]: Type     Name                                                                          # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s (stats.py:789)
[2024-10-25 06:27:49,697 -  INFO - fouram]: --------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|----------- (stats.py:789)
[2024-10-25 06:27:49,697 -  INFO - fouram]: grpc     delete                                                                           537     0(0.00%) |   5668       1   70785      9 |    0.05        0.00 (stats.py:789)
[2024-10-25 06:27:49,697 -  INFO - fouram]: grpc     flush                                                                            575     0(0.00%) | 115020     507  690441  55000 |    0.05        0.00 (stats.py:789)
[2024-10-25 06:27:49,697 -  INFO - fouram]: grpc     hybrid_search                                                                    597 597(100.00%) |      0       0       0      0 |    0.06        0.06 (stats.py:789)
[2024-10-25 06:27:49,697 -  INFO - fouram]: grpc     insert                                                                           597     0(0.00%) |   5832       3   60038     26 |    0.06        0.00 (stats.py:789)
[2024-10-25 06:27:49,697 -  INFO - fouram]: grpc     load                                                                             626     0(0.00%) |  11621       3  120007     70 |    0.06        0.00 (stats.py:789)
[2024-10-25 06:27:49,697 -  INFO - fouram]: grpc     query                                                                            651  563(86.48%) |     75       0    8881      0 |    0.06        0.05 (stats.py:789)
[2024-10-25 06:27:49,697 -  INFO - fouram]: grpc     search                                                                           587 587(100.00%) |      0       0       0      0 |    0.05        0.05 (stats.py:789)
[2024-10-25 06:27:49,697 -  INFO - fouram]: --------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|----------- (stats.py:789)
[2024-10-25 06:27:49,697 -  INFO - fouram]:          Aggregated                                                                      4170 1747(41.89%) |  19181       0  690441      5 |    0.39        0.16 (stats.py:789)
[2024-10-25 06:27:49,697 -  INFO - fouram]:  (stats.py:790)
[2024-10-25 06:27:49,701 -  INFO - fouram]: [PerfTemplate] Report data: 
{'server': {'deploy_tool': 'helm',
            'deploy_mode': 'standalone',
            'config_name': 'standalone_16c64m',
            'config': {'standalone': {'resources': {'limits': {'cpu': '16.0', 'memory': '64Gi'}, 'requests': {'cpu': '9.0', 'memory': '33Gi'}}},
                       'cluster': {'enabled': False},
                       'etcd': {'replicaCount': 1, 'metrics': {'enabled': True, 'podMonitor': {'enabled': True}}},
                       'minio': {'mode': 'standalone', 'metrics': {'podMonitor': {'enabled': True}}},
                       'pulsar': {'enabled': False},
                       'metrics': {'serviceMonitor': {'enabled': True}},
                       'log': {'level': 'debug'},
                       'extraConfigFiles': {'user.yaml': 'queryNode:\n  segcore:\n    multipleChunkedEnable: true\n'},
                       'image': {'all': {'repository': 'harbor.milvus.io/milvus/milvus', 'tag': 'master-20241025-ad2df904-amd64'}}},
            'host': 'memory-opt-scenes-mn2cd-2-milvus.qa-milvus.svc.cluster.local',
            'port': '19530',
            'uri': ''},
 'client': {'test_case_type': 'ConcurrentClientBase',
            'test_case_name': 'test_bitmap_locust_dql_dml_standalone',
            'test_case_params': {'dataset_params': {'metric_type': 'L2',
                                                    'dim': 128,
                                                    'max_length': 100,
                                                    'scalars_index': {'int8_1': {'index_type': 'BITMAP'},
                                                                      'int16_1': {'index_type': 'BITMAP'},
                                                                      'int32_1': {'index_type': 'BITMAP'},
                                                                      'int64_1': {'index_type': 'BITMAP'},
                                                                      'varchar_1': {'index_type': 'BITMAP'},
                                                                      'bool_1': {'index_type': 'BITMAP'},
                                                                      'array_int8_1': {'index_type': 'BITMAP'},
                                                                      'array_int16_1': {'index_type': 'BITMAP'},
                                                                      'array_int32_1': {'index_type': 'BITMAP'},
                                                                      'array_int64_1': {'index_type': 'BITMAP'},
                                                                      'array_varchar_1': {'index_type': 'BITMAP'},
                                                                      'array_bool_1': {'index_type': 'BITMAP'}},
                                                    'vectors_index': {'sparse_float_vector': {'index_type': 'SPARSE_INVERTED_INDEX',
                                                                                              'index_param': {'drop_ratio_build': 0.2},
                                                                                              'metric_type': 'IP'}},
                                                    'scalars_params': {'array_int8_1': {'params': {'max_capacity': 13},
                                                                                        'other_params': {'dataset': 'random_algorithm',
                                                                                                         'algorithm_params': {'algorithm_name': 'random_range',
                                                                                                                              'specify_range': [-128, 128],
                                                                                                                              'max_capacity': 13}}},
                                                                       'array_int16_1': {'params': {'max_capacity': 13},
                                                                                         'other_params': {'dataset': 'random_algorithm',
                                                                                                          'algorithm_params': {'algorithm_name': 'random_range',
                                                                                                                               'specify_range': [-200, 200],
                                                                                                                               'max_capacity': 13}}},
                                                                       'array_int32_1': {'params': {'max_capacity': 13},
                                                                                         'other_params': {'dataset': 'random_algorithm',
                                                                                                          'algorithm_params': {'algorithm_name': 'specify_scope',
                                                                                                                               'specify_range': [-300, 300],
                                                                                                                               'max_capacity': 13}}},
                                                                       'array_int64_1': {'params': {'max_capacity': 13},
                                                                                         'other_params': {'dataset': 'random_algorithm',
                                                                                                          'algorithm_params': {'algorithm_name': 'fixed_value_range',
                                                                                                                               'specify_range': [-400, 432],
                                                                                                                               'batch': 50,
                                                                                                                               'max_capacity': 13}}},
                                                                       'array_varchar_1': {'params': {'max_capacity': 13},
                                                                                           'other_params': {'dataset': 'random_algorithm',
                                                                                                            'algorithm_params': {'algorithm_name': 'random_range',
                                                                                                                                 'specify_range': [-1500, 1500],
                                                                                                                                 'max_capacity': 13}}},
                                                                       'array_bool_1': {'params': {'max_capacity': 13}},
                                                                       'int8_1': {'other_params': {'dataset': 'random_algorithm',
                                                                                                   'algorithm_params': {'algorithm_name': 'random_range',
                                                                                                                        'specify_range': [-128, 128],
                                                                                                                        'max_capacity': 13}}},
                                                                       'int16_1': {'other_params': {'dataset': 'random_algorithm',
                                                                                                    'algorithm_params': {'algorithm_name': 'random_range',
                                                                                                                         'specify_range': [-200, 200],
                                                                                                                         'max_capacity': 13}}},
                                                                       'int32_1': {'other_params': {'dataset': 'random_algorithm',
                                                                                                    'algorithm_params': {'algorithm_name': 'specify_scope',
                                                                                                                         'specify_range': [-300, 300],
                                                                                                                         'max_capacity': 13}}},
                                                                       'int64_1': {'other_params': {'dataset': 'random_algorithm',
                                                                                                    'algorithm_params': {'algorithm_name': 'fixed_value_range',
                                                                                                                         'specify_range': [-400, 432],
                                                                                                                         'batch': 50,
                                                                                                                         'max_capacity': 13}}},
                                                                       'varchar_1': {'other_params': {'dataset': 'random_algorithm',
                                                                                                      'algorithm_params': {'algorithm_name': 'random_range',
                                                                                                                           'specify_range': [-1500, 1500],
                                                                                                                           'max_capacity': 13}}}},
                                                    'dataset_name': 'sift',
                                                    'dataset_size': 2000000,
                                                    'ni_per': 5000},
                                 'collection_params': {'other_fields': ['sparse_float_vector', 'int8_1', 'int16_1', 'int32_1', 'int64_1', 'varchar_1', 'bool_1',
                                                                        'array_int8_1', 'array_int16_1', 'array_int32_1', 'array_int64_1', 'array_varchar_1',
                                                                        'array_bool_1'],
                                                       'shards_num': 1,
                                                       'auto_id': True},
                                 'resource_groups_params': {'reset': False},
                                 'database_user_params': {'reset_rbac': False, 'reset_db': False},
                                 'index_params': {'index_type': 'IVF_SQ8', 'index_param': {'nlist': 1024}},
                                 'concurrent_params': {'concurrent_number': 20, 'during_time': '3h', 'interval': 20, 'spawn_rate': None},
                                 'concurrent_tasks': [{'type': 'search',
                                                       'weight': 1,
                                                       'params': {'nq': 10,
                                                                  'top_k': 10,
                                                                  'search_param': {'nprobe': 16},
                                                                  'expr': 'int8_1 == 100',
                                                                  'guarantee_timestamp': None,
                                                                  'partition_names': None,
                                                                  'output_fields': ['id', 'float_vector', 'int64_1'],
                                                                  'ignore_growing': False,
                                                                  'group_by_field': None,
                                                                  'timeout': 60,
                                                                  'random_data': True,
                                                                  'check_task': 'check_search_output',
                                                                  'check_items': {'nq': 10}}},
                                                      {'type': 'query',
                                                       'weight': 1,
                                                       'params': {'ids': None,
                                                                  'expr': 'int64_1 > -1',
                                                                  'output_fields': ['*'],
                                                                  'offset': None,
                                                                  'limit': 10,
                                                                  'ignore_growing': False,
                                                                  'partition_names': None,
                                                                  'timeout': 60,
                                                                  'consistency_level': None,
                                                                  'random_data': False,
                                                                  'random_count': 0,
                                                                  'random_range': [0, 1],
                                                                  'field_name': 'id',
                                                                  'field_type': 'int64',
                                                                  'check_task': 'check_query_output',
                                                                  'check_items': {'expect_length': 10}}},
                                                      {'type': 'hybrid_search',
                                                       'weight': 1,
                                                       'params': {'nq': 10,
                                                                  'top_k': 1,
                                                                  'reqs': [{'search_param': {'nprobe': 128},
                                                                            'anns_field': 'float_vector',
                                                                            'expr': '(array_contains_any(array_int32_1, [0]) || array_contains(array_int64_1, '
                                                                                    '1)) || ((varchar_1 like "1%") and (bool_1 == True))',
                                                                            'top_k': 100},
                                                                           {'search_param': {'drop_ratio_search': 0.1},
                                                                            'anns_field': 'sparse_float_vector',
                                                                            'expr': 'not (int16_1 == int8_1) && ARRAY_CONTAINS_ANY(array_int64_1, [-1, 0, '
                                                                                    '1])'}],
                                                                  'rerank': {'RRFRanker': []},
                                                                  'output_fields': ['*'],
                                                                  'ignore_growing': False,
                                                                  'guarantee_timestamp': None,
                                                                  'partition_names': None,
                                                                  'timeout': 120,
                                                                  'random_data': True,
                                                                  'check_task': 'check_search_output',
                                                                  'check_items': {'output_fields': ['sparse_float_vector', 'int8_1', 'int16_1', 'int32_1',
                                                                                                    'int64_1', 'varchar_1', 'bool_1', 'array_int8_1',
                                                                                                    'array_int16_1', 'array_int32_1', 'array_int64_1',
                                                                                                    'array_varchar_1', 'array_bool_1', 'id', 'float_vector'],
                                                                                  'nq': 10}}},
                                                      {'type': 'load',
                                                       'weight': 1,
                                                       'params': {'replica_number': 1, 'timeout': 180, 'check_task': 'check_response', 'check_items': None}},
                                                      {'type': 'insert',
                                                       'weight': 1,
                                                       'params': {'nb': 10,
                                                                  'timeout': 30,
                                                                  'random_id': True,
                                                                  'random_vector': True,
                                                                  'varchar_filled': False,
                                                                  'start_id': 2000000,
                                                                  'shuffle_id': False,
                                                                  'check_task': 'check_response',
                                                                  'check_items': None}},
                                                      {'type': 'delete',
                                                       'weight': 1,
                                                       'params': {'expr': '',
                                                                  'delete_length': 10,
                                                                  'timeout': 30,
                                                                  'check_task': 'check_response',
                                                                  'check_items': None}},
                                                      {'type': 'flush',
                                                       'weight': 1,
                                                       'params': {'timeout': 600,
                                                                  'check_task': 'check_ignore_expected_errors',
                                                                  'check_items': [{'message': 'request is rejected by grpc RateLimiter middleware, please '
                                                                                              'retry later'},
                                                                                  {'message': 'wait for flush timeout'}]}}]},
            'run_id': 2024102551731872,
            'datetime': '2024-10-25 02:59:33.383302',
            'client_version': '2.5.0'},
 'result': {'test_result': {'index': {'RT': 928.5232,
                                      'sparse_float_vector': {'RT': 244.8948},
                                      'int8_1': {'RT': 101.311},
                                      'int16_1': {'RT': 0.6061},
                                      'int32_1': {'RT': 0.517},
                                      'int64_1': {'RT': 0.5269},
                                      'varchar_1': {'RT': 0.5139},
                                      'bool_1': {'RT': 0.5116},
                                      'array_int8_1': {'RT': 0.5183},
                                      'array_int16_1': {'RT': 0.5213},
                                      'array_int32_1': {'RT': 0.5343},
                                      'array_int64_1': {'RT': 0.5222},
                                      'array_varchar_1': {'RT': 0.5107},
                                      'array_bool_1': {'RT': 0.5112}},
                            'insert': {'total_time': 157.9593, 'VPS': 12661.4894, 'batch_time': 0.3949, 'batch': 5000},
                            'flush': {'RT': 3.0366},
                            'load': {'RT': 5.2977},
                            'Locust': {'Aggregated': {'Requests': 4170,
                                                      'Fails': 1747,
                                                      'RPS': 0.39,
                                                      'fail_s': 0.42,
                                                      'RT_max': 690441.5,
                                                      'RT_avg': 19181.56,
                                                      'TP50': 6,
                                                      'TP99': 446000.0},
                                       'delete': {'Requests': 537,
                                                  'Fails': 0,
                                                  'RPS': 0.05,
                                                  'fail_s': 0.0,
                                                  'RT_max': 70785.83,
                                                  'RT_avg': 5668.75,
                                                  'TP50': 9,
                                                  'TP99': 53000.0},
                                       'flush': {'Requests': 575,
                                                 'Fails': 0,
                                                 'RPS': 0.05,
                                                 'fail_s': 0.0,
                                                 'RT_max': 690441.5,
                                                 'RT_avg': 115020.61,
                                                 'TP50': 55000.0,
                                                 'TP99': 630000.0},
                                       'hybrid_search': {'Requests': 597,
                                                         'Fails': 597,
                                                         'RPS': 0.06,
                                                         'fail_s': 1.0,
                                                         'RT_max': 0,
                                                         'RT_avg': 0.0,
                                                         'TP50': 0,
                                                         'TP99': 0},
                                       'insert': {'Requests': 597,
                                                  'Fails': 0,
                                                  'RPS': 0.06,
                                                  'fail_s': 0.0,
                                                  'RT_max': 60038.93,
                                                  'RT_avg': 5832.49,
                                                  'TP50': 26,
                                                  'TP99': 60000.0},
                                       'load': {'Requests': 626,
                                                'Fails': 0,
                                                'RPS': 0.06,
                                                'fail_s': 0.0,
                                                'RT_max': 120007.31,
                                                'RT_avg': 11621.74,
                                                'TP50': 70,
                                                'TP99': 80000.0},
                                       'query': {'Requests': 651,
                                                 'Fails': 563,
                                                 'RPS': 0.06,
                                                 'fail_s': 0.86,
                                                 'RT_max': 8881.64,
                                                 'RT_avg': 75.17,
                                                 'TP50': 0,
                                                 'TP99': 3500.0},
                                       'search': {'Requests': 587,
                                                  'Fails': 587,
                                                  'RPS': 0.05,
                                                  'fail_s': 1.0,
                                                  'RT_max': 0,
                                                  'RT_avg': 0.0,
                                                  'TP50': 0,
                                                  'TP99': 0}}}}} 
```

**Comment by wangting0128** [comment]
**still exist**

image: 2.5-20241031-6b9b6999-amd64

client log:
<img width="1862" alt="截屏2024-11-01 17 27 13" src="https://github.com/user-attachments/assets/a82bd7b7-748d-4731-b1e2-89a854df6432">

/unassign @wangting0128

**Comment by NicoYuan1986** [comment]
also reproduced in nightly.  2.5(6b9b699)
link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI(new)/detail/2.5/5/pipeline/153
log: 
```
[pytest : test] [2024-11-01 03:52:28 - ERROR - pymilvus.decorators]: RPC error: [query], <MilvusException: (code=65535, message=fail to Query on QueryNode 1: worker(1) query failed: Operator::GetOutput failed for [Operator:PhyFilterBitsNode, plan node id: 6644] : Assert "(value_proto.val_case() == milvus::proto::plan::GenericValue::kFloatVal)"  at /workspace/source/internal/core/src/exec/expression/Utils.h:130
[pytest : test] )>, <Time:{'RPC start': '2024-11-01 03:52:28.219347', 'RPC error': '2024-11-01 03:52:28.995034'}> (decorators.py:140)
[pytest : test] [2024-11-01 03:52:28 - ERROR - ci_test]: Traceback (most recent call last):
[pytest : test]   File "/milvus/tests/python_client/utils/api_request.py", line 32, in inner_wrapper
[pytest : test]     res = func(*args, **_kwargs)
[pytest : test]   File "/milvus/tests/python_client/utils/api_request.py", line 63, in api_request
[pytest : test]     return func(*arg, **kwargs)
[pytest : test]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 1076, in query
[pytest : test]     return conn.query(
[pytest : test]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 141, in handler
[pytest : test]     raise e from e
[pytest : test]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 137, in handler
[pytest : test]     return func(*args, **kwargs)
[pytest : test]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 176, in handler
[pytest : test]     return func(self, *args, **kwargs)
[pytest : test]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 116, in handler
[pytest : test]     raise e from e
[pytest : test]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 86, in handler
[pytest : test]     return func(*args, **kwargs)
[pytest : test]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 1541, in query
[pytest : test]     check_status(response.status)
[pytest : test]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/utils.py", line 63, in check_status
[pytest : test]     raise MilvusException(status.code, status.reason, status.error_code)
[pytest : test] pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=fail to Query on QueryNode 1: worker(1) query failed: Operator::GetOutput failed for [Operator:PhyFilterBitsNode, plan node id: 6644] : Assert "(value_proto.val_case() == milvus::proto::plan::GenericValue::kFloatVal)"  at /workspace/source/internal/core/src/exec/expression/Utils.h:130
[pytest : test] )>
[pytest : test]  (api_request.py:45)
[pytest : test] [2024-11-01 03:52:28 - ERROR - ci_test]: (api_response) : <MilvusException: (code=65535, message=fail to Query on QueryNode 1: worker(1) query failed: Operator::GetOutput failed for [Operator:PhyFilterBitsNode, plan node id: 6644] : Assert "(value_proto.val_case() == milvus::proto::plan::GenericValue::kFloatVal)"  at /workspace/source/internal/core/src/exe...... (api_request.py:46)
```

**Comment by wangting0128** [comment]
### verification passed

argo task：memory-opt-scenes-7vrcm
image：master-20241108-a0315783-amd64
