### ISSUE TITLE
[Bug]: [Nightly] Query with expression failed when output count 

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#37274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: b44ef82
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Query with expression failed when output count.
```
[pytest : test] [2024-10-28 20:43:28 - DEBUG - ci_test]: (api_request)  : [Collection.query] args: ['(float + 1) == 3 or float * 2 == 64 or float == 10**2', ['count(*)'], None, 180], kwargs: {} (api_request.py:62)
[pytest : test] [2024-10-28 20:43:29 - ERROR - pymilvus.decorators]: RPC error: [query], <MilvusException: (code=65535, message=fail to Query on QueryNode 9: worker(9) query failed: Assert "(value_proto.val_case() == planpb::GenericValue::kFloatVal)"  at /workspace/source/internal/core/src/query/PlanProto.cpp:152
[pytest : test] )>, <Time:{'RPC start': '2024-10-28 20:43:28.060369', 'RPC error': '2024-10-28 20:43:29.049176'}> (decorators.py:147)
[pytest : test] [2024-10-28 20:43:29 - ERROR - ci_test]: Traceback (most recent call last):
[pytest : test]   File "/milvus/tests/python_client/utils/api_request.py", line 32, in inner_wrapper
[pytest : test]     res = func(*args, **_kwargs)
[pytest : test]   File "/milvus/tests/python_client/utils/api_request.py", line 63, in api_request
[pytest : test]     return func(*arg, **kwargs)
[pytest : test]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 1076, in query
[pytest : test]     return conn.query(
[pytest : test]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 148, in handler
[pytest : test]     raise e from e
[pytest : test]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 144, in handler
[pytest : test]     return func(*args, **kwargs)
[pytest : test]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 183, in handler
[pytest : test]     return func(self, *args, **kwargs)
[pytest : test]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 123, in handler
[pytest : test]     raise e from e
[pytest : test]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 87, in handler
[pytest : test]     return func(*args, **kwargs)
[pytest : test]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 1536, in query
[pytest : test]     check_status(response.status)
[pytest : test]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/utils.py", line 63, in check_status
[pytest : test]     raise MilvusException(status.code, status.reason, status.error_code)
[pytest : test] pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=fail to Query on QueryNode 9: worker(9) query failed: Assert "(value_proto.val_case() == planpb::GenericValue::kFloatVal)"  at /workspace/source/internal/core/src/query/PlanProto.cpp:152
[pytest : test] )>
[pytest : test]  (api_request.py:45)
[pytest : test] [2024-10-28 20:43:29 - ERROR - ci_test]: (api_response) : <MilvusException: (code=65535, message=fail to Query on QueryNode 9: worker(9) query failed: Assert "(value_proto.val_case() == planpb::GenericValue::kFloatVal)"  at /workspace/source/internal/core/src/query/PlanProto.cpp:152
[pytest : test] )> (api_request.py:46)
```

### Expected Behavior

pass

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI(new)/detail/2.4/66/pipeline/134
2. log: [artifacts-milvus-distributed-kafka-mdk-24-66-py-n-66-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20Nightly%20CI(new)/job/2.4/66/artifact/artifacts-milvus-distributed-kafka-mdk-24-66-py-n-66-e2e-logs.tar.gz)
3. error case: test_count_expression_auto_field

**Comment by xiaofan-luan** [comment]
can you try float * 2 == 64.0 can work?
I'm assuming this is a expression need implicit conversion and we don't support

**Comment by yanliang567** [comment]
> can you try float * 2 == 64.0 can work? I'm assuming this is a expression need implicit conversion and we don't support

It works on master and before

**Comment by xiaocai2333** [comment]
It seems that converting variables to float was omitted when supporting expression templates.
I will fix it.

**Comment by xiaocai2333** [comment]
It has been fixed, please verify.
/assign @NicoYuan1986 
/unassign

**Comment by NicoYuan1986** [comment]
fixed. master-20241106-8275e40f
