### ISSUE TITLE
[Bug]: [null & default] The data "None" is filtered out by keyword match expression "not TEXT_MATCH" which should not when enable nullable and keyword match simultaneously

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#37508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20241105-b83b376c-amd64
- Deployment mode(standalone or cluster):both
- MQ type(rocksmq, pulsar or kafka):    all
- SDK version(e.g. pymilvus v2.0.0rc2): 2.5.0rc107
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The data "None" is filtered by keyword match expression "not TEXT_MATCH" which should not when enable nullable and keyword match simultaneously

```
>>> r = collection.query(expr="not TEXT_MATCH(title, 'The')", output_fields=["id", "title"])
>>>
>>> r
data: ["{'id': 1, 'title': None}", "{'id': 4, 'title': None}"]
```

### Expected Behavior

The data "None" is not filtered by keyword match expression "not TEXT_MATCH" 

### Steps To Reproduce

```python
from pymilvus import (
     connections,
     FieldSchema, CollectionSchema, DataType,
     Collection,
 )
DIMENSION = 8
COLLECTION_NAME = "books"
connections.connect()

fields = [
     FieldSchema(name='id', dtype=DataType.INT64, is_primary=True),
     FieldSchema(name='title', dtype=DataType.VARCHAR, max_length=200, enable_match=True, enable_tokenizer=True, nullable=True),
     FieldSchema(name='release_year', dtype=DataType.INT64),
     FieldSchema(name='embeddings', dtype=DataType.FLOAT_VECTOR, dim=DIMENSION),
 ]
schema = CollectionSchema(fields=fields, enable_dynamic_field=True)
collection = Collection(name=COLLECTION_NAME, schema=schema)
data_rows = [
     {
         "id": 1,
         "title": None,
         "release_year": 1954,
         "embeddings": [0.64, 0.44, 0.13, 0.47, 0.74, 0.03, 0.32, 0.6],
     },
     {
         "id": 2,
         "title": "The Great Gatsby",
         "release_year": 1925,
         "embeddings": [0.9, 0.45, 0.18, 0.43, 0.4, 0.4, 0.7, 0.24],
     },
     {
         "id": 3,
         "title": "The Catcher in the Rye",
         "release_year": 1951,
         "embeddings": [0.43, 0.57, 0.43, 0.88, 0.84, 0.69, 0.27, 0.98],
     },
     {
         "id": 4,
         "title": None,
         "release_year": 2010,
         "embeddings": [0.84, 0.69, 0.27, 0.43, 0.57, 0.43, 0.88, 0.98],
     },
 ]

collection.insert(data_rows)
collection.create_index("embeddings", {"index_type": "FLAT", "metric_type": "L2"})
collection.load()
collection.flush()
r = collection.query(expr="TEXT_MATCH(title, 'The')", output_fields=["id", "title"])
print(r)
r = collection.query(expr="not TEXT_MATCH(title, 'The')", output_fields=["id", "title"])
print(r)
```

### Milvus Log

https://grafana-4am.zilliz.cc/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcluster%3D%5C%22devops%5C%22,namespace%3D%5C%22chaos-testing%5C%22,pod%3D~%5C%22test-null-master-wknnw.*%5C%22%7D%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D

**Comment by binbinlv** [comment]
working on verification.

**Comment by binbinlv** [comment]
Verification is failed:

querynode is crashed when query with TEXT_MATCH in this case:

milvus:
pymilvus
milvus: master-20241114-1304b405-amd64
pymilvus: 2.5.0rc119

results:
```
>>> from pymilvus import (
...      connections,
...      FieldSchema, CollectionSchema, DataType,
...      Collection,
...  )
DIMENSION = 8
COLLECTION_NAME = "books"
>>> DIMENSION = 8
>>> COLLECTION_NAME = "books"
>>>
>>> connections.connect(host="10.101.33.102")
>>> fields = [
...      FieldSchema(name='id', dtype=DataType.INT64, is_primary=True),
...      FieldSchema(name='title', dtype=DataType.VARCHAR, max_length=200, enable_match=True, enable_tokenizer=True, nullable=True),
...      FieldSchema(name='release_year', dtype=DataType.INT64),
...      FieldSchema(name='embeddings', dtype=DataType.FLOAT_VECTOR, dim=DIMENSION),
...  ]
>>> schema = CollectionSchema(fields=fields, enable_dynamic_field=True)
>>> collection = Collection(name=COLLECTION_NAME, schema=schema)
data_rows = [
     {
         "id": 1,
         "title": None,
         "release_year": 1954,
         "embeddings": [0.64, 0.44, 0.13, 0.47, 0.74, 0.03, 0.32, 0.6],
     },
     {
         "id": 2,
         "title": "The Great Gatsby",
         "release_year": 1925,
         "embeddings": [0.9, 0.45, 0.18, 0.43, 0.4, 0.4, 0.7, 0.24],
     },
     {
         "id": 3,
         "title": "The Catcher in the Rye",
         "release_year": 1951,
         "embeddings": [0.43, 0.57, 0.43, 0.88, 0.84, 0.69, 0.27, 0.98],
     },
     {
         "id": 4,
         "title": None,
         "release_year": 2010,
         "embeddings": [0.84, 0.69, 0.27, 0.43, 0.57, 0.43, 0.88, 0.98],
     },
 ]>>> data_rows = [
...      {
...          "id": 1,
...          "title": None,
...          "release_year": 1954,
...          "embeddings": [0.64, 0.44, 0.13, 0.47, 0.74, 0.03, 0.32, 0.6],
...      },
...      {
...          "id": 2,
...          "title": "The Great Gatsby",
...          "release_year": 1925,
...          "embeddings": [0.9, 0.45, 0.18, 0.43, 0.4, 0.4, 0.7, 0.24],
...      },
...      {
...          "id": 3,
...          "title": "The Catcher in the Rye",
...          "release_year": 1951,
...          "embeddings": [0.43, 0.57, 0.43, 0.88, 0.84, 0.69, 0.27, 0.98],
...      },
...      {
...          "id": 4,
...          "title": None,
...          "release_year": 2010,
...          "embeddings": [0.84, 0.69, 0.27, 0.43, 0.57, 0.43, 0.88, 0.98],
...      },
...  ]
>>> collection.insert(data_rows)
(insert count: 4, delete count: 0, upsert count: 0, timestamp: 453917229069107205, success count: 4, err count: 0
>>> collection.create_index("embeddings", {"index_type": "FLAT", "metric_type": "L2"})
Status(code=0, message=)
>>> collection.load()
>>> collection.flush()

>>>
>>> r = collection.query(expr="TEXT_MATCH(title, 'The')", output_fields=["id", "title"])
print(r)

RPC error: [query], <MilvusException: (code=503, message=failed to query: segment lacks[segment=453764290321212395]: channel not available[channel=by-dev-rootcoord-dml_10_453764290321208660v0])>, <Time:{'RPC start': '2024-11-14 12:00:49.373742', 'RPC error': '2024-11-14 12:01:10.704557'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 1076, in query
    return conn.query(
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 141, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 137, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 176, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 116, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 86, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 1542, in query
    check_status(response.status)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/utils.py", line 63, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=503, message=failed to query: segment lacks[segment=453764290321212395]: channel not available[channel=by-dev-rootcoord-dml_10_453764290321208660v0])>
```

node info:
![04abf552-e0b2-42cb-937f-9fd203b792a7](https://github.com/user-attachments/assets/5b19ef31-4ee3-4930-9950-9d9d78503325)


log:
https://qtp.zilliz.cc/run/submitTask?taskType=DeployServer&region=devops&taskId=10344

**Comment by binbinlv** [comment]
set it as urgent because the new code leads to the milvus crash.

**Comment by smellthemoon** [comment]
'enable_tokenizer' has convert to 'enable_analyzer', please try to use the new one to test. @binbinlv

**Comment by binbinlv** [comment]
Yes, when the parameter 'enable_tokenizer" is modified to "enable_analyzer", the result is good.

```
>>> r = collection.query(expr="TEXT_MATCH(title, 'The')", output_fields=["id", "title"])
>>> r
data: ["{'id': 2, 'title': 'The Great Gatsby'}", "{'id': 3, 'title': 'The Catcher in the Rye'}"]
>>> r = collection.query(expr="not TEXT_MATCH(title, 'The')", output_fields=["id", "title"])
>>> r
data: []
```

But this issue still exists, crash is not acceptable even if the parameter name is not right.

**Comment by smellthemoon** [comment]
I will try to handle the error by segcore more reasonably to avoid crashing.

**Comment by binbinlv** [comment]
verified and fixed:

milvus: master-20241115-d1596297-amd64
pymilvus: 2.5.0rc121


results:
```
>>> fields = [
...      FieldSchema(name='id', dtype=DataType.INT64, is_primary=True),
...      FieldSchema(name='title', dtype=DataType.VARCHAR, max_length=200, enable_match=True, enable_tokenizer=True, nullable=True),
...      FieldSchema(name='release_year', dtype=DataType.INT64),
...      FieldSchema(name='embeddings', dtype=DataType.FLOAT_VECTOR, dim=DIMENSION),
...  ]
>>> schema = CollectionSchema(fields=fields, enable_dynamic_field=True)
>>> collection = Collection(name=COLLECTION_NAME, schema=schema)
RPC error: [create_collection], <MilvusException: (code=65535, message=field title is set to enable match or bm25 function but not enable analyzer)>, <Time:{'RPC start': '2024-11-16 10:42:49.712003', 'RPC error': '2024-11-16 10:42:49.740039'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 150, in __init__
    conn.create_collection(self._name, schema, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 141, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 137, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 176, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 116, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 86, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 309, in create_collection
    check_status(status)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/utils.py", line 63, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=field title is set to enable match or bm25 function but not enable analyzer)>
```
