### ISSUE TITLE
[Bug]: [new_indexes] Create new HNSW_PRQ index time out for BFLOAT16_VECTOR

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#37602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20241112-b5b00355-amd64
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):    all
- SDK version(e.g. pymilvus v2.0.0rc2): 2.5.0rc118
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Create new HNSW_PRQ index time out for BFLOAT16_VECTOR

```
[2024-11-12 12:31:28 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['BFLOAT16_VECTORnew', {'index_type': 'FAISS_HNSW_PRQ', 'params': {'m': 32, 'nbits': 12, 'nrq': 8}, 'metric_type': 'IP'}, 1200], kwargs: {'index_name': 'BFLOAT16_VECTORnew'} (api_request.py:62)
[2024-11-12 12:51:28 - WARNING - pymilvus.decorators]: Retry timeout: 1200s (decorators.py:106)
[2024-11-12 12:51:28 - ERROR - pymilvus.decorators]: RPC error: [wait_for_creating_index], <MilvusException: (code=1, message=Retry timeout: 1200s, message=collection TestGroupSearchNewHNSWIndex_iaAaFraN create index BFLOAT16_VECTORnew timeout in 1200s)>, <Time:{'RPC start': '2024-11-12 12:31:28.237006', 'RPC error': '2024-11-12 12:51:28.669547'}> (decorators.py:140)
[2024-11-12 12:51:28 - WARNING - pymilvus.decorators]: Retry timeout: 1200s (decorators.py:106)
[2024-11-12 12:51:28 - ERROR - pymilvus.decorators]: RPC error: [create_index], <MilvusException: (code=1, message=Retry timeout: 1200s, message=Retry timeout: 1200s, message=collection TestGroupSearchNewHNSWIndex_iaAaFraN create index BFLOAT16_VECTORnew timeout in 1200s)>, <Time:{'RPC start': '2024-11-12 12:31:28.137710', 'RPC error': '2024-11-12 12:51:28.669840'}> (decorators.py:140)
[2024-11-12 12:51:28 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/binbin/zillizProjects/milvus_latest_runnable/tests/python_client/utils/api_request.py", line 32, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/Users/binbin/zillizProjects/milvus_latest_runnable/tests/python_client/utils/api_request.py", line 63, in api_request
    return func(*arg, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 1373, in create_index
    return conn.create_index(self._name, field_name, index_params, timeout=timeout, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 141, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 137, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 176, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 107, in handler
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 1200s, message=Retry timeout: 1200s, message=collection TestGroupSearchNewHNSWIndex_iaAaFraN create index BFLOAT16_VECTORnew timeout in 1200s)>
 (api_request.py:45)
```

### Expected Behavior

Create new HNSW_PRQ index successfully for BFLOAT16_VECTOR

### Steps To Reproduce

```python
    @pytest.mark.tags(CaseLabel.L0)
    @pytest.mark.parametrize("group_by_field", [DataType.VARCHAR.name, "varchar_inverted"])
    def test_search_group_size_new_hnsw_index(self, group_by_field):
        """
        target:
            1. search on 4 different float vector fields with group by varchar field with group size
        verify results entity = limit * group_size  and group size is full if group_strict_size is True
        verify results group counts = limit if group_strict_size is False
        """
        nq = 2
        limit = 50
        group_size = 5
        for j in range(len(self.vector_fields)):
            search_vectors = cf.gen_vectors(nq, dim=self.dims[j], vector_data_type=self.vector_fields[j])
            search_params = {"params": cf.get_search_params_params(self.index_types[j])}
            # when group_strict_size=true, it shall return results with entities = limit * group_size
            res1 = self.collection_wrap.search(data=search_vectors, anns_field=self.vector_fields[j],
                                               param=search_params, limit=limit,
                                               group_by_field=group_by_field,
                                               group_size=group_size, group_strict_size=True,
                                               output_fields=[group_by_field])[0]
            for i in range(nq):
                assert len(res1[i]) == limit * group_size
                for l in range(limit):
                    group_values = []
                    for k in range(group_size):
                        group_values.append(res1[i][l*group_size+k].fields.get(group_by_field))
                    assert len(set(group_values)) == 1

            # when group_strict_size=false, it shall return results with group counts = limit
            res1 = self.collection_wrap.search(data=search_vectors, anns_field=self.vector_fields[j],
                                               param=search_params, limit=limit,
                                               group_by_field=group_by_field,
                                               group_size=group_size, group_strict_size=False,
                                               output_fields=[group_by_field])[0]
            for i in range(nq):
                group_values = []
                for l in range(len(res1[i])):
                    group_values.append(res1[i][l].fields.get(group_by_field))
                assert len(set(group_values)) == limit
```

### Milvus Log

https://grafana-4am.zilliz.cc/explore?orgId=1&panes=%7B%22dY5%22:%7B%22datasource%22:%22vhI6Vw67k%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcluster%3D%5C%22devops%5C%22,namespace%3D%5C%22chaos-testing%5C%22,pod%3D~%5C%22test-null-master-cjqsw.%2A%5C%22%7D%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22vhI6Vw67k%22%7D%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1

### Anything else?

collection name：TestGroupSearchNewHNSWIndex_iaAaFraN

index:
```
[Collection.create_index] args: ['BFLOAT16_VECTORnew', {'index_type': 'FAISS_HNSW_PRQ', 'params': {'m': 32, 'nbits': 12, 'nrq': 8}, 'metric_type': 'IP'}, 1200], kwargs: {'index_name': 'BFLOAT16_VECTORnew'}
```

**Comment by foxspy** [comment]
The runtime for PRQ is approximately calculated as  niter (10) * row * dim * 2^nbits * nrq, nbits = 12 and nrq = 8 are really large, which can influence the total execution time. You can adjust nbits = 8 and nrq = 2, then the execution time can be reduced a lot.

**Comment by foxspy** [comment]
@alexanderguzhva Please help confirm again. I tried, and with this parameter configuration, indexing 10,000 * dim 128 entries takes over half an hour. After adjusting the configuration, it takes around 50 seconds. For 10,000 * dim 128, it still feels a bit long; if dim is large and the dataset is bigger, it seems PRQ could easily reach hours of processing time. Is this perhaps a bit too long?

**Comment by binbinlv** [comment]
> The runtime for PRQ is approximately calculated as niter (10) * row * dim * 2^nbits * nrq, nbits = 12 and nrq = 8 are really large, which can influence the total execution time. You can adjust nbits = 8 and nrq = 2, then the execution time can be reduced a lot.

When adjusting the parameters ('m': 32, 'nbits': 8, 'nrq': 2), PRQ index is created successfully in about 50s.

**Comment by binbinlv** [comment]
OK, cancel urgent label, but keep this issue open for tracking the future optimization.

**Comment by yanliang567** [comment]
close for this is by design for now
