### ISSUE TITLE
[Bug]: An error related to gRPC occurred when creating a connection using the MilvusClientV2 Java SDK.

### ISSUE THREAD

**Issue by davewxt** [milvus-io/milvus#37613]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.4.15
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.4.4
- OS(Ubuntu or CentOS): windows本地
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

    ConnectConfig connectConfig = ConnectConfig.builder()            
     .uri("http://xxxx:19530")               
    .dbName(dataBaseName)            
     .token("root:Milvus")             
     .idleTimeoutMs(5L)      
     .connectTimeoutMs(5L)             
    .build();         
 MilvusClientV2 milvusClientV2=new MilvusClientV2(connectConfig);       
  ListDatabasesResp listDatabasesResponse = milvusClientV2.listDatabases();   

### Expected Behavior

  Exception in thread "main" io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 0.892720700s. Name resolution delay 0.001561200 seconds. [closed=[], open=[[buffered_nanos=911662800, waiting_for_connection]]] 	at io.grpc.StatusRuntimeException.fillInStackTrace(StatusRuntimeException.java:68) 	at io.grpc.StatusRuntimeException.<init>(StatusRuntimeException.java:58) 	at io.grpc.StatusRuntimeException.<init>(StatusRuntimeException.java:50) 	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:268) 	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:249) 	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:167) 	at io.milvus.grpc.MilvusServiceGrpc$MilvusServiceBlockingStub.connect(MilvusServiceGrpc.java:4685) 	at io.milvus.v2.client.MilvusClientV2.connect(MilvusClientV2.java:147) 	at io.milvus.v2.client.MilvusClientV2.connect(MilvusClientV2.java:109) 	at io.milvus.v2.client.MilvusClientV2.<init>(MilvusClientV2.java:88) 	at com.sanofi.vector.rep.meta.main(meta.java:69)

### Steps To Reproduce

```markdown
1.milvus-java-sdk 2.4.4
2.jdk8
3.SpringBoot 2.6.0
4.milvus 版本2.14.5
```

### Milvus Log

  Exception in thread "main" io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 0.892720700s. Name resolution delay 0.001561200 seconds. [closed=[], open=[[buffered_nanos=911662800, waiting_for_connection]]] 	at io.grpc.StatusRuntimeException.fillInStackTrace(StatusRuntimeException.java:68) 	at io.grpc.StatusRuntimeException.<init>(StatusRuntimeException.java:58) 	at io.grpc.StatusRuntimeException.<init>(StatusRuntimeException.java:50) 	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:268) 	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:249) 	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:167) 	at io.milvus.grpc.MilvusServiceGrpc$MilvusServiceBlockingStub.connect(MilvusServiceGrpc.java:4685) 	at io.milvus.v2.client.MilvusClientV2.connect(MilvusClientV2.java:147) 	at io.milvus.v2.client.MilvusClientV2.connect(MilvusClientV2.java:109) 	at io.milvus.v2.client.MilvusClientV2.<init>(MilvusClientV2.java:88) 	at com.sanofi.vector.rep.meta.main(meta.java:69)

### Anything else?

  Exception in thread "main" io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 0.892720700s. Name resolution delay 0.001561200 seconds. [closed=[], open=[[buffered_nanos=911662800, waiting_for_connection]]] 	at io.grpc.StatusRuntimeException.fillInStackTrace(StatusRuntimeException.java:68) 	at io.grpc.StatusRuntimeException.<init>(StatusRuntimeException.java:58) 	at io.grpc.StatusRuntimeException.<init>(StatusRuntimeException.java:50) 	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:268) 	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:249) 	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:167) 	at io.milvus.grpc.MilvusServiceGrpc$MilvusServiceBlockingStub.connect(MilvusServiceGrpc.java:4685) 	at io.milvus.v2.client.MilvusClientV2.connect(MilvusClientV2.java:147) 	at io.milvus.v2.client.MilvusClientV2.connect(MilvusClientV2.java:109) 	at io.milvus.v2.client.MilvusClientV2.<init>(MilvusClientV2.java:88) 	at com.sanofi.vector.rep.meta.main(meta.java:69)

**Comment by davewxt** [comment]
It has already been changed to English. Please help to have a look. The project team is urging urgently now.

**Comment by davewxt** [comment]
It has already been changed to English. Please help to have a look. The project team is urging urgently now.

**Comment by yanliang567** [comment]
I don't think milvus supports running on Windows. do you mean you running on Windows docker? 
Please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation.
For Milvus installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs.

/assign @davewxt

**Comment by davewxt** [comment]
@yanliang567   My Milvus is installed on Kubernetes and proxied to the local machine via a proxy method. This set of old APIs can be tested locally on Windows, but some functions are not supported. 


 final MilvusServiceClient milvusClient = new MilvusServiceClient(
                ConnectParam.newBuilder()
                        .withHost("127.0.0.1")
                        .withPort(19530)
                        .withToken("root:Milvus")
                        .withDatabaseName(dataBaseName)
                        .build()
        );

        DescribeCollectionParam describeCollectionReq = DescribeCollectionParam.newBuilder()
                .withCollectionName("meta_collection1")
                .build();

        R<DescribeCollectionResponse> describeCollectionRes = milvusClient.describeCollection(describeCollectionReq);

        System.out.println(describeCollectionRes)

**Comment by xiaofan-luan** [comment]
@davewxt 
are you able to ping the milvus end point? We want to make sure there is no network issue here.

could you connect with attu and check if milvus service is all start as expected? or you can offer some log from server side

**Comment by ditunes** [comment]
i. also has same problem 
i config  the time: .rpcDeadlineMs(1000000).connectTimeoutMs(10000).keepAliveTimeoutMs(10000) but  after 0.5727549 not match my rpcDeadLineMs 

=========
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.milvus.v2.client.MilvusClientV2]: Factory method 'buildClient' threw exception; nested exception is io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 0.572754931s. [buffered_nanos=639915539, waiting_for_connection]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:641)
	... 126 common frames omitted
Caused by: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 0.572754931s. [buffered_nanos=639915539, waiting_for_connection]
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at io.milvus.grpc.MilvusServiceGrpc$MilvusServiceBlockingStub.connect(MilvusServiceGrpc.java:4685)
	at io.milvus.v2.client.MilvusClientV2.connect(MilvusClientV2.java:147)
	at io.milvus.v2.client.MilvusClientV2.connect(MilvusClientV2.java:109)
	at io.milvus.v2.client.MilvusClientV2.<init>(MilvusClientV2.java:88)

**Comment by yanliang567** [comment]
/assign @yhmo 
could you please help to take a look?
/unassign

**Comment by yhmo** [comment]
This is an issue of Java SDK v2.4.4, and the issue has been fixed in Java SDK v2.4.6.

v2.4.4 implemented an enhancement "Check connection when MilvusClientV2 is initialized", MilvusClientV2 constructor calls rpc interface connect() to pass client-side info to the server. The timeout value is hard-coded to 1 second. In some situations, it might fail to initial MilvusClientV2 with network problems.
Release note of v2.4.4: https://github.com/milvus-io/milvus-sdk-java/releases/tag/v2.4.4

In v2.4.6, this issue is fixed by using the ConnectConfig.getConnectTimeoutMs() as timeout value. The pr: https://github.com/milvus-io/milvus-sdk-java/commit/5aad7eaeab3889444a29c215cf1e71af53776ee4#diff-c48afd85609945d617ade1d709121915730da7a037f300b009e3e46b8b0867da
Release note of v2.4.6 https://github.com/milvus-io/milvus-sdk-java/releases/tag/v2.4.6

So, upgrade your Java SDK to v2.4.6 can fix this issue. Note that the default value of getConnectTimeoutMs() is 10 seconds.

**Comment by BongBongBang** [comment]
uhhhh, it still exists in  sdk 2.4.9

**Comment by BongBongBang** [comment]
Same exception stack trace

**Comment by yhmo** [comment]
> uhhhh, it still exists in sdk 2.4.9

If your sdk failed with "deadline exceeded after 10.xxxxx s.", the reason could be: the milvus server is not ready, or the address/port is incorrect.
