### ISSUE TITLE
[Bug]: pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on 3.80.209.190:19530, illegal connection params or server unavailable)>

### ISSUE THREAD

**Issue by SauravMishraaa** [milvus-io/milvus#37616]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 
- Deployment mode(standalone or cluster): Standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 4
- GPU: 
- Others:
```

### Current Behavior

Milvus is unable to being accessed from other pc and also unable to deploy it. This is my vm ip `3.80.209.190` .  But when I saw on my vm it is clearly working
![Screenshot (496)](https://github.com/user-attachments/assets/d55df396-4386-40fc-b688-da6c55935408)

### Milvus Log

/eks-deployment/app-service# k logs search-engine-7f89f4fb96-kt75c -n search-engine
INFO:     Started server process [8]
INFO:     Waiting for application startup.
ERROR:    Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 147, in _wait_for_channel_ready
    grpc.channel_ready_future(self._channel).result(timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/grpc/_utilities.py", line 162, in result
    self._block(timeout)
  File "/usr/local/lib/python3.10/site-packages/grpc/_utilities.py", line 106, in _block
    raise grpc.FutureTimeoutError()
grpc.FutureTimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 569, in __aenter__
    await self._router.startup()
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 670, in startup
    await handler()
  File "/app/app.py", line 22, in startup_event
    connect_to_milvus(config=config, timeout=30)
  File "/app/milvus_utils.py", line 8, in connect_to_milvus
    connections.connect(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/usr/local/lib/python3.10/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on 3.80.209.190:19530, illegal connection params or server unavailable)>

ERROR:    Application startup failed. Exiting.

**Comment by yanliang567** [comment]
@SauravMishraaa can you try to telnet the milvus address and port on the pc? if yes, please provide milvus logs for us.
Please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation.
For Milvus installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs.
/assign @SauravMishraaa 
/unassign

**Comment by SauravMishraaa** [comment]
I have tried it earlier , i tried to telnet the address but there was no response.

**Comment by SauravMishraaa** [comment]
you mean maybe the firewall is blocking the connection? but i don't think that is the case here. the server is not being accessed publicily.
