### ISSUE TITLE
[Bug]: Milvus-java-sdk 打包后不可用, gRpc相关报错

### ISSUE THREAD

**Issue by xiaojunxiang2023** [milvus-io/milvus#37773]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
Milvus Server: 2.4.11
Milvus-java-sdk: 2.4.3
```

### Current Behavior

一段最简单的 Milvus java客户端demo, idea里能正常运行：
![image](https://github.com/user-attachments/assets/f679e6ac-1ad0-4d54-bf1f-5e4a80839c37)

但是打 jar包后再跑就报错:
![image](https://github.com/user-attachments/assets/6b5a8a64-13c9-4f53-aba1-88e0d3276071)
![image](https://github.com/user-attachments/assets/45c0b1f4-f9ab-467e-a379-ed91f52eac8d)

### Expected Behavior

打包后依旧能正常运行

### Steps To Reproduce

```markdown
pom.xml:
    <dependencies>
        <dependency>
            <groupId>io.milvus</groupId>
            <artifactId>milvus-sdk-java</artifactId>
            <version>2.4.1</version>
        </dependency>
    </dependencies>
    
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.5.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <descriptorRefs>
                                <descriptorRef>jar-with-dependencies</descriptorRef>
                            </descriptorRefs>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

Main.java:
  public static void main(String[] args) {
    String dbName = "default";
    String collectionName = "a";
    System.out.println("collectionName: " + collectionName);
    String proxyUri = "http://10.148.40.27:19530";
    // 创建 Client
    MilvusClientV2 client = new MilvusClientV2(ConnectConfig.builder().uri(proxyUri).dbName(dbName).build());
    DescribeCollectionReq describeCollectionReq = DescribeCollectionReq.builder()
        .collectionName(collectionName)
        .build();
    DescribeCollectionResp describeCollectionResp = client.describeCollection(describeCollectionReq);
    System.out.println(describeCollectionResp + "\n\n");
  }
```

### Milvus Log

`Exception in thread "main" io.grpc.StatusRuntimeException: UNKNOWN
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:268)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:249)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:167)
        at io.milvus.grpc.MilvusServiceGrpc$MilvusServiceBlockingStub.listDatabases(MilvusServiceGrpc.java:4621)
        at io.milvus.v2.utils.ClientUtils.checkDatabaseExist(ClientUtils.java:107)
        at io.milvus.v2.client.MilvusClientV2.connect(MilvusClientV2.java:89)
        at io.milvus.v2.client.MilvusClientV2.<init>(MilvusClientV2.java:60)
        at org.example.Main.main(Main.java:20)
Caused by: java.nio.channels.UnsupportedAddressTypeException
        at sun.nio.ch.Net.checkAddress(Net.java:97)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:620)
        at io.grpc.netty.shaded.io.netty.util.internal.SocketUtils$3.run(SocketUtils.java:91)
        at io.grpc.netty.shaded.io.netty.util.internal.SocketUtils$3.run(SocketUtils.java:88)
        at java.security.AccessController.doPrivileged(Native Method)
        at io.grpc.netty.shaded.io.netty.util.internal.SocketUtils.connect(SocketUtils.java:88)
        at io.grpc.netty.shaded.io.netty.channel.socket.nio.NioSocketChannel.doConnect(NioSocketChannel.java:322)
        at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.connect(AbstractNioChannel.java:248)
        at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1342)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:653)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:632)
        at io.grpc.netty.shaded.io.netty.channel.ChannelDuplexHandler.connect(ChannelDuplexHandler.java:54)
        at io.grpc.netty.shaded.io.grpc.netty.WriteBufferingAndExceptionHandler.connect(WriteBufferingAndExceptionHandler.java:157)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:655)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.access$1000(AbstractChannelHandlerContext.java:61)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext$9.run(AbstractChannelHandlerContext.java:637)
        at io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:750)
`

**Comment by yhmo** [comment]
It is not a milvus sdk issue but maven packaging issue:
https://stackoverflow.com/questions/73286776/grpc-unsupportedaddresstypeexception-but-only-when-packaged-with-shadowjar
