### ISSUE TITLE
[Bug]: NotOneValueFound Error while connection

### ISSUE THREAD

**Issue by joyatcloudfall** [milvus-io/milvus#37848]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4.15
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus v2.4.9
- OS(Ubuntu or CentOS): CentOs
- CPU/Memory: 4C 8G
- GPU: None
- Others:
```

### Current Behavior

I install Milvus according to [Run Milvus with Docker Compose](https://milvus.io/docs/zh/install_standalone-docker-compose.md)

```
wget https://github.com/milvus-io/milvus/releases/download/v2.4.15/milvus-standalone-docker-compose.yml -O docker-compose.yml

sudo docker-compose up -d
⠿ Network milvus               Created
⠿ Container milvus-minio       Started
⠿ Container milvus-etcd        Started
⠿ Container milvus-standalone  Started

sudo docker logs -f milvus-standalone

2024/11/20 09:09:14 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined

    __  _________ _   ____  ______    
   /  |/  /  _/ /| | / / / / / __/    
  / /|_/ // // /_| |/ / /_/ /\ \    
 /_/  /_/___/____/___/\____/___/     

Welcome to use Milvus!
Version:   v2.4.15
Built:     Tue Nov  5 07:21:59 UTC 2024
GitCommit: b7c80f9
GoVersion: go version go1.21.11 linux/amd64

TotalMem: 8323067904
UsedMem: 21970944

open pid file: /run/milvus/standalone.pid
lock pid file: /run/milvus/standalone.pid
```

Then I try this example:
```
from pymilvus import connections, db
conn = connections.connect(host="192.xx.xx.214", port=19530)
database = db.create_database("my_database")
```
But got the following error:
```
Traceback (most recent call last):
  File "c:\Users\Joy\anaconda3\envs\codey\Lib\site-packages\IPython\core\interactiveshell.py", line 2105, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Joy\anaconda3\envs\codey\Lib\site-packages\IPython\core\ultratb.py", line 1428, in structured_traceback
    return FormattedTB.structured_traceback(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Joy\anaconda3\envs\codey\Lib\site-packages\IPython\core\ultratb.py", line 1319, in structured_traceback
    return VerboseTB.structured_traceback(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Joy\anaconda3\envs\codey\Lib\site-packages\IPython\core\ultratb.py", line 1172, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Joy\anaconda3\envs\codey\Lib\site-packages\IPython\core\ultratb.py", line 1087, in format_exception_as_a_whole
    frames.append(self.format_record(record))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Joy\anaconda3\envs\codey\Lib\site-packages\IPython\core\ultratb.py", line 969, in format_record
    frame_info.lines, Colors, self.has_colors, lvals
    ^^^^^^^^^^^^^^^^
  File "c:\Users\Joy\anaconda3\envs\codey\Lib\site-packages\IPython\core\ultratb.py", line 792, in lines
    return self._sd.lines
           ^^^^^^^^^^^^^^
  File "c:\Users\Joy\anaconda3\envs\codey\Lib\site-packages\stack_data\utils.py", line 144, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
                                               ^^^^^^^^^^^^^^
  File "c:\Users\Joy\anaconda3\envs\codey\Lib\site-packages\stack_data\core.py", line 734, in lines
    pieces = self.included_pieces
             ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Joy\anaconda3\envs\codey\Lib\site-packages\stack_data\utils.py", line 144, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
                                               ^^^^^^^^^^^^^^
  File "c:\Users\Joy\anaconda3\envs\codey\Lib\site-packages\stack_data\core.py", line 681, in included_pieces
    pos = scope_pieces.index(self.executing_piece)
                             ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Joy\anaconda3\envs\codey\Lib\site-packages\stack_data\utils.py", line 144, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
                                               ^^^^^^^^^^^^^^
  File "c:\Users\Joy\anaconda3\envs\codey\Lib\site-packages\stack_data\core.py", line 660, in executing_piece
    return only(
           ^^^^^
  File "c:\Users\Joy\anaconda3\envs\codey\Lib\site-packages\executing\executing.py", line 190, in only
    raise NotOneValueFound('Expected one value, found 0')
executing.executing.NotOneValueFound: Expected one value, found 0
```

### Expected Behavior

Connet to milvus host and create my_database successfully.

### Steps To Reproduce

```markdown
1. Run Milvus with Docker Compose
2. Run pymilvus example
```

**Comment by yanliang567** [comment]
it does not reproduce to me with milvus v2.4.15
![image](https://github.com/user-attachments/assets/a67f037f-d5c0-4dfc-8ac1-2c7f1648e971)
@joyatcloudfall please check you python env

/assign @joyatcloudfall 
/unassign

**Comment by joyatcloudfall** [comment]
I am using Python 3.11.4

**Comment by yanliang567** [comment]
/assign @XuanYang-cn 
any ideas?
/unassign

**Comment by joyatcloudfall** [comment]
I rebuilt milvus and reload my vscode as admin to run py-script then it works, not sure which one fix this issue, but it works eventually.
![image](https://github.com/user-attachments/assets/aae969bf-1866-4ecd-a0d7-878a44a9667f)
