### ISSUE TITLE
The error message should be updated if search on index IVF_SQ8_HYBRID with CPU 

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#3786]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
16:22:08  2020-09-17 08:22:08,524 - milvus_benchmark.client - DEBUG - Row count: 10000000 in collection: <sift_10m_2000000_128_l2>
16:22:08  DEBUG:milvus_benchmark.client:Row count: 10000000 in collection: <sift_10m_2000000_128_l2>
16:22:08  2020-09-17 08:22:08,525 - milvus_benchmark.k8s_runner - INFO - 10000000
16:22:08  INFO:milvus_benchmark.k8s_runner:10000000
16:22:08  2020-09-17 08:22:08,528 - milvus_benchmark.k8s_runner - INFO - {'index_type': 'ivf_sq8h', 'index_param': {'nlist': 1024}}
16:22:08  INFO:milvus_benchmark.k8s_runner:{'index_type': 'ivf_sq8h', 'index_param': {'nlist': 1024}}
16:23:30  2020-09-17 08:23:28,465 - milvus_benchmark.client - INFO - Milvus preload_collection run in 79.94s
16:23:30  INFO:milvus_benchmark.client:Milvus preload_collection run in 79.94s
16:23:30  2020-09-17 08:23:28,467 - milvus_benchmark.k8s_runner - INFO - Start warm up query
16:23:30  INFO:milvus_benchmark.k8s_runner:Start warm up query
16:23:30  2020-09-17 08:23:28,769 - milvus_benchmark.runner - INFO - Start query, query params: top-k: 1, nq: 1, actually length of vectors: 1
16:23:30  INFO:milvus_benchmark.runner:Start query, query params: top-k: 1, nq: 1, actually length of vectors: 1
16:23:30  2020-09-17 08:23:28,770 - milvus_benchmark.runner - INFO - Start run query, run 1 of 2
16:23:30  INFO:milvus_benchmark.runner:Start run query, run 1 of 2
16:23:45  Error: <BaseException: (code=1, message=Invalid field name: float_vector)>
16:23:45  ERROR:milvus.client.grpc_handler:Error: <BaseException: (code=1, message=Invalid field name: float_vector)>
16:23:45  2020-09-17 08:23:44,865 - milvus_benchmark - ERROR - <BaseException: (code=1, message=Invalid field name: float_vector)>
16:23:45  ERROR:milvus_benchmark:<BaseException: (code=1, message=Invalid field name: float_vector)>
16:23:45  2020-09-17 08:23:44,868 - milvus_benchmark - ERROR - Traceback (most recent call last):
16:23:45    File "main.py", line 80, in queue_worker
16:23:45      runner.run(run_type, collection)
16:23:45    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/k8s_runner.py", line 363, in run
16:23:45      res = self.do_query(milvus_instance, collection_name, vec_field_name, [1], [1], 2, search_param=search_params[0], filter_query=filter_query)
16:23:45    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/runner.py", line 264, in do_query
16:23:45      query_res = milvus.query(vector_query, filter_query=filter_query)
16:23:45    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/client.py", line 44, in wrapper
16:23:45      result = func(*args, **kwargs)
16:23:45    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/client.py", line 278, in query
16:23:45      result = self._milvus.search(tmp_collection_name, query)
16:23:45    File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 35, in inner
16:23:45      return func(self, *args, **kwargs)
16:23:45    File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 614, in search
16:23:45      return handler.search(collection_name, query_entities, partition_tags, fields, timeout=timeout, **kwargs)
16:23:45    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 50, in handler
16:23:45      raise e
16:23:45    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 42, in handler
16:23:45      return func(self, *args, **kwargs)
16:23:45    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 559, in search
16:23:45      raise BaseException(response.status.error_code, response.status.reason)
16:23:45  milvus.client.exceptions.BaseException: <BaseException: (code=1, message=Invalid field name: float_vector)>
16:23:45  
16:23:45  ERROR:milvus_benchmark:Traceback (most recent call last):
16:23:45    File "main.py", line 80, in queue_worker
16:23:45      runner.run(run_type, collection)
16:23:45    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/k8s_runner.py", line 363, in run
16:23:45      res = self.do_query(milvus_instance, collection_name, vec_field_name, [1], [1], 2, search_param=search_params[0], filter_query=filter_query)
16:23:45    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/runner.py", line 264, in do_query
16:23:45      query_res = milvus.query(vector_query, filter_query=filter_query)
16:23:45    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/client.py", line 44, in wrapper
16:23:45      result = func(*args, **kwargs)
16:23:45    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/client.py", line 278, in query
16:23:45      result = self._milvus.search(tmp_collection_name, query)
16:23:45    File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 35, in inner
16:23:45      return func(self, *args, **kwargs)
16:23:45    File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 614, in search
16:23:45      return handler.search(collection_name, query_entities, partition_tags, fields, timeout=timeout, **kwargs)
16:23:45    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 50, in handler
16:23:45      raise e
16:23:45    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 42, in handler
16:23:45      return func(self, *args, **kwargs)
16:23:45    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 559, in search
16:23:45      raise BaseException(response.status.error_code, response.status.reason)
16:23:45  milvus.client.exceptions.BaseException: <BaseException: (code=1, message=Invalid field name: float_vector)>
16:23:45  
16:24:53  2020-09-17 08:24:44,947 - milvus_benchmark.k8s_runner - DEBUG - Start clean up: milvus-benchmark-test-m7djenta
16:24:53  DEBUG:milvus_benchmark.k8s_runner:Start clean up: milvus-benchmark-test-m7djenta
16:24:53  2020-09-17 08:24:44,948 - milvus_benchmark.utils - DEBUG - helm uninstall -n milvus milvus-benchmark-test-m7djenta
```
**Steps/Code to reproduce behavior**

**Expected behavior**

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by del-zhenwu** [comment]
@shanghaikid if `gpu.enabled` was set false, the behavior of searching with index: ivf_sq8 should be defined.

**Comment by shanghaikid** [comment]
According to the documentation: https://milvus.io/cn/docs/v0.10.2/milvus_distributions-gpu.md#floating
On GPU version milvus, it supports indexing ivf_sq8 on CPU. 
So it's ok to choose Option(1).  @scsven @shengjun1985

**Comment by scsven** [comment]
> @shanghaikid
> The behavior of creating and searching with index: ivf_sq8 should be defined in the following cases.
> (1) GPU version, `gpu.enabled` was set false
> (2) CPU version
> 
> Option(1): directly run on CPU
> Option(2): throw an error

Do you mean ivf_sq8h ?

**Comment by shengjun1985** [comment]
Yes, it should be ivf_sq8h.

**Comment by shanghaikid** [comment]
yes, I chose option 1. @shengjun1985
