### ISSUE TITLE
[Bug]: [privilege_group] The object name is * rather than the collection names returned by "list_grants()" when grant the role with the built-in privilege group to collection level

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#37903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20241120-c73ca14a-amd64
- Deployment mode(standalone or cluster):both
- MQ type(rocksmq, pulsar or kafka):    all
- SDK version(e.g. pymilvus v2.0.0rc2): 2.5.0rc126
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The object name is * rather than the collection names returned by "list_grants()" when grant the role with the built-in privilege group to collection level

```
role.grant(object="Global", object_name="binbin", privilege="CollectionReadOnly")

>>> role.list_grants()
GrantInfo groups:
- GrantItem: <object:Global>, <object_name:*>, <db_name:default>, <role_name:binbin_new>, <grantor_name:root>, <privilege:CollectionReadOnly>

```

### Expected Behavior

The object name is the collection names rather than "*" returned by "list_grants()" when grant the role with the built-in privilege group to collection level

### Steps To Reproduce

```python
from pymilvus import Role
from pymilvus import connections
connections.connect()
role = Role("newRole")
role.create()
role.grant(object="Global", object_name="binbin", privilege="CollectionReadOnly")
role.list_grants()
```

**Comment by shaoting-huang** [comment]
fix:
```
role.grant_v2("CollectionReadOnly", "db", "binbin")
role.list_grants("db")
```
GrantInfo groups:
- GrantItem: <object:Global>, <object_name:binbin>, <db_name:db>, <role_name:binbin_new>, <grantor_name:root>, <privilege:CollectionReadOnly>

**Comment by binbinlv** [comment]
Now V1 interface "grant" could not operate privilege group, and only use grant_v2 to operate privilege group.

```
>>> role.grant(object="Global", object_name="binbin_new", privilege="CollectionReadOnly")
RPC error: [grant_privilege], <MilvusException: (code=65535, message=can not operate the built-in privilege group [CollectionReadOnly])>, <Time:{'RPC start': '2024-11-26 17:50:13.047538', 'RPC error': '2024-11-26 17:50:13.071613'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/orm/role.py", line 156, in grant
    return self._get_connection().grant_privilege(
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 141, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 137, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 176, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 116, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 86, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 1851, in grant_privilege
    check_status(resp)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/utils.py", line 63, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=can not operate the built-in privilege group [CollectionReadOnly])>
```

**Comment by binbinlv** [comment]
Close it first, and will reopen it if there are any errors on the master image when the fix pr is merged.
