### ISSUE TITLE
[Bug]: [privilege_group] The "PrivilegeCompaction" is forbidden when login with the user added in the role granted with the privilege "Compaction" 

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#38003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20241125-0b9edb62-amd64
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):    all
- SDK version(e.g. pymilvus v2.0.0rc2): 2.5.0rc126
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

 The "PrivilegeRenameCollection" is forbidden when login with the user added in the role granted with the built-in privilege group "CollectionReadWrite" 

### Expected Behavior

 The "PrivilegeRenameCollection" is not forbidden when login with the user added in the role granted with the built-in privilege group "CollectionReadWrite" 

### Steps To Reproduce

```markdown
1. connect with "root" user
2. create a role
2. grant the role with "CollectionReadWrite" privilege group
3. create a user "user1"
4. add this user to the role
5. create the collection "collection_1"
6. disconnect milvus
7. connect with "user1" user
8. rename collection "collection_1"
```

Reproduced script:
```python
from pymilvus import connections
from pymilvus import CollectionSchema, FieldSchema
from pymilvus import Collection
from pymilvus import connections
from pymilvus import DataType
from pymilvus import Partition
from pymilvus import utility
from pymilvus import MilvusClient
from pymilvus import Role

connections.connect(host="***", user="root", password="Milvus")
client = MilvusClient(uri="http://***:19530", user="root", password="Milvus")
client.create_collection("binbin_new", dimension=128)
role = Role("binbin")
role.create()
utility.list_roles(True)
utility.create_user(user="user1", password="Milvus")
role.add_user("user1")
utility.list_roles(True)
role.list_grants()
role.grant_v2(privilege="CollectionReadWrite", db_name="default", collection_name="binbin_new")
role.list_grants()

connections.disconnect('default')
connections.connect(host="", user="user1", password="Milvus")
c = Collection("binbin_new")
utility.rename_collection("binbin_new", "binbin_new_1")
```

**Comment by binbinlv** [comment]
For  the built-in privilege group "CollectionReadWrite":

1 "PrivilegeCompaction" and "PrivilegeRenameCollection" are forbidden, which should not

2.  "PrivilegeUpdateUser" is not forbidden, which should be forbidden

**Comment by binbinlv** [comment]
Using the latest dev image: shaoting-huang-rbacv2fix-99f4f88-20241126
rename collection is ok now:
```
>>> utility.rename_collection("binbin_new", "binbin_new_1")
>>>
```

but compact is still be forbidden:
```
>>> c.compact()
grpc RpcError: [compact], <_MultiThreadedRendezvous: StatusCode.PERMISSION_DENIED, PrivilegeCompaction: permission deny to user1 in the `default` database>, <Time:{'RPC start': '2024-11-26 19:08:19.705037', 'gRPC error': '2024-11-26 19:08:19.770591'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 1515, in compact
    self.compaction_id = conn.compact(
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 155, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 137, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 176, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 90, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 86, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 1600, in compact
    response = future.result()
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/grpc/_channel.py", line 881, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.PERMISSION_DENIED
	details = "PrivilegeCompaction: permission deny to user1 in the `default` database"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-11-26T19:08:19.77028+08:00", grpc_status:7, grpc_message:"PrivilegeCompaction: permission deny to user1 in the `default` database"}"
>
```

**Comment by binbinlv** [comment]
Using grant v1 interface, compact is forbidden too when the collection is granted "Compaction" privilege:
```
connections.connect(host="10.101.182.121", user="root", password="Milvus")
role.grant("Collection", "col1", "Compaction")
connections.connect(host="10.101.182.121", user="user1", password="Milvus1")
>>> c = Collection("col1")
>>> c.compact()
grpc RpcError: [compact], <_MultiThreadedRendezvous: StatusCode.PERMISSION_DENIED, PrivilegeCompaction: permission deny to user1 in the `default` database>, <Time:{'RPC start': '2024-11-26 21:20:53.161300', 'gRPC error': '2024-11-26 21:20:53.226722'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 1515, in compact
    self.compaction_id = conn.compact(
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 155, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 137, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 176, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 90, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 86, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 1600, in compact
    response = future.result()
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/grpc/_channel.py", line 881, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.PERMISSION_DENIED
	details = "PrivilegeCompaction: permission deny to user1 in the `default` database"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-11-26T21:20:53.226424+08:00", grpc_status:7, grpc_message:"PrivilegeCompaction: permission deny to user1 in the `default` database"}"
```

**Comment by binbinlv** [comment]
working on verification.

**Comment by binbinlv** [comment]
Compact could be executed for "CollectionReadWrite" and "CollectionAdmin", but it could be executed for "CollectionReadOnly" which should not?

**Comment by binbinlv** [comment]
And do upgrade tests:

1. 2.5.0-beta, "compaction" is permission denied.
2. upgrade 2.5.0-beta to  master-20241203-9e008685-amd64, the user is granted "compaction" previlige could do compact successfully.

So close this issue.
