### ISSUE TITLE
[Bug]: [privilege_group] Query/Search failed when login with the user added in the role granted with the built-in privilege group "CollectionReadOnly" 

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#38002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20241125-0b9edb62-amd64
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):    all
- SDK version(e.g. pymilvus v2.0.0rc2): 2.5.0rc126
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Query/Search failed when grant the role with the built-in privilege "CollectionReadOnly" 

```
grpc RpcError: [query], <_MultiThreadedRendezvous: StatusCode.PERMISSION_DENIED, PrivilegeQuery: permission deny to user1 in the `default` database>, <Time:{'RPC start': '2024-11-25 16:04:07.718817', 'gRPC error': '2024-11-25 16:04:07.760350'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 1076, in query
    return conn.query(
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 155, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 137, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 176, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 90, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 86, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 1539, in query
    response = future.result()
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/grpc/_channel.py", line 881, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.PERMISSION_DENIED
	details = "PrivilegeQuery: permission deny to user1 in the `default` database"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"PrivilegeQuery: permission deny to user1 in the `default` database", grpc_status:7, created_time:"2024-11-25T16:04:07.759873+08:00"}"
```

### Expected Behavior

Query/search successfully

### Steps To Reproduce

```markdown
1. connect with "root" user
2. create a role
2. grant the role with "CollectionReadOnly" privilege group
3. create a user "user1"
4. add this user to the role
5. create a collection, insert, create index, and load
6. disconnect milvus
7. connect with "user1" user
8. query

connections.disconnect("default")
connections.connect(host="10.101.142.165", user="root", password="Milvus")

utility.list_users(True)
role.name
role.list_grants()
connections.disconnect("default")
connections.connect(host="10.101.142.165", user="user1", password="Milvus")
c = Collection("binbin")
c.query("id==0")
```

**Comment by binbinlv** [comment]
And the followings in red "N" do not work as expected:

![9f26c19d-2866-4853-b9dc-7c734e352cc1](https://github.com/user-attachments/assets/82d2d6d5-053d-4eb8-b36a-7a8d90a51119)

**Comment by binbinlv** [comment]
Verified and fixed in dev branch.
milvus: shaoting-huang-rbacv2fix-df5df8d-20241125
pymilvus: 2.5.0rc126

results:
```
>>> c.query("id==1")
data: []
>>> dim = 128
>>> nb = 1
>>> import random
>>> vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
>>> c.search(data = vectors, anns_field="vector", param={}, limit=1)
data: ['[]']
>>> utility.load_state()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: load_state() missing 1 required positional argument: 'collection_name'
>>> utility.load_state("binbin_new")
<LoadState: Loaded>
>>>
>>>
>>> utility.loading_progress()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: loading_progress() missing 1 required positional argument: 'collection_name'
>>> utility.loading_progress("binbin_new")
{'loading_progress': '100%'}
>>>
>>> c.has_partition("default")
False
>>> c.has_partition("_default")
True
>>> c.partitions
[{"name":"_default","collection_name":"binbin_new","description":""}]
>>>
>>>
>>> utility.list_collections()
[]
```
