### ISSUE TITLE
[Bug]: [privilege_group] The interface "grant_v2" does not support empty collectionName while the error says it does

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#38042]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-latest
- Deployment mode(standalone or cluster):both
- MQ type(rocksmq, pulsar or kafka):    all
- SDK version(e.g. pymilvus v2.0.0rc2): 2.5.0rc126
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The interface "grant_v2" does not support empty collectionName while the error says it does

```
role.grant_v2("DatabaseReadOnly", "default", "binbin_new_1")
(code=65535, message=collectionName should be empty or * for the database level privilege: DatabaseReadOnly
role.grant_v2("DatabaseReadOnly", "default")
TypeError: grant_v2() missing 1 required positional argument: 'collection_name'
role.grant_v2("DatabaseReadOnly", "default", "")
code=1, message=`collection_name` value  is illegal
```

### Expected Behavior

The interface "grant_v2" supports empty collectionName

### Steps To Reproduce

```python
from pymilvus import connections
from pymilvus import CollectionSchema, FieldSchema
from pymilvus import Collection
from pymilvus import connections
from pymilvus import DataType
from pymilvus import Partition
from pymilvus import utility
from pymilvus import MilvusClient
from pymilvus import Role

connections.connect(host="***", user="root", password="Milvus")
client = MilvusClient(uri="http://***:19530", user="root", password="Milvus")
client.create_collection("binbin_new", dimension=128)
role = Role("binbin")
role.create()
utility.list_roles(True)
utility.create_user(user="user1", password="Milvus")
role.add_user("user1")
utility.list_roles(True)
role.list_grants()
role.grant_v2("DatabaseReadOnly", "default", "binbin_new_1")
role.grant_v2("DatabaseReadOnly", "default")
role.grant_v2("DatabaseReadOnly", "default", "")
```
```


### Milvus Log

_No response_

### Anything else?

_No response_

**Comment by binbinlv** [comment]
Currently, "the collection could be empty" is removed?

```
code=1100, message=collectionName should be * for the database level privilege: DatabaseReadOnly: invalid parameter
```

```
>>> role.grant_v2("DatabaseReadOnly", "default", "binbin_new_1")
2024-12-02 19:51:29,713 [ERROR][handler]: RPC error: [grant_privilege_v2], <MilvusException: (code=1100, message=collectionName should be * for the database level privilege: DatabaseReadOnly: invalid parameter)>, <Time:{'RPC start': '2024-12-02 19:51:29.696124', 'RPC error': '2024-12-02 19:51:29.713461'}> (decorators.py:140)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/orm/role.py", line 199, in grant_v2
    return self._get_connection().grant_privilege_v2(
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 141, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 137, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 176, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 116, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 86, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 1893, in grant_privilege_v2
    check_status(resp)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/utils.py", line 63, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1100, message=collectionName should be * for the database level privilege: DatabaseReadOnly: invalid parameter)>
```

**Comment by shaoting-huang** [comment]
the collection name can not be empty. Database param can be empty and it uses `default` db.

**Comment by binbinlv** [comment]
milvus: master-20241202-a5e0a56a
pymilvus: 2.6.0rc8

1. role.grant_v2("DatabaseReadOnly", "default", "binbin_new_1")
report error: "code=1100, message=collectionName should be * for the database level privilege: DatabaseReadOnly: invalid parameter"

2. role.grant_v2("DatabaseReadOnly", "default", "")
report error: "code=1100, message=object name should be not empty: invalid parameter[expected=not empty][actual=]"

3. role.grant_v2("DatabaseReadOnly", "default")
report error: "code=1100, message=object name should be not empty: invalid parameter[expected=not empty][actual=]"

**Comment by binbinlv** [comment]
I think the error message for scenario 2 and 3 could be optimized.

**Comment by shaoting-huang** [comment]
```
role.grant_v2("DatabaseReadOnly", "default", "")
<MilvusException: (code=1100, message=collection name should be not empty: invalid parameter[expected=not empty][actual=])>
```

**Comment by binbinlv** [comment]
Verified and fixed.
