### ISSUE TITLE
[Bug]: The privilege name is not match with the interface name for loading_progress

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#38182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-latest/
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):  all  
- SDK version(e.g. pymilvus v2.0.0rc2): all
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The interface name is not match with its privilege name for loading_progress

```
>>> utility.loading_progress("binbin_new")
2024-12-03 17:03:54,423 [ERROR][handler]: grpc RpcError: [get_loading_progress], <_MultiThreadedRendezvous: StatusCode.PERMISSION_DENIED, PrivilegeGetLoadState: permission deny to user1 in the `default` database>, <Time:{'RPC start': '2024-12-03 17:03:54.402346', 'gRPC error': '2024-12-03 17:03:54.423021'}> (decorators.py:151)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/orm/utility.py", line 218, in loading_progress
    progress = _get_connection(using).get_loading_progress(
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 155, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 137, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 176, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 90, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 86, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 1307, in get_loading_progress
    response = self._stub.GetLoadingProgress.future(request, timeout=timeout).result()
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/grpc/_channel.py", line 881, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.PERMISSION_DENIED
	details = "PrivilegeGetLoadState: permission deny to user1 in the `default` database"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"PrivilegeGetLoadState: permission deny to user1 in the `default` database", grpc_status:7, created_time:"2024-12-03T17:03:54.422572+08:00"}"
>
```

### Expected Behavior

From the error message, the interface "loading_progres" belongs to "PrivilegeGetLoadState", but we have "PrivilegeGetLoadingProgress"

![e6979d90-2aaa-404e-bad4-6f0fabdf4dd1](https://github.com/user-attachments/assets/0d9ec281-bf9a-4a0b-8ddd-2d7d5ad59eb8)

### Steps To Reproduce

```python
from pymilvus import connections
from pymilvus import CollectionSchema, FieldSchema
from pymilvus import Collection
from pymilvus import connections
from pymilvus import DataType
from pymilvus import Partition
from pymilvus import utility
from pymilvus import MilvusClient
from pymilvus import Role

connections.connect(host="***", user="root", password="Milvus")
client = MilvusClient(uri="http://***:19530", user="root", password="Milvus")
client.create_collection("binbin_new", dimension=128)
role = Role("binbin")
role.create()
utility.list_roles(True)
utility.create_user(user="user1", password="Milvus")
role.add_user("user1")
utility.list_roles(True)
role.list_grants()

connections.disconnect('default')
connections.connect(host="", user="user1", password="Milvus")
utility.loading_progress("binbin_new")
```

**Comment by shaoting-huang** [comment]
Confirmed with @SimFG , the GetLoadState and GetLoadProgress request is belonged to PrivilegeGetLoadState. Reference: https://github.com/milvus-io/milvus-proto/pull/313/files

**Comment by binbinlv** [comment]
OK， close this issue.
