### ISSUE TITLE
Server unavailable during building binary index 

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#3822]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
15:06:56  DEBUG:milvus_benchmark.client:19530
15:06:56  INFO:milvus_benchmark.client:Server command: get_milvus_config, result: {"cache.cache_insert_data":"false","cache.cache_size":"8GB","cache.cpu_cache_threshold":"0.700000","cache.insert_buffer_size":"1GB","cache.preload_collection":"","cluster.enable":"false","cluster.role":"rw","engine.build_index_threshold":"4096","engine.omp_thread_num":"0","engine.search_combine_nq":"64","engine.simd_type":"auto","engine.use_blas_threshold":"1100","general.meta_uri":"sqlite://:@:/","general.timezone":"UTC+8","gpu.build_index_devices":"gpu0,","gpu.cache_size":"1GB","gpu.cache_threshold":"0.700000","gpu.enable":"false","gpu.gpu_search_threshold":"1000","gpu.search_devices":"gpu0,","logs.level":"debug","logs.log_rotate_num":"0","logs.max_log_file_size":"1GB","logs.path":"/test/milvus/db_data_011/binary_50m_4000000_512_jaccard_ivf/logs","logs.trace.enable":"true","metric.address":"192.168.1.237","metric.enable":"true","metric.port":"9091","network.bind.address":"0.0.0.0","network.bind.port":"19530","network.http.enable":"true","network.http.port":"19121","storage.auto_flush_interval":"1","storage.path":"/test/milvus/db_data_011/binary_50m_4000000_512_jaccard_ivf","system.lock.enable":"true","tracing.json_config_path":"","transcript.enable":"false","transcript.replay":"","version":"0.5","wal.buffer_size":"256MB","wal.enable":"true","wal.path":"/test/milvus/db_data_011/binary_50m_4000000_512_jaccard_ivf/wal","wal.recovery_error_ignore":"true"}
15:06:56  DEBUG:milvus_benchmark.k8s_runner:Drop index
15:06:56  INFO:milvus_benchmark.client:Drop index: binary_50m_4000000_512_jaccard
15:06:56  INFO:milvus_benchmark.client:Server command: get_system_info, result: {"memory_total":"540746051584","memory_used":"23457792"}
15:06:56  INFO:milvus_benchmark.client:Milvus create_index start
15:06:56  INFO:milvus_benchmark.client:Building index start, collection_name: binary_50m_4000000_512_jaccard, index_type: BIN_IVF_FLAT, metric_type: JACCARD
15:06:56  INFO:milvus_benchmark.client:{'nlist': 16384}
16:15:53  RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
16:15:53  	status = StatusCode.UNAVAILABLE
16:15:53  	details = "Socket closed"
16:15:53  	debug_error_string = "{"created":"@1600676150.433596157","description":"Error received from peer ipv4:10.110.207.108:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
16:15:53  >
16:15:53  	{'API start': '2020-09-21 07:06:56.384812', 'RPC start': '2020-09-21 07:06:56.384838', 'RPC error': '2020-09-21 08:15:50.435012'}
16:15:53  ERROR:milvus.client.grpc_handler:RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
16:15:53  	status = StatusCode.UNAVAILABLE
16:15:53  	details = "Socket closed"
16:15:53  	debug_error_string = "{"created":"@1600676150.433596157","description":"Error received from peer ipv4:10.110.207.108:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
16:15:53  >
16:15:53  	{'API start': '2020-09-21 07:06:56.384812', 'RPC start': '2020-09-21 07:06:56.384838', 'RPC error': '2020-09-21 08:15:50.435012'}
16:15:53  2020-09-21 08:15:50,441 - milvus_benchmark - ERROR - <_MultiThreadedRendezvous of RPC that terminated with:
16:15:53  	status = StatusCode.UNAVAILABLE
16:15:53  	details = "Socket closed"
16:15:53  	debug_error_string = "{"created":"@1600676150.433596157","description":"Error received from peer ipv4:10.110.207.108:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
16:15:53  >
16:15:53  ERROR:milvus_benchmark:<_MultiThreadedRendezvous of RPC that terminated with:
16:15:53  	status = StatusCode.UNAVAILABLE
16:15:53  	details = "Socket closed"
16:15:53  	debug_error_string = "{"created":"@1600676150.433596157","description":"Error received from peer ipv4:10.110.207.108:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
16:15:53  >
16:15:53  2020-09-21 08:15:50,453 - milvus_benchmark - ERROR - Traceback (most recent call last):
16:15:53    File "main.py", line 80, in queue_worker
16:15:53      runner.run(run_type, collection)
16:15:53    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/k8s_runner.py", line 184, in run
16:15:53      milvus_instance.create_index(index_field_name, index_type, metric_type, index_param=index_param)
16:15:53    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/client.py", line 36, in wrapper
16:15:53      result = func(*args, **kwargs)
16:15:53    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/client.py", line 239, in create_index
16:15:53      self._milvus.create_index(self._collection_name, field_name, index_params)
16:15:53    File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 35, in inner
16:15:53      return func(self, *args, **kwargs)
16:15:53    File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 452, in create_index
16:15:53      return handler.create_index(collection_name, field_name, params, timeout, **kwargs)
16:15:53    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 59, in handler
16:15:53      raise e
16:15:53    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 42, in handler
16:15:53      return func(self, *args, **kwargs)
16:15:53    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 465, in create_index
16:15:53      status = future.result()
16:15:53    File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 625, in result
16:15:53      raise self
16:15:53  grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
16:15:53  	status = StatusCode.UNAVAILABLE
16:15:53  	details = "Socket closed"
16:15:53  	debug_error_string = "{"created":"@1600676150.433596157","description":"Error received from peer ipv4:10.110.207.108:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
16:15:53  >
16:15:53  
16:15:53  ERROR:milvus_benchmark:Traceback (most recent call last):
16:15:53    File "main.py", line 80, in queue_worker
16:15:53      runner.run(run_type, collection)
16:15:53    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/k8s_runner.py", line 184, in run
16:15:53      milvus_instance.create_index(index_field_name, index_type, metric_type, index_param=index_param)
16:15:53    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/client.py", line 36, in wrapper
16:15:53      result = func(*args, **kwargs)
16:15:53    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.0/milvus_benchmark/client.py", line 239, in create_index
16:15:53      self._milvus.create_index(self._collection_name, field_name, index_params)
16:15:53    File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 35, in inner
16:15:53      return func(self, *args, **kwargs)
16:15:53    File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 452, in create_index
16:15:53      return handler.create_index(collection_name, field_name, params, timeout, **kwargs)
16:15:53    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 59, in handler
16:15:53      raise e
16:15:53    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 42, in handler
16:15:53      return func(self, *args, **kwargs)
16:15:53    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 465, in create_index
16:15:53      status = future.result()
16:15:53    File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 625, in result
16:15:53      raise self
16:15:53  grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
16:15:53  	status = StatusCode.UNAVAILABLE
16:15:53  	details = "Socket closed"
16:15:53  	debug_error_string = "{"created":"@1600676150.433596157","description":"Error received from peer ipv4:10.110.207.108:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
16:15:53  >
16:15:53  
16:17:01  DEBUG:milvus_benchmark.k8s_runner:Start clean up: milvus-benchmark-test-bdvpyyjr
16:17:01  DEBUG:milvus_benchmark.utils:helm uninstall -n milvus milvus-benchmark-test-bdvpyyjr
```
data logs path:
```
/test/milvus/db_data_011/binary_50m_4000000_512_jaccard_ivf/logs
```
**Steps/Code to reproduce behavior**
```
dataset: binary-50m-512d
segment_row_limit: 4000000
index_type: bin_ivf_flat
index_params:
  nlist: 16384
```
**Expected behavior**

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
transcript.replay: 
version: 0.5
cluster.enable: false
cluster.role: rw
storage.path: /test/milvus/db_data_011/binary_50m_4000000_512_jaccard_ivf
wal.recovery_error_ignore: true
metric.enable: true
network.bind.address: 0.0.0.0
general.timezone: UTC+8
network.bind.port: 19530
network.http.port: 19121
storage.auto_flush_interval: 1
gpu.cache_size: 1GB
engine.simd_type: auto
wal.buffer_size: 256MB
transcript.enable: false
wal.path: /test/milvus/db_data_011/binary_50m_4000000_512_jaccard_ivf/wal
logs.log_rotate_num: 0
cache.cache_size: 8GB
cache.insert_buffer_size: 1GB
wal.enable: true
logs.path: /test/milvus/db_data_011/binary_50m_4000000_512_jaccard_ivf/logs
cache.cache_insert_data: false
general.meta_uri: sqlite://:@:/
cache.preload_collection: 
gpu.enable: false
cache.cpu_cache_threshold: 0.700000
gpu.gpu_search_threshold: 1000
gpu.search_devices: gpu0,
gpu.build_index_devices: gpu0,
tracing.json_config_path: 
logs.level: debug
logs.trace.enable: true
engine.omp_thread_num: 0
logs.max_log_file_size: 1GB
metric.address: 192.168.1.237
metric.port: 9091
network.http.enable: true
engine.build_index_threshold: 4096
engine.search_combine_nq: 64
gpu.cache_threshold: 0.700000
engine.use_blas_threshold: 1100
system.lock.enable: true
```

**Screenshots**

**Additional context**

**Comment by cqy123456** [comment]
[2020-09-21 15:06:56,378][DEBUG][SERVER][PrintTimeRecord][reqsched_thread] CreateIndexReq(collection=binary_50m_4000000_512_jaccard): check validation (0.000082 second [0.081670 ms])
[2020-09-21 15:06:56,378][DEBUG][ENGINE][CreateIndex][reqsched_thread] Create index for collection: binary_50m_4000000_512_jaccard field: binary_vector
[2020-09-21 15:06:56,378][DEBUG][ENGINE][Flush][reqsched_thread] Begin flush all collections

There is no more output in the debug log.

**Comment by del-zhenwu** [comment]
The second run:
```
[2020-09-22 20:23:03,239][DEBUG][SERVER][PrintTimeRecord][milvus_server] ExecutionEngineImpl::BuildIndex: build vector index for field: binary_vector (9621.182966 seconds [9621182.965740 ms])
[2020-09-22 20:23:04,940][DEBUG][SERVER][PrintTimeRecord][milvus_server] ExecutionEngineImpl::BuildIndex: serialize vector index for field: binary_vector (1.701295 seconds [1701.294841 ms])
[2020-09-22 20:23:04,985][DEBUG][SERVER][PrintTimeRecord][milvus_server] ExecutionEngineImpl::BuildIndex: totally cost (9622.929103 seconds [9622929.102612 ms])
[2020-09-22 23:02:54,090][DEBUG][SERVER][PrintTimeRecord][milvus_server] ExecutionEngineImpl::BuildIndex: build vector index for field: binary_vector (9587.022280 seconds [9587022.279993 ms])
[2020-09-22 23:02:55,559][DEBUG][SERVER][PrintTimeRecord][milvus_server] ExecutionEngineImpl::BuildIndex: serialize vector index for field: binary_vector (1.469737 seconds [1469.737085 ms])
[2020-09-22 23:02:55,603][DEBUG][SERVER][PrintTimeRecord][milvus_server] ExecutionEngineImpl::BuildIndex: totally cost (9588.535471 seconds [9588535.470631 ms])
[2020-09-23 01:39:17,424][DEBUG][SERVER][PrintTimeRecord][milvus_server] ExecutionEngineImpl::BuildIndex: build vector index for field: binary_vector (9379.342913 seconds [9379342.912932 ms])
[2020-09-23 01:39:18,929][DEBUG][SERVER][PrintTimeRecord][milvus_server] ExecutionEngineImpl::BuildIndex: serialize vector index for field: binary_vector (1.504752 seconds [1504.752347 ms])
[2020-09-23 01:39:19,294][DEBUG][SERVER][PrintTimeRecord][milvus_server] ExecutionEngineImpl::BuildIndex: totally cost (9381.213006 seconds [9381213.006498 ms])
[2020-09-23 04:26:54,163][DEBUG][SERVER][PrintTimeRecord][milvus_server] ExecutionEngineImpl::BuildIndex: build vector index for field: binary_vector (10052.939429 seconds [10052939.428860 ms])
[2020-09-23 04:26:55,620][DEBUG][SERVER][PrintTimeRecord][milvus_server] ExecutionEngineImpl::BuildIndex: serialize vector index for field: binary_vector (1.457705 seconds [1457.704611 ms])
[2020-09-23 04:26:55,673][DEBUG][SERVER][PrintTimeRecord][milvus_server] ExecutionEngineImpl::BuildIndex: totally cost (10054.449411 seconds [10054449.410707 ms])
[2020-09-23 07:10:40,436][DEBUG][SERVER][PrintTimeRecord][milvus_server] ExecutionEngineImpl::BuildIndex: build vector index for field: binary_vector (9822.851641 seconds [9822851.640506 ms])
[2020-09-23 07:10:41,985][DEBUG][SERVER][PrintTimeRecord][milvus_server] ExecutionEngineImpl::BuildIndex: serialize vector index for field: binary_vector (1.548974 seconds [1548.973825 ms])
[2020-09-23 07:10:42,030][DEBUG][SERVER][PrintTimeRecord][milvus_server] ExecutionEngineImpl::BuildIndex: totally cost (9824.445479 seconds [9824445.478955 ms])
[2020-09-23 09:54:54,100][DEBUG][SERVER][PrintTimeRecord][milvus_server] ExecutionEngineImpl::BuildIndex: build vector index for field: binary_vector (9849.725680 seconds [9849725.679906 ms])
[2020-09-23 09:54:55,555][DEBUG][SERVER][PrintTimeRecord][milvus_server] ExecutionEngineImpl::BuildIndex: serialize vector index for field: binary_vector (1.455455 seconds [1455.455222 ms])
[2020-09-23 09:54:55,607][DEBUG][SERVER][PrintTimeRecord][milvus_server] ExecutionEngineImpl::BuildIndex: totally cost (9851.232789 seconds [9851232.789395 ms])

```

**Comment by XuanYang-cn** [comment]
1. stuck in flush need to be reproduced.

2. It's slow in Jaccard distance calculation. In every iteration running `knn_jaccard_blas` will cost about 6 seconds
https://github.com/milvus-io/milvus/blob/b03362bbbdaa5cca6133e254b1002222fcdbe028/core/src/index/thirdparty/faiss/utils/distances.cpp#L507

**Comment by shengjun1985** [comment]
(1) There should be no difference between the 0.10.x and 0.11.0
(2) IVF_BIN_FLAT is rarely used. So it is recommended not to pay too much attention to its performance now.

**Comment by cqy123456** [comment]
It was built fast in v0.7.0 because nlist = 2048!
