### ISSUE TITLE
[Bug]: RPC error: [__internal_register], <MilvusException: (code=1, message=Incorrect port or sdk is incompatible with server, please check your port or downgrade your sdk or upgrade your server)>

### ISSUE THREAD

**Issue by meseguera** [milvus-io/milvus#38255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

root@vpshost:~/milvus_compose# python3 ./hello_milvus.py

=== start connecting to Milvus     ===

RPC error: [__internal_register], <MilvusException: (code=1, message=Incorrect port or sdk is incompatible with server, please check your port or downgrade your sdk or upgrade your server)>, <Time:{'RPC start': '2024-12-05 18:10:05.874863', 'RPC error': '2024-12-05 18:10:05.876054'}>
Traceback (most recent call last):
  File "/root/milvus_compose/./hello_milvus.py", line 32, in <module>
    connections.connect("default", host="localhost", port="19530")
  File "/usr/local/lib/python3.10/dist-packages/pymilvus/orm/connections.py", line 451, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/usr/local/lib/python3.10/dist-packages/pymilvus/orm/connections.py", line 402, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/usr/local/lib/python3.10/dist-packages/pymilvus/client/grpc_handler.py", line 157, in _wait_for_channel_ready
    raise e from e
  File "/usr/local/lib/python3.10/dist-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    self._setup_identifier_interceptor(self._user, timeout=timeout)
  File "/usr/local/lib/python3.10/dist-packages/pymilvus/client/grpc_handler.py", line 268, in _setup_identifier_interceptor
    self._identifier = self.__internal_register(user, host, timeout=timeout)
  File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 141, in handler
    raise e from e
  File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 137, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 176, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 116, in handler
    raise e from e
  File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 86, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 213, in handler
    raise MilvusException(message=msg) from e
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Incorrect port or sdk is incompatible with server, please check your port or downgrade your sdk or upgrade your server)>

**Comment by meseguera** [comment]
- Milvus version: Milvus cli version: 0.3.2
Pymilvus version: 2.2.1

- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): Ubuntu 22.04 server
- CPU/Memory: 8gb
- GPU: na
- Others:

**Comment by yanliang567** [comment]
which milvus version are you running?
/assign @meseguera 
/unassign

**Comment by XuanYang-cn** [comment]
This error msg is released last week at PyMilvus==2.4.10, @meseguera Please double check your pymilvus also

https://github.com/milvus-io/pymilvus/pull/2378
