### ISSUE TITLE
[Bug]: The role could be dropped in the database if the role is granted with no privilege in this database but with privilege in another database

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#38325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20241209-224c2c8e-amd64
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):    all
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The role could be dropped in the  database if the role is granted  no privilege in this database but with privilege in another database

```
>>> db.using_database("db1")
>>> role = Role("binbin")
>>> role.create()
>>>
>>>
>>> role.grant("Collection", "collection1", "Insert")
>>> role.list_grants()
- GrantItem: <object:Collection>, <object_name:collection1>, <db_name:db1>, <role_name:binbin>, <grantor_name:root>, <privilege:Insert>

>>> db.using_database("default")
>>> role.name
'binbin'
>>> role.list_grants()
GrantInfo groups:
>>>
>>>
>>> role.drop()
>>>
>>>
```

### Expected Behavior

The role could not be dropped in the  database if the role is granted  with privilege in any databases

### Steps To Reproduce

```python
from pymilvus import CollectionSchema, FieldSchema
from pymilvus import Collection
from pymilvus import connections
from pymilvus import DataType
from pymilvus import Partition
from pymilvus import utility
from pymilvus import MilvusClient
from pymilvus import Role
from pymilvus import db

connections.connect(host="***", user="root", password="Milvus)
utility.create_user("user1", "Milvus")
client = MilvusClient(uri="http://***:19530", user="root", password="Milvus")
client.create_collection("collection1", dimension=128)
client.create_collection("collection2", dimension=128)
db.create_database("db1")
db.using_database("db1")
role = Role("binbin")
role.create()
role.grant("Collection", "collection1", "Insert")
role.list_grants()
db.using_database("default")
role.list_grants()
role.drop()
```

### Milvus Log

https://grafana-4am.zilliz.cc/explore?orgId=1&panes=%7B%22Vco%22:%7B%22datasource%22:%22vhI6Vw67k%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcluster%3D%5C%22devops%5C%22,namespace%3D%5C%22chaos-testing%5C%22,pod%3D~%5C%22rbac-master-latest-bogwk.%2A%5C%22%7D%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22vhI6Vw67k%22%7D%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1

**Comment by binbinlv** [comment]
working on verification.

**Comment by binbinlv** [comment]
verified and fixed.

milvus:

results:
```
>>> db.create_database("db1")
>>> db.using_database("db1")
>>> role = Role("binbin")
>>> role.create()
>>> role.grant("Collection", "collection1", "Insert")
>>> role.list_grants()
GrantInfo groups:
- GrantItem: <object:Collection>, <object_name:collection1>, <db_name:db1>, <role_name:binbin>, <grantor_name:root>, <privilege:Insert>
>>> db.using_database("default")
>>> role.list_grants()
GrantInfo groups:
>>> role.drop()
2024-12-12 11:24:15,809 [ERROR][handler]: RPC error: [drop_role], <MilvusException: (code=65535, message=fail to drop the role that it has privileges. Use REVOKE API to revoke privileges)>, <Time:{'RPC start': '2024-12-12 11:24:15.741652', 'RPC error': '2024-12-12 11:24:15.809774'}> (decorators.py:140)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/milvus_rbac/lib/python3.8/site-packages/pymilvus/orm/role.py", line 67, in drop
    return self._get_connection().drop_role(self._name)
  File "/Users/binbin/milvus_rbac/lib/python3.8/site-packages/pymilvus/decorators.py", line 141, in handler
    raise e from e
  File "/Users/binbin/milvus_rbac/lib/python3.8/site-packages/pymilvus/decorators.py", line 137, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_rbac/lib/python3.8/site-packages/pymilvus/decorators.py", line 176, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/milvus_rbac/lib/python3.8/site-packages/pymilvus/decorators.py", line 116, in handler
    raise e from e
  File "/Users/binbin/milvus_rbac/lib/python3.8/site-packages/pymilvus/decorators.py", line 86, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_rbac/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 1825, in drop_role
    check_status(resp)
  File "/Users/binbin/milvus_rbac/lib/python3.8/site-packages/pymilvus/client/utils.py", line 63, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=fail to drop the role that it has privileges. Use REVOKE API to revoke privileges)>
>>> db.using_database("db1")
>>> role = Role("binbin")
>>> role.list_grants()
GrantInfo groups:
- GrantItem: <object:Collection>, <object_name:collection1>, <db_name:db1>, <role_name:binbin>, <grantor_name:root>, <privilege:Insert>
>>> role.revoke_v2("Insert", "collection1", "db1")
>>> role.list_grants()
GrantInfo groups:
>>>
>>> db.using_database("default")
>>> role = Role("binbin")
>>> role.drop()
```

```
