### ISSUE TITLE
[Bug]: Search failed with error `service internal error: target version mismatch` 

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#38428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20241212-d0a8110a-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):kafka    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2024-12-12T10:27:56.942Z] [2024-12-12 10:26:26 - INFO - ci_test]: collection name: deploy_test_index_type_IVF_PQ_is_compacted_not_compacted_segment_status_all_is_string_indexed_not_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000 (test_action_first_deployment.py:84)

[2024-12-12T10:27:56.942Z] [2024-12-12 10:26:26 - DEBUG - ci_test]: (api_request)  : [Connections.connect] args: ['default', '', '', 'default', ''], kwargs: {'host': '10.255.89.191', 'port': 19530} (api_request.py:62)

[2024-12-12T10:27:56.942Z] [2024-12-12 10:26:26 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-12-12T10:27:56.942Z] [2024-12-12 10:26:26 - INFO - ci_test]: server version: d0a8110 (client_base.py:166)

[2024-12-12T10:27:56.942Z] [2024-12-12 10:26:26 - INFO - ci_test]: collection name: deploy_test_index_type_IVF_PQ_is_compacted_not_compacted_segment_status_all_is_string_indexed_not_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000, replica_number: 1, is_compacted: not_compacted,is_deleted: is_deleted, is_string_indexed: not_string_indexed,segment_status: all, index_type: IVF_PQ (test_action_first_deployment.py:92)

[2024-12-12T10:27:56.942Z] [2024-12-12 10:26:26 - INFO - ci_test]: Test case of search interface: initialize before test case (client_base.py:262)

[2024-12-12T10:27:56.942Z] [2024-12-12 10:26:26 - DEBUG - ci_test]: (api_request)  : [Connections.has_connection] args: ['default'], kwargs: {} (api_request.py:62)

[2024-12-12T10:27:56.942Z] [2024-12-12 10:26:26 - DEBUG - ci_test]: (api_response) : True  (api_request.py:37)

[2024-12-12T10:27:56.942Z] [2024-12-12 10:26:26 - DEBUG - ci_test]: (api_request)  : [FieldSchema] args: ['int64', <DataType.INT64: 5>, ''], kwargs: {'is_primary': False, 'is_partition_key': False, 'nullable': False} (api_request.py:62)

[2024-12-12T10:27:56.942Z] [2024-12-12 10:26:26 - DEBUG - ci_test]: (api_response) : {'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>}  (api_request.py:37)

[2024-12-12T10:27:56.942Z] [2024-12-12 10:26:26 - DEBUG - ci_test]: (api_request)  : [FieldSchema] args: ['varchar', <DataType.VARCHAR: 21>, ''], kwargs: {'max_length': 65535, 'is_primary': False, 'is_partition_key': False, 'nullable': False} (api_request.py:62)

[2024-12-12T10:27:56.942Z] [2024-12-12 10:26:26 - DEBUG - ci_test]: (api_response) : {'name': 'varchar', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 65535}}  (api_request.py:37)

[2024-12-12T10:27:56.942Z] [2024-12-12 10:26:26 - DEBUG - ci_test]: (api_request)  : [FieldSchema] args: ['float_vector', <DataType.FLOAT_VECTOR: 101>, ''], kwargs: {'dim': 128, 'is_primary': False, 'nullable': False} (api_request.py:62)

[2024-12-12T10:27:56.942Z] [2024-12-12 10:26:26 - DEBUG - ci_test]: (api_response) : {'name': 'float_vector', 'description': '', 'type': <DataType.FLOAT_VECTOR: 101>, 'params': {'dim': 128}}  (api_request.py:37)

[2024-12-12T10:27:56.942Z] [2024-12-12 10:26:26 - DEBUG - ci_test]: (api_request)  : [FieldSchema] args: ['float', <DataType.FLOAT: 10>, ''], kwargs: {'is_primary': False, 'nullable': False} (api_request.py:62)

[2024-12-12T10:27:56.942Z] [2024-12-12 10:26:26 - DEBUG - ci_test]: (api_response) : {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}  (api_request.py:37)

[2024-12-12T10:27:56.942Z] [2024-12-12 10:26:26 - DEBUG - ci_test]: (api_request)  : [FieldSchema] args: ['json_field', <DataType.JSON: 23>, ''], kwargs: {'is_primary': False, 'nullable': False} (api_request.py:62)

[2024-12-12T10:27:56.942Z] [2024-12-12 10:26:26 - DEBUG - ci_test]: (api_response) : {'name': 'json_field', 'description': '', 'type': <DataType.JSON: 23>}  (api_request.py:37)

[2024-12-12T10:27:56.942Z] [2024-12-12 10:26:26 - DEBUG - ci_test]: (api_request)  : [CollectionSchema] args: [[{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}, {'name': 'varchar', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 65535}}, {'name': 'float_vector', 'description': '', 'type': <DataT......, kwargs: {'primary_field': 'int64', 'auto_id': False, 'enable_dynamic_field': False} (api_request.py:62)

[2024-12-12T10:27:56.942Z] [2024-12-12 10:26:26 - DEBUG - ci_test]: (api_response) : {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}, {'name': 'varchar', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params......  (api_request.py:37)

[2024-12-12T10:27:56.942Z] [2024-12-12 10:26:26 - INFO - ci_test]: init_collection_general: collection creation (client_base.py:306)

[2024-12-12T10:27:56.942Z] [2024-12-12 10:26:26 - DEBUG - ci_test]: (api_request)  : [Connections.has_connection] args: ['default'], kwargs: {} (api_request.py:62)

[2024-12-12T10:27:56.942Z] [2024-12-12 10:26:26 - DEBUG - ci_test]: (api_response) : True  (api_request.py:37)

[2024-12-12T10:27:56.942Z] [2024-12-12 10:26:26 - DEBUG - ci_test]: (api_request)  : [Collection] args: ['deploy_test_index_type_IVF_PQ_is_compacted_not_compacted_segment_status_all_is_string_indexed_not_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000', {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': ......, kwargs: {'consistency_level': 'Strong'} (api_request.py:62)

[2024-12-12T10:27:56.942Z] [2024-12-12 10:26:26 - DEBUG - ci_test]: (api_response) : <Collection>:

[2024-12-12T10:27:56.942Z] -------------

[2024-12-12T10:27:56.942Z] <name>: deploy_test_index_type_IVF_PQ_is_compacted_not_compacted_segment_status_all_is_string_indexed_not_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000

[2024-12-12T10:27:56.942Z] <description>: 

[2024-12-12T10:27:56.942Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'des......  (api_request.py:37)

[2024-12-12T10:27:56.942Z] [2024-12-12 10:26:26 - INFO - ci_test]: inserting 3000 data into collection deploy_test_index_type_IVF_PQ_is_compacted_not_compacted_segment_status_all_is_string_indexed_not_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000 (common_func.py:2821)

[2024-12-12T10:27:56.942Z] [2024-12-12 10:26:26 - DEBUG - ci_test]: Dynamic field is enabled: False (common_func.py:2826)

[2024-12-12T10:27:56.943Z] [2024-12-12 10:26:26 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [      int64   float varchar                                       float_vector

[2024-12-12T10:27:56.943Z] 0         0     0.0       0  [0.05981789710432397, 0.12361657794809894, 0.1...

[2024-12-12T10:27:56.943Z] 1         1     1.0       1  [0.047756618611172974, 0.040016463215113894, 0...

[2024-12-12T10:27:56.943Z] 2         2     2.0       2  [0.08756063720609121, 0.102169216......, kwargs: {'timeout': 180} (api_request.py:62)

[2024-12-12T10:27:56.943Z] [2024-12-12 10:26:27 - DEBUG - ci_test]: (api_response) : (insert count: 3000, delete count: 0, upsert count: 0, timestamp: 454557482869850113, success count: 3000, err count: 0  (api_request.py:37)

[2024-12-12T10:27:56.943Z] [2024-12-12 10:26:27 - INFO - ci_test]: inserted 3000 data into collection deploy_test_index_type_IVF_PQ_is_compacted_not_compacted_segment_status_all_is_string_indexed_not_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000 (common_func.py:2891)

[2024-12-12T10:27:56.943Z] [2024-12-12 10:26:27 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['float_vector', {'index_type': 'IVF_PQ', 'params': {'nlist': 128, 'm': 16, 'nbits': 8}, 'metric_type': 'L2'}, 1200], kwargs: {'index_name': ''} (api_request.py:62)

[2024-12-12T10:27:56.943Z] [2024-12-12 10:26:27 - DEBUG - ci_test]: (api_response) : Status(code=0, message=)  (api_request.py:37)

[2024-12-12T10:27:56.943Z] [2024-12-12 10:26:27 - DEBUG - ci_test]: (api_request)  : [Collection.release] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-12-12T10:27:56.943Z] [2024-12-12 10:26:27 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-12-12T10:27:56.943Z] [2024-12-12 10:26:27 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 120], kwargs: {} (api_request.py:62)

[2024-12-12T10:27:56.943Z] [2024-12-12 10:26:28 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-12-12T10:27:56.943Z] [2024-12-12 10:26:28 - DEBUG - ci_test]: (api_request)  : [wait_for_loading_complete] args: ['deploy_test_index_type_IVF_PQ_is_compacted_not_compacted_segment_status_all_is_string_indexed_not_string_indexed_replica_number_1_is_deleted_is_deleted_data_size_3000', None, 20, 'default'], kwargs: {} (api_request.py:62)

[2024-12-12T10:27:56.943Z] [2024-12-12 10:26:28 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-12-12T10:27:56.943Z] [2024-12-12 10:26:28 - DEBUG - ci_test]: (api_request)  : [Collection.delete] args: ['int64 in [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]', None, 180], kwargs: {} (api_request.py:62)

[2024-12-12T10:27:56.943Z] [2024-12-12 10:26:28 - DEBUG - ci_test]: (api_response) : (insert count: 0, delete count: 10, upsert count: 0, timestamp: 454557483276435465, success count: 0, err count: 0  (api_request.py:37)

[2024-12-12T10:27:56.943Z] [2024-12-12 10:26:28 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.08735470889924654, 0.126944289512811, 0.12588734133510945, 0.12918593311293058, 0.1023581167873091, 0.13100594443243985, 0.14499930205126696, 0.055924492187485256, 0.11857478597376263, 0.03724778442992587, 0.12569844239559744, 0.11167748125824499, 0.0258523851855115, 0.052830521480990454, 0.097......, kwargs: {} (api_request.py:62)

[2024-12-12T10:27:56.943Z] [2024-12-12 10:26:49 - ERROR - ci_test]: Traceback (most recent call last):

[2024-12-12T10:27:56.943Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2024-12-12T10:27:56.943Z]     res = func(*args, **_kwargs)

[2024-12-12T10:27:56.943Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2024-12-12T10:27:56.943Z]     return func(*arg, **kwargs)

[2024-12-12T10:27:56.943Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/orm/collection.py", line 799, in search

[2024-12-12T10:27:56.943Z]     resp = conn.search(

[2024-12-12T10:27:56.943Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 141, in handler

[2024-12-12T10:27:56.943Z]     raise e from e

[2024-12-12T10:27:56.943Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 137, in handler

[2024-12-12T10:27:56.943Z]     return func(*args, **kwargs)

[2024-12-12T10:27:56.943Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 176, in handler

[2024-12-12T10:27:56.943Z]     return func(self, *args, **kwargs)

[2024-12-12T10:27:56.943Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 116, in handler

[2024-12-12T10:27:56.943Z]     raise e from e

[2024-12-12T10:27:56.943Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 86, in handler

[2024-12-12T10:27:56.943Z]     return func(*args, **kwargs)

[2024-12-12T10:27:56.943Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/client/grpc_handler.py", line 836, in search

[2024-12-12T10:27:56.943Z]     return self._execute_search(request, timeout, round_decimal=round_decimal, **kwargs)

[2024-12-12T10:27:56.943Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/client/grpc_handler.py", line 777, in _execute_search

[2024-12-12T10:27:56.943Z]     raise e from e

[2024-12-12T10:27:56.943Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/client/grpc_handler.py", line 766, in _execute_search

[2024-12-12T10:27:56.943Z]     check_status(response.status)

[2024-12-12T10:27:56.943Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/client/utils.py", line 63, in check_status

[2024-12-12T10:27:56.943Z]     raise MilvusException(status.code, status.reason, status.error_code)

[2024-12-12T10:27:56.943Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=503, message=failed to search: service internal error: target version mismatch, collection: 454557213171154412, channel: by-dev-rootcoord-dml_15_454557213171154412v0,  current target version: 0, leader version: 0: channel not available[channel=by-dev-rootcoord-dml_15_454557213171154412v0])>

[2024-12-12T10:27:56.943Z]  (api_request.py:45)

[2024-12-12T10:27:56.943Z] [2024-12-12 10:26:49 - ERROR - ci_test]: (api_response) : <MilvusException: (code=503, message=failed to search: service internal error: target version mismatch, collection: 454557213171154412, channel: by-dev-rootcoord-dml_15_454557213171154412v0,  current target version: 0, leader version: 0: channel not available[channel=by-dev-rootcoord-dml_15_45455721...... (api_request.py:46)
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_kafka_cron/detail/deploy_test_kafka_cron/2969/pipeline

log:
[artifacts-kafka-cluster-reinstall-2969-server-second-deployment-logs.tar.gz](https://github.com/user-attachments/files/18120648/artifacts-kafka-cluster-reinstall-2969-server-second-deployment-logs.tar.gz)

cluster:4am
ns: chaos-testing
pod info 
```
[2024-12-12T10:32:19.953Z] + kubectl get pods -o wide

[2024-12-12T10:32:19.954Z] + grep kafka-cluster-reinstall-2969

[2024-12-12T10:32:20.209Z] kafka-cluster-reinstall-2969-0                                    2/2     Running            0                23m     10.104.25.9     4am-node30   <none>           <none>

[2024-12-12T10:32:20.209Z] kafka-cluster-reinstall-2969-1                                    2/2     Running            0                23m     10.104.26.59    4am-node32   <none>           <none>

[2024-12-12T10:32:20.209Z] kafka-cluster-reinstall-2969-2                                    2/2     Running            0                23m     10.104.17.191   4am-node23   <none>           <none>

[2024-12-12T10:32:20.209Z] kafka-cluster-reinstall-2969-etcd-0                               1/1     Running            0                23m     10.104.17.187   4am-node23   <none>           <none>

[2024-12-12T10:32:20.209Z] kafka-cluster-reinstall-2969-etcd-1                               1/1     Running            0                23m     10.104.16.28    4am-node21   <none>           <none>

[2024-12-12T10:32:20.209Z] kafka-cluster-reinstall-2969-etcd-2                               1/1     Running            0                23m     10.104.26.61    4am-node32   <none>           <none>

[2024-12-12T10:32:20.209Z] kafka-cluster-reinstall-2969-exporter-9d6fb94c6-sk6jc             1/1     Running            3 (23m ago)      23m     10.104.16.23    4am-node21   <none>           <none>

[2024-12-12T10:32:20.209Z] kafka-cluster-reinstall-2969-milvus-datanode-cb84d78cf-lb94g      1/1     Running            1                23m     10.104.19.119   4am-node28   <none>           <none>

[2024-12-12T10:32:20.209Z] kafka-cluster-reinstall-2969-milvus-datanode-cb84d78cf-r8qdj      1/1     Running            1 (23m ago)      23m     10.104.26.55    4am-node32   <none>           <none>

[2024-12-12T10:32:20.209Z] kafka-cluster-reinstall-2969-milvus-indexnode-5964b59d68-4dlxs    1/1     Running            0                23m     10.104.34.27    4am-node37   <none>           <none>

[2024-12-12T10:32:20.209Z] kafka-cluster-reinstall-2969-milvus-indexnode-5964b59d68-mvbzs    1/1     Running            1 (23m ago)      23m     10.104.27.68    4am-node31   <none>           <none>

[2024-12-12T10:32:20.209Z] kafka-cluster-reinstall-2969-milvus-indexnode-5964b59d68-zfg2c    1/1     Running            1 (23m ago)      23m     10.104.23.181   4am-node27   <none>           <none>

[2024-12-12T10:32:20.209Z] kafka-cluster-reinstall-2969-milvus-mixcoord-6f95d85dfb-29sjg     1/1     Running            1 (23m ago)      23m     10.104.16.22    4am-node21   <none>           <none>

[2024-12-12T10:32:20.209Z] kafka-cluster-reinstall-2969-milvus-proxy-685fddb76d-2swkh        1/1     Running            1 (23m ago)      23m     10.104.27.67    4am-node31   <none>           <none>

[2024-12-12T10:32:20.209Z] kafka-cluster-reinstall-2969-milvus-querynode-74745bd976-x6wgp    1/1     Running            1 (23m ago)      23m     10.104.16.21    4am-node21   <none>           <none>

[2024-12-12T10:32:20.209Z] kafka-cluster-reinstall-2969-milvus-querynode-74745bd976-zlnm7    1/1     Running            3 (5m50s ago)    23m     10.104.34.29    4am-node37   <none>           <none>

[2024-12-12T10:32:20.209Z] kafka-cluster-reinstall-2969-milvus-querynode-74745bd976-zwdzl    1/1     Running            3 (11m ago)      23m     10.104.19.120   4am-node28   <none>           <none>

[2024-12-12T10:32:20.209Z] kafka-cluster-reinstall-2969-minio-0                              1/1     Running            0                23m     10.104.16.29    4am-node21   <none>           <none>

[2024-12-12T10:32:20.209Z] kafka-cluster-reinstall-2969-minio-1                              1/1     Running            0                23m     10.104.17.188   4am-node23   <none>           <none>

[2024-12-12T10:32:20.209Z] kafka-cluster-reinstall-2969-minio-2                              1/1     Running            0                23m     10.104.26.62    4am-node32   <none>           <none>

[2024-12-12T10:32:20.209Z] kafka-cluster-reinstall-2969-minio-3                              1/1     Running            0                23m     10.104.23.183   4am-node27   <none>           <none>

[2024-12-12T10:32:20.209Z] kafka-cluster-reinstall-2969-zookeeper-0                          1/1     Running            0                23m     10.104.16.27    4am-node21   <none>           <none>

[2024-12-12T10:32:20.209Z] kafka-cluster-reinstall-2969-zookeeper-1                          1/1     Running            0                23m     10.104.27.70    4am-node31   <none>           <none>

[2024-12-12T10:32:20.209Z] kafka-cluster-reinstall-2969-zookeeper-2                          1/1     Running            0                23m     10.104.17.189   4am-node23   <none>           <none>
```

**Comment by weiliu1031** [comment]
please verify this with latest image

**Comment by zhuwenxing** [comment]
Not reproduced in the past two weeks.
verified at image tag `master-20250113-a00ba861-amd64`
