### ISSUE TITLE
[Bug]: After the pulsar pod failure is resolved, pulsar bookie still cannot recover

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#38426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20241211-e4a9a473-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):pulsarv3    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
  Normal   Scheduled  48m                   default-scheduler  Successfully assigned chaos-testing/pulsar-pod-failure-19791-pulsarv3-bookie-0 to 4am-node24
  Normal   Pulled     48m                   kubelet            Container image "apachepulsar/pulsar:3.0.7" already present on machine
  Normal   Created    48m                   kubelet            Created container pulsar-bookkeeper-verify-clusterid
  Normal   Started    48m                   kubelet            Started container pulsar-bookkeeper-verify-clusterid
  Normal   Pulled     48m                   kubelet            Container image "apachepulsar/pulsar:3.0.7" already present on machine
  Normal   Started    48m                   kubelet            Started container pulsar-pod-failure-19791-pulsarv3-bookie
  Normal   Killing    33m                   kubelet            Container pulsar-pod-failure-19791-pulsarv3-bookie definition changed, will be restarted
  Normal   Pulled     32m (x4 over 33m)     kubelet            Container image "gcr.io/google-containers/pause:latest" already present on machine
  Normal   Created    32m (x5 over 48m)     kubelet            Created container pulsar-pod-failure-19791-pulsarv3-bookie
  Warning  Failed     32m (x4 over 33m)     kubelet            Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "sh": executable file not found in $PATH: unknown
  Warning  BackOff    28m (x28 over 33m)    kubelet            Back-off restarting failed container
  Warning  Unhealthy  3m20s (x62 over 25m)  kubelet            Readiness probe failed: HTTP probe failed with statuscode: 503
```

```
[2024-12-11T09:09:26.841Z] + kubectl get pods -o wide

[2024-12-11T09:09:26.843Z] + grep pulsar-pod-failure-19791

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-etcd-0                                 1/1     Running            0                32m     10.104.33.252   4am-node36   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-etcd-1                                 1/1     Running            0                32m     10.104.19.246   4am-node28   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-etcd-2                                 1/1     Running            0                32m     10.104.18.178   4am-node25   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-milvus-datanode-6c77c77596-2k7ch       0/1     CrashLoopBackOff   4 (9s ago)       32m     10.104.13.210   4am-node16   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-milvus-datanode-6c77c77596-5qzlj       1/1     Running            2 (32m ago)      32m     10.104.26.234   4am-node32   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-milvus-indexnode-79d7c586ff-6mwnf      1/1     Running            2 (32m ago)      32m     10.104.13.211   4am-node16   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-milvus-indexnode-79d7c586ff-fhg8l      1/1     Running            2 (32m ago)      32m     10.104.9.63     4am-node14   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-milvus-indexnode-79d7c586ff-pdjf5      1/1     Running            2 (32m ago)      32m     10.104.16.40    4am-node21   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-milvus-mixcoord-856b7974b9-8n5nq       1/1     Running            2 (32m ago)      32m     10.104.26.232   4am-node32   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-milvus-proxy-676ff86bfc-fqxg8          1/1     Running            2 (32m ago)      32m     10.104.13.209   4am-node16   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-milvus-querynode-8869d966f-7x7xb       1/1     Running            2 (32m ago)      32m     10.104.27.28    4am-node31   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-milvus-querynode-8869d966f-l2wqs       1/1     Running            2 (32m ago)      32m     10.104.30.13    4am-node38   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-milvus-querynode-8869d966f-mr8jw       1/1     Running            1 (32m ago)      32m     10.104.6.162    4am-node13   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-minio-0                                1/1     Running            0                32m     10.104.23.254   4am-node27   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-minio-1                                1/1     Running            0                32m     10.104.34.181   4am-node37   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-minio-2                                1/1     Running            0                32m     10.104.33.253   4am-node36   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-minio-3                                1/1     Running            0                32m     10.104.19.251   4am-node28   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-pulsarv3-bookie-0                      0/1     Running            8 (10m ago)      32m     10.104.21.6     4am-node24   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-pulsarv3-bookie-1                      0/1     Running            8 (10m ago)      32m     10.104.23.4     4am-node27   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-pulsarv3-bookie-2                      0/1     Running            8 (11m ago)      32m     10.104.19.254   4am-node28   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-pulsarv3-bookie-init-hjdhc             0/1     Completed          0                32m     10.104.33.244   4am-node36   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-pulsarv3-broker-0                      1/1     Running            8 (10m ago)      32m     10.104.33.246   4am-node36   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-pulsarv3-broker-1                      1/1     Running            7 (12m ago)      32m     10.104.9.64     4am-node14   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-pulsarv3-proxy-0                       1/1     Running            8 (10m ago)      32m     10.104.34.177   4am-node37   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-pulsarv3-proxy-1                       1/1     Running            8 (10m ago)      32m     10.104.23.251   4am-node27   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-pulsarv3-pulsar-init-tgrmb             0/1     Completed          0                32m     10.104.33.243   4am-node36   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-pulsarv3-recovery-0                    1/1     Running            8 (10m ago)      32m     10.104.33.245   4am-node36   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-pulsarv3-zookeeper-0                   1/1     Running            8 (10m ago)      32m     10.104.33.251   4am-node36   <none>           <none>

[2024-12-11T09:09:27.099Z] pulsar-pod-failure-19791-pulsarv3-zookeeper-1                   1/1     Running            8 (10m ago)      32m     10.104.19.247   4am-node28   <none>           <none>

[2024-12-11T09:09:27.099Z] pulsar-pod-failure-19791-pulsarv3-zookeeper-2                   1/1     Running            8 (11m ago)      32m     10.104.34.182   4am-node37   <none>           <none>
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/19791/pipeline

log:
[artifacts-pulsar-pod-failure-19791-server-logs.tar.gz](https://github.com/user-attachments/files/18120320/artifacts-pulsar-pod-failure-19791-server-logs.tar.gz)

cluster: 4am
ns: chaos-testing

pod info
```
[2024-12-11T09:09:26.841Z] + kubectl get pods -o wide

[2024-12-11T09:09:26.843Z] + grep pulsar-pod-failure-19791

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-etcd-0                                 1/1     Running            0                32m     10.104.33.252   4am-node36   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-etcd-1                                 1/1     Running            0                32m     10.104.19.246   4am-node28   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-etcd-2                                 1/1     Running            0                32m     10.104.18.178   4am-node25   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-milvus-datanode-6c77c77596-2k7ch       0/1     CrashLoopBackOff   4 (9s ago)       32m     10.104.13.210   4am-node16   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-milvus-datanode-6c77c77596-5qzlj       1/1     Running            2 (32m ago)      32m     10.104.26.234   4am-node32   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-milvus-indexnode-79d7c586ff-6mwnf      1/1     Running            2 (32m ago)      32m     10.104.13.211   4am-node16   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-milvus-indexnode-79d7c586ff-fhg8l      1/1     Running            2 (32m ago)      32m     10.104.9.63     4am-node14   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-milvus-indexnode-79d7c586ff-pdjf5      1/1     Running            2 (32m ago)      32m     10.104.16.40    4am-node21   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-milvus-mixcoord-856b7974b9-8n5nq       1/1     Running            2 (32m ago)      32m     10.104.26.232   4am-node32   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-milvus-proxy-676ff86bfc-fqxg8          1/1     Running            2 (32m ago)      32m     10.104.13.209   4am-node16   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-milvus-querynode-8869d966f-7x7xb       1/1     Running            2 (32m ago)      32m     10.104.27.28    4am-node31   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-milvus-querynode-8869d966f-l2wqs       1/1     Running            2 (32m ago)      32m     10.104.30.13    4am-node38   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-milvus-querynode-8869d966f-mr8jw       1/1     Running            1 (32m ago)      32m     10.104.6.162    4am-node13   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-minio-0                                1/1     Running            0                32m     10.104.23.254   4am-node27   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-minio-1                                1/1     Running            0                32m     10.104.34.181   4am-node37   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-minio-2                                1/1     Running            0                32m     10.104.33.253   4am-node36   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-minio-3                                1/1     Running            0                32m     10.104.19.251   4am-node28   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-pulsarv3-bookie-0                      0/1     Running            8 (10m ago)      32m     10.104.21.6     4am-node24   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-pulsarv3-bookie-1                      0/1     Running            8 (10m ago)      32m     10.104.23.4     4am-node27   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-pulsarv3-bookie-2                      0/1     Running            8 (11m ago)      32m     10.104.19.254   4am-node28   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-pulsarv3-bookie-init-hjdhc             0/1     Completed          0                32m     10.104.33.244   4am-node36   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-pulsarv3-broker-0                      1/1     Running            8 (10m ago)      32m     10.104.33.246   4am-node36   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-pulsarv3-broker-1                      1/1     Running            7 (12m ago)      32m     10.104.9.64     4am-node14   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-pulsarv3-proxy-0                       1/1     Running            8 (10m ago)      32m     10.104.34.177   4am-node37   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-pulsarv3-proxy-1                       1/1     Running            8 (10m ago)      32m     10.104.23.251   4am-node27   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-pulsarv3-pulsar-init-tgrmb             0/1     Completed          0                32m     10.104.33.243   4am-node36   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-pulsarv3-recovery-0                    1/1     Running            8 (10m ago)      32m     10.104.33.245   4am-node36   <none>           <none>

[2024-12-11T09:09:27.098Z] pulsar-pod-failure-19791-pulsarv3-zookeeper-0                   1/1     Running            8 (10m ago)      32m     10.104.33.251   4am-node36   <none>           <none>

[2024-12-11T09:09:27.099Z] pulsar-pod-failure-19791-pulsarv3-zookeeper-1                   1/1     Running            8 (10m ago)      32m     10.104.19.247   4am-node28   <none>           <none>

[2024-12-11T09:09:27.099Z] pulsar-pod-failure-19791-pulsarv3-zookeeper-2                   1/1     Running            8 (11m ago)      32m     10.104.34.182   4am-node37   <none>           <none>
```

**Comment by xiaofan-luan** [comment]
this is a pulsar issue .

/assign @LoveEachDay

**Comment by jaime0815** [comment]
Datanode panic caused by the pulsar server being unready.
```
panic: Failed to create consumer by-dev-rootcoord-dml_9, errors = server error: ServiceNotReady: Topic creation encountered an exception by initialize topic policies service. topic_name=persistent://public/default/by-dev-rootcoord-dml_9 error_message={"errorMsg":"org.apache.bookkeeper.mledger.ManagedLedgerException: Error while recovering ledger error code: -10","reqId":3279619003618051315, "remote":"pulsar-pod-failure-19791-pulsarv3-broker-0.pulsar-pod-failure-19791-pulsarv3-broker.chaos-testing.svc.cluster.local/10.104.33.246:6650", "local":"/10.104.9.64:49442"}
```

**Comment by xiaofan-luan** [comment]
> Datanode panic caused by the pulsar server being unready.
> 
> ```
> panic: Failed to create consumer by-dev-rootcoord-dml_9, errors = server error: ServiceNotReady: Topic creation encountered an exception by initialize topic policies service. topic_name=persistent://public/default/by-dev-rootcoord-dml_9 error_message={"errorMsg":"org.apache.bookkeeper.mledger.ManagedLedgerException: Error while recovering ledger error code: -10","reqId":3279619003618051315, "remote":"pulsar-pod-failure-19791-pulsarv3-broker-0.pulsar-pod-failure-19791-pulsarv3-broker.chaos-testing.svc.cluster.local/10.104.33.246:6650", "local":"/10.104.9.64:49442"}
> ```
> 
> Datanode still failed to reconnect to Pulsar after restarting.
> 
> ```
> [2024/12/11 09:25:32.345 +00:00] [WARN] [retry/retry.go:46] ["retry func failed"] [retried=4] [error="server error: ServiceNotReady: Topic creation encountered an exception by initialize topic policies service. topic_name=persistent://public/default/by-dev-rootcoord-dml_10 error_message={\"errorMsg\":\"org.apache.bookkeeper.mledger.ManagedLedgerException: Error while recovering ledger error code: -10\",\"reqId\":3279619003618051567, \"remote\":\"pulsar-pod-failure-19791-pulsarv3-broker-0.pulsar-pod-failure-19791-pulsarv3-broker.chaos-testing.svc.cluster.local/10.104.33.246:6650\", \"local\":\"/10.104.9.64:49442\"}"]
> [2024/12/11 09:25:32.345 +00:00] [WARN] [retry/retry.go:46] ["retry func failed"] [retried=4] [error="server error: ServiceNotReady: Topic creation encountered an exception by initialize topic policies service. topic_name=persistent://public/default/by-dev-rootcoord-dml_3 error_message={\"errorMsg\":\"org.apache.bookkeeper.mledger.ManagedLedgerException: Error while recovering ledger error code: -10\",\"reqId\":3279619003618051567, \"remote\":\"pulsar-pod-failure-19791-pulsarv3-broker-0.pulsar-pod-failure-19791-pulsarv3-broker.chaos-testing.svc.cluster.local/10.104.33.246:6650\", \"local\":\"/10.104.9.64:49442\"}"]
> [2024/12/11 09:25:32.345 +00:00] [WARN] [retry/retry.go:46] ["retry func failed"] [retried=4] [error="server error: ServiceNotReady: Topic creation encountered an exception by initialize topic policies service. topic_name=persistent://public/default/by-dev-rootcoord-dml_1 error_message={\"errorMsg\":\"org.apache.bookkeeper.mledger.ManagedLedgerException: Error while recovering ledger error code: -10\",\"reqId\":3279619003618051567, \"remote\":\"pulsar-pod-failure-19791-pulsarv3-broker-0.pulsar-pod-failure-19791-pulsarv3-broker.chaos-testing.svc.cluster.local/10.104.33.246:6650\", \"local\":\"/10.104.9.64:49442\"}"]
> [2024/12/11 09:25:32.345 +00:00] [WARN] [retry/retry.go:46] ["retry func failed"] [retried=4] [error="server error: ServiceNotReady: Topic creation encountered an exception by initialize topic policies service. topic_name=persistent://public/default/by-dev-rootcoord-dml_12 error_message={\"errorMsg\":\"org.apache.bookkeeper.mledger.ManagedLedgerException: Error while recovering ledger error code: -10\",\"reqId\":3279619003618051567, \"remote\":\"pulsar-pod-failure-19791-pulsarv3-broker-0.pulsar-pod-failure-19791-pulsarv3-broker.chaos-testing.svc.cluster.local/10.104.33.246:6650\", \"local\":\"/10.104.9.64:49442\"}"]
> ```

why do we report error instead of panic?

**Comment by jaime0815** [comment]
> > Datanode panic caused by the pulsar server being unready.
> > ```
> > panic: Failed to create consumer by-dev-rootcoord-dml_9, errors = server error: ServiceNotReady: Topic creation encountered an exception by initialize topic policies service. topic_name=persistent://public/default/by-dev-rootcoord-dml_9 error_message={"errorMsg":"org.apache.bookkeeper.mledger.ManagedLedgerException: Error while recovering ledger error code: -10","reqId":3279619003618051315, "remote":"pulsar-pod-failure-19791-pulsarv3-broker-0.pulsar-pod-failure-19791-pulsarv3-broker.chaos-testing.svc.cluster.local/10.104.33.246:6650", "local":"/10.104.9.64:49442"}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Datanode still failed to reconnect to Pulsar after restarting.
> > ```
> > [2024/12/11 09:25:32.345 +00:00] [WARN] [retry/retry.go:46] ["retry func failed"] [retried=4] [error="server error: ServiceNotReady: Topic creation encountered an exception by initialize topic policies service. topic_name=persistent://public/default/by-dev-rootcoord-dml_10 error_message={\"errorMsg\":\"org.apache.bookkeeper.mledger.ManagedLedgerException: Error while recovering ledger error code: -10\",\"reqId\":3279619003618051567, \"remote\":\"pulsar-pod-failure-19791-pulsarv3-broker-0.pulsar-pod-failure-19791-pulsarv3-broker.chaos-testing.svc.cluster.local/10.104.33.246:6650\", \"local\":\"/10.104.9.64:49442\"}"]
> > [2024/12/11 09:25:32.345 +00:00] [WARN] [retry/retry.go:46] ["retry func failed"] [retried=4] [error="server error: ServiceNotReady: Topic creation encountered an exception by initialize topic policies service. topic_name=persistent://public/default/by-dev-rootcoord-dml_3 error_message={\"errorMsg\":\"org.apache.bookkeeper.mledger.ManagedLedgerException: Error while recovering ledger error code: -10\",\"reqId\":3279619003618051567, \"remote\":\"pulsar-pod-failure-19791-pulsarv3-broker-0.pulsar-pod-failure-19791-pulsarv3-broker.chaos-testing.svc.cluster.local/10.104.33.246:6650\", \"local\":\"/10.104.9.64:49442\"}"]
> > [2024/12/11 09:25:32.345 +00:00] [WARN] [retry/retry.go:46] ["retry func failed"] [retried=4] [error="server error: ServiceNotReady: Topic creation encountered an exception by initialize topic policies service. topic_name=persistent://public/default/by-dev-rootcoord-dml_1 error_message={\"errorMsg\":\"org.apache.bookkeeper.mledger.ManagedLedgerException: Error while recovering ledger error code: -10\",\"reqId\":3279619003618051567, \"remote\":\"pulsar-pod-failure-19791-pulsarv3-broker-0.pulsar-pod-failure-19791-pulsarv3-broker.chaos-testing.svc.cluster.local/10.104.33.246:6650\", \"local\":\"/10.104.9.64:49442\"}"]
> > [2024/12/11 09:25:32.345 +00:00] [WARN] [retry/retry.go:46] ["retry func failed"] [retried=4] [error="server error: ServiceNotReady: Topic creation encountered an exception by initialize topic policies service. topic_name=persistent://public/default/by-dev-rootcoord-dml_12 error_message={\"errorMsg\":\"org.apache.bookkeeper.mledger.ManagedLedgerException: Error while recovering ledger error code: -10\",\"reqId\":3279619003618051567, \"remote\":\"pulsar-pod-failure-19791-pulsarv3-broker-0.pulsar-pod-failure-19791-pulsarv3-broker.chaos-testing.svc.cluster.local/10.104.33.246:6650\", \"local\":\"/10.104.9.64:49442\"}"]
> > ```
> 
> why do we report error instead of panic?

![image](https://github.com/user-attachments/assets/0dc77cc4-e9e7-4884-885f-52fbd740b309)

Datanode exited with a panic, and the downloaded logs were incomplete.

**Comment by jaime0815** [comment]
> /assign @Linkwei @Linkwei Could you help to analyze whether pulsar cluster is recovered after pod failure?

It seems docker-compose or docker file has a bug in puslar 3

**Comment by Linkwei** [comment]
The Pulsar cluster has not been recovered.2024-12-11T09:25:26,569+0000 [BookKeeperClientScheduler-OrderedScheduler-0-0] ERROR org.apache.bookkeeper.proto.PerChannelBookieClient - Cannot connect to pulsar-pod-failure-19791-pulsarv3-bookie-0.pulsar-pod-failure-19791-pulsarv3-bookie.chaos-testing.svc.cluster.local:3181 as endpoint resolution failed (probably bookie is down) err org.apache.bookkeeper.proto.BookieAddressResolver$BookieIdNotResolvedException: Cannot resolve bookieId pulsar-pod-failure-19791-pulsarv3-bookie-0.pulsar-pod-failure-19791-pulsarv3-bookie.chaos-testing.svc.cluster.local:3181, bookie does not exist or it is not running
2024-12-11T09:25:26,569+0000 [BookKeeperClientScheduler-OrderedScheduler-0-0] ERROR org.apache.bookkeeper.proto.PerChannelBookieClient - Could not connect to bookie: null/pulsar-pod-failure-19791-pulsarv3-bookie-0.pulsar-pod-failure-19791-pulsarv3-bookie.chaos-testing.svc.cluster.local:3181, current state CONNECTING : 
org.apache.bookkeeper.proto.BookieAddressResolver$BookieIdNotResolvedException: Cannot resolve bookieId pulsar-pod-failure-19791-pulsarv3-bookie-0.pulsar-pod-failure-19791-pulsarv3-bookie.chaos-testing.svc.cluster.local:3181, bookie does not exist or it is not running
	at org.apache.bookkeeper.client.DefaultBookieAddressResolver.resolve(DefaultBookieAddressResolver.java:69) ~[org.apache.bookkeeper-bookkeeper-server-4.16.6.jar:4.16.6]
	at org.apache.bookkeeper.proto.PerChannelBookieClient.connect(PerChannelBookieClient.java:540) ~[org.apache.bookkeeper-bookkeeper-server-4.16.6.jar:4.16.6]
	at org.apache.bookkeeper.proto.PerChannelBookieClient.connectIfNeededAndDoOp(PerChannelBookieClient.java:678) ~[org.apache.bookkeeper-bookkeeper-server-4.16.6.jar:4.16.6]
	at org.apache.bookkeeper.proto.DefaultPerChannelBookieClientPool.obtain(DefaultPerChannelBookieClientPool.java:120) ~[org.apache.bookkeeper-bookkeeper-server-4.16.6.jar:4.16.6]
	at org.apache.bookkeeper.proto.DefaultPerChannelBookieClientPool.obtain(DefaultPerChannelBookieClientPool.java:115) ~[org.apache.bookkeeper-bookkeeper-server-4.16.6.jar:4.16.6]
	at org.apache.bookkeeper.proto.BookieClientImpl.readEntry(BookieClientImpl.java:487) ~[org.apache.bookkeeper-bookkeeper-server-4.16.6.jar:4.16.6]
	at org.apache.bookkeeper.proto.BookieClientImpl.readEntry(BookieClientImpl.java:473) ~[org.apache.bookkeeper-bookkeeper-server-4.16.6.jar:4.16.6]
	at org.apache.bookkeeper.proto.BookieClientImpl.readEntry(BookieClientImpl.java:467) ~[org.apache.bookkeeper-bookkeeper-server-4.16.6.jar:4.16.6]
	at org.apache.bookkeeper.client.ReadLastConfirmedOp.initiate(ReadLastConfirmedOp.java:79) ~[org.apache.bookkeeper-bookkeeper-server-4.16.6.jar:4.16.6]
	at org.apache.bookkeeper.client.LedgerHandle.asyncReadPiggybackLastConfirmed(LedgerHandle.java:1428) ~[org.apache.bookkeeper-bookkeeper-server-4.16.6.jar:4.16.6]
	at org.apache.bookkeeper.client.LedgerHandle.asyncReadLastConfirmed(LedgerHandle.java:1391) ~[org.apache.bookkeeper-bookkeeper-server-4.16.6.jar:4.16.6]
	at org.apache.bookkeeper.client.LedgerOpenOp.openWithMetadata(LedgerOpenOp.java:222) ~[org.apache.bookkeeper-bookkeeper-server-4.16.6.jar:4.16.6]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at org.apache.bookkeeper.common.util.SingleThreadSafeScheduledExecutorService$SafeRunnable.run(SingleThreadSafeScheduledExecutorService.java:46) ~[org.apache.bookkeeper-bookkeeper-common-4.16.6.jar:4.16.6]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty-netty-common-4.1.113.Final.jar:4.1.113.Final]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: org.apache.bookkeeper.client.BKException$BKBookieHandleNotAvailableException: Bookie handle is not available
	at org.apache.bookkeeper.discover.ZKRegistrationClient.getBookieServiceInfo(ZKRegistrationClient.java:249) ~[org.apache.bookkeeper-bookkeeper-server-4.16.6.jar:4.16.6]
	at org.apache.bookkeeper.client.DefaultBookieAddressResolver.resolve(DefaultBookieAddressResolver.java:47) ~[org.apache.bookkeeper-bookkeeper-server-4.16.6.jar:4.16.6]

**Comment by xiaofan-luan** [comment]
so i is due to pulsar upgrade to 3.x? 

Is there newer version fix it?

**Comment by zhuwenxing** [comment]
This issue only occurred once and hasn't been reproduced since, so it's temporarily considered an environment issue

**Comment by zhuwenxing** [comment]
not reproduced recently
