### ISSUE TITLE
[Bug]: After milvus recovers from mixcoord pod kill chaos, querynode is in a unhealthy status and collection load times out（180s）

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#38486]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20241216-8794ec96-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):pulsar    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2024-12-16T07:27:43.623Z] [2024-12-16 07:22:34 - INFO - ci_test]: ################################################################################ (conftest.py:232)

[2024-12-16T07:27:43.623Z] [2024-12-16 07:22:34 - INFO - ci_test]: [initialize_milvus] Log cleaned up, start testing... (conftest.py:233)

[2024-12-16T07:27:43.623Z] [2024-12-16 07:22:34 - INFO - ci_test]: [setup_class] Start setup class... (client_base.py:41)

[2024-12-16T07:27:43.623Z] [2024-12-16 07:22:34 - INFO - ci_test]: *********************************** setup *********************************** (client_base.py:47)

[2024-12-16T07:27:43.623Z] [2024-12-16 07:22:34 - INFO - ci_test]: pymilvus version: 2.5.1rc9 (client_base.py:48)

[2024-12-16T07:27:43.623Z] [2024-12-16 07:22:34 - INFO - ci_test]: [setup_method] Start setup test case test_milvus_default. (client_base.py:49)

[2024-12-16T07:27:43.623Z] ------------------------------ Captured log call -------------------------------

[2024-12-16T07:27:43.623Z] [2024-12-16 07:22:34 - DEBUG - ci_test]: (api_request)  : [Connections.connect] args: ['default', '', '', 'default', ''], kwargs: {'host': '10.255.38.45', 'port': 19530} (api_request.py:62)

[2024-12-16T07:27:43.623Z] [2024-12-16 07:22:34 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-12-16T07:27:43.623Z] [2024-12-16 07:22:34 - INFO - ci_test]: server version: 8794ec9 (client_base.py:166)

[2024-12-16T07:27:43.623Z] [2024-12-16 07:22:34 - DEBUG - ci_test]: (api_request)  : [Connections.has_connection] args: ['default'], kwargs: {} (api_request.py:62)

[2024-12-16T07:27:43.623Z] [2024-12-16 07:22:34 - DEBUG - ci_test]: (api_response) : True  (api_request.py:37)

[2024-12-16T07:27:43.624Z] [2024-12-16 07:22:34 - DEBUG - ci_test]: (api_request)  : [Collection] args: ['Checker__8GDm0TZr', {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}, {'name': 'varchar', 'description': '', 'type': <DataType......, kwargs: {'consistency_level': 'Strong'} (api_request.py:62)

[2024-12-16T07:27:43.624Z] [2024-12-16 07:22:34 - DEBUG - ci_test]: (api_response) : <Collection>:

[2024-12-16T07:27:43.624Z] -------------

[2024-12-16T07:27:43.624Z] <name>: Checker__8GDm0TZr

[2024-12-16T07:27:43.624Z] <description>: 

[2024-12-16T07:27:43.624Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}......  (api_request.py:37)

[2024-12-16T07:27:43.624Z] [2024-12-16 07:22:34 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-12-16T07:27:43.624Z] [2024-12-16 07:22:35 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-12-16T07:27:43.624Z] [2024-12-16 07:22:35 - DEBUG - ci_test]: (api_request)  : [Collection.compact] args: [False, 180], kwargs: {} (api_request.py:62)

[2024-12-16T07:27:43.624Z] [2024-12-16 07:22:35 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-12-16T07:27:43.624Z] [2024-12-16 07:23:04 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-12-16T07:27:43.624Z] [2024-12-16 07:23:05 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-12-16T07:27:43.624Z] [2024-12-16 07:23:05 - INFO - ci_test]: assert create collection: 0.021376848220825195, init_entities: 256500 (test_all_collections_after_chaos.py:49)

[2024-12-16T07:27:43.624Z] [2024-12-16 07:23:09 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [[{'int64': -3000, 'float': 0.03640775, 'varchar': 'msqwyupechmbutykp', 'text': 'North firm practice dream. Project experience smile where.\nHospital deep its town who there single. Team consider that mention. Wish TV business new born improve apply watch.', 'json_field': {'name': 'Alex Hogan', 'add......, kwargs: {'timeout': 180} (api_request.py:62)

[2024-12-16T07:27:43.624Z] [2024-12-16 07:23:10 - DEBUG - ci_test]: (api_response) : (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 454645196991758337, success count: 2000, err count: 0  (api_request.py:37)

[2024-12-16T07:27:43.624Z] [2024-12-16 07:23:10 - INFO - ci_test]: assert insert: 1.664029598236084 (test_all_collections_after_chaos.py:57)

[2024-12-16T07:27:43.624Z] [2024-12-16 07:23:10 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-12-16T07:27:43.624Z] [2024-12-16 07:23:26 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-12-16T07:27:43.624Z] [2024-12-16 07:23:26 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-12-16T07:27:43.624Z] [2024-12-16 07:23:45 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-12-16T07:27:43.624Z] [2024-12-16 07:23:45 - INFO - ci_test]: assert flush: 16.219479084014893, entities: 258500 (test_all_collections_after_chaos.py:67)

[2024-12-16T07:27:43.624Z] [2024-12-16 07:23:45 - INFO - ci_test]: index info: [{'collection': 'Checker__8GDm0TZr', 'field': 'float_vector', 'index_name': 'float_vector', 'index_param': {'params': {'M': 48, 'efConstruction': 500}, 'index_type': 'HNSW', 'metric_type': 'L2'}}, {'collection': 'Checker__8GDm0TZr', 'field': 'image_emb', 'index_name': 'image_emb', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}, {'collection': 'Checker__8GDm0TZr', 'field': 'voice_emb', 'index_name': 'voice_emb', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}, {'collection': 'Checker__8GDm0TZr', 'field': 'text_sparse_emb', 'index_name': 'text_sparse_emb', 'index_param': {'index_type': 'SPARSE_INVERTED_INDEX', 'metric_type': 'BM25', 'params': {'bm25_k1': 1.5, 'bm25_b': 0.75}}}, {'collection': 'Checker__8GDm0TZr', 'field': 'int64', 'index_name': 'int64', 'index_param': {'index_type': 'INVERTED'}}, {'collection': 'Checker__8GDm0TZr', 'field': 'float', 'index_name': 'float', 'index_param': {'index_type': 'INVERTED'}}, {'collection': 'Checker__8GDm0TZr', 'field': 'varchar', 'index_name': 'varchar', 'index_param': {'index_type': 'INVERTED'}}, {'collection': 'Checker__8GDm0TZr', 'field': 'text', 'index_name': 'text', 'index_param': {'index_type': 'INVERTED'}}] (test_all_collections_after_chaos.py:71)

[2024-12-16T07:27:43.624Z] [2024-12-16 07:23:45 - INFO - ci_test]: index info: [{'collection': 'Checker__8GDm0TZr', 'field': 'text', 'index_name': 'text', 'index_param': {'index_type': 'INVERTED'}}, {'collection': 'Checker__8GDm0TZr', 'field': 'float_vector', 'index_name': 'float_vector', 'index_param': {'params': {'M': 48, 'efConstruction': 500}, 'index_type': 'HNSW', 'metric_type': 'L2'}}, {'collection': 'Checker__8GDm0TZr', 'field': 'image_emb', 'index_name': 'image_emb', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}, {'collection': 'Checker__8GDm0TZr', 'field': 'voice_emb', 'index_name': 'voice_emb', 'index_param': {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 48, 'efConstruction': 500}}}, {'collection': 'Checker__8GDm0TZr', 'field': 'text_sparse_emb', 'index_name': 'text_sparse_emb', 'index_param': {'index_type': 'SPARSE_INVERTED_INDEX', 'metric_type': 'BM25', 'params': {'bm25_k1': 1.5, 'bm25_b': 0.75}}}, {'collection': 'Checker__8GDm0TZr', 'field': 'int64', 'index_name': 'int64', 'index_param': {'index_type': 'INVERTED'}}, {'collection': 'Checker__8GDm0TZr', 'field': 'float', 'index_name': 'float', 'index_param': {'index_type': 'INVERTED'}}, {'collection': 'Checker__8GDm0TZr', 'field': 'varchar', 'index_name': 'varchar', 'index_param': {'index_type': 'INVERTED'}}] (test_all_collections_after_chaos.py:86)

[2024-12-16T07:27:43.624Z] [2024-12-16 07:23:45 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 180], kwargs: {} (api_request.py:62)

[2024-12-16T07:27:43.624Z] [2024-12-16 07:23:45 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-12-16T07:27:43.624Z] [2024-12-16 07:23:45 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.14304523638543248, 0.026354657888254075, 0.12263819587515062, 0.01257761686931851, 0.010101147417344202, 0.11946248946986664, 0.1504146791325912, 0.15300368681398588, 0.06447075585305438, 0.001239720186621694, 0.1517587194368232, 0.03500244900750585, 0.009774818926895665, 0.07387772179337324, 0......, kwargs: {} (api_request.py:62)

[2024-12-16T07:27:43.624Z] [2024-12-16 07:23:45 - DEBUG - ci_test]: (api_response) : data: ["['id: 1734333290248130, distance: 21.578372955322266, entity: {}']"]  (api_request.py:37)

[2024-12-16T07:27:43.624Z] [2024-12-16 07:23:45 - INFO - ci_test]: assert search: 0.34995412826538086 (test_all_collections_after_chaos.py:99)

[2024-12-16T07:27:43.624Z] [2024-12-16 07:23:45 - DEBUG - ci_test]: (api_request)  : [Collection.query] args: ['int64 in [-3000, -2999, -2998, -2997, -2996, -2995, -2994, -2993, -2992, -2991, -2990, -2989, -2988, -2987, -2986, -2985, -2984, -2983, -2982, -2981, -2980, -2979, -2978, -2977, -2976, -2975, -2974, -2973, -2972, -2971, -2970, -2969, -2968, -2967, -2966, -2965, -2964, -2963, -2962, -2961, -2960, -......, kwargs: {} (api_request.py:62)

[2024-12-16T07:27:43.624Z] [2024-12-16 07:23:46 - DEBUG - ci_test]: (api_response) : data: ["{'int64': -3000}", "{'int64': -2999}", "{'int64': -2998}", "{'int64': -2997}", "{'int64': -2996}", "{'int64': -2995}", "{'int64': -2994}", "{'int64': -2993}", "{'int64': -2992}", "{'int64': -2991}"] ...  (api_request.py:37)

[2024-12-16T07:27:43.624Z] [2024-12-16 07:23:46 - INFO - ci_test]: assert query result 2000: 0.38707447052001953 (test_all_collections_after_chaos.py:106)

[2024-12-16T07:27:43.624Z] [2024-12-16 07:23:46 - DEBUG - ci_test]: (api_request)  : [Collection.release] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-12-16T07:27:43.624Z] [2024-12-16 07:23:47 - DEBUG - ci_test]: (api_response) : None  (api_request.py:37)

[2024-12-16T07:27:43.624Z] [2024-12-16 07:23:51 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [[{'int64': -8179815330524966693, 'float': 0.5086523, 'varchar': 'xprtptjwprxtonpdtps', 'text': 'Me side alone ok sometimes. Manager source bill measure represent.', 'json_field': {'name': 'Gina Smith', 'address': '6644 Travis Alley Suite 272\nRobertberg, GU 51540'}, 'array_int': [-15181779988349439......, kwargs: {'timeout': 180} (api_request.py:62)

[2024-12-16T07:27:43.624Z] [2024-12-16 07:23:51 - DEBUG - ci_test]: (api_response) : (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 454645208001806337, success count: 2000, err count: 0  (api_request.py:37)

[2024-12-16T07:27:43.624Z] [2024-12-16 07:23:51 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 180], kwargs: {} (api_request.py:62)

[2024-12-16T07:27:43.624Z] [2024-12-16 07:26:51 - ERROR - pymilvus.decorators]: RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=wait for loading collection timeout, collection: Checker__8GDm0TZr)>, <Time:{'RPC start': '2024-12-16 07:23:51.904099', 'RPC error': '2024-12-16 07:26:51.954003'}> (decorators.py:140)

[2024-12-16T07:27:43.624Z] [2024-12-16 07:26:51 - WARNING - pymilvus.decorators]: Retry timeout: 180s (decorators.py:106)

[2024-12-16T07:27:43.624Z] [2024-12-16 07:26:51 - ERROR - pymilvus.decorators]: RPC error: [load_collection], <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for loading collection timeout, collection: Checker__8GDm0TZr)>, <Time:{'RPC start': '2024-12-16 07:23:51.895457', 'RPC error': '2024-12-16 07:26:51.954842'}> (decorators.py:140)

[2024-12-16T07:27:43.624Z] [2024-12-16 07:26:51 - ERROR - ci_test]: Traceback (most recent call last):

[2024-12-16T07:27:43.624Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2024-12-16T07:27:43.624Z]     res = func(*args, **_kwargs)

[2024-12-16T07:27:43.625Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2024-12-16T07:27:43.625Z]     return func(*arg, **kwargs)

[2024-12-16T07:27:43.625Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/orm/collection.py", line 427, in load

[2024-12-16T07:27:43.625Z]     conn.load_collection(

[2024-12-16T07:27:43.625Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 141, in handler

[2024-12-16T07:27:43.625Z]     raise e from e

[2024-12-16T07:27:43.625Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 137, in handler

[2024-12-16T07:27:43.625Z]     return func(*args, **kwargs)

[2024-12-16T07:27:43.625Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 176, in handler

[2024-12-16T07:27:43.625Z]     return func(self, *args, **kwargs)

[2024-12-16T07:27:43.625Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 107, in handler

[2024-12-16T07:27:43.625Z]     raise MilvusException(

[2024-12-16T07:27:43.625Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for loading collection timeout, collection: Checker__8GDm0TZr)>

[2024-12-16T07:27:43.625Z]  (api_request.py:45)

[2024-12-16T07:27:43.625Z] [2024-12-16 07:26:51 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Retry timeout: 180s, message=wait for loading collection timeout, collection: Checker__8GDm0TZr)> (api_request.py:46)
```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/19824/pipeline
log:
[artifacts-mixcoord-pod-kill-19824-server-logs.tar.gz](https://github.com/user-attachments/files/18147009/artifacts-mixcoord-pod-kill-19824-server-logs.tar.gz)

cluster: 4am
namespace: chaos-testing
pod info
```
[2024-12-16T07:21:49.041Z] + kubectl get pods -o wide

[2024-12-16T07:21:49.042Z] + grep mixcoord-pod-kill-19824

[2024-12-16T07:21:49.298Z] mixcoord-pod-kill-19824-etcd-0                                 1/1     Running                 0                38m     10.104.32.206   4am-node39   <none>           <none>

[2024-12-16T07:21:49.298Z] mixcoord-pod-kill-19824-etcd-1                                 1/1     Running                 0                38m     10.104.26.143   4am-node32   <none>           <none>

[2024-12-16T07:21:49.298Z] mixcoord-pod-kill-19824-etcd-2                                 1/1     Running                 0                38m     10.104.33.144   4am-node36   <none>           <none>

[2024-12-16T07:21:49.298Z] mixcoord-pod-kill-19824-milvus-datanode-666c966fdf-mpgtq       1/1     Running                 2 (38m ago)      38m     10.104.25.88    4am-node30   <none>           <none>

[2024-12-16T07:21:49.298Z] mixcoord-pod-kill-19824-milvus-datanode-666c966fdf-zm9r8       1/1     Running                 2 (38m ago)      38m     10.104.34.83    4am-node37   <none>           <none>

[2024-12-16T07:21:49.298Z] mixcoord-pod-kill-19824-milvus-indexnode-84647f6fbd-6mlzv      1/1     Running                 2 (38m ago)      38m     10.104.16.198   4am-node21   <none>           <none>

[2024-12-16T07:21:49.298Z] mixcoord-pod-kill-19824-milvus-indexnode-84647f6fbd-stnk7      1/1     Running                 2 (38m ago)      38m     10.104.15.219   4am-node20   <none>           <none>

[2024-12-16T07:21:49.298Z] mixcoord-pod-kill-19824-milvus-indexnode-84647f6fbd-wlxx8      1/1     Running                 2 (38m ago)      38m     10.104.21.53    4am-node24   <none>           <none>

[2024-12-16T07:21:49.298Z] mixcoord-pod-kill-19824-milvus-mixcoord-7bf7684696-jtsqm       1/1     Running                 2 (38m ago)      38m     10.104.16.199   4am-node21   <none>           <none>

[2024-12-16T07:21:49.298Z] mixcoord-pod-kill-19824-milvus-proxy-55bcdcd84-qtq4v           1/1     Running                 2 (38m ago)      38m     10.104.21.51    4am-node24   <none>           <none>

[2024-12-16T07:21:49.298Z] mixcoord-pod-kill-19824-milvus-querynode-78c467bfbb-bwsrg      1/1     Running                 9 (8m3s ago)     38m     10.104.16.200   4am-node21   <none>           <none>

[2024-12-16T07:21:49.298Z] mixcoord-pod-kill-19824-milvus-querynode-78c467bfbb-hlmvt      1/1     Running                 9 (12m ago)      38m     10.104.34.84    4am-node37   <none>           <none>

[2024-12-16T07:21:49.298Z] mixcoord-pod-kill-19824-milvus-querynode-78c467bfbb-t6zw8      0/1     Running                 10 (6m22s ago)   38m     10.104.21.52    4am-node24   <none>           <none>

[2024-12-16T07:21:49.298Z] mixcoord-pod-kill-19824-minio-0                                1/1     Running                 0                38m     10.104.32.210   4am-node39   <none>           <none>

[2024-12-16T07:21:49.298Z] mixcoord-pod-kill-19824-minio-1                                1/1     Running                 0                38m     10.104.26.144   4am-node32   <none>           <none>

[2024-12-16T07:21:49.298Z] mixcoord-pod-kill-19824-minio-2                                1/1     Running                 0                38m     10.104.16.206   4am-node21   <none>           <none>

[2024-12-16T07:21:49.298Z] mixcoord-pod-kill-19824-minio-3                                1/1     Running                 0                38m     10.104.23.49    4am-node27   <none>           <none>

[2024-12-16T07:21:49.298Z] mixcoord-pod-kill-19824-pulsarv3-bookie-0                      1/1     Running                 0                38m     10.104.32.208   4am-node39   <none>           <none>

[2024-12-16T07:21:49.298Z] mixcoord-pod-kill-19824-pulsarv3-bookie-1                      1/1     Running                 0                38m     10.104.26.147   4am-node32   <none>           <none>

[2024-12-16T07:21:49.298Z] mixcoord-pod-kill-19824-pulsarv3-bookie-2                      1/1     Running                 0                38m     10.104.16.207   4am-node21   <none>           <none>

[2024-12-16T07:21:49.298Z] mixcoord-pod-kill-19824-pulsarv3-bookie-init-57t6q             0/1     Completed               0                38m     10.104.14.160   4am-node18   <none>           <none>

[2024-12-16T07:21:49.298Z] mixcoord-pod-kill-19824-pulsarv3-broker-0                      1/1     Running                 0                38m     10.104.14.162   4am-node18   <none>           <none>

[2024-12-16T07:21:49.298Z] mixcoord-pod-kill-19824-pulsarv3-broker-1                      1/1     Running                 0                38m     10.104.6.93     4am-node13   <none>           <none>

[2024-12-16T07:21:49.298Z] mixcoord-pod-kill-19824-pulsarv3-proxy-0                       1/1     Running                 0                38m     10.104.6.92     4am-node13   <none>           <none>

[2024-12-16T07:21:49.298Z] mixcoord-pod-kill-19824-pulsarv3-proxy-1                       1/1     Running                 0                38m     10.104.13.22    4am-node16   <none>           <none>

[2024-12-16T07:21:49.298Z] mixcoord-pod-kill-19824-pulsarv3-pulsar-init-zxdnv             0/1     Completed               0                38m     10.104.14.159   4am-node18   <none>           <none>

[2024-12-16T07:21:49.298Z] mixcoord-pod-kill-19824-pulsarv3-recovery-0                    1/1     Running                 0                38m     10.104.13.23    4am-node16   <none>           <none>

[2024-12-16T07:21:49.299Z] mixcoord-pod-kill-19824-pulsarv3-zookeeper-0                   1/1     Running                 0                38m     10.104.32.207   4am-node39   <none>           <none>

[2024-12-16T07:21:49.299Z] mixcoord-pod-kill-19824-pulsarv3-zookeeper-1                   1/1     Running                 0                38m     10.104.26.142   4am-node32   <none>           <none>

[2024-12-16T07:21:49.299Z] mixcoord-pod-kill-19824-pulsarv3-zookeeper-2                   1/1     Running                 0                38m     10.104.16.205   4am-node21   <none>           <none>
```

querynode is in a unhealthy status

### Anything else?

This also reproduced in minio pod kill chaos test

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/19831/pipeline
log:
[artifacts-s3-pod-kill-19831-server-logs.tar.gz](https://github.com/user-attachments/files/18147076/artifacts-s3-pod-kill-19831-server-logs.tar.gz)

**Comment by weiliu1031** [comment]
![image](https://github.com/user-attachments/assets/313e67c0-5bb0-496c-a1cf-15da07c66f18)
querynode panic due to segmentation fault

**Comment by zhuwenxing** [comment]
not a stable reproduced issue.
image tag: master-20241217-5d014c76-amd64
successful job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/19846/pipeline

**Comment by chyezh** [comment]
may be same with #38546

**Comment by zhuwenxing** [comment]
Not reproduced recently

verified and fixed in `master-20250113-640a49ff-amd64`
