### ISSUE TITLE
[Bug]: [Nightly] The error message of invalid alter index params is inaccurate

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#38517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 3e2a2f2
- Deployment mode(standalone or cluster):cluster & standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The error message of invalid alter index params is inaccurate.
```
024-12-16T21:46:23Z {container="step-test"} [2024-12-16 19:41:13 - ERROR - ci_test]: Traceback (most recent call last):
2024-12-16T21:46:23Z {container="step-test"} File "/milvus/tests/python_client/utils/api_request.py", line 32, in inner_wrapper
2024-12-16T21:46:23Z {container="step-test"} res = func(*args, **_kwargs)
2024-12-16T21:46:23Z {container="step-test"} File "/milvus/tests/python_client/utils/api_request.py", line 63, in api_request
2024-12-16T21:46:23Z {container="step-test"} return func(*arg, **kwargs)
2024-12-16T21:46:23Z {container="step-test"} File "/usr/local/lib/python3.10/site-packages/pymilvus/orm/collection.py", line 1409, in alter_index
2024-12-16T21:46:23Z {container="step-test"} return conn.alter_index_properties(self._name, index_name, extra_params, timeout=timeout)
2024-12-16T21:46:23Z {container="step-test"} File "/usr/local/lib/python3.10/site-packages/pymilvus/decorators.py", line 141, in handler
2024-12-16T21:46:23Z {container="step-test"} raise e from e
2024-12-16T21:46:23Z {container="step-test"} File "/usr/local/lib/python3.10/site-packages/pymilvus/decorators.py", line 137, in handler
2024-12-16T21:46:23Z {container="step-test"} return func(*args, **kwargs)
2024-12-16T21:46:23Z {container="step-test"} File "/usr/local/lib/python3.10/site-packages/pymilvus/decorators.py", line 176, in handler
2024-12-16T21:46:23Z {container="step-test"} return func(self, *args, **kwargs)
2024-12-16T21:46:23Z {container="step-test"} File "/usr/local/lib/python3.10/site-packages/pymilvus/decorators.py", line 116, in handler
2024-12-16T21:46:23Z {container="step-test"} raise e from e
2024-12-16T21:46:23Z {container="step-test"} File "/usr/local/lib/python3.10/site-packages/pymilvus/decorators.py", line 86, in handler
2024-12-16T21:46:23Z {container="step-test"} return func(*args, **kwargs)
2024-12-16T21:46:23Z {container="step-test"} File "/usr/local/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 1053, in alter_index_properties
2024-12-16T21:46:23Z {container="step-test"} check_status(response)
2024-12-16T21:46:23Z {container="step-test"} File "/usr/local/lib/python3.10/site-packages/pymilvus/client/utils.py", line 63, in check_status
2024-12-16T21:46:23Z {container="step-test"} raise MilvusException(status.code, status.reason, status.error_code)
2024-12-16T21:46:23Z {container="step-test"} pymilvus.exceptions.MilvusException: <MilvusException: (code=1100, message=error_param_key is not a configable index proptery: invalid parameter)>
2024-12-16T21:46:23Z {container="step-test"} (api_request.py:45)
2024-12-16T21:46:23Z {container="step-test"} [2024-12-16 19:41:13 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1100, message=error_param_key is not a configable index proptery: invalid parameter)> (api_request.py:46)
```

Here error_param_key is not a configable index `proptery` should be `property`.

### Expected Behavior

pass

### Milvus Log

1. link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI(new)/detail/master/214/pipeline/168
2. failed case: test_alter_index_invalid

**Comment by JsDove** [comment]
It has been fixed and the error message has been corrected.

**Comment by yanliang567** [comment]
/assign @NicoYuan1986 
please help to verify the fix

/unassign @JsDove
