### ISSUE TITLE
[Bug]: [GoSDK][ci] The queryNode crash when running go-sdk ci TestSearchGroupByFloatGrowing

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#38533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

- https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI(go-sdk)/detail/PR-38219/7/pipeline
```
2024-12-17T03:21:39Z {container="step-test"} [2024/12/17 03:21:39.525 +00:00] [INFO] [base/milvus_client.go:32] [Response] [method=Search] [resp="{\"status\":{\"error_code\":1,\"reason\":\"stack trace: /workspace/source/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace\\n/workspace/source/internal/util/grpcclient/client.go:575 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call\\n/workspace/source/......"]
```
```
#7 0x7f048889618f in milvus::exec::GrowingDataGetter<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Get(long) const /workspace/source/internal/core/src/exec/operator/groupby/SearchGroupByOperator.h:54
2024-12-17 03:20:22.177
    #6 0x7f048889618f in milvus::segcore::ConcurrentVector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::view_element(long) const /workspace/source/internal/core/src/segcore/ConcurrentVector.h:410
2024-12-17 03:20:22.177
    #5 0x7f04870b6ed3 in milvus::ThreadSafeChunkVector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, folly::fbvector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, false>::view_element(long, long) /workspace/source/internal/core/src/mmap/ChunkVector.h:125
```

**Comment by ThreadDao** [comment]
fixed
