### ISSUE TITLE
[Bug]: [Nightly] Insert/ delete failed reporting `time tick long delay`

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#38589]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 98052cf
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Insert/ delete failed reporting `time tick long delay`.
```
[2024-12-18 17:58:09 - DEBUG - ci_test]: (api_request)  : [Collection.delete] args: ['NewStr != "0"', None, 180], kwargs: {} (api_request.py:56)
[2024-12-18 17:58:09 - ERROR - pymilvus.decorators]: RPC error: [delete], <MilvusException: (code=9, message=quota exceeded[reason=time tick long delay])>, <Time:{'RPC start': '2024-12-18 17:58:09.205091', 'RPC error': '2024-12-18 17:58:09.207851'}> (decorators.py:145)
[2024-12-18 17:58:09 - ERROR - ci_test]: Traceback (most recent call last):
  File "/src/milvus-cloud-test/python_client/utils/api_request.py", line 26, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/src/milvus-cloud-test/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 580, in delete
    res = conn.delete(self._name, expr, partition_name, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 146, in handler
    raise e from e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 142, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 181, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 121, in handler
    raise e from e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 87, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 650, in delete
    raise err from err
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 644, in delete
    check_status(response.status)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/utils.py", line 63, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=9, message=quota exceeded[reason=time tick long delay])>
 (api_request.py:39)
[2024-12-18 17:58:09 - ERROR - ci_test]: (api_response) : <MilvusException: (code=9, message=quota exceeded[reason=time tick long delay])> (api_request.py:40)
```

### Expected Behavior

pass

**Comment by XuanYang-cn** [comment]
/assign @NicoYuan1986
/unassign
Please help verify

**Comment by yanliang567** [comment]
not reproduce on milvus 2.4.18
