### ISSUE TITLE
Error with data compact

### ISSUE THREAD

**Issue by shiyu22** [milvus-io/milvus#4026]
**Please state your issue using the following template and, most importantly, in English.**

**Location of incorrect documentation**
[Data compact](https://milvus.io/cn/docs/v0.11.0/compact_python.md)

**Describe the problems or issues found in the documentation**
 When I run `milvus.compact(collection_name='test01', timeout='1')`, it shows

Addr [192.168.1.58:19520] compact
Excepted error: unsupported operand type(s) for +: 'float' and 'str'
        {'API start': '2020-10-19 15:30:29.191418', 'RPC start': '2020-10-19 15:30:29.192269', 'Exception': '2020-10-19 15:30:29.192338'}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/workspace/conda/miniconda3/envs/video/lib/python3.7/site-packages/milvus/client/stub.py", line 33, in inner
    return func(self, *args, **kwargs)
  File "/data/workspace/conda/miniconda3/envs/video/lib/python3.7/site-packages/milvus/client/stub.py", line 675, in compact
    return handler.compact(collection_name, threshold, timeout, **kwargs)
  File "/data/workspace/conda/miniconda3/envs/video/lib/python3.7/site-packages/milvus/client/grpc_handler.py", line 63, in handler
    raise e
  File "/data/workspace/conda/miniconda3/envs/video/lib/python3.7/site-packages/milvus/client/grpc_handler.py", line 42, in handler
    return func(self, *args, **kwargs)
  File "/data/workspace/conda/miniconda3/envs/video/lib/python3.7/site-packages/milvus/client/grpc_handler.py", line 561, in compact
    future = self._stub.Compact.future(request, wait_for_ready=True, timeout=timeout)
  File "/data/workspace/conda/miniconda3/envs/video/lib/python3.7/site-packages/grpc/_channel.py", line 847, in future
    request, timeout, metadata, wait_for_ready, compression)
  File "/data/workspace/conda/miniconda3/envs/video/lib/python3.7/site-packages/grpc/_channel.py", line 779, in _prepare
    request, timeout, self._request_serializer)
  File "/data/workspace/conda/miniconda3/envs/video/lib/python3.7/site-packages/grpc/_channel.py", line 710, in _start_unary_request
    deadline = _deadline(timeout)
  File "/data/workspace/conda/miniconda3/envs/video/lib/python3.7/site-packages/grpc/_channel.py", line 85, in _deadline
    return None if timeout is None else time.time() + timeout
TypeError: unsupported operand type(s) for +: 'float' and 'str'

**Suggested fix for documentation**
`milvus.compact(collection_name='test01', timeout=1)`

**Comment by BossZou** [comment]
The example for `compact()` has been updated [here](https://milvus.io/cn/docs/v0.11.0/compact_python.md).

-------------------------------------------------------------------------------------
Fixed. Close it.
