### ISSUE TITLE
Database is locked returned when run locust search for a while

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#4040]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
05:46:17   Name                                                          # reqs      # fails     Avg     Min     Max  |  Median   req/s failures/s
05:46:17  --------------------------------------------------------------------------------------------------------------------------------------------
05:46:17   grpc query                                                     22549     0(0.00%)     135      22    1114  |     120  112.80    0.00
05:46:17  --------------------------------------------------------------------------------------------------------------------------------------------
05:46:17   Aggregated                                                     22549     0(0.00%)     135      22    1114  |     120  112.80    0.00
05:46:17  
05:46:17  error_code: META_FAILED
05:46:17  reason: "Encounter exception when describe collection:database is locked: database is locked"
05:46:17  
05:46:17  [2020-10-20 21:46:17,715] test-benchmark-milvus-benchmark-0.10.4-8-lf1c4-4m90h/ERROR/milvus.client.grpc_handler: error_code: META_FAILED
05:46:17  reason: "Encounter exception when describe collection:database is locked: database is locked"
05:46:17  
05:46:17  [2020-10-20 21:46:17,718] test-benchmark-milvus-benchmark-0.10.4-8-lf1c4-4m90h/ERROR/locust.user.task: 'NoneType' object has no attribute 'metric_type'
05:46:17  Traceback (most recent call last):
05:46:17    File "/usr/local/lib/python3.6/site-packages/locust/user/task.py", line 284, in run
05:46:17      self.execute_next_task()
05:46:17    File "/usr/local/lib/python3.6/site-packages/locust/user/task.py", line 309, in execute_next_task
05:46:17      self.execute_task(self._task_queue.pop(0))
05:46:17    File "/usr/local/lib/python3.6/site-packages/locust/user/task.py", line 416, in execute_task
05:46:17      task(self.user)
05:46:17    File "/home/jenkins/agent/workspace/milvus-benchmark-0.10.4/milvus_benchmark/milvus-benchmark-test-r1i3xcwm.py", line 36, in query
05:46:17      client = get_client(collection_name)
05:46:17    File "/home/jenkins/agent/workspace/milvus-benchmark-0.10.4/milvus_benchmark/milvus-benchmark-test-r1i3xcwm.py", line 24, in get_client
05:46:17      return MilvusTask(connection_type='multi', host=host, port=port, collection_name=collection_name)
05:46:17    File "/home/jenkins/agent/workspace/milvus-benchmark-0.10.4/milvus_benchmark/locust_task.py", line 16, in __init__
05:46:17      self.m = MilvusClient(host=host, port=port, collection_name=collection_name)
05:46:17    File "/home/jenkins/agent/workspace/milvus-benchmark-0.10.4/milvus_benchmark/client.py", line 85, in __init__
05:46:17      self._metric_type = self._metric_type_to_str(self.describe()[1].metric_type)
05:46:17  AttributeError: 'NoneType' object has no attribute 'metric_type'
```
The `self.describe` function is actually the `get_collection_info`
```
    def describe(self):
        return self._milvus.get_collection_info(self._collection_name)
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.
1. create a collection and insert 1 million entities with index_file_size 1024 (sift_1m_1024_128_l2)
2. execute `search` for 5 minutes with `locust -f x.py --headless -u 100 -r 2 -t 5m`
```

import random
import string
from locust import User, task, between
from locust_task import MilvusTask
from client import MilvusClient

host = '192.168.1.6'
port = 19530
dim = 128
connection_type = 'multi'
collection_names = ['sift_1m_1024_128_l2_Q6itv']
m = MilvusClient(host=host, port=port)


def get_collection_name():
    return random.choice(collection_names)
    
    
def get_client(collection_name):
    if connection_type == 'single':
        return MilvusTask(m=m)
    elif connection_type == 'multi':
        return MilvusTask(connection_type='multi', host=host, port=port, collection_name=collection_name)
        

class QueryTask(User):
    wait_time = between(0.001, 0.002)
        
    @task()
    def query(self):
        top_k = 10
        X = [[random.random() for i in range(dim)] for i in range(1)]
        search_param = {'nprobe': 16}
        collection_name = get_collection_name()
        print(collection_name)
        client = get_client(collection_name)
        client.query(X, top_k, search_param, collection_name=collection_name)
            
```

**Expected behavior**

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 - 0.10.4

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
sqlite_orm throw exception. Similar to #3998

**Comment by shengjun1985** [comment]
Please allow me to close the duplicate issues.
Let usl trace the problem in the issue 3998.

**Comment by yhmo** [comment]
Please double-check this issue, I think it is already fixed by pr4066
