### ISSUE TITLE
pymilvus安装不上

### ISSUE THREAD

**Issue by herryzhang** [milvus-io/milvus#4088]
操作系统 Ubuntu18.04
Python  3.5.4
Milvus 0.11.0
pymilvus  0.3.0
报错信息如下
(/data/zkn/envs/pytorch2/milvus) amax@amax:/data2/apps$ python3 example.py 
Traceback (most recent call last):
  File "example.py", line 4, in <module>
    from milvus import Milvus, DataType
  File "/data/zkn/envs/pytorch2/milvus/lib/python3.5/site-packages/milvus/__init__.py", line 3, in <module>
    from .client.stub import Milvus
  File "/data/zkn/envs/pytorch2/milvus/lib/python3.5/site-packages/milvus/client/stub.py", line 11, in <module>
    from .check import check_pass_param, is_legal_host, is_legal_port
  File "/data/zkn/envs/pytorch2/milvus/lib/python3.5/site-packages/milvus/client/check.py", line 5, in <module>
    from .exceptions import ParamError
  File "/data/zkn/envs/pytorch2/milvus/lib/python3.5/site-packages/milvus/client/exceptions.py", line 64
    return f"<{type(self).__name__}: (code={self._code}, message={self._message})>"
                                                                                  ^
SyntaxError: invalid syntax

**Comment by BossZou** [comment]
@herryzhang , you are recommended to use python 3.6 to run pymilvus. I'm sorry that it's a bug and we'll solve in pymilvus 0.3.1.

**Comment by herryzhang** [comment]
后来我换了下Python版本就可以了，我看你们的文档操作的，看来文档有些滞后了

**Comment by BossZou** [comment]
@herryzhang , thanks for your issue, we'll improve documentation soon.

**Comment by BossZou** [comment]
@PahudPlus , need update documentation at official site.

**Comment by ireneontheway5** [comment]
> The following page should be fixed.
> https://milvus.io/docs/v0.11.0/example_code.md

I've updated it in https://milvus.io/cn/docs/example_code.md.
