### ISSUE TITLE
The node crashes during the second round of queries

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#4481]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
The first round search costs too much time and the second round meets 502 status code.
```
16:36:50  DEBUG:milvus_benchmark.client:Row count: 10000000 in collection: <sift_10m_2000000_128_l2_011>
16:36:50  2020-12-18 08:36:49,649 - milvus_benchmark.k8s_runner - INFO - 10000000
16:36:50  INFO:milvus_benchmark.k8s_runner:10000000
16:36:50  2020-12-18 08:36:49,651 - milvus_benchmark.k8s_runner - INFO - {'index_type': 'flat', 'index_param': None}
16:36:50  INFO:milvus_benchmark.k8s_runner:{'index_type': 'flat', 'index_param': None}
16:36:50  2020-12-18 08:36:49,652 - milvus_benchmark.client - INFO - Milvus preload_collection start
16:36:50  INFO:milvus_benchmark.client:Milvus preload_collection start
16:37:03  2020-12-18 08:37:01,968 - milvus_benchmark.client - INFO - Milvus preload_collection run in 12.32s
16:37:03  INFO:milvus_benchmark.client:Milvus preload_collection run in 12.32s
16:37:03  2020-12-18 08:37:01,968 - milvus_benchmark.k8s_runner - INFO - Start warm up query
16:37:03  INFO:milvus_benchmark.k8s_runner:Start warm up query
16:37:03  2020-12-18 08:37:02,102 - milvus_benchmark.runner - INFO - Start query, query params: top-k: 1, nq: 1, actually length of vectors: 1
16:37:03  INFO:milvus_benchmark.runner:Start query, query params: top-k: 1, nq: 1, actually length of vectors: 1
16:37:03  2020-12-18 08:37:02,103 - milvus_benchmark.runner - INFO - Start run query, run 1 of 2
16:37:03  INFO:milvus_benchmark.runner:Start run query, run 1 of 2
16:37:03  2020-12-18 08:37:02,103 - milvus_benchmark.client - INFO - Milvus query start
16:37:03  INFO:milvus_benchmark.client:Milvus query start
16:37:22  2020-12-18 08:37:19,446 - milvus_benchmark.client - INFO - Milvus query run in 17.34s
16:37:22  INFO:milvus_benchmark.client:Milvus query run in 17.34s
16:37:22  2020-12-18 08:37:19,446 - milvus_benchmark.runner - INFO - Start run query, run 2 of 2
16:37:22  INFO:milvus_benchmark.runner:Start run query, run 2 of 2
16:37:22  2020-12-18 08:37:19,446 - milvus_benchmark.client - INFO - Milvus query start
16:37:22  INFO:milvus_benchmark.client:Milvus query start
16:37:27  
16:37:27  Addr [milvus-benchmark-test-r6opkqpn.milvus.svc.cluster.local:19530] search
16:37:27  RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
16:37:27  	status = StatusCode.UNAVAILABLE
16:37:27  	details = "Received http2 header with status: 502"
16:37:27  	debug_error_string = "{"created":"@1608280646.426403574","description":"Received http2 :status header with non-200 OK status","file":"src/core/ext/filters/http/client/http_client_filter.cc","file_line":130,"grpc_message":"Received http2 header with status: 502","grpc_status":14,"value":"502"}"
16:37:27  >
16:37:27  	{'API start': '2020-12-18 08:37:19.447205', 'RPC start': '2020-12-18 08:37:19.447240', 'RPC error': '2020-12-18 08:37:26.426910'}
16:37:27  ERROR:milvus.client.grpc_handler:
16:37:27  Addr [milvus-benchmark-test-r6opkqpn.milvus.svc.cluster.local:19530] search
16:37:27  RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
16:37:27  	status = StatusCode.UNAVAILABLE
16:37:27  	details = "Received http2 header with status: 502"
16:37:27  	debug_error_string = "{"created":"@1608280646.426403574","description":"Received http2 :status header with non-200 OK status","file":"src/core/ext/filters/http/client/http_client_filter.cc","file_line":130,"grpc_message":"Received http2 header with status: 502","grpc_status":14,"value":"502"}"
16:37:27  >
16:37:27  	{'API start': '2020-12-18 08:37:19.447205', 'RPC start': '2020-12-18 08:37:19.447240', 'RPC error': '2020-12-18 08:37:26.426910'}
16:37:27  2020-12-18 08:37:26,427 - milvus_benchmark - ERROR - <_MultiThreadedRendezvous of RPC that terminated with:
16:37:27  	status = StatusCode.UNAVAILABLE
16:37:27  	details = "Received http2 header with status: 502"
16:37:27  	debug_error_string = "{"created":"@1608280646.426403574","description":"Received http2 :status header with non-200 OK status","file":"src/core/ext/filters/http/client/http_client_filter.cc","file_line":130,"grpc_message":"Received http2 header with status: 502","grpc_status":14,"value":"502"}"
16:37:27  >
16:37:27  ERROR:milvus_benchmark:<_MultiThreadedRendezvous of RPC that terminated with:
16:37:27  	status = StatusCode.UNAVAILABLE
16:37:27  	details = "Received http2 header with status: 502"
16:37:27  	debug_error_string = "{"created":"@1608280646.426403574","description":"Received http2 :status header with non-200 OK status","file":"src/core/ext/filters/http/client/http_client_filter.cc","file_line":130,"grpc_message":"Received http2 header with status: 502","grpc_status":14,"value":"502"}"
16:37:27  >
16:37:27  2020-12-18 08:37:26,431 - milvus_benchmark - ERROR - Traceback (most recent call last):
16:37:27    File "main.py", line 82, in queue_worker
16:37:27      runner.run(run_type, collection)
16:37:27    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.1/milvus_benchmark/k8s_runner.py", line 384, in run
16:37:27      res = self.do_query(milvus_instance, collection_name, vec_field_name, [1], [1], 2, search_param=search_params[0], filter_query=filter_query)
16:37:27    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.1/milvus_benchmark/runner.py", line 274, in do_query
16:37:27      query_res = milvus.query(vector_query, filter_query=filter_query)
16:37:27    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.1/milvus_benchmark/client.py", line 42, in wrapper
16:37:27      result = func(*args, **kwargs)
16:37:27    File "/home/jenkins/agent/workspace/milvus-benchmark-0.11.1/milvus_benchmark/client.py", line 290, in query
16:37:27      result = self._milvus.search(tmp_collection_name, query)
16:37:27    File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 35, in inner
16:37:27      return func(self, *args, **kwargs)
16:37:27    File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 632, in search
16:37:27      fields, timeout=timeout, **kwargs)
16:37:27    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 63, in handler
16:37:27      raise e
16:37:27    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 44, in handler
16:37:27      return func(self, *args, **kwargs)
16:37:27    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 483, in search
16:37:27      response = ft.result()
16:37:27    File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 625, in result
16:37:27      raise self
16:37:27  grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
16:37:27  	status = StatusCode.UNAVAILABLE
16:37:27  	details = "Received http2 header with status: 502"
16:37:27  	debug_error_string = "{"created":"@1608280646.426403574","description":"Received http2 :status header with non-200 OK status","file":"src/core/ext/filters/http/client/http_client_filter.cc","file_line":130,"grpc_message":"Received http2 header with status: 502","grpc_status":14,"value":"502"}"
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**
1.deploy one ro-node and one rw-node
2. search from 10m(million) collection on ro-node

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 -0.11.1

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by XuPeng-SH** [comment]
@ThreadDao 
It is probably the read-only nodes are down. You can check the status of read-only nodes. It should be the same issue that the read-only nodes will crash in the concurrent test.

**Comment by ThreadDao** [comment]
yes, the node seems crashed. the log path is `/test/milvus/db_data_011/cluster/sift_10m_2000000_128_l2/logs/milvus-20-12-18-16:35-info.log`
```
[2020-12-18 16:36:49,644][INFO][SERVER][DescribeCollection][grpcpp_sync_ser] Request [2] DescribeCollection begin.
[2020-12-18 16:36:49,645][INFO][SERVER][DescribeCollection][grpcpp_sync_ser] Request [2] DescribeCollection end.
[2020-12-18 16:36:49,646][INFO][SERVER][HasCollection][grpcpp_sync_ser] Request [3] HasCollection begin.
[2020-12-18 16:36:49,647][INFO][SERVER][HasCollection][grpcpp_sync_ser] Request [3] HasCollection end.
[2020-12-18 16:36:49,648][INFO][SERVER][CountCollection][grpcpp_sync_ser] Request [4] CountCollection begin.
[2020-12-18 16:36:49,648][INFO][SERVER][CountCollection][grpcpp_sync_ser] Request [4] CountCollection end.
[2020-12-18 16:36:49,650][INFO][SERVER][DescribeCollection][grpcpp_sync_ser] Request [5] DescribeCollection begin.
[2020-12-18 16:36:49,650][INFO][SERVER][DescribeCollection][grpcpp_sync_ser] Request [5] DescribeCollection end.
[2020-12-18 16:36:49,653][INFO][SERVER][PreloadCollection][grpcpp_sync_ser] Request [6] PreloadCollection begin.
[2020-12-18 16:36:49,653][INFO][SERVER][PutToQueue][grpcpp_sync_ser] Create new thread for request group: dql
[2020-12-18 16:37:01,967][INFO][SERVER][PreloadCollection][grpcpp_sync_ser] Request [6] PreloadCollection end.
[2020-12-18 16:38:29,906][INFO][SERVER][HandleSignal][milvus_server] Server received critical signal: 15
[2020-12-18 16:38:29,912][INFO][SERVER][PrintStacktrace][milvus_server] Call stack:
[2020-12-18 16:38:29,912][INFO][SERVER][PrintStacktrace][milvus_server] /var/lib/milvus/bin/milvus_server(_ZN6milvus15PrintStacktraceEv+0x26) [0x112eb36]
[2020-12-18 16:38:29,912][INFO][SERVER][PrintStacktrace][milvus_server] /var/lib/milvus/bin/milvus_server(_ZN6milvus12HandleSignalEi+0x190) [0x112f6a0]
[2020-12-18 16:38:29,912][INFO][SERVER][PrintStacktrace][milvus_server] /lib64/libc.so.6(+0x36400) [0x7fe005729400]
[2020-12-18 16:38:29,912][INFO][SERVER][PrintStacktrace][milvus_server] /lib64/libc.so.6(epoll_wait+0x33) [0x7fe0057f1f43]
[2020-12-18 16:38:29,912][INFO][SERVER][PrintStacktrace][milvus_server] /var/lib/milvus/bin/milvus_server(_ZN5boost4asio6detail13epoll_reactor3runEbRNS1_8op_queueINS1_25task_io_service_operationEEE+0x3a) [0x1139b2a]
[2020-12-18 16:38:29,912][INFO][SERVER][PrintStacktrace][milvus_server] /var/lib/milvus/bin/milvus_server(_ZN5boost4asio6detail15task_io_service3runERNS_6system10error_codeE+0x1fc) [0x113c59c]
[2020-12-18 16:38:29,912][INFO][SERVER][PrintStacktrace][milvus_server] /var/lib/milvus/bin/milvus_server(_ZN6milvus12TimerManager3RunEv+0x30) [0x11360b0]
[2020-12-18 16:38:29,912][INFO][SERVER][PrintStacktrace][milvus_server] /var/lib/milvus/bin/milvus_server(_ZN6milvus6server6Server5StartEv+0xc5f) [0x7b2b7f]
[2020-12-18 16:38:29,912][INFO][SERVER][PrintStacktrace][milvus_server] /var/lib/milvus/bin/milvus_server(main+0x3fa) [0x75fefa]
[2020-12-18 16:38:29,912][INFO][SERVER][PrintStacktrace][milvus_server] /lib64/libc.so.6(__libc_start_main+0xf5) [0x7fe005715555]
[2020-12-18 16:38:29,912][INFO][SERVER][PrintStacktrace][milvus_server] /var/lib/milvus/bin/milvus_server() [0x77ae87]
[2020-12-18 16:38:30,482][INFO][ENGINE][Stop][milvus_server] OperationExecutor Stopped
[2020-12-18 16:38:30,482][INFO][SERVER][Stop][milvus_server] Scheduler gonna stop...
[2020-12-18 16:38:30,483][INFO][SERVER][Stop][milvus_server] Scheduler stopped
```
I will check this problem in the latest image
