### ISSUE TITLE
Collection not existed returned with nginx-delay as r/w proxy

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#4495]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
__________________ TestCompactBase.test_search_after_compact ___________________
[gw3] linux -- Python 3.6.8 /usr/local/bin/python3

self = <test_compact.TestCompactBase object at 0x7fdf01282978>
connect = <milvus.client.stub.Milvus object at 0x7fdf34deaeb8>
collection = 'test_g5vvyFWJ'

    @pytest.mark.timeout(COMPACT_TIMEOUT)
    def test_search_after_compact(self, connect, collection):
        '''
        target: test search after compact
        method: after compact operation, search vector
        expected: status ok
        '''
        ids = connect.bulk_insert(collection, default_entities)
        assert len(ids) == default_nb
        connect.flush([collection])
        status = connect.compact(collection)
        assert status.OK()
        query = copy.deepcopy(default_single_query)
        query["bool"]["must"][0]["vector"][field_name]["query"] = [default_entity[-1]["values"][0],
                                                                   default_entities[-1]["values"][0],
                                                                   default_entities[-1]["values"][-1]]
>       res = connect.search(collection, query)

test_compact.py:449: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.6/site-packages/milvus/client/stub.py:35: in inner
    return func(self, *args, **kwargs)
/usr/local/lib/python3.6/site-packages/milvus/client/stub.py:632: in search
    fields, timeout=timeout, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <milvus.client.grpc_handler.GrpcHandler object at 0x7fdf34bc5dd8>
args = ('test_g5vvyFWJ', {'bool': {'must': [{'vector': {'float_vector': {...}}}]}}, None, None)
kwargs = {'timeout': None}
record_dict = {'API start': '2020-12-22 02:42:23.160414', 'RPC start': '2020-12-22 02:42:23.161273'}

    def handler(self, *args, **kwargs):
        record_dict = {}
        try:
            record_dict["API start"] = str(datetime.datetime.now())
            if getattr(self, '_pre_ping'):
                self.ping()
            record_dict["RPC start"] = str(datetime.datetime.now())
            return func(self, *args, **kwargs)
        except BaseError as e:
            LOGGER.error(f"Error: {e.message}")
            if e.code == Status.ILLEGAL_COLLECTION_NAME:
                raise IllegalCollectionNameException(e.code, e.message)
            if e.code == Status.COLLECTION_NOT_EXISTS:
>               raise CollectionNotExistException(e.code, e.message)
E               milvus.client.exceptions.CollectionNotExistException: <CollectionNotExistException: (code=4, message=Collection not exist: test_g5vvyFWJ)>

/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py:50: CollectionNotExistException
----------------------------- Captured stderr call -----------------------------
Error: Collection not exist: test_g5vvyFWJ
------------------------------ Captured log call -------------------------------
[2020-12-22 02:42:23-ERROR-milvus.client.grpc_handler]: Error: Collection not exist: test_g5vvyFWJ (grpc_handler.py:46)
```
**Steps/Code to reproduce behavior**
nginx-delay
```
delay: 500ms
```
 1 read node and 1 writable node deployed

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by del-zhenwu** [comment]
connect readonly node directly after searching 10 mins:
```
>>> m=Milvus(host="milvus-benchmark-test-syn1zqrc.milvus", port=19530)
>>> m.list_collections()
['sift_10m_2000000_128_l2_011', 'sift_1m_2000000_128_l2_2', 'sift_50m_4000000_128_l2_011']
>>> m.count_entities('sift_10m_2000000_128_l2_011')
10000000
>>> m=Milvus(host="milvus-benchmark-test-syn1zqrc-readonly.milvus", port=19530)
>>> m.count_entities('sift_10m_2000000_128_l2_011')
Error: Collection not exist: sift_10m_2000000_128_l2_011
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 44, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 286, in count_entities
    raise BaseError(response.status.error_code, response.status.reason)
milvus.client.exceptions.BaseError: <BaseError: (code=4, message=Collection not exist: sift_10m_2000000_128_l2_011)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 35, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 257, in count_entities
    return handler.count_entities(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 50, in handler
    raise CollectionNotExistException(e.code, e.message)
milvus.client.exceptions.CollectionNotExistException: <CollectionNotExistException: (code=4, message=Collection not exist: sift_10m_2000000_128_l2_011)>
>>> m=Milvus(host="milvus-benchmark-test-syn1zqrc-writable.milvus", port=19530)
>>> m.count_entities('sift_10m_2000000_128_l2_011')
10000000

```

**Comment by del-zhenwu** [comment]
sometimes search ok:
```
19:58:29  2020-12-22 11:58:29,082 - milvus_benchmark.runner - INFO - Start query, query params: top-k: 1, nq: 1, actually length of vectors: 1
19:58:29  INFO:milvus_benchmark.runner:Start query, query params: top-k: 1, nq: 1, actually length of vectors: 1
19:58:29  2020-12-22 11:58:29,082 - milvus_benchmark.runner - INFO - Start run query, run 1 of 2
19:58:29  INFO:milvus_benchmark.runner:Start run query, run 1 of 2
19:58:29  2020-12-22 11:58:29,082 - milvus_benchmark.client - INFO - Milvus query start
19:58:29  INFO:milvus_benchmark.client:Milvus query start
19:58:29  Error: Collection not exist: sift_10m_2000000_128_l2_011
19:58:29  ERROR:milvus.client.grpc_handler:Error: Collection not exist: sift_10m_2000000_128_l2_011
19:58:29  2020-12-22 11:58:29,155 - milvus_benchmark.runner - INFO - Start query, query params: top-k: 1, nq: 1, actually length of vectors: 1
19:58:29  INFO:milvus_benchmark.runner:Start query, query params: top-k: 1, nq: 1, actually length of vectors: 1
19:58:29  2020-12-22 11:58:29,156 - milvus_benchmark.runner - INFO - Start run query, run 1 of 2
19:58:29  INFO:milvus_benchmark.runner:Start run query, run 1 of 2
19:58:29  2020-12-22 11:58:29,156 - milvus_benchmark.client - INFO - Milvus query start
19:58:29  INFO:milvus_benchmark.client:Milvus query start
19:58:30  2020-12-22 11:58:29,680 - milvus_benchmark.client - INFO - Milvus query run in 0.52s
19:58:30  INFO:milvus_benchmark.client:Milvus query run in 0.52s
19:58:30  2020-12-22 11:58:29,681 - milvus_benchmark.runner - INFO - Start run query, run 2 of 2
19:58:30  INFO:milvus_benchmark.runner:Start run query, run 2 of 2
19:58:30  2020-12-22 11:58:29,681 - milvus_benchmark.client - INFO - Milvus query start
19:58:30  INFO:milvus_benchmark.client:Milvus query start
19:58:30  2020-12-22 11:58:30,215 - milvus_benchmark.client - INFO - Milvus query run in 0.53s
19:58:30  INFO:milvus_benchmark.client:Milvus query run in 0.53s
19:58:30  2020-12-22 11:58:30,215 - milvus_benchmark.runner - INFO - Min query time: 0.53
19:58:30  INFO:milvus_benchmark.runner:Min query time: 0.53
19:58:30  2020-12-22 11:58:30,240 - milvus_benchmark.k8s_runner - INFO - End warm up query
19:58:30  INFO:milvus_benchmark.k8s_runner:End warm up query
19:58:30  2020-12-22 11:58:30,240 - milvus_benchmark.k8s_runner - INFO - Search param: {"nprobe": 8}
19:58:30  INFO:milvus_benchmark.k8s_runner:Search param: {"nprobe": 8}
19:58:30  2020-12-22 11:58:30,240 - milvus_benchmark.k8s_runner - INFO - filter param: []
19:58:30  INFO:milvus_benchmark.k8s_runner:filter param: []
19:58:30  2020-12-22 11:58:30,312 - milvus_benchmark.runner - INFO - Start query, query params: top-k: 1, nq: 1, actually length of vectors: 1
19:58:30  INFO:milvus_benchmark.runner:Start query, query params: top-k: 1, nq: 1, actually length of vectors: 1
19:58:30  2020-12-22 11:58:30,313 - milvus_benchmark.runner - INFO - Start run query, run 1 of 10
19:58:30  INFO:milvus_benchmark.runner:Start run query, run 1 of 10
19:58:30  2020-12-22 11:58:30,313 - milvus_benchmark.client - INFO - Milvus query start
19:58:30  INFO:milvus_benchmark.client:Milvus query start
19:58:30  Error: Collection not exist: sift_10m_2000000_128_l2_011
19:58:30  ERROR:milvus.client.grpc_handler:Error: Collection not exist: sift_10m_2000000_128_l2_011
19:58:30  2020-12-22 11:58:30,316 - milvus_benchmark - ERROR - <CollectionNotExistException: (code=4, message=Collection not exist: sift_10m_2000000_128_l2_011)>
19:58:30  ERROR:milvus_benchmark:<CollectionNotExistException: (code=4, message=Collection not exist: sift_10m_2000000_128_l2_011)>
19:58:30  2020-12-22 11:58:30,318 - milvus_benchmark - ERROR - Traceback (most recent call last):
19:58:30    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 44, in handler
19:58:30      return func(self, *args, **kwargs)
19:58:30    File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 490, in search
19:58:30      raise BaseError(response.status.error_code, response.status.reason)
19:58:30  milvus.client.exceptions.BaseError: <BaseError: (code=4, message=Collection not exist: sift_10m_2000000_128_l2_011)>
```

**Comment by del-zhenwu** [comment]
close
