### ISSUE TITLE
"java.math.BigDecimal cannot be cast to java.lang.Float" occurs when querying.

### ISSUE THREAD

**Issue by thankslife** [milvus-io/milvus#4849]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
milvus-sdk-java 1.0.0
java.lang.ClassCastException: java.math.BigDecimal cannot be cast to java.lang.Float
	at com.google.protobuf.FloatArrayList.add(FloatArrayList.java:45)
	at com.google.protobuf.AbstractMessageLite$Builder.addAllCheckingNulls(AbstractMessageLite.java:381)
	at com.google.protobuf.AbstractMessageLite$Builder.addAll(AbstractMessageLite.java:434)
	at io.milvus.grpc.RowRecord$Builder.addAllFloatData(RowRecord.java:611)
	at io.milvus.client.AbstractMilvusGrpcClient.buildRowRecordList(MilvusGrpcClient.java:1341)
	at io.milvus.client.AbstractMilvusGrpcClient.search(MilvusGrpcClient.java:639)
	at io.milvus.client.MilvusGrpcClient.search(MilvusGrpcClient.java:49)
	at com.hymars.MilvusClientService.search(MilvusClientService.java:98)

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
@thankslife 
Could you provide some code can reproduce this error?

**Comment by shengjun1985** [comment]
>  "BigDecimal cannot be cast to Float".

It seems that the data type is unmatched.

**Comment by yhmo** [comment]
The SearchParam require a list of Float type. I guess you got wrong type.

```
List<List<Float>> vectorsToSearch = ......
SearchParam searchParam = new SearchParam.Builder(collectionName)
       .withFloatVectors(vectorsToSearch)
       .withTopK(topK)
       .withParamsInJson(searchParamsJson.toString())
       .build();
```

**Comment by thankslife** [comment]
抱歉，是我的工程里从bert服务获取json数据进行转换时的出现问题，没有及时暴露导致后面与float转换才发生异常
