### ISSUE TITLE
connect milvus failed

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#4975]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
>>> m=Milvus(host="127.0.0.1", port=19531)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/milvus/client/stub.py", line 98, in __init__
    self._pool = SingletonThreadPool(pool_uri, **pool_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/milvus/client/pool.py", line 226, in __init__
    self._prepare()
  File "/usr/local/lib/python3.6/dist-packages/milvus/client/pool.py", line 241, in _prepare
    support_versions))
milvus.client.exceptions.VersionError: Version of python SDK(1.0.1.dev21) not match that of server1.1.0, excepted is ('1.0.x',)
```
**Steps/Code to reproduce behavior**

pymilvus-1.0.1.dev21

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by scsven** [comment]
@del-zhenwu It will be fix in [This PR](https://github.com/milvus-io/pymilvus/pull/491)

**Comment by scsven** [comment]
@del-zhenwu Package has been update in PyPI Test.

**Comment by del-zhenwu** [comment]
install pymilvus from `test.pypi` failed:

```
[2021-04-21T04:53:29.414Z] + python3 -m pip install --index-url https://test.pypi.org/simple/ pymilvus

[2021-04-21T04:53:29.682Z] Looking in indexes: https://test.pypi.org/simple/

[2021-04-21T04:53:29.682Z] Collecting pymilvus

[2021-04-21T04:53:33.914Z]   Downloading https://test-files.pythonhosted.org/packages/14/3a/bbb9ee0a6361305b292b97f5dc9669f58ab3643fae1f1007c0e9d4c26e17/pymilvus-1.0.1.dev21-py3-none-any.whl (56kB)

[2021-04-21T04:53:33.914Z] Collecting ujson>=2.0.0 (from pymilvus)

[2021-04-21T04:53:34.868Z]   Downloading https://test-files.pythonhosted.org/packages/8d/54/2a618356e54282e3f4fa0745cbddeed104ed5ff2930c98f2d9dfa9677af8/ujson-4.0.2-cp36-cp36m-manylinux1_x86_64.whl (179kB)

[2021-04-21T04:53:35.826Z] Collecting grpcio-tools>=1.22.0 (from pymilvus)

[2021-04-21T04:53:35.827Z]   ERROR: Could not find a version that satisfies the requirement grpcio-tools>=1.22.0 (from pymilvus) (from versions: 1.16.1)
```

**Comment by scsven** [comment]
@del-zhenwu The requirements of pymilvus published in PyPI, not PyPI Test, so that the installation failed.
Please install the requirements defined in setup.py before install pymilvus.
