### ISSUE TITLE
mishards UNAVAILABLE: io exception

### ISSUE THREAD

**Issue by JNero** [milvus-io/milvus#5040]
根据官网1.0版本用k8s+helm搭建mishards，milvus读写结点各一个(读写结点用docker logs 查看，都已经启动成功)。搭建成功后用java sdk连接报错

![image](https://user-images.githubusercontent.com/9392133/115989785-9f681800-a5f2-11eb-94ba-0b9f46fd5857.png)

`[text-format]11:15:28 155 ERROR (io.milvus.client.AbstractMilvusGrpcClient:1398) - Command RPC failed:
Status{code=UNAVAILABLE, description=io exception, cause=io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:19530
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.grpc.netty.shaded.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
}
io.milvus.client.exception.InitializationException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
`

**Comment by yhmo** [comment]
看起来是连接的IP不对，“172.0.0.1”， 你确定mishard的服务是在这个地址么？

**Comment by JNero** [comment]
在本地启动的

**Comment by JNero** [comment]
> 看起来是连接的IP不对，“172.0.0.1”， 你确定mishard的服务是在这个地址么？

在本地启动的

**Comment by JNero** [comment]
> 看起来是连接的IP不对，“172.0.0.1”， 你确定mishard的服务是在这个地址么？

是写错了127.0.0.1也不行

**Comment by yhmo** [comment]
参考过这里么？ https://github.com/milvus-io/milvus-helm

**Comment by JNero** [comment]
> 参考过这里么？ https://github.com/milvus-io/milvus-helm

第二天自动好了， 没有人做过变更，不知道为什么。
