### ISSUE TITLE
QueryNode crashed during frequently release/load/query

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#5053]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
2021-04-26 15:56:32,506 - milvus_benchmark.main:83 - DEBUG - Get runner
2021-04-26 15:56:32,506 - apscheduler.scheduler:632 - INFO - Removed job 75879207936f4693ab19c9bd7793d10f
2021-04-26 15:56:32,507 - apscheduler.scheduler:1021 - DEBUG - No jobs; waiting until a job is added
2021-04-26 15:56:45,450 - milvus_benchmark.runners.accuracy:146 - DEBUG - Building index with param: {"nlist": 1024}
2021-04-26 15:56:49,584 - milvus_benchmark.runners.utils:252 - INFO - Set normalize for metric_type: ip
2021-04-26 15:56:49,625 - milvus_benchmark.runners.utils:252 - INFO - Set normalize for metric_type: ip
2021-04-26 15:56:49,635 - milvus_benchmark.main:87 - INFO - Prepare to run cases
2021-04-26 15:56:49,642 - milvus_benchmark.client:251 - INFO - {'index_type': 'IVF_FLAT', 'metric_type': 'IP', 'params': {'nlist': 1024}}
2021-04-26 15:56:49,642 - milvus_benchmark.runners.accuracy:244 - INFO - {'index_type': 'ivf_flat', 'metric_type': 'IP', 'index_param': {'nlist': 1024}}
2021-04-26 15:56:49,642 - milvus_benchmark.runners.accuracy:245 - INFO - Start load collection: glove_200_angular

Addr [192.168.1.241:19530] release_collection
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1619423810.025902746","description":"Error received from peer ipv4:192.168.1.241:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Socket closed","grpc_status":14}"
>
	{'API start': '2021-04-26 15:56:49.642618', 'RPC start': '2021-04-26 15:56:49.642635', 'RPC error': '2021-04-26 15:56:50.026558'}
2021-04-26 15:56:50,026 - milvus.client.grpc_handler:71 - ERROR - 
Addr [192.168.1.241:19530] release_collection
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1619423810.025902746","description":"Error received from peer ipv4:192.168.1.241:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Socket closed","grpc_status":14}"
>
	{'API start': '2021-04-26 15:56:49.642618', 'RPC start': '2021-04-26 15:56:49.642635', 'RPC error': '2021-04-26 15:56:50.026558'}
2021-04-26 15:56:50,027 - milvus_benchmark.main:113 - ERROR - <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1619423810.025902746","description":"Error received from peer ipv4:192.168.1.241:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Socket closed","grpc_status":14}"
>
2021-04-26 15:56:50,031 - milvus_benchmark.main:114 - ERROR - Traceback (most recent call last):
  File "main.py", line 88, in run_suite
    runner.prepare(**cases[0])
  File "/home/zw/tmp/milvus_benchmark/milvus_benchmark/runners/accuracy.py", line 246, in prepare
    self.milvus.release_collection()
  File "/home/zw/tmp/milvus_benchmark/milvus_benchmark/client.py", line 46, in wrapper
    result = func(*args, **kwargs)
  File "/home/zw/tmp/milvus_benchmark/milvus_benchmark/client.py", line 421, in release_collection
    return self._milvus.release_collection(collection_name, timeout=3000)
  File "/usr/local/lib/python3.6/dist-packages/milvus/client/stub.py", line 39, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/milvus/client/stub.py", line 315, in release_collection
    return handler.release_collection(db_name="", collection_name=collection_name, timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/milvus/client/grpc_handler.py", line 72, in handler
    raise e
  File "/usr/local/lib/python3.6/dist-packages/milvus/client/grpc_handler.py", line 53, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/milvus/client/grpc_handler.py", line 882, in release_collection
    response = rf.result()
  File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 722, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1619423810.025902746","description":"Error received from peer ipv4:192.168.1.241:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Socket closed","grpc_status":14}"
>

2021-04-26 15:56:50,032 - apscheduler.executors.default:144 - INFO - Job "run_suite (trigger: date[2021-04-26 15:56:32 CST], next run at: 2021-04-26 15:56:32 CST)" executed successfully

```
```
[2021/04/26 07:56:41.436 +00:00] [DEBUG] [search_collection.go:218] ["get tSafe from flow graph"] [collectionID=424521574191140161] [tSafe=424522232996102144]
[2021/04/26 07:56:41.436 +00:00] [DEBUG] [timesync.go:179] ["receive tt msg"]
[2021/04/26 07:56:41.462 +00:00] [DEBUG] [segment.go:224] ["do search on segment"] [segmentID=424521743745941505] [segmentType=3]
[2021/04/26 07:56:41.568 +00:00] [DEBUG] [impl.go:1282] [RegisterLink] [role=ProxyNode-1] ["state code of proxynode"=Healthy]
[2021/04/26 07:56:41.635 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65535] [remainReqCnt=0]
[2021/04/26 07:56:41.835 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65534] [remainReqCnt=0]
[2021/04/26 07:56:42.035 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65533] [remainReqCnt=0]
[2021/04/26 07:56:42.235 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65532] [remainReqCnt=0]
[2021/04/26 07:56:42.435 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=0] [total=65531] [remainReqCnt=0]
[2021/04/26 07:56:42.435 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=0] [total=65536] [remainReqCnt=0]
[2021/04/26 07:56:42.435 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65536] [remainReqCnt=0]
[2021/04/26 07:56:42.436 +00:00] [DEBUG] [timetick.go:66] [proxyservice] ["msg type"=TimeTick]
[2021/04/26 07:56:42.436 +00:00] [DEBUG] [search_collection.go:211] ["querynode::doUnsolvedMsgSearch: setServiceableTime"] [serviceTime=424522233258246144]
[2021/04/26 07:56:42.436 +00:00] [DEBUG] [search_collection.go:218] ["get tSafe from flow graph"] [collectionID=424521574191140161] [tSafe=424522233258246144]
[2021/04/26 07:56:42.436 +00:00] [DEBUG] [timesync.go:179] ["receive tt msg"]
[2021/04/26 07:56:42.573 +00:00] [DEBUG] [impl.go:1282] [RegisterLink] [role=ProxyNode-1] ["state code of proxynode"=Healthy]
[2021/04/26 07:56:42.635 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65535] [remainReqCnt=0]
[2021/04/26 07:56:42.835 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65534] [remainReqCnt=0]
[2021/04/26 07:56:43.035 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65533] [remainReqCnt=0]
[2021/04/26 07:56:43.239 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65532] [remainReqCnt=0]
[2021/04/26 07:56:43.435 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=0] [total=65531] [remainReqCnt=0]
[2021/04/26 07:56:43.435 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=0] [total=65536] [remainReqCnt=0]
[2021/04/26 07:56:43.435 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65536] [remainReqCnt=0]
[2021/04/26 07:56:43.436 +00:00] [DEBUG] [timetick.go:66] [proxyservice] ["msg type"=TimeTick]
[2021/04/26 07:56:43.436 +00:00] [DEBUG] [search_collection.go:211] ["querynode::doUnsolvedMsgSearch: setServiceableTime"] [serviceTime=424522233520390144]
[2021/04/26 07:56:43.436 +00:00] [DEBUG] [search_collection.go:218] ["get tSafe from flow graph"] [collectionID=424521574191140161] [tSafe=424522233520390144]
[2021/04/26 07:56:43.436 +00:00] [DEBUG] [timesync.go:179] ["receive tt msg"]
[2021/04/26 07:56:43.635 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65535] [remainReqCnt=0]
[2021/04/26 07:56:43.839 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65534] [remainReqCnt=0]
[2021/04/26 07:56:44.035 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65533] [remainReqCnt=0]
[2021/04/26 07:56:44.261 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65532] [remainReqCnt=0]
[2021/04/26 07:56:44.437 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65531] [remainReqCnt=0]
[2021/04/26 07:56:44.437 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=0] [total=65530] [remainReqCnt=0]
[2021/04/26 07:56:44.438 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=0] [total=65536] [remainReqCnt=0]
[2021/04/26 07:56:44.635 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65536] [remainReqCnt=0]
[2021/04/26 07:56:44.635 +00:00] [DEBUG] [timetick.go:66] [proxyservice] ["msg type"=TimeTick]
[2021/04/26 07:56:44.636 +00:00] [DEBUG] [search_collection.go:211] ["querynode::doUnsolvedMsgSearch: setServiceableTime"] [serviceTime=424522233782534144]
[2021/04/26 07:56:44.636 +00:00] [DEBUG] [search_collection.go:218] ["get tSafe from flow graph"] [collectionID=424521574191140161] [tSafe=424522233782534144]
[2021/04/26 07:56:44.636 +00:00] [DEBUG] [timesync.go:179] ["receive tt msg"]
[2021/04/26 07:56:44.836 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65535] [remainReqCnt=0]
[2021/04/26 07:56:44.936 +00:00] [DEBUG] [meta_table.go:195] ["IndexService get mark deleted meta"]
[2021/04/26 07:56:45.035 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65534] [remainReqCnt=0]
[2021/04/26 07:56:45.236 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65533] [remainReqCnt=0]
[2021/04/26 07:56:45.435 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65532] [remainReqCnt=0]
[2021/04/26 07:56:45.435 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=0] [total=65531] [remainReqCnt=0]
[2021/04/26 07:56:45.437 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=0] [total=65536] [remainReqCnt=0]
[2021/04/26 07:56:45.639 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65536] [remainReqCnt=0]
[2021/04/26 07:56:45.639 +00:00] [DEBUG] [timetick.go:66] [proxyservice] ["msg type"=TimeTick]
[2021/04/26 07:56:45.639 +00:00] [DEBUG] [search_collection.go:211] ["querynode::doUnsolvedMsgSearch: setServiceableTime"] [serviceTime=424522234045464576]
[2021/04/26 07:56:45.640 +00:00] [DEBUG] [search_collection.go:218] ["get tSafe from flow graph"] [collectionID=424521574191140161] [tSafe=424522234045464576]
[2021/04/26 07:56:45.640 +00:00] [DEBUG] [timesync.go:179] ["receive tt msg"]
[2021/04/26 07:56:45.835 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65535] [remainReqCnt=0]
[2021/04/26 07:56:46.036 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65534] [remainReqCnt=0]
[2021/04/26 07:56:46.235 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65533] [remainReqCnt=0]
[2021/04/26 07:56:46.437 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=0] [total=65532] [remainReqCnt=0]
[2021/04/26 07:56:46.437 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=0] [total=65536] [remainReqCnt=0]
[2021/04/26 07:56:46.437 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65536] [remainReqCnt=0]
[2021/04/26 07:56:46.438 +00:00] [DEBUG] [timetick.go:66] [proxyservice] ["msg type"=TimeTick]
[2021/04/26 07:56:46.438 +00:00] [DEBUG] [search_collection.go:211] ["querynode::doUnsolvedMsgSearch: setServiceableTime"] [serviceTime=424522234307870720]
[2021/04/26 07:56:46.438 +00:00] [DEBUG] [search_collection.go:218] ["get tSafe from flow graph"] [collectionID=424521574191140161] [tSafe=424522234307870720]
[2021/04/26 07:56:46.438 +00:00] [DEBUG] [timesync.go:179] ["receive tt msg"]
[2021/04/26 07:56:46.635 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65535] [remainReqCnt=0]
[2021/04/26 07:56:46.835 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65534] [remainReqCnt=0]
[2021/04/26 07:56:47.035 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65533] [remainReqCnt=0]
[2021/04/26 07:56:47.235 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65532] [remainReqCnt=0]
[2021/04/26 07:56:47.435 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=0] [total=65531] [remainReqCnt=0]
[2021/04/26 07:56:47.435 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=0] [total=65536] [remainReqCnt=0]
[2021/04/26 07:56:47.435 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65536] [remainReqCnt=0]
[2021/04/26 07:56:47.436 +00:00] [DEBUG] [timetick.go:66] [proxyservice] ["msg type"=TimeTick]
[2021/04/26 07:56:47.436 +00:00] [DEBUG] [search_collection.go:211] ["querynode::doUnsolvedMsgSearch: setServiceableTime"] [serviceTime=424522234568966144]
[2021/04/26 07:56:47.436 +00:00] [DEBUG] [search_collection.go:218] ["get tSafe from flow graph"] [collectionID=424521574191140161] [tSafe=424522234568966144]
[2021/04/26 07:56:47.436 +00:00] [DEBUG] [timesync.go:179] ["receive tt msg"]
[2021/04/26 07:56:47.635 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65535] [remainReqCnt=0]
[2021/04/26 07:56:47.836 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65534] [remainReqCnt=0]
[2021/04/26 07:56:48.035 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65533] [remainReqCnt=0]
[2021/04/26 07:56:48.235 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65532] [remainReqCnt=0]
[2021/04/26 07:56:48.435 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=0] [total=65531] [remainReqCnt=0]
[2021/04/26 07:56:48.435 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=0] [total=65536] [remainReqCnt=0]
[2021/04/26 07:56:48.435 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65536] [remainReqCnt=0]
[2021/04/26 07:56:48.436 +00:00] [DEBUG] [timetick.go:66] [proxyservice] ["msg type"=TimeTick]
[2021/04/26 07:56:48.436 +00:00] [DEBUG] [search_collection.go:211] ["querynode::doUnsolvedMsgSearch: setServiceableTime"] [serviceTime=424522234831110144]
[2021/04/26 07:56:48.436 +00:00] [DEBUG] [search_collection.go:218] ["get tSafe from flow graph"] [collectionID=424521574191140161] [tSafe=424522234831110144]
[2021/04/26 07:56:48.436 +00:00] [DEBUG] [timesync.go:179] ["receive tt msg"]
[2021/04/26 07:56:48.635 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65535] [remainReqCnt=0]
[2021/04/26 07:56:48.836 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65534] [remainReqCnt=0]
[2021/04/26 07:56:49.037 +00:00] [DEBUG] [timestamp.go:105] ["TimestampAllocator pickCanDoFunc"] [need=1] [total=65533] [remainReqCnt=0]
command terminated with exit code 137
```
```
close inputChannel
close inputChannel
close inputChannel
2021-04-26 07:53:43.230298 I | clock offset{jet-lag 8 322789573  <nil>} {prev-physical 16 1619423622907490560  UTC} {now 16 1619423623230280133  UTC}
2021-04-26 07:53:43.230313 I | clock offset{jet-lag 8 322817891  <nil>} {prev-physical 16 1619423622907492976  UTC} {now 16 1619423623230310867  UTC}
2021-04-26 07:53:46,094 DEBUG [default] [user@load-milvus-ha-standalone-75f9987bdb-m6pj5] [virtual void milvus::knowhere::IVF_NM::QueryImpl(int64_t, const float*, int64_t, float*, int64_t*, const Config&, faiss::BitsetView)] [..ent/workspace/internal/core/src/index/knowhere/knowhere/index/vector_offset_index/IndexIVF_NM.cpp:349] [KNOWHERE][QueryImpl][singlenode] IVF_NM search cost: 327246, quantization cost: 123.537, data search cost: 203.705
2021-04-26 07:53:46,212 DEBUG [default] [user@load-milvus-ha-standalone-75f9987bdb-m6pj5] [virtual void milvus::knowhere::IVF_NM::QueryImpl(int64_t, const float*, int64_t, float*, int64_t*, const Config&, faiss::BitsetView)] [..ent/workspace/internal/core/src/index/knowhere/knowhere/index/vector_offset_index/IndexIVF_NM.cpp:349] [KNOWHERE][QueryImpl][singlenode] IVF_NM search cost: 117524, quantization cost: 86.22, data search cost: 31.2991
2021-04-26 07:53:46,460 DEBUG [default] [user@load-milvus-ha-standalone-75f9987bdb-m6pj5] [virtual void milvus::knowhere::IVF_NM::QueryImpl(int64_t, const float*, int64_t, float*, int64_t*, const Config&, faiss::BitsetView)] [..ent/workspace/internal/core/src/index/knowhere/knowhere/index/vector_offset_index/IndexIVF_NM.cpp:349] [KNOWHERE][QueryImpl][singlenode] IVF_NM search cost: 247678, quantization cost: 86.7729, data search cost: 160.9
2021-04-26 07:53:46,570 DEBUG [default] [user@load-milvus-ha-standalone-75f9987bdb-m6pj5] [virtual void milvus::knowhere::IVF_NM::QueryImpl(int64_t, const float*, int64_t, float*, int64_t*, const Config&, faiss::BitsetView)] [..ent/workspace/internal/core/src/index/knowhere/knowhere/index/vector_offset_index/IndexIVF_NM.cpp:349] [KNOWHERE][QueryImpl][singlenode] IVF_NM search cost: 109847, quantization cost: 78.9351, data search cost: 30.906
[true true true true]
2021-04-26 07:54:37.409213 I | clock offset{jet-lag 8 151696519  <nil>} {prev-physical 16 1619423677257481162  UTC} {now 16 1619423677409177681  UTC}
2021-04-26 07:54:37.410795 I | clock offset{jet-lag 8 153271950  <nil>} {prev-physical 16 1619423677257488877  UTC} {now 16 1619423677410760827  UTC}
2021-04-26 07:54:51.975835 I | clock offset{jet-lag 8 189854078  <nil>} {prev-physical 16 1619423691785951247  UTC} {now 16 1619423691975805325  UTC}
2021-04-26 07:54:51.975900 I | clock offset{jet-lag 8 166341096  <nil>} {prev-physical 16 1619423691809551282  UTC} {now 16 1619423691975892378  UTC}
2021-04-26 07:54:51.975911 I | clock offset{jet-lag 8 166350012  <nil>} {prev-physical 16 1619423691809557632  UTC} {now 16 1619423691975907644  UTC}
2021-04-26 07:54:59,948 DEBUG [default] [user@load-milvus-ha-standalone-75f9987bdb-m6pj5] [virtual void milvus::knowhere::IVF_NM::QueryImpl(int64_t, const float*, int64_t, float*, int64_t*, const Config&, faiss::BitsetView)] [..ent/workspace/internal/core/src/index/knowhere/knowhere/index/vector_offset_index/IndexIVF_NM.cpp:349] [KNOWHERE][QueryImpl][singlenode] IVF_NM search cost: 7.07466e+07, quantization cost: 246.85, data search cost: 70827
2021-04-26 07:55:18,013 DEBUG [default] [user@load-milvus-ha-standalone-75f9987bdb-m6pj5] [virtual void milvus::knowhere::IVF_NM::QueryImpl(int64_t, const float*, int64_t, float*, int64_t*, const Config&, faiss::BitsetView)] [..ent/workspace/internal/core/src/index/knowhere/knowhere/index/vector_offset_index/IndexIVF_NM.cpp:349] [KNOWHERE][QueryImpl][singlenode] IVF_NM search cost: 1.80649e+07, quantization cost: 860.681, data search cost: 17321.8
2021-04-26 07:55:41.877435 I | clock offset{jet-lag 8 317919501  <nil>} {prev-physical 16 1619423741559486769  UTC} {now 16 1619423741877406270  UTC}
2021-04-26 07:55:41.877903 I | clock offset{jet-lag 8 318397904  <nil>} {prev-physical 16 1619423741559491233  UTC} {now 16 1619423741877889137  UTC}
2021-04-26 07:55:41.878097 I | clock offset{jet-lag 8 286600989  <nil>} {prev-physical 16 1619423741591483111  UTC} {now 16 1619423741878084100  UTC}
2021-04-26 07:56:41,461 DEBUG [default] [user@load-milvus-ha-standalone-75f9987bdb-m6pj5] [virtual void milvus::knowhere::IVF_NM::QueryImpl(int64_t, const float*, int64_t, float*, int64_t*, const Config&, faiss::BitsetView)] [..ent/workspace/internal/core/src/index/knowhere/knowhere/index/vector_offset_index/IndexIVF_NM.cpp:349] [KNOWHERE][QueryImpl][singlenode] IVF_NM search cost: 8.34474e+07, quantization cost: 383.414, data search cost: 83311.7
close inputChannel
close inputChannel
close inputChannel

```
**Steps/Code to reproduce behavior**

1. create collection
2. insert `glove_200_IP` (2,000,000-200d)
2. create index ivf_flat, nlist:  1024
3. load/search
4. load/release

checkout `argo` branch on `https://github.com/zilliztech/milvus_benchmark`
**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by yanliang567** [comment]
try to repro against new build

**Comment by del-zhenwu** [comment]
test yaml:
```
locust_random_performance:
  collections:
    -
      milvus:
        cache_config.insert_buffer_size: 2GB
        engine_config.use_blas_threshold: 1100
        wal_enable: true
      collection_name: local_50w_128_l2
      # other_fields: int
      ni_per: 50000
      build_index: true
      index_type: ivf_sq8
      index_param:
        nlist: 1024
      task:
        types:
          -
            type: query
            weight: 1
            params:
              top_k: 10
              nq: 100
              search_param:
                nprobe: 16
           # -
           #   type: insert
           #   weight: 20
           #   params:
           #     ni_per: 1
          -
            type: load
            weight: 1
          -
            type: release
            weight: 1
        connection_num: 1
        clients_num: 20
        spawn_rate: 2
        during_time: 600
```

**Comment by bigsheeper** [comment]
hard to reproduce

**Comment by xige-16** [comment]
we can't reproduce the issue, please provide the querynode's log file after fail or crash. @del-zhenwu @yanliang567

**Comment by xiaofan-luan** [comment]
@yanliang567 shall we close this issue since it is not reproducible?

**Comment by yanliang567** [comment]
@del-zhenwu  does this repro recently on latest build? if not, lets close it.
