### ISSUE TITLE
Datanode pod start failed

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#5242]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
open pid file: /run/milvus/datanode.pid
lock pid file
[2021/05/17 03:51:50.523 +00:00] [INFO] [param_table.go:64] [DataNode] [port=41774]
[2021/05/17 03:51:50.525 +00:00] [DEBUG] [service.go:170] ["DataNode address"] [address=10.97.7.5:41774]
[2021/05/17 03:51:50.626 +00:00] [DEBUG] [service.go:179] ["Master service address"] [address=benchmark-test-loop-jz4vd-5-milvus-ha-master:53100]
[2021/05/17 03:51:50.626 +00:00] [DEBUG] [service.go:180] ["Init master service client ..."]
[2021/05/17 03:51:50.626 +00:00] [INFO] [logger.go:48] ["parsed scheme: \"\""]
[2021/05/17 03:51:50.626 +00:00] [INFO] [logger.go:48] ["scheme \"\" not registered, fallback to default scheme"]
[2021/05/17 03:51:50.626 +00:00] [INFO] [logger.go:48] ["ccResolverWrapper: sending update to cc: {[{benchmark-test-loop-jz4vd-5-milvus-ha-master:53100  <nil> 0 <nil>}] <nil> <nil>}"]
[2021/05/17 03:51:50.626 +00:00] [INFO] [logger.go:48] ["ClientConn switching balancer to \"pick_first\""]
[2021/05/17 03:51:50.626 +00:00] [INFO] [logger.go:48] ["pickfirstBalancer: HandleSubConnStateChange: 0xc000116170, {CONNECTING <nil>}"]
[2021/05/17 03:51:50.628 +00:00] [INFO] [logger.go:48] ["pickfirstBalancer: HandleSubConnStateChange: 0xc000116170, {READY <nil>}"]
[2021/05/17 03:51:50.630 +00:00] [DEBUG] [service.go:202] ["Data service address"] [address=benchmark-test-loop-jz4vd-5-milvus-ha-dataservice:13333]
[2021/05/17 03:51:50.630 +00:00] [DEBUG] [service.go:203] ["DataNode Init data service client ..."]
[2021/05/17 03:51:50.630 +00:00] [DEBUG] [client.go:48] ["dataservice connect "] [address=benchmark-test-loop-jz4vd-5-milvus-ha-dataservice:13333]
[2021/05/17 03:51:50.630 +00:00] [INFO] [logger.go:48] ["parsed scheme: \"\""]
[2021/05/17 03:51:50.630 +00:00] [INFO] [logger.go:48] ["scheme \"\" not registered, fallback to default scheme"]
[2021/05/17 03:51:50.630 +00:00] [INFO] [logger.go:48] ["ccResolverWrapper: sending update to cc: {[{benchmark-test-loop-jz4vd-5-milvus-ha-dataservice:13333  <nil> 0 <nil>}] <nil> <nil>}"]
[2021/05/17 03:51:50.630 +00:00] [INFO] [logger.go:48] ["ClientConn switching balancer to \"pick_first\""]
[2021/05/17 03:51:50.631 +00:00] [INFO] [logger.go:48] ["pickfirstBalancer: HandleSubConnStateChange: 0xc000025c30, {CONNECTING <nil>}"]
[2021/05/17 03:51:50.632 +00:00] [INFO] [logger.go:48] ["pickfirstBalancer: HandleSubConnStateChange: 0xc000025c30, {READY <nil>}"]
[2021/05/17 03:51:50.633 +00:00] [INFO] [logger.go:48] ["parsed scheme: \"endpoint\""]
[2021/05/17 03:51:50.633 +00:00] [INFO] [logger.go:48] ["ccResolverWrapper: sending new addresses to cc: [{benchmark-test-loop-jz4vd-5-etcd:2379  <nil> 0 <nil>}]"]
[2021/05/17 03:51:50.641 +00:00] [WARN] [service.go:224] ["datanode init error: "] [error="Receive error when registering data node, msg: peer 1 already exist"]
panic: Receive error when registering data node, msg: peer 1 already exist

goroutine 41 [running]:
github.com/milvus-io/milvus/cmd/distributed/components.(*DataNode).Run(0xc000287920, 0xc0000a5e00, 0x23b0b20)
	/go/src/github.com/milvus-io/milvus/cmd/distributed/components/data_node.go:41 +0x95
github.com/milvus-io/milvus/cmd/distributed/roles.(*MilvusRoles).Run.func7(0x23b0100, 0x23b01a0, 0xc0000a5e00, 0xc0004966c0)
	/go/src/github.com/milvus-io/milvus/cmd/distributed/roles/roles.go:222 +0xce
created by github.com/milvus-io/milvus/cmd/distributed/roles.(*MilvusRoles).Run
	/go/src/github.com/milvus-io/milvus/cmd/distributed/roles/roles.go:211 +0x55e
```
**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by XuanYang-cn** [comment]
This could happen if DataNode is crashed and restarted. I'll look into it.

**Comment by XuanYang-cn** [comment]
The corresponding code has been changed, I don't think this is a problem anymore.

Please close this issue if not reproducing. @del-zhenwu
