### ISSUE TITLE
Could not connect to Milvus Client using Java API

### ISSUE THREAD

**Issue by pradeepharbour** [milvus-io/milvus#5380]
**Please state your issue using the following template and, most importantly, in English.**

**Is your feature request related to a problem? Please describe.**

I am trying to acquire connection to milvus client using Java API. But it's throwing an exception. Please find the exception trace below.

**Describe the solution you'd like**

I want the connection to be established.

**Describe alternatives you've considered**

As an alternative I am currently using Milvus Rest API's

**Additional context**

> Code used to connect

`ConnectParam connectParam = new ConnectParam.Builder().withHost(milvusHost).withPort(milvusPort).build();`

> Exception Trace

`2021-05-25 00:00:39.360 ERROR 53377 --- [           main] i.m.client.AbstractMilvusGrpcClient      : Command RPC failed:
Status{code=INTERNAL, description=http2 exception, cause=io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:103)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.verifyFirstFrameIsSettings(Http2ConnectionHandler.java:338)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:239)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437)
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by yhmo** [comment]
The  java sdk version and milvus server version is?

**Comment by pradeepharbour** [comment]
Hi,

   I did some research on the issue and found [this](https://github.com/grpc/grpc-java/issues/2905) Milvus API is expecting a http2 server but milvus server is running with http1. 

I just followed your [documentation](https://milvus.io/docs/v1.1.0/milvus_docker-cpu.md) to setup milvus server. Can you guys suggest if I can configure anything on the server to get myself started with your API. I haven't found anything in your documentation related to this. Please suggest.

**Comment by yhmo** [comment]
Milvus server use oatpp to provide http service, currently the oatpp **not** yet support http2.0: https://github.com/oatpp/oatpp/issues/116

Milvus server expose two ports: 19530 and 19121(default), 19530 is for grpc, 19121 if for restful api. All milvus sdk are base on grpc(grpc is base on http2).
So, you should use java sdk to connect the port 19530, not 19121.

**Comment by pradeepharbour** [comment]
> Milvus server use oatpp to provide http service, currently the oatpp **not** yet support http2.0: [oatpp/oatpp#116](https://github.com/oatpp/oatpp/issues/116)
> 
> Milvus server expose two ports: 19530 and 19121(default), 19530 is for grpc, 19121 if for restful api. All milvus sdk are base on grpc(grpc is base on http2).
> So, you should use java sdk to connect the port 19530, not 19121.
> 
> There is an example for java sdk in /milvus-sdk-java/examples/src/main/java/MilvusClientExample.java, in this example, you can see it connect to port 19530. If the milvus server successfully started, you can run this example to interact with milvus server.

Thanks a lot, this worked. This has to be added in milvus-sdk-java readme doc.
