### ISSUE TITLE
Support auto compaction retention on etcd.

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#5519]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
The etcd space will be exceeded soon after several days running

```
7d955ef11d/load-3-etcd:2379","attempt":0,"error":"rpc error: code = ResourceExhausted desc = etcdserver: mvcc: database space exceeded"}
2021-06-01 02:39:31.309997 I | retry func error: etcdserver: mvcc: database space exceeded. attempts #1 after 1s.
{"level":"warn","ts":"2021-06-01T02:39:32.237Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-aed4564f-4618-492a-8ace-e87654538daf/load-3-etcd:2379","attempt":0,"error":"rpc error: code = ResourceExhausted desc = etcdserver: mvcc: database space exceeded"}
panic: etcdserver: mvcc: database space exceeded

goroutine 55 [running]:
github.com/milvus-io/milvus/internal/util/sessionutil.(*Session).Init(0xc0002e0000, 0x22a2683, 0xc, 0xc00039cc90, 0xf, 0x1, 0x1)
	/go/src/github.com/milvus-io/milvus/internal/util/sessionutil/session_util.go:90 +0x153
github.com/milvus-io/milvus/internal/indexservice.(*IndexService).Register(0xc00036e2a0, 0xd, 0x0)
	/go/src/github.com/milvus-io/milvus/internal/indexservice/indexservice.go:101 +0xfb
github.com/milvus-io/milvus/internal/distributed/indexservice.(*Server).init(0xc00011e050, 0x0, 0xc00015c3c0)
	/go/src/github.com/milvus-io/milvus/internal/distributed/indexservice/service.go:75 +0xc5
github.com/milvus-io/milvus/internal/distributed/indexservice.(*Server).Run(0xc00011e050, 0xc0005a3ac0, 0xc00015c3c0)
	/go/src/github.com/milvus-io/milvus/internal/distributed/indexservice/service.go:56 +0x2f
github.com/milvus-io/milvus/cmd/distributed/components.(*IndexService).Run(...)
	/go/src/github.com/milvus-io/milvus/cmd/distributed/components/index_service.go:36
github.com/milvus-io/milvus/cmd/distributed/roles.(*MilvusRoles).Run.func8(0x2468200, 0xc0005a3ac0, 0xc00059e808)
	/go/src/github.com/milvus-io/milvus/cmd/distributed/roles/roles.go:258 +0xb2
created by github.com/milvus-io/milvus/cmd/distributed/roles.(*MilvusRoles).Run
	/go/src/github.com/milvus-io/milvus/cmd/distributed/roles/roles.go:248 +0x493

```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by yanliang567** [comment]
I think we need a solution to rotate the archives.

**Comment by del-zhenwu** [comment]
User may be confused that server can not use after a few hundred collections operated

**Comment by czs007** [comment]
@neza2017

**Comment by yanliang567** [comment]
related to #6753

**Comment by yanliang567** [comment]
is it done now? @LoveEachDay

**Comment by LoveEachDay** [comment]
We've enabled auto compaction for etcd in docker-compose and helm charts.
