### ISSUE TITLE
Error with 'NoneType' object has no attribute 'count_entities' images in this set

### ISSUE THREAD

**Issue by limengyang1992** [milvus-io/milvus#5529]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**
![image](https://user-images.githubusercontent.com/73928007/120298273-87279f00-c2fc-11eb-9987-e3b0c26f4bf2.png)

**Additional context**

**Comment by yhmo** [comment]
Hi @shiyu22 

Could you help investigate this issue?

**Comment by shiyu22** [comment]
My pleasure :)

 @limengyang1992 , you need to check the version of Milvus with [this Bootcamp](https://github.com/milvus-io/bootcamp/tree/master/solutions/image_similarity_search/quick_deploy), and you can also follow [this issue](https://github.com/milvus-io/bootcamp/issues/478).

**Comment by yhmo** [comment]
It is caused by in-compatible version of milvus server. Inactive and close.

**Comment by why20000101** [comment]
my bug：
 'NoneType' object has no attribute 'count_entities' images in this set 
![image](https://user-images.githubusercontent.com/83963866/141277595-cb88aed6-5379-4bd0-9bac-aaaa91a7cead.png)
Check my logs：
Request timeout: 
2021-11-11 09:27:33,212 - root - ERROR - Cannot check server version: Request timeout
2021-11-11 09:27:33,212 - root - ERROR - 'NoneType' object has no attribute 'drop_collection'
2021-11-11 09:27:33,213 - werkzeug - INFO - 115.236.14.158 - - [11/Nov/2021 09:27:33] "POST /api/v1/delete HTTP/1.1" 200 -
2021-11-11 09:27:46,340 - werkzeug - INFO - 115.236.14.158 - - [11/Nov/2021 09:27:46] "OPTIONS /api/v1/train HTTP/1.1" 200 -
2021-11-11 09:27:46,366 - werkzeug - INFO - 115.236.14.158 - - [11/Nov/2021 09:27:46] "POST /api/v1/train HTTP/1.1" 200 -
2021-11-11 09:27:47,407 - app - ERROR - Exception on /api/v1/process [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 105, in thread_status_api
    return "current: {}, total: {}".format(cache['current'], cache['total'])
  File "/usr/local/lib/python3.6/dist-packages/diskcache/core.py", line 1262, in __getitem__
    raise KeyError(key)
KeyError: 'current'
2021-11-11 09:27:47,409 - werkzeug - INFO - 115.236.14.158 - - [11/Nov/2021 09:27:47] "GET /api/v1/process HTTP/1.1" 500 -
2021-11-11 09:27:47,457 - root - ERROR - [Errno 2] No such file or directory: ''
