### ISSUE TITLE
Assert occurs when using partition search

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#5581]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Assert occurs when using partition search: (the partition name was parsed wrong)
Error: <BaseException: (code=1, message=PartitonName: t not found)>

**Steps/Code to reproduce behavior**
Steps:
1 create connection and collection, successfully
2 create partiton, successfully
3 search, fail with assert

Code:
from pymilvus_orm import CollectionSchema, FieldSchema
from pymilvus_orm import Collection
from pymilvus_orm import connections
from pymilvus_orm.types import DataType
from pymilvus_orm import Partition

int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primaty=True)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=128)
schema = CollectionSchema(fields=[int64_field, float_field, float_vector])
connections.connect(host="172.18.255.155", port="19530")
import numpy as np
collection = Collection("test_search_collection_binbin_6", schema=schema)
partition = Partition(collection, "test_partition")
dim = 128
nb = 500
nq = 1
limit = 1000
import random
default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
partition.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")

Assert trace stack:
>>> partition.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
Error: <BaseException: (code=1, message=PartitonName: t not found)>
Error: <BaseException: (code=1, message=PartitonName: t not found)>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pymilvus_orm/partition.py", line 263, in search
    expr, self._name, output_fields, timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 39, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 1024, in search_with_expression
    return handler.search_with_expression(collection_name, data, anns_field, param, limit, expression, partition_names, output_fields, timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 62, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 54, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 91, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 710, in search_with_expression
    return self._execute_search_requests(requests, timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 62, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 54, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 680, in _execute_search_requests
    raise pre_err
  File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 671, in _execute_search_requests
    raise BaseException(response.status.error_code, response.status.reason)
milvus.client.exceptions.BaseException: <BaseException: (code=1, message=PartitonName: t not found)>

**Expected behavior**
Search without assert

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
milvus: master
pymilvus:
Name: pymilvus
Version: 2.0a1.dev8
pymilvus-orm
Name: pymilvus-orm
Version: 2.0a1.dev13

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by binbinlv** [comment]
the issue still exist in the latest version:
Name: pymilvus
Version: 2.0a1.dev22
Name: pymilvus-orm
Version: 2.0a1.dev15

**Comment by binbinlv** [comment]
Verified in the latest version, it has been fixed.
Name: pymilvus
Version: 2.0a1.dev27
Name: pymilvus-orm
Version: 2.0a1.dev19

>>> from pymilvus_orm import CollectionSchema, FieldSchema
>>> from pymilvus_orm import Collection
>>> from pymilvus_orm import connections
>>> from pymilvus_orm.types import DataType
>>> from pymilvus_orm import Partition
>>> int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primaty=True)
>>> float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
>>> float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=128)
>>> schema = CollectionSchema(fields=[int64_field, float_field, float_vector])
>>> connections.connect(host="172.22.255.155", port="19530")
<pymilvus.client.stub.Milvus object at 0x7f8c95a7d5c0>
>>> import numpy as np
>>> collection = Collection("test_search_collection_binbin_6", schema=schema)
>>> partition = Partition(collection, "test_partition")
>>> dim = 128
>>> nb = 500
>>> nq = 1
>>> limit = 1000
>>> import random
>>>
>>>
>>> default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
>>> vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
>>> partition.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
Error: <BaseException: (code=1, message=collection hasn't been loaded or has been released, collection id = %d425468383265030145
>>> data=[[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors]
>>> collection.partitions
[{"name": "_default", "description": "", "num_entities": 0}, {"name": "test_partition", "description": "", "num_entities": 0}]
>>> partition.insert(data)
>>> collection.load()
>>> partition.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0")
<pymilvus_orm.search.SearchResult object at 0x7f8c942416a0>

**Comment by binbinlv** [comment]
Could you please link the fix code in this issue?  Thanks
@DragonDriver

**Comment by binbinlv** [comment]
Verified, close it.
