### ISSUE TITLE
Create index failed with error: number of master service is incorrect

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#5586]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
2021-06-03 18:08:41,706 - milvus_benchmark.client:49 - DEBUG - Milvus insert run in 4.59s
2021-06-03 18:08:41,708 - milvus_benchmark.runners.accuracy:234 - DEBUG - End insert, start flush
2021-06-03 18:08:43,748 - milvus_benchmark.client:49 - DEBUG - Milvus flush run in 2.04s
2021-06-03 18:08:43,749 - milvus_benchmark.runners.accuracy:236 - DEBUG - End flush
2021-06-03 18:08:43,752 - milvus_benchmark.client:364 - DEBUG - Row count: 1183514 in collection: <glove_200_angular>
2021-06-03 18:08:43,753 - milvus_benchmark.runners.accuracy:238 - INFO - Table: glove_200_angular, row count: 1183514
2021-06-03 18:08:43,756 - milvus_benchmark.client:251 - INFO - None
2021-06-03 18:08:43,756 - milvus_benchmark.client:262 - INFO - Drop index: glove_200_angular
2021-06-03 18:08:43,759 - milvus_benchmark.runners.accuracy:243 - INFO - Re-create index: glove_200_angular
2021-06-03 18:08:43,760 - milvus_benchmark.client:236 - INFO - Building index start, collection_name: glove_200_angular, index_type:
 IVF_FLAT, metric_type: IP
2021-06-03 18:08:43,760 - milvus_benchmark.client:238 - INFO - {'nlist': 1024}
2021-06-03 18:09:17,317 - milvus.client.grpc_handler:56 - ERROR - Error: <BaseException: (code=1, message=CreateIndex failed, error
= number of master service is incorrect, 0)>
Error: <BaseException: (code=1, message=CreateIndex failed, error = number of master service is incorrect, 0)>
2021-06-03 18:09:17,318 - milvus_benchmark.main:113 - ERROR - <BaseException: (code=1, message=CreateIndex failed, error = number of
 master service is incorrect, 0)>
2021-06-03 18:09:17,320 - milvus_benchmark.main:114 - ERROR - Traceback (most recent call last):
  File "main.py", line 88, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/accuracy.py", line 244, in prepare
    self.milvus.create_index(index_field_name, index_type, metric_type, index_param=index_param)
  File "/src/milvus_benchmark/client.py", line 46, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 244, in create_index
    self._milvus.create_index(self._collection_name, field_name, index_params, _async=_async)
  File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 39, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 728, in create_index
    return handler.create_index(collection_name, field_name, params, timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 62, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 54, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 808, in create_index
    raise BaseException(status.error_code, status.reason)
milvus.client.exceptions.BaseException: <BaseException: (code=1, message=CreateIndex failed, error = number of master service is inc
orrect, 0)>
```
**Steps/Code to reproduce behavior**
1. create collection
2. insert 50,000 entities per request, total 1183514
3. flush
4. drop index, create index:  IVF_FLAT, metric_type: IP, with params {'nlist': 1024}
5. 

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by czs007** [comment]
At that time, the problem is that IndexService did not start successfully, but the reason was not found. The log here should be "number of index service is not correct".
I think it can be closed.
