### ISSUE TITLE
Server crashes when flushing collection with data

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#5610]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**

1. `add_connection` and `connect` get Milvus object as conn
2. create a schema with int64, float64, float_vec fields
2. create a collection with schema and 1200 entities
3. conn.flush([collection])

```
    def test_collection_with_dataframe(self):
        conn = self._connect()
        nb = ct.default_nb
        c_name = cf.gen_unique_str(prefix)
        data = cf.gen_default_dataframe_data(nb)
        collection, _ = self.collection.collection_init(c_name, schema=default_schema, data=data)
        conn.flush([c_name])
        assert_default_collection(collection, c_name, exp_num=nb)
```
The console log:
```
        collection, _ = self.collection.collection_init(c_name, schema=default_schema, data=data)
>       conn.flush([c_name])

test_collection.py:619: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../venv/lib/python3.8/site-packages/pymilvus/client/stub.py:39: in inner
    return func(self, *args, **kwargs)
../venv/lib/python3.8/site-packages/pymilvus/client/stub.py:884: in flush
    return handler.flush(collection_names, timeout, **kwargs)
../venv/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py:72: in handler
    raise e
../venv/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py:54: in handler
    return func(self, *args, **kwargs)
../venv/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py:1090: in flush
    self.wait_for_flushed(collection_name)
../venv/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py:72: in handler
    raise e
../venv/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py:54: in handler
    return func(self, *args, **kwargs)
../venv/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py:1061: in wait_for_flushed
    if flushed(first_segment_ids):
../venv/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py:1034: in flushed
    infos = self.get_persistent_segment_infos(collection_name, timeout, **kwargs)
../venv/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py:72: in handler
    raise e
../venv/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py:54: in handler
    return func(self, *args, **kwargs)
../venv/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py:1015: in get_persistent_segment_infos
    response = future.result()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Connection refused...:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Connection refused","grpc_status":14}"
>
timeout = None

    def result(self, timeout=None):
        """Returns the result of the computation or raises its exception.
    
        See grpc.Future.result for the full API contract.
        """
        with self._state.condition:
            timed_out = _common.wait(
                self._state.condition.wait, self._is_complete, timeout=timeout)
            if timed_out:
                raise grpc.FutureTimeoutError()
            else:
                if self._state.code is grpc.StatusCode.OK:
                    return self._state.response
                elif self._state.cancelled:
                    raise grpc.FutureCancelledError()
                else:
>                   raise self
E                   grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
E                   	status = StatusCode.UNAVAILABLE
E                   	details = "Connection refused"
E                   	debug_error_string = "{"created":"@1622788860.787395313","description":"Error received from peer ipv4:172.28.255.155:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Connection refused","grpc_status":14}"
E                   >

../venv/lib/python3.8/site-packages/grpc/_channel.py:624: _MultiThreadedRendezvous
```
Server crashes log:
```
71084 2021-06-04T06:40:38.75004056Z stdout F [2021/06/04 06:40:38.749 +00:00] [DEBUG] [collection_replica.go:295] ["Create collection"] ["collection name"=collection_gfz0N8CZ]
71085 2021-06-04T06:40:38.750116174Z stdout F [2021/06/04 06:40:38.750 +00:00] [DEBUG] [collection_replica.go:147] ["Add Segment"] ["Segment ID"=425404357335318530]
71086 2021-06-04T06:40:38.750120685Z stdout F [2021/06/04 06:40:38.750 +00:00] [DEBUG] [collection_replica.go:147] ["Add Segment"] ["Segment ID"=425404357335318529]
71087 2021-06-04T06:40:38.750122897Z stdout F [2021/06/04 06:40:38.750 +00:00] [DEBUG] [collection_replica.go:236] ["updating segment"] ["Segment ID"=425404357335318530] [numRows=2]
71088 2021-06-04T06:40:38.750125306Z stdout F [2021/06/04 06:40:38.750 +00:00] [DEBUG] [collection_replica.go:236] ["updating segment"] ["Segment ID"=425404357335318529] [numRows=1]
71089 2021-06-04T06:40:38.750128335Z stdout F [2021/06/04 06:40:38.750 +00:00] [DEBUG] [flow_graph_insert_buffer_node.go:749] ["Updating segments statistics..."]
71090 2021-06-04T06:40:38.750175377Z stdout F [2021/06/04 06:40:38.750 +00:00] [ERROR] [flow_graph_insert_buffer_node.go:396] ["binary.Read int64 wrong"] [error=EOF] [stack="github.com/milvus-io/milvus/internal/log.Error\n\t/go/src/github.com/milvus-io/milvus/internal/log/gl      obal.go:42\ngithub.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Operate\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:396\ngithub.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start\n\t/go/src/github.c      om/milvus-io/milvus/internal/util/flowgraph/node.go:73"]
71091 2021-06-04T06:40:38.750179535Z stdout F [2021/06/04 06:40:38.750 +00:00] [ERROR] [flow_graph_insert_buffer_node.go:396] ["binary.Read int64 wrong"] [error=EOF] [stack="github.com/milvus-io/milvus/internal/log.Error\n\t/go/src/github.com/milvus-io/milvus/internal/log/gl      obal.go:42\ngithub.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Operate\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:396\ngithub.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start\n\t/go/src/github.c      om/milvus-io/milvus/internal/util/flowgraph/node.go:73"]
71092 2021-06-04T06:40:38.752388216Z stderr F panic: runtime error: slice bounds out of range [8:0]
71093 2021-06-04T06:40:38.752398608Z stderr F
71094 2021-06-04T06:40:38.752402476Z stderr F goroutine 1090 [running]:
71095 2021-06-04T06:40:38.752405106Z stderr F github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Operate(0xc000675e00, 0xc001ff23b0, 0x1, 0x1, 0x2446940, 0xc00382de80, 0x0)
71096 2021-06-04T06:40:38.752408404Z stderr F     /go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:415 +0x6eaa
71097 2021-06-04T06:40:38.752417943Z stderr F github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start(0xc000a4f6c0, 0x2471860, 0xc00072e100, 0xc0006a5370)
71098 2021-06-04T06:40:38.752420783Z stderr F     /go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:73 +0x137
71099 2021-06-04T06:40:38.752423444Z stderr F created by github.com/milvus-io/milvus/internal/util/flowgraph.(*TimeTickedFlowGraph).Start
71100 2021-06-04T06:40:38.752427289Z stderr F     /go/src/github.com/milvus-io/milvus/internal/util/flowgraph/flow_graph.go:75 +0xfe
```
Total logs:  
[#5610.log](https://github.com/milvus-io/milvus/files/6596826/5610.log)

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
  pymilvus              2.0a1.dev22
  pymilvus-orm          2.0a1.dev17

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by XuanYang-cn** [comment]
I'm on it now

**Comment by XuanYang-cn** [comment]
After 19 days, there's a lot of changes. The offering code doesn't work anymore.

I'm testing with the following code:
```python
    def test_collection_with_dataframe(self):
        conn = self._connect()
        nb = ct.default_nb
        c_name = cf.gen_unique_str(prefix)
        data = cf.gen_default_dataframe_data(nb)
        collection, _ = self.collection_wrap.init_collection(c_name, schema=default_schema, data=data)
        conn.flush([c_name])
```
 And they work fine.

BTW I think this bug has been fixed long time ago.
