### ISSUE TITLE
Sdk grammar error in stub.py

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#5652]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
[2021-06-07 17:11:52,795 - ERROR - refactor_test]: Traceback (most recent call last):
  File "/home/zw/tmp/tmp/milvus/tests20/python_client/utils/api_request.py", line 15, in inner_wrapper
    res = func(*args, **kwargs)
  File "/home/zw/tmp/tmp/milvus/tests20/python_client/utils/api_request.py", line 36, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pymilvus_orm/index.py", line 65, in __init__
    conn.create_index(self._collection.name, self._field_name, self._index_params)
  File "/usr/local/lib/python3.6/dist-packages/pymilvus/client/stub.py", line 39, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pymilvus/client/stub.py", line 710, in create_index
    ", which must be one of: " + valid_index_types)
TypeError: must be str, not list
 (api_request.py:19)
[2021-06-07 17:11:52,796 - ERROR - refactor_test]: [Milvus API Exception]<function api_request at 0x7fee5231aea0>: must be str, not list (api_request.py:20)
```
**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus/pull/560
