### ISSUE TITLE
get_index_build_progress failed if not index created

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#5674]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
ERROR    ci_test:api_request.py:19 Traceback (most recent call last):
  File "/home/zw/tmp/tmp/milvus/tests20/python_client/utils/api_request.py", line 15, in inner_wrapper
    res = func(*args, **kwargs)
  File "/home/zw/tmp/tmp/milvus/tests20/python_client/utils/api_request.py", line 36, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pymilvus_orm/utility.py", line 135, in index_building_progress
    return get_connection(using).get_index_build_progress(collection_name, index_name)
  File "/usr/local/lib/python3.6/dist-packages/pymilvus/client/stub.py", line 39, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pymilvus/client/stub.py", line 1049, in get_index_build_progress
    return handler.get_index_build_progress(collection_name, index_name, timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/pymilvus/client/grpc_handler.py", line 62, in handler
    raise e
  File "/usr/local/lib/python3.6/dist-packages/pymilvus/client/grpc_handler.py", line 54, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pymilvus/client/grpc_handler.py", line 841, in get_index_build_progress
    raise BaseException(status.error_code, status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=Can't found IndexID for indexName_default_idx)>

ERROR    ci_test:api_request.py:20 [Milvus API Exception]<function api_request at 0x7f83124b32f0>: <BaseException: (code=1, message=Can't found IndexID for indexName_default_idx)>
```
**Steps/Code to reproduce behavior**
```
        c_name = cf.gen_unique_str(prefix)
        cw = self.init_collection_wrap(name=c_name)
        data = cf.gen_default_list_data(nb)
        cw.insert(data=data)
        res, _ = self.utility_wrap.index_building_progress(c_name)
```
**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by congqixia** [comment]
Same as #5673 
Currently the python sdk has not way to indicate index name when building index so proxy will compulsorily check whether there is an index named "_default_index". If the specified index can not be found, the exception will be raised. This is the designed behavior.
In next stage, after index naming is supported this behavior will be changed.
@del-zhenwu

**Comment by czs007** [comment]
refer to #5978 @del-zhenwu

**Comment by del-zhenwu** [comment]
need to update the error msg to tell user index should be indexed before

**Comment by czs007** [comment]
I'm working on it

**Comment by czs007** [comment]
> need to update the error msg to tell user index should be indexed before

please refer to #5978
