### ISSUE TITLE
Server unavailable after call `create index`

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#5703]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
2021-06-09 18:09:09,984 - milvus_benchmark.client:49 - DEBUG - Milvus insert run in 12.02s
2021-06-09 18:09:24,371 - milvus_benchmark.client:49 - DEBUG - Milvus insert run in 12.5s
2021-06-09 18:09:33,045 - milvus_benchmark.client:49 - DEBUG - Milvus insert run in 7.16s
2021-06-09 18:09:33,047 - milvus_benchmark.runners.accuracy:234 - DEBUG - End insert, start flush
2021-06-09 18:09:35,137 - milvus_benchmark.client:49 - DEBUG - Milvus flush run in 2.09s
2021-06-09 18:09:35,138 - milvus_benchmark.runners.accuracy:236 - DEBUG - End flush
2021-06-09 18:09:35,141 - milvus_benchmark.client:370 - DEBUG - Row count: 1183514 in collection: <glove_200_angular>
2021-06-09 18:09:35,142 - milvus_benchmark.runners.accuracy:238 - INFO - Table: glove_200_angular, row count: 1183514
2021-06-09 18:09:35,145 - milvus_benchmark.client:257 - INFO - None
2021-06-09 18:09:35,145 - milvus_benchmark.client:268 - INFO - Drop index: glove_200_angular
2021-06-09 18:09:35,148 - milvus_benchmark.runners.accuracy:243 - INFO - Re-create index: glove_200_angular
2021-06-09 18:09:35,148 - milvus_benchmark.client:242 - INFO - Building index start, collection_name: glove_200_angular, index_type:
 IVF_FLAT, metric_type: IP
2021-06-09 18:09:35,149 - milvus_benchmark.client:244 - INFO - {'nlist': 1024}
Addr [benchmark-cron-1623261600-5-milvus-ha.qa-milvus.svc.cluster.local:19530] create_index
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Socket closed"
        debug_error_string = "{"created":"@1623283327.116446572","description":"Error received from peer ipv4:10.96.177.18:19530","f
ile":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
>
        {'API start': '2021-06-09 18:09:35.149900', 'RPC start': '2021-06-09 18:09:35.149909', 'RPC error': '2021-06-10 00:02:07.119
455'}
2021-06-10 00:02:07,119 - milvus.client.grpc_handler:71 - ERROR -
Addr [benchmark-cron-1623261600-5-milvus-ha.qa-milvus.svc.cluster.local:19530] create_index
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Socket closed"
        debug_error_string = "{"created":"@1623283327.116446572","description":"Error received from peer ipv4:10.96.177.18:19530","f
ile":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
>
        {'API start': '2021-06-09 18:09:35.149900', 'RPC start': '2021-06-09 18:09:35.149909', 'RPC error': '2021-06-10 00:02:07.119
455'}
2021-06-10 00:02:07,121 - milvus_benchmark.main:113 - ERROR - <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Socket closed"
        debug_error_string = "{"created":"@1623283327.116446572","description":"Error received from peer ipv4:10.96.177.18:19530","f
ile":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
>
2021-06-10 00:02:07,125 - milvus_benchmark.main:114 - ERROR - Traceback (most recent call last):
  File "main.py", line 88, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/accuracy.py", line 244, in prepare
    self.milvus.create_index(index_field_name, index_type, metric_type, index_param=index_param)
  File "/src/milvus_benchmark/client.py", line 46, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 250, in create_index
    self._milvus.create_index(self._collection_name, field_name, index_params, _async=_async)
  File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 39, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 728, in create_index
    return handler.create_index(collection_name, field_name, params, timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 72, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 54, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 805, in create_index
    status = future.result()
  File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 625, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Socket closed"
        debug_error_string = "{"created":"@1623283327.116446572","description":"Error received from peer ipv4:10.96.177.18:19530","f
ile":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
>
```
**Steps/Code to reproduce behavior**
1. create collection
2. insert 1183514 entities, 50000 entities per request
3. create index:  index_type: IVF_FLAT, metric_type: IP with params: {'nlist': 1024}
**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by lajiyuan** [comment]
Can you share your milvus client code and milvus server version?

**Comment by del-zhenwu** [comment]
client:
`zilliztech/milvus_benchmark`: argo branch
server:
the latest image

**Comment by del-zhenwu** [comment]
the most of the benchmark cases still failed blocked by the issue

**Comment by yanliang567** [comment]
it looks not repro on Built:     Wed Jun 23 07:31:13 UTC 2021   GitCommit: 9ebca59 with cluster mode. i am not sure for standalone mode, please check.

**Comment by yanliang567** [comment]
@del-zhenwu does this repro recently on latest build?

**Comment by del-zhenwu** [comment]
> @del-zhenwu does this repro recently on latest build?

seems no-reproduced, close
