### ISSUE TITLE
 error occurs when pip3 install pymilvus==1.1.0

### ISSUE THREAD

**Issue by m5jun** [milvus-io/milvus#5758]
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-e052d2ni/grpcio/setup.py", line 255, in <module>
        if check_linker_need_libatomic():
      File "/tmp/pip-build-e052d2ni/grpcio/setup.py", line 205, in check_linker_need_libatomic
        stderr=PIPE)
      File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
        restore_signals, start_new_session)
      File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'c++': 'c++'

**Comment by yhmo** [comment]
Please refer this issue: https://github.com/grpc/grpc/issues/24556

**Comment by shengjun1985** [comment]
It seems to be solved.
