### ISSUE TITLE
Insert failed with err msg: the length of hashValue, timestamps , rowIDs, RowData are not equal

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#5764]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
2021-06-14 18:05:30,250 - milvus_benchmark.client:128 - INFO - Create collection: <sift_128_euclidean> successfully
2021-06-14 18:05:31,327 - milvus_benchmark.runners.accuracy:216 - DEBUG - The row count of entities to be inserted: 1000000
Error: <BaseException: (code=1, message=the length of hashValue, timestamps, rowIDs, RowData are not equal)>
2021-06-14 18:05:35,882 - milvus.client.grpc_handler:56 - ERROR - Error: <BaseException: (code=1, message=the length of hashValue, t
imestamps, rowIDs, RowData are not equal)>
2021-06-14 18:05:35,882 - milvus_benchmark.client:145 - ERROR - <BaseException: (code=1, message=the length of hashValue, timestamps
, rowIDs, RowData are not equal)>
2021-06-14 18:05:35,900 - milvus_benchmark.client:49 - DEBUG - Milvus insert run in 4.22s
2021-06-14 18:05:35,900 - milvus_benchmark.main:113 - ERROR -
2021-06-14 18:05:35,902 - milvus_benchmark.main:114 - ERROR - Traceback (most recent call last):
  File "main.py", line 88, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/accuracy.py", line 233, in prepare
    assert res_ids == ids
AssertionError
```
**Steps/Code to reproduce behavior**
1. create collection
2. insert entities

using sdk: pymilvus 

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
Please paste test code here.

**Comment by del-zhenwu** [comment]
> Please paste test code here.

zilliztech/milvus_benchmark:argo
could not reproduce, close

**Comment by xiaocai2333** [comment]
The logic of auto_id is changed, please retest by pymilvus-orm==2.0a1.dev37.

**Comment by del-zhenwu** [comment]
> The logic of auto_id is changed, please retest by pymilvus-orm==2.0a1.dev37.

the tests used `pymilvus`

**Comment by DragonDriver** [comment]
Already fixed. Cannot reproduce in my pc, please retry this.
/unassign
/assign @del-zhenwu
