### ISSUE TITLE
Describe collection failed

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#5842]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```

2021-06-17 09:47:11,718 - milvus_benchmark.main:83 - DEBUG - Get runner
2021-06-17 09:47:23,804 - milvus_benchmark.main:87 - INFO - Prepare to run cases
2021-06-17 09:47:23,818 - milvus_benchmark.client:135 - INFO - Create collection: <sift_1m_128_l2> successfully
2021-06-17 09:47:23,820 - milvus.client.grpc_handler:76 - ERROR -
Addr [benchmark-46n87-1-milvus-ha.qa-milvus.svc.cluster.local:19530] describe_collection
Excepted error: 'dim'
        {'API start': '2021-06-17 09:47:23.818624', 'RPC start': '2021-06-17 09:47:23.818634', 'Exception': '2021-06-17 09:47:23.820
127'}
Addr [benchmark-46n87-1-milvus-ha.qa-milvus.svc.cluster.local:19530] describe_collection
Excepted error: 'dim'
        {'API start': '2021-06-17 09:47:23.818624', 'RPC start': '2021-06-17 09:47:23.818634', 'Exception': '2021-06-17 09:47:23.820
127'}
2021-06-17 09:47:23,820 - milvus_benchmark.main:113 - ERROR - 'dim'
2021-06-17 09:47:23,822 - milvus_benchmark.main:114 - ERROR - Traceback (most recent call last):
  File "main.py", line 88, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/get.py", line 112, in prepare
    case_param["collection_size"], case_param["ni_per"])
  File "/src/milvus_benchmark/runners/base.py", line 100, in insert
    info = milvus.get_info(collection_name)
  File "/src/milvus_benchmark/client.py", line 408, in get_info
    return self._milvus.describe_collection(collection_name)
  File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 39, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/milvus/client/stub.py", line 267, in describe_collection
    return handler.describe_collection(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 77, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 54, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/milvus/client/grpc_handler.py", line 401, in describe_collection
    return CollectionSchema(raw=response).dict()
  File "/usr/local/lib/python3.6/site-packages/milvus/client/abstract.py", line 127, in __init__
    self.__pack(self._raw)
  File "/usr/local/lib/python3.6/site-packages/milvus/client/abstract.py", line 141, in __pack
    self.fields.append(FieldSchema(f))
  File "/usr/local/lib/python3.6/site-packages/milvus/client/abstract.py", line 74, in __init__
    self.__pack(self._raw)
  File "/usr/local/lib/python3.6/site-packages/milvus/client/abstract.py", line 90, in __pack
    self.params[type_param.key] = int(self.params[type_param.key])
KeyError: 'dim'
2021-06-17 09:47:23,8
```
**Steps/Code to reproduce behavior**
1. create collection
2. describe collection

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)
sdk: pymilvus

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
Please update the version of pymilvus.
