### ISSUE TITLE
Get/query entity failed

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#5876]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
W
benchmark-jj7vl-2960724823: 2021-06-18 09:48:20,089 - milvus_benchmark.main:89 - INFO - Start run case
benchmark-jj7vl-2960724823: 2021-06-18 09:48:20,192 - pymilvus.client.grpc_handler:77 - ERROR -
benchmark-jj7vl-2960724823: Addr [benchmark-jj7vl-1-milvus-ha.qa-milvus.svc.cluster.local:19530] query
benchmark-jj7vl-2960724823: Excepted error: error_code
benchmark-jj7vl-2960724823:     {'API start': '2021-06-18 09:48:20.099470', 'RPC start': '2021-06-18 09:48:20.099491', 'Exception':
'2021-06-18 09:48:20.192729'}
benchmark-jj7vl-2960724823: 2021-06-18 09:48:20,194 - milvus_benchmark.main:98 - ERROR - Traceback (most recent call last):
benchmark-jj7vl-2960724823:   File "main.py", line 95, in run_suite
benchmark-jj7vl-2960724823:     result = runner.run_case(case_metric, **case)
benchmark-jj7vl-2960724823:   File "/src/milvus_benchmark/runners/get.py", line 87, in run_case
benchmark-jj7vl-2960724823:     self.milvus.get(ids)
benchmark-jj7vl-2960724823:   File "/src/milvus_benchmark/client.py", line 46, in wrapper
benchmark-jj7vl-2960724823:     result = func(*args, **kwargs)
benchmark-jj7vl-2960724823:   File "/src/milvus_benchmark/client.py", line 241, in get
benchmark-jj7vl-2960724823:     res = self._milvus.query(tmp_collection_name, ids_expr, output_fields=None, partition_names=None)
benchmark-jj7vl-2960724823:   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 39, in inner
benchmark-jj7vl-2960724823:     return func(self, *args, **kwargs)
benchmark-jj7vl-2960724823:   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 1124, in query
benchmark-jj7vl-2960724823:     return handler.query(collection_name, expr, output_fields, partition_names, timeout=timeout)
benchmark-jj7vl-2960724823:   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 78, in handler
benchmark-jj7vl-2960724823:     raise e
benchmark-jj7vl-2960724823:   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 55, in handler
benchmark-jj7vl-2960724823:     return func(self, *args, **kwargs)
benchmark-jj7vl-2960724823:   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 1129, in query
benchmark-jj7vl-2960724823:     raise BaseException(response.error_code, response.reason)
benchmark-jj7vl-2960724823: AttributeError: error_code
```
**Steps/Code to reproduce behavior**
expr:
```
"id in [*,*]"
```
**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
```
pymilvus==2.0a1.dev35

```
- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by czs007** [comment]
@fishpenguin

**Comment by fishpenguin** [comment]
Fixed
