### ISSUE TITLE
data node crashed on full-ci test

### ISSUE THREAD

**Issue by neza2017** [milvus-io/milvus#5882]
**Describe the bug**
data node crashed on full-ci test

**Steps/Code to reproduce behavior**
```bash
cd tests/python_test
pytest -n 8
```

- Milvus version  master

```log
panic: Failed to describe collection, resp.Reason: describe collection failed: can't find collection id : 425738594935635969

goroutine 246130 [running]:
github.com/milvus-io/milvus/internal/datanode.(*dataSyncService).initNodes(0xc00f097b00, 0xc016444930)
	/home/cyf/work/milvus/internal/datanode/data_sync_service.go:192 +0x1bdc
github.com/milvus-io/milvus/internal/datanode.newDataSyncService(0x24bae00, 0xc0001befc0, 0xc019a0ec60, 0x24cb9c0, 0xc01043b4a0, 0x24a5200, 0xc0164581d0, 0x24bb780, 0xc00021fc60, 0xc016444930, ...)
	/home/cyf/work/milvus/internal/datanode/data_sync_service.go:71 +0x1b5
github.com/milvus-io/milvus/internal/datanode.(*DataNode).NewDataSyncService(0xc00037c0d0, 0xc016444930, 0x0, 0x0)
	/home/cyf/work/milvus/internal/datanode/data_node.go:169 +0x599
github.com/milvus-io/milvus/internal/datanode.(*DataNode).WatchDmChannels(0xc00037c0d0, 0x24baec0, 0xc01645a180, 0xc01016f280, 0x2223c00, 0x24cae00, 0x24bb700)
	/home/cyf/work/milvus/internal/datanode/data_node.go:265 +0x146
github.com/milvus-io/milvus/internal/distributed/datanode.(*Server).WatchDmChannels(0xc0002ae5a0, 0x24baec0, 0xc01645a180, 0xc01016f280, 0xc0002ae5a0, 0x2495f20, 0xc01043b310)
	/home/cyf/work/milvus/internal/distributed/datanode/service.go:260 +0x4c
github.com/milvus-io/milvus/internal/proto/datapb._DataNode_WatchDmChannels_Handler.func1(0x24baec0, 0xc01645a180, 0x221b160, 0xc01016f280, 0x231e84c, 0x2b, 0x24baec0, 0xc01645a180)
	/home/cyf/work/milvus/internal/proto/datapb/data_service.pb.go:3407 +0x89
github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1(0x24baec0, 0xc01645a120, 0x221b160, 0xc01016f280, 0xc00f580fe0, 0xc00f581000, 0xc01d66db78, 0x83fb06, 0x21f34c0, 0xc01645a120)
	/home/cyf/work/milvus-distributed-path/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/tracing/opentracing/server_interceptors.go:30 +0xda
github.com/milvus-io/milvus/internal/proto/datapb._DataNode_WatchDmChannels_Handler(0x2223c00, 0xc0002ae5a0, 0x24baec0, 0xc01645a120, 0xc019a0eb40, 0xc00007cb40, 0x24baec0, 0xc01645a120, 0xc00f14a040, 0x35)
	/home/cyf/work/milvus/internal/proto/datapb/data_service.pb.go:3409 +0x150
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000102c00, 0x24c72c0, 0xc000267c80, 0xc019277d00, 0xc0006aecf0, 0x3168370, 0x0, 0x0, 0x0)
	/home/cyf/work/milvus-distributed-path/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:1024 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc000102c00, 0x24c72c0, 0xc000267c80, 0xc019277d00, 0x0)
	/home/cyf/work/milvus-distributed-path/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:1313 +0xd34
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0006aacd0, 0xc000102c00, 0x24c72c0, 0xc000267c80, 0xc019277d00)
	/home/cyf/work/milvus-distributed-path/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:722 +0xa5
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/cyf/work/milvus-distributed-path/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:720 +0xa5

```

**Comment by XuanYang-cn** [comment]
This logic has been changed, datanode won't crash by this.
