### ISSUE TITLE
[Chaos] Fail to connect to Milvus after milvus-ha pod deleted and restarted

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#5901]
**Describe the bug**
Fail to connect to Milvus after milvus-ha pod deleted and restarted

**Steps/Code to reproduce behavior**
helm install milvus standalone
connect to Milvus by python SDK(run a python testcase)
delete the milvus-ha-standalone pod
wait until the milvus-ha-standalone pod restarted to running state
try reconnect to Milvus( try to rerun the python testcase)

**Expected behavior**
reconnect successfully

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
2.0

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

**Log attachement**
[milvus-ha-standalone-pod.log](https://github.com/milvus-io/milvus/files/6683579/milvus-ha-standalone-pod.log)

```

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by yanliang567** [comment]
[standalone.crash2.log](https://github.com/milvus-io/milvus/files/6685470/standalone.crash2.log)
the standalone pod crashed this time after running a search test, then fail to reconnect even after the pod is running

**Comment by yanliang567** [comment]
The standalone pod crashed when trying to do a query(but not every query, will do more testing to specify the repro query) 
call stacks are:
[2021-06-21 18:12:21,779 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/yanliang/pymilvus/pymilvus/client/stub.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/Users/yanliang/pymilvus/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/Users/yanliang/pymilvus/pymilvus/client/stub.py", line 1117, in query
    return handler.query(collection_name, expr, output_fields, partition_names, timeout=timeout)
  File "/Users/yanliang/pymilvus/pymilvus/client/grpc_handler.py", line 73, in handler
    raise e
  File "/Users/yanliang/pymilvus/pymilvus/client/grpc_handler.py", line 55, in handler
    return func(self, *args, **kwargs)
  File "/Users/yanliang/pymilvus/pymilvus/client/grpc_handler.py", line 1033, in query
    response = future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/grpc/_channel.py", line 624, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Socket closed"
        debug_error_string = "{"created":"@1624270309.740377000","description":"Error received from peer ipv4:10.98.0.7:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yanliang/pymilvus/pymilvus/client/grpc_handler.py", line 329, in ping
    ft.result(timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/grpc/_utilities.py", line 140, in result
    self._block(timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/grpc/_utilities.py", line 86, in _block
    raise grpc.FutureTimeoutError()
grpc.FutureTimeoutError

**Comment by binbinlv** [comment]
#5949 maybe the same root cause

**Comment by yanliang567** [comment]
#5949 shall focus on why milvus crashes, and this issue focuses on why it is not able to connect after pod deleted and restarted

**Comment by yanliang567** [comment]
it does not repro if MILVUS_CLUSTER_ENABLED=true

**Comment by ThreadDao** [comment]
1. standalone pod crashed and restated 2. `raise Exception("server is not healthy, please try again later")`
[1.log](https://github.com/milvus-io/milvus/files/6700434/1.log)

**Comment by neza2017** [comment]
```txt
2021-06-23T08:40:49.593957335Z stdout F
2021-06-23T08:40:49.593980659Z stdout F     __  _________ _   ____  ______
2021-06-23T08:40:49.593986977Z stdout F    /  |/  /  _/ /| | / / / / / __/
2021-06-23T08:40:49.593989647Z stdout F   / /|_/ // // /_| |/ / /_/ /\ \
2021-06-23T08:40:49.593992153Z stdout F  /_/  /_/___/____/___/\____/___/
2021-06-23T08:40:49.593994374Z stdout F
2021-06-23T08:40:49.593996899Z stdout F Welcome to use Milvus!
2021-06-23T08:40:49.59400035Z stdout F Version:   a09a3a1
2021-06-23T08:40:49.594002902Z stdout F Built:     Wed Jun 23 08:16:33 UTC 2021
2021-06-23T08:40:49.594005335Z stdout F GitCommit: a09a3a1
2021-06-23T08:40:49.594007756Z stdout F GoVersion: go version go1.15.2 linux/amd64
```

this git commit not found in the master branch, please check it

**Comment by neza2017** [comment]
```bash
git log | grep  a09a3a1
```

**Comment by neza2017** [comment]
msgstream.Seek block RootCoord, so root_coord in `Initializing` state
1.  we could find this msg in the log file `[root_coord.go:494] ["msgstream seek to position"]`
2. bu we could not find `[root_coord.go:498] ["msg stream seek`

**Comment by yanliang567** [comment]
on build master-20210626-2e37fca with PVC configured, it still repros

**Comment by yanliang567** [comment]
[standalone.crash2.log](https://github.com/milvus-io/milvus/files/6719935/standalone.crash2.log)

**Comment by yanliang567** [comment]
keep deleting the standalone pod for a few seconds, it still repros:
[standalone.crash3.log](https://github.com/milvus-io/milvus/files/6720032/standalone.crash3.log)

**Comment by yanliang567** [comment]
verified on build master-20210626-6036ef2
