### ISSUE TITLE
Create  a collection using not existed field as primary field should thrown an exception

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#5918]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
    def test_collection_not_existed_primary_field(self):
        self._connect()
        fake_field = cf.gen_unique_str()
        fields = [cf.gen_int64_field(), cf.gen_float_vec_field()]
        error = {ct.err_code: 0, ct.err_msg: "not existed field"}

        self.collection_schema_wrap.init_collection_schema(fields, primary_field=fake_field, 
                                                           check_task=CheckTasks.err_res, check_items=error)
```
```
[2021-06-21 14:40:09,945 - ERROR - ci_test]: Traceback (most recent call last):
  File "/home/zong/zong/projects/milvus/tests20/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/utils/api_request.py", line 41, in api_request
    return func(*arg, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus_orm/schema.py", line 55, in __init__
    if self._primary_field.dtype not in [DataType.INT64]:
AttributeError: 'NoneType' object has no attribute 'dtype'
 (api_request.py:22)
[2021-06-21 14:40:09,945 - ERROR - ci_test]: (api_response) [Milvus API Exception]<function api_request at 0x7fcd0bf0bdc0>: 'NoneType' object has no attribute 'dtype' (api_request.py:23)
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus              2.0a1.dev41
 pymilvus-orm          2.0a1.dev37

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/178
