### ISSUE TITLE
Failed to create a field when the is_primary and auto_id params are both false

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#5933]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
[2021-06-21 16:49:07,319 - DEBUG - ci_test]: is_primary: False (common_func.py:30)
[2021-06-21 16:49:07,319 - DEBUG - ci_test]: auto_id: False (common_func.py:31)
[2021-06-21 16:49:07,319 - DEBUG - ci_test]: (api_request) Request: [<class 'pymilvus_orm.schema.FieldSchema'>] args: ['int64', <DataType.INT64: 5>, ''], kwargs: {'is_primary': False, 'auto_id': False} (api_request.py:39)
[2021-06-21 16:49:07,319 - ERROR - ci_test]: Traceback (most recent call last):
  File "/home/zong/zong/projects/milvus/tests20/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/utils/api_request.py", line 41, in api_request
    return func(*arg, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus_orm/schema.py", line 187, in __init__
    raise PrimaryKeyException(0, "auto_id can only be specified on the primary key field")
pymilvus_orm.exceptions.PrimaryKeyException: <PrimaryKeyException: (code=0, message=auto_id can only be specified on the primary key field)>
 (api_request.py:22)
```
maybe not only auto_id in kwargs but also auot_id=True
```
        self.is_primary = kwargs.get("is_primary", False)
        if "auto_id" in kwargs:
            if not self.is_primary:
                raise PrimaryKeyException(0, "auto_id can only be specified on the primary key field")
```
**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus              2.0a1.dev42
 pymilvus-orm          2.0a1.dev39

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
pymilvus-orm==2.0a1.dev42
