### ISSUE TITLE
The exception message about non-int type dimensions is confusing

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#5950]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
    def test_collection_vector_invalid_dim(self, get_invalid_dim):
        """
        target: test collection with invalid dimension
        method: define float-vec field with invalid dimension
        expected: raise exception
        """
        self._connect()
        c_name = cf.gen_unique_str(prefix)
        float_vec_field = cf.gen_float_vec_field(dim=get_invalid_dim)
        schema = cf.gen_collection_schema(fields=[cf.gen_int64_field(is_primary=True), float_vec_field])
        error = {ct.err_code: 0, ct.err_msg: "dim must be of int"}
        self.collection_wrap.init_collection(c_name, schema=schema, check_task=CheckTasks.err_res, check_items=error)
```
```
[2021-06-21 20:56:32,125 - ERROR - ci_test]: Traceback (most recent call last):
  File "/home/zong/zong/projects/milvus/tests20/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/utils/api_request.py", line 41, in api_request
    return func(*arg, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus_orm/collection.py", line 122, in __init__
    conn.create_collection(self._name, fields=schema.to_dict())
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/client/stub.py", line 63, in handler
    raise e
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/client/stub.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/client/stub.py", line 229, in create_collection
    return handler.create_collection(collection_name, fields, timeout, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 78, in handler
    raise e
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 55, in handler
    return func(self, *args, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 358, in create_collection
    request = Prepare.create_collection_request(collection_name, fields, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/client/prepare.py", line 104, in create_collection_request
    int(tv)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'
 (api_request.py:22)
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus              2.0a1.dev42
 pymilvus-orm          2.0a1.dev39
 
**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by DragonDriver** [comment]
OK, I will fix this as soon as possible.

**Comment by DragonDriver** [comment]
OK, i will fix this as soon as possible.

**Comment by DragonDriver** [comment]
Already fixed. PTAL @ThreadDao

**Comment by ThreadDao** [comment]
??
```
[2021-06-24 17:23:58,143 - ERROR - ci_test]: Traceback (most recent call last):
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/client/prepare.py", line 104, in create_collection_request
    int(tv)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'
```

**Comment by DragonDriver** [comment]
test code:

```py
#!/usr/bin/env python

from pymilvus import Milvus, DataType

ip = "127.0.0.1"
port = "19530"

fields = {
    "fields": [
        {"name": "int64", "type": DataType.INT64, "is_primary": True, "auto_id": True},
        {"name": "float", "type": DataType.FLOAT},
        {"name": "fvec", "type": DataType.FLOAT_VECTOR,
         "params": {"dim": [1, 2, 3, 4]},
         "indexes": [{"index_type": "IVF_PQ", "metric_type": "L2"}]},
    ]
}

c = "c_5950"

if __name__ == "__main__":
    client = Milvus(host=ip, port=port)
    if client.has_collection(c):
        client.drop_collection(c)

    client.create_collection(c, fields)
```

Exception:

Addr [127.0.0.1:19530] create_collection
Excepted error: invalid dim: [1, 2, 3, 4]
	{'API start': '2021-06-25 10:02:42.907756', 'RPC start': '2021-06-25 10:02:42.907872', 'Exception': '2021-06-25 10:02:42.907927'}
Traceback (most recent call last):
  File "/home/ljq/work/pymilvus/pymilvus/client/prepare.py", line 104, in create_collection_request
    int(tv)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "5950.py", line 25, in <module>
    client.create_collection(c, fields)
  File "/home/ljq/work/pymilvus/pymilvus/client/stub.py", line 63, in handler
    raise e
  File "/home/ljq/work/pymilvus/pymilvus/client/stub.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/home/ljq/work/pymilvus/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/home/ljq/work/pymilvus/pymilvus/client/stub.py", line 229, in create_collection
    return handler.create_collection(collection_name, fields, timeout, **kwargs)
  File "/home/ljq/work/pymilvus/pymilvus/client/grpc_handler.py", line 78, in handler
    raise e
  File "/home/ljq/work/pymilvus/pymilvus/client/grpc_handler.py", line 55, in handler
    return func(self, *args, **kwargs)
  File "/home/ljq/work/pymilvus/pymilvus/client/grpc_handler.py", line 358, in create_collection
    request = Prepare.create_collection_request(collection_name, fields, **kwargs)
  File "/home/ljq/work/pymilvus/pymilvus/client/prepare.py", line 106, in create_collection_request
    raise ParamError("invalid dim: " + str(tv))
pymilvus.client.exceptions.ParamError: invalid dim: [1, 2, 3, 4]

**Comment by DragonDriver** [comment]
Already fixed in pymilvus. I will update pymilvus-orm later.
