### ISSUE TITLE
Insert data failed with True auto_id in construct_from_dataframe

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#5967]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
    @pytest.mark.tags(CaseLabel.L0)
    def test_construct_with_auto_id_true_no_insert(self):
        """
        target: test construct with true auto_id
        method: auto_id=True and not insert ids
        expected: verify num entities
        """
        self._connect()
        c_name = cf.gen_unique_str(prefix)
        df = cf.gen_default_dataframe_data(ct.default_nb)
        log.debug(df.head(3))
        df.drop(ct.default_int64_field_name, axis=1, inplace=True)
        log.debug(df.head(3))
        self.collection_wrap.construct_from_dataframe(c_name, df, priamry_field=ct.default_int64_field_name, auto_id=True)
        assert self.collection_wrap.num_entities == ct.default_nb
```
1. original df and  2. primary field values dropped df
```
int64  float                                       float_vector
0      0    0.0  [0.09336766008855327, 0.1317674862643589, 0.01...
1      1    1.0  [0.0563550342364594, 0.09466234222466972, 0.11...
2      2    2.0  [0.13097454121763366, 0.03635290706943362, 0.1... (test_collection.py:1150)

float                                       float_vector
0    0.0  [0.09336766008855327, 0.1317674862643589, 0.01...
1    1.0  [0.0563550342364594, 0.09466234222466972, 0.11...
2    2.0  [0.13097454121763366, 0.03635290706943362, 0.1... (test_collection.py:1152)
```
error trace:
```
3. insert
Traceback (most recent call last):
  File "/home/zong/zong/projects/milvus/tests20/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/utils/api_request.py", line 41, in api_request
    return func(*arg, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus_orm/collection.py", line 184, in construct_from_dataframe
    if dataframe[primary_field].isnull().all():
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'int64'
 (api_request.py:22)
```
```
    @classmethod
    def construct_from_dataframe(cls, name, dataframe, **kwargs):
        if dataframe is None:
            raise SchemaNotReadyException(0, "Dataframe can not be None!")
        if not isinstance(dataframe, pandas.DataFrame):
            raise SchemaNotReadyException(0, "Data type must be pandas.DataFrame!")
        primary_field = kwargs.get("priamry_field", None)
        if primary_field is None:
            raise SchemaNotReadyException(0, "Schema must have a primary key field!")
        auto_id = kwargs.get("auto_id", False)
        if auto_id:
            if dataframe[primary_field].isnull().all():
                dataframe.drop(primary_field, axis=1)
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus              2.0a1.dev42
 pymilvus-orm          2.0a1.dev40

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/181

**Comment by ThreadDao** [comment]
Fresh exception:
```
[2021-06-24 17:35:23,014 - DEBUG - ci_test]:    float                                       float_vector
0    0.0  [0.052903847643819495, 0.050318353581335636, 0...
1    1.0  [0.11665258627907264, 0.01132731987347007, 0.0...
2    2.0  [0.1293863732963343, 0.12627022990892994, 0.01... (test_collection.py:1136)
[2021-06-24 17:35:23,040 - ERROR - ci_test]: Traceback (most recent call last):
  File "/home/zong/zong/projects/milvus/tests20/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/utils/api_request.py", line 41, in api_request
    return func(*arg, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus_orm/collection.py", line 194, in construct_from_dataframe
    raise SchemaNotReadyException(0, "Primary field must in dataframe.")
pymilvus_orm.exceptions.SchemaNotReadyException: <SchemaNotReadyException: (code=0, message=Primary field must in dataframe.)>
```
Dataframe just have `[float, float_vec]` fields because auto_id=True, so that `pk_index == -1 is True`. This exception was thrown from collection.py:
```
    def construct_from_dataframe(cls, name, dataframe, **kwargs):
        if dataframe is None:
            raise SchemaNotReadyException(0, "Dataframe can not be None!")
        if not isinstance(dataframe, pandas.DataFrame):
            raise SchemaNotReadyException(0, "Data type must be pandas.DataFrame!")
        primary_field = kwargs.pop("primary_field", None)
        if primary_field is None:
            raise SchemaNotReadyException(0, "Schema must have a primary key field!")
        pk_index = -1
        for i, field in enumerate(dataframe):
            if field == primary_field:
                pk_index = i
        if pk_index == -1:
            raise SchemaNotReadyException(0, "Primary field must in dataframe.")
```

**Comment by ThreadDao** [comment]
```
FAILED [100%][2021-06-25 17:41:45,150 - DEBUG - ci_test]:    int64  float                                       float_vector
0      0    0.0  [0.1116454926113127, 0.08519984673095117, 0.00...
1      1    1.0  [0.010009149668036904, 0.05134151482359909, 0....
2      2    2.0  [0.09353742784453738, 0.09226466566574479, 0.1... (test_collection.py:1136)
[2021-06-25 17:41:45,179 - ERROR - ci_test]: Traceback (most recent call last):
  File "/home/zong/zong/projects/milvus/tests20/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/utils/api_request.py", line 41, in api_request
    return func(*arg, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus_orm/collection.py", line 207, in construct_from_dataframe
    raise SchemaNotReadyException(0, ExceptionsMessage.AutoIDWithData)
pymilvus_orm.exceptions.SchemaNotReadyException: <SchemaNotReadyException: (code=0, message=Auto_id is True, primary field should not have data.)>
 (api_request.py:22)
[2021-06-25 17:41:45,179 - ERROR - ci_test]: (api_response) [Milvus API Exception]<function api_request at 0x7f529e88b430>: <SchemaNotReadyException: (code=0, message=Auto_id is True, primary field should not have data.)> (api_request.py:23)
```

**Comment by ThreadDao** [comment]
Currently, construct_from_dataframe with auto_id=True, all values in the df primary field must be None, otherwise, an exception will be thrown.

**Comment by ThreadDao** [comment]
I will close this issue.
