### ISSUE TITLE
Create collection with auto_id failed

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#5994]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
@pytest.mark.parametrize("auto_id", [True, False])
    def test_collection_auto_id_in_collection_schema(self, auto_id):
        """
        target: test collection with auto_id in collection schema
        method: specify auto_id True in collection schema
        expected: verify schema auto_id and collection schema
        """
        self._connect()
        c_name = cf.gen_unique_str(prefix)
        int_field = cf.gen_int64_field(is_primary=True)
        vec_field = cf.gen_float_vec_field(name='vec')
        schema, _ = self.collection_schema_wrap.init_collection_schema([int_field, vec_field], auto_id=auto_id)
        log.debug(schema)
        assert schema.auto_id == auto_id
        self.collection_wrap.init_collection(c_name, schema=schema, check_task=CheckTasks.check_collection_property,
                                             check_items={exp_name: c_name, exp_schema: schema})
```
auto=True, and `"auto_id": null` in field schema
```
{"auto_id": true, "description": "", "fields": [{"name": "int64", "description": "", "type": 5, "is_primary": true, "auto_id": null}, {"name": "vec", "description": "", "type": 101, "params": {"dim": 128}}]} (test_collection.py:650)


[2021-06-22 20:41:47,641 - ERROR - ci_test]: Traceback (most recent call last):
  File "/home/zong/zong/projects/milvus/tests20/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/utils/api_request.py", line 41, in api_request
    return func(*arg, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus_orm/collection.py", line 122, in __init__
    conn.create_collection(self._name, fields=schema.to_dict())
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/client/stub.py", line 63, in handler
    raise e
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/client/stub.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/client/stub.py", line 229, in create_collection
    return handler.create_collection(collection_name, fields, timeout, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 78, in handler
    raise e
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 55, in handler
    return func(self, *args, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 358, in create_collection
    request = Prepare.create_collection_request(collection_name, fields, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/client/prepare.py", line 97, in create_collection_request
    field_schema.autoID = auto_id
TypeError: None has type NoneType, but expected one of: int, long, bool
 (api_request.py:22)
[2021-06-22 20:41:47,642 - ERROR - ci_test]: (api_response) [Milvus API Exception]<function api_request at 0x7fcbc992c0d0>: None has type NoneType, but expected one of: int, long, bool (api_request.py:23)
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus              2.0a1.dev44
 pymilvus-orm          2.0a1.dev43

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
https://github.com/milvus-io/pymilvus-orm/pull/182
