### ISSUE TITLE
Server crashed when query on a empty collection

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#6028]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
    def test_query_empty_collection(self):
        c_name = cf.gen_unique_str(prefix)
        collection_w = self.init_collection_wrap(name=c_name)
        collection_w.load()
        res, _ = collection_w.query(default_term_expr)
        assert len(res) == 0
```
[0.log](https://github.com/milvus-io/milvus/files/6700553/0.log)
```
1843 2021-06-23T09:07:18.395834564Z stdout F [2021/06/23 09:07:18.395 +00:00] [DEBUG] [rocksmq_impl.go:111] ["RocksMQ: query_JJYZJ3Ur_425836999644545025_0/begin_id or query_JJYZJ3Ur_425836999644545025_0/end_id existed."]
1844 2021-06-23T09:07:18.395874941Z stdout F [2021/06/23 09:07:18.395 +00:00] [DEBUG] [rocksmq_impl.go:111] ["RocksMQ: query_JJYZJ3Ur_425836999644545025_1/begin_id or query_JJYZJ3Ur_425836999644545025_1/end_id existed."]
1845 2021-06-23T09:07:18.395937543Z stdout F [2021/06/23 09:07:18.395 +00:00] [DEBUG] [task_scheduler.go:841] ["Proxy collectResultLoop, first receive"] [reqID=425836991190601031] [vchans="[query_JJYZJ3Ur_425836999644545025_0_v,query_JJYZJ3Ur_425836999644545025_1_v]"] []
1846 2021-06-23T09:07:18.395975673Z stdout F [2021/06/23 09:07:18.395 +00:00] [DEBUG] [task_scheduler.go:851] ["Proxy collectResultLoop, first receive"] [reqID=425836991190601031] [pchans="[query_JJYZJ3Ur_425836999644545025_0,query_JJYZJ3Ur_425836999644545025_1]"] []
1847 2021-06-23T09:07:18.396027757Z stdout F [2021/06/23 09:07:18.395 +00:00] [DEBUG] [task_scheduler.go:867] ["Proxy collectResultLoop"] ["collection name"=query_JJYZJ3Ur] [reqID=425836991190601031] ["answer cnt"=1]
1848 2021-06-23T09:07:18.396110769Z stdout F [2021/06/23 09:07:18.395 +00:00] [DEBUG] [task_scheduler.go:593] ["Proxy searchResultBuf readyToReduce"] [haveError=true]
1849 2021-06-23T09:07:18.396133182Z stdout F [2021/06/23 09:07:18.396 +00:00] [DEBUG] [task_scheduler.go:871] ["Proxy collectResultLoop readyToReduce and assign to reduce"]
1850 2021-06-23T09:07:18.396261667Z stdout F [2021/06/23 09:07:18.396 +00:00] [DEBUG] [task.go:2172] ["Retrieve failed on all querynodes."] [requestID=425836991190601031] [requestType=retrieve]
1851 2021-06-23T09:07:18.396291591Z stdout F [2021/06/23 09:07:18.396 +00:00] [DEBUG] [task.go:2148] [WaitAndPostExecute] ["time cost"=157.427736ms]
1852 2021-06-23T09:07:18.399876172Z stderr F panic: runtime error: invalid memory address or nil pointer dereference
1853 2021-06-23T09:07:18.399912747Z stderr F [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x146c1f7]
1854 2021-06-23T09:07:18.399924597Z stderr F
1855 2021-06-23T09:07:18.399937638Z stderr F goroutine 4774 [running]:
1856 2021-06-23T09:07:18.399948301Z stderr F github.com/milvus-io/milvus/internal/proxy.(*Proxy).Query.func2(0xc00024d720, 0xc00255a000, 0xc002558360)
1857 2021-06-23T09:07:18.39998846Z stderr F  /go/src/github.com/milvus-io/milvus/internal/proxy/impl.go:1541 +0x517
1858 2021-06-23T09:07:18.40000008Z stderr F github.com/milvus-io/milvus/internal/proxy.(*Proxy).Query(0xc000696dc0, 0x24f8580, 0xc00382def0, 0xc003823b90, 0xc0030c98c0, 0x0, 0x0)
1859 2021-06-23T09:07:18.400010922Z stderr F     /go/src/github.com/milvus-io/milvus/internal/proxy/impl.go:1546 +0xfc8
1860 2021-06-23T09:07:18.400033257Z stderr F github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).Query(0xc0000a8300, 0x24f8580, 0xc00382def0, 0xc003823b90, 0xc0000a8300, 0x0, 0x0)
1861 2021-06-23T09:07:18.400044234Z stderr F     /go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:388 +0x4d
1862 2021-06-23T09:07:18.400094296Z stderr F github.com/milvus-io/milvus/internal/proto/milvuspb._MilvusService_Query_Handler.func1(0x24f8580, 0xc00382def0, 0x228bb60, 0xc003823b90, 0x234dce1, 0x28, 0x24f8580, 0xc00382def0)
1863 2021-06-23T09:07:18.400181184Z stderr F     /go/src/github.com/milvus-io/milvus/internal/proto/milvuspb/milvus.pb.go:4685 +0x8b
1864 2021-06-23T09:07:18.400246326Z stderr F github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1(0x24f8580, 0xc00382dc50, 0x228bb60, 0xc003823b90, 0xc002554a00, 0xc002554a20, 0xc00284db78, 0x83f4a6, 0x2224a80, 0xc00382dc50)
1865 2021-06-23T09:07:18.400270741Z stderr F     /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/tracing/opentracing/server_interceptors.go:30 +0xda
1866 2021-06-23T09:07:18.400347396Z stderr F github.com/milvus-io/milvus/internal/proto/milvuspb._MilvusService_Query_Handler(0x22f9ce0, 0xc0000a8300, 0x24f8580, 0xc00382dc50, 0xc002535ce0, 0xc00079cd30, 0x24f8580, 0xc00382dc50, 0xc0006696b0, 0x21)
1867 2021-06-23T09:07:18.400398883Z stderr F     /go/src/github.com/milvus-io/milvus/internal/proto/milvuspb/milvus.pb.go:4687 +0x150
1868 2021-06-23T09:07:18.40044144Z stderr F google.golang.org/grpc.(*Server).processUnaryRPC(0xc0006faf00, 0x2505a00, 0xc003d3a600, 0xc002550600, 0xc0006a2480, 0x31b3200, 0x0, 0x0, 0x0)
1869 2021-06-23T09:07:18.400479678Z stderr F     /go/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:1024 +0x522
1870 2021-06-23T09:07:18.400533222Z stderr F google.golang.org/grpc.(*Server).handleStream(0xc0006faf00, 0x2505a00, 0xc003d3a600, 0xc002550600, 0x0)
1871 2021-06-23T09:07:18.400578672Z stderr F     /go/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:1313 +0xd34
1872 2021-06-23T09:07:18.400629735Z stderr F google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00304bef0, 0xc0006faf00, 0x2505a00, 0xc003d3a600, 0xc002550600)
1873 2021-06-23T09:07:18.400679179Z stderr F     /go/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:722 +0xa5
1874 2021-06-23T09:07:18.400698273Z stderr F created by google.golang.org/grpc.(*Server).serveStreams.func1
1875 2021-06-23T09:07:18.400717912Z stderr F     /go/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:720 +0xa5
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus              2.0a1.dev44
 pymilvus-orm          2.0a1.dev45
 Image:         milvusdb/milvus-dev:master-latest
    Image ID:      docker.io/milvusdb/milvus-dev@sha256:d1b5944a5c1944e755d07c91d8cba118c31e12c1e5028ae34c05caf1ea15f5d2

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by fishpenguin** [comment]
@czs007

**Comment by fishpenguin** [comment]
@czs007

**Comment by ThreadDao** [comment]
This problem also existed in empty partition
```
    def test_query_not_existed_partition(self):
        collection_w = self.init_collection_wrap(cf.gen_unique_str(prefix))
        collection_w.load()
        partition_names = cf.gen_unique_str()
        collection_w.query(default_term_expr, partition_names=[partition_names])
        error = {ct.err_code: 1, ct.err_msg: 'cannot find partition'}
        collection_w.query(default_term_expr, partition_names=[partition_names],
                           check_items=CheckTasks.err_res, check_task=error)
```
```
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1624505058.158909493","description":"Error received from peer ipv4:172.18.255.155:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}"

```

**Comment by fishpenguin** [comment]
Same bug with [issue 6049](https://github.com/milvus-io/milvus/issues/6049). Already fixed.

**Comment by cydrain** [comment]
query response looks not correct:
```
status.error_code: 26
status.reason: "ids is nil"
```
