### ISSUE TITLE
Server crashed when query with not existed output fields

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#6049]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
actual fields include int64, float, and float_vec. And query with output fields=["int]
```
    def test_query_output_not_existed_field(self):
        collection_w, vectors, _, = self.init_collection_general(prefix, insert_data=True)
        error = {ct.err_code: 1, ct.err_msg: 'cannot find field'}
        collection_w.query(default_term_expr, output_fields=["int"], check_items=CheckTasks.err_res, check_task=error)
```
[0.log](https://github.com/milvus-io/milvus/files/6702127/0.log)
```
10759 2021-06-23T13:18:22.442191359Z stdout F [2021/06/23 13:18:22.442 +00:00] [DEBUG] [task.go:2148] [WaitAndPostExecute] ["time cost"=243.274576ms]
10760 2021-06-23T13:18:22.445476873Z stderr F panic: runtime error: invalid memory address or nil pointer dereference
10761 2021-06-23T13:18:22.445492389Z stderr F [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x146ac17]
10762 2021-06-23T13:18:22.445498597Z stderr F
10763 2021-06-23T13:18:22.445506289Z stderr F goroutine 2394691 [running]:
10764 2021-06-23T13:18:22.445520996Z stderr F github.com/milvus-io/milvus/internal/proxy.(*Proxy).Query.func2(0xc00441b720, 0xc005741ec0, 0xc001312750)
10765 2021-06-23T13:18:22.445528851Z stderr F     /go/src/github.com/milvus-io/milvus/internal/proxy/impl.go:1541 +0x517
10766 2021-06-23T13:18:22.445535262Z stderr F github.com/milvus-io/milvus/internal/proxy.(*Proxy).Query(0xc000158500, 0x24f8f00, 0xc004a9cff0, 0xc0013126c0, 0xc000e8e240, 0x0, 0x0)
10767 2021-06-23T13:18:22.445542801Z stderr F     /go/src/github.com/milvus-io/milvus/internal/proxy/impl.go:1546 +0xfc8
10768 2021-06-23T13:18:22.44555461Z stderr F github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).Query(0xc00011e400, 0x24f8f00, 0xc004a9cff0, 0xc0013126c0, 0xc00011e400, 0x0, 0x0)
10769 2021-06-23T13:18:22.445565312Z stderr F     /go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:388 +0x4d
10770 2021-06-23T13:18:22.445579365Z stderr F github.com/milvus-io/milvus/internal/proto/milvuspb._MilvusService_Query_Handler.func1(0x24f8f00, 0xc004a9cff0, 0x228c040, 0xc0013126c0, 0x234e3d8, 0x28, 0x24f8f00, 0xc004a9cff0)
10771 2021-06-23T13:18:22.445587135Z stderr F     /go/src/github.com/milvus-io/milvus/internal/proto/milvuspb/milvus.pb.go:4685 +0x8b
10772 2021-06-23T13:18:22.445636273Z stderr F github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1(0x24f8f00, 0xc004a9cf90, 0x228c040, 0xc0013126c0, 0xc0047f6640, 0xc0047f6660, 0xc00505cb78, 0x83f4a6, 0x22255c0, 0xc004a9cf90)
10773 2021-06-23T13:18:22.445650664Z stderr F     /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/tracing/opentracing/server_interceptors.go:30 +0xda
10774 2021-06-23T13:18:22.445671544Z stderr F github.com/milvus-io/milvus/internal/proto/milvuspb._MilvusService_Query_Handler(0x22fa400, 0xc00011e400, 0x24f8f00, 0xc004a9cf90, 0xc005741d40, 0xc001e14190, 0x24f8f00, 0xc004a9cf90, 0xc005d94270, 0x26)
10775 2021-06-23T13:18:22.445692668Z stderr F     /go/src/github.com/milvus-io/milvus/internal/proto/milvuspb/milvus.pb.go:4687 +0x150
10776 2021-06-23T13:18:22.445719643Z stderr F google.golang.org/grpc.(*Server).processUnaryRPC(0xc0005d3380, 0x2506380, 0xc004c0b380, 0xc0034fe100, 0xc000370c00, 0x31b21e0, 0x0, 0x0, 0x0)
10777 2021-06-23T13:18:22.445727669Z stderr F     /go/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:1024 +0x522
10778 2021-06-23T13:18:22.445753364Z stderr F google.golang.org/grpc.(*Server).handleStream(0xc0005d3380, 0x2506380, 0xc004c0b380, 0xc0034fe100, 0x0)
10779 2021-06-23T13:18:22.445764334Z stderr F     /go/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:1313 +0xd34
10780 2021-06-23T13:18:22.44578118Z stderr F google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc003abb2e0, 0xc0005d3380, 0x2506380, 0xc004c0b380, 0xc0034fe100)
10781 2021-06-23T13:18:22.445815846Z stderr F     /go/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:722 +0xa5
10782 2021-06-23T13:18:22.445830876Z stderr F created by google.golang.org/grpc.(*Server).serveStreams.func1
10783 2021-06-23T13:18:22.445837613Z stderr F     /go/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:720 +0xa5
```
**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus              2.0a1.dev44
 pymilvus-orm          2.0a1.dev45

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by fishpenguin** [comment]
Already fixed

**Comment by yanliang567** [comment]
It does not crash on built:     
Thu Jun 24 08:46:20 UTC 2021
GitCommit: 0f409da
But the error msg looks meaningless #6074 
@ThreadDao
