### ISSUE TITLE
Server crashed when query on a not existed partition

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#6061]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
    @pytest.mark.tags(CaseLabel.L1)
    def test_query_not_existed_partition(self):
        """
        target: test query on a not existed partition
        method: query on not existed partition
        expected: raise exception
        """
        collection_w = self.init_collection_wrap(cf.gen_unique_str(prefix))
        collection_w.load()
        partition_names = cf.gen_unique_str()
        error = {ct.err_code: 1, ct.err_msg: 'cannot find partition'}
        collection_w.query(default_term_expr, partition_names=[partition_names],
                           check_items=CheckTasks.err_res, check_task=error)
```
```
[2021-06-24 11:31:44,880 - ERROR - ci_test]: Traceback (most recent call last):
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/client/stub.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/client/stub.py", line 1117, in query
    return handler.query(collection_name, expr, output_fields, partition_names, timeout=timeout)
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 73, in handler
    raise e
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 55, in handler
    return func(self, *args, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 1011, in query
    response = future.result()
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/grpc/_channel.py", line 624, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1624505492.820053399","description":"Error received from peer ipv4:172.18.255.155:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}"
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus 2.0a1.dev47
 pymilvus-orm 2.0a1.dev52
 image tag: master-20210623-dca24f3

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by fishpenguin** [comment]
I'm working on it...

**Comment by fishpenguin** [comment]
Cannot reproduce, pls check again...

**Comment by cydrain** [comment]
Raise exception as expected:
PartitionName: xxx not found
