### ISSUE TITLE
No exception is thrown when create schema with two primary fields

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#6093]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
    def test_collection_multi_primary_fields(self):
        """
        target: test collection with multi primary
        method: collection with two primary fields
        expected: raise exception
        """
        self._connect()
        int_field_one = cf.gen_int64_field(is_primary=True)
        int_field_two = cf.gen_int64_field(name="int2", is_primary=True)
        # error = {ct.err_code: 0, ct.err_msg: "Primary key field can only be one"}
        schema, _ = self.collection_schema_wrap.init_collection_schema(fields=[int_field_one, int_field_two,
                                                                               cf.gen_float_vec_field()])
```
```
{"auto_id": false, "description": "", "fields": [{"name": "int64", "description": "", "type": 5, "is_primary": true, "auto_id": null}, {"name": "int2", "description": "", "type": 5, "is_primary": true, "auto_id": false}, {"name": "float_vector", "description": "", "type": 101, "params": {"dim": 128}}]} (test_collection.py:579)
```
If create a collection with this schema, the exception is:
```
[2021-06-24 19:26:48,427 - ERROR - ci_test]: Traceback (most recent call last):
  File "/home/zong/zong/projects/milvus/tests20/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/utils/api_request.py", line 41, in api_request
    return func(*arg, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus_orm/collection.py", line 122, in __init__
    conn.create_collection(self._name, fields=schema.to_dict())
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/client/stub.py", line 63, in handler
    raise e
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/client/stub.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/client/stub.py", line 229, in create_collection
    return handler.create_collection(collection_name, fields, timeout, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 78, in handler
    raise e
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 55, in handler
    return func(self, *args, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 358, in create_collection
    request = Prepare.create_collection_request(collection_name, fields, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/venv/lib/python3.8/site-packages/pymilvus/client/prepare.py", line 97, in create_collection_request
    field_schema.autoID = auto_id
TypeError: None has type NoneType, but expected one of: int, long, bool
 (api_request.py:22)
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus              2.0a1.dev47
 pymilvus-orm          2.0a1.dev54
```
Built:     Thu Jun 24 07:42:18 UTC 2021
GitCommit: 133814b
```

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
It has been fixed. Please retest it. @ThreadDao

**Comment by ThreadDao** [comment]
fixed and will close
