### ISSUE TITLE
Create index failed with msg: core context done, context canceled

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#6106]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
2021-06-25 00:02:16,127 - milvus_benchmark.main:120 - ERROR - Traceback (most recent call last):
  File "main.py", line 88, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/accuracy.py", line 244, in prepare
    self.milvus.create_index(index_field_name, index_type, metric_type, index_param=index_param)
  File "/src/milvus_benchmark/client.py", line 46, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 260, in create_index
    self._milvus.create_index(self._collection_name, field_name, index_params, _async=_async)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 63, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 749, in create_index
    return handler.create_index(collection_name, field_name, params, timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 63, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 55, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 720, in create_index
    raise BaseException(status.error_code, status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=CreateIndex failed, error = core context done, context ca
nceled)>
```
**Steps/Code to reproduce behavior**
argo branch on zilliztech/milvus_benchmark
metric_type : IP

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by del-zhenwu** [comment]
still existed
/milestone 2.0.0-RC1

**Comment by neza2017** [comment]
@del-zhenwu  please provide log file, and describe how to reproduce it?

**Comment by del-zhenwu** [comment]
still failed in nightly benchmark test.
https://argo-test.zilliz.cc/workflows/qa/benchmark-cron-1626458400?tab=workflow&nodeId=benchmark-cron-1626458400-1860241766
logs:
https://kibana-dev.zilliz.cc/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-16T23:30:00.000Z',to:'2021-07-17T00:30:00.000Z'))&_a=(columns:!(log),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:ad1e1c50-c9d9-11eb-9e1a-b3dcad9693fd,key:kubernetes.pod_name,negate:!f,params:!(benchmark-cron-1626458400-1-milvus-standalone-77fb978446-kxdf7),type:phrases,value:benchmark-cron-1626458400-1-milvus-standalone-77fb978446-kxdf7),query:(bool:(minimum_should_match:1,should:!((match_phrase:(kubernetes.pod_name:benchmark-cron-1626458400-1-milvus-standalone-77fb978446-kxdf7))))))),hideChart:!f,index:ad1e1c50-c9d9-11eb-9e1a-b3dcad9693fd,interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',desc)))

**Comment by xiaocai2333** [comment]
The log seems to be out of date, can you reproduce it again? @del-zhenwu
