### ISSUE TITLE
Error message returns back to previous unmeaningful one when search with limit = 0

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#6170]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Error message returns back to previous unmeaningful one when search with limit = 0

**Steps/Code to reproduce behavior**
Run test case:
tests20/python_client/testcases/test_search.py::TestCollectionSearch::test_search_param_invalid_limit

returns: division by zero

>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, 0, "int64 >= 0")

Addr [172.18.255.155:19530] search_with_expression
Excepted error: division by zero
	{'API start': '2021-06-28 06:54:00.738359', 'RPC start': '2021-06-28 06:54:00.739799', 'Exception': '2021-06-28 06:54:00.749534'}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pymilvus_orm/collection.py", line 617, in search
    partition_names, output_fields, timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 63, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 1042, in search_with_expression
    return handler.search_with_expression(collection_name, data, anns_field, param, limit, expression, partition_names, output_fields, timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 78, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 55, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 92, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 618, in search_with_expression
    partition_names, output_fields, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/prepare.py", line 540, in search_requests_with_expr
    max_nq_per_batch = (5 * 1024 * 1024) / (bytes_per_vector * limit * factor)
ZeroDivisionError: division by zero

**Expected behavior**
limit must be greater than 0

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
- milvus master
- Name: pymilvus
Version: 2.0a1.dev53
Name: pymilvus-orm
Version: 2.0a1.dev59

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xige-16** [comment]
pymilvus should check the value of limit.

**Comment by binbinlv** [comment]
Verified in the following version, and it is fixed reporting "`limit` value 0 is illegal"

milvus-master (latest)
Name: pymilvus-orm
Version: 2.0.0rc2.dev10
Name: pymilvus
Version: 2.0.0rc2.dev4

Results:
[2021-06-30 08:53:13,947 - INFO - ci_test]: test_search_param_invalid_limit: searching with invalid limit (topK) = 0 (test_search.py:243)
...
[Milvus API Exception]<function api_request at 0x7f99bec8e7b8>: `limit` value 0 is illegal (api_request.py:25)
