### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by anhuaxiang** [milvus-io/milvus#6199]
**Please state your issue using the following template and, most importantly, in English.**

**Location of incorrect documentation**
Provide links and line numbers if applicable.

**Describe the problems or issues found in the documentation**
A clear and concise description of what you found to be incorrect.

**Steps taken to verify documentation is incorrect**
List any steps you have taken:

**Suggested fix for documentation**
Detail proposed changes to fix the documentation if you have any.

Follow the steps in the documentation [url](https://milvus.io/cn/docs/v2.0.0/hellomilvus.md)   
error message
```
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/yanrujing/Desktop/workspace/code/milvus_11/a.py", line 15, in <module>
    default_schema = schema.CollectionSchema(fields=default_fields, description="test collection")
  File "/Users/yanrujing/anaconda3/envs/milvus2/lib/python3.7/site-packages/pymilvus_orm/schema.py", line 52, in __init__
    raise PrimaryKeyException(0, ExceptionsMessage.PrimaryKeyNotExist)
pymilvus_orm.exceptions.PrimaryKeyException: <PrimaryKeyException: (code=0, message=Primary field must in dataframe.)>
python-BaseException
```

Modify the code 
```
default_fields = [
    schema.FieldSchema(name="count", dtype=DataType.INT64, is_primary=True),
    schema.FieldSchema(name="score", dtype=DataType.FLOAT),
    schema.FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
]
```
error message
```
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/yanrujing/Desktop/workspace/code/milvus_11/a.py", line 18, in <module>
    collection.insert([[i for i in range(nb)], [float(i) for i in range(nb)], vectors])
  File "/Users/yanrujing/anaconda3/envs/milvus2/lib/python3.7/site-packages/pymilvus_orm/collection.py", line 533, in insert
    raise SchemaNotReadyException(0, ExceptionsMessage.TypeOfDataAndSchemaInconsistent)
pymilvus_orm.exceptions.SchemaNotReadyException: <SchemaNotReadyException: (code=0, message=The types of schema and data do not match.)>
python-BaseException
```

**Comment by XuanYang-cn** [comment]
@anhuaxiang Thanks for pointing out the bug
/assign

**Comment by XuanYang-cn** [comment]
@anhuaxiang The `example.py` in https://github.com/milvus-io/pymilvus-orm/examples/ is the latest runnable example. 

The bug in the documentation will be fixed soon.

**Comment by XuanYang-cn** [comment]
Fixed and closing this issue.
