### ISSUE TITLE
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=syncTimeStamp Failed:state code = Initializing)>

### ISSUE THREAD

**Issue by anhuaxiang** [milvus-io/milvus#6236]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)  
   milvusdb/milvus:v2.0.0-rc1-20210628-b87baa1
- pymilvus-orm version
  2.0.0rc1

## The code reports an error after running for a while

####code :
```
import numpy as np
import pymilvus_orm
from pymilvus_orm import Collection, CollectionSchema, FieldSchema, DataType
import time


create_collection = True
dim = 2048
nb = 3000
n_list = 6000
client = pymilvus_orm.connections.connect(host='127.0.0.1', port=32191)
collections = ['main']

if create_collection:
    for co in collections:

        fields = [
            FieldSchema(name="id", dtype=DataType.INT64, is_primary=True),
            FieldSchema(name=co, dtype=DataType.FLOAT_VECTOR, dim=dim),
        ]

        schema = CollectionSchema(fields=fields, description=f"{co} schema")
        collection = Collection(name=co, schema=schema)

        index = {"index_type": "IVF_SQ8", "params": {"nlist": n_list}, "metric_type": "L2"}
        collection.create_index(field_name=co, index_params=index)
        collection.load()


batch = 1000
n_batch = 1000
for i in range(n_batch):

    print(f'range: [{i * batch}, {(i + 1) * batch}]')
    ids = list(range(i * batch, batch * (i + 1)))
    vectors = np.random.random([batch, dim]).tolist()

    entities = [ids, vectors]
    for co in collections:
        collection = Collection(co)

        print(f'insert {co} ...')
        s = time.time()
        collection.insert(entities)
        print(f'insert {co} success, time: {time.time() - s}')
        s = time.time()
        client.flush([co])
        print(f'flush {co} success, time: {time.time() - s}')

```

#### error message:
```
Addr [10.3.7.158:32191] get_persistent_segment_infos
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "keepalive watchdog timeout"
	debug_error_string = "{"created":"@1625055965.848295000","description":"Error received from peer ipv4:10.3.7.158:32191","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"keepalive watchdog timeout","grpc_status":14}"
>
	{'API start': '2021-06-30 20:24:49.460661', 'RPC start': '2021-06-30 20:24:49.461148', 'RPC error': '2021-06-30 20:26:05.850313'}

Addr [10.3.7.158:32191] _wait_for_flushed
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "keepalive watchdog timeout"
	debug_error_string = "{"created":"@1625055965.848295000","description":"Error received from peer ipv4:10.3.7.158:32191","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"keepalive watchdog timeout","grpc_status":14}"
>
	{'API start': '2021-06-30 20:24:47.829395', 'RPC start': '2021-06-30 20:24:47.829613', 'RPC error': '2021-06-30 20:26:05.852844'}

Addr [10.3.7.158:32191] flush
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "keepalive watchdog timeout"
	debug_error_string = "{"created":"@1625055965.848295000","description":"Error received from peer ipv4:10.3.7.158:32191","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"keepalive watchdog timeout","grpc_status":14}"
>
	{'API start': '2021-06-30 20:24:47.791962', 'RPC start': '2021-06-30 20:24:47.792296', 'RPC error': '2021-06-30 20:26:05.852964'}
Retry to connect server 10.3.7.158:32191 failed.
Traceback (most recent call last):
  File "/Users/yanrujing/anaconda3/envs/milvus2/lib/python3.7/site-packages/pymilvus/client/stub.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/Users/yanrujing/anaconda3/envs/milvus2/lib/python3.7/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/Users/yanrujing/anaconda3/envs/milvus2/lib/python3.7/site-packages/pymilvus/client/stub.py", line 900, in flush
    return handler.flush(collection_names, timeout, **kwargs)
  File "/Users/yanrujing/anaconda3/envs/milvus2/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 73, in handler
    raise e
  File "/Users/yanrujing/anaconda3/envs/milvus2/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 55, in handler
    return func(self, *args, **kwargs)
  File "/Users/yanrujing/anaconda3/envs/milvus2/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 978, in flush
    self._wait_for_flushed(collection_name, lambda: future.result().coll_segIDs[collection_name].data)
  File "/Users/yanrujing/anaconda3/envs/milvus2/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 73, in handler
    raise e
  File "/Users/yanrujing/anaconda3/envs/milvus2/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 55, in handler
    return func(self, *args, **kwargs)
  File "/Users/yanrujing/anaconda3/envs/milvus2/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 949, in _wait_for_flushed
    if flushed(first_segment_ids):
  File "/Users/yanrujing/anaconda3/envs/milvus2/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 934, in flushed
    infos = self.get_persistent_segment_infos(collection_name, timeout, **kwargs)
  File "/Users/yanrujing/anaconda3/envs/milvus2/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 73, in handler
    raise e
  File "/Users/yanrujing/anaconda3/envs/milvus2/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 55, in handler
    return func(self, *args, **kwargs)
  File "/Users/yanrujing/anaconda3/envs/milvus2/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 925, in get_persistent_segment_infos
    response = future.result()
  File "/Users/yanrujing/anaconda3/envs/milvus2/lib/python3.7/site-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "keepalive watchdog timeout"
	debug_error_string = "{"created":"@1625055965.848295000","description":"Error received from peer ipv4:10.3.7.158:32191","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"keepalive watchdog timeout","grpc_status":14}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yanrujing/anaconda3/envs/milvus2/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 329, in ping
    ft.result(timeout=timeout)
  File "/Users/yanrujing/anaconda3/envs/milvus2/lib/python3.7/site-packages/grpc/_utilities.py", line 140, in result
    self._block(timeout)
  File "/Users/yanrujing/anaconda3/envs/milvus2/lib/python3.7/site-packages/grpc/_utilities.py", line 86, in _block
    raise grpc.FutureTimeoutError()
grpc.FutureTimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yanrujing/Desktop/workspace/code/milvus_11/a.py", line 47, in <module>
    client.flush([co])
  File "/Users/yanrujing/anaconda3/envs/milvus2/lib/python3.7/site-packages/pymilvus/client/stub.py", line 61, in handler
    self._update_connection_pool()
  File "/Users/yanrujing/anaconda3/envs/milvus2/lib/python3.7/site-packages/pymilvus/client/stub.py", line 169, in _update_connection_pool
    self._pool = SingletonThreadPool(self._pool_uri, **self._pool_kwargs)
  File "/Users/yanrujing/anaconda3/envs/milvus2/lib/python3.7/site-packages/pymilvus/client/pool.py", line 231, in __init__
    self._prepare()
  File "/Users/yanrujing/anaconda3/envs/milvus2/lib/python3.7/site-packages/pymilvus/client/pool.py", line 236, in _prepare
    conn.client().ping()
  File "/Users/yanrujing/anaconda3/envs/milvus2/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 341, in ping
    raise NotConnectError('Fail connecting to server on {}. Timeout'.format(self._uri))
pymilvus.client.exceptions.NotConnectError: Fail connecting to server on 127.0.0.1:32191. Timeout
```

#### proxy log
```
[2021/06/30 12:29:50.476 +00:00] [WARN] [channels_time_ticker.go:96] ["Proxy channelsTimeTickerImpl failed to get ts from tso"] [error="syncTimeStamp Failed:state code = Initializing"]
[2021/06/30 12:29:50.476 +00:00] [WARN] [channels_time_ticker.go:164] [channelsTimeTickerImpl.tickLoop] [error="syncTimeStamp Failed:state code = Initializing"]
[2021/06/30 12:29:50.576 +00:00] [WARN] [channels_time_ticker.go:96] ["Proxy channelsTimeTickerImpl failed to get ts from tso"] [error="syncTimeStamp Failed:state code = Initializing"]
[2021/06/30 12:29:50.576 +00:00] [WARN] [channels_time_ticker.go:164] [channelsTimeTickerImpl.tickLoop] [error="syncTimeStamp Failed:state code = Initializing"]
[2021/06/30 12:29:50.674 +00:00] [WARN] [timetick.go:116] ["timeTick error"]
[2021/06/30 12:29:50.676 +00:00] [WARN] [proxy.go:280] ["Failed to get timestamp from tso"] [error="syncTimeStamp Failed:state code = Initializing"]
[2021/06/30 12:29:50.676 +00:00] [WARN] [channels_time_ticker.go:96] ["Proxy channelsTimeTickerImpl failed to get ts from tso"] [error="syncTimeStamp Failed:state code = Initializing"]
[2021/06/30 12:29:50.676 +00:00] [WARN] [channels_time_ticker.go:164] [channelsTimeTickerImpl.tickLoop] [error="syncTimeStamp Failed:state code = Initializing"]
```

#### querynode log
```

    __  _________ _   ____  ______
   /  |/  /  _/ /| | / / / / / __/
  / /|_/ // // /_| |/ / /_/ /\ \
 /_/  /_/___/____/___/\____/___/

Welcome to use Milvus!
Version:   b87baa1
Built:     Mon Jun 28 07:30:31 UTC 2021
GitCommit: b87baa1
GoVersion: go version go1.15.2 linux/amd64

open pid file: /run/milvus/querynode.pid
lock pid file: /run/milvus/querynode.pid
[2021/06/30 12:39:24.950 +00:00] [INFO] [logger.go:48] ["parsed scheme: \"endpoint\""]
[2021/06/30 12:39:24.951 +00:00] [INFO] [logger.go:48] ["ccResolverWrapper: sending new addresses to cc: [{etcd.etcd.svc.cluster.local:2379  <nil> 0 <nil>}]"]
[2021/06/30 12:39:25.014 +00:00] [INFO] [logger.go:48] ["parsed scheme: \"endpoint\""]
[2021/06/30 12:39:25.014 +00:00] [INFO] [logger.go:48] ["ccResolverWrapper: sending new addresses to cc: [{etcd.etcd.svc.cluster.local:2379  <nil> 0 <nil>}]"]
panic: All attempts results:
attempt #1:number of querycoord is incorrect, 0
attempt #2:number of querycoord is incorrect, 0
attempt #3:number of querycoord is incorrect, 0
attempt #4:number of querycoord is incorrect, 0
attempt #5:number of querycoord is incorrect, 0
attempt #6:number of querycoord is incorrect, 0
attempt #7:number of querycoord is incorrect, 0
attempt #8:number of querycoord is incorrect, 0
attempt #9:number of querycoord is incorrect, 0
attempt #10:number of querycoord is incorrect, 0
attempt #11:number of querycoord is incorrect, 0
attempt #12:number of querycoord is incorrect, 0
attempt #13:number of querycoord is incorrect, 0
attempt #14:number of querycoord is incorrect, 0
attempt #15:number of querycoord is incorrect, 0
attempt #16:number of querycoord is incorrect, 0
attempt #17:number of querycoord is incorrect, 0
attempt #18:number of querycoord is incorrect, 0
attempt #19:number of querycoord is incorrect, 0
attempt #20:number of querycoord is incorrect, 0


goroutine 14 [running]:
github.com/milvus-io/milvus/internal/distributed/querynode.(*Server).init(0xc000334070, 0xc000334000, 0x0)
	/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/service.go:114 +0x2efb
github.com/milvus-io/milvus/internal/distributed/querynode.(*Server).Run(0xc000334070, 0xffffffffffffffff, 0x24f79a0)
	/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/service.go:282 +0x2f
github.com/milvus-io/milvus/cmd/components.(*QueryNode).Run(...)
	/go/src/github.com/milvus-io/milvus/cmd/components/query_node.go:42
github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runQueryNode.func1(0x0, 0x0, 0xc0002e7900, 0x24f7020, 0xc00013dc00, 0xc000118f60, 0xc000322490)
	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:185 +0x13d
created by github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runQueryNode
	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:169 +0xcd
```

#### querycoord log
```
[2021/06/30 12:39:25.036 +00:00] [INFO] [logger.go:48] ["ClientConn switching balancer to \"pick_first\""]
[2021/06/30 12:39:25.036 +00:00] [INFO] [logger.go:48] ["pickfirstBalancer: HandleSubConnStateChange: 0xc0002061c0, {CONNECTING <nil>}"]
[2021/06/30 12:39:25.037 +00:00] [INFO] [logger.go:48] ["pickfirstBalancer: HandleSubConnStateChange: 0xc0002061c0, {READY <nil>}"]
[2021/06/30 12:39:43.461 +00:00] [INFO] [logger.go:48] ["pickfirstBalancer: HandleSubConnStateChange: 0xc0002061c0, {CONNECTING <nil>}"]
[2021/06/30 12:39:43.461 +00:00] [INFO] [logger.go:48] ["transport: loopyWriter.run returning. connection error: desc = \"transport is closing\""]
[2021/06/30 12:39:43.461 +00:00] [WARN] [logger.go:51] ["grpc: addrConn.createTransport failed to connect to {172.27.0.105:21123  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 172.27.0.105:21123: connect: connection refused\". Reconnecting..."]
[2021/06/30 12:39:43.461 +00:00] [INFO] [logger.go:48] ["pickfirstBalancer: HandleSubConnStateChange: 0xc0002061c0, {TRANSIENT_FAILURE connection error: desc = \"transport: Error while dialing dial tcp 172.27.0.105:21123: connect: connection refused\"}"]
[2021/06/30 12:39:44.461 +00:00] [INFO] [logger.go:48] ["pickfirstBalancer: HandleSubConnStateChange: 0xc0002061c0, {CONNECTING <nil>}"]
[2021/06/30 12:39:44.462 +00:00] [WARN] [logger.go:51] ["grpc: addrConn.createTransport failed to connect to {172.27.0.105:21123  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 172.27.0.105:21123: connect: connection refused\". Reconnecting..."]
[2021/06/30 12:39:44.462 +00:00] [INFO] [logger.go:48] ["pickfirstBalancer: HandleSubConnStateChange: 0xc0002061c0, {TRANSIENT_FAILURE connection error: desc = \"transport: Error while dialing dial tcp 172.27.0.105:21123: connect: connection refused\"}"]
[2021/06/30 12:39:45.761 +00:00] [INFO] [logger.go:48] ["pickfirstBalancer: HandleSubConnStateChange: 0xc0002061c0, {CONNECTING <nil>}"]
[2021/06/30 12:39:45.761 +00:00] [WARN] [logger.go:51] ["grpc: addrConn.createTransport failed to connect to {172.27.0.105:21123  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 172.27.0.105:21123: connect: connection refused\". Reconnecting..."]
[2021/06/30 12:39:45.762 +00:00] [INFO] [logger.go:48] ["pickfirstBalancer: HandleSubConnStateChange: 0xc0002061c0, {TRANSIENT_FAILURE connection error: desc = \"transport: Error while dialing dial tcp 172.27.0.105:21123: connect: connection refused\"}"]
[2021/06/30 12:39:48.618 +00:00] [INFO] [logger.go:48] ["pickfirstBalancer: HandleSubConnStateChange: 0xc0002061c0, {CONNECTING <nil>}"]
[2021/06/30 12:39:48.619 +00:00] [WARN] [logger.go:51] ["grpc: addrConn.createTransport failed to connect to {172.27.0.105:21123  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 172.27.0.105:21123: connect: connection refused\". Reconnecting..."]
[2021/06/30 12:39:48.619 +00:00] [INFO] [logger.go:48] ["pickfirstBalancer: HandleSubConnStateChange: 0xc0002061c0, {TRANSIENT_FAILURE connection error: desc = \"transport: Error while dialing dial tcp 172.27.0.105:21123: connect: connection refused\"}"]
[2021/06/30 12:39:52.539 +00:00] [INFO] [logger.go:48] ["pickfirstBalancer: HandleSubConnStateChange: 0xc0002061c0, {CONNECTING <nil>}"]
[2021/06/30 12:39:52.540 +00:00] [WARN] [logger.go:51] ["grpc: addrConn.createTransport failed to connect to {172.27.0.105:21123  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 172.27.0.105:21123: connect: connection refused\". Reconnecting..."]
[2021/06/30 12:39:52.540 +00:00] [INFO] [logger.go:48] ["pickfirstBalancer: HandleSubConnStateChange: 0xc0002061c0, {TRANSIENT_FAILURE connection error: desc = \"transport: Error while dialing dial tcp 172.27.0.105:21123: connect: connection refused\"}"]
```

**Comment by godchen0212** [comment]
@anhuaxiang We need querynode log.

**Comment by anhuaxiang** [comment]
querynode的日志上面有的 @godchen0212

**Comment by godchen0212** [comment]
根据日志
[2021/06/30 12:39:24.950 +00:00] 这时候querynode因为找不到querycoord已经挂掉了
[2021/06/30 12:39:43.461 +00:00] querycoord去连接querynode连接不上
中间差了19秒
querynode没有重启过吧

**Comment by anhuaxiang** [comment]
![image](https://user-images.githubusercontent.com/26645743/124071657-46918180-da72-11eb-904f-3d1d1fc1ae66.png)
重启了

**Comment by anhuaxiang** [comment]
@godchen0212 这是发生错误时，querynode完整的日志

```
 kubectl -n milvus2 logs -f milvus2-querynode-77b47c9748-cszj6

    __  _________ _   ____  ______
   /  |/  /  _/ /| | / / / / / __/
  / /|_/ // // /_| |/ / /_/ /\ \
 /_/  /_/___/____/___/\____/___/

Welcome to use Milvus!
Version:   b87baa1
Built:     Mon Jun 28 07:30:31 UTC 2021
GitCommit: b87baa1
GoVersion: go version go1.15.2 linux/amd64

open pid file: /run/milvus/querynode.pid
lock pid file: /run/milvus/querynode.pid
[2021/07/01 06:07:10.817 +00:00] [INFO] [logger.go:48] ["parsed scheme: \"endpoint\""]
[2021/07/01 06:07:10.817 +00:00] [INFO] [logger.go:48] ["ccResolverWrapper: sending new addresses to cc: [{etcd.etcd.svc.cluster.local:2379  <nil> 0 <nil>}]"]
[2021/07/01 06:07:10.830 +00:00] [INFO] [logger.go:48] ["parsed scheme: \"endpoint\""]
[2021/07/01 06:07:10.830 +00:00] [INFO] [logger.go:48] ["ccResolverWrapper: sending new addresses to cc: [{etcd.etcd.svc.cluster.local:2379  <nil> 0 <nil>}]"]
[2021/07/01 06:07:10.833 +00:00] [INFO] [logger.go:48] ["parsed scheme: \"\""]
[2021/07/01 06:07:10.833 +00:00] [INFO] [logger.go:48] ["scheme \"\" not registered, fallback to default scheme"]
[2021/07/01 06:07:10.833 +00:00] [INFO] [logger.go:48] ["ccResolverWrapper: sending update to cc: {[{milvus2-querycoord:19531  <nil> 0 <nil>}] <nil> <nil>}"]
[2021/07/01 06:07:10.833 +00:00] [INFO] [logger.go:48] ["ClientConn switching balancer to \"pick_first\""]
[2021/07/01 06:07:10.834 +00:00] [INFO] [logger.go:48] ["pickfirstBalancer: HandleSubConnStateChange: 0xc0000e0520, {CONNECTING <nil>}"]
[2021/07/01 06:07:11.868 +00:00] [WARN] [logger.go:51] ["grpc: addrConn.createTransport failed to connect to {milvus2-querycoord:19531  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 172.27.255.193:19531: connect: connection refused\". Reconnecting..."]
[2021/07/01 06:07:11.868 +00:00] [INFO] [logger.go:48] ["pickfirstBalancer: HandleSubConnStateChange: 0xc0000e0520, {TRANSIENT_FAILURE connection error: desc = \"transport: Error while dialing dial tcp 172.27.255.193:19531: connect: connection refused\"}"]
[2021/07/01 06:07:13.035 +00:00] [INFO] [logger.go:48] ["parsed scheme: \"\""]
[2021/07/01 06:07:13.035 +00:00] [INFO] [logger.go:48] ["scheme \"\" not registered, fallback to default scheme"]
[2021/07/01 06:07:13.035 +00:00] [INFO] [logger.go:48] ["ccResolverWrapper: sending update to cc: {[{milvus2-querycoord:19531  <nil> 0 <nil>}] <nil> <nil>}"]
[2021/07/01 06:07:13.035 +00:00] [INFO] [logger.go:48] ["ClientConn switching balancer to \"pick_first\""]
[2021/07/01 06:07:13.035 +00:00] [INFO] [logger.go:48] ["pickfirstBalancer: HandleSubConnStateChange: 0xc0002941c0, {CONNECTING <nil>}"]
[2021/07/01 06:07:13.036 +00:00] [INFO] [logger.go:48] ["pickfirstBalancer: HandleSubConnStateChange: 0xc0002941c0, {READY <nil>}"]
[2021/07/01 06:07:15.613 +00:00] [INFO] [logger.go:48] ["parsed scheme: \"endpoint\""]
[2021/07/01 06:07:15.613 +00:00] [INFO] [logger.go:48] ["ccResolverWrapper: sending new addresses to cc: [{etcd.etcd.svc.cluster.local:2379  <nil> 0 <nil>}]"]
[2021/07/01 06:07:15.617 +00:00] [INFO] [logger.go:48] ["parsed scheme: \"\""]
[2021/07/01 06:07:15.617 +00:00] [INFO] [logger.go:48] ["scheme \"\" not registered, fallback to default scheme"]
[2021/07/01 06:07:15.617 +00:00] [INFO] [logger.go:48] ["ccResolverWrapper: sending update to cc: {[{milvus2-rootcoord:53100  <nil> 0 <nil>}] <nil> <nil>}"]
[2021/07/01 06:07:15.617 +00:00] [INFO] [logger.go:48] ["ClientConn switching balancer to \"pick_first\""]
[2021/07/01 06:07:15.617 +00:00] [INFO] [logger.go:48] ["pickfirstBalancer: HandleSubConnStateChange: 0xc0000227a0, {CONNECTING <nil>}"]
[2021/07/01 06:07:15.619 +00:00] [INFO] [logger.go:48] ["pickfirstBalancer: HandleSubConnStateChange: 0xc0000227a0, {READY <nil>}"]
[2021/07/01 06:07:28.033 +00:00] [INFO] [logger.go:48] ["parsed scheme: \"endpoint\""]
[2021/07/01 06:07:28.033 +00:00] [INFO] [logger.go:48] ["ccResolverWrapper: sending new addresses to cc: [{etcd.etcd.svc.cluster.local:2379  <nil> 0 <nil>}]"]
[2021/07/01 06:07:28.038 +00:00] [INFO] [logger.go:48] ["parsed scheme: \"\""]
[2021/07/01 06:07:28.038 +00:00] [INFO] [logger.go:48] ["scheme \"\" not registered, fallback to default scheme"]
[2021/07/01 06:07:28.038 +00:00] [INFO] [logger.go:48] ["ccResolverWrapper: sending update to cc: {[{milvus2-indexcoord:31000  <nil> 0 <nil>}] <nil> <nil>}"]
[2021/07/01 06:07:28.038 +00:00] [INFO] [logger.go:48] ["ClientConn switching balancer to \"pick_first\""]
[2021/07/01 06:07:28.038 +00:00] [INFO] [logger.go:48] ["pickfirstBalancer: HandleSubConnStateChange: 0xc000294eb0, {CONNECTING <nil>}"]
[2021/07/01 06:07:28.040 +00:00] [INFO] [logger.go:48] ["pickfirstBalancer: HandleSubConnStateChange: 0xc000294eb0, {READY <nil>}"]
[2021/07/01 06:07:28.466 +00:00] [INFO] [logger.go:48] ["parsed scheme: \"endpoint\""]
[2021/07/01 06:07:29.606 +00:00] [INFO] [logger.go:48] ["ccResolverWrapper: sending new addresses to cc: [{etcd.etcd.svc.cluster.local:2379  <nil> 0 <nil>}]"]
[2021/07/01 06:07:29.700 +00:00] [INFO] [logger.go:48] ["parsed scheme: \"\""]
[2021/07/01 06:07:29.700 +00:00] [INFO] [logger.go:48] ["scheme \"\" not registered, fallback to default scheme"]
[2021/07/01 06:07:29.700 +00:00] [INFO] [logger.go:48] ["ccResolverWrapper: sending update to cc: {[{milvus2-datacoord:13333  <nil> 0 <nil>}] <nil> <nil>}"]
[2021/07/01 06:07:29.700 +00:00] [INFO] [logger.go:48] ["ClientConn switching balancer to \"pick_first\""]
[2021/07/01 06:07:29.700 +00:00] [INFO] [logger.go:48] ["pickfirstBalancer: HandleSubConnStateChange: 0xc0005de1f0, {CONNECTING <nil>}"]
[2021/07/01 06:07:29.701 +00:00] [INFO] [logger.go:48] ["pickfirstBalancer: HandleSubConnStateChange: 0xc0005de1f0, {READY <nil>}"]
[2021/07/01 06:07:30.180 +00:00] [INFO] [logger.go:48] ["parsed scheme: \"endpoint\""]
[2021/07/01 06:07:30.180 +00:00] [INFO] [logger.go:48] ["ccResolverWrapper: sending new addresses to cc: [{etcd.etcd.svc.cluster.local:2379  <nil> 0 <nil>}]"]
FAISS hook AVX512
2021-07-01 06:07:30,194 DEBUG [default] [user@milvus2-querynode-77b47c9748-cszj6] [static milvus::Status milvus::engine::KnowhereConfig::SetSimdType(milvus::engine::KnowhereConfig::SimdType)] [../github.com/milvus-io/milvus/internal/core/src/index/knowhere/knowhere/archive/KnowhereConfig.cpp:62] [ENGINE][SetSimdType][milvus] FAISS hook AVX512
time="2021-07-01T06:07:30Z" level=info msg="[Connecting to broker]" remote_addr="pulsar://milvus2-pulsar:6650"
time="2021-07-01T06:07:30Z" level=info msg="[TCP connection established]" local_addr="172.27.0.12:60132" remote_addr="pulsar://milvus2-pulsar:6650"
time="2021-07-01T06:07:30Z" level=info msg="[Connection is ready]" local_addr="172.27.0.12:60132" remote_addr="pulsar://milvus2-pulsar:6650"
time="2021-07-01T06:07:30Z" level=info msg="[Connecting to broker]" remote_addr="pulsar://milvus2-pulsar:6650"
time="2021-07-01T06:07:30Z" level=info msg="[TCP connection established]" local_addr="172.27.0.12:60134" remote_addr="pulsar://milvus2-pulsar:6650"
time="2021-07-01T06:07:30Z" level=info msg="[Connection is ready]" local_addr="172.27.0.12:60134" remote_addr="pulsar://milvus2-pulsar:6650"
time="2021-07-01T06:07:30Z" level=info msg="[Created producer]" cnx="172.27.0.12:60134 -> 172.27.255.199:6650" producerID=1 producer_name=standalone-0-4 topic="persistent://public/default/query-node-stats"
time="2021-07-01T06:07:53Z" level=info msg="[Created producer]" cnx="172.27.0.12:60134 -> 172.27.255.199:6650" producerID=2 producer_name=standalone-0-7 topic="persistent://public/default/query-node-time-tick-0"
time="2021-07-01T06:07:53Z" level=info msg="[Connected consumer]" consumerID=1 name=tmmhd subscription=queryNode-7-426015371371941185-7040227073330123861 topic="persistent://public/default/main_426015371371941185_0"
time="2021-07-01T06:07:53Z" level=info msg="[Created consumer]" consumerID=1 name=tmmhd subscription=queryNode-7-426015371371941185-7040227073330123861 topic="persistent://public/default/main_426015371371941185_0"
time="2021-07-01T06:07:53Z" level=info msg="Broker notification of Closed consumer: 1" local_addr="172.27.0.12:60134" remote_addr="pulsar://milvus2-pulsar:6650"
time="2021-07-01T06:07:53Z" level=info msg="[Reconnecting to broker in  100ms]" consumerID=1 name=tmmhd subscription=queryNode-7-426015371371941185-7040227073330123861 topic="persistent://public/default/main_426015371371941185_0"
time="2021-07-01T06:07:53Z" level=info msg="[Created producer]" cnx="172.27.0.12:60134 -> 172.27.255.199:6650" producerID=3 producer_name=standalone-0-8 topic="persistent://public/default/query-node-time-tick-0"
time="2021-07-01T06:07:53Z" level=info msg="[Connected consumer]" consumerID=2 name=cvbjs subscription=queryNode-7-426015371371941185-4842648100451316810 topic="persistent://public/default/main_426015371371941185_1"
time="2021-07-01T06:07:53Z" level=info msg="[Created consumer]" consumerID=2 name=cvbjs subscription=queryNode-7-426015371371941185-4842648100451316810 topic="persistent://public/default/main_426015371371941185_1"
time="2021-07-01T06:07:53Z" level=info msg="Broker notification of Closed consumer: 2" local_addr="172.27.0.12:60134" remote_addr="pulsar://milvus2-pulsar:6650"
time="2021-07-01T06:07:53Z" level=info msg="[Reconnecting to broker in  100ms]" consumerID=2 name=cvbjs subscription=queryNode-7-426015371371941185-4842648100451316810 topic="persistent://public/default/main_426015371371941185_1"
time="2021-07-01T06:07:53Z" level=info msg="[Connected consumer]" consumerID=3 name=wmjoc subscription=queryNode-7-426015371371941185-2520815618638818678 topic="persistent://public/default/search-0"
time="2021-07-01T06:07:53Z" level=info msg="[Created consumer]" consumerID=3 name=wmjoc subscription=queryNode-7-426015371371941185-2520815618638818678 topic="persistent://public/default/search-0"
time="2021-07-01T06:07:53Z" level=info msg="[Created producer]" cnx="172.27.0.12:60134 -> 172.27.255.199:6650" producerID=4 producer_name=standalone-0-9 topic="persistent://public/default/searchResult-0"
time="2021-07-01T06:07:53Z" level=info msg="Broker notification of Closed consumer: 3" local_addr="172.27.0.12:60134" remote_addr="pulsar://milvus2-pulsar:6650"
time="2021-07-01T06:07:53Z" level=info msg="[Reconnecting to broker in  100ms]" consumerID=3 name=wmjoc subscription=queryNode-7-426015371371941185-2520815618638818678 topic="persistent://public/default/search-0"
time="2021-07-01T06:07:53Z" level=info msg="[Connected consumer]" consumerID=1 name=tmmhd subscription=queryNode-7-426015371371941185-7040227073330123861 topic="persistent://public/default/main_426015371371941185_0"
time="2021-07-01T06:07:53Z" level=info msg="[Reconnected consumer to broker]" consumerID=1 name=tmmhd subscription=queryNode-7-426015371371941185-7040227073330123861 topic="persistent://public/default/main_426015371371941185_0"
[2021/07/01 06:07:53.722 +00:00] [WARN] [flow_graph_filter_dm_node.go:79] ["Non supporting"] ["message type"=100]
[2021/07/01 06:07:53.722 +00:00] [WARN] [flow_graph_filter_dm_node.go:79] ["Non supporting"] ["message type"=200]
time="2021-07-01T06:07:53Z" level=info msg="[Connected consumer]" consumerID=2 name=cvbjs subscription=queryNode-7-426015371371941185-4842648100451316810 topic="persistent://public/default/main_426015371371941185_1"
time="2021-07-01T06:07:53Z" level=info msg="[Reconnected consumer to broker]" consumerID=2 name=cvbjs subscription=queryNode-7-426015371371941185-4842648100451316810 topic="persistent://public/default/main_426015371371941185_1"
[2021/07/01 06:07:53.744 +00:00] [WARN] [flow_graph_filter_dm_node.go:79] ["Non supporting"] ["message type"=100]
[2021/07/01 06:07:53.744 +00:00] [WARN] [flow_graph_filter_dm_node.go:79] ["Non supporting"] ["message type"=200]
time="2021-07-01T06:07:53Z" level=info msg="[Connected consumer]" consumerID=3 name=wmjoc subscription=queryNode-7-426015371371941185-2520815618638818678 topic="persistent://public/default/search-0"
time="2021-07-01T06:07:53Z" level=info msg="[Reconnected consumer to broker]" consumerID=3 name=wmjoc subscription=queryNode-7-426015371371941185-2520815618638818678 topic="persistent://public/default/search-0"
rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

**Comment by yanliang567** [comment]
@godchen0212 any updates for this issue?

**Comment by godchen0212** [comment]
@yanliang567 #6350 is a new feature to solve this problem.
