### ISSUE TITLE
Server crashed when loading dataset: sift-50m

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#6237]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
W
2021-06-30 18:55:38,266 - milvus_benchmark.runners.search:250 - DEBUG - 50000000
2021-06-30 18:55:38,266 - milvus_benchmark.runners.search:252 - DEBUG - Start build index for last file
2021-06-30 18:55:38,267 - milvus_benchmark.client:251 - INFO - Building index start, collection_name: sift_50m_128_l2, index_type: I
VF_FLAT, metric_type: L2
2021-06-30 18:55:38,267 - milvus_benchmark.client:253 - INFO - {'nlist': 2048}
2021-06-30 20:41:13,372 - milvus_benchmark.client:49 - DEBUG - Milvus create_index run in 6335.1s
2021-06-30 20:41:13,382 - milvus_benchmark.runners.search:256 - DEBUG - {'flush_time': 218.93, 'build_time': 6335.12}
2021-06-30 20:41:13,385 - milvus_benchmark.client:379 - DEBUG - Row count: 50000000 in collection: <sift_50m_128_l2>
2021-06-30 20:41:13,386 - milvus_benchmark.runners.search:258 - INFO - 50000000
2021-06-30 20:41:13,386 - milvus_benchmark.runners.search:259 - INFO - Start load collection
2021-06-30 20:42:42,553 - pymilvus.client.grpc_handler:72 - ERROR -
Addr [benchmark-cron-1625076000-10-milvus.qa-milvus.svc.cluster.local:19530] get_query_segment_infos
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Socket closed"
        debug_error_string = "{"created":"@1625085762.552002519","description":"Error received from peer ipv4:10.96.21.106:19530","f
ile":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
>
        {'API start': '2021-06-30 20:41:14.074992', 'RPC start': '2021-06-30 20:41:14.075021', 'RPC error': '2021-06-30 20:42:42.553
540'}
2021-06-30 20:42:42,554 - pymilvus.client.grpc_handler:72 - ERROR -
Addr [benchmark-cron-1625076000-10-milvus.qa-milvus.svc.cluster.local:19530] wait_for_loading_collection
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Socket closed"
        debug_error_string = "{"created":"@1625085762.552002519","description":"Error received from peer ipv4:10.96.21.106:19530","f
ile":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
>
        {'API start': '2021-06-30 20:41:13.569658', 'RPC start': '2021-06-30 20:41:13.569677', 'RPC error': '2021-06-30 20:42:42.554
533'}
2021-06-30 20:42:42,555 - pymilvus.client.grpc_handler:72 - ERROR -
Addr [benchmark-cron-1625076000-10-milvus.qa-milvus.svc.cluster.local:19530] load_collection
W
Addr [benchmark-cron-1625076000-10-milvus.qa-milvus.svc.cluster.local:19530] load_collection
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Socket closed"
        debug_error_string = "{"created":"@1625085762.552002519","description":"Error received from peer ipv4:10.96.21.106:19530","f
ile":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
>
        {'API start': '2021-06-30 20:41:13.386981', 'RPC start': '2021-06-30 20:41:13.386995', 'RPC error': '2021-06-30 20:42:42.555
113'}
2021-06-30 20:42:55,589 - milvus_benchmark.main:119 - ERROR - server is not healthy, please try again later
2021-06-30 20:42:55,601 - milvus_benchmark.main:120 - ERROR - Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 333, in load_collection
    return handler.load_collection("", collection_name=collection_name, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 73, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 55, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 784, in load_collection
    self.wait_for_loading_collection(collection_name)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 73, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 55, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 811, in wait_for_loading_collection
    for info in self.get_query_segment_infos(collection_name, timeout):
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 73, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 55, in handler
  return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 628, in get_query_segment_infos
    response = future.result()
  File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 625, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Socket closed"
        debug_error_string = "{"created":"@1625085762.552002519","description":"Error received from peer ipv4:10.96.21.106:19530","f
ile":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "main.py", line 88, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/search.py", line 261, in prepare
    self.milvus.load_collection()
  File "/src/milvus_benchmark/client.py", line 46, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 430, in load_collection
    return self._milvus.load_collection(collection_name, timeout=3000)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 61, in handler
    self._update_connection_pool()
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 175, in _update_connection_pool
    self._wait_for_healthy()
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 148, in _wait_for_healthy
    raise Exception("server is not healthy, please try again later")
Exception: server is not healthy, please try again later
```
**Steps/Code to reproduce behavior** 

test suite yaml:
```
{
	"config.yaml": "insert_search_performance:
		  collections:
		    -
		      milvus:
		        db_config.primary_path: /test/milvus/distribued/sift_50m_128_l2_ivf_flat
		        wal_enable: true
		      collection_name: sift_50m_128_l2
		      ni_per: 50000
		      other_fields: int1,int2,float1,double1
		      build_index: true
		      index_type: ivf_flat 
		      index_param:
		        nlist: 2048
		      run_count: 2
		      top_ks: [1, 10, 100, 1000]
		      nqs: [1, 10, 100, 200, 500, 1000, 1200]
		      filters:
		        -
		          range: \"{'range': {'float1': {'GT': -1.0, 'LT': collection_size * 0.1}}}\"
		        -
		          range: \"{'range': {'float1': {'GT': -1.0, 'LT': collection_size * 0.5}}}\"
		        -
		          range: \"{'range': {'float1': {'GT': -1.0, 'LT': collection_size * 0.9}}}\"
		      search_params:
		        -
		          nprobe: 8
		        -
		          nprobe: 32
		"
}
```

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
standalone

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by del-zhenwu** [comment]
pod logs :
https://kibana-dev.zilliz.cc/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-30T20:41:13.573Z',to:'2021-06-30T20:42:27.320Z'))&_a=(columns:!(log),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:ad1e1c50-c9d9-11eb-9e1a-b3dcad9693fd,key:kubernetes.pod_name,negate:!f,params:(query:benchmark-cron-1625076000-10-milvus-standalone-66c48fc644-bsl9z),type:phrase),query:(match_phrase:(kubernetes.pod_name:benchmark-cron-1625076000-10-milvus-standalone-66c48fc644-bsl9z)))),index:ad1e1c50-c9d9-11eb-9e1a-b3dcad9693fd,interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',desc)))

**Comment by DragonDriver** [comment]
> pod logs :
> https://kibana-dev.zilliz.cc/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-30T20:41:13.573Z',to:'2021-06-30T20:42:27.320Z'))&_a=(columns:!(log),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:ad1e1c50-c9d9-11eb-9e1a-b3dcad9693fd,key:kubernetes.pod_name,negate:!f,params:(query:benchmark-cron-1625076000-10-milvus-standalone-66c48fc644-bsl9z),type:phrase),query:(match_phrase:(kubernetes.pod_name:benchmark-cron-1625076000-10-milvus-standalone-66c48fc644-bsl9z)))),index:ad1e1c50-c9d9-11eb-9e1a-b3dcad9693fd,interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',desc)))

Sorry but I cannot access this url, can you attach the log file directly?

**Comment by del-zhenwu** [comment]
> > pod logs :
> > https://kibana-dev.zilliz.cc/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-30T20:41:13.573Z',to:'2021-06-30T20:42:27.320Z'))&_a=(columns:!(log),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:ad1e1c50-c9d9-11eb-9e1a-b3dcad9693fd,key:kubernetes.pod_name,negate:!f,params:(query:benchmark-cron-1625076000-10-milvus-standalone-66c48fc644-bsl9z),type:phrase),query:(match_phrase:(kubernetes.pod_name:benchmark-cron-1625076000-10-milvus-standalone-66c48fc644-bsl9z)))),index:ad1e1c50-c9d9-11eb-9e1a-b3dcad9693fd,interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',desc)))
> 
> Sorry but I cannot access this url, can you attach the log file directly?

openvpn need to be connected before visiting grafana/kibana

**Comment by yanliang567** [comment]
not sure, but it might be related to #7022

**Comment by wangting0128** [comment]
Not recurring
