### ISSUE TITLE
Milvus standalone crash with default config

### ISSUE THREAD

**Issue by cydrain** [milvus-io/milvus#6238]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Milvus standalone crash with default config

**Steps/Code to reproduce behavior**
```
❯ ./bin/milvus run standalone
Set runtime dir at /run/milvus failed, set it to /tmp/milvus directory

    __  _________ _   ____  ______    
   /  |/  /  _/ /| | / / / / / __/    
  / /|_/ // // /_| |/ / /_/ /\ \    
 /_/  /_/___/____/___/\____/___/     

Welcome to use Milvus!
Version:   v2.0.0-rc1-34-gff4c6c7ff
Built:     Thu Jul  1 02:01:13 UTC 2021
GitCommit: ff4c6c7ff
GoVersion: go version go1.15.8 linux/amd64

open pid file: /tmp/milvus/standalone.pid
lock pid file: /tmp/milvus/standalone.pid
[2021/07/01 10:05:31.545 +08:00] [DEBUG] [mq_factory.go:116] ["RocksmqPath=/var/lib/milvus/rdb_data"]
panic: Create dir /var/lib/milvus/rdb_data failed

goroutine 50 [running]:
github.com/milvus-io/milvus/internal/util/rocksmq/server/rocksmq.InitRocksMQ.func1()
	/home/caiyd/vec/milvus/internal/util/rocksmq/server/rocksmq/global_rmq.go:40 +0x2d1
sync.(*Once).doSlow(0x326a3c0, 0xc000293eb8)
	/usr/local/go/src/sync/once.go:66 +0xec
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:57
github.com/milvus-io/milvus/internal/util/rocksmq/server/rocksmq.InitRocksMQ(0xc00013db40, 0x18, 0x0, 0x0)
	/home/caiyd/vec/milvus/internal/util/rocksmq/server/rocksmq/global_rmq.go:34 +0x85
github.com/milvus-io/milvus/internal/msgstream.NewRmsFactory(0xc00013db40, 0x18, 0x1282480, 0x322d400)
	/home/caiyd/vec/milvus/internal/msgstream/mq_factory.go:117 +0xc6
github.com/milvus-io/milvus/cmd/roles.newMsgFactory(0x322d401, 0xc00013db40, 0x18, 0x1, 0x766af6)
	/home/caiyd/vec/milvus/cmd/roles/roles.go:43 +0x45
github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runRootCoord.func1(0x2398c01, 0x24fecc0, 0xc0001b8040, 0xc0003fb7d8, 0xc000684ca0)
	/home/caiyd/vec/milvus/cmd/roles/roles.go:90 +0x72
created by github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runRootCoord
	/home/caiyd/vec/milvus/cmd/roles/roles.go:82 +0xb0
```

**Expected behavior**
report error and exit

**Comment by fishpenguin** [comment]
This is an unaccepted error when milvus standalone start, so I believe we can use panic to process such error.

**Comment by cydrain** [comment]
I suggest to report error and exit.
Showing backtrace is not friendly for users.
@fishpenguin

**Comment by Shreyash-Chede** [comment]
/reopen 
I'm facing the same issue, was this issue resolved?

**Comment by xiaofan-luan** [comment]
> /reopen I'm facing the same issue, was this issue resolved?

please open a separate issue with logs and descriptions about what you did.
Thanks
