### ISSUE TITLE
[Chaos] Fail to connecto Milvus after pulsar pod deleted and restart

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#6246]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Fail to connecto Milvus after pulsar pod deleted and restart

**Steps/Code to reproduce behavior**
1. deploy Milvus 2.0 with cluster mode
2. delete pulsar pod and wait it until running
3. try to connect to Milvus

**Expected behavior**
connect to Milvus 

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by neza2017** [comment]
just like #6157 ,`milvus 2.0` assumes `etcd` and `pulsar` are reliable, so there is no `reconnect` with pulsar when it failed.

**Comment by yanliang567** [comment]
It fails to connect to Milvus if uninstall and install Milvus again: 
1. install Milvus with cluster mode
2. uninstall Milvus by 'helm uninstall -n <namespace> <release_name>'
3. install Milvus with cluster mode again

Is it caused by  pulsar is not persist data in PVC yet?

**Comment by yanliang567** [comment]
It fails to connect to Milvus if uninstall and install Milvus again: 
1. install Milvus with cluster mode
2. uninstall Milvus by 'helm uninstall -n <namespace> <release_name>'
3. install Milvus with cluster mode again

Is it caused by  pulsar is not persist data in PVC yet?

**Comment by neza2017** [comment]
Is there any operation between step 1 and step 2?
If there is no operation between step 1 and step 2, then step 3 expect to work correctly.

**Comment by yanliang567** [comment]
@neza2017 I ran some tests(create collection and insert some data) between step1 and step2

**Comment by yanliang567** [comment]
@neza2017

**Comment by ThreadDao** [comment]
This issue has not been fixed.
1. deploy a cluster Milvus
```
helm install --wait --timeout 100s --set image.all.repository=milvusdb/milvus-dev --set image.all.tag=master-latest --set cluster.enabled=true --set image.all.pullPolicy=IfNotPresent --set service.type=LoadBalancer  milvus-zong .
```
2. run `/milvus/test20/python_client/testcases/test_e2e.py` and pass
3. delete the plusar pod
`kcbectl delete pod milvus-zong-pulsar-779449cc9c-9nql6`
4. after plusar pod restart and turn running, re-run test_e2e.py
```
[2021-08-16 14:27:27,527 - DEBUG - ci_test]: (api_request)  : [Collection] args: ['e2e__0DkOCnKQ', {"auto_id": false, "description": "", "fields": [{"name": "int64", "description": "", "type": 5, "is_primary": true, "auto_id": false}, {"name": "float", "description": "", "type": 10}, {"name": "float_vector", "description": "", "type": 101, "params": {"dim": 128}}]}], kwargs: {} (api_request.py:44)
[2021-08-16 14:39:56,820 - ERROR - ci_test]: Traceback (most recent call last):
  File "/home/zong/zong/projects/milvus/tests20/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/utils/api_request.py", line 45, in api_request
    return func(*arg, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus_orm/collection.py", line 134, in __init__
    conn.create_collection(self._name, fields=schema.to_dict())
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 66, in handler
    raise e
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 52, in handler
    return func(self, *args, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 233, in create_collection
    return handler.create_collection(collection_name, fields, timeout, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    raise e
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 59, in handler
    return func(self, *args, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 377, in create_collection
    raise BaseException(status.error_code, status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=state code = Initializing)>
 (api_request.py:26)
[2021-08-16 14:39:56,821 - ERROR - ci_test]: (api_response) : <BaseException: (code=1, message=state code = Initializing)> (api_request.py:27)
```

Additional context:
1. You can view the pod logs on kibaba according to the pod name
```
milvus-zong-datacoord-7878c484f4-cgnn6       1/1     Running   0          4h34m
milvus-zong-datanode-5f95b6455c-whbfx        1/1     Running   0          4h34m
milvus-zong-etcd-0                           1/1     Running   0          4h34m
milvus-zong-indexcoord-5cc6bf68f-kzsjl       1/1     Running   0          4h34m
milvus-zong-indexnode-99577778-c42xm         1/1     Running   0          4h34m
milvus-zong-minio-8454ddbcd6-nbqj7           1/1     Running   0          4h34m
milvus-zong-proxy-7c66d8575c-jmzwr           1/1     Running   0          4h34m
milvus-zong-pulsar-779449cc9c-gjqjc          1/1     Running   3          15m
milvus-zong-querycoord-6cfd9bd646-hg86t      1/1     Running   0          4h34m
milvus-zong-querynode-85ddfc64c6-5mj7q       1/1     Running   0          4h34m
milvus-zong-rootcoord-6f49469978-f2bdw       1/1     Running   1          4h34m
```
2. You can also download the log directly
[milvus_logs.tar.gz](https://github.com/milvus-io/milvus/files/6990250/milvus_logs.tar.gz)

**Comment by sunby** [comment]
@ThreadDao This problem is fixed in rc5. Please try to reproduce it.

**Comment by ThreadDao** [comment]
I regressed this issue in version `89748ac Built:     Wed Sep  1 02:16:10 UTC 2021` and it was fixed.
