### ISSUE TITLE
Server unavailable during concurrently inserting

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#6311]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
After inserted successfully in several minutes, the client get error.
```
2021-07-05 18:14:48,352 - locust.runners:354 - INFO - Shape test updating to 100 users at 50.00 spawn rate
2021-07-05 18:14:48,384 - locust.runners:312 - DEBUG - Updating running test with 100 users, 50.00 spawn rate and wait=False
2021-07-05 18:14:48,389 - locust.runners:186 - INFO - Spawning 50 users at the rate 50 users/s (50 users already running)...
2021-07-05 18:14:48,721 - locust.runners:209 - DEBUG - 60 users spawned
2021-07-05 18:14:49,041 - locust.runners:209 - DEBUG - 70 users spawned
2021-07-05 18:14:49,398 - locust.runners:209 - DEBUG - 80 users spawned
2021-07-05 18:14:49,779 - locust.runners:209 - DEBUG - 90 users spawned
2021-07-05 18:14:50,105 - locust.runners:209 - DEBUG - 100 users spawned
2021-07-05 18:14:50,110 - locust.runners:198 - INFO - All users spawned: MyUser: 50 (100 total running)
2021-07-05 18:15:08,266 - locust.stats_logger:720 - INFO -  Name                                                          # reqs      # fails  |     Avg     Min     Max  Median  |   req/s failures/s
2021-07-05 18:15:08,271 - locust.stats_logger:722 - INFO - --------------------------------------------------------------------------------------------------------------------------------------------
2021-07-05 18:15:08,277 - locust.stats_logger:725 - INFO -  grpc insert                                                    45159     0(0.00%)  |     119      39     887     110  |  580.70    0.00
2021-07-05 18:15:08,282 - locust.stats_logger:726 - INFO - --------------------------------------------------------------------------------------------------------------------------------------------
2021-07-05 18:15:08,287 - locust.stats_logger:727 - INFO -  Aggregated                                                     45159     0(0.00%)  |     119      39     887     110  |  580.70    0.00
2021-07-05 18:15:08,294 - locust.stats_logger:728 - INFO - 
2021-07-05 18:15:26,623 - pymilvus.client.grpc_handler:72 - ERROR - 
Addr [10.98.0.14:19530] describe_collection
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1625480126.588138503","description":"Error received from peer ipv4:172.16.20.90:7890","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Socket closed","grpc_status":14}"
>
	{'API start': '2021-07-05 18:15:08.460531', 'RPC start': '2021-07-05 18:15:08.460533', 'RPC error': '2021-07-05 18:15:26.623248'}
2021-07-05 18:15:26,631 - pymilvus.client.grpc_handler:72 - ERROR - 
Addr [10.98.0.14:19530] bulk_insert
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1625480126.588138503","description":"Error received from peer ipv4:172.16.20.90:7890","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Socket closed","grpc_status":14}"
>
	{'API start': '2021-07-05 18:15:08.460520', 'RPC start': '2021-07-05 18:15:08.460526', 'RPC error': '2021-07-05 18:15:26.631015'}
2021-07-05 18:15:26,637 - pymilvus.client.grpc_handler:72 - ERROR - 
Addr [10.98.0.14:19530] describe_collection
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1625480126.588183778","description":"Error received from peer ipv4:172.16.20.90:7890","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Socket closed","grpc_status":14}"

```
**Steps/Code to reproduce behavior**
test yaml: 

```
locust_insert_performance:
  collections:
    - 
      milvus:
        db_config.primary_path: /test/milvus/db_data_011/insert_sift_1m_128_l2_2
      collection_name: local_1m_128_l2
      ni_per: 50000
      build_index: false
      index_type: ivf_sq8
      index_param:
        nlist: 1024
      task:
        load_shape: true
        step_time: 100
        step_load: 50
        spawn_rate: 50
        connection_num: 1
        clients_num: 100
        during_time: 600
        types:
          -
            type: insert
            weight: 1
            params:
              ni_per: 1

```
**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
standalone version
with pymilvus-sdk: `2.0a1.dev53`

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by del-zhenwu** [comment]
after KeyboardInterrupt:
```
^CException in thread Thread-45412:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "src/python/grpcio/grpc/_cython/_cygrpc/thread.pyx.pxi", line 58, in grpc._cython.cygrpc._run_with_context._run
  File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 1235, in channel_spin
    event = state.channel.next_call_event()
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 491, in grpc._cython.cygrpc.Channel.next_call_event
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 169, in grpc._cython.cygrpc._next_call_event
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 163, in grpc._cython.cygrpc._next_call_event
  File "src/python/grpcio/grpc/_cython/_cygrpc/completion_queue.pyx.pxi", line 63, in grpc._cython.cygrpc._latent_event
  File "src/python/grpcio/grpc/_cython/_cygrpc/completion_queue.pyx.pxi", line 42, in grpc._cython.cygrpc._next
KeyboardInterrupt

kube2021-07-05 18:16:02,045 - locust.stats_logger:720 - INFO -  Name                                                          # reqs      # fails  |     Avg     Min     Max  Median  |   req/s failures/s
2021-07-05 18:16:02,052 - locust.stats_logger:722 - INFO - --------------------------------------------------------------------------------------------------------------------------------------------
2021-07-05 18:16:02,057 - locust.stats_logger:725 - INFO -  grpc insert                                                    45266     0(0.00%)  |     122      39   18257     110  |    0.00    0.00
2021-07-05 18:16:02,062 - locust.stats_logger:726 - INFO - --------------------------------------------------------------------------------------------------------------------------------------------
2021-07-05 18:16:02,069 - locust.stats_logger:727 - INFO -  Aggregated                                                     45266     0(0.00%)  |     122      39   18257     110  |    0.00    0.00
2021-07-05 18:16:02,075 - locust.stats_logger:728 - INFO - 
2021-07-05 18:16:03,147 - milvus_benchmark.client:154 - ERROR - 'NoneType' object has no attribute 'primary_keys'
2021-07-05 18:16:03,157 - milvus_benchmark.client:154 - ERROR - 'NoneType' object has no attribute 'primary_keys'
2021-07-05 18:16:03,163 - milvus_benchmark.client:154 - ERROR - 'NoneType' object has no attribute 'primary_keys'
2021-07-05 18:16:03,170 - milvus_benchmark.client:154 - ERROR - 'NoneType' object has no attribute 'primary_keys'
2021-07-05 18:16:03,178 - milvus_benchmark.client:154 - ERROR - 'NoneType' object has no attribute 'primary_keys'
2021-07-05 18:16:03,183 - milvus_benchmark.client:154 - ERROR - 'NoneType' object has no attribute 'primary_keys'
2021-07-05 18:16:03,190 - milvus_benchmark.client:154 - ERROR - 'NoneType' object has no attribute 'primary_keys'
2021-07-05 18:16:03,196 - milvus_benchmark.client:154 - ERROR - 'NoneType' object has no attribute 'primary_keys'
2021-07-05 18:16:03,203 - milvus_benchmark.client:154 - ERROR - 'NoneType' object has no attribute 'primary_keys'
2021-07-05 18:16:03,209 - milvus_benchmark.client:154 - ERROR - 'NoneType' object has no attribute 'primary_keys'
2021-07-05 18:16:03,215 - milvus_benchmark.client:154 - ERROR - 'NoneType' object has no attribute 'primary_keys'

```
