### ISSUE TITLE
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=call query coordinator LoadCollection: rpc error: code = DeadlineExceeded desc = context deadline exceeded)>

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#6325]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
This assert occurs after running test cases for a while

ERROR    pymilvus.client.grpc_handler:grpc_handler.py:58 Error: <BaseException: (code=1, message=call query coordinator LoadCollection: rpc error: code = DeadlineExceeded desc = context deadline exceeded)>
ERROR    ci_test:api_request.py:24 Traceback (most recent call last):
  File "/milvus/tests20/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/milvus/tests20/python_client/utils/api_request.py", line 42, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus_orm/collection.py", line 438, in load
    conn.load_collection(self._name, timeout=kwargs.get("timeout", None))
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 63, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 333, in load_collection
    return handler.load_collection("", collection_name=collection_name, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 64, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 56, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 787, in load_collection
    raise BaseException(response.error_code, response.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=call query coordinator LoadCollection: rpc error: code = DeadlineExceeded desc = context deadline exceeded)>

standalone pod logs:
2021-07-06T09:09:36.4956534Z stdout F [2021/07/06 09:09:36.495 +00:00] [DEBUG] [task_scheduler.go:663] ["processActivateTaskLoop: pop a active task from activateChan"] [taskID=426131228236972618]
2021-07-06T09:09:36.4957323Z stdout F [2021/07/06 09:09:36.495 +00:00] [DEBUG] [task_scheduler.go:643] ["waitActivateTaskDone: one activate task done"] [taskID=426131228236972618]
2021-07-06T09:09:36.495757Z stdout F [2021/07/06 09:09:36.495 +00:00] [DEBUG] [task_scheduler.go:553] ["waitActivateTaskDone: activate task return err"] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [taskID=426131228236972618]

**Steps/Code to reproduce behavior**

Run tests20/python_client/testcases/test_search.py cases, and it reports error at case "test_search_concurrent_multi_threads", but if only run this case "test_search_concurrent_multi_threads", it is OK even for several times. 

And sometimes the first time run all the cases of test_search.py, it is good. And for the second time, it fails at one case including load.

So this issue may related to load operations, but the reproduce way may be different. 

**Expected behavior**
No assertion

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
milvus master: 1665484
Name: pymilvus
Version: 2.0.0rc2.dev8
Name: pymilvus-orm
Version: 2.0.0rc2.dev21

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by binbinlv** [comment]
When running CI for PR, this occurs again.

logs files:
[log.txt](https://github.com/milvus-io/milvus/files/6775310/log.txt)
[artifacts-milvus-standalone-PR-6340-1-pymilvus-orm-e2e-logs.tar.gz](https://github.com/milvus-io/milvus/files/6775322/artifacts-milvus-standalone-PR-6340-1-pymilvus-orm-e2e-logs.tar.gz)


Assertion:
[2021-07-07T07:33:01.719Z] [2021-07-07 07:32:19,998 - ERROR - ci_test]: Traceback (most recent call last):

[2021-07-07T07:33:01.719Z]   File "/milvus/tests20/python_client/utils/api_request.py", line 18, in inner_wrapper

[2021-07-07T07:33:01.719Z]     res = func(*args, **kwargs)

[2021-07-07T07:33:01.719Z]   File "/milvus/tests20/python_client/utils/api_request.py", line 42, in api_request

[2021-07-07T07:33:01.719Z]     return func(*arg, **kwargs)

[2021-07-07T07:33:01.719Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus_orm/collection.py", line 438, in load

[2021-07-07T07:33:01.719Z]     conn.load_collection(self._name, timeout=kwargs.get("timeout", None))

[2021-07-07T07:33:01.719Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 63, in handler

[2021-07-07T07:33:01.719Z]     raise e

[2021-07-07T07:33:01.719Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 51, in handler

[2021-07-07T07:33:01.719Z]     return func(self, *args, **kwargs)

[2021-07-07T07:33:01.719Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner

[2021-07-07T07:33:01.719Z]     return func(self, *args, **kwargs)

[2021-07-07T07:33:01.719Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 333, in load_collection

[2021-07-07T07:33:01.719Z]     return handler.load_collection("", collection_name=collection_name, timeout=timeout)

[2021-07-07T07:33:01.719Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 64, in handler

[2021-07-07T07:33:01.719Z]     raise e

[2021-07-07T07:33:01.719Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 56, in handler

[2021-07-07T07:33:01.719Z]     return func(self, *args, **kwargs)

[2021-07-07T07:33:01.719Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 787, in load_collection

[2021-07-07T07:33:01.719Z]     raise BaseException(response.error_code, response.reason)

[2021-07-07T07:33:01.719Z] pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=call query coordinator LoadCollection: rpc error: code = DeadlineExceeded desc = context deadline exceeded)>

**Comment by xige-16** [comment]
did you run tests20/python_client/testcases/test_search.py with only one progress? @binbinlv

**Comment by binbinlv** [comment]
Yes, both one/multiple processes

**Comment by binbinlv** [comment]
When running test cases under multiple replicas, it occurs again. (proxy: 1, querynode:2, indexnode:2, datanode:2)

Even if it will not occur each time, but when continuously running test cases, it occurs at high probability.


[2021-07-09 07:40:43,528 - ERROR - ci_test]: (api_response) : <BaseException: (code=1, message=call query coordinator LoadCollection: rpc error: code = DeadlineExceeded desc = context deadline exceeded)> (api_request.py:25)
[2021-07-09 07:40:43,575 - INFO - ci_test]: *********************************** teardown *********************************** (client_base.py:64)
[2021-07-09 07:40:45,923 - INFO - ci_test]: *********************************** setup *********************************** (client_base.py:54)
[2021-07-09 07:41:51,402 - ERROR - ci_test]: Traceback (most recent call last):
  File "/milvus/tests20/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/milvus/tests20/python_client/utils/api_request.py", line 42, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus_orm/collection.py", line 439, in load
    conn.load_collection(self._name, timeout=kwargs.get("timeout", None))
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 63, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 334, in load_collection
    return handler.load_collection("", collection_name=collection_name, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 64, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 56, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 796, in load_collection
    raise BaseException(response.error_code, response.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=call query coordinator LoadCollection: rpc error: code = DeadlineExceeded desc = context deadline exceeded)>

**Comment by xige-16** [comment]
The issue has been solved by pr #6351. Trouble you check it. @binbinlv

**Comment by binbinlv** [comment]
Verified in standalone version, and run all the test search case for 5 counts, and no such errors. And verified in cluster with multiple replicas env, no such errors appear although other errors, so close this issue.

milvus: d896e31
Name: pymilvus
Version: 2.0.0rc3.dev1
Name: pymilvus-orm
Version: 2.0.0rc3.dev4
