### ISSUE TITLE
BuildIndex from index service failed and IndexBuilding Service not available

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#6345]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**

1. deploy Milvus 2.0 with standalone mode
2. repeat the follow operations 3-5 times
     create a collection
     insert 5000 entities
     flush
     search with nq=1 and nprobe=16, limit=1
     create index with  `index_params = {"index_type": "IVF_SQ8", "metric_type": "L2", "params": {"nlist": 64}}`
     inject chaos: kill pod standalone every 3s
     after 11s delete chaos
     reconnect and verify collection, entities and index existed, query result is correct

3. standalone pod is running but create index failed
```
[2021-07-07 16:15:03,262 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['float_vector', {'index_type': 'IVF_SQ8', 'metric_type': 'L2', 'params': {'nlist': 64}}], kwargs: {'name': 'test_MBXllaII'} (api_request.py:41)
[2021-07-07 16:15:03,830 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/nausicca/projects/milvus/tests20/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/Users/nausicca/projects/milvus/tests20/python_client/utils/api_request.py", line 42, in api_request
    return func(*arg, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus_orm/collection.py", line 946, in create_index
    return conn.create_index(self._name, field_name, index_params,
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 63, in handler
    raise e
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 749, in create_index
    return handler.create_index(collection_name, field_name, params, timeout, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 63, in handler
    raise e
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 55, in handler
    return func(self, *args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 720, in create_index
    raise BaseException(status.error_code, status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=CreateIndex failed, error = BuildIndex from index service failed, error = IndexBuilding Service not available)>
 (api_request.py:24)
[2021-07-07 16:15:03,830 - ERROR - ci_test]: (api_response) : <BaseException: (code=1, message=CreateIndex failed, error = BuildIndex from index service failed, error = IndexBuilding Service not available)> (api_request.py:25)
```
4. the standalone pod 
[standalone.log](https://github.com/milvus-io/milvus/files/6775733/standalone.log)

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus                           2.0a1.dev55
 pymilvus-orm                       2.0a1.dev62
 GitCommit: 1665484

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by czs007** [comment]
I'm working on it. @ThreadDao

**Comment by czs007** [comment]
The cause of the error has been found, the following check code should be removed:

internal/indexcoord/index_coord.go
func(i *IndexCoord) BuildIndex(ctx context.Context, req *indexpb.BuildIndexRequest ...)

	if i.nodeClients == nil || i.nodeClients.Len() <= 0 {
		ret.Status.Reason = "IndexBuilding Service not available"
		return ret, nil
	}
	t.nodeClients = i.nodeClients

**Comment by ThreadDao** [comment]
This issue did not recur. I will close this issue.
