### ISSUE TITLE
Fail to load collection after the milvus standalone pod is killed and restarted

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#6352]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
scripts path: /milvus/test20/chaos/test_chaos_data_consist.py

1. deploy Milvus 2.0 with standalone mode
2. milvus operations
   

- create a collection
- insert 5000 entities
- collection.num_entities
- load
- search
- index
- query

3. inject a chaos default: kill standalone pod every 3s
4. sleep 11s and delete chaos
5. sleep 100s (wait for pod restart and server recovery)
6. milvus operations

- connect
- utility.has_collection
- num_entities
- has_index
- load
```
[2021-07-07 19:24:23,284 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None], kwargs: {} (api_request.py:41)
[2021-07-07 19:37:45,240 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 334, in load_collection
    return handler.load_collection("", collection_name=collection_name, timeout=timeout)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 74, in handler
    raise e
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 56, in handler
    return func(self, *args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 799, in load_collection
    self.wait_for_loading_collection(collection_name)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 74, in handler
    raise e
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 56, in handler
    return func(self, *args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 826, in wait_for_loading_collection
    for info in self.get_query_segment_infos(collection_name, timeout):
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 74, in handler
    raise e
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 56, in handler
    return func(self, *args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 643, in get_query_segment_infos
    response = future.result()
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/grpc/_channel.py", line 624, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Operation timed out"
	debug_error_string = "{"created":"@1625657864.234588000","description":"Error received from peer ipv4:10.98.0.7:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Operation timed out","grpc_status":14}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nausicca/projects/milvus/tests20/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/Users/nausicca/projects/milvus/tests20/python_client/utils/api_request.py", line 42, in api_request
    return func(*arg, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus_orm/collection.py", line 439, in load
    conn.load_collection(self._name, timeout=kwargs.get("timeout", None))
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 61, in handler
    self._update_connection_pool()
TypeError: _update_connection_pool() missing 1 required positional argument: 'channel'
 (api_request.py:24)
[2021-07-07 19:37:45,240 - ERROR - ci_test]: (api_response) : _update_connection_pool() missing 1 required positional argument: 'channel' (api_request.py:25)
```
 The standalone pod: 
[standalone.log](https://github.com/milvus-io/milvus/files/6777009/standalone.log)

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus                           2.0.0rc2.dev9
 pymilvus-orm                       2.0.0rc2.dev24
 GitCommit: 017484e

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by czs007** [comment]
@scsven  Please assign issue back to the author.

**Comment by scsven** [comment]
@czs007 Not fixed yet. Need publish a new pymilvus-orm and update the requirments.txt in milvus......

**Comment by scsven** [comment]
Now, this issue should be fixed, please check.

/unassign @scsven 
/assign @ThreadDao

**Comment by ThreadDao** [comment]
The issue changed. It looks like the collection was load successfully, but the search no response for 10mins.
The restarted pod's log:
[standalone1.log](https://github.com/milvus-io/milvus/files/6800468/standalone1.log)

**Comment by ThreadDao** [comment]
I was wrong. Failed to load 5000 entities after standalone pod restart. The client did not get a response after a few minutes. Now It's 10:05
```
[2021-07-13 09:56:20,496 - DEBUG - ci_test]: (api_request)  : [Collection] args: ['chaos_collection_fqAiZZVR', None], kwargs: {} (api_request.py:41)
[2021-07-13 09:56:20,531 - DEBUG - ci_test]: (api_response) : {"name": "chaos_collection_fqAiZZVR", "schema": {"auto_id": false, "description": "", "fields": [{"name": "int64", "description": "", "type": 5, "is_primary": true, "auto_id": false}, {"name": "float", "description": "", "type": 10}, {"name": "float_vector", "description": "", "type": 101, "params":......  (api_request.py:20)
[2021-07-13 09:56:20,532 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None], kwargs: {} (api_request.py:41)

Built:     Mon Jul 12 09:26:44 UTC 2021
GitCommit: 83be910
```

**Comment by scsven** [comment]
@ThreadDao Is it a new issue?

**Comment by yanliang567** [comment]
@scsven any updates ? cc @ThreadDao
