### ISSUE TITLE
Start the second milvus cluster failed with the given etcd/minio, which is used by the first milvus server

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#6363]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
[2021/07/08 03:37:37.077 +00:00] [DEBUG] [session_util.go:63] ["Session try to connect to etcd"]
[2021/07/08 03:37:37.077 +00:00] [INFO] [logger.go:48] ["parsed scheme: \"endpoint\""]
[2021/07/08 03:37:37.077 +00:00] [INFO] [logger.go:48] ["ccResolverWrapper: sending new addresses to cc: [{benchmark-gbjnl-1-etcd:2379  <nil> 0 <nil>}]"]
[2021/07/08 03:37:37.087 +00:00] [DEBUG] [session_util.go:80] ["Sessiont connect to etcd success"]
[2021/07/08 03:37:37.087 +00:00] [DEBUG] [session_util.go:109] ["Session checkIDExist Begin"]
[2021/07/08 03:37:37.096 +00:00] [DEBUG] [session_util.go:116] ["Session checkIDExist End"]
[2021/07/08 03:37:37.096 +00:00] [DEBUG] [session_util.go:121] ["Session try to get serverID"]
[2021/07/08 03:37:37.105 +00:00] [DEBUG] [session_util.go:152] ["Session get serverID success"]
panic: All attempts results:
attempt #1:function CompareAndSwap error for compare is false for key: IndexCoord
attempt #2:function CompareAndSwap error for compare is false for key: IndexCoord
attempt #3:function CompareAndSwap error for compare is false for key: IndexCoord
attempt #4:function CompareAndSwap error for compare is false for key: IndexCoord
attempt #5:function CompareAndSwap error for compare is false for key: IndexCoord
attempt #6:function CompareAndSwap error for compare is false for key: IndexCoord
attempt #7:function CompareAndSwap error for compare is false for key: IndexCoord
attempt #8:function CompareAndSwap error for compare is false for key: IndexCoord
attempt #9:function CompareAndSwap error for compare is false for key: IndexCoord
attempt #10:function CompareAndSwap error for compare is false for key: IndexCoord
attempt #11:function CompareAndSwap error for compare is false for key: IndexCoord
attempt #12:function CompareAndSwap error for compare is false for key: IndexCoord
attempt #13:function CompareAndSwap error for compare is false for key: IndexCoord
attempt #14:function CompareAndSwap error for compare is false for key: IndexCoord
attempt #15:function CompareAndSwap error for compare is false for key: IndexCoord
attempt #16:function CompareAndSwap error for compare is false for key: IndexCoord
attempt #17:function CompareAndSwap error for compare is false for key: IndexCoord
attempt #18:function CompareAndSwap error for compare is false for key: IndexCoord
attempt #19:function CompareAndSwap error for compare is false for key: IndexCoord
attempt #20:function CompareAndSwap error for compare is false for key: IndexCoord
attempt #21:function CompareAndSwap error for compare is false for key: IndexCoord
attempt #22:function CompareAndSwap error for compare is false for key: IndexCoord
attempt #23:function CompareAndSwap error for compare is false for key: IndexCoord
attempt #24:function CompareAndSwap error for compare is false for key: IndexCoord
attempt #25:function CompareAndSwap error for compare is false for key: IndexCoord
attempt #26:function CompareAndSwap error for compare is false for key: IndexCoord
attempt #27:function CompareAndSwap error for compare is false for key: IndexCoord
attempt #28:function CompareAndSwap error for compare is false for key: IndexCoord
attempt #29:function CompareAndSwap error for compare is false for key: IndexCoord
attempt #30:function CompareAndSwap error for compare is false for key: IndexCoord


goroutine 12 [running]:
github.com/milvus-io/milvus/internal/util/sessionutil.(*Session).Init(0xc00040e070, 0x23217f5, 0xa, 0xc0004112e0, 0x1e, 0x1, 0x1)
	/go/src/github.com/milvus-io/milvus/internal/util/sessionutil/session_util.go:99 +0x145
github.com/milvus-io/milvus/internal/indexcoord.(*IndexCoord).Register(0xc0002c62a0, 0xb, 0x24d0120)
	/go/src/github.com/milvus-io/milvus/internal/indexcoord/index_coord.go:103 +0xce
github.com/milvus-io/milvus/internal/distributed/indexcoord.(*Server).init(0xc0000aebe0, 0x100000000, 0xc0003b0888)
	/go/src/github.com/milvus-io/milvus/internal/distributed/indexcoord/service.go:74 +0xc5
github.com/milvus-io/milvus/internal/distributed/indexcoord.(*Server).Run(0xc0000aebe0, 0xffffffffffffffff, 0xc000123730)
	/go/src/github.com/milvus-io/milvus/internal/distributed/indexcoord/service.go:55 +0x2f
github.com/milvus-io/milvus/cmd/components.(*IndexCoord).Run(...)
	/go/src/github.com/milvus-io/milvus/cmd/components/index_coord.go:39
github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runIndexCoord.func1(0xc000375900, 0x24fbfa0, 0xc000139c40, 0xc0001232f0, 0xc0003b0880)
	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:269 +0xbf
created by github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runIndexCoord
	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:255 +0xb0

```
**Steps/Code to reproduce behavior**
Start the second milvus cluster version failed with the existed etcd/minio, which is used by the first milvus server

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaofan-luan** [comment]
Don't think this is a bug. you need to change etcd/minio/pulsar path otherwise you cant start 2 milvus clusters

**Comment by del-zhenwu** [comment]
> Don't think this is a bug. you need to change etcd/minio/pulsar path otherwise you cant start 2 milvus clusters

Minio bucket name has changed used by cluster-2, so it's different, and pulsar is independent instance for each cluster, the etcd is shared by the two clusters
This feature is supported in milvus-1.0 if using mysql as meta storage backend, multi milvus instances can connect the same mysql in the parallel testing.
This serious is used in search performance testing, with the large scale dataset, and we only load the indexed data and search in the testing process to reduce the data preparing time, each test suite will start the milvus instance

**Comment by xiaofan-luan** [comment]
we will need to change etcd path to do so. Does root path of etcd configurable right now?

**Comment by sunby** [comment]
Please change the `etcd.rootPath` in milvus.yaml and retry.

**Comment by del-zhenwu** [comment]
@jeffoverflow , we need to expose it in helm configuration for users.

**Comment by xiaofan-luan** [comment]
don't seek this is a issue? user should change milvus.yaml themselves to specify the data directory?
You definitely can't start two cluster on the same folder

**Comment by del-zhenwu** [comment]
> don't seek this is a issue? user should change milvus.yaml themselves to specify the data directory?
> You definitely can't start two cluster on the same folder

Ok, anther issue will be created to expose configurations in helm if using k8s, this issue will be closed.

**Comment by del-zhenwu** [comment]
> > don't seek this is a issue? user should change milvus.yaml themselves to specify the data directory?
> > You definitely can't start two cluster on the same folder
> 
> Ok, anther issue will be created to expose configurations in helm if using k8s, this issue will be closed.

https://github.com/milvus-io/milvus/issues/6518
