### ISSUE TITLE
Fail to query if the collection schema is set auto_id=true

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#6389]
**Describe the bug**
Fail to query if the collection schema is set auto_id=true

**Steps/Code to reproduce behavior**
dim = 128
auto_id = FieldSchema(name="auto_id", dtype=DataType.INT64, is_primary=True, description="auto primary id")
age_field = FieldSchema(name="age", dtype=DataType.INT64, description="age")
embedding_field = FieldSchema(name="embedding", dtype=DataType.FLOAT_VECTOR, dim=dim)
schema = CollectionSchema(fields=[auto_id, age_field, embedding_field],
                          auto_id=True,
                          description="desc of collection")
collection_name2 = "tutorial_2"
collection2 = Collection(name=collection_name2, schema=schema)

import random
nb = 300
ages = [random.randint(20, 40) for i in range(nb)]
embeddings = [[random.random() for _ in range(dim)] for _ in range(nb)]
entities2 = [ages, embeddings]
ins_res2 = collection2.insert(entities2)

collection2.load()
expr = f"atuo_id in {ins_res2.primary_keys[0:5]}"       # only suport query on primary field by 'in'
query_res2 = collection2.query(expr)

**Actually**
Traceback (most recent call last):
  File "/Users/yanliang/fork/pymilvus/pymilvus/client/stub.py", line 63, in handler
    raise e
  File "/Users/yanliang/fork/pymilvus/pymilvus/client/stub.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/Users/yanliang/fork/pymilvus/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/Users/yanliang/fork/pymilvus/pymilvus/client/stub.py", line 1118, in query
    return handler.query(collection_name, expr, output_fields, partition_names, timeout=timeout)
  File "/Users/yanliang/fork/pymilvus/pymilvus/client/grpc_handler.py", line 64, in handler
    raise e
  File "/Users/yanliang/fork/pymilvus/pymilvus/client/grpc_handler.py", line 56, in handler
    return func(self, *args, **kwargs)
  File "/Users/yanliang/fork/pymilvus/pymilvus/client/grpc_handler.py", line 1023, in query
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=Invalid expression!)>

- Milvus version (master or released version)
master-20210707-3387b07
pymilvus                           2.0.0rc2.dev6
pymilvus-orm                       2.0.0rc2.dev19

**Comment by yanliang567** [comment]
typo in expr....not a issue.
