### ISSUE TITLE
Search failed when insert 5000 entities and create index

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#6435]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
The test case:
```
    def test_search_index(self):
        self._connect()
        self.collection_wrap.init_collection(name="c_name", schema=cf.gen_default_collection_schema())
        data = cf.gen_default_list_data(nb=5000)
        _, res = self.collection_wrap.insert(data)
        assert self.collection_wrap.num_entities == 5000
        index_params = {"index_type": "IVF_SQ8", "metric_type": "L2", "params": {"nlist": 128}}
        index, _ = self.collection_wrap.create_index(field_name=ct.default_float_vec_field_name,
                                                     index_params=index_params)
        self.collection_wrap.load()
        search_vectors = cf.gen_vectors(1, ct.default_dim)
        search_res, _ = self.collection_wrap.search(data=search_vectors,
                                                    anns_field=ct.default_float_vec_field_name,
                                                    param={"nprobe": 16}, limit=1)
        assert len(search_res) == 1
```
I don't understand the error message
```
[2021-07-12 14:33:41,170 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.14148532853003332, 0.12144082025179778, 0.05617269927354881, 0.008602888236867369, 0.13507321999722544, 0.1460233544054538, 0.017612654491386125, 0.1303742776260651, 0.010371652376227173, 0.06989837941584721, 0.06309726931468207, 0.03674370234092817, 0.04563095782385487, 0.05735866352566732, 0......., kwargs: {} (api_request.py:41)
[2021-07-12 14:33:41,202 - ERROR - ci_test]: Traceback (most recent call last):
  File "/home/zong/zong/projects/milvus/tests20/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/utils/api_request.py", line 42, in api_request
    return func(*arg, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus_orm/collection.py", line 626, in search
    res = conn.search_with_expression(self._name, data, anns_field, param, limit, expr,
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 63, in handler
    raise e
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 1042, in search_with_expression
    return handler.search_with_expression(collection_name, data, anns_field, param, limit, expression, partition_names, output_fields, timeout, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 63, in handler
    raise e
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 55, in handler
    return func(self, *args, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 92, in handler
    return func(self, *args, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 622, in search_with_expression
    return self._execute_search_requests(requests, timeout, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 63, in handler
    raise e
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 55, in handler
    return func(self, *args, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 591, in _execute_search_requests
    raise pre_err
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 582, in _execute_search_requests
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=Search failed, C runtime error detected, error code = 1, error msg = Error in virtual milvus::knowhere::DatasetPtr milvus::knowhere:
)>
 (api_request.py:24)
[2021-07-12 14:33:41,202 - ERROR - ci_test]: (api_response) : <BaseException: (code=1, message=Search failed, C runtime error detected, error code = 1, error msg = Error in virtual milvus::knowhere::DatasetPtr milvus::knowhere:
)> (api_request.py:25)
```

error code
**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
 pymilvus              2.0.0rc2.dev12
 pymilvus-orm          2.0.0rc2.dev29
 Built:     Mon Jul 12 03:06:11 UTC 2021
 GitCommit: a8e5fd2

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xige-16** [comment]
This problem is caused by the search without specifying a metric type in search param.
        search_res, _ = self.collection_wrap.search(data=search_vectors,
                                                    anns_field=ct.default_float_vec_field_name,
                                                    param={"nprobe": 16}, limit=1)
if set the metric type in param, the test will pass:
        search_res, _ = self.collection_wrap.search(data=search_vectors,
                                                    anns_field=ct.default_float_vec_field_name,
                                                    param={"metric_type": "L2", "nprobe": 16}, limit=1)

**Comment by xige-16** [comment]
search params should be checked before search, and I suggest that proxy be responsible for checking param. @czs007

**Comment by czs007** [comment]
@ThreadDao 
It seems that this test does not deliberately test the case of incomplete parameters?
I have submitted an issuse #6804  to record the underlying problem: the proxy did not check the parameters in advance and did not return a user-friendly error message.
Here you need to modify this case and pass metric_type in the parameter `param`.

**Comment by ThreadDao** [comment]
We will adjust the related case, and this issue will be closed.
