### ISSUE TITLE
Index create failed on standalone version with error: `IndexBuilding Service not available`

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#6437]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
[2021-07-11 18:05:22,796] [    INFO] - Table: sift_128_euclidean, row count: 1000000 (milvus_benchmark.runners.accuracy:240)
[2021-07-11 18:05:22,799] [    INFO] - None (milvus_benchmark.client:276)
[2021-07-11 18:05:22,804] [    INFO] - Drop index: sift_128_euclidean (milvus_benchmark.client:287)
[2021-07-11 18:05:22,807] [    INFO] - Re-create index: sift_128_euclidean (milvus_benchmark.runners.accuracy:245)
[2021-07-11 18:05:22,808] [    INFO] - Building index start, collection_name: sift_128_euclidean, index_type: HNSW, metric_type: L2
(milvus_benchmark.client:261)
[2021-07-11 18:05:22,810] [    INFO] - {'M': 16, 'efConstruction': 500} (milvus_benchmark.client:263)
[2021-07-11 18:05:23,327] [   ERROR] - Error: <BaseException: (code=1, message=CreateIndex failed, error = BuildIndex from index ser
vice failed, error = IndexBuilding Service not available)> (pymilvus.client.grpc_handler:58)
[2021-07-11 18:05:23,344] [   ERROR] - <BaseException: (code=1, message=CreateIndex failed, error = BuildIndex from index service fa
iled, error = IndexBuilding Service not available)> (milvus_benchmark.main:115)
[2021-07-11 18:05:23,347] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 84, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/accuracy.py", line 246, in prepare
    self.milvus.create_index(index_field_name, index_type, metric_type, index_param=index_param)
  File "/src/milvus_benchmark/client.py", line 46, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 269, in create_index
    self._milvus.create_index(self._collection_name, field_name, index_params, _async=_async)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 63, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 749, in create_index
    return handler.create_index(collection_name, field_name, params, timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 64, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 56, in handler
    return func(self, *args, **kwargs)
```
**Steps/Code to reproduce behavior**
build index after sift-1m inserted.
index_type: HNSW, metric_type: L2 with params: {'M': 16, 'efConstruction': 500}

log:

https://kibana-dev.zilliz.cc/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-11T20:00:00.000Z',to:'2021-07-11T21:00:00.000Z'))&_a=(columns:!(log),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:ad1e1c50-c9d9-11eb-9e1a-b3dcad9693fd,key:kubernetes.pod_name,negate:!f,params:!(benchmark-cron-1626026400-4-milvus-standalone-7596d7c9bc-kr8ln),type:phrases,value:benchmark-cron-1626026400-4-milvus-standalone-7596d7c9bc-kr8ln),query:(bool:(minimum_should_match:1,should:!((match_phrase:(kubernetes.pod_name:benchmark-cron-1626026400-4-milvus-standalone-7596d7c9bc-kr8ln))))))),hideChart:!t,index:ad1e1c50-c9d9-11eb-9e1a-b3dcad9693fd,interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',desc)))
**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xiaocai2333** [comment]
I can't reproduce it, and the log at this time no longer exists. The index type of 'HNSW' construction time is very slow. If you can reproduce it, please send me the latest log. @del-zhenwu
