### ISSUE TITLE
Load collection sift-50m failed on cluster server

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#6442]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
W
[2021-07-11 23:37:33,802] [   DEBUG] - {'collection count': 50000000} (milvus_benchmark.runners.get:117)
[2021-07-11 23:37:33,803] [   DEBUG] - {'flush_time': 425.19} (milvus_benchmark.runners.get:118)
[2021-07-11 23:40:08,811] [   ERROR] -
Addr [benchmark-cluster-cron-1626037200-1-milvus.qa-milvus.svc.cluster.local:19530] get_query_segment_infos
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Socket closed"
        debug_error_string = "{"created":"@1626046808.809989292","description":"Error received from peer ipv4:10.96.211.99:19530","f
ile":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Socket closed","grpc_status":14}"
>
        {'API start': '2021-07-11 23:37:34.656092', 'RPC start': '2021-07-11 23:37:34.656135', 'RPC error': '2021-07-11 23:40:08.811
642'} (pymilvus.client.grpc_handler:73)
[2021-07-11 23:40:08,812] [   ERROR] -
Addr [benchmark-cluster-cron-1626037200-1-milvus.qa-milvus.svc.cluster.local:19530] wait_for_loading_collection
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Socket closed"
        debug_error_string = "{"created":"@1626046808.809989292","description":"Error received from peer ipv4:10.96.211.99:19530","f
ile":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Socket closed","grpc_status":14}"
>
        {'API start': '2021-07-11 23:37:34.146587', 'RPC start': '2021-07-11 23:37:34.146608', 'RPC error': '2021-07-11 23:40:08.812
563'} (pymilvus.client.grpc_handler:73)
[2021-07-11 23:40:08,813] [   ERROR] -
Addr [benchmark-cluster-cron-1626037200-1-milvus.qa-milvus.svc.cluster.local:19530] load_collection
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Socket closed"
        debug_error_string = "{"created":"@1626046808.809989292","description":"Error received from peer ipv4:10.96.211.99:19530","f
ile":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Socket closed","grpc_status":14}"
>
        {'API start': '2021-07-11 23:37:33.804012', 'RPC start': '2021-07-11 23:37:33.804023', 'RPC error': '2021-07-11 23:40:08.813
188'} (pymilvus.client.grpc_handler:73)
[2021-07-11 23:40:24,611] [   ERROR] - server is not healthy, please try again later (milvus_benchmark.main:115)
[2021-07-11 23:40:24,615] [   ERROR] - Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 333, in load_collection
    return handler.load_collection("", collection_name=collection_name, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 74, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 56, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 790, in load_collection
    self.wait_for_loading_collection(collection_name)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 74, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 56, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 817, in wait_for_loading_collection
    for info in self.get_query_segment_infos(collection_name, timeout):
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 74, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 56, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 634, in get_query_segment_infos
    response = future.result()
  File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Socket closed"
        debug_error_string = "{"created":"@1626046808.809989292","description":"Error received from peer ipv4:10.96.211.99:19530","f
ile":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Socket closed","grpc_status":14}"
>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "main.py", line 84, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/get.py", line 119, in prepare
    self.milvus.load_collection()
  File "/src/milvus_benchmark/client.py", line 46, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 440, in load_collection
    return self._milvus.load_collection(collection_name, timeout=3000)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 61, in handler
    self._update_connection_pool()
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 175, in _update_connection_pool
    self._wait_for_healthy()
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 147, in _wait_for_healthy
    raise Exception("server is not healthy, please try again later")
Exception: server is not healthy, please try again later
 (milvus_benchmark.main:116)
```
**Steps/Code to reproduce behavior**

1. insert sift-50m
2. create index ivf_flat, nlist: 2048

https://kibana-dev.zilliz.cc/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-11T23:38:57.493Z',to:'2021-07-11T23:41:16.936Z'))&_a=(columns:!(log),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:ad1e1c50-c9d9-11eb-9e1a-b3dcad9693fd,key:kubernetes.pod_name,negate:!f,params:!(benchmark-cluster-cron-1626037200-1-milvus-standalone-7575vkdf7),type:phrases,value:benchmark-cluster-cron-1626037200-1-milvus-standalone-7575vkdf7),query:(bool:(minimum_should_match:1,should:!((match_phrase:(kubernetes.pod_name:benchmark-cluster-cron-1626037200-1-milvus-standalone-7575vkdf7))))))),hideChart:!f,index:ad1e1c50-c9d9-11eb-9e1a-b3dcad9693fd,interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',desc)))

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by xige-16** [comment]
pr #6908 #6935  has fixed load issue, trouble you retry @del-zhenwu

**Comment by del-zhenwu** [comment]
close it
