### ISSUE TITLE
Milvus becomes not healthy during CI or Nightly tests

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#6455]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Milvus becomes not healthy during CI or Nightly tests.
There are 2 potential root causes I can think of by now:
1. Milvus stability issues
2. KinD resource cannot hold for Milvus service workload

**Steps/Code to reproduce behavior**
Run CI or Nightly tests, occasionally Milvus becomes not healthy after a few mins.

**Expected behavior**
Milvus is always healthy

**Actually**
 File "/usr/local/lib/python3.6/site-packages/pymilvus_orm/connections.py", line 158, in connect
[2021-07-12T11:44:46.764Z]     conn = connect_milvus(**kwargs)
[2021-07-12T11:44:46.764Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus_orm/connections.py", line 148, in connect_milvus
[2021-07-12T11:44:46.764Z]     return Milvus(tmp_host, tmp_port, handler, pool, **tmp_kwargs)
[2021-07-12T11:44:46.764Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 122, in __init__
[2021-07-12T11:44:46.764Z]     self._update_connection_pool(channel=channel)
[2021-07-12T11:44:46.764Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 176, in _update_connection_pool
[2021-07-12T11:44:46.764Z]     self._wait_for_healthy()
[2021-07-12T11:44:46.764Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
[2021-07-12T11:44:46.764Z]     return func(self, *args, **kwargs)
[2021-07-12T11:44:46.764Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 147, in _wait_for_healthy
[2021-07-12T11:44:46.764Z]     raise Exception("server is not healthy, please try again later")
[2021-07-12T11:44:46.764Z] Exception: server is not healthy, please try again later
[2021-07-12T11:44:46.764Z]  (api_request.py:24)

- Milvus version (master or released version)
master-20210712-a8e5fd2
pymilvus                           2.0.0rc2.dev14
pymilvus-orm                   2.0.0rc2.dev31

**Comment by binbinlv** [comment]
After run some tests successfully,  server becomes not healthy:
standalone
milvus: master(d4239f0)
Name: pymilvus
Version: 2.0.0rc2
Name: pymilvus-orm
Version: 2.0.0rc2.dev32

Logs:
[log.tar.zip](https://github.com/milvus-io/milvus/files/6806060/log.tar.zip)

[2021-07-13 05:09:40 - ERROR - ci_test]: Traceback (most recent call last):
  File "/milvus/tests20/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/milvus/tests20/python_client/utils/api_request.py", line 42, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus_orm/connections.py", line 158, in connect
    conn = connect_milvus(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus_orm/connections.py", line 148, in connect_milvus
    return Milvus(tmp_host, tmp_port, handler, pool, **tmp_kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 122, in __init__
    self._update_connection_pool(channel=channel)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 176, in _update_connection_pool
    self._wait_for_healthy()
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 147, in _wait_for_healthy
    raise Exception("server is not healthy, please try again later")
Exception: server is not healthy, please try again later

**Comment by binbinlv** [comment]
Same issue when running CI for a while (standalone)
milvus master: da5bbdceb

Logs:
[artifacts-milvus-standalone-PR-6616-2-pymilvus-orm-e2e-logs.tar.gz](https://github.com/milvus-io/milvus/files/6840059/artifacts-milvus-standalone-PR-6616-2-pymilvus-orm-e2e-logs.tar.gz)
[artifacts-milvus-standalone-pymilvus-orm-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/6840068/artifacts-milvus-standalone-pymilvus-orm-pytest-logs.tar.gz)

[2021-07-19 10:03:12,718 - ERROR - ci_test]: Traceback (most recent call last):
  File "/milvus/tests20/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/milvus/tests20/python_client/utils/api_request.py", line 42, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus_orm/connections.py", line 158, in connect
    conn = connect_milvus(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus_orm/connections.py", line 148, in connect_milvus
    return Milvus(tmp_host, tmp_port, handler, pool, **tmp_kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 122, in __init__
    self._update_connection_pool(channel=channel)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 176, in _update_connection_pool
    self._wait_for_healthy()
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 147, in _wait_for_healthy
    raise Exception("server is not healthy, please try again later")
Exception: server is not healthy, please try again later

**Comment by yanliang567** [comment]
CI stability issues are tracked indepently. close
