### ISSUE TITLE
Create collection failed: collection test_collection_xxx exist

### ISSUE THREAD

**Issue by xige-16** [milvus-io/milvus#6475]
#### Describe the bug:
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-6351/6/pipeline report the bug: 
    status = error_code: UnexpectedError
    reason: "Create collection failed: collection test_collection_APDa0YYm exist"

    @error_handler()
    def create_collection(self, collection_name, fields, timeout=None, **kwargs):
        request = Prepare.create_collection_request(collection_name, fields, **kwargs)
        rf = self._stub.CreateCollection.future(request, wait_for_ready=True, timeout=timeout)
        status = rf.result()
        if status.error_code != 0:
            LOGGER.error(status)
>           raise BaseException(status.error_code, status.reason)
E           pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=Create collection failed: collection test_collection_APDa0YYm exist)>

#### Expected behavior:
create collection success

#### Steps/Code to reproduce:
run pytest in tests dir

#### Environment:
- Milvus version(master): 
- SDK version(pymilvus v2.0.0rc2):
- OS(Ubuntu): 
- CPU/Memory: 
- GPU: 
- Others: 

#### Additional context:
[rootcoord.log](https://github.com/milvus-io/milvus/files/6806808/rootcoord.log)

**Comment by xige-16** [comment]
thr rootCoord received two createCollection request according to the rootcoord.log file, and create failed.

**Comment by binbinlv** [comment]
Run test case under multiple replica environment, and reported collection exists at case test_search_multi_collections, maybe the same issue, so pasted the logs here if could be a help for analysis.

proxy:1, querynode:2, datanode:2, indexnode:2
milvus: d896e31
Name: pymilvus
Version: 2.0.0rc3.dev1
Name: pymilvus-orm
Version: 2.0.0rc3.dev4

Logs:
[log.tar.zip](https://github.com/milvus-io/milvus/files/6809045/log.tar.zip)

[2021-07-13 12:59:11,915 - ERROR - ci_test]: Traceback (most recent call last):
  File "/milvus/tests20/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/milvus/tests20/python_client/utils/api_request.py", line 42, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus_orm/collection.py", line 130, in __init__
    conn.create_collection(self._name, fields=schema.to_dict())
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 63, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 230, in create_collection
    return handler.create_collection(collection_name, fields, timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 375, in create_collection
    raise BaseException(status.error_code, status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=Create collection failed: collection search_collection_TuYC4pJd exist)>
 (api_request.py:24)
[2021-07-13 12:59:11,918 - ERROR - ci_test]: (api_response) : <BaseException: (code=1, message=Create collection failed: collection search_collection_TuYC4pJd exist)> (api_request.py:25)

**Comment by binbinlv** [comment]
Running CI, create collection failed for exist... occurs, could you please have a look? Thanks @neza2017 

https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-6839/3/pipeline/121


[2021-07-28T06:40:45.085Z] reason: "Create collection failed: meta table add collection failed,error = collection collection_heR7rTb4 exist"

[2021-07-28T06:40:45.085Z]  (grpc_handler.py:374)

[2021-07-28T06:40:45.085Z] [2021-07-28 06:40:36 - ERROR - pymilvus.client.grpc_handler]: Error: <BaseException: (code=1, message=Create collection failed: meta table add collection failed,error = collection collection_heR7rTb4 exist)> (grpc_handler.py:59)
