### ISSUE TITLE
When I call the insertasync interface, ConcurrentModificationException() is thrown

### ISSUE THREAD

**Issue by xuewenzhang** [milvus-io/milvus#6488]
#### Describe the bug:
When I call the insertasync interface, ConcurrentModificationException() is thrown.

#### Expected behavior:

Insert data into milvus normally

#### Steps/Code to reproduce:
1 每读十万行调用insert接口插入数据。
```java
while ((lineData = textFile.readLine()) != null){
                List<List<Float>> vectors = new ArrayList<>();
                List<Long> ids = new ArrayList<>();
                String[] split = lineData.split(",|，|\\s+");
                String name = "zhangxuewen";
                String collectionName = "data_10billion";
                String tag = "ks";
                // 注意插入大小为256M
                temp.clear();
                ids.add(Long.parseLong(split[0]));
                temp.add(Float.parseFloat(split[1].substring(1)));
                for(int i=2;i<512;i++){
                    temp.add(Float.parseFloat(split[i]));
                }
                temp.add(Float.parseFloat(split[512].substring(0,split[512].length()-1)));
                vectors.add(temp);
                count++;
                temp_vectors = vectors;
                temp_ids = ids;
                if(count==100000){
                    count = 0;
                    num++;
                    System.out.println("开始第"+num+"次插入数据");
                    distributedEmbed.insert(name,collectionName,tag,vectors,ids);
                }
            }
```
2  每次插入都开一个线程去处理。
```java
void insert(String userName,String CollectionName,String tag,List<List<Float>> vectors,List<Long> ids){
        threadPoolExecutor.execute(new Runnable() {
            @Override
            public void run() {
                doInsert(userName,CollectionName,tag,vectors,ids);
            }
        });
        // 不能关闭  可能会有线程来不及执行，被拒绝。
        //threadPoolExecutor.shutdown();
    }
```
3：具体每次的插入逻辑
```java
// 有多台milvus，每次插入随机选一台插入，client即此次插入的client
InsertParam insertParam = new InsertParam.Builder(userName+"_"+collectionName).withFloatVectors(vectors).withPartitionTag(tag).withVectorIds(ids).build();
        ListenableFuture future = client.insertAsync(insertParam);
        future.addListener(new Runnable() {
            @Override
            public void run() {
                num++;
                System.out.println("第"+num+"次insert执行完毕！");
            }
        },threadPoolExecutor);
```

#### Environment:
- Milvus version(e.g. v1.1.0 or 8b23a93): 
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others: 
milvus1.1.1
centos7

**Comment by xiaofan-luan** [comment]
please offer call stack of your exceptions, most likely it is temp list your declaired causing race condition

**Comment by xuewenzhang** [comment]
Exception in thread "pool-1-thread-3" java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at com.google.protobuf.AbstractMessageLite$Builder.addAllCheckingNulls(AbstractMessageLite.java:372)
	at com.google.protobuf.AbstractMessageLite$Builder.addAll(AbstractMessageLite.java:434)
	at io.milvus.grpc.RowRecord$Builder.addAllFloatData(RowRecord.java:611)
	at io.milvus.client.AbstractMilvusGrpcClient.buildRowRecordList(MilvusGrpcClient.java:1385)
	at io.milvus.client.AbstractMilvusGrpcClient.insertAsync(MilvusGrpcClient.java:575)
	at io.milvus.client.MilvusGrpcClient.insertAsync(MilvusGrpcClient.java:49)
	at com.kuaishou.mmu.DistributedEmbed.doInsert(DistributedEmbed.java:165)
	at com.kuaishou.mmu.DistributedEmbed$1.run(DistributedEmbed.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

> please offer call stack of your exceptions, most likely it is temp list your declaired causing race condition
