### ISSUE TITLE
inconsistent error message for unsupported search field

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#6538]
#### Describe the bug:
inconsistent error message for unsupported search field:
search field only support str, for unsupported types:
(1)class 'list': []
TypeError: unhashable type: 'list'
(2) class 'int': 1
Field 1 doesn't exist in schema
(3) <class 'tuple'>: (1,)
Field (1,) doesn't exist in schema
(4) <class 'dict'>: {1: 1}
TypeError: unhashable type: 'dict'
(5) <class 'NoneType'>: None
 Field None doesn't exist in schema

#### Expected behavior:
for str type field: current message is OK.
for non-str type field: could we report like " ** type is not supported for field in search"

#### Steps/Code to reproduce:
```python
from pymilvus_orm import CollectionSchema, FieldSchema
from pymilvus_orm import Collection
from pymilvus_orm import connections
from pymilvus_orm.types import DataType
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=128)
schema = CollectionSchema(fields=[int64_field, float_field, float_vector])
connections.connect()
import numpy as np
collection = Collection("test_search_collection_binbin_6", schema=schema)
dim = 128
nb = 10000
nq = 2
limit = 10
import random
default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors])
collection.load()
collection.num_entities
collection.partitions
res = collection.search(vectors[:nq], [], default_search_params, limit, "int64 >= 0")
```

```
Addr [172.18.255.155:19530] search_with_expression
Excepted error: unhashable type: 'list'
	{'API start': '2021-07-15 03:14:55.908238', 'RPC start': '2021-07-15 03:14:55.908955', 'Exception': '2021-07-15 03:14:55.923961'}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pymilvus_orm/collection.py", line 605, in search
    partition_names, output_fields, timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 63, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 1044, in search_with_expression
    return handler.search_with_expression(collection_name, data, anns_field, param, limit, expression, partition_names, output_fields, timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 80, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 94, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 635, in search_with_expression
    partition_names, output_fields, **_kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/prepare.py", line 583, in search_requests_with_expr
    if anns_field not in fields_name_locs:
TypeError: unhashable type: 'list'
```

#### Environment:
- Milvus version(e.g. v1.1.0 or 8b23a93): 
- SDK version():
Name: pymilvus
Version: 2.0.0rc3.dev2
Name: pymilvus-orm
Version: 2.0.0rc3.dev5

- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by DragonDriver** [comment]
OK, i will fix this soon. thx for pointing this. @binbinlv

**Comment by DragonDriver** [comment]
Already fixed, please retest this. thx.

/unassign
/assign @binbinlv

**Comment by binbinlv** [comment]
Verified and fixed. Thx.

Results:
`anns_field` value *** is illegal

Name: pymilvus
Version: 2.0.0rc3.dev4
Name: pymilvus-orm
Version: 2.0.0rc3.dev5
