### ISSUE TITLE
Type check is lacked for search data (vector) parameter

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#6541]
#### Describe the bug:
for search:
:type  data: list[list[float]]

Type check is lacked for search data (vector) parameter

(1) <class 'str'>: 1*2
The dimension of query entities is different from schema
(2) <class 'list'>: [1, 2]
TypeError: object of type 'int' has no len()
(3) <class 'list'>: ['a']
The dimension of query entities is different from schema
(4) <class 'list'>: [None]
object of type 'NoneType' has no len()
(5) <class 'NoneType'>: None
TypeError: object of type 'NoneType' has no len()
(6) <class 'dict'>: {'a': 1}
KeyError: 0

Now it reports a little confusion for not supported data type.

#### Expected behavior:
(1) if data is correct type, current message is OK: The dimension of query entities is different from schema.
(2) if data is not correct type, could we report messages like : The type of query entities is not ***.

#### Steps/Code to reproduce:
```python
from pymilvus_orm import CollectionSchema, FieldSchema
from pymilvus_orm import Collection
from pymilvus_orm import connections
from pymilvus_orm.types import DataType
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=128)
schema = CollectionSchema(fields=[int64_field, float_field, float_vector])
connections.connect()
import numpy as np
collection = Collection("test_search_collection_binbin_6", schema=schema)
dim = 128
nb = 10000
nq = 2
limit = 10
import random
default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors])
collection.load()
res = collection.search({'a': 1}, "float_vector", default_search_params, limit, "int64 >= 0")
```

```
Addr [172.18.255.155:19530] search_with_expression
Excepted error: 0
	{'API start': '2021-07-15 05:25:20.365994', 'RPC start': '2021-07-15 05:25:20.368386', 'Exception': '2021-07-15 05:25:20.383281'}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pymilvus_orm/collection.py", line 605, in search
    partition_names, output_fields, timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 63, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 1044, in search_with_expression
    return handler.search_with_expression(collection_name, data, anns_field, param, limit, expression, partition_names, output_fields, timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 80, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 94, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 635, in search_with_expression
    partition_names, output_fields, **_kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/prepare.py", line 564, in search_requests_with_expr
    if isinstance(data[0], bytes):
KeyError: 0
```

#### Environment:
- Milvus version(e.g. v1.1.0 or 8b23a93): 
- SDK version():
Name: pymilvus
Version: 2.0.0rc3.dev2
Name: pymilvus-orm
Version: 2.0.0rc3.dev5

- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by DragonDriver** [comment]
Already fixed.

**Comment by binbinlv** [comment]
Verified and fixed. Thx.

Name: pymilvus
Version: 2.0.0rc3.dev4
Name: pymilvus-orm
Version: 2.0.0rc3.dev5

Results:
`search_data` value ** is illegal
