### ISSUE TITLE
Can not get timestamp during indexing

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#6606]
#### Describe the bug:

```

[2021-07-16 18:05:54,161] [   DEBUG] - End flush (milvus_benchmark.runners.accuracy:238)
[2021-07-16 18:05:54,164] [   DEBUG] - Row count: 1183514 in collection: <glove_200_angular> (milvus_benchmark.client:389)
[2021-07-16 18:05:54,165] [    INFO] - Table: glove_200_angular, row count: 1183514 (milvus_benchmark.runners.accuracy:240)
[2021-07-16 18:05:54,168] [    INFO] - None (milvus_benchmark.client:276)
[2021-07-16 18:05:54,169] [    INFO] - Drop index: glove_200_angular (milvus_benchmark.client:287)
[2021-07-16 18:05:54,171] [    INFO] - Re-create index: glove_200_angular (milvus_benchmark.runners.accuracy:245)
[2021-07-16 18:05:54,172] [    INFO] - Building index start, collection_name: glove_200_angular, index_type: IVF_FLAT, metric_type:
IP (milvus_benchmark.client:261)
[2021-07-16 18:05:54,173] [    INFO] - {'nlist': 1024} (milvus_benchmark.client:263)
[2021-07-16 22:53:20,979] [   ERROR] - Error: <BaseException: (code=1, message=syncTimeStamp Failed:AllocTimestamp failed: can not g
et timestamp)> (pymilvus.client.grpc_handler:59)
[2021-07-16 22:53:20,982] [   ERROR] - Error: <BaseException: (code=1, message=syncTimeStamp Failed:AllocTimestamp failed: can not g
et timestamp)> (pymilvus.client.grpc_handler:59)
[2021-07-16 22:53:20,982] [   ERROR] - Error: <BaseException: (code=1, message=syncTimeStamp Failed:AllocTimestamp failed: can not g
et timestamp)> (pymilvus.client.grpc_handler:59)
[2021-07-16 22:53:20,983] [   ERROR] - <BaseException: (code=1, message=syncTimeStamp Failed:AllocTimestamp failed: can not get time
stamp)> (milvus_benchmark.main:112)
[2021-07-16 22:53:20,987] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 81, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/accuracy.py", line 246, in prepare
    self.milvus.create_index(index_field_name, index_type, metric_type, index_param=index_param)
  File "/src/milvus_benchmark/client.py", line 46, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 269, in create_index
    self._milvus.create_index(self._collection_name, field_name, index_params, _async=_async)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 63, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner                                          
    return func(self, *args, **kwargs)                                                                                              
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 750, in create_index                                  
    return handler.create_index(collection_name, field_name, params, timeout, **kwargs)                                             
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler                                
    raise e                                                                                                                         
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler                                
    return func(self, *args, **kwargs)                                                                                              
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 739, in create_index                          
    if not self.wait_for_creating_index(collection_name=collection_name, field_name=field_name):                                    
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler                                
    raise e                                                                                                                         
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler                                
    return func(self, *args, **kwargs)                                                                                              
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 785, in wait_for_creating_index               
    state = self.get_index_state(collection_name, field_name, timeout)                                                              
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler                                
    raise e                                                                                                                         
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler                                
    return func(self, *args, **kwargs)                                                                                              
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 779, in get_index_state                       
    raise BaseException(status.error_code, status.reason)                                                                           
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=syncTimeStamp Failed:AllocTimestamp failed: can not get t
imestamp)>                                                                                                                          
 (milvus_benchmark.main:113)                                                      
```
#### Environment:
- Milvus version(e.g. v1.1.0 or 8b23a93): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): rc3-004
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by xiaofan-luan** [comment]
Do we have log on this issue?

**Comment by czs007** [comment]
move to rc6

**Comment by xiaocai2333** [comment]
Has this problem occurred yet？ @yanliang567

**Comment by yanliang567** [comment]
not reproduce recently. close for now
