### ISSUE TITLE
When the inserted data size is larger than the segment, Milvus thrown an exception.

### ISSUE THREAD

**Issue by xiaocai2333** [milvus-io/milvus#6621]
#### Steps/Code to reproduce:

I modified the `segment.maxSize`  in `data_coord.yaml` to 1 'M'.

```
import random
import time
import pymilvus_orm
from pymilvus_orm import connections, Collection, CollectionSchema, FieldSchema, DataType
connections.connect()

dim = 128
nb = 50000

collection_name = "test_create_index"
field_name = "example_field"
pk = FieldSchema(name="pk", dtype=DataType.INT64, is_primary=True, auto_id=True)
field = FieldSchema(name=field_name, dtype=DataType.FLOAT_VECTOR, dim=dim)
schema = CollectionSchema(fields=[pk, field], description="example collection")

collection = Collection(name=collection_name, schema=schema)

vectors1 = [[random.random() for _ in range(dim)] for _ in range(nb)]
entities1 = [vectors1]
collection.insert(entities1)
```

#### Expected result:
Inserted successfully.

#### Actual results:
```
Error: <BaseException: (code=1, message=GetSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error)>
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    collection.insert(entities1)
  File "/home/zc/anaconda3/envs/orm/lib/python3.8/site-packages/pymilvus_orm/collection.py", line 517, in insert
    res = conn.insert(collection_name=self._name, entities=entities, ids=None,
  File "/home/zc/anaconda3/envs/orm/lib/python3.8/site-packages/pymilvus/client/stub.py", line 63, in handler
    raise e
  File "/home/zc/anaconda3/envs/orm/lib/python3.8/site-packages/pymilvus/client/stub.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/home/zc/anaconda3/envs/orm/lib/python3.8/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/home/zc/anaconda3/envs/orm/lib/python3.8/site-packages/pymilvus/client/stub.py", line 852, in insert
    return handler.bulk_insert(collection_name, entities, partition_name, timeout, **kwargs)
  File "/home/zc/anaconda3/envs/orm/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler
    raise e
  File "/home/zc/anaconda3/envs/orm/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
    return func(self, *args, **kwargs)
  File "/home/zc/anaconda3/envs/orm/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 539, in bulk_insert
    raise err
  File "/home/zc/anaconda3/envs/orm/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 535, in bulk_insert
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=GetSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error)>
```

#### Environment:
- Milvus version(master):
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by yanliang567** [comment]
data size (with 128d+50,000 entities) is larger than the segment? what is the segment size, 512M?

**Comment by xiaocai2333** [comment]
Segment size is Configurable, I modified it to 1M.

**Comment by yanliang567** [comment]
makes sense then.

**Comment by czs007** [comment]
same to #6696 
see #6788 
@xiaocai2333 @yanliang567

**Comment by czs007** [comment]
@yanliang567 
It may be fixed, please test it.

**Comment by yanliang567** [comment]
working on it

**Comment by binbinlv** [comment]
OK, working on it.

**Comment by binbinlv** [comment]
Verified and fixed.

milvus: master (3cc8ee2)
Name: pymilvus
Version: 2.0.0rc3.dev6
Name: pymilvus-orm
Version: 2.0.0rc3.dev8


Results:

Configure segment.maxSize in data_coord.yaml to 1 'M'.
collection.insert(entities)
(insert count: 100000, delete count: 0, upsert count: 0, timestamp: 426601183494799365)
