### ISSUE TITLE
Failed to batch insert vector into milvus

### ISSUE THREAD

**Issue by huazaizai0322** [milvus-io/milvus#6661]
#### Steps/Code to reproduce:
```python
from pymilvus_orm import *
import pyarrow.parquet as pq
df = pq.read_table(source='/tep/ichain_vector/site=us/cal_dt=2020-12-15').to_pandas()
connections.connect(host='xxx', port='19530')
dim = 128
default_fields = [
    schema.FieldSchema(name="item_id", dtype=DataType.INT64, is_primary=True),
    schema.FieldSchema(name="ichain_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
]
default_schema = schema.CollectionSchema(fields=default_fields, description="ichain collection")
collection = Collection(name="ichain_collection", data=None, schema=default_schema)
collection.insert(df[['item_id', 'ichain_vector']].head(3000000))
```

#### Expected result:
success

#### Actual results:
```
Error: <BaseException: (code=1, message=GetSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error)>
Traceback (most recent call last):
  File "ichain_vector.py", line 74, in <module>
    ichain_vector_insert()
  File "ichain_vector.py", line 58, in ichain_vector_insert
    collection.insert(df[['item_id', 'embeddings']].head(insert_vector_num))
  File "/usr/local/lib/python3.6/site-packages/pymilvus_orm/collection.py", line 518, in insert
    partition_name=partition_name, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 63, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 852, in insert
    return handler.bulk_insert(collection_name, entities, partition_name, timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 539, in bulk_insert
    raise err
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 535, in bulk_insert
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=GetSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error)>
```

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): 2.0
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): v2.0.0rc2
- OS(Ubuntu or CentOS): Centos
- CPU/Memory: 
- GPU: 
- Others: 

#### Additional context:
When I inserted 2,000,000 pieces of data into milvus, it succeeded. However, when I inserted 3,000,000 data into milvus, it failed.

**Comment by czs007** [comment]
@huazaizai0322 Thanks for the feedback.
May be related to this pr #6788.
It will be fixed in the next release of rc3.

**Comment by yanliang567** [comment]
@binbinlv could you please help to check whether it was fixed in latest build? Also please check if we need to add more testcases for this issue

**Comment by binbinlv** [comment]
@yanliang567 OK，working on it.

**Comment by binbinlv** [comment]
Assert still exists: insert 50000 entities.

milvus(master): 61786f7 [distributed]
Name: pymilvus
Version: 2.0.0rc3.dev6
Name: pymilvus-orm
Version: 2.0.0rc3.dev9

[2021-07-29 08:01:47 - ERROR - pymilvus.client.grpc_handler]: Error: <BaseException: (code=1, message=GetSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error)> (grpc_handler.py:59)
[2021-07-29 08:01:47 - ERROR - ci_test]: Traceback (most recent call last):
  File "/milvus/tests20/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/milvus/tests20/python_client/utils/api_request.py", line 45, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus_orm/collection.py", line 519, in insert
    partition_name=partition_name, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 63, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 852, in insert
    return handler.bulk_insert(collection_name, entities, partition_name, timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 539, in bulk_insert
    raise err
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 535, in bulk_insert
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=GetSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error)>
 (api_request.py:26)

**Comment by cydrain** [comment]
test in local machine using master branch, it pass

**Comment by binbinlv** [comment]
It could not be steadily reproduced. After insert many times, it is reproduced.

milvus(master): 7307332
Name: pymilvus
Version: 2.0.0rc3.dev7
Name: pymilvus-orm
Version: 2.0.0rc3.dev9

logs:
[log_6661.tar.zip](https://github.com/milvus-io/milvus/files/6910929/log_6661.tar.zip)

Results:
[2021-07-31 08:54:57,791 - INFO - ci_test]: inserting (test_e2e.py:30)
[2021-07-31 08:55:04,671 - ERROR - ci_test]: Traceback (most recent call last):
  File "/milvus/tests20/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/milvus/tests20/python_client/utils/api_request.py", line 45, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus_orm/collection.py", line 519, in insert
    partition_name=partition_name, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 63, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 852, in insert
    return handler.bulk_insert(collection_name, entities, partition_name, timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 66, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 58, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 540, in bulk_insert
    raise err
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 536, in bulk_insert
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=GetSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error)>

**Comment by cydrain** [comment]
current version is like this:
pymilvus              2.0.0rc3.dev15
pymilvus-orm          2.0.0rc3.dev13

why test using so old pymilvus and pymilvus-orm ?

**Comment by cydrain** [comment]
Can only find one ERROR message in all log files, seems ETCD breaks.
```
381728653/kind-worker2/pods/default_milvus-testing-rootcoord-7c9866649c-758d6_82e3e575-ca98-4568-b0da-eb25ca1ef25a/rootcoord/0.log:3312:2021-07-31T08:48:54.1634948Z stdout F [2021/07/31 08:48:54.142 +00:00] [ERROR] [root_coord.go:273] ["rootcoord disconnect with etcd, process will exit in 1 second"] [stack="github.com/milvus-io/milvus/internal/log.Error\n\t/go/src/github.com/milvus-io/milvus/internal/log/global.go:42\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).sessionLoop\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:273"]
```

**Comment by binbinlv** [comment]
> current version is like this:
> 
> ```
> pymilvus              2.0.0rc3.dev15
> pymilvus-orm          2.0.0rc3.dev13
> ```
> 
> why test using so old pymilvus and pymilvus-orm ?

It is not very old，the latest version was produced at weekends which I have not tested it yet. 

But I could have a try at latest version today to see if could reproduce this issue which may be a help for analyze the issue.

**Comment by xiaofan-luan** [comment]
@cydrain any progress on this issue?

**Comment by cydrain** [comment]
We can only see one ERROR in CI logs - "rootcoord disconnect with etcd, process will exit in 1 second".
This issue should have been resolved after we isolate ETCD resource from other CI resources.
Need tester help to check.

**Comment by binbinlv** [comment]
OK, working on verification.

**Comment by binbinlv** [comment]
Insert 50000, 500000 for several times, this assert did not occur. So suggest to close it first, will reopen it if it occurs again.

mode: standalone and cluster

milvus: bf2c427
pymilvus: 2.0.0rc5.dev20
