### ISSUE TITLE
Search doesn't support vector field as output_fields

### ISSUE THREAD

**Issue by dzhyy** [milvus-io/milvus#6662]
#### Steps/Code to reproduce:
```python
........
  def get_source(self, name: str):
      dim = get_dim(name)
      vectors = [np.ones(dim).tolist()]
      output_field = ["label", "embedding"]
      self.set_collection(name=name)
      self.collection.load()
      search_params = {
          "metric_type": settings.metric_type,
          "params": {"nprobe": 16},
      }
      res = self.collection.search(
          vectors,
          anns_field="embedding",
          param=search_params,
          limit=200,
          output_fields=output_field,
      )
      embeddings = []
      labels = []
      for hits in res:
          for hit in hits:
              embeddings.append(hit.entity.get('embedding'))
              labels.append(hit.entity.get('label'))
      return [labels,embeddings]
............
connection.load(name='plant')
a = connection.get_source('plant')
............
```

#### Expected result:

I expected getting entities(e.g: [class_list,embedding_list]) from collection,so i used 'search' with 'hit.entitity.get(field_name)' ,hope  it can achieve similar results.but got an error.

#### Actual results:
```
Error: <BaseException: (code=1, message=Search doesn't support vector field as output_fields)>
Traceback (most recent call last):
  File "/home/dzh/.cache/pypoetry/virtualenvs/labeling-i6bWZ5ol-py3.8/lib/python3.8/site-packages/pymilvus/client/stub.py", line 63, in handler
    raise e
  File "/home/dzh/.cache/pypoetry/virtualenvs/labeling-i6bWZ5ol-py3.8/lib/python3.8/site-packages/pymilvus/client/stub.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/home/dzh/.cache/pypoetry/virtualenvs/labeling-i6bWZ5ol-py3.8/lib/python3.8/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/home/dzh/.cache/pypoetry/virtualenvs/labeling-i6bWZ5ol-py3.8/lib/python3.8/site-packages/pymilvus/client/stub.py", line 1042, in search_with_expression
    return handler.search_with_expression(collection_name, data, anns_field, param, limit, expression, partition_names, output_fields, timeout, **kwargs)
  File "/home/dzh/.cache/pypoetry/virtualenvs/labeling-i6bWZ5ol-py3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 63, in handler
    raise e
  File "/home/dzh/.cache/pypoetry/virtualenvs/labeling-i6bWZ5ol-py3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 55, in handler
    return func(self, *args, **kwargs)
  File "/home/dzh/.cache/pypoetry/virtualenvs/labeling-i6bWZ5ol-py3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 92, in handler
    return func(self, *args, **kwargs)
  File "/home/dzh/.cache/pypoetry/virtualenvs/labeling-i6bWZ5ol-py3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 622, in search_with_expression
    return self._execute_search_requests(requests, timeout, **kwargs)
  File "/home/dzh/.cache/pypoetry/virtualenvs/labeling-i6bWZ5ol-py3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 63, in handler
    raise e
  File "/home/dzh/.cache/pypoetry/virtualenvs/labeling-i6bWZ5ol-py3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 55, in handler
    return func(self, *args, **kwargs)
  File "/home/dzh/.cache/pypoetry/virtualenvs/labeling-i6bWZ5ol-py3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 591, in _execute_search_requests
    raise pre_err
  File "/home/dzh/.cache/pypoetry/virtualenvs/labeling-i6bWZ5ol-py3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 582, in _execute_search_requests
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=Search doesn't support vector field as output_fields)>
```
python-BaseException

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):v2.0.0-RC
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.0.0
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: i56300HQ
- GPU: GTX960m
- Others:

**Comment by yhmo** [comment]
In latest version RC4, only the query() api can return vector fields. The search() will throw this error when exporting vector field.

**Comment by cydrain** [comment]
If user want to get raw vector of search result, they can use Search to get id firstly, then use Query to get raw vector.

Please check following MEP for details:
https://wiki.lfaidata.foundation/display/MIL/MEP+6+--+Support+vector+output+fields+design
