### ISSUE TITLE
[CI] etcdserver: request timed out

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#6689]
#### Steps/Code to reproduce:
When CI running, it suddenly becomes unavailable.
[CI pipeline logs](https://ci.milvus.io:18080/jenkins/blue/rest/organizations/jenkins/pipelines/milvus-ha-ci/branches/PR-6663/runs/3/nodes/15/steps/113/log/?start=0)

#### Actual results:
```
[2021-07-20T09:51:42.707Z] [2021-07-20 09:47:38 - ERROR - pymilvus.client.grpc_handler]: error_code: UnexpectedError
[2021-07-20T09:51:42.707Z] reason: "Create collection failed: meta table add collection failed,error = etcdserver: request timed out"
[2021-07-20T09:51:42.707Z]  (grpc_handler.py:374)
[2021-07-20T09:51:42.707Z] [2021-07-20 09:47:38 - ERROR - pymilvus.client.grpc_handler]: Error: <BaseException: (code=1, message=Create collection failed: meta table add collection failed,error = etcdserver: request timed out)> (grpc_handler.py:59)
[2021-07-20T09:51:42.707Z] [2021-07-20 09:47:38 - ERROR - ci_test]: Traceback (most recent call last):
[2021-07-20T09:51:42.707Z]   File "/milvus/tests20/python_client/utils/api_request.py", line 18, in inner_wrapper
[2021-07-20T09:51:42.707Z]     res = func(*args, **kwargs)
[2021-07-20T09:51:42.707Z]   File "/milvus/tests20/python_client/utils/api_request.py", line 42, in api_request
[2021-07-20T09:51:42.707Z]     return func(*arg, **kwargs)
[2021-07-20T09:51:42.707Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus_orm/collection.py", line 130, in __init__
[2021-07-20T09:51:42.707Z]     conn.create_collection(self._name, fields=schema.to_dict())
[2021-07-20T09:51:42.707Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 63, in handler
[2021-07-20T09:51:42.707Z]     raise e
[2021-07-20T09:51:42.707Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 51, in handler
[2021-07-20T09:51:42.708Z]     return func(self, *args, **kwargs)
[2021-07-20T09:51:42.708Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
[2021-07-20T09:51:42.708Z]     return func(self, *args, **kwargs)
[2021-07-20T09:51:42.708Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 230, in create_collection
[2021-07-20T09:51:42.708Z]     return handler.create_collection(collection_name, fields, timeout, **kwargs)
[2021-07-20T09:51:42.708Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler
[2021-07-20T09:51:42.708Z]     raise e
[2021-07-20T09:51:42.708Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
[2021-07-20T09:51:42.708Z]     return func(self, *args, **kwargs)
[2021-07-20T09:51:42.708Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 375, in create_collection
[2021-07-20T09:51:42.708Z]     raise BaseException(status.error_code, status.reason)
[2021-07-20T09:51:42.708Z] pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=Create collection failed: meta table add collection failed,error = etcdserver: request timed out)>
[2021-07-20T09:51:42.708Z]  (api_request.py:24)
[2021-07-20T09:51:42.708Z] [2021-07-20 09:47:38 - ERROR - ci_test]: (api_response) : <BaseException: (code=1, message=Create collection failed: meta table add collection failed,error = etcdserver: request timed out)> (api_request.py:25)
```

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by xiaofan-luan** [comment]
another etcd issue,please take a look

**Comment by godchen0212** [comment]
This problem is consistent with the previous problems that occurred when etcd resources were insufficient.
Please observe whether this problem still exists.

**Comment by yanliang567** [comment]
close for now as not repro in ci recently
