### ISSUE TITLE
[Load] querynode OOM if loading a collection that beyond the memory limit

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#6726]
#### Steps/Code to reproduce:
1. deploy Milvus 2.0 with cluster mode
   1.1  querynode memory limits: 250Mi
2. insert 2000,000 row data(about 1GB) into a collection
3. collection.load()

#### Expected result:
pops up an error to fail load operation  with a friendly msg or suggestion to users

#### Actual results:
querynode OOMKilled  and then  CrashLoopBackOff
exceptions:
```
Error: <BaseException: (code=1, message=rpc error: code = Unknown desc = query node 0 is not ready)>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus_orm/collection.py", line 439, in load
    conn.load_collection(self._name, timeout=kwargs.get("timeout", None))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/client/stub.py", line 63, in handler
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/client/stub.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/client/stub.py", line 334, in load_collection
    return handler.load_collection("", collection_name=collection_name, timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 800, in load_collection
    self.wait_for_loading_collection(collection_name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 827, in wait_for_loading_collection
    for info in self.get_query_segment_infos(collection_name, timeout):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 648, in get_query_segment_infos
    raise BaseException(status.error_code, status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=rpc error: code = Unknown desc = query node 0 is not ready)>
>>> pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=rpc error: code = Unknown desc = query node 0 is not ready)>
  File "<stdin>", line 1
    pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=rpc error: code = Unknown desc = query node 0 is not ready)>
                                              ^
SyntaxError: invalid syntax
```

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by yanliang567** [comment]
If manually delete and restart the querynode pod, it keeps OOM. It seems that the load operation is still pending in querycoord or somewhere :(

**Comment by xige-16** [comment]
The load collection is asynchronous. And the loadCollectionTask will be retried until the success on queryCoord.

**Comment by xige-16** [comment]
> If manually delete and restart the querynode pod, it keeps OOM. It seems that the load operation is still pending in querycoord or somewhere :(

if querynode restart, the load collection task will be executed automatically.

**Comment by xige-16** [comment]
> If manually delete and restart the querynode pod, it keeps OOM. It seems that the load operation is still pending in querycoord or somewhere :(

if querynode restart, the load collection task will be executed automatically.

**Comment by xige-16** [comment]
QueryCoord will provide an interface to display the status of load collection. If there is not enough memory, a prompt is given.

**Comment by xige-16** [comment]
releate issue: #6370

**Comment by yanliang567** [comment]
@xige-16 #6370 was closed, so any updates for this issue?

**Comment by xige-16** [comment]
> @xige-16 #6370 was closed, so any updates for this issue?

#6370 hasn't fix the bug.

**Comment by bigsheeper** [comment]
/assign @yanliang567
need to verify after fixed

**Comment by yanliang567** [comment]
working on verification

**Comment by yanliang567** [comment]
keep repro on master-20210907-b710335
```
milvus-latest-datacoord-6cf8958589-v8vqb        1/1     Running            0          121m
milvus-latest-datanode-8445769758-d9pnj         1/1     Running            0          121m
milvus-latest-etcd-0                            1/1     Running            0          121m
milvus-latest-indexcoord-6f5649c5d-zfdkk        1/1     Running            0          121m
milvus-latest-indexnode-66f657459c-674kk        1/1     Running            0          121m
milvus-latest-minio-55dbc95f49-r7xwn            1/1     Running            0          121m
milvus-latest-proxy-b65874696-fklmx             1/1     Running            0          121m
milvus-latest-pulsar-5fc86664dc-kpskc           1/1     Running            0          121m
milvus-latest-querycoord-59f4b8df57-h6xq5       1/1     Running            0          121m
milvus-latest-querynode-6ffd85876-zxdlx         0/1     CrashLoopBackOff   5          121m
milvus-latest-rootcoord-7c6db66dd9-bbf85        1/1     Running            0          121m
```

**Comment by bigsheeper** [comment]
I'v verified this works on my local bare machine, but still repro on docker.
Currently, we use `gopsutil` (similar to free/top command in linux) to check the memory usage. However, even we set the memory limit on docker, `gopsutil` still shows the memory stats of host machine. It's none of the business of the util we use, it's a common problem on the system deployed on docker.

ref: https://faun.pub/understanding-docker-container-memory-limit-behavior-41add155236c
       https://ops.tips/blog/why-top-inside-container-wrong-memory/

In a word, #7434 works on bare machine, not docker. I suggest to manage milvus cluster by k8s instead of adding a memory checking inside the code. @yanliang567

**Comment by bigsheeper** [comment]
/assign @yanliang567 
#8765 have been merged, need to verify after fixed
