### ISSUE TITLE
Issue happens during play with hello_milvus.py in milvus cluster which deployed by docker-compose

### ISSUE THREAD

**Issue by godlockin** [milvus-io/milvus#6733]
env:
Mac

components:
docker-compose
anconda

steps:
1. download the scripts of docker-compose and hello_milvus.py
2. install related platforms
3. prepare python env by `conda create -n milvus python=3.9`
4. install python library by `pip install pymilvus-orm==2.0.0rc2`
5. start the cluster
6. switch the python env 
7. run the hello script
8. the following error happened
```bash
>>> collection.num_entities
Error: <BaseException: (code=1, message=getSegmentsOfCollection, err:ShowSegments failed, error: rpc error: code = Unimplemented desc = unknown method GetFlushedSegments for service milvus.proto.data.DataCoord)>
Error: <BaseException: (code=1, message=getSegmentsOfCollection, err:ShowSegments failed, error: rpc error: code = Unimplemented desc = unknown method GetFlushedSegments for service milvus.proto.data.DataCoord)>
Error: <BaseException: (code=1, message=getSegmentsOfCollection, err:ShowSegments failed, error: rpc error: code = Unimplemented desc = unknown method GetFlushedSegments for service milvus.proto.data.DataCoord)>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mymac/opt/anaconda3/envs/milvus/lib/python3.9/site-packages/pymilvus_orm/collection.py", line 347, in num_entities
    conn.flush([self._name])
  File "/Users/mymac/opt/anaconda3/envs/milvus/lib/python3.9/site-packages/pymilvus/client/stub.py", line 63, in handler
    raise e
  File "/Users/mymac/opt/anaconda3/envs/milvus/lib/python3.9/site-packages/pymilvus/client/stub.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/Users/mymac/opt/anaconda3/envs/milvus/lib/python3.9/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/Users/mymac/opt/anaconda3/envs/milvus/lib/python3.9/site-packages/pymilvus/client/stub.py", line 901, in flush
    return handler.flush(collection_names, timeout, **kwargs)
  File "/Users/mymac/opt/anaconda3/envs/milvus/lib/python3.9/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler
    raise e
  File "/Users/mymac/opt/anaconda3/envs/milvus/lib/python3.9/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
    return func(self, *args, **kwargs)
  File "/Users/mymac/opt/anaconda3/envs/milvus/lib/python3.9/site-packages/pymilvus/client/grpc_handler.py", line 995, in flush
    self._wait_for_flushed(collection_name, lambda: future.result().coll_segIDs[collection_name].data)
  File "/Users/mymac/opt/anaconda3/envs/milvus/lib/python3.9/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler
    raise e
  File "/Users/mymac/opt/anaconda3/envs/milvus/lib/python3.9/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
    return func(self, *args, **kwargs)
  File "/Users/mymac/opt/anaconda3/envs/milvus/lib/python3.9/site-packages/pymilvus/client/grpc_handler.py", line 965, in _wait_for_flushed
    if flushed(first_segment_ids):
  File "/Users/mymac/opt/anaconda3/envs/milvus/lib/python3.9/site-packages/pymilvus/client/grpc_handler.py", line 950, in flushed
    infos = self.get_persistent_segment_infos(collection_name, timeout, **kwargs)
  File "/Users/mymac/opt/anaconda3/envs/milvus/lib/python3.9/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler
    raise e
  File "/Users/mymac/opt/anaconda3/envs/milvus/lib/python3.9/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
    return func(self, *args, **kwargs)
  File "/Users/mymac/opt/anaconda3/envs/milvus/lib/python3.9/site-packages/pymilvus/client/grpc_handler.py", line 945, in get_persistent_segment_infos
    raise BaseException(status.error_code, status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=getSegmentsOfCollection, err:ShowSegments failed, error: rpc error: code = Unimplemented desc = unknown method GetFlushedSegments for service milvus.proto.data.DataCoord)>
>>>
```

the same error also happens when invoke collection.is_empty, collection.load()

**Comment by godlockin** [comment]
it looks like error happened during invoking some python api inside of orm library, and it's probable happen during the cluster level status sync against the error log

**Comment by godlockin** [comment]
this issue might be randomly happened among several times of cluster bootstrap, so I was wondering if there would be some connection issue or something cause this issue?

**Comment by czs007** [comment]
Very strange, this method is actually implemented. We are trying to reproduce this bug.

**Comment by julitschkaa** [comment]
I'm facing the same issue while trying to load a dataset into the dna_sequence_classifiaction_solution from the milvus bootcamp https://github.com/shiyu22/bootcamp/blob/master/solutions/dna_sequence_classification/quick_deploy/README.md
env: Ubuntu 20.04
I set up the system following the quick deploy
Yet API endpoint /text/load_data results in "unknown method GetFlushState" Error
