### ISSUE TITLE
Load collection get stuck after index with two index nodes.

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#6747]
#### Steps/Code to reproduce:
Client get stuck during loading collection after indexed.
test yaml:
```
client-configmap: client-acc-sift-ivf-flat
server-configmap: server-cluster-8c16m-indexnode-2
```
test log:
```
[2021-07-22 10:16:06,353] [   DEBUG] - Milvus insert run in 1.53s (milvus_benchmark.client:49)
[2021-07-22 10:16:08,449] [   DEBUG] - Milvus insert run in 1.48s (milvus_benchmark.client:49)
[2021-07-22 10:16:08,454] [   DEBUG] - End insert, start flush (milvus_benchmark.runners.accuracy:236)
[2021-07-22 10:16:10,994] [   DEBUG] - Milvus flush run in 2.54s (milvus_benchmark.client:49)
[2021-07-22 10:16:10,994] [   DEBUG] - End flush (milvus_benchmark.runners.accuracy:238)
[2021-07-22 10:16:10,997] [   DEBUG] - Row count: 1000000 in collection: <sift_128_euclidean> (milvus_benchmark.client:389)
[2021-07-22 10:16:10,997] [    INFO] - Table: sift_128_euclidean, row count: 1000000 (milvus_benchmark.runners.accuracy:240)
[2021-07-22 10:16:11,000] [    INFO] - None (milvus_benchmark.client:276)
[2021-07-22 10:16:11,000] [    INFO] - Drop index: sift_128_euclidean (milvus_benchmark.client:287)
[2021-07-22 10:16:11,002] [    INFO] - Re-create index: sift_128_euclidean (milvus_benchmark.runners.accuracy:245)
[2021-07-22 10:16:11,002] [    INFO] - Building index start, collection_name: sift_128_euclidean, index_type: IVF_FLAT, metric_type:
 L2 (milvus_benchmark.client:261)
[2021-07-22 10:16:11,002] [    INFO] - {'nlist': 1024} (milvus_benchmark.client:263)
[2021-07-22 10:16:39,016] [   DEBUG] - Milvus create_index run in 28.01s (milvus_benchmark.client:49)
[2021-07-22 10:16:39,019] [    INFO] - None (milvus_benchmark.client:276)
[2021-07-22 10:16:39,019] [    INFO] - {'index_type': 'flat', 'metric_type': None, 'index_param': None} (milvus_benchmark.runners.ac
curacy:247)
[2021-07-22 10:16:39,019] [    INFO] - Start load collection: sift_128_euclidean (milvus_benchmark.runners.accuracy:248)
```
after 6 h:
```
[2021-07-22 10:16:39,019] [    INFO] - {'index_type': 'flat', 'metric_type': None, 'index_param': None} (milvus_benchmark.runners.ac
curacy:247)
[2021-07-22 10:16:39,019] [    INFO] - Start load collection: sift_128_euclidean (milvus_benchmark.runners.accuracy:248)
[2021-07-22 16:13:16,098] [   ERROR] - Error: <BaseException: (code=1, message=Connect to rootcoord failed with error:
context canceled)> (pymilvus.client.grpc_handler:59)
[2021-07-22 16:13:16,099] [   ERROR] - Error: <BaseException: (code=1, message=Connect to rootcoord failed with error:
context canceled)> (pymilvus.client.grpc_handler:59)
[2021-07-22 16:13:16,099] [   ERROR] - Error: <BaseException: (code=1, message=Connect to rootcoord failed with error:
context canceled)> (pymilvus.client.grpc_handler:59)
[2021-07-22 16:13:16,099] [   ERROR] - <BaseException: (code=1, message=Connect to rootcoord failed with error:
context canceled)> (milvus_benchmark.main:112)
[2021-07-22 16:13:16,102] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 81, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/accuracy.py", line 250, in prepare
    self.milvus.load_collection(timeout=600)
  File "/src/milvus_benchmark/client.py", line 46, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 440, in load_collection
    return self._milvus.load_collection(collection_name, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 63, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 334, in load_collection
    return handler.load_collection("", collection_name=collection_name, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 800, in load_collection
    self.wait_for_loading_collection(collection_name)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 827, in wait_for_loading_collection
    for info in self.get_query_segment_infos(collection_name, timeout):
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 648, in get_query_segment_infos
    raise BaseException(status.error_code, status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=Connect to rootcoord failed with error:
context canceled)>
 (milvus_benchmark.main:113)
```
check server logs in :
https://kibana-dev.zilliz.cc/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-22T10:00:00.000Z',to:'2021-07-22T10:30:00.000Z'))&_a=(columns:!(log),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:ad1e1c50-c9d9-11eb-9e1a-b3dcad9693fd,key:kubernetes.pod_name,negate:!f,params:!(benchmark-gk7sh-1-milvus-indexnode-55cc6b5647-wfhjm),type:phrases,value:benchmark-gk7sh-1-milvus-indexnode-55cc6b5647-wfhjm),query:(bool:(minimum_should_match:1,should:!((match_phrase:(kubernetes.pod_name:benchmark-gk7sh-1-milvus-indexnode-55cc6b5647-wfhjm))))))),hideChart:!f,index:ad1e1c50-c9d9-11eb-9e1a-b3dcad9693fd,interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',desc)))

no output log print in indexnodes.
```
NAME                                                   READY   STATUS    RESTARTS   AGE
benchmark-gk7sh-1-etcd-0                               1/1     Running   0          34s
benchmark-gk7sh-1-milvus-datacoord-5986787bd9-7zk48    1/1     Running   0          33s
benchmark-gk7sh-1-milvus-datanode-6f56866b86-sr7b5     1/1     Running   0          34s
benchmark-gk7sh-1-milvus-indexcoord-6f5bb56b68-nzvnk   1/1     Running   0          34s
benchmark-gk7sh-1-milvus-indexnode-55cc6b5647-dn9j2    1/1     Running   0          34s
benchmark-gk7sh-1-milvus-indexnode-55cc6b5647-wfhjm    1/1     Running   0          34s
benchmark-gk7sh-1-milvus-proxy-766d54f56-bw2dg         1/1     Running   0          33s
benchmark-gk7sh-1-milvus-pulsar-5f597d55b8-nwcbp       1/1     Running   0          33s
benchmark-gk7sh-1-milvus-querycoord-6cfcc5f6bc-fdvq4   1/1     Running   0          34s
benchmark-gk7sh-1-milvus-querynode-8477b9884f-xc5mt    1/1     Running   0          34s
benchmark-gk7sh-1-milvus-rootcoord-5bfbc69485-tsdgq    1/1     Running   0          34s
```
#### Expected result:

load finished in 2 mins 
#### Actual results:

after 30 mins, still get no response

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-dev12
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by scsven** [comment]
@milvus-io/sig-testing

**Comment by xige-16** [comment]
[WARN] [logger.go:51] ["grpc: addrConn.createTransport failed to connect to {benchmark-gk7sh-1-etcd:2379 <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 10.96.74.176:2379: i/o timeout\". Reconnecting..."]

**Comment by xige-16** [comment]
queryCoord failed to connect to etcd, the etcd server was not stable.

**Comment by del-zhenwu** [comment]
> queryCoord failed to connect to etcd, the etcd server was not stable.

Timeout set 6h in test framework, then it will uninstall the milvus cluster also with etcd.

**Comment by xiaofan-luan** [comment]
seems to be another etcd issue

**Comment by godchen0212** [comment]
This problem is consistent with the previous problems that occurred when etcd resources were insufficient.
Please observe whether this problem still exists.

**Comment by del-zhenwu** [comment]
> This problem is consistent with the previous problems that occurred when etcd resources were insufficient.
> After the ci is fixed, it is not easy to reproduce the problem of etcd. Please observe whether this problem still exists.

in benchmark, each test suite will start with a new etcd.

**Comment by xiaofan-luan** [comment]
close for now, the etcd issue still need to be tracked by other issues
