### ISSUE TITLE
Load collection more than 6 hours on sift-1m dataset

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#6797]
#### Steps/Code to reproduce:
```
[2021-07-25 18:05:10,096] [   DEBUG] - Milvus insert run in 1.88s (milvus_benchmark.client:49)
[2021-07-25 18:05:10,101] [   DEBUG] - End insert, start flush (milvus_benchmark.runners.accuracy:236)
[2021-07-25 18:05:13,139] [   DEBUG] - Milvus flush run in 3.04s (milvus_benchmark.client:49)
[2021-07-25 18:05:13,140] [   DEBUG] - End flush (milvus_benchmark.runners.accuracy:238)
[2021-07-25 18:05:13,142] [   DEBUG] - Row count: 1000000 in collection: <sift_128_euclidean> (milvus_benchmark.client:389)
[2021-07-25 18:05:13,155] [    INFO] - Table: sift_128_euclidean, row count: 1000000 (milvus_benchmark.runners.accuracy:240)
[2021-07-25 18:05:13,193] [    INFO] - None (milvus_benchmark.client:276)
[2021-07-25 18:05:13,194] [    INFO] - Drop index: sift_128_euclidean (milvus_benchmark.client:287)
[2021-07-25 18:05:13,196] [    INFO] - Re-create index: sift_128_euclidean (milvus_benchmark.runners.accuracy:245)
[2021-07-25 18:05:13,197] [    INFO] - Building index start, collection_name: sift_128_euclidean, index_type: IVF_FLAT, metric_type:
 L2 (milvus_benchmark.client:261)
[2021-07-25 18:05:13,198] [    INFO] - {'nlist': 1024} (milvus_benchmark.client:263)
[2021-07-25 18:06:07,984] [   DEBUG] - Milvus create_index run in 54.79s (milvus_benchmark.client:49)
[2021-07-25 18:06:07,987] [    INFO] - None (milvus_benchmark.client:276)
[2021-07-25 18:06:07,987] [    INFO] - {'index_type': 'flat', 'metric_type': None, 'index_param': None} (milvus_benchmark.runners.ac
curacy:247)
[2021-07-25 18:06:07,987] [    INFO] - Start load collection: sift_128_euclidean (milvus_benchmark.runners.accuracy:248)
[2021-07-26 00:02:22,101] [   ERROR] - Error: <BaseException: (code=1, message=describe collection failed: context canceled)> (pymil
vus.client.grpc_handler:59)
[2021-07-26 00:02:22,103] [   ERROR] - Error: <BaseException: (code=1, message=describe collection failed: context canceled)> (pymil
vus.client.grpc_handler:59)
[2021-07-26 00:02:22,104] [   ERROR] - Error: <BaseException: (code=1, message=describe collection failed: context canceled)> (pymil
vus.client.grpc_handler:59)
[2021-07-26 00:02:22,104] [   ERROR] - <BaseException: (code=1, message=describe collection failed: context canceled)> (milvus_bench
mark.main:112)
[2021-07-26 00:02:22,107] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 81, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/accuracy.py", line 250, in prepare
    self.milvus.load_collection(timeout=600)
  File "/src/milvus_benchmark/client.py", line 46, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 440, in load_collection
    return self._milvus.load_collection(collection_name, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 63, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 51, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 334, in load_collection
    return handler.load_collection("", collection_name=collection_name, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 800, in load_collection
    self.wait_for_loading_collection(collection_name)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 827, in wait_for_loading_collection
    for info in self.get_query_segment_infos(collection_name, timeout):
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 648, in get_query_segment_infos
    raise BaseException(status.error_code, status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=describe collection failed: context canceled)>
 (milvus_benchmark.main:113)
```
1. create collection
2. insert 50,000 entities per request, total 1m entities
3. drop index
4. create index IVF_FLAT/nlist: 1024
5. load collection more than 6 hours

test yaml:
```
client-configmap: client-acc-sift-ivf-flat
server-configmap: server-single-8c16m
```
#### Actual results:
https://kibana-dev.zilliz.cc/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-25T18:00:00.000Z',to:'2021-07-25T18:30:00.000Z'))&_a=(columns:!(log),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:ad1e1c50-c9d9-11eb-9e1a-b3dcad9693fd,key:kubernetes.pod_name,negate:!f,params:!(benchmark-cron-1627236000-1-milvus-standalone-65c69767-gfpc9),type:phrases,value:benchmark-cron-1627236000-1-milvus-standalone-65c69767-gfpc9),query:(bool:(minimum_should_match:1,should:!((match_phrase:(kubernetes.pod_name:benchmark-cron-1627236000-1-milvus-standalone-65c69767-gfpc9)))))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:ad1e1c50-c9d9-11eb-9e1a-b3dcad9693fd,key:log,negate:!f,params:!(error),type:phrases,value:error),query:(bool:(minimum_should_match:1,should:!((match_phrase:(log:error))))))),hideChart:!f,index:ad1e1c50-c9d9-11eb-9e1a-b3dcad9693fd,interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',desc)))
```




[2021/07/25 18:06:12.766 +00:00] [ERROR] [segment_loader.go:103] ["AppendIndex failed, C runtime error detected, error code = 1, error msg = map::at"] [stack="github.com/milvus-io/milvus/internal/log.Error\n\t/go/src/github.com/milvus-io/milvus/internal/log/global.go:42\ngithub.com/milvus-io/milvus/internal/querynode.(*segmentLoader).loadSegment\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/segment_loader.go:103\ngithub.com/milvus-io/milvus/internal/querynode.(*segmentLoader).loadSegmentOfConditionGRPC\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/segment_loader.go:59\ngithub.com/milvus-io/milvus/internal/querynode.(*loadSegmentsTask).Execute\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/task.go:349\ngithub.com/milvus-io/milvus/internal/querynode.(*taskScheduler).processTask\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:56\ngithub.com/milvus-io/milvus/internal/querynode.(*taskScheduler).loadAndReleaseLoop\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/task_scheduler.go:73"]

 

<br class="Apple-interchange-newline">
```

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): 
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-dev12
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by yanliang567** [comment]
@scsven please specify what information do you want?

**Comment by xige-16** [comment]
querynode failed to append index lead to load collection hang. please add more log info to debug the operation of append index. @fishpenguin  @godchen0212

**Comment by del-zhenwu** [comment]
also on dataset sift-50m:
https://argo-test.zilliz.cc/workflows/qa/benchmark-46pdt?tab=workflow&nodeId=benchmark-46pdt-4153134213&sidePanel=logs:benchmark-46pdt-4153134213:main

**Comment by xige-16** [comment]
The reason is that the slide meta value in the index file is incorrectly filled in. I'll fix the problem right away.

**Comment by del-zhenwu** [comment]
fixed
