### ISSUE TITLE
Failed to deploy the cluster milvus with image.all.pullPolicy=Always helm chart

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#6809]
#### Steps/Code to reproduce:
1. deploy cluster milvus with helm `image.all.pullPolicy=Always`
```
helm install --set image.all.repository=milvusdb/milvus-dev  --set image.all.tag=master-latest --set cluster.enabled=true --set image.all.pullPolicy=Always --set service.type=LoadBalancer clu-zong .
```
2. pod status are all running, but not available
```
clu-zong-etcd-0                               1/1     Running   0          24m
clu-zong-milvus-datacoord-669d6b55b5-wmscr    1/1     Running   0          24m
clu-zong-milvus-datanode-5b6bc8d884-db8dl     1/1     Running   1          24m
clu-zong-milvus-indexcoord-9fd46f856-pkn24    1/1     Running   0          24m
clu-zong-milvus-indexnode-748d876957-xv4zg    1/1     Running   0          24m
clu-zong-milvus-proxy-8f6b4b684-mjr7r         1/1     Running   0          24m
clu-zong-milvus-pulsar-74d8d66456-7g7wp       1/1     Running   0          24m
clu-zong-milvus-querycoord-5bd977c9f-xgg7w    1/1     Running   0          24m
clu-zong-milvus-querynode-6ccdf6d77f-mh6vg    1/1     Running   0          24m
clu-zong-milvus-rootcoord-66b9f77957-5zsfp    1/1     Running   0          24m
clu-zong-minio-f965db98-6gl4v                 1/1     Running   0          24m
```
```
from pymilvus import Milvus
c = Milvus("10.98.0.8", 19530)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 122, in __init__
    self._update_connection_pool(channel=channel)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 176, in _update_connection_pool
    self._wait_for_healthy()
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/Users/nausicca/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 147, in _wait_for_healthy
    raise Exception("server is not healthy, please try again later")
Exception: server is not healthy, please try again later
```
3. helm install with `--set image.all.pullPolicy=IfNotPresent` successfully once.

#### Expected result:
Milvus available

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):
  e43b43e
- Deployment mode(standalone or cluster):
  cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by yanliang567** [comment]
this could be a dup to issue #6694, and it does not matter with image.all.pullPolicy=Always or not.

**Comment by czs007** [comment]
It seems that it is because etcd is deployed independently and the remaining data is not cleared.

**Comment by yanliang567** [comment]
this is manually, etcd was re-installed everytime running helm install

**Comment by ThreadDao** [comment]
@yanliang567 No existed etcd pod. Just first helm install. The server not healthy did all happen when image.all.pullPolicy=Always. I also encountered this problem in commit `e45cb6c`
