### ISSUE TITLE
Search timeout when nprobe value set as 128

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#6828]
#### Steps/Code to reproduce:
test yaml
```
client-configmap: client-acc-sift-ivf-sq8
server-configmap: server-single-8c16m
```
```
[2021-07-27 03:39:00,701] [   DEBUG] - Milvus query run in 5.95s (milvus_benchmark.client:49)
[2021-07-27 03:39:01,616] [    INFO] - {'acc': 0.982} (milvus_benchmark.main:94)
[2021-07-27 03:39:01,653] [   DEBUG] - {'type': 'ann_accuracy', 'value': {'acc': 0.982}} (milvus_benchmark.main:102)
[2021-07-27 03:39:01,654] [   DEBUG] - {'_version': '0.1', '_type': 'case', 'run_id': 1627357017, 'mode': 'local', 'server': <milvus
_benchmark.metrics.models.server.Server object at 0x7f7f8c6f6c18>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware ob
ject at 0x7f7f8c6f6b38>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7f7f8c6f6a58>, 'status': 'RUN_SUCC', 'err_messa
ge': '', 'collection': {'dimension': 128, 'metric_type': 'l2', 'dataset_name': 'sift_128_euclidean'}, 'index': {'index_type': 'ivf_s
q8', 'index_param': {'nlist': 1024}}, 'search': {'nq': 10000, 'topk': 10, 'search_param': {'nprobe': 64}, 'filter': []}, 'run_params
': None, 'metrics': {'type': 'ann_accuracy', 'value': {'acc': 0.982}}, 'datetime': '2021-07-27 03:36:57.690741', 'type': 'metric'} (
milvus_benchmark.metric.api:29)
[2021-07-27 03:39:11,802] [   DEBUG] - Milvus query run in 10.12s (milvus_benchmark.client:49)
[2021-07-27 03:39:12,597] [    INFO] - {'acc': 0.985} (milvus_benchmark.main:94)
[2021-07-27 03:39:12,598] [   DEBUG] - {'type': 'ann_accuracy', 'value': {'acc': 0.985}} (milvus_benchmark.main:102)
[2021-07-27 03:39:12,598] [   DEBUG] - {'_version': '0.1', '_type': 'case', 'run_id': 1627357017, 'mode': 'local', 'server': <milvus
_benchmark.metrics.models.server.Server object at 0x7f7f8c6f6828>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware ob
ject at 0x7f7f8c6f6780>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7f7f8c6f66d8>, 'status': 'RUN_SUCC', 'err_messa
ge': '', 'collection': {'dimension': 128, 'metric_type': 'l2', 'dataset_name': 'sift_128_euclidean'}, 'index': {'index_type': 'ivf_s
q8', 'index_param': {'nlist': 1024}}, 'search': {'nq': 10000, 'topk': 10, 'search_param': {'nprobe': 128}, 'filter': []}, 'run_param
s': None, 'metrics': {'type': 'ann_accuracy', 'value': {'acc': 0.985}}, 'datetime': '2021-07-27 03:36:57.690741', 'type': 'metric'}
(milvus_benchmark.metric.api:29)
[2021-07-27 03:44:13,480] [   ERROR] -
Addr [benchmark-cron-6lf5t-3-milvus.qa-milvus.svc.cluster.local:19530] _execute_search_requests
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "{"created":"@1627357453.475071878","description":"Error received from peer ipv4:10.96.56.175:19530","f
ile":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
        {'API start': '2021-07-27 03:39:13.387770', 'RPC start': '2021-07-27 03:39:13.387785', 'RPC error': '2021-07-27 03:44:13.480
563'} (pymilvus.client.grpc_handler:74)
W
        {'API start': '2021-07-27 03:39:13.387770', 'RPC start': '2021-07-27 03:39:13.387785', 'RPC error': '2021-07-27 03:44:13.480
563'} (pymilvus.client.grpc_handler:74)
[2021-07-27 03:44:13,481] [   ERROR] -
Addr [benchmark-cron-6lf5t-3-milvus.qa-milvus.svc.cluster.local:19530] search
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "{"created":"@1627357453.475071878","description":"Error received from peer ipv4:10.96.56.175:19530","f
ile":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
        {'API start': '2021-07-27 03:39:12.636322', 'RPC start': '2021-07-27 03:39:12.636338', 'RPC error': '2021-07-27 03:44:13.481
699'} (pymilvus.client.grpc_handler:74)
[2021-07-27 03:44:15,491] [   DEBUG] - Milvus query run in 302.86s (milvus_benchmark.client:49)
[2021-07-27 03:44:15,494] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 90, in run_suite
    result = runner.run_case(case_metric, **case)
  File "/src/milvus_benchmark/runners/accuracy.py", line 258, in run_case
    result_ids = self.milvus.get_ids(query_res)
  File "/src/milvus_benchmark/client.py", line 342, in get_ids
    for res in result:
TypeError: 'NoneType' object is not iterable
 (milvus_benchmark.main:93)
[2021-07-27 03:44:15,494] [    INFO] - None (milvus_benchmark.main:94)
[2021-07-27 03:44:15,495] [   DEBUG] - {'type': 'ann_accuracy', 'value': {}} (milvus_benchmark.main:102)
[2021-07-27 03:44:15,496] [   DEBUG] - {'_version': '0.1', '_type': 'case', 'run_id': 1627357017, 'mode': 'local', 'server': <milvus
_benchmark.metrics.models.server.Server object at 0x7f7f8c6f66a0>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware ob
ject at 0x7f7f8c6f60f0>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7f7f8c76f208>, 'status': 'RUN_FAILED', 'err_mes
sage': '\'NoneType\' object is not iterable\nTraceback (most recent call last):\n  File "main.py", line 90, in run_suite\n    result
 = runner.run_case(case_metric, **case)\n  File "/src/milvus_benchmark/runners/accuracy.py", line 258, in run_case\n    result_ids =
 self.milvus.get_ids(query_res)\n  File "/src/milvus_benchmark/client.py", line 342, in get_ids\n    for res in result:\nTypeError:
\'NoneType\' object is not iterable\n', 'collection': {'dimension': 128, 'metric_type': 'l2', 'dataset_name': 'sift_128_euclidean'},
 'index': {'index_type': 'ivf_sq8', 'index_param': {'nlist': 1024}}, 'search': {'nq': 10000, 'topk': 10, 'search_param': {'nprobe':
256}, 'filter': []}, 'run_params': None, 'metrics': {'type': 'ann_accuracy', 'value': {}}, 'datetime': '2021-07-27 03:36:57.690741',
 'type': 'metric'} (milvus_benchmark.metric.api:29)
[2021-07-27 03:44:53,292] [   DEBUG] - Milvus query run in 37.76s (milvus_benchmark.client:49)
[2021-07-27 03:44:54,095] [    INFO] - {'acc': 0.986} (milvus_benchmark.main:94)
[2021-07-27 03:44:54,096] [   DEBUG] - {'type': 'ann_accuracy', 'value': {'acc': 0.986}} (milvus_benchmark.main:102)
[2021-07-27 03:44:54,097] [   DEBUG] - {'_version': '0.1', '_type': 'case', 'run_id': 1627357017, 'mode': 'local', 'server': <milvus
_benchmark.metrics.models.server.Server object at 0x7f7f8c76f358>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware ob
ject at 0x7f7f8c76f400>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7f7f8c76f2e8>, 'status': 'RUN_SUCC', 'err_messa
ge': '', 'collection': {'dimension': 128, 'metric_type': 'l2', 'dataset_name': 'sift_128_euclidean'}, 'index': {'index_type': 'ivf_s
q8', 'index_param': {'nlist': 1024}}, 'search': {'nq': 10000, 'topk': 10, 'search_param': {'nprobe': 512}, 'filter': []}, 'run_param
s': None, 'metrics': {'type': 'ann_accuracy', 'value': {'acc': 0.986}}, 'datetime': '2021-07-27 03:36:57.690741', 'type': 'metric'}
(milvus_benchmark.metric.api:29)
```

#### Expected result:
nprobe: [64, 128, 256] search successfully

#### Actual results:
nprobe: [64, 256] search successfully
nprobe: [128] search  failed

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): 
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-rc3-dev6
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others: 

#### Additional context:
server logs:
https://kibana-dev.zilliz.cc/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-27T03:38:18.067Z',to:'2021-07-27T03:45:04.577Z'))&_a=(columns:!(log),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:ad1e1c50-c9d9-11eb-9e1a-b3dcad9693fd,key:kubernetes.pod_name,negate:!f,params:!(benchmark-cron-6lf5t-3-milvus-standalone-5554c65c4-8nrrz),type:phrases,value:benchmark-cron-6lf5t-3-milvus-standalone-5554c65c4-8nrrz),query:(bool:(minimum_should_match:1,should:!((match_phrase:(kubernetes.pod_name:benchmark-cron-6lf5t-3-milvus-standalone-5554c65c4-8nrrz)))))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:ad1e1c50-c9d9-11eb-9e1a-b3dcad9693fd,key:log,negate:!f,params:!(error),type:phrases,value:error),query:(bool:(minimum_should_match:1,should:!((match_phrase:(log:error))))))),hideChart:!f,index:ad1e1c50-c9d9-11eb-9e1a-b3dcad9693fd,interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',desc)))
```




[2021/07/27 03:44:12.405 +00:00] [DEBUG] [impl.go:1306] ["Search Finished"] [error=timeout] [role=Proxy-] [msgID=426601890585086521] [timestamp=426601913352192031] [db=] [collection=sift_128_euclidean] [partitions="[]"] [dsl="{\"bool\":{\"must\":[{\"vector\":{\"float_vector\":{\"topk\":10,\"query\":\"$0\",\"metric_type\":\"L2\",\"params\":{\"nprobe\":256}}}}]}}"] [len(PlaceholderGroup)=52540]

 

<br class="Apple-interchange-newline">
```

**Comment by xige-16** [comment]
I failed to get the full log info.

**Comment by del-zhenwu** [comment]
> Sorry, I failed to get the full log info.

https://podlog-dev.zilliz.cc/pod-logs?pod-name=benchmark-cron-6lf5t-3-milvus-standalone-5554c65c4-8nrrz&started-at=2021-07-26T00:00:00

**Comment by wangting0128** [comment]
> @wangting0128 could you please help to repro this issue and collect the logs

copy that

**Comment by wangting0128** [comment]
No recurrence
