### ISSUE TITLE
Build index Error: <BaseException: (code=1, message=get collection statistics resp is nil)>

### ISSUE THREAD

**Issue by Bennu-Li** [milvus-io/milvus#6836]
#### Steps/Code to reproduce:
 When I building ivf_sq8 index for the collection that has 1 billion vectors, the client throw an error:
<BaseException: (code=1, message=get collection statistics resp is nil)>

<img width="1596" alt="截屏2021-07-27 下午4 50 55" src="https://user-images.githubusercontent.com/53458891/127125469-af65ba68-465f-487e-a479-e9c041953e8b.png">

But the Milvus server is still building the index.

[rootcoord.log.zip](https://github.com/milvus-io/milvus/files/6883945/rootcoord.log.zip)
[indexcoord.log.zip](https://github.com/milvus-io/milvus/files/6883949/indexcoord.log.zip)
[proxy.log.zip](https://github.com/milvus-io/milvus/files/6883951/proxy.log.zip)

#### Environment:
- Milvus version(v2.0.0-RC2):
- Deployment mode(cluster):
- SDK version(pymilvus v2.0.0rc2):

**Comment by xiaocai2333** [comment]
The datacoord crashed， please take a look. @sunby 
/assign @sunby

**Comment by sunby** [comment]
@Bennu-Li Can you provide the datanode log?

**Comment by NicoYuan1986** [comment]
I met the same error while creating index. Here is the detailed information.
```
[2022-09-14T06:44:25.655Z] [2022-09-14 06:44:13 - ERROR - pymilvus.decorators]: RPC error: [create_index], <MilvusException: (code=1, message=get collection statistics resp is nil)>, <Time:{'RPC start': '2022-09-14 06:44:07.696434', 'RPC error': '2022-09-14 06:44:13.616082'}> (decorators.py:100)
[2022-09-14T06:44:25.655Z] [2022-09-14 06:44:13 - ERROR - ci_test]: Traceback (most recent call last):
[2022-09-14T06:44:25.655Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2022-09-14T06:44:25.655Z]     res = func(*args, **_kwargs)
[2022-09-14T06:44:25.655Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2022-09-14T06:44:25.655Z]     return func(*arg, **kwargs)
[2022-09-14T06:44:25.655Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 1087, in create_index
[2022-09-14T06:44:25.655Z]     timeout=timeout, **kwargs)
[2022-09-14T06:44:25.655Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 101, in handler
[2022-09-14T06:44:25.655Z]     raise e
[2022-09-14T06:44:25.655Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 97, in handler
[2022-09-14T06:44:25.655Z]     return func(*args, **kwargs)
[2022-09-14T06:44:25.655Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 127, in handler
[2022-09-14T06:44:25.655Z]     ret = func(self, *args, **kwargs)
[2022-09-14T06:44:25.655Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 79, in handler
[2022-09-14T06:44:25.655Z]     raise e
[2022-09-14T06:44:25.655Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/decorators.py", line 50, in handler
[2022-09-14T06:44:25.655Z]     return func(self, *args, **kwargs)
[2022-09-14T06:44:25.655Z]   File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 576, in create_index
[2022-09-14T06:44:25.655Z]     raise MilvusException(status.error_code, status.reason)
[2022-09-14T06:44:25.655Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=get collection statistics resp is nil)>
[2022-09-14T06:44:25.655Z]  (api_request.py:39)
[2022-09-14T06:44:25.655Z] [2022-09-14 06:44:13 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=get collection statistics resp is nil)> (api_request.py:40)
```
collection name: search_collection_PtAkKjQl
log: [artifacts-milvus-distributed-PR-19184-2-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20HA%20CI/job/PR-19184/2/artifact/artifacts-milvus-distributed-PR-19184-2-pymilvus-e2e-logs.tar.gz)

**Comment by binbinlv** [comment]
Same error in the following CI:

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-19193/2/pipeline/

1. log:
[artifacts-milvus-distributed-PR-19193-2-pymilvus-e2e-logs.tar.gz](https://jenkins.milvus.io:18080/job/Milvus%20HA%20CI/job/PR-19193/2/artifact/artifacts-milvus-distributed-PR-19193-2-pymilvus-e2e-logs.tar.gz)

2. collection name: search_collection_LUJQYUlS
3. Failed timeline: [2022-09-14T06:59:28.463Z] [gw5] [ 40%] FAILED testcases/test_search.py::TestCollectionSearchInvalid::test_search_different_index_invalid_params[IVF_FLAT-params0]

**Comment by xiaocai2333** [comment]
fixed, please verify
/assign @binbinlv

**Comment by binbinlv** [comment]
It has not appeared from my side, fixed.

so this could be closed.
