### ISSUE TITLE
Error is reported when calculating distance between vectors from existed collection

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#6872]
#### Steps/Code to reproduce:
```python
from pymilvus_orm import CollectionSchema, FieldSchema
from pymilvus_orm import Collection
from pymilvus_orm import connections
from pymilvus_orm.types import DataType
dim = 128
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
schema = CollectionSchema(fields=[int64_field, float_field, float_vector])
connections.connect()
import numpy as np
collection = Collection("test_search_collection_binbin_6", schema=schema)
collection.create_partition(partition_name="search_partition_1", description="search partition")
par = collection.partitions
nb = 1000
nq = 2
limit = 10
import random
default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors],  par[0].name)
collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors],  par[1].name)
collection.load()
collection.num_entities
vectors_l = {"ids": [1, 2, 3, 4, 5], "collection": collection.name,"partition": par[0].name, "field": "float_vector"}
vectors_r = {"ids": [1, 2, 3, 4, 5], "collection": collection.name,"partition": par[1].name, "field": "float_vector"}
from pymilvus_orm import utility
params = {"metric": "L2", "sqrt": True}
results = utility.calc_distance(vectors_l, vectors_r, params)
```

#### Expected result:
distance calculated successfully

#### Actual results:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pymilvus_orm/utility.py", line 335, in calc_distance
    raise ResultError("Returned distance array is illegal")
pymilvus_orm.exceptions.ResultError: Returned distance array is illegal
```

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): latest
- Deployment mode(standalone or cluster):standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
Name: pymilvus
Version: 2.0.0rc3.dev6
Name: pymilvus-orm
Version: 2.0.0rc3.dev9

- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by yhmo** [comment]
The calc_distance() depends on retrieve() to retrieve vectors data from disk/memory. Currently the retrieve() function cannot read vectors data from disk, so calc_distance() failed to calculate distance.

**Comment by binbinlv** [comment]
OK, I will disable tests for this part. And could you remind me when the function for vectors from collection works and then I will enable these test cases. And thanks for clarify. @yhmo

**Comment by binbinlv** [comment]
Verified, and it has been fixed.

milvus: bdb8396
Name: pymilvus
Version: 2.0.0rc3.dev16
Name: pymilvus-orm
Version: 2.0.0rc3.dev15
