### ISSUE TITLE
Assert 'BaseException' object has no attribute 'code' when creating index with invalid parameters

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#6921]
#### Steps/Code to reproduce:

```python
from pymilvus_orm import CollectionSchema, FieldSchema
from pymilvus_orm import Collection
from pymilvus_orm import connections
from pymilvus_orm.types import DataType
dim = 8
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
schema = CollectionSchema(fields=[int64_field, float_field, float_vector])
connections.connect()
import numpy as np
collection = Collection("test_search_collection_binbin_6", schema=schema)
nb = 5000
nq = 2
limit = 10
import random
default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors])
collection.num_entities
index = "IVF_PQ"
params = {"nlist": 128, "m": 16, "nbits": 8}
default_index = {"index_type": index, "params": params, "metric_type": "L2"}
collection.create_index("float_vector", default_index)
```

#### Expected result:
Only error message for invalid index parameters, no other asserts

#### Actual results:
```
Error: (1, 'BuildFloatVecIndexWithoutIds failed, C runtime error detected, error code = 1, err msg = something wrong in index parameters!')
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 744, in create_index
    raise BaseException(Status.UNEXPECTED_ERROR, fail_reason)
BaseException: (1, 'BuildFloatVecIndexWithoutIds failed, C runtime error detected, error code = 1, err msg = something wrong in index parameters!')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pymilvus_orm/collection.py", line 896, in create_index
    timeout=kwargs.pop("timeout", None), **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 66, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 52, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 753, in create_index
    return handler.create_index(collection_name, field_name, params, timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 60, in handler
    if e.code == Status.ILLEGAL_COLLECTION_NAME:
AttributeError: 'BaseException' object has no attribute 'code'
```

#### Environment:
- Milvus version(): 7307332
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
Name: pymilvus
Version: 2.0.0rc3.dev12
Name: pymilvus-orm
Version: 2.0.0rc3.dev10

- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by yanliang567** [comment]
add critical label for blocking ci
