### ISSUE TITLE
Standalone init tso crashed

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#6955]
#### Steps/Code to reproduce:
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-6950/2/pipeline/72

#### Actual results:
```
2021-08-02T10:09:55.93781091Z stdout F [2021/08/02 10:09:55.937 +00:00] [DEBUG] [index_coord.go:597] ["IndexCoord assignTaskLoop"] ["Available IndexNode IDs"="[36]"]
2021-08-02T10:09:55.937916981Z stdout F [2021/08/02 10:09:55.937 +00:00] [DEBUG] [index_coord.go:602] ["IndexCoord assignTaskLoop"] ["Unassigned tasks number"=0] ["Unassigned tasks meta"=null]
2021-08-02T10:09:56.194627902Z stderr F panic: runtime error: invalid memory address or nil pointer dereference
2021-08-02T10:09:56.194649818Z stderr F [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x11c6261]
2021-08-02T10:09:56.194653263Z stderr F 
2021-08-02T10:09:56.19466021Z stderr F goroutine 105 [running]:
2021-08-02T10:09:56.194663567Z stderr F github.com/milvus-io/milvus/internal/kv/etcd.(*EtcdKV).Save(0xc000669420, 0xc000816150, 0x2f, 0xc0005c81b8, 0x8, 0x0, 0x0)
2021-08-02T10:09:56.194678083Z stderr F 	/go/src/github.com/milvus-io/milvus/internal/kv/etcd/etcd_kv.go:165 +0x121
2021-08-02T10:09:56.194681766Z stderr F github.com/milvus-io/milvus/internal/tso.(*timestampOracle).saveTimestamp(0xc0000a3b30, 0xc03a0efdcb1ed5dc, 0x62ded88de, 0x3249c40, 0xc03a0efdcb1ed5dc, 0x62ded88de)
2021-08-02T10:09:56.194686855Z stderr F 	/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:89 +0x103
2021-08-02T10:09:56.194689774Z stderr F github.com/milvus-io/milvus/internal/tso.(*timestampOracle).InitTimestamp(0xc0000a3b30, 0xc0000a3b01, 0xc003202020)
2021-08-02T10:09:56.194692933Z stderr F 	/go/src/github.com/milvus-io/milvus/internal/tso/tso.go:113 +0x85
2021-08-02T10:09:56.194695547Z stderr F github.com/milvus-io/milvus/internal/tso.(*GlobalTSOAllocator).Initialize(0xc003202010, 0xc003202020, 0x2522700)
2021-08-02T10:09:56.194698396Z stderr F 	/go/src/github.com/milvus-io/milvus/internal/tso/global_allocator.go:79 +0x2e
2021-08-02T10:09:56.194701164Z stderr F github.com/milvus-io/milvus/internal/allocator.(*GlobalIDAllocator).Initialize(...)
2021-08-02T10:09:56.194704384Z stderr F 	/go/src/github.com/milvus-io/milvus/internal/allocator/global_id.go:41
2021-08-02T10:09:56.194707364Z stderr F github.com/milvus-io/milvus/internal/querycoord.NewTaskScheduler(0x2512960, 0xc00038be00, 0xc000277c00, 0xc0004ec6c0, 0xc000417ee0, 0x252ca00, 0xc0004f11d0, 0x2528220, 0xc0003a4000, 0x7fa8f118aae0, ...)
2021-08-02T10:09:56.194713989Z stderr F 	/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:152 +0x2ee
2021-08-02T10:09:56.19471684Z stderr F github.com/milvus-io/milvus/internal/querycoord.(*QueryCoord).Init.func1(0x216a4e0, 0x12c)
2021-08-02T10:09:56.194720278Z stderr F 	/go/src/github.com/milvus-io/milvus/internal/querycoord/query_coord.go:98 +0x211
2021-08-02T10:09:56.194722935Z stderr F github.com/milvus-io/milvus/internal/util/retry.Do(0x2512960, 0xc00038be00, 0xc000cfb868, 0xc000cfb860, 0x1, 0x1, 0x3249c40, 0x0)
2021-08-02T10:09:56.194725974Z stderr F 	/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:31 +0x23f
2021-08-02T10:09:56.194728802Z stderr F github.com/milvus-io/milvus/internal/querycoord.(*QueryCoord).Init(0xc000294000, 0xa, 0xc000277800)
2021-08-02T10:09:56.194731671Z stderr F 	/go/src/github.com/milvus-io/milvus/internal/querycoord/query_coord.go:102 +0xdd
2021-08-02T10:09:56.194734552Z stderr F github.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).init(0xc00024cee0, 0xc00024ce00, 0x0)
2021-08-02T10:09:56.194737539Z stderr F 	/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/service.go:167 +0x118f
2021-08-02T10:09:56.194740349Z stderr F github.com/milvus-io/milvus/internal/distributed/querycoord.(*Server).Run(0xc00024cee0, 0xffffffffffffffff, 0x2513360)
2021-08-02T10:09:56.194743122Z stderr F 	/go/src/github.com/milvus-io/milvus/internal/distributed/querycoord/service.go:78 +0x2f
2021-08-02T10:09:56.194745979Z stderr F github.com/milvus-io/milvus/cmd/components.(*QueryCoord).Run(...)
2021-08-02T10:09:56.194748648Z stderr F 	/go/src/github.com/milvus-io/milvus/cmd/components/query_coord.go:41
2021-08-02T10:09:56.194751449Z stderr F github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runQueryCoord.func1(0x23a7d01, 0x2512960, 0xc0005aea80, 0xc000010030, 0xc000048030)
2021-08-02T10:09:56.194754627Z stderr F 	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:156 +0x105
2021-08-02T10:09:56.194757366Z stderr F created by github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runQueryCoord
2021-08-02T10:09:56.194760056Z stderr F 	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:139 +0xb0
```

**Comment by XuanYang-cn** [comment]
EtcdKV didn't check `clientv3.Client` nil.

```go
func EtcdKV(etcdEndPoints []string, root string) (*EtcdKV, error) {
    client, err := clientv3.New(clientv3.Config{
        Endpoints:   etcdEndpoints,
        DialTimeout: 5 * time.Second,
    })
    if err != nil {
        return nil, err
    }

    kv := &EtcdKV{
        client: client,
        rootPath: root, 
    }
    return kv, nil
}
```
@czs007

**Comment by czs007** [comment]
> EtcdKV didn't check `clientv3.Client` nil.
> 
> ```go
> func EtcdKV(etcdEndPoints []string, root string) (*EtcdKV, error) {
>     client, err := clientv3.New(clientv3.Config{
>         Endpoints:   etcdEndpoints,
>         DialTimeout: 5 * time.Second,
>     })
>     if err != nil {
>         return nil, err
>     }
> 
>     kv := &EtcdKV{
>         client: client,
>         rootPath: root, 
>     }
>     return kv, nil
> }
> ```
> 
> @czs007

UR right, we should check client and return err if `client` is nil.

**Comment by XuanYang-cn** [comment]
Working on it

**Comment by XuanYang-cn** [comment]
Still working on it now
