### ISSUE TITLE
Milvus was restarted after calculating distance for entities from collections

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#6975]
#### Steps/Code to reproduce:
```python
from pymilvus_orm import CollectionSchema, FieldSchema
from pymilvus_orm import Collection
from pymilvus_orm import connections
from pymilvus_orm.types import DataType
dim = 2
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
schema = CollectionSchema(fields=[int64_field, float_field, float_vector])
connections.connect()
 import numpy as np
collection = Collection("test_search_collection_binbin_1", schema=schema)
collection.create_partition(partition_name="search_partition_1", description="search partition")
par = collection.partitions
nb = 1000
import random
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors],  par[0].name)
collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors],  par[1].name)
ids = list(res.primary_keys)
vectors_l = [[1, 2]]
op_l = {"float_vectors": vectors_l}
op_r = {"ids": ids, "collection": collection.name, "field": "float_vector"}
metric = "L2"
sqrt = False
params = {"metric": metric, "sqrt": sqrt}
from pymilvus_orm import utility
result = utility.calc_distance(vectors_left=op_l, vectors_right=op_r, params=params)
```

#### Expected result:
return distance array

Logs:
[log.tar.zip](https://github.com/milvus-io/milvus/files/6923271/log.tar.zip)

#### Actual results:
```
Addr [172.21.255.155:19530] calc_distance
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1627984763.227470800","description":"Error received from peer ipv4:172.21.255.155:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}"
>
	{'API start': '2021-08-03 09:59:23.189410', 'RPC start': '2021-08-03 09:59:23.192036', 'RPC error': '2021-08-03 09:59:23.228199'}
Retry to connect server 172.21.255.155:19530 failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 52, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 1098, in calc_distance
    return handler.calc_distance(vectors_left, vectors_right, params, timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 77, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 59, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 1160, in calc_distance
    response = future.result()
  File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 624, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1627984763.227470800","description":"Error received from peer ipv4:172.21.255.155:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}"
```

#### Environment:
- Milvus version(): aba234f
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
Name: pymilvus
Version: 2.0.0rc3.dev16
Name: pymilvus-orm
Version: 2.0.0rc3.dev15

- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by yhmo** [comment]
It seems need call load_collection() after insert(), otherwise the server could not fetch vectors from database and crash when printing error log. This is a bug, the server should not crash even failed to fetch vectors.

**Comment by binbinlv** [comment]
OK, please trouble fix this issue. Thanks.

And trying adding the load operation, and it is still the same with issue #6872 @yhmo 

```python
from pymilvus_orm import CollectionSchema, FieldSchema
from pymilvus_orm import Collection
from pymilvus_orm import connections
from pymilvus_orm.types import DataType
dim = 2
dim = 2
int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=dim)
schema = CollectionSchema(fields=[int64_field, float_field, float_vector])
connections.connect(host="172.21.255.155", port=19530)
import numpy as np
collection = Collection("test_search_collection_binbin_1", schema=schema)
collection.create_partition(partition_name="search_partition_1", description="search partition")
par = collection.partitions
nb = 1000
import random
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors],  par[0].name)
collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors],  par[1].name)
collection.load()
ids = list(res.primary_keys)
vectors_l = [[1, 2]]
op_l = {"float_vectors": vectors_l}
op_r = {"ids": ids, "collection": collection.name, "field": "float_vector"}
metric = "L2"
sqrt = False
params = {"metric": metric, "sqrt": sqrt}
from pymilvus_orm import utility
result = utility.calc_distance(vectors_left=op_l, vectors_right=op_r, params=params)
```
Results:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pymilvus_orm/utility.py", line 336, in calc_distance
    raise ResultError("Returned distance array is illegal")
pymilvus_orm.exceptions.ResultError: Returned distance array is illegal
```

**Comment by yhmo** [comment]
The pr #6976 will fix the crash.

**Comment by binbinlv** [comment]
Verified and the crash has been fixed.

milvus: bdb8396
Name: pymilvus
Version: 2.0.0rc3.dev16
Name: pymilvus-orm
Version: 2.0.0rc3.dev15
