### ISSUE TITLE
Error msg: `len(collection_names) (1) != len(inMemory_percentages)` returned by loading

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#6989]
#### Steps/Code to reproduce:
```
W
[2021-08-03 18:03:35,936] [    INFO] - Table: sift_128_euclidean, row count: 1000000 (milvus_benchmark.runners.accuracy:240)
[2021-08-03 18:03:35,938] [    INFO] - None (milvus_benchmark.client:276)
[2021-08-03 18:03:35,938] [    INFO] - Drop index: sift_128_euclidean (milvus_benchmark.client:287)
[2021-08-03 18:03:35,940] [    INFO] - Re-create index: sift_128_euclidean (milvus_benchmark.runners.accuracy:245)
[2021-08-03 18:03:35,941] [    INFO] - Building index start, collection_name: sift_128_euclidean, index_type: IVF_FLAT, metric_type:
 L2 (milvus_benchmark.client:261)
[2021-08-03 18:03:35,941] [    INFO] - {'nlist': 1024} (milvus_benchmark.client:263)
[2021-08-03 18:04:23,389] [   DEBUG] - Milvus create_index run in 47.45s (milvus_benchmark.client:49)
[2021-08-03 18:04:23,391] [    INFO] - None (milvus_benchmark.client:276)
[2021-08-03 18:04:23,392] [    INFO] - {'index_type': 'flat', 'metric_type': None, 'index_param': None} (milvus_benchmark.runners.ac
curacy:247)
[2021-08-03 18:04:23,392] [    INFO] - Start load collection: sift_128_euclidean (milvus_benchmark.runners.accuracy:248)
[2021-08-03 18:04:23,441] [   ERROR] - Error: <BaseException: (code=1, message=len(collection_names) (1) != len(inMemory_percentages
) (0))> (pymilvus.client.grpc_handler:61)
[2021-08-03 18:04:23,442] [   ERROR] - Error: <BaseException: (code=1, message=len(collection_names) (1) != len(inMemory_percentages
) (0))> (pymilvus.client.grpc_handler:61)
[2021-08-03 18:04:23,442] [   ERROR] - <BaseException: (code=1, message=len(collection_names) (1) != len(inMemory_percentages) (0))>
 (milvus_benchmark.main:114)
[2021-08-03 18:04:23,444] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 83, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/accuracy.py", line 250, in prepare
    self.milvus.load_collection(timeout=600)
  File "/src/milvus_benchmark/client.py", line 46, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 440, in load_collection
    return self._milvus.load_collection(collection_name, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 66, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 52, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 337, in load_collection
    return handler.load_collection("", collection_name=collection_name, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 59, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 806, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 59, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 824, in wait_for_loading_collection
    return self._wait_for_loading_collection_v2(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 858, in _wait_for_loading_collection_v2
    f"len(collection_names) ({ol}) != len(inMemory_percentages) ({pl})")
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=len(collection_names) (1) != len(inMemory_percentages) (0
))>
```

https://kibana-dev.zilliz.cc/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-03T18:03:29.149Z',to:'2021-08-03T18:05:52.469Z'))&_a=(columns:!(log),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:ad1e1c50-c9d9-11eb-9e1a-b3dcad9693fd,key:kubernetes.pod_name,negate:!f,params:!(benchmark-cron-1628013600-1-milvus-standalone-5689bf8c75-x8frl),type:phrases,value:benchmark-cron-1628013600-1-milvus-standalone-5689bf8c75-x8frl),query:(bool:(minimum_should_match:1,should:!((match_phrase:(kubernetes.pod_name:benchmark-cron-1628013600-1-milvus-standalone-5689bf8c75-x8frl)))))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:ad1e1c50-c9d9-11eb-9e1a-b3dcad9693fd,key:log,negate:!f,params:!(fail,error),type:phrases,value:'fail,%20error'),query:(bool:(minimum_should_match:1,should:!((match_phrase:(log:fail)),(match_phrase:(log:error))))))),hideChart:!f,index:ad1e1c50-c9d9-11eb-9e1a-b3dcad9693fd,interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',desc)))

```
<div style="box-sizing: border-box; margin: 0px; padding: 0px; border: none; vertical-align: initial; color: rgb(52, 55, 65); font-family: &quot;Inter UI&quot;, -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: -0.08px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><doc-table columns="renderProps.columns" data-description="" data-shared-item="" data-test-subj="discoverDocTable" data-title="" filter="renderProps.onFilter" hits="renderProps.rows" index-pattern="renderProps.indexPattern" infinite-scroll="true" minimum-visible-rows="renderProps.minimumVisibleRows" on-add-column="renderProps.onAddColumn" on-change-sort-order="renderProps.onSort" on-move-column="renderProps.onMoveColumn" on-remove-column="renderProps.onRemoveColumn" render-complete="" use-new-fields-api="renderProps.useNewFieldsApi" sorting="renderProps.sort" class="ng-scope ng-isolate-scope" data-render-complete="true" style="box-sizing: border-box; overflow: auto; flex: 1 1 100%; flex-direction: column;"><div ng-if="hits.length" ng-class="{ loading: isLoading }" class="ng-scope" style="box-sizing: border-box; margin: 0px; padding: 0px; border: none; vertical-align: initial;">

Aug 4, 2021 @ 02:04:25.416 | [2021/08/03 18:04:25.416 +00:00] [WARN] [segment_loader.go:104] ["AppendIndex failed, C runtime error detected, error code = 1, error msg = map::at"]
-- | --

  | Aug 4, 2021 @ 02:04:23.626 | [2021/08/03 18:04:23.626 +00:00] [INFO] [logger.go:48] ["transport: loopyWriter.run returning. connection error: desc = \"transport is closing\""]

  | Aug 4, 2021 @ 02:04:23.391 | [2021/08/03 18:04:23.391 +00:00] [DEBUG] [impl.go:955] ["DescribeIndex Done"] [error="index not exist"] [role=Proxy-] [msgID=426774052421076734] [timestamp=426774066196643843] [db=] [collection=sift_128_euclidean] [field=] ["index name"=float_vector]

  | Aug 4, 2021 @ 02:03:35.938 | [2021/08/03 18:03:35.938 +00:00] [DEBUG] [impl.go:955] ["DescribeIndex Done"] [error="index not exist"] [role=Proxy-] [msgID=426774052421076645] [timestamp=426774053757911042] [db=] [collection=sift_128_euclidean] [field=] ["index name"=float_vector]


<kbn-infinite-scroll ng-if="infiniteScroll" more="addRows" class="ng-scope ng-isolate-scope" style="box-sizing: border-box;"></kbn-infinite-scroll></div></doc-table></div><span tabindex="-1" id="discoverBottomMarker" style="box-sizing: border-box; margin: 0px; padding: 0px; border: none; vertical-align: initial; color: rgb(52, 55, 65); font-family: &quot;Inter UI&quot;, -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: -0.08px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br class="Apple-interchange-newline">
```
#### Actual results:
https://argo-test.zilliz.cc/workflows/qa/benchmark-cron-1628013600?tab=workflow&nodeId=benchmark-cron-1628013600-765712479&sidePanel=logs:benchmark-cron-1628013600-765712479:main

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): latest-master
- Deployment mode(standalone or cluster): standalone/cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-dev16
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by xige-16** [comment]
The client version is higher than the server version, please upgrade the milvus server version. @del-zhenwu

**Comment by del-zhenwu** [comment]
close.
