### ISSUE TITLE
Server unavailable during loading collection

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#7022]
#### Steps/Code to reproduce:
test yaml:
```
client-configmap:client-get-local50m-512
server-configmap:server-single-16c64m
```
client logs:
```
[2021-08-09 22:48:56,001] [   DEBUG] - Milvus flush run in 56.35s (milvus_benchmark.client:49)
[2021-08-09 22:48:56,004] [   DEBUG] - Row count: 50000000 in collection: <local_50m_512_l2> (milvus_benchmark.client:389)
[2021-08-09 22:48:56,005] [   DEBUG] - {'collection count': 50000000} (milvus_benchmark.runners.get:117)
[2021-08-09 22:48:56,005] [   DEBUG] - {'flush_time': 56.35} (milvus_benchmark.runners.get:118)
[2021-08-09 22:48:56,006] [   DEBUG] - Start load collection (milvus_benchmark.runners.get:119)
[2021-08-09 23:18:45,591] [   ERROR] -
Addr [benchmark-cluster-cron-1628539200-1-milvus.qa-milvus.svc.cluster.local:19530] wait_for_loading_collection
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Connection reset by peer"
        debug_error_string = "{"created":"@1628551125.579231721","description":"Error received from peer ipv4:10.96.254.146:19530","
file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Connection reset by peer","grpc_status":14}"
>
        {'API start': '2021-08-09 22:48:56.477438', 'RPC start': '2021-08-09 22:48:56.477459', 'RPC error': '2021-08-09 23:18:45.582
899'} (pymilvus.client.grpc_handler:76)
[2021-08-09 23:18:45,592] [   ERROR] -
Addr [benchmark-cluster-cron-1628539200-1-milvus.qa-milvus.svc.cluster.local:19530] load_collection
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Connection reset by peer"
        debug_error_string = "{"created":"@1628551125.579231721","description":"Error received from peer ipv4:10.96.254.146:19530","
file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Connection reset by peer","grpc_status":14}"
>
        {'API start': '2021-08-09 22:48:56.006611', 'RPC start': '2021-08-09 22:48:56.006621', 'RPC error': '2021-08-09 23:18:45.592
692'} (pymilvus.client.grpc_handler:76)
[2021-08-09 23:19:56,236] [   ERROR] - Error: <BaseException: (code=1, message=call query coordinator LoadCollection: rpc error: cod
e = DeadlineExceeded desc = context deadline exceeded)> (pymilvus.client.grpc_handler:61)
[2021-08-09 23:19:56,238] [   ERROR] - <BaseException: (code=1, message=call query coordinator LoadCollection: rpc error: code = Dea
dlineExceeded desc = context deadline exceeded)> (milvus_benchmark.main:114)
[2021-08-09 23:19:56,242] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 83, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/get.py", line 120, in prepare
    self.milvus.load_collection(timeout=1200)
  File "/src/milvus_benchmark/client.py", line 46, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 440, in load_collection
    return self._milvus.load_collection(collection_name, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 66, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 52, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 337, in load_collection
    return handler.load_collection("", collection_name=collection_name, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 59, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 803, in load_collection
    raise BaseException(response.error_code, response.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=call query coordinator LoadCollection: rpc error: code =
DeadlineExceeded desc = context deadline exceeded)>
 (milvus_benchmark.main:115)
```
#### Actual results:
https://kibana-dev.zilliz.cc/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-09T18:30:00.000Z',to:'2021-08-10T01:30:00.000Z'))&_a=(columns:!(log),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:ad1e1c50-c9d9-11eb-9e1a-b3dcad9693fd,key:kubernetes.pod_name,negate:!f,params:(query:benchmark-cluster-cron-1628539200-1-milvus-standalone-84d8pdk9t),type:phrase),query:(match_phrase:(kubernetes.pod_name:benchmark-cluster-cron-1628539200-1-milvus-standalone-84d8pdk9t)))),index:ad1e1c50-c9d9-11eb-9e1a-b3dcad9693fd,interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',asc)))

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): GitCommit: 9eb3599
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-dev16
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by yanliang567** [comment]
could be related to #7032 and issue #6849

**Comment by yanliang567** [comment]
@bigsheeper mentioned that this issue was caused by node failed, which is different from #6849.

**Comment by xiaofan-luan** [comment]
@bigsheeper any updates?

**Comment by bigsheeper** [comment]
> still re-pro
> https://argo-test.zilliz.cc/workflows/qa/benchmark-cluster-cron-np29b?tab=workflow&nodeId=benchmark-cluster-cron-np29b-4102996709&sidePanel=logs:benchmark-cluster-cron-np29b-4102996709:main

Argo link is unavailable @del-zhenwu

**Comment by wangting0128** [comment]
【recurrent】
argo task： benchmark-cxnkt

server deployment：
```
NAME: benchmark-cxnkt-1
LAST DEPLOYED: Wed Sep  1 02:33:00 2021
NAMESPACE: qa-milvus
STATUS: deployed
REVISION: 1
TEST SUITE: None
I0901 02:35:48.774970      25 request.go:665] Waited for 1.124467996s due to client-side throttling, not priority and fairness, requ
est: GET:https://kubernetes.default.svc.cluster.local/apis/batch/v1beta1?timeout=32s
I0901 02:35:58.774970      25 request.go:665] Waited for 11.124308179s due to client-side throttling, not priority and fairness, req
uest: GET:https://kubernetes.default.svc.cluster.local/apis/serving.knative.dev/v1beta1?timeout=32s
NAME                                                   READY   STATUS    RESTARTS   AGE
benchmark-cxnkt-1-etcd-0                               1/1     Running   0          2m59s
benchmark-cxnkt-1-milvus-standalone-549c67cbcf-wztzb   1/1     Running   0          2m59s
```

client log：
```
[2021-09-01 05:18:35,982] [   DEBUG] - Row count: 50000000 in collection: <local_50m_512_l2> (milvus_benchmark.client:389)
[2021-09-01 05:18:35,982] [   DEBUG] - {'collection count': 50000000} (milvus_benchmark.runners.get:117)
[2021-09-01 05:18:35,983] [   DEBUG] - {'flush_time': 2.62} (milvus_benchmark.runners.get:118)
[2021-09-01 05:18:35,984] [   DEBUG] - Start load collection (milvus_benchmark.runners.get:119)
[2021-09-01 05:26:25,101] [   ERROR] - 
Addr [benchmark-cxnkt-1-milvus.qa-milvus.svc.cluster.local:19530] wait_for_loading_collection
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Connection reset by peer"
	debug_error_string = "{"created":"@1630473985.099721751","description":"Error received from peer ipv4:10.96.143.159:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Connection reset by peer","grpc_status":14}"
>
	{'API start': '2021-09-01 05:18:36.050662', 'RPC start': '2021-09-01 05:18:36.050691', 'RPC error': '2021-09-01 05:26:25.101675'} (pymilvus.client.grpc_handler:76)
[2021-09-01 05:26:25,109] [   ERROR] - 
Addr [benchmark-cxnkt-1-milvus.qa-milvus.svc.cluster.local:19530] load_collection
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Connection reset by peer"
	debug_error_string = "{"created":"@1630473985.099721751","description":"Error received from peer ipv4:10.96.143.159:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Connection reset by peer","grpc_status":14}"
>
	{'API start': '2021-09-01 05:18:35.984475', 'RPC start': '2021-09-01 05:18:35.984497', 'RPC error': '2021-09-01 05:26:25.109002'} (pymilvus.client.grpc_handler:76)
[2021-09-01 05:34:16,106] [   ERROR] - 
Addr [benchmark-cxnkt-1-milvus.qa-milvus.svc.cluster.local:19530] load_collection
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1630474456.104293193","description":"Error received from peer ipv4:10.96.143.159:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Socket closed","grpc_status":14}"
>
	{'API start': '2021-09-01 05:26:50.607390', 'RPC start': '2021-09-01 05:26:50.607436', 'RPC error': '2021-09-01 05:34:16.106149'} (pymilvus.client.grpc_handler:76)
[2021-09-01 05:41:47,754] [   ERROR] - 
Addr [benchmark-cxnkt-1-milvus.qa-milvus.svc.cluster.local:19530] load_collection
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1630474907.752521882","description":"Error received from peer ipv4:10.96.143.159:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Socket closed","grpc_status":14}"
>
	{'API start': '2021-09-01 05:34:42.290850', 'RPC start': '2021-09-01 05:34:42.290876', 'RPC error': '2021-09-01 05:41:47.754034'} (pymilvus.client.grpc_handler:76)
[2021-09-01 05:42:18,792] [   ERROR] - 
Addr [benchmark-cxnkt-1-milvus.qa-milvus.svc.cluster.local:19530] fake_register_link
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1630474938.792078972","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":81,"grpc_status":4}"
>
	{'API start': '2021-09-01 05:41:48.791307', 'RPC start': '2021-09-01 05:41:48.791330', 'RPC error': '2021-09-01 05:42:18.792641'} (pymilvus.client.grpc_handler:76)
[2021-09-01 05:42:19,794] [   ERROR] - server is not healthy, please try again later (milvus_benchmark.main:114)
[2021-09-01 05:42:19,799] [   ERROR] - Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 52, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 341, in load_collection
    return handler.load_collection("", collection_name=collection_name, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 77, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 59, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 806, in load_collection
    response = rf.result()
  File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1630474907.752521882","description":"Error received from peer ipv4:10.96.143.159:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Socket closed","grpc_status":14}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 83, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/get.py", line 120, in prepare
    self.milvus.load_collection(timeout=1200)
  File "/src/milvus_benchmark/client.py", line 46, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 440, in load_collection
    return self._milvus.load_collection(collection_name, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 64, in handler
    self._update_connection_pool()
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 179, in _update_connection_pool
    self._wait_for_healthy()
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 150, in _wait_for_healthy
    raise Exception("server is not healthy, please try again later")
Exception: server is not healthy, please try again later
 (milvus_benchmark.main:115)
[2021-09-01 05:42:19,800] [   DEBUG] - {'_version': '0.1', '_type': 'metric', 'run_id': 1630463802, 'mode': 'local', 'server': <milvus_benchmark.metrics.models.server.Server object at 0x7f40dec478d0>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware object at 0x7f40dec47d68>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7f40dec47b70>, 'status': 'RUN_FAILED', 'err_message': '', 'collection': {'dimension': 512, 'metric_type': 'l2', 'dataset_name': 'local_50m_512_l2', 'collection_size': 50000000, 'other_fields': None, 'ni_per': 50000}, 'index': {'index_type': 'ivf_sq8', 'index_param': {'nlist': 1024}}, 'search': None, 'run_params': None, 'metrics': {'type': 'insert_get_performance', 'value': {}}, 'datetime': '2021-09-01 02:36:42.592288', 'type': 'metric'} (milvus_benchmark.metric.api:29)
```

Environment:
Milvus version(e.g. v2.0.0-RC2 or 8b23a93): GitCommit: 1c88c8b
Deployment mode(standalone or cluster): standalone
SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc5.dev29

**Comment by bigsheeper** [comment]
Queynode OOM when loading collection.
`50 * 1000000 * 512 * 4 / 1024.0 / 1024.0 / 1024.0 = 95.37（GB）`，95GB > 60GB (memory).
So queynode should prevent to load collection if collection beyonds the limit of memory, see #7434 
@wangting0128

**Comment by wangting0128** [comment]
Verify after repair

**Comment by bigsheeper** [comment]
#7434 have been merged
/assign @wangting0128

**Comment by bigsheeper** [comment]
#7434 have been merged

**Comment by wangting0128** [comment]
**recurrent**

argo task：benchmark-qnvlt

client log：
```
[2021-09-07 06:01:07,371] [   DEBUG] - 49900000 (milvus_benchmark.runners.base:89)
[2021-09-07 06:01:07,371] [    INFO] - {'total_time': 3470.69, 'rps': 14406.34, 'ni_time': 3.47} (milvus_benchmark.runners.base:151)
[2021-09-07 06:01:10,715] [   DEBUG] - Milvus flush run in 3.1s (milvus_benchmark.client:49)
[2021-09-07 06:01:10,717] [   DEBUG] - Row count: 50000000 in collection: <local_50m_512_l2> (milvus_benchmark.client:389)
[2021-09-07 06:01:10,717] [   DEBUG] - {'collection count': 50000000} (milvus_benchmark.runners.get:117)
[2021-09-07 06:01:10,717] [   DEBUG] - {'flush_time': 3.1} (milvus_benchmark.runners.get:118)
[2021-09-07 06:01:10,717] [   DEBUG] - Start load collection (milvus_benchmark.runners.get:119)
[2021-09-07 06:10:09,748] [   ERROR] - 
Addr [benchmark-qnvlt-1-milvus.qa-milvus.svc.cluster.local:19530] wait_for_loading_collection
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Connection reset by peer"
	debug_error_string = "{"created":"@1630995009.747452847","description":"Error received from peer ipv4:10.96.157.9:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Connection reset by peer","grpc_status":14}"
>
	{'API start': '2021-09-07 06:01:10.777388', 'RPC start': '2021-09-07 06:01:10.777396', 'RPC error': '2021-09-07 06:10:09.748498'} (pymilvus.client.grpc_handler:76)
[2021-09-07 06:10:09,748] [   ERROR] - 
Addr [benchmark-qnvlt-1-milvus.qa-milvus.svc.cluster.local:19530] load_collection
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Connection reset by peer"
	debug_error_string = "{"created":"@1630995009.747452847","description":"Error received from peer ipv4:10.96.157.9:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Connection reset by peer","grpc_status":14}"
>
	{'API start': '2021-09-07 06:01:10.717544', 'RPC start': '2021-09-07 06:01:10.717552', 'RPC error': '2021-09-07 06:10:09.748910'} (pymilvus.client.grpc_handler:76)
[2021-09-07 06:10:40,752] [   ERROR] - 
Addr [benchmark-qnvlt-1-milvus.qa-milvus.svc.cluster.local:19530] fake_register_link
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1630995040.751527849","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":81,"grpc_status":4}"
>
	{'API start': '2021-09-07 06:10:10.750759', 'RPC start': '2021-09-07 06:10:10.750776', 'RPC error': '2021-09-07 06:10:40.751953'} (pymilvus.client.grpc_handler:76)
[2021-09-07 06:10:41,753] [   ERROR] - server is not healthy, please try again later (milvus_benchmark.main:114)
[2021-09-07 06:10:41,757] [   ERROR] - Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 52, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 343, in load_collection
    return handler.load_collection("", collection_name=collection_name, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 77, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 59, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 827, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 77, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 59, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 845, in wait_for_loading_collection
    return self._wait_for_loading_collection_v2(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 869, in _wait_for_loading_collection_v2
    response = future.result()
  File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Connection reset by peer"
	debug_error_string = "{"created":"@1630995009.747452847","description":"Error received from peer ipv4:10.96.157.9:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Connection reset by peer","grpc_status":14}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 83, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/get.py", line 120, in prepare
    self.milvus.load_collection(timeout=1200)
  File "/src/milvus_benchmark/client.py", line 46, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 440, in load_collection
    return self._milvus.load_collection(collection_name, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 66, in handler
    self._update_connection_pool()
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 181, in _update_connection_pool
    self._wait_for_healthy()
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 152, in _wait_for_healthy
    raise Exception("server is not healthy, please try again later")
Exception: server is not healthy, please try again later
 (milvus_benchmark.main:115)
[2021-09-07 06:10:41,758] [   DEBUG] - {'_version': '0.1', '_type': 'metric', 'run_id': 1630987102, 'mode': 'local', 'server': <milvus_benchmark.metrics.models.server.Server object at 0x7f293582e780>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware object at 0x7f293582eac8>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7f293582e828>, 'status': 'RUN_FAILED', 'err_message': '', 'collection': {'dimension': 512, 'metric_type': 'l2', 'dataset_name': 'local_50m_512_l2', 'collection_size': 50000000, 'other_fields': None, 'ni_per': 50000}, 'index': {'index_type': 'ivf_sq8', 'index_param': {'nlist': 1024}}, 'search': None, 'run_params': None, 'metrics': {'type': 'insert_get_performance', 'value': {}}, 'datetime': '2021-09-07 03:58:22.899027', 'type': 'metric'} (milvus_benchmark.metric.api:29)
```

**Comment by bigsheeper** [comment]
same reason as #6726

**Comment by bigsheeper** [comment]
/assign @wangting0128 
/unassign
#8765 have been merged, it gets a cacheSize param from ENV or config, which would prevent loading collection if collection beyonds the memory limit. If the loading operation timeout instead of server unavailable, it means #8765 worked.

**Comment by yanliang567** [comment]
rc7 loaded 100M entities successfully. close
