### ISSUE TITLE
Client get no response for more than 6 hours during loading collection on dataset sift1m

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#7077]
#### Steps/Code to reproduce:
client logs:
```
W
[2021-08-12 18:11:11,157] [    INFO] - Re-create index: sift_128_euclidean (milvus_benchmark.runners.accuracy:245)
[2021-08-12 18:11:11,158] [    INFO] - Building index start, collection_name: sift_128_euclidean, index_type: IVF_FLAT, metric_type:
 L2 (milvus_benchmark.client:261)
[2021-08-12 18:11:11,158] [    INFO] - {'nlist': 1024} (milvus_benchmark.client:263)
[2021-08-12 18:11:57,959] [   DEBUG] - Milvus create_index run in 46.8s (milvus_benchmark.client:49)
[2021-08-12 18:11:57,963] [    INFO] - None (milvus_benchmark.client:276)
[2021-08-12 18:11:57,964] [    INFO] - {'index_type': 'flat', 'metric_type': None, 'index_param': None} (milvus_benchmark.runners.ac
curacy:247)
[2021-08-12 18:11:57,967] [    INFO] - Start load collection: sift_128_euclidean (milvus_benchmark.runners.accuracy:248)
[2021-08-13 00:10:04,675] [   ERROR] - Error: <BaseException: (code=1, message=syncTimestamp Failed:Connect to rootcoord failed with
 error:
context canceled)> (pymilvus.client.grpc_handler:61)
[2021-08-13 00:10:04,703] [   ERROR] - Error: <BaseException: (code=1, message=syncTimestamp Failed:Connect to rootcoord failed with
 error:
context canceled)> (pymilvus.client.grpc_handler:61)
[2021-08-13 00:10:04,705] [   ERROR] - <BaseException: (code=1, message=syncTimestamp Failed:Connect to rootcoord failed with error:
context canceled)> (milvus_benchmark.main:114)
[2021-08-13 00:10:04,720] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 83, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/accuracy.py", line 250, in prepare
    self.milvus.load_collection(timeout=600)
  File "/src/milvus_benchmark/client.py", line 46, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 440, in load_collection
    return self._milvus.load_collection(collection_name, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 66, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 52, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 337, in load_collection
    return handler.load_collection("", collection_name=collection_name, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 59, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 806, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 59, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 824, in wait_for_loading_collection
    return self._wait_for_loading_collection_v2(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 851, in _wait_for_loading_collection_v2
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=syncTimestamp Failed:Connect to rootcoord failed with err
or:
context canceled)>
 (milvus_benchmark.main:115)
```
test yaml:
```
client-configmap: client-acc-sift-ivf-flat
server-configmap: server-single-8c16m

```
pod info:
```
NAME                                                             READY   STATUS    RESTARTS   AGE
benchmark-cron-1628791200-1-etcd-0                               1/1     Running   0          9m11s
benchmark-cron-1628791200-1-milvus-standalone-5d946bcbfd-z5nwj   1/1     Running   0          9m11s
```
#### Actual results:
client get no response after 6 hours.

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): 
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): rc4-dev1
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by xiaofan-luan** [comment]
rc4 is released, can we reproduce this on rc4?

**Comment by del-zhenwu** [comment]
> rc4 is released, can we reproduce this on rc4?

still can be re-produced with rc4

**Comment by del-zhenwu** [comment]
> > rc4 is released, can we reproduce this on rc4?
> 
> still can be re-produced with rc4

rc5 with. pymilvus-rc5-dev12

**Comment by xige-16** [comment]
["QueryNode Client grpc error"] [error="rpc error: code = Unknown desc = AppendIndex failed, C runtime error detected, error code = 1, error msg = map::at"]

**Comment by xige-16** [comment]
The reason for unsuccessful load is the same as #6797

**Comment by xige-16** [comment]
The reason is that the slide meta value in the index file is incorrectly filled in. I'll fix the problem right away.

**Comment by xige-16** [comment]
The bug has been fixed, trouble you check it. @del-zhenwu

**Comment by del-zhenwu** [comment]
fixed
