### ISSUE TITLE
Report "object of type 'NoneType' has no len()" for some invalid metric type when calculating distances for vectors

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#7086]
#### Steps/Code to reproduce:
```python
from pymilvus_orm import connections
from pymilvus_orm import utility
import random
connections.connect()
vectors_l = [[random.random() for _ in range(2)] for _ in range(5)]
vectors_r = [[random.random() for _ in range(2)] for _ in range(5)]
op_l = {"vectors": vectors_l}
op_r = {"vectors": vectors_r}
params = {"metric": 1}
results = utility.calc_distance(op_l, op_r, params)
params = {"metric": None}
results = utility.calc_distance(op_l, op_r, params)
```

#### Expected result:
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=Invalid metric type)>

#### Actual results:
for int, float, None
TypeError: object of type 'NoneType' has no len():
```
results = utility.calc_distance(op_l, op_r, params)
Addr [172.21.255.155:19530] calc_distance
Excepted error: object of type 'NoneType' has no len()
	{'API start': '2021-08-13 05:09:15.635049', 'RPC start': '2021-08-13 05:09:15.636485', 'Exception': '2021-08-13 05:09:15.636535'}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pymilvus_orm/utility.py", line 321, in calc_distance
    res = _get_connection(using).calc_distance(vectors_left, vectors_right, params, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 66, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 52, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 1098, in calc_distance
    return handler.calc_distance(vectors_left, vectors_right, params, timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 82, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 59, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 1158, in calc_distance
    req = Prepare.calc_distance_request(vectors_left, vectors_right, params)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/prepare.py", line 755, in calc_distance_request
    if "metric" not in params.keys() or len(params["metric"]) == 0:
TypeError: object of type 'NoneType' has no len()
```

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):  e1b3273
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
Name: pymilvus
Version: 2.0.0rc4.dev1
Name: pymilvus-orm
Version: 2.0.0rc4.dev2

- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by yhmo** [comment]
Fixed by https://github.com/milvus-io/pymilvus/pull/648
Use the latest pymilvus sdk to verify.

**Comment by binbinlv** [comment]
Verified, fixed.

pymilvus:
2.0.0rc5.dev19

Results:
 params value {'metric': None} is illegal
