### ISSUE TITLE
The number of milvus operation failure is always zero in chaos test

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#7135]
#### Steps/Code to reproduce:
1. When counting the `succ_rate` in chaos test, it is found that the `fail` num is always 0.
```
    def keep_running(self):
        while self._running is True:
            search_vec = cf.gen_vectors(5, ct.default_dim)
            _, result = self.c_wrap.search(
                                data=search_vec,
                                anns_field=ct.default_float_vec_field_name,
                                param={"nprobe": 32},
                                limit=1, timeout=timeout
                            )
            if result:
                self._succ += 1
            else:
                self._fail += 1
            sleep(constants.WAIT_PER_OP / 10)
```
2. Because we count the `fail` according to the `result` actually returned by `ResponseChecker`. However, when we expect that the successful request fails, it returns an exception before calling `ResponseChecker` and getting the `result`. You can simply understand it based on the following example. In a sense, the `check_result` returned by `ResponseChecker` has no meaning.
```
    def test_collection(self):
        self._connect()
        c_name = cf.gen_unique_str(prefix)
        res, check = self.collection_wrap.init_collection(c_name)
        log.debug(f'res: {res}')
        log.debug(f'check: {check}')
```
```
[2021-08-17 16:44:41 - DEBUG - ci_test]: (api_request)  : [Collection] args: ['collection_y5KefpWL', None], kwargs: {} (api_request.py:44)
[2021-08-17 16:44:41 - ERROR - ci_test]: Traceback (most recent call last):
  File "/home/zong/zong/projects/milvus/tests20/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/utils/api_request.py", line 45, in api_request
    return func(*arg, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus_orm/collection.py", line 131, in __init__
    raise SchemaNotReadyException(0, ExceptionsMessage.NoSchema)
pymilvus_orm.exceptions.SchemaNotReadyException: <SchemaNotReadyException: (code=0, message=Should be passed into the schema.)>
 (api_request.py:26)
[2021-08-17 16:44:41 - ERROR - ci_test]: (api_response) : <SchemaNotReadyException: (code=0, message=Should be passed into the schema.)> (api_request.py:27)

        self._connect()
        c_name = cf.gen_unique_str(prefix)
>       res, check = self.collection_wrap.init_collection(c_name)

testcases/test_collection.py:57: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
base/collection_wrapper.py:23: in init_collection
    check_result = ResponseChecker(res, func_name, check_task, check_items, is_succ,
check/func_check.py:31: in run
    result = self.assert_succ(self.succ, True)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

actual = False, expect = True

    @staticmethod
    def assert_succ(actual, expect):
>       assert actual is expect
E       AssertionError

check/func_check.py:67: AssertionError
```

3. How to fix: The statistical condition for `succ` and `fail` is whether to return an exception rather than `result`

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by yanliang567** [comment]
Trying to add a check_nothing task in test framework, which would directly return the result of api request without verifying anything.
