### ISSUE TITLE
[standalone] Server crash when loading collection

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#7179]
#### Steps/Code to reproduce:

test yaml:

```
  client-configmap: client-search-filter-sift50m-ivf-flat-2048
  server-configmap: server-single-16c64m
```

[client logs:
](https://argo-test.zilliz.cc/artifacts/qa/benchmark-cluster-cron-nhg6t/benchmark-cluster-cron-nhg6t-1300456843/main-logs)
```
  grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
          status = StatusCode.UNAVAILABLE
          details = "Socket closed"
          debug_error_string = "{"created":"@1629366108.797704452","description":"Error received from peer ipv4:10.96.23.36:19530","file":"src/core/lib/surface/call.cc","file_line":10
  68,"grpc_message":"Socket closed","grpc_status":14}"
  >
  During handling of the above exception, another exception occurred:
  Traceback (most recent call last):
    File "main.py", line 83, in run_suite
      runner.prepare(**cases[0])
    File "/src/milvus_benchmark/runners/search.py", line 265, in prepare
      self.milvus.load_collection(timeout=1200)
    File "/src/milvus_benchmark/client.py", line 46, in wrapper
      result = func(*args, **kwargs)
    File "/src/milvus_benchmark/client.py", line 440, in load_collection
      return self._milvus.load_collection(collection_name, timeout=timeout)
    File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 64, in handler
      self._update_connection_pool()
    File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 179, in _update_connection_pool
      self._wait_for_healthy()
    File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
      return func(self, *args, **kwargs)
    File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 150, in _wait_for_healthy
      raise Exception("server is not healthy, please try again later")
  Exception: server is not healthy, please try again later
   (milvus_benchmark.main:115)
  [2021-08-19 09:42:20,813] [   DEBUG] - {'_version': '0.1', '_type': 'metric', 'run_id': 1629361603, 'mode': 'local', 'server': <milvus_benchmark.metrics.models.server.Server object
  at 0x7f5e45f432e8>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware object at 0x7f5e45f43080>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7f5e45f4316
  0>, 'status': 'RUN_FAILED', 'err_message': '', 'collection': {'dimension': 128, 'metric_type': 'l2', 'dataset_name': 'sift_50m_128_l2', 'fields': None}, 'index': {'index_type': 'ivf
  _flat', 'index_param': {'nlist': 2048}}, 'search': None, 'run_params': None, 'metrics': {'type': 'insert_search_performance', 'value': {}}, 'datetime': '2021-08-19 08:26:43.554921',
   'type': 'metric'} (milvus_benchmark.metric.api:29)
```

#### Actual results:
https://kibana-dev.zilliz.cc/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-19T09:37:54.000Z',to:'2021-08-19T09:37:55.000Z'))&_a=(columns:!(log),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:ad1e1c50-c9d9-11eb-9e1a-b3dcad9693fd,key:kubernetes.pod_name,negate:!f,params:(query:benchmark-cluster-cron-nhg6t-5-milvus-standalone-5955bcb656j67r),type:phrase),query:(match_phrase:(kubernetes.pod_name:benchmark-cluster-cron-nhg6t-5-milvus-standalone-5955bcb656j67r)))),index:ad1e1c50-c9d9-11eb-9e1a-b3dcad9693fd,interval:auto,query:(language:kuery,query:benchmark-cluster-cron-nhg6t-5-milvus-standalone-5955bcb656j67r),sort:!(!('@timestamp',asc)))

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): GitCommit: 
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc5.dev12
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by xige-16** [comment]
[timeticksync.go:198] ["sendToChannel fail"] [err="proxyTimeTick has not been fulfilled"]
A lot of this information is printed in the log.

**Comment by del-zhenwu** [comment]
Loading process takes 9 mins and then server crashed.
```
[2021-08-19 10:59:27,507] [   DEBUG] - Milvus insert run in 4.45s (milvus_benchmark.client:49)
[2021-08-19 10:59:27,521] [   DEBUG] - Row count: 49900000 in collection: <local_50m_512_l2> (milvus_benchmark.client:389)
[2021-08-19 10:59:27,522] [   DEBUG] - 49900000 (milvus_benchmark.runners.base:89)
[2021-08-19 10:59:27,523] [    INFO] - {'total_time': 4492.97, 'rps': 11128.49, 'ni_time': 4.49} (milvus_benchmark.runners.base:151)
[2021-08-19 10:59:30,987] [   DEBUG] - Milvus flush run in 3.1s (milvus_benchmark.client:49)
[2021-08-19 10:59:30,989] [   DEBUG] - Row count: 50000000 in collection: <local_50m_512_l2> (milvus_benchmark.client:389)
[2021-08-19 10:59:30,990] [   DEBUG] - {'collection count': 50000000} (milvus_benchmark.runners.get:117)
[2021-08-19 10:59:30,990] [   DEBUG] - {'flush_time': 3.1} (milvus_benchmark.runners.get:118)
[2021-08-19 10:59:30,991] [   DEBUG] - Start load collection (milvus_benchmark.runners.get:119)
[2021-08-19 11:08:28,138] [   ERROR] -
Addr [benchmark-cluster-cron-nhg6t-1-milvus.qa-milvus.svc.cluster.local:19530] wait_for_loading_collection
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Connection reset by peer"
        debug_error_string = "{"created":"@1629371308.135926192","description":"Error received from peer ipv4:10.96.90.246:19530","f
ile":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Connection reset by peer","grpc_status":14}"
>
        {'API start': '2021-08-19 10:59:31.042928', 'RPC start': '2021-08-19 10:59:31.042937', 'RPC error': '2021-08-19 11:08:28.137
635'} (pymilvus.client.grpc_handler:76)
```

**Comment by congqixia** [comment]
After inspecting the log:
https://kibana-dev.zilliz.cc/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-19T09:40:57.813Z',to:'2021-08-19T09:41:06.721Z'))&_a=(columns:!(log),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:ad1e1c50-c9d9-11eb-9e1a-b3dcad9693fd,key:kubernetes.pod_name,negate:!f,params:(query:benchmark-cluster-cron-nhg6t-5-milvus-standalone-5955bcb656j67r),type:phrase),query:(match_phrase:(kubernetes.pod_name:benchmark-cluster-cron-nhg6t-5-milvus-standalone-5955bcb656j67r)))),index:ad1e1c50-c9d9-11eb-9e1a-b3dcad9693fd,interval:auto,query:(language:kuery,query:benchmark-cluster-cron-nhg6t-5-milvus-standalone-5955bcb656j67r),sort:!(!('@timestamp',asc)))

Here is the highlight snippet:
```
[2021/08/19 09:41:02.074 +00:00] [DEBUG] [session_util.go:233] ["session keepalive channel closed"]
```

Looks like server disconnected from etcd and quited.

**Comment by cymarechal** [comment]
I had the same error message running cluster mode on k8s with Istio. Looks like Envoy proxy is blocking gRPC calls before etcd could even receive the request:
```
2021-09-06T14:04:38.902978Z	debug	envoy http2	[C1084]
invalid http2: Invalid HTTP header field was received: frame type: 1, stream: 1, name: [:authority], value: [#initially=[milvus-etcd:2379]]
```
Please keep me posted if you find a solution.

**Comment by yanliang567** [comment]
rc7 standalone successfully loades 100m entities
