### ISSUE TITLE
An syncTimeStamp Failed exception occurs after the rootCoord is killed and restarted

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#7186]
#### Steps/Code to reproduce:
You can reproduce by chaos test
1. deploy milvus with cluster mode
2. update ALL_CHAOS_YAMLS = 'chaos_rootcoord_podkill.yaml' in /milvus/tests20/python_client/chaos/constants.py
2. cd tests20/python_client/chaos and pytest test_chaos.py --host 10.98.0.x -v -s
3. after rootCoord kill test, run test_e2e.py cd tests20/python_client and pytest testcases/test_e2e.py --host 10.98.0.x -v -s

You also can reproduce with the following steps:
1. start a thread responsible for uninterrupted operation of Milvus (create, insert, index, search, and query...)
2. kill rootCoord pod every 5s within 20s
3. 20s later, the rootCoord turns running and try to connect Milvus

#### Expected result:
After rootCoord turns into running, expect Milvus is health and available

#### Actual results:
```
[2021-08-20 11:25:52,156 - DEBUG - ci_test]: (api_request)  : [list_collections] args: [20, 'default'], kwargs: {} (api_request.py:44)
[2021-08-20 11:25:52,166 - ERROR - ci_test]: Traceback (most recent call last):
  File "/home/zong/zong/projects/milvus/tests20/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/home/zong/zong/projects/milvus/tests20/python_client/utils/api_request.py", line 45, in api_request
    return func(*arg, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus_orm/utility.py", line 267, in list_collections
    return _get_connection(using).list_collections()
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 66, in handler
    raise e
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 52, in handler
    return func(self, *args, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 411, in list_collections
    return handler.list_collections(timeout)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    raise e
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 59, in handler
    return func(self, *args, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 430, in list_collections
    raise BaseException(status.error_code, status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=syncTimeStamp Failed:state code = Initializing)>
 (api_request.py:26)
```

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):
  7233b62   Built:     Thu Aug 19 07:59:12 UTC 2021
- Deployment mode(standalone or cluster):
  cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
   pymilvus              2.0.0rc3.dev16
   pymilvus-orm          2.0.0rc4.dev2
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others: 

#### Additional context:
The logs:
[milvus_logs.tar.gz](https://github.com/milvus-io/milvus/files/7018984/milvus_logs.tar.gz)

The previous rootCoord pod:
`milvus-chaos-rootcoord-89d94b5fc-xrqsb`

The pods:
```
milvus-chaos-datacoord-756588d59c-q7dfq     1/1     Running   0          12m
milvus-chaos-datanode-7cf694bc94-5s9pn      1/1     Running   0          12m
milvus-chaos-etcd-0                         1/1     Running   0          12m
milvus-chaos-indexcoord-fd9c6f54d-h8f6t     1/1     Running   0          12m
milvus-chaos-indexnode-7cd6c6c7f5-vg64c     1/1     Running   0          12m
milvus-chaos-minio-6cd5bb4c6f-z5fl5         1/1     Running   0          12m
milvus-chaos-proxy-79d8b948f8-t59qg         1/1     Running   0          12m
milvus-chaos-pulsar-97cfccf4f-tmqp8         1/1     Running   0          12m
milvus-chaos-querycoord-66b76476f9-c8l7k    1/1     Running   0          12m
milvus-chaos-querynode-6b45f7bb5c-52lnz     1/1     Running   0          12m
milvus-chaos-rootcoord-89d94b5fc-txr2g      1/1     Running   0          8m2s
```

**Comment by scsven** [comment]
working on this

**Comment by ThreadDao** [comment]
This issue is fixed, and I will close it first.
```
Version:   86afde4
Built:     Mon Sep  6 03:56:05 UTC 2021
```
