### ISSUE TITLE
Milvus Pulsar node is CrashLoopBackOff

### ISSUE THREAD

**Issue by shiyu22** [milvus-io/milvus#7238]
#### Steps/Code to reproduce:
1. start Milvus cluster in k8s
2. run `kubectl get pods` after 3 days

#### Expected result:
each node is running.

#### Actual results:
Milvus Pulsar node is CrashLoopBackOff
<img width="691" alt="截屏2021-08-23 17 32 34" src="https://user-images.githubusercontent.com/53459423/130425048-6bc812bd-d71e-4297-a25a-a1d57cdd22f7.png">

#### Environment:
- Milvus version: v2.0.0-RC4
- Deployment mode: cluster
- OS: Ubuntu or CentOS

#### Configuration file:
https://github.com/milvus-io/milvus-helm/blob/master/charts/milvus/values.yaml

#### Additional context:
```bash
$ kubectl describe pod shiyu2-milvus-pulsar-6ff7c79764-jps9x
Name:         shiyu2-milvus-pulsar-6ff7c79764-jps9x
Namespace:    uso
Priority:     0
Node:         qa-node004.zilliz.local/10.100.32.7
Start Time:   Fri, 20 Aug 2021 16:32:16 +0800
Labels:       app.kubernetes.io/instance=shiyu2
              app.kubernetes.io/name=milvus
              component=pulsar
              pod-template-hash=6ff7c79764
Annotations:  <none>
Status:       Running
IP:           10.97.6.214
IPs:
  IP:           10.97.6.214
Controlled By:  ReplicaSet/shiyu2-milvus-pulsar-6ff7c79764
Containers:
  pulsar:
    Container ID:  docker://fd8f11b3ae1d753f218fc6ff57bee93219b6e3ed1af2c8fa5d48016bec811085
    Image:         apachepulsar/pulsar:2.6.1
    Image ID:      docker-pullable://apachepulsar/pulsar@sha256:4db6ff0b4045c40eaecf4c03df911563245f7adeee31895aeec12c31aed9e5a1
    Port:          6650/TCP
    Host Port:     0/TCP
    Command:
      /bin/sh
      -c
    Args:
      pulsar_conf_path=/pulsar/conf/standalone.conf; echo "" >> $pulsar_conf_path; echo "maxMessageSize=104857600" >> $pulsar_conf_path; echo "" >> $pulsar_conf_path; echo "nettyMaxFrameSizeBytes=104857600" >> $pulsar_conf_path; sed -i 's/^defaultRetentionTimeInMinutes=.*/defaultRetentionTimeInMinutes=10080/' /pulsar/conf/broker.conf; bin/pulsar standalone;
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 23 Aug 2021 17:25:32 +0800
      Finished:     Mon, 23 Aug 2021 17:28:36 +0800
    Ready:          False
    Restart Count:  53
    Environment:    <none>
    Mounts:
      /pulsar/data from milvus-pulsar-disk (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-9pqld (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  milvus-pulsar-disk:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  shiyu2-milvus-pulsar
    ReadOnly:   false
  default-token-9pqld:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-9pqld
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason   Age                       From     Message
  ----     ------   ----                      ----     -------
  Warning  BackOff  3m12s (x1088 over 5h28m)  kubelet  Back-off restarting failed container
```

logs: 
[pulsar-crashloopbackoff.log](https://github.com/milvus-io/milvus/files/7030810/pulsar-crashloopbackoff.log)

**Comment by shiyu22** [comment]
The pulsar node is running today, but I cannot connect Milvus and show the error:
```bash
2021-08-24 10:27:30,333 ｜ ERROR ｜ grpc_handler.py ｜ handler ｜ 61 ｜ Error: <BaseException: (code=1, message=syncTimeStamp Failed:state code = Initializing)>
Traceback (most recent call last):
  File "main.py", line 166, in <module>
    main()
  File "main.py", line 140, in main
    print(client.show_collection())
  File "/data/shiyu/git/bootcamp/benchmark_test/scripts/milvus_helpers.py", line 165, in show_collection
    return utility.list_collections()
  File "/home/zilliz_support/miniconda3/envs/shiyu/lib/python3.7/site-packages/pymilvus_orm/utility.py", line 267, in list_collections
    return _get_connection(using).list_collections()
  File "/home/zilliz_support/miniconda3/envs/shiyu/lib/python3.7/site-packages/pymilvus/client/stub.py", line 66, in handler
    raise e
  File "/home/zilliz_support/miniconda3/envs/shiyu/lib/python3.7/site-packages/pymilvus/client/stub.py", line 52, in handler
    return func(self, *args, **kwargs)
  File "/home/zilliz_support/miniconda3/envs/shiyu/lib/python3.7/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/home/zilliz_support/miniconda3/envs/shiyu/lib/python3.7/site-packages/pymilvus/client/stub.py", line 411, in list_collections
    return handler.list_collections(timeout)
  File "/home/zilliz_support/miniconda3/envs/shiyu/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    raise e
  File "/home/zilliz_support/miniconda3/envs/shiyu/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 59, in handler
    return func(self, *args, **kwargs)
  File "/home/zilliz_support/miniconda3/envs/shiyu/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 430, in list_collections
    raise BaseException(status.error_code, status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=syncTimeStamp Failed:state code = Initializing)>
```
and the status of the nodes:
<img width="631" alt="截屏2021-08-24 10 31 46" src="https://user-images.githubusercontent.com/53459423/130546536-82e81551-71c8-47d6-8751-b3bbb7ea60ec.png">

**Comment by xiaofan-luan** [comment]
can we have puslar logs and see why?
