### ISSUE TITLE
collection load error

### ISSUE THREAD

**Issue by dzhyy** [milvus-io/milvus#7242]
#### Steps/Code to reproduce:

class MilvusDB(IVectorDB):
    def __init__(self):
        self.collection = None
        connections.connect(
            host=settings.milvus_host,
            port=settings.milvus_port,
        )

    def set_collection(self, name: str):
        if utility.has_collection(name):
            self.collection = Collection(name=name)
            return self.collection
        else:
            raise RuntimeError(f"Unknown collection name: '{name}'")
......
    def load(self, name: str):
        self.set_collection(name=name)
        self.collection.load() # Error happen here #
        logger.debug("Successfully load '{}'".format(name))

#### Expected result:

just load collection to memory

#### Actual results:

Traceback (most recent call last):
  File "/home/dzh/.cache/pypoetry/virtualenvs/labeling-i6bWZ5ol-py3.8/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/dzh/.cache/pypoetry/virtualenvs/labeling-i6bWZ5ol-py3.8/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
  File "/home/dzh/.cache/pypoetry/virtualenvs/labeling-i6bWZ5ol-py3.8/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/dzh/.cache/pypoetry/virtualenvs/labeling-i6bWZ5ol-py3.8/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/dzh/.cache/pypoetry/virtualenvs/labeling-i6bWZ5ol-py3.8/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/dzh/.cache/pypoetry/virtualenvs/labeling-i6bWZ5ol-py3.8/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/dzh/.cache/pypoetry/virtualenvs/labeling-i6bWZ5ol-py3.8/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/dzh/.cache/pypoetry/virtualenvs/labeling-i6bWZ5ol-py3.8/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/dzh/.cache/pypoetry/virtualenvs/labeling-i6bWZ5ol-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/dzh/.cache/pypoetry/virtualenvs/labeling-i6bWZ5ol-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/dzh/.cache/pypoetry/virtualenvs/labeling-i6bWZ5ol-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/home/dzh/.cache/pypoetry/virtualenvs/labeling-i6bWZ5ol-py3.8/lib/python3.8/site-packages/fastapi/routing.py", line 216, in app
    raw_response = await run_endpoint_function(
  File "/home/dzh/.cache/pypoetry/virtualenvs/labeling-i6bWZ5ol-py3.8/lib/python3.8/site-packages/fastapi/routing.py", line 149, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/dzh/labeling/backend/app/api/copyright.py", line 43, in copyright_detection
    result = copyrightService.search(body.path, featureType)
  File "/home/dzh/labeling/backend/app/service/copyright.py", line 82, in search
    content_ids, distances = self.copyright_lib.search(settings.copyright_content_table, image_file_name, FeatureType.content, settings.copyright_top_k)
  File "/home/dzh/labeling/backend/app/model/copyright_lib.py", line 33, in search
    vector_db.load(category_name)
  File "/home/dzh/labeling/backend/app/db/milvus_db.py", line 90, in load
    self.collection.load()
  File "/home/dzh/.cache/pypoetry/virtualenvs/labeling-i6bWZ5ol-py3.8/lib/python3.8/site-packages/pymilvus_orm/collection.py", line 440, in load
    conn.load_collection(self._name, timeout=timeout, **kwargs)
  File "/home/dzh/.cache/pypoetry/virtualenvs/labeling-i6bWZ5ol-py3.8/lib/python3.8/site-packages/pymilvus/client/stub.py", line 66, in handler
    raise e
  File "/home/dzh/.cache/pypoetry/virtualenvs/labeling-i6bWZ5ol-py3.8/lib/python3.8/site-packages/pymilvus/client/stub.py", line 52, in handler
    return func(self, *args, **kwargs)
  File "/home/dzh/.cache/pypoetry/virtualenvs/labeling-i6bWZ5ol-py3.8/lib/python3.8/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/home/dzh/.cache/pypoetry/virtualenvs/labeling-i6bWZ5ol-py3.8/lib/python3.8/site-packages/pymilvus/client/stub.py", line 337, in load_collection
    return handler.load_collection("", collection_name=collection_name, timeout=timeout)
  File "/home/dzh/.cache/pypoetry/virtualenvs/labeling-i6bWZ5ol-py3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    raise e
  File "/home/dzh/.cache/pypoetry/virtualenvs/labeling-i6bWZ5ol-py3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 59, in handler
    return func(self, *args, **kwargs)
  File "/home/dzh/.cache/pypoetry/virtualenvs/labeling-i6bWZ5ol-py3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 806, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/home/dzh/.cache/pypoetry/virtualenvs/labeling-i6bWZ5ol-py3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    raise e
  File "/home/dzh/.cache/pypoetry/virtualenvs/labeling-i6bWZ5ol-py3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 59, in handler
    return func(self, *args, **kwargs)
  File "/home/dzh/.cache/pypoetry/virtualenvs/labeling-i6bWZ5ol-py3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 824, in wait_for_loading_collection
    return self._wait_for_loading_collection_v2(collection_name, timeout)
  File "/home/dzh/.cache/pypoetry/virtualenvs/labeling-i6bWZ5ol-py3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 857, in _wait_for_loading_collection_v2
    raise BaseException(ErrorCode.UnexpectedError,
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=len(collection_names) (1) != len(inMemory_percentages) (0))>

#### Environment:
- Milvus version  v2.0.0-RC4
- Deployment mode(standalone
- SDK version  pymilvus v2.0.0rc4
- OS(Ubuntu
- CPU/Memory: 8gb
- GPU:  i5 6500
- Others: 

#### Additional context:

Befor this, i have create and insert this collection,but when i load it, error raised.

!! This error only happen in version rc4! Before i update milvus from rc2 to rc4,it never happend

**Comment by yanliang567** [comment]
looks like a know issue.

/assign @xige-16 
@xige-16  please take a look.

**Comment by xige-16** [comment]
Is the version of Milvus image rc2 and the version of pymilvus rc4?

**Comment by yanliang567** [comment]
similar to issue #6989. 
@dzhyy could you please retry on latest Milvus and pymilvus?
/assign @dzhyy
