### ISSUE TITLE
Error: <BaseException: (code=1, message=syncTimestamp Failed:Connect to rootcoord failed

### ISSUE THREAD

**Issue by Bennu-Li** [milvus-io/milvus#7252]
#### Steps/Code to reproduce:
All pods are running in Milvus cluster, the pulsar always restart, and i can connect Milvus server.

```
NAME                                            READY   STATUS    RESTARTS   AGE
lym-rc4-etcd-0                                  1/1     Running   33         7d19h
lym-rc4-milvus-datacoord-7cd7c47c5d-49zmf       1/1     Running   0          7d19h
lym-rc4-milvus-datanode-5cb698b449-pghxb        1/1     Running   0          7d19h
lym-rc4-milvus-indexcoord-647c8bcff7-d4hxn      1/1     Running   0          7d19h
lym-rc4-milvus-indexnode-56c8fffc84-rmpk4       1/1     Running   0          7d19h
lym-rc4-milvus-proxy-64cb9d5c59-d8df7           1/1     Running   0          7d19h
lym-rc4-milvus-pulsar-7bd5cf6c98-f85j6          1/1     Running   190        7d19h
lym-rc4-milvus-querycoord-cf88dbc94-lz4lz       1/1     Running   0          7d19h
lym-rc4-milvus-querynode-7cb759fb54-h96pc       1/1     Running   0          7d19h
lym-rc4-milvus-rootcoord-54f7db7d46-d72dg       1/1     Running   13         7d19h
lym-rc4-minio-755fd9897f-64tgd                  1/1     Running   0          7d19h
```

but i can not do any other operation, such as creat collection, list_collections(), has_collections(). It through the same error:

```
creat collection:

Error: <BaseException: (code=1, message=syncTimestamp Failed:Connect to rootcoord failed with error:All attempts results:
attempt #1:number of RootCoord is incorrect, 0
attempt #2:number of RootCoord is incorrect, 0
attempt #3:number of RootCoord is incorrect, 0
attempt #4:number of RootCoord is incorrect, 0
attempt #5:number of RootCoord is incorrect, 0
attempt #6:number of RootCoord is incorrect, 0
attempt #7:number of RootCoord is incorrect, 0
attempt #8:number of RootCoord is incorrect, 0
attempt #9:number of RootCoord is incorrect, 0
attempt #10:number of RootCoord is incorrect, 0
)>
```

```
has_collection():

Failed to load data to Milvus: <BaseException: (code=1, message=syncTimestamp Failed:Connect to rootcoord failed with error:
All attempts results:
attempt #1:number of RootCoord is incorrect, 0
attempt #2:number of RootCoord is incorrect, 0
attempt #3:number of RootCoord is incorrect, 0
attempt #4:number of RootCoord is incorrect, 0
attempt #5:number of RootCoord is incorrect, 0
attempt #6:number of RootCoord is incorrect, 0
attempt #7:number of RootCoord is incorrect, 0
attempt #8:number of RootCoord is incorrect, 0
attempt #9:number of RootCoord is incorrect, 0
attempt #10:number of RootCoord is incorrect, 0
)>
```

#### Environment:
- Milvus version(ev2.0.0-RC4):
- Deployment mode(cluster):

**Comment by Bennu-Li** [comment]
[rootcoord.log](https://github.com/milvus-io/milvus/files/7036197/rootcoord.log)
[pulsar.log](https://github.com/milvus-io/milvus/files/7036198/pulsar.log)
[etcd.log](https://github.com/milvus-io/milvus/files/7036199/etcd.log)

**Comment by xiaofan-luan** [comment]
seeing same error log in pulsar, Starting with the -nss flag (no stream storage) will resolve the issue temporarily...

https://github.com/apache/pulsar/issues/5668

**Comment by xiaofan-luan** [comment]
hi zwd1208, can we change the pulsar start command to add -nss for our pulsar container, seems that this is a pulsar issue

**Comment by xiaofan-luan** [comment]
also it looks like the rootcoord failed to connect etcd for 04:14 to 05:45, while the etcd start from 05:42. Do you have more rood coord log after 5:45? @Bennu-Li

**Comment by Bennu-Li** [comment]
> also it looks like the rootcoord failed to connect etcd for 04:14 to 05:45, while the etcd start from 05:42. Do you have more rood coord log after 5:45? @Bennu-Li

I don't have any more. Attached are all logs of rootcord.

**Comment by wangting0128** [comment]
【**Occasionally**】
test yaml：
client-configmap: client-get-local50m-512
server-configmap: server-single-16c64m

argo task：benchmark-cluster-cron-1631131200

server deploy：
```
NAME: benchmark-cluster-cron-1631131200-1
LAST DEPLOYED: Wed Sep  8 20:00:25 2021
NAMESPACE: qa-milvus
STATUS: deployed
REVISION: 1
TEST SUITE: None
I0908 20:01:34.049342      28 request.go:665] Waited for 1.133830586s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.l
ocal/apis/monitoring.kiali.io/v1alpha1?timeout=32s
I0908 20:01:44.249206      28 request.go:665] Waited for 11.333544397s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.
local/apis/rbac.authorization.k8s.io/v1beta1?timeout=32s
NAME                                                              READY   STATUS    RESTARTS   AGE
benchmark-cluster-cron-1631131200-1-etcd-0                        1/1     Running   0          79s
benchmark-cluster-cron-1631131200-1-milvus-standalone-58f964wnn   1/1     Running   0          79s
```

client log：
```
[2021-09-08 22:45:58,563] [   DEBUG] - {'flush_time': 3.67} (milvus_benchmark.runners.get:118)
[2021-09-08 22:45:58,563] [   DEBUG] - Start load collection (milvus_benchmark.runners.get:119)
[2021-09-09 02:02:19,592] [   ERROR] - Error: <BaseException: (code=1, message=syncTimestamp Failed:Connect to rootcoord failed with error:
context canceled)> (pymilvus.client.grpc_handler:61)
[2021-09-09 02:02:19,593] [   ERROR] - Error: <BaseException: (code=1, message=syncTimestamp Failed:Connect to rootcoord failed with error:
context canceled)> (pymilvus.client.grpc_handler:61)
[2021-09-09 02:02:19,594] [   ERROR] - <BaseException: (code=1, message=syncTimestamp Failed:Connect to rootcoord failed with error:
context canceled)> (milvus_benchmark.main:114)
[2021-09-09 02:02:19,597] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 83, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/get.py", line 120, in prepare
    self.milvus.load_collection(timeout=1200)
  File "/src/milvus_benchmark/client.py", line 46, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 440, in load_collection
    return self._milvus.load_collection(collection_name, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 68, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 52, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 343, in load_collection
    return handler.load_collection("", collection_name=collection_name, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 59, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 827, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 59, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 845, in wait_for_loading_collection
    return self._wait_for_loading_collection_v2(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 872, in _wait_for_loading_collection_v2
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=syncTimestamp Failed:Connect to rootcoord failed with error:
context canceled)>
 (milvus_benchmark.main:115)
[2021-09-09 02:02:19,598] [   DEBUG] - {'_version': '0.1', '_type': 'metric', 'run_id': 1631131383, 'mode': 'local', 'server': <milvus_benchmark.metrics.models.server.Server object
at 0x7faeab113208>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware object at 0x7faeab113978>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7faeab113ac
8>, 'status': 'RUN_FAILED', 'err_message': '', 'collection': {'dimension': 512, 'metric_type': 'l2', 'dataset_name': 'local_50m_512_l2', 'collection_size': 50000000, 'other_fields':
 None, 'ni_per': 50000}, 'index': {'index_type': 'ivf_sq8', 'index_param': {'nlist': 1024}}, 'search': None, 'run_params': None, 'metrics': {'type': 'insert_get_performance', 'value
': {}}, 'datetime': '2021-09-08 20:03:03.416257', 'type': 'metric'} (milvus_benchmark.metric.api:29)
```
