### ISSUE TITLE
Drop collection failed: can't find collection even if the collection is created successfully

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#7306]
#### Steps/Code to reproduce:
1. deploy milvus with cluster mode (by milvus helm chart)
2. create a collection `e2e__k78CN3kh` and insert data
3. delete etcd pod with `kubectl delete pod {etcd}`
4. create collection `e2e__TRYI7BW9` and drop collection

#### Expected result:
If collection create successfully, then drop collection shouldn't raise exceptions that can't find collection

#### Actual results:
```
# 1. Collection() get success response
[2021-08-26 12:00:15 - DEBUG - ci_test]: (api_request)  : [Collection] args: ['e2e__TRYI7BW9', {"auto_id": false, "description": "", "fields": [{"name": "int64", "description": "", "type": 5, "is_primary": true, "auto_id": false}, {"name": "float", "description": "", "type": 10}, {"name": "float_vector", "description": "", "type": 101, "params": {"dim": 128}}]}], kwargs: {} (api_request.py:44)
[2021-08-26 12:00:15 - DEBUG - ci_test]: (api_response) : {"name": "e2e__TRYI7BW9", "schema": {"auto_id": false, "description": "", "fields": [{"name": "int64", "description": "", "type": 5, "is_primary": true, "auto_id": false}, {"name": "float", "description": "", "type": 10}, {"name": "float_vector", "description": "", "type": 101, "params": {"dim": 128......  (api_request.py:21)

# 2. ist_collections()
[2021-08-26 12:00:21,122 - DEBUG - ci_test]: (api_request)  : [list_collections] args: [20, 'default'], kwargs: {} (api_request.py:44)
[2021-08-26 12:00:21,131 - DEBUG - ci_test]: (api_response) : ['e2e__k78CN3kh', 'e2e__TRYI7BW9']  (api_request.py:21)

# 3. drop collection()
[2021-08-26 12:00:21,131 - DEBUG - ci_test]: (api_request)  : [Collection.drop] args: [], kwargs: {'timeout': 20} (api_request.py:44)
[2021-08-26 12:00:43,170 - ERROR - ci_test]: Traceback (most recent call last):
  File "/home/zong/zong/projects/milvus/tests/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/home/zong/zong/projects/milvus/tests/python_client/utils/api_request.py", line 45, in api_request
    return func(*arg, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/orm/pymilvus_orm/collection.py", line 404, in drop
    conn.drop_collection(self._name, timeout=timeout, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 66, in handler
    raise e
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 52, in handler
    return func(self, *args, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 258, in drop_collection
    return handler.drop_collection(collection_name, timeout)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    raise e
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 59, in handler
    return func(self, *args, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 390, in drop_collection
    raise BaseException(status.error_code, status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=Drop collection failed: can't find collection: e2e__TRYI7BW9)>
 (api_request.py:26)
```

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):
  4d9f89d
- Deployment mode(standalone or cluster):
  cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
   pymilvus              2.0.0rc5.dev20
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others: 

#### Additional context:
Logs
[milvus_logs.tar.gz](https://github.com/milvus-io/milvus/files/7051517/milvus_logs.tar.gz)

**Comment by ThreadDao** [comment]
I reproduced it in version `65f168e Mon Aug 30 02:07:15 UTC 2021`

**Comment by sunby** [comment]
Proxy received 2 DropCollection requests. RootCoord remove collection meta from memory and send this message to other services.  Because etcd crashed and rootcoord can not find other services from etcd, the first DropCollection timeout. After the first timeout, client resend the request and RootCoord can not find the collection info in memory so it returned `can't find collection: ` error.

**Comment by czs007** [comment]
I tend to make drop/create collections idempotent.  how do you think? @sunby @ThreadDao @xiaofan-luan 
If it is made idempotent, I wonder if the test case needs to be changed a lot? @ThreadDao

**Comment by sunby** [comment]
> I tend to make drop/create collections idempotent. how do you think? @sunby @ThreadDao @xiaofan-luan
> If it is made idempotent, I wonder if the test case needs to be changed a lot? @ThreadDao

If we have deleted a collection the first time but fail to send response to client. The client resend the request and what do you want to return, non-existed-collection error or success? If you return an error, it's werid that you successfully delete a collection but return an error. If return success, you can not diff whether the collection actually exist before you drop.

**Comment by ThreadDao** [comment]
Create collection successfully,  then drop collection get exception `StatusCode.DEADLINE_EXCEEDED`, then list collection result is empty.
1. Version
```
Version:   3b96096
Built:     Tue Aug 31 10:37:59 UTC 2021
```
2. Results
a. Except:
```
[2021-08-31 19:57:17,097 - DEBUG - ci_test]: (api_request)  : [Collection] args: ['e2e__Q1GbhbRy', {"auto_id": false, "description": "", "fields": [{"name": "int64", "description": "", "type": 5, "is_primary": true, "auto_id": false}, {"name": "float", "description": "", "type": 10}, {"name": "float_vector", "description": "", "type": 101, "params": {"dim": 128}}]}], kwargs: {} (api_request.py:44)
[2021-08-31 19:57:17,137 - DEBUG - ci_test]: (api_response) : {"name": "e2e__Q1GbhbRy", "schema": {"auto_id": false, "description": "", "fields": [{"name": "int64", "description": "", "type": 5, "is_primary": true, "auto_id": false}, {"name": "float", "description": "", "type": 10}, {"name": "float_vector", "description": "", "type": 101, "params": {"dim": 128......  (api_request.py:21)
[2021-08-31 19:57:17,138 - DEBUG - ci_test]: assert create: 0:00:01.063150 (test_e2e_20.py:23)
[2021-08-31 19:57:17,138 - DEBUG - ci_test]: (api_request)  : [list_collections] args: [20, 'default'], kwargs: {} (api_request.py:44)
[2021-08-31 19:57:17,147 - DEBUG - ci_test]: (api_response) : ['e2e__Q1GbhbRy']  (api_request.py:21)
[2021-08-31 19:57:17,147 - DEBUG - ci_test]: ['e2e__Q1GbhbRy'] (test_e2e_20.py:26)

[2021-08-31 19:57:17,147 - INFO - ci_test]: *********************************** teardown *********************************** (client_base.py:61)
[2021-08-31 19:57:17,147 - INFO - ci_test]: [teardown_method] Start teardown test case test_milvus_default... (client_base.py:62)
[2021-08-31 19:57:17,147 - DEBUG - ci_test]: (api_request)  : [Connections.get_connection] args: ['default'], kwargs: {} (api_request.py:44)
[2021-08-31 19:57:17,147 - DEBUG - ci_test]: (api_response) : <pymilvus.client.stub.Milvus object at 0x7f039ed2cc40>  (api_request.py:21)
[2021-08-31 19:57:17,147 - DEBUG - ci_test]: (api_request)  : [list_collections] args: [20, 'default'], kwargs: {} (api_request.py:44)
[2021-08-31 19:57:17,155 - DEBUG - ci_test]: (api_response) : ['e2e__Q1GbhbRy']  (api_request.py:21)
[2021-08-31 19:57:17,155 - DEBUG - ci_test]: (api_request)  : [Collection.drop] args: [], kwargs: {'timeout': 20} (api_request.py:44)
[2021-08-31 19:57:17,192 - DEBUG - ci_test]: (api_response) : None  (api_request.py:21)
```
 b. Actual:
```
[2021-08-31 20:05:50,436 - DEBUG - ci_test]: (api_request)  : [Collection] args: ['e2e__YqMRSoEu', {"auto_id": false, "description": "", "fields": [{"name": "int64", "description": "", "type": 5, "is_primary": true, "auto_id": false}, {"name": "float", "description": "", "type": 10}, {"name": "float_vector", "description": "", "type": 101, "params": {"dim": 128}}]}], kwargs: {} (api_request.py:44)
[2021-08-31 20:05:50,478 - DEBUG - ci_test]: (api_response) : {"name": "e2e__YqMRSoEu", "schema": {"auto_id": false, "description": "", "fields": [{"name": "int64", "description": "", "type": 5, "is_primary": true, "auto_id": false}, {"name": "float", "description": "", "type": 10}, {"name": "float_vector", "description": "", "type": 101, "params": {"dim": 128......  (api_request.py:21)
[2021-08-31 20:05:50,478 - DEBUG - ci_test]: assert create: 0:00:01.067494 (test_e2e_20.py:23)
[2021-08-31 20:05:50,478 - DEBUG - ci_test]: (api_request)  : [list_collections] args: [20, 'default'], kwargs: {} (api_request.py:44)
[2021-08-31 20:05:50,490 - DEBUG - ci_test]: (api_response) : ['e2e__YqMRSoEu']  (api_request.py:21)
[2021-08-31 20:05:50,490 - DEBUG - ci_test]: ['e2e__YqMRSoEu'] (test_e2e_20.py:26)

[2021-08-31 20:05:50,491 - INFO - ci_test]: *********************************** teardown *********************************** (client_base.py:61)
[2021-08-31 20:05:50,491 - INFO - ci_test]: [teardown_method] Start teardown test case test_milvus_default... (client_base.py:62)
[2021-08-31 20:05:50,491 - DEBUG - ci_test]: (api_request)  : [Connections.get_connection] args: ['default'], kwargs: {} (api_request.py:44)
[2021-08-31 20:05:50,491 - DEBUG - ci_test]: (api_response) : <pymilvus.client.stub.Milvus object at 0x7fbb19104dc0>  (api_request.py:21)
[2021-08-31 20:05:50,491 - DEBUG - ci_test]: (api_request)  : [list_collections] args: [20, 'default'], kwargs: {} (api_request.py:44)
[2021-08-31 20:05:50,501 - DEBUG - ci_test]: (api_response) : ['e2e__YqMRSoEu']  (api_request.py:21)
[2021-08-31 20:05:50,501 - DEBUG - ci_test]: (api_request)  : [Collection.drop] args: [], kwargs: {'timeout': 20} (api_request.py:44)
[2021-08-31 20:06:10,519 - ERROR - ci_test]: Traceback (most recent call last):
  File "/home/zong/zong/projects/milvus/tests/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/home/zong/zong/projects/milvus/tests/python_client/utils/api_request.py", line 45, in api_request
    return func(*arg, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/orm/pymilvus_orm/collection.py", line 409, in drop
    conn.drop_collection(self._name, timeout=timeout, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 60, in handler
    raise e
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 52, in handler
    return func(self, *args, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 264, in drop_collection
    return handler.drop_collection(collection_name, timeout)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 77, in handler
    raise e
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 59, in handler
    return func(self, *args, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 388, in drop_collection
    status = rf.result()
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/grpc/_channel.py", line 744, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "{"created":"@1630411570.514459145","description":"Error received from peer ipv4:10.98.0.8:19530","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
 (api_request.py:26)
[2021-08-31 20:06:10,519 - ERROR - ci_test]: (api_response) : <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "{"created":"@1630411570.514459145","description":"Error received from peer ipv4:10.98.0.8:19530","file":"src/core/lib/surface/call.cc","file_line":1067,...... (api_request.py:27)
```
3. Log or pods
[milvus_logs.tar.gz](https://github.com/milvus-io/milvus/files/7083764/milvus_logs.tar.gz)
```
milvus-chaos-datacoord-756588d59c-9pqpw         1/1     Running     0          17m
milvus-chaos-datanode-7cf694bc94-fcmq5          1/1     Running     0          17m
milvus-chaos-etcd-0                             1/1     Running     0          7m4s
milvus-chaos-indexcoord-fd9c6f54d-n92jj         1/1     Running     0          17m
milvus-chaos-indexnode-7cd6c6c7f5-vmfpx         1/1     Running     0          17m
milvus-chaos-minio-6cd5bb4c6f-zrcd2             1/1     Running     0          17m
milvus-chaos-proxy-79d8b948f8-x8s75             1/1     Running     0          17m
milvus-chaos-pulsar-65c554875-7rkbd             1/1     Running     0          17m
milvus-chaos-querycoord-66b76476f9-8d9gh        1/1     Running     0          17m
milvus-chaos-querynode-6b45f7bb5c-vml56         1/1     Running     0          17m
milvus-chaos-rootcoord-89d94b5fc-fldns          1/1     Running     1          17m
```
