### ISSUE TITLE
Querycoord container exited in less than 1 minutes when re-install cluster milvus

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#7344]
#### Steps/Code to reproduce:
* deploy Milvus by docker-compose up -d
* insert data and create index
* shut down milvus by docker-compose down (keep volumes dir)
* re-install milvus by docker-compose up -d
* check containers status
#### Expected result:
all containers running 

#### Actual results:
querycoord container exited in less than 1 minutes

#### Environment:
- Milvus version : 2dc2cb1
- Deployment mode : cluster
- SDK version : 2.0.0rc5.dev18
- OS : MacOS
- CPU/Memory: 
- GPU: 
- Others: 

#### Additional context:
All logs
[08-27.log](https://github.com/milvus-io/milvus/files/7066559/08-27.log)
something in termina but not in log
```
time="2021-08-27T11:01:49Z" level=info msg="[Connecting to broker]" remote_addr="pulsar://pulsar:6650"
time="2021-08-27T11:01:49Z" level=info msg="[TCP connection established]" local_addr="192.168.160.11:60550" remote_addr="pulsar://pulsar:6650"
time="2021-08-27T11:01:49Z" level=info msg="[Connection is ready]" local_addr="192.168.160.11:60550" remote_addr="pulsar://pulsar:6650"
time="2021-08-27T11:01:49Z" level=info msg="[Connecting to broker]" remote_addr="pulsar://pulsar:6650"
time="2021-08-27T11:01:49Z" level=info msg="[TCP connection established]" local_addr="192.168.160.11:60552" remote_addr="pulsar://pulsar:6650"
time="2021-08-27T11:01:49Z" level=info msg="[Connection is ready]" local_addr="192.168.160.11:60552" remote_addr="pulsar://pulsar:6650"
time="2021-08-27T11:01:49Z" level=info msg="[Created producer]" cnx="192.168.160.11:60552 -> 192.168.160.3:6650" producerID=1 producer_name=standalone-1-3 topic="persistent://public/default/query-node-stats"
```
Querycoord log
[querycoord-08-27.log](https://github.com/milvus-io/milvus/files/7066566/querycoord-08-27.log)
something in termina but not in log
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xe27f19]

goroutine 230 [running]:
google.golang.org/grpc.(*ClientConn).Close(0x0, 0x0, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.38.0/clientconn.go:1030 +0x59
github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Stop(0xc0000d2440, 0x0, 0xc000734c80)
        /go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:130 +0x2f
github.com/milvus-io/milvus/internal/querycoord.(*queryNode).stop(0xc0000dcc60)
        /go/src/github.com/milvus-io/milvus/internal/querycoord/querynode.go:126 +0xac
github.com/milvus-io/milvus/internal/querycoord.(*queryNodeCluster).stopNode(0xc000733640, 0x8)
        /go/src/github.com/milvus-io/milvus/internal/querycoord/cluster.go:494 +0xf0
github.com/milvus-io/milvus/internal/querycoord.(*QueryCoord).watchNodeLoop(0xc0006861a0)
        /go/src/github.com/milvus-io/milvus/internal/querycoord/query_coord.go:204 +0x7f3
created by github.com/milvus-io/milvus/internal/querycoord.(*QueryCoord).Start
        /go/src/github.com/milvus-io/milvus/internal/querycoord/query_coord.go:123 +0xd7
```

**Comment by zhuwenxing** [comment]
Verified and fixed.
Version: af574d1
