### ISSUE TITLE
Milvus-CLI: Search failed, C runtime error detected. Error in virtual milvus::knowhere::DatasetPtr milvus::knowhere::I

### ISSUE THREAD

**Issue by jaelgu** [milvus-io/milvus#7359]
#### Steps/Code to reproduce:

Install and use milvus-cli (https://github.com/milvus-io/milvus_cli)
1. create collection -n test_collection -f pk:INT64:primary_field -f emb:FLOAT_VECTOR:128 -f test_field:INT64:test_field -p pk -d 'test_description'
2. import milvus_cli > import 'my_csv_path' -c test_collection
(3000 rows inserted successfully)
3. create index -c test_collection
4. load -c test_collection (show loading_progress -c test_collection --> 3000 rows loaded)
5. search process: (inputs are [2 random vectors with dim=128])

#### Expected result:
Return search results properly

#### Actual results:
Search failed, C runtime error detected. Error in virtual milvus::knowhere::DatasetPtr milvus::knowhere::I
<img width="1436" alt="Screen Shot 2021-08-30 at 11 36 34 AM" src="https://user-images.githubusercontent.com/86251631/131283826-c2734478-1d73-429a-9ba4-676dee05d604.png">

#### Environment:
- Milvus version: v2.0.0rc4
- Deployment mode(standalone or cluster): standalone
- SDK version:  pymilvus-orm v2.0.0rc4
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others: Milvus Cli v0.1.4

**Comment by yanliang567** [comment]
According to my experience, it was caused by the search params are not matched with the index params, please refer to https://milvus.io/docs/v2.0.0/index_selection.md and double check the search params

**Comment by jaelgu** [comment]
@yanliang567 I tried with the following parameters:
- index: type = IVF_FLAT, metric_type = L2, nlist = 128
- search: metric_type = L2, nlist (nprobe?) = 20 (also tried with 128)
But still got the same error.

**Comment by yanliang567** [comment]
@jaelgu  could you please retry on milvus rc5

**Comment by jaelgu** [comment]
@yanliang567 Tried with updated milvus_cli & rc5. Still got the same error.

**Comment by czhen-zilliz** [comment]
I got a similar error by following the procedure above.
env: pymilvus==rc5; milvus rc5
```
$ python
Python 3.7.10 (default, May 20 2021, 15:31:48) 
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pymilvus import connections, Collection, FieldSchema, CollectionSchema, DataType
>>> import random
>>> fields = [
...     FieldSchema("pk", DataType.INT64, is_primary=True),
...     FieldSchema("emb", dtype=DataType.FLOAT_VECTOR, dim=128),
...     FieldSchema("test_field", DataType.INT64),
... ]
>>> description="This is a new collection description."
>>> schema = CollectionSchema(fields=fields, description=description)
>>> collection = Collection(name="test_collection", schema=schema)
>>> data = [
...     [random.randint(1, 100) for _ in range(10000)],
...     [[random.random() for _ in range(128)] for _ in range(10000)],
...     [random.randint(1, 100) for _ in range(10000)]
... ]
>>> collection.insert(data)
(insert count: 10000, delete count: 0, upsert count: 0, timestamp: 427416891485847553)
>>> collection.num_entities
10000
>>> index = {"index_type": "IVF_FLAT", "params": {"nlist": 128}, "metric_type": "L2"}
>>> collection.create_index("emb", index)
Status(code=0, message='')
>>> collection.indexes
[<pymilvus.orm.pymilvus_orm.index.Index object at 0x10df0e350>]
>>> collection.load()
>>> search_param = {
...     "data": [[random.random() for _ in range(128)] for _ in range(2)],
...     "anns_field": "emb",
...     "param": {"metric_type": "L2"},
...     "limit": 2,
... }
>>> res = collection.search(**search_param)
Error: <BaseException: (code=1, message=Search failed, C runtime error detected, error code = 1, error msg = 
)>
Error: <BaseException: (code=1, message=Search failed, C runtime error detected, error code = 1, error msg = 
)>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/czhen/Documents/github/milvus_cli/venv/lib/python3.7/site-packages/pymilvus/orm/pymilvus_orm/collection.py", line 610, in search
    partition_names, output_fields, timeout, **kwargs)
  File "/Users/czhen/Documents/github/milvus_cli/venv/lib/python3.7/site-packages/pymilvus/client/stub.py", line 66, in handler
    raise e
  File "/Users/czhen/Documents/github/milvus_cli/venv/lib/python3.7/site-packages/pymilvus/client/stub.py", line 52, in handler
    return func(self, *args, **kwargs)
  File "/Users/czhen/Documents/github/milvus_cli/venv/lib/python3.7/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/Users/czhen/Documents/github/milvus_cli/venv/lib/python3.7/site-packages/pymilvus/client/stub.py", line 1057, in search_with_expression
    return handler.search_with_expression(collection_name, data, anns_field, param, limit, expression, partition_names, output_fields, timeout, **kwargs)
  File "/Users/czhen/Documents/github/milvus_cli/venv/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    raise e
  File "/Users/czhen/Documents/github/milvus_cli/venv/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 59, in handler
    return func(self, *args, **kwargs)
  File "/Users/czhen/Documents/github/milvus_cli/venv/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 96, in handler
    return func(self, *args, **kwargs)
  File "/Users/czhen/Documents/github/milvus_cli/venv/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 640, in search_with_expression
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/Users/czhen/Documents/github/milvus_cli/venv/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    raise e
  File "/Users/czhen/Documents/github/milvus_cli/venv/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 59, in handler
    return func(self, *args, **kwargs)
  File "/Users/czhen/Documents/github/milvus_cli/venv/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 606, in _execute_search_requests
    raise pre_err
  File "/Users/czhen/Documents/github/milvus_cli/venv/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 597, in _execute_search_requests
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=Search failed, C runtime error detected, error code = 1, error msg = 
)>
>>> 
```

**Comment by yanliang567** [comment]
@czhen-zilliz it seems that you missed 'nprobe' in the search_param.
