### ISSUE TITLE
milvus-standalone container 2.0.0-RC5 error

### ISSUE THREAD

**Issue by kevinzezel** [milvus-io/milvus#7390]
Hi,

I was testing the new version of milvus, 2.0.0-RC5. After insert 45MM embeddings with 512d, milvus-standalone container stop and does not start any more. 

Docker logs:

```
[2021/08/31 11:20:04.096 +00:00] [DEBUG] [rocksmq_retention.go:264] ["In ticker: "] [ticker=1630408804]
[2021/08/31 11:20:04.096 +00:00] [DEBUG] [rocksmq_retention.go:353] ["In expiredCleanUp: "] [topic=facerec_ivf_flat_427391878742671361_1] [endID=0] [deletedAckedSize=0]
[2021/08/31 11:20:04.096 +00:00] [DEBUG] [rocksmq_retention.go:372] ["All messages are not expired"]
[2021/08/31 11:20:04.096 +00:00] [DEBUG] [rocksmq_retention.go:353] ["In expiredCleanUp: "] [topic=facerec_ivf_flat_427391878742671361_0] [endID=427391803498300469] [deletedAckedSize=2147633792]
panic: runtime error: slice bounds out of range [10:0]

goroutine 180 [running]:
github.com/milvus-io/milvus/internal/util/rocksmq/server/rocksmq.(*retentionInfo).expiredCleanUp(0xc000267080, 0xc0000c06cf, 0x25, 0x0, 0x0)
	/go/src/github.com/milvus-io/milvus/internal/util/rocksmq/server/rocksmq/rocksmq_retention.go:380 +0x22f6
github.com/milvus-io/milvus/internal/util/rocksmq/server/rocksmq.(*retentionInfo).retention.func1(0x2264640, 0xc0006481a0, 0x2263b40, 0xc00bb90948, 0x1)
	/go/src/github.com/milvus-io/milvus/internal/util/rocksmq/server/rocksmq/rocksmq_retention.go:267 +0x95
sync.(*Map).Range(0xc0002670f8, 0xc0253b7f08)
	/usr/local/go/src/sync/map.go:345 +0x1d9
github.com/milvus-io/milvus/internal/util/rocksmq/server/rocksmq.(*retentionInfo).retention(0xc000267080, 0xc0008a018f, 0xe)
	/go/src/github.com/milvus-io/milvus/internal/util/rocksmq/server/rocksmq/rocksmq_retention.go:265 +0x13e
created by github.com/milvus-io/milvus/internal/util/rocksmq/server/rocksmq.(*retentionInfo).startRetentionInfo
	/go/src/github.com/milvus-io/milvus/internal/util/rocksmq/server/rocksmq/rocksmq_retention.go:121 +0x11e


```
```
Milvus version: v2.0.0-RC5
Deployment mode: standalone
SDK version: pymilvus v2.0.0rc4
OS: Ubuntu 18.04.1-64 Minimal for Bare Metal
CPU/Memory: 2x 2.2GHz Intel Xeon-Broadwell (E5-2650-V4)/ 756gb ram
GPU: 2x NVIDIA Tesla-V100-PCIe-32GB
Others: IBM Bare Metal
Docker image Ubuntu 20.04 and Python 3.8.10
```

**Comment by xiaofan-luan** [comment]
we are working on that

**Comment by yanliang567** [comment]
Here are repro steps:
1. Update milvus helm values.yaml to shorten the retention time:
```
rocksmq:
    retentionTimeInMinutes: 10
```
2. helm install Milvus 2.0 standalone
3. write a script to insert data into collection( 5 threads, insert 20,000 entities for 100 rounds)

the panic error repos during inserting(10 mins after the first insert)

**Comment by stefan-it** [comment]
Hey guys, was this error fixed in RC5 :thinking: 

I'm currently using the Milvus standalone with `milvusdb/milvus:v2.0.0-rc5-hotfix1-20210901-9e0b2cc` and I'm getting pretty much the same error! I'm using RC5 of `pymilvus`.

**Comment by yanliang567** [comment]
@stefan-it it looks like a different issue. could you please file a new issue?
