### ISSUE TITLE
Milvus crashed throwing panic 

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#7405]
#### Steps/Code to reproduce:
Running test cases in local kind env.

#### Expected result:
No crash

#### Actual results:
Milvus crashed

Through 0.log:

```
2021-09-01T08:54:34.636168541Z stdout F [2021/09/01 08:54:34.635 +00:00] [DEBUG] [streaming.go:174] ["get segmentIDs by vChannel"] [collectionID=427422244604739587] [vChannel=rootcoord-dml_7_427422244604739587v] [partitionID=427422244604739588] [segmentIDs="[]"]
2021-09-01T08:54:34.636174293Z stdout F [2021/09/01 08:54:34.635 +00:00] [DEBUG] [time_recorder.go:73] ["search 427422244604739587(nq=1000, k=1): streaming search done (0ms)"]
2021-09-01T08:54:34.638801244Z stderr F [signal SIGSEGV: segmentation violation code=0x2 addr=0x7ff8a8108440 pc=0x7ff8a8108440]
2021-09-01T08:54:34.638822721Z stderr F
2021-09-01T08:54:34.638828364Z stderr F runtime stack:
2021-09-01T08:54:34.638833154Z stderr F runtime.throw(0x253bacc, 0x2a)
2021-09-01T08:54:34.638838531Z stderr F         /usr/local/go/src/runtime/panic.go:1116 +0x72
2021-09-01T08:54:34.638842608Z stderr F runtime.sigpanic()
2021-09-01T08:54:34.638846311Z stderr F         /usr/local/go/src/runtime/signal_unix.go:704 +0x4ac
2021-09-01T08:54:34.638850014Z stderr F
2021-09-01T08:54:34.638853512Z stderr F goroutine 2724027 [syscall]:
2021-09-01T08:54:34.638881199Z stderr F runtime.cgocall(0x16d0b12, 0xc0123c6b88, 0xc013f38078)
2021-09-01T08:54:34.638884808Z stderr F         /usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc0123c6b58 sp=0xc0123c6b20 pc=0x729a5b
2021-09-01T08:54:34.638958304Z stderr F github.com/milvus-io/milvus/internal/querynode._Cfunc_ReduceSearchResultsAndFillData(0x7ff8f44fdc40, 0xc00a195d40, 0x2, 0x0, 0x0)
2021-09-01T08:54:34.638965263Z stderr F         _cgo_gotypes.go:734 +0x56 fp=0xc0123c6b88 sp=0xc0123c6b58 pc=0x16a7456
2021-09-01T08:54:34.638969805Z stderr F github.com/milvus-io/milvus/internal/querynode.reduceSearchResultsAndFillData.func1(0xc0279fe910, 0xc00a195d40, 0x2, 0x1, 0x2)
2021-09-01T08:54:34.63905375Z stderr F  /go/src/github.com/milvus-io/milvus/internal/querynode/reduce.go:45 +0x8f fp=0xc0123c6bc8 sp=0xc0123c6b88 pc=0x16bc70f
2021-09-01T08:54:34.639062669Z stderr F github.com/milvus-io/milvus/internal/querynode.reduceSearchResultsAndFillData(0xc0279fe910, 0xc00a195cd0, 0x2, 0x2, 0x2, 0x0, 0x0)
2021-09-01T08:54:34.639228607Z stderr F         /go/src/github.com/milvus-io/milvus/internal/querynode/reduce.go:45 +0x16c fp=0xc0123c6c80 sp=0xc0123c6bc8 pc=0x16b29ec
2021-09-01T08:54:34.639234612Z stderr F github.com/milvus-io/milvus/internal/querynode.(*queryCollection).search(0xc003cda8c0, 0x2722020, 0xc011629440, 0x0, 0x0)
2021-09-01T08:54:34.639301182Z stderr F         /go/src/github.com/milvus-io/milvus/internal/querynode/query_collection.go:920 +0x155f fp=0xc0123c74c8 sp=0xc0123c6c80 pc=0x16939df
2021-09-01T08:54:34.639307756Z stderr F github.com/milvus-io/milvus/internal/querynode.(*queryCollection).receiveQueryMsg(0xc003cda8c0, 0x2722020, 0xc011629440, 0x0, 0x0)
2021-09-01T08:54:34.639311756Z stderr F         /go/src/github.com/milvus-io/milvus/internal/querynode/query_collection.go:387 +0x1aa5 fp=0xc0123c7ec0 sp=0xc0123c74c8 pc=0x168c805
2021-09-01T08:54:34.639316882Z stderr F github.com/milvus-io/milvus/internal/querynode.(*queryCollection).consumeQuery(0xc003cda8c0)
2021-09-01T08:54:34.639418852Z stderr F         /go/src/github.com/milvus-io/milvus/internal/querynode/query_collection.go:235 +0x32b fp=0xc0123c7fd8 sp=0xc0123c7ec0 pc=0x168ab8b
2021-09-01T08:54:34.639427594Z stderr F runtime.goexit()
2021-09-01T08:54:34.63943201Z stderr F  /usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc0123c7fe0 sp=0xc0123c7fd8 pc=0x796801
2021-09-01T08:54:34.639577608Z stderr F created by github.com/milvus-io/milvus/internal/querynode.(*queryCollection).start
2021-09-01T08:54:34.639585153Z stderr F         /go/src/github.com/milvus-io/milvus/internal/querynode/query_collection.go:123 +0xa5
```

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): 71aa300
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
Name: pymilvus
Version: 2.0.0rc6.dev3
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by binbinlv** [comment]
please contact me to get the full logs, thanks.

**Comment by yanliang567** [comment]
looks like an OOM for query node. does it still repo on rc6 @binbinlv , if yes, please set it to urgent, thx.

**Comment by binbinlv** [comment]
This is not reproduced on rc6, so close it first, will reopen if it occurs again.
