### ISSUE TITLE
Insert does not support string type

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#7513]
#### Steps/Code to reproduce:
1. Create a collection with `[int64, string, float_vector]` fields
2. Failed to insert list data
```
 def test_collection(self):
        self._connect()
        str_field, _ = self.field_schema_wrap.init_field_schema(name="str", dtype=DataType.STRING,
                                                                is_primary=False)
        # df = cf.gen_default_dataframe_data()
        fields = [str_field, cf.gen_int64_field(is_primary=True), cf.gen_float_vec_field()]
        schema, _ = self.collection_schema_wrap.init_collection_schema(fields=fields)
        self.collection_wrap.init_collection(cf.gen_unique_str(prefix), schema)
        int_values = [i for i in range(ct.default_nb)]
        str_values = ["a" for i in range(ct.default_nb)]
        float_vec_values = gen_vectors(ct.default_nb, ct.default_dim)
        data = [str_values, int_values, float_vec_values]
        self.collection_wrap.insert(data)
        assert self.collection_wrap.num_entities == ct.default_nb
```

#### Expected result:
Create collection successfully, insert data successfully

#### Actual results:
Create collection successfully, and failed to insert
```
[2021-09-06 19:51:45,630 - DEBUG - ci_test]: (api_request)  : [Collection] args: ['collection_FUbr6Bzu', {"auto_id": false, "description": "", "fields": [{"name": "str", "description": "", "type": 20}, {"name": "int64", "description": "", "type": 5, "is_primary": true, "auto_id": false}, {"name": "float_vector", "description": "", "type": 101, "params": {"dim": 128}}]}], kwargs: {} (api_request.py:44)
[2021-09-06 19:51:45,673 - DEBUG - ci_test]: (api_response) : {"name": "collection_FUbr6Bzu", "schema": {"auto_id": false, "description": "", "fields": [{"name": "str", "description": "", "type": 20}, {"name": "int64", "description": "", "type": 5, "is_primary": true, "auto_id": false}, {"name": "float_vector", "description": "", "type": 101, "params": {"dim":......  (api_request.py:21)
[2021-09-06 19:51:45,803 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [[['a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a......, kwargs: {'timeout': 20} (api_request.py:44)
[2021-09-06 19:51:45,846 - ERROR - ci_test]: Traceback (most recent call last):
  File "/home/zong/zong/projects/milvus/tests/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/home/zong/zong/projects/milvus/tests/python_client/utils/api_request.py", line 45, in api_request
    return func(*arg, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/orm/pymilvus_orm/collection.py", line 522, in insert
    res = conn.insert(collection_name=self._name, entities=entities, ids=None,
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 68, in handler
    raise e
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 52, in handler
    return func(self, *args, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 861, in insert
    return handler.bulk_insert(collection_name, entities, partition_name, timeout, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 82, in handler
    raise e
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 59, in handler
    return func(self, *args, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 541, in bulk_insert
    raise err
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 527, in bulk_insert
    request = self._prepare_bulk_insert_request(collection_name, entities, partition_name, timeout, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 520, in _prepare_bulk_insert_request
    else Prepare.bulk_insert_param(collection_name, entities, partition_name, fields_info)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/prepare.py", line 353, in bulk_insert_param
    raise ParamError("UnSupported data type")
pymilvus.client.exceptions.ParamError: UnSupported data type
 (api_request.py:26)
[2021-09-06 19:51:45,847 - ERROR - ci_test]: (api_response) : UnSupported data type (api_request.py:27)
```

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):
  86afde4    Mon Sep  6 03:56:05 UTC 2021
- Deployment mode(standalone or cluster):
   cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
   pymilvus              2.0.0rc6.dev4
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by xealml** [comment]
may have a time line?

**Comment by skriser** [comment]
I have got the same problem: 
pymilvus=pymilvus-2.0.0rc8
and i check the code ,then find that Insert does not support string type  in this version :
in pymilvus/client/prepare.py line:275
     for entity in entities:
            field_data = schema_types.FieldData()
            if entity.get("type") in (DataType.BOOL,):
                field_data.type = schema_types.DataType.Value("Bool")
                field_data.field_name = entity.get("name")
                field_data.scalars.bool_data.data.extend(entity.get("values"))
                if row_num != 0 and row_num != len(entity.get("values")):
                    raise ParamError("row num of all fields is not different")
                row_num = len(entity.get("values"))
            elif entity.get("type") in (DataType.INT8,):
                field_data.type = schema_types.DataType.Value("Int8")
                field_data.field_name = entity.get("name")
                field_data.scalars.int_data.data.extend(entity.get("values"))
                if row_num != 0 and row_num != len(entity.get("values")):
                    raise ParamError("row num of all fields is not different")
                row_num = len(entity.get("values"))
            elif entity.get("type") in (DataType.INT16,):
                field_data.type = schema_types.DataType.Value("Int16")
                field_data.field_name = entity.get("name")
                field_data.scalars.int_data.data.extend(entity.get("values"))
                if row_num != 0 and row_num != len(entity.get("values")):
                    raise ParamError("row num of all fields is not different")
                row_num = len(entity.get("values"))
            elif entity.get("type") in (DataType.INT32,):
                field_data.type = schema_types.DataType.Value("Int32")
                field_data.field_name = entity.get("name")
                field_data.scalars.int_data.data.extend(entity.get("values"))
                if row_num != 0 and row_num != len(entity.get("values")):
                    raise ParamError("row num of all fields is not different")
                row_num = len(entity.get("values"))
            elif entity.get("type") in (DataType.INT64,):
                field_data.type = schema_types.DataType.Value("Int64")
                field_data.field_name = entity.get("name")
                field_data.scalars.long_data.data.extend(entity.get("values"))
                if row_num != 0 and row_num != len(entity.get("values")):
                    raise ParamError("row num of all fields is not different")
                row_num = len(entity.get("values"))
            elif entity.get("type") in (DataType.FLOAT,):
                field_data.type = schema_types.DataType.Value("Float")
                field_data.field_name = entity.get("name")
                field_data.scalars.float_data.data.extend(entity.get("values"))
                if row_num != 0 and row_num != len(entity.get("values")):
                    raise ParamError("row num of all fields is not different")
                row_num = len(entity.get("values"))
            elif entity.get("type") in (DataType.DOUBLE,):
                field_data.type = schema_types.DataType.Value("Double")
                field_data.field_name = entity.get("name")
                field_data.scalars.double_data.data.extend(entity.get("values"))
                if row_num != 0 and row_num != len(entity.get("values")):
                    raise ParamError("row num of all fields is not different")
                row_num = len(entity.get("values"))
            elif entity.get("type") in (DataType.FLOAT_VECTOR,):
                field_data.type = schema_types.DataType.Value("FloatVector")
                field_data.field_name = entity.get("name")
                field_data.vectors.dim = len(entity.get("values")[0])
                if row_num != 0 and row_num != len(entity.get("values")):
                    raise ParamError("row num of all fields is not different")
                row_num = len(entity.get("values"))
                all_floats = [f for vector in entity.get("values") for f in vector]
                field_data.vectors.float_vector.data.extend(all_floats)
            elif entity.get("type") in (DataType.BINARY_VECTOR,):
                field_data.type = schema_types.DataType.Value("BinaryVector")
                field_data.field_name = entity.get("name")
                if row_num != 0 and row_num != len(entity.get("values")):
                    raise ParamError("row num of all fields is not different")
                row_num = len(entity.get("values"))
                field_data.vectors.dim = len(entity.get("values")[0]) * 8
                for vector in entity.get("values"):
                    field_data.vectors.binary_vector += vector
            else:
                raise ParamError("UnSupported data type")


Environment:
Milvus version(e.g. v2.0.0-rc8)
Deployment mode(standalone or cluster):
standalone
SDK version(e.g. pymilvus v2.0.0-rc8):
pymilvus v2.0.0-rc8
OS(Ubuntu or CentOS): 
CPU/Memory:
GPU:
Others:
