### ISSUE TITLE
Does not support querying by bool field

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#7521]
#### Steps/Code to reproduce:
1. create dataFrame with fields `[int64, float, float_vec, bool]`
2. construct collection from dataframe (create collection and insert)
3. flush and load
4. query with expr: `bool in [False]`
```
    def test_query_bool(self):
        self._connect()
        df = cf.gen_default_dataframe_data()
        bool_values = pd.Series(data=[np.bool(i) for i in range(ct.default_nb)], dtype="bool")
        df["bool"] = bool_values
        self.collection_wrap.construct_from_dataframe(cf.gen_unique_str(prefix), df,
                                                      primary_field=ct.default_int64_field_name)
        assert self.collection_wrap.num_entities == ct.default_nb
        self.collection_wrap.load()
        term_expr = f'bool in [False]'
        self.collection_wrap.query(term_expr, output_fields=[ct.default_float_field_name])
```

#### Expected result:
Query successfully

#### Actual results:
```
[2021-09-07 10:26:09,913 - DEBUG - ci_test]: (api_request)  : [Collection.construct_from_dataframe] args: ['query_OVZLmjuY',       int64   float                                       float_vector   bool
0         0     0.0  [0.13063222798087235, 0.132159401265968, 0.115...  False
1         1     1.0  [0.1237362641596877, 0.13604608109059618, 0.01...   True
2         2     2.0  [0.014309008209642817, 0.0......, kwargs: {'primary_field': 'int64'} (api_request.py:44)
[2021-09-07 10:26:10,292 - DEBUG - ci_test]: (api_response) : ({"name": "query_OVZLmjuY", "schema": {"auto_id": false, "description": "", "fields": [{"name": "int64", "description": "", "type": 5, "is_primary": true, "auto_id": false}, {"name": "float", "description": "", "type": 10}, {"name": "float_vector", "description": "", "type": 101, "params": {"dim": 1......  (api_request.py:21)
[2021-09-07 10:26:13,409 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None], kwargs: {'timeout': 20} (api_request.py:44)
[2021-09-07 10:26:13,950 - DEBUG - ci_test]: (api_response) : None  (api_request.py:21)
[2021-09-07 10:26:13,951 - DEBUG - ci_test]: (api_request)  : [Collection.query] args: ['bool in [False]', ['float'], None, 20], kwargs: {} (api_request.py:44)
[2021-09-07 10:26:13,961 - ERROR - ci_test]: Traceback (most recent call last):
  File "/home/zong/zong/projects/milvus/tests/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/home/zong/zong/projects/milvus/tests/python_client/utils/api_request.py", line 45, in api_request
    return func(*arg, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/orm/pymilvus_orm/collection.py", line 729, in query
    res = conn.query(self._name, expr, output_fields, partition_names, timeout)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 68, in handler
    raise e
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 52, in handler
    return func(self, *args, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 1215, in query
    return handler.query(collection_name, expr, output_fields, partition_names, timeout=timeout)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    raise e
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 59, in handler
    return func(self, *args, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 1129, in query
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=unsupported leaf node)>
 (api_request.py:26)
```

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):
   86afde4   Mon Sep  6 03:56:05 UTC 2021
- Deployment mode(standalone or cluster):
   cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
   pymilvus              2.0.0rc6.dev4
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by ThreadDao** [comment]
No fix.
```
Version:   80ae6b7
Built:     Tue Sep 14 10:46:03 UTC 2021
```
```
2021-09-14 18:58:32,304 - DEBUG - ci_test]: (api_request)  : [Collection.query] args: ['bool in [True]', ['bool'], None, 20], kwargs: {} (api_request.py:44)
[2021-09-14 18:58:32,317 - ERROR - ci_test]: Traceback (most recent call last):
  File "/home/zong/zong/projects/milvus/tests/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/home/zong/zong/projects/milvus/tests/python_client/utils/api_request.py", line 45, in api_request
    return func(*arg, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/orm/pymilvus_orm/collection.py", line 729, in query
    res = conn.query(self._name, expr, output_fields, partition_names, timeout)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 60, in handler
    raise e
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 44, in handler
    return func(self, *args, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 1179, in query
    return handler.query(collection_name, expr, output_fields, partition_names, timeout=timeout)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    raise e
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 59, in handler
    return func(self, *args, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 1129, in query
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=unsupported leaf node)>
 (api_request.py:26)
[2021-09-14 18:58:32,318 - ERROR - ci_test]: (api_response) : <BaseException: (code=1, message=unsupported leaf node)> (api_request.py:27)
```

**Comment by xiaofan-luan** [comment]
We will support in expression and compare bool with number in later version, so far the priority is to compare bool with TRUE/FALSE

**Comment by ThreadDao** [comment]
support

1.  id in [true / false]
2. id == true/ false
3. id == True / False

not support:

1. id in [True / False]
2. id == 0 / 1 / 2
