### ISSUE TITLE
Milvus crashed with fatal error throwing panic

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#7562]
#### Steps/Code to reproduce:
Run nightly test cases: [standalone]
https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/131/

Logs:
artifacts-milvus-standalone-master-131-e2e-nightly-logs:

0.log

#### Expected result:
No panic

#### Actual results:
```
2021-09-07T15:33:33.811301883Z stdout F [2021/09/07 15:33:33.811 +00:00] [DEBUG] [query_collection.go:445] ["doing search in doUnsolvedMsg..."] [collectionID=427564356902060033] [msgID=427564341422501284]
2021-09-07T15:33:33.811319419Z stderr F fatal error: unexpected signal during runtime execution
2021-09-07T15:33:33.814436593Z stderr F [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x7fd0d9bb6fc2]
2021-09-07T15:33:33.814441982Z stderr F
2021-09-07T15:33:33.814444893Z stderr F runtime stack:
2021-09-07T15:33:33.819281086Z stderr F runtime.throw(0x2553bfd, 0x2a)
2021-09-07T15:33:33.819292395Z stderr F         /usr/local/go/src/runtime/panic.go:1116 +0x72
2021-09-07T15:33:33.819298205Z stderr F runtime.sigpanic()
2021-09-07T15:33:33.819310497Z stderr F         /usr/local/go/src/runtime/signal_unix.go:704 +0x4ac
2021-09-07T15:33:33.819315624Z stderr F
2021-09-07T15:33:33.819318256Z stderr F goroutine 6662066 [syscall]:
2021-09-07T15:33:33.819320619Z stderr F runtime.cgocall(0x16e5a7a, 0xc00b7f5130, 0xc007c837e0)
2021-09-07T15:33:33.81932295Z stderr F  /usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc00b7f5100 sp=0xc00b7f50c8 pc=0x729a5b
2021-09-07T15:33:33.819840463Z stderr F github.com/milvus-io/milvus/internal/querynode._Cfunc_CreateSearchPlanByExpr(0x0, 0xc009b92fc0, 0x31, 0xc007c837e0, 0x0, 0x0)
2021-09-07T15:33:33.819852376Z stderr F         _cgo_gotypes.go:261 +0x56 fp=0xc00b7f5130 sp=0xc00b7f5100 pc=0x16bad96
2021-09-07T15:33:33.819861967Z stderr F github.com/milvus-io/milvus/internal/querynode.createSearchPlanByExpr.func1(0xc006964510, 0xc009b92fc0, 0x31, 0x40, 0xc007c837e0, 0x7fcdb2, 0xc0069643f0)
2021-09-07T15:33:33.81987107Z stderr F  /go/src/github.com/milvus-io/milvus/internal/querynode/plan.go:49 +0xb7 fp=0xc00b7f5178 sp=0xc00b7f5130 pc=0x16d10b7
2021-09-07T15:33:33.819889217Z stderr F github.com/milvus-io/milvus/internal/querynode.createSearchPlanByExpr(0xc006964510, 0xc009b92fc0, 0x31, 0x40, 0x0, 0x0, 0x273c740)
2021-09-07T15:33:33.819903727Z stderr F         /go/src/github.com/milvus-io/milvus/internal/querynode/plan.go:49 +0x6c fp=0xc00b7f51d8 sp=0xc00b7f5178 pc=0x16c54ec
2021-09-07T15:33:33.819915593Z stderr F github.com/milvus-io/milvus/internal/querynode.(*queryCollection).search(0xc005dfb7a0, 0x273d480, 0xc00164cb40, 0x0, 0x0)
2021-09-07T15:33:33.819927121Z stderr F         /go/src/github.com/milvus-io/milvus/internal/querynode/query_collection.go:778 +0x1c9 fp=0xc00b7f5a20 sp=0xc00b7f51d8 pc=0x16a6789
2021-09-07T15:33:33.819930106Z stderr F github.com/milvus-io/milvus/internal/querynode.(*queryCollection).doUnsolvedQueryMsg(0xc005dfb7a0)
2021-09-07T15:33:33.81993705Z stderr F  /go/src/github.com/milvus-io/milvus/internal/querynode/query_collection.go:453 +0xce5 fp=0xc00b7f5fd8 sp=0xc00b7f5a20 pc=0x16a2585
2021-09-07T15:33:33.81994334Z stderr F runtime.goexit()
2021-09-07T15:33:33.819950166Z stderr F         /usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00b7f5fe0 sp=0xc00b7f5fd8 pc=0x796801
2021-09-07T15:33:33.81995449Z stderr F created by github.com/milvus-io/milvus/internal/querynode.(*queryCollection).start
2021-09-07T15:33:33.819962565Z stderr F         /go/src/github.com/milvus-io/milvus/internal/querynode/query_collection.go:124 +0xc7
2021-09-07T15:33:33.819965089Z stderr F
2021-09-07T15:33:33.819970534Z stderr F goroutine 1 [chan receive, 35 minutes]:
2021-09-07T15:33:33.819991157Z stderr F github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run(0xc0009f7eff, 0x1, 0x0, 0x0)
2021-09-07T15:33:33.819998382Z stderr F         /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:428 +0x2bc
2021-09-07T15:33:33.820009676Z stderr F main.main()
2021-09-07T15:33:33.820016183Z stderr F         /go/src/github.com/milvus-io/milvus/cmd/main.go:283 +0x649
2021-09-07T15:33:33.820024325Z stderr F
2021-09-07T15:33:33.820030169Z stderr F goroutine 143 [select]:
2021-09-07T15:33:33.820039218Z stderr F github.com/milvus-io/milvus/internal/util/rocksmq/server/rocksmq.(*retentionInfo).retention(0xc0000e2bb0, 0xc00042c120, 0xc00070c040)
2021-09-07T15:33:33.820044292Z stderr F         /go/src/github.com/milvus-io/milvus/internal/util/rocksmq/server/rocksmq/rocksmq_retention.go:254 +0x1fb
2021-09-07T15:33:33.82005283Z stderr F created by github.com/milvus-io/milvus/internal/util/rocksmq/server/rocksmq.(*retentionInfo).startRetentionInfo
2021-09-07T15:33:33.820057328Z stderr F         /go/src/github.com/milvus-io/milvus/internal/util/rocksmq/server/rocksmq/rocksmq_retention.go:121 +0x11e
```

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): 76f5264
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
2.0.0rc6.dev3
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by czs007** [comment]
@bigsheeper  is working on it . Add logic to avoid crashes, instead return errors.
