### ISSUE TITLE
Ut action panic for timeout in rootcoord

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#7602]
#### Steps/Code to reproduce:
https://github.com/milvus-io/milvus/pull/7589/checks?check_run_id=3543036456

row-log
https://pipelines.actions.githubusercontent.com/c6NryAz2qaRK4LQlCYQ0LjvW1gQAYdd7KMx8DEnmMHb4LaBm12/_apis/pipelines/1/runs/16469/signedlogcontent/3?urlExpires=2021-09-08T10%3A24%3A58.2541436Z&urlSigningMethod=HMACV1&urlSignature=ESO424bf7bZPrTmXPL2Gj3f%2F14owRNYVLpANME5e%2FNo%3D

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by congqixia** [comment]
raw log uri expired. Re-run ut will expire the link

**Comment by XuanYang-cn** [comment]
[logs_16469.zip](https://github.com/milvus-io/milvus/files/7128217/logs_16469.zip)

**Comment by XuanYang-cn** [comment]
https://github.com/milvus-io/milvus/pull/7615/checks?check_run_id=3552100677 again 
[Uploading logs_16527.zip…]()

**Comment by congqixia** [comment]
FYI, found the case which hang:
```
goroutine 3770 [chan receive]:
github.com/apache/pulsar-client-go/pulsar.(*producer).internalCreatePartitionsProducers(0xc001fc7c20, 0x0, 0x0)
	/go/pkg/mod/github.com/apache/pulsar-client-go@v0.5.0/pulsar/producer_impl.go:216 +0x650
github.com/apache/pulsar-client-go/pulsar.newProducer(0xc0004b8480, 0xc0016aa840, 0x7fbd3c9fd3f0, 0xc0032c4f20, 0x24)
	/go/pkg/mod/github.com/apache/pulsar-client-go@v0.5.0/pulsar/producer_impl.go:123 +0x565
github.com/apache/pulsar-client-go/pulsar.(*client).CreateProducer(0xc0004b8480, 0xc0043e7cb0, 0x2a, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/apache/pulsar-client-go@v0.5.0/pulsar/client_impl.go:153 +0xa6
github.com/milvus-io/milvus/internal/util/mqclient.(*pulsarClient).CreateProducer(0xc000048410, 0xc0043e7cb0, 0x2a, 0x7fbd04e5db88, 0x4, 0xc001c658d0, 0x10)
	/go/src/github.com/milvus-io/milvus/internal/util/mqclient/pulsar_client.go:45 +0x155
github.com/milvus-io/milvus/internal/msgstream.(*mqMsgStream).AsProducer.func1(0x0, 0x0)
	/go/src/github.com/milvus-io/milvus/internal/msgstream/mq_msgstream.go:90 +0x103
github.com/milvus-io/milvus/internal/util/retry.Do(0x23e4ec0, 0xc000042070, 0xc0032c54c0, 0xc0032c54b0, 0x2, 0x2, 0xc000e31790, 0x7fbd3c980d30)
	/go/src/github.com/milvus-io/milvus/internal/util/retry/retry.go:31 +0x583
github.com/milvus-io/milvus/internal/msgstream.(*mqMsgStream).AsProducer(0xc0030e6420, 0xc000e31790, 0x1, 0x1)
	/go/src/github.com/milvus-io/milvus/internal/msgstream/mq_msgstream.go:104 +0x210
github.com/milvus-io/milvus/internal/rootcoord.newDmlChannels(0xc001cb7b80, 0xc0000b6b40, 0x26, 0x100, 0xc000ccaf48)
	/go/src/github.com/milvus-io/milvus/internal/rootcoord/dml_channels.go:52 +0x1c4
github.com/milvus-io/milvus/internal/rootcoord.(*Core).Init.func1()
	/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:928 +0xa33
sync.(*Once).doSlow(0xc001cb7c80, 0xc0032c5b60)
	/usr/local/go/src/sync/once.go:66 +0x10a
sync.(*Once).Do(0xc001cb7c80, 0xc0032c5b60)
	/usr/local/go/src/sync/once.go:57 +0x69
github.com/milvus-io/milvus/internal/rootcoord.(*Core).Init(0xc001cb7b80, 0xc000b29e00, 0x0)
	/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:860 +0xb7
github.com/milvus-io/milvus/internal/rootcoord.TestRootCoord_CheckZeroShardsNum(0xc000b29e00)
	/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord_test.go:2369 +0xb13
testing.tRunner(0xc000b29e00, 0x2179ef8)
	/usr/local/go/src/testing/testing.go:1127 +0x203
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1178 +0x797
```
Looks like producer creation blocked

**Comment by czs007** [comment]
@czs007  is working on it
