### ISSUE TITLE
Upgrade from rc5-hotfix1 to master-latest failed

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#7603]
#### Steps/Code to reproduce:
* deploy milvus `v2.0.0-rc5-hotfix1` by `docker-compose up -d`
* insert data
* uninstall milvus by `docker-compose down` but keep volumes dir
* deploy milvus `master-20210908-50c677f` by `docker-compose up -d`

#### Expected result:
deploy sucess

#### Actual results:
containers like`milvus-standalone` exited 
```
[2021/09/08 11:16:11.422 +00:00] [DEBUG] [dml_channels.go:55] ["init dml channels"] [num=256]
[2021/09/08 11:16:11.422 +00:00] [ERROR] [dml_channels.go:101] ["invalid channel name"] [chanName=IVF_FLAT_427582950415007745_0] [stack="github.com/milvus-io/milvus/internal/rootcoord.(*dmlChannels).AddProducerChannels\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/dml_channels.go:101\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).Init.func1\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:932\nsync.(*Once).doSlow\n\t/usr/local/go/src/sync/once.go:66\nsync.(*Once).Do\n\t/usr/local/go/src/sync/once.go:57\ngithub.com/milvus-io/milvus/internal/rootcoord.(*Core).Init\n\t/go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:860\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:182\ngithub.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:107\ngithub.com/milvus-io/milvus/cmd/components.(*RootCoord).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/root_coord.go:45\ngithub.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runRootCoord.func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:99"]
panic: invalid channel name

goroutine 74 [running]:
github.com/milvus-io/milvus/internal/rootcoord.(*dmlChannels).AddProducerChannels(0xc000650f80, 0xc0000ad800, 0x16, 0x20)
        /go/src/github.com/milvus-io/milvus/internal/rootcoord/dml_channels.go:102 +0x605
github.com/milvus-io/milvus/internal/rootcoord.(*Core).Init.func1()
        /go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:932 +0x62c
sync.(*Once).doSlow(0xc00015e100, 0xc000669ce8)
        /usr/local/go/src/sync/once.go:66 +0xec
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:57
github.com/milvus-io/milvus/internal/rootcoord.(*Core).Init(0xc00015e000, 0x273fc20, 0xc00023fd10)
        /go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:860 +0x41e
github.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).init(0xc0002b2140, 0x100000000, 0xc0004fa5c8)
        /go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:182 +0x336
github.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).Run(0xc0002b2140, 0xffffffffffffffff, 0x2728740)
        /go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:107 +0x2f
github.com/milvus-io/milvus/cmd/components.(*RootCoord).Run(...)
        /go/src/github.com/milvus-io/milvus/cmd/components/root_coord.go:45
github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runRootCoord.func1(0x2597001, 0x2727e40, 0xc0000b5480, 0xc00041d590, 0xc0004fa5c0)
        /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:99 +0xdc
created by github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).runRootCoord
        /go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:84 +0xb0
```

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): rc5-hotfix1 --> 50c677f
- Deployment mode(standalone or cluster): both standalone and cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.0.0rc5
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others: 

#### Additional context:

[cluster-upgrade-2021-09-08-10-08-15.log](https://github.com/milvus-io/milvus/files/7128282/cluster-upgrade-2021-09-08-10-08-15.log)
[standalone-upgrade-2021-09-08-10-07-33.log](https://github.com/milvus-io/milvus/files/7128284/standalone-upgrade-2021-09-08-10-07-33.log)

**Comment by cydrain** [comment]
The panic is expected, it's introduced by PR #7323.
Before rc6, rootcoord creates random physical channels for each collection.
Since rc6, rootcoord applies for physical channels from msgstream pool.
This panic is because rc6 cannot recognize the physical names created by rc5-hotfix1.

**Comment by yanliang567** [comment]
@xiaofan-luan it sounds that data in rc5 would NOT be available after upgraded to rc6. any ideas?

/assign @xiaofan-luan

**Comment by cydrain** [comment]
This fix is only to let rc6 compatible with rc5.
After rc6 release, will revert this code change.
