### ISSUE TITLE
Calling loading_progress with invalid partition names did not throw exceptions

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#7613]
#### Steps/Code to reproduce:
```
@pytest.fixture(scope="function", params=ct.get_invalid_strs)
    def get_invalid_partition_names(self, request):
        if isinstance(request.param, list):
            if len(request.param) == 0:
                pytest.skip("empty is valid for partition")
        if request.param is None:
            pytest.skip("None is valid for partition")
        yield request.param
```
```
    def test_loading_progress_invalid_partition_names(self, get_invalid_partition_names):
        """
        target: test loading progress with invalid partition names
        method: input invalid partition names
        expected: raise an exception
        """
        collection_w = self.init_collection_general(prefix)[0]
        partition_names = get_invalid_partition_names
        err_msg = {ct.err_code: 0, ct.err_msg: "`partition_name_array` value {} is illegal".format(partition_names)}
        collection_w.load()
        self.utility_wrap.loading_progress(collection_w.name, partition_names,
                                           check_task=CheckTasks.err_res, check_items=err_msg)
```

#### Expected result:
Raise an exception

#### Actual results:
partition_names=1
```
[2021-09-09 11:20:40,962 - DEBUG - ci_test]: (api_request)  : [loading_progress] args: ['utility_gMc28zjz', 1, 'default'], kwargs: {} (api_request.py:44)
[2021-09-09 11:20:40,963 - ERROR - ci_test]: Traceback (most recent call last):
  File "/home/zong/zong/projects/milvus/tests/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/home/zong/zong/projects/milvus/tests/python_client/utils/api_request.py", line 45, in api_request
    return func(*arg, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/orm/pymilvus_orm/utility.py", line 59, in loading_progress
    if not partition_names or len(partition_names) == 0:
TypeError: object of type 'int' has no len()
 (api_request.py:26)
```
partition_names=[1, "2",3]
```
[2021-09-09 11:20:43,755 - DEBUG - ci_test]: (api_request)  : [loading_progress] args: ['utility_EOg1PCpN', [1, '2', 3], 'default'], kwargs: {} (api_request.py:44)
[2021-09-09 11:20:43,791 - DEBUG - ci_test]: (api_response) : {'num_loaded_entities': 0, 'num_total_entities': 0}  (api_request.py:21)
```
partition_names=""
```
[2021-09-09 11:20:53,945 - DEBUG - ci_test]: (api_request)  : [loading_progress] args: ['utility_sAAcQFI5', '', 'default'], kwargs: {} (api_request.py:44)
[2021-09-09 11:20:53,978 - DEBUG - ci_test]: (api_response) : {'num_loaded_entities': 0, 'num_total_entities': 0}  (api_request.py:21)
```

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):
   3c2821e
   Built:     Wed Sep  8 13:52:17 UTC 2021
- Deployment mode(standalone or cluster):
  cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
   pymilvus              2.0.0rc6.dev11
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by yanliang567** [comment]
functional issue, set to higher priority

**Comment by yhmo** [comment]
The bug has been fix in pymilvus, please use the latest pymilvus to verify.
Once any partition name doesn't exist, the loading_progress() api will throw an exception: "partitionID of partitionName:xxx can not be found"

**Comment by yanliang567** [comment]
@ThreadDao please help to verify it
