### ISSUE TITLE
[benchmark] [standalone] syncTimestamp Failed:Connect to rootcoord failed 

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#7618]
#### Steps/Code to reproduce:
【**Occasionally**】
test yaml：
client-configmap: client-get-local50m-512
server-configmap: server-single-16c64m

argo task：benchmark-cluster-cron-1631131200

#### Actual results:

server deploy：
```
NAME: benchmark-cluster-cron-1631131200-1
LAST DEPLOYED: Wed Sep  8 20:00:25 2021
NAMESPACE: qa-milvus
STATUS: deployed
REVISION: 1
TEST SUITE: None
I0908 20:01:34.049342      28 request.go:665] Waited for 1.133830586s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.l
ocal/apis/monitoring.kiali.io/v1alpha1?timeout=32s
I0908 20:01:44.249206      28 request.go:665] Waited for 11.333544397s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.
local/apis/rbac.authorization.k8s.io/v1beta1?timeout=32s
NAME                                                              READY   STATUS    RESTARTS   AGE
benchmark-cluster-cron-1631131200-1-etcd-0                        1/1     Running   0          79s
benchmark-cluster-cron-1631131200-1-milvus-standalone-58f964wnn   1/1     Running   0          79s
```

client log：
```
[2021-09-08 22:45:58,563] [   DEBUG] - {'flush_time': 3.67} (milvus_benchmark.runners.get:118)
[2021-09-08 22:45:58,563] [   DEBUG] - Start load collection (milvus_benchmark.runners.get:119)
[2021-09-09 02:02:19,592] [   ERROR] - Error: <BaseException: (code=1, message=syncTimestamp Failed:Connect to rootcoord failed with error:
context canceled)> (pymilvus.client.grpc_handler:61)
[2021-09-09 02:02:19,593] [   ERROR] - Error: <BaseException: (code=1, message=syncTimestamp Failed:Connect to rootcoord failed with error:
context canceled)> (pymilvus.client.grpc_handler:61)
[2021-09-09 02:02:19,594] [   ERROR] - <BaseException: (code=1, message=syncTimestamp Failed:Connect to rootcoord failed with error:
context canceled)> (milvus_benchmark.main:114)
[2021-09-09 02:02:19,597] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 83, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/get.py", line 120, in prepare
    self.milvus.load_collection(timeout=1200)
  File "/src/milvus_benchmark/client.py", line 46, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 440, in load_collection
    return self._milvus.load_collection(collection_name, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 68, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 52, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 343, in load_collection
    return handler.load_collection("", collection_name=collection_name, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 59, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 827, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 59, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 845, in wait_for_loading_collection
    return self._wait_for_loading_collection_v2(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 872, in _wait_for_loading_collection_v2
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=syncTimestamp Failed:Connect to rootcoord failed with error:
context canceled)>
 (milvus_benchmark.main:115)
[2021-09-09 02:02:19,598] [   DEBUG] - {'_version': '0.1', '_type': 'metric', 'run_id': 1631131383, 'mode': 'local', 'server': <milvus_benchmark.metrics.models.server.Server object
at 0x7faeab113208>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware object at 0x7faeab113978>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7faeab113ac
8>, 'status': 'RUN_FAILED', 'err_message': '', 'collection': {'dimension': 512, 'metric_type': 'l2', 'dataset_name': 'local_50m_512_l2', 'collection_size': 50000000, 'other_fields':
 None, 'ni_per': 50000}, 'index': {'index_type': 'ivf_sq8', 'index_param': {'nlist': 1024}}, 'search': None, 'run_params': None, 'metrics': {'type': 'insert_get_performance', 'value
': {}}, 'datetime': '2021-09-08 20:03:03.416257', 'type': 'metric'} (milvus_benchmark.metric.api:29)
```

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): 9e0b2cc
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.0.0rc6.dev4
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by wangting0128** [comment]
#7252

**Comment by yanliang567** [comment]
@wangting0128  does it an OOM, as 512d-50M data size is about 100GB, which is exceeded 16c64m
