### ISSUE TITLE
[benchmark][cluster] GetSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#7619]
#### Steps/Code to reproduce:
【**Occasionally**】
test yaml：
client-configmap: client-search-sift50m-ivf-flat-2048
server-configmap: server-cluster-16c64m

argo task：benchmark-cluster-cron-1631131200

#### Actual results:
server deploy：
```
NAME: benchmark-cron-1631124000-7
LAST DEPLOYED: Wed Sep  8 18:00:27 2021
NAMESPACE: qa-milvus
STATUS: deployed
REVISION: 1
TEST SUITE: None
I0908 18:01:41.326366      28 request.go:665] Waited for 1.126792905s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.l
ocal/apis/serving.knative.dev/v1beta1?timeout=32s
I0908 18:01:51.526139      28 request.go:665] Waited for 11.326424976s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.
local/apis/networking.k8s.io/v1beta1?timeout=32s
NAME                                                             READY   STATUS    RESTARTS   AGE
benchmark-cron-1631124000-7-etcd-0                               1/1     Running   0          84s
benchmark-cron-1631124000-7-milvus-datacoord-65f8b7689b-6bgmk    1/1     Running   0          84s
benchmark-cron-1631124000-7-milvus-datanode-646d458db5-4jcpn     1/1     Running   0          84s
benchmark-cron-1631124000-7-milvus-indexcoord-6d6c69574f-w6mh2   1/1     Running   0          84s
benchmark-cron-1631124000-7-milvus-indexnode-765684fbb4-jl4ft    1/1     Running   0          84s
benchmark-cron-1631124000-7-milvus-proxy-7c845fbb5f-tb8ln        1/1     Running   0          84s
benchmark-cron-1631124000-7-milvus-pulsar-846bf6f986-msmcc       1/1     Running   0          84s
benchmark-cron-1631124000-7-milvus-querycoord-6c55d9df94-c8jns   1/1     Running   0          84s
benchmark-cron-1631124000-7-milvus-querynode-7d7dd99f8-pd87m     1/1     Running   0          84s
benchmark-cron-1631124000-7-milvus-rootcoord-7d5d6f7f44-64z8g    1/1     Running   0          84s

```

client log：
```
[2021-09-08 18:05:04,707] [   DEBUG] - Row count: 1400000 in collection: <sift_50m_128_l2> (milvus_benchmark.client:389)
[2021-09-08 18:05:04,708] [   DEBUG] - 1400000 (milvus_benchmark.runners.base:89)
[2021-09-08 18:05:05,321] [   DEBUG] - Start id: 1500000, end id: 1550000 (milvus_benchmark.runners.base:76)
[2021-09-08 18:05:34,124] [   ERROR] - Error: <BaseException: (code=1, message=GetSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error)> (pymilvus.client.grpc_han
dler:61)
[2021-09-08 18:05:34,125] [   ERROR] - <BaseException: (code=1, message=GetSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error)> (milvus_benchmark.client:154)
[2021-09-08 18:05:34,125] [   DEBUG] - Milvus insert run in 28.8s (milvus_benchmark.client:49)
[2021-09-08 18:05:34,196] [   ERROR] - Error: <BaseException: (code=1, message=syncTimeStamp Failed:state code = Initializing)> (pymilvus.client.grpc_handler:61)
[2021-09-08 18:05:34,197] [   ERROR] - <BaseException: (code=1, message=syncTimeStamp Failed:state code = Initializing)> (milvus_benchmark.main:114)
[2021-09-08 18:05:34,198] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 83, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/search.py", line 248, in prepare
    insert_result = self.insert(self.milvus, collection_name, case_param["data_type"], dimension, case_param["collection_size"], case_param["ni_per"])
  File "/src/milvus_benchmark/runners/base.py", line 129, in insert
    ni_time = self.insert_core(milvus, info, start_id, vectors)
  File "/src/milvus_benchmark/runners/base.py", line 89, in insert_core
    logger.debug(milvus.count())
  File "/src/milvus_benchmark/client.py", line 388, in count
    row_count = self._milvus.get_collection_stats(collection_name)["row_count"]
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 68, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 52, in handler
   return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 393, in get_collection_stats
    stats = handler.get_collection_stats(collection_name, timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 59, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 1030, in get_collection_stats
    raise BaseException(status.error_code, status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=syncTimeStamp Failed:state code = Initializing)>
 (milvus_benchmark.main:115)
[2021-09-08 18:05:34,276] [   DEBUG] - {'_version': '0.1', '_type': 'metric', 'run_id': 1631124191, 'mode': 'local', 'server': <milvus_benchmark.metrics.models.server.Server object
at 0x7fd481f95278>, 'hardware': <milvus_benchmark.metrics.models.hardware.Hardware object at 0x7fd481f95080>, 'env': <milvus_benchmark.metrics.models.env.Env object at 0x7fd481f952e
8>, 'status': 'RUN_FAILED', 'err_message': '', 'collection': {'dimension': 128, 'metric_type': 'l2', 'dataset_name': 'sift_50m_128_l2', 'fields': None}, 'index': {'index_type': 'ivf
_flat', 'index_param': {'nlist': 2048}}, 'search': None, 'run_params': None, 'metrics': {'type': 'insert_search_performance', 'value': {}}, 'datetime': '2021-09-08 18:03:11.761362',
 'type': 'metric'} (milvus_benchmark.metric.api:29)
```

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): v2.0.0-rc5-hotfix1-20210901-9e0b2cc
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.0.0rc6.dev4
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by wangting0128** [comment]
#6236

**Comment by yanliang567** [comment]
/assign @godchen0212 
could you please take a look whether it is related to #6236 and  #6350

**Comment by yanliang567** [comment]
set to urgent as it is blocking stability in insert.

**Comment by sunby** [comment]
@wangting0128 please provide the proxy and datacoord log

**Comment by wangting0128** [comment]
> @wangting0128 please provide the proxy and datacoord log

standalone, You need to find logs on kibana by pod name

**Comment by sunby** [comment]
/unassign 
@godchen0212 is working on it

**Comment by godchen0212** [comment]
The problem is caused by the low rate of fsync observed in prometheus. The fsync time is up to 2.5s.

**Comment by yanliang567** [comment]
not repo on 89358ad, remove urgent from rc6
will close it, if keep not-repo in the next few builds

**Comment by yanliang567** [comment]
@wangting0128 could you please help to close this issue

**Comment by jingkl** [comment]
I'm getting the same error in the Milvus rc7 cluster version
1.When I inserted the 20.5 million data, I got the error as shown in
![21](https://user-images.githubusercontent.com/34296482/137453465-0330d54b-9b1c-4ac0-9066-815fea28bd1b.png)
I insert 100,000 pieces of data at a time

**Comment by yanliang567** [comment]
@godchen0212 could you please help to check this issue again as updated above
