### ISSUE TITLE
No Available Query node result, filter reason Search failed, C runtime error detected

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#7774]
#### Steps/Code to reproduce:
```python
"""
https://github.com/milvus-io/pymilvus/issues/690
1. create, insert, create_index, load
2. search without expr, get a list of ids
3. search with expr f"film_id in {list of ids}"
"""

from pymilvus import Collection, FieldSchema, CollectionSchema, DataType
from data import gen_float_vectors

from functools import wraps
from time import time


COLLECTION_NAME = "_6250"
NUM = 100_000
DIM = 128


def timeit(f):
    @wraps(f)
    def wrap(*args, **kw):
        ts = time()
        result = f(*args, **kw)
        te = time()

        print(f"func:{f.__name__} - [{args}] took: {te-ts:8.4f}s")
        return result
    return wrap


if __name__ == "__main__":
    from pymilvus import connections
    m = connections.connect()
    if m.has_collection(COLLECTION_NAME):
        m.drop_collection(COLLECTION_NAME)

    schema = CollectionSchema(
        fields=[
            FieldSchema("film_id", DataType.INT64, is_primary=True, auto_id=True),
            FieldSchema("films", dtype=DataType.FLOAT_VECTOR, dim=128)
        ],
    )
    connections.connect()
    print(f"Create Collection {COLLECTION_NAME}")
    films = Collection(COLLECTION_NAME, schema=schema)

    print(f"Generate eneities")
    ve = gen_float_vectors(NUM, DIM)
    print(f"Num {len(ve)}, DIM {len(ve[0])}")

    films.insert([ve])
    print(f"insert ve")

    index_params = {
        "index_type": "IVF_FLAT",
        "metric_type": "L2",
        "params": {"nlist": 100}
    }

    status = films.create_index("films", index_params)
    print(f"index films")

    films.load()
    print(f"load films")

    search_param = {
        "data": [ve[0]],
        "anns_field": "films",
        "param": {"metric_type": "L2", "nprobe": 1},
        "limit": 10,
    }

    filter_lists = films.search(**search_param)[0].ids
    print(f"search 1")
    ans = films.search(**search_param, expr=f"film_id in {filter_lists}")[0].ids

    print(f"search 2")

    print(f"Expected both true")
    print(len(ans) == len(filter_lists))

    print(ans == filter_lists)
```

#### Actual results:
```
Error: <BaseException: (code=1, message=No Available Query node result, filter reason Search failed, C runtime error detected, error code = 1, error msg = 
: id 427688106875258547)>
Error: <BaseException: (code=1, message=No Available Query node result, filter reason Search failed, C runtime error detected, error code = 1, error msg = 
: id 427688106875258547)>

```

```
[2021/09/13 10:37:47.627 +08:00] [DEBUG] [query_collection.go:352] ["doing query in receiveQueryMsg..."] [collectionID=427688107215945729] [msgID=427688106875258547] [msgType=search]
[2021/09/13 10:37:47.627 +08:00] [DEBUG] [historical.go:243] ["no partition specified, search all partitions"] [collectionID=427688107215945729] ["all partitions"="[427688107215945730]"]
[2021/09/13 10:37:47.628 +08:00] [DEBUG] [historical.go:279] ["doing search in historical"] [collectionID=427688107215945729] [reqPartitionIDs="[]"] [searchPartitionIDs="[427688107215945730]"]
[2021/09/13 10:37:47.628 +08:00] [DEBUG] [segment.go:295] ["do search on segment"] [segmentID=427688109286883330] [segmentType=3]
Assert "(adapter->CheckSearch(conf, index_type, field_indexing->indexing_->index_mode()))" at /home/yangxuan/Github/milvus/internal/core/src/query/SearchOnSealed.cpp:88

[2021/09/13 10:37:47.628 +08:00] [WARN] [query_collection.go:831] ["Search failed, C runtime error detected, error code = 1, error msg = "]
[2021/09/13 10:37:47.628 +08:00] [DEBUG] [time_recorder.go:62] ["receiveQueryMsg 427688106875258547: operation done (0ms)"]
[2021/09/13 10:37:47.631 +08:00] [DEBUG] [query_collection.go:374] ["do query failed in receiveQueryMsg, publish failed query result"] [collectionID=427688107215945729] [msgID=427688106875258547] [msgType=search]
[2021/09/13 10:37:47.631 +08:00] [WARN] [query_collection.go:238] ["Search failed, C runtime error detected, error code = 1, error msg = "]

```

#### Environment:
- Milvus version: 759abd450ad3b76f6ffd723496b46532a3003d2b
- Deployment mode(standalone or cluster): cluster
- SDK: pymilvus 2.0.0rc6
- OS(Ubuntu or CentOS):  Ubuntu
- CPU/Memory: 
- GPU: 
- Others:

**Comment by xiaofan-luan** [comment]
Search failed, C runtime error detected, error code = 1, error msg = "" , this log looks weird, no error message shown up

**Comment by XuanYang-cn** [comment]
`: id 427688106875258547)` this is the error message, yet still very weird

**Comment by shanghaikid** [comment]
Same issue here
```
[2021/09/13 03:38:28.513 +00:00] [DEBUG] [segment.go:182] ["Proxy SegIDAssigner pickCanDoFunc"] [len(ToDoReqs)=0]
[2021/09/13 03:38:28.528 +00:00] [DEBUG] [impl.go:395] ["DescribeCollection enqueue"] [role=Proxy-] [db=] [collection=car_search2]
[2021/09/13 03:38:28.530 +00:00] [DEBUG] [id.go:133] ["IDAllocator pickCanDoFunc"] [need=1] [total=49822] [remainReqCnt=0]
[2021/09/13 03:38:28.530 +00:00] [DEBUG] [impl.go:409] [DescribeCollection] [role=Proxy-] [msgID=427688627258411683] [timestamp=427689065445851138] [db=] [collection=car_search2]
[2021/09/13 03:38:28.532 +00:00] [DEBUG] [root_coord.go:1277] [DescribeCollection] [name=car_search2] [msgID=427688627258411683]
[2021/09/13 03:38:28.532 +00:00] [DEBUG] [root_coord.go:1297] ["DescribeCollection Success"] [name=car_search2] [msgID=427688627258411683]
[2021/09/13 03:38:28.533 +00:00] [DEBUG] [impl.go:416] ["DescribeCollection Done"] [] [role=Proxy-] [msgID=427688627258411683] [timestamp=427689065445851138] [db=] [collection=car_search2]
[2021/09/13 03:38:28.536 +00:00] [DEBUG] [impl.go:1439] ["Search enqueue"] [role=Proxy-] [db=] [collection=car_search2] [partitions="[]"] [dsl=] [len(PlaceholderGroup)=524] [OutputFields="[id,brand,color]"]
[2021/09/13 03:38:28.537 +00:00] [DEBUG] [id.go:133] ["IDAllocator pickCanDoFunc"] [need=1] [total=49821] [remainReqCnt=0]
[2021/09/13 03:38:28.538 +00:00] [DEBUG] [impl.go:1457] [Search] [role=Proxy-] [msgID=427688627258411684] [timestamp=427689065445851139] [db=] [collection=car_search2] [partitions="[]"] [dsl=] [len(PlaceholderGroup)=524] [OutputFields="[id,brand,color]"]
[2021/09/13 03:38:28.539 +00:00] [DEBUG] [impl.go:76] ["show collection start"] [dbID=0]
[2021/09/13 03:38:28.539 +00:00] [DEBUG] [impl.go:101] ["show collection end"] [collections="[427688552379973633]"] [inMemoryPercentage="[100]"]
[2021/09/13 03:38:28.540 +00:00] [DEBUG] [task.go:1449] ["query coordinator show collections"] [collID=427688552379973633] [collections="[427688552379973633]"]
[2021/09/13 03:38:28.540 +00:00] [DEBUG] [task.go:1478] ["translate output fields"] [OutputFields="[id,brand,color]"]
[2021/09/13 03:38:28.540 +00:00] [DEBUG] [task.go:1542] [Proxy::SearchTask::PreExecute] [plan.OutputFieldIds="[100,102,103]"] [plan="vector_anns:<field_id:101 query_info:<topk:200 metric_type:\"L2\" search_params:\"{\\\"nprobe\\\":\\\"2\\\"}\" > placeholder_tag:\"$0\" > output_field_ids:100 output_field_ids:102 output_field_ids:103 "]
[2021/09/13 03:38:28.544 +00:00] [DEBUG] [task.go:1638] [proxy] ["length of searchMsg"=1]
[2021/09/13 03:38:28.544 +00:00] [DEBUG] [task.go:1639] ["proxy sent one searchMsg"] [collectionID=427688552379973633] [msgID=427688627258411684]
[2021/09/13 03:38:28.547 +00:00] [DEBUG] [time_recorder.go:62] ["receiveQueryMsg 427688627258411684: get searchable time done (0ms)"]
[2021/09/13 03:38:28.548 +00:00] [DEBUG] [query_collection.go:352] ["doing query in receiveQueryMsg..."] [collectionID=427688552379973633] [msgID=427688627258411684] [msgType=search]
[2021/09/13 03:38:28.548 +00:00] [DEBUG] [historical.go:243] ["no partition specified, search all partitions"] [collectionID=427688552379973633] ["all partitions"="[427688552379973634]"]
[2021/09/13 03:38:28.548 +00:00] [DEBUG] [historical.go:279] ["doing search in historical"] [collectionID=427688552379973633] [reqPartitionIDs="[]"] [searchPartitionIDs="[427688552379973634]"]
[2021/09/13 03:38:28.548 +00:00] [DEBUG] [segment.go:295] ["do search on segment"] [segmentID=427688559723151361] [segmentType=3]
Assert "(adapter->CheckSearch(conf, index_type, field_indexing->indexing_->index_mode()))" at /go/src/github.com/milvus-io/milvus/internal/core/src/query/SearchOnSealed.cpp:88

[2021/09/13 03:38:28.548 +00:00] [WARN] [query_collection.go:831] ["Search failed, C runtime error detected, error code = 1, error msg = "]
[2021/09/13 03:38:28.548 +00:00] [DEBUG] [time_recorder.go:62] ["receiveQueryMsg 427688627258411684: operation done (0ms)"]
[2021/09/13 03:38:28.553 +00:00] [DEBUG] [query_collection.go:374] ["do query failed in receiveQueryMsg, publish failed query result"] [collectionID=427688552379973633] [msgID=427688627258411684] [msgType=search]
[2021/09/13 03:38:28.553 +00:00] [WARN] [query_collection.go:238] ["Search failed, C runtime error detected, error code = 1, error msg = "]
[2021/09/13 03:38:28.555 +00:00] [DEBUG] [task_scheduler.go:679] ["Proxy collectResultLoop Got a SearchResultMsg"] [ReqID=427688627258411684]
[2021/09/13 03:38:28.555 +00:00] [DEBUG] [task_scheduler.go:699] ["Proxy collectResultLoop, first receive"] [reqID=427688627258411684] [vchans="[car_search2_427688552379973633_1_v1,car_search2_427688552379973633_0_v0]"] []
[2021/09/13 03:38:28.555 +00:00] [DEBUG] [task_scheduler.go:709] ["Proxy collectResultLoop, first receive"] [reqID=427688627258411684] [pchans="[car_search2_427688552379973633_1,car_search2_427688552379973633_0]"] []
[2021/09/13 03:38:28.555 +00:00] [DEBUG] [task_scheduler.go:722] ["Proxy collectResultLoop"] ["collection name"=car_search2] [reqID=427688627258411684] ["answer cnt"=1]
[2021/09/13 03:38:28.555 +00:00] [DEBUG] [task_scheduler.go:560] ["Proxy searchResultBuf readyToReduce"] [haveError=true]
[2021/09/13 03:38:28.555 +00:00] [DEBUG] [task_scheduler.go:726] ["Proxy collectResultLoop readyToReduce and assign to reduce"]
[2021/09/13 03:38:28.555 +00:00] [DEBUG] [task.go:1956] ["Proxy Search PostExecute stage1"] [availableQueryNodeNum=0]
[2021/09/13 03:38:28.555 +00:00] [DEBUG] [task.go:1958] ["Proxy Search PostExecute failed"] [filterReason="Search failed, C runtime error detected, error code = 1, error msg = \n"]
[2021/09/13 03:38:28.555 +00:00] [DEBUG] [task.go:1934] [WaitAndPostExecute] ["time cost"=11.3379ms]
[2021/09/13 03:38:28.555 +00:00] [DEBUG] [impl.go:1482] ["Search Finished"] [error="Search failed, C runtime error detected, error code = 1, error msg = \n"] [role=Proxy-] [msgID=427688627258411684] [timestamp=427689065445851139] [db=] [collection=car_search2] [partitions="[]"] [dsl=] [len(PlaceholderGroup)=524]
[2021/09/13 03:38:28.555 +00:00] [DEBUG] [impl.go:1468] ["Search Done"] [error="Search failed, C runtime error detected, error code = 1, error msg = \n"] [role=Proxy-] [msgID=427688627258411684] [timestamp=427689065445851139] [db=] [collection=car_search2] [partitions="[]"] [dsl=] [len(PlaceholderGroup)=524] [OutputFields="[id,brand,color]"]
[2021/09/13 03:38:29.267 +00:00] [DEBUG] [session_util.go:261] ["SessionUtil GetSessions"] [prefix=IndexNode] [resp="{\"header\":{\"cluster_id\":14841639068965178418,\"member_id\":10276657743932975437,\"revision\":2772,\"raft_term\":2},\"kvs\":[{\"key\":\"YnktZGV2L21ldGEvc2Vzc2lvbi9JbmRleE5vZGUtNQ==\",\"create_revision\":12,\"mod_revision\":12,\"version\":1,\"value\":\"eyJTZXJ2ZXJJRCI6NSwiU2VydmVyTmFtZSI6IkluZGV4Tm9kZSIsIkFkZHJlc3MiOiIxNzIuMTguMC40OjIxMTIxIn0=\",\"lease\":7587857136789869608}],\"count\":1}"]
[2021/09/13 03:38:29.267 +00:00] [DEBUG] [index_coord.go:715] ["IndexCoord assignTaskLoop"] ["Available IndexNode IDs"="[5]"]
[2021/09/13 03:38:29.267 +00:00] [DEBUG] [index_coord.go:720] ["IndexCoord assignTaskLoop"] ["Unassigned tasks number"=0] ["Unassigned tasks meta"=null]
```

**Comment by bigsheeper** [comment]
Segcore has two assertion functions named `Assert(expr)` and `AssertInfo(expr, info)` (core/src/exceptions/EasyAssert.h:55). If segcore uses `Assert` to check and failure is detected, no message would be returned to SDK(or even querynode). @xiaofan-luan @XuanYang-cn 

I think we should use `AssertInfo` instead of `Assert` in any place of segcore. @fishpenguin

**Comment by XuanYang-cn** [comment]
A similar error occurs when building `IVF_PQ` without parsing `m`.

```
   54     index_params = {                                                                                          
   55         "index_type": "IVF_PQ",                                                                               
   56         "metric_type": "L2",                                                                                  
   57         "params": {"nlist": 100}                                                                              
   58     } 
```

```
Error: <BaseException: (code=1, message=BuildFloatVecIndexWithoutIds failed, C runtime error detected, error code = 1, err msg = [json.exception.type_error.302] type must be number, but is null)>
Traceback (most recent call last):
  File "issue_pymilvus#690.py", line 60, in <module>
    status = films.create_index("films", index_params)
  File "/home/yangxuan/.virtualenvs/pymilvus-orm/lib/python3.7/site-packages/pymilvus/orm/pymilvus_orm/collection.py", line 992, in create_index
    timeout=timeout, **kwargs)
  File "/home/yangxuan/.virtualenvs/pymilvus-orm/lib/python3.7/site-packages/pymilvus/client/stub.py", line 60, in handler
    raise e
  File "/home/yangxuan/.virtualenvs/pymilvus-orm/lib/python3.7/site-packages/pymilvus/client/stub.py", line 44, in handler
    return func(self, *args, **kwargs)
  File "/home/yangxuan/.virtualenvs/pymilvus-orm/lib/python3.7/site-packages/pymilvus/client/stub.py", line 739, in create_index
    return handler.create_index(collection_name, field_name, params, timeout, **kwargs)
  File "/home/yangxuan/.virtualenvs/pymilvus-orm/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    raise e
  File "/home/yangxuan/.virtualenvs/pymilvus-orm/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 59, in handler
    return func(self, *args, **kwargs)
  File "/home/yangxuan/.virtualenvs/pymilvus-orm/lib/python3.7/site-packages/pymilvus/client/grpc_handler.py", line 762, in create_index
    raise BaseException(Status.UNEXPECTED_ERROR, fail_reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=BuildFloatVecIndexWithoutIds failed, C runtime error detected, error code = 1, err msg = [json.exception.type_error.302] type must be number, but is null)>

```

**Comment by bigsheeper** [comment]
I'v found the reason, 
```python
    search_param = {
        "data": [ve[0]],
        "anns_field": "films",
        "param": {"metric_type": "L2", "nprobe": 1},
        "limit": 10,
    }
```
should be
```python
    search_param = {
        "data": [ve[0]],
        "anns_field": "films",
        "param": {"metric_type": "L2", "params": {"nprobe": 1}},
        "limit": 10,
    }
```

Search plan doesn't have the param of `nprob`, and query node searched failed at `core/src/query/SearchOnSealed.cpp:88`, where a `Assert` function is called. We cannot get the direct causation from `Assert`. @fishpenguin

**Comment by yanliang567** [comment]
I think this error is caused by the search_params are not matched with the index_params, but the error msg is really confusing to users.

**Comment by yanliang567** [comment]
need verification before close

**Comment by yanliang567** [comment]
on master-20210916-4814f9c with pymilvus-2.0.0rc7.dev4
`index_params = {"index_type": "IVF_SQ8", "params": {"nlist": 64}, "metric_type": "L2"}`
`search_params = {"params": {"nprob": 16}}      `            with a typo nprob**e**

```
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 622, in _execute_search_requests
    raise pre_err
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 613, in _execute_search_requests
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=No Available Query node result, filter reason Search failed, C runtime error detected, error code = 1, error msg =
: id 427759809966419858)>
```

**Comment by zhuwenxing** [comment]
In version `c5bba3e`,  error message is still implicit
```
  search_param = {
      "data": [ve[0]],
      "anns_field": "films",
      "param":{"nprobe": 16},
      "limit": 10,
  }
```

```
Error: <BaseException: (code=1, message=No Available Query node result, filter reason Search failed, C runtime error detected, error code = 1, error msg = [SearchOnSealed]Search params check failed
: id 428549068485134016)>
Error: <BaseException: (code=1, message=No Available Query node result, filter reason Search failed, C runtime error detected, error code = 1, error msg = [SearchOnSealed]Search params check failed
: id 428549068485134016)>
Traceback (most recent call last):
  File "test.py", line 68, in <module>
    filter_lists = films.search(**search_param)[0].ids
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 673, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/stub.py", line 61, in handler
    raise e
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/stub.py", line 45, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/stub.py", line 1070, in search
    return handler.search(collection_name, data, anns_field, param, limit, expression,
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler
    raise e
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 94, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 620, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler
    raise e
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 587, in _execute_search_requests
    raise pre_err
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 578, in _execute_search_requests
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=No Available Query node result, filter reason Search failed, C runtime error detected, error code = 1, error msg = [SearchOnSealed]Search params check failed
: id 428549068485134016)>
```

**Comment by XuanYang-cn** [comment]
@zhuwenxing feel free to reopen this issue if the same error occurs
