### ISSUE TITLE
Connection lost after index created

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#787]
**Describe the bug**
```
19:36:40  DEBUG:milvus_acc.runner:Accuracy: 0.9787
19:36:40  INFO:milvus_acc.client:Building index start, table_name: anngist_1m_1024_960_l2, index_params: {"index_type": 6, "nlist": 16384}
19:46:17  Cannot contact dev-test-dgbg5-48hsf: java.lang.InterruptedException
21:28:39  <_Rendezvous of RPC that terminated with:
21:28:39  	status = StatusCode.UNAVAILABLE
21:28:39  	details = "Connection reset by peer"
21:28:39  	debug_error_string = "{"created":"@1576589311.946488546","description":"Error received from peer ipv4:10.103.103.153:19530","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Connection reset by peer","grpc_status":14}"
21:28:39  >
21:28:39  ERROR:milvus.client.grpc_client:<_Rendezvous of RPC that terminated with:
21:28:39  	status = StatusCode.UNAVAILABLE
21:28:39  	details = "Connection reset by peer"
21:28:39  	debug_error_string = "{"created":"@1576589311.946488546","description":"Error received from peer ipv4:10.103.103.153:19530","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Connection reset by peer","grpc_status":14}"
21:28:39  >
21:28:39  ERROR:milvus_acc.client:Error occurred. Connection reset by peer
21:28:39  Traceback (most recent call last):
21:28:39    File "main.py", line 110, in <module>
21:28:39      main()
21:28:39    File "main.py", line 99, in main
21:28:39      runner.run(milvus_instance, config, hdf5_path, args, server_config)
21:28:39    File "/home/jenkins/agent/workspace/milvus-nightly-ann-accuracy-new/milvu_ann_acc/runner.py", line 146, in run
21:28:39      milvus.create_index(index_type, nlist)
21:28:39    File "/home/jenkins/agent/workspace/milvus-nightly-ann-accuracy-new/milvu_ann_acc/client.py", line 23, in wrapper
21:28:39      result = func(*args, **kwargs)
21:28:39    File "/home/jenkins/agent/workspace/milvus-nightly-ann-accuracy-new/milvu_ann_acc/client.py", line 101, in create_index
21:28:39      self.check_status(status)
21:28:39    File "/home/jenkins/agent/workspace/milvus-nightly-ann-accuracy-new/milvu_ann_acc/client.py", line 52, in check_status
21:28:39      raise Exception("Status not ok")
21:28:39  Exception: Status not ok
```

server is running, and building index have already finished
```
2019-12-17 20:56:14,570 | DEBUG | default | [ENGINE] Update 2 table files
2019-12-17 20:56:14,570 | DEBUG | default | [ENGINE] New index file 1576586202168719000 of size 12886267 bytes from file 1576582249200004000
2019-12-17 20:56:14,570 | DEBUG | default | [SERVER] BuildIndexJob 64 finish index file: 62
2019-12-17 20:56:14,570 | DEBUG | default | [SERVER] BuildIndexJob 64 all done
2019-12-17 20:56:14,570 | DEBUG | default | [ENGINE] Building index job 64 succeed.
2019-12-17 20:56:14,570 | DEBUG | default | [ENGINE] Unmark ongoing file:1576582249200004000 refcount:0
2019-12-17 20:56:14,571 | DEBUG | default | [ENGINE] Background build index thread finished
2019-12-17 20:56:14,576 | DEBUG | default | [SERVER] DoBuildIndex file id:62: totally cost (1172.407685 seconds [1172407.684993 ms])
2019-12-17 20:56:14,597 | DEBUG | default | [SERVER] PickToExecute  (0.000003 second [0.002608 ms])
2019-12-17 20:56:14,597 | DEBUG | default | [SERVER] PickToExecute  (0.000000 second [0.000071 ms])
2019-12-17 20:56:14,597 | DEBUG | default | [SERVER] PickToLoad  (0.000003 second [0.003353 ms])
2019-12-17 20:56:14,598 | DEBUG | default | [SERVER] PickToLoad  (0.000004 second [0.004386 ms])
2019-12-17 20:56:14,598 | DEBUG | default | [SERVER] PickToLoad  (0.000000 second [0.000471 ms])
2019-12-17 20:56:15,417 | DEBUG | default | [SERVER] CreateIndexRequest(table=anngist_1m_1024_960_l2): totally cost (4774.851715 seconds [4774851.715398 ms])
```
no error logs

**Steps/Code to reproduce behavior**

**Expected behavior**

**Environment details**
0.6.0-GPU-version

**Screenshots**

**Additional context**

**Comment by del-zhenwu** [comment]
```
02:08:21  I1223 18:08:19.748364423     718 connectivity_state.cc:117]  ConnectivityStateTracker client_channel[0x3d15280]: add watcher 0x7fcdf4002020
02:08:21  I1223 18:08:19.949065439     240 connectivity_state.cc:140]  ConnectivityStateTracker client_channel[0x3d15280]: remove watcher 0x7fcdf4002020
07:19:55  Cancelling nested steps due to timeout
07:19:55  Sending interrupt signal to process
```

Client got no response from server
```
2019-12-24 02:42:33,608 | DEBUG | default | [SERVER] PickToLoad  (0.000005 second [0.005030 ms])
2019-12-24 02:42:33,609 | DEBUG | default | [SERVER] PickToLoad  (0.000000 second [0.000232 ms])
2019-12-24 02:42:34,708 | DEBUG | default | [SERVER] CreateIndexRequest(table=anngist_1m_1024_960_l2): totally cost (2055.148897 seconds [2055148.896986 ms])

```

**Comment by BossZou** [comment]
I think it is because the network is unstable.
Closing it.
reopen if have more question.
