### ISSUE TITLE
Ut action timeout panic

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#7977]
#### Steps/Code to reproduce:

https://github.com/milvus-io/milvus/pull/7909/checks?check_run_id=3607219032

Possibly caused by this:

```go
 618283 2021-09-15T07:40:15.1455272Z goroutine 177 [chan receive, 9 minutes]:
 618284 2021-09-15T07:40:15.1455864Z testing.(*T).Run(0xc0003fb980, 0x2fad3d1, 0xf, 0xc001b99cc0, 0x1)
 618285 2021-09-15T07:40:15.1456474Z    /usr/local/go/src/testing/testing.go:1179 +0x7cf
 618286 2021-09-15T07:40:15.1457330Z github.com/milvus-io/milvus/internal/proxy.TestProxy(0xc0003fb980)
 618287 2021-09-15T07:40:15.1458289Z    /go/src/github.com/milvus-io/milvus/internal/proxy/proxy_test.go:1043 +0x39ca
 618288 2021-09-15T07:40:15.1458973Z testing.tRunner(0xc0003fb980, 0x30267e8)
 618289 2021-09-15T07:40:15.1459539Z    /usr/local/go/src/testing/testing.go:1127 +0x203
 618290 2021-09-15T07:40:15.1460049Z created by testing.(*T).Run
 618291 2021-09-15T07:40:15.1460558Z    /usr/local/go/src/testing/testing.go:1178 +0x797
```

proxy_test.go
```go
1043     t.Run("load collection", func(t *testing.T) {                                                             
1044         resp, err := proxy.LoadCollection(ctx, &milvuspb.LoadCollectionRequest{                               
1045             Base:           nil,                                                                              
1046             DbName:         dbName,                                                                           
1047             CollectionName: collectionName,                                                                   
1048         })                                                                                                    
1049         assert.NoError(t, err)                                                                                
1050         assert.Equal(t, commonpb.ErrorCode_Success, resp.ErrorCode)                                           
1051                                                                                                               
1052         // load other collection -> fail                                                                      
1053         resp, err = proxy.LoadCollection(ctx, &milvuspb.LoadCollectionRequest{                                
1054             Base:           nil,                                                                              
1055             DbName:         dbName,                                                                           
1056             CollectionName: otherCollectionName,                                                              
1057         })                                                                                                    
1058         assert.NoError(t, err)                                                                                
1059         assert.NotEqual(t, commonpb.ErrorCode_Success, resp.ErrorCode)                                        
1060                                                                                                               
1061         f := func() bool {                                                                                    
1062             resp, err := proxy.ShowCollections(ctx, &milvuspb.ShowCollectionsRequest{                         
1063                 Base:            nil,                                                                         
1064                 DbName:          dbName,                                                                      
1065                 TimeStamp:       0,                                                                           
1066                 Type:            milvuspb.ShowType_InMemory,                                                  
1067                 CollectionNames: []string{collectionName},                                                    
1068             })                                                                                                
1069             assert.NoError(t, err)                                                                            
1070             assert.Equal(t, commonpb.ErrorCode_Success, resp.Status.ErrorCode)                                
1071                                                                                                               
1072             for idx, name := range resp.CollectionNames {                                                     
1073                 if name == collectionName && resp.InMemoryPercentages[idx] == 100 {                           
1074                     return true                                                                               
1075                 }                                                                                             
1076             }                                                                                                 
1077                                                                                                               
1078             return false                                                                                      
1079         }                                                                                                     
1080                                                                                                               
1081         // waiting for collection to be loaded                                                                
1082         for f() {                                                                                             
1083         }                                                                                                     
1084     }) 
```

/assign @DragonDriver

**Comment by XuanYang-cn** [comment]
```go
 618283 2021-09-15T07:40:15.1455272Z goroutine 177 [chan receive, 9 minutes]:
 618284 2021-09-15T07:40:15.1455864Z testing.(*T).Run(0xc0003fb980, 0x2fad3d1, 0xf, 0xc001b99cc0, 0x1)
 618285 2021-09-15T07:40:15.1456474Z    /usr/local/go/src/testing/testing.go:1179 +0x7cf
 618286 2021-09-15T07:40:15.1457330Z github.com/milvus-io/milvus/internal/proxy.TestProxy(0xc0003fb980)
 618287 2021-09-15T07:40:15.1458289Z    /go/src/github.com/milvus-io/milvus/internal/proxy/proxy_test.go:1043 +0x39ca
 618288 2021-09-15T07:40:15.1458973Z testing.tRunner(0xc0003fb980, 0x30267e8)
 618289 2021-09-15T07:40:15.1459539Z    /usr/local/go/src/testing/testing.go:1127 +0x203
 618290 2021-09-15T07:40:15.1460049Z created by testing.(*T).Run
 618291 2021-09-15T07:40:15.1460558Z    /usr/local/go/src/testing/testing.go:1178 +0x797

```

**Comment by XuanYang-cn** [comment]
```
2021-09-16T03:24:13.2720341Z goroutine 162 [chan receive, 9 minutes]:
2021-09-16T03:24:13.2720846Z testing.(*T).Run(0xc000241b00, 0x29bb145, 0xf, 0xc000012480, 0x27fa501)
2021-09-16T03:24:13.2721345Z 	/usr/local/go/src/testing/testing.go:1179 +0x7cf
2021-09-16T03:24:13.2722443Z github.com/milvus-io/milvus/internal/indexcoord.TestIndexCoord(0xc000241b00)
2021-09-16T03:24:13.2723603Z 	/go/src/github.com/milvus-io/milvus/internal/indexcoord/index_coord_test.go:103 +0xa45
2021-09-16T03:24:13.2724194Z testing.tRunner(0xc000241b00, 0x2a1f7d0)
2021-09-16T03:24:13.2724664Z 	/usr/local/go/src/testing/testing.go:1127 +0x203
2021-09-16T03:24:13.2725273Z created by testing.(*T).Run
2021-09-16T03:24:13.2725703Z 	/usr/local/go/src/testing/testing.go:1178 +0x797
```

/assign @xiaocai2333
