### ISSUE TITLE
Nightly CI hangs for hours [cluster]

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#8360]
#### Steps/Code to reproduce:
https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/151/

Timeline:

[2021-09-22T16:30:45.303Z] [gw4] [ 75%] FAILED testcases/test_search_20.py::TestCollectionSearch::test_search_multi_collections[3000-2-128-False-True] 

[2021-09-23T01:01:12.215Z] [gw0] [ 75%] FAILED testcases/test_search_20.py::TestCollectionSearch::test_search_max_dim[2-False-True]

#### Expected result:
Tests run without hanging

#### Actual results:
Tests hangs for hours

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): 3759fa5
- Deployment mode(standalone or cluster):
cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
2.0.0rc7.dev4
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by DragonDriver** [comment]
Seems that network problem caused this issue. RootCoord didn't receive any request since 16:27:38.
You can retry this and reopen this if this issue was reproduced again.

**Comment by binbinlv** [comment]
OK，will close this first and reopen it if it occurs again.

And I think this also expose the timeout issue for sdk, so open an issue to track this #8402

**Comment by binbinlv** [comment]
Nightly tests hang again, so reopen this issue: [standalone]

https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/152/pipeline/46

**Comment by binbinlv** [comment]
@godchen0212 could you please help to investigating this issue? Thanks.

**Comment by binbinlv** [comment]
Test cases hangs again at both standalone and cluster mode:

https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/153/

pymilvus==2.0.0rc7.dev11 

standalone:

Timeline:
```
[2021-09-24T**16:48:01.**903Z] [gw2] [ 51%] FAILED testcases/test_search_20.py::TestCollectionSearch::test_search_index_partitions[5000-2-128-False-False] 

[2021-09-24T**19:32:38.**421Z] [gw4] [ 51%] FAILED testcases/test_search_20.py::TestCollectionSearch::test_search_max_dim[2-False-False] timeout: sending signal TERM to command '/home/jenkins/agent/workspace/tests/scripts/e2e.sh'
```

Cluster:
Timeline:

```
[2021-09-24T**19:13:53.**253Z] [gw3] [ 63%] XFAIL testcases/test_search_20.py::TestCollectionSearch::test_search_with_expression_bool[128-False-True-False] 

[2021-09-25T**01:50:07**.120Z] [gw5] [ 63%] FAILED testcases/test_search_20.py::TestCollectionSearch::test_search_with_output_fields_empty[5000-500-128-False-True] Sending interrupt signal to process
```

**Comment by binbinlv** [comment]
Test cases hangs again at cluster mode:
https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/154/


Timeline: hangs at the following time
```
[2021-09-25T**15:56:41.**999Z] testcases/test_search_20.py::TestCollectionSearch::test_search_index_partitions_fuzzy[3000-500-8-False-True-partition_names0]
```

**Comment by binbinlv** [comment]
Set this as urgent because it occurs several times continuously, and block Nightly CI tests.

**Comment by yanliang567** [comment]
it repos on master-20210925-9497ba5 and running against non_ci env.
I saw the data node crashed once before CI test hang.
[datanode.crash.log](https://github.com/milvus-io/milvus/files/7230900/datanode.crash.log)
[datanode.crash.previous.log](https://github.com/milvus-io/milvus/files/7230902/datanode.crash.previous.log)

**Comment by binbinlv** [comment]
It reproduced in latest nightly: [both standalone and cluster mode]

https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/155/

Timeline:
standalone:
```
[2021-09-26T17:35:18.360Z] [gw3] [ 55%] XFAIL testcases/test_search_20.py::TestCollectionSearch::test_search_with_expression_bool[8-False-False-True] 
[2021-09-26T20:57:06.450Z] [gw2] [ 55%] XFAIL testcases/test_search_20.py::TestCollectionSearch::test_search_binary_tanimoto_flat_index[2-8-False-True-BIN_FLAT] timeout: sending signal TERM to command '/home/jenkins/agent/workspace/tests/scripts/e2e.sh'
```

cluster:
```
2021-09-26T18:14:37.358Z] [gw0] [ 62%] FAILED testcases/test_search_20.py::TestCollectionSearch::test_search_with_output_fields[5000-500-8-True-False] 
[2021-09-27T01:50:07.258Z] [gw4] [ 62%] FAILED testcases/test_search_20.py::TestCollectionSearch::test_search_expression_all_data_type[5000-2-8-True-False] Sending interrupt signal 
```

**Comment by godchen0212** [comment]
It may be the heavy load caused by channel multiplexing.
![20210928-160621](https://user-images.githubusercontent.com/67679556/135052877-86d5de74-b554-4f1b-8a23-d4e36254ed04.png)
reference to issue #8568

**Comment by binbinlv** [comment]
It repros on last night's nightly:
https://ci.milvus.io:18080/jenkins/job/milvus-nightly-ci/job/master/161/

Standalone:
```

[2021-09-28T16:06:46.542Z] testcases/test_search_20.py::TestSearchBase::test_search_multi_collections 

[2021-09-28T18:58:58.272Z] [gw0] [ 79%] PASSED testcases/test_utility.py::TestUtilityParams::test_drop_collection_name_invalid[ ] timeout: sending signal TERM to command '/home/jenkins/agent/workspace/tests/scripts/e2e.sh'
```

Cluster:
timeline:
```
[2021-09-28T15:36:58.581Z] testcases/test_search_20.py::TestCollectionSearch::test_search_multiple_vectors[5000-500-128-True-False] 

[2021-09-29T00:59:39.083Z] [gw3] [ 57%] XFAIL testcases/test_search_20.py::TestCollectionSearch::test_search_with_expression_bool[8-True-False-True] timeout: sending signal TERM to command '/home/jenkins/agent/workspace/tests/scripts/e2e.sh'
```

@godchen0212  could you please investigate it again? Thanks.

**Comment by godchen0212** [comment]
The hang this time is different from the previous problem, the previous problem has been solved by another issue. This issue will continue to be followed up.

**Comment by binbinlv** [comment]
OK, great, thanks.

**Comment by godchen0212** [comment]
It is caused by the crash of proxy. The status is assigned before the result is constructed.
I will track the cause of this error. The hang problem may be sovled.

```
2021-09-28T15:32:52.293754669Z stdout F [2021/09/28 15:32:52.293 +00:00] [ERROR] [grpclog.go:55] ["[core]grpc: server failed to encode response: rpc error: code = Internal desc = grpc: error while marshaling: proto: Marshal called with nil"] [stack="google.golang.org/grpc/internal/grpclog.ErrorDepth\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/internal/grpclog/grpclog.go:55\ngoogle.golang.org/grpc/grpclog.(*componentData).ErrorDepth\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/grpclog/component.go:46\ngoogle.golang.org/grpc/internal/channelz.Error\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/internal/channelz/logging.go:87\ngoogle.golang.org/grpc.(*Server).sendResponse\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1077\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1321\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1609\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:934"]
2021-09-28T15:32:52.295681794Z stderr F panic: runtime error: invalid memory address or nil pointer dereference
2021-09-28T15:32:52.295696054Z stderr F [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15bc5c2]
2021-09-28T15:32:52.295700126Z stderr F 
2021-09-28T15:32:52.295705178Z stderr F goroutine 62521 [running]:
2021-09-28T15:32:52.295714596Z stderr F github.com/milvus-io/milvus/internal/proxy.(*searchTask).Execute(0xc0006938c0, 0x2768880, 0xc002a57ad0, 0x0, 0x0)
2021-09-28T15:32:52.295727857Z stderr F 	/go/src/github.com/milvus-io/milvus/internal/proxy/task.go:1662 +0x982
2021-09-28T15:32:52.295739558Z stderr F github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).processTask(0xc000408640, 0x277ed80, 0xc0006938c0, 0x277c6e0, 0xc000010698)
2021-09-28T15:32:52.295746399Z stderr F 	/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:449 +0x7d8
2021-09-28T15:32:52.295752979Z stderr F created by github.com/milvus-io/milvus/internal/proxy.(*taskScheduler).queryLoop
2021-09-28T15:32:52.295761808Z stderr F 	/go/src/github.com/milvus-io/milvus/internal/proxy/task_scheduler.go:499 +0x1d3
```

**Comment by binbinlv** [comment]
@godchen0212 
Ok, I will keep tracking.

**Comment by godchen0212** [comment]
After the above question is over, Proxy restart. Python sdk call *num_entities* method send *getPersistenceInfo* requests continuously till the end.
![WechatIMG41](https://user-images.githubusercontent.com/67679556/135232295-a81d8599-6523-4475-a58f-162d20750180.jpeg)
The DataNode may have encountered a pulsar problem leading to the failure of flush.
![1632904293698](https://user-images.githubusercontent.com/67679556/135232433-e2a4663d-6736-4821-bd4e-abaa5295bae4.jpg)

**Comment by binbinlv** [comment]
Update: the nightly CI last night did not hang.

**Comment by binbinlv** [comment]
So cancel the urgent label first, will close it after several days' verification.
