### ISSUE TITLE
[benchmark][cluster] Create index of IVF_FLAT or HNSW for 100 million data, report error “unexpected EOF”

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#9444]
#### Steps/Code to reproduce:
argo task:
**IVF_FLAT: index-1006-1633482000**
**HNSW: index-1002-1633136400**

test yaml:
```
IVF_FLAT: 
client-configmap: client-index-sift100m-ivf-flat-2048-perf
server-configmap: server-cluster-3rd-16c64m-indexnode-4
```
```
HNSW: 
client-configmap: client-index-sift100m-hnsw-ef500-perf
server-configmap: server-cluster-3rd-16c64m-indexnode-4
```

server deploy:
**IVF_FLAT:** 
```
NAME                                                           READY   STATUS      RESTARTS   AGE     IP             NODE                      NOMINATED NODE   READINESS GATES
index-1006-1633482000-1-etcd-0                                 1/1     Running     0          120m    10.97.16.187   qa-node013.zilliz.local   <none>           <none>
index-1006-1633482000-1-etcd-1                                 1/1     Running     0          120m    10.97.17.128   qa-node014.zilliz.local   <none>           <none>
index-1006-1633482000-1-etcd-2                                 1/1     Running     0          120m    10.97.16.188   qa-node013.zilliz.local   <none>           <none>
index-1006-1633482000-1-milvus-datacoord-698dc685cd-rzqx8      1/1     Running     0          120m    10.97.14.197   qa-node011.zilliz.local   <none>           <none>
index-1006-1633482000-1-milvus-datanode-797c79d457-mg7zl       1/1     Running     0          120m    10.97.14.193   qa-node011.zilliz.local   <none>           <none>
index-1006-1633482000-1-milvus-indexcoord-6d6f88474c-4x28g     1/1     Running     0          120m    10.97.14.196   qa-node011.zilliz.local   <none>           <none>
index-1006-1633482000-1-milvus-indexnode-6d974f9bdd-2c2dc      1/1     Running     0          120m    10.97.17.126   qa-node014.zilliz.local   <none>           <none>
index-1006-1633482000-1-milvus-indexnode-6d974f9bdd-wlj5j      1/1     Running     0          120m    10.97.10.30    qa-node008.zilliz.local   <none>           <none>
index-1006-1633482000-1-milvus-indexnode-6d974f9bdd-xhlp5      1/1     Running     0          120m    10.97.16.184   qa-node013.zilliz.local   <none>           <none>
index-1006-1633482000-1-milvus-indexnode-6d974f9bdd-zzxhj      1/1     Running     0          120m    10.97.11.66    qa-node009.zilliz.local   <none>           <none>
index-1006-1633482000-1-milvus-proxy-58854c47b4-kwr4c          1/1     Running     0          120m    10.97.14.194   qa-node011.zilliz.local   <none>           <none>
index-1006-1633482000-1-milvus-querycoord-c9f5b9ddd-9bj8c      1/1     Running     0          120m    10.97.10.29    qa-node008.zilliz.local   <none>           <none>
index-1006-1633482000-1-milvus-querynode-5fc6c44466-hgbm5      1/1     Running     0          120m    10.97.13.131   qa-node010.zilliz.local   <none>           <none>
index-1006-1633482000-1-milvus-rootcoord-5cc9465c4-h44rt       1/1     Running     0          120m    10.97.14.195   qa-node011.zilliz.local   <none>           <none>
index-1006-1633482000-1-minio-0                                1/1     Running     0          120m    10.97.14.187   qa-node011.zilliz.local   <none>           <none>
index-1006-1633482000-1-minio-1                                1/1     Running     0          120m    10.97.14.188   qa-node011.zilliz.local   <none>           <none>
index-1006-1633482000-1-minio-2                                1/1     Running     0          120m    10.97.14.189   qa-node011.zilliz.local   <none>           <none>
index-1006-1633482000-1-minio-3                                1/1     Running     0          38s     10.97.7.65     qa-node005.zilliz.local   <none>           <none>
index-1006-1633482000-1-pulsar-autorecovery-5c8747c974-w7h9n   1/1     Running     0          120m    10.97.7.63     qa-node005.zilliz.local   <none>           <none>
index-1006-1633482000-1-pulsar-bastion-6d479555cb-228bc        1/1     Running     0          120m    10.97.13.132   qa-node010.zilliz.local   <none>           <none>
index-1006-1633482000-1-pulsar-bookkeeper-0                    1/1     Running     0          120m    10.97.15.109   qa-node012.zilliz.local   <none>           <none>
index-1006-1633482000-1-pulsar-bookkeeper-1                    1/1     Running     0          118m    10.97.15.111   qa-node012.zilliz.local   <none>           <none>
index-1006-1633482000-1-pulsar-broker-7948797748-2c2wh         1/1     Running     0          120m    10.97.8.57     qa-node006.zilliz.local   <none>           <none>
index-1006-1633482000-1-pulsar-proxy-5ddfbbcf94-69htp          2/2     Running     0          120m    10.97.14.191   qa-node011.zilliz.local   <none>           <none>
index-1006-1633482000-1-pulsar-zookeeper-0                     1/1     Running     0          120m    10.97.15.110   qa-node012.zilliz.local   <none>           <none>
index-1006-1633482000-1-pulsar-zookeeper-1                     1/1     Running     0          119m    10.97.8.58     qa-node006.zilliz.local   <none>           <none>
index-1006-1633482000-1-pulsar-zookeeper-2                     1/1     Running     0          119m    10.97.8.59     qa-node006.zilliz.local   <none>           <none>
index-1006-1633482000-1-pulsar-zookeeper-metadata-t2m6x        0/1     Completed   0          120m    10.97.14.190   qa-node011.zilliz.local   <none>           <none>
```

**HNSW:** 
```
NAME                                                           READY   STATUS      RESTARTS   AGE    IP             NODE                      NOMINATED NODE   READINESS GATES
index-1002-1633136400-1-etcd-0                                 1/1     Running     0          163m   10.97.17.248   qa-node014.zilliz.local   <none>           <none>
index-1002-1633136400-1-etcd-1                                 1/1     Running     0          163m   10.97.16.11    qa-node013.zilliz.local   <none>           <none>
index-1002-1633136400-1-etcd-2                                 1/1     Running     0          163m   10.97.16.12    qa-node013.zilliz.local   <none>           <none>
index-1002-1633136400-1-milvus-datacoord-888f75489-kh4px       1/1     Running     0          163m   10.97.7.195    qa-node005.zilliz.local   <none>           <none>
index-1002-1633136400-1-milvus-datanode-fbb9f4468-blchs        1/1     Running     0          163m   10.97.10.227   qa-node008.zilliz.local   <none>           <none>
index-1002-1633136400-1-milvus-indexcoord-7f6f4c98c8-sqgml     1/1     Running     0          163m   10.97.7.198    qa-node005.zilliz.local   <none>           <none>
index-1002-1633136400-1-milvus-indexnode-69c7d8c4f9-c8t9z      1/1     Running     0          163m   10.97.13.49    qa-node010.zilliz.local   <none>           <none>
index-1002-1633136400-1-milvus-indexnode-69c7d8c4f9-nrgwx      1/1     Running     0          163m   10.97.17.246   qa-node014.zilliz.local   <none>           <none>
index-1002-1633136400-1-milvus-indexnode-69c7d8c4f9-rdgvj      1/1     Running     0          163m   10.97.15.61    qa-node012.zilliz.local   <none>           <none>
index-1002-1633136400-1-milvus-indexnode-69c7d8c4f9-z9c2r      1/1     Running     0          163m   10.97.14.74    qa-node011.zilliz.local   <none>           <none>
index-1002-1633136400-1-milvus-proxy-d956df985-4hjcd           1/1     Running     0          163m   10.97.8.235    qa-node006.zilliz.local   <none>           <none>
index-1002-1633136400-1-milvus-querycoord-865d459fbf-jxs4z     1/1     Running     0          163m   10.97.8.236    qa-node006.zilliz.local   <none>           <none>
index-1002-1633136400-1-milvus-querynode-84444969f7-zd78v      1/1     Running     0          163m   10.97.16.8     qa-node013.zilliz.local   <none>           <none>
index-1002-1633136400-1-milvus-rootcoord-8f47d965-m9q6v        1/1     Running     0          163m   10.97.14.73    qa-node011.zilliz.local   <none>           <none>
index-1002-1633136400-1-minio-0                                1/1     Running     0          44s    10.97.11.3     qa-node009.zilliz.local   <none>           <none>
index-1002-1633136400-1-minio-1                                1/1     Running     0          163m   10.97.7.194    qa-node005.zilliz.local   <none>           <none>
index-1002-1633136400-1-minio-2                                1/1     Running     0          163m   10.97.7.197    qa-node005.zilliz.local   <none>           <none>
index-1002-1633136400-1-minio-3                                1/1     Running     0          163m   10.97.10.226   qa-node008.zilliz.local   <none>           <none>
index-1002-1633136400-1-pulsar-autorecovery-7ffdccbb7d-74ldk   1/1     Running     0          163m   10.97.8.234    qa-node006.zilliz.local   <none>           <none>
index-1002-1633136400-1-pulsar-bastion-64cdf9fb7b-kvsqn        1/1     Running     0          163m   10.97.7.199    qa-node005.zilliz.local   <none>           <none>
index-1002-1633136400-1-pulsar-bookkeeper-0                    1/1     Running     0          163m   10.97.8.238    qa-node006.zilliz.local   <none>           <none>
index-1002-1633136400-1-pulsar-bookkeeper-1                    1/1     Running     0          161m   10.97.7.203    qa-node005.zilliz.local   <none>           <none>
index-1002-1633136400-1-pulsar-broker-74fd85bcb-4xrtj          1/1     Running     0          163m   10.97.7.200    qa-node005.zilliz.local   <none>           <none>
index-1002-1633136400-1-pulsar-proxy-6446cb9f78-dkf5p          2/2     Running     0          163m   10.97.14.75    qa-node011.zilliz.local   <none>           <none>
index-1002-1633136400-1-pulsar-zookeeper-0                     1/1     Running     0          163m   10.97.8.237    qa-node006.zilliz.local   <none>           <none>
index-1002-1633136400-1-pulsar-zookeeper-1                     1/1     Running     0          162m   10.97.7.201    qa-node005.zilliz.local   <none>           <none>
index-1002-1633136400-1-pulsar-zookeeper-2                     1/1     Running     0          162m   10.97.7.202    qa-node005.zilliz.local   <none>           <none>
index-1002-1633136400-1-pulsar-zookeeper-metadata-k5gt2        0/1     Completed   0          163m   10.97.7.196    qa-node005.zilliz.local   <none>           <none>
```

client log:
```
[2021-10-02 02:32:33,530] [    INFO] - Building index start, collection_name: sift_100m_128_l2, index_type: HNSW, metric_type: L2 (milvus_benchmark.client:263)
[2021-10-02 02:32:33,530] [    INFO] - {'M': 16, 'efConstruction': 500} (milvus_benchmark.client:265)
[2021-10-02 02:32:33,530] [   DEBUG] - collection: sift_100m_128_l2 Index params: {'index_type': 'HNSW', 'metric_type': 'L2', 'params': {'M': 16, 'efConstruction': 500}} (milvus_benchmark.client:271)
[2021-10-02 03:42:56,324] [   ERROR] - Error: <BaseException: (code=1, message=unexpected EOF)> (pymilvus.client.grpc_handler:59)
[2021-10-02 03:42:56,333] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 91, in run_suite
    result = runner.run_case(case_metric, **case)
  File "/src/milvus_benchmark/runners/build.py", line 76, in run_case
    index_param=case_param["index_param"])
  File "/src/milvus_benchmark/client.py", line 46, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 272, in create_index
    res = self._milvus.create_index(tmp_collection_name, field_name, index_params, _async=_async)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 61, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 45, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 832, in create_index
    return handler.create_index(collection_name, field_name, params, timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 757, in create_index
    raise BaseException(Status.UNEXPECTED_ERROR, fail_reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=unexpected EOF)>
 (milvus_benchmark.main:94)
[2021-10-02 03:42:56,334] [    INFO] - None (milvus_benchmark.main:95)
[2021-10-02 03:42:56,334] [   DEBUG] - {'type': 'insert_build_performance', 'value': {}} (milvus_benchmark.main:103)
```

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-2.0.0rc7.dev18
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by yanliang567** [comment]
remove urgent as it reproduces occasionally.

**Comment by yanliang567** [comment]
moving to backlog, since
1. it does not repro recently
2. going to upgrade a newer minio to start more metrics in monitoring
