### ISSUE TITLE
[Bug]: BaseException: (code=1, message=CreateIndex Timeout)

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#9623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I running test cases L0 and L1 under multiple nodes (replica = 2) env (cluster etcd, minio, pulsar), it reports error:

pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=CreateIndex Timeout)>

Error timeline:
2021-10-11 07:04:57: sent create index request
2021-10-11 07:05:18:  CreateIndex Timeout

```
[2021-10-11 07:04:57 - DEBUG - ci_test]: (api_request)  : [Collection.create_index] args: ['float_vector', {'index_type': 'IVF_FLAT', 'params': {'nlist': 128}, 'metric_type': 'L2'}], kwargs: {'timeout': 20} (api_request.py:44)
[2021-10-11 07:05:18 - ERROR - pymilvus.client.grpc_handler]: Error: <BaseException: (code=1, message=CreateIndex Timeout)> (grpc_handler.py:59)
[2021-10-11 07:05:18 - ERROR - pymilvus.client.grpc_handler]: Error: <BaseException: (code=1, message=CreateIndex Timeout)> (grpc_handler.py:59)
[2021-10-11 07:05:18 - ERROR - ci_test]: Traceback (most recent call last):
  File "/milvus/tests/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/milvus/tests/python_client/utils/api_request.py", line 45, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 1028, in create_index
    timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 61, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 45, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 832, in create_index
    return handler.create_index(collection_name, field_name, params, timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 759, in create_index
    field_name=field_name, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 815, in wait_for_creating_index
    raise BaseException(1, "CreateIndex Timeout")
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=CreateIndex Timeout)>
 (api_request.py:26)
[2021-10-11 07:05:18 - ERROR - ci_test]: (api_response) : <BaseException: (code=1, message=CreateIndex Timeout)> (api_request.py:27)
```

```
FAILED test_search_20.py::TestCollectionSearchInvalid::test_search_index_partition_not_existed - AssertionError

Results (2687.56s):
    2265 passed
      33 xpassed
       1 failed
         - testcases/test_search_20.py:562 TestCollectionSearchInvalid.test_search_index_partition_not_existed
       6 xfailed
      61 skipped
```

### Expected Behavior

No timeout reports and index was created successfully

### Steps To Reproduce

```markdown
1. replica = 2, and etcd, minio and pulsar are cluster mode
2. Running L0 and L1 test cases
```

### Environment

```markdown
- Milvus version: 1bc4b36
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.0rc7.dev22
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

**Comment by binbinlv** [comment]
please ping me to get the logs, thanks.

**Comment by binbinlv** [comment]
Similar issue occurs in nightly:

Timeline;
```
[2021-11-30T02:46:48.611Z] [gw1] [ 54%] FAILED testcases/test_search_20.py::TestCollectionSearch::test_search_after_different_index_with_params[128-True-False-IVF_SQ8-params2] 
```

Failed collection name: 
search_collection_ihUf0shk

Case parameter: dim = 128, index = 'IVF_SQ8', params = {'nlist': 128}, auto_id = True, _async = False

Milvus Logs: [cluster]
https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/236/artifacts/

Test logs:
https://ci.milvus.io:18080/jenkins/blue/rest/organizations/jenkins/pipelines/milvus-nightly-ci/branches/master/runs/236/nodes/121/steps/129/log/?start=0

```
  File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
    res = func(*args, **kwargs)
  File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 56, in api_request
    return func(*arg, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/orm/collection.py", line 1044, in create_index
    timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 58, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 42, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 810, in create_index
    return handler.create_index(collection_name, field_name, params, timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 771, in create_index
    field_name=field_name, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 75, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 67, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 827, in wait_for_creating_index
    raise BaseException(1, "CreateIndex Timeout")
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=CreateIndex Timeout)>
```

**Comment by xiaocai2333** [comment]
> According to the log, when the wrong building the index, another case was also building the index(maybe it's asynchronous). And the another case building index is slow, blocked the case causes it to time out.
> 
> Maybe we should optimize the test case? @czs007

Maybe we can increase the timeout now to solve this problem. @yanliang567 @czs007

**Comment by yanliang567** [comment]
/assign @binbinlv 
@binbinlv I have added the indexing timeout to 40s, does it still repro
/unassign

**Comment by binbinlv** [comment]
Reproducing.

**Comment by binbinlv** [comment]
It has not been reproduced for a period of days, so close it first, will reopen it if it occurs latter.
