### ISSUE TITLE
[Bug]: [benchmark][standalone] collection has not been loaded to memory or load failed

### ISSUE THREAD

**Issue by wangting0128** [milvus-io/milvus#9872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`Inserting 50 million data, only 27.9 million data was inserted successfully, and an error of "code=1, message=rpc error: code = Unknown desc = collection has not been loaded to memory or load failed" was reported during load collection`

client log:
[client.log](https://github.com/milvus-io/milvus/files/7343784/client.log)
```
[2021-10-14 06:20:50,329] [   DEBUG] - Row count: 27900000 in collection: <local_50m_512_l2> (milvus_benchmark.client:403)
[2021-10-14 06:20:50,330] [   DEBUG] - 27900000 (milvus_benchmark.runners.base:89)
[2021-10-14 06:20:50,331] [    INFO] - {'total_time': 4744.53, 'rps': 10538.46, 'ni_time': 4.74} (milvus_benchmark.runners.base:151)
[2021-10-14 06:20:52,864] [   DEBUG] - Milvus flush run in 2.06s (milvus_benchmark.client:52)
[2021-10-14 06:20:52,866] [   DEBUG] - Row count: 27900000 in collection: <local_50m_512_l2> (milvus_benchmark.client:403)
[2021-10-14 06:20:52,867] [   DEBUG] - {'collection count': 27900000} (milvus_benchmark.runners.get:117)
[2021-10-14 06:20:52,867] [   DEBUG] - {'flush_time': 2.06} (milvus_benchmark.runners.get:118)
[2021-10-14 06:20:52,867] [   DEBUG] - Start load collection (milvus_benchmark.runners.get:119)
[2021-10-14 06:28:12,998] [   ERROR] - Error: <BaseException: (code=1, message=rpc error: code = Unknown desc = collection has not been loaded to memory or load failed)> (pymilvus.client.grpc_handler:59)
[2021-10-14 06:28:13,007] [   ERROR] - Error: <BaseException: (code=1, message=rpc error: code = Unknown desc = collection has not been loaded to memory or load failed)> (pymilvus.client.grpc_handler:59)
[2021-10-14 06:28:13,007] [   ERROR] - <BaseException: (code=1, message=rpc error: code = Unknown desc = collection has not been loaded to memory or load failed)> (milvus_benchmark.main:114)
[2021-10-14 06:28:13,011] [   ERROR] - Traceback (most recent call last):
  File "main.py", line 83, in run_suite
    runner.prepare(**cases[0])
  File "/src/milvus_benchmark/runners/get.py", line 120, in prepare
    self.milvus.load_collection(timeout=1200)
  File "/src/milvus_benchmark/client.py", line 48, in wrapper
    result = func(*args, **kwargs)
  File "/src/milvus_benchmark/client.py", line 465, in load_collection
    return self._milvus.load_collection(collection_name, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 61, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 45, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/stub.py", line 330, in load_collection
    return handler.load_collection("", collection_name=collection_name, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 824, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 65, in handler
    raise e
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 57, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 842, in wait_for_loading_collection
    return self._wait_for_loading_collection_v2(collection_name, timeout)
  File "/usr/local/lib/python3.6/site-packages/pymilvus/client/grpc_handler.py", line 869, in _wait_for_loading_collection_v2
    raise BaseException(response.status.error_code, response.status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=rpc error: code = Unknown desc = collection has not been loaded to memory or load failed)>
 (milvus_benchmark.main:115)
```

server:
```
NAME: benchmark-cluster-cron-ngx6r-1
LAST DEPLOYED: Thu Oct 14 03:23:10 2021
NAMESPACE: qa-milvus
STATUS: deployed
REVISION: 1
TEST SUITE: None
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /root/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /root/.kube/config
I1014 03:24:31.274096      26 request.go:665] Waited for 1.095931539s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.local/apis/serving.knative.dev/v1beta1?timeout=32s
I1014 03:24:41.274282      26 request.go:665] Waited for 11.090513627s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc.cluster.local/apis/networking.internal.knative.dev/v1alpha1?timeout=32s
NAME                                                              READY   STATUS      RESTARTS   AGE   IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-cluster-cron-ngx6r-1-etcd-0                             1/1     Running     0          94s   10.97.17.170   qa-node014.zilliz.local   <none>           <none>
benchmark-cluster-cron-ngx6r-1-milvus-standalone-6c94bdc7ch8zqq   1/1     Running     0          94s   10.97.17.166   qa-node014.zilliz.local   <none>           <none>
benchmark-cluster-cron-ngx6r-1-minio-595c6767f4-q7hvm             1/1     Running     0          94s   10.97.10.9     qa-node008.zilliz.local   <none>           <none>
```

### Steps To Reproduce

```markdown
argo task: benchmark-cluster-cron-ngx6r

test yaml:
client-configmap: client-get-local50m-512
server-configmap: server-single-16c64m
```

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-2.0.0rc7.dev23
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

**Comment by wangting0128** [comment]
update server config：server-single-32c128m
client config：client-get-local50m-512

Verified.
